### ISSUE TITLE
"Not sufficient disk space" error when recording to a samba share on macOS

### ISSUE THREAD

**Issue by rdd** [obsproject/obs-studio#10005]
### Operating System Info

macOS 13

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/56g5GjnxOSYnngej

### Expected Behavior

Recording to samba mounted directory to start.
This has worked fine up to and including 30.0.0, but fails on 30.0.1 and 30.0.2.

### Current Behavior

Recording fails to start, displaying a dialog with "There is not sufficient disk space to continue recording".
The samba share I'm attempting to record to has 2.7 TB free space.
If I change the recording output location to local disk with ~90 GB free space recording starts as expected.
After downgrading OBS to 30.0.0 recording to the samba share works again.

### Steps to Reproduce

1. Configure recording output to a directory on a samba share on macOS.
2. Attempt to start recording.

### Anything else we should know?

I'm assuming this is related to the macOS free disk check work done in https://github.com/obsproject/obs-studio/pull/9881

**Comment by tt2468** [comment]
Fixed in https://github.com/obsproject/obs-studio/commit/4a765d3bf028209ba8f13ec7ca93380c45d9511d

**Comment by rdd** [comment]
Yes, indeed, looks like #9996 will address my issue, thanks.
Closing this one.
