### ISSUE TITLE
OBS 30.0.2 Could not find virtual camera

### ISSUE THREAD

**Issue by agilebean** [obsproject/obs-studio#10001]
### Operating System Info

macOS 14

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/aAMlnVRBf4ClNemF

### Expected Behavior

Start Virtual Camera : should start without error message

### Current Behavior

Start Virtual Camera: Error message below is shown
<img width="1071" alt="image" src="https://github.com/obsproject/obs-studio/assets/28497542/51f757ca-2ed3-4b5b-86c0-6244ce19966a">

### Steps to Reproduce

1. Download OBS 30.0.2 for Apple Silicon
2. Open OBS Studio
3. Click on "Start Virtual Camera"
...

### Anything else we should know?

MacOS is 14.2

**Comment by gxalpha** [comment]
Try logging out of your account and logging back in. Alternatively, reboot your Mac.

**Comment by agilebean** [comment]
@gxalpha Thanks, rebooting did the trick - logging out&in wasn't enough.

Now, the virtual camera streaming directly from OBS works. However, it doesn't work when I try to access it programmatically. Why? Has the interface changed?

I use this code (which worked before):
```
        try:
            # set standard dimensions, see https://github.com/letmaik/pyvirtualcam/issues/110#issuecomment-1624273288
            self.virtualcam = pyvirtualcam.Camera(
                width=1280,
                height=720,
                fps=30,
                device="OBS Virtual Camera",
                fmt=pyvirtualcam.PixelFormat.BGR
            )
            logging.info(f'Using virtual camera: {self.virtualcam.device}')
            logging.info(
                f' with dimensions: {self.virtualcam.width}x{self.virtualcam.height} @fps {self.virtualcam.fps}')
        except RuntimeError as e:
            logging.error(f"OBS Virtual Camera is not available: {e}")
            self.virtualcam = None
```
which now throws:
```
ERROR: OBS Virtual Camera is not available: 'obs' backend: OBS Virtual Camera is not installed in your system. Use the Virtual Camera function in OBS to trigger installation.
```

**Comment by gxalpha** [comment]
You opened such an issue before: https://github.com/obsproject/obs-studio/issues/9680#issuecomment-1765758754
The answer I gave back then hasn't changed, this is something that pyvirtualcam needs to address, preferably by writing their own virtualcam backend.

**Comment by agilebean** [comment]
@gxalpha Yes, you are right. However, the crucial question in my previous comment was:

Does OBS have a programmatic interface to the virtual camera?

I looked at the API docs of OBS, but I couldn't identify any method that resembles `send(frame)`. 

But this must be possible, otherwise `pyvirtualcam` wouldn't be able to access the virtualcam via OBS, would it?

**Comment by gxalpha** [comment]
> Does OBS have a programmatic interface to the virtual camera?

No.

> But this must be possible

No, it doesn't have to be.

> otherwise pyvirtualcam wouldn't be able to access the virtualcam via OBS, would it?

Correct, but OBS does not maintain pyvirtualcam. Please ask them.
