### ISSUE TITLE
Intel Arc - No AV1 Streaming Option

### ISSUE THREAD

**Issue by jadenquinn** [obsproject/obs-studio#10012]
### Operating System Info

Windows 10

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/BkjuoKWo21hjNjMx

### Expected Behavior

I expected the option for AV1 to appear under the codec options for Streaming, not just Recording.

### Current Behavior

AV1 options only appeared in Recording, and not the Streaming tab.

### Steps to Reproduce

1. Buy Arc.
2. Download OBS.
3. Question your life choices.

### Anything else we should know?

I'm not saying there isn't a hardware option, I'm saying there are NO OPTIONS for AV1 streaming in OBS for me. There's only two options, and they're both H.264, one is SW and the other is QSV HW.

**Comment by derrod** [comment]
AV1 streaming is currently only supported by YouTube.
