### ISSUE TITLE
VLC sources being deinterlaced by VLC automatically

### ISSUE THREAD

**Issue by gllxflr** [obsproject/obs-studio#10016]
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.0.0

### OBS Studio Log URL

N/A (no relevant log messages)

### Expected Behavior

OBS receives a 50 fields per second interlaced video from the VLC source, as is consistent with the source.

### Current Behavior

OBS receives and displays a 25 fps progressive video from the VLC source, rather badly deinterlaced.

### Steps to Reproduce

1. Make a VLC Video source
2. Set the input to an interlaced video or stream (for example, a DVD or IPTV link)
3. Observe the output. It is progressive at half the field rate of the original, and OBS's own deinterlace options have no effect.

### Anything else we should know?

From my troubleshooting, it seems to have started in OBS 28 or 29 (although I have not tested older versions), and it seems to be fixable by telling libvlc not to deinterlace, although I do not know quite how

**Comment by Fenrirthviti** [comment]
Please include a log file, even if you don't feel it's relevant. There's a reason it's a required field.

**Comment by gllxflr** [comment]
I'll provide one tommorow, although from what I've seen it happens on completely default config across all platforms

**Comment by gxalpha** [comment]
No log has been provided. We can reopen in the future.
