### ISSUE TITLE
Release 30.0.2 missed DEBs for specified Ubuntu versions

### ISSUE THREAD

**Issue by krom** [obsproject/obs-studio#10013]
### Operating System Info

Other

### Other OS

Ubuntu 23.10

### OBS Studio Version

30.0.2

### OBS Studio Log URL

nope

### Expected Behavior

```
$ lsb_release -a                                              
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 23.10
Release:        23.10
Codename:       mantic

/tmp ⌚ 14:50:31
$ sudo dpkg -i obs-studio_30.0.2-0obsproject1.mantic_amd64.deb
(Reading database ... 490940 files and directories currently installed.)
Preparing to unpack obs-studio_30.0.1-0obsproject1.mantic_amd64.deb ...
Unpacking obs-studio (30.0.2-0obsproject1~mantic) over (30.0.1-0obsproject1~mantic) ...
Setting up obs-studio (30.0.2-0obsproject1~mantic) ...
Processing triggers for libc-bin (2.38-1ubuntu6) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu5) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
```

### Current Behavior

```
/tmp ⌚ 14:48:54
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 23.10
Release:        23.10
Codename:       mantic

/tmp ⌚ 14:48:56
$ sudo dpkg -i OBS-Studio-30.0.2-Ubuntu-x86_64.deb 
(Reading database ... 490940 files and directories currently installed.)
Preparing to unpack OBS-Studio-30.0.2-Ubuntu-x86_64.deb ...
Unpacking obs-studio (30.0.2-1) over (30.0.1-0obsproject1~mantic) ...
dpkg: dependency problems prevent configuration of obs-studio:
 obs-studio depends on libavcodec58 (>= 7:4.4); however:
  Package libavcodec58 is not installed.
 obs-studio depends on libavdevice58 (>= 7:4.4); however:
  Package libavdevice58 is not installed.
 obs-studio depends on libavformat58 (>= 7:4.4); however:
  Package libavformat58 is not installed.
 obs-studio depends on libavutil56 (>= 7:4.4); however:
  Package libavutil56 is not installed.
 obs-studio depends on libpython3.10 (>= 3.10.0); however:
  Package libpython3.10 is not installed.
 obs-studio depends on libswresample3 (>= 7:4.4); however:
  Package libswresample3 is not installed.
 obs-studio depends on libswscale5 (>= 7:4.4); however:
  Package libswscale5 is not installed.
 obs-studio depends on libx264-163 (>= 2:0.163.3060+git5db6aa6); however:
  Package libx264-163 is not installed.

dpkg: error processing package obs-studio (--install):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.38-1ubuntu6) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for mailcap (3.70+nmu1ubuntu1) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu5) ...
Errors were encountered while processing:
 obs-studio
```

### Steps to Reproduce

1. Install Ubuntu 23.10
2. Download DEB package
3. Install package

### Anything else we should know?

*Release 30.0.1 contains  those assets*
- [OBS-Studio-30.0.1-Ubuntu-x86_64-dbsym.ddeb](https://github.com/obsproject/obs-studio/releases/download/30.0.1/OBS-Studio-30.0.1-Ubuntu-x86_64-dbsym.ddeb)
- [OBS-Studio-30.0.1-Ubuntu-x86_64.deb](https://github.com/obsproject/obs-studio/releases/download/30.0.1/OBS-Studio-30.0.1-Ubuntu-x86_64.deb)
- **[obs-studio_30.0.1-0obsproject1.jammy_amd64.deb](https://github.com/obsproject/obs-studio/releases/download/30.0.1/obs-studio_30.0.1-0obsproject1.jammy_amd64.deb)**
- **[obs-studio_30.0.1-0obsproject1.lunar_amd64.deb](https://github.com/obsproject/obs-studio/releases/download/30.0.1/obs-studio_30.0.1-0obsproject1.lunar_amd64.deb)**
- **[obs-studio_30.0.1-0obsproject1.mantic_amd64.deb](https://github.com/obsproject/obs-studio/releases/download/30.0.1/obs-studio_30.0.1-0obsproject1.mantic_amd64.deb)**

*But, release 30.0.2 contains only those assets*
- [OBS-Studio-30.0.2-Ubuntu-x86_64-dbsym.ddeb](https://github.com/obsproject/obs-studio/releases/download/30.0.2/OBS-Studio-30.0.2-Ubuntu-x86_64-dbsym.ddeb)
- [OBS-Studio-30.0.2-Ubuntu-x86_64.deb](https://github.com/obsproject/obs-studio/releases/download/30.0.2/OBS-Studio-30.0.2-Ubuntu-x86_64.deb)

But OBS-Studio-30.0.2-Ubuntu-x86_64.deb does not suitable for latest versions of Ubuntu

**Could you please include packages for jammy, lunar and mantic into release**

**Comment by tytan652** [comment]
Ubuntu releases are available on OBS Project PPA, Github release is not an supported install method.

**Comment by Gol-D-Ace** [comment]
As a note.
OBS 30.0.1 and 30.0.2 would be the exact same code anyways because 30.0.2 doesn't contain any changes that affect Linux.
