### ISSUE TITLE
High FPS (>120) does not work on the new OBS versions (after around 27.2.4)

### ISSUE THREAD

**Issue by zorroseven** [obsproject/obs-studio#10015]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/SpoZdDReRP4R9IVO

### Expected Behavior

Upon entering Settings->Video->(Fractional FPS Value)-> Numerator ">120" (i.e. 240) and Denominator at "1", I expect my recorded videos to return a video output which has an FPS value at my desired value (say, 240FPS).

### Current Behavior

This simply does not work and results in videos that are either very stuttery or will just not even record and only works at values 120 or lower. I also get the message that there's an "encoding overload" as well. This however is a non-issue at the older OBS versions 27.2.4 and 27.2.3 works just fine for me. 

### Steps to Reproduce

1. Default FPS value is 60FPS, for the minority of people who desire to have >60FPS, you normally change that in the Settings->Video->(Fractional FPS Value)-> Numerator & Denominator tab.
2. You then insert your desired FPS value by changing the Numerator value to >120FPS (say, 180/240/360, etc), while the Denominator stays at 1.
3. Upon trying to record or do a replay buffer (saves x amount of seconds, same as Nvidia's Shadowplay), it either doesn't work at all or the video file results in a stuttery mess, not at all what you would expect and it never happens on the older versions mentioned above (27.2.4 and 27.2.3, these work as intended).

**Comment by prgmitchell** [comment]
This would be a result of your configuration (settings, other factors). If you would like assistance with this, please head over to the community [Discord](https://discord.com/invite/obsproject) or the [OBS Forums](https://obsproject.com/forum/).

**Comment by zorroseven** [comment]
> This would be a result of your configuration (settings, other factors). If you would like assistance with this, please head over to the community [Discord](https://discord.com/invite/obsproject) or the [OBS Forums](https://obsproject.com/forum/).

Even if it's solved by a change in settings, I 1:1'd the settings on both versions, why shouldn't it work on the newer ones like it does on the older ones? Seems weird to me.

**Comment by Delezatro** [comment]
Same issue here. Recording in 120 FPS works fine but at 240 FPS, the end result is a stuttery mess. I remember this working fine in an older version from last year at least.

**Comment by derrod** [comment]
Use a faster preset.

> Even if it's solved by a change in settings, I 1:1'd the settings on both versions, why shouldn't it work on the newer ones like it does on the older ones? Seems weird to me.

You can't 1:1 the settings because those old versions don't use the same presets (P1-7), which behave differently from the old NVENC rpesets.
