### ISSUE TITLE
Recording Fails with error - Wayland does not support QWindow::requestActivate()

### ISSUE THREAD

**Issue by amal-qb** [obsproject/obs-studio#10027]
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.0.1

### OBS Studio Log URL

https://obsproject.com/logs/s4YNOKUII1oaIaCm

### OBS Studio Crash Log URL

https://obsproject.com/logs/s4YNOKUII1oaIaCm

### Expected Behavior

The recording should start with no errors.

### Current Behavior

The recording doesn't start and shows an error popup:

![image](https://github.com/obsproject/obs-studio/assets/122610766/4c27e529-037b-448c-bd36-b6c0961bf3ca)

### Steps to Reproduce

1. Follow the "Ubuntu Instructions (20.04+)" section on [OBS Download](https://obsproject.com/download) page to install OBS.
2. Open OBS Studio and add a "Screen Capture (PipeWire)" source.
3. Click "Start Recording".

**Comment by tytan652** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for further assistance.

Thank you!
