### ISSUE TITLE
OBS Browser Source CEF version is extremely outdated 

### ISSUE THREAD

**Issue by mrmcpowned** [obsproject/obs-studio#10020]
### Operating System Info

macOS 14

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/B6K7JGJ9nbmLdKyK

### Expected Behavior

1. Create a new browser source
2. Set the url to https://toolbox.googleapps.com/apps/browserinfo/
3. See the "User Agent" field include the substring "Chrome/120.0.0.0"

### Current Behavior

User Agent does not include "Chrome/120.0.0.0" and is instead "Chrome/103.0.5060.134"

### Steps to Reproduce

1. Create a new browser source
2. Set the url to https://toolbox.googleapps.com/apps/browserinfo/
3. Observe value under "User Agent"

### Anything else we should know?

OBS's CEF package is severely out of date. So out of date, that there have been [398 vulnerabilities found](https://www.cvedetails.com/vulnerability-list/vendor_id-1224/product_id-15031/version_id-1043262/Google-Chrome-103.0.5060.134.html) since its release.

This needs to be updated and hotfixed as soon as possible, because the longer this is left at v103, the more every OBS user becomes a target for malicious activities.

**Comment by WizardCM** [comment]
Our copy of CEF is patched with security fixes, but unfortunately cannot be updated outright due to our requirements for texture sharing. See https://github.com/obsproject/obs-studio/issues/8657#issuecomment-1496905026
