### ISSUE TITLE
there is no way to change an output timer without stopping your stream

### ISSUE THREAD

**Issue by marktheminer** [obsproject/obs-studio#10026]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.2

### OBS Studio Log URL

n/a

### Expected Behavior

If you start an output timer, you should be able to stop the timer without stopping your stream.  However, stopping the timer stops the stream (and with no warning).  In addition, you can't change the timer because to change it you have to press enter which then triggers the stop timer button which then stops the stream.

### Current Behavior

If you start an output timer, you should be able to stop the timer without stopping your stream.  However, stopping the timer stops the stream (and with no warning).  In addition, you can't change the timer because to change it you have to press enter which then triggers the stop timer button which then stops the stream.

### Steps to Reproduce

1.  open the stream timer, set it to 30 minutes and press start
2.  your stream goes live (which is also kind of odd, seems like it should be disabled until you start your stream, but that's an aside)
3.  try to stop the timer or change the value to 31 minutes
...

**Comment by marktheminer** [comment]
https://obsproject.com/forum/threads/how-to-cancel-or-change-the-output-timer-once-started.137102/

**Comment by gxalpha** [comment]
This is working as designed. Arguably, this isn't a great design, but this isn't a bug.

As a note, we're looking at (potentially!) completely redesigning this feature, but can't give any more details or an ETA for that at this time.
