### ISSUE TITLE
Preview camera stutters when there is a different camera in live view

### ISSUE THREAD

**Issue by nospam2k** [obsproject/obs-studio#10025]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/0Z3tOrgdZ1QafwAg

### Expected Behavior

Both cameras should function normally with no stuttering

### Current Behavior

The preview camera will randomly stutter as if it's losing connection or cpu overload (USB cameras in use).

### Steps to Reproduce

1. Add two usb cameras to two different scenes.
2. Place one scene with one camera in live and the other scene with the other camera in preview.
3. The live camera will be fine, but the preview camera (doesn't matter which one) will freeze for a second randomly.

### Anything else we should know?

I've noticed this has been happening since v28. I upgraded to v28 and started seeing and went back to v27 (IIRC). I eventually upgraded to v28 and just lived with the stuttering on preview thinking that maybe my machine just wasn't powerful enough to keep up and the output stream was fine. I just upgraded to a much more powerful machine (i9, 32gb, nvme drive, RTX video card) and the stuttering is still happening. I didn't include a log because there is no error or crashing, but I can add if it is helpful.

**Comment by Penwy** [comment]
That is very likely a support request rather than a bug, most likely USB bandwidth issues.
I'd suggest you use either the [forums](https://obsproject.com/fourm/) or the [discord](https://obsproject.com/discord/) for support

**Comment by nospam2k** [comment]
Will do
