### ISSUE TITLE
OpenGL 3.1 no longer works to record with QuickSync

### ISSUE THREAD

**Issue by UnderscoreAngel** [obsproject/obs-studio#10032]
### Operating System Info

Windows 10

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/Ts44WvpK0JPlMvQP

### Expected Behavior

Record normally using QuickSync H.264

### Current Behavior

![imagen](https://github.com/obsproject/obs-studio/assets/105066360/f27ad303-4927-4ec5-b6dc-5cc427550c0e)
upon recording throws an error of "outdated video card" which didn't happen in older verisons

### Steps to Reproduce

1. Use Intel HD 3000 Graphics
2. Use QuickSync as Encoder
3. Try to record.

### Anything else we should know?

another example of... "if it's not broken, don't fix it"

**Comment by UnderscoreAngel** [comment]
and yes that is Windows 10 21H2 i just have a Windows 7 Skin on

**Comment by Fenrirthviti** [comment]
I'm unsure what OpenGL has to do with this report, the OpenGL pipeline is not and has not been supported on Windows for many years now, and you're not using it in the log file provided.

The newer Intel SDKs no longer support CPUs that old, so this is not something we are able to fix. You can continue to use older versions of OBS, which should work fine even if they are unsupported.
