### ISSUE TITLE
Can't record to a local NAS drive with 30.0.2 and 30.0.1, but works with 30.0.0 and earlier

### ISSUE THREAD

**Issue by ShikyC** [obsproject/obs-studio#10036]
### Operating System Info

macOS 14

### OBS Studio Version

30.0.2

### OBS Studio Version (Other)

30.0.1

### OBS Studio Log URL

https://obsproject.com/logs/x8nUABnPekcSWRBB

### Expected Behavior

Prior to version 30.0.0 (inclusive), recording to my NAS drive works well.

### Current Behavior

After upgrading to 30.0.1 and 30.0.2, when clicking the Start Recording button, it promts that "There is not sufficient disk space to continue recording." 

Recording to local disks works well, though. Downgrading to older versions also resolves the issue. This bug is 30.0.1 and 30.0.2 exclusive.

### Steps to Reproduce

1. Upgrade OBS to 30.0.1 or 30.0.2
2. Select a local NAS folder as the target location
3. Click the Start Recording button

**Comment by Fenrirthviti** [comment]
Please provide a log from 30.0.2, as this should have been fixed by #9996

**Comment by gxalpha** [comment]
Fixed by https://github.com/obsproject/obs-studio/pull/9996, this will be in the next release.
