### ISSUE TITLE
Tascam series 102i not working in obs

### ISSUE THREAD

**Issue by ApostolDmitry** [obsproject/obs-studio#10030]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://drive.google.com/file/d/1yL6Ew8DQy9RPlWwAVOhlx2arzIhVBbOm/view?usp=sharing

### Expected Behavior

The microphone should work

### Current Behavior

The microphone is not working

### Steps to Reproduce

1. Just add mic in obs (tascam 102i)
2. And End

### Anything else we should know?

I think the problem is the multichannel nature of this audio interface.  
I have seen that this issue has been discussed many times on forums. 

https://obsproject.com/forum/threads/tascam-series-208i-works-in-any-daw-audacity-etc-and-discord-but-no-audio-meter-or-any-audio-in-recordings-stream.145202/
https://www.reddit.com/r/streamlabsobs/comments/kzx0o0/tascam_102i_microphone_not_being_picked_up/

With all this, the microphone works quietly in other programs and games.

P.S The microphone is recorded in the logs as "series 102i"
Can you please fix this bug?

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by ApostolDmitry** [comment]
@Fenrirthviti  Well, how will the support help me? If the problem is that obs cannot take audio from the device. The problem here is not that I have configured something incorrectly, but that obs cannot do it. I also wrote that the problem is most likely that the card has 10 channels and most likely the wrong one will be detected and this is fixed only by third-party aiso plug-ins, but I do not want to use them because other programs cannot work with the audio interface.

**Comment by Fenrirthviti** [comment]
That is an assumption that you've made, but a quick glance at the log file shows constant spam of:

```02:30:11.971: Source Микро audio is lagging (over by 64.60 ms) at max audio buffering. Restarting source audio.
02:30:13.036: Source Микро audio is lagging (over by 61.08 ms) at max audio buffering. Restarting source audio.
02:30:14.104: Source Микро audio is lagging (over by 57.92 ms) at max audio buffering. Restarting source audio.
02:30:15.170: Source Микро audio is lagging (over by 64.61 ms) at max audio buffering. Restarting source audio.
02:30:16.238: Source Микро audio is lagging (over by 61.29 ms) at max audio buffering. Restarting source audio.```

Which indicates that there is a system, driver, or other issue with the device that's occurring outside OBS. Someone in the support channels can take a look at these errors.

**Comment by ApostolDmitry** [comment]
@Fenrirthviti I'm sorry this log is incorrect. 

https://drive.google.com/file/d/1SXgWUk7bx9alC6qgbK_P4zwl4p8sHJt2/view?usp=sharing

It was because I was switching inputs. If everything is fine, then I get only this.

```
03:13:34.552: WASAPI: Device 'Microphone (SERIES 102i)' [44100 Hz] initialized (source: Микро)
03:13:34.555: warning: Input channel layout "" is invalid or unsupported.
03:13:34.555: avresample_open failed: error code -22
03:13:34.555: creation of resampler failed
```
