### ISSUE TITLE
Scrolling text gets cut off after a certain number of characters in the text file based on what font size is chosen for the Text element

### ISSUE THREAD

**Issue by Go1den** [obsproject/obs-studio#10034]
### Operating System Info

Windows 10

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/pTH1Is3dWMqwJGfH

### Expected Behavior

All of the text in my text file would be scrolled when using the Scroll filter.

### Current Behavior

After 670 characters in the file, the scroll loops back to the start of the file, ignoring the entire second half of my text file. How far the scroll goes into the file seems to be correlated to the size of the font chosen, with smaller fonts making it deeper into the file before being cut off and looping back to the start prematurely.

### Steps to Reproduce

1. Create a new Text source, setting font size to 72.
2. Link that Text source to a .txt file that contains thousands of characters.
3. Set the horizontal scroll speed to any positive number.
4. Have the Text source span the width of the layout (in my case, 1920 pixels)
5. Observe: the scroll will not go through the entire contents of the text file.
6. Set the font size to a slightly smaller number, like 64.
7. Observe: the scroll makes it slightly farther in the file, but still doesn't make it through all the text.

### Anything else we should know?

I believe this may be related to the apparent upper bound of 8000 for a width on the Text element?

**Comment by RytoEX** [comment]
This is likely due to how much text at your selected font size can be rendered into the maximum texture size (16384 pixels in any dimension, in your case). Past that, the texture of the text source ends, and nothing else will fit into it. I don't know that there is a sane way to detect that your text has run off the texture.

**Comment by Go1den** [comment]
That seems to match up with what I was thinking was happening. Is there a way to override the maximum texture size? I tried setting the cx to 24000 in the scene json, but that didn't seem to do anything.

**Comment by RytoEX** [comment]
> That seems to match up with what I was thinking was happening. Is there a way to override the maximum texture size? I tried setting the cx to 24000 in the scene json, but that didn't seem to do anything.

No. The maximum texture size is determined by DirectX/Direct3D. It maxes out at 16384 pixels.
https://learn.microsoft.com/en-us/windows/win32/direct3d11/overviews-direct3d-11-devices-downlevel-intro#direct3d-11-feature-support-feature-levels-12_1-through-9_1

**Comment by gxalpha** [comment]
Closing per the above comment.
