### ISSUE TITLE
When Rec.2100(PQ)/Rec.2100(HLG) is selected, the video capture device has no image

### ISSUE THREAD

**Issue by zengdaqin** [obsproject/obs-studio#10046]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.2

### OBS Studio Log URL

no

### Expected Behavior

video capture device has image

### Current Behavior

video capture device has no image：
![image](https://github.com/obsproject/obs-studio/assets/152824936/4644a13c-6ad8-4bfe-9d01-6b551a28ea7b)

### Steps to Reproduce

1.add Video Capture Device
2.Select **XSPlit VCam** Device
3.Select  **Rec.2100(PQ) or Rec.2100(HLG)**
4.Check preview ， **no image**

**Comment by Fenrirthviti** [comment]
Are you sure that the xsplit vcam even supports these formats? This feels expected to me that it wouldn't work with incorrect settings.
