### ISSUE TITLE
OBS Recording or Streaming not possible, failed to start the output

### ISSUE THREAD

**Issue by DerScherenmann** [obsproject/obs-studio#10040]
### Operating System Info

Other

### Other OS

Arch Linux

OS: Arch Linux x86_64 
Host: MS-7C37 3.0 
Kernel: 6.6.7-arch1-1 
DE: Plasma 5.27.10 
WM: KWin 
CPU: AMD Ryzen 7 3800X (16) @ 3.900GHz 
GPU: NVIDIA GeForce RTX 2070 SUPER 
Memory: 48124MiB 

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/7eSZODfiEAaNNKFt

### Expected Behavior

Recording gets started and will be saved to a file. Additionally the NVIDIA encoder can be selected in the settings menu.

### Current Behavior

In the settings menu under settings -> output -> video encoder, only the Software encoder can be selected. When clicking "Start Recording" in the main window a popup opens which is informing the user that the output cannot be opened. In the first time configuration wizard a message is displayed, that the encoder couldn't be used.

Error Message:

![24122023_164329](https://github.com/obsproject/obs-studio/assets/36897891/10dae952-748e-4693-8e36-4ed8ca1b5f8b)

Encoder Options:

![24122023_164413](https://github.com/obsproject/obs-studio/assets/36897891/d14332af-773c-474c-9520-fec995a585e0)

### Steps to Reproduce

1. Install OBS from the Arch Linux repositories (sudo pacman -S obs-studio)
2. Start obs
3. Click "Start Recording"

### Anything else we should know?

The following log lines are probably what is causing this issue, note the two forward slashes in the path!

```
error: os_dlopen(/usr//lib/obs-plugins/obs-ffmpeg.so->/usr//lib/obs-plugins/obs-ffmpeg.so): libSPIRV.so.13: cannot open shared object file: No such file or directory

error: os_dlopen(/usr//lib/obs-plugins/obs-ffmpeg.so->/usr//lib/obs-plugins/obs-ffmpeg.so): libSPIRV.so.13: cannot open shared object file: No such file or directory

warning: Module '/usr//lib/obs-plugins/obs-ffmpeg.so' not loaded
```

**Comment by derrod** [comment]
This is a support issue, not a bug. Seems like the package in question is incomplete or broken, but that's not ours.
