### ISSUE TITLE
The media source property preview window displays incorrectly

### ISSUE THREAD

**Issue by zengdaqin** [obsproject/obs-studio#10045]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.2

### OBS Studio Log URL

no

### Expected Behavior

The media source property preview window displays normally

### Current Behavior

The media source property preview window displays incorrectly
![IMG_0049](https://github.com/obsproject/obs-studio/assets/152824936/48f024aa-5235-4dd6-b0b9-5a6371008a53)

### Steps to Reproduce

1.add media source
2.select media file ->ok click
3.open media source property window 
4. check property preview window 

### Anything else we should know?

This is the computer configuration：
CPU : 12th Gen Intel(R) Core(TM) i7-1260P   2.10 GHz
GPU : Intel(R) UHD Graphics
Display :  
    HDR video streaming : Supported
    Use HDR : Not Supported

This is a media file ：
[background_motion_snow_average.zip](https://github.com/obsproject/obs-studio/files/13774549/background_motion_snow_average.zip)

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
