### ISSUE TITLE
Web Socket not sending text sources information after connexion

### ISSUE THREAD

**Issue by Maxildan** [obsproject/obs-studio#10051]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/hiJnnkagTAUwVhSs

### Expected Behavior

When I am using this expression in Bit Companion: "$(obs:current_text_[source_name])", I should always have the updated value of this text source in Companion thanks to websocket.

### Current Behavior

I use Bit Companion and I need to retrieve the value of the text from a text source.
So, I am using this expression in Bit Companion: $(obs:current_text_Lorcana_PV_J_2).
And when the first connection is made between Companion and OBS via the websocket, it works and I correctly retrieve the information (here, the life points of a player).
However, afterwards when I modify this value, I don't get any updates. The text value stay fixed.

From having looked into other discussions here, I believe the problem clearly comes from the websocket, which doesn't send certain information continuously as it should.

### Steps to Reproduce

1. create a new button on companion with expression $(obs:current_text_[source_name]).
2. you can see the current text of your source
3. change the text of the source
4. no change in companion
...

### Anything else we should know?

If I'm restarting obs or companion, the value is updated. So, I guess websocket send the value but only once, at connexion

**Comment by tt2468** [comment]
This isn't the correct repo to report obs-websocket bugs to, there's a dedicated repo for that: https://github.com/obsproject/obs-websocket

However, this doesn't appear to be a bug with obs-websocket at all, and is most likely an issue with bitfocus companion. I see no `GetInputSettings` requests in the message log of your session, which is the only way that bitfocus would be able to know the current value of the input. obs-websocket does not emit updates when an input's settings data changes.

**Comment by Maxildan** [comment]
Who has the right answer? ^^

![chrome_eY5YVEKMk5](https://github.com/obsproject/obs-studio/assets/41596675/e37b99d2-3f24-4a18-ac63-59a37e07f7ee)
