### ISSUE TITLE
System lockup while opening OBS with USB analog grabber connected

### ISSUE THREAD

**Issue by Frambooisier** [obsproject/obs-studio#10056]
### Operating System Info

Ubuntu 22.10

### Other OS

Kubuntu 23.10

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/D4VCiCKlR86MCk4C

### Expected Behavior

Start OBS

### Current Behavior

When starting OBS while USB analog capture device is connected, the whole system lockup, hard reset required.

I have two different brands same looking USB capture devices, one of them is:
Bus 001 Device 011: ID 1b71:3002 Fushicai USBTV007 Video Grabber [EasyCAP]

I tried on Kernel version:
6.6.8-060608-generic
6.5.0-14.16

Log file attached here is from clean start without USB device connected since log files from lockup attempts are empty, one has single line of: 05:58:09.402: [Safe Mode] Unclean shutdown detected!

### Steps to Reproduce

1. Connect USB capture device Easycap
2.start OBS
3.lockup
...

### Anything else we should know?

I have mod to allow me capture audio from separate apps instead of whole desktop
I have installed plugin for camera filters, but those are not in use.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
