### ISSUE TITLE
macOS menubar missing in Application Capture 

### ISSUE THREAD

**Issue by omik** [obsproject/obs-studio#10062]
### Operating System Info

macOS 14

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/eglOyOHIazWFSFuf

### Expected Behavior

Source should show macOS menubar and its menus.

### Current Behavior

macOS menubar is no visible, instead there is a black bar at the top but you can spread and capture dropdown menus normally.

### Steps to Reproduce

1. Add an macOS Screen Capture source
2. Change method to Application Capture
3. Choose an app to capture 
...

### Anything else we should know?

This problem started a couple days ago, before that Application Capture was working as intended. I think the problem started right after the last Sonoma patch (14.2.1) but I'm not sure.

Can provide a video of the behavior before / after if needed.

**Comment by PatTheMav** [comment]
The menu bar is not automatically included in Application Capture starting with macOS 14.2 because of internal changes to ScreenCaptureKit.

https://github.com/obsproject/obs-studio/pull/10065 should restore that functionality.

**Comment by gxalpha** [comment]
Closing per the above comment.
