### ISSUE TITLE
The title bar buttons are totally gray (expected symbols not visible)

### ISSUE THREAD

**Issue by Cameo007** [obsproject/obs-studio#10068]
### Operating System Info

Other

### Other OS

NixOS 23.11

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/aWIbuVY4VYDXyTze

### Expected Behavior

The icons of the title bar buttons should be visible.

### Current Behavior

![Bildschirmfoto vom 2024-01-03 16-59-49](https://github.com/obsproject/obs-studio/assets/80521473/140c21fd-f803-4394-ae02-402381e435f2)

The icons of the title bar buttons are invisible. (They don't exist)

### Steps to Reproduce

Open OBS Studio

### Anything else we should know?

I installed OBS Studio via Flathub.

As I saw in the logs the needed icons are not found.

```
18:15:42.911: Failed to find an svg icon for  "window-close-symbolic.svg"
18:15:42.911: Failed to find an svg icon for  "window-minimize-symbolic.svg"
18:15:42.911: Failed to find an svg icon for  "window-maximize-symbolic.svg"
18:15:42.911: Failed to find an svg icon for  "window-restore-symbolic.svg"
```

**Comment by tytan652** [comment]
```
18:15:41.651: Runtime Extensions:
18:15:41.651:  - org.kde.WaylandDecoration.QAdwaitaDecorations
18:15:41.651:  - org.kde.WaylandDecoration.QGnomePlatform-decoration
```

Those installed Flatpaks that enforce custom Wayland decoration on Qt apps are not supported by OBS Studio.
Please report this issue to their maintainer.
