### ISSUE TITLE
Remove Twitch support

### ISSUE THREAD

**Issue by PhoenixLandPirate** [obsproject/obs-studio#10069]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.2

### OBS Studio Log URL

twitch.com

### Expected Behavior

You can currently find Twitch as a streaming platform, this platform promotes material that are against the COC, and thus should not be available.

We can see the project here take stances against services that go against the COC and so Twitch should also be removed.
https://github.com/obsproject/obs-studio/pull/10043#issuecomment-1874370922

 -   Violence, threats of violence or violent language directed against another person.
 -   Sexist, racist, homophobic, transphobic, ableist or otherwise discriminatory jokes and language.
 -   Posting or displaying sexually explicit or violent material.
 -   Posting or threatening to post other people’s personally identifying information ("doxing").
 -   Personal insults.
 -   Unwelcome sexual attention. This includes, sexualized comments or jokes, and unwelcome sexual advances.
 -   Deliberate intimidation, stalking or following.
 -   Advocating for, or encouraging, any of the above behavior.

Are all against the COC, and can be found promoted on Twitch.

### Current Behavior

You can currently see Twitch in the streaming menu.

### Steps to Reproduce

https://www.lifewire.com/twitch-streaming-with-obs-studio-4151808

### Anything else we should know?

Please allow OBS to be a platform for all, or do not allow any services that are morally against OBS's morals/COC.

**Comment by gxalpha** [comment]
We're not removing Twitch.

**Comment by Fenrirthviti** [comment]
This PR is disingenuous, and attempting to incite drama.

As such, the submitter has been banned from our repo.
