### ISSUE TITLE
Websocket listens only in ipv6

### ISSUE THREAD

**Issue by aluaces** [obsproject/obs-studio#10073]
### Operating System Info

Other

### Other OS

Debian testing

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/F0f7wZBjjkayv8ey

### Expected Behavior

obs listening on port 4455 on ipv4 interface 127.0.0.1 so I can use `obs-blade` android app.

### Current Behavior

It only listens on ipv6 socket, and `obs-blade` says it can't connect:

`tcp   LISTEN     0      4096                                [::]:4455             [::]:*     users:(("obs",pid=322969,fd=50))`

### Steps to Reproduce

Just by using it, no matter it is the flatpack version or the distro version.

### Anything else we should know?

This was addressed and fixed in `obs-websocket`, but somehow the patch didn't make it to obs in the merge:

https://github.com/obsproject/obs-websocket/pull/923

**Comment by tt2468** [comment]
obs-websocket binds to `[::]` using the `IPV6_V6ONLY` socket opt set to 0, meaning it's actually a dual stack bind. The issue you are encountering is likely to be a firewall issue, not a socket issue.
