### ISSUE TITLE
videos recorded on obs with amd h.265 cause issues with davinci resolve

### ISSUE THREAD

**Issue by GentlemanMC** [obsproject/obs-studio#10094]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/F2c5NNUD53w9BaA2

### Expected Behavior

When i record a clip using amd hvec it should import fine into davinci resolve without any problems

### Current Behavior

when i import an amd hvec clip into davinci resolve with mkv format the video plays back at 2x while audio is still at 1x causing audio to become out of sync then at the end of the clip its just an extended still frame of the frame to fill the gap

then when exporting the same thing happens

and if the format is mp4 the clip is always at 30 fps and when i change it to 60 fps (i record at 60 fps btw) it just says media offline

### Steps to Reproduce

1. record anything with amd hvec
2. import the video to davinci resolve
3. playback / export and see the bug

### Anything else we should know?

1- with ancient versions of obs (26.x is the only i tested) it works fine
2- im not the only one having this issue i saw multiple reddit posts about it
3- when i record with other recording programs the clips work fine with amd hvec hence it must be an obs issue

**Comment by Fenrirthviti** [comment]
Unfortunately, we will need more information from BMD on what exactly is going on here. This may be a bug on their end as well, but as they are closed source there's not much we can do to investigate further. I'd recommend reporting this to their support and seeing if they can identify what is wrong about our files (if anything), then we can reopen at that time.
