### ISSUE TITLE
Random Stuttering 

### ISSUE THREAD

**Issue by notpsx** [obsproject/obs-studio#10106]
### Operating System Info

Windows 10

### Other OS

Linux, Windows 11

### OBS Studio Version

30.0.2

### OBS Studio Version (Other)

29.0.2 (For testing)

### OBS Studio Log URL

https://obsproject.com/logs/iEntEnVHbrrI8EoH

### OBS Studio Crash Log URL

/

### Expected Behavior

/

### Current Behavior

When using the "Monitor" option in the Sources tab for recording, a noticeable drop in frame rate (10-15fps) occurs approximately every 20-30 seconds, persisting for around 5 seconds, as shown [in this video](https://youtu.be/xGAuo52_C2E?si=hNfQnpedW3aC9SNf). Surprisingly, this issue does not happen when using "Window Capture" or "Game Capture." Initially, I thought this might be a potential problem with my PC. However, subsequent tests on earlier versions of OBS, such as 29.0.2, revealed the same issues. Additionally, the issue occurs when tested on different PCs and operating systems.

### Steps to Reproduce

/

### Anything else we should know?

The log does not indicate any issues or anomalies.

**Comment by moops44** [comment]
How does the log dont indicate any issues ??

https://obsproject.com/tools/analyzer?log_url=https%3A%2F%2Fobsproject.com%2Flogs%2FiEntEnVHbrrI8EoH

**Comment by notpsx** [comment]
> How does the log dont indicate any issues ??
> 
> https://obsproject.com/tools/analyzer?log_url=https%3A%2F%2Fobsproject.com%2Flogs%2FiEntEnVHbrrI8EoH

They aren't related to that issue.

**Comment by notpsx** [comment]
They aren't related to that problem.

**Comment by notpsx** [comment]
> How does the log dont indicate any issues ??
> 
> https://obsproject.com/tools/analyzer?log_url=https%3A%2F%2Fobsproject.com%2Flogs%2FiEntEnVHbrrI8EoH

They aren't related to that problem.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
