### ISSUE TITLE
why does obs does not support more than one window capture?

### ISSUE THREAD

**Issue by Hankyu-Kim** [obsproject/obs-studio#10129]
### Operating System Info

Ubuntu 20.04

### OBS Studio Version

Other

### OBS Studio Version (Other)

OBS 25.0.3+dfsg1-2 (linux)

### OBS Studio Log URL

https://obsproject.com/logs/0MyfgwnE1kAucHGN

### Expected Behavior

I want to stream with two window capture with real-time using two gst-launcher tab. (more than one)
Following is my command that showing each camera result on ubuntu :
gst-launch-1.0 v4l2src device=/dev/video0 ! xvimagesink
gst-launch-1.0 v4l2src device=/dev/video1 ! xvimagesink

### Current Behavior

one is appearing, and the other is not.

### Steps to Reproduce

1. open the terminal
2. type "gst-launch-1.0 v4l2src device=/dev/video0 ! xvimagesink"
3. open another terminal
4. type "gst-launch-1.0 v4l2src device=/dev/video1 ! xvimagesink"
5. open the other terminal
6. type "obs"
7. add sources with 'Window Capture (Xcomposite)'
8. choose each result of gst-launcher output.
9. resize the box that showing result on one scene.
...

### Anything else we should know?

I am using jetson platform model name ORIN NX, if it cares.

**Comment by derrod** [comment]
Github issues are for bugs, this is a support request. See https://obsproject.com/help.

On top of that it's an ancient unofficial version on an unsupported platform.
