### ISSUE TITLE
Compound audio of sources

### ISSUE THREAD

**Issue by AskMP** [obsproject/obs-studio#10141]
### Operating System Info

macOS 14

### OBS Studio Version

30.0.2

### OBS Studio Log URL

N/A

### Expected Behavior

When adding a source that has audio, if it is duplicated, the audio output should not be compounded. Every source with audio should only have the output be equal to the DB level of the source (and the adjustment). 

### Current Behavior

Audio of a source on-air compounds onto both recording and streaming but does not show the impact of this compounding within the audio mixer VU meter.

### Steps to Reproduce

1. Create a scene called "Background" that has multiple source that contain audio (example would be NDI feeds)
2. Create a new scene with only one of those sources but add the "Background" scene (to ensure all sources are output when that is live)
3. Record or stream switching between the Background only stream and the source + background stream

### Anything else we should know?

The purpose of the "Background" or in my case "Global Audio" is to ensure that each scene has all guest and source audio but each 1up or PiP scene is a different level than something like a screenshare only. The PiP or camera scenes have a louder audio level of the camera feed (because that is where the audio is from) since the source is in the background layer AND in the source list of that scene.

**Comment by gxalpha** [comment]
This sounds like a feature request, which we don't track using GitHub Issues (we use GitHub exclusively for bug reports).
Please put ideas and feature requests on [our ideas page](https://ideas.obsproject.com).

The current behavior is intentional.

Thank you!
