### ISSUE TITLE
The DingTalk meeting process cannot be found in the window collection.

### ISSUE THREAD

**Issue by sunzhengbo** [obsproject/obs-studio#10158]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/Q7wSsSH2Q3wCwlBu

### Expected Behavior

窗口采集可以找到钉钉会议的进程

### Current Behavior

窗口采集找不到钉钉会议进程

### Steps to Reproduce

1. 开启钉钉会议
2.打开obs
3.添加窗口采集
4.选择钉钉会议，这里找不到，钉钉的版本是：7.5.0-Release.13119104Native

**Comment by gxalpha** [comment]
Please report this to DingTalk and/or visit our support channels.

This issue appears to be a support request, for which we don't use GitHub Issues.
Please make sure to visit the support sections on our [Discord server](https://discord.gg/obsproject) or [Forums](https://obsproject.com/forum).

Thank you!

**Comment by sunzhengbo** [comment]
原因找到了，就是钉钉会议必须在最上层，如果钉钉会议的上面还有进程覆盖，如果浏览器就会出现找不到的情况












sunzhengbo
***@***.***


---Original---
From: "Sebastian ***@***.***&gt;
Date: Fri, Feb 2, 2024 04:32 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [obsproject/obs-studio] The DingTalk meeting process cannot befound in the window collection. (Issue #10158)




 
Please report this to DingTalk and/or visit our support channels.
 
This issue appears to be a support request, for which we don't use GitHub Issues.
 Please make sure to visit the support sections on our Discord server or Forums.
 
Thank you!
