### ISSUE TITLE
Failed to compile, missing libVPL

### ISSUE THREAD

**Issue by ConHuevosGuey** [obsproject/obs-studio#10155]
### Operating System Info

Other

### Other OS

Slackware Linux 15.0

### OBS Studio Version

30.0.2

### OBS Studio Log URL

N/A

### Expected Behavior

Configure and compile correctly.

### Current Behavior

When executing the cmake command to compile:

`cmake -DLINUX_PORTABLE=ON -DCMAKE_INSTALL_PREFIX="${HOME}/obs-studio-portable" -DENABLE_BROWSER=ON -DENABLE_LIBDFK=ON -DCEF_ROOT_DIR="../../cef_binary_5060_linux64" -DENABLE_AJA=OFF .`

During the cmake configuration it stops with the error:

`CMake Error at /usr/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find VPL (missing: VPL_LIBRARY VPL_INCLUDE_DIR) (Required is at
  least version "2.6")
Call Stack (most recent call first):
  /usr/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindVPL.cmake:79 (find_package_handle_standard_args)
  plugins/obs-qsv11/cmake/legacy.cmake:13 (find_package)
  cmake/Modules/ObsHelpers.cmake:473 (include)
  plugins/obs-qsv11/CMakeLists.txt:3 (legacy_check)`

Is it possible to disable libvpl support when compiling?  It's my understanding this is an intel graphics card only feature and I do not need it however I could not find any switches or documentation on how to disable the requirement.

### Steps to Reproduce

1.  Attempt to compile

**Comment by tytan652** [comment]
> Is it possible to disable libvpl support when compiling?

`-DENABLE_QSV11=OFF`, libvpl is the library to provide QSV feature for Intels GPU.

Note that this sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for further assistance.

Thank you

**Comment by ConHuevosGuey** [comment]
Sorry, I would have filed it properly had I known.  Thank you.
