### ISSUE TITLE
Luts, Filters, Plugins do not persist after Updates

### ISSUE THREAD

**Issue by adrianboisclair** [obsproject/obs-studio#10164]
### Operating System Info

macOS 14

### OBS Studio Version

30.0.2

### OBS Studio Log URL

n/a

### OBS Studio Crash Log URL

n/a

### Expected Behavior

Expected behavior should be to persist any user-added filters (plugins, etc).

### Current Behavior

Every time an update is released, all of my added LUTS filters are lost. 

### Steps to Reproduce

1. MacOS, Apple Silicon, MBP M1 Max -- install an update.

### Anything else we should know?

This has been an issue ever since I can remember -- at least for the last several years.

**Comment by Fenrirthviti** [comment]
Please provide a log file before and after the issue.

**Comment by gxalpha** [comment]
No log has been provided.

Also, this sounds like you might be adding the LUTs into the OBS bundle itself. If that's so, do not do that. They will get lost. You can add them from anywhere on the system.
