### ISSUE TITLE
OBS crash on startup

### ISSUE THREAD

**Issue by edwloef** [obsproject/obs-studio#10174]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/bbVkmN3na7ZSBM4O

### Expected Behavior

No crash

### Current Behavior

Crash (segmentation fault)

### Steps to Reproduce

1. run `obs`

### Anything else we should know?

It runs in safe mode. Looking at the log it mentions DeckLink, which is something I do not use.

**Comment by RytoEX** [comment]
The DeckLink entry in the log is almost certainly a red herring. OBS always tries to check for DeckLink devices.

Please provide a gdb backtrace of the crash.

**Comment by edwloef** [comment]
[backtrace.txt](https://github.com/obsproject/obs-studio/files/14122996/backtrace.txt)

**Comment by QushyQushy** [comment]
Also having this issue on Plasma 6.

**Comment by RytoEX** [comment]
This appears to be a crash inside Qt 6.7 Beta 2, which we don't currently support. Looks like [QTBUG-121697](https://bugreports.qt.io/browse/QTBUG-121697). Please feel free to upvote that bug.

**Comment by QushyQushy** [comment]
> This appears to be a crash inside Qt 6.7 Beta 2, which we don't currently support. Looks like [QTBUG-121697](https://bugreports.qt.io/browse/QTBUG-121697), which may affect Qt 6.6. Please feel free to upvote that bug.

Just did, thank you so much! :)

**Comment by gxalpha** [comment]
Closing as so far this is only seen in a Beta version of Qt, which is unsupported as per above.
If this happens on a Qt release, we will reevaluate this.

**Comment by edwloef** [comment]
This has been fixed with Qt 6.7 beta 3
