### ISSUE TITLE
Buckshot Roulette can not be captured by WGC on win10（a part of win10）

### ISSUE THREAD

**Issue by MemeTao** [obsproject/obs-studio#10179]
### Operating System Info

Windows 10

### OBS Studio Version

30.0.2

### OBS Studio Log URL

no

### Expected Behavior

As mentioned above

### Current Behavior

As mentioned above

### Steps to Reproduce

1.
2.
3.
...

### Anything else we should know?

I tested 3 pc (win10) and 2 of them didn’t work.  win11 is good.

**Comment by WizardCM** [comment]
This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels below, and if it's determined that this is indeed a bug, then we will re-open this issue.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
