### ISSUE TITLE
Could not find the Qt platform plugin "xcb"

### ISSUE THREAD

**Issue by MacStevins** [obsproject/obs-studio#10194]
### Operating System Info

Ubuntu 22.04

### Other OS

Pop!_OS

### OBS Studio Version

30.0.2

### OBS Studio Log URL

Sadly, no logs, only terminal output which I lost

### Expected Behavior

Launch the application

### Current Behavior

Running on the terminal it shows `qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""` and tried doing someone's suggestion to use `export QT_DEBUG_PLUGINS=1` and all I got are some reads of directories, I've sadly lost those terminal output cause it didn't recognized the older official 30.0.1 installation guide through apt and had to restart the instance

30.0.2 was installed through the GitHub releases tab download file and used the OS's built-in .deb installer

### Steps to Reproduce

1. Install 30.0.2 on GitHub
2. Restarts PC
3. Run Application

**Comment by gxalpha** [comment]
This issue appears to be a support request, for which we don't use GitHub Issues.
Please make sure to visit the support sections on our [Discord server](https://discord.gg/obsproject) or [Forums](https://obsproject.com/forum).

Thank you!
