### ISSUE TITLE
Black screen, no video only sound

### ISSUE THREAD

**Issue by vhvSoma** [obsproject/obs-studio#10207]
### Operating System Info

Windows 10

### OBS Studio Version

30.1.0-beta1

### OBS Studio Version (Other)

30.0.2 and portable 30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/elLxsRdvPbE5BucC

### Expected Behavior

I don't know the reason for this problem. But I can assume that this is happening due to the fact that the system has some kind of virtual video adapter. However, I deleted all of them.

### Current Behavior

The screen capture method through Windows 10 (1903 above does not work correctly) is the same with window capture, only BitBlt or Dxgi works, but not the new one, I don’t know what this is connected with, even in theory, I used any solution methods that I found, but none helped, the obs itself also says that everything is fine, judging by the logs. attached video.

https://github.com/obsproject/obs-studio/assets/58812794/df685a4e-6270-47bf-a491-2e19e282d504

### Steps to Reproduce

-

**Comment by Fenrirthviti** [comment]
I'm a bit confused by this report, are you saying this doesn't work on 30.0.2 either? Or is this issue exclusive to the beta?

**Comment by RytoEX** [comment]
From some brief searching, it sounds like there are some bugs in CreateForMonitor and DWM that were fixed in Windows 11, but possibly not fixed in Windows 10. A couple of these are triggered if the targeted display is no longer active or attached, and there was also a bug related to virtual screens (supposedly fixed in 20H1).

What might be helpful is confirming that all virtual displays and old no longer attached displays are no longer in the display list. Please try opening Device Manager and view hidden devices, and screenshot what's available. After that, try removing the disconnected (greyed out) monitors and see if it makes a difference.
![233866162-2a90c18a-657f-41e1-87bc-c1633b65b428](https://github.com/obsproject/obs-studio/assets/624931/e1e2f4a2-4897-4930-9bb1-f025094a61e7)

**Comment by vhvSoma** [comment]
This problem exists on three versions of obs: Beta on Steam, Stable and Stable Portable. RytoEX you were right, there were 2 screens Generic Pnp Monitor and one UNPNP in the device manager, but deleting them did not solve the problem. The same event appears in the logs. https://obsproject.com/logs/u12ET3Y9O0OBFXbJ
![232323](https://github.com/obsproject/obs-studio/assets/58812794/ee4c61a4-ce29-4dfa-a90c-8d42f66350aa)

After the system transitioned from safe mode to normal mode, a new screen appeared (I turned on all services). The lower window refers to the lower monitor and the upper window, respectively, to the upper one.

**Comment by RytoEX** [comment]
If you do not have two S2421HN displays, you can delete the one that says it is not connected before starting OBS.

**Comment by vhvSoma** [comment]
![now](https://github.com/obsproject/obs-studio/assets/58812794/8f0cc002-147d-4059-a68c-266b1aa58b87)
Now I have one monitor, but even after rebooting the problem did not go away, maybe the problem is in the video card?
https://obsproject.com/logs/HmUjT5tgvl7Uk3Ur

**Comment by vhvSoma** [comment]
![now2](https://github.com/obsproject/obs-studio/assets/58812794/07a08b0e-fc6a-4691-bd5b-2e0b8f83d8f9)
Now I have one monitor, but even after rebooting the problem did not go away, maybe the problem is in the video card?
https://obsproject.com/logs/GuSCRDzNBKyiCxeb

**Comment by RytoEX** [comment]
Have you tried deleting and recreating the Display Capture source in OBS to ensure it's not using old data?

**Comment by vhvSoma** [comment]
Yes, I always do this when action is taken to solve a problem. One fact confuses me. I attached two screenshots, on the first one is another person’s screen, as I understand it, he uses Windows 11 (I’m not sure), and after the name of the monitor he has the symbol combination “@ -1920,0”, and I have “@0,0” . Maybe my screen capture is misaligned.

![cap2](https://github.com/obsproject/obs-studio/assets/58812794/f9d2d7a9-d157-4e05-bbaa-7e7051f1580a)
![cap2](https://github.com/obsproject/obs-studio/assets/58812794/3f9bb17a-a913-4a97-bb38-df2898d0e5d5)

**Comment by vhvSoma** [comment]
Yes, I always do this when action is taken to solve a problem. One fact confuses me. I attached two screenshots, on the first one is another person’s screen, as I understand it, he uses Windows 11 (I’m not sure), and after the name of the monitor he has the symbol combination “@ -1920.0”, and I have “@0.0” . Maybe my screen capture is misaligned.
![cap](https://github.com/obsproject/obs-studio/assets/58812794/ee8a1b1c-7345-448c-b97a-27cb3814f080)
![cap2](https://github.com/obsproject/obs-studio/assets/58812794/1dbf0adc-4092-4a12-9efd-47ae78d9f2fc)

**Comment by RytoEX** [comment]
`@-1920,0` and `@0,0` are the coordinates of the display as Windows sees them. `@0,0` are the default primary display coordinates. This is normal.

> Yes, I always do this when action is taken to solve a problem.

The log you attached showed loading an existing source. It did not show deleting and recreating the Display Capture source.

**Comment by vhvSoma** [comment]
> The log you attached showed loading an existing source. It did not show deleting and recreating the Display Capture source.
https://obsproject.com/logs/4OABgPlEm0B8t7wV
Recreated screen capture

**Comment by vhvSoma** [comment]
RytoEX, I don't fully understand what you want me to do. I have attached a video of what I assume you want from me. https://obsproject.com/logs/dbk2cc2on8WH60Jq

https://github.com/obsproject/obs-studio/assets/58812794/d2bb634c-0e7a-463d-834f-3511d68b7a88

**Comment by vhvSoma** [comment]
RytoEX, you were right, my service was turned off. CaptureService

**Comment by vhvSoma** [comment]
to fix the problem:
1. open cmd as administrator
2. and type "sc config CaptureService start= demand"
3. Restart pc

**Comment by RytoEX** [comment]
Closing per the above.
