### ISSUE TITLE
Ask Discord developers how they make window capture

### ISSUE THREAD

**Issue by CamaradaPrestes** [obsproject/obs-studio#10214]
### Operating System Info

Ubuntu 22.10

### OBS Studio Version

30.1.0-beta1

### OBS Studio Log URL

aaaaaaaaaaaaaaaaaaaaaaa

### Expected Behavior

It should work.

### Current Behavior

Black screen.

### Steps to Reproduce

1. Open OBS
2. Select Window Capture option
3. search for something in the options that could fix this
4. don't find anything
5. search on Google for a solution
6. find out that lots of people have the same issue for years

### Anything else we should know?

You should learn how to make Xcomposite work.

**Comment by WizardCM** [comment]
This is not a valid bug report. It does not contain a log file, it doesn't contain real reproduction steps.

This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels below.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
