### ISSUE TITLE
Start Virtual Camera text is cut off in the UI

### ISSUE THREAD

**Issue by theFireProject** [obsproject/obs-studio#10210]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.2

### OBS Studio Log URL

N/A

### Expected Behavior

The `Start Virtual Camera` text should be cut off at the right and three dots `...` should be added like in the title of the Scene Transitions dock (see screenshot).

![](https://github.com/obsproject/obs-studio/assets/61639215/41168ceb-236f-4d3c-9f87-44523c6bbc09)

### Current Behavior

Letters of the `Start Virtual Camera` text are cut off on both sides.

![](https://github.com/obsproject/obs-studio/assets/61639215/1859425c-abfd-4951-a236-19c0fc373cca)

### Steps to Reproduce

1. Change the width of the Controls dock to its minimum.

**Comment by powersagitar** [comment]
I would like to look into this :)

**Comment by Diog0o** [comment]
Is the issue closed? I would like to work on it
