### ISSUE TITLE
Video Capture Device (V4L2) stays active on scene switch

### ISSUE THREAD

**Issue by greaka** [obsproject/obs-studio#10215]
### Operating System Info

Other

### Other OS

6.7.4-arch1-1

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/uTH6xnLj572xHs8Y

### Expected Behavior

OBS should allow me to disable inactive sources and not drain my battery.

### Current Behavior

Ever since I've added an external webcam via uvc v4l2loopback to one of my OBS scenes, I experience a full core of load coming from OBS, regardless of whether that scene is active or if any output method is enabled. Disabling preview also doesn't help. I'm fine with this as long as I'm using the webcam. However, when the scene is unused, the source should be disabled instead. There is currently no checkbox available for this.

### Steps to Reproduce

1. Setup dkms v4l2loopback
2. Add Video Capture Device (V4L2) source
3. Select any input encoding (tested with motion jpeg and h264)
4. Switch scene

### Anything else we should know?

Fixing this would also allow me to duplicate the source and have different camera settings for different scenes as the old one wouldn't still hog the input feed. It would also allow the camera to go to sleep.

**Comment by polluxau** [comment]
I was just wondering today why this isnt available, while it's available on windows I'm pretty sure.

Maybe with the pipewire video capture they can add it

**Comment by RytoEX** [comment]
As far as I can tell, this is working as designed. The V4L2 source does not have a "deactivate when not showing" option, unlike the Windows DirectShow-based source. As such, this is a feature request and not a bug.
