### ISSUE TITLE
Flatpak QSV H264 error encoding

### ISSUE THREAD

**Issue by Zibbp** [obsproject/obs-studio#10221]
### Operating System Info

Ubuntu 22.10

### OBS Studio Version

30.1.0-beta1

### OBS Studio Log URL

https://obsproject.com/logs/6WMqhVBsBpPue1wC

### Expected Behavior

The WHIP stream to start successfully without QSV encoding errors.

### Current Behavior

When starting a WHIP stream with the encoder set to QSV/H.264, the encode will fail with the following.
```
17:50:23.013: [qsv encoder: 'advanced_video_stream'] Encode failed: bad texture handle
17:50:23.013: Error encoding with encoder 'advanced_video_stream'
```
Strangely, when I close OBS, the applications hangs open. When I go to run OBS again via the flatpak, OBS warns that it's already running. I acknowledge by clicking "launch anyway" and continue to launch. When I start streaming in this mode, using QSV/H.264, the stream works just fine.

The above linked log URL is of the failure. Here is a log link of the encoding working when I launch acknowledging that another OBS instance is running. https://obsproject.com/logs/MOWiWFbf0EAKLOHJ

### Steps to Reproduce

1. Set stream output to WHIP (likely not related to issue)
2. Set stream encoder to QSV/H.264 (any settings)
3. Start stream

### Anything else we should know?

I'm using an Intel Arc A380 - driver versions:
```
vainfo: VA-API version: 1.20 (libva 2.20.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 23.4.0 ()
```
I also noted this line in the log out, indicating that I'm not on an Intel GPU?
```
app not on intel GPU, fall back to old qsv encoder
```

**Comment by kkartaltepe** [comment]
I believe this is fixed in master, or beta2 when we cut that. Please try with master if you can build obs yourself.

**Comment by Zibbp** [comment]
I've built the Flatpak from master (https://github.com/obsproject/obs-studio/commit/848d76f52c2103acbed15d227bb603cf93bf7db7). It sees the new QSV encoder `>>> new qsv encoder`, but unfortunately it still errors out with the following.
```
21:55:21.419: [qsv encoder: 'advanced_video_stream'] Encode failed: bad texture handle
21:55:21.419: Error encoding with encoder 'advanced_video_stream'
```
https://obsproject.com/logs/pwwJpfbIQyAEBgEx

Specific flatpak Intel and Mesa versions
```
OBS Studio                     com.obsproject.Studio                    30.1.0-beta1-16-g848d76f52 master      studio-origin user
Mesa                           org.freedesktop.Platform.GL.default      23.3.4                     23.08       flathub       system
Mesa (Extra)                   org.freedesktop.Platform.GL.default      23.3.4                     23.08-extra flathub       system
Intel                          org.freedesktop.Platform.VAAPI.Intel                                23.08       flathub       system
openh264                       org.freedesktop.Platform.openh264        2.1.0                      2.2.0       flathub       system
```

Is there a way I can get more information into why this is happening?

**Comment by kkartaltepe** [comment]
Thanks for testing out master. 

> unfortunately it still errors out with the following.

Thats ok I have a pretty good idea of the problem, we should be able to fix it by beta2.

**Comment by Zibbp** [comment]
Thanks for the PR, I built it and it fixed the issue. While testing your PR I ran into another issue. If I start a stream then stop, then go to change a stream setting, such as dropping the bitrate. When I go to start stream again, VA-API/QSV fail to load.
```
16:45:49.256: Failed to initialize VA-API
16:45:49.256: [qsv encoder: 'msdk_impl'] Hardware device returned unexpected errors (MFX_ERR_DEVICE_FAILED)
16:45:49.256: [qsv encoder: 'advanced_video_stream'] qsv failed to load
```
Full log file showing this issue - https://obsproject.com/logs/UKLRjHt7jYT4lJWu
Some more output from the terminal, though it it's not very useful
```
info: [qsv encoder: 'advanced_video_stream'] debug info:
libva info: VA-API version 1.19.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_19
libva error: /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/iHD_drv_video.so init failed
libva info: va_openDriver() returns 1
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_19
libva error: /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/i965_drv_video.so init failed
libva info: va_openDriver() returns -1
info: 	surf:           SysMem
libva info: VA-API version 1.19.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_19
libva info: va_openDriver() returns 0
libva info: VA-API version 1.19.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_19
libva info: va_openDriver() returns 0
libva info: VA-API version 1.19.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_19
libva error: /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/iHD_drv_video.so init failed
libva info: va_openDriver() returns 1
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_19
libva error: /usr/lib/x86_64-linux-gnu/dri/intel-vaapi-driver/i965_drv_video.so init failed
libva info: va_openDriver() returns -1
error: Failed to initialize VA-API
```
I don't see anything initially wrong, let me know if there's more info I can gather.

**Comment by kkartaltepe** [comment]
You should probably uninstall the i965 driver as its deprecated, unsupported, and doesnt work with intel's sdks.

> When I go to start stream again, VA-API/QSV fail to load.

I dont see any attempts to use the ffmpeg va-api encoder, try that and if it also fails then qsv has device state somehow. ffmpeg vaapi does work then qsv ruined its own state, which seems pretty common but unless you can find a consistent way to get it replicated on my machine it will be impossible to debug.
