### ISSUE TITLE
I Found a Sound Issue in my current running video when i started obs in Background

### ISSUE THREAD

**Issue by Raafey-Khan** [obsproject/obs-studio#10225]
### Operating System Info

macOS 11

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/

### Expected Behavior

My Background Video Sound should be as it is without getting any disturbance or Changed after opening OBS studio while watching something on chrome video sound should not be disturbed.

### Current Behavior

So i was just watching my coding lectures on chrome, and i thought to open OBS and the moment obs opened on my macbook, the audio which is coming from my coding lecture, that got changed into muffed sound ,and dimmed sound like that, i don't know why its occuring, but in case if any developer is seeing my message please fix the sound issue that causing trouble . 

### Steps to Reproduce

1. I was watching Coding Tutorials on Chrome , and i immediately opened OBS Studio On My Mac
2. But when the Application Opened the Voice which is coming currently from my coding tutorials is got sound different 
3. i closed the OBS studio and reload my chrome and yeah the voice is normal ,but again when im start OBS its still happening
4. Even after closing
...

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
