### ISSUE TITLE
[Win10] [30.1.0-beta1] Unselected Audio source in Advanced Audio Properties appears on Twitch VOD Track

### ISSUE THREAD

**Issue by ampedPF** [obsproject/obs-studio#10237]
### Operating System Info

Windows 10

### OBS Studio Version

30.1.0-beta1

### OBS Studio Log URL

https://obsproject.com/logs/5KrBx0ToR3L2mFMt

### Expected Behavior

The unselected audio source in Advanced Audio Properties window shouldn't be heard onto the Twitch VOD Track.

### Current Behavior

I use Track 1 as the livestream track and Track 6 as the Twitch VOD track.
The audio I play through the device that I set to be heard only on the livestream (Track 1 checked) can also be heard on the VOD (Track 6 unchecked).

### Steps to Reproduce

1. In File > Settings > Output > Streaming : Set Audio Track to 1 and check Twitch VOD Track then set it to 6.
2. In Edit > Advanced Audio Properties : Have an audio source checked on Track 1 and unchecked on track 6.
3. Stream for a minute or so with some audio content going through the aforementioned audio source.
4. Check the livestream: you should hear your audio content.
5. Check the VOD:
    - expected: you shouldn't hear the audio content.
    - current : audio content can be heard on the VOD.

### Anything else we should know?

I'm using OBS 30.1.0-beta1 since February 5th and every VODs since then display this kind of behavior (I just noticed it).
I ran some tests on both this version and OBS 30.0.2.
Only the 30.1.0-beta1 version has this issue.
I hope this can help in any way.

**Comment by derrod** [comment]
This was fixed in beta 2 (coming soon).

**Comment by ampedPF** [comment]
Ok thank you! I did a quick search for a related issue but haven't been thorough enough apparently.
Thanks again for the quick reply!
