### ISSUE TITLE
OBS_GET_SOURCE_BY_NAME returns null for filter sources

### ISSUE THREAD

**Issue by PeterAkakpo** [obsproject/obs-studio#10247]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.2

### OBS Studio Log URL

N/A

### Expected Behavior

obs_get_source_by_name should find filter sources that are not added to a source.

### Current Behavior

null is return by **obs_get_source_by_name**  for filters that have not been added to a source

### Steps to Reproduce

1.  create a filter source ,  **obs_create_source**("basic_eq_filter", "EqualizerFilter" , settings, nullptr)
2.  obs_source_t *filter=**obs_get_source_by_name**("EqualizerFilter")
3.  filter is null
...

### Anything else we should know?

how can i find a globally created filter.  i have not added the filter to any source, so i cannot use **obs_source_get_filter_by_name**

**Comment by derrod** [comment]
Filters are always private by design, but you can still find them by UUID, which is a better idea anyway.

https://github.com/obsproject/obs-studio/blob/062813eb8a352dacb97d23bddcaf776b37d37ee8/libobs/obs-source.c#L367-L372
