### ISSUE TITLE
The recording pause button of OBS has disappeared.

### ISSUE THREAD

**Issue by xengine-qyt** [obsproject/obs-studio#10244]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/GG0z6V8BgKPyBwVQ

### Expected Behavior

Live streaming and recording have distinct configurations, with variations in stream quality, resolution, and bitrate.
I've tried different configurations, but none of them work. Even creating a new configuration doesn't help. I don't know what's wrong.

### Current Behavior

show pause button

### Steps to Reproduce

1.open obs

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
