### ISSUE TITLE
Every Time i Launch OBS It Blue Screens my PC Ever since the latist Update

### ISSUE THREAD

**Issue by FoxheartGames** [obsproject/obs-studio#10258]
### Operating System Info

Windows 10

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/Y5sqcsJDXqNmTg22

### OBS Studio Crash Log URL

https://obsproject.com/logs/M788Q0kezyUYwtQv

### Expected Behavior

For OBS to load and not Crash my PC Every time i Open it after my PC Has been off, Litraly every time i Turn my PC on and load OBS Takes a few seconds then it Blue screens my PC Every time since the Update

### Current Behavior

Crashes my PC on OBS Launch 

### Steps to Reproduce

1.Litraly just loading OBS up
2.
3.
...

**Comment by Fenrirthviti** [comment]
OBS runs in user space, and cannot directly cause a blue screen.

I recommend using a tool like bluescreenview or whocrashed to determine the cause. Most typically it's a misbehaving capture device or other hardware problem that crashes when OBS tries to access it, rather than OBS causing it.
