### ISSUE TITLE
OBS Crashes randomly on display capture (single GPU)

### ISSUE THREAD

**Issue by theofficialgman** [obsproject/obs-studio#10262]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/ptzKwckwogtD4ENt

### OBS Studio Crash Log URL

`Failed to recreate D3D11: Failed to create swap RTV (80070057)`

### Expected Behavior

Expect that OBS does not crash

### Current Behavior

OBS crashes randomly. Does not seem consistent. Sometime it crashes immediately on opening, other times on dragging the window between screen.

Seems related to display capture 

### Steps to Reproduce

1. start OBS and add display capture
2. wait to crash

### Anything else we should know?

Hardware info should be available in the uploaded log URL. if more information or testing is required I am happy to provide it

**Comment by Fenrirthviti** [comment]
Your GPU driver is constantly crashing, not OBS:

`12:59:45.751: Device Remove/Reset!  Rebuilding all assets...`

I'd recommend a clean reinstall of the GPU drivers, and checking any overclocking you might be doing for instability.

**Comment by theofficialgman** [comment]
This is an ` CPU Name: AMD Ryzen 5 7640U w/ Radeon 760M Graphics`. Its a fresh install of the GPU driver (latest stable version). No overclocking (not sure that is even possible on this mobile chip).

Only OBS is crashing. No other applications on my system have any instability. When OBS crashes no other applications show any issues or flickering or artifacting or anything.

After a few restarts of OBS (5 times or so) with the crashes I no longer get any error output in logs or crashes.... Maybe some sort of shader caching issue?

**Comment by Fenrirthviti** [comment]
A device remove/reset means the driver itself is crashing. We run in userspace, so we can't *cause* a device driver to crash like that. I guess it's possible there's a bug in the driver that we're tripping against that other software isn't, but it can't be directly caused by anything we have access to. A bit beyond scope of what we can realistically debug, unfortunately.

**Comment by theofficialgman** [comment]
Gotcha. If it happens again and I can recreate it consistently I'll open a report at AMD then and link it here (if publicly accessible).

**Comment by tomasmark79** [comment]
I am facing the same issue.

AMD Ryzen 7 PRO 7840HS with AMD Radeon 780M.

As the same is permanently broken hardware acceleration for video via DXD11 so the same crash is happening in OBS. For Chrome and Firefox it is solvable to not use OpenGL ANGLE and force to use different version than DXD11 (DXD9 DXD11on12, OpenGL, etc.) 

but for OBS not available other GPU frameworks

**Comment by tomasmark79** [comment]
> Mám tě. Pokud se to stane znovu a mohu to důsledně znovu vytvořit, otevřu zprávu na AMD a propojím ji zde (pokud je veřejně přístupná).
> 
> Děkuji!

What about AMD? Does they any answer?
