### ISSUE TITLE
repo is missing a changelog

### ISSUE THREAD

**Issue by Pomax** [obsproject/obs-studio#10275]
### Operating System Info

Other

### Other OS

n/a

### OBS Studio Version

30.1.0-beta1

### OBS Studio Version (Other)

n/a

### OBS Studio Log URL

n/a

### OBS Studio Crash Log URL

n/a

### Expected Behavior

The repo is missing a CHANGELOG file. 

### Current Behavior

It is impossible to find out what changed between tags except by doing a source comparison, which is not even remotely a substitute for a proper change log.

### Steps to Reproduce

Look at the repo. It has no changelog file.

**Comment by tt2468** [comment]
This is not a bug. Furthermore, we attach a changelog to every release: https://github.com/obsproject/obs-studio/releases

**Comment by WizardCM** [comment]
Changelogs are written as part of the tag, and as part of the GitHub release.

This can be viewed via `git show -s --format=%B 30.1.0-beta1`

**Comment by Pomax** [comment]
Cheers. "viewing the changelog using git" is one of those "you _can_, but no normal person ever will" (that's more something for the dev team itself, not users) but having the changelog be part of the releases page works I guess.

A real changelog will still be a great idea though, especially since OBS installs with a `data/obs-studio` dir that is already contains similar text files like the authors file and license. The perfect place to also put the readme and changelog.
