### ISSUE TITLE
Get Safe Mode prompt on every startup

### ISSUE THREAD

**Issue by LinuxMint20** [obsproject/obs-studio#10274]
### Operating System Info

Other

### Other OS

Linux Mint 21.3, "Vanessa"

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.0.1 64 Bit

### OBS Studio Log URL

https://obsproject.com/logs/rbuDiNGKJCNQZdjO

### Expected Behavior

I'd really like that prompt to either go away, or find out whats causing it and rectify it. immediately.

### Current Behavior

OBS opens with the safe mode prompt, every time, even when I click exit or use the x button in the top right of the window.

### Steps to Reproduce

1. Download and install OBS
2. install the plugins listed in the log
3. Close down the program using the methods described above and reopen
...

### Anything else we should know?

Im using Linux Mint with a Nvidia GeForce RTX 2050 on Performance Mode and have 2 pre-rendered screens listed in the log.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
