### ISSUE TITLE
CRASH when delete source

### ISSUE THREAD

**Issue by ogaaaan** [obsproject/obs-studio#10282]
### Operating System Info

Windows 11

### OBS Studio Version

30.1.0-beta1

### OBS Studio Log URL

https://obsproject.com/logs/IyhkG0pFIB515W1d

### OBS Studio Crash Log URL

https://obsproject.com/logs/vwVOj3FhttcNaWnX

### Expected Behavior

my obs always crash when deleting any source.
everytime.

### Current Behavior

crashed

### Steps to Reproduce

1. select source (any)
2. click delete button
3. crash

**Comment by Fenrirthviti** [comment]
Duplicate of #10245

**Comment by Fenrirthviti** [comment]
Update the Stream Deck software, and this should be fixed.

**Comment by ogaaaan** [comment]
thanks!!
