### ISSUE TITLE
OBS ignores output settings and sets rate control to CBR

### ISSUE THREAD

**Issue by jamesWalker55** [obsproject/obs-studio#10283]
### Operating System Info

Windows 10

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/lrvu93K8m97BkBnB

### Expected Behavior

I have my output settings set to the following:

![image](https://github.com/obsproject/obs-studio/assets/30405220/045a8767-2c73-4e96-ac45-f3d45a2b0657)

The rate control is set to CQP. However, the output bitrate hovers around 2500-3000 kbps. The log shows that OBS is still using CBR when streaming:

```
21:09:39.306: [obs-nvenc: 'advanced_video_stream'] settings:
21:09:39.306: 	codec:        H264
21:09:39.306: 	rate_control: CBR
21:09:39.306: 	bitrate:      2500
21:09:39.306: 	cqp:          20
21:09:39.306: 	keyint:       60
21:09:39.306: 	preset:       p6
21:09:39.306: 	tuning:       hq
21:09:39.306: 	multipass:    qres
21:09:39.306: 	profile:      high
21:09:39.306: 	width:        1280
21:09:39.306: 	height:       720
21:09:39.306: 	b-frames:     4
21:09:39.306: 	lookahead:    true
21:09:39.306: 	psycho_aq:    true
```

### Current Behavior

It uses CBR instead of my settings as above.

### Steps to Reproduce

1. Install OBS fresh
2. Skip stream settings detection tool
3. Go to settings and set configuration as shown in the screenshot above
4. Set up streaming to YouTube
5. Start streaming
6. Bitrate is limited to around 2500-3000 kbps, log shows it is using CBR

**Comment by Gol-D-Ace** [comment]
That's standard OBS behaviour.
IF you need to bypass it, select "custom" service in settings > stream.

**Comment by Fenrirthviti** [comment]
Streaming using rate control methods like that is generally discouraged, for a variety of reasons.

This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
