### ISSUE TITLE
windows build error

### ISSUE THREAD

**Issue by gihon12312340** [obsproject/obs-studio#10287]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

28.1

### OBS Studio Log URL

https://github.com/obsproject/obs-studio/wiki/Build-Instructions-For-Windows

### Expected Behavior

build success

### Current Behavior

`CI/build-windows.ps1 -Choco`
When I ran this line of code, the following issue occurred.

...................................
Call Stack (most recent call first):
  plugins/win-dshow/CMakeLists.txt:102 (obs_status)

-- OBS:  ENABLED    win-dshow
-- OBS:  ENABLED    win-capture
-- Found Detours: C:/jerry/obs-build-dependencies/windows-deps-2022-08-02-x64/lib/../lib/detours.lib  
-- Found Vulkan: C:/jerry/obs-build-dependencies/windows-deps-2022-08-02-x64/lib/vulkan-1.lib (found version "1.3.216")  missing components: glslc glslangValidator
-- OBS:  ENABLED    graphics-hook
-- OBS:  ENABLED    get-graphics-offsets
-- OBS:  ENABLED    inject-helper
-- OBS:  ENABLED    decklink
-- OBS:  ENABLED    win-mf
-- OBS:  ENABLED    obs-qsv11
-- OBS:  ENABLED    obs-text
-- Found LibVLC: C:/jerry/obs-build-dependencies/vlc-3.0.0-git/include/vlc  
-- OBS:  ENABLED    vlc-video
-- OBS:    -        obs-vst uses bundled VST headers
-- OBS:  ENABLED    obs-vst
CMake Warning at cmake/Modules/ObsHelpers.cmake:446 (message):
  OBS: enc-amf plugin not found.
Call Stack (most recent call first):
  plugins/CMakeLists.txt:32 (obs_status)

-- OBS:  DISABLED   Realsense camera plugin support
CMake Error at plugins/obs-browser/CMakeLists.txt:3 (legacy_check):
  Unknown CMake command "legacy_check".

-- Configuring incomplete, errors occurred!
cmake -S . -B build64 -G Visual Studio 17 2022 -DCMAKE_GENERATOR_PLATFORM="x64" -DCMAKE_SYSTEM_VERSION="10.0.18363.657" -DCMAKE_PREFIX_PATH:PATH="C:\jerry\obs-build-dependenci
es\windows-deps-2022-08-02-x64" -DCEF_ROOT_DIR:PATH="C:\jerry\obs-build-dependencies\cef_binary_5060_windows_x64" -DENABLE_BROWSER=ON -DVLC_PATH:PATH="C:\jerry\obs-studio/../o 
bs-build-dependencies/vlc-3.0.0-git" -DENABLE_VLC=ON -DCMAKE_INSTALL_PREFIX="build64/install" -DVIRTUALCAM_GUID="" -DTWITCH_CLIENTID="" -DTWITCH_HASH="" -DRESTREAM_CLIENTID="" 
 -DRESTREAM_HASH="" -DYOUTUBE_CLIENTID="" -DYOUTUBE_CLIENTID_HASH="" -DYOUTUBE_SECRET="" -DYOUTUBE_SECRET_HASH="" -DCOPIED_DEPENDENCIES=OFF -DCOPY_DEPENDENCIES=ON -DBUILD_FOR_ 
DISTRIBUTION="OFF"  -Wno-deprecated -Wno-dev --log-level=ERROR exited with non-zero code 1.
At C:\jerry\obs-studio\CI\include\build_support_windows.ps1:137 char:9
+         throw "${Command} ${CommandArgs} exited with non-zero code ${ ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (cmake -S . -B b...on-zero code 1.:String) [], RuntimeException
    + FullyQualifiedErrorId : cmake -S . -B build64 -G Visual Studio 17 2022 -DCMAKE_GENERATOR_PLATFORM="x64" -DCMAKE_SYSTEM_VERSION="10.0.18363.657" -DCMAKE_PREFIX_PATH:PATH  
   ="C:\jerry\obs-build-dependencies\windows-deps-2022-08-02-x64" -DCEF_ROOT_DIR:PATH="C:\jerry\obs-build-dependencies\cef_binary_5060_windows_x64" -DENABLE_BROWSER=ON -DVLC   
  _PATH:PATH="C:\jerry\obs-studio/../obs-build-dependencies/vlc-3.0.0-git" -DENABLE_VLC=ON -DCMAKE_INSTALL_PREFIX="build64/install" -DVIRTUALCAM_GUID="" -DTWITCH_CLIENTID="    
 " -DTWITCH_HASH="" -DRESTREAM_CLIENTID="" -DRESTREAM_HASH="" -DYOUTUBE_CLIENTID="" -DYOUTUBE_CLIENTID_HASH="" -DYOUTUBE_SECRET="" -DYOUTUBE_SECRET_HASH="" -DCOPIED_DEPEND    
ENCIES=OFF -DCOPY_DEPENDENCIES=ON -DBUILD_FOR_DISTRIBUTION="OFF"  -Wno-deprecated -Wno-dev --log-level=ERROR exited with non-zero code 1.

### Steps to Reproduce

1.CI/build-windows.ps1 -Choco
2.
3.
...

### Anything else we should know?

Please tell me how to solve it, thank you very much!

**Comment by derrod** [comment]
Your git checkout is out of date, update it and the submodules, then actually follow the instructions.

**Comment by gihon12312340** [comment]
"So, am I unable to build version 28.1?"

**Comment by derrod** [comment]
Building older versions is unsupported, but the second part of what I said is probably the issue, you need to do a recursive checkout so the submodules are the correct version.
