### ISSUE TITLE
Not possible to uninstall or disable the OBS virtual camera på MacOS Sonoma (M1/M2)

### ISSUE THREAD

**Issue by pertoft** [obsproject/obs-studio#10286]
### Operating System Info

macOS 14

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/r3dOzKfg9gBAECyV

### Expected Behavior

When I uninstall OBS i expect the OBS camera to be removed.

### Current Behavior

The OBS camera is still loaded after uninstallation. Its not possible to unload the system extension, even when the files are deleted in Library

### Steps to Reproduce

1. Install OBS
2. Grant all permissions
3. Uninstall
4. Follow camera uninstall guide: https://obsproject.com/kb/virtual-camera-troubleshooting
5. Delete sudo rm -rf /Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin

**Comment by jcm93** [comment]
To remove the virtual camera extension in macOS 14, you specifically need to drag OBS to the trash via Finder (and follow the password prompt to remove a system extension accordingly). The documentation you linked is unfortunately outdated and applies only to the legacy DAL plugin, which is no longer functional as of macOS 14. I think that a better flow for uninstallation/installation is desired, but just hasn't yet been implemented.

**Comment by pertoft** [comment]
I have also tried that. 
1. Installed OBS (again)
2. Dragged it to the trashcan.
3. Rebooted.

OBS camera is still there

**Comment by PatTheMav** [comment]
You might need to start the virtual camera at least once after installed OBS again to ensure that the camera extension that shipped with OBS is installed/overwrites any existing installation.

Once that was successful (the marketing and build version match), then removing the app in Finder will also trigger a prompt for permission to also remove the associated extension.

**Comment by jcm93** [comment]
I would add to make sure OBS is always in /Applications when attempting install or removal, which should be a given but hasn't been mentioned specifically. 

It is also prudent to make sure there are no existing copies of OBS in the Trash when you drag it there, as I have seen system extension removal fail in that circumstance for other programs.

In future, I'd recommend visiting the support channels before filing here as well.

**Comment by ZagrebaBogdan** [comment]
![Image](https://github.com/user-attachments/assets/2ca119a2-1636-43cc-bd46-df244712311b)

System Settings -> General (Scroll down)-> Camera Extensions and turn off obs virtual camera
