### ISSUE TITLE
undefined symbol: _Zls6QDebugRK11QDockWidget, version Qt_6

### ISSUE THREAD

**Issue by cakeisamadeupdrug** [obsproject/obs-studio#10280]
### Operating System Info

Other

### Other OS

openSUSE Tumbleweed

### OBS Studio Version

30.0.2

### OBS Studio Log URL

NA

### Expected Behavior

Launch OBS from GUI or command line, and OBS launches.

### Current Behavior

OBS is not launching.

### Steps to Reproduce

1. Launch OBS from the terminal to read the message after it fails to launch
2. Read the message after it fails to launch

### Anything else we should know?

There was an update to Qt 6 on the 16th of February that seems to have removed the symbol _Zls6QDebugRK11QDockWidget. As a result OBS will not launch.

Launching from the terminal results in:

`obs: symbol lookup error: obs: undefined symbol: _Zls6QDebugRK11QDockWidget, version Qt_6
`

Apologies for the lack of a logfile, but as the issue is preventing OBS from launching at all there is no log to speak of.

**Comment by tytan652** [comment]
This is a packaging issue (the package needs to be rebuilt against Qt 6 because of potential ABI breakage), please report it to the distribution bug tracker.

Best regards, tytan652
