### ISSUE TITLE
Broken Functionality when Adding "Browser" Source

### ISSUE THREAD

**Issue by graywilson** [obsproject/obs-studio#10297]
### Operating System Info

Windows 11

### OBS Studio Version

30.1.0-beta1

### OBS Studio Log URL

https://obsproject.com/logs/SKYsSJaMoqiRRlDV

### Expected Behavior

Upon adding the 'Browser' source to the 'Scene' in the OBS program, the expected behavior was that the application would successfully create and integrate the browser source without any errors or disruptions. After the addition, the anticipated outcome was to see the browser content seamlessly displayed in the scene without any interruptions or rendering issues.

### Current Behavior

The program throws an error when adding the 'Browser' source to the 'Scene.' After adding the source, issues arise on the preview canvas with several observed behaviors:

1) 'Browser' sources disappear, and after some time, they reappear in a cycle with a constant periodicity of about 20 seconds.
2) The preview window hangs along with other sources like 'Screen Capture' or 'Game Capture,' and when attempting to turn off OBS, an error occurs.
3) The preview screen stretches significantly, artifacts appear, and the application crashes. Also, artifacts resembling a broken video chip are observed in all three cases.
When removing the 'Browser' source, all errors disappear, and OBS works stably without issues. This problem is observed in OBS versions 28, 29, and 30 on a 64-bit system. However, in version OBS-Studio-27.2.4-Full-x86, this issue is resolved, and adding multiple 'Browser' sources does not lead to any errors, ensuring stable operation.

Redmibook 15 2023 7840HS 16 GB
Processor with AMD Ryzen 7 7840HS w/ Radeon 780M Graphics.
Windows has just been reinstalled, and there are no extra programs yet.
AMD drivers are up to date.
Windows is updated to the latest version.

Once again, without the 'Browser' source or after removing it, various OBS versions starting from 27 work correctly without errors.
I have read various articles and guides on troubleshooting errors in OBS, but it didn't yield any results, except for installing the 32-bit version.

Error log, while writing a bug report and encountering the errors shown in the screenshots.
https://obsproject.com/logs/B0kEevoMrRKOHpp6

Disable hardware acceleration for the 'Browser' source in the settings, tried it first!

### Steps to Reproduce

1. install obs
2. add source "browser"
3.
...

### Anything else we should know?

Screenshots
![Screenshots1](https://github.com/obsproject/obs-studio/assets/33847242/3bfd6393-3a94-47c2-aca8-9be96d8ad839)
![Screenshots2](https://github.com/obsproject/obs-studio/assets/33847242/4bf81296-de3f-43fd-883a-719af90ccee1)
![Screenshots3](https://github.com/obsproject/obs-studio/assets/33847242/2abf831d-f210-469c-8c4e-9ffc69c05f4f)
![Screenshots4](https://github.com/obsproject/obs-studio/assets/33847242/7d95d476-e43d-44c4-bdcb-0f10bd5b1136)
![Screenshots5](https://github.com/obsproject/obs-studio/assets/33847242/8f3b5fc2-0c3f-476c-83df-d5336529229a)

**Comment by Fenrirthviti** [comment]
Please also provide the crash log. At first look, this appears to be an issue specific to your system. The crash log you took a screenshot of the dialog for should help identify what might be going on.

**Comment by graywilson** [comment]
> Please also provide the crash log. At first look, this appears to be an issue specific to your system. The crash log you took a screenshot of the dialog for should help identify what might be going on.

1) Failed to recreate D3D11: Failed to create swap RTV (80070057)
2) Failed to recreate D3D11: Failed to create swap RTV (80070057)
3) Failed to recreate D3D11: Failed to create swap RTV (80070057)
...

**Comment by Fenrirthviti** [comment]
We typically require the full crash logs that OBS saved, but those errors indicate that your GPU driver is crashing, which is what is taking down the browser source (and likely other parts of OBS) with it. Not much we can do, unfortunately.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
