### ISSUE TITLE
Plasma 6 OBS Screencast issue

### ISSUE THREAD

**Issue by Melechtna** [obsproject/obs-studio#10310]
### Operating System Info

Windows 11

### Other OS

Fedora 40

### OBS Studio Version

30.1.0-beta1

### OBS Studio Log URL

https://obsproject.com/logs/ZLfi9ByuvXnWnucZ

### Expected Behavior

It can screen capture as it did in previous plasma versions

### Current Behavior

It does not for me, I get the error 
warning: [pipewire] Failed to start screencast, denied or cancelled by user

But others do not, and I'm been scouring my configs for anything that could be causing this behaviour and find nothing

### Steps to Reproduce

1.Launch OBS in Plasma 6
2.Select a Window
3.Get nothing

### Anything else we should know?

I have another friend who is using Plasma 6 in Fedora 40, and it just works for them, but we can't determine what's different between our systems.

**Comment by Melechtna** [comment]
Making a new user account, OBS just works, so as slightly suspected, it's a user config issue, but no telling which one.

**Comment by Fenrirthviti** [comment]
I'd recommend trying our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for further support assistance.

Thank you!

**Comment by MEXAHOTABOP** [comment]
This ticket was one of first when i seek for solution, problem was that some time after arch update to plasma 6, pipewire begin to require group video to capture windows, and possibly audio as well, but i didn't tested it.

usermod -a -G audio user_name
usermod -a -G video user_name
And relogin to apply changes
