### ISSUE TITLE
OBS Always crashed "GPU process isn't usable. Goodbye"

### ISSUE THREAD

**Issue by imamulakhyar93** [obsproject/obs-studio#10311]
### Operating System Info

macOS 14

### Other OS

Intel version

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/AHfaTtPB9cDiNFLB

### Expected Behavior

It should not be crahsed

### Current Behavior

It's crashed

### Steps to Reproduce

1. Open OBS
2. Wait until 3-5 seconds
3. Its crashed / closed

### Anything else we should know?

It seems due to the GPU of chromium. on my console its show this
```
FATAL:gpu_data_manager_impl_private.cc(451)] GPU process isn't usable. Goodbye.
```

**Comment by gxalpha** [comment]
I'm fairly certain there is no real Mac with an i9-9900KF and an RX 6900 XT, so this setup is unsupported.

**Comment by MattyFresh68** [comment]
I'm pretty sure that's a hackintosh

**Comment by imamulakhyar93** [comment]
> I'm pretty sure that's a hackintosh. Actually might be an actual mac running the 6900 as egpu?

yes, it's a Hackintosh.

> I'm fairly certain there is no real Mac with an i9-9900KF and an RX 6900 XT, so this setup is unsupported.

ah, noted that. maybe I need to try another config on my Hackintosh, thanks 🙏
