### ISSUE TITLE
OBS and ARMA 3 game in full screen mode. Problem with OBS game capture mode

### ISSUE THREAD

**Issue by WolfRock13** [obsproject/obs-studio#10315]
### Operating System Info

Windows 10

### OBS Studio Version

30.1.0-beta1

### OBS Studio Log URL

https://github.com/obsproject/obs-studio/files/14464631/2024-03-01.22-39-58.txt

### Expected Behavior

For several years now I have not been able to find a solution to the problem related to the fact that the game ARMA 3 purchased on Steam (not a pirated version) does not work with OBS. In the game itself I set it to full screen. In OBS I select the source “game capture” and there is nothing. The only thing I noticed is that OBS captures the very first frame from the game (the splash screen when you turn on the game) and does not capture any more. Below I attach a screenshot of the game's splash screen. This is the first frame from game. Then the game continues to work, but the OBS seems to have captured this frame of the initial splash screen and froze. The OBS itself works great. But not after this cutscene, the game continues, but the obs cannot capture anything else and does not display anything
[2024-03-01 22-39-58.txt](https://github.com/obsproject/obs-studio/files/14464631/2024-03-01.22-39-58.txt)

### Current Behavior

I don't know how to fix this. Maybe there is some way? Or this game uses some non-standard display mode and OBS does not support it.

### Steps to Reproduce

I just launch the obs, then the game and only see the first frame from the game.

### Anything else we should know?

Sorry if I didn't format the request correctly, this is just my first request and communication on GitHub. I don’t understand well how to communicate with developers on GitHub.
[2024-03-01 22-39-58.txt](https://github.com/obsproject/obs-studio/files/14464599/2024-03-01.22-39-58.txt)
![1](https://github.com/obsproject/obs-studio/assets/24271818/dba1ec4b-f046-405c-860e-fe71af9fe3a3)

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by WolfRock13** [comment]
Thank you!

пт, 1 мар. 2024 г. в 23:32, Joel Bethke ***@***.***>:
