### ISSUE TITLE
OBS Studio - 30.0.2 + Qt 6.x.x -> error: Cannot mix incompatible Qt library

### ISSUE THREAD

**Issue by darkicekeel** [obsproject/obs-studio#10317]
### Operating System Info

Other

### Other OS

Gentoo "2.14" AMD64 Kernel Version: Linux 6.1.19

### OBS Studio Version

30.0.2

### OBS Studio Log URL

cannot start the GUI

### Expected Behavior

starting of the program

### Current Behavior

nothing on screen. if i start obs from commandline, this is the output

debug: Found portal inhibitor
debug: Attempted path: share/obs/obs-studio/locale/en-US.ini
debug: Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
debug: Attempted path: share/obs/obs-studio/locale.ini
debug: Attempted path: /usr/share/obs/obs-studio/locale.ini
debug: Attempted path: share/obs/obs-studio/locale/it-IT.ini
debug: Attempted path: /usr/share/obs/obs-studio/locale/it-IT.ini
info: Using preferred locale 'it-IT'
debug: Attempted path: share/obs/obs-studio/themes/Yami.qss
debug: Attempted path: /usr/share/obs/obs-studio/themes/Yami.qss
info: Using EGL/X11
info: CPU Name: Intel(R) Celeron(R) J4105 CPU @ 1.50GHz
info: CPU Speed: 1497.600MHz
info: Physical Cores: 4, Logical Cores: 4
info: Physical Memory: 7600MB Total, 1640MB Free
info: Kernel Version: Linux 6.1.19-gentoo
info: Distribution: Gentoo "2.14"
info: Desktop Environment: XFCE
info: Session Type: tty
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.21.1
info: Qt Version: 6.6.2 (runtime), 6.6.2 (compiled)
info: Portable mode: false
error: Cannot mix incompatible Qt library (6.6.1) with this library (6.6.2)
Annullato

### Steps to Reproduce

1.
2.
3.
...

### Anything else we should know?

I've just updated my system and obs-studio isn't starting anymore.
of course it's Qt related, i'd like to know how to solve.
on my distro it's not available anymore Qt 5.x

**Comment by kkartaltepe** [comment]
You'll need to ask your distribution how to correctly build and maintain software on it, as we do not support gentoo.

**Comment by darkicekeel** [comment]
i'm gonna try on some channels, if you want i'll keep reporting here

**Comment by darkicekeel** [comment]
ok the thing seems to be solved, I had to remove the -qt5 I had in my make.conf, recompile some packages wanting qt6 and asked for it at an emerge -avND world, and at that point obs started working again.
