### ISSUE TITLE
Camera locked in OBS, unable use in the browser

### ISSUE THREAD

**Issue by yozachar** [obsproject/obs-studio#10327]
### Operating System Info

Other

### Other OS

ArchLinux

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/MBepOM7SaWZ1dsgs

### Expected Behavior

OBS provides the ability to disable/unload camera temporarily

### Current Behavior

Camera won't unload unless OBS is shutdown.

### Steps to Reproduce

1. Add a camera input.
2. Unable to unload the camera.

### Anything else we should know?

|Windows|Linux|
|---|---|
| ![Screenshot_2024-03-04_075903](https://github.com/obsproject/obs-studio/assets/38415384/15818261-0dc2-40dd-97bd-cb222737b25e) | ![image](https://github.com/obsproject/obs-studio/assets/38415384/9e5ccc13-2886-434d-abb2-1592aa4a5071) |
| `Deactivate` unloads the camera. | No such option is available. |

```
# System Details Report
---

## Report details
- **Date generated:**                              2024-03-04 08:08:46

## Hardware Information:
- **Hardware Model:**                              Lenovo ThinkBook 15 G5 ABP
- **Memory:**                                      24.0 GiB
- **Processor:**                                   AMD Ryzen™ 7 7730U with Radeon™ Graphics × 16
- **Graphics:**                                    AMD Radeon™ Graphics
- **Disk Capacity:**                               (null)

## Software Information:
- **Firmware Version:**                            LMCN16WW
- **OS Name:**                                     Arch Linux
- **OS Build:**                                    rolling
- **OS Type:**                                     64-bit
- **GNOME Version:**                               45.4
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.7.7-zen1-1-zen
```

**Comment by kkartaltepe** [comment]
Feel free to suggest/vote on features in our ideas page https://ideas.obsproject.com/ or on the similar section of the discord, but we do not use github issues for these.
