### ISSUE TITLE
Reference copies of sources with audio increase audio volume

### ISSUE THREAD

**Issue by fGeorjje** [obsproject/obs-studio#10325]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/LUvIxyUuP1BVjRo0

### Expected Behavior

Adding multiple copies of a single source that carries video and audio (e.g. Media Source, Browser Source with "Control Audio via OBS", etc.) should have no effect on the audio output.

### Current Behavior

The audio volume increases proportionally per source added. Audio monitoring on the source plays back at the original volume. The audio volume bar in the audio mixer does not change. **Except for very limited scenarios, users have no indication of this volume change happening.**

Examples:

- Browser Sources (by me): https://github.com/obsproject/obs-studio/assets/24189597/3027f507-c876-455d-a8c5-99ee1f16843e
- Browser and Media Sources (by @lackofcontent on the community discord): https://github.com/obsproject/obs-studio/assets/24189597/3c1055d0-64e8-440f-94dd-e88304ab8695
- Example of this happening live (Touhou Replay Showcase, March 3rd): https://www.twitch.tv/videos/2080528950?t=3h28m30s

### Steps to Reproduce

1. Add a source that carries audio with it (tested so far are Browser Source and Media Source, but likely applies to all audio carrying sources).
2. Make multiple **reference** copies of the source (e.g. to re-crop different areas of the source)

### Anything else we should know?

With the new "Capture Audio (BETA)" functionality on Game Captures that is likely being added in 30.1.0, this could really mess up people's audio if they are using multiple reference copies of a game capture to re-crop their games.

Discussion in the #development channel on the community server: https://discord.com/channels/348973006581923840/374636084883095554/1213925856028917800

**Comment by flaeri** [comment]
Just going to link these here:
https://github.com/obsproject/obs-studio/issues/2871#issuecomment-1261351922
https://github.com/obsproject/obs-studio/issues/5842

**Comment by Fenrirthviti** [comment]
Those appear to be related to nested scenes, where this does not. I'd say a nested scene, this is expected, but not just reference sources.

**Comment by datamattsson** [comment]
This issue is present on Mac as well. Highly annoying when you have different crops of the same AV source in the same scene.

**Comment by derrod** [comment]
There's no need to bump every old issue related to this. We are aware of this UX problem and there's a proposed fix for it in #10537 (at least in most cases, OBS's audio mixing is complicated and some features make solving this difficult).

**Comment by fGeorjje** [comment]
#10537 has made it into the 30.2 beta so this is now fixed!
