### ISSUE TITLE
Lagging on Screen Capture on Wayland.

### ISSUE THREAD

**Issue by Redoxahmii** [obsproject/obs-studio#10336]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/7PoCHmUvI5EO3jsN

### Expected Behavior

Should not be lagging the issue occurs only on Wayland and during screen capture.

### Current Behavior

Lagging a lot as soon as screen capture in enabled.
If i do window capture it works perfectly fine.

### Steps to Reproduce

1.Open OBS
2. Enable Screen Capture(pipewire)
3.
...

**Comment by kkartaltepe** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

**Comment by Redoxahmii** [comment]
The provided forums seem to be dead in terms of replying about this issue as this [post](https://obsproject.com/forum/threads/lagging-screen-capture-on-wayland-in-gnome.165767/) was made in April 7,2023 and there is no reply from any of the mods for the forum nor any confirmation or anything whether it is being worked on or just something that is going to exist for times to come.
