### ISSUE TITLE
Discard screen recorder appears twice and creates screen recorder anyway

### ISSUE THREAD

**Issue by Diog0o** [obsproject/obs-studio#10333]
### Operating System Info

Windows 11

### OBS Studio Version

30.1.0-rc1

### OBS Studio Log URL

https://obsproject.com/logs/aui0mftHgpYlLs3f

### Expected Behavior

When the "Discard" button is pressed the screen recorder should only be removed

### Current Behavior

When discard button is pressed the pop-up appears twice and created the screen recorder anyway

### Steps to Reproduce

1. Create a new screen recorder
2. Click in "Accept"
3. Click in the cross to close and select Discard
4. The pop-up will appear twice and create the screen recorder anyway

**Comment by andre-bento** [comment]
I will fix this bug

**Comment by RytoEX** [comment]
Does this also occur on OBS Studio 30.0.2, or is it new to OBS Studio 30.1.0?

**Comment by andre-bento** [comment]
> Does this also occur on OBS Studio 30.0.2, or is it new to OBS Studio 30.1.0?

This was happening in the latest version but I've already fixed it. I'm reviewing the final details before committing.

**Comment by RytoEX** [comment]
> > Does this also occur on OBS Studio 30.0.2, or is it new to OBS Studio 30.1.0?
> 
> This was happening in the latest version but I've already fixed it. I'm reviewing the final details before committing.

I'm asking specifically if it's a regression in 30.1.0 so we know how to prioritize the issue. "latest version" isn't specific enough.

**Comment by RytoEX** [comment]
I can confirm that this also happens in 30.0.2, so this is not new to 30.1.0 and is not a regression there.

**Comment by andre-bento** [comment]
> I can confirm that this also happens in 30.0.2, so this is not new to 30.1.0 and is not a regression there.

Ok, thank you.

**Comment by tytan652** [comment]
I dug a little and `OBSBasicProperties::reject()` which re-show a confirmation dialog is triggered when "Discard" is clicked.
