### ISSUE TITLE
 Cancel the creation of the screen recorder, creates it anyway

### ISSUE THREAD

**Issue by bugfixermaster** [obsproject/obs-studio#10332]
### Operating System Info

Windows 11

### OBS Studio Version

30.1.0-beta1

### OBS Studio Log URL

https://obsproject.com/logs/vvrD6OpumvlrFCRI

### Expected Behavior

When we cancel a screen recorder it should not create anything.

### Current Behavior

Even if canceled, the screen recorder is created anyway.

### Steps to Reproduce

1. Create a new screen recorder or anyother recorder available in the "+"
2. Click Accept
3.Then click Cancel
4. The recorder was created anyway

**Comment by derrod** [comment]
Once you add a source the properties dialog is automatically opened, dismissing that won't delete the source. This is not a bug.

**Comment by Diog0o** [comment]
I had a similar problem. When you create a screen recorder and then hit "Accept", if after you click on the top right corner to exit and select discard it will open the dialog box twice. Isn't that a bug ?

**Comment by derrod** [comment]
That's an actual bug, I'm aware of it but I don't know if it's tracked anywhere.

**Comment by Diog0o** [comment]
I didn't see it. I searched most of the bugs and dind't see nothing like that. Can I create the bug report and try to work on it ?
