### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Lone-WolfTV** [obsproject/obs-studio#10339]
### Operating System Info

Other

### Other OS

Window 8 

### OBS Studio Version

30.0.2

### OBS Studio Log URL

tried to get but it crashed  

### OBS Studio Crash Log URL

it crashes before i get

### Expected Behavior

Not to crash 

### Current Behavior

when i go on to Obs it crashes 

### Steps to Reproduce

1. Be better 
2. Don't slack 
3. 
4.
5.
...

### Anything else we should know?

I try open & get crash report but it crashes.

**Comment by derrod** [comment]
Windows 8 is not supported.

**Comment by Lone-WolfTV** [comment]
I switched it windows 7

**Comment by derrod** [comment]
Windows 7 is also not supported.

**Comment by Lone-WolfTV** [comment]
Streaming is my career this crashing situation needs to be fix asap

**Comment by Lone-WolfTV** [comment]
That's a lie because obs work fine with window 8 you need to stop lying

**Comment by Lone-WolfTV** [comment]
What about windows 11 because that's what my laptop is

**Comment by Lone-WolfTV** [comment]
Im not insulting im saying is that the whole windows 8 isn't supported is a
lie OBS was working fine with windows 8.

**Comment by Lone-WolfTV** [comment]
My laptop is windows 11 & obs is 100% supported as windows 8 or 7 i feel
like you're insulting me by thinking im lying.
