### ISSUE TITLE
Hotkeys will not begin a recording when in a fullscreen application on Linux.

### ISSUE THREAD

**Issue by Dazawassa** [obsproject/obs-studio#10348]
### Operating System Info

Other

### Other OS

Ubuntu 23.10

### OBS Studio Version

30.1.0-rc1

### OBS Studio Log URL

https://obsproject.com/logs/TppFD8GW5uX49QJM

### Expected Behavior

When in a video game I press the assigned hotkeys and they start and stop a recording.

### Current Behavior

Application does not start recordings when assigned keys are pressed in a full screen application.

### Steps to Reproduce

1. Open OBS.
2. Assign hotkeys to start recording.
3. Open a full screen application.
4. Press the assigned hotkeys to record.

### Anything else we should know?

I'm using Wayland if that causes any issues.

**Comment by tiberium-v** [comment]
In Wayland, obs has no global hotkey functionality, obs has to be the active window for his hotkeys. You have to run on the X11 display server for this feature at the moment.

**Comment by tytan652** [comment]
This is not a bug. Under Wayland, only focused windows can get keyboard shortcut.
OBS Studio needs to migrate to using the GlobalShortcut which is not simple, which is a feature request.

**Comment by gxalpha** [comment]
Closing per the above comments.

**Comment by cynthia2006** [comment]
Easy to close, hard to care for usability.
