### ISSUE TITLE
Underlined characters in widget titles rendered incorrectly as ampersands in KDE6

### ISSUE THREAD

**Issue by GloriousEggroll** [obsproject/obs-studio#10341]
### Operating System Info

Other

### Other OS

Fedora 40, Nobara 39

### OBS Studio Version

30.1.0-rc1

### OBS Studio Log URL

https://obsproject.com/logs/kTk1mXEjWlGxBQTE

### Expected Behavior

Characters should be underlined instead of showing a prefixed ampersand (&)

### Current Behavior

The random ampersands (&) where underlined characters should be in Scenes/Sources etc:

![obsbug](https://github.com/obsproject/obs-studio/assets/11287837/6ed26416-83c4-451a-8cfe-970e0cfcb862)

### Steps to Reproduce

i was hitting it in Nobara first, so I spun up a vanilla fedora 40 VM and was able to reproduce
it only happens with OBS + KDE 6
furthermore I can do `XDG_CURRENT_DESKTOP=gnome` and it works around the bug

Download Fedora 39 ISO and create a VM
Update:
`sudo dnf update --refresh`
Upgrade to Fedora 40:
```
sudo dnf install dnf-plugin-system-upgrade
sudo dnf system-upgrade download --releasever=40
sudo dnf system-upgrade reboot
```
Install kde 6:
```
sudo dnf install @kde-desktop
```
Log out then log into Plasma.

Install OBS
```
sudo dnf install obs-studio
```

Run it and the issue should be reproduced. I've confirmed it does not happen with KDE 5 or in Gnome.

**Comment by derrod** [comment]
The translation strings for dock titles have no `&` so I have no clue how they got there...

What does your `en-US.ini` for the main UI look like?

**Comment by GloriousEggroll** [comment]
> The translation strings for dock titles have no `&` so I have no clue how they got there...
> 
> What does your `en-US.ini` for the main UI look like?

unmodified, i rebuilt the package from source, same issue.

issue also goes away if i change the default theme from Yami to system

**Comment by derrod** [comment]
Strange but probably some Qt or KDE bug, we don't set those anywhere as far as I can tell so no idea where it's getting them from.

**Comment by GloriousEggroll** [comment]
qt 6.6.2 by itself its fine -- i checked that
on gnome its fine too
its something with kde
for more info -- another way i also checked this is like so:

install fedora 39
install obs
update fedora 39 all the way
= perfectly fine

install kde on fedora 39 = perfectly fine

enable kde6 copr repo on fedora 39 and update = problem

then i thought ok maybe is the copr repo -- so i did a wipe and another install of fedora 39
upgraded it to 40
installed kde 6 from fedora;s official repos
= problem

**Comment by GloriousEggroll** [comment]
After more digging I found if I remove kf6-ki18n it fixes it. (forcefully via rpm -e --nodeps). Obv, not an actual fix but at least a lead on the cause

**Comment by GloriousEggroll** [comment]
It's a bug in QT. I tracked it down and managed to patch it.
https://bugs.kde.org/show_bug.cgi?id=482657

closing

**Comment by RytoEX** [comment]
Thanks for following up on the QTBUG.

**Comment by rez1-dev** [comment]
Got this same error on Manjaro yesterday. Tried installing, but the issue persists.

**Comment by tylerebowers** [comment]
Also happening to me, fresh install of openSuse TW. Amd 8050s GPU.

**Comment by XiokroDarc** [comment]
Still a bug, but give it to github "contributors" for contributing as much as they always do. Which is mark posts that bring this up as duplicates of this already closed post that is not planned on fixing the pretty bad ui bug.
