### ISSUE TITLE
Video lags in the new version (compared to the old one)

### ISSUE THREAD

**Issue by mxnix** [obsproject/obs-studio#10368]
### Operating System Info

Windows 10

### OBS Studio Version

30.1.0

### OBS Studio Log URL

https://obsproject.com/logs/LmOOnZhbb1KoX9Pl

### Expected Behavior

(OBS 30.0.2)

https://github.com/obsproject/obs-studio/assets/159849110/0f9ea471-4255-4161-802a-2876cde38af1

### Current Behavior

(OBS 30.1)

https://github.com/obsproject/obs-studio/assets/159849110/fe33973a-f591-4636-9ab3-a181fc0fc925

### Steps to Reproduce

1. Start recording video

### Anything else we should know?

https://obsproject.com/logs/hkkloHXb1vBoFHDt - OBS 30.02 Logs.
https://obsproject.com/logs/LmOOnZhbb1KoX9Pl - ONS 30.1 Logs.
I encountered a problem that after the update the video began to lag, but the load on the processor was insignificant. In OBS version 30.02 everything is fine.

**Comment by RytoEX** [comment]
Nothing in the OBS logs indicates that there was any rendering or encoder lag. This seems like the display itself was lagging somehow. The only thing I could maybe suggest is trying to update your GPU drivers.

**Comment by mxnix** [comment]
> Nothing in the OBS logs indicates that there was any rendering or encoder lag. This seems like the display itself was lagging somehow. The only thing I could maybe suggest is trying to update your GPU drivers.

I have updated the driver to the latest version available, but the problem still persists.

**Comment by RytoEX** [comment]
Please re-test in OBS Studio 30.1.0 but set "B Frames" to `0`.

**Comment by mxnix** [comment]
> Please re-test in OBS Studio 30.1.0 but set "B Frames" to `0`.

Fixed, your advice helped, thanks!

**Comment by RytoEX** [comment]
This is probably caused in part due to #10076.
