### ISSUE TITLE
HDR Metadata Missing

### ISSUE THREAD

**Issue by WilliamsGomes1** [obsproject/obs-studio#10363]
### Operating System Info

Windows 11

### OBS Studio Version

30.1.0

### OBS Studio Log URL

https://obsproject.com/logs/ODa2WnwU5iRmtFBX

### Expected Behavior

In the previous OBS Version (30.0.2) the recorded files would show correctly set as HDR10 compatible and contain the mastering display metadata.
[Media Info Export 1.txt](https://github.com/obsproject/obs-studio/files/14581893/Media.Info.Export.1.txt)

### Current Behavior

In the current OBS Version (30.1.0) the recorded file is missing the mastering display metadata, causing playback issues in MPC-HC and potentially in other softwares as well.
[Media Info Export 2.txt](https://github.com/obsproject/obs-studio/files/14581896/Media.Info.Export.2.txt)

### Steps to Reproduce

1. Run a HDR recording in the latest OBS Version.
2. Verify the files using MediaInfo or...
3. Play the recording back using MPC-HC.

### Anything else we should know?

I guess that's something related to the Lavf version used in the new OBS, as it was the only change I could see in both files info.
I also tested with HEVC and changed the container to MP4, same behaviour.

**Comment by RytoEX** [comment]
The files you linked result in 404 errors for me.

**Comment by RytoEX** [comment]
Please provide a test video created with OBS Studio 30.0.2 and one produced with OBS Studio 30.1.0.

**Comment by RytoEX** [comment]
I can confirm that checking with ffprobe 6.1.1, HDR recordings from OBS Studio 30.0.2 seem to have HDR metadata (CLL, luminance, mastering, etc.) while recordings from OBS Studio 30.1.0 do not. We'll investigate. Thanks.

**Comment by HyPeRXKo** [comment]
Hi, i don't know if i should open a new issue or not, but for me, the issue if not fixed, using the same exact settings for both versions, obs 30.0.2 correctly encode my video with the SMTPE ST 2086 format, while 30.0.1 does not. i tried NVENC AV1/HEVC (main&main10), both/3 does not work on the newer version, everything works fine when i rollback.

<details><summary>30.0.2 rollbacked mediainfo</summary>
<p>

General
Unique ID                   : 125666136826622762941119354880547458101 (0x5E8A6AE73E2A6809F73C6F205A118C35)
Complete name               : D:\Vidéos\OBS\Record\HDR Video du 22 March 2024 a 04h (6).mkv
Format                      : Matroska
Format version              : Version 4
File size                   : 7.04 MiB
Duration                    : 4 s 500 ms
Overall bit rate            : 13.1 Mb/s
Frame rate                  : 60.000 FPS
Writing application         : Lavf60.3.100
Writing library             : Lavf60.3.100
ErrorDetectionType          : Per level 1

Video
ID                          : 1
Format                      : AV1
Format/Info                 : AOMedia Video 1
Format profile              : Main@L5.0
HDR format                  : SMPTE ST 2086
Codec ID                    : V_AV1
Duration                    : 4 s 500 ms
Bit rate                    : 569 kb/s
Width                       : 2 560 pixels
Height                      : 1 440 pixels
Display aspect ratio        : 16:9
Frame rate mode             : Constant
Frame rate                  : 60.000 FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 10 bits
Bits/(Pixel*Frame)          : 0.003
Stream size                 : 313 KiB (4%)
Default                     : No
Forced                      : No
Color range                 : Limited
Color primaries             : BT.2020
Transfer characteristics    : HLG
Matrix coefficients         : BT.2020 non-constant
Mastering display color pri : Display P3
Mastering display luminance : min: 0.0000 cd/m2, max: 1000 cd/m2
Maximum Content Light Level : 1000
Maximum Frame-Average Light : 1000

Audio #1
ID                          : 2
Format                      : PCM
Format settings             : Little
Codec ID                    : A_PCM/FLOAT/IEEE
Duration                    : 4 s 480 ms
Bit rate mode               : Constant
Bit rate                    : 3 072 kb/s
Channel(s)                  : 2 channels
Sampling rate               : 48.0 kHz
Bit depth                   : 32 bits
Stream size                 : 1.64 MiB (23%)
Title                       : Track3
Default                     : No
Forced                      : No

Audio #2
ID                          : 3
Format                      : PCM
Format settings             : Little
Codec ID                    : A_PCM/FLOAT/IEEE
Duration                    : 4 s 480 ms
Bit rate mode               : Constant
Bit rate                    : 3 072 kb/s
Channel(s)                  : 2 channels
Sampling rate               : 48.0 kHz
Bit depth                   : 32 bits
Stream size                 : 1.64 MiB (23%)
Title                       : Track4
Default                     : No
Forced                      : No

Audio #3
ID                          : 4
Format                      : PCM
Format settings             : Little
Codec ID                    : A_PCM/FLOAT/IEEE
Duration                    : 4 s 480 ms
Bit rate mode               : Constant
Bit rate                    : 3 072 kb/s
Channel(s)                  : 2 channels
Sampling rate               : 48.0 kHz
Bit depth                   : 32 bits
Stream size                 : 1.64 MiB (23%)
Title                       : Track5
Default                     : No
Forced                      : No

Audio #4
ID                          : 5
Format                      : PCM
Format settings             : Little
Codec ID                    : A_PCM/FLOAT/IEEE
Duration                    : 4 s 480 ms
Bit rate mode               : Constant
Bit rate                    : 3 072 kb/s
Channel(s)                  : 2 channels
Sampling rate               : 48.0 kHz
Bit depth                   : 32 bits
Stream size                 : 1.64 MiB (23%)
Title                       : Track6
Default                     : No
Forced                      : No
</p>
</details> 

<details><summary>30.1.0 release mediainfo</summary>
<p>

General
Unique ID                   : 141430663312507864743529725088878641168 (0x6A668E11632D46113E248A83F1754010)
Complete name               : D:\Vidéos\OBS\Record\HDR Video du 22 March 2024 a 04h.mkv
Format                      : Matroska
Format version              : Version 4
File size                   : 16.6 MiB
Duration                    : 2 s 484 ms
Overall bit rate            : 56.2 Mb/s
Frame rate                  : 60.000 FPS
Writing application         : Lavf60.16.100
Writing library             : Lavf60.16.100
ErrorDetectionType          : Per level 1

Video
ID                          : 1
Format                      : AV1
Format/Info                 : AOMedia Video 1
Format profile              : Main@L5.0
Codec ID                    : V_AV1
Duration                    : 2 s 484 ms
Bit rate                    : 42.8 Mb/s
Width                       : 2 560 pixels
Height                      : 1 440 pixels
Display aspect ratio        : 16:9
Frame rate mode             : Constant
Frame rate                  : 60.000 FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 10 bits
Bits/(Pixel*Frame)          : 0.194
Stream size                 : 12.7 MiB (76%)
Default                     : No
Forced                      : No
Color range                 : Limited
Color primaries             : BT.2020
Transfer characteristics    : HLG
Matrix coefficients         : BT.2020 non-constant

Audio #1
ID                          : 2
Format                      : PCM
Format settings             : Little
Codec ID                    : A_PCM/FLOAT/IEEE
Duration                    : 2 s 453 ms
Bit rate mode               : Constant
Bit rate                    : 3 072 kb/s
Channel(s)                  : 2 channels
Sampling rate               : 48.0 kHz
Bit depth                   : 32 bits
Stream size                 : 920 KiB (5%)
Title                       : Track3
Default                     : No
Forced                      : No

Audio #2
ID                          : 3
Format                      : PCM
Format settings             : Little
Codec ID                    : A_PCM/FLOAT/IEEE
Duration                    : 2 s 453 ms
Bit rate mode               : Constant
Bit rate                    : 3 072 kb/s
Channel(s)                  : 2 channels
Sampling rate               : 48.0 kHz
Bit depth                   : 32 bits
Stream size                 : 920 KiB (5%)
Title                       : Track4
Default                     : No
Forced                      : No

Audio #3
ID                          : 4
Format                      : PCM
Format settings             : Little
Codec ID                    : A_PCM/FLOAT/IEEE
Duration                    : 2 s 453 ms
Bit rate mode               : Constant
Bit rate                    : 3 072 kb/s
Channel(s)                  : 2 channels
Sampling rate               : 48.0 kHz
Bit depth                   : 32 bits
Stream size                 : 920 KiB (5%)
Title                       : Track5
Default                     : No
Forced                      : No

Audio #4
ID                          : 5
Format                      : PCM
Format settings             : Little
Codec ID                    : A_PCM/FLOAT/IEEE
Duration                    : 2 s 453 ms
Bit rate mode               : Constant
Bit rate                    : 3 072 kb/s
Channel(s)                  : 2 channels
Sampling rate               : 48.0 kHz
Bit depth                   : 32 bits
Stream size                 : 920 KiB (5%)
Title                       : Track6
Default                     : No
Forced                      : No
</p>
</details>
