### ISSUE TITLE
monitoring by bluetooth audio fails if you get disconnected and does not resume when reconnected, You have to close OBS studio and re-open to hear through bluetooth again

### ISSUE THREAD

**Issue by andypbaker** [obsproject/obs-studio#10361]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/0OlLGloJ01NWOWTt

### Expected Behavior

When audio monitoring by bluetooth disconnects then reconnects, I expect monitoring to continue with the bluetooth device.

### Current Behavior

When audio monitoring by bluetooth disconnects then reconnects, it reverts to PC speakers / headphones, but when reconnected to bluetooth, it does not switch back to bluetooth

### Steps to Reproduce

1. connect bluetooth device.
2. start obs studio
3. hear monitored audio in bluetooth device
4. disconnect bluetooth device.
5. monitored audio reverts to pc speakers / headphones.
6. reconnect bluetooth device.
7. monitored audio continues to work through speakers / headphones.
8.
9.
...

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
