### ISSUE TITLE
An encoder error occurred while recording.

### ISSUE THREAD

**Issue by iambeingtracked** [obsproject/obs-studio#10365]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.0.2-4

### OBS Studio Log URL

https://obsproject.com/logs/uBijhq71NxiBUETB

### Expected Behavior

The recording should start without this issue.

### Current Behavior

It doesn't

### Steps to Reproduce

1. Install obs-studio through pacman, version 3.0.2-4
2. Use nvidia drivers (The issue occured with nvidia, nvidia-dkms and nvidia-free, versions 545 and 550)
3. Set the encoder to NVENC, H.264
4. see the issue
...

### Anything else we should know?

It worked just fine yesterday and now all of a sudden it doesn't. I also had other issues pop up while trying out different drivers, but still the recording didn't start. Also I can't change my encoder because after selecting it and pressing "apply" OBS crashes

**Comment by kkartaltepe** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
