### ISSUE TITLE
Screen record "infinite" duration

### ISSUE THREAD

**Issue by quiellll** [obsproject/obs-studio#10374]
### Operating System Info

Windows 10

### OBS Studio Version

30.1.0

### OBS Studio Log URL

https://obsproject.com/logs/egvtzHRFCTldTdf4

### Expected Behavior

Screen recorded a video, expected it to save it correctly with the actual duration (around 2:55 minutes)

### Current Behavior

When opening the video with different video players, the player indicates a seemingly random and very long duration. It begins with "26113:24", but as I scroll, the numbers for the current time mark and the ending time mark just go random, with numbers like "55893:06", "68426:43", "29269:31"...

### Steps to Reproduce

1. Select "screen record" as source
2. Start recording
3. Add some pauses in the recording with the designated pause button
4. Continue recording and stop the recording
5. Open the video file

### Anything else we should know?

If the programs that I have opened or running in background and/or recorded are relevant, here is a list:
- Microsoft Edge
- File Explorer
- Autodesk 3ds Max
- Unity 2022.3.20.f1
- Ubuntu (WSL)
- Task Manager
- OneDrive
- Razer Synapse

Also, here is a screenshot of the video player
![image](https://github.com/obsproject/obs-studio/assets/69222000/15158489-d3a8-4432-85c3-1b5d3fa11a76)

**Comment by RytoEX** [comment]
The applications running the background are probably not relevant. What media players are you checking resulting files in?

**Comment by quiellll** [comment]
I don't have any external players, but I tried with all the Win10 preinstalled ones:
- Photos
- Movies & TV
- Windows Media Player
- Media Player (windows 10 media player?)

**Comment by RytoEX** [comment]
Please try in any non-Microsoft media player, such as VLC or MPC-HC. Alternatively, switch your recording format to MP4 or MKV.

**Comment by quiellll** [comment]
Tried with VLC, iTunes, and I also uploaded it to OneDrive to check the web player. They all play correctly.

I could trim the video using ffmpeg (because I needed to hand in an assignment), and the trimmed video plays just fine. Still, such a weird behavior. I suppose it is a Windows player bug instead?

**Comment by RytoEX** [comment]
> Tried with VLC, iTunes, and I also uploaded it to OneDrive to check the web player. They all play correctly.
> 
> I could trim the video using ffmpeg (because I needed to hand in an assignment), and the trimmed video plays just fine. Still, such a weird behavior. I suppose it is a Windows player bug instead?

We believe it is a bug in Media Player, Movies & TV, and possibly whatever underlying components Windows uses to determine media file length. I've submitted a Feedback item to Microsoft and will attempt to escalate. Thanks for reporting!

**Comment by quiellll** [comment]
Thank you for your help!
