### ISSUE TITLE
Pipewire capturing does not works - black screen.

### ISSUE THREAD

**Issue by serhii-nakon** [obsproject/obs-studio#10371]
### Operating System Info

Other

### Other OS

Debian 12

### OBS Studio Version

30.1.0

### OBS Studio Log URL

https://obsproject.com/logs/fZ1sAOEP8vBmRwK2

### Expected Behavior

Capturing should works using pipewire and wayland session on Debian 12

### Current Behavior

Capturing does not work using pipewire and wayland session on Debian 12

### Steps to Reproduce

1. Just add Screen Capturing (pipewire) to scenes

**Comment by serhii-nakon** [comment]
Here screenshot. Also I forget to mention that I use Flatpak version of OBS.
![image](https://github.com/obsproject/obs-studio/assets/57632032/5fd1d1f4-65e9-47f0-9b60-3d4c5ca50351)

**Comment by serhii-nakon** [comment]
Does it possible because I has too old version of Pipewire server?

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by serhii-nakon** [comment]
@Fenrirthviti Sorry, also I found solution - I just updated pipewire from Debian backports and it works now.
`sudo apt -t bookworm-backports install --upgrade pipewire`

**Comment by serhii-nakon** [comment]
@Fenrirthviti Can you write requirements to Pipewire for Flatpak version, due when OBS was updated to 30 version it start incompatible with some Linux distributives that use older version of Pipewire and cause black screen on Wayland.

It should be very helpfully for others to find solution for their distributives in such cases.

**Comment by serhii-nakon** [comment]
It second time when I got problem like this. First time with Flatpak version on previous version of Debian - exactly the same situation that after update OBS it began to require newer version of Pipewire and just black screan on Wayland.

**Comment by wevansprojects** [comment]
> @Fenrirthviti Sorry, also I found solution - I just updated pipewire from Debian backports and it works now. `sudo apt -t bookworm-backports install --upgrade pipewire`

Thank you for this many Debian Stable users choose Flatpak so they can leave well alone core system packages. But its great to know there is a work around in Debian backports to help resolve it.

**Comment by tomasmark79** [comment]
I may confirm that backported pipewire update works as well here.

OBS 30.2.3 (flatpak)

```
OS: Debian GNU/Linux 12 (bookworm) x86_64 
Host: HP ZBook Firefly 14 inch G10 A Mobile Workstation PC SBKPF,SBKPFV2 
Kernel: 6.11.10+bpo-amd64 
Uptime: 3 mins 
Packages: 2935 (dpkg), 11 (flatpak) 
Shell: bash 5.2.15 
Resolution: 3840x2160 
DE: GNOME 43.9 
WM: Mutter 
WM Theme: Adwaita 
Theme: Adwaita [GTK2/3] 
Icons: Adwaita [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD Ryzen 7 PRO 7840HS w/ Radeon 780M Graphics (16) @ 5.137GHz 
GPU: AMD ATI c3:00.0 Phoenix1 
Memory: 2600MiB / 56016MiB 
```

**note**: required reboot after upgrade pipewire
