### ISSUE TITLE
auto-remuxing mkv with PCM produces invalid file

### ISSUE THREAD

**Issue by Penwy** [obsproject/obs-studio#10384]
### Operating System Info

Windows 11

### OBS Studio Version

30.1.0

### OBS Studio Log URL

https://obsproject.com/logs/lTuF3pnasBavtZul

### Expected Behavior

Auto-remuxing should produce a playable file

### Current Behavior

When recording to mkv with PCM 32 bit float with auto-remuxing on windows, the remuxed file is an invalid .mp4 file.
As can be seen in the log, OBS' media source itself refuses to play it, so this is likely not an issue of player support

### Steps to Reproduce

1. Enable auto-remux and PCM 32-bit audio encoder
2. Record
3. Try playing the remuxed file.
...

### Anything else we should know?

This does not reproduce on ubuntu 22.04, presumably because of the ifdef that checks for libavformat version

**Comment by RytoEX** [comment]
What happens if you manually remux the file?

**Comment by Penwy** [comment]
Manually remuxing also produces an invalid file, with the same error message in the log.
[Here](https://github.com/obsproject/obs-studio/files/14621460/2024-03-15.17-27-36.zip) is both the original file recorded in that log and the result of remuxing it to mp4 (manually)
(the original video is black without sound, that's normal, I hadn't added any source)

**Comment by pkviet** [comment]
Could you test also with other pcm formats ?
@Penwy

**Comment by pkviet** [comment]
Ok ignore , we don't offer anything else than 32 float
