### ISSUE TITLE
One shot GIFs do not play all their frames when using "Media Source"

### ISSUE THREAD

**Issue by XC3N** [obsproject/obs-studio#10386]
### Operating System Info

Windows 11

### OBS Studio Version

30.1.0

### OBS Studio Log URL

https://obsproject.com/logs/qS3njwf5uIqvksUm

### Expected Behavior

Playing a GIF added as "Media Source"
I want to play the GIF one shot, when directly triggered, and then disappear.

### Current Behavior

When triggered, the GIF plays about 90% of it's frames then disappear.

Settings:
![obs64_hYQBzpKUwk](https://github.com/obsproject/obs-studio/assets/31542509/fae6c63d-e1d6-403a-bfe6-518608ef978e)

An example of a gif I use:
![WDYLTF](https://github.com/obsproject/obs-studio/assets/31542509/50704cc8-1338-49d7-a6d8-6acfcea108c4)

### Steps to Reproduce

1. add "media source"
2. set up a local .gif file
3. uncheck "Restart playback when source becomes active"
4. Trigger the GIF (I use the controls below the preview window when the source is selected)
5. The gif plays about 90% of it's frames and then disappear
...

### Anything else we should know?

This problem does not happen when using "image" as source
The GIF plays properly when "loop" is checked

**Comment by RytoEX** [comment]
The provided GIF seems to play the same on my machine in both OBS Studio 30.0.2 and 30.1.0 and in Firefox and Chrome.

**Comment by XC3N** [comment]
> The provided GIF seems to play the same on my machine in both OBS Studio 30.0.2 and 30.1.0 when loaded as an Image Source or a Media Source and in Firefox and Chrome.
> 
> Please reproduce this without any third-party plugins and with a scene collection that only has the problematic image.

I am really confused, the GIF I sent you no longer have this issue, but this one still does. If I can bother you to test on this one as well while I do more tests.

![3headedmonkey](https://github.com/obsproject/obs-studio/assets/31542509/7b73a936-4cae-4e82-92d0-8377104d4993)

**Comment by derrod** [comment]
Tried with four different methods, image source (top left), media source (top right), window capture of browser (bottom left), and browser source (bottom right). Plays back fine on all of them.

https://github.com/obsproject/obs-studio/assets/3123295/24ff8d28-ba58-4140-a8e0-f331a25213be

**Comment by XC3N** [comment]
Ok, seems this is something on my side, I will investigate further. Thanks a lot for taking the time to test!

**Comment by Fenrirthviti** [comment]
closing per above.

As note, it's usually best to run these things through our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) first.

Thank you!

**Comment by XC3N** [comment]
@Fenrirthviti Do you mind re-opening this? The test provided by derrod is not following the steps to reproduce + I have reinstalled OBS and tried on two other computers and reproduced this issue.
