### ISSUE TITLE
Sidechain/Ducking Source not working with macOS screen capture

### ISSUE THREAD

**Issue by MysticalOS** [obsproject/obs-studio#10387]
### Operating System Info

macOS 14

### OBS Studio Version

30.1.0

### OBS Studio Log URL

https://obsproject.com/logs/aLVoVUAlUOvsXn9V

### Expected Behavior

When using Sidechain/Ducking with macOS screen capture, audio is not ducked at all regardless of settings.
This should hopefully still be possible even if using apples proprietary screen capture utility replayd since it's possible to still adjust audio output level via sliders normally.

### Current Behavior

No ducking occurs when speaking through selected mic/aux source, at all.

### Steps to Reproduce

1. use macOS screen Capture for audio
2. Use mic/aux for speaking
3. Setup a Sidechain/Ducking compressor on macOS screen Capture audio filters to duck audio using mic/aux
...

### Anything else we should know?

macOS 14.4 used.
Audio capture is using Rode USB mic but the properties of mic/aux is just "default" since that's default macOS audio device.
![Screenshot 2024-03-15 at 6 37 56 PM](https://github.com/obsproject/obs-studio/assets/1899149/5c72bc1d-35fd-4efa-9a07-78fcf93caafb)

**Comment by RytoEX** [comment]
Does this also happen in OBS Studio 30.0.2?

**Comment by MysticalOS** [comment]
I have not tested that. would downgrading to test it mess up any scenes/settings? I've even been on 30.1 beta for a while now cause 30.0.x tended to crash at launch or hang at launch with setup and reading over changesets weeks ago convinced me that 30.1 was more stable due to some macOS rewrites (and it was).

But I suspect where you're going with this is those very changesets could be source of issue 🤔

**Comment by MysticalOS** [comment]
Oh, i'm so dummy, it's actually working now, I had the ducking triggering at mic close threshold not mic open, so it just wasn't triggering cause I was speaking too shoftly, i had to shot in mic to trigger it (or fix settings) disregard haha
*embarassed

Promise I normally QA better.
