### ISSUE TITLE
Screen Recording - Black Screen (Flatpak Version)

### ISSUE THREAD

**Issue by imotos** [obsproject/obs-studio#10396]
### Operating System Info

Other

### Other OS

Debian 12

### OBS Studio Version

30.1.0

### OBS Studio Log URL

?

### Expected Behavior

capturing the screen should be working (sound & video)

### Current Behavior

capturing the screen doesn't work (only sound recording works)

### Steps to Reproduce

just select Screen Recording (buildin screen source)

### Anything else we should know?

After the last update..

**Comment by tytan652** [comment]
If no log is provided, this issue will be closed in a week.

**Comment by gxalpha** [comment]
No. Log files are mandatory, it will be closed now.
