### ISSUE TITLE
NVENC: Failed locking bitstream buffer: invalid param (8)

### ISSUE THREAD

**Issue by ShadiestGoat** [obsproject/obs-studio#10395]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

Git

### OBS Studio Log URL

https://obsproject.com/logs/JhYDtksc9Q1WGiEz

### Expected Behavior

I expect the ffmpeg nvenc based encodeer to work - ie. allow for recording/streaming.

### Current Behavior

The recording fails to even start. Same for streaming.

### Steps to Reproduce

1. Open OBS
2. Set video encoder to "NVIDIA NVENC H.264 (FFmpeg)"
3. Record
4. Cry when error message pops up

### Anything else we should know?

Using `nvidia-dkms` package (v 550.564.14-5), with nvidia-utils.
The gpu used is NVIDIA GeForce GTX 1650 Ti Mobile
I have optimus-manager, with the nvidia-only mode enabled.

**Comment by derrod** [comment]
The NVIDIA 550 drivers have a bug that prevents NVENC from working on TU117 GPUs, this was fixed in a hotfix driver update, not sure if that was released for Linux though.

**Comment by ShadiestGoat** [comment]
Thanks! Will test
