### ISSUE TITLE
Cannot install OBS 30.X on Ubuntu 23.10

### ISSUE THREAD

**Issue by smellyonionman** [obsproject/obs-studio#10393]
### Operating System Info

Ubuntu 23.10

### OBS Studio Version

30.1.0

### OBS Studio Log URL

Cannot install OBS, cannot create log

### Expected Behavior

I expected the .deb package installer to complete the installation process as it does on Ubuntu 22.04.

### Current Behavior

The apt package manager reports the following error:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help resolve the situation:

The following packages have unmet dependencies:
 obs-studio : Depends: libavcodec58 (>= 7:4.4) but it is not installable
              Depends: libavdevice58 (>= 7:4.4) but it is not installable
              Depends: libavformat58 (>= 7:4.4) but it is not installable
              Depends: libavutil56 (>= 7:4.4) but it is not installable
              Depends: libpython3.10 (>= 3.10.0) but it is not installable
              Depends: libswresample3 (>= 7:4.4) but it is not installable
              Depends: libswscale5 (>= 7:4.4) but it is not installable
              Depends: libx264-163 (>= 2:0.163.3060+git5db6aa6) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

### Steps to Reproduce

1. Begin with any Ubuntu OS version 24.10 or higher
2. Attempt to install OBS-studio using the given .deb file by either double-clicking it or typing into apt-get.

### Anything else we should know?

It seems that Ubuntu 23.10 is running newer versions of these packages, and those in the list were the packages in use by Ubuntu 22.04 LTS.

Now 23.10 is using:
```
libavcodec60
libavdevice60
libavformat60
libavutil58
libpython3.11
libx264-164
```

...I couldn't find alternatives for libwresample or libwscale, however.  I tried using `apt-get list libwresample* --installed` with no results.  Same with `libwscale*`.

I don't know much about making linux software, but if OBS can be compiled to work with newer and older versions of these packages at the same time that would hopefully solve everything.

**Comment by tytan652** [comment]
This deb file is only meant for 22.04, use the PPA to get 23.10 releases.
