### ISSUE TITLE
Can't set frame rate when create new video capture device

### ISSUE THREAD

**Issue by WIndFate** [obsproject/obs-studio#10398]
### Operating System Info

macOS 14

### OBS Studio Version

30.1.0

### OBS Studio Log URL

https://obsproject.com/logs/SMN1JuiBEAM9ozfv

### Expected Behavior

<img width="718" alt="截屏2024-03-18 4 30 34" src="https://github.com/obsproject/obs-studio/assets/14509638/5d36c849-26e0-4ad4-948c-6e0a2dfa14c2">
Can't set frame rate when create new video capture device

### Current Behavior

<img width="718" alt="截屏2024-03-18 4 30 34" src="https://github.com/obsproject/obs-studio/assets/14509638/b446b40a-e046-4e89-982b-a91946e7d723">

### Steps to Reproduce

It appeared suddenly, and I'm unable to reproduce it.

**Comment by RytoEX** [comment]
You must scroll down in the properties dialog and set a valid "Input format" and "Color space" before we can populate a list of valid entries for "Frame rate".
