### ISSUE TITLE
OBS-Websocket enable to serve request immediatly after successful connection

### ISSUE THREAD

**Issue by frogeater** [obsproject/obs-studio#10408]
### Operating System Info

Windows 10

### OBS Studio Version

30.1.0

### OBS Studio Log URL

https://obsproject.com/logs/BbRHd4lydSmEX5UN

### Expected Behavior

Immediate request after connection should be successfull.

### Current Behavior

The call to GetCurrentSceneCollection (or any other call) with BarRaider .net obs-websocket helper immediatly after successfull connection returns following error.
"ErrorCode: 207, Comment: OBS is not ready to perform the request."

### Steps to Reproduce

1. External program tries connection to websocket priodically
2. OBS is started
3. External program websocket connection succeeds
4. External program sends immediatly GetCurrentSceneCollection request
5. The call to GetCurrentSceneCollection returns "ErrorCode: 207, Comment: OBS is not ready to perform the request."

### Anything else we should know?

Previous issue #9991 :  OBS crashes on startup if websocket request comes too fast after connection

UPDATE : sometimes the call to GetCurrentSceneCollection does not return error or anything else ... it is waiting something ... and this is blocking the application ...
This is the log file in such case : https://obsproject.com/logs/ntKqoGdxwRoYNBzV

**Comment by tt2468** [comment]
This is intended behavior. If you get status 207, it means OBS hasn't finished loading yet.

**Comment by frogeater** [comment]
@tt2468 
I understand. Explicit status 207 is easy to handle and I already modified the application.
But why sometimes the request is waiting and does not generate explicit error status ?
This is what I mentionned in above UPDATE. This behavoir is disturbing me.

**Comment by tt2468** [comment]
obs-websocket clients often have layers of abstraction which are usually where issues like that stem from. As such, please reproduce this using a script and provide obs-websocket debug messaging to show that obs-websocket is not responding to the request.
