### ISSUE TITLE
Black Screen while recording in Wayland 

### ISSUE THREAD

**Issue by complex7** [obsproject/obs-studio#10413]
### Operating System Info

Other

### Other OS

Arch Linux 

### OBS Studio Version

30.1.0

### OBS Studio Log URL

i don't know

### Expected Behavior

i expect that OBS studio record the screen 

### Current Behavior

it is recording screen with audio 

### Steps to Reproduce

1.
2.
3.
...

### Anything else we should know?

However i am not conform that if it is due to my fault

https://github.com/obsproject/obs-studio/assets/142241144/c94d82b6-ba9e-4438-b760-d5b0927b16bb

**Comment by tytan652** [comment]
Closed since no log was provided.

**Comment by RytoEX** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
