### ISSUE TITLE
Some chat emojis appear as squares on OSD

### ISSUE THREAD

**Issue by superbonaci** [obsproject/obs-studio#10412]
### Operating System Info

Windows 11

### OBS Studio Version

30.1.0

### OBS Studio Log URL

not available

### Expected Behavior

Display the emoji

### Current Behavior

Paste this emoji in a Twitch chat:
🫢🫢🫢🫢

The overlay on video will display squares:

![pic](https://github.com/obsproject/obs-studio/assets/8339596/309aaa91-f757-4c14-b342-8405d448af29)

### Steps to Reproduce

1. send emoji to chat
2.
3.
...

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
