### ISSUE TITLE
High GPU usage when using video capture devices

### ISSUE THREAD

**Issue by ecoBlackCH** [obsproject/obs-studio#10429]
### Operating System Info

Windows 11

### OBS Studio Version

30.1.1

### OBS Studio Version (Other)

30.0.1

### OBS Studio Log URL

https://obsproject.com/logs/QePBK5BnqshRtt7a

### Expected Behavior

Fix

### Current Behavior

I am using a capture board called GC311 with OBS. Until recently (before the OBS or Geforce Experience update) it was working normally, but the game gets ridiculously slow when using OBS and the capture device. Disabling them improves it. So I used "MSI Afterburner" and found that the GPU power consumption is 900mV when OBS and capture board are used, and the 3D specification rate is 36%. This was not possible before and the GPU is not even idling and running OBS in boost state. Because of this, the game occupies a lot of spare space and the FPS drops. I don't know if the OBS optimization is lagging behind or if this is some kind of bug, but one thing I can tell you is that the OBS that was running idle a while ago is now running on boost, and I have tried every setting possible, but without success. I have tried all possible settings, but they did not work. I feel that optimization and countermeasures are needed on that side.

### Steps to Reproduce

1.Lunch OBS
2.Enable Capture Device
3.Check MSI After burner
4.Power and boost clocks can be checked.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by Fenrirthviti** [comment]
On further inspection, this is *potentially* a duplicate of https://github.com/obsproject/obs-studio/issues/9890
