### ISSUE TITLE
error, version 30.1.1, NVENC CODEC

### ISSUE THREAD

**Issue by AR-SEED** [obsproject/obs-studio#10431]
### Operating System Info

Windows 10

### OBS Studio Version

30.1.1

### OBS Studio Log URL

https://obsproject.com/logs/3WOi6CF7FDHaxgkp

### Expected Behavior

Normal Record

### Current Behavior

The new update (30.1.1) broke my nvidia codec.
The NVENC Codec simply appears as not supported by my video card driver, but it is in the latest version in my case, 474.82 (GTX 760), and I can't start with the NVENC codec (when I want to)

NOTE: I saw the note "Note: NVIDIA users may need to update their GPU drivers to 531.61 or newer." for OBS Studio version 30.1.1, but the latest version for my video card is 474.82 (NVIDIA GTX 760).

OBS is telling me to update the driver but it's already on the latest for GTX 760
![error OBS](https://github.com/obsproject/obs-studio/assets/135024074/a836aca0-35e9-44b9-84b0-9e9d0c2506f0)

### Steps to Reproduce

1.i start
2. I try start recording as usual, without changes
3. and the new version says it is out of date
...

**Comment by RytoEX** [comment]
If you can, please test #10445.

**Comment by guihkx** [comment]
I know I'm a bit late, but I just tested the fix on my GTX 660 on Windows 10 with 474.82 drivers, and I NVENC works again. Thank you very much, @RytoEX!

It initially broke with 4a8e8bb1bdf2d1efaae75893a544bddab0e2bb2a, which I'm aware it's incorrect, but not even the follow up fix (24e59d16211e80c823d7254d2c19ba4649ec2205) fixed it.

Anyway, if possible, it'd be great to get this fix included in the 30.1 branch, because 30.0 is the last (stable) version that works.

Thank you once again.

**Comment by RytoEX** [comment]
> I know I'm a bit late, but I just tested the fix on my GTX 660 on Windows 10 with 474.82 drivers, and I NVENC works again. Thank you very much, @RytoEX!
> 
> It initially broke with [4a8e8bb](https://github.com/obsproject/obs-studio/commit/4a8e8bb1bdf2d1efaae75893a544bddab0e2bb2a), which I'm aware it's incorrect, but not even the follow up fix ([24e59d1](https://github.com/obsproject/obs-studio/commit/24e59d16211e80c823d7254d2c19ba4649ec2205)) fixed it.
> 
> Anyway, if possible, it'd be great to get this fix included in the 30.1 branch, because 30.0 is the last (stable) version that works.
> 
> Thank you once again.

It's planned to be included in the 30.1 branch. It just takes a non-zero amount of time to do it, and time is limited.

**Comment by guihkx** [comment]
No worries, I completely understand. Thank you for your hard work.

**Comment by RytoEX** [comment]
Please do note that as mentioned in the PR description and commit message, we plan to remove the compatibility hack that retains Kepler NVENC support at some point.
