### ISSUE TITLE
Twitch stream skewed with 960p using NVENC

### ISSUE THREAD

**Issue by kakra** [obsproject/obs-studio#10430]
### Operating System Info

Other

### Other OS

Linux flatpak

### OBS Studio Version

30.1.1

### OBS Studio Log URL

https://obsproject.com/logs/THFcqKo1pPQ0YLUP

### Expected Behavior

960p streaming should just work fine.

### Current Behavior

This worked fine previously but I'm not exactly sure if an OBS upgrade or an NVIDIA upgrade caused this issue:

When streaming with 960p resolution, the Twitch stream becomes skewed. It works with 864p and 1080p. I used 960p for months previously but didn't stream for a few weeks. Previous to that, 960p didn't work but the stream didn't skew, it just dropped frames and disconnected with an encoder error.

When the bug occurs, streaming is very unstable and the encoder will eventually crash. A lot of dropped frames occur, and Twitch reports unstable frame rates. Sometimes, the stream starts out fine and then suddenly breaks and skews. The only stable resolution seems to be 1080p, lower resolutions like 960p or 864p show this behavior.

### Steps to Reproduce

1. Use NVENC H.264 encoder (ffmpeg)
2. Set streaming resolution to 960p (source resolution is 4k), bilinear
3. Start streaming to Twitch

![image](https://github.com/obsproject/obs-studio/assets/17684/9d3461b0-9e74-4060-a317-21c1102f1446)

### Anything else we should know?

Screenshot of a skewed 960p stream:

![image](https://github.com/obsproject/obs-studio/assets/17684/bc2ae413-eeae-4e09-a414-771f60cf45eb)

I'm using the official flatpak version of OBS on Gentoo.

**Comment by derrod** [comment]
1706 x 960 is not 16:9, seems the OpenGL renderer doesn't like that. Use something that is the same aspect ratio, e.g. 1600x900 or 1728x972 if you don't want to use 1080p for some reason.

Since scaling is not expected or intended to work with differeing aspect ratios I'm going to close this as a wontfix.

**Comment by kakra** [comment]
Oh wow, I never realized it is ever so slightly off (`1920x960/1080 = 1706.66`). I'll try again with 864p (`1920x864/1080 = 1536`). I'm using that resolution for streaming because it usually results in a lot better image for viewers: less artifacts, and less scaling if the chat sidebar is opened.
