### ISSUE TITLE
insufficient disk space error when recording to url

### ISSUE THREAD

**Issue by BillGoldenWater** [obsproject/obs-studio#10443]
### Operating System Info

macOS 14

### OBS Studio Version

30.1.1

### OBS Studio Log URL

https://obsproject.com/logs/fla9JQHK9RnuC4vy

### Expected Behavior

expect successfully start recording

### Current Behavior

failed to record with a insufficient disk space error

### Steps to Reproduce

1. use Custom Output (FFmpeg)
2. select output type `Output to File`
3. select a valid path
4. delete the path in Finder
5. select output type `Output to URL`
6. enter a valid url
7. save then click `Start Recording`

### Anything else we should know?

I think there shouldn't be an error since the **current** output is url, shouldn't check the file output
Or, the error should be same as when the **current** output is file, which is a `path could not be opened` error

**Comment by RytoEX** [comment]
I suspect this should also happen many versions back. Can you confirm, at least on 30.0.2?

**Comment by Fenrirthviti** [comment]
While I agree that the `path could not be opened` error is better than showing disk full, I'm not sure we want to add any custom handling for url-based outputs in the custom ffmpeg output.

**Comment by BillGoldenWater** [comment]
> While I agree that the `path could not be opened` error is better than showing disk full, I'm not sure we want to add any custom handling for url-based outputs in the custom ffmpeg output.

I think have errors that from `file-based outputs` in `url-based outputs` is misleading, since they are "choose one, not both" type of settings

**Comment by BillGoldenWater** [comment]
> I suspect this should also happen many versions back. Can you confirm, at least on 30.0.2?

tested 24.0.6, it also happened, earlier version not tested

**Comment by Fenrirthviti** [comment]
> I think have errors that from `file-based outputs` in `url-based outputs` is misleading, since they are "choose one, not both" type of settings

This is implying that we support URL based outputs, which is more of an accident than anything. Adding custom handling for FFmpeg output mode is something I am against, as frankly I would prefer we removed it entirely.
