### ISSUE TITLE
OBS Flatpak nVEnc Issue ArchLinux

### ISSUE THREAD

**Issue by DarkXero-dev** [obsproject/obs-studio#10453]
### Operating System Info

Other

### Other OS

ArchLinux

### OBS Studio Version

30.1.1

### OBS Studio Version (Other)

Flatpak latest

### OBS Studio Log URL

https://obsproject.com/logs/UJacRsy25pELNV2k

### Expected Behavior

For it not to error out

### Current Behavior

nVidia nVEnc refuses to work getting error 

![image](https://github.com/obsproject/obs-studio/assets/81101439/a64233ca-79ae-47b6-be6a-5e5e5394fae6)

### Steps to Reproduce

1. Open OBS Settings
2. Set Output to High Quality / nVEnc 
3. Hit Stream/Record
...

### Anything else we should know?

I have tested Arch's Native version worked fine no issues it's only Flatpak version having the issue..  Latest nVidia drivers 550.67 both flatpak and native. Everything is up to date... Issue been happening since 30.1 ...

**Comment by RytoEX** [comment]
Please try, in order:
1. Disabling Psycho Visual Tuning manually.
2. Setting b-frames to `0`.
3. Setting multipass to Disabled.
4. Explicitly setting a keyframe interval.

Try to start the encoder (stream/recording/output) after each change.

**Comment by DarkXero-dev** [comment]
Log
https://obsproject.com/logs/yBFTeiug7KYmOJMc

**Comment by DarkXero-dev** [comment]
@RytoEX 

It would help if you told me where I could find these options I had to dig a round to find some of them. And what else exactly do you want me to do ?

**Comment by RytoEX** [comment]
After further discussion with people more familiar with Linux, this seems more like a support issue.

We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

**Comment by DarkXero-dev** [comment]
@RytoEX I came here from Discord coz no one could help even Tytan told me to post on here.. But whatever..
