### ISSUE TITLE
OBS makes an empty ~/.config directory

### ISSUE THREAD

**Issue by Samueru-sama** [obsproject/obs-studio#10450]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.1.0-1 from the Arch repo.

### OBS Studio Log URL

https://obsproject.com/logs/U9aVAKI8XdXOpYqz

### Expected Behavior

I have `$XDG_CONFIG_HOME` defined as `$HOME/.local/config` instead of the default location of `$HOME/.config`. I should be able to just use OBS studio without issues.

### Current Behavior

Opening OBS studio results in the creation of an empty `~/.config` directory. 

However it seems OBS is actually picking up the xdg variable, because my plugins and settings at `$XDG_CONFIG_HOME/obs-studio` do actually work and everything.

**So the main issue is just that OBS is making the empty dir on startup, the rest works.** 

(Also the fact that plugins get installed in `XDG_CONFIG_HOME` instead of `XDG_DATA_HOME` does not follow the xdg specification, but this isn't the main issue here anyway) 

### Steps to Reproduce

1. Define XDG_CONFIG_HOME to any path that isn't the default $HOME/.config location
2. Open obs-studio
3. A $HOME/.config directory is created by it.

**Comment by kkartaltepe** [comment]
This could be a large number of other components in obs that depend on config paths. If you can give a backtrace that would help diagnose who is making the directory.

Also if your profiledir is saved in settings to be $HOME/.config this will override things like XDG_CONFIG. Such as opening obs without XDG_CONFIG set originally or copying settings from another machine. This is probably the only thing in obs that would make an empty folder.

**Comment by Samueru-sama** [comment]
> This could be a large number of other components in obs that depend on config paths. If you can give a backtrace that would help diagnose who is making the directory.
> 
> Also if your profiledir is saved in settings to be $HOME/.config this will override things like XDG_CONFIG. Such as opening obs without XDG_CONFIG set originally or copying settings from another machine. This is probably the only thing in obs that would make an empty folder.

Well, turns out the issue is not obs itself, the issue is being caused by the input overlay plugin as I tested deleting the entire XDG_CONFIG_HOME/obs-studio dir and launched obs with and without the plugins dir inside. 

Sorry for this.

**Comment by RytoEX** [comment]
> > This could be a large number of other components in obs that depend on config paths. If you can give a backtrace that would help diagnose who is making the directory.
> > Also if your profiledir is saved in settings to be $HOME/.config this will override things like XDG_CONFIG. Such as opening obs without XDG_CONFIG set originally or copying settings from another machine. This is probably the only thing in obs that would make an empty folder.
> 
> Well, turns out the issue is not obs itself, the issue is being caused by the input overlay plugin as I tested deleting the entire XDG_CONFIG_HOME/obs-studio dir and launched obs with and without the plugins dir inside.
> 
> Sorry for this.

No problem. Thanks for investigating and following up.
