### ISSUE TITLE
The "Start Virtual Camera" button does not appear

### ISSUE THREAD

**Issue by matroska878655** [obsproject/obs-studio#10455]
### Operating System Info

Other

### Other OS

manjaro linux

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.0.2-4

### OBS Studio Log URL

https://obsproject.com/logs/x5uFqVH10ns0gLmU

### Expected Behavior

"Start Virtual Camera" button doesn't show up, although i have v4l2loopback installed on my system

### Current Behavior

![bug](https://github.com/obsproject/obs-studio/assets/162113613/94685f8e-f3a7-4bf8-b374-6eab0d5ec427)

### Steps to Reproduce

its happen when i open obs

**Comment by tytan652** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for further assistance.

Thank you!
