### ISSUE TITLE
where is obs-browser？

### ISSUE THREAD

**Issue by Aaronjiahao** [obsproject/obs-studio#10474]
### Operating System Info

macOS 14

### OBS Studio Version

30.1.1

### OBS Studio Log URL

https://github.com/Aaronjiahao/obs-studio.git

### Expected Behavior

cmake successfully

### Current Behavior

elseif(NOT EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/obs-browser/CMakeLists.txt")
        message("${CMAKE_GENERATOR_PLATFORM}")
        message(FATAL_ERROR "Required submodule 'obs-browser' not available.")
      endif()
when i build in macos, cmake failded。The error message is below:

CMake Error at plugins/CMakeLists.txt:20 (message):
  Required submodule 'obs-browser' not available.
Call Stack (most recent call first):
  plugins/CMakeLists.txt:63 (check_obs_browser)

### Steps to Reproduce

run cmake -G "Xcode" -DCMAKE_BUILD_TYPE=Debug -B build/debug in macos

**Comment by Aaronjiahao** [comment]
When I comment out the above part，there is new error:

CMake Error at plugins/obs-outputs/cmake/ftl.cmake:62 (target_link_libraries):
  Cannot find source file:

    /Users/bytedance/workingCode2/obs-studio/plugins/obs-outputs/ftl-sdk/libftl/ftl.h
Call Stack (most recent call first):
  plugins/obs-outputs/CMakeLists.txt:81 (include)


CMake Error at plugins/obs-outputs/cmake/ftl.cmake:11 (target_sources):
  Cannot find source file:

    ftl-sdk/libftl/posix/socket.c
Call Stack (most recent call first):
  plugins/obs-outputs/CMakeLists.txt:81 (include)


CMake Error at plugins/obs-outputs/cmake/ftl.cmake:4 (add_library):
  No SOURCES given to target: ftl-sdk
Call Stack (most recent call first):
  plugins/obs-outputs/CMakeLists.txt:81 (include)

**Comment by mihawk90** [comment]
You likely didn't clone the repo recursively, i.e. including submodules.
If you forgot to do that you can do `git submodule --init` to get them.

**Comment by Aaronjiahao** [comment]
thanks, i will try it

**Comment by Aaronjiahao** [comment]
my macos is 14.0 ，when i complie the Xcode project 。there is error msg：

/Users/bytedance/workingCode2/obs-studio/plugins/mac-virtualcam/src/dal-plugin/OBSDALPlugInInterface.mm:364:8 'CMIOHardwarePlugInInterface' is deprecated: first deprecated in macOS 12.3 - Use CMIOExtension instead

**Comment by gxalpha** [comment]
I'd recommend stopping by in the `#development` channel on our [Discord server](https://discord.gg/obsproject) for questions on compiling OBS.
