### ISSUE TITLE
the screen turns white

### ISSUE THREAD

**Issue by SmallHdcc** [obsproject/obs-studio#10476]
### Operating System Info

Windows 11

### OBS Studio Version

30.1.1

### OBS Studio Log URL

https://obsproject.com/logs/k5IporW81uzvQRHl

### Expected Behavior

If you could help me analyze the cause of this situation, I would try to solve it.

### Current Behavior

When I open the video capture device settings in Windows 11, the screen turns white and does not display normally after waiting for a long time.
![crash](https://github.com/obsproject/obs-studio/assets/124751872/44807c6b-1676-4f64-aeac-9f151481064a)

### Steps to Reproduce

1. I created a video capture device.
2. Then I right-clicked on the settings.
3. Then it turned white and did not display anything.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
