### ISSUE TITLE
I don’t know how to replace it with CMIOExtension

### ISSUE THREAD

**Issue by Aaronjiahao** [obsproject/obs-studio#10477]
### Operating System Info

macOS 14

### Other OS

macos14

### OBS Studio Version

30.1.1

### OBS Studio Log URL

https://github.com/obsproject/obs-studio.git 

### Expected Behavior

complie success

### Current Behavior

/Users/bytedance/workingCode2/obs-studio/plugins/mac-virtualcam/src/dal-plugin/OBSDALPlugInInterface.mm:97:13 'CMIOObjectCreate' is deprecated: first deprecated in macOS 12.3 - Use CMIOExtension instead
/Users/bytedance/workingCode2/obs-studio/plugins/mac-virtualcam/src/dal-plugin/OBSDALPlugInInterface.mm:108:13 'CMIOObjectCreate' is deprecated: first deprecated in macOS 12.3 - Use CMIOExtension instead。
。

I cannot find the interface in the corresponding header file～
such as : #import "CoreMediaIO/CMIOExtension.h"

### Steps to Reproduce

build project in macos 14

**Comment by tytan652** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for further assistance.

Thank you!
