### ISSUE TITLE
Video Toolbox CBR Unstable, Destabilizes More After Sustained Use

### ISSUE THREAD

**Issue by Luke6285** [obsproject/obs-studio#10489]
### Operating System Info

macOS 13

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.1.3

### OBS Studio Log URL

https://gist.github.com/Luke6285/ce935420334519d5f3fb7d0c2383181a

### Expected Behavior

Streaming/recording at a stable 2400 Kbps using CBR rate control.

### Current Behavior

Fluctuating bitrate for the whole duration of recording that eventually becomes more unstable over time with bigger fluctuations in bitrate.

### Steps to Reproduce

1. Choose Apple VT H264 Hardware Encoder as Video Encoder for Output.
2. Choose 'CBR' Rate Control in Encoder Settings.
3. Set Bitrate to 2400 Kbps.
4. Start Recording.
5. Deviation from 2400 CBR bitrate begins immediately.
6. After more time has passed, bigger fluctuations begin especially during static/high-motion scene transitions.

### Anything else we should know?

Here is a Twitch VOD from last night showcasing the issue.

Earlier scenes with no/low motion (loading, lobby, inventory, settings) and high motion (in-game movement) still stay close to 2400kbps but after time, the same type of scenes fluctuate bitrate dramatically with no/low motion dropping below 1000kbps and high-motion exceeding 4000-5000kbps.

Early (more)stable: https://www.twitch.tv/videos/2112131201?t=0h18m28s
Later unstable: https://www.twitch.tv/videos/2112131201?t=2h10m55s

Kbps stats on left side of video. Overall, it's generally unstable the whole time but seems to get worse over time. Definitely does not behave the same as x264 CBR.

EDIT: Forgot to mention, same exact behavior occurs during offline recordings as well. I have very fast internet and never drop frames during livestreams, so these examples are not affected by my upload speed at all.

**Comment by RytoEX** [comment]
We do not accept bug reports from older versions of OBS. Please re-test in OBS Studio 30.1.2 (or newer) and provide a new log file.

Without context for how the Kbps stats in your video are measured, we cannot say if this is a valid representation.

That said, CBR in hardware encoders, especially VideoToolbox, is never going to be perfect. They all fluctuate to some extent.

**Comment by Luke6285** [comment]
I forgot to specify that the bitrate reading is being captured from the OBS Stats window... And from reading the release logs of all newer versions, it doesn't look like anything related to VT has been changed.
