### ISSUE TITLE
i cant download obs studio

### ISSUE THREAD

**Issue by qsteereeee** [obsproject/obs-studio#10483]
### Operating System Info

Windows 11

### OBS Studio Version

30.1.1

### OBS Studio Version (Other)

30.0.1

### OBS Studio Log URL

asds

### OBS Studio Crash Log URL

when im trying to download it it says that obs is being used by another application aka "microsoft edge" 

### Expected Behavior

it would download

### Current Behavior

dosent let me

### Steps to Reproduce

1.
2.
3.
...

### Anything else we should know?

help

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
