### ISSUE TITLE
Replay Buffer not working

### ISSUE THREAD

**Issue by Antiquely0947** [obsproject/obs-studio#10491]
### Operating System Info

Windows 10

### Other OS

Windows 10 22H2

### OBS Studio Version

30.1.1

### OBS Studio Log URL

https://obsproject.com/logs/sdvHIGqRWOcBCIh4

### Expected Behavior

Use Replay Buffer and have it save with the expected time.

### Current Behavior

 Replay Buffer doesn't consistently work, sometimes it does, sometimes it doesn't, and sometimes it does but with a big delay? (it clips but only after a few minutes).
When it stops working, if I click "Stop Replay Buffer", it says "Stopping Replay Buffer" for around a minute before it finally does.

### Steps to Reproduce

1.Turn on Replay Buffer
2.Click on Save Replay
3.
...

### Anything else we should know?

I've tried in admin mode, without admin mode, latest version, old version (29.1.3), different encoder settings, and by using an hotkey or clicking the button with my mouse. It always ends up happening, and I've never had this problem before. I've used OBS for years now with these settings without any issues.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
