### ISSUE TITLE
When recording with NVENC AV1 at 1080p@60 every third frame is duplicated

### ISSUE THREAD

**Issue by danylofitel** [obsproject/obs-studio#10499]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/ibpNaWOh1VhzTCNP

### Expected Behavior

When recording the video at 1080p@60, each frame should be distinct. When replaying frame by frame, I can validate it.

### Current Behavior

When recording with NVENC AV1, the video is at 60 fps, but every third frame is a duplicate of the previous frame.

https://github.com/obsproject/obs-studio/assets/3258785/a112f9bf-1c58-43fe-b0ef-37ccc8b16276

### Steps to Reproduce

1. This reproduces on a system with NVIDIA GeForce RTX 4090 with driver version 552.12.
2. Create a scene with a video input at 1080p@60.
3. Under Settings -> Video change Base Resolution and Output Resolution to 1920x1080, set FPS to 60.
4. Under Output -> Recording set Recording Quality to Indistinguishable Quality, set Recording Format to MPEG-4, Video Encoder to Hardware (NVENC, AV1), Audio Encoder to AAC.
5. Record a video.
6. When playing the recorded video, pause it and go frame by frame. You'll notice that every third frame is a duplicate of the previous frame.
...

### Anything else we should know?

If you download the attached video and play it frame by frame, you should see the frame duplication issue.
Any other encoder (Software x264, NVENC H.264, NVENC HEVC) works fine, the problem is only with NVENC AV1. This very well could be an issue with NVidia encoder.

**Comment by Penwy** [comment]
On my end, every single frame of this video where the hand is present is unique, there is not a single visibly duplicated frame. This is likely a playback issue on your end. Can you provide an exact frame number that you see as duplicated?

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by danylofitel** [comment]
> On my end, every single frame of this video where the hand is present is unique, there is not a single visibly duplicated frame. This is likely a playback issue on your end. Can you provide an exact frame number that you see as duplicated?

You're right, it's a playback issue with MPC-HC, when using VLC I can also see each frame. Thank for checking it so quickly!
