### ISSUE TITLE
The sound is distorted when the obs application runs in the background

### ISSUE THREAD

**Issue by 9000000** [obsproject/obs-studio#10497]
### Operating System Info

Windows 11

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/Qa2O5tNU1eohaCYT

### Expected Behavior

The sound is distorted when the obs application runs in the background. When I run a youtube video on the obs browser and then run it in the background, I get a sound distortion error when running any other application.

### Current Behavior

The sound is distorted when the obs application runs in the background. When I run a youtube video on the obs browser and then run it in the background, I get a sound distortion error when running any other application.

### Steps to Reproduce

1. open browser in obs
2.Minimize the obs application to the taskbar
3.
...

**Comment by WizardCM** [comment]
Duplicates #7588
