### ISSUE TITLE
Streaming to local server with SRT in listener mode using "Start streaming" without a connection occurring prevents OBS from closing

### ISSUE THREAD

**Issue by robedpixel** [obsproject/obs-studio#10504]
### Operating System Info

Windows 11

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/AWe6fUonS1skxhOO

### Expected Behavior

When attempting to stream locally in listener mode using SRT with the "Start Streaming" button, if no client connects to OBS to view the stream. OBS should close properly when exiting.

### Current Behavior

When attempting to stream locally in listener mode using SRT with the "Start Streaming" button, if no client connects to OBS to view the stream. OBS seems to close when clicking the exit button, but the process is still running (icon can be seen in the system tray) and not responsive. Closing OBS requires ending the process through task manager

### Steps to Reproduce

1. In settings, set the service to custom and the server to srt://[local ip address]:[port]?mode=listener
2. Click "Start Streaming" to begin stream
3. Click "Exit" to exit OBS
4. OBS seems to exit, but process is still running and icon will still be present in system tray

### Anything else we should know?

Please provide an option to cancel the connection when attempting to stream in listener mode using SRT with the streaming function

**Comment by pkviet** [comment]
I can confirm the bug.
Thanks for the report.

**Comment by pkviet** [comment]
Fixed with https://github.com/obsproject/obs-studio/pull/10508

**Comment by tt2468** [comment]
Unfortunately, this does not appear fully fixed. Here's what I'm seeing on Ubuntu 22.04:

- Start stream with `srt://0.0.0.0:6969?mode=listener`
- Don't connect a client
  - Stream will never fully "start"
  - OBS begins spamming the log with `error: [obs-ffmpeg mpegts muxer / libsrt]: Connection rejected, Unknown or erroneous` messages
- Close OBS
- OBS will unload fully, however the program will segfault on finalization:
```
info: Number of memory leaks: 0
Segmentation fault (core dumped)
```

It completely fails to shut down the socket if I connect a client, then disconnect the client, then try stopping stream or shutting down OBS. To be completely honest, I think we need to just remove rendezvous and listener modes from our SRT output.
