### ISSUE TITLE
Issue with false GPU driver error (Cannot enter OBS anymore) 

### ISSUE THREAD

**Issue by Useor** [obsproject/obs-studio#10506]
### Operating System Info

Windows 11

### OBS Studio Version

Other

### OBS Studio Version (Other)

I don't know the Microsoft Store version.

### OBS Studio Log URL

No log file was given (I don't know why it didn't give me this)

### OBS Studio Crash Log URL

Crash log was not given (I don't know why it didn't give me this)

### Expected Behavior

Reopen OBS after downloading new drivers and work on a video

### Current Behavior

OBS stated that my Drivers were ether not supported or where outdated after updating them. I can no longer download OBS without having it crash or delete itself on my computer

### Steps to Reproduce

1.Download new Nvidia Drivers (OBS might have been open)
2.Open OBS
3.Error code opens up
4.Puts OBS into safe mode (cannot use in safe mode) or deletes its self

### Anything else we should know?

Error code image
![Screenshot 2024-04-10 033810](https://github.com/obsproject/obs-studio/assets/166590906/334e9605-84ad-4ae1-91e1-f8b712922aad)
I only tried to open it

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
