### ISSUE TITLE
GPG Key error when running "sudo apt update"

### ISSUE THREAD

**Issue by averageguyoriginal** [obsproject/obs-studio#10515]
### Operating System Info

Other

### Other OS

Debian bookworm

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.0.2+dfsg-1+b1

### OBS Studio Log URL

https://obsproject.com/logs/uBBIGe45iABSZdOD

### Expected Behavior

i didnt expect it to give the GPG error when i run "sudo apt update"

### Current Behavior

GIVES THE BELOW ERROR

`Err:10 http://download.opensuse.org/repositories/home:/selmf/Debian_12  InRelease
  The following signatures were invalid: EXPKEYSIG 3F3411BE43F8BC1F home:selmf OBS Project <home:selmf@build.opensuse.org>
Fetched 5,988 B in 1s (5,318 B/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://download.opensuse.org/repositories/home:/selmf/Debian_12  InRelease: The following signatures were invalid: EXPKEYSIG 3F3411BE43F8BC1F home:selmf OBS Project <home:selmf@build.opensuse.org>
W: Failed to fetch http://download.opensuse.org/repositories/home:/selmf/Debian_12/InRelease  The following signatures were invalid: EXPKEYSIG 3F3411BE43F8BC1F home:selmf OBS Project <home:selmf@build.opensuse.org>
W: Some index files failed to download. They have been ignored, or old ones used instead.
`

### Steps to Reproduce

1. run sudo apt update
2. it goes through fetching
3. it throws out the error
...

### Anything else we should know?

i googled a lot about this but couldnt find anyhthing related to obs. the other tutorial told me to delete apt key or reinstall the app and i tried everything but it didnt work.

**Comment by averageguyoriginal** [comment]
> This is an issue from a unofficial/third-party repo, not OBS Studio itself.

but i used the instruction on obs site to install for debian. i m confused what to do? even after purging obs, i still have this error.

**Comment by tytan652** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for further assistance.

Thank you!
