### ISSUE TITLE
Stopping Recording... takes too long when recording 1 FPS

### ISSUE THREAD

**Issue by szmarczak** [obsproject/obs-studio#10529]
### Operating System Info

Windows 11

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/q1vnykNx10Df6vIB

### Expected Behavior

Instant save.

### Current Behavior

Very long save.

### Steps to Reproduce

1. File
2. Settings
3. Video
4. Integer FPS Value set to `1`
5. Record
6. Stop
7. Takes too long.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
