### ISSUE TITLE
Encoding Overloaded

### ISSUE THREAD

**Issue by DogancanYr** [obsproject/obs-studio#10523]
### Operating System Info

Windows 11

### OBS Studio Version

30.1.2

### OBS Studio Log URL

.

### Expected Behavior

.

### Current Behavior

No matter what setting I change when trying to record at 60 fps or above, it gives an encoding overloaded error and the CPU usage rises to 6%, but there is no problem at 50 fps. 

### Steps to Reproduce

.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
