### ISSUE TITLE
Encoding overloading and not working in the latest version

### ISSUE THREAD

**Issue by melihreim** [obsproject/obs-studio#10528]
### Operating System Info

Windows 11

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/OYbFDZNO7Eqycbp8

### Expected Behavior

Recording screen without any overload.

### Current Behavior

Encoding overloads after 10-15 seconds no matter what is being recorded.

### Steps to Reproduce

1.Upgraded OBS Studio from 30.0.2 to 30.1.2
2.Tried to record the screen with the same settings before
3.Got overload not like before.
...

### Anything else we should know?

Using AMD HW H.264 
CQP, 18
0 seconds, quality, high, 0 B.
GPU : Rx 6800xt

**Comment by melihreim** [comment]
reverting to 30.0.2 solves the problem but I want to know what causes this bug.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
