### ISSUE TITLE
opening link in new tab in browser

### ISSUE THREAD

**Issue by hamidhtc** [obsproject/obs-studio#10559]
### Operating System Info

Windows 10

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/gtZtSRL8Pi43EVws

### Expected Behavior

i want login in website and record webinar

### Current Behavior

the website open link in new tab and nothing shows in obs

### Steps to Reproduce

1.try login in some websites that opens link in new tab
2. you cannot login because obs doesn't support new tab link
3.  ![asdasd](https://github.com/obsproject/obs-studio/assets/7674614/2a31118b-21b3-4cfa-a712-215bf55b7788)
...

### Anything else we should know?

i can not login in chrome and copy webinar link in obs. because it need authenticator.

**Comment by WizardCM** [comment]
This is not the intended use of the browser source. Please use a normal browser and window capture.
