### ISSUE TITLE
Encocing Error - An encoding error occurred during streaming

### ISSUE THREAD

**Issue by enrik90h** [obsproject/obs-studio#10558]
### Operating System Info

Windows 10

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/9fGBRsmIMxLKTj78

### Expected Behavior

Start stream normally.

I see encoder error on logs:

08:49:58.991: [obs-nvenc: 'advanced_video_stream'] settings:
08:49:58.991: 	codec:        H264
08:49:58.991: 	rate_control: CBR
08:49:58.991: 	bitrate:      6000
08:49:58.991: 	cqp:          20
08:49:58.991: 	keyint:       60
08:49:58.991: 	preset:       p6
08:49:58.991: 	tuning:       hq
08:49:58.991: 	multipass:    fullres
08:49:58.991: 	profile:      high
08:49:58.991: 	width:        1920
08:49:58.991: 	height:       1080
08:49:58.991: 	b-frames:     2
08:49:58.991: 	lookahead:    true
08:49:58.991: 	psycho_aq:    false
08:49:58.991: 
08:49:59.059: ---------------------------------
08:49:59.059: [FFmpeg aac encoder: 'adv_stream_audio'] bitrate: 160, channels: 2, channel_layout: stereo
08:49:59.059: 
08:49:59.060: [rtmp stream: 'adv_stream'] Connecting to RTMP URL rtmp://mad01.contribute.live-video.net/app...
08:49:59.077: [rtmp stream: 'adv_stream'] Interface: Realtek PCIe GBE Family Controller (ethernet, 1000↓/1000↑ mbps)
08:50:00.678: [rtmp stream: 'adv_stream'] Connection to rtmp://mad01.contribute.live-video.net/app (52.223.197.11) successful
08:50:00.680: [rtmp stream: 'adv_stream'] Socket send buffer is 65536 bytes
08:50:00.685: ==== Streaming Start ===============================================
**08:50:00.776: [obs-nvenc: 'advanced_video_stream'] get_tex_from_handle: OpenSharedResource failed: 0x80070057
08:50:00.776: Error encoding with encoder 'advanced_video_stream'
08:50:00.776: [rtmp stream: 'adv_stream'] Encoder error, disconnecting**
08:50:00.777: [rtmp stream: 'adv_stream'] Socket send buffer is 65536 bytes
08:50:00.777: Output 'adv_stream': stopping
08:50:00.777: Output 'adv_stream': Total frames output: 0
08:50:00.777: Output 'adv_stream': Total drawn frames: 52
08:50:00.779: ==== Streaming Stop ================================================

### Current Behavior

Steam Stop with error after 1 second

### Steps to Reproduce

1. Start PC
2. Start OBS
3. Start Stream

**Comment by enrik90h** [comment]
My temporary workaround is close OBS, search the process (not closed when i close OBS in this case), and open again OBS, then works.

**Comment by enrik90h** [comment]
I accidentally closed the issue

**Comment by enrik90h** [comment]
I accidentally closed the issue

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by enrik90h** [comment]
I think thats a bug, because i have 20 OBS on 20  different PC's on my job.
@Fenrirthviti
