### ISSUE TITLE
OBS opens more obs-browser-page.exe processes when opened with --minimize-to-tray

### ISSUE THREAD

**Issue by karasuhebi** [obsproject/obs-studio#10555]
### Operating System Info

Windows 10

### OBS Studio Version

30.1.2

### OBS Studio Log URL

The requested URL returned error: 413

### Expected Behavior

I expect it two open the same number of obs-browser-page.exe processes every time.

### Current Behavior

It opens more obs-browser-page.exe processes when you open it using `--minimize-to-tray`

### Steps to Reproduce

1. Open OBS via the UI (either a shortcut or the Start menu.) You will notice two obs-browser-page.exe processes.
2. Open OBS via CMD with the `--minimize-to-tray` switch. You will notice 5 obs-browser-page.exe processes.

**Comment by WizardCM** [comment]
This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels below, and if it's determined that this is indeed a bug, then we will re-open this issue.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
