### ISSUE TITLE
Ubuntu 24.04 need python 3.12 or more 

### ISSUE THREAD

**Issue by Fr-Dae** [obsproject/obs-studio#10557]
### Operating System Info

Other

### Other OS

Lubuntu 24.04

### OBS Studio Version

30.1.2

### OBS Studio Log URL

.

### Expected Behavior

install and use obs

### Current Behavior

i can't, i have try with adding ppa, modifiy it for  fit with 23.04
but obs need python3.11, i have only 3.12 :/

### Steps to Reproduce

...

```[tasklist]
### Tasks
```

**Comment by tytan652** [comment]
Ubuntu 24.04 is in beta so non-supported by the PPA for now.

**Comment by Fr-Dae** [comment]
it's the lts :/

**Comment by RytoEX** [comment]
> it's the lts :/

It's still not officially released. We only test and build packages for new Ubuntu LTS versions when they are fully released.

**Comment by briped** [comment]
See workaround here: https://github.com/obsproject/obs-studio/issues/10609#issuecomment-2113463560
