### ISSUE TITLE
Install on Ubuntu 22.04 LTS fails

### ISSUE THREAD

**Issue by alwindoss** [obsproject/obs-studio#10609]
### Operating System Info

Other

### Other OS

Ubuntu 24.04 LTS

### OBS Studio Version

30.1.2

### OBS Studio Log URL

Unable to install so no log URL

### Expected Behavior

Expected the Obs Studio to be installed.

### Current Behavior

The Ubuntu 24.04 LTS version is officially released and yet when I follow the instructions on the [website](https://obsproject.com/download#linux) I get the following error:

```
Err:8 https://ppa.launchpadcontent.net/obsproject/obs-studio/ubuntu noble Release
  404  Not Found [IP: 185.125.190.80 443]
Reading package lists... Done
E: The repository 'https://ppa.launchpadcontent.net/obsproject/obs-studio/ubuntu noble Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

### Steps to Reproduce

1. Followed the instructions on the [website](https://obsproject.com/download#linux)

### Anything else we should know?

The Ubuntu 24.04 LTS version is officially released and yet when I follow the instructions on the [website](https://obsproject.com/download#linux) I get the following error:

```
Err:8 https://ppa.launchpadcontent.net/obsproject/obs-studio/ubuntu noble Release
  404  Not Found [IP: 185.125.190.80 443]
Reading package lists... Done
E: The repository 'https://ppa.launchpadcontent.net/obsproject/obs-studio/ubuntu noble Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by tytan652** [comment]
The PPA does not actually provide package for 24.04, which is not a bug.

**Comment by alwindoss** [comment]
@tytan652 So what should be done forbit to be supported. Ubuntu 24.04 is an LTS version.

**Comment by tiberium-v** [comment]
@alwindoss give it some time. The version of ubuntu is fresh out. It takes a little time, that the devs can publish a version for it on the PPA.

**Comment by alwindoss** [comment]
Thank you for clarifying @tiberium-v

**Comment by ThatsNasu** [comment]
possible manual (and not recommended) workaround for installing obs anyways:

`sudo nano obsproject-ubuntu-obs-studio-noble.sources`

edit the line where it says `Suites: noble` to be `Suites: jammy`, then save the file and do `sudo apt update`. now Ubuntu 24.04 should eat the repository anyways.

I dont recommend doing so, because it means using a release not designed for the platform, aswell as using a different update path. Also please dont use sudo commands or edit files if you don't know what you are doing c:

Have a nice day anyways!

**Comment by briped** [comment]
Add the `obsproject/obs-studio` repository. Ignore the 404 error.
```
sudo add-apt-repository ppa:obsproject/obs-studio
```

Change from `noble` (24.04) to `manic` (23.10).
```
sudo mv /etc/apt/sources.list.d/obsproject-ubuntu-obs-studio-noble.sources /etc/apt/sources.list.d/obsproject-ubuntu-obs-studio-mantic.sources
sudo sed --in-place --expression='/^Suites:/c\Suites: mantic' /etc/apt/sources.list.d/obsproject-ubuntu-obs-studio-mantic.sources
sudo apt-get update

```

Manually download and install the required dependencies.
```
wget --quiet --directory-prefix=/tmp https://launchpad.net/ubuntu/+archive/primary/+files/libpython3.11-minimal_3.11.6-3_amd64.deb && \
sudo dpkg --install /tmp/libpython3.11-minimal_3.11.6-3_amd64.deb && \
wget --quiet --directory-prefix=/tmp https://launchpad.net/ubuntu/+archive/primary/+files/libpython3.11-stdlib_3.11.6-3_amd64.deb && \
sudo dpkg --install /tmp/libpython3.11-stdlib_3.11.6-3_amd64.deb && \
wget --quiet --directory-prefix=/tmp https://launchpad.net/ubuntu/+archive/primary/+files/libpython3.11_3.11.6-3_amd64.deb && \
sudo dpkg --install /tmp/libpython3.11_3.11.6-3_amd64.deb

```

Install OBS-Studio
```
sudo apt-get --yes install obs-studio
```

**Comment by davismj** [comment]
This strategy worked for me. I did need to `sudo apt install --fix-broken` before the libpython3 packages would install correctly.
