### ISSUE TITLE
[Flatpak] Custom Browser Docks setting is missing from OBS

### ISSUE THREAD

**Issue by 0fbcb238c0** [obsproject/obs-studio#10610]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/uZOjwnEeSURuWItL

### Expected Behavior

Selecting the "Dock" menu option should show the option for "Custom Browser Docks..." like so:
![grafik](https://github.com/obsproject/obs-studio/assets/24275722/e0a5b860-bdbe-4061-8f70-76aa58229c5c)

### Current Behavior

Opening the "Dock" tab from the menu bar does not contain the "Custom Browser Docks..." setting.
![grafik](https://github.com/obsproject/obs-studio/assets/24275722/c83b7987-8527-4013-9df8-046940c0abd7)

### Steps to Reproduce

1. Select the "Docks" tab from the menu bar
2. Observe the missing option

**Comment by mihawk90** [comment]
This is not a bug. Browser Docks are disabled on Wayland due to outstanding issues on the CEF side.

**Comment by 0fbcb238c0** [comment]
Good to know, I found nothing about this on Google concerning this.
Thanks you

**Comment by Avasam** [comment]
omg, I spent hours searching why my browser docks suddenly disappeared after an OS update... A clear indication would be much appreciated
