### ISSUE TITLE
AV1 with Intel Arc is borked

### ISSUE THREAD

**Issue by jadenquinn** [obsproject/obs-studio#10629]
### Operating System Info

Windows 10

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/PuY0h4gHpqRGwHr4

### Expected Behavior

 I expect AV1 with Intel Arc to work without issue.

### Current Behavior

I go to record with AV1, but chose too high a preset in the beginning, so when I went into a game (and wasn't just recording my desktop anymore), it got overloaded. This shouldn't be much of an issue, as I should just be able to go into the options of OBS and turn down the encoder preset like everyone else, right? Well.. when I stopped recording the time it got overloaded, it had to "process" or whatever for a bit to stop the recording, but after about 40 seconds of doing that... it just said "Encoding Error" or something very similar with a yellow triangle symbol.
Every time that I've tried to record after that has yielded (pun intended) that error too, leaving a 200-400KB video file after.

### Steps to Reproduce

1. Build a PC with Intel Arc
2. Get OBS and configure it like I have it configured
3. Try to record Doom

### Anything else we should know?

This PC has a 4060 that I'm using as the main GPU, and the Intel Arc is being used as a "secondary" GPU, basically the one I want to do encoding on with OBS. NVIDIA RTX 4060 and Intel Arc A310. This PC also has an i9-13900k, so I know it isn't CPU bottlenecked.
The audio seemed to continue recording properly past where the video encoding died, leading to the video after I closed the game having the audio from when I first opened the game after the AV1 encoder died.
The game is Doom with RTX, running at 2160p, 1920p, 1600p, and 1440p, I was changing them on the fly, but the screen never went black, meaning it probably didn't have to renegotiate with my monitor or anything, so that shouldn't have been an issue.

I went back and grabbed a couple more log files that I think actually ARE the ones that pertain to this issue, I restarted OBS a few times when making sure this was a problem, so it probably uploaded the "previous" log file from that.
[2024-05-01 14-16-45.txt](https://github.com/obsproject/obs-studio/files/15181825/2024-05-01.14-16-45.txt)
[2024-05-01 15-00-35.txt](https://github.com/obsproject/obs-studio/files/15181826/2024-05-01.15-00-35.txt)

**Comment by kkartaltepe** [comment]
It looks like your gpu driver crashed in these logs, probably the issues you are having are driver or device related. Try rebooting or using our [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum) if that doesnt help.
