### ISSUE TITLE
[Mac OS] OBS crash on selecting LocalVocal plug in

### ISSUE THREAD

**Issue by markshinshu** [obsproject/obs-studio#10650]
### Operating System Info

macOS 14

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/BBk3oUnKVeWB8a17

### OBS Studio Crash Log URL

https://drive.google.com/file/d/1_7NYp5Y6Wa3aS4Ps6-UCZIX5OfxuJpml/view?usp=sharing

### Expected Behavior

added localvocal plugin 
https://obsproject.com/logs/OlHA6SB7WNhjStj7
was expecting it to work!

### Current Behavior

OBS crashed

### Steps to Reproduce

1. Install obs-localvocal
2. in source, for Audio input capture, select filter
3. select "Local Vocal transcription"
4. crash
...

**Comment by RytoEX** [comment]
Please provide the crash log.

**Comment by markshinshu** [comment]
[OBS local vocal crash.txt](https://github.com/obsproject/obs-studio/files/15243214/OBS.local.vocal.crash.txt)

**Comment by RytoEX** [comment]
Why are you using the Intel/x86_64 copy of OBS on an Apple Silicon machine? If you don't need it for a specific reason, I would use the Apple/arm64 version of OBS instead, and make sure the plugin architecture matches the OBS architecture.

That said, the crash stack is inside the local vocal plugin, so you should report it to them.

**Comment by markshinshu** [comment]
Thank you @RytoEX! That has fixed the problem!
