### ISSUE TITLE
OBS causes BSOD with nvidia drivers when interacting with SteamVR

### ISSUE THREAD

**Issue by megamaz** [obsproject/obs-studio#10655]
### Operating System Info

Windows 10

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/UhwFHUAQhKu2bG2p

### Expected Behavior

Not a BSOD, as it does in 30.1.1 (tested on both)

### Current Behavior

A BSOD as a result of opening / closing SteamVR.

### Steps to Reproduce

1. Launch OBS first, ensuring version 30.1.2.
2. Make sure that OBS is on a secondary monitor.
3. Launch SteamVR. 
4. BSOD.

### Anything else we should know?

This only started happening in version 30.1.2. Here are specs that may be relevant, and I'm willing to reply with any other information requested;
- GPU: RTX 3070 Ti
- Nvidia Driver version: Game Ready 552.22
- [BSOD Dump](https://github.com/obsproject/obs-studio/files/15255724/050824-14546-01.dmp)

I tried figuring out exactly what SteamVR was doing that was causing OBS to lead to a BSOD to make this a more helpful error report but couldn't find anything. Things I have tried;
- using DDU to reinstall display drivers; didn't work.
- running OBS in safe mode; didn't work
- launching from windows start menu rather than streamdeck; didn't work
- removing secondary monitors; did work.

So far, a workaround is to launch SteamVR first, then OBS. It seems something about opening and closing SteamVR and the interaction of whatever action that is with OBS causes the BSOD. 

If any more info is needed to make this a more helpful error report, please let me know.

**Comment by Fenrirthviti** [comment]
OBS runs entirely in user space, and cannot cause a BSOD. We can potentially be a trigger for driver bugs or other such things as we access parts of the system, but we cannot directly be a cause. I would recommend using a tool like WhoCrashed or BlueScreenView to identify the faulting module, and report it appropriately.
