### ISSUE TITLE
macos screen capture and audio capture not working anymore

### ISSUE THREAD

**Issue by avafab** [obsproject/obs-studio#10668]
### Operating System Info

macOS 13

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/lNcHXrWDLmG3ef5Y

### Expected Behavior

If I select macos screen capture and audio capture in a scene it should show me a preview of what I selected and record them when I hit the record button. 
![image](https://github.com/obsproject/obs-studio/assets/1615967/5b885a93-53cf-4086-9476-eccbc013d2b0)

### Current Behavior

As a user, when selecting macOS screen capture and audio capture into a scene, I cannot see that it is capturing the screen and recording the audio. It is simply not doing anything, not showing preview and not showing that it is actually recording. All indicator are flat and the screen is black. If I record, it does not record. If I check the permission within the app it says "Access Granted" to everything. Tried uninstall, install different versions and enable/disable system permissions but it cannot record.

### Steps to Reproduce

1.Add MacOS audio and video capture into a scene
2.the indicator are not moving and screen is blank
3.if I hit record, it does not record anything
...

### Anything else we should know?

tried to go back to 30.0.2 version but did not work either. it was working before with previous versions

**Comment by jcm93** [comment]
This is more of a support inquiry. Most likely `replayd` is hanging and needs to be killed via pkill or Activity Monitor, or you can restart your machine.

**Comment by avafab** [comment]
Wow! That was it! Thanks. I think we need to make this part of the
documentation or FAQ I literally spend weeks trying to solve the issue

*Fabrizio*


Il giorno lun 13 mag 2024 alle 16:09 jcm ***@***.***> ha
scritto:

**Comment by mnelson4** [comment]
I had the same issue but terminating `replayd` didn't fix it for me. Uninstalling OBS and re-setting it up worked for me
