### ISSUE TITLE
Cannot paste into the stream key field on the Settings Stream section

### ISSUE THREAD

**Issue by Frankenmint** [obsproject/obs-studio#10663]
### Operating System Info

Ubuntu 23.10

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/ZdEYv9mRilgf8luO

### Expected Behavior

ctrl + v = paste in my stream key to save it in my configuration

### Current Behavior

it will not allow me to paste or even right click paste, all the options are greyed out in the context menu. It's been doing this  since 30.0.1 at least

### Steps to Reproduce

1. try to paste in a stream key into your obs field, it does nothing.

**Comment by tytan652** [comment]
The Snap package is not supported.

Please use either the OBS Project PPA or the Flatpak.
