### ISSUE TITLE
OBS crashes Wayland compositor

### ISSUE THREAD

**Issue by ABEC-projects** [obsproject/obs-studio#10664]
### Operating System Info

Other

### Other OS

Arch Linux (with hyprland WM)

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/EmBw4v5EXHAdPQeB

### Expected Behavior

Being able to switch between scenes without obs crashing wayland compositor.

### Current Behavior

When you have a PipeWire window capture, but the captured window is no longer present, if you switch between scenes a few times, my Wayland compositor dies.

### Steps to Reproduce

1. Use arch linux with hyprland 
2. Capture a window with pipewire
3. Close that window
4.  Switch between scene that contains this capture and another rapidly a few times 
5.  It's done! Your Wayland compositor dead!
...

### Anything else we should know?

Not sure who to blame, OBS, Wayland or Hyprland, because with an older version of Hyprland I had more cases like that, but this is the first really reproducible.

**Comment by kkartaltepe** [comment]
If your compositor crashes its a compositor bug. If they find we are doing something incorrect feel free to report back after they fix their crash.
