### ISSUE TITLE
OBS closes with no error reports in log when I click ANY button that browses files.

### ISSUE THREAD

**Issue by Corbent** [obsproject/obs-studio#10683]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/MIsqlvBfBge3uSd5

### Expected Behavior

When I click a browse button (...) like inside "Remux Recordings" or the filepath for a media source it should open a dialog to browse files.

### Current Behavior

When I click a browse button anywhere, OBS closes with no useful report in the logs.

### Steps to Reproduce

1. Just click a browse files (...) button anywhere on the program. Plenty to choose.
2.
3.
...

### Anything else we should know?

Guess it could be something external to OBS, yesterday it seemed to be working fine. The main difference is that today I tried to switch back to X11 because of that idiotic problem with the global hotkeys and it started happening, but now it also happens in wayland.

I have tried to delete the entire config folder (in fact this log I shared comes from a pristine installation of OBS), I have tried to reinstall both master branch and 30.1.2 of OBS, it's all the same.

It really is very annoying that the logs don't tell why in God's name it's closing.

**Comment by Corbent** [comment]
Something new. Tried running OBS straight on the console, instead of the App menu. When it closes I get the message:

zsh: segmentation fault (core dumped)  ./obs

**Comment by Fenrirthviti** [comment]
Please provide a gdb backtrace of the crash.

**Comment by tytan652** [comment]
> 22:48:02.303: OBS 30.1.0-196-gf60d6bcfe (linux)

You are not running OBS 30.1.2, but the master branch (196 commits to master since 30.1.0 when I write this).

**Comment by Corbent** [comment]
> > 22:48:02.303: OBS 30.1.0-196-gf60d6bcfe (linux)
> 
> You are not running OBS 30.1.2, but the master branch (196 commits to master since 30.1.0 when I write this).

In the "anything else we should know" section I mentioned I tried both.

And here's the backtrace. First time using gdb so I hope this is what you are asking for:
https://pastebin.com/0u4NbRDE

**Comment by tytan652** [comment]
> In the "anything else we should know" section I mentioned I tried both.

Log and given version were mismatching, but this is not a problem for this issue.

-----

Looks like an issue more on the KDE Plasma (kwidgetsaddons) 🤔 and since Plasma doesn't use Portals outside of Flatpaks.

Arch Linux GNOME works fine, the only difference is what handles the dialog.

**Comment by culebrasolida** [comment]
I'm also facing the same issue

**Comment by tytan652** [comment]
I forgot to say it explicitly, report the issue to KDE Plasma, if both release and master cause the crash this is unlikely strictly our fault.

**Comment by Corbent** [comment]
Got it. Thank you for your help.

**Comment by Corbent** [comment]
You were completely right! I downgraded kwidgetsaddons and the problem is solved! I need to learn to use this debugging tool because it would ahve saved like 3 invaluable hours of my life last night, I am on to stream tomorrow night.

**Comment by YanEx13** [comment]
Same problem in OBS Flatpak, in RHEL 9.4

**Comment by GuardianLiarus** [comment]
Facing the same issue wether it's flatpak or not same for a friend on arch

**Comment by Corbent** [comment]
As I mentioned, as a temporal workaround see if you can downgrade the kwidgetsaddons package.

6.1.0-1 on Arch works fine for me. I successfully made my first live stream last night. I am very happy.

**Comment by tytan652** [comment]
Messages indicating that you also encountered the issue is not helpful.

Nobody seems to have reported the issue to KDE and posted the link here, the issue will not get fixed if no Plasma user report the issue.

**Comment by Corbent** [comment]
I tried. But I don't even know where to file my report.

I went here:
https://invent.kde.org/frameworks/kwidgetsaddons/-/issues

Which is the source for kwidgetmodules, went to issues, but trying to create one requires KDE Identity which I don't have. So I suppose this is for internal use.

**Comment by GuardianLiarus** [comment]
> I tried. But I don't even know where to file my report.
> 
> I went here: https://invent.kde.org/frameworks/kwidgetsaddons/-/issues
> 
> Which is the source for kwidgetmodules, went to issues, but trying to create one requires KDE Identity which I don't have. So I suppose this is for internal use.

I created an issue on the KDE bug report forms, with the help of OBS friends!: [https://bugs.kde.org/show_bug.cgi?id=487247](https://bugs.kde.org/show_bug.cgi?id=487247)

**Comment by Corbent** [comment]
Thanks!

**Comment by tytan652** [comment]
Saw some of you showing that it happens in the Flatpak, which is weird since the Portal should be used and not kwidgetsaddons directly (so not the same issue/crash).

It makes me question if KDE stack is doing something wrong in a Flatpak context.

**Comment by Pointedstick** [comment]
Thanks for the KDE bug report. I can confirm that this is a regression in our code. We'll get right on it, and ship a bugfix release of the KWidgetsAddons framework once it's fixed.

So sorry for the breakage!

Folks wishing to be appraised of the progress of a fix can CC themselves on https://bugs.kde.org/show_bug.cgi?id=487247.

**Comment by GuardianLiarus** [comment]
> Thanks for the KDE bug report. I can confirm that this is a regression in our code. We'll get right on it, and ship a bugfix release of the KWidgetsAddons framework once it's fixed.
> 
> So sorry for the breakage!
> 
> Folks wishing to be appraised of the progress of a fix can CC themselves on https://bugs.kde.org/show_bug.cgi?id=487247.

You're amazing at what you do, i just want you to know that, you took the time to check the issue on the kde bug report but also respond here as well, thank you so much!

**Comment by Pointedstick** [comment]
Thanks, you are very kind!

**Comment by tytan652** [comment]
This issue will be close once a version of `KWidgetsAddons` with https://invent.kde.org/frameworks/kwidgetsaddons/-/commit/64fcc6fff124dd74e059b9271ba6693a2d561704 is released (e.g. 6.2.1 or 6.3.0).

**Comment by Pointedstick** [comment]
KWidgetsAddons 6.2.1 has been released now.

**Comment by ruineka** [comment]
I can confirm the system OBS package now works, but the flatpak still crashes the moment you attempt to import or export anything.

**Comment by Pointedstick** [comment]
Yes, the KDE Flatpak runtime needs to be updated to include the fix. That should be in progress too.

**Comment by ruineka** [comment]
> Yes, the KDE Flatpak runtime needs to be updated to include the fix. That should be in progress too.

Thanks for the reply! It seems that runtime has been updated according to what I see [here](https://invent.kde.org/packaging/flatpak-kde-runtimel). So I suppose all that is left to be done is the flatpak for obs itself needs to be updated to target 6.7 and not [6.6](https://github.com/obsproject/obs-studio/blob/e54af0d559a9cd66fe7c369b5b4206826f33b7e0/build-aux/com.obsproject.Studio.json#L4).

**Comment by tytan652** [comment]
> So I suppose all that is left to be done is the flatpak for obs itself needs to be updated to target 6.7 and not [6.6](https://github.com/obsproject/obs-studio/blob/e54af0d559a9cd66fe7c369b5b4206826f33b7e0/build-aux/com.obsproject.Studio.json#L4).

No, KDE should also update the 6.6 runtime. OBS has no plan and no reason to change the runtime since 6.6 is still supported.

**Comment by ruineka** [comment]
> > So I suppose all that is left to be done is the flatpak for obs itself needs to be updated to target 6.7 and not [6.6](https://github.com/obsproject/obs-studio/blob/e54af0d559a9cd66fe7c369b5b4206826f33b7e0/build-aux/com.obsproject.Studio.json#L4).
> 
> No, KDE should also update the 6.6 runtime. OBS has no plan and no reason to change the runtime since 6.6 is still supported.
> 
> Edit: https://invent.kde.org/packaging/flatpak-kde-runtime/-/tree/qt6.6 has the update

I see this now too. That is strange because OBS still crashes and I don't see any updates when I run `flatpak upgrade`. Is there something I'm missing here? Sorry, I'm not all to familiar with the flatpak upgrade process.

**Comment by thelabcat** [comment]
Are we sure that OBS has a version number set for the dependency?
