### ISSUE TITLE
No Audio in Discord Screen Share (Mac)

### ISSUE THREAD

**Issue by Chromagram** [obsproject/obs-studio#10688]
### Operating System Info

macOS 14

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/Q7ecrQx4gulKHM5b

### Expected Behavior

When selecting OBS Studio in Discord's screen share, it should broadcast both the video and the audio.

### Current Behavior

Currently, no matter what, only the video will broadcast, but never any audio.

### Steps to Reproduce

1. Open OBS Studio, add a source with audio (in my case, an Elgato HD60S+ capture card)
2. Select Advanced Audio Properties and make sure the monitor is not set to monitor off for the source the audio is coming from.
3. Right click the preview window, select Windowed Preview.
4. In Discord, start a call with somebody, click the Screen Share button. Select Windowed Preview (or OBS directly).

### Anything else we should know?

Firstly, I realize this is something the Discord team should be asked about, I have done that as well. The thing is, when I screen share any other application in Discord, the video and audio come through together no problem. It's strictly OBS Studio that does not have audio, so I was hoping to check with the OBS crew to see if there's some kind of odd restriction in place on this side that Discord can't see.

Additionally, I understand there are some more restrictions in place in general on a Mac versus the Windows version. However, Discord now has a built-in plugin to allow audio to come through on Mac screen share (again, all other apps except for OBS work).

Just in case, I have also tried Rogue Amoeba's Loopback software to create an aggregate audio device. Essentially, I merged my microphone (for chatting on the Discord share) and the OBS Studio audio output, merged it into one audio device, and set my Discord's audio to that. It just creates an echoey mess.

Really hoping I can get this looked at. Even if this is something I have to exclusively take back to Discord support, it would help a lot to receive any info about what is restricted and anything for the Discord team to use to try and troubleshoot this.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
