### ISSUE TITLE
erro 

### ISSUE THREAD

**Issue by Davidras444** [obsproject/obs-studio#10698]
### Operating System Info

Windows 11

### Other OS

windows 10

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/7QcOfXW149cPurLx

### Expected Behavior

iniciar normal

### Current Behavior

meu pc  congela a tela  trava 

### Steps to Reproduce

1. iniciei o obs e trava
2.
3.
...

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
