### ISSUE TITLE
conflito de drives amd

### ISSUE THREAD

**Issue by Davidras444** [obsproject/obs-studio#10697]
### Operating System Info

Windows 11

### Other OS

windows 10

### OBS Studio Version

30.1.2

### OBS Studio Log URL

16:26:36.197: CPU Name: Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz 16:26:36.197: CPU Speed: 2200MHz 16:26:36.197: Physical Cores: 12, Logical Cores: 24 16:26:36.197: Physical Memory: 32674MB Total, 26929MB Free 16:26:36.197: Windows Version: 10.0 Build 19045 (release: 22H2; revision: 4412; 64-bit) 16:26:36.197: Running as administrator: false 16:26:36.197: Windows 10/11 Gaming Features: 16:26:36.197: 	Game Bar: Off 16:26:36.197: 	Game DVR: Off 16:26:36.197: 	Game DVR Background Recording: Off 16:26:36.197: 	Game Mode: On 16:26:36.199: Sec. Software Status: 16:26:36.200: 	Microsoft Defender Antivírus: enabled (AV) 16:26:36.201: 	Firewall do Windows: enabled (FW) 16:26:36.201: Current Date/Time: 2024-05-19, 16:26:36 16:26:36.201: Browser Hardware Acceleration: true 16:26:36.201: Hide OBS windows from screen capture: false 16:26:36.201: Qt Version: 6.6.2 (runtime), 6.6.2 (compiled) 16:26:36.201: Portable mode: false 16:26:36.462: OBS 30.1.0 (64-bit, windows) 16:26:36.462: --------------------------------- 16:26:36.463: --------------------------------- 16:26:36.463: audio settings reset: 16:26:36.463: 	samples per sec: 48000 16:26:36.463: 	speakers:        2 16:26:36.463: 	max buffering:   960 milliseconds 16:26:36.463: 	buffering type:  dynamically increasing 16:26:36.466: --------------------------------- 16:26:36.466: Initializing D3D11... 16:26:36.466: Available Video Adapters:  16:26:36.468: 	Adapter 0: AMD Radeon RX 580 2048SP 16:26:36.468: 	  Dedicated VRAM: 8567906304 (8.0 GiB) 16:26:36.468: 	  Shared VRAM:    17130596352 (16.0 GiB) 16:26:36.468: 	  PCI ID:         1002:6fdf 16:26:36.469: 	  HAGS Status:    Disabled (Default: No, Driver status: Unsupported) 16:26:36.469: 	  Driver Version: 31.0.21912.14 16:26:36.470: 	  output 0: 16:26:36.470: 	    name=QG240Y S3 16:26:36.470: 	    pos={0, 0} 16:26:36.470: 	    size={1920, 1080} 16:26:36.470: 	    attached=true 16:26:36.470: 	    refresh=180 16:26:36.470: 	    bits_per_color=10 16:26:36.470: 	    space=RGB_FULL_G22_NONE_P709 16:26:36.470: 	    primaries=[r=(0.680664, 0.309570), g=(0.240234, 0.685547), b=(0.142578, 0.075195), wp=(0.313477, 0.329102)] 16:26:36.470: 	    relative_gamut_area=[709=1.363380, P3=1.005044, 2020=0.721052] 16:26:36.470: 	    sdr_white_nits=80 16:26:36.470: 	    nit_range=[min=0.078600, max=417.000000, max_full_frame=391.000000] 16:26:36.470: 	    dpi=96 (100%) 16:26:36.470: 	    id=\\?\DISPLAY#ACR0B4E#5&36f328b0&0&UID260#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} 16:26:36.470: 	    alt_id=\\.\DISPLAY1 16:26:36.470: Loading up D3D11 on adapter AMD Radeon RX 580 2048SP (0) 16:26:36.514: D3D11 loaded successfully, feature level used: b000 16:26:36.514: DXGI increase maximum frame latency success 16:26:36.514: D3D11 GPU priority setup failed (not admin?) 16:26:36.671: --------------------------------- 16:26:36.671: video settings reset: 16:26:36.671: 	base resolution:   1920x1080 16:26:36.671: 	output resolution: 2560x1440 16:26:36.671: 	downscale filter:  Bicubic 16:26:36.671: 	fps:               60/1 16:26:36.671: 	format:            NV12 16:26:36.671: 	YUV mode:          Rec. 709/Partial 16:26:36.671: NV12 texture support enabled 16:26:36.671: P010 texture support not available 16:26:36.674: Audio monitoring device: 16:26:36.674: 	name: Padrão 16:26:36.674: 	id: default 16:26:36.674: --------------------------------- 16:26:36.677: No AJA devices found, skipping loading AJA UI plugin 16:26:36.678: Failed to initialize module 'aja-output-ui.dll' 16:26:36.679: No AJA devices found, skipping loading AJA plugin 16:26:36.679: Failed to initialize module 'aja.dll' 16:26:36.679: Skipping module '../../obs-plugins/64bit/chrome_elf.dll', not an OBS plugin 16:26:36.683: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded 16:26:36.683: Failed to load 'en-US' text for module: 'decklink-captions.dll' 16:26:36.684: Failed to load 'en-US' text for module: 'decklink-output-ui.dll' 16:26:36.689: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed 16:26:36.689: Failed to initialize module 'decklink.dll' 16:26:36.700: Skipping module '../../obs-plugins/64bit/libcef.dll', not an OBS plugin 16:26:36.700: Skipping module '../../obs-plugins/64bit/libEGL.dll', not an OBS plugin 16:26:36.700: Skipping module '../../obs-plugins/64bit/libGLESv2.dll', not an OBS plugin 16:26:36.721: [obs-browser]: Version 2.23.4 16:26:36.721: [obs-browser]: CEF Version 103.0.5060.134 (runtime), 103.0.0-5060-shared-textures.2594+gc69ad37+chromium-103.0.5060.134 (compiled) 16:26:36.840: [noise suppress]: NVIDIA denoiser disabled, redistributable not found or could not be loaded. 16:26:36.841: Failed to get NVVideoEffects.dll version info size 16:26:36.843: [NVIDIA VIDEO FX]: FX disabled, redistributable not found or could not be loaded. 16:26:36.889: [obs-websocket] [obs_module_load] you can haz websockets (Version: 5.4.2 | RPC Version: 1) 16:26:36.889: [obs-websocket] [obs_module_load] Qt version (compile-time): 6.6.2 | Qt version (run-time): 6.6.2 16:26:36.889: [obs-websocket] [obs_module_load] Linked ASIO Version: 102900 16:26:36.900: [obs-websocket] [obs_module_load] Module loaded. 16:26:36.909: [vlc-video]: VLC 3.0.20 Vetinari found, VLC video source enabled 16:26:36.919: --------------------------------- 16:26:36.919:   Loaded Modules: 16:26:36.919:     win-wasapi.dll 16:26:36.919:     win-dshow.dll 16:26:36.919:     win-capture.dll 16:26:36.919:     vlc-video.dll 16:26:36.919:     text-freetype2.dll 16:26:36.919:     rtmp-services.dll 16:26:36.919:     obs-x264.dll 16:26:36.919:     obs-websocket.dll 16:26:36.919:     obs-webrtc.dll 16:26:36.919:     obs-vst.dll 16:26:36.919:     obs-transitions.dll 16:26:36.919:     obs-text.dll 16:26:36.919:     obs-qsv11.dll 16:26:36.919:     obs-outputs.dll 16:26:36.919:     obs-filters.dll 16:26:36.919:     obs-ffmpeg.dll 16:26:36.919:     obs-browser.dll 16:26:36.919:     logi_obs_plugin_x64.dll 16:26:36.919:     image-source.dll 16:26:36.919:     frontend-tools.dll 16:26:36.919:     decklink-output-ui.dll 16:26:36.919:     decklink-captions.dll 16:26:36.919:     coreaudio-encoder.dll 16:26:36.919: --------------------------------- 16:26:36.925: QWidget::setTabOrder: 'first' and 'second' must be in the same window 16:26:36.926: ==== Startup complete =============================================== 16:26:36.978: All scene data cleared 16:26:36.978: ------------------------------------------------ 16:26:36.982: [win-wasapi: 'Áudio do desktop'] update settings: 16:26:36.982: 	device id: default 16:26:36.982: 	use device timing: 1 16:26:36.983: [Loaded global audio device]: 'Áudio do desktop' 16:26:36.983: [win-wasapi: 'Mic/Aux'] update settings: 16:26:36.983: 	device id: default 16:26:36.983: 	use device timing: 0 16:26:36.983: [noise suppress: 'Supressão de ruídos'] NVAFX redist is not installed. 16:26:36.984: [noise suppress: 'Supressão de ruídos 2'] NVAFX redist is not installed. 16:26:36.984: [Loaded global audio device]: 'Mic/Aux' 16:26:36.984:     - filter: 'Supressão de ruídos' (noise_suppress_filter_v2) 16:26:36.984:     - filter: 'Supressão de ruídos 2' (noise_suppress_filter_v2) 16:26:36.985: [window-capture: 'Captura de janela'] update settings: 16:26:36.985: 	executable: Bluestacks.exe 16:26:36.985: 	method selected: Automatic 16:26:36.985: 	method chosen: BitBlt 16:26:36.985: 	force SDR: false 16:26:36.988: [duplicator-monitor-capture: 'Captura de tela'] update settings: 16:26:36.988: 	display: QG240Y S3 (1920x1080) 16:26:36.988: 	cursor: true 16:26:36.988: 	method: DXGI 16:26:36.988: 	id: \\?\DISPLAY#ACR0B4E#5&36f328b0&0&UID260#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} 16:26:36.988: 	alt_id: \\.\DISPLAY1 16:26:36.988: 	setting_id: \\?\DISPLAY#ACR0B4E#5&36f328b0&0&UID260#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7} 16:26:36.988: 	force SDR: false 16:26:36.990: Switched to scene 'Cena' 16:26:36.990: ------------------------------------------------ 16:26:36.990: Loaded scenes: 16:26:36.990: - scene 'Cena': 16:26:36.990:     - source: 'Captura de janela' (window_capture) 16:26:36.990:     - source: 'meta' (browser_source) 16:26:36.990:     - source: 'alerta' (browser_source) 16:26:36.990:     - source: 'msg' (browser_source) 16:26:36.990:     - source: 'Imagem' (image_source) 16:26:36.990:     - source: 'Captura de tela' (monitor_capture) 16:26:36.990: ------------------------------------------------ 16:26:37.009: WASAPI: Device '5 - QG240Y S3 (AMD High Definition Audio Device)' [48000 Hz] initialized (source: Áudio do desktop) 16:26:37.016: WASAPI: Device 'Microphone (High Definition Audio Device)' [44100 Hz] initialized (source: Mic/Aux) 16:26:37.085: adding 85 milliseconds of audio buffering, total audio buffering is now 85 milliseconds (source: Mic/Aux) 16:26:37.085:  16:26:37.108: YT: InitYTUserUrl() User is not signed 16:26:37.109: YT: InitYTUserUrl() User is not signed 16:26:38.534: [obs-browser: 'alerta'] Error: Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('https://streamlabs.com'). (https://www.youtube.com/s/player/b05eda73/www-widgetapi.vflset/www-widgetapi.js:275) 16:26:56.892: Failed to read log file C:\Users\david\AppData\Roaming\obs-studio/crashes/

### Expected Behavior

iniciar normal

### Current Behavior

meu pc  congela a tela  trava 

### Steps to Reproduce

1. iniciei o obs e trava
2.
3.
...

**Comment by kkartaltepe** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
