### ISSUE TITLE
OBS fails to record to UDP url in NUT container with av1_vaapi encoder

### ISSUE THREAD

**Issue by shmerl** [obsproject/obs-studio#10705]
### Operating System Info

Other

### Other OS

Debian testing Linux

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/CTBijZVCrRXKhjIV

### Expected Behavior

It should be possible to record to UDP URL with custom output (ffmpeg) using a nut container and av1_vaapi encoder.

### Current Behavior

With the above set up, OBS fails with such error:

![image](https://github.com/obsproject/obs-studio/assets/310927/ce9e06ed-f439-4e28-847c-6d4e70640a0f)

The log error isn't very informative about it:

```
00:53:59.756: Failed to open video codec: Invalid argument
00:53:59.756: ffmpeg_data_init failed
```

### Steps to Reproduce

1. Select some video source, like screen or window to share.
2. Set Settings > Output > Recording as follows:

![settings](https://github.com/obsproject/obs-studio/assets/310927/bc9dbe4b-868a-49c3-96bc-7a53828d0598)

4. Start Recording

### Anything else we should know?

* Above set up works for example with libsvtav1 codec selected.
* AV1 hardware encoding works fine for me when recording to a file using "Standard" type and selecting FFmpeg VAAPI AV1.
* UDP URL is using an IPv6 address in format `udp://[xxxx:...:xxxx]:1234` (address is correct and works with libsvtav1 as above).

**Comment by WizardCM** [comment]
Launch OBS from the terminal, and additional FFmpeg errors will appear in the terminal window. That should provide insight into what's going wrong.

**Comment by derrod** [comment]
The nut container doesn't support AV1 (officially), also FFmpeg output is very much untested/unsupported and you're on your own if things break.

**Comment by shmerl** [comment]
Unfortunately output in the terminal is exactly the same as the saved log. Is there some environment variable to increase verbosity / get more debug info?

And if nut container isn't suitable for AV1, which one is preferable?

I basically want to produce such scenario:

OBS sends data to some UDP URL (using AV1)
On the receiving end, mpv or ffplay decodes it and displays it.

That works with nut for example when using av1 encoded with libsvtav1, so it means it can work somehow?

**Comment by Fenrirthviti** [comment]
I'd recommend trying the support channels, as this doesn't seem to be a bug.

**Comment by shmerl** [comment]
Could be, but I want to confirm it's not actually a bug, and from the error there isn't enough info. If there is no way to increase log verbosity, I can try debugging it may be. I see log produces info and warn messages, but no debug ones.

Is there some setting or variable to increase it?

**Comment by shmerl** [comment]
OK, I managed to get a bit more info, by running it as `obs --verbose`

```
debug: [pipewire] Out of buffers!
debug: obs_output_set_audio_encoder: Null 'output' parameter
debug: A hardware frames reference is required to associate the encoding device.

warning: Failed to open video codec: Invalid argument
warning: ffmpeg_data_init failed
```

Not sure if `A hardware frames reference is required to associate the encoding device` is related or not.

**Comment by shmerl** [comment]
Digging through [this](https://github.com/obsproject/obs-studio/issues/5590#issuecomment-981176577) apply here?

I.e.:

> You cannot set this parameter via any of the existing settings parameters.

So currently it's simply impossible to use <...>_vaapi encoders in practice with that custom ffmpeg output path or I didn't understand something correctly?

**Comment by shmerl** [comment]
Yeah, looks like `obs-ffmpeg-output.c` is simply missing enabling hardware acceleration :( I tried using the above referenced patch reading VAAPI device with the help of `aapi_get_av1_default_device` / `aapi_get_h264_default_device` from vaapi-utils.* but something didn't really work, so I scrapped that effort.

I think having hardware acceleration for custom ffmpeg output at least for h264 and av1 is a worthy thing to implement. Because trying to go to cli ffmpeg isn't a good solution either, since it's still missing XDG portal integration so it can't properly handle screen or window sharing on Linux.

**Comment by shmerl** [comment]
@kkartaltepe: Do you have any suggestion how it can be implemented?

**Comment by DocMAX** [comment]
+1

**Comment by shmerl** [comment]
Personally I stopped bothering using OBS when I need custom ffmpeg output path with hardware acceleration. OBS developers clearly showed they don't want to support such case even though it should be supported.

If you need it, use something like [gpu-screen-recorder](https://git.dec05eba.com/gpu-screen-recorder/about/) for that.

Unfortunately it's still impossible yet to use the ffmpeg CLI tool directly for screen recording case, since they still didn't implement pipewire video capture source.
