### ISSUE TITLE
Problems with Hardware-accelerated GPU Scheduler

### ISSUE THREAD

**Issue by Yagodichka** [obsproject/obs-studio#10707]
### Operating System Info

Windows 11

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/ymSDoxd9gnN63ZYg

### Expected Behavior

OBS should work smoothly and not crash during the stream.

### Current Behavior

OBS crashes at random times during the stream. There are no error warnings. It just freezes. You have to shut down through the taskbar.
If you disable the Hardware-accelerated GPU Scheduler in the Windows settings, the OBS will slow down completely and it will be uncomfortable to use it for recording while playing a game. Sometimes, due to the brakes, it spoils the sound on the video. I need Hardware-accelerated GPU Scheduler to be enabled.

### Steps to Reproduce

1.Start broadcasting the game simultaneously with the web camera.
2.Wait a random amount of time.
3.OBS freezes itself.
...

**Comment by test12302008** [comment]
I encountered a similar issue when playing Hotta. To reproduce the freeze problem, it is not necessary to conduct live broadcast or video recording, but only to capture the DX12 game. When the issue arises, the OBS logs are normal and the crash logs are empty. By monitoring the memory usage (committed) in the Windows Task Manager, I inferred conflicts arise from the memory management mechanisms of the game, Win11 OS, and OBS. I conducted some WinDbg debugging sessions, occasionally encountering a call stack at VCRUNTIME140!memcpy_avx_ermsb_Intel.

**Comment by Fenrirthviti** [comment]
HAGS is a system-level driver implementation that OBS has no control over. What you're describing is, unfortunately, outside what we realistically have any control over. We log the current HAGS state in the OBS logs, but as the stack indicates, the stall is happening in the driver, not OBS.

While HAGS has improved stability since being introduced (we used to full-stop recommend turning it off), we still recommend disabling it when it causes issues like this.

**Comment by Xypha85** [comment]
with HAGS being required for DLSS 3 and up, and now 4 being released this is going to get more problematic, a fix thats not tuning it off or some info about it would be really good?

**Comment by pbaykalov** [comment]
@Xypha85 as it was explained on OBS forums HAGS is basically a black box and cannot be fixed from outside. Basically, you should ask Nvidia to fix any problem you encounter. Maybe you might use Nvidia Inspector to fine-tune some behaviour.

Maybe you should also look into Radeon and Intel Arc to have at least another option.
