### ISSUE TITLE
OBS doesn't follow system-wide Qt theming properties

### ISSUE THREAD

**Issue by Tiagoquix** [obsproject/obs-studio#10715]
### Operating System Info

Other

### Other OS

Fedora Linux 40 KDE

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.1.1 (from Fedora official repository)

### OBS Studio Log URL

https://obsproject.com/logs/4XF0gO2q0s6VAtzH

### Expected Behavior

OBS Studio should follow KDE Plasma Qt style properties for keyboard accelerators/(X11) mnemonics.

I did a fresh reinstall of OBS to be sure the problem was not on my side (that's why the logs contain unfinished things).

------------------------

Notice the underlines:

![image](https://github.com/obsproject/obs-studio/assets/30274161/bcfa42f8-bd56-4291-875f-d60db328ef2a)

------------------------

Notice the `&` (same bug as #10341):
![image](https://github.com/obsproject/obs-studio/assets/30274161/a615cc5b-c7cd-4458-a7ec-52c6f00cb905)

------------------------

On KDE Plasma 6 settings, I have "Keyboard accelerators visibility" set to "Always hide":
![image](https://github.com/obsproject/obs-studio/assets/30274161/89016081-201c-4082-829a-762fad41a711)

------------------------

If I change the theme to "System" from OBS settings, it fixes the bug described in #10341:
![image](https://github.com/obsproject/obs-studio/assets/30274161/6c41d59b-7015-4d6c-b365-166d228e924e)

------------------------

Using Yami, the default theme (because the "System" one is not the best for OBS), and launching OBS with `QT_STYLE_OVERRIDE=Breeze obs`, most of the keyboard accelerators go away:
![image](https://github.com/obsproject/obs-studio/assets/30274161/6022e744-e1b1-434a-a160-1c4bc92806c2)

------------------------

Except for the main menu ones, which are still shown:
![image](https://github.com/obsproject/obs-studio/assets/30274161/d5413ec2-591c-4cfa-9fcf-3b327e85cbbc)

------------------------

The settings menu also respects the new Qt override normally:
![image](https://github.com/obsproject/obs-studio/assets/30274161/e9623eae-889c-44a1-976f-a6d592290c2f)

------------------------

The `&` bug, however, is not fixed with the Qt override:
![image](https://github.com/obsproject/obs-studio/assets/30274161/02fca94e-f9f1-473e-b13d-af97b59152be)

------------------------

### Current Behavior

OBS doesn't respect system-wide keyboard accelerators visibility setting, and it seems to force its own Qt theming.

### Steps to Reproduce

Explained above.

### Anything else we should know?

Maybe transform this bug report into a new setting for OBS?

**Comment by tytan652** [comment]
OBS Studio only support Fusion as Qt style on Linux.

Any other QT style is not supported.
