### ISSUE TITLE
Failed to connect to server The RTMP server sent an invalid SSL certificate.

### ISSUE THREAD

**Issue by CitizenScyu** [obsproject/obs-studio#10712]
### Operating System Info

Other

### Other OS

Windows server 2022

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/YbbAsVxkN8vflY5G

### Expected Behavior

I hope the problem of ssl certificate error can be solved

### Current Behavior

I am in Windows server2022 system. After clicking Start Streaming, I am prompted Failed to connect to server.
The RTMP server sent an invalid SSL certificate.
Please tell me how to solve this problem. I tried through proxy but the problem was not solved.

### Steps to Reproduce

1.
2.
3.
...
![image](https://github.com/obsproject/obs-studio/assets/58416773/cd0a768d-8446-44b5-9a16-3af428f1a79d)

**Comment by derrod** [comment]
This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels below, and if it's determined that this is indeed a bug, then we will re-open this issue.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
