### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by Yuriltlef** [obsproject/obs-studio#10728]
### Operating System Info

Windows 11

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/Ne7cczFhcCAaAjJq

### Expected Behavior

以正常性能推流视频

### Current Behavior

当我启动OBS并在场景中添加了带有滤镜的窗口时，OBS似乎使dwm发生了异常（疑似内存泄漏），并且cpu占用非常高，使得鼠标卡顿，并且当游戏视角转动时有剧烈的fps波动。

### Steps to Reproduce

1.使用一个高回报率的鼠标（会使问题更加明显，我的是罗技G102）
2.打开Minecraft并启动光影使得GPU占用很高
3.启动OBS并且添加窗口采集（QQ音乐），采集方式：win10，添加l亮度键和色值滤镜
4.观察到MC帧率明显下滑，鼠标卡顿（尤其是这时启动其他有GPU占用的应用会非常明显）

```[tasklist]
### Tasks
```

**Comment by WizardCM** [comment]
This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels below, and if it's determined that this is indeed a bug, then we will re-open this issue.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
