### ISSUE TITLE
Is there a headless mode?

### ISSUE THREAD

**Issue by alanakos33** [obsproject/obs-studio#10729]
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

30.1.2

### OBS Studio Log URL

n/a

### Expected Behavior

It would be nice to launch obs in headless mode, since i am driving it solely by using obs-websocket api.

Is there a way to achieve that? And if not, are there any plants to implement such a feature?

### Current Behavior

The ui client which i don't use has to start every time.

### Steps to Reproduce

1. Launch obs to use it mainly as a headless server
2. Have the ui get in the way and consume resources.

**Comment by derrod** [comment]
No.

**Comment by alanakos33** [comment]
> No.

Are there no plans to add one? Since websocket-api is part of the obs-studio now, it would make sense to support a way to run it headlessly since the client is unnecessary.

**Comment by derrod** [comment]
> Are there no plans to add one? 

Yes.

**Comment by alanakos33** [comment]
> > Are there no plans to add one?
> 
> Yes.

You have a way with words don't you?

**Comment by Fenrirthviti** [comment]
We don't use github discussions for support requests/suggestions. Make sure you read any [pinned posts](https://github.com/obsproject/obs-studio/discussions/5206) on discussion boards before opening a new discussion. This has already been suggested and discussed on our Ideas page: https://ideas.obsproject.com/posts/16/add-a-headless-mode-that-allows-full-control-via-scripting-api

Thank you!
