### ISSUE TITLE
Trying to build Flatpak from Git , `libobs-opengl.so` not found

### ISSUE THREAD

**Issue by AFCMS** [obsproject/obs-studio#10737]
### Operating System Info

Other

### Other OS

Fedora 40

### OBS Studio Version

Git

### OBS Studio Log URL

https://gist.github.com/AFCMS/ce8400fcc09288c00478cf4bc2ea95c2

(not a obsproject.com uploaded log file because the interface didn't show up at all)

### Expected Behavior

I would like the software to start and work.

### Current Behavior

I wanted to build the latest Git version of OBS.

For that I cloned recursively the Git repo and executed the following:
```shell
flatpak-builder --user --install build-dir --force-clean ./build-aux/com.obsproject.Studio.json
```

The build worked fine but when I run `flatpak run --user com.obsproject.Studio` (no other versions of OBS are installed in Flatpak) in my terminal a small popup appear with `Failed to initialize video:  Graphics module not found`, while in logs there are two error lines:
```
error: os_dlopen(libobs-opengl.so.30->libobs-opengl.so.30): libobs-opengl.so.30: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type
error: Failed to initialize video:  Graphics module not found
```

![image](https://github.com/obsproject/obs-studio/assets/61794590/45f5c196-b119-48f9-b422-e2d1eb642473)

### Steps to Reproduce

I am unsure, really. I would have expected the Flatpak to work straight since it's a cross-platform format and the build process went smoothly.

I did multiple tests on my hardware/config and all lead to the same result.

**Comment by tytan652** [comment]
Feel free to test #10739

**Comment by AFCMS** [comment]
Wow that was fast! It seems to fix the problem :+1:

**Comment by tytan652** [comment]
For more context, `dlopen()` does not seem to take `/app/lib` in account.

**Comment by tytan652** [comment]
Apparently there was an issue inside the main runtime which contaminated its children.

**Comment by tytan652** [comment]
So the issue was on use, #10741 should fix it the right way.

**Comment by AFCMS** [comment]
Will test as soon as possible.
