### ISSUE TITLE
Crashes with Nvidia 555, kwin-explicit-sync on Wayland

### ISSUE THREAD

**Issue by quikssb** [obsproject/obs-studio#10734]
### Operating System Info

Other

### Other OS

NixOS

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/TkAUs3dAh9yNOXcK

### Expected Behavior

Open `Windowed Projector (Preview)` or `Fullscreen Projector (Preview)`. The Projector should open.

### Current Behavior

Open `Windowed Projector (Preview)` or `Fullscreen Projector (Preview)`  in a scene always results in a crash of OBS.

### Steps to Reproduce

1. Right click in a scene
2. Click on `Windowed Projector (Preview)` or `Fullscreen Projector (Preview)`

Use the new Nvidia Beta driver 555 on Wayland on a Linux system.

This error is taken from `journalctl --user`: 
```
wp_linux_drm_syncobj_surface_v1@118: error 4: explicit sync is used, but no acquire point is set
May 26 10:28:03 pizzapc plasmashell[3565]: warning: The Wayland connection experienced a fatal error
```

People seem to experience a similar issue also on other software like Firefox: https://www.reddit.com/r/linux_gaming/comments/1cxhxja/is_anybody_elses_firefox_crashing_with/

### Anything else we should know?

OBS works properly on X11 with the new driver.

**Comment by tytan652** [comment]
Close as it's not bug from OBS Studio.
