### ISSUE TITLE
the ffmpeg in can't find intel qsv encoder,but obs can use the qsv encoder to stream

### ISSUE THREAD

**Issue by CLDYG7240** [obsproject/obs-studio#10766]
### Operating System Info

Windows 11

### OBS Studio Version

30.1.2

### OBS Studio Log URL

none

### Expected Behavior

the ffmpeg in can find intel qsv encoder

### Current Behavior

the ffmpeg in can't find intel qsv encoder

### Steps to Reproduce

setting-advanced-recording-ffmpeg-videoencoder

**Comment by tytan652** [comment]
The FFmpeg built for OBS is not built with libvpl, this is not a bug.
