### ISSUE TITLE
NVENC HEVC colors distorted with 4:4:4 pixel formats

### ISSUE THREAD

**Issue by Maxoverpower** [obsproject/obs-studio#10768]
### Operating System Info

Windows 11

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/KaN4d8pOaz9qMOvG

### Expected Behavior

When recording in native resolution using 4:4:4 chroma subsampling, colored edges are expected to appear exactly as they do in the source image.

### Current Behavior

While chroma resolution is maintained, colored edges are visibly misrepresented. Comparison - https://slow.pics/c/OlrJWkyU
x264 and H.264 NVENC can reproduce the original image without issues, only HEVC fails.

### Steps to Reproduce

1. Using any material with colored text, take a screenshot or H.264 recording as reference, with 4:4:4 chroma.
2. Record the same material with HEVC NVENC.
3. Compare the results.

### Anything else we should know?

Unfortunately, this appears to be a fault of the encoder, - I was able to replicate the issue using an ffmpeg encode, outside of OBS.

GIven that HEVC NVENC can technically record 10-bit 4:4:4 in OBS, when combining its ffmpeg output variety with P416 format, - it looked like a promising option for near-lossless HDR video recording. But having found this, the encoder looks a lot less appealing, so we're basically out of options for recording high quality 4:4:4 HDR.

**Comment by derrod** [comment]
> Unfortunately, this appears to be a fault of the encoder, - I was able to replicate the issue using an ffmpeg encode, outside of OBS.

So you've determined it's not an issue with OBS, then why did you still open this?

> GIven that HEVC NVENC can technically record 10-bit 4:4:4 in OBS, when combining its ffmpeg output variety with P416 format, - it looked like a promising option for near-lossless HDR video recording. But having found this, the encoder looks a lot less appealing, so we're basically out of options for recording high quality 4:4:4 HDR.

OBS does not support any 10-bit 444 format and NVENC doesn't support P416 so for the time being 444 recording is restricted to 8-bit.
