### ISSUE TITLE
Build dependency librist-dev not available on Ubuntu 22.04

### ISSUE THREAD

**Issue by Erotemic** [obsproject/obs-studio#10762]
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

Git

### OBS Studio Version (Other)

cf4681a9c3f177269c2d7344984497ce2cbaf3f7

### OBS Studio Log URL

None

### Expected Behavior

I would expect the build instructions for Debian based systems would work on Ubuntu 22.04 or there would be a note saying which Debian variants were supported.

https://github.com/obsproject/obs-studio/wiki/Build-Instructions-For-Linux

### Current Behavior

The build instructions claim you can `apt install librist-dev`, but I get an error saying: `Unable to locate package librist-dev`. 

### Steps to Reproduce

Let's test this on a minimal system using docker. Starting from a fresh Ubuntu 22.04 container: 

```
docker run -it ubuntu:22.04 bash
```

I run: 

```
apt update
apt install librist-dev
```

and get:

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package librist-dev
```

Indicating that this dependency is not available on Ubuntu 22.04. However running on `docker run -it debian bash` it does work. It also seems to work on Ubuntu 24.04.

### Anything else we should know?

I think the resolution to this is just marking that the install instructions with the minimum Ubuntu that works would be helpful. Either that, or providing a link to a PPA for librist-dev or some other way to get it?

**Comment by tytan652** [comment]
Not a bug, Ubuntu does not provide librist, `-DENABLE_NEW_MPEGTS_OUTPUT=OFF` disable the feature realying on it.

The wiki is mainly community maintained.

**Comment by Erotemic** [comment]
I just went to the build instructions wiki and added the note:

> **NOTE:** On Ubuntu 22.04, librist-dev is not provided. Add `-DENABLE_NEW_MPEGTS_OUTPUT=OFF` to disable the feature that relies on it.

And I was expecting it to ask me to fork the repo and submit an MR, but it seems like it just directly accepted my change!? Is that expected?

**Comment by gxalpha** [comment]
You edited the wiki. Changes there are not part of the actual repo.
