### ISSUE TITLE
Beta version crashes on Win11 24h2 26100 release preview

### ISSUE THREAD

**Issue by Ptilopsis01** [obsproject/obs-studio#10799]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.0-beta1

### OBS Studio Log URL

cannot get it

### Expected Behavior

OBS starts correctly

### Current Behavior

[Crash 2024-06-08 16-04-59.txt](https://github.com/user-attachments/files/15747265/Crash.2024-06-08.16-04-59.txt)
It crashes just when I start the application. 

### Steps to Reproduce

1. Install the latest beta ver.
2. Start OBS
3. OBS crashes

**Comment by maginhart** [comment]
same
[Crash 2024-06-08 13-33-23.txt](https://github.com/user-attachments/files/15747645/Crash.2024-06-08.13-33-23.txt)

**Comment by derrod** [comment]
Ismyour Windows set to a non-English language?

**Comment by maginhart** [comment]
In my case no, windows is set to English

**Comment by notr1ch** [comment]
Can you try updating your VC redist? https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by knot2006** [comment]
> Can you try updating your VC redist? https://aka.ms/vs/17/release/vc_redist.x64.exe

Thank you! This fixed crashing for me.

**Comment by maginhart** [comment]
Worked in my case too.

**Comment by Ptilopsis01** [comment]
Works for me, thx a lot!

**Comment by RytoEX** [comment]
As of OBS Studio 30.2.0 Beta 3, this should be resolved as much as we can manage now.
