### ISSUE TITLE
obs cannot record on "Nouveau"

### ISSUE THREAD

**Issue by flowerseacar** [obsproject/obs-studio#10811]
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

30.2.0-beta1

### OBS Studio Log URL

https://obsproject.com/logs/b5wUqBsTaonHBaGp

### Expected Behavior

can work

### Current Behavior

Black screen

### Steps to Reproduce

use Nouveau on wayland

**Comment by kkartaltepe** [comment]
Please dont recreated closed issues, #10792

Unless you can provide a log that works with another graphics driver, in which case you should have updated your original issue.
