### ISSUE TITLE
Resize output (source size) doesn't work with source cropping

### ISSUE THREAD

**Issue by pjhfggij** [obsproject/obs-studio#10814]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.1.2-1

### OBS Studio Log URL

https://obsproject.com/logs/DMypG5v0zf18OB56

### Expected Behavior

1. Crop Source by dragging by window corners with alt pressed
2. right click on the source
3. Select "Resize output (source size)"
4. Output of the recording is in the resolution of the cropped source

### Current Behavior

Steps 1.-3. are the same, but the output resolution isn't cropped (black background appears).

### Steps to Reproduce

1. Crop Source by dragging by window corners with alt pressed
2. right click on the source
3. Select "Resize output (source size)"
4. Observe output resolution isn't cropped

### Anything else we should know?

This is duplicate of [this issue](https://github.com/obsproject/obs-studio/issues/4969), however the solution proposed there is cumbersome - it requires you to apply a Crop/Pad filter that can only be entered numerically.

Please let me know if this would break anyone's workflow if the "Resize output (source size)" option followed the source crop region? If so, maybe it could work only when the cropped source is the only source in the scene? 

Or if that would still break someone's workflow why not create a new "Resize output (cropped source size)" entry in the right click context menu?

Other users expressed [similar view](https://obsproject.com/forum/threads/resize-base-and-output-res-to-current-source-size.138795/)

**Comment by Penwy** [comment]
cropping by holding alt does not affect the source size, only the sceneitem's, so it's normal that resizing output to source size does not take it into account.
If you want it to resize to the cropped source size, use a crop filter instead.

**Comment by pjhfggij** [comment]
@Penwy thank you for the quick reply, I've since clarified the issue, like you said you CAN do that using crop/pad filter, but it's cumbersome:

```org
* crop source
hold alt when clicking on any of the display capture windows handles and drag
copy its heigh/width
* add Crop/Pad Filter
right click on source
choose Filters
Add Crop/Pad
Enter the height and width
* apply
1. right click on the source in the display window
2. Resize output (source size)
```

instead it could be as simple as:
* crop source
hold alt when clicking on any of the display capture windows handles and drag
* apply
1. right click on the source in the display window
2. Resize output (source size)
```

**Comment by Penwy** [comment]
Well, if you want to change the current behaviour to that, you can propose it, but as it is, it's not an issue, it's expected behaviour.

**Comment by gxalpha** [comment]
Closing per the above. We use GitHub exclusively for bug reports.
Please put ideas and feature requests on [our ideas page](https://ideas.obsproject.com).

Thank you!

**Comment by pjhfggij** [comment]
[Submitted](https://ideas.obsproject.com/posts/2609/resize-output-source-size-to-source-crop)
[Another good/related idea](https://ideas.obsproject.com/posts/1396/make-the-option-resize-output-source-size-automatic)
