### ISSUE TITLE
OBS ERROR VIA FLATPAK

### ISSUE THREAD

**Issue by jas-ells** [obsproject/obs-studio#10816]
### Operating System Info

Other

### Other OS

DEBIAN 12.5 STABLE

### OBS Studio Version

30.1.2

### OBS Studio Log URL

flatpak install flathub com.obsproject.Studio

### OBS Studio Crash Log URL

flatpak install flathub com.obsproject.Studio

### Expected Behavior

it working properly and not crashing.

### Current Behavior

Hello! I use Debian 12.5 stable and the OBS version 29.02 is natively available in the repository. I tried to use the current version via flatpak and OBS has been closing by itself, and when it opens, the interface is buggy and freezes after a few seconds. (Note: version 29.02 works correctly, but I want to use the current version.) I thank you in advance for your attention and help.

### Steps to Reproduce

1. Bug
2. Crash
3. Close by itself
...

**Comment by kkartaltepe** [comment]
Please fill out the bug template correctly if you do not want your issue to be closed immediate. If you think obs is crashing you must provide a backtrace from gdb as well.

**Comment by jas-ells** [comment]
Like what? I use version 29.02 of the Debian 12.5 stable repository. I try to install the OBS version through Flatpak and it simply opens, takes a while, crashes and closes by itself. With that, I'm stuck on version 29.02 because it works correctly on Debian. I looked for a '.deb' version on the OBS github for Debian, but I didn't get it. The way I see to stay up to date is to use flatpak. That's what happens.

**Comment by jas-ells** [comment]
How do I find the 'failure file' for this issue to post here?

**Comment by kkartaltepe** [comment]
For using gdb in the Flatpak ([src](https://docs.flatpak.org/en/latest/debugging.html)):
``` sh
$ flatpak install org.freedesktop.Sdk.Debug com.obsproject.Studio.Debug # Optional: Install OBS Studio debug symbols
$ flatpak run --command=sh --devel com.obsproject.Studio
$ gdb /app/bin/obs
```

Once `gdb` ready, run by entering the command `r` and reproduce the crash.
Once done, you should be able to enter the command `bt`. Message the output of this command.
You can quit by entering the command `q`.

**Comment by jas-ells** [comment]
It's asking to download 3GB of file. Even so, it gave an error. Well, it didn't work.

**Comment by kkartaltepe** [comment]
It sounds like there is nothing actionable in this report, feel free to attach all the things requested later and we can consider reopening this.
