### ISSUE TITLE
[BUG] Crash at startup with segmentation fault in libFcitx5Qt6DBusAddons.so.1

### ISSUE THREAD

**Issue by autogris** [obsproject/obs-studio#10815]
### Operating System Info

Other

### Other OS

Slackware

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://pastebin.com/3LWiL9DH

### Expected Behavior

Should open the application normally.

### Current Behavior

Crashes at the startup with segmentation fault. This is the backtrace:
```
Thread 1 "obs" received signal SIGSEGV, Segmentation fault.
0x00007fffe9522f91 in fcitx::FcitxQtWatcher::watch() ()
   from /usr/lib64/libFcitx5Qt6DBusAddons.so.1
(gdb) bt
#0  0x00007fffe9522f91 in fcitx::FcitxQtWatcher::watch() ()
    at /usr/lib64/libFcitx5Qt6DBusAddons.so.1
#1  0x00007fffe957511d in ??? ()
    at /usr/lib64/qt6/plugins/platforminputcontexts/libfcitx5platforminputcontextplugin.so
#2  0x00007ffff33d85bb in QObject::event(QEvent*) ()
    at /usr/lib64/libQt6Core.so.6
#3  0x00007ffff4793f81 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib64/libQt6Widgets.so.6
#4  0x00007ffff3379298 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib64/libQt6Core.so.6
#5  0x00007ffff337d08c in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /usr/lib64/libQt6Core.so.6
#6  0x000000000055a7b9 in OBSBasic::ClearSceneData() ()
#7  0x000000000055b06b in OBSBasic::CreateDefaultScene(bool) ()
#8  0x000000000055c2c0 in OBSBasic::Load(char const*) ()
#9  0x000000000057692d in OBSBasic::OBSInit() ()
#10 0x00000000004a5aa3 in OBSApp::OBSInit() ()
#11 0x0000000000480d6d in main ()

```

### Steps to Reproduce

1. Run OBS binary
2. It crashes instantly with a segmentation fault

### Anything else we should know?

Fcitx5 version: 5.1.10
Qt6 version: 6.7.1
Qt5 version: 5.15.13

**Comment by kkartaltepe** [comment]
This doesnt look like an OBS bug based on the stack, you should probably file bugs against Fcitx for not handling its events correctly.

**Comment by autogris** [comment]
Thank you, I will do that.

**Comment by autogris** [comment]
Fcitx5 bug tracker mention a similar error, the problem is a mismatch of unstable versions of Plasma and the shipped fcitx5-qt package. By recompiling the fcitx5-qt the segmentation fault is solved.

**Comment by YellowOnion** [comment]
Is there a work around for this? in the mean time till pkg maintainers fix the issue?

**Comment by autogris** [comment]
> Is there a work around for this? in the mean time till pkg maintainers fix the issue?

You must rebuild fcitx5-qt on your system.
