### ISSUE TITLE
QuickSync not working on Ubuntu 24.04

### ISSUE THREAD

**Issue by lizardpeter** [obsproject/obs-studio#10829]
### Operating System Info

Other

### Other OS

Ubuntu 24.04

### OBS Studio Version

30.2.0-beta1

### OBS Studio Log URL

https://obsproject.com/logs/YUWvjEnHqVlOxuWX

### Expected Behavior

Recording to start.

### Current Behavior

Recording doesn't start.

### Steps to Reproduce

1. Record using QuickSync H264.

**Comment by kkartaltepe** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
