### ISSUE TITLE
Color picker shouldn't be affected by the setting "Hide OBS Windows from screen capture".

### ISSUE THREAD

**Issue by nacalai** [obsproject/obs-studio#10825]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.0-beta1

### OBS Studio Log URL

https://obsproject.com/logs/lOL866F2x8QnTHY2

### Expected Behavior

I would expect color picker to ignore the "Hide OBS Windows from screen capture"-setting, and be able to pick a color from within OBS, since it is the window in focus anyway.

### Current Behavior

It is showing the color of whatever is behind the OBS windows, which doesn't make much sense, as you can't see what is behind it anyway.

### Steps to Reproduce

1. Enable "Hide OBS Windows from screen capture" in settings.
2. Use a color picker
...

**Comment by RytoEX** [comment]
The "Hide OBS Windows from screen capture" is a Windows API function that hides the application from _all_ screen capture methods. This sounds like it's working as intended, and we cannot change it.
