### ISSUE TITLE
"System" main theme sometime disappear.

### ISSUE THREAD

**Issue by SakuraRK** [obsproject/obs-studio#10846]
### Operating System Info

Windows 11

### Other OS

Pro workstation Insider Preview 24H2 26227.5000

### OBS Studio Version

30.2.0-beta3

### OBS Studio Log URL

https://obsproject.com/logs/5B9oMJ9HSbpAV5pF

### Expected Behavior

*System* main theme is can be select.

### Current Behavior

*System* main theme is disappear.

### Steps to Reproduce

1.Select the *setting* and turn to *theme*(*“外观”* In Chinese)
2.Set the *main theme*(*主题* In Chinese) to *Yami*.
3.Change the *type*(*“样式”* In Chinese) one more times.
4.After that, the *System* theme will disappear sometime.

**Comment by SakuraRK** [comment]
![image](https://github.com/obsproject/obs-studio/assets/95642715/4171b0ae-2b09-42ed-9c32-5a41d5f1e5f7)
This is a screenshot about the bug will happen.

**Comment by RytoEX** [comment]
If you mean that the System Theme disappears after choosing a different theme and closing the Settings window, that is intentional. The System theme is intentionally no longer selectable. OBS will change to the System theme if the Operating System is set to a High Contrast theme.

**Comment by SakuraRK** [comment]
thanks

**Comment by RokeJulianLockhart** [comment]
> https://github.com/obsproject/obs-studio/issues/10846#issuecomment-2192713568

@RytoEX, so the "System" theme doesn't exist as an option anymore? If so, may I know why? I ask because OBS Studio looks incredibly inconsistent to the rest of the OS on all new installations now, in stark contrast to all alternative Qt6 applications.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/obsproject/obs-studio/issues/10846#issuecomment-2192713568

@RytoEX, so the "System" theme doesn't exist as an option anymore? If so, may I know why? I ask because OBS Studio looks incredibly inconsistent to the rest of the OS on all new installations now, in stark contrast to all alternative Qt6 applications.

As you can see per https://obsproject.com/forum/threads/theme-system-dark.149202/post-662921, there is desire for system theme adherence.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/obsproject/obs-studio/issues/10846#issuecomment-2424233290

I've filed https://ideas.obsproject.com/posts/2737/re-implement-support-for-the-system-theme to officially request this be re-supported again.

**Comment by weskerty** [comment]
It seems that the only solution is to revert to a previous version.

**Comment by ssalggnikool** [comment]
You can edit a `~/.config/obs-studio/user.ini` file and force this:

```ini
[Appearance]
Theme=com.obsproject.System
```

[source](<https://github.com/obsproject/obs-studio/blob/3bba730f76bcecb1ac88be5740395291ca197a57/frontend/OBSApp_Themes.cpp#L1045>)

(sorry for bumping this, just thought I would mention as it seems like nobody has ever mentioned this online)
