### ISSUE TITLE
macOS screen capture should automatically restart when display becomes available

### ISSUE THREAD

**Issue by crinkytreadmill** [obsproject/obs-studio#10858]
### Operating System Info

macOS 14

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/CIiqPkrhCgJPbRNI

### Expected Behavior

I expected OBS to try and automatically restart the screen capture when the display is turned off and then becomes available once again.

### Current Behavior

OBS never automatically restarts the screen capture. This can only be achieved by manually pressing the `Restart capture` button in the source properties. This is very bothersome in settings where OBS is left unmonitored for extended periods of time, as this behavior is triggered whenever the monitor or computer goes into sleep mode from inactivity.

### Steps to Reproduce

1. Add the `macOS Screen Capture` source
2. Start recording
3. Turn off the monitor for a few seconds
4. Observe that the recording has frozen

**Comment by RytoEX** [comment]
This sounds more likely to be a feature request rather than a bug report, and we are not currently accepting feature requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by ackhia** [comment]
I do feel this is a bug. A user would never expect to have to restart all their capture devices every time their computer sleeps.

**Comment by robert-sarosi** [comment]
yes, this should be considered as a bug. I also lost a recording because the display capture stalled and I wasn't aware of restarting.

**Comment by crinkytreadmill** [comment]
For those interested I've made a feature request for this at https://ideas.obsproject.com/posts/2674

**Comment by linuxiamo** [comment]
> This sounds more likely to be a feature request rather than a bug report, and we are not currently accepting feature requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.
> 
> Thank you!

Wake up. This is a bug...

**Comment by crinkytreadmill** [comment]
As a workaround, I wrote a lua script that simulates a click on the 'Restart capture' button in the source properties once it becomes active, i.e., when the capture freezes.

https://github.com/crinkytreadmill/obs-mac-capture-restarter
