### ISSUE TITLE
New Windows load white

### ISSUE THREAD

**Issue by Michael13435** [obsproject/obs-studio#10868]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.0-beta3

### OBS Studio Log URL

https://obsproject.com/logs/ThhRM6MmOzTJaIXg

### Expected Behavior

Window Opens Black

### Current Behavior

Window opens white

### Steps to Reproduce

1. Close OBS Studio if running
2. Open OBS studio
3. Go to File > Settings
...

**Comment by RytoEX** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
