### ISSUE TITLE
OBS Navbar padding need some improvement, i have fixed it but i don't know how to contribute to UI OBS

### ISSUE THREAD

**Issue by rendi12345678** [obsproject/obs-studio#10865]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

30.2.0-beta3

### OBS Studio Version (Other)

no

### OBS Studio Log URL

no

### OBS Studio Crash Log URL

no

### Expected Behavior

there is more navbar padding
![screenshot-20240616-143122Z-all](https://github.com/obsproject/obs-studio/assets/143745165/609489c6-c447-44a7-bf9b-50660128b7a2)

### Current Behavior

![screenshot-20240616-143033Z-all](https://github.com/obsproject/obs-studio/assets/143745165/99929c7d-3f8a-4d22-9f73-6319c87a8247)
the padding block is so shrink

### Steps to Reproduce

1. i saw it at fist there is no padding in navbar

### Anything else we should know?

please add padding on OBS Navbar website

**Comment by tytan652** [comment]
This issue tracker is for OBS Studio not OBS Project website.

**Comment by Fenrirthviti** [comment]
To clarify, the website itself is not currently open for changes, but it is something we've been working towards. In this instance, I do not believe we are looking for layout changes.

**Comment by rendi12345678** [comment]
okay, thanks for the answer
