### ISSUE TITLE
error when building from source : Could NOT find FFnvcodec: Found unsuitable version "12.2.72.1"

### ISSUE THREAD

**Issue by Hyphaed** [obsproject/obs-studio#10873]
### Operating System Info

Ubuntu 23.10

### OBS Studio Version

Git

### OBS Studio Log URL

building

### Expected Behavior

to build properly

### Current Behavior

CMake Error at /usr/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find FFnvcodec: Found unsuitable version "12.2.72.1", required
  range is "12.0.0.0...<12.2.0.0" (found /usr/local/include)

      Reason given by package: Ensure FFnvcodec headers are available in local include paths.

Call Stack (most recent call first):
  /usr/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:598 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindFFnvcodec.cmake:78 (find_package_handle_standard_args)
  plugins/obs-ffmpeg/cmake/legacy.cmake:119 (find_package)
  cmake/Modules/ObsHelpers.cmake:473 (include)
  plugins/obs-ffmpeg/CMakeLists.txt:3 (legacy_check)

### Steps to Reproduce

use the command

cmake -S . -B YOUR_BUILD_DIRECTORY -G Ninja \
	-DCEF_ROOT_DIR="../obs-build-dependencies/cef_binary_5060_linux_x86_64" \
	-DENABLE_PIPEWIRE=OFF \
	-DENABLE_AJA=0 \
        -DENABLE_WEBRTC=0 \
	-DQT_VERSION=6

**Comment by derrod** [comment]
As the error says, only version 12.0 and 12.1 are supported. If you can't install an older version you can disable native NVENC via `-DENABLE_NATIVE_NVENC=OFF`.

**Comment by Gol-D-Ace** [comment]
Hi
Not sure how you installed the headers but 
`libffmpeg-nvenc-dev` provides them in a suitable version.

This is the package I'm currently using for the beta PPA.

**Comment by fat-tire** [comment]
On ubuntu 22.04, `libffmpeg-nvenc-dev` will be too old and you'll probably need to not use that package but instead clone [this](https://github.com/FFmpeg/nv-codec-headers) with the `-b n12.1.14.0 ` branch, and then `make install` it.  That way you don't have to disable native NVENC via -`DENABLE_NATIVE_NVENC=OFF` and can enjoy the acceleration.
