### ISSUE TITLE
Could not dynamically load CUDA (nvcuda.dll). On a AMD build.

### ISSUE THREAD

**Issue by TimeFlex1** [obsproject/obs-studio#10906]
### Operating System Info

Windows 10

### OBS Studio Version

30.2.0-beta4

### OBS Studio Log URL

https://obsproject.com/logs/FRHAZKTvIxR3LroE

### Expected Behavior

Should notice that Nvidia is not installed and not load CUDA/nvcuda.dll. Or see that AMD is installed and not load CUDA.

### Current Behavior

Will infinitely try to load nvcuda.dll and flood the log file, making the log file size large.

### Steps to Reproduce

1. Open OBS
2. Look at log file
3. Done
...

**Comment by derrod** [comment]
Did that system previously have NVIDIA drivers/GPUs installed?

**Comment by TimeFlex1** [comment]
No its a fresh install of Windows 10
