### ISSUE TITLE
OBS Beta Hybrid MP4 corrupting files when split by size is enabled

### ISSUE THREAD

**Issue by SuperSkypper** [obsproject/obs-studio#10903]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.0-beta4

### OBS Studio Log URL

https://obsproject.com/logs/DSUGKmb5B35qB0Br

### Expected Behavior

Before the beta, I was able to record videos normally and used the split by size feature to divide them into 2GB files. These files could be converted with Handbrake, used for editing in DaVinci Resolve, and worked normally.

### Current Behavior

Now I make a recording, check it, and the 2GB files are separated, but only the first file is not corrupted.

- I can watch all of them with VLC.
- I can't put any of the files from the second cut onwards into Handbrake.
- I can add them to DaVinci Resolve, but only the first few seconds appear, and when rendered, everything goes black.
- Shutter Encoder crashes when I try to do anything with the file in it.

### Steps to Reproduce

1. Turn on Automatic File Splitting - Split By Size (Didn't test others)
2. Record
3. Try to put the file into Handbrake, it will give this warning
![2024-06-21 - 01-58-25  Screenshot](https://github.com/obsproject/obs-studio/assets/64727025/38b23afb-d719-4d71-8b30-809f4e021efb)

### Anything else we should know?

Here's a sample of the recordings: https://drive.google.com/drive/folders/1a_2lusDusgxYeNFS_GkGu_RqmKFe86qZ?usp=sharing

**Comment by WizardCM** [comment]
If you manually remux the files in OBS, do they then work?

**Comment by SuperSkypper** [comment]
@WizardCM Unfortunately not.

**Comment by derrod** [comment]
Recent (7.0) FFmpeg itself in the command line might be fine. It will emit a warning but should still remux it find afaik.

If that doesn't work and the recordings are important and need to be recovered you can manually open the files in a hex editor like HxD (ideally you keep a backup) and then modify these 8 bytes:
![2024-06-21_19-42-00_ReQ2nm](https://github.com/obsproject/obs-studio/assets/3123295/57aeca9f-a038-43d4-b62b-e25cb53c410d)

Replace them with `00 00 00 10 66 72 65 65` (which should show up as `....free` in the text view), this will restore the original fragmented structure of the file, which should then be able to be remuxed normally.
