### ISSUE TITLE
No audio output on Twitch live stream with Enhanced Broadcasting enabled.

### ISSUE THREAD

**Issue by mordang7** [obsproject/obs-studio#10905]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.0-beta4

### OBS Studio Log URL

https://obsproject.com/logs/ZK66RwRQyaowunCW

### Expected Behavior

Sound should output on live stream.

### Current Behavior

Sound is not outputting while live streaming on Twitch.

### Steps to Reproduce

1. Tick "Enable Enhanced Broadcasting"
2. Click on Start Streaming button.
3. Even though all Audio seems to working on the Audio Mixer Panel, there is no audio on the live stream.
...

### Anything else we should know?

Don't know if this is relevant but my GPU is an AMD RX 6800XT.

**Comment by derrod** [comment]
There's an off-by-one error that will result in the wrong audi otrack being used (i.e. if you have selected 1 it will use 2 and so on), this was fixed in 5f98d34e2c4d81a43eafd3d87ae65e67a3d04e06 but has not shipped yet.

**Comment by WizardCM** [comment]
There's also https://github.com/obsproject/obs-studio/commit/fb3e571ce8592c080f9a9d346c76e361b96bb531 which can cause this.
