### ISSUE TITLE
Hardware H264 encoding broken on RX 590

### ISSUE THREAD

**Issue by therealmate** [obsproject/obs-studio#10914]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.0-beta4

### OBS Studio Log URL

https://obsproject.com/logs/hlDCtmCuHqzi7n23

### Expected Behavior

Recording works normally without encoding overload

### Current Behavior

encoding overload after 3 seconds

### Steps to Reproduce

1. Start a recording with default settings on RX 590
2.
3.
...

### Anything else we should know?

-AMD driver version is 24.3.1
-This is a regression as it worked before
-From my bisecting, it seems that https://github.com/obsproject/obs-studio/commit/572407a928905e209c19beae545006f3f957f792 is the bad commit
-video of the issue: https://github.com/obsproject/obs-studio/assets/61843503/04e2aa8d-08ea-40a9-ac2b-8fe5a9b92ba8

**Comment by prgmitchell** [comment]
@therealmate this seems more likely to be a support issue, the newer AMD encoder requires you use the "speed" preset with that card. I'd recommend visiting the [community discord](https://discord.com/invite/obsproject) or [forums](https://obsproject.com/forum/) for support.
