### ISSUE TITLE
OBS uses the microphone "permission" even when microphone capture is disabled

### ISSUE THREAD

**Issue by Tiagoquix** [obsproject/obs-studio#10913]
### Operating System Info

Other

### Other OS

Fedora Linux 40 KDE

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.1.1

### OBS Studio Log URL

https://obsproject.com/logs/wcUeSs7fb7YanGBH

### Expected Behavior

![image](https://github.com/obsproject/obs-studio/assets/30274161/7561794f-c1e3-4d19-85af-aa69f324cc60)

When microphone audio is disabled from audio capture, OBS should not require microphone "permission" from the OS. In this case, I'm using KDE Plasma and it tells me OBS is using the microphone, even though it's disabled in OBS settings.

![image](https://github.com/obsproject/obs-studio/assets/30274161/53a88676-289b-4a59-b0bf-9ffcd0b20f22)

### Current Behavior

OBS requires the microphone "permission" from the OS even though it is not being used. As I understand it, it seems like OBS is doing streamlined microphone access to avoid possible lag if it had to request "permission" everytime.

I'm using the word "permission" inside quotes because KDE Plasma, the desktop environment, does not have a permission system for the microphone. However, I believe this issue also applies to Windows 10 and 11, which have the permission system.

### Steps to Reproduce

Explained above.

### Anything else we should know?

A possible way to fix this behavior would be to add an option such as "Streamlined microphone usage" or something like it that keeps current behavior and it's enabled by default, but that could be disabled for users that desire it.

**Comment by WizardCM** [comment]
Per your log file, OBS is still set with a Desktop Audio Device. I have a strong suspicion this is what KDE Plasma is incorrectly assuming is a "microphone".

```
02:13:15.877: pulse-input: Server name: 'PulseAudio (on PipeWire 1.0.7) 15.0.0'
02:13:15.878: pulse-input: Audio format: s16le, 48000 Hz, 2 channels
02:13:15.878: pulse-input: Started recording from 'alsa_output.usb-HP__Inc_HyperX_Virtual_Surround_Sound_00000000-00.analog-stereo.monitor'
```
