### ISSUE TITLE
Start streaming freezes on beta.

### ISSUE THREAD

**Issue by Penwy** [obsproject/obs-studio#10929]
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

30.2.0-beta4

### OBS Studio Log URL

https://obsproject.com/logs/YuJnDwiIyZlg7um6

### Expected Behavior

Pressing "Start Stream" should start the stream.

### Current Behavior

Pressing "Start Stream" fully freezes obs.

### Steps to Reproduce

1. Open non-flatpak obs on ubuntu 22.04
2. Press "Start Stream"
...

### Anything else we should know?

Flatpak works correctly, only deb and self-compile have the issue.
Bisect pointed to c8950900c36fd6d0bd014eb6fd24da829a63033d as the culprit.
[Backtrace](https://github.com/user-attachments/files/16014293/message.txt) pointed to [this](https://github.com/obsproject/obs-studio/blob/c8950900c36fd6d0bd014eb6fd24da829a63033d/UI/window-basic-main-outputs.cpp#L1143) as the very likely issue.

**Comment by RytoEX** [comment]
Given that it doesn't happen in Flatpak (Qt 6.6.x) but does happen in presumably the PPA version (Qt 6.2.4), this may just be an unfixed Qt Futures bug in older Qt versions. It would be good to determine if there's a version of Qt where this does _not_ happen so we can scope out what a possible fix might be.

**Comment by RytoEX** [comment]
Off-thread testing indicates that this is not a problem with builds on Ubuntu 23.10 with Qt 6.4.2.

**Comment by RytoEX** [comment]
This is possibly one of these:
* https://bugreports.qt.io/browse/QTBUG-105182
* https://bugreports.qt.io/browse/QTBUG-106083

which are the same core bug, and only fixed in 6.2.7, 6.4.1, and 6.5+. Since Ubuntu 22.04 is frozen on 6.2.4, we can't expect it to be fixed on Ubuntu 22.04 with a Qt update. We probably need to implement a code path to Start Streaming that either:
a) avoids this specific behavior
b) does not use QFuture at all

**Comment by palana** [comment]
> This is possibly one of these:
> 
> * https://bugreports.qt.io/browse/QTBUG-105182
> * https://bugreports.qt.io/browse/QTBUG-106083
> 
> which are the same core bug, and only fixed in 6.2.7, 6.4.1, and 6.5+. Since Ubuntu 22.04 is frozen on 6.2.4, we can't expect it to be fixed on Ubuntu 22.04 with a Qt update. We probably need to implement a code path to Start Streaming that either:
> a) avoids this specific behavior
> b) does not use QFuture at all

I'd probably go with completely disabling the multitrack video output on affected qt versions (a)

manually unrolling/hooking up the code to signals/slots is generally somewhat tedious and feels like somewhat of a maintenance hazard
