### ISSUE TITLE
Quality CQP now working in 30.2.0

### ISSUE THREAD

**Issue by marvin1099** [obsproject/obs-studio#10922]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

30.2.0-beta4

### OBS Studio Log URL

https://obsproject.com/logs/pZw6kleDujHbpG43

### Expected Behavior

When recording using the cqp option in the `NVIDIA NVENC HEVC` the quality should be high enough to not have any artifacts visible to the eye.

### Current Behavior

The poor quality is clearly visible, here the small video recorded with cqp 22:
https://github.com/obsproject/obs-studio/assets/40715852/c15c159e-3bf7-4a0b-8dd2-d9a3eed4fbc4

### Steps to Reproduce

1. Set endcoder to `NVIDIA NVENC HEVC`
2. Set rate control to `cqp`
3. Start a recording

### Anything else we should know?

I think it will always results in poor quality no mater what value is entered for cqp
Edit: It seems a lower cqp value still makes the quality go higher,  
but the expected good quality is way higher than using -qp,  
not sure if this i intended i always used qp 22 but in obs it seems it needs to be lower

**Comment by flaeri** [comment]
I've analyzed the video file you uploaded. It is in fact CQP 22. The smooth scrolling background has some visible macroblocking, and I assume that is what you're referring to. Unfortunately, that is expected with 8bit limited range, smooth gradients.

OBS and the NVENC encoder is doing is functioning as requested (settings are respected), so I don't think this could be considered a bug.

**Comment by marvin1099** [comment]
> I've analyzed the video file you uploaded. It is in fact CQP 22. The smooth scrolling background has some visible macroblocking, and I assume that is what you're referring to. Unfortunately, that is expected with 8bit limited range, smooth gradients.
> 
> OBS and the NVENC encoder is doing is functioning as requested (settings are respected), so I don't think this could be considered a bug.

Ok strange since in other recording ways this problem did not appear on -qp 22

**Comment by marvin1099** [comment]
Maby it was my mistake after all the problem seems to appear on custom ffmpeg output `-qp 22` too, could have sworn it worked, hmm.
O well i guess i have to go lower then 22 in that case thanks anyway.
