### ISSUE TITLE
Quality CQP now working

### ISSUE THREAD

**Issue by marvin1099** [obsproject/obs-studio#10921]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/Zk1R4QBzBPIz0oo7

### Expected Behavior

obs should use -qp and not `global_quality `

### Current Behavior

obs uses `global_quality`

### Steps to Reproduce

1. Set recording encoder to `NVIDEA NVENC HEVC (ffmpeg)`
2. Set rate control  to cqp
3. Start a recording

### Anything else we should know?

The video recorded from the setting using cqp will have very crappy quality, therefore the quality setting cqp is not working.

The error is printed in the console, it's not in the log, so here the error: 
`[hevc_nvenc @ 0x5c32aecc0340] Using global_quality with nvenc is deprecated. Use qp instead.`

Please add the option to set custom video parameters, this wold give more control, 
the custom ffmpeg option , does not support things like pausing so its not a good option.

**Comment by derrod** [comment]
With 30.2 there is a native NVENC implementation on Linux. The FFmpeg version is deprecated and will be removed once we stop supporting Ubuntu 22.04.
