### ISSUE TITLE
Unable to install virtual camera in Sequoia Beta

### ISSUE THREAD

**Issue by Mantene** [obsproject/obs-studio#10939]
### Operating System Info

Other

### Other OS

MacOS 15 Developer Beta 2

### OBS Studio Version

30.2.0-rc1

### OBS Studio Log URL

https://obsproject.com/logs/QRyMcL8YmDA9vNXm

### Expected Behavior

I expect something to pop up in the Security and Privacy portion of the Mac control panel asking me to allow OBS to install the virtual camera.

### Current Behavior

Nothing. I get the OBS pop-up alerting me to go and allow it to install the camera, but the Security&Privacy panel does not have any such prompt.
<img width="1394" alt="Screenshot 2024-07-01 at 3 32 21 PM" src="https://github.com/obsproject/obs-studio/assets/2818812/71ba49dc-ddae-4816-816a-0a06b0bea705">

### Steps to Reproduce

1. Open OBS
2. Click "Start Virtual Camera" for the first time.
3. Frustration
...

### Anything else we should know?

I mean, this is a beta OS I am running it on. I don't expect every piece of software to work. I just thought I would give you a heads-up as to the current behavior of OBS in this beta OS.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by tech-andgar** [comment]
Unless the beta changes before general release, the instructions for MacOS 15+ would be something like:
1. When opening OBS for the first time, you will get a prompt "System Extension Blocked". Open **System Settings** → **General** → **Login Items & Extensions** → click the information "i" icon by **Camera Extensions**.
![2024-09-16_11-06](https://github.com/user-attachments/assets/6d24ed60-b308-447b-b1d7-662fd7a45dc1)

2. In the "OBS" box, click the switch/slider to the right to enable the extension.

![2024-09-16_11-07](https://github.com/user-attachments/assets/01ea8cbb-678e-4261-9631-50c48c394a11)



3. Authenticate to allow the system extension.
4. Restart OBS.
