### ISSUE TITLE
Cannot record on OBS studio with VAAPI running with Main10 profile

### ISSUE THREAD

**Issue by hueychen27** [obsproject/obs-studio#10945]
### Operating System Info

Other

### Other OS

Debian

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.1.2.1-1+b2

### OBS Studio Log URL

https://obsproject.com/logs/iOC351pXJIkit9nj

### Expected Behavior

I expected recording to work normally.

### Current Behavior

This error message appears:
```
Starting the output failed. Please check the log for details.

Note: If you are using the NVENC or AMD encoders, make sure your video drivers are up to date.
```

### Steps to Reproduce

1. Use "FFmpeg VAAPI HEVC" for video encoder
2. Set profile to "Main10" in Output>recordings tab.
3. Start recording and witness error

### Anything else we should know?

I did a simple test where I used the "main" and "main10" profile. The "main" profile reported no error and was fine. The other one reported the error.

**Comment by kkartaltepe** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

**Comment by hueychen27** [comment]
Sorry, I did not know that.

**Comment by hueychen27** [comment]
@kkartaltepe I am banned from forums because of my email.

**Comment by hueychen27** [comment]
All outlook.com emails are banned apparently.

**Comment by Fenrirthviti** [comment]
Correct, because the outlook.com domain is 99% spam these days. Use a different email address, or our Discord instead.

**Comment by hueychen27** [comment]
Alright
