### ISSUE TITLE
HEVC VAAPI On Radeon RX 6800 Adds 5 Rows of Green Pixels At Bottom Of Video 

### ISSUE THREAD

**Issue by HurricanePootis** [obsproject/obs-studio#10953]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/ABgnSKQi1LZ71TVl

### Expected Behavior

For the HEVC VAAPI to not have 5 rows of green pixels at the bottom

### Current Behavior

Whenever I record with HEVC VAAPI on my Radeon RX 6800 at 1900x1080p, the video ends up being 1905x1080p, with the 5 extra rows pixels being green at the bottom of the video.

### Steps to Reproduce

1. Install obs-studio
2. Use VAAPI HEVC, recording to an mkv file
3. Record
...

### Anything else we should know?

I have the same software setup on my Ryzen 5 5625U (Vega based graphics) Laptop, and the bug does not occur there.

**Comment by tytan652** [comment]
This is a Mesa bug.

**Comment by HurricanePootis** [comment]
@tytan652 Is there already an upstream issue for Mesa?
