### ISSUE TITLE
OBS Freezes on Wayland with Pipewire

### ISSUE THREAD

**Issue by nnra6864** [obsproject/obs-studio#10959]
### Operating System Info

Other

### Other OS

Arch

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.1.2-2

### OBS Studio Log URL

https://obsproject.com/logs/fNO4oOj2Ern3YRXF

### Expected Behavior

Expected behaviour is for screen capture to actually update, not stay frozen on the first frame.

### Current Behavior

It just freezes as soon as I select what to capture with pipewire.

### Steps to Reproduce

1. open obs
2. select the output with pipewire
3. freeze
...

### Anything else we should know?

Interesting thing is that it starts working again when I disable and enable the capture.
It also works if I am screensharing on vesktop, start the obs and select the output.
Here's the video I made showcasing the bug:
https://youtu.be/xQUKy5_UHr0

**Comment by tytan652** [comment]
The issue is likely on the portal side, https://github.com/hyprwm/xdg-desktop-portal-hyprland.

**Comment by Different-Name** [comment]
This issue is resolved for me by hiding and showing the source in OBS

**Comment by nnra6864** [comment]
> This issue is resolved for me by hiding and showing the source in OBS

Same, I am pretty sure I showed it in the video.

**Comment by Different-Name** [comment]
> Same, I am pretty sure I showed it in the video.

My bad, I missed that - did you end up making an issue on [xdg-desktop-portal-hyprland](https://github.com/hyprwm/xdg-desktop-portal-hyprland)? I couldn't find one

Or better yet, find a workaround?

**Comment by nnra6864** [comment]
> > Same, I am pretty sure I showed it in the video.
> 
> My bad, I missed that - did you end up making an issue on [xdg-desktop-portal-hyprland](https://github.com/hyprwm/xdg-desktop-portal-hyprland)? I couldn't find one
> 
> Or better yet, find a workaround?

I didn't.
You can do it if you'd like to, feel free to attach the vid I sent if you want.

**Comment by Different-Name** [comment]
https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/239
