### ISSUE TITLE
[Bug] Incorrect Aspect Ratio for the 1366x768 resolution in Video Settings

### ISSUE THREAD

**Issue by mycpphurts** [obsproject/obs-studio#10950]
### Operating System Info

Other

### Other OS

Archlinux 6.9.7-arch1-1

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.1.2-2

### OBS Studio Log URL

https://obsproject.com/logs/Tne4cyeWj8BsCzvU

### Expected Behavior

Using the 1366x768 should return that the aspect ratio is 16:9

### Current Behavior

Using the 1366x768 resolution displays that the aspect ratio is 683:384
![Shot-2024-07-05-103254](https://github.com/obsproject/obs-studio/assets/57727007/00a80dbf-4e61-40ad-aa5d-edcbf10341c4)

### Steps to Reproduce

1. Open OBS from the latest package version
2. Head to Settings > Video > Set resolution to 1366x768 on either Base Resolution or Output Resolution

### Anything else we should know?

Reading the code I'm sure the incorrect aspect ratio happens because of the simplification of the ratios using GCD. Which for 16:10 ratios and 1366x768 will fail. While for the 16:10 aspect ratio, this issue has been fixed as shown in the codeblock below for the 16:10 resolutions with a special case handler for what GCD actually returns for 16:10 resolutions (8:5). OBS will display 683:384 for 1366x768 because 683 is a prime number, while the resolution is almost 16:9 to GCD since it calculates to 16.0078125.

https://github.com/obsproject/obs-studio/blob/8c71b0b586a0b0a21fb6de9113c57de168d28668/UI/window-basic-settings.cpp#L298-L310

This issue can also happen to the following resolutions:
- 2560 x 1080
- 3440 x 1440
- 3840 x 1600

**Comment by derrod** [comment]
Well it's technically not 16:9. So this isn't a bug, it's just a stupid resolution.

**Comment by mycpphurts** [comment]
> Well it's technically not 16:9. So this isn't a bug, it's just a stupid resolution.

While the SAR for it is indeed 683:384, the DAR is 16:9 for the resolution is. There's a patch already in the code for 16:10 since their DAR and SAR are both 8:5.

Is the SAR more suitable for OBS or is the DAR..?

**Comment by derrod** [comment]
OBS doesn't support non-square pixels. The special case for 16:10 only exists because that's the more commonly used term in spec sheets compared to 8:5.

**Comment by mycpphurts** [comment]
How about 21:9 for ultrawide monitors? Resolutions such as 3440x1440 which should display 21:9 as its aspect ratio but in OBS its resolution is set to 43:18 because of GCD, when the resolution itself is 1:1 when it comes to being 21:9.

**Comment by WizardCM** [comment]
As a 21:9 owner, I can safely say 3440x1440 is not exactly 21:9, the existing calculation is technically correct on that front.

**Comment by mycpphurts** [comment]
Did some math on it, you stand correct, a true 21:9 aspect ratio of your monitor would be 3440x1474.29 if my math is correct
