### ISSUE TITLE
OBS records black screen using "screen" capture when running minecraft in fullscreen

### ISSUE THREAD

**Issue by D4n2021** [obsproject/obs-studio#10968]
### Operating System Info

Windows 10

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/YenMaO007BKs3rJo

### Expected Behavior

Should record the game in **screen** capture mode while running the game in fullscreen

### Current Behavior

OBS records black screen

### Steps to Reproduce

Simply set OBS to screenrecording, launch minecraft, select fullscreen in minecraft

### Anything else we should know?

This article proves that it isn't working in "screen" recording currently: https://obsproject.com/kb/minecraft-java-edition-troubleshooting

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by TOWUK** [comment]
disable optimization on display > graphics!!!! i have this problem too and my fix is:
![image](https://github.com/user-attachments/assets/26e7ad86-7579-4640-9141-49fe6289efc3)
