### ISSUE TITLE
OBS is crashing with RX 580

### ISSUE THREAD

**Issue by PatrickCreations** [obsproject/obs-studio#10969]
### Operating System Info

Windows 10

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://patrickcreations.altervista.org/2024-07-12%2010-58-01.txt

### Expected Behavior

I did expect OBS to open as it usually does, whilst Unity was opening in the background.

### Current Behavior

The moment OBS started, the computer freezed, AMD's software did reset the driver settings and Unity crashed.

### Steps to Reproduce

1. Having AMD software 24.3.1 since it's the latest version of AMD's software for the RX 580
2. I am not sure if either a Game or Unity need to be open
3. Open OBS studio

### Anything else we should know?

The issue has been showing up recently, so I suppose it's due to the AMD software updates but it could also be due to the OBS ones.

**Comment by WizardCM** [comment]
This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels below, and if it's determined that this is indeed a bug, then we will re-open this issue.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
