### ISSUE TITLE
Crash when trying to create projector on Fedora 40 (Wayland)

### ISSUE THREAD

**Issue by NanoDrivee** [obsproject/obs-studio#10986]
### Operating System Info

Other

### Other OS

Fedora 40

### OBS Studio Version

30.2.0

### OBS Studio Version (Other)

30.2.0 Flatpak

### OBS Studio Log URL

https://obsproject.com/logs/Ys4xZ9e8AC1kwLOs

### Expected Behavior

New window created with desired source

### Current Behavior

OBS window closed

### Steps to Reproduce

1. `flatpak run com.obsproject.Studio`
2. Right click desired source or the background of the preview window
3. Select Windowed Projector/Fullscreen Projector option
4. Crash occurs
...

### Anything else we should know?

Someone else described an issue where opening the settings menu results in a freeze, I don't experience [that issue](https://github.com/obsproject/obs-studio/issues/10752) but I followed how to use gdb there and I'll upload my gdb log here too.

[gdb.txt](https://github.com/user-attachments/files/16228459/gdb.txt)

**Comment by kkartaltepe** [comment]
Wayland protocol errors are a problem with your drivers or qt, Id suggest you raise the issue on their trackers.
