### ISSUE TITLE
30.2 WebSocket VirtualCam commands are reporting VirtualCam is not available

### ISSUE THREAD

**Issue by digitaldrummerj** [obsproject/obs-studio#10983]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.0

### OBS Studio Log URL

https://obsproject.com/logs/r1Hx1Hd3P9rbbQUX

### Expected Behavior

When using the WebSocket, the following commands should for the VirtualCam should allow you to get the virtual cam status, turn on, turn off or toggle status as they did in previous version of OBS.

- GetVirtualCamStatus
- ToggleVirtualCam
- StartVirtualCam
- StopVirtualCam

### Current Behavior

The websocket is returning "VirtualCam is not available" .  I can manually turn on/off the virtual cam and it is showing up as expected in other programs.  It is just the websocket that is not seeing the virtualcam

### Steps to Reproduce

1. Install 30.2.0
2. Enable WebSocket Server
3. Go to https://obs-raw.streamer.bot/#GetVirtualCamStatus 
4. Connect to your OBS websocket (you might have to add the password to connect)
5. Click on Send Request button
6. The Response will be "Error: VirtualCam is not available."

If you run steps 2-6 using OBS 30.1.2 it returns the VirtualCam status and the other VirtualCam commands work as expected.
...

### Anything else we should know?

I also verified it was an OBS 30.2 issue on my machine by re-installed OBS 30.1.2 over the top of OBS 30.2 and seeing the command work with 30.1.2 and then upgrading again to 30.2 and the commands failed.it

**Comment by instinctualjealousy** [comment]
Can confirm the error in my own scripting and that it only started with this new build.

**Comment by RytoEX** [comment]
This was fixed by https://github.com/obsproject/obs-studio/commit/c5a01b7df4471a44154363a0699b30b8ade86032.
