### ISSUE TITLE
OBS 30.2.0 flatpak, custom plugins fail to load

### ISSUE THREAD

**Issue by lefty82** [obsproject/obs-studio#10981]
### Operating System Info

Other

### Other OS

arch linux

### OBS Studio Version

30.2.0

### OBS Studio Log URL

https://obsproject.com/logs/Oy4q2U9ul0NgE87P

### Expected Behavior

Custom plugins should be able to load. The native arch linux package works fine, but not the flatpak.

### Current Behavior

Custom plugins fail to load. This was also tested on a debian virtual machine with the flatpak version, same error.

### Steps to Reproduce

1. Install a custom plugin, you can use "com.obsproject.Studio.Plugin.OBSVkCapture" from flathub to test it
2. Check the current log if it has loaded.
3.
...

**Comment by Penwy** [comment]
Can duplicate on ubuntu 22.04
Any plugin installed via flathub doesn't even log an attempt to load.
Plugins installed by copying in the plugins config folder fail to load with :
```os_dlopen(/app/plugins/lib/obs-plugins/linux-vkcapture.so->/app/plugins/lib/obs-plugins/linux-vkcapture.so): libobs.so.0: cannot open shared object file: No such file or directory ```

**Comment by lefty82** [comment]
Flatpaks load manually installed plugins from `$HOME/.var/app/com.obsproject.Studio/config/obs-studio/plugins/`

Those fail as well

**Comment by tytan652** [comment]
Just to set the scope of the issue:
- Plugins manually installed (copy-paste in the config folder) are not supported in the Flatpak and never was.
- "Flatpak extension can't be loaded since 30.2" is the scope of the issue

**Comment by tytan652** [comment]
The easiest solution, would be to have every extension re-built against the latest Flathub.

I asked Flathub, I'll see how it is going.

**Comment by lefty82** [comment]
That leaves the issue with extensions that are not through FP, and just dropped in `$HOME/.var/app/com.obsproject.Studio/config/obs-studio/plugins/`

I guess it will be up to the individual devs for those

**Comment by tytan652** [comment]
They accepted to start re-build of plugins, in +3 hours most of the re-built plugins will be pushed to Flathub.

If a plugin is not re-built (in the next 24 hours), please open an issue on it's Flathub manifest repo.

**Comment by tytan652** [comment]
> That leaves the issue with extensions that are not through FP, and just dropped in `$HOME/.var/app/com.obsproject.Studio/config/obs-studio/plugins/`
> 
> I guess it will be up to the individual devs for those

Like said we don't support this, for the Flatpak we only support Flatpak extensions.

**Comment by jaedolph** [comment]
Also having this issue, the OBSVkcapture plugin is not working for me (installed via the flatpak)

**Comment by Gamertech** [comment]
Unfortunately, 27 hours later and none of the extensions appear to have been modified.

Rolled back for now, but has anyone got more info on what's being done atm?

**Comment by joaojotta** [comment]
> Unfortunately, 27 hours later and none of the extensions appear to have been modified.
> 
> Rolled back for now, but has anyone got more info on what's being done atm?

I'm having the same issue. None of the plugins are loading. Tried to rollback but I OBS wouldn't open after that.

**Comment by tytan652** [comment]
Re-build have be been normally publish unless the build failed or the plugin did not keep up with KDE Sdk updates.

If a plugin is not re-built (does not work), please open an issue on the Flathub manifest repo.

**Comment by joaojotta** [comment]
It worked last night (the plugins) before the update. Rebuilding OBS didn't fix it.
Let's hope for a new version soon. 👍

*João Jotta*
*formador*
*t *934 659 666[tel:+351934659666]
***@***.***
*w *joaojotta.com[https://joaojotta.com]

15 Jul 2024 19:38:54 tytan652 ***@***.***>:

**Comment by rmnvgr** [comment]
Hello,

I help maintain the [Waveform Flatpak plugin](https://github.com/flathub/com.obsproject.Studio.Plugin.waveform), and, from what I can see, no rebuild has been triggered for it: https://buildbot.flathub.org/#/apps/com.obsproject.Studio.Plugin.waveform

I tried to manually build it and update it to the latest KDE SDK, but the build fails because it's not finding an OBS symbol:

```
-- The C compiler identification is GNU 13.2.0
-- The CXX compiler identification is GNU 13.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /run/ccache/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /run/ccache/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
CMake Deprecation Warning at deps/cpu_features/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for getauxval
-- Looking for getauxval - found
-- Looking for obs_properties_add_color_alpha
CMake Error in /run/build/waveform/CMakeFiles/CMakeScratch/TryCompile-qP7bFG/CMakeLists.txt:
  No known features for CXX compiler

  ""

  version .


CMake Error at /usr/share/cmake-3.29/Modules/CheckSymbolExists.cmake:140 (try_compile):
  Failed to generate test project build system.
Call Stack (most recent call first):
  /usr/share/cmake-3.29/Modules/CheckSymbolExists.cmake:66 (__CHECK_SYMBOL_EXISTS_IMPL)
  CMakeLists.txt:228 (check_symbol_exists)


-- Configuring incomplete, errors occurred!
```

Please let me know if you have any idea on how to resolve this.

**Comment by tytan652** [comment]
@rmnvgr, outdated SDK, for the build error this is an issue with upstream plugin CMake from what I see.

Issues are not meant for support. So for maintainers, for further assistance either the OBS Comnunity Discord or the Flathub Matrix.
