### ISSUE TITLE
"--disable-web-security" CEF flag not passed correctly to obs-browser-page.exe

### ISSUE THREAD

**Issue by dawn-lc** [obsproject/obs-studio#10985]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.0

### OBS Studio Log URL

https://obsproject.com/logs/zV4WtnIIVRZxIkAY

### Expected Behavior

obs-browser-page.exe should be launched with the "--disable-web-security" CEF flag

### Current Behavior

obs-browser-page.exe is launched without the "--disable-web-security" CEF flag

### Steps to Reproduce

1.Add "--disable-web-security" CEF flag to the shortcut
2.Launch OBS using the modified shortcut
...

### Anything else we should know?

![image](https://github.com/user-attachments/assets/1d94ad94-56dc-4feb-9875-b931622709cc)

![image](https://github.com/user-attachments/assets/e46333da-17b8-4ded-a84c-a381437d0182)

**Comment by WizardCM** [comment]
> This switch has no effect unless `--user-data-dir` (as defined by the content embedder) is also present.

This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels below, and if it's determined that this is indeed a bug, then we will re-open this issue.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
