### ISSUE TITLE
NVENC disappeared in OBS 

### ISSUE THREAD

**Issue by jose-rafael** [obsproject/obs-studio#10984]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

30.2.0

### OBS Studio Log URL

https://obsproject.com/logs/3iuGQavd2lbqpJdp

### Expected Behavior

Video Encoder Options, NVENC option to use Nvidia encoder appears

### Current Behavior

All Nvidia-related features are gone

### Steps to Reproduce

1.Settings 
2.Output 
3.Output Mode -> Advanced 
4. Video Encoder -> (Nvenc)

### Anything else we should know?

I have an Nvidia GT470M, and it supports NVENC and NVDEC because until the last version it was working on OBS

**Comment by RytoEX** [comment]
Did you mean 740M? The GT470M is Fermi GPU which shouldn't have NVENC.

Your OBS log does not show OBS loading on an NVIDIA GPU.

**Comment by jose-rafael** [comment]
Sorry, it's the GT740M, and because it's M it's an old hybrid gpu, so it doesn't appear in the logs that it went up via nvidia, but it has nvidia installed and I use acceleration to watch videos with mpv, and obs to record but it no longer has nvenc in OBS 

how do I get a log from an old version if I've already updated?
![image](https://github.com/user-attachments/assets/5f53e73c-e179-4b8d-af1b-80cf423eb346)

**Comment by jose-rafael** [comment]
I found it, I'll post the screenshot of the previous version and the link as you requested

https://obsproject.com/logs/SJJzEY6rggNmCnRd

![image](https://github.com/user-attachments/assets/73204c88-1d1e-4231-835b-4f0f3e957c42)

**Comment by RytoEX** [comment]
> I found it, I'll post the screenshot of the previous version and the link as you requested
> 
> https://obsproject.com/logs/SJJzEY6rggNmCnRd

There is no recording/streaming session in that log. As far as I know, NVENC would also fail on the GT 740M due to a driver version check due to the nv-codec-headers version used in OBS Studio 30.1. Please provide a log where you successfully used NVENC in a previous version of OBS.

**Comment by jose-rafael** [comment]
https://obsproject.com/logs/MsyoPKJOc5FJasii


https://github.com/user-attachments/assets/83608328-e8d5-4461-ac2e-0ce6a9b1e76e

**Comment by RytoEX** [comment]
You are using a third-party plugin to record rather than using the encoders shipped with OBS. Please report this to the plugin maintainer.

**Comment by Eyion** [comment]
What's happening? What can I do to solve this problem? 
![image](https://github.com/user-attachments/assets/b292d779-d0b1-4e3e-8573-cb7f25e4f8e6)
