### ISSUE TITLE
OBS Studio not outputting any visuals using pipewire

### ISSUE THREAD

**Issue by thndgonz** [obsproject/obs-studio#10995]
### Operating System Info

Other

### Other OS

KDE Neon

### OBS Studio Version

30.2.0

### OBS Studio Log URL

https://obsproject.com/logs/dqirGrL9csoSkj2C

### Expected Behavior

Windows or Screens captured through pipewire works

### Current Behavior

It opens up the screen/window selector but when you press OK OBS Studio doesn't really use the feed (window/screen) that's supposed to be the output. 
Only noticeable thing is Error retrieving pipewire fd: GDBus.Error:org.freedesktop.DBus.Error.NoReply

### Steps to Reproduce

1. Update KDE Neon to the latest
2. Use OBS repo or flatpak (any of them will fail either way)
3. Add a pipewire screen or window. 
4. Select the screen/window you want
5. Notice that while Screen casting is shown as active by KDE nothing really shows in OBS Studio

**Comment by tytan652** [comment]
Report to KDE Neon, it's a distro issue not OBS Studio's.
