### ISSUE TITLE
Video Capture Device (PipeWire) only has YUYV422

### ISSUE THREAD

**Issue by theofficialgman** [obsproject/obs-studio#10994]
### Operating System Info

Other

### Other OS

Ubuntu 24.04

### OBS Studio Version

30.2.0

### OBS Studio Log URL

https://obsproject.com/logs/QZ6nw3EjuvvMRPNI

### Expected Behavior

I expect Video Capture Device (PipeWire) to have the same video format, framerate, and resolution options as the Video Capture Device (V4L2)

### Current Behavior

Video Capture Device (PipeWire) only has YUYV422 option, resulting in the camera unable to output in full resolution and framerate combinations (eg: max of 1920x1080 at 5fps)

### Steps to Reproduce

1. Using Framework 13 AMD (webcam module 1st gen)
2. Select Video Capture Device (PipeWire) 
3. Accept the prompt to share webcam
4. Select the device Laptop Camera V4L2
5. See the resolution and framerate combinations are severely limited due to only YUYV422 being available

### Anything else we should know?

Video Capture Device (V4L2) has the same limitations on YUYV422 but that is not the default input format (which is Motion JPEG). Motion JPEG has more resolution/framerate combinations available (such as 1920x1080 at 60fps)

**Comment by derrod** [comment]
Per https://github.com/obsproject/obs-studio/pull/9771#issuecomment-1858987828 support for MJPEG/H.264 was deferred until later. Unfortunately @GeorgesStavracas has been very busy so this hasn't happened yet.

**Comment by tytan652** [comment]
As above and stated in the linked issue, this is not a bug.

This then sounds more likely to be a feature request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [Fider](https://ideas.obsproject.com/) or [Discord](https://obsproject.com/discord/).
