### ISSUE TITLE
IOS Input (OBS iPhone APP) connection is gone after upgrade

### ISSUE THREAD

**Issue by tarekmaalouf** [obsproject/obs-studio#10991]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.0

### OBS Studio Log URL

https://obsproject.com/logs/VzBUSXKqQ5mmYTHy

### Expected Behavior

Normally we would have this ios camera appear without issue. It is gone now , the option is no longer listed, and while the IOS camera source appears in our sources list, it does not have options for properties etc. We cannot add a new iOS Camera 

### Current Behavior

the ios is not functioning at all and the option to add this as a source is gone. 

### Steps to Reproduce

Just go to sources and you will see it is no longer there.

### Anything else we should know?

I attempted to add the plug-in manually as well and this did not work.

**Comment by prgmitchell** [comment]
@tarekmaalouf hello, this would be an issue for the plugin developer to address. Looking at their github page, you can see many have already filed issues. https://github.com/wtsnz/obs-ios-camera-source/issues

**Comment by tarekmaalouf** [comment]
Very sorry. Thank you for the help and input.
