### ISSUE TITLE
Native/default browser should be used for OAuth2 authorization

### ISSUE THREAD

**Issue by SReject** [obsproject/obs-studio#11007]
### Operating System Info

Windows 10

### OBS Studio Version

30.2.0

### OBS Studio Log URL

https://obsproject.com/logs/nCO3llJg1ACRTsRi

### Expected Behavior

OBS should use my default web browser to perform OAuth authorization requests as per the [OAuth2 Best Practices RFC](https://datatracker.ietf.org/doc/html/rfc8252#page-4)

> For authorizing users in native apps, the best current practice is to perform the OAuth authorization request in an external user-agent (typically the browser) rather than an embedded user-agent (such as one implemented with web-views).

### Current Behavior

OBS uses an inbuilt web-view to facilitate authorization

### Steps to Reproduce

1. Navigate to File -> Settings -> Stream
2. Under Destination, select 'Auto (Recommended)'
3. Click 'Connect Account'

Obs Opens a webview

**Comment by gxalpha** [comment]
This sounds like a feature request, which we don't track using GitHub Issues (we use GitHub exclusively for bug reports).
Please put ideas and feature requests on [our ideas page](https://ideas.obsproject.com).

Thank you!

**Comment by WizardCM** [comment]
Unfortunately we are unable to switch all our services to oauth-only as we use the cookies from the session to display the Chat (and related) Docks. The alternative would be to recreate any functionality provided by the current docks from scratch, and maintain it.
