### ISSUE TITLE
Media Sources Won't Deactivate

### ISSUE THREAD

**Issue by dog199200** [obsproject/obs-studio#11008]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.0

### OBS Studio Log URL

https://obsproject.com/logs/QX3mOqgzXseFylMt

### Expected Behavior

When changing a scene, or disabling a media source I expect playback to stop to stop when the "Close File When Inactive" is selected

![image](https://github.com/user-attachments/assets/2052ab18-9db3-4029-8c3b-48c047190000)

### Current Behavior

Media sources are not becoming inactive when they do not exist in an active scene.

![image](https://github.com/user-attachments/assets/430960d4-2b6c-456e-be0d-fe7da50da297)
![image](https://github.com/user-attachments/assets/425fc3b9-a581-4aa6-9255-8dfad0fb132a)

### Steps to Reproduce

1. Create a media source, maybe 2, and make sure each have settings in the photo set. 
![image](https://github.com/user-attachments/assets/04aca86d-58fb-46f3-a9bd-162833e61079)

2. Create a few scenes. 1 for each media source (each source in it's own unique scene), and 2 main scenes (One displaying each media source "scene"). 

3. Change between the 2 "main" scenes and watch as the media source from the previous scene is still outputting audio
![image](https://github.com/user-attachments/assets/480a3fe7-f264-4927-ac50-202c3d695415)

**Comment by Fenrirthviti** [comment]
Pleas reproduce this in a reduced scene collection with only the affected media sources and third party plugins disabled, as I cannot reproduce this with the directions provided.

**Comment by Sugam-Chand-M** [comment]
@dog199200 , I think a similar issue is already present - #10676 
A fix is already available for the same - #10980

**Comment by dog199200** [comment]
> Pleas reproduce this in a reduced scene collection with only the affected media sources and third party plugins disabled, as I cannot reproduce this with the directions provided.

So I was able to find exactly what was causing it and it is not an OBS issue. For anyone else who is having this issue, this issue is an Aitum Vertical problem, and I reported the issue to them. Scene sources are not properly shutting down if the vertical preview is disabled..
