### ISSUE TITLE
(Flatpak) OBS crash with browser source and no X11 DISPLAY (only Wayland)

### ISSUE THREAD

**Issue by YaLTeR** [obsproject/obs-studio#11019]
### Operating System Info

Other

### Other OS

Fedora 40 Silverblue

### OBS Studio Version

30.2.0

### OBS Studio Log URL

https://obsproject.com/logs/VQrv3WVhM7OWOocu

### OBS Studio Crash Log URL

https://obsproject.com/logs/VQrv3WVhM7OWOocu

### Expected Behavior

No crash.

### Current Behavior

Adding or having a browser source on the scene while there's no X11 DISPLAY causes a crash in libcef. Giving OBS a DISPLAY makes everything work fine, even when otherwise running under Wayland. Here's a *successful* log file running under Wayland, but with an X11 DISPLAY set: https://obsproject.com/logs/0IMwG6lApsY8tgBB

The backtrace looks something like this:
```
#0  0x00007f46d95dbd40 n/a (/app/lib/obs-plugins/libcef.so + 0x57dbd40)
#1  0x00007f46d956d7ea n/a (/app/lib/obs-plugins/libcef.so + 0x576d7ea)
#2  0x00007f46d95923c3 n/a (/app/lib/obs-plugins/libcef.so + 0x57923c3)
#3  0x00007f46d959212e n/a (/app/lib/obs-plugins/libcef.so + 0x579212e)
#4  0x00007f46d956cee9 n/a (/app/lib/obs-plugins/libcef.so + 0x576cee9)
#5  0x00007f46d956cc03 n/a (/app/lib/obs-plugins/libcef.so + 0x576cc03)
#6  0x00007f46d5ecf3b8 n/a (/app/lib/obs-plugins/libcef.so + 0x20cf3b8)
#7  0x00007f4747f7482d n/a (/app/lib/obs-plugins/obs-browser.so + 0x7682d)
#8  0x00007f4747f4ff5b n/a (/app/lib/obs-plugins/obs-browser.so + 0x51f5b)
#9  0x00007f4747f50edd n/a (/app/lib/obs-plugins/obs-browser.so + 0x52edd)
#10 0x00007f476e2f14e4 n/a (/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.32 + 0xf14e4)
#11 0x00007f476e0a1e39 n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x8ee39)
#12 0x00007f476e1299c4 n/a (/usr/lib/x86_64-linux-gnu/libc.so.6 + 0x1169c4)
```
It seems that `com.obsproject.Studio.Debug` is missing libcef debug symbols so I can't provide a proper backtrace.

### Steps to Reproduce

1. `env DISPLAY= flatpak run com.obsproject.Studio`
2. Add a browser source if you don't have one.

### Anything else we should know?

I'm running a compositor without rootless Xwayland ([niri](https://github.com/YaLTeR/niri)) so this issue is kinda annoying, because it means that I need to start up some rootful Xwayland instance just to give a DISPLAY to OBS. And nothing seems to actually need it apart from avoiding the libcef crash.

There's https://github.com/obsproject/obs-studio/issues/7927 but I'm not sure whether it's related because there people are running compositors with rootless Xwayland.

**Comment by kkartaltepe** [comment]
> nothing seems to actually need it apart from avoiding the libcef crash.

Just to note, this occurs precisely because you are using something that depends on X11. Its possible this may be resolved after the update to a newer cef version.
