### ISSUE TITLE
Cannot Record: starting output failed

### ISSUE THREAD

**Issue by JasonGrace2282** [obsproject/obs-studio#11014]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/v0EjDjOWJBfvBace

### Expected Behavior

I should be able to record my screen

### Current Behavior

![image](https://github.com/user-attachments/assets/4ad58d4b-6e67-4852-bb37-da9f0893b535)

### Steps to Reproduce

1. Open OBS Studio
2. Add source for screen capture
3. Choose full screen
4. Hit record

### Anything else we should know?

```
❯ pacman -Qsq desktop-portal
xdg-desktop-portal
xdg-desktop-portal-gtk
xdg-desktop-portal-hyprland
```

**Comment by tytan652** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for further assistance.

Thank you!

**Comment by JasonGrace2282** [comment]
I'll be sure to ask there. Thanks for pointing me in the right direction!
