### ISSUE TITLE
Removing any source cause OBS to crash

### ISSUE THREAD

**Issue by johannesschander** [obsproject/obs-studio#11028]
### Operating System Info

macOS 14

### OBS Studio Version

30.2.2

### OBS Studio Log URL

https://obsproject.com/logs/l4ZKwsQdLC9dn4O8

### OBS Studio Crash Log URL

System Integrity Protection: enabled  Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread  Exception Type:        EXC_BAD_ACCESS (SIGSEGV) Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000 Exception Codes:       0x0000000000000001, 0x0000000000000000  Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11 Terminating Process:   exc handler [7070]  VM Region Info: 0 is not in any region.  Bytes before following region: 4366991360       REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL       UNUSED SPACE AT START --->         __TEXT                      1044b0000-1048b0000    [ 4096K] r-x/r-x SM=COW  /Applications/OBS.app/Contents/MacOS/OBS  Thread 0 Crashed:: CrBrowserMain Dispatch queue: com.apple.main-thread 0   libsystem_platform.dylib      	       0x184ed8904 _platform_strlen + 4 1   StreamDeckPluginASIO1-28-0    	       0x120eb1cc8 std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>* nlohmann::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, bool, long long, unsigned long long, double, std::__1::allocator, nlohmann::adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>>::create<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, char const* const&>(char const* const&) + 48 2   StreamDeckPluginASIO1-28-0    	       0x120eb54f8 build_sceneitem_reference(obs_scene_item*) + 116 3   StreamDeckPluginASIO1-28-0    	       0x120eb6208 streamdeck::handlers::obs_scene::on_item_remove(void*, calldata*) + 112

### Expected Behavior

Remove an source, the source gets removed.

### Current Behavior

Click the trash icon to remove a source, gets asked "Are you sure you wish to remove" I say yes and OBS crashes. 

### Steps to Reproduce

1. Remove any source of any type 

### Anything else we should know?

I could not figure out a crash log from OBS, but macOS gives me a 180 pages long crash report. This is a part of it, but I have the full log saved. Not sure if theres any sensitive data but if safe I'm willing to share the full log. 

System Integrity Protection: enabled  Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread  Exception Type:        EXC_BAD_ACCESS (SIGSEGV) Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000 Exception Codes:       0x0000000000000001, 0x0000000000000000  Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11 Terminating Process:   exc handler [7070]  VM Region Info: 0 is not in any region.  Bytes before following region: 4366991360       REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL       UNUSED SPACE AT START --->         __TEXT                      1044b0000-1048b0000    [ 4096K] r-x/r-x SM=COW  /Applications/OBS.app/Contents/MacOS/OBS  Thread 0 Crashed:: CrBrowserMain Dispatch queue: com.apple.main-thread 0   libsystem_platform.dylib      	       0x184ed8904 _platform_strlen + 4 1   StreamDeckPluginASIO1-28-0    	       0x120eb1cc8 std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>* nlohmann::basic_json<std::__1::map, std::__1::vector, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, bool, long long, unsigned long long, double, std::__1::allocator, nlohmann::adl_serializer, std::__1::vector<unsigned char, std::__1::allocator<unsigned char>>>::create<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, char const* const&>(char const* const&) + 48 2   StreamDeckPluginASIO1-28-0    	       0x120eb54f8 build_sceneitem_reference(obs_scene_item*) + 116 3   StreamDeckPluginASIO1-28-0    	       0x120eb6208 streamdeck::handlers::obs_scene::on_item_remove(void*, calldata*) + 112

**Comment by RytoEX** [comment]
This is a crash caused by an outdated Stream Deck plugin. You must update or remove that plugin to avoid the crash.

**Comment by johannesschander** [comment]
> This is a crash caused by an outdated Stream Deck plugin. You must update or remove that plugin to avoid the crash.
@RytoEX You are so right! Sorry to bother and thank you very very much for saving the day! 👯‍♂️
