### ISSUE TITLE
Minecraft 1.8.9 forge crashing when i obs begins to capture the game

### ISSUE THREAD

**Issue by Lunarate** [obsproject/obs-studio#11025]
### Operating System Info

Windows 11

### Other OS

Windows 11

### OBS Studio Version

30.2.2

### OBS Studio Log URL

https://obsproject.com/logs/aHamvOZuBj8iOUSk and https://obsproject.com/logs/v1T8iYjoOgPZxSNv

### Expected Behavior

Minecraft java 1.8.9 to run smoothly without crashing

### Current Behavior

https://mclo.gs/hEqoF7G this is the minecraft crash and whenever obs begins to capture the game the game crashes, i sorted my mods and it doesnt crash when i dont use obs

### Steps to Reproduce

Honestly dont know

### Anything else we should know?

bo

**Comment by RytoEX** [comment]
Duplicate of #5841

**Comment by TOWUK** [comment]
disable optimization on display > graphics!!!! i have this problem too and my fix is:
![image](https://github.com/user-attachments/assets/26e7ad86-7579-4640-9141-49fe6289efc3)
