### ISSUE TITLE
"reuqire" typo in the documentation

### ISSUE THREAD

**Issue by arphox** [obsproject/obs-studio#11024]
Sorry, if I'm opening this in the wrong place, I haven't found the GitHub repository of the [knowledge base documentation](https://obsproject.com/kb), otherwise I would have done a Pull Request to resolve that.

The issue I'm reporting is that the [Audio/Video Formats Guide | OBS](https://obsproject.com/kb/audio-video-formats-guide) page has a typo, see the bold word:
>However, it is not well supported in editing software and may **reuqire** remuxing for use in editing software.

Please let me know if I could have posted a PR for this somehow.

**Comment by WizardCM** [comment]
Thank you for the report, I've fixed the typo.

In future, the recommended way to report these issues is the #documentation channel in the [OBS Discord](https://obsproject.com/discord).
