### ISSUE TITLE
When you try to save a repeat, the repeat is not saved and the repeat recording does not stop.

### ISSUE THREAD

**Issue by SXDIST** [obsproject/obs-studio#11033]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.2

### OBS Studio Log URL

https://ru.files.fm/u/k97qn72sha

### Expected Behavior

OBS Should have created a record from the replay buffer. 

### Current Behavior

OBS does not stop the recording or save it. And it happens only after some time, not at once....

### Steps to Reproduce

Just turned on the replay buffer and played a little bit of the game, then it stopped working.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
