### ISSUE TITLE
Python Error when importing Pandas module into python script

### ISSUE THREAD

**Issue by matt-gree** [obsproject/obs-studio#11039]
### Operating System Info

macOS 14

### OBS Studio Version

30.2.2

### OBS Studio Log URL

https://obsproject.com/logs/4TWg8B0DEHYnrJOD

### Expected Behavior

I expect my script to run normally

### Current Behavior

Upon loading the script, I get the following error and the script is not loaded.

```[InGameStatsOBS.py] Traceback (most recent call last):
[InGameStatsOBS.py]   File "/Users/mattgree/GitHub/OBS_scripts/InGameStatsOBS.py", line 13, in <module>
[InGameStatsOBS.py]     import pandas as pd
[InGameStatsOBS.py]   File "/Library/Frameworks/Python.framework/Versions/Current/lib/python3.12/site-packages/pandas/__init__.py", line 11, in <module>
[InGameStatsOBS.py]     __import__(_dependency)
[InGameStatsOBS.py]   File "/Library/Frameworks/Python.framework/Versions/Current/lib/python3.12/site-packages/numpy/__init__.py", line 144, in <module>
[InGameStatsOBS.py]     from . import core
[InGameStatsOBS.py]   File "/Library/Frameworks/Python.framework/Versions/Current/lib/python3.12/site-packages/numpy/core/__init__.py", line 24, in <module>
[InGameStatsOBS.py]     from . import multiarray
[InGameStatsOBS.py]   File "/Library/Frameworks/Python.framework/Versions/Current/lib/python3.12/site-packages/numpy/core/multiarray.py", line 10, in <module>
[InGameStatsOBS.py]     from . import overrides
[InGameStatsOBS.py]   File "/Library/Frameworks/Python.framework/Versions/Current/lib/python3.12/site-packages/numpy/core/overrides.py", line 62, in <module>
[InGameStatsOBS.py]     add_docstring(
[InGameStatsOBS.py] TypeError: Cannot set a docstring for that object
```

### Steps to Reproduce

1. Be on MacOS (not replicable on Windows)
2. Write any Python script that imports the Pandas module
3. Try to load the script

### Anything else we should know?

I have tried on two different Macs, one running on MacOS 14 with an M1 pro, and the other running MacOS 12 on an intel chip, got the same result on both. I've had friends test the issue on windows and they did not encounter it. I have ensured that Pandas is installed in my Python (I get a different error when it is not installed) and messed with different versions of both Pandas, NumPy, and Python. These packages work fine when I run them in scripts outside of OBS. I've reached out to people in the discord for help and have not been able to get anything to work. I also have found basically nothing online about the specific error message I have received.

**Comment by matt-gree** [comment]
Pinging @PatTheMav since you are credited with adding Python support.

**Comment by PatTheMav** [comment]
I wouldn't expect complex stuff like Pandas to work with our scripting system.

The main use case is simple interaction with sources via the frontend API (mainly automation), anything beyond that is practically unsupported.

**Comment by PatTheMav** [comment]
> FWIW Pandas does work on Windows OBS

Which is fine if it does, but we cannot make any guarantees about which 3rd party packages will or won't work as there are just too many of them.

When the scripting system was implemented, the intended scope was limited to what one might call "simple" procedural scripts (hence why you cannot use async or threads). 

Also the language capabilities of Python were much more limited, so the implementation does not (and in its current form cannot) support lots of things that had been introduced in recent Python versions (case in point: we cannot even implement Python 3.11 support on Windows right now).

**Comment by matt-gree** [comment]
Understood, thank you for your explanation. I guess I wasn’t really aware of the intended use (i.e. this script I’m working on also uses threads, which seems to function as intended). I’ll keep it in mind when writing future scripts.

**Comment by PatTheMav** [comment]
> Understood, thank you for your explanation. I guess I wasn’t really aware of the intended use (i.e. this script I’m working on also uses threads, which seems to function as intended). I’ll keep it in mind when writing future scripts.

There is nothing in the language or the runtime that prevents you from using threading, but it will lead to issues when interacting with the frontend API as there is a scaffolding of competing mutexes built into OBS that can either lead to deadlocks or weird race conditions that can come from its use (the same applies to modern Python language functionality, i.e. providing object methods instead of global functions as callbacks to the fronend API, etc.).
