### ISSUE TITLE
flip red and blue pipewire need

### ISSUE THREAD

**Issue by eqfae** [obsproject/obs-studio#11035]
### Operating System Info

Other

### Other OS

nix

### OBS Studio Version

30.2.2

### OBS Studio Log URL

https://obsproject.com/logs/rpEsGll7XOJAUgoM

### Expected Behavior

The color of the recording screen matches what I see

### Current Behavior

![图片](https://github.com/user-attachments/assets/63a2f6a5-1fc0-4a66-ad85-a18d991a5259)
![图片](https://github.com/user-attachments/assets/1fc992b8-7d92-4ba7-93c8-7f48f033c725)
![图片](https://github.com/user-attachments/assets/9c5d8466-e5cf-4860-8768-d87f0db4e6ca)
The color is wrong when selecting a window to record in. Not for full screen or region

### Steps to Reproduce

1.
2.
3.
...

```
  environment.systemPackages = [
    (pkgs.wrapOBS {
      plugins = with pkgs.obs-studio-plugins; [
        obs-pipewire-audio-capture
      ];
    })
  ];

  xdg.portal = {
    enable = true;
    wlr.enable = true;
    xdgOpenUsePortal = true;
    extraPortals = [
      pkgs.xdg-desktop-portal-hyprland
      #pkgs.xdg-desktop-portal-gtk
    ];
  };


{

  nixpkgs.config.packageOverrides = pkgs: {
    intel-vaapi-driver = pkgs.intel-vaapi-driver.override { enableHybridCodec = true; };
  };

  services.xserver.enable = true;  
  services.xserver.videoDrivers = [ "modesetting" ];
  hardware.amdgpu.initrd.enable = true;
  # amd显卡驱动
  
  # Enable OpenGL
  hardware.graphics = {
    enable = true;
    enable32Bit = true;
    extraPackages = with pkgs; [
      mesa
    ];
    extraPackages32 = with pkgs.pkgsi686Linux; [
      mesa
    ];
  };
}

That's what happened to me when I installed it, and I'm not sure which of his related nixos configurations reproduces it to some degree.

```

### Anything else we should know?

obs-vkcapture He can flip the colors, but only full screen.

**Comment by kkartaltepe** [comment]
Doesnt look like our bug, id recommend filing the bug with your compositor for reporting BGRX data but sending RGBX data instead.

**Comment by eqfae** [comment]
> Doesnt look like our bug, id recommend filing the bug with your compositor for reporting BGRX data but sending RGBX data instead.
![图片](https://github.com/user-attachments/assets/8ee46b95-3946-46ea-a2bf-9f5fd5bbab28)

Thank you. I found the problem.
https://wiki.hyprland.org/Configuring/Monitors/
#,bitdepth,10  # 10bit support causes app recording color flip

**Comment by kkartaltepe** [comment]
Well this log shows your compositor is not reporting 10 bit color formats to us, so they should probably fix that if they want 10 bit capture to work...
