### ISSUE TITLE
OBS Canvas won't show anything

### ISSUE THREAD

**Issue by felippenardi** [obsproject/obs-studio#11032]
### Operating System Info

macOS 14

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.02

### OBS Studio Log URL

https://obsproject.com/logs/ONGMQCtfPa5K3yhj

### Expected Behavior

I should be able to see OBS canvas

### Current Behavior

Nothing shows up in the OBS preview window
![CleanShot 2024-07-26 at 16 22 34@2x](https://github.com/user-attachments/assets/67a8e97c-c74b-4bc2-ab09-f9c1dc0d94fd)

### Steps to Reproduce

1. Open OBS
2. Nothing shows up on the OBS canvas

### Anything else we should know?

I already tried the version 30.2.2, but what happens is that OBS does not even stay open, it crashes immediately.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
