### ISSUE TITLE
Media playback not restarting after fast hide/show on playback end

### ISSUE THREAD

**Issue by Durss** [obsproject/obs-studio#11040]
### Operating System Info

Windows 11

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.2.0

### OBS Studio Log URL

https://obsproject.com/logs/IDN3X6TArJ9RWtOk

### Expected Behavior

Here's what I do:
* create a media source with a video or audio file
* tick option "Restart playback when source becomes active"
* show the source to start playback
* right when playback completes => hide/show the source

The media playback should restart

### Current Behavior

The playback does not restart properly unless I wait at least one full second after playback completes.

That's not something easy to reproduce manually but easily reproductible via OBS-websocket.

### Steps to Reproduce

1. Ceeate a media source with a local audio or video file
2. Tick option "Restart playback when source becomes active"
3. show the source to start playback
4. right when playback complete => hide/show the source

**Comment by tt2468** [comment]
This is not a bug. This is just how it works. Hiding and showing a scene item only toggles a bool and it's up to the graphics thread to iterate and do things according to that. If you hide and show a scene item, it is unlikely that the graphics thread will process in that time, so nothing will happen.

Use a SerialFrame request batch with a single frame sleep if you want it to work.
