### ISSUE TITLE
After Updating System and OBS Preview Screen is Black

### ISSUE THREAD

**Issue by Smithx10** [obsproject/obs-studio#11042]
### Operating System Info

Linux

### Other OS

Void Linux

### OBS Studio Version

30.2.2

### OBS Studio Log URL

https://obsproject.com/logs/ihH9FdQUpLEKvn4A

### Expected Behavior

Preview Screen to not be Black.

### Current Behavior

Preview Screen is black

### Steps to Reproduce

1. Update Void Linux to latest via xbps-install -Syu
2. Install OBS xbpx-install -Sy obs
3. Open OBS and view Black Preview Window.
...

### Anything else we should know?

Kernel Version:
❯ uname -a
Linux void-live 6.6.43_1 #1 SMP PREEMPT_DYNAMIC Sun Jul 28 07:18:17 UTC 2024 x86_64 GNU/Linux

Installed Packages on my system:
[installed-packages.txt](https://github.com/user-attachments/files/16414736/installed-packages.txt)

Here is a forum post describing the issue also where another user is suffering from the same issue.
https://obsproject.com/forum/threads/obs-no-longer-capturing-display-after-system-update.177102/

**Comment by kkartaltepe** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
