### ISSUE TITLE
Click on "Start Streaming" button cause OBS to crash on MacOS 14.5

### ISSUE THREAD

**Issue by JanPoonthong** [obsproject/obs-studio#11049]
### Operating System Info

macOS 14

### OBS Studio Version

30.2.2

### OBS Studio Log URL

https://obsproject.com/logs/6GPL3MNVTx5BR7e5

### OBS Studio Crash Log URL

https://obsproject.com/logs/7ROdsdjsEm7Mi8eI

### Expected Behavior

I expected to start streaming right away on YouTube and Twithc when I click on "Start Streaming".

I use obs-multiple-out RTM: https://sorayuki.github.io/obs-multi-rtmp/

### Current Behavior

When I clicked on "Start Streaming" obs crashed, but "Start Recording" works normal

### Steps to Reproduce

1. Click on "Start Streaming" button

**Comment by PatTheMav** [comment]
Does streaming to YouTube work out of the box without the 3rd party plugin?

**Comment by JanPoonthong** [comment]
Without a 3rd party plugin, streaming on YouTube or Twitch works perfectly fine.

**Comment by PatTheMav** [comment]
In that case you should report this crash to `obs-multiple-out` because it seems to be the a necessary component in causing it.
