### ISSUE TITLE
Theme not loading

### ISSUE THREAD

**Issue by claymorwan** [obsproject/obs-studio#11053]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

30.2.2

### OBS Studio Log URL

https://obsproject.com/logs/uPpTtTIP5QELntH5

### Expected Behavior

Themes are supposed to show in Settings>Appearence>Theme

### Current Behavior

Only the Yami theme shows up

### Steps to Reproduce

Install a theme and see if it shows up in the Theme dropdown

**Comment by WizardCM** [comment]
Legacy themes will need to be rewritten as of 30.2. Full details about how they work can be found [here](https://github.com/obsproject/obs-studio/wiki/OBS-Studio-Theme-System). If you are not the developer of the theme in question, you'll need to reach out to the original author.
