### ISSUE TITLE
Failed to initialize MFX

### ISSUE THREAD

**Issue by DZDeemix** [obsproject/obs-studio#11065]
### Operating System Info

Other

### Other OS

Ubuntu 24 LTS

### OBS Studio Version

30.2.2

### OBS Studio Log URL

https://obsproject.com/logs/NRPucUftt5ipLzWy

### Expected Behavior

Should start recording screen video

### Current Behavior

Output failed. Details in the logs. 

> error: Failed to initialize MFX

>  Specified object not found. ./plugins/obs-qsv11/common_utils_linux.cpp 347

>  Specified object not found. ./plugins/obs-qsv11/QSV_Encoder_Internal.cpp 153
> warning: [qsv encoder: 'msdk_impl'] Specified object/item/sync point not found. (MFX_ERR_NOT_FOUND)
> warning: [qsv encoder: 'simple_video_recording'] qsv failed to load

### Steps to Reproduce

1. Select in source screen capture
2.Click start record
3.
...

**Comment by kkartaltepe** [comment]
This is working as intended, and we do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum) if you want more help installing drivers on your system.
