### ISSUE TITLE
SRT streamID not recognized

### ISSUE THREAD

**Issue by spagettifritz** [obsproject/obs-studio#11061]
### Operating System Info

Windows 10

### OBS Studio Version

30.2.2

### OBS Studio Log URL

https://obsproject.com/logs/5XwmTgfJws2AvuuZ

### Expected Behavior

I expect OBS to properly handle the streamID parameter in media sources with SRT URLs. Specifically, each media source in OBS should only play the stream corresponding to its assigned streamID. This allows multiple SRT streams to be received on the same port but differentiated by their unique streamID.

Example:
- SRT encoder with two streams configured, acting as 'caller'
-> One SRT video stream configured with parameter 'streamID=foo'
-> One SRT video stream configured with parameter 'streamID=bar'

- OBS with two media sources configured, acting as 'listener'
-> Media source 'foo': srt://[ip]:[port]?mode=listener&streamid=foo 
--> playing the 'foo' video
-> Media source 'bar': srt://[ip]:[port]?mode=listener&streamid=bar
--> playing the 'bar' video

### Current Behavior

OBS seems to ignore the streamID parameter in the SRT URL. As a result, media sources in OBS play any incoming stream on the specified port, regardless of the streamID specified in the URL, therefore sometimes mixing up the media sources.

Example:

- SRT encoder with two streams configured, acting as 'caller'
-> One SRT video stream configured with parameter 'streamID=foo'
-> One SRT video stream configured with parameter 'streamID=bar'

- OBS with two media sources configured, acting as 'listener'
-> Media source 'foo': srt://[ip]:[port]?mode=listener&streamid=foo 
--> Sometimes playing the 'foo' video, but sometimes the wrong 'bar' video
-> Media source 'bar': srt://[ip]:[port]?mode=listener&streamid=bar
--> Sometimes playing the 'bar' video, but sometimes the wrong 'foo' video

If both streams have no passphrase or the same passphrase set, it will just mix up the videos, but if both streams have different passphrases, on the mixup of the streamIDs, there is no video at all, because the passphrase is not correct for the according streamID.

### Steps to Reproduce

1. Set up two SRT streams with different streamID values sending to the same port using an SRT encoder as 'caller'.
2. Configure two media sources in OBS with the respective SRT URLs as 'listener', including the streamID parameter.
3. Start the SRT streams on the transmitting encoder and observe that OBS sometimes plays any incoming stream on the specified port, regardless of the streamID specified in the URL, mixing up the streamIDs and therefore the videos.

### Anything else we should know?

- Tried using the SRT connection with as well as without password
- Tried using different streamIDs on both, encoder as caller and OBS as listener (numeric, alphabetic)
- Tried using streamIDs in SRT URL in OBS with and without quotation marks

**Comment by tt2468** [comment]
Your expected configuration is not valid. Multiple media sources cannot share the same listener port, for there to be a situation where the listener side needs to care about the stream ID.
