### ISSUE TITLE
Poor video quality for both live-stream and recoding by using amd gpu

### ISSUE THREAD

**Issue by GADDQ** [obsproject/obs-studio#11070]
### Operating System Info

Windows 10

### OBS Studio Version

30.2.2

### OBS Studio Log URL

https://obsproject.com/logs/BMjfElIAwCqv7b97

### Expected Behavior

I use VBR to record and stream, on older version, i can get a great graphic quality, such as 25.x.x, but recently when i update OBS, it's looks terrible.

### Current Behavior

I have a amd RX6600XT gpu and trying to stream and record video on it, but after i upgrade OBS Studio, video looks terrible.
Notice that this problem ONLY appears when you using Windows, cause' when i using my Arch Linux to stream and record, everything looks fine, but Windows NOT.

### Steps to Reproduce

1.Choose VBR.
2.Set 10000Kbps.
3.Stream or record.

### Anything else we should know?

![1df8dd7a929b511806c0d82b0e36aada](https://github.com/user-attachments/assets/0aceadc5-cd3d-4926-af89-cc7b0e82a7a7)Looks like this picture, it's definitely terrible.
AMD Driver Version: 24.7.1

**Comment by RytoEX** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
