### ISSUE TITLE
Low framerate while previewing and recording

### ISSUE THREAD

**Issue by TotallyMonica** [obsproject/obs-studio#11076]
### Operating System Info

Other

### Other OS

Fedora 40 / Flatpak

### OBS Studio Version

30.2.2

### OBS Studio Log URL

https://obsproject.com/logs/1uLNkcDJH6vlZWZ2

### Expected Behavior

Consistent 60fps preview and recording.

### Current Behavior

Low framerate and encoding overload warnings.

### Steps to Reproduce

1. Ensure Nvidia proprietary drivers are installed
2. Install OBS through Flatpak
3. Run
4. Observe low framerates
5. After starting a recording, observe even lower framerates and encoding overload messages

### Anything else we should know?

Issue arose after updating to nvidia drivers 555.58, persists after a reinstall of the OS
Specs:
Ryzen 5 3600
Nvidia GeForce RTX 3060 12GB (Proprietary drivers)
32 GB DDR4
Plasma 6.1 (Wayland)

**Comment by TotallyMonica** [comment]
https://github.com/user-attachments/assets/982f60bd-e5cf-4af0-b0f4-e0b16a6512bb

For what it's worth, here's the recording used to get the log

**Comment by kkartaltepe** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

**Comment by TotallyMonica** [comment]
I'll visit the Discord server, however it is my belief this isn't a support question but rather a bug when a system is using the aforementioned video driver.
