### ISSUE TITLE
If you change the window language, not the whole interface changes. 

### ISSUE THREAD

**Issue by F3F5** [obsproject/obs-studio#11072]
### Operating System Info

Windows 11

### Other OS

Windows

### OBS Studio Version

30.2.2

### OBS Studio Version (Other)

.

### OBS Studio Log URL

.

### OBS Studio Crash Log URL

.

### Expected Behavior

![Screenshot_1](https://github.com/user-attachments/assets/3a255e98-2cfe-4870-97c9-f6fc75361be2)
here, also mic/aux scenes for example in Russian.

### Current Behavior

.

### Steps to Reproduce

.

### Anything else we should know?

.

**Comment by Fenrirthviti** [comment]
Please properly fill out the PR template, and this can be re-opened.
