### ISSUE TITLE
[Flatpak] Thread 58 "Chrome_IOThread" received signal SIGTRAP, Trace/breakpoint trap.

### ISSUE THREAD

**Issue by LunasShade** [obsproject/obs-studio#11085]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

30.2.2

### OBS Studio Log URL

https://pastebin.com/LziPzqbq

### Expected Behavior

No problems during recording

### Current Behavior

Thread 58 "Chrome_IOThread" received signal SIGTRAP, Trace/breakpoint trap.
[Switching to Thread 0x7fff516006c0 (LWP 131)]
0x00007fff9567cd3a in ?? () from /app/lib/obs-plugins/libcef.so

### Steps to Reproduce

1. Start OBS normal
2. Try to record
3. OBS crashes through error

### Anything else we should know?

If helpful:
- The previous error log was with vkcapture source: https://pastebin.com/qL0F4PRq

**Comment by kkartaltepe** [comment]
Please provide the actual backtrace after the crash.

**Comment by LunasShade** [comment]
I followed this instruction from Discord and hope you mean that.

- To get a backtrace on flatpak:
1. Get the debug symbols: `flatpak install flathub com.obsproject.Studio.Debug`
2. Run `flatpak run --command=sh --devel com.obsproject.Studio`. This will throw an error `error: runtime/org.kde.Sdk/x86_64/<version number> not installed`, note the version number
3. Install the sdk: `flatpak install flathub org.kde.Sdk`. This will ask you which version to install, select the one you noted previously
4. Run again `flatpak run --command=sh --devel com.obsproject.Studio`. This time, it should work and switch you to a console inside the runtime (the part at the left of the prompt will change to [ com.obsproject.Studio ~]$)
5. Inside that console, run` gdb obs` to start gdb, then `r` to run obs, then `bt` to get a backtrace once obs has crashed
6. `q` to quit gdb, and `Ctrl + D` to exit the flatpack console back to the normal one

The output i got is this:
```
Thread 69 "Chrome_IOThread" received signal SIGTRAP, Trace/breakpoint trap.
[Switching to Thread 0x7fff3e0006c0 (LWP 142)]
0x00007fff81722608 in ?? () from /app/lib/obs-plugins/libcef.so
(gdb) bt
#0  0x00007fff81722608 in ??? () at /app/lib/obs-plugins/libcef.so
#1  0x00007fff3dffe550 in ??? ()
#2  0x00007fff7fbbd25c in ??? () at /app/lib/obs-plugins/libcef.so
#3  0x00007fff873394b0 in ??? () at /app/lib/obs-plugins/libcef.so
#4  0x00000000ffffffff in ??? ()
#5  0x00007fff3dffe550 in ??? ()
#6  0x0000000000200000 in ??? ()
#7  0x00007fff3dffe600 in ??? ()
#8  0x00007fff3dffe5a0 in ??? ()
#9  0x00007ffe5c0300c0 in ??? ()
#10 0x00007ffef0043a80 in ??? ()
#11 0x00007fff3dffe720 in ??? ()
#12 0x00007fff7fbac818 in ??? () at /app/lib/obs-plugins/libcef.so
#13 0x0000000000000000 in ??? ()
```

**Comment by kkartaltepe** [comment]
please provide the full regular log from obs when this occurs, from the log https://pastebin.com/qL0F4PRq it seems your system is dying. Maybe your gpu reset or something.

**Comment by LunasShade** [comment]
Here is again a complete log with backtrace, but after the latest update I got, on my first try, what came out of the backtrace has become smaller. https://pastebin.com/aZ1dLRgH

**Comment by LunasShade** [comment]
I use the Spotify widget from: https://6klabs.com/

**Comment by LunasShade** [comment]
However, it is not only due to the website but also to OBS together with Wayland, if you start OBS with X11 the problem does not occur.

Source: https://github.com/obsproject/obs-studio/issues/7927
