### ISSUE TITLE
Untraceable static noise in recordings/streams when using Game Capture Audio

### ISSUE THREAD

**Issue by Karsteski** [obsproject/obs-studio#11113]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.2

### OBS Studio Log URL

https://obsproject.com/logs/64O26EkWRyOBdHte

### Expected Behavior

No static in game capture audio track

### Current Behavior

Random static noise in game capture audio track

### Steps to Reproduce

1. Use Game Capture Source
2. Enable Capture Audio (Beta) in Properties
3. Record long enough for problem to occur randomly.
4. Be sad.

### Anything else we should know?

[Here's an example of the sound](https://www.youtube.com/watch?v=dhuyq4nll88)

**Comment by Fenrirthviti** [comment]
Duplicate of https://github.com/obsproject/obs-studio/issues/8064
