### ISSUE TITLE
Tests are not built/enabled with "updated CMake path".

### ISSUE THREAD

**Issue by Chiitoo** [obsproject/obs-studio#11115]
### Operating System Info

Other

### Other OS

Gentoo Linux

### OBS Studio Version

Git

### OBS Studio Log URL

N/A

### Expected Behavior

Test files are generated and unit tests enabled as they are with "outdated CMake path".

### Current Behavior

The 'ENABLE_UNIT_TESTS' switch is only included in the "legacy path" and no tests are found for CTest to run (only 'test-input' is built with '-DENABLE_TEST_INPUT').

### Steps to Reproduce

1. Build OBS Studio with '-DENABLE_UNIT_TESTS=ON'.

### Anything else we should know?

Perhaps this is intentional, considering the CMake switches/'enable_testing()' have not been included in the "updated CMake path", but including them does seem to successfully generate/enable the tests as before.

Thank you!

**Comment by PatTheMav** [comment]
Unit tests were unmaintained and not supported for a very long time, so they've been removed from the modern build setup. 

The only "tests" remaining are the test sources/inputs.

PRs for proper unit tests would be welcome, but should be platform-appropriate (i.e. use `XCTest` on macOS, "Visual Studio Unit Testing Framework" on Windows, etc.).
