### ISSUE TITLE
Twitch Disconnect Protection not working reliably with new eRTMP vodtrack audio implementation 

### ISSUE THREAD

**Issue by lablo111** [obsproject/obs-studio#11118]
### Operating System Info

Windows 10

### OBS Studio Version

30.2.2

### OBS Studio Log URL

https://obsproject.com/logs/LiEBBwDZ8dm8Iclt

### Expected Behavior

Twitch "NotLikeThis" emote disconnect protection screen kicks in for 90 secs reliably

### Current Behavior

Stream ends like 75% of the time instantly

### Steps to Reproduce

1. Enable "Disconnect Protection feature on Twitch"
2. Enable "Twitch Vod Track" in Output->Stream settings
3. Go Live, wait a bit
4. `killall -9 OBS` or equivalent

### Anything else we should know?

So this isn't technically an OBS bug but really a Twitch bug however it does affect and seems to be catching out a bunch of OBS users so having a findable issue for it seems like a good idea (to me).

It appears that when the recently added enhanced RTMP multitrack audio/video implementation in OBS is used with Twitch VodTrack audio then the Twitch "Disconnect Protection" becomes broken or really unreliable, as in it doesn't kick in most of the time in case of OBS crashes or internet hiccups.

Testing was done with killing OBS 30.2.2 about 30 times in a row, each time toggling between VOD track on and off, and seeing if Disconnect Protection kicks in. It always does without vod track but only very rarely does with it enabled (when testing be sure that stream is down fully when turning it on and going live and not still live on the NotLikeThis screen from an earlier test with vod track off).

I also reproduced that with the eRTMP ffmpeg fork (https://github.com/BtbN/FFmpeg/tree/enhanced-flv by `BtbN` && `derrod`) and streaming to Twitch with it with dual audio tracks and killing the process and the same happens there, no disconnect protection most of the time when having 2 audio tracks but always reliable when on a single audio track.

There are multiple people in discord complaning about the same issue with it too:

https://discord.com/channels/348973006581923840/374636015396192257/1267313075338608681
2024-07-29 "Hello i would like help with something my OBS dissconnects frequently and now when it dissconnects it ends my whole stream even when i have dissconnect preotection on"

https://discord.com/channels/348973006581923840/374636015396192257/1270500780704534539
https://discord.com/channels/348973006581923840/374636015396192257/1264349361492721805

2024-07-20 "Hey, guys! I have problem with new obs version. Twitch disconnect protection just not working, the stream ends as usual.
Someone has this problem with current version? Disconnect protection is on in twitch settings. Thank you."
"Hi, I have the same problem with disconnect protection, I wrote about it above but no one helped me. Returning to version 30.1.2 - helped to solve the problem."

And same on Twitter https://twitter.com/duckisaurus_/status/1819856839242399771 and a couple more
"Does anyone have experience with their disconnect protection on twitch not working anymore? I turned it off & on a few times. It just no longer pops up & leaves me with 3-5 vods per a stream."

**Comment by derrod** [comment]
This is a Twitch issue which you will need to report to them, e.g. via the enhanced broadcasting discord.

**Comment by lablo111** [comment]
@derrod Yeah makes sense. Seems like that discord was for beta users only which I am not so no clue how i would still join that. And normal Twitch bug reporting has generally been the most useless thing ever sadly.

I just wanted to make an issue here since this basically breaks Disconnect Protection on Twitch for everyone that updates to latest OBS if they use vodtrack so anyone finding this at least knows whats going on.
