### ISSUE TITLE
Encoders missing after update - NVENC 

### ISSUE THREAD

**Issue by Gamma195** [obsproject/obs-studio#11112]
### Operating System Info

Other

### Other OS

CachyOS

### OBS Studio Version

30.2.2

### OBS Studio Log URL

https://obsproject.com/logs/RKONsct1r5FIpUtn

### Expected Behavior

NVIDIA Encoders showing under recording tab. 

### Current Behavior

Hello!

This is my first time reporting something, so if I don't provide everything I apologize.

I recently updated my system (I'm fairly new to linux. Only been on it for a few weeks daily driving it), and everything was working as it should but after the update last night for OBS, it appears that my encoders went missing. I previously had NVENC and NVENC HVEC, along with several others - and they are now missing.  There was also a change to the preset - which I am confused on the naming change. 

My system specs:
OS: CachyOS
KERNEL: 6.10.1-2-cachyos
CPU: AMD Ryzen 9 7900X 12-Core
GPU: NVIDIA GeForce RTX 4080
GPU DRIVER: NVIDIA 560.31.02
RAM: 32 GB

I will also attach my log from today, and a few others for references. 

[2024-08-11 05-08-40.txt](https://github.com/user-attachments/files/16573207/2024-08-11.05-08-40.txt)
[2024-08-11 05-06-14.txt](https://github.com/user-attachments/files/16573208/2024-08-11.05-06-14.txt)
[2024-08-08 10-32-18.txt](https://github.com/user-attachments/files/16573210/2024-08-08.10-32-18.txt)
[2024-08-05 12-09-53.txt](https://github.com/user-attachments/files/16573211/2024-08-05.12-09-53.txt)

![Screenshot_20240811_052445](https://github.com/user-attachments/assets/fa7190a9-cb42-4c8d-b803-24d2f27ca4d9)

### Steps to Reproduce

1.Launch OBS 
2.Click settings and click output
3.Under recording, video encoder, there should've been an NVIDIA Encoder. 
...

**Comment by tytan652** [comment]
Report to your distro packager.

**Comment by Gamma195** [comment]
This was an update from OBS?

**Comment by tt2468** [comment]
OBS does not maintain any release builds for CatchyOS. It is the responsibility of the packager to ensure that the necessary dependencies are available at build time.
