### ISSUE TITLE
For windows 10 x64 version 没法链接动态库

### ISSUE THREAD

**Issue by qqxiaoteng** [obsproject/obs-studio#11129]
### Operating System Info

Windows 10

### OBS Studio Version

30.2.2

### OBS Studio Log URL

nope

### Expected Behavior

<img width="304" alt="Screenshot at 15-39-16" src="https://github.com/user-attachments/assets/92980d44-56af-41a2-834f-1bf981d6d11b">

### Current Behavior

<img width="304" alt="Screenshot at 15-39-16" src="https://github.com/user-attachments/assets/92980d44-56af-41a2-834f-1bf981d6d11b">

### Steps to Reproduce

1.
2.
3.
...
<img width="304" alt="Screenshot at 15-39-16" src="https://github.com/user-attachments/assets/92980d44-56af-41a2-834f-1bf981d6d11b">

**Comment by WizardCM** [comment]
You are running an outdated version of Windows 10, which not supported by OBS. You need Windows 10 1709 or newer.

This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels below, and if it's determined that this is indeed a bug, then we will re-open this issue.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
