### ISSUE TITLE
Can't use mouse buttons 4 & 5 as hotkeys when window not focused

### ISSUE THREAD

**Issue by guy-bartkus** [obsproject/obs-studio#11130]
### Operating System Info

Other

### Other OS

Linux Mint 22

### OBS Studio Version

30.2.2

### OBS Studio Log URL

https://obsproject.com/logs/7tuTEs8jAASatJ3K

### Expected Behavior

Expected mouse button 4 to work as hotkey to start recording when OBS window is not focused.

### Current Behavior

Able to set mouse button 4 as hotkey for start recording, but doesn't actually work to start recording when the window is not focused. Confirmed keyboard keys work fine. Have not tested other mouse buttons besides 4 & 5.

### Steps to Reproduce

Set mouse button 4 as start recording hotkey and attempt to start recording while OBS window is not focused.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
