### ISSUE TITLE
Preview freezes after dragging window to different size monitor and snapping to fullscreen

### ISSUE THREAD

**Issue by BuggyAl** [obsproject/obs-studio#11134]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.2

### OBS Studio Log URL

https://obsproject.com/logs/eI0DqlTOhVaCAZcg

### Expected Behavior

The preview does not freeze and continues to update as normal.

### Current Behavior

After snapping the window to fullscreen on a different monitor, the preview freezes up. This does not affect the recording or other docks.

### Steps to Reproduce

1. Use 2 different monitors (in my case a monitor and a laptop screen)
2. Open OBS on one screen
3. Drag it to another screen
4. Fullscreen OBS by clicking the fullscreen button or dragging to top of screen
5. Observe the preview window freeze

**Comment by BuggyAl** [comment]
The error in the log appears to be 
```
15:59:50.449: device_resize_internal (D3D11): Failed to resize swap buffers (887A0005)
15:59:50.450:   Device Removed Reason: 00000000
15:59:50.468: device_draw (D3D11): texture is not a render target (x17)
```

**Comment by matoi974** [comment]
This looks like a graphics card driver crash, try asking for help on Discord and/or the obsproject.com forums.

**Comment by BuggyAl** [comment]
Issue was solved after switching from Hybrid graphic to Discrete in OMEN Gaming Hub. Thanks for the help!
