### ISSUE TITLE
When using OBS scripting features, the application hangs or freezes right after startup.

### ISSUE THREAD

**Issue by wangbaoyi** [obsproject/obs-studio#11132]
### Operating System Info

Windows 10

### OBS Studio Version

30.1.2

### OBS Studio Log URL

1

### Expected Behavior

Under normal circumstances, it shouldn’t hang or freeze like that. Additionally, I’ve noticed that while the OBS script program does run, its performance isn’t as good as expected. I’ve done some comparisons.

### Current Behavior

I called a C++ DLL interface using Python code, and after launching, it hangs or freezes. I also tried using Python's shared dictionary, and the same issue occurs.
![image](https://github.com/user-attachments/assets/ef32a5ca-72ad-4441-a7a9-93a3068285c3)

### Steps to Reproduce

import obspython as obs
from ant.UdpSend import DxUdp

dxt = DxUdp()
dxt.IP = b"192.168.31.74"
dxt.Port = 8888
dxt.Range = 416
dxt.FPS = 2

def script_description():
    return "截图+局域网传输工具,IP信息:"

def test1(props, prop):
    print("启动")
    dxt.dx_screena()
    #B是多线程，电脑好的用
    # dxt.dx_screenb()

def test2(props, prop):
    print("停止")

def script_properties():
    props = obs.obs_properties_create()
    obs.obs_properties_add_button(props, 'test1', '启动', test1)
    obs.obs_properties_add_button(props, 'test2', '停止', test2)
    return props

def script_load(settings):
    pass
    # dxt.dx_screena()
    #B是多线程，电脑好的用
    # dxt.dx_screenb()

# def script_unload():
#     # dx.stop_sending()
#     pass

udpsend.py:

from ctypes import *
import ctypes

class DxUdp:
    def __init__(self):
        # # 加载DLLng m
        self.my_dll = ctypes.cdll.LoadLibrary("C:/DxDll/DxgiUdp.dll")
        # std::string IP, std::string Port, int Range, int FPS
        # 定义函数参数和返回类型
        self.my_dll.add_numbers.argtypes = [ctypes.c_int, ctypes.c_int]
        self.my_dll.add_numbers.restype = ctypes.c_int

        self.my_dll.sendData.argtypes = [ctypes.c_char_p, ctypes.c_int, ctypes.c_int, ctypes.c_int]
        self.my_dll.sendData.restype = None

        # self.my_dll.DxRun.argtypes = [ctypes.c_char_p, ctypes.c_int, ctypes.c_int, ctypes.c_int]
        # self.my_dll.DxRun.restype = ctypes.c_int

        # self.my_dll.main.restype = None  # 如果main函数没有返回值，可以不设置restype

        # self.IP = b"192.168.31.74"
        self.IP = b"192.168.31.74"
        self.Port = 8888
        self.Range = 416
        self.FPS = 2

    def dx_screena(self):
        # 调用DLL函数
        self.my_dll.sendData(self.IP,self.Port,self.Range,self.FPS)

    # def dx_screenb(self):
    #     # 调用DLL函数-多线程
    #     self.my_dll.DxRun(self.IP,self.Port,self.Range,self.FPS)

if __name__ == '__main__':
    dxt = DxUdp()
    dxt.dx_screena()
    # dxt.dx_screenb()

### Anything else we should know?

import obspython as obs
from ant.UdpSend import DxUdp

dxt = DxUdp()
dxt.IP = b"192.168.31.74"
dxt.Port = 8888
dxt.Range = 416
dxt.FPS = 2

def script_description():
    return "截图+局域网传输工具,IP信息:"

def test1(props, prop):
    print("启动")
    dxt.dx_screena()
    #B是多线程，电脑好的用
    # dxt.dx_screenb()

def test2(props, prop):
    print("停止")

def script_properties():
    props = obs.obs_properties_create()
    obs.obs_properties_add_button(props, 'test1', '启动', test1)
    obs.obs_properties_add_button(props, 'test2', '停止', test2)
    return props

def script_load(settings):
    pass
    # dxt.dx_screena()
    #B是多线程，电脑好的用
    # dxt.dx_screenb()

# def script_unload():
#     # dx.stop_sending()
#     pass

udpsend.py:

from ctypes import *
import ctypes

class DxUdp:
    def __init__(self):
        # # 加载DLLng m
        self.my_dll = ctypes.cdll.LoadLibrary("C:/DxDll/DxgiUdp.dll")
        # std::string IP, std::string Port, int Range, int FPS
        # 定义函数参数和返回类型
        self.my_dll.add_numbers.argtypes = [ctypes.c_int, ctypes.c_int]
        self.my_dll.add_numbers.restype = ctypes.c_int

        self.my_dll.sendData.argtypes = [ctypes.c_char_p, ctypes.c_int, ctypes.c_int, ctypes.c_int]
        self.my_dll.sendData.restype = None

        # self.my_dll.DxRun.argtypes = [ctypes.c_char_p, ctypes.c_int, ctypes.c_int, ctypes.c_int]
        # self.my_dll.DxRun.restype = ctypes.c_int

        # self.my_dll.main.restype = None  # 如果main函数没有返回值，可以不设置restype

        # self.IP = b"192.168.31.74"
        self.IP = b"192.168.31.74"
        self.Port = 8888
        self.Range = 416
        self.FPS = 2

    def dx_screena(self):
        # 调用DLL函数
        self.my_dll.sendData(self.IP,self.Port,self.Range,self.FPS)

    # def dx_screenb(self):
    #     # 调用DLL函数-多线程
    #     self.my_dll.DxRun(self.IP,self.Port,self.Range,self.FPS)

if __name__ == '__main__':
    dxt = DxUdp()
    dxt.dx_screena()
    # dxt.dx_screenb()

**Comment by Penwy** [comment]
OBS scripting runs in the frontend, meaning that any blocking call will block the whole frontend, effectively causing a whole program hang.
Scripting is not the tool for what you're trying to achieve here.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
