### ISSUE TITLE
No source selected

### ISSUE THREAD

**Issue by ley112476** [obsproject/obs-studio#11138]
### Operating System Info

macOS 14

### OBS Studio Version

30.2.2

### OBS Studio Log URL

https://obsproject.com/logs/ek3SG0ElrMZF8DEe

### Expected Behavior

To open the properties and pick the video I wanted to run.

### Current Behavior

Unable to access my sources. It says 'no source selected' and the properties box is inactive.

### Steps to Reproduce

1. After updating to 30.2.2 version
2. I am on Sonoma 14.4.1 on my MacBook
3.
...

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
