### ISSUE TITLE
wont record on UBUNTU and crashes

### ISSUE THREAD

**Issue by ruderod** [obsproject/obs-studio#11157]
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

30.2.2

### OBS Studio Log URL

ok

### Expected Behavior

wanted to record one window screen.

### Current Behavior

App crashes.  There must be specific installations of specific hardware that OBS studio works on.  Linux appears to have many people report crashes.  Can we specify the hardware that people have gotten OBS to work on? This must be some driver issue and so lets go ahead and state what drivers work.   I have used this app with Windows with no problems.  . . my guess it uses windows api calls/directx and does not talk to the video chip drivers directly?

### Steps to Reproduce

1.run app,  try to record.  it crashes. 
2.
3.
...

**Comment by tytan652** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for further assistance.

Thank you!
