### ISSUE TITLE
Game capture fails if 2 sources capture the same window

### ISSUE THREAD

**Issue by Stevoisiak** [obsproject/obs-studio#11158]
### Operating System Info

Windows 11

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/TJ1knPNcx3lOjDLj

### Expected Behavior

If you add two different Game Capture sources that record the same window, both sources should display the game window.

### Current Behavior

Only one Game Capture source will display the game window. The other will show a black screen.

### Steps to Reproduce

1. Open OBS
2. Create a new "Game Capture" source.
3. Set mode to "Capture specific window" and select a game window.
4. Click OK.
5. Create a second "Game Capture" source.
6. Set mode to "Capture specific window" and select the same game window as in step 3.
7. Click OK.
...

https://github.com/user-attachments/assets/a84965fa-b799-49c6-a2d1-389d0b9d03ca

### Anything else we should know?

If visibility is toggled off for the Game Capture that is displaying the game correctly, the other Game Capture will begin displaying the game instead.

**Comment by Fenrirthviti** [comment]
This is expected. The game can only support one game capture hook at a time. Use "Add Existing" when adding the second source.

This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by Stevoisiak** [comment]
> This is expected. The game can only support one game capture hook at a time. Use "Add Existing" when adding the second source.
> 
> This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.
> 
> Thank you!

I've edited my ticket to provide a use case example where using "Add existing" would not be sufficient. On that note, if capturing the same window twice is not supported, it would be nice for there to be a warning within OBS.

**Comment by prgmitchell** [comment]
> > This is expected. The game can only support one game capture hook at a time. Use "Add Existing" when adding the second source.
> > This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.
> > Thank you!
> 
> I've edited my ticket to provide a use case example where using "Add existing" would not be sufficient. On that note, if capturing the same window twice is not supported, it would be nice for there to be a warning within OBS.

Do feel free to stop by the Discord server that was linked for help with this, you can ping me if you'd like my name there is Mitchell | Yolo.
