### ISSUE TITLE
spellingerrors

### ISSUE THREAD

**Issue by umlaeute** [obsproject/obs-studio#11160]
### Operating System Info

Other

### Other OS

n.n.

### OBS Studio Version

30.2.2

### OBS Studio Log URL

n.n.

### Expected Behavior

i expect output to be free of spelling errors.

### Current Behavior

there are some spelling errors in the code base, among others:

| current | expected |
|---|---|
|`doesnt` | `doesn't` |
| `depricated` | `deprecated` |
| `retreived` | `retrieved` |

### Steps to Reproduce

1. install `lintian`
   ```sh
   apt install lintian
   ```

2. get the latest and greatest Ubuntu package from your [release page](https://github.com/obsproject/obs-studio/releases/)
   ```sh
   wget https://github.com/obsproject/obs-studio/releases/download/30.2.3/OBS-Studio-30.2.3-Ubuntu-22.04-x86_64.deb
   ```
3. use lintian to spell-check the binary
   ```sh
   lintian  OBS-Studio-30.2.3-Ubuntu-22.04-x86_64.deb  | grep spelling-error | egrep -v "(libcef|libGLES)"
   ```

### Anything else we should know?

my list above does not include the `depracated` misspelling mandated by the twitch API.

I'm aware that some of the spelling errors do not originate in *this* repository.
since you know better where things come from, I decided not to file separate bugs.

**Comment by WizardCM** [comment]
All but one of these are internal code comments. Feel free to PR the fix to ALSA's logging, but generally these kinds of GitHub issues aren't helpful.

**Comment by gxalpha** [comment]
Feel free to make Pull Requests (this repo and obs-websockets) if you’re bothered by them. These are minor typos in log files though, which I don’t think warrant a bug report.

**Comment by RytoEX** [comment]
> ```
> plugins/linux-alsa/alsa-input.c:		blog(LOG_ERROR, "device doesnt support any OBS formats");
> plugins/obs-outputs/ftl-sdk/libftl/ftl-sdk.c:  FTL_LOG(ftl, FTL_LOG_WARN, "%s() is depricated, please use ftl_ingest_speed_test_ex()\n", __FUNCTION__);
> plugins/obs-outputs/ftl-sdk/libftl/handshake.c:      FTL_LOG(ftl, FTL_LOG_ERROR, "This version of the FTLSDK is depricated");
> plugins/obs-websocket/src/forms/ConnectInfo.cpp:		blog(LOG_ERROR, "[ConnectInfo::showEvent] Unable to retreive config!");
> plugins/obs-websocket/src/forms/SettingsDialog.cpp:		blog(LOG_ERROR, "[SettingsDialog::showEvent] Unable to retreive config!");
> plugins/obs-websocket/src/forms/SettingsDialog.cpp:		blog(LOG_ERROR, "[SettingsDialog::RefreshData] Unable to retreive config!");
> plugins/obs-websocket/src/forms/SettingsDialog.cpp:		blog(LOG_ERROR, "[SettingsDialog::SaveFormData] Unable to retreive config!");
> plugins/obs-websocket/src/websocketserver/WebSocketServer.cpp:		blog(LOG_ERROR, "[WebSocketServer::Start] Unable to retreive config!");
> plugins/obs-websocket/src/websocketserver/WebSocketServer.cpp:		blog(LOG_ERROR, "[WebSocketServer::onOpen] Unable to retreive config!");
> plugins/obs-websocket/src/websocketserver/WebSocketServer.cpp:		blog(LOG_ERROR, "[WebSocketServer::onClose] Unable to retreive config!");
> ```

We removed ftl-sdk, and obs-websocket is its own repo.

**Comment by umlaeute** [comment]
Ah, I now see that flt-sdk was removed just recently (https://github.com/obsproject/obs-studio/pull/10019) *after* the last release, which is what I tested against. 

Time permitting I will open PRs for the other issues.
