### ISSUE TITLE
if input video have move that should forbid system close screen

### ISSUE THREAD

**Issue by runsys** [obsproject/obs-studio#11168]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.2

### OBS Studio Log URL

no

### Expected Behavior

obs forbid system close screen

### Current Behavior

after some minutes will close screen.

### Steps to Reproduce

1.jusr run and see.
2.
3.
...

**Comment by WizardCM** [comment]
This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels below, and if it's determined that this is indeed a bug, then we will re-open this issue.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

**Comment by Fenrirthviti** [comment]
As a note, OBS will inhibit screen/system sleep if there is an active output. Simply being open will not, but it is something that may change in the future as this is a constant complaint that keeps coming up, and we don't support recovery from any kind of sleep operation anyway.
