### ISSUE TITLE
nVenc Codec causes game crashes

### ISSUE THREAD

**Issue by ShirubaPixel** [obsproject/obs-studio#11173]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/FiqyXbM67xmIWK7V

### Expected Behavior

That games are not crashing using the nVenc Codec

### Current Behavior

Using OBS with nVenc Codec causes some games to crash for me. When i use x264 i have no game crashes, also without OBS the games are never crashing

### Steps to Reproduce

1. using nVenc Codec
2.
3.
...

### Anything else we should know?

What i tried:
- fresh windows 11 installment
- fresh windows 10 installment to try out if this is there happening too, it is
- graphic driver, bios etc are all up to date
- tried enhanced broadcast feature, games still crashing
- deactivate enhanced broadcast and using the normal nVenc Codec, games are crashing
- tried the lowest settings to make sure settings are not to high, games still crashing
- uninstalled all plugins, games still crashing
- fps i tried 30fps, 48fps, 60fps, no difference
- running obs in administrator mode and without, no difference
- as soon i choose the x264 codec, games are running fine and i can stream for hours without that a single game is crashing
- games that are crashing: call of duty, league of legends, overwatch 2, fortnite, dead by daylight, elden ring
- the game crashes are also happening when i just have obs open without recording or streaming and have the nvenc codec chosen in the settings

since i have no problems when iam playing without nVenc Codec, also without OBS open i highly doubt that this is a graphic cards problem when these issues only happening with the nVenc Codec. This problems started around 7-8 months ago and before i never had any issues with using the nVenc Codec.

**Comment by derrod** [comment]
This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels below, and if it's determined that this is indeed a bug, then we will re-open this issue.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

---

Really just sounds like your system is unstable for whatever reason, we can't fix that on our end.

**Comment by ShirubaPixel** [comment]
so my system is "unstable" when its only happening with the nVenc Codec? WIthout i have 0 problems, 0 crashes but its my system then? k thx for nothing
