### ISSUE TITLE
Impossible to stream to custom SRT with hardware accelerated AV1 encoding

### ISSUE THREAD

**Issue by shmerl** [obsproject/obs-studio#11186]
### Operating System Info

Other

### Other OS

Debian testing Linux

### OBS Studio Version

30.1.2

### OBS Studio Version (Other)

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/DmurwEekqcarLOym

### Expected Behavior

It should be possible to create an SRT stream when encoding happens with hardware acceleration (when using AV1 for example).

### Current Behavior

Currently, to stream something using SRT (as described [here](https://obsproject.com/wiki/Streaming-With-SRT-Or-RIST-Protocols)) there are two options: Stream and Record to custom URL. Neither of those scenarios work with hardware acceleration unfortunately.

More exactly:

* When selecting Streaming and Service: Custom (to stream your own SRT set up), it claims that the only available encoder is x264, so that prevents not only using AV1 but any hardware acceleration encoding too:

![image](https://github.com/user-attachments/assets/d3eb0755-9a31-43ab-b4f7-4caecce8a8ce)

* When using custom recording to an SRT URL, software av1 encoder works, but as known hardware acceleration encoder is completely broken in that set up due to OBS not handling VAAPI set up for it correctly (i.e. `av1_vaapi` there).

In result, there is no way to do it with either option. Can you please enable it either in one or the other?

### Steps to Reproduce

1. Try to Stream or Record to SRT URL while enabling hardware acceleration encoding with AV1

**Comment by derrod** [comment]
SRT in OBS uses MPEG-TS, which does not have standardised support for AV1. As such, this is not supported.

**Comment by shmerl** [comment]
Well, I was using Mastroska, not MPEG-TS since SRT documentation points out that Matroska should work (and Matroska supports AV1 fine).

The problem is not the container, the problem is that OBS doesn't even offer an option to use hardware accelerated encoders for that. I.e. more exactly, it doesn't offer it for "Stream" option and it's broken for custom URL option.

**Comment by Sean-Der** [comment]
@shmerl AV1 via RTP is probably your best bet for lossy scenarios + AV1 today.
