### ISSUE TITLE
No Rec. 709 color space option for Elgato 4K X capture card on Apple Silicon devices

### ISSUE THREAD

**Issue by iamursky** [obsproject/obs-studio#11224]
### Operating System Info

macOS 14

### OBS Studio Version

30.2.2

### OBS Studio Log URL

https://obsproject.com/logs/Fkwfi9fzP61ySaEE

### Expected Behavior

There should be Rec. 709 color space option.

### Current Behavior

There's no Rec. 709 color space option.

<img width="733" alt="Screenshot 2024-08-30 at 14 18 46" src="https://github.com/user-attachments/assets/35e69231-ce1f-45e8-a96b-56357a664c4a">

### Steps to Reproduce

1. Connect Elgato 4K X to a Mac with Apple Silicon
2. Add Elgato 4K X as a Video Capture Device

### Anything else we should know?

A detailed YouTube video about the issue: https://www.youtube.com/watch?v=COVdzFA2Ysk

**Comment by jcm93** [comment]
Elgato's card not offering 709 at this resolution on macOS is an Elgato issue (if they even consider it an issue), and this report should be directed toward them.

**Comment by iamursky** [comment]
Got it, thank you! Submitted a support request to Elgato:

> Hello, I just bought a 4K X capture card and spent some time trying to figure out why the colors on my monitor and recordings appeared greenish. After some investigation, I discovered that the capture card does not support Rec. 709 on Mac with Apple Silicon. This issue is confirmed by users on OBS' GitHub: https://github.com/obsproject/obs-studio/issues/11224. I also found a video on YouTube discussing the issue: https://www.youtube.com/watch?v=COVdzFA2Ysk. I've attached a photo of two monitors with the same settings: the left one is connected through the 4K X capture card, and the right one is connected directly to the computer.

**Comment by jcm93** [comment]
For what it's worth, the 4K X should offer Rec. 709 for lower resolution formats on macOS. As part of your investigation, you may want to check the appearance of your colors against Rec. 709 on lower resolutions, in order to verify that what you're seeing is indeed a result of the incoming buffers being in Rec. 601.

**Comment by iamursky** [comment]
Lowering the resolution in OBS doesn't affect available color space options.

**Comment by jcm93** [comment]
Ah yeah, I was misremembering a different device- looks like all the advertised formats with the 4K X indeed use the Rec. 601 YUV matrix, which is what OBS is checking to determine the color space.
