### ISSUE TITLE
Text Boxes Not Appearing in Capture of AGI Games via ScummVM

### ISSUE THREAD

**Issue by JoLiKMC** [obsproject/obs-studio#11228]
### Operating System Info

Windows 10

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/kHnCI4QyfzUZOihC

### Expected Behavior

Text boxes and other text should always appear in recordings of Adventure Game Interpreter games run through *ScummVM*.

### Current Behavior

On occasion, the text boxes or other instances of text printing within Adventuer Game Interpreter games will fail to be captured.  The text or text windows will, however, display just fine in *ScummVM*.

### Steps to Reproduce

(Note: This may affect other software as well, but this is how *I* did it.)
1. Open *ScummVM*, then open *OBS Studio* and make a new Game Capture window, linking it to *ScummVM*.
2. Open any version of *Space Quest I* (AGI version) in *ScummVM*.
3. Start recording and type anything to generate a text message window.

### Anything else we should know?

As documented [here](https://forums.scummvm.org/viewtopic.php?t=16904), there seems to be a weird visual bug with *ScummVM* while capturing Adventure Game Interpreter engine games under certain setups, such as using *OBS Studio* in "Game Capture" mode.  It's not consistent, or maybe it only happens on certain frames or cycles.  In *OBS*, particularly, the text boxes disappear in both the recording *and* the preview window, but still appear in the *ScummVM* window like nothing's wrong.

I've tested this issue with a couple of different games: *Space Quest, Chapter I* (v1.0x AGI 2.089, v2.2 AGI 2.917) and *King's Quest IV* (v2.0 AGI 3.002.086).  Both of them displayed the same issues with *OBS Studio*.  I tried changing the video settings as well, but that did absolutely nothing.  In all likelihood, this is probably more the fault of *Open Source Broadcaster* than anything, but I figured it was worth sharing since this has happened to at least two other people.

Switching to "Window Capture" in OBS Studio seems to have solved this issue for me.  I also tried recording from *DOSBox* v0.74-3 using Game Capture.  No issues occurred, so something is definitely not meshing with Game Capture and *ScummVM*, in particular.

### Relevant Media
- [Video recording of the bug in action](https://www.youtube.com/watch?v=lFeGVbDm4DQ)

### Related Links
- [*ScummVM* bug report thread](https://bugs.scummvm.org/ticket/15346) (Pretty much the same as this one.)

**Comment by Fenrirthviti** [comment]
This is likely an issue with how ScummVM is rendering outputs;. I doubt we will be able to do much about it. If ScummVM devs determine we're doing something incorrect for support of legacy DX9 capture, this can be reopened with that information.

Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for further assistance.

Thank you!

**Comment by JoLiKMC** [comment]
Counter-points:
1. *ScummVM* uses OpenGL or Surface SDL.  I've been lead to believe that Surface SDL uses whatever version of DirectX is in Windows, up to DirectX 11.
2. This happens with *ScummVM* **regardless** of whether one is using Surface SDL *or* OpenGL.

**Comment by Fenrirthviti** [comment]
The emulator is presenting a d3d9 surface for capture, not d3d11:

```12:36:44.106: [game-capture: 'Game Capture (Other)'] attempting to hook process: scummvm-2.8.1.exe
12:36:44.134: [game-capture: 'Game Capture (Other)'] d3d9 shared texture capture successful
12:36:44.140: [game-capture: 'Game Capture (Other)'] shared texture capture successful
12:36:48.176: [game-capture: 'Game Capture (Other)'] Hooked IDXGISwapChain::Present
12:36:48.176: [game-capture: 'Game Capture (Other)'] Hooked IDXGISwapChain::ResizeBuffers
12:36:48.176: [game-capture: 'Game Capture (Other)'] Hooked IDXGISwapChain1::Present1
12:36:48.176: [game-capture: 'Game Capture (Other)'] Hooked DXGI```

**Comment by JoLiKMC** [comment]
I have done further testing with *ScummVM* and *OBS*.  Here are my results:
- [Testing *ScummVM* with all possible settings.](https://obsproject.com/logs/BT9AjdEYmBqPATBy)
- [Testing Game Capture with a variety of other games.](https://obsproject.com/logs/nawdMuCYJMUs7UWp)

In the first test, you can see there are four recordings:

1. *ScummVM* in "OpenGL" rendering mode, *OBS* in Game Capture mode. (**OpenGL** display with **Direct3D 9** capture.)
2. *ScummVM* in "Surface SDL" rendering mode, *OBS* in Game Capture mode. (**D3D9** display and capture.)
3. *ScummVM* in "OpenGL" rendering mode, *OBS* in Window Capture mode.
4. *ScummVM* in "Surface SDL" rendering mode, *OBS* in WindowCapture mode.

As we can see, it doesn't matter if **OpenGL** or Surface SDL is used.  I don't know if this is going to be of any help whatsoever, but these are the only settings available to me in *ScummVM* and my preferred capture methods in *OBS*.

In the second test, there are seven Game Capture mode recordings (and one failed attempt at capture):

1. *FTL: Faster Than Light* with "Hyperspace" add-on. (**OpenGL** display and capture.)
2. *ECWolf* (a *Wolfenstein 3-D* source port). (**D3D9** display with **DirectX Graphics Infrastructure** capture.)
3. *MegaZeux* 2.93 in "OpenGL2" rendering mode. (**OpenGL** display and capture.)
4. *Free Heroes 2* (a *Heroes of Might & Magic II* reconstruction). (**D3D9** display with **DXGI** capture.)
5. ***Dwarf Fortress* 0.47.05**. (Unable to capture; uses unrecognized renderer?)
6. *Mega Man Maker* 1.7.5.2. (**D3D11** display with **DXGI** capture.)
7. *Rise of the Triad: Ludicrous Edition*. (**D3D11** display with **DXGI** capture.)
8. *Mercenary Kings: Reloaded Edition*. (**OpenGL** display and capture.)

As we can see from *this* test (which was more for my benefit than anything), *OBS Studio* does, indeed, use a variety of display and capture methods when it hooks into various things.  Of note, it uses the DirectX Graphic Infrastructure to do most of the capturing.

Also of note, *ScummVM* tries to capture *directly* from Direct3D 9 rather than using the DXGI, or capturing from "**OpenGL** shared texture", directly.  Again, I'm not sure if this is of *any* help in the slightest, but it was certainly interesting for me to test and read.  It also tells me that you might be onto something; that much like everything else about *ScummVM*… its rendering is a little unconventional.

Thank you for your patience, and I hope these logs are helpful in some way.

**Comment by JoLiKMC** [comment]
Quick update on this: it really _is_ specifically a *ScummVM* issue.  And apparently, it's related to [a known issue](https://bugs.scummvm.org/ticket/15346#comment:5).  So, I apologize?

Anyway, if this wasn't already marked as "can't fix / won't fix", I'd say go ahead and do that.
