### ISSUE TITLE
Using WHIP for live streaming on Twitch, the video is shaking

### ISSUE THREAD

**Issue by CaptainTeemo** [obsproject/obs-studio#11237]
### Operating System Info

macOS 14

### OBS Studio Version

30.2.2

### OBS Studio Log URL

https://obsproject.com/logs/6W10MRhtKl4riwFM

### Expected Behavior

The video is fluent.

### Current Behavior

The video is shaking.

### Steps to Reproduce

1. Use whip protocol for streaming, tested on Twitch here
2. Select the encoder (VT H264 Software/Hardware with bframe checked, x264 with option "bframes=2")
3. Start streaming and view on platform webpage.
4. The video is shaking.

### Anything else we should know?

1. It's probably the b-frame issue.
2. If we uncheck the "Use B-Frames" option on videotoolbox encoder, the video is good.
3. Also, the issue occurs on windows when selecting x264 encoder with option "bframes=2".
4. The RTMPS works good.

The abnormal video is like:
https://github.com/user-attachments/assets/8fd7aaff-3770-43b2-a84e-c323694c5fc3

**Comment by tt2468** [comment]
B-frames are in most cases considered incompatible with WebRTC. Don't use b-frames with WHIP.
