### ISSUE TITLE
obs video capture device function: pull the virtual camera screen black screen

### ISSUE THREAD

**Issue by cHollower** [obsproject/obs-studio#11238]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

OBS-Studio-27.2.4-Full-Installer-x86.exe

### OBS Studio Log URL

https://obsproject.com/logs/o4HAMOlyEZ84LPTW

### Expected Behavior

obs video capture device function: can normally pull the virtual camera screen display

### Current Behavior

Add a video capture device and select virtual camera black screen.
This virtual camera image can be captured using the graphedt.exe tool）

### Steps to Reproduce

1.Add a video capture device and select virtual camera black screen.
(This virtual camera image can be captured using the graphedt.exe tool)

**Comment by WizardCM** [comment]
You are running a very old version of OBS, released over 2 years ago. First, try updating. Secondly, EagleCloud AntiVirus might be conflicting.

This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels below, and if it's determined that this is indeed a bug, then we will re-open this issue.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

**Comment by cHollower** [comment]
log:
17:13:52.131: Video capture device: DecodeDeviceId failed
17:13:52.131: Video capture device: Video configuration failed

What does it represent? Is this error the cause?
