### ISSUE TITLE
device_texture_create (D3D11): Failed to create 2D texture (80070057): The parameter is incorrect. (E_INVALIDARG)

### ISSUE THREAD

**Issue by getkirill** [obsproject/obs-studio#11242]
### Operating System Info

Windows 11

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/EDZ5nPgSDGNSyirU

### Expected Behavior

the game capture supposed to capture game contents (in this case Minecraft)

### Current Behavior

black screen, errors related to dx11 texture creation

### Steps to Reproduce

1. open minecraft 1.21.1
2. try game capture
3. it doesn't work and logs have texture creation fail

**Comment by prgmitchell** [comment]
@getkirill this is not a bug with OBS but a support request which we do not use Github for. You'll want to head over to the community discord server or OBS project forums for help with it.

**Comment by getkirill** [comment]
uh, pretty sure it is?

**Comment by getkirill** [comment]
same behaviour observed in noita

**Comment by notr1ch** [comment]
https://obsproject.com/forum/threads/laptop-black-screen-when-capturing-read-here-first.5965/

**Comment by getkirill** [comment]
the thing is i already tried most of the common fixes
high performance, admin, no scheduler

**Comment by getkirill** [comment]
and reading in the logs that behaviour feels like a bug

**Comment by getkirill** [comment]
noticed that minecraft ran on iGPU, reloading it with dGPU did not fix it
i've exhausted all mentioned fixes in the linked article

**Comment by getkirill** [comment]
compiling source code to check if working tree contains the bug

**Comment by getkirill** [comment]
working tree contains the bug

**Comment by RytoEX** [comment]
Minecraft 1.21.1 captures fine here on Windows 10 with OBS Studio 30.2.3.

**Comment by prgmitchell** [comment]
@getkirill I strongly suggest just heading to the Discord for help, this is not a bug and is solvable.

**Comment by TOWUK** [comment]
`maybe fix, try it`

disable optimization on display > graphics!!!! i have this problem too and my fix is:
![image](https://github.com/user-attachments/assets/26e7ad86-7579-4640-9141-49fe6289efc3)
