### ISSUE TITLE
有核显和独显，但是把视频线插到核显上去obs就会黑屏。

### ISSUE THREAD

**Issue by uzunynw** [obsproject/obs-studio#11241]
### Operating System Info

Windows 10

### OBS Studio Version

30.2.2

### OBS Studio Log URL

https://obsproject.com/logs/O0CBZxEjQNtsHmBw

### Expected Behavior

修好

### Current Behavior

我电脑上有核显和独显，把显示线插到核显上，obs打开就是黑屏的

### Steps to Reproduce

1.有一个核显
2.有一个独显
3.把视频线插到核显
...

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
