### ISSUE TITLE
Unable to use NVENC

### ISSUE THREAD

**Issue by CoffeeShifter** [obsproject/obs-studio#11258]
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/OwRRBQJJdLpzbfnI

### Expected Behavior

I would be able to record using NVENC (any codec)

### Current Behavior

None of the NVENC options work and I get this error:
init_cuda_ctx: CUDA call "cu->cuInit(0)" failed with CUDA_ERROR_UNKNOWN (999): unknown error

### Steps to Reproduce

1. in simple out mode, set recording video encoder to any nvenc option
2. start recording
3.error
...

### Anything else we should know?

Software encoding works

**Comment by lextra2** [comment]
Have you [done this](https://emby.media/community/index.php?/topic/116880-solution-to-installing-nvidia-drivers-on-ubuntu-2204-for-transcoding/)?

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
