### ISSUE TITLE
g++12: -Wenum-conversion and -Werror cause build failure

### ISSUE THREAD

**Issue by stephematician** [obsproject/obs-studio#11256]
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

Git

### OBS Studio Log URL

None - build issue

### OBS Studio Crash Log URL

None - build issue

### Expected Behavior

Should be able to build with existing presets.

### Current Behavior

Build fails with output:

```
obs-studio/shared/properties-view/properties-view.cpp:946:49: error: bitwise operation between different enumeration types ‘QFrame::Shadow’ and ‘QFrame::Shape’ is deprecated [-Werror=enum-conversion]
```

### Steps to Reproduce

1. Install all dependencies as per instructions (including backport of ffmpeg6 for Ubuntu 22.04).
2. Open folder in VSCode.
3. Select "Ubuntu" preset for  CMake.
4. Configure.
5. Build.

**Comment by tytan652** [comment]
https://github.com/obsproject/obs-studio/commit/f1f89a4864a05e508408889035fb7f065b15942d

Support for Qt 6.2 was dropped on master.

**Comment by stephematician** [comment]
Ah, I see. I just installed a local version of Qt 6.7 and I can see how they've worked around it via an operator definition.
