### ISSUE TITLE
OBS 30.2.3 Not Recording

### ISSUE THREAD

**Issue by frumpymussel13** [obsproject/obs-studio#11254]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/Lw1EiljX5hrr1Ix9

### Expected Behavior

It To Start Recording

### Current Behavior

It Said 
Failed to start recording
Starting the output failed. Please check the log for details.
Note: If you are using the NVENC or AMD encoders, make sure your video drivers are up to date.

### Steps to Reproduce

I Really Dont Know I Was Changed From Admin To Standard Then Back To Admin
When I Use Software Encoding It Works.

### Anything else we should know?

no

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
