### ISSUE TITLE
Trying to install OBS through Flatpak on Raspberry Pi gives `error: Nothing matches com.obsproject.Studio in remote flathub` 

### ISSUE THREAD

**Issue by anandijain** [obsproject/obs-studio#11261]
### Operating System Info

Other

### Other OS

Raspberry Pi OS - Debian GNU/Linux 12 (bookworm)

### OBS Studio Version

Other

### OBS Studio Log URL

n/a

### Expected Behavior

I thought I would be able to install OBS 

### Current Behavior

```
anand@anand-rpi:~ $ flatpak install flathub com.obsproject.Studio
Looking for matches…
error: Nothing matches com.obsproject.Studio in remote flathub
```

### Steps to Reproduce

Try installing OBS through flatpak on a Raspberry Pi 5 

### Anything else we should know?

Thanks!

**Comment by derrod** [comment]
There is no ARM version available for Linux (or Windows) yet.

**Comment by anandijain** [comment]
If I try to manually install through a Flatpak file

I get
```
anand@anand-rpi:~/Downloads $ flatpak install com.obsproject.Studio.flatpakref
error: No such ref 'app/com.obsproject.Studio/aarch64/stable' in remote flathub
```

Ah just got your comment, any discussion post to follow that tracks getting that working?

**Comment by derrod** [comment]
See https://github.com/obsproject/obs-studio/pull/9979 for the ongoing effort to provide aarch64 builds via Flatpak.
