### ISSUE TITLE
"MacOS Screen Capture" does not correctly restart capturing when restarting the game

### ISSUE THREAD

**Issue by lesha-co** [obsproject/obs-studio#11276]
### Operating System Info

macOS 14

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/wBdkxuHBQqHoywWa

### Expected Behavior

When restarting the game that I've added as a source, OBS should restart window capturing

### Current Behavior

OBS forgets the window 

### Steps to Reproduce

1. Add "MacOS Screen Capture" source with following settings
  - method: Window Capture 
  - window: any window, fullscreen or not 

(the window is correctly added to the scene)

2. Restart the application that you've added

(OBS shows freeze frame from before you've exited the application, and doesn't restart the capture)

3. enter "MacOS Screen Capture" settings again

Window dropdown shows whatever is first in the list instead of whatever you've selected in (1), "Restart capture" button is disabled. Manually selecting the window helps, but that's what the button is there for, isn't it

**Comment by gxalpha** [comment]
As you have correctly identified, this is expected and intended. If you close an app and open it again, it's a different window, so window capture does not pick it up.

If you want your app to stay captured, consider using Application Capture instead.

**Comment by lesha-co** [comment]
I would love to, but the "expose" function on macOS affects recording 

<img width="1505" alt="image" src="https://github.com/user-attachments/assets/3e41b5b2-2981-4cfe-895a-1fbc7a59e4df">


it's almost like Application Capture captures entire screen, ignoring all other windows

**Comment by gxalpha** [comment]
Is your screenshot from Application Capture? I.e., does that show other apps even though it shouldn't?
In that case, yes, please open another bug with specific information on your version of macOS and specific steps to reproduce. It's unlikely we would be able to solve that ourselves but might be able to raise it with Apple.
