### ISSUE TITLE
win-wasapi regression: no desktop or microphone audio monitor on windows 10.

### ISSUE THREAD

**Issue by vincuo70** [obsproject/obs-studio#11274]
### Operating System Info

Windows 10

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/KQKp0TPkHGI0tqUD

### Expected Behavior

On same target machine, an older version of obs studio (30.1.2) the desktop audio or microphone are monitored and recorded. The module win-wasapi is correctly loaded, see log [https://obsproject.com/logs/NRLyxLB6HAawvVlK](https://obsproject.com/logs/NRLyxLB6HAawvVlK), rows at 08:57:18.832 and 08:57:18.848.

### Current Behavior

On same target machine, the current version of obs studio (30.2.2) the desktop audio or microphone aren't monitored or recorded. The module win-wasapi is NOT correctly loaded with error "Failed to initialize audio client: 80070057", see log [https://obsproject.com/logs/KQKp0TPkHGI0tqUD](https://obsproject.com/logs/KQKp0TPkHGI0tqUD), rows at 09:06:42.391 and 09:06:42.403

### Steps to Reproduce

1. Install obs studio (30.1.2) on windows
2. Check the desktop audio monitor and microphone are listening (levels move)
3. Uninstall obs sudio (checking clear settings) and install the last 30.2.3.
4. Now the desktop audio monitor and microphone are mute (no move of the levels)

### Anything else we should know?

Windows 10 machine have the last patchs applied yesterday.
The machine also is behind a firewall that filter twitch or other gaming streams.

**Comment by vincuo70** [comment]
Windows 10 machine have the last patchs applied yesterday.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by vincuo70** [comment]
Feel free to close, but isn't a support request because the previous release is working. I will try on another Windows 10 machine.

**Comment by Fenrirthviti** [comment]
I have tested on a Windows 10 machine and everything is working fine, so there is something specific to your setup causing the issue. Support will help determine what that is, and if it is determined there is some specific configuration or setup that causes this, this can be reopened.

As it stands, this is not actionable without more information, and we prefer that happens through the support channels.

**Comment by vincuo70** [comment]
Tested on three machine in office, all three behind the same firewall. Same behaviour. I think it's some network related issue on first startup and auto configuration. I will reopen this when I have more information and I have steps to reproduce on a windows machine without firewall.
