### ISSUE TITLE
The following packages have unmet dependencies.

### ISSUE THREAD

**Issue by ivostoykov** [obsproject/obs-studio#11285]
### Operating System Info

Ubuntu 24.04

### OBS Studio Version

30.2.3

### OBS Studio Log URL

n/a - installation failed

### OBS Studio Crash Log URL

not available

### Expected Behavior

install properly

### Current Behavior

$ sudo apt install obs-studio
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 libpython3.12t64 : Depends: libpython3.12-stdlib (= 3.12.3-1ubuntu0.1) but 3.12.5-1+jammy1 is to be installed
E: Unable to correct problems, you have held broken packages.

### Steps to Reproduce

1. add PPA if not exists with `sudo add-apt-repository ppa:obsproject/obs-studio`
2. install with `sudo apt install obs-studio`

### Anything else we should know?

The system was upgraded from 22.04 LTS to 24.04.
Fully updated & upgraded
No broken packages
No errors (I can find)

**Comment by Penwy** [comment]
The issue is your apt sources are still using the 22.04 PPAs.
`3.12.5-1+jammy1 is to be installed` means it's going to install the 22.04 (jammy jellyfish) version, which it shouldn't do on 24.04.
Fix your sources and try again.

**Comment by derrod** [comment]
You'll need to fix the PPA in you repo list.
