### ISSUE TITLE
Can't CLick and Drag Sources

### ISSUE THREAD

**Issue by alkaris2** [obsproject/obs-studio#11287]
### Operating System Info

Other

### Other OS

Manjaro 24.0.7

### OBS Studio Version

Other

### OBS Studio Version (Other)

 obs-studio-tytan652 30.2.3-1

### OBS Studio Log URL

https://obsproject.com/logs/LgvaBERs1uVitfQO

### Expected Behavior

Can't click and drag sources into groups. I add a source to my scenes, and I create a group for one, but then I can't click and drag that Source into Groups. This is not the first time this was disabled in previous OBS versions because of unrelated crash issues on other platforms, and now it's disabled again without reason.

### Current Behavior

Click and dragging sources does not work at all because you've gone and disabled it. in the latest versions.

### Steps to Reproduce

1. Add Source to Scenes
2. Add Group to Scenes
3. Drag Source into Group
4. Does not work.

### Anything else we should know?

How do I re-enable clicking and dragging of sources into groups in OBS again?

**Comment by kkartaltepe** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
