### ISSUE TITLE
Video artifacts

### ISSUE THREAD

**Issue by NAAIN** [obsproject/obs-studio#11286]
### Operating System Info

Other

### Other OS

Arch linux

### OBS Studio Version

Other

### OBS Studio Version (Other)

OBS 30.2.1-1 (linux)

### OBS Studio Log URL

https://obsproject.com/logs/Z7PoWJbzMD7xSoZG

### Expected Behavior

all frames in the video are intact and unbroken

### Current Behavior

all frames in the video are torn as if with no vertical synchronization

### Steps to Reproduce

Updated arch with pacman -Syu

### Anything else we should know?

No artifacts before system upgrade

Screenshot of artifacts: ![Снимок экрана от 2024-09-14 20-12-34](https://github.com/user-attachments/assets/e90d458f-681d-4ea5-b0a7-7aaccdda0908)

Mesa and mesa-vdpau version is 24.2.2-1
Kernel version is 6.9.5-arch1-1

P.S. I downgraded obs to 30.1.2-2 and everything was fine

**Comment by kkartaltepe** [comment]
mesa is broken with texture encoding, downgrading to before that was added can be a workaround until a fixed mesa is released.
