### ISSUE TITLE
Exposure ranges are weird

### ISSUE THREAD

**Issue by juanfelipegiraldoc** [obsproject/obs-studio#11289]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.3

### OBS Studio Version (Other)

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/Pw54R4ROdxA5GbqJ

### Expected Behavior

Manual exposure range should be from 1 to 16. As you can see below, the minimum value should be 1 and maximum 16.
![Screenshot 2024-09-16 114622](https://github.com/user-attachments/assets/cd414ef3-5d42-4e56-9873-dadc89893c4f)

### Current Behavior

Manul exposure range shows up from -13 to -9.
![Screenshot 2024-09-16 114412](https://github.com/user-attachments/assets/d0d2a78e-c755-47df-878f-1efd58257821)
![Screenshot 2024-09-16 114423](https://github.com/user-attachments/assets/ef35db73-248c-458e-9fda-fd176b2b445f)

When -13 it sends the index '1d'
When -12 it sends the index '2d'
When -11 it sends the index '5d'
When -10 it sends the index '10d'
When -9 it sends the index '16d'

So at the end it recognizes the range is 1 to 16, but there are some missing indexes.

Other than that, something that I'm not sure if it's normal when I move the slider from '-10' to '-9' in manual exposure, it sends the following commands in the order below:
1. Auto exposure requests.
2. Set auto exposure
3. Set manual exposure
4. Auto exposure requests
5. Set auto exposure
6. Set manual exposure 

The debug messages below show this behavior, but it seems too much just for changing 1 value in manual exposure. If I move the slider 2 values, it's 12 requests in a row, which sometimes kills my camera.

(11:59:05.718) <CR>Auto Exposure 
(11:59:05.718) <CR>GET_CUR
(11:59:05.718) <CR>USBStpCB:VCI GET_REQ - RequestOption: 0x1, Value sent: [byte 0] 0x1 (hex)
(11:59:05.718) <CR>USBStpCB:VCI GET_REQ - RequestOption: 0x1, Value sent: [byte 0] 1 (uint8_t)
(11:59:05.718) <CR>USBStpCB:VCI GET_REQ - RequestOption: 0x1, Value sent: [byte 0] 1 (int8_t)
(11:59:05.718) <CR>USBStpCB:VCI GET_REQ - RequestOption: 0x1, Value sent: [byte 1] 0x0 (hex)
(11:59:05.718) <CR>USBStpCB:VCI GET_REQ - RequestOption: 0x1, Value sent: [byte 1] 0 (uint8_t)
(11:59:05.718) <CR>USBStpCB:VCI GET_REQ -  RequestOption: 0x1, Value sent: [byte 1] 0 (int8_t)
(11:59:05.718) <CR>Auto Exposure 
(11:59:05.718) <CR>USBStpCB:VCI SET_CUR_REQ - Value received: [byte 0] 0x0 (hex)
(11:59:05.718) <CR>USBStpCB:VCI SET_CUR_REQ - Value received: [byte 0] 0 (uint8_t)
(11:59:05.718) <CR>USBStpCB:VCI SET_CUR_REQ - Value received: [byte 0] 0 (int8_t)
(11:59:05.718) <CR>USBStpCB:VCI SET_CUR_REQ - Value received: [byte 1] 0x0 (hex)
(11:59:05.718) <CR>USBStpCB:VCI SET_CUR_REQ - Value received: [byte 1] 0 (uint8_t)
(11:59:05.718) <CR>USBStpCB:VCI SET_CUR_REQ - Value received: [byte 1] 0 (int8_t)
(11:59:05.718) <CR>USBStpCB:VCI SET_CUR_REQ - Total readCount: 1
(11:59:05.718) <CR>set Auto exposure = 1<CR>
(11:59:05.718) <CR>
(11:59:05.718) Register = 0x5002: Value = 0x29C
(11:59:05.718) <CR>Manual Exposure 
(11:59:05.718) <CR>USBStpCB:VCI SET_CUR_REQ - Value received: [byte 0] 0x0 (hex)
(11:59:05.718) <CR>USBStpCB:VCI SET_CUR_REQ - Value received: [byte 0] 0 (uint8_t)
(11:59:05.718) <CR>USBStpCB:VCI SET_CUR_REQ - Value received: [byte 0] 0 (int8_t)
(11:59:05.718) <CR>USBStpCB:VCI SET_CUR_REQ - Value received: [byte 1] 0x0 (hex)
(11:59:05.718) <CR>USBStpCB:VCI SET_CUR_REQ - Value received: [byte 1] 0 (uint8_t)
(11:59:05.718) <CR>USBStpCB:VCI SET_CUR_REQ - Value received: [byte 1] 0 (int8_t)
(11:59:05.718) <CR>USBStpCB:VCI SET_CUR_REQ - Total readCount: 4
(11:59:05.718) <CR>set Manual exposure = 16<CR>
(11:59:05.718) <CR>
(11:59:05.718) Register = 0x5002: Value = 0x290<CR>
(11:59:05.718) Register = 0x500C: Value = 0x3E8<CR>
(11:59:05.718) Register = 0x5006: Value = 0x1000
(11:59:05.919) <CR>Auto Exposure 
(11:59:05.919) <CR>GET_CUR
(11:59:05.919) <CR>USBStpCB:VCI GET_REQ - RequestOption: 0x1, Value sent: [byte 0] 0x1 (hex)
(11:59:05.919) <CR>USBStpCB:VCI GET_REQ - RequestOption: 0x1, Value sent: [byte 0] 1 (uint8_t)
(11:59:05.919) <CR>USBStpCB:VCI GET_REQ - RequestOption: 0x1, Value sent: [byte 0] 1 (int8_t)
(11:59:05.919) <CR>USBStpCB:VCI GET_REQ - RequestOption: 0x1, Value sent: [byte 1] 0x0 (hex)
(11:59:05.919) <CR>USBStpCB:VCI GET_REQ - RequestOption: 0x1, Value sent: [byte 1] 0 (uint8_t)
(11:59:05.919) <CR>USBStpCB:VCI GET_REQ -  RequestOption: 0x1, Value sent: [byte 1] 0 (int8_t)
(11:59:05.919) <CR>Auto Exposure 
(11:59:05.919) <CR>USBStpCB:VCI SET_CUR_REQ - Value received: [byte 0] 0x0 (hex)
(11:59:05.919) <CR>USBStpCB:VCI SET_CUR_REQ - Value received: [byte 0] 0 (uint8_t)
(11:59:05.919) <CR>USBStpCB:VCI SET_CUR_REQ - Value received: [byte 0] 0 (int8_t)
(11:59:05.919) <CR>USBStpCB:VCI SET_CUR_REQ - Value received: [byte 1] 0x0 (hex)
(11:59:05.919) <CR>USBStpCB:VCI SET_CUR_REQ - Value received: [byte 1] 0 (uint8_t)
(11:59:05.919) <CR>USBStpCB:VCI SET_CUR_REQ - Value received: [byte 1] 0 (int8_t)
(11:59:05.919) <CR>USBStpCB:VCI SET_CUR_REQ - Total readCount: 1
(11:59:05.919) <CR>set Auto exposure = 1<CR>
(11:59:05.919) <CR>
(11:59:05.919) Register = 0x5002: Value = 0x29C
(11:59:05.919) <CR>Manual Exposure 
(11:59:05.919) <CR>USBStpCB:VCI SET_CUR_REQ - Value received: [byte 0] 0x0 (hex)
(11:59:05.919) <CR>USBStpCB:VCI SET_CUR_REQ - Value received: [byte 0] 0 (uint8_t)
(11:59:05.919) <CR>USBStpCB:VCI SET_CUR_REQ - Value received: [byte 0] 0 (int8_t)
(11:59:05.919) <CR>USBStpCB:VCI SET_CUR_REQ - Value received: [byte 1] 0x0 (hex)
(11:59:05.919) <CR>USBStpCB:VCI SET_CUR_REQ - Value received: [byte 1] 0 (uint8_t)
(11:59:05.919) <CR>USBStpCB:VCI SET_CUR_REQ - Value received: [byte 1] 0 (int8_t)
(11:59:05.919) <CR>USBStpCB:VCI SET_CUR_REQ - Total readCount: 4
(11:59:05.919) <CR>set Manual exposure = 16<CR>
(11:59:05.919) <CR>
(11:59:05.919) Register = 0x5002: Value = 0x290<CR>
(11:59:05.919) Register = 0x500C: Value = 0x3E8<CR>
(11:59:05.919) Register = 0x5006: Value = 0x1000

### Steps to Reproduce

1. Open the properties of the camera
2. Check the manual exposure ranges

### Anything else we should know?

All the Processing Unit Descriptors work perfectly (Brightness, contrast, saturation, etc), same as the Input (Camera) Terminal Descriptor (like zoom, or auto exposure). The only one not setting the range correctly is manual exposure.

**Comment by Fenrirthviti** [comment]
Those options are provided by your webcam driver, not OBS.

**Comment by juanfelipegiraldoc** [comment]
I'm the developer, as you can see I'm sending 1 as minimum and 16 as the maximum and it works for all the other properties. The only one failing is manual exposure.

**Comment by notr1ch** [comment]
That dialog is from DirectShow, which relies on the camera driver or provides a generic one if not implemented. The only influence OBS has it that it asks DirectShow to open the camera properties dialog.

**Comment by mirh** [comment]
https://github.com/m-riley04/QtCameraControls
This could probably provide a good test platform to see what's screwed up.
