### ISSUE TITLE
OBS UI is very glitchy, but still functional

### ISSUE THREAD

**Issue by jadenquinn** [obsproject/obs-studio#11294]
### Operating System Info

Windows 10

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/nyckLelB9jbfzDfA

### Expected Behavior

No white crap on the UI.

### Current Behavior

![image](https://github.com/user-attachments/assets/cbaf6473-7eb9-4432-824c-c33a2b1d7765)

### Steps to Reproduce

No idea. I honestly just started OBS up one day and it started doing this. I was trying to capture Borderlands 2.

### Anything else we should know?

Note: This is a BUG WITH OBS, and NOT a SUPPORT REQUEST. DO NOT classify this issue as a SUPPORT REQUEST. Fix the issue. I checked all the things as is required to be helped in the Discord, and no one was able to tell me what was wrong or how to fix it. I was also instructed to go over the 'FAQ' list of things to check before submitting a thing, and none of them rang any bells.

My setup is fairly standard. I have an RTX 2070 SUPER that I am using for my monitor. My "2nd monitor" is just there to get the audio stream from the HDMI port to the AVR, or my speakers won't work. This didn't cause the issue, since I had been doing this for months up to the point of OBS breaking.

Recently (maybe after I updated my GPU drivers), the UI became slightly less glitchy than before, the menu now appears. The white blocks are still there, but now the menu is back, so something got fixed a little.

"Resetting" OBS did nothing. (new profile)
Reinstalling OBS did nothing.
Downgrading OBS did nothing, but I only went down a couple versions. OBS 29 still works fine, it's something y'all did for 30 that broke something.

I also determined that I could continue to actually use this glitched as hell OBS installation by choosing a different Capture Method, now the "Windows 10 (1903 and up)" option is the only one that works. Automatic and DXGI Desktop Duplication don't work anymore. I'm assuming that means it has something to do with how you guys are utilizing DirectX..? idk. Just fix the bug.
I looked up this DXGI problem and I got threads from years ago that mention having loads of plugins that caused issues, which I have absolutely none of. I have zero plugins.

**Comment by jadenquinn** [comment]
![image](https://github.com/user-attachments/assets/c7bf2e11-d28a-4097-8942-d5d772a1a39f)

I fixed it. You guys broke something related to high-DPI stuff.

**Comment by prgmitchell** [comment]
@jadenquinn yes you had manually set the program to override the DPI scaling behavior (this is not what is set by default), I was in the middle of typing this when you responded again. This isn't anything controlled by OBS though, it is handled by QT which is what the UI for OBS is built in.

**Comment by jadenquinn** [comment]
> @jadenquinn yes you had manually set the program to override the DPI scaling behavior (this is not what is set by default), I was in the middle of typing this when you responded again. This isn't anything controlled by OBS though, it is handled by QT which is what the UI for OBS is built in.

Then they should fix it. You guys should let them know this is a problem XD

**Comment by prgmitchell** [comment]
> > @jadenquinn yes you had manually set the program to override the DPI scaling behavior (this is not what is set by default), I was in the middle of typing this when you responded again. This isn't anything controlled by OBS though, it is handled by QT which is what the UI for OBS is built in.
> 
> Then they should fix it. You guys should let them know this is a problem XD

There is nothing to fix from them, unchecking the box to override the DPI scaling behavior that you had checked in the past is the fix.

**Comment by Fenrirthviti** [comment]
DPI scaling in Qt is sketchy at best, there is definitely something for them to fix somewhere. These issues are already well documented on their end, and has been for years. There isn't much more we can do.

In the future, please refrain from passive aggressive issue reports. I understand that you are frustrated by this problem, but making a post with an aggressive attitude is a great way to discourage community members and contributors from looking at reports. We are much more likely to engage with users who are respectful and willing to work with us, than someone who is shouting at us to fix something that isn't even our fault.

**Comment by jadenquinn** [comment]
> DPI scaling in Qt is sketchy at best, there is definitely something for them to fix somewhere. These issues are already well documented on their end, and has been for years. There isn't much more we can do.
> 
> In the future, please refrain from passive aggressive issue reports. I understand that you are frustrated by this problem, but making a post with an aggressive attitude is a great way to discourage community members and contributors from looking at reports. We are much more likely to engage with users who are respectful and willing to work with us, than someone who is shouting at us to fix something that isn't even our fault.

I was told VERY different things before, and was left in the dark for a while, and kept reaching out, despite being pushed aside over and over. I hate when this happens, and I feel like I'm more than justified in being a lil pissed off by this situation. I use OBS to get things done, not having it work is unacceptable. If y'all looked further than just the top of the page the first couple times before closing the issue, this wouldn't have happened and I wouldn't have to be rude to get someone to look at the issue. Constant problem in the open source community.

**Comment by alinsavix** [comment]
The responses to the other tickets you opened made some suggestions for fixes, and when they didn't pan out, suggested you hit up the normal support channels for further help, to try to figure out the actual problem. Did you? If not, how do you expect anyone to be able to help with your problem? When one person out of thousands runs into an issue and refuses to even work with the folks that might be able to help them, to figure out what the actual issue is (instead, just opening more tickets with no additional useful information), what do you expect?

Your problem can't get fixed without people understanding what causes it. Figuring out what causes it requires actually working _with_ people that can help you, not just jumping up and down in a ticket going "FIX IT FIX IT". Even the best support in the world won't be able to take any useful action on a bug report where there are no real reproduction steps available and the user refuses to engage with the normal support channels to try to figure out more about what's happening.

And no, you're not justified in being pissed off. You weren't pushed aside, you were told where to go to be able to get help. Best I can tell (I might be missing it if you logged into discord with a username significantly different than your username here), you never did that.

And I get all sorts of great support in the open source community. I don't think I've ever needed to be rude at all. Maybe my experience (over the course of 30 years) is unusual, but I kinda doubt it.

Finally, if you don't like the quality of the free support (that it seems you never actually used) available for the free software you're using, I might suggest that there are plenty of companies and software packages that would gladly allow you to pay them to get less "unacceptable" support.

Best of luck.

**Comment by jadenquinn** [comment]
> The responses to the other tickets you opened made some suggestions for fixes, and when they didn't pan out, suggested you hit up the normal support channels for further help, to try to figure out the actual problem. Did you? If not, how do you expect anyone to be able to help with your problem? When one person out of thousands runs into an issue and refuses to even work with the folks that might be able to help them, to figure out what the actual issue is (instead, just opening more tickets with no additional useful information), what do you expect?
> 
> 
> 
> Your problem can't get fixed without people understanding what causes it. Figuring out what causes it requires actually working _with_ people that can help you, not just jumping up and down in a ticket going "FIX IT FIX IT". Even the best support in the world won't be able to take any useful action on a bug report where there are no real reproduction steps available and the user refuses to engage with the normal support channels to try to figure out more about what's happening.
> 
> 
> 
> And no, you're not justified in being pissed off. You weren't pushed aside, you were told where to go to be able to get help. Best I can tell (I might be missing it if you logged into discord with a username significantly different than your username here), you never did that.
> 
> 
> 
> And I get all sorts of great support in the open source community. I don't think I've ever needed to be rude at all. Maybe my experience (over the course of 30 years) is unusual, but I kinda doubt it.
> 
> 
> 
> Finally, if you don't like the quality of the free support (that it seems you never actually used) available for the free software you're using, I might suggest that there are plenty of companies and software packages that would gladly allow you to pay them to get less "unacceptable" support.
> 
> 
> 
> Best of luck.

I used the Discord support channel. It took me like an hour to get anyone to respond to me, and no one found a solution.

OBS was broken for a month, and when you do what I do, that's simply not ok. I would pay for OBS, but unfortunately it's open source software. Sadly, none of the paid options are replacements for OBS, either.

Whenever I have to contact support, usually I have to push a bit before I get anything useful. Just how it is. Some, like yourself, might be luckier than I am, or just give the exact right information needed or something, idk.

Having an issue closed by reason of "go to the Discord for help" is being pushed aside. That's not a solution. That's like calling a company when you actually need info, and you keep having to call back getting bumped one higher on the chain on who you're talking to, except in this case I'm being bumped down. And I DID go through with it, because again, I need OBS to work.

I gave enough info, all the info I had. If y'all needed more, questions might help. Working _with_ someone goes both ways.
Wtf am I supposed to do when my ticket gets closed for what I determine to be a bullcrap reason that doesn't make sense? I open a new one, because again, I'm am partially dependent on OBS to do what I do. If someone asked me a question, I would work with them, but I instead just got my tickets closed and no more. How am I supposed to work with someone who I don't even know is there..

As an act of desperation, I was screwing with all of my DPI-related display settings for the machine and the OBS executable itself, and I did end up fixing it.

https://youtu.be/ky6q1zXmltg?si=zhnmGT5eE2dWj2c2


Many people use this software as a professional, it's time to either step up support, or make a paid version with better support, because relying on community efforts clearly isn't enough.
