### ISSUE TITLE
AMD GPU Encoders on OBS overutilize GPU on RX 7900 XT

### ISSUE THREAD

**Issue by pompompur1nn** [obsproject/obs-studio#11303]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/Gk84BNkUAGHSAGlJ

### Expected Behavior

Normal GPU usage, 2 to 3 percent usually.

### Current Behavior

Very high GPU usage, around 60-80%.

### Steps to Reproduce

1. Set encoder as AMD HVEC or H.264, (for some reason, av1 is perfectly fine)
2. No scene required, recording nothing returns absurd GPU usage
3. Tada!!!!

### Anything else we should know?

This seems to only happen on a 7900 XT, as I upgraded from a 7600 and nothing of the nature happened. 
(update, trying to reproduce the bug after setting your encoder to software miraculously fixes it?? i think this is a GPU bug)

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
