### ISSUE TITLE
Youtube Live Control Panel is not logged in by default for some resean when logging in though the standard stream youtube acount connection

### ISSUE THREAD

**Issue by derric-young** [obsproject/obs-studio#11305]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/qzRRO0ZIOR82SYli

### Expected Behavior

it should auto log in with every other youtube acount thingy when linking a youtube acount

### Current Behavior

the live control panel shows the google acount sign in page
![image](https://github.com/user-attachments/assets/6badfd5c-87f1-4bd0-88e9-e54bff9126cf)

### Steps to Reproduce

1. log into youtube acount in obs stream connection settings (make sure it is acually logged in with the manege stream button being there)
2. check youtube live control panel. thats it

### Anything else we should know?

i was using the steam version altho im pretty sure the non steam version and the steam version have the exact same builds as far as im aware

**Comment by Fenrirthviti** [comment]
This is currently expected, as the login flow for the control panel has a separate flow. This is currently a limitation imposed by YouTube.
