### ISSUE TITLE
The encoder is overloaded

### ISSUE THREAD

**Issue by madKULOLO** [obsproject/obs-studio#11309]
### Operating System Info

Windows 10

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/jGyvpydY51DxG7Yf

### Expected Behavior

корректная, стабильная работа

### Current Behavior

После обновления на последнюю актуальную версию начались проблемы перегруженного кодировщика.
ранее:
использовался открытый браузер 5-7 вкладок, настройки стриминга высокие, 2 монитора 1080p 60fps - проблем не наблюдалось.
Сейчас при открытии 2 и более вкладок - кодировщик перегружается.

### Steps to Reproduce

1. Запуск стрима
2. Включение сцены с браузером
3. Стриминг вкладки браузера

### Anything else we should know?

загрузка процессора и видеокарты при стриме
![Taskmgr_Mc7VnYTVuH](https://github.com/user-attachments/assets/6f022a8c-363e-40b8-a265-3af1900e61eb)

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
