### ISSUE TITLE
OBS on Debian 12 KDE Wayland, Pipewire not capturing screen Flathub

### ISSUE THREAD

**Issue by dannyp9000** [obsproject/obs-studio#11314]
### Operating System Info

Other

### Other OS

Debian 12 KDE Wayland

### OBS Studio Version

30.2.3

### OBS Studio Version (Other)

https://flathub.org/apps/com.obsproject.Studio

### OBS Studio Log URL

https://flathub.org/apps/com.obsproject.Studio

### Expected Behavior

Black Screen, unable to see screen. Look at picture below:

### Current Behavior

1. Turn on OBS Studio
2. Enable Screen Capture on Display #1
3. Black Screen, unable to see screen.

### Steps to Reproduce

1. Turn on OBS Studio
2. Enable Screen Capture on Display #1
3. Black Screen, unable to see screen.

### Anything else we should know?

AMD CPU 5000 series
AMD GPU 6900xt

![image](https://github.com/user-attachments/assets/08a5d3cc-9ad3-408b-aac6-bf4b46350592)

**Comment by mihawk90** [comment]
If your portal isn't capturing anything there is nothing OBS can do about it.

Report it to your distro's Bug Tracker. Debian has been shipping broken Portals for a while.

**Comment by mihawk90** [comment]
As I said, your distro's bugtracker. IDK where Debian tracks theirs but it's likely on their website somewhere.

**Comment by kkartaltepe** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
