### ISSUE TITLE
Preview Window doesn't show PC game, when using Window Capture

### ISSUE THREAD

**Issue by CrimsonFox762** [obsproject/obs-studio#11313]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/cTgtC2DJ0ASOEOgp

### Expected Behavior

The window for the PC game showing up in the Preview window, and the game showing on stream for Twitch and Youtube, without it being an black screen during the stream

### Current Behavior

I loaded up the PC game, and it shows an red border of the game in the Preview window with 2 white rectangles

![Screenshot 2024-09-25 124936](https://github.com/user-attachments/assets/272f48c9-9794-4bf5-ab7a-c20319b3257d)

### Steps to Reproduce

1. Open OBS Studio, and have an scene with Window Capture
2. Open an random PC game and set the window in OBS to the PC
3. Click on the window for the PC game
4. Go back to OBS and look at the preview window to see what it shows on the screen

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
