### ISSUE TITLE
OBS Studio Microsoft store reported version 27.2.4 but installed version 30.1.0 (Intune)

### ISSUE THREAD

**Issue by TjerkvGerwen** [obsproject/obs-studio#11323]
### Operating System Info

Windows 11

### OBS Studio Version

Other

### OBS Studio Log URL

https://obsproject.com/logs/Hu7wTVHxJksGR0OC

### Expected Behavior

no popup thats an update is needed because the newer version is installed and not the reported 27.2.4

### Current Behavior

Gives popup after first startup that there is a newer version that needs to be installed 

### Steps to Reproduce

1. Addd Intune New store app
2. Install store app on device
3. start OBS Studio
...

**Comment by Fenrirthviti** [comment]
The latest supported 64-bit version of OBS Studio in the Microsoft store is 30.2.2. If your environment is trying to install 32-bit, you would receive the last version (27.2.4) that supported 32-bit before support was dropped. Newer versions than 27.2.4 do not support 32-bit, I would recommend updating local packages to target the correct bitness for your environment.

This sounds like a local environment issue, please reach out to your IT department to have them update the package to 64-bit.
