### ISSUE TITLE
The source properties window and filter window rendering screen are different from the actual resource

### ISSUE THREAD

**Issue by zengdaqin** [obsproject/obs-studio#11326]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.3

### OBS Studio Log URL

no

### Expected Behavior

The source properties window and filter window render the **same** as the actual resource

### Current Behavior

The source properties window and filter window rendering screen are **different** from the actual resource

### Steps to Reproduce

1. add image or media source
2. open Filters or Properties windows
3. check preview

![111](https://github.com/user-attachments/assets/89cea55c-2b6d-482e-a57e-7787f94b5ded)
![160613](https://github.com/user-attachments/assets/92376bd3-ff10-4a0a-8189-a0183dcaf73d)

### Anything else we should know?

I have a desktop computer and it works fine, but the above phenomenon only occurs on a laptop. 
This is the laptop configuration:
Manufacturer : Dell Inc , 
Win11
System Model : Vostro 5620
CPU	        12th Gen Intel(R) Core(TM) i7-1260P   2.10 GHz
RAM	32.0 GB 
GPU         Intel(R) UHD Graphics
The display supports HDR video streaming, but does not support HDR.
log:
[2024-09-29 16-48-08.txt](https://github.com/user-attachments/files/17178609/2024-09-29.16-48-08.txt)

**Comment by Fenrirthviti** [comment]
I have tested this on both a desktop and laptop, and cannot reproduce the behavior described here. I'd recommend checking that all drivers are up-to-date.

As it stands, this is not actionable without further information on how to reproduce, as it appears to be an environment-specific issue, and not with OBS itself.

If more information can be provided on how to reproduce, we can reopen this.
