### ISSUE TITLE
UI suggestions

### ISSUE THREAD

**Issue by hologerry** [obsproject/obs-studio#11338]
### Operating System Info

macOS 14

### Other OS

macOS 15

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/cCVLoC5OBtYmgifn

### Expected Behavior

1. The padding space should be larger, or put to the right side.
<img width="880" alt="OBS Studio 2024-10-03 04 07 31" src="https://github.com/user-attachments/assets/cb1d048c-c717-4d25-9d40-c5159bd7a9b0">

2. The line in value changer should be removed, the 'up' and 'down' are not the same size.
<img width="89" alt="OBS Studio 2024-10-03 04 10 48" src="https://github.com/user-attachments/assets/e5a445d5-4815-476b-ac05-6f4ad67f2424">

### Current Behavior

1. the space is too narrow, or should be on the right
2. the value changer's behavior is weird by hovering on it.

### Steps to Reproduce

1. Install the latest version macOS app.
2. See the icon in the title of the dock modules
3. See the value changer, hover on it

**Comment by Fenrirthviti** [comment]
Please use our [Ideas Page](https://ideas.obsproject.com/) for suggestions. GitHub is reserved for verified bug reports.

Thank you!
