### ISSUE TITLE
OBS Crash with obs-browser.dll exception

### ISSUE THREAD

**Issue by Manu2001tek** [obsproject/obs-studio#11335]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://pastebin.com/G57EQYUa

### OBS Studio Crash Log URL

https://pastebin.com/xbYcSPna

### Expected Behavior

Working well without crashing

### Current Behavior

Crash often on startup but crashed yesterday during live streaming

### Steps to Reproduce

1. Start OBS
2. NVIDIA Broadcast launches too
3. Boom. crashed
4. After OBS restart the application works good

### Anything else we should know?

Nope

**Comment by Fenrirthviti** [comment]
Crash log indicates that browser source is not crashing, but nvvirtualcamerafilter_x64.dll which is provided by nvidia broadcast. Please report this to nvidia.
