### ISSUE TITLE
AV1 Not working

### ISSUE THREAD

**Issue by FV101** [obsproject/obs-studio#11330]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/rIkxBw0GhG0uMp6L

### OBS Studio Crash Log URL

theres no crash log

### Expected Behavior

I wanted it to record and work

### Current Behavior

Didnt work at all. Crashed without any log and didnt cause any cpu usage spikes or lag or freezing.

### Steps to Reproduce

1. Use these settings:
![image](https://github.com/user-attachments/assets/23f1f6c1-6be9-4b4e-8158-5e4661d75e5c)
2. Have a Xeon E5 1650 V4 (i7 6850k) and an Rx 480 with 24 gigs of ram.
3. Use window capture.
4. Click record.
5. Watch it crash.

### Anything else we should know?

Reencoded a video with ffmpeg with the same settings as i used on obs (1080p) and it did that at 28fps but it would still crash on obs when i selected 10fps
ffmpeg -i test.mkv -c:v libsvtav1 -crf 22 -preset 9 -pix_fmt yuv420p10le -c:a copy testav1v1.mkv

**Comment by Fenrirthviti** [comment]
Tested with above repro steps, no issues on my end.

This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by FV101** [comment]
> Tested with above repro steps, no issues on my end.
> 
> This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.
> 
> Thank you!

are you sure it isnt my pc or something? what do i do.
