### ISSUE TITLE
Alt Tappin to switch windows freezes Game capture

### ISSUE THREAD

**Issue by SenkuG** [obsproject/obs-studio#11343]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/Qcvut9PqBugcSoxx

### Expected Behavior

Alt tappin is used to switch between windows easily, this shouldn't affect the recorders in any way

### Current Behavior

when you alt tap from a game in fullscreen for example, Minecraft, the Game captrue will freeze on the frame that was before you alt- taps

### Steps to Reproduce

1. get Game capture and start recording
2. Open the game you want to record and set it to full screen (start recording early to see when the footage freezes)
3. Alt + Tab, to OBS or any software
4. Go back to OBS and check the preview

### Anything else we should know?

Restarting OBS doesn't help, it makes the Game capture into a black screen (I couldn't get any footage because I don't know how to record the desktop in anything else other than OBS)
[Uploading 2024-10-04 19-55-42.zip…]()

**Comment by Fenrirthviti** [comment]
When you alt-tab out of a full-screen game, the game stops rendering so there is nothing for OBS to capture. This is expected, and there isn't anything that we can do about it. Run your games either windowed or borderless if you will be regularly alt-tabbing away from them.

Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for further assistance.

Thank you!
