### ISSUE TITLE
no encoders other then software 264 (arch linux amd 7000 series gpu)

### ISSUE THREAD

**Issue by testc2n14** [obsproject/obs-studio#11344]
### Operating System Info

Other

### Other OS

arch linux

### OBS Studio Version

Git

### OBS Studio Log URL

https://obsproject.com/logs/jFECiyR2HXzF3bZw

### Expected Behavior

to show av1 h265 and ahrdware h264 on the encoder preset

### Current Behavior

only software h264
![image](https://github.com/user-attachments/assets/7c5b2f85-d4bc-4419-8628-847e9ecf2fff)

### Steps to Reproduce

use obs

**Comment by kkartaltepe** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

**Comment by testc2n14** [comment]
ah ok
