### ISSUE TITLE
Random crash after opening OBS, check for updates and then close it by pressing the X at the top right

### ISSUE THREAD

**Issue by MinionAttack** [obsproject/obs-studio#11348]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/aRagT09Bf5YGbI0B

### OBS Studio Crash Log URL

https://obsproject.com/logs/DN93H4mMmLFKG6z1

### Expected Behavior

When closing the programme, the crash does not occur.

### Current Behavior

Random crash after opening OBS, check for updates and then close it by pressing the X at the top right

### Steps to Reproduce

1. Open OBS.
2. Check for an update.
3. Close OBS by pressing the X at the top right.

**Comment by Fenrirthviti** [comment]
The crash is coming from your AMD GPU driver. Make sure your GPU driver is fully updated, otherwise please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for further assistance.

Thank you!
