### ISSUE TITLE
OBS crashes at launch on Windows 11 24H2 (build 26100.1882)

### ISSUE THREAD

**Issue by MarioSwitch** [obsproject/obs-studio#11347]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.3

### OBS Studio Log URL

OBS crashes before I can go to the Help menu...

### Expected Behavior

OBS starts normally

### Current Behavior

OBS crashes after 2-3 seconds... I can't even select anything on the navbar

### Steps to Reproduce

1. Open OBS normally / on Safe Mode on W11 24H2 build 26100.1882
2. Wait 2-3 seconds, OBS crashes

### Anything else we should know?

https://github.com/user-attachments/assets/f42c3a74-7326-4d80-8119-059a6965217d

**Comment by WizardCM** [comment]
To find the OBS Studio crash logs, follow these steps:

Press WinKey+R to open the Run dialog
Type in: %APPDATA%\obs-studio\crashes and press Enter
Upload the desired crash log, usually the latest, directly to this Discord channel by dragging and dropping the file into the chat window

**Comment by MarioSwitch** [comment]
Thanks for the path 👌

But I only have a crash log from 2022...
![image](https://github.com/user-attachments/assets/bdb45903-451c-45d4-b27e-d7b66ab8109d)

But this seems to be related to Windows as I can't even install Streamlabs, the setup screen also crashes...

**Comment by MarioSwitch** [comment]
The latest log file:
[2024-10-05 14-01-54.txt](https://github.com/user-attachments/files/17266089/2024-10-05.14-01-54.txt)

**Comment by WizardCM** [comment]
This is likely caused by your antivirus, Norton 360.

This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels below, and if it's determined that this is indeed a bug, then we will re-open this issue.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

**Comment by MarioSwitch** [comment]
When using a shortcut to obs64.exe, it says:
![image](https://github.com/user-attachments/assets/92db1272-ad4e-4140-9754-90e83cb40cce)

**Comment by MarioSwitch** [comment]
It was a Windows bug, an update just fixed it!
