### ISSUE TITLE
Default settings

### ISSUE THREAD

**Issue by herheliuk** [obsproject/obs-studio#11359]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.3

### OBS Studio Log URL

Not needed.

### Expected Behavior

1. "View Release Notes" checkbox from Setup is in charge of "What's New" window when first opened.
2. "Resize output" and "Default source" (like Display Capture) settings in "Auto-configuration Wizard"
3. Resolution for both "Steaming" and "Recording" is set to resolution of main monitor.
4. "Resize output" aka down-scaling is off by default.
5. Each audio source takes only 1st channel.
6. "Video Encoder" is set to "Hardware" by default (if available)
7. "Video Bitrate" is set to 5000 Kbps and "Audio Bitrate" is set to 192
8. "Process Priority" is set to "High" by default or configurable in "Auto-configuration Wizard"

### Current Behavior

1. "View Release Notes" checkbox from Setup opens "What's New" website page and "What's New" window shows when first opened despite "View Release Notes" checkbox is being off in Setup.
2. "Resize output" aka down-scaling is on by default and cannot be configured from "Auto-configuration Wizard".
3. There is no default source on the scene.
4. Each audio source takes every channel.
5. Resolution for both "Steaming" and "Recording" is set to 1080p despite monitor being 1440p.
6. "Resize output" aka down-scaling is on by default and set to 1 step lower e.g. 720p.
7. "Video Encoder" is set to "Software" by default despite "Hardware" encoding being available.
8. "Video Bitrate" is set to 2500 Kbps and "Audio Bitrate" is set to 160

### Steps to Reproduce

1. Delete obs (if installed) with "Erase Scenes, etc." being checked.
2. Install obs normally with "Open OBS" being checked.

### Anything else we should know?

This is what initial user experience like. You have a good program, don't make bad first impression.

**Comment by gxalpha** [comment]
This sounds like a feature request, which we don't track using GitHub Issues (we use GitHub exclusively for bug reports).
Please put ideas and feature requests on [our ideas page](https://ideas.obsproject.com).

Thank you!
