### ISSUE TITLE
Scenes don't swap positions when you click 'Transition'

### ISSUE THREAD

**Issue by dude363635** [obsproject/obs-studio#11352]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/JirQefJfI70KqSCl

### Expected Behavior

I expected the scene I had in the Preview side to switch to the Program side, and the Program scene to switch to the Preview side.

### Current Behavior

Instead, the scene on the left side of the screen duplicated onto the right side of the screen. The result of this is that now I have the same scenes in Preview and Program. Now to switch them I have to select the same scene that I had on program if I want to use it again instead of just clicking 'Transition' again.

### Steps to Reproduce

1. Open OBS
2. Have 2 or more scenes in the menu
3. Select a scene from the menu to put it into the 'Preview' side.
4. Click 'Transition'
5. Now the 'Preview' side is in the 'Program' side and the 'Program' scene has not switched to the 'Preview' side.

### Anything else we should know?

This is not a recent issue for me, it has been happening for many updates now.

**Comment by derrod** [comment]
![2024-10-06_00-33-11_BRmzON](https://github.com/user-attachments/assets/c7438100-42c2-4cd1-9fc5-3afe321ccd7e)

**Comment by dude363635** [comment]
Oops, I shoulda looked first....
Thanks!
