### ISSUE TITLE
[Nightly Build] Group function is broken

### ISSUE THREAD

**Issue by style1925** [obsproject/obs-studio#11366]
### Operating System Info

Windows 11

### OBS Studio Version

Git / 31.0.0-beta1

### OBS Studio Log URL

https://gist.github.com/style1925/48c3600dafcc8305dcb27ab9a4c9c891

### Expected Behavior

Same as version 30.2.3

### Current Behavior

Group is broken.

### Steps to Reproduce

(1) When a scene created in version 30.2 is loaded in version 31.0, the source position is different.
1. Create a scene in version 30.2.
2. Update to version 31.0 (or import scene collection)
Scene collection file to reproduce this problem: [here](https://www.dropbox.com/scl/fi/56ircp4vnqagbdelhlra1/version_302_Scene.json?rlkey=hqh16lsstlurk7kc10fjew737&st=lduoyt91&dl=0)

Version 30.2.3
![version-30-2](https://github.com/user-attachments/assets/8570af49-88d0-4396-91c7-1fc95b30bb32)

Version 30.1 (Nightly Build)
![version-31-0](https://github.com/user-attachments/assets/f707aa66-1583-408e-b2bb-afc8881fc3de)

(2) When ungrouping, the source moves to 90001.
1. Create a source. (use a browser source)
2. Move the source to the center. (Transform → Center to Screen)
3. Add the source created in step 1 to a group.
4. Ungroup the source.
5. The source is not displayed. (it moves to 90001)

Version 30.2.3

https://github.com/user-attachments/assets/c809d49f-01f7-4514-b7d3-5b0421856e46

Version 30.1 (Nightly Build)

https://github.com/user-attachments/assets/9e17f7bd-a39c-4af8-b0e7-d55eb503416e

(3) When a source is added to a group, it is moved to a different location than the original source.
1. Create a source. (use a browser source)
2. Move the source to the center. (Transform → Center to Screen)
3. Add the source from step 1 to a group.
6. Create a color source.
7. Add the color source created in step 4 to the group.
8. The position of the color source is incorrect. (-90001)
9. Ungroup the source.
10. The source is not displayed.

Version 30.2.3

https://github.com/user-attachments/assets/bfb219f5-5f16-453a-994f-9505d9d6e9e6

Version 30.1 (Nightly Build)

https://github.com/user-attachments/assets/6dbc53b8-d2fa-4c93-8141-0afb807e3cff

### Anything else we should know?

This issue does not occur in version 30.2.3.

**Comment by RytoEX** [comment]
@style1925 Does the linked PR resolve the issue for you?

**Comment by style1925** [comment]
@RytoEX 

The issue has been resolved.
Thank you very much!

(1)

https://github.com/user-attachments/assets/fcdce06e-17a1-465f-a513-5f8e5796a9be

(2)

https://github.com/user-attachments/assets/fa8c5bb0-958f-4c76-8899-d79f1b886d3d

(3)

https://github.com/user-attachments/assets/943db084-66af-44d3-ade9-ec11c2c4f9d9
