### ISSUE TITLE
[Nightly Build] OBS crashes when using non-ASCII characters in profile name

### ISSUE THREAD

**Issue by style1925** [obsproject/obs-studio#11363]
### Operating System Info

Windows 11

### OBS Studio Version

Git

### OBS Studio Log URL

https://gist.github.com/style1925/ecc6a1acb1dda1602c2bd6389576ee69

### OBS Studio Crash Log URL

https://gist.github.com/style1925/06c56b562b0ec52715212b98c5bc7d93

### Expected Behavior

OBS does not crash

### Current Behavior

OBS crashes

### Steps to Reproduce

1. Nightly Build Download.
2. Launch OBS.
3. Use a profile name with non-ASCII characters, e.g., '日本語', 'てすと', or 'テスト'.
*日本語 (kanji) = Japanese / てすと (hiragana) = test / テスト (katakana) = test
4. Exit OBS.
5. OBS crashes and will not Launch.

If the profile folder already uses non-ASCII characters.
1. Nightly Build Download.
2. OBS crashes and will not Launch.

### Anything else we should know?

Change the folder name of the profile to English and OBS will start.
Example: テスト (katakana) → test

This issue does not occur in version 30.2.3.

memo (if the profile name is “test”)
Pressing “File → Show Profile Folder” does not open the folder for the selected profile.

Version 30.2.3
C:\Users\Admin\AppData\Roaming\obs-studio\basic\profiles\test
test folder opens

Version 31.0 (Nightly)
C:\Users\Admin\AppData\Roaming\obs-studio\basic\profiles
test folder is not opened

**Comment by notr1ch** [comment]
Seems to be caused by https://github.com/obsproject/obs-studio/pull/11055
