### ISSUE TITLE
Mixer cannot be sorted

### ISSUE THREAD

**Issue by zuilintan** [obsproject/obs-studio#11367]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.3

### OBS Studio Log URL

...

### Expected Behavior

Maybe it can drag sort?

### Current Behavior

Mixer cannot be sorted

### Steps to Reproduce

...

**Comment by gxalpha** [comment]
This sounds like a feature request, which we don't track using GitHub Issues (we use GitHub exclusively for bug reports).
Please put ideas and feature requests on [our ideas page](https://ideas.obsproject.com).

Thank you!

**Comment by mihawk90** [comment]
In fact there already is one:

https://ideas.obsproject.com/posts/117/add-the-ability-to-reorder-audio-mixer-items

**Comment by zuilintan** [comment]
> In fact there already is one:
> 
> https://ideas.obsproject.com/posts/117/add-the-ability-to-reorder-audio-mixer-items

THK，I am understand，
Now in alphabetical order.
