### ISSUE TITLE
Macos 15 Virtual Camera not working

### ISSUE THREAD

**Issue by B4fb** [obsproject/obs-studio#11360]
### Operating System Info

Other

### Other OS

MacOS 15

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/FzFqEI6p78pW2NWs

### Expected Behavior

The virtual camera can be started

### Current Behavior

an error message appears, that the virtual camera couldn't be started.

### Steps to Reproduce

1. Open OBS
2. Press "start virtual camera"
3. See error message

**Comment by gxalpha** [comment]
This is `OSSystemExtensionErrorForbiddenBySystemPolicy`, which indicates that you're likely running on some kind of managed system.

In any way, this issue appears to be a support request, for which we don't use GitHub Issues.
Please make sure to visit the support sections on our [Discord server](https://discord.gg/obsproject) or [Forums](https://obsproject.com/forum).

Thank you!
