### ISSUE TITLE
Scene Collection and Profile launch parameters causing a crash

### ISSUE THREAD

**Issue by sestain** [obsproject/obs-studio#11394]
### Operating System Info

Windows 11

### OBS Studio Version

31.0.0-beta1

### OBS Studio Log URL

https://obsproject.com/logs/BaJfBNY6jjlclTqj

### OBS Studio Crash Log URL

https://obsproject.com/logs/fmD5nL5u4Q3L0cGP

### Expected Behavior

Launch parameters should set collection and profile to the specified ones.

### Current Behavior

OBS Crashes before safe-mode prompt is seen.

### Steps to Reproduce

1. Open cmd/pwsh
2. Go to OBS' 64bit bin folder (obs-studio\bin\64bit)
3. Run this command ´.\obs64.exe --collection "Record" --profile "Replay"´
4. OBS has crashed window should popup

**Comment by derrod** [comment]
Fixed by #11380
