### ISSUE TITLE
Shortcuts are still processed even when finder is on top of the OBS window

### ISSUE THREAD

**Issue by EDmitry** [obsproject/obs-studio#11396]
### Operating System Info

macOS 14

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/BsQtsOn9tDBgcjeQ

### Expected Behavior

I have "Space" set to start recording a video. When I switch to finders window and use space there (to open quicklook), the OBS behind Finder should NOT handle this command.

### Current Behavior

I have "Space" set to start recording a video. When I switch to finders window and use space there (to open quicklook), OBS also starts recording, but it's in the foreground, so it shouldn't.

### Steps to Reproduce

1. Set the "space" key to start recording in OBS settings
2. Open OBS. Switch to Finder's window
3. Press space in Finder to quicklook a file
...

**Comment by Penwy** [comment]
haave you tried setting hotkey focus behaviour (in settings > advanced) to "disable hotkeys when main window isn't in focus"

**Comment by Fenrirthviti** [comment]
This is expected, hotkeys are registered regardless of OBS being in focus or not. You can change this behavior in Settings -> Advanced if you want.

**Comment by EDmitry** [comment]
Thank you!
