### ISSUE TITLE
n/a

### ISSUE THREAD

**Issue by NakosCeo** [obsproject/obs-studio#11419]
### Operating System Info

Ubuntu 24.04

### OBS Studio Version

30.2.3

### OBS Studio Log URL

n/a

### Expected Behavior

The obs wiki should list instructions on how to install using the .deb files in the Releases page:

[Latest Release](https://github.com/obsproject/obs-studio/releases/tag/30.2.3)

Here there are offered 2 deb files for Ubuntu 24.04 (Noble):

1. `obs-studio_30.2.3-0obsproject1.noble_amd64.deb`
2. `OBS-Studio-30.2.3-Ubuntu-24.04-x86_64.deb`

Both of these target ubuntu noble (24.04) but have different sizes, and unpacking them and reading their control files, it seems they have different requirements as well.

The first i understand is the one the official PPA offers, but i cannot find any information on the second one.

It should be made clear, how these two versions differ (different requirements in control file), and which one should someone install on (Ubuntu Noble) if they have not the ability to add the PPA repository and install from there.

### Current Behavior

Two deb files for ubuntu noble, and no relevant information in wiki or Readme.md

### Steps to Reproduce

1. Navigate to [Latest Release](https://github.com/obsproject/obs-studio/releases/tag/30.2.3)
2. Find 2 deb files for Ubuntu 24.04 (Noble)
3. No explanation in wiki or readme

**Comment by kkartaltepe** [comment]
The wiki is community maintained, be the change you wish to see in the world.
