### ISSUE TITLE
Crashes when switching profiles

### ISSUE THREAD

**Issue by gechoto** [obsproject/obs-studio#11414]
-

**Comment by PatTheMav** [comment]
Is your filesystem set to be case-sensitive? Also what are the contents of your profile directory (`${HOME}/.config/obs-studio/basic/profiles`)?

**Comment by PatTheMav** [comment]
The directory names look correct, but is there a `basic.ini` inside the `test` directory?

I've tried to reproduce the issue on Windows, Ubuntu, and macOS but have met no issues.

**Comment by PatTheMav** [comment]
That exception makes it seem as if it tried to switch to the "Untitled" profile and not the "test" profile. As I'm not able to reproduce this, you'd have to launch OBS with `gdb` attached yourself and inspect the contents of the profile cache when the exception was thrown.

**Comment by PatTheMav** [comment]
I think the ampersand is used as an accelerator marker for the "U" in undefined. It's unexpected for me that calling `text()` on the menu action will actually _include_ the accelerator.

**Comment by tytan652** [comment]
Looks like Qt (and the KDE Platform plugin) does some things that breaks the expectation between `setText()` and `text()`.

**Comment by PatTheMav** [comment]
Indeed this looks like the return of an old KDE bug for Qt6: https://bugs.kde.org/show_bug.cgi?id=337491

We'll add some hardening to our code to not rely on the `text` of a `QAction` anymore as it obviously cannot be trusted.
