### ISSUE TITLE
CreateForMonitor (0x80070005)

### ISSUE THREAD

**Issue by wzzlearning** [obsproject/obs-studio#11413]
### Operating System Info

Windows 10

### OBS Studio Version

Git

### OBS Studio Log URL

 obs_service_apply_encoder_settings: Null 'service' parameter [2024-10-18 14:08:56.673] [WXAmCast] [info] obs_service_apply_encoder_settings: Null 'service' parameter [2024-10-18 14:08:56.675] [WXAmCast] [info] >>> new qsv encoder [2024-10-18 14:08:56.675] [WXAmCast] [info] [qsv encoder: 'simple_h264_stream'] settings: 	rate_control:   CBR [2024-10-18 14:08:56.675] [WXAmCast] [info] 	target_bitrate: 2000 [2024-10-18 14:08:56.675] [WXAmCast] [info] 	fps_num:        30 	fps_den:        1 	width:          1152 	height:         720 [2024-10-18 14:08:56.676] [WXAmCast] [info] [qsv encoder: 'simple_h264_stream'] debug info: [2024-10-18 14:08:56.679] [WXAmCast] [info] WASAPI: Device 'Realtek HD Audio 2nd output (Realtek(R) Audio)' [48000 Hz] initialized [2024-10-18 14:08:56.699] [WXAmCast] [info] source 'Basic.DesktopDevice1' destroyed [2024-10-18 14:08:56.699] [WXAmCast] [info] WASAPI: Device '麦克风 (Realtek(R) Audio)' Terminated [2024-10-18 14:08:56.734] [WXAmCast] [info] 	impl:           D3D11 	surf:           D3D11 [2024-10-18 14:08:56.806] [WXAmCast] [info] WASAPI: Device '麦克风 (Realtek(R) Audio)' [48000 Hz] initialized [2024-10-18 14:08:56.835] [WXAmCast] [info] source 'Basic.AuxDevice1' destroyed [2024-10-18 14:08:56.923] [WXAmCast] [info] 	m_nSurfNum:     39 [2024-10-18 14:08:56.981] [WXAmCast] [info] 	m_nTaskPool:    4 [2024-10-18 14:08:56.981] [WXAmCast] [info] 	major:          1 	minor:          255 [2024-10-18 14:08:56.981] [WXAmCast] [info] libfdk_aac encoder created [2024-10-18 14:08:56.981] [WXAmCast] [info] libfdk_aac bitrate: 160, channels: 2 [2024-10-18 14:08:56.982] [WXAmCast] [info] end WXCast::onvideocapture::<lambda_de50867c0b0e0bb7370616fca96e1c0a>::operator () 523 [2024-10-18 14:08:57.074] [WXAmCast] [info] [qsv encoder: 'simple_h264_stream'] settings: 	rate_control:   CBR [2024-10-18 14:08:57.074] [WXAmCast] [info] 	target_bitrate: 2000 [2024-10-18 14:08:57.074] [WXAmCast] [info] 	fps_num:        30 	fps_den:        1 	width:          1152 	height:         720 [2024-10-18 14:08:57.074] [WXAmCast] [info] [qsv encoder: 'simple_h264_stream'] debug info: [2024-10-18 14:08:57.203] [WXAmCast] [info] 	m_nSurfNum:     39 [2024-10-18 14:08:57.249] [WXAmCast] [info] 	m_nTaskPool:    4 [2024-10-18 14:08:59.715] [WXAmCast] [info] CreateForMonitor (0x80070005) [2024-10-18 14:09:02.754] [WXAmCast] [info] CreateForMonitor (0x80070005) [2024-10-18 14:09:05.780] [WXAmCast] [info] CreateForMonitor (0x80070005)

### Expected Behavior

capture success

### Current Behavior

capture monitor black

### Steps to Reproduce

1.start obs
2.capture monitor
3.
...

**Comment by Fenrirthviti** [comment]
Please provide the full log file.
