### ISSUE TITLE
Macrosilicon Hdmi capture dongle audio not working 

### ISSUE THREAD

**Issue by Codythedragonrude** [obsproject/obs-studio#11423]
### Operating System Info

Other

### Other OS

Linux Mint 22

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/1GKaxJVWfO0Eyk8X

### Expected Behavior

Outputs Capture device (MacroSilicon USB3.0 HD VIDEO) Audio Through OBS 

### Current Behavior

Video Shows no audio even after unplugging device and plugging it back in as well as a complete shut down 
When i do get it working somehow if i close and re open OBS later audio remains gone no matter what i do 

### Steps to Reproduce

1.log into distro
2.open obs close it down and the re open it later 
3.see if audio is still outputting consistently 
...

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
