### ISSUE TITLE
Linux - Laggy/stuttering recording with Nvidia proprietary drivers on Wayland

### ISSUE THREAD

**Issue by Milli189** [obsproject/obs-studio#11447]
### Operating System Info

Other

### Other OS

Manjaro

### OBS Studio Version

31.0.0-beta2

### OBS Studio Log URL

https://obsproject.com/logs/r0o6AFFUPEuAOSdu

### Expected Behavior

Smooth recording

### Current Behavior

The recording stutters every second, making the recording laggy, and it stutters especially when recording gameplay

### Steps to Reproduce

1. Every version of OBS I've tried has the issue, so it's an out of the box issue for me, I didn't do anything to trigger it
2.
3.
...

### Anything else we should know?

I'm using the latest 560 nvidia driver, and pipewire to record

**Comment by kkartaltepe** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

**Comment by Milli189** [comment]
> We do not use GitHub Issues for support questions.
> 
> Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

this is not a support request, this is a real bug/issue I'm having
this is not closed, I still have this issue, it's months I have this issue, every time I reinstall manjaro I have that issue

**Comment by Fenrirthviti** [comment]
Please go through the support channels for troubleshooting. This issue report is far too generic and is not actionable, and we do not do troubleshooting through GitHub Issues. If an actual issue or bug with OBS is found, a new issue can be opened with actual details on what that is.

**Comment by Milli189** [comment]
> Please go through the support channels for troubleshooting. This issue report is far too generic and is not actionable, and we do not do troubleshooting through GitHub Issues. If an actual issue or bug with OBS is found, a new issue can be opened with actual details on what that is.

I don't have this issue with GPU Screen Recorder though, it's only OBS, so it must be related to OBS

**Comment by Fenrirthviti** [comment]
I'm glad that other software is working!

Please use the support channels to go through the troubleshooting process to gather more information.
