### ISSUE TITLE
Video Encoder resets when closing and opening the app.

### ISSUE THREAD

**Issue by byuwur** [obsproject/obs-studio#11464]
### Operating System Info

Windows 10

### OBS Studio Version

31.0.0-beta2

### OBS Studio Log URL

https://obsproject.com/logs/KnomraaKCj5YKPww

### Expected Behavior

Keep the Video Encoder settings I previously applied in my profile:
![image](https://github.com/user-attachments/assets/b76425df-f2a7-4159-a81d-3a9654b4dd97)

### Current Behavior

When I save my video encoders for use, they behave as normal. The issue is when I close the app and then re-open it, then the video encoder settings specifically reset to x264:
![image](https://github.com/user-attachments/assets/9adccc13-a218-49df-b067-cfd43aa48399)
Everything else seems to stay the same as intended.

### Steps to Reproduce

1. Have either one or two (or more) profiles.
2. In one of them, change the Video Encoder setting on Settings > Output > Streaming and/or Recording > Video Encoder
3. Apply > OK
4. Close OBS.
5. Open OBS.
6. Check the settings being reset to x264 (doesn't seem to affect other profiles than the selected when the app closed).
7. If you have a second profile: then change the Video Encoder again.
8. Switch profiles.
9. Assuming the profile has a Video Encoder other than x264, Close OBS with the second profile active.
10. Open OBS.
11. Now the second profile's Encoders are set to x264.
12. If you switch back to your first profile, you see than it remains unaffected.

### Anything else we should know?

Drivers up to date.
Hopefully everything you may need is already in the log information.
Never encountered something like that up to 30.2.3.

**Comment by RytoEX** [comment]
Please check #11465 and see if it fixes this Issue.
