### ISSUE TITLE
Python 3.13.0 refuses to load but 3.12.7 works

### ISSUE THREAD

**Issue by InsanePanda** [obsproject/obs-studio#11461]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/5WBiLKSbtbGop00W

### Expected Behavior

OBS Script should load with Python 3.13.0 without issue.

### Current Behavior

OBS Script refuses to load Python version 3.13.0

### Steps to Reproduce

1. Install Python 3.13.0
2. Open OBS Scripts menu, change Python path to 3.13.0
3. It shows "Python is currently not loaded"

![image](https://github.com/user-attachments/assets/b2a550de-113d-4dbe-a4f8-2eddfbb3fdf6)

**Comment by gxalpha** [comment]
Python 3.13 is not currently supported. This may change in a future version of OBS, but as-is this is not a bug. Please use Python 3.12 for now.

**Comment by Chiitoo** [comment]
For what it is worth, it has been working for quite a while on Linux (just using the `url-text` script to test), even though unsupported indeed.
