### ISSUE TITLE
Flatpak version need to be upgraded

### ISSUE THREAD

**Issue by stigman9393** [obsproject/obs-studio#11483]
### Operating System Info

Other

### Other OS

arch linux

### OBS Studio Version

30.2.3

### OBS Studio Log URL

doesnt have

### Expected Behavior

org.kde.Platform, tree 6.6 is no more supported, need to be upgraded to newer version

### Current Behavior

flatpak shows an error everytime when im doing flathub update

### Steps to Reproduce

1. Updated packages
2.
3.
...

**Comment by tiberium-v** [comment]
See comment here: https://github.com/obsproject/obs-studio/issues/11478
