### ISSUE TITLE
obs doesn't run after compile

### ISSUE THREAD

**Issue by Coderdreams** [obsproject/obs-studio#11481]
### Operating System Info

Ubuntu 24.04

### OBS Studio Version

31.0.0-beta3

### OBS Studio Log URL

Can't obtain one as obs doesn't start

### Expected Behavior

obs runs successfully

### Current Behavior

After compiling attempting to execute obs throws:

/usr/local/bin/obs: symbol lookup error: /usr/local/bin/obs: undefined symbol: obs_encoder_group_destroy

### Steps to Reproduce

1. compile with instructions in https://github.com/obsproject/obs-studio/wiki/build-instructions-for-linux
2. needed to download and compile rnnoise from: https://github.com/xiph/rnnoise.git
3. needed to sudo apt install libffmpeg-nvenc-dev
4. install doesn't work

**Comment by kkartaltepe** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

**Comment by Coderdreams** [comment]
This is not a support  question, the project doesn't run after following the site instructions. Please consider reopening

**Comment by Coderdreams** [comment]
For people searching for the same problem, it was fixed by removing libobs0t64:amd64

The hint was that the executable loaded libobs from this location:

$ ldd /usr/local/bin/obs | grep libobs
        libobs-frontend-api.so.30 => /lib/x86_64-linux-gnu/libobs-frontend-api.so.30 (0x000070ee94b31000)
        libobs.so.30 => /lib/x86_64-linux-gnu/libobs.so.30 (0x000070ee91cf3000)

and that location wasn't from the compiled version, it was from a system package: 

$ dpkg -S libobs.so.30
libobs0t64:amd64: /usr/lib/x86_64-linux-gnu/libobs.so.30

with that deleted it went to search for the correct version:

$ ldd /usr/local/bin/obs | grep libobs
        libobs-frontend-api.so.30 => /usr/local/lib/libobs-frontend-api.so.30 (0x00007f6fcdb80000)
        libobs.so.30 => /usr/local/lib/libobs.so.30 (0x00007f6fcaced000)

**Comment by kuator** [comment]
> For people searching for the same problem, it was fixed by removing libobs0t64:amd64
> 
> The hint was that the executable loaded libobs from this location:
> 
> $ ldd /usr/local/bin/obs | grep libobs libobs-frontend-api.so.30 => /lib/x86_64-linux-gnu/libobs-frontend-api.so.30 (0x000070ee94b31000) libobs.so.30 => /lib/x86_64-linux-gnu/libobs.so.30 (0x000070ee91cf3000)
> 
> and that location wasn't from the compiled version, it was from a system package:
> 
> $ dpkg -S libobs.so.30 libobs0t64:amd64: /usr/lib/x86_64-linux-gnu/libobs.so.30
> 
> $ dpkg -l libobs0t64:amd64 Desired=Unknown/Install/Remove/Purge/Hold | Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend |/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad) ||/ Name Version Architecture Description +++-================-===================-============-============================================================= ii libobs0t64:amd64 30.0.2+dfsg-3build1 amd64 recorder and streamer for live video content (shared library)
> 
> with that deleted it went to search for the correct version:
> 
> $ ldd /usr/local/bin/obs | grep libobs libobs-frontend-api.so.30 => /usr/local/lib/libobs-frontend-api.so.30 (0x00007f6fcdb80000) libobs.so.30 => /usr/local/lib/libobs.so.30 (0x00007f6fcaced000)

Thank you a lot!
