### ISSUE TITLE
macOS: Video Capture Device "new" vs "legacy"

### ISSUE THREAD

**Issue by jimpalompa** [obsproject/obs-studio#11487]
### Operating System Info

macOS 15

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/gb1SO5SLpABq2PJT

### Expected Behavior

When I add a **Video Capture Device** on macOS I do not have the same options as the **Video Capture Device (Legacy)** I want to to have **Video range: Full** but it's not even available. However, using the Legacy I have all the options. I've attached images using the Legacy source here:

<img width="653" alt="Video Capture Decice (Legacy)" src="https://github.com/user-attachments/assets/27fcf5b1-eec0-4fb3-b5df-b3e0edb0db03">

### Current Behavior

Here are the options I get with the "new" **Video Capture Device** source:

![Video Capture Decice (New)](https://github.com/user-attachments/assets/df2f340e-bbc2-4b6d-b231-90b8cd56b5fb)

### Steps to Reproduce

1. Add a Video Capture Device
2. Add a Video Capture Device (Legacy)

**Comment by PatTheMav** [comment]
This is by design - the old source never bothered to check if the video format(s) provided by the video device actually have full or limited RGB range. The new source actually checks for this and only allows you to select/configure formats that are supported by the device.

**Comment by jimpalompa** [comment]
I see, I was not aware of that, thanks for the info. I just hope we will be able to use the Legacy one in the future, since it gives me way more detail in dark areas, even though my video device, according to the new source, does not support it. I can post examples when I get home if needed.

**Comment by jimpalompa** [comment]
Here are two screenshots from my camera to compare. One is full video range, the other is limited.

Video range: Full
![video range full](https://github.com/user-attachments/assets/095541dd-89b0-4602-9371-9e1d685c22be)

Video range: Limited
![video range limited](https://github.com/user-attachments/assets/35326bd5-dc47-4c78-b9da-8e9a21e5a7cf)

I'm just curious if the "new" video source is correct, not giving me an option to use full video range. I obviously get much greater blacks using full. Perhaps I'm missing something?

**Comment by Fenrirthviti** [comment]
That doesn't look like it has anything to do with color range, but rather exposure settings on the camera. In any event, this is deep in to support territory, so it's probably best to stop by the [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for further assistance.

Thank you!

**Comment by jimpalompa** [comment]
Thank you for your feedback. I can however confirm this has nothing to do with exposure settings. The only difference is Limited vs Full on the source. I just wanted to inform the developers about it.

Cheers!
