### ISSUE TITLE
Scale of (Relatively Positioned) Grouped Sources BREAK when changing its order inside the group.

### ISSUE THREAD

**Issue by byuwur** [obsproject/obs-studio#11488]
### Operating System Info

Windows 10

### OBS Studio Version

31.0.0-rc1

### OBS Studio Log URL

https://obsproject.com/logs/mgPpTTrT6NxfOvql

### Expected Behavior
I'm to using Grouped Sources references.
Everything works as intented in latest stable version (30.2.3), where if I move and reorder anything whether it's inside a group or not, is stays in its position and scaling thanks to these values being absolute.
Video for reference:
v30.2.3 = https://github.com/user-attachments/assets/67b0f003-846a-42e8-be17-aa00925671a8

### Current Behavior

The issue occurs when I try to do the exact same in OBS31:
I think this has something to do with the new feature of relative positioning and scaling (which is a blessing) due to the nature of this bug, but I may be mistaken.
I have the same scene with the same groups and all. But when I change and reorder any element, a bunch of other stuff breaks its parameters.
It'd be more understandable if this issue happened within the Sources inside the group, but it's affecting other groups too.
I'm just trying to get a Source on top of my cam feed and cannot do it for now.
Can't really tell if this issue persists with Nested Scenes.
Video for reference:
v31.0.0-b3 = https://github.com/user-attachments/assets/49ccbcc3-facc-43d0-a8b9-0e1db06876d5
v31.0.0-rc1 = https://github.com/user-attachments/assets/8173f844-6900-44a3-a2a5-a1bf8b76fca4

### Steps to Reproduce

(Kudos to @style1925 for giving a better resource to this)

1. I think the relative position magic happens as soon as you open/create a new Scene Collection, so you can create one from scratch.
1.1. This is the scene collection where it's happening:
[byuwurtest.json](https://github.com/user-attachments/files/17874172/byuwurtest.json)
2. Set up some Grouped Sources, ideally many of them.
3. Resize any Group.
4. Once all's set up, try to change the order of any Source inside any Group.
5. Enjoy.

Video for reference:
v31.0.0-rc1 = https://github.com/user-attachments/assets/8173f844-6900-44a3-a2a5-a1bf8b76fca4

### Anything else we should know?

If I'm missing something let me know. c:

**Comment by RytoEX** [comment]
From off-thread comments, this seems to be an issue with Move Transition. @Penwy ?

**Comment by Penwy** [comment]
That was just a guess based on the fact I could not repro.
Maybe if they could share a scene collection with said issue?

**Comment by RytoEX** [comment]
cc @exeldro due to above mention of Move Transition.

**Comment by byuwur** [comment]
Hi, sorry for the late response.
This scene collection will do:
[byuwurtest.json](https://github.com/user-attachments/files/17680145/byuwurtest.json)
I doesn't have anything to do with my plugins: I said I used Exeldro's Move Transition because it doesn't work as I want to with Nested Scenes so I had to create Source Groups. When I move anything on top of anything, even inside the same group/folder it breaks.
Same behavior happened in Safe Mode.
This is how it should look like:
![image](https://github.com/user-attachments/assets/53b5455a-ce17-4816-8d59-ac6ab365c562)
Here I moved MusicImg above MusicTxt, both being inside the same group and broke the whole scene:
![image](https://github.com/user-attachments/assets/0504267e-302d-45ff-ad76-f88dd4e4428c)

**Comment by ZeroTenFuras** [comment]
I have the same problem too when using fresh install of OBS 31.0.0-beta3.

**Comment by RytoEX** [comment]
I tried to reproduce this in a fresh scene collection but did not observe any unexpected behavior. We'll need a reliable way to reproduce this.

**Comment by byuwur** [comment]
@RytoEX, Did you try with [byuwurtest.json](https://github.com/user-attachments/files/17680145/byuwurtest.json) too?

**Comment by RytoEX** [comment]
@byuwur Yes, but since I do not have the scene collection assets, I cannot observe any actual changes occurring.

**Comment by Buttgoblin** [comment]
It's annoying that I can't share due to it being a paid plugin, but I could replicate this by installing the "Streamup" Polaroid extension which creates a new scene with new sources & groups, then just adjusting a source position from that will cause it to get smaller and smaller each time you change the order of the sources.

I also had a group for a camera (camera + border image), and below the group was a monitor capture, moving the display capture source above the group triggered the same behaviour every time.

**Comment by style1925** [comment]
@RytoEX 

The following method can reproduce the same issue.

### Steps to Reproduce
1. Add a source to a group.
2. Resize the group in the preview window.
3. Reorder the source within the group.

### Anything else we should know?
I tested it with no plugins and in portable mode.
In the video, the group size is decreased, but if it is increased, the behavior reverses (it expands).

Versions where the issue does not occur: 30.2.3, 31.0-beta1

|30.2.3|31.0-beta1|
|:-:|:-:|
|<video src="https://github.com/user-attachments/assets/e85693b6-759e-4da4-a329-2ea6d714e075">|<video src="https://github.com/user-attachments/assets/2b962523-d345-4442-9759-5174fa580d5c">|

Versions where the issue occurs: 31.0-beta2, 31.0-beta3

|31.0-beta2|31.0-beta3|
|:-:|:-:|
|<video src="https://github.com/user-attachments/assets/e171f545-880f-420f-8179-974e58c36c5b">|<video src="https://github.com/user-attachments/assets/cbee6f85-e728-40a5-b5f6-7cf76643d439">|

**Comment by Penwy** [comment]
yeah, can repro with those steps

**Comment by ZeroTenFuras** [comment]
> @RytoEX, Did you try with [byuwurtest.json](https://github.com/user-attachments/files/17680145/byuwurtest.json) too? @ZeroTenFuras, it'd be nice if you can confirm that the same happened to you with this Scene Collection in Safe Mode.

Just tested, and yes - same thing happening in safe mode

**Comment by byuwur** [comment]
Hi, @RytoEX, sorry, I didn't realize the thing with the sources. [byuwurtest.json](https://github.com/user-attachments/files/17874172/byuwurtest.json) In this one is a browser source that could suffice.
@style1925, thanks for the resource.
@Penwy, @ZeroTenFuras:
v31.0.0-rc1 = https://github.com/user-attachments/assets/8173f844-6900-44a3-a2a5-a1bf8b76fca4
I've just tested with the RC1 update and the issue persists. Also updated the issue accordingly.

**Comment by SuslikV** [comment]
It may turn out that issue itself lies far beyond recent fixes ( https://github.com/obsproject/obs-studio/pull/11390 )
Because grouping/un-grouping of items for example was known to have positional/size issues long time ago (far before v30): https://obsproject.com/forum/threads/sizing-groups-of-sources-confusing-behavior.181868/post-664765

**Comment by Penwy** [comment]
> Because grouping/un-grouping of items for example was known to have positional/size issues long time ago

There is more than one transform bug with groups, some not recent, and though some might be related (I'm pretty sure a few different symptoms are caused by issues in the in-to-out group coordinate transfer function), those specific symptoms, at the very least are new to 31.

**Comment by sprEEEzy** [comment]
Confirming same issue in 31.

**Comment by byuwur** [comment]
According to style1925's evidence: this was injected in 31.0.0-beta2, which I can confirm was an issue I didn't have until updating to beta 2.

> It may turn out that issue itself lies far beyond recent fixes ( #11390 ) Because grouping/un-grouping of items for example was known to have positional/size issues long time ago (far before v30): https://obsproject.com/forum/threads/sizing-groups-of-sources-confusing-behavior.181868/post-664765

**Comment by RytoEX** [comment]
Yes, our own investigation for _this specific Issue_ yielded that as well:
> Probably one of these:
> https://github.com/obsproject/obs-studio/commit/bece05bbc6e7b14d23848f10d20bd95da160f8c7
> https://github.com/obsproject/obs-studio/commit/e97d7c10c2572a14d7be5c7aecacbf65f7a617ce
> 
> From https://github.com/obsproject/obs-studio/pull/11390.
