### ISSUE TITLE
autoconfig selecteed hardware encoding on a gpu that does not have it.

### ISSUE THREAD

**Issue by weather-tracker** [obsproject/obs-studio#11493]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/foX2TkzadL5RUO2g

### Expected Behavior

not to auto-select an encoder my GPU doesn't have.

### Current Behavior

it auto-selected h264 encoder.
clicked record to test, it said error check drivers.

### Steps to Reproduce

1. download obs
2. runit
3. let auto config select settings.
...
run it/ as in test recored

### Anything else we should know?

it is an rx6400 it has no hardware encoding.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by weather-tracker** [comment]
I did not need assistance, I changed it to software encoding. I was just putting this out there so that it does not cause confusion for someone else.
