### ISSUE TITLE
The colour of the text in the Style label of the Appearance page of the Settings window is unreadable.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [obsproject/obs-studio#11498]
### Operating System Info

Other

### Other OS

[`urn:cpe:/o:fedoraproject:fedora:41`](https://download.fedoraproject.org/pub/fedora/linux/releases/41/Spins/x86_64/iso/Fedora-KDE-Live-x86_64-41-1.4.iso)

### OBS Studio Version

Other

### OBS Studio Version (Other)

[`obs-studio-31.0.0~beta1-4.fc41.x86_64`](https://fedora.pkgs.org/41/fedora-updates-x86_64/obs-studio-31.0.0~beta1-4.fc41.x86_64.rpm.html#:~:text=Package%20filename-,obs%2Dstudio%2D31.0.0~beta1%2D4.fc41.x86_64.rpm,-Package%20name%20%09obs%2Dstudio)

### OBS Studio Log URL

https://obsproject.com/logs/OFvnFKMmNg2zc20m

### Expected Behavior

The text should be the system-defined colour, instead of its current hardcoded colour.

### Current Behavior

The colour of the text in the “Style” label of the “Appearance” page of the “Settings” window is unreadable:

![Screenshot_20241107_212754](https://github.com/user-attachments/assets/76765fa9-a3e5-404f-a03c-6a256ccb4dcc)

### Steps to Reproduce

If using Yami, switch to the System theme.

### Anything else we should know?

I presume that this relates to https://github.com/obsproject/obs-studio/issues/10846#issuecomment-2424233290.

**Comment by Fenrirthviti** [comment]
The System theme is no longer valid, and is not supported. This looks like a packaging issue that it's even still selectable.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/obsproject/obs-studio/issues/11498#issuecomment-2463269430

@Fenrirthviti, thanks. I've reported this upstream at https://bugzilla.redhat.com/show_bug.cgi?id=2324493#c0, and I've filed https://github.com/obsproject/obs-studio/issues/10846#issuecomment-2463292791 to request that support be re-added.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/obsproject/obs-studio/issues/11498#issuecomment-2463314713

A new installation of `obs-studio-31.0.0-1.fc41.x86_64` does not include this preference. Consequently, I presume that it remained because the application was updated from a version with that preference present to a version without. @Fenrirthviti, do you remain confident that it was a packaging bug?

**Comment by Fenrirthviti** [comment]
I don't recall offhand what migrations we had, but there might have been a transitionary period at some point where if System was previously selected, it was still allowed to be shown selected in the UI to varying degrees of success. I'd have to defer to others who worked on the migration from existing configs.

**Comment by beedell-roke** [comment]
@Fenrirthviti, [`issues/10846#issuecomment-4828627525`](https://github.com/obsproject/obs-studio/issues/10846#issuecomment-4828627525) demonstrates that the migration likely doesn't switch from `com.obsproject.System`, to another, supported theme, considering that it remains accessible in OBS's interface, once added to `file://$Home/.config/obs-studio/user.ini`:

- <p></p><img width="638" height="345" alt="Image" src="https://github.com/user-attachments/assets/cc4f06af-7e59-456d-b824-396f8f1f395f" /><p></p>

- > https://github.com/obsproject/obs-studio/blob/3bba730f76bcecb1ac88be5740395291ca197a57/frontend/OBSApp_Themes.cpp#L1045

**Comment by Fenrirthviti** [comment]
Manually editing a config file to force an unsupported option is not a path we consider worth development time to mitigate or prevent. If you understand the limitations and wish to force the setting via a manual edit of the config file, you are welcome to do so.

**Comment by beedell-roke** [comment]
@Fenrirthviti, I'm aware of that; it's irrelevant to my comment. Perhaps, I didn't phrase it well: the migration path may not transition a user from that theme, to a now-supported one. That would explain why it appears to persist in some users' configurations, even though they've not manually modified that preference in the `.ini` file.

**Comment by RytoEX** [comment]
If I recall correctly, it was an intentional decision to not switch the theme away from System if the user had selected it.

**Comment by beedell-roke** [comment]
@RytoEX, if so, having it be unsupported is strange.

**Comment by RytoEX** [comment]
> [@RytoEX](https://github.com/RytoEX), if so, having it be unsupported is strange.

It was left as-is in user settings if they had selected it to not suddenly break their UI. It is unavailable to select in the UI for new installations, and as such we treat it as unsupported (no longer receiving updates).
