### ISSUE TITLE
OBS Virtual Camera is Active in Google Chrome with No Active Tab Using Camera

### ISSUE THREAD

**Issue by unholyHub** [obsproject/obs-studio#11505]
### Operating System Info

Windows 10

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/zth3lOdWFY8jKO5Z

### Expected Behavior

Google Chrome appears to use the OBS Virtual Camera even without any active tabs that require camera access. Attempting to test the camera at https://webcamtests.com/ results in the following JavaScript error:
- Name: NotReadableError
- Message: Could not start video source

### Current Behavior

The OBS Virtual Camera appears to be in use by Google Chrome, despite there being no open tabs or web applications that are accessing the camera. This causes the OBS Virtual Camera to remain occupied, even when not in use, and interferes with the intended operation of the OBS Virtual Camera in other applications.

![image](https://github.com/user-attachments/assets/198dbe0e-a9b0-4847-b518-714bd1d0033b)

### Steps to Reproduce

1. Open OBS Studio and start the OBS Virtual Camera.
2. Open Google Chrome.
3. Ensure no tabs are open that would require camera access (e.g., Google Meet, Zoom, or any video conferencing tool).
4. Go to https://webcamtests.com/ and attempt to start a camera test.
5. Check the camera usage indicator in OBS and on the operating system.

### Anything else we should know?

Google Chrome Version 130.0.6723.117 (Official Build) (64-bit)

**Comment by Fenrirthviti** [comment]
This sounds like it should be reported to Chrome, as we don't have any control over applications that use our virtual device.

**Comment by unholyHub** [comment]
The OBS Virtual Camera is being shown as active across multiple browsers (Google Chrome, Brave, Microsoft Edge, Firefox) even when there are no open tabs or applications that require camera access. Reinstalling OBS did not resolve this issue.

**Comment by Fenrirthviti** [comment]
Then there is likely something else on your system that is accessing the camera. There are [several methods](https://superuser.com/questions/1746419/which-application-is-currently-using-my-camera-on-windows-10) to determine what application is currently accessing the camera.

If you need further assistance, please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/).

Thank you!
