### ISSUE TITLE
OBS Studio 31.0.0 Beta 3 - All Lossless Audio Codecs don't work after FFmpeg 7.1 update

### ISSUE THREAD

**Issue by Gnatzelle** [obsproject/obs-studio#11504]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

Other

### OBS Studio Version (Other)

obs-studio-rc from the AUR

### OBS Studio Log URL

https://obsproject.com/logs/XNERtVHzNtyHgSqL

### Expected Behavior

Before the FFmpeg Update to 7.1 no Problems occured when Recording was done with a lossless Audio Codec (FLAC, PCM, etc.)

### Current Behavior

After the FFmpeg Update to 7.1 all lossless Audio Codecs prevent Recording of any kind. Regardless of the choosen Codec, OBS throws the following Error-Message: "Failed to open AAC Codec: Argument Invaild".

The Output in the Terminal is a complete different Error:
```
[flac @ 0x6388bcd21840] The encoder bitrate is negative.
warning: [FFmpeg flac encoder: 'Streaming'] Failed to open AAC codec: Das Argument ist ungültig
```

### Steps to Reproduce

1. Choose any Lossless Codec for Recording (FLAC, PCM, etc.) which doesn't follow the standard Bitrate Settings from 64-320 Kbit/s
2. Hit the Record-Button
3. Look at the Error-Message...
...

**Comment by gxalpha** [comment]
FFmpeg 7.1 is not currently supported by OBS.

**Comment by Lain-B** [comment]
(We'll likely add support for 7.1 some time after release)
