### ISSUE TITLE
Why is there two Apple VT HEVC Hardware encoders? What does T2 stands for?

### ISSUE THREAD

**Issue by stephane-archer** [obsproject/obs-studio#11527]
### Operating System Info

macOS 15

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/z10axsBBiaXFso0x

### Expected Behavior

<img width="1440" alt="Screenshot 2024-11-14 at 19 08 58" src="https://github.com/user-attachments/assets/11661b2c-2f24-4467-9ca4-9b6248971a5f">

### Current Behavior

Why is there two Apple VT HEVC Hardware encoders? What does T2 stands for?

### Steps to Reproduce

have an late intel macbook pro

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
