### ISSUE TITLE
Recording stops at this error: Invalid argument av_interleaved_write_frame failed -1: Operation not permitted

### ISSUE THREAD

**Issue by AstroPkOwO** [obsproject/obs-studio#11531]
### Operating System Info

Windows 11

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/fDqWSFJhGLhbA8Bt

### Expected Behavior

I expected obs to record my gameplay like it used to.

### Current Behavior

crashed my recording and game randomly

### Steps to Reproduce

1. Press record
2. Play game
3. recording stops because of this error
![Screenshot 2024-11-17 165811](https://github.com/user-attachments/assets/c916c784-907b-4ab4-85bc-b121a1ad05e1)

**Comment by prgmitchell** [comment]
@AstroPkOwO Hello, this looks more likely to be a support issue which we do not handle through github issues. I'd recommend heading over to the [community discord](https://discord.com/invite/obsproject) for help or the [forums](https://obsproject.com/forum/). If you are asking in the discord feel free to ping me, my display name is Mitchell | Yolo.

**Comment by AstroPkOwO** [comment]
@prgmitchell alright thanks ill take it to the forums most likely
