### ISSUE TITLE
Arc A580 - Encoder overload occurs constantly when streaming / recording games that didn't overload on an RTX 2060.

### ISSUE THREAD

**Issue by SapphireDrew** [obsproject/obs-studio#11530]
### Operating System Info

Windows 10

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/UhRBBrWIKSyuOLHZ

### Expected Behavior

The Intel Arc QuickSync Encoder (_both H264 and AV1_) shouldn't overload when attempting to stream or record the games (_Stray and Deep Rock Galactic_) that I was able to stream and record perfectly fine when using the ASUS TUF RTX 2060. Performance of the Intel Arc A580 should be at parity with or slightly better than that of an RTX 2060 based on GamersNexus GPU benchmarks and reviews.

### Current Behavior

Encoder overload occurs and (_according to GPU-Z_) GPU Load reaches 99% when attempting to stream or record Stray and Deep Rock Galactic with the Intel Arc A580, even setting the `Target Usage` to `TU7: Fastest (Best Speed)` and the profile to `baseline`.

### Steps to Reproduce

1. Install Intel Arc A580
2. Set encoder to `QuickSync H.264` or `QuickSync AV1`
3. Set Target Usage to `TU7: Fastest (Best Speed)`
4. Launch either Stray or Deep Rock Galactic
5. Set Max FPS to 60
6. Start Streaming or Start Recording
7. Observe encoder overload and 100% GPU load

### Anything else we should know?

Additional Log: https://obsproject.com/logs/9puluLlPm0vKf4kc

Framerates are capped to 60 FPS, display refresh rate is set to 60 Hz, and VSync is enabled both in-game and via Arc Control. Encoder overload occurs immediately upon streaming and / or recording either of the games used to test and compare the Intel Arc A580 to the RTX 2060, even when setting the Target Usage to `TU7: Fastest (Best Speed)` and the profile to `baseline`. Content was streamed to Twitch with a 720p canvas and broadcast resolution at a CBR of 6000 kbps when the issue occurred while using the QuickSync H.264 Video Encoder. Games streamed were played in Windowed Mode at 720p (_due to only having a single monitor_) and were added to OBS as a Game Capture source.

C.A.M. (_Clever Access Memory_) / Resizeable BAR and Above 4G Decoding were enabled via UEFI despite motherboard having an Intel 300 series chipset (_ASRock Taichi Z390 with an Intel Core i7 9700K and 32 GB DDR4 RAM_).

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
