### ISSUE TITLE
Incorrect message how to fix missing virtual camera on Mac 

### ISSUE THREAD

**Issue by emarc** [obsproject/obs-studio#11533]
### Operating System Info

macOS 15

### Other OS

Apple Silicon

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/FttjowrNXilqGUkq

### Expected Behavior

Popup should indicate where I should change settings in the MacOS version I'm using in order to allow install of system software, using the correct message for my OS, which in my case should be [Error.SystemExtension.NotInstalled.MacOS15](https://github.com/obsproject/obs-studio/blob/4652daf748e467415976682e41ea507d6fee8f25/plugins/mac-virtualcam/src/obs-plugin/data/locale/en-US.ini#L3C1-L3C43) "The virtual camera is not installed Please allow OBS to install the camera system extension in **System Settings → General → Login Items & Extensions → Camera Extensions.** You may need to restart OBS if this message still appears afterward."

### Current Behavior

The popup clearly told me what to change, but indicated the wrong location for my OS version. The translation files seem to contain the correct message in the `Error.SystemExtension.NotInstalled.MacOS15` key, but I'm getting the "regular" `Error.SystemExtension.NotInstalled` even though I'm on 15.

This popup should say "The virtual camera is not installed Please allow OBS to install the camera system extension in **System Settings → General → Login Items & Extensions → Camera Extensions.** You may need to restart OBS if this message still appears afterward."
![Screenshot%20on%202024-11-18%20at%2005-12-56](https://github.com/user-attachments/assets/ef0fd10a-9a58-4ed6-b8f0-255f6483bf1b)

### Steps to Reproduce

1. New computer with MacOS 15.1
2. Install OBS giving all the permissions as prompted
3. Try starting the virtual camera
-> Popup with incorrect details how to fix.

### Anything else we should know?

I thought "maybe I can improve the popup text and make a PR", but then I noticed this has already been addressed in a separate translation for MacOS 15. However, this does not seem to work in 30.2.3. I did not investigate further, but some potential reasons include A) translation not making it into 30.2.3 B) my OS not being correctly detected (perhaps because it's 15.1, perhaps because it's Apple Silicon?) C) the OS version detection not working properly at all, or something else.

**Comment by gxalpha** [comment]
This is fixed in OBS 31.
