### ISSUE TITLE
[31.0.0-rc1] source tarball contains wrong content (still beta3)

### ISSUE THREAD

**Issue by tgurr** [obsproject/obs-studio#11546]
### Operating System Info

Other

### Other OS

Exherbo Linux

### OBS Studio Version

Other

### OBS Studio Version (Other)

31.0.0-rc1

### OBS Studio Log URL

-

### Expected Behavior

* `OBS-Studio-31.0.0-rc1-Sources.tar.gz` -> `obs-studio-31.0.0-rc1-sources`

### Current Behavior

* `OBS-Studio-31.0.0-rc1-Sources.tar.gz` -> `obs-studio-31.0.0-beta3-sources`
* tar also spams a lot of `tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'` while unpacking
* also a bunch of additional `.` hidden files are included compared to the previous releases

### Steps to Reproduce

1. Download provided `OBS-Studio-31.0.0-rc1-Sources.tar.gz`
2. `tar xf OBS-Studio-31.0.0-rc1-Sources.tar.gz`
...

### Anything else we should know?

Unpacking the tarball with tar also spams a lot of `tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.quarantine'` which also isn't the case for the previous `OBS-Studio-31.0.0-beta3-Sources.tar.gz`

```
$ tar --version
tar (GNU tar) 1.35
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
```

**Comment by tgurr** [comment]
Actually after a further look I think the content of `OBS-Studio-31.0.0-rc1-Sources.tar.gz` appears also to be identical to `beta3` missing the changes to `rc1`, the . hidden files make things hard to diff for actual changes since they're in every directory.

**Comment by RytoEX** [comment]
This is all mostly because I had to manually fix the source tarball on a Mac system. The one produced by CI was invalid.

**Comment by RytoEX** [comment]
This should now be resolved.
