### ISSUE TITLE
Can't record videos to Network Folder on SteamOS

### ISSUE THREAD

**Issue by shaunroselt** [obsproject/obs-studio#11578]
### Operating System Info

Other

### Other OS

SteamOS

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/B0DvGOfJIOX2FgBX

### Expected Behavior

1. Set Output Recording Path to Network Folder
2. Start Recording
3. Works as expected

### Current Behavior

1. Set Output Recording Path to Network Folder
2. Start Recording
3. Error appears saying I don't have enough disk space on that network drive to continue recording even though there is more than enough free space.

![There is not enough sufficient disk space to continue recording](https://github.com/user-attachments/assets/149e3333-b493-44d9-a91c-daf201a937d1)

### Steps to Reproduce

Click on Start Recording

### Anything else we should know?

The network folders are shared from a Windows 11 device.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
