### ISSUE TITLE
--remote-debugging-port is not working on latest builds

### ISSUE THREAD

**Issue by Regynate** [obsproject/obs-studio#11576]
### Operating System Info

Windows 10

### OBS Studio Version

31.0.0-rc1

### OBS Studio Log URL

https://obsproject.com/logs/NMbfc9LTKtJEdQA2

### Expected Behavior

Being able to debug browser sources by opening devtools in browser

### Current Behavior

Opening any page shows the error "Debugging connection was closed. Reason: WebSocket disconnected"

### Steps to Reproduce

1. Launch OBS with the command line argument "--remote-debugging-port=9222"
2. Go to http://localhost:9222 in the browser
3. Open any browser source page

### Anything else we should know?

It works fine on the release 30.2.3

**Comment by WizardCM** [comment]
With the CEF update, you also need to provide ``--remote-allow-origins=*``.

**Comment by Regynate** [comment]
Thank you!

**Comment by Warchamp7** [comment]
We really should have a wiki page talking about remote debugging so I've now also [created that](https://github.com/obsproject/obs-studio/wiki/Browser-source-development-and-debugging)
