### ISSUE TITLE
OBS 30x segfault on interaction with window capture (xcomposite)

### ISSUE THREAD

**Issue by alejandro-alzate** [obsproject/obs-studio#11579]
### Operating System Info

Other

### Other OS

Linux Mint 22 x86_64 

### OBS Studio Version

Other

### OBS Studio Version (Other)

`OBS Studio - 30.0.2.1-3build1`

### OBS Studio Log URL

https://obsproject.com/logs/CajX8IjRXuYWRfNt

### OBS Studio Crash Log URL

https://obsproject.com/logs/CajX8IjRXuYWRfNt

### Expected Behavior

Succesfull window capture

### Current Behavior

Segmentation fault

### Steps to Reproduce

1. Open obs
2. make a scene or use the current one
3. create a `Window Capture (XComposite)` source
4. Interact with this source

### Anything else we should know?

OBS will segfault upon creation of the source.
It will successfully create the source but if you click it on the source list it will segfault again.

- Consistent bug
- Reproducible (At least on my machine)
- No delay in crash

ASCIInema recording of the terminal during one of the crashes (it *may* be useful idk):
[tmpaykmgrw4-ascii.cast.zip](https://github.com/user-attachments/files/17981437/tmpaykmgrw4-ascii.cast.zip)

**Comment by alejandro-alzate** [comment]
> Please provide a GDB backtrace of the crash.

How can I provide that?

**Comment by alejandro-alzate** [comment]
I updated the system.
`OBS 30.2.3.1-1~bpo24.04.1` seems to work fine.

Is it still worth doing the debug trace for other people?
Or we close it here?

What do you think miss/mr @Fenrirthviti?

**Comment by Fenrirthviti** [comment]
Probably not if an update fixed the issue. Thanks for the update!

**Comment by alejandro-alzate** [comment]
I came back, the native version does not crash but cannot record video the flatpak version works flawless.

off topic but related: Blender is having issues rendering in mp4

And obs does mention on the logs that
```
info: adding 42 milliseconds of audio buffering, total audio buffering is now 42 milliseconds (source: Mic/Aux)

info: ---------------------------------
info: [x264 encoder: 'simple_video_recording'] preset: veryfast
info: [x264 encoder: 'simple_video_recording'] profile: high
info: [x264 encoder: 'simple_video_recording'] settings:
	rate_control: CRF
	bitrate:      0
	buffer size:  0
	crf:          21
	fps_num:      30
	fps_den:      1
	width:        1280
	height:       720
	keyint:       250

info: ---------------------------------
info: [FFmpeg aac encoder: 'simple_aac_recording0'] bitrate: 192, channels: 2, channel_layout: stereo

warning: [ffmpeg muxer: 'simple_file_output'] Failed to create process pipe
```

for this new issue it seems to be a skill issue on the ffmpeg part, now i googled both the blender & obs error trying to invoke ffmpeg with no luck.

Could you point me on the right direction to fix this one?
I really don't like flatpaks and I use neative binaries as much as I can.
I would like to use the native obs version but I haven't been able to get rid of that error.

I swear the dependency comic of xkcd is real.

**Comment by alejandro-alzate** [comment]
Understood.
But no ffmpeg is the liable here
Shocut, OBS & Blender broke on fast succession all 3 need ffmpeg to work.

This is a upstream issue I will stop bothering here.
(Use a like or eyes as read if you don't want to write anything)
