### ISSUE TITLE
Was the multi-GPU option removed in version 31? I use 2 Nvidia GPUs.

### ISSUE THREAD

**Issue by ipmaru** [obsproject/obs-studio#11577]
### Operating System Info

Windows 11

### OBS Studio Version

31.0.0-rc1

### OBS Studio Log URL

none

### Expected Behavior

The GPU input value field allows for input.

### Current Behavior

I use two 4060,3060 GPUs simultaneously. The GPU selection in the encoder settings was there up until version 30, but I don't see it in the 31 beta.
![image](https://github.com/user-attachments/assets/dc5a892c-a6b2-4173-ae4d-b83a7df5ab75)

### Steps to Reproduce

1.Launch OBS 31.0.0-rc1
2.Selete Setting - Output - Streaming - Video Enconder - NVIDIA NVENC H.264 
3.There is no GPU input value field.
...

**Comment by Fenrirthviti** [comment]
Please provide a log file.

**Comment by derrod** [comment]
The option should be here:
![2024-12-01_15-58-23_3HqrWJ](https://github.com/user-attachments/assets/761da5eb-1388-44e4-9360-3c4031d2e965)

Please provide a log.

**Comment by RytoEX** [comment]
Closing this as no log file has been provided.
