### ISSUE TITLE
Panel titles include ampersands

### ISSUE THREAD

**Issue by Jookia** [obsproject/obs-studio#11588]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/z1GZNCmBjSDLcDCj

### Expected Behavior

Panel titles to read 'Scenes' or 'Sources'

### Current Behavior

Panels include ampersands in their titles.

![image](https://github.com/user-attachments/assets/bdf315dc-b2dd-4123-8fc2-264b70066edf)

### Steps to Reproduce

1. Open OBS
2. Look at the panels

**Comment by mihawk90** [comment]
Duplicate of #10341

**Comment by RytoEX** [comment]
Duplicate of #10341

**Comment by Jookia** [comment]
Could you re-open #10341 at least?

**Comment by derrod** [comment]
> Could you re-open #10341 at least?

No. It's not our bug but Qt/KDE.

**Comment by Jookia** [comment]
Does this mean https://github.com/obsproject/obs-studio/issues/11478 will need to be done to fix this?

**Comment by mihawk90** [comment]
Possibly. We don't really know. In the support channels we've seen this come and go without updates on OBS' side.
