### ISSUE TITLE
OBS on Linux (X11) render lags caused by resizing windows

### ISSUE THREAD

**Issue by lexano-ivs** [obsproject/obs-studio#11582]
### Operating System Info

Ubuntu 24.04

### OBS Studio Version

31.0.0-rc1

### OBS Studio Log URL

https://obsproject.com/logs/CZ2VtpKYZ0civf4A

### Expected Behavior

Simply resizing a window on an X11-based Linux desktop should not cause severe render lag in OBS. This lag happens even when not streaming.

### Current Behavior

Resizing a window on the desktop causes render lag and render frame time to dramatically increase. This happens with or without streaming active.

### Steps to Reproduce

1. Run 31.0.0-rc1 flatpak (using X11 desktop, not Wayland)
2. Add a Media Source (any file will do)
3. Open the OBS Stats window
4. Reset the OBS stats
5. Grab the edge of any window (even the Stats window) and resize it. The render frame time will increase and lagged frames will also increase.
6. As long as you keep resizing the window, the lag will be present.

### Anything else we should know?

The problem happens on X11. I have not been able to reproduce this problem on a Wayland-based desktop.

The included log file doesn't show anything amiss. It's best to reproduce this bug locally and observe the Stats window in realt-ime as you resize a window on the desktop.

I'm using the NVIDIA 4060 with driver 550.120.

I've also reproduced this issue with a local DEB install; it does not seem to be flatpak specific. It happens with 30.2.3, 31.0.0-rc1, and the TEB v40 flatpak.

**Comment by lexano-ivs** [comment]
I had just reset the Stats to zero, then gently resized the Firefox browser window by maybe 100 pixels. This caused 22 render lags:

![Screenshot from 2024-12-02 17-29-32](https://github.com/user-attachments/assets/4d8849db-c19b-45a2-bfe8-b6d7b7c8d453)

**Comment by kkartaltepe** [comment]
This is just how window resizing works, to resolve this would probably require changes in Qt and how obs renders in general.

I'm going to close this as its unlikely anything will come from this being open.
