### ISSUE TITLE
Facebook Live : RTMP_Connect1, TLS_Connect failed: -0x7080

### ISSUE THREAD

**Issue by pl-gauthier** [obsproject/obs-studio#11586]
### Operating System Info

Other

### Other OS

Arch Linux 6.6.60-1-lts

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/JaVKXInB88ROdsOM

### Expected Behavior

To stream on Facebook Live

### Current Behavior

Streaming impossible on Facebook Live due to some SSL/TLS error with either addresses :
`rtmps://rtmp-api.facebook.com:443/rtmp/` 
`rtmps://live-api-s.facebook.com:443/rtmp/`

### Steps to Reproduce

1. Attempt to stream on Facebook Live

### Anything else we should know?

Here is a forum thread on the subject :
`https://obsproject.com/forum/threads/rtmp_connect1-tls_connect-failed-0x7080-on-facebook-live.182153/`

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
