### ISSUE TITLE
OBS 31.0.0 Debugging connection is closed 

### ISSUE THREAD

**Issue by sergeos** [obsproject/obs-studio#11598]
### Operating System Info

Windows 11

### OBS Studio Version

31.0.0

### OBS Studio Log URL

https://obsproject.com/logs/D4taVysabSftuL1m

### Expected Behavior

After the latest update from 30.2.3 to 31.0.0 the debugger stopped working. When trying to go to the debugged page, a message appears that the websocket is disabled. I specially returned to the previous version of OBS and the debugger works fine there.
<img width="445" alt="image" src="https://github.com/user-attachments/assets/585c95ed-4588-48fd-9699-2c1221eaca6f">

### Current Behavior

New version of obs broke debugger

### Steps to Reproduce

1. run powershell from bin folder with obs application
2. type in command line _.\obs64.exe --remote-debugging-port=9222_
3. open browser developer tools (in this case i'm use the edge)
4. select the item that needs to be debugged
5. an error occurs at this point

**Comment by derrod** [comment]
Newer Chromium (and thus CEF) versions require an additional flag, see https://github.com/obsproject/obs-studio/wiki/Browser-source-development-and-debugging
