### ISSUE TITLE
Please update flatpak package to use latest Qt runtime

### ISSUE THREAD

**Issue by LaurentBonnaud** [obsproject/obs-studio#11593]
### Operating System Info

Other

### Other OS

Ubuntu 24.10

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/AeEbQduhDbzD8eZq

### Expected Behavior

The flatpak package should depend on a supported runtime.

### Current Behavior

```
$ flatpak update
Looking for updates…

Info: runtime org.kde.Platform branch 6.6 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Platform and SDK
Info: applications using this runtime:
   com.obsproject.Studio

```

### Steps to Reproduce

1. flatpak update

**Comment by mihawk90** [comment]
Duplicate of #11478 

^ which is also pinned.
