### ISSUE TITLE
Game capture has black screen in both modes in 31.0

### ISSUE THREAD

**Issue by MrKoddy** [obsproject/obs-studio#11604]
### Operating System Info

Windows 10

### OBS Studio Version

31.0.0

### OBS Studio Log URL

https://obsproject.com/logs/tCx2lJF9lotT7O8r

### Expected Behavior

Game capture has black screen after updating in 31.0 in full screen and window mode

### Current Behavior

Game Capture should display the game in both modes like before 31.0

### Steps to Reproduce

1. Add a game capture source
2. Display in full screen or window mode
3.  Try to delete old source and add new one, same black screen

### Anything else we should know?

here an example https://streamable.com/hjqmqb

**Comment by Penwy** [comment]
Star Citizen will need to update its EasyAntiCheat module dor it to accept the OBS capture hook again.
In the meantime, you will have to use window capture for it.

**Comment by MrKoddy** [comment]
With window mode it doesn't work

**Comment by Penwy** [comment]
then, I4d suggest you check the forums or the discord for support
