### ISSUE TITLE
Using media source to capture mp3, monitor has no sound

### ISSUE THREAD

**Issue by FanZR123** [obsproject/obs-studio#11611]
### Operating System Info

Windows 11

### OBS Studio Version

31.0.0

### OBS Studio Log URL

none

### Expected Behavior

Use media source to capture mp3, monitor is normal

### Current Behavior

Using media source to capture mp3, monitor has no sound

### Steps to Reproduce

1.Add media source, select mp3
2.open monitor
3.There is no sound after about a minute of playback.
mp3：[test.zip](https://github.com/user-attachments/files/18070532/test.zip)

### Anything else we should know?

I print the audio timestamp in the get_audio function of obs-ffmpeg-source.c.
I print the timestamp before judging "delay audio if rushing" in process_audio_delay of wasapi-outout.c.
The result is as follows:
![1733797287](https://github.com/user-attachments/assets/70b46cc4-f24c-4469-9ea6-9f1dd03c2839)

I guess the reason is: the MP3 is played with media source, only one frame of video is played, and the monitor's AV synchronization algorithm will compare the audio and video timestamps. Because the video timestamp does not change, the audio timestamp keeps increasing. When the audio timestamp increases to be greater than the video timestamp and exceeds 75ms, the monitor will be silent.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
