### ISSUE TITLE
Browser Source not rendering embedded video

### ISSUE THREAD

**Issue by androoo06** [obsproject/obs-studio#11616]
### Operating System Info

Windows 11

### OBS Studio Version

31.0.0

### OBS Studio Log URL

https://obsproject.com/logs/3vuTiNqd6XHE4zk8

### Expected Behavior

Video would be autoplayed through the iframe in the browser source's HTML.

### Current Behavior

Nothing but a gray screen appears.

### Steps to Reproduce

Set iframe src to a vdoninja link in the browsersource's HTML

### Anything else we should know?

This issue started only after updating OBS from 30.1.2 to 31.0.0. I'm embedding webcams from [vdoninja](https://vdo.ninja/) links into iframes in the source HTML.

Things I've tried:
- running OBS with [--autoplay-policy=no-user-gesture-required] flag
- disabling browsersource hardware acceleration
- switching links and configuration properties of iframe / vdoninja links

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
