### ISSUE TITLE
Software not responding after changing stream bitrate

### ISSUE THREAD

**Issue by Abdolahi34** [obsproject/obs-studio#11613]
### Operating System Info

Windows 10

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/Hu4q7B50ZRqQPafT

### Expected Behavior

I expected the software to continue working normally after changing the stream bitrate.

### Current Behavior

When I stream and record at the same time, when I change the stream bitrate, the bitrate displayed at the bottom of the screen becomes zero and the stream actually stops. In this case, when I press the stop stream button, nothing happens. And the stop stream button remains in the state (Stopping Streaming...).
While the device resources such as CPU and RAM are also at 60%, and in this case, if I open another software, it runs without problems.

### Steps to Reproduce

1. Start Stream
2. Start Record
3. Change Stream Bitrate (Settings > Output > Streaming > Video Bitrate)

### Anything else we should know?

In this case, the problem is only solved when the obs software is closed through the task manager with end task and reopened.
If the stream bitrate is set to an acceptable number before starting the stream and record, and the bitrate does not change after they start, then the stream and record will be completed without problems until the end.

**Comment by Fenrirthviti** [comment]
Please try without third party plugins, it looks like you're using the rtmp-multi plugin and that is what is causing issues.

**Comment by Abdolahi34** [comment]
I used this plugin in previous versions of obs, but I had no problems.

**Comment by Fenrirthviti** [comment]
If the plugin is not compatible with the latest version of OBS, then they will need to update it to be compatible. Third-party plugins are not guaranteed to work across all versions of OBS.

If you can replicate this issue without third-party plugins, we can reopen this, but as it stands please report to the multi-rtmp developer.

**Comment by Abdolahi34** [comment]
Thank you very much for your guidance.
