### ISSUE TITLE
obs在macos中，如何更改虚拟摄像机名字

### ISSUE THREAD

**Issue by vionTest** [obsproject/obs-studio#11623]
### Operating System Info

macOS 14

### Other OS

macOS

### OBS Studio Version

31.0.0

### OBS Studio Log URL

无日志

### Expected Behavior

obs 在macos中，如何理性虚拟摄像机名字

### Current Behavior

obs 在macos中，如何理性虚拟摄像机名字

### Steps to Reproduce

1.obs 在macos中，如何理性虚拟摄像机名字

### Anything else we should know?

obs 在macos中，如何理性虚拟摄像机名字

**Comment by vionTest** [comment]
obs在macos中，如何更改虚拟摄像机名字

**Comment by WizardCM** [comment]
/
This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels below, and if it's determined that this is indeed a bug, then we will re-open this issue.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
