### ISSUE TITLE
Flatpak package using EOL runtime

### ISSUE THREAD

**Issue by rdscorreia74** [obsproject/obs-studio#11627]
Hi there. 
Just installed OBS using the Flatpak package and I am receiving the information that the package is using a EOL org.kde.Platform 6.6 runtime. 
Since the package is maintained by the developers, would you please take a look at this when you have some time? 
Thanks a lot. 🙂
Cheers

**Comment by rdscorreia74** [comment]
Hi again. 
It says you closed this issue because it's not planned. 
Does that mean that you're abandoning the Flatpak package? 
Thanks in advance. 
Cheers

**Comment by Fenrirthviti** [comment]
Please check pinned issues, this was closed because it's a frequently asked question:

https://github.com/obsproject/obs-studio/issues/11478
