### ISSUE TITLE
Nvidia VGPU LTS support

### ISSUE THREAD

**Issue by ejb1123** [obsproject/obs-studio#11634]
### Operating System Info

Other

### Other OS

Windows and Linux

### OBS Studio Version

31.0.0

### OBS Studio Log URL

https://obsproject.com/logs/uKcUOzqUNxM48NiI

### Expected Behavior

Nvidia NVENC to show up as an option under the encoders.
This vGPU driver is still supported by Nvidia and will be until July 2026.

### Current Behavior

I do not see NVENC encoders

### Steps to Reproduce

1. Setup a VM using the Nvidia vGPU Release 16.8
2. Install OBS on the OS of choice
3. open settings and notice that NVENC does not show up.

### Anything else we should know?

Nvidia is supporting the vGPU driver until July 2026.

**Comment by Fenrirthviti** [comment]
I defer to our linux folks, but we, generally, do not support running OBS in a VM.

**Comment by ejb1123** [comment]
> I defer to our linux folks, but we, generally, do not support running OBS in a VM.

What are the technical reasons for not supporting it in a VM?
With proper server hardware and software, I found zero issue related to OBS being in VM.

**Comment by Fenrirthviti** [comment]
And yet, here you are, reporting an issue :)

We don't support it because OBS expects direct access to hardware to function. It may work, but we the project do not support it or really spend much effort trying to fix issues that do not occur outside a VM.

**Comment by ejb1123** [comment]
## OBS Version breakdown
OBS 31.x.x: No NVENC encoders  
OBS 30.2.3 NVENC Encoder are avalible

## nvidia-smi output:
```
Sun Dec 15 02:52:14 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.216.01             Driver Version: 535.216.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  GRID P40-4Q                    On  | 00000000:06:10.0  On |                  N/A |
| N/A   N/A    P0              N/A /  N/A |    712MiB /  4096MiB |      1%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
```

**Comment by derrod** [comment]
The NVIDIA encoder library is missing and you're running on a software renderer, so this isn't even a version thing, your driver just doesn't work.

That said, we only support drivers R550 or newer in ojr first party builds, you are free to build your own version with SDK versions down to 12.0 thoigh.
