### ISSUE TITLE
libobs includes -Werror in its .pc file

### ISSUE THREAD

**Issue by lilydjwg** [obsproject/obs-studio#11646]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

31.0.0

### OBS Studio Log URL

https://build.archlinuxcn.org/imlonghao-api/pkg/obs-studio-lily/log/1733750475

### Expected Behavior

No `-Werror` is included in `pkg-config --cflags libobs`.

### Current Behavior

`-Werror` is included in `pkg-config --cflags libobs`, despite compiled with `-Wno-dev` option.

This makes plugin failed to compile. Root privileges are required to make them build (I'm _building_ a plugin, not _developing_ it).

### Steps to Reproduce

1. Install obs-studio
2. Try to build https://hg.sr.ht/~scoopta/wlrobs
3. Fail the build

**Comment by gxalpha** [comment]
This sounds like an issue with the plugin or your environment.
Since you’re saying that you’re building the plugin, not developing it, please consult the plugin author on how to fix your error. If they end up determining that there really is an issue with OBS itself, please consider opening a pull request or explaining in more detail what the problem is.

Thank you!

**Comment by lilydjwg** [comment]
No. It fails because you add `-Werror` to it. When developing a project, you'd like to catch any compiler warnings and make your code better, but when building a project, especially an old project, the more recent and smarter compiler may issue warnings to things that has been working for their users for years. The user shouldn't be fixing their software.

**Comment by lilydjwg** [comment]
This is an example of such warnings that obs makes it to fail instead:

```
C compiler for the host machine: ccache cc (gcc 14.2.1 "cc (GCC) 14.2.1 20240910")
C linker for the host machine: cc ld.bfd 2.43.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: YES (/usr/bin/pkg-config) 2.3.0
Run-time dependency wayland-client found: YES 1.23.1
Run-time dependency libobs found: YES 31.0.0
Library dl found: YES
Library rt found: YES
Build targets in project: 1

wlrobs undefined

  User defined options
    auto_features     : enabled
    b_pie             : true
    buildtype         : plain
    libexecdir        : lib
    prefix            : /usr
    python.bytecompile: 1
    sbindir           : bin
    werror            : false
    wrap_mode         : nodownload

Found ninja-1.12.1 at /usr/bin/ninja
ninja: Entering directory `build'                                                                                                                                                              
[5/7] Compiling C object libwlrobs.so.p/src_scpy_source.c.o
FAILED: libwlrobs.so.p/src_scpy_source.c.o 
ccache cc -Ilibwlrobs.so.p -I. -I.. -I../inc -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -DENABLE_SCPY -D_GNU_SOURCE -DENABLE_DMABUF -march=x86-64-v3 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -g -ffile-prefix-map=/home/lilydjwg/tmpfs/makepkg/wlrobs-hg/src=/usr/src/debug/wlrobs-hg -flto=auto -fPIC -std=gnu17 -fPIC -fvisibility=hidden -fopenmp-simd -Werror -MD -MQ libwlrobs.so.p/src_scpy_source.c.o -MF libwlrobs.so.p/src_scpy_source.c.o.d -o libwlrobs.so.p/src_scpy_source.c.o -c ../src/scpy_source.c
../src/scpy_source.c: In function ‘buffer’:
../src/scpy_source.c:241:9: error: ignoring return value of ‘ftruncate’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
  241 |         ftruncate(this->frame->fd, stride * height);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
[6/7] Compiling C object libwlrobs.so.p/src_dmabuf_source.c.o
ninja: build stopped: subcommand failed.
```

Compiler warnings are evolving, but projects may not catch up, and they may continue to work well despite those warnings. obs shouldn't prevent them from building.
