### ISSUE TITLE
Trying to use a projector crashes OBS on KDE Wayland+Nvidia unless explicit sync is disabled with variable

### ISSUE THREAD

**Issue by queenbiscuit311** [obsproject/obs-studio#11641]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

31.0.0

### OBS Studio Log URL

https://obsproject.com/logs/vpTKnDp9YqPHVbUb

### OBS Studio Crash Log URL

I'm not seeing a crash log to upload

### Expected Behavior

Opening a projector does not crash the program without workarounds.

### Current Behavior

Opening a projector immediately crashes the program unless using a workaround.

### Steps to Reproduce

1. Open OBS
2. Try to open a projector, windowed or fullscreen
3. OBS immediately crashes
4. Open OBS with environment variable "__NV_DISABLE_EXPLICIT_SYNC=1" set
5. Try to open a projector, windowed or fullscreen
6. OBS functions as expected

### Anything else we should know?

When the program crashes the following error is thrown right before the last line that doesn't seem to make it into the log file: "wp_linux_drm_syncobj_surface_v1#87: error 4: explicit sync is used, but no acquire point is set".

**Comment by kkartaltepe** [comment]
Dupe #11022

**Comment by queenbiscuit311** [comment]
missed that one, thanks

**Comment by Kozzlick** [comment]
what is the workaround?

**Comment by queenbiscuit311** [comment]
__NV_DISABLE_EXPLICIT_SYNC=1
