### ISSUE TITLE
Check File Integrity / Check for updates - Does nothing

### ISSUE THREAD

**Issue by pelssi** [obsproject/obs-studio#11644]
### Operating System Info

Windows 10

### OBS Studio Version

30.2.3

### OBS Studio Log URL

https://obsproject.com/logs/FvPCYuSiH6wyku0m

### Expected Behavior

Check File Integrity and check for updates not working. Theres not popups or nothing

### Current Behavior

Nothing happen when i press those check file and check updates buttons on obs

### Steps to Reproduce

Just trying to update or Check File Integrity

**Comment by Fenrirthviti** [comment]
This is currently tied to the updater, and we've turned off the updater for the moment due to an issue with the new relative positioning feature until a hotfix can be made.

If you need to repair OBS, just run the normal installer and it should accomplish the same thing.

**Comment by StarMaster21** [comment]
Check File Integrity and Check for Update are broken on my OBS on version 31.0.0 since old vesion i had was 29.0.0. I remove OBS fully and install new copy fully before i added steam elements stuff and any add-ons. 

![Screenshot 2025-01-01 022032](https://github.com/user-attachments/assets/0d0918cc-f9a7-493b-a937-453369783119)
I get this all the time now i close the program. Can you please fix the problems going on with OBS? 

OBS is the best program since i switch to it.

**Comment by Fenrirthviti** [comment]
Again, nothing is broken, these are temporarily disabled until we fix a critical issue. You can just run the installer again to achieve the same result.

**Comment by StarMaster21** [comment]
So if i get this all the time I open OBS up it's normal then? I restarted my pc after deleting old files and install fresh latest version after that. Restarted it again with the same result of opening it.

![image](https://github.com/user-attachments/assets/685278e2-3377-4575-9104-38e5d8fe719d)

**Comment by Fenrirthviti** [comment]
No, that is not normal, and is completely unrelated to the updater being temporarily disabled. You likely have some kind of third-party plugin that is crashing on exit.

Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by Fenrirthviti** [comment]
As mentioned, the updater is disabled. Selecting check for updates or check file integrity is expected to work.

We understand there is no feedback right now in these cases, and are looking in to options to improve user feedback in the future.
