### ISSUE TITLE
Number fields too small

### ISSUE THREAD

**Issue by c33howard** [obsproject/obs-studio#11649]
### Operating System Info

Other

### Other OS

KDE Neon (Ubuntu 24.04)

### OBS Studio Version

31.0.0

### OBS Studio Log URL

https://obsproject.com/logs/i2veMVC35fYyjC22

### Expected Behavior

In 30.x and earlier, the input elements for "Stop Recording After" were wide enough to show two digits.

### Current Behavior

The UI elements are now too narrow.  I can only see a fraction of one digit.  Increasing the size of the window just increases the size of the Start/Stop buttons.  In this capture, the stop time is actually 0:43:38

![Screenshot_20241219_233735](https://github.com/user-attachments/assets/98b90d48-20a9-4547-a35f-9ab75bca9446)

### Steps to Reproduce

1. Open the Output Timer window
2. Drag the window to resize

**Comment by Bleuzen** [comment]
This seems to be not limited to the "Output Timer" window but affect all number fields.
Have a look at the encoder settings:

![](https://github.com/user-attachments/assets/98a14682-221f-4612-9ee9-cafaf56ec3a6)

**Comment by gxalpha** [comment]
This occurs when using Qt 6.8.1 or later (in particular, since https://github.com/qt/qtbase/commit/96adebed606cdbc73c73778917d777dc04c6e93e). For reference, OBS currently supports Qt 6.4.2 - 6.6.3.

**Comment by derrod** [comment]
Closing as it's an issue in an upstream dependency version that we do not yet use/support.
