### ISSUE TITLE
OBS 31.0.0 - Freezes With White Opaque Background

### ISSUE THREAD

**Issue by RajStartsHere** [obsproject/obs-studio#11653]
### Operating System Info

Windows 11

### OBS Studio Version

31.0.0

### OBS Studio Log URL

https://send.vis.ee/download/35469769484f0be9/#BtQE-GyKuAfBGicwte_C-w

### Expected Behavior

To Open Normally In The Respected Profile With All The Plugins And Scripts

### Current Behavior

Freezes After Providing Option To Continue Running In Safe Mode Or Normal Mode , Every Times After Selecting The 'Normal Mode'

### Steps to Reproduce

1.I Tried To A Update Plugin With The Help Of StreamUP Installer In The Elevated Settings Directly Into The 'OBS-Studio' Folder Inside The 'Program Files' Folder
2.It Usually Gets Update In Some Minutes But This Time, It Showed Error From Microsoft .NET Like This - 
[Screen Recording 2024-12-21 102733-output.webm](https://github.com/user-attachments/assets/0b2f3f9d-2c52-4bad-90c4-8bf576091fe0)
3.Then It Freezes (StreamUP Pluginstaller V2) And Get Close , From After That It Always Open Like This In Normal Mode - 
![Screenshot 2024-12-21 095953](https://github.com/user-attachments/assets/d507be2f-8b65-42b1-97af-1d63c3464a3a)
![Screenshot 2024-12-21 100025](https://github.com/user-attachments/assets/8b58e01c-2600-40a4-b680-f9373e335202)
![Screenshot 2024-12-21 100048](https://github.com/user-attachments/assets/779dd0a7-4e27-49a1-b2ae-7b932e225f5b)

### Anything else we should know?

I Reinstalled The OBS Studio From 31.0.0 Rc1 To 31.0.0 Stable After The Issue
I Tried To Replace All The Data In Program Files Folder From OBS Back Created By StreamUP Pluginstaller V2 Before Applying The Settings
I Restarted And Did Almost Everything (Except Fresh Re-Installation) But It Always Get Stuck In The White Opaque Background (Except In The 'Safe Mode')

**Comment by derrod** [comment]
This is an issue on a third-party plugin.

**Comment by RajStartsHere** [comment]
But This Is Affecting The OBS File , Not Third Party Client File
Is There Any Fix

**Comment by Fenrirthviti** [comment]
We do not support or have anything to do with StreamUP or their plugin installer, you will need to contact them for assistance.

**Comment by RajStartsHere** [comment]
I Understand Your Recommendation But StreamUP Pluginstaller Work As A Portable Software And It Don't Even Influence The OBS Files Except Replacing It (Plugins) From New Newer Version
Is There Any Way You Can Help
