### ISSUE TITLE
OBS disables custom system-wide hotkeys

### ISSUE THREAD

**Issue by Markus74a** [obsproject/obs-studio#11657]
### Operating System Info

Windows 11

### OBS Studio Version

31.0.0

### OBS Studio Log URL

https://obsproject.com/logs/wIEpSbNHWVTFbHtP

### Expected Behavior

If a keyboard button is pressed and OBS has not assigned any action to that key combination, the OBS keyboard hook handler should pass the button to the next handler in the hook chain (instead of calling the "default handler").

### Current Behavior

When a third party application installs a system-wide keyboard hook and OBS is the current foreground application, pressing the hooked key will result in the execution of the system's default action (for example, the "Web Browser" multimedia button launches "firefox.exe")

When OBS is not the current foreground application, pressing the hooked key executes the action defined by the keyboard hook (for example, the "Web Browser" multimedia button launches "winver.exe")

### Steps to Reproduce

1. Install a system-wide keyboard hook (for example, map "Web Browser" button on keyboard to action "run winver.exe")
2. Launch OBS (and make sure it is the current foreground process)
3. Make sure the "Web Browser" button is not assigned to any OBS keyboard shortcut
4. Press "Web Browser" button
5. Firefox will launch (instead of "winver.exe")

### Anything else we should know?

- If OBS is not the foreground application (or not running at all), the keyboard hooks will always work fine.
- Media players which install system-wide hooks (for example, PLAY/PAUSE button hooks) do not interfere with a hook set on the "Web Browser" button by another application.
- This bug was not introduced with OBS v31, I remember it already existed with OBS v28. OBS v27 and versions before worked fine.

**Comment by Fenrirthviti** [comment]
OBS is not blocking anything, the OS is:

`11:10:53.297: Running as administrator: true`

Don't run OBS as admin, as application contexts that aren't run as admin will not be available for input when OBS is in focus. This is an OS design, not OBS.
