### ISSUE TITLE
XComposite window capture no longer working on X11 / Arch after NVidia 565 driver update ("Cannot create EGLImage: One or more argument values are invalid.")

### ISSUE THREAD

**Issue by pcrain** [obsproject/obs-studio#11660]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

31.0.0

### OBS Studio Log URL

https://obsproject.com/logs/JmWhO6dxW8GxX1Pc

### Expected Behavior

Window Capture (XComposite) sources should capture / render previews for the contents of selected windows.

### Current Behavior

Window Capture (XComposite) sources capture / render nothing to OBS when previewing or recording them.

When launching OBS with `--verbose`, scenes containing XComposite sources spam the output log with `debug: Cannot create EGLImage: One or more argument values are invalid.`

### Steps to Reproduce

1. With the latest NVidia drivers (565) instaled, launch OBS on Arch Linux from a terminal with `obs --verbose`.
2. Add a "Window Capture (XComposite)" source to a new or existing scene, and select any open window.
3. Notice that no matter what window is selected, the window preview remains black, and the terminal log is spammed with the message "Cannot create EGLImage: One or more argument values are invalid." every 2 seconds or so.

### Anything else we should know?

I first noticed this issue using Arch's main `obs-studio` package (version `31.0.0-1`), but I've tested and reproduced this issue with version `31.0.0-4` of the `obs-studio` package, the `obs-studio-git` package, and the OBS Flatpak as well.

My system is a laptop with an NVidia Optimus dual GPU setup. This issue is reproducible even when running OBS with `env __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia obs --version`.

Downgrading my NVidia drivers (provided by the `nvidia`, `nvidia-settings`, `nvidia-utils`, and `lib32-nvidia-utils` packages) from the current 565 drivers to the previous 560 drivers I had installed fixes the problem, but breaks other applications on my machine (e.g., Minecraft fails to launch with the error "GLFW error 65543: GLX: Failed to create context: GLXBadFBConfig.")

A notable change on Arch Linux between the 560 and 565 NVidia driver releases is that the `egl-gbm`, `egl-wayland`, and `egl-x11` packages now provide several files that `nvidia-utils` previously provided (specifically `/usr/lib/libnvidia-egl-xcb.so`, `/usr/share/egl/egl_external_platform.d/20_nvidia_xcb.json`, and `/usr/share/egl/egl_external_platform.d/20_nvidia_xlib.json`). I suspect a change to / incompatibility with `libnvidia-egl-xcb.so` might be the root cause of the current issue with OBS as well as incompatibilities that result from downgrading my drivers, but that is a shot in the dark educated guess I'm unable to verify. :sweat_smile: 

I'm running the latest mainline kernel (6.12.4-arch1-1) under the X11 XFCE desktop environment with Compiz as a compositor. I'm also able to reproduce this issue with XFCE's built in XFWM compositor (so Compiz isn't the issue), and I'm not currently set up to test Wayland.

Happy to provide any other info I can as needed. Thanks for all your hard work maintaining OBS. :slightly_smiling_face:

**Comment by tytan652** [comment]
Your log shows that your are not running on NVIDIA driver (or even Intel), and also likely not an OBS bug.
```
11:20:31.745: Loading up OpenGL on adapter Mesa llvmpipe (LLVM 18.1.8, 256 bits)
11:20:31.745: OpenGL loaded successfully, version 4.5 (Core Profile) Mesa 24.3.1-arch1.3, shading language 4.50
```

This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for further assistance.

Thank you!

**Comment by pcrain** [comment]
Whoops, sorry, you're right, that instance was running without my NVIDIA GPU. :sweat_smile: Just in case this makes a difference, running OBS with `env __NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia obs --verbose` produces the following log:

https://obsproject.com/logs/dBaFIqvJlP8JGtM3

Which appears to be using the NVIDIA driver:

```
13:50:07.853: Initializing OpenGL...
13:50:07.905: Created EGLDisplay 0x5afb1ce6a970
13:50:07.969: Loading up OpenGL on adapter NVIDIA Corporation NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2
13:50:07.969: OpenGL loaded successfully, version 3.3.0 NVIDIA 565.77, shading language 3.30 NVIDIA via Cg compiler
```

A key difference is that the log is now spammed with "debug: Cannot create EGLImage: EGL failed to allocate resources for the requested operation". The issue with XComposite windows not working at all still remains.

In any case, if this is still not an issue with OBS proper, I'll take to the forums / Discord as you suggest. Thanks! :heart:

**Comment by Aeres-u99** [comment]
@pcrain were you able to find the solution for this? In case there is any discord link can you please share that?

**Comment by pcrain** [comment]
@Aeres-u99 I just dug up my old Discord thread, and it ended up being a problem with the `mesa` package on Arch Linux. Here's the relevant part of my Discord post:

```
Just did some package downgrade bisection and it turns out Arch's latest mesa package 
of all things is what was causing the issues. 😓  Downgrading mesa from 1:24.3.2-1 
to 1:24.2.4-1 fixed all EGL issues with OBS and Java, and everything works even with 
the latest 565 NVidia drivers.

Posting here in case anyone else on Arch runs into this issue. 
```

And here's [the Discord link for posterity](https://discord.com/channels/348973006581923840/636682839382949888/1320822463361318934). Hope this helps with your issue as well. 🫡 ❤️
