### ISSUE TITLE
Encoding performance seriously degraded after upgrade to Windows 11 Pro 24H2 and OBS 31

### ISSUE THREAD

**Issue by scientastic** [obsproject/obs-studio#11666]
### Operating System Info

Windows 11

### OBS Studio Version

31.0.0

### OBS Studio Log URL

https://obsproject.com/logs/NFiVaRwFy9iHKYoL

### Expected Behavior

Streaming/encoding to perform as it had under OBS 30

### Current Behavior

Performance of streaming, specifically encoding, degraded drastically. Audio scrambled (popping, clicking at first, then large gaps in the audio, skipping and garbling). Video performance also suffered. I can share an unlisted YouTube URL if necessary.

### Steps to Reproduce

1. Let Windows apply the latest Windows Update to 24H2
2. Upgrade OBS to 31
3. Stream as normal...

(I don't have a way to go back to the previous setup for a detailed comparison)

### Anything else we should know?

I tried various Windows settings, including turning on Game Mode. This seemed to make a slight difference (improvement) but did not completely solve the issue.

I had to downgrade the video quality from 1080p to 720p to get it back to "normal." This is not an acceptable long-term solution.

The hardware is a Dell Optiplex 7060 with Intel i7-8700T at 2.40GHz and 32GB of RAM. This has kept up with our basic church live streaming needs (no gaming, only video sourced from 3 cameras over NDI, combined with an overlay from an HDMI input captured by a USB video capture device). We normally stream at 1080p and 29.97 FPS due to some legacy reasons.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
