### ISSUE TITLE
Randomly Changing Hotkeys

### ISSUE THREAD

**Issue by AvgGd** [obsproject/obs-studio#11669]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.1.0

### OBS Studio Log URL

i don't believe this requires a log but https://obsproject.com/logs/lSqOEVjGn07Dlhzz

### OBS Studio Crash Log URL

no crash

### Expected Behavior

it keeps the same hotkey and doesn't just randomly change it unwarranted

### Current Behavior

it just randomly changes the hotkeys, in my case it changes NUM 0 to INSERT just randomly. There isn't a pattern. It's happened ever since I've started using the clipping feature

### Steps to Reproduce

i genuinely have no idea, its just put NUM 0 from the number pad and it just randomly changes it.

### Anything else we should know?

its annoying

**Comment by Fenrirthviti** [comment]
Sounds like you're hitting numlock. KP_0 is also Insert without numlock on many keyboards.
