### ISSUE TITLE
Full OS crash when using media source

### ISSUE THREAD

**Issue by markisha64** [obsproject/obs-studio#11664]
### Operating System Info

Other

### Other OS

Garuda Linux (KDE + Wayland)

### OBS Studio Version

31.0.0

### OBS Studio Log URL

https://pastebin.com/Vk4EdwpB

### Expected Behavior

I except media source to work?

### Current Behavior

After a while (I was using 2 different videos, one would crash at ~48mins one at ~1hr) obs causes an amdgpu error and takes down the whole OS (only REISUB still works).

Stack Trace https://pastebin.com/WREqR3CU

### Steps to Reproduce

1. Use media source
2. record/stream for long enough depending on media source

### Anything else we should know?

CPU: Ryzen 7 5700x
GPU: Radeon Rx 6700

**Comment by derrod** [comment]
Sounds like something youdhould report to the thungs that's crashing (amdgpu), not us.
