### ISSUE TITLE
Screen capture on wayland using pipewire does not work

### ISSUE THREAD

**Issue by 64-bitman** [obsproject/obs-studio#11673]
### Operating System Info

Other

### Other OS

Fedora 41 Workstation 

### OBS Studio Version

31.0.0

### OBS Studio Log URL

https://obsproject.com/logs/t3g3sOVhR8GBkhFX

### Expected Behavior

See the actual current wayland session being displayed

### Current Behavior

Glitched out view is displayed instead (The mouse pointer is still visible however)

https://github.com/user-attachments/assets/d3999124-d916-465c-b244-17e734dfba3d

### Steps to Reproduce

1. Open OBS studio
2. Add `Screen Capture (Pipewire)` source

### Anything else we should know?

This only happens when I use the integrated GPU on my desktop. If I use my dedicated one (RX 580), OBS studio simply crashes and core dumps instantly without any subsequent log messages. Additionally, I tried using the official flatpak package, and this issue still persists.

**Comment by kkartaltepe** [comment]
Crashing on ancient amd cards will be fixed in the next hotfix. The misrendering is a limitation of such ancient cards and pipewire, its unlikely anyone cares enough to resolve that issue in pipewire and id recommend just buying something with modern driver support.

**Comment by 64-bitman** [comment]
> Crashing on ancient amd cards will be fixed in the next hotfix. The misrendering is a limitation of such ancient cards and pipewire, its unlikely anyone cares enough to resolve that issue in pipewire and id recommend just buying something with modern driver support.

Are you talking about the crashing issue on the RX 580? I opened this issue mainly on the non working screen capture for the integrated GPU (which is "modern"?)

**Comment by kkartaltepe** [comment]
Unplug the old gpu to fix the rendering glitch.

**Comment by 64-bitman** [comment]
> Unplug the old gpu to fix the rendering glitch.

So the RX 580 in my computer is causing the integrated GPU to glitch out in OBS? I just want to make sure.

**Comment by 64-bitman** [comment]
Any update on this?
