### ISSUE TITLE
When closing and reopening a captured windows, OBS will use the last frame of the previous windows instead of the new Window

### ISSUE THREAD

**Issue by Usinganame** [obsproject/obs-studio#11670]
### Operating System Info

Other

### Other OS

Debian 12.8

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/OkXbAtxDJ4MwCXS6

### Expected Behavior

The new window should be captured

### Current Behavior

The last frame of the previous window is displayed

### Steps to Reproduce

1. Open OBS and choose any application to capture though window capture
2. Close the application that is being captured
3. Reopen said application
...

### Anything else we should know?

This is run with GNOME 43.9 Wayland and installed as a native app.

**Comment by kkartaltepe** [comment]
We do not use GitHub Issues for support questions. And your obs is out of date.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
