### ISSUE TITLE
“Failed to initialize video” error upon startup

### ISSUE THREAD

**Issue by jacobalze** [obsproject/obs-studio#11681]
### Operating System Info

Other

### Other OS

Raspberry Pi Os (Linux) 

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.2.2

### OBS Studio Log URL

Can’t get this it won’t start

### OBS Studio Crash Log URL

N/A

### Expected Behavior

For the App to boot up and work

### Current Behavior

Got an error saying “Failed to initialize video. Your GPU may not be supported, or your graphics drivers may need to be updated.”

### Steps to Reproduce

1. Opened the app

### Anything else we should know?

I tried updating the graphics drivers and nothing changed. I was using a Raspberry Pi 3B. I tried switching over to a Pi 5 but still got the same error. I tried installing it different ways (through GitHub, Pi-Apps, Flatpak, and the terminal) and only GitHub and Pi-Apps worked to install it but I encountered the same error on both devices. It might be just my devices but I would appreciate any help.

**Comment by mihawk90** [comment]
Raspberry Pi is not currently a supported platform. The Pi-Apps are a third-party build so if you're having an issue with them you should ask in their support channels.
