### ISSUE TITLE
[Mac] Audio Output Capture doesn't display any devices

### ISSUE THREAD

**Issue by ElliotChong** [obsproject/obs-studio#178]
![image](https://cloud.githubusercontent.com/assets/270706/3589604/87b79c42-0c4f-11e4-85fa-01df12c67e68.png)

When creating an Audio Output Capture source the devices dropdown is empty on OSX. No audio is subsequently captured.

**Comment by Lekensteyn** [comment]
> It's because you probably don't have wavtap/soundflower installed. That particular source can only capture from wavtap or soundflower.

For those looking into this, BlackHole is the modern maintained equivalent that does not require a kernel driver. Instructions for setting it up can be found at https://github.com/ExistentialAudio/BlackHole/wiki/Multi-Output-Device, afterwards Blackhole 2ch becomes visible in OBS.
