### ISSUE TITLE
Starting a recording changes the minimum horizontal size of the main window

### ISSUE THREAD

**Issue by gongyoyo** [obsproject/obs-studio#2157]
I used the Chinese language.I drag the window in the minimal horizontal size.![picture1](https://user-images.githubusercontent.com/36725275/68074825-d92fd800-fdda-11e9-9f53-3ca67e6eae0f.png)

When I start reording.The horizontal size will be traction.If just start repaly button.It will be not.
I know the english word is longer than chinese and the new version add pause mode.
So the window must be traction longer to contain pause button.But chinese just has four word.
It do not need to traction longer the horizontal window's size.So please fix it.
![批注_2019-11-03_01-38-29](https://user-images.githubusercontent.com/36725275/68074835-ffee0e80-fdda-11e9-8639-1ed8c53fa15a.png)

Or you just add one future about locked the horizontal size!Please!😭
Because I am the severe obsessive-compulsive disorder.And not me!
There are a lot obsessive-compulsive disorder user around the world.I am just one of them.😂
Ok,all in all.Just fix it.OBS-Studio is the best recording software i had used.

**Comment by Fenrirthviti** [comment]
To clarify this issue, and replication steps for anyone who might want to take a look:

1. Set OBS to the minimum possible width.
2. Click `Start Recording`
3. Observe the minimum width of the main OBS window is increased (likely due to the Pause icon being added)
