### ISSUE TITLE
FPS capped in Minecraft after starting to record

### ISSUE THREAD

**Issue by Mrcubix** [obsproject/obs-studio#2163]
I know from a fact, i should be able to record 1080p 50FPS with my config which is :
- i3 4150-T 3.0 Ghz
- GT 1030 OC at 1.5 Ghz on clock speed and 6 Ghz on memory clock
- 8 GB DDR3 1600 Mhz
The fact the Gt 1030 doesn't have Nvenc should prevent me from recording at this framerate,
i can use some resources intensive shaders with this GPU usually at 50-60 FPS,
when recording, my CPU run at 80-85% and 90% memory usage (3.5 GB allocated to minecraft) .

If i start Minecraft, then i start OBS, then start recording, Minecraft fps suddenly cap at 30 FPS, and then if i close OBS and then i restart Minecraft, back to 60 FPS.

also skyrim 1080p med run at 50-55 FPS when recording (at 1080p 50 fps too)

any ideas on how to fix it?

**Comment by Fenrirthviti** [comment]
The GitHub issues is not for support requests.
