### ISSUE TITLE
Can't open OBS after running with arguments mode

### ISSUE THREAD

**Issue by r-martins** [obsproject/obs-studio#2164]
The OBS Studio GitHub issue tracker is **ONLY** to be used for reporting bugs that have replication steps. New features should be discussed on our [Discord](https://obsproject.com/discord/) or [Ideas](https://ideas.obsproject.com/) page. For support issues, use the Discord or [forums](https://obsproject.com/forum/)

## Expected Behavior
Open OBS without errors

## Current Behavior
Nothing happens, and after some seconts I see the error report window.
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/191149/68160821-ae937a00-ffa8-11e9-9db1-16f709810af6.png">

## Steps to Reproduce

1. Install OBS Mac 24.0.2 on MacOS Catalina
2. Run it via terminal (in order to fix permission problems) with `open /Applications/OBS.app/Contents/MacOS/OBS --args -picture`
3. Quit OBS
4. Try to open it via Spotlight or simply running OBS.app

## Additional information
The error reporting content is available at https://pastebin.com/PTKFk5pm

If I click on "Reopen", I get 2 alerts:
<img width="389" alt="Failed to find locale/en-US.ini" src="https://user-images.githubusercontent.com/191149/68161305-b7388000-ffa9-11e9-8bdd-54b348398fbc.png">
<img width="371" alt="Failed to load locale" src="https://user-images.githubusercontent.com/191149/68161322-c28bab80-ffa9-11e9-8685-14022bc5e83c.png">

**Comment by Fenrirthviti** [comment]
Catalina is not supported at this time.

https://obsproject.com/forum/threads/macos-10-15-catalina-support-status.111343/
