### ISSUE TITLE
Not Custom Dokk Panel

### ISSUE THREAD

**Issue by tyupika93** [obsproject/obs-studio#2169]
Hello, I can't add a custom Dockable panel. I use Linux as a Mate interface for a fresh installation
View-Dock menu
I can't take a picture of it because the system doesn't allow it

**Comment by kkartaltepe** [comment]
The GitHub issues is not for support requests.

**Comment by ElectronicWar** [comment]
Custom browser docks are not available on Linux yet. This will come once the official browser source is finished for Linux.
