### ISSUE TITLE
Twitch popout URLs not processing correctly in dockable view

### ISSUE THREAD

**Issue by LanceLake** [obsproject/obs-studio#2173]
The OBS Studio GitHub issue tracker is **ONLY** to be used for reporting bugs that have replication steps. New features should be discussed on our [Discord](https://obsproject.com/discord/) or [Ideas](https://ideas.obsproject.com/) page. For support issues, use the Discord or [forums](https://obsproject.com/forum/)

When pulling up URLs in pop out windows for twitch, they load the full page, not the custom window.

## Expected Behavior
The window should look like how the popup window looks, not the page that launched it.

## Current Behavior
The window shows the full dashboard and not the window that was popped out. 

## Steps to Reproduce
1. Log into a twitch account. 
2. Go to the live dashboard (not the new one, but the older one). 
3. Go down to polls.
4. Click pop out and notice that it works.
5. Copy the URL.
6. Add a dockable URL window in OBS and use that URL.
7. Note how it loads up the full dashboard and not just the polls.

## Additional information
I noticed that if I copy and paste the URL into another window on my browser, it does the same thing (loading https://www.twitch.tv/(ChannelName)/dashboard/live?no-reload=true). I talked to Twitch about this (thinking it was their issue), but the techs there said that it was an OBS issue. So they may be passing the buck. But just in case they aren't, I'm making this ticket in case there is something you guys can do on your side.

**Comment by Fenrirthviti** [comment]
PR here for this issue: https://github.com/obsproject/obs-studio/pull/2042

**Comment by Fenrirthviti** [comment]
PR has been merged.
