### ISSUE TITLE
Left 4 Dead 2 black screen

### ISSUE THREAD

**Issue by lunatixxx** [obsproject/obs-studio#2174]
Windows 7 (64 bits)
OBS version 24.0.3 
GTX 970 driver : 441.08

Game in full screen + game capture = black screen
Game in borderless fullscreen + window capture = black screen
Game in borderless fullscreen + window capture + aero disabled = Working

Full screen capture was working some years ago with this game, can't say if it is a problem with OBS  / nvidia drivers or even with an update of the game.

Forum post : https://steamcommunity.com/app/550/discussions/0/1640927348822566151/

**Comment by kkartaltepe** [comment]
The GitHub issues is not for support requests.

Please use the forums or discord.
https://discord.gg/obsproject
https://obsproject.com/forum
