### ISSUE TITLE
Linux Browser not loading some Streamlabs URLS, ChatBox in particular

### ISSUE THREAD

**Issue by calexil** [obsproject/obs-studio#2175]
## Expected Behavior
Steamlabs Urls should load items(chat, goals, alerts)

## Current Behavior
Some items load, chatbox does not

## Steps to Reproduce
Linux mint 19.1 tessa
Mate
obs 24.x stable
Linux browser

1.Try reloading, no change
2. try restarting browser, no change
3. restart obs, no change
4. restart pc, no change

## Additional information
Further reading: 

https://github.com/bazukas/obs-linuxbrowser/issues/118

**Comment by Fenrirthviti** [comment]
The Linux browser source is currently maintained by a third party. Please submit your issue on their repo for more assistance.

https://github.com/bazukas/obs-linuxbrowser
