### ISSUE TITLE
sh script wants to record key presses after installing OBS Studio (MacOS)

### ISSUE THREAD

**Issue by ianrandmckenzie** [obsproject/obs-studio#2176]
## Expected Behavior
I don't expect OBS Studio to need to record my keypresses.

## Current Behavior
I get a security warning on my Mac saying an `sh` app wants to record my key presses. I clicked Deny.

## Steps to Reproduce
1. Make sure your security settings don't allow key recordings without permission
2. Install OBS on MacOS Catalina
3. Go through setup wizard
4. Close OBS

**Comment by tehbasshunter** [comment]
This is so you can set hotkeys in settings. How else would you switch scenes via your keyboard?

**Comment by derrod** [comment]
OBS requires access to keypresses for hotkeys. It currently shows up as "sh" because it uses a script to launch the main binary. This will be fixed with the Catalina update.
