### ISSUE TITLE
Enable looping in Media source or add remote file in "Images" with looping setting

### ISSUE THREAD

**Issue by karl-police** [obsproject/obs-studio#2178]
The OBS Studio GitHub issue tracker is **ONLY** to be used for reporting bugs that have replication steps. New features should be discussed on our [Discord](https://obsproject.com/discord/) or [Ideas](https://ideas.obsproject.com/) page. For support issues, use the Discord or [forums](https://obsproject.com/forum/)

In media source, local files have the option "Loop" and "remote files" do not. So if I load up a .GIF it won't restart the animation because there is no Loop.

Also since Media source also adds a new audio bar in the audio mixer, maybe a remote option could be added in the "Image" part with the same stuff media source has just that it's especially for images and do not add a media audio thing, even though you can hide it with right click, but it still exists.

```
if (is_local_file) {
        input = (char *)obs_data_get_string(settings, "local_file");
        input_format = NULL;
        s->is_looping = obs_data_get_bool(settings, "looping");
        s->close_when_inactive =
            obs_data_get_bool(settings, "close_when_inactive");
    } else {
        input = (char *)obs_data_get_string(settings, "input");
        input_format =
            (char *)obs_data_get_string(settings, "input_format");
        s->is_looping = false;
        s->close_when_inactive = true;
    }
```

## Expected Behavior

It's not a bug, it's just something that hasn't been added?

**Comment by WizardCM** [comment]
GitHub issues is only for issues. Please submit feature requests to https://ideas.obsproject.com/
