### ISSUE TITLE
Can't run obs on intel graphics

### ISSUE THREAD

**Issue by TooYoungTooSimp** [obsproject/obs-studio#2181]
The OBS Studio GitHub issue tracker is **ONLY** to be used for reporting bugs that have replication steps. New features should be discussed on our [Discord](https://obsproject.com/discord/) or [Ideas](https://ideas.obsproject.com/) page. For support issues, use the Discord or [forums](https://obsproject.com/forum/)

## Expected Behavior

Run obs on intel graphic card and use nvenc to encode video

## Current Behavior

Either I can use nvenc with get black screen when capturing a full display,
or I use x264 to encode with nvidia graphic card disabled, which cause a lot cpu usage.

## Steps to Reproduce

1. Set obs64.exe to use integrate intel graphic card.
2. Open obs64.exe
3. Display capture gives a black screen
4. Disable nvidia gpu, I can capture screen now,
5. but I can't use nvenc, so I had to use x264 or quicksync which cause high cpu usage or significant display lag and glich.

## Additional information

![image](https://user-images.githubusercontent.com/6648049/69005915-69d1f080-0963-11ea-9993-135da45d3a9e.png)
![image](https://user-images.githubusercontent.com/6648049/69005918-6fc7d180-0963-11ea-96ce-44e8ddf5d0cb.png)
![image](https://user-images.githubusercontent.com/6648049/69005933-95ed7180-0963-11ea-9c90-8bc12968a5d2.png)
[A log file](https://obsproject.com/logs/4CRGFLjziVltleOt)

**Comment by derrod** [comment]
The GitHub issues are not for support requests. Use our forums or discord for that.

Please see our wiki for how to switch between GPUs on switchable laptops: https://github.com/obsproject/obs-studio/wiki/Laptop-Troubleshooting-Windows-10
