### ISSUE TITLE
Building on macOS 10.15.1 fails in Linking CXX shared library libobs-scripting.dylib step

### ISSUE THREAD

**Issue by zWaR** [obsproject/obs-studio#2182]
When building on a macOS 10.15.1 build fails in the Linking CXX shared library libobs-scripting.dylib step.

## Expected Behavior

Running cmake would build OBS 

## Current Behavior

When running cmake:

```bash
➜ cmake .. && make
-- OBS_VERSION: 24.0.3-138-g0adb5b81
-- Found FFmpeg: /usr/local/Cellar/ffmpeg/4.1.4_1/lib/../lib/libavcodec.dylib (found version "58.35.100") found components:  avcodec avdevice avutil avformat
-- Luajit support not found.
-- Scripting: Python 3 supported
-- Jansson >=2.5 not found, building bundled version
C compiler: Clang
-- Found FFmpeg: /usr/local/Cellar/ffmpeg/4.1.4_1/lib/../lib/libavformat.dylib (found version "58.20.100") found components:  avformat avutil swscale swresample avcodec
-- Using libavcodec for image loading in libobs
-- Could NOT find LibVLC_INCLUDES (missing: VLC_INCLUDE_DIR)
-- LibVLC includes not found, VLC video plugin disabled
-- Checking for module 'jack'
--   No package 'jack' found
-- JACK Audio Connection Kit not found, disabling JACK plugin
-- Using the bundled VST header.
-- Found FFmpeg: /usr/local/Cellar/ffmpeg/4.1.4_1/lib/../lib/libavcodec.dylib (found version "58.35.100") found components:  avcodec avfilter avdevice avutil swscale avformat swresample
-- Found FFmpeg: /usr/local/Cellar/ffmpeg/4.1.4_1/lib/../lib/libavcodec.dylib (found version "58.35.100") found components:  avcodec avutil avformat
-- SpeexDSP support not found
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/ukolar/Development/experiments/obs-studio/build
[  1%] Built target glad
[  2%] Built target media-playback
[  5%] Built target jansson
[ 26%] Built target libobs
[ 27%] Built target file-updater
[ 28%] Built target obs-frontend-api
[ 29%] Linking CXX shared library libobs-scripting.dylib
Undefined symbols for architecture x86_64:
  "_PyDict_New", referenced from:
      _libobs_to_py_ in obs-scripting-python.c.o
  "_PyTuple_New", referenced from:
      _libobs_to_py_ in obs-scripting-python.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [deps/obs-scripting/libobs-scripting.dylib] Error 1
make[1]: *** [deps/obs-scripting/CMakeFiles/obs-scripting.dir/all] Error 2
make: *** [all] Error 2
```

## Steps to Reproduce

1. Follow build guide https://github.com/obsproject/obs-studio/wiki/Install-Instructions#macos-build-directions
2. Run `cmake .. && make` out of the build folder, as directed by the documentation

Any help to resolve this would be welcome!

**Comment by Fenrirthviti** [comment]
Python does not currently work on macOS. Please disable it for your build and try again.

**Comment by zWaR** [comment]
Thanks @Fenrirthviti! How can I disable it?

**Comment by Fenrirthviti** [comment]
Disable the flag in cmake.

Alternately, you can try the changes in this PR that may fix the problem: https://github.com/obsproject/obs-studio/pull/2183

**Comment by jp9000** [comment]
The PR has been merged.  Could you clear cache and try with latest master branch again?

**Comment by ratwithacompiler** [comment]
I usually get those errors when building against an incompatible python version, if you do actually want python support you'll probably wanna install 3.6 or 3.7 for now. 3.8 doesn't work I think.

**Comment by furiousgreencloud** [comment]
I'm also getting this had to add `-lpython` into: 

`<your build dir>/deps/obs-scripting/CMakeFiles/obs-scripting.dir/link.txt`

before the last parameter (which is  ../../libobs/libobs.0.dylib on my build)

unfortunately the python load from my path:
```
[Python]
Path64bit=/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7

```
will then Segmentation fault: 11 on Py_Initialize():

![image](https://user-images.githubusercontent.com/1821255/69119364-32d70a00-0a4b-11ea-805f-bc5804768d54.png)

---------

ps, i thought this doing:

```
CFLAGS=-I$(brew --prefix)/include LDFLAGS=-L$(brew --prefix)/lib cmake ..
CFLAGS=-I$(brew --prefix)/include LDFLAGS=-L$(brew --prefix)/lib make 
```

would help, from [Brewed Python modules Docs]( https://docs.brew.sh/Homebrew-and-Python#brewed-python-modules), but it did not.

---------

My System: MacOS 10.13.4, XCode 9.3, Python 3.7.5 (from brew)

**Comment by LukeKeywalker** [comment]
It happens when your default Python instalation is version 3.X. I've fixed it by adding:
```
find_package( PythonInterp 2.7 REQUIRED )
find_package( PythonLibs 2.7 REQUIRED )
```
at the beginning of main CMakeLists.txt

**Comment by furiousgreencloud** [comment]
hmmm, thanks Luke, but still failing on link, and after manual insertion of `-lpython` into 

`<your build dir>/deps/obs-scripting/CMakeFiles/obs-scripting.dir/link.txt`

, i can build but same crash, sticking with Azure Build for now to get Python scripting. Maybe my XCode is too old?

![Screen Shot 2019-11-27 at 13 12 53](https://user-images.githubusercontent.com/1821255/69760065-6800ed80-1118-11ea-8f3a-e4133371f746.png)

![Screen Shot 2019-11-27 at 13 12 33](https://user-images.githubusercontent.com/1821255/69760104-7c44ea80-1118-11ea-950e-185d28972f5d.png)

My System: MacOS 10.13.4, XCode 9.3, Python 3.7.5 and 2.7.17 (from brew)

**Comment by songmink** [comment]
Find your 'python include directory' and
`$> cmake -DPYTHON_INCLUDE_DIR=[your python include directory] .. && make`

I am using pyenv and python3.7, so I did like this
`$> cmake -DPYTHON_INCLUDE_DIR=~/.pyenv/versions/3.7.4/include/python3.7m .. && make`

[FindPythonLibs Document](https://cmake.org/cmake/help/v3.0/module/FindPythonLibs.html)
[Homebrew python document](https://docs.brew.sh/Homebrew-and-Python)

**Comment by furiousgreencloud** [comment]
Thank you @songmink can you describe your build environment?

i still get a build fail using this method,

```
cmake -DPYTHON_INCLUDE_DIR=/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/include/python3.7m .. 
```

gives, 

Scripting: Python 3 supported, but then the build failed on: 

```
Undefined symbols for architecture x86_64:
  "_PyDict_New", referenced from:
      _libobs_to_py_ in obs-scripting-python.c.o
  "_PyTuple_New", referenced from:
      _libobs_to_py_ in obs-scripting-python.c.o
ld: symbol(s) not found for architecture x86_64
```

same as the original poster's problem.

**Comment by keyboardcowgirl** [comment]
The problem I can see right away is this block, at the top of the file _obs/deps/obs-scripting/obs-scripting-python-import.c_:

```c++
#ifdef __APPLE__
#define PYTHON_LIB_SUBDIR "lib/"
#else
#define PYTHON_LIB_SUBDIR ""
#endif
```

Even if you were to specify the exact location of your `PYTHON_INCLUDE_DIR`, the `PYTHON_LIB_SUBDIR` is still appended. There are many patches to be made, but that one in particular is the one that ruins your command-line path setting.

**Comment by willlllllio** [comment]
> The problem I can see right away is this block, at the top of the file _obs/deps/obs-scripting/obs-scripting-python-import.c_:
> 
> ```c++
> #ifdef __APPLE__
> #define PYTHON_LIB_SUBDIR "lib/"
> #else
> #define PYTHON_LIB_SUBDIR ""
> #endif
> ```
> 
> Even if you were to specify the exact location of your `PYTHON_INCLUDE_DIR`, the `PYTHON_LIB_SUBDIR` is still appended. There are many patches to be made, but that one in particular is the one that ruins your command-line path setting.

That block just turns the lib name `libpython3.6m` into `lib/libpython3.6m` on macOS at runtime when trying to load Python and is unrelated to any compiling error you may have and the `PYTHON_INCLUDE_DIR`path is not directly related to that anyway.

**Comment by keyboardcowgirl** [comment]
That's the only thing I can see right away. I still use an old patched-up scripting build (see attached zip) that's never failed me on either Mojave or Catalina. There's a lot of differences in a variety of the files, but both Lua and Python work on my system.

If only I could compile the new rep, but that's unrelated.

[obs-scripting.zip](https://github.com/obsproject/obs-studio/files/4078607/obs-scripting.zip)

**Comment by Fenrirthviti** [comment]
Going to close this for now as it's not clear if this is a bug or just an issue with build environments Everything has been building just fine in our CI, and I would recommend looking at the newly updated CI scripts for reference. If you are still having issues building, or have identified the exact issue with replicable steps, feel free to either reopen this or submit a new bug report. That said, I would prefer to leave general troubleshooting for self-building to our [Discord](https://obsproject.com/discord) or [Forums](https://obsproject.com/forum).
