### ISSUE TITLE
Record selected area on screen

### ISSUE THREAD

**Issue by ArchiveBase** [obsproject/obs-studio#2185]
#### Expected Behavior
We need an option to define selected area on screen to record.

It can be add as Sources > Flexible Display Capture > let user to select the area (it's not necessary such drawing facilities; just within that properties window basically allow to reduce area from all corners(gui) or input width/height in specific field(easy) to adjust necessary recording space > ok(add)

#### Current Behavior
Currently only able record whole screen or window however window capture not detect most applications https://github.com/obsproject/obs-studio/issues/2160 [chrome] and mirrorgo etc

#### Additional information
https://www.apowersoft.com/free-online-screen-recorder
_(Flexible Screen Capture feature)_

**Comment by derrod** [comment]
The GitHub issues are for bugs, not for suggestions, see https://ideas.obsproject.com/ for that (and it already exists as https://ideas.obsproject.com/posts/262/selecting-sub-region-display-capture).
