### ISSUE TITLE
Pick scene profile from system tray and start record

### ISSUE THREAD

**Issue by ArchiveBase** [obsproject/obs-studio#2186]
#### Expected Behavior
We usually keep several scene profiles collections with single or multiple sources for each and OBS Studio allows to start recording and start recording through system tray (it really perfect for hurry persons like us). 

- Add an option to select desired scene through system tray.
![image](https://user-images.githubusercontent.com/46082456/69141365-34f6a280-0af7-11ea-9c4e-b002a336470b.png)

- Display the current active scene on the top.
 
![image](https://user-images.githubusercontent.com/46082456/69141772-088f5600-0af8-11ea-909e-587cc6553286.png)

#### Current Behavior
User need to open OBS Studio window and select the profile through 'Scene Collection' then start record

**Comment by notr1ch** [comment]
Github issues is for bugs, not feature requests. Please use https://ideas.obsproject.com/ for feature suggestions.
