### ISSUE TITLE
Crashes when Built-In device camera selected for Video Capture Device (MacOS)

### ISSUE THREAD

**Issue by ianrandmckenzie** [obsproject/obs-studio#2188]
Sorry, another issue. Hopefully, this time it isn't slightly on the side of user error.

## Expected Behavior
Video capture device lets me select my device's built-in camera as a device. Because this requires system permission, I also expect OBS Studio to ask permission to access my built-in camera.

## Current Behavior
When I select my built-in camera as a Video Capture Device, does not ask for permission to use my camera, and instead, OBS crashes.

## Steps to Reproduce
1. Select a scene
2. Click the + under Sources
3. Select Video Capture Device
4. Under Device, select FaceTime HD Camera (Built-In) (the camera on most MacOS devices manufactured by Apple)
5. (the app will crash)

## Additional information
I am on the latest Catalina version of MacOS. My system is the iMac (Retina 5k, 27-inch, Late 2015)

**Comment by Fenrirthviti** [comment]
https://obsproject.com/forum/threads/macos-10-15-catalina-support-status.111343/

**Comment by ianrandmckenzie** [comment]
Thanks! Downloading the test release also fixed a bunch of other issues I ran into, including the last one. Closing this down.
