### ISSUE TITLE
Add Jami Service

### ISSUE THREAD

**Issue by ovari** [obsproject/obs-studio#2190]
Please add [Jami](https://jami.net/) to the `Service` drop-down as shown in the image below.

![image](https://user-images.githubusercontent.com/17465872/69405807-b860ff80-0d54-11ea-8840-5be9207afd45.png)

Use-case: OBS Studio use for virtual camera for screen sharing in Jami VoIP call
https://git.jami.net/savoirfairelinux/ring-daemon/issues/182#note_16309 

Please advise if you require any further information.

Thank you

**Comment by tielqt** [comment]
The OBS Studio GitHub issue tracker is **ONLY** to be used for reporting bugs that have replication steps. New features should be discussed on our [Discord](https://obsproject.com/discord/) or [Ideas](https://ideas.obsproject.com/) page. For support issues, use the Discord or [forums](https://obsproject.com/forum/)
