### ISSUE TITLE
Browser ignores video autoplay

### ISSUE THREAD

**Issue by delongerr** [obsproject/obs-studio#2191]
## Expected Behavior
Browser doesn't ignore video autoplay

## Current Behavior
Browser ignores video autoplay 

## Steps to Reproduce
1. [Download](https://drive.google.com/file/d/1Sa_3G16kOd8FtyUB6qfcsUHuxajEsZex/view?usp=sharing) and unzip archive widget.zip
2. Open OBS
3. Click on "Plus" in sources and select "Browser"
4. Click "OK"
5. Set checkbox "Local file"
6. Browse our widget (widget/index.html)
7. Click "OK"

## Additional information
OBS v24.0.2
macOS 10.14.6

**Comment by derrod** [comment]
This repo is for bugs and issues related to obs-studio, the browser source is a separate plugin with its own issue tracker: https://github.com/obsproject/obs-browser/issues
