### ISSUE TITLE
Wrong mouse cursor location w/ top or left cropped window capture

### ISSUE THREAD

**Issue by ajh3** [obsproject/obs-studio#2197]
Ubuntu 18.04.3 LTS
Thinkpad T480 w/ Integrated Intel® UHD Graphics 620
Dual 1920x1200 monitors

OBS shows the mouse cursor in the wrong place when doing a **top or left cropped** Window Capture (Xcomposite). Right or bottom crops appear to work correctly.

## Steps to Reproduce

1. Create a new Window Capture (Xcomposite) source
2. Select any window for the capture
3. Set a top or left crop
4. The mouse cursor in the preview/recording is now in the wrong place, compared to its actual location on the screen

**Comment by WizardCM** [comment]
This was fixed in https://github.com/obsproject/obs-studio/pull/2152 and will be available in the next release.

**Comment by Fenrirthviti** [comment]
Closing as this fix is already merged.
