### ISSUE TITLE
No application windows exhibited for selection

### ISSUE THREAD

**Issue by Ricky-Tigg** [obsproject/obs-studio#2200]
No application windows exhibited for selection.

## Expected Behavior

Opened applications windows to be exhibited for selection as it is the case under _Gnome on Xorg_ sessions.

## Current Behavior

Opened applications windows are not exhibited for selection.

## Steps to Reproduce

1. Log in into a Gnome on Wayland session –which is the default on Fedora Linux Desktop–;
2. Under section  _Sources_,  select option _Window Capture (Xcomposite)_ 

## Additional information

Log file: [2019-11-26 11-14-54.txt](https://github.com/obsproject/obs-studio/files/3890977/2019-11-26.11-14-54.txt)

**Comment by Fenrirthviti** [comment]
Wayland is not currently supported.
