### ISSUE TITLE
[Linux][OBS Studio 24.0.3-1 64bit] Scene Item Tranfsorm Crop Calculation problems

### ISSUE THREAD

**Issue by ifohancroft** [obsproject/obs-studio#2204]
The issue may also be present in other operating systems, however I can only confirm for Linux as this is where I am experiencing it.

The steps to reproduce will better explain the issue but here is a general, free form explanation:
When you import a scene with a single item that has resolution smaller than the overall resolution used as a source in another scene and then you resize it and crop it, the crop is calculated wrong.

Steps to reproduce:
1. Set your base and output resolution in OBS Studio as 1920x1080
2. Create a scene and inside it create a single source (in my case, this is my webcam). Set the source's resolution to 1280x720
3. Create another scene and inside it create a scene source and select the previously created scene (the one that has your webcam).
4. Right click the scene source and go to Tranfsorm > Edit Transform
5. Set size to 480x270
6. Make sure Bounding Box's type, alignment and size are default (no bounds, center, 1, 1)
7. Set Crop Right to 160 and Crop Bottom to 90 while leaving Crop Left and Crop Top to 0.

When you have a canvas (generally speaking, not the OBS canvas) with the size of 1920x1080 with a content of 1280x720 and you scale the canvas to 480x270, the free space around the content is 160px width to the right and 90px height to the bottom. However, in the OBS case, when you Crop Right 160px and Crop Bottom 90px it doesn't crop all the empty space.
The crop and maybe also the content sizes are calculated wrong or something like that.

**Comment by kkartaltepe** [comment]
This appears working as intended. The crops apply before the scaling transforms.

**Comment by RytoEX** [comment]
I reached the same conclusion as @kkartaltepe.  Crop calculations are done based on the source's original size before scaling, rather than referring to pixels on the current overall OBS canvas.  Otherwise, you'd have to constantly recalculate what the appropriate crop is based on your source scaling rather than the known sizes of the source.

**Comment by Fenrirthviti** [comment]
Going to close for now. Feel free to reopen if you have a compelling argument on why it should work otherwise. I suspect changing this will only confuse most users.

**Comment by ifohancroft** [comment]
You are right. I have understood where my confusion comes from:

1. Not knowing at first that crops are being applied to original size, not to resize
2. Because of the way the size borders cover part of the source when you have them visible, it looks like you need to crop just 626 pixels from the right and 345 from the bottom to get fully rid of the whitespace, but instead you actually need to crop 640 pixels from the right and 360 from the bottom (just as expected).

I agree that the crop should continue working as it currently does.

Although maybe the position should start working the way the crop does, as it currently depends on both resize and crop so for example in my test scenario:
1920x1080 scene with a 1280x720 source, rezised to 480x270 and right (doesn't really matter if right or left crop) crop of 640 and bottom (again, doesn't really matter top or bottom crop) crop of 360 pixel, if I want to position the resulting rectangle in the top right corner (it's easy to do that by mouse movement and snapping but I am just using the top right corner as an easy example, if you want to actually put it at a specific place on the screen (like a stream overlay that you want your notifications to show on top of) it would be very hard) I need to know the size of the resulting content is 320x180 which I couldn't think of a way to calculate so I had to put heavy contrasting content and background, open full screen projector, screen shot it, then measure the size in GIMP so I know what to put for size. Although this is not really the topic of this ticket/issue.
