### ISSUE TITLE
Audio sync issue in Browser via "Control audio via OBS" 

### ISSUE THREAD

**Issue by sebseb7** [obsproject/obs-studio#2207]
Windows Browser Plugin:

When "Control Audio via OBS" is checked audio is ~1 second out of sync (delayed)

**Comment by WizardCM** [comment]
Closing this ticket as it doesn't include a filled out issue template, and because the browser plugin has its own repository found [here](https://github.com/obsproject/obs-browser/issues). Please submit your issue there, and be sure to fill out the issue template.
