### ISSUE TITLE
The Stats dock steals focus from the main window at startup

### ISSUE THREAD

**Issue by UserNaem** [obsproject/obs-studio#2209]
## Steps to Reproduce
1. Enable the Stats dock in View > Docks.
2. Quit and restart obs-studio.
3. Press Alt+F4

## Expected Behavior
After step 3, the main window should close, quitting obs-studio.

## Current Behavior
After step 3, the Stats dock is closed.

## Additional information
This reproduces on Windows 7 and Windows 10 1903, can try to reproduce on Linux w/ KDE too if needed.

**Comment by Nexidian** [comment]
@UserNaem I can't seem to replicate this on windows 10 using the listed steps. This issue was opened a while ago, it may be have fixed already.

**Comment by UserNaem** [comment]
@Nexidian Make sure obs-studio is allowed to steal focus from the currently active window. I have "Focus assist" disabled, and I launched obs-studio from the Start menu using search results, not using the mouse. Still reproduces.

**Comment by Bennik2000** [comment]
I was able to reproduce this issue, it is still a bug in v 25.0.8

**Comment by notr1ch** [comment]
The main window remains in focus for me after startup with a popped out stats dock. There must be some other variable required to reproduce this.

**Comment by UserNaem** [comment]
@notr1ch Yes, make sure the Stats sock is docked and not floating.

**Comment by notr1ch** [comment]
That was it, didn't expect those would even respond to Alt+F4.

**Comment by Bennik2000** [comment]
They do. But its unexpected that the dock closes instead of the main window when pressing Alt+F4

**Comment by Bennik2000** [comment]
I fond a similar bug which causes the program view to close when in studio mode: 

1. Start OBS and enable Studio Mode
2. Close OBS with the [x]
3. Start OBS again
4. Press Alt+F4

Expected behavior: 
The main OBS Window closes

Actual behavior: 
The preview disappears

The PR #2915 fixes both bugs

**Comment by notr1ch** [comment]
Is there also a flag we could sent on the widgets to mark them as not closable? I am very surprised that it's even possible to close the program window with Alt+F4.

**Comment by WizardCM** [comment]
This bug was fixed with #2915. Closing.
