### ISSUE TITLE
AMD Encoder is outdated in the latest OBS installation bundle (Windows)

### ISSUE THREAD

**Issue by minhngoc25a** [obsproject/obs-studio#2214]
The OBS Studio GitHub issue tracker is **ONLY** to be used for reporting bugs that have replication steps. New features should be discussed on our [Discord](https://obsproject.com/discord/) or [Ideas](https://ideas.obsproject.com/) page. For support issues, use the Discord or [forums](https://obsproject.com/forum/)

## Expected Behavior

OBS Studio launches normally

## Current Behavior

OBS crashes on startup

## Steps to Reproduce

Launching OBS

## Solution
Install the updated AMD Encoder from OBS Project Resources.

## Additional information

You need to include a newer AMD encoder version in the upcoming installer of OBS Studio.

**Comment by FerretBomb** [comment]
Yes, that happens on each new release of OBS.

**Comment by Xaymar** [comment]
This isn't technically a bug as the update for the AMD Encoder was released _after_ obs released.

**Comment by derrod** [comment]
See above.
