### ISSUE TITLE
Fonts don't get reloaded in-app

### ISSUE THREAD

**Issue by WizardCM** [obsproject/obs-studio#2217]
## Expected Behavior
New fonts added to the operating system should be available after the properties window has been restarted

## Current Behavior
The user has to restart the application for new fonts to be loaded.

## Steps to Reproduce
1. Install a new font to your OS (Windows, for example)
2. Open the properties window of a source
3. Open the font selector
4. New font should be available, but isn't

## Additional information
Tested on Windows 10 with fonts installed globally ("All Users" vs "Current User")

**Comment by ryantheleach** [comment]
How would you expect this to be implemented? Just not cache the font store, and load the list everytime the UI element is displayed?

I doubt you would want file watchers for this sort of thing...

I guess you could cache the fetch time, and compare it to last modified on the font folder?

**Comment by jp9000** [comment]
In terms of GDI+ on Windows, I think the API or something in GDI/etc is caching the font data internally on startup.  So it might not really be easy to solve.

Plus I don't really think this is that important personally.  I feel like it's insignificant and not worth expending manpower on.

**Comment by Fenrirthviti** [comment]
Going to close this for now as I agree with Jim's comments. If anyone wants to tackle this and open a PR, please feel free but it doesn't seem like it's worth the effort, as you can just easily restart OBS, and I don't feel people will be involved with workflows where they are adding fonts while OBS is open with any kind of regularity. This feels like a non-issue.
