### ISSUE TITLE
Filters with OBS_SOURCE_CUSTOM_DRAW can't be added to Sources that do not have this flag

### ISSUE THREAD

**Issue by Xaymar** [obsproject/obs-studio#2223]
## Expected Behavior
A filter with the flag OBS_SOURCE_CUSTOM_DRAW should be able to be added to a Source without the flag. 

## Current Behavior
Filters that have the flag OBS_SOURCE_CUSTOM_DRAW can't be added to sources without the flag. The dialog opens, the filter is created, and immediately destroyed again.

## Steps to Reproduce
1. Install OBS Stream Effects v0.7.2
2. Add a Video Capture Source
3. Add a Displacement Mapping Filter to that source.
4. Add a Displacement Mapping Filter to that source. (repeat endlessly as this won't succeed)

## Additional information
`filter_compatible` in obs-source.c L2254 is the culprit. The function should be changed as the way it checks right now is pretty much broken.

**Comment by Xaymar** [comment]
This may even apply to more flags, such as OBS_SOURCE_COMPOSITE on a filter, OBS_SOURCE_DEPRECATED on a filter, etc.

**Comment by jp9000** [comment]
Fixed here:
https://github.com/obsproject/obs-studio/commit/c1522019e08ce44236c9c44d9b4b90ec17a3a38d
