### ISSUE TITLE
OBS Studio gets crashing when selecting Word Vision USB Video capture device (04b4:00ed) as input source on macOS Catalina

### ISSUE THREAD

**Issue by ItoSchum** [obsproject/obs-studio#2226]
## Expected Behavior

The capture device Word Vision USB Video (04b4:00ed) should be successfully selected as the Video Capture Device without crashing.

## Current Behavior

OBS will crash and quit as the Word Vision USB Video (04b4:00ed) gets selected.

## Steps to Reproduce

1. Open up OBS and change the Video Capture Device settings
2. Set the Word Vision USB Video as the Video Capture Device

## Additional information

1. The USB capture card I used:
Product ID: 0x00ed
Vendor ID: 0x04b4
2. OBS Studio Version: 24.0.2
3. OS Version: macOS 10.15.1 (19B88)
4. Auto-generated bug report: [obs_bug_report.txt](https://github.com/obsproject/obs-studio/files/3930651/obs_bug_report.txt)

**Comment by Fenrirthviti** [comment]
Catalina is not currently supported. Please see #2165 for more details (and a link to our beta build which should work properly).
