### ISSUE TITLE
Window Capture (Xcomposite) doesn't list any windows

### ISSUE THREAD

**Issue by l29ah** [obsproject/obs-studio#2237]
## Expected Behavior

It should work.

## Current Behavior
![](https://pstbin.ru/f/94879/)

## Steps to Reproduce
1. run obs
2. add xcompose backend

## Additional information
obs-studio-24.0.3 on Gentoo GNU/Linux with xorg-server-1.20.6, xmonad window manager and Intel video.

**Comment by kkartaltepe** [comment]
`<!--- Please include a log file here if possible. -->`
Issues are also not for support. Please use the discord for that. Iirc this WM does not support the appropriate standards to list windows. You are expected to implement it yourself.

**Comment by l29ah** [comment]
Here you go: 
[2019-12-12 19-24-34.txt](https://github.com/obsproject/obs-studio/files/3956815/2019-12-12.19-24-34.txt)

Silent failure is a bug.

What standards are you talking about? It's not mentioned anywhere in the UI or docs.

**Comment by kkartaltepe** [comment]
http://standards.freedesktop.org/wm-spec/wm-spec-latest.html

I recommend you file a bug against your WM as falsely advertising standards compliance. Or better yet just use a different one.

**Comment by l29ah** [comment]
404
The page you're looking for could not be found.

**Comment by Heufneutje** [comment]
That page very much exists. I can access it right now.

**Comment by l29ah** [comment]
```
‰ wget http://standards.freedesktop.org/wm-spec/wm-spec-latest.html
URL transformed to HTTPS due to an HSTS policy
--2019-12-13 19:50:52--  https://standards.freedesktop.org/wm-spec/wm-spec-latest.html
Resolving standards.freedesktop.org (standards.freedesktop.org)... 131.252.210.176, 2610:10:20:722:a800:ff:feda:470f
Connecting to standards.freedesktop.org (standards.freedesktop.org)|131.252.210.176|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-12-13 19:50:55 ERROR 404: Not Found.
```

**Comment by dodgepong** [comment]
Try this: https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html
