### ISSUE TITLE
obs_properties_remove_by_name corrupts obs_properties_t object

### ISSUE THREAD

**Issue by Xaymar** [obsproject/obs-studio#2262]
If a Source, Filter or Transition adds properties in the modified properties callback, the properties don't show up unless the properties window is reopened.

## Expected Behavior
Newly added properties show up when `true` is returned from the callback.

## Current Behavior
Newly added properties take up memory space but do not show up. 

## Steps to Reproduce
1. Call obs_properties_add_... in any properties_modified callback after the first update.

## Additional information
Debugging revealed that even though these properties are created, they seem to not appear in the obs_properties_t* structure at all (RefreshProperties skips over the loop for content). It's like there is a check failing somewhere, or a duplicate of the obs_properties_t*.

**Comment by Xaymar** [comment]
Quite sure this is again related to obs_properties_remove_by_name. Working on a fix.

**Comment by Xaymar** [comment]
Fix available as #2257, which also fixes another issue.

**Comment by Xaymar** [comment]
This is _still happening in current master_, despite a fix being available for more than a full month now. I think I can safely remove the >= OBS 25.x check in StreamFX as it doesn't seem that the fix is going to be merged anytime soon.

**Comment by jp9000** [comment]
Merged it.

**Comment by Xaymar** [comment]
Thanks. Confirmed as fixed in master now.
