### ISSUE TITLE
24.x crashes on El Capitan 10.11

### ISSUE THREAD

**Issue by markovanderpuil** [obsproject/obs-studio#2265]
## Expected Behavior

Does not crash when starting.

## Current Behavior

All versions of 24.x crash on El Capitan with following crash log:

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000028
Exception Note:        EXC_CORPSE_NOTIFY

VM Regions Near 0x28:
--> 
    Kernel Alloc Once      00000000023b5000-00000000023b6000 [    4K] rw-/rwx SM=PRV

**Comment by Fenrirthviti** [comment]
See #2249, 10.11 is no longer supported.

**Comment by markovanderpuil** [comment]
Says 10.11+ in the website.

**Comment by Fenrirthviti** [comment]
Thanks, it's been updated. Must have missed that part after release.
