### ISSUE TITLE
Treats non existent path as insufficient disk space

### ISSUE THREAD

**Issue by botanegg** [obsproject/obs-studio#2266]
## Expected Behavior

Expecting OBS will create directories or say me "is not exist"

## Current Behavior

I see next window when I starting the recording
![image](https://user-images.githubusercontent.com/752322/71484340-7a1c9b80-283e-11ea-992d-f24f2f35963a.png)

## Steps to Reproduce

1. Set unexistent diretory as recording directory
![image](https://user-images.githubusercontent.com/752322/71484319-68d38f00-283e-11ea-9ad6-cc4c68b55d11.png)
(this path is not exist, only `/home/botanegg/`)
2. Start record and see
![image](https://user-images.githubusercontent.com/752322/71484340-7a1c9b80-283e-11ea-992d-f24f2f35963a.png)

## Additional information

obs-studio 24.0.5

**Comment by notr1ch** [comment]
Fixed by https://github.com/obsproject/obs-studio/pull/2279
