### ISSUE TITLE
Unreadable text in settings on Windows without western fonts

### ISSUE THREAD

**Issue by cloudsben** [obsproject/obs-studio#2268]
windows 10 chinese version
obs version 24.0.3 windows 64

![image](https://user-images.githubusercontent.com/1283779/71498079-dd85e800-2895-11ea-8584-6b20384ed5fe.png)

**Comment by Fenrirthviti** [comment]
Looks like there is some kind of font override happening, can you try one of the other themes if it has the same issue? I'm not sure there's anything we can do about this if the system is selecting the wrong font.

**Comment by Fenrirthviti** [comment]
Seems like the only solution here would be to ship a font with OBS in situations where the normal Qt fallback fonts are not available.

**Comment by cloudsben** [comment]
New version fixed it!
