### ISSUE TITLE
Audio delayed when browser audio routed to OBS

### ISSUE THREAD

**Issue by sebseb7** [obsproject/obs-studio#2269]
OBS 24.0.3 Windows

## Expected Behavior
audio & video in sync

## Current Behavior
around 1 second Audio delay

## Steps to Reproduce
1. open this page in brower-plugin http://reference.dashif.org/dash.js/v2.9.2/samples/low-latency/index.html
2. enable "Control Audio via OBS"

**Comment by Fenrirthviti** [comment]
I am unable to replicate this issue. Please provide a log file.

**Comment by sebseb7** [comment]
can't replicate anymore
