### ISSUE TITLE
Possible to increase width/height to more than 4096? E.g 8K.

### ISSUE THREAD

**Issue by DeadSix27** [obsproject/obs-studio#2270]
Not sure if supported by CEF or OBS or at all.
But would higher resolutions work?

(Right now its limited by the number input box to 4096, I tried simply setting the number to 12288 width/height limit) (inside the source code)

EDIT: Is the FPS limit also not supported past 60? Or would higher framerates work.

But compiling this is a pain and I run into:
![image](https://cloud.githubusercontent.com/assets/1492505/20618285/784f5554-b2ee-11e6-8135-c52c8096aba3.png)

**Comment by Fenrirthviti** [comment]
OBS currently supports a maximum internal texture value of 4096x4096. There are not many good reasons why you'd need higher than that.

This issue is well over 3 years old, but feel free to submit your case on why this should be increased and this can be reopened.

**Comment by xavioreg** [comment]
@Fenrirthviti 

Hi! 
i have a custom projectors array that is 6680x1200, and i need a browser page with drawings outputed for that)
So custom LED or projections mapping would need that fuctionality)
