### ISSUE TITLE
[Remux window] Last slash in the target file path is a backslash

### ISSUE THREAD

**Issue by derMiepz** [obsproject/obs-studio#2272]
When selecting a file for remuxing, the last slash in the output path is a backslash.

## Expected Behavior
It should be a normal slash like the other ones

## Current Behavior
It's a backslash

## Steps to Reproduce
1. Select a file you want to remux
![](https://i.imgur.com/YMbznkH.png)

## Additional information
Just a cosmetic issue

**Comment by Heufneutje** [comment]
They really should all be backslashes on Windows as that is the correct path separator.

**Comment by Scrxtchy** [comment]
![image](https://user-images.githubusercontent.com/12771982/71564823-078c1400-2afb-11ea-8b36-45c4d08666c3.png)
> They really should all be backslashes

go figure
