### ISSUE TITLE
video lagg/freeze in browser source

### ISSUE THREAD

**Issue by pisikak** [obsproject/obs-studio#2283]
[2020-01-01 22-58-57.zip](https://github.com/obsproject/obs-studio/files/4014489/2020-01-01.22-58-57.zip)

24.0.3. When i play some video from youtube link or another video service in my browser source it's totally frizzes out. I have good sound but slideshow video. And i hav'nt got this problem in earlier version. 

## Expected Behavior
smooth video in browser source like before.

## Current Behavior
 video in browser source is like slideshow. 

## Steps to Reproduce
video example is attached in zip but beware of high volume

## Additional information
I have ryzen 2600 , 16 gb ram, rx-570 8gb, win 7 x64, so i don't think that my pc is not enough for this. Also i tryed to disable/enable gpu acceleration in shortcut and settings , create new scenes with different bitrates but nothing changes.-->

**Comment by notr1ch** [comment]
Please use the forums or Discord for support.
