### ISSUE TITLE
Recording lossless RGB results in artifacts.

### ISSUE THREAD

**Issue by icylavah** [obsproject/obs-studio#2299]
Recording in lossless RGB in OBS Studio 24.0.3 doesn't result in lossless footage like expected. OBS Studio 23.2.1 doesn't have this issue. I didn't test any versions in-between.

![Red artifact](https://i.imgur.com/nUNdR2R.png)

As you can see, scrolling from right to left resulted in some red artifacts being left behind.

## Expected Behavior

We get footage that represents exactly what was on the screen at any given time.

## Current Behavior

We get footage that has red artifacts in it. Desaturated colors don't seem to cause the problem.

## Steps to Reproduce

1. Go to File > Settings > Output
2. Set Output Mode to Simple
3. Set Recording Quality to Lossless Quality
4. Go to File > Settings > Advanced
5. Set Color Format to RGB
6. Apply settings
7. Click Start Recording and record your display with significant motion in it. An easy way to do this is to go here: [DuckDuckGo image search for "colorful"](https://duckduckgo.com/?q=colorful&atb=v1-1&iax=images&ia=images) and hold the Page Down key.

## Additional information

OBS Studio 23.2.1 does not exhibit this issue, it follows the expected behavior when taking the same steps to reproduce. These artifacts seem to be caused by saturated colors only.

It seems the video is encoded differently between the two versions. MPC-HC shows the following properties for a file recorded with 24.0.3:
```
Video
ID                             : 0
Format                         : ULY4
Codec ID                       : ULY4
Duration                       : 5 s 700 ms
Bit rate                       : 1 178 Mb/s
Width                          : 1 920 pixels
Height                         : 1 080 pixels
Display aspect ratio           : 16:9
Frame rate                     : 60.000 FPS
Bits/(Pixel*Frame)             : 9.467
Stream size                    : 800 MiB (100%)
```
And for 23.2.1:
```
Video
ID                             : 0
Format                         : RGBA
Codec ID                       : ULRA
Codec ID/Info                  : Ut Video Lossless Codec
Codec ID/Hint                  : Ut Video
Duration                       : 3 s 517 ms
Bit rate                       : 666 Mb/s
Width                          : 1 920 pixels
Height                         : 1 080 pixels
Display aspect ratio           : 16:9
Frame rate                     : 60.000 FPS
Color space                    : RGBA
Chroma subsampling             : 4:4:4:4
Bit depth                      : 8 bits
Bits/(Pixel*Frame)             : 5.355
Stream size                    : 279 MiB (100%)
```

Using Windows 10 64-bit, NVIDIA GTX 1050

**Comment by notr1ch** [comment]
Have you different media players to ensure this isn't a decoder artifact?

**Comment by icylavah** [comment]
@notr1ch I only tried MPC-HC, as VLC doesn't support the format. Though the nightly builds support it, I can try it with that.

**Comment by icylavah** [comment]
Yep, shows the same artifacts on VLC nightly build as well.

**Comment by icylavah** [comment]
I tried updating the ut video codec, didn't help.

**Comment by derrod** [comment]
This is likely the issue I fixed with https://github.com/obsproject/obs-studio/commit/5e183ff9a7aa2597c06795d28f0c291dff6ae529

Please try with current master, if you cannot build yourself, try the latest CI build: https://dev.azure.com/obsjim/1437b187-9c54-400d-a378-3dff67a18804/_apis/build/builds/2354/artifacts?artifactName=winbuild&api-version=5.1&%24format=zip

**Comment by icylavah** [comment]
@derrod Yup, latest build works, thanks!
