### ISSUE TITLE
Qt Frameless window not recorded

### ISSUE THREAD

**Issue by Ethosa** [obsproject/obs-studio#2306]
Dear developers, correct the write error of frameless applications, if possible.
Details:
Operating System: Windows 7, 64-bit
The application I'm trying to record is written in Python using the PyQt5 library
![frameless window recording](https://user-images.githubusercontent.com/49402667/72055445-6d4b7d80-32fd-11ea-8c66-eb2ead213ee6.png)
![window with frames](https://user-images.githubusercontent.com/49402667/72055515-8f450000-32fd-11ea-9417-e88f1609fcb8.png)

**Comment by derrod** [comment]
Please use the issue template rather than deleting it.

Also does this happen with Aero enabled? Can you provide a sample application? Qt's "shapedclock" example is captured just fine on Windows 10.

**Comment by notr1ch** [comment]
As the application uses transparency, it is a layered window and thus not captured by Windows 7 screen capture when Aero is disabled. Upgrade to Windows 10 or enable Aero.
