### ISSUE TITLE
OBS 24.0.1-24.0.3 Calculation for Disk Space Check Using Incorrect Path

### ISSUE THREAD

**Issue by CrafterLaughter** [obsproject/obs-studio#2309]
## Expected Behavior

When OBS 24.0.1-24.0.3 does it's disk space check upon recording a video it still seems to be checking the default C path (concealed in the GUI) despite different recording paths being specified in Settings -> Output -> Recording Path.  I was thinking it was fixed via pull 2087 [https://github.com/obsproject/obs-studio/pull/2087](url)

Yet, that pull looks to have been merged into master 24.02+ unless I'm reading that incorrectly.

![image](https://user-images.githubusercontent.com/23381273/72183415-e2927d80-33e5-11ea-930e-13b94f810cde.png)

A couple other users noting the same ill disk space check path behavior
[https://obsproject.com/forum/threads/insufficient-disk-space-although-there-is-enough.110979/](url)

[https://linustechtips.com/main/topic/1107290-obs-not-letting-me-record-for-not-sufficient-disk-space-despite-space-free/](url)

**Comment by Fenrirthviti** [comment]
https://github.com/obsproject/obs-studio/pull/2279 It's likely this issue. The message is a red herring.

In the future, please do not delete the issue template, and make sure you are properly filling it out.

**Comment by CrafterLaughter** [comment]
That was exactly it!  I didn't know OBS requires the folder be created ahead of time instead of just creating one on the fly.  So yes, total red herring.  Understood about leaving the template sections.  Thanks again for getting me in the right direction.

**Comment by Fenrirthviti** [comment]
This is already merged, so next release will show the proper error.
