### ISSUE TITLE
Running in 'Studio Mode' caps FPS at 30 (macOS)

### ISSUE THREAD

**Issue by hylkefaber** [obsproject/obs-studio#2313]
When running OBS in studio mode, where you have both the program and preview monitor open at the same time, locks the frame rate at 30 fps, even though I have my settings set to 60 fps. Disabling 'studio mode', running just with the program monitor visible, unlocks the FPS and allows me to record with 60 fps, conforming to the settings I set. 

## Expected Behavior
I expect OBS to let me record and stream at 60 fps in both 'studio mode' and 'non-studio mode'

## Current Behavior
OBS caps my frame rate to 30 fps in 'studio mode', logfile here https://pastebin.com/3tdJ1ei1

## Steps to Reproduce
Video: https://gofile.io/?c=iub4o1
1. open OBS (macOS version 24.0.6)
2. click 'studio mode'
3. observe FPS in the lower right corner, unable to get higher than 30 fps
4. click 'studio mode' again and observe FPS again

## Additional information
I've verified the lower-right-fps-indicator by making separate video's and they show the same: recording in 'studio-mode' caps the fps to 30, without 'studio-mode' get me a solid 60 fps.

I'm running a Hackintosh, as you can see by my logfile, using a Blackmagic Intensity Pro HDMI capture card. However, I believe that this machine being a Hackintosh shouldn't affect this issue.

**Comment by dodgepong** [comment]
More specifically, this is a known issue with studio mode on Mac where studio mode halves the framerate that OBS renders at due to rendering two views.

**Comment by Fenrirthviti** [comment]
There has been a long and detailed discussion about this issue here:

https://obsproject.com/mantis/view.php?id=847

I am going to leave this issue open so that others can see it, and it is technically a bug, but I would recommend to provide any new information on the mantis issue for better tracking.

**Comment by hylkefaber** [comment]
Ah, I was unaware this is a known issue. Maybe present macOS users a pop-up when they first switch to 'studio mode' to tell them about this issue?

**Comment by dodgepong** [comment]
This should be resolved in 25.0.6.
