### ISSUE TITLE
Airwindows VSTs don't open/crash on macOS

### ISSUE THREAD

**Issue by alkasm** [obsproject/obs-studio#2315]
I am on macOS 10.14.6 (18G103) and OBS Studio 24.0.6 (64 bit). 

[Airwindows](https://www.airwindows.com/) makes free and excellent cross-platform VSTs. They have a huge collection, especially of audio effects, which would be an extremely positive addition to OBS Studio for plenty of users. OBS Studio recognizes Airwindows plugins (as in, they populate in the list), but won't load the UI and then crashes for the handful of plugins I tried on my computer.

I did not have a problem with the free Melda Production VSTs listed on the wiki: https://github.com/obsproject/obs-studio/wiki/Filters-Guide#vst-plugin.

As Airwindows is also freeware, I figured it might be up your alley to investigate if possible. Since it's not clear where the problem lies, I also opened up [an issue on Airwaves' GitHub](https://github.com/airwindows/airwindows/issues/9).

Steps to repro:
1. Download the full VST collection via the link on the sidebar of https://www.airwindows.com/
1. Install/simlink the VSTs to `/Library/Audio/Plug-Ins/VST/`
1. Create an audio filter, add a VST 2.x effect, and then select an Airwindows VST (for repro, lets say `Console4Channel`)
1. Select Open Plug-in Interface
1. No window opens for me, the button just changes to Close Plug-in Interface
1. Now change the VST (for repro, say to `Highpass2`)
1. OBS Studio crashes

The general pattern here works for me regardless of what plugins I select---the first won't open the VST UI, and then whenever switching to another VST, OBS crashes.

If this becomes resolved (or, if it generally works on other systems), Airwaves' products would be a great addition to the wiki for filters.

Thanks for taking a look!

**Comment by WizardCM** [comment]
Not sure where this ticket is best suited, here or the https://github.com/obsproject/obs-vst repo.

**Comment by Fenrirthviti** [comment]
This should probably be on the VST repo.

Is this VST considered a console VST? We currently don't have support for console VSTs and they will crash OBS.

**Comment by Fenrirthviti** [comment]
No updates in months, and this should be reported to the vst repo anyway. Closing.
