### ISSUE TITLE
[Bug][WIN] Video of empty window source will stay on last frame

### ISSUE THREAD

**Issue by wangshaohui1314** [obsproject/obs-studio#2321]
OS: WIN10 64bit
OBS: 24.0.3-338 64bit
Reproduce Rate:100%

Maybe video of an invalid window source whose params are empty should not stay on incorrect frame.

## Expected Behavior
In that situation, source should not be drawn in preview canvas.

## Current Behavior
video of source will stay on last frame

## Steps to Reproduce

1. click button and menu to add a window source.
2. after jumping to property window, first window in combox will be selected and it will be captured and displayed on preview window.
3. click "cancel" to jump to main dialog.
4. now params (title, class, executable) of the created window source have been empty but video still stay on last frame.

## Additional information
I find that in wc_tick(...) of window source, when title and class are empty, just return function.
Maybe "dc_capture_free(&wc->capture)" should be runned before returning.

**Comment by jpark37** [comment]
I can repro in 24.0.3, but not master. I think Jim fixed this: 9b4d9c67881d13cb17ce3a9e610d89817223d022

**Comment by wangshaohui1314** [comment]
> I can repro in 24.0.3, but not master. I think Jim fixed this: [9b4d9c6](https://github.com/obsproject/obs-studio/commit/9b4d9c67881d13cb17ce3a9e610d89817223d022)

That commit history was fixing #2320

**Comment by Fenrirthviti** [comment]
Can you please confirm if you have tested against current master to see if the issue is still present? It is not clear from your comment. The fix referenced may have been for another reported issue, but resolved this as well.

**Comment by jpark37** [comment]
I did mean to post on the other issue though. I don't think it's related.

**Comment by wangshaohui1314** [comment]
![1579226149](https://user-images.githubusercontent.com/18413354/72577989-a2645b00-390f-11ea-91ad-50c55f5dea7a.png)

**Comment by WizardCM** [comment]
Is this still an issue in OBS 25?

**Comment by wangshaohui1314** [comment]
> Is this still an issue in OBS 25?

yes， still reproduced in 25.0.1

**Comment by PatTheMav** [comment]
> Add code here:
> ![1579226149](https://user-images.githubusercontent.com/18413354/72577989-a2645b00-390f-11ea-91ad-50c55f5dea7a.png)

Is this the supposed bugfix? If so (and the bug is still present), please submit it as a PR.
