### ISSUE TITLE
[Improvement][WIN] Window/game/monitor are not be updated immediately

### ISSUE THREAD

**Issue by wangshaohui1314** [obsproject/obs-studio#2322]
OS: WIN10 64bit
OBS: 24.0.3-338 64bit
Reproduce Rate:100%

Gennerally, source's updating should be done immediately after selecting window/game/monitor.
But currently in OBS it will be delayed for about 1s~3s.

## Expected Behavior
source's updating should be done immediately after choosing object in combox.

## Current Behavior
window/game/monitor are not be updated immediately 

## Steps to Reproduce

1. jump to property window of window/game/monitor
2. switch window/game/monitor and check preview window
3. preview window is often updated after 1~3 seconds

## Additional information
Window/game/monitor are applied new settings in video_tick, there are variables to make sure the interval time. such as:
_struct window_capture::check_window_timer
struct duplicator_capture::reset_timeout
struct game_capture::retry_time_
It will be better to reset these variables with max interval time in obs_source_info::update to make sure new settings will be applied as soon as possible.

**Comment by Fenrirthviti** [comment]
I am not sure that updating the hook rate is something we should be doing, it is set the way it is for compatibility reasons. Can you explain the exact situation where this is an issue, or are you just expecting it to be instant?

**Comment by notr1ch** [comment]
This makes sense to me, it would improve the perceived responsiveness of OBS if the preview updated immediately when a new target was selected.
