### ISSUE TITLE
OBS Detects non-game/background processes

### ISSUE THREAD

**Issue by diligamer** [obsproject/obs-studio#2326]
OBS Detects background and system processes

## Expected Behavior

It should only show foreground processes
## Current Behavior

It shows system, background, and apps that cannot be open

## Steps to Reproduce

1. Make A Game Capture Source
2. Click on the mode dropdown

**Comment by Fenrirthviti** [comment]
Can you please be more specific which applications are showing up? What version are you testing against? We recently updated the blacklist on Windows to hide additional background services, so this is likely already resolved in master.

**Comment by diligamer** [comment]
These apps include Malwarebytes.
