### ISSUE TITLE
Feature request: support for v4l2 format V4L2_PIX_FMT_RGB24

### ISSUE THREAD

**Issue by robstewart57** [obsproject/obs-studio#2331]
Currently obs supports a few V4L video formats, including BGR24:

```
case V4L2_PIX_FMT_BGR24:
  return VIDEO_FORMAT_BGR3;
```

However, it does not support the `V4L2_PIX_FMT_RGB24` format.

https://github.com/obsproject/obs-studio/blob/c938ea712bce0e9d8e0cf348fd8f77725122b9a5/plugins/linux-v4l2/v4l2-helpers.h#L57

## Expected Behavior

When a camera has support for RGB24, i.e.

```
v4l2-ctl --list-formats -d /dev/video0
ioctl: VIDIOC_ENUM_FMT
	Type: Video Capture

	[0]: 'RGB3' (24-bit RGB 8-8-8)
```
It would appear in the list of video formats for a "Video Capture Device (V4L)" source.

## Current Behavior

Instead, a few emulation formats are offered.

![image](https://user-images.githubusercontent.com/800982/72747750-7239e800-3bad-11ea-8e95-4be3e9498c6b.png)

For a camera with only RGB42 support, the colours will be incorrect, e.g if the "BG3 (Emulated)" option is chosen.

I assume a possible fix might to be include a `V4L2_PIX_FMT_RGB24` in `video_format v4l2_to_obs_video_format`, and a new internal value `VIDEO_FORMAT_GBR3`?

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Fenrirthviti** [comment]
Per the issue template:

```The OBS Studio GitHub issue tracker is **ONLY** to be used for reporting bugs that have replication steps. New features should be discussed on our Discord (https://obsproject.com/discord/) or Ideas page (https://ideas.obsproject.com/). For support issues, use the Discord or forums (https://obsproject.com/forum/)```
