### ISSUE TITLE
[REQUEST] Standalone Xcomposite grabber for Linux, pretty please?

### ISSUE THREAD

**Issue by kokoko3k** [obsproject/obs-studio#2334]
Hello, i know this is not really a bug report, but my use case for obs is a bit (a lot) different as the intended for everyone else.
Usually, i use x11grab from ffmpeg to grab the whole desktop to drive leds on the back of my monitor so that somehow reflects what is on the screen.
If the gpu is under heavy stress, that method produces heavy stuttering
As you probably know, if not nvfbc, xcomposite is the fastest way to do it, and indeed there is absolutely no stutter if i use obs to do that.
...but that requires me to open the whole obs with a specified profile and scene, start the streaming to an udp address, and have some other tool to pick it and drive the leds.
It works and works well, but it is a bit tedious for my special purpose, as you may imagine.
I'm searching since days, but it seems your implementation is the only one existing.

So what i'm asking is to be able to do something like:
#> Xcompositegrab -fps -wid 0x12345 | ffmpeg -f image2pipe -vcodec ppm -i - [...whatever...]

Would it be possible and if not, could you point me to an existing implementation or at something simple i can hack into?
I'm not a C programmer and yes, i tried to understand the code specific to the linux grabber, but i failed miserably.

Thanks.

**Comment by ElectronicWar** [comment]
Per the issue template:

> The OBS Studio GitHub issue tracker is **ONLY** to be used for reporting bugs that have replication steps. New features should be discussed on our Discord (https://obsproject.com/discord/) or Ideas page (https://ideas.obsproject.com/). For support issues, use the Discord or forums (https://obsproject.com/forum/)
