### ISSUE TITLE
OBS Projector output is not smooth/fluid

### ISSUE THREAD

**Issue by ShadowBullet** [obsproject/obs-studio#2340]
## Expected Behavior
Output should be smooth without stutter or jitter

## Current Behavior
When using projector mode, the output stutters at random and is quite jittery

## Steps to Reproduce
1. Make a source with either display or game capture
2. Make that scene/source output with a projector
3. Notice that it is not smooth and fluid

## Additional information
Issue has been reported many times on the forum, but was not listed as a bug here and would be a major win for streamers with dual PC setups in order to have this fixed.

**Comment by WizardCM** [comment]
There are a few bugfixes and performance enhancements in the master branch that may fix this issue: please try the [latest nightly here](https://dev.azure.com/obsjim/1437b187-9c54-400d-a378-3dff67a18804/_apis/build/builds/2424/artifacts?artifactName=winbuild&api-version=5.1&%24format=zip).

If the issue still occurs in the latest nightly, please provide a log or the following details:
* Windows version (if 10, include build number)
* Whether it's a fullscreen or windowed projector
* Whether it only occurs with scenes/sources, or the preview projector too
* Hardware information. CPU, GPU. Number of monitors.

**Comment by ShadowBullet** [comment]
> 
> 
> There are a few bugfixes and performance enhancements in the master branch that may fix this issue: please try the [latest nightly here](https://dev.azure.com/obsjim/1437b187-9c54-400d-a378-3dff67a18804/_apis/build/builds/2424/artifacts?artifactName=winbuild&api-version=5.1&%24format=zip).
> 
> If the issue still occurs in the latest nightly, please provide a log or the following details:
> 
>     * Windows version (if 10, include build number)
> 
>     * Whether it's a fullscreen or windowed projector
> 
>     * Whether it only occurs with scenes/sources, or the preview projector too
> 
>     * Hardware information. CPU, GPU. Number of monitors.

I'm not seeing an .exe install file for it, does it need to be built?

**Comment by Fenrirthviti** [comment]
It's not an installer, it's just the program directory. The main executable is in the `bin` folder.

**Comment by ShadowBullet** [comment]
> 
> 
> It's not an installer, it's just the program directory. The main executable is in the `bin` folder.

Ah, gotcha, I'll test it here and report back my findings

**Comment by ShadowBullet** [comment]
> 
> 
> There are a few bugfixes and performance enhancements in the master branch that may fix this issue: please try the [latest nightly here](https://dev.azure.com/obsjim/1437b187-9c54-400d-a378-3dff67a18804/_apis/build/builds/2424/artifacts?artifactName=winbuild&api-version=5.1&%24format=zip).
> 
> If the issue still occurs in the latest nightly, please provide a log or the following details:
> 
>     * Windows version (if 10, include build number)
> 
>     * Whether it's a fullscreen or windowed projector
> 
>     * Whether it only occurs with scenes/sources, or the preview projector too
> 
>     * Hardware information. CPU, GPU. Number of monitors.

I can definitely tell that it is smoother and less choppy than before (by comparing footage of the current release vs the version you provided), not quite fully smooth, but much better than the current public release.

For reference, here is the logs I just uploaded https://obsproject.com/logs/PnqH6WGnPNUoBZmQ

 All my testing has been done with a fullscreen projector on a capture card that is identical in resolution and refresh rate as my main monitor. (in my case 3440x1440 @ 100hz)

**Comment by ShadowBullet** [comment]
Been doing extensive testing with this, it is better than current release, but still stutters and jitters quite a bit and the frame pacing is not butter smooth (I know that is hard to explain, but I think you know what I mean)

**Comment by WizardCM** [comment]
Looking at your log, I see one display is at 100Hz and the rest are 60Hz. Make them all consistent, and if the issue goes away then you'll have to wait until Windows 10 2004 where the issue will be fixed.

**Comment by ShadowBullet** [comment]
> 
> 
> Looking at your log, I see one display is at 100Hz and the rest are 60Hz. Make them all consistent, and if the issue goes away then you'll have to wait until Windows 10 2004 where the issue will be fixed.

Yeah my main ultrawide is 3440x1440 @ 100hz, and my capture card is the exact same. I have 2 side 1080p monitors at 60hz and a 4k monitor also at 60hz. But the projector is only on the CC. So in Windows 10 2004 this issue should be fixed you said? What kind of fix does it entail and do you know when it might be releasing?

**Comment by DarkFaith** [comment]
This issue has been around since Windows 10 RC in 2014. They finally fixed it. It was a DWM problem since itis hardware-accelerated. Something animating on secondary monitors with different refresh rate would cause frame-pacing, skips, drops on other monitors of different refresh rates because of how the DWM buffers and refreshes.

I've tried the latest "fast ring" preview build of Windows 10 and can confirm this issue is fixed.

What you were seeing was a symptom of this bug.
