### ISSUE TITLE
OBS crashes when entering to high resolution

### ISSUE THREAD

**Issue by Vainock** [obsproject/obs-studio#2343]
## Expected Behavior
The resolution should be limited in some way to prevent unexpected calculations.

## Current Behavior
When entering to high values in the resolution fields in the Video tab, OBS crashes. (Probably because of trying to calculate the aspect ratio.)
Log file: https://pastebin.com/7H5Q2y7W

## Steps to Reproduce

1. Go to the Settings -> Video tab.
2. Enter extreme high resolution like 1920x999999999999999.
3. (OBS crashes)

## Additional information

I am using one of the newest builds in which the aspect ratio was added.

**Comment by ElectronicWar** [comment]
The crash comes from trying to convert a too large number from the text field into an integer

**Comment by cg2121** [comment]
Fixed: https://github.com/obsproject/obs-studio/commit/765bb34641dce1cbc3fb8c7ba5ef30901f6b8305
