### ISSUE TITLE
Bug: Script reload button icon is hidden

### ISSUE THREAD

**Issue by maartenverheul** [obsproject/obs-studio#2344]
The button to reload scripts has no icon, but does still work.

## Expected Behavior
You should see the icon on the button, to see that it is even there.

## Current Behavior
The icon is hidden

## Steps to Reproduce
1. Install latest obs release
2. Open [Tools] > [Scripts]

## Additional information
It was funny to unexpectedly discover the reload button, because without an icon I didn't know it was there.

**Comment by Fenrirthviti** [comment]
Showing up just fine for me:

![scriptsmenu](https://pub.rachni.com/img/obs64_2020-01-22_13-31-10.png)

Can you please provide more information on what environment/theme are you are using?

**Comment by maartenverheul** [comment]
Oh, I'm sorry, I didn't realize there where themes. I was using the Acri theme, buy appearantly by loading the theme again it was visible again.
![Acri](https://user-images.githubusercontent.com/43140847/72932624-6cd0cf00-3d60-11ea-9d98-89b0c078ab18.PNG)
