### ISSUE TITLE
Logitech Brio 4K - Image Glitches constanly

### ISSUE THREAD

**Issue by 8ternity** [obsproject/obs-studio#2349]
I swith from StreamLabs OBS last month due to loss of settings, stream deck recognition and alerts not working with StreamLabs and install OBS Studio.

I have a Logitech Brio 4k webcam updated to latest firmware, which i have video glitches on the webcam (only into OBS Studio). 

My setup settings are in 1080P, 60 fps with x264 codecs. See attachments down this post for screnshots and log files.

- I use auto configuration on first startup. It's has selected 1080P with 60 fps and i change NVEC to x264 because my setup is able to handle it.

To see the glitch itself, please visit [my latest live on timeline 01m30s](https://www.twitch.tv/videos/540304552?t=00h01m29s). See also 01m37s and 01m38s.

## Additional information
Here Log Analysis from OBS Log Analyser
[OBS Log Analyser submited by ET34N1TY](https://obsproject.com/analyzer/?url=https://cdn.discordapp.com/attachments/374636015396192257/669772664029708318/2020-01-22_20-24-17.txt)

Here the latest log on my latest live of yesturday.
[2020-01-22 20-24-17.txt](https://github.com/obsproject/obs-studio/files/4103333/2020-01-22.20-24-17.txt)

Output Settings 
![2020-01-23_08h48_53](https://user-images.githubusercontent.com/16780421/72989913-31182280-3dbd-11ea-8a1d-ab36a4d2ce8f.png)

Video Settings
![2020-01-23_08h49_26](https://user-images.githubusercontent.com/16780421/72989939-442af280-3dbd-11ea-89f0-64192b4e2b33.png)

Camera Settings
![2020-01-23_08h50_02](https://user-images.githubusercontent.com/16780421/72989991-59a01c80-3dbd-11ea-9d09-d30664260e0a.png)

- What i try with resolutions -
> Tried to uninstalled logitech driver and softwares; No Results.
> Disable all power management on USB Human and logitech
> Disable all power management into Windows Energy
> Tried into a different USB Port 3.0 (Not motherboard, but on Front Port (USB 3.0)).

Thanks.

**Comment by notr1ch** [comment]
Please use the forums or Discord for support.

**Comment by 8ternity** [comment]
@notr1ch Since yesturday, i have trouble with getting help. 

See this log info, your OBS Studio has issue decoding MJPEG with Logitech Brio 4k.

`24:21.329: [DShow Device: 'Caméra Brio 4K'] settings updated: 
20:24:21.329: 	video device: Logitech BRIO
20:24:21.329: 	video path: \\?\usb#vid_046d&pid_085e&mi_00#7&3b85d10c&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\global
20:24:21.329: 	resolution: 1920x1080
20:24:21.329: 	fps: 60.00 (interval: 166666)
20:24:21.329: 	format: MJPEG
20:24:21.421: 	using video device audio: no
20:24:21.421: 	audio device: Microphone sur casque (Arctis 7 Chat)
20:24:21.421: 	sample rate: 44100
20:24:21.421: 	channels: 2
20:24:21.421: 	audio type: Capture
20:24:37.379: warning: EOI missing, emulating
20:24:49.139: warning: mjpeg_decode_dc: bad vlc: 0:0 (0000023258AA64C8)
20:24:49.139: error:   error dc
20:24:49.139: error:   error y=127 x=42
20:24:51.491: warning: mjpeg_decode_dc: bad vlc: 0:0 (0000023258AA64C8)
20:24:51.491: error:   error dc
20:24:51.491: error:   error y=117 x=102
20:25:03.540: warning: mjpeg_decode_dc: bad vlc: 0:0 (0000023258AA64C8)
20:25:03.540: error:   error dc
20:25:03.540: error:   error y=125 x=111
20:25:48.614: warning: mjpeg_decode_dc: bad vlc: 0:0 (0000023258AA64C8)
20:25:48.614: error:   error dc
20:25:48.614: error:   error y=112 x=89
20:25:50.246: warning: mjpeg_decode_dc: bad vlc: 0:0 (0000023258AA64C8)
20:25:50.246: error:   error dc
20:25:50.246: error:   error y=111 x=70
20:25:54.295: warning: mjpeg_decode_dc: bad vlc: 0:0 (0000023258AA64C8)
20:25:54.295: error:   error dc
20:25:54.295: error:   error y=127 x=19
20:26:03.404: WASAPI: Device 'Microphone sur casque (Arctis 7 Chat)' initialized
20:26:03.434: adding 46 milliseconds of audio buffering, total audio buffering is now 46 milliseconds (source: Mic/Aux)
`

So please do not close it.

**Comment by Fenrirthviti** [comment]
Impatience is not a good reason to spam our issues page with support requests. Please use the appropriate channels.
