### ISSUE TITLE
OBS fails to load ca-bundle on Fedora

### ISSUE THREAD

**Issue by jp-bennett** [obsproject/obs-studio#2350]
This is an official bug report on the issue discussed in https://obsproject.com/forum/threads/unable-to-live-stream-to-facebook-live-over-rtmps.102849/

Fedora and CentOS use a symlink in the expected ca-bundle location. /etc/ssl/cert/ca-bundle.crt is a symlink off to /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem. OBS uses mbedtls_x509_crt_parse_path() to load certificates, but that function skips loading symlinked cert files, resulting in the ca-bundle not getting loaded, and the "info: RTMP_Connect1, TLS_Connect failed: -0x7680" error.

https://github.com/obsproject/obs-studio/blob/44dc06ede4c8f3404f8116a84d686d29508fb787/plugins/obs-outputs/librtmp/rtmp.c#L347

A quick and dirty workaround is to change that line to 
`if (mbedtls_x509_crt_parse_file(chain, "/etc/ssl/certs/ca-bundle.crt") != 0) {`
Though that would cause problems for any systems that need to load certificates other than ca-bundle.crt. I've opened a bug report with mbedtls here: https://github.com/ARMmbed/mbedtls/issues/3005

**Comment by notr1ch** [comment]
Combining both `mbedtls_x509_crt_parse_path` on the directory and `mbedtls_x509_crt_parse_file` on the `ca-certificates.crt` seems like it should be safe and cover both cases.

**Comment by jp-bennett** [comment]
@notr1ch That sounds reasonable. Do you want me to open a PR to that effect, or is it trivial enough to not bother with the PR?

**Comment by notr1ch** [comment]
Feel free to open a PR if you want to. I'm working on some other mbedtls fixes recently so if you don't want the commit credit I can include it as part of those changes.

**Comment by jp-bennett** [comment]
@notr1ch I don't care about the credit, I'd just like to see it fixed. :) Feel free to fold it into your changes.

**Comment by jcfrosty** [comment]
I've tested the patch and it indeed works! I've able to livestream to facebook live now!

**Comment by notr1ch** [comment]
Thanks for the feedback, I'll try and get this merged over the weekend.

**Comment by jp-bennett** [comment]
@notr1ch perfect. Once a release is made with this, I'll test and close the issue.

**Comment by notr1ch** [comment]
@jp-bennett or @jcfrosty, if you're able to test if the changes from the branch at https://github.com/obsproject/obs-studio/tree/librtmp-thread-safety fix the issue it would be greatly appreciated. I don't have a Linux environment where I can try this and I would like it to be tested prior to merging.

**Comment by jp-bennett** [comment]
@notr1ch Ugggh, I'm an idiot. https://github.com/obsproject/obs-studio/commit/4d89123cdc9c47fdf984980b93a70447c1692183 already fixes this issue. It has nothing to do with symlinks. I'm closing this bug, since it's technically already fixed in master.

I did build and test your branch, and rtmp streaming does seem to work on Linux, still.

**Comment by jcfrosty** [comment]
@notr1ch Just a heads up, I had a chance to compile and test and verify librtmp-thread-safety, it seems to work just fine. Sorry for the late update.
