### ISSUE TITLE
obs-qsv11: Linux supports via intel-mediasdk

### ISSUE THREAD

**Issue by RarogCmex** [obsproject/obs-studio#2353]
## Expected Behavior

Obs studio should enable support for intel quick sync video on Linux platforms
## Current Behavior

It depends on directx9

## Additional information

https://github.com/Intel-Media-SDK/MediaSDK now fully supports linux. I has just ported it latest version on my Gentoo Linux distribution
emerge --search
*  media-libs/intel-mediasdk
      Latest version available: 19.4.0
      Latest version installed: 19.4.0
      Size of files: 10294 KiB
      Homepage:      http://mediasdk.intel.com
      Description:   Intel Media SDK
      License:       MIT

**Comment by WizardCM** [comment]
QSV is currently supported via FFMPEG.

**Comment by RarogCmex** [comment]
@WizardCM No, it don't because ffmpeg support in obs is very basic. May be https://github.com/Xaymar/obs-ffmpeg-encoder can support something, but it closed and in re-working.

**Comment by VodBox** [comment]
The FFMPEG VAAPI encoder that ships with Linux OBS will use either AMF or QSV if they're available.

**Comment by notr1ch** [comment]
Closing, as this is more a feature request than a bug report.
