### ISSUE TITLE
[ubuntu_18.04.3]capture loads RAM to 100% and freezes the system after

### ISSUE THREAD

**Issue by TheK0tYaRa** [obsproject/obs-studio#2354]
## Expected Behavior
Proper capture

## Current Behavior
Proper capture with RAM and SWAP overflow

## Steps to Reproduce
1.Install OBS Studio
2.Start OBS Studio
3.Create window capture (Xcomposite) or screen capture (XSHM)
4.Look at that RAM burn up in HTOP or other tool for process managing
5.Ubuntu freezes after filling all the RAM ans SWAP

## Additional information
Used FFMPEG VAAPI coder because didn't find AMD coder in the list.
GPU is rx580, non-pro drivers because pro drivers make capture into an epilepsy inducing gibberish.
x264 does the same stuff, but slower.

**Comment by TheK0tYaRa** [comment]
It's not even the capture part that does that it seems. It's mainly view part of OBS.
Deleting capture element doesn't stop OBS from overflowing RAM. Only closing it does.

**Comment by TheK0tYaRa** [comment]
OBS Studio version is 24.0.3 64bit

**Comment by TheK0tYaRa** [comment]
Removing the non-pro driver didn't help

**Comment by kkartaltepe** [comment]
Provide a log from obs.

Most likely broken mesa drivers with a memory leak on other platforms have finally made it into ubuntu.

**Comment by TheK0tYaRa** [comment]
https://obsproject.com/logs/Q7TNvggIr2ARhJqq

**Comment by TheK0tYaRa** [comment]
I will check if previous deb packages have the same problem on my PC.

**Comment by TheK0tYaRa** [comment]
Yep, according to discord it's amd mesa drivers

**Comment by kkartaltepe** [comment]
19.2 is one of the affected mesa packages. Attempt to downgrade if possible or wait a few months and try the hardware enablement repositories as Mesa believe they fixed this as of a few days ago (so who knows when those patches will be available for ubuntu users).

**Comment by TheK0tYaRa** [comment]
This appears to be a problem because standard repository has only one version for HWE.

**Comment by kkartaltepe** [comment]
"wait a few months and try the hardware enablement repositories"
The wait a few months part is critical as the fix was barely merged into mesa a few days ago.

The only immediate solution would be to attempt a downgrade to before the issue occurred.

**Comment by TheK0tYaRa** [comment]
But i didn't find a lower HWE version. `aptitude versions` doesn't show them.

**Comment by TheK0tYaRa** [comment]
Oh, wait, I'm dumb.

**Comment by TheK0tYaRa** [comment]
Works on mesa 18.0.*, if there is some repo with 18.1.* please let me know.
