### ISSUE TITLE
Linux should use XDG_VIDEOS_DIR as deafult save path

### ISSUE THREAD

**Issue by Spirit55555** [obsproject/obs-studio#236]
You can find more information about it here https://wiki.archlinux.org/index.php/Xdg_user_directories and here http://www.freedesktop.org/wiki/Software/xdg-user-dirs/

**Comment by underscorejoser** [comment]
This should be reopened or at least closed as not planned if that is the choice.

Could be easily implemented with [QStandardPaths](https://doc.qt.io/qt-6/qstandardpaths.html).
