### ISSUE TITLE
"Settings -> Output -> Recording" cannot be edited

### ISSUE THREAD

**Issue by christianparpart** [obsproject/obs-studio#2362]
When I am recording a video, I do not want to use the default location, such as `$HOME`, so I can change that in the mentioned settings area.

However, no matter how hard I try (with googling around and see if these things fit), I am not able to get those fields editable.

## Expected Behavior
The Settings area in Output -> Recording MUST be editable
- or at least tell the user why it is not editable, and if so, than it would be a good advice to tell the user how to change that.

## Current Behavior
All settings within Output->Recording cannot be changed.

## Steps to Reproduce

1. start OBS
2. open settings
3. click on output
4. attempt a change in the recording section (will fail, because you cannot).

## Additional information
It's an Ubuntu 19.10, a very fresh installation (a day old). I'm not sure if other systems are affected, because I never cared about recording until lately.

**Comment by Fenrirthviti** [comment]
You cannot edit the encoder settings in the Output tab when there is an active output. You need to stop all active streams/recordings first.

**Comment by christianparpart** [comment]
I remember that statement from the internet. However, I did not start any stream nor did I start any recording. 

I tried creating and switching to a new and empty profile/scene-cillection too. No luck.

I also cannot find a way to disable the preview 

If I have to delete all my scenes just to be able to edit (eg. Recording destination), then the is clearly a design bug. 

What exactly do you mean with active out? How can I identify that?

**Comment by WizardCM** [comment]
Like Recording, Streaming, and Replay Buffer, if you have OBS-NDI or obs-virtualcam installed, those count as outputs too. Check the Tools menu.

**Comment by dodgepong** [comment]
Given that it's Ubuntu I don't think it's obs-virtualcam, but another option is Decklink output.

**Comment by Fenrirthviti** [comment]
I have confirmed on my Ubuntu laptop that this is not the case. If you need further support, please use the [forums or Discord](https://obsproject.com/help) as GitHub issues is for repeatable, confirmed bugs.
