### ISSUE TITLE
[Possibly repeated] Fullscreen/borderless window won't record with 720p60fps option

### ISSUE THREAD

**Issue by Cjnator38** [obsproject/obs-studio#2363]
![image](https://user-images.githubusercontent.com/39870226/73504360-bccd1880-4394-11ea-838a-d1976f033a8e.png)
![image](https://user-images.githubusercontent.com/39870226/73504633-ad020400-4395-11ea-9283-43ef289934d1.png)

 
I was trying to record a 15 minute long Minecraft video in 720p60 (Downscaled from 1080p) the entire recording was just the OBS window and desktop, frozen, nothing else. The cursor did make it onto the final recording though. It's just Minecraft what wouldn't show up. I'm using the Badlion Client that might make the window borderless (which might be a different bug, although I didn't check if the client made Minecraft a borderless window or fullscreen.

**Comment by Fenrirthviti** [comment]
You deleted the template, probably without reading it.

GitHub Issues is not for support. Please use the [Forums or Discord](https://obsproject.com/help) instead.
