### ISSUE TITLE
Stream with FFMPEG from linux terminal

### ISSUE THREAD

**Issue by koreanfan** [obsproject/obs-studio#2364]
Hello. I want to stream with amd rx560 video with proc fx-8300. I try obs on my debian buster and it works fine with x264. But i dont need many features from obs, i need simple stream. So i create 2 scripts. One of them start streaming and another stop streaming. But i have pixelate on my stream and video have micro freezes. With obs i dont have those issues. Below 2 scripts used by me:
1)start_streaming.sh
#!/bin/bash
ffmpeg -f x11grab -s 1920x1080 -r 30 -i :0.0 -f pulse -i 0 -f flv -ac 2 -ar 44100
-vcodec libx264 -g 60 -keyint_min 30 -b:v 5000k -minrate 5000k -maxrate 5000k -pix_fmt yuv420p
-s 1920x1080 -preset ultrafast -tune film -acodec aac -threads 0 -strict normal
-bufsize 5000k "rtmp://live.restream.io/live/mystreamkey"
2)stop_stream.sh
#!/bin/bash
pkill ffmpeg
I use 2 keybshortcut for those scripts to run stream and stop stream. Can you help me please to fix this issues and how i can use amd vaapi for streaming from linux terminal? Or maby obs have cli interface and i can use it from terminal with command lika "obs-studio --ffmpeg -f x11grab ...." On debian buster in official rep there were obs with version 22.0.3. I try to use 24.x version of obs but it work improperly on debian buster and with ffmpeg vaapi obs increase my bitrate from 5000 to random value from 5000 to 25000 and my stream is crash. I wrote about this randome increase bitrate on obs forum but there were no answers to me from obs developer.

**Comment by derrod** [comment]
We're not the ffmpeg support.

OBS doesn't have a UI-less mode. Though you can automate it somewhat by starting it minimized and by using the command line parameters to start streaming automatically. See [Launch Parameters](https://github.com/obsproject/obs-studio/wiki/Launch-Parameters) in the wiki.

**Comment by koreanfan** [comment]
so how about bitrate increase from setup in option tab  in obs from 5000 to
25000? Will you fix this problem?

пт, 31 янв. 2020 г. в 12:04, Rodney <notifications@github.com>:

**Comment by ElectronicWar** [comment]
Please join the forums or Discord for troubleshooting of your OBS issues. Github is only to report reproducible errors in OBS.

**Comment by koreanfan** [comment]
I wrote on obs forum about spontaneous increase bitrate with vaapi in obs
but there were no answers on forum and this problem not fixed yet.
Maybe its again fault of ffmpeg developers?

пт, 31 янв. 2020 г. в 12:40, Manuel <notifications@github.com>:

**Comment by Sur3** [comment]
@koreanfan I had a similar problem, but it was just an incompatibility between different ffmpeg versions and obs-studio, so updating to ffmpeg 4.2.2 and latest obs-studio master fixed it. ;)
