### ISSUE TITLE
可以内置一个proxy功能吗，直播到youtube推流rtmp代理失败，Proxifier，SocksCap64等多款软件都无法工作

### ISSUE THREAD

**Issue by 1265578519** [obsproject/obs-studio#2367]
可以内置一个proxy功能吗，直播到youtube推流rtmp代理失败，Proxifier，SocksCap64等多款软件都无法工作

**Comment by 1265578519** [comment]
Can a proxy function be built in? If the RTMP proxy fails to live stream to youtube, proxifier, socksacp64 and other software will not work

**Comment by kkartaltepe** [comment]
Github issues are not for feature requests.

Feature requests belong on https://ideas.obsproject.com/

Please use english on official channels. We cannot support other languages at this time.

**Comment by 1265578519** [comment]
![image](https://user-images.githubusercontent.com/6442439/73598050-39ffb580-456e-11ea-8c2a-da1755c5e866.png)
我没找到一个issue按钮。。

**Comment by kkartaltepe** [comment]
I see you have found how to use it already.

https://ideas.obsproject.com/posts/724/ke-yi-nei-zhi-ge-proxygong-neng-ma-zhi-bo-dao-youtubetui-liu-rtmpdai-li-shi-bai

**Comment by 1265578519** [comment]
Thank you. I just found the box on the left

**Comment by 1265578519** [comment]
25版本依旧没看到代理功能..

**Comment by KeSaite** [comment]
yes, we need http or socks proxy

**Comment by calidion** [comment]
SocksCap64可以工作的。

**Comment by 1265578519** [comment]
> SocksCap64可以工作的。

测试需要在hosts内添加一行，目前他正常工作，可能obs预先在本地进行了dns解析没有提交给远程代理服务器
142.250.204.76 a.rtmp.youtube.com

**Comment by calidion** [comment]
Windows 平台有解决方案。 目前linux平台还没有。呵呵。

**Comment by gxalpha** [comment]
I'm not quite sure what this is about, but please don't use closed issues as a support channel. I'd recommend visiting our [support page](https://obsproject.com/help) instead.
