### ISSUE TITLE
B-Frame reference mode flag in ffmpeg nvenc is bugged and doesn't work.

### ISSUE THREAD

**Issue by maginhart** [obsproject/obs-studio#2374]
## Expected Behavior

This flag enables B-frames as reference and it should improve picture quality. It's basically b-pyramid from x264.
## Current Behavior

When **-b_ref_mode 2** is enabled my recording starts and after 2 seconds drop's bitrate to zero. If I try to stop recording, ui button just freezes and I have to kill obs process.
## Steps to Reproduce

1. I'm using Xaymar's plugin for FFmpeg Nvenc that includes all the flags with easy to use UI.
2. https://obsproject.com/forum/resources/ffmpeg-encoders-for-obs-studio.826/
3. After installing just select the encoder in OBS Output
![image](https://user-images.githubusercontent.com/60628882/73732885-a384ed00-4743-11ea-9689-45f740887e8d.png)
4. You can leave everything at default and just enable this option
![image](https://user-images.githubusercontent.com/60628882/73733006-d8913f80-4743-11ea-8a93-8954da699044.png)

## Additional information

Enabling this flag -b_ref_mode 2 in Custom Output (FFmpeg) 
![image](https://user-images.githubusercontent.com/60628882/73733453-a502e500-4744-11ea-996c-4d3bc0b3344f.png) should result in the same bug.

**Comment by pkviet** [comment]
Please check with ffmpeg custom output to confirm the issue is in obs or in the plugin. For issues with Xaymar's plugins, you should post to his repo. Not here.

**Comment by maginhart** [comment]
Xaymar answered that question. But I will check Custom Output (FFmpeg) later today.
![image](https://user-images.githubusercontent.com/60628882/73736013-cb2a8400-4748-11ea-8927-5fe8684a2508.png)

**Comment by pkviet** [comment]
If Xaymar's answer is correct, it's an ffmpeg issue.
You should then test with ffmpeg cli, with version 4 and then master to see if the bug is fixed.
It doesn't seem to be an issue with obs at any rate.

**Comment by pkviet** [comment]
For further reference: https://trac.ffmpeg.org/ticket/7303

**Comment by ValZapod** [comment]
I think we should reopen this. It is important. Technically this issue is simple to solve as it is off by one (usually 3600) error. And is only present when you stream not when you output to file.

**Comment by pkviet** [comment]
? what's your simple fix ? @ValZapod 
If there is one, feel free to PR. But it seemed to be on FFmpeg side rather than OBS.

**Comment by ValZapod** [comment]
Was fixed in https://github.com/FFmpeg/FFmpeg/commit/aaadf0dce8fa7b3b5073089498a84e758ceb975a Please reopen ASAP!

**Comment by pkviet** [comment]
the fix is upstream so it'll come to obs when we update the ffmpeg dll. Let's keep this closed.

**Comment by ValZapod** [comment]
But it is very important, really. Why you think it is not?

**Comment by dodgepong** [comment]
There's not really a point to re-opening this if the issue is already fixed. All that needs to happen is to release a new OBS package with an updated FFmpeg, which we can do with the next release if we need. Personally I don't think this is urgent enough to warrant an immediate hotfix.

**Comment by ValZapod** [comment]
@dodgepong I strongly desagree with you but okay. Just remember Twitch already supported it before this patch and now it may be broken because they applied some fix, you know.

**Comment by cs9kc** [comment]
ValZapod, ffmpeg -just now- put in a fix that won't make it into an official release for another month or two.  OBS Studio -then- needs to take that and integrated it into their program, which will take more time.

The use-case for b-frames as reference for recording is so hilariously microscopic, that we can live without it until OBS Studio developers can get an official ffmpeg release and get to work themselves.

Please don't clutter up this ticket any more.

**Comment by cs9kc** [comment]
The aforementioned fix for "b_ref_mode=middle" was integrated into Zeranoe's latest Windows nightly.  The change does appear to fix the issue and ffmpeg no longer produces errors.

For you OBS Studio devs, I thought I'd be cheeky and copy the .dll files from "/ffmpeg/bin/" (from a "shared" version of the ffmpeg nightly), into the /obs-studio/bin/64bit/ folder, just to see what happens.  Interestingly, I can record h264/h265 using "b_ref_mode=middle" with ffmpeg custom output and Xaymar's StudioFX gui, with no problems.

Hopefully that means little-to-no work will need to be done once you all integrate the next full ffmpeg release into a future OBS Studio version.

Thank you all again for your help!

**Comment by Fenrirthviti** [comment]
Not exactly. You're correct there's not much work that needs to be done, but you've only tested a single aspect: custom ffmpeg output. We use ffmpeg for things like media source, image source, etc. as well, so we'd need to fully test against those. Also, I am not comfortable shipping a nightly unstable build.

Once the fix makes it to a stable release, we will look in to updating, but you're more than welcome to replace the shared library files with the nightly for your own use cases!

**Comment by ValZapod** [comment]
Any updates? BTW, what is the status of this commit? https://github.com/obsproject/obs-studio/commit/f27a00d266a380312025fa09878023592d9bb612 Should be reland it??? I think we should. 

What about this, BTW? https://github.com/FFmpeg/FFmpeg/commit/9ce7de903882793749abc68eeb29813a19f50de5 Can you comment @BtbN? 

> This leaves open an issue with VFR content, for which some more complex
> logic might be needed.
>

**Comment by BtbN** [comment]
With VFR content, it's virtually impossible to properly do timestamp calculation when re-ordering is required, given that you can't possibly know the largest possible gap.
x264 also leaves that unsolved, so I didn't bother implementing it, since it's a non-issue in practice.

**Comment by ValZapod** [comment]
@cs9kc We fixed bframe each for hevc (avc is not supported anyway by Nvidia cards). I tested it, works nice.
https://github.com/FFmpeg/FFmpeg/commit/466c14d10728cd315c60e602ffe3797e7dd0c3d3
https://trac.ffmpeg.org/ticket/8809

So it is now fully operational. Note, each is very hardcore for some video players, like Microsoft's.

**Comment by ValZapod** [comment]
Will just notify you that 4.4 release will have another final fix (unless we will do VFR, of course) for default values of B-frames, which are now turned on by default (that introduces a problem, as `-bf -1` was not really allowed in the code, see https://github.com/FFmpeg/FFmpeg/commit/a0949d0bcb0eee2f3fffcf9a4810c0295d14c0dc). That is commit https://github.com/FFmpeg/FFmpeg/commit/30cd7feb2dd497b16edb6d7c09a83eb49f89645d

We also fixed some DTS cpu ticks problem.

**Comment by ValZapod** [comment]
>avc is not supported anyway by Nvidia cards

b_ref_mode each is now supported for H264: https://github.com/FFmpeg/nv-codec-headers/commit/7947f29859f2fa7a9252309daeb4717030d027e0#diff-7e89fa6759c697c70618e5debd0af1d85b415ec339f16850993dc23c39ae68c3L671
