### ISSUE TITLE
OBS ignoring Radeon Settings Switchable Graphics settings

### ISSUE THREAD

**Issue by Tetriser** [obsproject/obs-studio#2378]
##  Expected Behavior
OBS should use the primary GPU (GPU 0 in Task Manager).

## Current Behavior
As the title said, it ignores my SG settings and stuck with the discrete GPU.

## Steps to Reproduce
https://streamable.com/hljej

## Additional information
It works just fine in an older Radeon driver (17.2.1), but drivers after that are causing black screens on some machines (including mine) since Windows 10 May 2019 Update. 19.7.1 solves the problem but now OBS got stuck with discrete graphics. I don't want to use the driver as a workaround since it's very problematic with some games and emulators.

**Comment by derrod** [comment]
With newer Windows versions the setting in the driver control panels no longer works reliably, you have to change it in the Windows settings: https://github.com/obsproject/obs-studio/wiki/Laptop-GPU-Selection-Windows-10

This is not directly an OBS issue we can fix.
