### ISSUE TITLE
Inconsistency in Instant Replay feature

### ISSUE THREAD

**Issue by BadCoder1337** [obsproject/obs-studio#2379]
## Current Behavior

I'm using Instant Replay with VLC Playlist in VLC Source.
I've set replay buffer length to `10` seconds. When i save it first time - replay is `8-13` secs long (it isn't `10` secs but ok). If i save it again in `1-5` secs - replay is like first with these `1-5` secs concatenated. If i save it in `5-9` secs after first - replay again is `8-13` secs long but there is overlap. Anyway, interesting moment in my playlist shows twice.

## Expected Behavior

When saving replays OBS should flush replay buffer like as GeForce Experience Instant Replay.
The current behavior is ok when you show only last replay, but isn't ok when clipping all best moments.
Some switch in settings would be great.

## Steps to Reproduce

1. Set replay length to `N` sec.
2. Start replay buffer.
3. Wait `N` secs.
4. Save replay first time.
5. Save replay second time with some pause.

## Additional information

Record format is `mp4` but i didn't find any difference with default.

**Comment by Fenrirthviti** [comment]
This doesn't sound like a bug, but more of a feature request to add a flush to the buffer when the replay buffer is saved. Please show your support for this feature here instead, as the issues page should be reserved for repeatable bugs.

https://ideas.obsproject.com/posts/246/add-replay-buffer-option-to-clear-on-save
