### ISSUE TITLE
Linux version does not have option for browser source

### ISSUE THREAD

**Issue by LuciousLisa** [obsproject/obs-studio#2383]
## Expected Behavior

When choosing from the dropdown menu to add a source, the option 'browser source' should be available.

## Current Behavior

When choosing from the dropdown menu to add a source, the option 'browser source' is not included. This makes having overlays for chat, notifications, etc. much less user friendly and unreliable.

## Steps to Reproduce

1. Click + button in 'Sources' panel
2. ???
3. No 'browser source' option

## Additional information

OS: Ubuntu
OBS-Studio version: 24.0.3 (latest on the Ubuntu repository)

**Comment by kkartaltepe** [comment]
Github is not for feature requests.

You can follow the progress for getting browser sources implemented for linux at the appropriate PR https://github.com/obsproject/obs-studio/pull/1759

**Comment by LuciousLisa** [comment]
I considered it a bug, becaise it's such a basic feature of (the Windows version of) OBS-Studio. My bad for not realising it was left out on purpose! Thanks for the link, I hope this gets implemented soon, as it would make life a hell of a lot more convenient for us Linux streamers.
