### ISSUE TITLE
Locked UI snaps in floating docks

### ISSUE THREAD

**Issue by ngollan** [obsproject/obs-studio#2387]
## Expected Behavior

When moving a floating dock across the main window but not dropping it inside, i.e., no placeholder is showing when you release the mouse, the dock should not snap into the main window.

## Current Behavior

When "Lock UI" is enabled, the above action will have the floating dock snap into the main window.

## Steps to Reproduce

1. unlock UI
2. snap off any dock into its own window
3. lock UI again
4. move that floating thing so the layout placeholder shows up in the main window, but then move it away again so the placeholder disappears without releasing the mouse
5. release mouse.

**Comment by Fenrirthviti** [comment]
There is not likely much we can do about this, we are using Qt's built-in docking system.

**Comment by PatTheMav** [comment]
@Fenrirthviti At least on macOS with Qt 5.15.2 this part right here doesn't happen:

> move that floating thing so the layout placeholder shows up 

Maybe the Qt update fixed this on Windows as well?

**Comment by Fenrirthviti** [comment]
Appears that this one was indeed fixed. When the UI is locked, you no longer can re-dock floating docks to the main window, which means this condition does not occur anymore.
