### ISSUE TITLE
OBS Version 24.0.6 

### ISSUE THREAD

**Issue by ipetr13** [obsproject/obs-studio#2395]
New OBS Version 24.0.6 seems not to support the InfoWriter Plugin: https://github.com/partouf/OBSInfoWriter/releases/download/v1.2/OSX.libOBSInfoWriter.v1.2.zip

After libOBSInfoWriter.so is pasted into the OBS Plugins folder, it can't be found in OBS sources as it was in the OBS Version 24.0.2.

I'm using Mac Catalina 10.15.3. 

Is there any solution for that issue?

**Comment by WizardCM** [comment]
As part of OBS 24.0.5 for Catalina compatibility, the OBS package structure was changed. You'll need to ask the developer of the plugin in question to update their system.
