### ISSUE TITLE
rtmp-servies: Add Uncanny.gg 

### ISSUE THREAD

**Issue by jake-shomer** [obsproject/obs-studio#2396]
> ### Description
> Added Uncanny.gg to services drop down .
> 
> ### Types of changes
> New feature (non-breaking change which adds functionality)
> 
> ### Checklist:
> * [x]  My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
> * [x]  I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
> * [x]  My code is not on the master branch.
> * [x]  The code has been tested.
> * [x]  All commit messages are properly formatted and commits squashed where appropriate.

**Comment by dodgepong** [comment]
Is this supposed to be a pull request?

**Comment by jake-shomer** [comment]
Yes, I am sorry about that. I just submitted a pull request.
