### ISSUE TITLE
wrong error message when reccording to inexistant directory

### ISSUE THREAD

**Issue by wonwon0** [obsproject/obs-studio#2404]
On windows, OBS 24.0.4 clean install, after modifying the directory to which videos are recorded. When starting a recording the error message "There is not sufficient disk space to continue recording" is displayed if the output directory does not exist. This error message tells us that there is a problem, but not the right one.
## Expected Behavior
The error message should indicate that the output directory does not exist.
In the best case scenario, the directory should be created and no error message should pop up.

## Current Behavior
When starting a recording the error message "There is not sufficient disk space to continue recording" is displayed if the output directory does not exist. This error message tells us that there is a problem, but not the right one.

## Steps to Reproduce

1. Start OBS.
2. Modify the output recording directory to an existent directory.
3. Start recording.

**Comment by dodgepong** [comment]
This was fixed by https://github.com/obsproject/obs-studio/pull/2279 and will be available in the upcoming release.
