### ISSUE TITLE
Game capture with Street Fighter 5 not working

### ISSUE THREAD

**Issue by cloonix** [obsproject/obs-studio#2414]
Game capture source is not working for the (steam) game Street Fighter 5. 

## Expected Behavior
Capturing the game Street Fighter 5 via OBS and "Game Capture Source" (window). 

## Current Behavior
OBS does not show anything in preview mode, nor in streaming. The window is not captured at all.

## Steps to Reproduce
1. Adding a game capture source and select the specific game window "StreetFighterV.exe".
2. Select "Match title, otherwise find window of same executeable"
3. The game is started in window mode and no borders via the Steam launch options (-fullscreen -noborder). 

## Additional information
Actually i found a - not very convenient - work around:

1. Start OBS as administrator once
2. Disable anti-cheat compatibility
3. Start OBS as regular user

These steps are necessary after every reboot. 

System settings:
- Windows 10 (latest release)
- NVIDIA GTX 1060

**Comment by notr1ch** [comment]
Please use the forums or Discord for support. This simply sounds like the game is running as admin.
