### ISSUE TITLE
Replay buffer ignores slashes in filename formatting pattern

### ISSUE THREAD

**Issue by UserNaem** [obsproject/obs-studio#2416]
## Steps to Reproduce

1. In Settings > Advanced, change filename pattern to ``%CCYY-%MM-%DD/%hh-%mm-%ss``
2. Enable Replay buffer and set a hotkey for it.
3. Start and stop recording.
4. Start Replay buffer, save it, stop replay buffer
5. Open recordings folder.

## Expected Behavior
A subfolder called ``2020-02-21`` (current calendar day), with both recordings formatted as ``hh-mm-ss``.

## Current Behavior
The recording will follow the file name pattern properly and go into the subfolder, but the replay buffer will be saved in the root recordings folder. All forward slash and back slash characters are silently replaced with underscores.

**Comment by dodgepong** [comment]
Does this actually create a folder with the `%CCYY-%MM-%DD` name in the recordings folder? I wouldn't have expected it to create a folder at all.

**Comment by UserNaem** [comment]
![image](https://user-images.githubusercontent.com/21028464/74979929-62821d80-5451-11ea-886f-56f97f4332d6.png)
Yep, it does.

**Comment by WizardCM** [comment]
What if you use a slash in the other direction (backslash)?

**Comment by UserNaem** [comment]
To quote my first post,
>All forward slash and back slash characters are silently replaced with underscores.

**Comment by Fenrirthviti** [comment]
Tested and confirmed this, and as an aside if you set the recording filename similarly:

`%YY/%MM/Video %H-%M`

Resulted in the folders being created and the video file properly name (in this test case, it was successfully written to `F:\Video\20\04\Video 23-46.mkv`)

**Comment by jp9000** [comment]
As of 002886bbac, the program will now allow slashes in recording names and replay buffer prefixes/suffixes, and will generate directories as needed if there are slashes present.
