### ISSUE TITLE
Custom font not appearing on Text (GDI+)

### ISSUE THREAD

**Issue by LordPicasoNL** [obsproject/obs-studio#2425]
## Expected Behavior
Text (GDI+) should appear

## Current Behavior
No text appears it's just blank.
https://obsproject.com/logs/lTzs9z0UBDAXDiwP

## Steps to Reproduce

A screen shot of how it looks like https://gyazo.com/0ffd42322efd6ccc9e40a93837572f23

1. Reinstalling the font works untlil i reboot my PC.
2. Standard installed fonts works.
3. Custom font works in other software.

**Comment by Fenrirthviti** [comment]
The issues page is not for support. Please use the forums or Discord.
