### ISSUE TITLE
How to build updater.exe, please!

### ISSUE THREAD

**Issue by artisan-yp** [obsproject/obs-studio#2430]
I want to build updater.exe, how? please~online waiting!

**Comment by Fenrirthviti** [comment]
This is not an appropriate place to ask for support, use the Discord or forums if you are having issues compiling OBS. I don't believe the updater is currently published to the repository.

**Comment by artisan-yp** [comment]
> This is not an appropriate place to ask for support, use the Discord or forums if you are having issues compiling OBS. I don't believe the updater is currently published to the repository.

./obs-studio/UI/CMakelists.txt, line 397~399
if(WIN32)
	add_subdirectory(win-update/updater)
endif()

the updater souce code, but how can i compile it?
