### ISSUE TITLE
Xcode Project Error

### ISSUE THREAD

**Issue by xp19870106** [obsproject/obs-studio#2437]
I create a xcode project following instruction from https://github.com/obsproject/obs-studio/wiki/Using-Xcode
when run it in Xcode, I get following error :
![Screen Shot 2020-02-26 at 8 37 26 PM](https://user-images.githubusercontent.com/5085902/75345524-d439eb80-58d7-11ea-9466-791abaec20af.png)

**Comment by notr1ch** [comment]
Please use the developer support forums or Discord.
