### ISSUE TITLE
don't see browser source on Linux

### ISSUE THREAD

**Issue by LiamDawe** [obsproject/obs-studio#2447]
With the latest RC release, it mentions:

> Implemented browser plugin on Linux [bazukas/cg2121]

I just compiled it, using the instructions for a [portable build](https://github.com/obsproject/obs-studio/wiki/Install-Instructions#linux-portable-mode-all-distros), making sure to follow and use the bits described for browser source inclusion.

However, after compiling the plugin is not listed.

Here's a full log: https://gist.github.com/LiamDawe/83a5d2088109f47dc31c6ad89d7336e2

**Comment by tt2468** [comment]
https://gist.github.com/LiamDawe/83a5d2088109f47dc31c6ad89d7336e2#file-gistfile1-txt-L21

It says browser submodule not found. Are you sure that you specified --recursive in your git command? Check that the browser plugin is in the `obs-studio/plugins` directory. I think it's called `obs-browser`

**Comment by Gol-D-Ace** [comment]
obs-browser submodule not found!  Please fetch submodules

git submodule init
git submodule update

Or clone directly with the submodules

**Comment by LiamDawe** [comment]
> It says browser submodule not found. Are you sure that you specified --recursive in your git command? 

I followed the compile instructions exactly as listed, if they're out of date and more steps are needed can someone "in the know" please update them for Linux? That is not mentioned.

> Check that the browser plugin is in the obs-studio/plugins directory. I think it's called obs-browser

No, it's not in there.

**Comment by tt2468** [comment]
What was the command that you used to fetch the obs-studio source?

**Comment by LiamDawe** [comment]
> What was the command that you used to fetch the obs-studio source?

I downloaded the release package source build from the announcement.

**Comment by tt2468** [comment]
That package does not include the submodules like obs-browser.

Use ```git clone --recursive https://github.com/obsproject/obs-studio.git
cd obs-studio
mkdir build && cd build```

to download obs-studio with the submodules.

**Comment by LiamDawe** [comment]
Well then, that solved that, woops.

Big thanks!
