### ISSUE TITLE
srt: unable to reconnect after VLC receiver restart 

### ISSUE THREAD

**Issue by boxerab** [obsproject/obs-studio#2453]
From @ragnos

I've tested this with v25-rc1 like @dodgepong did. The initial test with VLC worked just fine. (I'm also using VLC 3.0.8, no need for nightly.) After i've stopped the VLC playback obs disconnected and attempted automatic reconnects which have not been successful. I've stopped the stream, started again immediately, and now obs claims "Invalid Path or Connection URL.".

https://obsproject.com/logs/rO4EK0_-9ZJunlQd

Edit: I was able to replicate the behaviour. If you initially entered a incorrect stream path (eg. omiting "?mode=listener"), the automatic reconnect won't actually make a reconnect attempt. You have to stop and restart obs altogether and leave the path alone, now it will reconnect reliable.

Edit 2: When OBS is trying to reconnect and has to wait (eg. closed vlc) the whole window becomes unresponsive, can't stop stream without making the application crash. Recovers by restarting vlc playback.

**Comment by boxerab** [comment]
Related PR: https://github.com/obsproject/obs-studio/pull/1748

**Comment by choseh** [comment]
Can confirm this behavior with OBS on streaming PC as listener, and OBS custom output via ffmpeg on guest (macos). Whenever I stop the caller I can't reconnect to the stream unless I disable/reenable the media source listener.

**Comment by b3ck** [comment]
OBS needs to close and destroy the listening port after the SRT caller disconnects or if you delete the source or hide visibility of the source, after it's successfully destroyed and if it's still visible then OBS needs to start listening again (srt mode listener).  

The srt-live-transmit does this nornally so I don't know why they didn't implement this when adding SRT support for the Media Source 🤔
