### ISSUE TITLE
Starting OBS with task scheduler causes error

### ISSUE THREAD

**Issue by Balint197** [obsproject/obs-studio#2456]
I'm trying to autostart OBS at a given time using Task Scheduler with the --startrecording parameter. I get the same error if starting without launch parameters. 

## Expected Behavior
OBS starts at scheduled time(, and automatically starts recording). 

## Current Behavior
At the scheduled time, OBS starts, but gives two error popup messages:

1) Failed to find locale/en-US.ini
2) Failed to load locale

Then quits. 

## Steps to Reproduce
1. start task scheduler
2. schedule task for obs64.exe
3. wait for the program to start

## Additional information
I tried reinstalling, and putting the en-US.ini file in different folders, with no success. 

Using windows 10, obs64. The command parameter version works from a shortcut. If I make a bat file with the same function, it works if run from the same folder as the exe, but it doesn't run with task scheduler.

**Comment by notr1ch** [comment]
You need to set the correct working directory (the folder of obs64.exe). This isn't a problem with OBS but with your environment.

**Comment by Balint197** [comment]
Thanks, and sorry for the wrong assumptions. 

I tried looking for  a task scheduler working directory, but couldn't find one. Not sure if that's what you meant. 

I also tried to set the .bat file to execute with navigating to the shortcut first, but it doesn't work. Could you maybe please clarify what you meant exactly? Thanks a lot. :)

**Comment by Balint197** [comment]
Thanks a lot , I figured it out. :)

**Comment by alinsavix** [comment]
What I use for my action in the task scheduler (which works) is:

**Action**: Start a Program
**Program/script**: `cmd.exe`
**Add arguments**: `/c start "OBS Studio" "C:\program files\obs-studio\bin\64bit\obs64.exe" --remote-debugging-port=1234`
**Start in**: `C:\Program Files\obs-studio\bin\64bit`

**Comment by Balint197** [comment]
> 
> 
> What I use for my action in the task scheduler (which works) is:
> 
> **Action**: Start a Program
> **Program/script**: `cmd.exe`
> **Add arguments**: `/c start "OBS Studio" "C:\program files\obs-studio\bin\64bit\obs64.exe" --remote-debugging-port=1234`
> **Start in**: `C:\Program Files\obs-studio\bin\64bit`

Thanks, thats even better. I had problems with cmd staying open with my code.
