### ISSUE TITLE
OBS-Studio-24.0.3-Full-x64 randomly crashes

### ISSUE THREAD

**Issue by iNgeon** [obsproject/obs-studio#2465]
Please is there a way to debug or look at logs to determine why it keeps crashing ?

**Comment by ElectronicWar** [comment]
Please only post reproducible issues here. Github Issues are not for general support. Join our [Discord](https://obsproject.com/discord) or [Forums](https://obsproject.com/forum) for help.

**Comment by iNgeon** [comment]
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	obs64.exe
  Application Version:	24.0.3.0
  Application Timestamp:	5da1792b
  Fault Module Name:	StackHash_1eb3
  Fault Module Version:	6.1.7601.24545
  Fault Module Timestamp:	5e0eb67f
  Exception Code:	c0000374
  Exception Offset:	00000000000bf262
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	7177
  Additional Information 1:	1eb3
  Additional Information 2:	1eb3e0e3b2f403f9de5cb9fd2de20602
  Additional Information 3:	986d
  Additional Information 4:	986dd6e8ae958c040657327a08dbc04b

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
