### ISSUE TITLE
OBS won't capture windows with back color transparent

### ISSUE THREAD

**Issue by Leemonn** [obsproject/obs-studio#2480]
If you have a window with a background color and you make this color transparent, OBS won't show this window, even if only the background color of the window is transparent.

## Expected Behavior

It should still show the window as only the background color is transparent.

## Current Behavior

As soon as you turn the background color transparent the window will dissappear from the stream.

## Steps to Reproduce

[Actual window](https://imgur.com/klLexqm)
[OBS output](https://imgur.com/vE1VSE6)
I can provide code in AHK:
```
Gui, Main: New, +HwndmainGuiId -caption, testingOBS

Gui, Potion: New, +ParentMain -caption +hwndTestWindow
gui, Potion: color, FF00FF
Gui, Potion: Add, Picture, w50 h50

Gui, Child: New, +ParentMain -caption
Gui, Child: Add, Picture, x0 y0

Gui, Main: Show, w500 h500 x500 y500
Gui, Potion: Show, x0 y0
Gui, Child: Show, x0 y0
return

f5::
WinSet, TransColor, FF00FF, ahk_id %TestWindow%
return


f6::
WinSet, Transparent, 100, ahk_id %TestWindow%
return

f7::
WinSet, Transparent, off, ahk_id %TestWindow%
return
```
## Additional information
Press F5 to set background's color transparency 0.
Press F6 to set background's color transparency to 100.
Press F6 to set background's color transparency off.

**Comment by Leemonn** [comment]
Bump?

**Comment by Fenrirthviti** [comment]
Please provide a log from OBS where this happens. The link you provided requires you to sign up for a paid subscription so I have removed it.

**Comment by WizardCM** [comment]
Bump: please provide a log as requested by Fenrir.

**Comment by PatTheMav** [comment]
Asked for log twice, no reaction even 9 months later.
