### ISSUE TITLE
Can not build in Xcode after add QtNetwork

### ISSUE THREAD

**Issue by xp19870106** [obsproject/obs-studio#2481]
I used QtNetwork in OBS and added it to the cmakelist file under UI folder
```
find_package(Qt5Network REQUIRED)

target_link_libraries(obs
    libobs
    Qt5::Widgets
    Qt5::Network
    obs-frontend-api
    ${FFMPEG_LIBRARIES}
    ${LIBCURL_LIBRARIES}
    ${obs_PLATFORM_LIBRARIES})
```

but after I build it for xcode following the Guid 
https://github.com/obsproject/obs-studio/wiki/Using-Xcode
I get the following error at step 5
```
'QtNetwork' file not found
```

## Expected Behavior
Hope it can still be compiled in xcode after import qtnetwork

**Comment by notr1ch** [comment]
OBS does not use QtNetwork. If you are building your own version that requires it then it is up to you to resolve the appropriate dependencies.
