### ISSUE TITLE
Validate swap chain creation

### ISSUE THREAD

**Issue by dzimanAMD** [obsproject/obs-studio#2485]
Parameters to GetSwapchainImagesKHR should be validated prior to calling vkGetSwapchainImagesKHR. If vkCreateSwapChainKHR fails, then calls to vkGetSwapChainImagesKHR should not be made without valid parameters. This results in an application crash when swap chain creation fails.

Call to create swap chain:
https://github.com/obsproject/obs-studio/blob/95a920d7eea8a2db117aa9ffbc062b9027f24e32/plugins/win-capture/graphics-hook/vulkan-capture.c#L1320

Call to get swap chain images without check for success:
https://github.com/obsproject/obs-studio/blob/95a920d7eea8a2db117aa9ffbc062b9027f24e32/plugins/win-capture/graphics-hook/vulkan-capture.c#L1324

**Comment by jpark37** [comment]
Seems easy enough to clean up. Did this break unit tests or something, or were you just inspecting the code?

**Comment by dzimanAMD** [comment]
We were testing an application.
