### ISSUE TITLE
Mac App Bundle created from source does not contain qt dynamic libraries

### ISSUE THREAD

**Issue by xp19870106** [obsproject/obs-studio#2487]
I use macOS Build Directions from 
https://github.com/obsproject/obs-studio/wiki/Install-Instructions#macos-build-directions
and the dmg file created by 'make package' command does not contian qt libraries, so it can not run on other's mac

sorry the picture of content folder can not be shown!

**Comment by xp19870106** [comment]
![Screen Shot 2020-03-11 at 11 28 39 PM](https://user-images.githubusercontent.com/5085902/76434386-93ba9180-63f0-11ea-990e-539c9aac2606.png)

**Comment by Fenrirthviti** [comment]
If you are having issues building OBS, please contact us on the forums or discord.

https://obsproject.com/help
