### ISSUE TITLE
Automatic flip of sources, MacOS

### ISSUE THREAD

**Issue by aski71** [obsproject/obs-studio#2489]
## Expected Behavior
The selected source that is currently streaming is supposed to stay the selected source until user interaction.

## Current Behavior
After some time the source that is to go online next (after the user pressing the transition button) is transitioned to without any user interaction.

## Steps to Reproduce
I set up a source from a USB camera and another source that plays VLC videos.
When I start the streaming, attach it to facebook and watch the preview, I can see the source of the video camera. Fine. Then I press transition and the facebook preview shows the videos playing. Then I leave for some minutes and upon return I discover that OBS automatically switched back to the camera source. This happens a few times until it gets to a stable situation.

## Additional information
macOS 10.13.6
obs 24.0.2

**Comment by Fenrirthviti** [comment]
The issues page is not for support, please use the Discord or forums instead.

This sounds like you have set a hotkey and are hitting it by accident.
