### ISSUE TITLE
25.0.0-rc5: building from source (on linux) broken

### ISSUE THREAD

**Issue by balducci** [obsproject/obs-studio#2490]
hello

apologies if I am missing something trivial here

Build of 25.0.0-rc5 (cloned from the git repo) on linux fails with:

    ---8<----
    cd /home/balducci/tmp/install-us-d/obs-studio-24.0.6.d/obs-studio-25.0.0-rc5/plugins/obs-browser && /opt/stow.d/versions/cmake-3.17.0-rc2/usr/bin/cmake -E cmake_link_script CMakeFiles/obs-browser-page.dir/link.txt --verbose=1
    /usr/bin/g++  -m64  -Wall -Wextra -Wvla -Wno-unused-function -Wno-missing-field-initializers  -fno-strict-aliasing -O2 -g -DNDEBUG  -rdynamic CMakeFiles/obs-browser-page.dir/obs-browser-page_autogen/mocs_compilation.cpp.o CMakeFiles/obs-browser-page.dir/obs-browser-page/obs-browser-page-main.cpp.o CMakeFiles/obs-browser-page.dir/browser-app.cpp.o CMakeFiles/obs-browser-page.dir/deps/json11/json11.cpp.o  -o obs-browser-page  -Wl,-rpath,/home/balducci/tmp/install-us-d/obs-studio-24.0.6.d/obs-studio-25.0.0-rc5/cef_binary_3770_linux64/Release: ../../cef_binary_3770_linux64/Release/libcef.so ../../cef_binary_3770_linux64/build/libcef_dll_wrapper/libcef_dll_wrapper.a 
    /usr/bin/ld: cannot open output file obs-browser-page: Is a directory
    collect2: error: ld returned 1 exit status
    ---->8----

There actually seems to be an inconsistency where the requested linker
output filename (-o obs-browser-page) is the same as that of a
(sub)directory of the working dir

    ----8<----
    /home/balducci/tmp/install-us-d/obs-studio-24.0.6.d/obs-studio-25.0.0-rc5/plugins/obs-browser/obs-browser-page
    ---->8----

If that matters, configuring with:

    ----8<----
    cmake \
    -G '"Unix' 'Makefiles"' \
    -DCMAKE_INSTALL_PREFIX=/opt/stow.d/versions/obs-studio-25.0.0-rc5/usr \
    -DCMAKE_VERBOSE_MAKEFILE=ON \
    -DUNIX_STRUCTURE=1 \
    -DBUILD_BROWSER=ON \
    -DCEF_ROOT_DIR=/home/balducci/tmp/install-us-d/obs-studio-24.0.6.d/obs-studio-25.0.0-rc5/cef_binary_3770_linux64 \
    -Wno-dev /home/balducci/tmp/install-us-d/obs-studio-24.0.6.d/obs-studio-25.0.0-rc5
    ----8<----

No problems with 24.0.6

thanks 
ciao
-gabriele

**Comment by Fenrirthviti** [comment]
Please use the Discord or forums for support.
