### ISSUE TITLE
OBS Crash During Bandwidth Test

### ISSUE THREAD

**Issue by engineershamrock** [obsproject/obs-studio#2491]
## Expected Behavior

It should not crash 

## Current Behavior

During the bandwidth test OBS says it has crashed.

## Steps to Reproduce

1. Tools -> Autoconfiguration Wizard
2. Click Next until it will start the bandwidth test
3. Force disconnect the RTMP connection on the server side 3 times, 2 seconds apart.
4. OBS will reconnect twice but the third time it will crash, occasionally the second time

If you desperately need a log file to repro I can provide but the steps are pretty simple.

**Comment by Fenrirthviti** [comment]
This crash has been fixed and the fix will be in v25.

**Comment by engineershamrock** [comment]
wow speedy!

**Comment by Fenrirthviti** [comment]
For clarity, it was fixed about a month ago :)

https://github.com/obsproject/obs-studio/pull/2357
