### ISSUE TITLE
obs-filter link error .      Which library am I missing?

### ISSUE THREAD

**Issue by chengkeke366** [obsproject/obs-studio#2499]
I am build the obs-studio project.  I has a  link error :
Can you help me??  I am crazy!

version : MacOS10.15,    Qt5.9,    FFmpeg4.2

`Ld build/plugins/obs-filters/Debug/obs-filters.so normal x86_64
    cd /Users/chengkeke/Work/Src/OBS/obs-studio
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-macos10.15 -bundle -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -L/Users/chengkeke/Work/Src/OBS/obs-studio/build/plugins/obs-filters/Debug -F/Users/chengkeke/Work/Src/OBS/obs-studio/build/plugins/obs-filters/Debug -filelist /Users/chengkeke/Work/Src/OBS/obs-studio/build/plugins/obs-filters/obs-studio.build/Debug/obs-filters.build/Objects-normal/x86_64/obs-filters.LinkFileList -Xlinker -rpath -Xlinker @loader_path/ -Xlinker -rpath -Xlinker @executable_path/ -Xlinker -object_path_lto -Xlinker /Users/chengkeke/Work/Src/OBS/obs-studio/build/plugins/obs-filters/obs-studio.build/Debug/obs-filters.build/Objects-normal/x86_64/obs-filters_lto.o -Xlinker -no_deduplicate -Wl,-search_paths_first -Wl,-headerpad_max_install_names /Users/chengkeke/Work/Src/OBS/obs-studio/build/libobs/Debug/libobs.0.dylib -framework OpenGL -framework CoreGraphics -Xlinker -dependency_info -Xlinker /Users/chengkeke/Work/Src/OBS/obs-studio/build/plugins/obs-filters/obs-studio.build/Debug/obs-filters.build/Objects-normal/x86_64/obs-filters_dependency_info.dat -o /Users/chengkeke/Work/Src/OBS/obs-studio/build/plugins/obs-filters/Debug/obs-filters.so`

**Comment by notr1ch** [comment]
Please use the forums or Discord for support.
