### ISSUE TITLE
m3u8 recording stucks after 14 or 33 segments

### ISSUE THREAD

**Issue by DaWe35** [obsproject/obs-studio#2500]
I'm recording into m3u8 on Windows 10 and after n number of .ts sectors are recorded, nothing happens. No error message, CPU/GPU performaces are the same, it just do not generate any new files, and when I click Stop recording, it never stops - I need to shutdown OBS from taks manager.

With OBS 23.2.1 I can record 16 segments
With OBS 24.0.3 I can record 33 segments before stuck
With OBS 25.0-rc5 I can record 16 segments
With OBS 25.0.1 I can record 14 segments

I tried out a lot of options, same happened with m3u8.

## Expected Behavior

Record infinite .ts segments.

## Current Behavior
Stuck at 14, 16, or 33, depends on the version.

## Steps to Reproduce

1. Set the Recording format to m3u8
2. Start recording
3. Wait for 14/33 files

## Additional information

[logs.zip](https://github.com/obsproject/obs-studio/files/4333322/logs.zip)

**Comment by derrod** [comment]
This is normal, by default the hls muxer will produce a live playlist with a limited time window:

See this in the logs:
```
17:32:30.381: [ffmpeg muxer: 'simple_file_output'] Using muxer settings:
17:32:30.381: 	hls_time=30
17:32:30.381: 	hls_list_size=0
```

Check ffmpeg documentation for how to correctly configure this muxer: https://ffmpeg.org/ffmpeg-formats.html#hls-2 Keep in mind that muxer parameters in OBS have the a space separated format like `key=value key2=value2`.

**Comment by DaWe35** [comment]
> This is normal, by default the hls muxer will produce a live playlist with a limited time window:
> 
> See this in the logs:
> 
> ```
> 17:32:30.381: [ffmpeg muxer: 'simple_file_output'] Using muxer settings:
> 17:32:30.381: 	hls_time=30
> 17:32:30.381: 	hls_list_size=0
> ```
> 
> Check ffmpeg documentation for how to correctly configure this muxer: https://ffmpeg.org/ffmpeg-formats.html#hls-2 Keep in mind that muxer parameters in OBS have the a space separated format like `key=value key2=value2`.


@derrod is it normal that I need to kill OBS from task manager? Is it normal that I lost my data?
- The same happens **with and without** custom mixer settings.
- I know how to write the mixer parameters, I spend 2 days around the issue.
Please read my report again, and tell me if I was not understandable.

**Comment by DaWe35** [comment]
I recorded my screen: https://www.youtube.com/watch?v=VitmvCyZoko

**Comment by derrod** [comment]
Alright I misunderstood what the issue was and I can reproduce now, apologies.

Seems like the ffmpeg muxer is somehow locking up, that'll take some time to figure out...

**Comment by DaWe35** [comment]
@derrod how can I help to fix it soon? I don't see through how OBS works, and I don't have too much money, would 100$ in BTC mean anything? I saw there is a 10 000$ bounty, I can't compete with it, but I really want to help you.

**Comment by cthurston** [comment]
We've tested m3u8 local recording on 5 different machines with the following results:
MacOS, OBS 25 - Works great software and hardware encode. (Software encode with ffmpeg hls).
Windows, OBS 24, 25 - Will record 19 segments (40 seconds) then freeze with hardware encoding. With software encode it seems to work fine.

Given those results we think the issue is somewhere with windows and hardware encoding. Hopefully this helps track down the issue.

**Comment by Delivator** [comment]
I'm having the same issue!

**Comment by craigkehl** [comment]
Tested this issue with OBS 26.0.0:
MacOS Catalina 10.15.7 - Works as mentioned above
Windows 10 2004 19041.508 - Will record 1 segment before crashing.

**Comment by RytoEX** [comment]
Please confirm if this is still an issue with OBS Studio 28.0.2.

**Comment by craigkehl** [comment]
The issue with Windows 10 has been resolved. Thank you.
