### ISSUE TITLE
Update QT in Windows CI script to 5.14.1

### ISSUE THREAD

**Issue by EwoutH** [obsproject/obs-studio#2504]
Since QT got updated to 5.14.1 for the macOS builds (in f0fe107 by @DDRBoxman), I think the Windows build should use the same version to prevent comparability issues.

- [ ] Upload a new QT version to cdn-fastly.obsproject.com
- [ ] Update the QT version to 5.14.1 in [CI/install-qt-win.cmd#L1](https://github.com/obsproject/obs-studio/blob/master/CI/install-qt-win.cmd#L1) and [CI/install-script-win.cmd#L12](https://github.com/obsproject/obs-studio/blob/master/CI/install-script-win.cmd#L12)
- [ ] Test the new Windows builds

**Comment by Fenrirthviti** [comment]
The issues page is only for bug reports. Please discuss in the #development channel on our Discord or forums instead.

**Comment by dodgepong** [comment]
The reason Qt got updated in Mac CI was to fix an issue that seems to only be fixable on Mac by updating to a newer version. However, even on Mac, doing so has come with some issues. We aren't going to update Qt on Windows unless those sorts of issues can be sorted out, as a Qt update would probably cause a lot more problems than it would solve.
