### ISSUE TITLE
Feature request - make it possible to hide the Menu

### ISSUE THREAD

**Issue by gerazov** [obsproject/obs-studio#2508]
Hi guys, I'm using OBS in a workaround to enable me to share a single screen in BigBlueButton as described here https://github.com/bigbluebutton/bigbluebutton/issues/8785

I've managed to trim almost everything from the interface except the Menu, and it would be nice to be able to hide the Menu (say with Ctrl+M like in KDE apps).

![image](https://user-images.githubusercontent.com/15214418/76785369-9bde4c80-67b5-11ea-80f9-a04cb5e145f1.png)

If I select Fullscreen Projector (Preview) instead, I do get the whole screen but then it stays on top of other applications.

**Comment by UserNaem** [comment]
Settings > General
![image](https://user-images.githubusercontent.com/21028464/76836172-2e342e00-6852-11ea-9670-5b06a85114fa.png)

**Comment by gerazov** [comment]
That's weird, I have it deselected like you're showing here.
![image](https://user-images.githubusercontent.com/15214418/76837779-68da9e00-6833-11ea-8479-b5aa791c20e4.png)
but still the preview stays on top ...

**Comment by UserNaem** [comment]
At this point, all newly created projectors should be overlapped by other windows. Have you restarted obs and re-created projectors?
Your fonts don't look.. Windows-like, are you using Linux? If so, this might be an OS-specific issue.

**Comment by gerazov** [comment]
They don't. I am using Linux - Plasma Manjaro 19.0.2 (kernel 5.4), might be OS specific I guess.

**Comment by Fenrirthviti** [comment]
The Issues page is for verified bug reports only. If you have a suggestion or feature request, please use the ideas page: https://ideas.obsproject.com/ per the Issue template.

**Comment by gerazov** [comment]
Ok got it. I filed a bug for the staying on top bit. btw Windowed projector does obey and solves my issue!
Thanks!
