### ISSUE TITLE
Add improved Window Capture for Linux

### ISSUE THREAD

**Issue by yulayula16** [obsproject/obs-studio#2510]
XComposite Window Capture is useless half the time because doesn't capture windows that draw their own windowing compositors separate from the desktop's own desktop compositor. This is in the case of Node.js, Electron built applications and Qt5 applications. It's possible for people using Qt5 to build their own custom windowing compositor instead of using the standard desktop windowing compositor, applications like these cannot be seen properly by OBS because they show up as nothing, transparent window captured source.

**Comment by kkartaltepe** [comment]
Github issues are not for feature requests. Please use our ideas page. https://ideas.obsproject.com/
