### ISSUE TITLE
Make projectors always on top doesn't work

### ISSUE THREAD

**Issue by gerazov** [obsproject/obs-studio#2514]
When I do a `Fullscreen projector (Preview)` it keeps staying on top even if the `Make projectors always on top` option is unchecked. 
![image](https://user-images.githubusercontent.com/15214418/76837779-68da9e00-6833-11ea-8479-b5aa791c20e4.png)
It does work for `Windowed projector` though.

I am running GNU/Linux - Plasma Manjaro 19.0.2 (kernel 5.4).

**Comment by Fenrirthviti** [comment]
I believe this is intentional. That is the point of a fullscreen projector.

**Comment by Fenrirthviti** [comment]
Also, in the future, please do not delete the issue template. Github issues is restricted to verified and repeatable bug reports, so please make sure you fill out the template appropriately when submitting a report.

**Comment by VodBox** [comment]
"Make projectors always on top" is a setting that is respected on Windows for fullscreen projectors. It not being respected on a Linux distro is definitely a bug.

**Comment by gerazov** [comment]
@Fenrirthviti there was not much more to say than what I wrote so I didn't respect the template. If you think this is the way it should work then maybe it would make sense to change the setting to `Make Windowed Projectors always on top`.

On the other hand, if it does work on Windows as @VodBox says, it should be made the same.

Anyways, I really like OBS-studio and have recommended it to all my colleagues for doing their online teaching videos :wink:
