### ISSUE TITLE
New window hook also capture cursor 

### ISSUE THREAD

**Issue by Marocco2** [obsproject/obs-studio#2517]
Using new window capture, OBS captures also cursor without any option to disable it

## Expected Behavior

OBS should capture window without cursor if there was an option to disable it

## Current Behavior

OBS captures also cursor and there is no way to change that behaviour 

## Steps to Reproduce

1. Set up a scene with a Window projector
2. Select a window (my example: Microsoft Teams)
3. Move your cursor onto window captured
4. Cursors should be seen in preview panel

## Additional information

Windows 10 20H1
OBS 25.0 stable
Dual monitor

**Comment by derrod** [comment]
Currently it is not possible to disable the cursor because Microsoft didn't add that feature yet. As of Windows 10 2004 it will be possible though and OBS will be updated accordingly.

**Comment by jpark37** [comment]
He did say he was on 20H1, but the Windows SDK isn't officially released yet.

**Comment by Marocco2** [comment]
> 
> 
> Currently it is not possible to disable the cursor because Microsoft didn't add that feature yet. As of Windows 10 2004 it will be possible though and OBS will be updated accordingly.

Shouldn't this be left open and closed when it's implemented?

**Comment by detroittiger79** [comment]
I agree. This should be open until it is resolved.

**Comment by Fenrirthviti** [comment]
My understanding is that the code on the OBS side already exists. It will start working as soon as the update is released from Microsoft.

**Comment by jpark37** [comment]
The code is there, but we still need to build OBS with the new SDK, and do a release.

**Comment by shantnu-agarwal** [comment]
OBS Version 25.0.8 and Windows 10 2004 Build 19041, this still hasn't been resolved. Even if the captured windows is on a different virtual desktop, the mouse pointer is captured and relayed on the recording/stream. 
Strange that the issue has been closed without a resolution. @derrod

**Comment by WizardCM** [comment]
Correct, "we still need to build OBS with the new SDK, and do a release" - this has not occurred yet, but soon.

**Comment by shantnu-agarwal** [comment]
Eagerly waiting 💯
