### ISSUE TITLE
MacBook Pro FaceTime camera not listed under devices (24.0.6, High Sierra)

### ISSUE THREAD

**Issue by cesss** [obsproject/obs-studio#2521]
## Expected Behavior

On the first start of the application, the FaceTime builtin camera should appear in the devices list when you add a new device.

## Current Behavior

The builtin camera is not in the list.

## Steps to Reproduce

1. Download the **OBS** 24.0.6 DMG on a MacBook Pro with High Sierra and install it
2. Click on the + button at the devices list
3. The builtin camera is not in the list.

## Additional information

Yes, I searched for this, and found some threads suggesting to add **OBS** to the Privacy allowed apps. I did it, restarted OBS, but no change. Then, I tried to record video from the builting cam using **ffmpeg**, and it worked out of the box (I didn't grant any permission to **ffmpeg**, nor it popped up any dialog box for granting permissions, it just was able to record from the FaceTime camera out of the box). Note that I'm not able to debug this because I have no time, I just needed to record some videotutorials with picture-in-picture today, so I cannot help you debugging this (I'll be using **Quicktime Player** instead because I need it now). I'm just reporting this in case it can help you to improve Mac support in the future.

In case it can help you, this is what **ffmpeg** finds in my Mac (again, without granting any permissions to it):

```
ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with Apple LLVM version 8.1.0 (clang-802.0.42)
  configuration: --prefix=/Users/cesss/FFmpeg/4.1 --disable-static --enable-shared --enable-libmp3lame --enable-libvorbis --enable-libtheora --enable-libopenh264 --enable-libvpx --sysroot=/Users/cesss/external/MacOSX10.12.sdk
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
[AVFoundation input device @ 0x7fa1b18075c0] AVFoundation video devices:
[AVFoundation input device @ 0x7fa1b18075c0] [0] FaceTime HD Camera
[AVFoundation input device @ 0x7fa1b18075c0] [1] Capture screen 0
[AVFoundation input device @ 0x7fa1b18075c0] AVFoundation audio devices:
[AVFoundation input device @ 0x7fa1b18075c0] [0] MacBook Pro Microphone
```

**Comment by afriza** [comment]
Have you checked if the `Video Capture Device` shows your `FaceTime HD Camera`?

![OBS-Video-Capture-Device](https://user-images.githubusercontent.com/68133/78315555-917acb80-7587-11ea-82c7-4e39900e5788.png)

**Comment by Fenrirthviti** [comment]
Can you please confirm if this is still an issue on 25.0.7? Also, as mentioned in the above comment, you add a webcam as a Video Capture Device, and you might need to allow OBS access in the privacy options.

**Comment by WizardCM** [comment]
Friendly bump - please verify if this is still an issue in OBS 26.1.0.

**Comment by PatTheMav** [comment]
I vote to close this - no reaction since march, affected OBS v24 and High Sierra.

**Comment by gxalpha** [comment]
Closing as stale.
Feel free to reopen this issue and respond to the feedback above should the problem persist in OBS 27.2.
