### ISSUE TITLE
The status bar (window name) is light when the Windows app uses a dark theme

### ISSUE THREAD

**Issue by Rakleed** [obsproject/obs-studio#2522]
## Expected Behavior

The status bar (window name) is dark when the Windows app uses a dark theme
## Current Behavior

The status bar (window name) is light when the Windows app uses a dark theme
## Steps to Reproduce

1. Open Setting
2. Chose Dark theme

## Additional information

![image](https://user-images.githubusercontent.com/19418601/77106064-9a1fbd80-6a2f-11ea-9590-e8b4b7f55a0e.png)

**Comment by WizardCM** [comment]
The title bar colour is controlled by your system settings, not by OBS. As far as I know, Qt doesn't have the ability to change it.

Open the Windows 10 Settings app, then go to Personalisation, Colors, scroll down and select "Show the accent colour on the following surfaces: Title bars and window borders"
