### ISSUE TITLE
OBS should not be in a folder in the Windows Start menu

### ISSUE THREAD

**Issue by Poopooracoocoo** [obsproject/obs-studio#2525]
## Expected Behavior

OBS Studio is by itself in the Windows Start menu

## Current Behavior

OBS Studio is in a folder in the Start menu called OBS Studio

## Steps to Reproduce

N/A, not that type of bug.

## Additional information

Sorry, I know this is a very low priority issue.

**Comment by Fenrirthviti** [comment]
I'm confused by this report. We add shortcuts to the start menu as part of the installer. Is your report that you don't want those icons to be added?

**Comment by WizardCM** [comment]
There are two reasons why it's in a folder:
1. Previously we shipped both 32/64bit together, so having them in a folder made sense
2. We provide the Uninstaller in the start menu, so having it in a folder is good

**Comment by Fenrirthviti** [comment]
Going to close this, because it's not really a bug. Please use the Ideas page or come talk to us on Discord.

**Comment by Poopooracoocoo** [comment]
@WizardCM Microsoft recommends in various places that a shortcut for the uninstaller should not be placed in the start menu. I've seen it on Old New Thing from Raymond Chen. It also pops up in Windows Search which is another side effect.

@Fenrirthviti Ah alright. Thanks Joel! :)

**Comment by Poopooracoocoo** [comment]
if anyone happens to stumble upon this, here's a link to the OBS Ideas page: https://ideas.obsproject.com/posts/770/take-obs-studio-out-of-its-folder-and-remove-the-shortcut-to-uninstall-in-the-windows-start-menu
