### ISSUE TITLE
OBS hangs when closing settings dialog, color pick dialog, perhaps other dialogs

### ISSUE THREAD

**Issue by dx9s** [obsproject/obs-studio#2530]
The recent 25.0.1 has several UI 

## Expected Behavior

Closing various dialog windows should not lock up the application

## Current Behavior

Open settings dialog, try to close it.

## Steps to Reproduce

1. removed obs-studio, remove ~/.config/obs-studio
2. reinstall obs-studio from PPA
3. open settings
4. click OK and OBS hangs

## Additional information

Same thing also happens with other dialogs such as color picker (under various filters)

**Comment by dx9s** [comment]
Trying to downgrade to previous 24.whatever it was as it was usable.

**Comment by kkartaltepe** [comment]
Please provide a log and a backtrace from the hang. There was a crash introduced into settings in 25.0.1 with a fix pending. But i cannot replicate any hangs in color source even on the affected version.

**Comment by dx9s** [comment]
I just downloaded the source for 25 and rebuilt some deb.. @kkartaltepe I am rusty on GNU debugger (remember).. but when I run from command line, it does core dump.. Can you run me through some steps or point me at a wiki. 

Thanks in advance.

**Comment by dx9s** [comment]
have some output .. need to output to a file instead of pasting the whole thing here?! what is preferred and what options to throw at gdb:

here is a portion: 
Thread 1 "obs" received signal SIGSEGV, Segmentation fault.
0x00007ffff4eb5400 in QAbstractButton::isChecked() const () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
(gdb) bt
#0  0x00007ffff4eb5400 in QAbstractButton::isChecked() const () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#1  0x0000555555651d94 in  ()
#2  0x0000555555651e98 in  ()
#3  0x000055555573c2da in  ()
#4  0x00005555557401a5 in  ()
#5  0x00007ffff3d97619 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007ffff4f5504f in QDialogButtonBox::clicked(QAbstractButton*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007ffff4f55646 in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007ffff3d97555 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007ffff4eb4ba2 in QAbstractButton::clicked(bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007ffff4eb4dba in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007ffff4eb619a in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007ffff4eb638d in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff4e02048 in QWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff4dc383c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff4dcb65f in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ffff3d688d8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007ffff4dca632 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ffff4e1d16b in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007ffff4e1f7da in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007ffff4dc383c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007ffff4dcb104 in QApplication::notify(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007ffff3d688d8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007ffff432a583 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#24 0x00007ffff432c055 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#25 0x00007ffff43032eb in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#26 0x00007fffdb795676 in  () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#27 0x00007ffff3d6690a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#28 0x00007ffff4fadf17 in QDialog::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#29 0x000055555561db9f in  ()
#30 0x000055555573f02a in  ()
#31 0x0000555555742537 in  ()
#32 0x00007ffff3d97619 in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x00007ffff4eb4ba2 in QAbstractButton::clicked(bool) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#34 0x00007ffff4eb4dba in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#35 0x00007ffff4eb619a in  () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#36 0x00007ffff4eb638d in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#37 0x00007ffff4e02048 in QWidget::event(QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#38 0x00007ffff4dc383c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5

**Comment by kkartaltepe** [comment]
There is a fix for this already out. It should be available in 25.0.2

**Comment by dx9s** [comment]
I'll keep eye open and report back here. Also if a (most likely) unrelated issues still exists, I'll report that in separate issue.

**Comment by dx9s** [comment]
manually applying this patch and rebuilding now: https://github.com/obsproject/obs-studio/pull/2524/files ..
I think it solved it.. needed the fix ASAP for upcoming meeting .. Thanks @kkartaltepe

**Comment by dx9s** [comment]
25.0.4 also fixes the color picker by NOT using the gnome default color picker it appears.
