### ISSUE TITLE
Building from source on MAC does not support SRT

### ISSUE THREAD

**Issue by mikeRead** [obsproject/obs-studio#2531]
## Expected Behavior
After building using the workflow defined here https://github.com/obsproject/obs-studio/wiki/Install-Instructions#macos
SRT Should be supported

## Current Behavior

After building and Setting up a SRT recording and clicking record button, alert pops up saying the protocol was not found
## Steps to Reproduce

1. Build as directed at https://github.com/obsproject/obs-studio/wiki/Install-Instructions#macos
3. Open build `cd build/rundir/RelWithDebInfo/bin && ./obs`
4.  Setup Recording via "Option 2: stream srt with the Custom FFmpeg Record output"
https://obsproject.com/wiki/Streaming-With-SRT-Protocol
5. Click Record
6. SRT protocol not found error will show

## Additional information

This seems to be that the ffmpeg brew does not have srt (https://formulae.brew.sh/formula/ffmpeg)
Running `brew install ffmpeg`  does not seem to install srt and `brew install ffmpeg --with-srt` fails

But installing with this tap and --with-srt works as expected
```
brew tap homebrew-ffmpeg/ffmpeg
brew install homebrew-ffmpeg/ffmpeg/ffmpeg --with-srt
```
(https://github.com/homebrew-ffmpeg/homebrew-ffmpeg)

**Comment by Fenrirthviti** [comment]
I am unsure what the bug report here is. We use FFmpeg's SRT support for OBS, so if the version of FFmpeg you are building against doesn't support SRT, this is expected that it will not work. This is an issue with brew's version of FFmpeg, not OBS.

**Comment by dodgepong** [comment]
Updated the wiki page to include the recommended instructions.

**Comment by mikeRead** [comment]
Thanks guys
