### ISSUE TITLE
Game Capture doesn't show some games.

### ISSUE THREAD

**Issue by tlfn** [obsproject/obs-studio#2535]
I'm an user who uses OBS to record my game, Minecraft (Lunar Client).
On OBS v25 series, it doesn't show my screen that Lunar Client shows to me, in its Preview screen. It just shows black screen.
I checked it worked well until v24.0.3.
So I just thought it's only preview issue but it even not record my games!
I tried to reset my obs settings but it didn't solve my problem.

**Comment by WizardCM** [comment]
GitHub issues are not for support requests. Please use our Discord or the forums.

Lunar Client need to update their anti-cheat to whitelist the latest version of OBS.
