### ISSUE TITLE
Can't choose which capture method to use in window capture properties & not work for UWP.

### ISSUE THREAD

**Issue by Mishasama** [obsproject/obs-studio#2540]
## Expected Behavior
https://github.com/obsproject/obs-studio/releases/latest
It should be a new feature for window capture, but not now.

## Current Behavior
![020321231305](https://user-images.githubusercontent.com/54498172/77228333-e30b7980-6bc9-11ea-98f3-f6424b9deab3.png)
Not see any new things in properties. And can't capture the MSN Weather (UWP), still black screen.
Log: [2020-03-21 21-50-19.txt](https://github.com/obsproject/obs-studio/files/4363114/2020-03-21.21-50-19.txt)

## Additional information
Windows Version: 10.0 Build 17134 (release: 1803; revision: 1304; 64-bit)
Tested under both iGPU & NvGPU.

**Comment by derrod** [comment]
The new Windows capture API is only supported on Windows 10 1903 or newer.
