### ISSUE TITLE
linux-capture: Try harder to produce valid window names

### ISSUE THREAD

**Issue by kkartaltepe** [obsproject/obs-studio#2542]
## Expected Behavior
We should be able to return valid window names if `xprop` can show a valid _NET_WM_NAME or NET_NAME.

## Current Behavior
If you set your locale to something invalid and have windows with non-ascii you can get invalid strings or "unknown" returned if you are lucky. 
E.G.
https://github.com/obsproject/obs-studio/pull/2541
https://obsproject.com/forum/threads/window-capture-xcomposite-only-showing-obs-menu-and-titling-every-window-as-unknown.91451/ 

## Steps to Reproduce

```
export LANG=en_XX.UTF-9
./obs
# Check window names here. I get garbage for firefox started from a different but also invalid locale. Ideally it would be "unknown" like other reports but we should also not return invalid strings.
# en_US.UTF-8 windows continue to work I think.
```

## Additional information
We should probably validate _NET_WM_NAME properties for being valid UTF-8 before attempting locale conversion (similar to xprop, and recommended by standards https://specifications.freedesktop.org/wm-spec/wm-spec-1.5.html#idm45408774038800). Also following from xprop this encoding will likely be accompanied by an empty(0) encoding atom and not XA_STRING.

Its also questionable if the XA_STRING atom should be passed back without undergoing conversion since it could actually be ISO8859-1 and not utf-8 if its somewhat standards compliant.

**Comment by kkartaltepe** [comment]
Someone ran into this again with a seemingly valid Indonesian locale.

**Comment by GeorgesStavracas** [comment]
Is this fixed by your rewrite of the xcomposite capture?

**Comment by kkartaltepe** [comment]
probably.... or at least i cannot replicate it with my old steps.
