### ISSUE TITLE
settings fault with 25.0.1 under linux

### ISSUE THREAD

**Issue by zenz** [obsproject/obs-studio#2543]
Change any settings with 25.0.1 under linux will crash the app. when Check the log, I can see the log stop at some point like this:
02时36分34秒.404: Settings changed (stream 1)
02时36分34秒.404: ------------------------------------------------

**Comment by kkartaltepe** [comment]
This is fixed in 25.0.2. Please update once it is released.

**Comment by chepecarlos** [comment]
the same and thanks for correcting the error
