### ISSUE TITLE
Windows/Updater: Incorrect user context after update

### ISSUE THREAD

**Issue by adlerweb** [obsproject/obs-studio#2546]
When starting OBS-Studio (obs64.exe, tested 25.0-rc1) it will check for updates and - if available - open a dialog based on obs-browser-page.exe to inform the user. If "update now" is selected obs64.exe and obs-browser-page.exe will be closed and "OBS Updater" (updater.exe; stored in user profile; v1.0.0.1?) started. OBS Updater will check if the user is allowed to modify software, ask for permissions if necessary (for example if UAC if enabled) and switch to a context with elevated permissions. After download and update are completed updater.exe stays open with a button "Launch OBS".  

## Expected Behavior
After a successful update the updater should drop down to the previous user context before starting OBS-Studio

## Current Behavior
After a successful update OBS-Studio is started in the same elevated context as the updater. OBS has in this case no access to user connected network drives, but still has full write permission to all system files and directories.

## Steps to Reproduce
1. Install a release of OBS-Studio for Windows older than the current stable
2. start OBS
3. When a update message is displayed start auto updater
4. Launch OBS from updater

## Additional information
* OS: W10P x64 19.09 DE
* Doesn't seem to affect the installer itself, there permissions are dropped before launching OBS
* ![obs-perm](https://user-images.githubusercontent.com/1146482/77246601-61e3cf00-6c29-11ea-993e-c897fc35a40c.png)
  * left: obs started from the system itself, Medium Mandatory Level
  * right: obs started from updater.exe, High Mandatory Level

**Comment by notr1ch** [comment]
This is more complex than it seems - the updater is already designed to always re-launch OBS under the context of the original user. It seems Windows may be "helpfully" elevating it by an application compatibility shim that looks for `*update*` in the application name, despite us using a manifest that should prevent this.

**Comment by notr1ch** [comment]
After a long and winding path down into the realms of application compatibility helpers, manifests and other fun topics, it turns out I was wrong in my initial assessment and this is now fixed in https://github.com/obsproject/obs-studio/commit/078ea5222dab23084b91b8476441d37cbdc2cbaf
