### ISSUE TITLE
Capturing from webcam on Ubuntu in 25.0.2 slows OBS to a crawl

### ISSUE THREAD

**Issue by codysandahl** [obsproject/obs-studio#2552]
OBS was working fine for me a few days ago with 24.0.3, but since upgrading to v25, whenever I add a Video Capture Device the app slows to a crawl. Clicks take 30-60 seconds to register. The webcam preview runs about 1-2 FPS. This affects every other capture as well, slowing window captures that were fine to a crawl as well. Oddly, my built-in laptop webcam light turns on and off repeatedly and it simply stayed on before. Changing between hardware and software capture did not solve the problem.

## Expected Behavior

Adding a video capture device should still allow previewing the capture at a normal frame rate. GUI interactions should still be almost instantaneous. Should be able to change settings on a video capture device.

## Current Behavior

Log file uploaded at https://obsproject.com/logs/3zJ0Z_oqPqWr_-Y-

Upon adding a video capture device, the preview frame rate drops to 1-2 FPS. CPU usage does NOT spike up to account for this. GUI interactions like mouse clicks take 30-60 seconds to register. The color of the video capture is sometimes very distorted.

## Steps to Reproduce

1. On Ubuntu 18, upgrade to OBS 25.0.2
2. Add a video capture device like an integrated or external USB webcam
3. Watch as the app slows to an unusable crawl

**Comment by kkartaltepe** [comment]
This was introduced fixing another bug, the fix is available https://github.com/obsproject/obs-studio/pull/2550

If you find this PR does not fix the issue feel free to reopen.
