### ISSUE TITLE
bug(vidi-dc): CreateForWindow (0x80070057): The parameter is incorrect.

### ISSUE THREAD

**Issue by Kristinita** [obsproject/obs-studio#2554]
### 1. Summary

I can't use `Windows Graphics Capture` Capture Method for [**ViDi-DC**](https://dvorkin.by/vidi-dc/) program. I get black screen.

### 2. Log

I downloaded it to [**obsproject.com**](https://obsproject.com/logs/ttsa5_0VHM8YouZ2).

### 3. Purpose

I want to record [**title bars**](https://www.computerhope.com/jargon/t/titlebar.htm) of my programs. I can't find methods for it in `Windows Capture` except using `Windows Graphics Capture`.

### 4. Steps to reproduce

I downloaded ([**direct download link**](https://dvorkin.by/downloads/ViDi-DC_setup.exe)) and installed ViDi-DC → I run ViDi-DC, then OBS Studio. Into OBS Studio: `Sources` → `Add` → `Window Capture` → I created new capture, that named `Debugging ViDi-DC Window Capture`.

### 5. Expected behavior

**If** `Window` — `ViDi-DC.exe` **and** `Capture Method` — `Automatic` **or** `BitBlt`:

![BitBlt](https://i.imgur.com/21Mq4PR.png)

**elif** `Window` — any program (I tried SumatraPDF, ConEmu, Sublime Text 3, Thunderbird) **and** `Capture Method` — `Windows Graphics Capture`:

![SumatraPDF](https://i.imgur.com/9yJm33Z.png)

OBS Studio works for me successfully.

### 6. Current behavior

**Else** `Window` — `ViDi-DC.exe` **and** `Capture Method` — `Windows Graphics Capture`:

![Black screen](https://i.imgur.com/vkgJM9r.png)

Black screen.

Part of the log:

```text
08:43:01.305: [window-capture: 'Debugging ViDi-DC Window Capture'] update settings:
08:43:01.305:   executable: ViDi-DC.exe
08:43:01.320: CreateForWindow (0x80070057): The parameter is incorrect.
```

#### 7.1. High performance

I set it as described in:

+ [**Laptop GPU Selection Windows 10 — OBS wiki article**](https://github.com/obsproject/obs-studio/wiki/Laptop-GPU-Selection-Windows-10)
+ [**Laptop? Black screen when capturing? Read here first. — OBS forum post**](https://obsproject.com/forum/threads/laptop-black-screen-when-capturing-read-here-first.5965/)
+ [**Solution for "Black Screen" Display Capture even after performing the steps on OBS forum**](https://obsproject.com/forum/threads/solution-for-black-screen-display-capture-even-after-performing-the-steps-on-obs-forum.112109/)

![High performance](https://i.imgur.com/aS9tEju.png)

No effect for both: `High performance` and `Power saving`.

#### 7.2. Run OBS Studio as administrator

I tried run OBS Studio as administrator, as described here:

+ [**How to Fix the OBS Capture Window Black Issue**](https://www.obs.live/articles/2019/3/20/how-to-fix-the-obs-capture-window-black-issue)

Also, no effect.

#### 7.3. Game Capture

![Game Capture](https://i.imgur.com/28pCa5H.png)

I can't set `Game Capture` so that it works for ViDi-DC.

#### 8.1. “GitHub issues are not for support requests”

As it's written [**here**](https://github.com/obsproject/obs-studio/issues/2535#issuecomment-602001776) or [**here**](https://github.com/obsproject/obs-studio/issues/2174#issuecomment-552134972). My issue is “bug report” (as [**this**](https://obsproject.com/mantis/view.php?id=167), for example), not “support request”. If “support request” has in OBS Studio terminology some specific meaning, please, add it to README or wiki.

#### 8.2. Don't use ViDi-DC

ViDi-DC has no alternatives for actions that I need.

#### 8.3. Use Display Capture instead of Window Capture

As recommended [**here**](https://obsproject.com/forum/threads/how-do-you-capture-entire-window-in-obs-studio.53978/#post-236882) or [**here**](https://obsproject.com/forum/threads/how-to-show-a-window-name.62422/#post-270851). `Windows Capture` is more easy and convenient. **If** `Display Capture`, streamer:

1. Must spend a time on the exact parameters in [**`Crop/Pad` filter**](https://www.youtube.com/watch?v=ypMDvZ_Jgl4);
1. Can't move and resize (otherwise incorrect area will display for stream viewers) ViDi-DC window quickly, without additional actions.

Thanks.

**Comment by Fenrirthviti** [comment]
Unfortunately, this appears to be an issue with the application not drawing windows correctly or in layers, which is not supported. There is no real solution we can implement on our end. Your options are to use Display Capture and crop (which is not ideal, I understand, but it DOES work) or to contact the developer of the application and ask them to update to a more modern UI framework.
