### ISSUE TITLE
"Display capture" doesn't work on Windows 10 ("window capture" works though)

### ISSUE THREAD

**Issue by luger19** [obsproject/obs-studio#2557]
## Expected Behavior
OBS should capture my screen in "Display capture" mode.

## Current Behavior
In "Display capture" mode OBS recognizes my screen (I have only one) but it doesn't capture what the screen shows.

## Steps to Reproduce
1. Start OBS
2. Choose "Display capture"
3. Select the screen. The preview is grey.
4.  Nothing to see. Only a black screen.

## Additional information
"Window capture" mode works fine.
My PC: Intel i7-6700HQ, GeForce 940MX and Windows 10 Pro 1909 (build 18363.720, but previous builds didn't work too)

**Comment by WizardCM** [comment]
The OBS Studio GitHub issue tracker is **only** to be used for reporting bugs that have replication steps. For support issues, use the Discord (https://obsproject.com/discord/) or forums (https://obsproject.com/forum/).

**Comment by luger19** [comment]
Solution: https://obsproject.com/forum/threads/laptop-black-screen-when-capturing-read-here-first.5965/
