### ISSUE TITLE
OBS crashes when pressing OK or Apply in settings prompt Manjaro Linux

### ISSUE THREAD

**Issue by pasimko** [obsproject/obs-studio#2558]
## Current Behavior
I believe that installing the [libva-vdpau-driver](https://www.archlinux.org/packages/?name=libva-vdpau-driver) to use VA-API caused OBS to crash when pressing OK or Apply Settings.
Log file: https://gist.github.com/pasimko/acd693f0ab943933c9a07f8e74d49cdb

## Steps to Reproduce
1. Install [libva-vdpau-driver](https://www.archlinux.org/packages/?name=libva-vdpau-driver) as described by the Arch Wiki
2. Restart computer
3. Open OBS settings, press OK or Apply

## Additional information
The autoconfigure wizard works, but manually adjusting settings does not. I reinstalled OBS and removed my config folder but this did not solve the issue.

**Comment by WizardCM** [comment]
Update to OBS 25.0.2 or above. There was a bug introduced in .1 which was fixed.
