### ISSUE TITLE
[Crash] Increase stability by replacing strcat_s  with snprintf

### ISSUE THREAD

**Issue by walker-WSH** [obsproject/obs-studio#2560]
strcat_s  cann't avoid memory error when buffer is overflow.
maybe it's better to use snprintf.

## Current Behavior

When input a long title for scene colloection, crash will happen

## Steps to Reproduce

1. Top menu > Scene Collection > New > Input long title > Click OK
2. crashed every time on 25.0.1

## Additional information

strcat_s is used in :
_obs/deps/ipc-util/ipc-util/pipe-windows.c
obs/libobs/util/platform-windows.c_

![2020-03-24 20;05;26](https://user-images.githubusercontent.com/18413354/77423789-ee011c80-6e0a-11ea-9c63-be580af98e6b.gif)

**Comment by notr1ch** [comment]
This is actually a larger issue with how ANSI / unicode conversion is performed in various places throughout the program, the buffers are not appropriately sized for when a large amount of unicode characters are used as in your example.
