### ISSUE TITLE
[Crash] Consider thread safe while deleting scene

### ISSUE THREAD

**Issue by walker-WSH** [obsproject/obs-studio#2561]
OBSBasic::GetCurrentScene() will be invoked from RenderMain() in graphic-thread.
In GetCurrentScene(), firstly get current pointer of QListWidgetItem, then return its user data (OBSScene); 

However, before returning user data, this item may be deleted in UI thread.
This crash happened once on my PC. Not easy to appear.

## Additional information

![1585051804](https://user-images.githubusercontent.com/18413354/77424882-c9a63f80-6e0c-11ea-97f9-a67181f1421d.png)
![1585051853](https://user-images.githubusercontent.com/18413354/77424830-b72c0600-6e0c-11ea-87df-f4baa83b4f20.png)

**Comment by notr1ch** [comment]
There must be at least one scene, so it does not seem possible to end up in a state where there is no current scene. Are you able to reproduce this crash or are you only commenting on the code?

**Comment by wangshaohui1314** [comment]
> There must be at least one scene, so it does not seem possible to end up in a state where there is no current scene. Were you only using the base OBS UI to edit scenes?

The crash situation is not that I was deleting the only scene. Steps as below:
1. added more than one scene;
2. delete current scene (not delete the only one, there are other scenes left); 

Yes, I was testing with the latest code

**Comment by notr1ch** [comment]
I was able to reproduce this during a shutdown with the sleep inserted, was difficult to reproduce during scene addition / deletion but the race condition definitely exists. It seems like we need to protect all OBSBasic functions that are called outside the UI thread with a mutex.

**Comment by wangshaohui1314** [comment]
@notr1ch
Yes, you got it! 
It is not safe to access UI object out of UI thread.

**Comment by wangshaohui1314** [comment]
> I was able to reproduce this during a shutdown with the sleep inserted, was difficult to reproduce during scene addition / deletion but the race condition definitely exists. It seems like we need to protect all OBSBasic functions that are called outside the UI thread with a mutex.

At present, I just find out here accessing scene widget out of UI thread:
in OBSBasic::RenderMain():
![1585114589](https://user-images.githubusercontent.com/18413354/77505266-a8416400-6e9d-11ea-870d-aa4ec86564cf.png)
![1585114389](https://user-images.githubusercontent.com/18413354/77505108-32d59380-6e9d-11ea-83c4-cc53b9f328c4.png)

**How about modify logic as below:**

![1585114537](https://user-images.githubusercontent.com/18413354/77505222-87790e80-6e9d-11ea-9e9e-091404b809a8.png)

**Comment by wangshaohui1314** [comment]
Oh ~~ 
I have confirmed that I cann't use invokeMethod with BlockingQueuedConnection in OBSBasic::GetCurrentScene(), it causes nested lock.

**Comment by PatTheMav** [comment]
Fixed by @norihiro already in 1c4bc6e.
