### ISSUE TITLE
Game Capture does not Detect Division 2

### ISSUE THREAD

**Issue by MrTeaRexx** [obsproject/obs-studio#2562]
## Expected Behavior
In any game window, Division 2 doesnt appear on game capture

## Current Behavior
21:33:45.552: User added source 'Game Capture' (game_capture) to scene 'Live!'21:33:45.552: 
obs-browser[2]: API: posting call to 'getAllManagedHotkeyBindings', callback id 32, args: []
21:33:45.553: obs-browser[2]: API: posting call to 'getAllManagedHotkeyBindings', callback id 33, args: []
21:33:45.553: obs-browser[2]: API: posting call to 'getAllManagedHotkeyBindings', callback id 34, args: []
21:33:45.627: obs-browser[1]: API: performing call to 'getAllManagedHotkeyBindings', callback id 19
21:33:45.627: obs-browser[1]: API: completed call to 'getAllManagedHotkeyBindings', callback id 19
21:33:45.627: obs-browser[2]: API: performing call to 'getAllManagedHotkeyBindings', callback id 27
21:33:45.627: obs-browser[2]: API: completed call to 'getAllManagedHotkeyBindings', callback id 27
21:33:45.627: obs-browser[1]: API: performing call to 'getAllManagedHotkeyBindings', callback id 20
21:33:45.627: obs-browser[1]: API: completed call to 'getAllManagedHotkeyBindings', callback id 20
21:33:45.628: obs-browser[1]: API: performing call to 'getAllManagedHotkeyBindings', callback id 21
21:33:45.628: obs-browser[1]: API: completed call to 'getAllManagedHotkeyBindings', callback id 21
21:33:45.628: obs-browser[2]: API: performing call to 'getAllManagedHotkeyBindings', callback id 28
21:33:45.628: obs-browser[2]: API: completed call to 'getAllManagedHotkeyBindings', callback id 28
21:33:45.628: obs-browser[1]: API: performing call to 'getAllManagedHotkeyBindings', callback id 22
21:33:45.628: obs-browser[1]: API: completed call to 'getAllManagedHotkeyBindings', callback id 22
21:33:45.628: obs-browser[2]: API: performing call to 'getAllManagedHotkeyBindings', callback id 29
21:33:45.628: obs-browser[2]: API: completed call to 'getAllManagedHotkeyBindings', callback id 29
21:33:45.628: obs-browser[1]: API: performing call to 'getAllManagedHotkeyBindings', callback id 23
21:33:45.628: obs-browser[1]: API: completed call to 'getAllManagedHotkeyBindings', callback id 23
21:33:45.628: obs-browser[1]: API: performing call to 'getAllManagedHotkeyBindings', callback id 24
21:33:45.628: obs-browser[1]: API: completed call to 'getAllManagedHotkeyBindings', callback id 24
21:33:45.628: obs-browser[2]: API: performing call to 'getAllManagedHotkeyBindings', callback id 30
21:33:45.628: obs-browser[2]: API: completed call to 'getAllManagedHotkeyBindings', callback id 30
21:33:45.628: obs-browser[1]: API: performing call to 'getAllManagedHotkeyBindings', callback id 25
21:33:45.629: obs-browser[1]: API: completed call to 'getAllManagedHotkeyBindings', callback id 25
21:33:45.629: obs-browser[2]: API: performing call to 'getAllManagedHotkeyBindings', callback id 31
21:33:45.629: obs-browser[2]: API: completed call to 'getAllManagedHotkeyBindings', callback id 31
21:33:45.629: obs-browser[1]: API: performing call to 'getAllManagedHotkeyBindings', callback id 26
21:33:45.629: obs-browser[1]: API: completed call to 'getAllManagedHotkeyBindings', callback id 26
21:33:45.629: obs-browser[2]: API: performing call to 'getAllManagedHotkeyBindings', callback id 32
21:33:45.629: obs-browser[2]: API: completed call to 'getAllManagedHotkeyBindings', callback id 32
21:33:45.629: obs-browser[2]: API: performing call to 'getAllManagedHotkeyBindings', callback id 33
21:33:45.629: obs-browser[2]: API: completed call to 'getAllManagedHotkeyBindings', callback id 33
21:33:45.629: obs-browser[2]: API: performing call to 'getAllManagedHotkeyBindings', callback id 34
21:33:45.629: obs-browser[2]: API: completed call to 'getAllManagedHotkeyBindings', callback id 34
21:34:00.671: [game-capture: 'Game Capture'] attempting to hook fullscreen process: TheDivision2.exe
21:34:00.674: [game-capture: 'Game Capture'] using helper (compatibility hook)
21:34:00.710: [game-capture: 'Game Capture'] hook not loaded yet, retrying..
21:34:03.693: [game-capture: 'Game Capture'] attempting to hook fullscreen process: TheDivision2.exe
21:34:03.698: [game-capture: 'Game Capture'] using helper (compatibility hook)
21:35:00.939: [game-capture: 'Game Capture'] attempting to hook process: TheDivision2.exe
21:35:00.941: [game-capture: 'Game Capture'] using helper (compatibility hook)
21:35:00.977: [game-capture: 'Game Capture'] hook not loaded yet, retrying..
21:35:02.955: [game-capture: 'Game Capture'] attempting to hook process: TheDivision2.exe
21:35:02.957: [game-capture: 'Game Capture'] using helper (compatibility hook)
21:35:04.972: [game-capture: 'Game Capture'] attempting to hook process: TheDivision2.exe
21:35:04.974: [game-capture: 'Game Capture'] using helper (compatibility hook)
21:35:05.010: [game-capture: 'Game Capture'] hook not loaded yet, retrying..
21:35:06.989: [game-capture: 'Game Capture'] attempting to hook process: TheDivision2.exe
21:35:06.991: [game-capture: 'Game Capture'] using helper (compatibility hook)
21:35:09.005: [game-capture: 'Game Capture'] attempting to hook process: TheDivision2.exe
21:35:09.007: [game-capture: 'Game Capture'] using helper (compatibility hook)
21:35:09.046: [game-capture: 'Game Capture'] hook not loaded yet, retrying..
21:35:11.022: [game-capture: 'Game Capture'] attempting to hook process: TheDivision2.exe
21:35:11.024: [game-capture: 'Game Capture'] using helper (compatibility hook)
21:35:13.038: [game-capture: 'Game Capture'] attempting to hook process: TheDivision2.exe
21:35:13.041: [game-capture: 'Game Capture'] using helper (compatibility hook)
21:35:13.078: [game-capture: 'Game Capture'] hook not loaded yet, retrying..
21:35:15.055: [game-capture: 'Game Capture'] attempting to hook process: TheDivision2.exe
21:35:15.058: [game-capture: 'Game Capture'] using helper (compatibility hook)
21:35:17.073: [game-capture: 'Game Capture'] attempting to hook process: TheDivision2.exe
21:35:17.075: [game-capture: 'Game Capture'] using helper (compatibility hook)
21:35:17.113: [game-capture: 'Game Capture'] hook not loaded yet, retrying..
21:35:19.089: [game-capture: 'Game Capture'] attempting to hook process: TheDivision2.exe
21:35:19.091: [game-capture: 'Game Capture'] using helper (compatibility hook)
21:35:21.105: [game-capture: 'Game Capture'] attempting to hook process: TheDivision2.exe
21:35:21.107: [game-capture: 'Game Capture'] using helper (compatibility hook)
21:35:21.142: [game-capture: 'Game Capture'] hook not loaded yet, retrying..
21:35:23.122: [game-capture: 'Game Capture'] attempting to hook process: TheDivision2.exe
21:35:23.124: [game-capture: 'Game Capture'] using helper (compatibility hook)
21:35:25.139: [game-capture: 'Game Capture'] attempting to hook process: TheDivision2.exe
21:35:25.141: [game-capture: 'Game Capture'] using helper (compatibility hook)
21:35:25.176: [game-capture: 'Game Capture'] hook not loaded yet, retrying..
21:35:27.155: [game-capture: 'Game Capture'] attempting to hook process: TheDivision2.exe
21:35:27.157: [game-capture: 'Game Capture'] using helper (compatibility hook)
21:35:29.173: [game-capture: 'Game Capture'] attempting to hook process: TheDivision2.exe
21:35:29.175: [game-capture: 'Game Capture'] using helper (compatibility hook)
21:35:29.208: [game-capture: 'Game Capture'] hook not loaded yet, retrying..
21:35:31.189: [game-capture: 'Game Capture'] attempting to hook process: TheDivision2.exe
21:35:31.191: [game-capture: 'Game Capture'] using helper (compatibility hook)
21:35:32.584: ==== Shutting down ==================================================

## Steps to Reproduce
1. Add Game Capture to OBS Latest Version
2. Change window method to Division 2

**Comment by ElectronicWar** [comment]
This is a known issue and you need to waiting until they ship an update to their anti-cheat software. Until then you can downgrade to OBS 24.0.3
