### ISSUE TITLE
custom css for iframe not work in obs but work in chrome

### ISSUE THREAD

**Issue by cyperdark** [obsproject/obs-studio#2564]
## Expected Behavior
Wanna result like on the right chat

## Current Behavior
Showed default iframe without custom css (the left chat)
p.s. custom css is added on the site itself and looks like this

> $("#myiFrame").on("load", function () {
>   let head = $("#myiFrame").contents().find("head");
>   let css = '<style>#chat_box{bottom:0}.chat_line{opacity:0;max-height:0;transform:translateX(-60px);animation-delay:.2s;animation:tryy .4s ease forwards}.emoticon{width:25px}@keyframes tryy{0%{transform:translateX(-60px);opacity:0;max-height:0}100%{transform:translateX(0);opacity:1;max-height:100px}}</style>';
>   $(head).append(css);
> });

## Steps to Reproduce
1. add Browser
2. past this link: https://chat.osuck.net

**Comment by notr1ch** [comment]
The issue tracker is not for support. Please debug your page using the Chrome debugger.

Launch OBS with `--remote-debugging-port=9222` then open your browser and go to http://localhost:9222/
