### ISSUE TITLE
[Bug]: Scene Collections with special characters ("/", "|") in their name cannot be imported

### ISSUE THREAD

**Issue by TreZc0** [obsproject/obs-studio#2566]
Scene Collections that include "/" in their name key are not imported into OBS using the Scene Collection Importer. 

## Expected Behavior
A scene collection with "/" in its name should be added to the list of scene collections in OBS v25.0.1 after using the Scene Collection Importer.

## Current Behavior
Instead of adding the scene collection to the list, OBS just doesn't do anything. It closes the dialog, doesn't give an error message. The scene collection is not added.
The log files do not output anything about the failed import.

## Steps to Reproduce
1. Create a scene collection in OBS, name it anything and include a "/" in the name (in our case "w/ routing)
2. Export the scene collection.
3. Delete the scene collection in OBS.
4. Try import the previously exported json file via Menu -> Scene Collection -> Import

## Additional information
OBS still allows "/" in names for scene collections.
Scene collections that contain this character in their "name" key can be added by manually putting the JSON file in %appdata%\obs-studio\basic\scenes and restarting OBS.

**Comment by TreZc0** [comment]
I should actually add another thing to this.
We'll having a scene collection with "/" in the name loaded, the Sources tab bugs out. New entries to it are not shown until you switch off the current scene and back to another.

**Comment by playaspec** [comment]
This isn't at all surprising. That character is used throughout the ENTIRE computing world (except the Microsoft ecosystem) as a path separator. It's ALWAYS been an illegal character for file names. It should filtered from being allowed by the app though.

**Comment by TreZc0** [comment]
This is not the file name, but the internal collection name though, so it can and should simply be escaped.

**Comment by tielqt** [comment]
I've also found that this issue applies to the "|" character. It works perfectly fine if you rename the collection to include this character afterwards, but importing this collection fails.

**Comment by RytoEX** [comment]
This was partially addressed by #3765, which specifically addressed forward slashes ("/") in scene collection names.  This should be completely addressed by #3916 if merged.
