### ISSUE TITLE
We are no longer using github issues

### ISSUE THREAD

**Issue by jp9000** [obsproject/obs-studio#257]
Github issues are terrible.  Too many people are just using github issues as just another forum.  So instead, we've set up a mantis bug tracker on the main site:

https://obsproject.com/mantis/

To use mantis, just create an account on the forums (which can be used both for forums and mantis) and then log in to leave an issue.  If you have an issue creating a forum account, just use the 'contact us' button at the bottom and I will create an account for you if you have issues with the spam filter.

We have moved over all major issues to the bug tracker.  Pull requests will still work fine, but if you have a legitimate bug, please use the bug tracker.

Do NOT use the bug tracker to ask questions, request features, or things that aren't bug/issue reporting.  Please use the relevant forums on the site.  I have too many different forums that I have to keep track of so it would be greatly helpful.

**Comment by Fenrirthviti** [comment]
Apologies to everyone for the email spam. We are starting fresh on issues here on GitHub. The above still applies, please do not submit support or feature requests to the GitHub issues page. Use the appropriate forum, Ideas page, Discord, or Mantis as appropriate. See https://obsproject.com/help for links to those.
