### ISSUE TITLE
[Bug][Crash] Remux renaming target file

### ISSUE THREAD

**Issue by OzakIOne** [obsproject/obs-studio#2575]
## Expected Behavior

1. Adding character to the default name shouldn't reset cursor position to the end of string (imo)
2. Replacing the whole string shouldn't be as [ laggy as it is / crashing obs ]

## Current Behavior

1. Each time a character is pressed, the cursor position is placed to the end of the filename
2. When replacing the whole string, obs goes crazy with cpu usage & ends up crashing

## Steps to Reproduce

1. Launch OBS
2. Go to : Files => Remux recordings => Select a video file
3. Rename the target file by [ adding character OR replacing the whole string ]

## Additional information

OBS Installed with scoop.sh 25.0.1 & ran without admin privileges 

https://i.imgur.com/odYJRlD.gifv

https://i.imgur.com/kVJ0qPX.gifv

**Comment by Fenrirthviti** [comment]
I can confirm this on my end, using our installer for v25.0.1.
