### ISSUE TITLE
[Bug] Studio mode transitions when program restarts

### ISSUE THREAD

**Issue by Fenrirthviti** [obsproject/obs-studio#2576]
## Expected Behavior
OBS should not transition when the program is restarted.

## Current Behavior
If set to studio mode, when OBS is restarted, the preview will become transitioned to the program.

## Steps to Reproduce
1. Open OBS
2. Enabled Studio Mode
3. Set a different scene to the preview than the program
4. Restart OBS
5. Observe that the preview is now set to the program

## Additional information
Suspicion is that this is caused by the t-bar addition, potentially because it might be defaulting to a value of 1? Speculation, but it does not occur in v24. I tested back to v25rc5 and the behavior is still present there.

**Comment by notr1ch** [comment]
Bug introduced here: https://github.com/obsproject/obs-studio/commit/f7d39c12c0bf9e0f1e715435fac32b61c1bdb937#diff-a0eec92bde9402a347f40d7593c0cdc9

Causes this code to no longer run: https://github.com/obsproject/obs-studio/blob/master/UI/window-basic-main.cpp#L968-L969

**Comment by RytoEX** [comment]
@cg2121 If this is still happening, could you take a look at this since it seems it was introduced from your PR?
