### ISSUE TITLE
NVENC encoding with preview disabled in 25.0.1 creates a condition of 10x worse performance

### ISSUE THREAD

**Issue by Vigrond** [obsproject/obs-studio#2579]
## Expected Behavior
Performance should not be significantly affected by turning Preview off

## Current Behavior
Skipped frames due to encoding lag is at ~2% with preview on
With Preview off it turns into 20%

Settings seem to be irrelevant besides using Nvenc (new)

My current settings are
1080
CBR
6000kbps
Max Quality
High
GPU 0

Hardware is RTX 2080
CPU is i9-9900K @ 3.6ghz
Windows 10
Nvidia driver 442.19
## Steps to Reproduce
Begin encoding, view stats, play a game

**Comment by Vigrond** [comment]
this was caused by a plugin.  sorry

**Comment by dodgepong** [comment]
Which plugin?

**Comment by Vigrond** [comment]
> 
> 
> Which plugin?

see edited update
