### ISSUE TITLE
BattlEye blocked loading of file: "C:\ProgramData\obs-studio-hook\graphics-hook64.dll".

### ISSUE THREAD

**Issue by kagurayui** [obsproject/obs-studio#2581]
11:56:31: Starting BattlEye Service...

11:56:36: Launching game...
11:57:07: Note: File blocks can be ignored if they don't cause problems with the game.
11:57:07: [INFO] Blocked loading of file: "C:\ProgramData\obs-studio-hook\graphics-hook64.dll".

**Comment by dodgepong** [comment]
The game you are trying to capture will need to update their BattlEye whitelist to allow the updated OBS game capture hook to hook the game. Nothing we can do about that, unfortunately, it's up to the game developer.
