### ISSUE TITLE
[linux] OBS Studio running on Wayland session of KDE Plasma desktop environment has Wayland generic icon in its title bar and in alt+tab menu

### ISSUE THREAD

**Issue by glaubersm** [obsproject/obs-studio#2585]
Hi
I use OBS Studio 25.0.3 on Arch Linux running KDE Plasma 5.18.3 desktop environment.

## Expected Behavior
When OBS Studio is running on Wayland session of KDE Plasma desktop environment,
title bar and alt+tab menu should show OBS Studio icon instead of Wayland generic icon. 

## Current Behavior
OBS Studio running on Wayland session of KDE Plasma desktop environment
has Wayland generic icon in its title bar and in alt+tab menu. See the screenshot below.

## Steps to Reproduce

1. use a linux distribution with KDE Plasma desktop environment
2. start Wayland session
3. open OBS Studio and observe the icon shown in its title bar
4. press alt+tab and hold alt key. Observe the icon of OBS Studio.

## Additional information

![obsstudio](https://user-images.githubusercontent.com/15967631/77771016-e917b500-7024-11ea-8d1c-4dcffca36e1e.png)

**Comment by Fenrirthviti** [comment]
Closing this as we currently do not support Wayland. There is work being done to support it, but until we finalize that support I don't feel there is anything we can do here. If this is a trivial change that you know how to make, feel free to submit a PR or provide it as part of the open Wayland support PRs.

**Comment by prometheanfire** [comment]
is there a place we can track the progress of the wayland work?

**Comment by dodgepong** [comment]
The best place would probably be here; https://github.com/obsproject/rfcs/pull/14

**Comment by glaubersm** [comment]
Unfortunately I don't understand anything about software development.
Maybe the following link can help someone else to solve this issue.

https://community.kde.org/Guidelines_and_HOWTOs/Wayland_Porting_Notes#Application_Icon

**Comment by dodgepong** [comment]
To "solve the issue" OBS needs to support Wayland, which it currently does not. The RFC that I linked is the best place to refer to regarding Wayland support status.

**Comment by glaubersm** [comment]
OBS already runs natively on Wayland.
It just is unusable to record the screen on Plasma yet.

Other apps that run natively on Wayland have this issue, here is an example
https://bugs.kde.org/show_bug.cgi?id=416669

**Comment by Fenrirthviti** [comment]
OBS might launch on wayland, but it does not "run natively" and we do not currently support it. Again, please follow the RFC or the open PRs for the current status of Wayland support. Once it is completed and merged, we can look at this issue. Or, you can make sure it is called out on the RFC as something to update (and what we need to do).

**Comment by glaubersm** [comment]
Apps running on Xwayland don't show Wayland icon in its title bar. I have even confirmed that OBS runs natively on Wayland with `xwininfo` command.

**Comment by kkartaltepe** [comment]
Considering xwininfo is an X tool as the name suggests, im not sure what you mean by natively on wayland.

Perhaps you have configured qt to run in wayland native, but that has no effect on obs internals which still use glx (requires X as the name suggests). And such a configuration will be broken in many more ways than just your icon.

**Comment by glaubersm** [comment]
it's obs icon, not mine.

https://fedoraproject.org/wiki/How_to_debug_Wayland_problems#Does_your_application_run_on_Wayland_natively.2C_or_uses_XWayland_.28X11_compatibility_layer.29.3F

**Comment by kkartaltepe** [comment]
That is only for telling if the window is using a wayland surface. Which as mentioned is insufficient for OBS, even if Qt is using a wayland surface OBS is not running natively under wayland.

**Comment by glaubersm** [comment]
OBS 27 offcially supports Wayland and this issue is still relevant.
Could anyone reopen it please? Thanks.

**Comment by kkartaltepe** [comment]
If this is still occuring it seems its because wayland either doesnt support setting the icons (likely) or Qt doesnt implement the appropriate wayland extensions.

We set the window icon via https://github.com/obsproject/obs-studio/blob/master/UI/obs-app.cpp#L1145 which works on X11.

There is a claim that this can be fixed for some compositors via a bunch of correctly installed files splattered across the file system and also manually setting the desktop file via something like https://git.libreoffice.org/core/+/045de7a51f402062f23a3deeb15a199fd039a6f2%5E%21 . We already have the files so we can try adding this call but given the highly likely chance of people having broken installs this will probably only work for people using correct packaging.

**Comment by glaubersm** [comment]
This bug occurs on KDE Plasma, not on Gnome. It's a common issue, here are some examples of wrong icons already fixed.

https://bugs.kde.org/show_bug.cgi?id=409956
https://bugs.kde.org/show_bug.cgi?id=416669
https://bugs.kde.org/show_bug.cgi?id=424823
https://github.com/ksnip/ksnip/issues/269

**Comment by tytan652** [comment]
It feels like a KDE Qt platform theme issue and an issue with OBS itself.

**Comment by glaubersm** [comment]
> It feels like a KDE Qt platform theme issue and not an issue with OBS itself.

I do not think so. The same bug was fixed in other apps. Some examples below:
https://github.com/ksnip/ksnip/issues/269
https://github.com/jurplel/qView/issues/432
https://bugs.launchpad.net/pinta/+bug/1967687

**Comment by tytan652** [comment]
Seems to be fixed since f43b046f8bb20a1a4f7d276a559f4924b7b6a9a8

**Comment by tytan652** [comment]
Sorry miss-click.

**Comment by tytan652** [comment]
Since 28 we switched to Qt6, so Qt decorations might not work with Qt6 right now.

**Comment by tytan652** [comment]
Installed Plasma and launched OBS 27 same for 28.
