### ISSUE TITLE
[NDI Source crash] Using latest version of OBS, setting up an NDI source makes OBS unexpectedly quit when attempting to confirm the source..

### ISSUE THREAD

**Issue by Mattefew** [obsproject/obs-studio#2592]
## Platform

Operating system and version:
OBS Studio version:

## Steps to Reproduce

1.
2.
3.
4.

**Comment by dodgepong** [comment]
Ignoring the fact that you didn't fill out the issue template: If you want to report an issue with the NDI plugin, please post it on the correct repository: https://github.com/Palakis/obs-ndi/issues
