### ISSUE TITLE
[Linux] Entire UI unresponsive to  clicks with Wacom tablet

### ISSUE THREAD

**Issue by inducer** [obsproject/obs-studio#2593]
## Expected Behavior

The UI (menus, buttons) should respond to clicks from my "Wacom Intuos Pen & Touch Small" (Wacom CTH-480).

## Current Behavior

They don't.

## Steps to Reproduce

1. `apt-get install obs-studio` (Debian archive, versions see below)
2. Connect Wacom hardware
3. Click on "Start recording" button with pen
4. Nothing happens

Other Qt5 apps (e.g. KeepassXC) do not have this issue.

## Additional information

<details>
<summary>Debian version info</summary>
<pre>
-- System Information:
Debian Release: bullseye/sid
  APT prefers testing
  APT policy: (990, 'testing'), (500, 'unstable-debug'), (500, 'stable-updates'), (500, 'unstable'), (500, 'stable'), (1, 'experimental')
Architecture: amd64 (x86_64)
Foreign Architectures: i386

Kernel: Linux 5.6.0-rc6 (SMP w/8 CPU cores)
Kernel taint flags: TAINT_WARN, TAINT_UNSIGNED_MODULE
Locale: LANG=de_DE.UTF-8, LC_CTYPE=de_DE.UTF-8 (charmap=UTF-8), LANGUAGE=de_DE:de (charmap=UTF-8)
Shell: /bin/sh linked to /usr/bin/dash
Init: systemd (via /run/systemd/system)
LSM: AppArmor: enabled

Versions of packages obs-studio depends on:
ii  libavcodec58         7:4.2.2-1+b1
ii  libavformat58        7:4.2.2-1+b1
ii  libavutil56          7:4.2.2-1+b1
ii  libc6                2.30-2
ii  libcurl3-gnutls      7.68.0-1
ii  libgcc-s1 [libgcc1]  10-20200312-2
ii  libgcc1              1:10-20200312-2
ii  libluajit-5.1-2      2.1.0~beta3+dfsg-5.1
ii  libobs0              24.0.6+dfsg1-1
ii  libpython3.7         3.7.7-1
ii  libqt5core5a         5.12.5+dfsg-9
ii  libqt5gui5           5.12.5+dfsg-9
ii  libqt5svg5           5.12.5-2
ii  libqt5widgets5       5.12.5+dfsg-9
ii  libqt5x11extras5     5.12.5-1
ii  libstdc++6           10-20200312-2
ii  obs-plugins          24.0.6+dfsg1-1
ii  python3              3.7.5-3
ii  python3.7            3.7.7-1

obs-studio recommends no packages.

obs-studio suggests no packages.

-- no debconf information
</pre>
</details>

**Comment by kkartaltepe** [comment]
Cannot replicate, likely due to outdated drivers or qt on debian.

**Comment by gwillegers** [comment]
Since I am having the same problem with OBS Studio on Linux Mint 20 and a Wacom Intuos 4, I searched and found this thread on the [OBS forum](https://obsproject.com/forum/threads/mouse-offset-on-obs-window.109957/). The thread contains a workaround, and points to another thread on the [ArchLinux forum](https://bbs.archlinux.org/viewtopic.php?id=248540), which in turn points to this [Qt bugreport](https://bugreports.qt.io/browse/QTBUG-77826).
