### ISSUE TITLE
[BUG] pthread handle leaks

### ISSUE THREAD

**Issue by sorayuki** [obsproject/obs-studio#2599]
## Platform

Operating system and version: Windows 10 1903 (18362.720)
OBS Studio version: OBS-Studio 25.0.3 32-bit

## Expected Behavior

Less Thread Handle kept not released.

## Current Behavior

Lots of Thread Handle are not released when end of `main` function reached.

## Steps to Reproduce

1. Build OBS-Studio
2. Set breakpoint at `return` statement of `main` function, and run OBS with debugger attched.
3. To make it more evident, start / stop streaming for 10 or 20 times.
4. Close OBS main Window, and breakpoint is triggered.
5. Use ProcessExplorer tool to see Handles (Ctrl+H) hold by obs32.exe, sorting by `Type`.

## Additional information

How I trace it:
1. use my branch with modified w32-pthreads: `https://github.com/sorayuki/obs-studio/tree/bugfix/pthread-trace`
2. Set breakpoint at `return` statement of `main` function and debug OBS in VisualStudio.
3. start / stop streaming for several times.
4. Close OBS
5. Use ProcessExplorer to see Thread Handles.
6. Switch `output` window in VisualStudio to `debug`, and search for Thread Handle id, and copy the caller address
7. Open `disassembly` window, and paste the address then press enter
8. right click the assembly instruction, select `go to source`
9. It's the place where not released thread was created.

Almost from something like `connect_thread`, `send_thread`, `end_data_capture_thread` which is not joined or detached.

**Comment by Fenrirthviti** [comment]
Closing as stale. If this is still an issue please open with updated reproduction steps on the latest version of OBS.
