### ISSUE TITLE
[BUG] <bug description>obs studio is not compatible with BE anticheat system 

### ISSUE THREAD

**Issue by MrFutureV** [obsproject/obs-studio#2601]
## Platform

Operating system and version:
OBS Studio version:

## Steps to Reproduce

1.
2.
3.
4.

**Comment by WizardCM** [comment]
BattlEye has already been updated with the OBS 25's Game Capture signature. It is up to each game to update their own copies of BattlEye.

In future, Github issues are **only** for bugs and crashes that are reproducible with steps. Use Discord or the forums for support queries.
