### ISSUE TITLE
[BUG] Mouse cursor is captured at the wrong size, for non-default cursor sizes

### ISSUE THREAD

**Issue by chris-morgan** [obsproject/obs-studio#2604]
## Platform
Operating system and version: Windows 10 (20H1; version 2004, build 19041.172)
OBS Studio version: 25.0.1 (64-bit, windows)
Hardware: Surface Book, high-DPI screen (2× scaling factor, potentially relevant here).

## Expected Behavior
OBS Studio should capture the mouse cursor with the same size and appearance as it has on screen.

(Sorry, no screenshot, because Windows doesn’t capture the cursor in screenshots, and ShareX which does suffers from [much the same bug](https://github.com/ShareX/ShareX/issues/4378), and I’m too lazy right now to synthesise equivalent screenshots.)

## Current Behavior
My mouse cursor is captured in the correct colour, but not at the correct size.

At sizes 1–7, OBS Studio draws the cursor at size 1.

At sizes 8–15, OBS Studio draws the cursor at the true size, then at size 1 on top of that.

## Steps to Reproduce
1. Be using at least the major version of Windows 10 from the second half of 2019, when this new cursor sizing and colouring interface was added. (It may have existed previously, I don’t know; but the interface for it is fairly new.)
2. In Windows’ Settings app, Ease of Access → Mouse pointer → Change pointer size, increase it from 1 to some other value. The largest value, 15, will make it super-obvious, because your mouse pointer will now be 150 pixels tall, which is arguably excessive.
3. In OBS Studio, Add → Display Capture, and in its properties, tick Capture Cursor.
4. Twiddle the pointer size slider in the Settings app, and watch how it appears in OBS Studio.

## Additional Information
Related issues for which I shan’t file bugs:
- switching pointer *colour* (white, black, inverted, any coloured) doesn’t seem to take effect until you restart OBS Studio, or maybe something else can trigger it because I don’t *think* I restarted OBS but a couple of times when I came back a few minutes later it was the right colour? (Not filing because it’s such a niche thing, but maybe it’ll get fixed as part of this?)
- The size 1 inverted cursor is just black, not inverted. The size 8+ cursor *is* inverted properly. (Not filing because I suspect it may be fixed as part of this—it looks like there are two code paths, one right and one wrong, if the wrong is dropped then it all pans out—and I don’t use an inverted cursor myself anyway.)

The bug I am reporting here was previously reported in #2258, but rapidly closed because it was improperly filed.

**Comment by UserNaem** [comment]
OBS doesn't really "capture" the mouse pointer, it just draws one exactly where the real one would be. And it doesn't respect your mouse pointer scaling settings.
You can work around this by using a custom mouse pointer in the size you want.

**Comment by chris-morgan** [comment]
Yeah, it draws one, but it draws it *incorrectly*. That’s the bug. Also note how I report that for size 8 and beyond it draws the cursor both correctly *and* incorrectly.

**Comment by WizardCM** [comment]
OK, I did some extensive testing on this today. Here's what I figured out.

* When you see double cursors (in Display Capture), one is being rendered in the Duplicator API's texture directly (ie. Software Cursor), and the second one is being rendered by our cursor helpers.
* Window Capture uses its own cursor rendering functions, rather than our cursor helpers
* Every time you see a cursor that is the wrong size, it's our code. Whenever you see a cursor that is the correct size, that's Microsoft's code (specifically, a software cursor)

As described by @VodBox (who helped me debug this):
> When using the Desktop Duplication API (which we do on Win 8+), the texture we receive will already include a cursor whenever a software cursor is being used by Windows. The correct procedure we're supposed to follow is to check from the data returned by AcquireNextFrame whether a hardware cursor is visible, and therefore whether we should draw it ourselves, and also whether the pointer shape has changed. In order to get the right pointer shape to draw, we're supposed to call GetFramePointerShape to retrieve the shape as pixel data.
> 
> Currently in OBS, when capture cursor is enabled, Display Capture will draw the cursor on every frame. It'll also use old Win32 APIs (GetCursorInfo, GetIconInfo, GetObject, GetBitmapBits) for getting information about the cursor to draw. These functions on Windows 10 seem to not reflect the true size of any cursor.

I don't think the APIs we currently use in the helper functions (starting with [GetCursorInfo](https://github.com/obsproject/obs-studio/blob/a4535915fe21b8c6b25186a872f0d8537f55481d/plugins/win-capture/cursor-capture.c#L193)) have the ability to give us correctly-sized textures. My guess is that as it's a legacy API (Windows 2000-era), it will always recieve a 32x32 icon for compatibility reasons, and getting more modern cursors should be done with newer APIs (ie [GetFramePointerShape](https://docs.microsoft.com/en-us/windows/win32/api/dxgi1_2/nf-dxgi1_2-idxgioutputduplication-getframepointershape), Windows 8+).

**Comment by chllcy** [comment]
hi @WizardCM the gdi draw cursor is slow,will obs support the new api

**Comment by WizardCM** [comment]
@chllcy As this is relatively low priority and I don't have the skill, nobody is currently looking into this further.

**Comment by EposVox** [comment]
I am running into this as well, with my cursor being tiny in the capture - very frustrating.

**Comment by rafaltrzop** [comment]
I have found a workaround for this problem on OBS forums:
https://obsproject.com/forum/threads/mouse-cursor-doesnt-change-to-contrast-background.74839/#post-321835

Workaround for Windows platform:
1. In OBS, inside the Sources panel, right-click your Display Capture and select Properties. Inside the Properties window turn off Capture Cursor checkbox and click OK.
2. Open Windows Magnifier program (Windows key + "+" key) and zoom out to 100% (Windows key + "-" key).
3. Leave Windows Magnifier program open in the background and record a video with OBS - now your cursor should be recorded correctly.

**Comment by SamGG** [comment]
I faced the same problem with OBS 26.1.1 64bits Win10.
I **solved** it by changing the cursor size and shape in the "old" mouse settings panel. I chose a large cursor but I could also add a cursor with a yellow halo (there are many on internet). And it works: OBS is using this cursor during the recording. I guess OBS refers to this cursor setting but not to the scaling proposed in the mouse panel of Windows 10. To **access the old mouse settings**, click on the Windows icon in the task bar, and then type **`main.cpl`** and go to **cursors**. I think that is what @UserNaem was meaning.
@EposVox @chris-morgan this really does the job and your frustration will disappear as mine.
@WizardCM My thanks to the devel team: continue providing this incredible piece of software called OBS.

**Comment by RytoEX** [comment]
Confirmed that this only occurs when using DXGI Display Capture (Display Duplicator API). This does not happen when using the WGC Display Capture (Windows 10 1903+) and OBS Studio 25+, which we now recommend in nearly all cases.

**Comment by eobet** [comment]
It's 2023 and all I see in the capture selection in OBS is this:

![image](https://github.com/obsproject/obs-studio/assets/3254196/b33384aa-c445-4ecd-8923-1d3b9ae4d1a1)

OBS 29.13 was set to automatic (and I'm using a Geforce 3090). Why is it defaulting to a non recommended capturing method if what @RytoEX said still applies?

**Comment by RytoEX** [comment]
I said that we recommend "Windows 10 (1903 and up)" "in nearly all cases". If using it causes a problem for you and your setup, and the other one does not, then we don't recommend it. In nearly all other cases (default cursor size), it works just fine and in some cases does not suffer from issues that "DXGI Desktop Duplication" does (like not working on laptops).
