### ISSUE TITLE
Desktop audio is disabled on MacOS

### ISSUE THREAD

**Issue by veresistvan95** [obsproject/obs-studio#2606]
Hi!
I'm using mac os 10.15.3 and I found some issues.
First: When I try to record my desktop audio. Preferences » Audio » Devices » Desktop audio is disabled.
I know, when I use some third-party apps than its works. But I want to tell you.

**Comment by Fenrirthviti** [comment]
Apple provides no capture options for desktop audio. A third party program is required.

See: https://obsproject.com/forum/resources/505/

In the future, please make sure you read the issue template rather than deleting it, and you would see that support issues should not be posted here.
