### ISSUE TITLE
[BUG] Streaming Stopped from unknown reason

### ISSUE THREAD

**Issue by DemonRem** [obsproject/obs-studio#2607]
## Platform

Operating system and version: Windows 10
OBS Studio version: 23 

## Expected Behavior
well long time I didn't update it and I don't know if its related the bug , howerver while I streaming my game to facebook after like 5 - 10 the streaming stopped , and where the green light the kb's stand on 0.0kb only and not moving

## Current Behavior
the software after a while when facebook streaming suddenly drop to 0,0kb and streaming is over by himself

## Steps to Reproduce
cant send a link because its automatically deleted by facebook

## Additional information
I don't know how is happened bit its like 5 times its happened from unknown reason

**Comment by notr1ch** [comment]
Please use the forums or Discord for support.
