### ISSUE TITLE
[BUG] Icon to show additional help/info sometimes does not load

### ISSUE THREAD

**Issue by Xaymar** [obsproject/obs-studio#2610]
In >50% of launches the icon for additional help in properties does not load or is completely replaced by a 0x0 image, resulting in the UI either showing a "New File" symbol, or nothing at all. In very rare cases a corrupt mess of pixels can also be observed where the icon should be.

## Platform
Operating system and version: Windows 10 1909 
OBS Studio version: 25.0.1 64-bit Windows Full

## Expected Behavior
The icon/image should always load.

## Current Behavior
The icon/image does not load at all times.

## Steps to Reproduce
1. Launch OBS Studio
2. Open any Source, Filter, Transition or Encoder settings
3. Check if the icon loaded.

## Additional information
Happens in any theme, and both admin and normal runs of obs have the same behavior.

**Comment by notr1ch** [comment]
Could you take a screenshot of the icon you're referring to? As far as I'm aware we've never had a help icon in the properties window.

**Comment by Xaymar** [comment]
![https://cdn.xaymar.com/private/2020-04-02/2020-04-02T17-02-59_obs64_WeepyRipeDore.png](https://cdn.xaymar.com/private/2020-04-02/2020-04-02T17-02-59_obs64_WeepyRipeDore.png)

The icon after "Source" was added with 25.0.x and randomly fails to load. It is not from my plugin.

**Comment by WizardCM** [comment]
I am unable to reproduce this issue. The icon is fetched from Qt's resources, so I'm unsure what could cause it to fail.

Source: https://github.com/obsproject/obs-studio/commit/51948ebc8763c468c5e4b8a91d208fb4ff1e4192#diff-283f8e5d2ac8d0ded1674f1da3cf0434R1444-R1447

When you say "50% of launches", do you mean launches of the window that contains the property (eg. Media Source Properties), or of OBS itself?

**Comment by Xaymar** [comment]
As far as I can tell, it's launches of OBS Studio itself. Sometimes the icon will be the "New File" icon, at other times it will be empty, and at very rare times its a mess of pixels. I'm not entirely sure how this can even happen, as other things should also be broken. Screenshot below is of this happening in the current 25.0.1 Windows release:

![https://cdn.xaymar.com/private/2020-04-04/2020-04-04T13-01-59_obs64_DopeyTraumaticBeagle.png](https://cdn.xaymar.com/private/2020-04-04/2020-04-04T13-01-59_obs64_DopeyTraumaticBeagle.png)

I also had this happen live on stream where it was replaced by a new page, but it's unfortunately already older than Twitch archives streams for. At the time I thought that it was intentional as I never had anything different than a new page icon.

**Comment by WizardCM** [comment]
Hmm. And during the launches where it isn't working properly, the same (lack of) icon appears in all locations? Media Source properties, NVENC settings, etc? Mess of pixels possibly sounds like memory corruption? Antivirus? Not sure, I agree that if there was an issue it would manifest in more places, especially as it's just one of many resources loaded by OBS during startup. I'll experiment more on my side I guess.

**Comment by notr1ch** [comment]
I've been keeping an eye out for this each time I launch a new build and also haven't been able to reproduce it yet. Seems like it might be GPU dependent or something.

**Comment by Xaymar** [comment]
> And during the launches where it isn't working properly, the same (lack of) icon appears in all locations?

It appears everywhere where this icon is supposed to show up. Which as far as I can tell is only in the properties of things.

> Seems like it might be GPU dependent or something.

That is a possibility I had though of. I'm using a RTX 2080 Ti combined with Ryzen 3950X, and my Windows (and OBS Studio) is installed on a NVMe. All of these together shouldn't actually have issues loading this icon, but for some reason do.

**Comment by Xaymar** [comment]
I haven't been able to reproduce this with more recent versions of Qt. Seems to only happen when I downgrade to Qt 5.10.x. Closing as this seems to be an upstream Qt issue instead.
