### ISSUE TITLE
Syphone Client - Launch SyphonInject disabled 

### ISSUE THREAD

**Issue by lorinchever** [obsproject/obs-studio#2613]
macOS 10.14.6
OBS 24.0.6

$ csrutil status
System Integrity Protection status: disabled.

Syphone Client the Launch SyphonInject button is  disabled 

I get the following 3 error messages every time when I try to add a new Syphone Client

error: obs-data.c: [obs_data_create_from_json] Failed reading json string (1): '[' or '{' expected near end of file
error: obs-data.c: [obs_data_create_from_json] Failed reading json string (1): '[' or '{' expected near end of file
error: obs-data.c: [obs_data_create_from_json] Failed reading json string (1): '[' or '{' expected near end of file

**Comment by tielqt** [comment]
Github is not for support. Please use Discord or the forums for this.

Additionally, SyphonInject no longer functions as of MacOS 10.14 (Mojave) and will not be supported in any future versions of MacOS.
