### ISSUE TITLE
There is a problem with the camera display on version 25.0.3

### ISSUE THREAD

**Issue by hschenzhimin** [obsproject/obs-studio#2616]
There is a problem with the camera display on version 25.0.3
![1](https://user-images.githubusercontent.com/7993948/78223767-04d5fc00-74fa-11ea-9a9d-5e03f5b2f74c.png)

**Comment by WizardCM** [comment]
When filling out a bug report, following the template is crucial.

In future, Github issues are **only** for bugs and crashes that are reproducible with steps. Use Discord or the forums for support queries.
