### ISSUE TITLE
[BUG] 'readlink' fails without reporting an error code

### ISSUE THREAD

**Issue by yurivict** [obsproject/obs-studio#2622]
This call failed on FreeBSD: https://github.com/obsproject/obs-studio/blob/master/libobs/util/platform-nix.c#L278 and obs-studio just accepted "-1" as "count", and just returned "NULL" to  https://github.com/obsproject/obs-studio/blob/master/plugins/obs-ffmpeg/obs-ffmpeg-mux.c#L235 where NULL was just processed in a bogus way.

Please, ***always*** immediately check return codes of all system calls for errors, report the errors to the user using ```strerror(errno)```, and terminate the application after the error message.

The original bug report from the user: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=245299

**Comment by WizardCM** [comment]
Please fill in the [issue template](https://raw.githubusercontent.com/obsproject/.github/master/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by Fenrirthviti** [comment]
Please do not delete our issue template. It should be properly filled out.

**Comment by yurivict** [comment]
## Platform
Operating system and version: FreeBSD 12

OBS Studio version: 25.0.1

## Expected Behavior
Failed to save the video to disk

## Current Behavior
Save the video to disk.

## Steps to Reproduce
See https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=245299#c0

**Comment by yurivict** [comment]
There are 2 problems:
1. It continues despite the error message. Once this error has occurred, the application should be terminated.
2. The linux part doesn't check for the error.
