### ISSUE TITLE
[BUG] Doesn't install obs-frontend-api.h

### ISSUE THREAD

**Issue by yurivict** [obsproject/obs-studio#2625]
summary of the issue in the Title above -->

## Platform
Operating system and version: FreeBSD 12
OBS Studio version: 25.0.1

## Expected Behavior
Install obs-frontend-api.h

## Current Behavior
Doesn't install obs-frontend-api.h for users to be able to use lib/libobs-frontend-api.so

## Steps to Reproduce
Try to compile obs-websocket with obs-studio installed from a package, and it would fail with a missing header.

**Comment by kkartaltepe** [comment]
Are you sure this is the only missing header? I think we have had mutliple missing public headers at some point but have not had the time to look into them.

**Comment by yurivict** [comment]
This particular header is the only missing header needed in order to build ```obs-websocket```.

Otherwise - I don't know.

**Comment by MarioMey** [comment]
I'm running the same problem by compiling obs-websocket with obs-studio 25.0.7-198-g8ec1edb6, compiled here. Sorry if I don't completly understand, but this issue is supposedly closed, but issue is still here. At least, in my computer.

```
mario@debian:~/src/obs-websocket/build$ sudo make install
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mario/src/obs-websocket/build
[  3%] Automatic MOC and UIC for target obs-websocket
[  3%] Built target obs-websocket_autogen
Scanning dependencies of target obs-websocket
[  7%] Building CXX object CMakeFiles/obs-websocket.dir/src/obs-websocket.cpp.o
/home/mario/src/obs-websocket/src/obs-websocket.cpp:20:10: fatal error: obs-frontend-api.h: No existe el fichero o el directorio
 #include <obs-frontend-api.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/obs-websocket.dir/build.make:63: CMakeFiles/obs-websocket.dir/src/obs-websocket.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/obs-websocket.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

I checked this PR #2650 and, in my code, it's merged.

I would like to compile websocket because there's a feature that it supposedly to be in 4.8 and it is not working (GetAudioMonitoringType).
