### ISSUE TITLE
[BUG]  error: non-void function 'add_control_property' should return a value [-Wreturn-type]

### ISSUE THREAD

**Issue by yurivict** [obsproject/obs-studio#2628]
Operating system and version: FreeBSD 12
OBS Studio version: 25.0.3
Compiler: clang-8

## Expected Behavior
Compilation succeeds.

## Current Behavior
```
/usr/ports/multimedia/obs-studio/work/obs-studio-25.0.3/plugins/linux-v4l2/v4l2-controls.c:105:3: error: non-void function 'add_control_property' should return a value [-Wreturn-type]
                return;
                ^
```

## Steps to Reproduce
Regular compilation.

**Comment by yurivict** [comment]
Same in the latest revision c899d164

None of the versions I tried works in a stable manner.
25.0.1 crashes on changing of a microphone.
25.0.3 and later revisions fail to compile.

**Comment by notr1ch** [comment]
Fixed in https://github.com/obsproject/obs-studio/pull/2573
