### ISSUE TITLE
[BUG] No apparent way to change audio backends

### ISSUE THREAD

**Issue by yurivict** [obsproject/obs-studio#2631]
## Platform
Operating system and version: FreeBSD 12
OBS Studio version: 25.0.3

## Expected Behavior
In Settings/Audio/Devices have a combobox that would allow to choose what audio backend to use (Jack/PulseAudio/...).

Both ```linux-jack.so``` and ```linux-pulseaudio.so``` are installed, however only PulseAudio is used and there is no apparent way to switch to Jack.

## Current Behavior
PulseAudio is used by default.

**Comment by tielqt** [comment]
Unfortunately FreeBSD is not a supported platform for OBS. While OBS may run, we aren't able to look into issues like this as none of our core development team uses FreeBSD. That said, if there are platform specific issues that can be fixed without touching other code, we'd be open to merging a PR.

**Comment by yurivict** [comment]
This issue has nothing to do with FreeBSD.

**Comment by Fenrirthviti** [comment]
This is not a FreeBSD specific issue, but is not technically a bug either. I'm going to leave it open, but feature requests/enhancements should really be submitted to our Ideas page or as an RFC.

**Comment by yurivict** [comment]
```cmake``` detects both Jack and PulseAudio, builds both plugins, but leaves no apparent way to choose which one to use. This is a usability issue. System should have a way to choose Audio backend, otherwise why build both?

**Comment by VbNetMatrix** [comment]
>  but feature requests/enhancements should really be submitted to our Ideas page or as an RFC.
Where is the IDEAS page ?  I would like to write one.

**Comment by kkartaltepe** [comment]
Only Alsa and PulseAudio are supported audio backends and we only support building with a single backend.

Jack Alsa and PulseAudio can be used as sources via the plugins you mention.

**Comment by Fenrirthviti** [comment]
Closing per the above comment, as we only support building with a single audio backend at this time. The input sources for capturing other audio systems are separate. If you would like to see this changed, please [submit an RFC](https://github.com/obsproject/rfcs) for the change.
