### ISSUE TITLE
[BUG] Mouse cursor surrounded by black box when using Blur filter (With Display Capture)

### ISSUE THREAD

**Issue by NotBlod** [obsproject/obs-studio#2632]
## Platform
Operating system and version: Windows 10 1903 (Build 18362)
OBS Studio version: 25.0.1 (64 bit)

## Expected Behavior
Mouse cursor shouldn't have a black box around it

## Current Behavior
The mouse cursor has a black box around it when the "blur" filter is used no matter the level of blur or type of blur used

## Steps to Reproduce
https://i.imgur.com/riaRdmn.mp4
1. Create a Display Capture source
2. Add the Blur filter with any type or level of blur

**Comment by Fenrirthviti** [comment]
This filter is provided by a third party plugin, you will need to contact them for more assistance.

**Comment by NotBlod** [comment]
oh yeh my bad <3
