### ISSUE TITLE
[BUG] Failure on starting a recording with NVENC encoder

### ISSUE THREAD

**Issue by matheuscandido** [obsproject/obs-studio#2636]
## Platform

Operating system and version: Xubuntu 20.04
OBS Studio version: 25.0.3+dfsg1-2

## Expected Behavior

When one configures the recording encoder to NVENC on a compatible machine, it records.

## Current Behavior
I have the latest Nvidia drivers up and running, Hardware (NVENC) as my Encoder selected and when I press Start Recording a dialog with the following text shows up:

"Starting the output failed. Please check the log for details.
Note: If you are using the NVENC or AMD encoders, make sure your video drivers are up to date."

And the log is:
```
23:26:57.781: CPU Name: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
23:26:57.781: CPU Speed: 3491.143MHz
23:26:57.782: Physical Cores: 4, Logical Cores: 8
23:26:57.782: Physical Memory: 15696MB Total, 13545MB Free
23:26:57.782: Kernel Version: Linux 5.4.0-21-generic
23:26:57.782: Distribution: "Ubuntu" "20.04"
23:26:57.782: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.7
23:26:57.783: Portable mode: false
23:26:57.814: OBS 25.0.3+dfsg1-2 (linux)
23:26:57.814: ---------------------------------
23:26:57.814: ---------------------------------
23:26:57.814: audio settings reset:
23:26:57.814: 	samples per sec: 44100
23:26:57.814: 	speakers:        2
23:26:57.819: ---------------------------------
23:26:57.819: Initializing OpenGL...
23:26:57.896: Loading up OpenGL on adapter NVIDIA Corporation GeForce MX130/PCIe/SSE2
23:26:57.896: OpenGL loaded successfully, version 3.3.0 NVIDIA 440.64, shading language 3.30 NVIDIA via Cg compiler
23:26:57.903: ---------------------------------
23:26:57.903: video settings reset:
23:26:57.903: 	base resolution:   1920x1080
23:26:57.903: 	output resolution: 1920x1080
23:26:57.903: 	downscale filter:  Bicubic
23:26:57.903: 	fps:               60/1
23:26:57.903: 	format:            NV12
23:26:57.903: 	YUV mode:          601/Partial
23:26:57.903: NV12 texture support not available
23:26:57.904: Audio monitoring device:
23:26:57.904: 	name: Default
23:26:57.904: 	id: default
23:26:57.904: ---------------------------------
23:26:57.905: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
23:26:57.929: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
23:26:57.929: No blackmagic support
23:26:57.943: NVENC supported
23:26:57.943: FFMPEG VAAPI supported
23:26:57.949: VLC found, VLC video source enabled
23:26:57.949: ---------------------------------
23:26:57.949:   Loaded Modules:
23:26:57.949:     vlc-video.so
23:26:57.949:     text-freetype2.so
23:26:57.949:     rtmp-services.so
23:26:57.949:     obs-x264.so
23:26:57.949:     obs-transitions.so
23:26:57.949:     obs-outputs.so
23:26:57.949:     obs-filters.so
23:26:57.950:     obs-ffmpeg.so
23:26:57.950:     linux-v4l2.so
23:26:57.950:     linux-pulseaudio.so
23:26:57.950:     linux-jack.so
23:26:57.950:     linux-decklink.so
23:26:57.950:     linux-capture.so
23:26:57.950:     linux-alsa.so
23:26:57.950:     image-source.so
23:26:57.950:     frontend-tools.so
23:26:57.950:     decklink-ouput-ui.so
23:26:57.950: ---------------------------------
23:26:57.950: ==== Startup complete ===============================================
23:26:57.950: Service '' not found
23:26:57.951: All scene data cleared
23:26:57.951: ------------------------------------------------
23:26:57.953: pulse-input: Server name: 'pulseaudio 13.99.1'
23:26:57.953: pulse-input: Audio format: s16le, 48000 Hz, 2 channels
23:26:57.953: pulse-input: Started recording from 'alsa_output.pci-0000_00_1f.3.analog-stereo.monitor'
23:26:58.023: pulse-input: Server name: 'pulseaudio 13.99.1'
23:26:58.023: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
23:26:58.023: pulse-input: Started recording from 'alsa_input.pci-0000_00_1f.3.analog-stereo'
23:26:58.026: xshm-input: Geometry 1920x1080 @ 1920,0
23:26:58.028: Switched to scene 'Scene'
23:26:58.028: ------------------------------------------------
23:26:58.029: Loaded scenes:
23:26:58.029: - scene 'Scene':
23:26:58.029:     - source: 'Screen Capture (XSHM)' (xshm_input)
23:26:58.029: ------------------------------------------------
23:26:58.600: adding 46 milliseconds of audio buffering, total audio buffering is now 46 milliseconds (source: Mic/Aux)
23:26:58.600: 
23:27:00.591: ---------------------------------
23:27:00.591: [NVENC encoder: 'simple_h264_recording'] settings:
23:27:00.591: 	rate_control: CQP
23:27:00.591: 	bitrate:      0
23:27:00.591: 	cqp:          16
23:27:00.591: 	keyint:       250
23:27:00.591: 	preset:       hq
23:27:00.591: 	profile:      high
23:27:00.591: 	width:        1920
23:27:00.591: 	height:       1080
23:27:00.591: 	2-pass:       false
23:27:00.591: 	b-frames:     2
23:27:00.591: 	GPU:          0
23:27:00.591: 
23:27:00.842: [NVENC encoder: 'simple_h264_recording'] Failed to open NVENC codec: Generic error in an external library
```

## Steps to Reproduce

1. On a fresh Ubuntu 20.04 LTS-based install with Nvidia graphics cards and the latest 440.64 graphics drivers, open OBS Studio and select Hardware (NVENC) as the recording encoder.
2. Start recording

## Additional information
I can record easily with NVENC on Windows at the same computer, so I guess it's not a hardware problem.

**Comment by Fenrirthviti** [comment]
You will need to recompile FFmpeg for NVENC support, as we use the system-provided FFmpeg on Linux.

**Comment by coder3101** [comment]
I also have the exact same issue. Did you managed to fix it? I know using software encoding can be a work around but anyone would prefer to use NVENC if they have GPU

I am using arch linux and my official `fffmpeg -codecs` reports that it was compiled with `--enable-nvenc`.

**Comment by motekulo** [comment]
Same problem - pop-os (20.04 LTS), latest nvidia drivers, ffmpeg shows nvenc compiled

**Comment by brianmsm** [comment]
I have the same issue

**Comment by rahbal** [comment]
> Same problem - pop-os (20.04 LTS), latest nvidia drivers, ffmpeg shows nvenc compiled

Exactly Same operating system. Latest nvidia drivers, ffmpeg

`
ffmpeg version 4.2.4-1ubuntu0.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)
  configuration: --prefix=/usr --extra-version=1ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Hyper fast Audio and Video encoder

`

**Comment by agl77** [comment]
Click "Settings" then select "Output". Change "Encoding" to "Software" under "Streaming" and "Recording."

**Comment by Mertzenich** [comment]
Same issue here, I have full ffmpeg.

**Comment by qptain-Nemo** [comment]
Very similar intermittent issues here. Previously recording with NVENC kind of only failed when there was not enough free VRAM, but after updating the kernel and drivers (to 5.9.1-arch1-1, 455.28) it just doesn't work at all for no apparent reason. ffmpeg does have nvenc compiled in.

**Comment by occam25** [comment]
Same issue here. It works fine for a while but, sometimes, after finishing a recording and editing it (with shotcut) next recording attempt fails (even after closing shotcut). After rebooting it works again. I'm using (K)Ubuntu 20.04.1

**Comment by razcore-art** [comment]
Why was this issue closed? There seem to be a lot of people having this problem. I also got this issue on Ubuntu 20.10 with `ffmpeg` compiled with nvenc:

```
❯ ffmpeg -codecs
ffmpeg version 4.3.1-4ubuntu1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 10 (Ubuntu 10.2.0-9ubuntu2)
  configuration: --prefix=/usr --extra-version=4ubuntu1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
# ...
 DEV.LS h264                 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (decoders: h264 h264_v4l2m2m h264_qsv h264_cuvid ) (encoders: libx264 libx264rgb h264_nvenc h264_omx h264_qsv h264_v4l2m2m h264_vaapi nvenc nvenc_h264 )
 DEV.L. hevc                 H.265 / HEVC (High Efficiency Video Coding) (decoders: hevc hevc_qsv hevc_v4l2m2m hevc_cuvid ) (encoders: libx265 nvenc_hevc hevc_nvenc hevc_qsv hevc_v4l2m2m hev
```

**Comment by HeatSeaker** [comment]
> Why was this issue closed? There seem to be a lot of people having this problem. I also got this issue on Ubuntu 20.10 with `ffmpeg` compiled with nvenc:
> 
> ```
> ❯ ffmpeg -codecs
> ffmpeg version 4.3.1-4ubuntu1 Copyright (c) 2000-2020 the FFmpeg developers
>   built with gcc 10 (Ubuntu 10.2.0-9ubuntu2)
>   configuration: --prefix=/usr --extra-version=4ubuntu1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
> # ...
>  DEV.LS h264                 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (decoders: h264 h264_v4l2m2m h264_qsv h264_cuvid ) (encoders: libx264 libx264rgb h264_nvenc h264_omx h264_qsv h264_v4l2m2m h264_vaapi nvenc nvenc_h264 )
>  DEV.L. hevc                 H.265 / HEVC (High Efficiency Video Coding) (decoders: hevc hevc_qsv hevc_v4l2m2m hevc_cuvid ) (encoders: libx265 nvenc_hevc hevc_nvenc hevc_qsv hevc_v4l2m2m hev
> ```
> 
> Nevermind, I answered my own question:
> 
> ```
> [h264_nvenc @ 0x55557a0147c0] Driver does not support the required nvenc API version. Required: 9.1 Found: 9.0
> [h264_nvenc @ 0x55557a0147c0] The minimum required Nvidia driver for nvenc is 435.21 or newer
> warning: [NVENC encoder: 'simple_h264_recording'] Failed to open NVENC codec: Function not implemented
> ```
> 
> This should be stated somewhere in the error given by OBS cause that one is just a useless generic error.

Did you find a solution? (I've just started using linux, so idk my way around that much, I will try looking it up myself, if I find the solution, I'll update this comment)
