### ISSUE TITLE
[BUG] AutoHotkey app with multiple views is not captured correctly after restart

### ISSUE THREAD

**Issue by DavidTamas** [obsproject/obs-studio#2643]
## Platform

Operating system and version: Windows 10 Home, version 1903, 64bit
OBS Studio version: 25.0.1 (64 bit)

## Expected Behavior

After restarting Lighnat0r's 100% Checklist for GTA, window capture should always show the application's current window.
## Current Behavior

When we restart Lighnat0r's 100% Checklist for GTA, window capture will show a black box instead of the application's current window. Issue is temporarily fixed (until the next restart) by changing any setting in the source properties, even if the change is not saved.
## Steps to Reproduce

1. Download Lighnat0r's 100% Checklist for GTA from https://github.com/Lighnat0r/100pc_checklist/raw/master/Released%20Versions%20Zipped/100%25%20Checklist%201.58.zip
2. Launch the exe, select any game, click the Confirm button.
3. Set up a window capture for the checklist.
4. Restart the checklist, select any game, click the Confirm button.
![checklist](https://user-images.githubusercontent.com/22328803/78460137-b1f97180-76be-11ea-9744-466159cb8b45.png)
Left: after setting up window capture. Right: after restarting the checklist and confirming game selection.

**Comment by Fenrirthviti** [comment]
Please include a log from OBS when then capture fails so we can check for any errors.

**Comment by Fenrirthviti** [comment]
Replicated, but this doesn't appear to be a bug with OBS. The window is destroyed and recreated, so you need to refresh the window capture before capture will work again. Not sure there's much we can do about it.

**Comment by DavidTamas** [comment]
No related event can be found in the log file.

**Comment by Fenrirthviti** [comment]
Example of what happens: ![example](https://pub.rachni.com/img/obs64_2020-04-04_15-12-37.png)

It still "captures" the original window but if I refresh the source it works properly.

**Comment by Fenrirthviti** [comment]
Going to close this as there's not really anything we can do, the program is destroying the captured window.
