### ISSUE TITLE
[BUG] Doesn't install ObsHelpers.cmake so external plugins can't use install_obs_plugin_with_data

### ISSUE THREAD

**Issue by yurivict** [obsproject/obs-studio#2647]
## Platform
Operating system and version: FreeBSD (but this is not a FreeBSD issue)
OBS Studio version: 25.0.3

## Expected Behavior
Install ```ObsHelpers.cmake```

## Current Behavior
```install_obs_plugin_with_data``` isn't available for uses like this: https://github.com/univrsal/spectralizer/blob/master/CMakeLists.txt#L41

## Steps to Reproduce
1. Install obs-studio
2. Try to build https://github.com/univrsal/spectralizer

**Comment by Xaymar** [comment]
[The functions do not seem to be aimed at external plugins, rather than that it is more for internal/bundled use.](https://github.com/obsproject/obs-studio/blob/master/cmake/Modules/ObsHelpers.cmake#L507)

**Comment by yurivict** [comment]
What is the expected behavior for https://github.com/univrsal/spectralizer/blob/master/CMakeLists.txt#L41 then?

**Comment by kkartaltepe** [comment]
Currently there are no helpers for building out of tree. Plugins that want to support out of tree builds should package themselves appropriately using the normal cmake packaging rules.

A partial example of supporting in tree and out of tree builds can be seen 
https://github.com/kkartaltepe/obs-text-pango/blob/master/CMakeLists.txt

**Comment by bedroomdeejay** [comment]
Hi,

Not sure if this is the right thread but I am running into some issues installing the spectralizer plugin, have posted my logs below.

https://obsproject.com/logs/wGqTXWiiv_n8Anz_

I've attempted to extract to many different file locations, no difference was achieved. I am running Windows 10 (64) and have a different root drive set to the one written into the shell script; changed it to where mine was but no solution found. 

Would appreciate any help from users who have managed to get it running on Windows 64. 

Thanks

**Comment by Fenrirthviti** [comment]
This issue has nothing to do with the spectralizer plugin, and you should not be asking for support on github in the first place. Use the forums or discord.
