### ISSUE TITLE
[BUG] No way to unregister output

### ISSUE THREAD

**Issue by yurivict** [obsproject/obs-studio#2661]
## Platform
Operating system and version: FreeBSD 12.1
OBS Studio version: 25.0.4

## Expected Behavior
Have ```obs_unregister_output()```.

## Current Behavior
Currently there is ```obs_register_output()``` but no ```obs_unregister_output()```. Maybe plugin would like to stop and deactivate at some point, and there is no easy way to do this cleanly.

## Additional information
Some entities do have ```unregister``` functions: ```obs_hotkey_unregister()```, ```obs_hotkey_pair_unregister()```, ```gs_unregister_loss_callbacks()```.

It would be consistent if everything that can be registered would also be able to be unregistered.

**Comment by WizardCM** [comment]
As far as I know, plugins are not currently designed to be dynamically unloaded, which is why something like output registration doesn't have the ability to unregister.

**Comment by kkartaltepe** [comment]
Hotkeys are meant to be configured at runtime. Outputs (and most other plugin functionality) is meant to be loaded once.

Unless you have a use case in mind  that requires unloading outputs this is working as intended.

**Comment by yurivict** [comment]
Ok, thanks.
