### ISSUE TITLE
[BUG] Missing mbedTLS support in Xenial PPA package

### ISSUE THREAD

**Issue by johnnya23** [obsproject/obs-studio#2664]
## Platform

Operating system and version: Distribution: "Linux Mint" "18.3"
OBS Studio version: OBS 24.0.3 (linux)

## Expected Behavior

Stream to facebook

## Current Behavior

Installed OBS Using:
sudo apt-get install ffmpeg
sudo add-apt-repository ppa:obsproject/obs-studio
sudo apt-get update
sudo apt-get install obs-studio
After inputting  the server and stream key values I hit "start steaming" and I see "Failed to connect to server"

https://obsproject.com/logs/Kdp_xYQSRtFW1xGS
## Steps to Reproduce

1. Fresh install (described above)
2. add server and key from facebook (apply)
3. hit "start stream".

## Additional information
tried to troubleshoot here:
https://obsproject.com/forum/threads/obs-studio-24-0-3-failed-to-connect-to-server-no-ssl-tls-support.118456/#post-445944

**Comment by dodgepong** [comment]
How did you install OBS? Did you build it yourself or did you use a package?

**Comment by dodgepong** [comment]
Also, please include an appropriate title for your bug report.

**Comment by pkviet** [comment]
you need mbedtls for rtmps which is required by Facebook

**Comment by johnnya23** [comment]
Installed OBS like this:
sudo apt-get install ffmpeg
sudo add-apt-repository ppa:obsproject/obs-studio
sudo apt-get update
sudo apt-get install obs-studio

@pkviet an you be very specific about how to add rtmps to mbedtls (NEWBIEEEEE)

**Comment by kkartaltepe** [comment]
Your obs is out of date. and your platform is based on ubuntu 16.04 which is not supported. Please upgrade your system and then upgrade OBS.

**Comment by Fenrirthviti** [comment]
We discussed and we are going to try and provide a build for 16.04 that might work with mbedtls. Leaving this open until testing is complete, but it's a good idea to update regardless if you do not want to wait.

**Comment by Gol-D-Ace** [comment]
An updated xenial build should now be available in the PPA. I tested Facebook streaming with it and it worked.
