### ISSUE TITLE
[BUG] OBS don't use NVDEC/CUVID

### ISSUE THREAD

**Issue by maxdrash** [obsproject/obs-studio#2674]
## Platform

Operating system and version: Linux Ubuntu Mate 18.04
OBS Studio version: 25.0.4

## Current Behavior

OBS should use hardware acceleration decoding on nvidia with media plugin or vlc plugin or blackmagic but not.
Nvidia Video Engine Utilization stay at 0% when hardware accelerated playback (if available) boxes are checked.
This cause lot of high cpu usage.

## Steps to Reproduce

1. Open OBS.
2. Play a video file with plugins (h264)
3. Note that no nvidia video engine utilization for decoding.

## Additional information

OBS uses NVENC for encoding and it's great but no NVDEC/CUVID/VDPAU for playing.
I have ffmpeg with h264_cuvid enabled.
VLC standalone uses VDPAU for playback, why not OBS ?
Can you tell me more about this trouble ?
Thanks.

**Comment by Fenrirthviti** [comment]
This is not really a bug, we just haven't implemented it. We use ffmpeg to decode for media source, and far fewer file formats support hw decode than you would expect. This should be submitted either on our [Ideas page](https://ideas.obsproject.com/) or as an [RFC](https://github.com/obsproject/rfcs).

**Comment by maxdrash** [comment]
Ok i was thinking that NVDEC is supported by OBS. Thank you.

**Comment by joeyjarosz** [comment]
By using ffmpeg to decode media sources, does that require (or cause) disabling vpx hardware acceleration in browser sources/docks? I'm on windows 10 desktop with a GTX 1050 which supports vp9, but vp9 does not show up in the list of supported hardware acceleration video codecs by inspecting chrome://gpu in OBS, but does in a regular chrome browser. As @maxdrash stated, the impact on cpu usage is pretty significant with video so maybe re open?

OBS browser:

![image](https://user-images.githubusercontent.com/28229454/79027173-dcc94700-7b50-11ea-84c2-980063dbecba.png)


Regular chrome: 

![image](https://user-images.githubusercontent.com/28229454/79026927-ee5e1f00-7b4f-11ea-82e4-3ae11f98348c.png)

**Comment by WizardCM** [comment]
@joeyjarosz the browser source is 100% unrelated to the media source, so it's not relevant to this ticket.

**Comment by joeyjarosz** [comment]
This ticket is %100 related to OBS not properly using hardware acceleration for video, the source is irrelevant IMO. So should I open a new issue here or in obs-browser?

**Comment by WizardCM** [comment]
Sources are completely isolated from each other and making one support something does not magically add the capability to another.

Yes, the best place to open a new ticket related to VPx decoding not working on the browser would be the obs-browser repo.

**Comment by maxdrash** [comment]
But, from 25.0.8 and Ubuntu 20.04, I have NVDEC acceleration on Linux.
I don't know why, maybe driver or library on nvidia side.
