### ISSUE TITLE
[BUG] Window Capture (Xcomposite) R/B swapped

### ISSUE THREAD

**Issue by emaste** [obsproject/obs-studio#2675]
## Platform

Operating system and version: FreeBSD 13-CURRENT
OBS Studio version: 921a74296613084b301e89459f0769f62fdb5517 + FreeBSD build fix PRs applied

## Expected Behavior
Window Capture (Xcomposite) faithfully reproduces colours from the source window

## Current Behavior
Red and blue are swapped. In the image below the Firefox window on the right is the source captured with Window Capture.
![colour](https://user-images.githubusercontent.com/1034582/78734129-6987c100-7915-11ea-86d0-2c5a483a87f5.png)

## Steps to Reproduce
1. Create a scene with 1 Window Capture (Xcomposite)
2. Use a Firefox window as the source with content 
3. Observe R and B swapped

## Additional information
Screen Capture (XSHM) does not show this issue

**Comment by kkartaltepe** [comment]
This is what the "Swap red and blue" option is for.

Im fine with leaving this bug open as a long standing issue.

**Comment by emaste** [comment]
D'oh, thanks for the clue. I almost included a screenshot of the Xcomposite properties window which would have included that checkbox and then I would have felt really silly.

I presume that this issue is not universal and that there's no obvious way to determine if the swapping is necessary.

**Comment by kkartaltepe** [comment]
Typically only intel hardware is in RGBA intead of BGRA format. We dont provide information on drivers so we cant make a very educated guess. GL doesnt offer internal format as part of the spec until 4.5 or so and we are supporting 3.3. Someone could try to load the KHR extension and use it if its available probably. And we currently rely on a hack to make texture imports as correct as they are (we previously had red channel used for transparency issues...).

**Comment by clockley** [comment]
Could glGetString(GL_RENDERER) be used to get driver info so the plugin could automatically select the R/B option on intel hardware?
https://docs.gl/gl3/glGetString

**Comment by clockley** [comment]
It looks like intel on linux/FreeBSD? supports GL_ARB_internalformat_query https://feedback.wildfiregames.com/report/opengl/feature/GL_ARB_internalformat_query
https://feedback.wildfiregames.com/report/opengl/feature/GL_ARB_internalformat_query2

**Comment by dongsub-joung** [comment]
Also, I encounter the same thing. 
Solution: ON "Swap red and blue" option

info: CPU Name: Intel(R) Pentium(R) CPU 2020M @ 2.40GHz
info: CPU Speed: 2323.221MHz
info: Physical Cores: 2, Logical Cores: 2
info: Physical Memory: 3806MB Total, 1774MB Free
info: Kernel Version: Linux 5.12.15-arch1-1
info: Distribution: "Arch Linux" Unknown
info: Session Type: x11
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.12
info: Portable mode: false
....
info: xcompcap: [window-capture: 'Window Capture (Xcomposite)'] update settings:
	title: Desktop
	class: xfdesktop
	Bit depth: 24
	Found proper GLXFBConfig (in 24): yes

info: xcompcap: [window-capture: 'Window Capture (Xcomposite)'] update settings:
	title: Desktop
	class: xfdesktop
	Bit depth: 24
	Found proper GLXFBConfig (in 24): yes

info: xcompcap: [window-capture: 'Window Capture (Xcomposite)'] update settings:
	title: 極黒のブリュンヒルデ　#3　鎮死剤 - ニコニコ動画 — Mozilla Firefox
	class: Navigator
	Bit depth: 32
	Found proper GLXFBConfig (in 24): yes

info: xcompcap: [window-capture: 'Window Capture (Xcomposite)'] update settings:
	title: 極黒のブリュンヒルデ　#3　鎮死剤 - ニコニコ動画 — Mozilla Firefox
	class: Navigator
	Bit depth: 32
	Found proper GLXFBConfig (in 24): yes

info: xcompcap: [window-capture: 'Window Capture (Xcomposite)'] update settings:
	title: YouTube Live Streaming API Overview  |  Google Developers — Mozilla Firefox
	class: Navigator
	Bit depth: 32
	Found proper GLXFBConfig (in 24): yes

info: xcompcap: [window-capture: 'Window Capture (Xcomposite)'] update settings:
	title: YouTube Live Streaming API Overview  |  Google Developers — Mozilla Firefox
	class: Navigator
	Bit depth: 32
	Found proper GLXFBConfig (in 24): yes

**Comment by RytoEX** [comment]
As previously stated by @kkartaltepe , this is what the "Swap red and blue" option is for. If someone can figure out a way to fix this without requiring said option, patches and PRs are welcome.
