### ISSUE TITLE
[BUG] Grid mode scene list allows items to be removed 

### ISSUE THREAD

**Issue by notr1ch** [obsproject/obs-studio#2676]
## Platform

Operating system and version: Windows 10 1909
OBS Studio version: 25.0.4

## Expected Behavior
Should not be able to accidentally discard the buttons.

## Current Behavior
![example](https://i.imgur.com/4lR0OxE.gif)

## Steps to Reproduce
1. Set scenes to grid mode
2. Drag and drop wildly

**Comment by emaste** [comment]
Confirmed similar misbehaviour on FreeBSD at 2a318d915fcc62ec31377ab7c3ac41a9bdecd2ae

**Comment by notr1ch** [comment]
More detailed reproduction steps:

Start dragging a scene item:
![](https://i.imgur.com/dcJozlX.png)

Notice how as soon as the scene item is moved away from its original location, the only place it exists now is on your cursor:
![](https://i.imgur.com/aPdcjaa.png)

Drop it somewhere invalid and the scene item is never restored to the Scenes list:
![](https://i.imgur.com/lO1zH5T.png)

**Comment by yunus-cakir** [comment]
How can I make grid?
