### ISSUE TITLE
Screen Capturing is not working

### ISSUE THREAD

**Issue by karthikone** [obsproject/obs-studio#2680]
Obs version : obs studio - 25.0.4(64bit)
Device : Acer Swift-3 
Cpu : intel i5-8250 ,intel UHD graphics 620
Gpu : Mx 150

Nvidia 3D settings are set to integrated/(tried with nvidia but both are not working.)
Tried run as admin, changed graphics settings to High performance but still not working.

**Comment by WizardCM** [comment]
The Github issues are **not** for support. Please use the [Discord](http://obsproject.com/discord) or the [Forums](http://obsproject.com/forum).
