### ISSUE TITLE
[BUG] Flatpak version (Linux) doesn't capture anything on Debian Testing and Fedora 32 Beta using Wayland

### ISSUE THREAD

**Issue by cold-distance** [obsproject/obs-studio#2683]
Hi, I'm using the Flatpak version of OBS Studio because I want to do screencasting from a Wayland session (GNOME). I tried Fedora 31 (GNOME 3.34), Fedora 32 Beta (GNOME 3.36) and Debian Bullseye Testing (mix of GNOME 3.34 and 3.36, but the Shell and Mutter are in 3.34). I can record the screen in Fedora 31, but the results are horrible. In Fedora 32 Beta the application crashes and on Debian Testing the recording is all black (so it's capturing nothing).

I use a RX 580 as GPU with AMDGPU (Open Source driver for Linux kernel), with 

## Platform
Operating system and version: Linux --> Fedora 32 Beta and Debian Testing (Bullseye 11) with Wayland 1.18.0-1.
OBS Studio version: 25.0.4 in Flatpak format (I use it because it has obs-xdg-portal plugin by default).

## Current Behavior
On Fedora 32 Beta the application crashes when it tries to capture (after selecting the screen or the app in the Screen Share section) the screen or an application through the obs-xdg-portal plugin on Wayland.

On Debian Testing (Bullseye) you see the screen capture all black after selecting the screen or the app in the Screen Share section. It doesn't crashes, but you can't record anything.

**Comment by tt2468** [comment]
The flatpak version is unofficial and not maintained by the OBS developers. I would recommend going to the maintainers of the package to get a fix.

**Comment by cold-distance** [comment]
So why the information of the Flatpak version says that is developed by "OBS Project" instead of "maintainers of the Flatpak version"? That's false information.

![Captura de pantalla de 2020-04-09 12-41-19](https://user-images.githubusercontent.com/43167050/78887228-c8595180-7a5f-11ea-8314-2313ffaba351.png)

**Comment by tt2468** [comment]
It is not false information. The publisher link on the site literally links to https://github.com/flathub/com.obsproject.Studio

Which has no affiliation with obsproject.

The "developer" field is just who made the source code, not who packaged it into a flatpak.

**Comment by kkartaltepe** [comment]
This package is unsupported by us.

The wayland capture plugins you are using are also unsupported by us.

**Comment by TingPing** [comment]
To be clear the bug tracker for the plugin is here: https://gitlab.gnome.org/feaneron/obs-xdg-portal/

**Comment by KiaraGrouwstra** [comment]
this bug itself appears related to #2471.
