### ISSUE TITLE
[Build process] Mac OS Nightly builds?

### ISSUE THREAD

**Issue by rcarmo** [obsproject/obs-studio#2684]
Hello there,

I tried to find another place to discuss this, but wasn't able to.

Since you're using Azure Pipelines, is there any chance you'd consider pushing out Mac builds (even if unstable) on a daily basis? I'd really like to have an updated version for the Mac (it's currently one major behind, and I'd like to have the recent hotfix release, but AFAIK the binaries are not available anywhere...).

I can help out with that if necessary, obviously.

**Comment by dodgepong** [comment]
We had a brief release of 25.0.5 for macOS, but there was an issue with the build setup that prevented RTMP streams from going live, so we took it down. We will be publishing it as soon as we get it fixed up.

**Comment by rcarmo** [comment]
Thanks, I appreciate the quick reply. It’s just that having the 24.x version on the website feels weird, plus I had to use Windows to work on a project instead...

**Comment by Fenrirthviti** [comment]
Going to close this for now, as it's not really a bug. In the future, we are most active on our [Discord](https://obsproject.com/discord). You can come ask us there in the appropriate channels.
