### ISSUE TITLE
[CRASH/FREEZE] Right clicking on any file or folder in "Remux Recordings" file selector crashes.

### ISSUE THREAD

**Issue by TheDWPCer** [obsproject/obs-studio#2692]
## Platform

Operating system and version: Windows 10 (64-bit)
OBS Studio version: 25.0.4 (64-bit)

## Expected Behavior

Don't Crash
## Current Behavior

Crashes
## Steps to Reproduce

1. Click on the "File" tab at the top left of the window.
2. Click on "Remux recordings."
3. Click on the "..." to select a file.
4. Now, right click on any file or folder.
5. ***KABOOM!*** **KER-POWEY!** ***BOOM!*** you've got a crash.

## Additional information

The only things I tested right click on was a mkv file and a folder (I assume it crashes with any file or folder).

**Comment by WizardCM** [comment]
Could you post the crash log that is generated by the crash?

**Comment by TheDWPCer** [comment]
Sadly I don't have a crash log, but I do have a log: https://pastebin.com/gd66SuFT
It's kind of a freeze, not a crash. I'll change that in the title

**Comment by TheDWPCer** [comment]
I checked event viewer there is something about obs there: 

> The program obs64.exe version 25.0.4.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 47a0
 Start Time: 01d60fbe4c6ade12
 Termination Time: 16
 Application Path: C:\Program Files (x86)\obs-studio\bin\64bit\obs64.exe
 Report Id: 37d36dd6-05f7-4dcf-82f7-b17957effc22
 Faulting package full name: 
 Faulting package-relative application ID: 
 Hang type: Cross-thread
>
here is also the details page (in xml):
`<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
<System>
  <Provider Name="Application Hang" /> 
  <EventID Qualifiers="0">1002</EventID> 
  <Level>2</Level> 
  <Task>101</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2020-04-11T05:02:17.927633500Z" /> 
  <EventRecordID>39169</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>DWGAMES</Computer> 
  <Security /> 
  </System>
<EventData>
  <Data>obs64.exe</Data> 
  <Data>25.0.4.0</Data> 
  <Data>47a0</Data> 
  <Data>01d60fbe4c6ade12</Data> 
  <Data>16</Data> 
  <Data>C:\Program Files (x86)\obs-studio\bin\64bit\obs64.exe</Data> 
  <Data>37d36dd6-05f7-4dcf-82f7-b17957effc22</Data> 
  <Data /> 
  <Data /> 
  <Data>Cross-thread</Data> 
  <Binary>430072006F00730073002D0074006800720065006100640000000000</Binary> 
  </EventData>
  </Event>`

**Comment by notr1ch** [comment]
Unable to reproduce, this is likely caused by buggy 3rd party shell extensions. Check https://obsproject.com/wiki/Known-Conflicts and https://docs.microsoft.com/en-us/sysinternals/downloads/autoruns
