### ISSUE TITLE
[BUG] OBS does not remove itself from the taskbar when NDI plugin is used

### ISSUE THREAD

**Issue by Bagny89** [obsproject/obs-studio#2695]
## Platform

Notebook: Acer Aspire E15-573G-79UB
Processor: Intel i7-5500u 2.40 Ghz - Dual Core
Graphics: Intel Graphic 5500 and Nvidia Geforce 920M
RAM: 8 GB
Operating system and version: Windows 10 1909
OBS Studio version: 25.0.4
Plugin Installed: OBS VirtualCam, NDI Sources

## Expected Behavior

After starting it, I would like OBS to be displayed during recording and live are in the system tray and not in the taskbar.

## Current Behavior

Basically - if I set OBS to minimize to tray AND minimize to tray on start-up it goes to tray on start-up, but if I bring it out of there.. And try to minimize it again it just goes to the taskbar, not to the tray.. And the "Hide" option when you right click the OBS tray icon doesn't do anything at all.

## Verification of the problem

From practice, I proceeded as follows: uninstalled OBS and plugins and gradually check where the problem arises.

Then I installed OBS -> VirtualCAM -> NDI Plugin. Until virtual CAM, the hide taskbar function works. (as seen in the video: https://streamable.com/tmfxtz

Installing NDI Plugin, the problem arises. (all this on my notebook.) In fact, the different checkpoints and the "Hide" command (right click on the system tray) do not work.

**Comment by Bagny89** [comment]
From practice, I proceeded as follows: uninstalled OBS and plugins and gradually check where the problem arises.

Then I installed OBS -> VirtualCAM -> NDI Plugin. Until virtual CAM, the hide taskbar function works. Installing NDI Plugin, the problem arises. (all this on my notebook.)

**Comment by notr1ch** [comment]
Reproduced with the NDI plugin. Very weird, no idea why the NDI plugin would be affecting tray behavior.

**Comment by Bagny89** [comment]
> Reproduced with the NDI plugin. Very weird, no idea why the NDI plugin would be affecting tray behavior.

Which version of NDI do you use? I used the last one (obs-ndi 4.8.0).

**Comment by grocal-speednet** [comment]
Wow, glad I found this bug. Here's my 0.03 $. I know the bug it's confirmed but here my observations.

With NDI plugin installed:
- minimizing to tray won't work, it minimizes but app stays in taskbar
- when OBS is minimized, clicking tray icon won't restore OBS
- when OBS is visible (not minimized), clicking tray icon... turns off preview, turning preview on  requires two click into "Enable Preview" button

I know, it's weird but it is what it is. And as it's a plugin related I guess it won't be easily fixed. Or at all :/

**Comment by gxalpha** [comment]
Please test whether this still happens with the OBS 28.0.2, the UI framework got a major update between 27.2 and 28.
If it does, please report this issue to obs-ndi as it appears to be caused by the plugin, not OBS itself.
