### ISSUE TITLE
[BUG] source properties checkbox label is not clickable when tooltip is present

### ISSUE THREAD

**Issue by notr1ch** [obsproject/obs-studio#2698]
## Platform

Operating system and version: Windows 10 1909
OBS Studio version: 25.0.4

## Expected Behavior
Clicking the text label next to a checkbox should toggle the checkbox state.

## Current Behavior
If the checkbox has a "long description" (obs_property_long_description), a tooltip widget is added which breaks the behavior of being able to click the label to toggle the checkbox.

Example:
![example](https://i.imgur.com/7w1qhqt.png)

## Steps to Reproduce

1. Add a media source
2. Try toggling "Close file while inactive" by clicking the text

Reported on Discord at https://discordapp.com/channels/348973006581923840/376042662580715521/698576079618572449

**Comment by notr1ch** [comment]
Regression introduced in https://github.com/obsproject/obs-studio/commit/51948ebc8763c468c5e4b8a91d208fb4ff1e4192

**Comment by WizardCM** [comment]
I could have sworn I explicitly made sure to handle this use case because I use the text to click on checkboxes all the time. I'll submit a fix for this today.

**Comment by AngeredZeus** [comment]
https://github.com/AngeredZeus/obs-studio/commit/56df333f23ac6ee958a73f6597e61b684ca52c64I tried to create a fix here.

**Comment by notr1ch** [comment]
Thanks for the fix! A tip for next time - if you mention in the PR comment "Fixes https://github.com/obsproject/obs-studio/issues/2698" then github can automatically link the issue to the PR and close it when the PR is merged.
