### ISSUE TITLE
[BUG] Virustotal has detected a virus in zip file 

### ISSUE THREAD

**Issue by faxage6391** [obsproject/obs-studio#2703]
The zip file is detected as having a virus (Backdoor.Dtback.b)
https://www.virustotal.com/gui/file/db6214dce625f429369f6e537a86c48adbfa2d123b204f3e347b02ceaaca1b93/detection

## Platform

Operating system and version: Windows 10
OBS Studio version: OBS-Studio-25.0.4-Full-x64

## Expected Behavior

No virus should be detected

## Current Behavior

here is the link to virustotal report https://www.virustotal.com/gui/file/db6214dce625f429369f6e537a86c48adbfa2d123b204f3e347b02ceaaca1b93/detection

## Steps to Reproduce

1. Download zip from official site
2. Upload to virustotal.com

**Comment by Fenrirthviti** [comment]
The detection comes from a very low reputation Chinese adware company. False positive.
