### ISSUE TITLE
[BUG] <bug description>No browser-source after building and installing obs 25.0.3 and 25.0.4 Debian

### ISSUE THREAD

**Issue by koreanfan** [obsproject/obs-studio#2705]
## Platform

Operating system and version: Debian Bullseye 5.4.0-4-amd64  SMP Debian 5.4.19-1 (2020-02-13) x86_64 GNU/Linux
OBS Studio version: 25.0.4 and 25.0.3

## Expected Behavior

Use buld-in browser source plugin 
## Current Behavior

After building and installing from wiki browser source plugin didnt show up
## Steps to Reproduce

1. mkdir ~/Test_obs , cd Test_obs , wget -nc https://github.com/obsproject/obs-studio/archive/25.0.4.tar.gz
tar xvzf 25.0.4.tar.gz
2.wget https://cdn-fastly.obsproject.com/downloads/cef_binary_3770_linux64.tar.bz2
           tar -xjf ./cef_binary_3770_linux64.tar.bz2
3.cd obs-studio-25.0.4 , mkdir build && cd build
4.cmake -DUNIX_STRUCTURE=1 -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_BROWSER=ON -DCEF_ROOT_DIR="../../cef_binary_3770_linux64" ..

  make -j4
  sudo checkinstall --default --pkgname=obs-studio --fstrans=no --backup=no \
         --pkgversion="$(date +%Y%m%d)-git" --deldoc=yes
5. Start obs and browser source didnt show up
6. Delete obs-studio with config files and try build and install obs 25.0.3
7. Browser source didnt show up

**Comment by Gol-D-Ace** [comment]
The build instructions mention to use git clone with the recursive option.

The reason for that is because the browser source and other plugins like FTL are submodules and aren't included in the top you can download from GitHub.

**Comment by WizardCM** [comment]
On top of what Gol-D-Ace mentioned, your build steps also do not run cmake on CEF, which you also need to do before compiling OBS.

**Comment by Gol-D-Ace** [comment]
@WizardCM 
The zip we offer does have the wrapper already build. It isn't necessary therefore to run cmake there.

**Comment by koreanfan** [comment]
So, i need download all plugins from https://github.com/obsproject/obs-studio/tree/master/plugins to my directrory ~/Test_obs/obs-studio-25.0.4/plugins if i want have all plugins and after that install obs?

**Comment by Gol-D-Ace** [comment]
Run
`git clone --recursive https://github.com/obsproject/obs-studio.git`
to get a source code copy that includes everything

**Comment by koreanfan** [comment]
Ok, i download git clone --recursive https://github.com/obsproject/obs-studio.git, then i copy browser source plugin from obs-studio.git to my current folder  ~/Test_obs/obs-studio-25.0.4/plugins
Then i install obs and browser source plugin show and work. Btw in obs 25.0.4 i dont have problem when pick a file for obs image plugin (https://github.com/obsproject/obs-studio/issues/2651), thats why i downgraded from 25.0.5

**Comment by Fenrirthviti** [comment]
Appears to be user error in build steps which is now resolved. In the future, please do not report build environment issues, come talk to us on [Discord](https://obsproject.com/discord) first.

**Comment by koreanfan** [comment]
Sry but i dont use discord
