### ISSUE TITLE
[BUG] Scene source still shows in sources after the scene is deleted

### ISSUE THREAD

**Issue by skeletonbow** [obsproject/obs-studio#2713]
## Platform

Operating system and version:  Windows 10 x64 (1909)
OBS Studio version:  25.0.4

## Expected Behavior

When a scene is deleted in the scenes pane, Scene Source that refer to it in other scenes should either be changed to not refer to it and stay present, or they should be deleted from the sources list for any scenes they appear in.

## Current Behavior

When deleting a scene that is used elsewhere in a scene source, OBS sometimes still shows the scene source as being present and continues to refer to the scene that was deleted.

https://obsproject.com/logs/wwYQr1_Xulb08lMi

## Steps to Reproduce

1.  Create a new scene collection "Bug Test"
2.  Add a new scene named "Scene 2", and another named "Scene 3"
3.  Switch to the default "Scene", and add Scene Source "Scene 2", then another for "Scene 3"
4.  In the Scenes pane, select Scene 3, right click and Remove it.
5.  Now do the same and remove Scene 2 from the scenes pane.

OBS now shows the remaining original scene named "Scene" with one of the scenes that were previously deleted still showing up in the sources list.

**Comment by skeletonbow** [comment]
![image](https://user-images.githubusercontent.com/49483514/79153108-53f21b80-7d9b-11ea-951a-565af1ef537d.png)

**Comment by skeletonbow** [comment]
Right clicking on the visible "Scene 3" source and choosing "Remove" from the menu does nothing and the Scene 3 continues to stick around in the sources pane with no apparent way to remove it.

**Comment by skeletonbow** [comment]
After exiting OBS completely then reopening it, the Scene Source for "Scene 3" disappeared from the sources list for "Scene", however... oddly enough OBS added "Scene 3" back to the scenes pane for some reason.

**Comment by maxdrash** [comment]
But, as long as the deleted scene are visible in program view it's better that it stays ?
Have you switch scenes in program ?

**Comment by skeletonbow** [comment]
> But, as long as the deleted scene are visible in program view it's better that it stays ?

I would definitely say no, because the existing behaviour is inconsistent because when removing scenes, all of the scenes are actually removed in the scene pane, but only the last one removed stays showing up in the source pane for the original scene.  Also, when the program exits and restarts, then the Scene comes back from the dead magically into the Scene list, but is no longer present as a Scene Source in the first scene.  That can't possibly be intended behaviour.

If the intention of the developers is that Scene Source for deleted scenes stay present in the sources list, then the bug is that sometimes they are deleted and sometimes they are not.  I can't imagine why keeping the source around would be useful as you can't point it at another scene I don't believe, and it's pointing to a non-existent one if it remains.  Either way there is a bug here because of the inconsistent behaviour, and the fact that the configuration changes on its own without user intervention just by restarting OBS.

> Have you switch scenes in program ?

While adding the scenes, yes.  When the scenes are then deleted, there is only one scene remaining when this problem occurs and so it isn't possible to switch scenes anymore because there is only one scene left.  Once the program is exited and restarted and the scene comes back from the dead in the scene list, it is possible to switch to it.  In my reproducible test case I did not put anything in the other scenes however so nothing is actually visible in the preview area, but the test case I gave does reproduce the bug reliably.  Someone else has independently reproduced it in private chat not long after I posted the bug also.

If anyone has problems reproducing let me know and I'll screen capture on a fresh installation.

Thanks for investigating, much appreciated!

**Comment by WizardCM** [comment]
I personally vote that the best fix to this solution would be https://github.com/obsproject/obs-studio/pull/2238 with a greyed out, already checked "Remove all references", to make it clear what is about to happen.

**Comment by exeldro** [comment]
This seems related to #2602 and #3807

**Comment by gxalpha** [comment]
@skeletonbow could you confirm this is still an issue in 27.2?
There have been several changes made related to this in the meantime and I think this problem no longer exists.

**Comment by gxalpha** [comment]
We think this should be fixed by now.
