### ISSUE TITLE
[BUG] Ubuntu version in PPA not buildt with browser plugin

### ISSUE THREAD

**Issue by Tandolf** [obsproject/obs-studio#2714]
## Platform
Operating system and version: Ubuntu 19.10
OBS Studio version: 25.0.4 64-bit

## Expected Behavior
The former used browser plugin was deprecated in favor of browser support in obs-studio for linux from v25 and beyond. So expected is that after installing obs-studio from the obsproject ppa, the browserplugin should be present.

## Current Behavior
After installing OBS-Studio from the obsproject ppa. The official browser plugin is not installed.

## Steps to Reproduce
1. sudo add-apt-repository ppa:obsproject/obs-studio
2. sudo apt-get update
3. sudo apt-get install obs-studio

## Additional information
At the browser plugins github readme, there is only instruction for building the plugin from source for Mac and Windows, no linux option.

**Comment by Fenrirthviti** [comment]
This is not a bug, we temporarily rolled back due to crashing conflicts with gtk+ based window managers. See: https://github.com/obsproject/obs-browser/issues/219

**Comment by Corben78** [comment]
A hint in the patch notes would have been helpful (and saved time finding this closed issue).

**Comment by Fenrirthviti** [comment]
This is a temporary solution until we can fix the bug, it was an emergency rollback, we are working to resolve it as soon as we can.
