### ISSUE TITLE
[BUG]Decklink crash when start output and preview output at the same time

### ISSUE THREAD

**Issue by wxq118691** [obsproject/obs-studio#2716]
## Platform
Operating system and version:windows10 64 pro
OBS Studio version: 25.0.4

## Expected Behavior
not to be crash

## Current Behavior
Crash：if start OUTPUT and PREVIEW OUTPUT using same Ducklink Duo（x）always caused crash

## Reproduce Rate: 
100%

## Steps to Reproduce
1. Using blackmagic duo2 and add this blackmagic source：Ducklink duo（4）
2. Open tool >deck link output >
OUTPUT ：select ducklink duo（1），1080p60，auto start（whatever），disabled > start
3. PREVIEW OUTPUT ：select ducklink duo（1），whatever，auto start（whatever），NOTdisabled（external/internal）
4.click start few times

## Additional information
[2020-04-14 17-35-22.txt](https://github.com/obsproject/obs-studio/files/4474498/2020-04-14.17-35-22.txt)

![2020-04-14 17;43;19](https://user-images.githubusercontent.com/11622602/79210503-8709dd00-7e77-11ea-9dd7-1343ec68ca16.gif)

**Comment by Fenrirthviti** [comment]
Can you provide the crash log as well?

**Comment by wxq118691** [comment]
[2020-04-15 13-43-59.txt](https://github.com/obsproject/obs-studio/files/4479315/2020-04-15.13-43-59.txt)
[2020-04-15 13-45-06.txt](https://github.com/obsproject/obs-studio/files/4479318/2020-04-15.13-45-06.txt)
[2020-04-15 13-45-39.txt](https://github.com/obsproject/obs-studio/files/4479319/2020-04-15.13-45-39.txt)
@Fenrirthviti here you are

**Comment by wxq118691** [comment]
More detail：
1.device： 
Blackmagic webpresenter+Sony CAM+Blackmagic DeckLink Duo2
2.device connect：
+ Blackmagic webpresenter plug in the power cord
+Blackmagic webpresenter HDMI IN to Sony Camera
+Blackmagic webpresenter SDI OUT plug in SDI line, the other end connects to Blackmagic Duo 2 interface (4)
+Debug the corresponding interface of Blackmagic Duo 2 software: desktop video setup, reference picture:
![下载](https://user-images.githubusercontent.com/11622602/79302847-1074ea00-7f20-11ea-868f-f1433405318c.png)
3.Capture Blackmagic Duo 2
+Source> Blackmagic source> Select the channel used as the channel used (4)
+Video Connection: SDI
+Mode: auto (using other will not output the picture, which may also be a issue？)

**Comment by maxdrash** [comment]
Issue not reproduced on Linux.
Same Output selected (decklink 4 for example) start Output and tried to start Preview Output, no crash, just: the start button won't be enabled.

log say:
decklink: Failed to enable video output

I think that's Decklink SDK that don't allow 2 SMPTE streams but OBS don't crash.
It's a Windows specific issue maybe ?

**Comment by wxq118691** [comment]
yes @maxdrash 
It is happened on Windows 10 64bit

**Comment by oddsix** [comment]
This happens on Linux(Mint) with a Declink Quad HDMI recorder.  Choose Decklink Output, click start and SEGV.  I can provide whatever is needed, logs, core, etc..

**Comment by maxdrash** [comment]
> This happens on Linux(Mint) with a Declink Quad HDMI recorder. Choose Decklink Output, click start and SEGV. I can provide whatever is needed, logs, core, etc..

That card can be used only for inputs no outputs.

**Comment by pthewy** [comment]
I am experiencing the same issue. Has anyone found a resolution to this problem?

**Comment by ogmkp** [comment]
Is this issue still occurs ?

**Comment by Fenrirthviti** [comment]
Closing as stale. If this is still an issue please open with updated reproduction steps on the latest version of OBS.
