### ISSUE TITLE
[BUG] Image file not appearing in file browser if extension is in uppercase

### ISSUE THREAD

**Issue by hellocatfood** [obsproject/obs-studio#2717]
## Platform
Operating system and version: Ubuntu 19.10 64 Bit
OBS Studio version: 25.0.4 installed via ppa https://launchpad.net/~obsproject/+archive/ubuntu/obs-studio

## Expected Behavior
When adding an Image source I click on Browse to find an image (jpg or png) and then I should be able to double-click on it to select it.

## Current Behavior
When clicking Browse the image does not show up in the file browser if the file extension is in uppercase (i.e. JPG or PNG)

## Steps to Reproduce
1. Add an image source
2. Click on Browse
3. Navigate to a location where a jpg or png resides that has the file extension in uppercase
4. File does not show up in file browser invoked by OBS

## Additional information
This was tested only with jpg and png file types but may be true of any file type if the extension is in uppercase

**Comment by kkartaltepe** [comment]
At this time we are uninterested in supporting mixed case extensions on case sensitive filesystems. Its recommended you use lower case.
