### ISSUE TITLE
NDI not present in OBS 25 update; via Mac ios [BUG] <bug description>

### ISSUE THREAD

**Issue by Cinsound** [obsproject/obs-studio#2722]
## Platform

Operating system and version:
OBS Studio version:

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Fenrirthviti** [comment]
This is not a valid bug report, as you did not properly fill out the template. We also do not maintain the NDI plugin. Please report it on the NDI plugin repository.

**Comment by Cinsound** [comment]
I’m just letting who ever know

Always looking forward
Nicholas Rossi

On Apr 15, 2020, at 2:03 AM, Joel Bethke <notifications@github.com> wrote:

﻿

This is not a valid bug report, as you did not properly fill out the template. We also do not maintain the NDI plugin. Please report it on the NDI plugin repository.
