### ISSUE TITLE
[BUG] shared handle of D3D11 is passing by 32bit

### ISSUE THREAD

**Issue by wangshaohui1314** [obsproject/obs-studio#2727]
Hello, when I study code of OBS, I find a question and maybe it is a bug.
Please confirm it, thanks !

There are several modules using shared handle, such as monitor capture on Window 10, GPU capture for browser and game. However I find the share handle of D3D11Texture2D (HANDLE) is passing with 4 Bytes. This may cause data loss for HANDLE in 64 bit.

By the way, while using HANDLE between OBS.X86 and game.x64, memory size should also be considered.

=================================
Such as these  code:

**graphics.c**
gs_texture_t *gs_texture_open_shared(uint32_t handle)

**graphics-hook-info.h**
struct shtex_data {
	uint32_t tex_handle;
};

**Comment by walker-WSH** [comment]
> This is not a bug. Those values assigned to those variables by Microsoft are always limited to 32bit to allow interoperability between 32bit and 64bit.


I just save the related doc of MS
https://learn.microsoft.com/en-us/windows/win32/winprog64/interprocess-communication
