### ISSUE TITLE
[BUG] SRT Support on Mac

### ISSUE THREAD

**Issue by anders-d** [obsproject/obs-studio#2731]
## Platform

Operating system and version: MacOS 10.14.16
OBS Studio version: 25.0.6 (mac)

## Expected Behavior

SRT streaming according to:
https://obsproject.com/wiki/Streaming-With-SRT-Protocol

## Current Behavior

"Invalid Path or Connection URL. Please check your settings to confirm that they are valid."

## Additional information

Is really the bundled FFmpeg srt enabled and the srtlib included, with the OBS version 25 release for Mac?

**Comment by pkviet** [comment]
yes they are.
Detail your setup and post a log.
What was your destination ? vlc ? a server ? (which server)

**Comment by susemeee** [comment]
Uploading your log file (Help -> Log Files -> Upload Last Log File) might be helpful.

**Comment by Fenrirthviti** [comment]
The Issues page is not for support. Please use the forums or Discord if you need further assistance with this.

https://obsproject.com/help
