### ISSUE TITLE
OBS can't capture background processes

### ISSUE THREAD

**Issue by Jwguy** [obsproject/obs-studio#2734]
Sorry if this the wrong place for this, but I've been trying to capture a window with OBS, but it runs as a background process, and can't be selected in Window Capture. It's kind of the opposite problem of [#2326 ].

Is there a means of configuring OBS to be able to capture this kind of process? Or might I suggest one?

**Comment by notr1ch** [comment]
Please use the forums or Discord for support. If you're reporting a reproducible bug, fill in the issue template fully.
