### ISSUE TITLE
[BUG] Shortcuts not working on Ubuntu 19.10

### ISSUE THREAD

**Issue by FilippoLeone** [obsproject/obs-studio#2740]
## Platform
Operating system and version: Ubuntu 19.10
OBS Studio version: 25.0.6 (Linux) installed via `snap install obs-studio`

## Expected Behavior
Mute/Unmute shortcuts (I assigned SHIFT + /) should mute my microphone input

## Current Behavior
My shortcut doesn't do anything when triggered

## Steps to Reproduce
1. Add shortcut to shortcut list and apply
2. Trigger shortcut

## Additional information
Restarting OBS didn't work, changing shortcut keys didn't work. The shortcut is not used by anything else in the system

**Comment by Gol-D-Ace** [comment]
We do not maintain the Ubuntu Snap.
Please contact the snap maintainer.
https://github.com/snapcrafters/obs-studio
