### ISSUE TITLE
[BUG] Saved projector is not displayed when starting OBS

### ISSUE THREAD

**Issue by nuevoextremo** [obsproject/obs-studio#2742]
## Platform

Operating system and version: Windows 10 Pro (with all official updates)
OBS Studio version: 25.0.4

## Expected Behavior
What should happen is that when you start OBS with projector saved, it should automatically show the projector.

## Current Behavior
I have OBS configured so that when Windows starts, OBS immediately runs with a screen configured as a projector, but when I start OBS, the projector does not appear and only the icon remains in the system tray. To display the projector you must close OBS and then select the projector screen again.

## Steps to Reproduce
1. Start Windows 10 PRO
2. Automatic OBS with projector execution through Scheduled Tasks
3. OBS starts and is minimized in the system tray
4. OBS does not show the projector on the configured screen

## Additional information
The rest of the options work without problems, however, the projectors are having problems to be shown when starting OBS and to fix it you have to manually activate the projector. Maybe the option "Save projectors on exit" has problems.

**Comment by RytoEX** [comment]
This appears to no longer be an issue in OBS Studio 28.0.1. If this is still an issue for you, please comment on this Issue with additional details and steps to reproduce.
