### ISSUE TITLE
[BUG] Multiview on MacOS is Non Functioning

### ISSUE THREAD

**Issue by TBurnip** [obsproject/obs-studio#2743]
## Platform
Operating system and version: MacOS Catalina
OBS Studio version: 25.0.7

## Expected Behavior
Multiview should by default provide a view of Program and Preview as well as a series of defined scenes

## Current Behavior
Multiview is only rendering Program and Preview and it is rendering them over the wrong section (e.g. rendering where the scenes should be). The scenes are not rendering at all even when program or preview is transparent (however the grid and names can be viewed when program or preview is at least partially transparent).
`19:45:52.035: CPU Name: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
19:45:52.035: CPU Speed: 2300MHz
19:45:52.035: Physical Cores: 8, Logical Cores: 16
19:45:52.035: Physical Memory: 32768MB Total
19:45:52.035: OS Name: Mac OS X (NSMACHOperatingSystem)
19:45:52.035: OS Version: Version 10.15.4 (Build 19E287)
19:45:52.035: Kernel Version: 19.4.0
19:45:52.045: hotkeys-cocoa: Using layout 'com.apple.keylayout.British-PC'
19:45:52.047: Portable mode: false
19:45:52.162: OBS 25.0.7 (mac)
19:45:52.162: ---------------------------------
19:45:52.163: ---------------------------------
19:45:52.163: audio settings reset:
19:45:52.163: 	samples per sec: 48000
19:45:52.163: 	speakers:        2
19:45:52.180: ---------------------------------
19:45:52.180: Initializing OpenGL...
19:45:52.205: Loading up OpenGL on adapter ATI Technologies Inc. AMD Radeon Pro 5500M OpenGL Engine
19:45:52.205: OpenGL loaded successfully, version 4.1 ATI-3.8.24, shading language 4.10
19:45:52.284: ---------------------------------
19:45:52.284: video settings reset:
19:45:52.284: 	base resolution:   1920x1080
19:45:52.284: 	output resolution: 1280x720
19:45:52.284: 	downscale filter:  Bicubic
19:45:52.284: 	fps:               25/1
19:45:52.284: 	format:            NV12
19:45:52.284: 	YUV mode:          601/Partial
19:45:52.284: NV12 texture support not available
19:45:52.284: Audio monitoring device:
19:45:52.284: 	name: Steinberg UR22C
19:45:52.284: 	id: YamahaUSBAudioEngine2:0499:172f:0101:Steinberg UR22C:L-01130000:SS
19:45:52.284: ---------------------------------
19:45:52.304: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
19:45:52.338: os_dlopen(libpython3.7m.dylib->libpython3.7m.dylib): dlopen(libpython3.7m.dylib, 257): image not found
19:45:52.338: 
19:45:52.338: [Python] Could not load library: libpython3.7m.dylib
19:45:52.495: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
19:45:52.495: No blackmagic support
19:45:52.591: [VideoToolbox encoder]: Adding VideoToolbox H264 encoders
19:45:52.705: [obs-browser]: Version 2.8.6
19:45:52.861: os_dlopen(/Applications/VLC.app/Contents/MacOS/lib/libvlccore.dylib->/Applications/VLC.app/Contents/MacOS/lib/libvlccore.dylib): dlopen(/Applications/VLC.app/Contents/MacOS/lib/libvlccore.dylib, 257): image not found
19:45:52.861: 
19:45:52.861: Couldn't find VLC installation, VLC video source disabled
19:45:52.869: [obs-ndi] hello ! (version 4.7.1)
19:45:52.869: [obs-ndi] Trying ''
19:45:52.869: [obs-ndi] Trying '/usr/lib'
19:45:52.869: [obs-ndi] Trying '/usr/local/lib'
19:45:52.869: [obs-ndi] Found NDI library at '/usr/local/lib/libndi.4.dylib'
19:45:52.911: [obs-ndi] NDI runtime loaded successfully
19:45:52.912: [obs-ndi] NDI library initialized successfully (NDI SDK APPLE 14:35:05 Dec 19 2019 4.1.3)
19:45:53.166: ---------------------------------
19:45:53.166:   Loaded Modules:
19:45:53.166:     spectralizer.so
19:45:53.166:     obs-ndi.so
19:45:53.166:     vlc-video.so
19:45:53.166:     text-freetype2.so
19:45:53.166:     rtmp-services.so
19:45:53.166:     obs-x264.so
19:45:53.166:     obs-vst.so
19:45:53.166:     obs-transitions.so
19:45:53.166:     obs-outputs.so
19:45:53.166:     obs-libfdk.so
19:45:53.166:     obs-filters.so
19:45:53.166:     obs-ffmpeg.so
19:45:53.166:     obs-browser.so
19:45:53.166:     mac-vth264.so
19:45:53.166:     mac-syphon.so
19:45:53.166:     mac-decklink.so
19:45:53.166:     mac-capture.so
19:45:53.166:     mac-avcapture.so
19:45:53.166:     linux-jack.so
19:45:53.166:     image-source.so
19:45:53.166:     frontend-tools.so
19:45:53.166:     decklink-ouput-ui.so
19:45:53.166:     coreaudio-encoder.so
19:45:53.166: ---------------------------------
19:45:53.166: os_dlopen(../obs-plugins/obs-browser->../obs-plugins/obs-browser.so): dlopen(../obs-plugins/obs-browser.so, 257): image not found
19:45:53.166: 
19:45:53.166: ==== Startup complete ===============================================
19:45:53.183: All scene data cleared
19:45:53.183: ------------------------------------------------
19:45:53.241: coreaudio: device 'Steinberg UR22C' initialized
19:45:53.241: [Loaded global audio device]: 'Mic/Aux'
19:45:53.250: FT2-text: Failed to load font Myriad Pro
19:45:53.292: [Media Source 'Hold']: settings:
19:45:53.292: 	input:                   /Users/thomasburnip/OneDrive/Pause/Stream Hold/HoldForStream3.mp4
19:45:53.292: 	input_format:            (null)
19:45:53.292: 	speed:                   100
19:45:53.292: 	is_looping:              yes
19:45:53.292: 	is_hw_decoding:          no
19:45:53.292: 	is_clear_on_media_end:   yes
19:45:53.292: 	restart_on_activate:     no
19:45:53.292: 	close_when_inactive:     no
19:45:53.347: adding 64 milliseconds of audio buffering, total audio buffering is now 64 milliseconds (source: Hold)
19:45:53.347: 
19:45:53.377: coreaudio: device 'BlackHole 16ch' initialized
19:45:53.378: [obs-ndi] started A/V threads for source 'DESKTOP-AS93VO8 (Parallels Display Adapter (WDDM) 2)'
19:45:53.378: [obs-ndi] A/V thread for 'NDI™ Source' started
19:45:53.378: [spectralizer] Added audio capture to 'Mic/Aux'
19:45:53.386: [spectralizer] Added audio capture to 'NDI™ Source'
19:45:53.387: [Media Source 'Paws (Stinger)']: settings:
19:45:53.387: 	input:                   /Users/thomasburnip/OneDrive/ME/Blender/Pause/Output4.webm
19:45:53.387: 	input_format:            (null)
19:45:53.387: 	speed:                   100
19:45:53.387: 	is_looping:              no
19:45:53.387: 	is_hw_decoding:          no
19:45:53.387: 	is_clear_on_media_end:   yes
19:45:53.387: 	restart_on_activate:     yes
19:45:53.387: 	close_when_inactive:     no
19:45:53.387: Switched to scene 'Holding'
19:45:53.387: ------------------------------------------------
19:45:53.387: Loaded scenes:
19:45:53.388: - scene 'Holding':
19:45:53.388:     - source: 'Hold' (ffmpeg_source)
19:45:53.388: - scene 'Games':
19:45:53.388:     - source: 'NDI™ Source' (ndi_source)
19:45:53.388: - scene 'Games Covered':
19:45:53.388:     - source: 'Overlays' (scene)
19:45:53.388:     - source: 'To Rude' (text_ft2_source_v2)
19:45:53.388: - scene 'Just Speech':
19:45:53.388:     - source: 'Color Source' (color_source_v2)
19:45:53.388:     - source: 'Overlays' (scene)
19:45:53.388:     - source: 'Pause Streaming Logo' (image_source)
19:45:53.388: - scene 'Overlays':
19:45:53.388:     - source: 'NDI™ Source' (ndi_source)
19:45:53.388:     - source: 'Toms Mic Visualiser' (spectralizer)
19:45:53.388:     - source: 'Discord Visualiser' (spectralizer)
19:45:53.388:         - filter: 'Image Mask/Blend' (mask_filter)
19:45:53.388:     - source: 'Discord Audio' (coreaudio_input_capture)
19:45:53.388: ------------------------------------------------
19:45:53.419: [Media Source 'CountIn (Stinger)']: settings:
19:45:53.419: 	input:                   /Users/thomasburnip/OneDrive/Pause/CountIn/Test5.webm
19:45:53.419: 	input_format:            (null)
19:45:53.419: 	speed:                   100
19:45:53.419: 	is_looping:              no
19:45:53.419: 	is_hw_decoding:          no
19:45:53.419: 	is_clear_on_media_end:   yes
19:45:53.419: 	restart_on_activate:     yes
19:45:53.419: 	close_when_inactive:     no
19:45:53.461: Switched to Preview/Program mode
19:45:53.461: ------------------------------------------------
19:45:57.355: adding 21 milliseconds of audio buffering, total audio buffering is now 85 milliseconds (source: Hold)
19:45:57.355: 
19:46:05.292: User switched to scene 'Overlays'
19:46:05.360: adding 21 milliseconds of audio buffering, total audio buffering is now 106 milliseconds (source: Hold)
19:46:05.360: 
19:46:11.064: User switched to scene 'Games'
19:46:12.970: User switched to scene 'Holding'
`

## Steps to Reproduce
1. Open obs
2. Set Up a series of different scenes three should do
3. Open Multiview Using either Fullscreen or windowed

Thanks for your help I really appreciate people supporting an open source project with there time

**Comment by dodgepong** [comment]
We've tracked the cause of this bug to this commit: https://github.com/obsproject/obs-studio/commit/9f330050ef8d

We're still working out why it's happening, and how it can be fixed.

**Comment by Jamie-** [comment]
This issue has been closed but has it actually been fixed? I was seeing this too and if it's not fixed can it please be re-opened.

**Comment by dodgepong** [comment]
It should be fixed as of 25.0.8.

**Comment by TBurnip** [comment]
As far as i could ascertain it has been fixed in 25.0.8 that's why i closed the issue. With my limited testing it was working. I have opened and played around with the multiview but not used it for an duration or while streaming or recording because i haven't need to yet.
