### ISSUE TITLE
[BUG] LUTs no longer working

### ISSUE THREAD

**Issue by maxdrfr** [obsproject/obs-studio#2747]
## Platform

Operating system and version: Linux Ubuntu 18.04
OBS Studio version: 25.0.4-0obsproject3~bionic from official ppa

## Expected Behavior

When I apply a LUT in cube format, it changes the colors of the source.

## Current Behavior

When I apply a LUT in cube format, it don't change the colors of the source.

## Steps to Reproduce

1. Right click on video source and choose a filter
2. Add a LUT
3. Choose the grayscale LUT in cube format
4. No effect

## Additional information

If i choose a LUT in png format, it works.
No errors in log, logging don't mention that i apply a LUT file but just the filter:
```
info: User removed filter 'Appliquer un LUT' (clut_filter) from source 'Source média'
info: User added filter 'Appliquer un LUT' (clut_filter) to source 'Source média'
```
It's working with 25.0.4-0obsproject1~bionic

**Comment by Gol-D-Ace** [comment]
Can confirm that cube format filters aren't working.

My local builds with different versions (25.0.2 / 25.0.4) also have no working cube filters.

They appear to be working fine on windows.

I personally have no clue why they would work in that particular build and not in a later one.

Both builds use the same code, only the browser source got removed.
(Yes I tried building with and without the browser source locally and it doesn't make a difference.)

**Comment by Gol-D-Ace** [comment]
Tried different Linux distros now as well (Manjaro) and still not working.
I'm starting to doubt if cube files ever worked.

I'm gonna try to get a none VM system to run with Ubuntu. Maybe it will make a difference.

**Comment by maxdrash** [comment]
Yes, It's working on 25.0.4-0obsproject1~bionic from ppa but that not promoted anymore. 
See: https://github.com/obsproject/obs-studio/issues/2644#issuecomment-612632902

**Comment by Gol-D-Ace** [comment]
I tried this now on Ubuntu 19.10 (Eoan) with real hardware and it worked fine there.

I also tried it with Ubuntu 18.04 (Bionic) with real hardware and I can't reproduce it there.
https://i.imgur.com/kJr5nSer.png

Please try reinstalling OBS.
sudo apt remove obs-studio
sudo apt install obs-studio

**Comment by maxdrash** [comment]
I have installed Ubuntu 20.04 this morning, wich promote OBS 25.0.3 in their repos, and LUT don't work on cube files.
After this test, I've installed OBS 25.0.7 from official ppa, same result, cube format won't work.
I have real hardware, sorry.
Two screenshots:
https://imgur.com/a/LMVQQtw

**Comment by kkartaltepe** [comment]
Provide a log, at least the part containing your driver versions and hardware.

**Comment by maxdrash** [comment]
Yes, here:
https://pastebin.com/raw/Vy5XCkRz

**Comment by burkingman** [comment]
Same problem here: png LUTs work fine, cube LUTs have no effect at all (my OS is Linux Mint 19.3). Rather happy with OBS otherwise, I like how much control it gives me when broadcasting. Great software.
My log: https://pastebin.com/raw/cGtqYZan

**Comment by maxdrash** [comment]
Any news about this regression ?

**Comment by maxdrash** [comment]
Same problem on OBS 25.0.8 ppa

**Comment by maxdrash** [comment]
But, i don't understand, the LUTs on cube format works again, no changes in sources/scenes/filters, just restarting OBS many times.

**Comment by maxdrash** [comment]
Same OBS 25.0.8 version and Ubuntu 20.04 version on 2 PCs, and first works great with LUTs but not other one.

**Comment by jpark37** [comment]
I am not able to reproduce on 20.04 with apt (25.0.3) or master HEAD (in-progress 26). It may help if you can provide an entire log from a session where the CUBE LUT fails.

**Comment by maxdrash** [comment]
> I am not able to reproduce on 20.04 with apt (25.0.3) or master HEAD (in-progress 26). It may help if you can provide an entire log from a session where the CUBE LUT fails.

I provided the log here: 
https://github.com/obsproject/obs-studio/issues/2747#issuecomment-619298770

But theres a last log with LUT cube not working on OBS 26.0:
https://obsproject.com/logs/oj3KiEfcCoLRIZ68

I don't know if this is a GPU problem or anything else, I tested on two nvidia GPU, first cube works great, second not (same OBS version, same Ubuntu, same nvidia drivers).
PNG luts works all the time.

**Comment by DrNI** [comment]
I can confirm this on OBS 25.02. and 26.1.0 on Kubuntu 18.04 using an V4L2 video source (AverMedia LGP2 HDMI/USB-UVC). 

Nothing happens, no debug out. I tried with grayscale.cube that comes with OBS, but also with others.

GPU is Nvidia.

**Comment by maxdrfr** [comment]
Hi, no solution for this random issue ?
@Gol-D-Ace @jp9000 ?

**Comment by maxdrfr** [comment]
Theres a LUT fix merged for OBS 27.0 RC4, seeking for testers.
https://github.com/obsproject/obs-studio/pull/4647

**Comment by WizardCM** [comment]
@maxdrfr Are you still seeing this issue in OBS 27.0.1?

**Comment by maxdrfr** [comment]
@WizardCM tested with 27.0.1 on Debian 10, approved, LUTs works, thanks for the fix. Free free to close this issue.

**Comment by majkrzak** [comment]
Looks like it happens again on 27.1.3 (at least on Arch)
