### ISSUE TITLE
[BUG] <Transition and Quick Transition Buttons disabled>

### ISSUE THREAD

**Issue by trickiedick** [obsproject/obs-studio#2748]
## Platform

Operating system and version: macOS 10.13.6 on iMac 27
OBS Studio version: OBS Studio 25.0.7 (64bit)

## Expected Behavior

The transition buttons should be clickable.

## Current Behavior

After clicking a transition button where both source and preview are the same (ie a non functional request to transition) , all of the transition and quick transition buttons are disabled.  They remain so. The only way to re-enable them is to perform a transition by another method, or to add another quick transition button.
## Steps to Reproduce

1. In studio or streaming mode, select a scene, 
2. Click a transition button to send it to program
3. With the same scene selected, click any transition or quick transition button again.
4. The transition buttons all become disabled. Even if another scene is selected.
![buttons enabled](https://user-images.githubusercontent.com/5082898/79643859-f1cf5700-819c-11ea-98f3-38cdb6d72c82.png)
![buttons disabled](https://user-images.githubusercontent.com/5082898/79643863-f562de00-819c-11ea-99eb-bde75dd952f9.png)

**Comment by dodgepong** [comment]
Hmm, I'm on 10.15.4 but I can't reproduce this. I can transition to the same scene over and over just fine. The buttons disable themselves during the transition, but after the transition is over, they re-enable. Possible a 10.13 issue? Can someone on 10.13 try this?

**Comment by omniskop** [comment]
The Issue also occurs on macOS Big Sur, on macOS Mojave (10.14.6) and on Windows 10 Home 2004. So it is not a macOS specific issue.

As far as I can tell it only occurs if "Duplicate Scene" and "Swap Preview/Output Scenes After Transitioning" are both disabled.
Immediately after turning these off you can transition to the same scene once and after the second transition the buttons will stay disabled, even when selecting to other scenes. You can get them back by manually moving the transition slider. After that the buttons will work again but as soon as you trigger a transition to the same scene the buttons will stay disabled again.

**Comment by gxalpha** [comment]
This does indeed require both "Duplicate Scene" and "Swap Preview/Output Scenes After Transitioning" to be disabled.
