### ISSUE TITLE
[BUG] Low audio volume on stream output

### ISSUE THREAD

**Issue by corneels** [obsproject/obs-studio#2754]
## Platform

Operating system and version: Windows 10
OBS Studio version: 25.0.4

## Expected Behaviour

When I have all my inputs coming through in the green / yellow zones on the OBS audio mixer, and the mix sounds good and loud through my monitor headphones, the expectation is that a similar volume is heard by users watching the livestream.

## Current Behaviour

When I have all my inputs (voice, instruments, audio tracks) coming through in the green / yellow zones on the audio mixer, the mix sounds good through my monitor headphones. However, when I replay the stream afterwards, the audio is very soft relative to other videos. I have to set my TV and speakers to a very high volume to reach an acceptable loudness.

## Steps to Reproduce

1. Connect audio source
2. Adjust gain to ensure audio source is playing back consistently in the yellow band in the OBS Studio audio meter.
3. Stream the video, including audio source.
5. Play back audio at same volume that monitor was set to during the broadcast. Note the lower volume of the recording.

## Additional information

Also reported by other users here: https://obsproject.com/forum/threads/obs-studio-playback-audio-too-quiet.43162/

**Comment by Fenrirthviti** [comment]
The Issues pages are not for support. Please use the forums or discord instead:

https://obsproject.com/help

This is likely an issue with your device, not OBS.

**Comment by corneels** [comment]
I understand that this might seem like a device issue, however from the forum I linked to it's clear that many other users are experiencing the same issue.

What type of issue with my device would affect the output volume from OBS into the stream?

**Comment by Fenrirthviti** [comment]
Filters, possibly. Monitoring is pre-filter/processing so it's not guaranteed to be an accurate representation of the output. A master mix that is the actual encoded output would be useful for this situation, but it's honestly not a bug in OBS, it's just how audio works. Certain drivers will not report their system volume (in the windows control panel) and present at full volume regardless to OBS, which skews the results. A lot of these issues are in WASAPI and device drivers where there is inconsistency in how they present their levels.

**Comment by corneels** [comment]
> Monitoring is pre-filter/processing
In my experience, this is not correct. When I apply a gain filter, for example, the level heard in my monitor output increases/decreases accordingly. Perhaps you're referring to something else that I'm not aware of.

> It's honestly not a bug in OBS
So is this a feature request then? How can I hear what my audience is hearing, precisely?

Another point of comparison – on my MacBook Pro, when I route audio from an application through OBS Studio (Soundflower --> OBS --> Headphones), I lose a significant amount of volume. My volume is set at 50% without routing through OBS, it's set at 90% when passing through OBS to achieve a similar volume. If this is not intended behaviour, then surely it's a bug.

**Comment by corneels** [comment]
Further, from the wiki:

> The input level are the small square indicator at the far left of the meter. This is the best place to see if the audio is too loud for the audio interface that captures your microphone.
>
>The colours have the following meters:
>
>dark green: the input level is less than -50 dBFS
light green: the input level is between -50 and -20 dBFS
yellow: the input level is between -20 and -9 dBFS
red: the input level is between -9 dBFS and -0.5 dBFS
white: the input level is larger than -0.5 dBFS
>
>If the indicator is missing it means there is no audio streaming toward OBS. This may be simply due to no audio being available yet, waiting for the user to start playback of an audio file. Or it may indicate a problem like the audio interface having been disconnected.
>
>The input level meter is before the volume fader, but it is behind any filters that are in use by a source. To correctly determine input level you will need to disable the filters for this source.

The input level meter (the square indicator) is consistently yellow/red for me (OBS Studio indicating the volume should be no higher), then my slider is set to maximum, and yet the volume on the stream is too low. Essentially there is no feasible way for the user to boost the overall volume of the output audio as OBS (in my experience) will then start clipping the audio.

**Comment by dodgepong** [comment]
Please make a post on the forums and include a log, and possibly a video of the issue. We can take a look there, and if we determine there is actually a bug, we can re-open this.
