### ISSUE TITLE
[BUG] Mixed languages in Menus

### ISSUE THREAD

**Issue by schousda** [obsproject/obs-studio#2757]
## Platform

Operating system and version: Windows 10 18363.778
OBS Studio version: 25.0.4 x64

## Expected Behavior

Menu shows all entries in the same language

## Current Behavior

Menu shows mixed languages
## Steps to Reproduce

1. select a source
2. right click on the source
![grafik](https://user-images.githubusercontent.com/21222928/79688448-b2f9d980-824e-11ea-8c97-7dfc05e850ce.png)

## Additional information

I use a Windows 10 in german, but OBS normaly is english only.

**Comment by dodgepong** [comment]
In the screenshot above, what language was OBS set to in General settings?

**Comment by schousda** [comment]
I'm very sure, i didn't change the setting, but it was set to "Azarbaycanca".
Switched it back to "English" and all is fine.
So, i'm not sure, if this is a bug from updating OBS, what i just did before, or a mistake of myself, which i didn't notice.

**Comment by dodgepong** [comment]
It might have been changed on accident, maybe by pressing a key on the keyboard that you didn't realize changed it while it was selected. Without reliable reproduction steps demonstrating a clear issue, I'm going to go ahead and close this.
