### ISSUE TITLE
[BUG] It never default to my language if I open it the first time.

### ISSUE THREAD

**Issue by laichiaheng** [obsproject/obs-studio#2758]
## Platform

Operating system and version: Manjaro Linux x86_64
OBS Studio version: 25.0.4-1

## Expected Behavior

It should use my language by default.
## Current Behavior

I am a Traditional Chinese user, but it always defaults to Simplified Chinese, I need to switch to my language manually.

## Steps to Reproduce

1. Run obs-studio.

**Comment by RytoEX** [comment]
We think this was fixed by #3038 for OBS Studio 26.0.0. If this is still a problem in OBS Studio 28.0.2 or newer, please comment with details and we can consider reopening this.
