### ISSUE TITLE
[Regression] OBS v25.0.4 prints "Aero is on" when it's off

### ISSUE THREAD

**Issue by matoi974** [obsproject/obs-studio#2765]
## Platform

Operating system and version: Windows 1909
OBS Studio version: 25.0.4; this is a regression from v24.0.3

## Expected Behavior
OBS should be able to detect whether or not Aero is enabled and print it in the log.

## Current Behavior
Using the current latest version, it always prints:
`Aero is Enabled (Aero is always on for windows 8 and above)`
v24.0.3 is unaffected by this.

## Steps to Reproduce

1. In Windows Settings > Ease of access > High contrast, enable the high contrast theme. This disables DWM/Aero.
2. Start OBS.
3. Read the log file.

**Comment by notr1ch** [comment]
Why do you think high contrast is disabling DWM? I did not see this in my testing.

**Comment by WizardCM** [comment]
Hi there @matoi974 - any answer to notr1ch's question?

**Comment by matoi974** [comment]
It seems that disabling DWM is no longer possible on recent versions of Windows 10, and I'm not entirely sure if my issue existed in the first place. Since I lack the tools to reproduce the issue again, I think it can be closed now.
