### ISSUE TITLE
OBS does not launch 

### ISSUE THREAD

**Issue by r3str0b3** [obsproject/obs-studio#2769]
## Platform
Operating system and version: Distribution: Void Linux
OBS Studio version: OBS 25.0.3_1 & 25.0.6 (linux)

## Expected Behavior
OBS setups with wizard and launches normally.

## Current Behavior
OBS stays stuck at startup

## Steps to Reproduce
1) Install OBS using package manager (Note: This installs obs 25.0.3_1)
    $ xpbs-install -S obs
2) Launch OBS
    $ obs

I also tried compiling OBS 25.0.6 from source with and without obs broswer. Followed the install instructions provided. Got exactly the same behavior.

## Additional information
This was tried with both nouveau drivers and nvidia drivers.
Took a look at issues #2655, #2347, and #2645  to look for relevant solutions. None worked.

Startup Log
> 12:41:07 AM.262: CPU Name: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
> 12:41:07 AM.262: CPU Speed: 2113.547MHz
> 12:41:07 AM.262: Physical Cores: 6, Logical Cores: 12
> 12:41:07 AM.262: Physical Memory: 16010MB Total, 7443MB Free
> 12:41:07 AM.262: Kernel Version: Linux 5.4.33_2
> 12:41:07 AM.262: Distribution: "void" Unknown
> 12:41:07 AM.262: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.8
> 12:41:07 AM.263: Portable mode: false
> 12:41:07 AM.295: OBS 25.0.6 (linux)
> 12:41:07 AM.295: ---------------------------------
> 12:41:07 AM.295: ---------------------------------
> 12:41:07 AM.295: audio settings reset:
> 12:41:07 AM.295: 	samples per sec: 44100
> 12:41:07 AM.295: 	speakers:        2
> 12:41:07 AM.298: ---------------------------------
> 12:41:07 AM.298: Initializing OpenGL...
> 12:41:07 AM.379: Loading up OpenGL on adapter NVIDIA Corporation GeForce GTX 1080/PCIe/SSE2
> 12:41:07 AM.379: OpenGL loaded successfully, version 3.3.0 NVIDIA 440.82, shading language 3.30 NVIDIA via Cg compiler
> 12:41:07 AM.386: ---------------------------------
> 12:41:07 AM.386: video settings reset:
> 12:41:07 AM.386: 	base resolution:   1920x1080
> 12:41:07 AM.386: 	output resolution: 1280x720
> 12:41:07 AM.386: 	downscale filter:  Bicubic
> 12:41:07 AM.386: 	fps:               30/1
> 12:41:07 AM.386: 	format:            NV12
> 12:41:07 AM.386: 	YUV mode:          601/Partial
> 12:41:07 AM.387: NV12 texture support not available
> 12:41:07 AM.387: Audio monitoring device:
> 12:41:07 AM.387: 	name: Default
> 12:41:07 AM.387: 	id: default
> 12:41:07 AM.387: ---------------------------------
> 12:41:07 AM.388: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
> 12:41:07 AM.453: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
> 12:41:07 AM.453: No blackmagic support
> 12:41:07 AM.458: NVENC supported
> 12:41:07 AM.458: FFMPEG VAAPI supported
> 12:41:07 AM.460: ---------------------------------
> 12:41:07 AM.460:   Loaded Modules:
> 12:41:07 AM.460:     text-freetype2.so
> 12:41:07 AM.460:     rtmp-services.so
> 12:41:07 AM.460:     obs-x264.so
> 12:41:07 AM.460:     obs-transitions.so
> 12:41:07 AM.460:     obs-outputs.so
> 12:41:07 AM.460:     obs-libfdk.so
> 12:41:07 AM.460:     obs-filters.so
> 12:41:07 AM.460:     obs-ffmpeg.so
> 12:41:07 AM.460:     linux-v4l2.so
> 12:41:07 AM.460:     linux-pulseaudio.so
> 12:41:07 AM.460:     linux-jack.so
> 12:41:07 AM.460:     linux-decklink.so
> 12:41:07 AM.460:     linux-capture.so
> 12:41:07 AM.460:     linux-alsa.so
> 12:41:07 AM.460:     image-source.so
> 12:41:07 AM.460:     frontend-tools.so
> 12:41:07 AM.460:     decklink-ouput-ui.so
> 12:41:07 AM.460: ---------------------------------
> 12:41:07 AM.460: ==== Startup complete ===============================================
> 12:41:07 AM.461: Service '' not found
> 12:41:07 AM.476: No scene file found, creating default scene
> 12:41:07 AM.476: All scene data cleared
> 12:41:07 AM.476: ------------------------------------------------

**Comment by Fenrirthviti** [comment]
Please provide a gdb backtrace of the crash. If I had to guess looks like it might be some kind of permissions issue as there are error reading the default settings.

**Comment by r3str0b3** [comment]
It doesn't crash. It stays stuck at the point indicated in the log output. As far as I know, no core file was created.

**Comment by r3str0b3** [comment]
Here is the backtrace generated by GDB. @Fenrirthviti 
[obs-backtrace.txt](https://github.com/obsproject/obs-studio/files/4512753/obs-backtrace.txt)

**Comment by notr1ch** [comment]
Looks like your pulseaudio server is blocking in a call to pulse_get_sink_info_list.

**Comment by r3str0b3** [comment]
My pulseaudio daemon wasn't working properly. Just used "sv restart pulseaudio". OBS now works. Thank you very much.
