### ISSUE TITLE
[WIKI] Problem rendering on website

### ISSUE THREAD

**Issue by miniBill** [obsproject/obs-studio#2776]
I edited the wiki to fix some formatting in the install instructions (btw, thanks @tt2468 for catching my mistake, I swapped two rows), but while it now looks fine on Github, there are some rendering issues on the website itself.

Compare:
Correctly formatted: https://github.com/obsproject/obs-studio/wiki/install-instructions#linux
Formatting broken: https://obsproject.com/wiki/install-instructions#linux

The markdown is correct, so I _guess_ it's something in the website's own markdown transformation?

**Comment by tt2468** [comment]
Was it broken before I made my change?

**Comment by miniBill** [comment]
Yes, the problem is the way I edited it is interpreted differently between the website markdown processor and the standard md processing that gh, vscode, ... do

**Comment by Warchamp7** [comment]
This looks like GitHub breaking Markdown spec? Code blocks are 4 space indents, plus another 4 spaces when in a list item

For nested list items, it's 4 spaces per nest, but GitHub seems to be fine with just 8 spaces for any nesting level

For example, I've changed a line in the macOS section here to be 12 spaces, as it's within a second level list item
![image](https://user-images.githubusercontent.com/1554753/79988009-246a9f80-847c-11ea-8a78-dd0b7949933d.png)

On GitHub, it's got 4 leading spaces as extra

On the website, it now displays correctly

![image](https://user-images.githubusercontent.com/1554753/79988228-6267c380-847c-11ea-96f6-5ee63d525dcd.png)
