### ISSUE TITLE
[BUG] Stats "Disk full in (approx.):" time overflow when available disk storage is below 900MB

### ISSUE THREAD

**Issue by russiantux** [obsproject/obs-studio#2781]
## Platform

Operating system and version: Windows 10 build 18362
OBS Studio version: 24.0.1 (64 bit)

## Expected Behavior
The "Disk full in (approx.): " stat timer should display a approximate time based off available storage and current bitrate of recording.

## Current Behavior
When available disk storage drops below roughly 900 MBs, the "Disk full in (approx.):" timer overflows to -596523 hours

## Steps to Reproduce

1. Reduce available disk space to below 900 MB while recording
2. View the stats page to see the time overflow

Image of time overflow: [https://imgur.com/a/MBis3Pj](https://imgur.com/a/MBis3Pj)

## Additional information

I noticed it when Windows gave me a notification saying that I'm low on storage while recording my screen. The time did recalculate back to a positive number after going above 1 GB of available disk storage.

**Comment by ShizuneHakamichi** [comment]
Fixed with v25, would absolutely recommend updating to the latest version.

**Comment by Fenrirthviti** [comment]
@russiantux Can you please confirm that you are testing this on v25, and if the issue is still present there? This is not an easy condition to test, unfortunately.

**Comment by russiantux** [comment]
Indeed it isn't easy to test. I did update to v25 and didn't see the issue when I tried to recreate the issue. I didn't see anything in the changelogs regarding this so I'd figured I'd make a bug report.
