### ISSUE TITLE
[BUG] CHECK_FOR_SERVICE_UPDATES seems disabled on Windows since 25.0.1

### ISSUE THREAD

**Issue by koizuka** [obsproject/obs-studio#2787]
## Platform

Operating system and version: Windows 10 (64bit)
OBS Studio version: 25.0.1, 25.0.4 (24.0.3 works fine)

## Expected Behavior

Streaming Services should be updated from https://obsproject.com/obs2_update/rtmp-services/services.json when launched the OBS Studio.
In Services in Stream tab in the Settings dialog, it should contain services added after the binary was released, such as WASD.TV and niconico.

screenshot below: OBS Studio 24.0.3(as expected).
![image](https://user-images.githubusercontent.com/864587/80106496-e624cb80-85b4-11ea-8c86-01eb54a96bfa.png)

## Current Behavior

Streaming Services only shows services which bundled with the binary(25.0.1 and 25.0.4).

screen shot below: OBS Studio 25.0.4
![image](https://user-images.githubusercontent.com/864587/80106676-22f0c280-85b5-11ea-981d-a5e65ae76dd0.png)

In contrast, it works fine on OBS Studio 24.0.3.

## Steps to Reproduce

1. launch OBS Studio.
2. click Settings - Stream - Service - Show All...
3. scroll the list to the bottom.
4. check whether some sites recently added (such as WASD.TV and niconico) exist.

**Comment by RytoEX** [comment]
We are aware of this issue and we are working to resolve it.

**Comment by notr1ch** [comment]
Resolved in 25.0.8.
