### ISSUE TITLE
[BUG] Missing scripting support for obs_sceneitem_group_enum_items()

### ISSUE THREAD

**Issue by insin** [obsproject/obs-studio#2788]
## Platform

Operating system and version: Windows 10
OBS Studio version: 25.0.4

## Expected Behavior
`obs.obs_sceneitem_group_enum_items()` should be usable when writing scripts.

## Current Behavior
`obs_sceneitem_group_enum_items()` has a similar signature to `obs_scene_enum_items()`, which [as per the docs](https://obsproject.com/docs/scripting.html#other-differences-from-the-c-api) is "implemented differently from the C API due to how callbacks work".

Trying to use it by passing in a `obs_sceneitem_t ` results in the following error in the Script Log:

```
Error in obs_sceneitem_group_enum_items expected 3..3 args, got 1
```

## Steps to Reproduce
1. Add this repro Lua script: https://gist.github.com/insin/a376b2fb52566a3e0ddf20255ac1c2d0
2. Open a scene which has a group in it
3. Pick something in the script's Source: config

Screenshot:
![obs64_1t82t4LWhw](https://user-images.githubusercontent.com/226692/80133023-f2724e00-85df-11ea-8135-5ad1c7ffc8e5.png)

**Comment by upgradeQ** [comment]
Seems that it possible to use `obs_scene_enum_items` like [this](https://github.com/midnight-studios/obs-lua/blob/6f01e2909474a99a2b5371c2f12e7e94c029f459/source-visibility-timer.lua#L130
) . [Gist](https://gist.github.com/upgradeQ/5d0112e222dc410613eace8873e85bf7) - enumerate over group items and if selected source in the one, print it.
