### ISSUE TITLE
[BUG] Group scenes swallow signal for selecting sub scene items

### ISSUE THREAD

**Issue by DDRBoxman** [obsproject/obs-studio#2794]
## Platform

Operating system and version: ALL
OBS Studio version: 25.0.7

## Expected Behavior

Parent scene should get signal that a scene item in a group has been selected

## Current Behavior

 Group scenes swallow signal for selecting sub scene items

## Steps to Reproduce

Signal handler is bound:
https://github.com/obsproject/obs-studio/blob/b35c3a21f734e6c477f23406648662e416523fce/UI/window-basic-main.cpp#L2583

Source tree calls into function to fire signal:
https://github.com/obsproject/obs-studio/blob/b35c3a21f734e6c477f23406648662e416523fce/UI/source-tree.cpp#L1378

Signal is fired:
https://github.com/obsproject/obs-studio/blob/b35c3a21f734e6c477f23406648662e416523fce/libobs/obs-scene.c#L1866

Here parent is the group scene and not the scene that contains the group, I believe this should bubble up.

**Comment by cg2121** [comment]
Fixed in #2955.
