### ISSUE TITLE
[ERROR] <Fuente de Video VLC>

### ISSUE THREAD

**Issue by Nxtfred** [obsproject/obs-studio#2802]
Saludos Cordiales, he descargado el OBS Studio vr. 25.0.4 (64 bit) para Windows, pero en fuentes  no encuentro la opción de Fuente de Video VLC, quien me podria ayudar por favor con ese problema.

Este son solo las opciones que me aparece..
![Sin título](https://user-images.githubusercontent.com/64322267/80284873-3142f980-86ef-11ea-85c8-0d22712233cf.jpg)

Gracias de Antemano....

Bendiciones

**Comment by notr1ch** [comment]
Please use the forums or Discord for support.
