### ISSUE TITLE
[BUG] <bug description>

### ISSUE THREAD

**Issue by gaetano-virgallito** [obsproject/obs-studio#2806]
## Platform

Operating system and version: MacOs 10.14.4
OBS Studio version:25.0.7

## Expected Behavior

Multiview shows the right panel order

## Current Behavior

The Preview and program panel overlaps the scene panel

## Steps to Reproduce

https://youtu.be/xtHsJp2p8OM

**Comment by dodgepong** [comment]
Fixed by https://github.com/obsproject/obs-studio/pull/2749, will be available in 25.0.8 soon.
