### ISSUE TITLE
[BUG] Logitech BRIO red color missing as soon as the properties menu is shown

### ISSUE THREAD

**Issue by depeje** [obsproject/obs-studio#2808]
## Platform
Operating system and version: Ubuntu 20.04 (also obeserved in the past in Ubuntu 19.10)
OBS Studio version: 25.0.7 (installed through the synaptic package manager, from the official ubuntu repo)

## Expected Behavior
The image produced by Logitech BRIO should have natural colors.

## Current Behavior
As soon as I open the "Properties for " a v4l2 device, the image doesn't seem to have much red anymore. In the attached log file, opening the properties window happens at line 100. As a workaround, the camera can be unplugged, and plugged back in to get realistic colors. As soon as the properties are opened, red disappears again. Note that the log file doesn't include steps 4, 5 and 6 of the "steps to reproduce". When creating this file, the webcam was preconfigured as a source.

[obsblue.txt](https://github.com/obsproject/obs-studio/files/4535827/obsblue.txt)

## Steps to Reproduce
1. Disconnect webcam
2. Open OBS
3. Connect Logitech BRIO
4. Add a new V4L2 video source
5. In the dialog, change some settings. Anything I change here doesn't trigger the bug. Just for the sake of documentation, I changed the following settings to represent a reasonable use case:
    - video format: YU12 (Emulated)
    - Resolution: 1920x1080
    - Frame rate: 30.00
6. Click OK to add the device.
7. See how the colors are realistic: 
![0_normal](https://user-images.githubusercontent.com/16429514/80313493-70567500-87eb-11ea-8316-d666d97d44f2.png)
8. Click the cog below the sources to change settings. See how most red immediately disappears from the image: 
![1_properties_opened](https://user-images.githubusercontent.com/16429514/80313547-c4615980-87eb-11ea-8a71-8ef0a41d64ec.png)

## Additional information
Here's a picture of https://en.wikipedia.org/wiki/SMPTE_color_bars#/media/File:SMPTE_Color_Bars_16x9.svg: 
![3_no_red](https://user-images.githubusercontent.com/16429514/80313579-fa064280-87eb-11ea-986e-f13badbf04e2.png)

I'm experimenting with this fork of obs-studio because I also want MJPG support: https://github.com/ggodlewski/obs-studio . It doesn't seem to have this issue, and it also lacks all the properties shown below "Color Range" in the propeties menu in my second screenshot. So I assume the issue has something to do with these settings.

While completing this report, I noticed that version 25.0.7 is the version that was shipped with ubuntu 18.10, and was still installed. I quickly "up"-graded OBS to the repository version of ubuntu 20.04, which is 25.0.3+dfgs1-2. This version behaves the same.

**Comment by notr1ch** [comment]
This looks like the white balance "auto" setting might be  off. Could you try turning it off auto and setting it to a sensible value (like 5500k)?

**Comment by depeje** [comment]
I tried. It didn't help. In fact it didn't seem to do anything. I switched off the white balance and moved the slider.

**Comment by depeje** [comment]
I tried it again, and noticed that just after I move the white balance slider, the image changes, but then over the span of a few seconds goes back to how it was. And the change doesn't seem to be white balance related, but rather brightness.

**Comment by kkartaltepe** [comment]
Use the official ppa not the debian packaging. After updating to the official ppa delete the source and re-add it. Feel free to open and provide a log if it still occurs after that.

https://obsproject.com/wiki/install-instructions#ubuntu-installation

**Comment by depeje** [comment]
Just installed version 25.0.7-0obsproject1 as per the link kkartaltepe sent. The problem still occurs, and here is the new log file according to my previously documented steps to reproduce: 
[obsblue2.txt](https://github.com/obsproject/obs-studio/files/4536023/obsblue2.txt)

Furthermore, I just tried this webcam with another program called guvcview. This program has the same image controls. In that program, manually setting the white balance temperature to 2000K yields the same image. Switching on the automatic white balance brings back natural colors.

**Comment by depeje** [comment]
With the newly installed version, I deleted the source, closed OBS, started logging the terminal and opened OBS.

**Comment by depeje** [comment]
I don't seem to have the power to re-open this ticket.

**Comment by clook** [comment]
Hi @depeje and @notr1ch,

It seems to be a bug for v4l2 bool controls: the input widget is created as a checkbox but the value is got as if it was an integer input:
https://github.com/obsproject/obs-studio/blob/master/plugins/linux-v4l2/v4l2-controls.c#L49

Since there is a type validity check that occurs at https://github.com/obsproject/obs-studio/blob/master/libobs/obs-data.c#L1656, it will always return 0, that's why the "White Balance Temperature, Auto" is always set to 0, regardless of the auto settings.

I may open a PR to submit a fix if welcome :)

**Comment by depeje** [comment]
Hi @clook,

I'm happy to test the PR when you make one :)

**Comment by wesgarland** [comment]
Any chance this has been fixed yet?  I just streamed a very blue stream by accident a couple of weeks ago; Ubuntu 20.04, OBS (not sure which, probably Ubuntu's), and a Logitech Brio. 

Linux: https://www.facebook.com/ChinaCatRiders/videos/2904445076492936/
Windows: https://www.facebook.com/ChinaCatRiders/videos/1908573072609227/

Same camera, same location. The difference is pretty striking.

**Comment by kkartaltepe** [comment]
Probably fixed by #3429

**Comment by dmusican** [comment]
I'm seeing exactly this same bug on my Lenovo Thinkpad using the built-in webcam, using Ubuntu 20.04.

**Comment by DMJC** [comment]
This is some sort of crash in the white balance as people above suggested. My camera went blue in OBS and all other camera apps, selecting the white color balance tick box did nothing to fix it. BUT. I closed OBS, opened GUVCVIEW and the camera came up blue.... until I ticked the White color balance box in GUVCView. Suddenly my camera looked normal again. Something in OBS is breaking the white color balance.

**Comment by kkartaltepe** [comment]
Are you saying this still occurs in 26.0.2?

**Comment by DMJC** [comment]
No, I've just checked the versions. Debian still has an older build than 26.0.2.

**Comment by GoPapaSmurf** [comment]
This didn't fix my problem. However, I found a fix: Launch the Logitech camera settings or Logitech Capture application *as administrator*. Change your settings, quit. Unplug and replug your USB cable. Launch the application that needs your webcam: Your settings should still be applied. My guess is that, in order to save settings, the settings application needs admin priviledges.

**Comment by enragedshoe** [comment]
> This didn't fix my problem. However, I found a fix: Launch the Logitech camera settings or Logitech Capture application _as administrator_. Change your settings, quit. Unplug and replug your USB cable. Launch the application that needs your webcam: Your settings should still be applied. My guess is that, in order to save settings, the settings application needs admin priviledges.

Can confirm that this resolved my issue. Specifically Logitech Capture, not Logitech Camera Settings.
