### ISSUE TITLE
[BUG] Stream URL Missing

### ISSUE THREAD

**Issue by rchav** [obsproject/obs-studio#2810]
## Platform
Operating system and version: Windows 10 build 18363
OBS Studio version: 25.0.4

## Expected Behavior
stream to twitch should work

## Current Behavior
I get an error message "Steam URL is missing". This did not happen on 24.0.6 (last tested version).

![urlmissing](https://user-images.githubusercontent.com/7969586/80320076-15ac2180-87c9-11ea-96d8-32a8e48a1647.png)

Forum thread: https://obsproject.com/forum/threads/stream-url-missing.118839/#post-452368

## Steps to Reproduce
Tried to stream via both stream key and account login. Same error for both. All other streaming platforms work (YouTube/Periscope). Same stream key on macOS works fine. Logs attached here: https://obsproject.com/logs/SAUGiFAYQREgdcxt

**Comment by Fenrirthviti** [comment]
The issues page is not for support requests. Please post a current log file after getting the error on the forum post. Everything is working fine here so it is an issue on your end.
