### ISSUE TITLE
[BUG] Single item group resizing can resize the source instead of the group

### ISSUE THREAD

**Issue by kkartaltepe** [obsproject/obs-studio#2812]
## Platform
Operating system and version: Linux
OBS Studio version: Head

## Expected Behavior
Resize on a group containing one source should only resize the group, and never the source.

## Current Behavior
You can independently resize the group and source when there is one item in the group.

When the group is unbound this behaves as one would expect, the group is resized to the dimensions of the source. However when the group is bounded it allows you to resize the source smaller or larger than the group but this has no effect since the group is bounded. When there is only a single source in the group it doesnt make sense to allow the user to do this no-op (that visually looks like it should work).

## Steps to Reproduce
1. Add a source
2. Add it to a group
3. Select the source in "sources". This allows you to resize the source instead of the group. When you go to resize you will see the blue boundary of the group but the red resize points of the source. If you instead have the group selected or a source outside the group selected you will only be able to get the group when resizing (and wont see the blue bounding box of the group). If you move the cursor far enough out the blue bounding box will go away and you will instead resize the group, be sure you see the blue bounding box before resizing.
4. Attempt to resize the source. Observe it seemingly behaving normally.
5. Set the group bounding to anything via transforms (or ctrl+f)
6. Re-try 3-4 and see that your resize has no visual effect.

## Additional information
floating point issues start happening if you keep resizing long enough which is kind of neat.

**Comment by Fenrirthviti** [comment]
Closing as stale. If this is still an issue please open a new issue with updated reproduction steps on the latest version of OBS.
