### ISSUE TITLE
[BUG] Vid goes blurry for every keyframe in VBR_LAT mode

### ISSUE THREAD

**Issue by TonyDong51089** [obsproject/obs-studio#2819]
## Platform

Operating system and version: Windows 10 18363.778
OBS Studio version: 25.0.8

## Expected Behavior
A constant clear video

## Current Behavior
In VBR_LAT recording mode, goes blurry for every keyframe

[2020-04-28 01-19-19.txt](https://github.com/obsproject/obs-studio/files/4541135/2020-04-28.01-19-19.txt)

## Steps to Reproduce

1.[Video example](https://github.com/obsproject/obs-studio/files/4541197/2020-04-28.01-30-00.zip)(I set the keyframe to 1sec interval, the vid goes blurry once a sec. The rate of blurry goes alone keyframe interval)

## Additional information
VBR under the same setting and CBR are perfectly fine

**Comment by TonyDong51089** [comment]
[2020-04-28 01-30-00.zip](https://github.com/obsproject/obs-studio/files/4541197/2020-04-28.01-30-00.zip)

**Comment by notr1ch** [comment]
This is not a bug. To allow low latency the encoder does not reference any data outside the GOP. For recording you should not be using bitrate constraints anyway.
