### ISSUE TITLE
[BUG] OBS generated files lack color information

### ISSUE THREAD

**Issue by CorrosiveTruths** [obsproject/obs-studio#2822]
## Platform
Operating system and version: Gentoo
OBS Studio version: obs-studio-25.0.3 portage

## Expected Behavior
Video stream / frames contain the relevant color information.

ffprobe -hide_banner -show_entries stream=color_range,color_space,color_transfer

[STREAM]
color_range=tv
color_space=bt709
color_transfer=bt709
[/STREAM]

## Current Behavior
Video stream / frames hold no color information.

ffprobe -hide_banner -show_entries stream=color_range,color_space,color_transfer

[STREAM]
color_range=unknown
color_space=unknown
color_transfer=unknown
[/STREAM]

## Steps to Reproduce
1. From scratch, dismiss the wizard.
2. Add a source, e.g. screen capture (xshm)
3. Start Recording
4. Stop Recording
5. Run ffprobe -hide_banner -show_entries stream=color_range,color_space,color_transfer,color_primaries on the resulting file.

## Additional information
Bug is cross-platform and with all Recording Formats, but worked (contained the color information) several years ago.

The problem is that players / transcoders will use 601 for SD files and 709 for HD files in the absence of color info. For example, if you run the wizard and have an HD recording with OBS's color space set to 601 (the default) you will get the wrong colours when you play back the file. You don't have to use ffprobe, vlc and other programs will not show colour information either.

**Comment by Fenrirthviti** [comment]
This is currently intentional, as setting the metadata caused just as many playback issues when players didn't respect the metadata anyway.

You can follow https://github.com/obsproject/rfcs/pull/7 for more details.

**Comment by CorrosiveTruths** [comment]
> This is currently intentional, as setting the metadata caused just as many playback issues when players didn't respect the metadata anyway.
> 
> You can follow [obsproject/rfcs#7](https://github.com/obsproject/rfcs/pull/7) for more details.

Yes, this all looks sorted now from the looks of it, with 601 no longer being the default. Thanks!

**Comment by jpark37** [comment]
It should be noted the previous failed attempt to set the 601 color space chose bt470bg, which has a very different transfer function (gamma 2.8). It would probably be best to use smpte170m instead.
