### ISSUE TITLE
[BUG] <bug description>

### ISSUE THREAD

**Issue by Obicom** [obsproject/obs-studio#2823]
Operating system and version: Windows 10
OBS Studio version: 25.0.8

## Expected Behavior
M ystandard audio output is first my earphone and second the speakers of my monitor. My Windows system sound goes to the headset if it is pluged in. If I plug out the headset it switched automaticly to the moinitor speakers. The same I would expect in OBS if I chouse in the "Audio" setting "Standard" for monitoring.   

## Current Behavior
If I start OBS with pluged in headset the sound comes from headset. If I plug out the (usb) headset the monitoring sound do not switch to the moinitor speakers as expected. (I hear nothing)

If I restart OBS the sound output switched to the correct audio output source (speakers).

**Comment by Fenrirthviti** [comment]
The issues page is not for support. Please use the Forums or Discord.

https://obsproject.com/help

**Comment by Obicom** [comment]
Sorry, but from my point of view it is a issue or better say a bug in OBS.

**Comment by Fenrirthviti** [comment]
It is not a bug, it's working as intended right now. We do not follow the default device until OBS is restarted. There is discussion on changing this behavior, but the current behavior is expected.
