### ISSUE TITLE
Whole-system freezes on OBS v25.0.8 for Mac

### ISSUE THREAD

**Issue by jamesshore** [obsproject/obs-studio#2825]
I experienced several whole-system freezes and a lockup requiring a reboot while streaming to Twitch with OBS v25.0.8 for Mac. I've streamed for several hours successfully with previous versions (25.0.6 and 25.0.7).

MacOS version 10.14.6.

Applications running:
* OBS 25.0.8
* WebStorm 2020.1
* Stay 1.2.8
* KeyCastr 0.9.2
* Terminal 2.9.5 (MacOS built-in Terminal app) running Node.js 12.16.2 (specifically `./watch.sh` from [this commit](https://github.com/jamesshore/livestream/tree/63a4f5dc68434882227502c2d6ba75a0f3e18464))
* Firefox 75.0 with multiple windows open:
    * https://en.wikipedia.org/wiki/ASCII
    * Twitch stream manager page, including preview of stream
    * Twitch chat pop-out from stream manager

Timeline of events:
* ~10:00: start OBS. Record rehearsal for upcoming stream. Experience a brief ~5 sec whole-system freeze during rehearsal.
* ~11:00: Stop recording. View recording in VLC while OBS remains open.
* 11:53: Start stream in "starting soon" scene.
* 12:00: Main part of broadcast begins.
* ~12:10: Experience 5-10 sec whole-system freeze.
* ~12:15: Whole system freezes and doesn't recover.
* Hard power-down and restart computer.
* 12:18: Restart stream.
* ~12:20: Experience several more 5-10 sec whole-system freezes.
* 12:21: Shut down stream, exit and restart OBS.
* 12:22: Restart stream.
* ~12:23: Experience several more 5-10 sec whole-system freezes.
* 12:24: Stop stream
* 12:25: Attempt to exit OBS, but it doesn't exit. Use "Force Quit" in MacOS.

I'm not sure if this is related, but OBS now appears to be corrupted. If I launch OBS and look at the "Preferences" screen, it shows an empty window.

OBS logs attached. There are no crash logs.

* [2020-04-28 10-03-54.txt](https://github.com/obsproject/obs-studio/files/4548241/2020-04-28.10-03-54.txt)
* [2020-04-28 12-17-14.txt](https://github.com/obsproject/obs-studio/files/4548242/2020-04-28.12-17-14.txt)
* [2020-04-28 12-22-16.txt](https://github.com/obsproject/obs-studio/files/4548243/2020-04-28.12-22-16.txt)

**Comment by Fenrirthviti** [comment]
Just a guess, but probably the Apple VT encoder crapping out. Can you test again on x264 and see if the same issue happens? The VT encoder is pretty terrible.

**Comment by jamesshore** [comment]
Thanks for the quick response. I'll try it later today.

FWIW, I downgraded to 25.0.6 and the "empty properties window" issue remained, even after removing ~/Library/Application Support/obs-studio. It went away after a reboot.

I've used OBS's built-in "Check for Updates" to update back to 25.0.8 and will see if I can reproduce the issue with VT encoder and x264 encoder later today.

**Comment by jamesshore** [comment]
It seems @Fenrirthviti was correct about the issue being the Apple VT encoder. I'm not sure why I didn't run into it before, but I've consistently reproduced it today:

* v25.0.8 w/ VT hardware encoder: hang after 4m40s.
* v25.0.8 w/ x264 encoder: no hang after 52m04s.
* v25.0.6 w/ VT hardware encoder: hang after 11m08s.

I think you can close this issue.

**Comment by Fenrirthviti** [comment]
Thanks for confirming. We're aware that the VT encoder isn't very stable, but honestly it's not clear if it's on our end, or Apple's. I've heard as many reports from other applications that try to use it that have similar issues that it's hard to say. We haven't had time to really dig in to it, unfortunately.
