### ISSUE TITLE
[BUG] OSX Catalina OBS crashes when selecting video capture device

### ISSUE THREAD

**Issue by joshburghardt** [obsproject/obs-studio#2826]
## Platform

Operating system and version:
OBS Studio version:

## Current Behavior
beach ball of. death

## Steps to Reproduce
open latest v of obs search for capture device then locks up

1.
2.
3.
4.

**Comment by dodgepong** [comment]
Please be sure to fill out the complete bug report template.

**Comment by Fenrirthviti** [comment]
This report is not actionable, and sounds like a support request more than anything. Please reach out on our Forums or Discord so we can take a closer look. We are not able to replicate this issue.

https://obsproject.com/discord
