### ISSUE TITLE
Cannot compile under macOS 10.15.4 - implicit declaration of function 'gzclose_w' is invalid in C99

### ISSUE THREAD

**Issue by reetpetite** [obsproject/obs-studio#2832]
## Platform
Operating system and version: macOS 10.15.4
OBS Studio version: 25.0.8

## Expected Behavior
When following the build instructions the binary should be build.

## Current Behavior
The build doesn't finish, I receive error message:
```[  5%] Building C object libobs/CMakeFiles/libobs.dir/util/profiler.c.o
/Users/.../obs-studio/libobs/util/profiler.c:1061:2: error: implicit declaration of function 'gzclose_w' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
        gzclose_w(gz);
        ^
/Users/.../obs-studio/libobs/util/profiler.c:1061:2: note: did you mean 'gzclose'?
/Library/Frameworks/libz.framework/Headers/zlib.h:1229:24: note: 'gzclose' declared here
ZEXTERN int ZEXPORT    gzclose OF((gzFile file));
                       ^
1 error generated.
make[2]: *** [libobs/CMakeFiles/libobs.dir/util/profiler.c.o] Error 1
make[1]: *** [libobs/CMakeFiles/libobs.dir/all] Error 2
make: *** [all] Error 2
```

## Steps to Reproduce
In the terminal of my Macbook I enter
1. git clone --recursive https://github.com/obsproject/obs-studio.git
2. cd obs-studio
3. brew install FFmpeg x264 Qt5 cmake mbedtls swig
4. mkdir build
5. cd build
6. cmake .. && make

**Comment by reetpetite** [comment]
Looking forward to your help

**Comment by notr1ch** [comment]
Update your system zlib, gzclose_w is from zlib 1.2.3.5 released in 2010 so your dependencies are extremely out of date.

**Comment by PatTheMav** [comment]
Small correction - on a stock macOS there should not be a `libz.framework` in `/Library/Frameworks`, so that's part of the issue. By default, OBS will use the system `libz.dylib` found in `/usr/lib`, so deleting that outdated Framework should fix this after `CMake` picks up the dylib on a new run.

**Comment by reetpetite** [comment]
> Small correction - on a stock macOS there should not be a `libz.framework` in `/Library/Frameworks`, so that's part of the issue. By default, OBS will use the system `libz.dylib` found in `/usr/lib`, so deleting that outdated Framework should fix this after `CMake` picks up the dylib on a new run.

Thanks soooo much - this did the trick. Now it works
