### ISSUE TITLE
[BUG] Recording Advanced settings show Keyframe Interval for I-Frame Codecs

### ISSUE THREAD

**Issue by alcomposer** [obsproject/obs-studio#2839]
## Platform
Operating system and version:
OS: Arch Linux x86_64 
Host: TM1701 
Kernel: 5.6.8-arch1-1 
Shell: bash 5.0.16 
DE: GNOME 
CPU: Intel i7-8550U (8) @ 4.000GHz 
GPU: NVIDIA GeForce MX150 
GPU: Intel UHD Graphics 620 

OBS Studio version: obs-studio-25.0.8

## Expected Behavior
Settings that don't relate to the currently selected codec should be greyed out and not settable.

## Current Behavior
Settings such as `Keyframe Interval` are able to be set for I-Frame codecs.

## Steps to Reproduce
1. Select Settings -> Output
2. Select Advanced Mode & Recording Tab
3. Change output to MOV container- and select an I-Frame codec (such as ProRes)
4. Keyframe Interval setting is able to be changed, and is a source of confusion for an end user. (Is OBS indeed setting keyframes? Is it a different setting? Is it a setting that has nothing to do with ProRes?)

## Additional information
![prores_keyframe_display](https://user-images.githubusercontent.com/12004932/80722148-34e6de00-8b3e-11ea-9d60-6620e6fa9422.png)

**Comment by notr1ch** [comment]
In custom output mode it is expected you know what you are doing. Given that we expose every possible ffmpeg container and codec, is it not practical to customize the UI for the thousands of possible combinations you can pick from.
