### ISSUE TITLE
[BUG] Auto-Configuration Wizard on Linux window size

### ISSUE THREAD

**Issue by superbonaci** [obsproject/obs-studio#2842]
First start of obs on Ubuntu 20.04LTS. The wizard can be resized, but by default text is cramped.

![](https://i.imgur.com/H0UhAl0.png)

**Comment by dodgepong** [comment]
I noticed this issue on macOS 10.15.4 as well.

**Comment by Fenrirthviti** [comment]
Closing as stale. If this is still an issue please open with updated reproduction steps on the latest version of OBS.

**Comment by superbonaci** [comment]
The linux flatpak version 30.2.3 is fixed. Thanks.
