### ISSUE TITLE
[BUG] Tray icon has red dot overlay even if recording fails to start

### ISSUE THREAD

**Issue by RadarNyan** [obsproject/obs-studio#2845]
## Platform
Operating system and version: Windows 7 SP1 64-bit
OBS Studio version: 25.0.8 64-bit

## Expected Behavior
Tray icon only shows red dot overlay when obs is actually recording.

## Current Behavior
If the recording fails to start, obs still shows a red dot overlay on its tray icon.

## Steps to Reproduce
1. Use "Custom Output (FFmpeg)" in Output - Recording, choose "Output Type" to "Output to URL" and leave the next field blank (so the recording is guaranteed to fail)
2. Start recording, it fails with a dialog saying "An unspecified error occurred while recording."
3. After clicking OK on the dialog, notice the tray icon now has a red dot overlay.
4. The tray icon stays in the red dot state until a successful recording is started then stopped.

**Comment by WizardCM** [comment]
This should be fixed as of https://github.com/obsproject/obs-studio/commit/4869167f5c3161a3930d5f10b1778d1b53f97d0c and I've verified that it no longer happens in 26.1.0-rc2.
