### ISSUE TITLE
[BUG] Restart a stream crash OBS Studio 

### ISSUE THREAD

**Issue by DJ-PD** [obsproject/obs-studio#2849]
## Platform
Operating system and version: Windows 10 v1909 64bit 
OBS Studio version: v25.0.8

## Expected Behavior
1. Start Streaming = start the stream (it's ok and works today)
2. Stop Streaming = stop the stream (it's ok and works today)
3. Start Streaming again after a stop = shall start the stream as task 1

## Current Behavior
1. Start Streaming = start the stream (it's ok and works today)
2. Stop Streaming = stop the stream (it's ok and works today)
3. Start Streaming again after a stop = stream doesn't start, control button "Start/Stop Streaming" is totally grey and I can't do any thing with this button. Exit OBS studio works but the program still runs in background and process task need to be ended via Windows task manager. Thereafter can OBS Studio be started and used again until next stop.

## OBS Studio part of log file when issue occur 
11:29:13.744: ---------------------------------
11:29:13.744: [FFmpeg aac encoder: 'avc_aac_stream'] bitrate: 320, channels: 2, channel_layout: 3
11:29:13.744: 
11:29:13.746: [rtmp stream: 'adv_stream'] Connecting to RTMP URL rtmp://192.168.0.174/live/...
11:29:13.750: [rtmp stream: 'adv_stream'] Interface: Intel(R) 82574L Gigabit Network Connection (ethernet, 1000 mbps)
11:29:16.507: [rtmp stream: 'adv_stream'] Connection to rtmp://192.168.0.174/live/ successful
11:29:16.514: ==== Streaming Start ===============================================
11:29:52.048: [rtmp stream: 'adv_stream'] User stopped the stream
11:29:52.048: Output 'adv_stream': stopping
11:29:52.048: Output 'adv_stream': Total frames output: 880
11:29:52.048: Output 'adv_stream': Total drawn frames: 957
11:29:52.053: ==== Streaming Stop ================================================
11:29:52.116: warning: 2 frames left in the queue on closing
11:32:28.898: [jim-nvenc: 'streaming_h264'] settings:
11:32:28.898: 	rate_control: VBR
11:32:28.898: 	bitrate:      2500
11:32:28.898: 	cqp:          20
11:32:28.898: 	keyint:       125
11:32:28.898: 	preset:       llhq
11:32:28.898: 	profile:      high
11:32:28.898: 	width:        1920
11:32:28.898: 	height:       1080
11:32:28.898: 	2-pass:       false
11:32:28.898: 	b-frames:     2
11:32:28.898: 	lookahead:    false
11:32:28.898: 	psycho_aq:    true
11:32:28.898: 
11:32:28.920: ---------------------------------
11:32:28.921: [FFmpeg aac encoder: 'avc_aac_stream'] bitrate: 320, channels: 2, channel_layout: 3
11:32:28.921: 
11:32:28.922: [rtmp stream: 'adv_stream'] Connecting to RTMP URL rtmp://192.168.0.174/live/...
11:32:28.923: [rtmp stream: 'adv_stream'] Interface: Intel(R) 82574L Gigabit Network Connection (ethernet, 1000 mbps)
11:32:28.927: HandleInvoke, error decoding invoke packet

## Steps to Reproduce
1. Start Streaming = start the stream
2. Stop Streaming = stop the stream
3. Start Streaming again after a stop = stream doesn't start

**Comment by Fenrirthviti** [comment]
When you say "crash" you just mean you can't connect anymore, or are you getting a crash dialog? If you are getting an actual crash, please provide the crash log.

**Comment by DJ-PD** [comment]
No crash dialog but the stream doesn't start and after I exit the program it still runs in the background.

**Comment by Fenrirthviti** [comment]
This appears to be an issue with your custom stream server, which is rejecting the reconnect. Not an issue on the OBS side.
