### ISSUE TITLE
[BUG] <Python error message that doesn't ocurr outside OBS>

### ISSUE THREAD

**Issue by MarioMey** [obsproject/obs-studio#2851]
## Platform
Operating system and version: Debian 10 Buster x64, Mate Desktop
OBS Studio version: 25.0.7 (compiled here)
Python version installed: 3.7.3
Python version inside OBS (by printing sys.version): 3.7.3 (default, Dec 20 2019, 18:57:59)

## Expected Behavior
I'm trying to use an script that uses [pytho-osc](https://github.com/attwad/python-osc) to send/receive OSC messages from/to OBS. python-osc example files (as they are in [README.str](https://github.com/attwad/python-osc/blob/master/README.rst)) work great when I run them in a python console. Expected behavior: Inside OBS, it should, at least, import python-osc library. But...

## Current Behavior
... at this very first line `from pythonosc import osc_server`, OBS shows this message:

> [test.py] Traceback (most recent call last):
> [test.py]   File "/home/mario/videoconfestejo/obs-scripts/OSCOBS_new.py", line 15, in <module>
> [test.py]     from pythonosc import osc_server
> [test.py]   File "/home/mario/.local/lib/python3.7/site-packages/pythonosc/osc_server.py", line 4, in <module>
> [test.py]     import asyncio
> [test.py]   File "/usr/lib/python3.7/asyncio/__init__.py", line 8, in <module>
> [test.py]     from .base_events import *
> [test.py]   File "/usr/lib/python3.7/asyncio/base_events.py", line 39, in <module>
> [test.py]     from . import events
> [test.py]   File "/usr/lib/python3.7/asyncio/events.py", line 14, in <module>
> [test.py]     import contextvars
> [test.py]   File "/usr/lib/python3.7/contextvars.py", line 1, in <module>
> [test.py]     from _contextvars import Context, ContextVar, Token, copy_context
> [test.py] ImportError: /usr/lib/python3.7/lib-dynload/_contextvars.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyContext_Type

## Steps to Reproduce
1. Install python-osc:
pip3 install python-osc
2. Create a simple script file, including only this:
from pythonosc import osc_server
3. Load it in OBS.

Now, try to run that same script in console.
## Additional information
I program some stuff in python, but I'm not a programmer. Reading the log, as I can understand, the problem is in the last file "contextvars.py"... but as I said above, this is not happening in console. So, why's the difference?

**Comment by WizardCM** [comment]
This usually means that OBS was built with a different version of Python. My guess is 3.6.x.

**Comment by MarioMey** [comment]
```
import sys
print(sys.version)
```

> [test.py] 3.7.3 (default, Dec 20 2019, 18:57:59) 
> [test.py] [GCC 8.3.0]

**Comment by Scrxtchy** [comment]
Regardless of the version of python installed on your system OBS documentation clearly states that version 3.6 is the only one supported
https://obsproject.com/docs/scripting.html

The version match is defined at compile time as swig is used for interop between C code and python

**Comment by MarioMey** [comment]
Oh, I see... anyway, it's still confuse for me. In that link, it says:

> NOTE: On windows, currently only Python 3.6 is supported. To use Python on windows, you must download and install Python 3.6.x “x86-64” for OBS 64bit (64bit is the default), or Python 3.6.x “x86” if using OBS 32bit. Then, in the scripting dialog, you must set the path to the Python 3.6.x install in the “Python Settings” tab.

"On windows"... so, what about Linux?

Also, if you say that the version mach is defined at compile time by swig... I trust you. But I didn't find any "3.6" in CMakeCache.txt :

> //Path to a file.
> PYTHON_INCLUDE_DIR:PATH=/usr/include/python3.7m
> //Path to a library.
> PYTHON_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libpython3.7m.so

¯\_(ツ)_/¯
What should I do? Maybe look for an old version of python-osc?

**Comment by Scrxtchy** [comment]
There's a paragraph or two in SWIG's documentation covering Undefined Symbol, someone will have to no doubtably chip away at the linker and see what's up 
http://www.swig.org/Doc1.3/Python.html#Python_nn9

**Comment by WizardCM** [comment]
@MarioMey Would you be able to confirm whether #3335 fixes this?

**Comment by MarioMey** [comment]
> @MarioMey Would you be able to confirm whether #3335 fixes this?

I installed PR and tested it: it works like a charm. Even I can't make this OSC code work as it should (it receives OSC messages, but for now, OBS is inoperable XD), OBS can do `import osc_server` with no errors. So, I can confirm that #3335 fixes this issue.

Thanks!

**Comment by tytan652** [comment]
Fixed by #5507
