### ISSUE TITLE
[BUG] encoder error

### ISSUE THREAD

**Issue by psyborg55** [obsproject/obs-studio#2859]
FX9830P with RX560 GPU, latest adrenaline driver 20.4.1

## Platform
Win7 x64 latest OBS, downloaded May 2 2020.

## Expected Behavior
recording starts

## Current Behavior
Dialog pops out with: An encoder error occured while recording

## Steps to Reproduce

Set advanced video setting to I420 I444 or RGB while using hardware encoder, select display capture as a source, start recording.

**Comment by Fenrirthviti** [comment]
Github issues is not for support, please use the forums or Discord instead.

https://obsproject.com/help

**Comment by psyborg55** [comment]
WTF? i report bug not ask for support

**Comment by Fenrirthviti** [comment]
There is not enough information here to be actionable. You just say "encoder error" and don't even provide the error, a log file, a screenshot, or really any information of any kind that will help us replicate. Encoders failing to start is usually not a bug, but a misconfiguration of OBS. Please go through the support channels first to validate.
