### ISSUE TITLE
OSX 10.9.5 Mavericks backward compatibility guide / tutorial

### ISSUE THREAD

**Issue by juanpc2018** [obsproject/obs-studio#2861]
the idea of writing this guide / tutorial is for people still using OSX Mavericks 10.9.5
usually owners/users of ProTools HD10.3.10 with HD Core PCIe or PCI-x hardware.
and usually MacPro4,1 or 5,1 2009 2010 2012

Latest FireFox 75.0 works, but has weird menus that must be manually disabled, procedure is on Mozilla / firefox OSX Desktop forums,
or install 74.0
Opera 49.0.2725.64
Chrome 67.0.3396.79 (Official Build) (64-bit)

To install Mavericks or any older OSX requires to unlock Date&Time Clock, and lower a few years back.
Not login to Apple Store when installing, then works OK.

OBS v19.0.2 Works, its sensitive to Audio settings in: Launchpad/Audio MIDI Setup.
Mic/input works ok no problem, 
Desktop Audio Device Configuration does Not work unless you manually select core audio driver / soundcard in: Launchpad/Audio MIDI Setup.

OBS v19.0.3-installer to OBS v20.1-installer
installs and runs, but Menu does Not allow to select any Input device. Clicking (+) makes Nothing.

OBS over >v20.1 crash when running (ignore) or (reopen).
those should work in OSX Yosemite 10.10.
but ProTools HD10.3.10 does Not.

Matrox MXO2 MAX recommended drivers for OSX Mavericks are v4.2,
for Yosemite 10.10. recomended drivers are v4.5.1 or v4.6 depends on the 3rd party software you are running. Adobe CC 6.0 or Adobe CC 7.0

there is also driver v4.5.0 unknown compatibility.

Other soundcards that work in OSX Mavericks:
Focusrite 18i20 Mk2 & Clarett8PRE USB, driver v3.4.6 or lower down to v2.2
but... Focusrite Control Panel sometimes does Not show "Empty", requires OSX Log-out & Log-in to same account, and works flawless.

LG Phone drivers + Android File Transfer work OK.

Is Not Recommended to install Mojave 10.14.6 because converts HDDs to APFS, 
Paragon APFS discontinued driver was for Yosemite 10.10
HighSierra converts SSD to APFS but Not HDDs.
recommended OSX dual boot.
Bootcamp does Not support APFS.
Using dual HDD with Mojave 10.14.6 Requires Metal GPU with Apple Boot Screen.
some video cards like GTX Titan 6GB has built in drivers in OSX since Moutain Lion 10.8. but does Not have Boot Screen, unless hardware is modified.

**Comment by Fenrirthviti** [comment]
This is not an appropriate place to post this kind of information, I would recommend submitting it as a guide on the forums.

As a side note, we no longer support 10.9, and have not for some time.
