### ISSUE TITLE
[BUG] Browser source missing from official Ubuntu packages (was @font-face not working in browser source on Linux)

### ISSUE THREAD

**Issue by nekromoff** [obsproject/obs-studio#2862]
## Platform

Operating system and version: Ubuntu 18.04
OBS Studio version: 25.0.8

## Expected Behavior
Browser source available

~~@font-face custom fonts such as woff2 or woff (or any other kind even ttf or svg) loading properly, no substitute font is used (e.g. sans-serif)~~

## Current Behavior
Browser source missing

~~@font-face custom fonts such as woff2 or woff (or any other kind even ttf or svg) not loading properly, substitute font is used (e.g. sans-serif)
HTML with custom fonts not loading fonts in OBS (Linux) browser source.~~

## Steps to Reproduce
1. Install OBS from official Ubuntu repo.

~~Create HTML with custom (local file or remote URL) fonts. 
fonts loaded correctly in common browser:
![image](https://user-images.githubusercontent.com/8550349/80927778-7080e280-8da0-11ea-8caf-a63e81128905.png)
fonts not loaded correctly in OBS browser source:
![image](https://user-images.githubusercontent.com/8550349/80927772-665ee400-8da0-11ea-9325-2f8c35435945.png)~~

**Comment by Fenrirthviti** [comment]
This is actually the wrong place to report this, you were right the first time. Closing this and reopening the other one.
