### ISSUE TITLE
[BUG] OBS Studio freezes on Wayland (Fedora 32)

### ISSUE THREAD

**Issue by dmarrazzo** [obsproject/obs-studio#2866]
## Platform
Operating system and version:
Fedora 32 64bit
installed via flatpak
Wayland session

OBS Studio version: 25.0.4 (and 25.0.8)

## Expected Behavior
Record the Wayland screen
(it used to work on Fedora 31, same context)

## Current Behavior
As I grant the screen sharing, OBS Studio freezes (even the voice meter stop moving).
After a white the operating system ask me if I want to kill the process. 

## Steps to Reproduce
1.Start OBS Studio
2.Add a source "Desktop Screencast (Wayland / X11)"
3.Grant the screen share via the gnome app

## Additional information
Log:

Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
Gtk-Message: 18:54:08.753: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:54:08.753: Failed to load module "pk-gtk-module"
Gtk-Message: 18:54:08.753: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:54:08.753: Failed to load module "pk-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /app/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/locale.ini
Attempted path: /app/share/obs/obs-studio/locale.ini
Attempted path: share/obs/obs-studio/themes/Dark.qss
Attempted path: /app/share/obs/obs-studio/themes/Dark.qss
info: CPU Name: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
info: CPU Speed: 3401.026MHz
info: Physical Cores: 4, Logical Cores: 8
info: Physical Memory: 23919MB Total, 3109MB Free
info: Kernel Version: Linux 5.6.8-300.fc32.x86_64
info: Distribution: "KDE Flatpak runtime" "5.14"
info: Window System: X11.0 - vendor string: Fedora Project - vendor release: 12008000
info: Portable mode: false
Attempted path: share/obs/obs-studio/themes/Dark/no_sources.svg
Attempted path: /app/share/obs/obs-studio/themes/Dark/no_sources.svg
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_clicked()
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_destroyed()
QMetaObject::connectSlotsByName: No matching signal for on_actionGridMode_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_program_customContextMenuRequested(QPoint)
info: OBS 25.0.4 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 44100
	speakers:        2
info: ---------------------------------
info: Initializing OpenGL...
info: Loading up OpenGL on adapter Intel Mesa Intel(R) UHD Graphics 620 (KBL GT2)
info: OpenGL loaded successfully, version 4.6 (Core Profile) Mesa 20.0.5, shading language 4.60
info: ---------------------------------
info: video settings reset:
	base resolution:   1920x1080
	output resolution: 1920x1080
	downscale filter:  Bicubic
	fps:               30/1
	format:            NV12
	YUV mode:          601/Partial
info: NV12 texture support not available
info: Audio monitoring device:
	name: Default
	id: default
info: ---------------------------------
warning: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
info: No blackmagic support
error: os_dlopen(libnvidia-encode.so.1->libnvidia-encode.so.1): libnvidia-encode.so.1: cannot open shared object file: No such file or directory

info: FFMPEG VAAPI supported
error: os_dlopen(/app//lib/obs-plugins/obs-ndi.so->/app//lib/obs-plugins/obs-ndi.so): /app//lib/obs-plugins/obs-ndi.so: cannot open shared object file: No such file or directory

warning: Module '/app//lib/obs-plugins/obs-ndi.so' not loaded
info: ---------------------------------
info:   Loaded Modules:
info:     text-freetype2.so
info:     rtmp-services.so
info:     obs-xdg-portal.so
info:     obs-x264.so
info:     obs-transitions.so
info:     obs-outputs.so
info:     obs-libfdk.so
info:     obs-filters.so
info:     obs-ffmpeg.so
info:     linux-v4l2.so
info:     linux-pulseaudio.so
info:     linux-decklink.so
info:     linux-capture.so
info:     image-source.so
info:     frontend-tools.so
info:     decklink-ouput-ui.so
info: ---------------------------------
info: ==== Startup complete ===============================================
error: Service '' not found
info: All scene data cleared
info: ------------------------------------------------
info: pulse-input: Server name: 'pulseaudio 13.99.1-rebootstrapped'
info: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_output.pci-0000_00_1f.3.analog-stereo.monitor'
info: pulse-input: Server name: 'pulseaudio 13.99.1-rebootstrapped'
info: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_input.pci-0000_00_1f.3.analog-stereo'
info: OBS XDG initialized (sender name: 1_1035)
info: Switched to scene 'Scene'
info: ------------------------------------------------
info: Loaded scenes:
info: - scene 'Scene':
info:     - source: 'Desktop Screencast (Wayland / X11)' (obs-xdg-source)
info: ------------------------------------------------
Attempted path: share/obs/obs-studio/images/overflow.png
Attempted path: /app/share/obs/obs-studio/images/overflow.png
info: [OBS XDG] Screencast session created
info: [OBS XDG] Asking for monitor…
info: adding 46 milliseconds of audio buffering, total audio buffering is now 46 milliseconds (source: Mic/Aux)

info: [OBS XDG] Monitor selected, setting up screencast
info: [OBS XDG] Starting monitor screencast…

**Comment by dodgepong** [comment]
The Flatpak is not maintained by us. Furthermore, it looks like you are capturing your screen using a [third-party plugin](https://gitlab.gnome.org/feaneron/obs-xdg-portal) that the Flatpak maintainers decided to include in the bundle, but is not part of the official project. You will need to contact the plugin's maintainer for help with your issue.

cc @GeorgesStavracas

**Comment by GeorgesStavracas** [comment]
Apologies that this ticket reached here. @dmarrazzo there's already an issue opened about it on other places.

**Comment by dmarrazzo** [comment]
Hi all, thank you for the update.
I strongly suggest the OBS team to adopt this plugin.
In fact, Wayland is the new normal for Linux.
@GeorgesStavracas can you point me where this issue is tracked so I can follow the evolution.

**Comment by GeorgesStavracas** [comment]
It's being tracked here: https://github.com/flathub/com.obsproject.Studio/issues/60

**Comment by osirase** [comment]
Just want to add this here to save people searching, as @GeorgesStavracas says, the issue is tracked there.

The problem is pipewire 0.2 vs 0.3. 

The solution is to install the flathub beta repo like this:
`flatpak remote-add flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
 flatpak install obs`
Then select the flathub beta repo when prompted. I also went with 'app/com.obsproject.Studio/x86_64/beta' as there was another repo called 'app/org.mobsya.ThymioSuite/x86_64/beta'  but I'm not sure what this is.

Hope this helps someone in the future.
