### ISSUE TITLE
[BUG] <custom stingers not playing correctly when fast switching>

### ISSUE THREAD

**Issue by ssj-tadpole** [obsproject/obs-studio#2867]
## Platform
Operating system and version: Windows10 10.0.18363 
OBS Studio version: 25.0.8

## Expected Behavior
custom stings should play on every scene change

## Current Behavior
custom stingers not playing correctly on the second scene change when switching quickly between scenes.

they play fine when the stinger is left to play until the end of its cycle and then change.
it stutters and stops if a scene change happens during the animation.

this has happened since i started using stingers (maybe version 22(??))
also happens with the normal transition dock and advanced matrix

discord discussion here
https://discordapp.com/channels/348973006581923840/374636015396192257/706911580226322502

## Steps to Reproduce
1. be on scene 1
2. switch to scene 2
3. quickly switch back to scene 1

## Additional information
myself and 2 others have the same error from the discord link above.
can provide any information in the discord if needed <3

**Comment by RytoEX** [comment]
A transition is not finished until it is finished visually. See the explanation in https://github.com/obsproject/obs-studio/issues/7219#issuecomment-1246671208.
