### ISSUE TITLE
[BUG] RTSP streams fail to reconnect after faults

### ISSUE THREAD

**Issue by johnhtodd** [obsproject/obs-studio#2878]
## Platform
Operating system and version: MacOS 10.14.6
OBS Studio version: 25.0.7

## Expected Behavior
RTSP stream should be temporarily lost and then re-connected in the event of an RTSP fault. If an RTSP source vanishes, it should be aggressively attempted for reconnection. If the user has not turned off the source, OBS should at a minimum keep trying to reconnect after a reset of the stream.

## Current Behavior
RTSP source streams currently stop for reasons that are unclear. This may be frame loss on the RTSP stream, overload on the CPU of the OBS host, or other failures. It is not clear from debugging what causes the RTSP stream to fail. Error messages are vague: "MP: av_read_frame failed: Operation timed out (-60)" but the error that causes the problem is not really the problem I'm identifying in this report. The problem is that the streams are not re-connected after a fault.

The behavior is that the RTSP stream does not restart after experiencing interruption. OBS does not reconnect to the sources, or if there are reconnect attempts they are not successful.  

Clicking on the "eye" in the source name and re-clicking (turning off/on the source) or restarting OBS  is the only way to get the RTSP streams back online. Reconnection is immediate after restart.

Logfile here: https://drive.google.com/file/d/1Cm6-UibJsAmjU_UMglp8pBVmlzcr7T16/view?usp=sharing

## Steps to Reproduce
Connect to one or two 15fps, 1080p RTSP stream, preferably Amcrest. Start stream to YouTube. Wait. One or both streams will eventually fail, possibly not at the same time, and the RTSP stream will not be automatically restarted. (Faults have been seen with single RTSP stream sources, or dual RTSP stream sources where one fails and the other does not, or where both fail eventually.)

## Additional information
I can provide more debugging or remote console if required, and am happy to test various settings or patched versions.

**Comment by johnhtodd** [comment]
Also, forgot to mention: Love OBS!  Just found it, and this is the solution to a lot of things that have been rolling around in my head for years on how to appropriately mix/edit/notate my security camera array that doesn't expose the backend systems. We might even use it for some national-level DNSSEC key ceremony management in the future, which requires public viewing of our security platform plus framed scenes and text. If this problem gets sorted out, it'll do everything I want!

**Comment by Yohox** [comment]
the fork can solve it
https://github.com/Yohox/obs-studio/tree/feature-ffmpeg-source-reconnect

**Comment by johnhtodd** [comment]
Thanks for the pointer and the fixes! But compiling my own might take days or never, based on what I'm sure is very probably a large dependency chain and my having zero time recently. Sadly, I am reduced to just fetching pre-compiled packages these days given time constraints.

Is there a plan to merge whatever changes you made in the branch back into the main OBS code base for future releases?

**Comment by Yohox** [comment]
i have taken a pr last night, but i don't know what time offical merge the pr.
