### ISSUE TITLE
[BUG] OBS automatically deactivates an audio input capture source

### ISSUE THREAD

**Issue by alejandroasa** [obsproject/obs-studio#2881]
## Platform

Operating system and version: Windows 10 Versión 1909
OBS Studio version: 25.0.8 (64bit)

## Expected Behavior

Keep active the audio input capture source
## Current Behavior

After some time, the audio input capture gets deactivated automatically. And I cant set active again.
## Steps to Reproduce

1. Add an input audio capture. (In my case an USC mic Blue Snowball). Check it in the mixer that get input signal.
2. Add it to a scene.
3. Wait some time (30 mins aprox.)
4.Then the source is not listed in the mixer, and go to Advanced Audio Properties and the source is with Inactive Status

## Additional information

The source is using a VST plugin filter (Reastream standalone) in order to receive audio from a DAW.

**Comment by WizardCM** [comment]
Could you post a log after reproducing the issue? Help -> Log Files -> Upload Current Log and post the link below.

**Comment by alejandroasa** [comment]
Hi!. There isnt a log file in the crashes folder.

**Comment by WizardCM** [comment]
Sorry for the confusion & the super late reply. I don't need a crash log - just a session log when the issue has been reproduced. My guess is the source is being hidden, either via a hotkey or a third party connection (like a websocket or a streamdeck).

**Comment by WizardCM** [comment]
Hi there, reminder to provide a session log.

**Comment by WizardCM** [comment]
As a session log has not been provided, I am closing this. If a session log is posted below in reply, I will reopen this ticket.
