### ISSUE TITLE
[BUG] Recording to an MP4 or a MOV file causes freezes in the video if the storage is slow

### ISSUE THREAD

**Issue by carbn** [obsproject/obs-studio#2883]
## Platform
Operating system and version: Windows 10 Pro 10.0.18362
OBS Studio version: 25.0.8 (64bit)

## Expected Behavior
Recorded files should be smooth regardless of the format and storage used.

## Current Behavior
When a recording is saved on a network drive and the format is set to MP4 or MOV the resulting video has frequent freezes/skipped frames. When the format is changed to FLV the resulting video is smooth without any dropped frames.

## Steps to Reproduce
1. Configure the recording path to be on a network drive
2. Set the recording format to MP4
3. Set the encoder to the new NVENC (not sure if this is needed)
4. Record gameplay for ~30secs
5. Observe that the resulting video will have frequent freezes. I got one every ~4 seconds.

## Additional information
Previous discussion about the issue where a slow HDD causes encoding overload can be found here: https://obsproject.com/forum/threads/encoding-overload-is-tied-to-hdd-speed.113120/
It does not mention that changing the format has an effect on this. It seems that all output formats that are passed through ffmpeg have this problem, though I only tested MP4 and MOV.

Here's an obs-studio log from different test recordings: https://funkd.org/~samu/obs-studio-log.txt
(check the file header for more information)

**Workaround**: set the recording format to FLV

**Comment by notr1ch** [comment]
Please give #5717 a try to see if it resolves this.

**Comment by gxalpha** [comment]
This is likely fixed by #5717.
