### ISSUE TITLE
Hotkeys for replay stop without warning

### ISSUE THREAD

**Issue by fefo-dev** [obsproject/obs-studio#2885]
My bound hotkeys, normally mic, camera and replay, just stop working without verifiable cause. I noticed this problem about 2 weeks ago, still on OBS 25.0.1, and it persists on the latest version.

It happened today midstream, despite minimal interaction with the program. Here's the log:
https://pastebin.com/e0AVvwGP

From 21:16 to 22:34 no replay was created and no info logged, despite me using the feature latter. At a point I clearly remember creating a replay through OBS UI, but no video was created. I'll track the exact point and add it latter.

Hotkeys tested, with no change in behaviour: `Ctrl+/`, `Ctrl+Alt+;`, `'`, `OBS_KEY_0xC2` (numpad dot for pt-br keyboard), `OBS_KEY_VK_MEDIA_PLAY_PAUSE`.
Replay buffer settings: 512MB for 60s at 1280x720.

Hotkey used for other functions (mic/camera source toggle) also stop working.

**Comment by WizardCM** [comment]
Please fill out the issue template.

**Comment by fefo-dev** [comment]
**Platform**

Operating system and version: Windows 10 17763.1158
OBS Studio version: 25.0.8 (64bit)

**Expected Behavior**

Hotkeys should reproduce the attributed action when said key is pressed

**Steps to Reproduce**

No reproducible pattern; the issue appears and disappears without user interaction.

**Additional information**

Logfile of the session: https://pastebin.com/e0AVvwGP
As previously said, in this session the issue happened latter between 21:16 and 22.34, with no replay saved despite using the replay hotkey. More details on the opening post

**Comment by danieljimenez** [comment]
I have this problem if I have task manager in focus, OBS hot keys do not seem to work while Task Manager is the focused app.

**Comment by Fenrirthviti** [comment]
This appears to be a support request. Hotkeys may not work on windows if the active window is running in a different context or blocks hotkeys from other applications. Please use the support forums or Discord for further assistance, as there is not enough information to replicate this.

**Comment by fefo-dev** [comment]
The issue is still present in the latest release, and it's can be reproduced on my end by opening OBS, setting a easy to check shortcut like mute mic, applying the changes and testing without change in focus. The shortcut will not work until after a few minutes and may break without alert during usage. Opening and closing Settings without any change is guaranteed to break shortcuts for a while.

A thread was created in the main forum previous to this: https://obsproject.com/forum/threads/hotkeys-stop-working-at-will-and-cant-be-reenabled.121241/#post-456288

**Comment by Fenrirthviti** [comment]
I am entirely unable to replicate this issue on my system using version 25.0.8 on Windows 10 build 2004. Hotkeys work fine in any situation I am testing. Until there are clear replication steps that are repeatable on multiple systems, there is not going to be a whole lot we can do. If we can't replicate, we can't fix it. We need absolute clear and repeatable steps.
