### ISSUE TITLE
Choppy recordings / streams after updating to 25.x

### ISSUE THREAD

**Issue by QiwTV** [obsproject/obs-studio#2892]
## Platform
Windows 10 (1909)
OS Build: 18363.778

OBS Studio version: 25.0.8

## Expected Behavior
Streaming / recording without regular freezes every 1-4 seconds.

## Current Behavior
Getting regular freezes after updating to the latest version, it's like clockwork and it does not seem to be related to the settings i have used. I get the same issues regardless, OBS does not seem to keep up with the FPS selected under video, if 60 fps is selected its running at 52.1 fps in the bottom right even before recording or streaming.

## Steps to Reproduce
I'm not sure how to even reproduce this, it's constant for me regardless if i just did a fresh restart of the computer and any other steps i have tried so far.

## Additional information
As you can see from the log file its around 14% dropped frames due to encoding lag / stall.
[Recording Lag Log 20200509.txt](https://github.com/obsproject/obs-studio/files/4603518/Recording.Lag.Log.20200509.txt)

**Comment by RytoEX** [comment]
Github Issues is not for support.  Please use the forums or Discord instead.

https://obsproject.com/help
