### ISSUE TITLE
[BUG] Problem With Browser

### ISSUE THREAD

**Issue by ShayanSlash** [obsproject/obs-studio#2894]
Hello, In last version I have problem with browser source, I have a website for showing donate alert, and I use socket.io for this, in previous versions its work great but in the last version, 3 or 4 times browser work ( show donate alert )  perfectly but after then, The browser shows nothing ! if I send 100 times more donate its get nothing ! just black screen! 99% I think browser block socket.io  after a few requests!

**Comment by unknowndomain** [comment]
When you complete a bug report there is a pre-entered format for a reason it, helps the developers understand what your issue, what platform etc... please could you update your issue with the information:

```
<!-- READ THIS FIRST -->
<!-- The OBS Studio GitHub issue tracker is **ONLY** to be -->
<!-- used for reporting Bugs that have replication steps. -->

<!-- You can post Feature Requests here: https://ideas.obsproject.com/ -->
<!-- Get help for Support Issues here: https://obsproject.com/help -->

<!--- Provide a general summary of the issue in the Title above -->

## Platform
<!-- Please fill out the following information about your bug report. -->
<!-- If you are on Linux and installed using a package, please list the package type. -->
Operating system and version:
OBS Studio version:

## Expected Behavior
<!--- Tell us what should happen -->

## Current Behavior
<!--- Tell us what happens instead of the expected behavior. -->
<!--- Please include a log file here if possible. -->

## Steps to Reproduce
<!--- Provide a link to a live example, or an unambiguous set of steps to -->
<!--- reproduce this bug. Include code to reproduce, if relevant. -->
<!--- Screenshots and video are encouraged if applicable. -->
1.
2.
3.
4.

## Additional information
<!--- Not obligatory, but provide any additional details or information -->
<!--- that you feel might be relevant to the issue -->
```

**Comment by Fenrirthviti** [comment]
Please use the forums or Discord for support. The issues pages are reserved for verified and replicable bugs.

https://obsproject.com/help
