### ISSUE TITLE
[BUG] DeckLink Quad HDMI generates black frames in preview & recording on Linux

### ISSUE THREAD

**Issue by LGCW** [obsproject/obs-studio#2899]
## Platform
Operating system and version: Debian Linux 10 (buster) kernel 5.4.39.
OBS Studio version: 25.0.7-98 self compiled.

## Expected Behavior
No flickering in preview or recorded video when recording 2160p 60 source.

## Current Behavior
1 to 3 black frames in preview and recorded video when recording 2160p 60 source.
Log: https://obsproject.com/logs/0Ajn9wRmu6TLdvpk
Video: https://www.youtube.com/watch?v=IlUiEEbzjzk

## Steps to Reproduce
1. Add source Blackmagic device.
2. Select Decklink Quad HDMI Recorder.

## Additional information
Tested with Decklink API 11.1 & 11.5.1

OBS does not have this issue with the DeckLink Mini Recorder 4K, Intensity Pro 4K, or Intensity Pro.

I have observed occasional black frames when recording 4 1080p 60 sources with the DeckLink Quad HDMI but only twice.

Media Express can preview and capture 1080 & 2160p 60 video without issue. 

Seeing high number of memory leaks when the DeckLink Quad HDMI is activated and recording and sometimes only when activated with 1080p sources.

**Comment by LGCW** [comment]
Strace output https://pastebin.com/iHyHPsaF

**Comment by walterav1984** [comment]
The flickering is actual a black frame or not? On our decklink duo2 recently they started showing up on ubuntu-mate 20.04 with default kernel 5.4 and desktopvideo software 11.5. I did recently set the aspm=off to try if it fixes the erratic input/output assignement  since the card can operate in 4x in or 4x out or any combination, maybe this is a side effect or since a recently 5.4 kernel upgrade... 

Could you test "BMD mediaexpress" and see if the flickering/blackframes also come up there since in our situation its also affected so it looks like?

**Comment by LGCW** [comment]
The flickering appears to be a black frame. I keep pci=noaer pcie_aspm=off set in Grub because Threadripper. 

I have tested it with both enabled and it was the same issue. This was on both 4.19 and 5.4 using Debian 10.4.

Media Express can preview and capture 1080 & 2160p 60 video without issue. 

It's a mystery since the DeckLink Mini Recorder 4K, Intensity Pro 4K, and Intensity Pro all works in the same box without issue.

**Comment by walterav1984** [comment]
Is Desktop video Setup consistently working for you, as in it always shows your Quad HDMI card and can configure parameters and save them for you?

Have you tested [shotcut](https://shotcut.org/) and or [nageru](https://nageru.sesse.net/) to see if they capture fine without blackframes?

**Comment by LGCW** [comment]
Desktop Video works as expected. Unlike previous BlackMagic devices the DeckLink Quad HDMI has no configurable parameters in Desktop video Setup. 

The device functions as expected with Media Express. No, I have not tested the device with  shotcut and or nageru.

**Comment by LGCW** [comment]
Blackmagic confirmed today that there is an issue with the Decklink HDMI Quad on Threadripper systems. 

A fix is in the works.

**Comment by LGCW** [comment]
Almost a year later Blackmagic responded with a fix. Disable IOMMU in the BIOS or toss amd_iommu=off in GRUB. 

Yes, it works.

**Comment by walterav1984** [comment]
Thanks for sharing this!
