### ISSUE TITLE
[BUG] Installation Error: Failed to create aac streaming encoder (simple output)

### ISSUE THREAD

**Issue by E3V3A** [obsproject/obs-studio#2901]
I was trying to install this according to the [webpage](https://obsproject.com/forum/resources/obs-virtualcam.539/) instructions, for a Windows 8.1 machine. However, I keep getting the following error:

![obs64_2020-04-20_23-38-53](https://user-images.githubusercontent.com/194392/79799635-74a20e80-8363-11ea-8acf-c69b194312fa.png)

I reported this here: 
* https://github.com/CatxFish/obs-virtual-cam/issues/103

Now, I know I already have the codecs in my system because VLC any many other players and encoders work with AAC, except OBS. 

**So how and where is OBS looking and testing for this encoder?**

--- 

I've also seen the crappy [solution here](https://obsproject.com/forum/resources/obs-studio-enable-coreaudio-aac-encoder-windows.220/) which tell you to install Apple QuickTime crap, which I decided a decade ago, to never do again, because of all the bloat and registry changes associated with that. 

So why isn't there a simple solution using already available and up-to-date encoders?  
Such as those listed here:

* https://www.winxdvd.com/resource/aac-codec.htm
* https://www.videohelp.com/software/sections/audio-encoders
* https://sites.google.com/site/qaacpage/cabinet
* https://github.com/mstorsjo/fdk-aac

In addition MS pages state that the AAC codecs are already installed on Windows... 
So what the heck is going on?

**Comment by Fenrirthviti** [comment]
The error isn't exactly accurate, it's a bit of a red herring. The problem is that loading the ffmpeg deps fails, because virtualcam ships with its own deps that conflict with OBS. I have corrected this problem and provided a working installer for it here: https://github.com/Fenrirthviti/obs-virtual-cam/releases/tag/2.0.5

**Comment by E3V3A** [comment]
@Fenrirthviti  Awesome! But have you file a PR with that Repo or is it abandoned? We never heard from CatxFish again...

**Comment by Fenrirthviti** [comment]
@E3V3A As far as I know CatxFish has been inactive and unresponsive for months, so I would consider it abandoned for now.
