### ISSUE TITLE
[BUG] OBS on macOS Catalina does not request required permissions to perform Window Capture

### ISSUE THREAD

**Issue by unknowndomain** [obsproject/obs-studio#2902]
## Platform
Operating system and version: macOS 10.15.4 (All versions of Catalina are affected)
OBS Studio version: OBS 25.0.8 (All versions of OBS Are affected)

## Expected Behavior
When first using Window Capture it should prompt for permission from the operating system.

## Current Behavior
OBS doesn't request permission to use the macOS Screen Recording API which means it can only Window Capture it's own windows and `Dock.app` (the Desktop + the Dock).

## Steps to Reproduce
1. Quit OBS
2. Use terminal to reset OBS Screen Recording permissions to simulate a new user `tccutil reset ScreenCapture com.obsproject.obs-studio`
3. Launch OBS
4. Add a Window Capture (do not do Display Capture first).

You will see that there are windows but most are missing:
<img width="1142" alt="Screenshot 2020-05-09 at 23 05 10" src="https://user-images.githubusercontent.com/147143/81485991-8af80780-9249-11ea-84a0-5fda2e5d1858.png">

## Work around
1. Add a Display Capture Source
2. Follow the usual operating system steps to approve OBS permission including restarting OBS
3. Edit the Window Capture settings and you'll see the windows are back.

## Additional information
This can be resolved by requesting Screen Recording permissions from macOS when you use the Window Capture, it would solve a recurring support issue where users go straight to Window Capture and are not able to tick the box in System Preferences.

## Credit
Thanks to Aberads on Discourse for originally finding this.

**Comment by Fenrirthviti** [comment]
I believe @PatTheMav has some ideas on how we can better assign these permissions in a more transparent way. We've known about this since Catalina launched.

**Comment by unknowndomain** [comment]
It would make sense to have a wizard or an addition to the auto-configuration.

**Comment by PatTheMav** [comment]
It's not really my idea, someone else on the team has already a first-launch dialog in mind that - similar to other apps - checks permissions and contains shortcuts for people to set/approve them.

So it's definitely on the radar, but not implemented yet. In the meantime it seems that checking the "show windows with empty names" checkbox adds all current windows to the dropdown and selecting one of them triggers the permission notice.

**Comment by energizerfellow** [comment]
> It's not really my idea, someone else on the team has already a first-launch dialog in mind that - similar to other apps - checks permissions and contains shortcuts for people to set/approve them.

I agree that there needs to be a first-launch dialog that's both way more extensive and (much) more strongly encourages running of the autoconfig workflow. On macOS check for things like permissions and on Windows things like outdated GPU drivers, multi-GPU setups, webcam conflicts, etc.  Having a pull-down list or checkbox that defaults to running the checks/autoconfig on first launch so when people instinctively click "Yes"/"OK" by muscle memory to a pop-up, they'll be guided through the checks and autoconfig workflow.

Probably a good idea to save if the autoconfig has been ran and OBS will on-launch ask about running autoconfig every launch or every few launches until autconfig has run to completion or the user manually selects the ignore future requests option.

I like the idea of a pull-down with options worded like "Setup Wizard" and "Base Defaults (not recommended)" with the setup checks being default and the Defaults option changing the UI text to something about OBS being unconfigured and running setup checks being recommended. I'd also avoid the literal words "OK"/"Yes" and instead use words like "Run Checks" and "I understand" for the autoconfig/defaults, respectively.

**Comment by PatTheMav** [comment]
At least for macOS something like this is now common UI: 

![image](https://user-images.githubusercontent.com/9436503/81595154-480d6f80-93c2-11ea-9585-1ca68fd87ef5.png)

Also some apps provide a drag&drop icon for the same purpose:

![image](https://user-images.githubusercontent.com/9436503/81595224-683d2e80-93c2-11ea-82a1-5d85585ac7b2.png)

**Comment by unknowndomain** [comment]
That second one unfortunately wouldn’t work with the screen recording permission sadly.

**Comment by PatTheMav** [comment]
@unknowndomain True, but those screenshots aren't representative of what we need to build for OBS, just to get the general idea across.

**Comment by chengkeke366** [comment]
I also encountered this problem, how to solve it ？

**Comment by offthegrid-mike** [comment]
@chengkeke366 Here is the work around, you can try it.

1. Add a Display Capture Source
2. Follow the usual operating system steps to approve OBS permission including restarting OBS
3. Edit the Window Capture settings and you'll see the windows are back.

**Comment by dossy** [comment]
I don't know if this is still an issue?  I just tested with OBS 26.1.2 on macOS 10.15.7 Catalina and I received the following window:

![image](https://user-images.githubusercontent.com/65378/121644451-00dc2d00-ca61-11eb-8e12-854db7562c3b.png)

**Comment by WizardCM** [comment]
@dossy What we've noticed is that occasionally that dialog will appear _behind_ the OBS window without the user seeing it, which makes the flow unpleasant and unexpected.

**Comment by dossy** [comment]
@WizardCM Yeah, it's not a great user experience, but I'd say that this isn't exactly a bug in OBS, but a deficiency in macOS's UI/UX?  I suppose a helper modal dialog guiding the user into their System Preferences to grant Screen Recording access might help alleviate some new user confusion.

**Comment by dodgepong** [comment]
A more ideal solution would be a first-run onboarding process that would guide the user through accepting these permissions.

**Comment by dossy** [comment]
@dodgepong That sounds like a great enhancement request that should probably be fleshed out in a separate issue, though?  As far as the "bug" is concerned in this issue, it seems more like an OS limitation in how it presents the permission authorization UI to the user, which OBS has no control over.

**Comment by dodgepong** [comment]
Sure. Honestly I'm not sure why this is still open, as it's more of a feature request than a bug at this point. Would be a better candidate for an RFC.
