### ISSUE TITLE
[BUG] resizing window leaves "invalid/not-drawn" (preview) area

### ISSUE THREAD

**Issue by sim590** [obsproject/obs-studio#2904]
# Platform

* Operating system and version:

        No LSB modules are available.
        Distributor ID:  Debian
        Description:     Debian GNU/Linux bullseye/sid
        Release:         testing
        Codename:        bullseye

  I do use the [Awesome Window Manager][awesome]

* OBS Studio version: `OBS Studio - 25.0.3+dfsg1-2 (linux)`
* Debian package: `25.0.3+dfsg1-2`

[awesome]: https://awesomewm.org/

## Expected Behavior

Resizing the window under any circumstance should not disable OBS from drawing certain areas of the screen when it is told to draw on this very area by the window manager.

## Current Behavior

The window leaves "not-drawn" areas on the screen. More precisely, it's the preview screen that is not drawn where it should. These areas are free for OBS to draw and its window size given by the window manager indicates that it should draw there, but it doesn't.

Here, I linked a screenshot of the bug:

![bug](https://user-images.githubusercontent.com/4147254/81487834-7ad32e80-922f-11ea-8a4a-097522027461.png)

Here is what the screen should look like (after workaround applied):

![pasbug](https://user-images.githubusercontent.com/4147254/81487854-b5d56200-922f-11ea-97a0-74578060966f.png)

## Steps to Reproduce

1. (For best perspective) resize the window width to the 3rd or 4th of the screen. Up to now, it's fine.
2. Right-click the preview area and choose `Windowed Projector (Preview)` and close the window projector window right away.
3. Now resize the width of the screen from the 3rd or 4th to the maximum of the width of your screen and notice the areas not drawn by the OBS window.

**(sort of) WORKAROUND**

It is possible to work around this by right-clicking the preview screen and choosing `Full Screen (Preview)` option, then closing that with `escape` key.

## Additional information

Here is a live video demonstrating the issue:

https://vimeo.com/416778256

Notice in this video that there were some areas below the preview area and above the bottom menu where it was not drawn also. The issue of this last detail may be linked to the issue described in this ticket.

**Comment by dodgepong** [comment]
Where did you get the Debian package from that you used to install this?

**Comment by kkartaltepe** [comment]
We dont support debian packaging, consider installing from source and seeing if the issue is fixed.

Otherwise it looks like a bug in your window manager not reporting resizing correctly (considering I cannot replicate it nor have we had any other reports about this).

**Comment by sim590** [comment]
> Where did you get the Debian package from that you used to install this?

From the official repository. Here are the official sources for the package:

```
obs-studio:
  Installé : 25.0.3+dfsg1-2
  Candidat : 25.0.3+dfsg1-2
 Table de version :
 *** 25.0.3+dfsg1-2 900
        900 http://ftp.ca.debian.org/debian testing/main amd64 Packages
        800 http://ftp.ca.debian.org/debian unstable/main amd64 Packages
        100 /var/lib/dpkg/status
     22.0.3+dfsg1-1 600
        600 http://ftp.ca.debian.org/debian stable/main amd64 Packages
```

> We dont support debian packaging, consider installing from source and seeing if the issue is fixed.

I will consider it.

> Otherwise it looks like a bug in your window manager not reporting resizing correctly (considering I cannot replicate it nor have we had any other reports about this).

It could be due to my window manager, I agree. I will link this issue to the issue bug tracker of AwesomeWM.

**Comment by kkartaltepe** [comment]
Considering you are on debian its likely your WM will also tell you stop using ancient packages before filing a bug report.

**Comment by sim590** [comment]
> will also tell you stop using ancient packages before filing a bug report.

Well, 25.0.3 is not that old... It's just from 2 months ago. I categorize that as a relatively late version.

Also, filling up bug reports for bugs that can't be found in your bug tracker is a good and productive thing which will prevent other people from searching and creating other bugs related to this. Plus it lets me link this bug cleanly to the primary suspected responsible project.

@kkartaltepe : Your attitude of sermonizing people that help find bugs is little discomforting.

**Comment by kkartaltepe** [comment]
Im not sure what you think is sermonizing, its typically good manners to ensure you test on the latest version of code before claiming a bug is upstreams fault for any package. I suppose i didnt notice you were on sid as most debian bug reports come from stable. Though trying to remember the code names for every linux out there is more or less a futile task.

**Comment by Fenrirthviti** [comment]
As an additional note, the repo you listed is not official for OBS. We only provide packages via the Ubuntu PPA right now. If this can be replicated on 25.0.8 built from source, please reply and I will reopen this. I cannot replicate this issue on my Debian system (using XFCE), though, so it appears to be an environment issue and not one with OBS.

**Comment by sim590** [comment]
@Fenrirthviti: I have run my window manager in Xephyr and I don't experience trouble like in plain X. See the video:

https://vimeo.com/417348712

I don't know why, but it demonstrates that it the issue may not be in my window manager after all, but at some lower level may be? Anyway, I don't think that the issue should be reopened for now. I'll update if I can find an answer.
