### ISSUE TITLE
[BUG] Windows Graphics Capture 'client area' crash.

### ISSUE THREAD

**Issue by lindenkron** [obsproject/obs-studio#2905]
## Platform
Operating system and version: Windows 10, Home 64-bit (10.9, Build 18363)
OBS Studio version: 25.0.8

## Expected Behavior
Not to crash.

## Current Behavior
Crashes.

## Steps to Reproduce
1. Add 'Windows Capture'
2. **Important** Select application (Open Firefox/Chrome - Select twitch and any streamer. I had theater mode on).
3. Select Windows Graphics Capture (Windows 10 1903 and up)
4. Check/Uncheck Client Area rapidly

## Additional information
Seems to happen easier on heavier Scene Collections. At least how I ran into it, and thought I couldn't reproduce the steps until I spam clicked it.

Does **not** crash with youtube videos.

**Comment by WizardCM** [comment]
Please provide the crash report. Help -> Crash Reports -> Upload Last Crash Report and post the link.

**Comment by RytoEX** [comment]
I am currently unable to reproduce this crash with OBS Studio 25.0.8 64-bit on Windows 10 1903 Home 64-bit.

**Comment by lindenkron** [comment]
It simply crashed. Did not create a crash report. I reproduced it 10 times in a row to test for youtube video/browser. On a fresh scene collection (was also crashing in my own scene collection)

Now that I tried to make it crash again it refuses. I've changed nothing in the last 5 minutes since posting this, but watching a stream. Nothing further to add at this point, if I manage to figure out why I'll reply here.

**Comment by lindenkron** [comment]
> The program obs64.exe version 25.0.8.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
>  Process ID: 46ac
>  Start Time: 01d6269f33223845
>  Termination Time: 16
>  Application Path: C:\Program Files\obs-studio\bin\64bit\obs64.exe
>  Report Id: 1945864b-b690-492e-be04-f7b11af75e16
>  Faulting package full name: 
>  Faulting package-relative application ID: 
>  Hang type: Unknown

Doesn't really help much. I just restarted OBS - tried the steps again and it crashed. 

'Upload latest log file'
https://obsproject.com/logs/iknEfhY4_iDOm77k

**Comment by notr1ch** [comment]
Also unable to reproduce here, the dump would be useful to figure out what's causing this.

**Comment by notr1ch** [comment]
After examining the dump file, OBS gets stuck shutting down the WinUI capture in an RPC call to the local CaptureService service. Examining the dump of svchost hosting CaptureService revealed no obvious stuck threads though.

**Comment by lindenkron** [comment]
Thanks for taking the time R1CH. This problem seems rather sporadic, sometimes I can reproduce with above steps 10 times in a row. And sometimes it refuses to occur at all.

It's not a super crucial crash (seeing as it only happened cus I accidentally clicked 'client area 3 times in a row') and spending any more time on it over more important things is probably not worth it.

**Comment by Del-B** [comment]
Hi, I'm also having the same issue over multiple computers.

It seems to when I switch scenes. And doesn't happen if I use "Automatic" or "BitBlt". It does take some time before it crashes. I can reproduce it too.

Here is the crash log.

Thanks!

[Crash_2020-07-04_15-31-05.txt](https://github.com/obsproject/obs-studio/files/4873046/Crash_2020-07-04_15-31-05.txt)

**Comment by WizardCM** [comment]
Is this still an issue with latest nightly? It contains a lot of extra checks for WGC stability.

**Comment by WizardCM** [comment]
@lindenkron Please confirm if this is still an issue in OBS 26.1.0-rc2.

**Comment by WizardCM** [comment]
Closing due to lack of response. Happy to reopen if it's still a problem.
