### ISSUE TITLE
[BUG] OBS Crashes when making changes to audio filters.

### ISSUE THREAD

**Issue by SMHanley** [obsproject/obs-studio#2909]
Repeatedly crashes when trying to modify or remove an audio filter.

## Platform
Operating system and version: Windows 10 1909
OBS Studio version: OBS 25.0.8 64 Bit

## Expected Behavior
Should not crash

## Current Behavior
Crashes

## Steps to Reproduce
Currently 3 filters.  If I ty to modify one or remove one.  OBS Crashes.

**Comment by Fenrirthviti** [comment]
Can you please provide the crash log, and a normal log? I am not able to replicate this.

**Comment by SMHanley** [comment]
[Crash 2020-05-12 23-09-59.txt](https://github.com/obsproject/obs-studio/files/4619624/Crash.2020-05-12.23-09-59.txt)

**Comment by SMHanley** [comment]
Here is the thread I mentioned.
https://obsproject.com/forum/threads/crash-when-removing-or-moving-audio-filters.119129/#post-454445

**Comment by WizardCM** [comment]
What filters/VSTs do you have installed? The crash is occurring deep in Qt's code when trying to update the UI to reflect the removed filter.

**Comment by WizardCM** [comment]
OK, had someone on Discord reproduce the issue. Turns out it only happens on the built-in **Acri** theme, and other third party themes.

**Comment by RytoEX** [comment]
We believe that this has been fixed through a combination of changes to Acri and bug fixes to both our UI and obs-vst components. If this is still an issue, please comment, and we can consider reopening this.
