### ISSUE TITLE
[BUG] Duplicating a Group corrupts transforms of entries, the groups size, and more

### ISSUE THREAD

**Issue by Xaymar** [obsproject/obs-studio#2913]
## Platform

Operating system and version: Windows 10 2004
OBS Studio version: 25.0.8

## Expected Behavior
Duplicating a group should result in an identical copy of it.

## Current Behavior
The duplicated group is filled with nonsense. Contained sources are all over the place. Transforms for content are somewhat merged with the groups transform instead of being unique to each entry.

## Steps to Reproduce

1. Create a group with multiple sources.
2. Assign different transforms to each of them.
3. Copy the group.
4. Paste the group as a duplicate.
5. Enjoy the mess.

**Comment by Bennik2000** [comment]
I was not able to reproduce this issue. 

Things I tried to reproduce this: 
1. Create a Group
2. Add color sources to it 
3. Transformed each source (translated/scaled/rotated)
4. Copied the group
5. Added the group as duplicate

This is the (expected) result I got: 

![grafik](https://user-images.githubusercontent.com/8039939/81611693-c7f40380-93db-11ea-9f67-086e06bb755a.png)


Did you do anything special? What sources did you use?

**Comment by Xaymar** [comment]
The sources I used were Source Mirror from StreamFX and Media Source for the original repro, but I've reproduced it with Media Source, Video Capture Source and Image Source as well now. The latter case is actually just my webcam overlay with stock OBS filters on them (Chroma Key).

The exact setup for the latter one is:
- Group with bounding box set to base resolution, maximum size scaling, aligned to bottom right.
  - Media Source for the background video. Transform set to offset by 30x30, bounding box set to 480x270, fit outer, center. Locked.
  - Video Capture Device for the webcam. Transform set to offset by 30x30, bounding box set to 480x270, fit outer, center. Locked.
  - Image Source for a final overlay to smooth out the edges. Transform left alone as it is in the correct size.

Duplicating the group caused all of the underlying transforms to freak out. Not even copying the transform from the other working elements to the new references worked. The size for the group was stuck at some insane size that matched nothing contained in it.

Edit: Also please make sure that you clicked Copy and then Paste (Duplicate) not Paste (Reference).

**Comment by Xaymar** [comment]
I seem to be unable to repro this in 26.x, so I'm closing this.

**Comment by WizardCM** [comment]
That's good to hear, although I don't think anything in this area was changed.
