### ISSUE TITLE
[BUG] It is possible to move "locked" entries into groups and corrupt the transform

### ISSUE THREAD

**Issue by Xaymar** [obsproject/obs-studio#2914]
## Platform

Operating system and version: Windows 10 2004
OBS Studio version: 25.0.8

## Expected Behavior
Locked items should not be movable into groups.

## Current Behavior
Locked items can be moved into groups, which changes their transform.

## Steps to Reproduce

1. Lock an item.
2. Move it into a group.
3. Move it out of the group.
4. Enjoy the mess.

**Comment by WizardCM** [comment]
As broken as groups can be, just tested this in 26 RC2, I was unable to reproduce this bug with the specified steps.

I tried with an image that I dragged into a newly created group, and then back out. I also tried with a second image source once the first was in the group.

**Comment by Xaymar** [comment]
Did you also _lock_ the item? I should probably have added to the steps that you actually need to set a custom transform, and that the change to the transform is usually small, but sometimes explodes into value differences of 100 or more, depending on where the origin of the group is.

**Comment by Xaymar** [comment]
Retesting this on the Github Actions 26-rc2 build, I seem to be unable to reproduce it following the exact original steps and any variations I have recorded. Most likely this was fixed.

**Comment by Xaymar** [comment]
Original test case: [26.0.0rc2-issue2914.zip](https://github.com/obsproject/obs-studio/files/5197794/26.0.0rc2-issue2914.zip).

1. Extract it somewhere
2. Extract OBS portable binaries next to it (config directory must be on the same level as bin, data and obs-plugins).
3. Launch 'launch.bat'.
4. Try moving the locked item into the group and out of it, and watch if the transform stays the same or is modified.
