### ISSUE TITLE
[BUG] picture of file media not showing when starting OBS

### ISSUE THREAD

**Issue by galuel** [obsproject/obs-studio#2920]
## Platform

Operating system and version: Ubuntu 18.04
OBS Studio version: 25.0.8 (official ppa:obsproject/obs-studio )

## Expected Behavior

I use a mp3 media source in a scene, that shows automatically a picture of the album ( Tryad : https://tryad.bandcamp.com/ ). The mp3 media picture should be fully visible when starting OBS

## Current Behavior

When starting OBS the mp3 media picture shows only very tiny lines - pixels of the picture (seems not to be there, but I can see pixels of it).

When just checking "properties" of the mp3 media source, and click "ok" (not changing anything), then the picture appears correctly. I need to do the same for any OBS start to see the picture.

## Steps to Reproduce

1. Add Tryad mp3 media source in a OBS Scene : https://tryad.bandcamp.com/
2. Check the picture of the mp3 appears in the screen
3. Close OBS
4. Start OBS, the mp3 picture doesn't appear, but only tiny lines of it...

Starting OBS : 

![OBS](https://user-images.githubusercontent.com/5245398/81746086-2c7b9500-94a6-11ea-9fff-1aec25739b58.jpg)

After Tryad album -> properties -> ok (not changing the path at all, nothing else but ok !) : 

![obs2](https://user-images.githubusercontent.com/5245398/81746251-6e0c4000-94a6-11ea-835a-b8fbfcb687b6.jpg)

**Comment by Fenrirthviti** [comment]
Please fill out the issue template, you have not provided enough information for this to be actionable.

**Comment by galuel** [comment]
I did fill all necessary information to reproduce the bug + screen captures before / after.

**Comment by Fenrirthviti** [comment]
Not filling out the template means that we have to hunt for the information in the request. Please update the original post to follow the template. Failure to do so may mean this request is overlooked for others who are able to follow our process.

**Comment by galuel** [comment]
@Fenrirthviti I did update the issue adding and filling the template.

**Comment by WizardCM** [comment]
I am unable to reproduce this with OBS 25.0.8 on Ubuntu 20.04 and Windows 10. Could you include a log of the session where this happened (Help -> Log Files -> Upload Current Log)?

**Comment by WizardCM** [comment]
@galuel Please provide the session log, as requested in my previous comment.

**Comment by galuel** [comment]
I can't reproduce it with OBS 26.0.2

**Comment by WizardCM** [comment]
Even better, thanks for checking!
