### ISSUE TITLE
[BUG] UI elements can cause crash when OBS exits

### ISSUE THREAD

**Issue by tt2468** [obsproject/obs-studio#2923]
## Platform

Operating system and version: Ubuntu 19.10
OBS Studio version: 24.0.7-90 (built from source)

## Expected Behavior
No crashes or errors in log.

## Current Behavior
I can cause OBS to either throw errors in the log saying `Failed to fetch parent window geometry!` or say errors and cause a core dump.

## Steps to Reproduce

So I tested for a long time, and I could not find a method that causes a core dump every time. It's very odd. But here is a method that seems to bring out the issues a good part of the time:
1. Use a terminal to open `obs`
2. Do 2 times: Click the "Settings" button in the control widget, then click the (x) in the corner.
3. Enable studio mode
4. Play around with the t-bar a bit, leaving it in the middle and also doing a full transition
5. Disable studio mode
6. Click the (x) in the top right corner of OBS and it will usually throw errors into your terminal about window geometry and such.

## Additional information

Here is a log: https://obsproject.com/logs/A_VvNa3mZQBDhgrn
Sometimes it will throw errors but stay alive enough to fully shut down, other times it appears to be too much for OBS to handle and it does a full crash
[crash.txt](https://github.com/obsproject/obs-studio/files/4618687/crash.txt)

**Comment by dodgepong** [comment]
What version of Qt did you use to build this?

Can you try on the latest 25.0.8 tag?

**Comment by tt2468** [comment]
Using QT 5.12.4 according to `qmake --version`

Tested a bunch of times. I wasnt able to get a crash. The only errors that appeared were ```
error: X Error: BadDrawable (invalid Pixmap or Window parameter), Major opcode: 130, Minor opcode: BadWindow (invalid Window parameter), Serial: 7083
error: X Error: BadDrawable (invalid Pixmap or Window parameter), Major opcode: BadIDChoice (invalid resource ID chosen for this connection), Minor opcode: 0, Serial: 7085```

Which appeared on the first runtime

**Comment by kkartaltepe** [comment]
Please provide an actual gdb backtrace. The provided (ubuntu crash handler?) crash.txt does not include stacks, nor do we have symbols for your build.

**Comment by tt2468** [comment]
@kkartaltepe I would try, but I simply cant get it to crash anymore for some reason. It still throws the errors though on occasion, and sometimes it hangs on them for a few seconds before the normal OBS shutdown stuff happens.

**Comment by tt2468** [comment]
Closing this since it seems to be a desktop environment bug and not an OBS issue. Will reopen if it becomes a large issue.

**Comment by kkartaltepe** [comment]
Your crash.txt has a core dump encoded in it. If you can figure out how to extract it you can use that and your compiled obs (for the symbols) to extract a backtrace.
