### ISSUE TITLE
[BUG] Media Source CPU usage increases if other processes are also using Disk resources

### ISSUE THREAD

**Issue by Xaymar** [obsproject/obs-studio#2925]
## Platform

Operating system and version: Windows 10 2004
OBS Studio version: 25.0.8

## Expected Behavior
Media Source CPU usage should stay constant and not increase when other processes are also using disk resources.

## Current Behavior
When other processes are also using disk resources, Media Source CPU usage shoots up to 10x the original usage. This can be observed by simply compiling a program on an SSD - a task which barely uses 5% of a PCIE M.2 SSD and causes Media Source to increase CPU usage by 10x, causing it to fully load 8 out of 16 physical cores on my system (16 out of 32 threads).

## Steps to Reproduce

1. Add a Media Source.
2. Point it at any video file, I used a H.264 High444 VBR file, 2560x1440@120fps.
3. Enable loop, restart playback when source becomes active, show nothing when playback ends.
4. All other options do not matter.
5. Start compiling OBS Studio for example.

### Updated test case from 2020-09-09
* Test Case: [26.0.0rc2-issue2925.zip](https://github.com/obsproject/obs-studio/files/5197833/26.0.0rc2-issue2925.zip)
* Video File for Media Source: https://drive.google.com/file/d/1MNWgsJfNkPvDhMGLVvUV6GdE4d4SOHGz/view?usp=drivesdk
1. Extract test case somewhere.
2. Extract OBS Studio binaries next to the test case (config must be on the same level as bin, data and obs-plugins).
3. Launch using 'launch.bat'.
4. Modify all Media Sources to point at the downloaded video file (or your own).
5. Copy anything onto any disk (or start encoding to disk).

[Video Example](https://xaymar.com/private/obs-studio/issue/2925/20200909-example.mp4)

## Additional information
The disk itself is mostly unused by OBS Studio, yet for some reason this causes Media Source to completely freak out. In fact it is so unused by OBS Studio that the disk usage report is 0%: 
![image](https://user-images.githubusercontent.com/437395/81759230-6c517500-94c4-11ea-82f9-0a4a97964b5c.png)

**Comment by Xaymar** [comment]
Current workaround: Move files to flash storage that isn't integrated in your PC. That seems to solve the problem, somehow.

**Comment by DrunKev** [comment]
Is there any update on this issue? For people with just 1 storage drive, do any of the media source properties options help alleviate the CPU usage or does it not matter?

**Comment by Xaymar** [comment]
Grab a USB stick, it works. All that matters is that _only_ OBS uses it.

**Comment by WizardCM** [comment]
I was unable to reproduce this myself with 26 RC1 and a 12GB 8 hour 720p h264 video and a variety of tasks, including compiling a clean OBS build and using UltraSearch.

**Comment by Xaymar** [comment]
I'm easily able to reproduce this with the exact given steps in the OP. It's easier to reproduce with files on the same disk as where OBS Studio is writing a log file.

**Comment by Xaymar** [comment]
Reproduced on the Github Actions build of 26-rc2.

* Test Case: [26.0.0rc2-issue2925.zip](https://github.com/obsproject/obs-studio/files/5197833/26.0.0rc2-issue2925.zip)
* Video File for Media Source: https://drive.google.com/file/d/1MNWgsJfNkPvDhMGLVvUV6GdE4d4SOHGz/view?usp=drivesdk

1. Extract test case somewhere.
2. Extract OBS Studio binaries next to the test case (config must be on the same level as bin, data and obs-plugins).
3. Launch using 'launch.bat'.
4. Modify all Media Sources to point at the downloaded video file (or your own).
5. Copy anything onto any disk (or start encoding to disk).

[Video Example](https://private.xaymar.com/obs-studio/issue/2925/20200909-example.mp4)

**Comment by Xaymar** [comment]
Updated the OP with improved test steps, and an example video of it happening. The effect is more clearly visible when compiling where OBS Studio will suddenly struggle to maintain 10 FPS as long as a Media Source is active.

**Comment by Xaymar** [comment]
Closing as requested.
