### ISSUE TITLE
[BUG]  window-capture WGC cann't restore after process reboot

### ISSUE THREAD

**Issue by wangshaohui1314** [obsproject/obs-studio#2928]
## Platform

Operating system and version: WIN10 64
OBS Studio version: 25.0.X

## Expected Behavior

after UWP reboot, window capture can restore normally

## Current Behavior

after UWP reboot, WGC won't try to restore again because _wc->previously_failed_ is true

## Steps to Reproduce

1. run calculate.exe
2. add WGC capture depond on calculate.exe (captured normally)
3. exit calculate.exe (here, _previously_failed_ will be set with true because find another window and fail to init WGC)
4. reboot calculate.exe (here, WGC won't try to reset again even we find out new window)
4. check preview of this source (the captured video is incorrect)

## Additional information

This issue can be fixed as below:
![clipboard](https://user-images.githubusercontent.com/18413354/81806734-7ec4c080-954f-11ea-8ac7-403fc9a7f25f.png)

**Comment by wangshaohui1314** [comment]
@jpark37  Please confirm it, thanks.

**Comment by WizardCM** [comment]
@wangshaohui1314 Can you confirm this merged PR doesn't fix the issue? https://github.com/obsproject/obs-studio/pull/2880

**Comment by wangshaohui1314** [comment]
> @wangshaohui1314 Can you confirm this merged PR doesn't fix the issue? #2880

This pr has been merged 6 days ago. However, I was testing with latest code 4 hours ago. 
So I think it has not been fixed.

**Comment by WizardCM** [comment]
Good to know. Please update your original report with a link to the specific commit from the master branch that you've tested with for clarity.

**Comment by wangshaohui1314** [comment]
> Good to know. Please update your original report with a link to the specific commit from the master branch that you've tested with for clarity.

Do you mean to provide the branch which inludes my recommended logic ?
Maybe this logic should be confirmed by @jpark37

**Comment by WizardCM** [comment]
No, from the master branch, where you were able to reproduce the bug, as this is a bug report.

**Comment by wangshaohui1314** [comment]
> No, from the master branch, where you were able to reproduce the bug, as this is a bug report.

It can be reproduced with master branch at this point:
https://github.com/obsproject/obs-studio/commit/42bbca3d4ba2330c8c3a905c153d39a090403757

**Comment by notr1ch** [comment]
A semi related issue it seems, if the window to capture is minimized when OBS is started, it is unable to be captured (tested on both on master and this branch).

Repro steps:
Run calculator, add window capture for it. Close OBS, minimize calculator, restart OBS.

`18:37:33.219: CreateForWindow (0x80070057): The parameter is incorrect.`
