### ISSUE TITLE
[BUG] window-capture-WGC Preview of wgc-window will stay in incorrect resolution after window is iconic

### ISSUE THREAD

**Issue by wangshaohui1314** [obsproject/obs-studio#2932]
## Platform

Operating system and version: win10 64
OBS Studio version: master branch at this point : 42bbca3d4ba2330c8c3a905c153d39a090403757

## Expected Behavior

Preview of wgc-window should stay in correct resolution

## Current Behavior

Preview of wgc-window will stay in incorrect resolution after minimizing captured window

## Steps to Reproduce

1. open chrome
2. add window source with WGC for chrome, choosing "client-area"
3. minimize chrome and restore chrome
4. simetimes, preview of source will stay in incorrect resolution after (3)
 (attached recorded video)

## Additional information

Reason: when the last frame arrived, resolution of chrome window has been changed as iconic state.
I guess this issue can be fixed as below:
![1589439268](https://user-images.githubusercontent.com/18413354/81902541-d7996500-95f2-11ea-9c34-127682da4800.png)

It is better to invoke IsIconic() after get_client_box(), to make sure client_box is normal.

**Comment by wangshaohui1314** [comment]
[obs-2932.zip](https://github.com/obsproject/obs-studio/files/4626551/obs-2932.zip)

@jpark37   Please confirm it, thanks.

**Comment by jpark37** [comment]
I have an unmerged PR to deal with minimized WGC captures, #2908.

**Comment by wangshaohui1314** [comment]
> I have an unmerged PR to deal with minimized WGC captures, #2908.

In your pr, I find it is checking (client_rect.right > 0) && (client_rect.bottom > 0). 
In my situation, its resolution is 288x37, will that commit fix this situation ? If yes, I will close this issue.
![2020-05-14 15;21;59](https://user-images.githubusercontent.com/18413354/81905220-01548b00-95f7-11ea-9e19-4fd3733d221e.PNG)

**Comment by wangshaohui1314** [comment]
> I have an unmerged PR to deal with minimized WGC captures, #2908.

I verified that commit, this bug is reproduced.

**Comment by jpark37** [comment]
I forced pushed a couple IsIconic checks. Let me know if you can still reproduce.

**Comment by wangshaohui1314** [comment]
> I forced pushed a couple IsIconic checks. Let me know if you can still reproduce.

it is fixed now, good job.
Should I close this issue ?

**Comment by jpark37** [comment]
No, it will automatically be closed when the changes are merged.

**Comment by notr1ch** [comment]
A semi related issue it seems, if the window to capture is minimized when OBS is started, it is unable to be captured (tested on both on master and this branch).

Repro steps:
Run calculator, add window capture for it. Close OBS, minimize calculator, restart OBS.

`18:37:33.219: CreateForWindow (0x80070057): The parameter is incorrect.`

**Comment by jpark37** [comment]
#2908 has been updated to address the minimized Calculator case. I tested non-UWP apps as well for regressions, but UWP behavior is weird and awful, and I wouldn't be surprised if I added another bug somehow.
