### ISSUE TITLE
[BUG] Crash on start

### ISSUE THREAD

**Issue by anonymix007** [obsproject/obs-studio#2934]
## Platform
qt5ct: using qt5ct plugin
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/locale.ini
Attempted path: /usr/share/obs/obs-studio/locale.ini
Attempted path: share/obs/obs-studio/themes/Dark.qss
Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
info: CPU Name: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
info: CPU Speed: 4337.443MHz
info: Physical Cores: 6, Logical Cores: 12
info: Physical Memory: 32103MB Total, 2225MB Free
info: Kernel Version: Linux 4.19.0-8-amd64
info: Distribution: "LMDE" "4"
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.4
info: Portable mode: false
qt5ct: D-Bus global menu: no
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_clicked()
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_destroyed()
QMetaObject::connectSlotsByName: No matching signal for on_program_customContextMenuRequested(QPoint)
info: OBS 0.0.1 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 44100
	speakers:        2
info: ---------------------------------
info: Initializing OpenGL...
obs: Fatal IO error 22 (Invalid argument) on X server :0.

GPU: Nvidia GTX 1030
CPU: i7-8700K

## Expected Behavior
Being able to run OBS without fatal errors

## Current Behavior
Crash on start

## Steps to Reproduce
1.Install on LMDE via apt
2.Try to run

##Additional info
logs:
05:38:25 PM.218: CPU Name: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
05:38:25 PM.218: CPU Speed: 4400.137MHz
05:38:25 PM.219: Physical Cores: 6, Logical Cores: 12
05:38:25 PM.219: Physical Memory: 32103MB Total, 2195MB Free
05:38:25 PM.219: Kernel Version: Linux 4.19.0-8-amd64
05:38:25 PM.219: Distribution: "LMDE" "4"
05:38:25 PM.219: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.4
05:38:25 PM.220: Portable mode: false
05:38:25 PM.234: OBS 0.0.1 (linux)
05:38:25 PM.234: ---------------------------------
05:38:25 PM.234: ---------------------------------
05:38:25 PM.234: audio settings reset:
05:38:25 PM.234: 	samples per sec: 44100
05:38:25 PM.234: 	speakers:        2
05:38:25 PM.240: ---------------------------------
05:38:25 PM.240: Initializing OpenGL...

(other log files are the same, no crashes folder exists in ~/.config/obs-studio/)

**Comment by notr1ch** [comment]
LMDE is not an officially supported distribution, please contact the package vendor for support.
