### ISSUE TITLE
[BUG] Audio capture from AverMedia GC553 appears to encounter a buffer issue

### ISSUE THREAD

**Issue by KateLibC** [obsproject/obs-studio#2935]
## Platform

Operating system and version: macOS 10.15.4
OBS Studio version: 25.0.8 (mac)

## Expected Behavior

Audio passed via HDMI capture from an AverMedia Live Gamer Ultra (GC553) should just pass right through as an audio device like any other. It should play audio normally at whatever volume, through whatever filter, et cetera. 

## Current Behavior

After a period of time usually either as little as five minutes, usually at 20 minutes, and sometimes after 1.5 hours, the audio will cease to function, leaving the audio track just looping a second of audio on repeat.

Video continues to work just fine.

This appears to rear its ugly head usually when streaming directly to Twitch although I haven't had a chance to catch this when I record to disk as I typically do not do that. It doesn't get captured on stream but you can catch it in monitor mode.

Here is a video of what monitor mode catches:
https://youtu.be/f0HtMdYUvMo

When reading my logs, it appears to be a buffer issue:
16:15:56.591: adding 46 milliseconds of audio buffering, total audio buffering is now 116 milliseconds (source: Mic/Aux)
16:15:56.591: 
16:15:56.671: adding 69 milliseconds of audio buffering, total audio buffering is now 185 milliseconds (source: Mic/Aux)
16:15:56.671: 
16:15:56.750: adding 92 milliseconds of audio buffering, total audio buffering is now 278 milliseconds (source: Mic/Aux)
16:15:56.750: 
16:15:56.828: adding 69 milliseconds of audio buffering, total audio buffering is now 348 milliseconds (source: Mic/Aux)
16:15:56.828: 
16:15:56.907: adding 92 milliseconds of audio buffering, total audio buffering is now 441 milliseconds (source: Mic/Aux)
16:15:56.907: 
16:15:56.965: adding 46 milliseconds of audio buffering, total audio buffering is now 487 milliseconds (source: Mic/Aux)
16:15:56.965: 
16:15:57.046: adding 92 milliseconds of audio buffering, total audio buffering is now 580 milliseconds (source: Mic/Aux)
16:15:57.046: 
16:15:57.122: adding 69 milliseconds of audio buffering, total audio buffering is now 650 milliseconds (source: Mic/Aux)
16:15:57.122: 
16:15:57.196: adding 69 milliseconds of audio buffering, total audio buffering is now 719 milliseconds (source: Mic/Aux)
16:15:57.196: 
16:15:57.269: adding 69 milliseconds of audio buffering, total audio buffering is now 789 milliseconds (source: Mic/Aux)
16:15:57.269: 
16:15:57.345: adding 92 milliseconds of audio buffering, total audio buffering is now 882 milliseconds (source: Mic/Aux)
16:15:57.345: 
16:15:57.424: adding 69 milliseconds of audio buffering, total audio buffering is now 952 milliseconds (source: Mic/Aux)
16:15:57.424: 
16:15:57.500: adding 69 milliseconds of audio buffering, total audio buffering is now 1021 milliseconds (source: Mic/Aux)
16:15:57.500: 
16:15:57.583: Max audio buffering reached!
16:15:57.583: adding 23 milliseconds of audio buffering, total audio buffering is now 1044 milliseconds (source: Mic/Aux)

## Steps to Reproduce

1. Configure AverMedia device as audio device 1
2. Stream to Twitch or any other service
3. Wait for the VU meter to demonstrate a repeating pattern
4. Check to see if "Max audio buffering reached!"

This will either happen immediately as it did in this case or it happens after a random period of time. Restarting OBS resolves the problem.

**Comment by WizardCM** [comment]
You shouldn't be using capture card audio devices directly, but rather use them as part of the Video Capture device source.

Disabling timestamps may potentially fix this edge case (Click the ⚙gear for the device in the Audio Mixer -> Properties), but we also have some special handling for Avermedia audio in the Video Capture Device source that is likely better suited.

In future, please use the Discord for support requests. http://obsproject.com/discord
