### ISSUE TITLE
[BUG] DRI devices are not persistent across reboots and should not be used to identify GPUs

### ISSUE THREAD

**Issue by marmistrz** [obsproject/obs-studio#2936]
## Platform
Operating system and version: Arch Linu
OBS Studio version: OBS Studio - 25.0.8-1 (linux)

## Expected Behavior
If there are several GPUs available at a host machine (e.g. dual GPU laptops, Intel+AMD/Intel+Nvidia), the same physical GPU should be used for encoding with ffmpeg-vaapi. Currently the same `/dev/dri/renderDXXX` device is used for encoding instead. 

The mapping of physical devices to `/dev/dri/renderDXXX` is not persistent across reboots, so some other information about the devices should be used to identify it instead.

**Comment by Fenrirthviti** [comment]
Do you have a suggestion on what else should be used? Is there a way to consistently identify graphics devices across reboots?

**Comment by kkartaltepe** [comment]
Doesnt look like there is any persistent mapping to DRI devices. Maybe the best thing available currently is to identify devices by PCI slot.

**Comment by marmistrz** [comment]
You can use `/dev/dri/by-path/` for instance `/dev/dri/by-path/pci-0000:00:02.0-render`.

**Comment by RarogCmex** [comment]
I can confirm it with Intel hd 530/amd radeon rx 560.

**Comment by carlocastoldi** [comment]
Any intention to work on this? Shouldn't be too difficult to point to `/dev/dri/by-path/` rather then `/dev/dri/`, is it?
combine it with `lspci | grep ' VGA '` and we even get the actual name for each of the available cards!

**Comment by kkartaltepe** [comment]
I dont believe anyone is actively working on it, it is a good issue for anyone wanting to  start with contributing though.
