### ISSUE TITLE
OBS logs the current working directory instead of path to pixel shader on errors

### ISSUE THREAD

**Issue by skeletonbow** [obsproject/obs-studio#2938]
## Platform

Operating system and version:  Windows 10/x64 (1909)
OBS Studio version: 25.0.8

## Expected Behavior

When a pixel shader fails to load and OBS writes an error to the log file, it should write a log entry that shows the full explicit path to the shader file in order to facilitate tracking down pixel shader bugs.

## Current Behavior

When a pixel shader fails, OBS writes out an entry that shows the name of the current working directory that OBS launched from instead of the path name pointing to the shader file, which I concluded is probably a bug as the CWD is not useful information for the log entry.

https://obsproject.com/logs/oV1hbIXEv4A_Ej3y

## Steps to Reproduce

1.  Load a pixel shader into OBS which contains an error.
2.  When it fails to load, look at the OBS log file and you'll see the CWD printed in the log instead of the explicit pathname of the shader file that failed to load.

## Additional information

11:16:05.371: device_pixelshader_create (D3D11): Compiler warnings/errors for  (Pixel shader, technique Draw, pass 0):
11:16:05.371: C:\Program Files\obs-studio\bin\64bit\ (Pixel shader, technique Draw, pass 0)(82,54): error X3000: syntax error: unexpected token ')'

**Comment by skeletonbow** [comment]
19:56:43.471: device_pixelshader_create (D3D11): Compiler warnings/errors for  (Pixel shader, technique Draw, pass 0):
19:56:43.471: C:\Program Files\obs-studio\bin\64bit\ (Pixel shader, technique Draw, pass 0)(19,12-36): warning X3206: implicit truncation of vector type
19:56:43.471: C:\Program Files\obs-studio\bin\64bit\ (Pixel shader, technique Draw, pass 0)(48,58-64): error X3000: unrecognized identifier 'asdfadf'
19:56:43.471: 
19:56:43.471: Pass (0) <> missing pixel shader!
19:56:43.471: [obs-shaderfilter] Unable to create effect. Errors returned from parser:
19:56:43.471: (None)

**Comment by Fenrirthviti** [comment]
I see you're using the shaderfilter plugin, which is not something we directly support. Please report this issue to the plugin developer.

**Comment by skeletonbow** [comment]
Yes, I had asked in Discord prior to filing the bug report to determine if it would be an issue in OBS or not and was suggested to file it here.  Someone else tracked the problem down to a presumed bug in Shaderfilter, I'll move it over there.  Thanks.
