### ISSUE TITLE
[BUG] NV12 texture format is falsely reported as "not available" if color format isn't NV12

### ISSUE THREAD

**Issue by matoi974** [obsproject/obs-studio#2943]
## Platform

Operating system and version: Windows 10 Pro 1909 64-bit
OBS Studio version: 25.0.8

## Expected Behavior
NV12 texture support reported accurately

## Current Behavior
NV12 texture support inaccurately reported as unavailable, even on systems that do have it available (log says: `NV12 texture support not available`)

## Steps to Reproduce

1. Set color format to I420, I444 or RGB
2. Restart OBS
3. Help > Log files > Show current log file

**Comment by energizerfellow** [comment]
Do you have the OBS logs from any systems from where this is a known issue?

**Comment by Gol-D-Ace** [comment]
I don't think it's a false report in this case.

If you set the color format to anything but NV12 the features that make use of NV12 textures aren't working.

NV12 could potentially be available but isn't in this circumstance.

**Comment by Gol-D-Ace** [comment]
OBS is running a test for NV12 textures and  that one is probably failing?

**Comment by Gol-D-Ace** [comment]
If the color format isn't set to NV12 the encoders that can use NV12 textures (like Jim NVENC) will not work.

The message might be a bit inaccurate but it isn't entirely wrong.

At the time you see that message in the log Encoders that use NV12 textures will not work.

**Comment by Fenrirthviti** [comment]
This message isn't inaccurate, it is referring to the NV12 texture support not NV12 itself.

Not a bug.
