### ISSUE TITLE
[BUG] GC573 Not allowing higher then 60fps input in OBS

### ISSUE THREAD

**Issue by bensam123** [obsproject/obs-studio#2945]
## Platform
Windows, current x64 version

## Expected Behavior
Higher then 60fps options should be selectable from the drop down menu under the video capture device.

## Current Behavior
Either OBS only has access up to 60fps options or currently only supports up to 60fps input despite the device having access to a 240hz input on the card and RECentral allowing 240fps capture.

## Steps to Reproduce
1. Install GC573 Live Gamer 4k
2. Select correct resolution and refresh on client computer
3. Add the device
4. Look at drop down menu for FPS in OBS

## Additional information
There has never been a greater then 60fps input from this card inside of OBS and has been discussed in a few different places, despite it being advertised as higher then that.

https://www.reddit.com/r/AverMedia/comments/eiihxz/avermedia_4k_gc573_not_ingesting_1080p_240_fps/

**Comment by Fenrirthviti** [comment]
This is likely a limitation of their DirectShow drivers. It sounds like their RECentral app is not accessing the device through DirectShow like it is through OBS. This is something they would need to expose on their end before OBS can support it. We just query the device for available modes and list what the driver responds with.

**Comment by bensam123** [comment]
Currently opened a support ticket on their end as well, hopefully this can get figured out as a lot of people have this card and I think they think if they select 'Highest FPS' it's inputting at 240fps, when it's not.

**Comment by Fenrirthviti** [comment]
Discussed internally with the team, and if OBS is set to 240fps, and the capture device properties is set to highest FPS, then it should be running at 240fps (assuming the directshow drivers support it). None of us on the OBS team have this capture device, so we cannot validate any of this on our end.

**Comment by bensam123** [comment]
Yeah, I'll let you guys know what I hear back from Avermedia.

I had a Magewell Pro Capture HDMI 4k Plus before this and allowed selection of a multiple FPS inputs all the way up to 240, so the options do appear if they're available.

**Comment by bensam123** [comment]
Still in the middle of talking to a CSR. They sent me to a article telling you how to change the output format to 240fps. Trying to clarify that the input is what's not at 240fps.

https://www.avermedia.com/us/support/faq?keyword=0220200511002

**Comment by WizardCM** [comment]
Note: we provide a base list in our Video Capture Device source to provide common formats.

https://github.com/obsproject/obs-studio/blob/f80421a76dfdebc853e773385c5933b12a56d643/plugins/win-dshow/win-dshow.cpp#L1249-L1267

I have no idea if drivers have the ability to add to that list.

**Comment by energizerfellow** [comment]
At a minimum I think it's time that OBS got updated to support the refresh rates of BT.2100 as that's definitely the ITU-R spec for the foreseeable future.

https://www.itu.int/rec/R-REC-BT.2100
https://en.wikipedia.org/wiki/Rec._2100

It also looks like OBS's capture rates are merely a fixed list and not queried from the DirectShow driver? Querying directly from the driver would allow for non-standard incoming fps rates like 144, 165, or 60.08.  Applications like VirtualDub allow for capturing these non-standard, arbitrary fps rates and there's really no reason OBS shouldn't as well.

**Comment by bensam123** [comment]
Finally getting some feedback!

I owned a Magewell Pro Capture HDMI 4K Plus for a couple years and it definitely allowed and OBS received input higher then 60fps. I captured at 240 and streamed to Twitch at 120 for awhile. Not sure if that was a specific driver or plugin built for OBS that allowed it, but it worked. In hindsight I sold a superior card for a inferior one. Didn't know that till I received the GC573 and found out about this in OBS, a fix never emerged as well.

**Comment by WizardCM** [comment]
Unfortunately, I don't own any capture cards or devices that would expose framerates outside of the ones OBS predefines, so I have no way to verify this issue or potentially come up with a fix. Just wanted to contribute what little I could to the conversation.

**Comment by DrunKev** [comment]
Are there any plans to improve on higher than 60 fps support for capture devices that are capable?

**Comment by lizardpeter** [comment]
This is my most requested feature and fix too (the multi-track audio issues at high frame rates). It makes my recording process convoluted and hacky (if it even works at all). They do have limited resources, however. I just really hope it’s fixed at some point.

**Comment by alinsavix** [comment]
I suspect one way to get more traction on this kind of ticket is to provide one of the OBS developers with the hardware needed to both generate and capture high-fps content (but talk to them about it first). It's difficult (if not impossible) to debug a problem, attempt a fix, and verify that fix without actually being able to reproduce the problem (and reproduction means... someone needs the hardware).

(Even then, I doubt these issues would be high priority, given the relatively tiny number of people that need high-fps capture, but there definitely won't be progress until it's possible for someone to reproduce the issues.)

((note that I don't speak for the OBS team, but I've worked with them closely in the past so have an idea of the lay of the land))

**Comment by Fenrirthviti** [comment]
Getting us the hardware is certainly part of it, but also finding the time and desire to work on it is another. This issue is open as basically a standing invitation for anyone that wants to work on it. Don't need to wait for the core team to :)

**Comment by lizardpeter** [comment]
@alinsavix At least with the issue he mentioned in regards to multiple audio tracks at high frame rates, it should be easily reproducible by anyone with a decent CPU or GPU. Any NVENC GPU from the 1000 series or above can easily record at 120 FPS at 1080p.

**Comment by Fenrirthviti** [comment]
> @alinsavix At least with the issue he mentioned in regards to multiple audio tracks at high frame rates, it should be easily reproducible by anyone with a decent CPU or GPU. Any NVENC GPU from the 1000 series or above can easily record at 120 FPS at 1080p.

That issue is completely unrelated, and is not exactly comparable as the proper fixes there require basically rewriting parts of the audio subsystem.

**Comment by lizardpeter** [comment]
> That issue is completely unrelated, and is not exactly comparable as the proper fixes there require basically rewriting parts of the audio subsystem.

Yeah, for sure. I just wasn’t sure what he meant when he said “provide one of the OBS developers with the hardware needed to both generate and capture high-fps content” as I’m sure most developers have access to a decent CPU or GPU capable of easily capturing this.

**Comment by Fenrirthviti** [comment]
I think you might be slightly confused. This is about hardware capture devices, not software capture. Most of us don't have high-end capture devices capable of more than 60fps capture. They aren't very common, and can be quite expensive.

**Comment by lizardpeter** [comment]
> I think you might be slightly confused. This is about hardware capture devices, not software capture. Most of us don't have high-end capture devices capable of more than 60fps capture. They aren't very common, and can be quite expensive.

You’re right. I’m mistaken. I did not catch that in the original post.

**Comment by bensam123** [comment]
To bring things up to speed here. This bug report was in relation specifically to the GC573 (a Avermedia capture card) not outputting 120fps stream TO OBS to ingest. The card itself would not output 120fps. These cards are not that expensive or uncommon, a lot of streamers use them.

Through my prolonged prodding I found out that Avermedia only allows 1080p@120fps output through their RECentral app and only for local recording, not streaming. It refuses to output 1080p@120 to OBS. AFAIK that's not a problem with OBS as even their native RECentral app will not output 1080p@120 stream, even though Twitch and other services can handle it. I eventually went on to make a Amazon review about this after everything was said and done as it's disingenuous and they never fixed it despite me going through the proper channels.

I've streamed in the past fine at 1080p@120 with other capture cards, such as the Magewell 4K Plus, but ended up with a lot of tearing. OBS couldn't sync up to it properly despite both operating at 120fps. I could actually output 1080p@240 from the Magewell as well.

**Comment by dodgepong** [comment]
So, this issue can be closed then? Sounds like Fenrir's original reply was accurate after all.

**Comment by derrod** [comment]
The GC573 (Live Gamer 4K) can do higher than 60 FPS over DirectShow just fine, OBS just doesn't offer it because it's limited to a hardcoded list of common framerates.

I think either "Highest FPS" or "Match output FPS" will still select modes higher than 60 FPS if OBS is configured in such a way.

**Comment by derrod** [comment]
If you want to go higher than 120 you can switch to fractional FPS mode and type in whatever you want.

There are some issues with high fps such as #2855 which are complicated to fix, so that's why it's not directly available.
