### ISSUE TITLE
[BUG] BrowserSource option does not appear in linux

### ISSUE THREAD

**Issue by wuniversales** [obsproject/obs-studio#2950]
Operating system and version: Manjaro
OBS Studio version: 25.0.8

## Expected Behavior
The option should appear

## Current Behavior
There is simply no option.

## Steps to Reproduce
1. Open OBS
2. Press +
3. You can't find the option in the menu

**Comment by kkartaltepe** [comment]
The browser source was removed from official packaging. If you are not using official packaging you should ask your package maintainer to package it once it is added back to official packaging.

**Comment by dodgepong** [comment]
It was removed from packaging due to this crash: https://github.com/obsproject/obs-browser/issues/219
