### ISSUE TITLE
[BUG] Use T-bar with Mouse Wheel Does not work

### ISSUE THREAD

**Issue by shugen002** [obsproject/obs-studio#2951]
## Platform

Operating system and version: windows 10 2004
OBS Studio version: 25.0.8

## Expected Behavior

transition should be start in output 

## Current Behavior

T-bar move but not thing happen in output
no error in log.

## Steps to Reproduce

1. ensure two different scene and studio mode
2. roll the T-bar with mouse wheel
3.
4.

**Comment by tt2468** [comment]
Is the t-bar even designed to be used with a mouse wheel? Trying it on my end makes it move like a snail.

**Comment by shugen002** [comment]
I don't know . But maybe we should block this way or make it work .

**Comment by tt2468** [comment]
I may work on a pr then to disable it.

**Comment by shugen002** [comment]
emmmmm, the T-bar is also can be move with arrow key when it have the cursor and it appear like with mouse wheel.
