### ISSUE TITLE
Scene source FFMpegSource local audio file does not play or gets played in the next scene transition

### ISSUE THREAD

**Issue by da-bilguun** [obsproject/obs-studio#2958]
## Platform

Operating system and version: Ubuntu 20.04
OBS Studio version: 25.0.7

## Expected Behavior

FFMpeg source audio file should be played when i change the scene

## Current Behavior

Audio gets played fine at first but after couple scene change events audio file does not play even though audio mixer volume seems to be moving but on the next scene change new audio file gets played with the previous audio file that is supposed to be played before

## Steps to Reproduce

1.Create two scenes , one with the ffmpeg source audio file 
2.other one blank 
3. change it back and forth between two

## Additional information

I'm using obs-websocket to control obs-studio scene change command is working fine from obs-websocket but on obs studio scene change audio source is not playing correctly

**Comment by WizardCM** [comment]
Please provide a log file from the session when this issue is reproduced (Help -> Log Files -> Upload Current Log)

**Comment by RytoEX** [comment]
No log file was provided. If this is still an issue, please comment with a log file from a session where this occurs, and we can consider reopening this.
