### ISSUE TITLE
Push to mute doesn't work

### ISSUE THREAD

**Issue by Varstahl** [obsproject/obs-studio#2959]
## Platform

Operating system and version: Win10 (19041.207)
OBS Studio version: 25.0.8

## Expected Behavior
Push to mute silences microphone.

## Current Behavior
Mute/Unmute works, but PTM/PTT don't. Changing hotkey doesn't help. Logs don't show anything relevant.

## Steps to Reproduce

1. Enable PTM for an audio input
2. Set a hotkey for that audio input PTM
3. Press the hotkey, audio's not muting

## Additional information
![image](https://user-images.githubusercontent.com/284077/82435209-40218f80-9a94-11ea-85f3-5d08af8ee7cc.png)
![image](https://user-images.githubusercontent.com/284077/82435282-5c253100-9a94-11ea-8385-53ee26b20ccd.png)

**Comment by Fenrirthviti** [comment]
I cannot replicate this on my end. Please provide a full log from OBS, even though you think there is nothing relevant there is invaluable environment and configuration information in log files. Additionally, I notice that your hotkeys have `(Tn)` after them. Are you using some kind of virtual keyboard device?

**Comment by Varstahl** [comment]
(Tn) is italian for Numpad. I also tried other keys to check if it was a pad problem, but every key behaves the same. Here are the two most recent logs provided by obs.
[2020-05-20 12-12-36.txt](https://github.com/obsproject/obs-studio/files/4660025/2020-05-20.12-12-36.txt)
[2020-05-20 14-01-46.txt](https://github.com/obsproject/obs-studio/files/4660026/2020-05-20.14-01-46.txt)

**Comment by Fenrirthviti** [comment]
Ah, understood thanks. That shouldn't be an issue to use the numpad keys.

Can you run OBS as administrator and see if this corrects the issue?

**Comment by Varstahl** [comment]
Yep, forgot to mention it, tried that as well and doesn't work. But it's not a problem of keyboard focus, doesn't even work when OBS is the active window. I think I had this kind of issue even a year or two ago on Windows 7, if it matters. I think it's one of the reasons I may have went with SLOBS, only to get back to OBS and get bit by the same problem.

**Comment by Fenrirthviti** [comment]
I am very much not able to replicate this on my end. All push to mute hotkeys I'm trying are working just fine. I am not sure what else to check, as this is not really an issue we have had reported. There must be something specific to your setup causing some kind of conflict. These are physical keys, correct? You are hitting on the keyboard and not using any kind of macroing or anything like that?

**Comment by alinsavix** [comment]
@Varstahl - Are you certain it's not muting? Note that the mute *icon* will not change when you hit your push-to-mute key, though the VU meter should drop to zero within a few seconds.

**Comment by Varstahl** [comment]
I had tested that as well but the mic was keeping its volume, I just re-double checked for safety and @alinsavix is right. When I tested muting talking to the mic the VU kept showing audio because I didn't enable PTM in the audio settings.

At some point I must have thought that the icon would reflect the muting like in other streaming software and I stopped testing it with the mic.

Sorry for the confusion, works as intended.

**Comment by Fenrirthviti** [comment]
Thanks for the follow up, we should probably look in to making the mute icon show when the push-to-mute hotkey is pressed. I actually made the same mistake when I started testing and thought it wasn't working for a moment, so you're not alone. :)

**Comment by Varstahl** [comment]
Well, it's the most counter-intuitive thing, because first you have to set it up in two different places, and then if you do one thing or the other the mic doesn't mute, and when you do everything there's no visual feedback. I was thinking of looking into it myself, and maybe make the mute color purple instead of red, to differentiate between mute and push-to-mute at a glance.

Never looked at OBS sources though, might take me a while.

**Comment by elfchief** [comment]
If it makes you feel any better, @Varstahl, my own transition from SL to OBS Studio was delayed by more than a month because I couldn't get push-to-mute to "work", because of this...
