### ISSUE TITLE
OBS not launching from usb on Mac OS Catalina

### ISSUE THREAD

**Issue by GunnerBasil** [obsproject/obs-studio#2963]
## Platform
Operating system and version: macOS Catalina version 10.15.4
OBS Studio version: 25.0.8

## Expected Behavior
I would think that it should launch as normal and keep all of its files on the USB drive.

## Current Behavior
I dragged the app from the DMG to the USB drive, and when I launched it, it said "OBS is corrupted and can't be launched."

## Steps to Reproduce
1. Insert a USB drive into a port. (I had to use an adapter.)
2. Open the DMG, and drag the app to the USB drive.
3. Double click it, or right click and select "open"

**Comment by WizardCM** [comment]
This is due to the USB drive being formatted to FAT32. The recommended solution is to format to APFS.

In future, for support requests please use the Discord.
