### ISSUE TITLE
Error: Failed to find locale/en-US.ini

### ISSUE THREAD

**Issue by jsoref** [obsproject/obs-studio#2966]
Starting OBS from a command prompt with the working directory outside the program directory results in unhelpful errors.

## Platform
Operating system and version: Windows 10 - 2004 (19628.1)
OBS Studio version: 25.0.8

## Expected Behavior
Program should pick path for locale based on location of program instead of working directory

## Current Behavior
It's apparently a fatal condition expressed in the form of a pair of dialogs.

## Steps to Reproduce
1. Read [advice](https://github.com/obsproject/obs-studio/issues/2634#issuecomment-632049898)
2. Open Command Prompt (cmd32)
3. ```C:\>"C:\Program Files\obs-studio\bin\64bit\obs64.exe"```
    ![Error - Failed to find locale/en-US.ini](https://user-images.githubusercontent.com/2119212/82563922-e11c5300-9b45-11ea-9864-dd125fce8c87.png)
4. Click OK
    ![Error - Failed to load locale](https://user-images.githubusercontent.com/2119212/82563938-e8dbf780-9b45-11ea-8627-3890372660be.png)
5. Click OK
    Program quits.

## Additional information
This works:
```C:\Program Files\obs-studio\bin\64bit>obs64.exe```

But, that isn't the point.

**Comment by Fenrirthviti** [comment]
This is expected, we do not support running OBS from outside the current working directory.

**Comment by darkworks** [comment]
you can run it from cmd like this

`start /d "C:\Program Files\obs-studio\bin\64bit\" obs64.exe --startrecording --minimize-to-tray`

to stop recording

`taskkill /F /IM obs64.exe`

**Comment by theorlando5000** [comment]
I figured it out.  Im using Up deck to control obs 
In the properties I made it run as admin.
I opened the file location and made a shortcut.  It stated it had to make it on the desktop.  From there i moved it a predetermined folder of my choosing.  I used that new address of the short cut as the address I put in Up deck.  Hope it helps

**Comment by Taster-git** [comment]
> This is expected, we do not support running OBS from outside the current working directory.

If anyone is opening this application via programming (with saved path) then how he can set working directory ?

**Comment by w921** [comment]
In the window, you can use SetCurrentDirectoryA in the main method to set the working directory.

**Comment by Aphexus** [comment]
Same issue when trying to run from registry. To claim it is a feature that it gives such an error is, well, I won't say it.

**Comment by kargalar** [comment]
create shortcut

**Comment by IceLancerSR** [comment]
> you can run it from cmd like this
> 
> `start /d "C:\Program Files\obs-studio\bin\64bit\" obs64.exe --startrecording --minimize-to-tray`
> 
> to stop recording
> 
> `taskkill /F /IM obs64.exe`

This is the answer.
Usually no one writes \64bit**\**"
Its always \64bit"
except for OBS........
I am using Total Commander and experience the same issue. I had to do the same thing.

This WORKS
[em_set_obsstreamingk]
Cmd=cd %COMMANDER_PATH%\Plugins\Media\OBS\bin\64bit\

This DOESNT
[em_set_obsstreamingk]
Cmd=cd %COMMANDER_PATH%\Plugins\Media\OBS\bin\64bit

**Comment by IceLancerSR** [comment]
It's suppose to be portable?
Well then, absolute path will not do.

This is what i have done for my self and its working.
Made .bat file with this inside:

> set GAMENAME=obs64.exe
> set HOME="%~dp0
> cd /d%HOME%
> start "OBS" %HOME%%GAMENAME%
> exit

Now i can launch from anywhere and anything.

**Comment by joxley72** [comment]
If it helps I do this. Change WD to OBS, open OBS, change WD back

    def open_obs(self):
        """Open OBS if it is not already running."""
        if not self.is_obs_running():
            # Save the current working directory
            original_cwd = os.getcwd()

            # Change to the directory where the OBS executable is located
            obs_dir = os.path.dirname(OBS_EXECUTABLE_PATH)
            os.chdir(obs_dir)

            # Open OBS
            subprocess.Popen(OBS_EXECUTABLE_PATH)

            # Revert to the original working directory
            os.chdir(original_cwd)
            return True
        return False

**Comment by raywood1** [comment]
I get the error simply from trying to open OBS using a shortcut in Win11 24H2.

**Comment by raywood1** [comment]
Correction: from using a script to open the shortcut. Never mind. Too late to delete the previous comment.

**Comment by HuskeyDev** [comment]
> 在Windows系统中，你可以在主方法中使用SetCurrentDirectoryA来设置工作目录。

Thank you very much. This method is available and effective.
I tested this method and successfully got the program running.

<img width="984" height="51" alt="Image" src="https://github.com/user-attachments/assets/1f4e9106-fa55-4d46-978f-8620fd14af06" />

<img width="555" height="130" alt="Image" src="https://github.com/user-attachments/assets/94b1a7ff-a65e-4546-9dfb-cac00ce1f46b" />

<img width="67" height="68" alt="Image" src="https://github.com/user-attachments/assets/59b58343-d4b0-4047-8fa1-ef6c85e611f8" />

**Comment by chrisvicant** [comment]
For proper operation, in the shortcut, specify in "Start in" the folder containing obs64.exe
That’s all!

**Comment by elieux** [comment]
Hello. Sorry for a bit of necromancy here, but I figure it's better than to create duplicate tickets. Is the project actively avoiding the feature of "starting OBS from arbitrary w.d. on Windows" or is it just not willing to spend the time implementing it? Cause I'd be okay with contributing this feature myself.
