### ISSUE TITLE
The shader parser mishandles non-parameterized preprocessor macros in parentheses

### ISSUE THREAD

**Issue by skeletonbow** [obsproject/obs-studio#2968]
## Platform

Operating system and version:  Windows 10 (1909) / x64
OBS Studio version:  25.0.8

## Expected Behavior

The parser should handle any valid Microsoft documented HLSL preprocessor directives.

## Current Behavior

When attempting to use a preprocessor macro where the expansion is within parentheses, OBS gives a parsing error of:

    Unable to create effect. Errors returned from parser: (null) (29, 29): Expected ',' or ')'

https://obsproject.com/logs/l2IllwhfupviP5J0

## Steps to Reproduce

1.  Take any working shader file (including those that come with OBS).
2.  Review Microsoft's documentation for #define macros found at:
https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-appendix-pre-define-1
3.  Copy and paste Microsoft's following example into the top of the shader file:

#define WIDTH       80
#define LENGTH      ( WIDTH + 10 )

4.  Save the shader file.
5.  If it is a shader for one of the shader addons, add it to OBS as a filter, source, or transition depending on the shader type and particular shader plugin.

## Additional information

I'm using OBS Shaderfilter by OnCorporation at the moment but the problem is not limited to usage of this addon so I don't believe it is an addon related bug.

It's important to be able to use macros in this fashion in order to avoid mathematical order of operations related bugs and other unintended and difficult to diagnose problems.  Macros such as these are crucial for avoiding a lot of code duplication which can lead to difficult to find and fix bugs, as well as being very useful for maintaining code readability.

**Comment by skeletonbow** [comment]
For anyone else that encounters this issue, one workaround is to wrap the macro in float() or int() etc.  For example:

`
#define LENGTH int(WIDTH + 10)
`

**Comment by skeletonbow** [comment]
Another more generic solution is to create a macro like this:

`#define macro(x) ((x))`

then you can create parameterless macros encased in parentheses by doing:

`#define LENGTH macro(WIDTH + 10)`

This works around the bug and appears to do the right thing.

**Comment by Fenrirthviti** [comment]
Closing as stale. If this is still an issue please open a new issue with updated reproduction steps on the latest version of OBS.
