### ISSUE TITLE
Pulseaudio sink and source selection mangled on connecting new sink

### ISSUE THREAD

**Issue by ysalmon** [obsproject/obs-studio#2974]
## Platform

Operating system and version: KUbuntu 18.04
OBS Studio version: 25.0.8

## Steps to Reproduce

1. Create OBS sources relating to pulseaudio sinks (monitors) and sources
2. In the sources properties, choose sinks and sources at will
3. Connect a new device to the system (bluetooth phone, using the computer as a headset)

## Expected Behavior
Nothing should change with respect to the already existing sinks/sources associations.
![Previous and expected config](https://user-images.githubusercontent.com/536850/82643557-fe1d5880-9c0f-11ea-854b-1e55b856ffdc.png)

## Current Behavior
All sources reset to the default pulseaudio source ; the monitoring output also reverts to the default.
![Happens upon connecting new device](https://user-images.githubusercontent.com/536850/82643552-fbbafe80-9c0f-11ea-9945-de40fc94bf1b.png)

## Additional information
When closing and reopening OBS, the configuration becomes correct again.
The problem also arises on removing a pulseaudio element.

**Comment by Fenrirthviti** [comment]
Closing as stale. If this is still an issue please open with updated reproduction steps on the latest version of OBS.
