### ISSUE TITLE
Indistinguishable and Lossless render different colors with same input

### ISSUE THREAD

**Issue by Slapbox** [obsproject/obs-studio#2975]
Platform

Operating system and version: Windows 7 x64
OBS Studio version: 25.0.8

## Expected Behavior
Indistinguishable should be virtually indistinguishable from lossless

## Current Behavior
Indistinguishable produces content that is immediately recognizable as not being the same as the source.

1. Text is faded and _slightly_ fuzzy - nothing terrible, but far from "indistinguishable" 
2. Much more importantly, colors are modified from their originals

![image](https://user-images.githubusercontent.com/6835891/82709617-f7fa9c80-9c4e-11ea-8594-750f5636a496.png)

## Steps to Reproduce
Self-evident

## Additional information
Thanks to the OBS team for their great work!

**Comment by skeletonbow** [comment]
Good idea to include the log file from when the encoding was done so the devs have something to go on.

**Comment by Slapbox** [comment]
@kkartaltepe the issue is not merely colors, it is just the most outstandingly obvious aspect. I believe the original issue title was more correct. If the option were called "Very High" then I'd say text fuzziness is inconsequential, but if it's labeled "Indistinguishable" then text fuzziness is an issue.

@skeletonbow your suggestion is a good one. Here's the log file https://pastebin.com/ZrEk3KRx

**Comment by notr1ch** [comment]
This is due to your color format settings, OBS defaults to NV12 for anything other than lossless. Set I444 or RGB and try again, but be aware compatibility for these formats is quite poor.

**Comment by Slapbox** [comment]
Thanks for your reply @notr1ch. We're already set to `RGB`, but I'll give `I444` a shot and report back.

**Comment by Slapbox** [comment]
With regards to the color issue: `I444` is closer to the original, based on my very limited testing, but still off. The text seems a tad better too, but I think it's due to the contrast ratio being restored by the proper colors.

All combinations of `RGB` and `I444` and `601` vs `709` produce colors that don't match the original.

**Comment by kkartaltepe** [comment]
You also dont tell us what you are using to play back the videos. Every media player deals with colors differently.

**Comment by notr1ch** [comment]
Uncommon color spaces have poor compatibility with various video players, editors, etc. I have verified that recording at indistinguishable quality, RGB, 709 produces [perfect colors](https://i.imgur.com/llolBZy.png) in my recordings when replayed with VLC. Colors are NOT accurate in the default Windows video player. Please double check your playback settings - things like hardware acceleration and video driver settings may influence your results.

**Comment by Slapbox** [comment]
@kkartaltepe thanks for pointing that out, I'd meant to mention - VLC Player.

@notr1ch I checked in VLC and also Chrome. While both differ, Chrome differs slightly less. I'll do a bit more digging in terms of color setting/playback combinations.

> Colors are NOT accurate in the default Windows video player.

Even as a relative layman, I know better than to touch that mess!

----

The above addresses the color differences, but not differences in text quality. While the text quality differences _may_ just be a result of differences in color reproduction, it would be my strong recommendation to rename "Indistinguishable" to "Very High," because it is indeed distinguishable, and so it's a bit misleading.

Thanks to all for your advice and hard work. Will report back.

**Comment by kkartaltepe** [comment]
indistinguishable is indistinguishable to the layman. It is still a significant compression and you dont provide any evidence of what you consider unacceptable performance for text quality. You are probably rendering worst case scenarios where you can expect there to be artifacts even at indistinguishable. It not called lossless for a reason.

**Comment by notr1ch** [comment]
All of the quality presets will result in color information loss with the default NV12 Partial color space. The indistinguishable preset is intended to mean that compression artifacts (eg macroblocking) cannot be distinguished, not that it is indistinguishable from lossless. I'm going to close this issue as we're getting into arguments over the semantics of how the word is used, and given how users are already used to this terminology (and all our translations would need updating), it is unlikely we will be changing it.
