### ISSUE TITLE
Text area does not correctly display UTF-8 symbols from file

### ISSUE THREAD

**Issue by sxiii** [obsproject/obs-studio#2981]
## Platform

Operating system and version: Manjaro 19
OBS Studio version: 25.0.8-1
 
## Expected Behavior
Show "☮" and other UTF-8 and 16 symbols.

## Current Behavior
Does not show the UTF-8 symbols correctly even with font that has the symbols.

## Steps to Reproduce
1. Type-in the UTF-8 symbol (like ☮ for example) into text file. 
2. Then, load this text file into OBS. 
3. Select the font that 100% has the "☮" symbol inside it. 
4. Check out, that video on the screen shows "square empty" symbol instead of "☮".

**Comment by notr1ch** [comment]
Unable to reproduce here, make sure your file is really saved in UTF-8. Manjaro 19 is not an officially supported platform, if you continue to experience issues you may want to raise this with whoever built the package you're using.

**Comment by kkartaltepe** [comment]
Please use support before opening a bug.

**Comment by sxiii** [comment]
@notr1ch 
```
[sw@t490s fakecam]$ file text.txt 
text.txt: UTF-8 Unicode text
[sw@t490s fakecam]$ tail -n1 text.txt 
Imagine all the people living life in peace ☮
```
![image](https://user-images.githubusercontent.com/575925/82758292-f0213080-9de5-11ea-83a7-366a4803d791.png)

**Comment by sl5net** [comment]
searching a complete list of possible icons using "DejaVu Sans". For example if this is possble to use in OBS : 🌿
