### ISSUE TITLE
Hotkey bindings involving "control" fail when the right control key is used to activate them

### ISSUE THREAD

**Issue by CNakai** [obsproject/obs-studio#2982]
## Platform

Operating system and version: Manjaro Linux 20.0.1 (Lysia)
OBS Studio version: 25.0.8-1 (linux) installed via pacman

## Expected Behavior
Hotkey bindings involving control should activate regardless fo which control key (left/right) is pressed to activate them

## Current Behavior
When the right control key is pressed and the OBS window is in focus, the hotkey binding will activate sporadically.  If the OBS window is not in focus, the hotkey binding will not activate at all when the right control key is used

## Steps to Reproduce
1. Set hotkey binding for Start/Stop recording to "Control + `" and apply changes
2. Focus a window other than OBS
3. Press the right control key and the "`" key

## Additional information
The program xev registers the keys pressed as expected

**Comment by RytoEX** [comment]
Please confirm that this is still an issue on OBS Studio 28.0.2 (or newer).

**Comment by PatTheMav** [comment]
Closing this as there has been no reply after 3 weeks. Feel free to reply with the requested information at a later point.
