### ISSUE TITLE
[BUG] Installing on windows new updates from a non-administrator users is taking all the system resources (crash)

### ISSUE THREAD

**Issue by trueliarx** [obsproject/obs-studio#2984]
## Platform

Operating system and version: Windows 10 Pro 64bit - Version 1909 - build 18363.836
OBS Studio version 25.0.4 64bit

## Expected Behavior
After launching the update for the new version, as non-admnistrator, the OBS Studio updater warns about the lack of administrator rights and stops or installs the software only for the current user.

## Current Behavior
After launching the update for the new version, as non-admnistrator, the Obs Updater goes in loop and opens several new "updater.exe" processes until the whole system is unresponsive.

I needed to kill all the processes several times with
taskkill /F /IM "Updater.exe"

There are no useful informations in the log files.

## Steps to Reproduce

1. Log in as a non-administrator user
2. Open Obs studio
3. Click on "Update now".

https://ibb.co/5B1kh2G
https://ibb.co/MNg8fTv

**Comment by notr1ch** [comment]
Having the user and administrator as separate user accounts is not currently supported in the updater, but it should definitely error out instead of getting stuck in a loop. Will look into it.

**Comment by notr1ch** [comment]
I am unable to reproduce this. When the non-elevated user account launches the updater, a runas prompt appears asking for administrator credentials. Cancelling the prompt works as expected (ie, the updater exits). Could you describe your user account environment in more detail?
