### ISSUE TITLE
Streaming with srt, stremaid no set or truncated

### ISSUE THREAD

**Issue by xiaozhihong** [obsproject/obs-studio#2990]
## Platform

Operating system and version: macOS Catalina 10.15.4 (19E287)
OBS Studio version: 25.0.8 (64 bit)

## Expected Behavior

Streaming using SRT will set streamid "test"

## Current Behavior

SRT don't set streamid.

## Steps to Reproduce

1. Stream, set "Server" to "srt://127.0.0.1:9000".
2. Stream, set "Stream Key" to "test".
3. "OK".
4. "Start Streaming".
5. Capture network using Wireshark, analyse the output.

## Additional information

If I use the url like "srt://127.0.0.1:9000?streamid=test", it can work.
But if I have a sepcial streamid like "test?key_1=value_1&key_2=value_2", the streamid
in SRT will change to "test?key_1=value_1"

**Comment by pkviet** [comment]
The stream key is used for rtmp; why would you expect it to be useful for srt ? the streamid is **not** a stream key though it could be used as one. Its use is not compulsory for srt streams ... while for rtmp it's compulsory.
At the moment, there is 0 code to use it for the srt output in obs.
I'd try to set the streamid differently server-side.
Did you try to URL encode your question mark ? "?" is normally forbidden, so no wonder it's not parsed correctly by the srt server ...

**Comment by xiaozhihong** [comment]
> The stream key is used for rtmp; why would you expect it to be useful for srt ? the streamid is **not** a stream key though it could be used as one. Its use is not compulsory for srt streams ... while for rtmp it's compulsory.
> At the moment, there is 0 code to use it for the srt output in obs.
> I'd try to set the streamid differently server-side.
> Did you try to URL encode your question mark ? "?" is normally forbidden, so no wonder it's not parsed correctly by the srt server ...

Many people use rtmp streamid like "app/stream?key_1=value_1&key_2=value_2" to take custom arguments to the rtmp server, like token, secret key.

I think when obs parse srt url, it can not assume "there is no special symbol in the streamid(? & ...)"

**Comment by Meekel** [comment]
Whatever way this ends up going, the [OBS Wiki](https://obsproject.com/wiki/Streaming-With-SRT-Protocol#option-1-stream-srt-using-the-streaming-output) should probably be updated. Currently it shows something within the "Stream Key" field which is a little misleading, but doesn't say at any point how that would be handled.

The wiki **does** mention however that options should be place in the Server field.

**Comment by pkviet** [comment]
> 
> I think when obs parse srt url, it can not assume "there is no special symbol in the streamid(? & ...)"

of course, that's why you need to URL encode it.
We use ffmpeg libs for the srt output: the URL is parsed by avformat so it should work with any regular URL that works with ffmpeg (provided you URL encode special characters)

**Comment by pkviet** [comment]
> Whatever way this ends up going, the [OBS Wiki](https://obsproject.com/wiki/Streaming-With-SRT-Protocol#option-1-stream-srt-using-the-streaming-output) should probably be updated. Currently it shows something within the "Stream Key" field which is a little misleading, but doesn't say at any point how that would be handled.
> 

oh right, that's an oversight from me when I made the screenshot (the original URL was rtmp)

Yeah i'll change that and update the wiki. Thanks for pointing out @Meekel

**Comment by WizardCM** [comment]
Is this something we actually want to "fix"? Seems to me like the stream key field just isn't designed to be used this way.

**Comment by WizardCM** [comment]
Closed after discussion internally.
