### ISSUE TITLE
[BUG] Crash after 30m with Video Source and Apple VT H264 Hardware Encoder

### ISSUE THREAD

**Issue by yuletide** [obsproject/obs-studio#2991]
## Platform

Operating system and version: OSX 10.14.6, Macbook Pro 2017, Apple VT Hardware Encoder
OBS Studio version:25.0.8 x64

## Expected Behavior

OBS should run without interruption

## Current Behavior

OBS Crashes after 28-29m when using a VLC playlist or Media source and the Apple H264 hardware encoder. 

Other test cases:
 - Blank scene with H264 encoder: No crash
 - Media source with software encoder: No crash
 - VLC Playlist source with hardware encoder: Crash
 - Media Source with hardware encoder: Crash

Logs: https://obsproject.com/forum/threads/vlc-media-playlist-crash-after-20-30m.122113/

```14:49:18.441: glBindFramebuffer failed, glGetError returned GL_INVALID_OPERATION(0x502)
14:49:18.442: glFrameBufferTexture2D failed, glGetError returned GL_INVALID_OPERATION(0x502)
```

## Steps to Reproduce

1. Create scene with VLC Video or Media source, set output to Apple H264 Hardware encoder
2. OBS crashes after ~28-29m

## Additional information

Four sets of crashlogs from various crashes in my forum post here: https://obsproject.com/forum/threads/vlc-media-playlist-crash-after-20-30m.122113/

**Comment by chech0x** [comment]
In my case obs crashes after ~10-20 minutes when i use vlc plugin.

**Comment by mandrios** [comment]
Same behaviour than @chech0x

**Comment by gxalpha** [comment]
Does this still happen on OBS 27.2?

**Comment by gxalpha** [comment]
Closing as stale. Feel free to report a new issue if this is still a problem.
