### ISSUE TITLE
Bitrate Spikes Caused by a Beta Option

### ISSUE THREAD

**Issue by EnigmaO** [obsproject/obs-studio#2996]
Hello,
I've been having a weird issue lately. My bitrate spikes to 30-40K, even though my upload speed is 20K and I use 6K CBR (Constant Bitrate) on OBS Studio. Streaming on Twitch with new NVENC, 2060 Super. A picture of the spikes is attached from the Twitch Inspector tool, showing bitrate depending on time of a stream. 
Unfortunately, because of those big spikes, Twitch kept disconnecting me from their servers and my streams would just end. I've done an elimination process until i found what caused the issue. In settings, under the advanced tab, there's an option called "Dynamically change bitrate to manage congestion (beta)". I turned it ON when it was first added lately, thinking it's good, but it was causing the issue. Probably because it's still a beta version. https://cdn.discordapp.com/attachments/715326874494173204/715465044867022848/Screenshot_3047.png

**Comment by kkartaltepe** [comment]
Github issues are not for support. Please use the discord or forums for support.
