### ISSUE TITLE
Unavailable filters silently disappear

### ISSUE THREAD

**Issue by ysalmon** [obsproject/obs-studio#2997]
## Platform

Operating system and version: KUBuntu 20.04
OBS Studio version: 25.0.8 compiled form git repo

## Expected Behavior

When a filter is applied to an object, but, due to a change of circumstances, this filter is no longer available to OBS, it should be displayed in a special way to let the user understand what is happening.

## Current Behavior

The relevant filter just does not appear at all in the source's filter list.
## Steps to Reproduce

1. With debian packaged OBS, create a pulseaudio source.
2. Apply a Noise reduction filter to it.
3. Uninstall debian packaged OBS and compile OBS from source without the noise-suppress plugin (eg. due to unavailable library).
4. Run OBS and show the filters GUI of the source.

## Additional information

This may also happen when transferring scenes between computers with slightly different OBS configuration.

**Comment by exeldro** [comment]
This might be related to #2509

**Comment by ysalmon** [comment]
Maybe but the filter reappeared in the list after I recompiled OBS with the corresponding plugin, so I do not think it was deleted from the filter list, only not displayed. In my perception this is a GUI problem.

**Comment by WizardCM** [comment]
Could you confirm if this still happens on latest nightly? Thanks!

**Comment by WizardCM** [comment]
@ysalmon Hi there, is this still an issue in 26.1.0? Thanks!

**Comment by Xaymar** [comment]
This may have been a manifestation of #2509, as if you did not modify anything within the scene collection through any means the scene collection would stay the same and not be messed up.

**Comment by gxalpha** [comment]
Closing as stale. Feel free to report a new issue if this is still a problem.
