### ISSUE TITLE
running obs on idle in bg on win10 (2004) causing low fps in games 

### ISSUE THREAD

**Issue by JoqniX** [obsproject/obs-studio#3008]
## Platform

Operating system and version: Windows 10 x64bit , version 2004(OS Build 19041.264)
OBS Studio version: 25.0.8 (64 bit)

## Expected Behavior
 normally if i run a game and then open obs or vise versa fps should remain the same (while on idle) . and fps should be affected if im streaming or recording {back in windows 10 (1909)} 

## Current Behavior
as of now i did a fresh install of the latest update of windows 10 (2004) and if i open obs while my game is running or vise versa , if i add more than 3-4 browser scenes or others the fps drops like alot in game !

log with my scenes - https://obsproject.com/logs/HBsCTGKE_yFg2PeC 
log using a new scene collection having just 6 browser sources - https://obsproject.com/logs/f8eN4ycE_udc5dIp

## Steps to Reproduce

1.https://media.discordapp.net/attachments/374636015396192257/716308077896269914/unknown.png?width=328&height=684
2.https://cdn.discordapp.com/attachments/681842980809998346/716320023534108712/FortniteClient-Win64-Shipping_Wmmyw8Sp3E.jpg
3.https://cdn.discordapp.com/attachments/681842980809998346/716320031499354252/FortniteClient-Win64-Shipping_IqSAGvYPWp.jpg
4.

## Additional information
 do note this - i reinstalled obs 3times and now im getting a little bit of my fps back but the game is laggy even with 190fps tho i should get 300fps in game 
and at first install of obs today after i had reinstalled windows 10 2004 version , and added  my scene collection to obs  i got like 20- 40 fps in game while obs was running ,and when i quit obs i got my 300fps back !

**Comment by Fenrirthviti** [comment]
This appears to be just standard GPU overload. Please use the support forums or Discord for support requests, this is not a bug.

https://obsproject.com/help

**Comment by JoqniX** [comment]
how is that possible???? didn't i mention my cpu and gpu usage were low ??? cpu was at 4% and gpu 2.2%

**Comment by SoldierInHell** [comment]
i just recently updated to the newest Windows... Before I was getting no FPS drops at all... literally none. i would run warzone on 130+ and now when i even open OBS or Streamlabs... my fps just plummets... not even streaming the game, i just open it and i lose 10-30 fps, depending which scene i use in OBS or streamlabs. if someone has a fix please lmk, i can't stream at all. I even tried doing a dual-pc stream and i still get fps drop because i have to gave OBS open to send the screen to my streaming pc...
