### ISSUE TITLE
OBS Text Refresh Rate is too slow on files

### ISSUE THREAD

**Issue by Meerkov** [obsproject/obs-studio#3012]
## Platform

Operating system and version: All
OBS Studio version: 25.0.1 64 bit

## Expected Behavior
Text Source with a "Read File" source should update soon after a file updates.

## Current Behavior

It takes 1-2 seconds for a source to actually update.

## Steps to Reproduce

1. Update a text file more than once per second (say 5 times)
2. Notice the text source only updates once a second.

## Additional information
There are forum user complaints about this, going back at least 3 years, with proposed fix (reducing the update time from 1 second to 0.02 seconds, to hit 50 FPS).
https://obsproject.com/forum/threads/read-from-text-file-refresh-rate.73589/

**Comment by kkartaltepe** [comment]
Much like #1192 and #1566 there isnt a ton of desire to increase the polling rate upstream.

You can still work around this on a per source basis via scripts like https://gist.github.com/kkartaltepe/861b02882056b464bfc3e0b329f2f174 or by recompiling the source locally. I think a change actually enabling directory watching in windows would be more likely to get in than polling (maybe).

Not sure if this bug should stay open but we did have https://obsproject.com/mantis/view.php?id=1350 earlier

**Comment by RytoEX** [comment]
The correct way to address this would be to switch to platform file notification APIs instead of adjusting the polling rate. We do not want to adjust the polling rates because we do not want to perform possibly blocking operations more often. As written, this is more like a feature request, but as stated, we do not want to adjust polling rates.

**Comment by based-a-tron** [comment]
@RytoEX I hacked in inotify support for OBS image source and freetype text source like 2 years ago, and just waited for someone to add this in the upstream, but I guess there is no plan for this. Would such a change be welcome?

**Comment by aut0-m8** [comment]
Why not make the polling rate variable?

**Comment by Fenrirthviti** [comment]
Our reasoning is explained in RytoEX's comment in this thread.

**Comment by aut0-m8** [comment]
That looks like a lot of work, why not make it variable for now and revamp it later? I'm sure that would take less time than waiting for a revamp.

**Comment by aut0-m8** [comment]
Especially since this issue is from 2020 and nothing has been implemented in the past 4 years.

**Comment by RytoEX** [comment]
We are not interested in making the polling rate adjustable as yet another thing to track points of failure for when users set it to values we did not test or expect. If you require this to be changed, the OBS source code is freely available and able to be modified.
