### ISSUE TITLE
[BUG] macOS upload crash report and show crash reports broken

### ISSUE THREAD

**Issue by unknowndomain** [obsproject/obs-studio#3019]
## Platform
Operating system and version: macOS Catalina 10.15.4
OBS Studio version: 25.0.8

## Expected Behavior
Pressing Help > Crash Reports > Show Crash Reports or Help > Crash Reports > Upload Last Crash Report should work.

## Current Behavior
When you press either of these buttons nothing happens.

## Steps to Reproduce
1. Some how crash OBS
2. Relaunch
3. Press either button

Nothing happens and no error message either.

## Additional information
This issue keeps coming up for other Mac users in #macos-support on Discord.

**Comment by Fenrirthviti** [comment]
We don't actually have internal crash reporting for macOS, we use the system crash system, so this is more or less expected. These menu options should probably be deleted on macOS until we can have proper crash reporting on all three platforms.

**Comment by unknowndomain** [comment]
Definitely, but also probably need to add some guidence for Mac users on how to get this as its not trivial, i.e. a Wiki article here on crash reporting for macOS and a !maccrashlog that links to it on discord.

**Comment by offthegrid-mike** [comment]
Should we temporarily remove "Crash Reports" in menu section or provide a text area for user to upload their os system crash stack?

**Comment by gxalpha** [comment]
Fixed by https://github.com/obsproject/obs-studio/pull/3825.
