### ISSUE TITLE
1080p 60FPS laggy on Linux (R5 2600 + RX 580 8GB)

### ISSUE THREAD

**Issue by JediFonseca** [obsproject/obs-studio#3028]
## Platform
Linux
Tested on Fedora Workstation 32, Fedora Silverblue 32, ZorinOS Lite 15.2 Ubuntu 20.04 and Ubuntu 18.04.
Tested using both Xorg and Wayland.

OBS Studio 25.0.8 installed via Ubuntu/Fedora official repositories and the **[Flatpak package](https://flathub.org/apps/details/com.obsproject.Studio)**.

## Expected Behavior/Current Behavior

A friend using an "i7 4790k + RX 580 8GB" can screen capture on 1080p 60fps flawlessly using VAAPI on Fedora Silverblue 32. The same can't be done with my Ryzen 5 2600 + the same RX 580 8GB, 'cause it always acuses "Encoding overloaded" and the result is extremely laggy. 1080p/30fps and 720p/60fps works fine though.

When using "x264" even on 1080p/60 OBS it doesn't acuse "Encoding overloaded", and the final result is way better than with VAAPI, but in this case the game loses frames and shows some stuttering.

On Windows 10 using the same machine screen recording runs flawlessly on 1080p/60.

## Additional info:

Already tried "VBR and CBR 10000Kbps, CQP 20QP and all options on the "Level" field. Also tried all options on "Downscale Filter" field.

## OBS Configs images:

![PintScreen](https://user-images.githubusercontent.com/47907146/83467562-a45b3080-a450-11ea-8445-b48fc3c58638.png)

![PintScreen_1](https://user-images.githubusercontent.com/47907146/83467579-ad4c0200-a450-11ea-8fcc-331a928950ad.png)

**Comment by notr1ch** [comment]
Please use the forums or Discord for support. Github issues are for reproducible bugs.
