### ISSUE TITLE
Recording rawvideo causes SIGSEGV

### ISSUE THREAD

**Issue by reitzig** [obsproject/obs-studio#3031]
## Platform

Operating system and version: Linux 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
OBS Studio version: OBS Studio - 25.0.8 (linux)
Installer: DEB from official PPA

## Expected Behavior

When I set obs to record `rawvideo` to my v4l2loopback device `/dev/video0`, I expect it to do so OR display a meaningful error message.

## Current Behavior

    “obs” terminated by signal SIGSEGV (Address boundary error)

## Steps to Reproduce

_Prerequisites:_ Install v4l2loopback and load the kernel module.

1. Set Recording to Custom Output (FFmpeg) > Output to URL, `/dev/video0`, rawvideo
   
   ![image](https://user-images.githubusercontent.com/4246780/83634381-bea52380-a5a2-11ea-8722-45a47873a916.png)

2. Press "Start Recording"

I can reproduce the crash also without v4l2loopback, selecting Output to File.

## Additional information

```
$ v4l2-ctl -d /dev/video0 --list-formats-ext
ioctl: VIDIOC_ENUM_FMT
	Index       : 0
	Type        : Video Capture
	Pixel Format: 'MJPG' (compressed)
	Name        : Motion-JPEG
		Size: Discrete 1280x720
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 320x180
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 320x240
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 352x288
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 424x240
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 640x360
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 640x480
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 848x480
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 960x540
			Interval: Discrete 0.033s (30.000 fps)

	Index       : 1
	Type        : Video Capture
	Pixel Format: 'YUYV'
	Name        : YUYV 4:2:2
		Size: Discrete 1280x720
			Interval: Discrete 0.100s (10.000 fps)
		Size: Discrete 320x180
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 320x240
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 352x288
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 424x240
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 640x360
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 640x480
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 848x480
			Interval: Discrete 0.050s (20.000 fps)
		Size: Discrete 960x540
			Interval: Discrete 0.067s (15.000 fps)
```

YUYV does not appear in the recording options. MJPEG doesn't work either but doesn't crash (separate issue). FWIW:

```
 $ ffplay /dev/video0
<snip>
Input #0, video4linux2,v4l2, from '/dev/video0':B sq=    0B f=0/0   
  Duration: N/A, start: 1214650.214122, bitrate: 147456 kb/s
    Stream #0:0: Video: rawvideo (YUY2 / 0x32595559), yuyv422, 1280x720, 147456 kb/s, 10 fps, 10 tbr, 1000k tbn, 1000k tbc
```

That's why I tried to use `rawvideo`.

**Comment by notr1ch** [comment]
Please also attach a backtrace.

**Comment by reitzig** [comment]
And how would I do that?

(Are you not able to reproduce?)

**Comment by kkartaltepe** [comment]
Replicates on my machine

**Comment by jam3st** [comment]
Can you add the v4l option if you fix this?
