### ISSUE TITLE
Recording mjpeg to v4l2loopback device fails

### ISSUE THREAD

**Issue by reitzig** [obsproject/obs-studio#3032]
## Platform

Operating system and version: Linux 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
OBS Studio version: OBS Studio - 25.0.8 (linux)
Installer: DEB from official PPA

## Expected Behavior

When I set obs to record `mjpeg` to my v4l2loopback device `/dev/video0`, I expect it to do so OR display a helpful error message.

## Current Behavior

Error message:

> An unspecified error occurred while recording.

On the CLI:

```
info: ==== Recording Start ===============================================
warning: receive_audio: Error writing packet: Invalid argument
info: Output 'adv_ffmpeg_output': stopping
info: Output 'adv_ffmpeg_output': Total frames output: 5
info: Output 'adv_ffmpeg_output': Total drawn frames: 13
info: ==== Recording Stop ================================================
```

I do not understand why it complains about audio, which I understand to be disabled in `mjpeg` mode (see below).

## Steps to Reproduce

_Prerequisites:_ Install v4l2loopback and load the kernel module.

1. Set Recording to Custom Output (FFmpeg) > Output to URL, `/dev/video0`, mjpeg

   ![image](https://user-images.githubusercontent.com/4246780/83634963-b7324a00-a5a3-11ea-95c9-42c502e391db.png)

2. Press "Start Recording"

I can not reproduce the error without v4l2loopback; selecting Output to File, I get a single mjpeg file.

## Additional information

```
$ v4l2-ctl -d /dev/video0 --list-formats-ext
ioctl: VIDIOC_ENUM_FMT
	Index       : 0
	Type        : Video Capture
	Pixel Format: 'MJPG' (compressed)
	Name        : Motion-JPEG
		Size: Discrete 1280x720
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 320x180
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 320x240
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 352x288
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 424x240
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 640x360
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 640x480
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 848x480
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 960x540
			Interval: Discrete 0.033s (30.000 fps)

	Index       : 1
	Type        : Video Capture
	Pixel Format: 'YUYV'
	Name        : YUYV 4:2:2
		Size: Discrete 1280x720
			Interval: Discrete 0.100s (10.000 fps)
		Size: Discrete 320x180
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 320x240
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 352x288
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 424x240
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 640x360
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 640x480
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 848x480
			Interval: Discrete 0.050s (20.000 fps)
		Size: Discrete 960x540
			Interval: Discrete 0.067s (15.000 fps)
```

**Comment by kkartaltepe** [comment]
The warning you see _is_ the helpful error message. Otherwise custom ffmpeg output is use at your own risk. This is the risk you subscribe to when using it.

**Comment by reitzig** [comment]
How is this error message actionable (which is how I define "helpful" in this context)? Something is wrong -- got it. But _what_? How do I fix it? ffmpeg itself usually prints more detail. obs also doesn't tell me what it tried (= the ffmpeg call) so I could try and debug the ffmpeg call on the CLI.

I'll also note, from a UX perspective, if you're giving me limited UI (only a few of ffmpeg's options are covered) for custom stuff that I have to debug myself, that's no good. If you missed a required option, I get blocked.

(The UI should probably indicate the at-your-own-risk-ness?)

---

That all said: 

> I do not understand why it complains about audio

Can anyone shed some light on this? Of _course_ forwarding audio to a video-only format/device will fail. Seems like a bug in obs to me: it shouldn't "send" audio in such cases. ffmpeg can certainly drop audio tracks (but I don't see a way to tell it to through obs).

**Comment by kkartaltepe** [comment]
It sounds like what you actually want is a feature request to improve the error reporting pipeline in obs (and probably for ffmpeg).

>How is this error message actionable (which is how I define "helpful" in this context)? Something is wrong -- got it. But what? How do I fix it? ffmpeg itself usually prints more detail. 
A good feature request for FFMPEG since this is their error message.

> obs also doesn't tell me what it tried (= the ffmpeg call) so I could try and debug the ffmpeg call on the CLI.
Well obs doesnt use the ffmpeg cli, so there is no such thing as "the ffmpeg call". You have indeed chosen all the settings yourself in the obs ui. If you need help debugging ffmpeg behavior that is unfortunately the risk in using ffmpeg custom output.

>(The UI should probably indicate the at-your-own-risk-ness?)
This is why it's only accessible under "advanced", it means "I know i can do bad things and I accept the responsibility for it"

>I'll also note, from a UX perspective, if you're giving me limited UI (only a few of ffmpeg's options are covered) for custom stuff that I have to debug myself, that's no good. If you missed a required option, I get blocked.
Perhaps you can provide the options that you find necessary that are missing instead.


For clarity, yes its possible that obs is sending audio when it shouldnt. But the rest of your bug report reads like a feature request, or support request. Both of which we want to avoid having on the issues page, we have https://ideas.obsproject.com/ for feature requests and discord for support.

**Comment by reitzig** [comment]
> It sounds like what you actually want is a feature request to improve the error reporting pipeline in obs (and probably for ffmpeg).

What I actually want it to use obs output in Zoom. What I describe above is what I think is a bug blocking me from tinkering that together, and (as added feedback, if you will) why its output and UI didn't enable me to dig deeper for myself. You are, of course, free to ignore the latter part.

I will note that I spent only very little of the ticket text on those (potentially out-of-scope) UX issues you're reacting so strongly to (that OR passage under 'expected'). This _is_ a bug report which you've so far chosen to not engage with. :/

> For clarity, yes its possible that obs is sending audio when it shouldnt.

Then let's focus on that. Can we agree that

 - MJPEG is selected,
 - Disable [Audio] Encoder is selected (in fact, all audio encoder fields are disabled), yet still
 - FFMPEG is called in such a way that it responds with `receive_audio`?

**Comment by dodgepong** [comment]
Have you tried the v4l2sink plyugin? https://github.com/CatxFish/obs-v4l2sink

**Comment by kkartaltepe** [comment]
Closing as virtual cam is up streamed now.
