### ISSUE TITLE
obs starting menu is missing many important elements

### ISSUE THREAD

**Issue by doe2jon1** [obsproject/obs-studio#3041]
![Screenshot_20200606_140846](https://user-images.githubusercontent.com/66154079/83951416-7a628f00-a7ff-11ea-8f12-440018fdcaa8.png)
when obs is opened it is just a black screen with a grey border and all the settings that are usually on the bottom. im on kde ubuntu 20.04

**Comment by notr1ch** [comment]
Please use the forums or Discord for support requests.
