### ISSUE TITLE
Crashing when opening RTMP stream

### ISSUE THREAD

**Issue by reavessm** [obsproject/obs-studio#3043]
Whenever I stream from my desktop to my RTMP server, OBS crashes when trying to read from RTMP source.

## Platform

Operating system and version: Gentoo
OBS Studio version: 25.0.8-r1

## Expected Behavior

Create VLC Input source, specify URL, and see stream as input
## Current Behavior

OBS crashes when reading from RTMP source

### Logs
```
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/locale.ini
Attempted path: /usr/share/obs/obs-studio/locale.ini
Attempted path: share/obs/obs-studio/themes/Dark.qss
Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
info: CPU Name: AMD Ryzen 7 2700 Eight-Core Processor
info: CPU Speed: 3231.826MHz
info: Physical Cores: 8, Logical Cores: 16
info: Physical Memory: 64249MB Total, 10230MB Free
info: Kernel Version: Linux 5.7.0-rc4
info: Distribution: Gentoo Unknown
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.7
info: Portable mode: false
Attempted path: share/obs/obs-studio/themes/Dark/no_sources.svg
Attempted path: /usr/share/obs/obs-studio/themes/Dark/no_sources.svg
info: OBS 25.0.8 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 44100
	speakers:        2
info: ---------------------------------
info: Initializing OpenGL...
info: Loading up OpenGL on adapter VMware, Inc. llvmpipe (LLVM 9.0.1, 256 bits)
info: OpenGL loaded successfully, version 3.3 (Core Profile) Mesa 20.1.0, shading language 3.30
info: ---------------------------------
info: video settings reset:
	base resolution:   1920x1080
	output resolution: 1920x1080
	downscale filter:  Bilinear
	fps:               30/1
	format:            NV12
	YUV mode:          601/Partial
info: NV12 texture support not available
info: Audio monitoring device:
	name: Default
	id: default
info: ---------------------------------
warning: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
info: No blackmagic support
info: FFMPEG VAAPI supported
info: VLC found, VLC video source enabled
info: ---------------------------------
info:   Loaded Modules:
info:     vlc-video.so
info:     text-freetype2.so
info:     rtmp-services.so
info:     obs-x264.so
info:     obs-transitions.so
info:     obs-outputs.so
info:     obs-libfdk.so
info:     obs-filters.so
info:     obs-ffmpeg.so
info:     linux-v4l2.so
info:     linux-pulseaudio.so
info:     linux-decklink.so
info:     linux-capture.so
info:     linux-alsa.so
info:     image-source.so
info:     frontend-tools.so
info:     decklink-ouput-ui.so
info: ---------------------------------
info: ==== Startup complete ===============================================
info: All scene data cleared
info: ------------------------------------------------
info: Switched to scene '3-way'
info: ------------------------------------------------
info: Loaded scenes:
info: - scene 'Stephen':
info:     - source: 'Stephen RTMP' (vlc_source)
info: - scene 'Test':
info:     - source: 'Test Red' (color_source_v2)
info: - scene 'Tyler':
info:     - source: 'Tyler RTMP' (vlc_source)
info: - scene 'Ethan':
info:     - source: 'Ethan RTMP' (vlc_source)
info: - scene '3-way':
info:     - source: 'Ethan' (scene)
info:     - source: 'Tyler' (scene)
info:     - source: 'Stephen' (scene)
info: ------------------------------------------------
[00007f272c001970] main xml reader error: XML reader not found
Attempted path: share/obs/obs-studio/images/overflow.png
Attempted path: /usr/share/obs/obs-studio/images/overflow.png
info: User switched to scene 'Stephen'
```

## Steps to Reproduce

1. Add custom RTMP server to stream from OBS on Desktop
2. Open OBS through SSH on headless server
3. Add VLC Source, specifying RMTP url
4. Open VLC throuhg SSH on headless server and verify VLC plays the stream, Close VLC
5. Start streaming on Desktop
6. OBS on server crashes

## Additional information

obs-studio was compiled with USE="alsa fdk imagemagick luajit pulseaudio python speex ssl truetype v4l vlc -jack -nvenc"

vlc was compiled with USE="X a52 alsa archive chromaprint dbus dts dvbpsi dvd encode fdk ffmpeg flac fontconfig gcrypt gme jpeg libass libcaca libnotify libsamplerate lirc lua macosx-notifications mad matroska modplug mp3 mpeg ncurses nfs ogg omxil opus png pulseaudio qt5 sid soxr speex ssl svg theora truetype twolame udev upnpn v4l vaapi vnc vorbis x264 x265 xml zvbi -aom -aribsub -bidi -bluray -cddb -chromecast -dav1d -dc1394 -debug (-directx) -fadd -fluidsynth -gnome-keyring -gstreamer -ieee1394 -jack -kate -libtar -libtiger -linsys -live -mtp -musepack -optimisememory -projectm -rdp -run-as-root -samba -sdl-image -sftp -shout -skins -srt -taglib -test -tremor -vdpau -vpx -wayland -zeroconf

ffmpeg was compiled with USE="X alsa amr amrenc bzip2 chromium codec2 cpudetection dav1d encode fdk fontconfig frei0r fribidi gcrypt gme gmp gnutls gpl hardcoded-tables iconv jpeg2k kvazaar ladspa libass libcaca libdrm librlbc librtmp libsoxr libv4l libxml2 modplug mp3 network openal opencl opengl openh264 openssl opus oss pic postproc pulseaudio rubberband sdl snappy speex srt ssh static-libs svg theora threads truetype twolame v4l vaapi vidstab vorbis wavpack x264 x265 xvid zeromq zlib zvbi (-altivec) (-appkit) -bluray -bs2b -cdio -chromaprint (-cuda) -debug -doc -flite -gsm -iec61883 -ieee1394 -jack -libaom -libaribb24 -libressl -libtesseract -lv2 -lzma (-mipsdspr1) (-mipsdspr2) (-mipsfpu) (-mmal) -samba -test -vdpau -vpx -webp -zimg"

VLC can see the stream perfectly fine, so it's not a VLC issue

**Comment by notr1ch** [comment]
Please include a backtrace.

**Comment by notr1ch** [comment]
Actually gonna go ahead and close this, you're doing way too many unsupported things. OBS is meant to be used with real hardware and is not designed to run headless.

**Comment by reavessm** [comment]
I figured it out.  Instead of using a 'vlc' source, I used a 'media' source, unchecked the 'local file' and added the rtmp URL.  The performance was still pretty bad though.  Around 15 fps.  Disabling the scene preview allows OBS via ssh to run at full speed.  If you have spare cpu and are network bottlenecked, you can look into compressing the SSH connection via the '-C' option.  Now to play with VAAPI...
