### ISSUE TITLE
Getting-Started-With-OBS-Studio-Development - legacy mantis reference

### ISSUE THREAD

**Issue by kosmisk-dk** [obsproject/obs-studio#3045]
## Platform
Wiki
## Expected Behavior
Tell us where bugs are reported

## Current Behavior
Leads us to read-only mantis installation

## Steps to Reproduce
Go to https://github.com/obsproject/obs-studio/wiki/Getting-Started-With-OBS-Studio-Development
Find section 4
Get misdirected

**Comment by RytoEX** [comment]
I've updated the wiki.  For the record, the wiki is open to public editing, so anyone can make changes to fix things like this.  Thank you for bringing it to our attention.
