### ISSUE TITLE
Preview window not working in sway window manager (wlroots)

### ISSUE THREAD

**Issue by ruabmbua** [obsproject/obs-studio#3052]
## Platform

Operating system and version:
* ArchLinux kernel 5.6.15-arch1-1
* sway window manager

OBS Studio version: OBS Studio - 25.0.8-1 (linux)

## Expected Behavior

Be able to see preview video with all its layers.

## Current Behavior

Preview is transparent, and shows windows / desktop background below, when using wayland. Preview is black, when using xwayland.

## Steps to Reproduce

1. Just start OBS in sway window manager.
https://gist.github.com/ruabmbua/f61daa3eaf70797a93f660d626d7b6a5
![obs_sway](https://user-images.githubusercontent.com/2522373/84059639-3caa6580-a9bb-11ea-8d46-c5a6f52db591.png)

**Comment by Fenrirthviti** [comment]
We do not current support wayland.

**Comment by kkartaltepe** [comment]
Feel free to test and provide feedback on #2484 (Does not include wayland capture methods)

**Comment by ruabmbua** [comment]
Will try :+1:
