### ISSUE TITLE
yuv444p16 video sources have bad chroma conversion

### ISSUE THREAD

**Issue by marcan** [obsproject/obs-studio#3057]
## Platform
Operating system and version: Arch Linux
OBS Studio version: 25.0.8
ffmpeg version n4.2.2

## Expected Behavior
Videos that decode to yuv444p16 or yuva444p16 (e.g. ProRes 4444 stuff) should be correctly converted to other pixel formats.

## Current Behavior
It seems every other chroma sample is dropped, and replaced with the previous one. This creates fairly nasty chroma artifacts.

Correct output on the top, incorrect output on the bottom:

![image](https://user-images.githubusercontent.com/98387/84360368-ea5c8500-ac04-11ea-94df-2291961e2d67.png)

## Steps to Reproduce

Try one of these files in a media source and observe the result vs. other media players:

* https://mrcn.st/t/chromasiting_prores.mov
* https://mrcn.st/t/chromasiting_v1.mov

You can try other pixel formats like this:

`ffmpeg -i chromasiting_prores.mov -pix_fmt yuv422p -c:v ffv1 chromasiting_v1_yuv422p.mov`

## Additional information
yuv444p works well, so it's something specific about the yuv444p16 variant.
yuv422p displays as intended too (half horizontal chroma res, looks better than the mangled output from yuv444p16), but crashes OBS after stopping and starting the source a few times, so it seems there's likely a memory corruption bug in there somewhere too.

**Comment by kkartaltepe** [comment]
Please provide a backtrace from a crash.

**Comment by marcan** [comment]
That's a different problem, I just mentioned it because I ran into it while debugging this one. I'll open a different issue once I get a chance to properly repro it and get a backtrace.

**Comment by jpark37** [comment]
@jp9000 There's a couple ways to solve this. One is to update the closest_format() with the extra YUV444P and YUVA444P formats, and have OBS perform the YUV to RGB conversion with its own shader. The other change that seems to work is to replace SWS_FAST_BILINEAR with SWS_POINT. We don't use swscale for width/height scaling here, so bilinear filtering seems pointless. Was that necessary for some reason?

**Comment by jpark37** [comment]
Jim says he doesn't remember, so I've marked the PR as ready.
