### ISSUE TITLE
'Save projectors on exit' resets OBS window position and sizing (Mac)

### ISSUE THREAD

**Issue by 8times9** [obsproject/obs-studio#3059]
## Platform
macOS 10.15.5
OBS 25.0.8

## Expected Behavior
Window size and position for the OBS main window should be preserved regardless of whether the 'Save projectors on exit' option is enabled or not.

## Current Behavior
When the option 'Save projectors on exit' (in Settings > General > Projectors) is enabled, the window sizing and positioning of OBS is reset upon exiting and restarting. When the option is disabled, window size and position is remembered as expected.

## Steps to Reproduce
1. Enable 'Save projectors on exit'
2. Configure a fullscreen or windowed projector via the right click menu on the preview
3. Click Exit and close OBS
4. Open OBS again and regardless of previous window positioning, the window is reset to the below size in the top right corner of the primary display.
<img width="1191" alt="Screen Shot 2020-06-11 at 1 46 40 PM" src="https://user-images.githubusercontent.com/35514663/84427105-fbe46380-abe9-11ea-8b1c-f52534b25497.png">

**Comment by WizardCM** [comment]
I cannot reproduce this on 10.14.

**Comment by blsz** [comment]
I see this on 11.2 when an external monitor is attached.
https://obsproject.com/forum/threads/bug-window-layout-size-not-being-saved-recalled.124634/

**Comment by RytoEX** [comment]
We cannot reproduce this on OBS Studio 28.0.2 on macOS 12. If this is still an issue, please comment and we can consider reopening this issue.
