### ISSUE TITLE
OBS crashes when playing webm in vlc source

### ISSUE THREAD

**Issue by duncte123** [obsproject/obs-studio#3064]
## Platform

Operating system and version: 10.0 build 18362 (revision: 900; 64-bit)
OBS Studio version: 25.0.8

## Expected Behavior
I would expect obs to play the webm file in the vlc source

## Current Behavior
OBS crashes

## Steps to Reproduce

1. Add a new vlc source
2. Add a single webm file to the playlist
3. Press apply

## Additional information
The crash report:
[Crash 2020-06-13 19-03-23.txt](https://github.com/obsproject/obs-studio/files/4775061/Crash.2020-06-13.19-03-23.txt)

**Comment by notr1ch** [comment]
Is your VLC up to date? Does the file play back OK in VLC?

**Comment by duncte123** [comment]
Nope and nope.

After updating vlc to version 3.010 the file does not play either

**Comment by notr1ch** [comment]
Your .webm file is likely corrupt in some way that's causing this. If VLC is also crashing or unable to play the file this is likely an upstream bug in VLC and I'd suggest reporting it there.
