### ISSUE TITLE
Streamed/recorded audio starts stuttering, requiring an OBS restart to fix

### ISSUE THREAD

**Issue by marcan** [obsproject/obs-studio#3069]
Sometimes, with unclear triggers, stream and recording output from OBS breaks up like this:

https://mrcn.st/t/obs_audio_malfunction.mp4

This is an insidious bug that hit me three times during an 8-hour stream today, requiring OBS (and stream) restarts to fix. I've heard of similar things from another long event streamer. I don't have concrete repro steps yet, but I want to open this bug while I investigate, because I could use any hints the devs might have to help debug/repro this. I apologize for not using the usual template (yet). I will edit things once I have more concrete info.

The setup was basically one or more active RTMP ffmpeg sources, and an active JACK source. There are a lot of other inactive sources at any given time (mostly RTMP, some misc JACK capture sources and one ALSA one). It has happened to me with both 44.1kHz and 48kHz sources on a 48kHz configured OBS.

* The first time there was one 44.1kHz RTMP source and a pending (no stream yet, so no data/rate) RTMP source + 48kHz JACK source.
* Another time there was one 48kHz RTMP source + 48kHz JACK source active I believe
* Last time it happened there was only a single active RTMP source at 48kHz, plus two JACK sources at 48kHz, an ALSA one configured for 48kHz but the underlying device only supports 96kHz, so OBS must be using that)

* The bug manifests in both the stream and the recorded output, even when the recording is using a separate encoder, or even PCM as was the case here (the above mp4 is transcoded, the recording was PCM). So it's not an encoder problem. The breakups are identical in both outputs.
* The bug is *not* apparent in monitoring output, which makes it particularly insidious, since you won't notice until people tell you it's broken. This makes me think the problem is in the OBS audio mixbus, since (at least on Linux) monitoring opens up a new PulseAudio client per source, i.e. there is no internal mixing for monitoring.
* It's hard to correlate the times the bug appears to wall clock time and thus logs (since you can only tell by the stream/rec timestamps, and I expect that might slip a bit if there are glitches/drops), but I was able to correlate two of the instances to toggling monitoring on/off for a source in the logs (within a few seconds). However, I just mashed my buttons to do that for a few minutes now while streaming without successfully reproing it, so it's not that easy. There are no error messages or other abnormal log entries. It happens silently.
* Looking back at old test recordings, this has happened to me in the past, though not during a prior 8h stream a month ago (probably just luck since it did happen in a pre-test recording).

Older test recordings showing a similar issue, in this case it seemed to happen on transitions:

https://mrcn.st/t/obs_audio_malfunction_older.mp4
https://mrcn.st/t/obs_audio_malfunction_older2.mp4

Two Windows users have reported what sounds like the same problem, and it has also been seen on other streams.

Related forum post: https://obsproject.com/forum/threads/sudden-choppy-audio-on-stream-output.80936/

## Platform
Operating system and version: Gentoo Linux
OBS Studio version: 25.0.8 (was 25.0.3 when I first saw it in the "older" recordings above).

**Comment by Fenrirthviti** [comment]
I would recommend keeping discussion going in the forum thread until proper replication steps can be identified. I am going to close this for now as there is unfortunately no actionable steps we can take, and this is not a verified or complete report. Please use the forum thread for further discussion, once replication steps are identified feel free to open a new report.

I would also recommend not deleting large parts of our report template in the future, as it makes parsing reports unnecessarily difficult.

**Comment by marcan** [comment]
There was no useful developer feedback in the forum thread, just users blindly trying things (some of which are obviously irrelevant, e.g. bitrate changes). I am myself a developer, and was hoping to get some useful feedback here while I try to figure out repro steps.

If the developers are not interested in helping experienced users root cause nontrivial and rather painful heisenbugs, that's not a great support experience, is it? It's one thing to want clear repro steps for bugs that are consistently reproducible, but this one isn't. I can say with absolute certainty that there was nothing special I did that explicitly triggered the bug, that I didn't do at other times. I'm not even fully convinced that it's correlated with monitoring state changes yet.

I deleted parts of the template because I do not have repro steps yet, and was going to add them back once I did. So far my repro attempt (by automating a lot of monitoring state changes) has instead ended up crashing OBS another way, so now I get to yak shave another bug first 🤷‍♂️

**Comment by WizardCM** [comment]
In that case, you may have better luck coordinating with support volunteers & contributors in the Discord, where most of us are quite active https://obsproject.com/discord

**Comment by Fenrirthviti** [comment]
The issues page is restricted to verified bug reports with replication steps right now. I apologize if my response came off harsh, but we need to be strict to avoid flooding our issues page with unactionable reports. It's easy to say "I'll update this later" but how do we know you won't forget  about it or become busy and then this issue is left to rot without enough details for us to do anything with? It's not a risk I am currently willing to take, as our previous bug tracker (Mantis) is filled with reports like that where the original reporter submitted half a report and then stopped responding. It is not personal, and we're happy to help take a look, but doing the support over github issues is not where we want to do this right now. I hope you can understand.

I'd definitely recommend trying the Discord and bringing up your findings in the #development channel for discussion to see if things can be narrowed down further.

**Comment by marcan** [comment]
I'm used to these kinds of issues being worked out in bug trackers (with the usual solution to the issue rot issue being that if a developer asks for further info and gets no reply, a few months later the issue can be closed as non-actionable). If you prefer Discord that's fine, just please mention that up front, as clearly that forum thread I linked was not engaged with in any meaningful way with devs so that option clearly didn't work :-)
