### ISSUE TITLE
Screen sharing of projector on google chrome show studio.

### ISSUE THREAD

**Issue by matheod** [obsproject/obs-studio#3070]
**Disclaimer :** this issue might be more related to google chrome than Obs, I don't know. Feel free to close this issue if you think it's not an OBS issue

## Platform
Operating system and version: Windows 10
OBS Studio version: 25.0.8 (64bit)

## Expected Behavior
- Screen sharing of projector on google chrome only share the projector window

![image](https://user-images.githubusercontent.com/339611/84609090-c96e8b00-aeb5-11ea-9188-a14e4a66e433.png)

## Current Behavior
- Screen sharing of projector on google chrome show the studio UI when it is above the projector window

![image](https://user-images.githubusercontent.com/339611/84609103-dab79780-aeb5-11ea-8911-4d02913fdbef.png)

## Steps to Reproduce
1. Project a scene in window mode
2. Open any website on chrome that allow to share screen to other and share the projector window. You can also use this website as example : https://www.webrtc-experiment.com/Pluginfree-Screen-Sharing/
2. Bring up the OBS studio Ui and move it above the projector window
3. Instead of only sharing the projector window, it also share the OBS studio UI

## Additional information
The bug happen on google chrome but does not happen on firefox.

**Comment by dodgepong** [comment]
This indeed sounds like a Chrome issue, not an OBS issue.

**Comment by matheod** [comment]
(for information, chromium issue created : https://bugs.chromium.org/p/chromium/issues/detail?id=1094838)
