### ISSUE TITLE
Scripts dialog Add button freezes on OBS 25.0.3+dfsg1-2 (linux)

### ISSUE THREAD

**Issue by metal450** [obsproject/obs-studio#3075]
Summary: Cannot add LUA scripts via the Scripts dialog (freezes when clicking "+").

Steps:
1) Tools->Scripts.
2) In the Script dialog, click "+."
3) The background of the button lightens, as if it's being pressed, but nothing else happens.
4) Attempting to close the Scripts dialog now produces "Application obs is not responding," & has to be terminated.

Operating system and version: Kubuntu 20.04, KDE Plasma 5.18.5, Qt 5.12.8, Kernel 5.4.42
OBS Studio version: 25.0.3+dfsg1-2 (64-bit) (installed from the default repo)

**Comment by kkartaltepe** [comment]
Use the official repository instead. If you can replicate it on that we can consider re-opening.

**Comment by metal450** [comment]
Removed & reinstalled from ppa:obsproject/obs-studio. The version is now 25.0.8 (linux). Behavior & bug described above are identical.

**Comment by Fenrirthviti** [comment]
Please update the original post to follow our template. and provide a gdb trace of the issue.

**Comment by metal450** [comment]
You mean you want me to just rearrange the information that's currently there so it has headings?  Ok....done.

gdb trace: please provide a link to where the OBS docs describes how to do this?

**Comment by metal450** [comment]
This issue remains closed, but has not been fixed.  Doesn't seem like I have the ability to reopen it -  I think @kkartaltepe was going to do once I confirmed that it applies to the version in your repo same as the version in the default repo.
