### ISSUE TITLE
VST UI blanks when plugin draw area changes size

### ISSUE THREAD

**Issue by ngollan** [obsproject/obs-studio#3076]
## Platform

Operating system and version: Windows 10 amd64 1909
OBS Studio version: 25.0.8

## Expected Behavior

When the UI of a VST plugin changes size, it should still be drawn.

## Current Behavior

The UI window stays the same size but goes blank (grey background).

## Steps to Reproduce

1. Install a VST plugin with variable UI size, e.g., https://www.bluecataudio.com/Products/Product_TripleEQ/ (Win x64 VST).
2. Set it up as filter on an audio channel and open the UI.
3. Click any of the buttons that would lead to the UI changing size (in TripleEQ: "zoom", "show controls", or "show graph").

**Comment by PatTheMav** [comment]
Cannot reproduce with OBS 28.0.3 on macOS, alas I only have an arm64 Windows 11 installation available to me, so maybe someone else with an x64 installation can check on Windows.

**Comment by RytoEX** [comment]
Win11 x64 here. I do not get a blank/gray background. I do get a white background, but only on non-filled areas. The UI otherwise works fine, even if there are other visual issues.

![image](https://user-images.githubusercontent.com/624931/194667361-d2ad774c-7555-4c95-934b-dd51a0145662.png)

**Comment by WizardCM** [comment]
Yes this issue should have been fixed in 27.2 via https://github.com/obsproject/obs-vst/pull/102

**Comment by ngollan** [comment]
Just tried it again and it appears to be working as expected now 👍
