### ISSUE TITLE
Why QT

### ISSUE THREAD

**Issue by thomrainier** [obsproject/obs-studio#3077]
Why is obs-studio being built only using QT, do you know how bad qt based apps look running on gtk based gnome? How would I build obs with gtk instead of qt?

**Comment by henke37** [comment]
You are free to make your own replacement using `libobs`.

As for why? It's a lot of work to make just one version of the GUI. There isn't enough motivation to duplicate the work by doing it all over with another gui framework.

**Comment by notr1ch** [comment]
Qt is a hard dependency, is it not possible to build OBS without it. Closing as this isn't an issue but a question better posted on the forums or Discord chat.
