### ISSUE TITLE
Can't record some games fullscreen

### ISSUE THREAD

**Issue by samOki27** [obsproject/obs-studio#3079]
Hi There,
I have noticed that OBS-Studio cannot record games that are written in Java. When selected they just give a black screen. Is there a way to fix this or no?

**Comment by RytoEX** [comment]
OBS can record Minecraft Java Edition just fine.  I can also confirm that it can capture other Java applications.  This sounds like a misconfiguration, which can be addressed via our support channels.  Please use the support forums or Discord for support requests.

https://obsproject.com/help
