### ISSUE TITLE
Linux Advanced Streaming FFMPEG VAAPI settings aren't used

### ISSUE THREAD

**Issue by trapexit** [obsproject/obs-studio#3081]
## Platform

Operating system and version: Ubuntu Linux 20.04
OBS Studio version: 25.0.8

## Expected Behavior
Use selected rate control type when using FFMPEG VAAPI for streaming.

## Current Behavior
When changing to Encoder FFMPEG VAAPI in the Output panel in Advanced and selecting any options it is failing to properly use the Rate Control method selected. The logs indicate only CQP is supported but when selected and streaming is started it lists CBR as being used and fails. When doing the same for recording it seems fine. Other settings such as level, bitrate, etc seem to be properly saving and being used. Just the rate control doesn't work. 

Tried this on an older Mint Linux system and it worked fine. The config files show the proper values. Just not being passed to ffmpeg it seems.

**Comment by kkartaltepe** [comment]
If you have "Enforce streaming service encoder settings" enabled which will expectedly enforce CBR.

Feel free to attach a log and confirm that it happens when you dont have this setting enabled and we can consider reopening.
