### ISSUE TITLE
OBS crashes in game capture source

### ISSUE THREAD

**Issue by zsm1703** [obsproject/obs-studio#3082]
## Platform

Operating system and version: Windows 10 version 2004 (10.0.19041.329).
OBS Studio version: 25.0.8 (64-bit, windows).

## Expected Behavior

OBS should get game source captured.

## Current Behavior

OBS crashes.

## Steps to Reproduce

1. Add new game capture source by create new.
2. Select "Capture any fullscreen application" / "Capture specific window".
3. Launch a fullscreen application and OBS crashes / Select target window (any application) and OBS crashes.

## Additional information

https://obsproject.com/logs/aywa2FUBbNdVq0k-
https://obsproject.com/forum/attachments/obscrashed-log.57149/
crash logs above.

**Comment by Fenrirthviti** [comment]
What application exactly are you trying to capture? We will probably need a memory dump to be able to investigate this further as this looks to be some kind of conflict crash.

https://obsproject.com/forum/resources/598/

**Comment by zsm1703** [comment]
> What application exactly are you trying to capture? We will probably need a memory dump to be able to investigate this further as this looks to be some kind of conflict crash.
> 
> https://obsproject.com/forum/resources/598/

e.g. Steam games.
Dump created by start Bejeweled3 from Steam, OBS using specific windows mode and select Bejeweled3 window.
Target process name: Bejeweled3.exe
Dump file: https://send.firefox.com/download/a9c96ed51fa28f93/#XRfz98M3G2CZazOE3bk0DA

**Comment by notr1ch** [comment]
Your cheat that tries to use OBS to insert cheats into multiplayer games is causing this crash. No further support will be given for this use case.
