### ISSUE TITLE
Problem with OBS, an Avermedia grabber and a RaspBerry PI 4 mode B

### ISSUE THREAD

**Issue by Residentcl** [obsproject/obs-studio#3086]
## Platform

Operating system and version: Windows 10 - November 2019 Update - 64 BIT.
OBS Studio version: OBS 25.0.8 (64 bit).

## Expected Behavior

See the video of the raspberry without problems.

## Current Behavior

Video is output with video signal problems.

## Steps to Reproduce

1. https://www.youtube.com/watch?v=UaWwelrO0cY
2.
3.
4.

## Additional information

The full detail of my team:
With the Aver MediaCenter 3D program I have no problems.

System: Windows 10 - November 2019 Update - 64 BIT.

Motherboard: Asus H87M-E. BIOS 2201

CPU: Intel Core I7-4770.

RAM: Kingston HyperX DDR3 1866 C10 4x4GB.

GPU: Asus Radeon 590 - 8 GB - ROG-STRIX-RX590-8G-GAMING.
Driver: Radeon Software Adrenalin 2020 Edition 20.5.1

OBS 25.0.8 (64 bit).
Avermedia driver: 1.7.9.97.17090701_Drv_1.54.x.82.
Raspberry Pi 4 Model B - 4 GB.

Display 1 and 2: LG - Product No: LG 29UM68-P.
               Display: Current Mode: 2560 x 1080 (32 bit) (60Hz)
               Mode: horizontal.
               Radeon freeSync: off.
               Monitor input: Displayport.
               Graphic card output: Displayport.

Display 3: LG - Product No: LG 29UM68-P.
               Display: Current Mode: 2560 x 1080 (32 bit) (60Hz)
               Mode: vertical.
               Radeon freeSync: off.
               Monitor input: HDMI.
               Graphic card output: HDMI.
         

HDD: OS: Crucial MX500 SSD 500GB SATA 3 (6Gb / s)
           SanDiSK x110 SSD 120GB SATA 3 (6Gb / s)
           Seagate BarraCuda ST1000DM010 1TB 7200 RPM SATA 3 (6Gb / s)
           Western Digital Blue 500 GB WD5000AAKX SATA 3 (6Gb / s).

Power supply: Seasonic FOCUS 80Plus Gold - 850 Watts.

**Comment by kkartaltepe** [comment]
Github issues are not for support. Please use the forum or discord.
