### ISSUE TITLE
OBS Game capture functionality not work when changing Game to Full Screen Mode or to Windowed Mode

### ISSUE THREAD

**Issue by tierre0703** [obsproject/obs-studio#3094]
## Platform

Operating system and version: Win 10
OBS Studio version: this bug exists since the latest update of Game Capture-Graphics-Hook

## Expected Behavior

Once OBS's graphics-hook injected to the Target Game, when changing the game from windowed mode to Full-Screen or vice versa, OBS Studio should output the Game Screen without failure. 
## Current Behavior

But from the latest update of the graphics-hook of the OBS, (I think this bug exists from the beginning of the Game-Capture Functionality.), in the above situation, OBS fails to show the Game Screen.
This Bug is from the dxgi hook:
dxgi-capture.cpp line#130
```cpp
static HRESULT STDMETHODCALLTYPE hook_present(IDXGISwapChain *swap,
		UINT sync_interval, UINT flags)
```
Here when changing the game screen into Full-Screen mode or vice versa, the _IDXGISwapChain *swap_ changed, that  _data.capture_ part failed to be executed.
```cpp
if (capture && capture_overlay) {
		/*
		 * It seems that the first call to Present after ResizeBuffers
		 * will cause the backbuffer to be invalidated, so do not
		 * perform the post-overlay capture if ResizeBuffers has
		 * recently been called.  (The backbuffer returned by
		 * get_dxgi_backbuffer *will* be invalid otherwise)
		 */
		if (resize_buffers_called) {
			resize_buffers_called = false;
		} else {
			backbuffer = get_dxgi_backbuffer(swap);

			if (!!backbuffer) {
				data.capture(swap, backbuffer, capture_overlay);
				backbuffer->Release();
			}
		}
	}
```
**_swap_** changed, that the above code stuff cannot be run, which result the OBS Studio fails to output the Game Screen.

## Additional information

I think this bug is crucial for the OBS Lovers  or most of the people who use OBS for Game Broadcasting, and I wish if you can update this bug-fix and expecting the update asap.

Thank you for your support and sorry for my poor explanation.

**Comment by RytoEX** [comment]
We cannot reproduce this on OBS Studio 28.0.2. If this is still an issue, please comment with a log file of an OBS 28.0.2 (or newer) session from where it happens, and make sure to include the title of the game that you are trying to capture.
