### ISSUE TITLE
Show/Hide sources with audio

### ISSUE THREAD

**Issue by Bmille916** [obsproject/obs-studio#3105]
## Platform

Operating system and version: Windows ver. 1909
OBS Studio version: 25.0.7-63-g56e4b1e6

## Expected Behavior

I expected that when i would hide the source with a luma wipe, the audio would hide as well.

## Current Behavior

Instead, the audio from either a vlc playlist and a video continued to play

## Steps to Reproduce

1. Video source with audio
2. Luma wipe show/hide transition
3. Show then hide or vice versa depending on the transition to activate it
4. Audio remains

## Additional information

I will add that i tried this when a nested scene with VLC audio and a video source with audio. Both had this bug.

**Comment by Fenrirthviti** [comment]
I'm unsure what you mean by "hide a source with luma wipe". Do you mean that you changed scenes? How are you hiding the source specifically?

This sounds like a support issue more than anything, it might be best for you to stop by our [Discord](https://obsproject.com/discord) instead.

**Comment by Bmille916** [comment]
I apologize, this was for an experimental build of OBS.

**Comment by Fenrirthviti** [comment]
Going to close this issue then. I assume you're referring to the test build for visibility transitions. I'd recommend reporting this on the PR for that instead of as an issue as that code has not been reviewed or merged.
