### ISSUE TITLE
Intel QSV Encoder for Video Sizes Larger than 1920x1080 Crashes Immediately

### ISSUE THREAD

**Issue by reece146** [obsproject/obs-studio#3107]
When using Intel QSV as encoder for video sizes larger than 1920x1080 starting recording crashes immediately.

This is on an admittedly old platform and I have not been able to test on a newer platform. Platform is i7-3770K Ivy bridge. Latest Intel iGPU drivers or oldest I could find or Windows 10 offered driver does not seem to make a difference.

Operating system and version: Windows 10 (2004)
OBS Studio version: 25.0.8

## Expected Behavior

Selecting video base/canvas resolution at 2560x1440 and outputting at 2560x1440 should allow recording.

## Current Behavior

Crashes immediately after pressing 'start recording'.

Workaround is to select output scaled resolution of 1920x1080.

## Steps to Reproduce

1. Configure for recording. Game Capture and/or Display Capture does not seem to matter.
2. Configure Settings -> Output -> Recording, Ecnoder to use Quicksync
3. Configure Settings -> Video -> Base and Output to 2560x1440
4. Press 'Start Recording'

## Additional information
1.) Used old and newest Ivy Bridge Intel drivers. 9.18.10.3222, 15.33.48.5069, 15.33.50.5129
2.) Tried OBS 25.0.8 and 23.2.1. Reproducible in all combinations.
3.) According to Intel specifications for Graphics 4000 (Ivy) max resolution is larger than 2560x1440.
4.) Crash log attached.

[Crash 2020-06-24 22-18-13.txt](https://github.com/obsproject/obs-studio/files/4832926/Crash.2020-06-24.22-18-13.txt)

**Comment by Fenrirthviti** [comment]
Did you forget to attach the crash log? I don't see it here.

**Comment by reece146** [comment]
Should be there now.

**Comment by RytoEX** [comment]
I cannot reproduce this on an Intel HD Graphics 630 (i7-7700HQ) with driver 30.0.101.1069 in either OBS Studio 27.1.3 or 27.2.0. Can you please re-test and confirm if this is still an issue? I can try to get access to an Ivy Bridge system tomorrow.

If this is still an issue, please provide an updated OBS session log and OBS crash log.

**Comment by RytoEX** [comment]
I cannot reproduce this on an Intel HD Graphics 4000 (i5-3570K) with driver 10.18.10.4252 on OBS Studio 28.0.3 on Windows 10 1803 (17134.1304).
