### ISSUE TITLE
broken AMD encoder

### ISSUE THREAD

**Issue by killer983** [obsproject/obs-studio#3111]
## Platform

Operating system and version: Windows 10 May Update 2020
OBS Studio version: 25.0.8

## Expected Behavior

A smooth 1080p60 video with a bitrate of 10000-20000Kbps depending on the game
## Current Behavior

Losing most of the frames and the video seem like a succession of photos
## Steps to Reproduce

1. open obs
2. choose AMD hardware decoder from your graphics and choose any high or low bitrate 
3. start recording
4.

## Additional information

Show the overload message in the encoder all the time still and using any quality profile.
Programs that were being recorded for performance tests the ghost recon wildlans and the division 2 (performance tests of these).
Using the graphics driver software itself the video is completely smooth even with higher bitrate and less fps is lost in the game

**Comment by skeletonbow** [comment]
This is more of a technical support issue than a bug report, best handled by using the OBS support forums or Discord server #windows-support channel.

**Comment by notr1ch** [comment]
Closing as this is a support issue.
