### ISSUE TITLE
Crash OBS Studio 25.0.8 (x64) in Windows (x64)  (NDI Plugin 4.9.0 Error)

### ISSUE THREAD

**Issue by rafaelholeva** [obsproject/obs-studio#3112]
Bug Ndi In Obs Studio 25.0.8 (x64) for Windows 7 Professional (X64)

After active exit from the mother of ndi in obs studio, the same crashes.

Hello guys from the ndi plugin. I'm using Windows 7 Professional (x64) with all the updates ok, trying to use the NDI plugin in OBS Studio version 25.0.8 (x64) without success. Downloading the plugin (NDI) version 4.9.0 and installing with its respective dependency on (NDI 4 Runtime) version 4.5.1 (x64). After opening OBS and activating the NDI output in "Tools"> Active "MAIN, NDI Output", Close the program and open it again, it returns an error message and closes the program. I believe it is a matter of x86 incompatibility with x64. Users of windows 10 (x64) 2004 are also reporting the same problem, it seems that the problem extends to all versions of windows (x64), because in version * (x86) it seems to work perfectly.
I am forwarding a link to the error log and also a screenshot of the screen so that someone can evaluate it. more details, you can follow the problem on the obs forum too.]

Thank you

Log Error:
https://obsproject.com/logs/YnOzjjYkB19SKaQG

Link problem to Forum:
https://obsproject.com/forum/threads/ndi-plugin-error-in-obs-studio-25-0-8-x64.125341/

**Comment by notr1ch** [comment]
The NDI plugin is not part of the core OBS plugins. You may want to report this at https://github.com/Palakis/obs-ndi.
