### ISSUE TITLE
obs_service_get_output_type is used inconsistently

### ISSUE THREAD

**Issue by henke37** [obsproject/obs-studio#3115]
The function `obs_service_get_output_type` is supposed to merely call a service provided callback and return a value. However, three of the callers do further adjustments of the result in duplicate code. The only other callers are scripting bindings that nobody uses.

The adjustment code needs to be rolled into the function itself, to solve both the duplication and ensure that all callers get the _same_ adjusted value.

**Comment by WizardCM** [comment]
Please fill in the issue template.

**Comment by tt2468** [comment]
Also, plugins use this function (example obs-websocket), so changing the behavior of the function would break plugins.

**Comment by henke37** [comment]
It would not break plugins. The api would remain the same.
