### ISSUE TITLE
UI: Save Replay button stays at checked state

### ISSUE THREAD

**Issue by SuslikV** [obsproject/obs-studio#3116]
## Platform
OS: Any
OBS Studio: v25.0.8+

## Expected Behavior
The button should reset its state after the save replay buffer operation is complete.

## Current Behavior
The button changes its state on each click. 

## Steps to Reproduce
1. _Start Replay Buffer_ (new button to "Save Replay" will appear right to it).
2. Click "Save Replay" button right to the _Start Replay Buffer_ button.
3. Despite existing UI themes lacks the "checked" icon state drawing, the enhanced (custom ones) clearly indicates that button stays checked until next mouse click.

## Additional information
The checked button was used here to draw the button similar to "Pause" button of the casual recording:
https://github.com/obsproject/obs-studio/blob/e2fa510436b48d7bdfc1b76cf7bb2d2e4e57d304/UI/window-basic-main.cpp#L7622-#L7623

but for "Save Replay" the checked state is never resets on file operation complete.

The behavior can be visualized by the next changes to Themes (add code to the end of the any `.qss` file), just for example:

```
QPushButton[themeID="replayIconSmall"] {
	border-image: url(./Rachni/checkbox_checked.png);
}

QPushButton[themeID="replayIconSmall"]:checked {
	border-image: url(./Rachni/checkbox_checked_disabled.png);
}
```

**Comment by WizardCM** [comment]
Not quite sure why this button was configured to be checkable, but we have two options. Automatically uncheck it immediately after click, or remove this line:

https://github.com/obsproject/obs-studio/blob/5889e2905ef6f046a1e011a3e1004e9650d735f0/UI/window-basic-main.cpp#L8210

**Comment by RytoEX** [comment]
Possibly to account for a save action that takes long enough that retriggering save would be bad and we should indicate that to the user?  Not entirely sure.  It could also have just been "the other buttons are all checkable, so this one will be too".

**Comment by WizardCM** [comment]
@RytoEX As far as I can tell, I don't think it's the former. It doesn't check the checked state before triggering, and you can mash the hotkey if you like. The function itself doesn't return anything either. The latter seems most likely.
