### ISSUE TITLE
Emoji / Symbols are not displayed in Text Sources (OBS 25.08 mac)

### ISSUE THREAD

**Issue by i3games** [obsproject/obs-studio#3127]
## Platform
Operating system and version: Mac OSX 10.15
OBS Studio version: 25.08

## Expected Behavior
Entering an Emoji / Symbol in a Text Source should display that Emoji / Symbol

## Current Behavior
Entering an Emoji / Symbol in a Text Source displays a white rectangle.

## Steps to Reproduce
1. Add a Text Source
2. In the Text field, enter an Emoji or Symbol (Edit > Emoji & Symbols)
3. Click OK
4. The Text field contains the Emoji or Symbol but the Text Source does not display it, instead a white rectangle is shown.

## Additional information
The same happens if "read from file" is chosen and the emoji is read from an UTF-8 encoded file.

**Comment by WizardCM** [comment]
Correct, this is a limitation of two things:
1) the Freetype library
2) The font you're using

If you fix 2) by using an emoji font (Apple Color Emoji in your case) it should help, but they may be simplified versions.

I personally recommend the [text-pango plugin](https://obsproject.com/forum/resources/text-pango-multi-language-and-emoji.656/), which has full emoji support.

This is not something OBS can or will fix, unfortunately.

**Comment by i3games** [comment]
Thanks for the link to the plugin. Just for info - if somebody else stumbles across this. It does not depend on the font used (it is a UTF problem in the library chosen). Apple Color Emoji does not work.

**Comment by davemacdo** [comment]
> Correct, this is a limitation of two things:
> 
> 1. the Freetype library
> 2. The font you're using
> 
> If you fix 2) by using an emoji font (Apple Color Emoji in your case) it should help, but they may be simplified versions.

Actually, I find that selecting Apple Color Emoji does not resolve the issue. 

> I personally recommend the [text-pango plugin](https://obsproject.com/forum/resources/text-pango-multi-language-and-emoji.656/), which has full emoji support.
> 
> This is not something OBS can or will fix, unfortunately.

Pango is ok, but it doesn't seem to support any emoji that were added in the last couple of years. Based on this, it probably _is_ something that OBS can fix with some encoding changes, but I don't think it's likely to be a priority. 

Sorry to bug those on the thread. Mostly leaving this here for others searching.

**Comment by SergioSV96** [comment]
I have the same problem with Windows 10 and OBS 27.0.1
Emojis won't display

**Comment by beetleuk** [comment]
Still the same in 2023... surely time adds priority ;-) 🥰

**Comment by raleighlittles** [comment]
2025 here and still having the same issue.. the newest version of Freetype claims that they support emojis, so I don't know if this limitation in (1) still applies

**Comment by Jeetah** [comment]
You could also try to generate a HTML page with font e.g. Verdana and use the Browser Source - that will show UTF-8 just fine
