### ISSUE TITLE
Unable to capture inner tabs within Windows Terminal

### ISSUE THREAD

**Issue by emelens** [obsproject/obs-studio#3128]
## Platform
Operating system and version: Windows 10 Home Edition
OBS Studio version: 25.4

## Expected Behavior
I am trying to make screencast using OBS. I am trying to capture Windows Terminal Preview window tabs inside which I have powershell and Windows Subystem for Linux tabs open. 

OBS should be able to capture the tabs inside the windows terminal 

## Current Behavior

OBS does not capture the tabs within Windows Terminal

## Steps to Reproduce
(Optional
1. Install WSL and Ubuntu 20.04 in windows .
) 
2. Install Windows Terminal Preview 
2.  Launch WIndows Terminal preview.
3. Open one or more tabs inside it (ex: a new Ubuntu tab inside the windows terminal)
4. Within OBS, add source and select window capture and add Windows terminal in the windows list.

**Comment by henke37** [comment]
Did you try both capture methods? The new one is reportedly very good at capturing troublesome windows the old method didn't work with.

**Comment by Fenrirthviti** [comment]
Working fine here with WGC capture, can you please confirm you are using WGC? With BitBlt the window cannot be captured at all as it is a UWP application.

https://pub.rachni.com/vid/2020-07-05_19-18-51.webm

**Comment by emelens** [comment]
I tried WGC. It is working fine. Thanks for letting me know. I think I can close this issue.
