### ISSUE TITLE
Despite mouse capture being turned on, the mouse doesn't get recorded in the code editor tab of JetBrains programs (tested with Android Studio & IntelliJ)

### ISSUE THREAD

**Issue by philipplackner** [obsproject/obs-studio#3129]
## Platform
Operating system and version: Windows 10 Pro Version 1903
OBS Studio version: 24.0.3

## Expected Behavior
When mouse capture is turned on for screen captures, it should always capture the mouse.

## Current Behavior
In JetBrains programs the mouse doesn't get captured only in the code editor tab (tested with Android Studio and IntelliJ).

## Steps to Reproduce
This is how it looks like:
https://streamable.com/zzzj0h
Someone told me, this doesn't happen on Linux, however I don't have any evidence for that. To reproduce it, just use my OBS version with Windows and a JetBrains program such as Android Studio.

**Comment by androiddevs18** [comment]
Also tested with OBS version 25.0.8, the issue still persists

**Comment by Fenrirthviti** [comment]
Which capture method are you using?

**Comment by androiddevs18** [comment]
I'm using display capture with the mouse capture option turned on. If I use window capture, it records the mouse also in the code editor tab, but it doesn't work with display capture.

**Comment by Fenrirthviti** [comment]
I can confirm this, but it looks like an issue with JetBrains' software and not with OBS. They seem to render a hardware cursor over the edit window, which means the desktop cursor is being hidden by the program. I'll let someone more familiar with the display capture code comment, however, as there might be something we can do on our side.

**Comment by androiddevs18** [comment]
Alright, interesting. Other screen capture softwares (e.g. Camtasia/Bandicam) have no problems with recording the cursor.
