### ISSUE TITLE
In zoom application for capture method windows graphics capture method (Windows 10 and above 1903 ) capturing mouse cursor even if disabled while capturing. 

### ISSUE THREAD

**Issue by suhitmaster** [obsproject/obs-studio#3130]
steps to reproduce - 
1. add window capture 
2. put zoom application 
3. capture method is windows 10 or above 
4. disable mouse capture 

current behavior - 
1. mouse capture is recording even though its disabled.

expected - 
1. mouse should not capture 

solution - 
IsCursorEnabled
Windows insiders who have opted in to skip ahead/fast rings and are running build 18994 or greater will see a new API IsCursorEnabled which supports omitting the cursor from capture. Please see all the warnings that apply to APIs in these environments.

**Comment by Fenrirthviti** [comment]
This is expected currently as WGC capture does not currently support disabling the cursor. It will be available in the next release of OBS when we upgrade the Windows SDK version we are building against.
