### ISSUE TITLE
In flv onmetadata, audiocodecid and videocodecid data types should be number

### ISSUE THREAD

**Issue by NodeBoy2** [obsproject/obs-studio#3131]
# Possible modifications 
https://github.com/obsproject/obs-studio/blob/c938ea712bce0e9d8e0cf348fd8f77725122b9a5/plugins/obs-outputs/flv-mux.c
88: enc_str_val(&enc, end, "videocodecid", "avc1"); -> enc_num_val(&enc, end, "videocodecid", 7);
95: enc_str_val(&enc, end, "audiocodecid", "mp4a");-> enc_num_val(&enc, end, "audiocodecid", 10);
reference：
- https://en.wikipedia.org/wiki/Flash_Video
- ffmpeg: videocodecid and audiocodecid must be number
![image](https://user-images.githubusercontent.com/26833659/86785979-f74e8600-c095-11ea-8be6-fe2404163216.png)

**Comment by Fenrirthviti** [comment]
Please properly fill out the issue template with what the issue you are having and how we can replicate it. It's not clear from this post if you are having an actual issue or if this is just a suggestion.

**Comment by pkviet** [comment]
The spec indeed says the metadata for codecid are double. But as @Fenrirthviti said, why bother ? the audio/video streams are usually decoded directly without compulsory reliance on the container and it's not as if it was required to provide these metadatas or any metadata btw ... For instance width/height/videodatarate medatatas will be read directly from the sps/pps headers in video stream. It's the pair h264/aac which is the de facto standard codecs for rtmp/flv ... Who's using h263/vp6 or mp3 ?

**Comment by NodeBoy2** [comment]
I have problems writing rtmpclient and parsing metada.  It is just a suggestion

**Comment by pkviet** [comment]
ok just make a pull request with the changes you wish; it's a few chars, no big deal.
Refer to this issue, and close this issue.
