### ISSUE TITLE
window_capture has a delay in MacBook（Mac）

### ISSUE THREAD

**Issue by 435129214** [obsproject/obs-studio#3135]
Recently, I was developing obs. OBS is a very powerful streaming tool, which is excellent. But I found two problems.
1. The window captured by OBS has a delay of about 1 second, and the delay time depends on the performance of the computer. But there is no delay in Windows system. I installed the same app on a Mac server with strong configuration, and the delay disappeared. Therefore, I think there is still a lot of room for improvement, and I hope it can be optimized as soon as possible.
2. On some computers, the window captured by OBS will flicker once every 3 seconds, and there will be irregular blank in some positions of the window, and then it will flash and disappear. I suspect that this has something to do with the configuration of the computer. I also hope that this problem can be fixed as soon as possible.

**Comment by WizardCM** [comment]
Please fill in the issue template.

**Comment by 435129214** [comment]
Platform

Operating system and version: Mac osx 13,14 and 15
OBS Studio version:25.0.8

Expected Behavior

Recently, I was developing obs. OBS is a very powerful streaming tool, which is excellent. But I found two problems.

1, If, when I raise my hand in zoom window, the OBS capture window has a delay of about 1 second, which depends on the performance of the computer. But there is no delay in Windows system. I installed the same app on a Mac server with strong configuration, and the delay disappeared. Therefore, I think there is still a lot of room for improvement, and I hope it can be optimized as soon as possible.
2,  On some computers, the window captured by OBS will flicker once every 3 seconds, and there will be irregular blank in some positions of the window, and then it will flash and disappear. I suspect that this has something to do with the configuration of the computer. I also hope that this problem can be fixed as soon as possible.
this happend at osx 13. Please check the picture.
截屏2020-07-08 下午3 07 35


Current Behavior

Steps to Reproduce

Additional information

**Comment by 435129214** [comment]
![](https://user-images.githubusercontent.com/16433951/86932124-85487080-c16b-11ea-8967-358f21b1ce93.png)

**Comment by Fenrirthviti** [comment]
This screenshot looks like a fork of OBS, which we do not support. Can you please test and confirm this works in the latest official release of OBS Studio and provide details on this fork?

**Comment by 435129214** [comment]
> This screenshot looks like a fork of OBS, which we do not support. Can you please test and confirm this works in the latest official release of OBS Studio and provide details on this fork?

yes, I download obs from offical to test ,has the same question.

**Comment by 435129214** [comment]
> This screenshot looks like a fork of OBS, which we do not support. Can you please test and confirm this works in the latest official release of OBS Studio and provide details on this fork?

Hold a meeting with zoom, then capture the zoom window with version 25.0.8. Raise your hand and drop it to see obvious delay, especially on low configuration computers.

**Comment by Fenrirthviti** [comment]
I am going to close this issue as you have opened a duplicate and having the same conversation across two threads is a waste of time.
