### ISSUE TITLE
window_capture  has delay and flash(Mac)

### ISSUE THREAD

**Issue by 435129214** [obsproject/obs-studio#3137]
## Platform

Operating system and version: Mac osx 13,14 and 15
OBS Studio version:25.0.8

## Expected Behavior

Recently, I was developing obs. OBS is a very powerful streaming tool, which is excellent. But I found two problems.
1. If, when I raise my hand in zoom window, the OBS capture window has a delay of about 1 second, which depends on the performance of the computer. But there is no delay in Windows system. I installed the same app on a Mac server with strong configuration, and the delay disappeared. Therefore, I think there is still a lot of room for improvement, and I hope it can be optimized as soon as possible.
2. On some computers, the window captured by OBS will flicker once every 3 seconds, and there will be irregular blank in some positions of the window, and then it will flash and disappear. I suspect that this has something to do with the configuration of the computer. I also hope that this problem can be fixed as soon as possible.Please check the picture.

> 
<img width="1099" alt="截屏2020-07-08 下午3 07 35" src="https://user-images.githubusercontent.com/16433951/86932124-85487080-c16b-11ea-8967-358f21b1ce93.png">

>

**Comment by dodgepong** [comment]
What version of OBS is in that screenshot? Where did you download it from?

**Comment by 435129214** [comment]
> What version of OBS is in that screenshot? Where did you download it from?

25.0.8 ，download from obs offical has the same question.

**Comment by dodgepong** [comment]
That screenshot is not from OBS Studio 25.0.8, it's from some sort of fork. Please fill in the complete issue template, including the steps to reproduce, as I'm not able to reproduce this issue on OBS Studio 25.0.8 for Mac.

**Comment by 435129214** [comment]
> That screenshot is not from OBS Studio 25.0.8, it's from some sort of fork. Please fill in the complete issue template, including the steps to reproduce, as I'm not able to reproduce this issue on OBS Studio 25.0.8 for Mac.

the scrrenshot Is the second question I feedback, This kind of problem is not frequently crops up.    In contrast, the first problem is serious and easy to reproduce.  Hold a meeting with zoom, then capture the zoom window with version 25.0.8. Raise your hand and drop it to see obvious delay, especially on low configuration computers.

**Comment by Fenrirthviti** [comment]
I have confirmed the slight delay when using window capture with Zoom.

**Comment by 435129214** [comment]
> I have confirmed the slight delay when using window capture with Zoom.

The delay time is related to the computer configuration. I don't know why.

**Comment by dossy** [comment]
Please help test #4863, I believe it will also fix this issue.

**Comment by gxalpha** [comment]
Closing as stale.
If there are still issues in 28.0, please open a new report.
