### ISSUE TITLE
Can't bind F13+ keys on Linux

### ISSUE THREAD

**Issue by AlexWayfer** [obsproject/obs-studio#3138]
## Platform

Operating system and version: Linux
OBS Studio version: 25.0.8-1

## Expected Behavior

F13 key input (displaying, saving) into "Hotkeys" OBS settings.

## Current Behavior

Nothing at key press.

## Steps to Reproduce

1. Bind F13+ keys to some keys on keyboard (Logitech G keyboards have additional G-keys).
2. Save it to device, reboot into Linux.
3. Open OBS.
4. Try to bind this keys for any action.

## Additional information

It works on Windows, although without localization: #2377

**Comment by Fenrirthviti** [comment]
Did you confirm that the same keyboard works under windows? Macro keys often have issues as they do not hold the keypress for a sufficient amount of time.

**Comment by AlexWayfer** [comment]
> Did you confirm that the same keyboard works under windows?

Yes. In the OBS, the same keyboard with the same keys and the same profile.

> Macro keys often have issues as they do not hold the keypress for a sufficient amount of time.

I can check it later and send a screenshot. As I remember, there is 50 ms default.

**Comment by AlexWayfer** [comment]
Screenshot of assignments in Logitech G HUB:

![image](https://user-images.githubusercontent.com/6510020/86958244-875b0100-c164-11ea-937e-12dc0cae6829.png)

They're keys, not macros. I can't change keypress duration. I guess it should be enough.

Settings in OBS on Windows:

![image](https://user-images.githubusercontent.com/6510020/86958434-d99c2200-c164-11ea-9104-cf0525747348.png)

There is nothing to screenshot on Linux… empty fields after key pressing.

**Comment by AlexWayfer** [comment]
I can try to collect some debug information if you'll direct me.

**Comment by pmichaud** [comment]
Can you perhaps verify that your windowing environment is properly mapping the keycodes?  On my Linux system (Kubuntu 20.04), I had to change the .Xmodmap settings to recognize F13..F24, as they weren't in the standard keymapping table.

The ```xmodmap -pk``` command displays the current key/modifier mapping table on the standard output -- look through it and see if F13 through F24 are listed.  If not, then the keystrokes are likely not ever getting to obs-studio from the windowing environment.

Also, run the ```xev``` command and press the F13 keys on the keyboard and see what keys are being reported.  Before I adjusted the xmodmap on my system, F13 was giving me "XF86Activity5", and obs-studio doesn't seem to honor any of the XF86* keystrokes (or it never receives them, not sure which).

For my system, I created the following $HOME/.Xmodmap file to enable the F13..F24 bindings:

```
! XF86Mail
keycode 163 = F25 F25 F25

keycode 191 = F13 F13 F13
keycode 192 = F14 F14 F14
keycode 193 = F15 F15 F15
keycode 194 = F16 F16 F16
keycode 195 = F17 F17 F17
keycode 196 = F18 F18 F18
keycode 197 = F19 F19 F19
keycode 198 = F20 F20 F20
keycode 199 = F21 F21 F21
keycode 200 = F22 F22 F22
keycode 201 = F23 F23 F23
keycode 202 = F24 F24 F24
```

You may need to logout/login to get the updated keymapping table to take effect, or run ```xmodmap $HOME/.Xmodmap``` to load the keymappings into the current table.

Hope this helps, the keys have been working fine for me once I enabled them in Linux.

Pm

**Comment by AlexWayfer** [comment]
@pmichaud thank you, it definitely works! So, I'm going to close this issue because it's a problem out of OBS, as I understand.
