### ISSUE TITLE
Counter-Strike: Global Offensive will not capture after new update

### ISSUE THREAD

**Issue by KillaBoi** [obsproject/obs-studio#3139]
## Platform

Operating system and version: Windows 10 x64 Version 1909 OS Build 18363.900
OBS Studio version: 25.0.8

## Expected Behavior

CSGO should be captured as normal
## Current Behavior

CS:GO does not get captured on Game Capture mode and just shows a black screen.

## Steps to Reproduce

1. Download latest version of CS:GO with the new Trusted Mode feature.
2. Try to game capture on CS:GO process
3. See just a black screen for CS:GO

## Additional information

N/A, loads of streamers are facing this issue right now.

**Comment by Fenrirthviti** [comment]
Nothing we can currently fix.

Reference: https://blog.counter-strike.net/index.php/2020/07/30736/

Valve needs to allow this, we will not be implementing workarounds for their anticheat protections.

**Comment by KillaBoi** [comment]
Understood.

**Comment by ricardovsilva** [comment]
@Fenrirthviti how OBS interacts with CS:GO? I'm facing the same issue. The first point was that game was stuttering a lot so I disabled `Use anti-cheat compatibility hook` and also reenabled `Capture cursor`, then the stuttered ended.
But still having black screen.

Do you know details about what of the game specifically OBS gets? I was used to believe that it only gets the video output.

**Comment by ricardovsilva** [comment]
Also, are OBS dlls signed?

**Comment by ricardovsilva** [comment]
The bypass by now is to run CS:GO in Fullscreen Window mode and capture the window. The downside is that all your steam overlay is going to be shown in the stream.

**Comment by meydominic** [comment]
With default settings I have stuttering ingame as well. Not playable.
Setting OBS to record whole desktop works fine, but you'll see everything.

(Only wanted to share my sight).

As ricardovsilva already asked, are all binaries in OBS signed?

**Comment by WizardCM** [comment]
> As ricardovsilva already asked, are all binaries in OBS signed?

Most (if not all) `dll` and `exe` files in OBS are signed, including the main EXE, the inject helper, and the game capture hooks (both 32bit and 64bit).

**Comment by ricardovsilva** [comment]
@WizardCM can you point the docs or at least give to us a direction about how OBS interacts with CS:GO itself? So I can dig into the code to try to figure out what is not being recognized by CSGO.

**Comment by Fenrirthviti** [comment]
I appreciate the eagerness to get this fixed, but it's extremely unlikely that it is anything you can fix, we are already aware of the issue and looking in to it.

**Comment by ricardovsilva** [comment]
@Fenrirthviti so can you reopen this issue? This give to the community the feedback that you guys are looking for it instead of:
> Valve needs to allow this, we will not be implementing workarounds for their anticheat protections.

Also can you give a light? I would love start to study OBS code and contribute in any way. I have really good ideas and would love to try to experiment then so it could become PRs in future.

**Comment by Fenrirthviti** [comment]
There is nothing for us to do, this is an issue on the Valve side of things. They are blocking our capture hook. They claim that hooks need to be signed, but OBS hooks have been signed since their inception. This issue affects every single app that does direct game capture, not just OBS. There is no workaround, and I do not want people discussing how to bypass this restriction on our repository.

Again, I appreciate your eagerness but this issue has no actionable items. We have already reached out to Valve regarding this issue, but as it is not a bug with OBS, this is not the appropriate place to track it. If you want to discuss further, I suggest joining the Discord server.

https://obsproject.com/discord

**Comment by Muhadkhan** [comment]
today I tried streaming csgo with streamlabs obs and it worked in trusted mode, my settings were 
screen display record in OBS
the game was in fullscreen windowed mode 
it worked
there may be a setting issue although it was a test stream 
and like I wasted more than 30 mins to figure this set out so try it out it might work for u as well, I have no idea does it varies from region to region or not.

**Comment by Fenrirthviti** [comment]
Yes, display/window capture will work fine. Game Capture is what is currently not working.

**Comment by DasX** [comment]
They probably are afraid of something like this:

https://github.com/ekknod/G37OBS

**Comment by Fenrirthviti** [comment]
I'm going to post the information we have, and then lock this thread from further comments as people keep posting hacks/cheats on this thread, which is something we absolutely do not condone. Here is our current response:

Valve has implemented a Trusted mode which does not allow OBS to hook CS:GO using Game Capture. Read more in their [announcement post](https://blog.counter-strike.net/index.php/2020/07/30736/). Additionally, [they have no plans on allowing OBS](https://support.steampowered.com/kb_article.php?ref=8835-KLXV-0292#whitelist) in Trusted mode.

You will need to run the game in either windowed or borderless fullscreen and use Window Capture instead. Alternately, you can launch the game with `-allow_third_party_software` .
