### ISSUE TITLE
Keyframe interval setting ignored when using NVENC

### ISSUE THREAD

**Issue by Shizmob** [obsproject/obs-studio#3143]
## Platform

Operating system and version: Windows 10
OBS Studio version: 25.0.8

## Expected Behavior

Even when selecting NVENC as the output h.264 encoder in advanced output settings, I expect the keyframe interval setting to be honoured when set to `2`: that is, a keyframe should be sent every two seconds. If the setting can't be honored due to NVENC limitations, then I'd expect it to be hidden or greyed out.

## Current Behavior

Keyframes are never sent unless deemed necessary by the encoder, similar to setting it to the default setting of `0`.

## Steps to Reproduce

1. Set output encoder to NVENC and keyframe interval to `2`;
2. Start streaming a fairly static image to an RTMP server (we used OSSRS);
3. Re-connect to the server and notice the image being a glitchy B/P-frame mess not resolved until significant movement happens or the NVENC encoder otherwise decides a new I-frame is necessary.

**Comment by flaeri** [comment]
This should be working fine, and I even did a quick test to confirm. Nvenc does insert keyframes when you specify. Feel free to drop by the discord with your log, and we can try to troubleshoot the issue with you.

**Comment by Fenrirthviti** [comment]
Appears to be a support issue, closing.
