### ISSUE TITLE
[ CS: GO ] [ LoadLibrary - Fix ] - The new update brokes the game capture

### ISSUE THREAD

**Issue by alexevladgabriel** [obsproject/obs-studio#3154]
## Platform

Operating system and version: Windows 10 Pro x64
OBS Studio version:  OBS 25.0.8

## Expected Behavior

When you try to record the game capture of CS:GO, you get a big black screen, because of the new update, who brokes, the hook
of game capture to game.

This help the CS:GO Cheaters, to play again on the new update.
https://pastebin.com/Bb3dima0

## Steps to Reproduce

1.
2.
3.
4.

**Comment by RytoEX** [comment]
This is not we can currently fix.

Reference: https://blog.counter-strike.net/index.php/2020/07/30736/

Valve needs to allow this, we will not be implementing workarounds for their anticheat protections.

See also #3139.
