### ISSUE TITLE
Noise appears in the webcam image while charging the laptop.

### ISSUE THREAD

**Issue by MitaKousuke** [obsproject/obs-studio#3157]
## Platform
Operating system and version:Windows 10(Home)
OBS Studio version: from25.0.1 to25.0.8　I have not check whether it will occur in other versions.

## Expected Behavior & Current Behavior
There is noise in the webcam image.
It does not occur when the laptop is not charging.
This noise remains in both recording and distribution.
The same is true for other webcams.
No noise is generated in the video using an application that uses a smartphone as a web camera regardless of whether it is wired or wireless. (Droidcam/iVcam)
No noise occurs with other distribution software.(N air)
Noise will occur if you shoot with another shooting software while OBS is running.
Noise will not occur if the resolution is 640*480 or less.

## Steps to Reproduce
It happens anyway,
It has not been confirmed whether it occurs on other PCs.
Confirmation video
https://twitter.com/MitaKousuke/status/1282047989502980097

## Additional information
I have a DELL Inspiron 3580. I once replaced the HDD with an SSD.

**Comment by cpyarger** [comment]
My first thoughts are either 

1. noisy power brick
2 bad /damaged shielding on the webcam cable

basically, it looks like a hardware issue.

**Comment by MitaKousuke** [comment]
As I wrote,
・Does not occur with other software
・It occurs in any webcam

**Comment by WizardCM** [comment]
A current log file is required. Please post a link to your current log file after reproducing the issue.

- In OBS select Help > Log Files > Upload Current Log File.
- Copy the URL and paste it here.

**Comment by MitaKousuke** [comment]
https://obsproject.com/logs/td-UwIwQXsnyNQzQ

**Comment by mufunyo** [comment]
> As I wrote,
> ・Does not occur with other software
> ・It occurs in any webcam

This might be related to the format OBS is requesting and/or the (accelerated or not) conversion routines used to decode the format. Ultimately, anything that changes based on whether the AC cord is plugged in or not indicates a hardware failure; it's just curious that OBS triggers this hardware failure while it appears other software does not.

I'd recommend testing different resolutions, fps and pixel formats, and see if that makes any difference.

**Comment by gxalpha** [comment]
There has not been any more information on this issue for two years, any no. one has been able to reproduce it.
Closing as stale.
