### ISSUE TITLE
Linux: failed to detect real screen size when HiDPI scale is ON.

### ISSUE THREAD

**Issue by RinCat** [obsproject/obs-studio#3161]
## Platform

Operating system and version: Linux 5.6.19-gentoo-x86_64
OBS Studio version: OBS 25.0.8 (linux)

## Expected Behavior
OBS should able to detect real screen size no matter what HiDPI scale value is.

## Current Behavior
OBS shows only screen size after scale.

## Steps to Reproduce
1. Open KDE System  Settings, go to Display Configuration
2. Change global scale to 150%
3. Logout and login again to make the new setting effective
4. Open OBS and check Base Canvas Resolution

![screenshot](https://i.imgur.com/Ngo3JTe.png)

## Additional information
OBS can detect 4K resolution if scale set to 100%

**Comment by Fenrirthviti** [comment]
That field is a combo box, you can just enter any value you want in it. The default values populated are what is reported by your display manager. Not a bug.
