### ISSUE TITLE
Scripts dialog Add button freezes on OBS 25.0.3+dfsg1-2 (linux)

### ISSUE THREAD

**Issue by metal450** [obsproject/obs-studio#3162]
## Platform
Operating system and version: Kubuntu 20.04, KDE Plasma 5.18.5, Qt 5.12.8, Kernel 5.4.42
OBS Studio version: 25.0.8 (64-bit) (installed via ppa:obsproject/obs-studio)

## Expected Behavior
Be able to add scripts via the script dialog

## Current Behavior
Clicking the "Add" button in the Scripts dialog causes the UI to lockup & need to be force terminated.

## Steps to Reproduce
1. Tools->Scripts.
2. In the Script dialog, click "+."
3. The background of the button lightens, as if it's being pressed, but nothing else happens.
4. Attempting to close the Scripts dialog now produces "Application obs is not responding," & has to be terminated.

## Additional information
Here's a screencast showing the behavior: https://lnk2.tk/snaps/2020-07-13_18.04.10.mp4

**Comment by kkartaltepe** [comment]
Update to the most recent version.

**Comment by metal450** [comment]
I am on the most recent version.  apt shows no updates, and OBS website shows "Latest Release 25.0.8," which is exactly what I stated above.  Screenshot: https://lnk2.tk/snaps/2020-07-13_19.10.02.png

**Comment by kkartaltepe** [comment]
The github is not for support, please go through our discord or forums if you want more support with your issue. If it ends up not being an environmental issue we can reopen this bug.

**Comment by metal450** [comment]
This isn't a support request, it's a bug report.  How could it be any simpler?  I provided explicit & very clear steps, and a video, showing two actions that caused it to crash. Select from a menu, click a button, and it crashes.  What could be more of a bug than that?

**Comment by kkartaltepe** [comment]
Because it does not replicate, So your replication steps are insufficient.
