### ISSUE TITLE
Monitor Audio is heard in scenes that don't feature that audio source

### ISSUE THREAD

**Issue by Craig88** [obsproject/obs-studio#3165]
## Platform
Operating system and version: macOS Catalina 10.15.5 (released by Apple approx 1 June 2020)
OBS Studio version: 25.0.8 (mac)

## Expected Behavior
When using monitoring audio on a source, changing to another scene (that doesn't include the source) means that the audio can no longer be heard.

## Current Behavior
When switching to a difference scene the monitored audio continues playing, across all scenes.

## Steps to Reproduce
1. Create a scene and add an audio source
2. Use Advanced Audio Properties and set it to be Monitor and Output
3. Listen to the audio using your monitoring device
4. Create a new empty scene, switch to that scene and the audio continues.

## Additional information
I tried the same steps in Streamlabs OBS and the issue was the same. 
This makes me think it might be a macOS issue.
I tried uninstall and reinstalling OBS.

**Comment by Fenrirthviti** [comment]
This sounds more like a support issue, can you stop by the Discord and check with the #macos-support channel first? If we can confirm it there, we can reopen this as a bug report. It seems to be working fine for me on my end, so there might just be a misunderstanding.

**Comment by Craig88** [comment]
Hey @Fenrirthviti  - here are some recent posts from the OBS Forums by other users experiencing the same issue:

https://obsproject.com/forum/threads/how-to-stop-monitoring-audio-of-an-inactive-audio-device.122000/
https://obsproject.com/forum/threads/monitor-audio-is-spilling-over-different-scenes.122239/

I've made a post in the Discord too, so will add any further info here.
