### ISSUE TITLE
[libobs] Dead-lock sometimes appear while group/ungroup selected items 

### ISSUE THREAD

**Issue by walker-WSH** [obsproject/obs-studio#3166]
## Platform

Operating system and version: WIN10
OBS Studio version: 25.0.8 (also tested with latest code)

## Expected Behavior

UI should not block while group/ungroup selected items

## Current Behavior

sometimes, UI block forever

## Steps to Reproduce

1. add two scenes : scene-1, scene-2;
2. switch to scene-2, add a scene source depond on existed scene-1;
3. continue adding many sources in scene-2;
4. select all sources in scene-2 > click right mouse to show menu > click "group selected items";
5. select all sources in scene-2 > click right mouse to show menu > click "ungroup selected items";
6. loop operation for (4) and (5), sometimes UI block forever.

## Additional information
**Reason:**
1. In obs_graphics_thread, while rendering video, firstly get gs lock in render_displays, then require scene lock;
2. In obs_sceneitem_group_ungroup, firstly get scene lock, then require gs lock to create obs_scene_item::item_render in obs_scene_add_internal;
3. While running between (1) and (2), sometimes the two thread are nested to waiting lock.
To make sure this UI block appear everytime, we can add Sleep(500) in render_displays after getting gs lock.

**How to fix ?**
1. After reviewing gs_texrender_create, I find that gs lock is unnecessary for this function. Yes ?
2. If the gs lock must be gotten, maybe we can remove creating item_render for obs_sceneitem_group_ungroup. Because this canvas will be created in obs_graphics_thread (created in function named update_item_transform).

**Comment by jp9000** [comment]
Correctly fixed in https://github.com/obsproject/obs-studio/commit/b2839c3ec30e60930180b8ee85a4b95d8a254cda
