### ISSUE TITLE
Window title used for window capture is not correct on multi-window UWP apps

### ISSUE THREAD

**Issue by hinterlandcreative** [obsproject/obs-studio#3171]
When trying to use window capture on multi-window UWP apps the wrong title is shown in the Window dropdown.

## Platform
Operating system and version: Windows 10 19041.329
OBS Studio version: 25.0.8

## Expected Behavior
The actual window title is shown in the window drop down under properties for Window Capture.

## Current Behavior
It appears that the window title shown on the "Properties for 'Window Capture'" is simply showing the package name?

## Steps to Reproduce

1. Download the forked windows sample for projection here: https://github.com/hinterlandsupplyco/Windows-universal-samples/tree/master/Samples/Projection/cs
2. Run the app on a PC with two monitors.
3. Start Projecting.
4. Notice that the windows both have distinct titles:
![BothWindows](https://user-images.githubusercontent.com/26602171/87696907-7c553180-c75f-11ea-9117-818795f99a88.PNG)
5. Using a Win32 window inspector tool, like the one included in AutoIt GUI scripting tools, see that the Window title of the second view is actually available: 
![Win32WindowInfo](https://user-images.githubusercontent.com/26602171/87697080-a9094900-c75f-11ea-9d53-1cc8b0582139.PNG)
6. Open OBS and add a "Window Capture" Source.
7. Notice that the Window titles do not match the actual titles of the windows.
![WrongTitleFound](https://user-images.githubusercontent.com/26602171/87697106-aeff2a00-c75f-11ea-8aaa-f5875f9e5374.PNG)

## Additional information
N/A

**Comment by WizardCM** [comment]
Confirmed using https://docs.microsoft.com/en-us/samples/microsoft/windows-universal-samples/projection/

**Comment by Fenrirthviti** [comment]
Closing as stale. If this is still an issue please open a new issue with updated reproduction steps on the latest version of OBS.
