### ISSUE TITLE
Display caputure can't filter specified window（Mac OSX）

### ISSUE THREAD

**Issue by 435129214** [obsproject/obs-studio#3178]
## Platform

Operating system and version: osx 10.15.5
OBS Studio version:25.0.8

## Expected Behavior

I'm doing MAC development with OBS source code. Now I have a problem. I don't know whether OBS can be supported or what modifications can be made. If I want to share a desktop now, but I don't want to share the window content of my own app. I don't know how to remove the specified window when sharing the desktop.Is there any way to filter the specified window, the same as filtering the mouse？ Please specify any method. Thank you.
## Steps to Reproduce

1.
2.
3.
4.

**Comment by Fenrirthviti** [comment]
Github issues is not for support, please use the forums or Discord instead.

https://obsproject.com/help
