### ISSUE TITLE
Files with uppercase extensions are not shown in Open file dialog.

### ISSUE THREAD

**Issue by MarioMey** [obsproject/obs-studio#3190]
## Platform
Operating system and version: Debian 10 Buster, Mate Desktop 1.20.4
OBS Studio version: 25.0.7 (compiled here)

## Expected Behavior
Files as *.MP4 or *. MOV should be shown in Open file dialog

## Current Behavior
They are not shown.

## Steps to Reproduce
1. Rename some file.mp4 to file.MP4
2. Try to add it as a source.

**Comment by univrsal** [comment]
Works fine here with the qt file dialog.

**Comment by MarioMey** [comment]
> Works fine here with the qt file dialog.

Can I change my file dialog to QT?

**Comment by univrsal** [comment]
I don't know, I don't use mate.

**Comment by kkartaltepe** [comment]
Working as intended, if your file picker is case sensitive then you wont be able to find files with cased extensions.
