### ISSUE TITLE
Compile error（macOS）

### ISSUE THREAD

**Issue by 435129214** [obsproject/obs-studio#3191]
QT_HOME=/Users/XXXXX/Qt5.14.2/5.14.2/clang_64
export PATH=$QT_HOME/bin:$PATH
export QTDIR=/Users/XXXXX/Qt5.14.2

cmake -D CMAKE_OSX_DEPLOYMENT_TARGET=10.12 -D MAC_OS_X_VERSION_MIN_REQUIRED=10.12 ../obs-studio-25.0.8 && make -j 4

## Platform

Operating system and version:macosx 10.15.5
OBS Studio version:25.0.8

## Current Behavior

Undefined symbols for architecture x86_64:
  "__Py_Dealloc", referenced from:
      _py_to_libobs_ in obs-scripting-python.c.o
      _libobs_to_py_ in obs-scripting-python.c.o
      _add_functions_to_py_module in obs-scripting-python.c.o
      _add_to_python_path in obs-scripting-python.c.o
      _load_python_script in obs-scripting-python.c.o
      _obs_python_script_update in obs-scripting-python.c.o
      _obs_python_script_unload in obs-scripting-python.c.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [deps/obs-scripting/libobs-scripting.dylib] Error 1
make[1]: *** [deps/obs-scripting/CMakeFiles/obs-scripting.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

## Steps to Reproduce

1.
2.
3.
4.

**Comment by PatTheMav** [comment]
The issue template is there for a reason, just dumping console output in a GitHub issue is not only rude but also shows a lack of respect for the people working on this project.
