### ISSUE TITLE
Video loop Media Sources get unloaded for the rest of the session if unused for some minutes

### ISSUE THREAD

**Issue by YorVeX** [obsproject/obs-studio#3192]
## Platform

Operating system and version: Windows 10 64 Bit, Build 1909
OBS Studio version: 25.0.8

## Expected Behavior
Inactive Media Sources with video loops should be able to get activated at any time, regardless of how long they've been unused before and whether they've ever been used before during the current OBS session.

## Current Behavior
Media Sources with video loops that haven't been used yet in this session will not show at all anymore if a certain time (I think roughly 15 minutes?) has passed. After this time has passed if the Media Source is activated it will not show anything. The only way to fix this is to use "Browse" and load the same video file again.

## Steps to Reproduce
1. Start OBS with a disabled Media Source that loads a video file with the following settings activated: "Loop", "Restart playback when source becomes active", "Close file when inactive".
2. Wait at least 15 minutes (if reproducing fails, try again with longer times, e.g. 30 minutes) while not enabling the Media Source.
3. Enable the Media Source.
4. Bug: the Media Source will not show.
5. Workaround: opening the Media Source and browsing for the same video file will make it work again

As a counter example:
1. Start OBS with a disabled Media Source that loads a video file with the following settings activated: "Loop", "Restart playback when source becomes active", "Close file when inactive".
2. Enable the Media Source during the first minutes -> it is shown correctly
3. Disable the Media Source again
2. Wait at least 15 minutes or longer while not enabling the Media Source.
3. Enable the Media Source.
4. Now the Media Source is shown correctly

## Additional information
As shown by the reproduction steps what makes the difference is whether the Media Source was enabled during the first ~15 minutes at least once. If it was, then it will work correctly for the rest of the session. If it wasn't, then it will stop working after roughly ~15 minutes.
This is a big issue for me, since I use around 14 background video loops that stay disabled until they are needed. I never know when they are, some might be needed after 30 minutes into the session, others after 4 hours, others never. Currently to work around this I always enable and disable each of them after OBS start, this makes sure they will keep working during the session, but it's pretty tedious and I often forget about it, leaving me with a black background at a later point.

This doesn't happen with OBS 24.0.3 - I haven't tested all of the hotfix versions but it happened to me with 25.0.4 and 25.0.8 so I believe it was introduced with the 25 major release.

**Comment by maxdrash** [comment]
Not reproduced on Ubuntu 20.04 with a very slow disk.

**Comment by YorVeX** [comment]
OK, so maybe this is a Windows specific issue.

**Comment by RytoEX** [comment]
Can you confirm if this is still an issue on OBS Studio 28.0.3 or newer? I could not reproduce this with a 15 minute interval.

**Comment by PatTheMav** [comment]
Wasn't able to reproduce this on macOS with a 15 minute interval either.

**Comment by YorVeX** [comment]
Can confirm that this is fixed, cannot reproduce anymore with OBS 28.0.3.
