### ISSUE TITLE
v4l2 properties window gets buggy

### ISSUE THREAD

**Issue by gersonjferreira** [obsproject/obs-studio#3193]
## Platform
Manjaro Linux, OBS installed from the main repository.

Operating system and version: Manjaro Linux, kernel 5.6.16-1-MANJARO, gnome on x11
OBS Studio version: 25.0.8-1

## Expected Behavior
Dropdown and text input elements on the properties window of v4l2 sources should render properly.

## Current Behavior
Once I select the video source, all elements (dropdown menus, text areas, etc) get glitchy, the window becomes impossible to read. Closing the window and opening it again restores it to proper rendering, but it gets buggy again if I change any webcam property. 

## Steps to Reproduce
1. Start a clean OBS project and add a V4L2 source.
2. Open its properties window and its elements are already buggy.
3. If not rendered incorrectly yet, try changing the webcam properties and the window elements will get a bad render.
4. Close the window and open the properties again. It will be fine until you change something.

## Additional information
A screenshot:
![image](https://user-images.githubusercontent.com/5455489/87881786-e8d76700-c9d1-11ea-94e2-1c1ad22d5623.png)

**Comment by kkartaltepe** [comment]
Please provide a log from obs and the output of `v4l2-ctl --all /dev/videoX` where X is the number associated with this webcam. Does this occur for all video input devices or only for this one webcam?

I cannot replicate this.

**Comment by gersonjferreira** [comment]
I have two webcams, the internal one from the notebook and an external USB Logitech. Both show the same problem. It seems to be something with my computer, since OBS works fine in my wife's notebook also running Manjaro, but with KDE. I'm searching on Google, but I don't see anybody complaining about this.

I'm attaching the log of both webcams here.

[cam0.txt](https://github.com/obsproject/obs-studio/files/4944484/cam0.txt)
[cam1.txt](https://github.com/obsproject/obs-studio/files/4944485/cam1.txt)

**Comment by kkartaltepe** [comment]
If you also cannot replicate it then im going to close this. Feel free to update once you can find a way to replicate on the 2nd machine and if you still believe its an obs issue, and we can re open.

**Comment by gersonjferreira** [comment]
I understand the difficulty to reproduce. It seems that it only happens to me, but also only happens to OBS and V4L2 in my computer. Luckyly I don't have to open this window too often, but it bothers me.

It would be nice to keep the issue here to see if it happens to somebody else so we can try to identify how to reproduce in the future.

**Comment by gersonjferreira** [comment]
@kkartaltepe, just to let you know and register here. I've fixed the issue. It was the Kvantum theme manager. It was messing with OBS Studio and since yesterday's update also with Spyder IDE. I don't know how Kvantum was breaking the interface, but uninstalling it solved everything.
