### ISSUE TITLE
"Read from file" FreeType2 Text source should start reading if unavailable file becomes available without restarting OBS

### ISSUE THREAD

**Issue by JPLeBreton** [obsproject/obs-studio#3196]
## Platform

Operating system and version: Linux (Manjaro latest 64-bit, OBS package from official repositories)
OBS Studio version: 25.0.8-1

## Steps to Reproduce
1. Create a FreeType 2 Text source in a layout.
2. Open the source properties and select "Read from file".
3. Select a text file that exists on the local system.
4. Observe: the text source appears in the preview as expected.
6. Delete the file and relaunch OBS.
7. Observe: the text source doesn't appear, as expected, because the file isn't there.
8. Without closing OBS, create the file in its original path and name in a text editor.
9. Observe: Text doesn't appear in preview until you restart OBS.

## Expected Behavior
Expected behavior: OBS checks for the file at a reasonable rate, eg once every 1-5 seconds, and starts reading from the file if it exists.

## Current Behavior
See repro steps above - text doesn't appear in preview if file starts to exist / becomes available.
I notice that the GDI+ text source in Windows builds of OBS does *not* exhibit this behavior, and FreeType2 Text inputs are listed as obsolete. If they're obsolete on Linux as well it would be good to have feature parity here.

## Additional information
I have an automated setup that displays info on the current level I'm playing, and sometimes the file it writes to will briefly cease to exist. It would be nice not to have to work around this.

**Comment by skeletonbow** [comment]
Hammering the disk with polling isn't a way to go, it's wasteful.  Using OS filesystem notifications would be the way to do this.  Seems unlikely for a deprecated feature though.

**Comment by JPLeBreton** [comment]
> Hammering the disk with polling isn't a way to go, it's wasteful.

Checking to see if a file exists once every 1 to 5 seconds is not "hammering the disk", and it's especially nothing for an application that does as much I/O as OBS.

> Using OS filesystem notifications would be the way to do this. Seems unlikely for a deprecated feature though.

What is the non-deprecated solution for getting text in a layout in OBS Linux, then?

**Comment by Fenrirthviti** [comment]
Freetype2 is not deprecated on Linux, but I would recommend checking out the Pango plugin as a workaround for now.

**Comment by Fenrirthviti** [comment]
Closing as stale. If this is still an issue please open a new issue with updated reproduction steps on the latest version of OBS.
