### ISSUE TITLE
lost connection to resource (file or device) fails without error

### ISSUE THREAD

**Issue by therentabrain** [obsproject/obs-studio#3199]
## Platform

Operating system and version:
Windows 7 64
OBS Studio version:
25.0.8
## Expected Behavior

When loading a scene collection and its resources, if any are missing, there should be an error message or warning to the user, possibly with the opportunity to fix.  Missing/broken links should be visibly different.  This behavior is the same for missing files and missing or reordered USB devices such as audio / cameras.
## Current Behavior

If an audio source is not found, such as an Audio Capture, the resource in OBS stops functioning but appears unchanged.   

This may occur after rebooting, after changing which audio output device is the Windows default, after upgrading drivers, or after unplugging and replugging a USB cable.  Looking in OBS, it appears normal, but no sound comes through; you have to reselect the identical option from the list and it (usually) comes back to life.

The same problem happens with the chosen audio Monitoring Device (in Settings, Audio).  No sound comes from OBS, though the setting appears perfect and unchanged.

Related but different, this happens with files too.  If I create a media source which is located on a file server (perfect gigabit wired network) and restart the system, such that the drive has not been reconnected, OBS does not notice or complain, it simply leaves the resource looking perfectly fine and passively fails to play anything.

Or, if a file has been renamed while OBS was closed. 

In all the above cases, I have had shows _ruined_ while I had to stop everything and figure out why something was not working.  

OBS should notify the user if a critical piece of a show is not found.  The option to never warn me again about this resource would be nice, too, for resources that are often not present.
## Steps to Reproduce

1. On a system with multiple audio devices (such as a ui24r or Scarlett 6i6, etc), set up a show with media files and overlays and a specific audio device source for background music.  Configure the monitor output to go through your non-default audio device.  
2. Run through every step.  Confirm that everything is great and ready for tomorrow's show. 
3. Unplug your USBs and shut down the computer.
4. Restart the computer and plug USBs back in, preferably changing up which ports are which but this is not required.  
5. And/or, change which device you prefer for default playback in Windows (also not required but it may help reveal the problems).  
6. Rename one of your media files.  Also, don't visit all network drive letters, such that not all your connections are awake.
7.  Start OBS.  Quickly click around and notice that everything looks perfect and you have seen no errors or warnings.
8.  Run your show and notice how you can no longer hear anything, your videos are a black screen, etc.  
9.  Resolve never to play with the Internet again.

## Additional information

My dream version:
A "Relink" dialog pops up and says which resource and what is not available.
("Source 'Rode Mic' is not found"  "Media source 'Opening Credits' file not found")
In the dialog, you can choose a new one / browse to relink / replace.  
If you choose Ignore Link State, then it shuts up like always, but the others will still bug you if they disappear.
You can also choose to Stop Relinking.
Sources and scenes affected remain italicised, or bold, or tinted "unavailable" grey, except the ones you set to Ignore Link State.
Also, when you look at a setting and it has lost its connection (e.g. Monitoring Device), instead of dumbly showing the old value (which is dead) it should be greyed out.

**Comment by notr1ch** [comment]
You may want to take a look at or test https://github.com/obsproject/obs-studio/pull/2233

**Comment by therentabrain** [comment]
That looks great, solving 50% of my issue.  I don't compile my own stuff and my time is very tight with producing shows... I looked at the Windows link, and tried to see if I could download a compiled version, and it is no longer available.  I would love to see this implemented.

(It doesn't address the missing audio/video devices, but a very similar or combined dialog could be great.  As a user experience, knowing what pieces of my show are missing before go time is critical.)

Thank you :)

**Comment by notr1ch** [comment]
Not sure what happened to the build artifacts, I guess they are deleted after a while. After the merge conflicts are fixed there will likely be a new build available for testing, if you subscribe to that PR you should get a notification when that happens.

**Comment by therentabrain** [comment]
Cool, did that :)  The disappearing devices (which are not actually gone, just changed slightly) is more of a regular problem for me, so I hope this gets some attention somehow.  Wish I knew more and could program it.

**Comment by Vandebeque** [comment]
Excuse me interupting, are you the same therentabrain who modified the Vista Tascam us224 driver for W7 on this site https://homerecording.com/bbs/user-forums-by-brand/tascam-user-forum/any-chance-using-tascam-us-224-windows-7-64-bit-340117/
?

**Comment by therentabrain** [comment]
who wants to know?  what popcorn machine stuffed with fish filets?  I've never been to philadelphia and I've never seen that icecream cone before in my life!  but if i DID know where to find that person, and if you have a large cash reward for them or something, what would you want me to tell them

**Comment by Vandebeque** [comment]
I was hoping for a way to contact therentabrain that didn't involve abusing this thread (sorry guys!) so that the obsproject had to delete my comments :-)

**Comment by therentabrain** [comment]
This wouldn't be an issue if github allowed private messaging!  you can reach me at any address at therentabrain dotcom.
