### ISSUE TITLE
LIBOBS - Stop fires End signal

### ISSUE THREAD

**Issue by PeterAkakpo** [obsproject/obs-studio#3200]
## Platform

Operating system and version: Windows 10, 1903
OBS Studio version: 25.0.8

## Expected Behavior

Calling **obs_source_media_stop()** on **ffmpeg_source**  should not trigger the **media_end** signal, but just the **media_stop** signal.
## Current Behavior

Both **media_stop** and **media_end** signals are triggered when **obs_source_media_stop()** is called
## Steps to Reproduce

1. create an ffmpeg_source
2. add signal handlers for both media_stop and media_end to the source
3.  update the source with local_file setting 
4. call obs_source_media_stop()
5. monitor the signal handlers

**Comment by kkartaltepe** [comment]
Can you describe what you are trying to do that it doesnt make sense for the media end to trigger when media stop stops and ends the playback?

**Comment by PeterAkakpo** [comment]
am developing a video player with logging. now videos are to be logged into a text file only when they are played to the end. sending a media_end signal when the video is stopped by the user will not achieve this purpose without further having a workaround it. stopping and ending signals are two distinct events and one should be triggered by the other. this is how almost all video sdks work. Stopped event is never an EndOfStream event.

**Comment by WizardCM** [comment]
That'd be here, I think

https://github.com/obsproject/obs-studio/blob/5662ec699198532915364d483a3fbb1fee80ca87/plugins/obs-ffmpeg/obs-ffmpeg-source.c#L290-L291

This was added for media controls in https://github.com/obsproject/obs-studio/pull/2394

**Comment by gxalpha** [comment]
This is intentional. If a media source gets stopped, it also ends.
