### ISSUE TITLE
UI: Tray icon always enabled after the recording started

### ISSUE THREAD

**Issue by SuslikV** [obsproject/obs-studio#3205]
## Platform
All platforms where tray is supported.
OBS Studio version: at least 25.0.7-430-gf9801c9 (64bit), 23-07-2020 was tested.

## Expected Behavior
The tray menu icon shouldn't appear if it is disabled in _Settings>General>System Tray>Enable_ (unchecked)

## Current Behavior
When user starts recording the tray icon always appear no matter if it was disabled in OBS Studio Settings.

## Steps to Reproduce
1. Make unchecked the _Settings>General>System Tray>Enable_ (click OK button to save changes)
2. Restart OBS Studio (just to make sure that all is work as intended).
3. Start recording by Hotkey or by UI button.
4. See that tray icon will appear right after the recording started.

## Additional information
This is long time issue and known to exist in v21.1.2 and some other versions of OBS Studio.
https://github.com/obsproject/obs-studio/blob/f9801c933e4885468476381e7f4471ec655dd4b2/UI/window-basic-main.cpp#L5395
https://github.com/obsproject/obs-studio/blob/f9801c933e4885468476381e7f4471ec655dd4b2/UI/window-basic-main.cpp#L5413
https://github.com/obsproject/obs-studio/blob/f9801c933e4885468476381e7f4471ec655dd4b2/UI/window-basic-main.cpp#L7889
https://github.com/obsproject/obs-studio/blob/f9801c933e4885468476381e7f4471ec655dd4b2/UI/window-basic-main.cpp#L7918
etc...

Doesn't checks if tray icon is visible, like in:
https://github.com/obsproject/obs-studio/blob/f9801c933e4885468476381e7f4471ec655dd4b2/UI/window-basic-main.cpp#L4087

**Comment by WizardCM** [comment]
Fixed in #3339.
