### ISSUE TITLE
Unexpected Crash during Live Stream

### ISSUE THREAD

**Issue by HeyITGuyFixIt** [obsproject/obs-studio#3213]
## Platform

Operating system and version: Linux Mint 19.3 Tricia with Cinnamon 4.4.8
OBS Studio version: 25.0.8

## Expected Behavior

OBS shouldn't have randomly crashed like it did today.
## Current Behavior

OBS Studio randomly crashed in the middle of streaming. The laptop was idle and streaming, it all of a sudden crashed. OBS Studio's logs do not reveal any information about the crash.

OBS Studio's log:
[2020-07-26 08-19-24.txt](https://github.com/obsproject/obs-studio/files/4977835/2020-07-26.08-19-24.txt)

Crash log from journalctl:
[obs-crash-2020-07-26.log](https://github.com/obsproject/obs-studio/files/4977828/obs-crash-2020-07-26.log)

Hopefully this was only a one time issue. I was able to open OBS Studio again and continue the live stream.

## Steps to Reproduce
I don't know how to reproduce it, as the computer was idle while streaming and randomly crashed.

## Additional Information
System information:
[System information.txt](https://github.com/obsproject/obs-studio/files/4977838/System.information.txt)

**Comment by notr1ch** [comment]
Linux Mint is not an officially supported platform so we're not able to offer support for it. Consider contacting the package maintainer.

**Comment by HeyITGuyFixIt** [comment]
It is based on Ubuntu Bionic
