### ISSUE TITLE
Linux version does not remember window sources

### ISSUE THREAD

**Issue by KelvinShadewing** [obsproject/obs-studio#3217]
On Windows, if I add a window capture source, it will always remember what application I set it to, even if it isn't currently running. On Linux, if that application stops running, it will default to focusing on the XFCE panel when I open its properties, and I have to actually start that program it was originally watching to reassign it. I can't seem to find anything about this in settings, so I figured maybe it's a bug.

**Comment by RytoEX** [comment]
Please fill out the issue template completely.  Do not just delete it.

**Comment by notr1ch** [comment]
Closed due to lack of template.
