### ISSUE TITLE
GUI corruption after editing setting for V4L2 device

### ISSUE THREAD

**Issue by UsernameInvalidException** [obsproject/obs-studio#3224]
## Platform

Operating system and version: Manjaro 20.0.3, kernel `5.6.19-2-MANJARO`
OBS Studio version: `25.0.8-1`

## Expected Behavior
GUI should behave normally

## Current Behavior
GUI becomes corrupted after editing V4L2 device setting:

![Screenshot_2020-07-28_11-36-50](https://user-images.githubusercontent.com/28464769/88688069-fe7e1800-d0c6-11ea-995a-1ffe85a93d63.png)

## Steps to Reproduce
1. Add a V4L2 source
2. Open the source settings
3. Change an option
4. GUI is now corrupted

## Additional information
[obs_gui_corruption.txt](https://github.com/obsproject/obs-studio/files/4989425/obs_gui_corruption.txt)

**Comment by kkartaltepe** [comment]
Please see if you have any odd theming like #3193 which might break Qt.
