### ISSUE TITLE
OBS crashed at launch on Aarch64

### ISSUE THREAD

**Issue by theofficialgman** [obsproject/obs-studio#3225]
## Platform
Operating system and version: L4T Ubuntu 18.04
OBS Studio version: 25.0.7
Hardware: Nintendo Switch (Tegra X1)

## Expected Behavior
OBS starts up and runs.

## Current Behavior
OBS crashes stating that its can't initailize libgl.
If I run this before starting then it works perfectly: export LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libGL.so

**Comment by Fenrirthviti** [comment]
A log file would be helpful here showing the crash, with a backtrace. That said, Switch and ARM aren't really officially support platforms right now, so there's likely not going to be a whole lot we can do.

**Comment by theofficialgman** [comment]
I've attached a log when the obs is started with export LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libGL.so as well as the crash log and the backtrace associated with it.

[normal_log.txt](https://github.com/obsproject/obs-studio/files/4991680/normal_log.txt)
[crash_log.txt](https://github.com/obsproject/obs-studio/files/4991681/crash_log.txt)
[backtrace.txt](https://github.com/obsproject/obs-studio/files/4991668/backtrace.txt)

**Comment by kkartaltepe** [comment]
We are happy to accept patches regarding arm, but no one is actively supporting arm. Thus it is unsupported.

**Comment by kkartaltepe** [comment]
The crash you provide is inside your systems glx implementation, (and given the lack of stack information) this likely means that your system is in a bad state.

**Comment by theofficialgman** [comment]
@kkartaltepe thanks for that information. Though I think my system is working as well as nvidia's l4t ubuntu will let me. Some other nvidia tegra x1 users have also noted this https://gist.github.com/danieloneill/9952820ad3ae0fe36738b4106ae6a775
https://obsproject.com/forum/threads/build-for-arm64-aarch64.85875/

**Comment by kkartaltepe** [comment]
That just makes it sound even more like its an issue on your system, or my specifically nvidias custom proprietary ubuntu flavor or wherever you found a platform with this chip. If you want to figure out whats wrong and submit a PR that seems like a good thing to do.

afaik most/all of the huge diff you link has already been PR'ed and merged. Maybe try compiling master yourself and see if your issue was actually already fixed before you even posted this.

**Comment by theofficialgman** [comment]
@kkartaltepe I have been compiling master this entire time. I just linked the diff because at the bottom there were a few people chatting about the the same issue I am having (obvious using different code but same problem) and I just though it has to do with the obs code base originally. I will look into seeing if it is truly an nvidia code base problem.

Thanks for all the help!

**Comment by Fenrirthviti** [comment]
These platforms are still entirely unsupported, and do not (last I checked) meet our minimum OpenGL requirements in the first place from a hardware support standpoint, so I would prefer that this stay closed.

That said, our linux-support channel on discord usually likes a good challenge and might be able to offer some pointers.

**Comment by theofficialgman** [comment]
> These platforms are still entirely unsupported, and do not (last I checked) meet our minimum OpenGL requirements in the first place from a hardware support standpoint, so I would prefer that this stay closed.
> 
> That said, our linux-support channel on discord usually likes a good challenge and might be able to offer some pointers.

all nvidia jetsons have full opengl 4.6, opengles 3.2, ELG support. they meet the minimums

running is not issue, the preload is fine for doing that. I am building now using the latest master to see if the now forced EGL implementation has issues or not

**Comment by theofficialgman** [comment]
@Fenrirthviti the EGL method which is now used on X11 (without specifying the variable) works without issue. no need to preload

closing as this will be fixed in the next release.

**Comment by Fenrirthviti** [comment]
Understood, and my mistake I didn't see the mention of jetson as well, just the Pi4, which definitely doesn't meet our minimum requirements.
