### ISSUE TITLE
Certain VST Plug-Ins Cause Crash on Versions Later Than 24.0.3.

### ISSUE THREAD

**Issue by Kukeiha** [obsproject/obs-studio#3226]
## Platform
Operating system and version: Windows 10 (1909)
OBS Studio version: 25+

## Expected Behavior
As with versions before 25, the VST plug-ins should load and work correctly. I've been using them for years, but ever since builds made in 2020, they crash the client.

## Current Behavior
When upgrading, the client simply won't open. When launching from a clean install and then adding the VST plug-ins, the client crashes.

## Steps to Reproduce
1. Have certain plug-ins loaded in audio filter chain in OBS Studio version 24.0.3 or earlier.
2. Update to any Windows version later than 24.0.3.
3. Sit and wait as if the client will open.
4. Weep at the incomplete log generated.

From a clean install:
1. Launch OBS Studio.
2. Open filter screen for desired audio device.
3. Select and add desired VST plug-in(s).
4. CRASH!

## Additional information
I've tried the 32-bit and 64-bit versions of said plug-ins. The plug-ins are developed by Solid State Logic and Softube (both, very well-known in the pro-audio industry, but not as popular as Waves plug-ins). Been using these plug-ins since 2016 or so, and they have not been updated since, so nothing has changed with them. Speaking to someone on the Discord, it was said that "We updated Qt with v25." For what it's worth, these specific VST plug-ins all continue to work in my other DAWs (audio applications).
[2020-05-18 01-09-13.txt](https://github.com/obsproject/obs-studio/files/4994179/2020-05-18.01-09-13.txt)

**Comment by Fenrirthviti** [comment]
Can you be more specific about which plugins are causing the issue? Please provide the crash log as well.

**Comment by Kukeiha** [comment]
I was unable to get a crash log when trying to add the Softube TUBE-TECH legacy plug-ins, but I was able to get one when trying to add an SSL Stereo Bus Compressor (The Duende version, not the latest "SSL Native" version).
[Crash 2020-07-31 21-30-15.txt](https://github.com/obsproject/obs-studio/files/5009736/Crash.2020-07-31.21-30-15.txt)

**Comment by RytoEX** [comment]
Could you please confirm if this is still an issue in OBS Studio 28.0.3 or newer?

**Comment by PatTheMav** [comment]
If it still persists, we'd also need a free VST to test this with, because we need to be able to reproduce/debug this crash in a development environment. Otherwise we'd need to ask you to debug the crash in a development environment on your machine if the issue only happens with VSTs available to you and open a PR to fix the issue.

**Comment by Kukeiha** [comment]
Hello,

The plug-ins I used to use had been updated within the past couple of years
and they ended up working fine in the later 27.* builds (as well as the
current 28+ builds) . I no longer use the older versions (which likely
still wouldn't work), but I haven't had any issues with the current
versions or any of the newer VST plug-ins I've added in the past year. And
I no longer have access to the old plug-in versions to try them in version
28+.
