### ISSUE TITLE
Please make a release

### ISSUE THREAD

**Issue by yurivict** [obsproject/obs-studio#3230]
Many pull requests have been merged since the last release, for example https://github.com/obsproject/obs-studio/pull/2712 https://github.com/obsproject/obs-studio/pull/2657

Users ask to backport these PRs to the FreeBSD port, but this would be difficult especially when your ```master``` branch is tagged ```25.0.7``` which is behind the latest release ```25.0.8```.

**Comment by Fenrirthviti** [comment]
I understand your desire for a release, but posting on here and ignoring the project guidelines and rules is not a great way to get your voice heard. We are working towards a beta release soon, and will update as soon as we have it. Our Discord is the best place to follow active work.
