### ISSUE TITLE
Screencast on Fedora 32 shows strange diagonal lines and random patterns

### ISSUE THREAD

**Issue by elmehalawi** [obsproject/obs-studio#3231]
## Platform

Operating system and version: Fedora 32
OBS Studio version: 25.0.8

## Expected Behavior

Screencast should work

## Current Behavior

Screencast source shows diagonal lines like this:

![Screenshot from 2020-07-31 04-19-21](https://user-images.githubusercontent.com/2058016/89020942-5b571980-d2e5-11ea-82d9-9453ef4c560c.png)

## Steps to Reproduce

1. Install OBS on Fedora 32 (using the software app)
2. Run OBS
3. Click '+' under "Sources"
4. Click "Desktop Screencast (Wayland / X11)"

![Screenshot from 2020-07-31 04-23-33](https://user-images.githubusercontent.com/2058016/89021184-b5f07580-d2e5-11ea-8c4d-b707f0c22c99.png)

5. Click "OK"
6. Any selection here will work. The result is the same whether you choose "Entire Screen" or "Single Window".
7. Click "Share"
8. Click "OK"

**Comment by kkartaltepe** [comment]
Please file a bug against the plugin, we do not support this plugin or running obs under flatpak currently.
