### ISSUE TITLE
Motion filter on Webcam removes the Transform > Horizontal Flip 

### ISSUE THREAD

**Issue by egallant90** [obsproject/obs-studio#3234]
I currently have my webcam setup and I use the option Transform > Horizontal flip. I also use the Motion filter on my webcam to make it smaller and move to a new spot on the screen. However when I use the hotkey to move the camera and shrink it the Horizontal flip gets removed. But when I use the Hotkey to switch back to the bigger version of the webcam the horizontal flip comes back. 

I have tried adding Horizontal flip at both positions of the Motion filter but the Horizontal flip gets removed the next time I move to the smaller position of the Motion filter every time.

**Comment by dodgepong** [comment]
Please don't delete the issue template. The template is there for a good reason, because people often omit important data from their issues, and this is no exception.

However, this initially strikes me as an issue with the motion filter plugin, which is a third party plugin. I recommend raising the issue with the plugin author.

**Comment by egallant90** [comment]
sorry did not know there was a template. as when i selected "new issue" the details part was just blank ? I do see it now when I click new issue. Now that i know there should be a template ill obviously follow it with any further submissions. Thank you.

**Comment by exeldro** [comment]
You can use the move source filter from the move transition plug-in instead to make it work

**Comment by skeletonbow** [comment]
Horizontal/Vertical flip appear to be implemented by just flipping the sign on the particular axis if you look carefully at what happens when they're used.  So it's probably a matter of just inverting the sign on the given axis when setting things up.
