### ISSUE TITLE
plugin update callback not called with most recent settings when callback is slow

### ISSUE THREAD

**Issue by e00E** [obsproject/obs-studio#3236]
## Platform

Operating system and version: Windows + Linux
OBS Studio version: master

## Current Behavior 

Observe the log output (and the visual preview). See that the log message prints the width with values like `1` `12` `123` but never `1234` (in my 10 tests). See that the input  field contains `1234`.

## Expected Behavior

The update callback should be called with `1234`. It might also be called with partial input but definitely with the final one.

## Steps to Reproduce

I am using the color source to illustrate my point. Modify the `update` callback to be slow by adding a one second sleep and logging the user settings.

```diff
diff --git a/plugins/image-source/color-source.c b/plugins/image-source/color-source.c
index b2e08747..c9a087c1 100644
--- a/plugins/image-source/color-source.c
+++ b/plugins/image-source/color-source.c
@@ -1,4 +1,5 @@
 #include <obs-module.h>
+#include <threads.h>
 
 struct color_source {
 	uint32_t color;
@@ -25,6 +26,8 @@ static void color_source_update(void *data, obs_data_t *settings)
 	context->color = color;
 	context->width = width;
 	context->height = height;
+    blog(LOG_WARNING, "update %u %u", context->width, context->height);
+    thrd_sleep(&(struct timespec){.tv_sec=1}, NULL);
 }
 
 static void *color_source_create(obs_data_t *settings, obs_source_t *source)
```

1. Start obs with this modified version (I compile everything from scratch).
2. Create an image source.
3. Go into its properties.
4. Go into the `Width` input field, select the whole text and delete so that the box is empty. 
5. With one quick rolling motion on your keyboard enter `1234`.

## Additional information

This means that the source did not update to the correct most recent settings despite the user interface showing this as the current value.
This is related to the callback being slow. Without the sleep I could not reproduce this. I originally noticed this when debugging a real third party plugin whose update is naturally slow (not as bad as 1 second slow, but haven't measured the real time).

**Comment by Fenrirthviti** [comment]
Please properly fill out the issue template.

**Comment by e00E** [comment]
Edited to issue template exactly.
