### ISSUE TITLE
elapsed_time in custom shaders eventually crawls to a halt

### ISSUE THREAD

**Issue by nobuyukinyuu** [obsproject/obs-studio#3240]
## Platform

Operating system and version:  Windows 10 x64
OBS Studio version:  24.0.8 (64-bit)

## Expected Behavior

Shaders using `elapsed_time` should continue to work as expected over long periods of time

## Current Behavior

Once OBS is open for a number of days, `elapsed_time` will no longer update in a timely manner.  This could be because the value is being accumulated from a delta:  As `elapsed_time`'s value grows greater, the number of digits available to express the fractional component drops below the actual fractional component delta between update ticks.  The functional effect is that over time, `elapsed_time` will no longer to continue to update in a timely manner, before eventually stopping to iterate at all.

## Steps to Reproduce

1.  create a shader which uses elapsed_time in a visually consistent manner.  A simple rotation shader is defined below these steps.
2.  leave this shader running in OBS for a few days.
3.  come back and observe the shader's behavior.

## Additional information
Code for an example shader which will rotate an image:
```hlsl
uniform float angle;
uniform float delta;
uniform float resx;
uniform float resy;

float4 mainImage(VertData v_in) : TARGET
{
	static const float PI = 3.14159265f;
	float2 coord = v_in.uv;
	float theta =elapsed_time*delta * angle ;
	float sin_factor = sin(theta * PI / 180);
	float cos_factor = cos(theta * PI / 180);
	
	float2x2 rotMatrix = {cos_factor, sin_factor, -sin_factor, cos_factor};
	
	//coord = float2((coord.x - 0.5) * (resx / resy), coord.y - 0.5) * rotMatrix;
	coord = mul(float2((coord.x - 0.5) * (resx / resy), coord.y - 0.5) , rotMatrix);
	
	coord += 0.5;
	return image.Sample(textureSampler, coord);
}
```
One possible workaround to this issue is to modulo `elapsed_time` against a reasonably large number which still has full precision for the given variables;  this will make the value inaccurate over a shorter period of time, however the current behavior as `elapsed_time` approached max value seems to have either already been undefined, or didn't account for an appreciable loss in precision at the point the value was supposed to be reset.

A good number to modulo against may be (2<sup>17</sup>)-1 = **262143**;  at 32-bits, this provides a precision of `0.015625`;  after this value (which is about 3 days), the change in `elapsed_time` begins to slow down due to precision dropping to `0.03125`.

**Comment by kkartaltepe** [comment]
Obs does not offer a built in `elapsed_time` parameter to shaders. It seems you have confused us with a plugin you might be using.

**Comment by skeletonbow** [comment]
`elapsed_time` is a parameter provided by the OBS Shaderfilter plugin, not OBS.  Use `frac(elapsed time * speed)` or similar to manipulate the plugin provided timing parameter into what is needed for the given algorithm.

**Comment by nobuyukinyuu** [comment]
Much appreciated.  Moving the issue to [here](https://github.com/Oncorporation/obs-shaderfilter/).
