### ISSUE TITLE
Logitech PTZ Pro 2, Pan/Tilt not working (Windows) 

### ISSUE THREAD

**Issue by jorrit-jdjict** [obsproject/obs-studio#3250]
Operation system: Windows 10
OBS Studio version: 25.0.8

### Expected Behavior
Drag the pan and tilt sliders to pan and tilt according to how you drag them.

### Current Behavior
Tilt & Pan does not work at all
some times in the opposite direction.
Log: https://obsproject.com/logs/fQL7LCXm_bDki33g

### Steps to Reproduce
Add the Logitech PTZ Pro 2 as a source and double click it to open the settings
Try to drag pan & Tilt switches.

Would love to hear from you

**Comment by dodgepong** [comment]
Which pan/tilt sliders are you referring to? OBS does not have any built-in controls for PTZ cameras. Can you take a screenshot of what you're referring to?

**Comment by tt2468** [comment]
@dodgepong I think that they are referencing the `Configure Video` button that opens the third party camera control menu, in which case it really has nothing to do with OBS

**Comment by dodgepong** [comment]
I suspect that but I want to hear it from them.

**Comment by jorrit-jdjict** [comment]
![image](https://user-images.githubusercontent.com/41777298/89338754-56a3b400-d69d-11ea-9fc6-36c6859b65b1.png)

**Comment by jorrit-jdjict** [comment]
Where does this menu come from then?

**Comment by Fenrirthviti** [comment]
That menu is the driver configuration menu, which is provided by the device driver itself, you'll need to reach out to Logitech for assistance on why it's not working. First step I would suggest would be to make sure you have the latest version of the drivers/software for the device installed.
