### ISSUE TITLE
X11 Window Capture returns a frozen frame for full-screen applications when the X server uses page flipping in XPresent

### ISSUE THREAD

**Issue by YaLTeR** [obsproject/obs-studio#3255]
## Platform

Operating system and version: Fedora 32
OBS Studio version: [Flathub Beta](https://flathub.org/apps/details/com.obsproject.Studio) which is at OBS 25.0.8

## Expected Behavior

OBS continues capturing as normal.

## Current Behavior

OBS captures a frozen frame (last before going full-screen?)

## Steps to Reproduce

1. Launch `glxgears` under GNOME Wayland 3.36
2. Set up Window Capture in OBS for glxgears
3. Press GNOME's "Toggle fullscreen mode" shortcut

Alternatively, test using SDL2 `test/testdraw2 --fullscreen` or `test/testdraw2 --fullscreen-desktop`.

## Additional information

We've discussed this in `#gnome-shell` with @jadahl, @ofourdan and Michel Dänzer. The culprit seems to be that Xwayland uses flipping when running with XPresent under GNOME Wayland, and when flipping is done, the pixmap that OBS gets from `XCompositeNameWindowPixmap` is invalidated every frame, rather than just on certain X11 events. As per Michel Dänzer's [comment on the Mutter issue tracker](https://gitlab.gnome.org/GNOME/mutter/-/issues/1369#note_884542):
> Looking at OBS code, this looks like an OBS issue. It only gets a new window pixmap via `XCompositeNameWindowPixmap` in response to `ConfigureNotify`/`MapNotify`/`Expose`/`VisibilityNotify`/`DestroyNotify` events. But while Xwayland is using page flipping for clients using the Present extension, the window pixmap changes for each frame, so OBS would need to call `XCompositeNameWindowPixmap` for each frame. (I don't know of another mechanism which allows to do this only when needed in this case)
> 
> (I suspect Xwayland just doesn't hit the page flip path with sway for some reason)

The suggested fix is to try re-obtaining the pixmap every frame and seeing if this causes a performance impact, potentially enabling it [only on Xwayland](https://gitlab.freedesktop.org/xorg/app/xisxwayland). There's on-going discussion in `#gnome-shell` on whether it's feasible for Xwayland to post an event every time it invalidates the pixmap instead.

**Comment by kkartaltepe** [comment]
We do not support flathub, please open your issues against the flathub maintainers.

**Comment by YaLTeR** [comment]
???

This is not a Flathub issue. I can reproduce it on obs-studio-25.0.8-1.fc32.src.rpm from Fedora 32 packages. Please re-open.

**Comment by kkartaltepe** [comment]
Please provide replication steps for X11 (Not XWayland), capture on XWayland (Or any other X implementation) has never been supported. If it works great, if not then its not then oh well.

Given Michel's comments, it sounds like its an unfortunate case of X protocols and it would be better for gnome to avoid ones that are broken like this (Assuming this does indeed replicate on traditional X11 setup).

**Comment by jadahl** [comment]
> Given Michel's comments, it sounds like its an unfortunate case of X protocols and it would be better for gnome to avoid ones that are broken like this (Assuming this does indeed replicate on traditional X11 setup).

This is an X11 extensions used by X11 clients, implemented by the X server, so not related to GNOME, and not anything GNOME can directly choose to avoid. The reason it might work together with other Wayland compositors right now is more likely due to something preventing the Present extension implementation in Xwayland to work as it was intended to.

With that said, if your intention is to only treat Xorg as the single supported X11 implementation, then I guess this will stay broken on others, but that is of course up to you to decide.

**Comment by kkartaltepe** [comment]
> With that said, if your intention is to only treat Xorg as the single supported X11 implementation, then I guess this will stay broken on others, but that is of course up to you to decide.

Indeed we would prefer that if you run in a wayland environment you use a wayland solution. We are always looking for feedback on our PRs. Perhaps you would be interested in providing it on #2484

**Comment by jadahl** [comment]
I agree, time is indeed better spent on things like #2484 and https://gitlab.gnome.org/feaneron/obs-xdg-portal. Tweaking any X11 solution to work better together with Xwayland would only be an incomplete stop gap solution.

**Comment by ofourdan** [comment]
> Indeed we would prefer that if you run in a wayland environment you use a wayland solution. […]

If so, you may want to disable/hide the Xcomposite source when running on Xwayland, maybe?

**Comment by YaLTeR** [comment]
> > Indeed we would prefer that if you run in a wayland environment you use a wayland solution. […]
> 
> If so, you may want to disable/hide the Xcomposite source when running on Xwayland, maybe?

I don't think it's a good idea at all until obs-xdg-portal works. Apart from this full-screen case OBS window capture works perfectly fine under Xwayland.

**Comment by ofourdan** [comment]
I can understand your point from a user perspective, but that's clearly an unsupported solution from OBS so people shouldn't use it on Wayland.

**Comment by YaLTeR** [comment]
Michel Dänzer has suggested on the IRC that instead of using the Composite extension for capturing, OBS could use a separate pixmap allocated by OBS itself, and copy from the window to that pixmap for each frame. They said it would be more robust, and while it might be slightly less efficient in some cases, it should be more efficient overall with Xorg full-screen apps as well.

**Comment by Agno94** [comment]
I'm also experiencing this issue.

> Tweaking any X11 solution to work better together with Xwayland would only be an incomplete stop gap solution.

I don't think so. Many applications don't work as wayland client and fall back to Xwayland. We can expect some (eg. Wine/proton applications, non-gtk/qt applications) to still work as X client for years. On the other hand there are rumors they might drop support for Xorg in the near future. This might accelerate the shifted towards wayland enviroment. Thus a working X window source for Xwayland will be valuable, IMHO.
