### ISSUE TITLE
Git tag for 25.0.8 is not on master

### ISSUE THREAD

**Issue by jonhoo** [obsproject/obs-studio#3256]
This isn't an OBS bug as much as a repository bug, so the normal issue template doesn't really apply.

The `25.0.8` git tag seems to somehow have been made on a commit that isn't on `master`. If you run `git describe --always --tags`, you get `25.0.7-479-gbfdf5dc94`, not `25.0.8-...` as you'd expect. You can also see this by scrolling back in `git log --oneline master` and see that `25.0.8` never appears there.

**Comment by Gol-D-Ace** [comment]
This is also not a repository "bug".
25.0.8 got cherry picked together.

**Comment by jonhoo** [comment]
Ah, I see, interesting...
I wonder if that might cause issues in the build step, such as here: https://github.com/obsproject/obs-studio/blob/a705030b2398598488c653238ba6f13be37a3be8/cmake/Modules/ObsCpack.cmake#L20
I know the Arch Linux git package also uses `git describe` to extract the current version number.
I suppose that then means that anything that wants to know the "current" version from a git build should instead parse `libobs/obs-config.h`?

**Comment by Gol-D-Ace** [comment]
#!/bin/bash
latesttag=$(git describe --tags)
echo checking out ${latesttag}
git checkout ${latesttag}

Would probably work.

**Comment by PatTheMav** [comment]
IIRC for nightlies the commit hash is always part of the version, so it's "different" enough. A proper release tag build should pick up the tag name that triggered a build and thus should have the correct version.

**Comment by jp9000** [comment]
I mean if we start a merge phase where we're merging big untested features and then later on we unexpectedly need to make a critical hotfix to the previous version, the only choice we have is to tag separately from master with cherry-picks.  It is simply not possible to guarantee every tag on the master branch.

**Comment by jonhoo** [comment]
In that case I suggest that the code in the OBS cmake file I linked above should possibly be changed to take that possibility into account? Just trying to mitigate potential future bugs :)
