### ISSUE TITLE
Browser Source doesn't account for Cropping/Padding filter when interacting with it

### ISSUE THREAD

**Issue by abrman** [obsproject/obs-studio#3257]
## Platform
Operating system and version: Windows 10 Pro, version 1909
OBS Studio version: 25.0.8

## Expected Behavior
Clicking on a button inside of Browser Source Interaction window triggers it as intended.

## Current Behavior
In order to click on the intended button I have to click right and below it by the same distance I've cropped from the left and top on filter.

## Steps to Reproduce
1. Create a Browser Source of any website (ideally with buttons that have hover animations)
2. Add a Crop/Pad filter to the created Browser Source
3. Interact with Browser Source ("Interact" from the right click interaction menu)

Video: https://youtu.be/QrrOGinOlSE

**Comment by skeletonbow** [comment]
I reported this before too either here in github or on Discord (18 months or so ago estimate) and at the time it was suggested that I should window capture a web browser instead as browser source's Interact wasn't intended for what I was doing.  The specific thing I was doing is only possible as Browser Source however so I had no other option.

I ended up having to work around this problem by toggling my crop filters off every time I wanted to use Interact.  Don't know of any other option other than that or editing the source code and rebuilding at the moment, at least for the specific use case I have.

I think it might fall into the category of niche use case that few people will ever encounter so probably a low priority issue I fear.  I might take a stab at it sometime myself once I'm more familiar with the OBS sources if nobody beats me to it, but that's likely a ways off as I ramp up...  'tis on my own bugfix wishlist too though.

**Comment by WizardCM** [comment]
I worry that this'd require specialised code to calculate the crop/offset by looping through filters manually.

**Comment by davidaspden** [comment]
Can we not have an option to see the interactive preview sans filters?

**Comment by PatTheMav** [comment]
> Can we not have an option to see the interactive preview sans filters?

Alas that's a non-trivial ask, because the interact window is nothing but a new projector limited to a single source, with added code to handle mouse and keyboard events.

Projectors use OBS' normal render functions to display the source output, which always take filters into account (the property preview uses the same function). We'd need to rework our render system or add a new render call just for preview and I'm not sure if that added complexity is worth it.

**Comment by Fenrirthviti** [comment]
Closing as stale. If this is still an issue please open a new issue with updated reproduction steps on the latest version of OBS.
