### ISSUE TITLE
Browser Source No longer works after suspected Nvidia Driver Update

### ISSUE THREAD

**Issue by b3ck** [obsproject/obs-studio#3265]
## Platform

Operating system and version: Windows 10 - Version 2004 - Build 19041.388
OBS Studio version: 25.0.8

## Expected Behavior
Browser Source to show either local or non-local web content, it doesn't even show the default OBS Page.

## Current Behavior
When adding a Youtube Video URL or ANY URL that has audio/video, audio plays but doesn't show content.

## Steps to Reproduce

1. Installed NVidia drivers
2. No longer works...

## Additional information

NVIDIA Driver Version: 451.67

**Comment by Fenrirthviti** [comment]
Please use the forums or Discord for support. The issues pages are reserved for verified and replicable bugs. Browser source is working just fine on that nvidia driver version, there is likely a miscofig somewhere, or you are on a laptop and OBS is running on the incorrect GPU after an update.

https://obsproject.com/help

**Comment by b3ck** [comment]
Thanks, for those who are interested in the outcome: 

[https://obsproject.com/forum/threads/browser-source-no-longer-works-after-suspected-nvidia-driver-update.128042/](https://obsproject.com/forum/threads/browser-source-no-longer-works-after-suspected-nvidia-driver-update.128042/)
