### ISSUE TITLE
OBS does not record transient windows like menus or contextual menus (with XComposite)

### ISSUE THREAD

**Issue by mclegrand** [obsproject/obs-studio#3267]
## Platform

Operating system and version: Ubuntu 20.04.1 LTS
OBS Studio version: (from apt) : OBS Studio - 25.0.3+dfsg1-2 (linux)

## Expected Behavior

I should be able to record an application like Inkscape, including what shows up when I open a menu or when I right click

## Current Behavior
GTK3 draws menus and contextual menus in their separate windows which are marked are transient for their top level window.
OBS does not capture those windows, so what I do with menus is invisible

## Steps to Reproduce

1. Launch Inkscape 1.0 (for instance, that should also work with any GTK3 application - I tried gparted, same issue )
2. Create a scene, add a Window capture (XComposite) for inkscape
3. try to open a menu, or right click, in the application
4. => menus open, but are invisible to OBS

## Additional information

```IRC
17:22 < Mc> Hi! A question about gtk3 : it seems that when recording with e.g. OBS, the menus are not part of the same "window" as the application, making them invisible to the recording application… is this intended or bypassable ?
17:33 <~ebassi_afk> Mc: Menus are not "part" of a window: they have their own window
17:33 <~ebassi_afk> Mc: It depends on the capturing software to include all the other windows that are marked as transient for a top level
17:35 < Mc> ah, so OBS could do it ? (ie : there is a mechanism to pre-allow access to those kind of windows ?)
17:42 <~ebassi_afk> Mc: I have no idea what OBS does or does not, sorry
17:42 <~ebassi_afk> Mc: I also assume you're talking about X11
17:42 < Mc> ah, yes
17:43 <@mclasen> no need to allow anything then, X doesn't have access control
17:44 <~ebassi_afk> Mc: In any case, whenever a menu window pops up, it's marked as "transient for" for the top level window; OBS would need to watch all the windows being created, and check if they belong to the application's window it is "recording"
17:44 <~ebassi_afk> If they do, OBS would need to also record and composite the menu window
17:44 <@mclasen> do we do that for or windows, actually ?
17:45 <~ebassi_afk> Or, and I guess this is more common, OBS would need to record the whole desktop, which would include every window
17:45 <~ebassi_afk> mclasen: AFAIR, gnome-screenshot used to have tree walking code in order to take a screenshot of decorations and open menus
17:45 <~ebassi_afk> Because of that
17:46 <@mclasen> we have a similar problem with screenshots in wayland
17:46 <@mclasen> where mutter doesn't collect popups
17:47 <~ebassi_afk> mclasen: I guess the screencasting interface would need to include all the surfaces (including xdg-popup and friends) tied to a window
17:48 < wb9688> But I agree that OBS should just record those menus as well
17:48 < wb9688> When you choose to record a window
17:49 <@mclasen> thats entirely between the recorder and the compositor, though. gtk is not involved

```

**Comment by kkartaltepe** [comment]
If your program uses multiple windows you are better off capturing your display instead. Window capture is intended to only capture a single window.

This limitation is the same across platforms surprisingly. You should prefer display capture if you need to capture multiple transient windows.

**Comment by RaitoBezarius** [comment]
@kkartaltepe Rather than closing abruptly the issue, wouldn't be better to mark it as "help needed as per your edit?

**Comment by kkartaltepe** [comment]
Its working as intended, so its not a bug. Feature requests should go into the https://ideas.obsproject.com

I dont see a reason to leave this open. It would possibly confuse people into thinking this was not working as intended or that someone was actively working on changing this functionality.

**Comment by Fenrirthviti** [comment]
To clarify the point further, given the conversation from IRC that you posted, it sounds like the folks involved want us to iterate across all available windows that a program draws, identify only those that are related to the main window being capture, spawn a new window capture invisibly in the background to capture the new window drawn, and then composite that on top of the existing window capture in the correct location. All in realtime, using custom methods that the capture APIs do not provide natively. I hope you can understand why that is a little unrealistic to ask of the capture program, and a large part on why things like full display capture exist.

I'm not saying this is impossible, but as mentioned everything is working as expected. This should be submitted as an idea, or as an RFC with a proposed design.
