### ISSUE TITLE
Control modifier on hotkeys no longer works when restarting obs-studio (or loading scene collection)

### ISSUE THREAD

**Issue by pmichaud** [obsproject/obs-studio#3270]
## Platform
Operating system and version:  Kubuntu 20.04
OBS Studio version: 25.0.8

## Expected Behavior
I have two scenes in my configuration; one has "F6" assigned as a hotkey, the other has "Control + F6" assigned as a hotkey.  Pressing F6 should always load the first scene, pressing Control + F6 should always load the second scene.

## Current Behavior
When first setting up the hotkeys, the scenes work as expected.  But upon exiting obs-studio and returning to obs-studio, the Control+F6 version of the hotkey no longer functions properly -- it acts as if the control isn't being pressed and loads the first scene.

## Steps to Reproduce
1.  Start obs-studio 25.0.8 .
2.  Create two scenes, or use two existing scenes.  Let's refer to them as "Scene1" and "Scene2" for this example.
3.  Go to File -> Settings -> Hotkeys
4.  For Scene1, set "Switch to scene" to be F6
5.  For Scene2, set "Switch to scene" to be Control + F6
6.  Press "Apply" and then "OK".  This closes the settings dialog and returns to the main window.
7.  Press F6.  Scene1 should be loaded.
8.  Press Control + F6.  Scene2 should be loaded.
9.  Deactivate the obs-studio window.
10. Press F6.  Scene1 should be loaded.
11. Press Control + F6.  Scene2 should be loaded.

-->  At this point, we know that the OS/windowing system is properly sending the hotkey to obs-studio, with the control information.  All appears to be "fine", but...

12.  Exit obs-studio.
13. (optional step) View the contents of .config/obs-studio/basic/scenes/*.json ; search for "F6" in the file.  It should appear in the "hotkeys" section for each of the two scenes; one of the scenes will also have an entry of ```"control": true```.  So we know the scene configuration has been saved properly.
14. Restart obs-studio.
15. Press F6.  As expected, Scene1 is loaded.
16. Switch to any other scene.  A third scene is helpful here, but you can also manually switch to Scene2 to illustrate the issue in the next scene.
17. Press Control + F6.  On my system, this is (incorrectly) loading Scene1, and not the Scene2 that is associated with the Control + F6 hotkey.
17a.  _Sometimes_ if I press/release the control key at exactly the same moment as pressing/releasing the F6 key, I can get Scene2 to load.  Or sometimes I can hit Control + F6 and briefly see Scene2 load but it's immediately replaced with Scene1, as if F6 alone was being pressed.

## Additional information
A1:  The same problem seems to occur with the "Shift" and "Alt" modifiers.  They work when first setup in obs-studio, but upon exiting/returning to obs-studio it treats "Shift+F6" or "Alt+F6" the same as if F6 was pressed alone.

A2: Workaround, of sorts (and possible clue to the bug):  Sometimes re-loading the scene collection inside of obs-studio seems to cause the hotkeys to start working again.  For example, on my system... I can create a duplicate of the current scene collection, then switch back to the original and the hotkeys start working properly again.  But this only happens some of the time -- sometimes I have to switch between the two duplicate scene collections before things start working again.

The behavior here could be related to issue #2982 , but it's sufficiently different that I figured opening a new issue was best and just reference that issue from this one in case they are related.

Thanks,

Pm

**Comment by pmichaud** [comment]
After some further investigation, the problem seems to be related to the order in which scenes are saved in the scenes/*.json file.

In the scene collection's .json file, if Scene1 (using an unmodified key for the hotkey) appears later in the .json file than Scene2 (with a modified version of the same key as its hotkey), then Scene1 gets loaded even if the hotkey with modifier is being pressed.  I suspect what is happening is that Scene2 is loaded briefly, then the hotkey processing also incorrectly treats Scene1 w/o the modifier as a match and so Scene1 gets incorrectly loaded and replaces the just-loaded Scene2.

If Scene1 (hotkey w/o modifier) appears earlier in the .json file than Scene2 (hotkey with modifier), then things kind of work correctly.  Scene1 gets improperly loaded for a brief moment, but Scene2 is properly loaded after it so all is well.  There's some evidence to support this -- just repeatedly hit the hotkey with modifier  (e.g. Control + F6 in the OP) and I see Scene 1 being briefly loaded and immediately replaced by Scene 2.

Of course, when a modifier isn't present then only Scene1 loads and so it always "works".

The .json file appears to be rewritten frequently (e.g., right before switching to a new Scene Collection, or when exiting obs-studio), and the sequence of scenes isn't fixed in the .json file.  That's why it tends to switch from "working" to "not working" to "working" again depending on what's saving/loading the file.  In fact, after playing a bit with switching scenes in the Scene Collection menu, it appears that when the .json file is (re)written the scenes are always saved in the reverse order from how they were when they were loaded.

The fix should probably be that a hotkey entry without modifiers shouldn't match a hotkey keystroke when modified.  In other words, a scene with a hotkey setting of "F6" shouldn't be activated at all when "Control + F6" isn't pressed.

In https://github.com/obsproject/obs-studio/blob/master/libobs/obs-hotkey.c#L1197 I see that the absence of any modifiers is automatically treated as a true match; similarly at https://github.com/obsproject/obs-studio/blob/master/libobs/obs-hotkey.c#L1246 .  That feels wrong to me -- a hotkey entry without modifiers could end up matching keypresses where modifiers are present -- but I can't quite follow the logic well enough to know why these are here and how they might be adjusted.

Anyway, that's what I have for now.  For now the only workaround seems to be to always use modifiers on hotkeys, or to recognize that having a hotkey with a modifier excludes being able to use the same keyboard character (unmodified) as a distinguishable hotkey.

Pm

**Comment by pmichaud** [comment]
As a follow-up, there's also an issue with multiple modifier keys.  I have one scene set to be "Control + F17", and another scene set to be "Control + Shift + F17".  The second scene never ends up as the active scene -- the first one always gets loaded (last) regardless of whether the Shift key is being pressed.

Pm

**Comment by OldBaldGeek** [comment]
This is basically [https://github.com/obsproject/obs-studio/issues/4408](url)

**Comment by RytoEX** [comment]
Please confirm that this is still an issue on OBS Studio 28.0.2 (or newer).

**Comment by ftc7172** [comment]
> This is basically [https://github.com/obsproject/obs-studio/issues/4408](url)

It might be more accurate to say that #4408 is basically the same as this one.  :)

**Comment by pmichaud** [comment]
> Please confirm that this is still an issue on OBS Studio 28.0.2 (or newer). Possibly fixed by either #5095 or #6512.

After doing a quick test with 28.0.2, it appears this issue is resolved.

(Given how long it was taking to resolve the issue I've implemented several workarounds with my setup to avoid using the hotkeys feature of OBS studio altogether.  But doing a quick test with 28.0.2 hotkeys they appear to now work as I would expect.)

Pm

**Comment by gxalpha** [comment]
Closing per the above comment. Thanks for confirming.
