### ISSUE TITLE
Unable to record on FreeBSD after 37f01b35, error Missing expected option: 'audio bitrate'

### ISSUE THREAD

**Issue by emaste** [obsproject/obs-studio#3274]
## Platform
Operating system and version: FreeBSD-CURRENT
OBS Studio version: c5b3125b75c0f198ed3862102200c465a9b9b89e

## Expected Behavior
Recording works

## Current Behavior
Get `Missing expected option: 'audio bitrate'` error from ffmpeg mux
```
info: ==== Recording Start ===============================================
info: [ffmpeg muxer: 'simple_file_output'] Writing file '/home/emaste/2020-08-12 12-49-42.mkv'...
Missing expected option: 'audio bitrate'
Couldn't initialize muxer
warning: [ffmpeg muxer: 'simple_file_output'] os_process_pipe_write for packet data failed
info: [ffmpeg muxer: 'simple_file_output'] Output of file '/home/emaste/2020-08-12 12-49-42.mkv' stopped
info: Output 'simple_file_output': stopping
info: Output 'simple_file_output': Total frames output: 1
```

## Steps to Reproduce
1. Build latest obs-studio from git
2. Click record

## Additional information
Bisected to identify 37f01b35f69e591c0653f2dad35ba2759f128330 as the responsible commit. Building c5b3125b75c0f198ed3862102200c465a9b9b89e with that reverted works. I'll investigate further/propose a patch later, especially if it is not reproducible on Linux.

**Comment by emaste** [comment]
For reference my ffmpeg is `ffmpeg-4.3,1                   Realtime audio/video encoder/converter and streaming server`

**Comment by kkartaltepe** [comment]
Please provide the actual encoder settings (Preferably the entire log, posting a snippet is almost always the wrong choice).

**Comment by jpark37** [comment]
The set of arguments has changed between obs and obs-ffmpeg-mux. Make sure both executables are up to date, and that you aren't accidentally running a stale version of either.

**Comment by emaste** [comment]
> you aren't accidentally running a stale version of either.

Indeed, I accidentally had an older obs-ffmpeg-mux. Thanks, and apologies for the noise.
