### ISSUE TITLE
Blackmagic Decklink Mini

### ISSUE THREAD

**Issue by niclasboy** [obsproject/obs-studio#3276]
Hello,

I have got a Blackmagic Decklink Mini, but I can't add it as a "Blackmagic Device". I can add it as an normal Video Capturing Device, but can not choose 1080p25. I am able to get a video output, when I choose 1080i50 or 720p50.

Could someone tell me why I can't add it as a "Blackmagic Device"? 

Niclas

**Comment by unknowndomain** [comment]
This is a support question, not a bug.

Try the forum or Discord: https://obsproject.com/help

**Comment by niclasboy** [comment]
Ok thank you I will close it...
