### ISSUE TITLE
decklink: Intensity Pro 4K captures black screen with mode set to "auto" on version 11.6 of the Blackmagic Desktop Video software

### ISSUE THREAD

**Issue by ToadKing** [obsproject/obs-studio#3277]
## Platform

Operating system and version: Windows 10/Arch Linux
OBS Studio version: 25.0.8

## Expected Behavior

The "Blackmagic Device" capture with mode set to "auto" will work with the Intensity Pro 4K on verison 11.6 of the Blackmagic Desktop Video software

## Current Behavior

The Blackmagic Device source is a black screen if using the "auto" mode. Setting the mode manually and pixel format from 8-bit YUV to 8-bit BGRA fixes the source. Audio still plays but gets delayed (delay visible in the logs). The Blackmagic Media Express software can capture video, and on Windows the "Blackmagic WDM Capture" dshow capture works. This bug goes away if I downgrade to version 11.5.1 of the Blackmagic Desktop Video software on both Windows and Linux.

## Steps to Reproduce

1. Have a Blackmagic Intensity Pro 4K.
2. Install version 11.6 of the Blackmagic Desktop Video software.
3. Add a "Blackmagic device" source to OBS and select the "Intensity Pro 4K" device. Set the "Mode" to "auto".

## Additional information

Logs: [2020-08-10 11-38-30.txt](https://github.com/obsproject/obs-studio/files/5066370/2020-08-10.11-38-30.txt)

**Comment by dgcampea** [comment]
The automatic _Mode_ detection seems to be broken (no idea if its OBS or Decklink side) but if you manually set the _Mode_ and _Pixel Format_ to `8-bit BGRA` you should get it to work.

**Comment by ToadKing** [comment]
Can confirm that setting the mode and pixel format manually gets things working again, updating the issue title.

**Comment by thebookfreak58** [comment]
I have a similar issue with the 3G recorder which has to use the 11.6 drivers.

Try this: https://youtu.be/pC1uX4Ik1cU
