### ISSUE TITLE
Bounding Boxes disappeared during YouTube Live broadcast and never returned even after reinstall.

### ISSUE THREAD

**Issue by AbundanceMind** [obsproject/obs-studio#3278]
## Platform

Operating system and version:
OBS Studio version:

## Steps to Reproduce

1.
2.
3.
4.

**Comment by AbundanceMind** [comment]
MacBook Air
OS 10.15.5 (19F101)
OBS 25.07 and 25.08

Expected Behavior
Move and adjust bounding boxes (red line with grab dots) inside the scene.  

Current Behavior
No Bounding box is visible for any source in the window.  Each source is at full screen.
   
Steps to Reproduce
Add to any scene and new source and it fill the full window with no box to adjust size.

Additional information
during a live broadcast to youtube, I was able to adjust boxes and flip scenes and turn on and off sources.  I added a new course during the broadcast and the Box was not available.   
I have rebooted, reinstalled 25.08 and tried to downgrade to 25.07.   No Boxes are available.
My system does not auto update the Mac OS

**Comment by Fenrirthviti** [comment]
This sounds like you accidentally locked your preview. Click the Edit menu and make sure Lock Preview is unchecked. In the future, please do not submit support requests to the bug tracker. The tracker is limited to reports that are verifiable and have replication steps.

Use Discord or the forums instead. https://obsproject.com/help
