### ISSUE TITLE
Elgato HD60 S+ macOS shows poor performance

### ISSUE THREAD

**Issue by mtippett** [obsproject/obs-studio#3280]
## Platform

Operating system and version: macOS Catalina 10.15.6 
OBS Studio version: 25.0.8 (verified as failing on old versions as well)

## Expected Behavior
When using HD60 S+ a 1080p30 video capture should should not tax the CPU, using the GPU for processing the image.

## Current Behavior
Currently there does not appear to be any use of the GPU when preparing the image for rendering.  The rendering pipeline seems to stall and wait for the completion of the processing of the image pulled from the HD60 (which appears as a UVC webcam).

## Steps to Reproduce
1. Create OBS Source, add HD60 as source
2. Note a large increase in frame rendering
3. Start streaming
4. Notice a much larger impact on frame rendering time

## Additional information
More information will be added here and https://www.livedebug.dev/obs-studio-3280/README.html

**Comment by Fenrirthviti** [comment]
Have you tested with other UVC capture devices to validate if this is something specific to the HD60 S+?

**Comment by mtippett** [comment]
I have a logitech streamcam, which I'll look at the details on the output
formats and the code paths that frames go through to confirm.  The code is
unfamiliar so it will take a few days of hacking around before I find
sufficient details.

**Comment by Fenrirthviti** [comment]
Thanks, just changes the context of the report significantly if this can be replicated with all UVC devices as opposed to a single device. If it's *only* the HD60 S+, we can probably forward this along to Elgato to take a look on their end if there is something up with that specific device.

**Comment by mtippett** [comment]
Understood.  I looked in the code (I've included a reference in the
livedebug.dev), where there is a comment saying that NV12 will fall back to
CPU, and to uncomment when OBS supports NV12 decode.  The commit was made
around 6 years ago, so I'm assuming it is a forgotten disabling of a
feature.  Let me confirm the behavior before I raise it a bit more.

Matthew

**Comment by Fenrirthviti** [comment]
Thanks! I don't see that information in the livedebug, but can you please put any details in this issue so we can all see it and be updated? Using an external website on top of the github issues seems... strange, and adds an unnecessary step for us when trying to assist in correcting the issue.

Also in the meantime, please provide the full log when the issues occurs so we can take a spotcheck and see if anything jumps out.

**Comment by mtippett** [comment]
It's there as I gather the thoughts and validate.  The livedebug is more of
an experiment on structured debugging and streaming.  So I'm gathering
information (both right and wrong) there, and will transfer it to the bug
once I get clearer confirmation on the root cause.  I hadn't pushed the
details, it's now up at
https://www.livedebug.dev/obs-studio-3280/README.html

**Comment by Fenrirthviti** [comment]
Sorry, allow me to be more blunt: Please do not use a third party issue reporting/tracking tool. Post the details here. If you want to use that for your own purposes until you have information to provide, that is fine, but I don't like critical bug report information for our project hosted on an external website we have no control over.

**Comment by mtippett** [comment]
I understand.  I have not fully reproduced it and so have only partial
information, not what I would accept in any bug system that I would
present.  Once I have more complete information I will be the information
in there.   The comments I've made as part of debugging only indicate that
it is a software fallback path, and has been that way for the past six
years.   I'll transcribe the critical parts, however I don't believe there
is sufficient actionable data yet.

**Comment by mtippett** [comment]
Dug deeper into the code.  Relevant paths are in [av-capture.mm#L313](https://github.com/obsproject/obs-studio/blob/5f9f7166f9aa6e77562b0917a21c60b1f37cf18a/plugins/mac-avcapture/av-capture.mm#L313 ) exists a comment
```
    //TODO: uncomment VIDEO_FORMAT_NV12 and VIDEO_FORMAT_ARGB once libobs
    //      gains matching GPU conversions or a CPU fallback is implemented
```
And confirmed that the camera outputs in NV12.  Debug code in [av-capture.mm#1046](https://github.com/obsproject/obs-studio/blob/5f9f7166f9aa6e77562b0917a21c60b1f37cf18a/plugins/mac-avcapture/av-capture.mm#L1046) provides a debug information that is needed to understand the formats offered by the camera.  When not using a preset, the following output is placed in the logs

```
00:58:52.032: Video Capture Device: Capturing 'Game Capture HD60 S+ #2' (0x15000000fd9006a):
00:58:52.032:   Resolution: 1920x1080
00:58:52.032:   FPS: 60.0103 (60010321/1000000)
00:58:52.032:   Frame interval: 0.0166638 s
00:58:52.032:   Input format: Auto (actual: NV12 - 420YpCbCr8BiPlanar (420v))
00:58:52.032:   Requested color space: Auto (-1)
00:58:52.032:   Requested video range: Auto (-1)
00:58:52.032:   Using format: <AVCaptureDeviceFormat: 0x60000384f6e0> 'vide'/'420v' enc dims = 1920x1080, pres dims = 1920x108
0 { 60.01 fps }
```

[Intel Power Gadget](https://software.intel.com/content/www/us/en/develop/articles/intel-power-gadget.html#attachment-heading) provides useful graphs of the perfomance of the system.  Also macOS Activity Monitor also provides a GPU performance image.

Note that I have not actually confirmed that there is actually software fallback, and will update this when I get that.

**Comment by ryanschmitty** [comment]
Hey, just wanted to chime in with my anecdotal evidence here. I see the same high usage when using the HD60 S+ on macOS (Big Sur). I don't see the same high usage when using the Razer Kiyo Pro. I think you're on to something here with the HD60 S+ being worse than other UVC devices.

Is this still an issue for you as well @mtippett ?

**Comment by RytoEX** [comment]
Reporter has confirmed that there is not sufficient actionable data here. If someone can confirm that this is still an issue on supported macOS systems with OBS Studio 28.0.3 (or newer), please feel free to open a new Issue. Please also include the following:
1. Have you tested with other UVC capture devices to validate if this is something specific to the HD60 S+?

Please also provide an OBS log file from an affected session.
