### ISSUE TITLE
[BUG] NVENC ffmpeg: B-Frames causing recording to hang

### ISSUE THREAD

**Issue by dark-swordsman** [obsproject/obs-studio#3282]
## Platform

**Operating system and version:** Windows 10 Pro 64-bit, version 2004, build 19041.423
**OBS Studio version:** 25.0.8

## Expected Behavior

Using Xaymar's StreamFX plugin (which uses OBS's ffmpeg version), using any B-Frame references should allow the recording to stop.

## Current Behavior

When using "B-Frames/2" for "B-Frame Referenence Mode", the recording will hang and stay on "Stopping Recording", while also preventing the obs-ffmpeg process from stopping.

The only way to stop the obs-ffmpeg process is to kill it in task manager.

## Steps to Reproduce

1. Install [Xaymar's StreamFX version 0.8.3](https://github.com/Xaymar/obs-StreamFX/releases/tag/0.8.3)
2. Set up the recording settings to be exactly as [in this screenshot](https://blog.xaymar.com/wp-content/uploads/2020/06/obs64_VLu69iGnof-774x1024.png) (mainly the "B-Frame Reference Mode" as "Only (# of B-Frames)/2"
3. Start a recording that lasts at least 10 seconds.
4. Stop recording.

## Additional information

Firstly, I want to mention [the same issue](https://github.com/Xaymar/obs-StreamFX/issues/260) over on StreamFX. This is the main reason I am making this issue. Xaymar said:

> Good news, it's actually fixed in the recent ffmpeg versions. Just need to wait for OBS to update their FFmpeg version.

The only other similar issue I found in this repo was #2824. So I guess this is really a request for OBS to update to the latest ffmpeg version (unless, is there some way to manually change it?).

I would prefer to be able to record these settings since I am doing a personal comparison, instead of setting up a dummy account just to stream to twitch and then download the video. However, if this can't be solved relatively soon I guess I could just try that.

Also, here is [an OBS log](https://obsproject.com/logs/SxtiZAJ5eobMWb-u), though, the only actual error I see is this, but I don't know if it's related:

```
14:52:33.629: error:   Failed setup for format d3d11: hwaccel initialisation returned error.
```

**Comment by Fenrirthviti** [comment]
You can compile and include your own FFmpeg version if you wish, simply replace the binaries in the OBS Studio program directory.

As we don't support that plugin directly, incompatibility is not a high priority for us. If the plugin exposes features that are bugged, that is their responsibility to address, not us.

We will likely update FFmpeg at some point in the future, however, but I can't give an ETA on it.

**Comment by Xaymar** [comment]
The feature is technically not entirely broken. It works for RTMP streaming, which ignores the timestamps provided and uses the timestamps embedded into the H.264 stream instead, only recording is broken. It has already been addressed multiple times, and only affects Windows.

> You can compile and include your own FFmpeg version if you wish, simply replace the binaries in the OBS Studio program directory.

That would be great if that actually worked. OBS Studio on Windows is right in the middle of Ubuntu 18.04 and Ubuntu 20.04 in terms of FFmpeg versions, so updating to the most recent version crashes OBS, and downgrading also crashes OBS. If it wasn't for that, I'd already have done it to fix the libvpx-vp9 threading problems.
