### ISSUE TITLE
[Crash] Crash on exit when dragging and dropping scenes

### ISSUE THREAD

**Issue by cg2121** [obsproject/obs-studio#3310]
## Platform
Operating system and version: Happens on all OSes
OBS Studio version: 25.0.8 (also happens on latest master)

## Expected Behavior
OBS shouldn't crash.

## Current Behavior
Sometimes will cause OBS to crash on exit.

## Steps to Reproduce
1. Start with fresh OBS
2. Keep Scene 1 empty
3. Create Scene 2
4. Add a source to Scene 2 (source has to not have audio with it)
5. Drag and drop the second scene to the top and then drag and drop it back at the bottom
6. Exit OBS
7. OBS crashes

## Crash Log
[crash.txt](https://github.com/obsproject/obs-studio/files/5113448/crash.txt)

**Comment by cg2121** [comment]
Extra info: If the scenes have no sources and you drag & drop a few times, you get memory leaks instead of crashing on exit.

**Comment by cg2121** [comment]
Also it seems to happen with any sources instead of ones without audio. You have to drag & drop then close OBS a couple times before it crashes though.

**Comment by Programatic** [comment]
Could just be semantics, but I've also found you don't even need a fresh install of obs. If you start with 2 scenes, one of which has a source, it will still crash on exit.

**Comment by Programatic** [comment]
I [believe this](https://github.com/Programatic/obs-studio/tree/crash_fix) fixes it. It gets rid of the mem leak and I also can no longer cause the crash.
