### ISSUE TITLE
[BUG] T-Bar inconsistent - obsSourceActiveChanged

### ISSUE THREAD

**Issue by Livastyle** [obsproject/obs-studio#3312]
## Platform

Operating system and version: Windows 10 Pro
OBS Studio version: 25.0.4

## Expected Behavior

Starting transition using T-Bar: (moving slider slightly right)
`obsSourceActiveChanged => true`
Cancel transition using T-Bar: (moving slider back to the left)
 `obsSourceActiveChanged => false`

## Current Behavior

Starting transition using T-Bar: (moving slider slightly right)
`obsSourceActiveChanged => true`
Cancel transition using T-Bar: (moving slider back to the left)
 `nothing happens`
When selecting another scene for preview, and then transition it:
 -  `obsSourceActiveChanged => false` finally emits
 - that scene actually gets selected for preview **instead** of the previous active scene
## Steps to Reproduce

explained above

**Comment by nettings** [comment]
I saw this under LInux, too, and it seems to be fixed for me.

**Comment by tt2468** [comment]
Closing this as there it appears to have been fixed.
