### ISSUE TITLE
[Workaround] enable LUA scripting support in recent openSUSE Tumbleweed

### ISSUE THREAD

**Issue by nettings** [obsproject/obs-studio#3323]
## Platform
Operating system and version: openSUSE Tumbleweed
OBS Studio version: aef10d46c4a7bd61940bb8511bed06e1bb2dd0ff

## Current Behavior
The dependency luajit-devel (or libluajit-devel) does not exist (any more?) on current oS Tw. Hence, Lua scripting support will be disabled.

## Workaround
Turns out that the JIT compiler for Lua is called moonjit, and its headers are in moonjit-devel, so make sure to install those.

It doesn't seem to be recognized automatically, so in place of `cmake <your options>`, use `ccmake <your options>` to change the configuration manually, press `t`for advanced mode. Now enable `COMPILE_LUA` and set `LUAJIT_INCLUDE_DIR` to `/usr/include/moonjit-2.2` (or whatever version is current when you do it).

## Expected Behaviour

It would be nice if the moonjit includes could be found automatically. However, I don't know enough about Lua and its packaging to know whether that's more of an openSUSE issue, an upstream issue, or something that can/should be fixed in obs.

**Comment by WizardCM** [comment]
A quick Google tells me that MoonJIT is a "Fork of LuaJIT to continue development." It's also apparently less careful merging changes, so I'm not sure if it's something we want to depend on.

**Comment by nettings** [comment]
@WizardCM: Thanks, I didn't think of checking the project... I understand your reluctance. In any case, oS Tw have no other option at this point. Maybe this ticket can help Tw users work around the issue for now. Is there a way to add this information to the distribution-specific build documentation?

**Comment by gxalpha** [comment]
We're not looking to add moonJIT support to OBS.
