### ISSUE TITLE
OBS recoding lagging and choppy output 

### ISSUE THREAD

**Issue by LEOkonami** [obsproject/obs-studio#3337]
## Platform
Windows 10 version 2004 build:19041.450
OBS 25.0.8

## Expected Behavior
Should capture a video without dropping frames

## Current Behavior
When using OBS to capture a few games the video will be lagging and choppy (Dropping frames)

## Steps to Reproduce
How to reproduce:

1. Install one of these games (Apex Leagues, Tom Clancy's Rainbow Six Siege, Valorant)
2. Sent OBS to game capture (Choose the game exe)
3. Play a short game on whatever capture settings and record in locally 

[2020-08-25 15-18-09.txt](https://github.com/obsproject/obs-studio/files/5123682/2020-08-25.15-18-09.txt)

**Comment by LEOkonami** [comment]
I found more users with the same issue
https://obsproject.com/forum/threads/obs-lagging.128931/
https://obsproject.com/forum/threads/lag-spikes.128927/
https://obsproject.com/forum/threads/video-not-smooth-even-though-i-recorded-it-in-60fps.128909/
https://obsproject.com/forum/threads/obs-framerate-spikes.128862/
https://obsproject.com/forum/threads/local-recording-really-bad-flickering-playback.128625/

**Comment by WizardCM** [comment]
The Issues page is not for support. Use our Discord for that.

For reference - your GPU can't keep up. Run OBS as admin.

**Comment by LEOkonami** [comment]
> The Issues page is not for support. Please use our Discord for that.
> 
> For reference - your GPU can't keep up. Run OBS as admin.

Looks the same event in admin mode... This worked just great 3 weeks ago~
I think there is a bigger issue here you overseeing, please take a closer look over this issue
[2020-08-25 15-34-09.txt](https://github.com/obsproject/obs-studio/files/5123735/2020-08-25.15-34-09.txt)

**Comment by RytoEX** [comment]
> This worked just great 3 weeks ago~
> I think there is a bigger issue here you overseeing,

If it worked great 3 weeks ago, and you haven't updated OBS, then the problem is more likely something on your PC, not OBS.

> Apex Leagues, Tom Clancy's Rainbow Six Siege, Valorant

These are all fairly demanding games.  Make sure you've capped your in-game FPS to something reasonable (like your monitor refresh rate, at most).  As @WizardCM said above, the Issues page is not for support.  We won't be replying to this with further troubleshooting.  Please use our Discord or forums for support.
