### ISSUE TITLE
A media source video cannot be started at a specific time when it transitions, with VLC video source it's possible

### ISSUE THREAD

**Issue by COOLIGUAY** [obsproject/obs-studio#3341]
## Platform

Operating system and version: Windows 10 Pro 1903
OBS Studio version: 25.0.8 and last nightly

## Expected Behavior

Media Source should work like VLC Video Source when transitioning a video that has already started (paused at some point).
The video should start from the point where it was paused.

## Current Behavior

Media Source doesn't start from the point where it was paused when transitioning, it will start from the beginning.
In the last nightly with source context bar, does not start from the beginning but it will fast forward trying to get to that point.

## Steps to Reproduce

With OBS Studio 25.0.8, Media Controls plugin is needed to use the seek bar.

1. In Studio Mode (preview), leave a Media Source video paused somewhere in the middle
2. Transition the scene in preview to program
3. The video will not start from the point where it was paused, it will start from the beginning
4. In the nightly, it will fast forward trying to get to that point

## Additional information

Video with 25.0.8 - VLC & Media Source
https://i.gyazo.com/8d04f0b5694ca9abefdab3a844f23599.gif

Nightly with the context bar - VLC & Media Source
https://i.gyazo.com/ed83bd8b0a141470484bc765c29b499a.gif
You can also see the high CPU consumption of issue https://github.com/obsproject/obs-studio/issues/3235.

It is very useful to be able to show a video from a specific point, not always only from the beginning.

**Comment by WizardCM** [comment]
As a side note, I'd be super curious to see if #3269 fixes this issue too.

**Comment by nkmerrill** [comment]
I can only somewhat reproduce this by setting the "restart playback when source becomes active" flag. #3269 does not stop the video from restarting in this scenario (I haven't looked too deeply but I think its treating this as a scene change), but it does fix the fast forward seeking that happens in the current build for me.

If you uncheck the "restart playback when source becomes active" flag, this works as expected for me in master and #3269. Can you confirm your media source settings?

**Comment by COOLIGUAY** [comment]
Without "Restart playback when source becomes active" the media source does not start to play in both versions (25.0.8 and nightly).

https://i.gyazo.com/1c6e8afe127082c98b3965b6a08c83de.gif

I tried with videos in .mp4 and 1 or 2 minutes long, with and without loop, hardware decoding and restart playback.

If you don't pause the video and transition when the video is running without restart playback, works properly.
The problem is start a video from pause, and also, the fast forward issue in the nightly.

Being able to do this would be great i.e. to have a replay, find an exact moment in that replay and leave it ready on pause and then transition to program when needed.

With VLC there is no problem, but you cannot take advantage of hardware decoding with VLC video source at the moment.

If https://github.com/obsproject/obs-studio/pull/3269 fixes this is great.

**Comment by nkmerrill** [comment]
With further testing, I'm confident the video fast-forwarding is a side effect of #3235. The problem is caused by resetting a paused video that has been paused for some time. The longer the video has been paused, the longer the fast forwarding occurs. You don't even need to use scene transitions to test this. Just pause a video, wait 10 seconds, then reset it. There will be a brief fast forward. #3269 fixes that.

As for the video staying paused after a transition, I'm not sure if that's a bug or by design. If the scene transition doesn't signal a play, then I see no reason the media source would begin playing.

**Comment by COOLIGUAY** [comment]
> #3269 fixes that.

Perfect!

> As for the video staying paused after a transition, I'm not sure if that's a bug or by design. If the scene transition doesn't signal a play, then I see no reason the media source would begin playing.

Probably by design, could be.
This makes sense with the restart playback option disabled.

With the option enabled, it seems more logical to me that the video starts playing whether it's paused at some point or starts from the beginning (not paused).

It's not really a problem for those who need to perform this function, they can do it with VLC.
But it seems better that both options (media or vlc) can work in the same way imo.

I really appreciate all your work!

**Comment by nkmerrill** [comment]
No problem!
