### ISSUE TITLE
libobs: obs_data_item_get_default_obj/_array returns bad data.

### ISSUE THREAD

**Issue by Xaymar** [obsproject/obs-studio#3357]
## Platform
Operating system and version: Windows 10 2004
OBS Studio version: master

## Expected Behavior
Calling `obs_data_item_get_default_obj` and `obs_data_item_get_default_array` should return the default values of an item.

## Current Behavior
Calling either of the functions returns the current user data, instead of the default data.

## Steps to Reproduce
1. Call `obs_data_item_set_default_obj` or `obs_data_item_set_default_array` with valid objects.
2. Call `obs_data_item_set_obj` or `obs_data_item_set_array` with valid or invalid objects.
3. Call `obs_data_item_get_default_obj` or `obs_data_item_get_default_array`.
4. Returned values mismatch actual default objects. Objects are now inaccessible.

## Additional information
1. https://github.com/obsproject/obs-studio/blob/master/libobs/obs-data.c#L1763-L1766
2. https://github.com/obsproject/obs-studio/blob/master/libobs/obs-data.c#L1768-L1771

This was accidentally found while testing the libobs validation layer I built to verify my plugin against. An obs_data test would always fail, despite being correct in theory, so investigation revealed that these two functions are the cause.

**Comment by WizardCM** [comment]
Would this be as simple as swapping out
```
get_item_obj -> get_item_default_obj
get_item_array -> get_item_default_array
```
for the second parameters in the return functions?

**Comment by Xaymar** [comment]
Looks like it.

**Comment by WizardCM** [comment]
Weirdly, `string`, `int` and `double`, and `bool` use `get_item_default_data` as their second parameter. I'll make a PR with that change instead, and we'll see from there.
