### ISSUE TITLE
obs crashes after uncertain time

### ISSUE THREAD

**Issue by zakii1337** [obsproject/obs-studio#3358]
## Platform

Operating system and version: Windows 10
OBS Studio version: 25.08 (64bit)

## Expected Behavior

no crashes

## Current Behavior

logfile: https://pastebin.com/4ghQQPQj
OBS crashes after some time when streaming to twitch

## Steps to Reproduce

1. Im not certain what causes this, I suspect it may be some hardware issue

**Comment by Fenrirthviti** [comment]
This crash is caused by system instability or hardware failure. Common fixes are disabling an unstable overclock or making sure the Ryzen BIOS is fully up to date. No further action possible on our end, unfortunately.
