### ISSUE TITLE
Bug: Any executable that begins with "time" will not show up in a Window Capture Source window selection.

### ISSUE THREAD

**Issue by KeithSwanger** [obsproject/obs-studio#3359]
## Platform

Operating system and version: Windows 10 1903
OBS Studio version: 25.0.8

## Expected Behavior
Create a window capture source for a game with a .exe that begins with "time" ("time crisis.exe", etc) or capture a timer application that is named "timer.exe"

## Current Behavior
Any executable that begins with `time` does not show up as selectable in a window capture source. 

## Steps to Reproduce

1. Rename any executable that runs in a window to begin with "time" ("timePhotoshop.exe", "timeBlender.exe", "timer.exe", etc)
2. Run the executable
3. Attempt to select the window in a Window Capture

## Additional information

The file [window-helpers.c](https://github.com/obsproject/obs-studio/blob/97ecf23df047e22847a9e613140233e4074bba9f/plugins/win-capture/window-helpers.c) seems to have something to do with the issue. For some reason, instead of checking for an exact match of "time.exe", it is checking for a partial match. The same behavior occurs with "cortana", "systemsettings", and others defined in `*internal_microsoft_exes_exact[]`

Thanks for reading!

**Comment by Fenrirthviti** [comment]
https://github.com/obsproject/obs-studio/commit/50e1d17615a0e8e83f81604a40b1d7cc4aa0ca04#diff-b704386539496a52c5fa9e85bc1400f3

This was already fixed, and should be testable in [RC1](https://github.com/obsproject/obs-studio/releases/tag/26.0.0-rc1), which was just published. Can you please test and confirm?

**Comment by KeithSwanger** [comment]
Confirmed as fixed! Should have searched more before posting, oops!

Thanks!
