### ISSUE TITLE
When opening the Properties for 'Video Capture Device' menu, UI is jumbled.

### ISSUE THREAD

**Issue by ldhacker** [obsproject/obs-studio#3368]
## Platform

Operating system and version: Manjaro Linux Kernel Version 5.8.3-2
OBS Studio version: 25.0.8-2 (linux) Dowloaded and Installed with Manjaro Pamac Package Manager

## Expected Behavior

A UI that is not jumbled together.

## Current Behavior

A UI where all the dropdown menus and text fields are jumbled together and not usable. 

## Steps to Reproduce

1. Open OBS Studio
2. Click Plus (+) under Sources
3. Click 'Video Capture Device (V4L2)'
4. Leave 'Create New' selected and 'Make Source Visible' checked. 
5. Click 'OK'

## Additional information

![OBS_Screenshot](https://user-images.githubusercontent.com/262713/91666199-ec7a0580-eac8-11ea-9f90-87abb2fc6be0.png)

**Comment by notr1ch** [comment]
Manjaro Linux is not an officially supported platform, you may want to raise this with the package maintainer for your distribution.

**Comment by ldhacker** [comment]
Thank you! Will do!
