### ISSUE TITLE
[BUG] Multiple Apple VT Encoders Freezes UI

### ISSUE THREAD

**Issue by unknowndomain** [obsproject/obs-studio#3369]
## Platform
Operating system and version: macOS 10.13
OBS Studio version: 25.0.8

## Expected Behavior
UI should prevent the user from being able to try to run multiple streams on the same single encoder.

## Current Behavior
User is able to configure both a streaming and recording encoder and attempt to start them which results in the second encoder appearing stuck and being unable to stop the encoder.

## Steps to Reproduce
1. Configure both streaming and recording encoders to use Apple VT, set recording to use MP4
2. Press start on recording
3. Press start on streaming
4. Stop recording - OK
5. Stop streaming - Fails

## Additional information
User log: https://obsproject.com/logs/FHgdJObYrwGHaQty

**Comment by PatTheMav** [comment]
I'm not able to reproduce this on my Mac Studio, does this still occur with OBS 28.0.3?

It could very well be a limitation of the Intel-based encoders, but I was able to record and stream with two separate VT-based encoders and OBS stopped both as expected.

**Comment by Fenrirthviti** [comment]
Closing as stale. If this is still an issue please open a new issue with updated reproduction steps on the latest version of OBS.
