### ISSUE TITLE
OBS Virtual Cam on macOS Big Sur 11.0 Beta (20A5354i)

### ISSUE THREAD

**Issue by UConnPhysicsLabTech-ZT** [obsproject/obs-studio#3370]
Hello all,

When I click "Start Virtual Camera", I am unable to get this feature of OBS to appear in Cisco WebEx, Zoom, Blackboard Collaborate Ultra (through a web browser) while running macOS Big Sur 11.0 Beta (20A5354i).

I am just reporting this here to make the developer community aware.

Best,
Zac

**Comment by Fenrirthviti** [comment]
I am assuming you mean in the v26 RC? There is no virtualcam output for macOS available, this button should not be showing up. Can you please provide a log file?

Also, in the future, please make sure you fill out the issue template rather than deleting it.

**Comment by UConnPhysicsLabTech-ZT** [comment]
Hello,

My apologies, I didn't realize I deleted a template. I am running v25.0.8 of OBS on my Mac and can see the Start Virtual Camera in the Tools menu.

Best,
Zac
[2020-08-30 18-18-08.txt](https://github.com/obsproject/obs-studio/files/5147557/2020-08-30.18-18-08.txt)

**Comment by Fenrirthviti** [comment]
There is no native macOS virtualcam as part of OBS v25.0.8. You are likely using the third party plugin, which should be reported on that repository instead: https://github.com/johnboiles/obs-mac-virtualcam

**Comment by UConnPhysicsLabTech-ZT** [comment]
Okay, thank you so much.

**Comment by gxalpha** [comment]
@UConnPhysicsLabTech-ZT in case you have questions regarding the virtualcam **plugin** for macos, refer to [this](https://github.com/johnboiles/obs-mac-virtualcam/) github repository
