### ISSUE TITLE
Tray Icon Bug After Stopping Virtual Camera

### ISSUE THREAD

**Issue by PowerNao** [obsproject/obs-studio#3375]
## Platform
Win 10 64bit 2004
26 RC1

## Expected Behavior
The red circle on the tray icon should disappear after stopping

## Current Behavior
Red circle remains on tray icon even when virtual camera is stopped

## Steps to Reproduce
1. Start virtual camera.
2. Stop the virtual camera.
3. A bug has occurred

## Additional information

**Comment by Cereal-Killa** [comment]
Same issue here, tray icon doesn't revert back when stopping the camera, plus my virtual camera is not showing up on streamyard.com website, which used to work fine when I was using the virtual camera standalone plugin so I'm guessing the installing didn't go well on my system.

**Comment by WizardCM** [comment]
This is partially related to #3018.

The Virtual Camera triggers `OnDeactivate()` twice (in `OnVirtualCamStop` and `StopVirtualCam`), which causes side effects. I'd personally recommend removing it from `StopVirtualCam()` as running that will trigger the former anyway.

https://github.com/obsproject/obs-studio/blob/6df30951f561a2c357499083b07e5d7dda85c5bf/UI/window-basic-main.cpp#L6217

https://github.com/obsproject/obs-studio/blob/6df30951f561a2c357499083b07e5d7dda85c5bf/UI/window-basic-main.cpp#L6191

**Comment by WizardCM** [comment]
Fixed in https://github.com/obsproject/obs-studio/commit/4869167f5c3161a3930d5f10b1778d1b53f97d0c
