### ISSUE TITLE
OBS 25.0.8 crash on iMac OS 10.15.6.. Freezes whole computer

### ISSUE THREAD

**Issue by rhinoxnation** [obsproject/obs-studio#3379]
OBS 25.0.8 crash on iMac OS 10.15.6.. Freezes whole computer

after a couple hours of streaming, it crashes and I have to hold the power button in on the computer to do a restart.
can't shift command escape to force quit the app... it crashes the whole computer.

half the screen is blue and half the screen is grey when this happens

doesnt happen all the time, but has happened 2 or 3 times. don't really know how to reproduce the issue

only things running were Chrome (latest version) and OBS 25.0.8

iMac is a 2015 model running latest OS with 24 gb of memory.. about 300 gigs of disk space available

**Comment by Fenrirthviti** [comment]
Please properly fill out the issue template.
