### ISSUE TITLE
Hotkeys don't save with Python scripts

### ISSUE THREAD

**Issue by cg2121** [obsproject/obs-studio#3384]
## Platform
Operating system and version: Any
OBS Studio version: 26.0.0-rc1 & previous versions as well

## Expected Behavior
Hotkeys should save when using Python scripts

## Current Behavior
When using a Python script, the hotkeys don't save when shutting down OBS.

## Steps to Reproduce
1. Load Python script that uses hotkeys
2. Set the hotkey in the settings
3. Hotkey works normally
4. Shut down and reload OBS
5. Hotkey is no longer set, having to go into settings and set it again

## Attachment
Attached is an example script with a hotkey, the script does nothing. It is just to show that the settings don't save when setting a hotkey and restarting OBS.

[test-hotkeys.zip](https://github.com/obsproject/obs-studio/files/5158680/test-hotkeys.zip)

**Comment by Scrxtchy** [comment]
I've had hotkeys working on my scripts, I will have to see what's different here

**Comment by Scrxtchy** [comment]
You are missing a `global hotkey` term from your `script_load` function. The hotkey variable that's created on line 18 is only local to that function.
This is something I spent a week debugging two years ago

**Comment by cg2121** [comment]
As @Scrxtchy pointed out, I was handling the variables wrong.
