### ISSUE TITLE
Cant add Desktop Audio using BackgroundMusic

### ISSUE THREAD

**Issue by firefinchdev** [obsproject/obs-studio#3392]
## Platform
Operating system and version: macOS, 10.15.6

## Expected Behavior
Desktop Audio can be recorder using Soundflower(2ch /64ch), but there is no option to select BackgroundMusic as source for Desktop Audio.
(Please see: https://github.com/kyleneideck/BackgroundMusic#recording-system-audio)

## Current Behavior
BackgroundMusic not listed as an option for desktop audio source

## Steps to Reproduce
1. Open OBS Preferences
2. Select Audio section
3. Try selecting Audio source 1
4. Only listed options are "Default", "Soundflower(2ch)", "Soundflower(64ch)", but "BackgroundMusic" is not listed even though BackgroundMusic is installed.

Please see the attached screenshot. It shows the available devices on macOS (sounflower and BackgroundMusic are included), but OBS dont have option to include BackgroundMusic.

BackgroundMusic is quite useful and famous. Adding support for it in OBS will be awesome.

<img width="1536" alt="Screenshot 2020-09-02 at 9 42 35 PM" src="https://user-images.githubusercontent.com/26357501/92009312-f3717400-ed65-11ea-8d32-c9edc10946be.png">

**Comment by Fenrirthviti** [comment]
These audio devices are actually input, check under Mix/Auxiliary. We have simple string matching to show common macOS sound routing applications under Desktop Audio, so non-standard devices or devices with custom names will instead show under Mic/Auxiliary inputs.

In the future, please use the Forums or Discord for support. https://obsproject.com/help

**Comment by firefinchdev** [comment]
Thanks for the info.
