### ISSUE TITLE
'save projectors on exit' does NOT work when inputting method is Chinese of Microsoft.

### ISSUE THREAD

**Issue by iesvme** [obsproject/obs-studio#3401]
## Platform

Operating system and version: WIn10 1809 LTSC
OBS Studio version: 26.0.0

## Expected Behavior

'save projectors on exit' does NOT work when inputting method is Chinese of Microsoft.

Steps to Reproduce
1. Switch the inputting method to Chinese of Microsoft.
2. Launch the OBS that had been checked 'save projectors on exit' 
3. And now the projector is full of gray instead.

**Comment by Scrxtchy** [comment]
I cannot replicate this, I think I need to adjust my Windows Display Language to Chinese for it to have the effect. 
It's hard to think about why it is indeed not working when OBS does not load the projector if the source name is not found

**Comment by iesvme** [comment]
Let me show you Gif, please.

https://github.com/iesvme/Gif/blob/master/obs-bug.gif
