### ISSUE TITLE
OBS crashes

### ISSUE THREAD

**Issue by lcalder** [obsproject/obs-studio#3411]
[2020-09-04 09-45-40.txt](https://github.com/obsproject/obs-studio/files/5177395/2020-09-04.09-45-40.txt)
[2020-09-04 16-32-47.txt](https://github.com/obsproject/obs-studio/files/5177396/2020-09-04.16-32-47.txt)

**Comment by Fenrirthviti** [comment]
Neither of those are crash logs, and you have provided no actionable information, and you deleted the template. Please provide the actual crash log and fill out the issue template.

**Comment by lcalder** [comment]
Where to find the crash logs?

**Comment by Fenrirthviti** [comment]
This feels like a support request, please use the Discord or forums for support.

https://obsproject.com/help

**Comment by lcalder** [comment]
[Crash 2020-09-03 22-48-10.txt](https://github.com/obsproject/obs-studio/files/5177405/Crash.2020-09-03.22-48-10.txt)
[Crash 2020-09-04 15-32-25.txt](https://github.com/obsproject/obs-studio/files/5177406/Crash.2020-09-04.15-32-25.txt)
[Crash 2020-09-04 16-30-57.txt](https://github.com/obsproject/obs-studio/files/5177407/Crash.2020-09-04.16-30-57.txt)
Sorry I just found the right location for the crash logs... Where do I find the template?

**Comment by skeletonbow** [comment]
When you file a new bug report there is a template to fill out right in the bug report.
