### ISSUE TITLE
window capturing a chromium based window crashes obs

### ISSUE THREAD

**Issue by Qverb** [obsproject/obs-studio#3416]
## Platform
Windows 10
OBS Version: 25.0.8

## Expected Behavior
Switching Scenes

## Current Behavior
Window Capture a chrome tab leads to crash when switching scenes

## Steps to Reproduce
1. Window Capturing a chrome tab on both scenes
2. Switching these scenes make OBS crash without creating a crashlog

**Comment by Fenrirthviti** [comment]
If OBS is not creating a crash log, can you please be more specific what is actually happening? I cannot replicate this issue on my end, so we need more information.

**Comment by Fenrirthviti** [comment]
Closing for now, cannot replicate. If you can provide more information and repeatable replication steps I can reopen this.

**Comment by JaielSoft** [comment]
Window Capturing an Electron based windows desktop application crashes OBS 25 when switching between scenes that window capture same app window.

Source of it could be the new feature to run chromium based application with hardware acceleration that used to produce a black screen prior to OBS 25. Downgrade was necessary to OBS 24 to stop OBS from crashing. Tested on two different PC's.

Should be replicatable by Window capturing same Chrome tab on two different scenes and switching between them multiple times. Crash occurs after several tries.

Might also be only an issue with Electron based application windows, but they basically are run on the same engine that Chrome uses for displaying tabs in their webbrowser.
