### ISSUE TITLE
[Linux] Some times maximize from tray doesn't appear as normal

### ISSUE THREAD

**Issue by Aikatsui** [obsproject/obs-studio#3417]
**Platform**
Operating system and version: PopOS 20.04.01 LTS | Gnome
OBS Studio version: 25.0.8 64bit (using apt)

**Expected Behavior**
OBS studio maximize properly when click 'show' button on tray

**Current Behavior**
Appear maximize animation and nothing open then again need to click 'show' button to open the obs studio window.
Sometimes if i have any other opened window then whole obs studio window show as preview of it then again need to minimize and maximize or re-configure screen or windows capture sources.

**Steps to Reproduce**

1. Open OBS studio and minimize to tray
2. Right click on tray icon and click 'show'

**Additional information**
No stuck, slowdown or else.

**Comment by Fenrirthviti** [comment]
Please fully fill out the issue template.

**Comment by KizunaH** [comment]
@Fenrirthviti Above included all possible details able to provide and cover the issue template However let me know if that details insufficient to recognize the problem or required to add screenshots and other details

**Comment by Fenrirthviti** [comment]
The details are out of order and make it difficult to parse. The template is designed so that we can quickly find and look at the relevant information. When you delete the template, you are sending a message that following our process is not worth your time, which means this report is unlikely to be looked at.

**Comment by KizunaH** [comment]
> The details are out of order and make it difficult to parse. The template is designed so that we can quickly find and look at the relevant information. When you delete the template, you are sending a message that following our process is not worth your time, which means this report is unlikely to be looked at.

Added template

**Comment by aliyazdi75** [comment]
I have the same issue. After like 3-5 seconds after obs started up. The maximize button disappears.

**Comment by aliyazdi75** [comment]
![Peek 2022-01-05 22-40](https://user-images.githubusercontent.com/20153831/148274950-454376cf-4ce0-4507-886c-a069e3e23f01.gif)

**Comment by aliyazdi75** [comment]
This is odd because I have dual monitors and my first one is the primary one but the obs opens in the second one without the maximize button.

**Comment by aliyazdi75** [comment]
As I think this is not going to fix soon, I used snap obs and works as expected.

**Comment by tytan652** [comment]
Not reproducible with OBS 28 on Arch Linux (GNOME 42) and Ubuntu 22.04.

If this is still an issue, we can reopen this.
