### ISSUE TITLE
[Linux] Profiles sources changes apply globally

### ISSUE THREAD

**Issue by KizunaH** [obsproject/obs-studio#3419]
**Steps to Reproduce**

1. Default profile: Untitled then add some sources
2. Profile > new > add name and save
3. Create new profile again or go to untitled profile and create new profile
4. Go to the new profile and add some other sources or delete existing sources
5. Check other profiles, you can be see it applied to them

PopOS 20.04.01 LTS | Gnome | 25.0.8 64bit

**Comment by kkartaltepe** [comment]
Profiles do not manage sources.

**Comment by KizunaH** [comment]
I noticed 'Scenes' in use for that.
