### ISSUE TITLE
Right and left arrow keys move the media control progress bar, but not the actual media being played

### ISSUE THREAD

**Issue by tmurph** [obsproject/obs-studio#3421]
Platform
===

Operating system and version: Linux 5.2.0 64-bit
OBS Studio version: 26.0.0-rc1 64-bit

Expected Behavior
===

When using the media controls in the new source toolbar, space should pause / resume playback, and the right and left arrow keys should advance / back up the playback by some amount. 

Current Behavior
===

Space pauses and resumes, but the arrow keys only affect the appearance of the progress bar. When the right / left arrow keys are pressed the slider button moves forward / backward in the progress bar, but the actual video playback is unaffected.  This happens when the video is running, as well as if the video is paused (playback resumes from the initial pause point, regardless of how far the slider is moved due to right / left arrow keys).

Steps to Reproduce
===

1.   Add a VLC Video Source and a video file.  Let it play.
2.   Click and drag the slider button to some arbitrary point.
3.   Press and hold the right arrow key for a few seconds.
4.   The slider button slides to the right, but the video continues playing as normal.  Also, the slider button continuously jumps back to where it was before pressing the right arrow key.
5.   Pause the video (either with the space bar or the media control).
6.   Press the right arrow key several times.
7.   The slider button advances to the right.
8.   Unpause the video.
9.   The video continues playing from when it was paused, and the slider button jumps back to where it was before pausing.

Same thing with the left arrow key to back up.  

Additional Information
===

Same thing when controlling Media sources (both video and audio).

**Comment by dodgepong** [comment]
While space and arrow keys seem like reasonable hotkeys to do what you want to do on a surface level, I would actually suggest that the space bar and arrow keys doing _anything at all_ to the media controls would be unintentional behavior, especially if they have not been explicitly set as hotkeys to do those things. For example, if I have a source selected, I would expect arrow keys to nudge the source around the preview, not move the play head. The fact that the space bar toggles play/pause at all is probably a Qt behavior whereby the spacebar triggers a button press on whatever button is in focus.
