### ISSUE TITLE
Portable Build: Librnnoise missing

### ISSUE THREAD

**Issue by zenny** [obsproject/obs-studio#3424]
Hi I am trying to follow a portable build  (in pursuant to https://github.com/obsproject/obs-studio/wiki/install-instructions#linux-portable-mode-all-distros) in voidlinux (there is a problem to build external plugins with the default obs xpbs pacakge in void (https://github.com/void-linux/void-packages/issues/24706#issuecomment-687720959).

However, librnnoise was not listed as required dependency, however, I am getting:

```
$ cmake -DUNIX_STRUCTURE=0 -DCMAKE_INSTALL_PREFIX="${HOME}/Downloads/obs-studio-portable" -DBUILD_BROWSER=ON -DCEF_ROOT_DIR="../../cef_binary_3770_linux64" ..
...
-- Found ftl-sdk: ftl outputs enabled
-- Found Libspeexdsp: /usr/bin/../lib64/libspeexdsp.so
-- Could NOT find Librnnoise (missing: RNNOISE_LIB RNNOISE_INCLUDE_DIR)
-- Noise Reduction effect enabled
CMake Error at UI/CMakeLists.txt:50 (find_package):
  By not providing "FindQt5Svg.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Svg", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5Svg" with any
  of the following names:

    Qt5SvgConfig.cmake
    qt5svg-config.cmake

  Add the installation prefix of "Qt5Svg" to CMAKE_PREFIX_PATH or set
  "Qt5Svg_DIR" to a directory containing one of the above files.  If "Qt5Svg"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
```

Any clue?

**Comment by tt2468** [comment]
You need to build rnnoise from source and install it.

**Comment by Fenrirthviti** [comment]
This build failure appears to be a Qt5 issue, not RNNoise.

Please use the Forums or Discord for support. Additionally, in the future, if you are reporting an actual bug do not delete the issue template.
