### ISSUE TITLE
Twitch connect button not visible

### ISSUE THREAD

**Issue by BlitzKraft** [obsproject/obs-studio#3430]
## Platform

Operating system and version: Sabayon Linux amd64 20.03
OBS Studio version: 25.0.8

## Expected Behavior

In stream settings, selecting twitch for streaming should show a button to connect twitch account, using username and password.

## Current Behavior

"Connect Account (optional)" button does not show up at all.

## Steps to Reproduce

1. Install obs-studio using `sudo equo install obs-studio` (installs version 25.0.8 - latest)
2. Start obs (`/usr/bin/obs`)
3. Open settings ( File -> Settings -> Stream)
4. Select streaming service to twitch
5. Expect to see "connect account" button, but it is not present.

## Additional information

This is on sabayon KDE edition. Sabayon is downstream of gentoo. `equo` is the package manager for this distro.

**Comment by Fenrirthviti** [comment]
Service integration is currently Windows only.

**Comment by BlitzKraft** [comment]
Is it possible to enable it on linux? I would build it myself, if that is an option.

**Comment by Fenrirthviti** [comment]
There is a significant amount of development work that needs to be done to enable browser docks on linux first.

**Comment by nanoni17728** [comment]
Bumping this issue.

Browser docks are now enabled on Linux and we can add custom twitch docks manually, but it is quite hard to find what URLs to provide to get the same docks as Windows.

I’m ready to work to make the twitch integration possible on Linux if needed.

**Comment by Gol-D-Ace** [comment]
> Bumping this issue.
> 
> Browser docks are now enabled on Linux and we can add custom twitch docks manually, but it is quite hard to find what URLs to provide to get the same docks as Windows.
> 
> I’m ready to work to make the twitch integration possible on Linux if needed.

The service integrations are already available.

Please either use the version from the PPA or the Flatpak Beta.

Other versions will not have the service integrations available.

**Comment by nanoni17728** [comment]
My bad, I haven’t checked past the current standard release.

**Comment by dodgepong** [comment]
To be clear, the only "standard" ("official") release of OBS Studio 27.1.3 on Linux is the PPA. If you didn't install it via the PPA, then integrations won't be available.

As of OBS Studio 27.2 (currently in beta), the Flatpak will also be officially maintained by the OBS team and will have integrations available. Service integrations are not available on the 27.1.3 Flatpak.

**Comment by heyleao** [comment]
I managed to make it work!!!! I made a backup of my Obs Windows Profile and imported it into obs linux. I think it's something in the "nameless" json file.
