### ISSUE TITLE
Missing -fPIC

### ISSUE THREAD

**Issue by yurivict** [obsproject/obs-studio#3436]
Build fails on some FreeBSD systems:
```
ld: error: relocation R_386_PC32 cannot be used against symbol strlist_split; recompile with -fPIC
```

Log: http://beefy5.nyi.freebsd.org/data/121i386-default/547958/logs/obs-studio-26.0.0.r1.log

## Platform

Operating system and version: FreeBSD 12.1 i386
OBS Studio version: 26.0.0-rc1

Likely the issue is only present on i386 architectures.

## Expected Behavior
Build succeeds.

## Current Behavior
Build breaks.

## Steps to Reproduce

Build the package: cmake . && gmake

## Additional information
none

**Comment by Fenrirthviti** [comment]
Please properly fill out the issue template.

**Comment by Gol-D-Ace** [comment]
This is also also happening on Ubuntu 16.04 aka Xenial. Probably happening because of an too old x264 version that didn't include this.

Compilation on newer Ubuntu versions with newer x264 Versions does work fine..

**Comment by Gol-D-Ace** [comment]
Just checked and it might not be necessary age.
Bionic for example is using 2:0.152.2854+gite9a5903-2 which is older than the version in your log

**Comment by yurivict** [comment]
FreeBSD uses x264 revision cde9a933 from 2 months ago (https://code.videolan.org/videolan/x264/-/commits/master).

**Comment by notr1ch** [comment]
This is unrelated to libx264 as it's the libobs x264 option parsing code that is the issue. For some reason `libobs-x264-util` is being built without `-fPIC` like all other modules.

**Comment by notr1ch** [comment]
Please try this patch: https://github.com/notr1ch/obs-studio/commit/479f80c1ea4347ed27fff7b837922626d8113f1d

**Comment by yurivict** [comment]
This would be quite difficult and long for me to test, because failing systems are only on the farm.

Could you please just check that all commands have -fPIC in them, this should be sufficient.

**Comment by notr1ch** [comment]
OBS does not set CFLAGS directly, they are generated by CMake. I have updated the CMakefiles to include the option for PIC, which I presume will now set CFLAGS to contain -fPIC, however I also have no system on which to test this.

**Comment by yurivict** [comment]
When you run 'make VERBOSE=1' it print all command lines. You can just compare before and after logs.
