### ISSUE TITLE
[Windows] webm crash with default settings

### ISSUE THREAD

**Issue by CyrilWaechter** [obsproject/obs-studio#3440]
## Platform
Operating system and version: Windows 10
OBS Studio version: 25.0.8

## Expected Behavior
Record keep going without any crash and output a readable webm file.

## Current Behavior
Get `Woops, OBS  has crashed!` after few seconds.

## Steps to Reproduce
1. Open settings
2. Select webm container. Using this option auto set video encoder to libvpx-vp9 and audio encoder to libopus.
3. Set audio to 48 kHz to fix issue with libopus (https://github.com/obsproject/obs-studio/issues/2503).
4. Start recording -> Get `Woops, OBS  has crashed!` after few seconds

## Additional information
* [Crash log](https://github.com/obsproject/obs-studio/files/5195021/Crash.2020-09-09.13-54-58.txt)
* Apparently some people have already tried for a long time to find workaround to make it work without any success : [forum thread](https://obsproject.com/forum/threads/even-going-back-trought-past-editions-of-obs-doesnt-help-when-you-are-dealing-with-no-possible-encoding-or-similar-result-with-the-vp9-opus-help.121607/).
* Recording using same settings on Manjaro Linux using same computer works.

**Comment by WizardCM** [comment]
The exact code in OBS where this error gets triggered is:
https://github.com/obsproject/obs-studio/blob/5662ec699198532915364d483a3fbb1fee80ca87/plugins/obs-ffmpeg/obs-ffmpeg-output.c#L766-L769

```
 	libvpx-1.dll!00000000664022f3()	Unknown
 	libvpx-1.dll!000000006642f765()	Unknown
 	libvpx-1.dll!0000000066431805()	Unknown
 	libvpx-1.dll!00000000663c722d()	Unknown
 	libvpx-1.dll!0000000066281c01()	Unknown
 	avcodec-58.dll!00007ff9fd2c4f8c()	Unknown
 	avcodec-58.dll!00007ff9fd08348d()	Unknown
 	avcodec-58.dll!00007ff9fd083c72()	Unknown
>	obs-ffmpeg.dll!receive_video(void * param, video_data * frame) Line 768	C
 	obs.dll!default_raw_video_callback(void * param, video_data * frame) Line 1712	C
 	[Inline Frame] obs.dll!video_output_cur_frame(video_output *) Line 142	C
 	obs.dll!video_thread(void * param) Line 188	C
 	w32-pthreads.dll!ptw32_threadStart(void * vthreadParms) Line 225	C
 	[External Code]	
```

**Comment by GuardianLiarus** [comment]
So that's where my issue has been comming from, i couldn't record at all in WebM

**Comment by Fasteroid** [comment]
still waiting for a fix...

**Comment by RytoEX** [comment]
While I can crash OBS Studio 27.2.4 with these settings (though, without a crash log), I can not reproduce this in OBS Studio 28.0.3. The default webm settings in "Custom Output (FFmpeg)" produce a readable webm file.

**Comment by szmarczak** [comment]
OBS 29.1.3 goes "Not Responding" for me on Windows. On Linux it freezes as well.
