### ISSUE TITLE
Download link for Mac torrent file seems to be broken, returns 404

### ISSUE THREAD

**Issue by yb66** [obsproject/obs-studio#3446]
## Current Behavior

There's a 404 on the given link for the torrent file. I've tried it with 2 different browsers (Firefox and Safari) and wget.

## Steps to Reproduce

```
wget https://obsproject.com/downloads/torrents/obs-mac-25.0.8.dmg.torrent
--2020-09-10 15:15:46--  https://obsproject.com/downloads/torrents/obs-mac-25.0.8.dmg.torrent
Resolving obsproject.com (obsproject.com)... 149.56.72.190
Connecting to obsproject.com (obsproject.com)|149.56.72.190|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-09-10 15:15:48 ERROR 404: Not Found.
```

Regards,
iain

**Comment by skeletonbow** [comment]
I can confirm the file gives a 404 error here as well.  Where did you find the link to that BTW, I wasn't able to find torrent links on the OBS website, didn't know it was available over torrent also.
