### ISSUE TITLE
Error while installing 26.0-rc2

### ISSUE THREAD

**Issue by chrisinhim** [obsproject/obs-studio#3452]
## Platform

Operating system and version:
OBS Studio version:

## Steps to Reproduce

1.
2.
3.
4.

![image](https://user-images.githubusercontent.com/43258549/92920847-95711a80-f450-11ea-9f3b-d875d29d15e8.png)

**Comment by WizardCM** [comment]
This means the camera is in use, mostly likely by Microsoft Teams. Close it first.
