### ISSUE TITLE
The cursor will disappear when it is in an TextEdit area

### ISSUE THREAD

**Issue by HaujetZhao** [obsproject/obs-studio#3454]
## Platform
Operating system and version: Windows 10 2004 19041.450
OBS Studio version: 26.0.0

## Expected Behavior
The cursor should be captured. 

## Current Behavior
When the mouse move into a TextEdit area and become a **工** shape, then it will disappear from the OBS scene, no matter in any softwares. 

I have tried reinstalling Windows newest version, then install OBS, but this issue still exists. 

See the pictures below: 

![image](https://user-images.githubusercontent.com/19181833/92923583-43d58980-f46a-11ea-86cb-3aca9b012c68.png)

![image](https://user-images.githubusercontent.com/19181833/92923629-58198680-f46a-11ea-87f9-2f860c2d0b8d.png)

![image](https://user-images.githubusercontent.com/19181833/92923759-84350780-f46a-11ea-98e6-b44785c557ed.png)

**Comment by WizardCM** [comment]
Duplicate of #3129 - which is likely a dupe of #2604

**Comment by notr1ch** [comment]
Not sure this is a duplicate - I tested this myself and the cursor is actually rendered, but with the wrong inversion.

![image](https://i.imgur.com/wMJcDEy.png)

**Comment by rafaltrzop** [comment]
I have found a workaround for this problem on OBS forums:
https://obsproject.com/forum/threads/mouse-cursor-doesnt-change-to-contrast-background.74839/#post-321835

Workaround for Windows platform:
1. In OBS, inside the Sources panel, right-click your Display Capture and select Properties. Inside the Properties window turn off Capture Cursor checkbox and click OK.
2. Open Windows Magnifier program (Windows key + "+" key) and zoom out to 100% (Windows key + "-" key).
3. Leave Windows Magnifier program open in the background and record a video with OBS - now your cursor should be recorded correctly.

**Comment by mufunyo** [comment]
> I have found a workaround for this problem on OBS forums:
> https://obsproject.com/forum/threads/mouse-cursor-doesnt-change-to-contrast-background.74839/#post-321835
> 
> Workaround for Windows platform:
> 
> 1. In OBS, inside the Sources panel, right-click your Display Capture and select Properties. Inside the Properties window turn off Capture Cursor checkbox and click OK.
> 2. Open Windows Magnifier program (Windows key + "+" key) and zoom out to 100% (Windows key + "-" key).
> 3. Leave Windows Magnifier program open in the background and record a video with OBS - now your cursor should be recorded correctly.

This is because the Magnifier disables the hardware cursor. Another way to disable the hardware cursor is to enable cursor trails with a trail length of zero.

**Comment by HJassar** [comment]
![image](https://user-images.githubusercontent.com/5434867/113531381-3f032f00-958e-11eb-9b40-b977f6db5ea2.png)
Changing the pointer color did the trick for me, inspired by @mufunyo 's trail length response.

**Comment by xinruoshinian** [comment]
Environment: Win10 system, 3840*2160 resolution, display zoom 150%.
This will also happen on my side, when the cursor is moved into the input box and transformed into an I-shaped cursor, the preview does not actually see the screen, I use obs 30.2.2 preview and this situation will still occur, currently my code integrates this part of the function, how should this situation be modified in the code?
If I restore the zoom to 100%, the cursor will be able to display the preview normally again.
