### ISSUE TITLE
File selection button in Remux Recordings is just a white box

### ISSUE THREAD

**Issue by jimthesfn** [obsproject/obs-studio#3455]
## Platform

Operating system and version: Windows 10 19041.508
OBS Studio version: 26.0.0-rc2

## Expected Behavior

When you go to Remux Recordings under File in the menu and you are to select a file, the box should have 3 ... and use the theme settings color scheme for it.

## Current Behavior

When you go to Remux Recordings under File in the menu and you are to select a file the box is just a white box until you mouse over it and then the 3 ... appears.
This issue happens under the themes Acri, Dark(default) and Rachni.

## Steps to Reproduce

1. Go to File in the menu and pick Remux Recordings
2. You then see that the file selection box is all white
3.
4.

**Comment by WizardCM** [comment]
After bisecting this, looks like https://github.com/obsproject/obs-studio/commit/fddbbe259da6091086d457666241a13d3e9c3e23 is the first bad commit (it introduced the Source Toolbar). Unfortunately, nothing immediately stands out, so I shall keep digging.

**Comment by WizardCM** [comment]
Ah, OK I've now tracked it down to this line.

https://github.com/obsproject/obs-studio/blob/32dca37304c890f1952bc24315f250bf62fc0acf/UI/obs-app.cpp#L1093

My guess is it overrides the styling from the stylesheet, causing the button to change colour.

**Comment by jp9000** [comment]
Whoops, forgot to mark that this was fixed in 5978094fa0.
