### ISSUE TITLE
Memory Leak When Removing Audio Device

### ISSUE THREAD

**Issue by Programatic** [obsproject/obs-studio#3457]
## Platform
Operating system and version: Linux (also on windows 10)
OBS Studio version: Current Master

## Expected Behavior
No memory leaks on exit

## Current Behavior
When you delete an audio device in the settings, it creates 111 memory leaks 

## Steps to Reproduce

1.Go to audio settings in settings
2. If no audio devices enabled, enable one to some device.
3. Set the device back to disabled.
4. Exit

## Additional information
I believe I have tracked the memory leak to OBSBasic::ResetAudioDevice, specifically 
`if (disable) {
			obs_set_output_source(channel, nullptr);
		} else {`

**Comment by Programatic** [comment]
I traced the issue to `delete volumes[i];` in DeactivateAudioSource. Ignore that commit, it was just me screwing around with it.

**Comment by norihiro** [comment]
Does this issue still persist?
I tried the same step on Linux and there is no memory leaks reported.
(The step 2 is ambiguous. It is not clear I need to click `Ok` to apply settings or just go to the step 3 without applying settings. However, I don't see memory leaks in either way.)

**Comment by jp9000** [comment]
This issue shouldn't be happening anymore -- if it is, please let us know and we'll reopen it.
