### ISSUE TITLE
OBS virtual camera does not work in apps that need an "imaging device" and don't support directshow source

### ISSUE THREAD

**Issue by barfin** [obsproject/obs-studio#3458]
## Platform
Operating system and version: Windows 10 version 2004
OBS Studio version:  26.0 Release Candidate 2

## Steps to Reproduce
1. Install something like Xsplit Vcam that needs imaging device
2. Start OBS virtual camera

**Comment by Fenrirthviti** [comment]
I'm not sure if this bug report belongs with us, and you deleted half the template.

This sounds like you need to report to xsplit, as the virtualcam is registered as a directshow device, so it is up to them to support it, not us to support them.

**Comment by barfin** [comment]
> 
> 
> I'm not sure if this bug report belongs with us, and you deleted half the template.
> 
> This sounds like you need to report to xsplit, as the virtualcam is registered as a directshow device, so it is up to them to support it, not us to support them.

but it's not only xsplit vcam there are many apps like this for example windows 10's default camera app

**Comment by WizardCM** [comment]
@barfin Windows 10's Camera app uses Media Foundation instead of DirectShow, so it doesn't show virtual DirectShow devices.
