### ISSUE TITLE
No Longer Launches after QT Update

### ISSUE THREAD

**Issue by sangoku116** [obsproject/obs-studio#3464]
## Platform

Operating system and version: Arch Linux 5.8.8 Zen kernel
OBS Studio version: 25.0.8-2

## Expected Behavior

The app should launch.

## Current Behavior

The app does not launch and gives the following message:

```
Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use:
   QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors.
   QT_SCREEN_SCALE_FACTORS to set per-screen DPI.
   QT_SCALE_FACTOR to set the application global scale factor.
Cannot mix incompatible Qt library (5.15.0) with this library (5.15.1)
[1]    18922 abort (core dumped)  obs
```

## Steps to Reproduce

Type obs in terminal. 

## Additional information

QT was updated on arch linux today and obs is expecting the older version.

**Comment by dodgepong** [comment]
We don't manage the Arch AUR. Please report this issue to your package manager.

**Comment by sangoku116** [comment]
> We don't manage the Arch AUR. Please report this issue to your package manager.

It's not in the AUR it is in the community packages.

**Comment by Fenrirthviti** [comment]
The only package we directly maintain is the Ubuntu PPA. You will still need to reach out the owner of the package and report this to them.
