### ISSUE TITLE
UI: Renaming a source in the list does not return keyboard or mouse focus to the list

### ISSUE THREAD

**Issue by Xaymar** [obsproject/obs-studio#3465]
## Platform

Operating system and version: Windows 10 2004
OBS Studio version: 25.0.8

## Expected Behavior
Keyboard control should not be lost when renaming an item using F2, allowing selection of items via Arrow Keys.

## Current Behavior
Keyboard focus is lost after renaming an item with F2, disallowing selection with arrow keys.
The focus is lost completely, no item is now in focus.

## Steps to Reproduce

1. Create two sources of any kind.
2. Select either of them with the mouse in the sources list.
3. Verify that keyboard control is on the list by moving with arrow keys.
4. Rename the current item with F2, and either cancel (ESCAPE) or finish (ENTER) editing.
5. Try to continue controlling the sources list via Keyboard.
6. Notice that it stopped working.

## Additional information
Does not affect scenes, only sources.

**Comment by skeletonbow** [comment]
Tested and confirmed with 25.0.8/x64 on Windows 10/1909

**Comment by jberenhaus** [comment]
Mind if I take a shot at this one on Tuesday? 

Assuming I can get an environment up in a reasonable amount of time, I should have some time to learn and get a local repro to play with.

Thanks for the pointer to https://github.com/obsproject/obs-studio/blob/f96b6dfeed0c4d6ded4f655a75d8443d3564bf31/UI/source-tree.cpp#L340 @WizardCM

**Comment by jberenhaus** [comment]
Repro'ed on Win10 2004
OBS 26.0.2 (64-bit)

Working on a fix
