### ISSUE TITLE
Bug: Beta 1 & 2 recording in Variable Frame Rate

### ISSUE THREAD

**Issue by JohnEaglez** [obsproject/obs-studio#3466]
Operating system and version: Windows 10 
OBS Studio version: OBS Studio 26.0 Release Candidate 2

## Expected Behavior
Recording frame rate should match what we set in video settings

## Current Behavior
Recording frame rates are always higher than what is set in video settings and show up as "variable frame rate". I have confirmed this via multiple computers. OBS 25 does not have this issue. Example: if recording 59.94 fps, OBS 26 records at 60.12 or some other number. This is happening with all frame rate settings on OBS 26. This is confirmed by windows file explorer when turning on the detailed panel. also confirmed by Premiere Pro metadata. Please test it and you will see. 

## Steps to Reproduce
1. Make sure you have detailed panel enabled: https://i.imgur.com/lDdHcRp.png
2. Set your video settings frame rate on both OBS 25 and OBS 26 to be identical and record a video on both versions.
3. Single click on the recorded file and you will see the OBS 26 version had added frames. 

4. If you want to go extra mile, bring both clips to premiere pro and right click on each, then click "properties" and you will see the OBS 25 version does not give you the "varible frame rate" warning. 

Why is this important?
Adobe's manual states that premiere runs better than video matches sequence settings, so its important that OBS 26 recorded videos match whatever we set in the video settings of OBS.

**Comment by pyorot** [comment]
This has been confirmed in the final release as well, reported twice ([1](https://obsproject.com/forum/threads/obs-26-recording-in-vfr-now-how-do-i-change-back-into-cfr.132287/), [2](https://obsproject.com/forum/threads/vfr-variable-frame-rate-problem-confirmed.132925/)) and yet to receive a single response. Most tools used in speedrun communities to time runs from video break from VFR, so it's important that OBS is able to produce a CFR video with duplicated frames as standard.

**Comment by Senku2022** [comment]
Can this bug be fixed, please, it's been 1 year and 5 months since it was reported.

**Comment by Fenrirthviti** [comment]
As far as I know this is simply an issue with metadata, not the files themselves, and with how media editors trust metadata too much. If you feel it is a bug, and you understand what the solution is, please submit a PR with the fix. This issue has been basically dormant for a year, as it's not really a big concern.

**Comment by Senku2022** [comment]
I'm an idiot, I thought this issue is about remux, sorry for posting.

**Comment by NotesOfReality** [comment]
If Hitfilm Express is worth trusting this isn't just a matter of metadata, if I force 60 FPS in the editor settings the issues typical of a variable frame rate file don't go away at all.

**Comment by RytoEX** [comment]
I can confirm that this occurs in OBS Studio 28.0.3 with NVENC when it falls back to the FFmpeg path. I am still looking into this, and I have a vague idea of why this occurs, but I will need some time to work out a few more pieces of the puzzle.

**Comment by jerpdoesgames** [comment]
Freaking hell.  This is the cause of TWO YEARS of frustration with nonfunctional proxies in Premiere that I could just not figure out until today.
