### ISSUE TITLE
Window Capture Blank Screen with Bugged Cursor

### ISSUE THREAD

**Issue by ammarasyad** [obsproject/obs-studio#3469]
## Platform

Operating system and version: Windows 10 2004
OBS Studio version: 26.0-rc2

## Expected Behavior

Just like in previous versions, I should be able to use the application in the foreground without OBS capture getting "corrupted."

## Current Behavior

When the captured app is in the foreground, OBS seems to be unable to capture the window properly, showing a blank screen with a bugged cursor, like an error back from the Windows XP days. Logs don't show anything unusual, nor does it pick up the issue, so I don't think it's necessary.

## Steps to Reproduce

1. Window capture, any window (_this only happens in Windows Graphics Capture, BitBlt does not have any issues_)
2. Preview looks normal, switch to the captured window
3. Done, bug reproduced.

## Additional information

I have attached screenshots regarding the issue. Also my system specs are Intel Core i5-3230M, NVIDIA GeForce GT 740M, 8GB RAM. To further emphasize this issue does **not** occur in release build (OBS Studio 25). I have noticed that my GPU Usage goes up from 11% to >20% when the issue occured.
![Screenshot (95)](https://user-images.githubusercontent.com/20443208/93035885-7220b800-f668-11ea-96a5-e684c6d55326.png)
![Screenshot (96)](https://user-images.githubusercontent.com/20443208/93035889-75b43f00-f668-11ea-86e8-0808b1146e57.png)

**Comment by flaeri** [comment]
cannot reproduce on RC2, win10 2004. Tried with explorer windows and a few others in WGC. Cursor and window captures fine, on both monitors.

**Comment by ammarasyad** [comment]
Weird. An isolated case, maybe? It's just so weird that it only happens in rc2, and it's exclusive to WGC. If so, any tips or recommendations to try and workaround the problem?

**Comment by ammarasyad** [comment]
Somehow the issue fixed itself, I don't know how. Maybe its because I messed around in BitBlt and WGC, because there's an option to capture cursor in WGC which shouldn't be there, but it stays there, even upon restart. Since this is most likely an isolated case, I'll close this issue.
