### ISSUE TITLE
[x264] Unable to join existing stream

### ISSUE THREAD

**Issue by raytrap** [obsproject/obs-studio#3471]
Operating system: Windows 10 x64
OBS Studio version: 25.0.8

### Steps to reproduce
1. Set up external server as SRT receiver in listen mode (nimble streamer in my case)
2. Configure SRT/RTSP endpoint pulling from stream in step 1. Make sure no transcoding is happening on the server. 
3. Set OBS to stream to SRT listener from step 1
4. Start streaming session in OBS
5. Wait 30 seconds
6. Connect to SRT/RTSP endpoint from step 2 using VLC or ffplay

### Expected Behavior
It is possible to connect (with VLC or ffplay) to existing session re-streamed via nimble stremer/srt-live-server

### Current Behavior
Only clients that were connected and waiting for stream to start get image decoded. Neither ffplay nor VLC are able to join active session. 

### Additional information
When x264 compressed stream from OBS is distributed to clients (using srt/rtmp) without server-side transcoding it is not possible to join existing session. The reason for that seems to be that codec is not configured to re-transmit PPS info with each keyframe. I would rather expected this configured this way for offline encoding. Is there a reason that is disabled for a live streaming application? Setting b_repeat_headrs true here solved the problem for me:
https://github.com/obsproject/obs-studio/blob/86147d971966de0554c4020f361dc89b9db48beb/plugins/obs-x264/obs-x264.c#L616

Although this doesn't affect most of scenarios OBS is currently being used in, the suggested change still makes sense to me.

**Comment by Fenrirthviti** [comment]
Please properly fill out the issue template with replication steps on the issue you are having. If this is just a general question and not a bug report, I would recommend reaching out via the forums or discord instead.

**Comment by sensodejay** [comment]
There is already a pull request for this #3083 "UI: Enable sps/pps (video headers) repetition (for srt/mpegts). You can download the Build from there an check if solve you issue.

**Comment by raytrap** [comment]
Oh, I should have researched better. Thanks for pointing me at that.
