### ISSUE TITLE
Display Capture Recording did not happen smoothly. so many frames are missed and skipped due to rendering and encoding lag respectively.

### ISSUE THREAD

**Issue by chrisinhim** [obsproject/obs-studio#3484]
Recording didn't happen properly.

## Platform

Operating system and version: Windows 10 version 2004
OBS Studio version: 26.0.0-rc2

## Expected Behavior

Expected smooth video and audio recording

## Current Behavior

thousands of frames are skipped and missed due to encoding and rendering lag respectively.

## Steps to Reproduce

1. Have a Display Capture source and record screen for 5 mins.
2.
3.
4.

## Additional information

Please find attached the log.
[2020-09-19 21-49-19.txt](https://github.com/obsproject/obs-studio/files/5250219/2020-09-19.21-49-19.txt)

**Comment by Mister36MN** [comment]
The issues section of github is not for regular support problems. Please go to the discord or the forums if you need help.

**Comment by chrisinhim** [comment]
I'm using OBS 26.0.0-rc2. that's why I thought it's a bug.
