### ISSUE TITLE
Installer fails when virtual camera is in use

### ISSUE THREAD

**Issue by exeldro** [obsproject/obs-studio#3486]
Installing OBS RC3 I got this error:
![Error Installing OBS RC3](https://user-images.githubusercontent.com/5457024/93705134-1c8e5480-fb1b-11ea-80a2-53e4d4e46508.png)

I think the updater might have the same issue.

## Platform
Operating system and version: Windows 10
OBS Studio version: OBS RC3

## Expected Behavior
A warning for the user to close all programs that use the virtual camera

## Current Behavior
![Error Installing OBS RC3](https://user-images.githubusercontent.com/5457024/93705134-1c8e5480-fb1b-11ea-80a2-53e4d4e46508.png)

## Steps to Reproduce
1. Have a version of OBS installed with the virtual camera option.
2. Make sure the camera is in use by for example Microsoft Teams
3. Try to run the installer of OBS 26 RC3

## Additional information
This issue might also happen in the updater

**Comment by jp9000** [comment]
Fixed in https://github.com/obsproject/obs-studio/commit/e9a0b417957bfbfb54cc3e856765ce92ced80c16
