### ISSUE TITLE
Context-Bar Media and VLC Source "Play/Pause" Icon is a "Reload" Icon? (26-RC3)

### ISSUE THREAD

**Issue by starfishpatkhoo** [obsproject/obs-studio#3491]
## Platform

Operating system and version: Windows 10 2004
OBS Studio version: 26-RC3 x64

## Expected Behavior

The `Play/Pause` button icon in the Context-Bar for Media Source and VLC Source should be more like https://www.svgrepo.com/svg/311430/video-play-pause

## Current Behavior

Currently, it looks like https://www.svgrepo.com/svg/64968/reload-arrow which is.. `Reload`.. But it functions like `Play/Pause`. The tooltip is correct though.. 

When one is live streaming, there is no time to look at a tooltip, so I was confused for a long while... Ha ha ha.. ^_^

## Steps to Reproduce

1. Add a Media Source or a VLC Playlist Source
2. Play it and press the `Stop` and `Play/Pause` .. I mean `Reload` buttons..

**Comment by WizardCM** [comment]
The only time I see the "reload" button is when the source is stopped, with the correct "Restart media" tooltip.

Please provide full reproduction steps, including exactly which source type, which properties are changed, and whether you're playing local file.

![image](https://user-images.githubusercontent.com/941350/93842297-b6036500-fcd9-11ea-868a-6e4e1efcbad9.png)

**Comment by starfishpatkhoo** [comment]
Oh! My bad!

I been using Material Dark theme.. Guess that's what that was!

I switched to default Dark and it works correctly. No biggie.. Closing this bug.. ^_^
