### ISSUE TITLE
Preview change its position after I click on another window

### ISSUE THREAD

**Issue by diegoveloper** [obsproject/obs-studio#3495]
I have some sources using windows capture, and every time I click on a different window , the preview change its position.

## Platform

Operating system and version: macOS Catalina 10.15.6
OBS Studio version: 25.0.8 (64 bit)

## Expected Behavior

The position of the preview should be in the same position after we click on another window.

## Current Behavior

The position of the preview change which is very annoying when you are recording.

## Steps to Reproduce

1. Add a window capture source like an IDE (vscode).
2. Select another window different from the IDE.
3. Check in OBS how it changes the position.

## Additional information

![preview_bug](https://user-images.githubusercontent.com/4898256/94225606-1271aa80-febb-11ea-8eb4-08d76ca68a0f.gif)

**Comment by diegoveloper** [comment]
Any news about this issue ? :/ is pretty annoying

**Comment by WizardCM** [comment]
My guess is the capture source is capturing the shadow, and when the window isn't focused the shadow goes away.

Try this:

1. Right click the source in the list
2. Go to Transform -> Edit Transform
3. Under "Positional alignment" change it to "Center"
4. Reposition the source.

I'm personally not sure if this is something we can work around.

**Comment by diegoveloper** [comment]
> My guess is the capture source is capturing the shadow, and when the window isn't focused the shadow goes away.
> 
> Try this:
> 
> 1. Right click the source in the list
> 2. Go to Transform -> Edit Transform
> 3. Under "Positional alignment" change it to "Center"
> 4. Reposition the source.
> 
> I'm personally not sure if this is something we can work around.

Unfortunately it doesn't work either. Do you know another workaround?

**Comment by diegoveloper** [comment]
> My guess is the capture source is capturing the shadow, and when the window isn't focused the shadow goes away.
> 
> Try this:
> 
> 1. Right click the source in the list
> 2. Go to Transform -> Edit Transform
> 3. Under "Positional alignment" change it to "Center"
> 4. Reposition the source.
> 
> I'm personally not sure if this is something we can work around.

Hey @WizardCM , now that you mentioned `shadow` , I unchecked the `Show Window shadow` option and it works perfect!

![Screen Shot 2020-12-06 at 10 42 14 AM](https://user-images.githubusercontent.com/4898256/101284810-e4a8bc00-37af-11eb-9103-84ce9f76a311.png)  
`Uncheck 'Show Window shadow' option`.

Thanks so much.

**Comment by mufunyo** [comment]
So is it accurate to conclude that active and inactive windows have different shadow dimensions, and it would be best to position the source relative to the window borders rather than relative to the shadows? Does macOS expose something similar to GetClientRect?
