### ISSUE TITLE
VLC Video Source Cannot Bypass DVD Menus

### ISSUE THREAD

**Issue by Baa14453** [obsproject/obs-studio#3499]
## Platform

Operating system and version: "Ubuntu" "20.04" Linux 5.4.0-47-generic
OBS Studio version: OBS 26.0.0-rc2-17-g2963b3b8 (linux)

## Expected Behavior
OBS VLC Video Source skips disk menus on DVDs and Blurays to play the movie directly.

## Current Behavior
Upon reaching the disk menu the media will stay on the menu because there is no ability to interact with it.

## Steps to Reproduce
1. Create a VLC Video Source
2. Add a random video file to the playlist
3. Edit the file path so it goes directly to the disk drive:
![image](https://user-images.githubusercontent.com/9057997/94309469-0b58a400-ff70-11ea-9a55-bf13fe8f3cc5.png)

4. Play the disk.

## Additional information
VLC Media Player has a 'No disc menus' checkbox that skips the disk menu and plays the film straight away, if this could be set the default for the VLC Video Source in OBS then it should resolve the issue:
![image](https://user-images.githubusercontent.com/9057997/94309709-67bbc380-ff70-11ea-8502-60d220b348d3.png)

**Comment by WizardCM** [comment]
As far as I can tell, libvlc doesn't expose that option in its API.

I think the only workaround would be to try loading with `dvdsimple://` or for someone to spend the time to implement an Interact UI that'd allow you to click on menu items.

**Comment by RytoEX** [comment]
This seems like a feature request. We do not intend to implement support for this feature.

**Comment by Baa14453** [comment]
yeah fair enough
