### ISSUE TITLE
Window display doesnt show track playhead on garage band

### ISSUE THREAD

**Issue by quantuminformation** [obsproject/obs-studio#3501]
## Platform

Operating system and version: MacOS 10.x
OBS Studio version: 25.0.7

## Expected Behavior

should see the playhead line 
![image](https://user-images.githubusercontent.com/216566/94323380-d9f2cf00-ff95-11ea-827a-7a33a2423201.png)

## Current Behavior

is gone in window capture, but fine with display capture
![image](https://user-images.githubusercontent.com/216566/94323386-e6772780-ff95-11ea-9927-9cf1f2515a20.png)

## Steps to Reproduce

1.open garage band
2. connect with capture window
3. playhead is gone

**Comment by quantuminformation** [comment]
Same issue with logic pro X

![image](https://user-images.githubusercontent.com/216566/94338698-9c715e80-fff4-11ea-9780-1c3a08b0ab72.png)

**Comment by gxalpha** [comment]
We can't reproduce this issue in OBS 28 on macOS 12.
If it still appears for you on the current version of OBS and macOS, feel free to open a new report.
