### ISSUE TITLE
显卡nvenc使用游戏源的情况下载一些场景nvenc画面下会出现黑色闪缩

### ISSUE THREAD

**Issue by 1265578519** [obsproject/obs-studio#3502]
显卡nvenc使用游戏源的情况下载一些场景nvenc画面下会出现黑色闪缩

出现问题的游戏有
Call of Duty：Modern Warfare
Death Stranding

demo video https://www.youtube.com/watch?v=2R3IFkh7r0I

**Comment by notr1ch** [comment]
Please use forums (https://obsproject.com/forum/list/windows-support.32/) or Discord for help. Until this is a confirmed bug, Github issues is not the right place to report it.

**Comment by 1265578519** [comment]
You have been banned for the following reason: Spam. Please contact the administrator if this was done in error..

我无法在论坛发送帖子，账号被锁定了，如果有人看到，希望可以帮我发一下

**Comment by notr1ch** [comment]
What is your forum username?

**Comment by 1265578519** [comment]
> What is your forum username?

丶小樱
