### ISSUE TITLE
CoreAudio is not available under certain conditions. (Windows)

### ISSUE THREAD

**Issue by style1925** [obsproject/obs-studio#3503]
## Platform

Operating system and version: Windows 10 2004
OBS Studio version: OBS Studio 26.0.0-rc3 (All versions available for CoreAudio)

## Expected Behavior

need to be able to use CoreAudio.

## Current Behavior

CoreAudio cannot be used when installing iTunes newly.
("AppleApplicationSupport.msi" and "AppleApplicationSupport64.msi" have been removed from the iTunes installer.)

## Steps to Reproduce

1. Prepare an environment where Apple Application Support (32bit) and Apple Application Support (64bit) is not installed.
2. Install iTunes (12.10.9.3).
3. Start OBS Studio.
4. View logfile.
```
[CoreAudio encoder]: Failed loading library 'CoreAudioToolbox.dll'
[CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
```

## Additional information

https://hydrogenaud.io/index.php?topic=119889.0
*"CoreAudioToolbox.dll" is located in "C:\Program Files\iTunes\CoreAudioToolbox.dll".
(I use Google Translate. I apologize if my English is strange.)

**Comment by WizardCM** [comment]
Looks like OBS looks in `Program Files\Common Files\Apple\Apple Application Support`

https://github.com/obsproject/obs-studio/blob/d4ce4061381d4bcefd6a7a188d8a17bc2381ed5b/plugins/coreaudio-encoder/windows-imports.h#L384

As you mentioned, they've moved it to the iTunes app directory. We'd have to support both, as there are a number of users (myself included) who won't install iTunes.
