### ISSUE TITLE
REC stops when transition

### ISSUE THREAD

**Issue by makishart** [obsproject/obs-studio#3505]
Operating system and version: windows 10 pro
OBS Studio version: 25.0.8 64bit

## Expected Behavior
It should start rec

## Current Behavior
Rec canceled after another action

## Steps to Reproduce
1.In studio mode while streaming make a transition to a scene.
2.Then press rec
3.Then press transition whatever is on preview window.
4.Rec stops

**Comment by Fenrirthviti** [comment]
Please provide a log file after this happens, I have not been able to replicate.

**Comment by makishart** [comment]
Ok actually I found out what was causing it.. It wasn't transition by mouse click but by using ctrl+space shortcut and then space hits rec button also
