### ISSUE TITLE
Linux Video Capture Device Graphical Bugs

### ISSUE THREAD

**Issue by foosroos** [obsproject/obs-studio#3506]
I am working on incorporating capturing footage from my PlayStation Vita through OBS using the vita plugin [udcd-uvc](https://github.com/xerpi/vita-udcd-uvc). When loading the video input capture in OBS, 50% of the screen is green, as well as some other graphical bugs. The issue does not occur when displaying the video on other players (mplayer, Cheese, VLC).

## Platform

Operating system and version: Debian 10 (installed from source)
OBS Studio version: 26.0 (have replicated the issue on 25.0)

## Expected Behavior

The video feed should be free from graphical bugs.

## Current Behavior

The capture device is split with a green color as well as different distortions.

## Steps to Reproduce

1. Plug Vita into machine
2. Open OBS
3. Add Video Input Capture Source
4. Select Vita
5. Preview becomes this: 

![](https://raw.githubusercontent.com/foosroos/ignorethisshit/master/Screenshot%20from%202020-09-26%2013-23-53.png?token=AQAV2E43WD3VUTMB7UCTXQK7N6QRM)

Log:

> 

> 01:50:56 PM.258: CPU Name: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
> 01:50:56 PM.258: CPU Speed: 2402.340MHz
> 01:50:56 PM.259: Physical Cores: 4, Logical Cores: 8
> 01:50:56 PM.259: Physical Memory: 7753MB Total, 783MB Free
> 01:50:56 PM.259: Kernel Version: Linux 5.7.0-0.bpo.2-amd64
> 01:50:56 PM.259: Distribution: "Debian GNU/Linux" "10"
> 01:50:56 PM.259: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.4
> 01:50:56 PM.260: Portable mode: false
> 01:50:56 PM.477: OBS 26.0.0-rc2-2-g88a30267 (linux)
> 01:50:56 PM.477: ---------------------------------
> 01:50:56 PM.503: ---------------------------------
> 01:50:56 PM.503: audio settings reset:
> 01:50:56 PM.503: 	samples per sec: 48000
> 01:50:56 PM.503: 	speakers:        2
> 01:50:56 PM.514: ---------------------------------
> 01:50:56 PM.514: Initializing OpenGL...
> 01:50:56 PM.547: Loading up OpenGL on adapter Intel Open Source Technology Center Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2) 
> 01:50:56 PM.547: OpenGL loaded successfully, version 4.5 (Core Profile) Mesa 18.3.6, shading language 4.50
> 01:50:56 PM.583: ---------------------------------
> 01:50:56 PM.583: video settings reset:
> 01:50:56 PM.583: 	base resolution:   1920x1080
> 01:50:56 PM.583: 	output resolution: 1920x1080
> 01:50:56 PM.583: 	downscale filter:  Bicubic
> 01:50:56 PM.583: 	fps:               30/1
> 01:50:56 PM.583: 	format:            NV12
> 01:50:56 PM.583: 	YUV mode:          709/Partial
> 01:50:56 PM.583: NV12 texture support not available
> 01:50:56 PM.584: Audio monitoring device:
> 01:50:56 PM.584: 	name: Default
> 01:50:56 PM.584: 	id: default
> 01:50:56 PM.584: ---------------------------------
> 01:50:56 PM.586: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
> 01:50:56 PM.703: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
> 01:50:56 PM.703: No blackmagic support
> 01:50:56 PM.711: [obs-browser]: Version 2.8.7
> 01:50:56 PM.736: FFMPEG VAAPI supported
> 01:50:56 PM.751: VLC found, VLC video source enabled
> 01:50:56 PM.751: ---------------------------------
> 01:50:56 PM.751:   Loaded Modules:
> 01:50:56 PM.751:     vlc-video.so
> 01:50:56 PM.751:     text-freetype2.so
> 01:50:56 PM.751:     rtmp-services.so
> 01:50:56 PM.751:     obs-x264.so
> 01:50:56 PM.751:     obs-vst.so
> 01:50:56 PM.751:     obs-transitions.so
> 01:50:56 PM.751:     obs-outputs.so
> 01:50:56 PM.751:     obs-libfdk.so
> 01:50:56 PM.751:     obs-filters.so
> 01:50:56 PM.751:     obs-ffmpeg.so
> 01:50:56 PM.751:     obs-browser.so
> 01:50:56 PM.751:     linux-v4l2.so
> 01:50:56 PM.751:     linux-pulseaudio.so
> 01:50:56 PM.751:     linux-jack.so
> 01:50:56 PM.751:     linux-decklink.so
> 01:50:56 PM.751:     linux-capture.so
> 01:50:56 PM.751:     linux-alsa.so
> 01:50:56 PM.751:     image-source.so
> 01:50:56 PM.751:     frontend-tools.so
> 01:50:56 PM.751:     decklink-ouput-ui.so
> 01:50:56 PM.751: ---------------------------------
> 01:50:56 PM.751: os_dlopen(../obs-plugins/obs-browser->../obs-plugins/obs-browser.so): ../obs-plugins/obs-browser.so: cannot open shared object file: No such file or directory
> 01:50:56 PM.751: 
> 01:50:56 PM.751: ==== Startup complete ===============================================
> 01:50:56 PM.754: All scene data cleared
> 01:50:56 PM.754: ------------------------------------------------
> 01:50:56 PM.758: v4l2-input: Start capture from /dev/video1
> 01:50:56 PM.876: v4l2-input: Input: 0
> 01:50:56 PM.878: v4l2-input: Resolution: 1280x720
> 01:50:56 PM.878: v4l2-input: Pixelformat: 21VN
> 01:50:56 PM.878: v4l2-input: Linesize: 1280 Bytes
> 01:50:56 PM.878: v4l2-input: Framerate: 30.00 fps
> 01:50:56 PM.881: Switched to scene 'Scene'
> 01:50:56 PM.881: ------------------------------------------------
> 01:50:56 PM.881: Loaded scenes:
> 01:50:56 PM.882: - scene 'Scene':
> 01:50:56 PM.882:     - source: 'Video Capture Device (V4L2)' (v4l2_input)
> 01:50:56 PM.882: ------------------------------------------------
> 01:51:09 PM.818: v4l2-input: /dev/video3 seems to not support video capture
> 01:51:09 PM.820: v4l2-input: Found device 'PSVita' at /dev/video1
> 01:51:09 PM.821: v4l2-input: /dev/video4 seems to not support video capture
> 01:51:09 PM.936: v4l2-input: Found device 'Integrated Camera: Integrated C' at /dev/video2
> 01:51:09 PM.937: v4l2-input: Found input 'Input 1' (Index 0)
> 01:51:09 PM.939: v4l2-input: Pixelformat: Y/CbCr 4:2:0 (available)
> 01:51:09 PM.939: v4l2-input: Pixelformat: RGB3 (Emulated) (unavailable)
> 01:51:09 PM.939: v4l2-input: Pixelformat: BGR3 (Emulated) (available)
> 01:51:09 PM.939: v4l2-input: Pixelformat: YU12 (Emulated) (available)
> 01:51:09 PM.939: v4l2-input: Pixelformat: YV12 (Emulated) (available)
> 01:51:09 PM.941: v4l2-input: Stepwise and Continuous framerates are currently hardcoded
> 01:51:09 PM.942: v4l2-input: Pixelformat: Y/CbCr 4:2:0 (available)
> 01:51:09 PM.942: v4l2-input: Pixelformat: RGB3 (Emulated) (unavailable)
> 01:51:09 PM.942: v4l2-input: Pixelformat: BGR3 (Emulated) (available)
> 01:51:09 PM.942: v4l2-input: Pixelformat: YU12 (Emulated) (available)
> 01:51:09 PM.942: v4l2-input: Pixelformat: YV12 (Emulated) (available)
> 01:51:09 PM.944: v4l2-input: Stepwise and Continuous framerates are currently hardcoded
> 01:51:09 PM.946: v4l2-input: Stepwise and Continuous framerates are currently hardcoded
> 01:51:09 PM.947: v4l2-input: Stepwise and Continuous framerates are currently hardcoded
> 01:51:12 PM.889: v4l2-input: Stepwise and Continuous framesizes are currently hardcoded
> 01:51:12 PM.890: v4l2-input: Stepwise and Continuous framerates are currently hardcoded
> 01:51:12 PM.946: v4l2-input: Stopped capture after 481 frames
> 01:51:12 PM.947: v4l2-input: Start capture from /dev/video1
> 01:51:12 PM.948: v4l2-input: Input: 0
> 01:51:12 PM.949: v4l2-input: Resolution: 480x272
> 01:51:12 PM.949: v4l2-input: Pixelformat: 21VN
> 01:51:12 PM.949: v4l2-input: Linesize: 480 Bytes
> 01:51:12 PM.949: v4l2-input: Framerate: 60.00 fps
> 01:51:14 PM.810: v4l2-input: Stepwise and Continuous framesizes are currently hardcoded
> 01:51:14 PM.811: v4l2-input: Stepwise and Continuous framerates are currently hardcoded
> 01:51:14 PM.828: v4l2-input: Stopped capture after 112 frames
> 01:51:14 PM.829: v4l2-input: Start capture from /dev/video1
> 01:51:14 PM.830: v4l2-input: Input: 0
> 01:51:14 PM.831: v4l2-input: Resolution: 480x272
> 01:51:14 PM.831: v4l2-input: Pixelformat: 21VN
> 01:51:14 PM.831: v4l2-input: Linesize: 480 Bytes
> 01:51:14 PM.831: v4l2-input: Framerate: 60.00 fps
> 01:51:16 PM.442: v4l2-input: Stepwise and Continuous framesizes are currently hardcoded
> 01:51:16 PM.444: v4l2-input: Stepwise and Continuous framerates are currently hardcoded
> 01:51:16 PM.463: v4l2-input: Stopped capture after 98 frames
> 01:51:16 PM.464: v4l2-input: Start capture from /dev/video1
> 01:51:16 PM.466: v4l2-input: Input: 0
> 01:51:16 PM.467: v4l2-input: Resolution: 480x272
> 01:51:16 PM.467: v4l2-input: Pixelformat: 21VN
> 01:51:16 PM.467: v4l2-input: Linesize: 480 Bytes
> 01:51:16 PM.467: v4l2-input: Framerate: 60.00 fps
> 01:51:18 PM.241: v4l2-input: Stepwise and Continuous framerates are currently hardcoded

## Additional information

Similar issue was made on the udcd github: https://github.com/xerpi/vita-udcd-uvc/issues/44

**Comment by kkartaltepe** [comment]
replicated using ffmpeg and v4l2loopback

`ffmpeg -re -i some_file.mkv  -vf 'format=nv12' -f v4l2 /dev/videoX`
