### ISSUE TITLE
Crash with ffmpeg 4.3.1

### ISSUE THREAD

**Issue by valeth** [obsproject/obs-studio#3510]
## Platform
Operating system and version: Arch Linux
OBS Studio version: 25.0.8 (official repository package)

## Expected Behavior
OBS Studio does start and show the GUI

## Current Behavior
The program terminates with either SIGSEGV, SIGABRT, or SIGBUS

## Steps to Reproduce
1. Update ffmpeg version to 4.3.1
2. Try launching OBS Studio
3. Program crashes

## Additional information
Downgrading `ffmpeg` to version `4.2.3` completely fixes the issue

Sometimes there's additional log output, but it is not consistent.
Here are the logs of three consecutive runs:
[sigabrt-obs0.log](https://github.com/obsproject/obs-studio/files/5293333/obs0.log)
[sigabrt-obs1.log](https://github.com/obsproject/obs-studio/files/5293336/obs1.log)
[sigbus-obs2.log](https://github.com/obsproject/obs-studio/files/5293337/obs2.log)

**Comment by notr1ch** [comment]
We do not provide an official Arch Linux package, this issue should be raised with the package maintainer.

**Comment by kkartaltepe** [comment]
Doesnt crash with ffmpeg 4.3.1, as mentioned you or your package manager are probably doing something wrong.

**Comment by Gol-D-Ace** [comment]
Just for good measure.
Also no crashing with 4.3.1 here.

**Comment by valeth** [comment]
Leaving this here in case other people search for this
https://bugs.archlinux.org/task/68034

**Comment by valeth** [comment]
I looked further into this and the issue seems to come from an extremely specific combination of files.
Just posting my findings here in case anyone wants to investigate this further.

I managed to reproduce it on the following systems so far:

**Desktop 1:**
  OS: Arch Linux 64bit
  CPU: AMD FX-8350
  GPU: AMD RX480
  OBS: 25.0.8
  ffmpeg/libav: 4.3.1

**Laptop 1:**
  OS: Arch Linux 64bit
  CPU: Intel i7-2670QM
  GPU: Integrated
  OBS: 25.0.8
  ffmpeg/libav: 4.3.1

**Desktop 2:**
  OS: KDE Neon 5.19
  CPU: Intel i7-870
  GPU: AMD Radeon HD 5850
  OBS: 25.0.3
  ffmpeg/libav: 4.3.1 ([PPA])

Managed to reproduce the crash with the attached two files by putting them into the scene in various ways.
Most consistent method is dragging [File A] into the scene, removing it and dragging it in again.
Also got some crashes when dragging both [File A] and [File B] into the same scene.
Using the files after transcoding them into different format (e.g.: PNG) doesn't cause the crash anymore.

[File A]
[File B]



[File A]: https://mega.nz/file/ktQUzRyS#XnVMRbhkKYdFbUyy0K04t3LwVSi279-gx1wy89ojIok
[File B]: https://mega.nz/file/NsBG2LCA#tvcOMOKXGW5WTsIMHsk4UWJ89UBN_O6efbUh1UJPqlU
[PPA]: https://launchpad.net/~savoury1/+archive/ubuntu/ffmpeg4

**Comment by kkartaltepe** [comment]
Ah noticed you were using 25.0.8 there is a bad buffer allocation for jpgs in that version. Update to 26 for patches or conver the images to png as workaround.
