### ISSUE TITLE
Virtualcam cannot be started automatically

### ISSUE THREAD

**Issue by Technetium1** [obsproject/obs-studio#3513]
## Platform
Operating system and version: Windows 10
OBS Studio version: 26.0

## Expected Behavior

I was able to check a box in the settings for virtualcam to trigger an autostart when OBS starts.

## Current Behavior

There is no option anywhere in settings to autostart the virtualcam when OBS launches.

## Steps to Reproduce
N/A

## Additional information
![image](https://user-images.githubusercontent.com/9877150/94568586-af757000-023a-11eb-9b59-68aae773af57.png)

**Comment by Gol-D-Ace** [comment]
The virtualcam can automatically be started through the command line option
--startvirtualcam

Append this to the path (right click shortcut>properties >  obs64.exe" --startvirtualcam

**Comment by Technetium1** [comment]
Thank you
