### ISSUE TITLE
Audio interface over USB not working in Mac

### ISSUE THREAD

**Issue by brendt** [obsproject/obs-studio#3521]
## Platform
Operating system and version: Mac OSX Catalina (as well as Mojave)
OBS Studio version: 26.0 and older versions

## Expected Behavior
Audio input should work

## Current Behavior
You can add the audio interface (Motu MK2, but the same happens with all Motu interfaces), but no signal comes true

## Steps to Reproduce
1. Plug in Motu audio interface and validate that it's properly connected
2. Add audio input capture in OBS, select Motu
3. OBS receives no signal from it

**Comment by pkviet** [comment]
There's already a PR addressing this. The issue is that obs currently support devices with up to 8 audio channels on mac.

**Comment by brendt** [comment]
Could you share the issue?

**Comment by pkviet** [comment]
https://github.com/obsproject/obs-studio/pull/2889

This pr includes code increasing the number of audio channels, if i remember well.

**Comment by brendt** [comment]
Ok let's continue the conversation over there!
