### ISSUE TITLE
Digital pen cursor not followed by OBS

### ISSUE THREAD

**Issue by alberto-chiarini** [obsproject/obs-studio#3526]
## Platform

Operating system and version:
OBS Studio version: 26

## Expected Behavior

I should be able to record my digital pen cursor when Capture cursor is on.

## Current Behavior

When recording my cursor the mouse is recorded but the digital pen cursor is not recorded. Sometimes it get recorded but in the position of the mouse. This is working in the previous release 25.

## Steps to Reproduce

1. Open any application record its window with capture cursor on
2. Over a digital pen on it -> you don't see the cursor recorded
3. Over the mouse on it -> you see it recorded

**Comment by Fenrirthviti** [comment]
Try changing the capture modes between BitBlt and WGC and see if this corrects the issue for you.

In the future, please use the forums or Discord for support: https://obsproject.com/help
