### ISSUE TITLE
Regression: macOS "Window Capture" window filtering too aggressive (Version 25.0.8 --> 26.0.0)

### ISSUE THREAD

**Issue by uberkelium** [obsproject/obs-studio#3528]
## Platform

Operating system and version: macOS 10.14.1 Mojave
OBS Studio version: 26.0

## Expected Behavior

"[zoom.us] Poll", which is a separate window from the Zoom application, should be a selectable option in "Window Capture" source

## Current Behavior

"[zoom.us] Poll" is not an option anymore

## Steps to Reproduce

1. Create Zoom meeting, create poll which then appears as a pop-up window (not configurable)
![image](https://user-images.githubusercontent.com/22272118/94733523-c1c7da80-031c-11eb-8653-1474b39df741.png)
2. Add a "Window Capture" source in OBS Studio 26.0
3. Try to add "[zoom.us] Polls" in "Window Capture" source
![image](https://user-images.githubusercontent.com/22272118/94733540-c8565200-031c-11eb-9c8c-03c6d181ca61.png)

## Additional information

Though I understand the intent of #3388, which was to filter clutter in macOS, it is easy to ignore clutter, but it is not easy to ignore not being able to select a window

Downgrading to 25.0.8 shows that "[zoom.us] Polls" is an option for "Window Capture"
![image](https://user-images.githubusercontent.com/22272118/94732507-34d05180-031b-11eb-98e3-29c7b6f27a2a.png)

**Comment by steveseguin** [comment]
https://github.com/steveseguin/electroncapture/issues/32

The application we use to support macOS users with video capture has broken with OBS v26.

I've had three user complaints today. I expect quite a few more of the coming days.  I'll try to fix this on my end, but it might break the always-on-top functionality of our app.

kindly,
steve

**Comment by chrismarquardt** [comment]
Is there something I can do to get the old filtering back? This change has removed a central app from Display Capture and Window Capture that is mission critical for my daily use.

**Comment by kkartaltepe** [comment]
It looks instead of the changes in #3388 something like modifying the options to CGWindowListCopyWindowInfo to include excludeDesktopElements (https://developer.apple.com/documentation/coregraphics/quartz_window_services/window_list_option_constants) would be less likely to affect user applications the filtering all windows at the top level. If anyone affected can test this and send a PR that would be great.

**Comment by steveseguin** [comment]
For reference, our application is an Electron.js app and it uses these settings to ensure the app is always on top (on macOS). 

```
mainWindow.setAlwaysOnTop(true, "floating", 1);
mainWindow.setVisibleOnAllWorkspaces(true);
```

In testing, when we disable the always-on-top feature, the app appears listed in OBS for capture. The always-on-top functionality is needed on macOS to ensure other elements (other windows, system UI, or popups) do not get captured accidentally.

This electron app is used to address the existing limitations with OBS's CEF webRTC implementation.

**Comment by WizardCM** [comment]
Looks like Jim has reverted the original changes for now. I will keep this issue open for anyone who would want to take a stab at using the API suggested by @kkartaltepe

**Comment by rayzorfist** [comment]
This is still a problem. Older setup scenes will find the old window but you cannot set up a new scene using the window in question. In my case it's an Audio Hijack meter. With 26.0.2 I can see the window in my original scene again but cannot set up a new scene with the same window.

I'm attaching two screen captures. One shows the old scene with the Audio Hijack window selected and one shows the new scene I was trying to set up and the Audio Hijack window is not visible.

Version 25.0.8 works perfectly in this regard.
![Screen Shot 2020-10-07 at 7 10 27 PM](https://user-images.githubusercontent.com/6672931/95400800-3082d600-08d1-11eb-8e83-a7c18e8730e4.png)
![Screen Shot 2020-10-07 at 7 10 58 PM](https://user-images.githubusercontent.com/6672931/95400813-37a9e400-08d1-11eb-87a3-688a632d2da8.png)

**Comment by Fenrirthviti** [comment]
The commit was completely reverted, I am unsure how it would behave differently between the two versions. A revert means the change was undone, so the code is now identical to 25.0.8. Might need further investigation. Can you provide log files from both versions after attempting to capture the window?

**Comment by rayzorfist** [comment]
OK, I may be a complete idiot. 

I just did another test with 26.0.2. The window is there. I didn't have the bloody option to show windows with empty names checked! Doh! 

I'm really sorry for the confusion here. 

This is working in 26.0.2 on Mac OS Catalina 10.15.7.

Again, really sorry for the mix-up.

**Comment by Fenrirthviti** [comment]
No worries! Thanks for the follow up. We're looking in to a better way of filtering out the junk windows that doesn't affect legitimate ones. Keep an eye on future updates for more information.
