### ISSUE TITLE
macOS "Window Capture" displays last frame of window when closed

### ISSUE THREAD

**Issue by hi-usui** [obsproject/obs-studio#3529]
## Platform

Operating system and version: macOS 10.14.6 Mojave
OBS Studio version: 26.0.0

## Expected Behavior

"Window Capture" should stop displaying when a window is closed in macOS

## Current Behavior

"Window Capture" source only shows the last frame before the window was closed
![a mov](https://user-images.githubusercontent.com/22272118/94742300-55ec6e80-032a-11eb-83c9-da0646a7c4af.gif)

## Steps to Reproduce

1. Add a "Window Capture" source
2. Close the window

## Additional information

Someone reported this on support forums 2020-06-02
https://obsproject.com/forum/threads/window-capture-staying-on-screen-in-obs-after-closed-window.123690/

Windows 10 OS has the behavior where it stops displaying if window closes.
Expecting the same behavior on macOS, please correct if wrong.

**Comment by dossy** [comment]
It would be nice if after `mac-capture` detects that the window being captured has disappeared because the application has terminated, it can signal to OBS to hide the input source, so that not only does the displayed content go away, the capture thread can stay asleep and not consume any CPU.

**Comment by Fenrirthviti** [comment]
Closing as stale. If this is still an issue please open a new issue with updated reproduction steps on the latest version of OBS.
