### ISSUE TITLE
Settings -> Output with Output Mode "Advanced": cannot view or edit encoder properties in Streaming tab when profile has encoder in it that is no longer available

### ISSUE THREAD

**Issue by YorVeX** [obsproject/obs-studio#3531]
## Platform
Operating system and version: Windows 10 Pro Build 2004 (x64)
OBS Studio version: 26.0.0

## Expected Behavior
In the Output settings in "Advanced" Output Mode when only the x264 encoder is available the encoder properties should still be shown and editable in the below window section.

## Current Behavior
The encoder properties section just says "No properties available" and there doesn't seem to be any way to bring these settings up. 

## Steps to Reproduce
Run OBS 26.0.0 on a computer that only supports the x264 encoder (i.e. doesn't have any graphics device or QuickSync capable CPU), go to Settings -> Output and set "Output Mode" to "Advanced".

## Additional information
On computers that offer more than one encoding option this problem doesn't occur.
This issue also existed in 25.0.8.

**Comment by Fenrirthviti** [comment]
Please provide a log file.

**Comment by YorVeX** [comment]
Here is a log of a session where I started OBS, did the reproduction steps as mentioned above, then closed everything again:
[2020-10-01 03-42-33.txt](https://github.com/obsproject/obs-studio/files/5309034/2020-10-01.03-42-33.txt)

Here's also a screenshot of the result:
![Advanced-Output](https://user-images.githubusercontent.com/528974/94756796-c6ca6f80-0398-11eb-8d11-5967e3a47d93.jpg)

**Comment by Fenrirthviti** [comment]
It looks like you have imported or copied a profile from a system with an encoder selection that does not exist on this PC:

```03:42:34.850: Encoder ID 'amd_amf_h264' not found
03:42:34.850: Encoder ID 'amd_amf_h264' not found```

You can fix this by simply creating a new profile from the profile menu, but I agree that this is a bug we should address when an encoder is no longer available. It's a pretty rare edge case where this can actually happen.

**Comment by YorVeX** [comment]
Right, using a new profile fixes it. Thanks a lot for the quick help with this!

When I last used AMF that must have been 4 years ago or so, on a completely different computer even. But since I am lazy I always just copied the profiles over.

I changed the title to reflect that this was in fact the cause of the problem.

**Comment by YorVeX** [comment]
Note for others running into this: if you don't want to recreate all your profiles like me you can simply edit \config\obs-studio\basic\profiles\your_profile_name\basic.ini with a text editor and in the [AdvOut] section delete the lines that say "Encoder=amd_amf_h264" and "RecEncoder=amd_amf_h264" (or whatever other invalid encoder you might have set there).

This has worked for me to fix this issue and still keep the other profile settings, No guarantees that it will work for anyone else, create backups of your profile files before you do this if you want to be on the safe side.

**Comment by offthegrid-mike** [comment]
I can help fix this issue.
What properties should we expected to show in this case?(when there is an encoder which is not found)

**Comment by YorVeX** [comment]
I don't know whether the question is directed at me or the main contributors of this project, but IMHO you should keep the behavior consistent with the rest of the UI. For example if an audio device is configured that went missing it looks like this:
![image](https://user-images.githubusercontent.com/528974/100801305-16c0c380-3428-11eb-93e6-7995a73e68e4.png)

So it should be similar if an encoder is configured that went missing.

**Comment by Mahas1234** [comment]
Are there any more fixes needed. I'm looking for first contribution.
Thank you!

**Comment by Fenrirthviti** [comment]
Closing as stale. If this is still an issue please open a new issue with updated reproduction steps on the latest version of OBS.
