### ISSUE TITLE
OBS generating corrupt SRT packets - causing video playback glitches

### ISSUE THREAD

**Issue by thekingofjibs** [obsproject/obs-studio#3535]
## Platform

Operating system and version: Windows 10 1903
OBS Studio version: 26.0

## Expected Behavior

SRT streaming to SRT-Live-Server and playing back with FFplay should playback smoothly without distortion or console errors in FFplay.

## Current Behavior

SRT streaming to SRT-Live-Server and playing back with FFplay there are frequent, large glitches across the playback window and the following errors are logged to the console in FFplay:

[h264 @ 00000235891bc940] non-existing PPS 0 referenced  0B f=0/0
    Last message repeated 1 times
[h264 @ 00000235891bc940] decode_slice_header error
[h264 @ 00000235891bc940] no frame!
[h264 @ 00000235891bc940] non-existing PPS 0 referenced  0B f=0/0
    Last message repeated 1 times
[h264 @ 00000235891bc940] decode_slice_header error
[h264 @ 00000235891bc940] no frame!
[h264 @ 00000235891bc940] non-existing PPS 0 referenced  0B f=0/0
    Last message repeated 1 times
[h264 @ 00000235891bc940] decode_slice_header error
[h264 @ 00000235891bc940] no frame!
[h264 @ 00000235891bc940] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 00000235891bc940] decode_slice_header error
[h264 @ 00000235891bc940] no frame!
[h264 @ 00000235891bc940] non-existing PPS 0 referenced  0B f=0/0
    Last message repeated 1 times
[h264 @ 00000235891bc940] decode_slice_header error
[h264 @ 00000235891bc940] no frame!
[h264 @ 00000235891bc940] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 00000235891bc940] decode_slice_header error
[h264 @ 00000235891bc940] no frame!
[h264 @ 00000235891bc940] non-existing PPS 0 referenced  0B f=0/0
    Last message repeated 1 times
[h264 @ 00000235891bc940] decode_slice_header error
[h264 @ 00000235891bc940] no frame!
[h264 @ 00000235891bc940] non-existing PPS 0 referenced  0B f=0/0
    Last message repeated 1 times
[h264 @ 00000235891bc940] decode_slice_header error
[h264 @ 00000235891bc940] no frame!
[h264 @ 00000235891bc940] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 00000235891bc940] decode_slice_header error
[h264 @ 00000235891bc940] no frame!
[h264 @ 00000235891bc940] non-existing PPS 0 referenced  0B f=0/0
[h264 @ 00000235891bc940] non-existing PPS 0 referenced  0B f=0/0
[h264 @ 00000235891bc940] decode_slice_header error
[h264 @ 00000235891bc940] no frame!
[h264 @ 00000235891bc940] non-existing PPS 0 referenced  0B f=0/0
    Last message repeated 1 times
[h264 @ 00000235891bc940] decode_slice_header error
[h264 @ 00000235891bc940] no frame!
[h264 @ 00000235891bc940] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 00000235891bc940] decode_slice_header error
[h264 @ 00000235891bc940] no frame!
[h264 @ 00000235891bc940] non-existing PPS 0 referenced  0B f=0/0
    Last message repeated 1 times
[h264 @ 00000235891bc940] decode_slice_header error
[h264 @ 00000235891bc940] no frame!
[h264 @ 00000235891bc940] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 00000235891bc940] decode_slice_header error
[h264 @ 00000235891bc940] no frame!
[h264 @ 00000235891bc940] non-existing PPS 0 referenced  0B f=0/0
    Last message repeated 1 times
[h264 @ 00000235891bc940] decode_slice_header error
[h264 @ 00000235891bc940] no frame!
[mpegts @ 0000023581f3b440] Packet corrupt (stream = 0, dts = NOPTS).
[mpegts @ 0000023581f3b440] Packet corrupt (stream = 0, dts = NOPTS).
[h264 @ 00000235891bc940] concealing 4525 DC, 4525 AC, 4525 MV errors in I frame
[mpegts @ 0000023581f3b440] Packet corrupt (stream = 0, dts = NOPTS).
[mpegts @ 0000023581f3b440] Packet corrupt (stream = 0, dts = NOPTS).
[mpegts @ 0000023581f3b440] Packet corrupt (stream = 0, dts = NOPTS).
[mpegts @ 0000023581f3b440] Packet corrupt (stream = 0, dts = NOPTS).
[mpegts @ 0000023581f3b440] Packet corrupt (stream = 0, dts = NOPTS).
[mpegts @ 0000023581f3b440] Packet corrupt (stream = 0, dts = NOPTS).
[mpegts @ 0000023581f3b440] Packet corrupt (stream = 0, dts = NOPTS).
[mpegts @ 0000023581f3b440] Packet corrupt (stream = 0, dts = NOPTS).

The server and sending computer have been tested with the following FFmpeg command:

`ffmpeg -f lavfi -re -i testsrc=size=1920x1080:rate=25 -c:v libx264 -tune zerolatency -g 1 -b:v 20M -minrate 10M -maxrate 20M -bufsize 10M -c:a aac -ac 2 -strict -2 -y -bsf:v h264_mp4toannexb -f mpegts "srt://_REDACTED-ADDRESS_:1935?streamid=input/live/a&pkt_size=1316"`

With this command, playback was as expected with no errors; so I'm not sure this is a networking, encoding computer or a server not being compliant issue.

As a final check, I attempted to replicate this FFmpeg command in the OBS Record custom output section and ended up with the same errors as before when decoding.

Obviously, I'm using other software here...but I think this is an OBS issue just because FFmpeg worked perfectly (I might be entirely wrong though!)

OBS Log File:

17:13:34.521: CPU Name: Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
17:13:34.521: CPU Speed: 1992MHz
17:13:34.521: Physical Cores: 4, Logical Cores: 8
17:13:34.521: Physical Memory: 16225MB Total, 3762MB Free
17:13:34.521: Windows Version: 10.0 Build 18362 (release: 1903; revision: 1082; 64-bit)
17:13:34.521: Running as administrator: false
17:13:34.521: Aero is Enabled (Aero is always on for windows 8 and above)
17:13:34.522: Windows 10 Gaming Features:
17:13:34.522: 	Game DVR: On
17:13:34.525: Sec. Software Status:
17:13:34.530: 	Windows Defender Antivirus: disabled (AV)
17:13:34.530: 	Avast Antivirus: enabled (AV)
17:13:34.530: 	Windows Firewall: enabled (FW)
17:13:34.531: Current Date/Time: 2020-10-01, 17:13:34
17:13:34.531: Browser Hardware Acceleration: true
17:13:34.531: Portable mode: false
17:13:35.027: OBS 26.0.0 (64-bit, windows)
17:13:35.027: ---------------------------------
17:13:35.028: ---------------------------------
17:13:35.028: audio settings reset:
17:13:35.028: 	samples per sec: 48000
17:13:35.028: 	speakers:        2
17:13:35.030: ---------------------------------
17:13:35.030: Initializing D3D11...
17:13:35.030: Available Video Adapters: 
17:13:35.044: 	Adapter 0: NVIDIA GeForce MX150
17:13:35.044: 	  Dedicated VRAM: 2080038912
17:13:35.044: 	  Shared VRAM:    4212000768
17:13:35.044: 	  PCI ID:         10de:1d10
17:13:35.045: 	  Driver Version: 27.21.14.5638
17:13:35.045: 	  output 0: pos={0, 0}, size={3840, 2160}, attached=true, refresh=59, name=DELL P2715Q
17:13:35.045: 	Adapter 1: Intel(R) UHD Graphics 620
17:13:35.045: 	  Dedicated VRAM: 134217728
17:13:35.045: 	  Shared VRAM:    4212000768
17:13:35.045: 	  PCI ID:         8086:5917
17:13:35.046: 	  Driver Version: 22.20.16.4836
17:13:35.059: Loading up D3D11 on adapter NVIDIA GeForce MX150 (0)
17:13:35.117: D3D11 loaded successfully, feature level used: b000
17:13:35.117: DXGI increase maximum frame latency success
17:13:35.117: D3D11 GPU priority setup failed (not admin?)
17:13:35.585: ---------------------------------
17:13:35.585: video settings reset:
17:13:35.585: 	base resolution:   1920x1080
17:13:35.585: 	output resolution: 1920x1080
17:13:35.585: 	downscale filter:  Bicubic
17:13:35.585: 	fps:               25/1
17:13:35.585: 	format:            NV12
17:13:35.585: 	YUV mode:          709/Partial
17:13:35.585: NV12 texture support enabled
17:13:35.587: Audio monitoring device:
17:13:35.587: 	name: Default
17:13:35.587: 	id: default
17:13:35.587: ---------------------------------
17:13:35.607: [CoreAudio encoder]: Adding CoreAudio AAC encoder
17:13:35.611: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
17:13:35.694: [AMF] Unable to load 'amfrt64.dll', error code 126.
17:13:35.698: [AMF] AMF Test failed due to one or more errors.
17:13:35.698: Failed to initialize module 'enc-amf.dll'
17:13:35.729: [obs-browser]: Version 2.8.7
17:13:35.736: Failed to load 'en-GB' text for module: 'obs-ndi.dll'
17:13:35.736: [obs-ndi] hello ! (version 4.5.3)
17:13:35.736: [obs-ndi] Trying 'C:\Program Files\NewTek\NDI 4 Tools\Runtime'
17:13:35.736: [obs-ndi] Found NDI library at 'C:/Program Files/NewTek/NDI 4 Tools/Runtime/Processing.NDI.Lib.x64.dll'
17:13:35.740: [obs-ndi] NDI runtime loaded successfully
17:13:35.751: [obs-ndi] NDI library initialized successfully
17:13:35.799: Failed to load 'en-GB' text for module: 'obs-websocket.dll'
17:13:35.799: [obs-websocket] you can haz websockets (version 4.5.0)
17:13:35.799: [obs-websocket] qt version (compile-time): 5.10.1 ; qt version (run-time): 5.10.1
17:13:35.807: [obs-websocket] server started successfully on TCP port 4444
17:13:35.808: [obs-websocket] module loaded!
17:13:35.816: VLC found, VLC video source enabled
17:13:35.830: Decklink API Compiled version 10.11.4
17:13:35.830: Decklink API Installed version 10.11.4
17:13:35.847: ---------------------------------
17:13:35.847:   Loaded Modules:
17:13:35.847:     win-wasapi.dll
17:13:35.847:     win-mf.dll
17:13:35.847:     win-dshow.dll
17:13:35.847:     win-decklink.dll
17:13:35.847:     win-capture.dll
17:13:35.847:     vlc-video.dll
17:13:35.847:     text-freetype2.dll
17:13:35.847:     rtmp-services.dll
17:13:35.847:     obs-x264.dll
17:13:35.847:     obs-websocket.dll
17:13:35.847:     obs-vst.dll
17:13:35.847:     obs-transitions.dll
17:13:35.847:     obs-text.dll
17:13:35.848:     obs-qsv11.dll
17:13:35.848:     obs-outputs.dll
17:13:35.848:     obs-ndi.dll
17:13:35.848:     obs-filters.dll
17:13:35.848:     obs-ffmpeg.dll
17:13:35.848:     obs-browser.dll
17:13:35.848:     image-source.dll
17:13:35.848:     frontend-tools.dll
17:13:35.848:     enc-amf.dll
17:13:35.848:     decklink-ouput-ui.dll
17:13:35.848:     coreaudio-encoder.dll
17:13:35.848: ---------------------------------
17:13:35.848: ==== Startup complete ===============================================
17:13:35.862: All scene data cleared
17:13:35.862: ------------------------------------------------
17:13:36.915: WASAPI: Device 'Speaker/Headphone (Realtek High Definition Audio(SST))' [48000 Hz] initialized
17:13:36.915: [Loaded global audio device]: 'Desktop Audio'
17:13:36.963: WASAPI: Device 'VoiceMeeter VAIO3 Output (VB-Audio VoiceMeeter VAIO3)' [44100 Hz] initialized
17:13:36.963: [Loaded global audio device]: 'Mic/Aux'
17:13:36.999: adding 42 milliseconds of audio buffering, total audio buffering is now 42 milliseconds (source: Mic/Aux)
17:13:36.999: 
17:13:37.003: [obs-ndi] started A/V threads for source 'AURA-LAPTOP (1)'
17:13:37.004: [obs-ndi] A/V thread for 'NDI™ Source' started
17:13:37.097: Switched to scene 'clock'
17:13:37.098: ------------------------------------------------
17:13:37.098: Loaded scenes:
17:13:37.098: - scene 'Scene':
17:13:37.098:     - source: 'Color Source' (color_source)
17:13:37.098: - scene 'Scene 2':
17:13:37.098:     - source: 'NDI™ Source' (ndi_source)
17:13:37.098: - scene 'browser':
17:13:37.098:     - source: 'Browser' (browser_source)
17:13:37.098:         - monitoring: monitor only
17:13:37.098: - scene 'clock':
17:13:37.098:     - source: 'Browser 2' (browser_source)
17:13:37.098:         - monitoring: monitor only
17:13:37.098: - scene 'Scene 3':
17:13:37.098:     - source: 'Blackmagic Device' (decklink-input)
17:13:37.098: - scene 'srt':
17:13:37.098: - scene 'Scene 4':
17:13:37.098: ------------------------------------------------
17:15:21.561: >>> app not on intel GPU, fall back to old qsv encoder
17:15:21.561: [qsv encoder: 'streaming_h264'] settings:
17:15:21.561: 	rate_control:   CBR
17:15:21.561: 	target_bitrate: 10000
17:15:21.561: 	fps_num:        25
17:15:21.561: 	fps_den:        1
17:15:21.561: 	width:          1920
17:15:21.561: 	height:         1080
17:15:21.561: [qsv encoder: 'streaming_h264'] debug info:
17:15:21.577: 	impl:           D3D11
17:15:21.577: 	surf:           D3D11
17:15:21.646: 	m_nSurfNum:     9
17:15:21.649: 	m_nTaskPool:    4
17:15:21.649: 	major:          1
17:15:21.649: 	minor:          25
17:15:21.651: [CoreAudio AAC: 'avc_aac_stream']: settings:
17:15:21.651: 	mode:          AAC
17:15:21.651: 	bitrate:       320
17:15:21.651: 	sample rate:   48000
17:15:21.651: 	cbr:           on
17:15:21.651: 	output buffer: 1536
17:15:21.659: ==== Streaming Start ===============================================
17:15:21.659: [ffmpeg muxer: 'adv_stream'] Writing file 'srt://_REDACTED-ADDRESS_:1935?streamid=input/live/a&pkt_size=1316'...
17:16:44.796: [ffmpeg muxer: 'adv_stream'] Output of file 'srt://_REDACTED-ADDRESS_:1935?streamid=input/live/a&pkt_size=1316' stopped
17:16:44.796: Output 'adv_stream': stopping
17:16:44.796: Output 'adv_stream': Total frames output: 2071
17:16:44.796: Output 'adv_stream': Total drawn frames: 2079
17:16:44.799: ==== Streaming Stop ================================================

## Steps to Reproduce

1. Run SRT-Live-Server in Docker (ravenium/srt-live-server)
2. Set OBS to stream to "srt://_REDACTED-ADDRESS_:1935?streamid=input/live/a&pkt_size=1316"
3. Set streaming settings to H264 (Quicksync or libx264 have the same outcome), CBR 10M
4. Start streaming
5. Excecute `ffplay "srt://_REDACTED-ADDRESS_:1935?streamid=output/live/a"`

**Comment by pkviet** [comment]
Try one of these builds:
https://github.com/obsproject/obs-studio/actions/runs/220574056
I have a PR addressing these kind of issues. It might help.

**Comment by thekingofjibs** [comment]
Just tried the Windows 64-bit build and sadly still have the same issues

**Comment by thekingofjibs** [comment]
appears to be resolved with 26.0.2
