### ISSUE TITLE
Incompatible with 240Hz 240fps livestreaming without recompile

### ISSUE THREAD

**Issue by mdrejhon** [obsproject/obs-studio#3538]
## Platform
Windows 10
Intel i7 7740-X
GeForce RTX 2080 Ti
ViewSonic XG270 240Hz monitor
ASUS VG259QN 360Hz monitor (ASUS sent it to me)
Operating system and version: Windows 10
OBS Studio version: Latest

## Expected Behavior
Ability to do frame rates above 120 frames per second screen recording

## Current Behavior
OBS can only create video files up to 120fps

## Steps to Reproduce
1. Try to record on a 240Hz monitor at 240fps
2. OBS only lets you record up to 120fps 

## Additional information
There is a hardcoded "120" at this github file:
https://github.com/obsproject/obs-studio/blob/f9d664302e6943e2bd2c19b4b6e370aecc8ca276/UI/forms/OBSBasicSettings.ui

This is considered a magic number and bad programming practice (Who needs more than 640 kilobytes? ;) ).  It should be a user-editable limitation, not requiring a recompile.   

Someone successfully recompiled OBS with a one-line edit to screen record over 2000 frames per second at 360p, for a **debug-analysis of a high-Hz gaming mouse**: https://forums.blurbusters.com/viewtopic.php?f=10&t=7569&start=10#p57843 

P.S. Files above 120fps are classified as "[Ultra HFR](https://blurbusters.com/ultrahfr)"

**Comment by WizardCM** [comment]
If you need something higher than 120fps, you can use Fractional FPS and set it to 240 / 1 for example.

This is less about programming practices and more about providing less ways for users to hurt themselves.

**Comment by VodBox** [comment]
If you want to set OBS to use ultra high framerates, then you can set OBS to any arbitrary framerate using Fractional FPS Values (for instance, 240 numerator, 1 denominator), however we do not provide support for this and cannot guarantee stable performance at that point.

**Comment by kkartaltepe** [comment]
Not a bug.
