### ISSUE TITLE
AHK script can't run obs 26.

### ISSUE THREAD

**Issue by iesvme** [obsproject/obs-studio#3540]
## Platform

Operating system and version: win10 1809_x64
OBS Studio version: 26.0

## Steps to Reproduce

1. AHK script "run "C:\Program Files\obs-studio\bin\64bit\obs64.exe"" will be error.
![image](https://user-images.githubusercontent.com/16969250/94894638-57e63700-04bc-11eb-8213-56de52733e18.png)

**Comment by WizardCM** [comment]
Set your working directory to the OBS directory first. This is by design.

**Comment by iesvme** [comment]
Thank you very much!!!
