### ISSUE TITLE
MacOS Regression OBS 26.0 Number of lagged frames due to rendering lag/stalls much higher than 25.0.8

### ISSUE THREAD

**Issue by snicolai-blog** [obsproject/obs-studio#3543]
2015 MacBook Air with Mojave on it, connected to gigabit ethernet, on laptop cooler so it doesn't throttle for heat.  It does NOT have the most recent Mojave update on it (the one that Apple pulled recently).

El Gato USB capture stick (not 4K) grabbing 1280x720 30 fps from HDMI output of camera (audio from this video source only)

Two incoming NDI video only streams, one via ethernet, one from an iPhone via a created WiFi network (5GHz channel 44)  iPhone NDI app set to middle quality.

Output set to the VT encoder 1280x720 30fps  Also saving the same encoding to local SSD as an mkv file.

Safari is open to the YouTube stream health page during both tests, but the Safari window is behind OBS most of the time.

With OBS 25.0.8 this gives about 38-40% CPU and about 2.3% lagged frames.  See Sept 27 log enclosed
With OBS 26.0.0 the CPU % is about the same, but the lagged frames jumps to 24%  See Oct 1 log enclosed

Converting the mkv recording files to MP4 and looking at them with InvisioLight shows both at 30fps, so I don't think stream viewers see a degraded experience with 26.0.0, but the streaming operator does.

Expected behavior is that 26.0.0 is not substantially slower rendering than 25.0.8.

The dropped frames in the 25.0.8 log file occurred in the first few seconds after streaming was started, before going live in YouTube.  That seems to be a mostly regular occurrence with 25.0.8.  I don't have enough experience with 26.0.0 to say if the behavior is the same or different.

Willing to try test builds at Thursday night practices on this machine.

[2020-09-27 08-25-10.txt](https://github.com/obsproject/obs-studio/files/5318898/2020-09-27.08-25-10.txt)
[2020-10-01 18-38-24.txt](https://github.com/obsproject/obs-studio/files/5318899/2020-10-01.18-38-24.txt)

**Comment by kkartaltepe** [comment]
This should probably be moved to discussion in #2841 there is also a test build to try out there.

**Comment by snicolai-blog** [comment]
I'm fairly sure it's not the same initial problem, as OBS 24.0.x was unusable on this MacBook Air, dropping frames consistently.  I had to use a 2014 MacBook Pro.  Once 25.0.[6?] came out, OBS performance improved enough on that MacBook Pro that I tried going back to the MacBook Air and OBS 25.0.8 worked enough to be usable. 

If #2841 has migrated to be all the MacOS performance problems, then we can add this to the list.

**Comment by kkartaltepe** [comment]
consider trying this nightly build https://github.com/obsproject/obs-studio/actions/runs/285971879 and let us know if it is resolved.

**Comment by snicolai-blog** [comment]
That build improved things back to 25.0.8 levels of performance (or maybe slightly better) on the MacBook Air.

[2020-10-04 09-06-07.txt](https://github.com/obsproject/obs-studio/files/5324521/2020-10-04.09-06-07.txt)

**Comment by kkartaltepe** [comment]
That change will be in the next hotfix release. Closing this out then.
