### ISSUE TITLE
Virtual Camera does not work with Tencent QQ

### ISSUE THREAD

**Issue by ZeroAurora** [obsproject/obs-studio#3545]
## Platform

Operating system and version: Windows 10 1909
OBS Studio version: 26.0

## Expected Behavior
When video chatting in Tencent QQ, OBS Virtual Camera should work.

## Current Behavior

Tencent QQ crashed, while OBS remains working.
Logs (modified to remove personal info):
QQ logs: [QQ106d49b.txt](https://github.com/obsproject/obs-studio/files/5321239/QQ106d49b.txt)
OBS logs: https://obsproject.com/logs/MXsSRyczB9zn0Slb

## Steps to Reproduce

1. Download Tencent QQ (if not installed). But QQ may be usable only in China.
2. Select OBS Virtual Camera in QQ's setting (and it crashed, for the first time).
3. Start a video chat in QQ
4. Crashed.

## Additional information

May be related to #3453

**Comment by WizardCM** [comment]
Thank you for including the crash log from QQ. I don't yet know if that will be helpful enough, though the crash does seem to be in the virtual camera module.

Have you reached out to Tencent to see if they'd have a better idea why it would cause their app to crash? My best guess is that both OBS and QQ will need a fix, but any insight into _what_ needs fixing would be invaluable.

**Comment by ZeroAurora** [comment]
Not yet. QQ allows me to upload the log file but I don't know will it help. I may have a try to reach the developers. Anyway, thank you for replying and I look forward to further fixes.

**Comment by ZeroAurora** [comment]
I've posted this issue's link to the feedback fourm of QQ. Hope that will help.

**Comment by WizardCM** [comment]
Adding to the list: apparently lecture capture software Panopto crashes when the OBS camera is selected. [Source](https://obsproject.com/forum/threads/new-virtualcam-makes-panopto-crash.131641/).

**Comment by RytoEX** [comment]
Could you please test in OBS Studio 28.0.3 or newer? Alternatively, could you please test https://github.com/obsproject/obs-studio/issues/7529#issuecomment-1276494786.

If it is still an issue, please post new a QQ crash log.

**Comment by ZeroAurora** [comment]
I haven't tested it for long but my friends told me that it's working, so I'm  going to close the issue for now. I will open it again if I find any problems.
