### ISSUE TITLE
Virtual camera output is mirrored horizontally

### ISSUE THREAD

**Issue by peterk** [obsproject/obs-studio#3546]
## Platform

Operating system and version: Windows 10 Home v2004
OBS Studio version: 26.0.0

## Expected Behavior
Output from OBS Studio virtual camera should look the same in the preview of the application using the feed (e.g. Microsoft Teams or Skype)

## Current Behavior
Starting the virtual camera in OBS. Selecting the virtual camera in my other application (tested with Microsoft Teams, Skype and browser) shows a horizontally mirrored image.

## Steps to Reproduce

1. Set up a scene in OBS that shares a window from a text application.
2. Start the virtual camera.
3. Open other application (e.g. Teams) and check OBS virtual camera source in settings.

## Additional information
OBS setup:
![image](https://user-images.githubusercontent.com/19284/94986263-9ed83900-055d-11eb-9d51-3513ea84feec.png)

Microsoft Teams camera preview
![image](https://user-images.githubusercontent.com/19284/94986278-ba434400-055d-11eb-944a-65635974c3d2.png)

**Comment by derrod** [comment]
it's not, that's just the preview in Teams. Most conferecing application mirror it for webcams.

**Comment by WizardCM** [comment]
The view you see in your application is flipped for you only. This is because most applications expect a webcam, and they want to mimic looking in a mirror for your own preview. Everyone else sees what you see in the OBS preview.

**Comment by peterk** [comment]
Thx! Ah sorry! That was confusing.
