### ISSUE TITLE
alsa-input: Doesnt work with cards missing s16 format support

### ISSUE THREAD

**Issue by lockie** [obsproject/obs-studio#3547]
## Platform

Operating system and version: Gentoo Linux desktop 17.1
OBS Studio version: 25.0.8

## Expected Behavior
Getting some audio input from USB audio card with _ALSA Auido Capture Device_ source.

## Current Behavior
There's no sound from the mic in OBS (the indicator in "Audio Mixer" is not moving), although I can record sound from that card and mic in different applications (e.g. Audacity). There's the line
```
error: alsa-input: snd_pcm_hw_params_set_format failed: Invalid argument
```
constantly written by OBS in its log.

## Steps to Reproduce
1. Plug in external USB audio card (Behringer UMC202HD in my case).
2. Add _ALSA Auido Capture Device_ source targeting that card.

## Additional information
I've grepped OBS source for that error and found out that [the input format is hardcoded to be 16 bit](https://github.com/obsproject/obs-studio/blob/f4f2d383b1f234dc231ca0dc2804d8ba5c69635e/plugins/linux-alsa/alsa-input.c#L443), although the card does not seem to support 16 bit sample format:
```
$ arecord -f S16 -D hw:4,0
Recording WAVE 'stdin' : Signed 16 bit Little Endian, Rate 8000 Hz, Mono
arecord: set_params:1343: Sample format non available
Available formats:
- S32_LE
```

**Comment by kkartaltepe** [comment]
Please try #3548 and let me know if it fixes your issue.

**Comment by lockie** [comment]
This worked like a charm, thank you Kurt!
