### ISSUE TITLE
[Minor Bug] Windows 10 64 Bit OBS 26 Twitch Information

### ISSUE THREAD

**Issue by CanadianJeff** [obsproject/obs-studio#3552]
With Twitch linked to OBS when I go to play starcraft and set my streams game to starcraft it works fine but when I want to play league of legends and pick league from the category it will not switch away from starcraft

https://i.imgur.com/VcCHPh1.png

**Comment by Fenrirthviti** [comment]
Unable to replicate, but this panel is maintained by twitch, it's just a browser dock in OBS. You will need to report to Twitch.

Also, in the future, please make sure you take the time to read the issue template, rather than completely deleting it.

**Comment by CanadianJeff** [comment]
is there like a browser cache folder somewhere that I could empty or set back to default?
