### ISSUE TITLE
Virtual Camera can not be removed even when uninstalling OBS

### ISSUE THREAD

**Issue by flabbert** [obsproject/obs-studio#3554]
## Platform

Operating system and version: Windows 10 2004 64bit
OBS Studio version: 26

## Expected Behavior
There should be an option to remove the virtual camera device from the system. The virtual camera stays even if uninstalling obs

## Current Behavior
Virtual Camera device persists in windows regardless of uninstalling OBS. And there is no option to remove the camera inside obs.

## Steps to Reproduce

1. Install OBS
2. Accept Virtual Camera
3. Uninstall OBS
4. Virtual Camera persists in the camera list

**Comment by Scrxtchy** [comment]
Looks like it should be working
https://github.com/obsproject/obs-studio/blob/d4ce4061381d4bcefd6a7a188d8a17bc2381ed5b/UI/installer/mp-installer.nsi#L416-L420

I loaded up OBS 26 into a fresh windows sandbox to try and replicate
I noticed that these are indeed being executed in the uninstaller
![image](https://user-images.githubusercontent.com/12771982/95067323-6435f280-074f-11eb-8a34-d3ac1db2fde0.png)

Refreshing the webpage I was using to test the webcam still displayed the device, but after restarting Edge the device was no longer detected. In addition to this, the term virtualcam did not return any results to OBS within a search of the registry (only references to the Mixed Reality dlls)

I cannot replicate this issue

**Comment by Gol-D-Ace** [comment]
Cannot replicate this as well.
I even had discord with the camera preview open and the camera instantly disappeared while uninstalling.

**Comment by Scrxtchy** [comment]
It's hard to say if the OP has the plugin version of the virtualcamera installed on the system, which has it's own uninstaller. This has caught me out a couple times

**Comment by flabbert** [comment]
It was a brand new install of OBS, without the plugin version installed. And you are right, a restart of chrome removed the camera. However, there should still be a way to remove the camera without having to uninstall OBS.

**Comment by WizardCM** [comment]
You can find an unregistration batch file in that win-dshow folder.

Closing as this issue is specifically for browsers not refreshing their list of cameras automatically.
