### ISSUE TITLE
OBS 25 => 26 upgrade looses hotkey support via external software

### ISSUE THREAD

**Issue by JeffreyDavidsz** [obsproject/obs-studio#3556]
Multiple users report that when upgraded to 26, VICREO listener does not work anymore. I would like to help restoring that. But you might already know a solution for it (I personally don't use OBS)

**Comment by WizardCM** [comment]
Please fill in the issue template, including reproduction steps.

**Comment by Fenrirthviti** [comment]
No actionable information, template deleted, closing.
