### ISSUE TITLE
Multiple desktops support

### ISSUE THREAD

**Issue by Janaue** [obsproject/obs-studio#3557]
Hi

I have OBS 26 on windows 10 1809, up to date. I use the feature Multiple desktops by w10 and and I record with OBS.
In OBS I choose ''display capture'' but the recording does not care about which desktop is ON, ie if OBS is set to record desktop_1, and I switch between desktops_1->Desktop_2, then OBS records the transition between the two desktops, instead of sticking to desktop_1.

In fact, I have  various Displays, and I have various Desktops.
I want to have Display_1, Display_2,  desktop_1(going across all displays) and desktop_2(going across all displays), I set up my software and OBS on desktop_2 (going across all displays) and I want OBS only to record  the software placed on the pair [**_Desktop_2_**, Display_2]. As I said , when I change desktops, OBS record [**_Desktop_1_**, Display_2].

How do I force OBS to stick to a particular pair of [Desktop, Display] ?

**Comment by WizardCM** [comment]
This is not a bug, but a limitation of Windows 10 capture APIs. You can try submitting it [here](https://ideas.obsproject.com/), but I don't think there's a way for us to work around it.
