### ISSUE TITLE
OBS Will not select proper Pulseaudio output stream

### ISSUE THREAD

**Issue by sparkie3** [obsproject/obs-studio#3559]
## Platform

Operating system and version: Kubuntu 20.04
OBS Studio version: 26.00

## Expected Behavior

When selecting a built-in audio stream, or the default audio device for capture, OBS should capture that audio stream and record along with video.

## Current Behavior

OBS will only capture the microphone stream, despite the built-in audio speakers being the only device present on the system.

## Steps to Reproduce

1. Install OBS package
2. Set the "Desktop Audio" setting to "speakers"
3. Try to record video with speaker output for audio

https://i.imgur.com/Dm91aVz.png
https://i.imgur.com/iHwmSnl.png
https://i.imgur.com/sLimqkS.png
https://obsproject.com/tools/analyzer?log_url=https%3A%2F%2Fobsproject.com%2Flogs%2F1azWE97gabzv_uig

## Additional information

I am not sure why, but no matter what I set OBS audio capture to, it wants to use the microphone. I managed to get it to record audio a couple times, but it is far from consistent. Even when I don't change my audio settings, I have to juggle them around and it is sheer luck if I can get OBS to record audio. This is with all audio devices removed from my system but my speakers.

**Comment by kkartaltepe** [comment]
It looks like it is recording from your log.
Started recording from 'alsa_output.pci-0000_00_1b.0.analog-stereo.monitor'

And the devices were created as you show. Please come to the support channel in discord or our forums for configuration issues.

**Comment by sparkie3** [comment]
The reason I don't believe this to be a bug rather than a configuration issue is that the stream recorded is for the microphone if one is plugged in, and not not the selected device, despite setting the audio device in the configuration settings. Essentially, OBS wants to use the microphone rather than the configured audio device. Despite being set to analog-stereo, OBS uses the a microphone.
