### ISSUE TITLE
Window Capture Blank Screen with Bugged Cursor, continuation of #3469

### ISSUE THREAD

**Issue by weeblr-dev** [obsproject/obs-studio#3560]
I experience the exact same problem described in #3469. That report was for OBS 26 RC, mine is with the current stable OBS 26. When capturing a window (with Windows Graphics Capture):

- if the captured window has focus, then the capture becomes an entirely black screen, sometimes with multiple images of the mouse randomly displayed on top of it

- as soon as either OBS or any other window than the captured one has focus, capture comes back to normal.

Compared to the previous report, I can add that this issue goes away if **Capture cursor** is disabled. I cannot work without capturing cursor so that's not a real workaround for me.

In addition, **I have installed back OBS 25 in another folder and it does not have this problem.**

## Platform

Operating system and version: Win 10 Pro X64 fully updated.
OBS Studio version: 26.0.0 64 bit

## Expected Behavior

Window capture should work regardless of which window has focus.

## Current Behavior

Capture is a black screen if the captured window has focus **and** "Capture cursor" is selected.

## Steps to Reproduce

1. Add a Window Capture source to a scene, make sure Capture cursor is selected
2. Click on the window to give it focus
3.Preview/capture becomes a full black screen with random cursor images

![image](https://user-images.githubusercontent.com/7250379/95089491-7e0e1000-0724-11eb-8c9d-4ae1f9548c8b.png)

## Additional information

My system has 3 nvidia GPU, 2 x GT 730 and 1 x GTX 1050TI, so this is all nvidia (all drivers fully updated), just like the other reporter in #3469

**Comment by RytoEX** [comment]
I suspect that this is fixed by #3550, which will be released as part of OBS Studio 26.0.1 relatively soon.  Please feel free to test a recent nightly build.

**Comment by weeblr-dev** [comment]
Hi

>Black screens when OBS and target window were driven by separate GPUs.

yes, that would be my case indeed.

Not sure where to get nightly builds. As you're using Github actions, I downloaded one fo the artifacts in the most recent commit to master (this one: https://github.com/obsproject/obs-studio/actions/runs/289218286). Is this correct?

That build indeed fixes the problem. Oddly, it does not have the "Start VirtualCam" button?

**Comment by RytoEX** [comment]
> 
> 
> Hi
> 
> > Black screens when OBS and target window were driven by separate GPUs.
> 
> yes, that would be my case indeed.
> 
> Not sure where to get nightly builds. As you're using Github actions, I downloaded one fo the artifacts in the most recent commit to master (this one: https://github.com/obsproject/obs-studio/actions/runs/289218286). Is this correct?
> 
> That build indeed fixes the problem. Oddly, it does not have the "Start VirtualCam" button?

Yes, that's the correct build.  Glad to hear it fixed the issue.  Yes, it's expected at this time that "Start VirtualCam" is missing for nightly builds by default.

**Comment by weeblr-dev** [comment]
Hi

Anyway to bring it back? or do I have to wait until 26.0.1 is released to have both VirtualCam and black screen fixed?
Going to try installing the Virtual Cam plugin anyway...

**Comment by RytoEX** [comment]
> 
> 
> Hi
> 
> Anyway to bring it back? or do I have to wait until 26.0.1 is released to have both VirtualCam and black screen fixed?
> Going to try installing the Virtual Cam plugin anyway...

For now, not easily.  The nightly builds do not include the install script at the moment.  We'll fix it in due time.

Please note that the third-party virtual camera plugin is not the same as the built-in virtual camera feature in OBS Studio 26.

**Comment by weeblr-dev** [comment]
The VC plugin don't seem to work but I may have misconfigured or have too many instances of OBS now. I'll give it another try and we'll wait for 26.0.1 most likely.

Thanks for the fix and assistance.
