### ISSUE TITLE
OBS Crashes on start. macOS Catalina

### ISSUE THREAD

**Issue by mal4i6ka** [obsproject/obs-studio#3563]
## Platform

Operating system and version: macOS Catalina 10.15.7 (19H2)
OBS Studio version: 26.0.0-e24aaa0b

## Expected Behavior

OBS App Starts
## Current Behavior

Crash dialog is displayed
## Steps to Reproduce

1. Run App

## Additional information

[Crash log on pastebin](https://pastebin.com/Y43WY8rV)

**Comment by Fenrirthviti** [comment]
This crash appears to be coming from the advanced scene switcher plugin, you'll need to report it to the developer of that plugin:

```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   advanced-scene-switcher.so    	0x00000000331d5d82 SwitcherData::saveGeneralSettings(obs_data*) + 818
1   advanced-scene-switcher.so    	0x000000003319d791 SaveSceneSwitcher(obs_data*, bool, void*) + 257
```

**Comment by mal4i6ka** [comment]
I don't really have it. My OBS App package -> Plugin's folder don't include `advanced-scene-switcher.so` but every time I lunch the app ~/Library/ApplicationSupport/obs-studio/plugin_config/advanced-scene-switcher/ empty folder will be generated. Maybe it was installed on my machine and after uninstalled incorrectly? Is there a way to find a trace of the leftovers of that plugin and remove them?

**Comment by PatTheMav** [comment]
Please check `/Library/Application Support/obs-studio` for `advanced-scene-switcher.so` - according to the crash log that's the loaded library that OBS calls to load/save its settings.

Unfortunately most macOS plugin installers still throw OBS plugins in there instead of the user's Application Support folder.

**Comment by mal4i6ka** [comment]
> Please check `/Library/Application Support/obs-studio` for `advanced-scene-switcher.so` - according to the crash log that's the loaded library that OBS calls to load/save its settings.
> 
> Unfortunately most macOS plugin installers still throw OBS plugins in there instead of the user's Application Support folder.

WOW I don't actually know that on macOS two /Library/ Folder one in the root of Mackintosh HD and another in users folder @PatTheMav thank you so much I'm literally thinking of that problem hole night! Thank you!

**Comment by PatTheMav** [comment]
There's three actually: `/Library/`, `/System/Library/` and `~/Library/` - the second one is off limits since Catalina and the first one requires annoying root access.

**Comment by mal4i6ka** [comment]
> There's three actually: `/Library/`, `/System/Library/` and `~/Library/` - the second one is off limits since Catalina and the first one requires annoying root access.

That information is very helpful, i mean its how the system works, and I was looking in the wrong place but now I understand it better. Thx to you.
