### ISSUE TITLE
[Linux] Cannot load url-text.py plugin

### ISSUE THREAD

**Issue by TRPB** [obsproject/obs-studio#3565]
## Platform

Operating system and version: Arch Linux
OBS Studio version:  OBS Studio - 25.0.8-2 (linux)

## Steps to Reproduce

1. Open the scripts dialog
2. Click add
3. Select url-text.py
4. Open the Script log

The following error comes up:

```
[url-text.py] Traceback (most recent call last):
[url-text.py]   File "/usr/share/obs/obs-plugins/frontend-tools/scripts/url-text.py", line 2, in <module>
[url-text.py]     import urllib.request
[url-text.py]   File "/usr/lib/python3.8/urllib/request.py", line 84, in <module>
[url-text.py]     import base64
[url-text.py]   File "/usr/lib/python3.8/base64.py", line 10, in <module>
[url-text.py]     import struct
[url-text.py]   File "/usr/lib/python3.8/struct.py", line 13, in <module>
[url-text.py]     from _struct import *
[url-text.py] ImportError: /usr/lib/python3.8/lib-dynload/_struct.cpython-38-x86_64-linux-gnu.so: undefined symbol: _PyFloat_Pack4
```

I believe the problem is OBS specific as if I just create a python script `test.py` with 

```
 import urllib.request
```

and run it from the command line `python test.py`, I don't get this error. It seems to be to do with the way OBS runs the python script. 

Unfortunately, googling "undefined symbol: _PyFloat_Pack4" doesn't give any meaningful results.

**Comment by Chiitoo** [comment]
I believe the particular script is not compatible with Python >=3.8, meaning it probably still works for you if you use 3.7 or lower?

I was meaning to look more into this several months ago already, but yeah...

**Comment by kkartaltepe** [comment]
Looks like a broken package. Remove it and build obs yourself, if it still occurs ask to reopen the ticket.

**Comment by TRPB** [comment]
Reported to Arch: https://bugs.archlinux.org/task/68132

They are saying it's an OBS issue, not a packaging issue. Is OBS incompatible with Python 3.8?

**Comment by kkartaltepe** [comment]
Replicated

**Comment by kkartaltepe** [comment]
Seems to be a fairly common issue with python modules compiled without dependencies on python for some odd reason. You can work around this by running obs in an environment that LD_PRELOAD's your python binary. Im not sure why python modules dont link against python, but that would be my recommendation to fix upstream.

**Comment by eli-schwartz** [comment]
Should be fixed by #3335

**Comment by kkartaltepe** [comment]
ah someone pinged on an old bug that refernces this already #2222 closing as dupe.

**Comment by eli-schwartz** [comment]
To better understand why this is an issue:

https://bugs.python.org/issue21536

Every importable module implemented in C, even the stdlib ones, no longer links to libpython but expects the interpreter to provide the needed global symbols on python >=3.8

obs-studio does not directly link to libpython, but uses dlopen, then marks it as non-global despite trying to embed a standard python interpreter. This then breaks everywhere.
