### ISSUE TITLE
Streamlabs Donation Ticker doesn't show

### ISSUE THREAD

**Issue by PoketVision22** [obsproject/obs-studio#3567]
Hi! I'm having troubles with Donation Ticker from Streamlabs, it won't show up while Bits Ticker has no problem. I tried everything, reinstalling, deleting caché, deleting CSS, I disabled Hardware Acceleration, no firewall/antivirus on

currently using OBS 26.0.2

thank you for any advise!

**Comment by notr1ch** [comment]
Please use the forums or discord for support.
