### ISSUE TITLE
OBS Doesn't Show My In-Built Video Capturing Device's Captured Video In The Latest Update.

### ISSUE THREAD

**Issue by DevTheGenius** [obsproject/obs-studio#3570]
## Platform

Operating system and version: Windows 10
OBS Studio version: OBS 26.0.2

## Expected Behavior
In this update, OBS should and does look like 26.0.0 but slightly better. But when I was recording with my webcam (Video Capturing device option) on it wasn't showing the video being captured from my webcam.

## Current Behavior
When I was recording with my webcam (Video Capturing device option) on it wasn't showing the video being captured from my webcam and would only allow the proper video capture of the OBS virtual camera which would show the window/game/display capture instead of my face.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by WizardCM** [comment]
Please fill in the reproduction steps.
