### ISSUE TITLE
Encoder error after upgrading to 26.0.2

### ISSUE THREAD

**Issue by chazsolo** [obsproject/obs-studio#3572]
After upgrading to 26.0.2 and attempting to record, a window appears with the message:

"An Encoder Error occurred while recording."

## Platform

Operating system and version: macOS Mojave 10.14.6
OBS Studio version: 26.0.2

## Expected Behavior

It should record the output as expected.

## Current Behavior

We looked into the logs and saw:

```
20:00:34.143: ==== Recording Start ===============================================
20:00:34.143: [ffmpeg muxer: 'adv_file_output'] Writing file '<redacted>/Movies/2020-10-07 20-00-34.mov'...
20:00:34.398: [ffmpeg muxer: 'adv_file_output'] os_process_pipe_write for packet data failed
20:00:34.398: [ffmpeg muxer: 'adv_file_output'] Output of file '<redacted>/Movies/2020-10-07 20-00-34.mov' stopped
20:00:34.398: Output 'adv_file_output': stopping
20:00:34.398: Output 'adv_file_output': Total frames output: 10
20:00:34.398: Output 'adv_file_output': Total drawn frames: 16
20:00:34.399: ==== Recording Stop ================================================
```

## Steps to Reproduce

1. Run OBS at v26.0.2
2. Click on "Start Recording"
3. Recording begins and then stops, showing a window with the above error.
4. A file is created but is less than a second long.

**Comment by kkartaltepe** [comment]
Please use the discord or the forums for support.

**Comment by eric** [comment]
Related: #3460

**Comment by kkartaltepe** [comment]
Did you bisect and reproduce the error? Do you have any reproduction steps? "related" isnt very useful.

**Comment by eric** [comment]
I wrote the code in question that changed the behavior from ignoring all errors in ffmpeg-mux to now look for and abort on an error. 

This failure being reported is likely an underlying issue, but the fact that it is now surfaced where before it was ignored was something that I thought would be helpful for anyone investigating this further.
