### ISSUE TITLE
Virtual camera bug in certain programs

### ISSUE THREAD

**Issue by PowerNao** [obsproject/obs-studio#3576]
## Platform

Operating system and version: Windows 10 64bit 2004
OBS Studio version: 26.0.2

## Expected Behavior
All programs in which virtual cameras are loaded require normal operation

## Current Behavior
In some broadcast programs such as Xsplit, when OBS virtual camera source is loaded as a device source, there is a problem that the screen cannot be updated after only one frame is loaded at the time of loading.

## Steps to Reproduce
1. Activate the OBS virtual camera.
2. In broadcast programs such as Xsplit, the OBS virtual camera source is loaded as the device source.
3. After the first frame is loaded normally, the screen is not updated in the loaded program no matter what operation is performed in OBS.
4. After that, pressing the "Start Virtual Camera" button does not respond until the program in which the virtual camera is loaded is closed.

## Additional information
AfreecaTV uses the freecshot program, RTMP transmission is not good, so it is forced to use it.
AfreecaTV mentioned that this bug should be fixed by OBS.
old VirtualCam plugin worked fine.

**Comment by WizardCM** [comment]
Hi there, could you confirm if this is fixed in [OBS 26.1.0 RC2](https://github.com/obsproject/obs-studio/releases/tag/26.1.0-rc2)? Thanks!

**Comment by PowerNao** [comment]
> Hi there, could you confirm if this is fixed in [OBS 26.1.0 RC2](https://github.com/obsproject/obs-studio/releases/tag/26.1.0-rc2)? Thanks!

Nope. Still having the same problem ;(

**Comment by WizardCM** [comment]
Understood, thanks for verifying. We'll re-explore the issue in 26.2.

**Comment by PowerNao** [comment]
Thank you! Virtualcam plugin works fine. Thanks to this, you can wait long enough.

**Comment by RytoEX** [comment]
Could you please test in OBS Studio 28.0.3 or newer? Could you also please test https://github.com/obsproject/obs-studio/issues/7529#issuecomment-1276494786?

**Comment by RytoEX** [comment]
XSplit v.4.5 (4.5.2311.2106) seems to work fine with the OBS Virtual Camera from OBS Studio 30.0.2.
