### ISSUE TITLE
Audio monitoring goes out of sync over time

### ISSUE THREAD

**Issue by TRPB** [obsproject/obs-studio#3577]
## Platform

Operating system and version: Arch Linux (Also happens on windows)
OBS Studio version: 24-26

## Expected Behavior

When monitoring the audio, the audio input should always be immediately sent to the monitoring device.

## Current Behavior

After some time, there is a delay in the monitor. 

This has been described by other users here: https://obsproject.com/forum/threads/audio-monitoring-delay.77056/

and here: 

https://obsproject.com/forum/threads/audio-monitoring-slowly-going-out-of-sync-over-time.119829/

So it happens (or at least used to happen) on Windows as well.

There's a similar issue  reported here: https://github.com/obsproject/obs-studio/issues/192 but not to do with the monitor.

## Steps to Reproduce

1. Set up monitoring on a device
2. Wait?
3. Monitor is out of sync after some time and delayed by several seconds from when the sound occurred. 

Periodically restarting OBS  fixes it, but it's not ideal.

## Additional information

The monitoring device doesn't seem to matter.  Originally I had thought this was a PulseAudio problem because I was monitoring to a virtual sink then outputting to a virtual microphone, but after setting the monitor to my headphones it happens there as well.

If I play other audio through the dummy sink (e.g. piping the microphone straight into the virtual sink) the audio is correct. The problem seems to be coming from OBS itself.

I realise this is quite a  difficult problem to fix as it is non-specific and the steps to reproduce are difficult. But would it be possible to write a script/plugin as a workaround that resets the monitor periodically? 

For now, I'll try to write a plugin that resets the monitor every time there is 0db (or some user selected threshold)  of audio being monitored but I've no idea where to start and it would be nice if this could be done by OBS.

**Comment by kkartaltepe** [comment]
#3525 this was already investigated. If you are trying to use a low latency buffers thats likely a cause.

**Comment by TRPB** [comment]
thanks, the suggestions there seem to have fixed it.
