### ISSUE TITLE
Standartized dafualt x264 bframes setting does not correspond to optimal value for b-adapt=1 algorithm

### ISSUE THREAD

**Issue by Anton-Latukha** [obsproject/obs-studio#3579]
This is essentially a copy of battle-tested fix submitted to PerrTube: https://github.com/Chocobozzz/PeerTube/pull/774

## Preface

For any x264 where `--b-adapt` is default or explicitly `1`, please see: http://www.chaneru.com/Roku/HLS/X264_Settings.htm#b-adapt

> 1. 'Fast' algorithm, faster, speed slightly increases with higher --b-frames setting. When using this mode, you basically always want to use --bframes 16.

Yes, you read right.

## Short history of B-adapt

In the invention of x264, B-frames were introduced.
x264 picked B-frames by the number in the B-frames option, and the pattern on I BBBB P BBBB ... frames.
Despite being primitive it was giving pretty good results, compared to MPEG2.
That is how x264 worked for a number of years.

For a long time, no one could invent an adaptive algorithm to pick B-frames.
In the end, it was invented.
```
commit 68c13530b5ffc28325aee408f4cd19ab7da06715 [revision 137]
Author: Loren Merritt <pengvado@videolan.org>
Date: Wed Feb 23 19:58:02 2005 +0000

Preliminary adaptive B-frame decision (not yet tuned).
Fix flushing of delayed frames when the encode finishes.
```
https://www.videohelp.com/software/x264-Encoder/version-history

And for a long time was in the experimental stage.
```
commit f89e0d06700620d4e2f1467e80995f8192182496 [revision 967]
Author: Fiona Glaser <fiona@x264.com>
Date: Tue Sep 9 23:51:17 2008 -0700

Fix crash when using b-adapt at resolutions 32x32 or below.
Original patch by BugMaster, but was mostly rewritten in order to make b-adapt actually *work* at such resolutions, not merely stop crashing.
```

During that time, `b-adapt 2` was invented.
Original thread: https://forum.doom9.org/showthread.php?t=139827
```
26th July 2008, 01:00 Dark Shikari x264 developer
The new B-frame decision (--bframes 16 and you)

---

One of the GSOC projects for the summer was to improve B-frame  decision. 
This was the most important project, IMO... but the student on the task just disappeared after the first week.

So I decided to do his job for him, and with akupenguin's assistance on  the algorithm side of things, spent this week writing an optimal  trellis-like function for B-frame decision.

This algorithm provides perfect B-frame decision--or more precisely, as perfect as one can get with the current cost approximation function used.
The downside is that its a bit slower, and moreover, its speed scales linearly with --bframes.

While with the previous algorithm, --bframes 16 was only minimally slower than --bframes 3, here it will be a lot  slower.

And this new algorithm is going to be default, since it is  considerably better.
The old algorithm will still be available for  those who need a fast but inaccurate B-frame decision method.
So, this is a warning to all those who use --bframes 16, MeGUI and otherwise; the new B-frame decision is coming soon, and when it does, in the interests of speed you may want to lower the --bframes value to 3-5 or something otherwise reasonable.
```

```
commit 95ed2720b7772199f04cc9a657632107bb1c548c [revision 969]
Author: Fiona Glaser <fiona@x264.com>
Date: Sun Sep 14 18:18:15 2008 -0700

Add optional more optimal B-frame decision method
This method (--b-adapt 2) uses a Viterbi algorithm somewhat similar to that used in trellis quantization.
Note that it is not fully optimized and is very slow with large --bframes values.
It also takes into account weightb, which should improve fade detection.
Additionally, changes were made to cache lowres intra results for each frame to avoid recalculating them. This should improve performance in both B-frame decision methods.
This can also be done for motion vectors, which will dramatically improve b-adapt 2 performance when it is complete.
This patch also reads b_adapt and scenecut settings from the first pass so that the x264 header information in the output file will have correct information (since frametype decision is only done on the first pass).
```

## Conclusion
You probably already see the pattern in messages.
The story is:
B-adapt 1 was created in heuristic way with skip-hacks and with a lot of polish on top. B-frames option does affect algorithm but not in the speed/complexity way. In fact in many cases  B-frames 16 runs a tiny bit faster while producing a better results. It was also my experience, but it was years ago.

B-adapt 2 does the proper by logic the path of analysis, so the bigger the chain of B-frames allowed - the more it's tree of analysis grows.

From then-on the improvements in B-adapt 2 and B-adapt 1 go toe to toe.
But heuristic/hacked B-adapt 1 turned-out very productive.

```
Date: Thu Jul 28 19:34:04 2016 +0200

Adjust --preset slow

* Swap --me umh for --trellis 2. They have a similar effect on performance
but the latter gives slightly better results in most cases.
* Change --b-adapt from 2 to 1. Negligible difference in quality since the
b-adapt 1 improvements, but it's significantly faster.
Also remove a redundant assignment from veryfast (--me hex is set by default).
```

Maybe I need to make new tests, but I am sure as dev-logs show the old parity.

## For reference:
1. Thread of creation of B-adapt 2: https://forum.doom9.org/showthread.php?t=139827
2. MEGUI Wiki:
2.a B-adapt: https://en.wikibooks.org/wiki/MeGUI/x264_Settings#b-adapt
2.b B-frames: https://en.wikibooks.org/wiki/MeGUI/x264_Settings#b-frames
3. Old x264 wiki page: http://www.chaneru.com/Roku/HLS/X264_Settings.htm#b-adapt
4. I submitted errata to: http://www.videorip.info/x264/78-polnoe-opisanie-vseh-kljuchej-kodirovanija-x264libx264 they had information on `b-adapt`/`b-frames`, in two places, one of them was right.
5. x264 commit logs: https://www.videohelp.com/software/x264-Encoder/version-history

**Comment by Anton-Latukha** [comment]
Also lets from the beginning distinguish the difference in ref frames option and B-frames.

Ref frames increase the complexity of interlinks in the frames (between frames) and so in the chain. Primarily it impacts complexity of P-frames, and in lesser extend B-frames. And so ref option impacts encoding/decoding complexity significantly.

Raising ref frames steeply increase the encoding computation requirements,

MPEG4 Levels refer to ref frames option. Because option raises a requirements to the decoding complexity (somewhat) and primarily frame buffer requirements - DPB (Decoded Picture Buffer). And H.264 decoding hardware has frame buffers implemented in hardware. And hardware buffer has it's physical size, so that is why they have strict requirement/support of Levels. If P-frame refers to the frames that does not got in the buffer - P-frame gets dropped/partly decoded, and so it impacts B-frames that rely to it.

That is about ref frames.

====

B-frames are not ref frames option. There is no limit on length of chain of B-frames in the standards, the length of B-frame chains does not affect decoding much.

Permitting longer B-frames chains offsets it's tiny increase in decoding complexity by eliminating P-frames complexity (P-frames have the peak major complexity during decoding), so usage of B-frames sometimes even can decrease decoding complexity overall.

The longer B-frames chain x264 detects - the better bit-compression we get. If in the shot - picture is still or moves gradually, naturally - we don't need frequent P-frames, B-frames would flow referring to their neighbors.

**Comment by Anton-Latukha** [comment]
Ok. Real results:

### Input
I ran fast-assembled encoding test on classic test - Big Buck Bunny raw source footage. It is an animation test.

```
ffmpeg -i ./big_buck_bunny_1080p24.y4m -c:v libx264 -crf 23 -movflags faststart output-ref3-badapt1-bf16.mkv
```

```
ffmpeg -i ./big_buck_bunny_1080p24.y4m -c:v libx264 -crf 23 -bf 16 -movflags faststart output-ref3-badapt1-bf16.mkv
```

### Results

The difference is **so massive** and obvious, that I do not need other tests.

`-bf 3` (default setting):
```
[libx264 @ 0x762920] frame I:151   Avg QP:18.05  size:209171
[libx264 @ 0x762920] frame P:4176  Avg QP:21.82  size: 30327
[libx264 @ 0x762920] frame B:9988  Avg QP:25.31  size:  6169
[libx264 @ 0x762920] consecutive B-frames:  3.9%  5.8%  9.8% 80.4%
[libx264 @ 0x762920] kb/s:2948.67
1734.58user 20.99system 7:52.95elapsed 371%CPU (0avgtext+0avgdata 689144maxresident)
```

We already can see, that B chain (`3.9%  5.8%  9.8% 80.4%`) floores in ~80% of cases, it wants to go further, but default setting does not allow it. So I already expected massive change. Interesting why this still is not fixed in FFMpeg. I probably would raise a issue for them. Or ask `libav` folks, they are also HandBrake devs, and they have other defaults.

`-bf 16`:
```
[libx264 @ 0x22cb9e0] frame I:151   Avg QP:17.53  size:220066
[libx264 @ 0x22cb9e0] frame P:2624  Avg QP:21.98  size: 37530
[libx264 @ 0x22cb9e0] frame B:11540 Avg QP:25.66  size:  6766
[libx264 @ 0x22cb9e0] consecutive B-frames:  3.7%  5.3%  9.1%  7.3%  5.9% 11.4%  4.9%  8.4%  4.1%  4.7%  3.3%  4.5%  3.3%  3.0%  2.5%  2.6% 15.9%
[libx264 @ 0x22cb9e0] kb/s:2813.70
1888.44user 22.45system 7:17.72elapsed 436%CPU (0avgtext+0avgdata 1204828maxresident)k
84877520inputs+422456outputs (0major+23962minor)pagefaults 0swaps
```

### B-frame chains

We can see `-bf 16` permits longer B-chains.

```
[libx264 @ 0x22cb9e0] consecutive B-frames:  3.7%  5.3%  9.1%  7.3%  5.9% 11.4%  4.9%  8.4%  4.1%  4.7%  3.3%  4.5%  3.3%  3.0%  2.5%  2.6% 15.9%
```

Also we see that P-frames usage changed to B-frames usage change:

```
-bf 3
[libx264 @ 0x762920] frame P:4176  Avg QP:21.82  size: 30327
[libx264 @ 0x762920] frame B:9988  Avg QP:25.31  size:  6169
vs
-bf 16
[libx264 @ 0x22cb9e0] frame P:2624  Avg QP:21.98  size: 37530
[libx264 @ 0x22cb9e0] frame B:11540 Avg QP:25.66  size:  6766
```
`1 - (2624/4176)  = 0.3716475095785441  -> ~37.2%` reduction of P-frames usage.
`(11540/9988) - 1 = 0.1553864637565079  -> ~15.6%` increase  of B-frames usage (we have bigger pool of B-frames then P-frames, that is why 1500 P-frames reduction of ~37.2% increased B pool on ~15.6%)

#### Encoding time

So we see the time of encoding reduced mainly because it encodes much less P frames (it used to floor B-frames to 3, so x264 was forced to encode P, and they have more encoding/decoding complexity). I-frames number was the same, because algorithm of their detection does not depend on B-frames or P-frames, but on input from the source.

The speed-up of encoding we got: `0.09x`, or 9%, which is massive gain number in encoding.

### Compression

#### In stream metric
We got `2950.8kbits/s - 2815.8kbits/s = 134.97 kbits/s` stream reduction! That is the whole supplementary audio stream right there.

#### In filesize metric

`1-(204975kB/214802kB) = 4.58%` decrease of file size. 
Or in MBytes, we got 1 MByte/minute savings.

#### Decoding benchmark

`-bf 3`
```
frame=14315 fps=615 q=-0.0 Lsize=N/A time=00:09:56.45 bitrate=N/A speed=25.6x
bench: utime=138.506s
bench: maxrss=110292kB
```

`-bf 16`
```
frame=14315 fps=592 q=-0.0 Lsize=N/A time=00:09:56.45 bitrate=N/A speed=24.7x
video:7381kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
bench: utime=142.228s
bench: maxrss=135544kB
```

`-bf 16` decoding took `(142.228/138.506) - 1 = 2.7%` more CPU time.

### So, lets sum-up:

```
B-frames 16 give:

* +9% to encoding speed
* +2.7% decoding complexity 
* +4.58% better compression
```

As you know - most times users have playback problems due to networking. And +4.58% better compression gives much better user expirience bump, then +2.7% of decoding complexity. Like mobile phone users - most of the time users have that 3% of CPU while playing video around, but they often rely on mobile network coverage. And 3%-5% reduction means a smoother/faster loading playback to them.

And +9% to encoding speed.

So we got what I said in previous messages.


### Encoding logs

#### B-frames 3

```
Output #0, matroska, to 'output-ref3-badapt1-bf3.mkv':
  Metadata:
    encoder         : Lavf57.83.100
    Stream #0:0: Video: h264 (libx264) (H264 / 0x34363248), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=-1--1, 24 fps, 1k tbn, 24 tbc
    Metadata:
      encoder         : Lavc57.107.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
frame=14315 fps= 30 q=-1.0 Lsize=  214802kB time=00:09:56.33 bitrate=2950.8kbits/s speed=1.27x      
video:214693kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.050843%
[libx264 @ 0x762920] frame I:151   Avg QP:18.05  size:209171
[libx264 @ 0x762920] frame P:4176  Avg QP:21.82  size: 30327
[libx264 @ 0x762920] frame B:9988  Avg QP:25.31  size:  6169
[libx264 @ 0x762920] consecutive B-frames:  3.9%  5.8%  9.8% 80.4%
[libx264 @ 0x762920] mb I  I16..4: 19.0% 62.7% 18.4%
[libx264 @ 0x762920] mb P  I16..4:  1.9%  7.3%  0.8%  P16..4: 27.2%  8.1%  5.6%  0.0%  0.0%    skip:49.1%
[libx264 @ 0x762920] mb B  I16..4:  0.3%  0.9%  0.1%  B16..8: 23.1%  1.7%  0.4%  direct: 1.1%  skip:72.3%  L0:41.4% L1:53.3% BI: 5.2%
[libx264 @ 0x762920] 8x8 transform intra:69.8% inter:74.9%
[libx264 @ 0x762920] coded y,uvDC,uvAC intra: 55.9% 60.8% 28.5% inter: 7.9% 8.0% 1.1%
[libx264 @ 0x762920] i16 v,h,dc,p: 26% 19%  4% 51%
[libx264 @ 0x762920] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 21% 14% 18%  5%  8% 13%  7%  8%  7%
[libx264 @ 0x762920] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 24% 14% 12%  6% 11% 12%  8%  7%  6%
[libx264 @ 0x762920] i8c dc,h,v,p: 52% 19% 17% 11%
[libx264 @ 0x762920] Weighted P-Frames: Y:4.9% UV:3.3%
[libx264 @ 0x762920] ref P L0: 63.9% 18.1% 12.0%  6.0%  0.1%
[libx264 @ 0x762920] ref B L0: 84.8% 12.4%  2.8%
[libx264 @ 0x762920] ref B L1: 96.3%  3.7%
[libx264 @ 0x762920] kb/s:2948.67
1734.58user 20.99system 7:52.95elapsed 371%CPU (0avgtext+0avgdata 689144maxresident)k
84964792inputs+444136outputs (0major+23772minor)pagefaults 0swaps
```

#### B-frames 16

```
Output #0, matroska, to 'output-ref3-badapt1-bf16.mkv':
  Metadata:
    encoder         : Lavf57.83.100
    Stream #0:0: Video: h264 (libx264) (H264 / 0x34363248), yuv420p, 1920x1080 [SAR 1:1 DAR 16:9], q=-1--1, 24 fps, 1k tbn, 24 tbc
    Metadata:
      encoder         : Lavc57.107.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
frame=14315 fps= 33 q=-1.0 Lsize=  204975kB time=00:09:56.33 bitrate=2815.8kbits/s speed=1.36x       
video:204866kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.053076%
[libx264 @ 0x22cb9e0] frame I:151   Avg QP:17.53  size:220066
[libx264 @ 0x22cb9e0] frame P:2624  Avg QP:21.98  size: 37530
[libx264 @ 0x22cb9e0] frame B:11540 Avg QP:25.66  size:  6766
[libx264 @ 0x22cb9e0] consecutive B-frames:  3.7%  5.3%  9.1%  7.3%  5.9% 11.4%  4.9%  8.4%  4.1%  4.7%  3.3%  4.5%  3.3%  3.0%  2.5%  2.6% 15.9%
[libx264 @ 0x22cb9e0] mb I  I16..4: 18.4% 62.3% 19.3%
[libx264 @ 0x22cb9e0] mb P  I16..4:  2.8% 10.5%  1.2%  P16..4: 29.4%  8.9%  5.9%  0.0%  0.0%    skip:41.4%
[libx264 @ 0x22cb9e0] mb B  I16..4:  0.3%  1.0%  0.1%  B16..8: 21.1%  2.0%  0.4%  direct: 1.3%  skip:73.7%  L0:43.4% L1:50.9% BI: 5.6%
[libx264 @ 0x22cb9e0] 8x8 transform intra:69.6% inter:75.6%
[libx264 @ 0x22cb9e0] coded y,uvDC,uvAC intra: 56.6% 61.5% 29.4% inter: 7.3% 6.8% 0.7%
[libx264 @ 0x22cb9e0] i16 v,h,dc,p: 26% 18%  4% 52%
[libx264 @ 0x22cb9e0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 21% 14% 17%  5%  8% 13%  8%  8%  7%
[libx264 @ 0x22cb9e0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 24% 14% 12%  6% 11% 12%  8%  7%  6%
[libx264 @ 0x22cb9e0] i8c dc,h,v,p: 52% 19% 18% 11%
[libx264 @ 0x22cb9e0] Weighted P-Frames: Y:7.4% UV:5.3%
[libx264 @ 0x22cb9e0] ref P L0: 65.2% 18.0% 11.7%  4.9%  0.1%
[libx264 @ 0x22cb9e0] ref B L0: 86.7% 11.8%  1.5%
[libx264 @ 0x22cb9e0] ref B L1: 96.0%  4.0%
[libx264 @ 0x22cb9e0] kb/s:2813.70
1888.44user 22.45system 7:17.72elapsed 436%CPU (0avgtext+0avgdata 1204828maxresident)k
84877520inputs+422456outputs (0major+23962minor)pagefaults 0swaps
```

**Comment by Fenrirthviti** [comment]
This seems like it is more of an RFC than a bug report.

This post is also confusing and isn't clear exactly what you're trying to say here.

If this is supposed to be a bug report, please correctly fill out the issue template. In the future, make sure you are taking the time to read the template and not just deleting it.

If this is an RFC, please follow our RFC process outlined here: https://github.com/obsproject/rfcs

**Comment by Anton-Latukha** [comment]
> This seems like it is more of an RFC than a bug report.
> 
> This post is also confusing and isn't clear exactly what you're trying to say here.
> 
> If this is supposed to be a bug report, please correctly fill out the issue template. In the future, make sure you are taking the time to read the template and not just deleting it.
> 
> If this is an RFC, please follow our RFC process outlined here: https://github.com/obsproject/rfcs

Thanks.

Sometime IDK, it is not a feature request. It can be seen as kind of bug report, but more as a bug in x264 default settings.

Maybe I should upstream it anyway even more.

Would close and open RFC and discuss there.

**Comment by lextra2** [comment]
I wouldn't recommend using `bframes=16` for livestreaming. It is much slower and at 8000 bitrate, it has no quality advantages over `preset=medium` defaults.

Here are my tests, with a Ryzen 9 3900x. I've used the same settings a stream produced by OBS would set.

```
ffmpeg -y -benchmark -i blender.mp4 -t 120 -c:v libx264 -x264-params "keyint=120:scenecut=0:nal-hrd=none:filler=1:vbv-maxrate=8000:vbv-bufsize=8000:bitrate=8000:threads=24" -profile:v high -level:v 4.2 -preset medium -pix_fmt nv12 -color_primaries bt709 -color_trc bt709 -colorspace bt709 -color_range tv -an OUTPUT.mkv
```

```
frame= 7198 fps=180 q=-1.0 Lsize=  117114kB time=00:01:59.95 bitrate=7998.3kbits/s speed=   3x
bench: utime=613.766s stime=3.047s rtime=39.963s
bench: maxrss=1369476kB
[libx264 @ 00000239f48fed40] frame I:60    Avg QP:12.39  size:331923
[libx264 @ 00000239f48fed40] frame P:2050  Avg QP:15.12  size: 32223
[libx264 @ 00000239f48fed40] frame B:5088  Avg QP:20.65  size:  6662
[libx264 @ 00000239f48fed40] consecutive B-frames:  3.5%  4.4%  6.7% 85.4%
[libx264 @ 00000239f48fed40] mb I  I16..4: 14.9% 57.9% 27.3%
[libx264 @ 00000239f48fed40] mb P  I16..4:  1.4%  3.7%  0.7%  P16..4: 28.1%  9.1%  6.6%  0.0%  0.0%    skip:50.4%
[libx264 @ 00000239f48fed40] mb B  I16..4:  0.2%  0.2%  0.0%  B16..8: 23.7%  1.1%  0.2%  direct: 0.9%  skip:73.6%  L0:44.2% L1:52.2% BI: 3.6%
[libx264 @ 00000239f48fed40] 8x8 transform intra:60.8% inter:69.0%
[libx264 @ 00000239f48fed40] coded y,uvDC,uvAC intra: 59.0% 67.8% 44.5% inter: 6.1% 6.8% 1.6%
[libx264 @ 00000239f48fed40] i16 v,h,dc,p: 40% 20%  5% 34%
[libx264 @ 00000239f48fed40] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 19% 18% 17%  6%  8%  8%  8%  8%  8%
[libx264 @ 00000239f48fed40] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 23% 19% 11%  7% 10%  8%  8%  8%  7%
[libx264 @ 00000239f48fed40] i8c dc,h,v,p: 49% 22% 17% 11%
[libx264 @ 00000239f48fed40] Weighted P-Frames: Y:1.3% UV:1.2%
[libx264 @ 00000239f48fed40] ref P L0: 61.7% 13.9% 16.7%  7.6%  0.0%
[libx264 @ 00000239f48fed40] ref B L0: 86.3% 10.6%  3.1%
[libx264 @ 00000239f48fed40] ref B L1: 94.7%  5.3%
[libx264 @ 00000239f48fed40] kb/s:7993.33
```

```
Encoding settings: cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=24 / lookahead_threads=4 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=120 / keyint_min=12 / scenecut=0 / intra_refresh=0 / rc_lookahead=40 / rc=cbr / mbtree=1 / bitrate=8000 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / vbv_maxrate=8000 / vbv_bufsize=8000 / nal_hrd=none / filler=1 / ip_ratio=1.40 / aq=1:1.00
```

------------------------------------------------------------------------------------
And now with 16 bframes:
------------------------------------------------------------------------------------

```
ffmpeg -y -benchmark -i blender.mp4 -t 120 -c:v libx264 -x264-params "bframes=16:keyint=120:scenecut=0:nal-hrd=none:filler=1:vbv-maxrate=8000:vbv-bufsize=8000:bitrate=8000:threads=24" -profile:v high -level:v 4.2 -preset medium -pix_fmt nv12 -color_primaries bt709 -color_trc bt709 -colorspace bt709 -color_range tv -an OUTPUT2.mkv
```

```
frame= 7198 fps=144 q=-1.0 Lsize=  117115kB time=00:01:59.95 bitrate=7998.4kbits/s speed=2.41x
bench: utime=667.844s stime=7.422s rtime=49.827s
bench: maxrss=1996948kB
[libx264 @ 000001b537632c00] frame I:60    Avg QP:12.57  size:331180
[libx264 @ 000001b537632c00] frame P:1408  Avg QP:14.30  size: 37448
[libx264 @ 000001b537632c00] frame B:5730  Avg QP:21.15  size:  8250
[libx264 @ 000001b537632c00] consecutive B-frames:  3.1%  4.3%  4.2% 18.9%  8.1% 17.2% 10.5%  5.9%  2.9%  4.2%  3.4%  6.5%  1.8%  0.8%  2.7%  0.4%  5.2%
[libx264 @ 000001b537632c00] mb I  I16..4: 15.5% 57.4% 27.1%
[libx264 @ 000001b537632c00] mb P  I16..4:  2.0%  5.2%  0.9%  P16..4: 26.1%  8.8%  6.1%  0.0%  0.0%    skip:51.0%
[libx264 @ 000001b537632c00] mb B  I16..4:  0.2%  0.3%  0.0%  B16..8: 20.9%  1.2%  0.2%  direct: 0.9%  skip:76.3%  L0:41.4% L1:54.0% BI: 4.6%
[libx264 @ 000001b537632c00] 8x8 transform intra:61.0% inter:68.4%
[libx264 @ 000001b537632c00] coded y,uvDC,uvAC intra: 60.3% 68.1% 45.5% inter: 4.7% 5.1% 1.3%
[libx264 @ 000001b537632c00] i16 v,h,dc,p: 41% 20%  5% 34%
[libx264 @ 000001b537632c00] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 19% 18% 16%  6%  8%  8%  8%  8%  8%
[libx264 @ 000001b537632c00] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 22% 19% 11%  7% 10%  8%  8%  8%  7%
[libx264 @ 000001b537632c00] i8c dc,h,v,p: 49% 22% 17% 11%
[libx264 @ 000001b537632c00] Weighted P-Frames: Y:1.6% UV:1.5%
[libx264 @ 000001b537632c00] ref P L0: 67.2% 14.1% 13.7%  5.0%  0.0%
[libx264 @ 000001b537632c00] ref B L0: 91.1%  7.6%  1.3%
[libx264 @ 000001b537632c00] ref B L1: 97.3%  2.7%
[libx264 @ 000001b537632c00] kb/s:7993.33
```

```
Encoding settings: cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=24 / lookahead_threads=4 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=16 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=120 / keyint_min=12 / scenecut=0 / intra_refresh=0 / rc_lookahead=40 / rc=cbr / mbtree=1 / bitrate=8000 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / vbv_maxrate=8000 / vbv_bufsize=8000 / nal_hrd=none / filler=1 / ip_ratio=1.40 / aq=1:1.00
```

As you can see by the "rtime", 16 bframes is about 25% slower.

**Comment by Anton-Latukha** [comment]
Tested encoding in sets multiple times before & in the decade before opening the thread, the first link in the head is where old test results are also posted. In those years time delta was on a margin of statistical error, and there were cases when setting `bframes=16 / b_adapt` was faster & compression was better.

Not tracking upstream changes in x264, maybe something changed in 3 years. No longer holding the breath.
