### ISSUE TITLE
Replay Buffer don't work with M3U8 in version 26.0.0

### ISSUE THREAD

**Issue by RandoMixs** [obsproject/obs-studio#3580]
## Platform

Operating system and version: Windows 10, Version 2004, Build 19041.508
OBS Studio version: 26.0.2 (64bit)

## Expected Behavior
You would press the button to generate the replay buffer and it would return the buffer files in ts and m3u8

## Current Behavior
You try generate the buffer replay but it never generates all files

## Steps to Reproduce
[YouTube Video](https://www.youtube.com/watch?v=3QMmE1PG8s8)

1. Launch OBS Studio
2. Start Replay Buffer
3. Try save it
4. It will not save all necessary m3u8 files;

## Additional information
In the process manager when trying to generate the replay buffer, a process called "obs-ffmpeg-mux.exe" appears and gets stuck, using no computer resources

*Edit: m3u8 recordings also broke in my tests

**Comment by flaeri** [comment]
curiosity got the better of me, and I have to ask, since I dont understand. Why would you ever want your replay buffer files to be in the form of m3u8?

**Comment by RandoMixs** [comment]
> curiosity got the better of me, and I have to ask, since I dont understand. Why would you ever want your replay buffer files to be in the form of m3u8?

@flaeri as the m3u8 generates several fragments of 2 seconds of each replay when you are going to play them, it ends up loading faster than a mp4, I made my own script to reproduce all replays and I did a previous version working with MP4 and sometimes I had a problem with buffering even on the local network.

**Comment by dodgepong** [comment]
> as the m3u8 generates several fragments of 2 seconds of each replay when you are going to play them, it ends up loading faster than a mp4

"Loading" in what context? For local playback? Or for posting online somewhere?

**Comment by RandoMixs** [comment]
> > as the m3u8 generates several fragments of 2 seconds of each replay when you are going to play them, it ends up loading faster than a mp4
> 
> "Loading" in what context? For local playback? Or for posting online somewhere?

@dodgepong Local reproduction, I reproduce all the replay buffers via HTML & JS (I use a browser source in this case)

m3u8 worked well in previous versions of OBS for this, but now OBS is no longer generating files correctly (and apparently m3u8 recordings are also not being generated correctly)

**Comment by energizerfellow** [comment]
@RandoMixs Define "previous version". What was the last functional version of OBS Studio where this M3U8 worked the way you're expecting?

**Comment by RandoMixs** [comment]
> @RandoMixs Define "previous version". What was the last functional version of OBS Studio where this M3U8 worked the way you're expecting?

For me it worked until OBS Studio 25.0.8
M3U8 stopped working on 26.0.0 (the current version 26.0.2 it also doesn't work)

**Comment by derrod** [comment]
There have been some fixes to the ffmpeg muxer for the HLS output (see #3114) that may fix this as well, could you retest with a more recent build?

**Comment by gxalpha** [comment]
Closing as stale. May be fixed by now.
