### ISSUE TITLE
Can't resize Windowed Projector on KDE/Plasma

### ISSUE THREAD

**Issue by strotlog** [obsproject/obs-studio#3582]
## Platform
Operating system and version: Ubuntu Linux 20.04
OBS Studio version: 26.0.2 ppa:obsproject/obs-studio

## Expected Behavior
Can resize Windowed Projectors.

## Current Behavior
Can maximize window which increases resolution/detail successfully.
**Cannot resize** the Windowed Projector window to any other size. It is stuck at about 270p resolution.

## Steps to Reproduce
0. Start desktop environment as `startplasma-x11` (kubuntu-desktop package)
1. In OBS, right click the current Scene's name
2. Select Windowed Projector (Scene)

## Additional information
- Resize still works fine for all other windows created by the application, OBS Studio.
- Issue does not occur if OBS is run under X forwarding, nor is it encountered if run under Gnome.
- Workaround: `wmctrl -r 'windowed projector' -e 0,100,100,1280,720`

**Comment by kkartaltepe** [comment]
If it runs under gnome and X, and resizing it with the wmctrls works, then im not sure how this can be an OBS problem. As described it sounds like you should file a bug against KDE.

**Comment by strotlog** [comment]
Hm.

Added new workaround (B) to OP.
