### ISSUE TITLE
OBS window still resizes upon starting recording in version 26.0.2 if docked to a side of the monitor in Windows

### ISSUE THREAD

**Issue by jhobz** [obsproject/obs-studio#3583]
## Platform

Operating system and version: Windows 10 Pro
OBS Studio version: 26.0.2

## Expected Behavior

Starting recording should not resize window per v26.0 update.

## Current Behavior

**Specifically when the window is snapped to a side of the monitor,** it still resizes upon starting a recording (or starting streaming with the "automatically record" setting enabled).

## Steps to Reproduce

1. Open OBS Studio v26.0.2 in Windows 10
2. Click and drag from the title bar to the edge of a monitor such that the window "snaps" to one side of the monitor
3. Start recording, observe that window resizes

## Additional information

Seems to not happen when the window is maximized nor floating standalone, only when snapped to a side. Happened on 26.0.0 as well.

**Comment by jpark37** [comment]
I am not able to reproduce with 26.0.2 on Windows 10 Pro 2004 on either of my monitors. Can you reproduce the issue, then upload the current log file from the help menu?

**Comment by jhobz** [comment]
Here's a [video of the issue occurring](https://streamable.com/e1dfjl) and the [log file.](https://obsproject.com/logs/TGepdxP4e94aIvfS)

**Comment by jpark37** [comment]
I think it's the Calculating... message in the Stats panel that is causing it. I can reproduce without side docking by just squishing the window down.
