### ISSUE TITLE
Obs wont let me record with current encoder. (Which i have been using since i started using OBS) the problem started as soon as I downloaded obs 26.0.2

### ISSUE THREAD

**Issue by AgentClyde** [obsproject/obs-studio#3584]
## Platform

Operating system and version:
OBS Studio version:

## Steps to Reproduce

1.
2.
3.
4.

**Comment by WizardCM** [comment]
Please fill in the issue template completely.

**Comment by Fenrirthviti** [comment]
The issues page is not for support, please use the forums or Discord instead.
