### ISSUE TITLE
 When the recording output format is ffmpeg, the pause button is not visible.

### ISSUE THREAD

**Issue by kmoon2437** [obsproject/obs-studio#3585]
When the recording output format is ffmpeg, the pause button is not visible.

**Comment by kmoon2437** [comment]
When the recording output format is ffmpeg, the pause button is not visible.

**Comment by Fenrirthviti** [comment]
Pausing is not supported with custom ffmpeg output mode as there are too many variables to account for. Not a bug.

In the future, please do not disregard and delete our issue template.
