### ISSUE TITLE
Virtual Camera: image source confusing implicit horizontal flip

### ISSUE THREAD

**Issue by int3l** [obsproject/obs-studio#3590]
## Platform

Operating system and version: Windows 10 Pro 1909 18363.1110
OBS Studio version: 26.0.2 (64 bit)

## Expected Behavior

The new Virtual Camera built-in flipping feature should not affect any other source besides the **Video Capture Device** or we should have the option to manually enable flipping.

## Current Behavior

At the moment, there is no practical way to stream and use the Virtual Camera at the same time with Image/Slide Show sources without the image source being horizontally flipped in either the stream or the virtual camera.

Example, correct image on stream and flipped on Virtual Camera:
![flipped_image_source](https://user-images.githubusercontent.com/1278836/95632453-5a352c00-0a8e-11eb-8cf6-eacf9d56efff.png)

Example, flipped image on stream and correct on Virtual Camera:
![image](https://user-images.githubusercontent.com/1278836/95633388-3d015d00-0a90-11eb-8278-d8f494c81dbb.png)

## Steps to Reproduce

1. Add webcam source and/or just an image source
2. Start the new Virtual Camera and also start the streaming.
3. Observe the difference at the Preview screen and at the actual software that uses the OBS Virtual Camera.
The image will be horizontally flipped in either the OBS Virtual Camera or in the current stream.

## Additional information

I know that the developers want to make this feature really simple, but at the moment this is really confusing.
The implicit flipping is not intuitive at all and also if you have multiple image sources - you will have to go and flip all of them in order to have the text correctly displayed in the stream or in the virtual camera.

**Comment by Fenrirthviti** [comment]
The view you see in your application is flipped for you only. This is because most applications expect a webcam, and they want to mimic looking in a mirror for your own preview. Everyone else sees what you see in the OBS preview.

This is not a bug, and you don't need to flip anything.

**Comment by dodgepong** [comment]
To clarify this further: OBS isn't doing any flipping at all. The "implicit flipping" you describe is happening entirely on the side of the application you are using the view the virtual camera feed, and OBS has no control over that behavior. OBS sends the camera feed in the correct orientation -- if it's flipped after that, it's being flipped by the other program.

**Comment by int3l** [comment]
@dodgepong yep, I understand that now - but maybe it will be cool if this can be pointed somehow to the user.
Maybe adding this to the default OBS Virtual Camera (blue) background? Or at least adding a hint, when you start the virtual camera for the first time?

**Comment by duaneking** [comment]
This is an accessibility bug because I'm not able to show people my screen easily, and needing to google the fix makes OBS look broken.  I want to see what others see, and I want the ability to see my screen without flip.
