### ISSUE TITLE
Hotkeys are not persisted across restarts for “Advanced Scene Switcher” Plugin

### ISSUE THREAD

**Issue by Bombe** [obsproject/obs-studio#3591]
## Platform

Operating system and version: macOS 10.13.6
OBS Studio version: 26.0.2 (64 bit)

## Expected Behavior

When exiting and restarting OBS I expect all hotkey assignments to be restored.

## Current Behavior

Hotkey assignments for the Advanced Scene Switcher plugin are not restored.

## Steps to Reproduce

1. Install the Advanced Scene Switcher plugin.
2. Configure a hotkey for starting or stopping it.
3. Exit OBS.
4. Restart OBS. The hotkeys are no longer assigned.

## Additional information

It is unclear (at least to me) whether this behaviour is specific to this one plugin or whether all plugin hotkey configuration is concerned; no other plugin I have installed has configurable hotkeys.

**Comment by Fenrirthviti** [comment]
This will need to be reported to the author of the plugin, as we do not maintain the advanced scene switcher.

**Comment by Bombe** [comment]
Yeah but you do maintain the persistence of all the options in OBS’s settings dialog, don’t you?

**Comment by Fenrirthviti** [comment]
Does the issue persist without the plugin installed? If the plugin is causing issues with OBS' normal functions, you'll need to report it to them. There is not much we can do.

**Comment by Bombe** [comment]
If the plugin is not installed, I can (of course) not assing hotkeys to it. Other hotkeys are persisted just fine. Without knowing OBS’s code I do however find it dubious that a plugin actually needs to persist its own hotkeys, especially when configured in OBS’s settings dialog (and not in the plugin’s custom UI).

**Comment by Fenrirthviti** [comment]
Plugins are responsible for registering and saving their own hotkeys. Again, please report this issue to the plugin developer.

**Comment by Bombe** [comment]
As you can see above, I already did. Thanks for the explanation!
