### ISSUE TITLE
picture slideshow only displays a few pictures and not full directory

### ISSUE THREAD

**Issue by scantsquad** [obsproject/obs-studio#3595]
## Platform

Operating system and version:
OBS Studio version:

## Steps to Reproduce

1.
2.
3.
4.

**Comment by scantsquad** [comment]
windows 10 64bit, obs 26.0.2, only displays maybe 6-8 pictures in slideshow display. the rest of the pictures do not attempt to load or display

**Comment by WizardCM** [comment]
Duplicate of #3366. Next time please fill in the issue template.
