### ISSUE TITLE
YouTube stream -- OBS "Start Streaming" does nothing until I first "listen" on the YT Studio page

### ISSUE THREAD

**Issue by icy-** [obsproject/obs-studio#3596]
## Platform

Operating system and version:
OBS Studio version:  Windows 10, 26.0.2

## Expected Behavior

I should be able to click OBS "Start Streaming" button, and in a few seconds see the results in YT's Channel Videos page.  This page would then produce a new stream under "Live" tab with the red recording marker.

## Current Behavior

Currently, OBS shows the normal green square to show the bits are being sent, but there's no actual result.  The Channel Videos page is the same as before, with no indication anything is live.
In the last week, I suspect something changed, perhaps from YT side, idk.  I've been pressing just the one OBS button for many months successfully on the same stream key.  

I never had to do an in-between step before.  Apparently this is now the "Create" button, with camcorder icon, from YT signed in page.  This then brings you to their platform called "Studio", with a live preview box.  Inside this box is text "Connect streaming software to go live", implying that the YT "listen" has been started.  After doing this step, then OBS sends fine.

## Steps to Reproduce

1. Confirm you're sending to Youtube primary in settings->streaming.  Make sure your key is fine.
2. "Start Streaming" button
3. Go to Channel Videos.   This is from (signed in youtube)-> click your icon/avatar -> YouTube Studio -> Videos tab on the left side -> Live tab near the middle
4. Wait some seconds, confirm nothing is happening.

Workaround is after Step 1, go to your icon/avatar -> YouTube Studio -> Create (camcorder icon in top right).

## Additional information

OBS was able to start the stream listen on its own in the past

**Comment by Gol-D-Ace** [comment]
Had a quick look and this is a change in YouTube's behavior. OBS Studio has nothing to do with that.

**Comment by dodgepong** [comment]
I would consider this a feature request for YouTube API integration rather than a bug.

**Comment by derrod** [comment]
YouTube has removed the old "Stream Now" feature. Whole you can set a stream to automatically go live once it receives data from OBS, I don't think it is possible to create a permanent stream within the new UI.

**Comment by Gol-D-Ace** [comment]
Streams in the new UI did go live automatically and they added permanent stream keys but apparently the behavior changed once again in the last days.

**Comment by Gol-D-Ace** [comment]
Did a bit more testing and they show up for me on the channel just not in the videos.
![Screenshot_20201010-171633](https://user-images.githubusercontent.com/5058319/95658686-93b47880-0b1c-11eb-8598-91034a42fa2c.png)

**Comment by icy-** [comment]
this is with the `https://studio.youtube.com/video/SOMETOKENHERE/livestreaming`  page not open?

**Comment by Gol-D-Ace** [comment]
Live Studio is definitely not open.
Did you mark your stream as unlisted or private?
This is using the default stream key they provide.

**Comment by icy-** [comment]
yeah it's an unlisted key.  I've had it work when the Live Studio page was recently closed, such as just now, and OBS Start Streaming did result in a Channel Videos.  But this could be coincidence.

I've killed the Live Studio page, restarted OBS, did Start Streaming, went to Channel Videos.  More than a minute of waiting and still nothing.

**Comment by icy-** [comment]
> YouTube has removed the old "Stream Now" feature. Whole you can set a stream to automatically go live once it receives data from OBS, I don't think it is possible to create a permanent stream within the new UI.
Still, @derrod , I disagree with closing the issue.
Clicking "Start Streaming" without first listening with things looking normal is a bug.  Perhaps a YT API error (in bind?) got swallowed.  https://developers.google.com/youtube/v3/live/docs/liveBroadcasts/bind
The bug is about a button not fully working, not about a "stream now" permanent key feature.

**Comment by derrod** [comment]
OBS doesn't interact with the YouTube API. The "Start Streaming" button just starts streaming to the server specified in the OBS configuration. Therefore this is not an OBS bug, just an idiosyncrasy with how YouTube handles live streams now.
