### ISSUE TITLE
obs v26 issue

### ISSUE THREAD

**Issue by Mihnyy** [obsproject/obs-studio#3602]
When recording at high framerates and resampling we are getting less frames than we are meant to, and less than obs is reporting of and being skipped. my friends have researched this and found the problem was coming from obs and not vegas. currently we are using obs v24 as a temporary fix. we have also noticed that v26's bt601 and bt709 are also messed up in terms of accuracy

**Comment by Fenrirthviti** [comment]
Please properly fill out the issue template. This report is not actionable as provided.
