### ISSUE TITLE
When the OBS window is not in focus, using shortcut keys to switch scenes occasionally fails.

### ISSUE THREAD

**Issue by Danjuanlab** [obsproject/obs-studio#3605]
Operating system and version:Windows 10 1903
OBS Studio version:26.0.2

## Expected Behavior
When the obs window is not in focus, use shortcut keys to switch scenes, OBS will not have accidental freezes.

## Current Behavior
When the OBS window is not in focus, using shortcut keys to switch scenes occasionally fails.
Occasionally it will get stuck, and when the switch fails, the scene transitions will turn gray.At this point, I need to press the shortcut key again to switch scenes to normal.

## Steps to Reproduce
here is my obs settings:
![捕获11111](https://user-images.githubusercontent.com/42509669/96002821-23835b00-0e6c-11eb-8ca5-f115a0b9b40f.PNG)

![tt](https://user-images.githubusercontent.com/42509669/96004077-86292680-0e6d-11eb-9d40-4dfaaffaab59.gif)
Watch the Scene Transitions~
[LOG.txt](https://github.com/obsproject/obs-studio/files/5378921/2020-10-14.22-11-16.txt)

**Comment by Fenrirthviti** [comment]
I am not able to replicate on the limited information you have provided. Can you please provide clear and concise replication steps rather than making us guess what is going on in those gifs?

**Comment by Danjuanlab** [comment]
> I am not able to replicate on the limited information you have provided. Can you please provide clear and concise replication steps rather than making us guess what is going on in those gifs?

1. Set the behavior of shortcut keys in OBS settings to never disable hotkeys.
2. Create scene 1, and set the shortcut key F9.
3. Create scene 2 and set the shortcut key F10.
4. Create some new sources arbitrarily in scenes 1 and 2 to distinguish them.
5. Set the scene transtions to cut.
5. Switch the currently focused window to chrome and keep the obs window out of focus.
6. Click F9 and F10 in turn to switch scenes in OBS. In continuous operation, scene switching failures occasionally occur. When it fails, the drop-down list of scene transitions will turn gray.
7. Click the shortcut key again to activate the corresponding scene again.

**Comment by Wiethoofd** [comment]
Can confirm this happens with the F-keys in Chrome, stinger/transition type doesn't matter, same for having studio mode enabled or not.

Logs also only show a duplicate entry for scene transition, without actually doing the transition.

Note, the chrome page I also used for testing has `evt.preventDefault();` on all the F-keys, so it's not Chrome picking up F1-F12, but even with global hotkeys enabled in OBS that shouldn't be an issue to completely skip the scene transition, but still report in the log it did.

**Comment by mouarfff** [comment]
I can confirm, i always this bug since some monthes
what information do you need ?
(latested version of OBS Studio, with Streamelements plugin)

**Comment by nicoasi** [comment]
Last working version is 25.0.8

**Comment by RytoEX** [comment]
Please retest in OBS Studio 28.0.3 (or newer) to see if this is still an issue.

**Comment by tom-huntington** [comment]
Windows 11, OBS 19.1.3, running as admin

If I spam the hotkey eventually it works. Sometimes it works 90% of the time, sometimes it takes more than 10 tries. Fickle

**Comment by tom-huntington** [comment]
I realized that running as admin makes no difference for me. So this is probably this issue.

**Comment by Fenrirthviti** [comment]
Closing as stale. If this is still an issue please open a new issue with updated reproduction steps on the latest version of OBS.

As a note we have not been able to reproduce, and there is a good change third-party software is interfering in some way.
