### ISSUE TITLE
Obs v26.0.3 resample issue

### ISSUE THREAD

**Issue by Mihnyy** [obsproject/obs-studio#3609]
Operating system and version:windows 10 1909
 OBS Studio version:26.0.3
 Tell us what happens instead of the expected behavior:When recording at high framerates and resampling we are getting less frames than we are meant to, and less than obs is reporting of and being skipped. my friends have researched this and found the problem was coming from obs and not vegas. currently we are using obs v24 as a temporary fix. we have also noticed that v26's bt601 and bt709 are also messed up in terms of accuracy

**Comment by Fenrirthviti** [comment]
Template deleted, not a valid report, unclear what this is actually reporting, but sounds like a support request. Support requests should be submitted to our forums or discord: https://obsproject.com/help

Closing this report for now as it is not actionable.
