### ISSUE TITLE
ideas.obsproject.com is completely unusable without JS

### ISSUE THREAD

**Issue by KOLANICH** [obsproject/obs-studio#3611]
## Platform
Operating system and version: Firefox Web Browser with NoScript in JS-blocking mode
OBS Studio version: Any

## Expected Behavior
Unable to send a feature request.

## Current Behavior
New Issue suggests me to use `ideas.obsproject.com`, which requires JavaScript.

## Steps to Reproduce
1. https://ideas.obsproject.com

## Additional information

The proposed way to fix it is to use GitHub for feature requests too. I don't want to register on ideas.obsproject.com and I am not going to enable JavaScript. For me it is more convenient to use GitHub for that. GitHub is proprietary, but it is more privacy-friendly than for example gitlab.com and standalone installations of GitLab, since JS here is not mandatory.

**Comment by WizardCM** [comment]
There are no plans on listing feature requests on the GitHub Issues page, and as this isn't an issue with OBS itself, I'm closing it.

Additionally, for issues with Fider, you can find their repo here - https://github.com/getfider/fider - however, it looks like Fider is no longer actively maintained. I guess keep an eye out to see what we end up doing.

**Comment by dodgepong** [comment]
Github also lacks the ability to vote on ideas and then sort on those votes, so it becomes difficult to gauge the interest level for a given feature.
