### ISSUE TITLE
Audio setting Channels=Mono causes audible click at each pause of recording

### ISSUE THREAD

**Issue by mgkuhn** [obsproject/obs-studio#3614]
## Platform

Operating system and version: Ubuntu Linux 18.04, 20.04
OBS Studio version: 26.0.2, 28.0.3

## Expected Behavior

There should be no audible artefact in a "Channels: Mono" recording at the point where the recording was paused.

## Current Behavior

There is a brief audible audio distortion (a loud, sharp click) almost each time the recording is paused, but only when under Settings I have selected "Channels: Mono": https://www.cl.cam.ac.uk/~mgk25/volatile/mono-pause-clicks.mkv

For comparison, the problem does not occur in a very similar recording made with the setting "Channels: Stereo": https://www.cl.cam.ac.uk/~mgk25/volatile/stereo-pause-noclicks.mkv

## Steps to Reproduce

1. Start from a virgin configuration:
```
$ mv .config/obs-studio ~/obs-studio.saved
$ obs
```
2. In the auto-configuration wizard, select "Optimize just for recording", leave the default for other questions.
3. Go to Settings | Audio | Channels and select "Mono". Press Ok and Yes to restart.
4. Start recording, click yes to a warning about the lack of a video source, say five times "test" into a microphone (e.g. Yeti Blue), each time followed by pausing the recording for about one second (by clicking the pause symbol right of the "Stop Recording" button, then say "stop".
5. Listen to the resulting example recording at
https://www.cl.cam.ac.uk/~mgk25/volatile/mono-pause-clicks.mkv for example using `vlc` or `mplayer`. Four of the five pauses resulted in a loud sharp artifact (much louder than the acoustic click from the mouse button).

The microphone used was a Yeti Blue (cardioid mode), 48 kHz, 16-bit, USB 2.0, configured in PulseAudio Volume Control in the "Analog Stereo Duplex" profile.

**Comment by RytoEX** [comment]
I'm unable to reproduce this on Windows 10 with OBS Studio 28.0.3. Please retest this on OBS Studio 28.0.3 (or newer). If this is still an issue, then we can consider reopening this or opening a new Issue.

**Comment by mgkuhn** [comment]
@RytoEX I've just retested and immediately reproduced this issue with OBS Studio 28.0.3 on Ubuntu Linux 20.04. Please reopen this issue as there still hasn't been any progress yet.

**Comment by RytoEX** [comment]
> @RytoEX I've just retested and immediately reproduced this issue with OBS Studio 28.0.3 on Ubuntu Linux 20.04. Please reopen this issue as there still hasn't been any progress yet.

Please provide a log file. Please also ensure that when you pause and unpause, that you are not producing an audible mouse-click that is picked up by the mic.

Did you test this with the PPA build or with the Flatpak build? Could you test with both?

cc: @kkartaltepe @GeorgesStavracas Could this be specific to one of the Linux audio systems or a Linux platform dependency?

**Comment by mgkuhn** [comment]
> Did you test this with the PPA build or with the Flatpak build?

Tested with package `obs-studio` version `28.0.3-0obsproject1~focal` from PPA repo at http://ppa.launchpad.net/obsproject/obs-studio/ubuntu

**Comment by mgkuhn** [comment]
It's definitely not an acoustic pickup: the control experiment in stereo never had this problem.

**Comment by mgkuhn** [comment]
> Please provide a log file.

Here are the two log files from the experiment (two because changing audio settings to mono causes OBS Studio to restart the application). 
[2022-10-17 13-44-01.txt](https://github.com/obsproject/obs-studio/files/9800645/2022-10-17.13-44-01.txt) (initial startup, change setting to mono)
[2022-10-17 13-45-06.txt](https://github.com/obsproject/obs-studio/files/9800644/2022-10-17.13-45-06.txt) (record from microphone with five pauses)

The resulting recording is at https://www.cl.cam.ac.uk/~mgk25/volatile/2022-10-17%2013-46-20.mkv

**Comment by RytoEX** [comment]
Could you please re-test in OBS Studio 30.1.1 or newer? I primarily work on Windows, but perhaps a new report will spur someone on Linux to investigate further.

**Comment by Fenrirthviti** [comment]
Closing as stale. If this is still an issue please open a new issue with updated reproduction steps on the latest version of OBS.
