### ISSUE TITLE
OBS 26.0.2  on MacOS drawing unchanging pixels

### ISSUE THREAD

**Issue by snicolai** [obsproject/obs-studio#3615]
Using Quartz Debug (an Apple developer tool) you can turn on yellow rectangles over the areas that have been drawn recently.  The setting is "Flash screen updates"

Quartz Debug is not shipped with Xcode but can be downloaded and installed via the Xcode -> Open Developer Tool -> More Developer Tools.. menu.  There is also an OpenGL Profiler that might be interesting to run as well in the download.

Redrawing these unchanging pixels uses extra memory bandwidth that could be used for something else, slowing down OBS.

## Platform

MacOS Mojave (10.14.6 (18G6032)  (All the current supplemental updates)
OBS 26.0.2

## Expected Behavior

OBS should only draw the needed areas on the screen.  The gray bars either above and below Previews or to the left and right of them should not be redrawn.

In the Audio Mixer panel, only the actual sound meter(s) and other changes should be redrawn, not the whole panel.

## Current Behavior

Quartz Debug shows yellow rectangles on the places being redrawn.  See the two photos, one with "Flash screen updates" turned on, and one with it turned off so you can see what was being drawn.

![Flash screen updates on](https://user-images.githubusercontent.com/2096194/96203944-b681cb00-0f28-11eb-9965-a3e5856be384.jpg)
![Flash screen updates off](https://user-images.githubusercontent.com/2096194/96203956-c0a3c980-0f28-11eb-8160-e2db01d2e716.jpg)

In these photos, there are gray bars above and below the the Preview and Program views that are getting redrawn, and quite a bit of very dark pixels in the bottom of the Audio Mixer panel.

## Steps to Reproduce

1.  Start up OBS in Studio mode with two different video sources being viewed.
2.  Download and run Quartz Debug
3.  Check "Flash screen updates"
4.  See unchanging pixels being redrawn

**Comment by kkartaltepe** [comment]
The github issues are for bug reports. If you are interested in improving performance feel free to submit a PR with changes to that effect. If you notice severe performance regressions between versions feel free to report on the difference observed and why you think they are severe.
