### ISSUE TITLE
OBS 26 not seeing Intel HD Graphics as usable

### ISSUE THREAD

**Issue by aihngel** [obsproject/obs-studio#3620]
Quicksync shows up for decoder/encoder, but forces use of discrete graphics for program and uses discrete for decoder/encorder anyhow.

Can we get an option to force OBS window to run on a certain card also?

**Comment by derrod** [comment]
Do not remove the issue template, it also sounds more like a support question than an actual issue. Please see https://obsproject.com/help for that.
