### ISSUE TITLE
Note: If you are using NVENC or AMD encoders, make sure your video drivers are up to date.

### ISSUE THREAD

**Issue by icomputo** [obsproject/obs-studio#3623]
Note: If you are using NVENC or AMD encoders, make sure your video drivers are up to date.

OSB 26.0.2
openSUSE Leap 15.2
Linux 5.3.18-lp152.44-default x86_64
MATE 1.24.0
AMD Ryzen 5 3400G with Radeon Vega Graphics

With the old version of OBS it worked fine. OBS 24.0.6 (linux)
LOG: https://obsproject.com/forum/attachments/2020-10-16-08-04-59-txt.62113/

Update:
---------
Update the kernel and the problem continues
Kernel Linux 5.8.15-1
LOG: https://obsproject.com/forum/attachments/2020-10-17-11-29-27-txt.62162/

**Comment by dodgepong** [comment]
Do not delete the issue template. At no point in your post did you actually describe the problem you are having.

But even then, this does not sound like a bug report but a support request. Please use the forums or Discord for support: https://obsproject.com/help
