### ISSUE TITLE
[BUG]Note: If you are using NVENC or AMD encoders, make sure your video drivers are up to date.

### ISSUE THREAD

**Issue by icomputo** [obsproject/obs-studio#3628]
## Platform

Operating system and version:openSUSE 15.2
OBS Studio version:26.0.2

## Expected Behavior

when wanting to record the error appears: Note: If you are using NVENC or AMD encoders, make sure your video drivers are up to date. 
## Current Behavior

LOG: https://obsproject.com/forum/attachments/2020-10-16-08-04-59-txt.62113/
## Steps to Reproduce

1. https://susepaste.org/images/92975827.png
2. https://susepaste.org/images/49178195.png
3.
4.

## Additional information

Linux 5.3.18-lp152.44-default x86_64
MATE 1.24.0
AMD Ryzen 5 3400G with Radeon Vega Graphics
With the old version of OBS it worked fine. OBS 24.0.6 (linux)
-----
Update the kernel and the problem continues
Kernel Linux 5.8.15-1
Log: https://obsproject.com/forum/attachments/2020-10-17-11-29-27-txt.62162/

**Comment by Fenrirthviti** [comment]
Please use the forums or Discord for support.

**Comment by icomputo** [comment]
Seriously? Don't you think this is a bug? if in previous versions I had no problems

**Comment by Fenrirthviti** [comment]
Given the log, there is an issue with your local x264 installation, or with the third party repo (assuming you're not compiling yourself). It's unlikely anything in our update caused this. Please use the support forums or Discord for further assistance.

**Comment by Fenrirthviti** [comment]
```
11:30:10.919: [x264 encoder: 'simple_h264_recording'] invalid crop-rect 0,0,-1,2
11:30:10.919: 
11:30:10.919: [x264 encoder: 'simple_h264_recording'] x264 failed to load 
```

**Comment by icomputo** [comment]
yes, it was installed from the packman repository, the same as recommended in the obs project wiki
Thanks for your information, I will compile myself obs, to see if that is the problem

**Comment by icomputo** [comment]
I compiled the source, and it worked fine

**Comment by Fenrirthviti** [comment]
Thanks for confirming! I would recommend reporting the error to the packman manager for the obs-studio package.
