### ISSUE TITLE
Copy-pasting multiple sources between scenes pastes both in the same spot instead of inheriting original source's position

### ISSUE THREAD

**Issue by matoi974** [obsproject/obs-studio#3632]
## Platform

Operating system and version: Windows 10 2004
OBS Studio version:26.0.2

## Expected Behavior
Both sources should be pasted at their original positions.

## Current Behavior
Both sources are pasted in the same spot - presumably the one that's the highest in the sources list - instead of being pasted at the same spot they were in the other scene. Same behaviour with "Paste(Reference)" and "Paste(Duplicate)".

## Steps to Reproduce

1. Create two text sources, move them to different spots
2. Click on one of them in the Sources list, hold Ctrl, click on the other, release Ctrl
3. Ctrl+C, switch to a different scene, Ctrl+V

## Additional information
Screenshots below. It also seems that my scaling settings are not copied over, I'll report that too.

![image](https://user-images.githubusercontent.com/63289008/96396729-43ef4480-11e1-11eb-93af-a78b05d53f5e.png)

![image](https://user-images.githubusercontent.com/63289008/96396745-4e114300-11e1-11eb-893c-29c99920fb3c.png)

**Comment by maxdrash** [comment]
Reproduced on 26.0.2-0obsproject1~focal.
