### ISSUE TITLE
Built-in virtual camera does not work with OpenCV

### ISSUE THREAD

**Issue by upgradeQ** [obsproject/obs-studio#3635]
## Platform

Operating system and version: Windows 7 64 bit
OBS Studio version: 26.0.2 64 bit
Python version: Python 3.6 64 bit

## Expected Behavior

Built-in virtual camera should be usable with [OpenCV python package](https://pypi.org/project/opencv-python/)

## Current Behavior
OpenCV window shows black screen if `OBS Virtual Camera` is selected.

## Steps to Reproduce

1. Start virtual camera
2. Run `check_cv.py` 

## Additional information
Black screen 
![screenshot](https://i.imgur.com/uUwA1cz.png)
However OpenCV works with [obs-virtual-cam](https://github.com/Fenrirthviti/obs-virtual-cam) plugin, if `OBS-Camera` is selected.
![screenshot](https://i.imgur.com/N72DAdm.png)
Code used to check it:
```python
# check_cv.py

import numpy as np
import cv2 as cv

def check_cam_by_index(i):
    cap = cv.VideoCapture(i)
    cap.set(cv.CAP_PROP_FRAME_WIDTH, 1280)
    cap.set(cv.CAP_PROP_FRAME_HEIGHT, 720)

    if not cap.isOpened():
        print("Cannot open camera")
        exit()
    while True:
        # Capture frame-by-frame
        ret, frame = cap.read()
        # if frame is read correctly ret is True
        if not ret:
            print("Can't receive frame (stream end?). Exiting ...")
            break
        cv.imshow('frame',frame)
        if cv.waitKey(1) == ord('q'):
            break
    # When everything done, release the capture
    cap.release()
    cv.destroyAllWindows()


def check_multiple():
    for i in range(-1,10):
        try:
            print(f'checking camera #{i}')
            check_cam_by_index(i)
        except:
            continue

#check_multiple() # 2 is index of OBS Virtual Camera , 0 is index of OBS-Camera
check_cam_by_index(2) 
```

I've tried reinstalling OBS, virtual cam drivers, running it as admin - same result.

Also, built-in virtual webcam is accessible from [imageio](https://github.com/imageio/imageio/blob/master/docs/examples.rst#grab-frames-from-your-webcam) by index, but with high CPU usage.

**Comment by Fenrirthviti** [comment]
Sounds like OpenCV doesn't support NV12 format. Might need to check with their developers first.

**Comment by WizardCM** [comment]
Hi there, could you confirm if this is fixed in [OBS 26.1.0 RC2](https://github.com/obsproject/obs-studio/releases/tag/26.1.0-rc2)? Thanks!

**Comment by upgradeQ** [comment]
No, it is still black.

**Comment by Unmoon** [comment]
Also seeing this issue, both laptop webcam and obs-virtualcam plugin work, but built-in virtual camera returns a black image with some glitches at the top.

Windows 10 Pro Build 19041 64bit
OBS 26.0.2 64bit
OBS 26.1 RC2
Python 3.7.6 64bit
\- opencv-python 3.4.11.45
\- numpy 1.19.3

```python
import cv2

camera = cv2.VideoCapture(0)

while cv2.waitKey(1) != 27:
    _, image = camera.read()
    cv2.imshow("", image)
```
Built-in:
![image](https://user-images.githubusercontent.com/7273082/101778658-d1258a00-3afc-11eb-90fc-65799ddbdc88.png)
Plugin:
![image](https://user-images.githubusercontent.com/7273082/101778682-dc78b580-3afc-11eb-8efb-40bd90a0f3e7.png)

**Comment by TheGuy920** [comment]
@Unmoon , I too have experienced the same thing, lucky, after searching for a solution, the plugin option was not too bad

**Comment by devedse** [comment]
I'm experiencing the same issue. It would be nice if there's a bit more configurability for the built in virtual camera of OBS. E.g. specify the output format.

**Comment by sergorl** [comment]
Is somebody who find solution?

**Comment by letmaik** [comment]
Reported here: https://github.com/opencv/opencv/issues/19746

**Comment by qinst64** [comment]
> Sounds like OpenCV doesn't support NV12 format. Might need to check with their developers first.

Version 26.1.1 does not work either. Under setting-advanced, If I switch the video setting from `NV12` to others like `RGB`, `I420`... no luck though

**Comment by mkoeda** [comment]
This thread may help you.

How to get virtual Camera Data using opencv？ | OBS Forums https://obsproject.com/forum/threads/how-to-get-virtual-camera-data-using-opencv%EF%BC%9F.137113/

**Comment by bmox** [comment]
When I'm using obs virtual camera using opencv python I got an greay screen. Any solution ?

**Comment by AntumArk** [comment]
> This thread may help you.
> 
> How to get virtual Camera Data using opencv？ | OBS Forums https://obsproject.com/forum/threads/how-to-get-virtual-camera-data-using-opencv%EF%BC%9F.137113/

It did help, though it would be great if the camera could be set up from console.

**Comment by DavraYoung** [comment]
Same problem, cannot read buildin obs virtual camera from python opencv 4.5.4, windows 11.
![image](https://user-images.githubusercontent.com/33338429/147841612-49b0b916-b4d2-4095-b14e-4986b9e7fbe0.png).
Tried to change VideoCapture backend api to DirectShow, still no luck(

**Comment by RazvanCristian** [comment]
I encountered the same problem using:
- Windows 10 19042.1415
- OBS 27.1.3 (64 bit)
- opencv 4.5.4.60

![image](https://user-images.githubusercontent.com/34897183/147864684-41c5c585-1dbd-449d-8eda-33116dc1803f.png)

**Comment by aliencaocao** [comment]
Still same issue OBS 27.1.3 (64 bit) and opencv 4.5.5 on windows 10

**Comment by KarthikRaja2k1** [comment]
Found any solutiions?

**Comment by KarthikRaja2k1** [comment]
yes

**Comment by Avasam** [comment]
Worth nothing OpenCV does give the following warning with the built-in Virtual Camera: `[swscaler @ 000001c8f0633040] Warning: data is not aligned! This can lead to a speed loss`

**Comment by DavraYoung** [comment]
still waiting....

**Comment by Fenrirthviti** [comment]
This is almost definitely going to be something that needs to be reported to the OpenCV developers or whatever library is being used for them to provide support. I'd recommend that anyone having the issue reach out to them, and if there is any new information that points to a bug on our end (which it doesn't seem to be at present, but more that the libraries don't support the formats we use for our virtual cam), we can reopen this.

**Comment by ManuGraiph** [comment]
Any news on this?

**Comment by upgradeQ** [comment]
I've stumbled upon this [project](https://github.com/makifoxgirl/MakiScreen) its uses FFMPEG on udp socket to transfer mjpeg stream over local network,thanks to this helpful SO [answer](https://stackoverflow.com/a/50917584) the code goes as follows:
```python
import cv2
cap = cv2.VideoCapture('udp://127.0.0.1:10800',cv2.CAP_FFMPEG)
if not cap.isOpened():
    print('VideoCapture not opened')
    exit(-1)

while True:
    ret, frame = cap.read()

    if not ret:
        print('frame empty')
        break

    cv2.imshow('image', frame)

    if cv2.waitKey(1)&0XFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()
```
Click yes to allow local access to this port 10800.  

FFMPEG string, qscale 0 - 31 to control quality.  
```terminal
.\ffmpeg.exe -y -f dshow -thread_queue_size 4096 -hwaccel cuda -hwaccel_output_format cuda -i video="OBS Virtual Camera" -f rawvideo -c:v mjpeg -qscale:v 0 -r 120 udp://127.0.0.1:10800
```

I've tested it on 1280x720 with 120 FPS, there is like .1 sec delay

P.S.

There will big update (28.1+) in OBS Studio [later this year](
https://web.archive.org/web/20221013195929/https://www.nvidia.com/en-us/geforce/news/rtx-40-series-and-studio-updates-for-content-creation/)
As of July 31 [this](https://github.com/obsproject/obs-studio/pull/3327) related pull request(game bar integration with texture sharing IPC) has been set to 28.1 or 29 version by @gxalpha, though works on [in-game overlay](https://ideas.obsproject.com/posts/5/allow-obs-to-provide-in-game-overlay) has been stalled for unknown time.

**Comment by ManuGraiph** [comment]
> I've stumbled upon this [project](https://github.com/makifoxgirl/MakiScreen) its uses FFMPEG on udp socket to transfer mjpeg stream over local network,thanks to this helpful SO [answer](https://stackoverflow.com/a/50917584) the code goes as follows:
> 
> ```python
> import cv2
> cap = cv2.VideoCapture('udp://127.0.0.1:10800',cv2.CAP_FFMPEG)
> if not cap.isOpened():
>     print('VideoCapture not opened')
>     exit(-1)
> 
> while True:
>     ret, frame = cap.read()
> 
>     if not ret:
>         print('frame empty')
>         break
> 
>     cv2.imshow('image', frame)
> 
>     if cv2.waitKey(1)&0XFF == ord('q'):
>         break
> 
> cap.release()
> cv2.destroyAllWindows()
> ```
> 
> Click yes to allow local access to this port 10800.
> 
> FFMPEG string, qscale 0 - 31 to control quality.
> 
> ```
> .\ffmpeg.exe -y -f dshow -thread_queue_size 4096 -hwaccel cuda -hwaccel_output_format cuda -i video="OBS Virtual Camera" -f rawvideo -c:v mjpeg -qscale:v 0 -r 120 udp://127.0.0.1:10800
> ```
> 
> I've tested it on 1280x720 with 120 FPS, there is like .1 sec delay
> 
> P.S.
> 
> There will big update (28.1+) in OBS Studio [later this year](https://web.archive.org/web/20221013195929/https://www.nvidia.com/en-us/geforce/news/rtx-40-series-and-studio-updates-for-content-creation/) As of July 31 [this](https://github.com/obsproject/obs-studio/pull/3327) related pull request(game bar integration with texture sharing IPC) has been set to 28.1 or 29 version by @gxalpha, though works on [in-game overlay](https://ideas.obsproject.com/posts/5/allow-obs-to-provide-in-game-overlay) has been stalled for unknown time.

I tried that solution and i can get 33 frames out of the cam video, after that, it only gets empty frames.

**Comment by jasperan** [comment]
Has this issue been fixed?

**Comment by Fenrirthviti** [comment]
As far as I know, nobody has reached out to OpenCV to report the issue. If you're looking for movement, I would suggest reaching out to them for them to take a look at why they don't support our virtual device.

**Comment by Avasam** [comment]
> As far as I know, nobody has reached out to OpenCV to report the issue. If you're looking for movement, I would suggest reaching out to them for them to take a look at why they don't support our virtual device.

https://github.com/obsproject/obs-studio/issues/3635#issuecomment-803199045

You can go upvote it: https://github.com/opencv/opencv/issues/19746

**Comment by jasperan** [comment]
I can't stress the lengths which I've crossed trying to work around this bug / low priority feature.

If anyone is interested, I tried both Windows 10 & 11, and Windows 11 works for some reason, Windows 10 instead gave me very painful encoding issues with the virtualized camera inputs

12 days have passed since New Years and I feel like I aged a year

**Comment by aramg** [comment]
Try the DroidCam Virtual Output plugin, or the OBS v28 build of the original obs-virtual-cam plugin mentioned in the above issue reference.

**Comment by jasperan** [comment]
@aramg I did try the OBS v28 plugin but somehow this didn't fix my problem. It's fine though, I'll resort to other ways for getting screen input

**Comment by ByPikod** [comment]
Still same problem. Also my computer slowing down while viewing obs virtualcam output.
![resim](https://user-images.githubusercontent.com/46069238/213924937-5096af20-5223-4f04-9a4d-60daca9b4941.png)

**Comment by Avasam** [comment]
https://github.com/opencv/opencv/issues/19746#issuecomment-1383056787

> > Faulting module name: obs-virtualcam-module64.dll, version: 29.0.0.0, time stamp: 0x63b8a352
> 
> This is not a part of OpenCV actually:
> 
> > obs-virtualcam-module64.dll
> 
> [...]
> 
> Just to clarify, OBS built-in virtual camera uses DirectShow API for virtual camera (CAP_DSHOW), which is deprecated in OpenCV in favor of Microsoft Media Foundation (CAP_MSMF) backend (about 4+ years ago, before OpenCV 4.0). So, due to deprecation there are no plans to significantly rework DSHOW backend. Also, due to deprecation "acceptable fix" is a 2-5 lines disabler of this unsupported case (but this can't satisfy OBS users) to avoid breaking of existed code.
> 
> Perhaps, problem is that `SetFormat()` doesn't fail on this line (`hr=0` / S_OK) during request of `RGB24` format: [`4.7.0`/modules/videoio/src/cap_dshow.cpp#L2618 (blame)](https://github.com/opencv/opencv/blame/4.7.0/modules/videoio/src/cap_dshow.cpp#L2618)
> 
> After that in debug mode these errors are reported: `ERROR: SampleCB() - buffer sizes do not match` (this is a case if format is not changed properly)
> 
> Forcing ["native"](https://github.com/obsproject/obs-studio/blob/27.2.4/plugins/win-dshow/virtualcam-module/virtualcam-filter.hpp?rgh-link-date=2023-01-15T04%3A59%3A46Z#L12-L13) resolution of OBS camera crashes the process (by default OpenCV DSHOW backend requests 640x480):
> 
> ```
>     capture.set(CAP_PROP_FRAME_WIDTH, 1920);
>     capture.set(CAP_PROP_FRAME_HEIGHT, 1080);
> ```
> 
> WinDbgX shows this stacktrace of the crash (from non-main thread):
> 
> ```
> [0x0]   obs_virtualcam_module64!memcpy_repmovs + 0xe   
> [0x1]   obs_virtualcam_module64!VCamFilter::Frame + 0x1b5   
> [0x2]   obs_virtualcam_module64!VCamFilter::Thread + 0x24b   
> [0x3]   obs_virtualcam_module64!std::thread::_Invoke<std::tuple<<lambda_4e6f779957cbddf8fba6c1db701dac17> >,0> + 0x11   
> [0x4]   obs_virtualcam_module64!thread_start<unsigned int (__cdecl*)(void *),1> + 0x5a   
> [0x5]   KERNEL32!BaseThreadInitThunk + 0x14   
> [0x6]   ntdll!RtlUserThreadStart + 0x21   
> ```
> 
> with `r8d` "size" register value: `0x00000000007e9000` (or 8294400).
> 
> RGB24 frame size is `1920*1080*3 = 6220800` (this is requested) RGB32 frame buffer size is `1920*1080*4 = 8294400` (this value we see during the crash)
> 
> So, looks like format is not switched to RGB24 properly.
> 
> I would blame on this OBS code with `IAMStreamConfig::SetFormat` method implementation which ignores passed input and returns S_OK **unconditionally**:
> 
> [obsproject/libdshowcapture@`2fa2e48`/source/output-filter.cpp#L346-L363](https://github.com/obsproject/libdshowcapture/blob/2fa2e488b7dc4a266eb8f5be56ced626e39a6159/source/output-filter.cpp#L346-L363)
> 
> `IAMStreamConfig::SetFormat` documentation and expected behavior: [learn.microsoft.com/en-us/windows/win32/api/strmif/nf-strmif-iamstreamconfig-setformat](https://learn.microsoft.com/en-us/windows/win32/api/strmif/nf-strmif-iamstreamconfig-setformat)

**Comment by NicoDeLarge** [comment]
I had trouble with the built in virtual cam in OBS v28 as well and the only solution I found was downgrading to [25.0.8](https://github.com/obsproject/obs-studio/releases/tag/25.0.8) and using [OBS Virtualcam 2.0.5](https://obsproject.com/forum/resources/obs-virtualcam.949/).

The root cause up to my analysis, is that the built-in virtual cam is [hard coded to use NV12](https://github.com/obsproject/obs-studio/blob/master/plugins/win-dshow/virtualcam-module/virtualcam-filter.cpp#L22) as output format for the direct show filter, but my system (Windows 10 22H2) does not have an appropriate built in downstream DirectShow filter, that converts NV12 to some RGB format, which is required in my case for the renderer. 

This can also be observed when using the [graphedit](https://learn.microsoft.com/en-us/windows/win32/directshow/using-graphedit) tool from the windows SDK, when dragging the "Video Capture Sources" -> "OBS Virtual Camera" to the filter graph, right-clicking on its ouput pin and selecting "Render Pin". This prompts an error, that no appropriate graph could be build to render.

In contrast to the build in virtual camera, the OBS Virtualcam 2.0.5 uses [YUY2](https://github.com/Fenrirthviti/obs-virtual-cam/blob/master/src/virtual-source/virtual-cam.cpp#L288) as video format. And for that configuration my DirectShow automatically finds a filter graph to convert to render the data.

<img src="https://user-images.githubusercontent.com/50635207/229901308-9cf02b36-4f0c-4653-90c0-aacd8228b394.png" width="250">

<img src="https://user-images.githubusercontent.com/50635207/229899866-a54546e8-3719-4948-86e5-02ee48861dfa.png" width="250">

<img src="https://user-images.githubusercontent.com/50635207/229901013-4bffcece-bbf9-4feb-9cfa-ccd66c3cd94b.png" width="350">

**Comment by Avasam** [comment]
> I had trouble with the built in virtual cam in OBS v28 as well and the only solution I found was downgrading to 25.0.8 [...]

If you don't wanna have to downgrade OBS, checkout https://github.com/Avasam/obs-virtual-cam/releases . 
It is only a bandaid fix though, OBS needs to fix w/e is wrong with their DirectShow cam and/or support MediaFoundation.

**Comment by Fenrirthviti** [comment]
We would certainly welcome any PRs from someone who understands the changes necessary, or at least can explain clearly what the problem is and what we'd need to change. It will probably be some time before we investigate MF support, however.

A lot of the issue here is lack of resources and interest in the problem in general, just to be honest. As this doesn't affect a lot of users, and the issue isn't really obvious (and is probably far from simple) it's hard to prioritize it over more important bug fixes and feature updates when it comes to allocating the handful of developers who are full time on the project.

That said, I'm happy to reopen if others are interested in investigating this.

**Comment by Fenrirthviti** [comment]
As an additional note, we do (should) support YUY2 output: https://github.com/obsproject/obs-studio/commit/18a73c9a45c77aaf9349dc1e6bad6643f501d3ea

**Comment by NicoDeLarge** [comment]
Thats good indeed. However, the VideoFormat is [set to NV12 in the VCamFilter](https://github.com/obsproject/obs-studio/blob/3840f92777a1e66a67dc20eb1c28b54f83e8968d/plugins/win-dshow/virtualcam-module/virtualcam-filter.cpp#L22), which does not tickle down to OutputPin during construction in first place, but then [NV12 is set as VideoFormat](https://github.com/obsproject/obs-studio/blob/3840f92777a1e66a67dc20eb1c28b54f83e8968d/plugins/win-dshow/virtualcam-module/virtualcam-filter.cpp#L99) in VCamFilter constructor for the OutputPin. So finally OutputPin has a MediaFormat based on NV12.

And when it now comes to the media type negotation between the VCamFilter (or its OutputPin) and the downstream filter input pin, the Connect method of OutputPin only succeeds, [if the input pin accepts NV12 during the ReceiveConnection call](https://github.com/obsproject/libdshowcapture/blob/bac23f2ca01b712b9740c6a3822d32c134ab6325/source/output-filter.cpp#L110).

To overcome that, instead of trying just the NV12 based MediaFormat, OutputPin could iterate within the Connect method over its mtList, check if the requested pmt is in mtList and making the ReceiveConnection call with the matching MediaType. 

If this succeeds, then I guess the SetVideoFormat should be called to update the OutputPin, so that [this](https://github.com/obsproject/obs-studio/blob/master/plugins/win-dshow/virtualcam-module/virtualcam-filter.cpp#L298) triggers.

**Comment by gottagofaster236** [comment]
FYI, https://github.com/opencv/opencv/pull/23460 got merged. It probably should've used NV12 directly, though.

**Comment by RytoEX** [comment]
> FYI, [opencv/opencv#23460](https://github.com/opencv/opencv/pull/23460) got merged. It probably should've used NV12 directly, though.

Feel free to open another PR against OpenCV that does that, if you like. Given that the OpenCV Issue is closed, we will likely consider this Issue resolved and close it out as well.

**Comment by gottagofaster236** [comment]
> > FYI, [opencv/opencv#23460](https://github.com/opencv/opencv/pull/23460) got merged. It probably should've used NV12 directly, though.
> 
> Feel free to open another PR against OpenCV that does that, if you like. Given that the OpenCV Issue is closed, we will likely consider this Issue resolved and close it out as well.

SetFormat() returning S_OK unconditionally (which does not comply to the DShow spec) still has to be fixed, that's the reason OpenCV broke in the first place.

**Comment by RytoEX** [comment]
> > > FYI, [opencv/opencv#23460](https://github.com/opencv/opencv/pull/23460) got merged. It probably should've used NV12 directly, though.
> > 
> > 
> > Feel free to open another PR against OpenCV that does that, if you like. Given that the OpenCV Issue is closed, we will likely consider this Issue resolved and close it out as well.
> 
> SetFormat() returning S_OK unconditionally (which does not comply to the DShow spec) still has to be fixed, that's the reason OpenCV broke in the first place.

Sure, I don't disagree. However, the scope of this Issue is "Built-in virtual camera does not work with OpenCV". That would seem to no longer the case once OpenCV 4.8.0 is released.

**Comment by gottagofaster236** [comment]
> > FYI, [opencv/opencv#23460](https://github.com/opencv/opencv/pull/23460) got merged. It probably should've used NV12 directly, though.
> 
> Feel free to open another PR against OpenCV that does that, if you like. Given that the OpenCV Issue is closed, we will likely consider this Issue resolved and close it out as well.

https://github.com/opencv/opencv/pull/23469 is merged now. 
I guess that's about all that could be done from the OpenCV side of things.

**Comment by RytoEX** [comment]
Sounds like this is solved in OpenCV then.

**Comment by Avasam** [comment]
Once the next version of OpenCV-Python comes out I'll test their fix and report if it works for me.

Whilst I'm very glad that they did and accepted @gottagofaster236  's patch, I agree that OpenCV shouldn't have to special case the OBS Virtual Camera and that there's still an underlying issue that needs to be fixed here.

Assuming a working patch in OpenCV 4.8, it does make sense to close this issue given its scope and I'll be satisfied with that. As long as another is open for:

> SetFormat() returning S_OK unconditionally (which does not comply to the DShow spec) still has to be fixed, that's the reason OpenCV broke in the first place.

**Comment by RytoEX** [comment]
> Assuming a working patch in OpenCV 4.8, it does make sense to close this issue given its scope and I'll be satisfied with that. As long as another is open for:
> 
> > SetFormat() returning S_OK unconditionally (which does not comply to the DShow spec) still has to be fixed, that's the reason OpenCV broke in the first place.

That is my stance, yes. This Issue as written has a resolution. Someone shouldn't have to wade through 40+ comments here to get to the information about `SetFormat()`.

**Comment by DarkGamer209788** [comment]
I decided to use SplitCam instead, it works fine

**Comment by Avasam** [comment]
Tested opencv-python using the latest build artefacts, looks like their patch works. Just need to wait for an official release now.
![image](https://github.com/obsproject/obs-studio/assets/1350584/65311318-16bc-496d-8967-fe59c06b0849)

**Comment by agilebean** [comment]
> Tested opencv-python using the latest build artefacts, looks like their patch works. Just need to wait for an official release now. ![image](https://user-images.githubusercontent.com/1350584/243508020-65311318-16bc-496d-8967-fe59c06b0849.png)

can you please specify how you installed it?

**Comment by gottagofaster236** [comment]
OpenCV 4.8.0 with the fixes is out

**Comment by WizardCM** [comment]
Closing per the above. Feel free to comment with confirmation or disagreement based on experience. Thanks!

**Comment by Fenrirthviti** [comment]
As a note and final comment here, this issue is closed as the stated report of not working with OpenCV has been resolved by OpenCV.

However, our issue of not using SetFormat() properly is still ongoing, should anyone wish to open a new issue on that for tracking. It hasn't been fixed on our end just due to lack of time and resources for someone to take a look at it. PRs are, as always, welcome for fixes there.

**Comment by vietdoo** [comment]
> OpenCV 4.8.0 with the fixes is out
 I've been stuck for over 2 hours trying to upgrade it using "pip install --upgrade opencv-python==4.8.1.78."

**Comment by Avasam** [comment]
> I've been stuck for over 2 hours trying to upgrade it using "pip install --upgrade opencv-python==4.8.1.78."

If you have a problem installing a library, ask around on Python help forums, or raise an issue in the appropriate repository. https://github.com/opencv/opencv-python
There's nothing the OBS team can do about `opencv-python` having issues installing on your machine.

**Comment by iamkunal9** [comment]
Leaving a comment for anyone here: If you have any version smaller than 30.2.0, you will face the same issue. Updating to the latest version fixed this issue for me. I was using 30.0.0 and updated to 30.2.0, and the issue was resolved.

**Comment by GadgetNutt** [comment]
Not working for me with OpenCVSharp 4.11 and OBS 32.04
