### ISSUE TITLE
I have an issue where my application crashes with obs-virtualcam-module32.dll

### ISSUE THREAD

**Issue by jeremyheo-nsuslab** [obsproject/obs-studio#3636]
## Platform

Operating system and version:
Windows 10 Pro 1909 64bit 
OBS Studio version:
26.0.2

## Expected Behavior

An application crash occurred when I looked up the list of cameras on a PC with obs-virtualcam-module32.dll installed.

## Current Behavior

-- Exception Code Info 
`Unhandled exception at 0x6B00822A (obs-virtualcam-module32.dll) in eb1063f4-4d7a-4c9a-87d5-c5e6d8ebcfba.GGnet.exe.20201021045414.dmp: 0xC0000005: Access violation reading location 0x00000034.`

## Steps to Reproduce

1. My Application build with adobe air (action script)
2. Action Script API that  cause crash with obs-virtualcam-module32.dll
Error Occured --> `_cameraList = Camera.names.filter(filter);`

flash.media.Camera
https://help.adobe.com/ko_KR/FlashPlatform/reference/actionscript/3/flash/media/Camera.html#names

## Additional information

i attatched crash dump file.
[dump.zip](https://github.com/obsproject/obs-studio/files/5413988/dump.zip)

**Comment by WizardCM** [comment]
Hi there, could you confirm this is fixed in [OBS 26.1.0 RC2](https://github.com/obsproject/obs-studio/releases/tag/26.0.2)? Thanks!

**Comment by jeremyheo-nsuslab** [comment]
It works without crash in OBS 26.1.0 RC2. thanks!

**Comment by RytoEX** [comment]
Glad to hear it!  Closing this now.
