### ISSUE TITLE
Window Capture on Windows fails to capture two windows with exact same title

### ISSUE THREAD

**Issue by CodeYan01** [obsproject/obs-studio#3637]
## Platform

Operating system and version: Windows10.0 Build 19041 (release: 2004)
OBS Studio version: 26.0.2

## Expected Behavior

OBS should be able to capture two windows with the exact same title.

## Current Behavior

If two windows with same title exist, they are both listed in the window selection, but switching to either of them will only capture the window that was most recently focused. Selecting one of the windows then focusing on the other window will work for a while in OBS, but malfunctions when switching the window to be selected in the Properties dialog (switches to the most recently focused one). Note that even discarding the changes to the properties will not revert it to the previous window being captured.

## Steps to Reproduce

1. Open 2 Notepad windows.
2. Type 'abc' on one, 'def' on the other. Window titles will change to "*Untitled - Notepad". Make the 'def' one the last window you focused.
![Two Windows with same name](https://user-images.githubusercontent.com/65320293/96704451-b0776880-13c6-11eb-95ab-5d517eb79898.jpg)
3. Open OBS with a clean profile and scene collection.
4. Add a window capture.
5. Change the window to one of the Notepad windows (they have the same name). The one with 'def' will be captured
6. Optionally, click OK to confirm settings and change Properties again.
7. Change the window to the other Notepad window. The one with 'def' will still be the one to be captured. Click OK.
![Two Windows with same name obs](https://user-images.githubusercontent.com/65320293/96705756-46f85980-13c8-11eb-924c-f52ad2703e16.jpg)
8. Focus on the window with 'abc', type even more characters optionally.
9. Returning to OBS, the one with 'def' is still captured. Open its properties and switch to the other Notepad window.
10. The 'abc' Notepad will be the one to be captured, regardless of which option you pick.

## Additional information

This applies to other windows as well. Windows I have tried are: Notepad, File Explorer (go to same folder, have a different sorting order), and Zoom (second instance by running as different user, both using dual monitors, the second monitor will have the same window title).
It does not matter whether Automatic, BitBlt, or WGC is chosen, nor whether you click OK to save the properties. Not even capture cursor.
Tried saving Notepad file to 'test.txt', in different folders, and opening them, still the same.

**Comment by RytoEX** [comment]
Confirmed on Windows.

**Comment by jp9000** [comment]
This isn't a bug, this is a limitation of the operating system itself. In order to find a window, it uses the window class name and window title and tries to find the one that matches, therefore if you have two identical windows, it cannot differentiate between them because there's no other unique identifier. It's always been a problem and it'll always be a problem.

**Comment by alinsavix** [comment]
> there's no other unique identifier

This isn't actually the case, though, is it? Each window has its own unique window handle that could be used to differentiate between multiple otherwise-identical windows (right?). Yes, that would no longer apply once the specific windows being captured are closed, but that still seems far preferable to 'can never capture a second window at all, ever, which is the current state of things.

**Comment by mufunyo** [comment]
There's a unique HWND and also a unique PID. So during a session, it should be possible to differentiate between identically named windows, at least.

**Comment by Hicsy** [comment]
Occasionally, OBS will insist on displaying the wrong window, despite the above workaround.
 Plz consider changing OBS to correctly use HWND in Windows rather than whatever it's using now.
