### ISSUE TITLE
Remux Window Position Doesn't Account For Multiple Vertical Monitors. 

### ISSUE THREAD

**Issue by DanielLester83** [obsproject/obs-studio#3639]
## Platform 
Operating system and version: Windows 10
OBS Studio version: latest 

## Expected Behavior
The remux pop up window should be in the middle of the apps current monitor.

## Current Behavior
The remux window is on the bottom/top edge of 2 vertically aligned monitors. 

## Steps to Reproduce
1. Install at least 2 monitors to be vertically on top of each other, one directly above each other. (Full disclosure, I have 1 primary monitor on the left left side of the 2 vertical monitors) 
2. Place OBS Studio on the bottom monitor.
3. Trigger the remux pop up to appear.

**Comment by skeletonbow** [comment]
As a data point, I'm using Windows 10 here on an ASUS laptop, 1080p display built in, and an external monitor attached via mDP at 2560x1600 set up in a top/bottom configuration.  I tried to reproduce the report above with OBS on the bottom display (laptop) as well as on the top display and OBS properly centered the dialogue box for remux on the display it was running on.

Unable to reproduce here.  Should probably fill out more of the template including submitting log file and posting link here.
