### ISSUE TITLE
Livestream Audio garbled after update to 26.0.2

### ISSUE THREAD

**Issue by dangerous-e** [obsproject/obs-studio#3640]
## Platform

Operating system and version: Windows
OBS Studio version: 26.0.2

## Expected Behavior
 Have used OBS for livestreaming our house of worship for 2 years with no issues. PC setup using Black Magic ATEM TV Studio HD switcher and black magic capture card.
## Current Behavior
 We have garbled, unusable audio.
 https://obsproject.com/logs/Yju6Z8-QGBCvG-SR

## Steps to Reproduce

1.
2.
3.
4.

## Additional information

 Is there any way to rollback this version for Sunday Services?

**Comment by notr1ch** [comment]
This is not a complete bug report. Please use the forums or Discord for support.
