### ISSUE TITLE
Virtual Camera does not appear in BlueJeans Desktop app

### ISSUE THREAD

**Issue by frogcrush** [obsproject/obs-studio#3643]
## Platform

Operating system and version: Windows 10 2004 (19041.572)
OBS Studio version: 26.0.2

## Expected Behavior

OBS Virtual Camera should show up as an input device in BlueJeans Desktop

## Current Behavior

USB cameras appear, but not the OBS Virtual Camera

## Steps to Reproduce

1. Install OBS 26
2. Join a BlueJeans meeting using the desktop app
3. OBS Virtual Camera should appear as a camera option

## Additional information
OBS Virtual Camera is working and showing up in other applications. It also works properly if you join the meeting through Microsoft Edge, via their WebRTC interface.

**Comment by WizardCM** [comment]
If it does not show up in the list, either BlueJeans uses Media Foundation rather than DirectShow, or they have a allowlist and OBS isn't allowed.

**Comment by firstgear** [comment]
Same here, W10 using OBS 26.0.2 (64-bit) camera detected by Zoom, Webex, Teams, Chime, basically any conferencing software I came across last couple of months, but OBS camera not detected by BlueJeans Windows Client, only direct USB camera is detected by BlueJeans.

**Comment by frogcrush** [comment]
> If it does not show up in the list, either BlueJeans uses Media Foundation rather than DirectShow, or they have a allowlist and OBS isn't allowed.

After some decompilation, it uses both DirectShow and Media Foundation, and doesn't use an allowlist. It does skip adding virtual devices from the list, however.

**Comment by WizardCM** [comment]
In that case, this issue is on their side and I will close this issue. Thanks for digging into it!

**Comment by frogcrush** [comment]
What's odd though is it officially works with other virtual camera software like Snap Camera (https://www.bluejeans.com/blog/new-integrate-snap-camera-bluejeans-virtual-accessories-backgrounds) and supposedly also works with XSplit VCam without issue. Do those not show up as "virtual" devices?

**Comment by WizardCM** [comment]
Correct, Snap Camera installs a camera driver into `C:\Windows\System32\DRIVERS\SnapCameraVirtualDevice.sys`.

We have no plans on creating a virtual driver.
