### ISSUE TITLE
Sound being detected (but not heard) when hardware mute switch is activated

### ISSUE THREAD

**Issue by curya** [obsproject/obs-studio#3644]
## Platform

Operating system and version: Windows 10
OBS Studio version: 26.0.2

I have a microphone with a mute switch. When I mute it, OBS's audio mixer obviously doesn't detect any audio, right? BUT, if I put my mic right on my lips and talk, OBS _will_ detect audio in the audio mixer!
BUUUUT, it gets weirder. If I try to monitor the audio under those circumstances, I hear **nothing**!

Maybe my mute switch isn't technically a mute switch? Maybe it just lowers the volume or something? But if that's the case, why don't I hear any sound when monitoring, yet OBS detects a signal???

Something is wrong here...

EDIT: After some testing, I have discovered something. When talking normally with my mic right on my lips I get it about 45db in the audio mixer. This is with my mic muted with the mute switch. No audio can be heard at all when monitoring.
But, if I raise my voice and get up past 35db, I can then hear myself through OBS even though my mute switch is on.
Therefore, it seems that my mute switch is not a true mute switch. BUT it still raises certain OBS related issues. Why is OBS displaying 45db when I can't hear anything when monitoring? Why am I only able to hear it when it gets to 35db?

**Comment by Fenrirthviti** [comment]
Please use the forums or Discord for support.

In the future, if making a valid bug report, do not delete our template.
