### ISSUE TITLE
Encoding overload often appear on linux

### ISSUE THREAD

**Issue by gtaphash** [obsproject/obs-studio#3645]
## Platform
Operating system and version: ubuntu 20.04.01
OBS Studio version: 25.0.3+dfsg1-2 64bit

#### System
HP 15T-AU000 (energy star)
CPU: Intel® Core™ i3-6100U CPU
RAM: 6GB
Graphics: Intel® HD Graphics 520
Disk: 1TB

#### OBS Studio: Video
Base resolution: 1366x768
Output resolution: 1092x614
Downscale filter: Bicubic (sharpened scaling, 16 samples)
FPS values: 48

## Expected Behavior
I never have seen this for 2-3yrs even with higher fps while has windows 10 on that laptop. why happen that with ubuntu?

## Current Behavior
Encoding overloaded notification appear sometimes when start to record
(retry 1-2 times with new records then not appear for more minutes or hr)

Sometimes appear after 20-35min then i stop record and start new recording

## Steps to Reproduce
Record: screen capture (XSHM)
Record small size: window capture (xcomposite)
above sources doesn't use at same time and no audio source

**Comment by Fenrirthviti** [comment]
Please use the forums or discord for support.
