### ISSUE TITLE
MPC-HC's VMR-9 (window) can no longer be captured by game capture.

### ISSUE THREAD

**Issue by MoonLightRose** [obsproject/obs-studio#3646]
## Platform

Operating system and version: Windows 10 Home and Pro build 2004
OBS Studio version: 26.02 64bit windows(25.00 and above)

## Expected Behavior

The obs game capture captures the screen and the correct image flows.

## Current Behavior

When I capture a screen with obs game capture, it remains pitch black and does not capture the video.

## Steps to Reproduce

1.Set the output to VMR-9 (window) on the MPC-HC and play any video.
2.Importing MPC-HC with OBS STUDIO game capture
3.Make sure the screen is captured.
4.It should work correctly with obs 24.03; after 25.00 it does not work properly and is pitch black.

## Additional information

Starting from version 25.0 and above, VMR-9 game capture is no longer possible.
It was working in versions below 24.03.

This is what it looks like, specifically.
I used MPC-HC to make it a VMR-9 (Window) output, and imported it with game capture.
The advantage of this is that even if the MPC-HC window is small, the capture size could be done at the original size.
This was very useful because we could control playback on the small window MPC-HC and deliver it at full size on the delivery.

I'm hoping it will be fixed and work correctly as it did before 24.03.

Best regards.

**Comment by Fenrirthviti** [comment]
Have you rolled back to test on v24.0.3? The comments suggest that you are assuming the issue is OBS, but you have not actually tested. Can you please provide log files from both versions with an attempt to capture the window?

**Comment by matoi974** [comment]
Can confirm, MPC-HC v. 1.7.10.236 (d531d05), 64-bit captured correctly on v24.0.3 . Version 25.0.8 claims to have captured successfully in the log, but shows nothing on the canvas.
Log files:
v24.0.3 https://obsproject.com/logs/f-1cxCi--WcW2RNB
v25.0.8 https://obsproject.com/logs/vHa0L9sdcwgT3f10

**Comment by WizardCM** [comment]
I cannot verify this.

Doesn't work in 20.0.0, 24.0.3, 25.0.8 or 26.0.2. Running on Windows 10.

```
19:47:11.452: User added source 'Game Capture 2' (game_capture) to scene 'Scene 2'
19:47:14.662: [game-capture: 'Game Capture 2'] attempting to hook process: mpc-hc64.exe
19:47:14.705: [game-capture: 'Game Capture 2'] d3d9 shared texture capture successful
```

Older versions of OBS seem to set a super incorrect source size, whereas newer ones use a correct one. All report a successful capture, but nothing is rendered.

**Comment by RytoEX** [comment]
I can confirm that this does work in OBS Studio 24.0.3, and it does not work in OBS Studio 25.0.0-rc1. However, on my system (an Intel+NVIDIA laptop) it _only_ works if both OBS and MPC-HC are running on the iGPU. If MPC-HC runs on the NVIDIA GPU, it doesn't render anything. If MPC-HC is on the Intel iGPU and OBS is on the NVIDIA dGPU, MPC-HC renders a video, and OBS reports that it has hooked correctly, but it does not capture anything.

**Comment by RytoEX** [comment]
Bisected this to https://github.com/obsproject/obs-studio/pull/1871.

**Comment by Fenrirthviti** [comment]
Closing as stale. If this is still an issue please open a new issue with updated reproduction steps on the latest version of OBS.
