### ISSUE TITLE
System becomes laggy when OBS left open overnight

### ISSUE THREAD

**Issue by RedDragonWebDesign** [obsproject/obs-studio#3650]
## Platform
Operating system and version: Windows 7 Professional SP1
OBS Studio version: 26.0.2 (64 bit)

## Expected Behavior
Programs should open and/or maximize immediately when clicked.

## Current Behavior
If I leave OBS open overnight (not recording), and I come back to my computer in the morning, the entire computer has the following issues.

- Mouse works
- Cannot open any programs, including file Explorer and Task Manager, for about 1 minute
- Cannot maximize any minimized programs for about 1 minute
- After 1 minute, everything finally catches up, opens, maximizes, and goes back to normal.

## Steps to Reproduce
1. Open OBS
2. Leave computer on, go to bed for about 8 hours
3. [There might be another variable. OS? My particular microphone/camera/other hardware?]
4. In the morning, start clicking on things. Mouse moves, but other computer functions hang for about 1 minute.

## Additional information
My computer specs are good. SSD, 32GB RAM, Intel Core i7, etc. And I don't lag under other circumstances. I've had this happen a couple of times, only with OBS open, so I've isolated this issue to OBS.

If you have a debug/logging process you'd like me to go through, need me to try specific things, etc. let me know and I can try to get more data.

**Comment by Fenrirthviti** [comment]
Please use the forums or Discord for support.

**Comment by RedDragonWebDesign** [comment]
I typed this up for bug fixing purposes. Program causing computer to hang for 1 minute seems like a bug to me.

Support not needed since the workaround is pretty simple (don't leave OBS open overnight)

**Comment by Fenrirthviti** [comment]
There is not enough information in this report, and I have frequently left OBS open for days at a time on my PC and not experienced any issues. Without full, confirmed, reduced replication steps then there is not much we can do, as we do not want troubleshooting/support through github. That is what the support forums and Discord are for. If you post the issue there, we will be happy to gather the necessary information, and if there is an issue we can make a detailed bug report. Thank you for understanding.

**Comment by RedDragonWebDesign** [comment]
Fair enough. Thanks for your time.
