### ISSUE TITLE
[OBS 26.0.2] Image object displays old buffer when changing image

### ISSUE THREAD

**Issue by w7rus** [obsproject/obs-studio#3655]
Operating system and version: Windows 10 Pro for Workstations x64
OBS Studio version: 26.0.2

### Description
Using a specific Image object setup in OBS version 26.0.2, when the image changes (from large to smaller), it does show the buffer of old image for some reason + out of the bounding box with wrong vertical position.
![image](https://user-images.githubusercontent.com/11144322/97395647-f75de480-1917-11eb-94de-2508af365a41.png)

Such bug does not happen on OBS version 25.0.8

Log files if needed:
[2020-10-28 11-07-13.txt](https://github.com/Xaymar/obs-StreamFX/files/5449822/2020-10-28.11-07-13.txt)

### Steps to reproduce

1. Set up image object with this setup:
![image](https://user-images.githubusercontent.com/11144322/97395611-e6ad6e80-1917-11eb-8ade-6c91143a763a.png)
2. Link the image with dimensions of 640x640
3. Check that the image loaded fine into the image object
4. Override the file via another image with dimensions of 512x512
5. New image won't be drawn, but the previous image buffer will be drawn + out of the bounding box, with wrong vertical alignment

You can also see the demo [here](https://youtu.be/CZpR7RAsHsI)

### System Information
[DxDiag.txt](https://github.com/Xaymar/obs-StreamFX/files/5449817/DxDiag.txt)
The images itself to test on:
[cover_to_replace_with](https://user-images.githubusercontent.com/11144322/97397819-b1efe600-191c-11eb-9fc4-1e664630bf8b.png)
[cover](https://user-images.githubusercontent.com/11144322/97397822-b2887c80-191c-11eb-8ee6-8de5b1186412.png)

**Comment by 404-Mint** [comment]
is reproduceable, tested with pictures provided
![obs64_6bwzwqnLfn](https://user-images.githubusercontent.com/39891198/97400079-97306800-1942-11eb-9534-0782ea27e5d5.png)

**Comment by matoi974** [comment]
Reproduces here.
![image](https://user-images.githubusercontent.com/63289008/97406014-63414c80-191a-11eb-872e-0d4cc361f5d2.png)

**Comment by RytoEX** [comment]
Cannot reproduce this as described on OBS Studio 28.0.3. If you retest and experience this in OBS Studio 28.0.3 (or newer), please comment with a new OBS log and new steps to reproduce, and we can consider reopening this.
