### ISSUE TITLE
Sync offset not always used for stream or recording

### ISSUE THREAD

**Issue by Sync-offset** [obsproject/obs-studio#3659]
The sync offset works on the program screen, but not always for the recording or stream.
When you re enter the valuye after starting the stream it works fine.

**Comment by Fenrirthviti** [comment]
Issue template not filled out, sounds like a support issue. Please use the forums or Discord for support.

**Comment by Sync-offset** [comment]
Hi Joel,

I think youre jumping to conclusios.
The template is filled out with an offset value.
After starting the stream I reenter the same value in the template and it works.
This bug first apeared in version 26.0.0.
I never had the problem before.




Van: Joel Bethke
Verzonden: woensdag 28 oktober 2020 22:05
Aan: obsproject/obs-studio
CC: Sync-offset; Author
Onderwerp: Re: [obsproject/obs-studio] Sync offset not always used for stream orrecording (#3659)

Issue template not filled out, sounds like a support issue. Please use the forums or Discord for support.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Dit e-mailbericht is gecontroleerd op virussen met Avast antivirussoftware.
https://www.avast.com/antivirus

**Comment by Fenrirthviti** [comment]
I am talking about the github issue template. Please use the forums or Discord for support. If this issue can be replicated and verified, then it may be submitted as a proper bug report.

In the future, please do not delete the templates for issue submission, and make sure you are taking the time to read them.

**Comment by Sync-offset** [comment]
I’ll just go back to version 25 and wait for the bug to be solved in a future version.
