### ISSUE TITLE
Window capture settings shows incorrect list of opened windows

### ISSUE THREAD

**Issue by loremcdmx** [obsproject/obs-studio#3660]
## Platform
Operating system and version: Windows 19042.546
OBS Studio version: 26.0.2

## Expected Behavior
Settings for Windows capture should provide an actual list of opened windows as possible sources

## Current Behavior
Settings for Windows capture provide a list of all opened windows from a time when a window was assigned before
Might be related to closing of chosen before window.

## Steps to Reproduce
1. Assign a window in window capture settings
2. Close chosen window
3. Reopen settings 
4. List of available sources is not updated
5. If match priority is changed than list would update

**Comment by WizardCM** [comment]
The list will show a greyed out entry for the window that it's assigned to, but the rest of the list will reflect the other opened windows. Are you saying the entire list is outdated, or just that the entry for the one now-closed window exists?

**Comment by loremcdmx** [comment]
> The list will show a greyed out entry for the window that it's assigned to, but the rest of the list will reflect the other opened windows. Are you saying the entire list is outdated, or just that the entry for the one now-closed window exists?

weirdly issue is not replicating right now, i would investigate a bit more and come back if i would figure out what's the difference

**Comment by WizardCM** [comment]
Also keep in mind that the list is only updated when the Properties window is opened, not when the dropdown is opened, so it's possible to have an outdated list until you close & reopen Properties.
