### ISSUE TITLE
There is no VST 2.x Plug-in detected in 26.0.2 for Linux

### ISSUE THREAD

**Issue by nopalfi** [obsproject/obs-studio#3678]
## Platform
Operating system and version: Pop OS 20.04
OBS Studio version: 26.0.2

## Expected Behavior
I installed many working VST for Linux, it should be shown when i want to add filter in my mic in obs studio.

## Current Behavior
There is nothing in the drop down list.
Even i use the reaper main program to check if my VST successfully installed or not and it detected all of my installed VST.

## Steps to Reproduce

1. I already put the vst file (.so) inside /usr/lib/vst, ~/.vst, ~/.vst3/ etc
2. I tried to detect all of vst installed through Reaper main app, it showed everything but not working in OBS Studio
[2020-11-02 00-48-33.txt](https://github.com/obsproject/obs-studio/files/5471365/2020-11-02.00-48-33.txt)
![image](https://user-images.githubusercontent.com/33050934/97809328-2ae99780-1ca7-11eb-821f-df0a3422142e.png)
![image](https://user-images.githubusercontent.com/33050934/97809350-4785cf80-1ca7-11eb-9d0d-4e062e748ed1.png)

**Comment by kkartaltepe** [comment]
Sandboxed installs are not supported.
