### ISSUE TITLE
Windows10 x64: moving main OBS window erratic if dual monitors, snaps to midpoint between the 2 displays

### ISSUE THREAD

**Issue by studleylee** [obsproject/obs-studio#3680]
## Platform

Operating system and version:
OBS Studio version:

## Steps to Reproduce

1.
2.
3.
4.

**Comment by WizardCM** [comment]
Please fill in the issue template.

**Comment by studleylee** [comment]
A stupid mistake on my part. There is no issue. Thank you!

**Comment by studleylee** [comment]
A stupid mistake on my part. There is no issue. Thanks.

**Comment by mufunyo** [comment]
This is a stupid behaviour that Windows 10 does regardless of which application you're using. It's extremely frustrating.
