### ISSUE TITLE
caption.h is missing

### ISSUE THREAD

**Issue by vixns** [obsproject/obs-studio#3682]
## Platform

Operating system and version: Linux debian sid
OBS Studio version: master

## Expected Behavior

compiles

## Current Behavior

obs-studio/libobs/obs-internal.h:39:10: fatal error: caption/caption.h: No such file or directory
   39 | #include <caption/caption.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.

## Steps to Reproduce

1.  clone the master branch and follow the build procedure.

**Comment by Dschorim** [comment]
I have the same issue on gentoo

**Comment by jhenkins** [comment]
I have the same issue on Ubuntu Studio:

```
...
[ 14%] Building C object libobs/CMakeFiles/libobs.dir/util/platform-nix.c.o
In file included from ~/obs-studio-build/libobs/obs-nix.c:19:
~/obs-studio-build/libobs/obs-internal.h:39:10: fatal error: caption/caption.h: No such file or directory
   39 | #include <caption/caption.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
...
```

**Comment by WizardCM** [comment]
Looks like this was added in https://github.com/obsproject/obs-studio/commit/923f06bfa6ea80a432f182b50bb6dc5256ba2560#diff-72ae7e44ca140ee28cbd84d594972f72ac95b8070a5d0b3bd401a4d569774a94R39

I have a feeling it assumes that captions are enabled, which isn't always the case, per the `ENABLE_CAPTIONS` cmake flag.

Error occurs on Windows 10 too.

**Comment by Gol-D-Ace** [comment]
Can confirm this as well.
CI didn't fail because captions are enabled on all builds.

**Comment by DDRBoxman** [comment]
I'm going to update this flag to make sure it only relates to the window speech to text caption stuff, and probably change the name of it to reflect that

**Comment by wexi** [comment]
Fatal error: caption/caption.h: No such file or directory
git describe master
26.0.2-67-g923f06bf

**Comment by DDRBoxman** [comment]
#3687

**Comment by shawnjgoff** [comment]
Does including `<caption/caption.h>` also break anything that depends on libobs without also depending on libcaption?  I've built obs-studio after the [associated commit](https://github.com/obsproject/obs-studio/pull/3687) and then attempted to build [obs-gphoto](https://github.com/Atterratio/obs-gphoto/), but it gives the same error.

**Comment by KristijanZic** [comment]
Can this issue please be reopened?
I've tried building https://github.com/adlerweb/obs-gphoto and I got this error:
```
$ make
Scanning dependencies of target obs-gphoto
[ 16%] Building C object CMakeFiles/obs-gphoto.dir/src/obs-gphoto.c.o
[ 33%] Building C object CMakeFiles/obs-gphoto.dir/src/gphoto-utils.c.o
In file included from /home/aresminos/Software/source/obs-gphoto/src/gphoto-utils.c:2:
/usr/include/obs/obs-internal.h:39:10: fatal error: caption/caption.h: No such file or directory
   39 | #include <caption/caption.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/obs-gphoto.dir/build.make:76: CMakeFiles/obs-gphoto.dir/src/gphoto-utils.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/obs-gphoto.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by robinuniverse** [comment]
Is there any way to fix this? I am still unable to build this from the AUR, and I don't really know what I can change to make it build correctly

**Comment by jp9000** [comment]
You shouldn't need to install a separate package. Our repository comes with libcaption in the deps/libcaption directory. It should be using it by default.

**Comment by bnordgren** [comment]
On Fedora, I had to clone obs-studio from git, then `cp -r deps/libcaption/caption /usr/include`. 

A bit ugly, but I did it in a toolbox, so it's contained.

**Comment by pierrextardif** [comment]
it seems like it's not shipped with the [dependencies ZIP file](https://obsproject.com/wiki/Install-Instructions#windows) which comes in the tutorial for windows 10:
![Capture](https://user-images.githubusercontent.com/6206595/116411283-7a131e00-a82d-11eb-98bb-2fa87df75d72.JPG).
However it's in the deps folder, but isn't taken into account by VSStudio, :(.
Seems like modifying the makefile is enough - in my case for a filter - ?

```sh

include_directories(${CMAKE_SOURCE_DIR}/deps/libcaption)
set(libobs_PLATFORM_DEPS
	${libobs_PLATFORM_DEPS}
	caption)
```



Is that correct?

**Comment by RytoEX** [comment]
> it seems like it's not shipped with the [dependencies ZIP file](https://obsproject.com/wiki/Install-Instructions#windows) which comes in the tutorial for windows 10:
> However it's in the deps folder, but isn't added in the Makefile of the solution i'm building.
> Seems like modifying the makefile is enough - in my case for obs-filters - ?
> 
> ```shell
> include_directories(${CMAKE_SOURCE_DIR}/deps/libcaption)
> set(libobs_PLATFORM_DEPS
> 	${libobs_PLATFORM_DEPS}
> 	caption)
> ```
> 
> Is that correct?

`#include <captions/captions.h>` works fine in a standard dev environment for building OBS Studio because we have `deps\libcaption` specified in the "Additional Include Directories" from the CMake call `include_directories(${CMAKE_SOURCE_DIR}/deps/libcaption)`.  You're free to peruse our CMakeLists.txt files to see how we do this, but GitHub Issues is for verified bug reports, not developer support.  If you need assistance building plugins for OBS, you're welcome to ask on our Discord or forums.  Thank you for understanding.

https://obsproject.com/help

**Comment by pierrextardif** [comment]
> You're free to peruse our CMakeLists.txt files to see how we do this, but GitHub Issues is for verified bug reports, not developer support. If you need assistance building plugins for OBS, you're welcome to ask on our Discord or forums. Thank you for understanding.

Thanks, sorry for misunderstanding, let me clarify:
I'm calling `obs-internal.h` from my filter; which in turn calls `#include <caption/caption.h>` . 
Therefore I would believe  that it was a bug coming from OBS. I don't need libcaption directly, I only do `#include "obs-internal.h"` , :).

**Comment by RytoEX** [comment]
> I'm calling `obs-internal.h` from my filter;

Why?  I wouldn't recommend doing that.  Including an internal header like that isn't something I'd consider supported, and that doesn't convince me that this should be reopened.

Again, if you have development related questions, ask on our Discord or forums.
https://obsproject.com/help

**Comment by pierrextardif** [comment]
> Why? I wouldn't recommend doing that

ah alright, noted.
Well i'm adapting this filter from source code from a couple of years ago, but I guess `obs-internal.h` call might not be needed anymore.
> Again, if you have development related questions, ask on our Discord or forums.

Ok will do, thks.
