### ISSUE TITLE
Error when linking libobs

### ISSUE THREAD

**Issue by Dschorim** [obsproject/obs-studio#3685]
## Platform

Operating system and version:
Gentoo on Kernel 5.9.1
OBS Studio version:
latest (master branch)

## Expected Behavior
compile should run through

## Current Behavior
compile (make -j4) crashes with
Linking C shared library libobs.so
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/local/sbin/../lib/libavcodec.a(me_cmp.o): warning: relocation against `ff_pb_80' in read-only section `.text'
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/local/sbin/../lib/libswscale.a(swscale.o): relocation R_X86_64_PC32 against symbol `ff_M24A' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [libobs/CMakeFiles/libobs.dir/build.make:1222: libobs/libobs.so.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:1215: libobs/CMakeFiles/libobs.dir/all] Error 2 

## Steps to Reproduce
follow the compile instructions for Linux, the "make -j4" terminates with this error message

## Additional information
I did modify option(BUILD_CAPTIONS "Build captions" FALSE) to option(BUILD_CAPTIONS "Build captions" TRUE) in CMakeLists.txt as a workaround for https://github.com/obsproject/obs-studio/issues/3682

**Comment by notr1ch** [comment]
Your local installation of libswscale is broken, as the error suggests, it needs to be built with -fPIC. Gentoo is not an officially supported platform, so you're on your own to fix this.
