### ISSUE TITLE
obs uses so much CPU when i start it up and i have to change the FPS just to make it use less again (NVENC ENCODER)

### ISSUE THREAD

**Issue by yeongy** [obsproject/obs-studio#3696]
## Platform

Operating system and version: windows 10 pro 64bit
OBS Studio version: 26.0.2

## Expected Behavior
OBS should start up and use less than 5% or around 5% CPU usage (according to the software)
## Current Behavior
OBS is using 10+% CPU and i have to change the FPS capture just to make it go lower again which messes up certain plugins that I am using
https://obsproject.com/logs/FT3C0g26vLT2xwLj

## Steps to Reproduce

1. video footage (a bit low quality): https://youtu.be/6icZHZMPox8
2.
3.
4.

**Comment by Fenrirthviti** [comment]
The issues pages are not for support, please use the forums or Discord.

**Comment by yeongy** [comment]
i was told to put this issue here FROM THE DISCORD @Fenrirthviti

**Comment by Fenrirthviti** [comment]
Staff would not recommend that you submit support requests to the GitHub issues page. Please use the forums or Discord in the appropriate channel for assistance.
