### ISSUE TITLE
 obs uses so much CPU when i start it up and i have to change the FPS just to make it use less again (NVENC ENCODER)

### ISSUE THREAD

**Issue by yeongy** [obsproject/obs-studio#3697]
## Platform

Operating system and version: window PRO 10 64bit
OBS Studio version: 26.0.2

## Expected Behavior
obs should start up and use around 5% or less CPU

## Current Behavior
obs starts up (60FPS) and uses more than 10%CPU and i have to change FPS and put it back to 60 just to make it use less CPU but it messes with certain plugins i have
log: https://obsproject.com/logs/FT3C0g26vLT2xwLj

## Steps to Reproduce

1. video: https://www.youtube.com/watch?v=6icZHZMPox8&feature=youtu.be
2.
3.
4.

**Comment by kkartaltepe** [comment]
Dont reopen an issue when it is closed for being off topic.

**Comment by yeongy** [comment]
i just posted this? this isn't a reopened topic??

**Comment by yeongy** [comment]
sorry i thought it didn't post the first time because it gave me a 404 page when i hit submit
