### ISSUE TITLE
Hebrew text sources are reversed

### ISSUE THREAD

**Issue by AlmogBaku** [obsproject/obs-studio#3698]
## Platform

Operating system and version: MacOS Catalina 10.15.7 (19H2)
OBS Studio version: OBS 26.0.2 

## Expected Behavior
A text should be displayed in the right order

## Current Behavior
When I create a "text source" and type a Hebrew text (RTL), the order of the characters is reversed. ("אבג" -> "גבא")

## Steps to Reproduce
1. Create a Text source
2. Choose a font that supports Hebrew (such as Arial)
3. Type Hebrew text

Logs: [2020-11-05 10-22-26.txt](https://github.com/obsproject/obs-studio/files/5492937/2020-11-05.10-22-26.txt)
Screenshot: 
<img width="887" alt="Screen Shot 2020-11-05 at 10 23 21" src="https://user-images.githubusercontent.com/98982/98216149-5a233180-1f51-11eb-9da5-1b0d0393ae74.png">

**Comment by kkartaltepe** [comment]
Complex scripts, including LTR, are not supported in the freetype text plugin.

You can try third party text plugins if you need to render complex text. One choice might be https://github.com/kkartaltepe/obs-text-pango/releases/tag/v1.0

**Comment by Fenrirthviti** [comment]
Closing as this isn't really a bug, just an unsupported feature in the plugin.

One of these days we should just pull in the Pango plugin for all platforms and get it over with.
