### ISSUE TITLE
Crash: linux-decklink.so: undefined symbol

### ISSUE THREAD

**Issue by LGCW** [obsproject/obs-studio#3699]
Everything after OBS 26.0.2-66-gb9a15162 crashes with the following error. 

./obs: symbol lookup error: ../../obs-plugins/64bit/linux-decklink.so: undefined symbol: _ZN13OBSVideoFrameC1Ell

This happens with portable and and regular. 

## Platform
Operating system and version: Debian 10
OBS Studio version: OBS 26.0.2-81-g3564e446 (linux)

## Expected Behavior
OBS should launch. 

## Current Behavior
Decided lack of launch. 

## Steps to Reproduce
1. ./obs

## Additional information
This system is running a Decklink Intensity Pro 4K.

**Comment by kkartaltepe** [comment]
You can compiled things incorrectly.

**Comment by LGCW** [comment]
I compiled obs using the insurrections here https://github.com/obsproject/obs-studio/wiki/Install-Instructions#debian-based-build-directions

Same way I compiled obs the past few years. Would you be so kind as to point me to the new **correct** compilation instructions. 

Thank you.

**Comment by kkartaltepe** [comment]
Please use the discord for support, there is a development channel where you can get help with building obs.
