### ISSUE TITLE
Stop recording at 7 minutes during certain games bug

### ISSUE THREAD

**Issue by jokerguy21476** [obsproject/obs-studio#3703]
I'm not sure if it is a bug, but whenever I record a certain game, the recorder stops recording after 7 minutes.

**Comment by WizardCM** [comment]
Please fill in the issue template, including providing reproduction steps and a log of a session where the issue occurred.

**Comment by notr1ch** [comment]
If you aren't sure it's a bug, this is not the right place. Use the forums or Discord for support.
