### ISSUE TITLE
Recording stops after 7 minutes of recording a certain game

### ISSUE THREAD

**Issue by jokerguy21476** [obsproject/obs-studio#3704]
## Platform

Operating system and version:
OBS Studio version: 26.0.2

## Expected Behavior
 keep recording until I press stop recording

## Current Behavior
 the recording stops by itself after 7 minutes of recording a certain game

## Steps to Reproduce

1. I press record before I go into game
2. After 7 minutes, the recording stops by itself
3.
4.

**Comment by Fenrirthviti** [comment]
As mentioned in the previous report, this is not a confirmed or actionable report, please use the support forums or Discord for support.
