### ISSUE TITLE
OBS when disk full

### ISSUE THREAD

**Issue by Its-Just-Nans** [obsproject/obs-studio#3705]
## Platform
Operating system and version: windows 2004
OBS Studio version:  21.1.0

## Expected Behavior
Alert the user when the disk is full and OBS cannot record

## Current Behavior

When you start a record when your disk is full, OBS say it is recording but it's not.
And the output is a very small file (48 bytes or less). And the files isn't working.

## Steps to Reproduce

1.Just have your disk full
2. Try to record 
3. Finish your record
4.Try view the file -> you can't because there is nothing

## Additional information

some solutions (maybe) : 
- check if there is enough space
- check the length of the file after 1 or 2 second, if the lenght is not 'logical', there is an error

I didn't what OBS do if the disk is full when recording :/

**Comment by notr1ch** [comment]
Your version of OBS is outdated, newer versions already warn when there is insufficient disk space.

**Comment by Gol-D-Ace** [comment]
Please note that this version does have a broken auto updater.

So you will need to download OBS from https://obsproject.com
