### ISSUE TITLE
GPU Usage

### ISSUE THREAD

**Issue by BoboTheBandit1972** [obsproject/obs-studio#3707]
Hello

OBS Version: 26.0.2

Linux Distro: Current: ( Linux Mint 20:00 ) Previous ( Ubuntu 18.04 and 20.04, Kubuntu 20.04 and Linux Mint 18.03 )

GPU used ( AMD RX 550 and RX 580 )

When I try to record or stream the GPU usage maxes out at 100% instantly yet if i leave OBS idle I have no such issues 

This issue has only started happening since I updated from OBS 25.0.8 to 26.0.2

Regards

Bobo

**Comment by notr1ch** [comment]
Please use the forums or Discord for support. Also note that Linux Mint is not an officially supported platform.
