### ISSUE TITLE
Chroma Key behaves different when added to a scene then directly to a source

### ISSUE THREAD

**Issue by CloudCorleone** [obsproject/obs-studio#3709]
## Platform
Operating system and version: Windows 10 Home Build 19041.572
OBS Studio version: 26.0.2 (64 bit)

## Expected Behavior
Adding a Chroma Key filter to a scene should have the same effect when beeing added to a source.

## Current Behavior
When adding the Chroma Key to a scene  it filters out colors partially. When adding the same filter to a Source nothing is changed.
 
filter on media: https://cdn.discordapp.com/attachments/374636015396192257/774819914552836106/Screenshot_2020-11-08_03-16-00.png

filter on scene: https://cdn.discordapp.com/attachments/374636015396192257/774819974967066684/Screenshot_2020-11-08_03-16-32.png

## Steps to Reproduce 

1. create to scenes
2. add scene 1 to scene 2
3. add media source with the video to scene 1
4. add chroma filter to video in scene 1 to configure it so it does no changes (for example: green, 1, 1, 1, 100, 0, 0, 0)
5. delete filter again
6. go to scene 2
7. add filter to scene 1 in scene 2 with the same settings as the chroma key before

## Additional information
i could only reproduce this error with following video, maybe reproducing"works" for other videos too too:  https://cdn.discordapp.com/attachments/416296432891330562/774941851605401610/Droplets_Iddle.webm

**Comment by skeletonbow** [comment]
Haven't attempted to confirm this, but it reminded me of bug #2852.

**Comment by RytoEX** [comment]
I cannot reproduce this in OBS Studio 28.0.3. If you retest and experience this in OBS Studio 28.0.3 (or newer), please comment with a new OBS log and new steps to reproduce, and we can consider reopening this.
