### ISSUE TITLE
VLC source cuts audio between clips when monitoring

### ISSUE THREAD

**Issue by coltertv** [obsproject/obs-studio#3712]
## Platform

Operating system and version: Windows 10.0.19041.572
OBS Studio version: 26.0.2

## Expected Behavior

Sound between clips in a VLC playlist should not be clipped

## Current Behavior

You add 2 or more clips to a VLC playlist, when playback goes to the next clip, audio gets clipped 1 or 2 seconds before completion. This only happens when monitoring audio, not streaming or recording.  This is very annoying for people who use OBS Studio as a projector, because you want to monitor the audio.

## Steps to Reproduce

1. Create a VLC source
2. Add 2 or more videos
3. Monitor the source (headphones for example)
4. When the clip is about to finish, audio will be clipped 1 or 2 seconds before completion.

**Comment by maxdrash** [comment]
Is this related to the bad sources ingestion for pulseaudio ? #3525

**Comment by coltertv** [comment]
> Reproduced on 26.0.2-0obsproject1~focal and earlier 25.0.8, 24, 23 etc ...
> Is this related to the bad sources ingestion for pulseaudio ? #3525

I don't think so. Pulseaudio afaik is a linux thing and I'm using windows

**Comment by barbrastreisand** [comment]
Also seeing this on Windows. This thread seems to suggest downgrading the version of VLC installed to 2.2.8, which seems to work better, though still seems to cut a little off at the end. I would use a different source, but since I'm using Tuna to display the track info, this requires the VLC source to be used.

https://obsproject.com/forum/threads/vlc-video-source-audio-cuts-off-early.114866/

**Comment by coltertv** [comment]
> Also seeing this on Windows. This thread seems to suggest downgrading the version of VLC installed to 2.2.8, which seems to work better, though still seems to cut a little off at the end. I would use a different source, but since I'm using Tuna to display the track info, this requires the VLC source to be used.
> 
> https://obsproject.com/forum/threads/vlc-video-source-audio-cuts-off-early.114866/

What you mean using a different source? It is a VLC playlist.

**Comment by Phil7789** [comment]
> What you mean using a different source? It is a VLC playlist.

Maybe he is referring to the media source that is also available.

Addition to the issue: This is still a bug with OBS 27.0.1 (64bit) and VLC 3.0.16 Vetinari. I am aware of the "solution" of using VLC 2.2.8 but as this exposes security risks, this is not a real solution.
I've tested the playlist within VLC and there are no audio cut offs, so this is probably related to OBS.

The media files are also flickering when going to the next file, this is also only in OBS and not VLC but this would be subject to an own issue.

**Comment by coltertv** [comment]
> > What you mean using a different source? It is a VLC playlist.
> 
> Maybe he is referring to the media source that is also available.

Oh, I see. But media source has no playlists afaik ? I need playlists.

> Addition to the issue: This is still a bug with OBS 27.0.1 (64bit) and VLC 3.0.16 Vetinari. I am aware of the "solution" of using VLC 2.2.8 but as this exposes security risks, this is not a real solution.
> I've tested the playlist within VLC and there are no audio cut offs, so this is probably related to OBS.

Yes, but this only happens when monitoring audio. If you send the vlc playlist audio directly to a stream or recording, it goes OK.  But I need to use the monitoring function.

> The media files are also flickering when going to the next file, this is also only in OBS and not VLC but this would be subject to an own issue.

I personally have not suffered this issue so far.

Thank you

**Comment by VaughnWhiskey** [comment]
Just started using VLC Media Source and instantly had this problem monitoring the audio. Hoping this can be looked at whenever. I'd like to be able to hear the VLC Media Source audio to better judge when to cut the clips off and transition back to gameplay.

**Comment by VaughnWhiskey** [comment]
> I have confirmed the issue on Windows. This doesn't mean someone will look into it immediately, just that I've verified myself that the bug exists.

Understand but still, thanks for confirming!

**Comment by ElizabethMcFife** [comment]
Can confirm this is still occurring on OBS Studio 27.1.3

Turning off audio monitoring stops the clipping issue, but obviously cannot hear the source.

A fix for this would be great.

**Comment by dark-swordsman** [comment]
Can confirm this is still a problem in 27.2.4. 

Someone suggested rolling back to VLC 2.2.8 but that didn't seem to fix it. Someone else also mentioned that it only happens with the audio monitor.

**Comment by werewolfgold** [comment]
It'd be really nice to have a fix for this. VLC is still cutting both the first second and ending seconds for me when monitoring. This is in ver. 28.01

**Comment by FedetheTV** [comment]
it would be nice if they fixed this

**Comment by PatTheMav** [comment]
Duplicate of https://github.com/obsproject/obs-studio/issues/7552 - VLC's audio monitoring works as implemented (so it's not necessarily a "bug") but that implementation doesn't take sudden changes of input sources into account.

We will track progress on that issue, but so far this will require a volunteer to look into the associated monitoring code.
