### ISSUE TITLE
Virtual camera does not work

### ISSUE THREAD

**Issue by bradrn** [obsproject/obs-studio#3717]
## Platform

Operating system and version: Windows 10 (version 1909)
OBS Studio version: 26.0.2

## Expected Behavior

When I start the Virtual Camera, it appears as an available camera with programs such as Camera, Zoom etc., as well as appearing in a query with `System.Management.ManagementObjectSearcher`.

## Current Behavior

The camera appears on Zoom, but not in the inbuilt Camera app nor when I run a query with `System.Management.ManagementObjectSearcher`.

## Steps to Reproduce

1. Open OBS.
2. Start the virtual camera with the ‘Start Virtual Camera’ button.
3. Open the inbuilt Camera app and toggle through the list of camera apps. The OBS Virtual Camera does not appear.
4. Run the following command in Powershell (taken from [here](https://stackoverflow.com/questions/19452757/how-can-i-get-a-list-of-camera-devices-from-my-pc-c-sharp/62128539#62128539));
   ```
   [System.Management.ManagementObjectSearcher]::new("SELECT * FROM Win32_PnPEntity WHERE (PNPClass = 'Image' OR PNPClass = 'Camera')").Get() | % { $_.Caption }
   ```
   The OBS Virtual Camera does not appear in the resulting list.
5. Open Zoom and inspect the list of available cameras. The OBS Virtual Camera appears and works correctly.

**Comment by Fenrirthviti** [comment]
This is expected, the virtual camera uses DirectShow, not Media Foundation.

**Comment by bradrn** [comment]
> This is expected, the virtual camera uses DirectShow, not Media Foundation.

Thanks for the quick reply! In that case, is there any way to get the virtual camera to work with those apps which only support Media Foundation?

**Comment by Fenrirthviti** [comment]
Unfortunately, not that I am aware of. The virtualcam output would need to be updated (read: rewritten from scratch) to support MediaFoundation, which is something OBS does not currently support.
