### ISSUE TITLE
Can't use same webcam with 2 differents scenes without copying reference (Windows)

### ISSUE THREAD

**Issue by scls19fr** [obsproject/obs-studio#3718]
## Platform
Operating system and version: Windows 10 (v2004)
OBS Studio version: 26.0.2 (64 bits)

## Expected Behavior
When creating 2 different scene, with same webcam on each scene. It can be useful to apply different filter on each occurence of the webcam.

## Current Behavior
Unfortunately under Windows, creating a new source with same webcam freezes the webcam screen.

## Steps to Reproduce
1. Create a scene Scene1 and add webcam as input video source
2. Create a scene Scene2 and add (same) webcam as input video source
3. Go back to Scene1 and move webcam... image is not updated

## Additional information
Why simply copy and pasting (Reference) doesn't help ?
Because in such a case you can't have filter applied on one input video source and not on the other one (I simply need a crop filter)

This problem occurs under Windows but not under Mac OS.

Contextual menu Paste (Duplicate) is disabled... it shouldn't (at least under Mac OS X) because we can have 2 differents objects for same webcam... which is a duplicate... and not a reference.

**Comment by Gol-D-Ace** [comment]
You are running into DirectShow / driver limitations there.

It's normal for DirectShow devices to be only be able to be initialized once like you already noticed.

Workarounds are putting the webcam into it's own scene and then adding that scene to another scene and applying a filter to it and add that final scene as a reference or putting the reference in a group and applying the filter to the group.

macos isn't using DirectShow so you can't really compare them here.


Should this be handled bette

Yes

Is it a big though?

Absolutely not.

**Comment by mufunyo** [comment]
> Workarounds are putting the webcam into it's own scene and then adding that scene to another scene and applying a filter to it and add that final scene as a reference

Unfortunately, that does not work, as filters are applied to scenes globally, so a filter applied to a scene in one instance is also applied to all other instances of that scene inside other scenes.

**Comment by Gol-D-Ace** [comment]
That's why you put the scene with the webcam into a scene.

Basically like this

Scene 1 Webcam
Scene 2 Reference of Webcam
Scene 3 (apply filter to this scene) reference to scene 2

Scene 4 reference to scene 3


Just putting the reference in a group and then applying the filter to that group is by far way easier.

**Comment by scls19fr** [comment]
Thanks for your help. I will try to proceed that way.
