### ISSUE TITLE
Linux/x11: twitch network error when swapping between sources

### ISSUE THREAD

**Issue by AdelKS** [obsproject/obs-studio#3719]
## Platform
Operating system and version: Up to date Archlinux
OBS Studio version: 26.0.2
x11, error happens on Gnome and LXDE

OBS settings:
![obs-settings](https://user-images.githubusercontent.com/13605217/98857243-15226200-245f-11eb-820a-d111f5650f30.png)

## Current Behavior
I usually play Overwatch and stream on twitch, with two sources: one display capture of the desktop and one game capture for the game. When I queue I swap between the sources. Swapping between sources sometimes gives this error on twitch: 

![twitch-network-error](https://user-images.githubusercontent.com/13605217/98856463-de981780-245d-11eb-968a-87800e458a66.png)

It doesn't only happen on my end, everyone watching the stream get it.

## Expected Behavior
No network error when swapping between sources and virtual desktops.

## Steps to Reproduce
1. Use linux on x11
2. Stream to twitch
3. Have the game in a virtual desktop and the rest on another virtual desktop
4. Have one game capture and one desktop capture
5. Switch between the two sources and the two virtual desktops, the error should happen. The number of switches needed vary.

Here's a video showing the steps to (re)produce the error:
https://youtu.be/muPDcvfx6vE

I am happy and willing to help out debugging, thank you in advance for your help!

**Comment by Fenrirthviti** [comment]
Please provide a log file, but this sounds like an environment issue rather than anything to do with OBS. Switching scenes in OBS has nothing to do with the network connection, I am not sure how this could be related in any way. There is likely something on your system that is changing the network when different virtual desktops are being accessed, if I had to guess.

**Comment by Fenrirthviti** [comment]
Actually, on second thought, this is more of a support issue as you aren't even really sure yourself what is going on. Please use the forums or Discord if you need support.

**Comment by AdelKS** [comment]
Some viewers also reported that they had to refresh because of "encoder crash". I think the error twitch spits out doesn't reflect the actual error, who I feel is something related to encoding. I will go to the forum as you suggested. Thanks.

**Comment by AdelKS** [comment]
@Fenrirthviti This issue remains since I opened it, even on other distros: switching virtutal desktops makes the stream crash on twitch

More information: I have the game alone in a separate virtual desktop, sometimes I switch off the game, so OBS starts recording black (which is normal), but switching on and off the game by switching virtual desktops crashes the stream on twitch at least. Can you have give it a try and reproduce it ? 

Please consider this issue.

Thank you!

**Comment by AdelKS** [comment]
Hello, I finally figured out how to work around this issue: switching between virtual desktops or apps sometimes makes OBS output a black/gray frame for a very short moment, and that seems to make streaming to Twitch crash, for an unknown reason.

The workaround: keep a background image under all the other sources, so whenever a black image is supposed to happen, it's the background image instead. My twitch streams never crashed since. They used to crash every time I stream, for nearly a year.
