### ISSUE TITLE
First frame of large .webm not completely transparent in Media Source

### ISSUE THREAD

**Issue by megalon** [obsproject/obs-studio#3721]
## Platform
Operating system and version: Windows 10, 64bit (OS Build 1836.1198)
OBS Studio version: 26.0.2

## Expected Behavior
Transparent pixels in the first frame of the large (1542 x 1542 px) webm should render as completely transparent when loaded with the Media Source.

## Current Behavior
On a black (#000000) background, the first frame of the large (~1500+px) .webm appears as #010101 instead of #000000 when loaded in a Media Source.

I've only seen this in the preview window. I made a recording, but it wasn't visible in the recording when I played it back. That may just be my recording settings, I'm not sure.

## Steps to Reproduce
1. Load a large (~1500px+) transparent webm in a Media Source.
2. Pause on the first frame and check the borders of the background.

### Screenshots
First frame of the included 1542 x 1542px webm.
The white "1" should be surrounded by a completely transparent background, but instead there is a faint white box. (Might not be visible on some monitors. Use a color picker to verify if you can't see it here.)
![image](https://user-images.githubusercontent.com/27714637/98923510-97734c00-2488-11eb-8773-08ba69e53016.png)

And here is the 2nd frame. You can see there is no faint white box.
![image](https://user-images.githubusercontent.com/27714637/98923593-b376ed80-2488-11eb-9bb1-8dc87cb9891b.png)

## Additional information
I've included the webms and source images that I used to create the webms in the zip attached to this post. All of these webms I tested appear with completely transparent backgrounds in VLC.

The square 1024px and 1025px webms load correctly (with a completely transparent background).

The 1500px version appears to have a translucent box in the bottom right quadrant.

The 1542px version has a slightly translucent background for the entire video. 

[TestOBS-webms.zip](https://github.com/obsproject/obs-studio/files/5529799/TestOBS-webms.zip)

Edit:
Here is my current log file
https://obsproject.com/logs/CcKDRtS4aeOzm-C0

**Comment by walterav1984** [comment]
See that the framerate is 1fps of outout-1024.webm, have you tried matching the webm framerate with your project framerate?

**Comment by Fenrirthviti** [comment]
Issue appears to be with the actual video file, not OBS. We've replicated the same issue in normal video players.
