### ISSUE TITLE
Source Toolbar doesn't behave properly on OBS start

### ISSUE THREAD

**Issue by Vainock** [obsproject/obs-studio#3722]
## Platform

Operating system and version: Windows 10 2004
OBS Studio version: 26.0.2-91-g3e7e99e0 (https://github.com/obsproject/obs-studio/commit/3e7e99e0f33454200d4f951f1d6672459e05c793)

## Expected Behavior

When the program starts, the source toolbar should show the text "No source selected", as I have no source selected.

## Current Behavior

On program start the source toolbar shows:
![Pic](https://user-images.githubusercontent.com/39059951/98935151-64aa7180-24e3-11eb-950e-da6edab7197a.png)
It is also possible to click on "Properties" and "Filters" in this state.
Once I click on a source, and unselect it again, the toolbar works correctly and shows me the text "No source selected".

## Steps to Reproduce

1. Start OBS

## Additional information

/

**Comment by maxdrash** [comment]
Not reproduced on 26.0.2-0obsproject1~focal from ppa.
Windows only issue ?

**Comment by WizardCM** [comment]
Reproduction steps require the user to have never toggled View -> Source Toolbar.
