### ISSUE TITLE
Fix the Crop filter

### ISSUE THREAD

**Issue by Hitrate** [obsproject/obs-studio#3723]
## Platform

Operating system and version:
OBS Studio version:

## Expected Behavior

What should happen is that when you do minus crop on any surface, top, bottom, left or right side, it should all behave the same - that is, the right side should crop inwards - meaning remove more and more of itself, not move the image. 

Same with when you then want to crop away some of the top, lets say on the same image/capture, it should take away/remove inwards the image from the top (and down), not as it is now where it moves the image up from the bottom (!), so you have to re-frame (not good). This is standard behavior on other normal editing platforms and should be fixed to work similarly in OBS immediately. 

## Current Behavior

something weird is happening with the crop filter
the crop filter doesn't crop more than one or two sides, like, I can't crop the top for instance...or the left side :/
when i do plus or minus it just moves the image up or down it doesn't crop away the top part just moves the whole image up or down within the frame :/
I have to then manually move the whole frame down/up afterwards
that's not a proper way to implement cropping
as opposed to just positioning it where I want, then crop away the top
I can't do that as it is
I can crop away the top but then it raises the frame rather than removing the top part
u can all replicate this urselves

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Fenrirthviti** [comment]
I think you're misunderstanding how the crop filter works. Try using the transform crop instead, by holding alt+dragging the source bounding box, or by clicking the source and pressing ctrl+e to manually enter crop values, rather than using the filter.

In the future, please use the forums or Discord for support and try not to submit unverified and uncertain bugs.
