### ISSUE TITLE
About using same name of different streams in same pipeline

### ISSUE THREAD

**Issue by Mlocik97** [obsproject/obs-studio#3727]
Hello, Linux users...

this problem refer on problem: https://github.com/wwmm/pulseeffects/issues/822

Because We use same pipeline (Record Stream) and same name of App (OBS) for both audio streams / entries (Mic/AUX, and Desktop Audio), it has a disadvantages for specific using like I wrote in PulseEffects issue.

(And also it automatically connect both streams for Desktop Audio and Mic/Aux to PE (Mic) pipeline. Need to change it at every start of OBS app.)

![Snímka obrazovky z 2020-11-13 16-23-30](https://user-images.githubusercontent.com/34808350/99089274-5d5f9280-25cd-11eb-95d8-4204b91c5f9d.png)
![Snímka obrazovky z 2020-11-12 20-28-09](https://user-images.githubusercontent.com/34808350/99089283-5fc1ec80-25cd-11eb-8557-44f5e8f2bd57.png)

I don't know, what we can do with this, but actual situation is that, adding specific stream of OBS to blocklist add automatically all OBS's streams to it.

**Comment by kkartaltepe** [comment]
This doesnt seem like a bug report. Please use https://ideas.obsproject.com/ for feature requests.
