### ISSUE TITLE
Crashes on subsequent recordings (mov, libxvid, pcm_s16le)

### ISSUE THREAD

**Issue by Twiggeh** [obsproject/obs-studio#3731]
## Platform

Operating system and version:
```
System:    Kernel: 5.8.18-1-MANJARO x86_64 bits: 64 compiler: gcc v: 10.2.0 
           parameters: BOOT_IMAGE=/boot/vmlinuz-5.8-x86_64 root=UUID=528f8171-7936-4019-9382-d327f9354b32 rw quiet 
           apparmor=1 security=apparmor resume=UUID=4b0f0b7e-6616-4a9b-a7e2-5bedfd0afcd8 udev.log_priority=3 
           Desktop: KDE Plasma 5.20.2 tk: Qt 5.15.1 wm: kwin_x11 dm: SDDM Distro: Manjaro Linux 
```

OBS Studio version: obs-studio 26.0.2-2

## Expected Behavior

Should be able to record subsequent videos, not just one 

## Current Behavior

Not sure where to find the log file, but it crashes if you try to make a record a new video after you have already recorded one

## Steps to Reproduce

1. Set the output to mov, 5000kbs, 250 keyframe, libxvid, pcm_s16le
![image](https://user-images.githubusercontent.com/23149166/99150039-28694380-2692-11eb-8ced-6482b72e6591.png)
2. Record a video
3. Try recording a video again, it either crashes on start recording & creates a bad file or it crashes on stop recording & sometimes leaves a good file sometimes a bad one.

**Comment by kkartaltepe** [comment]
Replicated, though I think this is possibly not our bug.

```
(gdb) bt
#0  0x00007ffff2456fae in  () at /usr/lib/libxvidcore.so.4
#1  0x00007ffff2433d0f in  () at /usr/lib/libxvidcore.so.4
#2  0x00007ffff23e6da0 in  () at /usr/lib/libxvidcore.so.4
#3  0x00007ffff6e555c6 in  () at /usr/lib/libavcodec.so.58
#4  0x00007ffff6c2017b in avcodec_encode_video2 () at /usr/lib/libavcodec.so.58
#5  0x00007ffff6c20533 in  () at /usr/lib/libavcodec.so.58
#6  0x00007ffff6c2069f in avcodec_send_frame () at /usr/lib/libavcodec.so.58
#7  0x00007fffbef8ec29 in receive_video (param=<optimized out>, frame=0x7fffe4a6f8b0)
    at ../plugins/obs-ffmpeg/obs-ffmpeg-output.c:767
#8  0x00007ffff5cb2ad8 in default_raw_video_callback (frame=0x7fffe4a6f8b0, param=0x555557ec8640)
    at ../libobs/obs-output.c:1767
#9  default_raw_video_callback (param=0x555557ec8640, frame=0x7fffe4a6f8b0) at ../libobs/obs-output.c:1759
#10 0x00007ffff5c856d5 in video_output_cur_frame (video=0x5555561aac60) at ../libobs/media-io/video-io.c:142
#11 video_thread (param=0x5555561aac60) at ../libobs/media-io/video-io.c:188
#12 0x00007ffff4cc23e9 in start_thread () at /usr/lib/libpthread.so.0
#13 0x00007ffff4bf0293 in clone () at /usr/lib/libc.so.6
```

**Comment by kkartaltepe** [comment]
Works when not using xvid. Id recommend not using an ancient encoder.

**Comment by Twiggeh** [comment]
@kkartaltepe Yeah Davinci Resolve is really a pain with encoders, this is like the only stable option that to record & edit on linux without needing to transcode videos or switch to windows to edit them.

**Comment by Fenrirthviti** [comment]
Just record to mkv (or flv if you don't need multiple audio tracks) and remux after. Remux happens at the speed of disk should only take a few seconds at most. File -> Remux Recordings from the OBS menu.

**Comment by Twiggeh** [comment]
This is  a workaround, you should keep this issue open because it is still a bug
