### ISSUE TITLE
macOS Focusrite Audio Interface missing

### ISSUE THREAD

**Issue by unknowndomain** [obsproject/obs-studio#3734]
## Platform
Operating system and version: macOS Catalina 10.15.7
OBS Studio version: 25.x + 26.x

## Expected Behavior
Audio interfaces be available as an audio input capture.

## Current Behavior
The interface only appears in Settings > Audio > Mic/aux

## Steps to Reproduce
1. Connect a FocusRite Scarlette 2i2, 4i4, 18i20 etc... USB UAC class compliant interface
2. Verify it works in other places
3. Open OBS
4. Add a scene with Audio Input capture
5. Device absent.
6. Go to Settings > Audio
7. Device present in mic/aux list

## Additional information
Verified by two users, @unknowndomain (Scarlette 4i4) and ChuckW. (Discord User) (Scarlette 18i20)

**Comment by OlliV** [comment]
Focusrite Scarlett 2i2 3rd gen appears to work fine with macOS 10.15.7 and OBS 26.1.0.

**Comment by Fenrirthviti** [comment]
Is this issue still present in current release (28.0.3)?

We do not have access to this device on the team, so we cannot test ourselves but it is working fine with other similar interfaces, and the most recent comment indicates that this is working properly.

**Comment by Fenrirthviti** [comment]
Closing as stale. If this is still an issue please open a new issue with updated reproduction steps on the latest version of OBS.
