### ISSUE TITLE
Wanted: OBS 26.0.2 streaming or recording fails with "av_interleaved_write_frame failed:" in logs

### ISSUE THREAD

**Issue by eric** [obsproject/obs-studio#3738]
# Tracking Issue

Pull request #3460 introduced error checking for `ffmpeg-mux` in OBS 26.0.2 to no longer silently fail on encoder errors. To help identify common themes please link to other related GitHub issues **if** they include logs that contain `av_interleaved_write_frame failed: `.

### This is only tracking issues with log messages containing `av_interleaved_write_frame failed:`

If there are no log messages containing `av_interleaved_write_frame failed:` it is a separate issue.

An example of such a log message is:

```
17:56:42.090: [ffmpeg muxer: 'adv_stream'] ffmpeg-mux: av_interleaved_write_frame failed: Invalid data found when processing input
```

**Comment by eric** [comment]
In #3629 in log file `2020-10-18 17-54-36.txt` it contains:

```
17:55:34.174: [ffmpeg muxer: 'adv_stream'] ffmpeg-mux: av_interleaved_write_frame failed: Invalid data found when processing input
17:55:34.174: [mpegts @ 0000027fe40f48c0] H.264 bitstream malformed, no startcode found, use the video bitstream filter 'h264_mp4toannexb' to fix it ('-bsf:v h264_mp4toannexb' option with ffmpeg)
```

I've added a check in #3737 to not fail on `AVERROR_INVALIDDATA` to try to prevent this from causing failures.

**Comment by RytoEX** [comment]
As #3737 and subsequent fixes have been merged, should we close this now?  Or are we still investigating other possible errors?

**Comment by eric** [comment]
I would be willing to close it. It seems the two errors we are handling as non-fatal were the only ones to be showing up regularly.
