### ISSUE TITLE
Audio Issues on Magewell Eco Capture and Blackmagic DeckLink Quad 2

### ISSUE THREAD

**Issue by OscarParzon** [obsproject/obs-studio#3748]
Windows 10 Pro
OBS 26.0.2 (64)

two different issues with audio on two different devices.

Device: Magewell, Eco Capture Dual SDI M.2
when adding as "video capture device" there is no audio. video Ok.
the audio works correctly if it is selected as the auxiliary input source in: "Settings", "Audio", "Global Audio Devices".
the device works correctly with other software.

Device: Blackmagic, DeckLink Quad 2
When adding as "Blackmagic Device", the audio and video are played correctly.
When selecting as an audio source in: "Settings", "Audio", "Global Audio Devices", any input is heard with noise (saturated?).

the device works correctly with other software.

**Comment by Fenrirthviti** [comment]
Please fill out the issue template.

**Comment by OscarParzon** [comment]
> Please fill out the issue template.

Aha...

**Comment by OscarParzon** [comment]
Regarding the broken audio (saturated, noisy) of the DeckLink Quad 2. Everything remains the same. Being in clean Windows, just installed, you try to put an entry in: "Settings", "Audio", "Global Audio Devices", the audio enters dirty.

Regarding the lack of Magewell audio, Eco Capture Dual SDI M.2
solution: "format c: /s" and good show !!

previously:
An attempt was made to uninstall the drivers and retouch the boards from their slots. it didn't work.
delete files and / or folders installation and / or configuration, uninstall and reinstall OBS did not work either.

The solution of Format and reinstall OS and Soft is not a real solution, we do not know when or why the error occurs again (difficult when one is working with difficulties!).

Yes, Yes! ... I should be more neat and attentive to the directives of the place, but I'm in a hurry and I'm old.

**Comment by Fenrirthviti** [comment]
If reinstalling the OS corrects the issue, sounds like an environment problem rather than anything with OS. If you are unwilling to properly fill out the issue template, there is nothing we can do as the template has the information required for this to be actionable.

**Comment by OscarParzon** [comment]
> Si reinstalar el sistema operativo corrige el problema, suena como un problema ambiental en lugar de algo con OBS. Si no está dispuesto a completar correctamente la plantilla de problemas, no hay nada que podamos hacer, ya que la plantilla tiene la información necesaria para que sea procesable.

Okay, Joel, I thank you very much for your help.

**Comment by OscarParzon** [comment]
good. what was said. It didn't work!
Reinstalling the OS did not solve the problem and it happens again:
Device: Magewell, Eco Capture Dual SDI M.2
when adding as "video capture device" there is no audio. video Ok.
the audio works correctly if it is selected as the auxiliary input source in: "Settings", "Audio", "Global Audio Devices".
the device works correctly with other software.

We know that, in clean install, when you configure it for the first time, it works correctly. When restarting Windows (or restarting OBS), the device runs out of audio (remember that it works correctly if we include it as "Global Audio Devices" !!. (For now the only solution).

I am very sorry that the rules do not allow to have the necessary information to solve the problem with the usual speed and haste in this beautiful place. But I'm sure my few and messy lines will serve someone else who has the same problem (or not ...)

**Comment by OscarParzon** [comment]
I found the source of the problem. When I physically remove the Quad 2 from the motherboard (unplug from the PCi slot. It is not placed inside the PC), the Eco Capture audio appears "Magically", without touching anything.

To add more data, I remove the "DeckLink Quad 2" board, but a Blackmagic "Monitor" board remains plugged in (sdi and HDMI output only) and the Blackmagic drivers and software are still installed.

I have another BlackMagic board, during the afternoon or morning I'm going to try plugging in another DeckLink with SDi input to see if Eco Capture continues to work.
Another test to be carried out, maybe tomorrow, is the same machine with the same boards but on Linux.

I don't understand why it says that the problem is closed. Do I have any way to announce it as open?
