### ISSUE TITLE
New scene switcher entries don't save - unless I manually restart the OBS application

### ISSUE THREAD

**Issue by Cubly** [obsproject/obs-studio#3751]
## Platform

Operating system and version: Windows 10 1909
OBS Studio version: 26.0.2

## Expected Behavior

When adding a new application and scene to the (built-in) automatic scene switcher it should save immediately. 
When my PC then restarts, the new entry would then still be present.

## Current Behavior

I add a new application and scene to the scene switcher, then once I turn my pc on the next day, the entry is missing.
It only stays if I manually close OBS after adding it and then re-open it before a PC shutdown.

## Steps to Reproduce

1. Add new entry to scene switcher
2. Restart PC (with OBS still open)

## Additional information

I have OBS open on system start and run replay buffer, once I shutdown my PC at night and start it up the next day, the entry to automatic scene switcher I made is missing, but any new scenes/sources I added are still present.

**Comment by WizardCM** [comment]
Just to confirm, this is for the built-in Automatic Scene Switcher, and not the third party Advanced Scene Switcher?

**Comment by Cubly** [comment]
This is built in automatic scene switcher. Sorry if that wasn't clear!

**Comment by PatTheMav** [comment]
@WizardCM Looks like the close button has an event handler connected to it that calls `done()` but `obs_frontend_save` is only called in `SceneSwitcher::closeEvent`, and that event is not(!) triggered by clicking on close, but only when closing the widget with the window control (circumventing the close button).

**Comment by Cubly** [comment]
Kind of related, but not specific to this issue: the same kind of thing happens with the update popups, if I click skip version, it doesn't save that unless I manually close OBS and reopen it.

**Comment by gxalpha** [comment]
Fixed by #8626
