### ISSUE TITLE
Pulseaudio audio input channels mixed together

### ISSUE THREAD

**Issue by bdrung** [obsproject/obs-studio#3754]
## Platform
Operating system and version: Ubuntu 20.04 LTS (focal)
OBS Studio version: 25.0.3+dfsg1-2

## Expected Behavior
I am using a Behringer XR 18 mixing console as input audio source for OBS via pulseaudio. The mixer provides 18 channels. OBS does not provide an option to select the channels to use. I expect that OBS takes the first two channels (as left and right stereo channel), because the first two channels contain the main mix. Parallel to the usage of OBS, I want to record the 18 channels with Audacity for later use.

## Current Behavior
OBS mixes the channels together. For example, channel 4 was mixed into the record.

## Steps to Reproduce
1. Connect an audio device with more than two channels to your system
2. Click on the plus sign in "Sources" and select "Audio Input Capture (PulseAudio)"
3. Select this audio device in the "Device" drop-down menu
4. Start the recording
5. Produce audio signal in channel >= 3
6. Check if the produced audio signal appears in the recording

**Comment by Fenrirthviti** [comment]
This is not a bug, this is expected that all channels are included in the final mix right now. Feel free to show your support for better channel management here: https://ideas.obsproject.com/posts/199/multichannel-audio-interface-support-for-mac

Or check out the rematrix plugin which allows channel selection here: https://obsproject.com/forum/resources/rematrix-filter-plugin.620/

**Comment by bdrung** [comment]
Thanks for your quick feedback. I tried out the rematrix plugin, but this plug-in did not show all 18 channels, but only one. So it was useless.

I found a different solution: PulseAudio supports remapping the channels. This is the command that I am using now:
```
pactl load-module module-remap-source source_name=XR18-stereo remix=no \
    master=alsa_input.usb-BEHRINGER_X18_XR18_5C514753-00.multichannel-input \
    master_channel_map=front-left,front-right channels=2 source_properties="device.description=Behringer_XR18_Stereo"
```
