### ISSUE TITLE
Volume's lowest value is "-inf dB"

### ISSUE THREAD

**Issue by Vainock** [obsproject/obs-studio#3763]
## Platform

Operating system and version: Windows 10 20H2
OBS Studio version: 26.0.2-91-g3e7e99e0 (https://github.com/obsproject/obs-studio/commit/3e7e99e0f33454200d4f951f1d6672459e05c793)

## Expected Behavior

Cap the volume at -96.0 dB.

## Current Behavior

If you go lower than -96.0 dB in the advanced audio properties or the audio mixer, the number turns into "-inf dB":
![Pic](https://user-images.githubusercontent.com/39059951/100114573-dbdfee00-2e71-11eb-84e1-d09d4de4e167.png)

## Steps to Reproduce

1. Use the volume slider or the advanced audio properties to set the volume to under -96.0 dB. If you are using the volume slider, just 'slide' to the farthest left. If you are using the advanced audio properties you have to use your arrow keys on your keyboard or the buttons next to the input field.

## Additional information

Not sure about this issue's title, likely does not represent exactly what happens in the background.

**Comment by derrod** [comment]
This is accurate, as the volume is literally set to "minus infinity", which is also an industry standard way of labelling that setting in audio mixing software. -96 dB would be nearly inaudibly quiet, but the sound would technically still be there.

**Comment by mufunyo** [comment]
I thought we changed this from "inf" to "∞"?
