### ISSUE TITLE
Feature Parity

### ISSUE THREAD

**Issue by DarkBlaez** [obsproject/obs-studio#3764]
Not sure if I have this right but has I understand it Browser Docks are not in the Mac version. What is the plan for feature parity across all platforms? Again, perhaps I am mistaken but I think this is the case since version 25

DB

**Comment by WizardCM** [comment]
You can keep an eye on macOS Browser Docks @ https://github.com/obsproject/obs-browser/pull/197

Currently there is nobody working on Browser Docks for Linux. Palakis was able to put in some effort, but quickly realised the entire thing will be very complicated and didn't have time to dig into it further.

**Comment by DarkBlaez** [comment]
Thanks appreciate the quick response. I can contribute cross-platform for both MacOS (registered developer) and Linux. Just wanted to see where things stood. I'll keep an eye on the effort and see where I can contributed. 

Thanks
DB
