### ISSUE TITLE
AMD Encoder Bitrate Issue

### ISSUE THREAD

**Issue by DOGGYBONEGAMING** [obsproject/obs-studio#3767]
## Platform

Operating system and version: Windows 10 Home 
OBS Studio version: 26.0.2

## Expected Behavior

Allow to change the bitrate to anything you enter and function just like the any other encoder.
## Current Behavior

When you have the AMD encoder as the chosen option the bitrate can't be set to anything pass 1 or just two zeros. Any other encoder bitrate works as expected allowing to type anything but the AMD encoder.
## Steps to Reproduce

1. Choose advance for streaming settings.
2. Select AMD encoder.
3. Try changing bitrate.
4. No changes allowed passed 1 or zeros.

**Comment by WizardCM** [comment]
This is an issue with the latest AMD drivers. Try downgrading to 20.11.1. AMD are aware of the issue.

**Comment by DOGGYBONEGAMING** [comment]
> This is an issue with the latest AMD drivers. Try downgrading to 20.11.1. AMD are aware of the issue.

Thank you for the info! I'll be trying that out now as it worked just wonders a few days ago until I updated my PC on everything like lastest Windows updates and my GPU drivers.
