### ISSUE TITLE
Log-viewer : Display number of time an entry in log file appear if repeated.

### ISSUE THREAD

**Issue by Trouffman** [obsproject/obs-studio#3769]
(Thanks for the good work on OBS!)

Log-Viewer is not showing the new lines in log if this reached MAX_REPEATED_LINES.

## Platform
Windows 10 - 2H2020 update
OBS Studio version: 26.0.2
OBS-NDI 4.9.0
Advanced Scene switcher

## Expected Behavior
Log-Viewer should display the number of repeated time the last line of log appears.

In the OBS Log-viewer : Having the last line as "Last log entry repeated for XX more lines" and only update the XX part based on MAX_REPEATED_LINES would be nice.

## Current Behavior
Repeated log entry are counted and written/displayed only once a new/different line in logging is written.
Managed by : too_many_repeated_entries()

When in the log-viewer, if the entry is repeated XX times it will be written in the log files as "Last log entry repeated for XX more lines" as soon as a new/different line will be added.

This can be confusing as it does not appear in the Log-viewer with incremental number until another (different line is added).

This is the function related to this :
https://github.com/obsproject/obs-studio/blob/2902cdb2ff04ab19a304826765f275728a410602/UI/obs-app.cpp#L332-L337

## Steps to Reproduce
1. Get something to log the same line over an over again.
> install the Advanced Scene Switcher ( https://obsproject.com/forum/resources/advanced-scene-switcher.395/ )
> Activate verbose logging
> Start the A.S.S.
2. open OBS log-viewer
3. Do nothing. A.S.S. should be logging in there

After 30 lines, no new log-lines appears, no way to know if things are still working/checked

## Additional information
Note : I first though that it was an ASS issue : https://github.com/WarmUpTill/SceneSwitcher/issues/67

**Comment by WizardCM** [comment]
Potential workaround: Launch OBS with the `--verbose` flag which removes the "[..] repeated" filter.

**Comment by Trouffman** [comment]
Looks like this would be the solution : 
--unfiltered_log | Disable log filter (do not suppress repeated lines).

Source : https://obsproject.com/wiki/Launch-Parameters

Is there a way to define this option in the config file ?

**Comment by RytoEX** [comment]
It is impossible to tell when a log line has finished being repeated until a non-repeated line is about to be logged. Logging incrementally defeats the purpose of avoiding log spam:
```
Last log entry repeated for 1 more lines
Last log entry repeated for 2 more lines
Last log entry repeated for 3 more lines
Last log entry repeated for 4 more lines
Last log entry repeated for 5 more lines
```

Logging a counted repeat number periodically is a feature request, and not a bug, as this is currently working as designed.
