### ISSUE TITLE
Muxer/Encoder settings containing decimal points should NOT respect system locale

### ISSUE THREAD

**Issue by GranPC** [obsproject/obs-studio#3770]
## Platform

Operating system and version: elementary OS 5.1.4
OBS Studio version: 26.0.0 - installed from PPA

## Expected Behavior
Muxer/encoder settings that take decimals (such as `hls_time`) should always use `.` as a decimal separator

## Current Behavior
On a system with locale `LC_NUMERIC=es_ES.UTF-8`, decimals are expected to use `,` - otherwise, an "Invalid argument" error is shown.

```21:54:34.617: Using muxer settings: 
21:54:34.617: 	hls_time=0.5
21:54:34.617: 	hls_init_time=0.5
21:54:34.617: 	hls_list_size=3
21:54:34.617: Error opening '/home/granpc/hls/wtf-locales.m3u8': Invalid argument
21:54:34.618: ffmpeg_data_init failed
21:54:34.619: ==== Recording Stop ================================================
```

Using the local decimal separator (`,`) causes a corrupted file to be written.

```#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:1
#EXT-X-MEDIA-SEQUENCE:2
#EXTINF:0,500000,
wtf-locales2.ts
#EXTINF:0,500000,
wtf-locales3.ts
#EXTINF:0,500000,
wtf-locales4.ts
```

Notice how EXTINF is using comma as a decimal separator. This kills the HLS file.

## Steps to Reproduce

1. Set your system locale to any of the places in the world that don't use dots as a decimal separator, such as Spain
2. Configure OBS to record to an HLS file with `hls_time` set to a value with decimal places:
2.1. Settings > Output > Recording
2.2. Set type to "Custom Output (FFmpeg)" and output to a file
2.3. Set container format to `hls`
2.4. Set Muxer Settings to `hls_time=0.5 hls_init_time=0.5 hls_list_size=3`
2.5. Any other parameters can be left as default
3. Attempt to initiate the recording
4. Watch as it immediately errors out

## Workaround

Move to another country. Or alternatively, run OBS with `LOCALE=C LC_NUMERIC=C LANG=C LANGUAGE=C obs`.

**Comment by kkartaltepe** [comment]
Cannot replicate. `LOCALE=C LC_NUMERIC=C LANG=C LANGUAGE=C obs` fails with your settings the same as `es_ES.UTF-8`

mpv also plays back files with commas in the `#EXTINF` field, so im not sure that your diagnosis is correct.

**Comment by GranPC** [comment]
Upgraded to 26.0.2 and still seeing the same issue, unless `LC_NUMERIC=C`. Setting that environment variable allows me to use decimals, with the exact muxer settings I posted.

As for MPV playing back files with commas in the field, while that is possible, it's a violation of RFC 8216, in which section 4.2 specifies:

>   o  decimal-floating-point: an unquoted string of characters from the
>      set [0..9] and '.' that expresses a non-negative floating-point
>      number in decimal positional notation.

`,` is not an allowed character in decimal floating points in a properly formed HLS file. Safari for iOS refuses to play back an HLS file with `,` in `#EXTINF`, and other implementations may also fail.

**Comment by kkartaltepe** [comment]
hmm it seemed localectl wasnt playing nice, I was able to get the recording to work with LANG=C.

**Comment by kkartaltepe** [comment]
Looks like its not our bug unfortunately. The strings you see printed with `.` are exactly what we are passing to ffmpeg. Within ffmpeg it seems they are being converted in a locale sensitive way.

**Comment by GranPC** [comment]
Interestingly, it workw fine in the ffmpeg command line, and the output isn't malformed there. :thinking:

**Comment by kkartaltepe** [comment]
we are not using the ffmpeg commandline so it's only a vague approximation. Its possible ffmpeg cli' forces C locale because it knows this an issue. im not sure how it behaves.

**Comment by GranPC** [comment]
A quick glance at the ffmpeg codebase doesn't seem to reveal any locale wizardry.

```granpc@gram:~/tmp/FFmpeg$ find . -type f | xargs grep locale
./libavcodec/ppc/asm.S:    .localentry X(\name), .-X(\name)
./configure:# Prevent locale nonsense from breaking basic text processing.
./configure:# Avoid locale weirdness, besides we really just want to translate ASCII.
./compat/solaris/make_sunver.pl:# Enforce C locale.
```

I really think this is worth investigating; I would do it myself if I had the time. I've spent over 5 months trying to figure out what was going on, and I only figured it out today on a whim.

**Comment by GranPC** [comment]
You rock! Thank you @kkartaltepe!

**Comment by kkartaltepe** [comment]
Even after that commit lands it will just let you successfully initialize the muxer. It will still output with comma's in the EXTINF because we _are_ a locale aware application i dont think we can leave everything in "C" locale. But using C locale is the only way to get ffmpeg to mux correctly for HLS it seems.

ffmpeg cli never initializes locale information so it is unaffected by whatever locale you might be using.

**Comment by GranPC** [comment]
I was actually thinking just that. And I guess since ffmpeg runs in its own thread there's no real way to switch back and forth between locales, since that would cause a bunch of other issues with the threading, right?

I take it the only proper way to fix this would be to submit a fix upstream?

**Comment by kkartaltepe** [comment]
The only way to fix it is indeed to make ffmpeg play nicely in a locale aware environment. I might change the fix around and just set LC_NUMERIC on start and hope no one changes or wanted to see their local numeric format.

**Comment by GranPC** [comment]
Awesome, thanks for the fix @jpark37!
