### ISSUE TITLE
error: Failed to initialize video.  Your GPU may not be supported, or your graphics drivers may need to be updated.

### ISSUE THREAD

**Issue by zdavatz** [obsproject/obs-studio#3776]
I am running Gentoo Linux with Kernel 5.9.0

1. Install obs-studio from source, using these steps: 
```
git clone --recursive https://github.com/obsproject/obs-studio.git
cd obs-studio
mkdir build && cd build
cmake -DUNIX_STRUCTURE=1 ..
make -j4
sudo make install
```
2. run `/usr/local/bin/obs
3. results in 
![latest-screenshot](https://user-images.githubusercontent.com/4953/100320781-fde88600-2fc1-11eb-86c7-9b4f4bff8976.png)
4. Attached logfile: [2020-11-26 08-29-13.txt](https://github.com/obsproject/obs-studio/files/5601119/2020-11-26.08-29-13.txt)
5. `glxinfo | grep OpenGL` results in
```
OpenGL vendor string: Mesa Project
OpenGL renderer string: Software Rasterizer
OpenGL version string: 2.1 Mesa 19.1.7
OpenGL shading language version string: 1.20
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 19.1.7
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
OpenGL ES profile extensions:
```

**Comment by Fenrirthviti** [comment]
Please use the Discord or forums for assistance.

**Comment by zdavatz** [comment]
Ok, thank you, then I will try to install OpenGL from source.

**Comment by Fenrirthviti** [comment]
That's not how it works. OpenGL is a hardware function, not software. Your GPU does not support the minimum requirements to run OBS, you will need to use a different machine.

**Comment by zdavatz** [comment]
Ok, that is very interesting, thank you. I just bought a new `Nvidia GP107` card and it runs great with Nouveau and the latest kernel. Is Nvidia not supported? I would think my card should handle Video well.

**Comment by Chiitoo** [comment]
Considering

```
OpenGL vendor string: Mesa Project
OpenGL renderer string: Software Rasterizer
```

it looks like nouveau might not be being used, but that's kind of getting off-topic here.  :]

**Comment by zdavatz** [comment]
I am not using any Nvidia closed source drivers at the moment. I am only using what is in the Kernel and Gentoo supplies via emerge.

**Comment by Chiitoo** [comment]
Right, but I believe you should be seeing something along the lines of

```
OpenGL vendor string: nouveau
```

instead of Mesa Project.

Perhaps check the Gentoo wiki and/or forums/IRC to make sure things are set up right-like.

**Comment by zdavatz** [comment]
My setup is correct AFAICT. Everything works fine, only obs-studio is not working (but it does compile and install). Does it work on your Gentoo machine? If yes, what Graphics Card do you have?

**Comment by Fenrirthviti** [comment]
Again, please use the forums or Discord for support. This is not an appropriate place to troubleshoot environment issues.

**Comment by zdavatz** [comment]
@Fenrirthviti I do think obs-studio should offer a solution that is not based on Nvidia proprietary drivers and that works out of the box for Nouveau Users. FYI.

**Comment by Fenrirthviti** [comment]
We don't have any dependency on NVIDIA proprietary drivers, this is purely an issue with your environment not running properly, not OBS.
