### ISSUE TITLE
LIBOBS Set Master Volume not working

### ISSUE THREAD

**Issue by PeterAkakpo** [obsproject/obs-studio#3786]
## Platform

Operating system and version:  Window 10
OBS Studio version: 26.02

## Expected Behavior

A call to **obs_set_master_volume** must set the overall volume level

## Current Behavior

Nothing happens, no change in volume

## Steps to Reproduce

1.  call **obs_set_master_volume** passing any value between 0 and 1
2.
3.
4.

**Comment by WizardCM** [comment]
You are correct. Looking at the code, the API does change the `obs_core_audio` `user_volume` value (and can be fetched using `obs_get_master_volume`), but that value isn't used anywhere.

As the API was added by Jim 7 years ago, very early on in the project, it's possible it was just never implemented, or was scrapped in favour of something different.

Could you elaborate on your use case?
