### ISSUE TITLE
26.1.0-rc1 - Ignore or enforce stream settings for ingest ?

### ISSUE THREAD

**Issue by maxdrash** [obsproject/obs-studio#3787]
## Platform

Operating system and version: Debian 10.6
OBS Studio version: 26.1.0-rc1

## Expected Behavior
Force encoder to limit capacity for streaming service.

## Current Behavior
Following improvement on 26.1.0-rc1:
"Changed the “Enforce Streaming Service Bitrate” to “Ignore streaming service setting recommendations”, moved it to the Streaming section of the Settings window, and made it so it now affects both Simple and Advanced output modes. [Jim]"

Two check box in two different panels.
What checkbox means to ?
Can you simplify ?

## Steps to Reproduce

1. 
![image](https://user-images.githubusercontent.com/17526713/100514947-0f27c300-3179-11eb-9257-55ccea73883f.png)

2. 
![image](https://user-images.githubusercontent.com/17526713/100514955-164ed100-3179-11eb-945e-662cf2d05ae3.png)

Thanks !

**Comment by WizardCM** [comment]
Fixed in https://github.com/obsproject/obs-studio/commit/15d000c50c88beb8a0064e206d1ddf317a837d6b
