### ISSUE TITLE
26.1.0-rc1 - Virtual Camera output on Linux fail to find modprobe

### ISSUE THREAD

**Issue by maxdrash** [obsproject/obs-studio#3788]
## Platform

Operating system and version: Debian 10.6
OBS Studio version: 26.1.0-rc1

## Expected Behavior
Click on "Start Virtual Camera" and get a virtual camera device.

## Current Behavior
Click on "Start Virtual Camera" and get a message in logs:
"Cannot run program modprobe: No such file or directory"
And no window error popup.

In Debian based OS, users won't get access to modprobe at level user, they need to pass modprobe command through sudo.

## Steps to Reproduce

1. Click on "Start Virtual Camera" .
2. Get: Cannot run program modprobe: No such file or directory in log.

**Comment by Gol-D-Ace** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=918754

**Comment by kkartaltepe** [comment]
You need to add modprobe to your path.

**Comment by maxdrash** [comment]
Thats right, like Ubuntu, I had to add /usr/sbin to $PATH.
I have a popup for asking to sudo password now.

I suggest to close this ticket.
