### ISSUE TITLE
LUA: Signal handler for source_activate/source_deactivate not triggering on all source types in studio mode

### ISSUE THREAD

**Issue by 22hn** [obsproject/obs-studio#3789]
## Platform

Operating system and version: Windows 10 2004
OBS Studio version: 26.0.2 64-bit

## Expected Behavior
When in studio mode, handler should trigger on every source type that supports duplication

## Current Behavior
Handler only triggers on some source type (or maybe even just one)

## Steps to Reproduce
Activate studio mode
Create a scene with 3 different source types, one Media, one Image and one Text (GDI+)
Make all 3 items visible
Load script below
Open script log window
Doubleclick scene to make it go live, this will show in script log
Hide the Media source and do a transition, the deactivation will show in script log
Now hide the Image source and do the same. Nothing in log!
The same goes for the Text source...

## Script code
```lua
obs			= obslua
debug		= true

-- add handlers
function script_load(settings)
	if debug then print ("Loading...") end
	local sh = obs.obs_get_signal_handler()
	obs.signal_handler_connect(sh, "source_activate", source_activated)
	obs.signal_handler_connect(sh, "source_deactivate", source_deactivated)
	print ("Loaded")
end

function source_activated(cd)
	if debug then print ("(source_activated called)") end
	local source = obs.calldata_source(cd, "source")
	if source ~= nil then
		local name = obs.obs_source_get_name(source)
		print ("Activated: " .. name)
	end
end

function source_deactivated(cd)
	if debug then print ("(source_deactivated called)") end
	local source = obs.calldata_source(cd, "source")
	if source ~= nil then
		local name = obs.obs_source_get_name(source)
		print ("Deactivated: " .. name)
	end
end
```

**Comment by exeldro** [comment]
Some sources can be duplicated in studio mode, did you try and disable the duplicate sources option?
![image](https://user-images.githubusercontent.com/5457024/100518998-6cca0880-3195-11eb-92ed-dd79de3cca28.png)

**Comment by 22hn** [comment]
Ahhh, that's it. Thank you!

**Comment by 22hn** [comment]
Actually no... We do need to run in duplicate sources mode...

Reason is that when we bring up a name tag during live stream, we want to verify that it contains the correct name before sending it to the program feed. When checked, we do a transition... And this is what I want to capture in the script!

The idea is to make script that will wait 10 sec, then hide the name tag again and do a transition (if the scene is still the same!) to make it disappear again on the program feed.

It says in the "duplicate source" description that sources like capture & media won't work (actually, media is the one that do work!), but one would think that a simple source like text should work...?

**Comment by 22hn** [comment]
Changed expected behavior to:
When in studio mode, handler should trigger on every source type that supports duplication

**Comment by 22hn** [comment]
Any news on this...?

**Comment by exeldro** [comment]
This might be connected to sources having no name when duplicated #3819

**Comment by RytoEX** [comment]
Please confirm if this is still an issue in OBS Studio 28.0.3 (or newer).

**Comment by gxalpha** [comment]
Closing as there has been no response in 4 months and the PR that potentially fixed the issue has been merged and released for some time.
