### ISSUE TITLE
OBS Settings Video FPS changing in software

### ISSUE THREAD

**Issue by LaCieMouSe** [obsproject/obs-studio#3793]
## Platform
Operating system and version: Windows 10 2004 20H2
OBS Studio version: 26.0.2

## Expected Behavior
What happened was that during my stream or just normal use of OBS preview and stream would show 30fps at certain moments at random and then switch back to 60fps at random. In beginning I thought this was due to heavy load on CPU of GPU but none were overloading and logs were not showing anything wrong.

## Current Behavior
Normal 60fps or everything I can see on my monitor

## Steps to Reproduce
Like I said it is from the start of starting OBS normal for me to see this behaviour that it seems to switch between 30fps and 60fps.

However if I change OBS Settings in Video the fps of the output to 30fps apply and back to 60fps apply its gone until I restart OBS. I'll provide 2 links for logs. 1 were I didn't change and 1 after the change in settings

Before: https://obsproject.com/logs/ZW5B4lraAxn-zJdQ
After: https://obsproject.com/logs/EuZxrmNOOvr6qFS_

To be short I am able to reproduce my problem but I don't think somebody else will unless they start with the same problem.

What I tried:
Reinstall OBS and add my scenes and sources one by one
Reinstall Nvidia drivers with a DDU
Reinstall windows
Updat windows to 20H2
All settings in Nvidia control panel.
All settings in OBS except for output FPS untill a friend told me as a joke you should stream at 30fps then maybe it will always be the same that I thought hey why not... but it was too bad and changed it back and that was how i figured this out.

**Comment by WizardCM** [comment]
Please use the Discord or forums for support.

**Comment by LaCieMouSe** [comment]
Discord send me here because it fixed my problem so someone can try it out.
