### ISSUE TITLE
libobs-opengl: gs_sampler_info->border_color is ignored

### ISSUE THREAD

**Issue by Xaymar** [obsproject/obs-studio#3794]
## Platform

Operating system and version: Windows 10 2004
OBS Studio version: master / 26.1-rc1

## Expected Behavior
gs_sampler_info->border_color should not be ignored by the OpenGL renderer.

## Current Behavior
gs_sampler_info->border_color is ignored by the OpenGL renderer.

## Steps to Reproduce

1. Use gs_sampler_info->border_color for any purpose.
2. Fail to do so on OpenGL

## Additional information
- [gs_sampler_state has no border color entry.](https://github.com/obsproject/obs-studio/blob/master/libobs-opengl/gl-subsystem.h#L376)
- [Which causes the setting to be ignored](https://github.com/obsproject/obs-studio/blob/master/libobs-opengl/gl-subsystem.c#L165)

**Comment by Xaymar** [comment]
Closing as requested.

**Comment by alessionossa** [comment]
I'm still experiencing issues related to this (through [StreamFX](https://github.com/Xaymar/obs-StreamFX/issues/245)), even if this issue has been closed.

**Comment by alessionossa** [comment]
I am still experiencing this issue on OBS Studio 27.2.2
![border screenshot](https://user-images.githubusercontent.com/17525117/156917771-13d38a87-22bb-4fbe-b410-235f6542a890.png)

**Comment by alessionossa** [comment]
Further investigating the issue with StreamFX's developers, they reported the following:

> if the Problem still occurs that means that the upstream bug has not been fixed. As the problem does not occur with the DirectX backend in OBS, which is as far as I'm aware the standard for OBS rendering, the upstream issue should be reopened. If they request an example of how it is broken, they can look at these files:
> 
> https://github.com/Xaymar/obs-StreamFX/blob/master/data/effects/sdf/sdf-producer.effect#L48
> https://github.com/Xaymar/obs-StreamFX/blob/master/data/effects/sdf/sdf-consumer.effect#L22
> Both of these files work fine under DirectX, but are broken with the OpenGL backend.

**Comment by alessionossa** [comment]
Is there any chance that this issue will be reconsidered and investigated again, since it has not been been resolved yet?

**Comment by Fenrirthviti** [comment]
OpenGL isn't really supported on Windows, it's been deprecated for years now, so it's unlikely anyone from our core team will spend time looking in to this. If a fix is submitted, we'd be happy to review it, however.

**Comment by alessionossa** [comment]
Actually, I am facing the issue on macOS. For now I have never worked with graphic libraries, so I don't know where to start, but if that's the situation, I can give it a try in the future.
