### ISSUE TITLE
Source Toolbar: Doesn't update after transitioning in Studio Mode

### ISSUE THREAD

**Issue by xathon** [obsproject/obs-studio#3796]
## Platform

Operating system and version: Windows 10
OBS Studio version: 26.0.2

## Expected Behavior
The properties window opens when clicking on the properties button in the source toolbar for a source that's currently on Program.

## Current Behavior
Nothing happens when clicking on the properties button in the source toolbar for a source that's currently on Program.

## Steps to Reproduce
1. Enable Studio mode.
2. Select a source from the Preview scene that is not on the current live scene.
3. Transition the Preview scene to Program.
4. Click the Properties button in the Source Toolbar.

## Additional information
The filter button and media controls work.

**Comment by WizardCM** [comment]
This is easiest to verify by having two different scenes and using the default Fade quick transition button.

Essentially, when the transition has ended, the Source Toolbar doesn't update, causing it to be in a slightly confused state.

**Comment by RytoEX** [comment]
Cannot reproduce in OBS Studio 28.0.3. If you can still reproduce this in OBS Studio 28.0.3 (or newer), please confirm that this is still a problem, and please provide a new OBS log and new Steps To Reproduce, and we can consider reopening this Issue.
