### ISSUE TITLE
Incorrect color space on macOS 

### ISSUE THREAD

**Issue by RoadToDream** [obsproject/obs-studio#3798]
## Platform

Operating system and version: macOS 10.15.7 
OBS Studio version: 26.0.2

## Expected Behavior

Color recorded in OBS studio should be the same as on screen when selecting default color profile 
## Current Behavior

Recorded video have washed out color when using default default color profile "Color LCD"
## Steps to Reproduce

1. Choose default color profile "Color LCD" in System preference->Displays->Color
2. Open OBS and start recording

## Additional information

Problem will be solved if selecting sRGB color profile, but system color will be over saturated on P3 monitor.

**Comment by Fenrirthviti** [comment]
Please use the forums or Discord for support.

**Comment by mufunyo** [comment]
OBS is currently not colour managed. It's on the roadmap, but don't hold your breath.
