### ISSUE TITLE
Closing a detached browser dock using its close button on OBS built with Qt 5.11.1+ results in unresizable browser dock when reopening the dock

### ISSUE THREAD

**Issue by RytoEX** [obsproject/obs-studio#3799]
This is a follow-up to #3784 and obsproject/obs-browser#197.

## Platform

Operating system and version:  Windows 10 2004 64-bit
OBS Studio version:  26.1-rc1

## Expected Behavior

If you close an undocked browser dock by clicking its close button, reopening the dock from the View -> Docks menu should result in the browser dock spawning with its previous geometry and be able to be resized.

## Current Behavior

If you close an undocked browser dock by clicking its close button, reopening the dock from the View -> Docks menu will result in the browser dock spawning as a small window that cannot be resized.

## Steps to Reproduce

1. Open OBS.
2. Add a custom browser dock.
3. Make sure the dock is _not_ docked in OBS.
4. Close the browser dock using its close button (the X button on Windows, the red button on macOS).
5. Reopen the browser dock from the View -> Docks menu.
6. Observe that the browser dock has reopened as a small window that is not resizable.

## Additional information

This is not reproducible in OBS Studio 26.0.2 on Windows, but it is reproducible in OBS Studio 26.0.2 on macOS if building with obsproject/obs-browser#197.  This is because 26.0.2 on Windows uses Qt 5.10.1 whereas on macOS we use 5.14.1.  Given that this appears to be a Qt behavior change, I built the current git master (roughly 26.1-rc1) against various Qt versions to test:
* Qt 5.10.1 - expected behavior
* Qt 5.11.0 - expected behavior
* Qt 5.11.1 - current behavior

Then, I went through the commit log for qtbase between Qt 5.11.0 and 5.11.1 and discovered this commit:  https://github.com/qt/qtbase/commit/e0b5ff4ad583befbecbcbe462998e3ed80899531

Reverting this commit (and possibly https://github.com/qt/qtbase/commit/62b08b50d05098d8215fcf59c23096dbc7420f45), changes the behavior in OBS from the current behavior to the expected behavior.

**Comment by RytoEX** [comment]
This looks like [QTBUG-74606](https://bugreports.qt.io/browse/QTBUG-74606).

**Comment by jp9000** [comment]
We have a patch for this for now, and posted the issue on the Qt bug tracker. So I guess there's not much more we can do for now.
