### ISSUE TITLE
Can't install obs-studio on debian bullseye 5.9.0-3-amd64 Debian 5.9.9-1 x86_64 GNU/Linux

### ISSUE THREAD

**Issue by koreanfan** [obsproject/obs-studio#3800]
## Platform

Operating system and version: debian bullseye 5.9.0-3-amd64 Debian 5.9.9-1 x86_64 GNU/Linux
OBS Studio version: latest obs

## Expected Behavior
Install obs and use it

## Current Behavior

According to wiki page from official obs-studio site obs-studio installation crash on this step: install debian package
## Steps to Reproduce

1.install obs-studio form source according to wiki page
2.
3.
4.

**Comment by kkartaltepe** [comment]
Please use the discord for support.

**Comment by koreanfan** [comment]
sry i dont use discord

**Comment by koreanfan** [comment]
discord is not allowed in my company
