### ISSUE TITLE
Bug: Connect the eGPU BOX in Big Sur and the screen turns white

### ISSUE THREAD

**Issue by umentu** [obsproject/obs-studio#3808]
## Platform
Operating system and version: macOS(11.0 Big Sur)
OBS Studio version: 26.0.2
eGPU BOX: Razer Core X Aluminum External GPU Enclosure (eGPU): Compatible w/Windows & Mac Thunderbolt 3 Laptops
GPU: Radeon RX 580

## Expected Behavior
I expect the delivery screen to launch

## Current Behavior
When you connect the eGPU BOX and launch OBS, the delivery screen will be white.Adding sources does not change.

![スクリーンショット_2020-12-01_15_0_40_22](https://user-images.githubusercontent.com/10708630/100709604-c0d12900-33f1-11eb-86a8-2df867c4f128.png)

## Steps to Reproduce

1. Connect the eGPU BOX in Big Sur.
2. Run OBS studio. 
3. Add sources.

**Comment by FryMinis** [comment]
Hi! I have the same problem. Have you found a fix?

**Comment by DDRBoxman** [comment]
Seems like Big Sur may have introduced some issues with Thunderbolt 3 devices, I've had issues with a TB3 enclosure with some SDI cards even since upgrading. This eGPU issue might be related to the same OS issue.

**Comment by Fenrirthviti** [comment]
Unfortunately, eGPUs are more or less abandoned and unsupported in majority configurations by Apple at this point, so we will likely not spend any significant amount of time on a fix. However, if someone who has this issue wants to spend the time to correct it, we would be happy to review a PR for it.

**Comment by Fenrirthviti** [comment]
Even at the time, support was dubious at best. :)
