### ISSUE TITLE
Can't install obs-studio on debian bullseye. NO REDIRECT TO DISCORD, DISCORD IS NOT ALLOWED IN MY COMPANY. WHERE UR HELP OBS DEVELOPERS

### ISSUE THREAD

**Issue by koreanfan** [obsproject/obs-studio#3809]
## Platform

Operating system and version: debian bullseye 5.9.0-3-amd64 Debian 5.9.9-1 x86_64 GNU/Linux
OBS Studio version: latest obs

## Expected Behavior

Install obs and use it
## Current Behavior

According to wiki page from official obs-studio site obs-studio installation crash on this step: install debian package
## Steps to Reproduce

1.install obs-studio form source according to wiki page
2.
3.
4.

**Comment by RytoEX** [comment]
This is still a support question.  Please do not use GitHub issues for support requests, including support building OBS.

Please use our [help resources](https://obsproject.com/help) for support.

If you cannot use Discord, you can use our forums:  https://obsproject.com/forum/
Or you can use IRC from our website:  https://obsproject.com/irc
Or you can use any IRC client to connect to:  #obsproject on chat.freenode.org
