### ISSUE TITLE
Balance on mono audio track should become pan

### ISSUE THREAD

**Issue by dxf** [obsproject/obs-studio#3820]
## Platform

Operating system and version: macOS 10.14.6
OBS Studio version: 25.0.8

## Expected Behavior

When a channel is set to mono on the Advanced Audio Properties window, the balance slider should become a pan slider. Balance sliders mean that when you have an input which has audio in on channel 1 only, it's impossible to bring that input all the way to the right audio channel.
## Current Behavior

Balance slider still exists.
## Steps to Reproduce

1. Connect an audio source with only 1 channel of audio for your input (in this case, a Scarlett Solo with an XLR on channel 1)
2. Go into advanced audio properties 
3. Set source to mono

**Comment by WizardCM** [comment]
This is not a bug. Please submit feature requests to Fider https://ideas.obsproject.com/

**Comment by dxf** [comment]
Balancing on a mono track is effectively useless - isn't that a bug?
