### ISSUE TITLE
Uninstallation

### ISSUE THREAD

**Issue by baris-inandi** [obsproject/obs-studio#3821]
I uninstalled virtualcam and obs-studio but the camera devices are still visible. I tried reinstalling and finding a proper uninstallation tool that was intended to be used with virtualcam but couldn't. Also, I tried some manual techniques through the registry editor but it doesn't seem to delete the virtual camera devices from my PC. I also used the unins000.exe for OBS-studio but that executable also doesn't seem to remove virtual camera devices 
[Windows 10 64-bit]

How can I properly uninstall all devices and data associated with obs?
Thanks

**Comment by Fenrirthviti** [comment]
Please use the forums or Discord for support.
