### ISSUE TITLE
duplication of grouped Text (GD+) Elements

### ISSUE THREAD

**Issue by maasst** [obsproject/obs-studio#3822]
## Platform
Operating system and version: Win10 Enterprice LTSC
OBS Studio version: 26.0.2

## Expected Behavior
If I copy a group of Text(GDI+) elements, I expect, that all text elements are also duplications.

## Current Behavior
The group will be duplicated, but the text-elements are references.

## Steps to Reproduce

1. generate some Text(GDI+) elements
2. group them
3. copy the group
4. paste as duplication

**Comment by exeldro** [comment]
that is done here in the code:
https://github.com/obsproject/obs-studio/blob/7a17f47d8aa9c8bca1b5e2dd90a93992dfe7677f/libobs/obs-scene.c#L1359

**Comment by WizardCM** [comment]
Per the linked comment from Jim in the code, this is currently by design. If you'd like to suggest an alternative behaviour, I'd recommend https://ideas.obsproject.com/

I'd personally vote for duplicating sub-items to be a non-default option that should be exposed as an option when pasting.
