### ISSUE TITLE
Game Capture Problems/ Xbox Companion App

### ISSUE THREAD

**Issue by Haytham304** [obsproject/obs-studio#3823]
Hello All, 
I am having an issue with the Game capture of the Xbox companion app. every time I run it OBS displays stays black. It works in Window capture but it doesn't work as game capture. I was using it last week no problem. but since yesterday its not working. I'm not sure if there was an update that created the issue or not. but I tried downloading previous versions of OBS and it's still giving me issues. 

Please let me know if any one has come across this issue with the Companion App.

Thanks

**Comment by notr1ch** [comment]
Please use the forums or Discord for support requests.
