### ISSUE TITLE
Copy/Paste (ctrl + c, ctrl + a, ctrl + v) does not work in Browser Source interact

### ISSUE THREAD

**Issue by Hantick** [obsproject/obs-studio#3832]
After upgrade to 26.0.2 my browser interaction source does not support keyboard shortcuts.
## Platform

Operating system and version: Windows 10 Education 10.0.17763 compilation 17763
OBS Studio version: 26.0.2

## Expected Behavior

Shortcuts should work in interaction browser
## Current Behavior

Browser interaction source does not support keyboard shortcuts.
## Steps to Reproduce

1. Create browser scene
2. Click "interaction"
3. Click ctrl + a or ctrl + c or ctrl + v

**Comment by derrod** [comment]
Wrong repo (see https://github.com/obsproject/obs-browser).

Also the "interact" window is only a workaround for cases where some interaction is absolutely required, but generally all web based content used within OBS should be designed to work without it. Hence it is unlikely that anybody is going to actually implement those features for use with the interact feature.

**Comment by mufunyo** [comment]
Duplicate of obsproject/obs-browser#238.
