### ISSUE TITLE
26.1.0-rc2: error: implicit declaration of function 'strerror_l' is invalid in C99

### ISSUE THREAD

**Issue by yurivict** [obsproject/obs-studio#3835]
clang-10.0.1 fails to compile 26.1.0-rc2 on FreeBSD 12.2:

```
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:129:4: error: implicit declaration of function 'strerror_l' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                        berr(LOG_ERROR, "exiting due to poll error");
                        ^
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:41:24: note: expanded from macro 'berr'
                const char *errstr = strerror_l(errno, NULL);   \
                                     ^
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:129:4: note: did you mean 'strerror_r'?
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:41:24: note: expanded from macro 'berr'
                const char *errstr = strerror_l(errno, NULL);   \
                                     ^
/usr/include/string.h:91:6: note: 'strerror_r' declared here
int      strerror_r(int, char *, size_t);
         ^
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:129:4: warning: incompatible integer to pointer conversion initializing 'const char *' with an expression of type 'int' [-Wint-conversion]
                        berr(LOG_ERROR, "exiting due to poll error");
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:41:15: note: expanded from macro 'berr'
                const char *errstr = strerror_l(errno, NULL);   \
                            ^        ~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:145:5: error: implicit declaration of function 'strerror_l' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                                berr(LOG_ERROR,
                                ^
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:41:24: note: expanded from macro 'berr'
                const char *errstr = strerror_l(errno, NULL);   \
                                     ^
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:145:5: warning: incompatible integer to pointer conversion initializing 'const char *' with an expression of type 'int' [-Wint-conversion]
                                berr(LOG_ERROR,
                                ^~~~~~~~~~~~~~~
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:41:15: note: expanded from macro 'berr'
                const char *errstr = strerror_l(errno, NULL);   \
                            ^        ~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:276:3: error: implicit declaration of function 'strerror_l' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                berr(LOG_ERROR, "socketpair");
                ^
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:41:24: note: expanded from macro 'berr'
                const char *errstr = strerror_l(errno, NULL);   \
                                     ^
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:276:3: warning: incompatible integer to pointer conversion initializing 'const char *' with an expression of type 'int' [-Wint-conversion]
                berr(LOG_ERROR, "socketpair");
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:41:15: note: expanded from macro 'berr'
                const char *errstr = strerror_l(errno, NULL);   \
                            ^        ~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:288:3: error: implicit declaration of function 'strerror_l' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                berr(LOG_ERROR, "could not open %s sndio device", devname);
                ^
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:41:24: note: expanded from macro 'berr'
                const char *errstr = strerror_l(errno, NULL);   \
                                     ^
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:288:3: warning: incompatible integer to pointer conversion initializing 'const char *' with an expression of type 'int' [-Wint-conversion]
                berr(LOG_ERROR, "could not open %s sndio device", devname);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:41:15: note: expanded from macro 'berr'
                const char *errstr = strerror_l(errno, NULL);   \
                            ^        ~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:301:3: error: implicit declaration of function 'strerror_l' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                berr(LOG_ERROR, "could not set parameters for %s sndio device",
                ^
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:41:24: note: expanded from macro 'berr'
                const char *errstr = strerror_l(errno, NULL);   \
                                     ^
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:301:3: warning: incompatible integer to pointer conversion initializing 'const char *' with an expression of type 'int' [-Wint-conversion]
                berr(LOG_ERROR, "could not set parameters for %s sndio device",
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:41:15: note: expanded from macro 'berr'
                const char *errstr = strerror_l(errno, NULL);   \
                            ^        ~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:309:3: error: implicit declaration of function 'strerror_l' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                berr(LOG_ERROR, "could not start recording on %s sndio device",
                ^
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:41:24: note: expanded from macro 'berr'
                const char *errstr = strerror_l(errno, NULL);   \
                                     ^
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:309:3: warning: incompatible integer to pointer conversion initializing 'const char *' with an expression of type 'int' [-Wint-conversion]
                berr(LOG_ERROR, "could not start recording on %s sndio device",
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:41:15: note: expanded from macro 'berr'
                const char *errstr = strerror_l(errno, NULL);   \
                            ^        ~~~~~~~~~~~~~~~~~~~~~~~
7 warnings and 6 errors generated.
```

**Comment by WizardCM** [comment]
Please fill in the issue template.

**Comment by yurivict** [comment]
## Platform


Operating system and version: FreeBSD 12.2
OBS Studio version: 26.1.0-rc2

## Expected Behavior
compilation succeeds

## Current Behavior


/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:129:4: error: implicit declaration of function 'strerror_l' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                        berr(LOG_ERROR, "exiting due to poll error");
                        ^
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:41:24: note: expanded from macro 'berr'
                const char *errstr = strerror_l(errno, NULL);   \
                                     ^
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:129:4: note: did you mean 'strerror_r'?
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:41:24: note: expanded from macro 'berr'
                const char *errstr = strerror_l(errno, NULL);   \
                                     ^
/usr/include/string.h:91:6: note: 'strerror_r' declared here
int      strerror_r(int, char *, size_t);
         ^
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:129:4: warning: incompatible integer to pointer conversion initializing 'const char *' with an expression of type 'int' [-Wint-conversion]
                        berr(LOG_ERROR, "exiting due to poll error");
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:41:15: note: expanded from macro 'berr'
                const char *errstr = strerror_l(errno, NULL);   \
                            ^        ~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:145:5: error: implicit declaration of function 'strerror_l' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                                berr(LOG_ERROR,
                                ^
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:41:24: note: expanded from macro 'berr'
                const char *errstr = strerror_l(errno, NULL);   \
                                     ^
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:145:5: warning: incompatible integer to pointer conversion initializing 'const char *' with an expression of type 'int' [-Wint-conversion]
                                berr(LOG_ERROR,
                                ^~~~~~~~~~~~~~~
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:41:15: note: expanded from macro 'berr'
                const char *errstr = strerror_l(errno, NULL);   \
                            ^        ~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:276:3: error: implicit declaration of function 'strerror_l' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                berr(LOG_ERROR, "socketpair");
                ^
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:41:24: note: expanded from macro 'berr'
                const char *errstr = strerror_l(errno, NULL);   \
                                     ^
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:276:3: warning: incompatible integer to pointer conversion initializing 'const char *' with an expression of type 'int' [-Wint-conversion]
                berr(LOG_ERROR, "socketpair");
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:41:15: note: expanded from macro 'berr'
                const char *errstr = strerror_l(errno, NULL);   \
                            ^        ~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:288:3: error: implicit declaration of function 'strerror_l' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                berr(LOG_ERROR, "could not open %s sndio device", devname);
                ^
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:41:24: note: expanded from macro 'berr'
                const char *errstr = strerror_l(errno, NULL);   \
                                     ^
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:288:3: warning: incompatible integer to pointer conversion initializing 'const char *' with an expression of type 'int' [-Wint-conversion]
                berr(LOG_ERROR, "could not open %s sndio device", devname);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:41:15: note: expanded from macro 'berr'
                const char *errstr = strerror_l(errno, NULL);   \
                            ^        ~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:301:3: error: implicit declaration of function 'strerror_l' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                berr(LOG_ERROR, "could not set parameters for %s sndio device",
                ^
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:41:24: note: expanded from macro 'berr'
                const char *errstr = strerror_l(errno, NULL);   \
                                     ^
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:301:3: warning: incompatible integer to pointer conversion initializing 'const char *' with an expression of type 'int' [-Wint-conversion]
                berr(LOG_ERROR, "could not set parameters for %s sndio device",
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:41:15: note: expanded from macro 'berr'
                const char *errstr = strerror_l(errno, NULL);   \
                            ^        ~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:309:3: error: implicit declaration of function 'strerror_l' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                berr(LOG_ERROR, "could not start recording on %s sndio device",
                ^
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:41:24: note: expanded from macro 'berr'
                const char *errstr = strerror_l(errno, NULL);   \
                                     ^
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:309:3: warning: incompatible integer to pointer conversion initializing 'const char *' with an expression of type 'int' [-Wint-conversion]
                berr(LOG_ERROR, "could not start recording on %s sndio device",
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/ports/multimedia/obs-studio/work/obs-studio-26.1.0-rc2/plugins/sndio/sndio-input.c:41:15: note: expanded from macro 'berr'
                const char *errstr = strerror_l(errno, NULL);   \
                            ^        ~~~~~~~~~~~~~~~~~~~~~~~
7 warnings and 6 errors generated.

## Steps to Reproduce



1. cmake .
2. gmake
3.
4.

## Additional information

**Comment by kkartaltepe** [comment]
fwiw this function is posix standard and compiles in clang 11.

**Comment by yurivict** [comment]
It turned out that this function is missing in FreeBSD: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=251651
