### ISSUE TITLE
OBS randomly crash when closing the program

### ISSUE THREAD

**Issue by admshao** [obsproject/obs-studio#3840]
## Platform

Operating system and version: Windows 10 2004 (19041.630)
OBS Studio version: Release version 26.0.2 (64bit)

## Expected Behavior

OBS gracefully closes the program with no crash

## Current Behavior

OBS randomly crashes on exit, I managed to replicate a couple times from many attempts.

5 CrashLogs from different dates
https://gist.github.com/admshao/9512183948591a34400a396d36f4b864

## Steps to Reproduce

1. Open OBS
2. Start Decklink Output (usually helps to reproduce, not mandatory)
3. Close OBS

## Additional information

I checked other Crash on Exit related bugs and doesn't seem related

**Comment by Sorqan** [comment]
I also experience this every time I close OBS while decklink output is on. Started after upgrading Blackmagic Desktop Video and OBS.

Blackmagic Desktop Video version 12.1

**Comment by admshao** [comment]
This has been fixed already in OBS 27 and forgot to close this
