### ISSUE TITLE
Browser plugin does not accept self-signed SSL certificates

### ISSUE THREAD

**Issue by vbooka1** [obsproject/obs-studio#3846]
## Platform

Operating system and version: Windows 8.1 x64
OBS Studio version: 26.0.2

## Expected Behavior

Browser plugin should load any website regardless of its SSL certificate (e.g. by adding a checkbox "ignore invalid/expired certificate")

## Current Behavior

Browser plugin shows blank screen without any debug information.

## Steps to Reproduce

1. add a Browser source
2. point it to any HTTPS website with invalid certificate (examples: https://expired.badssl.com/  https://self-signed.badssl.com/ ) 
3. nothing appears in the Browser window

## Additional information

Some software wants to run on HTTPS only, and I need to display that software from the computer in local network (192.168.x.x), so there is no way to install a valid SSL certificate on that host. Of course I could setup some SSL termination like stunnel on the computer with OBS but it would be great to have an option to just ignore invalid or self-signed certificates.

**Comment by WizardCM** [comment]
We have no plans on providing methods for users to shoot themselves in the foot. I'm not actually sure if we can simply tell CEF to ignore certificate errors.

A quick look at Chromium's launch flags, you may be able to use `--ignore-certificate-errors-spki-list` ([more info](https://peter.sh/experiments/chromium-command-line-switches/#ignore-certificate-errors-spki-list)). OBS passes any launch flags you provide to it that it doesn't recognise directly to CEF.
