### ISSUE TITLE
OBS interface cannot fit on one screen due to incorrect Display/monitor resolution 640x320

### ISSUE THREAD

**Issue by NinjaTycoon** [obsproject/obs-studio#3848]
## Platform

Operating system and version: Fedora 28
OBS Studio version: 23.1.0

## Expected Behavior

It sees both monitors as 1920x1080.  

## Current Behavior

It correctly sees the Samsung 27", but not the Samsung TV, which comes back to Xorg with a vendor ID of "Unknown".  I don't see a reference to vendor IDs, but I've seen it before and it comes down to that.  Other things are able to discover, like NVidia says samsung 1920x1080 and Fedora itself correctly displays its resolution in its displays.  I suspect the issue is the Xorg interface Qt/OBS is using.  

OBS changes its window size and fonts based on the monitor resolution, but clearly cannot support 640x320, so it cannot fit all of its windows for the main screen or settings on the screen, going off into the right or left, and below.  Where there is the 2nd monitor, it displays there, taking 1.5 screens width.  But. where there is no screen, below, you cannot get to it, making it impossible to get to all settings.  The bigger issue is you just don't have a usable production window for managing streams.  

Note that streaming itself technically works.  While streaming a display is not an option because I cannot use the main OBS window without it bleeding to the other monitor, I have successfully streamed individual windows.  This is just a user interface issue.  

Also note that if I mirror the displays, OBS loads up correctly, being smaller and only using a portion of the display.  Obviously, this isn't a solution.  I need dual screen capability.  

## Steps to Reproduce

1. Launch OBS with my Samsung TV as primary monitor.  
2.
3.
4.

## Additional information

Note that this is in a living room, and I sit many feet away from the screen with poor vision.  If I need to read text, it needs to be on the primary monitor in a readable format.  This alone is a good reason to simply let us customize the window and font sizes instead of doing it automatically from monitor detection that doesn't always work.  If we could configure this in one of the settings files, we could set it up before launching.

**Comment by NinjaTycoon** [comment]
OBS loading correctly with the monitors mirrored:

![image](https://user-images.githubusercontent.com/40535852/101517253-8bc35a00-394e-11eb-820a-1daab12d3067.png)

**Comment by NinjaTycoon** [comment]
OBS primary window not fitting on the display with dual monitor:

![image](https://user-images.githubusercontent.com/40535852/101517499-d1802280-394e-11eb-93d3-8cca32018f16.png)

Ditto for settings.  This is the best theme for this situation:

![image](https://user-images.githubusercontent.com/40535852/101517613-f1174b00-394e-11eb-94aa-fecfed7e46dd.png)

**Comment by kkartaltepe** [comment]
I think your issue is broken hidpi setup on your platform. Probably try overriding Qt's hidpi settings with something like setting `QT_AUTO_SCREEN_SCALE_FACTOR=0` environment variable before running obs from a terminal. You are on a very outdated version of your distribution and possibly a newer version of Qt would fix your issue.

Closing as not our issue.

**Comment by kkartaltepe** [comment]
Also do not open bugs for old versions of OBS, file bugs against your packager if you are not using our official packaging and/or out of date versions.

**Comment by NinjaTycoon** [comment]
There is no way to upgrade beyond this version due to nVidia dropping support for my cards as of Kernel 5.0.  The video cards are working perfectly.  Not buying new video cards to upgrade the OS to upgrade OBS.  I have to actually boot into the last working 4.x kernel version to be able to use video after upgrading to Fedora 28 installed Kernel 5.0.  

I would love to be able to upgrade the OBS if there is a way to get the latest version without upgrading the OS.  Can you link to instructions for Fedora on having the latest version?  

To be clear, are you saying that choosing to use Qt is not a problem for OBS?  It's the only piece of software I've run in years that can't figure out how to size its windows correctly.

**Comment by Fenrirthviti** [comment]
https://github.com/obsproject/obs-studio/wiki/Install-Instructions#red-hatfedora-based-build-directions

**Comment by NinjaTycoon** [comment]
QT_AUTO_SCREEN_SCALE_FACTOR=0 did resolve the problem.  Thank you.
