### ISSUE TITLE
Disabling Video Encoder in FFMPEG output causes recording files to have no audio streams

### ISSUE THREAD

**Issue by Pimpmuckl** [obsproject/obs-studio#3851]
## Platform

Operating system and version: Windows 10 20H2
OBS Studio version: 26.1.0-rc2

## Expected Behavior

Start Recording with video encoder disabled and an audio encoder enabled in FFMPEG output should record container file with audio stream in it.

## Current Behavior

Container file gets created when "Stop Recording" is pressed but contains no audio stream.

## Steps to Reproduce

1. Configure FFMPEG recording output to use audio encoder but no video encoder. 
![image](https://user-images.githubusercontent.com/14083666/101541427-c1456300-39a1-11eb-9537-060bbe42abd3.png)
2. Hit "Start Recording"
3. Hit "Stop Recording" after a bit
4. Empty container file gets created.

**Comment by Fenrirthviti** [comment]
Unfortunately, we don't really support audio-only output. Custom ffmpeg output is already a "no warranty" option, and audio-only is even less supported. It's unlikely we'll spend time looking in to this any time soon.

**Comment by derrod** [comment]
That being said, maybe we should remove "Disable Encoder" as an option from the video encoder dropdown...
