### ISSUE TITLE
OBS in Mac poor performance

### ISSUE THREAD

**Issue by iamqk** [obsproject/obs-studio#3852]
Operating system and version: catalina 10.15.7 (19H15)
OBS Studio version: 26.1 Release Candidate 2, OBS Studio 26.0.2
Hardware: Macbook pro 2015 15" cpu 4870HQ m370x (no hevc support)

## Expected Behavior
cpu should not be at very high usage, should be as low as under windows, or near.

## Current Behavior
one core of the cpu at maximum（100）usage
I think there must be some place to optimize

## Steps to Reproduce
1. start obs with video input，no stream out, no recording, just preview
2. observer cpu usage

## Additional information
<img width="414" alt="截屏2020-12-09 上午10 42 00" src="https://user-images.githubusercontent.com/281031/101568097-fe930a80-3a0c-11eb-9283-0563171d100c.png">

**Comment by Fenrirthviti** [comment]
Please use the forums or Discord for support. There is also already a large discussion on this issue here: https://github.com/obsproject/obs-studio/issues/2841
