### ISSUE TITLE
Build fails on Big Sur

### ISSUE THREAD

**Issue by erango** [obsproject/obs-studio#3866]
## Platform
Operating system and version: MacOS 11 Big Sur
OBS Studio version: latest code from master branch

## Expected Behavior
Build should pass

## Current Behavior
Build fails: with multiple `unsupported architecture`-related errors, see build log:
https://pastebin.com/ch1JScpr

## Steps to Reproduce
1. Clone latest master code `git clone --recursive https://github.com/obsproject/obs-studio.git`
2. On MacOS Big Sur, run full build script: `./CI/full-build-macos.sh`
3. Observe build failure

**Comment by johnboiles** [comment]
But it didn't break CI right? @erango perhaps you are using an old Xcode version? Try Xcode 12.2

**Comment by erango** [comment]
@johnboiles I am using the latest version of Command Line Tools, which should be the same, no?

**Comment by WizardCM** [comment]
Would it maybe be worth it/possible to log the version to make it clearer? Especially if we have a minimum required version.

**Comment by mwdiers** [comment]
This isn't just on Big Sur. It's also broken on Catalina.

**Comment by johnboiles** [comment]
@mwdiers same question for you. Did you install Xcode 12.2 or above? Please post a screenshot of your Xcode about page.

![image](https://user-images.githubusercontent.com/218876/102255038-55da2480-3ebe-11eb-9f25-3d3a98741d0f.png)

@erango probably, though I've heard reports of Apple's Command Line Tools not updating. You might try the following to force them to update.

```
sudo rm -rf /Library/Developer/CommandLineTools
sudo xcode-select --install
```

**Comment by mwdiers** [comment]
I had 12.2 installed, but the Command Line Tools did not update. After forcing the update, it is working.

**Comment by erango** [comment]
@johnboiles  just finished installing xcode for this 😁

**Comment by johnboiles** [comment]
:+1: this can be closed @PatTheMav @WizardCM
