### ISSUE TITLE
Virtual Camera occasionally shows green, corrupted frames

### ISSUE THREAD

**Issue by mandonnaud** [obsproject/obs-studio#3870]
### Platform

Operating system and version: Windows 10 
OBS 26.0.2 (all drivers up to date)

## Expected Behavior

Use obs as virtual camera, send the same stream to OBS preview

## Current Behavior

Randomly and for a duration of 20 to 50 seconds, the received stream sent by Zoom or Microsoft Teams has a green color addition

## Steps to Reproduce

- Activate the virtual OBS camera
- Use it as a camera on ZOOM or Microsoft Teams
(on Zoom, observe from another client in the conversation)
- Randomly several times, the flow has a green layer which disappears after 20 to 50 seconds

## Additional information

Problem to observe on:
- Teams (visible from both sides)
- Zoom (visible only to others)

Problem to observe on:
- Native virtual OBS camera
- NDI camera input

Two discussion on the forum with multiple screenshots
https://obsproject.com/forum/threads/virtual-cam-output-gets-distorted-and-turns-greenish.135098/
https://obsproject.com/forum/threads/green-screen-while-streaming-on-obs.132740/

**Comment by WizardCM** [comment]
Please fill in the issue template.

**Comment by mandonnaud** [comment]
sorry, it's corrected

**Comment by Mister36MN** [comment]
I actually ran into this exact same thing last night while using Zoom...but not with VirtualCam. It just happened in Zoom by itself occasionally when screen sharing.

**Comment by energizerfellow** [comment]
This would appear to be the same issue as #3600?

**Comment by WizardCM** [comment]
Duplicates #3600 

Nice catch!
