### ISSUE TITLE
Decklink issues on OBS 26.1

### ISSUE THREAD

**Issue by LGCW** [obsproject/obs-studio#3872]
Decklink Quad HDMI corrupted input with latest RC. Bouncing Mode, Colour space / range, or Pixel Format did not result in a usable image. 

## Platform
OBS Studio version: OBS 26.1.0-rc2-22-g00f0d5eb4 

## Expected Behavior
Clean HDMI capture from PC. 

## Current Behavior
Corrupted HDMI capture from PC.

## Steps to Reproduce
Create BlackMagic source with Decklink Quad HDMI. Auto or manual. 

1. Screenshots https://imgur.com/a/5kASjmD

## Additional information
The device functions correctly with OBS 26.0.2-66-gb9a151625 as shown in the screenshots. Only occurs when capturing from PC, a DSLR HDMI input worked as expected. 

## Log
[2020-12-12 15-44-52.txt](https://github.com/obsproject/obs-studio/files/5683774/2020-12-12.15-44-52.txt)

**Comment by WizardCM** [comment]
Looks like users have reproduced this on Windows too, including one of our support volunteers so I'm marking this confirmed. Not sure if it's a conflict between OBS and the 11.6 SDK update, or just the 11.6 SDK in general.

**Comment by Fenrirthviti** [comment]
Updated the title of this to reflect that this is occurring on more than just Windows.

**Comment by BlackScreen** [comment]
I am using the 11.7 version of the Decklink drivers and the Windows version is 20H2, sorry for the wrong version number in my issue. I just re-looked at it.
I am also using a DeckLink Duo Card.

**Comment by ryanfreng** [comment]
SDI input is not working in 26.1 from a decklink duo 2 on macOS 10.15.7. I ended up rolling back to 26.0.2 to re-enable decklink sdi input.

**Comment by edwinr** [comment]
Not the exact same hardware but it seems related: Intensity Pro is also not working on 26.1 (testing with component input, driver version 11.7, Windows 20H2)
Reinstalled 26.0.2 and it works again.

Also tested Windows 64-bit CI build from #3907 which mentions this issue, this makes a new 10-bit YUV pixel format option appear which does work correctly. The 8-bit YUV option that was previously used in 26.0.2 still shows up corrupted when using this build:
![afbeelding](https://user-images.githubusercontent.com/847413/102409408-47d7f100-3fef-11eb-90bd-74834f0ac896.png)
![afbeelding](https://user-images.githubusercontent.com/847413/102411203-dd748000-3ff1-11eb-9213-0153f8074426.png)

Interestingly starting 26.1 right after using this CI build with the 10-bit YUV option temporarily makes 26.1 work too, but it breaks again after opening the properties window for the source.
