### ISSUE TITLE
Completely transparent images in slide show appear as completely black image

### ISSUE THREAD

**Issue by justin-hackin** [obsproject/obs-studio#3876]
## Platform

Operating system and version: MX linux 19.2
OBS Studio version: 25.0.8

## Expected Behavior

transparent images should not present any content, revealing layers underneath.

## Current Behavior

Layers underneath slide show are completely obscured by black image when completely transparent image is reached in slide show

## Steps to Reproduce

1. Add slide show
2. Add completely transparent image slide
3. place visible content undeneath slide show
3. Observe this content can not be seen

## Additional information

Adding a single non-transprent pixel to the image fixes the issue.

The use case for this: a blank-slide delimited slideshow.  This is useful when the presenter has a bunch of items to cover. The presenter is prompted with non-blank slide and then clears the prompt in order to present unobscured by slide. In my case, I exported a slideshow with a transparent background to a pdf, then used this command (ImageMagick) to convert it to a series of images.

```
convert -density 150 -antialias  presentation.pdf  -resize 1024x -quality 100 "presentation-%02d.png"
```

Side note: when a directory is chosen for the images, the images are not presented in alphabetical order so one must multi-select the files with Add files.

**Comment by kkartaltepe** [comment]
I cannot replicate, creating a transparent png in krita renders transparent as expected.
