### ISSUE TITLE
ftl_output not found on Arch Linux Install

### ISSUE THREAD

**Issue by GRVYDEV** [obsproject/obs-studio#3881]
## Platform

Operating system and version: Manjaro Linux Kernel version 5.9.11-3-MANJARO
OBS Studio version: 26.0.2-2 64 bit

## Expected Behavior
When adding a custom service to use ftl_output it should use ftl to stream

## Current Behavior
In the log file it says 

```
11:55:13 AM.313: Output ID 'ftl_output' not found
11:55:13 AM.313: Failed to create output 'simple_stream'!
11:55:13 AM.313: Output 'simple_stream': Tried to set a delay value on a non-encoded output
11:55:13 AM.313: Stream output type 'ftl_output' failed to start!
11:55:19 AM.601: Settings changed (outputs)
```

## Steps to Reproduce
1. Install obs studio using Pacman
2. Edit ~/.config/obs-studio/plugin_config/rtmp-services/services.json to include a custom service that uses "ftl_output"
3. Select that service and click Start Streaming

**Comment by notr1ch** [comment]
There is no official build for Arch, this is likely a packaging issue. Contact your package maintainer and ask them to build OBS with FTL support.
