### ISSUE TITLE
SRT Streaming with slow playback speed on receiving end.

### ISSUE THREAD

**Issue by Sorqan** [obsproject/obs-studio#3888]
## Platform

Operating system and version: Windows 10 Pro 1903
OBS Studio version: 26.1

## Expected Behavior

I'm using a really old blackmagic decklink that is not recognized as a decklink by OBS so I am using a normal Video Capture Device source and Blackmagic WDM with default settings. Outputting a record to custom ffmpeg URL srt stream to another OBS server that is listening with a Media Source source. Tested with the same settings in OBS version 26.0.2 works flawlessly at the expected playback rate on the receiving server.

## Current Behavior

Playback rate on receiving server is about half speed, but frame rate on both servers is showing solid 29.97 on the bottom right of the OBS window. I tried the same with the transmitting server running version 26.0.2 and it works fine at full playback speed seen on the receiving server, but after upgrading to version 26.1 and not changing anything, playback is about half speed, sometimes speeding up to catch-up most of the time getting a recording failed on the transmitting server after a minute or so. No issues with receiving an srt stream in version 26.1, only appears to be an issue with streaming out.

## Steps to Reproduce

1. Load my settings on a transmit server.
2. Start listening on another OBS server with a Media Source in srt mode=listener and format mpegts, rest of the settings default.
3. "Start Recording" on the transmit server.
4. Observe the playback speed on the receiving server and the fact there is no other indication of fps drops.

Of course this could be an issue that only applies to using a really old Decklink card of course. But it is working flawlessly in OBS version 26.0.2 with these settings.

Receiving OBS server I have tried running 26.0.2 or 26.1 and either does the same thing, so that doesn't seem to be the issue.

Here is the config:
[config.zip](https://github.com/obsproject/obs-studio/files/5693666/config.zip)

**Comment by pkviet** [comment]
closing since this is quite old; feel free to reopen if the bug still persists for you.
