### ISSUE TITLE
VLC video source does not display subtitles

### ISSUE THREAD

**Issue by NuclearMonster** [obsproject/obs-studio#3892]
## Platform

Operating system and version: macOS Big Sur 11.1
OBS Studio version: 26.1

## Current Behavior

When using a typical video file that displays subtitles when streamed or opened and previewed with VLC video source on Linux or Windows, vlc video source on macos will not display subtitles.

## Steps to Reproduce

Repro Steps:
1) install OBS 26.1 on macOS Big Sur. 
2) Install VLC
3) add vlc video source to scene
4) add test file to vlc video source (eg https://github.com/Matroska-Org/matroska-test-files/blob/master/test_files/test5.mkv )
5) verify that subtitles are enabled and set to subtitle track number that contains subtitles (eg 1 or 2 with example file)
6) accept properties dialog
7) view previewed media file, scrubbing to appropriate time code for dialogue if needed.

Expected result:
Video file plays with subtitles

Actual result:
Video file plays without subtitles

**Comment by WizardCM** [comment]
Which version of VLC?

**Comment by NuclearMonster** [comment]
Version 3.0.11.1 Vetinari (Intel 64bit)

**Comment by fathonyfath** [comment]
Can confirm it sill happening on VLC 3.0.12 with OBS 26.1.2
Machine is Macbook Pro MF841 on macOS Catalina

Weird thing is if I downgrade to VLC 2.2.8, the subtitle is working as expected on OBS. Not sure whether this is OBS or VLC issue.

**Comment by NuclearMonster** [comment]
Confirmed here, older versions of the 3.series of VLC don't work for subtitles in OBS as a VLC video source, but 2.2.8 does work with OBS (now 26.1.2). Good catch and an adequate temporary workaround.

**Comment by WizardCM** [comment]
Interesting that it works with VLC 2.x on macOS but not 3.x.

I've just confirmed on Windows that VLC 3.x subtitles work fine in OBS. So maybe an API difference on the VLC side between platforms? That's really weird - might be a bug the VLC folks might be able to look into.

**Comment by navo-k** [comment]
I had the same issue where my subtitles weren't displaying, so I downgraded to 2.2.8 and then my captions showed up on OBS. How can we report this to VLC to flag the issue?

**Comment by navo-k** [comment]
> Can confirm it sill happening on VLC 3.0.12 with OBS 26.1.2
> Machine is Macbook Pro MF841 on macOS Catalina
> 
> Weird thing is if I downgrade to VLC 2.2.8, the subtitle is working as expected on OBS. Not sure whether this is OBS or VLC issue.

Thank you for this fix!

I had the same issue where my subtitles weren't displaying, so I downgraded to 2.2.8 and then my captions showed up on OBS. How can we report this to VLC to flag the issue?

**Comment by NuclearMonster** [comment]
navo-k did the hard work and posted the bug report to VLC's GitLab: https://code.videolan.org/videolan/vlc/-/issues/25660

**Comment by flaeri** [comment]
Subtitles work for me when I follow the reproduction steps.

However, if I modify the subtitle track selection, I no longer get subtitles (switching the track from 1 to 2 for instance).

Restarting the video does not bring the subtitles back, but removing the file from the VLC source, and re-adding it brings them back. IE it is *not* required to completely delete and re-add the source.

This was on OBS 28.0.3, VLC 3.0.17.4 Vetinari.

**Comment by PatTheMav** [comment]
My current hunch is that because VLC caches file entries, changing a audio or subtitle stream index just adds additional options to the media entry, but doesn't replace the old ones (we just call `libvlc_media_add_option_` with the new option).

So we end up with the original options (audio track 1, subtitle track 1) and then just add new options (audio track 1, subtitle track 1, subtitle track 2) which might confuse VLC. There doesn't seem a way to fetch or change the currently configured options and the `vlc_media_t` struct is not documented in VLCs API docs, so it looks like we'd need to release the old media objects and ensure a new object is created.

**Comment by Fenrirthviti** [comment]
Closing as stale. If this is still an issue please open a new issue with updated reproduction steps on the latest version of OBS.
