### ISSUE TITLE
Nothing can load the virtual camera, zoom crashes once it tries and google meets and other applications give "camera failed" errors or simply don't load

### ISSUE THREAD

**Issue by coolduderules** [obsproject/obs-studio#3896]
## Platform

Operating system and version: MacOS Catalina (10.15.7)
OBS Studio version: 26.1.0

## Expected Behavior

Virtual camera should load and function.
## Current Behavior

Zoom instantly crashes once it tries to load the virtual camera and other programs generally just give errors such as "camera failed" in google meets. Originally I was using an old 2014 macbook air when this first occurred and I assumed it was just some issue the computer had gotten in my years of using it. I recently purchased a 2020 macbook pro, and just like on my old computer the virtual camera worked perfectly fine for a week or two before this issue occurred. For both my old and new computer I was using the plugin on github until I hit this wall, but now even after uninstalling that, removing all files it left, and updating OBS, the built in one is having this same issue. [Here](https://github.com/johnboiles/obs-mac-virtualcam/issues/233) is the issue I made on the old virtualcam plugin github that includes logs and responses from me and developers that may help. (https://github.com/johnboiles/obs-mac-virtualcam/issues/233)

## Steps to Reproduce

1. Download OBS
2. Use the virtual camera with no problem for a bit
3. Wait for it to break

## Additional information

Just to reiterate, this happened to me on two separate computers on different versions, so it is certainly a recurring issue. Also, reinstalling does not help anything at all, even after manually searching for and deleting all possible relevant files I can find, the virtual camera cannot load by other programs and zoom will crash the second I try to switch to it.

**Comment by Fenrirthviti** [comment]
https://obsproject.com/forum/threads/fyi-macos-virtual-cam-on-obs-26-1.135468/

Have you tried these steps?

**Comment by polyneux** [comment]
Hi. I'm having this same issue but on Windows 10. It worked flawlessly up until about a week ago. And that was on the previous version. Suddenly it started crashing zoom (built in virt cam). I installed the .1 update thinking it would fix it and it is the same issue.

@coolduderules I wonder if a recent zoom update might have made it not work, and not an OBS issue? 🐙

**Comment by coolduderules** [comment]
@Fenrirthviti yes, I did that before updating OBS.

@polyneux It was fully working in all applications, but out of nowhere it stopped working, not just in zoom, but in all other applications as well. It also was working on my new computer after freshly installing zoom when it had already been having the same issue on my old one for weeks, so I definitely had it working when zoom the same version or higher as the broken one on my old computer. Also, zoom is the only application that crashes (I assume that is just due to how zoom handles loading video inputs), but the virtual camera cannot load in any other application either so it definitely isn't a zoom problem.

I pasted my logs in the original issue I submitted on the old plugin github, which i linked in my original post. Hopefully that is helpful to pinpoint exactly what the issue is.

**Comment by polyneux** [comment]
@coolduderules I am also experiencing what you suggested. It wouldn't load into GTMs app. However, it DOES work fine on MS teams for me. Interesting. Not trying to hijack just piqued my interest because my zoom crashing sounds a lot like yours even though I'm on windows. Started just last week, odd.

**Comment by mitu-lv** [comment]
All problems would be gone on MacOs if you would disable SIP. There is something MacOs SIP does not like about that virtual cam plugin it could be that it does something that SIP considers harmful. Probably the virtual cam plugin needs different approach of using that data channel.

This is how to disable SIP:
Click the Apple symbol in the Menu bar.
Click Restart…
Hold down Command-R to reboot into Recovery Mode.
Click Utilities.
Select Terminal.
Type csrutil disable.
Press Return or Enter on your keyboard.
Click the Apple symbol in the Menu bar.
Click Restart…

**Comment by gxalpha** [comment]
This issue should be fixed for quite some time now.
If this is still an issue in OBS 28.1 RC 1 (which should be released very shortly, and contains a fix for a crash newly introduced in 28.0), please open a new report.
