### ISSUE TITLE
Audio Monitoring sometimes doesn't work on first launch after PC restart

### ISSUE THREAD

**Issue by KyButler** [obsproject/obs-studio#3898]
## Platform

Operating system and version: Windows 10 20H2 build 19042.685
OBS Studio version: 26.1.0

## Expected Behavior

Audio Monitoring output should work on first launch after a system restart.

## Current Behavior

Audio monitoring does not output audio until the user changes the Monitoring Device then restarts OBS. It then works and can be switched to the desired Device. It then also works on subsequent launches, until the user restarts the computer.

https://obsproject.com/logs/dnczjvfG4UcVL2gC <- restarted PC, Monitoring not working on any source
https://obsproject.com/logs/gRFEl27Fpky0qm_T <- after applying fix of changing audio monitoring source to Default then restarting OBS then setting back to GC553

## Steps to Reproduce

1. Set Audio Monitoring Device to the GC553 (Avermedia Capture Card)
2. Restart PC
3. Open OBS
4. OBS Audio Monitoring *usually* does not output audio to the selected GC553. 
5. Change Audio Monitoring source to any other source including Default.
6. Close OBS
7. Open OBS. The selected Audio Monitoring now works (so if you selected Default, you'd hear the audio feedback loop as it's outputting back to your headphones, meaning Monitoring is working)
8. Change Monitoring Device back to GC553, at which time it will output correctly.

## Additional information

The issue happens whether or not the GC553 is plugged in before OBS is started, after OBS is started, and before and after PC restart. The issue also is fixed in subsequent restarts of OBS, until the PC is restarted.

**Comment by energizerfellow** [comment]
To get an initial support thing out of the way...  I assume you've updated the firmware on the Avermedia Live Gamer Ultra (GC553) and unplugged/re-plugged the capture card after updating the firmware? There seems to be a lot of NOS inventory in the channel on these, so watch out for ancient firmware.

This seems to be a case of Windows having the concept of different Default Device vs Default **Communications** Device on the audio side and the capture card (correctly) identifying itself as a UVC A/V device with non-Communications WASAPI audio, which you'll see below:

![image](https://user-images.githubusercontent.com/47622403/102284010-b4b89180-3ef0-11eb-86cd-d9217d7da864.png)
![image](https://user-images.githubusercontent.com/47622403/102284479-766fa200-3ef1-11eb-8688-f9499984ef5b.png)

OBS Studio has issues with this as OBS's "Default" is (currently) hard-coded to use the Default Communications Device and has no concept of a non-Communications Default Device. Additionally, OBS Studio doesn't (currently) follow changes in the audio defaults in real-time, so any hotplug events or settings changes will be ignored until the next OBS launch.

If you set the the capture card to the Default Communications Device or set both Default Device types to the same audio device and don't change them while OBS is running, OBS should behave as expected.

**Comment by coltertv** [comment]
It happens to me often that monitoring doesn't work, and when I go to check the monitoring devices in the dropdown list, mine is greyed and there is another below with exactly the same name. Choosing the 'new' device fixes the issue, but not sure why it happens to begin with

**Comment by Fenrirthviti** [comment]
Closing as stale. If this is still an issue please open a new issue with updated reproduction steps on the latest version of OBS.
