### ISSUE TITLE
Runs fine, crashes on closing

### ISSUE THREAD

**Issue by dylix** [obsproject/obs-studio#3899]
OBS runs fine, when I close obs it always crashes and I get this dump..
I've narrowed it down to a LUA script that causes this, but the dump doesn't say anything about it so maybe it points to a bigger possible bug?

Operating system and version: Win10 19042.630
OBS Studio version: 26.1.0 (happened in previous version too)

## Expected Behavior
Closes normally

## Current Behavior
OBS works fine, crashes when I close the application

## Steps to Reproduce
1. Open OBS studio
2. Close OBS studio

## Additional information
[offending lua](https://pastebin.com/cTdXprXk)
[crashlog](https://pastebin.com/raw/CHwEB227)

**Comment by WizardCM** [comment]
The script isn't releasing references properly, contact the developer of the plugin.
