### ISSUE TITLE
In Settings > Hotkeys, the Filter only looks at the first 74 characters of the item name

### ISSUE THREAD

**Issue by cowboy** [obsproject/obs-studio#3902]
## Platform

Operating system and version: Windows 10 Pro 1909 18363.1256
OBS Studio version: 26.1.0 (64 bit)

## Expected Behavior
When I enter text into the "Filter" box at the top of the Hotkeys settings page, I expect the entire name of sources to be searched

## Current Behavior
When I enter text into the "Filter" box at the top of the Hotkeys settings page, only the first 74 characters of sources seem to be searched. Any characters after that are ignored. I have some long, descriptive source names, so this is causing me problems.

## Steps to Reproduce
Add a source to a scene with the name `1234567890123456789012345678901234567890123456789012345678901234567890ABCDE` (75 characters long)

![image](https://user-images.githubusercontent.com/54051/102305745-c456cb00-3f2e-11eb-9ccf-32fb3ea8d879.png)

Search for `ABCD` in the Hotkeys "Filter" box (chars 70-74), see it work (also note that the source name next to Show and Hide is truncated at 74 chars)

![image](https://user-images.githubusercontent.com/54051/102305796-d6d10480-3f2e-11eb-8cf8-48805d159d7e.png)

Add an `E` to make it `ABCDE` (chars 70-75), see it fail

![image](https://user-images.githubusercontent.com/54051/102305824-e6e8e400-3f2e-11eb-8b4d-25a67e8eea0e.png)

**Comment by WizardCM** [comment]
Is this affected by the width of the window, specifically the truncation?

**Comment by cowboy** [comment]
@WizardCM no, the truncation happens regardless of the width of the window.

**Comment by cowboy** [comment]
![image](https://user-images.githubusercontent.com/54051/102308091-e69f1780-3f33-11eb-967a-027eddfa341b.png)

**Comment by WizardCM** [comment]
A quick look tells me that the check is only done on the visible text,

https://github.com/obsproject/obs-studio/blob/46118470abed7a4f4ee2398c90f8855988820f58/UI/window-basic-settings.cpp#L2725-L2727

And that the truncation is done by us, manually.

https://github.com/obsproject/obs-studio/blob/46118470abed7a4f4ee2398c90f8855988820f58/UI/window-basic-settings.cpp#L2586-L2590

However, the downside is that `fullName` is only defined when the name is too long.

**Comment by awarus** [comment]
Hi guys! I could fix it, but I have to know what size will we use eventually? Is size of 100 chars right for you?

**Comment by WizardCM** [comment]
> Hi guys! I could fix it, but I have to know what size will we use eventually? Is size of 100 chars right for you?

The correct fix shouldn't care about the length of truncation. It should

* always set fullName
* check `fullName` when searching, rather than `item.text()`

**Comment by Fenrirthviti** [comment]
Fixed in #4109
