### ISSUE TITLE
Integer list property settings are 0 when obs_property_set_modified_callback's callback is first called.

### ISSUE THREAD

**Issue by creallfluharty** [obsproject/obs-studio#3905]
## Description
When the callback passed to `obs_property_set_modified_callback` is called for the first time (when the script is first loaded into OBS), the settings it is given are `0` for an already created list property.

## Platform
OS + OS version: Windows 10 Home (Version: 20H2 OS build: 19042.662)
OBS Studio version: 26.1.0 (64 bit)
Python version: 3.6 (64 bit) -- Though this behavior is not specific to Python

## Expected Behavior
I would expect that either the callback is not called until the setting has been set, or that the settings would reflect the value set as the default.

## Current Behavior
The callback is called with settings that are `0` for the list property it is tracking.

## Steps to Reproduce
1. Add the following to a `.py` file
```python
import obspython as obs

def script_properties():
	props = obs.obs_properties_create()
	_list = obs.obs_properties_add_list(props, "list", "A List", obs.OBS_COMBO_TYPE_LIST, obs.OBS_COMBO_FORMAT_INT)
	obs.obs_property_list_add_int(_list, '1', 1)

	obs.obs_property_set_modified_callback(_list, lambda ps, p, s: print("list is", obs.obs_data_get_int(s, "list")))
	
	return props
```
2. Add said `.py` file in the Scripts menu
3. Confirm that the logs are as follows:
```
[<script_name>] list is 0
[<script_name>] list is 1
```

## Additional information
1: The same behavior occurs for the equivalent Lua code
```lua
function script_properties()
	local properties = obslua.obs_properties_create()
	local _list = obslua.obs_properties_add_list(properties, "list", "A List", obslua.OBS_COMBO_TYPE_LIST, obslua.OBS_COMBO_FORMAT_INT)
	obslua.obs_property_list_add_int(_list, "1", 1)

	obslua.obs_property_set_modified_callback(_list, function(ps, p, s) print("list is " .. obslua.obs_data_get_int(s, "list")) end)

	return properties
end
```
2. Setting a default value via `obs_data_set_default_int` doesn't stop the null settings issue, but it prevents the second call with the correct settings (which I assume is worse)
3. I'm not 100% sure if this unintended behavior, but it certainly is unexpected.

**Comment by PatTheMav** [comment]
This can indeed seem counterintuitive, but it's working as implemented:

* Upon loading the script, the properties are initialised
* At this point the modification callbacks are called as well to create a valid "initial state" of the properties
* Then the properties need to be drawn as UI elements, for this a refresh/reload takes place
* As no valid list index exists (the script has been added fresh, so no script settings are available), a settings update is triggered
* This will then create a new settings object with the values currently set for each property object
* Finally the modified callback is called again, this time with this new settings object

Thus the callback will be called twice, but as your print the value as represented in the settings object, it will only be set to "1" during the first UI refresh.
