### ISSUE TITLE
OBS Locks Up when srt-live-transmit is SIGKILLed

### ISSUE THREAD

**Issue by stazio** [obsproject/obs-studio#3909]
## Platform

Operating system and version: Windows 10
OBS Studio version: 26.1.0

## Expected Behavior

When srt-live-transmit is SIGKILLed in listen mode it should try to reconnect, but still allow you to stop streaming.

## Current Behavior

When srt-live-transmit is SIGKILLed in listen mode, the notification appears that it tries to reconnect, but pressing `Stop Streaming` does nothing the first time, and causes Windows to report the process as Non-Responsive when pressed the second time. If you don't press the button twice, and exit OBS, it is still present in the taskbar and needs to be killed in Task Manager.

## Steps to Reproduce

1. Publish to srt-live-transmit in listen mode
2. SIGKILL srt-live-transmit
3. Try to stop streaming, or exit OBS.

**Comment by RytoEX** [comment]
Closing this as a duplicate in favor of #5791 as that has more info on it.
