### ISSUE TITLE
Unable to start output from C API, no error message given

### ISSUE THREAD

**Issue by R030t1** [obsproject/obs-studio#3911]
## Platform

Operating system and version: Linux, Gentoo
OBS Studio version: 25.0.8

## Expected Behavior
Using the C API, I should see my raw video data callback triggered.

## Current Behavior
Attempting to `obs_set_output_source` and `obs_output_start` fails with no error message.
At a minimum the lack of error message should be corrected, if I am doing something incorrect I'm unable to tell what it is.

## Steps to Reproduce
Please look at this file: https://github.com/R030t1/obsscrape/blob/master/obsscrape.cc
It has some code I used to investigate the structures passed to the obs functions but is still fairly minimal.

**Comment by gxalpha** [comment]
`null_output` is an encoded output. You need to set an encoder via `obs_output_set_video_encoder`.

In the future, please use the Discord server or OBS Forums for developer support. GitHub issues aren't the correct place for this.
