### ISSUE TITLE
Tiny audio mixer tick values scale poorly via DPI (especially 100->125%)

### ISSUE THREAD

**Issue by Rubbyx** [obsproject/obs-studio#3915]
## Platform

Operating system and version: Windows 10 20H2
OBS Studio version: 26.1

## Expected Behavior

Normal fonts and sizing, like in 26.0.2

![image](https://user-images.githubusercontent.com/56994514/102440372-2ef02f80-4031-11eb-9c9a-bfd7834c031b.png)

## Current Behavior

Blurry fonts and scales of Audio Mixer, the window got bigger, unwanted space below the "Exit" button.

![image](https://user-images.githubusercontent.com/56994514/102439358-357da780-402f-11eb-8da7-f5854d66bd6b.png)

## Steps to Reproduce

Just updated from 26.0.2 to 26.0.1, ang things went blurry, the window - bigger.

## Additional information

Perhaps, it has something to do with my 125% scaling display size (1920x1080 resolution).

**Comment by WizardCM** [comment]
Looking at this screenshot, it's only the tick numbers in the audio mixer that are blurry. There's a downside to using such a small font size with that particular font it seems.

Does this only happen with the System theme? You can change in Settings -> General.

The larger sizing of everything is correct due to your 125% scaling. The old system (in 26.0) would have rounded it down to 100%. which is not ideal in every situation.

**Comment by Rubbyx** [comment]
> Does this only happen with the System theme?

Looks like not
![image](https://user-images.githubusercontent.com/56994514/102442527-9dcf8780-4035-11eb-9fd4-cb0d61da8656.png)
![image](https://user-images.githubusercontent.com/56994514/102442536-a1630e80-4035-11eb-9c0b-efecf588b5f2.png)

**Comment by WizardCM** [comment]
Oof. We'll likely have to find a more suitable font for tiny text there.

In the meantime, you can get the old behaviour (mostly) via this:

> 1. Close OBS Studio.
> 2. Find your OBS Studio shortcut, either on your desktop or in your start menu (Right click -> Open file location).
> 3. Right click on it and select "Properties".
> 4. Go to the "Compatibility tab".
> 5. Click "Change high DPI settings".
> 6. Tick "Override high DPI scaling behavior".
> 7. In the dropdown, change it to "System (Enhanced)".
> 8. Click OK to exit out of the scaling settings.
> 9. Click OK to save the new properties.
> 10. Launch OBS Studio as you normally would.

**Comment by Rubbyx** [comment]
> In the dropdown, change it to "System (Enhanced)"

Well, it all went blurry 😅 (except for windows title)

![image](https://user-images.githubusercontent.com/56994514/102443883-dae94900-4038-11eb-957d-6e6e6f73ad22.png)

I think I'll just stay on 26.0.2 for a while, it works well for me.

**Comment by Rubbyx** [comment]
> Looking at this screenshot, it's only the tick numbers in the audio mixer that are blurry.

And the scales has some kind of disturbance: some lines are thicker than the others.

This is 26.0.1
![image](https://user-images.githubusercontent.com/56994514/102445120-cd818e00-403b-11eb-8ed8-17ec26f7ac02.png)

And this is 26.0.2
![image](https://user-images.githubusercontent.com/56994514/102445295-38cb6000-403c-11eb-8f49-7f39be1e0ce7.png)

**Comment by tbodt** [comment]
Perhaps the text is being drawn and then scaled down?

**Comment by notr1ch** [comment]
Does this still happen if you pop out the mixer to its own window?

**Comment by Rubbyx** [comment]
> Does this still happen if you pop out the mixer to its own window?

Yes 
![image](https://user-images.githubusercontent.com/56994514/102726830-cf489b80-4332-11eb-92f6-901de9915136.png)

**Comment by jclay** [comment]
QPainter as it's used today seems to not take advantage of the current DPI setting. I did a quick test and set the QPixmap devicePixelRatio to 2.0 (the scaling DPI Qt uses for my retina screen), and this makes the numbers look just as they should -- nice and crisp. 

The [docs](https://doc.qt.io/qt-5/qpixmap.html#devicePixelRatio) seem to indicate that the geometry functions automatically take this into account, but that was not my experience as I had to divide the width and height by the scaling factor (2.0 in this case) in a number of places where tick spacing etc is calculated.

**Comment by WizardCM** [comment]
Following the hints from @jclay, I experimented a little.

https://github.com/obsproject/obs-studio/blob/46118470abed7a4f4ee2398c90f8855988820f58/UI/volume-control.cpp#L1045

I read through the [RenderHints](https://doc.qt.io/qt-5/qpainter.html#RenderHint-enum), and tried out each of them.

```cpp
painter.setRenderHint(QPainter::SmoothPixmapTransform, true);
```
(125%)
![image](https://user-images.githubusercontent.com/941350/104449697-19036980-55f3-11eb-9bf8-3089cce802c6.png)

This one was the only one that retained a "consistent" look between ticks, **however** as it's smooth, it's very blurry (and therefore barely readable). The [Rendering Quality](https://doc.qt.io/qt-5/qpainter.html#rendering-quality) docs provided no insight.

I wonder if we want to just render everything in here at a larger resolution, then scale down. I do fear that on macOS that'd result in even worse performance, so I'd only enable such a hack on Windows.

**Comment by jclay** [comment]
@WizardCM regarding performance, keep in mind the ticks and meter are drawn with different painter instances iirc. You could only upscale the tick drawing part. It is only done once and already gets cached until resize, so performance impact should be negligible on macOS.
