### ISSUE TITLE
Video Capture from iOS device does not handle resolutions properly

### ISSUE THREAD

**Issue by wookayin** [obsproject/obs-studio#3923]
## Platform

Operating system and version: MacOS 11.0 Big Sur (M1) & MacOS 10.14 Mojave (Intel)
OBS Studio version: 26.1.0

iOS: 13.3.1 (iPad Pro) / 14.0 (iPhone)

## Expected Behavior

In the video capture source properties, we should be able to select resolutions just like other webcams.

The video capture source should support iPad's maximum native resolution.

## Current Behavior

When "Use Preset" is clicked, I can see some preset resolutions such as 1280x720, 540p, 480p, etc., and Maximum. However, when it is unclicked, the dropdown list does not show any available resolutions. Screenshot:

![image](https://user-images.githubusercontent.com/1009873/102549725-9a1a2000-408a-11eb-8fd3-2648fdfac2a4.png)

Also, in such situations, it cannot capture the video at all. No videos on "High" preset as well.  (AVCaptureSessionPresetHigh does not work)  It seems that on some environments (e.g. 10.15) it works but broken on 11.0.

As a result, the maximum resolution I can get is 1280x720 (16:9), where there are some black paddings on the left and right side (as iPad's screen resolution has 4:3 ratio). 

I can reproduce same results with iPhone. QuickTime is able to receive a 1126x2436 video, but OBS is not.

## Steps to Reproduce

Straightforward.

1. Launch OBS
2. Connect iPad/iPhone to mac. Add a Video Capture source.
3. Unclick "use preset"

## Additional information

NA

**Comment by wookayin** [comment]
Additional information: looks not being able to enumerate available resolutions is a macOS SDK limitation.

From the source code https://github.com/obsproject/obs-studio/blob/master/plugins/mac-avcapture/av-capture.mm:

- `enumerate_resolutions(AVCaptureDevice *dev)`: `dev.formats` enumerates only one `AVCaptureDeviceFormat`, which is `{ .width = 0, .height = 0 }`.

**Comment by ryandesign** [comment]
I am able to capture high-resolution video from my iPhone in OBS by checking the "Use Preset" checkbox and selecting the "High" preset.

**Comment by wookayin** [comment]
@ryandesign Is your macOS version Big Sur? Is it a Intel mac or M1 mac?

**Comment by ryandesign** [comment]
It works for me on macOS Big Sur 11.0.1 on 2012 15" MacBook Pro with Retina Display. Also works on macOS High Sierra 10.13.6 on 2016 15" MacBook Pro with Touch Bar. I haven't tested on any Apple Silicon Macs.

**Comment by wookayin** [comment]
I see, thanks. I do not have any intel mac with Big Sur installed. The "High" preset not working seems to be a M1 (Rosetta2) issue then. I am waiting from Apple's support on this.

**Comment by yoavartzi** [comment]
Any update on this? The "high" preset still seems not to work on M1 machines with the highest functioning resolution for Video Capture Device with an iPad is 720p.

**Comment by wookayin** [comment]
OBS 27 now supports 1080p and 2160p presets (ead1c63a187e6e1efd4cb8d604c669e608e032d6), and I think this is a pretty good workaround. One still needs to *crop* unnecessary black regions (paddings) though. The "high" preset still does not work (as of 11.2) which I think is a macOS bug.

**Comment by PatTheMav** [comment]
There doesn't seem to be anything wrong in the code - the AVCaptureDevice only returns a single format with a resolution of "0x0", so using the Preset is the canonical way to set up such devices.

**Comment by nickretallack** [comment]
Could you please add a way to type in the correct source resolution like you can in the Video Base (Canvas) Resolution settings?

**Comment by victornpb** [comment]
Could it be that the resolution changes once the stream starts? as it could change from landscape to portrait? it used to work
