### ISSUE TITLE
OBS automatically switches red and blue on alt+tab from or back to the game (or toggle preview on/off).

### ISSUE THREAD

**Issue by kindagoose** [obsproject/obs-studio#3935]
## Platform

Operating system and version: Linux Pop!_OS 20.04
OBS Studio version: 26.1.0 (the issue was in previous versions as well)

## Expected Behavior

Nothing should change because of preview toggling.

## Current Behavior

Sometimes while streaming or recording turning on the preview shows the source with switched red and blue colours, and sometimes it switches it back to normal, basically it switches colours randomly so using a checkbox in properties isn't a solution. It affects both stream and recordings.

Log: https://obsproject.com/logs/cRHoG4DjHuv8epTC
Look at the end of the log, where I constantly switch preview on and off after the issue appeared again.

## Steps to Reproduce

1. Capture any game with window capture (xcomposite)
2. Show preview
3. Toggle preview on and off or alt+tab from game and back until it will happen, sometimes it takes a couple of minutes, sometimes it is instant.
4. PROFIT??

## Additional information

So far had it in Dark Souls 3, Dark Souls Remastered, RPCS3, Hollow Knight.

**Comment by kkartaltepe** [comment]
please put upload your log somewhere like https://obsproject.com/tools/analyzer to preserve formatting and make your post readable.

**Comment by ewbteewbte** [comment]
Added link to the log. Sorry.

**Comment by kkartaltepe** [comment]
I cannot replicate this, your rendering looks broken already before the stats window has been docked. We have change a lot of the qt properties for 27. Please test with one of the RCs and we can reopen if you still see this happening.

**Comment by kkartaltepe** [comment]
fixed on egl backend.
