### ISSUE TITLE
Hiding a scene also hides nested base scene used elsewhere

### ISSUE THREAD

**Issue by Gameagle** [obsproject/obs-studio#3947]
## Platform
Operating system and version: Win10 64bit
OBS Studio version: 26.1.0 (64bit)

## Expected Behavior
When a scene with a nested scene inside is hidden it shouldn't apply the hide down to its content (so the nested scene). This seems to also happen when the nested scenes are moved into a folder and the folder is hidden.

## Current Behavior
Following nested scene setup:
Webcam Raw -> [Video Source]: Webcam
Webcam Greenscreen -> [Scene]: Webcam Raw
Webcam Frame -> [Scene]: Webcam Raw, additional graphics & text

Webcam Greenscreen and Webcam Frame are both nested inside a scene "Stream". When Greenscreen or Frame is hidden with the eye tool the other scene also looses the video stream from the webcam (the base scene Webcam Raw is being hidden). So it seems hiding the nested scene also hides every other scene thats nested in there, instead of just hiding the very top scene.

## Steps to Reproduce
1. Create a scene with a webcam as video source
2. Include scene from step 1 as nested scene in two other scenes
3. Include both scenes from step 2 as nested scenes in the actual scene that is shown (e.g. live feed)
4. Hide one of the scenes and the base video source will also be hidden in the other (still visible) scene
5. Check other scenes: The scene from step 1 is marked as visible everywhere else but behaves like it is hidden

## Workaround
Hide the nested base scene inside one of the scenes (e.g. Webcam Raw in Webcam Greenscreen) and enable it again. Afterwards Webcam Greenscreen and Webcam Frame can be hidden independent from one another while keeping the base video feed (or Webcam Raw) visible.

## Additional information
**I'm not sure if this is a bug or intended by design. Any hint is appreciated.**

Why this approach? To be able to alter the base scene (the raw webcam feed) for color correction or cropping and e.g. to use the webcam with a frame in different live scenes. While the webcam frame could be inserted as reference with this approach there is a scene which contains all graphics that could be changed from time to time. So there is no need so search for the source / group referenced from in other scenes, but to use the scene in the root to quickly find and edit items that are applied elsewhere.

**Comment by Warchamp7** [comment]
I wasn't able to reproduce this issue on my end. Everything appears to be working as intended.

https://user-images.githubusercontent.com/1554753/103175667-ab58ee80-4839-11eb-9fe4-5c5bff370ca9.mp4

**Comment by RytoEX** [comment]
I cannot reproduce this in OBS Studio 28.0.3. If you retest and experience this in OBS Studio 28.0.3 (or newer), please comment with a new OBS log and new steps to reproduce, and we can consider reopening this.
