### ISSUE TITLE
Error is displayed when uploading Current Log File on macOS after 26.1 update

### ISSUE THREAD

**Issue by heyitsjk** [obsproject/obs-studio#3959]
## Platform
Operating system and version: macOS 10.14.6
OBS Studio version: OBS 26.1.0

## Expected Behavior
The ability to upload a current log file to function as expected. 
(Help > Logs > Upload Current Log File)

## Current Behavior
An application error alert appears with the following message: 
error setting certificate verify locations: CAfile: /usr/local/etc/openssl@1.1/cert.pem CApath: /usr/local/etc/openssl@1.1/certs

No URL is generated

## Steps to Reproduce

1. Click Help
2. Click Logs
3. Click Upload Current Log File 
4. Observe Displayed Error Message

## Additional information

![Screen Shot 2020-12-22 at 12 26 32 PM](https://user-images.githubusercontent.com/74597290/102930261-f39a9a00-4450-11eb-94aa-cca2aa707cd8.png)

**Comment by PatTheMav** [comment]
Known issue and fixed via https://github.com/obsproject/obs-studio/pull/3895 - should land in the next patch release.
