### ISSUE TITLE
Display Capture: disabling Show Cursor does not work

### ISSUE THREAD

**Issue by wookayin** [obsproject/obs-studio#3961]
## Platform

Operating system and version: macOS 11.0 Big Sur
OBS Studio version: OBS 26.1.0

## Expected Behavior

When "Show Cursor" is turned off, the display capture source should not capture cursors.

## Current Behavior

Regardless "Show Cursor" is on/off, the display capture source always shows cursors captured.

![image](https://user-images.githubusercontent.com/1009873/102951775-a394f500-449b-11eb-80f2-5e24573b15d4.png)

## Steps to Reproduce

1. Launch OBS
2. Add a Display Capture
3. uncheck "Show Cursor"
4. the captured frame still shows mouse cursors

## Additional information

-

**Comment by wookayin** [comment]
Interestingly, on another mac with 10.15 it works well -- the cursor disappears when the option has been disabled. Guess this would be a Big Sur issue.

**Comment by WizardCM** [comment]
The code in question:

https://github.com/obsproject/obs-studio/blob/20fb235b8fe86284fcd0de7848a76056b0771228/plugins/mac-capture/mac-display-capture.m#L207

The API in question [kCGDisplayStreamShowCursor](https://developer.apple.com/documentation/coregraphics/kcgdisplaystreamshowcursor?language=objc) in [CGDisplayStreamCreateWithDispatchQueue](https://developer.apple.com/documentation/coregraphics/1454968-cgdisplaystreamcreatewithdispatc?language=objc).

I wonder if the cast to `id` is causing an issue, as the API explicitly states

> The value must be specified as a CFBoolean

**Comment by wookayin** [comment]
It appears to be a macOS SDK bug. 

I tried a couple of possibilities like:

```
(__bridge NSString *)kCGDisplayStreamShowCursor: (dc->hide_cursor ? @NO : @YES), 
```
in which the behavior is same (works on 10.15 but not on 11.0), or


```
(__bridge NSString *)kCGDisplayStreamShowCursor: @(CFBooleanGetValue(show_cursor_cf)),
```
in which cursors are never shown on either case. I guess it is a regression bug around null pointer vs false object (kCFBooleanFalse). I have reported a bug to Apple, and am waiting for the feedback.

**Comment by wookayin** [comment]
Found a commit a892fa9e33d9c91db40af2952076b67154bed9bc which says the use of `id` casting was necessary. Sounds very odds to me.

/cc @jp9000 Do you have any idea?

**Comment by WizardCM** [comment]
I guess a workaround in the meantime would be @true for show vs null for hide?

**Comment by wookayin** [comment]
I also tried several values for hiding cursors like NULL but it is ignored by Big Sur. Conditionally setting `@(CFBooleanGetValue(show_cursor_cf))` also did not work. Maybe my guess about NULL was wrong; I just cannot make cursor hidden. Let me try a few more things and will let you know of the possible workaround.

**Comment by wookayin** [comment]
I found the reason --- when **there are multiple sources** (or any other applications other than OBS capturing the device screen), the option conflicts. The code has no problem.

Specifically, here is how to reproduce (reproducible both in 10.15 and 11.0; Intel/M1):

- Create a display capture source A with cursor *shown*
- Create another display capture source B with cursor *hidden*

Then B will *always* have cursors shown and captured, because of the existence of A. Another program that captures the screen but with capturing cursor enabled (this was the my case as I was having only one display capture source) can replace the display source A.

If there is only one display capture source, or all such sources have options "hide cursors", then the option works fine. I still believe this is a limitation or bug of MacOS CoreGraphics SDK. Not sure how this can be fixed.

**Comment by PatTheMav** [comment]
What's weird is if I disable the cursor on source A and then create a new source B, the new source has the cursor activated by default. This makes the cursor appear on source A as well.

As soon as source B is removed, source A doesn't show the cursor again. I haven't dug into the display capture source code, but it seems weird that as soon as a second display capture stream _with_ a cursor is removed the first source is able to revert to its own settings.

**Comment by wookayin** [comment]
My guess is that the internal graphics buffer for one display device is shared across all display capturing sessions (not only within OBS but across any other applications too). In my experiments, if there is *any* active display capture session with cursor appear enabled (which is by default, unfortunately), the cursor will appear in *all* existing capturing sessions.

**Comment by PatTheMav** [comment]
@wookayin Yeah that sounds about right. Given that fact I think it's fine to close the issue, would you agree?

**Comment by wookayin** [comment]
Yes, I am okay with that. If anyone come across a solution to work around the limitation of CoreGraphics, let's revisit the issue.

**Comment by mufunyo** [comment]
> If anyone come across a solution to work around the limitation of CoreGraphics (or I hear any updates from Apple), let's revisit the issue.

The obvious workaround would be to force the cursor off at all times, and selectively draw a fake cursor in OBS, the same way we do with BitBlt capture on Windows?
