### ISSUE TITLE
Issue initializing various Font Style within a Font Family

### ISSUE THREAD

**Issue by Jimmyson** [obsproject/obs-studio#3962]
## Platform
Operating system and version: **Windows 10 Pro 1909 (Build 18363.1256)**
OBS Studio version: **26.1.0**

## Expected Behavior
Previewing and initializing correct font style within any Text layer, and the Font Selection text box.

## Current Behavior
Font Preview window, Text Properties window and OBS output incorrectly displays other font styles of the chosen font family

## Steps to Reproduce
Updated from [response below](https://github.com/obsproject/obs-studio/issues/3962#issuecomment-1304351898)

1. Retrieve the font files [attached](https://github.com/obsproject/obs-studio/files/9942534/font.ttf%2Botf.zip)
2. Install OTF files to the Windows Font Directory __(These will be the baseline)__
   - Either via the Windows 10 Control Panel
   - Font Preview Window
   - Explorer Context Menu on the File
3. Open OBS 28.0.3
4. Create a new Text Source
5. Select `ABCSans` from the first **Font** list
6. Set the **Font style** (start with Light)
7. Save the selection and confirm the Font Panel matches the Preview Panel. <- **Issue is shown here**
8. Commit the Text Source to the scene <- **Issue is shown here**
9. Validate the ABCSans font is being displayed
10. Open the Text Source Properties, and the "Select Font" window
11. Change the **Font Style** to `RoundedBold`
12. Save the selection and confirm the Font Panel matches the Preview Panel. <- **Issue is shown here**
13. Commit the Text Source to the scene <- **Issue is shown here**
14. Reopen the Text Source Properties, and the "Select Font" window scene
14. Change the **Font** to `ABCSans CondensedBold`
15. Save the selection and confirm the Font Panel matches the Preview Panel. <- **Issue is resolved here**
16. Commit the Text Source to the scene
17. Remove the Text Source and close OBS
18. Uninstall the Font from Windows using the Windows 10 Control Panel
19. Install the TTF file to the Windows Font Directory and repeat from Step 3. <- **Issue persists with TTF variant**

## Notes
- There are further font style variants with the `TTF` font set, allowing for more chances to test with
- It's more likely a font issue with the internal metadata embedded in the `OTF` and `TTF` data, but worth checking why TTF is unable to select the font styles correctly, nor reveal each style under the **Font** list on the selection window.

https://user-images.githubusercontent.com/8276052/102956069-89a2f300-452b-11eb-9451-b400240c93d2.mp4

## Additional information
Not every font with various styles experiences this. I am currently experiencing this with the _ABCSans_ and _ABCSans Serif_ font-family. I have tried the TTF and OTF formats, and experience the same problem. Whatever font is installed first, is the style that's fallen back upon. Sometimes, when a font is selected, it is not used when rendering into the preview or output.

The issue only happens inside OBS.

![List of Font Styles for ABCSans](https://user-images.githubusercontent.com/8276052/102956103-a2aba400-452b-11eb-9883-7c2751eeb916.png)

![obs64_2020-12-22_22-15-23](https://user-images.githubusercontent.com/8276052/102956112-ab9c7580-452b-11eb-8e5b-cef40c0f34b7.png)
![obs64_2020-12-22_22-15-42](https://user-images.githubusercontent.com/8276052/102956116-ac350c00-452b-11eb-8fd2-fae6639c77bb.png)
![obs64_2020-12-22_22-15-51](https://user-images.githubusercontent.com/8276052/102956119-accda280-452b-11eb-9382-4d774382bbde.png)
![obs64_2020-12-22_22-16-07](https://user-images.githubusercontent.com/8276052/102956121-ad663900-452b-11eb-8acb-2692c378e500.png)
![obs64_2020-12-22_22-16-21](https://user-images.githubusercontent.com/8276052/102956123-adfecf80-452b-11eb-93a0-21a9e7416021.png)
![obs64_2020-12-23_14-04-34](https://user-images.githubusercontent.com/8276052/102956124-ae976600-452b-11eb-99f2-522f29fcd80b.png)

Case where ABCSans Serif has been selected, but not rendered on the Preview
![obs64_2020-12-23_14-29-00](https://user-images.githubusercontent.com/8276052/102956126-af2ffc80-452b-11eb-91f9-08b28a7df0ec.png)

**Comment by PatTheMav** [comment]
Could you please test and confirm whether this is still an issue with OBS 28.0.3?

It would also be great if you could provide very concrete reproduction steps (which font file to install in the system, which precise steps to take to reproduce).

In my tests I wasn't able to reproduce the described issue, the only issue I found was that the ABCSans Regular variant was displayed as italic, which usually happens if a font uses a slant value in its tables, but does not set the OS/2 ITALIC style variable (alas Linux, Windows, and freetype still rely on these old font tables).

**Comment by RytoEX** [comment]
> In my tests I wasn't able to reproduce the described issue

I was also unable to reproduce this in my recent tests.

**Comment by Jimmyson** [comment]
It has been some time since the original post. I have downloaded the latest version and reattempted the creation of the Text Source

I am still receiving the issue.
I have not updated my font files since my original ticket.

Fonts were installed via the "Install" context menu option in Windows, and the Font Settings Page

![image](https://user-images.githubusercontent.com/8276052/198015806-c59f22af-15d0-483f-ae74-470780f0e453.png)

I am currently using the TTF formatted font files. OTF and other formats exist.
There is also a variant family on ABCSans called ABCSerif. I also have these fonts in TTF format any whilst they exhibit the same issue, there are also extra records in the Font List window that manage to be properly assigned.

![image](https://user-images.githubusercontent.com/8276052/198021975-b73f7c61-9a5d-429d-986a-bfe8ab7eae40.png)

![image](https://user-images.githubusercontent.com/8276052/198020559-99d4220c-a37e-452b-82e8-870e4ec7d614.png)

I took the opportunity to utilize the OTF files of ABCSans, and it presented the same issue a ABCSerif, where the grouped font record failed to assign, but the individual font weights in the same list worked fine,

![image](https://user-images.githubusercontent.com/8276052/198021497-6404e481-4fa0-4ff6-9fc7-54cae71dc020.png)

It's possible there is an issue with the Font-files themselves. There was a updated metadata content between ABCSans in TTF verses all other variants

![image](https://user-images.githubusercontent.com/8276052/198022310-ba4db557-3edc-48cf-b04c-397fbe98f11d.png)

I'll aim to have some detailed Reproduction Steps soon.

**Comment by Jimmyson** [comment]
## Steps to Reproduce

1. Retrieve the font files [attached](https://github.com/obsproject/obs-studio/files/9942534/font.ttf%2Botf.zip)
2. Install OTF files to the Windows Font Directory __(These will be the baseline)__
   - Either via the Windows 10 Control Panel
   - Font Preview Window
   - Explorer Context Menu on the File
3. Open OBS 28.0.3
4. Create a new Text Source
5. Select `ABCSans` from the first **Font** list
6. Set the **Font style** (start with Light)
7. Save the selection and confirm the Font Panel matches the Preview Panel. <- **Issue is shown here**
8. Commit the Text Source to the scene <- **Issue is shown here**
9. Validate the ABCSans font is being displayed
10. Open the Text Source Properties, and the "Select Font" window
11. Change the **Font Style** to `RoundedBold`
12. Save the selection and confirm the Font Panel matches the Preview Panel. <- **Issue is shown here**
13. Commit the Text Source to the scene <- **Issue is shown here**
14. Reopen the Text Source Properties, and the "Select Font" window scene
14. Change the **Font** to `ABCSans CondensedBold`
15. Save the selection and confirm the Font Panel matches the Preview Panel. <- **Issue is resolved here**
16. Commit the Text Source to the scene
17. Remove the Text Source and close OBS
18. Uninstall the Font from Windows using the Windows 10 Control Panel
19. Install the TTF file to the Windows Font Directory and repeat from Step 3. <- **Issue persists with TTF variant**

## Notes
- There are further font style variants with the TTF family, allowing for more chances to test with
- It's more likely a font issue with the internal metadata embedded in the OTF and TTF data, but worth checking why TTF us unable to select the font styles correctly, nor reveal each style under the *Font* list on the selection window.

**Comment by Fenrirthviti** [comment]
Closing as stale. If this is still an issue please open a new issue with updated reproduction steps on the latest version of OBS.

**Comment by CosmicEffect** [comment]
I'm with exact same issue: select Akagi Pro font and it shows a different font. Tried different sizes (someone said that would work, it doesn't), tried reinstalling the font, downloaded a new TTF... nothing. Someone can help with that one? I'm on Windows 10 and OBS 31.1.1. 

<img width="462" height="427" alt="Image" src="https://github.com/user-attachments/assets/a0a40ab0-d695-464e-923c-d2aa5d480043" />
