### ISSUE TITLE
Version number not shown in Get Info window

### ISSUE THREAD

**Issue by ryandesign** [obsproject/obs-studio#3968]
## Platform
Operating system and version: macOS 11.0.1
OBS Studio version: 26.1.0

## Expected Behavior
Get Info window should show the program's version in the Version field.

## Current Behavior
Get Info window shows "OBS - Free and Open Source Streaming/Recording Software" in the Version field.

<img width="377" alt="Screen Shot 2020-12-24 at 4 55 09 PM" src="https://user-images.githubusercontent.com/429209/103107970-d5779a00-4608-11eb-81ce-d832c4d2e2d4.png">

## Steps to Reproduce
1. Select the OBS.app icon in the Finder
2. Choose Get Info from the File menu

## Additional information
This happens because in CI/scripts/macos/app/Info.plist you set `CFBundleGetInfoString`. This key is obsolete; its replacement is `NSHumanReadableCopyright`, however normally you would not set either of these (unless you need to store a copyright string that you can load into your About box for example, in which case feel free to do so). Instead, you would set `CFBundleShortVersionString` to the version number (e.g. 26.1.0) and set `CFBundleVersion` to the build number. For example, if you have a CI system that builds for every change, it could increment `CFBundleVersion` on every build, while `CFBundleShortVersionString` would not change until you decide to do a new version release.

**Comment by WizardCM** [comment]
For reference, this is the offending obsolete line that we use;

https://github.com/obsproject/obs-studio/blob/20fb235b8fe86284fcd0de7848a76056b0771228/CI/scripts/macos/app/Info.plist#L9-L10

CMake does have a way to set Info.plist values apparently. We could reuse the strings we use for the Windows rc file.

**Comment by PatTheMav** [comment]
@ryandesign Feel free to submit a PR to fix this - you'll need to update the `full-build-macos.sh` script as well as the `main.yml` Github CI workflow and also the `CMakeLists.txt` for the DAL plugin to keep these values in sync.

You probably also need to come up with a way to keep track of or procedurally create the `CFBundleVersion` counter to have it properly increment on CI and on local builds.

Feel free to remove `CFBundleGetInfoString` from the template `Info.plist` while you're at it. Much appreciated.

**Comment by ryandesign** [comment]
I'm not going to have time to work on it.

**Comment by WizardCM** [comment]
Fixed via #4553.
