### ISSUE TITLE
Duplicating Sources Behaves Weirdly

### ISSUE THREAD

**Issue by MrTeeXD** [obsproject/obs-studio#3976]
## Platform

Operating system and version: Windows 10 64bit Build 20H2
OBS Studio version: 26.1.0

## Expected Behavior
When I tried to duplicate my Webcam to a new scene, it behaves abnormally, instead, it acts like its one with another source.

## Current Behavior
 
I should be able to duplicate my Webcam Source without having it acting like its one with another source.

## Steps to Reproduce

1. Create a new scene
2. Right click, add Video Capture Device, select Add existing and select the already existing source
3. Try moving the source around and you will see it is paired with another source

## Additional information

I have a screen recording of this happening right here:
https://user-images.githubusercontent.com/37266538/103143250-f9c39b80-471a-11eb-930e-cae1c0aed66b.mp4

**Comment by WizardCM** [comment]
When you choose "Add Existing", that is not duplicating. That is creating a new instance of the same source.

Webcams cannot be duplicated because only one "source" can use hardware webcams at a time, so we essentially make it harder to accidentally break your configuration.

By design.
