### ISSUE TITLE
If Camera settings window is open, shows not responding at OBS shutdown

### ISSUE THREAD

**Issue by bass9030** [obsproject/obs-studio#3977]
## Platform

Operating system and version: Windows 10 Build 20H2 64Bit
OBS Studio version: 26.1

## Expected Behavior

The OBS shut down normally.

## Current Behavior

OBS shows not responding, but camera settings window can be operated normally, and if you close the camera settings window, the OBS shut down normally.

## Steps to Reproduce

1. Open OBS
2. Enter the Camera Settings window on any video capture device.
3. With the camera settings window open, exit the OBS with the End button or the X button on the top left.
4. The OBS displays not responding, but the camera settings window works normally.

https://user-images.githubusercontent.com/59216834/103162110-223cba00-482f-11eb-95e0-d7f7b1d111da.mp4

**Comment by mufunyo** [comment]
For what its worth, Microsoft Management Console does the same thing if you leave a properties window open.

**Comment by Fenrirthviti** [comment]
Closing as stale. If this is still an issue please open a new issue with updated reproduction steps on the latest version of OBS.
