### ISSUE TITLE
Screen preview now working on wayland

### ISSUE THREAD

**Issue by bl4ckb0ne** [obsproject/obs-studio#3984]
## Platform

Operating system and version: Archlinux 
OBS Studio version: 26.0.2-3

Running on sway 1.5.1

## Expected Behavior
Screen preview is shown in the obs window

## Current Behavior
The screen preview is not rendered, but the stream somehow works.

## Steps to Reproduce

1. install https://hg.sr.ht/~scoopta/wlrobs
2. start obs
3. add a wayland output (scpy)
4. start stream

## Additional information

Log from execution https://pastebin.com/a9C3gUJM

Even if this log is appearing, i assure you that this isnt a compositor issue
```
qt.qpa.wayland: Ignoring unexpected wl_surface.enter received for output with id: 18 screen name: "DVI-D-1" screen model: "2267W" This is most likely a bug in the compositor.
```

**Comment by WizardCM** [comment]
OBS doesn't officially support wayland, and the plugin you linked is third party.

If you'd like to keep an eye out for Wayland support, watch #2478 #2482 #2484

**Comment by ubone** [comment]
You can use obs to record your wayland desktop if you use sway or anything else that wf-recorder works in via v4l2 loopback. See https://wiki.archlinux.org/index.php/Screen_capture#Via_a_virtual_webcam_video_feed
