### ISSUE TITLE
Documentation Error:  Instructions XCode with CMake Incorrect/Incomplete

### ISSUE THREAD

**Issue by DAConsulting** [obsproject/obs-studio#3987]
When following instructions to create XCode project, the process fails with insufficient information.

## Platform

Operating system and version:  Mac OSX 15.x
OBS Studio version:  Latest

## Expected Behavior

Following instructions should result in XCode project being generated.

## Current Behavior

Following instructions results in an error with insufficient information provided.

## Steps to Reproduce

1. Follow the instructions for downloading and building on Mac as per this Wiki:

```
https://obsproject.com/wiki/install-instructions
> Wiki - Install Instructions | OBS
> If you want to develop for OBS, please visit our Discord and get to know the devs or have questions answered! Also, if there is something in this guide you want to change/improve…
> obsproject.com obsproject.com
```

2.  Everything will build, and you can run and use OBS, BUT....

3.  Following these instructions for running CMake to build the XCode project results in an error:

```
macOS Xcode Project
To create an Xcode project for OBS, cmake must be run with additional flags. Follow the build instructions above to create a working configuration setup, then add -G Xcode to the cmake command, e.g.:

cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13 -DDISABLE_PYTHON=ON -G Xcode
```

4. You will receive this error:

```
CMake Warning:

**No source or binary directory provided. Both will be assumed to be the
same as the current working directory, but note that this warning will
become a fatal error in future CMake releases.

CMake Error: The source "/Users/darndt/projects/obs-studio/build/CMakeLists.txt" does not match the source "/Users/darndt/Projects/obs-studio/CMakeLists.txt" used to generate cache. Re-run cmake with a different source directory.**
```

PROBLEMS:

A) Nothing specified as to HOW to change to change the '**source directory**' as suggested in the error.  (Is it an environment variable? Or is this specified somewhere else?)

B) No information as to what the the source directory should be set TO  

C) This is all following the instructions on the wiki, on a clean machine, so the current directory structure matches that structure, but the process fails.  Instructions should be added to indicate how to complete the process of setting up the XCode project, including A) how to specify the source directory and B) what should it be, assuming a clean install following these instructions.

**Comment by gxalpha** [comment]
You forgot to add the `..` to the command.
This is important if you are in a subdirectory (like "obs-studio/build" or something; as it points to the directory above, the root directory. 
The command has to be 
```
cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13 -DDISABLE_PYTHON=ON -G Xcode ..
```
Btw this is how it is described in the wiki

**Comment by RytoEX** [comment]
> PROBLEMS:
> 
> A) Nothing specified as to HOW to change to change the '**source directory**' as suggested in the error. (Is it an environment variable? Or is this specified somewhere else?)
> 
> B) No information as to what the the source directory should be set TO
> 
> C) This is all following the instructions on the wiki, on a clean machine, so the current directory structure matches that structure, but the process fails. Instructions should be added to indicate how to complete the process of setting up the XCode project, including A) how to specify the source directory and B) what should it be, assuming a clean install following these instructions.

A) The cmake CLI syntax can be looked up [elsewhere](https://cmake.org/cmake/help/latest/manual/cmake.1.html).
> `cmake [<options>] <path-to-source>`

B) Per the documentation you've referenced, the source directory is `..`, or the parent directory of your current directory, which is the build directory.
> Create a build directory inside the `obs-studio` directory, change to it

C) Neither A nor B seem to actually be an issue with our documentation.  In the future, this sort of question should probably be brought up on our Discord first rather than filing an issue on GitHub, per the documentation that you referenced:
> Also, if there is something in this guide you want to change/improve on, it is recommended that you talk about it with the devs in Discord or IRC first.

I'll be closing this now.
