### ISSUE TITLE
Wiki: two guides contradicting each other

### ISSUE THREAD

**Issue by Kadilov** [obsproject/obs-studio#3992]
Wiki page titled "GPU Overload Issues" tells that Windows 10 Game Mode should be disabled, while "How To Disable Windows 10 Gaming Features" recommends turning it on for Windows build 1809 and newer. The latter page has a more recent timestamp, so probably it means that the other page should be edited.

1. https://github.com/obsproject/obs-studio/wiki/GPU-overload-issues
2. https://github.com/obsproject/obs-studio/wiki/How-to-disable-Windows-10-Gaming-Features

Should I have posted it here? I assume two questions might arise...

_Why do not you edit it yourself, this is a wiki anyway?_
Unfortunately, I am not confident enough to choose which one of the contradicting pages has the right information. I did not benchmark OBS with and without Game Mode enabled. However, I found this contradiction important enough to report.

_Bug tracker is for docs, not wikis_
This is a valid point if the team members do not consider the wiki as user docs. I am not sure on this, giving the fact that there are no actual docs for the end user.

**Comment by Fenrirthviti** [comment]
These guides overlap in suggestions, but they serve two very different functions. The former should be edited, as game mode in 1809+ has been fixed to not affect OBS anymore. Feel free to amend.

**Comment by RytoEX** [comment]
I've already edited the former in an attempt to resolve this ambiguity.  In the future, this can probably be raised in conversation on our Discord rather than on GitHub.
