### ISSUE TITLE
Scripting Documentation still refers to permitting Python

### ISSUE THREAD

**Issue by walterrowe** [obsproject/obs-studio#4001]
## Platform

Operating system and version: macOS Catalina
OBS Studio version: 26.1.0

## Expected Behavior
Expected Python script to load from Tools > Scripts > +

## Current Behavior
Tools > Scripts > + shows python scripts grayed out.

## Steps to Reproduce
1. Open OBS 26.1.0 on macOS
2. Go to Tools > Scripts
3. Press "+" to load a script
4. Navigate to a folder with python scripts
5. Python scripts will be grayed out

## Additional information
Downloaded a Python script. Tools > Scripts would not load it. Searched forums and a comment stated Python was removed in OBS 26. Went to read scripting docs. Looked at the OBS Developer docs, and the Scripting section mentions LUA and Python. The Developer Docs for Scripting should remove references to Python if support was removed in OBS 26 as is claimed in this forum post.

https://obsproject.com/forum/threads/how-to-load-python-scripts-to-obs-studio.135044/#post-497992

**Comment by derrod** [comment]
OBS on macOS does not have python support, but OBS on Windows and Linux does.

**Comment by walterrowe** [comment]
> OBS on macOS does not have python support, but OBS on Windows and Linux does.

The documentation page should state this.

**Comment by jp9000** [comment]
The reason why it wasn't is because python support was working at some point, but we had to remove it. I think someone's been trying to get it working properly again but it's just been a bit on the back burner. So I don't think anyone's particularly in the wrong.

**Comment by PatTheMav** [comment]
https://github.com/obsproject/obs-studio/pull/3689 adds Python support on macOS again. It just hasn't been merged yet but it's planned in one of the next milestones iirc.

**Comment by walterrowe** [comment]
Thanks! Glad to hear this.
