### ISSUE TITLE
26.1.0-43 compilation error in plugins/decklink and obs-browser on slackware64 14.2 (stable)

### ISSUE THREAD

**Issue by tdkuehnel** [obsproject/obs-studio#4012]
## Platform
Operating system and version: Slackware64 14.2 (stable) on intel PC hardware
OBS Studio version: 26.1.0-43-g9616b79-modified

The used cmake is from the sbo cmake-202x

## Expected Behavior
cmake should configure and make should compile

## Current Behavior
[tdkuehnel@tdkuehnel3 build]$ /opt/cmake-202x/bin/cmake -DUNIX_STRUCTURE=0 -DCMAKE_INSTALL_PREFIX="${HOME}/obs-studio-portable" -DBUILD_BROWSER=ON -DCEF_ROOT_DIR="../../cef_binary_3770_linux64" ..
-- The C compiler identification is GNU 5.3.0
-- The CXX compiler identification is GNU 5.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- OBS_VERSION: 26.1.0-43-g9616b79-modified
-- Found OpenGL: /usr/lib64/libGL.so   
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found FFmpeg: /usr/bin/../lib64/libavcodec.so (found version "57.64.101") found components: avcodec avdevice avutil avformat 
-- Found Libcurl: /usr/bin/../lib64/libcurl.so  
-- Scripting: Luajit supported
-- Scripting: Python 3 supported
-- Found SWIG: /usr/bin/swig (found suitable version "3.0.7", minimum required is "2")  
-- Using system Jansson library
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- XCB[XCB]: Found component XCB
-- Found XCB: /usr/lib64/libxcb.so  found components: XCB 
-- Found X11_XCB: /usr/lib64/libX11-xcb.so  
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Found FFmpeg: /usr/bin/../lib64/libavformat.so (found version "57.56.101") found components: avformat avutil swscale swresample avcodec 
-- XCB[XINPUT]: Found component XINPUT
-- Found XCB: /usr/lib64/libxcb-xinput.so  found components: XINPUT 
-- Found PulseAudio - Audio Monitor enabled
-- Using libavcodec for image loading in libobs
-- Found ZLIB: /usr/bin/../lib64/libz.so  
-- XCB[XCB]: Found component XCB
-- XCB[RANDR]: Found component RANDR
-- XCB[SHM]: Found component SHM
-- XCB[XFIXES]: Found component XFIXES
-- XCB[XINERAMA]: Found component XINERAMA
-- Found XCB: /usr/lib64/libxcb.so;/usr/lib64/libxcb-randr.so;/usr/lib64/libxcb-shm.so;/usr/lib64/libxcb-xfixes.so;/usr/lib64/libxcb-xinerama.so  found components: XCB RANDR SHM XFIXES XINERAMA 
-- Found Libv4l2: /usr/lib64/libv4l2.so  
-- Found UDev: /usr/lib64/libudev.so  
-- Checking for module 'jack'
--   Found jack, version 1.9.14
-- Found jack: /usr/lib64/libjack.so
-- Found ALSA: /usr/lib64/libasound.so (found version "1.1.1") 
-- Found LibVLC: /usr/include/vlc  
-- Could NOT find Sndio (missing: Sndio_LIBRARY Sndio_INCLUDE_DIR) 
-- Sndio not found, disabling Sndio plugin
-- Looking for Chromium Embedded Framework in /home/tdkuehnel/Projekte/Software/cef_binary_3770_linux64
-- Using the bundled VST header.
-- Found Libx264: /usr/bin/../lib64/libx264.so  
-- Found FFmpeg: /usr/bin/../lib64/libavcodec.so (found version "57.64.101") found components: avcodec avfilter avdevice avutil swscale avformat swresample 
-- Found FFmpeg: /usr/bin/../lib64/libavcodec.so (found version "57.64.101") found components: avcodec avutil avformat 
-- Found MbedTLS: /usr/bin/../lib64/libmbedtls.so;/usr/bin/../lib64/libmbedcrypto.so;/usr/bin/../lib64/libmbedx509.so  
-- Found ftl-sdk: ftl outputs enabled
-- Found Libspeexdsp: /usr/bin/../lib64/libspeexdsp.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tdkuehnel/Projekte/Software/obs-studio/build
[tdkuehnel@tdkuehnel3 build]$ make
...
Scanning dependencies of target obs-browser
[ 38%] Building CXX object plugins/obs-browser/CMakeFiles/obs-browser.dir/obs-browser_autogen/mocs_compilation.cpp.o
[ 38%] Building CXX object plugins/obs-browser/CMakeFiles/obs-browser.dir/obs-browser-source.cpp.o
In file included from /home/tdkuehnel/Projekte/Software/obs-studio/libobs/graphics/../util/simde/x86/sse2.h:35:0,
                 from /home/tdkuehnel/Projekte/Software/obs-studio/libobs/graphics/../util/sse-intrin.h:24,
                 from /home/tdkuehnel/Projekte/Software/obs-studio/libobs/graphics/vec4.h:22,
                 from /home/tdkuehnel/Projekte/Software/obs-studio/libobs/graphics/vec3.h:21,
                 from /home/tdkuehnel/Projekte/Software/obs-studio/libobs/obs.h:26,
                 from /home/tdkuehnel/Projekte/Software/obs-studio/libobs/obs-module.h:20,
                 from /home/tdkuehnel/Projekte/Software/obs-studio/plugins/obs-browser/obs-browser-source.hpp:21,
                 from /home/tdkuehnel/Projekte/Software/obs-studio/plugins/obs-browser/obs-browser-source.cpp:19:
/home/tdkuehnel/Projekte/Software/obs-studio/libobs/graphics/../util/simde/x86/sse.h:530:59: error: 'simde_x_mm_round_ps' declared as an 'inline' variable
 #define simde_mm_round_ps(a, rounding) simde_x_mm_round_ps((a), (rounding), 0)
                                                           ^
/home/tdkuehnel/Projekte/Software/obs-studio/libobs/graphics/../util/simde/x86/sse.h:530:59: warning: 'simde_x_mm_round_ps' initialized and declared 'extern'
/home/tdkuehnel/Projekte/Software/obs-studio/libobs/graphics/../util/simde/x86/sse.h:530:59: warning: '__gnu_inline__' attribute ignored [-Wattributes]
/home/tdkuehnel/Projekte/Software/obs-studio/libobs/graphics/../util/simde/x86/sse.h:530:59: warning: '__always_inline__' attribute ignored [-Wattributes]
/home/tdkuehnel/Projekte/Software/obs-studio/libobs/graphics/../util/simde/x86/sse.h:530:59: warning: '__artificial__' attribute ignored [-Wattributes]
/home/tdkuehnel/Projekte/Software/obs-studio/libobs/graphics/../util/simde/x86/sse.h:530:59: error: '__m128 simde_x_mm_round_ps' redeclared as different kind of symbol
/home/tdkuehnel/Projekte/Software/obs-studio/libobs/graphics/../util/simde/x86/sse.h:410:13: note: previous declaration 'simde__m128 simde_x_mm_round_ps(simde__m128, int, int)'
 simde__m128 simde_x_mm_round_ps(simde__m128 a, int rounding, int lax_rounding)
             ^
/usr/lib64/gcc/x86_64-slackware-linux/5.3.0/include/smmintrin.h:125:1: error: expected primary-expression before '__V'
 _mm_round_ps (__m128 __V, const int __M)
 ^
/usr/lib64/gcc/x86_64-slackware-linux/5.3.0/include/smmintrin.h:125:1: error: expected ')' before '__V'
In file included from /usr/lib64/gcc/x86_64-slackware-linux/5.3.0/include/x86intrin.h:41:0,
                 from /usr/include/c++/5.3.0/x86_64-slackware-linux/bits/opt_random.h:33,
                 from /usr/include/c++/5.3.0/random:50,
                 from /usr/include/c++/5.3.0/bits/stl_algo.h:66,
                 from /usr/include/c++/5.3.0/algorithm:62,
                 from /home/tdkuehnel/Projekte/Software/cef_binary_3770_linux64/include/base/cef_scoped_ptr.h:136,
                 from /home/tdkuehnel/Projekte/Software/cef_binary_3770_linux64/include/internal/cef_ptr.h:40,
                 from /home/tdkuehnel/Projekte/Software/cef_binary_3770_linux64/include/cef_base.h:39,
                 from /home/tdkuehnel/Projekte/Software/cef_binary_3770_linux64/include/cef_app.h:41,
                 from /home/tdkuehnel/Projekte/Software/obs-studio/plugins/obs-browser/cef-headers.hpp:30,
                 from /home/tdkuehnel/Projekte/Software/obs-studio/plugins/obs-browser/obs-browser-source.hpp:23,
                 from /home/tdkuehnel/Projekte/Software/obs-studio/plugins/obs-browser/obs-browser-source.cpp:19:
/usr/lib64/gcc/x86_64-slackware-linux/5.3.0/include/smmintrin.h:130:1: error: expected ')' before 'extern'
 extern __inline __m128 __attribute__((__gnu_inline__, __always_inline__, __artificial__))
 ^
/usr/lib64/gcc/x86_64-slackware-linux/5.3.0/include/smmintrin.h:588:25: error: expected declaration before end of line
plugins/obs-browser/CMakeFiles/obs-browser.dir/build.make:94: recipe for target 'plugins/obs-browser/CMakeFiles/obs-browser.dir/obs-browser-source.cpp.o' failed
make[2]: *** [plugins/obs-browser/CMakeFiles/obs-browser.dir/obs-browser-source.cpp.o] Error 1
CMakeFiles/Makefile2:1404: recipe for target 'plugins/obs-browser/CMakeFiles/obs-browser.dir/all' failed
make[1]: *** [plugins/obs-browser/CMakeFiles/obs-browser.dir/all] Error 2
Makefile:170: recipe for target 'all' failed
make: *** [all] Error 2

## Steps to Reproduce
Install Slackware64 14.2 (stable)
configure and install xcb-proto-1.14.tar.gz    
configure and install libxcb-1.14.tar.gz 
install sbo cmake-202x
Follow the obs linux install guideline (portable distribution)
Disable decklink plugin (the same compilation error shown above occurs when trying to compile the deckling plugin)
cmake and make as above

## Additional information
I am at the end of my knowledge. Any insights of what may cause the errors are welcome ! Thanks you for the great software!

**Comment by kkartaltepe** [comment]
This doesnt happen on modern version of GCC. Simde claims support back to GCC 4.8-ish and the first error seems nonsensical to me. The second error seems more interesting combined with the first, it seems like simde failed to detect your platform as having native sse support and then your libc++ imported native sse headers which maybe caused some "bad things" to happen. 

Looking through simde it appears to be this error. https://github.com/simd-everywhere/simde/issues/459

**Comment by kkartaltepe** [comment]
I dont have this issue with the decklink, on my platform simd is detected and native headers are used in simde. Perhaps its due to the age of your compiler.

**Comment by kkartaltepe** [comment]
Looks like this conflict may have been fixed in gcc 6.1.0. Feel free to revert the simde changes 1e96573328775585551bb3e9105705af1aab5279 to continue building on your platform if you dont want to update.

**Comment by tdkuehnel** [comment]
Many thanks for your insights. I will pull up my gcc to the version mentioned and will report back.

Thanks a lot for the great software !
