### ISSUE TITLE
OBS 26.1 Hangs on macOS Catalina 10.15.7

### ISSUE THREAD

**Issue by evillgenius75** [obsproject/obs-studio#4014]
## Platform
Operating system and version: macOS Catalina 10.15.7
OBS Studio version: 26.1

## Expected Behavior
OBS launches after running from LaunchPad

## Current Behavior
OBS will not load and a Force quit reports a hang

## Steps to Reproduce
1. Install OBS from .pkg download
2. Run OBS from Launchpad

## Additional information
Apple Error Report:
Date/Time:        2021-01-04 09:09:29 -0600
End time:         2021-01-04 09:09:30 -0600
OS Version:       Mac OS X 10.15.7 (Build 19H114)
Architecture:     x86_64h
Report Version:   29

Data Source:      Stackshots
Shared Cache:     0x9f1b000 4A76F6C9-AF4F-3518-8B44-C276F5C6CF06

Command:          obs
Path:             /Applications/OBS.app/Contents/Frameworks/libavformat.58.dylib
Version:          ??? (???)
Parent:           launchd [1]
PID:              7713

Event:            hang
Duration:         1.00s
Steps:            11 (100ms sampling interval)

Hardware model:   MacBookPro16,1
Active cpus:      12
Boot args:        chunklist-security-epoch=0 -chunklist-no-rev2-dev

Time Awake Since Boot: 2700s

--------------------------------------------------
Timeline format: stacks are sorted chronologically
Use -i and -heavy to re-report with count sorting
--------------------------------------------------

Heaviest stack for the main thread of the target process:
  11  start + 1 (libdyld.dylib + 109769) [0x7fff710d2cc9]
  11  main + 5032 (obs + 203832) [0x10e9b6c38]
  11  OBSApp::OBSInit() + 505 (obs + 187401) [0x10e9b2c09]
  11  OBSBasic::OBSInit() + 201 (obs + 333001) [0x10e9d64c9]
  11  OBSBasic::ResetVideo() + 824 (obs + 340232) [0x10e9d8108]
  11  obs_reset_video + 471 (libobs.0.dylib + 411223) [0xf430657]
  11  gs_create + 304 (libobs.0.dylib + 111296) [0xf3e72c0]
  11  device_create + 103 (libobs-opengl.so + 54583) [0x27c79537]
  11  gl_platform_create + 18 (libobs-opengl.so + 17074) [0x27c702b2]
  11  gl_context_create + 80 (libobs-opengl.so + 17328) [0x27c703b0]
  11  -[NSOpenGLPixelFormat initWithAttributes:] + 52 (AppKit + 4083317) [0x7fff3467de75]
  11  CGLChoosePixelFormat + 85 (OpenGL + 36325) [0x7fff41b70de5]
  11  ??? (OpenGL + 39068) [0x7fff41b7189c]
  11  ??? (OpenGL + 25569) [0x7fff41b6e3e1]
  11  cglBadApplicationNotMuxAwareLockDown + 45 (OpenGL + 25249) [0x7fff41b6e2a1]
  11  ??? (OpenGL + 23196) [0x7fff41b6da9c]
  11  IOServiceOpen + 39 (IOKit + 13272) [0x7fff39ddf3d8]
  11  io_service_open_extended + 137 (IOKit + 13426) [0x7fff39ddf472]
  11  mach_msg_trap + 10 (libsystem_kernel.dylib + 3578) [0x7fff71213dfa]
 *11  hndl_mach_scall64 + 22 (kernel + 786982) [0xffffff80002c0226]
 *11  mach_call_munger64 + 517 (kernel + 2273349) [0xffffff800042b045]
 *11  mach_msg_overwrite_trap + 722 (kernel + 1100514) [0xffffff800030cae2]
 *11  ipc_kmsg_send + 309 (kernel + 1006901) [0xffffff80002f5d35]
 *11  ipc_kobject_server + 568 (kernel + 1176456) [0xffffff800031f388]
 *11  ??? (kernel + 2105487) [0xffffff800040208f]
 *11  is_io_service_open_extended + 297 (kernel + 8757817) [0xffffff8000a5a239]
 *11  ??? (AppleMuxControl2 + 34744) [0xffffff7f83f7a7b8]
 *11  IOWorkLoop::runAction(int (*)(OSObject*, void*, void*, void*, void*), OSObject*, void*, void*, void*, void*) + 62 (kernel + 8561374) [0xffffff8000a2a2de]
 *11  ??? (AppleMuxControl2 + 34604) [0xffffff7f83f7a72c]
 *11  ??? (AppleMuxControl2 + 36466) [0xffffff7f83f7ae72]
 *11  ??? (AppleMuxControl2 + 36693) [0xffffff7f83f7af55]
 *11  ??? (AppleMuxControl2 + 58793) [0xffffff7f83f805a9]
 *11  ??? (AppleMuxControl2 + 4450) [0xffffff7f83f73162]
 *11  IOEventSource::sleepGate(void*, unsigned int) + 75 (kernel + 8566475) [0xffffff8000a2b6cb]
 *11  IOGraphicsSystemWorkLoop::sleepGate(void*, unsigned int) + 9 (IOGraphicsFamily + 139121) [0xffffff7f83f38f71]
 *11  IOGraphicsWorkLoop::sleepGate(void*, unsigned int) + 100 (IOGraphicsFamily + 36532) [0xffffff7f83f1feb4]
 *11  lck_mtx_sleep + 112 (kernel + 1222832) [0xffffff800032a8b0]
 *11  thread_block_reason + 175 (kernel + 1285359) [0xffffff8000339cef]
 *11  ??? (kernel + 1291441) [0xffffff800033b4b1]
 *11  machine_switch_context + 200 (kernel + 2361416) [0xffffff8000440848]

Process:          obs [7713]
UUID:             5C064026-EECF-3BF8-A88F-14DC2893EBC9
Path:             /Applications/OBS.app/Contents/Frameworks/libavformat.58.dylib
Architecture:     x86_64
Parent:           launchd [1]
UID:              808689
Footprint:        14.38 MB
Start time:       2021-01-04 09:09:29 -0600
End time:         2021-01-04 09:09:30 -0600
Num samples:      11 (1-11)
CPU Time:         0.023s (53.6M cycles, 58.1M instructions, 0.92c/i)
Note:             1 idle work queue thread omitted

  Thread 0x124d9    DispatchQueue "com.apple.main-thread"(1)    11 samples (1-11)    priority 46 (base 46)
  <thread QoS user interactive (requested user interactive), IO tier 0>
  11  start + 1 (libdyld.dylib + 109769) [0x7fff710d2cc9] 1-11
    11  main + 5032 (obs + 203832) [0x10e9b6c38] 1-11
      11  OBSApp::OBSInit() + 505 (obs + 187401) [0x10e9b2c09] 1-11
        11  OBSBasic::OBSInit() + 201 (obs + 333001) [0x10e9d64c9] 1-11
          11  OBSBasic::ResetVideo() + 824 (obs + 340232) [0x10e9d8108] 1-11
            11  obs_reset_video + 471 (libobs.0.dylib + 411223) [0xf430657] 1-11
              11  gs_create + 304 (libobs.0.dylib + 111296) [0xf3e72c0] 1-11
                11  device_create + 103 (libobs-opengl.so + 54583) [0x27c79537] 1-11
                  11  gl_platform_create + 18 (libobs-opengl.so + 17074) [0x27c702b2] 1-11
                    11  gl_context_create + 80 (libobs-opengl.so + 17328) [0x27c703b0] 1-11
                      11  -[NSOpenGLPixelFormat initWithAttributes:] + 52 (AppKit + 4083317) [0x7fff3467de75] 1-11
                        11  CGLChoosePixelFormat + 85 (OpenGL + 36325) [0x7fff41b70de5] 1-11
                          11  ??? (OpenGL + 39068) [0x7fff41b7189c] 1-11
                            11  ??? (OpenGL + 25569) [0x7fff41b6e3e1] 1-11
                              11  cglBadApplicationNotMuxAwareLockDown + 45 (OpenGL + 25249) [0x7fff41b6e2a1] 1-11
                                11  ??? (OpenGL + 23196) [0x7fff41b6da9c] 1-11
                                  11  IOServiceOpen + 39 (IOKit + 13272) [0x7fff39ddf3d8] 1-11
                                    11  io_service_open_extended + 137 (IOKit + 13426) [0x7fff39ddf472] 1-11
                                      11  mach_msg_trap + 10 (libsystem_kernel.dylib + 3578) [0x7fff71213dfa] 1-11
                                       *11  hndl_mach_scall64 + 22 (kernel + 786982) [0xffffff80002c0226] 1-11
                                         *11  mach_call_munger64 + 517 (kernel + 2273349) [0xffffff800042b045] 1-11
                                           *11  mach_msg_overwrite_trap + 722 (kernel + 1100514) [0xffffff800030cae2] 1-11
                                             *11  ipc_kmsg_send + 309 (kernel + 1006901) [0xffffff80002f5d35] 1-11
                                               *11  ipc_kobject_server + 568 (kernel + 1176456) [0xffffff800031f388] 1-11
                                                 *11  ??? (kernel + 2105487) [0xffffff800040208f] 1-11
                                                   *11  is_io_service_open_extended + 297 (kernel + 8757817) [0xffffff8000a5a239] 1-11
                                                     *11  ??? (AppleMuxControl2 + 34744) [0xffffff7f83f7a7b8] 1-11
                                                       *11  IOWorkLoop::runAction(int (*)(OSObject*, void*, void*, void*, void*), OSObject*, void*, void*, void*, void*) + 62 (kernel + 8561374) [0xffffff8000a2a2de] 1-11
                                                         *11  ??? (AppleMuxControl2 + 34604) [0xffffff7f83f7a72c] 1-11
                                                           *11  ??? (AppleMuxControl2 + 36466) [0xffffff7f83f7ae72] 1-11
                                                             *11  ??? (AppleMuxControl2 + 36693) [0xffffff7f83f7af55] 1-11
                                                               *11  ??? (AppleMuxControl2 + 58793) [0xffffff7f83f805a9] 1-11
                                                                 *11  ??? (AppleMuxControl2 + 4450) [0xffffff7f83f73162] 1-11
                                                                   *11  IOEventSource::sleepGate(void*, unsigned int) + 75 (kernel + 8566475) [0xffffff8000a2b6cb] 1-11
                                                                     *11  IOGraphicsSystemWorkLoop::sleepGate(void*, unsigned int) + 9 (IOGraphicsFamily + 139121) [0xffffff7f83f38f71] 1-11
                                                                       *11  IOGraphicsWorkLoop::sleepGate(void*, unsigned int) + 100 (IOGraphicsFamily + 36532) [0xffffff7f83f1feb4] 1-11
                                                                         *11  lck_mtx_sleep + 112 (kernel + 1222832) [0xffffff800032a8b0] 1-11
                                                                           *11  thread_block_reason + 175 (kernel + 1285359) [0xffffff8000339cef] 1-11
                                                                             *11  ??? (kernel + 1291441) [0xffffff800033b4b1] 1-11
                                                                               *11  machine_switch_context + 200 (kernel + 2361416) [0xffffff8000440848] 1-11

  Thread 0x12546    11 samples (1-11)    priority 31 (base 31)    cpu time 0.021s (49.7M cycles, 57.4M instructions, 0.87c/i)
  <thread QoS default (requested default), IO tier 0>
  11  thread_start + 15 (libsystem_pthread.dylib + 7051) [0x7fff712d2b8b] 1-11
    11  _pthread_start + 148 (libsystem_pthread.dylib + 24841) [0x7fff712d7109] 1-11
      2   obs_hotkey_thread + 174 (libobs.0.dylib + 493790) [0xf4448de] 1-2
        2   os_event_timedwait + 176 (libobs.0.dylib + 260416) [0xf40b940] 1-2
          2   __psynch_cvwait + 10 (libsystem_kernel.dylib + 14466) [0x7fff71216882] 1-2
           *2   psynch_cvcontinue + 0 (pthread + 18722) [0xffffff7f82b41922] 1-2
      1   obs_hotkey_thread + 284 (libobs.0.dylib + 493900) [0xf44494c] 3
        1   obs_hotkeys_platform_is_pressed + 227 (libobs.0.dylib + 256819) [0xf40ab33] 3
          1   IOHIDDeviceGetValue + 33 (IOKit + 239597) [0x7fff39e167ed] 3
            1   ??? (IOHIDLib + 57959) [0x141a5267] 3
              1   ??? (IOHIDLib + 54870) [0x141a4656] 3
                1   -[NSArray indexOfObject:] + 229 (CoreFoundation + 301378) [0x7fff3702f942] 3
                  1   objc_release + 103 (libobjc.A.dylib + 34503) [0x7fff6ff1f6c7] (running) 3
      8   obs_hotkey_thread + 174 (libobs.0.dylib + 493790) [0xf4448de] 4-11
        8   os_event_timedwait + 176 (libobs.0.dylib + 260416) [0xf40b940] 4-11
          8   __psynch_cvwait + 10 (libsystem_kernel.dylib + 14466) [0x7fff71216882] 4-11
           *8   psynch_cvcontinue + 0 (pthread + 18722) [0xffffff7f82b41922] 4-11

  Thread 0x12548    Thread name "audio-io: audio thread"    11 samples (1-11)    priority 31 (base 31)    cpu time 0.002s (3.9M cycles, 715.0K instructions, 5.44c/i)
  <thread QoS default (requested default), IO tier 0>
  11  thread_start + 15 (libsystem_pthread.dylib + 7051) [0x7fff712d2b8b] 1-11
    11  _pthread_start + 148 (libsystem_pthread.dylib + 24841) [0x7fff712d7109] 1-11
      11  audio_thread + 418 (libobs.0.dylib + 177170) [0xf3f7412] 1-11
        11  usleep + 53 (libsystem_c.dylib + 490980) [0x7fff71199de4] 1-11
          11  __semwait_signal + 10 (libsystem_kernel.dylib + 14166) [0x7fff71216756] 1-11
           *11  semaphore_wait_continue + 0 (kernel + 1334000) [0xffffff8000345af0] 1-11

  Binary Images:
             0xe995000 -          0xebc8fff  libavformat.58.dylib                            <5C064026-EECF-3BF8-A88F-14DC2893EBC9>  /Applications/OBS.app/Contents/Frameworks/libavformat.58.dylib
             0xf3cc000 -          0xf473fff  libobs.0.dylib (0)                              <D5D25FC4-6337-3A60-ADD5-7378BF46B9AC>  /Applications/OBS.app/Contents/Frameworks/libobs.0.dylib
            0x14197000 -         0x141aafff  com.apple.iokit.IOHIDLib 2.0.0 (2.0.0)          <7F9377F9-15B8-3BE1-B464-6150546F5D3B>  /System/Library/Extensions/IOHIDFamily.kext/Contents/PlugIns/IOHIDLib.plugin/Contents/MacOS/IOHIDLib
            0x27c6c000 -         0x27c83fff  libobs-opengl.so (0)                            <3DE8BE29-D3C2-3B3A-92A9-E767FD9569D5>  /Applications/OBS.app/Contents/Frameworks/libobs-opengl.so
           0x10e985000 -        0x10ebc4fff  com.obsproject.obs-studio 26.1.0 (26.1.0)       <1E915057-5693-3A59-9B3B-B4F89A906774>  /Applications/OBS.app/Contents/MacOS/obs
        0x7fff34299000 -     0x7fff35059fff  com.apple.AppKit 6.9 (1894.60.100)              <322D043D-1140-3486-9523-3F56FF4D8349>  /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
        0x7fff36fe6000 -     0x7fff37465fff  com.apple.CoreFoundation 6.9 (1677.201)         <56B0FE5F-D493-3DF1-ABFF-ECC450268B97>  /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
        0x7fff39ddc000 -     0x7fff39e80fff  com.apple.framework.IOKit 2.0.2 (1726.140.1)    <14223387-6F81-3976-8605-4BC2F253A93E>  /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
        0x7fff41b68000 -     0x7fff41b77fff  com.apple.opengl 17.10.22 (17.10.22)            <D3C57A32-6BD0-3228-B1C4-0F42A6128A6C>  /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
        0x7fff6ff17000 -     0x7fff6ff4afff  libobjc.A.dylib (787.1)                         <6DF81160-5E7F-3E31-AA1E-C875E3B98AF6>  /usr/lib/libobjc.A.dylib
        0x7fff710b8000 -     0x7fff710eefff  libdyld.dylib (750.6)                           <789A18C2-8AC7-3C88-813D-CD674376585D>  /usr/lib/system/libdyld.dylib
        0x7fff71122000 -     0x7fff711a9fff  libsystem_c.dylib (1353.100.2)                  <BBDED5E6-A646-3EED-B33A-91E4331EA063>  /usr/lib/system/libsystem_c.dylib
        0x7fff71213000 -     0x7fff7123ffff  libsystem_kernel.dylib (6153.141.10)            <FF092EE8-5BEE-3B9A-8749-F0A067115C7E>  /usr/lib/system/libsystem_kernel.dylib
        0x7fff712d1000 -     0x7fff712dbfff  libsystem_pthread.dylib (416.100.3)             <62CB1A98-0B8F-31E7-A02B-A1139927F61D>  /usr/lib/system/libsystem_pthread.dylib
   *0xffffff7f82b3d000 - 0xffffff7f82b44fff  com.apple.kec.pthread 1.0 (1)                   <F40851B5-2F70-3CD5-9173-1D60125B6D0A>  /System/Library/Extensions/pthread.kext/Contents/MacOS/pthread
   *0xffffff7f83f17000 - 0xffffff7f83f43fff  com.apple.iokit.IOGraphicsFamily 576.1 (576.1)  <2B967D64-A3C5-30D6-87AD-5C4C413EDC1D>  /System/Library/Extensions/IOGraphicsFamily.kext/IOGraphicsFamily
   *0xffffff7f83f72000 - 0xffffff7f83f83fff  com.apple.driver.AppleMuxControl2 5.2.7 (5.2.7) <DD8F58E1-C56D-300F-A335-E83BBA991557>  /System/Library/Extensions/AppleGraphicsControl.kext/Contents/PlugIns/AppleMuxControl2.kext/Contents/MacOS/AppleMuxControl2
   *0xffffff8000200000 - 0xffffff8000bfffff  kernel (6153.141.10)                            <A477D537-F87E-3978-8D7F-A84B7C02E62E>  /System/Library/Kernels/kernel

--- Cut for Brevity Full Logs Attached ---
[OBSError.txt](https://github.com/obsproject/obs-studio/files/5765461/OBSError.txt)

**Comment by MMichael-S** [comment]
I encountered the same issue, and tried 26.1.2 and 26.1.1 are the same, but 26.1.0 is ok.

**Comment by PatTheMav** [comment]
Does this problem still occur with OBS 28.0.3?

**Comment by RytoEX** [comment]
We no longer support OBS Studio 26.1 or macOS 10.15. If this occurs with a current version of OBS Studio on macOS 11+, please open a new Issue.
