### ISSUE TITLE
Copied sources from a scene to a new scene get rearranged after paste

### ISSUE THREAD

**Issue by kutibotond** [obsproject/obs-studio#4016]
## Platform
Operating system and version: Windows 10 64-bit OS Version 20H2 Build 19042.685
OBS Studio version: 26.1.0

## Expected Behavior
Inside a scene where I have multiple individual sources and groups let's say I want to copy a selection from the middle of the list. 
If I click on one of them ...

![image](https://user-images.githubusercontent.com/4682426/103698982-e4683000-4faa-11eb-83fb-2a4909d1518e.png)

... then press Shift and down arrows until I get my desired selection ...

![image](https://user-images.githubusercontent.com/4682426/103699075-124d7480-4fab-11eb-9d95-7c29c30053a4.png)

... If I copy the selection and paste it to a new scene it works as expected, it retains the same order 

![image](https://user-images.githubusercontent.com/4682426/103699250-59d40080-4fab-11eb-839a-ff3638a028a7.png)

The problem, however, is that this won't be the same result if I do the same selection but with Shift + Up arrow, selecting upwards. Let me show you.

## Current Behavior

I click on a source from my initial scene  ....

![image](https://user-images.githubusercontent.com/4682426/103699725-0910d780-4fac-11eb-901d-d7c74ed3ed97.png)

... select the same items as in the example before ...

![image](https://user-images.githubusercontent.com/4682426/103699756-15953000-4fac-11eb-9da6-3069133d43d6.png)

... copy either by right clicking any of the selected items or CTRL + C and paste it in to the new scene. My result looks like this ...

![image](https://user-images.githubusercontent.com/4682426/103700523-4164e580-4fad-11eb-9ff2-4222075f7461.png)

From what I can tell the top and bottom sources from my initial selection get switched up .... But that's not all

Here's a different way of doing it 

Let's go back to the initial scene. Click on the bottom item that I want to include in my selection ...

![image](https://user-images.githubusercontent.com/4682426/103701531-d9170380-4fae-11eb-9657-8ca03832771f.png)

... hold down Shift, then click the top item of my wanted selection ....

![image](https://user-images.githubusercontent.com/4682426/103701596-f8159580-4fae-11eb-935c-c9ab766fa416.png)

... now let's go to the new scene and paste there ... 

![image](https://user-images.githubusercontent.com/4682426/103701887-327f3280-4faf-11eb-9651-b3b3b7369bf2.png)

this is a new variant ... it looks like the bottom source jumped to the top while the rest remained in order ...

## Steps to Reproduce
Simulate what I did above ...

## Additional information
This happens directly after first time when you try to copy and paste. 
If 
1. you succeed in reproducing the problem
2. then you delete those sources
3. go back to the current selection
4. copy again
5. paste again 

... the order will be right, So you have to deselect to be able to repeat the whole process of reproducing. 

I find that it doesn't matter what action you use for copy or what item of the selection you might right click.

Making the selection with a mouse from down upwards and including the bottom source in the selection, copy-pasting that will give the correct order with paste to the new scene.

**Comment by Fenrirthviti** [comment]
Please ensure you properly fill out the issue template.

**Comment by dodgepong** [comment]
It's implemented this way, but is this behavior _intended_ by this implementation, or was this consequence of the implementation an oversight? This behavior seems counter-intuitive enough that I might still consider this a bug -- granted, a bug that requires a nontrivial amount of development effort to fix.

That said, since this is a UX issue, I will defer to @Warchamp7.

**Comment by PatTheMav** [comment]
It would require quite a bit more code to make this operation consider the order of items in the list regardless of order of selection and also make the paste operation more complex, so I reckon it just wasn't considered.
