### ISSUE TITLE
Poor rendering of the statistics panel

### ISSUE THREAD

**Issue by toby3d** [obsproject/obs-studio#4017]
The docked statistics panel does not render well when it is included in the main window. As a separate popup or a individual dock-panel, the statistics are displayed and updated correctly.

## Platform
Operating system and version: `Linux 5.9.11-3-MANJARO x86_64 GNU/Linux`
OBS Studio version: `26.1.0.rc2.r2.g5f5b22004 (64 bit)`

## Expected Behavior
The docked statistics panel is displayed and updated in the OBS interface.

## Current Behavior
[![](http://i3.ytimg.com/vi/s_qk761Y_2c/hqdefault.jpg)](https://www.youtube.com/watch?v=s_qk761Y_2c)

## Steps to Reproduce
1. Show this panel by: View -> Dock-panels -> Statistics
2. Insert this panel in any place of OBS interface

## Additional information
Logs of recorded demonstration: https://obsproject.com/logs/vOPOkNxzwNP6G49V

**Comment by WizardCM** [comment]
We don't officially support anything other than Ubuntu, but I'm curious - what version of Qt is this built on?

**Comment by toby3d** [comment]
> We don't officially support anything other than Ubuntu, but I'm curious - what version of Qt is this built on?

This [package in AUR](https://aur.archlinux.org/packages/obs-studio-git) has only `qt5-x11extras` dependency. I have the `5.15.2-1` version of this package installed.

**Comment by kkartaltepe** [comment]
Your rendering already looks broken in this example. We have modified a lot of qt properties so please test this on one of the RCs and we can reopen if we can find it still happens.
