### ISSUE TITLE
only twitch chat dock showing up after transferring config to other pc

### ISSUE THREAD

**Issue by Juesto** [obsproject/obs-studio#4020]
i have connected my twitch account in obs on my computer then i've copied the configuration files to another computer with the same version of obs studio installed. when i select twitch, the only dock available is chat, not the rest

## Platform
Operating system and version: 6.1.7601
OBS Studio version: 26.1.0 64-bits windows

## Expected Behavior
all of the docks should be available

## Current Behavior
only chat dock is available

## Steps to Reproduce
1. connect twitch
2. close obs and transfer configuration to a different computer
3. start instance on new computer
4. behavior happens

**Comment by WizardCM** [comment]
How much of the configuration did you copy? Just scenes, or the whole AppData/obs-studio folder?

**Comment by Juesto** [comment]
> How much of the configuration did you copy? Just scenes, or the whole AppData/obs-studio folder?

everything but logs and machine specific stuff.

**Comment by RytoEX** [comment]
Please re-test this in OBS Studio 28.0.3 (or newer) and confirm if this is still an issue.

**Comment by Juesto** [comment]
> Please re-test this in OBS Studio 28.0.3 (or newer) and confirm if this is still an issue.

i will, i have forgotten my twitch password for the time being

**Comment by Juesto** [comment]
I've reproduced the issue on 28.1.1 by duplicating the profile and returning to it afterwards, 
original profile lost docks, duplicated profile is not connected to twitch

**Comment by Fenrirthviti** [comment]
Closing as stale. If this is still an issue please open a new issue with updated reproduction steps on the latest version of OBS.
