### ISSUE TITLE
OBS Crash streaming to ICECAST via webM format

### ISSUE THREAD

**Issue by lulou** [obsproject/obs-studio#4022]
## Platform
Unhandled exception: c0000005
Date/Time: 2021-01-06, 15:50:53
Fault address: 6638C733 (c:\lulu\bin\obs-studio-26.1-full-x64\bin\64bit\libvpx-1.dll)
libobs version: 26.1.0 (64-bit)
Windows version: 10.0 build 19042 (release: 2009; revision: 685; 64-bit)
CPU: AMD Ryzen 5 2400G with Radeon Vega Graphics    

## Expected Behavior
OBS would use ffmpeg to strem to icecast with webm format

## Current Behavior
Url to GIST: https://gist.github.com/lulou/4378f6434d91a8fd6967ddb2269682b3
OBS crashes after pressing the record button

## Steps to Reproduce
go to settings -> output -> recording
To reproduce set the recording option to userdefined (ffmpeg)
-> url icecast://user:pass@host/target
->container webm
-> videoencoder libvpx-v9
-> audioencoder libopus
apply the settings

hit record -> obs crashes with the above log

## Additional information
Note that using mpegts and libx264 with aac, streaming to icecast works (even thou the stream is unsupported by icecast and will not play in the browser, but using vlc it can be watched).

settings the encoder to libvpx does not work either, error message "Failed to open Video Codec: Invalid argument".
Note: vpx vp8 uses much less processor usage, wich somehow justifies the quality for me.

**Comment by Fenrirthviti** [comment]
Can you please edit this message to follow our template, and instead upload the crash log to a gist or paste? This issue report is difficult to parse as presented.

**Comment by lulou** [comment]
Done, sorry for the confusion.

**Comment by Fenrirthviti** [comment]
Thanks very much! Can you also provide a normal OBS log file to go along with the crash log? Might be some additional clues there. A few other questions as well:

- Has this been working, and recently stopped, or has this never worked?
- What exact settings are you using in custom FFmpeg output mode?

I suspect the issue here is that you're selecting an incompatible selection of options for the vpx encoder, which is causing it to crash. Custom FFmpeg output mode comes with 0 safety checks and no warranty, and is a "use at your own risk" option in OBS.

**Comment by Fasteroid** [comment]
Getting the same issue.
These settings result in a crash
![image](https://user-images.githubusercontent.com/29342750/127426821-dcc7a8ff-c45a-4fa9-a21e-82f81b236054.png)

**Comment by eebrains** [comment]
@lulou
Were you able to resolve the webm streaming to icecast?  I've encountered the same issue (under windows 11).
I'm guessing its related to the bundled ffmpeg, but no idea.

I have verified mpeg2ts streaming works well with libx264 / aac.  But like you, I would prefer native browser support.

Logfile:
```
Unhandled exception: c0000005
Date/Time: 2022-06-24, 10:58:47
Fault address: 6638C733 (c:\program files\obs-studio\bin\64bit\libvpx-1.dll)
libobs version: 27.2.4 (64-bit)
Windows version: 10.0 build 22000 (release: 2009; revision: 739; 64-bit)
CPU: AMD Ryzen 7 5800U with Radeon Graphics 

........
```
![image](https://user-images.githubusercontent.com/38725873/175576923-48303a36-68a5-48a0-b66d-5c37c48f387d.png)

Things I've tried:

- latest AMD drivers
- all color modes
- 
- removing all video media
- various encoder settings

**Comment by RytoEX** [comment]
We fixed some issues with libvpx in OBS Studio 28. Please re-test this in OBS Studio 28.0.3 (or newer) and confirm if this is still an issue.

**Comment by RytoEX** [comment]
After figuring out how to set up Icecast and how to stream to it with OBS, I cannot reproduce this in OBS Studio 29.0.0 Beta 1. I can successfully encode VP9 and output to a file or output to a URL to Icecast and subsequently view it in a browser.
