### ISSUE TITLE
OBS crashed when right button clicked

### ISSUE THREAD

**Issue by llbec** [obsproject/obs-studio#4023]
## Platform
Operating system and version: windows 7 64
OBS Studio version: git log dffa8221124106bc2a4c92e5f5d0fa21128a61f6

## Expected Behavior
---

## Current Behavior
crashed

## Steps to Reproduce
1. modify plugin CmakeLists.txt
[CMakeLists.txt](https://github.com/obsproject/obs-studio/files/5778967/CMakeLists.txt)
2. Visual Studio 2019 build Debug 64
3. add image source
4. right button clicked on the picture
5. mouse move on the menu
6. crash

[Crash 2021-01-06 23-17-03.txt](https://github.com/obsproject/obs-studio/files/5778945/Crash.2021-01-06.23-17-03.txt)

**Comment by RytoEX** [comment]
Please properly fill out the issue template and attach the crash log to the post instead of pasting the text into the post.

**Comment by llbec** [comment]
## Platform
Operating system and version: windows 7 64
OBS Studio version: git log dffa8221124106bc2a4c92e5f5d0fa21128a61f6

## Expected Behavior
---

## Current Behavior
crashed

## Steps to Reproduce
1. modify plugin CmakeLists.txt
[CMakeLists.txt](https://github.com/obsproject/obs-studio/files/5778967/CMakeLists.txt)
2. Visual Studio 2019 build Debug 64
3. add image source
4. right button clicked on the picture
5. mouse move on the menu
6. crash

[Crash 2021-01-06 23-17-03.txt](https://github.com/obsproject/obs-studio/files/5778945/Crash.2021-01-06.23-17-03.txt)

**Comment by Evernow** [comment]
Windows 7 is EOL. It is not supported by Microsoft or OBS.

https://obsproject.com/wiki/System-Requirements

Please [clean install Windows 10](https://old.reddit.com/r/24hoursupport/wiki/installingwindows) and see if the issue occurs.

**Comment by RytoEX** [comment]
This looks like a Qt crash of some kind. If you are still on Windows 7, please re-test in OBS Studio 27.2.4, which is the last version of OBS Studio that supports Windows 7. That said, we no longer provide support for OBS Studio on Windows 7, so I will be closing this.

If you are now on Windows 10 or 11, please re-test this in OBS Studio 28.0.3 (or newer) and confirm if this is still an issue.
