### ISSUE TITLE
Links with libpulse.so when -DDISABLE_PULSEAUDIO=TRUE

### ISSUE THREAD

**Issue by yurivict** [obsproject/obs-studio#4025]
## Platform
Operating system and version: FreeBSD 12.2
OBS Studio version: 26.1.0

## Expected Behavior
Not link with disabled libraries.

## Current Behavior
With these cmake arguments:
```
-DOBS_VERSION_OVERRIDE:STRING="26.1.0" -DDISABLE_JACK=TRUE -DDISABLE_PULSEAUDIO=TRUE -DENABLE_SNDIO=TRUE -DCMAKE_C_COMPILER:STRING="cc"  -DCMAKE_CXX_COMPILER:STRING="c++"  -DCMAKE_C_FLAGS:STRING="-O2 -pipe -fno-omit-frame-pointer  -D_WITH_GETLINE -fstack-protector-strong -fno-strict-aliasing "  -DCMAKE_C_FLAGS_DEBUG:STRING="-O2 -pipe -fno-omit-frame-pointer  -D_WITH_GETLINE -fstack-protector-strong -fno-strict-aliasing "  -DCMAKE_C_FLAGS_RELEASE:STRING="-O2 -pipe -fno-omit-frame-pointer  -D_WITH_GETLINE -fstack-protector-strong -fno-strict-aliasing "  -DCMAKE_CXX_FLAGS:STRING="-O2 -pipe -fno-omit-frame-pointer -D_WITH_GETLINE -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer  "  -DCMAKE_CXX_FLAGS_DEBUG:STRING="-O2 -pipe -fno-omit-frame-pointer -D_WITH_GETLINE -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer  "  -DCMAKE_CXX_FLAGS_RELEASE:STRING="-O2 -pipe -fno-omit-frame-pointer -D_WITH_GETLINE -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer  "  -DCMAKE_EXE_LINKER_FLAGS:STRING=" -fPIC -fstack-protector-strong "  -DCMAKE_MODULE_LINKER_FLAGS:STRING=" -fPIC -fstack-protector-strong "  -DCMAKE_SHARED_LINKER_FLAGS:STRING=" -fPIC -fstack-protector-strong "  -DCMAKE_INSTALL_PREFIX:PATH="/usr/local"  -DCMAKE_BUILD_TYPE:STRING="Release"  -DTHREADS_HAVE_PTHREAD_ARG:BOOL=YES  -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=YES  -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DUNIX_STRUCTURE:BOOL=ON -GNinja -DPython_ADDITIONAL_VERSIONS=3.7 -DBOOST_PYTHON_SUFFIX:STRING=37
```
it still links with libpulse.so:
```
====> Running Q/A tests (stage-qa)
Error: /usr/local/lib/libobs.so.0 is linked to /usr/local/lib/libpulse.so.0 from audio/pulseaudio but it is not declared as a dependency
Warning: you need LIB_DEPENDS+=libpulse.so:audio/pulseaudio
```

## Steps to Reproduce
obvious

**Comment by kkartaltepe** [comment]
libobs has a dependency on pulseaudio for audio monitoring functionality which is not implemented in the pulseaudio plugin (which is managed by `DISABLE_PULSEAUDIO`). It should probably also respect `DISABLE_PULSEAUDIO`.

**Comment by yurivict** [comment]
Shouldn't it be able to monitor using any currently enabled backend, vs. using PulseAudio regardless?

Instead of making monitoring to respect ```DISABLE_PULSEAUDIO```, shouldn't this function migrate into audio backend plugins?

**Comment by kkartaltepe** [comment]
pulseaudio,wasapi, and whatever mac uses are the only backends for monitoring. There is no plugin infrastructure for this functionality its written into the platform layer.

**Comment by duckinator** [comment]
Is there _any_ way to get around this? For example, some way to disable monitoring at build time?

Installing OBS currently actively breaks audio on my system, because just _installing_ pulseaudio on my system causes problems, but I can't install OBS without dragging in pulseaudio.

**Comment by Chiitoo** [comment]
I don't know about FreeBSD, but on Linux it is possible to build without PulseAudio installed (I use ALSA only), but I did now notice due to this issue that there is some automagic happening still if PulseAudio is installed at build-time (meaning OBS Studio breaks if PulseAudio is uninstalled afterwards, though I thought I had tested that before...).

**Comment by duckinator** [comment]
It turns out that on FreeBSD if you don't have pulseaudio installed, you can just install OBS from ports (which builds it from source) and it won't drag in pulseaudio. So that's the workaround for me specifically. :+1:

**Comment by yurivict** [comment]
> It turns out that on FreeBSD if you don't have pulseaudio installed, you can just install OBS from ports (as opposed to using pkg install obs-studio) and it won't drag in pulseaudio.

It is this way when the port option PULSEAUDIO is set to "OFF". But the "OFF" choice is marked as broken due to this very issue. So unfortunately this doesn't currently work.

**Comment by duckinator** [comment]
@yurivict what happened when I tried building the port is: if pulseaudio was installed, the build failed and mentioned this issue; if pulseaudio was _not_ installed, it built fine.

(I still can't convince it to cooperate, but I'm unsure whether that's a bug or something wrong with my setup.)

**Comment by hunteroone** [comment]
Getting led here when attempting to build the obs-studio port (on FreeBSD).

**Comment by duckinator** [comment]
I just realized I left out a really important detail before. Actually, it was the detail that prompted me to leave a comment at all, whoops.

If you're trying to build without pulse _and do not have pulse installed_, you can simply add a `#` before this line:

```
#PULSEAUDIO_BROKEN_OFF=    https://github.com/obsproject/obs-studio/issues/4025
```

For me, this works without issue. But if you have pulseaudio installed, **even if you don't use it**, it'll break.

**Comment by yurivict** [comment]
Yes, the PULSEAUDIO option can't currently be cleanly disabled in the FreeBSD port pending fix of this issue by the upstream.

**Comment by yurivict** [comment]
This is still a problem in the version 28.1.2

Could you please reopen it?

**Comment by Fenrirthviti** [comment]
Since this issue is quite old and has a PR to fix it that's been merged for over a year, please open a new issue with details on the problem and any errors or steps to reproduce.
