### ISSUE TITLE
FYI - 26.1.1 - Crashed on startup Mac OS 11.2 - Reverted back to 26.1 working 

### ISSUE THREAD

**Issue by ParzivalWins** [obsproject/obs-studio#4027]
## Platform

Operating system and version:
OBS Studio version: 26.1.1 

## Steps to Reproduce

1.
![Crash](https://user-images.githubusercontent.com/25649258/103826738-3d2bdd00-502c-11eb-9440-a33b87284c69.png)

2.
3.
4.

**Comment by adarhef** [comment]
Same here. Still happens after restart. 26.1 was fine. Running on macOS 11.1 Big Sur.

**Comment by jp9000** [comment]
Reverted the update for now, seems we need to implement a test for this so this doesn't happen in the future. Update will be a bit delayed until it's solved.

**Comment by jjdeprisco** [comment]
I'm on OSX 13.6. I just tried the 26.1.1 release which was supposed to fix the Mac crash on OBS startup. Still have the same issue.

"...please ensure all third party plugins such as obs-websocket or StreamFX are up to date."

I even pulled out all of my plugins. I do not use obs-websocket or StreamFX.

**Comment by Gol-D-Ace** [comment]
Version:               26.1.0 (26.1.0)
So you didn't actually run 26.1.1 there.

The update got also removed because of other issues.

**Comment by jjdeprisco** [comment]
So that means the update was bad because something appeared to update and
won't run. The update process shouldn't offer me 26.1.1 if it isn't even
available.

Since it broke my installation, the update obviously did something. I've
sent in all my logs.

Let me know when it is officially fixed and available to try.

**Comment by jp9000** [comment]
The mac updater notes are stuck on 26.1.1, but the version on the mac updater is 26.1.0.

**Comment by WizardCM** [comment]
This was fixed in 26.1.2. You may need to manually redownload OBS if you updated to 26.1.1 in the short time it was up & can't launch, otherwise use the built-in updater.
