### ISSUE TITLE
UI - duplicating scenes doesn't duplicate their color states.

### ISSUE THREAD

**Issue by lindenkron** [obsproject/obs-studio#4029]
## Platform

Operating system and version: Windows 10, 64 bit Home Edition 10.0.18363 Build 18363
OBS Studio version: 26.1.1 (64 bit)

## Expected Behavior
Duplicating a scene should duplicate all states. 

## Current Behavior
Doesn't duplicate color state  of a source.

## Steps to Reproduce
1. Create Scene.
2. Add Source.
3. Change Source to be a color.
4. Duplicate Scene with the source in it.
5. New scene has no colors.

## Additional information
Originally it didn't duplicate locked state, and while annoying I assumed purposefully. Now that that's been fixed, I'm guessing the color states should also be duplicated.

**Comment by WizardCM** [comment]
I previously asked about this, and it's currently by design. Colour state is part of private data, which is not copied.
