### ISSUE TITLE
Replay Buffer Doesn't Save Last Moment. Instead, Goes Back More than It Needs

### ISSUE THREAD

**Issue by EladKarni** [obsproject/obs-studio#4032]
I can't reproduce, but this 100% a bug!

So I clicked save replay buffer, but instead of saving the last 4 minutes, it saved 4 minutes from 5min ago :frowning: so I didn't actually save the moment I wanted....

Here is a video showing the issue.

I ended the game, and saved the replay buffer, but instead of having that last moment of the Overwatch game, it has a random moment within the game.

## Platform

Operating system and version: Windows 10 Pro - 10.0.19041
OBS Studio version: 26.1.1

## Expected Behavior

It should record the last 4 minutes, not a 4 minutes starting at 5 minutes ago.

## Current Behavior

When I save a replay buffer, instead of saving the last 4 minutes. It goes back 5 or 6 minutes, and saves the last 4 minutes then. Meaning that if something happened in the last minute, the replay buffer doesn't contain it.

## Steps to Reproduce

N/A

## Additional information

Here is a link to a video of the end of the game, and how a replay buffer doesn't contain the moment it should.
https://youtu.be/ZNi1WLHg4F4

**Comment by EladKarni** [comment]
I didn't restart OBS, nor did I change anything, but suddenly it works fine. I'm at a totally loss!

**Comment by EladKarni** [comment]
I made a plugin to tell me if the replay buffer was successfully saved, but now I can't even count on it to work...

**Comment by EladKarni** [comment]
Here are my logs
[2021-01-07 02-05-44.txt](https://github.com/obsproject/obs-studio/files/5783539/2021-01-07.02-05-44.txt)

**Comment by Fenrirthviti** [comment]
Closing as stale, if this is still an issue in current OBS versions, please make a new report with full reproduction steps.
