### ISSUE TITLE
OBS Crash on Scene remove

### ISSUE THREAD

**Issue by BluePeer** [obsproject/obs-studio#4035]
It is not very special but
if i remove a scene and this scene is active
OBS crash
bypass is easy by activate another scene (default)
but idk can't remember that his is a issue in old versions (feels new for me)

**Comment by WizardCM** [comment]
Please fill in the issue template and include the crash report.

**Comment by BluePeer** [comment]
sorry i have no know about how this features here work or need to be used in the style 
[Crash 2021-01-08 12-33-46.txt](https://github.com/obsproject/obs-studio/files/5786923/Crash.2021-01-08.12-33-46.txt)
that is a crashlog

to reproduce
add a scene
be sure it is active
then right click on the scene and select remove (crash)
remove the scene mit the - button below scene list (no crash)

**Comment by notr1ch** [comment]
This crash is in a 3rd party plugin, obs-transition-matrix.

**Comment by BluePeer** [comment]
True? yeah i seen this too
you not think this is relevant for obs that 2 "self" Operations
one crash and another not?

sorry if my intension for the report is not "default"
but if i write a Programm and i add "same" function avaible on 2 Positions
and there have Different Effects, i take a look on it by "not good for me" if i have 2 Operations make the same but work other

but yeah close by 3rd party -.-
