### ISSUE TITLE
Zoom crashes when recording with OBS - PopOS

### ISSUE THREAD

**Issue by lucasrpmv** [obsproject/obs-studio#4036]
## Platform

Operating system and version: Pop!_OS 20.10 x86_64 
OBS Studio version: 26.1.1 64 bits

## Expected Behavior

When I am at a meeting in Zoom and start recording with OBS Studio it kind of crashes the video conference.
My perception of what is happening its that Zoom slowly start loosing video and then audio, then it just look like there is no internet, its something like internet its fading away because of OBS. After it completely stops I try to open any webpage on firefox with no success, like there is no internet. My solution is to restart the computer.

## Steps to Reproduce

1. Join a Zoom meeting.
2. Start recording the Zoom window with audio output from the computer.
3. See how slowly the Zoom meeting lose connection.
4.

## Additional information

This did not happen one month ago having the same machine and same system.

**Comment by notr1ch** [comment]
This sounds like a PC problem and not related to OBS. Pop! OS is not a supported platform in any case. You may have better luck using the forum at https://obsproject.com/forum/list/linux-support.34/.
