### ISSUE TITLE
OBS does not work on Mac OSX 10.13.6

### ISSUE THREAD

**Issue by FrancescoCaltabiano** [obsproject/obs-studio#4038]
Today I opened OBS and the program made me do the update, after this every time I try to open OBS it doesn't open saying that there was an unexpected closure of OBS

**Comment by RytoEX** [comment]
Please follow the issue template when opening issues on GitHub.

**Comment by notr1ch** [comment]
Please use the forums or Discord for support, this is not a valid issue.
