### ISSUE TITLE
Spaces wrong in pop-up window

### ISSUE THREAD

**Issue by gxalpha** [obsproject/obs-studio#4041]
## Platform

Operating system and version: macOS 11.1 (20C69)
OBS Studio version: 26.1.0

## Expected Behavior

The text should appear with correct spacings after periods.

## Current Behavior

The text, at first glance, appears to have no spaces at all after periods (picture 1). Selecting the text shows that there seems to indeed be multiple characters, but stacked over it each other (It's hard to explain, maybe picture 2 can provide an explanation).

## Steps to Reproduce

1. Start an output, in my case virtual camera
2. Click on "Quit" / "Beenden" in the bottom right
3. The window will pop up, with the wrong spacings (see below)

## Additional information

I obviously thought at first that this would be an issue with the actual strings, but checking on crowdin it seems correct. https://crowdin.com/translate/obs-studio/29/en-de#2260 (link to german string)

Picture 1:
<img width="420" alt="Bildschirmfoto 2021-01-09 um 00 04 55" src="https://user-images.githubusercontent.com/59806498/104074436-6ad17b80-5210-11eb-884d-7db9d2ae7e47.png">
Picture 2:
<img width="420" alt="Bildschirmfoto 2021-01-09 um 00 05 32" src="https://user-images.githubusercontent.com/59806498/104074441-6efd9900-5210-11eb-93b9-05e57ff30d6b.png">
Seems to happen in all languages:
<img width="420" alt="Screenshot 2021-01-09 at 00 28 03" src="https://user-images.githubusercontent.com/59806498/104074934-b7698680-5211-11eb-967d-fdd003b0e03d.png">

**Comment by WizardCM** [comment]
Is the issue only with this specific popup?

**Comment by gxalpha** [comment]
<img width="420" alt="Bildschirmfoto 2021-01-09 um 00 37 41" src="https://user-images.githubusercontent.com/59806498/104075409-006e0a80-5213-11eb-8a53-4822bc2efe94.png">
<img width="420" alt="Bildschirmfoto 2021-01-09 um 00 38 00" src="https://user-images.githubusercontent.com/59806498/104075408-ff3cdd80-5212-11eb-82bc-2cc7d9fdfc2f.png">

Looks like every popup

**Comment by WizardCM** [comment]
Could not reproduce on 10.14.

![image](https://user-images.githubusercontent.com/941350/104828722-741db080-58c0-11eb-90c4-1dc92243de96.png)

I wonder if it's caused by the system locale?

**Comment by gxalpha** [comment]
So you mean by me having macOS in German?

When I set it to English and restarted OBS, it was still there (3rd screenshot in the original post)

**Comment by WizardCM** [comment]
Yeah, that's my final guess.

**Comment by gxalpha** [comment]
Just for tracking, this looks like [QTBUG-88495](https://bugreports.qt.io/browse/QTBUG-88495), and should be fixed in QT 5.15.3 (commercial only) and some version of QT6.
