### ISSUE TITLE
MacOS Big Sur - Can't record window in full screen or separate desktops.

### ISSUE THREAD

**Issue by landevan7** [obsproject/obs-studio#4043]
When using OBS on macOS Big Sur, I am unable to capture any windows that live in desktops other than the one OBS is in. Even full screen apps that take up their own desktop aren't seen by OBS.

**Comment by WizardCM** [comment]
This is not a bug but a limitation of macOS capture APIs.

**Comment by Fenrirthviti** [comment]
Please use the forums or Discord for support. If you were trying to make an actual bug report, please fill out the template properly and this can be reopened.
