### ISSUE TITLE
Screenshot feature stoppes/not working

### ISSUE THREAD

**Issue by Kashimus** [obsproject/obs-studio#4048]
The new screenshot feauture is not working with the new file formatting options.
i mean when i change the file name formatting in the advanced menu to " \ %CCYY-%MM \ %DD-%A \ %CCYY-%MM-%DD-%a-%hh-%mm-%ss" it will not save any screenshots.(so it will make a folder with the year and month date,and organize a little bit better) but when i change it back to the "old"  %CCYY-%MM%DD-%A%CCYY-%MM-%DD-%a-%hh-%mm-%ss 
it works 
please see linked videos for clarification

## Platform

Operating system and version: win 7 64bit Ultimate
OBS Studio version: 26.1.1

## Expected Behavior

Taking screenshot with hot key or by menu option
## Current Behavior
Not taking/making screenshot

## Steps to Reproduce

The output saving location is 
![bandicam 2021-01-11 15-35-46-090](https://user-images.githubusercontent.com/77279779/104195321-61b3fa80-541a-11eb-81f3-1554b10ba546.png)
1.Change the file formatting option in advanced to a "custom" like  \ %CCYY-%MM \ %DD-%A \ %CCYY-%MM-%DD-%a-%hh-%mm-%ss  
![bandicam 2021-01-11 15-27-38-847](https://user-images.githubusercontent.com/77279779/104194471-4b596f00-5419-11eb-9aab-a33ef5865e1a.png)
This will make the folder "2021-01" and in that another with the date and name of that day
![bandicam 2021-01-11 15-32-47-931](https://user-images.githubusercontent.com/77279779/104195505-9cb62e00-541a-11eb-886d-f1a2c71f9ace.png)
![bandicam 2021-01-11 15-39-44-274](https://user-images.githubusercontent.com/77279779/104195852-08989680-541b-11eb-82eb-250fc4b64ba4.png)
2.Try to take screenshots by menu or by the hot key (see video below)
3.Check if it works or not
4.Change the file name formatting back to the "original" with out the specific formatting (%CCYY-%MM%DD-%A%CCYY-%MM-%DD-%a-%hh-%mm-%ss")
![bandicam 2021-01-11 15-27-48-124](https://user-images.githubusercontent.com/77279779/104194504-54e2d700-5419-11eb-85fc-3aadd1006688.png)
This will just make a new file in the obs folder as seen and screenshots aswell
![bandicam 2021-01-11 15-32-47-931](https://user-images.githubusercontent.com/77279779/104195478-9758e380-541a-11eb-916e-155fff6745fc.png)
5.Video link not working : https://youtu.be/KndUFqSpqQc
6.Video link working: https://youtu.be/2xOIEYiyQ3w
7.check linked videos for "better" description
## Additional information
The screenshot folder in the obs folder contains screenshot's made by 3rd party program.in the working video link you can see it works as intended when there is no special formatting in the file formatting.
The new file formatting in advanced is not supporting the screenshot feature or the feauture cant handle the formatting i dont know iam not a programmer.

**Comment by kkartaltepe** [comment]
your format string for old and new are identical.

**Comment by Kashimus** [comment]
the "\" sigh is not visible in the video you can see the difference but will make screenshots

**Comment by WizardCM** [comment]
Don't put a \ at the very start of the string.

**Comment by Kashimus** [comment]
> Don't put a \ at the very start of the format string, that should solve your issue.

Thank you now it works and makes a folder called screenshot and the same dating format, i would never though about that 
![bandicam 2021-01-11 23-04-32-534](https://user-images.githubusercontent.com/77279779/104243766-ff2e1f00-5458-11eb-87f4-c6ac2ab1be42.png)
