### ISSUE TITLE
Rename OBS Virtual Cam?

### ISSUE THREAD

**Issue by Amw94** [obsproject/obs-studio#4053]
How do I rename the OBS Virtual Cam?

**Comment by WizardCM** [comment]
The Issues page is not for support requests.

Additionally, we have no plans for adding the ability to rename the virtual camera.

**Comment by w1redch4d** [comment]
Hi, will the maintainers mind if i create a PR for the feature?

**Comment by Fenrirthviti** [comment]
We are not currently interested in supporting this feature. There have been no proposed legitimate use cases for needing to change the name.
