### ISSUE TITLE
FFmpeg is out of date (4.1.git) and missing DASH options

### ISSUE THREAD

**Issue by WinterPhoenix** [obsproject/obs-studio#4064]
## Platform
Operating system and version: Windows 10 20H2 (OS Build 19042.685)
OBS Studio version: 26.1.1

## Expected Behavior
Users should be able to use the current documented [FFmpeg 4.3.x DASH options](https://ffmpeg.org/ffmpeg-formats.html#dash-2) `ldash` and `http_opts` in OBS > Settings > Output > Recording >Advanced > Custom Output (FFmpeg) > Muxer Settings.

## Current Behavior
Due to the FFmpeg version in OBS being 4.1.git circa June 2019, those options are missing and the log outputs this information:
```
23:02:31.903: Using muxer settings: 
23:02:31.903:     streaming=1
23:02:31.903:     ldash=1
23:02:31.903:     http_opts=method=GET
23:02:31.905: Invalid muxer settings: 
23:02:31.905:     ldash=1
23:02:31.905:     http_opts=method=GET
```

## Steps to Reproduce
1. Set these Advanced Recording settings, with whichever URL you wish:
![image](https://user-images.githubusercontent.com/2799393/104548482-e8c1c800-55fe-11eb-84f4-cff357ff9a88.png)
3. View the Current OBS Log to see the above log output, confirming the `ldash` and `http_opts` options aren't being used

## Additional information
This appears to be a relatively drop-in upgrade. Replacing the existing DLLs in OBS with up to date versions from the FFmpeg 4.3.1 (the latest stable release) "shared" builds works seemingly without a hitch, except that OBS's FFmpeg build doesn't include `libpostproc`.

Also, taking the Existing (Windows) Dependencies at https://obsproject.com/downloads/dependencies2019.zip, updating FFmpeg's DLLs/Libs/Includes in it to 4.3.1, and compiling OBS with it, seems to work as well.

Please let me know if I can help test or anything, I'd be glad to do all that I can to help this along!

**Comment by Fenrirthviti** [comment]
We had planned on updating ffmpeg for 26.1, but issues with certain functions (notably the SRT output) prevented us from updating. We are still planning to update with the next major release, barring any further roadbumps.

**Comment by WinterPhoenix** [comment]
That’s wonderful news! I’m glad to hear it’s on the roadmap in the short term.

**Comment by Fenrirthviti** [comment]
Here is the bug report we submitted to FFmpeg, for tracking: https://trac.ffmpeg.org/ticket/9010

**Comment by cs9kc** [comment]
> 
> 
> We had planned on updating ffmpeg for 26.1, but issues with certain functions (notably the ~SRT~ HLS output) prevented us from updating. We are still planning to update with the next major release, barring any further roadbumps.

Hello!  I'm glad I dug around through ffmpeg and OBS's githubs before opening a new ticket.  It's good to hear that the included ffmpeg version should be updated in the next OBS Studio version!

I am -quite- looking forward to the update!  The ffmpeg version included in OBS Studio 26.1.1 and earlier includes several AMF bugs that have been fixed in recent _years_, and even still includes an ffmpeg bug I personally had fixed (h265 b-frame reference PTS/DTS error) in early 2020.  

Keep being awesome, yall!  Carry on.

**Comment by WinterPhoenix** [comment]
Hi maintainers; could we get an update on this by chance? Are we waiting for the FFmpeg team?

Thanks!

**Comment by RytoEX** [comment]
> 
> 
> Hi maintainers; could we get an update on this by chance? Are we waiting for the FFmpeg team?
> 
> Thanks!

No change from the previous update:
> We had planned on updating ffmpeg for 26.1, but issues with certain functions (notably the ~SRT~ HLS output) prevented us from updating. We are still planning to update with the next major release, barring any further roadbumps.

> Here is the bug report we submitted to FFmpeg, for tracking: https://trac.ffmpeg.org/ticket/9010

**Comment by RytoEX** [comment]
OBS Studio 27.2 will be shipping with FFmpeg 4.4.1.  OBS Studio 27.2 is currently in beta and can be downloaded from the [releases](https://github.com/obsproject/obs-studio/releases) list.
