### ISSUE TITLE
Compile time error on building OBS-Studio on Windows 10

### ISSUE THREAD

**Issue by alokmahor** [obsproject/obs-studio#4065]
## Platform

Operating system and version: Windows 10, Version 2004 (OS Build 19041.685)
OBS Studio version: Latest Master pull 

## Expected Behavior

By following https://github.com/obsproject/obs-studio/wiki/Install-Instructions#windows-build-directions I should be able to build OBS-Studio on windows 10

## Current Behavior

While building on Visual Studio I am getting these errors

1. Error   C2039   'IsCursorCaptureEnabled': is not a member of 'winrt::Windows::Graphics::Capture::GraphicsCaptureSession'    libobs-winrt    C:\Users\alokm\obs-studio\libobs-winrt\winrt-capture.cpp    290 
2. Error   C2039   'IsCursorCaptureEnabled': is not a member of 'winrt::Windows::Graphics::Capture::GraphicsCaptureSession'    libobs-winrt    C:\Users\alokm\obs-studio\libobs-winrt\winrt-capture.cpp    372
3. Error   C2039   'IsCursorCaptureEnabled': is not a member of 'winrt::Windows::Graphics::Capture::GraphicsCaptureSession'    libobs-winrt    C:\Users\alokm\obs-studio\libobs-winrt\winrt-capture.cpp    473 

## Steps to Reproduce

1. Get clone of repo on windows 10
2. Follow build instructions given at https://github.com/obsproject/obs-studio/wiki/Install-Instructions#windows-build-directions
3. Build project in Visual studio

**Comment by henke37** [comment]
The wrong Windows SDK was used. Remove any obsolete versions you have and ensure that you have the latest one installed.

**Comment by WizardCM** [comment]
You need the 19041 or above Windows SDK.
