### ISSUE TITLE
Cannot select video capture device when it has moved ports but has the same name

### ISSUE THREAD

**Issue by notr1ch** [obsproject/obs-studio#4066]
## Platform

Operating system and version: Windows 10 20H2
OBS Studio version: 26.1.1

## Expected Behavior
When a device has moved and becomes available under a new path, the user should be able to select the new device (or more ideally, OBS should detect this situation and update it automatically where possible) without having to select an intermediate device first.

## Current Behavior
Selecting the "new" capture device from the properties window of the existing source does not do anything.

## Steps to Reproduce
1. Move a device to a new port such that the device path changes but the name does not.
2. Open video capture device properties.
3. Observe that there are now two entries (eg Logitech BRIO) in the list. The one representing the "old" device with the invalid path is grayed out and unselectable.
4. Select the new device with the same name (eg the white, selectable Logitech BRIO) that is present in the list.
5. OBS fails to initialize the new device.

https://user-images.githubusercontent.com/876345/104605649-0b93c100-567f-11eb-8a01-955f0201e8d7.mp4

## Additional information
Switching to an intermediate device (if available) and then going back to the original device name works around the issue (the grayed out device is removed). OBS is presumably getting confused by the presence of two devices with the same name in the list.

**Comment by Fenrirthviti** [comment]
Closing as stale. If this is still an issue please open a new issue with updated reproduction steps on the latest version of OBS.
