### ISSUE TITLE
Unable to game capture when OBS is started after the target not before

### ISSUE THREAD

**Issue by Juesto** [obsproject/obs-studio#4068]
I've verified for possible conflicts and it still happens.
I have UAC turned off so there shouldn't be any elevation issues.
error 57 is "parameter incorrect" apparently

## Platform
Operating system and version: 6.1.7601
OBS Studio version: 26.1.1 64-bits windows

## Expected Behavior
game capture should activate successfully

## Current Behavior
no capture happens at all and log shows following error: `is_app GetTokenInformation failed: 0x00000057` then stops capturing, see below

## Steps to Reproduce
1. Start game to capture
2. Start OBS
3. Attempt to capture
4. restart game without closing obs
5. capture works

## Additional information
example log with verbose and unfiltered enabled (which really doesn't make much difference)
```
15:57:33.051: [game-capture: 'Game Capture'] Activate hotkey pressed
15:57:33.061: is_app GetTokenInformation failed: 0x00000057
15:57:33.061: [game-capture: 'Game Capture'] attempting to hook process: Control_DX11.exe
15:57:33.063: is_app GetTokenInformation failed: 0x00000057
15:57:33.064: [game-capture: 'Game Capture'] using helper (compatibility hook)
15:57:33.190: [game-capture: 'Game Capture'] hook not loaded yet, retrying..
15:57:34.074: is_app GetTokenInformation failed: 0x00000057
15:57:34.074: [game-capture: 'Game Capture'] attempting to hook process: Control_DX11.exe
15:57:34.076: is_app GetTokenInformation failed: 0x00000057
15:57:34.076: [game-capture: 'Game Capture'] using helper (compatibility hook)
15:57:35.087: is_app GetTokenInformation failed: 0x00000057
15:57:35.087: [game-capture: 'Game Capture'] attempting to hook process: Control_DX11.exe
15:57:35.089: is_app GetTokenInformation failed: 0x00000057
15:57:35.089: [game-capture: 'Game Capture'] existing hook found, signaling process: (null)
15:57:35.090: [game-capture: 'Game Capture'] map id: CaptureHook_HookInfo21624
15:57:38.181: [game-capture: 'Game Capture'] capture stopped
```
```
15:58:25.171: [game-capture: 'Game Capture'] Activate hotkey pressed
15:58:25.181: is_app GetTokenInformation failed: 0x00000057
15:58:25.181: [game-capture: 'Game Capture'] attempting to hook process: Control_DX11.exe
15:58:25.183: is_app GetTokenInformation failed: 0x00000057
15:58:25.183: [game-capture: 'Game Capture'] existing hook found, signaling process: Control_DX11.exe
15:58:25.183: [game-capture: 'Game Capture'] map id: CaptureHook_HookInfo21624
15:58:25.194: [game-capture: 'Game Capture'] hook stop signal received
15:58:25.194: [game-capture: 'Game Capture'] capture stopped
15:58:27.018: [game-capture: 'Game Capture'] Deactivate hotkey pressed
```

**Comment by Fenrirthviti** [comment]
Can you provide the whole log file please? Is this replicated in every game, or just with Control? I am not able to replicate this with several DX11 games on my end, they all capture just fine, but I don't own Control to test against directly.

**Comment by Juesto** [comment]
> Can you provide the whole log file please? Is this replicated in every game, or just with Control? I am not able to replicate this with several DX11 games on my end, they all capture just fine, but I don't own Control to test against directly.

I've not been able to see anything else relevant. the snippet above is everything that's there related to game capture.

im scratching my head with vaguely remembering having the same issue with life is strange 2. 

ill try a bit and get back to you

**Comment by Fenrirthviti** [comment]
Logs contain much information about the configuration that OBS is running in. The information may not seem important to you, but it is important to us to be able to properly troubleshoot and understand what the issue might be. Can you please provide the whole log so we can examine it?

**Comment by Juesto** [comment]
> Logs contain much information about the configuration that OBS is running in. The information may not seem important to you, but it is important to us to be able to properly troubleshoot and understand what the issue might be. Can you please provide the whole log so we can examine it?

Okay, i'll have a look. i understand the importance

**Comment by Juesto** [comment]
Sorry @Fenrirthviti I saw the log and there's absolutely nothing. there's no magic.

**Comment by Fenrirthviti** [comment]
Sorry, I think you're misunderstanding why I'm asking for a log. I'm not looking for an error message, I need to see the whole log as it contains setup and configuration information on how OBS is running that might explain why it is failing to capture. Without the full log file, troubleshooting is much, much more difficult. Feel free to scan the log for any personal information (there should not be any, except maybe file paths for local media) and remove it, but we really need the entire log file.

**Comment by Juesto** [comment]
99% of the log is unrelated stuff.
All I got relating to game capture is what i posted, even if i used the parameters to make the logs more verbose which only increases verbosity in areas that aren't the interest.
I can auto-troubleshoot with some directions. sorry, please and thanks.

**Comment by energizerfellow** [comment]
To put is more succinctly, there's no more support that we can provide without the original OBS log in its entirety.

**Comment by Fenrirthviti** [comment]
If you are unwilling to provide the log file, there is nothing else we can do. I've tested and everything is working on my end. Refusal to provide the log, my inability to replicate, and the additional fact that don't really spend a lot of time on Windows 7 issues anymore either means I am going to close this issue. If you change your mind and are willing to provide the information we are requesting, I will consider reopening.

**Comment by Juesto** [comment]
> If you are unwilling to provide the log file, there is nothing else we can do. I've tested and everything is working on my end. Refusal to provide the log, my inability to replicate, and the additional fact that don't really spend a lot of time on Windows 7 issues anymore either means I am going to close this issue. If you change your mind and are willing to provide the information we are requesting, I will consider reopening.

This is ridiculous.
If you don't like providing support for windows 7 then why not straight up close it for that reason or leave it open for someone else to take in?
here's the log, 
[2021-01-14 15-56-11.txt](https://github.com/obsproject/obs-studio/files/5825453/2021-01-14.15-56-11.txt)
Happy @Fenrirthviti ?
