### ISSUE TITLE
Virtual webcam feature not available after building OBS-Studio from latest source code on Windows 10

### ISSUE THREAD

**Issue by alokmahor** [obsproject/obs-studio#4071]
## Platform

Operating system and version: Windows 10, Version 2004 (OS Build 19041.685)
OBS Studio version: Latest Master pull

## Expected Behavior

I should be able to see button to enable virtual webcam at right bottom menu

## Current Behavior

After building from latest source code I am not able to see button to enable virtual webcam at right bottom menu. Here is image link https://i.stack.imgur.com/Vr5aQ.png 

## Steps to Reproduce

1. Get clone of repo on windows 10
2. Follow build instructions given at https://github.com/obsproject/obs-studio/wiki/Install-Instructions#windows-build-directions
3. Build project in Visual studio 2019

**Comment by WizardCM** [comment]
The process of building OBS does not register the virtual camera. That is either done by the installer, via the `virtualcam-install.bat` script (which is generated at build time), or manually using `regserv`. Make sure you have the `VIRTUALCAM_GUID` CMake flag set with a valid GUID.

**Comment by Fenrirthviti** [comment]
As a side note, this is missing from current documentation, and I think this should be kept open until someone updates documentation to reflect proper steps to building with virtual camera support.

**Comment by alokmahor** [comment]
Yes this should keep open as build from source code on MacOS is giving this feature enabled by default. So there should be same behavior on Windows too.

**Comment by dodgepong** [comment]
Not really. The virtual cameras on each platform work very differently, and based on how they work it doesn't really make sense for the Windows version to behave the same way as the Mac version. I'm not even certain if it's possible to make it work the same. In any case, I'm not really a fan of the way it gets installed on Mac, but it's the least-bad option we could come up with for the time being.

**Comment by hollowaykeanho** [comment]
Able to replicate this when building source from Debian 10. I'm tracking this issue on my build repository here:
https://gitlab.com/holloway/obsProfile/-/issues/1

Exactly how to build virtual camera on Linux again? Been digging through the repo for quite some times and with no avail.

**Comment by alokmahor** [comment]
> The process of building OBS does not register the virtual camera. That is either done by the installer, via the `virtualcam-install.bat` script (which is generated at build time), or manually using `regserv`. Make sure you have the `VIRTUALCAM_GUID` CMake flag set with a valid GUID.

Could you please tell me exact steps to get virtual camera working after building from latest code?

**Comment by hollowaykeanho** [comment]
Update: I'm longer seeing the issue with missing virtual camera button upon the latest build from source dated to master branch 81a89e6) on Debian Buster.

**Comment by RytoEX** [comment]
I have updated the build instructions for Windows with the following:
> If you want to use the Virtual Camera from this build, you will need to run its install script.  If you already have a standard OBS Studio installation, you will need to uninstall its Virtual Camera first.
> 
>    To uninstall an OBS Virtual Camera:
>    1. Close any applications that were using the OBS Virtual Camera.
>    2. In the obs-studio installation directory, run `data\obs-plugins\win-dshow\virtualcam-uninstall.bat` as administrator.
>    
>    To install an OBS Virtual Camera:
>    1. In the obs-studio installation directory (for Visual Studio builds, this is '[build dir]/rundir/[build type]'), run `data\obs-plugins\win-dshow\virtualcam-install.bat` as administrator.
>
>    Don't forget to uninstall your build's virtual camera before cleaning/deleting your build files.

With this addition, I believe this can be closed.

As a reminder, the build instructions are open to edits from anyone.  Anyone is welcome to correct the build instructions.
