### ISSUE TITLE
Blackmagic Intensity Pro 4K Purple since 26.1

### ISSUE THREAD

**Issue by sangoku116** [obsproject/obs-studio#4072]
## Platform

Operating system and version: Arch Linux Kernel 5.10.7-zen1-1-zen
OBS Studio version: 26.1.0-2

## Expected Behavior
The image coming from the capture card should be displaying properly with the proper colours just like mediaexpress(blackmagic software) and as it was on versions prior to 26.1.

## Current Behavior
The image is purple, doubled and displayed on half the preview. 

## Steps to Reproduce
1. Launch OBS-Studio
2. Add Blackmagic Device
3. Configure the resolution, framerate, colours appropriately for the console in use. 
4. Enable preview or project the source
Screenshot from obs 26.1:
![Screenshot_2021-01-14_23-58-42](https://user-images.githubusercontent.com/18174977/104683986-07d75d00-56c6-11eb-90e0-119ec429c51d.png)
Screenshot from mediaxpress:
![Screenshot_2021-01-15_00-14-03](https://user-images.githubusercontent.com/18174977/104684239-99df6580-56c6-11eb-86b0-c90c60ca724c.png)

**Comment by WizardCM** [comment]
Update to OBS 26.1.1, it should be fixed there.

**Comment by sangoku116** [comment]
> Update to OBS 26.1.1, it should be fixed there.

I will install obs-studio-git from the AUR and give it a shot as the package in the official repos is at version 26.0.1-2.

**Comment by sangoku116** [comment]
Fixed by switching to the ```obs-stuio-git``` package in the AUR as the one in the repo has been flagged out of date since January 6 and this issue has been fixed.
