### ISSUE TITLE
obs_source_create doesn't make names unique despite what's written in the documentation

### ISSUE THREAD

**Issue by adriansuwala** [obsproject/obs-studio#4077]
## Platform

Operating system and version: Windows 10: Build 19042, release: 2009, revision: 685, 64bit
OBS Studio version: 26.1.1

## Expected Behavior

Second source's name is made unique as described in the documentation (https://obsproject.com/docs/reference-sources.html#c.obs_source_create)

## Current Behavior

Name of the second source is not changed, there are multiple sources with the same name.

## Steps to Reproduce

1. Save this code as a Lua script and load it.
```lua
obs = obslua

function script_properties()
    properties = obs.obs_properties_create()
    obs.obs_properties_add_button(properties, "test", "Test", test)
    return properties
end

function test(properties, property)
    local s = obs.obs_scene_from_source(obs.obs_frontend_get_current_scene())

    local t = obs.obs_source_create("color_source", "test", nil, nil)
    obs.obs_scene_add(s, t)
    obs.obs_source_release(t)

    t = obs.obs_source_create("image_source", "test", nil, nil)
    obs.obs_scene_add(s, t)
    obs.obs_source_release(t)

    obs.obs_scene_release(s)
end
```
2. Select any scene.
3. Click the Test button.

**Comment by cg2121** [comment]
Same as #4076

**Comment by cg2121** [comment]
Duplicate of https://github.com/obsproject/obs-studio/issues/4076

The functions to set the name are the same for both scenes and sources, so fixing just that fixes the issue for both.

**Comment by cg2121** [comment]
The functions to set the name are the same for both scenes and sources, so fixing just that, fixes the issue for both.
