### ISSUE TITLE
Windows audio missing from system tray when OBS is launched with a microphone

### ISSUE THREAD

**Issue by macromaniac** [obsproject/obs-studio#4085]
On windows 10 when I start OBS I can't access the audio system tray anymore. Since I use headphones and don't have a volume knob on my keyboard I have to open up the volume mixer to change the volume while OBS is open.

Here is a video showing some of the problem: https://youtu.be/WVOlCYjjZnE , After disabling OBS from the system tray the audio system tray icon comes back

## Platform
Operating system and version: Windows Version: 10.0 Build 19041 (release: 2004; revision: 746; 64-bit)

OBS Studio version: 26.1.1 (64 bit)

## Expected Behavior

I launch OBS and it adds it to the system tray without modifying other items
## Current Behavior
I launch OBS and it adds it to the system tray but the windows audio system tray icon goes missing

logfile: https://pastebin.com/PK8R56Cg
## Steps to Reproduce
1. Ensure Settings->General->System Tray->Enable is checked
2. Ensure you have a microphone in your scene
3. Ensure "Allow apps to access your microphone is checked on" by searching for "microphone privacy settings" in windows taskbar (this is on by default)
4. (edit) Ensure you have no "hidden" system tray icons (there should be no arrow, e.g. "^" in your system tray)
5. Close and then open OBS
6. Observe that the windows audio tray icon is missing

## Additional information
When "Allow apps to access your microphone" is checked off this behavior does not happen
When you start OBS and then enable system tray this behavior does not happen until you restart it again (shown in video)
This bug is annoying because this computer doesn't have hardware control on the keyboard

**Comment by macromaniac** [comment]
I found a workaround. When I go to "select which icons appear in the taskbar" I can turn off the microphone one
![image](https://user-images.githubusercontent.com/828529/104844426-bf6e9980-5895-11eb-867a-0d732839d60c.png)

Now OBS no longer replaces the audio system tray
(before)
![image](https://user-images.githubusercontent.com/828529/104844545-7703ab80-5896-11eb-9b16-4b2c20912c0d.png)
(after)
![image](https://user-images.githubusercontent.com/828529/104844440-d44b2d00-5895-11eb-9a91-fc0b9424a2e5.png)

I think this bug only happens when the "<" is not there. I can add anything, not just the microphone, to the "<" group and the bug no longer happens.

**Comment by WizardCM** [comment]
I'll be honest, this doesn't sound like an OBS bug. Not sure there's anything we could do.

**Comment by energizerfellow** [comment]
I agree this very much sounds like a bug/feature in Windows itself is how it's prioritizing the display of OS-provided default icons in the system tray.

You can try updating to the latest 20H2/2009 build of Windows 10 to see if things change, but this is likely an intentional default to make users more aware that some application is using a microphone.

**Comment by notr1ch** [comment]
Closing as this is almost certainly a Windows issue, OBS has no influence over which system icons appear.
