### ISSUE TITLE
macOS - OBS fails to install/ start Virtual Camera if directory "/Library/CoreMediaIO/Plug-Ins" is missing.

### ISSUE THREAD

**Issue by verstaerker-583** [obsproject/obs-studio#4095]
## Platform
Operating system and version: macOs Big Sur 11.1
OBS Studio version: 26.1.2

## Expected Behavior
OBS should mkdir "/Library/CoreMediaIO/Plug-Ins" or at least report issues finding/ making the required directory.

## Current Behavior
OBS fails, without giving an error message, to install/ start Virtual Camera if directory "/Library/CoreMediaIO/Plug-Ins" is missing.

## Steps to Reproduce
rm -rf "/Library/CoreMediaIO/Plug-Ins"
Start OBS and try to start OBS Virtual Camera.

**Comment by gxalpha** [comment]
Can confirm, the expected behaviour needs to be `sudo mkdir "/Library/CoreMediaIO/Plug-Ins/DAL"` though, otherwise the DAL directory is created by OBS but the `Contents` directory of the `.plugin` is placed directly into it, which likely is the cause of the problem

**Comment by PatTheMav** [comment]
Would be interesting to know if macOS doesn't create this directory by default anymore, because it should not _not exist_. And I'm not entirely happy creating system directories from within an app.

Otherwise creating the directory if it doesn't exist should not be too hard to fix.

**Comment by verstaerker-583** [comment]
> Would be interesting to know if macOS doesn't create this directory by default anymore, because it should not _not exist_. And I'm not entirely happy creating system directories from within an app.
> 
> Otherwise creating the directory if it doesn't exist should not be too hard to fi

**Comment by verstaerker-583** [comment]
ups - sorry - did close this by mistake

I think, but do not know for sure, the directory was missing after uninstalling other plugins. For sure, this was not a clean, new installation. OBS should at least not fail "silently" - simply reporting the missing directory would be sufficient, but not comfortable, in my eyes.
