### ISSUE TITLE
GPU encoding device resets to primary on system reboot with two AMD GPUs

### ISSUE THREAD

**Issue by Jarkkis** [obsproject/obs-studio#4099]
## Platform

Operating system and version: Windows 10 Pro version 20H2 build 19042.746
OBS Studio version: 26.1.1 (64 bit)

## Expected Behavior

Selected GPU encoding device should be applied on system reboot.

## Current Behavior

Selected GPU encoding device resets to primary GPU on system reboot.

## Steps to Reproduce

1. Go to settings -> output and select advanced
2. Select both streaming and recording encoders to use H264 (AMD)
3. Select both streaming and recording to use secondary GPU instead of primary
4. Reboot computer
5. Open OBS and observe GPU selection reverted to primary GPU.

## Additional information

I have two AMD gpus and targetting to use secondary GPU as encoding device. Primary is RX5700XT and secondary is RX570.

### Logfiles
Switching to secondary GPU and exiting application [2021-01-19 17-50-00.txt](https://github.com/obsproject/obs-studio/files/5837032/2021-01-19.17-50-00.txt)
After reboot primary GPU is used [2021-01-19 17-52-05.txt](https://github.com/obsproject/obs-studio/files/5837039/2021-01-19.17-52-05.txt)

**Comment by RytoEX** [comment]
This was filed against the old AMD encoder implementation, which is now deprecated and is no longer receiving bug fixes. If you experience this with the new AMD encoder implementation, please open a new GitHub Issue.
