### ISSUE TITLE
Release 26.1.3

### ISSUE THREAD

**Issue by abcdw** [obsproject/obs-studio#4100]
Put 26.1.3 tag, please.

This commit https://github.com/obsproject/obs-studio/commit/fb347c3c62ced2ea302769e449d300fd923c2d4b from master branch is required to update obs package in GNU Guix repositories.

Without that commit it's not possible to package obs plugins with guix and nix (https://github.com/NixOS/nixpkgs/issues/77627) package managers. Without 26.1.3 tag it's hard to update obs package in guix repositories.

Sorry for disturbing you, thank you for all your work!

**Comment by notr1ch** [comment]
You can checkout by commit hash, there is no need to use a tag. It's unlikely we'll make a new release just for this.

**Comment by abcdw** [comment]
@notr1ch Sure I can, for my personal needs, but to upstream those changes to GNU/Linux distributions the tag is needed.

According to packaging [guidlines](https://guix.gnu.org/manual/en/guix.html#Version-Numbers):
> Occasionally, we package snapshots of upstream’s version control system (VCS) instead of formal releases. This should remain exceptional, because it is up to upstream developers to clarify what the stable release is.

It's very likely that the patch updating package from release version to some random commit will be rejected by Guix. Waiting for 3-4 months is possible, but it would be cool to have acces to obs and its ecosystem from those cool package managers earlier. 

BTW, according to https://repology.org/, nix is one of the biggest package repository.

@Nathan-Huckleberry, please reopen the issue, maybe other maintainers will comment on that and will share their thoughts. Thank you!

**Comment by dodgepong** [comment]
I concur with R1CH's assessment that it's unlikely that we will make a new release just for this.

**Comment by Fenrirthviti** [comment]
I also agree. Any time I've seen a package manager with a need for a specific fix, they have always just cherry picked the commit. I can understand wanting to keep things "clean", but that also applies to us. Creating a tag for a single commit seems a little wasteful when it's not a requirement and you are able to work around it by just pulling the commit directly. You're asking us to create a tag, and then potentially cause every other *nix package manager (and some on Windows and macOS, potentially) to update to a new tag that has no impact on them.

**Comment by abcdw** [comment]
@Fenrirthviti 
As I expected it to be a minor release, there is no need for other PMs to bump OBS package, but overall your argument is sound. Thank you for the explanation and your time!)

OK, I will think, how I can workaround it.
