### ISSUE TITLE
Visibility of sources synchronise across duplicated scenes

### ISSUE THREAD

**Issue by KoreusZ** [obsproject/obs-studio#4104]
## Platform
Operating system and version: Windows 10 Build 19041
OBS Studio version: 26.1.1

## Expected Behavior
Visibility of sources in a duplicated scene are independent from the visibility of those sources in the original scene. 

## Current Behavior
Visibility of sources in a duplicated scene are synchronized with the visibility of those sources in the original scene _but only when those sources are in groups. The visibility of the groups themselves are still independent_

## Steps to Reproduce

1. Create a scene with sources in groups
2. Duplicate the scene
3. Turn off one of the sources in the new scene
4. It will now be off in the original scene.
5. Turn on the source in the original scene, then turn off its group.
6. The group will still be on in the new scene

## Additional information
https://youtu.be/yZ0FvJRXINk

**Comment by WizardCM** [comment]
A group cannot be duplicated. It is always a reference, which means its children are too. This is by design, I believe. I'll leave this open for another to confirm.

**Comment by KoreusZ** [comment]
So the visibility of the contents of a group is shared between all scenes that contain the group?

**Comment by WizardCM** [comment]
Correct, as visibility of items within a group are tied to the group, not the scene.
