### ISSUE TITLE
Audio distortion with BlackHole 2ch on MacOS Catalina

### ISSUE THREAD

**Issue by andrewschreiber** [obsproject/obs-studio#4111]
## Platform

Operating system and version: MacOS 10.17.5
OBS Studio version: 26.0.2 (64 bit)

## Expected Behavior

Normal sounding audio played through BlackHole to OBS. 

## Current Behavior

https://youtu.be/zlzmySfFJ1o

Audio is distorted by a slo-mo effect. This distortion happens immediately when starting OBS - even if I haven't selected an audio device to listen to BlackHole. I can hear it if I have Spotify playing. If I quit OBS, the music cuts out for a moment, then resumes with no distortion.

## Attempts to fix
- Swapping from stereo to mono
- Audio bitrate from 44kHz to 48kHz
- Disabling any BlackHole2ch-sourced audio device in OBS
- All permutations of my Audio MIDI Setup
- Restarting computer
- All permutations of enabling / opening the relevant applications.
![image](https://user-images.githubusercontent.com/1892071/105268183-945ea100-5b46-11eb-9687-dd92c2cfe340.png)

## Log file 
Log File:
16:43:30.346: Command Line Arguments: /Applications/OBS.app/Contents/MacOS/obs
16:43:30.346: CPU Name: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
16:43:30.346: CPU Speed: 2200MHz
16:43:30.346: Physical Cores: 4, Logical Cores: 8
16:43:30.346: Physical Memory: 16384MB Total
16:43:30.346: OS Name: Mac OS X (NSMACHOperatingSystem)
16:43:30.346: OS Version: Version 10.15.7 (Build 19H15)
16:43:30.346: Kernel Version: 19.6.0
16:43:30.350: hotkeys-cocoa: Using layout 'com.apple.keylayout.US'
16:43:30.351: Portable mode: false
16:43:30.482: OBS 26.0.2 (mac)
16:43:30.482: ---------------------------------
16:43:30.483: ---------------------------------
16:43:30.483: audio settings reset:
16:43:30.483: 	samples per sec: 44100
16:43:30.483: 	speakers:        1
16:43:30.484: ---------------------------------
16:43:30.484: Initializing OpenGL...
16:43:30.509: Loading up OpenGL on adapter Intel Inc. Intel Iris Pro OpenGL Engine
16:43:30.509: OpenGL loaded successfully, version 4.1 INTEL-14.7.8, shading language 4.10
16:43:30.611: ---------------------------------
16:43:30.611: video settings reset:
16:43:30.611: 	base resolution:   1920x1080
16:43:30.611: 	output resolution: 1280x720
16:43:30.611: 	downscale filter:  Bicubic
16:43:30.611: 	fps:               30/1
16:43:30.611: 	format:            NV12
16:43:30.611: 	YUV mode:          709/Partial
16:43:30.611: NV12 texture support not available
16:43:30.611: Audio monitoring device:
16:43:30.611: 	name: Default
16:43:30.611: 	id: default
16:43:30.611: ---------------------------------
16:43:30.614: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
16:43:30.668: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
16:43:30.669: No blackmagic support
16:43:30.733: [VideoToolbox encoder]: Adding VideoToolbox H264 encoders
16:43:30.760: [obs-browser]: Version 2.8.7
16:43:30.771: VLC found, VLC video source enabled
16:43:30.774: ---------------------------------
16:43:30.774:   Loaded Modules:
16:43:30.774:     advanced-scene-switcher.so
16:43:30.774:     vlc-video.so
16:43:30.774:     text-freetype2.so
16:43:30.774:     rtmp-services.so
16:43:30.774:     obs-x264.so
16:43:30.774:     obs-vst.so
16:43:30.774:     obs-transitions.so
16:43:30.774:     obs-outputs.so
16:43:30.774:     obs-libfdk.so
16:43:30.774:     obs-filters.so
16:43:30.774:     obs-ffmpeg.so
16:43:30.774:     obs-browser.so
16:43:30.774:     mac-vth264.so
16:43:30.774:     mac-syphon.so
16:43:30.774:     mac-decklink.so
16:43:30.774:     mac-capture.so
16:43:30.774:     mac-avcapture.so
16:43:30.774:     linux-jack.so
16:43:30.774:     image-source.so
16:43:30.774:     frontend-tools.so
16:43:30.774:     decklink-ouput-ui.so
16:43:30.774:     coreaudio-encoder.so
16:43:30.774: ---------------------------------
16:43:30.774: os_dlopen(../obs-plugins/obs-browser->../obs-plugins/obs-browser.so): dlopen(../obs-plugins/obs-browser.so, 257): image not found
16:43:30.774: 
16:43:30.774: ==== Startup complete ===============================================
16:43:30.791: All scene data cleared
16:43:30.791: ------------------------------------------------
16:43:30.838: coreaudio: device 'sbbخj4&7=I	lZ*' initialized
16:43:30.838: [Loaded global audio device]: 'Mic/Aux'
16:43:30.843: coreaudio: device 'BlackHole 2ch' initialized
16:43:30.914: adding 46 milliseconds of audio buffering, total audio buffering is now 46 milliseconds (source: Mic/Aux)
16:43:30.914: 
16:43:30.924: Webcam: Selected device 'FaceTime HD Camera'
16:43:30.926: Webcam: Using preset 640x480
16:43:30.973: coreaudio: device 'BlackHole 16ch' initialized
16:43:30.974: Switched to scene 'Left Monitor'
16:43:30.974: Advanced Scene Switcher started
16:43:30.974: ------------------------------------------------
16:43:30.974: Loaded scenes:
16:43:30.974: - scene 'Center Monitor':
16:43:30.974:     - source: 'Screen 1' (display_capture)
16:43:30.974:     - source: 'Webcam' (av_capture_input)
16:43:30.974:     - source: 'Audio Input Capture 2' (coreaudio_input_capture)
16:43:30.974: - scene 'Left Monitor':
16:43:30.974:     - source: 'Screen Left' (display_capture)
16:43:30.974:     - source: 'Webcam' (av_capture_input)
16:43:30.974:     - source: 'Audio Output Capture' (coreaudio_output_capture)
16:43:30.974: ------------------------------------------------
16:43:50.558: coreaudio: device 'BlackHole 2ch' initialized
16:43:50.559: Settings changed (audio)
16:43:50.559: ------------------------------------------------
16:43:52.143: ==== Shutting down ==================================================
16:43:52.149: Advanced Scene Switcher stopped
16:43:52.631: All scene data cleared
16:43:52.631: ------------------------------------------------
16:43:52.713: [Scripting] Total detached callbacks: 0
16:43:52.713: Freeing OBS context data
16:43:52.725: == Profiler Results =============================
16:43:52.725: run_program_init: 893.606 ms
16:43:52.725:  ┣OBSApp::AppInit: 4.555 ms
16:43:52.725:  ┃ ┗OBSApp::InitLocale: 2.317 ms
16:43:52.725:  ┗OBSApp::OBSInit: 686.882 ms
16:43:52.725:    ┣obs_startup: 4.69 ms
16:43:52.725:    ┗OBSBasic::OBSInit: 550.037 ms
16:43:52.725:      ┣OBSBasic::InitBasicConfig: 0.308 ms
16:43:52.725:      ┣OBSBasic::ResetAudio: 0.098 ms
16:43:52.725:      ┣OBSBasic::ResetVideo: 127.787 ms
16:43:52.725:      ┣OBSBasic::InitOBSCallbacks: 0.009 ms
16:43:52.725:      ┣OBSBasic::InitHotkeys: 0.056 ms
16:43:52.725:      ┣obs_load_all_modules: 162.456 ms
16:43:52.725:      ┃ ┣obs_init_module(coreaudio-encoder.so): 0.022 ms
16:43:52.725:      ┃ ┣obs_init_module(decklink-ouput-ui.so): 0.779 ms
16:43:52.725:      ┃ ┣obs_init_module(frontend-tools.so): 4.376 ms
16:43:52.725:      ┃ ┣obs_init_module(image-source.so): 0.01 ms
16:43:52.725:      ┃ ┣obs_init_module(linux-jack.so): 0.006 ms
16:43:52.725:      ┃ ┣obs_init_module(mac-avcapture.so): 41.328 ms
16:43:52.725:      ┃ ┣obs_init_module(mac-capture.so): 0.009 ms
16:43:52.725:      ┃ ┣obs_init_module(mac-decklink.so): 0.122 ms
16:43:52.725:      ┃ ┣obs_init_module(mac-syphon.so): 0.003 ms
16:43:52.725:      ┃ ┣obs_init_module(mac-vth264.so): 62.602 ms
16:43:52.725:      ┃ ┣obs_init_module(obs-browser.so): 0.081 ms
16:43:52.725:      ┃ ┣obs_init_module(obs-ffmpeg.so): 0.017 ms
16:43:52.725:      ┃ ┣obs_init_module(obs-filters.so): 0.026 ms
16:43:52.725:      ┃ ┣obs_init_module(obs-libfdk.so): 0.003 ms
16:43:52.725:      ┃ ┣obs_init_module(obs-outputs.so): 0.007 ms
16:43:52.725:      ┃ ┣obs_init_module(obs-transitions.so): 0.008 ms
16:43:52.725:      ┃ ┣obs_init_module(obs-vst.so): 0.015 ms
16:43:52.725:      ┃ ┣obs_init_module(obs-x264.so): 0.003 ms
16:43:52.725:      ┃ ┣obs_init_module(rtmp-services.so): 0.789 ms
16:43:52.725:      ┃ ┣obs_init_module(text-freetype2.so): 0.03 ms
16:43:52.725:      ┃ ┣obs_init_module(vlc-video.so): 1.077 ms
16:43:52.725:      ┃ ┗obs_init_module(advanced-scene-switcher.so): 0.328 ms
16:43:52.725:      ┣OBSBasic::ResetOutputs: 11.782 ms
16:43:52.725:      ┣OBSBasic::CreateHotkeys: 0.057 ms
16:43:52.725:      ┣OBSBasic::InitService: 1.98 ms
16:43:52.725:      ┣OBSBasic::InitPrimitives: 0.127 ms
16:43:52.725:      ┗OBSBasic::Load: 191.971 ms
16:43:52.726: obs_hotkey_thread(25 ms): min=0.365 ms, median=0.531 ms, max=2.19 ms, 99th percentile=1.632 ms, 100% below 25 ms
16:43:52.726: audio_thread(Audio): min=0.014 ms, median=0.114 ms, max=1.018 ms, 99th percentile=0.536 ms
16:43:52.726: obs_graphics_thread(33.3333 ms): min=0.094 ms, median=0.841 ms, max=126.366 ms, 99th percentile=21.752 ms, 99.6974% below 33.333 ms
16:43:52.726:  ┣tick_sources: min=0 ms, median=0.011 ms, max=126.254 ms, 99th percentile=0.207 ms
16:43:52.726:  ┣output_frame: min=0.081 ms, median=0.374 ms, max=12.113 ms, 99th percentile=1.388 ms
16:43:52.726:  ┃ ┗gs_context(video->graphics): min=0.081 ms, median=0.373 ms, max=12.112 ms, 99th percentile=1.387 ms
16:43:52.726:  ┃   ┣render_video: min=0.015 ms, median=0.273 ms, max=4.603 ms, 99th percentile=0.715 ms
16:43:52.726:  ┃   ┃ ┗render_main_texture: min=0.013 ms, median=0.269 ms, max=4.6 ms, 99th percentile=0.659 ms
16:43:52.726:  ┃   ┗gs_flush: min=0.045 ms, median=0.084 ms, max=11.525 ms, 99th percentile=0.682 ms
16:43:52.726:  ┗render_displays: min=0.001 ms, median=0.414 ms, max=34.588 ms, 99th percentile=19.803 ms
16:43:52.726: =================================================
16:43:52.726: == Profiler Time Between Calls ==================
16:43:52.726: obs_hotkey_thread(25 ms): min=25.462 ms, median=29.134 ms, max=173.902 ms, 0.262467% within ±2% of 25 ms (0% lower, 99.7375% higher)
16:43:52.726: obs_graphics_thread(33.3333 ms): min=4.826 ms, median=33.325 ms, max=126.374 ms, 32.4242% within ±2% of 33.333 ms (33.6364% lower, 33.9394% higher)
16:43:52.726: =================================================
16:43:52.733: Number of memory leaks: 0

Issue on BlackHole's github: https://github.com/ExistentialAudio/BlackHole/issues/267

**Comment by WizardCM** [comment]
What happens if you set both OBS and BlackHole to 48kHz?

**Comment by andrewschreiber** [comment]
@WizardCM Thanks for the quick response! No change, distortion persists.

**Comment by asher-the-thrasher** [comment]
In a new multi-output, try matching your settings to mine and see if it still happens (its fine that I have 16ch and you have 2ch, it shouldn't make a difference)
![image](https://user-images.githubusercontent.com/76796294/105268568-7c941680-5b60-11eb-934b-2f67b4ba3674.png)

**Comment by andrewschreiber** [comment]
Update: The issue seems to go away if I use my built-in laptop speakers instead of my AirPods (sbbخ�j�4&7=I l�Z). So there must be something going on with OBS and my headphones?

**Comment by asher-the-thrasher** [comment]
> Update: The issue seems to go away if I use my built-in laptop speakers instead of my AirPods (sbbخ�j�4&7=I l�Z). So there must be something going on with OBS and my headphones?

i think the issue is the timing with them and having the built-in there syncs the timing.

**Comment by andrewschreiber** [comment]
@asher-the-thrasher Hmm is there a way to force the timing to sync? Its not viable to use the built in speakers for streaming as they drown out the mic.

**Comment by andrewschreiber** [comment]
Okay looks like I can swap my AirPods to use 48kHz if I disable the AirPods microphone. Will use the laptop mic. Not ideal but it works, and hey, my airpods now sound GREAT!

**Comment by andrewschreiber** [comment]
![image](https://user-images.githubusercontent.com/1892071/105269432-c244e500-5b48-11eb-9180-2d31c6ac8eaf.png)
^ working setup.

Unsure if I should close this issue. Is it worth aiming to fix the timing mismatch problem?

**Comment by energizerfellow** [comment]
Does the behavior continue after updating OBS Studio to 26.1.2?

**Comment by andrewschreiber** [comment]
Upgrading to OBS 26.1.2 fixed the issue, thanks!

**Comment by filipjurcak** [comment]
Hi, does the 26.1.2 really fix the problem? I experience this on two new M1 Macs with AirPods, even after upgrading to OBS 26.1.2 - I still need to disable AirPods microphone in order to select 48kHz sample rate on aggragate device in Audio MIDI setup app.
