### ISSUE TITLE
Zooming into the preview breaks at some point at a high zoom level

### ISSUE THREAD

**Issue by lebaston100** [obsproject/obs-studio#4115]
## Platform

Operating system and version: Win 10 20H2
OBS Studio version: x64 CI Build of commit 552bd035d55c0df237f99e27e9ce827b129d2d84

## Expected Behavior

The preview should either stop zooming in at some point or just continue zooming in

## Current Behavior

At some point after a very high zoom level (not exactly sure how many "steps") the preview seemingly resets the size, scales the preview to the size of the available preview area (ignoring the aspect ratio of the canvas) but the lines of the source still appear as if it was farther zoomed in.

## Steps to Reproduce

1. right click the canvas
2. select preview scaling -> canvas
3. hold down spacebar
4. using the mouse scroll in the preview area to zoom in
5. continue zooming in until the zoom breaks

## Additional information

[https://obsproject.com/logs/rxgfkhpgBvh2zPcC](https://obsproject.com/logs/rxgfkhpgBvh2zPcC) (nothing really special here)
[https://streamable.com/l0rvj1](https://streamable.com/l0rvj1)

**Comment by WizardCM** [comment]
Verified on Windows 10

https://github.com/obsproject/obs-studio/blob/951acf2dfed47dcf8fe04082b6d8986d7e6a0303/UI/window-basic-preview.cpp#L501-L505

Looks like it gets confused around `scalingLevel = 33` at 720p, `scalingLevel = 30` at 1080p, and `scalingLevel = 25` at 1440p.
