### ISSUE TITLE
Window capturing regularly stutters every 6 minutes for 20 seconds

### ISSUE THREAD

**Issue by Adega-Studio** [obsproject/obs-studio#4117]
## Platform

Operating system and version: Operating system and version: Win 10 20H2
OBS Studio version: 26.1.1 (64 bit)

## Current Behavior

Window capturing regularly stutters every 6 minutes for 20 seconds

## Steps to Reproduce

1. I tried everything on 5 different computers and found no reason for regular video stuttering (.
2. Window Capture regularly stutters every 6 minutes for 20 seconds. Why is this happening? Game capture is supported even more often.
3. Here is a test video recorded in obs through window capturing • Timecode of start and end of stuttering: from 3:05 to 3:25 and so regularly (.
4. https://www.youtube.com/watch?v=1i7cR6pfiww&feature=emb_logo

## Additional information

I tried everything on 5 different computers and found no reason for regular video stuttering (.
Window Capture regularly stutters every 6 minutes for 20 seconds. Why is this happening? Game capture is supported even more often.
Here is a test video recorded in obs through window capturing • Timecode of start and end of stuttering: from 3:05 to 3:25 and so regularly (.
https://www.youtube.com/watch?v=1i7cR6pfiww&feature=emb_logo
File log https://obsproject.com/logs/BOnmFdIpwNUHFYr-

**Comment by Fenrirthviti** [comment]
When filing an issue report on GitHub, please ensure that you are filling out the issue template and providing replication steps.

**Comment by Adega-Studio** [comment]
> When filing an issue report on GitHub, please ensure that you are filling out the issue template and providing replication steps.

It seems to have correctly designed. It's hard for me, a language I don't know, I use a translator.

**Comment by Scrxtchy** [comment]
The log file provided is from a version of obs that does not match the version in your opening post

**Comment by Adega-Studio** [comment]
> The log file provided is from a version of obs that does not match the version in your opening post

Does not depend on the version of the program, the problem remains. I update regularly in the hope that the problem will be fixed, but this is not the case (. I have been looking for a solution for over a year now and all without result.

**Comment by Adega-Studio** [comment]
Site for test and verification.
https://www.testufo.com/stutter#demo=smooth&foreground=ffffff&background=000000&pps=720

**Comment by Adega-Studio** [comment]
Curious to know if a solution has been found

**Comment by Fenrirthviti** [comment]
Going to close this in favor of #4191 as there is more discussion/testing being done there.
