### ISSUE TITLE
Remux drops audio tracks.

### ISSUE THREAD

**Issue by ryantheleach** [obsproject/obs-studio#4118]
## Platform

Operating system and version: Windows 10 (Version	10.0.19041 Build 19041)
OBS Studio version: 26.1.1

## Expected Behavior

I expect all tracks in the MKV to be copied to the MP4 upon remuxing.

## Current Behavior

Only one of the audio tracks is copied into the MP4, and it isn't always the one I expect.

## Steps to Reproduce

1. Record a replay as mp4 with multiple audio tracks.
2. Swap to mkv.
3. record a replay.
3. remux the mkv replay.
4. Compare the produced mp4 files, audio tracks will be missing from the version that was remuxed.

## Additional information

Workaround: Remuxing yourself using ffmpeg: `ffmpeg -i input.mkv -c copy -map 0 output.mp4`

**Comment by matoi974** [comment]
Can't repro, my remuxed recordings and replay buffers have all 3 audio tracks still in them. Maybe try restarting obs after changing container format?

**Comment by ryantheleach** [comment]
It's either an intermittent issue or a dumb mistake on my part, sorry for wasting your time @matoi974
