### ISSUE TITLE
OBS randomly decides to start recording at a low framerate (FFMPEG VAAPI)

### ISSUE THREAD

**Issue by PQCraft** [obsproject/obs-studio#4121]
## Platform

Operating system and version: Linux
OBS Studio version: 26.1.0-rc1

## Expected Behavior

Should record @ 30 fps like it always has

## Current Behavior

Currently records at around 0.2 fps despite saying that it is recording at around 30 fps.

## Steps to Reproduce

1. Open OBS
2. Press "Start Recording"
3. Wait until you feel as though you should stop the video (if you stop before 5 seconds then you will only get 1 frame)
4. Press "Stop Recording"
5. Open the video

6. Cringe at 1 frame per 5 seconds

## Additional information

Screenshots of settings and log are attached. I also cannot use software rendering as that causes a 5-10 fps output when recording Minecraft (which I do often).
![Screenshot](https://user-images.githubusercontent.com/58464017/105528711-503cdf00-5cb3-11eb-9874-0adcff493000.png)
![Screenshot](https://user-images.githubusercontent.com/58464017/105528776-63e84580-5cb3-11eb-919b-efba889dded4.png)
![Screenshot](https://user-images.githubusercontent.com/58464017/105528804-6e0a4400-5cb3-11eb-81ef-80a9e9af6495.png)
[2021-01-22 11-08-01.txt](https://github.com/obsproject/obs-studio/files/5857772/2021-01-22.11-08-01.txt)
Video: https://drive.google.com/file/d/1ugmgTIkjIPlztR3E0SMnqEM24ldyT9dH/view?usp=sharing

**Comment by kkartaltepe** [comment]
Please use one of the support channels, such as https://obsproject.com/discord or the forums.

**Comment by ernstp** [comment]
I have the same issue. If you look at the video with VLC statistics you can see that it's constantly decoding new frames. Is the problem that it's simply encoding the same frame over and over again?

**Comment by PQCraft** [comment]
@ernstp Yes! That’s exactly what it’s doing lol. I got around it by switching to software rendering but I cannot play certain games and record now :(
