### ISSUE TITLE
Output resolution cannot be changed for services using "supported resolutions"

### ISSUE THREAD

**Issue by SCG82** [obsproject/obs-studio#4124]
## Platform

Operating system and version: macOS 10.14.6/11.1, windows 10
OBS Studio version: 26.1.2 (macOS), 26.1.1 (win)

## Expected Behavior

Output size should be set to the selected size.
## Current Behavior

Output size does not actually change to the size selected.

## Steps to Reproduce

1. Change the service to "Facebook Live"
2. Set Canvas size to 1920x1080 and Output size to 852x480 and close settings.
3. Open settings, change Output size to 1280x720, close settings.
4. Reopen settings and check output size.

## Additional information

"supported resolutions" was added in ebbe8d1

**Comment by Fenrirthviti** [comment]
As a sidenote, when changing the dropdown from 720p to 480p, the Apply button does not activate, so it's likely something is blocking the UI from knowing that the field has changed and it isn't bothering to try and update the value.

I have also confirmed this only happens on services that have supported resolutions listed. Twitch, for example, does not exhibit this problem.
