### ISSUE TITLE
OBS cannot record screen on AMD.

### ISSUE THREAD

**Issue by LinXiaoDe** [obsproject/obs-studio#4129]
## environment
computer：Lenovo Yoga 14s
OS: Arch Linux x86_64 
CPU: AMD Ryzen 7 4800H with Radeo 
GPU: AMD ATI 03:00.0 Renoir 

## problem
When I use OBS capture screen, OBS can get the sound normally, but it can't get the screen. So the result of the recording is a black screen

How can I solve this problem that has been bothering me for a long time? Thank you in advance!

**Comment by tielqt** [comment]
Please don't delete the issue template when you're creating an issue.

This question is better suited to our Discord server or forums. Please visit https://obsproject.com/help to get support.

**Comment by LinXiaoDe** [comment]
> Please don't delete the issue template when you're creating an issue.
> 
> This question is better suited to our Discord server or forums. Please visit https://obsproject.com/help to get support.

I'm sorry to delete the template and thank you very much for your reply
