### ISSUE TITLE
EOS Canon 50M Camera not detected on Mac?

### ISSUE THREAD

**Issue by alvarotrigo** [obsproject/obs-studio#4134]
## Platform
Operating system and version: Mac OS X Catalina 10.15.7 (19H114)
OBS Studio version: 26.1.2 (64 bits)

## Expected Behavior
My camera should appear as a Video Capture device.

## Current Behavior
Camera doesn't appear on the Video Capture device modal. (Canon EOS M50)

## Steps to Reproduce
1- Connect camera via micro - USB 
2- Turn on camera
3- Change to video mode

## Additional information
I installed EOS Webcam utility and it works fine in Google meets and zoom.

**Comment by PatTheMav** [comment]
Please attach OBS log file - contrary to popular belief we don't all have a Canon EOS lying around to reproduce this.. 😉

**Comment by gxalpha** [comment]
Closing as there was no answer in over a year.
