### ISSUE TITLE
Input Mixer display error with Studio Mode

### ISSUE THREAD

**Issue by Mishasama** [obsproject/obs-studio#4142]
## Platform

Operating system and version: WIN 10 1809
OBS Studio version: 26.1.1

## Expected Behavior

I don't know, maybe it should display in properties if 'Hide in Mixer' is active.

## Current Behavior

The 'Hide in Mixer' will make a duplicate meter when switch scenes.

## Steps to Reproduce

> https://github.com/pkviet/obs-studio/issues/47

Please check [this video](https://youtu.be/jwdPbuvc7mA) for steps.

## Additional information

It may be related to #3334.

**Comment by pkviet** [comment]
obsproject.com has no audio; can you try with a youtube url for instance ?

**Comment by pkviet** [comment]
Followed your steps in obs 26.1.1 and I definitely can't repro... Maybe corrupted settings ?

**Comment by Mishasama** [comment]
> obsproject.com has no audio; can you try with a youtube url for instance ?

It doesn't need any audio. It just leaves a meter on the mixer and can't be removed anyway.

> Followed your steps in obs 26.1.1 and I definitely can't repro... Maybe corrupted settings ?

I don't know, I was used a new scene collection and a new profile.

**Comment by pkviet** [comment]
i tested with you exact steps with obsproject.com url, but no, i can't repro. I've asked other people in support team to double check, we'll see if they can repro.

**Comment by pkviet** [comment]
ok i repro'd eventually, as did others in the support team of obs. I'll investigate

**Comment by pkviet** [comment]
Repro steps (thanks to Flaeri from obs support team):
1. make two blank scenes.
2. enable studio mode.
3. add browser source to scene 1, enable audio control
4. switch to scene 2 (dont transition)
5. go back to scene 1, "hide in mixer" on the browser source
6. unhide it again, you should now have a visible "browser" in your audio mixer
7. transition, you now have 2 "browser" in your audio mix

NB: it needn't be a browser source; can be any source with audio

**Comment by Mishasama** [comment]
[Crash 2021-01-27 04-26-41.txt](https://github.com/obsproject/obs-studio/files/5875914/Crash.2021-01-27.04-26-41.txt)
This is another tester get crash after the test. Maybe it helps.

**Comment by pkviet** [comment]
are you sure it's related ? the crash is with the audio monitor

**Comment by Mishasama** [comment]
> are you sure it's related ? the crash is with the audio monitor

If it is with the audio monitor, then it should relate to several issues.

**Comment by dodgepong** [comment]
That's not how crashes work. You're reporting a UI issue, not a crash. Your tester friend got a crash, but there's no evidence that the crash was specifically related to this UI issue. A brief examination of the crash log suggests that it's completely unrelated to the issue you're reporting here, and they only incidentally encountered it while trying to reproduce this issue. If they are getting a crash, they should report it in a separate issue with reproduction steps as well.
