### ISSUE TITLE
Jittery cursor on window-only screencast (Linux)

### ISSUE THREAD

**Issue by BreadyX** [obsproject/obs-studio#4146]
When trying to screen cast a single window using the 'Desktop Screencast (Wayland/X11)' source (the one using the xdg portal) the window is correctly recorded but the cursor keeps jumping around. This happens both on Wayland and X11. Sometimes the whole window would flicker (rarely on amdgpu, constantly on NVIDIA).

Full desktop screencast doesn't have problems.

The problem could also be a bug in mutter. I tested the xdg portal using firefox on wayland and the [webrtc test page](https://mozilla.github.io/webrtc-landing/gum_test.html) and firefox seems to not capture the cursor at all. I will cross post this issue also on the mutter bug tracker.

OS information:
- Fedora 32 (linux 5.10.10), tested both on NVIDIA proprietary and on amdgpu
- OBS version 26.1.1 (flatpak)
- Software encoding

Relevant screencasts:
- xorg:

https://user-images.githubusercontent.com/37741488/106025899-802c1e00-60c9-11eb-84c3-f524b0a9a3d0.mp4

- wayland:

https://user-images.githubusercontent.com/37741488/106025964-920dc100-60c9-11eb-99bd-25d8affb8aa7.mp4

- window flicker: (will upload later, don't have access to my PC with NVIDIA right now)

**Comment by kkartaltepe** [comment]
We dont support third party plugins or the flathub flatpak, you should file issues against the flatpak repository or the plugin itself.

**Comment by BreadyX** [comment]
Sorry about that! Will post under the flatpak version.
