### ISSUE TITLE
Video Input Sources freezing (OBS 26.1.2 and macOS Big Sur)

### ISSUE THREAD

**Issue by BoxingOctopus** [obsproject/obs-studio#4150]
## Platform

Operating system and version: macOS 11.1 (Big Sur) on 2018 MacBook Pro w/16 GB RAM 
OBS Studio version: 26.1.2

## Expected Behavior
Video Input sources should function uninterrupted

## Current Behavior
Playback of video input sources freeze up (regardless of whether stream has been started or not) at random intervals. Sources return to normal temporarily if the input device is switched to a different device in the source properties, and then switched back to the original device.

Log output: https://obsproject.com/logs/oOG7Ji25FkVrHdI5

## Steps to Reproduce

1. Create a profile with a 1280x720 canvas size
2. Create a scene in OBS with no fewer than two video input sources (each using a separate video device) and one media source (preferably a looped video clip in H264 format)
3. Upon the video input source freezing, switch the device to a different one, then switch back.

## Additional information
Analyzing the log output in macOS' Console, calls from the `obs` process to CoreMediaIO seem to stop completely once a video input source freezes

**Comment by TuxOtaku** [comment]
It's been a while since I submitted this. Has anyone had a chance to take a look?

**Comment by abates** [comment]
I seem to be having a very similar problem with Windows 64bit (version 26.1.1).  We have a single media source (rtsp from a camera) in all our scenes.  When switching scenes the input video will (sometimes) freeze.  We have seen it freeze for as much as 2 minutes.  This problem seems to occur almost always when switching from a scene with no video (slides we display before our stream) to a stream with the media source of our camera.

In troubleshooting this, I discovered that if I check "Close file when inactive" on the media source properties, then the problem no longer occurs (or at least becomes more difficult to reproduce).

**Comment by TuxOtaku** [comment]
> I seem to be having a very similar problem with Windows 64bit (version 26.1.1). We have a single media source (rtsp from a camera) in all our scenes. When switching scenes the input video will (sometimes) freeze. We have seen it freeze for as much as 2 minutes. This problem seems to occur almost always when switching from a scene with no video (slides we display before our stream) to a stream with the media source of our camera.
> 
> In troubleshooting this, I discovered that if I check "Close file when inactive" on the media source properties, then the problem no longer occurs (or at least becomes more difficult to reproduce).

In my case, the video source will freeze regardless of whether the scene it's being used in is live or not. Also it will freeze seemingly indefinitely, until I switch the device on the video source, and switch it back.

**Comment by fperez** [comment]
FWIW, I was experiencing this same problem and eventually my only solution was to downgrade from Big Sur back to Catalina. I need OBS to work so for now I'm staying in Catalina...

**Comment by RytoEX** [comment]
Please re-test this in OBS Studio 28.1.1 (or newer), ideally on macOS 13, and confirm if this is still an issue.

**Comment by tobiasbueschel** [comment]
I'm on macOS 13.0.1 and OBS 28.1.2 and always run into video freezing issues when using a Canon DSLR connected via USB using [EOS Webcam Utility v1.1.](https://hk.canon/en/support/0200629304).

**To replicate:**
1. connect Canon DSRL e.g., 70D using USB and EOS Webcam Utility
2. start OBS and start virtual camera
3. open Zoom and select OBS as a video source
4. OBS instantly starts freezing

**Here's a related post about the same issue:**
https://obsproject.com/forum/threads/eos-webcam-utility-camera-freezes-in-obs-when-zoom-is-started.161344/

I'm not sure if the error lies within OBS, EOS or Zoom, but would be grateful if anyone has any suggestions?

Thanks!

**Comment by RytoEX** [comment]
So far, I'm unable to reproduce either the original described issue or the issue reported by @tobiasbueschel with OBS Studio 28.1.2 (x86_64 version), Canon EOS Webcam Utility 1.0 (offered from [here](https://en.canon-cna.com/cameras/eos-webcam-utility/)), on macOS 12.6 and Zoom 5.12.9 (13190). I hooked up a Canon EOS Rebel T3i via the A/V Out Digital port (Mini USB) to my MacBook Pro. I set the OBS canvas to 1280x720. I have a scene with my FaceTime camera, the EOS Webcam Utility, a looping Media Source, and the OBS Virtual Camera all in it. I opened Zoom and loaded the OBS Virtual Camera in that. I left them open for over an hour and everything is still playing fine. Nothing is frozen. I also have a reliable report that the OBS Virtual Camera 

@BoxingOctopus Please retest in OBS Studio 28.1.2 (or newer) and confirm if this is still happening. If this is still happening, please provide a new OBS log file, and please specify what exactly is freezing. Is it a single source, the entire Virtual Camera as viewed in Zoom, the OBS preview, the entire OBS UI, or some combination of those?

@tobiasbueschel I would like to consider your issue separately. Please open a new GitHub Issue with answers to the questions that I asked above about what exactly is freezing.

**Comment by Fenrirthviti** [comment]
No response, closing.
