### ISSUE TITLE
First Download, Then Crash App

### ISSUE THREAD

**Issue by leokwsw** [obsproject/obs-studio#4152]
## Platform

Operating system and version: MacOS Cataline 10.15.7 Mac Mini(Late 2014)
OBS Studio version: 26.1.2

## Expected Behavior
When open OBS, then Crash. More information please check ##Additional information

## Steps to Reproduce

1. Just open App

## Additional information
[obs.txt](https://github.com/obsproject/obs-studio/files/5886868/obs.txt)

**Comment by gxalpha** [comment]
Hey,

did you have the virtual camera plugin installed before you updated to 26.1?
If so, make sure to uninstall it first https://github.com/johnboiles/obs-mac-virtualcam#uninstalling

Also I believe this is more a support related question, in that case rather use the Discord or the Forums for further questions.

**Comment by leokwsw** [comment]
> Hey,
> 
> did you have the virtual camera plugin installed before you updated to 26.1?
> If so, make sure to uninstall it first https://github.com/johnboiles/obs-mac-virtualcam#uninstalling
> 
> Also I believe this is more a support related question, in that case rather use the Discord or the Forums for further questions.

Ooo Thx.
