### ISSUE TITLE
Use anti cheat compatibility hook with specific game capture 

### ISSUE THREAD

**Issue by BCTinkleToes** [obsproject/obs-studio#4159]
last couple of days fortnite kept crashing with obs in the background or when i try to switch scenes, works fine when using display capture and ive learned its anti cheat hook, but when i have it disable the preview window is disabled, but when i had anti cheat enabled when playing apex legends the game runs fine and doesnt crash
## Platform
Windows 10 
OBS Studio version: 26.1.1
OBS.Live version 20.12.23.684

## Expected Behavior
try to change scene and my game doesnt crash and preview window works, I change my scenes fluidly and my game cap works as intended 

## Current Behavior
anti cheat compatibility hook conflicting with anti cheat software in games when enabled , also the game isnt popping up in preview window 

1. game capture 
2. specific window capture (Allow transparency, capture censor, Use anti cheat compatibility hook, hook rate normal)
3. window on fortnite (only game i had not work for me , might be more)
4. try to change a scene and the game crashes 

## Additional information
note: i've only noticed this in fortnite, any game like apex or cod the preview window and game capture is working

**Comment by notr1ch** [comment]
Please use the forums or Discord for support. Game crashing is usually due to a hook conflict.

https://obsproject.com/wiki/Known-Conflicts

**Comment by BCTinkleToes** [comment]
> Please use the forums or Discord for support. Game crashing is usually due to a hook conflict.
> 
> https://obsproject.com/wiki/Known-Conflicts

well the forums and the discord said to come here so idk dude
