### ISSUE TITLE
Preview window is completely transparent on Fedora 33

### ISSUE THREAD

**Issue by panos** [obsproject/obs-studio#4161]
## Platform

Operating system and version:
OBS Studio version: 26.1.2-111-g5efb10a5e

## Expected Behavior
The preview window should be drawn successfully.

## Current Behavior
The preview window seems to be transparent and cannot react to any sort of changes, such as adding or removing elements.

## Steps to Reproduce
- Add the OBS Studio repository from RPMFusion
- Install OBS
- Run OBS

## Additional information

**Note:** *Fedora 33* is running on GNOME with Wayland.

This setup is also running on a laptop with an Nvidia card with the nouveau drivers, but the results don't vary.

![image](https://user-images.githubusercontent.com/30193966/106274264-e6c94d00-622b-11eb-8e1b-2bf78f928bf3.png)

## Workaround:

- `QT_QPA_PLATFORM=xcb obs` (Running `obs` with the `QT_QPA_PLATFORM=xcb` environment variable/value)

**Comment by notr1ch** [comment]
Wayland is not supported. See https://github.com/obsproject/obs-studio/pull/2484 if you wish to test a PR.
