### ISSUE TITLE
No audio in recorded file (but audio in live stream) with NDI source

### ISSUE THREAD

**Issue by coldfire99** [obsproject/obs-studio#4171]
Description
- No audio in recorded file with NDI source

Setup

Using OBS 26.1.1. (64bit) with Windows 10
Using latest NDI plugin (OBS ndi 4.9.0)

Settings
6000 kbps
Audio 320 kbits
Videoout: 1280x720
Record Format: mkv

NDI Settings
Audio Only
Source Timing
No Hardware acceleration
no Fix for Alpha blending

Streaming and Recording at the same time:

 Result:
Stream has Audio
Recording has no audio

Expected Result
Stream has Audio
Recording has Audio

Changes1:
-Set Recording format to MP4
- Set NDI source  to Network Timing and press OK
- Set NDI source to Source Timing and Press OK

Result1:
- Stream has Audio - Recording has also Audio -> OK

Changes2
- Stop everything
- Close OBS
- Open OBS
- Start to record, Start to stream

Result2:
- Stream has Audio; recording has no Audio

Expected Result2: Stream and Recoding have Audio

Changes 3:
- Stop Stream and recording
- Set NDI source  to Network Timing and press OK
- Set NDI source to Source Timing and Press OK
- Start Stream and Recording

Result3:
- Stream and mp4 Recording have Audio - OK

Change4:
- restart OBS
- Start Stream and recording

Result4:
- Stream has Audio; recording has no Audio

Expected Result4: Stream and mp4 Recording have audio

Can you please fix this issue. I use very much this Network Source Functions with NDI and also Recording and it is really bad that it is not working!

Thanks

Chris

**Comment by Fenrirthviti** [comment]
The NDI plugin is third party, and we do not currently directly support it. I would recommend posting this issue on the NDI plugin repo instead.

https://github.com/Palakis/obs-ndi
