### ISSUE TITLE
Groups break Scene Item transforms for Copy & Paste (Reference) or Paste (Duplicate) actions

### ISSUE THREAD

**Issue by Xaymar** [obsproject/obs-studio#4173]
## Platform

Operating system and version: Windows 10 20H2
OBS Studio version: 26.1.2

## Expected Behavior
Item Transforms should be complete copied over.

## Current Behavior
Item transforms lose their bounding box and alignment setting. Occasionally they may also all take the transform of one of the items and all occupy the same space.

## Steps to Reproduce

1. Add some items into a group.
2. Copy the items in the group.
3. Paste them anywhere else.

**Comment by AskMP** [comment]
Just pinging here as well as subscribing, I do a lot of copy/paste building out scenes and designs. It is a VERY big pain needing to remove from group, paste and put back for scenes that have at times 30+ sources within multiple groups. Love the fact that there is a c/p for transform specifically but it should be able to allow for pasting transform attribute pertaining to the parent item: if not in a group, it is relative to the scene.

**Comment by Xaymar** [comment]
Closing as requested.
