### ISSUE TITLE
Groups occasionally stop updating their own size

### ISSUE THREAD

**Issue by Xaymar** [obsproject/obs-studio#4174]
## Platform

Operating system and version: Windows 10 20H2
OBS Studio version: 26.1.2

## Expected Behavior
Groups should continuously update their own size. 

## Current Behavior
Groups occasionally stop updating their own size and behave as if they were scenes with a fixed size. Can only be fixed by restarting OBS.

## Steps to Reproduce

1. Add sources that change in size to a group.
2. Move them.
3. Restart OBS
4. Move them again.
5. Occasionally the Group will stop updating its own size forever.

**Comment by Xaymar** [comment]
![image](https://user-images.githubusercontent.com/437395/106466056-1df16580-649b-11eb-8ec6-35d7c61d7e8c.png)

Got it to happen _outside_ of a debugging session. For whatever reason it got stuck as 1280x1800, and no longer updates.

**Comment by Xaymar** [comment]
![image](https://user-images.githubusercontent.com/437395/106466392-8dffeb80-649b-11eb-9982-d8fd0d6a9452.png)

Also got this to happen where groups suddenly had 90001x90001 as size.

**Comment by WizardCM** [comment]
This should be fixed via #4314 - please confirm.

**Comment by Xaymar** [comment]
Partially fixed by #4314.

**Comment by Xaymar** [comment]
I've been able to reproduce this by deleting an element from a group after restarting OBS Studio.

**Comment by Xaymar** [comment]
Closing as requested.
