### ISSUE TITLE
OBS v Intel Graphics Command Center (QSV QuickSync)

### ISSUE THREAD

**Issue by webglgames** [obsproject/obs-studio#4177]
## Platform

Operating system and version: Windows 10 Enterprise LTSC 1809 (64bit)
OBS Studio version: LATEST

## Expected Behavior

On Intel cpu(s) with QSV QuickSync, OBS must use "Video Proccessing" for lower down cpu usage. The same way
as Intel Graphics Command Center !
QSV QuickSync = Intel Graphics Command Center is using rarely 25% cpu usage.
QSV QuickSync = **OBS is using 88% and over 90% cpu usage !!!!!!!!!!!!!!!!**

## Current Behavior

On all Intel CPU(s) witn QSV QuickSync OBS is using high cpu resources over 90%. This is unacceptable.

## Steps to Reproduce

1. Intel Graphics Command Center (press ctrl + alt + f5) to record (it will record on qsv quicksync)
2. Check Windows Task Manager the CPU and GPU usage (on GPU usage check and see that "Video Proccessing" usage !)
3. versus
4. OBS  qsv quicksync is hogging all the cpu(s) !!!!!!!!!!
5. OBS people is 2021 OBS update intel media sdk and fix this issue for ALL INTEL CPU(s) that support QSV QuickSync !

## Additional information

![QSV_Intel Graphics Command Center v OBS](https://user-images.githubusercontent.com/61231114/106488177-19897480-64bc-11eb-93b3-aa1aaf28632f.jpg)
![QSV_Intel Graphics Command Center v OBS Studio](https://user-images.githubusercontent.com/61231114/106488197-1ee6bf00-64bc-11eb-85c6-52946467a0ad.jpg)

**Comment by Fenrirthviti** [comment]
Please use the forums or discord for support.
