### ISSUE TITLE
v4l2loopback-related Segfault

### ISSUE THREAD

**Issue by AuroransSolis** [obsproject/obs-studio#4178]
## Platform

Operating system and version: Gentoo Base System release 2.7 x86_64, kernel 5.4.92-gentoo
OBS Studio version: 26.1.2-137-g40a47b3af-modified

## Expected Behavior

Upon clicking the `Start Virtual Camera` button, it should start a virtual camera on an available dummy video device created by the `v4l2loopback` kernel module, regardless of how `v4l2loopback` is loaded.

## Current Behavior

If `v4l2loopback` is loaded by a file in `/etc/modules-load.d/`, upon clicking `Start Virtual Camera`, OBS segfaults. If `v4l2loopback` is loaded by a user with the `modprobe` command, it puts out video to the dummy video device successfully.

## Steps to Reproduce

1. Create `/etc/modules-load.d/v4l2loopback.conf`
2. File contents should be `v4l2loopback exclusive_caps=1`
3. Reboot to force the module to be loaded through the file just created
4. Open OBS and click `Start Virtual Camera`

The problem persists until the next reboot where `v4l2loopback` is not loaded by `modules-load.d`.

**Comment by WizardCM** [comment]
Please include a stack trace from `gdb`.

**Comment by AuroransSolis** [comment]
So funny thing - I can no longer replicate this. I'm not sure if this has anything to do with a recent kernel upgrade, but if it sounds like a big enough issue I wouldn't mind downgrading to the kernel I know this happened on and trying to replicate the issue again. Sorry to be a bother.

**Comment by kkartaltepe** [comment]
feel free to update if you can replicate it.
