### ISSUE TITLE
Ubuntu 20.10 - Crash at VLC Media Source

### ISSUE THREAD

**Issue by domi555** [obsproject/obs-studio#4185]
## Platform

Operating system and version: Ubuntu 20.10
OBS Studio version: 26.1.1

## Expected Behavior

VLC Media Source should work after correct installation...

## Current Behavior

When start playing the source, OBS crashes and dont opens again. (because the scene file includes the new source, which causes a crash...)

## Steps to Reproduce

1. Install OBS on Ubuntu 20.10 with the PPA
2. Install VLC with APT (sudo apt install vlc)
3. VLC Media Source should be visible as source
4. Try to play a video file
5. CRASH

## Additional information

Ubuntu 20.04 works... (maybe ffmpeg has a problem)
Own compile of ffmpeg didnt solve it...
Tested on multiple devices...

**Comment by WizardCM** [comment]
Please include a `gdb` trace.

**Comment by domi555** [comment]
**I hope this is right:**
GNU gdb (Ubuntu 9.2-0ubuntu2) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from obs...
(No debugging symbols found in obs)
(gdb) run
Starting program: /usr/bin/obs 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffea59c640 (LWP 7006)]
[New Thread 0x7fffe9050640 (LWP 7007)]
[New Thread 0x7fffe884f640 (LWP 7008)]
[New Thread 0x7fffdbdbb640 (LWP 7009)]
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/locale.ini
Attempted path: /usr/share/obs/obs-studio/locale.ini
Attempted path: share/obs/obs-studio/locale/de-DE.ini
Attempted path: /usr/share/obs/obs-studio/locale/de-DE.ini
info: Using preferred locale 'de-DE'
Attempted path: share/obs/obs-studio/themes/Dark.qss
Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
info: CPU Name: Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
info: CPU Speed: 3021.612MHz
info: Physical Cores: 4, Logical Cores: 4
info: Physical Memory: 15892MB Total, 12781MB Free
info: Kernel Version: Linux 5.8.0-41-generic
info: Distribution: "Ubuntu" "20.10"
info: Session Type: x11
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.9
[New Thread 0x7fffdb4e8640 (LWP 7011)]
info: Portable mode: false
Attempted path: share/obs/obs-studio/themes/Dark/no_sources.svg
Attempted path: /usr/share/obs/obs-studio/themes/Dark/no_sources.svg
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_clicked()
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_destroyed()
QMetaObject::connectSlotsByName: No matching signal for on_actionGridMode_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_program_customContextMenuRequested(QPoint)
QMetaObject::connectSlotsByName: No matching signal for on_transitionRemove_clicked()
info: OBS 26.1.1 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 48000
	speakers:        2
[New Thread 0x7fffdac46640 (LWP 7012)]
info: ---------------------------------
info: Initializing OpenGL...
[New Thread 0x7fffd8844640 (LWP 7013)]
[New Thread 0x7fffc705b640 (LWP 7014)]
[New Thread 0x7fffc685a640 (LWP 7015)]
[New Thread 0x7fffc6059640 (LWP 7016)]
info: Loading up OpenGL on adapter Intel Mesa Intel(R) HD Graphics 630 (KBL GT2)
info: OpenGL loaded successfully, version 4.6 (Core Profile) Mesa 20.2.1, shading language 4.60
info: ---------------------------------
info: video settings reset:
	base resolution:   1920x1080
	output resolution: 1280x720
	downscale filter:  Bicubic
	fps:               30/1
	format:            NV12
	YUV mode:          709/Partial
[New Thread 0x7fffc56c5640 (LWP 7017)]
info: NV12 texture support not available
[New Thread 0x7fffaf7ff640 (LWP 7018)]
info: Audio monitoring device:
	name: Standard
	id: default
info: ---------------------------------
warning: Failed to load 'en-US' text for module: 'decklink-captions.so'
warning: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
[New Thread 0x7fffaeaaf640 (LWP 7019)]
libDeckLinkAPI.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
info: No blackmagic support
[Detaching after vfork from child process 7020]
warning: v4l2loopback not installed, virtual camera disabled
info: [obs-browser]: Version 2.9.1
info: [obs-browser]: CEF Version 76.1.13+gf19c584+chromium-76.0.3809.132
error: os_dlopen(libnvidia-encode.so.1->libnvidia-encode.so.1): libnvidia-encode.so.1: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden

info: FFMPEG VAAPI supported
[New Thread 0x7fff9ce96640 (LWP 7022)]
[New Thread 0x7fff97fff640 (LWP 7023)]
[Thread 0x7fff97fff640 (LWP 7023) exited]
info: VLC found, VLC video source enabled
info: ---------------------------------
info:   Loaded Modules:
info:     vlc-video.so
info:     text-freetype2.so
info:     rtmp-services.so
info:     obs-x264.so
info:     obs-vst.so
info:     obs-transitions.so
info:     obs-outputs.so
info:     obs-libfdk.so
info:     obs-filters.so
info:     obs-ffmpeg.so
info:     obs-browser.so
info:     linux-v4l2.so
info:     linux-pulseaudio.so
info:     linux-jack.so
info:     linux-decklink.so
info:     linux-capture.so
info:     linux-alsa.so
info:     image-source.so
info:     frontend-tools.so
info:     decklink-ouput-ui.so
info:     decklink-captions.so
info: ---------------------------------
error: os_dlopen(../obs-plugins/obs-browser->../obs-plugins/obs-browser.so): ../obs-plugins/obs-browser.so: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden

info: ==== Startup complete ===============================================
info: All scene data cleared
info: ------------------------------------------------
[New Thread 0x7fff97fff640 (LWP 7024)]
info: pulse-input: Server name: 'pulseaudio 13.99.2'
info: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_output.pci-0000_00_1f.3.analog-stereo.monitor'
info: [Loaded global audio device]: 'Desktop-Audio'
info: pulse-input: Server name: 'pulseaudio 13.99.2'
info: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_input.pci-0000_00_1f.3.analog-stereo'
info: [Loaded global audio device]: 'Mikrofon/AUX-Audio'
info: Switched to scene 'Szene'
info: ------------------------------------------------
info: Loaded scenes:
info: - scene 'Szene':
info: ------------------------------------------------
[New Thread 0x7fff977fe640 (LWP 7025)]
[New Thread 0x7fff96ffd640 (LWP 7026)]
[New Thread 0x7fff967fc640 (LWP 7027)]
[New Thread 0x7fff95ffb640 (LWP 7028)]
Attempted path: share/obs/obs-studio/images/overflow.png
Attempted path: /usr/share/obs/obs-studio/images/overflow.png
[Thread 0x7fff9ce96640 (LWP 7022) exited]
info: adding 42 milliseconds of audio buffering, total audio buffering is now 42 milliseconds (source: Mikrofon/AUX-Audio)

[New Thread 0x7fff94fd8640 (LWP 7030)]
[New Thread 0x7fff947d7640 (LWP 7031)]
[New Thread 0x7fff5ffff640 (LWP 7032)]
[Thread 0x7fff94fd8640 (LWP 7030) exited]
[Thread 0x7fff5ffff640 (LWP 7032) exited]
info: User added source 'VLC-Videoquelle' (vlc_source) to scene 'Szene'
[New Thread 0x7fff5ffff640 (LWP 7164)]
[New Thread 0x7fff94fd8640 (LWP 7165)]
[New Thread 0x7fff6ffff640 (LWP 7166)]
[New Thread 0x7fff6f7fe640 (LWP 7167)]
[New Thread 0x7fff6effd640 (LWP 7168)]
[New Thread 0x7fff6e7fc640 (LWP 7169)]
[Thread 0x7fff6ffff640 (LWP 7166) exited]
[Thread 0x7fff94fd8640 (LWP 7165) exited]
[Thread 0x7fff6f7fe640 (LWP 7167) exited]
Empty filename passed to function
Empty filename passed to function
[Thread 0x7fff5ffff640 (LWP 7164) exited]
[Thread 0x7fff6effd640 (LWP 7168) exited]
[New Thread 0x7fff946d6640 (LWP 7308)]
[New Thread 0x7fff6ff013c0 (LWP 7309)]
[New Thread 0x7fff6fdfd3c0 (LWP 7310)]
[New Thread 0x7fff6fcf93c0 (LWP 7311)]
[New Thread 0x7fff6fbf53c0 (LWP 7312)]
[New Thread 0x7fff6faf13c0 (LWP 7313)]
[New Thread 0x7fff6d3fa3c0 (LWP 7314)]
[New Thread 0x7fff6d2f63c0 (LWP 7315)]
[New Thread 0x7fff6d1f23c0 (LWP 7316)]
[New Thread 0x7fff6d0ee3c0 (LWP 7317)]
[New Thread 0x7fff6cfea3c0 (LWP 7318)]
[New Thread 0x7fff6cde83c0 (LWP 7319)]
[New Thread 0x7fff6cce43c0 (LWP 7320)]
[New Thread 0x7fff6cbe03c0 (LWP 7321)]
[New Thread 0x7fff6cadc3c0 (LWP 7322)]
[New Thread 0x7fff6c9d83c0 (LWP 7323)]
[New Thread 0x7fff6c7d63c0 (LWP 7324)]
[New Thread 0x7fff6c6d23c0 (LWP 7325)]
[New Thread 0x7fff6c5ce3c0 (LWP 7326)]
[New Thread 0x7fff6c4ca3c0 (LWP 7327)]
[New Thread 0x7fff6c3c63c0 (LWP 7328)]
[New Thread 0x7fff6c2c2640 (LWP 7329)]
[New Thread 0x7fff6c1c1640 (LWP 7330)]
[New Thread 0x7fff5f7d7640 (LWP 7331)]
--Type <RET> for more, q to quit, c to continue without paging--

Thread 54 "libobs: graphic" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff5f7d7640 (LWP 7331)]
__memmove_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:248
248	../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S: Datei oder Verzeichnis nicht gefunden.

**Comment by domi555** [comment]
> Please include a `gdb` trace.

Was this helpful? I'm no C/C++ expert.



...not yet, maybe in a few months. ;-)

**Comment by awarus** [comment]
@domi555, is there line in output with " (gdb) backtrace " ? I mean in [#issue2645](https://github.com/obsproject/obs-studio/issues/2645) issue there is some more information about crash. It could help to figure out where is the problem.

**Comment by wirepatch** [comment]
Exactly the same here including gdb stack trace when trying to add a .mkv video file. Same obs-studio and Ubuntu version

**Comment by flo333** [comment]
Same problem here, but on Manjaro (Plasma, kernel 5.9). There's also talk about it happening on PopOS [here](https://obsproject.com/forum/threads/obs-crashes-when-adding-vlc-video.136547/). Apparently it doesn't happen with the [obs-studio-browser](https://aur.archlinux.org/packages/obs-studio-browser/) AUR package, but I haven't been able to test that yet.

`gdb` backtrace: [trace.txt](https://github.com/obsproject/obs-studio/files/6189070/trace.txt)

You also don't have to remove the entire `~/.config/obs-studio` folder, you can just edit the VLC source out of the JSON at `~/.config/obs-studio/basic/scenes` to get it running again.

**Comment by domi555** [comment]
Update: Problem still exists with the PPA version

But Ubuntu Store OBS-app works with playback at Vlc... (20.10)

**Comment by tt2468** [comment]
Can reproduce in 27.0.0-rc2 on Ubuntu 20.04.

**Comment by domi555** [comment]
> Can reproduce in 27.0.0-rc2 on Ubuntu 20.04.

With the PPA or Ubuntu Snap Store Version?

**Comment by tybor** [comment]
> Update: Problem still exists with the PPA version
> 
> But Ubuntu Store OBS-app works with playback at Vlc... (20.10)
Could you please check which libraries does that VLC plugin use when you use the app obtained from the Ubuntu store?
Probably they are different; in that case the bug resides in the libs used by /usr/lib/obs-plugins/vlc-video.so (found using ldd on exe or lib).

I'm getting the same issue here
