### ISSUE TITLE
Crash after closing without turning off virtual camera

### ISSUE THREAD

**Issue by mcDandy** [obsproject/obs-studio#4186]
## Platform

Operating system and version: Windows 10 20H2 (19042)
OBS Studio version: 26.1.1

## Expected Behavior

Not crashing after closing (https://obsproject.com/logs/dHDGEDZfpORhTkpz)

## Current Behavior

I closed OBS without turning off virtual camera after disconnecting from msteams call. After few hours I discovered, that OBS has crashed.
[2021-02-03 13-04-03.txt](https://github.com/obsproject/obs-studio/files/5925623/2021-02-03.13-04-03.txt)
)
## Steps to Reproduce

https://user-images.githubusercontent.com/18588943/106902354-057e8680-66f9-11eb-8f89-cec823049e05.mp4

1. Have Virtual camera enabled
2. Close OBS without stopping virual camera
3. Wait for crash

**Comment by RytoEX** [comment]
Please re-test this in OBS Studio 28.1.1 (or newer) and confirm if this is still an issue. We've deployed many changes and fixes for the Virtual Camera on Windows, so we think this is fixed, but we would like to confirm.

**Comment by gxalpha** [comment]
Closing as there has been no answer for two weeks and we think this is fixed
