### ISSUE TITLE
version 26.1.1 breaks Blackmagic ultrastudio 4k mini

### ISSUE THREAD

**Issue by cusdvod** [obsproject/obs-studio#4189]
## Platform

Operating system and version:
OBS Studio version: 26.1.1

## Expected Behavior

connect and view video from blackmagic ultrastudio 4k mini
## Current Behavior

after upgrading to current version OSB can no longer talk to BMD Ultrastudio 4k mini correctly. Detects device but will not access and display video.
## Steps to Reproduce

1. upgrade 26.1 to 26.1.1 when connected to BMD ultrastudio 4k mini
2.
3.
4.

**Comment by westonator** [comment]
I made an account just to comment here. 
this issue is KILLING me. It absolutely doesn’t even recognize the ultra studio 4K mini at all. Very frustrating. Rolling back to an older version hasn’t worked either.

**Comment by dodgepong** [comment]
Are you using the latest version of Blackmagic Desktop Video?

**Comment by westonator** [comment]
Yes. After it broke I went to updating the Mac software, and black magic software. I got OBS to recognize the BM device instead of just crashing. But still no video.

**Comment by Fenrirthviti** [comment]
Closing as stale, and I've tested this device as (generally) working fine and is recognized correctly.
