### ISSUE TITLE
Image Source Causing OBS To Crash

### ISSUE THREAD

**Issue by JTF4** [obsproject/obs-studio#4190]
Whenever I have a logo source in preview or in program, it causes the program to crash.

The crash report can be found here: https://gist.github.com/JTF4/a490bfac5a979e0bc718b39da36a3f91

**Comment by dodgepong** [comment]
Please fill out the issue template, including reproduction steps.

**Comment by WizardCM** [comment]
According to the crash log, this is triggered by obs-websocket. It's possible it's causing an issue on our side, but I'd recommend reaching out to the plugin developers first.
