### ISSUE TITLE
unable to install, hash sum mismatch on installing on Ubuntu 18.04

### ISSUE THREAD

**Issue by sumitkp1** [obsproject/obs-studio#4193]
Error appearing on CLI when the following command is executed with sudo: _sudo apt install obs-studio_

Error:
__E: Failed to fetch http://in.archive.ubuntu.com/ubuntu/pool/main/q/qtbase-opensource-src/libqt5core5a_5.9.5+dfsg-0ubuntu2.5_amd64.deb  Hash Sum mismatch
   Hashes of expected file:
    - SHA512:380a90446ce48e291921960296c5f7b0018e43b27e977353bcb8f5f7477070edede78e6669d4857502d10c902d93d2ccb4330719583068f14c167378551eab04
    - SHA256:c2207de1e402831399d8e1aa33545f1528a2597f803e3a0c8847d08a33d93135
    - SHA1:45e0fd32a886d6b99d36d843a994e37ccde435df [weak]
    - MD5Sum:e47f18f74cbb1e17299ceb51dbf01c1b [weak]
    - Filesize:2036136 [weak]
   Hashes of received file:
    - SHA512:88d38e87ccf740e9d1d0bd73639a95099363bf571a46ab4973dcbf74a5570d1613b6cce7daed8fd37ea2d57a2ac7b839c632ddebb883304ccc017ecb49f4d304
    - SHA256:2c32c4091f75fc64dafee6dc395aaf881c5a970dc1e83857d9fd1d99088959d0
    - SHA1:1e74d6f17e73d5505adc45162ca6a95893192d07 [weak]
    - MD5Sum:8e18fd794037fcd0beabe657f467be85 [weak]
    - Filesize:2036136 [weak]
   Last modification reported: Mon, 10 Feb 2020 13:29:31 +0000
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?__

**Comment by notr1ch** [comment]
This is a problem with your package lists or mirror, unrelated to OBS.
