### ISSUE TITLE
Native Linux Virtual Camera glitched out when no free v4l2 device slots available (w/ solution)

### ISSUE THREAD

**Issue by daviddeutsch** [obsproject/obs-studio#4200]
Operating system and version: Ubuntu 18.10
OBS Studio version: OBS Studio - 26.1.2-149-g951acf2df-modified (linux)

## Expected Behavior
I'm using a v4l2loopback to pick up a camera signal piped from gphoto2 (canon eos dslr connected via USB) via ffmpeg into v4l2. I want to share my obs output as a virtual camera to a video call.

## Current Behavior
Switching on "Start Virtual Camera" creates this situation:

![grafik](https://user-images.githubusercontent.com/630246/107132213-59e25b80-68dd-11eb-9242-16abad1c2fac.png)

but no error or anything in the stdout. 

## Steps to Reproduce
1. modprobe v4l2loopback devices=1
2. occupy /dev/video0 with a video input stream
3. start obs, use /dev/video0 in a v4l2 capture device source
4.  then "Start Virtual Camera"

I'm assuming that obs simply picks /dev/video0 for an output and that makes v4l2 freak out. I solved it by adding more devices but did not dig deeper into where precisely it went wrong, here.

## Solution
The solution for me was to restart v4l2loopback with more devices:

```
sudo modprobe -r v4l2loopback
sudo modprobe v4l2loopback devices=2
```

then, everything worked flawless, which was quite impressive.

## Suggestion
My suggestion here is to check whether there are free v4l2 devices available to send the virtual camera stream into. If there is a conflict, it could give a helpful pointer on how to add more devices.

**Comment by kkartaltepe** [comment]
Duplicate #3929

**Comment by daviddeutsch** [comment]
Oh woops, sorry. Somehow I came across that other issue but didn't bother to look into it because at that point, I didn't think it WAS a loopback conflict.

Anyhow, my bad!
