### ISSUE TITLE
OBS Studio does not keep the source resized output size after quitting and starting again

### ISSUE THREAD

**Issue by psads-git** [obsproject/obs-studio#4207]
## Platform

Operating system and version: Fedora 33
OBS Studio version: 26.1.2

## Expected Behavior

OBS Studio should keep the source output size after quitting and starting again OBS Studio.

## Current Behavior

If one resizes the output (source size), after quitting and starting again OBS Studio, the size of the resized output is not kept.

## Steps to Reproduce

1. Add a scene with video capture device (V4L2);
2. Apply the crop/pad filter;
3. Resize output (source size);
4. Quit OBS Studio;
5. Start OBS Studio.

**Comment by WizardCM** [comment]
After verifying, I also tested OBS 23.0.1, the version where this feature was introduced, and it didn't save the settings back then either.
