### ISSUE TITLE
OBS crashes at initial startup (after clean boot) if the scene-collection contains at least 1 WebBrowser scene item

### ISSUE THREAD

**Issue by sebionofrei** [obsproject/obs-studio#4208]
## Platform

Operating system and version: 10.0 build 19041 (release: 2004; revision: 746; 64-bit)
OBS Studio version: 26.1.1 (64-bit)

## Expected Behavior

The app is expected to start without any errors. However, it displays an error about it crashed. And either if choosing YES or NO at the question about copying the crash log to clipboard, the OBS dies.

## Current Behavior

After starting OBS, it shows information that it crashed (with yes/no options about copying the crash log to clipboard).
I've noticed in the UI that some sources related to a WEB-page overlay have failed to load
I'll also include the crash log on the bottom of this report.

## Steps to Reproduce

1. prepare a OBS scene-collection and in it, add at least 3-4 web-page overlays
2. close obs, and restart your PC
3. clean boot your PC
4. start OBS (eventually with profile and scene collection arguments (dunno if relevant though) .Either way it should load last used profile/collection
5. notice the error (hopefully it will show-up to you)

## Additional information

[Crash 2021-02-06 07-25-10.txt](https://github.com/obsproject/obs-studio/files/5944756/Crash.2021-02-06.07-25-10.txt)

**Comment by PatTheMav** [comment]
This is a long shot, but do you have audio monitoring enabled on any source? 😬

**Comment by sebionofrei** [comment]
Hello,

As someone sugested on Discord, this appeared to be a 3rd party bug. So I've contacted the developer of some obs-plugin, informed them about the issue and now its resolved.
