### ISSUE TITLE
OBS Crashes/Hangs when recording to NAS/Shared Folder

### ISSUE THREAD

**Issue by jammerxd** [obsproject/obs-studio#4217]
I am trying to record to my NAS shared folder over SMB or NFS.

I've ran as admin and non-admin. 

I've used network mapped drives and UNC paths - NFS and SMB.

For NFS:

Server:
I'm using the built-in windows tools for NFS. There's an NFS Sharing tab that allows me to specify anonymous users/unmapped users. 

For the client:
I'm using the built in windows nfs client under "Add or remove windows features" in the old control panel (NOT the settings app). I used the command `mount -o anon <ip>:/<share>  *` in a command prompt to mount the drive.

The message from NFS is "There is not sufficient disk space to continue recording"

## Platform
Operating system and version: Windows 10 Enterprise 2004
OBS Studio version:  26.1.1

## Expected Behavior
Recording should begin normally

## Current Behavior
OBS hangs and has to have all processes closed in task manager

## Steps to Reproduce

1. Set recording directory to NAS share
2. Click "Start Recording"
3. Click "Stop Recording"

## Additional information
Destination is a Windows Server 2019 Virtual Machine hosted on ESXi 6.7 with a PERC H700 PCI passthrough.

[2021-02-10 22-51-51.txt](https://github.com/obsproject/obs-studio/files/5963263/2021-02-10.22-51-51.txt)
[2021-02-10 22-56-08.txt](https://github.com/obsproject/obs-studio/files/5963264/2021-02-10.22-56-08.txt)

**Comment by WizardCM** [comment]
I was able to successfully write to a SMB share hosted by Ubuntu:
```
16:12:05.545: ==== Recording Start ===============================================
16:12:05.811: [ffmpeg muxer: 'simple_file_output'] Writing file '//wizardcm-nuc/wizardcm/Desktop/2021-02-11 16-12-05.mkv'...
16:12:10.004: User switched to scene 'Scene 2'
16:12:13.819: User switched to scene 'Scene'
16:12:20.348: User switched to scene 'Scene 2'
16:12:30.601: User switched to scene 'Scene'
16:12:32.350: [ffmpeg muxer: 'simple_file_output'] Output of file '//wizardcm-nuc/wizardcm/Desktop/2021-02-11 16-12-05.mkv' stopped
16:12:32.350: Output 'simple_file_output': stopping
16:12:32.350: Output 'simple_file_output': Total frames output: 1598
16:12:32.350: Output 'simple_file_output': Total drawn frames: 1590 (1592 attempted)
16:12:32.350: Output 'simple_file_output': Number of lagged frames due to rendering lag/stalls: 2 (0.1%)
16:12:32.350: Video stopped, number of skipped frames due to encoding lag: 2/1607 (0.1%)
16:12:32.366: ==== Recording Stop ================================================
```

You mention NFS - how are you connecting to the NFS share? Is it a mounted drive? Using what tool(s)?

**Comment by WizardCM** [comment]
The reporter confirmed in Discord that the issue was caused by their hosted VM.
