### ISSUE TITLE
directshow VirtualCam  crashes when set to different Format

### ISSUE THREAD

**Issue by sandercox** [obsproject/obs-studio#4218]
## Platform
Operating system and version: Windows 10 19041
OBS Studio version: 26.1.1

## Expected Behavior
Changing between different reported resolutions in the direct show filter works and proces different size images.

## Current Behavior
When you open the DirectShow filter and enumerate the optional resolutions for the media type, you can only accept the highest (1920x1080) when switching to a lower (scaled) output size (setup in OBS settings) the filter crashes within the image scaling

## Steps to Reproduce
1. Make sue OBS VIdeo settings have `Base Canvas Resolution` = 1920x1080 and Output scaled resolution to some lower number
2. Open software where you can set the resolution on the camera (I'm testing with Resolume Arena 7.3.2 (I know this version hasn't been released yet))
3. Switch the video setting and you get a crash in the scaler

It also happens without having to run OBS as long as it's setup right the default frame rendering has the same issue.

## Additional information
It seems that the VCamFilter is not setting up the scaler when the VideoFormat of the PIN is changes. I think the filter needs to observe the actual video format set on it's output pin and scale to that dst size instead of the input size. The scaler still uses a destination width/height of 1920/1080 instead of the lower setting causing memory corruption.

**Comment by notr1ch** [comment]
Likely #7529.

**Comment by notr1ch** [comment]
Please test https://github.com/obsproject/obs-studio/issues/7529#issuecomment-1276494786.

**Comment by gxalpha** [comment]
We believe that this is fixed by #7529, which is included in OBS 28.1. If this still is an issue in OBS 28.1, please open a new report with new, detailed reproduction step.
