### ISSUE TITLE
Display capture missing most frames when using display port, but not hdmi. Need display port for my configuration.

### ISSUE THREAD

**Issue by Musicamphetamine** [obsproject/obs-studio#4224]
Trying to use display capture in OBS using display port. Using a 1440p 144hz 1ms Monitor. Unsure if this is a settings configuration issue or a bug. Running very new parts so I am unsure if the program is not updated for my configuration, but this seems less likely. When I use display port as said, I cannot capture many frames, if any of my primary display. However when I switch to HDMI all issues are resolved. Unfortunately with my set up my only HDMI port in my gpu is occupied by my second monitor so display port is my only option. Beneath is as much info as I can provide with screen shots of my OBS setting and logs.

AMD Ryzen 9 5900X 12-Core Processor               3.70 GHz 
Windows 10 Home 20H2
OBS studio 26.1.1 (64 bit)

Log 

[2021-02-12 14-48-04.txt](https://github.com/obsproject/obs-studio/files/5974296/2021-02-12.14-48-04.txt)

![image](https://user-images.githubusercontent.com/78982425/107822627-07bd9200-6d44-11eb-9aa0-283085b7e651.png)

![image](https://user-images.githubusercontent.com/78982425/107822667-17d57180-6d44-11eb-88d9-0b1fe4e22c29.png)

![image](https://user-images.githubusercontent.com/78982425/107822719-2c196e80-6d44-11eb-8623-24954cdce1f6.png)

Any help is greatly appreciated.

**Comment by Fenrirthviti** [comment]
Please use the forums or Discord for support. We prefer to keep the issues to verified and confirmed reports with replication steps. Thanks!

**Comment by energizerfellow** [comment]
This is a duplicate of existing case #4164 and this information should have been added to the there, as was instructed in Discord.

https://github.com/obsproject/obs-studio/issues/4164
