### ISSUE TITLE
Drag and drop ignores file extension with caps.

### ISSUE THREAD

**Issue by dmail00** [obsproject/obs-studio#4236]
## Platform

Operating system and version: Windows 10
OBS Studio version: 26.1.1 (64 bit)

## Expected Behavior

When an image with a fille extension which is in capitals is dropped into the window it should show up.

## Current Behavior

Currently when an image with a capitalised file extension is dropped nothing is shown on screen.

## Steps to Reproduce

1. Rename an image file to use capitals for the file extension
2. Drop image onto screen
3.
4.

## Additional information

The file extensions  [1] are not being santitised [2] . After looking at the code, I also tried it with a video with the extension renamed to use caps, this video failed to load yet using small casing it loads. 
Three possible fixes for this issue which I assume effects all media types. One possilbility is to include the upper cap version in the array of extensions, second it to sanitise the extension before the strcmp. However the issue with this is that the code using a pointer to constant char so a copy would need to be made and then sanitised. Thirdly to use a platform specific function (POSIX strcasecmp, MS stricmp) to compare the extensions.

[1] https://github.com/obsproject/obs-studio/blob/cab32e7e67c2a78d10e0961f746ee7408978fb43/UI/window-basic-main-dropfiles.cpp#L17
[2] https://github.com/obsproject/obs-studio/blob/cab32e7e67c2a78d10e0961f746ee7408978fb43/UI/window-basic-main-dropfiles.cpp#L247

**Comment by WizardCM** [comment]
The simplest solution here is

https://github.com/obsproject/obs-studio/blob/cab32e7e67c2a78d10e0961f746ee7408978fb43/UI/window-basic-main-dropfiles.cpp#L250

Change to [astrcmpi](https://obsproject.com/docs/reference-libobs-util-dstr.html#c.astrcmpi). I'm quite sure the same change was made elsewhere for the same reason.
