### ISSUE TITLE
Build script issues on macOS

### ISSUE THREAD

**Issue by 297w** [obsproject/obs-studio#4237]
## Platform
Operating system and version: macOS Big Sur 11.2.1
OBS Studio version: 26.1.2

## Expected Behavior
An app-bundle that can open should be produced after building.

## Current Behavior
It appears to build correctly, but when creating an app bundle, it quits with an error:

` [OBS-Studio] Creating macOS app bundle `
` [OBS-Studio] Preparing OBS.app bundle `
`  + Copy binary and plugins... `
` mv: rename ./OBS.app/Contents/Resources/data/obs-scripting/_obspython.so to ./OBS.app/Contents/MacOS/_obspython.so: No such file or directory `
 ` + ERROR during build step: bundle app `

The app-bundle it ends up creating is only ~25MB and doesn't launch.

## Steps to Reproduce
1. Follow the build steps on the OBS wiki (./CI/full-build-macos.sh -b)

## Additional information
This issue seems to be related to the latest commit to the full-build-macos.sh. When I revert **only** that file back to the commit from 28 days ago ([CI: Fix CEF version for both Linux & macOS, PR# 4060](https://github.com/obsproject/obs-studio/commit/95c4db3bc61cbd2b893d4eeb598f37b4684ed288#diff-7d08e2aa3b0343852354ec8898489e67793cc9622d288495574eb5642cb58c02)), and then run `./CI/full-build-macos.sh -s -b` to use the existing build to produce an app-bundle, it works correctly, so it seems like there was something changed in between that caused an issue (though I don't know what).

**Comment by WizardCM** [comment]
If you previously built using the script, you will have to manually unset `DISABLE_PYTHON` to `OFF`.
