### ISSUE TITLE
User Interface on Arch Linux XFCE 4.16 has been disturbed after updating from XFCE4.14.

### ISSUE THREAD

**Issue by hamhaingaurav** [obsproject/obs-studio#4241]
## Platform

Operating system and version: Arch Linux XFCE 4.16
OBS Studio version: 26.1.2-1 (64 bit)

## Expected Behavior

It should show all the UI elements perfectly.

## Current Behavior

The UI is totally broken, I dont know the reason.

## Steps to Reproduce

Open OBS on Arch Linux XFCE 4.16 based system and open it, you will get to see the issue.

## Additional information

I am attaching the screen shot of the issue.
![obs](https://user-images.githubusercontent.com/34805677/107912706-0202bf00-6f85-11eb-9ddd-47f7540e31f5.png)

P.S. - OBS is working perfectly on the same system with different desktop environment, i have tested it on same system with Gnome and KDE Plasma, it was all good.

**Comment by kkartaltepe** [comment]
Disable fractional scaling before starting obs, or set your scaling factor to something greater than or  equal to 1.

**Comment by hamhaingaurav** [comment]
Thanks, it works perfectly on increasing the DPI settings in my  XFCE4 desktop environment. 
Just out of curiosity, I wanted to ask if there is any alternative ways to solve this issue without affecting my DPI settings.
