### ISSUE TITLE
Browser sources breaks Group transformation

### ISSUE THREAD

**Issue by lindenkron** [obsproject/obs-studio#4245]
## Platform

Operating system and version: Windows 10 Home 64-bit (10.0, Build 18363)
OBS Studio version: 26.1.1, 64-bit

## Expected Behavior
Nothing, I assume it should keep its properties and not go to 90001.

## Current Behavior
Goes to 90001.

## Steps to Reproduce
1. Clean Scene Collection.
2. Create Scene
3. Create Group
4. Create browser Source > Press Okay
5. Go to Group Transformation, change Positional Alignment to 'center'
6. Drag browser source into group.
7. Watch in despair as your group transformation is now all 90001s.

## Additional information
https://streamable.com/o2emrk
Preview of said issue.

**Comment by flaeri** [comment]
Confirmed.

Slight additional info:
5. One the group, go to Group Transformation, change Positional Alignment to 'center'

**Comment by farhanjiwani** [comment]
Confirmed by reproduction of issue.
OBS Studio 26.1.1 (64-bit)

**Comment by lindenkron** [comment]
28.1.2 Update - Still broken.

Specifically for Groups and their Transformation - changing either '**Positional Alignment**' or '**Bounding Box Type**' on a group, then dragging a browser source _into_ the group will set its size to 90001, effectively breaking the group.

It also appears that there's various ways to break **other** source types than Browser Sources, such as Images.

Changing a groups '**Positional Alignment**' to 'Center', then dragging a default image into yields this:
https://streamable.com/y4nz65
Changing a groups '**Bounding Box**', then dragging a default media source into it, yields the source just disappearing, but without the '90001' 

Outside of Positional Alignment & Bounding Box breaking various sources dragged into them if set, **Position** also breaks the dragged in sources. If you:
- Create a **New group**
- Set the position to **200px** **0px**
- Drag a Media Source into the group
You get this:
https://i.imgur.com/aBJkZug.png

A "cropped" source, that isn't actually cropped.

I believe Positional Alignment & Bounding Box issues applies mostly to all other sources. At least I experienced the various issues with Color Source, Media Source, Image Source, Browser Source.

**Comment by Fenrirthviti** [comment]
Closing as stale. If this is still an issue please open a new issue with updated reproduction steps on the latest version of OBS.
