### ISSUE TITLE
Windows OBS in Windows ARM runs well, but no video capture sources work

### ISSUE THREAD

**Issue by foxgeere** [obsproject/obs-studio#4248]
## Platform

Operating system and version: Windows 10 ARM Build 21301.rs.prerelease.210123-1645 (but all versions before as well)
OBS Studio version: 26.1.1 (64 Bit)

## Expected Behavior
Create scene
Add video capture device / camera / capture card
See preview of video in properties preview window
Be able to use video source in scene

## Current Behavior
Select any input (have tried different USB cameras, Capture cards including Elgato 4k etc)
See properties and dropdown change as expected
Do NOT see any video feed/input. Black screen remains.

## Steps to Reproduce

1. Install Windows ARM
2. Install OBS
3. Add new 'video capture device' source
4. Choose any video camera / usb input / video source

## Additional information
Have installed other software such as Zoom and cameras are working fine. So they are present and correctly driven within windows without any problems. Only OBS is having problems showing any video input.

Have tried changing all properties for all cameras and inputs but no difference is made.

**Comment by Fenrirthviti** [comment]
Are you self-compiling? We don't offer ARM as a currently supported platform.

**Comment by WizardCM** [comment]
Please include a session log.

This is using the x64 emulation I assume?

Additionally, try this:

> Windows 10's April 2018 Update adds new privacy settings for microphones and cameras, which can block them from use. The camera privacy settings also affect capture cards. These settings are opt-in. To allow apps like OBS to use your microphone or camera again, follow these steps.
> 1) Open the Settings app.
> 2) Go to Privacy -> Camera for capture cards and webcams, and turn "Allow apps to access your camera" on.

**Comment by foxgeere** [comment]
No. This is the regular windows OBS build. It runs using emulation. 

All features are working wonderfully and at speed. The only error is the video issue described here. Fixing it would allow full and fast use on arm installs without the need for a specific arm build as far as I can currently tell. 

So this is trying to progress that use case and support the growing number of arm installs without huge efforts if possible. 

I do understand if you opt to close the issue. But I remain hopeful.

**Comment by foxgeere** [comment]
> Please include a session log.
> 
> This is using the new x64 emulation I assume?
> 
> Additionally, try this:
> 
> > Windows 10's April 2018 Update adds new privacy settings for microphones and cameras, which can block them from use. The camera privacy settings also affect capture cards. These settings are opt-in. To allow apps like OBS to use your microphone or camera again, follow these steps.
> > 
> > 1. Open the Settings app.
> > 2. Go to Privacy -> Camera for capture cards and webcams, and turn "Allow apps to access your camera" on.

Thanks. I appreciate the pointer. I have done all of this. As noted camera and inputs all working fine in other software / zoom. And all properties for each camera correctly read into the OBS properties window. It simply doesn’t render the actual video view.

**Comment by foxgeere** [comment]
I will get a session log for you and attach in due course. Sorry for the the oversight there.

**Comment by foxgeere** [comment]
I hope this has something useful. Will double check I followed instructions correctly.

https://obsproject.com/logs/EMpcNKSVuT7VQaht

**Comment by foxgeere** [comment]
Aha
I imagine this is the problem

DShow: Failed to create ICaptureGraphBuilder2 (0x800700C1): %1 is not a valid Win32 application

**Comment by Fenrirthviti** [comment]
I also see `Adapter 0: Parallels Display Adapter (WDDM)`

Is this being run in a VM? OBS does not typically work very well inside VMs, and we don't support running it in a VM.

**Comment by foxgeere** [comment]
I can confirm it is. And I understand the position entirely. I guess given other apps worked I was hopeful I could move to the windows version of OBS due to missing features on the Mac builds (e.g. no GDI, No StreamFX etc etc).

I full anticipate you'll close this issue for the time being. Thank you for at least giving it some attention. Fingers crossed for the future.

**Comment by WizardCM** [comment]
Heads up: this is apparently fixed in the latest Insider build on ARM64.

**Comment by foxgeere** [comment]
I was just heading here to note this fix. Will be doing full testing tomorrow but I can confirm capture/camera absolutely show up now.
