### ISSUE TITLE
srt: "stream key" field is discarded, should be applied to streamid parameter

### ISSUE THREAD

**Issue by iameli** [obsproject/obs-studio#4250]
## Platform

Operating system and version: macOS 10.15.7
OBS Studio version: 25.0.8

## Expected Behavior
If streaming over SRT, OBS's "Stream Key" parameter should be applied to the SRT `streamid` field. This makes sense semantically — SRT doesn't have the concept of a "Path" like RTMP does, but the `streamid` field fulfills a similar purpose. From [the pertinent docs](https://github.com/Haivision/srt/blob/master/docs/AccessControl.md):

> As of SRT version 1.3.3 a callback can be registered on the listener socket for an application to make decisions on incoming caller connections. This callback, among others, is provided with the value of Stream ID from the incoming connection. Based on this information, the application can accept or reject the connection, select the desired data stream, or set an appropriate passphrase for the connection.

The docs go on to explain a key/value formatting convention for the field which definitely exceeds the scope of OBS's connection picker thing.

To avoid this being a backwards-breaking change for folks that already have `streamid` in their URL, OBS should probably not overwrite the `streamid` in the field. That would involve parsing the URL in the other field and playing nicely with it.

## Current Behavior
So instead of this relatively elegant UX:

![image](https://user-images.githubusercontent.com/257909/108306056-3a122980-7160-11eb-868a-da0b10804dbf.png)

I have to do this:

![image](https://user-images.githubusercontent.com/257909/108306097-54e49e00-7160-11eb-90fe-259f0924b007.png)

**Comment by energizerfellow** [comment]
How about modifying the `Stream Key` label to `Stream Key (Stream ID)` with a pulldown next to it with the options `URL` and `Embedded`? This way the URL option will automatically attach the `?streamid=my_stream_key`.

**Comment by WizardCM** [comment]
A quick look at this page's code tells me that we don't currently do _any_ string/url parsing or manipulation on the server URL, so this'd be a whole new feature essentially. The cleanest functions we could use for this is from [QUrlQuery](https://doc.qt.io/qt-5/qurlquery.html), which we already use in the drag-and-drop link capability.

**Comment by eric** [comment]
There could definitely be some usability improvements to providing fields for the most used query params for SRT, but it seems like that would be a bigger project.

**Comment by wfjsw** [comment]
Note that this might cause some significant security issue since the stream key got its way into the log file.

**Comment by RytoEX** [comment]
Possibly fixed by #7136. Please test artifacts from that PR.
