### ISSUE TITLE
Obs-Studio with error message on Fedora 33 with Deepin 15.11

### ISSUE THREAD

**Issue by serial02** [obsproject/obs-studio#4251]
Hello everybody

I installed Obs-Studio on Fedora 33 with Deepin 15.11 and I get the following error message:

![DeepinScreenshot_select-area_20210218121507](https://user-images.githubusercontent.com/32621790/108388656-9b340e80-71ed-11eb-8c8f-8c52f007d247.png)

I tried to open it from the terminal and the same error occurs:
Any suggestions on what needs to be done to resolve this issue?

https://pastebin.com/aVzA6Caz

https://pastebin.com/raw/aVzA6Caz

**Comment by notr1ch** [comment]
Please use the forums or Discord for support. Note that Fedora 33 with Deepin 15.11 is not an officially supported platform.

**Comment by Gol-D-Ace** [comment]
Also the Intel GPU in this cpu doesn't support the necessary OpenGL Version.
Max support is OpenGL 2.1 while OBS requires at least 3.3
