### ISSUE TITLE
[libdshowcapture] Should we check HRESULT with 0X800705AA for "Result::InUse" ?

### ISSUE THREAD

**Issue by wangshaohui1314** [obsproject/obs-studio#4255]
## Platform

Operating system and version: WIN10 64
OBS Studio version: OBS 26.XX

## Steps to Reproduce

1. connect a camera, make sure it is using by another app
2. create camera source in OBS and check error code returned by "Result HDevice::Start()"
3. for some device, Result::InUse is not returned

## Additional information

Now Result::InUse is only set when HRESULT is 0x8007001F.
But I find some cameras are returning ERROR_NO_SYSTEM_RESOURCE (0X800705AA).
Should we check HRESULT also with 0X800705AA for "Result::InUse" ?

![1613700834](https://user-images.githubusercontent.com/18413354/108447679-40f18700-729b-11eb-988f-b9cd5b441f57.png)

**Comment by wangshaohui1314** [comment]
@jp9000 @jpark37

**Comment by dodgepong** [comment]
Might be better to submit a pull request for this if it sounds like you have a solution in mind.

**Comment by WizardCM** [comment]
As this code does nothing but print an error in the log, I would say this is not a bug. Additionally, `ERROR_NO_SYSTEM_RESOURCE` does not mean the device is in use - it more often means that the USB hub the webcam is connected to cannot provide enough power to the device.
