### ISSUE TITLE
Linux v4l2 virtual camera not starting

### ISSUE THREAD

**Issue by nachobacanful** [obsproject/obs-studio#4256]
## Platform
Operating system and version: `Linux 5.4.89-1-MANJARO`
OBS Studio version: `26.1.2-35-gbb6b1e53f (snap)`

## Expected Behavior
Clicking "Start Virtual Camera" under the controls panel should start the virtual camera. A prompt should appear asking to modprobe `v4l2loopback`. Starting the virtual can makes the output of OBS available to other programs as a camera. Should also be found under `/dev/videoX`.

## Current Behavior
When clicking "Start Virtual Camera" nothing happens.

## Steps to Reproduce
1. Start OBS
2. Click "Start Virtual Camera" from the Controls panel

## Additional information
If I run OBS from a shell I get the following error:
```
sh: 1: pkexec: not found
```
The problem is that for some reason `pkexec` is not in path. I can execute `pkexec` just fine from a shell as a regular user (because it is in my path).

In my case if I run `which pkexec ` I get `/usr/bin/pkexec`. This just means it cant find that binary. 
By comparing the current code https://github.com/obsproject/obs-studio/blob/81a89e689fb36bd24b47c5806d09438e3d82ece3/plugins/linux-v4l2/v4l2-output.c#L70 to this older commit https://github.com/obsproject/obs-studio/blob/b9a1516254f722fc9367140e28ade7ec8b5539d5/plugins/linux-v4l2/v4l2-output.c#L56 I can see that there was a similar issue at some point and it was fixed by adding `sbin` to PATH. In my case is `/usr/bin` that needs to be added to path as well. 
making the new line look like this:
```c
"PATH=\"$PATH:/sbin:/usr/bin\" pkexec modprobe v4l2loopback exclusive_caps=1 card_label='OBS Virtual Camera' && sleep 0.5"); 
```
it is very odd to me that `/usr/bin` might note be in path when executing OBS. From a shell, that directory is part of my path.

I personally have not compiled OBS myself, so I have not been able to truly troubleshoot this further.
### Temporary workaround
I execute `modprobe v4l2loopback exclusive_caps=1 card_label='OBS Virtual Camera'` manually in a separate shell. Then I click start virtual camera, and everything works after that.

**Comment by kkartaltepe** [comment]
snap is not supported. Manually load kernel modules if you want to use a sandboxed environment.
