### ISSUE TITLE
OBS Linux Window Capture is not working for Browser based apps (VSCode, Chrome)

### ISSUE THREAD

**Issue by pranshuchittora** [obsproject/obs-studio#4261]
## Platform

Ubuntu 20, OBS Lastest

Operating system and version:
OBS Studio version:

## Expected Behavior
Window capture for Browser shouldn't show black sreen

## Current Behavior
Black screen for Chrome, VSCode

## Steps to Reproduce
1. Selecte WindowCapture
2. Select Chrome
3.
4.

**Comment by Fenrirthviti** [comment]
Please provide a session log and further environment information, what compositor are you using? What desktop manager? X11/Wayland?

**Comment by kkartaltepe** [comment]
Please use discord or the forums for support questions.
