### ISSUE TITLE
cdn-fastly.obsproject.com lacks IPv6 support

### ISSUE THREAD

**Issue by ikomwrestling** [obsproject/obs-studio#4270]
## Platform

Operating system and version: Windows 10 2004
OBS Studio version: 26.1.1

## Expected Behavior
User should able to download OBS installer through a IPv6 connection.

## Current Behavior
cdn-fastly.obsproject.com lacks IPv6 addresses and thus resources (OBS installer) from it can't be received using IPv6.

## Additional information
Since the CDN served by Fastly, which has great IPv6 support, it should hopefully be a simple fix by asking Fastly support to enable IPv6 on the map, as per their [IPv6 documentation](https://docs.fastly.com/en/guides/ipv6-support).

**Comment by notr1ch** [comment]
We've enabled IPv6 support at Fastly. It may take up to a day to reflect this due to the DNS TTL.
