### ISSUE TITLE
The system cannot find the extension

### ISSUE THREAD

**Issue by UnixCro** [obsproject/obs-studio#4272]
`kextstat |grep -v com.apple`

I found the virtual camera here. `'/Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin`' Just what is strange to me where is the kernel extension, because the kernel can only connect software modules with the hardware?

Thank you for an answer

**Comment by WizardCM** [comment]
Please fill in the issue template.

**Comment by PatTheMav** [comment]
We do not use Kernel Extensions for the virtual camera functionality - Apple discourages the use of Kernel Extensions moving forward anyway.

Instead the plugin is made available as a DAL plugin which is loaded by the host application once they access CMIO functionality. Apple applies additional code signing checks here, only loading DAL plugins by either the same developer as the host application or from an additional allowlist specified by the app developer.
