### ISSUE TITLE
The Text will hide when copying from group

### ISSUE THREAD

**Issue by iesvme** [obsproject/obs-studio#4274]
## Platform

Operating system and version: win10 1809
OBS Studio version: 26.1.1

## Current Behavior

Sorry, That's source toggle of lua script's reason.

## Steps to Reproduce

![obs-bug2](https://user-images.githubusercontent.com/16969250/109135478-1703fd00-7792-11eb-91d5-fbf057916ea3.gif)

**Comment by WizardCM** [comment]
Please fill in the issue template.
