### ISSUE TITLE
doesn't compile on recent linux

### ISSUE THREAD

**Issue by darvin** [obsproject/obs-studio#4275]
[ 71%] Built target _obspython
[ 72%] Built target obslua
[ 76%] Built target frontend-tools
[ 76%] Linking CXX executable obs
/usr/bin/ld: cannot find -lQt5::GuiPrivate
collect2: error: ld returned 1 exit status
make[2]: *** [UI/CMakeFiles/obs.dir/build.make:1386: UI/obs] Error 1

**Comment by GeorgesStavracas** [comment]
You need `qtbase5-private-dev` or equivalent to build the master branch of OBS Studio.
