### ISSUE TITLE
"Capture any fullscreen application" doesn't work...

### ISSUE THREAD

**Issue by PaulNevada** [obsproject/obs-studio#4276]
This feature shows BlackScreen at:

1. Win7 Pro (SP1, x64);
2. OBS 26.1.1;
3. Steam Game, not a Steam Game - nevermind;
4. Have tried "Ruan as administrator".

PS: Also, I thought "Display Capture" will capture everything (it'd be nice to for an ez start-to-go-with) and it doesn't as well...

**Comment by RytoEX** [comment]
Please follow the issue template when opening issues on GitHub.

**Comment by notr1ch** [comment]
Use the forums or Discord for support.
