### ISSUE TITLE
Black preview screen in Linux Manjaro 20.1

### ISSUE THREAD

**Issue by abdoulayegk** [obsproject/obs-studio#4279]
I am trying to use obs to record video but since I install it it's showing only black screen I try to uncomment the wayland = False from the custom.conf and it crash my system for the first time I was using Ubuntu 20.04LTS that is even the reason I switch to manjaro and I am getting the same error can anyone help me out with this issue.

**Comment by Fenrirthviti** [comment]
In the future, please make sure when posting an issue to a repository, that you read the issue template instead of deleting it.

Use the forums or Discord for support, thanks!
