### ISSUE TITLE
crashes with logs on the raspberry pi 4

### ISSUE THREAD

**Issue by darvin** [obsproject/obs-studio#4280]
error: X Error: GLXBadDrawable, Major opcode: 151, Minor opcode: BadAlloc (insufficient resources for operation), Serial: 19246
error: Failed to fetch parent window geometry!
error: Failed to fetch parent window geometry!
error: Failed to fetch parent window geometry!
error: Failed to fetch parent window geometry!
error: X Error: GLXBadDrawable, Major opcode: 151, Minor opcode: BadAlloc (insufficient resources for operation), Serial: 19251
error: Failed to fetch parent window geometry!
error: Failed to fetch parent window geometry!
error: Failed to fetch parent window geometry!
error: Failed to fetch parent window geometry!
error: X Error: GLXBadDrawable, Major opcode: 151, Minor opcode: BadAlloc (insufficient resources for operation), Serial: 19256
error: Failed to fetch parent window geometry!
error: Failed to fetch parent window geometry!
error: Failed to fetch parent window geometry!
error: Failed to fetch parent window geometry!
error: X Error: GLXBadDrawable, Major opcode: 151, Minor opcode: BadAlloc (insufficient resources for operation), Serial: 19261
error: Failed to fetch parent window geometry!
error: Failed to fetch parent window geometry!
error: Failed to fetch parent window geometry!
error: Failed to fetch parent window geometry!
error: X Error: GLXBadDrawable, Major opcode: 151, Minor opcode: BadAlloc (insufficient resources for operation), Serial: 19266
error: Failed to fetch parent window geometry!
error: Failed to fetch parent window geometry!
error: Failed to fetch parent window geometry!
error: Failed to fetch parent window geometry!
error: X Error: GLXBadDrawable, Major opcode: 151, Minor opcode: BadAlloc (insufficient resources for operation), Serial: 19271
error: Failed to fetch parent window geometry!
error: Failed to fetch parent window geometry!
error: Failed to fetch parent window geometry!
error: Failed to fetch parent window geometry!
error: X Error: GLXBadDrawable, Major opcode: 151, Minor opcode: BadAlloc (insufficient resources for operation), Serial: 19276
error: Failed to fetch parent window geometry!
error: Failed to fetch parent window geometry!
error: Failed to fetch parent window geometry!
error: Failed to fetch parent window geometry!
error: X Error: GLXBadDrawable, Major opcode: 151, Minor opcode: BadAlloc (insufficient resources for operation), Serial: 19281
info: ==== Shutting down ==================================================
error: Failed to fetch parent window geometry!
error: Failed to fetch parent window geometry!
error: Failed to fetch parent window geometry!
error: Failed to fetch parent window geometry!
error: X Error: GLXBadDrawable, Major opcode: 151, Minor opcode: BadAlloc (insufficient resources for operation), Serial: 19286
error: Failed to fetch parent window geometry!
error: Failed to fetch parent window geometry!
error: Failed to fetch parent window geometry!
error: Failed to fetch parent window geometry!
error: X Error: GLXBadDrawable, Major opcode: 151, Minor opcode: BadAlloc (insufficient resources for operation), Serial: 19291
info: pulse-input: Stopped recording from 'alsa_output.usb-Razer_Razer_Ripsaw_HD-Game_Capture_Card-00.analog-stereo.monitor'
info: pulse-input: Got 20953 packets with 6414683 frames
info: All scene data cleared
info: ------------------------------------------------
error: Failed to fetch parent window geometry!
error: Failed to fetch parent window geometry!
error: Failed to fetch parent window geometry!
error: Failed to fetch parent window geometry!
error: X Error: GLXBadDrawable, Major opcode: 151, Minor opcode: BadAlloc (insufficient resources for operation), Serial: 19296
info: [rtmp stream: 'simple_stream'] User stopped the stream
info: Output 'simple_stream': stopping
info: Output 'simple_stream': Total frames output: 0
info: Output 'simple_stream': Total drawn frames: 3399 (3421 attempted)
info: Output 'simple_stream': Number of lagged frames due to rendering lag/stalls: 22 (0.6%)
info: libfdk_aac encoder destroyed
info: [Scripting] Total detached callbacks: 0
info: Freeing OBS context data
info: == Profiler Results =============================
info: run_program_init: 2072.46 ms
info:  ┣OBSApp::AppInit: 10.873 ms
info:  ┃ ┗OBSApp::InitLocale: 6.392 ms
info:  ┗OBSApp::OBSInit: 1545.67 ms
info:    ┣obs_startup: 2.075 ms
info:    ┗OBSBasic::OBSInit: 1372.46 ms
info:      ┣OBSBasic::InitBasicConfig: 0.387 ms
info:      ┣OBSBasic::ResetAudio: 1.063 ms
info:      ┣OBSBasic::ResetVideo: 514.246 ms
info:      ┣OBSBasic::InitOBSCallbacks: 0.022 ms
info:      ┣OBSBasic::InitHotkeys: 0.128 ms
info:      ┣obs_load_all_modules: 614.014 ms
info:      ┃ ┣obs_init_module(decklink-captions.so): 0.184 ms
info:      ┃ ┣obs_init_module(decklink-ouput-ui.so): 2.141 ms
info:      ┃ ┣obs_init_module(frontend-tools.so): 281.439 ms
info:      ┃ ┣obs_init_module(image-source.so): 0.023 ms
info:      ┃ ┣obs_init_module(linux-alsa.so): 0.008 ms
info:      ┃ ┣obs_init_module(linux-capture.so): 1.957 ms
info:      ┃ ┣obs_init_module(linux-decklink.so): 1.09 ms
info:      ┃ ┣obs_init_module(linux-jack.so): 0.006 ms
info:      ┃ ┣obs_init_module(linux-pulseaudio.so): 0.006 ms
info:      ┃ ┣obs_init_module(linux-v4l2.so): 49.191 ms
info:      ┃ ┣obs_init_module(obs-ffmpeg.so): 0.791 ms
info:      ┃ ┃ ┗nvenc_check: 0.585 ms
info:      ┃ ┣obs_init_module(obs-filters.so): 0.097 ms
info:      ┃ ┣obs_init_module(obs-libfdk.so): 0.007 ms
info:      ┃ ┣obs_init_module(obs-outputs.so): 0.03 ms
info:      ┃ ┣obs_init_module(obs-transitions.so): 0.027 ms
info:      ┃ ┣obs_init_module(obs-vst.so): 0.014 ms
info:      ┃ ┣obs_init_module(obs-x264.so): 0.009 ms
info:      ┃ ┣obs_init_module(rtmp-services.so): 2.615 ms
info:      ┃ ┣obs_init_module(sndio.so): 0.011 ms
info:      ┃ ┣obs_init_module(text-freetype2.so): 0.052 ms
info:      ┃ ┗obs_init_module(vlc-video.so): 17.731 ms
info:      ┣OBSBasic::ResetOutputs: 0.55 ms
info:      ┣OBSBasic::CreateHotkeys: 0.117 ms
info:      ┣OBSBasic::InitService: 6.615 ms
info:      ┣OBSBasic::InitPrimitives: 0.283 ms
info:      ┗OBSBasic::Load: 79.28 ms
info: obs_hotkey_thread(25 ms): min=0.243 ms, median=0.524 ms, max=31.049 ms, 99th percentile=9.892 ms, 99.9607% below 25 ms
info: audio_thread(Audio): min=0.001 ms, median=0.566 ms, max=105.785 ms, 99th percentile=1.684 ms
info:  ┗receive_audio: min=0.005 ms, median=0.341 ms, max=18.65 ms, 99th percentile=0.859 ms, 0.898693 calls per parent call
info:    ┣buffer_audio: min=0.001 ms, median=0.003 ms, max=1.478 ms, 99th percentile=0.023 ms
info:    ┗do_encode: min=0.135 ms, median=0.328 ms, max=13.908 ms, 99th percentile=0.818 ms
info:      ┗encode(simple_aac): min=0.131 ms, median=0.229 ms, max=7.134 ms, 99th percentile=0.581 ms
info: obs_graphics_thread(33.3333 ms): min=3.074 ms, median=6.863 ms, max=1174.47 ms, 99th percentile=26.175 ms, 99.3039% below 33.333 ms
info:  ┣tick_sources: min=0.002 ms, median=0.022 ms, max=0.545 ms, 99th percentile=0.067 ms
info:  ┣output_frame: min=2.839 ms, median=3.869 ms, max=1172.73 ms, 99th percentile=8.335 ms
info:  ┃ ┣gs_context(video->graphics): min=2.837 ms, median=3.866 ms, max=1172.72 ms, 99th percentile=8.331 ms
info:  ┃ ┃ ┣render_video: min=0.052 ms, median=0.086 ms, max=1172.67 ms, 99th percentile=0.197 ms
info:  ┃ ┃ ┃ ┣render_main_texture: min=0.042 ms, median=0.076 ms, max=0.761 ms, 99th percentile=0.16 ms
info:  ┃ ┃ ┃ ┣render_output_texture: min=3.283 ms, median=5.15 ms, max=482.916 ms, 99th percentile=482.916 ms, 0.00335138 calls per parent call
info:  ┃ ┃ ┃ ┣render_convert_texture: min=269.928 ms, median=314.93 ms, max=677.469 ms, 99th percentile=677.469 ms, 0.00335138 calls per parent call
info:  ┃ ┃ ┃ ┗stage_output_texture: min=7.983 ms, median=9.625 ms, max=22.558 ms, 99th percentile=22.558 ms, 0.00335138 calls per parent call
info:  ┃ ┃ ┣gs_flush: min=0.007 ms, median=3.696 ms, max=25.864 ms, 99th percentile=7.594 ms
info:  ┃ ┃ ┗download_frame: min=0.001 ms, median=0.016 ms, max=0.029 ms, 99th percentile=0.029 ms, 0.00335138 calls per parent call
info:  ┃ ┗output_video_data: min=0.695 ms, median=3.934 ms, max=5.562 ms, 99th percentile=5.562 ms, 0.00309358 calls per parent call
info:  ┗render_displays: min=0.02 ms, median=2.37 ms, max=132.959 ms, 99th percentile=14.559 ms
info: video_thread(video): min=0.003 ms, median=339.613 ms, max=1326.09 ms, 99th percentile=1326.09 ms
info:  ┗receive_video: min=3.063 ms, median=22.467 ms, max=230.256 ms, 99th percentile=140.693 ms, 9.08333 calls per parent call
info:    ┗do_encode: min=3.059 ms, median=22.463 ms, max=230.249 ms, 99th percentile=140.689 ms
info:      ┗encode(simple_h264_stream): min=3.03 ms, median=22.311 ms, max=229.955 ms, 99th percentile=140.652 ms
info: =================================================
info: == Profiler Time Between Calls ==================
info: obs_hotkey_thread(25 ms): min=25.328 ms, median=25.651 ms, max=56.145 ms, 31.9003% within ±2% of 25 ms (0% lower, 68.0997% higher)
info: obs_graphics_thread(33.3333 ms): min=6.64 ms, median=33.333 ms, max=1174.52 ms, 96.983% within ±2% of 33.333 ms (1.39247% lower, 1.62455% higher)
info: =================================================
info: Number of memory leaks: 0

**Comment by notr1ch** [comment]
`BadAlloc (insufficient resources for operation)`

This would imply the Pi 4 does not have enough resources to run OBS. In any case, such a device is woefully underpowered for real time video composition and encoding.
