### ISSUE TITLE
wayland flatpak does not allow Desktop Screencast Wayland  screencapture to update

### ISSUE THREAD

**Issue by ilippert** [obsproject/obs-studio#4282]
Operating system and version: fedora 33
OBS Studio version:

I use OBS flatpak commit
3f2cf2013982261626657eafd8b989a458d782f5a7a598040288bd6079a6f766

## Expected Behavior
If I use the Desktop Screencast Wayland/X11, select a display/window via the gnome screen share manager, the screencapture should work, i.e. capture should be updated.

## Current Behavior
the capture does not update

I checked older commits - in efbd5d2fc438ae7dd6602fca6beeba1e849cd920134d5c1339cbf040f48ab958 from flathub the behaviour is as expected.

sorry, this is the first time I report something here. Please let me know where to look precisely for more information that I should add here.

**Comment by GeorgesStavracas** [comment]
It seems you're using Flathub's OBS Studio. Please move this ticket to https://github.com/flathub/com.obsproject.Studio/issues.

**Comment by notr1ch** [comment]
Closing this as the flatpak isn't officially maintained.

**Comment by ilippert** [comment]
thanks, for reference. it is now reported at https://github.com/flathub/com.obsproject.Studio/issues/101
