### ISSUE TITLE
Obs can't accurately identify multiple usb capture cards of the same model.

### ISSUE THREAD

**Issue by iesvme** [obsproject/obs-studio#4283]
## Platform

Operating system and version: win10 1808
OBS Studio version: 26.1.1
OBS Log file:

## Current Behavior

Obs can't accurately identify multiple usb capture cards of the same model. Because it will identify according to the order of booting, rather than manually setting the identification.

**Comment by iesvme** [comment]
because they have the same device name, OBS confused.

**Comment by Fenrirthviti** [comment]
This is not something we can fix, please contact the device manufacturer and have them provide drivers that support multiple devices of the same model.
