### ISSUE TITLE
Virtual webcam feature not available after building OBS-Studio with VIRTUALCAM_GUID from latest source code on Windows 10

### ISSUE THREAD

**Issue by alokmahor** [obsproject/obs-studio#4286]
## Platform

Operating system and version: Windows 10, Version 2004 (OS Build 19041.685)
OBS Studio version: Latest Master pull
OBS Log file:

## Expected Behavior
I should be able to see button to enable virtual webcam at right bottom menu

## Current Behavior
After building from latest source code I am not able to see button to enable virtual webcam at right bottom menu. Here is image link https://i.stack.imgur.com/Vr5aQ.png

## Steps to Reproduce

1. Get clone of repo on windows 10
2. `mkdir build64`
3. `cmake -G "Visual Studio 16 2019" -A x64 -S . -B build64 -DDepsPath=C:\Users\alokm\Downloads\dependencies2019\win64 -DQTDIR=C:\Qt\5.15.2\msvc2019_64 -DVIRTUALCAM_GUID=e61ba6f1-ac3a-47b6-aaee-b537088061e4 -DCMAKE_CONFIGURATION_TYPES=Release`
4. `cmake --build .\build64 --config Release`
5.  `regsvr32.exe build64\rundir\Release\data\obs-plugins\win-dshow\obs-virtualcam-module64.dll`
6.  Open `build64\rundir\Release\bin\64bit\obs64.exe` (Virtual camera button is not present)

**Comment by Fenrirthviti** [comment]
Please use our Discord for assistance building OBS.

**Comment by alokmahor** [comment]
First I posted these steps in discord only. 
And in official https://github.com/obsproject/obs-studio/wiki/Install-Instructions#windows-build-directions use of `VIRTUALCAM_GUID` is not mentioned anywhere so I guess `windows-build-directions` should be updated. So we should keep this issue open.

**Comment by RytoEX** [comment]
> 
> 
> @Fenrirthviti First I posted these steps in discord only. I did not get any reply on that.
> And in official https://github.com/obsproject/obs-studio/wiki/Install-Instructions#windows-build-directions use of `VIRTUALCAM_GUID` is not mentioned anywhere so I guess `windows-build-directions` should be updated. So we should keep this issue open.

I've added a note in the optional CMake variables section about VIRTUALCAM_GUID, so this can remain closed.  For future reference, the wiki is publicly editable, so anyone is welcome to improve the build instructions.

**Comment by alokmahor** [comment]
Thank you @RytoEX for updating wiki.
Could you please validate my building steps mentioned in this issue? Are those steps fine to have virtual camera enabled in OBS Studio?
