### ISSUE TITLE
VLC media player导入RTSp串流出现问题

### ISSUE THREAD

**Issue by xisohi** [obsproject/obs-studio#4288]
## Platform

Operating system and version:Windows Version: 10.0 Build 18363 (release: 1909; revision: 1379; 64-bit)
OBS Studio version:OBS 26.1.1 (64-bit, windows)
VLC media player version:3.0.12
OBS Log file:09:30:53.930: CPU Name: AMD Ryzen 7 4800H with Radeon Graphics         
09:30:53.930: CPU Speed: 2895MHz
09:30:53.930: Physical Cores: 8, Logical Cores: 16
09:30:53.930: Physical Memory: 15741MB Total, 10608MB Free
09:30:53.930: Windows Version: 10.0 Build 18363 (release: 1909; revision: 1379; 64-bit)
09:30:53.930: Running as administrator: false
09:30:53.930: Aero is Enabled (Aero is always on for windows 8 and above)
09:30:53.931: Windows 10 Gaming Features:
09:30:53.931: 	Game DVR: On
09:30:53.935: Sec. Software Status:
09:30:53.938: 
09:30:53.939: 
09:30:53.940: Current Date/Time: 2021-03-01, 09:30:53
09:30:53.940: Browser Hardware Acceleration: true
09:30:53.940: Portable mode: false
09:30:54.759: OBS 26.1.1 (64-bit, windows)
09:30:54.759: ---------------------------------
09:30:54.837: ---------------------------------
09:30:54.837: audio settings reset:
09:30:54.837: 	samples per sec: 48000
09:30:54.837: 	speakers:        2
09:30:54.860: ---------------------------------
09:30:54.860: Initializing D3D11...
09:30:54.860: Available Video Adapters: 
09:30:54.864: 	Adapter 0: NVIDIA GeForce GTX 1650 Ti
09:30:54.864: 	  Dedicated VRAM: 4154458112
09:30:54.864: 	  Shared VRAM:    3958016000
09:30:54.864: 	  PCI ID:         10de:1f95
09:30:54.865: 	  Driver Version: 27.21.14.6140
09:30:54.865: 	  output 0: pos={0, 0}, size={1920, 1080}, attached=true, refresh=60, name=
09:30:54.869: Loading up D3D11 on adapter NVIDIA GeForce GTX 1650 Ti (0)
09:30:54.954: D3D11 loaded successfully, feature level used: b000
09:30:54.954: DXGI increase maximum frame latency success
09:30:54.954: D3D11 GPU priority setup failed (not admin?)
09:30:55.632: ---------------------------------
09:30:55.632: video settings reset:
09:30:55.632: 	base resolution:   1920x1080
09:30:55.632: 	output resolution: 1280x720
09:30:55.632: 	downscale filter:  Bicubic
09:30:55.632: 	fps:               30/1
09:30:55.632: 	format:            NV12
09:30:55.632: 	YUV mode:          709/Partial
09:30:55.633: NV12 texture support enabled
09:30:55.634: Audio monitoring device:
09:30:55.634: 	name: 默认
09:30:55.634: 	id: default
09:30:55.665: ---------------------------------
09:30:55.776: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
09:30:55.801: Failed to load 'en-US' text for module: 'decklink-captions.dll'
09:30:55.828: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
09:30:55.874: Failed to load 'zh-CN' text for module: 'droidcam-obs.dll'
09:30:56.118: [AMF] Version 2.7.0 loaded (Compiled: 1.4.14.0, Runtime: 1.4.15.0, Library: 1;4;15;0;19.40.34.02;202003021629;CL#2078333).
09:30:56.118: [AMF] [H264/AVC] Not supported by any GPU, disabling...
09:30:56.118: [AMF] [H265/HEVC] Not supported by any GPU, disabling...
09:30:56.452: [obs-browser]: Version 2.9.1
09:30:56.452: [obs-browser]: CEF Version 75.1.16+g16a67c4+chromium-75.0.3770.100
09:30:56.537: NVENC supported
09:30:56.615: [obs-ndi] hello ! (version 4.9.0)
09:30:56.615: [obs-ndi] Trying 'd:\Program Files\NewTek\NDI 4 Runtime\v4'
09:30:56.615: [obs-ndi] Found NDI library at 'D:/Program Files/NewTek/NDI 4 Runtime/v4/Processing.NDI.Lib.x64.dll'
09:30:56.690: [obs-ndi] NDI runtime loaded successfully
09:30:56.696: [obs-ndi] NDI library initialized successfully (NDI SDK WIN64 06:20:19 Apr  1 2020 4.5.1.0)
09:30:57.213: VLC found, VLC video source enabled
09:30:57.399: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
09:30:57.400: No blackmagic support
09:30:57.502: ---------------------------------
09:30:57.502:   Loaded Modules:
09:30:57.502:     win-wasapi.dll
09:30:57.502:     win-mf.dll
09:30:57.502:     win-dshow.dll
09:30:57.502:     win-decklink.dll
09:30:57.502:     win-capture.dll
09:30:57.503:     vlc-video.dll
09:30:57.503:     text-freetype2.dll
09:30:57.503:     rtmp-services.dll
09:30:57.503:     obs-x264.dll
09:30:57.503:     obs-vst.dll
09:30:57.503:     obs-transitions.dll
09:30:57.503:     obs-text.dll
09:30:57.503:     obs-rtspserver.dll
09:30:57.503:     obs-qsv11.dll
09:30:57.503:     obs-outputs.dll
09:30:57.503:     obs-ndi.dll
09:30:57.503:     obs-filters.dll
09:30:57.503:     obs-ffmpeg.dll
09:30:57.503:     obs-browser.dll
09:30:57.503:     image-source.dll
09:30:57.503:     frontend-tools.dll
09:30:57.503:     enc-amf.dll
09:30:57.503:     droidcam-obs.dll
09:30:57.503:     decklink-ouput-ui.dll
09:30:57.503:     decklink-captions.dll
09:30:57.503:     coreaudio-encoder.dll
09:30:57.503: ---------------------------------
09:30:57.504: ==== Startup complete ===============================================
09:30:57.527: All scene data cleared
09:30:57.527: ------------------------------------------------
09:30:57.843: WASAPI: Device '扬声器 (Realtek(R) Audio)' [48000 Hz] initialized
09:30:57.843: [Loaded global audio device]: '桌面音频'
09:30:57.844: [WASAPISource::TryInitialize]:[线路 (MG-XU)] Failed to activate client context: 88890004
09:30:57.844: [WASAPISource::WASAPISource] Device '{0.0.1.00000000}.{03a1a0e8-e658-4479-a4fc-ccbc964b6d48}' not found.  Waiting for device
09:30:57.844: [Loaded global audio device]: '麦克风/Aux'
09:30:57.884: adding 42 milliseconds of audio buffering, total audio buffering is now 42 milliseconds (source: 桌面音频)
09:30:57.884: 
09:30:59.979: [DroidCamOBS] create(source=000001518E1586A0) v1.1.1
09:31:00.216: [DroidCamOBS] activated=1, deactivateWNS=0, is_showing=0, enable_audio=0
09:31:00.216: [DroidCamOBS] video_format=avc video_resolution=1280x720
09:31:00.216: [DroidCamOBS] device_info.id=dev_id_wifi device_info.ip=192.168.2.108 device_info.port=4747 device_info.type=1
09:31:00.217: [DroidCamOBS] video_thread start
09:31:00.217: [DroidCamOBS] video_decode_thread start
09:31:00.217: [DroidCamOBS] audio_thread start
09:31:00.217: [Media Source '背景视']: settings:
09:31:00.217: 	input:                   C:/Users/86152/Desktop/直播/炫酷科技感手指全息投影文字LOGO片头.mp4
09:31:00.217: 	input_format:            (null)
09:31:00.217: 	speed:                   100
09:31:00.217: 	is_looping:              yes
09:31:00.217: 	is_hw_decoding:          no
09:31:00.217: 	is_clear_on_media_end:   yes
09:31:00.217: 	restart_on_activate:     yes
09:31:00.217: 	close_when_inactive:     no
09:31:02.908: [obs-ndi] started A/V threads for source ''
09:31:02.909: [obs-ndi] A/V thread for 'NDI™ 来源' started
09:31:02.913: Switched to scene '前摄'
09:31:02.913: ------------------------------------------------
09:31:02.913: Loaded scenes:
09:31:02.913: - scene '开场':
09:31:02.913:     - source: '图像' (image_source)
09:31:02.913: - scene '前摄':
09:31:02.913:     - source: '前摄像头' (vlc_source)
09:31:02.913:     - source: '台标' (image_source)
09:31:02.913:     - source: 'live' (image_source)
09:31:02.913:     - source: 'LED Clock' (lua_led_clock)
09:31:02.913: - scene '后摄':
09:31:02.913:     - source: '后摄像头' (vlc_source)
09:31:02.913:     - source: '台标' (image_source)
09:31:02.913: - scene '主画':
09:31:02.913:     - source: '主画面' (droidcam_obs)
09:31:02.913:     - source: '台标' (image_source)
09:31:02.913: - scene '双画面':
09:31:02.913:     - source: '背景' (image_source)
09:31:02.913:     - source: '背景视' (ffmpeg_source)
09:31:02.913:     - source: '后摄像头' (vlc_source)
09:31:02.914:     - source: '框' (image_source)
09:31:02.914:         - filter: '色值' (color_key_filter)
09:31:02.914:     - source: '前摄像头' (vlc_source)
09:31:02.914:     - source: '框' (image_source)
09:31:02.914:         - filter: '色值' (color_key_filter)
09:31:02.914:     - source: '台标' (image_source)
09:31:02.914:     - source: '地球' (image_source)
09:31:02.914: - scene '双画面2':
09:31:02.914:     - source: '背景' (image_source)
09:31:02.914:     - source: '后摄像头' (vlc_source)
09:31:02.914:     - source: '背景视' (ffmpeg_source)
09:31:02.914:     - source: '前摄像头' (vlc_source)
09:31:02.914:     - source: '框' (image_source)
09:31:02.914:         - filter: '色值' (color_key_filter)
09:31:02.914:     - source: '主画面' (droidcam_obs)
09:31:02.914:     - source: '框' (image_source)
09:31:02.914:         - filter: '色值' (color_key_filter)
09:31:02.914:     - source: '台标' (image_source)
09:31:02.914:     - source: '地球' (image_source)
09:31:02.914: - scene '三画面':
09:31:02.914:     - source: '背景' (image_source)
09:31:02.914:     - source: '前摄像头' (vlc_source)
09:31:02.914:     - source: '主画面' (droidcam_obs)
09:31:02.914:     - source: '后摄像头' (vlc_source)
09:31:02.914:     - source: 'VLC 视频源' (vlc_source)
09:31:02.914:     - source: '框' (image_source)
09:31:02.914:         - filter: '色值' (color_key_filter)
09:31:02.914:     - source: '框' (image_source)
09:31:02.914:         - filter: '色值' (color_key_filter)
09:31:02.914:     - source: '台标' (image_source)
09:31:02.914:     - source: '地球' (image_source)
09:31:02.914:     - source: '框' (image_source)
09:31:02.914:         - filter: '色值' (color_key_filter)
09:31:02.914:     - source: 'NDI™ 来源' (ndi_source)
09:31:02.914:     - source: 'live' (image_source)
09:31:02.914: ------------------------------------------------
09:31:29.371: [jim-nvenc: 'simple_h264_stream'] settings:
09:31:29.371: 	rate_control: CBR
09:31:29.371: 	bitrate:      2500
09:31:29.371: 	cqp:          20
09:31:29.371: 	keyint:       250
09:31:29.371: 	preset:       hq
09:31:29.371: 	profile:      high
09:31:29.371: 	width:        1280
09:31:29.371: 	height:       720
09:31:29.371: 	2-pass:       false
09:31:29.371: 	b-frames:     2
09:31:29.371: 	lookahead:    false
09:31:29.371: 	psycho_aq:    true
09:31:29.371: 
09:31:29.378: ---------------------------------
09:31:29.378: [FFmpeg aac encoder: 'simple_aac'] bitrate: 160, channels: 2, channel_layout: 3
09:31:29.378: 
09:31:29.420: ==== Recording Start ===============================================
09:31:29.420: [ffmpeg muxer: 'simple_file_output'] Writing file 'C:/Users/86152/Videos/2021-03-01 09-31-29.mkv'...
09:32:16.713: Switched to Preview/Program mode
09:32:16.714: ------------------------------------------------
10:02:52.242: [ffmpeg muxer: 'simple_file_output'] Output of file 'C:/Users/86152/Videos/2021-03-01 09-31-29.mkv' stopped
10:02:52.242: Output 'simple_file_output': stopping
10:02:52.242: Output 'simple_file_output': Total frames output: 56476
10:02:52.242: Output 'simple_file_output': Total drawn frames: 56485
10:02:52.242: ==== Recording Stop ================================================
10:04:43.580: ==== Shutting down ==================================================
10:04:43.641: [DroidCamOBS] stopping
10:04:43.641: [DroidCamOBS] video_decode_thread end
10:04:43.644: [DroidCamOBS] video_thread end
10:04:43.656: [DroidCamOBS] audio_thread end
10:04:43.657: [DroidCamOBS] cleanup
10:04:43.734: [obs-ndi] audio thread for 'NDI™ 来源' completed
10:04:43.824: WASAPI: Device '扬声器 (Realtek(R) Audio)' Terminated
10:04:43.833: All scene data cleared
10:04:43.833: ------------------------------------------------
10:04:43.965: [obs-ndi] goodbye !
10:04:43.967: [Scripting] Total detached callbacks: 3
10:04:44.033: Freeing OBS context data
10:04:44.070: == Profiler Results =============================
10:04:44.070: run_program_init: 9311.85 ms
10:04:44.070:  ┣OBSApp::AppInit: 76.736 ms
10:04:44.070:  ┃ ┗OBSApp::InitLocale: 30.924 ms
10:04:44.070:  ┗OBSApp::OBSInit: 9132.66 ms
10:04:44.070:    ┣obs_startup: 9.618 ms
10:04:44.070:    ┗OBSBasic::OBSInit: 8226.7 ms
10:04:44.070:      ┣OBSBasic::InitBasicConfig: 1.191 ms
10:04:44.070:      ┣OBSBasic::ResetAudio: 0.29 ms
10:04:44.070:      ┣OBSBasic::ResetVideo: 796.707 ms
10:04:44.070:      ┣OBSBasic::InitOBSCallbacks: 0.006 ms
10:04:44.070:      ┣OBSBasic::InitHotkeys: 0.06 ms
10:04:44.070:      ┣obs_load_all_modules: 1836.95 ms
10:04:44.070:      ┃ ┣obs_init_module(coreaudio-encoder.dll): 4.515 ms
10:04:44.070:      ┃ ┣obs_init_module(decklink-captions.dll): 0.044 ms
10:04:44.070:      ┃ ┣obs_init_module(decklink-ouput-ui.dll): 0.95 ms
10:04:44.070:      ┃ ┣obs_init_module(droidcam-obs.dll): 0.004 ms
10:04:44.070:      ┃ ┣obs_init_module(enc-amf.dll): 204.659 ms
10:04:44.070:      ┃ ┣obs_init_module(frontend-tools.dll): 8.062 ms
10:04:44.070:      ┃ ┣obs_init_module(image-source.dll): 0.013 ms
10:04:44.070:      ┃ ┣obs_init_module(obs-browser.dll): 0.798 ms
10:04:44.070:      ┃ ┣obs_init_module(obs-ffmpeg.dll): 2.923 ms
10:04:44.070:      ┃ ┃ ┗nvenc_check: 2.814 ms
10:04:44.070:      ┃ ┣obs_init_module(obs-filters.dll): 0.067 ms
10:04:44.070:      ┃ ┣obs_init_module(obs-ndi.dll): 88.729 ms
10:04:44.070:      ┃ ┣obs_init_module(obs-outputs.dll): 0.024 ms
10:04:44.070:      ┃ ┣obs_init_module(obs-qsv11.dll): 104.519 ms
10:04:44.070:      ┃ ┣obs_init_module(obs-rtspserver.dll): 5.763 ms
10:04:44.070:      ┃ ┣obs_init_module(obs-text.dll): 0.456 ms
10:04:44.070:      ┃ ┣obs_init_module(obs-transitions.dll): 0.013 ms
10:04:44.070:      ┃ ┣obs_init_module(obs-vst.dll): 0.004 ms
10:04:44.070:      ┃ ┣obs_init_module(obs-x264.dll): 0.006 ms
10:04:44.070:      ┃ ┣obs_init_module(rtmp-services.dll): 11.662 ms
10:04:44.071:      ┃ ┣obs_init_module(text-freetype2.dll): 0.422 ms
10:04:44.071:      ┃ ┣obs_init_module(vlc-video.dll): 5.548 ms
10:04:44.071:      ┃ ┣obs_init_module(win-capture.dll): 105.402 ms
10:04:44.071:      ┃ ┣obs_init_module(win-decklink.dll): 3.46 ms
10:04:44.071:      ┃ ┣obs_init_module(win-dshow.dll): 4.856 ms
10:04:44.071:      ┃ ┣obs_init_module(win-mf.dll): 0 ms
10:04:44.071:      ┃ ┣obs_init_module(win-wasapi.dll): 0.016 ms
10:04:44.071:      ┃ ┗reset_win32_symbol_paths: 0.216 ms
10:04:44.071:      ┣OBSBasic::ResetOutputs: 0.379 ms
10:04:44.071:      ┣OBSBasic::CreateHotkeys: 0.058 ms
10:04:44.071:      ┣OBSBasic::InitService: 7.655 ms
10:04:44.071:      ┣OBSBasic::InitPrimitives: 0.105 ms
10:04:44.071:      ┗OBSBasic::Load: 5406.18 ms
10:04:44.071: obs_hotkey_thread(25 ms): min=0.004 ms, median=0.016 ms, max=12.994 ms, 99th percentile=0.165 ms, 100% below 25 ms
10:04:44.071: audio_thread(Audio): min=0 ms, median=0.349 ms, max=143.327 ms, 99th percentile=0.583 ms
10:04:44.071:  ┗receive_audio: min=0.004 ms, median=0.261 ms, max=9.47 ms, 99th percentile=0.396 ms, 0.913674 calls per parent call
10:04:44.071:    ┣buffer_audio: min=0.001 ms, median=0.002 ms, max=0.273 ms, 99th percentile=0.003 ms
10:04:44.071:    ┗do_encode: min=0.086 ms, median=0.254 ms, max=9.463 ms, 99th percentile=0.386 ms
10:04:44.071:      ┗encode(simple_aac): min=0.084 ms, median=0.209 ms, max=1.638 ms, 99th percentile=0.259 ms
10:04:44.071: obs_graphics_thread(33.3333 ms): min=0.139 ms, median=3.474 ms, max=5059.21 ms, 99th percentile=4.46 ms, 99.9769% below 33.333 ms
10:04:44.071:  ┣tick_sources: min=0.001 ms, median=1.787 ms, max=5058.5 ms, 99th percentile=2.506 ms
10:04:44.071:  ┣output_frame: min=0.123 ms, median=0.901 ms, max=4.89 ms, 99th percentile=1.3 ms
10:04:44.071:  ┃ ┗gs_context(video->graphics): min=0.122 ms, median=0.9 ms, max=4.89 ms, 99th percentile=1.299 ms
10:04:44.071:  ┃   ┣render_video: min=0.006 ms, median=0.848 ms, max=4.732 ms, 99th percentile=1.214 ms
10:04:44.071:  ┃   ┃ ┣render_main_texture: min=0.004 ms, median=0.477 ms, max=4.729 ms, 99th percentile=0.691 ms
10:04:44.071:  ┃   ┃ ┣render_output_texture: min=0.007 ms, median=0.013 ms, max=0.245 ms, 99th percentile=0.025 ms, 0.931097 calls per parent call
10:04:44.071:  ┃   ┃ ┣render_convert_texture: min=0.01 ms, median=0.022 ms, max=0.265 ms, 99th percentile=0.044 ms, 0.931097 calls per parent call
10:04:44.071:  ┃   ┃ ┗output_gpu_encoders: min=0 ms, median=0.063 ms, max=0.395 ms, 99th percentile=0.121 ms, 0.931097 calls per parent call
10:04:44.071:  ┃   ┗gs_flush: min=0.015 ms, median=0.053 ms, max=0.92 ms, 99th percentile=0.198 ms
10:04:44.071:  ┗render_displays: min=0.001 ms, median=0.78 ms, max=11.148 ms, 99th percentile=1.177 ms
10:04:44.071: =================================================
10:04:44.071: == Profiler Time Between Calls ==================
10:04:44.071: obs_hotkey_thread(25 ms): min=24.51 ms, median=25.019 ms, max=39.002 ms, 70.0944% within ±2% of 25 ms (0% lower, 29.9056% higher)
10:04:44.071: obs_graphics_thread(33.3333 ms): min=2.377 ms, median=33.333 ms, max=5059.22 ms, 99.9505% within ±2% of 33.333 ms (0.0263748% lower, 0.0230779% higher)
10:04:44.071: =================================================
10:04:44.122: Number of memory leaks: 9

## Expected Behavior

使用VLC media player导入RTST流（rtmp://admin:850610lzx@192.168.0.70:554/unicast/c16/s0/live/）播放
![image](https://user-images.githubusercontent.com/29686769/109447369-773ebb80-7a7e-11eb-801d-4803efffd690.png)

## Current Behavior

开始一切正常，在9：54：32之后出现问题，9：54：36又恢复正常。此问题不定时出现！！
![image](https://user-images.githubusercontent.com/29686769/109447596-04821000-7a7f-11eb-8240-a5096c11bc8d.png)
![image](https://user-images.githubusercontent.com/29686769/109447826-925dfb00-7a7f-11eb-95ec-737b70b4cdbc.png)
![image](https://user-images.githubusercontent.com/29686769/109447695-35fadb80-7a7f-11eb-819d-40cc32ac1236.png)
![image](https://user-images.githubusercontent.com/29686769/109447710-3f844380-7a7f-11eb-89ea-824cddec4445.png)
![image](https://user-images.githubusercontent.com/29686769/109447731-48751500-7a7f-11eb-83d8-2694da6b04c6.png)

![image](https://user-images.githubusercontent.com/29686769/109447675-27acbf80-7a7f-11eb-8a61-0456712ee15b.png)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by xisohi** [comment]
如果使用VLC media player单独播放，问题不会出现！！

**Comment by Fenrirthviti** [comment]
Please use the forums or Discord for support, thanks!
