### ISSUE TITLE
Transform panel window inconsistently updates for subsequent selected sources.

### ISSUE THREAD

**Issue by AskMP** [obsproject/obs-studio#4291]
## Platform
Operating system and version: Windows
OBS Studio version: 26.1.1
OBS Log file: N/A

## Expected Behavior
EITHER:
a) Multiple transform panels open for different sources and closed manually (not preferred)
b) The transform panel shows the appropriate information for the respected layer selected

## Current Behavior
The transform panel _sometimes_ shows the newly selected item however is inconsistent. At times, I need to select the top level group, then the internal item. Then to see another group's item transformation, I select it's parent group then the internal item. Selecting it again after closing the transform results in the transform panel losing attributes and resetting to blank even when selecting items that do have attributes adjusted.

## Steps to Reproduce
1. Select a source and right-click to open the "Transform" -> "Edit Transform"
2. Modify the transformation attributes (no matter the one)
3. Select a different source from either the existing scene or a different scene
4. Replicate the process for different source types, groups, sources within groups, etc... it's all different and sometimes works but never consistently.

**Comment by WizardCM** [comment]
Confirmed. Switching scenes then clicking on sources does not update the Transform dialog. Switching back to the original scene and selecting sources does update it again. How strange.

**Comment by RytoEX** [comment]
Fixed by https://github.com/obsproject/obs-studio/commit/9267c7e53d7781e299fda77f0b62ba599e23ff3a (manual merge of #4312).
