### ISSUE TITLE
OBS locks session (wayland)

### ISSUE THREAD

**Issue by tallero** [obsproject/obs-studio#4292]
When used in Wayland sessions OBS flatpak locks the environment after a while, with both wayland screencast plugin and Xcomposite.
Logs will be available next time it happens.

**Comment by Fenrirthviti** [comment]
Support for the flathub package can be found here: https://github.com/flathub/com.obsproject.Studio/issues

Additionally, in the future when you submit and issue, please read the template instead of deleting it.

**Comment by tallero** [comment]
Yup, it's in that state because I needed to provide logs. Anyway at this point I believe this is a bug in GNOME Shell.
