### ISSUE TITLE
OBS: Vulkan-API games blackscreen/framefreeze

### ISSUE THREAD

**Issue by TheFapf** [obsproject/obs-studio#4296]
## Platform

Operating system and version: Gaming-PC: Windows 10 20H2 19042.804 Recording-PC: Windows 10 20H2 19042.804
OBS Studio version: 26.1.1
OBS Log file: [obs.log](https://github.com/obsproject/obs-studio/files/6075813/obs.log)

## Expected Behavior

Capturing a vulkan-api game (Doom Eternal, Valheim) should work in OBS 26.1.1 by a dual-pc setup with elgato 4k60 mk2 should work in OBS Studio. 

## Current Behavior

When starting a vulkan-api game like Doom Eternal, the Preview-Screen in OBS Studio stays black. Used Capturemode is Videocapture (with Elgato 4K60 Mk2). The sound works fine. Sometimes it seems, that the game apears to work fine in obs-preview window, but its just one frame that freezed. Non-Vulkan games works fine.

## Steps to Reproduce

1. Use a dual-pc setup with a capture card
2. On the recording-PC open OBS Studio 26.1.1
2. On the gaming-PC open a vulkan-bases game like Doom Eternal or Valheim
3. Previewscreen in OBS Studio stays black, sound is comming in

## Additional information

If i switch in Doom Eternal to windowed-mode, the capturing works fine, but i have the window-borders and framskips. 
If i switch to borderless windowed-mode, the screen strays black. 
If i switch to windowed-mode and then back to fullscreen, it works fine and i can capture. This doesnt work in Valheim, only in Doom Eternal. 
If i try to use an overlay from the radeon-driver in fullscreen-mode (https://github.com/obsproject/obs-studio/issues/2219) the screen stays black
If i switch alt+tab to desktop an back to game, i get the last frame of the game frezzed
I tried to use OBS Studio 25.0.1, the same issue appears
I get no error-message
Gaming-PC works fine all the time, game runs smooth
Systems are Stock, no OC

All drivers/bios/windows are upto date. 

My entire Hardware information:
Gaming-PC:
Ryzen 5900x
AMD RX 6900 XT
32 GSkill Neo F4-3600C16Q-32GTZN
Samsung EVO 980 Pro
Asus Dark Hero Mainboard
1200W Asus Thor Powersupply

Recording-PC
Ryzen 3600x
Geforce RTX 2060
Samsung EVO 970
WD Blue 3TB HDD
32 GB GSkill Ripjaws0
Gigabyte b450 Aorus M Mainboard
Bequiet Straightpower 650 Powersupply
Elgato 4K60 MK2

**Comment by WizardCM** [comment]
For support requests, please use the Discord or the Forums. GitHub issues are for reproducible bugs within OBS itself.
