### ISSUE TITLE
Crash on close

### ISSUE THREAD

**Issue by IkerGalardi** [obsproject/obs-studio#4297]
## Platform

Operating system and version: Arch Linux, kernel version 5.10.19-1
OBS Studio version: 26.1.2-1
OBS Log file: [2021-03-03 14-26-01.txt](https://github.com/obsproject/obs-studio/files/6076363/2021-03-03.14-26-01.txt)
`error: Failed to fetch parent window geometry!`
`error: Failed to fetch parent window geometry!`
`error: Failed to fetch parent window geometry!`
`error: Failed to fetch parent window geometry!`
`[1]    37454 segmentation fault (core dumped)  obs`

## Expected Behavior

When quiting the application, should simply close without any error.
## Current Behavior

After openning the application through the console, when closing, a segmentation fault error shows.
## Steps to Reproduce

1. Simply close the application
![image](https://user-images.githubusercontent.com/27565092/109815330-d1cb4980-7c2f-11eb-9c2d-ad41aedcc301.png)

**Comment by notr1ch** [comment]
Arch Linux is not an officially supported platform. Please raise this with your packager.
