### ISSUE TITLE
OBS does not recognize 4k displays in the current version (v26.1.1)

### ISSUE THREAD

**Issue by joolaas** [obsproject/obs-studio#4298]
## Platform
Operating system and version: Windows 10 Version: 20H2
OBS Studio version: 26.1.1 x64
OBS Log file: https://obsproject.com/logs/kt18qCVv6NOdZs1a

## Expected Behavior
OBS should recognize automatically a display with a 4k (3840x2160) resolution with the "auto setup" and in the settings -> video -> Base (Canvas) Resolution dropdown menu

## Current Behavior
With the "auto setup" on the first start of OBS, it recognizes the 4k display but shows that it has a resolution of 2560x1440, which is not correct!

## Steps to Reproduce
1. Install OBS with the 26.1.1 version
2. Run OBS the first time with a connected 4k display
3. choose "optimized for recording
4. you'll see the 4k display is only shown with a resolution of 2k (2560x1440)

## Additional information
I've tried this on three different computers and it was always the same issue.
The I've tried it with the older version of OBS (26.0.2) and everything works perfectly fine. The 4k display is shown as a 4k display.

**Comment by notr1ch** [comment]
Likely the same issue as https://github.com/obsproject/obs-studio/pull/4225

**Comment by WizardCM** [comment]
Fixed by #4225

**Comment by notr1ch** [comment]
#4225 only seems to affect the settings dialog, not the auto config wizard. I think the wizard needs fixing also.

**Comment by energizerfellow** [comment]
OBS's auto-config also doesn't appear to have any check for resolutions over 4096.  If the PC's display has a resolution of >4096 pixels on any one side you'll end up in a situation where auto-config will set the output resolution to some high resolution the encoder can't handle.
