### ISSUE TITLE
I am using OBS studio version 24.0.2 on macOS el capitan. virtual camera does not work

### ISSUE THREAD

**Issue by Justiniscoding** [obsproject/obs-studio#4302]
OBS Studio version: 24.0.2
OBS Log file:https://obsproject.com/logs/XDpWcw-uAZrLLRLV

## Expected Behavior

i should be able to use the virtual camera. i downloaded the plugin from github ( mac-obs-virtualcamera ) and i can choose the virtual camera in FaceTime but i can't actually edit what it shows in OBS

 in tools there is not a virtual camera button. shows OBS logo if i choose ops-virtual-camera in FaceTime. CANNOT edit what it shows

**Comment by Justiniscoding** [comment]
screen shots: https://filebin.net/wcoux8inx5tuhjma

**Comment by Gol-D-Ace** [comment]
The plug-in you are talking about is split into two parts.

While the DAL Plug-in might work the OBS side of the plug-in will not with old OBS versions.

The plug-in is also from a third party and we don't maintain it. (The merged plug-in in current OBS Studio versions we do of course.)
