### ISSUE TITLE
'Transition' Issues After MacOS Update

### ISSUE THREAD

**Issue by CadeDotJPEG** [obsproject/obs-studio#4303]
After updating MacOS to Catalina 10.15.7, I ran into some issues with transitions between scenes, as well as transitioning the same scene after adding/removing sources.

In **Studio Mode**
-If the 'Transition' button is accidentally clicked on when there is no change made to the preview side, the button (and all of the 'quick transitions') fade out so that they cannot be clicked on again. The manual slider under the quick transitions does work, and resets the 'Transition' button when I use the slider. It's not a big issue for me, but I have a couple of less tech-savvy people working under me that freaked out when the button faded out.
-Additionally, I used to be able to un-hide or hide a source in the same scene, and it would only change in the preview window and I could transition to it, making the source (a timer in my case) fade in. Now, whenever I un-hide or hide a source, it just cuts in or out respectively, both in the preview window and in the program window.

Other than that y'all are amazing and keep up the good work!

If I could postpone MacOS updates, I would, but this is an IT managed device, and they have it set to automatically update without asking the user.

I am using a 2019 MacBook Pro 13" (A2159)
Running MacOS Catalina v10.15.7
Running OBS Studio 26.1.2 (mac)

**Comment by Fenrirthviti** [comment]
Please properly fill out the issue template.

**Comment by notr1ch** [comment]
Closed due to lack of feedback.
