### ISSUE TITLE
Duplicate sources won't work when changing the text in group.

### ISSUE THREAD

**Issue by iesv** [obsproject/obs-studio#4309]
## Platform

Operating system and version: win10 1809 x64
OBS Studio version: 26.1.1
OBS Log file: None

## Expected Behavior

Duplicate sources can work correctly when changing the text of group in studio mode.
## Current Behavior

Duplicate sources won't work when changing the text in group.
## Steps to Reproduce

1. Switch the studio mode
2. Check the Duplicate sources 
3. Add a text 
4. Group selected items
5. Click the transition
6. Change the text 
7. Now we can find the duplicate sources won't work in studio mode.

**Comment by Fenrirthviti** [comment]
Closing as stale. If this is still an issue please open a new issue with updated reproduction steps on the latest version of OBS.
