### ISSUE TITLE
Source color labels do not propagate when duplicating a scene

### ISSUE THREAD

**Issue by AskMP** [obsproject/obs-studio#4315]
## Platform
Operating system and version: Windows
OBS Studio version: 26.1.1
OBS Log file: N/A

## Expected Behavior
Duplicating a scene should result in the colour labels for each source to also be replicated to the new scene.

## Current Behavior
Duplicating a scene blanks out any labelling that existed in the original and also opens all the groups.

## Steps to Reproduce
1. Create a new group or _any_ source type in an empty scene (or filled, no impact either way)
2. right-click on the source and select a colour from the "set color" option
3. repeat if necessary or use only that one source
4. right-click and duplicate the scene
5. confirm that the new scene has lost the colour label originally set

## Additional information
It would be nice to also check as to why groups are also all opened during this duplication, my guess is that there are certain attributes associated to sources that are not carried over and instead simply pick up their default values when duplicated.

**Comment by gxalpha** [comment]
This sounds like a feature request, which we don't track using GitHub Issues (we use GitHub exclusively for bug reports).
Please put ideas and feature requests on [our ideas page](https://ideas.obsproject.com).

Thank you!
