### ISSUE TITLE
Image Slide Show is not hidden when the last slide is gone through

### ISSUE THREAD

**Issue by VazMike** [obsproject/obs-studio#4319]
## Platform

Operating system and version: macOS Big Sur 11.2.1
OBS Studio version: 26.1.2
OBS Log file:

## Expected Behavior

I want slideshow to stop if I click forward on the last slide.
As a consequence I want the slideshow to be hidden if the proper checkbox is checked.

## Current Behavior

Slideshow doesn't stop and it loops to the first slide.

## Steps to Reproduce

1. Add Source -> Image Slide Show -> Create New -> OK
2. Set `Slide Mode` to Manual
3. Uncheck `Loop` and check `Hide when slideshow is done`
4. Add Image Files (any number)
5. Click `Next in Playlist` button until you reach the last slide, then click again.

## Additional information

I was looking if my issue already exists on GitHub, but I couldn't find one.
What I found was the [post on the OBS forum](https://obsproject.com/forum/threads/image-slide-show-not-stopping-at-end-in-manual-mode.138392/) where the exact same problem is described. Nobody has replied there yet.

**Comment by Fenrirthviti** [comment]
Closing as stale. If this is still an issue please open a new issue with updated reproduction steps on the latest version of OBS.

As a note, image slideshow has been completely rewritten, so this issue report is no longer valid anyway.
