### ISSUE TITLE
"Resize output (Source size)" button doesn't save new video settings

### ISSUE THREAD

**Issue by matoi974** [obsproject/obs-studio#4326]
## Platform

Operating system and version: Windows 10 2004 x64
OBS Studio version: 26.1.1 x64
OBS Log file: n/a

## Steps to Reproduce

1. Create a new profile and a new scene collection, then quit and restart obs-studio.
2. Create a Browser source, which has a default size of 800x600. Make sure it's 800x600 if it isn't.
3. Right-click the Browser source in the sources list and select "Resize output (source size)".
4. Quit and restart obs-studio.

## Expected Behavior
Canvas and output sizes in Settings>Video must both stay at 800x600.

## Current Behavior
Canvas and output sizes were both unset to their default values (1920x1080 and 1280x720 respectively).

**Comment by kkartaltepe** [comment]
Duplicate #4207
