### ISSUE TITLE
Video Capture Device source type sometimes initializes attached audio at low sample rate

### ISSUE THREAD

**Issue by FerretBomb** [obsproject/obs-studio#4332]
## Platform
Operating system and version: Windows 10 (1909, 2004, 20H2)
OBS Studio version: 26.1.1
OBS Log file: https://obsproject.com/logs/mo4WiSQUxVL_zXbF

## Expected Behavior
VCD associated audio device should init at highest sampling rate available (48kHz)

## Current Behavior
VCD source audio for some devices inits at 44.1kHz with no option to force 48kHz.
Adding an Audio Input Capture source pointed at the same device inits at 48kHz, demonstrating that Windows is reporting available device sampling rates properly.

## Steps to Reproduce
Erratic reproduction based on hardware configuration.
1a. Add a VCD source. Allow it to use Device Audio. Inits at 44100 per the log.
1b. Add a VCD source. Use a Custom Device, pointed at the VCD's audio device. Inits at 44100 per the log.
2. Add an Audio Input Capture source, pointed at the VCD's audio device. Inits at 48000. Demonstrates that Windows is reporting device capabilities to OBS correctly, but the VCD source type mis-handles the audio device in some cases.

## Additional information
Issue has occurred with an Elgato HD60 Pro and a Magewell 2-port HDMI Pro Capture in my case, and a second Elgato HD60 Pro in https://obsproject.com/forum/threads/audio-pops-click-garble-only-with-per-scene-mic-not-with-global-audio.140678
Wider occurrence frequency unknown but entirely possible, as most users will not know to check logs and report this issue.

**Comment by Atlas42** [comment]
I have the same problem here using directly the libdshowcapture and made a fast fix for it.

In my case the Windows API used to get the device properties (IAMStreamConfig::GetStreamCaps) reports a max rate of 44.1Hz even if the device pin list an available 48KHz pin configuration.
I have forked the library code and replaced the function with one that does not rely on the erroneous report.
There is some code in that function that does not make sense to me so I am not sure my changes will cover all intended cases, but it works well in my cases.

Here are my changes if someone that understand that function wants to take a look.
https://github.com/Atlas42/libdshowcapture/commit/85d9fa39c7f3471d58da137f7bd10f26f083f8b2

**Comment by Fenrirthviti** [comment]
Closing as stale. If this is still an issue please open a new issue with updated reproduction steps on the latest version of OBS.

If there is an existing fix for this, please PR it so it can be reviewed.
