### ISSUE TITLE
Video Capture Device source latency unexpectedly slow

### ISSUE THREAD

**Issue by FerretBomb** [obsproject/obs-studio#4333]
## Platform
Operating system and version: Windows 10 (1909, but occurs on 20H2)
OBS Studio version: 26.1.1
OBS Log file: N/A

## Expected Behavior
VCD sources should capture and intake video with a minimum delay.

## Current Behavior
VCD capture delay is significantly increased as compared to other video capture applications.
It is literally lower latency in most cases to capture a VCD in AmaRecTV and Window Capture that application, than to directly VCD source in OBS Studio.

## Steps to Reproduce
1. Add a VCD Source in OBS that allows multi-program access (Magewell, some Elgato devices)
2. Open AmaRecTV 2.20c, assign it to capture from the same device.
3. Add a Window Capture in OBS, pointed at AmaRecTV. Side-by-side split-crop if needed.
4. Observe that the Window Capture from ARTV has capture latency to-preview (compared to independent audio) in the 25-40ms range, while OBS' VCD source is in the 250-300ms range.

## Additional information
I am available to assist as a testbed if needed, VCD delay on my system is consistently present in OBS, but not in other video-capture applications.

**Comment by WizardCM** [comment]
Did you disable "Buffering" in the source properties?

**Comment by FerretBomb** [comment]
Yes, Buffering is set to Disable.

**Comment by Fenrirthviti** [comment]
Closing as stale. If this is still an issue please open a new issue with updated reproduction steps on the latest version of OBS.
