### ISSUE TITLE
Virtual camera functions not working from lua script

### ISSUE THREAD

**Issue by frogeater** [obsproject/obs-studio#4340]
OBS Studio 26.1.1 (64 bit)
Windows 10 Pro up to date
Calling any of the following functions from lua script generates an error : obs_frontend_start_virtualcam, obs_frontend_stop_virtualcam, obs_frontend_virtualcam_active.
Similar functions for streaming, recording and replaybuffer are working perfectly.

**Comment by RytoEX** [comment]
Please follow the issue template when opening issues on GitHub.

**Comment by willlllllio** [comment]
I don't think the virtualcam functions are in 26.1.1 https://github.com/obsproject/obs-studio/blob/26.1.1/UI/api-interface.cpp

They were committed  a couple days after it released https://github.com/obsproject/obs-studio/commit/3bc4e8ecbab768b3a700aba2d34fc2364179f6f2 so you'll have to wait for OBS 27

**Comment by frogeater** [comment]
Thank you for the information, I'll wait for OBS 27.
Sorry, I was not aware of template.
