### ISSUE TITLE
New system - M1 Mac - Virtual Cam Starts, no device shown

### ISSUE THREAD

**Issue by jdgwf** [obsproject/obs-studio#4341]
## Platform

Operating system and version: macOS 11.2.3 (M1 MacBook Pro)
OBS Studio version: 26.1.2 (64 bit)
OBS Log file: See Attached
[2021-03-13 15-40-45.txt](https://github.com/obsproject/obs-studio/files/6135635/2021-03-13.15-40-45.txt)

## Expected Behavior

Expected a Virtual Camera to show up in FaceTime or Discord, but no device shows up.
## Current Behavior

Starting the Virtual Camera clicks and switches to Stop Virtual Camera with no error, seems to b e working in OBS, but other software doesn't see the Virtual Device.

## Steps to Reproduce

1. Installed OBS (relatively clean OS, no past installs of OBS)
2. Set up for Recording
3. Clicked Start Virtual Camera
4. Closed/Restarted Discord to find Camera, no device found
5. Opened Quicktime to try to find device, no device found
6. Stop Virtual Camera
7. Shut down OBS
8. Restarted OS
9. Started OBS,
10. tried 3-5 again.

**Comment by PatTheMav** [comment]
Virtual Cameras on macOS will only show up in applications that have whitelisted OBS _or_ disabled library validation for hardened runtime. Neither Facetime, Quicktime nor Discord have done either, so OBS' virtual cam will not work there.

Apple will not enable loading of 3rd party plugins (that includes all virtual cameras), other apps (i.e. Discord) could choose to do so but haven't yet afaik.

**Comment by jdgwf** [comment]
Thanks for the explanation - I'll poke Discord ;) 

Love you folks!

**Comment by asher-the-thrasher** [comment]
Actually there are workarounds for getting it to work on discord, come to the OBS discord and I can explain it there. https://discord.gg/obsproject

**Comment by jdgwf** [comment]
> Actually there are workarounds for getting it to work on discord, come to the OBS discord and I can explain it there. https://discord.gg/obsproject

I found the de-signer CLI command, and I’ve got it working for me. Took a little digging. Thanks!
