### ISSUE TITLE
Virtual Camera does not work or produce a "Start Virtual Camera" button for standalone/portable installs.

### ISSUE THREAD

**Issue by refriedfood** [obsproject/obs-studio#4342]
## Platform
Operating system and version: Tried on both windows 7 and 10
OBS Studio version: 26+
OBS Log file: n/a

## Expected Behavior
"Start Virtual Camera" option (button)

## Current Behavior
When downloading a compressed package (i.e. obs26.1.1.zip) and extracted to a directory, and then ran out of that directory, the "Start Virtual Camera" is not present. In order to make it present, OBS must be installed through its installer: exe, thus rendering any portable use null without it.

## Steps to Reproduce
Explained above.

**Comment by WizardCM** [comment]
In `data\obs-plugins\win-dshow\` you will find the installer for the virtual camera.
