### ISSUE TITLE
Linux Mint 20: "Include X Border" doesn't work

### ISSUE THREAD

**Issue by 0lhi** [obsproject/obs-studio#4345]
## Platform

Operating system and version: Linux Mint 20
OBS Studio version: OBS 26.1.1 (from the PPA)
OBS Log file: https://obsproject.com/logs/Anek6Cw9I9AwrpTn

## Expected Behavior

The X Border should be included.

https://i.imgur.com/a2TQGD4.png

## Current Behavior

The X Border is not included.

https://i.imgur.com/RRClPc4.png

## Steps to Reproduce

1. Add a new "Window Capture (Xcomposite)" Source
2. Select a Window
3. Check "Include X Border"

## Additional information

Including the Window Border is required on some Speedrun Leaderboards.

**Comment by kkartaltepe** [comment]
It looks like you want the window capture to include server side decorations. Those are not the X border and are not captured by the X border option. There is no way to capture server side decorations except to capture the fully composited screen with screen capture.
