### ISSUE TITLE
linux-v4l2 : loopback device not found if video_nr > 63

### ISSUE THREAD

**Issue by didierm** [obsproject/obs-studio#4347]
## Platform

Operating system and version: Linux Fedora 33
OBS Studio version: obs-studio-26.1.2-1.fc33.x86_64
OBS Log file:

## Expected Behavior
Virtual Camera should be started when clicking the [Start Virtual Camera]  button

## Current Behavior
Nothing happens.
The log reveals : 
`warning: Failed to start virtual camera`

## Steps to Reproduce
1. sudo modprobe v4l2loopback
2. obs

## Additional information
/etc/modprobe.d/v4l2-loopback.conf contains : 
`options v4l2loopback devices=1 video_nr=99 card_label=VirtCam exclusive_caps=1`

OBS iterates over /dev/videoX, where X=0-63 ; this is probably due to **MAX_DEVICES=64** : 
https://github.com/obsproject/obs-studio/blame/9eb32eed18214eb3b292449fe46cd7749db86788/plugins/linux-v4l2/v4l2-output.c#L8

As a result, devices with a **video_nr >=64** (99 in the above example) are not found.

This neglects what @tovrstra already suggested in https://github.com/obsproject/obs-studio/pull/3182#discussion_r493162462 , i.e. iterating over the values in /sys/module/v4l2loopback/parameters/video_nr , which should resolve this issue.

**Comment by tovrstra** [comment]
It is not so hard to change the plugin such that it reads the file `/sys/module/v4l2loopback/parameters/video_nr` and only tries these devices. However, there seems to be a bug in the `v4l2loopback` kernel module, making this approach problematic. The file `/sys/module/v4l2loopback/parameters/video_nr` does not always contain the correct information. Try e.g. the following:

```bash
# unload v4l2loopback to have a clean start
modprobe -r v4l2loopback
# The modprobe line from the plugin
modprobe v4l2loopback exclusive_caps=1 card_label='OBS Virtual Camera'
# Check the result
cat /sys/module/v4l2loopback/parameters/video_nr
# Check with v4l2-ctl
v4l2-ctl --list-devices
```

This gives me:

```
-1,-1,-1,-1,-1,-1,-1,-1
```

and

```
OBS Virtual Camera (platform:v4l2loopback-000):
	/dev/video6
...
```

**Comment by tovrstra** [comment]
The issue on v4l2loopback was not reported yet, so I've opened one: https://github.com/umlaeute/v4l2loopback/issues/416.

**Comment by KenwoodFox** [comment]
> It is not so hard to change the plugin such that it reads the file `/sys/module/v4l2loopback/parameters/video_nr` and only tries these devices. However, there seems to be a bug in the `v4l2loopback` kernel module, making this approach problematic. The file `/sys/module/v4l2loopback/parameters/video_nr` does not always contain the correct information. Try e.g. the following:
> 
> ```shell
> # unload v4l2loopback to have a clean start
> modprobe -r v4l2loopback
> # The modprobe line from the plugin
> modprobe v4l2loopback exclusive_caps=1 card_label='OBS Virtual Camera'
> # Check the result
> cat /sys/module/v4l2loopback/parameters/video_nr
> # Check with v4l2-ctl
> v4l2-ctl --list-devices
> ```
> 
> This gives me:
> 
> ```
> -1,-1,-1,-1,-1,-1,-1,-1
> ```
> 
> and
> 
> ```
> OBS Virtual Camera (platform:v4l2loopback-000):
> 	/dev/video6
> ...
> ```

Doing this FINALLY fixed my issue. But it's not automatic, I lose the camera at boot. Anything I could do?

**Comment by flexiondotorg** [comment]
> Doing this FINALLY fixed my issue. But it's not automatic, I lose the camera at boot. Anything I could do?

As a workaround you could use `video_nr` when loading v4l2loopback: I fix the OBS Virtual Camera to `video_nr` 13 like so:

    sudo modprobe v4l2loopback devices=1 video_nr=13 card_label="OBS Virtual Camera" exclusive_caps=1

And to automate at system boot:

    echo 'options v4l2loopback devices=1 video_nr=13 card_label="OBS Virtual Camera" exclusive_caps=1' | sudo tee /etc/modprobe.d/v4l2loopback.conf

**Comment by Doriangaensslen** [comment]
`sudo rmmod v4l2loopback` before starting obs helped!
