### ISSUE TITLE
can't capture widows secure desktop (for example winlogon)

### ISSUE THREAD

**Issue by ckelsel** [obsproject/obs-studio#4353]
## Platform

Operating system and version: Windows 10
OBS Studio version: 25.0.8
OBS Log file:

## Expected Behavior

start record, press Ctrl+Alt+Del，video of record should capture secure desktop
## Current Behavior

video is black.

## Steps to Reproduce

1. start record
2. press ctrl + alt + del
3. stop record
4. open xx.mkv file, we will see black picture after press ctrl + alt + del

**Comment by WizardCM** [comment]
This is expected behaviour.
