### ISSUE TITLE
UI: Crash on missing files close button press

### ISSUE THREAD

**Issue by cpyarger** [obsproject/obs-studio#4359]
## Platform

Operating system and version: 10
OBS Studio version: master
OBS Log file: nothing interesting about the problem is there

## Expected Behavior
the dialog should close as it does for the cancel button

## Current Behavior

if you click here 
![image](https://user-images.githubusercontent.com/1778298/111523703-fc3dfc00-8731-11eb-88f1-a2bb88f06d64.png)

obs crashes

![image](https://user-images.githubusercontent.com/1778298/111523638-e29cb480-8731-11eb-846d-1dfc417eb564.png)

## Steps to Reproduce

1. open obs with missing files, 
2. hit the close button shown above
3. boom!

**Comment by notr1ch** [comment]
Can't seem to reproduce this here.

**Comment by exeldro** [comment]
I have seen this crash myself too, but have not taken the time to investigate yet.

**Comment by WizardCM** [comment]
Could you post either an OBS crash log or the bottom half of the call stack from your screenshot?

**Comment by cpyarger** [comment]
![image](https://user-images.githubusercontent.com/1778298/111547728-fbb45e00-874f-11eb-888d-6d80b1759afc.png)
 It is not generating a log file

**Comment by WizardCM** [comment]
Crash logs are not generated when you have a debugger attached.

**Comment by cpyarger** [comment]
https://obsproject.com/logs/zKulthz8hD1N-qn1

**Comment by WizardCM** [comment]
I can't reproduce this issue on latest master with Qt 5.15.2, either on Debug or RelWithDebInfo.
