### ISSUE TITLE
Missing setting to change the no signal image (Virtual Cam)

### ISSUE THREAD

**Issue by Meetsch** [obsproject/obs-studio#4366]
The no signal image is located here:
`C:\Program Files\obs-studio\data\obs-plugins\win-dshow\placeholder.png`

But the issue is that if we change this image it is overwritten each time we update OBS.

We should have a profile setting to set the image to another file.

**Comment by dodgepong** [comment]
First: Don't delete the issue template when you submit a new issue.

Second: This feature isn't "missing" as we decided not to add a setting for it. If you want to request it as a feature, post it on ideas.obsproject.com.

**Comment by Meetsch** [comment]
Thanks

Here is the idea to vote on:
https://ideas.obsproject.com/posts/1325/add-setting-to-replace-placeholder-png
