### ISSUE TITLE
[win-dshow/ffmpeg-decode] Memory leak caused by using incorrect API

### ISSUE THREAD

**Issue by wangshaohui1314** [obsproject/obs-studio#4367]
## Platform

Operating system and version: WIN10 64bit
OBS Studio version: 26.1.2
OBS Log file: none

## Expected Behavior

After choosing video format for camera source between MJPG and H264, memory usage should not be more and more.

## Current Behavior

After choosing video format for camera source between MJPG and H264, memory usage is being more and more.

## Steps to Reproduce

1. connect a camera whose video format includes MJPG and H265, such as Logitch C920.
2. add camera source and open property window.
3. choose video format as MJPG;
4. choose video format as H265;
5. repeat (3) and (4), we can find memory usage is being more and more, and it won't reduce anly more.

## Additional information

**file:** https://github.com/obsproject/obs-studio/blob/master/plugins/win-dshow/ffmpeg-decode.c
**function:** ffmpeg_decode_free
**desc:** While freeing decode->hw_frame and decode->frame, we should use av_frame_free() instead of av_free(). Otherwise, memory leak happen.

**Comment by WizardCM** [comment]
Please fill in the issue template.

Additionally, feel free to submit a PR yourself with these changes, as that is the fastest way for the solution to be tested & merged.

**Comment by wangshaohui1314** [comment]
@WizardCM
In fact， every time when I try to push my commit to fix an issue, I will always receive a permission error (403).
Can you help fix this error ?

_git.exe push --progress "origin" windshow_DecodeMemoryLeak_branch
remote: Permission to obsproject/obs-studio.git denied to wangshaohui1314.
fatal: unable to access 'https://github.com/obsproject/obs-studio/': The requested URL returned error: 403_

**Comment by WizardCM** [comment]
You need to push to your own repository in a branch (you can clone it first), then submit the PR to the main repository. You can try following [this guide](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request). May be worth starting [here](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-forks).

**Comment by wangshaohui1314** [comment]
Oh~~ I was just pushing code on my own branch named _windshow_DecodeMemoryLeak_branch_.
But 403 is still received ~

**Comment by RytoEX** [comment]
> @WizardCM
> In fact， every time when I try to push my commit to fix an issue, I will always receive a permission error (403).
> Can you help fix this error ?
> 
> _git.exe push --progress "origin" windshow_DecodeMemoryLeak_branch
> remote: Permission to obsproject/obs-studio.git denied to wangshaohui1314.
> fatal: unable to access 'https://github.com/obsproject/obs-studio/': The requested URL returned error: 403_

`git push` pushes local code (your local branch "windshow_DecodeMemoryLeak_branch") to a remote repository.  The error message you posted clearly indicates that you are trying to push to the obsproject/obs-studio repo.  Specifically this part:

> remote: Permission to **_obsproject/obs-studio.git_** denied to wangshaohui1314.

You need to make your own fork of the obs-studio repo, clone that, make your changes locally, and git push to your fork.  Then you can make a Pull Request.  Please check the links @WizardCM provided above.
