### ISSUE TITLE
Crash in Qt5 metacall when switching Scene Collections after toggling visibility of a scene item

### ISSUE THREAD

**Issue by Xaymar** [obsproject/obs-studio#4374]
## Platform

Operating system and version: Windows 10 20H2 (March 2021 Update)
OBS Studio version: 26.0.x, 26.1.x, master
OBS Log file: [2021-03-19 08-44-02.txt](https://github.com/obsproject/obs-studio/files/6169413/2021-03-19.08-44-02.txt)

## Expected Behavior
Switching the Scene Collection should work fine without error.

## Current Behavior
OBS Studio crashes without any crash dialog appearing at all.

## Steps to Reproduce

1. Download [this archive](https://cdn.xaymar.com/share/2021-03-19/obsstudio-4374.zip) and a portable (.zip) version of OBS Studio.
2. Extract both into the same directory, then run the portable version with `--portable` as arguments.
3. Toggle the visibility of the Color Source and **change nothing else!**
4. Change the Scene Collection to "First" or "Second".
5. Crash

## Additional information
<details><summary>Call Stack</summary><pre>
obs64.exe!OBSRef<obs_scene *,&obs_scene_addref,&obs_scene_release>::OBSRef<obs_scene *,&obs_scene_addref,&obs_scene_release>(const OBSRef<obs_scene *,&obs_scene_addref,&obs_scene_release> & ref) Line 68
	at D:\Projects\Elgato\obs-studio\libobs\obs.hpp(68)
obs64.exe!QtPrivate::QVariantValueHelper<OBSRef<obs_scene *,&obs_scene_addref,&obs_scene_release>>::metaType(const QVariant & v={...}) Line 744
	at D:\Tools\SDKs\Qt\5.15.2\msvc2019_64\include\QtCore\qvariant.h(744)
obs64.exe!QtPrivate::MetaTypeInvoker<QtPrivate::QVariantValueHelper<OBSRef<obs_scene *,&obs_scene_addref,&obs_scene_release>>,QVariant const &,OBSRef<obs_scene *,&obs_scene_addref,&obs_scene_release>>::invoke(const QVariant & a={...}) Line 116
	at D:\Tools\SDKs\Qt\5.15.2\msvc2019_64\include\QtCore\qvariant.h(116)
obs64.exe!qvariant_cast<OBSRef<obs_scene *,&obs_scene_addref,&obs_scene_release>>(const QVariant & v={...}) Line 879
	at D:\Tools\SDKs\Qt\5.15.2\msvc2019_64\include\QtCore\qvariant.h(879)
obs64.exe!QVariant::value<OBSRef<obs_scene *,&obs_scene_addref,&obs_scene_release>>() Line 367
	at D:\Tools\SDKs\Qt\5.15.2\msvc2019_64\include\QtCore\qvariant.h(367)
obs64.exe!GetOBSRef<OBSRef<obs_scene *,&obs_scene_addref,&obs_scene_release>>(QListWidgetItem * item=0x0000025af463afb0) Line 130
	at D:\Projects\Elgato\obs-studio\UI\window-basic-main.cpp(130)
obs64.exe!OBSBasic::on_scenes_currentItemChanged(QListWidgetItem * current=0x0000025af463afb0, QListWidgetItem * prev=0x0000000000000000) Line 4475
	at D:\Projects\Elgato\obs-studio\UI\window-basic-main.cpp(4475)
obs64.exe!OBSBasic::qt_static_metacall(QObject * _o=0x0000025ae9816760, QMetaObject::Call _c=InvokeMetaMethod, int _id=144, void * * _a=0x000000a5674f0a70) Line 1241
	at D:\Projects\Elgato\obs-studio\build\UI\obs_autogen\include_Debug\EWIEGA46WW\moc_window-basic-main.cpp(1241)
obs64.exe!OBSBasic::qt_metacall(QMetaObject::Call _c=InvokeMetaMethod, int _id=144, void * * _a=0x000000a5674f0a70) Line 1453
	at D:\Projects\Elgato\obs-studio\build\UI\obs_autogen\include_Debug\EWIEGA46WW\moc_window-basic-main.cpp(1453)
Qt5Cored.dll!QMetaObject::metacall() + 168 bytes
Qt5Cored.dll!00007ff866a26d59()
Qt5Cored.dll!QMetaObject::activate() + 103 bytes
Qt5Widgetsd.dll!QListWidget::currentItemChanged() + 102 bytes
Qt5Widgetsd.dll!QListWidget::sortOrder() + 12123 bytes
Qt5Widgetsd.dll!QListWidget::qt_static_metacall() + 1148 bytes
Qt5Cored.dll!00007ff866a26ccf()
Qt5Cored.dll!QMetaObject::activate() + 103 bytes
Qt5Cored.dll!QItemSelectionModel::currentChanged() + 101 bytes
Qt5Cored.dll!QItemSelectionModel::setCurrentIndex() + 440 bytes
Qt5Widgetsd.dll!QAbstractItemView::focusInEvent() + 416 bytes
Qt5Widgetsd.dll!QWidget::event() + 2577 bytes
Qt5Widgetsd.dll!QFrame::event() + 63 bytes
Qt5Widgetsd.dll!QAbstractScrollArea::event() + 2044 bytes
Qt5Widgetsd.dll!QAbstractItemView::event() + 409 bytes
Qt5Widgetsd.dll!QListView::event() + 29 bytes
Qt5Widgetsd.dll!QListWidget::event() + 29 bytes
Qt5Widgetsd.dll!QApplicationPrivate::notify_helper() + 423 bytes
Qt5Widgetsd.dll!QApplication::notify() + 14783 bytes
Qt5Cored.dll!QCoreApplication::notifyInternal2() + 287 bytes
Qt5Cored.dll!QCoreApplication::sendEvent() + 66 bytes
Qt5Widgetsd.dll!QApplicationPrivate::setFocusWidget() + 583 bytes
Qt5Widgetsd.dll!QWidget::setFocus() + 807 bytes
Qt5Widgetsd.dll!QWidget::focusNextPrevChild() + 624 bytes
Qt5Widgetsd.dll!QWidget::focusNextPrevChild() + 153 bytes
Qt5Widgetsd.dll!QWidget::focusNextPrevChild() + 153 bytes
Qt5Widgetsd.dll!QWidget::focusNextPrevChild() + 153 bytes
Qt5Widgetsd.dll!QWidget::focusNextPrevChild() + 153 bytes
Qt5Widgetsd.dll!QAbstractItemView::focusNextPrevChild() + 375 bytes
Qt5Widgetsd.dll!QWidget::focusNextPrevChild() + 153 bytes
Qt5Widgetsd.dll!QWidget::focusNextPrevChild() + 153 bytes
Qt5Widgetsd.dll!QWidgetPrivate::hide_helper() + 421 bytes
Qt5Widgetsd.dll!QWidgetPrivate::setVisible() + 1130 bytes
Qt5Widgetsd.dll!QWidget::setVisible() + 136 bytes
Qt5Widgetsd.dll!QWidget::hide() + 37 bytes
Qt5Widgetsd.dll!00007ff86b4def97()
Qt5Widgetsd.dll!QAbstractItemView::rowsAboutToBeRemoved() + 1758 bytes
Qt5Widgetsd.dll!QListView::rowsAboutToBeRemoved() + 79 bytes
Qt5Widgetsd.dll!QAbstractItemView::qt_static_metacall() + 1088 bytes
Qt5Cored.dll!00007ff866a26ccf()
Qt5Cored.dll!QMetaObject::activate() + 103 bytes
Qt5Cored.dll!QAbstractItemModel::rowsAboutToBeRemoved() + 139 bytes
Qt5Cored.dll!QAbstractItemModel::beginRemoveRows() + 308 bytes
obs64.exe!SourceTreeModel::Remove(obs_scene_item * item=0x0000025af422d800) Line 756
	at D:\Projects\Elgato\obs-studio\UI\source-tree.cpp(756)
obs64.exe!SourceTree::Remove(OBSRef<obs_scene_item *,&obs_sceneitem_addref,&obs_sceneitem_release> item={...}) Line 1506
	at D:\Projects\Elgato\obs-studio\UI\source-tree.cpp(1506)
obs64.exe!SourceTree::qt_static_metacall(QObject * _o=0x0000025aece80800, QMetaObject::Call _c=InvokeMetaMethod, int _id=2, void * * _a=0x000000a5674f3e40) Line 372
	at D:\Projects\Elgato\obs-studio\build\UI\obs_autogen\include_Debug\EWIEGA46WW\moc_source-tree.cpp(372)
Qt5Cored.dll!QMetaMethod::invoke() + 1272 bytes
Qt5Cored.dll!QMetaObject::invokeMethod() + 1533 bytes
Qt5Cored.dll!QMetaObject::invokeMethod() + 3674 bytes
obs64.exe!SourceTreeItem::ReconnectSignals::__l2::<lambda>(void * data=0x0000025af3d22010, calldata * cd=0x000000a5674f5bc8) Line 191
	at D:\Projects\Elgato\obs-studio\UI\source-tree.cpp(191)
obs64.exe!void <lambda>(void *, calldata *)::<lambda_invoker_cdecl>(void * data=0x0000025af3d22010, calldata * cd=0x000000a5674f5bc8) Line 197
	at D:\Projects\Elgato\obs-studio\UI\source-tree.cpp(197)
obs.dll!signal_handler_signal(signal_handler * handler=0x0000025af43c0440, const char * signal=0x00007ff869f15f98, calldata * params=0x000000a5674f5bc8) Line 332
	at D:\Projects\Elgato\obs-studio\libobs\callback\signal.c(332)
obs.dll!signal_parent(obs_scene * parent=0x0000025af43be8c0, const char * command=0x00007ff869f15f98, calldata * params=0x000000a5674f5bc8) Line 2019
	at D:\Projects\Elgato\obs-studio\libobs\obs-scene.c(2019)
obs.dll!signal_item_remove(obs_scene_item * item=0x0000025af422d800) Line 71
	at D:\Projects\Elgato\obs-studio\libobs\obs-scene.c(71)
obs.dll!remove_without_release(obs_scene_item * item=0x0000025af422d800) Line 150
	at D:\Projects\Elgato\obs-studio\libobs\obs-scene.c(150)
obs.dll!remove_all_items(obs_scene * scene=0x0000025af43be8c0) Line 169
	at D:\Projects\Elgato\obs-studio\libobs\obs-scene.c(169)
obs.dll!scene_destroy(void * data=0x0000025af43be8c0) Line 185
	at D:\Projects\Elgato\obs-studio\libobs\obs-scene.c(185)
obs.dll!obs_source_destroy(obs_source * source=0x0000025af43aebc0) Line 649
	at D:\Projects\Elgato\obs-studio\libobs\obs-source.c(649)
obs.dll!obs_source_release(obs_source * source=0x0000025af43aebc0) Line 733
	at D:\Projects\Elgato\obs-studio\libobs\obs-source.c(733)
obs.dll!obs_scene_release(obs_scene * scene=0x0000025af43be8c0) Line 1566
	at D:\Projects\Elgato\obs-studio\libobs\obs-scene.c(1566)
obs64.exe!OBSRef<obs_scene *,&obs_scene_addref,&obs_scene_release>::~OBSRef<obs_scene *,&obs_scene_addref,&obs_scene_release>() Line 71
	at D:\Projects\Elgato\obs-studio\libobs\obs.hpp(71)
obs64.exe!`anonymous namespace'::SignalContainer<OBSRef<obs_scene *,&obs_scene_addref,&obs_scene_release>>::~SignalContainer<OBSRef<obs_scene *,&obs_scene_addref,&obs_scene_release>>()
obs64.exe!`anonymous namespace'::SignalContainer<OBSRef<obs_scene *,&obs_scene_addref,&obs_scene_release>>::`scalar deleting destructor'(unsigned int)
obs64.exe!QtMetaTypePrivate::QMetaTypeFunctionHelper<`anonymous namespace'::SignalContainer<OBSRef<obs_scene *,&obs_scene_addref,&obs_scene_release>>,1>::Destruct(void * t=0x0000025a80e5e330) Line 820
	at D:\Tools\SDKs\Qt\5.15.2\msvc2019_64\include\QtCore\qmetatype.h(820)
Qt5Cored.dll!QMetaType::construct() + 2581 bytes
Qt5Cored.dll!QMetaType::construct() + 4799 bytes
Qt5Cored.dll!00007ff8669df551()
Qt5Cored.dll!QMetaType::destruct() + 56 bytes
Qt5Cored.dll!00007ff866a4da66()
Qt5Cored.dll!QVariant::~QVariant() + 138 bytes
Qt5Widgetsd.dll!00007ff86b556beb()
Qt5Widgetsd.dll!QListWidgetItem::`default constructor closure'() + 471 bytes
Qt5Widgetsd.dll!QListWidget::d_func() + 938 bytes
Qt5Widgetsd.dll!QListWidgetItem::foreground() + 404 bytes
Qt5Widgetsd.dll!00007ff86b556b5f()
Qt5Widgetsd.dll!00007ff86b556b9a()
Qt5Widgetsd.dll!QListWidgetItem::`default constructor closure'() + 311 bytes
Qt5Widgetsd.dll!QListWidgetItem::~QListWidgetItem() + 99 bytes
obs64.exe!QListWidgetItem::`scalar deleting destructor'(unsigned int)
Qt5Widgetsd.dll!QListWidget::sortOrder() + 916 bytes
Qt5Widgetsd.dll!QListWidget::clear() + 73 bytes
obs64.exe!ClearListItems(QListWidget * widget=0x0000025aecd9e0a0) Line 46
	at D:\Projects\Elgato\obs-studio\UI\item-widget-helpers.cpp(46)
obs64.exe!OBSBasic::ClearSceneData() Line 4226
	at D:\Projects\Elgato\obs-studio\UI\window-basic-main.cpp(4226)
obs64.exe!OBSBasic::Load(const char * file=0x0000025af47ccea0) Line 926
	at D:\Projects\Elgato\obs-studio\UI\window-basic-main.cpp(926)
obs64.exe!OBSBasic::ChangeSceneCollection() Line 421
	at D:\Projects\Elgato\obs-studio\UI\window-basic-main-scene-collections.cpp(421)
obs64.exe!QtPrivate::FunctorCall<QtPrivate::IndexesList<>,QtPrivate::List<>,void,void (__cdecl OBSBasic::*)(void)>::call(void(OBSBasic::*)() f=0x000000a5674f8480, OBSBasic * o=0x0000025ae9816760, void * * arg=0x000000a5674f8810) Line 152
	at D:\Tools\SDKs\Qt\5.15.2\msvc2019_64\include\QtCore\qobjectdefs_impl.h(152)
obs64.exe!QtPrivate::FunctionPointer<void (__cdecl OBSBasic::*)(void)>::call<QtPrivate::List<>,void>(void(OBSBasic::*)() f=0x000000a5674f84e0, OBSBasic * o=0x0000025ae9816760, void * * arg=0x000000a5674f8810) Line 186
	at D:\Tools\SDKs\Qt\5.15.2\msvc2019_64\include\QtCore\qobjectdefs_impl.h(186)
obs64.exe!QtPrivate::QSlotObject<void (__cdecl OBSBasic::*)(void),QtPrivate::List<>,void>::impl(int which=1, QtPrivate::QSlotObjectBase * this_=0x0000025a80fc7a10, QObject * r=0x0000025ae9816760, void * * a=0x000000a5674f8810, bool * ret=0x0000000000000000) Line 419
	at D:\Tools\SDKs\Qt\5.15.2\msvc2019_64\include\QtCore\qobjectdefs_impl.h(419)
Qt5Cored.dll!00007ff8669ce9d2()
Qt5Cored.dll!00007ff866a26bb8()
Qt5Cored.dll!QMetaObject::activate() + 103 bytes
Qt5Widgetsd.dll!QAction::triggered() + 66 bytes
Qt5Widgetsd.dll!QAction::activate() + 345 bytes
Qt5Widgetsd.dll!00007ff86b3116c3()
Qt5Widgetsd.dll!00007ff86b3115a4()
Qt5Widgetsd.dll!QMenu::mouseReleaseEvent() + 256 bytes
Qt5Widgetsd.dll!QWidget::event() + 495 bytes
Qt5Widgetsd.dll!QMenu::event() + 1353 bytes
Qt5Widgetsd.dll!QApplicationPrivate::notify_helper() + 423 bytes
Qt5Widgetsd.dll!QApplication::notify() + 3605 bytes
Qt5Cored.dll!QCoreApplication::notifyInternal2() + 287 bytes
Qt5Cored.dll!QCoreApplication::sendSpontaneousEvent() + 59 bytes
Qt5Widgetsd.dll!QApplicationPrivate::sendMouseEvent() + 1138 bytes
Qt5Widgetsd.dll!QSizePolicy::QSizePolicy() + 7310 bytes
Qt5Widgetsd.dll!QSizePolicy::QSizePolicy() + 2788 bytes
Qt5Widgetsd.dll!QApplicationPrivate::notify_helper() + 423 bytes
Qt5Widgetsd.dll!QApplication::notify() + 1320 bytes
Qt5Cored.dll!QCoreApplication::notifyInternal2() + 287 bytes
Qt5Cored.dll!QCoreApplication::sendSpontaneousEvent() + 59 bytes
Qt5Guid.dll!QGuiApplicationPrivate::processMouseEvent() + 3027 bytes
Qt5Guid.dll!QGuiApplicationPrivate::processWindowSystemEvent() + 166 bytes
Qt5Guid.dll!QWindowSystemInterface::sendWindowSystemEvents() + 194 bytes
qwindowsd.dll!00007ff867b64802()
Qt5Cored.dll!QEventDispatcherWin32::processEvents() + 162 bytes
qwindowsd.dll!00007ff867b647b4()
Qt5Cored.dll!QEventLoop::processEvents() + 123 bytes
Qt5Cored.dll!QEventLoop::exec() + 420 bytes
Qt5Cored.dll!QCoreApplication::exec() + 361 bytes
Qt5Guid.dll!QGuiApplication::exec() + 24 bytes
Qt5Widgetsd.dll!QApplication::exec() + 10 bytes
obs64.exe!run_program(std::basic_fstream<char,std::char_traits<char>> & logFile={...}, int argc=2, char * * argv=0x0000025ae7488f80) Line 2087
	at D:\Projects\Elgato\obs-studio\UI\obs-app.cpp(2087)
obs64.exe!main(int argc=2, char * * argv=0x0000025ae7488f80) Line 2762
	at D:\Projects\Elgato\obs-studio\UI\obs-app.cpp(2762)
obs64.exe!WinMain(HINSTANCE__ * __formal=0x00007ff6cf240000, HINSTANCE__ * __formal=0x0000000000000000, char * __formal=0x0000025ae7444917, int __formal=10) Line 97
	at C:\Users\qt\work\qt\qtbase\src\winmain\qtmain_win.cpp(97)
obs64.exe!invoke_main() Line 107
	at D:\a01\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl(107)
obs64.exe!__scrt_common_main_seh() Line 288
	at D:\a01\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl(288)
obs64.exe!__scrt_common_main() Line 331
	at D:\a01\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl(331)
obs64.exe!WinMainCRTStartup(void * __formal=0x000000a5672e9000) Line 17
	at D:\a01\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_winmain.cpp(17)
kernel32.dll!BaseThreadInitThunk() + 20 bytes
ntdll.dll!RtlUserThreadStart() + 33 bytes
</pre></details>

**Comment by Xaymar** [comment]
Earliest known _working_ version: 25.0.8

**Comment by WizardCM** [comment]
I can't reproduce this with latest master and Qt 5.15.2.

**Comment by Xaymar** [comment]
[Video](https://youtu.be/mgzvX7vLoDo)

**Comment by Xaymar** [comment]
Successfully reproduced on OBS Studio 27.0.0, this crash completely bypasses the crash handler.

**Update 2021-06-04:** Further testing revealed this to be caused by Studio Mode. Having it enabled from the start causes this metacall crash.

**Comment by Xaymar** [comment]
Closing as requested.
