### ISSUE TITLE
Scam site liveobs.com ?

### ISSUE THREAD

**Issue by schweini** [obsproject/obs-studio#4379]
Sorry if this is the wrong place to report this, but:

I just saw an ad on Facebook linking to the website https://liveobs.com/ which seems to be a (only partly functional) copy of the official OBS website.

The ad coaxes people to download a new version, which supposedly can't use the regular update mechanism, but has to be installed on top of your previous installation. Quite fishy.

I have reported the probably fraudulent ad to FB, but the website is of course still up.

Sadly, FB wont let me see stuff I have reported, so I can't include a screenshot.

**Comment by notr1ch** [comment]
We're aware of this, unfortunately Facebook are very slow to respond and the domain keeps bouncing between hosting providers. Reporting the site at [Google Safebrowsing](https://safebrowsing.google.com/safebrowsing/report_badware/?hl=en) might be helpful.
