### ISSUE TITLE
[Crash] cannot start program from scheuled task

### ISSUE THREAD

**Issue by mcDandy** [obsproject/obs-studio#4380]
## Platform

Operating system and version: Windows 10 21H1 (19043.867)
OBS Studio version: 26.1.1
OBS Log file:  
[2021-03-20 13-00-37.txt](https://github.com/obsproject/obs-studio/files/6175725/2021-03-20.13-00-37.txt)

## Expected Behavior

OBS should start and record
## Current Behavior

After running scheuled jobs it threw errors about missing locale (could not find locale/en_us.ini) and (could not find locale) after
## Steps to Reproduce

1. create basic scheuled task which starts obs and begins recording (Program or script: ["C:\Program Files\obs-studio\bin\64bit\obs64.exe"] arguments:[--startrecording -m --scene "animeklub stream 2"]) //scene name should not matter
![image](https://user-images.githubusercontent.com/18588943/111873312-fcd3ce00-898f-11eb-925b-90a7aa026993.png)
how it looks while editing event
2. wait for event or force trigger it
3. program will not load

## Additional information

https://obsproject.com/logs/3_4JwB8VX--2FoZd

**Comment by notr1ch** [comment]
This is because you did not specify the working directory.
