### ISSUE TITLE
Assumed Memory Leak with video Media Sources for OBS Mac

### ISSUE THREAD

**Issue by kcannick** [obsproject/obs-studio#4382]
OBS for Mac seems to have memory leak issue associated with playing back Media. I've been dealing with the issue for nearly a year after upgrading. I assumed it was my laptop (which was a 2015 Macbook pro) I upgraded to a new Macbook with 64G of Ram and i9 processor... and have the same issue. Digging into stats I realized OBS was creeping up to 9-14 Gigs of ram for a very basic setup (4 scenes no more than 5 sources each). After some research I eliminated VLC source and it helped but ultimately only delayed the performance breakdown as it still occurs... Created empty project and added only 2 scenes with 2 Media Sources and image slide show (Video 1: 8MB; Video 2: 100MB; Slideshow: 10 jpgs) With this minimalist project Memory Usage ballooned to 3 Gigs without streaming or recording... Just switching back and forth between scenes over time

## Platform

Operating system and version: MacOS Big Sur 11.2.3
OBS Studio version: 26.1.2
OBS Log file:

## Expected Behavior
Switch between scenes

## Current Behavior
After memory usage reaches a certain point, OBS UI becomes unresponsive

## Steps to Reproduce
1. Create empty scene collection
2. Create 2-3 scenes 
3. Add one media source per scene with a Video (I'm assuming larger files will help reproduce faster)
4. Switch between scenes periodically and watch Memory usage balloon
5. Switch away from OBS to another program then back to OBS and notice UI becomes unresponsive.

## Additional information
Can't produce log report for sessions where it becomes critical because I have to force quit.

<details>
  <summary>Crash Log</summary>
<pre>00:05:24.327: CPU Name: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
00:05:24.327: CPU Speed: 2300MHz
00:05:24.327: Physical Cores: 8, Logical Cores: 16
00:05:24.327: Physical Memory: 65536MB Total
00:05:24.327: OS Name: Mac OS X (NSMACHOperatingSystem)
00:05:24.327: OS Version: Version 11.2.3 (Build 20D91)
00:05:24.327: Kernel Version: 20.3.0
00:05:24.329: hotkeys-cocoa: Getting keyboard keys failed
00:05:24.329: hotkeys-cocoa: Getting keyboard keys failed
00:05:24.329: hotkeys-cocoa: Using layout 'com.apple.keylayout.US'
00:05:24.330: Current Date/Time: 2021-03-21, 00:05:24
00:05:24.330: Browser Hardware Acceleration: true
00:05:24.330: Portable mode: false
00:05:24.426: OBS 26.1.2 (mac)
00:05:24.426: ---------------------------------
00:05:24.427: ---------------------------------
00:05:24.427: audio settings reset:
00:05:24.427: 	samples per sec: 48000
00:05:24.427: 	speakers:        2
00:05:24.428: ---------------------------------
00:05:24.428: Initializing OpenGL...
00:05:24.450: Loading up OpenGL on adapter ATI Technologies Inc. AMD Radeon Pro 5500M OpenGL Engine
00:05:24.450: OpenGL loaded successfully, version 4.1 ATI-4.2.15, shading language 4.10
00:05:24.520: ---------------------------------
00:05:24.520: video settings reset:
00:05:24.520: 	base resolution:   1280x720
00:05:24.520: 	output resolution: 1280x720
00:05:24.520: 	downscale filter:  Bicubic
00:05:24.520: 	fps:               30/1
00:05:24.520: 	format:            NV12
00:05:24.520: 	YUV mode:          709/Partial
00:05:24.520: NV12 texture support not available
00:05:24.520: Audio monitoring device:
00:05:24.520: 	name: Default
00:05:24.520: 	id: default
00:05:24.520: ---------------------------------
00:05:24.522: Failed to load 'en-US' text for module: 'decklink-captions.so'
00:05:24.523: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
00:05:24.599: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
00:05:24.599: No blackmagic support
00:05:24.601: [mac-virtualcam] version=1.3.0
00:05:24.663: obs_register_encoder: Encoder id 'vt_h264_hw' already exists!  Duplicate library?
00:05:24.663: [VideoToolbox encoder]: Adding VideoToolbox H264 encoders
00:05:24.666: [obs-browser]: Version 2.10.0
00:05:24.666: [obs-browser]: CEF Version 85.0.0-HEAD.2273+g93b66a0+chromium-85.0.4183.121
00:05:24.689: VLC found, VLC video source enabled
00:05:24.692: Failed to load 'en-US' text for module: 'StreamDeckPlugin.so'
00:05:24.693: Ignoring old obs-browser.so version
00:05:24.693: ---------------------------------
00:05:24.693:   Loaded Modules:
00:05:24.693:     StreamDeckPlugin.so
00:05:24.693:     vlc-video.so
00:05:24.693:     text-freetype2.so
00:05:24.693:     rtmp-services.so
00:05:24.693:     obs-x264.so
00:05:24.693:     obs-vst.so
00:05:24.693:     obs-transitions.so
00:05:24.693:     obs-outputs.so
00:05:24.693:     obs-filters.so
00:05:24.693:     obs-ffmpeg.so
00:05:24.693:     obs-browser.so
00:05:24.693:     mac-vth264.so
00:05:24.693:     mac-virtualcam.so
00:05:24.693:     mac-syphon.so
00:05:24.693:     mac-decklink.so
00:05:24.693:     mac-capture.so
00:05:24.693:     mac-avcapture.so
00:05:24.693:     image-source.so
00:05:24.693:     frontend-tools.so
00:05:24.693:     decklink-ouput-ui.so
00:05:24.693:     decklink-captions.so
00:05:24.693:     coreaudio-encoder.so
00:05:24.693: ---------------------------------
00:05:24.693: os_dlopen(../obs-plugins/obs-browser->../obs-plugins/obs-browser.so): dlopen(../obs-plugins/obs-browser.so, 257): image not found
00:05:24.693: 
00:05:24.694: ==== Startup complete ===============================================
00:05:24.707: All scene data cleared
00:05:24.707: ------------------------------------------------
00:05:24.711: Switched to scene 'Scene'
00:05:24.711: ------------------------------------------------
00:05:24.712: Loaded scenes:
00:05:24.712: - scene 'Scene':
00:05:24.712: ------------------------------------------------
00:05:34.402: User added source 'Image Slide Show' (slideshow) to scene 'Scene'
00:08:41.198: [Media Source 'Media Source']: settings:
00:08:41.198: 	input:                   
00:08:41.198: 	input_format:            (null)
00:08:41.198: 	speed:                   100
00:08:41.198: 	is_looping:              no
00:08:41.198: 	is_hw_decoding:          no
00:08:41.198: 	is_clear_on_media_end:   yes
00:08:41.198: 	restart_on_activate:     yes
00:08:41.198: 	close_when_inactive:     no
00:08:41.201: User added source 'Media Source' (ffmpeg_source) to scene 'Scene'
00:09:03.350: [Media Source 'Media Source']: settings:
00:09:03.350: 	input:                   /Users/kelbycannick/Documents/Makin' It Magazine/_PROJECTS/_Upcoming/One Love One Mic/One Love One Mic - 2021-01 Promo Video - Cade Infinite.mov
00:09:03.350: 	input_format:            (null)
00:09:03.350: 	speed:                   100
00:09:03.350: 	is_looping:              no
00:09:03.350: 	is_hw_decoding:          no
00:09:03.350: 	is_clear_on_media_end:   yes
00:09:03.350: 	restart_on_activate:     yes
00:09:03.350: 	close_when_inactive:     no
00:09:57.956: User added scene 'Scene 2'
00:09:57.957: User switched to scene 'Scene 2'
00:10:00.734: User switched to scene 'Scene'
00:10:06.657: User switched to scene 'Scene 2'
00:10:17.697: [Media Source 'Media Source 2']: settings:
00:10:17.697: 	input:                   
00:10:17.697: 	input_format:            (null)
00:10:17.697: 	speed:                   100
00:10:17.697: 	is_looping:              no
00:10:17.697: 	is_hw_decoding:          no
00:10:17.697: 	is_clear_on_media_end:   yes
00:10:17.697: 	restart_on_activate:     yes
00:10:17.697: 	close_when_inactive:     no
00:10:17.699: User added source 'Media Source 2' (ffmpeg_source) to scene 'Scene 2'
00:18:35.572: [Media Source 'Media Source 2']: settings:
00:18:35.572: 	input:                   /Users/kelbycannick/Documents/Makin' It Magazine/_PROJECTS/Dollar Music Reviews/OBS/Video Premiere/Music Video.mp4
00:18:35.572: 	input_format:            (null)
00:18:35.572: 	speed:                   100
00:18:35.572: 	is_looping:              yes
00:18:35.572: 	is_hw_decoding:          no
00:18:35.572: 	is_clear_on_media_end:   yes
00:18:35.572: 	restart_on_activate:     yes
00:18:35.572: 	close_when_inactive:     no
00:19:37.681: User switched to scene 'Scene'
00:19:45.910: User switched to scene 'Scene 2'
00:19:50.777: User switched to scene 'Scene'
00:19:54.496: User switched to scene 'Scene 2'
00:19:54.547: adding 42 milliseconds of audio buffering, total audio buffering is now 42 milliseconds (source: Media Source 2)
00:19:54.547: 
00:20:27.166: User switched to scene 'Scene'
00:20:31.210: User switched to scene 'Scene 2'
00:20:32.708: User switched to scene 'Scene'
00:20:33.600: User switched to scene 'Scene 2'
00:21:05.522: User switched to scene 'Scene'
00:21:06.417: User switched to scene 'Scene 2'
00:21:08.738: User switched to scene 'Scene'
00:21:14.828: User switched to scene 'Scene 2'
00:21:19.327: User switched to scene 'Scene'
00:26:36.359: User switched to scene 'Scene 2'
00:26:38.060: User switched to scene 'Scene'
00:26:41.040: User switched to scene 'Scene 2'
00:31:03.410: User switched to scene 'Scene'
00:31:10.097: User switched to scene 'Scene 2'
00:42:01.750: adding 256 milliseconds of audio buffering, total audio buffering is now 298 milliseconds (source: Media Source 2)
00:42:01.750: 
00:52:27.430: User switched to scene 'Scene'
00:52:58.907: User switched to scene 'Scene 2'
00:56:00.467: Max audio buffering reached!
00:56:00.467: adding 661 milliseconds of audio buffering, total audio buffering is now 960 milliseconds (source: Media Source 2)
00:56:00.467: 
01:01:57.652: User switched to scene 'Scene'
01:11:21.860: User switched to scene 'Scene 2'
01:11:38.371: User added source 'Image' (image_source) to scene 'Scene 2'
01:12:26.629: User switched to scene 'Scene'
01:16:47.587: [Media Source 'Media Source']: settings:
01:16:47.587: 	input:                   /Users/kelbycannick/Documents/Makin' It Magazine/_PROJECTS/_Upcoming/One Love One Mic/One Love One Mic - 2021-01 Promo Video - Cade Infinite.mov
01:16:47.587: 	input_format:            (null)
01:16:47.587: 	speed:                   100
01:16:47.587: 	is_looping:              yes
01:16:47.587: 	is_hw_decoding:          no
01:16:47.587: 	is_clear_on_media_end:   yes
01:16:47.587: 	restart_on_activate:     yes
01:16:47.587: 	close_when_inactive:     no
01:16:52.458: [Media Source 'Media Source']: settings:
01:16:52.458: 	input:                   /Users/kelbycannick/Documents/Makin' It Magazine/_PROJECTS/_Upcoming/One Love One Mic/One Love One Mic - 2021-01 Promo Video - Cade Infinite.mov
01:16:52.458: 	input_format:            (null)
01:16:52.458: 	speed:                   100
01:16:52.458: 	is_looping:              yes
01:16:52.458: 	is_hw_decoding:          no
01:16:52.458: 	is_clear_on_media_end:   yes
01:16:52.458: 	restart_on_activate:     yes
01:16:52.458: 	close_when_inactive:     no
01:16:54.000: User switched to scene 'Scene 2'
01:16:56.527: User switched to scene 'Scene'
02:35:01.704: User switched to scene 'Scene 2'
02:37:37.177: User switched to scene 'Scene'
02:38:01.482: User switched to scene 'Scene 2'
02:38:54.009: User switched to scene 'Scene'
02:39:20.647: User switched to scene 'Scene 2'
02:40:33.202: User added source 'Scene' (scene) to scene 'Scene 2'
02:41:05.351: User switched to scene 'Scene'
02:41:32.641: [Media Source 'Media Source']: settings:
02:41:32.641: 	input:                   /Users/kelbycannick/Documents/Makin' It Magazine/_PROJECTS/_Upcoming/One Love One Mic/One Love One Mic - 2021-01 Promo Video - Cade Infinite.mov
02:41:32.641: 	input_format:            (null)
02:41:32.641: 	speed:                   100
02:41:32.641: 	is_looping:              yes
02:41:32.641: 	is_hw_decoding:          no
02:41:32.641: 	is_clear_on_media_end:   yes
02:41:32.641: 	restart_on_activate:     yes
02:41:32.641: 	close_when_inactive:     yes
02:45:06.089: User switched to scene 'Scene 2'
02:46:20.730: User switched to scene 'Scene'
02:46:25.598: User switched to scene 'Scene 2'
02:48:14.121: User Removed source 'Image' (image_source) from scene 'Scene 2'
02:48:20.703: User switched to scene 'Scene'
02:48:23.558: User switched to scene 'Scene 2'
02:49:43.784: User switched to scene 'Scene'
02:49:51.877: User switched to scene 'Scene 2'
02:51:04.810: User switched to scene 'Scene'
02:51:06.015: User switched to scene 'Scene 2'
02:58:49.804: User switched to scene 'Scene'
02:58:55.772: User switched to scene 'Scene 2'
02:59:10.562: [Media Source 'Media Source 2']: settings:
02:59:10.562: 	input:                   /Users/kelbycannick/Documents/Makin' It Magazine/_PROJECTS/Dollar Music Reviews/OBS/Video Premiere/Music Video.mp4
02:59:10.562: 	input_format:            (null)
02:59:10.562: 	speed:                   100
02:59:10.562: 	is_looping:              yes
02:59:10.562: 	is_hw_decoding:          no
02:59:10.562: 	is_clear_on_media_end:   yes
02:59:10.562: 	restart_on_activate:     yes
02:59:10.562: 	close_when_inactive:     yes
02:59:18.095: User switched to scene 'Scene'
02:59:19.867: User switched to scene 'Scene 2'
02:59:22.011: User switched to scene 'Scene'
02:59:23.545: User switched to scene 'Scene 2'
03:14:00.715: User switched to scene 'Scene'
03:42:47.080: ==== Shutting down ==================================================
03:42:47.120: All scene data cleared
03:42:47.120: ------------------------------------------------
03:42:47.190: [Scripting] Total detached callbacks: 0
03:42:47.210: Freeing OBS context data
03:42:47.220: == Profiler Results =============================
03:42:47.220: run_program_init: 561.366 ms
03:42:47.220:  ┣OBSApp::AppInit: 2.696 ms
03:42:47.220:  ┃ ┗OBSApp::InitLocale: 1.45 ms
03:42:47.220:  ┗OBSApp::OBSInit: 427.237 ms
03:42:47.220:    ┣obs_startup: 2.646 ms
03:42:47.220:    ┗OBSBasic::OBSInit: 327.42 ms
03:42:47.220:      ┣OBSBasic::InitBasicConfig: 0.204 ms
03:42:47.220:      ┣OBSBasic::ResetAudio: 0.071 ms
03:42:47.220:      ┣OBSBasic::ResetVideo: 93.034 ms
03:42:47.220:      ┣OBSBasic::InitOBSCallbacks: 0.005 ms
03:42:47.220:      ┣OBSBasic::InitHotkeys: 0.032 ms
03:42:47.220:      ┣obs_load_all_modules: 172.642 ms
03:42:47.220:      ┃ ┣obs_init_module(coreaudio-encoder.so): 0.004 ms
03:42:47.220:      ┃ ┣obs_init_module(decklink-captions.so): 0.069 ms
03:42:47.220:      ┃ ┣obs_init_module(decklink-ouput-ui.so): 0.329 ms
03:42:47.220:      ┃ ┣obs_init_module(frontend-tools.so): 1.966 ms
03:42:47.220:      ┃ ┣obs_init_module(image-source.so): 0.005 ms
03:42:47.220:      ┃ ┣obs_init_module(mac-avcapture.so): 66.024 ms
03:42:47.220:      ┃ ┣obs_init_module(mac-capture.so): 0.005 ms
03:42:47.220:      ┃ ┣obs_init_module(mac-decklink.so): 0.649 ms
03:42:47.220:      ┃ ┣obs_init_module(mac-syphon.so): 0.002 ms
03:42:47.220:      ┃ ┣obs_init_module(mac-virtualcam.so): 0.03 ms
03:42:47.220:      ┃ ┣obs_init_module(mac-vth264.so): 61.487 ms
03:42:47.220:      ┃ ┣obs_init_module(obs-browser.so): 15.767 ms
03:42:47.220:      ┃ ┣obs_init_module(obs-ffmpeg.so): 0.009 ms
03:42:47.220:      ┃ ┣obs_init_module(obs-filters.so): 0.029 ms
03:42:47.220:      ┃ ┣obs_init_module(obs-outputs.so): 0.006 ms
03:42:47.220:      ┃ ┣obs_init_module(obs-transitions.so): 0.009 ms
03:42:47.220:      ┃ ┣obs_init_module(obs-vst.so): 0.012 ms
03:42:47.220:      ┃ ┣obs_init_module(obs-x264.so): 0.002 ms
03:42:47.220:      ┃ ┣obs_init_module(rtmp-services.so): 0.586 ms
03:42:47.220:      ┃ ┣obs_init_module(text-freetype2.so): 0.015 ms
03:42:47.220:      ┃ ┣obs_init_module(vlc-video.so): 0.733 ms
03:42:47.220:      ┃ ┗obs_init_module(StreamDeckPlugin.so): 0.534 ms
03:42:47.220:      ┣OBSBasic::ResetOutputs: 11.036 ms
03:42:47.220:      ┣OBSBasic::CreateHotkeys: 0.041 ms
03:42:47.220:      ┣OBSBasic::InitService: 1.237 ms
03:42:47.220:      ┣OBSBasic::InitPrimitives: 0.091 ms
03:42:47.220:      ┗OBSBasic::Load: 5.252 ms
03:42:47.220: obs_hotkey_thread(25 ms): min=0 ms, median=0 ms, max=0.068 ms, 99th percentile=0.001 ms, 100% below 25 ms
03:42:47.220: audio_thread(Audio): min=0 ms, median=0.077 ms, max=3956.08 ms, 99th percentile=0.572 ms
03:42:47.220: obs_graphics_thread(33.3333 ms): min=0.064 ms, median=1.289 ms, max=6038.19 ms, 99th percentile=4.912 ms, 99.9738% below 33.333 ms
03:42:47.220:  ┣tick_sources: min=0 ms, median=0.019 ms, max=240.859 ms, 99th percentile=0.108 ms
03:42:47.220:  ┣output_frame: min=0.039 ms, median=0.539 ms, max=6023.33 ms, 99th percentile=1.527 ms
03:42:47.220:  ┃ ┗gs_context(video->graphics): min=0.039 ms, median=0.538 ms, max=6023.33 ms, 99th percentile=1.526 ms
03:42:47.220:  ┃   ┣render_video: min=0.013 ms, median=0.492 ms, max=3945.97 ms, 99th percentile=1.469 ms
03:42:47.220:  ┃   ┃ ┗render_main_texture: min=0.011 ms, median=0.488 ms, max=3945.97 ms, 99th percentile=1.464 ms
03:42:47.220:  ┃   ┗gs_flush: min=0.017 ms, median=0.046 ms, max=6022.64 ms, 99th percentile=0.228 ms
03:42:47.220:  ┗render_displays: min=0.001 ms, median=0.598 ms, max=575.965 ms, 99th percentile=4.39 ms
03:42:47.220: =================================================
03:42:47.220: == Profiler Time Between Calls ==================
03:42:47.220: obs_hotkey_thread(25 ms): min=25.008 ms, median=27.458 ms, max=10001.5 ms, 18.9215% within ±2% of 25 ms (0% lower, 81.0785% higher)
03:42:47.220: obs_graphics_thread(33.3333 ms): min=0.645 ms, median=33.33 ms, max=10000.1 ms, 32.027% within ±2% of 33.333 ms (35.0598% lower, 32.9132% higher)
03:42:47.220: =================================================
03:42:47.277: Number of memory leaks: 0</pre></details>

**Comment by RytoEX** [comment]
> Can't produce log report for sessions where it becomes critical because I have to force quit.

OBS always write log files to `~/Library/Application Support/obs-studio/logs` on macOS.  The only difference introduced by force quitting OBS is that OBS will not write the log footer with detailed stats.  You could also use the steps, increase memory usage to a point before the UI becomes unresponsive, and then close at that point instead of continuing.  This would produce a full OBS log written to the directory previously mentioned.

**Comment by PatTheMav** [comment]
FWIW I profiled OBS over the course of 2 hours recently to check for another issue that was reported as a "memory leak" and couldn't find any.

If I find some time this week I can try to replicate the scene setup and run Instruments on OBS again.

Just to be sure: The issue also appears with just 3 sources (small file size video, big file size video, image slideshow)?

**Comment by kcannick** [comment]
> > Can't produce log report for sessions where it becomes critical because I have to force quit.
> 
> OBS always write log files to `~/Library/Application Support/obs-studio/logs` on macOS. The only difference introduced by force quitting OBS is that OBS will not write the log footer with detailed stats. You could also use the steps, increase memory usage to a point before the UI becomes unresponsive, and then close at that point instead of continuing. This would produce a full OBS log written to the directory previously mentioned.

Forgot to remove the comment... Log is included in original post.

**Comment by kcannick** [comment]
Created project with just two scenes ONE video in each and Memory usage exceeded 800MB in 10 minutes. No streaming or recording taking place. I have also uploaded a screen recording of Memory usage. You can see toward the end that even after video finishes playing the Memory usage increases by 100MB in a couple of minutes while absolutely no video is playing. It just keeps growing.

Screen Recording
https://www.mediafire.com/file/f88vyayncdus19e/Screen_Recording_2021-03-22_at_9.08.36_AM.mp4/file

Log File
https://obsproject.com/logs/gWRdLW0qh07vh8SO
