### ISSUE TITLE
[SCAM] Public scammers?

### ISSUE THREAD

**Issue by ZurMaD** [obsproject/obs-studio#4383]
Hello obs-studio team,

This issue is just to notify you that on social media there are several paid ads trying to supplant developers to install msi files infected

I saw it on Twitter but I didn't save the SS. However, today I get one on Facebook, I think it's a good idea to clarify to your users to keep them safe.

Screenshot:
![image](https://user-images.githubusercontent.com/28235457/112040391-2c5f1380-8b13-11eb-97c0-d31404bf301e.png)
fake fanpage https://www.facebook.com/SoftwareOBS

The ad has around 600 likes, so ...

When analysing the msi that they upload to the fake website we have:

![image](https://user-images.githubusercontent.com/28235457/112040649-78aa5380-8b13-11eb-8514-bf5a5cfc556f.png)

https://www.virustotal.com/gui/file/31761283418d46095935daa7be6afa54da1059bb276d91b4a50c38490c60f59e/detection

**Comment by Fenrirthviti** [comment]
We are already aware, and have engaged with Facebook on this. Feel free to report the facebook page directly, as more reports may help expedite getting the page taken down.

**Comment by ZurMaD** [comment]
Thanks !

**Comment by Heufneutje** [comment]
Probably a good idea for everyone encountering it to report the website as deceptive as well. I just submitted a report.
