### ISSUE TITLE
libfdk-aac2 not available on Ubuntu 20.10

### ISSUE THREAD

**Issue by juanuys** [obsproject/obs-studio#4384]
## Platform

Operating system and version: Ubuntu 20.10; Linux nil 5.8.0-45-generic #51-Ubuntu SMP Fri Feb 19 13:24:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
OBS Studio version: latest from apt
OBS Log file: not available

## Expected Behavior

I'm following the Linux installation instructions on the website:

```
sudo add-apt-repository ppa:obsproject/obs-studio
# I added this necessary + undocumented step:
# sudo apt-get update
sudo apt install obs-studio
```

I expect obs-studio to be installed.

## Current Behavior

The last step actually fails with:

```
sudo apt install obs-studio     
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 obs-studio : Depends: libfdk-aac2 (>= 2.0.1) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

## Steps to Reproduce

Just follow the Linux installation steps on https://obsproject.com/download on an Ubuntu 20.10 PC with ffmpeg already installed.

**Comment by juanuys** [comment]
Commenter here says you can make libfdk-aac optional: https://trisquel.info/en/forum/trying-install-open-broadcaster-software-studio-obs-studio-trisquel-8

**Comment by Gol-D-Ace** [comment]
You are missing repositories.

sudo add-apt-repository universe
sudo add-apt-repository multiverse
sudo apt update

and you should have the necessary packages available.

**Comment by juanuys** [comment]
Ah, nice one. Sorry, it's a fresh install, and I forgot about enabling universe/multiverse.
