### ISSUE TITLE
CoreAudio installed on D: drive not utilized

### ISSUE THREAD

**Issue by glenbecker** [obsproject/obs-studio#4387]
### Operating System Info

Windows 10

### OBS Studio Version

26.1.1

### OBS Studio Log URL

see attached files

### Expected Behavior

OBS should find and utilize CoreAudio in any install location

### Current Behavior

OBS missed D: drive install and fails to load CoreAudio. Installing CoreAudio on C: fixed it.

### Steps to Reproduce

1. Install OBS Studio on D: in default path (D:\Program Files\obs-studio)
2. Extract and run AppleApplicationSupport64.msi using guide here: https://obsproject.com/forum/resources/obs-studio-enable-coreaudio-aac-encoder-windows.220/
3. Select D: drive default path as install location (D:\Program Files\Common Files\Apple\Apple Application Support)
4. Run OBS studio and check log file for "[CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded"
...

### Anything else we should know?

OBS ui last/current log file upload didn't show error since it had been launched several times since fixing. Examples of good and bad logs attached.
Thanks for the great software!!

[bad_log.txt](https://github.com/obsproject/obs-studio/files/6200178/bad_log.txt)
[good_log.txt](https://github.com/obsproject/obs-studio/files/6200182/good_log.txt)

**Comment by mufunyo** [comment]
What path does %PROGRAMFILES% expand to on your system?

**Comment by glenbecker** [comment]
C:\Users\Glen>cd %PROGRAMFILES%

C:\Program Files>

**Comment by mufunyo** [comment]
There's your problem. It's not because you installed it on drive D:, but rather that you installed it in a custom location. If you relocated your program files by changing your ProgramFilesDir registry key, OBS would be able to find CoreAudio just fine.

**Comment by Fenrirthviti** [comment]
That's definitely a workaround though, we shouldn't require that applications be installed to only default locations if there's, say, a registry key we can just check, and then fall back on the default locations.

**Comment by Fenrirthviti** [comment]
Going to go ahead and close this as it's a stale issue and effectively a feature request, not a bug.
