### ISSUE TITLE
disconnecting a display and then changing what display obs is capturing causes obs to crash

### ISSUE THREAD

**Issue by asher-the-thrasher** [obsproject/obs-studio#4388]
### Operating System Info

macOS 11.2

### OBS Studio Version

Other

### OBS Studio Version (Other)

26.1.2-5522c1508 (26.1.2-5522c1508)

### OBS Studio Log URL

https://obsproject.com/logs/r6MMw33C9tqBKt8e

### OBS Studio Crash Log URL

https://pastebin.com/6CuZPbec

### Expected Behavior

obs to continue to run normally after unplugging a display and switching what display to capture

### Current Behavior

after unplugging the display that obs is capturing and then switching what display obs is capturing, obs crashes

### Steps to Reproduce

1. add a new display capture source
2. select an external display I chose display 2 but also works with display 1 (I would assume it would work the same no matter what display it is hooked to but cannot confirm it because on a laptop) 
3. select the display capture source so that it shows up in the source toolbar.
4. unplug the display obs is capturing, obs falls back to display 0 automatically but still shows as display 2 in the source toolbar. (i believe this is another issue altogether and am going to submit another bug report for it)
5. change obs to capture another display and then switch it to yet another (in my case I tested it a bunch and it seems it doesn't matter what it switched to, it will still crash)
6. OBS crashes

video of steps taken and crash https://vimeo.com/528660656 

### Anything else we should know?

in the log, there are 2 instances of obs open but that was only to record the issue. it still happens with only one instance of obs open.

**Comment by asher-the-thrasher** [comment]
also happens on OBS version 26.1.2

**Comment by RytoEX** [comment]
Possibly related to #3808 and/or #4355 ?

**Comment by RytoEX** [comment]
Please retest in OBS Studio 28.1.2 (or newer). I think we've committed several fixes around the code path in the crash log since this was reported.

**Comment by gxalpha** [comment]
Closing per above (as there hasn't been a response in 3 weeks)
