### ISSUE TITLE
Imported Scene Collection with win-dshow crashes on macOS

### ISSUE THREAD

**Issue by metalandcoffee** [obsproject/obs-studio#4391]
### Operating System Info

macOS 11.2

### OBS Studio Version

26.1.2

### OBS Studio Log URL

https://obsproject.com/logs/EqUbV-lcRtQNORq0

### OBS Studio Crash Log URL

https://obsproject.com/logs/EqUbV-lcRtQNORq0

### Expected Behavior

Not crash when I click on a Video Capture source after importing a Scene Collection.

### Current Behavior

Crashes when I click on a Video Capture source after importing a Scene Collection.

### Steps to Reproduce

1. Export a scene collection from a Windows machine.
2. Import it into OBS on a Mac machine.
3. Try to click through sources.

Here is a screenshot of my sources panel. Whenever I click on the Video Capture Device, it crashes (notice how the icon isn't the same one you usually see for a video capture device). This scene collection was imported from a Windows machine. I'm not sure how to get around this issue. I'd like to just delete the source and recreate it but I can't do that.

![image](https://user-images.githubusercontent.com/20868511/112482399-65cf9300-8d4e-11eb-9ced-459822b54bbe.png)

**Comment by asher-the-thrasher** [comment]
@metalandcoffee can you include the crash report from this, you can get it by opening finder, pressing cmd shift g and then pasting this file path `~/Library/Logs/DiagnosticReports/` then find the latest obs crash in that folder and paste it into https://pastebin.com/ and generate a link and link it here.

**Comment by metalandcoffee** [comment]
Sure! here's the link: [https://pastebin.com/M8bhBvby](https://pastebin.com/M8bhBvby)

Sorry about not including that!

**Comment by WizardCM** [comment]
Hmm, seems the importer isn't converting the Windows Video Capture Device source to a macOS Video Capture Device source, and because `win-dshow` isn't loaded, it crashes trying to load the text for Activate/Deactivate in the Source Toolbar.
