### ISSUE TITLE
.json file does not work and web source is not displayed

### ISSUE THREAD

**Issue by GU1D0** [obsproject/obs-studio#4392]
### Operating System Info

macOS 10.15

### OBS Studio Version

26.1.2

### OBS Studio Log URL

https://obsproject.com/logs/OdQApa_GuuN-HhrV

### Expected Behavior

With the imported .json file I expect a web source to appear from the following URL: 

http://www.deeptakt.net/share/tcp/tcp_overlay_720.html

### Current Behavior

The current behaviour is symply a black screen, nothing is shown. 

### Steps to Reproduce

1. Menu: Scene Collection - Import 
2. Collection Path = "The Path Of the .json file on my computer"
3. Press the Button "Import"
4. Select the imported Screen Collection
5. The screen remains black   

### Anything else we should know?

On my PC the .json file is working flawlessly in OBS. 

[OBS BUG json file does not work.zip](https://github.com/obsproject/obs-studio/files/6206538/OBS.BUG.json.file.does.not.work.zip)

**Comment by GU1D0** [comment]
I am not so sure about that because the same overlay works flawlessly in Twitch Studio on the same computer. What solution do you suggest? Why do you think I implement a Google ad?

**Comment by GU1D0** [comment]
> Part of the issue that I can see is that the google ad you're implementing is taking too much system resources and that Google is outright stopping the processes before the page content loads in their iframe.

I am not so sure about that because the same overlay works flawlessly in Twitch Studio on the same computer. What solution do you suggest? Why do you think I implement a Google ad?

**Comment by RytoEX** [comment]
> Why do you think I implement a Google ad?

I assume they thought that because they saw this in the source code:
```
<script data-source="https://s0.2mdn.net/ads/studio/Enabler.js" data-exports-type="gwd-google-ad" src="https://s0.2mdn.net/ads/studio/Enabler.js"></script>
<script data-source="gwdgooglead_min.js" data-version="8" data-exports-type="gwd-google-ad">
```
```
gwd-google-ad
```
```
Start the Ad lifecycle.
```

Also, uBlock Origin blocks it from loading.

Please provide a simple, reproducible test case that doesn't include ads.

Please also provide a scene collection file that fails to import.  If you're importing a scene collection file between computers with different operating systems, please include that information.

**Comment by GU1D0** [comment]
Hi,

 

You can close this thread. 

 

Cheers Guido
