### ISSUE TITLE
scene transition was not correct in preview

### ISSUE THREAD

**Issue by Usunshine** [obsproject/obs-studio#4396]
### Operating System Info

Windows 10

### OBS Studio Version

26.1.1

### OBS Studio Log URL

https://obsproject.com/logs/oqzzc_SJZ8XYLPcR

### Expected Behavior

Scene transition correctly converted, and preview show current scene source.

### Current Behavior

Scene transition was not correctly converted, and preview always show same scene source.

### Steps to Reproduce

1. add image source in scene1;
2. add media source in scene2;
3.add fade to color scene transition, and set duration 3300s;
4. quickly switch scenes, the scene transition was not correct.

[2021-03-26 15-53-15.txt](https://github.com/obsproject/obs-studio/files/6210199/2021-03-26.15-53-15.txt)

https://user-images.githubusercontent.com/29565972/112600637-6cdccb00-8e4c-11eb-88aa-15fd2a689144.mp4

**Comment by WizardCM** [comment]
Please test without any third party plugins.

**Comment by Usunshine** [comment]
yes, I have removed all third party plugins, and still have this problems.
Log link: https://obsproject.com/logs/ESm3RY708RladUcP

**Comment by Usunshine** [comment]
> Please test without any third party plugins.

yes, I have removed all third party plugins, and still have this problems.
Log link: https://obsproject.com/logs/ESm3RY708RladUcP

**Comment by Fenrirthviti** [comment]
Closing as stale. If this is still an issue please open a new issue with updated reproduction steps on the latest version of OBS.
