### ISSUE TITLE
Missing cursor when using MPX features in linux

### ISSUE THREAD

**Issue by 3331** [obsproject/obs-studio#4399]
### Operating System Info

Ubuntu 20.04

### OBS Studio Version

26.1.1

### OBS Studio Log URL

N/A

### OBS Studio Crash Log URL

N/A

### Expected Behavior

I expected that OBS would record both cursors in a MPX setup

### Current Behavior

Only one cursor is drawn at all times, even when creating multiple masters with xinput

### Steps to Reproduce

1. Open OBS
2. Add screen
3. do `xinput create-master asdf` in a terminal (spawns extra cursor in the middle of screen)
4. ?
5. Expected to see 2 cursors in obs preview at this point...
...

### Anything else we should know?

```
xinput create-master asdf
xinput list
xinput remove-master <id_of_master_you_just_created>
```

Also the usability of this MPX feature is highly dependent on the window manager, but I dont see why you would limit OBS to only record the first master device which is why I am making this bug report.

**Comment by kkartaltepe** [comment]
Please use https://ideas.obsproject.com/ for feature requests.
