### ISSUE TITLE
Twitch VOD Track Silent on Linux

### ISSUE THREAD

**Issue by Krutonium** [obsproject/obs-studio#4400]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

Git

### OBS Studio Log URL

https://obsproject.com/logs/7S-m5OWDv5VN__LY

### Expected Behavior

Audio should be heard for people in the Stream, but not in VOD's or Clips

### Current Behavior

Nothing is heard

### Steps to Reproduce

1. Either through Advanced or Simple Settings, enable Twitch VOD Track on the channel of your choice
2. Configure some audio to go through only that channel
3. Go Live
4. Unable to hear
5. Put that audio back on a normal channel
6. Can hear

### Anything else we should know?

This hasn't ever actually worked for me, so there's a chance I'm just being boneheaded and doing somthing wrong.

**Comment by kisik21** [comment]
It's called the VOD track, so is the sound from the channel present in the VOD?

I understand that your configuration looks somthing like this:

|                 | Track 1 | Track 2  (VOD) |
|--------------|-----------|------------|
| Source 1 | `[x]`      | `[ ]`        |
| Source 2 | `[ ]`       | `[x]`       |

In this case, the source 1 will only be heard on Live, while Source 2 will only be present in the VOD. The usual workflow for the VOD track is to play music on Live but not on VOD to avoid DMCA claims on VODs, so the source 1 (your usual audio) must be present on both tracks, while your music channel (mixed separately, perhaps via capturing a remap or a null-sink if you're using PulseAudio?) is only present on track 1 but not on track 2 (VOD).

**Comment by Krutonium** [comment]
...OH

Okay, for some reason I assumed that it was like, Track 1 and 2 would both be played on stream, but only the VOD track would be recorded, with Twitch mixing them for the live stream. Doi. Thanks, I'll give this a try.
