### ISSUE TITLE
ONE scene with ONE Media Source (65MB video on loop) is using 2.9 Gigs Memory!?

### ISSUE THREAD

**Issue by kcannick** [obsproject/obs-studio#4402]
### Operating System Info

macOS 11.2

### OBS Studio Version

26.1.2

### OBS Studio Log URL

https://obsproject.com/logs/3rgCPMFStTO2xIAW

### Expected Behavior

For UI to not freeze or become unresponsive under such a low load

### Current Behavior

UI becomes completely unresponsive when interacting with UI... get spinning beach ball for several minutes before UI begins to respond again.

### Steps to Reproduce

1. Create scene
2. Add Media Source [Video File, set to loop]
3. Let the video play and watch the memory slowly creep to infinity

**Comment by Fenrirthviti** [comment]
Please use the Discord or Forums for support requests.

**Comment by kcannick** [comment]
@Fenrirthviti Not a support request... I'm trying to report a bug.... I believe it's a memory leak, but I'm no expert. Appears to be an issue experienced by many other Mac OBS users.
