### ISSUE TITLE
Suddenly stopped opening. Crashes without even starting up.

### ISSUE THREAD

**Issue by xxRockOnxx** [obsproject/obs-studio#4407]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

Git

### OBS Studio Log URL

https://obsproject.com/logs/IhMakPQgIU2VaALb

### Expected Behavior

Can open without crashing

### Current Behavior

Crashing upon running. No UI shown.

### Steps to Reproduce

1. install OBS
2. run `obs`

### Anything else we should know?

Following https://obsproject.com/wiki/install-instructions#linux-portable-mode-all-distros and running the compiled binary, it works fine but needs the `-p` otherwise it crashes every now and then.

**Comment by notr1ch** [comment]
Please use forums or Discord for support, this is not an actionable bug report.
