### ISSUE TITLE
Crash on exit - Unhandled exception: c0000005 - obs.dll!audio_monitor_destroy+0x95

### ISSUE THREAD

**Issue by negue** [obsproject/obs-studio#4409]
### Operating System Info

Windows 10

### OBS Studio Version

26.1.0

### OBS Studio Log URL

https://obsproject.com/logs/LMz6e6f0-AIPOm5F

### OBS Studio Crash Log URL

https://obsproject.com/logs/GMOlj-V3NG3bmwqN

### Expected Behavior

To exit without issues :)

### Current Behavior

When you close OBS it crashes on exit

### Steps to Reproduce

1. Open OBS
2. Optional, Play desktop audio
3. Optional, Play Browser audio
4. Exit
5. Crash

### Anything else we should know?

Seems to be the same as #2879 but there it is linked to a fix PR so I don't really know if its related

Might be also related to https://obsproject.com/forum/threads/crashing-when-closing-unhandled-exception-c0000005.124444/

**Comment by energizerfellow** [comment]
Both OBS Studio itself and the StreamFX plug-in need to be updated. Update both, then try again.

Both your Nvidia GPU drivers and Intel GPU drivers could use updates as well.

**Comment by negue** [comment]
Forgot to post that yesterday... 

> Both your Nvidia GPU drivers and Intel GPU drivers could use updates as well.
- Nvidia one was updated a month -or- 2 ago (I think :D ) but I updated that yesterday after your suggestion ✔️ 
- I didn't get any Updates for the Intel one,  might need to check that again later today.

> You should also change your color back to 709/partial/NV12 to be HD video compliant

- I don't know which settings I had before, but with the previous one I had a pink tint / overlay on my stream in a chrome browser, and the solution was to use `601/Partial` - checked with 709 now and it worked fine on chrome again, so thank you :)


> Both OBS Studio itself and the StreamFX plug-in need to be updated.

- Haven't tried that yet, but add those to the todo list.


What I also tried was that in a "fresh" scenes ... is it called config / collection? => I didn't get any issues

So I'll also try to narrow it down what exactly of my scenes let it crash, might help to debug it in code as well


> and you're only outputting 720p30, which I'm not entirely sure is intentional

Yes, it is intentional. Being only an affliate on twitch you never know if you get transcoding, so in a worst-case you don't get transcoding and not everyone can watch in 1080p

**Comment by notr1ch** [comment]
Confirmed this by manually leaking a reference. This would usually be triggered by 3rd party plugins that hold references to sources after the UI has freed them, but it also affects libobs consumers who don't free sources before calling `obs_shutdown`.

Potential fix in https://github.com/notr1ch/obs-studio/commit/f22df70a82b82f46c5e0b793498e0b0dad699b68 but I'm not 100% happy with it. Changing the shutdown ordering so the audio subsystem remains alive during source destroying introduces further bugs and complexity.
