### ISSUE TITLE
[Bug] OBS Studio cuts off video at random points, freezes wildly on Twitter.

### ISSUE THREAD

**Issue by LWFlouisa** [obsproject/obs-studio#4410]
### Operating System Info

Other

### Other OS

Linux Mint

### OBS Studio Version

Other

### OBS Studio Version (Other)

25.0.3

### OBS Studio Log URL

There is no log for this issue.

### OBS Studio Crash Log URL

There is no crash log.

### Expected Behavior

The program should be able to stop precisely when I instruct it to, and run smoothly when scrolling over twitter.

### Current Behavior

It pretty much does the opposite of this.

### Steps to Reproduce

1. Open up OBS Studio
2. Try recording video
3. Video stops at random points, Twitter locks and freezes.
...

OBS studio should not have issues like these, it makes tutorial videos generally impractical.

**Comment by WizardCM** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
