### ISSUE TITLE
Undo/Redo Strings Initialize in Wrong Language

### ISSUE THREAD

**Issue by Vainock** [obsproject/obs-studio#4413]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

bde55cbf7b9cd6047416d2d93bb0199de21ec04c (https://github.com/obsproject/obs-studio/pull/4361)

### OBS Studio Log URL

https://obsproject.com/logs/EvqTNHogSpMyclpv

### Expected Behavior

The strings "Undo" ("Undo.Undo") and "Redo" ("Undo.Redo") initialize in the current language with the correct translations.

### Current Behavior

The strings "Undo" ("Undo.Undo") and "Redo" ("Undo.Redo") initialize in English, even if you add translations for the current language.
![UndoRedoWrongLanguage](https://user-images.githubusercontent.com/39059951/112994498-99edee00-916a-11eb-9001-4f84e2461046.png)

### Steps to Reproduce

0. Change the language of OBS to German and close the program.
1. Download the newest German translations for the UI locale file: [de-DE.zip](https://github.com/obsproject/obs-studio/files/6229261/de-DE.zip) which also includes all translations for the undo/redo feature.
2. Update the translations by replacing `obs-studio\data\obs-studio\locale\de-DE.ini` in your installation folder with the downloaded file.
3. Start OBS.
4. View the Edit tab ("Bearbeiten") and you will see the two strings are in English.
5. Just use the undo/redo system. (Do any action that triggers this feature)
6. The texts are now in German.

**Comment by tytan652** [comment]
"Undo"and "Redo" were put rather than "Undo.Undo" and "Undo.Redo" in OBSBasic.ui strings
