### ISSUE TITLE
Crash on startup after BSOD

### ISSUE THREAD

**Issue by mcDandy** [obsproject/obs-studio#4423]
### Operating System Info

Windows 10

### OBS Studio Version

26.1.1

### OBS Studio Log URL

not possible, gives error message, attaching as file

### OBS Studio Crash Log URL

https://obsproject.com/logs/2EpLx7c2ub73g5gP

### Expected Behavior

not crash

### Current Behavior

crashed on startup (only once)

### Steps to Reproduce

1. crash windows (dpc_watchdog_violation)
2. open OBS (crash)

### Anything else we should know?

attaching crash from before BSOD and log file for which obs gives error message when trying to upload it (both this and last).

crash before BSOD:
[Crash 2021-03-31 16-03-08.txt](https://github.com/obsproject/obs-studio/files/6237270/Crash.2021-03-31.16-03-08.txt)

Log file:
[2021-03-31 16-22-03.txt](https://github.com/obsproject/obs-studio/files/6237322/2021-03-31.16-22-03.txt)

![image](https://user-images.githubusercontent.com/18588943/113161488-b8bdb480-923e-11eb-8047-15685613f6bf.png)

**Comment by kkartaltepe** [comment]
Well since you were about to have a BSOD something terrible was happening on your machine. In this case OBS failed to allocate memory, probably because your entire machine was about to crash from being out of memory.
