### ISSUE TITLE
Unexpected Crash when trying to delete a copy/pasted scene filter that was copy/pasted from a duplicated scene

### ISSUE THREAD

**Issue by DrumDad** [obsproject/obs-studio#4424]
### Operating System Info

macOS 10.15

### OBS Studio Version

26.1.2

### OBS Studio Log URL

https://obsproject.com/logs/IntaVY5fyPTyMeMp

### OBS Studio Crash Log URL

https://drive.google.com/file/d/1RiqFlKFVW8RtdjdannFzmtmgykTUsYXr/view?usp=sharing

### Expected Behavior

Expected the duplicate filter to be removed from the scene.

### Current Behavior

OBS crashed upon delete confirmation "Are you sure you wish to remove 'Border'?

### Steps to Reproduce

1. Use "Duplicate" command on "Scene A" with two filters on it "SDF Effects" and "Move Transition" - "Scene B" is created as a result.  Filters are custom named "Borders" and "Move Caption"
2. Use "Copy Filters" command on "Scene A"
3. Use "Paste Filters" command on "Scene B"
4. Observe that "Scene B" now includes "SDF Effects", "SDF Effects 2", "Move Transition", and "Move Transition 2"
5. Select any effect and click on "-" (minus) button.
6. Select "Yes" at confirmation dialog.
7. Program crashes

--- 

Update:
Trying to delete any existing filter from within this Scene Collection results in an instant crash.

### Anything else we should know?

• Adding and removing a new filter to the culprit scenes is possible.  Removing existing filters causes crash.

• Collection contains nested scenes, scene filters are on the Source Scenes only (ex. "Scene A" is a source in "Scene C").  Scene A contains a scene filter.  Scene C does not.  Trying to remove the existing scene filters from the nested Scene A as a source in Scene C results in crash as well.

**Comment by WizardCM** [comment]
This looks related to #2909

**Comment by asher-the-thrasher** [comment]
this crash seems to be a result of the move transition, I just went through a bunch of different scenarios, and it only seems to happen when the move transition override filter is in the scene.
