### ISSUE TITLE
Recording (and maybe streaming) outputs are jittery with Nvidia's Fast Sync enabled

### ISSUE THREAD

**Issue by ghost** [obsproject/obs-studio#4427]
### Operating System Info

Windows 10

### OBS Studio Version

26.1.1

### OBS Studio Log URL

n/a

### Expected Behavior

Recording similar to non-fast-sync gameplay

### Current Behavior

Frames are recorded at irregular times (e.g. frames that should be displayed 1-2-3-4 are displayed 1-3-2-4, leading to "jittery" playback). 

### Steps to Reproduce

1. Have an Nvidia Graphics card.
2. Go to NVIDIA Control Panel settings -> Manage 3D Settings -> Vertical sync | Fast
3. Run a game (such as CS:GO) and start recording with Display Capture . 
4. View the resultant recording.

### Anything else we should know?

For context, I was using fast sync as I wanted my recordings to be tear-free AND be able to play CS:GO without ridiculous input lag. Also Display Capture because Game Capture no longer works with CS:GO (considered untrusted software for some reason).

Also, I think OBS accesses the wrong buffer (as https://beebom.com/what-is-nvidia-fast-sync-enable/ mentions Fast Sync using a different frame buffer), or it accesses the correct one in the wrong order (resulting in weird 1-3-2-4 playback). 

Edit: could be a problem with AMD's "Enhanced Sync" too.

**Comment by Kyorie** [comment]
Display Capture isn't designed for capturing games, i suppose. Use -allow_third_party_software in launch options for CS:GO.

**Comment by stykx** [comment]
I know it isn't. However, with CS:GO being the most played game on Steam, and with Shadowplay being so full of bugs, I can't be the only person who would like to see this fixed: -allow_third_party_software doesn't allow for recording in official-server matches. It doesn't matter as much, as my no-vsync config. works fine, but I believe this problem should be quite easy to fix and would help many people.

**Comment by Fenrirthviti** [comment]
If it's easy to fix, please feel free to submit a PR for review.

**Comment by gxalpha** [comment]
This report is a somewhat expected result of using fast sync. It's unlikely that we're able to do anything about it (and unfortunately, OP who claimed to have an easy fix has since deleted their GitHub Account).
