### ISSUE TITLE
Undocked docks cannot be docked again under Wayland

### ISSUE THREAD

**Issue by rmnvgr** [obsproject/obs-studio#4435]
### Operating System Info

Other

### Other OS

Fedora 34

### OBS Studio Version

Other

### OBS Studio Version (Other)

26.1.2-338-g62bc8f905

### OBS Studio Log URL

https://obsproject.com/logs/8rMowSgZN4XcJ51d

### Expected Behavior

Undocked docks can be docked again when dragging them on the main window.

### Current Behavior

- When undocking a dock by clicking on its undock button: a new window is created, it can be moved around but nothing happens when dragging it above the main window.
- When undocking a dock by dragging it outside the main window, a new window is created but without any decorations, it cannot be dragged.

The only way to have the docks docked again is by resetting the UI.

### Steps to Reproduce

1. Open OBS under a Wayland session
2. Undock a dock
3. Drag it above the main window

CC @GeorgesStavracas

**Comment by kkartaltepe** [comment]
I think unfortunately part of this is not our bug. We rely on the Qt code to handle the docking iirc, which likely is just not entirely implemented for wayland. There may be some bugs in the OBS part for handling this though.

**Comment by RytoEX** [comment]
We don't do anything particularly special for normal docks, so I'd bet on an issue with the Qt version used and Wayland.

**Comment by RytoEX** [comment]
Looks like this to me:
https://bugreports.qt.io/browse/QTBUG-87332

**Comment by kkartaltepe** [comment]
Yea we rely entirely on the Qt implementation it seems. Not even fiddling with the native window settings for the docks works around the poor handling by the Qt implementation.

**Comment by hadron43** [comment]
If users are looking for a temporary fix, go to View > Docks > Reset UI.

**Comment by MightyCreak** [comment]
I still have the issue and the workaround doesn't work because when resetting the docks, the stats window isn't part of the default docked windows. So if I enable the stats window, it's still a floating window I can't dock in the UI.

**Comment by GeorgesStavracas** [comment]
This is not only not implemented in Qt, it is unlikely to be *implementable* whatsoever under Wayland. Anything that tries to position windows on Wayland is not going to work, since standard protocols and extensions explicitly do not support this. Please understand that there is nothing either OBS or Qt can do about it right now.

**Comment by MightyCreak** [comment]
Would it be possible to provide a workaround? Something like a config file that we could edit, where we would put which window we want to be docked. Because once the window is docked, we can move it around within the OBS UI, it's just a matter of having the window docked in the first place.

**Comment by RytoEX** [comment]
> Would it be possible to provide a workaround? Something like a config file that we could edit, where we would put which window we want to be docked. Because once the window is docked, we can move it around within the OBS UI, it's just a matter of having the window docked in the first place.

No. The docks are managed by Qt, which reads and writes the dock state as a base64 data string. We do not, as far as I recall, do any special or custom handling of dock positioning ourselves.

**Comment by GeorgesStavracas** [comment]
I don't think there's any workaround to this issue. What I've done in the past is to initialize OBS Studio using X11 by running in the terminal, `$ env QT_QPA_PLATFORM=xcb flatpak run com.obsproject.Studio` (if you're not using Flatpak, replace the last part with `obs`), then reattach the dock to the window, then finally close OBS and reopen it regularly and proceed from there. I don't know if this still works, or if this will ever work in the future. Sorry.

**Comment by MightyCreak** [comment]
@GeorgesStavracas It worked!! thank you :wink:

**Comment by navaati** [comment]
Just an extra "redock" button at the bottom of the un-docked window would solve the problem nicely.

**Comment by phedders** [comment]
Or a wee "dock" icon in the window title bar. I think this should be re-openned it such a workaround can be found.
