### ISSUE TITLE
incorrect animation when docking a dock on the sides of the preview

### ISSUE THREAD

**Issue by asher-the-thrasher** [obsproject/obs-studio#4440]
### Operating System Info

macOS 11.2

### OBS Studio Version

26.1.2

### OBS Studio Log URL

https://obsproject.com/logs/Ix4yWp7VSKWqnTY9

### Expected Behavior

the dock animation when docking on the left side of the preview should appear on the left side where the space appears

### Current Behavior

the dock animation when docking on the left side of the preview appears on the right side where the right dock space would be going if docking on that side

### Steps to Reproduce

1. move a dock to the left side of the preview 
2. notice how the red animations appear on the right side of the preview instead of where it should go 

https://user-images.githubusercontent.com/76796294/113469086-a8613180-9418-11eb-9c1d-ef6dd233c2c4.mp4

**Comment by RytoEX** [comment]
I'd guess the red is Qt repainting surfaces as they move around.  Does it occur, or not occur, on other themes?  If it doesn't occur on at least one theme, then perhaps we can add some styles to hide the repaint, if I'm right about that.  @PatTheMav might be able to provide more insight.

**Comment by asher-the-thrasher** [comment]
it occurs on all of the themes that come with obs (acri, dark, and rachni)

**Comment by WizardCM** [comment]
I cannot reproduce this on Big Sur with the RC - I only see a dark grey patch, no red.

**Comment by asher-the-thrasher** [comment]
> I cannot reproduce this on Big Sur with the RC - I only see a dark grey patch, no red.

I still have it with the RC on big sur. The same exact example that's above. though I also check on another machine and it doesn't have the red lines at all, the same thing you descibed.

**Comment by RytoEX** [comment]
Please retest in OBS Studio 28.1.2 (or newer) to confirm if this is still an issue.

That said, I think this is just how Qt handles dock animations, and this is not a bug in OBS itself.

**Comment by gxalpha** [comment]
I'm fairly certain that we fixed this by now, most likely with the update to Qt 6.3.
In case it's not fixed, please leave a comment here and we can try to investigate it again (although we still probably wouldn't be able to do anything about it).
