### ISSUE TITLE
Scene collections with identical names are selected at the same time in OBS 27 RC1 (Import does not increment name)

### ISSUE THREAD

**Issue by iesvme** [obsproject/obs-studio#4442]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0-rc1

### OBS Studio Log URL

NONE

### Expected Behavior

Replace the old scene when importing the same scene.

### Current Behavior

Both scenes are selected at the same time in OBS 27 RC1

### Steps to Reproduce

1. export the one of scene
2. import the same scene
3. both scenes will be selected at the same time
4. import the same scene again
5. Three  / four / five / six etc.
...

![image](https://user-images.githubusercontent.com/16969250/113471481-2c560080-948f-11eb-9bd9-1ec714cd7495.png)
![image](https://user-images.githubusercontent.com/16969250/113471738-fca7f800-9490-11eb-9cfd-a6b8aacc8271.png)

**Comment by WizardCM** [comment]
I'm assuming this was introduced by #3916.

Please include a log file after importing.

**Comment by iesvme** [comment]
https://obsproject.com/logs/4ZmMsF81T2HjOJh9

**Comment by iesvme** [comment]
https://obsproject.com/logs/1Zw4ez_fQHu5dX-f

**Comment by iesvme** [comment]
https://obsproject.com/logs/dK5ZeyrVOFvYGst8

**Comment by WizardCM** [comment]
I have confirmed that exporting & reimporting the same scene collection adds a new entry to the Scene Collection menu, missing the increment. Filename is incremented instead.

```
21:56:12.871: Import Scene Collection: Custom SC Name (Custom_SC_Name2) - SUCCESS
```
```
03/04/2021  09:55 PM            27,517 Custom_SC_Name.json
03/04/2021  09:55 PM            27,517 Custom_SC_Name.json.bak
03/04/2021  09:56 PM            12,983 Custom_SC_Name2.json
```

![image](https://user-images.githubusercontent.com/941350/113476528-c20d8200-94c7-11eb-8314-c38d4d2cbcf9.png)
