### ISSUE TITLE
libpipewire-0.3-dev is not available on Ubuntu 20.04LTS

### ISSUE THREAD

**Issue by Mitsunee** [obsproject/obs-studio#4443]
### Operating System Info

Ubuntu 20.04

### OBS Studio Version

Git

### OBS Studio Log URL

the what?

### Expected Behavior

Expected the command in the build instructions to install all build deps to just work

### Current Behavior

libpipewire-0.3-dev is not available on Ubuntu 20.04LTS, only libpipewire-0.2-dev is found

```bash
aptitude search libpipewire
i A libpipewire-0.2-1                            - libraries for the PipeWire multimedia server          
p   libpipewire-0.2-dev                          - libraries for the PipeWire multimedia server - develop
p   libpipewire-0.2-doc                          - libraries for the PipeWire multimedia server - documen
```

### Steps to Reproduce

1. Go to the wiki link in README.md
2. Copy the command under #debian-based-build-directions
3. apt will now fail to find the package

### Anything else we should know?

I am trying to build obs-studio with the cef browser source and also the obs-text-pango plugin from https://github.com/kkartaltepe/obs-text-pango

Other than adding `add_subdirectory(obs-text-pango)` to `./plugins/CMakeLists.txt` and cloning the repo of obs-text-pango into `./plugins/obs-text-pango` I have done no modifications to the local repo.

I've done it on an older version of Ubuntu (19.04? maybe 19.10?) a while ago and got version 25.0.7-174-g7998189-modified(linux) from that, but would like to upgrade to a newer version as I've sometimes been getting crashing issues when stopping streams or longer recordings.

**Comment by WizardCM** [comment]
Set `ENABLE_PIPEWIRE` to OFF in CMake and reconfigure.

For more info see #4439

**Comment by Mitsunee** [comment]
Disabled pipewire (I think?) and got an error while building now
(I'm writing a small guide for myself in the gedit window on the left, including them here for reference)

![Screenshot_20210403_110508](https://user-images.githubusercontent.com/19474909/113473855-7679ba80-946c-11eb-85f2-3fc4f0d2eff1.png)

I got errors while building with `make -j4`, so a friend suggested doing `make clean && make` to see if that actually shows the error. Otherwise I followed the steps in my guide.

**Comment by Mitsunee** [comment]
still getting the same error with the updated cmake command from the wiki
`cmake -DUNIX_STRUCTURE=1 -DENABLE_PIPEWIRE=OFF -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_BROWSER=ON -DCEF_ROOT_DIR="../../cef_binary_4280_linux64" ..`

**Comment by Gol-D-Ace** [comment]
Try deleting the build folder and let cmake regenerate it. Perhaps that will help. Did build the PPA for all Ubuntu versions without errors.

**Comment by Mitsunee** [comment]
I've done so a few times already (as per the text file in the screenshot above) to rule out random mistakes, but that didn't fix it.

**Comment by GeorgesStavracas** [comment]
The error in the screenshot is related to BrowserClient, not PipeWire.

**Comment by Mitsunee** [comment]
Either way, it doesn't build and I'd really like a newer version because in the one I currently have the list of windows in the Windows Capture Source properties is broken now, which a newer version would hopefully fix.

**Comment by GeorgesStavracas** [comment]
May I suggest then, using the 27 RC of OBS Studio from Flathub Beta? It should be super simple to install:

```
$ flatpak install --user https://dl.flathub.org/beta-repo/appstream/com.obsproject.Studio.flatpakref
```

**Comment by Mitsunee** [comment]
does that include obs-text-pango and the cef browser plugin?

**Comment by GeorgesStavracas** [comment]
I think so

**Comment by Mitsunee** [comment]
I tried installing it and it does not include obs-text-pango, so I still need to compile my own custom version

**Comment by GeorgesStavracas** [comment]
Okay
