### ISSUE TITLE
Don't see virtual camera option under tools

### ISSUE THREAD

**Issue by awebdeveloper** [obsproject/obs-studio#4445]
### Operating System Info

macOS 10.15

### OBS Studio Version

26.1.2

### OBS Studio Log URL

 https://obsproject.com/logs/XBXSorvbzWEdn7N8

### Expected Behavior

I should see virtual camera option under tools

### Current Behavior

I don't see virtual camera option though I am on version 26.1+

### Steps to Reproduce

1. Open OBS Studio
2. Go to Tools

**Comment by WizardCM** [comment]
The official Virtual Camera is not under Tools, it is in the Controls dock.
