### ISSUE TITLE
Any OBS version from 26.1.0 and up doesn't launch at all

### ISSUE THREAD

**Issue by aisopos72** [obsproject/obs-studio#4451]
### Operating System Info

Windows 10

### OBS Studio Version

26.1.1

### OBS Studio Log URL

Can't post log url since obs doesn't launch in the first place

### OBS Studio Crash Log URL

No crash, just doesn't launch in the first place

### Expected Behavior

OBS should start.

### Current Behavior

Every OBS version from 26.1.0 and up doesn't launch (Downgrading to 26.0.2 works).

The program doesn't run regardless of whether in administrator mode or not, and the task manager doesn't show that obs is running either.

### Steps to Reproduce

1. Either upgrade from older version or do a clean reinstall of OBS for any version from 26.1.0 and up.
2. Launch OBS
3. Doesn't launch

### Anything else we should know?

I've tried just about everything I can :

1) Complete uninstall (including settings) and reinstall of OBS
2) Reboot the computer after each install many times
3) Manually update web-socket and streamfx plugins (I read a community advice telling me to do so)

While I would have normally been perfectly okay to use the old 26.0.2 version until everything got fixed, the old version does NOT include the Twitch VOD track feature, which is really essential for me.

**Comment by Fenrirthviti** [comment]
Please use the forums or Discord for support, as this is not an actionable report.
