### ISSUE TITLE
Python 3.9 Not Working with OBS 27.0 RC1 (or OBS 26)

### ISSUE THREAD

**Issue by guitaristtom** [obsproject/obs-studio#4460]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.0 RC1

### OBS Studio Log URL

https://obsproject.com/logs/D3shp1Nx-gXxJQ5Q

### Expected Behavior

To not error out when loading up a Python script

### Current Behavior

It errors out when loading up a Python script

### Steps to Reproduce

1. Be running Linux and Python 3.9x (3.9.2 in my case).
2. Load up OBS
3. Load Python Script up
4. It errors

### Anything else we should know?

The script I'm using is https://github.com/guitaristtom/obspokemonhud

The script works fine with OBS 26 on Windows 8.1 and Windows 10 (with the specific required version of Python 3.6 installed. But OBS 26 and 27.0 RC1 don't seem to like Python 3.9.x on Linux. The build of OBS I'm running is the newest push to the main repo on Github here, compiled through Arch Linux's AUR with the `yay` AUR helper.

Any help or feedback on this issue would be appreciated, or if there's something wrong with this script, that would also be helpful.

![Screenshot from 2021-04-04 14-10-12](https://user-images.githubusercontent.com/6890628/113521745-5ae7e000-9550-11eb-8463-88fc802f40ca.png)

**Comment by notr1ch** [comment]
Are you sure you built OBS against Python 3?

**Comment by kkartaltepe** [comment]
Duplicate #2222

**Comment by guitaristtom** [comment]
> Are you sure you built OBS against Python 3?

From what I can see, yes.

https://aur.archlinux.org/packages/obs-studio-git/
