### ISSUE TITLE
OBS takes very long time to load under Catalina

### ISSUE THREAD

**Issue by GeoSn0w** [obsproject/obs-studio#4461]
### Operating System Info

macOS 10.15

### Other OS

macOS 10.15.7

### OBS Studio Version

26.1.2

### OBS Studio Log URL

-

### Expected Behavior

It should load basically in a few seconds or so, like it did back on macOS High Sierra.

### Current Behavior

It takes a very long time to load. Up to minutes long. It just bounces in the dock for a while, and then it stops bouncing and the app is no longer responding for a few minutes until it just suddenly comes back to life. I have reinstalled, clean restored the Mac, etc. Issue persits.

### Steps to Reproduce

1. Install OBS on Catalina, iMac 2015.
2. Open it

### Anything else we should know?

It used to work perfectly fine on macOS High Sierra.

The problem seems to have started with Catalina. macOS High Sierra worked fine.

**Comment by WizardCM** [comment]
Please include a session log

**Comment by GeoSn0w** [comment]
> Please include a session log

I did some investigation... it's the damn trustd basically taking ages to send something to ocsp.apple.com and thus keeping OBS in limbo until the response arrives. The second I blocked ocsp.apple.com in hosts OBS loads instantly.
