### ISSUE TITLE
Matte transition issue

### ISSUE THREAD

**Issue by Samlmdg** [obsproject/obs-studio#4466]
### Operating System Info

macOS 10.14

### OBS Studio Version

27.0.0-rc1

### Expected Behavior

I'm try ti use stinger with alpha track matte (matte is at the bottom of my stinger file) Size of my video : 1920x 2160

### Current Behavior

When I try to use transition with  track matte alpha channel is not used ans transition comes after the stinger

### Steps to Reproduce

1. edit stinger
2. select file with transition & track matte
3. check "use track matte", then "Same file stacked (stinger on top, track matte at the bottom)
...

**Comment by WizardCM** [comment]
Try it without obs-websocket installed.

**Comment by Samlmdg** [comment]
[2021-04-05 15-18-35.txt](https://github.com/obsproject/obs-studio/files/6258316/2021-04-05.15-18-35.txt)

Same issue :(

**Comment by WizardCM** [comment]
Please include the stinger video file.

**Comment by Samlmdg** [comment]
https://user-images.githubusercontent.com/21952967/113578220-c26e6000-9622-11eb-9592-142aff4be7e3.mov

**Comment by VodBox** [comment]
There has been a common misconception being reported about how the feature works that you seem to have run into. The track matte portion is not describing the alpha of the stinger (like you would have with a key + fill in SDI workflows), but instead the track matte describes the transitioning between the scenes. The stinger portion itself must still be a transparent video to have proper alpha at this stage.

Per our recently added [wiki guide](https://github.com/obsproject/obs-studio/wiki/Getting-Started-With-Track-Matte-Stinger-Transitions):

> In the mask video, black pixels tell OBS where to show pixels from the current scene, where white pixels tell OBS where to show pixels from the next scene. Pixels inbetween plain black and plain white are allowed too, and allow for crossfades from the current scene to the next scene.

You can see in the following images how it's intended to be used:

![](https://user-images.githubusercontent.com/1812130/113523399-d1fc9300-95a7-11eb-9702-2773b7c9031a.gif)
![](https://user-images.githubusercontent.com/1812130/113523577-8ac2d200-95a8-11eb-8b72-9807cb0f861b.png)
