### ISSUE TITLE
Only 5 attempts to reconnect to RTSP

### ISSUE THREAD

**Issue by GiovanniG11** [obsproject/obs-studio#4467]
### Operating System Info

Windows 10

### OBS Studio Version

26.1.1

### OBS Studio Log URL

https://pastebin.com/NEdyfVQy

### Expected Behavior

Supposing it attempts to reconnect forever, in any condition

### Current Behavior

After 5 times it stops attempting, which is too few short time to wait a camera or a router to reboot. It needs to restart manually stopping and starting view

### Steps to Reproduce

1. Connect an RTSP camera
2. Reboot camera and count with tcpviewer.exe the number of attempts
3. stop and start manually to see the camera back (after reboot is completed)
...

**Comment by WizardCM** [comment]
Please test again with the OBS 27 RC.

**Comment by GiovanniG11** [comment]
Thanks for quick answer, I've installed it and recreated the same circustances, nothing is changed. I've realized a video for you https://youtu.be/pilk1R8xrSA

**Comment by GiovanniG11** [comment]
27RC has several bugs, it shows in the beginning "missing files" even if I use only RTSP, if I clear that message I''ve lost all my mosaic, patently I've recreated it with crops and enlargments, closed OBS and again it shows the same. Also websocket was not more listening on 4444. So I've immediately reversed back to 26

**Comment by flaeri** [comment]
What type of camera is it?

Does it happen only with the VLC source, or also the media source?

**Comment by RytoEX** [comment]
The provided log indicates that you were using VLC source rather than Media Source. However, given that @flaeri tested both, I'm closing this based on that comment. If you experience this in OBS Studio 28.1.2 (or newer), please comment with a new log file and new Steps To Reproduce, and we can consider whether to reopen this or open a new issue.
