### ISSUE TITLE
Gnome Font scalling to 0.7 create glitches into interface

### ISSUE THREAD

**Issue by RKiemGames** [obsproject/obs-studio#4472]
### Operating System Info

Other

### Other OS

Ubuntu / Pop OS!

### OBS Studio Version

26.1.1

### OBS Studio Log URL

undefined

### Expected Behavior

Font scales into interface according to gnome scale configuration.

### Current Behavior

The menu interface and sections have hide and generate glitches.

### Steps to Reproduce

1. scale font from gnome configuration to 0.7
2. open OBS.
3. fail interface.

### Anything else we should know?

if scale is set to 1.0, it's work.

**Comment by kkartaltepe** [comment]
Fixed in master. Fractional font scaling has  been disabled, since Qt is broken for these scales.
