### ISSUE TITLE
OpenGL Game Capture doesn't display the last game's state after minimizing the game

### ISSUE THREAD

**Issue by Kyorie** [obsproject/obs-studio#4474]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0-rc1

### OBS Session Log

https://github.com/obsproject/obs-studio/files/6265932/2021-04-06.18-44-58.txt

### Expected Behavior

Previously it was still displaying the last game's screen after Alt+Tab, kinda freezing it until you return to your game's window.

### Current Behavior

It loses the capture after Alt+Tab and doesn't display the game's screen before you've minimized the game.

### Steps to Reproduce

1. Use Game Capture
2. Run a game with OpenGL renderer
3. Wait until OBS hooks up the game
4. Alt+Tab and you'll see that now there's no game on your scene as it was before in 26.1.2.

### Anything else we should know?

the game was osu!, in case if it matters

**Comment by Fenrirthviti** [comment]
Please provide a session log.

**Comment by Kyorie** [comment]
[2021-04-06 18-44-58.txt](https://github.com/obsproject/obs-studio/files/6265932/2021-04-06.18-44-58.txt)
Here's the log

**Comment by Fenrirthviti** [comment]
Looks like the game stops rendering, and therefor can't be captured. Please use the support channels for further assistance, as I cannot replicate this on my end with another OpenGL game (Minecraft).

```
18:46:03.434: device_texture_create (D3D11): Failed to create 2D texture (80070057)
18:46:03.434: [game-capture: 'osu'] init_shmem_capture: failed to create texture
18:46:03.434: [game-capture: 'osu'] capture stopped
```

**Comment by Kyorie** [comment]
I've done the same with the latest OBS release (26.1.1.) and i had no such issue. Here's the log from the previous version: https://obsproject.com/logs/0wJMLxq_JxiLheZ6

**Comment by matoi974** [comment]
Same behaviour on v26.1.1 and v27.0.0-rc1 for me with osu, it renders a black screen almost immediately after I alt-tab out of it.

**Comment by Kyorie** [comment]
https://www.youtube.com/watch?v=5gi-j08dGEU
