### ISSUE TITLE
Can't compile source (git), reason - libpipewire-0.2-dev (Debian Buster) and require libpipewire-0.3-dev

### ISSUE THREAD

**Issue by sws33** [obsproject/obs-studio#4480]
### Operating System Info

Other

### Other OS

Debian Buster

### OBS Studio Version

Git

### OBS Studio Log URL

https://github.com/sws33/obs/blob/main/CMakeError.log

### OBS Studio Crash Log URL

https://github.com/sws33/obs/blob/main/CMakeOutput.log

### Expected Behavior

Compile completely

### Current Behavior

Error of libpipewire

### Steps to Reproduce

1. clone git 
2. cd obs-studio
3. mkdir build && cd build
4. cmake -DUNIX_STRUCTURE=1 -DCMAKE_INSTALL_PREFIX=/usr .. 
...

### Anything else we should know?

Can't compile source (git), reason - libpipewire-0.2-dev (Debian Buster) and require libpipewire-0.3-dev

**Comment by tytan652** [comment]
Look #4443

**Comment by sws33** [comment]
> Look #4443
Thanks!
