### ISSUE TITLE
Black screen when Capture Window (Debian Linux, Wine, MT4) 

### ISSUE THREAD

**Issue by sws33** [obsproject/obs-studio#4481]
### Operating System Info

Other

### Other OS

Debian Buster

### OBS Studio Version

Git

### OBS Studio Version (Other)

27.0.0 rc1

### OBS Studio Log URL

https://github.com/sws33/obs/blob/main/2021-04-07%2015-16-35.txt

### OBS Studio Crash Log URL

no crash

### Expected Behavior

normal screen record

### Current Behavior

blank black screen

### Steps to Reproduce

1. Run obs
2. Create new scene
3. Add video source Capture Window (XComposite)
4. Run MetaTrader 4 - https://www.metatrader4.com  via latest stable wine 6.0
5. Start screen capture
6. Check result. It may be black screen or sometimes black screen and some times - normal picture (alternation)
...

### Anything else we should know?

Screen Resolution for the wine must be 98 dpi
(winecfg - Graphic - Screen Resolution)

**Comment by GeorgesStavracas** [comment]
Which desktop environment?

**Comment by sws33** [comment]
> Which desktop environment?
Fluxbox

**Comment by edmundlaugasson** [comment]
Perhaps is possible to use SimpleScreenRecorder libraries, which is also free and open-source app - https://github.com/MaartenBaert/ssr - usually that app has no issues and is capable capture even 3D apps.

**Comment by kkartaltepe** [comment]
This looks like user error. If you started a window capture before your window was available, then it wont know what window to capture. The log shows that no windows were ever matched for capture.

> Perhaps is possible to use SimpleScreenRecorder libraries, which is also free and open-source app - https://github.com/MaartenBaert/ssr - usually that app has no issues and is capable capture even 3D apps.

In the future please dont use our issues to advertise other tools.

**Comment by edmundlaugasson** [comment]
Looks like or is really? Very poor interpretation and it doesn't solve issue at all. Based on what argumentation you say, that user error? Have you ever analyzed really the issue in appropriate circumstances? It looks for me, that you just don't want to deal with the issue and therefore it's easy to just close it... The question is - why even bother to report if there will be no solution at all? I am still experiencing black windows: some apps are just black after I choose them, e.g. Brave web browser windows, WebCatalog started via AppImage. Sometimes it helps, when run from command-line in app mode the exact URL. So, I choose existing window - it cannot be "user error".

**Comment by Fenrirthviti** [comment]
The closing of this issue does not mean we are not willing to support, we do not with to use GitHub issues reports for support, and while it can be frustrating sometimes, we are going to be aggressive on issue reports that are "maybe this is broken" and don't have clear, concise, repeatable replication steps. Feel free to stop by the Discord or make a forum post for support-related requests, where time can be spent investigating. If this is an actual bug, and not user error, we will be happy to reopen it at that time.

**Comment by edmundlaugasson** [comment]
But closing argument is also seemingly. When it is closed, nobody will not pay attention to it anymore. I clearly explained that black windows are REAL. Take Linux Mint or Ubuntu, install it onto PC with nVidia GPU and install also latest OBS Studio. Then install also Brave web browser and try to use window
I don't know the reason, but some windows are black. It might be, that issue is not in OBS. It also might be, that issue is not in GPU software. Quite often GPU software people will redirect to OBS people and vice versa. Users, like me, are between somewhere out there... We obviously don't know, where to say that issue. I've been said it here and at nVidia's forum. Both are quite silent and this discussion is first indication of some life. nVidia has released some new versions, but these did not solve black window issue. Hopefully there are anybody, who succeed to solve the black windows issue. We, users, truly hope.

**Comment by nicokimmel** [comment]
Internet is full of people reporting this problem and it exists for years now. This is by far not an user error. You select a window and the only thing it captures is the cursor.

Im on Ubuntu 20.04 Gnome 3.36 and it happens for me as well.

**Comment by edmundlaugasson** [comment]
That's true - many people suffer under that bug. I switched to [EndeavourOS](https://distrowatch.com/endeavouros) with KDE and there is no such issue. Although haven't tested all mentioned apps, but at least those apps I could not record under Linux Mint, I can now under EndeavourOS, which is close to Arch Linux. You can try also [Manjaro Linux](https://distrowatch.com/manjaro), if EndeavourOS is not suitable. Certainly there are other [rolling release Arch distros available](https://distrowatch.com/search.php?ostype=All&category=All&origin=All&basedon=Arch&notbasedon=None&desktop=All&architecture=All&package=All&rolling=Rolling&isosize=All&netinstall=All&language=All&defaultinit=All&status=Active#simple).

**Comment by nicokimmel** [comment]
I hope the swap to Wayland with 22.04 in April will fix it. Although I have to use the OBS Wayland Plugin then.

**Comment by Fenrirthviti** [comment]
> Internet is full of people reporting this problem and it exists for years now. This is by far not an user error. You select a window and the only thing it captures is the cursor.
> 
> Im on Ubuntu 20.04 Gnome 3.36 and it happens for me as well.

In all cases we have investigated and dug in to, it has been user error, an OBS package issue that we don't maintain, or a configuration issue in their environment. If you'd like someone to take a closer look, I'd recommend our support forums or Discord as a good starting place.

https://obsproject.com/help

**Comment by nicokimmel** [comment]
I did not see a single person that got this problem fixed. But Ill look into the Discord/Forums.

(Tried the official repo, flatpak, Ubuntu Store, different versions, beta versions. I dont know what else packages there are.
Configs were all the default ones. Plain OBS, plain Ubuntu 20.04.)

**Comment by Chiitoo** [comment]
For anyone experiencing this, it would be nice for them to list the steps to reproduce the issue (including the environment details).

I just tried all that I could see here (including the oddly specific 98 DPI setting) with some applications (metatrader can't be downloaded at this time it seems), and I could not make this happen, nor have I seen this since several years ago when I first started using OBS Studio on Gentoo Linux across different Window Managers and Desktop Environments.

One way to reproduce a black window I do know of, is to minimise an application, and capture that.  Perhaps there is a specific combination where OBS still sees the application minimised?  Probably not, but it's a thought I had.

But yeah, steps to reproduce this is what is needed here.  Just "me too" will not help fer sure.  :]

**Comment by nicokimmel** [comment]
I recorded a video. [https://www.youtube.com/watch?v=GUXJuLssKw0](https://www.youtube.com/watch?v=GUXJuLssKw0)
It does not happen for OBS itself, Spotify and some other apps, but Steam (native, not via wine) and Wine/Proton applications dont work at all (I tested multiple of them).
Running Ubuntu 20.04.3 LTS with Gnome 40.4.0, x11. I upgraded from Gnome 38 to 40 but the problem did not change.

**Comment by dodgepong** [comment]
Please include your OBS log as well for debugging.

**Comment by nicokimmel** [comment]
```04:09:56.515: CPU Name: AMD Ryzen 5 2600 Six-Core Processor
04:09:56.515: CPU Speed: 1746.288MHz
04:09:56.535: Physical Cores: 6, Logical Cores: 12
04:09:56.535: Physical Memory: 15953MB Total, 2314MB Free
04:09:56.535: Kernel Version: Linux 5.13.0-28-generic
04:09:56.535: Distribution: "KDE Flatpak runtime" "5.15-21.08"
04:09:56.536: Session Type: x11
04:09:56.536: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.13
04:09:56.538: Qt Version: 5.15.3 (runtime), 5.15.3 (compiled)
04:09:56.538: Portable mode: false
04:09:56.583: OBS 27.2.0-beta4 (linux)
04:09:56.583: ---------------------------------
04:09:56.583: ---------------------------------
04:09:56.583: audio settings reset:
04:09:56.583: 	samples per sec: 48000
04:09:56.583: 	speakers:        2
04:09:56.589: ---------------------------------
04:09:56.589: Initializing OpenGL...
04:09:56.709: Loading up OpenGL on adapter NVIDIA Corporation NVIDIA GeForce GTX 1070/PCIe/SSE2
04:09:56.709: OpenGL loaded successfully, version 3.3.0 NVIDIA 470.86, shading language 3.30 NVIDIA via Cg compiler
04:09:56.720: ---------------------------------
04:09:56.721: video settings reset:
04:09:56.721: 	base resolution:   1920x1080
04:09:56.721: 	output resolution: 1920x1080
04:09:56.721: 	downscale filter:  Bicubic
04:09:56.721: 	fps:               60/1
04:09:56.721: 	format:            NV12
04:09:56.721: 	YUV mode:          709/Partial
04:09:56.721: NV12 texture support not available
04:09:56.721: Audio monitoring device:
04:09:56.721: 	name: Default
04:09:56.721: 	id: default
04:09:56.721: ---------------------------------
04:09:56.728: No AJA devices found, skipping loading AJA UI plugin
04:09:56.728: Failed to initialize module 'aja-output-ui.so'
04:09:56.734: No AJA devices found, skipping loading AJA plugin
04:09:56.734: Failed to initialize module 'aja.so'
04:09:56.735: Failed to load 'en-US' text for module: 'decklink-captions.so'
04:09:56.738: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
04:09:56.882: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
04:09:56.882: No blackmagic support
04:09:56.907: v4l2loopback not installed, virtual camera disabled
04:09:56.910: [obs-browser]: Version 2.17.8
04:09:56.910: [obs-browser]: CEF Version 95.0.0-MediaHandler.2463+g3b3ac84+chromium-95.0.4638.69
04:09:56.912: NVENC supported
04:09:56.912: FFMPEG VAAPI supported
04:09:56.925: ---------------------------------
04:09:56.925:   Loaded Modules:
04:09:56.925:     text-freetype2.so
04:09:56.925:     rtmp-services.so
04:09:56.925:     obs-x264.so
04:09:56.925:     obs-vst.so
04:09:56.925:     obs-transitions.so
04:09:56.925:     obs-outputs.so
04:09:56.925:     obs-libfdk.so
04:09:56.925:     obs-filters.so
04:09:56.925:     obs-ffmpeg.so
04:09:56.925:     obs-browser.so
04:09:56.925:     linux-v4l2.so
04:09:56.925:     linux-pulseaudio.so
04:09:56.925:     linux-jack.so
04:09:56.925:     linux-decklink.so
04:09:56.925:     linux-capture.so
04:09:56.925:     image-source.so
04:09:56.925:     frontend-tools.so
04:09:56.925:     decklink-ouput-ui.so
04:09:56.925:     decklink-captions.so
04:09:56.925:     aja.so
04:09:56.925:     aja-output-ui.so
04:09:56.925: ---------------------------------
04:09:56.926: aja main card manager: 140016407446368
04:09:56.926: NUM CARDS: 0
04:09:56.926: ==== Startup complete ===============================================
04:09:56.943: All scene data cleared
04:09:56.943: ------------------------------------------------
04:09:56.945: pulse-input: Server name: 'pulseaudio 15.0'
04:09:56.945: pulse-input: Audio format: s16le, 48000 Hz, 2 channels
04:09:56.945: pulse-input: Started recording from 'alsa_output.usb-SteelSeries_SteelSeries_Arctis_7-00.stereo-game.monitor'
04:09:56.945: [Loaded global audio device]: 'Desktop-Audio'
04:09:56.946: pulse-input: Server name: 'pulseaudio 15.0'
04:09:56.946: pulse-input: Audio format: s16le, 96000 Hz, 1 channels
04:09:56.946: pulse-input: Started recording from 'alsa_input.usb-MACROSILICON_ShadowCast-02.mono-fallback'
04:09:56.946: [Loaded global audio device]: 'Mikrofon-/AUX-Audio'
04:09:56.949: Switched to scene 'Szene'
04:09:56.949: ------------------------------------------------
04:18:43.355: User added source 'asdfg' (xcomposite_input) to scene 'Szene'
04:18:46.021: xcompcap: cleanup glXReleaseTexImageEXT failed: GLXBadPixmap
04:18:46.021: xcompcap: cleanup glXDestroyPixmap failed: GLXBadPixmap
04:18:46.022: xcompcap: [window-capture: 'asdfg'] update settings:
04:18:46.022: 	title: Steam
04:18:46.022: 	class: Steam
04:18:46.022: 	Bit depth: 24
04:18:46.022: 	Found proper GLXFBConfig (in 9): yes
04:18:46.022: 
04:18:46.555: xcompcap: cleanup glXReleaseTexImageEXT failed: GLXBadPixmap
04:18:46.555: xcompcap: cleanup glXDestroyPixmap failed: GLXBadPixmap
04:18:46.556: xcompcap: [window-capture: 'asdfg'] update settings:
04:18:46.556: 	title: Steam
04:18:46.556: 	class: Steam
04:18:46.556: 	Bit depth: 24
04:18:46.556: 	Found proper GLXFBConfig (in 9): yes
04:18:46.556: 
04:18:47.069: X Error: BadWindow (invalid Window parameter), Major opcode: 20, Minor opcode: 0, Serial: 92418
04:18:47.070: X Error: BadWindow (invalid Window parameter), Major opcode: 20, Minor opcode: 0, Serial: 92419
04:18:47.070: X Error: BadWindow (invalid Window parameter), Major opcode: 20, Minor opcode: 0, Serial: 92420
04:18:47.070: X Error: BadWindow (invalid Window parameter), Major opcode: 20, Minor opcode: 0, Serial: 92421```

**Comment by kkartaltepe** [comment]
> Internet is full of people reporting this problem and it exists for years now. 

Indeed the internet is full of people with unrelated issues that all manifest as what users can only describe as "black screen". Which is why we have support to help users diagnose and solve their issues and bring up non-user problems like bugs. As we can see from your logs it is clearly not the case that you have the same issue as the OP. And what you _should_ do is to follow the instructions originally given and use one of our support channels.

Combining superficially similar issues together in issues like this only makes then less likely to get resolved by hiding them among already fixed issues, and it also hurts other users who are going to try all kinds of silly fixes for issues they dont have (as you said the internet is full of people reporting "this" and im sure you have tried every fix you could find unrelated to your issue).

Please file a separate bug report to avoid reviving this useless issue yet again.
