### ISSUE TITLE
Filter color values from previous version no longer display correctly (OBS 27.0 RC1) 

### ISSUE THREAD

**Issue by GreatSphynx** [obsproject/obs-studio#4497]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0-rc1

### OBS Studio Log URL

https://obsproject.com/logs/vrrQ_rBu3GFRFxts

### Expected Behavior

On previous version I had a scene with a large number of assets with various color correction and keying filters to create a collage. Transparency, key colors, and other variables were all set to maintain the proper collage of sources.

### Current Behavior

Updated to v27 RC-1 for DX12 frame out of order fix. Instead loaded up scene and it appears that all previous color values on every filter in the scene now are being displayed differently (possibly due to color space change). Tested other color values. Current solution seems to be manually redoing all filters on over 50 sources. Filter settings should carry over visually.

### Steps to Reproduce

1. Create scene in previous version and compose multiple overlayed sources.
2. Apply color correction and color key filters to sources, and adjust settings to desired visuals
3. Load scene in v27 RC-1
4. Filter visual settings are not carried over.

### Anything else we should know?

I know my scene is dumb as hell but its been gradually added to over the course of a year. Would be hell to redo all filter settings to try and match the original look. For now I'll use the previous stable build.

**Comment by WizardCM** [comment]
This was fixed in #4452 and will be available in RC2.
