### ISSUE TITLE
Browser Source ignoring css property opacity

### ISSUE THREAD

**Issue by BeeFox-sys** [obsproject/obs-studio#4498]
### Operating System Info

Windows 10

### OBS Studio Version

26.1.1

### OBS Studio Log URL

none

### Expected Behavior

Expected the Browser Source element to correctly apply the css opacity property.
When text or an image has an opacity of 0.5, it is expected to be 50% visible

### Current Behavior

Currently, the opacity property is ignored and everything is set to 1.0 opacity, however the `filter: opacity ()` function works on images, and transparent colours work for text, borders, etcetera

### Steps to Reproduce

1. Create a new Browser Element
2. Set the page to something with an element that uses the opacity property
3. The browser source does not respect this and will display it as full opacity

**Comment by WizardCM** [comment]
Please include a session log file.

**Comment by WizardCM** [comment]
I cannot reproduce this issue. `body { opacity: 0.1; }` in the Custom CSS box works correctly on Windows.

**Comment by Scrxtchy** [comment]
Opening a debugger with `--remote-debugging-port=9999` the rules are still injected into style tags in the header
![image](https://user-images.githubusercontent.com/12771982/114304490-c87aaa00-9b16-11eb-8f1e-4cc26fd107e3.png)
... and also I could not replicate it on a windows machine
![image](https://user-images.githubusercontent.com/12771982/114304552-25766000-9b17-11eb-90dd-94c829d55890.png)

**Comment by BeeFox-sys** [comment]
I have done more testing and it seems that it only effects objects directly on the background?

Log Link: https://obsproject.com/logs/ENSrkdaDHI_t7CkK
A site that has this issue: https://commissionersafetyreviewboard.org/

**Comment by BeeFox-sys** [comment]
Ah I was incorrect about my obs version, I will update and test again

**Comment by BeeFox-sys** [comment]
I Can confirm as of 26.1.1 this is still an issue

**Comment by Scrxtchy** [comment]
Still cannot replicate.
You have not provided either of any examples of what your css input looks like so if there's any issue with how we are doing it differently to yours is possible, or any visual representation that would go alongside this.

in the url provided, I was able to appropriately target `body`, `.content`, `li` and `img` elements without issues, even without an `!important` flag

**Comment by BeeFox-sys** [comment]
That's really odd, I can attach a screenshot of what it looks like to me. and my css is literally just `opacity:50%;`

Here is a test html page I wrote up, it works in browser however not in OBS Studio

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Opacity Test</title>
    <style>
        h1{
            opacity: 50%;
        }
    </style>
</head>
<body>
    <h1>Example Text</h1>
</body>
</html>```

**Comment by BeeFox-sys** [comment]
Huh! I think I just figured it out! it is specificly when opacity is described with a percent, using a float such as 0.5 seems to operate fine?

**Comment by Scrxtchy** [comment]
Yeah, the version of CEF in obs 26 is too old to support opacity as a percentage. There's a list of whichbbrowsers support which value at the bottom of this mdn document 
https://developer.mozilla.org/en-US/docs/Web/CSS/opacity

It is added in version 78

**Comment by BeeFox-sys** [comment]
Thank you! for now I will just use .5 as a work around c:
