### ISSUE TITLE
Virtual camera output format not working with most applications on Linux

### ISSUE THREAD

**Issue by knipknap** [obsproject/obs-studio#4499]
### Operating System Info

Ubuntu 20.10
Kernel: 5.11.0-11-lowlatency

### OBS Studio Version

26.1.2

### OBS Studio Log URL

https://gist.github.com/knipknap/bb3e23c2e1dc1b0259ad29ef78f69c7b

### Expected Behavior

The camera should show up and be supported in applications such as Cheese, Zoom, and Cisco Webex.

### Current Behavior

The camera starts up properly in VLC, but it doesn't show up in Zoom (in Chrome) or Webex, and it fails with an error ("There was an error playing video from the webcam") in Cheese.

### Steps to Reproduce

1. Install OBS and v4l2loopback-dkms, reboot, start OBS, set Settings -> Video to 1280x720 + 30fps, click "Start virtual camera", and ensure that the camera works properly in VLC.
2. Start Zoom in Chrome: Observe that the virtual camera does not show up in the camera selection menu.
3. Start Cheese: Observe that the camera shows up (it only shows up if the mentioned settings of 1280x720 + 30fps were made; otherwise it doesn't even show up as a capture device).
3. Select OBS Virtual Camera
4. Note that it doesn't work, the error message in Cheese is "There was an error playing video from the webcam"

### Anything else we should know?

Since the camera works in VLC (though only at 1280x720, not at 1920x1080), I am guessing that it has to do with color format configuration. However, I tried all available modes under Settings -> Advanced and none of them work with Cheese or Zoom.
I found online recommendations to use YUY2 output, but didn't find this in the OBS settings.

**Comment by Swamp2k9** [comment]
I'm having the same issue. The virtual camera works fine in Brave, but not in Firefox.

OS: Pop!_OS 22.04 LTS
Gnome: 42.9
OBS: 30.2.2 (64-bit)

**Comment by Fenrirthviti** [comment]
Closing as stale. If this is still an issue please open a new issue with updated reproduction steps on the latest version of OBS.

As a note, please ensure to provide log files as well as steps followed to reproduce alongside "me too" comments, as they are unactionable otherwise.
