### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [obsproject/obs-studio#4519]
### Operating System Info

Other

### OBS Studio Version

Other

### OBS Studio Log URL

x

### Expected Behavior

[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [DeckLinkDeviceInstance](https://github.com/obsproject/obs-studio/blob/8285141ba5e5687e7ba1b3c97f303583941cfcbf/plugins/decklink/decklink-device-instance.cpp#L82 "Destructor for DeckLinkDeviceInstance")
- [DecklinkOutputUI::SetupPropertiesView](https://github.com/obsproject/obs-studio/blob/cab32e7e67c2a78d10e0961f746ee7408978fb43/UI/frontend-plugins/decklink-output-ui/DecklinkOutputUI.cpp#L28 "DecklinkOutputUI::SetupPropertiesViewfunction")
- [MSDK_SAFE_DELETE_ARRAY](https://github.com/obsproject/obs-studio/blob/cab32e7e67c2a78d10e0961f746ee7408978fb43/plugins/obs-qsv11/common_utils.h#L67 "MSDK_SAFE_DELETE_ARRAY macro")

### Current Behavior

Some questionable pointer checks.

### Steps to Reproduce

[Perform another bit of source code analysis](https://clang.llvm.org/extra/clang-tidy/checks/readability-delete-null-pointer.html "Deletion of unnecessary null pointer checks").

**Comment by dodgepong** [comment]
Is this causing a problem somewhere? If not, could you just submit a pull request?

We don't typically use Github issues for tracking fixup issues.

**Comment by elfring** [comment]
I propose to improve the run time characteristics another bit (according to special source code search patterns).

**Comment by RytoEX** [comment]
After further consideration and discussion with other project members, we've decided to close this issue.  If you have proposed fixes for these issues, please feel free to submit pull requests.
