### ISSUE TITLE
Remuxing process continues instead of stopping

### ISSUE THREAD

**Issue by chticer** [obsproject/obs-studio#4522]
### Operating System Info

Windows 10

### OBS Studio Version

26.1.1

### OBS Studio Log URL

https://obsproject.com/logs/IJVvvaiYcrwhERo7

### Expected Behavior

The program should not close when clicking "No" to the dialog box indicating that remuxing is in progress after trying to close OBS.

### Current Behavior

The main program closes but leaves the remux recording dialog opened and freezes (does not fully crash but is not responsive).

### Steps to Reproduce

1. Click "File -> Remux Recordings"
2. Select a file for OBS Recording and Target File then click "Remux"
3. Before remuxing finishes, close OBS in any way
4. Click "No" to "Remuxing is not finished, stopping now may render the target file unusable. Are you sure you want to stop remuxing?"
5. Repeat step 4 again one more time (same dialog message reappears) then go to step 6
6. Program closes, remux recordings dialog box still shows but is unresponsive and must be killed

**Comment by RytoEX** [comment]
I can confirm that this happens in OBS Studio 26.1.1 on Windows 10.  Clicking "No" to the first dialog seems to result in the main application spawning a second dialog and then the main application closes.  In my case, the remaining remux dialog closed itself without needing to be force closed.

Perhaps the "No" in this case sends a signal to the main application window that it shouldn't?  Something to investigate later.

**Comment by notr1ch** [comment]
I looked into this, it seems there is nothing that attaches an active remux operation to the main application, so the app has no 
 way of knowing if a remux operation is in progress when closing. The "Are you sure you want to stop" prompt is actually firing in two places, once on the remux window being closed as part of Qt closing all active windows, and once on the OBSRemux destructor (which is obviously way too late to say no).

I wasn't able to replicate the freezing. The dialog did remain open but after a few seconds the remux completed successfully and it closed by itself.

**Comment by chticer** [comment]
Okay, can confirm that the dialog does remain open and closes automatically only when the remuxing process is finished, which mine took a few minutes because of a >2 GB file. The dialog window does not update the status of the remuxing process making it seem that it is frozen.

To add, right after step 3, the sources list becomes empty. I am assuming that OBS has started the process of releasing sources for program shutdown. This should happen if the user truly wants to quit OBS and stop the remuxing process but user decision is not made at that point yet.

**Comment by RytoEX** [comment]
I can also confirm that despite the main application window closing and the remux dialog not updating afterward, the remux process itself completes and I have a working file afterward.

**Comment by chticer** [comment]
I have updated the title to reflect that this issue pertains to the remuxing process overall. In step 3 of the original reproduction steps, the same outcome occurs when switching scene collections.
