### ISSUE TITLE
Unable to use DirectInput Joystick mappings for push to talk bindings

### ISSUE THREAD

**Issue by Hawkeye4040** [obsproject/obs-studio#4526]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

I'm using Streamlabs OBS but I know the current doesn't support it.

### OBS Studio Log URL

obsproject.com

### Expected Behavior

I would like to be able to use the buttons on my Joystick and throttle (specifically the Thrustmaster T16000M and TWCS throttle). That way as I'm streaming my existing push to talk bindings on my HOTAS trigger my push to talk for streaming/recording video as well as it being layered with all the existing keybindings.

### Current Behavior

It simply doesn't read input when you press a button to add the keybind as it would on your keyboard.

### Steps to Reproduce

1. Plug in any joystick or game controller using DirectInput
2. Boot up OBS and open settings
3. Open hotkeys and attempt to bind push to talk or similar behavior to a joystick button.

### Anything else we should know?

I technically use Streamlabs OBS but I also have standard OBS for testing/dev purposes so I did attempt this on there too to rule out Streamlabs simply not catching up to the open source code.

**Comment by tehbasshunter** [comment]
While I know one of the devs/contributors will give a better explanation to my understanding it's simply a "missing option" atm.  
  
(You're not the only one wanting PTT with gamepads)

**Comment by Hawkeye4040** [comment]
> While I know one of the devs/contributors will give a better explanation to my understanding it's simply a "missing option" atm.
> 
> (You're not the only one wanting PTT with gamepads tbf)

I'm not saying put it on the top of the priorities list just submitting it. I might even add the functionality myself and submit PR after we talk about it here a bit since I probably need it more than other people.

**Comment by Hawkeye4040** [comment]
I also have a couple keyboard keys that are used to communicate in the flight sim I'm doing this for. Those work fine of course. But once I'm flying if I want to use PTT it won't pick that up which I would like it too and I'd like that ability on my HOTAS for pretty obvious reasons. You want to keep your hands on the stick. 

I'm still looking into it more myself at the moment but I think all that needs to be done is the addition of DirectInput to the Hotkey mapping section.

![image](https://user-images.githubusercontent.com/22573488/114665073-6c985880-9cb1-11eb-9aab-aad23c7346f0.png)

**Comment by RytoEX** [comment]
This is a feature request and not a bug report.  We use GitHub issues strictly for verified bug reports.  We don't support DirectInput.  Please voice your support for adding this feature here.
https://ideas.obsproject.com/posts/9/allow-xinput-dinput-device-on-windows-for-hotkeys

If you're able to write the code to support it yourself, PRs are welcome.  Please make sure you check our [contributing document](https://github.com/obsproject/obs-studio/blob/4a890e1da9a27003c796527b4a603312514e9eac/CONTRIBUTING.rst).

**Comment by Hawkeye4040** [comment]
> This is a feature request and not a bug report. We use GitHub issues strictly for verified bug reports. We don't support DirectInput. Please voice your support for adding this feature here.
> https://ideas.obsproject.com/posts/9/allow-xinput-dinput-device-on-windows-for-hotkeys
> 
> If you're able to write the code to support it yourself, PRs are welcome. Please make sure you check our [contributing document](https://github.com/obsproject/obs-studio/blob/4a890e1da9a27003c796527b4a603312514e9eac/CONTRIBUTING.rst).

my mistake how do I change it or do I have to re-post?

**Comment by RytoEX** [comment]
> my mistake how do I change it or do I have to re-post?

You don't change it or re-post it.  We only use GitHub Issues for verified bug reports.  What you're asking for is a feature request, and we track feature requests at https://ideas.obsproject.com/.  I've linked you to a feature request submission that already exists for xinput/dinput devices.

https://ideas.obsproject.com/posts/9/allow-xinput-dinput-device-on-windows-for-hotkeys

**Comment by Hawkeye4040** [comment]
> > my mistake how do I change it or do I have to re-post?
> 
> You don't change it or re-post it. We only use GitHub Issues for verified bug reports. What you're asking for is a feature request, and we track feature requests at https://ideas.obsproject.com/. I've linked you to a feature request submission that already exists for xinput/dinput device based hotkeys.
> 
> https://ideas.obsproject.com/posts/9/allow-xinput-dinput-device-on-windows-for-hotkeys

That's a strange way to do it. I don't see why you don't have everything in the same place. I don't see how I could've possibly known that but I saw that post you linked and apparently so far it's just limited to Linux so I suppose I'll have to work on it myself.

**Comment by dodgepong** [comment]
> I don't see why you don't have everything in the same place

Github doesn't have the featureset we want for managing feature suggestions -- namely, a useful way to solicit and track votes for a particular feature.

Also, keeping feature requests on a separate site reduces noise on the Github project considerably, and allows people finer control over what project content they get notifications for.
