### ISSUE TITLE
Audio track 1 offset/desynced

### ISSUE THREAD

**Issue by flaeri** [obsproject/obs-studio#4530]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

OBS 27.0.0-rc2

### OBS Studio Log URL

https://obsproject.com/logs/y9XfULuwDnckI7R0

### Expected Behavior

When recording with multiple audio tracks, I would expect audio track 1 (0) to be synced with the other audio tracks.

### Current Behavior

Regardless of encoder (video or audio), regardless of container (mp4 / mkv), audio track 1 (0) is not in sync with the other tracks. It seems to be lagging behind (its later) by some degree, maybe around 10-20ms.

The PTS and DTS seem to be identical for all tracks, so I believe its earlier in the pipeline (prior to encoding and muxing).

### Steps to Reproduce

1. Enable two or more audio tracks Output>recording (advanced)
2. Ensure you have the same audio device on both (or more)
3. Hit start recording
4. Use your mic to record yourself clapping or snapping your fingers
5. Hit stop recording
6. Import the video file into an editor/NLE capable of handling multiple tracks, like Adobe Premiere or Davinci Resolve
7. Observe how audio track 1 is later than the others (which are in sync)

### Anything else we should know?

This occurs not only on the rc2, but also on the current release version (26.1.1). I reproduced this on rc2, and didnt want the log to differ from the reported version. This was reproduced on an nvme SSD.

I've confirmed this happens on at least one more machine. I've observed it in Davinci Resolve personally, and I've had a friend check it in premiere (same issue).

**Comment by p0mz0r** [comment]
This is coming from me. I have this behaviour on 26.1.1 (using OBS.live). In Premiere audio Track 1 has the same length as the video file, track 2 and 3 for me are different. Which is odd seeing as Track 1 is pretty much just 2 and 3 merged (2 has the mic, 3 has the desktop audio and track 1 has both). 
See the images for what the tracks look like.


![image](https://user-images.githubusercontent.com/1659998/114747599-4de99e80-9d51-11eb-95a0-55be0b5faa0f.png)

![image](https://user-images.githubusercontent.com/1659998/114747581-488c5400-9d51-11eb-975a-bcee1226a83e.png)

**Comment by WizardCM** [comment]
I've been able to personally reproduce this for over a year, as have others (including @pkviet and EposVox). pkv did fix some related bugs, but his changes apparently didn't fix this particular one.

**Comment by Trouffman** [comment]
This is also present on previous version.
> 2 frames missing on audio tracks 2-6

Error log : 
12:19:32.942: ==== Recording Stop ================================================
12:19:32.978: warning: Timestamps are unset in a packet for stream 0. This is deprecated and will stop working in the future. Fix your code to set the timestamps properly
12:19:33.027: warning: 2 frames left in the queue on closing
12:19:33.027: warning: 2 frames left in the queue on closing
12:19:33.028: warning: 2 frames left in the queue on closing
12:19:33.028: warning: 2 frames left in the queue on closing
12:19:33.028: warning: 2 frames left in the queue on closing
12:19:33.028: warning: 2 frames left in the queue on closing
