### ISSUE TITLE
Widgets do not load

### ISSUE THREAD

**Issue by beucismis** [obsproject/obs-studio#4541]
### Operating System Info

Other

### Other OS

Debian GNU/Linux 11 (bullseye)

### OBS Studio Version

Other

### OBS Studio Version (Other)

26.1.2+dfsg1-1+b2 (linux)

### OBS Studio Log URL

https://paste.debian.net/hidden/10d95bff

### Expected Behavior

Installing window widgets.

### Current Behavior

Screenshot: https://i.imgur.com/Bpbjmds.png

### Steps to Reproduce

1. Open the program
2. Wait...

### Anything else we should know?

I deleted it and installed it again, but the problem has not changed.

**Comment by kkartaltepe** [comment]
Fixed in 27. But since you are not using our package, you should be raising bugs against your package maintainer.

**Comment by beucismis** [comment]
@kkartaltepe I can't find Fized 27.

**Comment by dodgepong** [comment]
Version 27 is currently in testing and has not reached final release yet. If you want the fix, you'll need to build it yourself, or ask your package maintainer to make a package of the current release candidate.
