### ISSUE TITLE
Clicking 'no' on remove confirmation acts the same as 'yes'

### ISSUE THREAD

**Issue by Vainock** [obsproject/obs-studio#4546]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.0.0-rc2

### OBS Studio Log URL

https://obsproject.com/logs/UZcuUod8yI3eLgeF

### Expected Behavior

Clicking 'no' when removing multiple items should cancel the action and not remove them.

### Current Behavior

When being asked 'Are you sure you wish to remove %1 items?' and clicking 'no' results in the items being removed.
Clicking 'yes' also results in the items being removed.

### Steps to Reproduce

1. Create 2 sources.
2. Select both of them.
3. Remove them with the - symbol.
4. Click 'no'.

### Anything else we should know?

It seems not to occur for a single item.

**Comment by WizardCM** [comment]
This is caused by this line:

https://github.com/obsproject/obs-studio/blob/81757006208888aeec2e9f06f1a6e07cc46daaae/UI/window-basic-main.cpp#L5527

Which was modified as part of undo/redo. Originally it was more like:

```cpp
return Yes == remove_items.clickedButton();
```
