### ISSUE TITLE
OBS Video Source not Using Video Decoder [VirtualGL]

### ISSUE THREAD

**Issue by emreanilterzioglu4dsight** [obsproject/obs-studio#4561]
### Operating System Info

Ubuntu 20.04

### OBS Studio Version

26.1.1

### OBS Studio Log URL

none

### Expected Behavior

When Add MediaSource CPU usage %20 it should drop down to 4 or 5 percent.

### Current Behavior

When Add MediaSource CPU usage %20 it should drop down to 4 or 5 percent.

### Steps to Reproduce

1.Add Media Source

### Anything else we should know?

I am using remote obs with VGL and xpra setup. When I start video from Media Source it does not use GPU and I dont see any process on nvidia-smi. Also CPU %20. If I start streaming this video OBS use video encoding with gpu and i can see obs on nvidia-smi but still not decoding on GPU. I also tried VLC Source but this one is also same. Could you please help me? 

My command:
xpra start ssh://ubuntu@x.x.x.x --ssh="sudo ssh -i public_key.pem" --start="obs --collection user1 --profile user1 --multi" --exec-wrapper=/usr/bin/vglrun --env=VGL_LOGO=1

**Comment by WizardCM** [comment]
VGL and xpra are not a supported use case for OBS. Additionally, media source hardware decoding is media type specific and not guaranteed. 

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help) for further discussion.

**Comment by emreanilterzioglu4dsight** [comment]
Hi thanks for the fast reply,
I understand. Another question is on my home pc if i disable hardware decoding it uses 5percent more CPU. But on AWS iy uses 20 percent and that machine is much more powerful than my home pc. Is there any reason for this(Its only OBS's cpu usage not xpra or vgl)?

**Comment by emreanilterzioglu4dsight** [comment]
It also gives this error while scene init.
 [AVHWDeviceContext @ 0x7f77d0134880] VDPAU device creation on X11 display :15 failed.

**Comment by WizardCM** [comment]
> Hi thanks for the fast reply,
> But on AWS iy uses 20 percent and that machine is much more powerful than my home pc

GPU decoding for media additionally depends on the specific GPU. Again, try our support channels instead.
