### ISSUE TITLE
Pause/Resume Recording button should show its state visually

### ISSUE THREAD

**Issue by vintas** [obsproject/obs-studio#4563]
### Operating System Info

Windows 10

### OBS Studio Version

26.1.0

### OBS Studio Log URL

UX issue.

### Expected Behavior

The pause symbol(U+23F8 ⏸) changes to play symbol(U+23F5 ⏵, U+25B6 ▶) when paused and returns back when resumed.

Also the word 'unpause' is quite unintuitive, 'resume recording' may be better for the tooltip.

### Current Behavior

The tooltip text that shows that the recording is paused/unpaused only shows up when you hover the mouse over the button. Without this text it is not possible to know at first glance that the recording is going on or not.

When recording is paused:
![obs_paused_recording](https://user-images.githubusercontent.com/17967770/115423652-a1f5f680-a21b-11eb-8ab4-095b6f82cd1f.JPG)

When recording is resumed:
![obs_unpaused_recording](https://user-images.githubusercontent.com/17967770/115423736-b3d79980-a21b-11eb-893b-b35a0dcce0d3.JPG)

### Steps to Reproduce

1. Open OBS Studio
2. Start recording
3. Click on the pause button that appears besides stop recording.
4. Observe the pause button.

**Comment by WizardCM** [comment]
This is intended. Resume is not the same as "play", and we wanted to avoid confusion in that area. If the button is highlighted and the status bar says PAUSED, then the recording is paused.
