### ISSUE TITLE
Unable to stream

### ISSUE THREAD

**Issue by tandy-1000** [obsproject/obs-studio#4575]
### Operating System Info

Other

### Other OS

Fedora 34 - Testing

### OBS Studio Version

27.0.0-rc2

### OBS Studio Log URL

https://obsproject.com/logs/l6QzVqbyyclfsl_K

### Expected Behavior

Before upgrading to F34, using the F33 version of OBS, I was able to stream to Twitch on Xorg, but now that Wayland is supported I tried that, this issue persists in a Xorg session.

### Current Behavior

A popup says that OBS failed to start streaming, with the message "Starting the output failed. Please check the log for details. Note: If you are using the NVENC or AMD encoders, make sure your video drivers are up to date."

### Steps to Reproduce

1. Try to stream to Twitch with FFMPEG VAAPI output
2. Stream fails

### Anything else we should know?

This also fails when trying to go through the Auto configuration wizard, with this log output.
```==== Auto-config wizard testing commencing ======

info: ---------------------------------
info: video settings reset:
	base resolution:   1920x1080
	output resolution: 128x128
	downscale filter:  Lanczos
	fps:               60/1
	format:            NV12
	YUV mode:          709/Partial
info: NV12 texture support not available
error: Output ID 'rtmp_output' not found
error: Failed to create output 'test_stream'!
Segmentation fault (core dumped)```

**Comment by ElectronicWar** [comment]
Something in your OBS install is broken as it cannot load an essential internal plugin:
`os_dlopen(/usr//lib64/obs-plugins/obs-outputs.so->/usr//lib64/obs-plugins/obs-outputs.so): /usr//lib64/obs-plugins/obs-outputs.so: undefined symbol: ftl_ingest_update_params`

Contact your package maintainer for this issue.
