### ISSUE TITLE
Does not capture Rainbow Six: Siege anymore (Vulkan)

### ISSUE THREAD

**Issue by BorniPL** [obsproject/obs-studio#4577]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0-rc2

### OBS Studio Log URL

https://pastebin.com/GucvHw1T

### Expected Behavior

Captures R6S in all modes (fullscreen/borderless/windowed) with game capture source.

### Current Behavior

Does not capture the game + resizes the OBS window so it is above 1080p on vertical screen (so it goes a little bit to the 2nd screen).

### Steps to Reproduce

1. Open R6S in Vulkan fullscreen/borderless/windowed
2. Add Game Capture and choose R6S
3.
...

### Anything else we should know?

Ubisoft recently patched Intel Graphics wireframe feature - maybe they broke your hook.

**Comment by Mister36MN** [comment]
Tested this on rc2 and had no problems.

18:48:14.283: [game-capture: 'R6 Vulkan'] vk_shtex_init_d3d11_tex: OBS requesting VK_FORMAT_B8G8R8A8_UNORM texture format. capture dimensions: 1920x1080
18:48:14.284: [game-capture: 'R6 Vulkan'] vulkan shared texture capture successful
18:48:14.296: [game-capture: 'R6 Vulkan'] shared texture capture successful
18:48:17.280: [game-capture: 'R6 Vulkan'] Hooked DXGI

**Comment by Fenrirthviti** [comment]
Please use the Discord or forums for support requests.

**Comment by BorniPL** [comment]
@Mister36MN could you please share your GameSettings.ini file?

Maybe I'm missing some VulkanWhitelistedLayers

**Comment by Acamio28** [comment]
Still have this problem even after updating to update 27rc2

**Comment by BorniPL** [comment]
Guys maybe it's because of KB5001330 ?
