### ISSUE TITLE
where did the video fileters go?

### ISSUE THREAD

**Issue by walterDIDit** [obsproject/obs-studio#4581]
### Operating System Info

Windows 10

### OBS Studio Version

26.1.2

### OBS Studio Log URL

none

### Expected Behavior

video filters are not present

### Current Behavior

cant use video filters

### Steps to Reproduce

1.
2.
3.
...
none

**Comment by RytoEX** [comment]
Filters are present in OBS Studio 26.1.1 on Windows.  There is no OBS Studio 26.1.2 for Windows.

Please use our Discord or forums for support.
https://obsproject.com/help

**Comment by walterDIDit** [comment]
sorry clicked the worng one.  I am using 1.1    I cant get the chromakey or color key filters to show.  Do they have to be downloaded from somewhere?


Show Up, Connect, Succeed!!!
[cid:eb1d0a9e-8643-4e35-81d6-2232d09ee8f2][cid:233ecb14-23f9-437b-899f-d8a80a65db22][cid:63994324-d1ef-49b5-b1b6-7260197738d4]
[cid:86f668b0-0299-4d58-b465-5d7bbdcd5df4][cid:4d2072fa-0b01-4b67-9c52-b6c12932b428]

Steven L. Long BSN-Rn

Science Teacher, Goal Academy Schools - Pueblo

1861 South Pueblo Blvd.

Pueblo, Colorado 81005

719-569-2886

CONFIDENTIALITY NOTICE:
This e-mail message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential information. If you have received this communication in error, please immediately notify the sender by e-mail and delete the original message and do not review, distribute, or copy the message. Thank you for your cooperation.

________________________________
From: Ryan Foster ***@***.***>
Sent: Friday, April 23, 2021 11:14 AM
To: obsproject/obs-studio ***@***.***>
Cc: Steve Long ***@***.***>; Author ***@***.***>
Subject: [EXT]Re: [obsproject/obs-studio] where did the video fileters go? (#4581)


[EXTERNAL EMAIL] This message originated outside GOAL Academy. DO NOT CLICK links or attachments unless you recognize the sender and know the content is safe.

Filters are present in OBS Studio 26.1.1 on Windows. There is no OBS Studio 26.1.2 for Windows.

Please use our Discord or forums for support.
https://obsproject.com/help

**Comment by RytoEX** [comment]
A standard installation of OBS Studio has these filters included.

Please use our Discord or forums for support.
https://obsproject.com/help
