### ISSUE TITLE
OBS Cannot be minimized to the tray（无法最小化到托盘）

### ISSUE THREAD

**Issue by OG-C** [obsproject/obs-studio#4588]
### Operating System Info

Windows 10

### OBS Studio Version

26.1.1

### OBS Studio Log URL

21:39:30.139: CPU Name: Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz 21:39:30.139: CPU Speed: 2904MHz 21:39:30.139: Physical Cores: 6, Logical Cores: 6 21:39:30.139: Physical Memory: 16299MB Total, 5109MB Free 21:39:30.139: Windows Version: 10.0 Build 19042 (release: 2009; revision: 867; 64-bit) 21:39:30.139: Running as administrator: true 21:39:30.139: Aero is Enabled (Aero is always on for windows 8 and above) 21:39:30.139: Windows 10 Gaming Features: 21:39:30.140: 	Game DVR: On 21:39:30.224: Sec. Software Status: 21:39:30.229:  21:39:30.230:  21:39:30.231:  21:39:30.231:  21:39:30.241: Current Date/Time: 2021-04-12, 21:39:30 21:39:30.241: Browser Hardware Acceleration: true 21:39:30.241: Portable mode: false 21:39:30.708: OBS 26.1.1 (64-bit, windows) 21:39:30.708: --------------------------------- 21:39:30.709: --------------------------------- 21:39:30.709: audio settings reset: 21:39:30.709: 	samples per sec: 48000 21:39:30.709: 	speakers:        2 21:39:30.733: --------------------------------- 21:39:30.733: Initializing D3D11... 21:39:30.733: Available Video Adapters:  21:39:30.736: 	Adapter 0: NVIDIA GeForce GTX 1050 Ti 21:39:30.736: 	  Dedicated VRAM: 4213178368 21:39:30.736: 	  Shared VRAM:    4250804224 21:39:30.736: 	  PCI ID:         10de:1c82 21:39:30.736: 	  Driver Version: 27.21.14.5638 21:39:30.736: 	  output 0: pos={0, 0}, size={1920, 1080}, attached=true, refresh=60, name=27E1 21:39:30.756: Loading up D3D11 on adapter NVIDIA GeForce GTX 1050 Ti (0) 21:39:30.834: D3D11 loaded successfully, feature level used: b000 21:39:30.834: DXGI increase maximum frame latency success 21:39:30.834: D3D11 GPU priority setup success 21:39:31.346: --------------------------------- 21:39:31.346: video settings reset: 21:39:31.346: 	base resolution:   1920x1080 21:39:31.346: 	output resolution: 1920x1080 21:39:31.346: 	downscale filter:  Bicubic 21:39:31.346: 	fps:               30/1 21:39:31.346: 	format:            NV12 21:39:31.346: 	YUV mode:          709/Partial 21:39:31.346: NV12 texture support enabled 21:39:31.347: Audio monitoring device: 21:39:31.347: 	name: 默认 21:39:31.347: 	id: default 21:39:31.395: --------------------------------- 21:39:31.519: LoadLibrary failed for '../../obs-plugins/64bit/CalabashDanmuPlugin.dll': The specified module could not be found. 21:39:31.519:  (126) 21:39:31.519: Module '../../obs-plugins/64bit/CalabashDanmuPlugin.dll' not loaded 21:39:31.804: [CoreAudio encoder]: Adding CoreAudio AAC encoder 21:39:31.820: Failed to load 'en-US' text for module: 'decklink-captions.dll' 21:39:31.834: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll' 21:39:31.993: [AMF] Unable to load 'amfrt64.dll', error code 126. 21:39:31.995: [AMF] AMF Test failed due to one or more errors. 21:39:31.995: Failed to initialize module 'enc-amf.dll' 21:39:32.559: [obs-browser]: Version 2.9.1 21:39:32.559: [obs-browser]: CEF Version 75.1.16+g16a67c4+chromium-75.0.3770.100 21:39:32.710: NVENC supported 21:39:32.895: [obs-ndi] hello ! (version 4.9.0) 21:39:32.895: [obs-ndi] Trying 'd:\Program Files\NewTek\NDI 4 Runtime\v4' 21:39:32.895: [obs-ndi] Found NDI library at 'D:/Program Files/NewTek/NDI 4 Runtime/v4/Processing.NDI.Lib.x64.dll' 21:39:32.950: [obs-ndi] NDI runtime loaded successfully 21:39:32.956: [obs-ndi] NDI library initialized successfully (NDI SDK WIN64 06:20:19 Apr  1 2020 4.5.1.0) 21:39:33.229: Failed to load 'en-US' text for module: 'ObssDanmuInfo.dll' 21:39:33.402: Couldn't find VLC installation, VLC video source disabled 21:39:33.614: obs_register_source: Source 'monitor_capture' already exists!  Duplicate library? 21:39:33.614: obs_register_source: Source 'window_capture' already exists!  Duplicate library? 21:39:33.775: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed 21:39:33.776: No blackmagic support 21:39:34.351: --------------------------------- 21:39:34.351:   Loaded Modules: 21:39:34.351:     win-wasapi.dll 21:39:34.351:     win-mf.dll 21:39:34.351:     win-dshow.dll 21:39:34.351:     win-decklink.dll 21:39:34.351:     win-capture.dll 21:39:34.351:     vlc-video.dll 21:39:34.351:     text-freetype2.dll 21:39:34.351:     rtmp-services.dll 21:39:34.351:     ObssDanmuInfo.dll 21:39:34.351:     obs-x264.dll 21:39:34.351:     obs-vst.dll 21:39:34.351:     obs-transitions.dll 21:39:34.351:     obs-text.dll 21:39:34.351:     obs-qsv11.dll 21:39:34.351:     obs-outputs.dll 21:39:34.351:     obs-ndi.dll 21:39:34.351:     obs-filters.dll 21:39:34.351:     obs-ffmpeg.dll 21:39:34.351:     obs-browser.dll 21:39:34.351:     image-source.dll 21:39:34.351:     frontend-tools.dll 21:39:34.351:     enc-amf.dll 21:39:34.351:     decklink-ouput-ui.dll 21:39:34.351:     decklink-captions.dll 21:39:34.351:     coreaudio-encoder.dll 21:39:34.351:     CalabashWinCapture.dll 21:39:34.351: --------------------------------- 21:39:34.351: ==== Startup complete =============================================== 21:39:34.453: All scene data cleared 21:39:34.453: ------------------------------------------------ 21:39:34.575: WASAPI: Device '扬声器 (Realtek High Definition Audio)' [48000 Hz] initialized 21:39:34.575: [Loaded global audio device]: '桌面音频' 21:39:34.690: WASAPI: Device '麦克风 (Realtek High Definition Audio)' [48000 Hz] initialized 21:39:34.690: [Loaded global audio device]: '麦克风/Aux' 21:39:34.711: adding 21 milliseconds of audio buffering, total audio buffering is now 21 milliseconds (source: 麦克风/Aux) 21:39:34.711:  21:39:34.724: [obs-ndi] started A/V threads for source '' 21:39:34.724: [obs-ndi] A/V thread for 'NDI™ 来源' started 21:39:34.727: Switched to scene '场景' 21:39:34.728: ------------------------------------------------ 21:39:34.728: Loaded scenes: 21:39:34.728: - scene '场景': 21:39:34.728:     - source: '显示器捕获' (monitor_capture) 21:39:34.728:     - source: 'NDI™ 来源' (ndi_source) 21:39:34.728:     - source: '视频采集设备' (dshow_input) 21:39:34.728: ------------------------------------------------ 21:39:34.942: --------------------------------- 21:39:34.942: [DShow Device: '视频采集设备'] settings updated:  21:39:34.942: 	video device: OBS Virtual Camera 21:39:34.942: 	video path:  21:39:34.942: 	resolution: 1920x1080 21:39:34.942: 	flip: 0 21:39:34.942: 	fps: 30.00 (interval: 333333) 21:39:34.942: 	format: NV12 21:39:40.282: ==== Shutting down ================================================== 21:39:40.355: [obs-ndi] audio thread for 'NDI™ 来源' completed 21:39:40.383: WASAPI: Device '扬声器 (Realtek High Definition Audio)' Terminated 21:39:40.386: WASAPI: Device '麦克风 (Realtek High Definition Audio)' Terminated 21:39:40.391: All scene data cleared 21:39:40.391: ------------------------------------------------ 21:39:40.545: [obs-ndi] goodbye ! 21:39:40.547: [Scripting] Total detached callbacks: 0 21:39:40.567: Freeing OBS context data 21:39:40.586: == Profiler Results ============================= 21:39:40.586: run_program_init: 5247.46 ms 21:39:40.586:  ┣OBSApp::AppInit: 143.679 ms 21:39:40.586:  ┃ ┗OBSApp::InitLocale: 91.228 ms 21:39:40.586:  ┗OBSApp::OBSInit: 4909.88 ms 21:39:40.586:    ┣obs_startup: 102.121 ms 21:39:40.586:    ┗OBSBasic::OBSInit: 4339.78 ms 21:39:40.586:      ┣OBSBasic::InitBasicConfig: 0.691 ms 21:39:40.586:      ┣OBSBasic::ResetAudio: 0.353 ms 21:39:40.586:      ┣OBSBasic::ResetVideo: 637.288 ms 21:39:40.586:      ┣OBSBasic::InitOBSCallbacks: 0.007 ms 21:39:40.586:      ┣OBSBasic::InitHotkeys: 0.036 ms 21:39:40.586:      ┣obs_load_all_modules: 2955.14 ms 21:39:40.586:      ┃ ┣obs_init_module(CalabashWinCapture.dll): 1.659 ms 21:39:40.586:      ┃ ┣obs_init_module(coreaudio-encoder.dll): 110.332 ms 21:39:40.586:      ┃ ┣obs_init_module(decklink-captions.dll): 0.021 ms 21:39:40.586:      ┃ ┣obs_init_module(decklink-ouput-ui.dll): 0.491 ms 21:39:40.586:      ┃ ┣obs_init_module(enc-amf.dll): 87.495 ms 21:39:40.586:      ┃ ┣obs_init_module(frontend-tools.dll): 7.121 ms 21:39:40.586:      ┃ ┣obs_init_module(image-source.dll): 0.005 ms 21:39:40.586:      ┃ ┣obs_init_module(obs-browser.dll): 32.333 ms 21:39:40.586:      ┃ ┣obs_init_module(obs-ffmpeg.dll): 11.688 ms 21:39:40.586:      ┃ ┃ ┗nvenc_check: 11.634 ms 21:39:40.586:      ┃ ┣obs_init_module(obs-filters.dll): 0.023 ms 21:39:40.586:      ┃ ┣obs_init_module(obs-ndi.dll): 67.283 ms 21:39:40.586:      ┃ ┣obs_init_module(obs-outputs.dll): 0.223 ms 21:39:40.586:      ┃ ┣obs_init_module(obs-qsv11.dll): 63.791 ms 21:39:40.586:      ┃ ┣obs_init_module(obs-text.dll): 0.213 ms 21:39:40.586:      ┃ ┣obs_init_module(obs-transitions.dll): 0.009 ms 21:39:40.586:      ┃ ┣obs_init_module(obs-vst.dll): 0.002 ms 21:39:40.586:      ┃ ┣obs_init_module(obs-x264.dll): 0.001 ms 21:39:40.586:      ┃ ┣obs_init_module(ObssDanmuInfo.dll): 7.108 ms 21:39:40.586:      ┃ ┣obs_init_module(rtmp-services.dll): 1.97 ms 21:39:40.586:      ┃ ┣obs_init_module(text-freetype2.dll): 0.926 ms 21:39:40.586:      ┃ ┣obs_init_module(vlc-video.dll): 0.057 ms 21:39:40.586:      ┃ ┣obs_init_module(win-capture.dll): 39.252 ms 21:39:40.586:      ┃ ┣obs_init_module(win-decklink.dll): 5.265 ms 21:39:40.586:      ┃ ┣obs_init_module(win-dshow.dll): 82.716 ms 21:39:40.586:      ┃ ┣obs_init_module(win-mf.dll): 0 ms 21:39:40.586:      ┃ ┣obs_init_module(win-wasapi.dll): 0.008 ms 21:39:40.586:      ┃ ┗reset_win32_symbol_paths: 3.501 ms 21:39:40.586:      ┣OBSBasic::ResetOutputs: 60.651 ms 21:39:40.586:      ┣OBSBasic::CreateHotkeys: 0.045 ms 21:39:40.586:      ┣OBSBasic::InitService: 0.562 ms 21:39:40.586:      ┣OBSBasic::InitPrimitives: 0.076 ms 21:39:40.586:      ┗OBSBasic::Load: 320.69 ms 21:39:40.586: obs_hotkey_thread(25 ms): min=0.002 ms, median=0.004 ms, max=28.286 ms, 99th percentile=1.121 ms, 99.75% below 25 ms 21:39:40.586: audio_thread(Audio): min=0 ms, median=0.029 ms, max=0.242 ms, 99th percentile=0.085 ms 21:39:40.586: obs_graphics_thread(33.3333 ms): min=0.073 ms, median=0.375 ms, max=19.607 ms, 99th percentile=5.819 ms, 100% below 33.333 ms 21:39:40.586:  ┣tick_sources: min=0.001 ms, median=0.14 ms, max=19.259 ms, 99th percentile=0.931 ms 21:39:40.586:  ┣output_frame: min=0.066 ms, median=0.126 ms, max=0.307 ms, 99th percentile=0.246 ms 21:39:40.586:  ┃ ┗gs_context(video->graphics): min=0.066 ms, median=0.126 ms, max=0.306 ms, 99th percentile=0.246 ms 21:39:40.586:  ┃   ┣render_video: min=0.005 ms, median=0.023 ms, max=0.09 ms, 99th percentile=0.066 ms 21:39:40.586:  ┃   ┃ ┗render_main_texture: min=0.003 ms, median=0.022 ms, max=0.088 ms, 99th percentile=0.065 ms 21:39:40.586:  ┃   ┗gs_flush: min=0.023 ms, median=0.1 ms, max=0.28 ms, 99th percentile=0.207 ms 21:39:40.586:  ┗render_displays: min=0 ms, median=0.067 ms, max=19.456 ms, 99th percentile=1.099 ms 21:39:40.586: ================================================= 21:39:40.586: == Profiler Time Between Calls ================== 21:39:40.586: obs_hotkey_thread(25 ms): min=24.974 ms, median=25.865 ms, max=53.845 ms, 34.3358% within ±2% of 25 ms (0% lower, 65.6642% higher) 21:39:40.586: obs_graphics_thread(33.3333 ms): min=33.22 ms, median=33.333 ms, max=33.448 ms, 100% within ±2% of 33.333 ms (0% lower, 0% higher) 21:39:40.586: ================================================= 21:39:40.590: Number of memory leaks: 0

### Expected Behavior

Always minimize to the system tray, not the taskbar
总是最小化到系统托盘，而不是任务栏

This setting cannot currently take effect
该设置当前无法生效

### Current Behavior

Always minimize to the system tray, not the taskbar
总是最小化到系统托盘，而不是任务栏

实际无论是否勾选，均不生效
Actually, no matter whether it is checked or not, it will not take effect

### Steps to Reproduce

1. Settings
2. General
3. System tray
...
1.设置
2.通用
3.系统托盘
...

### Anything else we should know?

using Google Translate
使用谷歌翻译

**Comment by notr1ch** [comment]
Can't reproduce this here. Are you able to show a video of the problem?


https://user-images.githubusercontent.com/876345/115964004-99a30180-a522-11eb-830b-1c9cca90b6dd.mp4

**Comment by OG-C** [comment]
我是从以前版本一路升级过来的，持续了大半年接近一年，最早出现该问题好像是24.x的某个版本。最后能检测到的版本是26.1.1，以为是BUG，等更新修复，等了许久，直到在github上下载安装了27.0.2覆盖安装依然出现此问题。

在提交该问题的时候，我将OBS卸载清理干净，重新下载后恢复正常了。但在另外一台笔记本上也是同样的情况，但是因为该笔记本OBS有复杂的设置，我没有清理，暂不打算完全卸载，如需提交日志文件分析原因我愿意配合。

谢谢，我用的翻译机，可能会有些翻译错误。

I upgraded all the way from the previous version, and it lasted for half a year or nearly a year. The first issue appeared to be a certain version of 24.x. The last version that can be detected is 26.1.1. I thought it was a BUG. I waited for the update and repaired. I waited for a long time until I downloaded and installed the 27.0.2 overwrite installation on github. This problem still occurred.

When I submitted the problem, I uninstalled and cleaned up OBS, and it was back to normal after re-downloading. But the same is true on another laptop, but because the OBS of this laptop has complicated settings, I haven't cleaned it up, so I don't plan to uninstall it completely. If I need to submit a log file to analyze the reason, I am willing to cooperate.

Thank you, the translator I used may have some translation errors.

**Comment by wangshaohui1314** [comment]
@OG-C   
你可以用笔记本复现 录一个操作步骤  如果担心配置丢失 可以先保存这个路径下的所有文件：%appdata%\obs-studio\

**Comment by TrustMeICan** [comment]
Looks like caused by obs-ndi instead of purely OBS. See Palakis/obs-ndi#322.
