### ISSUE TITLE
laptop lenove e480 was can't search screen output and dark scenes, the screen caputure showing is below.

### ISSUE THREAD

**Issue by yhm2046** [obsproject/obs-studio#4589]
### Operating System Info

Windows 10

### OBS Studio Version

26.1.1

### OBS Studio Log URL

23:11:33.759: CPU Name: AMD Ryzen 5 3500X 6-Core Processor              23:11:33.759: CPU Speed: 3593MHz 23:11:33.759: Physical Cores: 6, Logical Cores: 6 23:11:33.759: Physical Memory: 16315MB Total, 8830MB Free 23:11:33.759: Windows Version: 10.0 Build 19041 (release: 2009; revision: 928; 64-bit) 23:11:33.759: Running as administrator: true 23:11:33.759: Aero is Enabled (Aero is always on for windows 8 and above) 23:11:33.759: Windows 10 Gaming Features: 23:11:33.759: 	Game Bar: Off 23:11:33.759: 	Game DVR: Off 23:11:33.759: 	Game DVR Background Recording: Off 23:11:33.761: Sec. Software Status: 23:11:33.762:  23:11:33.762:  23:11:33.763: Current Date/Time: 2021-04-24, 23:11:33 23:11:33.763: Browser Hardware Acceleration: true 23:11:33.763: Portable mode: false 23:11:34.114: OBS 26.1.1 (64-bit, windows) 23:11:34.114: --------------------------------- 23:11:34.115: --------------------------------- 23:11:34.115: audio settings reset: 23:11:34.115: 	samples per sec: 48000 23:11:34.115: 	speakers:        2 23:11:34.117: --------------------------------- 23:11:34.117: Initializing D3D11... 23:11:34.117: Available Video Adapters:  23:11:34.119: 	Adapter 0: NVIDIA GeForce GTX 970 23:11:34.119: 	  Dedicated VRAM: 4239917056 23:11:34.119: 	  Shared VRAM:    4258969600 23:11:34.119: 	  PCI ID:         10de:13c2 23:11:34.119: 	  Driver Version: 27.21.14.5671 23:11:34.119: 	  output 0: pos={0, 0}, size={1920, 1080}, attached=true, refresh=60, name=Philips 221EL 23:11:34.119: 	  output 1: pos={-1280, 0}, size={1280, 1024}, attached=true, refresh=60, name= 23:11:34.121: Loading up D3D11 on adapter NVIDIA GeForce GTX 970 (0) 23:11:34.186: D3D11 loaded successfully, feature level used: b000 23:11:34.186: DXGI increase maximum frame latency success 23:11:34.186: D3D11 GPU priority setup success 23:11:34.714: --------------------------------- 23:11:34.714: video settings reset: 23:11:34.714: 	base resolution:   1920x1080 23:11:34.714: 	output resolution: 1280x720 23:11:34.714: 	downscale filter:  Bicubic 23:11:34.714: 	fps:               30/1 23:11:34.714: 	format:            NV12 23:11:34.714: 	YUV mode:          709/Partial 23:11:34.714: NV12 texture support enabled 23:11:34.715: Audio monitoring device: 23:11:34.715: 	name: 默认 23:11:34.715: 	id: default 23:11:34.717: --------------------------------- 23:11:34.720: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded 23:11:34.721: Failed to load 'en-US' text for module: 'decklink-captions.dll' 23:11:34.721: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll' 23:11:34.753: [AMF] Unable to load 'amfrt64.dll', error code 126. 23:11:34.755: [AMF] AMF Test failed due to one or more errors. 23:11:34.755: Failed to initialize module 'enc-amf.dll' 23:11:34.785: [obs-browser]: Version 2.9.1 23:11:34.785: [obs-browser]: CEF Version 75.1.16+g16a67c4+chromium-75.0.3770.100 23:11:34.788: NVENC supported 23:11:34.888: Couldn't find VLC installation, VLC video source disabled 23:11:34.897: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed 23:11:34.898: No blackmagic support 23:11:34.902: --------------------------------- 23:11:34.902:   Loaded Modules: 23:11:34.902:     win-wasapi.dll 23:11:34.902:     win-mf.dll 23:11:34.902:     win-dshow.dll 23:11:34.902:     win-decklink.dll 23:11:34.902:     win-capture.dll 23:11:34.902:     vlc-video.dll 23:11:34.902:     text-freetype2.dll 23:11:34.902:     rtmp-services.dll 23:11:34.902:     obs-x264.dll 23:11:34.902:     obs-vst.dll 23:11:34.902:     obs-transitions.dll 23:11:34.902:     obs-text.dll 23:11:34.902:     obs-qsv11.dll 23:11:34.902:     obs-outputs.dll 23:11:34.902:     obs-filters.dll 23:11:34.902:     obs-ffmpeg.dll 23:11:34.902:     obs-browser.dll 23:11:34.902:     image-source.dll 23:11:34.902:     frontend-tools.dll 23:11:34.902:     enc-amf.dll 23:11:34.902:     decklink-ouput-ui.dll 23:11:34.902:     decklink-captions.dll 23:11:34.902:     coreaudio-encoder.dll 23:11:34.902: --------------------------------- 23:11:34.902: ==== Startup complete =============================================== 23:11:34.925: All scene data cleared 23:11:34.925: ------------------------------------------------ 23:11:35.000: WASAPI: Device '耳机 (HAVIT M3 Stereo)' [44100 Hz] initialized 23:11:35.000: [Loaded global audio device]: '桌面音频' 23:11:35.573: WASAPI: Device '耳机 (HAVIT M3 Hands-Free AG Audio)' [8000 Hz] initialized 23:11:35.573: [Loaded global audio device]: '麦克风/Aux' 23:11:35.576: Switched to scene '场景' 23:11:35.576: ------------------------------------------------ 23:11:35.576: Loaded scenes: 23:11:35.576: - scene '场景': 23:11:35.576: ------------------------------------------------ 23:11:35.590: adding 42 milliseconds of audio buffering, total audio buffering is now 42 milliseconds (source: 麦克风/Aux) 23:11:35.590: 

### Expected Behavior

show the display capture, but now was empty
！[image]（http://tiebapic.baidu.com/forum/w%3D580/sign=f1fde767a751f819f1250342eab54a76/bde4e61190ef76c66f009a678a16fdfaae516761.jpg）

### Current Behavior

show the display capture, but now was empty
！[image]（http://tiebapic.baidu.com/forum/w%3D580/sign=f1fde767a751f819f1250342eab54a76/bde4e61190ef76c66f009a678a16fdfaae516761.jpg）

### Steps to Reproduce

1. sources
2.add
3.display capture
...

### Anything else we should know?

I user Chinese, all above is writing English, if some grammatical error please tell me ,thanks

**Comment by yhm2046** [comment]
the image：![image](https://obsproject.com/forum/attachments/obs-png.68949/)

**Comment by notr1ch** [comment]
This is not a bug, laptops require additional configuration for screen capture. See https://obsproject.com/forum/threads/laptop-black-screen-when-capturing-read-here-first.5965/
