### ISSUE TITLE
'Scene name is already in use' error must not occur

### ISSUE THREAD

**Issue by VazMike** [obsproject/obs-studio#4591]
### Operating System Info

macOS 11.2

### OBS Studio Version

26.1.2

### OBS Studio Log URL

Not necessary.

### Expected Behavior

The error must not occur.

### Current Behavior

Scene can not be created.

### Steps to Reproduce

1. Create a scene named 'X'.
2. Delete the scene you've just created.
3. Try creating a scene with the same name 'X'.

**Comment by notr1ch** [comment]
Unable to reproduce this. Are you sure you are not using one of the v27 release candidates? This was a bug introduced by the undo / redo system which should be fixed in the latest RC.

**Comment by VazMike** [comment]
Yes, I'm using 26.1.2 version.
Maybe I should wait for the v27 release and see if it is fixed there.

**Comment by notr1ch** [comment]
Also check you don't have any third party plugins installed. A leaked reference might be keeping the scene active.

**Comment by VazMike** [comment]
You're right. I'm using [Move Transition plugin](https://obsproject.com/forum/resources/move-transition.913). If I turn it off the error disappears.

**Comment by VazMike** [comment]
Thanks, I've created an issue at the plugin's gihub repository.
