### ISSUE TITLE
Audio click (crackle) when pause record

### ISSUE THREAD

**Issue by sws33** [obsproject/obs-studio#4593]
### Operating System Info

Other

### Other OS

Debian Buster

### OBS Studio Version

27.0.0-rc2

### OBS Studio Version (Other)

27.0.0-rc2-32

### OBS Studio Log URL

https://obsproject.com/logs/-Dfn7idVTtLPwQVY

### OBS Studio Crash Log URL

no crash

### Expected Behavior

Audio silence 

### Current Behavior

Audio click (crackle)

### Steps to Reproduce

1. Start record
2. Make pause
3. Continue record
4. Stop record
5. Watch video and listen audio

### Anything else we should know?

See screenshot of audio click (crackle) when pause record - https://imgur.com/a/8TbmmJw

**Comment by Fenrirthviti** [comment]
Please use the support channels in Discord or our forums for support. Thanks!
