### ISSUE TITLE
Scene blinking when select a file or resize in Finder

### ISSUE THREAD

**Issue by diegoveloper** [obsproject/obs-studio#4594]
### Operating System Info

macOS 10.15

### OBS Studio Version

27.0.0-rc2

### OBS Studio Log URL

https://obsproject.com/logs/6pFJebMUZz8fQ8tF

### Expected Behavior

The scene shouldn't blink when we do another action.

### Current Behavior

The scene/recording blinks when the user do some other actions.

### Steps to Reproduce

1. See the scene.
2. Open the Finder.
3. Select some files from Finder and see the blinks.
4. Resize the Finder and see the blinks.

### Anything else we should know?

It's happening on the last stable version too, so it's not something related to 27.0.0.

https://user-images.githubusercontent.com/4898256/115977375-0d520800-a53d-11eb-849a-b36fb3900709.mov

**Comment by WizardCM** [comment]
I can't reproduce this when choosing items in Fider, but the window capture does flicker a little when resizing a Finder window. This is likely due to how the window capture API works, and is likely not limited to the RC so I'm deprioritising this for now.

**Comment by diegoveloper** [comment]
@RytoEX are you going to add any other label to this issue?

**Comment by diegoveloper** [comment]
one question, anybody know a hack to avoid this scene blinking? any workaround? (without using display capture)

**Comment by diegoveloper** [comment]
I used this `temporal` solution and it worked -> https://www.youtube.com/watch?v=zFfdZUL91Bw

**Comment by dossy** [comment]
Can you test #4863 and see if that fixes your issue, @diegoveloper?

**Comment by diegoveloper** [comment]
> Can you test #4863 and see if that fixes your issue, @diegoveloper?

Oh I saw that PR, is that a binary available that I could try or do I have to compile manually?

**Comment by dossy** [comment]
@diegoveloper A link to the test build is in [this comment](https://github.com/obsproject/obs-studio/pull/4863#issuecomment-859337943) on that PR.  Thanks!

**Comment by diegoveloper** [comment]
> @diegoveloper A link to the test build is in [this comment](https://github.com/obsproject/obs-studio/pull/4863#issuecomment-859337943) on that PR. Thanks!

I tried but I couldn't see/select my windows   (Code = Vscode)

![Screen Shot 2021-06-11 at 1 28 37 PM](https://user-images.githubusercontent.com/4898256/121733553-40366800-cab9-11eb-9ac0-ce191e0a3b3b.png)

Only a few were available

![Screen Shot 2021-06-11 at 1 28 57 PM](https://user-images.githubusercontent.com/4898256/121733596-4e848400-cab9-11eb-91af-daf8c0a3de71.png)

**Comment by dossy** [comment]
@diegoveloper Try executing this CLI command:

and then launching the new test build, then going into Security & Privacy Preferences, then under Privacy, select Screen Recording, and check the box next to "OBS.app", then restart OBS.

The explanation why this is necessary to get the test build working is in [this comment](https://github.com/obsproject/obs-studio/pull/4863#issuecomment-859687359).

**Comment by diegoveloper** [comment]
> @diegoveloper Try executing this CLI command:
> 
> ```
> tccutil reset ScreenCapture com.obsproject.obs-studio
> ```
> 
> and then launching the new test build, then going into Security & Privacy Preferences, then under Privacy, select Screen Recording, and check the box next to "OBS.app", then restart OBS.
> 
> The explanation why this is necessary to get the test build working is in [this comment](https://github.com/obsproject/obs-studio/pull/4863#issuecomment-859687359).

Ok, I tried but I have the same issue:


https://user-images.githubusercontent.com/4898256/121741889-b8eef180-cac4-11eb-9b14-090ca1967e84.mov

I think it's the same as described here -> https://www.youtube.com/watch?v=zFfdZUL91Bw

**Comment by dossy** [comment]
@diegoveloper Are you sure you're running the test build?  Unfortunately your screen recording doesn't show the OBS app window bar which shows the app version information.

**Comment by diegoveloper** [comment]
> @diegoveloper Are you sure you're running the test build? Unfortunately your screen recording doesn't show the OBS app window bar which shows the app version information.

Yep, I'm running the test version 

![Screen Shot 2021-06-11 at 4 56 26 PM](https://user-images.githubusercontent.com/4898256/121752572-0c1d7000-cad6-11eb-9cd5-65daa96c8e48.png)

**Comment by dossy** [comment]
@diegoveloper Okay, can I get some more information?  Would you mind sharing your log?  In the test build of OBS, go to "Help > Log Files > Upload Current Log File" and share the log file URL?  Thanks.

**Comment by diegoveloper** [comment]
> @diegoveloper Okay, can I get some more information? Would you mind sharing your log? In the test build of OBS, go to "Help > Log Files > Upload Current Log File" and share the log file URL? Thanks.

Sure, this is the log  : https://obsproject.com/logs/cxTbjUweUcmJFLAW

**Comment by dossy** [comment]
@diegoveloper Okay, I see that you have 3 `window_capture` input sources in the scene.  Even if they're hidden, I believe at the moment their threads are still running but should be sleeping waiting on a condvar.

Could you try creating a new test scene with only one single Window Capture input source in it and nothing else, and see if you can still reproduce the flicker?

**Comment by diegoveloper** [comment]
> @diegoveloper Okay, I see that you have 3 `window_capture` input sources in the scene. Even if they're hidden, I believe at the moment their threads are still running but should be sleeping waiting on a condvar.
> 
> Could you try creating a new test scene with only one single Window Capture input source in it and nothing else, and see if you can still reproduce the flicker?

here you have. Log: https://obsproject.com/logs/j8n1PF1WcGHZKQRL

Uploading Screen Recording 2021-06-11 at 7.24.51 PM.mov…

**Comment by dossy** [comment]
Ahh, I was able to finally reproduce the issue is that Finder window overlapping any part of the window you're capturing, by any chance?

Can you arrange things so that the window being captured is in the foreground, and your Finder window never overlaps it - can you still reproduce the effect?

I was able to reproduce the issue, and I just realized this in the Obj-C docs:

https://developer.apple.com/documentation/coregraphics/1455730-cgwindowlistcreateimagefromarray?language=objc

> Return Value
>
> A composite image formed from the contents of the specified set of windows. Invalid window IDs are ignored. If the windows are unreadable (because their sharing setting is set to kCGWindowSharingNone, for example) or **if no windows meet the specified criteria, this function returns an image that is either 0 by 0 pixels in size or is of the specified size but is filled with the transparent black color.** If you call this function from outside of a GUI security session or when no window server is running, this function returns NULL.

(Bold added to emphasize the relevant section.)

So, there is some condition under which `CGWindowListCreateImageFromArray()` is going to return an image, but it will be transparent black, not the actual pixels of the area being captured.

It would have been far better if Apple would either return `NULL` or even the 0x0 size, both which could be easily detected and skipped/ignored.  But, getting an image that matches the size you expect AND has transparent black pixels... sure, maybe try to recognize that and treat it as an error, but what if the ACTUAL window contents are just transparent black pixels, even for a few frames ... then that app's window won't capture properly, either!

**Comment by diegoveloper** [comment]
> Ahh, I was able to finally reproduce the issue is that Finder window overlapping any part of the window you're capturing, by any chance?
> 
> Can you arrange things so that the window being captured is in the foreground, and your Finder window never overlaps it - can you still reproduce the effect?
> 
> I was able to reproduce the issue, and I just realized this in the Obj-C docs:
> 
> https://developer.apple.com/documentation/coregraphics/1455730-cgwindowlistcreateimagefromarray?language=objc
> 
> > Return Value
> > A composite image formed from the contents of the specified set of windows. Invalid window IDs are ignored. If the windows are unreadable (because their sharing setting is set to kCGWindowSharingNone, for example) or **if no windows meet the specified criteria, this function returns an image that is either 0 by 0 pixels in size or is of the specified size but is filled with the transparent black color.** If you call this function from outside of a GUI security session or when no window server is running, this function returns NULL.
> 
> (Bold added to emphasize the relevant section.)
> 
> So, there is some condition under which `CGWindowListCreateImageFromArray()` is going to return an image, but it will be transparent black, not the actual pixels of the area being captured.
> 
> It would have been far better if Apple would either return `NULL` or even the 0x0 size, both which could be easily detected and skipped/ignored. But, getting an image that matches the size you expect AND has transparent black pixels... sure, maybe try to recognize that and treat it as an error, but what if the ACTUAL window contents are just transparent black pixels, even for a few frames ... then that app's window won't capture properly, either!

Yeah, as I mentioned on this comment -> https://github.com/obsproject/obs-studio/issues/4594#issuecomment-860063657  

Using that workaround works fine, and now that you give us that explanation is more clear , thanks.

Just one question, we won't be able to fix this issue (even if I overlap the finder with my window) until Apple makes some changes, right?

**Comment by dossy** [comment]
> Just one question, we won't be able to fix this issue (even if I overlap the finder with my window) until Apple makes some changes, right?

I'm actually going to experiment with some code to see if I can detect these "error frames" and skip them, and see what kind of results that gets.

But, yes, this is largely a consequence of what Apple's WindowServer is returning when our code asks for the contents of the window being captured.  In theory, you should be able to reproduce this same issue with Zoom or Google Meet or any other app other than OBS that lets you screen share a single window - I just tested this with Mozilla's [Screen Capture API demo](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture#result), click "Start Capture" then "Window" and select a window, then move and resize a window overlapping the shared window, and you can see the same blinking and blacking out of the captured window.

So, yes, at this point this is an issue with Apple's WindowServer computing the correct image for the window's contents in the window capture API.

Interesting that this doesn't happen when capturing an entire screen, but then you can't get the contents of a single window when it's being overlapped by another window, which is the entire point of Window Capture functionality.

**Comment by diegoveloper** [comment]
> > Just one question, we won't be able to fix this issue (even if I overlap the finder with my window) until Apple makes some changes, right?
> 
> I'm actually going to experiment with some code to see if I can detect these "error frames" and skip them, and see what kind of results that gets.
> 
> But, yes, this is largely a consequence of what Apple's WindowServer is returning when our code asks for the contents of the window being captured. In theory, you should be able to reproduce this same issue with Zoom or Google Meet or any other app other than OBS that lets you screen share a single window - I just tested this with Mozilla's [Screen Capture API demo](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture#result), click "Start Capture" then "Window" and select a window, then move and resize a window overlapping the shared window, and you can see the same blinking and blacking out of the captured window.
> 
> So, yes, at this point this is an issue with Apple's WindowServer computing the correct image for the window's contents in the window capture API.
> 
> Interesting that this doesn't happen when capturing an entire screen, but then you can't get the contents of a single window when it's being overlapped by another window, which is the entire point of Window Capture functionality.

Hey @dossy , thanks for all the work you are making, one question. Should I wait for a new workaround for this or because it's related to Apple API I should close the issue? 

Let me know if you need I test another build, many thanks :)

**Comment by dossy** [comment]
@diegoveloper - Let's leave this open for now - if I can find an efficient way to alpha-composite the current frame with the previous frame, it would eliminate this flicker as well.  So, this is still a "bug" in OBS, technically, but it might be one that's a little harder to fix.  Thanks for asking!

**Comment by gxalpha** [comment]
Please test if this still happens with the new macOS Screen Capture source on macOS 13.

**Comment by gxalpha** [comment]
As alluded to in the comment above, we believe that this problem no longer exists in the new ScreenCaptureKit API used by the "macOS Screen Capture" source. Seeing that there was no response to that comment, I will assume that this is the case. If this problem can also be observed with the macOS Screen Capture source (on macOS 13.1 or newer), please open a new report with new steps to reproduce.
