### ISSUE TITLE
OBS crashes on exit when applying Noise Suppression filter

### ISSUE THREAD

**Issue by Vainock** [obsproject/obs-studio#4598]
### Operating System Info

Windows 10

### OBS Studio Version

Git

### OBS Studio Log URL

https://obsproject.com/logs/oKtpnElkFTI9zYmI

### OBS Studio Crash Log URL

https://obsproject.com/logs/Yc6NLdbk1YJ69rA-

### Expected Behavior

Do not crash.

### Current Behavior

When applying the Noise Suppression filter to a Audio Input Capture source and trying to exit OBS, it crashes (and sometimes even corrupts your OBS data)

I'm not actually sure how to consistently corrupt your data, but it happened to me a few times while testing.

### Steps to Reproduce

1. Open OBS.
2. Create a Audio Input Capture source.
3. Apply the Noise Suppression filter.
4. Exit OBS.

### Anything else we should know?

I've used these Windows 64 artifacts: https://github.com/obsproject/obs-studio/actions/runs/783111394

**Comment by notr1ch** [comment]
Please try this commit: https://github.com/notr1ch/obs-studio/commit/4702b58bb7d5a4f6d7de44b5fbe5a87bf03684e7

**Comment by Vainock** [comment]
@notr1ch As I'm not able to build OBS, could you trigger a Multiplatform Build on your fork? (if even possible)

**Comment by notr1ch** [comment]
Unfortunately CI doesn't build the fork properly, you can try just replacing the plugin with this: [obs-filters.zip](https://github.com/obsproject/obs-studio/files/6372566/obs-filters.zip)

**Comment by Vainock** [comment]
Your patch seems to have fixed the issue. OBS no longer crashes.

**Comment by notr1ch** [comment]
Thanks for the feedback. Fixed in https://github.com/obsproject/obs-studio/commit/61964d519c45f5965aaa2d3222b4509b789941b2.
