### ISSUE TITLE
OBS点击停止推流不会停止

### ISSUE THREAD

**Issue by OG-C** [obsproject/obs-studio#4599]
### Operating System Info

Windows 10

### OBS Studio Version

26.1.1

### OBS Studio Log URL

21:39:30.139: CPU Name: Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz 21:39:30.139: CPU Speed: 2904MHz 21:39:30.139: Physical Cores: 6, Logical Cores: 6 21:39:30.139: Physical Memory: 16299MB Total, 5109MB Free 21:39:30.139: Windows Version: 10.0 Build 19042 (release: 2009; revision: 867; 64-bit) 21:39:30.139: Running as administrator: true 21:39:30.139: Aero is Enabled (Aero is always on for windows 8 and above) 21:39:30.139: Windows 10 Gaming Features: 21:39:30.140: 	Game DVR: On 21:39:30.224: Sec. Software Status: 21:39:30.229:  21:39:30.230:  21:39:30.231:  21:39:30.231:  21:39:30.241: Current Date/Time: 2021-04-12, 21:39:30 21:39:30.241: Browser Hardware Acceleration: true 21:39:30.241: Portable mode: false 21:39:30.708: OBS 26.1.1 (64-bit, windows) 21:39:30.708: --------------------------------- 21:39:30.709: --------------------------------- 21:39:30.709: audio settings reset: 21:39:30.709: 	samples per sec: 48000 21:39:30.709: 	speakers:        2 21:39:30.733: --------------------------------- 21:39:30.733

### Expected Behavior

点击“停止推流”按钮时，立即停止推流。
When you click the "Stop Push Streaming" button, the push stream will be stopped immediately.

### Current Behavior

点击“停止推流”按钮会变成“停止推流…”不会立即停止，甚至有时需要再次点击停止按钮。该故障在丢帧率变红时更容易复现。
Clicking the "Stop Streaming" button will change to "Stop Streaming..." and it will not stop immediately, and sometimes you need to click the Stop button again. This failure is easier to reproduce when the frame loss rate turns red.

### Steps to Reproduce

1.丢帧率变红时
2.点击“停止推流”

1. When the frame loss rate turns red
2. Click "Stop Push Stream"

### Anything else we should know?

由谷歌翻译
Translated by Google

**Comment by WizardCM** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
