### ISSUE TITLE
Client Area still showing in Windows Graphics Capture method

### ISSUE THREAD

**Issue by CoinAxe** [obsproject/obs-studio#4614]
### Operating System Info

Windows 10

### OBS Studio Version

26.1.1

### OBS Studio Log URL

NA

### Expected Behavior

The client area checkbox should work 

### Current Behavior

When having the capture method "Windows Graphics Capture" on.

The client area still shows even though its disabled.

### Steps to Reproduce

1. Add a windows capture
2. Choose "Windows Graphics Capture" as a capture method
3. Have Client area unchecked
4. The client area still shows

**Comment by Xaymar** [comment]
The "Client Area" option denotes whether you want to capture only the window content (checked) or the entire window (unchecked).

**Comment by CoinAxe** [comment]
What's showing is the yellow border

**Comment by dodgepong** [comment]
Is the yellow border actually being captured? or are you just concerned that the yellow border is appearing on your screen?

WGC does not yet provide us any way to disable the yellow border, though it should do so soon. "Client area" has nothing to do with the yellow border.

**Comment by CoinAxe** [comment]
I'm concerned about that yellow border, its really annoying

**Comment by dodgepong** [comment]
There's nothing we can do about that for now. Once the SDK is updated to allow us to remove it, we will make it an option.

**Comment by TimPietrusky** [comment]
@dodgepong I couldn't find any ticket where this is mentioned, so I put this in here: It seems that there is an option now to disable the yellow border: https://docs.microsoft.com/en-us/uwp/api/windows.graphics.capture.graphicscapturesession.isborderrequired?view=winrt-20348#Windows_Graphics_Capture_GraphicsCaptureSession_IsBorderRequired

If this is the wrong place, I will open a new ticket!

**Comment by RytoEX** [comment]
> 
> 
> @dodgepong I couldn't find any ticket where this is mentioned, so I put this in here: It seems that there is an option now to disable the yellow border: https://docs.microsoft.com/en-us/uwp/api/windows.graphics.capture.graphicscapturesession.isborderrequired?view=winrt-20348#Windows_Graphics_Capture_GraphicsCaptureSession_IsBorderRequired
> 
> If this is the wrong place, I will open a new ticket!

We're aware of that change.  No new GitHub Issue is required.

**Comment by Nikhil1O1** [comment]
> > @dodgepong I couldn't find any ticket where this is mentioned, so I put this in here: It seems that there is an option now to disable the yellow border: https://docs.microsoft.com/en-us/uwp/api/windows.graphics.capture.graphicscapturesession.isborderrequired?view=winrt-20348#Windows_Graphics_Capture_GraphicsCaptureSession_IsBorderRequired
> > If this is the wrong place, I will open a new ticket!
> 
> We're aware of that change. No new GitHub Issue is required.

So is it possible to disable the border right now in OBS?
I can't find a way to do so

**Comment by RytoEX** [comment]
> So is it possible to disable the border right now in OBS?
> I can't find a way to do so

You don't disable it in OBS.  You disable it in Windows via a setting that is currently only available in Windows 11.  If you are on Windows 11, you can find this setting under Settings > Privacy & security > Screenshot borders.
