### ISSUE TITLE
FFmpeg NVENC fallback occasionally ignores Key-Frame Interval and/or tags P-Frames as Key-Frames

### ISSUE THREAD

**Issue by Xaymar** [obsproject/obs-studio#4622]
### Operating System Info

Windows 10

### OBS Studio Version

26.1.1

### OBS Studio Log URL

N/A (already deleted as it was discovered too late)

### Expected Behavior

- FFmpeg fallback should be tagging only I-Frames as Key-Frames.
- Key-Frame Interval should not be ignored.

### Current Behavior

- FFmpeg fallback occasionally tags P-Frames as Key-Frames.
- Key-Frame Interval is occasionally ignored entirely.

### Steps to Reproduce

1. Change Recording Encoder to CQP, CQ 11, Keyframe Interval 1, Max Perforamnce, high
2. Change Color Format to I444
3. Start Replay Buffer and Save it every now and then. 
4. File may start being recorded with 250 frame KFI, instead of 1 second.
5. Occasionally, a P-Frame will be tagged as a Key-Frame. This occasionally happens, in a 1m59s footage, a single P-Frame was turned into a Key-Frame.

### Anything else we should know?

It appears [this function call](https://github.com/obsproject/obs-studio/blob/master/plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c#L467) is malfunctioning and tagging P-Frames as Key-Frames in the container, which results in weird decoding issues with FFmpeg. It only affected two replay buffer recordings out of the entire set.

Additionally it seems that replay buffer did not apply encoder settings as expected, so [this](https://github.com/obsproject/obs-studio/blob/master/plugins/obs-ffmpeg/obs-ffmpeg-nvenc.c#L268-L272) may have failed too.

**Comment by Xaymar** [comment]
![mpc-hc64_QPqVBlZGFv](https://user-images.githubusercontent.com/437395/116621019-e03d9500-a942-11eb-99aa-a1ef397d5619.png)

Above is an example of how this looks like when a player trusts the Container and starts decoding on a fake I-Frame.

**Comment by Xaymar** [comment]
Closing as requested.

**Comment by alinsavix** [comment]
@Xaymar  Was this fixed, or not actually a problem, or ... ?

**Comment by Xaymar** [comment]
@alinsavix The issue is not fixed, and still a rare problem.
