### ISSUE TITLE
Crash when stopping stream: text-freetype2.dll

### ISSUE THREAD

**Issue by salamanders** [obsproject/obs-studio#4623]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

26.0.2.1 (RPAN)

### OBS Studio Log URL

n/a

### OBS Studio Crash Log URL

n/a

### Expected Behavior

Not crash on end of stream.

### Current Behavior

Unhandled exception: c0000005
Date/Time: 2021-04-29, 19:26:08
Fault address: 7FF92A5E5A37 (c:\program files\rpan studio\obs-plugins\64bit\text-freetype2.dll)
libobs version: 26.0.2.1 (64-bit)
Windows version: 10.0 build 19042 (release: 2009; revision: 928; 64-bit)
CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz

### Steps to Reproduce

Exit the app
[obs_rpan_crash.log.txt](https://github.com/obsproject/obs-studio/files/6402795/obs_rpan_crash.log.txt)

**Comment by WizardCM** [comment]
We do not provide support for third party forks.
