### ISSUE TITLE
Data rate is labeled incorrectly.

### ISSUE THREAD

**Issue by icedterminal** [obsproject/obs-studio#4625]
### Operating System Info

Windows 10

### OBS Studio Version

26.1.2

### OBS Studio Log URL

n/a

### Expected Behavior

n/a

### Current Behavior

n/a

### Steps to Reproduce

n/a

### Anything else we should know?

Data Bitrates are using the [incorrect abbrevation](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/term-collections/bits-bytes-terms). This should be `KBps`, not `Kbps`.

- `Kbps` = Kilobits per second
- `KBps` = Kilobytes per second

If you were to follow the suggestions and know your abbrevations, one would think you need to enter `32,000 Kbps` to get the suggested `4,000 KBps` (4 Megabytes). `4,000 Kbps` is `500 KBps` (Half a Megabyte). I see confusion in terms of internet plans when users see it advertised in bits and not bytes. Once explained, they take that newly learned information, `b` vs `B`, and see OBS uses lower. Pile on confusion.

This something that has always tickled me. Would it be possible to use the correct abbreivation? Or add a tooltip? Just wanted to see what thoughts were. You can do what Twitch does and nullify confusion making it all lowercase, even though it's incorrect itself.

**Comment by WizardCM** [comment]
Kilobits per second is correct for streaming bitrate.

For reference, YouTube correctly uses Kbps

> Video Bitrate Range: 3,000-6,000 Kbps

[Source](https://support.google.com/youtube/answer/2853702?hl=en#zippy=%2Cp).

Facebook even mention that OBS bitrate is in Kbps.

> Note: OBS bitrate is in Kbps, so 10Mbps is 10,000 in OBS.

[Source](https://www.facebook.com/fbgaminghome/creators/best-practices#streamSettings).

**Comment by ElectronicWar** [comment]
To add: Internet connection speeds are typically advertised with Mbps (megabits per second) as well and not Megabyte/s.
So you do not need use much math to convert your internet upload speed to a suitable bitrate setting in OBS (only multiply or divide by 1000)

**Comment by derrod** [comment]
If we're being smartasses here then `kbps` is correct and `Kbps` is incorrect because the si-prefix for "kilo" is a lowercase "k".

**Comment by icedterminal** [comment]
> If we're being pedantic here then kbps is correct and Kbps is incorrect because the si-prefix for "kilo" is a lowercase "k". So the real fix would be to make the "k" lowercase in the OBS settings dialogues.

That's a good point. Twitch does this. https://stream.twitch.tv/encoding/

**Comment by infostud** [comment]
> There is also a de facto rule where lowercase k means 1024 and uppercase K means 1000, while lowercase b means bit and uppercase B means byte. So: Kbps = 1000 bits per second kB/s = 1024 bytes per second
> 
> The "correct" way to write it is to use KiB instead for the latter case, but urgh.

Uppercase K never means x1000. Lowercase k is alway x1000. [NIST The twenty prefixes](https://physics.nist.gov/cuu/Units/prefixes.html).
