### ISSUE TITLE
No Longer Able to Window Capture on Linux

### ISSUE THREAD

**Issue by sangoku116** [obsproject/obs-studio#4633]
### Operating System Info

Other

### Other OS

Arch Linux 

### OBS Studio Version

Git

### OBS Studio Log URL

https://obsproject.com/logs/M3Z0Pr-VbN-rW1PY

### Expected Behavior

Selecting a window capture and the window should show what is displayed in that window.

### Current Behavior

The capture is Black. 

### Steps to Reproduce

1. Launch OBS
2. Add a Window Capture
3. Select the Window
4. Observe the Black Preview
...

### Anything else we should know?

I am using XFCE. It was working fine before updating with the latest commits.

**Comment by WizardCM** [comment]
Could you bisect to track down which commit (if any) introduced the issue?

**Comment by sangoku116** [comment]
> Could you bisect to track down which commit (if any) introduced the issue?

It would be between 

Fri Apr 30 2021 20:21:54 GMT-0400 and now

**Comment by kkartaltepe** [comment]
Its more likely your graphics drivers broke us then.

**Comment by 26fiftysix** [comment]
Broken on mesa-git - https://gitlab.freedesktop.org/mesa/mesa/-/issues/4718.
obs-studio 26.1.2-2 crashes completely when trying to window capture.

black window on obs-studio 27.0.0.rc3.r1.gbd98e41ca:
```
02:00:41 AM.672: Switched to scene 'Scene 1'
02:00:41 AM.672: ------------------------------------------------
02:00:41 AM.672: Loaded scenes:
02:00:41 AM.672: - scene 'Scene 1':
02:00:41 AM.672:     - source: 'www' (xcomposite_input)
02:00:41 AM.672: ------------------------------------------------
02:00:42 AM.403: adding 42 milliseconds of audio buffering, total audio buffering is now 42 milliseconds (source: Desktop Audio)
02:00:42 AM.403:
02:00:46 AM.477: xcompcap: cleanup glXDestroyPixmap failed: BadPixmap (invalid Pixmap parameter)
02:00:46 AM.477: xcompcap: [window-capture: 'www'] update settings:
02:00:46 AM.477:        title: GitHub: Where the world builds software · GitHub — Mozilla Firefox
02:00:46 AM.477:        class: Navigator
02:00:46 AM.477:        Bit depth: 24
02:00:46 AM.477:        Found proper GLXFBConfig (in 368): yes
02:00:46 AM.477:
02:00:48 AM.043: ==== Shutting down ==================================================
02:00:48 AM.044: xcompcap: cleanup glXReleaseTexImageEXT failed: GLXBadContextTag
02:00:48 AM.045: pulse-input: Stopped recording from 'alsa_output.pci-0000_0c_00.1.output_hdmi-stereo-extra2.monitor'
02:00:48 AM.045: pulse-input: Got 290 packets with 296960 frames
02:00:48 AM.045: pulse-input: Stopped recording from 'alsa_input.usb-Elgato_Cam_Link_4K_000511C696000-03.input_analog-stereo'
02:00:48 AM.045: pulse-input: Got 289 packets with 295936 frames
02:00:48 AM.045: All scene data cleared
02:00:48 AM.045: ------------------------------------------------
```

**Comment by jph168** [comment]
> Broken on mesa-git - https://gitlab.freedesktop.org/mesa/mesa/-/issues/4718.
> obs-studio 26.1.2-2 crashes completely when trying to window capture.
> 
> black window on obs-studio 27.0.0.rc3.r1.gbd98e41ca:
> 
> ```
> 02:00:41 AM.672: Switched to scene 'Scene 1'
> 02:00:41 AM.672: ------------------------------------------------
> 02:00:41 AM.672: Loaded scenes:
> 02:00:41 AM.672: - scene 'Scene 1':
> 02:00:41 AM.672:     - source: 'www' (xcomposite_input)
> 02:00:41 AM.672: ------------------------------------------------
> 02:00:42 AM.403: adding 42 milliseconds of audio buffering, total audio buffering is now 42 milliseconds (source: Desktop Audio)
> 02:00:42 AM.403:
> 02:00:46 AM.477: xcompcap: cleanup glXDestroyPixmap failed: BadPixmap (invalid Pixmap parameter)
> 02:00:46 AM.477: xcompcap: [window-capture: 'www'] update settings:
> 02:00:46 AM.477:        title: GitHub: Where the world builds software · GitHub — Mozilla Firefox
> 02:00:46 AM.477:        class: Navigator
> 02:00:46 AM.477:        Bit depth: 24
> 02:00:46 AM.477:        Found proper GLXFBConfig (in 368): yes
> 02:00:46 AM.477:
> 02:00:48 AM.043: ==== Shutting down ==================================================
> 02:00:48 AM.044: xcompcap: cleanup glXReleaseTexImageEXT failed: GLXBadContextTag
> 02:00:48 AM.045: pulse-input: Stopped recording from 'alsa_output.pci-0000_0c_00.1.output_hdmi-stereo-extra2.monitor'
> 02:00:48 AM.045: pulse-input: Got 290 packets with 296960 frames
> 02:00:48 AM.045: pulse-input: Stopped recording from 'alsa_input.usb-Elgato_Cam_Link_4K_000511C696000-03.input_analog-stereo'
> 02:00:48 AM.045: pulse-input: Got 289 packets with 295936 frames
> 02:00:48 AM.045: All scene data cleared
> 02:00:48 AM.045: ------------------------------------------------
> ```

You'll want to comment that on my mesa gitlab report, thats a different GLX Extension that's broken for you.

**Comment by jph168** [comment]
Can we confirm this issue has been Resolved for the rest of you with the commit having been reverted in the latest mesa git so this issue can be closed? @sangoku116 @26fiftysix

**Comment by jph168** [comment]
Can we confirm this issue has been Resolved for the rest of you with the [commit](https://gitlab.freedesktop.org/mesa/mesa/-/commit/f5d6a1b916fb163ee72e6a6f356937b1fbac53e0) having been reverted in the latest mesa git so this issue can be closed? @sangoku116 @26fiftysix

**Comment by 26fiftysix** [comment]
> This issue is irrelevant to Obs Studio itself the [commit](https://gitlab.freedesktop.org/mesa/mesa/-/commit/f5d6a1b916fb163ee72e6a6f356937b1fbac53e0) that actually broke obs has been reverted in the latest mesa git so this issue can be closed.

Can confirm. OBS window capture is working again with the latest mesa-git.

**Comment by FabioSedia** [comment]
I crashed adding the new Xcomposite source, fixed updating to the latest mesa-tkg-git

**Comment by kkartaltepe** [comment]
Thanks for confirming the mesa issue is fixed.

**Comment by sangoku116** [comment]
Works on my end as well.
