### ISSUE TITLE
OBS 27 rc3 keeps  slowing down 

### ISSUE THREAD

**Issue by torment78** [obsproject/obs-studio#4640]
### Operating System Info

Windows 10

### Other OS

Win 10 20h2

### OBS Studio Version

27.0.0-rc3

### OBS Studio Log URL

https://obsproject.com/forum/threads/having-issues-with-crashing.143263/

### Expected Behavior

to work similer to 26 but with minor issues 

### Current Behavior

after running for about 40 min it stars lowering the in game on MW fps then starts lagging the stream then the stream crashes ,
and for some reason when tested with nvidia overlay it was working no flicker but with nv overlay it worked for shorter period and it did not slow down it just crashed obs /locked up
i had no issues with latest 26 
im running in 720 60 . 
with a nvidia 2080 
canvas at 1080 
but running game in 1440 and normaly no problem to run in 105 to 120 fps with obs open 
after 40 min it goes to 80 then lower and lower then at 55 it start afecting the stream then crash

### Steps to Reproduce

1.str4eam run for 40 min or more 
2.
3.
...

**Comment by WizardCM** [comment]
Unfortunately this report is too generic & unreproducible to be actionable. Please report to the #beta-testing Discord channel or the forum thread for the beta.

**Comment by torment78** [comment]
hey I linked a log that should give u my settings my 2080 asus turbo  gpu is clocked to 2050mhz
cpu running all core 4.8ghz i9 9900k
32gb ram @2666mhz
im going back to 26 but it felt to me like a memory leak or similer it was increasing very gradualy  
is there any other kind of log u want that might help .and  fyi there is no special prosedure to replicate the issue since did no difrent from 26 all settings the same all scenes the same so i u got nvidia 2080 and i9 9900k u should be able to replicate it i can send a user profile copy if u whant
