### ISSUE TITLE
Can't minimize to systemtray

### ISSUE THREAD

**Issue by Fma965** [obsproject/obs-studio#4643]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0-rc3

### OBS Studio Log URL

https://obsproject.com/logs/6IryalKiu4K0EJ2i

### Expected Behavior

OBS minimizes to the system tray.

### Current Behavior

OBS doesn't minimize to the system tray.

### Steps to Reproduce

1. enable the setting to minimize to tray
2. try to minimize.

### Anything else we should know?

![image](https://user-images.githubusercontent.com/1707290/116924506-de7c1600-ac4f-11eb-9904-115ca6bdcbdf.png)

On start-up it minimizes but it doesn't afterwards.

![image](https://user-images.githubusercontent.com/1707290/116924564-f05db900-ac4f-11eb-842c-3aeb9c07d955.png)

**Comment by RytoEX** [comment]
Works fine here for me.  I can't reproduce.

**Comment by Fma965** [comment]
Weirdly I rebooted my pc and now it works, so no idea what happened there. consider it a non issue
