### ISSUE TITLE
Wayland does not support QWindow::requestActivate()

### ISSUE THREAD

**Issue by mrepetto94** [obsproject/obs-studio#4645]
### Operating System Info

Other

### Other OS

Fedora 34

### OBS Studio Version

27.0.0-rc3

### OBS Studio Log URL

https://pastebin.com/3FWacGJv

### Expected Behavior

OBS opening

### Current Behavior

It crashes 

### Steps to Reproduce

1. Run OBS on a Wayland system

**Comment by Idiot64** [comment]
this is probably not your problem, since it says it too here, but it doesn't crash

your problem is probably something else

**Comment by WizardCM** [comment]
Agreed, the exact error you've mentioned is likely unrelated. Unfortunately the steps you've provided are too generic so I'm going to close this for now.
