### ISSUE TITLE
OBS stream disconnecting on its own bug

### ISSUE THREAD

**Issue by sora566** [obsproject/obs-studio#4646]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

27

### OBS Studio Log URL

n/a

### Expected Behavior

I always record my streams and at the end of stream, OBS version 27 stopped my stream on its own

### Current Behavior

OBS version 27 stopped my stream on its own without me doing anything

### Steps to Reproduce

1.i was ending my stream and then OBS stopped my stream on its own, i did not do anything

**Comment by notr1ch** [comment]
Please use the forums or Discord for support.
