### ISSUE TITLE
Can't stream Vulkan games using game capture (specifically Rainbow Six Siege and Detroit: Become Human)

### ISSUE THREAD

**Issue by AkalaGit** [obsproject/obs-studio#4653]
### Operating System Info

Windows 10

### OBS Studio Version

26.1.1

### OBS Studio Log URL

https://obsproject.com/logs/xLo52huy_4xWcYwk

### Expected Behavior

I expect Vulkan games to be detected by OBS.

### Current Behavior

Black screen. This has only been happening for a week so I'm not sure what changed.

### Steps to Reproduce

1. Open Rainbow Six Siege or Detroit: Become Human
2. Use Game Capture to capture either game
3.
...

### Anything else we should know?

Haven't had issues until last week. I'm pretty much always on the latest Windows version.

**Comment by RytoEX** [comment]
Since 26.1.1 has been working previously and we haven't shipped any out-of-band changes to Vulkan capture, we think this is related to a recent Windows update rather than anything we've changed.

**Comment by RytoEX** [comment]
Following up, as this is either an issue with a Windows Update or a support issue, I'm going to close this Issue.  Please use the forums or Discord for support.  Thank you for understanding.

https://obsproject.com/help

**Comment by AkalaGit** [comment]
Okay, thanks. Is there a specific Windows version that I should rollback to or would that not help?
