### ISSUE TITLE
There are so many graphic bugs on native wayland that I can't even use it

### ISSUE THREAD

**Issue by Toadfield** [obsproject/obs-studio#4654]
### Operating System Info

Other

### Other OS

Arch

### OBS Studio Version

26.1.2

### OBS Studio Log URL

How can I get the log?

### Expected Behavior

That it doesn't have graphic bugs

### Current Behavior

It looks like this:
![image](https://user-images.githubusercontent.com/68649672/117175558-473dcc80-adcf-11eb-9fdb-41955151f5bd.png)
And also,when I record something then it is just a black screen (Btw I can just select "XWAYLAND" as a video source,maybe that's the problem?).

### Steps to Reproduce

1.Install arch linux and kde and run it with wayland-session
2.Open obs native wayland

**Comment by tytan652** [comment]
OBS 26 does not support Wayland

**Comment by dodgepong** [comment]
Initial Wayland support will be in v27. See here for testing details: https://obsproject.com/forum/threads/obs-studio-27-release-candidate.141857/

**Comment by Toadfield** [comment]
Oh,then I mean that it doesn't work on xwayland.
So if I got you right you won't fix this for xwayland obs until you officially support native wayland?

**Comment by GeorgesStavracas** [comment]
There is a fix to Xwayland in queue for OBS Studio 27, an EGL renderer, which is what allows it to run as a native Wayland application in the first place.

**Comment by Toadfield** [comment]
When do you plan to release version 27?

**Comment by dodgepong** [comment]
Within the next few weeks, it's been undergoing an extensive testing process.
