### ISSUE TITLE
For debuging, Where to find the pdb file for avcodec-58.dll, avutil-56.dll and etc.

### ISSUE THREAD

**Issue by wly65535** [obsproject/obs-studio#4659]
### Operating System Info

Windows 10

### OBS Studio Version

26.0.0

### OBS Studio Log URL

http://none

### Expected Behavior

Where to find the pdb file for avcodec-58.dll, avutil-56.dll and etc

### Current Behavior

No pdb file

### Steps to Reproduce

1.
2.
3.
...

**Comment by WizardCM** [comment]
We do not use GitHub Issues for this kind of question.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
