### ISSUE TITLE
Pipewire Sources Drop A Significant Amount of Frames

### ISSUE THREAD

**Issue by myownfriend** [obsproject/obs-studio#4661]
### Operating System Info

Ubuntu 21.04

### OBS Studio Version

27.0.0-rc3

### OBS Studio Log URL

https://obsproject.com/logs/P08x26ka1h-NGbgQ

### Expected Behavior

Pipewire captures should be at full frame rate.

### Current Behavior

A significant amount of frames get dropped. The Stats panel shows 66% of frames dropped from rendering lag. The frame rate shows as 4-7fps but some frames will persist for more than a second. Even sources that don't update often will show only capture at ~45 fps. Whatever is happening also effects the smoothness of Gnome animations.

Other types of sources were tried and only Pipewire sources cause these drops.

### Steps to Reproduce

1. Add a PipeWire capture source, either Screen Capture or Window Capture
2. That's it.

**Comment by kkartaltepe** [comment]
virtual graphics cards are not supported and you should not be surprised that performance is awful with them.

**Comment by myownfriend** [comment]
> software rendering is not supported and you should not be surprised that performance is awful with it.

Software rendering? I have a GTX 1070.

**Comment by GeorgesStavracas** [comment]
To be clear: the problem here is that NVidia doesn't implement the APIs required by Wayland screensharing to work. Your best bet is somehow pressure NVidia to stop being such a bad actor when it comes to Linux.

**Comment by myownfriend** [comment]
> To be clear: the problem here is that NVidia doesn't implement the APIs required by Wayland screensharing to work. Your best bet is somehow pressure NVidia to stop being such a bad actor when it comes to Linux.

I'm guessing this has to do with DMA-Buf support? If so then I'll just have to wait until the 470.xx drivers.

**Comment by GeorgesStavracas** [comment]
DMA-BUF sharing, yes, and also GBM. Besides waiting for the 470 driver, you might be interested in keeping an eye on [this merge request against libgbm](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/9902).

**Comment by myownfriend** [comment]
Oh, Pipewire relies on both? Damn. I've been following that MR and I'm hopeful that the relatively small amount of code that it's made up of means that it won't take too long before it's merged.
