### ISSUE TITLE
[BUG]Window capture on macOS only supports 30 fps

### ISSUE THREAD

**Issue by AkinoYuiko** [obsproject/obs-studio#4662]
### Operating System Info

macOS 11.3

### OBS Studio Version

27.0.0-rc3

### OBS Studio Log URL

no crash

### OBS Studio Crash Log URL

no crash

### Expected Behavior

Should it support 60 fps or higher?

### Current Behavior

When using "window capture" to capture a gameplay, the record looks just like a 30-fps video, even the record is set to 60 fps. I use Apple VT Encoder, and it looks normal in "monitor capture".

### Steps to Reproduce

1. Set video frame to 60.
2. Create a window capture and record any window that is 60 fps or higher.
3. Use monitor capture and do the same work.
4.  Compare the two records with your eyes.
...

**Comment by asher-the-thrasher** [comment]
1) Because of how OBS has to capture sources on MacOS, display capture is known to have better performance than window capture. 
2) Please use the forums or Discord for support next time.

**Comment by PatTheMav** [comment]
Window capture is essentially taking a screenshot of a window on a timer, then creating a texture from that image which requires copying data from RAM to VRAM, applying colourspace transformation, etc. - it's a costly process that becomes slower the bigger the window area is and is thus decoupled from the capture frame rate.

We have filed a feedback to Apple on that front to make them aware of the need for a fast Window Capture API but that's an ongoing process.
