### ISSUE TITLE
Resizing OBS window causes dock layout to shift

### ISSUE THREAD

**Issue by funguscolander** [obsproject/obs-studio#4666]
### Operating System Info

Windows 10

### OBS Studio Version

26.1.1

### OBS Studio Log URL

https://obsproject.com/logs/e9ACUfyUkd8HL_j-

### Expected Behavior

When the window changed from maximised to windowed and then returned to maximised, the layout should stay the same.

### Current Behavior

The dock layout reverts to a different layout upon every resize.

[Youtube video showing behaviour](https://www.youtube.com/watch?v=IvXkn2UQkUQ) (25 seconds).

### Steps to Reproduce

1. Change the size of some dock elements.
2. Change the size of the window or unmaximise and remaximise it.

### Anything else we should know?

#2949 describes a similar issue upon closing and reopening OBS. User [skeletonbow](https://github.com/obsproject/obs-studio/issues/2949#issuecomment-683703203) suggested that this could be caused by the minimum size of dock elements overriding the set values. These issues may be caused by the same reason, and if this is the case then a solution similar to [WizardCM's](https://github.com/obsproject/obs-studio/issues/2949#issuecomment-762822888_) (below) about saving the dock state may help. The dock state could be saved after any dock element resizing is done and then referenced any time window resizing is done.

> So based on what others have said, and the code I've looked at, there are two potential theories:
> 
> 1. When initialising, certain docks have a minimum size that's different to their defined minimum size
> 2. (this one's my own) dock positions aren't being saved properly, but it's not related to OAuth dock saving
> 
> If it's 2, then performing this task sooner during shutdown might help:
> https://github.com/obsproject/obs-studio/blob/54207a0d6032e507801c96f69731c3a5a39543da/UI/window-basic-main.cpp#L4294-L4295
> 
> If it's 1, we might need to do more specific tests to see if everyone is able to reproduce it the same way. That is, we need to put together reproduction steps using specific built-in docks in a certain layout & window size.
> 
> _Originally posted by @WizardCM in https://github.com/obsproject/obs-studio/issues/2949#issuecomment-762822888_

**Comment by Fenrirthviti** [comment]
This is a quirk of how Qt works, so there is unfortunately not much we can do without breaking other things in the UI.
