### ISSUE TITLE
hevc_amf under ffmpeg mislabeled as nvenc

### ISSUE THREAD

**Issue by felix920506** [obsproject/obs-studio#4671]
### Operating System Info

Windows 10

### OBS Studio Version

26.1.1

### OBS Studio Log URL

not applicable

### Expected Behavior

I just thought it was strange that nvenc and amf were in the same encoder option

### Current Behavior

![image](https://user-images.githubusercontent.com/25688628/117531186-e9e68d00-b013-11eb-9eb2-11c09247e003.png)
It says AMF at the beginning and NVENC at the end
when I ran it the encoder it used was AMF

### Steps to Reproduce

1.Open Settings
2.Select Output
3.Select Recording
4.change type to ffmpeg
5.open the encoder dropdown menu
...

**Comment by gxalpha** [comment]
As far as we can tell, we're showing and using exactly the names libavcodec (FFmpeg) gives us. If these turn out to be wrong, there's pretty much nothing we can do about it. In Custom FFmpeg Output, you're pretty much on your own.

However, as of OBS 28.1 both NVENC and AMF have native HEVC support in OBS, so if you're goal was to record in HEVC I'd recommend checking out Simple Mode (or non-custom Advanced Mode).
