### ISSUE TITLE
Using arrow keys to move content doesn't work in group

### ISSUE THREAD

**Issue by Josh-65** [obsproject/obs-studio#4674]
### Operating System Info

Windows 10

### OBS Studio Version

26.1.1

### OBS Studio Log URL

not a crash

### OBS Studio Crash Log URL

not a crash

### Expected Behavior

When clicking on the content in a group on the preview it should select that as active rather then selecting the group transform. I cant use the arrow key for fine positioning because of this. What makes it worse is that it cant click the source on the sources page because that will then make it change the selected source in the list.

### Current Behavior

Currently it will just select the group transform and clicking again will go to the sources behind it.

### Steps to Reproduce

1. Add a source to a group
2. Try click on that source
3. See that it will just select the group rather than source
4. Click multiple time on it
5. See that it selects what's behind it

**Comment by gxalpha** [comment]
This is intentional. Clicking in the preview is meant to select the group, not the items within it (it's kind of what groups are for). If you need to select the individual items, you can always expand the group in the sources dock and select them there.

**Comment by Josh-65** [comment]
That still doesn't work because it changes the source selected rather then moving it.

**Comment by RytoEX** [comment]
> That still doesn't work because it changes the source selected rather then moving it.

This is a bit janky, but this works:
1. Click sceneitem in Sources list.
2. Click *and drag and drop* the item in the Preview.
3. Use arrow keys for fine adjustments.
