### ISSUE TITLE
Right click should not switch to the scene

### ISSUE THREAD

**Issue by josh-65** [obsproject/obs-studio#4675]
### Operating System Info

Windows 10

### OBS Studio Version

26.1.1

### OBS Studio Log URL

not a crash

### OBS Studio Crash Log URL

not a crash

### Expected Behavior

When i right click it should not switch to that scene and just show right click options

### Current Behavior

It will switch and show right click options

### Steps to Reproduce

^

**Comment by WizardCM** [comment]
I have previously looked into fixing this bug, but this is just how the list is designed on Qt's side. I don't think it's something we can fix without completely replacing the functionality of the list.

The current workaround is to enable Studio Mode.

**Comment by RytoEX** [comment]
> 
> 
> I have previously looked into fixing this bug, but this is just how the list is designed on Qt's side. I don't think it's something we can fix without completely replacing the functionality of the list.
> 
> The current workaround is to enable Studio Mode.

I suspect we could change this by overriding `mousePressEvent` to emit a context menu without selecting the scene or listening for the `QListWidget::itemClicked` signal and trying the same.  However, I also suspect that there are assumptions in the UI code that expect context menu actions to be taken on the _selected_ item.

For what it's worth, I've observed different behavior in different applications for this.  Discord, Firefox, Chrome, Opera, and Steam do not activate or switch to right-clicked items (tabs, servers, channels, games).  Windows Explorer, Notepad++, Excel, Google Sheets, and Photoshop activate or switch to right-clicked items - this is also Qt's default behavior.

I'm in favor of closing this.  I don't think it's a bug.  It's working as designed.  Requesting different behavior is a feature request.

**Comment by josh-65** [comment]
Il make this a feature request now
https://ideas.obsproject.com/posts/1476/right-click-should-not-switch-to-the-scene
