### ISSUE TITLE
Importing external scenes cause naming issue

### ISSUE THREAD

**Issue by josh-65** [obsproject/obs-studio#4676]
### Operating System Info

Windows 10

### OBS Studio Version

26.1.1

### OBS Studio Log URL

not a crash

### Expected Behavior

When I import some scene and sources from Streamlabs it create them with a number in brackets. It should not have those and should let me rename it without issue since there is no duplicates.

### Current Behavior

When I try renaming it to normal it say that name already exists.

### Steps to Reproduce

^

### Anything else we should know?

I tried removing (1) from starting soon(1)
![image](https://user-images.githubusercontent.com/26977075/117556721-d400b880-b063-11eb-93ff-2993c31a4c60.png)

**Comment by WizardCM** [comment]
Scenes and sources cannot share a name. You have an Image Slide Show with the same name, therefore the Scene cannot have that name. This is by design.

**Comment by josh-65** [comment]
Why though it doesn't make much sense to me for this to be need especial when streamlabs doesn't have this requirement.

**Comment by notr1ch** [comment]
OBS allows 3rd party plugins which use libobs APIs, one of the functions returns a source by name. If sources had duplicate names this would not function correctly.
