### ISSUE TITLE
cannot start in windows 10

### ISSUE THREAD

**Issue by fanshengshuai** [obsproject/obs-studio#4683]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0-rc3

### OBS Studio Log URL

no logs

### OBS Studio Crash Log URL

no logs

### Expected Behavior

cannot start.  
this is the windows application error log:

错误应用程序名称: obs64.exe，版本: 27.0.0.0，时间戳: 0x608e4e49
错误模块名称: ntdll.dll，版本: 10.0.19041.844，时间戳: 0x60a6ca36
异常代码: 0xc0000005
错误偏移量: 0x0000000000048f39
错误进程 ID: 0x43b8
错误应用程序启动时间: 0x01d745fa727dbcb8
错误应用程序路径: D:\Program Files\obs-studio\bin\64bit\obs64.exe
错误模块路径: C:\Windows\SYSTEM32\ntdll.dll
报告 ID: 4e928ec8-ec12-4d5d-b54d-efbdf469fa70
错误程序包全名: 
错误程序包相对应用程序 ID: 

日志名称:          Application
来源:            Application Error
日期:            2021/5/11 8:13:20
事件 ID:         1000
任务类别:          (100)
级别:            错误
关键字:           经典
用户:            暂缺
计算机:           DESKTOP-Q7NDJH6
描述:
错误应用程序名称: obs64.exe，版本: 27.0.0.0，时间戳: 0x608e4e49
错误模块名称: ntdll.dll，版本: 10.0.19041.844，时间戳: 0x60a6ca36
异常代码: 0xc0000005
错误偏移量: 0x0000000000048f39
错误进程 ID: 0x43b8
错误应用程序启动时间: 0x01d745fa727dbcb8
错误应用程序路径: D:\Program Files\obs-studio\bin\64bit\obs64.exe
错误模块路径: C:\Windows\SYSTEM32\ntdll.dll
报告 ID: 4e928ec8-ec12-4d5d-b54d-efbdf469fa70
错误程序包全名: 
错误程序包相对应用程序 ID: 
事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-05-11T00:13:20.3897731Z" />
    <EventRecordID>11599</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>DESKTOP-Q7NDJH6</Computer>
    <Security />
  </System>
  <EventData>
    <Data>obs64.exe</Data>
    <Data>27.0.0.0</Data>
    <Data>608e4e49</Data>
    <Data>ntdll.dll</Data>
    <Data>10.0.19041.844</Data>
    <Data>60a6ca36</Data>
    <Data>c0000005</Data>
    <Data>0000000000048f39</Data>
    <Data>43b8</Data>
    <Data>01d745fa727dbcb8</Data>
    <Data>D:\Program Files\obs-studio\bin\64bit\obs64.exe</Data>
    <Data>C:\Windows\SYSTEM32\ntdll.dll</Data>
    <Data>4e928ec8-ec12-4d5d-b54d-efbdf469fa70</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

### Current Behavior

every time

### Steps to Reproduce

1. every time when i click the icon from desktop
2.
3.
...

**Comment by WizardCM** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
