### ISSUE TITLE
crash on recorded application crash

### ISSUE THREAD

**Issue by mcDandy** [obsproject/obs-studio#4685]
### Operating System Info

Windows 10

### OBS Studio Version

26.1.1

### OBS Studio Log URL

when trying to upload I get empty error box, uploading as file

### OBS Studio Crash Log URL

https://obsproject.com/logs/VSsFDMVNgu8SAAaY

### Expected Behavior

not  crash

### Current Behavior

crashed on chrome hang

### Steps to Reproduce

1. be on second latest dev branch of windows (21370.1) - exact version probably does not matter
2. record chrome (or any application)
3. crash application (closing might also work)
4. obs crashed
...

### Anything else we should know?

[2021-05-11 09-12-49.txt](https://github.com/obsproject/obs-studio/files/6457644/2021-05-11.09-12-49.txt)

**Comment by RytoEX** [comment]
```
Unhandled exception: 80000003
```
```
09:12:49.216: Physical Memory: 16230MB Total, 1265MB Free
```

This is an out of memory crash. The system being out of memory is causing the applications to crash.
