### ISSUE TITLE
Radeon Software 21.4.1+ AVC/HEVC Failed to start recording

### ISSUE THREAD

**Issue by Neoony** [obsproject/obs-studio#4689]
### Operating System Info

Windows 10

### OBS Studio Version

26.1.1

### OBS Studio Log URL

https://pastebin.com/SpsJmQjH

### Expected Behavior

Should be able to record with AVC/HEVC

### Current Behavior

Ever since AMD Radeon software / drivers update 21.4.1 
I am getting following error when I start recording with AVC/HEVC codec:
![](https://i.imgur.com/EXZJxzY.png)

Settings:
![](https://i.imgur.com/Zq9pNoK.png)
![](https://i.imgur.com/E7xGK0m.png)

I also tried updating drivers to 21.5.1, but still same problem
And I also tried installing OBS 27.0.0-rc3, but still same problem

AMD Ryzen 1800x CPU
Radeon VII GPU
4x 8GB 3200MHz RAM

### Steps to Reproduce

1. Start OBS with AMD drivers 21.4.1 or higher
2. Select AVC or HEVC codec
3. Start Recording
4. Error appears

### Anything else we should know?

Not sure whether AMD messed something up, but there were many changes also to the Relive recording.
Or OBS just needs to update something that AMD changed?

Also not sure if I am the only one getting this problem with new drivers.

**Comment by WizardCM** [comment]
Sounds like a driver issue.

> [AMF] <Id: 1> Unable to set converter transfer characteristic, error AMF_NOT_FOUND (code 11)

I don't know AMF well enough to know for sure though.

**Comment by Neoony** [comment]
I also sent a bug report to AMD over Radeon Software and pointed to this thread

**Comment by Neoony** [comment]
hmm I guess this guy has same issue
https://obsproject.com/forum/threads/amd-encoder-stopped-working-starting-output-failed.143208/

**Comment by Lithium64** [comment]
Same bug here, can't record or stream with AMF on driver 21.5.2

**Comment by Lithium64** [comment]
AMD ended R7 260X support and don't fixed it, shame.

**Comment by dumpsters** [comment]
Same issue on my R7 260X with latest drivers. Shame on AMD.

**Comment by Neoony** [comment]
> 
> 
> Same issue on my R7 260X with latest drivers. Shame on AMD.

Its probably more about the fact that there is barely any support for AMD with OBS
Nobody to update to whatever change AMD made

**Comment by dumpsters** [comment]
> 
> 
> > Same issue on my R7 260X with latest drivers. Shame on AMD.
> 
> Its probably more about the fact that there is barely any support for AMD with OBS
> Nobody to update to whatever change AMD made

Not even ReLive works

**Comment by Neoony** [comment]
For me I could record with ReLive fine with newest drivers [Radeon VII]
But for a while I cant record audio with ReLive (a while before this issue)
I also use modded audio drivers though (which worked fine before) [AAF Optimus Universal Sound]

**Comment by Neoony** [comment]
Ok, so I went to discord to ask and Jessica | tielqt suggested to DDU and install new drivers again.
Although I tried that with drivers before 21.6.2

But this time with 21.6.2 it helped.

DDU in safe mode and restart
then installed newest chipset drivers 2.17.25.506 (X370)
then installed newest AMD drivers 21.6.2
Restarted

And now I get no error with OBS anymore

so for me with Radeon VII, its resolved.

**Comment by Shahed0631j** [comment]
I am using Intel pentium g4400 with 8gb ddr4 ram amd asus h110mk motherboard, 120 GB transcend ssd
recently I've added asus r7 360 oc 2gb ddr5 v2 graphics card ,
I had installed amd driver adrenalin-2020-21.5.2 , in obs it shows h254/AVF,,, but when I select and try to record or stream it says
'starting the output failed. please check the log for more details '
and in the log it says
"Unable to initialize converter, error AMF_OPENCL_FAILED (code 19)"
please please please please please please please please please please please please please please please please please please please please please please please please please help me
[2021-09-29 13-37-32.txt](https://github.com/obsproject/obs-studio/files/7249777/2021-09-29.13-37-32.txt)

**Comment by Neoony** [comment]
I guess you are screwed with that one as AMD dropped support (no new drivers)

Any chance it works with older driver?
like 21.3.2?

https://www.amd.com/en/support/previous-drivers/graphics/amd-radeon-r7-series/amd-radeon-r7-300-series/amd-radeon-r7-360

**Comment by Shahed0631j** [comment]
Thanks for responding! I am really too upset about this. I will try your
suggestion.

**Comment by Shahed0631j** [comment]
thankssssssssssssss a lot Thank you Thank you  Thank you Thank you  Thank
you Thank you  Thank you Thank you  Thank you Thank you  Thank you Thank
you  Thank you Thank you  Thank you Thank you  Thank you Thank you  Thank
you Thank you  Thank you Thank you  Thank you Thank you  Thank you Thank
you  Thank you Thank you  Thank you Thank you  Thank you Thank you  Thank
you Thank you  Thank you Thank you  Thank you Thank you  Thank you Thank
you  Thank you Thank you  Thank you Thank you  Thank you Thank you  Thank
you Thank you  Thank you Thank you  Thank you Thank you  Thank you Thank
you  Thank you Thank you Thank you Thank you  Thank you Thank you  Thank
you Thank you  Thank you Thank you  Thank you Thank you  Thank you Thank
you  Thank you Thank you  Thank you Thank you  Thank you Thank you  Thank
you Thank you  Thank you Thank you  Thank you Thank you  Thank you Thank
you  Thank you Thank you Thank you Thank you  Thank you Thank you  Thank
you Thank you  Thank you Thank you  Thank you Thank you  Thank you Thank
you  Thank you Thank you  Thank you Thank you  Thank you Thank you  Thank
you Thank you  Thank you Thank you  Thank you Thank you  Thank you Thank
you  Thank you Thank you Thank you Thank you  Thank you Thank you  Thank
you Thank you  Thank you Thank you  Thank you Thank you  Thank you Thank
you  Thank you Thank you  Thank you Thank you  Thank you Thank you  Thank
you Thank you  Thank you Thank you  Thank you Thank you  Thank you Thank
you  Thank you Thank you Thank you Thank you  Thank you Thank you  Thank
you Thank you  Thank you Thank you  Thank you Thank you  Thank you Thank
you  Thank you Thank you  Thank you Thank you  Thank you Thank you  Thank
you Thank you  Thank you Thank you  Thank you Thank you  Thank you Thank
you  Thank you Thank you Thank you Thank you  Thank you Thank you  Thank
you Thank you  Thank you Thank you  Thank you Thank you  Thank you Thank
you  Thank you Thank you  Thank you Thank you  Thank you Thank you  Thank
you Thank you  Thank you Thank you  Thank you Thank you  Thank you Thank
you  Thank you Thank you Thank you Thank you  Thank you Thank you  Thank
you Thank you  Thank you Thank you  Thank you Thank you  Thank you Thank
you  Thank you Thank you  Thank you Thank you  Thank you Thank you  Thank
you Thank you  Thank you Thank you  Thank you Thank you  Thank you Thank
you  Thank you Thank you Thank you Thank you  Thank you Thank you  Thank
you Thank you  Thank you Thank you  Thank you Thank you  Thank you Thank
you  Thank you Thank you  Thank you Thank you  Thank you Thank you  Thank
you Thank you  Thank you Thank you  Thank you Thank you  Thank you Thank
you  Thank you Thank you Thank you Thank you  Thank you Thank you  Thank
you Thank you  Thank you Thank you  Thank you Thank you  Thank you Thank
you  Thank you Thank you  Thank you Thank you  Thank you Thank you  Thank
you Thank you  Thank you Thank you  Thank you Thank you  Thank you Thank
you  Thank you Thank you Thank you Thank you  Thank you Thank you  Thank
you Thank you  Thank you Thank you  Thank you Thank you  Thank you Thank
you  Thank you Thank you  Thank you Thank you  Thank you Thank you  Thank
you Thank you  Thank you Thank you  Thank you Thank you  Thank you Thank
you  Thank you Thank you Thank you Thank you  Thank you Thank you  Thank
you Thank you  Thank you Thank you  Thank you Thank you  Thank you Thank
you  Thank you Thank you  Thank you Thank you  Thank you Thank you  Thank
you Thank you  Thank you Thank you  Thank you Thank you  Thank you Thank
you  Thank you Thank you Thank you Thank you  Thank you Thank you  Thank
you Thank you  Thank you Thank you  Thank you Thank you  Thank you Thank
you  Thank you Thank you  Thank you Thank you  Thank you Thank you  Thank
you Thank you  Thank you Thank you  Thank you Thank you  Thank you Thank
you  Thank you Thank you Thank you Thank you  Thank you Thank you  Thank
you Thank you  Thank you Thank you  Thank you Thank you  Thank you Thank
you  Thank you Thank you  Thank you Thank you  Thank you Thank you  Thank
you Thank you  Thank you Thank you  Thank you Thank you  Thank you Thank
you  Thank you Thank you Thank you Thank you  Thank you Thank you  Thank
you Thank you  Thank you Thank you  Thank you Thank you  Thank you Thank
you  Thank you Thank you  Thank you Thank you  Thank you Thank you  Thank
you Thank you  Thank you Thank you  Thank you Thank you  Thank you Thank
you  Thank you Thank you Thank you Thank you  Thank you Thank you  Thank
you Thank you  Thank you Thank you  Thank you Thank you  Thank you Thank
you  Thank you Thank you  Thank you Thank you  Thank you Thank you  Thank
you Thank you  Thank you Thank you  Thank you Thank you  Thank you Thank
you  Thank you Thank you Thank you Thank you  Thank you Thank you  Thank
you Thank you  Thank you Thank you  Thank you Thank you  Thank you Thank
you  Thank you Thank you  Thank you Thank you  Thank you Thank you  Thank
you Thank you  Thank you Thank you  Thank you Thank you  Thank you Thank
you  Thank you Thank you

**Comment by Shahed0631j** [comment]
You don't knock how much happy i am right now
May God bless you
