### ISSUE TITLE
OBS build from source - running virtualcam-install.bat fails on 32bit (64bit OK) but zoom doesnt show OBS virtual cam

### ISSUE THREAD

**Issue by asie-collab** [obsproject/obs-studio#4698]
### Operating System Info

Windows 10

### OBS Studio Version

26.1.2

### OBS Studio Log URL

xxx

### Expected Behavior

Zoom to show OBS virtual cam as an option in the video camera selection

### Current Behavior

Zoom doesnt show an option for OBS virtual cam

### Steps to Reproduce

Cmake was configured with Virtual Cam GUID
Build for 64 bit is OK
Had to modify virtualcam-install.bat to avoid 32 bit (as i dont have a build for it)
Run the modified 
[virtualcam-install.txt](https://github.com/obsproject/obs-studio/files/6473121/virtualcam-install.txt)
virtualcam-install.bat

I got OK on 64bit and failure on 32Bit as expected 
App shows "Start virtual camera" in control dock

Open zoom - doesnt show virtual camera

[virtualcam-install.txt](https://github.com/obsproject/obs-studio/files/6473136/virtualcam-install.txt)

### Anything else we should know?

If i install standard OBS, then ZOOM identify it and the virtual cam from my app works

How can i make it without installing standard OBS ?

**Comment by RytoEX** [comment]
Zoom may require the 32-bit virtual camera DLL.  Try building both 32-bit and 64-bit builds, and then copy the 32-bit virtual camera file (`data\obs-plugins\win-dshow\obs-virtualcam-module32.dll`) into the 64-bit build before running the install script.

Additionally, GitHub Issues is for verified bug reports, not developer support.  Please use the forums or Discord for developer support.  Thank you for understanding.

https://obsproject.com/help
