### ISSUE TITLE
OBS will freeze and need to be killed 3 out of 5 times when launched and then exited immediately

### ISSUE THREAD

**Issue by lcalder** [obsproject/obs-studio#4706]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0-rc3

### OBS Studio Log URL

https://github.com/obsproject/obs-studio/files/6477648/2021-05-14.01-27-32.txt

### Expected Behavior

I launched OBS and then immediately click on the X to exit the application. I expected it to close normally.
I've also included a crash which occurred upon closing I believe which may or may not be related in case it helps.

### Current Behavior

Approximately every 2 out of 5 tries OBS exited without hanging. But 3 out of 5 tries it hung and needed to be killed.
[2021-05-14 01-27-32.txt](https://github.com/obsproject/obs-studio/files/6477648/2021-05-14.01-27-32.txt)
[2021-05-13 22-00-51.txt](https://github.com/obsproject/obs-studio/files/6477651/2021-05-13.22-00-51.txt)

Recent crash log which may be related included below in case it is of help...
[Crash 2021-05-12 16-14-08.txt](https://github.com/obsproject/obs-studio/files/6477670/Crash.2021-05-12.16-14-08.txt)

### Steps to Reproduce

1.Launch OBS
2.Exit OBS
3.
...

**Comment by tt2468** [comment]
Can you try uninstalling obs-websocket and seeing if the crash goes away? I see that it is loaded and it's a similar crashlog to what I've seen obs-websocket induce.

**Comment by RytoEX** [comment]
The Move Transition plugin is in the stack of the crashing thread.  @exeldro

**Comment by WizardCM** [comment]
There is a known hang on Windows if you try and close OBS too quickly on startup while it's trying to initialise CEF. Currently this is expected behaviour & low priority because in most cases it shouldn't happen, and in the cases where it does happen the user can just kill the process.

**Comment by RytoEX** [comment]
> 
> 
> There is a known hang on Windows if you try and close OBS too quickly on startup while it's trying to initialise CEF. Currently this is expected behaviour & low priority because in most cases it shouldn't happen, and in the cases where it does happen the user can just kill the process.

While I did get that CEF crash myself trying to reproduce this, the OP's crash log doesn't have CEF in the crashing thread.  That crash log looks like it could be a separate mutex issue.  It's possible that they are experiencing two different issues.

**Comment by RytoEX** [comment]
I'm reasonably certain this has been solved, if not by changes in our shutdown process, then by bug fixes in the Move Transition plugin. If you are still experiencing this in OBS Studio 28.1.2 (or newer) with the most recent release of the Move Transition plugin, please comment with new logs, and we can consider whether or not to reopen this issue or open a new issue.
