### ISSUE TITLE
error during build step: bundle app

### ISSUE THREAD

**Issue by oalotfy** [obsproject/obs-studio#4708]
### Operating System Info

macOS 11.3

### OBS Studio Version

Other

### OBS Studio Version (Other)

building app

### OBS Studio Log URL

(no URL)

### Expected Behavior

The OBS app to be built on my macOS.

### Current Behavior

**Error on the bottom**
<img width="1440" alt="Screen Shot 2021-05-15 at 1 08 04 PM" src="https://user-images.githubusercontent.com/58657919/118356618-cde86b80-b57e-11eb-9a99-fd69829ac22d.png">

### Steps to Reproduce

1. install homebrew
2. git clone --recursive https://github.com/obsproject/obs-studio.git
2. ./CI/full-build-macos.sh
3. ./CI/full-build-macos.sh -b (step where issue happened)
...

### Anything else we should know?

I can't mount the OBS dmg on my mac (long story)

**Comment by gxalpha** [comment]
This looks like scripting isn't enabled, make sure to install both lua and python and enable scripting.
In the future, the #developement channel on the discord is probably a better place to ask
https://obsproject.com/discord

**Comment by oalotfy** [comment]
> This looks like scripting isn't enabled or working properly, make sure to install both lua and python and enable scripting.
> In the future, the #developement channel on the discord is probably a better place to ask
> https://obsproject.com/discord

Thanks for the response! I will try the fix you recommended and will pop over to the discord to ask, thanks!
