### ISSUE TITLE
Mouse cursor is a black square when adding a filter to Pipewire capture source

### ISSUE THREAD

**Issue by richieloro** [obsproject/obs-studio#4711]
### Operating System Info

Other

### Other OS

Fedora 34

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.0.0 rc2 (latest version on Fedora RPM Fusion

### OBS Studio Log URL
https://obsproject.com/logs/q73zC6pFT2vTQ5Cl

### Expected Behavior

Mouse cursor is a faithful representation of the actual desktop.

### Current Behavior

Mouse cursor is a black square !

### Steps to Reproduce

Just record your screen in Fedora 34 (Gnome 40, Wayland, Pipewire).
It is **visible** in the **preview in OBS**, but also on the recorded screen capture **video**.

### Anything else we should know?

![Screenshot from 2021-05-16 13-12-07](https://user-images.githubusercontent.com/81038208/118395204-56334300-b649-11eb-9a58-101dca83ed22.png)
![Screenshot from 2021-05-16 18-25-44](https://user-images.githubusercontent.com/81038208/118404679-37967180-b674-11eb-885a-e9a9460c2da8.png)

**Comment by GeorgesStavracas** [comment]
Interesting. Seems like you tested it with RC4 and it's fixed? If not, you can try the Flathub Beta's build of OBS Studio, which currently is 27 RC4:

```
$ flatpak install --user https://flathub.org/beta-repo/appstream/com.obsproject.Studio.flatpakref
```

Let me know if you can confirm it's fixed or not.

**Comment by GeorgesStavracas** [comment]
Yay \o/

Thank you! I guess we can close this issue then :slightly_smiling_face:

**Comment by richieloro** [comment]
Hi guys. It needs reopening !!!
**When I add a crop filter**, the mouse is back to a black square !
![Screenshot from 2021-05-18 15-22-24](https://user-images.githubusercontent.com/81038208/118658705-ecec3500-b7ec-11eb-849d-502684cb3fea.png)

**Comment by GeorgesStavracas** [comment]
27 RC5 is out, and is available on Flathub Beta, can you please try that?

**Comment by richieloro** [comment]
I will try but it has something to do with the crop, if I don't crop the mouse is fine.
I used `flatpak update` I have the RC5 now. Same thing a black cursor.
IF I REMOVE THE CROP/PAD filter it good again.

With the **Crop/pad** filter :
![Screenshot from 2021-05-18 17-52-09](https://user-images.githubusercontent.com/81038208/118683612-d0a6c300-b801-11eb-98ab-76231d848906.png)

Without :
![Screenshot from 2021-05-18 17-54-43](https://user-images.githubusercontent.com/81038208/118684039-2a0ef200-b802-11eb-8a13-d6ebb50ee24a.png)

**Comment by RytoEX** [comment]
Does this also happen if you apply a Crop/Pad filter to another source, like "Screen Capture (XHSM)" or Window Capture?  Do you need to set any parameters in the filter, or does just adding the filter cause this issue?

**Comment by richieloro** [comment]
No it does not happen on Xorg session (HXSM), only on wayland session (pipewire), I currently record on xorg, it works fine.
But on wayland there is the bug, also the context menus are all over the place sometime (but that is not an OBS specific it's a qt / wayland gnome thing).

**Comment by rmnvgr** [comment]
It has been happening to me for a while as well. If you add any filter to a Pipewire source (both screen and window), the region around the cursor becomes transparent (it isn't black, it's just that the background is black; if you add a solid color under the layer, you will see it around the cursor).

**Comment by GeorgesStavracas** [comment]
Okay I can reproduce this as well

**Comment by GeorgesStavracas** [comment]
Could you folks please test https://github.com/obsproject/obs-studio/pull/4742 and let me know if it fixes this issue?

If someone with more credentials rerun the "Flatpak (Experimental)" CI workflow, there'll be a fresh new Flatpak bundle for you all to easily test :slightly_smiling_face:

**Comment by richieloro** [comment]
Hello I want to test. But I don't understand how to do it ?

**Comment by luismanfroni** [comment]
Using XSHM choosing any scale filter makes the mouse stop having a black square under it:
(2 last prints is shot from a screen recording)
<details>
<img src="https://user-images.githubusercontent.com/33612042/188772875-01cd289c-b832-42e2-a11a-dba7c9b0f900.png" />
<img src="https://user-images.githubusercontent.com/33612042/188773739-85773418-327f-45ea-9a55-84bcf89aaa0e.png" />
<img src="https://user-images.githubusercontent.com/33612042/188773824-85720624-9242-40ea-bfe1-69090fa17b44.png" />
</details
