### ISSUE TITLE
Audio blips whilst recording under Linux

### ISSUE THREAD

**Issue by kaihendry** [obsproject/obs-studio#4712]
### Operating System Info

Other

### Other OS

Archlinux

### OBS Studio Version

26.1.2

### OBS Studio Log URL

https://obsproject.com/logs/lzdzyEyvep6-vUjB

### Expected Behavior

No audio blips

### Current Behavior

Captured Audio has blips, which can be clearly seen by FCP's audio analysis

<img src="https://s.natalian.org/2021-05-16/checksum.png">

https://s.natalian.org/2021-05-16/checksum.mp4

### Steps to Reproduce

1. Record to file
2. Copy over to my MBP for FCPX editing
3. Notice these audio peaks!
...

### Anything else we should know?

I tried different Rode mics, same issue.

**Comment by kaihendry** [comment]
Strangely when I listen to https://s.natalian.org/2021-05-16/checksum.mp4 I can't hear the blips but I can certain hear them under MacOS!

https://www.reddit.com/r/fcpx/comments/ndmtba/audio_has_clicks_only_when_playing_back_in_fcpx/?

**Comment by gxalpha** [comment]
This sounds very much like a Final Cut Pro X issue to me. If it's fine everywhere else, it seems unlikely to me that this is caused by OBS.
