### ISSUE TITLE
Projectors are showing "ALWAYS ON TOP" even though option on general tab of 'settings' dialog is not checked

### ISSUE THREAD

**Issue by lcalder** [obsproject/obs-studio#4719]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0-rc4

### OBS Studio Log URL

[2021-05-17 19-06-26.txt](https://github.com/obsproject/obs-studio/files/6497828/2021-05-17.19-06-26.txt)

### Expected Behavior

Since I do not have "Projectors always on top" selected in the General tab of the settings dialog, when I move or open or maximize another window it should be on top of the projector window.

### Current Behavior

If I maximize the main obs application or open another window (such as a browser) while my projectors are displaying, the projector will stay on top of any other open window even though my settings->general->'projectors always on top' is NOT checked.

If I check and uncheck the "always on top' checkbox and then close the settings dialog the problem is corrected. However if I exit OBS and relaunch, the problem will be back again until I repeat the above solution.

[2021-05-17 19-06-26.txt](https://github.com/obsproject/obs-studio/files/6497828/2021-05-17.19-06-26.txt)

### Steps to Reproduce

1.Make sure your settings are saved with 'projectors on top' set to unchecked on the settings->general tab (I also have save projectors on exit selected... BTW)
2. exit OBS
3. relaunch OBS and you projectors should appear
3. maximize a window or open a new application/window and the projector will still be on top.
4. TO FIX: check and then uncheck settings->general->'projectors always on top' and OK the settings dialog
...

**Comment by RytoEX** [comment]
I cannot reproduce this in OBS Studio 28.1.2 with either fullscreen or windowed scene projectors. Please retest this in OBS Studio 28.1.2 (or newer) and confirm is this is still happening.

**Comment by gxalpha** [comment]
Closing as there has been no response since November and we cannot reproduce this (see above).
Please open a new issue if this still happens in OBS 29.1 (current beta) or newer.
