### ISSUE TITLE
IBaseFilter:FindPin not implemented

### ISSUE THREAD

**Issue by berndfuhrmann** [obsproject/obs-studio#4721]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0-rc4

### OBS Studio Log URL

obsproject.com/not-applicable

### Expected Behavior

Calling IBaseFilter::FindPin("Output Pin", &pin); on OBS Virtual Camera should succeed with S_OK.

### Current Behavior

Calling IBaseFilter::FindPin("Output Pin", &pin); on OBS Virtual Camera returns E_NOTIMPL.

### Steps to Reproduce

1. Create a DirectShow graph
2. Add OBS virtual camera
3. Enum pins, query output pin id (Result: "Output Pin");
4. Call FindPin on OBS virtual camera

### Anything else we should know?

Likely, https://github.com/obsproject/libdshowcapture/blob/master/source/capture-filter.cpp#L500 this method needs to be properly implemented.

**Comment by Fenrirthviti** [comment]
Can you provide more information on what issue this is actually causing or what it is preventing from working?

**Comment by WizardCM** [comment]
This sounds like a feature request rather than a bug.

**Comment by jp9000** [comment]
Could you explain the context behind this issue report? We don't have an issue with this with all the known programs it's been used with. Like for example, what made you write this issue report, how specifically did you run into this issue

**Comment by berndfuhrmann** [comment]
@WizardCM https://docs.microsoft.com/en-us/windows/win32/api/strmif/nf-strmif-ibasefilter-findpin states, that IBaseFilter supports FindPin and NOT_IMPL doesn't seem like a response you have to expect. So from a formal standpoint, FindPin any filter must implement and support this, although not many apps might actually use this.

@Fenrirthviti, @jp9000 I found this issue while experimenting with DirectShow device configuration and graph building. I just wanted to persist a graph and rebuild it 100ms later. As a workaround, it's possible to just enumerate all pins again, but this is very ugly and so far OBS would be the first device that requires such a workaround. So there is no software I can show you that will have issues with FindPin, but FindPin is well documented and DirectShow filters are expected to implement it. At least, that is how I understand the Microsoft docs there.
If it is of any help, I can distill my experiment down to a small demo program.
Since this looks fairly easy to me, I was even thinking about making a PR myself.
