### ISSUE TITLE
Virtual Camera keeps Zoom hanging when run in >55 FPS

### ISSUE THREAD

**Issue by httpsterio** [obsproject/obs-studio#4726]
### Operating System Info

Windows 10

### OBS Studio Version

26.1.1

### OBS Studio Log URL

https://obsproject.com/logs/UAHS-qXzDi7ENtrS

### Expected Behavior

Zoom supports webcams up to (at least) 60 FPS. This was verified with using a Logitech C920 and DroidcamX on Android.

Setting the OBS resolution and output to 1080p and 60 FPS, it should show up in Zoom correctly and not affect the rest of the application.

### Current Behavior

The camera shows up correctly in Zoom and the picture runs at least locally at the correct resolution and FPS. At the same time, the Zoom UI starts to lag horribly and timing out every time you try to interact with it. It takes the inputs and performs them with a ~10 second delay. Base canvas and output resolution don't affect this.

### Steps to Reproduce

1. Set OBS video settings to 60FPS. 
2. Start Virtual Camera
3. Join a Zoom meeting
4. Turn camera on (and set it to OBS virtual camera)
...

### Anything else we should know?

Turning off the Virtual Camera will resolve the issue. Dropping the FPS in OBS video settings to 55 FPS and restarting the Zoom meeting will also resolve the issue.

**Comment by RytoEX** [comment]
While I can confirm this observed behavior, I would recommend reporting this to Zoom.  We don't have access to their code, but they have access to ours.

Additionally, their UI gets laggy even with a USB camera if I drag a window, such as the settings window with a camera preview, near the edges of a display.  The UI lag in general becomes worse if you mirror or rotate the camera (either USB or virtual camera) using Zoom options.

**Comment by WizardCM** [comment]
Sounds like a Zoom issue. Closing unless additional details are found.
