### ISSUE TITLE
OBS 26.1.1 encoder missing the option of HW encoder.

### ISSUE THREAD

**Issue by 7th-heaven** [obsproject/obs-studio#4729]
### Operating System Info

Windows 10

### OBS Studio Version

26.1.1

### OBS Studio Log URL

at the end of the report

### Expected Behavior

Settings--Output--Encoder
Shows the option of HW encoder NVENC and(or) QSV

### Current Behavior

Settings--Output--Encoder
Shows Software(x264) only.

### Steps to Reproduce

My device is a laptop. I attempted to test to see if iGPU(UHD 620) was able to handle 4K live streaming.
1. Run OBS (Encoder shows NVENC) 
2. Close OBS.
3. Disable 940MX GPU
4. Run OBS (Encoder shows QSV)
5. Finish my test of 4K with iGPU(UHD 620).
6. Close OBS.
7. Enable 940MX GPU
8. Run OBS.(Encoder shows QSV)
9. Close OBS.
10. Disable UHD 620
11. Run OBS (Encoder shows Software x264 only)
12. Close OBS.
13. Enable UHD 620
14. Run OBS(Encode still shows Software x264 only)
...

### Anything else we should know?

Here's the Logfile
14:31:59.303: CPU Name: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
14:31:59.303: CPU Speed: 1800MHz
14:31:59.304: Physical Cores: 4, Logical Cores: 8
14:31:59.304: Physical Memory: 8108MB Total, 4808MB Free
14:31:59.304: Windows Version: 10.0 Build 18363 (release: 1909; revision: 1556; 64-bit)
14:31:59.304: Running as administrator: true
14:31:59.304: Aero is Enabled (Aero is always on for windows 8 and above)
14:31:59.304: Windows 10 Gaming Features:
14:31:59.304: 	Game Bar: On
14:31:59.304: 	Game DVR: On
14:31:59.304: 	Game DVR Background Recording: Off
14:31:59.309: Sec. Software Status:
14:31:59.314: 
14:31:59.314: 
14:31:59.315: Current Date/Time: 2021-05-20, 14:31:59
14:31:59.315: Browser Hardware Acceleration: true
14:31:59.315: Portable mode: false
14:32:00.234: OBS 26.1.1 (64-bit, windows)
14:32:00.234: ---------------------------------
14:32:00.236: ---------------------------------
14:32:00.236: audio settings reset:
14:32:00.236: 	samples per sec: 48000
14:32:00.236: 	speakers:        2
14:32:00.240: ---------------------------------
14:32:00.240: Initializing D3D11...
14:32:00.240: Available Video Adapters: 
14:32:00.257: 	Adapter 0: NVIDIA GeForce 940MX
14:32:00.257: 	  Dedicated VRAM: 2107703296
14:32:00.257: 	  Shared VRAM:    4251406336
14:32:00.257: 	  PCI ID:         10de:134d
14:32:00.259: 	  Driver Version: 27.21.14.6647
14:32:00.259: 	  output 0: pos={0, 0}, size={1920, 1080}, attached=true, refresh=32, name=
14:32:00.259: 	Adapter 1: Intel(R) UHD Graphics 620
14:32:00.259: 	  Dedicated VRAM: 134217728
14:32:00.259: 	  Shared VRAM:    4251406336
14:32:00.259: 	  PCI ID:         8086:5917
14:32:00.261: 	  Driver Version: 23.20.16.4973
14:32:00.278: Loading up D3D11 on adapter NVIDIA GeForce 940MX (0)
14:32:00.406: D3D11 loaded successfully, feature level used: b000
14:32:00.406: DXGI increase maximum frame latency success
14:32:00.406: D3D11 GPU priority setup success
14:32:01.360: ---------------------------------
14:32:01.360: video settings reset:
14:32:01.360: 	base resolution:   1920x1080
14:32:01.360: 	output resolution: 1280x720
14:32:01.360: 	downscale filter:  Bicubic
14:32:01.360: 	fps:               30/1
14:32:01.360: 	format:            NV12
14:32:01.360: 	YUV mode:          709/Partial
14:32:01.360: NV12 texture support enabled
14:32:01.363: Audio monitoring device:
14:32:01.363: 	name: 默认
14:32:01.363: 	id: default
14:32:01.368: ---------------------------------
14:32:01.374: [adv-ss] version: e4bf5fa74936bc0130d80cd4fbc06d2e50f8525d
14:32:01.374: [adv-ss] trying 'E:/OBS/bin/64bit'
14:32:01.374: [adv-ss] found curl library at 'E:/OBS/bin/64bit/libcurl.dll'
14:32:01.374: [adv-ss] curl loaded successfully
14:32:01.401: [CoreAudio encoder]: Adding CoreAudio AAC encoder
14:32:01.402: Failed to load 'en-US' text for module: 'decklink-captions.dll'
14:32:01.404: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
14:32:01.477: [AMF] Unable to load 'amfrt64.dll', error code 126.
14:32:01.480: [AMF] AMF Test failed due to one or more errors.
14:32:01.480: Failed to initialize module 'enc-amf.dll'
14:32:01.523: [obs-browser]: Version 2.9.1
14:32:01.523: [obs-browser]: CEF Version 75.1.16+g16a67c4+chromium-75.0.3770.100
14:32:01.827: [obs-websocket] you can haz websockets (version 4.8.0)
14:32:01.827: [obs-websocket] qt version (compile-time): 5.10.1 ; qt version (run-time): 5.15.2
14:32:01.830: [obs-websocket] module loaded!
14:32:01.838: Failed to load 'zh-CN' text for module: 'source-switcher.dll'
14:32:01.842: Couldn't find VLC installation, VLC video source disabled
14:32:01.864: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
14:32:01.865: No blackmagic support
14:32:01.878: ---------------------------------
14:32:01.878:   Loaded Modules:
14:32:01.878:     win-wasapi.dll
14:32:01.878:     win-mf.dll
14:32:01.878:     win-dshow.dll
14:32:01.878:     win-decklink.dll
14:32:01.878:     win-capture.dll
14:32:01.878:     vlc-video.dll
14:32:01.878:     text-freetype2.dll
14:32:01.878:     source-switcher.dll
14:32:01.878:     rtmp-services.dll
14:32:01.878:     obs-x264.dll
14:32:01.878:     obs-websocket.dll
14:32:01.878:     obs-vst.dll
14:32:01.878:     obs-transitions.dll
14:32:01.878:     obs-text.dll
14:32:01.878:     obs-qsv11.dll
14:32:01.878:     obs-outputs.dll
14:32:01.878:     obs-filters.dll
14:32:01.878:     obs-ffmpeg.dll
14:32:01.878:     obs-browser.dll
14:32:01.878:     image-source.dll
14:32:01.878:     frontend-tools.dll
14:32:01.878:     enc-amf.dll
14:32:01.878:     decklink-ouput-ui.dll
14:32:01.878:     decklink-captions.dll
14:32:01.878:     coreaudio-encoder.dll
14:32:01.878:     advanced-scene-switcher.dll
14:32:01.878: ---------------------------------
14:32:01.878: ==== Startup complete ===============================================
14:32:01.907: All scene data cleared
14:32:01.907: ------------------------------------------------
14:32:02.115: WASAPI: Device '喇叭/耳机 (Realtek High Definition Audio)' [48000 Hz] initialized
14:32:02.115: [Loaded global audio device]: '桌面音频'
14:32:02.299: WASAPI: Device '麦克风阵列 (Realtek High Definition Audio)' [48000 Hz] initialized
14:32:02.299: [Loaded global audio device]: '麦克风/Aux'
14:32:02.301: Switched to scene '场景'
14:32:02.301: [adv-ss] trying to reconnect to  in 10 seconds.
14:32:02.301: ------------------------------------------------
14:32:02.301: Loaded scenes:
14:32:02.301: - scene '场景':
14:32:02.301: ------------------------------------------------
14:32:02.302: [adv-ss] started
14:32:02.334: adding 42 milliseconds of audio buffering, total audio buffering is now 42 milliseconds (source: 麦克风/Aux)
14:32:02.334: 
14:32:02.579: [obs-websocket] server started successfully on port 4444
14:32:02.579: [obs-websocket] io thread started

**Comment by ElectronicWar** [comment]
The Nvidia 940MX does not support NVENC (it's missing the needed chip).

The odd behavior of random QSV availability is strange tho.

**Comment by 7th-heaven** [comment]
> 
> 
> The Nvidia 940MX does not support NVENC (it's missing the needed chip).
> 
> The odd behavior of random QSV availability is strange tho.

I checked up the NVENC support list. 940MX does not supported... Sorry for my jumbled memory.

Is there any idea to refind the option of QSV ?

**Comment by WizardCM** [comment]
I believe the QSV check only runs when the Intel GPU is the default, but I may be wrong.

**Comment by RytoEX** [comment]
> 
> 
> I believe the QSV check only runs when the Intel GPU is the default, but I may be wrong.

I have the QSV encoder listed on my GTX 1060 + Intel HD Graphics 630 laptop when OBS is running on the GTX 1060.  The i5-8250U (UHD Graphics 620) is supposed to support QSV according to [i5-8250U on Intel ARK](https://ark.intel.com/content/www/us/en/ark/products/124967/intel-core-i5-8250u-processor-6m-cache-up-to-3-40-ghz.html).

**Comment by 7th-heaven** [comment]
After the drivers of UHD and 940mx had been uninstalled completely.
I searched the drivers in device manager automaticly.
Hardware(QSV) comes back...

May it helps the people who had the same problem.
