### ISSUE TITLE
TCP_NODELAY nagle on or off ? i think incorrect condition

### ISSUE THREAD

**Issue by marakew** [obsproject/obs-studio#4731]
### Operating System Info

Other

### OBS Studio Version

Other

### OBS Studio Log URL

none

### Expected Behavior

-

### Current Behavior

-

### Steps to Reproduce

-

### Anything else we should know?

https://github.com/obsproject/obs-studio/blob/master/plugins/obs-outputs/rtmp-stream.c#L1013

stream-&gt;rtmp.m_bUseNagle = true;<br class="Apple-interchange-newline">

https://github.com/obsproject/obs-studio/blob/master/plugins/obs-outputs/librtmp/rtmp.c#L941

    if(!r-&gt;m_bUseNagle)        setsockopt(r-&gt;m_sb.sb_socket, IPPROTO_TCP, TCP_NODELAY, (char *) &amp;on, sizeof(on));

**Comment by WizardCM** [comment]
We only use GitHub Issues for verifiable bugs, not code questions.

Please visit the #development channel the [Discord server](https://obsproject.com/discord) instead.
