### ISSUE TITLE
Wayland isn't record on gnome 40

### ISSUE THREAD

**Issue by Vertecedoc4545** [obsproject/obs-studio#4736]
### Operating System Info

Other

### Other OS

opensuse tumbleweed

### OBS Studio Version

27.0.0-rc5

### OBS Studio Log URL

https://obsproject.com/logs/dMsjpmxQiDwzPaEu

### Expected Behavior

That record properly the screen and audio

### Current Behavior

doesn't record the screen on wayland through pipewine neither the applications on past monts version recorded the screen on gnome 3.38
the gnome version is 40.0-2.2

### Steps to Reproduce

you need install open suse tumbleweed with the online installer 
1. (on terminal, flatpak is installed as default on open suse) flatpak remote-add flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
2. flatpak install flathub-beta com.obsproject.Studio
3. open obs 
4. at first time will take a little time so i pressed ESC i thing
5. add screen recoarding (pipewire)
6. try recoard
...

### Anything else we should know?

my gnome shell have some extensions 
blur my shell
compiz alike lamp effect
compiz windows effect
duckduckgo search privider
just perfection
night theme switcher
tweaks & extensions in system menu
user themes
workspace indicator

and on xorg works well

**Comment by GeorgesStavracas** [comment]
I can see in the logs the following line:

```
20:39:11.477: [pipewire] Failed to start screencast, denied or cancelled by user
```

Did you accidentally press "Cancel" in the window / monitor selection dialog? Can you see any other issue in `journalctl` - specifically, crashes or errors on `xdg-desktop-portal` or `xdg-desktop-portal-gtk`?

**Comment by All3xJ** [comment]
I have the same identical issue on GNOME. It worked on KDE.

**Comment by GeorgesStavracas** [comment]
Ah I see - I suspect you had two different portal implementations trying to run at the same time, and the KDE version was winning the race even when running on GNOME. Naturally, the KDE implementation wouldn't work on GNOME.

I'm pretty sure we could avoid situations like these, but I think your last comment confirms this is not an OBS Studio issue. Thanks for digging into it and figuring it out :slightly_smiling_face:

**Comment by Vertecedoc4545** [comment]
I don't had KDE applicatins or didn't installed KDE on open suse, only happens on open suse.
also some many other projects didn't work properly on open suse tumbleweed.
i am now on arch linux and works as expected

**Comment by Vertecedoc4545** [comment]
open suse appear be more for enterprisse ecosystem and nor for "normal users"

**Comment by RytoEX** [comment]
> 
> 
> Ah I see - I suspect you had two different portal implementations trying to run at the same time, and the KDE version was winning the race even when running on GNOME. Naturally, the KDE implementation wouldn't work on GNOME.
> 
> I'm pretty sure we could avoid situations like these, but I think your last comment confirms this is not an OBS Studio issue. Thanks for digging into it and figuring it out 🙂

@GeorgesStavracas Does that mean this should be closed, or is there something on the OBS side we should be addressing?

**Comment by GeorgesStavracas** [comment]
I can't think of anything that could be done on OBS Studio side to prevent this particular situation. It seems the packaging of portals isn't well handled by a few distros, and that's entirely external to OBS Studio. I believe we can close this one.
