### ISSUE TITLE
Closing randomly on KDE Plasma Wayland session 

### ISSUE THREAD

**Issue by eiglow** [obsproject/obs-studio#4738]
### Operating System Info

Fedora 34 (KDE Plasma 5.21.90)

### OBS Studio Version

27.0.0-rc5

### OBS Studio Log URL

This isn't an "obsproject.com URL", I'm not sure what you mean by that, but here is a github gist of the log: https://gist.github.com/eiglow/a71ea4c7e693205b670950630647843c

### Expected Behavior

For it to stay open

### Current Behavior

It closed after about a minute of idling. This is always reproducible, it happens every time. Screen-recording and everything else works fine.

Pushing it into the background, so that another app draws ontop of it, seems to trigger this bug much more quickly.

### Steps to Reproduce

1. Open OBS, allow it to capture your screen like usual
2. Wait

### Anything else we should know?

This is from flathub-beta. I don't have a backtrace, because no coredump is generated, because it's (seemingly) not a crash. I tried gdb'ing it from within the sandbox, but as soon as OBS closed, the sandbox instantly disappeared too. So maybe this is a flatpak bug, but I'm only seeing this happen in OBS, not in any of the other flatpak apps I use.

**Comment by kkartaltepe** [comment]
Ask you package manager to port the upstream qt fixes. In the future if you want to report a crash please try to provide a gdb backtrace.

https://github.com/qt/qtwayland/commit/93058de8d7e7c2f320c22b3bd898aa06cf5babcd
