### ISSUE TITLE
Media source input doesn't update automatically

### ISSUE THREAD

**Issue by Sov-trotter** [obsproject/obs-studio#4753]
### Operating System Info

Other

### Other OS

Manjaro Linux

### OBS Studio Version

26.1.2

### OBS Studio Log URL

https://obsproject.com/logs/VLJJZyL2Ce4EZLq5

### Expected Behavior

I am using ffmpeg to stream animations(gif) generated using a programming language(julia) via udp and taking them as input in OBS via media source. Quite frequently I do the following:

- Kill the ffmpeg process(stop the stream)
- overwrite the existing gif on disk and re-stream via ffmpeg. 

 I expect OBS to update these changes automatically(eg: if ffmpeg is terminated, stop showing the looping gif).

### Current Behavior

Currently the animation keeps on playing even if it kill ffmpeg or stream a new animation. It only updates when either I hide->unhide it or open it's properties and then close them. 

### Steps to Reproduce

1. Create new 'Media Source'.
2. Remove local file check mark.
3. Add: udp://0.0.0.0:8080 into 'Input' field.
4. Add: mpegts into the 'Input Format' field.
5. Run `-stream_loop -1 -i test.gif -loglevel quiet -f mpegts udp://0.0.0.0:8080` command with ffmpeg (test.gif is the test video)
6. kill ffmpeg process
7. try streaming another video 
8. If the preview is not updated try hiding/unhiding the source.
...

**Comment by NotDiamondZ** [comment]
I dunno.

**Comment by Sov-trotter** [comment]
Is this supposed to happen?

**Comment by NotDiamondZ** [comment]
Not sure. I'll test it on my Windows 10.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Sov-trotter** [comment]
Update on this issue: I actually figured out that the preview does update, but only after 1-2 minutes. Is there a way to handle this?

**Comment by Sov-trotter** [comment]
Updates: The input source does update automatically. Putting the `-re` flag worked for me.
