### ISSUE TITLE
Pipewire video option worked yesterday, but doesn't appear anymore today

### ISSUE THREAD

**Issue by All3xJ** [obsproject/obs-studio#4756]
### Operating System Info

Other

### Other OS

ArchLinux

### OBS Studio Version

27.0.0-rc6

### OBS Studio Log URL

https://hastebin.com/idikerusow.yaml

### Expected Behavior

It should show Pipewire source

### Current Behavior

It doesn't show it anymore, yesterday it worked.

### Steps to Reproduce

1.
2.
3.
...

### Anything else we should know?

![image](https://user-images.githubusercontent.com/20903913/119554618-2dbfed00-bd9d-11eb-8c00-68581ceff4b9.png)

**Comment by notr1ch** [comment]
Please use the forums or Discord for support.

**Comment by All3xJ** [comment]
> Please use the forums or Discord for support.

ok, I asked in Discord linux support, and they suggested to launch obs this way: QT_QPA_PLATFORM=wayland ob
to force it to launch under wayland session, and now it works.... don't know why it doesn't launch wayland session by default

**Comment by GeorgesStavracas** [comment]
So, a similar issue happened at https://github.com/obsproject/obs-studio/issues/4736#issuecomment-848222805 and it turned out that the culprit was having both the KDE and GNOME implementations of portals at the same time... could you please double check if that's your case too?

**Comment by GeorgesStavracas** [comment]
Another information that would be useful is your `journalctl` output. (Please make sure to remove any sensitive information, if any!)
