### ISSUE TITLE
Unresponsive cursor on OBS window with Huion 420 drawing tablet

### ISSUE THREAD

**Issue by Deivedux** [obsproject/obs-studio#4757]
### Operating System Info

Windows 10

### OBS Studio Version

26.1.1

### OBS Studio Log URL

https://obsproject.com/logs/dJIHFGfzpYalxpmd

### Expected Behavior

Cursor continues to function with the Huion 420 tablet when alt-tabbing into the OBS window.

### Current Behavior

The cursor stops responding to the Huion 420 tablet while the OBS window is in focus.

### Steps to Reproduce

1. Run OBS as administrator (normal mode gets a pass)
2. Try moving the cursor on the Huion 420 tablet with a pen

https://user-images.githubusercontent.com/36776659/119558726-716d2380-bdaa-11eb-9814-d0b04b8b089d.mp4

---
3. Run the tablet driver as administrator by accessing its settings
4. The cursor starts to work with OBS window in focus, but may stop again after the next OBS restart.

https://user-images.githubusercontent.com/36776659/119558935-b42efb80-bdaa-11eb-859b-d3391b7e626e.mp4

### Anything else we should know?

My understanding is that OBS is "taking over" the cursor if the driver that's controlling it has lower system permissions than itself. This has never been a thing with any other software, just OBS as far as my personal experience goes.

I should also note that even _clicking_ on the OBS window doesn't work, as you can see what happens when I even try to hover over it when exiting the File Explorer window.

**Comment by notr1ch** [comment]
This is a Windows security feature, applications at a lower permissions level cannot read from or send input to applications running at a higher permission level. It sounds like the issue is with your tablet driver not running with sufficient privileges. You should be able to confirm this by running any other application as administrator and trying the same thing.
