### ISSUE TITLE
Undo/redo of sync offset in Advanced Audio Properties causes crashing

### ISSUE THREAD

**Issue by iesvme** [obsproject/obs-studio#4760]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0-rc6

### OBS Studio Log URL

https://obsproject.com/logs/pIOoWnDM4JMNxtaR

### OBS Studio Crash Log URL

https://obsproject.com/logs/gAFJAg9l_J0cFhwO

### Expected Behavior

hoping it does work.

### Current Behavior

![image](https://user-images.githubusercontent.com/16969250/119646415-b8faba80-be51-11eb-8391-13a12dc631b1.png)
it can't undo/redo neither.

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/16969250/119644974-1beb5200-be50-11eb-90b3-d9263cc8e2d7.png)
![image](https://user-images.githubusercontent.com/16969250/119645496-a8961000-be50-11eb-8e93-66e08a3c7fc0.png)

1. open Advanced Audio Properties 
2. change the offset
3. click close button
4. open Advanced Audio Properties  again
5. undo
6. redo
7. undo
8. crash

### Anything else we should know?

[Crash 2021-05-26 18-31-07.txt](https://github.com/obsproject/obs-studio/files/6548695/Crash.2021-05-26.18-31-07.txt)

<details>
<summary>Crash log snippet</summary>
Unhandled exception: c0000005
Date/Time: 2021-05-26, 18:31:07
Fault address: 7FF6B029AAE3 (e:\users\andy\downloads\obs-studio-27.0-rc6-full-x64\bin\64bit\obs64.exe)
libobs version: 27.0.0-rc6 (64-bit)
Windows version: 10.0 build 17763 (release: 1809; revision: 1971; 64-bit)
CPU: AMD Ryzen 5 3600 6-Core Processor              

Thread 2DC8: (Crashed)
Stack            EIP              Arg0             Arg1             Arg2             Arg3             Address
000000C9886FB800 00007FF6B029AAE3 0000026C553309E0 0000000000000032 000000C9886FBB70 0000000000000000 obs64.exe!undo_stack::redo+0xa3
000000C9886FB940 00007FF6B012207E 0000000000000032 000000C9886FBB70 0000000000000000 000000C9886FBB70 obs64.exe!OBSBasic::qt_static_metacall+0x52e
000000C9886FB9D0 00007FF6B0124F96 0000000000000001 000000C9886FBB00 0000026C53030F01 000000C9886FBB00 obs64.exe!OBSBasic::qt_metacall+0x46
000000C9886FBA00 00007FFA3B870B52 0000026C553309E0 0000026C00000004 0000026C0151C100 0000026C53086E01 qt5core.dll!0x7ffa3b870b52
000000C9886FBB50 00007FFA3D9B5DBF 0000026C53083D60 000000C9886FC200 000000C9886FC248 00007FFA3B85427B qt5widgets.dll!0x7ffa3d9b5dbf
000000C9886FBB90 00007FFA3D9B6D5B 0000026C53083D60 0000026C53086E00 000000C9886FC248 0000026C553309E0 qt5widgets.dll!0x7ffa3d9b6d5b
000000C9886FBBE0 00007FFA3D9C4980 0000026C53083D60 000000C9886FBD10 00007FFA3D9B0000 00007FFA6F9BB5C6 qt5widgets.dll!0x7ffa3d9c4980
000000C9886FBC10 00007FFA3D9C3A03 00007FFA3B977338 0000026C52F70000 0000000000000000 0000026C53030F80 qt5widgets.dll!0x7ffa3d9c3a03
000000C9886FC150 00007FFA3B8519CA 00007FFA3B977338 000000C9886FC2C0 00007FFA3B977338 000000000000005A qt5core.dll!0x7ffa3b8519ca
000000C9886FC1C0 00007FFA3D3C84E2 0000000000000001 000000C9886FC3A0 00007FFA3B977338 0000026C5D8AD0D0 qt5gui.dll!0x7ffa3d3c84e2
000000C9886FC320 00007FFA3D3CA9CA 0000000006000000 0000000000094EE4 0000026C7E4ABE90 0000002F00000058 qt5gui.dll!0x7ffa3d3ca9ca
000000C9886FC350 00007FFA3D38D77F 0000026C53086ED8 0000026C7E4ABE90 0000026C09F777E0 00007FFA3D959688 qt5gui.dll!0x7ffa3d38d77f
000000C9886FC410 00007FFA3D3A260D 0000000000000024 0000000000000024 0000000000000024 0000026C02C63E60 qt5gui.dll!0x7ffa3d3a260d
000000C9886FC4B0 00007FFA3D38ECE0 0000000000000000 00007FFA3D959688 000000C9886FC5E0 0000026C02C63E60 qt5gui.dll!0x7ffa3d38ece0
000000C9886FC4E0 00007FFA3B89A83A 0000026C5308FC80 0000000000000000 0000026C02C63E60 0000000000000000 qt5core.dll!0x7ffa3b89a83a
000000C9886FF600 00007FFA3FEB2619 0000000000000000 00007FFA00000014 0000000000000000 0000000000000002 qwindows.dll!0x7ffa3feb2619
000000C9886FF630 00007FFA3B84DE7C 0000026C5305D9B8 0000000000000000 000000C9886FFB60 00007FFA3B96FC90 qt5core.dll!0x7ffa3b84de7c
000000C9886FF690 00007FFA3B850994 00007FF6B03BBC17 0000000000000002 000000C9886FFB60 0000000000000060 qt5core.dll!0x7ffa3b850994
000000C9886FF6F0 00007FF6B01541CF 0000026C53049610 0000026C53049610 0000000000000000 0000026C53064410 obs64.exe!run_program+0x78f
000000C9886FFA60 00007FF6B0156101 0000000000000000 0000000000000000 0000000000000000 0000026C530315FA obs64.exe!main+0x591
000000C9886FFC20 00007FF6B02BDC87 0000000000000000 0000000000000000 0000000000000000 0000000000000000 obs64.exe!WinMain+0x157
000000C9886FFCB0 00007FF6B02BD546 0000000000000000 0000000000000000 0000000000000000 0000000000000000 obs64.exe!__scrt_common_main_seh+0x106
000000C9886FFCF0 00007FFA70977974 0000000000000000 0000000000000000 0000000000000000 0000000000000000 kernel32.dll!0x7ffa70977974
000000C9886FFD20 00007FFA736CA2F1 0000000000000000 0000000000000000 0000000000000000 0000000000000000 ntdll.dll!0x7ffa736ca2f1
</details>

**Comment by notr1ch** [comment]
Caused by redo callback clearing redo stack while adding undo action:

```
     obs64.exe!undo_stack::clear_redo() Line 164    C++
     obs64.exe!undo_stack::add_action(const QString & name, std::function<void __cdecl(std::string const &)> undo, std::function<void __cdecl(std::string const &)> redo, std::string undo_data, std::string redo_data, bool repeatable) Line 61    C++
>    obs64.exe!OBSAdvAudioCtrl::syncOffsetChanged(int milliseconds) Line 535    C++
     obs64.exe!OBSAdvAudioCtrl::qt_static_metacall(QObject * _o, QMetaObject::Call _c, int _id, void * * _a) Line 155    C++
     [External Code]    
     obs64.exe!OBSAdvAudioCtrl::SourceSyncChanged(__int64 offset) Line 381    C++
     obs64.exe!OBSAdvAudioCtrl::qt_static_metacall(QObject * _o, QMetaObject::Call _c, int _id, void * * _a) Line 149    C++
     [External Code]    
     obs64.exe!OBSAdvAudioCtrl::OBSSourceSyncChanged(void * param, calldata * calldata) Line 331    C++
     obs.dll!signal_handler_signal(signal_handler * handler, const char * signal, calldata * params) Line 332    C
     obs.dll!obs_source_set_sync_offset(obs_source * source, __int64 offset) Line 3907    C
     obs64.exe!OBSAdvAudioCtrl::syncOffsetChanged::__l2::<lambda>(const std::string & name, __int64 val) Line 531    C++
     [External Code]    
     obs64.exe!undo_stack::redo() Line 101    C++
     obs64.exe!OBSBasic::on_actionMainRedo_triggered() Line 8357    C++
```

**Comment by RytoEX** [comment]
I've edited the original post to include a Crash Log URL to reduce the amount of scrolling needed.

In the future, you can upload your crash log and get a Crash Log URL by using the "Upload Last Crash Report" menu option in Help -> Crash Reports.

![image](https://user-images.githubusercontent.com/624931/119707794-8ccb4380-be29-11eb-8ab7-47993a835de5.png)
