### ISSUE TITLE
Blank pipewire capture on Wayland/F34 Silverblue/flatpack-beta

### ISSUE THREAD

**Issue by bnordgren** [obsproject/obs-studio#4762]
### Operating System Info

Other

### Other OS

Fedora Silverblue 34

### OBS Studio Version

27.0.0-rc6

### OBS Studio Version (Other)

flatpak-beta

### OBS Studio Log URL

https://obsproject.com/logs/HqHvdr535q6t1J0B

### Expected Behavior

When adding a "Window Capture (Pipewire)" source, I expected: 

1. To select the window
2. To see the outline of the window on the preview screen, which I could then resize or move until it was positioned as I wanted it.
3. To see the contents of the selected window in the previes screen.

### Current Behavior

1. I was able to select the window to share via the selection dialog.
2. A single red handle appeared in the upper left corner of the preview screen. (I was able to right click on the source and select Transform -> Fit to Screen.)
3. The contents of the preview pane were blank. 

I selected a few different windows with the same result. Also the same behavior results from adding a "Screen Capture (Pipewire)" source.

There is no output from this time period from the command: 
`sudo journalctl --since today | grep xdg-desktop-portal`

### Steps to Reproduce

1. Installed obs-studio from flatpak-beta repository
2. Added source to default scene

### Anything else we should know?

I normally run obs-studio 27.0.0-rc3 from the rpm-fusion repos out of a toolbox, on X instead of Wayland. None of my config from that environment has carried over to the flatpak install.

**Comment by GeorgesStavracas** [comment]
Okay, looking at the OBS Studio log, it seems everything went well on OBS side. [Here's a small python script to test window sharing](https://github.com/obsproject/obs-studio/files/6548726/xdp-screen-cast.zip), could you please run it and let me know if window sharing works with it? To run it, unpack this zip file, open a terminal at the folder you unpacked it, and run:

```
$ ./xdg-screen-cast.py
```

**Comment by carlocastoldi** [comment]
> Okay, looking at the OBS Studio log, it seems everything went well on OBS side. [Here's a small python script to test window sharing](https://github.com/obsproject/obs-studio/files/6548726/xdp-screen-cast.zip), could you please run it and let me know if window sharing works with it? To run it, unpack this zip file, open a terminal at the folder you unpacked it, and run:
> 
> ```
> $ ./xdg-screen-cast.py
> ```

It does work for me.
I am on GNOME 40 on Manjaro Linux

**Comment by bnordgren** [comment]
The script works for me. 

OBS from flatpak-beta now also works for me.

I haven't updated either the base system or the flatpak. I have rebooted a couple of times. I cannot think of what might have happened to fix it, but the problem is apparently gone...

**Comment by bnordgren** [comment]
D'oh. Spoke too soon. Running your script then running OBS makes OBS work. Logging out and back in and running OBS without running your script exhibits the behavior above. Your script seems to initialize something that persists until the session terminates...

**Comment by bnordgren** [comment]
Further testing this morning. This time with a reboot rather than merely log-out, log-in under a different windowing system. Flatpak OBS worked right out of the gate, no need to run the script first.

Perhaps what I'm running into is that switching back and forth between X11 and Wayland merely by logging out and back in is not the way to go. 

Not convinced that I've found what is causing the initially reported problem. For the moment I'm willing to chalk this up to larger-scale system issues related to switching back and forth between X11 and Wayland. I can't point the finger at anything specific other than that.

I'll close now and re-open if it happens again and rebooting doesn't fix it...
