### ISSUE TITLE
"Default" button does not work on Chroma Key when applied to media source or video capture device

### ISSUE THREAD

**Issue by dodgepong** [obsproject/obs-studio#4764]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0-rc6

### OBS Studio Log URL

n/a

### Expected Behavior

Pressing "Default" on a Chroma Key filter should reset the filter settings to default.

### Current Behavior

Clicking the "Default" button after changing the Chroma Key settings does not reset the settings to the default.

### Steps to Reproduce

1. Create a new media source or video capture device source.
2. Add a Chroma Key filter
3. Change the settings on the filter
4. Click the "Default" button -- nothing happens.

### Anything else we should know?

The "Default" button appears to work on Display capture and Image sources. It may only be an issue on async video sources.

To make things weirder, it appears that this issues resolves itself once you add another filter. If you delete all the filters, close the filters window, then open the Filters window again and add a filter, then the issue reappears.

**Comment by jpark37** [comment]
I think this is some sort of focus bug for sources that can have A/V filters in the filters dialog. It also seems to apply to other filter types, so I don't think this is just limited to Chroma Key.

This also doesn't appear to be a 27 regression since I can reproduce in 26.1.1.
