### ISSUE TITLE
Crash on Win7 (after some days)

### ISSUE THREAD

**Issue by GiovanniG11** [obsproject/obs-studio#4772]
### Operating System Info

Other

### Other OS

Win7 SP1

### OBS Studio Version

26.1.2

### OBS Studio Log URL

https://pastebin.com/JMYKxKGW

### Expected Behavior

The OBS was working fine for some days (about 20), but yesterday and today it crashed with the same error, after the first crash yesterday the PC was rebooted, what is this about? (Windows logs) Thanks.
Faulting application name: obs64.exe, version: 26.1.1.0, time stamp: 0x5ff48658
Faulting module name: ntdll.dll, version: 6.1.7601.24384, time stamp: 0x5c6e245d
Exception code: 0xc0000005
Fault offset: 0x000000000006bf17
Faulting process id: 0x8ec
Faulting application start time: 0x01d7539d29db7ca1
Faulting application path: C:\Program Files\obs-studio\bin\64bit\obs64.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 8fb147e1-c057-11eb-a8b3-80a589cd1ef0

### Current Behavior

see up

### Steps to Reproduce

1.
2.
3.
...
nothing

**Comment by MattyFresh68** [comment]
A)you didn't fill out the template properly.
B)windows 7 has been officially dead for well over a year

**Comment by WizardCM** [comment]
We do not use GitHub Issues for support questions. In this case, this is not an actionable bug report with reliable reproduction steps.

Additionally, as @MattyFresh68 has mentioned, Windows 7 is not officially supported. We won't stop you from using it, but for the most part it's up to you to try and solve any issues you run into.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

**Comment by GiovanniG11** [comment]
there are no other infos to add, I don't know what you mean. Obs doesn't report any debug.
I can agree with you about Win7, I've just asked how this bug can be connected to, if it is because of Win7 I accept it
