### ISSUE TITLE
Can't capture applications with Reverse PRIME Bypass

### ISSUE THREAD

**Issue by HugLifeTiZ** [obsproject/obs-studio#4775]
### Operating System Info

Ubuntu 20.04

### OBS Studio Version

26.1.2

### OBS Studio Log URL

https://obsproject.com/logs/mN08VP5KTlUT-ww4

### Expected Behavior

The application is continuously captured to the recorded video.

### Current Behavior

The last frame shown before Reverse PRIME Bypass kicks in is all that is captured.

### Steps to Reproduce

1. Use a laptop with NVIDIA Optimus, and a desktop environment with Xorg.
2. Use an NVIDIA driver version equal or greater to 460.27.04.
3. Use the standard on-demand configuration where the desktop is rendered by the integrated GPU and render offload is controlled by environment variables.
4. Plug in an output wired to the NVIDIA card.
5. Run a fullscreen application on that output, with render offload enabled, and the compositor disabled (or enable automatic unredirection for compositors that have it).

### Anything else we should know?

This issue can be worked around by rendering the entire desktop on the NVIDIA GPU, but that unfortunately has its own problems. Besides, render offload and Reverse PRIME seem to be the way NVIDIA wants to handle Optimus moving forward. Unfortunately there does not seem to be a documented way to disable Reverse PRIME Bypass. Another workaround is to enable a compositor and prevent it from unredirecting the application, but that can impose performance and/or latency overhead.

The ball for this is very likely entirely in NVIDIA's court, but I wanted to at least document it here as it does affect usage of OBS Studio.

**Comment by arrowgent** [comment]
do you use nvidia's enviornment variables to offload?

in your ~/.profile, or in a terminal before launching obs
```
export __NV_PRIME_RENDER_OFFLOAD=1
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export __VK_LAYER_NV_optimus=NVIDIA_only
export __NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-0
```

yes optimus on linux has been a struggle
with Xorg it should be working as of latest 460.x driver versions (or previous 440/450)
ive not had issue with previous versions of OBS, i dont think i will be testing v27 anytime soon unfortunately

**Comment by HugLifeTiZ** [comment]
Yeah, the offload part is working just fine. The fact that Reverse PRIME Bypass is kicking in and rendering applications uncaptureable is further proof of that. I also run OBS Studio via offload, and that doesn't make any difference on whether or not it can capture applications running with Reverse PRIME Bypass.

**Comment by kkartaltepe** [comment]
Can you test #6091 and see if there is any informative error when the capture fails (or if it miraculously works?)

**Comment by HugLifeTiZ** [comment]
Hey there. I appreciate you reaching out, but I'm not going to have an opportunity to test anytime soon; I'm running my system with NVidia-as-Primary because of a xorg/kernel bug, [this one in specific.](https://gitlab.freedesktop.org/xorg/xserver/-/issues/24#note_1317487) I'll get back to you if I do, though. Thank you!

**Comment by kkartaltepe** [comment]
im closing this out as someone has confirmed capture working correctly on a mixed intel/nvidia system with intel driving the x session.
