### ISSUE TITLE
White noise in audio when hitting higher levels

### ISSUE THREAD

**Issue by yoniversefilms** [obsproject/obs-studio#4776]
### Operating System Info

macOS 10.15

### OBS Studio Version

26.1.2

### OBS Studio Log URL

na

### Expected Behavior

I expect to be able to record audio in any level without having a white noise accompany it at certain moments (higher decibles) 

### Current Behavior

when I connect a mic directly to the 3.5mm input in my mac the audio gets noticeable white noise when getting into the yellow or red area in the meter.
This does not happen when sending the audio through HDMI I haven't tested sending audio through USB.
noise suppression tends to help but not eliminate the issue

### Steps to Reproduce

1.
2.
3.
...

**Comment by notr1ch** [comment]
This is almost certainly a hardware issue, a 3.5mm connection is an analogue connection which can pick up a lot of noise, HDMI and USB are digital and do not suffer from this. Having high volume or gain applied to a 3.5mm source will almost certainly result in some noise.
