### ISSUE TITLE
Intel 11gen processor integrated graphics card UHD750 hardware-coded QSV memory leak

### ISSUE THREAD

**Issue by lipengzhou** [obsproject/obs-studio#4777]
### Operating System Info

Windows 10

### OBS Studio Version

26.1.1

### OBS Studio Version (Other)

27.0.0.0-rc6

### OBS Studio Log URL

https://obsproject.com/logs/mLeb3y2pmtSNo0nt

### Expected Behavior

Now graphics cards are too expensive, so we can only use integrated graphics cards.

A memory leak occurred in OBS broadcast on Intel 11 generation processors using the integrated graphics card UHD750 hardcoded-QSV of the CPU, which I tested did not occur with UHD630.

And I tried to update the UHD750 driver, and it was still a memory leak.

Hope to help me solve this problem, thanks to the super developer.

### Current Behavior

I had a memory leak when I was coding with the built-in UHD750 graphics card QSV on an Intel 11 generation processor. I tried 26.1.1 and the RC version on GitHub didn't fix the problem.

### Steps to Reproduce

1. Open the obs
2. Add desktop sources
3. Select the QSV hardware code
4. Go live
5. Memory continues to grow until it fills up the entire memory space

My memory is 32GB 3600MHz.

**Comment by WizardCM** [comment]
Should be fixed by #5829. Please test in 27.2 and let us know if it's not fixed.
