### ISSUE TITLE
FFmpeg Media Sources always auto-play on launching OBS or changing the media's properties

### ISSUE THREAD

**Issue by cbeer** [obsproject/obs-studio#4778]
### Operating System Info

macOS 11.3

### OBS Studio Version

27.0.0-rc6

### OBS Studio Log URL

-

### Expected Behavior

I have a media source where I've disabled "Restart playback when source becomes active". I expected that the media source in my scene will not play unless + until I click the play button on the source

### Current Behavior

The media source starts playing immediately when OBS is started or when the media's properties are changed, whether the scene is active or not.

### Steps to Reproduce

1. Add a media source to a scene
2. Edit the properties of the media source to disable "Restart playback when source becomes active"
3. Click OK.
4. The media starts playing immediately.
3. Quit OBS
4. Re-open OBS
5. The media starts playing immediately.

Note that this happens in studio mode or non-studio mode, and whether the scene is active or non-active when the media properties are saved or when OBS is relaunched, or the state of the "Close file when inactive" property. 

This video shows the auto-play behavior in studio mode; when OBS is relaunched when the media source is in "preview", the media starts playing immediately after being relaunched: 
https://user-images.githubusercontent.com/111218/120210735-f90cc500-c1e4-11eb-9992-4084993c377c.mp4

### Anything else we should know?

The last time the relevant code was touched (in 2016: https://github.com/obsproject/obs-studio/commit/74c78c1f131de85ccdfdfbc39b7975736be73349) suggests that this may be a feature (and previously the behavior was to always autoplay, whether the source is active or not), in which case I'd propose to add an Autoplay setting on the media source to control this behavior, maybe something like (omitting property boilerplate):

```diff
        bool active = obs_source_active(s->source);
-       if (!s->close_when_inactive || active)
+       if (!s->close_when_inactive || active || s->autoplay)
                ffmpeg_source_open(s);
 
        dump_source_info(s, input, input_format);
-       if (!s->restart_on_activate || active)
+       if (s->autoplay || (s->restart_on_activate && active))
                ffmpeg_source_start(s);

```
https://github.com/obsproject/obs-studio/blob/master/plugins/obs-ffmpeg/obs-ffmpeg-source.c#L441-L447

I'm happy to work on this issue, if I can get guidance on:

- whether the current behavior is, indeed, a feature not a bug or quirk of history;
- guidance on how the project handles internationalization for new strings (e.g. do I just add an English version, and other contributors will provide translations asynchronously?);
- and, having peeked down this path a little bit, the changes i propose above could leave the media in the `OBS_MEDIA_STATE_NONE` state, which the [media controls play/pause button handle](https://github.com/obsproject/obs-studio/blob/master/UI/media-controls.cpp#L347-L370) doesn't deal with. Is it appropriate to add that state to the action, initialize it in a different existing state, or add a new state for non-autoplaying videos (`OBS_MEDIA_STATE_READY` or somesuch)?

Thanks

**Comment by notr1ch** [comment]
This behavior is / was intended, as prior to the media controls being added there was no easy way to control media sources via the UI. Now that we have media controls, I do agree that the autoplay behavior could be seen as undesirable.

For adding new strings, only edit the en-US.ini and the other languages will be built from this file on [Crowdin](https://crowdin.com/project/obs-studio).

I do think a ready state might be useful in this case, none implies it perhaps hasn't finished loading or similar.

**Comment by cbeer** [comment]
Unresolved, but closing in favor of an RFC:

https://github.com/obsproject/rfcs/pull/40
