### ISSUE TITLE
https://obsproject.com/update_studio/manifest.json returns a 404

### ISSUE THREAD

**Issue by AshleyHow** [obsproject/obs-studio#4783]
### Operating System Info

Windows 10

### OBS Studio Version

26.1.2

### OBS Studio Log URL

NA

### Expected Behavior

JSON manifest is able to be downloaded successfully

### Current Behavior

A **404 Not Found** error is returned when trying to download the file.

### Steps to Reproduce

1. Attempt to navigate to https://obsproject.com/update_studio/manifest.json

### Anything else we should know?

This manifest is used to determinate the latest sable version of OBS Studio using https://github.com/aaronparker/Evergreen

**Comment by jp9000** [comment]
It's not currently available because we're in the middle of an update. That's probably not the most reliable way to determine the current version. I'd probably check the git for the latest non-RC non-beta release tag instead. And even then, sometimes we delete the tag.

**Comment by jp9000** [comment]
Also just as a note, we sometimes temporarily remove the file to halt updates. So what we'll usually do is release, then if we see anything go wrong, we'll pause the updates by temporarily removing/renaming the file, then when we're ready we'll put it back again. Kind of gives me a somewhat scuffed way to do rolling updates if I need to gauge how the update is going for users.

**Comment by notr1ch** [comment]
The update has begun rolling out so the manifest is available again now.
