### ISSUE TITLE
OBS crashed when I pressed start recording

### ISSUE THREAD

**Issue by denisgolius** [obsproject/obs-studio#4791]
### Operating System Info

Ubuntu 20.04

### OBS Studio Version

27.0.0

### OBS Studio Log URL

https://pastebin.com/Y3SZX7aa

### OBS Studio Crash Log URL

https://pastebin.com/FyYePZhC

### Expected Behavior

normal work

### Current Behavior

When I pressed "start recording" it crashed.

### Steps to Reproduce

1. Install latest version of obs 27 from ppa
2. run it
3. press start recording

### Anything else we should know?

Maybe it crashed because I have different ffmpeg version?

https://pastebin.com/pVGu6xd7

My os + driver versions
https://pastebin.com/rQvMKGC2

**Comment by WizardCM** [comment]
Please provide a gdb trace.

**Comment by denisgolius** [comment]
> Please provide a gdb trace.

https://pastebin.com/1BvVTuFJ

First time work with gdb... Sorry if I'm doing something wrong.

**Comment by kkartaltepe** [comment]
> > Please provide a gdb trace.
> 
> https://pastebin.com/1BvVTuFJ
> 
> First time work with gdb... Sorry if I'm doing something wrong.

That does not contain a back trace. But from where it failed your assumption was correct you replaced ffmpeg with one that is not binary compatible with the typical ubuntu ffmpeg.

**Comment by denisgolius** [comment]
> > > Please provide a gdb trace.
> > 
> > 
> > https://pastebin.com/1BvVTuFJ
> > First time work with gdb... Sorry if I'm doing something wrong.
> 
> That does not contain a back trace. But from where it failed your assumption was correct you replaced ffmpeg with one that is not binary compatible with the typical ubuntu ffmpeg.

It's interesting cuz when I installed a new ffmpeg from ppa all apps still works well instead of obs. Maybe there is issue with obs that can work with some of ffmpeg versions and some system libs version?

**Comment by denisgolius** [comment]
Build it from sources and it works well.
