### ISSUE TITLE
OBS 27.0 freeze when I try to move a source in "Sources" panel

### ISSUE THREAD

**Issue by Copainduweb** [obsproject/obs-studio#4795]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0

### OBS Studio Log URL

http://copainduweb.com/partage/2021-06-02%2010-06-38.txt

### Expected Behavior

Move some source inside the "Sources" panel of a scene

### Current Behavior

A very long waiting or completly freeze of OBS

### Steps to Reproduce

1. Open OBS
2. Go to a specific scene
3. Click on a source and drag without release
4. Freeze

### Anything else we should know?

This does not happen in fairly simple scenes, but the more nesting there is, the longer the waiting time becomes until it becomes infinite.

For example my webcam is nested several times (to be able to apply fx on top of other fx) and at each stage of the nesting the waiting times increase.

This problem did not exist at all on the previous version of OBS.

Thanks to help me !

**Comment by nuttylmao** [comment]
Can confirm. The issue is particularly noticeable with heavily nested scenes. Downgrading to v27 RC2 fixes the issue entirely. All releases following RC2 (including v27 Stable) experience the freezing issue.

**Comment by Copainduweb** [comment]
Thank you. I can confirm that 27 RC2 fixes the issue here too.
I tried to install the RC3 version and the bug appears.
That the bug occurs when I use drag and drop but also when I try to move my sources with the up and down buttons at the bottom of the panel.

**Comment by jp9000** [comment]
I'll check out the performance of the undo/redo operation. I don't think it should be occurring on drag. Should only be on drop. But there's probably something unoptimized when backing up scene data for the undo/redo operation that can be optimized as well.

**Comment by jp9000** [comment]
I'm not reproducing any issue with drag. Only drop, which is definitely taking some time. Are you able to confirm?

**Comment by RytoEX** [comment]
The log in the OP is a bit too busy to easily understand what's going on.

@nuttylmao Please provide a log so we can compare.

Is someone able to provide a scene collection for us to examine?  If this can be reproduced with a heavily nested scene collection of just color sources, that would be helpful.

Here are the questions I have about reproducing this:
1. Is this reproducible without any third party plugins?
2. Are we talking about nesting as in "scenes as sources" or nesting as in groups?
3. How much nesting is required to reproduce this issue?
4. Does the issue actually occur when _just_ dragging a source, or only after _dropping_ the source?

**Comment by Copainduweb** [comment]
Here is [my scenes collection](http://copainduweb.com/partage/COPAIN_DU_WEB_1.json) and a [log](http://copainduweb.com/partage/2021-06-05%2011-21-35.txt) without websocket's debug logging.

I can confirm that the problem appear not on drag but on drop.

"CAM1 - SOURCE" : OK
"CAM1 + COULEURS" (with "CAM1 - SOURCE" inside) : OK
"CAM1 + COUL. + DEFOR." (with "CAM1 + COULEURS" inside) : it begin to take more time on drop
"CAM1 + COUL. + DEFOR. + FX" (with "CAM1 + COUL. + DEFOR." inside) : it will take much more time

Try to move a source in the "CAM 1 - MASTER" scene. It should takes an infinite time then : white screen.

1. I don't know how to desactivate all my plugins…
2. Scenes as sources
3. Maybe you have the answer now
4. On drop

Thank you for taking the time to deal with my problem.

**Comment by RytoEX** [comment]
I can reproduce by loading the scene collection and simply trying to move one source with the up arrow in the sources list.

Perhaps it is worth noting that this scene collection on load takes up 2-2.5 GB of RAM.  While waiting for the source reorder action to resolve, the memory usage rose to about 6GB.

**Comment by Copainduweb** [comment]
As you can see I use a lot of scenes / sources / filters / plugins. I know that I ask a lot of work to my pc and obs :)

What surprises me is that I don't have this freeze problem on version 27 rc2 while the undo / redo option is there. Something happened between version rc2 and rc3.

**Comment by RytoEX** [comment]
> Something happened between version rc2 and rc3.

What happened is that we added undo/redo tracking for source reordering between RC2 and RC3.  In RC2, that wasn't tracked in undo/redo.  Undo/Redo tracks a lot of data.  With the size and complexity of your scene collection, the undo/redo data being updated is likely the issue.

**Comment by Copainduweb** [comment]
Do you think you will find a solution or am I condemned to the RC2 version?

**Comment by RytoEX** [comment]
You can test the [Windows 64-bit build artifact](https://github.com/obsproject/obs-studio/actions/runs/908766402) from #4813 if you want.  Though, please take care to back up your files first.

In my limited testing, that build seems to resolve the issue.

**Comment by Copainduweb** [comment]
Sorry but I don't know how to install this…

**Comment by Copainduweb** [comment]
… and I think I close something by mistake.

**Comment by Copainduweb** [comment]
Ok @RytoEX ! I try the artifact and it seems to correct the bug !! Do you think this fix will be implemented in futur version of OBS ?
