### ISSUE TITLE
Microsoft Defender SmartScreen prevented an unrecognised app from starting. Running this app might put your PC at risk.

### ISSUE THREAD

**Issue by kashyap-shah** [obsproject/obs-studio#4797]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0

### OBS Studio Log URL

https://obsproject.com/download

### Expected Behavior

Install smoothly without any windows defender security showing warning.

### Current Behavior

Windows Security warns to install app that might be a risk to a device.

### Steps to Reproduce

1. Downloaded .exe
2. opened the .exe file
3. windows security pop-up with a message - "Microsoft Defender SmartScreen prevented an unrecognised app from starting. Running this app might put your PC at risk."
...

### Anything else we should know?

Q. Is this safe to install?

**Comment by kashyap-shah** [comment]
No, I don't know about the OBS certificate. 
I just wanted to live stream meeting so get to know about this software.

**Comment by kashyap-shah** [comment]
> Is it signed with the obs certificate? If so, then yes.
> 
> And windows has the ability to show you the certificate, right click on the executable and open the properties dialog, the signature will be one of the tabs in it.

**Comment by notr1ch** [comment]
This happens to any newly released .exe that doesn't pay to bypass the warning. As long as you download from obsproject.com or the github releases, you're safe.
