### ISSUE TITLE
Game Capture breaks after toggling studio mode

### ISSUE THREAD

**Issue by headassbtw** [obsproject/obs-studio#4801]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0

### OBS Studio Log URL

https://obsproject.com/logs/2EGE3CuUDi6MvmJ-

### Expected Behavior

I expected to have a game capture running, go into studio mode to edit the contents of a different scene, and come back to still have the game capture working

### Current Behavior

i enter studio mode, tweak another scene, and when i exit studio mode, the game capture no longer works unless it's respective properties window is open

https://user-images.githubusercontent.com/16214950/120546842-2f913e00-c3a5-11eb-864c-93407e810425.mp4

### Steps to Reproduce

1. Have a game capture source
2. Have a separate scene you want to edit (in my case it was also added as a source in the first scene)
3. Enter studio mode
4. Tweak the secondary scene
5. Exit studio mode

### Anything else we should know?

* the issue happens on 27 RC4 and RC5 as well (those are the versions i was running before i updated to stable)
* i did not use OBS to record the demonstration video, so it was not a separate instance grabbing the game capture

**Comment by dodgepong** [comment]
Does it work again once you focus the game?

Does this happen on v26.1?

**Comment by headassbtw** [comment]
on 27.0.0 it persists when i re-focus the game,

however, this does not happen on 26.1.1

**Comment by Fenrirthviti** [comment]
Confirmed on my end as well. Something about editing another scene is the trigger, just enabling studio mode, switching scenes, and disabling does NOT trigger this. Editing the other scene in studio mode and disabling studio mode causes this to replicate 100% of the time.

**Comment by ammondn** [comment]
I was recording an old family video with a video capture card two weeks ago from a Hi 8 Sony camera. Today I attempted to do the same with all the same wires but the video would not show.  I am guessing it is an analog signal.  I thought this was possibly related to this other capture card problem. I want v 26 back.

**Comment by Fenrirthviti** [comment]
> I was recording an old family video with a video capture card two weeks ago from a Hi 8 Sony camera. Today I attempted to do the same with all the same wires but the video would not show. I am guessing it is an analog signal. I thought this was possibly related to this other capture card problem. I want v 26 back.

That does not seem related to this bug report. Please try the support channels in our Discord or forums for more assistance.

**Comment by lindenkron** [comment]
Just adding my experience with a similar issue. Browser source though:
https://streamable.com/5syvha

**Comment by Fenrirthviti** [comment]
That looks like a webcam source, not a browser source, can you please provide a log file? What is changed in the second scene doesn't have any relevance, it's any change at all that seems to trigger it, but only certain sources seem to be affected. I can only currently replicate with Game Capture source as the one that stops showing.

**Comment by lindenkron** [comment]
Sorry about the vagueness above.

So main scene has two Nested streams (the stream), and those nested scenes have a browser source in them each.
The 'webcam' is a window capture of an electron app with the webcam feed in them (camera 1 window).

I simplified the scene massively - recorded video and added logs. Hope this helps.
https://streamable.com/qyzzsf
https://obsproject.com/logs/S_v3XpejpPJaHB-R
