### ISSUE TITLE
Possible performance regression with 21H1

### ISSUE THREAD

**Issue by icedterminal** [obsproject/obs-studio#4803]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0

### OBS Studio Log URL

https://obsproject.com/logs/ff40GlX6Pve58XV0

### Expected Behavior

FPS to remain consistent with OBS opened, *not* doing anything.

### Current Behavior

FPS does not remain consistent with OBS opened, *not* doing anything.

### Steps to Reproduce

1. Launch a game that only works with Window capture.
2. Enable Window capture for that game.
3. Observe.

### Anything else we should know?

21H1 was installed cleanly on May 12th 2021. I don't do in-place upgrades for the yearly releases. [dxdiag](https://gist.github.com/icedterminal/773712fa892b1473a5586356bc6c0108).
All drivers on this system are up-to-date. Graphics, audio, and chipset.

Here's what I've concluded:
- Revolves around using Window capture (WGC). Game capture is unaffected and operates buttery smooth no matter the configuration. Certain games can only use Window capture as Game capture will crash it (Forza series).
- You *do not* have to be recording or streaming. Simply opening OBS with Window capture enabled is enough to degrade performance. You don't even have to close/open OBS. Just toggle the Window capture to the same effect. [Demo.](https://youtu.be/cZOcRnGSrT4)
- **FPS unlocked:** Remains consistent. Though slight stutter has been introduced. There is little to no overall FPS loss (~%1 to ~%2). Screen tearing is extensive. [FH4 demo.](https://youtu.be/p2jV6TPpSAs)
- **60 FPS, Vsync OFF:** Remains consistent. Though slight stutter has been introduced. There is little to no overall FPS loss (~%1 to ~%2). Screen tearing is moderate.
- **60 FPS, Vsync ON:** Drops to 50 on average, but ranges from 40 to 60. It is widely inconsistent. Dips to sub 30 at times. Consistent stutter, feels like you're lagging. Screen tearing absent. [FH4 demo](https://youtu.be/3L9LwxLU5kw) and [FM7 demo.](https://youtu.be/FK97Ikr5Qcc)
- While it's not as noticeable, play a YouTube video with constant motion and use Window capture. Minor stutter is introduced.

Things I have tried:
- Game Mode has zero effect. I have tried both ON and OFF.
- OBS has been run as admin with above normal and high priority.
- The three most recent *stable* builds.

I am unsure who entirely is to blame here. I am leaning more towards Windows as that's the only major change. But I cannot say for certain. I don't use OBS often. The last time I used it was April 26th with Forza Horizon 4 (on 20H2) and that recording is flaw free. At present, this problem makes gameplay nearly impossible for accuracy.

---

## Edit
Display Capture is affected too. Though does not dip excessively into the 30-40 FPS range. [FH4 demo.](https://youtu.be/JxzX75-Hm3U). This was actually tested using 466.27.

I looked over a previous backup to retrieve information pertaining to 20H2 drivers:
- audio [6.0.9155.1](https://github.com/AlanFinotty/AAFDCHDriverMod/releases/tag/6.0.9155.1) 
- graphics [466.27](https://www.nvidia.com/download/driverResults.aspx/174662/en-us)

21H1 has:
- audio [6.0.9160.1](https://github.com/AlanFinotty/AAFDCHDriverMod/releases/tag/6.0.9160.1)
- graphics [466.47](https://www.nvidia.com/download/driverResults.aspx/175535/en-us)

Both Windows builds use the same chipset drivers as there is no update. Uninstalled audio and graphics drivers with clean removal using DDU. Installed the driver versions last used with 20H2. No difference was made. Both games ran poorly.

---

## Edit 2

Figured it out. I have time to spare, backups to use, and lots of free space for Multiple concurrent installs.

As I said earlier I don’t use OBS often and just happened to use it after all updates were applied. the optional cumulative update preview does it. At least pertaining to my current system configuration. `.985` operates fine. Once updated to `.1023` the graphics take a hit. Notably, CPU x264 Display and Window capture is unaffected just like GPU Game capture. Only the GPU Display and Window capture takes a hit. GameBar recording was also affected since it leverages the GPU.

To alleviate the problem, at least for me, remove chipset, graphics and audio drivers. Clean boot by disabling all third party (msconfig). Install the cumulative update. Made sure the policy to exclude drivers from WU is enabled. Install drivers. Enable all third party.

I was able to repeat this twice to confirm. Whether or not a clean boot and removing all drivers is necessary, I do not know entirely. I was more so wanting to eliminate all potential problems. Performance has been restored. It could be noted this update *might* cause problems depending on the system configuration. I’m probably a 0.0001% chance in the grand scheme of things. Apologies. I’ll mark this is as closed since OBS is not to blame at all.

**Comment by mufunyo** [comment]
Can confirm that KB5003214 completely broke GPU performance on my system. Had to uninstall the update and reinstall my GPU drivers for it to return to normal.

**Comment by icedterminal** [comment]
Now I'm just mad. False alarm on fixing it. The issue came back on 21H1. For comparison here is 20H2 (`19042.985`).

- [dxdiag](https://gist.github.com/icedterminal/fc0bcd7a663f5c7fcb37cac0a2034243)
- [FH4 demo](https://youtu.be/KFFw19H9XJU)
- [obs log](https://obsproject.com/logs/2KjQCff7Tg72JzR_)

It *appeared* KB5003214 (`19043.1023`) was the culprit but that was not the case after all. On build `19043.985`, after being on over a day, the issue manifested. I don't know what has broken OBS performance.

**Comment by icedterminal** [comment]
Just updating with notes. 21H1 `19043.1052` with the following drivers...

- audio 6.0.9160.1
- graphics 471.11

still has issues with Display and Window capture.

Meanwhile, 20H2 `19042.1052` with the following drivers...

- audio 6.0.9160.1
- graphics 471.11

has no issues. I'll skip 21H1 entirely and test Windows 11 when released before I jump from 20H2. Seeing as how I am the only one to report this problem, I am unsure if this is worth keeping open for further investigation.

**Comment by icedterminal** [comment]
I found the problem!

When OBS is open the GPU changes states from P0 to P2. This doesn't happen with 20H2 for some reason. Only 21H1.

**Comment by Squall-Leonhart** [comment]
> When OBS is open the GPU changes states from P0 to P2. This doesn't happen with 20H2 for some reason. Only 21H1.

Yes it does.

**Comment by icedterminal** [comment]
> Yes it does.
> Always has.

What you're saying and what I see are two different things.

Also, I just found this: https://obsproject.com/forum/threads/starting-obs-makes-my-vram-clock-below-average.137187/

According to this developer, this is not normal behavior for OBS and the NVidia driver. Which I did not experience until I upgrading to 21H1
