### ISSUE TITLE
obs crashes after being unfocused/in background on Wayland

### ISSUE THREAD

**Issue by RavenOchlich** [obsproject/obs-studio#4811]
### Operating System Info

Other

### Other OS

Arch Linux using Sway (Wayland)

### OBS Studio Version

27.0.0

### OBS Studio Log URL

https://obsproject.com/logs/8NDTcgNujVQmVfam

### Expected Behavior

Obs continues to record and doesn't crash.

### Current Behavior

Obs crashes when it gets refocused after beeing in an not focused workspace for around 10 minutes. The log file doesn't capture an error.  The terminal output after the crash is: `Wayland connection broke. Did the Wayland compositor die?`

### Steps to Reproduce

1. Start OBS and record anything
2. Move the workspace with obs in the background (workspace not displayed)
3. Refocus Workspace / obs
4. Obs instantly crashes

**Comment by kkartaltepe** [comment]
Duplicate #4295
