### ISSUE TITLE
VT h264 Apple Hardware Cder

### ISSUE THREAD

**Issue by kvzonbr** [obsproject/obs-studio#4818]
### Operating System Info

macOS 11.4

### OBS Studio Version

27.0.0

### OBS Studio Log URL

https://github.com/kvzonbr/reports/blob/main/2021-06-05%2017-59-14.txt

### Expected Behavior

transmit image on stream

### Current Behavior

on chosing hardware coding for apple m1 macbook air it doesn't show image on transmition. preview works correctly.

### Steps to Reproduce

1.options -> output -> advanced -> coder -> apple hardware VT H264 
2.start transmition
3.
...

**Comment by WizardCM** [comment]
This sounds like a duplicate of #4670 - could you check if following some of the suggested steps there fix the issue for you?

**Comment by kvzonbr** [comment]
thanks a lot, the solution was as mentioned on #4670 this happened on twitch just as was on facebook.
