### ISSUE TITLE
OBS captures wrong audio.

### ISSUE THREAD

**Issue by Krutonium** [obsproject/obs-studio#4824]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

Git

### OBS Studio Version (Other)

27.0.0.r11.g94404a4d2

### OBS Studio Log URL

https://obsproject.com/logs/O7Mj5MVhQkhynaPc

### Expected Behavior

OBS should capture Desktop Audio and Microphone

### Current Behavior

OBS captures the Mic as both Desktop and Mic inputs - The desktop cannot be heard. Using qjackctl (I'm using pipewire) I can visually confirm that the mic is connected to both inputs. Pipewire also sees the request as one for mono audio, not stereo, so reconnecting it manually does not correct provide stereo sound. 

### Steps to Reproduce

1. Install obs-studio-git
2. Try to set up audio
3. Record & Listen
...

### Anything else we should know?

I'm running on Wayland with Pipewire on an up to date installation of Arch.

**Comment by WizardCM** [comment]
According to your log file, Desktop Audio pulls from:

```
08:09:37 AM.853: pulse-input: Server name: 'PulseAudio (on PipeWire 0.3.29) 14.0.0'
08:09:37 AM.853: pulse-input: Audio format: s32le, 48000 Hz, 2 channels
08:09:37 AM.853: pulse-input: Started recording from 'alsa_output.pci-0000_20_00.3.analog-stereo.monitor'
08:09:37 AM.853: [Loaded global audio device]: 'Desktop Audio'
```

And your mic pulls from:
```
08:09:37 AM.853: pulse-input: Server name: 'PulseAudio (on PipeWire 0.3.29) 14.0.0'
08:09:37 AM.854: pulse-input: Audio format: s16le, 48000 Hz, 1 channels
08:09:37 AM.854: pulse-input: Started recording from 'alsa_input.usb-BLUE_MICROPHONE_Blue_Snowball_AYM_2018_08_28_43565-00.mono-fallback'
08:09:37 AM.854: [Loaded global audio device]: 'Mic/Aux'
08:09:37 AM.854:     - filter: 'Noise Suppression' (noise_suppress_filter_v2)
```

How are you verifying that the desktop audio is not captured? Do both bars in the Audio Mixer move exactly the same way?

**Comment by Krutonium** [comment]
Yes, I have verified that, and also verified that reconnecting it via qjackctl works, but in mono instead of stereo like obs is suggesting.

**Comment by niarbeht** [comment]
> Yes, they do move together in almost sync (one seems louder than the other), and also verified that reconnecting it via qjackctl works, but in mono instead of stereo like obs is suggesting.
> 
> I verified it by recording a clip of myself with music playing, and speaking.
> 
> I heard myself twice and no music.

I'm noticing the same issue.  Also on Arch Linux.  In my case, I've also tried disabled compiling with pipewire and wayland support and it still displays the issue.  I'll try rolling back to a 26.x version next.

**Comment by Krutonium** [comment]
I found that the audio did work on OBS 26.X until I upgraded to the git version (Because I need some features not available on 26). I wonder what the difference is.

**Comment by Krutonium** [comment]
I bypassed this issue for myself by building OBS without Pulseaudio support and manually capturing my mic with ALSA and my Speakers using Jack, at least for the time being.

**Comment by Krutonium** [comment]
I got an update to pipewire today that seems to have fixed this issue.

**Comment by WizardCM** [comment]
Thanks for the update!

**Comment by Krutonium** [comment]
No Problem, if the issue comes back I'll re-open the issue.

**Comment by mibmo** [comment]
I'm having this issue right now, also using Arch & Pipewire.
