### ISSUE TITLE
undefined reference to `gs_create_texture_file_data2' when building libobs against ImageMagick

### ISSUE THREAD

**Issue by invakid404** [obsproject/obs-studio#4827]
### Operating System Info

Other

### Other OS

Funtoo Linux 1.4

### OBS Studio Version

27.0.0

### OBS Studio Log URL

https://pastebin.com/gQXGf6wM

### Expected Behavior

OBS Studio builds and works fine.

### Current Behavior

OBS Studio fails to build due to a linker error.

### Steps to Reproduce

1. Configure libobs with LIBOBS_PREFER_IMAGEMAGICK=1
2. Build fails

### Anything else we should know?

My presumption is this is caused by the fact that there's no `gs_create_texture_file_data2` in `libobs/graphics/graphics-magick.c`, as there is in `libobs/graphics/graphics-ffmpeg.c`.

Note: related build log is in pastebin.

**Comment by Chiitoo** [comment]
Since it looks like imagemagick support is going away [1], I don't imagine it makes much sense to put time into actually fixing this...

1. https://github.com/obsproject/obs-studio/pull/4560#issuecomment-826345608

**Comment by invakid404** [comment]
Well, that is enough of an answer for me. Considering imagemagick support is going away, then it makes sense to force disable it in our ebuild then. Thanks!
