### ISSUE TITLE
OBS starts capturing wrong audio(mic) when default

### ISSUE THREAD

**Issue by ShrirajHegde** [obsproject/obs-studio#4828]
### Operating System Info

GNU/Linux

### Other OS

Fedora Linux, 34

### OBS Studio Version

27.0.0

### OBS Studio Log URL

https://obsproject.com/logs/W31HeLFlcHaEl0id

### Expected Behavior

The audio source is selected as with device as `Default`

The recording starts with `bluez_output.5C_EB_68_74_02_19.a2dp-sink.monitor` (which is a bluetooth headset).

On Bluetooth disconnect, bluez input stops working and default is switched to `alsa_output.pci-0000_00_1f.3.analog-stereo.monitor` since the device is selected as defaulted and default device is switched when Bluetooth connects/disconnects.

### Current Behavior

The audio recording gets stuck on initial input and recording goes silent

### Steps to Reproduce

1. Launch  OBS while bluetooth headset is connected
2. Start Recording with bluetooth headset on
3.  Turn off/Disconnect bluetooth headset
4.  (audio capture stops when default device gets changed)
...

### Anything else we should know?

Bluetooth headset was disconnected while recording 

```
11:01:51 PM IST.817: ==== Recording Start ===============================================
11:01:51 PM IST.817: [ffmpeg muxer: 'adv_file_output'] Writing file '/media/srj/Shriraj_Storage/Others/Recording_Folder/2021-06-06_23-01-50.mkv'...
11:02:07 PM IST.386: [ffmpeg muxer: 'adv_file_output'] Output of file '/media/srj/Shriraj_Storage/Others/Recording_Folder/2021-06-06_23-01-50.mkv' stopped
11:02:07 PM IST.386: Output 'adv_file_output': stopping
11:02:07 PM IST.386: Output 'adv_file_output': Total frames output: 276
11:02:07 PM IST.386: Output 'adv_file_output': Total drawn frames: 311
11:02:07 PM IST.387: ==== Recording Stop ================================================
```
somewhere in between this, but the audio input never gets switched.  To fix the issue, I have to go to device selection and click on default which solves the issue.

**Comment by kkartaltepe** [comment]
Device switching is not implemented in pulseaudio, or on other platforms (maybe someone added this for windows recently I cannot remember). So not a bug but if anyone is interested they could implement it.

And at least on arch linux with a recent pipewire backend, audio switches automatically back and forth as bluetooth connects and disconnects.

**Comment by ShrirajHegde** [comment]
Fedora 34 had pipewire. But now it seems to have been fixed on fedora 35 (pipewire)
