### ISSUE TITLE
Failed to initalize video (graphics module not found)

### ISSUE THREAD

**Issue by CourteousGeek** [obsproject/obs-studio#4829]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

27.0.0

### OBS Studio Log URL

02:04:54 PM.879: CPU Name: Intel(R) Xeon(R) CPU           E5450  @ 3.00GHz 02:04:54 PM.879: CPU Speed: 2670.000MHz 02:04:54 PM.879: Physical Cores: 4, Logical Cores: 4 02:04:54 PM.879: Physical Memory: 7954MB Total, 5446MB Free 02:04:54 PM.879: Kernel Version: Linux 5.12.9-arch1-1 02:04:54 PM.879: Distribution: "Arch Linux" Unknown 02:04:54 PM.879: Session Type: x11 02:04:54 PM.879: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.11 02:04:54 PM.880: Portable mode: false 02:04:54 PM.950: OBS 27.0.0-1 (linux) 02:04:54 PM.950: --------------------------------- 02:04:54 PM.951: --------------------------------- 02:04:54 PM.951: audio settings reset: 02:04:54 PM.951: 	samples per sec: 48000 02:04:54 PM.951: 	speakers:        2 02:04:54 PM.954: os_dlopen(libobs-opengl.so.0->libobs-opengl.so.0): /usr/lib/libobs-opengl.so.0: undefined symbol: eglCreateImage 02:04:54 PM.954:  02:04:54 PM.954: Failed to initialize video:  Graphics module not found 02:04:56 PM.596: Freeing OBS context data 02:04:56 PM.607: == Profiler Results ============================= 02:04:56 PM.607: run_program_init: 1915.26 ms 02:04:56 PM.607:  ┣OBSApp::AppInit: 13.288 ms 02:04:56 PM.607:  ┃ ┗OBSApp::InitLocale: 1.314 ms 02:04:56 PM.607:  ┗OBSApp::OBSInit: 75.113 ms 02:04:56 PM.607:    ┣obs_startup: 1.087 ms 02:04:56 PM.607:    ┗OBSBasic::OBSInit: 3.686 ms 02:04:56 PM.607:      ┣OBSBasic::InitBasicConfig: 0.794 ms 02:04:56 PM.607:      ┣OBSBasic::ResetAudio: 0.219 ms 02:04:56 PM.607:      ┗OBSBasic::ResetVideo: 2.625 ms 02:04:56 PM.607: obs_hotkey_thread(25 ms): min=0.154 ms, median=0.165 ms, max=24.27 ms, 99th percentile=24.27 ms, 100% below 25 ms 02:04:56 PM.607: audio_thread(Audio): min=0.02 ms, median=0.022 ms, max=0.064 ms, 99th percentile=0.064 ms 02:04:56 PM.607: ================================================= 02:04:56 PM.607: == Profiler Time Between Calls ================== 02:04:56 PM.607: obs_hotkey_thread(25 ms): min=25.188 ms, median=25.227 ms, max=49.332 ms, 90.625% within ±2% of 25 ms (0% lower, 9.375% higher) 02:04:56 PM.607: ================================================= 02:04:56 PM.608: Number of memory leaks: 182

### Expected Behavior

02:04:54 PM.879: CPU Name: Intel(R) Xeon(R) CPU           E5450  @ 3.00GHz
02:04:54 PM.879: CPU Speed: 2670.000MHz
02:04:54 PM.879: Physical Cores: 4, Logical Cores: 4
02:04:54 PM.879: Physical Memory: 7954MB Total, 5446MB Free
02:04:54 PM.879: Kernel Version: Linux 5.12.9-arch1-1
02:04:54 PM.879: Distribution: "Arch Linux" Unknown
02:04:54 PM.879: Session Type: x11
02:04:54 PM.879: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.11
02:04:54 PM.880: Portable mode: false
02:04:54 PM.950: OBS 27.0.0-1 (linux)
02:04:54 PM.950: ---------------------------------
02:04:54 PM.951: ---------------------------------
02:04:54 PM.951: audio settings reset:
02:04:54 PM.951: 	samples per sec: 48000
02:04:54 PM.951: 	speakers:        2
02:04:54 PM.954: os_dlopen(libobs-opengl.so.0->libobs-opengl.so.0): /usr/lib/libobs-opengl.so.0: undefined symbol: eglCreateImage
02:04:54 PM.954: 
02:04:54 PM.954: Failed to initialize video:  Graphics module not found
02:04:56 PM.596: Freeing OBS context data
02:04:56 PM.607: == Profiler Results =============================
02:04:56 PM.607: run_program_init: 1915.26 ms
02:04:56 PM.607:  ┣OBSApp::AppInit: 13.288 ms
02:04:56 PM.607:  ┃ ┗OBSApp::InitLocale: 1.314 ms
02:04:56 PM.607:  ┗OBSApp::OBSInit: 75.113 ms
02:04:56 PM.607:    ┣obs_startup: 1.087 ms
02:04:56 PM.607:    ┗OBSBasic::OBSInit: 3.686 ms
02:04:56 PM.607:      ┣OBSBasic::InitBasicConfig: 0.794 ms
02:04:56 PM.607:      ┣OBSBasic::ResetAudio: 0.219 ms
02:04:56 PM.607:      ┗OBSBasic::ResetVideo: 2.625 ms
02:04:56 PM.607: obs_hotkey_thread(25 ms): min=0.154 ms, median=0.165 ms, max=24.27 ms, 99th percentile=24.27 ms, 100% below 25 ms
02:04:56 PM.607: audio_thread(Audio): min=0.02 ms, median=0.022 ms, max=0.064 ms, 99th percentile=0.064 ms
02:04:56 PM.607: =================================================
02:04:56 PM.607: == Profiler Time Between Calls ==================
02:04:56 PM.607: obs_hotkey_thread(25 ms): min=25.188 ms, median=25.227 ms, max=49.332 ms, 90.625% within ±2% of 25 ms (0% lower, 9.375% higher)
02:04:56 PM.607: =================================================
02:04:56 PM.608: Number of memory leaks: 182

### Current Behavior

02:04:54 PM.879: CPU Name: Intel(R) Xeon(R) CPU           E5450  @ 3.00GHz
02:04:54 PM.879: CPU Speed: 2670.000MHz
02:04:54 PM.879: Physical Cores: 4, Logical Cores: 4
02:04:54 PM.879: Physical Memory: 7954MB Total, 5446MB Free
02:04:54 PM.879: Kernel Version: Linux 5.12.9-arch1-1
02:04:54 PM.879: Distribution: "Arch Linux" Unknown
02:04:54 PM.879: Session Type: x11
02:04:54 PM.879: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.11
02:04:54 PM.880: Portable mode: false
02:04:54 PM.950: OBS 27.0.0-1 (linux)
02:04:54 PM.950: ---------------------------------
02:04:54 PM.951: ---------------------------------
02:04:54 PM.951: audio settings reset:
02:04:54 PM.951: 	samples per sec: 48000
02:04:54 PM.951: 	speakers:        2
02:04:54 PM.954: os_dlopen(libobs-opengl.so.0->libobs-opengl.so.0): /usr/lib/libobs-opengl.so.0: undefined symbol: eglCreateImage
02:04:54 PM.954: 
02:04:54 PM.954: Failed to initialize video:  Graphics module not found
02:04:56 PM.596: Freeing OBS context data
02:04:56 PM.607: == Profiler Results =============================
02:04:56 PM.607: run_program_init: 1915.26 ms
02:04:56 PM.607:  ┣OBSApp::AppInit: 13.288 ms
02:04:56 PM.607:  ┃ ┗OBSApp::InitLocale: 1.314 ms
02:04:56 PM.607:  ┗OBSApp::OBSInit: 75.113 ms
02:04:56 PM.607:    ┣obs_startup: 1.087 ms
02:04:56 PM.607:    ┗OBSBasic::OBSInit: 3.686 ms
02:04:56 PM.607:      ┣OBSBasic::InitBasicConfig: 0.794 ms
02:04:56 PM.607:      ┣OBSBasic::ResetAudio: 0.219 ms
02:04:56 PM.607:      ┗OBSBasic::ResetVideo: 2.625 ms
02:04:56 PM.607: obs_hotkey_thread(25 ms): min=0.154 ms, median=0.165 ms, max=24.27 ms, 99th percentile=24.27 ms, 100% below 25 ms
02:04:56 PM.607: audio_thread(Audio): min=0.02 ms, median=0.022 ms, max=0.064 ms, 99th percentile=0.064 ms
02:04:56 PM.607: =================================================
02:04:56 PM.607: == Profiler Time Between Calls ==================
02:04:56 PM.607: obs_hotkey_thread(25 ms): min=25.188 ms, median=25.227 ms, max=49.332 ms, 90.625% within ±2% of 25 ms (0% lower, 9.375% higher)
02:04:56 PM.607: =================================================
02:04:56 PM.608: Number of memory leaks: 182

### Steps to Reproduce

1.
2.
3.
...

### Anything else we should know?

02:04:54 PM.879: CPU Name: Intel(R) Xeon(R) CPU           E5450  @ 3.00GHz
02:04:54 PM.879: CPU Speed: 2670.000MHz
02:04:54 PM.879: Physical Cores: 4, Logical Cores: 4
02:04:54 PM.879: Physical Memory: 7954MB Total, 5446MB Free
02:04:54 PM.879: Kernel Version: Linux 5.12.9-arch1-1
02:04:54 PM.879: Distribution: "Arch Linux" Unknown
02:04:54 PM.879: Session Type: x11
02:04:54 PM.879: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.11
02:04:54 PM.880: Portable mode: false
02:04:54 PM.950: OBS 27.0.0-1 (linux)
02:04:54 PM.950: ---------------------------------
02:04:54 PM.951: ---------------------------------
02:04:54 PM.951: audio settings reset:
02:04:54 PM.951: 	samples per sec: 48000
02:04:54 PM.951: 	speakers:        2
02:04:54 PM.954: os_dlopen(libobs-opengl.so.0->libobs-opengl.so.0): /usr/lib/libobs-opengl.so.0: undefined symbol: eglCreateImage
02:04:54 PM.954: 
02:04:54 PM.954: Failed to initialize video:  Graphics module not found
02:04:56 PM.596: Freeing OBS context data
02:04:56 PM.607: == Profiler Results =============================
02:04:56 PM.607: run_program_init: 1915.26 ms
02:04:56 PM.607:  ┣OBSApp::AppInit: 13.288 ms
02:04:56 PM.607:  ┃ ┗OBSApp::InitLocale: 1.314 ms
02:04:56 PM.607:  ┗OBSApp::OBSInit: 75.113 ms
02:04:56 PM.607:    ┣obs_startup: 1.087 ms
02:04:56 PM.607:    ┗OBSBasic::OBSInit: 3.686 ms
02:04:56 PM.607:      ┣OBSBasic::InitBasicConfig: 0.794 ms
02:04:56 PM.607:      ┣OBSBasic::ResetAudio: 0.219 ms
02:04:56 PM.607:      ┗OBSBasic::ResetVideo: 2.625 ms
02:04:56 PM.607: obs_hotkey_thread(25 ms): min=0.154 ms, median=0.165 ms, max=24.27 ms, 99th percentile=24.27 ms, 100% below 25 ms
02:04:56 PM.607: audio_thread(Audio): min=0.02 ms, median=0.022 ms, max=0.064 ms, 99th percentile=0.064 ms
02:04:56 PM.607: =================================================
02:04:56 PM.607: == Profiler Time Between Calls ==================
02:04:56 PM.607: obs_hotkey_thread(25 ms): min=25.188 ms, median=25.227 ms, max=49.332 ms, 90.625% within ±2% of 25 ms (0% lower, 9.375% higher)
02:04:56 PM.607: =================================================
02:04:56 PM.608: Number of memory leaks: 182

**Comment by notr1ch** [comment]
Arch Linux is not an officially supported platform, please contact your packager for support. Looks like you have a broken opengl installation.
