### ISSUE TITLE
Live audio Stutter when VOD Track enabled

### ISSUE THREAD

**Issue by meza** [obsproject/obs-studio#4834]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0

### OBS Studio Log URL

https://obsproject.com/logs/WL1Ser-0f5dVPmRR

### Expected Behavior

Audio working fine for both LIVE and VOD

### Current Behavior

When I use a VOD track than the stream audience hears stuttering/crackling of the audio.
It doesn't show up on the VOD itself, only during live

As soon as I turned off the VOD track, the stuttering stopped.

### Steps to Reproduce

1. Turn on the vod track feature
2. Stream live

### Anything else we should know?

I've been happily using the VOD track feature since it was introduced.
After upgrading to 27.0, everything was fine for the first 3 hours of the stream after the update and then suddenly it gave up. The issue persists since no matter if I restart my computer, delete cashes, etc.

**Comment by Fenrirthviti** [comment]
Is this still an issue? There are quite a few errors and warnings in your log, many of which seem to be coming from third-party plugins.

Can you test this in a clean portable install of OBS, with no third-party plugins, and confirm if this is still an issue for you?

**Comment by gxalpha** [comment]
Closing as there hasn't been a response so far.

If this still happens in the conditions outlined by Fenrir above, please leave a comment and we can look at re-opening this issue again.
