### ISSUE TITLE
Push-to-talk no longer functions correctly

### ISSUE THREAD

**Issue by JoshStrobl** [obsproject/obs-studio#4843]
### Operating System Info

Other

### Other OS

Solus

### OBS Studio Version

27.0.0

### OBS Studio Log URL

https://obsproject.com/logs/6tCS6jlZTFHZFYg0

### Expected Behavior

In OBS Studio releases prior to 27.0, I could use various hotkeys such as my Right Control or Mouse 6 (DPI typically) for push-to-talk on the default Audio Input Capture (Pulseaudio).

### Current Behavior

In OBS Studio 27.0, I am no longer able to use push-to-talk and have had to temporarily switch to constant transmit with various filters like a limiter and noise gat.

### Steps to Reproduce

1. Open the OBS Studio Settings window
2. Under Audio, choose Enable Push-to-talk on Audio Input Capture (Pulseaudio)
3. Under Hotkeys, type "push" to filter irrelevant items, and press a relevant key such as Right Control or a mouse button
4. Click OK to apply the settings and close the window.
5. Click off the window, press relevant key / button, and notice missing audio input in any scene which has it as a source (you may need to add it if you have a fresh configuration, I am not sure).

### Anything else we should know?

This is under X11 and Pulseaudio, as opposed to Wayland and Pipewire. Package build instructions are at https://dev.getsol.us/source/obs-studio/browse/master/package.yml, as you can see we only apply one patch from related to CMake, otherwise it is stock OBS Studio.

**Comment by quickishfm** [comment]
I can reproduce this problem. I'm using Arch Linux and upgraded to OBS v27 and my Mouse4 button no longer works as push to talk. Looking at the sound bar when I press the PTT button, it goes high for almost a tenth of a second then quickly fades to zero, even when still pressed. Downgrading to v26 from pacman cache works and the issue is not here on this version.

After mapping PTT to the Q key for testing (in v27) it _does_ work, so I think it's only mouse buttons. Turning off PTT for the audio input device works too, though then it's always recording so I prefer to stick to v26 and working PTT for now.

**Comment by Moondarker** [comment]
Can confirm, mouse PTT only works after a downgrade to v16.1.2

**Comment by JoshStrobl** [comment]
Still broken in 27.1.1 :\

**Comment by garpu** [comment]
For what it's worth, it's only when I use a mouse button (like mouse 4 or 5) that push-to-talk doesn't function.  If I use a keyboard command (like one of the meta keys) it's fine. I'm on slackware-current, obs 27.1.3. Logitech mouse.

**Comment by CAG2Mark** [comment]
Can confirm on Arch with OBS 27.1.3, KDE Plasma (X11), and Pipewire. Mapping to keyboard works fine.

**Comment by thennothinghappened** [comment]
Does anyone have an idea why this happens? I use a mouse key so that I can push to talk with Discord at the same time as that's my key on there, and clearly Discord is picking it up correctly, just not OBS.

**Comment by lucasmr** [comment]
I still have this issue in 27.2.4, exactly as described.

**Comment by garpu** [comment]
I'm still having this issue in 28.0.3.  I thought it had been fixed?

**Comment by egrain** [comment]
Updated to 29.0.2-2 on arch, and now push to talk on mouse4 and 5 buttons stopped working. Worked fine for me in 28... though.
Same behavior that quickishfm had:  Looking at the sound bar when I press the PTT button, it goes high for almost a tenth of a second then quickly fades to zero, even when still pressed.
