### ISSUE TITLE
Hotkeys don't work in Wayland session with version 27.0

### ISSUE THREAD

**Issue by Chill3dOut** [obsproject/obs-studio#4844]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

27.0.0

### OBS Studio Log URL

https://obsproject.com/logs/FrhvRudojSfg70C8

### Expected Behavior

In the Hotkeys settings, register my key combinations for using different features and controls.

### Current Behavior

Nothing registers.

### Steps to Reproduce

1. Launch OBS.
2. Open Settings.
3. Go to Hotkeys.
4. Try to input the desired key combination as usual.
5. Nothing happens.
...

### Anything else we should know?

Currently running AUR package obs-studio-browser [https://aur.archlinux.org/packages/obs-studio-browser/](url)

**Comment by kkartaltepe** [comment]
wayland does not allow you to register arbitrary hotkeys (at least last I checked). And if there are compositor specific extensions for this, then they are not implemented by Qt which is our platform layer.

**Comment by GeorgesStavracas** [comment]
I'd like to add to @kkartaltepe's comment by saying that there are conversations happening on how to best implement this. It's not an easy problem to solve since the "tradition" behind Wayland protocols strongly discourage giving applications raw access to events.

**Comment by Chill3dOut** [comment]
Well... new to coding and new to Wayland... just wanted to be on the bleeding edge... Guess I'll keep using the awesome OBS in X11 until Wayland is mature enough.

Thank you for taking the time to explain.

**Comment by machitgarha** [comment]
Can't it be done using [`org.freedesktop.portal.RemoteDesktop` protocol](https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-org.freedesktop.portal.RemoteDesktop), just like how screencast is implemented?

**Comment by kkartaltepe** [comment]
Not necessarily, it may be the case that remote desktoping into your own system will reuse the existing session and we might be able to avoid accidentally consuming all of your input or multiplying all of your input.

But no, a remote desktop api is not a hotkey api, if you want to write an implementation of it be my guest but I imagine no one on our side would be interested in maintaining such nor would I imagine flatpak people be particularly jazzed. (Nor do I think it would actually work across compositors)

**Comment by MoonfirePDX** [comment]
Late last year, a new global shortcut protocol was added to xdg-desktop-portal, [org.freedesktop.portal.GlobalShortcuts](https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.GlobalShortcuts). Implementing this in OBS should properly resolve both this issue and #4992.

**Comment by v4u6h4n** [comment]
Are there any updates regarding plans to implement global shortcuts in Wayland? It's already a bit concerning its not supported when Gnome runs Wayland by default, but now KDE is following suite in with v6.

**Comment by GeorgesStavracas** [comment]
There has been no update since the last comment. Please avoid asking for status updates in issues, especially closed ones, usually the lack of activity is an indicator of the level of attention it's receiving.

**Comment by v4u6h4n** [comment]
Hey there, thanks for taking the time to respond.

I agree with your sentiment that the general activity in an issue is an decent indicator of the attention it is recieving, and I understand if there is not currently any interest in addressing this issue as such matters are at the discretion of those who are generous enough to contribute to this project.

To clarify, what I'm actually enquiring about is if there are plans to update the _status_ of this issue to open, instead of closed, as this status is an indicator of whether there is an intention to fix/maintain what is not only a critical, but also an advertised feature.

**Comment by Aviana** [comment]
The xdg-desktop-portal is not able to provide a suitable fix to make hotkeys work in Wayland. OBS changes its hotkeys during runtime (adding / removing scenes etc). The [official documentation](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.GlobalShortcuts.html) however calls for a dialog to be shown every time bindings are submitted. This could either be very annoying when trying to set up multiple scenes or there would have to be a quirk in OBS just for Wayland to hold off any changes until they are manually submitted. Neither seems to be acceptable to me. I have submitted this issue [to their tracker](https://github.com/flatpak/xdg-desktop-portal/issues/1101).

A better alternative seems to be the [action binder Wayland protocol](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/216).

**Comment by orowith2os** [comment]
The action binder protocol is not an alternative (at least for most applications), but an underlying implementation meant to be utilized to build a portal on top of (and for other privileged clients to use in a compositor). Do not use it in clients without knowing it will work everywhere, including GNOME and KDE, in a sandboxed environment (where, if that protocol is even implemented, will likely be restricted from sandboxed clients).
