### ISSUE TITLE
OBS Studio Cannot Change Aspect Ratio 16:9  to 9:16 

### ISSUE THREAD

**Issue by Fiziey2020** [obsproject/obs-studio#4849]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0

### OBS Studio Log URL

no

### OBS Studio Crash Log URL

no

### Expected Behavior

I hope can change any size Ratio

Thank You

### Current Behavior

OBS Studio Cannot Change Aspect Ratio 16:9 to 9:16 , before this version ok.

### Steps to Reproduce

1.
2.
3.
...

### Anything else we should know?

ok

**Comment by ElectronicWar** [comment]
We do not use GitHub Issues for support questions. In this case, this is not an actionable bug report with reliable reproduction steps.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
