### ISSUE TITLE
Windows Captures Do Not Work For Browsers 

### ISSUE THREAD

**Issue by tmrdev** [obsproject/obs-studio#4853]
### Operating System Info

macOS 11.4

### OBS Studio Version

27.0.0

### OBS Studio Log URL

https://obsproject.com/logs/bBHuIckzJIMArcR0

### Expected Behavior

I expected that when I enable Window Capture that it would show all tabs open in Chrome or any other Browser

### Current Behavior

When I create a Window Capture and try to select Chrome or any browser (Safari, Firefox, etc...) there are no windows to select.  Chrome is listed with two entries (I have two Chrome windows open with a few tabs in each) and null appears at. the end. So OBS is unable to recognize tabs in Chrome?

### Steps to Reproduce

1. Add Window Capture To A Scene
2.Double click the Window Capture
3.Try to select a tab within a browser window
...

**Comment by notr1ch** [comment]
Tabs are not individual applications. You would need to move them to their own window as they are not rendered when not visible. In future please use Discord or forums for support questions.

**Comment by tmrdev** [comment]
I fixed the issue.  It's related to Security/Privacy System Settings in Big Sur.  I had to give access to OBS Studio. Both Apple and 3rd party developers need to do a better job at explaining these issues.  I should have been notified at the System or App level that these permissions need to be set.
