### ISSUE TITLE
No PipeWire Screen Capture Options on Latest OBS Studio 27.0.0

### ISSUE THREAD

**Issue by spsrijan** [obsproject/obs-studio#4857]
### Operating System Info

Ubuntu 21.04

### OBS Studio Version

27.0.0

### OBS Studio Log URL

https://obsproject.com/logs/LwosNbbg-20VuROj

### Expected Behavior

As stated in the OBS Studio 27.0.0, we should have a Screen Capture(PipeWire) option for Wayland.

### Current Behavior

Only screen capture option available is the old Screen Capure(XSHM) which doen't work on Wayland.

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/48404712/121503439-e4110c80-ca02-11eb-8e96-9571bc09f651.png)

### Anything else we should know?

Downloaded from official PPA.

**Comment by tytan652** [comment]
Under GNOME, Qt doesn't launch by default with Wayland, you will need to launch OBS in a terminal with this command:
```sh
QT_QPA_PLATFORM=wayland obs
```
If you want more explanations you can quiet find them [here](https://github.com/obsproject/obs-studio/pull/4496)

**Comment by WizardCM** [comment]
As @tytan652 has mentioned, if "Screen Capture (XSHM)" is in the list, OBS is not currently running in Wayland mode.

Launch it with the additional environment variable.

**Comment by spsrijan** [comment]
Thanks
