### ISSUE TITLE
Display Resolution Detected Incorrectly

### ISSUE THREAD

**Issue by RoyalReject** [obsproject/obs-studio#4862]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0

### OBS Studio Log URL

https://obsproject.com/logs/BXe932MXOcQoXacy

### Expected Behavior

When selecting display I expect it to get current resolution correctly my display is 2560x1440

### Current Behavior

OBS Detects my resolution as 2561x1440 causing aspect ration issues

### Steps to Reproduce

1.Open Settings
2. Video Tab
3. Look at base resolution
...

**Comment by WizardCM** [comment]
That field is a text box - manually put the correct resolution into the box to fix your issue.

Additionally, we do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
