### ISSUE TITLE
--stoprecording parameter does not work

### ISSUE THREAD

**Issue by xmha97** [obsproject/obs-studio#4871]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0

### OBS Studio Log URL

https://obsproject.com/logs/fSWxfvXOyIIYWNQG

### Expected Behavior

Stop recording/streamming

### Current Behavior

recording/streamming does not stop

### Steps to Reproduce

1. Open cmd.exe
2. Run `start /min /d "C:\Program Files\obs-studio\bin\64bit" obs64.exe --startrecording` to start recording.
3. Run `start /min /d "C:\Program Files\obs-studio\bin\64bit" obs64.exe --stoprecording` to stop recording. 
4. I have to run `TASKKILL /F /IM obs64.exe /T` because above command does not work.
...

**Comment by WizardCM** [comment]
Per the [launch parameters Wiki page](https://obsproject.com/wiki/Launch-Parameters), `--stoprecording` is not a supported parameter. Each time you launch OBS, it is a standalone instance and has no concept of existing running instances.
