### ISSUE TITLE
Discord Keybindings do not work when OBS is Ran as adman and is the active window (focused).

### ISSUE THREAD

**Issue by MattLong6** [obsproject/obs-studio#4872]
### Operating System Info

Windows 10

### OBS Studio Version

26.1.2

### OBS Studio Log URL

https://obsproject.com/logs/EDcQAJt4GYxlx4pf

### Expected Behavior

Running OBS as admin should not affect keybindings.

### Current Behavior

Discord Keybindings do not work when OBS is the active windows and it has been ran as Administrator.

### Steps to Reproduce

I have a toggle mute keybind for Discord.
If I am playing a game, I can mute and unmute just fine, but if I click OBS, I am no longer able to mute/unmute Discord.

### Anything else we should know?

Hello, when I run OBS as admin AND it is the active window, it stops my ability to use my keybind for Discord's toggle mute. If any other application is active, there are no issues.
https://www.reddit.com/r/obs/comments/fi2crt/hotkeys_not_working_when_obs_is_the_active_window/

When I run Discord and OBS as Admin. It will solve the issue for keybinding if you use a standard key on the keyboard, however it does not work with my Corsair K55 RGB Gaming Keyboard which offers 6 G-keys (Fully programmable with complex macros and key remaps for an in-game advantage. _Program special streaming **commands through Elgato Stream Deck Software**_.)

If I run the Elgato Stream Deck Software and make my G-key a toggle mute in Discord, it does not work.

My current workaround is to run ONLY OBS as Admin (to make sure it runs properly for the Twitch stream) and then run NOTHING else as Admin. Then just click away from OBS if I need to mute or use other Discord keybindings. However, I would love for it to just work instead.

**Comment by notr1ch** [comment]
This is by design in Windows for security, non-admin applications cannot intercept keypresses sent to admin applications.

**Comment by MattLong6** [comment]
Hey notr1ch, how can I get in contact with windows then to talk to them about a possible solution?

**Comment by notr1ch** [comment]
You can use the Feedback Hub, but it's unlikely this will be changed as it's a core part of privilege isolation.
