### ISSUE TITLE
27.0.1: libobs.so.0 doesn't have a SONAME

### ISSUE THREAD

**Issue by yurivict** [obsproject/obs-studio#4875]
### Operating System Info

Other

### Other OS

FreeBSD

### OBS Studio Version

Other

### OBS Studio Log URL

n/a

### Expected Behavior

Has SONAME.

### Current Behavior

```
====> Running Q/A tests (stage-qa)
Warning: /disk-samsung/freebsd-ports/multimedia/obs-studio/work/stage/usr/local/lib/libobs.so.0 doesn't have a SONAME.
Warning: pkg(8) will not register it as being provided by the port.
Warning: If another port depend on it, pkg will not be able to know where it comes from.
Warning: It is directly in /usr/local/lib, it is probably used by other ports.
```

### Steps to Reproduce

Port build.

**Comment by kkartaltepe** [comment]
From https://cmake.org/cmake/help/latest/prop_tgt/NO_SONAME.html it sounds like the default is to add a soname and if you dont see one its either a limitation or somehow being stripped in your process? 

When I build and install I can see the soname, so im going to close this.

```
$ objdump -p install/bin/64bit/libobs.so | grep SONAME
  SONAME               libobs.so.0
```
