### ISSUE TITLE
Black screen when alt tabbing out of a fullscreen game/window

### ISSUE THREAD

**Issue by Bestfast** [obsproject/obs-studio#4879]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/l_tR4e9KGDnesrUt

### Expected Behavior

When alt tabbing out, the screen should just freeze like before

### Current Behavior

When alt tabbing out, the screen just turns black

### Steps to Reproduce

1. window capture to a full screen game, for example osu!
2. alt tab or return to desktop in any way

### Anything else we should know?

It used to work before 27.0.0

**Comment by WizardCM** [comment]
This is expected behaviour. Some games do not render a texture when minimised. The only solution is to use borderless windowed mode.

The previous behaviour was not intentional, but rather a side effect of the design.

**Comment by Bestfast** [comment]
While I understand this might be an expected behavior, might be worth to revert it or to find a solution to this. Borderless fullscreen has a lot of problem in games and since it renders DWM it will also impact the resource usage. Please, understand that it's not the best when a stream alt tabs and everything turns black.

**Comment by Akarinnnnn** [comment]
I suppose to use something "Signal Lost" screen to indicate such state.
