### ISSUE TITLE
Webcam and USB Capture card not displaying at the same time, crash if changing video settings.

### ISSUE THREAD

**Issue by Xlaits** [obsproject/obs-studio#4882]
### Operating System Info

Other

### Other OS

Void Linux

### OBS Studio Version

26.1.2

### OBS Studio Log URL

https://obsproject.com/logs/FPEh84_Ri5Rq40tN

### Expected Behavior

Able to see both webcam and capture card.

### Current Behavior

Only able to see capture card *or* webcam, not both. Changing any video settings crashes OBS upon save.

### Steps to Reproduce

1. Have AVer Media Portable Live 2 plugged in.
2. Have Webcam plugged in
3. Attempt to change video settings.

**Comment by Xlaits** [comment]
Just updated to latest and tried again, no change. Did a system update, also no change.

**Comment by Xlaits** [comment]
Someone might ask for a dmesg, here it is
```[xlaits@cinnamon ~]$ lsusb
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 007 Device 003: ID 8087:0a2b Intel Corp. 
Bus 007 Device 002: ID 1b1c:0c02 Corsair H80iGT Cooler
Bus 007 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 006 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 002 Device 004: ID 046d:0825 Logitech, Inc. Webcam C270
Bus 002 Device 003: ID 1235:8212 Focusrite-Novation Scarlett 4i4 USB
Bus 002 Device 002: ID 07ca:1513 AVerMedia Technologies, Inc. Live Gamer Portable 2 Plus
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 005 Device 002: ID 046d:c52b Logitech, Inc. Unifying Receiver
Bus 005 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 002: ID 0951:16b7 Kingston Technology HyperX Alloy FPS Mechanical Gaming Keyboard
Bus 004 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
```

**Comment by kkartaltepe** [comment]
Provide a backtrace from GDB of your crash.

**Comment by kkartaltepe** [comment]
Update the 27, if this still occurs I can reopen.

**Comment by Xlaits** [comment]
As mentioned in a comment, I did update, and there was no change. However,
changing USB ports of the webcam seemed to have solved the issue for the
most part. I am still crashing when attempting to change any settings that
involve the capture card. They DO save before the crash somehow, though...
