### ISSUE TITLE
obs-ffmpeg: AAC encoder fails with Invalid argument (NaN error)

### ISSUE THREAD

**Issue by SuslikV** [obsproject/obs-studio#4885]
### Operating System Info

Other

### Other OS

any OS

### OBS Studio Version

27.0.0

### OBS Studio Log URL

about:blank

### Expected Behavior

Common AAC Encoder shouldn't fail on broken audio samples.

### Current Behavior

When decoded audio has NaN as value the OBS Studio fails to encode it into AAC and stops recording/streaming immediately.

### Steps to Reproduce

1. Run OBS Studio
2. Enable Replay Buffer (simple mode)
3. Start Replay Buffer (encoding should start)
4. Add Media source and point it to the attached "issue FFmpeg NaN aac encode error - Short - 50ms.wav" file.
5. Click OK button to close the source properties.
6. If encoder didn't yet fail for you - try to show/hide the Media source (p.4) few times.
7. The OBS Studio stops the Replay Buffer and rises error message: "Recording error - An unsupported error occurred while recording". The log file has next entry: 
```
20:02:03.547: error:   Input contains (near) NaN/+-Inf
20:02:03.547: [FFmpeg aac encoder: 'simple_aac'] avcodec_encode_audio2 failed: Invalid argument
20:02:03.547: Error encoding with encoder 'simple_aac'
```
**TEST FILE:**
[issue FFmpeg NaN aac encode error - Short - 50ms.zip](https://github.com/obsproject/obs-studio/files/6642593/issue.FFmpeg.NaN.aac.encode.error.-.Short.-.50ms.zip)
359 bytes to download, CRC of the .zip archive MD5:1C0440AB08860A39A02822AFA4C369C7

### Anything else we should know?

- The FFmpeg AAC encoder fails on input of the  floating point number that represents NaN (usually it keeps NaN in all math calculations, thus it is possible). This happens inside internal FFmpeg's _aac_encode_frame_ function.
- Audio in OBS can be modified by third-party plugins that can be written improperly (or without awareness of this limitation of the FFmpeg and OBS): https://obsproject.com/forum/threads/obs-studio-27-release-candidate.141857/page-2#post-522499
- The **test file*** that surely fails to encode by the OBS consist of the stereo data, 48kHz, about 50ms long, 32 bit float-point format. Both channels keeps silent until offset 1038(h), **where placed two NaN**s - 7F900000(h) (LSB first, one number for each channel). Media files less then 22ms may not trigger the encoding error. Any NaN in the audio will trigger the error and stops any running output that uses FFmpeg's AAC encoder.
*see attached above "issue FFmpeg NaN aac encode error - Short - 50ms.wav" file for Media source.

**Comment by notr1ch** [comment]
Are you aware of what conditions an audio stream could contain NaNs outside of a specifically crafted file?

**Comment by SuslikV** [comment]
@notr1ch I only assume: mistakes in the writing of the plugins, data transmission errors and faulty hardware/drivers. Obviously, the third one should be solved on the user's side.

Bug is rarely reported. Maybe you will find the pattern that can trigger the error for some OBS filter, some PC. Thus you'll be able to stop anyone's stream anytime remotely via the sound effect. But, you know... good luck to you with it! This will be new no streaming protection!.. ^_^

I only found workaround that if the user has faulty media source - he can add Noise Suppression>Speex filter to it (even with the 0 dB suppression level) to pass the stream to the FFmpeg AAC encoder without triggering the error. Users of other encoders may not experience this error at all (for example, the Core Audio encoder was recommended on the forum long time ago to solve this kind of errors).

**Comment by WizardCM** [comment]
For reference, this error specifically comes from FFmpeg, not our code directly:

https://github.com/FFmpeg/FFmpeg/blob/dd770883e976c91feeb8de58eacd97dfb4e8308e/libavcodec/aacenc.c#L671-L673

**Comment by mufunyo** [comment]
You can work around this bug by installing CoreAudio.

**Comment by SuslikV** [comment]
The funniest thing is that the attempt to clamp the audio output data exist in the OBS code:
https://github.com/obsproject/obs-studio/blob/16a49eb10d4609198fc6b1502319d5e73ce0c3ee/libobs/media-io/audio-io.c#L190-L191
and volume meter (UI/volume-control.cpp) operates with NaNs and Inf numbers as inputs just OK.

Of course, it is limitation of the encoder that it can't handle the audio input stream errors, but... Or maybe there is nothing to but.

**Comment by SuslikV** [comment]
I noticed side effect of the mentioned steps to reproduce the issue.

When the encoding fails (replay buffer stops, p.7) the button to start the recording changes its text to the "Stopping Recording..." (despite no recording was started!). And this causes other issues like application hung on exit or when you will try to start new recording (via hotkey or by clicking the "Stopping Recording..." button).

**Comment by claudeha** [comment]
I ran into this last night, live-coding DSP algorithms (so probably not so common...). Streaming just stopped as described above.

Currently `clamp_audio_output()` lets NaNs through, making FFMPEG complain later:

https://github.com/obsproject/obs-studio/blob/d044231bfcb246ff3f1edc4cdd73e0f8e4c42a6d/libobs/media-io/audio-io.c#L148-L149

It should be rewritten to guard against NaN, using the fact that all comparisons involving NaN return false:

```
/* note: NaN compares false */
val = (val < 1.0f) ? val : 1.0f;
val = (val > -1.0f) ? val : -1.0f;
```

This version will turn NaN into 1.0f instead of passing it through.  If you want NaN to be 0 (in case DC bias causes issues), you could prefix with an additional

```
val = (val == val) ? val : 0.0f; /* NaN -> 0 */
```

**Comment by RytoEX** [comment]
@claudeha Feel free to PR this implementation for further review. Though, I have been informed that FFmpeg will also complain about "near-NaN" values. Regardless, it is probably worth fixing this to avoid sending NaNs to encoders.

**Comment by claudeha** [comment]
near-NaN does not exist as far as I know, but near-Inf might - large (including infinite) non-NaN values should have been clamped already by the existing code, and should still be clamped in my PR unless I messed up). There is a near-0 concept in floating point (denormalized numbers), that do sometimes cause (mainly performance-related) issues, but I haven't addressed that in my PR.
