### ISSUE TITLE
Intermittent Stinger 1 frame glitch

### ISSUE THREAD

**Issue by lindenkron** [obsproject/obs-studio#4886]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.0

### OBS Studio Log URL

https://obsproject.com/logs/mNTTGQGYW67PoJWZ

### Expected Behavior

Matte stinger transition should take you smoothly from Scene A to Scene B.

### Current Behavior

Matte stinger transition intermittently flickers 1 frame from Scene B you're about to transition from Scene A to Scene B, before playing the matte stinger.

### Steps to Reproduce

1. Create Scene A
2. Create Scene B
3. Add color source Scene A
4. Add color source Scene B
5. Add multiple Window Captures (any mode should work) to Scene A.
6. Add same multiple Window Captures (any mode should work) to Scene B.
7. Add a stinger, select 'Matte_Transition_08.webm'
8. (Optional) Select top Scene, and run the .ahk. 
9. (Optional) Press 'Shift + X' to start the scene transitoning
10. Wait 1-20 minutes and watch as you'll intermittently get 1-frame glitches.

**Note:** as stated above, this similar can be "forced" more frequently with Exeldro's Virtual Cam Filter plugin, but the issue/behaviour/glitch appears to be a default OBS underlying problem.

### Anything else we should know?

Currently there's a chance that you'll get a 1 frame screenflicker of the scene you're about to transition into, using Matte Stingers in version v27+

This behaviour is experdited by a number of unknown factors, possibly more sources and most likely plugins such as 'Virtual Cam Filter' by Exeldro  (https://obsproject.com/forum/resources/virtual-cam-filter.1142/)
Repo created by Flaeri on Virtual Cam Filter since this plugin in particular seems to make this glitch happen **A LOT** more frequent. (https://github.com/exeldro/obs-virtual-cam-filter/issues/10)

To reproduce this takes some dedication to starring at a screen doing transitions. It can happen anywhere between 1 second and 20 minutes. Average time to trigger it 3~ mins on a **clean v27 OBS without plugins**.
**However** on actual scenes (such as my main scene) it happens around 20% of the time, so 1/5 which is really often. Which things exactly expedite it isn't currently very clear.

Also tested it on v27.0.1 with similar breaking results.

This was also tested externally by Flaeri who could repo it. (v27)
This was also tested externally by Matty Fresh who could repo it. (v27.0.1) 
Matty Fresh log: https://obsproject.com/logs/JRV0j5XuF3u-PSkq
Tested by me on v27 & v27.0.1.

This issue was tested with both my own stinger (uncompressed .avi, ffmpeg .webm libvpx ) & a free matte stinger from nerdordie (attached). Both display same issue. Matte attached for testing.

**Examples of glitch:**
https://www.youtube.com/watch?v=bMESD7vWE9s
https://www.youtube.com/watch?v=1SK-frs5HVY

Attached is a zip file with the following:

- An .ahk for switching scene (presses up and down) to help anyone willing to take a look at this with just having to watch (trust me, you'll want this - thanks Energizerfellow for the suggestion). 
- A 'Scene Collection' in case repo steps are unclear or lacking.
- Matte Stinger
- Examples of glitch
- Read me file 'step by step'
- Text files for Window Capture 'notepad'.
[Intermittent stinger 1 frame glitch.zip](https://github.com/obsproject/obs-studio/files/6642761/Intermittent.stinger.1.frame.glitch.zip)

**Comment by lindenkron** [comment]
I'd like to point out at while independant viewer might think "it happens so rarely, not worth looking into" I'd like to remind you that I looked into this because on the scene collections I use, whichever, it happens somewhere around 20-30% of the transitions because of something that feels accumilative. The rarity is on a simple scene boiled down. I cannot speak of the technical terms as to what's going on.

**Comment by MattyFresh68** [comment]
Nobody else wants to give this a go at reproducing?

**Comment by PatTheMav** [comment]
I've been trying to reproduce this on macOS, but wasn't able to. I _did_ see the described behaviour (and very noticeably so) in the preview for the stinger transition, but never in the live program.

**Comment by treier57lol** [comment]
Reproducible on Manjaro Linux 21.0.6 and OBS 27.0.1. Indeed, this is not a "happens rarely" problem (at least for some), I have this issue quite often, especially on more heavily demanding scene collections with lots of media files, like for example in the following second and third example video. The first two videos I've added demonstrate the already described "1 frame blink", but I also experience a "long blink" shown in the third video, which is a whole 16 frames long (can't miss it) and more frequently than the "1 frame blink/stutter/glitch/flicker" or whatever you like to call it. The "1 frame blink" seems to always happen at the start of a transition and the "long blink" at the end.

About reproducibility, it seems that almost any scene collection will have this issue no matter the complexity or resource intensiveness. It's just a matter of time until OBS slips up and starts "blinking".

If it is of any help, then I will also mention that my stinger was rendered using Blender and converted into .webm using ffmpeg.

Log file (all examples were recorded in the same session): https://obsproject.com/logs/6moVfeQTnwph3A6Q

Also, thank you @lindenkron for the example scene collection!

https://user-images.githubusercontent.com/33978534/123860854-25744800-d92f-11eb-8ce9-88480fd924d4.mp4

https://user-images.githubusercontent.com/33978534/123860868-273e0b80-d92f-11eb-98ca-6779e203edfe.mp4

https://user-images.githubusercontent.com/33978534/123860871-286f3880-d92f-11eb-86bc-f237ed46a490.mp4

**Comment by BchWut** [comment]
I get this issue as well. Decided to not run matte transitions until further versions of OBS. Happens on every transition change almost, I would say 80% occurrence.

**Comment by MattyFresh68** [comment]
I still use track mattes in routine "production" and its not super frequent, but does indeed happen at what seems like relative randomness

**Comment by lindenkron** [comment]
Am still experiencing this in every project - and it's a shame it isn't getting more attention. Am fairly sure it could be tracked down to something as simple as an execution order or something.

**Comment by MattyFresh68** [comment]
> Am still experiencing this in every project - and it's a shame it isn't getting more attention. Am fairly sure it could be tracked down to something as simple as an execution order or something.

I actually experienced this multiple times in about 9 minutes yesterday rearranging some things in my fairly simple scene collection. Very sadge that it becomes super noticeable once you know what you are looking for.

**Comment by ElectronicWar** [comment]
Possible fix was added with commit f48795439504acdfcd985e0d43f3f49ed08d3f85
Please re-test with a nightly build (use `!nightly` on Discord) or the next OBS release/beta when possible and post feedback :)

**Comment by lindenkron** [comment]
> 
> 
> Possible fix was added with commit [f487954](https://github.com/obsproject/obs-studio/commit/f48795439504acdfcd985e0d43f3f49ed08d3f85)
> Please re-test with a nightly build (use `!nightly` on Discord) or the next OBS release/beta when possible and post feedback :)

It was tested before the commit was added. I couldn't break it in 30 mins (500~ transitions). We're hoping this is the final fix.

**Comment by MattyFresh68** [comment]
> > Possible fix was added with commit [f487954](https://github.com/obsproject/obs-studio/commit/f48795439504acdfcd985e0d43f3f49ed08d3f85)
> > Please re-test with a nightly build (use `!nightly` on Discord) or the next OBS release/beta when possible and post feedback :)
> 
> It was tested before the commit was added. I couldn't break it in 30 mins (500~ transitions). We're hoping this is the final fix.

If you cant break it, I would consider that fixed haha

**Comment by jp9000** [comment]
Glad that it's fixed (as far as everyone can tell). I pretty much figured out what the problem was. Just a race condition pretty much. Going to close for now.

**Comment by IonicEcko** [comment]
I can also repro this on the 27.2 beta.

Happening reliably for me with a track matte, not when spam changing (I know that is broken) but even after waiting a couple of minutes and changing scenes.

Switching back to fade removes the problem
