### ISSUE TITLE
Put update file to %temp% instead of %AppData%

### ISSUE THREAD

**Issue by xmha97** [obsproject/obs-studio#4891]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/2Q5qB6-o9Di2pz-G

### Expected Behavior

Put update file to %temp% instead of %AppData%
![Windows Explorer](https://user-images.githubusercontent.com/23485114/121804820-7ad90580-cc5d-11eb-9bf1-ae394a3d1d05.png)

### Current Behavior

Update file put in %AppData%

### Steps to Reproduce

1. Open OBS
2. Click on the Help menu.
3. Click on the "Chack For Updates"
...

**Comment by WizardCM** [comment]
This is not a bug. The manifest is stored & cached so that it's not redownloaded all the time.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum) if you have any questions. For more info, check our [Help page](https://obsproject.com/help).
