### ISSUE TITLE
Pipewire screen capture on plasma wayland on Artix fails

### ISSUE THREAD

**Issue by appetrosyan** [obsproject/obs-studio#4893]
### Operating System Info

Other

### Other OS

Artix Linux

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.0.0-2

### OBS Studio Log URL

https://obsproject.com/logs/K9ezqAqm6P0B68l6

### Expected Behavior

Screen capture shows a list of screens and after choosing one, the preview window shows the captured screen. Window capture contains a list of winodws that can be shared using pipewire. 

### Current Behavior

Opening the screen sharing (pipewire) dialog fails. The button that's supposed to produce either the screen selection or window selection menus does nothing. The built in preview window doesn't show anything and is instead empty. The console procduces the following error 

```
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
info: [pipewire] screencast session cancelled
info: PipeWire initialized (sender name: 1_55)
info: [pipewire] available cursor modes:
error: [pipewire] Error creating screencast session: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
info: [pipewire] screencast session cancelled
info: PipeWire initialized (sender name: 1_55)
info: [pipewire] available cursor modes:
error: [pipewire] Error creating screencast session: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
info: [pipewire] screencast session cancelled
info: PipeWire initialized (sender name: 1_55)
info: [pipewire] available cursor modes:
error: [pipewire] Error creating screencast session: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.Desktop was not provided by any .service files
```

### Steps to Reproduce

1. Run Artix (runit) in KDE and/or gnome wayland session
2. Open OBS and add screen capture (pipewire)
3. Try to select a window. 
...

**Comment by GeorgesStavracas** [comment]
It seems like your system doesn't have the desktop portal installed.

**Comment by appetrosyan** [comment]
You are right! 

I only had `xdg-desktop-portal-kde` and not `xdg-desktop-portal` installed. Installing the latter resolved the issue. 

I do think that some feedback to the user in the GUI would be nice, but this resolves the issue.

**Comment by GeorgesStavracas** [comment]
I suggest you contact your distro and report this broken packaging. All portal implementations (`xdg-desktop-portal-gtk`, `xdg-desktop-portal-kde`, and `xdg-desktop-portal-wlr`) depend on `xdg-desktop-portal`.
