### ISSUE TITLE
I can't record my screen via pipewire on wayland. I just get a blackscreen

### ISSUE THREAD

**Issue by Toadfield** [obsproject/obs-studio#4896]
### Operating System Info

Other

### Other OS

Arch

### OBS Studio Version

27.0.0

### OBS Studio Log URL

When I go to the "help" tab and do strg+f and search for "Log Files",then I can't find anything.

### Expected Behavior

That I can record my screen.

### Current Behavior

When I try to add my screen to sources,then it is just a black screen,I tested it by starting a recording,then it is still just a black screen.

### Steps to Reproduce

1.open obs
2.add your screen as a source

**Comment by RytoEX** [comment]
Please use the forums or Discord for support, thanks!

https://obsproject.com/help

**Comment by Toadfield** [comment]
But it is a bug.
