### ISSUE TITLE
OBS doesn't pick up sound from Nvidia cards on Linux

### ISSUE THREAD

**Issue by JStyle21** [obsproject/obs-studio#4897]
### Operating System Info

Other

### Other OS

Gentoo Linux

### OBS Studio Version

26.1.2

### OBS Studio Log URL

https://obsproject.com/logs/KWiRQAW00bGgd3RR

### Expected Behavior

OBS should record\display the sound captured\playing

### Current Behavior

OBS doesn't pick up any sound at all from the NVIDIA HDMI card

### Steps to Reproduce

1. Run OBS in linux with an nvidia card
2. Move the default output device to the nvidia card
3. Try to capture the sound in OBS
...

### Anything else we should know?

This works in everything else just fine, i've tried building OBS without ALSA, Pulseaudio. 
Didn't help one bit, nor did playing with any of the audio settings.

**Comment by kkartaltepe** [comment]
It looks like its working as intended. Please use our support channels for help with configuration, notably if you didnt intend to filter all of our desktop audio out..

**Comment by JStyle21** [comment]
Forums were a bust for a week but i just got it resolved in discord, thanks @kkartaltepe 
Turns out i had the input on mute in PA thinking OBS can record audio from the output *face palm*
