### ISSUE TITLE
VirtualCam plugin missing

### ISSUE THREAD

**Issue by SpiGAndromeda** [obsproject/obs-studio#4898]
### Operating System Info

macOS 11.4

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/3VKPfk9nK2OMS8Jr

### Expected Behavior

I wanted to start the virtual camera but the plugin doesn't seem to be installed.

### Current Behavior

The OBS Logs show the following error: 
[mac-virtualcam] [macOS] VirtualCam DAL Plugin Installation status: (null)

There is no plugin file in /Library/CoreMediaIO/Plug-Ins/DAL/

### Steps to Reproduce

I removed the old virtualcam plugin and all the Library files to test if this changes seomthing.

**Comment by WizardCM** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

**Comment by SpiGAndromeda** [comment]
I seemed a bug to me because OSB should install this plugin at startup as far as I know. This would be an application bug @WizardCM

**Comment by WizardCM** [comment]
It should, yes - but only when you click the "Start Virtual Camera" button in the Controls dock.

**Comment by SpiGAndromeda** [comment]
@WizardCM I did. And the error message I provided was the result. Sorry for the bad explanation in the issue.
