### ISSUE TITLE
OBS fails to start and reports symbol look lookup error

### ISSUE THREAD

**Issue by Meliowant** [obsproject/obs-studio#4899]
### Operating System Info

Other

### Other OS

Debian GNU/Linux 11 (bullseye)

### OBS Studio Version

Git

### OBS Studio Log URL

<NA>

### Expected Behavior

OBS should start

### Current Behavior

OBS crashes on start with the error:
```
$ obs
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/locale/uk-UA.ini
Attempted path: /usr/share/obs/obs-studio/locale/uk-UA.ini
Attempted path: share/obs/obs-studio/themes/Dark.qss
Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
obs: symbol lookup error: obs: undefined symbol: obs_set_nix_platform

```

### Steps to Reproduce

1. Build OBS [upon instruction](https://obsproject.com/wiki/install-instructions#debian-based-build-directions) with browser source
2. Run obs
3. Get error

### Anything else we should know?

This happens on my Debian testing platform, under

```
$ gnome-shell --version
GNOME Shell 3.38.4
```

```
$ echo $XDG_SESSION_TYPE
wayland
```

[Installation log](https://www.dropbox.com/s/m8awfzxuj5jngnu/install.log?dl=0)

**Comment by notr1ch** [comment]
Your libobs is not installed correctly. You are loading the system libobs with a different version of obs.

**Comment by cshunt** [comment]
I think this was due to having a previous version installed. I removed the distro version `sudo apt remove obs-studio`
I was able to get past this with 
`sudo apt remove libobs0`
From the build folder
`sudo make install`

-Posting this here for others that may run into the same issue
