### ISSUE TITLE
OBS virtual camera not starting

### ISSUE THREAD

**Issue by maxicarlos08** [obsproject/obs-studio#4901]
### Operating System Info

Other

### Other OS

Arch linux

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/HDRJUehL3G_Gu8v4

### Expected Behavior

When I click the start virtual camera button, the virtual camera should start and be visible to all applications.

### Current Behavior

When I click the '*start virtual camera button*', it actually asks me for a password to run `modprobe` but I can't see my camera on any application.

### Steps to Reproduce

1. Install OBS (I've tried, pacman, aur and flatpak)
2. Click on the *start virtual camera* button
3. check if the camera is visible to any application

### Anything else we should know?

Apps from where I tried to access my camera: 
 - QT v4l2 test utility
 - Chrome
 - Skype (electron)
 - VLC

I don't use OBS often so I wouldn't set this to a high priority...

**Comment by RytoEX** [comment]
```
07:33:39 PM.923: ================================
07:33:39 PM.925: Warning: OBS is already running!
07:33:39 PM.925: ================================
07:33:39 PM.925: User is now running multiple instances of OBS!
```

Are you trying to run the Virtual Camera from multiple instances at the same time?

**Comment by pythonmaxi** [comment]
No, I had an OBS instance running before but closed it, but the virtual camera wasn't working in that previous instance either

**Comment by jbrains** [comment]
I have a similar (the same?) problem on Pop!_OS 21.04. When I try to start the Virtual Camera, I just get "Failed to start virtual camera" in the log with on further details.

This was working fine for me with OBS Studio 26.1. I'm going to downgrade and hope that that works around the problem for now.

**Comment by moniquelive** [comment]
I don't know if it's related, but on latest PopOS (21.04) w/ `kernel 5.11.0-7620-generic` the virtual camera works for the first time (it calls gksudo in order to invoke modprobe). If I stop and start again it does nothing (the button says "Start Virtual Camera" forever).

But if I do `sudo rmmod v4l2loopback` (I need to close OBS Studio first or I get a `Module v4l2loopback is in use` error message) then I can start it again.

**Comment by ctroncoso** [comment]
> I don't know if it's related, but on latest PopOS (21.04) w/ `kernel 5.11.0-7620-generic` the virtual camera works for the first time (it calls gksudo in order to invoke modprobe). If I stop and start again it does nothing (the button says "Start Virtual Camera" forever).
> 
> But if I do `sudo rmmod v4l2loopback` (I need to close OBS Studio first or I get a `Module v4l2loopback is in use` error message) then I can start it again.

Same here with ubuntu 21.04.
First time starting virtualcam, works fine. 
Stopping virtualcam doesn't remove v4l2loopback mod even though the button sets to OFF.
Checking v4l2-ctl, the virtual camera is still there. 
![image](https://user-images.githubusercontent.com/121016/128779997-28a0a56f-a3b2-40f0-93a9-ae6fc4b86e8c.png)

Trying to click again on start virtual camera fails.

Manually removing v4l2loopback (sudo rmmod v4l2loopback) makes virtualcam work again.

**Comment by fgadaleta** [comment]
on version `27.2.3 linux` this is still a problem.
The first time the virtual camera goes fine. 
Then I have to close `obs`, `sudo rmmod v4l2loopback` manually and open `obs` again. Only then virtual camera will work again.

**Comment by flexiondotorg** [comment]
For Ubuntu users, I've made a PPA containing builds of `v4l2loopback` for 20.04 (Focal), 21.10 (Impish), 22.04 (Jammy), 22.10 (Kinetic) that includes a backport of the following patch:

 🩹 https://github.com/umlaeute/v4l2loopback/pull/477

The patch above fixes the ability to start/stop the Virtual Camera in OBS many times. It *"works for me"*™

The PPA is here:

 📦 https://launchpad.net/~flexiondotorg/+archive/ubuntu/v4l2loopback

Feedback welcome. If this fix works widely, I'll work towards landing in the official packages for Ubuntu.

**Comment by kkartaltepe** [comment]
Closing as duplicate, thanks.
