### ISSUE TITLE
igdgmm64.dll

### ISSUE THREAD

**Issue by snowyMN** [obsproject/obs-studio#4905]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

I don't know what this is

### Expected Behavior

I expected the application to open. 

### Current Behavior

[woppsLogFile.txt](https://github.com/obsproject/obs-studio/files/6657903/woppsLogFile.txt)
![woops](https://user-images.githubusercontent.com/25513805/122106184-38d7cd00-cddf-11eb-81fe-40641d847ca8.png)

### Steps to Reproduce

1. Double click on desktop icon for OBS Software
2.
3.
...

### Anything else we should know?

I am unable to replace the igdgmm64.dll with one from another computer due to permission issues to c:\windows\system32\driverstore\filerepository\iigd_dch.inf_amd64_e6610765cda2bce8\ folder. I have tried updating my Intel UHD 620 graphics driver to the latest version and uninstalling / reinstalling my graphics driver with no success.

**Comment by Fenrirthviti** [comment]
Please use the Discord or Forums for support.
