### ISSUE TITLE
source: 'Text (FreeType 2)' doesn't support Arabic shaping

### ISSUE THREAD

**Issue by munzirtaha** [obsproject/obs-studio#4913]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/RAT2h9ZaK3ev68FF

### Expected Behavior

Typing an Arabic word should look the in the preview exactly the same as it looks in the text input widget.

![obs-issue](https://user-images.githubusercontent.com/2936425/122296149-bea06900-cf02-11eb-8663-cdd33bfffe47.png)

### Current Behavior

Arabic letters look disjoint and rendered in reverse order

### Steps to Reproduce

1. Add a source of 'Text (FreeType 2)'
2. Type an Arabic word, e.g. منذر
3. It's rendered wrongly as ر ذ ن م

### Anything else we should know?

Qt widgets supports Arabic long ago so this is an OBS bug and not an upstream bug

**Comment by RytoEX** [comment]
> Qt widgets supports Arabic long ago so this is an OBS bug and not an upstream bug

This has nothing to do with Qt.  The text source rendered on the OBS canvas is not a Qt widget.  On Linux and macOS, text sources are rendered from FreeType2.

I'm not sure that FreeType2 supports right-to-left (RTL) languages, or the different representations of Arabic glyphs based on position.  At least, I'm having trouble finding a clear answer.  If FreeType2 doesn't support this, then I'm not sure I'd call this a bug.

You can try using the [text-pango plugin](https://obsproject.com/forum/resources/text-pango-multi-language-and-emoji.656/), which should support this feature.

**Comment by kkartaltepe** [comment]
Freetype does not support shaping complex text. This is a known limitation of the plugin.

**Comment by Fenrirthviti** [comment]
As an aside, the [pango text source](https://obsproject.com/forum/resources/text-pango-multi-language-and-emoji.656/) plugin should work properly, and would be my recommendation for an alternate text source that should not have these issues.

**Comment by munzirtaha** [comment]
I tested the pango plugin and it renders the text correctly but in a bitmap-like resolution which is not good and I might report it as a bug there.

However, don't you think that any good application should be designed with multilingual support including RTL support as a basic, core feature? May be the reason you didn't replace FreeType with Pango as a default plugin is because the pango plugin is buggy?

**Comment by kkartaltepe** [comment]
Please report issues with the plugin to the plugin repository.

Currently there has not been a strong desire to add even more text sources into the mix in obs especially if they cannot be reasonably deployed to all platforms.

**Comment by munzirtaha** [comment]
@kkartaltepe: Ok, it seems you are the plugin developer so thanks for your care, but I cannot add an issue there. It redirects me to https://ideas.obsproject.com/ !

**Comment by kkartaltepe** [comment]
The plugin issue tracker is https://github.com/kkartaltepe/obs-text-pango/issues

**Comment by munzirtaha** [comment]
@kkartaltepe: I know but going there there is no Bug Report option. Take a look ...

![obs-pango](https://user-images.githubusercontent.com/2936425/122630345-8ac46f80-d0cb-11eb-822e-67753966ccc4.png)

**Comment by kkartaltepe** [comment]
Ah... I guess i was editing the template for another repository and it affected my own. It should be fixed now, thanks for the heads up.

**Comment by ahangarha** [comment]
I have relatively similar issue with Persian text:

![image](https://user-images.githubusercontent.com/11241315/133654322-a5ed2bd4-0c16-4145-8116-33c30ba09e0b.png)

it shows squares in place of characters.

**Comment by munzirtaha** [comment]
@ahangarha
Your issue is different. My guess is the rectangles mostly indicates the font chosen "Roboto" doesn't support Persian. Try to chose a different font that supports your language

**Comment by ahangarha** [comment]
> @ahangarha
> Your issue is different. My guess is the rectangles mostly indicates the font chosen "Roboto" doesn't support Persian. Try to chose a different font that supports your language

Roboto support Persian but also it doesn't matter which font I choose. I chose roboto since I guessed everyone would have it.

**Comment by ahangarha** [comment]
If needed, I open a new issue

**Comment by RytoEX** [comment]
> 
> 
> If needed, I open a new issue

As stated earlier in [my reply](https://github.com/obsproject/obs-studio/issues/4913#issuecomment-862778042) and @kkartaltepe's [reply](https://github.com/obsproject/obs-studio/issues/4913#issuecomment-862821661), FreeType does not support complex text shaping (languages where each character can affect the shape of another character).

If you need complex text shaping on Windows, use the "Text (GDI+)" source.  If you need complex text shaping on other platforms, use the Pango Text plugin linked the above comments.

Any GitHub Issues about lack of complex text shaping in the "Text (FreeType 2)" source will be closed.

Furthermore, "obs-studio_25.0.3+dfsg1-2" is quite old and is released and maintained by someone else.  Either upgrade to the latest version offered on our PPA, or seek assistance from the package maintainer.

**Comment by ahangarha** [comment]
Thanks @RytoEX for your insights.

I have also installed OBS 27 via PPA but the issue persists for the reason you mentioned.

Very much based on what you said, it is important to include such plugins by default in OBS.

**Comment by A1Gard** [comment]
> > Qt widgets supports Arabic long ago so this is an OBS bug and not an upstream bug
> 
> This has nothing to do with Qt. The text source rendered on the OBS canvas is not a Qt widget. On Linux and macOS, text sources are rendered from FreeType2.
> 
> I'm not sure that FreeType2 supports right-to-left (RTL) languages, or the different representations of Arabic glyphs based on position. At least, I'm having trouble finding a clear answer. If FreeType2 doesn't support this, then I'm not sure I'd call this a bug.
> 
> You can try using the [text-pango plugin](https://obsproject.com/forum/resources/text-pango-multi-language-and-emoji.656/), which should support this feature.

 `pango text`  is very good Idea solve my problem
 
 Any one can answer him?
 
 https://obsproject.com/forum/threads/how-to-solve-the-problem-of-writing-persian-fonts-separately-in-obs.139689/
