### ISSUE TITLE
Question: Is it possible to click on the browser?

### ISSUE THREAD

**Issue by xmha97** [obsproject/obs-studio#4924]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/G7gjOxtgB6cKvRAZ

### Expected Behavior

Can click on the browser.
![image](https://user-images.githubusercontent.com/23485114/122688238-5c13d980-d230-11eb-9998-35842ead4e38.png)
I want to click on the Connect button.
### Current Behavior

I can click on the browser.

### Steps to Reproduce

1. Open OBS
2. Click on browser
3. Nothing.
...

**Comment by RytoEX** [comment]
Please use the forums or Discord for support, thanks!

https://obsproject.com/help

**Comment by xmha97** [comment]
> 
> 
> Please use the forums or Discord for support, thanks!
> 
> https://obsproject.com/help

OK, please move this issue to discussions.

**Comment by RytoEX** [comment]
> 
> 
> > Please use the forums or Discord for support, thanks!
> > https://obsproject.com/help
> 
> OK, please move this issue to discussions.



GitHub Discussions are also not a support venue.  Please use our forums or Discord for support.

**Comment by xmha97** [comment]
> 
> 
> > > Please use the forums or Discord for support, thanks!
> > > https://obsproject.com/help
> > 
> > 
> > OK, please move this issue to discussions.
> 
> GitHub Discussions are also not a support venue. Please use our forums or Discord for support.

OK, thanks.
