### ISSUE TITLE
plugins/linux-v4l2/v4l2-input.c issues negative select timeouts

### ISSUE THREAD

**Issue by Mikael-Lovqvist** [obsproject/obs-studio#4926]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

27.0.1

### OBS Studio Log URL

Log file is 96 gigabytes and OBS removed it before I realized I had to back it up

### Expected Behavior

I expect the behavior in Current Behavior to not happen.

### Current Behavior

When using the v4l2-input plugin the log file is filled up quickly with the following two lines
```
07:53:56 AM.045: v4l2-input: /dev/video0: failed to log status
07:53:56 AM.045: v4l2-input: /dev/video0: select timed out
```
This happens 131.000 times per second on my system, caused me to get a 96 gigabyte log file.
I traced the problem to https://github.com/obsproject/obs-studio/blob/master/plugins/linux-v4l2/v4l2-input.c#L175-L179 where `fps_num`and `fps_denom`are both zero. This causes `ffps` to be `NaN` which I think causes the `select` call to misbehave.

### Steps to Reproduce

1. Start OBS 
2. Use the v4l2-linux plugin
3.
...

### Anything else we should know?

I did see that someone else had this issue on the [forum](https://obsproject.com/forum/threads/huge-amount-of-error-logs-when-camera-doesnt-return-framerate.145191/).

I am not sure how to properly make a pull request but I did make a solution that works for me here https://github.com/Mikael-Lovqvist/obs-studio/commit/3cd5742be5168f625558c14c1b38fedf23116277

If `framerate` is 0 during `v4l2_init` I  set it to a fallback framerate. This works for me and it does not limit the framerate from the camera as far as I can tell.

If logs are truly needed I can reinstall the version I did not modify on my system to recreate them.

**Comment by tt2468** [comment]
Outside of the logging spam, does the source work as expected when this happens?

**Comment by Mikael-Lovqvist** [comment]
> Outside of the logging spam, does the source work as expected when this happens?

Sort of. Since the select times out immediately I suspect it wastes a lot of CPU power but the issue mainly manifested itself through unmanageable log spam filling up disk til other applications started failing due to it. It is not correct to call select with negative timeouts and it should not be done but the source did seem to function properly from the point of view of a user using the application. I did not perform any measurements to quantify any performance difference with or without negative timeouts.

**Comment by t0msk** [comment]
still not fixed after 2 years :(
