### ISSUE TITLE
Not connecting to server / Millicast

### ISSUE THREAD

**Issue by TPBird** [obsproject/obs-studio#4930]
### Operating System Info

Windows 10

### OBS Studio Version

26.1.2

### OBS Studio Log URL

https://obsproject.com/logs/0CsHo_xsQwbfzuGn

### Expected Behavior

Connects with no issues at user's home office. Will not connect in Studio via wifi or hard wire.

### Current Behavior

Error message:
An unexpected error occurred when trying to connect to the server. More information in the log file
Connection failure

### Steps to Reproduce

1. open OBS
2. output Display Capture. No audio
3. start streaming
4. does not connect, gives above error message
...

### Anything else we should know?

Same configuration works from different location on different internet.

**Comment by dodgepong** [comment]
This appears to be using an unofficial build of OBS with WebRTC support. You will need to contact the developers of this fork, as we do not support it.
