### ISSUE TITLE
ucrtbase.terminate error

### ISSUE THREAD

**Issue by zigordlc** [obsproject/obs-studio#4938]
### Operating System Info

Other

### Other OS

Windows 7

### OBS Studio Version

Other

### OBS Studio Version (Other)

25.0.4

### OBS Studio Log URL

I can't open the program

### Expected Behavior

The program to work normally

### Current Behavior

The program don't start, it gives me this error. 
![Obs error](https://user-images.githubusercontent.com/67767832/123029621-cacf6f00-d3b7-11eb-84b0-a671996f3619.PNG)

### Steps to Reproduce

1. Open the program.
2. That's it.
3.
...

### Anything else we should know?

I'm using Windows 7 Ultimate 32-bit. The same thing happens to Audacity.

**Comment by notr1ch** [comment]
Please use the forums or Discord for support.
