### ISSUE TITLE
Cannot "Window Capture (Xcomposite)" with sublime, gedit and other windows

### ISSUE THREAD

**Issue by jwgrenning** [obsproject/obs-studio#4944]
### Operating System Info

Ubuntu 20.04

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/ZYiuTOCwq3YSGM8M

### Expected Behavior

When I add a "Window Capture (Xcomposite)" for sublime, gedit, chrome, and other apps, I expect the window in my scene.

### Current Behavior

The sources windows are not in the scene.

### Steps to Reproduce

1.open sublime text
2.add "Window Capture (Xcomposite)" to a scene
3.it does not show in the scene
...

### Anything else we should know?

The troubleshooter at sublime thought it was related to Wayland.

I used to be able to use a sublime window as a source. Now the window is transparent (black).

These apps can be a window source
OBS
Firefox
terminal
Chromium

These apps cannot be a source
Chrome
Sublime Text
Ubuntu Software
Rhythm Box

**Comment by pausz** [comment]
I have exactly the same issue. Same OS and OBS version, & Sublime 4 (Build 4107). With Sublime I thought it could be the hardware accelerated rendering. But in my case that setting is disabled.

**Comment by jwgrenning** [comment]
Seem there are some clues are in the log, though I have not tried to hunt the root cause down.
`
01:31:44 PM.533: xcompcap: cleanup glXReleaseTexImageEXT failed: GLXBadPixmap
01:31:44 PM.539: xcompcap: [window-capture: 'sublime'] update settings:
01:31:44 PM.539: 	title: /Users/james/repos/bitbucket/teachable/to-do.md (teachable-tdd) - Sublime Text
01:31:44 PM.539: 	class: sublime_text
01:31:44 PM.539: 	Bit depth: 32
01:31:44 PM.539: 	Found proper GLXFBConfig (in 9): yes
01:31:44 PM.539: 
01:31:45 PM.066: xcompcap: cleanup glXReleaseTexImageEXT failed: GLXBadPixmap
01:31:45 PM.066: xcompcap: cleanup glXDestroyPixmap failed: GLXBadPixmap
01:31:45 PM.067: xcompcap: [window-capture: 'sublime'] update settings:
01:31:45 PM.067: 	title: /Users/james/repos/bitbucket/teachable/to-do.md (teachable-tdd) - Sublime Text
01:31:45 PM.067: 	class: sublime_text
01:31:45 PM.067: 	Bit depth: 32
01:31:45 PM.067: 	Found proper GLXFBConfig (in 9): yes
01:31:45 PM.067: `
`

**Comment by kkartaltepe** [comment]
Closing this out as this is a known issues due to deficiencies in the nvidia driver and gnome compositor being unique in exposing those deficiencies.
