### ISSUE TITLE
OBS fails to start on Wayland

### ISSUE THREAD

**Issue by Bleuzen** [obsproject/obs-studio#4946]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

27.0.1

### OBS Studio Log URL

It doesn't even start so can't do this

### Expected Behavior

OBS should start without an error and show the main window

### Current Behavior

OBS doesn't start but shows an error message box:
Failed to initialize video.  Your GPU may not be supported, or your graphics drivers may need to be updated.

### Steps to Reproduce

1. Use a Wayland session on Arch Linux with KDE Plasma
2. Try to start OBS

### Anything else we should know?

Console output:
https://pastebin.com/raw/C93rBU5z

GPU: Nvidia GTX 1060
Driver: Nvidia v465.31 and v470.42.01 beta (both behave the same)

**Comment by kkartaltepe** [comment]
While nvidia doesnt support the traditional wayland interfaces I dont think we want to try and support nvidia on wayland. Feel free to attach the output of `eglinfo` to this report as well.

**Comment by Bleuzen** [comment]
Output of eglinfo is attached now.
Nvidia has no plans to support "the traditional wayland interfaces". But wayland is the future.
Now if there are really no plans from OBS to support nvidias interface, this means that in the future you just can't use OBS if you are a Nvidia user, which would be a really sad future.
I hope things are reconsidered at some point.
Also, since the problem still persists, I'm not sure if this should be closed already. Maybe someone else (OBSs wayland maintainer?) could have a look at it.

**Comment by kkartaltepe** [comment]
eglinfo looks fine, some people report nvidia doesnt support EGL_NATIVE_RENDERABLE surfaces, which may be why there are no acceptable surfaces for obs to render to on your driver.

> Nvidia has no plans to support "the traditional wayland interfaces". But wayland is the future.

Sounds like you should be telling that to nvidia, not us.

**Comment by Bleuzen** [comment]
Btw. OBS v26 does start on Wayland. (but I guess non native, so with xwayland). Only thing is the preview doesn't work and it records just black (because of missing pipewire support in that version?)

Would it be possible to get OBS v27 to run with xwayland to make it usable?

**Comment by puyoxyz** [comment]
any updates on this? anything gonna happen? or can i just not use obs anymore?

**Comment by Fenrirthviti** [comment]
There is not much for us to do. From what I understand, the issue is with Nvidia and Wayland, not us. The reason things are broken in v26 is because xwayland doesn't support the functions obs requires, hence the work to support it that has been done. We can't fix your broken environment, though.

**Comment by kkartaltepe** [comment]
You can already force OBS 27 to run on xwayland by passing the `-platform xcb` to obs (Or setting QT_QPA_PLATFORM=xcb) for controlling qt will also control OBS.

It may be possible for us to write a graphics backend that doesnt require native surfaces, but it would probably be unusably slow or grind most CPUs to a halt. Which isnt a very appealing prospect for most users, so no one has looked into it.

The best option for everyone is to wait until either the entire open source graphics, compositor, and A/V community rewrites all their code to use nvidias custom protocols. Or wait for nvidia to implement the open source standards. OBS is just one small part of the stack that needs to change for things to work unless nvidia wants to start supporting things.

**Comment by kkartaltepe** [comment]
> Running on xwayland works fine, but there's no option to capture with PipeWire, so it's useless

You can load the X11/EGL backend with env var `OBS_USE_EGL=1` when forcing X11 to allow the pipewire plugin to load.

**Comment by myownfriend** [comment]
The same thing happens with Nvidia's GBM driver.

**Comment by kkartaltepe** [comment]
Their beta driver still does not support EGL_NATIVE_RENDERABLE's which are required for our current EGL backend.

**Comment by myownfriend** [comment]
Damn it. So close yet so far lol

**Comment by myownfriend** [comment]
After updating to egl-wayland 1.1.9, OBS now opens but runs with lllvmpipe so it's sloooow. Just point this out because it at least gets past the specific issue mentioned in this thread.

**Comment by kkartaltepe** [comment]
OBS will start and render on nvidia hardware with #5620

 However nvidia and qt are currently incompatible, so trying to run Qt applications like OBS on wayland with their drivers will result in Qt programs hanging or lagging horribly. Considering there is no fix in Qt yet its unlikely nvidia users will be able to use OBS for quite some time even if the PR lands in OBS.

**Comment by AlynxZhou** [comment]
> OBS will start and render on nvidia hardware with #5620
> 
> However nvidia and qt are currently incompatible, so trying to run Qt applications like OBS on wayland with their drivers will result in Qt programs hanging or lagging horribly. Considering there is no fix in Qt yet its unlikely nvidia users will be able to use OBS for quite some time even if the PR lands in OBS.

Just build master source and it works smooth on NVIDIA + GNOME Wayland session, Qt hanging seems depend on desktop environment.

**Comment by puyoxyz** [comment]
> > OBS will start and render on nvidia hardware with #5620
> > However nvidia and qt are currently incompatible, so trying to run Qt applications like OBS on wayland with their drivers will result in Qt programs hanging or lagging horribly. Considering there is no fix in Qt yet its unlikely nvidia users will be able to use OBS for quite some time even if the PR lands in OBS.
> 
> Just build master source and it works smooth on NVIDIA + GNOME Wayland session, Qt hanging seems depend on desktop environment.

yeah because the pr (#5620) they were talking about got merged.....

**Comment by lukts30** [comment]
Does not work on KDE Plasma but in Gnome Wayland Session on the same system, it does work. 
After I select a Window from the KDE portal prompt I only get a black.
With pipewire fullscreen recording, I get a black recording where only the mouse cursor is visible.

But what does work is screen sharing with  WebRTC in Firefox with pipewire.
(Tested on:https://www.webrtc-experiment.com/Pluginfree-Screen-Sharing)

Seems to be KDE Bug (https://bugs.kde.org/show_bug.cgi?id=448944) but WebRTC Firefox does work on my system (wayland & xwayland firefox).

**Comment by kkartaltepe** [comment]
Do not use this issue as a dumping ground for your nvidia issues or we will be forced to lock it.

Feel free to use our support channels but again nvidia hardware is mostly unsupported.

**Comment by majkrzak** [comment]
> xwayland doesn't support the functions obs requires
Is there a xwayland ticket opened regarding that?

**Comment by kkartaltepe** [comment]
Its quite likely that xwayland will consider not listing native wayland windows and making not them available via xcomposite a feature and not a bug. I guess if you want confirmation you can open a bug against them if you really want.

**Comment by mcnaveen** [comment]
Solved after installing this package. `qtwayland5`

```
sudo apt install qtwayland5
```
