### ISSUE TITLE
Sound recording but no Sound on Device

### ISSUE THREAD

**Issue by Xusr404** [obsproject/obs-studio#4947]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/Ds2Rp-Q-MbsrmyRk

### Expected Behavior

If i start OBS it should continue play sound on my Wireless Headphones (Aukey EP-B40) not only in "Hands free AG Audio" but also in Stereo mode
No Problems with wired Headphones (Aux)

### Current Behavior

If i start OBS it immediatelly stops playing sound on the wireless headphones, but the sound is beeing recorded as it should
No Problems with wired Headphones (Aux)

### Steps to Reproduce

1. Connect to the wireless Headphones (Aukey EP-B40 in Stereo Mode not with "Hands free AG Audio"")
2. (Play Music/Sound)
3. start OBS

**Comment by notr1ch** [comment]
Please use the forums or Discord for support issues.
