### ISSUE TITLE
Missing build instruction section for debian buster

### ISSUE THREAD

**Issue by anakimluke** [obsproject/obs-studio#4949]
### Operating System Info

Other

### Other OS

debian 10

### OBS Studio Version

Git

### OBS Studio Log URL

Not applicable.

### Expected Behavior

Expected for all the required packages listed at [Debian-based Build Directions](https://github.com/obsproject/obs-studio/wiki/Install-Instructions#debian-based-build-directions) to be installed upon attempting to install.

### Current Behavior

If the user does not have 'non-free' packages enabled on their system, they are presented with the following error message:

```
E: Unable to locate package libfdk-aac-dev
```

### Steps to Reproduce

1. Follow the build instructions for debian-based distros.
2. Profit.

### Anything else we should know?

I don't know if this package is really needed, so I don't know if it should be removed from the list or if a instructions on how to enable the non-free packages should be added.

**Comment by RytoEX** [comment]
The package `libfdk-aac-dev` is for the obs-libfdk optional plugin.  You can disable that plugin at configure time by specifying `-DDISABLE_LIBFDK` via CMake:
https://github.com/obsproject/obs-studio/blob/7993179466cffcccd7973c2105563d9a6924f75d/plugins/obs-libfdk/CMakeLists.txt#L3-L6

In the future, please use our forums or our Discord for questions about building OBS.

**Comment by anakimluke** [comment]
Right! I still think this is an issue, though. If it is optional and it *will* throw an error, there should be some guidance about it in the instructions. :)

**Comment by WizardCM** [comment]
The Wiki is free to be edited by anyone: https://github.com/obsproject/obs-studio/wiki
