### ISSUE TITLE
OBS 27.0.1 crash on macOS 10.13.6

### ISSUE THREAD

**Issue by Alvazz** [obsproject/obs-studio#4952]
### Operating System Info

macOS 10.13

### Other OS

macOS

### OBS Studio Version

27.0.1

### OBS Studio Log URL

http

### Expected Behavior

just double-click start running. then crash.

### Current Behavior

when I want startup OBS.app then crash.

### Steps to Reproduce

1. double-click OBS.app
2.then crash.
3.
...

### Anything else we should know?

bug log:

Crashed Thread:        16  com.apple.audio.IOThread.client

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x4] Symbol missing

Dyld Error Message:
  Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/OBS.app/Contents/MacOS/../Frameworks/libavutil.56.70.100.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by Fenrirthviti** [comment]
Please provide the entire crash log, the snippet you copies is not actionable.

**Comment by Alvazz** [comment]
crash.log:
[crash.log](https://github.com/obsproject/obs-studio/files/6727842/crash.log)

**Comment by dossy** [comment]
Wonder if the solution is as easy as this: https://github.com/nodegui/nodegui/issues/391#issuecomment-582788859

**Comment by dossy** [comment]
![image](https://user-images.githubusercontent.com/65378/123721827-1d47da00-d855-11eb-84a6-0f4bd273edc4.png)

> a7ul commented on Feb 6, 2020
> Re opening this issue since the issue seems to be with how the prebuilt binary is built.
> Need to add CMAKE_OSX_DEPLOYMENT_TARGET to an older version of mac than the latest to make the binary compatible.

**Comment by dossy** [comment]
Given the mention of libavutil.56.70.100.dylib, it looks like the issue is with how the ffmpeg that's bundled with OBS was built?

**Comment by Alvazz** [comment]
@dossy thank so much.. you are right.

**Comment by dossy** [comment]
@Alvazz What did you do to fix the problem?
