### ISSUE TITLE
on the problem of virtual camera

### ISSUE THREAD

**Issue by salier** [obsproject/obs-studio#4958]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://github.com/salier/don-t-know-where-to-put-thing/blob/main/2021-06-29%2023-55-31.txt

### Expected Behavior

I want to start the virtual camera and get the media stream of the virtual camera in other programs.

### Current Behavior

When i start the virtual camera,don't see the hardware of the virtual camera. can't get the signal. There is no prompt.
I've tried to re install it. But it didn't work.
![QQ截图20210629235743](https://user-images.githubusercontent.com/28691601/123832119-9881bc80-d937-11eb-91a9-54535c9897b7.png)
![QQ截图20210629235723](https://user-images.githubusercontent.com/28691601/123832130-9ae41680-d937-11eb-9665-c21c163f1611.png)

### Steps to Reproduce

emmmm
download
install
start-up
Virtual camera not found

### Anything else we should know?

May be caused by repeated installation? I see the option of obs virtual camera in some programs (but it doesn't work )

**Comment by Fenrirthviti** [comment]
Please use the Discord or forums for support, but this sounds like something you need to bring up with the applications it is not working in, as many applications explicitly block virtual camera devices.
