### ISSUE TITLE
Audio Howling Issue when Broadcasting Twitch Server

### ISSUE THREAD

**Issue by trustkim** [obsproject/obs-studio#4963]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/9B7jblX7Fqkd9HaG

### Expected Behavior

I just woke up today and tried broadcasting as usual.
But my viewers told me this issue.
Until that time, I wasn't realized at all.
Because the OBS monitoring audio was sounded find.

### Current Behavior

There is no problem with the monitoring sound, but the live sound overlaps.

### Steps to Reproduce

I tried to just re-boot all my system, and re-start OBS.
But this issue still...
And also I tried to test all this setting into another system.

In the same way in other systems,
there is no problem with the monitoring sound,
and only the sound on the livestreaming has a problem.

### Anything else we should know?

It looks like you did a recent Windows 10 update.

**Comment by WizardCM** [comment]
This is an issue on Twitch's side, the VoD track is playing in live videos alongside the live audio, causing doubling of volume & other quirks. Nothing we can do on our side but wait. The workaround for now is to disable the Twitch VoD track in OBS Settings -> Output.
