### ISSUE TITLE
Black OBS output on captured, unfocused window with xmonad noBorders/smartBorders

### ISSUE THREAD

**Issue by T-X** [obsproject/obs-studio#4966]
### Operating System Info

Other

### Other OS

Debian Sid

### OBS Studio Version

26.1.2

### OBS Studio Version (Other)

26.1.2+dfsg1-1+b1

### OBS Studio Log URL

https://obsproject.com/logs/PH4c12kmf5aer4At

### Expected Behavior

OBS should be able to capture not only a focused but also an unfocused window with "Window Capture (xcomposite)" when using the xmonad tiling window manager with a fullscreen layout with noBorders or smartBorders.

https://hackage.haskell.org/package/xmonad-contrib-0.16/docs/XMonad-Layout-NoBorders.html#v:noBorders
https://hackage.haskell.org/package/xmonad-contrib-0.16/docs/XMonad-Layout-NoBorders.html#v:smartBorders

With a tiling window manager like xmonad you typically have no or only a minimal frame around the contents of a window. And by default xmonad will only draw a small, coloured frame around the currently focused window:

https://xmonad.org/images/screenshots/Screen-rob-dzen.png

When adding "noBorders" (or with smartBorders when using a single screen and a fullscreen layout) this frame will be omitted.

### Current Behavior

When using xmonad with noBorders or alternatively with smartBorders with a single screen and fullscreen layout then OBS will show a black output when trying to capture an unfocused window with "Window Capture (xcomposite)". And OBS will output the following error message in the logs:

```xcompcap: XCompositeNameWindowPixmap failed: BadMatch (invalid parameter attributes)```

When switching back to the captured window then the capture of the window and OBS output works again and OBS shows the following message in the logs:

```
20:31:14.642: xcompcap: [window-capture: 'Window Capture (Xcomposite)'] update settings:
20:31:14.642: 	title: Warzone 2100
20:31:14.642: 	class: warzone2100
20:31:14.642: 	Bit depth: 24
20:31:14.642: 	Found proper GLXFBConfig (in 392): yes
```

When switching to another window again then the output will turn black again with the Pixmap failed error.

When removing "noBorders" and "smartBorders" from the xmonad config file then the OBS window capture works perfectly fine, no matter if the window is focused or not.

### Steps to Reproduce

1. Install xmonad
2. Enable ewmh and noBorders by creating ~/.xmonad/xmonad.hs with the following content:
```
import XMonad
import XMonad.Hooks.EwmhDesktops
import XMonad.Layout.NoBorders

main :: IO ()
main = xmonad $ ewmh defaultConfig { layoutHook = noBorders Full }
```
3. Recompile and start xmonad via "xmonad --recompile && xmonad --replace"
4. Switch to a fullscreen xmonad layout (rotate through available layouts with mod-space)
4. Start OBS and an application window you want to capture (for instance, gedit)
5. Configure a "Window Capture (Xcomposite)" source in OBS for the application you want to capture
6. Focus a window other than the one you are capturing in OBS (for instance OBS itself).
7. OBS will display a black output in its preview (and also when streaming).

ewmh is needed for the OBS window capture (or "wmctl" for instance, too) to detect any window at all: https://hackage.haskell.org/package/xmonad-contrib-0.16/docs/XMonad-Hooks-EwmhDesktops.html

### Anything else we should know?

xmonad versions:

```
$ dpkg -l | grep xmonad
ii  libghc-xmonad-contrib-dev                                   0.16-1+b1                           amd64        Extensions to xmonad
ii  libghc-xmonad-dev                                           0.15-4+b1                           amd64        Lightweight X11 window manager
ii  xmonad                                                      0.15-4+b1                           amd64        Lightweight X11 window manager written in Haskell
```

intel and mesa driver versions:
```
$ dpkg -l | grep -e mesa -e intel
ii  intel-gpu-tools                                             1.25-2.1                            amd64        tools for debugging the Intel graphics driver
ii  intel-media-va-driver-non-free:amd64                        21.1.1+ds1-1                        amd64        VAAPI driver for the Intel GEN8+ Graphics family
ii  intel-media-va-driver-non-free:i386                         21.1.1+ds1-1                        i386         VAAPI driver for the Intel GEN8+ Graphics family
ii  libdrm-intel1:amd64                                         2.4.102-1                           amd64        Userspace interface to intel-specific kernel DRM services -- runtime
ii  libdrm-intel1:i386                                          2.4.102-1                           i386         Userspace interface to intel-specific kernel DRM services -- runtime
ii  libegl-mesa0:amd64                                          20.2.4-1                            amd64        free implementation of the EGL API -- Mesa vendor library
ii  libegl1-mesa-dev:amd64                                      20.2.1-1                            amd64        free implementation of the EGL API -- development files
ii  libgl1-mesa-dev:amd64                                       20.3.4-1                            amd64        transitional dummy package
ii  libgl1-mesa-dri:amd64                                       20.2.4-1                            amd64        free implementation of the OpenGL API -- DRI modules
ii  libgl1-mesa-dri:i386                                        20.2.4-1                            i386         free implementation of the OpenGL API -- DRI modules
ii  libgl1-mesa-glx:amd64                                       20.2.1-1                            amd64        transitional dummy package
ii  libglapi-mesa:amd64                                         20.2.4-1                            amd64        free implementation of the GL API -- shared library
ii  libglapi-mesa:i386                                          20.2.4-1                            i386         free implementation of the GL API -- shared library
ii  libgles2-mesa-dev:amd64                                     20.2.1-1                            amd64        transitional dummy package
ii  libglu1-mesa:amd64                                          9.0.1-1                             amd64        Mesa OpenGL utility library (GLU)
ii  libglu1-mesa:i386                                           9.0.1-1                             i386         Mesa OpenGL utility library (GLU)
ii  libglu1-mesa-dev:amd64                                      9.0.1-1                             amd64        Mesa OpenGL utility library -- development files
ii  libglx-mesa0:amd64                                          20.2.4-1                            amd64        free implementation of the OpenGL API -- GLX vendor library
ii  libglx-mesa0:i386                                           20.2.4-1                            i386         free implementation of the OpenGL API -- GLX vendor library
ii  libintellij-annotations-java                                20.1.0-1                            all          transitional package for libjetbrains-annotations-java
ii  libosmesa6:amd64                                            20.2.4-1                            amd64        Mesa Off-screen rendering extension
ii  libosmesa6:i386                                             20.2.4-1                            i386         Mesa Off-screen rendering extension
ii  libwayland-egl1-mesa:amd64                                  20.2.1-1                            amd64        transitional dummy package
ii  mesa-common-dev:amd64                                       20.2.1-1                            amd64        Developer documentation for Mesa
ii  mesa-utils                                                  8.4.0-1+b1                          amd64        Miscellaneous Mesa GL utilities
ii  mesa-va-drivers:amd64                                       20.3.5-1                            amd64        Mesa VA-API video acceleration drivers
ii  mesa-va-drivers:i386                                        20.3.5-1                            i386         Mesa VA-API video acceleration drivers
ii  mesa-vdpau-drivers:amd64                                    20.2.1-1                            amd64        Mesa VDPAU video acceleration drivers
ii  mesa-vdpau-drivers:i386                                     20.2.1-1                            i386         Mesa VDPAU video acceleration drivers
ii  mesa-vulkan-drivers:amd64                                   20.2.4-1                            amd64        Mesa Vulkan graphics drivers
ii  mesa-vulkan-drivers:i386                                    20.2.4-1                            i386         Mesa Vulkan graphics drivers
ii  mosh                                                        1.3.2-2.1+b3                        amd64        Mobile shell that supports roaming and intelligent local echo
ii  whois                                                       5.5.7                               amd64        intelligent WHOIS client
ii  wvdial                                                      1.61-5                              amd64        intelligent Point-to-Point Protocol dialer
ii  xserver-xorg-video-intel                                    2:2.99.917+git20200714-1            amd64        X.Org X server -- Intel i8xx, i9xx display driver
```

Kernel:
```
$ uname -a
Linux linus-work 5.7.19 #7 SMP Sun Nov 8 00:36:09 CET 2020 x86_64 GNU/Linux
```

Device:
* ThinkPad T480s
* Intel(R) Core(TM) i7-8550U CPU
* onboard Intel GPU

glxinfo:
* https://gist.github.com/T-X/a2027b289e11b09459650996b798f88f

Past ticket which mentioned the same "XCompositeNameWindowPixmap failed: BadMatch" error with the same symptoms (black output) but in a different scenario (at least there is no mention of xmonad or window focus):

https://github.com/obsproject/obs-studio/issues/2693

**Comment by T-X** [comment]
One more important addition: I just noticed that with the xmonad smartBorders and noBorders removed the `XCompositeNameWindowPixmap failed: BadMatch` error message is gone and the black capture, too. But:

The window capture is then a frozen image for the captured, unfocused window...

This happens even when both OBS and the captured window are on the same xmonad workspace.

**Comment by kkartaltepe** [comment]
It sounds like you are saying that the window you would like to capture is entirely obscured by other windows when you experience this issue. If that is the case then this is likely working as intended due to your compositor telling the window it does not need to render so it stops rendering.

**Comment by T-X** [comment]
@kkartaltepe hm, sounds plausible. I'm not that familiar with X and xmonad internals. But it seems I get similar issues when trying to record a window with gstreamer and an ximagesrc. gstreamer will throw an error either immediately if the window is unfocused. Or if the window is focused then gstreamer will start recording but will throw an error when switching away:

Patiently waiting while focusing the window works:

```
$ sleep 3; timeout 15 gst-launch-1.0 ximagesrc xid=0x2200014 ! videoconvert ! queue ! x264enc qp-min=18 ! avimux ! filesink location=gstreamer-ximagesrc.avi
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Redistribute latency...
```

But when switching away gstreamer aborts:

```
$ sleep 3; timeout 20 gst-launch-1.0 ximagesrc xid=0x2200014 ! videoconvert ! queue ! x264enc qp-min=18 ! avimux ! filesink location=gstreamer-ximagesrc-3.avi
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Redistribute latency...
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  73 (X_GetImage)
  Serial number of failed request:  501
  Current serial number in output stream:  501
```

xid was retrieved via `xwininfo`. So seems unrelated to OBS, you're right... Guess I'm lucky then that OBS at least continues gracefully when refocusing, in contrast to gstreamer which quits immediately :-D.

---

One more important thing I forgot to mention: For OBS or wmctl to see the window at all, EWMH needed to be added to the xmonad configuration:

https://hackage.haskell.org/package/xmonad-contrib-0.16/docs/XMonad-Hooks-EwmhDesktops.html

I've edited the original ticket description to include a minimal, 5 lines xmonad configuration file with EWMH and noBorders. I'm not really sure what EWMH hints are actually doing. But I guess I'll best ask the xmonad ewmh author(s) or at xmonad in general.

Thanks for your quick reply @kkartaltepe!
