### ISSUE TITLE
Resize output(source size) on cropped source resizes to source size, not cropped area size

### ISSUE THREAD

**Issue by Echo51** [obsproject/obs-studio#4969]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/v42NLzmjD1cl2hCb

### Expected Behavior

I believe it should resize output to the cropped area of the selected source, since the cropped area is just empty/black/not filled

### Current Behavior

It resizes output to the source size, and then scales the cropped area with in that according to the transform settings, usually resulting in black bars/empty space if it's not a crop to the same aspect ratio

### Steps to Reproduce

1. Create window capture of smaller-than-canvas window.
2. Crop this source a bit, to show it clearly crop to just the center 1/3
3. Resize output (source size)
4. you will now see the canvas beign resized to the source size(hit ctrl+e, check size), while the actual cropped contents are fitted per the Bounding Box Type selected in the transform

### Anything else we should know?

I'm not sure if i'm just not used to the cropping tool, or if cropping afterwards doing these steps also makes the cropping act weird(can't uncrop with alt-drag, doesn't show cropped/green lines?)

**Comment by WizardCM** [comment]
I would personally say this is expected behaviour combined with an expected quirk of alt-cropping. The crop is on the scene item, and the button specifically says (source size).

If you need this capability to respect crop, use a Crop/Pad filter on the source directly.
