### ISSUE TITLE
Video Capture Device (V4L2) loses device on startup

### ISSUE THREAD

**Issue by guitaristtom** [obsproject/obs-studio#4972]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/7kFe4RM6vKCvlXSY

### Expected Behavior

On Windows it remembers a video device, such as a webcam, and goes back to it when it's plugged in. 

### Current Behavior

Once it's unplugged in Linux though it tends to say `/dev/video1` or grabs (and locks) a different video device. 

This is rather frustrating when a USB capture card is unplugged or being finicky / flakey and it grabs and locks my webcam to one of those sources instead of my standard webcam source. Causing me several minutes of trial and error to try and get my webcam set up with its proper source instead of one of the four separate capture card sources I have.

### Steps to Reproduce

1. Start OBS
2. Create two video capture sources, each with a different video capture device
3. Close OBS
4. Unplug one of the devices
5. Open OBS, the issue should have occurred

**Comment by kkartaltepe** [comment]
dup #3003
