### ISSUE TITLE
Failed to START OBS 27.0.1 ON Ubuntu 20.04

### ISSUE THREAD

**Issue by jotana240** [obsproject/obs-studio#4976]
### Operating System Info

Ubuntu 20.04

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/forum/threads/obs-27-0-1-startup-error-in-xubuntu-ver-24-04.145836/

### Expected Behavior

When opening the obs, an error window is given, about the video driver not starting, Failed to initalize video, and I have to open the obs in the terminal with the following command to open the obs: LIBGL_ALWAYS_SOFTWARE = 1 obs

### Current Behavior

I can open it but with the command, only with the command, if I try to open normally through the icon, the error appears, I have not yet tested all the operation of the obs

### Steps to Reproduce

1. Open Terminal with Ctrl + Alt + T 
2. paste the command and enter: LIBGL_ALWAYS_SOFTWARE = ​​1 obs
3. and voila open the obs
...

### Anything else we should know?

In previous versions I did not get this error because now I do

**Comment by WizardCM** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
