### ISSUE TITLE
Can't access Logitech Streamcam MJPG/60FPS on Linux

### ISSUE THREAD

**Issue by melissaboiko** [obsproject/obs-studio#4978]
### Operating System Info

Other

### Other OS

Debian bullseye 

### OBS Studio Version

Git

### OBS Studio Log URL

https://obsproject.com/logs/7hLKqwH0P0_m7FBC

### Expected Behavior

Logitech Streamcam can do 60Fps on all resolutions (up to 1920x1080). This is visible on v4l2-ctl, testable on qv4l2 etc., but there's no way to see or set it in OBS that I know of.

### Current Behavior

MJPEG mode is not available on linux. The usual workaround is to use one of the "emulated" modes.  But if I do that, all I can see is 30FPS, in all 3 "emulated" (BGR12, YU3, YV3).

One workaround is set the resolution and FPS elsewhere, then "leave unchanged" on OBS.  If the resolution is "unchanged", the 60 FPS setting is visible. (There's no "leave unchanged" for the video format to leave it in MJPG.)

Currently I'm doing this with the resolution I want:

```
v4l2-ctl -d "$dev" --set-fmt-video width=960,height=540,pixelformat=MJPG
v4l2-ctl -d "$dev" -p 60 # FPS
```

### Steps to Reproduce

1. Choose a resolution.
2. See the FPS list.

**Comment by kkartaltepe** [comment]
Based on your own accounting it cannot reach 60fps on MJPEG so this seems working as intended. If you think 60fps should be available configure it with 60fps and provide the full v4l2-clt dump and then the same dump when it is configured with obs and we can consider reopening.

**Comment by melissaboiko** [comment]
It can reach 60FPS on MJPEG; that's on the camera spec, and it's also testable under qv4l2-ctl.  I can capture videos at 60FPS and they play fine.  It's also setable under OBS if you leave "resolution" as "unchanged".  Only if you set the resolution OBS can't set 60FPS anymore.  And OBS is the only application that does that, probably because it can't see the MJPG mode.

Here's the v4l2-ctl dump after I set it to 1920x1080@60FPS on qv4l2-ctl, I can test it and it displays fine:

```
Driver Info:
	Driver name      : uvcvideo
	Card type        : Logitech StreamCam
	Bus info         : usb-0000:06:00.3-1
	Driver version   : 5.13.0
	Capabilities     : 0x84a00001
		Video Capture
		Metadata Capture
		Streaming
		Extended Pix Format
		Device Capabilities
	Device Caps      : 0x04200001
		Video Capture
		Streaming
		Extended Pix Format
Media Driver Info:
	Driver name      : uvcvideo
	Model            : Logitech StreamCam
	Serial           : AA334D45
	Bus info         : usb-0000:06:00.3-1
	Media version    : 5.13.0
	Hardware revision: 0x00000317 (791)
	Driver version   : 5.13.0
Interface Info:
	ID               : 0x03000002
	Type             : V4L Video
Entity Info:
	ID               : 0x00000001 (1)
	Name             : Logitech StreamCam
	Function         : V4L2 I/O
	Flags         : default
	Pad 0x01000007   : 0: Sink
	  Link 0x0200001f: from remote pad 0x100000a of entity 'Processing 3': Data, Enabled, Immutable
Priority: 2
Video input : 0 (Camera 1: ok)
Format Video Capture:
	Width/Height      : 1920/1080
	Pixel Format      : 'MJPG' (Motion-JPEG)
	Field             : None
	Bytes per Line    : 0
	Size Image        : 4147200
	Colorspace        : sRGB
	Transfer Function : Rec. 709
	YCbCr/HSV Encoding: ITU-R 601
	Quantization      : Default (maps to Full Range)
	Flags             : 
Crop Capability Video Capture:
	Bounds      : Left 0, Top 0, Width 1920, Height 1080
	Default     : Left 0, Top 0, Width 1920, Height 1080
	Pixel Aspect: 1/1
Selection Video Capture: crop_default, Left 0, Top 0, Width 1920, Height 1080, Flags: 
Selection Video Capture: crop_bounds, Left 0, Top 0, Width 1920, Height 1080, Flags: 
Streaming Parameters Video Capture:
	Capabilities     : timeperframe
	Frames per second: 60.000 (60/1)
	Read buffers     : 0
                     brightness 0x00980900 (int)    : min=0 max=255 step=1 default=128 value=128
                       contrast 0x00980901 (int)    : min=0 max=255 step=1 default=128 value=128
                     saturation 0x00980902 (int)    : min=0 max=255 step=1 default=128 value=128
 white_balance_temperature_auto 0x0098090c (bool)   : default=1 value=1
                           gain 0x00980913 (int)    : min=0 max=255 step=1 default=0 value=41
           power_line_frequency 0x00980918 (menu)   : min=0 max=2 default=2 value=1
				0: Disabled
				1: 50 Hz
				2: 60 Hz
      white_balance_temperature 0x0098091a (int)    : min=2000 max=7500 step=1 default=4000 value=4524 flags=inactive
                      sharpness 0x0098091b (int)    : min=0 max=255 step=1 default=128 value=128
         backlight_compensation 0x0098091c (int)    : min=0 max=1 step=1 default=0 value=0
                  exposure_auto 0x009a0901 (menu)   : min=0 max=3 default=3 value=3
				1: Manual Mode
				3: Aperture Priority Mode
              exposure_absolute 0x009a0902 (int)    : min=3 max=2047 step=1 default=250 value=300 flags=inactive
         exposure_auto_priority 0x009a0903 (bool)   : default=0 value=0
                   pan_absolute 0x009a0908 (int)    : min=-36000 max=36000 step=3600 default=0 value=0
                  tilt_absolute 0x009a0909 (int)    : min=-36000 max=36000 step=3600 default=0 value=0
                 focus_absolute 0x009a090a (int)    : min=0 max=255 step=1 default=0 value=0
                     focus_auto 0x009a090c (bool)   : default=1 value=0
                  zoom_absolute 0x009a090d (int)    : min=100 max=400 step=1 default=100 value=100

```

Here's how it looks like on OBS even if you set an "emulated" mode, notice 60FPS is missing:

![Bildschirmfoto vom 2021-07-05 09-05-22](https://user-images.githubusercontent.com/74593/124496820-3a7f2a00-ddba-11eb-8d59-4549f20971e4.png)

And the diff of the dump:

```diff
-	Pixel Format      : 'MJPG' (Motion-JPEG)
+	Pixel Format      : 'NV12' (Y/CbCr 4:2:0)
-	Bytes per Line    : 0
-	Size Image        : 4147200
+	Bytes per Line    : 1920
+	Size Image        : 3110400
-	Quantization      : Default (maps to Full Range)
+	Quantization      : Default (maps to Limited Range)
-	Frames per second: 60.000 (60/1)
+	Frames per second: 30.000 (30/1)
```

**Comment by kkartaltepe** [comment]
I dont have you precise device, but perhaps you can try other emulated formats. Generally these should choose MJPG (for example on a C920 they do), but on your device it appears to choose NV12 which wont support 60fps.

**Comment by Bitals** [comment]
@kkartaltepe I have the same webcam, I tried every single available format and none supported 60fps. But it does list 60 (while not actually working at 60, image is clearly 30 at best). I use USB 3, 60fps works outside OBS.

**Comment by pmartiner** [comment]
I have a Streamcam as well and I can confirm the issue. No format allows 60FPS (as @Bitals said, when leaving the resolution "unchanged" the option does get listed but the video does not render at 60FPS)

**Comment by fbievan** [comment]
Master branch, still unstable though atleast for me, but initial support is here now.

**Comment by kkartaltepe** [comment]
compressed format support was added.
