### ISSUE TITLE
OBS 27.0.1 won't fully close after H.264 Recording

### ISSUE THREAD

**Issue by Pablomx2** [obsproject/obs-studio#4981]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/z_KzZbHhTetrw2MM

### Expected Behavior

Have OBS close and kill obs64.exe when clicking the "X" button.

### Current Behavior

OBS will close, leaving a system tray icon that can't be clicked to access OBS since it's closed. Only way to close it is by using the task manager.

### Steps to Reproduce

1. Launch OBS
2. Start a recording session using H.264 (AMF)
3. Stop the recording.

**Comment by flaeri** [comment]
Feel like this might have been better in the support channels on discord :)
Make sure you try updating to 4.9.1 websocket, and see if it still happens.
https://github.com/Palakis/obs-websocket/releases/tag/4.9.1

Would suggest further steps (assuming this dosent solve it), to go in the support channels.
If you believe this is a bug with OBS, it would be nice to have confirmed repro steps without plugins.
