### ISSUE TITLE
Audio Mixer empty in Artix

### ISSUE THREAD

**Issue by AnantGupta384** [obsproject/obs-studio#4987]
### Operating System Info

Other

### Other OS

Artix Linux with s6 init system

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/Z-3Rh8f0QAZx6GeN

### Expected Behavior

Should see options for audio like for Desktop, Mike etc. Can change the volume percentage of both of these

### Current Behavior

Nothing present in audiomixer, litreally it is empty, it is like this
![image](https://user-images.githubusercontent.com/71361442/124897516-01ce9300-dffc-11eb-9c58-2c6d7bb13eec.png)

### Steps to Reproduce

1. Installed artix with the s6 init system
2. Installed these audio packages *alsa-utils pavucontrol pcmanfm pulseaudio pulseaudio-alsa pulseaudio-bluetooth python-pyalsa* from pacman  
3. Installed obs-studio from pacman
4. Starting obs-studio
5. Can't see anything in audio mixer
6. Voice from desktop & audio is also not recording
...

### Anything else we should know?

I can hear voice if I play a video from any browser or any video player. My mic is also working, I tried it by attending a video confrencing meeting

**Comment by WizardCM** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

**Comment by notr1ch** [comment]
```
02:44:45 PM.022: os_dlopen(libnvidia-encode.so.1->libnvidia-encode.so.1): libnvidia-encode.so.1: cannot open shared object file: No such file or directory
02:44:45 PM.029: os_dlopen(/usr//lib/obs-plugins/sndio.so->/usr//lib/obs-plugins/sndio.so): libsndio.so.7.1: cannot open shared object file: No such file or directory
```

Looks like some system libraries are missing / broken. Artix Linux with s6 init system is not an officially supported platform, so you should contact your packager for assistance.
