### ISSUE TITLE
Screen capture source display numbers change after computer restart

### ISSUE THREAD

**Issue by vjpr** [obsproject/obs-studio#4991]
### Operating System Info

macOS 11.4

### OBS Studio Version

27.0.1

### OBS Studio Log URL

xxx

### Expected Behavior

You should be able to specify the screen `id` rather than the OBS "screen number".

It seems that the OBS "screen number" is the order in which the screens are enumerated from the Quartz API.

### Current Behavior

When restarting macOS, the screen numbers change, and you have to manually go and change them.

### Steps to Reproduce

It's not that easy to reproduce.

You need multiple monitors connected to MacBook.

Create screen capture sources with different display numbers.

Restart macOS.

### Anything else we should know?

Related: https://obsproject.com/forum/threads/how-does-obs-assign-display-numbers.115199/

Here are the docs to the API call: https://developer.apple.com/documentation/coregraphics/1454603-cggetactivedisplaylist#discussion

It says:
> The first entry in the list of active displays is the main display.

I guess after this it is a bit random depending on when the OS detects the displays.

**Comment by davidgatti** [comment]
I can confirm, I have the same problem. With 8 monitors this is incredibly annoying to re-map them all each time.

**Comment by vjpr** [comment]
> I can confirm, I have the same problem. With 8 monitors this is incredibly annoying to re-map them all each time.

I wrote a script to automate the update if you are interested I can post it.

**Comment by davidgatti** [comment]
Sure, but maybe you cold propose a PR with a fix? 😅

**Comment by WizardCM** [comment]
It does look like we just use an index. The API only seems to provide a `CGDirectDisplayID` via `dc->screen.deviceDescription[@"NSScreenNumber"]`. The big downside of `CGDirectDisplayID` is:

> A display ID can persist across processes and typically remains constant until the machine is restarted.

Theoretically, one could combine certain data (say, resolution + display name?) to generate a persistent identifier, which may be better than just an index that changes on each reboot.

**Comment by davidgatti** [comment]
I did try to find the properties of `deviceDescription` but no luck - I don't miss developing for Apple 😅

@WizardCM  regarding your idea

1. about the display name, if I have 2 identical displays, same brand and model, will the name be the same for both?
2. dose a display provide its own serial number maybe?

Because I have for example: 6 HP monitor with the same model. and two LG also sam models. So I wonder if your idea will work in this scenario.

**Comment by rbradcurtis** [comment]
I suggest that CGGetOnlineDisplayList() may be a possible solution here.
[See:](https://developer.apple.com/documentation/coregraphics/1454964-cggetonlinedisplaylist)

This Apple provided API in Core Graphics allows access to a device's UUID which will persist across reboot, reconnections, resizing etc.

Further to @davidgatti 's note above, identical displays should be properly handled as the UUID considers:


I noted the usage of this capability in [jakehilborn/displayplacer](https://github.com/jakehilborn/displayplacer) with sample code here: [](https://github.com/jakehilborn/displayplacer/blob/master/displayplacer.c)

Updates would need to be made throughout /plugins/mac-capture/mac-display-capture.m etc.

Implementation of this as a PR is beyond my skillset, but hopefully someone will take this across the finish line!

**Comment by davidgatti** [comment]
@rbradcurtis Fantastic, can't wait it being implemented in to OBS :) Thank you very much!

**Comment by gxalpha** [comment]
Could you check whether this also is an issue with the `macOS Screen Capture` source?
We consider the traditional display capture source to be deprecated.

**Comment by attaboyBrad** [comment]
> Could you check whether this also is an issue with the `macOS Screen Capture` source?
> We consider the traditional display capture source to be deprecated.

I can confirm this appears to be an issue with 'macOS Screen Capture'.

I use a few 'macOS Screen Capture' sources to 'App Capture' on my second monitor, and upon launch I fairly regularly need to open properties and reselect the second monitor as the desired display.  I think it mostly depends on whether the system has been restarted in between OBS launches.

Oddly, sometimes the second display will remain selected in these sources, but I'll have to select a different app and then re-select the desired app to make the windows actually show up.

**Comment by rbradcurtis** [comment]
Issue not resolved.

Tested on OBS 28.1.2 (64-bit) Applie Silicon.
MBP 16-in, 2021

**Test case:**

- created a new empty scene
- added (1) MacOS Screen Capture source for the first monitor with label "Left" 
- source "Left" linked to 1st of two identical monitors
- added (1) MacOS Screen Capture source for the second monitor with label "Right"
- source "Right" linked to 2nd of two identical monitors
- functions as expected
- reboot system
- Launch OBS

**OUTCOME**: Random.  On some reboots monitors are swapped (left to right).  On some reboots one monitor appears in both MacOS Screen Capture sources.  When "doubled" it could be either monitor that has been "doubled." Occasionally, sources do behave correctly and the appropriate displays are shown in the appropriate sources.

<img width="574" alt="Screenshot 2022-11-24 at 6 54 37 PM" src="https://user-images.githubusercontent.com/3240673/203876021-31419a82-75f7-44c0-8fb5-39345b7b2304.png">

I believe that the display sources are not using the UUID or other unique value(s) that might help OBS reliably connect to expect devices upon OS or Application restart.

**Comment by ianjukes** [comment]
> > I can confirm, I have the same problem. With 8 monitors this is incredibly annoying to re-map them all each time.
> 
> I wrote a script to automate the update if you are interested I can post it.

@vjpr I've just come across this. Can I get a copy of your script?? 🙏

**Comment by PatTheMav** [comment]
`ScreenCaptureKit` internally uses the `CGDirectDisplayID` (as is canonical on macOS), so that's the only way to identify a display for "Display Capture" or "Application Capture".

But it's not too complicated to convert the session information (display ID) to long-term information (UUID) via `CGDisplayCreateUUIDFromDisplayID` and `CGDisplayGetDisplayIDFromUUID` - while the source is active, using display ID is simpler and more immediate, but we can convert the value when storing the settings and restoring from it.

We'll look into implementing this for a version after 29.1, as we'll have to take existing configurations into account and gracefully upgrade those.

**Comment by ianjukes** [comment]
> `ScreenCaptureKit` internally uses the `CGDirectDisplayID` (as is canonical on macOS), so that's the only way to identify a display for "Display Capture" or "Application Capture".
> 
> But it's not too complicated to convert the session information (display ID) to long-term information (UUID) via `CGDisplayCreateUUIDFromDisplayID` and `CGDisplayGetDisplayIDFromUUID` - while the source is active, using display ID is simpler and more immediate, but we can convert the value when storing the settings and restoring from it.
> 
> We'll look into implementing this for a version after 29.1, as we'll have to take existing configurations into account and gracefully upgrade those.

Thanks @PatTheMav 💪
