### ISSUE TITLE
Fedora 34 (Gnome 40): Cannot set hotkeys

### ISSUE THREAD

**Issue by nasseef20** [obsproject/obs-studio#4992]
### Operating System Info

Other

### Other OS

Fedora 34

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/oUGY3_OWyz7ywDtK

### Expected Behavior

When I go to Settings > Hotkeys, and then click on an option (Example : Start Recording), I would be able to assign a hotkey by clicking the corresponding command on the keyboard.

### Current Behavior

Nothing is set, as in when I type the command, nothing appears beside the option. No matter which keys I press, nothing appears. As if the keyboard does not work at all in the hotkeys menu of the settings.

https://user-images.githubusercontent.com/86907615/125122022-a3e29e00-e116-11eb-9491-024c1255f4a2.mp4

### Steps to Reproduce

1. Open OBS Studio 
2. Go to Settings > Hotkeys
3. Try to set a hotkey (it won't, as if the keyboard is not working at all)
...

**Comment by kkartaltepe** [comment]
Wayland does not support hotkeys.

**Comment by orowith2os** [comment]
Can this be reopened now? There's a global shortages portal available, allowing shortcuts to work on Wayland. Someone just needs to implement it in OBS.

**Comment by kkartaltepe** [comment]
Our issues are not for feature requests. You can probably find the feature request on the [ideas](https://ideas.obsproject.com/) page already, if not feel free to make a new request there.

**Comment by cfreis** [comment]
I create a a kludge solution for workaround this issue.
You can find it here:
https://github.com/cfreis/obs-scripts
