### ISSUE TITLE
OBS won't stop recording on HEVC

### ISSUE THREAD

**Issue by jivvy** [obsproject/obs-studio#4995]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/Rpg2FX5EnM66olSC

### Expected Behavior

After clicking Start Recording, the recording starts
When clicking Stop Recording, the recording stops and the file on disk will be finalized

### Current Behavior

Clicking Start Recording causes OBS to behave as expected, REC in the bottom, button changes to Stop Recording...

Clicking Stop Recording changes the button's text to "Stopping Recording..." and it stays like that. The recording timer in the bottom continues ticking upward as if it's still recording.
The file is not found on disk.

This only occurs when I use the HEVC codec.

### Steps to Reproduce

1. Use HEVC  codec
2. Click Start Recording in the bottom right
3. Click Stop Recording in the bottom right
![obs64_WZVjdOw82r](https://user-images.githubusercontent.com/24281896/125558316-6e917261-2951-477c-bb08-805b404260a0.png)

### Anything else we should know?

Graphics Card: RX 6700 XT, latest stable drivers ( 21.6.1 )
CPU: Ryzen 3600
Memory: 32 GB
Saving to a hard drive

**Comment by Fenrirthviti** [comment]
You are attempting to use Master Mode for the AMF encoder, which is unsupported. If you can replicate this in simple mode, please reply and this can be reopened.

**Comment by Xaymar** [comment]
Please note that simply entering View mode Expert or Master permanently alters the state of the configuration. In order to repro it properly in simple mode you will need to create a new profile.

**Comment by jivvy** [comment]
Oh I wasn't aware I could reopen it, I thought you had me make a new one because the log file was slightly off
So here's a log file with Basic View mode:
[Link to log file](https://obsproject.com/logs/JliIJYsbG1BYhXA_)

**Comment by jivvy** [comment]
@Fenrirthviti Is there anything else I need to do for this to be reopened?
