### ISSUE TITLE
OBS won't stop recording on HEVC

### ISSUE THREAD

**Issue by jivvy** [obsproject/obs-studio#4996]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

[Link to log file](https://obsproject.com/logs/JliIJYsbG1BYhXA_)

### Expected Behavior

After clicking Start Recording, the recording starts
When clicking Stop Recording, the recording stops and the file on disk will be finalized

### Current Behavior

Clicking Start Recording causes OBS to behave as expected, REC in the bottom, button changes to Stop Recording...

Clicking Stop Recording changes the button's text to "Stopping Recording..." and it stays like that. The recording timer in the bottom continues ticking upward as if it's still recording.
The file is not found on disk.

This only occurs when I use the HEVC codec.

### Steps to Reproduce

1. Use HEVC codec
2. Click Start Recording in the bottom right
3. Click Stop Recording in the bottom right
![obs64_WZVjdOw82r](https://user-images.githubusercontent.com/24281896/125592266-a41b20d7-b614-47d8-8c74-0e069493b959.png)

**Comment by kkartaltepe** [comment]
Dont recreate your issue beccause the previous onewasclosed. If you have made some kind of change and you think the precious one should be reopened. Make an appropriate comment in your prevous issue with why you think it should be reopened.
