### ISSUE TITLE
Obs-studio 27.0.1 is causing interference with Bluetooth Controllers

### ISSUE THREAD

**Issue by RyzenDew** [obsproject/obs-studio#5002]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://cdn.discordapp.com/attachments/812292812107546624/865778869838282792/2021-07-16_22-27-32.txt

### Expected Behavior

i wanted obs to not cause these issues 

### Current Behavior

my joycons and pro controller would disconnect and would be laggy 

here is that happening on stream

it worked perfect with obs off

### Steps to Reproduce

1.Connect Controllers
2.run any game or Yuzu with skyward sword
3.watch the lag or it turns off and reconnects
...

### Anything else we should know?

it happens to any app based on obs but not xsplit

**Comment by Fenrirthviti** [comment]
Please use the support channels or Discord for support.

**Comment by RyzenDew** [comment]
no this is a bug that can't be fixed with discord or forums

**Comment by RyzenDew** [comment]
> Please use the support forums or Discord for support.

do you guys not fix bugs anymore cause discord is worthless for fixing issues coded in and forums wont be any help

**Comment by Fenrirthviti** [comment]
I use bluetooth controllers, headsets, keyboards, and mice with OBS running on a near daily basis without any issues whatsoever. This doesn't sound like an issue with OBS, but rather something specific to your system. Going off the log file, and the audio buffering, it looks like you're simply overloading your system (probably a USB controller or similar) and that is what is causing the issue. OBS doesn't do any kind of integration or direct communication with bluetooth devices in any way whatsoever, we connect using OS-provided APIs and functions so there wouldn't be any "issues coded in" for us to fix in the first place.
