### ISSUE TITLE
Closing main window with unsaved source properties dialog open, results in 2 save popups and crash

### ISSUE THREAD

**Issue by nyanpasu64** [obsproject/obs-studio#5003]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/XDqoaOB_sCku2iqM

### OBS Studio Crash Log URL

https://obsproject.com/logs/2u6mi3qwUWBMxSOz

### Expected Behavior

- Pressing Discard discards changes and closes the program.
- Pressing Cancel either acts like Discard (don't save changes to source) or cancels closing the main window.

### Current Behavior

- Pressing Discard saves changes and closes the program.
- Pressing Cancel causes a second "Settings Changed" popup to appear.
	- Pressing Discard saves changes and closes the program. I haven't seen it crash yet.
	- Pressing Cancel a second time closes the program and often results in a crash.

### Steps to Reproduce

1. Launch OBS.
2. Add a window capture with unsaved changes. If you already have a window capture, open the properties dialog for an existing window capture and change some settings.
	- This bug also occurs with other types of sources, like GDI+ Text.
3. Click the titlebar X button of the *main* OBS Studio window (or close OBS from the taskbar), with a source properties dialog open with unsaved changes.

**Comment by flaeri** [comment]
I can confirm I observe the same crash. For text source, I needed to hit cancel.
Hitting discard, would not close nor crash, but it would actually save my change, which is kind of weird.

**Comment by WizardCM** [comment]
Part of this sounds related to #4576, the other part sounds like the buttons might be performing the wrong actions. I'll look into the latter when I have time.

**Comment by RytoEX** [comment]
I cannot reproduce the crash on OBS Studio 29.0.0 Beta 1. There are still multiple dialogs prompting, but we consider the core issue here to be the crash.
