### ISSUE TITLE
Show/Hide Transitions only working on preview (Linux)

### ISSUE THREAD

**Issue by niklasberlin** [obsproject/obs-studio#5004]
### Operating System Info

Ubuntu 21.04

### OBS Studio Version

Other

### OBS Studio Version (Other)

OBS-studio ppa (27.0.1)

### OBS Studio Log URL

https://obsproject.com/logs/ZYAG9YLNwF9ddlQZ

### Expected Behavior

when i set the visibility to true/visible of some sources in the current scene i expect them to show up on program with the configured Show Transition (it works this way on windows)

### Current Behavior

in the preview window (studio mode) i can see the transition, but in the program window (with the same scene) i do not see the transition nor the now visible source

### Steps to Reproduce

1. create a source (e.g. color source)
2. configure show/hide transitions (e.g. slide in/out)
3. select the scene for program and preview in studio mode
3. toggle visibility of the source -> in preview the transition works, on program nothing changes

**Comment by WizardCM** [comment]
This is expected behaviour. You can click the gear icon between the preview/program in Studio Mode, and disable "Duplicate Scenes" to allow pass-through of Source Transitions.
