### ISSUE TITLE
OBS Window Capture doesn't work on Nvidia GPU, Debian Rolling Release 

### ISSUE THREAD

**Issue by thecoder08** [obsproject/obs-studio#5020]
### Operating System Info

Other

### Other OS

Debian Rolling Release (unstable/sid/11)

### OBS Studio Version

26.1.2

### OBS Studio Log URL

https://obsproject.com/logs/oAmIZrCn9f3G91wx

### Expected Behavior

I expect that when I run OBS on my discrete Nvidia GPU, Window Capture (Xcomposite) should properly capture the window of choice.

### Current Behavior

Xcomposite captures the cursor with a black background.

### Steps to Reproduce

1. Open OBS on discrete Nvidia GPU
2. Add Window Capture (Xcomposite) source
3. Observe that only the cursor is captured and the window is black
...

### Anything else we should know?

I have tried:

Using alpha-less textures (no effect)

Running OBS on integrated Intel Graphics (This works but the framerate is not high enough)

Running as root (this works but it is a hassle. This makes me think it is a permissions issue)

Note: The window I want to capture is Minecraft, running on discrete Nvidia GPU. It can be captured with OBS running on Intel GPU, just with low OBS framerate.

My Discrete GPU: Nvidia GeForce GTX 1650  
My Integrated GPU: Mesa Intel UHD Graphics

X.org v1.20.11

**Comment by kkartaltepe** [comment]
Duplicate #4694

**Comment by thecoder08** [comment]
> Duplicate #4694

This is not a duplicate. That issue has something to do with CSD and Minecraft does not use CSD at all. That issue references nothing about graphics cards and the like. That issue is using Pop OS and I'm using Debian. When I use alternative desktops (xfce4, cinnamon) it doesnt change a thing. the issue exists for CSD and non-CSD applications. This should be reopened.

**Comment by kkartaltepe** [comment]
Basically, if "Window Capture fails with glXCreatePixmap failed: BadAlloc" then your issue is a duplicate. There is some discussion of things that cause it more or less frequently but that is the issue. Sorry we have not rewritten the text of the issue to reflect further discussion in the issue and other duplicates.
