### ISSUE TITLE
OBS Studio transparent colors aren't rendering properly

### ISSUE THREAD

**Issue by megatrook** [obsproject/obs-studio#5025]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

there is no log? its completely unnecessary. i just have pictures.

### Expected Behavior

Transparent colors are actually transparent.

### Current Behavior

Transparent colors appear as "darkened"

### Steps to Reproduce

1. get a partially transparent png/browser page
2. place it in an obs source
3. it looks wrong and very dark

### Anything else we should know?

this used to work in previous versions, like a few months ago. y'all broke it and it hasnt been fixed since. i want to use a transparent white (#FFFFFF) on one of my sources but it just looks gray.
![image](https://user-images.githubusercontent.com/77197776/126788087-22af7f22-903f-49f7-9045-e201b4b2e9c3.png)
![image](https://user-images.githubusercontent.com/77197776/126788129-cafc4cc8-2846-4a4f-ba5b-a09178e0c36b.png)
![image](https://user-images.githubusercontent.com/77197776/126788298-8b4d640c-db89-4805-9fbb-efcf554b88ae.png)
please don't ignore this its really infuriating

**Comment by flaeri** [comment]
well, I wouldnt say its broken, but it is changed. I would recommend giving this a read:
https://github.com/obsproject/obs-studio/wiki/Linear-Color-Blending

Sounds like you want to aim for around 80% opacity full white. 
As far as images goes, you may need to check the "linear alpha" box if you decide to re-author your images.

I know they did what they could to minimize the impact to existing setups, but certain changes are just happen naturally when the pipeline is changed to do linear gamma.

**Comment by megatrook** [comment]
how do i change a browser source to be compatible with the change then?

**Comment by flaeri** [comment]
If you're looking for advice on how to change web sources to match the look you want, I would recommend seeking support in the discord server, or on the forums. Github issues isnt really the place for that kind of stuff.

Discord: https://obsproject.com/discord
Forums: https://obsproject.com/forum

**Comment by megatrook** [comment]
legitimately surprised obs decided to make this change for everyone instead of having it be a toggle in the settings for those who need it so that it doesnt destroy things for everyone else

**Comment by flaeri** [comment]
its not possible to make the change without it having downstream effects. I know they did what they could to keep existing setups from changing.
