### ISSUE TITLE
OBS reduces fps by up to 15% on my RTX 3060 without recording

### ISSUE THREAD

**Issue by jesuschrist4202** [obsproject/obs-studio#5028]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/o8IUiNE_H-0KZczU

### Expected Behavior

I expect OBS to have little effect on my FPS while not recording just like it did on my 1050 Ti which is significantly weaker than my current 3060.

### Current Behavior

OBS Reduces my fps while 100% gpu limited by up to 15% while I am not recording.

I'm on a scene with just game capture active and a 1080p webcam on top of it. I have a display capture in the same scene but it is disable and I tested removing it makes no difference.

I setup a scenario: Minecraft with shaders without mobs, no day cycle, etc so the FPS will be exactly the same in the scene unless something outside the game changes.

OBS not open: 108 fps
OBS with just game capture: 101 fps (7% reduction)
Adding webcam on top: 95 fps (6% reduction)
Starting the 1440p60fps recording: 90fps (5% reduction, expected)

This fps loss will occur in any game which is 100% gpu limited and the % of fps lost will be the same.

My 1050 Ti had no noticeable fps loss from opening OBS until I started recording which caused the expected 5% loss. This means the fps loss is not from the little bit of gpu power OBS needs to render scenes since the 3060 is more than twice as powerful as the 1050 Ti.

I also tested shadowplay on my 3060, which had no affect on my fps until I started recording which had the expected 5% loss. This leads me to believe nothing is wrong with my 3060 since shadowplay works as it is supposed to.

### Steps to Reproduce

1. Open a game and enter a scenario which is 100% gpu limited (where msi afterburner reports 98%+ gpu usage)
2. Probably need to use an RTX 3060, I have the updated version with the hashrate limiter which is not bypassed by beta driver 470.05. Idk if there are any other cards which exhibit this behavior.
3. Open OBS with game capture + 1080p webcam and your framerate should drop by the same percentage as mine.

### Anything else we should know?

I have tried multiple nvidia driver versions.

One interesting thing I noticed is that while OBS is running during the scenario, hwinfo64 reports my 3060 drawing only ~167 watts but as soon as I close OBS it shoots up to ~181 watts and gives me my fps back. So maybe OBS is somehow preventing the gpu from operating at it's max potental somehow?

I also noticed minimizing OBS gives back 3% of my fps and disabling preview window will give back another 1% of my fps.

While very unlikely, maybe the hashrate limiter is causing this slowdown because it detects obs as a mining software?

I tested on my friends 1070 and 1080 Ti and both of those cards also had no fps loss from just having OBS open like my 1050 Ti.

**Comment by Fenrirthviti** [comment]
Please use the support forums or Discord for support.
