### ISSUE TITLE
Can't start virtual camera with smart card-only authentication on MacOS

### ISSUE THREAD

**Issue by andrewrynhard** [obsproject/obs-studio#5030]
### Operating System Info

macOS 11.2

### OBS Studio Version

27.0.1

### OBS Studio Log URL

none

### Expected Behavior

Virtual camera should start.

### Current Behavior

I have a smart card and have disable password authentication in MacOS. When starting the virtual camera, I get the following error with no prompt for a PIN:

![Screen Shot 2021-07-25 at 4 26 54 PM](https://user-images.githubusercontent.com/3383143/126916846-8c876425-befb-4304-b38d-dc2516642b5e.png)

### Steps to Reproduce

1. Setup smart card
2. Enable smart card-only authentication: `sudo defaults write /Library/Preferences/com.apple.security.smartcard enforceSmartCard -bool true`
3. Try to start virtual camera in OBS

**Comment by gxalpha** [comment]
We did a complete refactor of the virtual camera on macOS that will be included in the next release of OBS. With that, we will no longer have a custom authentication dialog to install the virtual camera, so this should no longer happen then.
