### ISSUE TITLE
Black Screen Pipewire (Wayland Kde Garuda Linux)

### ISSUE THREAD

**Issue by davigamer987** [obsproject/obs-studio#5031]
### Operating System Info

Other

### Other OS

Garuda Linux KDE Dragonized Gaming Edition (Arch Based)

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/SOjvJjD9K7trTZRi

### Expected Behavior

Screen is shown 

### Current Behavior

I get a black screen

### Steps to Reproduce

1. Download Obs from Store (Pamac) On Garuda Linux KDE (With wayland session)
2. Create a new screen capture
3. Look at the preview (Its plain black)
...

**Comment by WizardCM** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
