### ISSUE TITLE
OUTPUT JERKING

### ISSUE THREAD

**Issue by PeterAkakpo** [obsproject/obs-studio#5032]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/QHEHtrHxp3rbsoEj

### Expected Behavior

all outputs at higher base and output resolution must run smoothly without any jerks provided there is enough CPU and GPU time and memory available.

### Current Behavior

at higher base and output resolutions (at least 1920x1080) running Decklink output, NDI output and recording at the same time, all outputs are jerky or freezing with the exception of screen projector even those the is still CPU is at 32.5%, GPU at 37.3% and memory usage is just 700MB
![obs task manager](https://user-images.githubusercontent.com/7926382/126964713-d82e35ee-7b49-44b3-8e0e-8cf9542d9da1.png)
. so is the audio too

### Steps to Reproduce

1. set base and output resolutions to at least 1920x1080, color format: RGB, renderer: D3d11,  Color Space: 709, Color Range: Full, FPS: 30
2. start decklink output, ndi output and start record
3. observe the outputs on ndi studio monitor and the decklink connected monitor
...

**Comment by notr1ch** [comment]
Please use the forums or Discord for support.

**Comment by PeterAkakpo** [comment]
what am reporting has got nothing to do with settings that someone from discord or the forum need to direct me to use a particular settings. this is an issue related to the core or the software. so i don't see the reason why you have to close the issue without providing any concrete response. if you still think the discord or the forum is the right place, can you direct me to the exact location on both discord and forum where this issue is addressed.

**Comment by Fenrirthviti** [comment]
Seeing as you are on Windows, the Windows support sections would be the place to start.

Or if you don't want to go through the normal support channels, you can try reading the guide to reducing performance bottlenecks for [CPU](https://obsproject.com/wiki/General-Performance-and-Encoding-Issues) and [GPU](https://obsproject.com/wiki/GPU-overload-issues)

GitHub Issues are reserved for verified, replicable bug reports of the core program. NDI is a third party plugin, so the inclusion thereof already makes this an invalid bug report as we don't control or develop that plugin.

**Comment by PeterAkakpo** [comment]
It doesn't just happen with ndi output, decklink output with virtual cam
output also behave same. As u can see from the attached image, there is
enough cpu and GPu available. It's not that cpu and gpu  are been used up

**Comment by PeterAkakpo** [comment]
will be glad if this issue is looked it instead of closing it. as i said earlier, running multiple output such as decklink output, vcam and recording at the same time make the image on those outputs to jerk and lags behind the preview. the preview is ok, but when u monitor output on the decklink device, its jerking, same with virtual camera. everything works ok when you only run a single output. the issue is with running multiple outputs at the same time at a high frame rate eg (1080p60). This happens even those there is more CPU and GPU available
