### ISSUE TITLE
Window Capture keeps displaying window even when window is closed and no longer detected

### ISSUE THREAD

**Issue by Pxartist** [obsproject/obs-studio#5034]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/VK1AR3mg7UMIHF0G

### Expected Behavior

When the window that is being tracked by the Window Capture is closed or no longer detected (indicated by the text "Window" in the properties window being red), Window Capture should not be displaying anything.

### Current Behavior

Depending on the type of window that is being captured, the window will continue being displayed on screen even when closed or undetected and may even continue to track the cursor.

Here is a youtube video demonstrating the issue: [https://youtu.be/4-NpjfAc9JI](https://youtu.be/4-NpjfAc9JI)

Watch for the color of the "Window" text in the properties window

### Steps to Reproduce

1. Create a Window Capture Source
2. Capture Window
3.
...

### Anything else we should know?

The code fix should be somewhat simple:

When the source being tracked (the window) is disconnected or no longer detected, do not display anything. If such a feature is considered too dangerous / disruptive of standard functionality, please add a "Do not display source when no longer detected" checkbox in the properties window.

**Comment by RytoEX** [comment]
After getting through the Clip Studio Paint sign up and trial process, I can finally confirm that this is still occurring in OBS Studio 29.0.0 Beta 1. The linked PR will need to be reviewed and tested.

Note that reproducing this seems to require using BitBlt Window Capture on a child/sub-window. Testing this on a regular application window will not reproduce the behavior.
