### ISSUE TITLE
Fractional scaling display error Ubuntu 20.04 and OBS 27.0.1

### ISSUE THREAD

**Issue by richtertoralf** [obsproject/obs-studio#5036]
### Operating System Info

Ubuntu 20.04

### OBS Studio Version

27.0.1

### OBS Studio Log URL

not available

### Expected Behavior

normal start and window as always
![Bildschirmfoto vom 2021-07-27 15-11-31](https://user-images.githubusercontent.com/73883286/127159852-0d84c98f-a183-4629-a90a-a03797f564a9.png)

### Current Behavior

![screenshot](https://user-images.githubusercontent.com/73883286/127156417-e081deba-a295-4ca7-9c00-4d965a58eb87.png)

### Steps to Reproduce

1. I use one 4K monitor and two FullHD monitors.
2. Select "Fractional scaling" in the settings for display devices. Set 150%.
![Bildschirmfoto vom 2021-07-27 15-14-02](https://user-images.githubusercontent.com/73883286/127159698-4899ca64-02dc-47c3-b0cf-fce0f4d5cee1.png)

3. Launch OBS Studio
->  Missing the line with File, Edit, Profile, ....
-> The lower section is double.

See screenshot!

### Anything else we should know?

I have tested different variants of FFmpeg and also installed OBS-Studio several times. Whenever I select "Fractional Scaling" and set e.g. 150%, OBS shows this strange behavior.
I am using Ubunte 20.04 LTS minimal version with X11 without any changes. Ubuntu I have freshly installed. Except for ffmpeg and OBS I have no other programs installed.

**Comment by kkartaltepe** [comment]
Fractional scaling was disabled on linux because qt was broken.
