### ISSUE TITLE
filters: Image Mask/Blend of type Blend results in overexposed image

### ISSUE THREAD

**Issue by SuslikV** [obsproject/obs-studio#5048]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

about:blank

### Expected Behavior

When _Image Mask/Blend_ of type _Blend (Addition)_ filter applied to the solid color sources of RGB(0,0,0) with the PNG ("blend") files that filled with the RGB(16, 16, 16 ) colors, the result image colors should be visible on the screen as the RGB(16, 16, 16).

### Current Behavior

When _Image Mask/Blend_ of type _Blend (Addition)_ filter applied to the solid color sources of RGB(0, 0, 0) with the PNG ("blend") files that filled with the RGB(16, 16, 16 ) colors, the result image colors is visible on the screen as the RGB(71, 71, 71). Result is too bright.

### Steps to Reproduce

1. Add pure black RGBA(0, 0, 0, 255) Color Source to the obs Scene.
2. Add filter _Image Mask/Blend_ to the Color Source from p1.
3. Set _Type_ of the _Image Mask/Blend_ filter (p2.) to the _Blend (Addition)_
4. Point _Path_ of the _Image Mask/Blend_ filter (p2.) to the attached test image "obs_image_mask_blend_filter_0+16.png";
the test picture below, 128x128, left half is filled with the RGB(0 ,0 ,0); right half - RGB(16, 16, 16):
![obs_image_mask_blend_filter_0+16](https://user-images.githubusercontent.com/19683044/127635106-70d5b6aa-aef3-4159-b136-85654855f813.png)
5. Notice that the resulting image (Color Source) will be rendered too bright on the right half. I estimated the resulting colors as RGB(71, 71, 71).

### Anything else we should know?

Was reported on the forum: https://obsproject.com/forum/threads/image-mask-blend-broken-as-of-v27.145973/

**Comment by notr1ch** [comment]
Blending was changed in v27, have you read https://github.com/obsproject/obs-studio/wiki/Linear-Color-Blending ?

**Comment by SuslikV** [comment]
@notr1ch Yes. But it didn't says that OBS's **only filters** output is linear now (or else). The _Image Mask/Blend_ filter is simply bugged and it is not related to the blending handling. Because there is no math that can do the 0+16=71 (nonlinear+nonlinear=nonlinear), the values should be back gamma applied. The "71" - is a raw linear result as I see. So, it behaves like nonlinear+nonlinear=linear. As workaround, you can apply new _Color Correction_ filter with the _Gamma_: -1.25 (or about).

Also, I did remark in the https://github.com/obsproject/obs-studio/issues/4989 that users don't understands that opacity spinner in no longer linear in the human's view. So if user sets 0.5 opacity it "should" do the gamma applied middle not the true middle. Because we look on the screen by our own eyes and constantly comparing it to the "feel" of the 0.5. So, some UI spinners should not go linear (my opinion).
