### ISSUE TITLE
Developer cannot modify OBSBasic.ui

### ISSUE THREAD

**Issue by laoyebisheng** [obsproject/obs-studio#5053]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

no

### Expected Behavior

I want to modify OBSBasic.ui the layout. 
I want  add some buttons!
 But  if  button is added, an error will be reported after recompiling. The error says it can't be found 
"error C2039: "previewDisabledWidget": not a member of "Ui::OBSBasic""

### Current Behavior

![obs bug](https://user-images.githubusercontent.com/30955451/127778132-33f4b1af-6b91-4699-8ef9-6f4711a207da.png)
1>mocs_compilation_Debug.cpp
1>E:\Git\obs-studio\UI\window-basic-main.cpp(233,6): error C2039: "previewDisabledWidget": not a member of "Ui::OBSBasic"
1>E:\Git\obs-studio\VS2019\UI\ui_OBSBasic.h(1322): message: see the statement of "Ui::OBSBasic"
1>E:\Git\obs-studio\UI\window-basic-main.cpp(234,6): error C2039: "contextContainer": not a member of "Ui::OBSBasic"
1>E:\Git\obs-studio\VS2019\UI\ui_OBSBasic.h(1322): message: see the statement of "Ui::OBSBasic"
1>E:\Git\obs-studio\UI\window-basic-main.cpp(436,6): error C2039: "previewDisabledWidget": not a member of "Ui::OBSBasic"
1>E:\Git\obs-studio\VS2019\UI\ui_OBSBasic.h(1322): message: see the statement of "Ui::OBSBasic"
1>E:\Git\obs-studio\UI\window-basic-main.cpp(437,14): error C2039: "previewDisabledWidget": not a member of "Ui::OBSBasic"
1>E:\Git\obs-studio\VS2019\UI\ui_OBSBasic.h(1322): message: see the statement of "Ui::OBSBasic"
1>E:\Git\obs-studio\UI\window-basic-main.cpp(1843,6): error C2039: "contextContainer": not a member of "Ui::OBSBasic"
1>E:\Git\obs-studio\VS2019\UI\ui_OBSBasic.h(1322): message: see the statement of "Ui::OBSBasic" 

### Steps to Reproduce

1.open OBSBasic.ui by Qt Designer
2.add  pushbutton to centralwidget
3.compiling
4.log out error

...

### Anything else we should know?

VS2019+QT5.15.2

**Comment by Fenrirthviti** [comment]
Please use the Discord for issues building OBS. the .ui files are automatically generated by Qt, and should probably not be manually edited like this.

**Comment by laoyebisheng** [comment]
I can't understand your answer.
When I was developing obs in the past（25.0.0&&26.1.0）, I can modify  OBSbasic.ui by  Qt Designer

**Comment by laoyebisheng** [comment]
> Please use the Discord for issues building OBS. the .ui files are automatically generated by Qt, and should probably not be manually edited like this.

I can't understand your answer.
When I was developing obs in the past（25.0.0&&26.1.0）, I can modify OBSbasic.ui by Qt Designer
