### ISSUE TITLE
Obs crashes when restoring after minimizing on Wayland/Linux

### ISSUE THREAD

**Issue by shanefagan** [obsproject/obs-studio#5054]
### Operating System Info

Ubuntu 21.04

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/_et90OEb1ewFYc3U

### Expected Behavior

To select the window and show obs 

### Current Behavior

Just for it not to crash when I tab in or select the window. The last line of the log might hint that it's a Wayland issue but it doesn't give much info about what broke

> The Wayland connection broke. Did the Wayland compositor die?

### Steps to Reproduce

1. Start streaming with obs
2. Go minimize the window a few times over the course of the stream
3. alt-tab back in or click the icon
4. Obs crashes

It is very reproducible on my system if you want to send me instructions on what to do to get more verbose logs

**Comment by kkartaltepe** [comment]
This is a bug in Qt and being fixed upstream.

**Comment by hollunder** [comment]
> This is a bug in Qt and being fixed upstream.

Do you have any reference to the QT bug? I did not find anything but it would be nice to know when the fix will be released.

**Comment by kkartaltepe** [comment]
https://github.com/obsproject/obs-studio/issues/4295
