### ISSUE TITLE
CEA captions don't work when using the AMD Hardware encoder

### ISSUE THREAD

**Issue by ulysso** [obsproject/obs-studio#5055]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/SZsjFH95YbU6_olH

### Expected Behavior

Captions work just like with all other encoders.

### Current Behavior

CEA captions don't work on Twitch when using the AMF Hardware encoder. When switching to x264 or Quicksync without changing anything else they work right away.

### Steps to Reproduce

1. enable Captions (Experimental), (or Google captions plugin, or Webcaptioner with OBS Websocket plugin)
2. set the encoder to AMD hardware encoder
3. no captions show up on Twitch

### Anything else we should know?

Ran into this when trying to set up captions on a friends PC with OBS 27.0.1 and it seems like this is a known problem with the AMD encoder but I couldn't find any tracking issue for it yet so thought I'd make this. Seems more appropriate here than the AMD encoder repo since the captions get embedded in OBS itself.

Since logs appear to be required for opening an issue I linked ones taken from the OBS google captions plugin issue about this. People there using a RX 560 and RX 5700 XT, my friend has a AMD 580 so seems to effect AMD encoder in general.
Other logs from that thread:
https://obsproject.com/logs/MpbH__GvwDUahyhG
https://obsproject.com/logs/9AbRaWoLKhR4wD81
https://obsproject.com/logs/SZsjFH95YbU6_olH

I don't have an AMD card myself so can't provide logs from OBS 27.0.1 but the issue still persist with it. Various people on Twitter mentioning this issue with the AMD encoder too so should hopefully be easy to reproduce for anyone with an AMD card.

**Comment by gxalpha** [comment]
This issue is about the AMF encoder which got replaced with a complete rewrite in OBS 28.
If it still happens in OBS 29 with the new encoder, please open a new issue with new logs, Steps to Reproduce, etc.
