### ISSUE TITLE
Intel QSV broken

### ISSUE THREAD

**Issue by felix-22** [obsproject/obs-studio#5059]
### Operating System Info

Other

### Other OS

Windows 7 SP1 64

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/i6zTN04IdQcwFhGk

### Expected Behavior

Intel QSV working

### Current Behavior

Intel QSV broken

### Steps to Reproduce

1. Start recording
...

### Anything else we should know?

Some people on OBS forum said QSV is broken due to bugged intel GPU drivers and they reccomend to install an older Intel GPU driver, so I have tried on the following Intel GPU driver versions, but it made no difference:

10.18.14.4294 (2015-09-25)
10.18.14.4578 (2017-01-04)
10.18.14.5143 (2020-05-15)
10.18.14.5180 (2021-03-09)

**Comment by WizardCM** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

**Comment by felix-22** [comment]
1. As if you didn't notice...this is not a support question, I'm reporting a OBS's bug: broken QSV encoding feature (hard to say whether it's for sure an OBS's bug, perhaps it might be a Intel GPU driver's bug)
2. Before I filled the bug here, I have been trying to ask on https://obsproject.com/forum but it's anit-spam mechanism won't let me in.

**Comment by felix-22** [comment]
Look:

<details not-open>
<summary>screenshoot</summary>


![capture_001_03-08-2021_14-00-17](https://user-images.githubusercontent.com/75935068/128014316-6ea8af7c-1b9a-421a-badd-778b624d6da6.png)
</details>

It says to contact the administrator, but it doesn't say how to contact him...what do I do now?

**Comment by felix-22** [comment]
What a crap and unfirenldy community.

**Comment by dodgepong** [comment]
I've lifted the ban on your account. Our forums have a lot of issues with spam, so we have a pretty aggressive anti-spam system. Apologies for the issues.

**Comment by felix-22** [comment]
Cool ! You are a man ! I appreciate.
