### ISSUE TITLE
Unable to stream (to Twitch), connection failed

### ISSUE THREAD

**Issue by Phoenix616** [obsproject/obs-studio#5062]
### Operating System Info

Ubuntu 20.04

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/xVnFbFpbnUhjWIAD

### Expected Behavior

It to start streaming

### Current Behavior

Doesn't start streaming, shows error message:

![](https://is.papr.best/gkQVETNm.png)

(I'm not using NVenc or AMD as the encoder)

### Steps to Reproduce

1. Connect to Twitch via login
2. Try to start streaming

### Anything else we should know?

I tried pinging the server address from the error log and it is reachable. Also trying any other server or re-logging doesn't work either.

**Comment by Fenrirthviti** [comment]
Please use the Forums or Discord for support questions.

**Comment by Phoenix616** [comment]
Can you explain to me why this is not a bug? It works without issues on other systems.

**Comment by dodgepong** [comment]
Because it works without issues on other systems, it is more likely that you are experiencing an issue with your configuration rather than a bug. Thus, until it can be demonstrated that this is not a configuration issue and is indeed a bug, then we consider it a support question.

**Comment by artur-borys** [comment]
I have the same problem on Manjaro when using obs-studio-browser from AUR. When I removed it and installed obs-studio from community repo, everything works

**Comment by Phoenix616** [comment]
> I have the same problem on Manjaro when using obs-studio-browser from AUR. When I removed it and installed obs-studio from community repo, everything works

I'm a bit sceptical about it being the same issue, mine was solved by disabling the socket loop feature in the profile file directly. For some reason obs loads that one even though it's not compatible with the platform and then doesn't offer a way to disable it in the GUI.
