### ISSUE TITLE
OBS 27.0.1 is unable to send output to any device in Monitor Device.

### ISSUE THREAD

**Issue by Farrukhw** [obsproject/obs-studio#5064]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/od4vr9bP91QJbEfT

### Expected Behavior

It should simply be sending the output to the Default device in the Monitor Device list. I tried selecting other devices including the Voice Meter Virtual devices, but it was always quiet, however displaying the playing the media in the UI.

### Current Behavior

It shows playing the media or taking the Microphone input, but it is unable to send output to any of the devices listed in the Monitor Devices, including the Default one.

### Steps to Reproduce

1. Install version 27.0.1
2. If you have any microphone connected, speak into that. Or add Media Source and play anything (e.g. *.mp3).
3.  Nothing would be heard from any of the Monitor Device(s).
...

### Anything else we should know?

After closing 27.0.1, I downloaded the zipped version 27.0.0, extracted it in a separate folder, and run the program and it behaves as expected i.e. it is able to play the media and the output from the mic can be heard through all the Monitor Devices.
Please note that I've removed all the plugins, previous settings from AppData\Roaming\obs-studio folder, but 27.0.1 was still failing...

**Comment by Fenrirthviti** [comment]
According to that log, you're sending the monitor audio to a virtual audio device name: VoiceMeeter Input (VB-Audio VoiceMeeter VAIO). Recommend changing this to something else or looking at your VoiceMeeter configurations.

In the future, please use the Forums or Discord for support questions. Thanks!
