### ISSUE TITLE
Mac: Apparent QT Issue w/Mixer Window On High-DPI Displays

### ISSUE THREAD

**Issue by jasonmvp** [obsproject/obs-studio#5065]
### Operating System Info

macOS 11.4

### Other OS

It's actually 11.5.

### OBS Studio Version

27.0.1

### OBS Studio Version (Other)

26.1.2

### OBS Studio Log URL

https://obsproject.com/logs/mecJ72XXYidRMSvR

### Expected Behavior

I should be able to interact with the OBS UI whether there's an active stream or not.

### Current Behavior

Usually during a stream, OBS' UI will go unresponsive and the app shows up as "Not Responding" to the OS.  The active stream continues to work, though there's usually a brief drop of data (literally 0 Mbps) when this happens.

I also note warnings from YouTube that I'm sending more data than allowed, and it tells me I'm sending >90Mbit/sec.  I have both numbers set to 50Mbit/sec, so that's another potential symptom.  It's almost as if the OBS process is trying to "catch up" to where it was in the stream after locking up.

The logs are not showing anything useful.  You'll note a small encoder overload.  That literally happened right as I tried to interact with the UI.  It was fine before (and after) that.

### Steps to Reproduce

1. Send a VT H264 Hardware Encoded stream to YouTube
2. While doing so, interact with the UI
3. Wait for the beachball of doom.
...

### Anything else we should know?

Sources:
- NDI input from gaming machine for video (audio complains about buffering but I have it muted)
- Elgato HD60S+ for camera input
- Sound Blaster X7 for audio

4K/60 screen, and stream.  Sending a 50Mbit/sec hardware stream to YouTube.  Machine is a Mac Pro 2019 (tower) with an AMD Radeon Pro Vega II GPU.

**Comment by dodgepong** [comment]
It should be noted that the VT encoder should absolutely not be used for livestreaming due to the lack of CBR (hence the errors on YouTube's side).

**Comment by jasonmvp** [comment]
[obs-lldb.txt](https://github.com/obsproject/obs-studio/files/6938505/obs-lldb.txt)

Ran it again with `lldb` and, during the beach ball o' doom, I CTRL-C'd and `bt all`.  Output snagged and included in the file.  Dunno if any of that will help.

**Comment by jasonmvp** [comment]
Current theory based on suggestions from the Discord channel is that this is due to the Audio Meter dock being re-drawn 30-60 times/second.  At higher resolutions (eg: my 4K display) that's a lot more to re-draw.  The test was to completely disable the dock in question and see if Thread #1 ever hit 100% and locked the UI up.  It hasn't, thus far.

Qt-on-the-Mac bug?

**Comment by RytoEX** [comment]
Can you try to reproduce this with #5233?  If you do reproduce it, can you answer the following:
1. Does it happen less often, more often, or about the same frequency?
2. Is the unresponsiveness period shorter, longer, or about the same?
3. Is the unresponsiveness effect less severe (e.g, UI is laggy, but not totally locked up), more severe (not sure how it could be worse than locking up, crashing?), or about the same?

**Comment by jasonmvp** [comment]
> 1. Does it happen less often, more often, or about the same frequency?

My one run with it says "less often" but I can't say by how much.  When I first ran it with the mixer window visible, Thread #1 marched right up to "100%" in the XCode debugger.  It never fully hit 100%, but as it was bouncing around +90% consistently I hit the "Settings" button and: beach ball of doom.

> 2. Is the unresponsiveness period shorter, longer, or about the same?

About the same.

> 3. Is the unresponsiveness effect less severe (e.g, UI is laggy, but not totally locked up), more severe (not sure how it could be worse than locking up, crashing?), or about the same?

The UI completely locked up for a couple of seconds.  During that time, Thread 1 was plateau'd at 100%.  After the beach ball went away and the UI become responsive again, the thread utilization dropped back down to "noise" level.  But over time, it started ramping back up again.

**Comment by Mwoodin123** [comment]
I think someone is trying to hack my email.
On Fri, Nov 12, 2021 at 8:14 AM M W ***@***.***> wrote:

> --
Matthew Woodin iPhone

**Comment by RytoEX** [comment]
Closing as there has been no response. If this is still occurring in the latest stable version of OBS Studio (29.1.1 at time of writing), please provide a new OBS log and ideally provide an Instruments trace.
