### ISSUE TITLE
Pipewire Screen Capture can't capture full-screen applications

### ISSUE THREAD

**Issue by fabriciojardim** [obsproject/obs-studio#5070]
### Operating System Info

Other

### Other OS

Fedora Workstation 33

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/zdoQiBaLEamsSmyt

### Expected Behavior

For simplicity, when you add your screen as a source it should capture everything it displays, including full-screen applications. I Have no idea how to make this possible.

### Current Behavior

When your source is a Pipewire Screen Capture and you run a full screen application the output is either a black screen or a frozen frame. Currently the only way to capture the content of a full screen application is to add the 'application window' as a source by itself.

I don't know if this is really a bug or just the normal behavior of Wayland compositors or the portals API or something else...

Either way it is not ideal for the following reasons:

1. Getting a black/frozen frame during a session can be frustrating and confusing.

2. It is impracticable and sometimes impossible to make a record or transmission that shows the switching between your desktop or a full-screen application (Retroarch or Steam Big Picture for instance) and another full-screen application (a game).

### Steps to Reproduce

1. Add Pipewire Screen Capture as your video source
2. Start recording
3. Launch a full-screen application on your selected monitor (as Retroarch in full-screen mode or Steam in Big Picture Mode)

### Anything else we should know?

**Users workaround:**

Some applications have a full-screen windowed mode where the application behaves as a window but looks like full-screen.

**System:**
Fedora Workstation 33
Gnome/Mutter 3.8.5
OBS 27.0.1 from Flathub

**Comment by kkartaltepe** [comment]
You should report this to your compositor/xdg-desktop-portal implementation's bug tracker. We only play the stream that is provided by the xdg-desktop-portal so when it stops sending data we dont render anything.

**Comment by fabriciojardim** [comment]
> You should report this to your compositor/xdg-desktop-portal implementation's bug tracker. We only play the stream that is provided by the xdg-desktop-portal so when it stops sending data we dont render anything.

Thanks for your input. Reported on xdg-desktop-portal. Hopefully this will help.

**Comment by fabriciojardim** [comment]
I'm waiting to test but this issue is supposed to be fixed now 😊.

Thanks!

https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1914
