### ISSUE TITLE
VirtualCam DAL Plugin Installation status: (null)

### ISSUE THREAD

**Issue by fredguth** [obsproject/obs-studio#5088]
### Operating System Info

macOS 11.4

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/MaGYRgdf3o0BWQHr

### Expected Behavior

OBS Virtual Camera should Appear in Zoom and other apps.

### Current Behavior

Option does not appear in any app.

### Steps to Reproduce

1. Removed previous OBS installation
1.1. `rm  -rf /Applications/OBS.app &  rm -rf ~/Library/Application\ Support/obs-studio`
1.2. checked that `/Library/CoreMediaIO/Plug-Ins/DAL` is empty
2. installed current official version
2.1. downloaded latest obs-studio version from website (27.0.1)
2.2. run `obs-mac-27.0.1.dmg`, move OBS.app to Applications folder
2.3.Start obs-studio > auto-configuration wizard optimize for recording > apply settings
2.4 Create Scene with video capture
3. click ' Start Virtual Camera' (no UI difference noted, how do I checked it started?)
4. Checked in Zoom (not working)
5. Uploaded log
...

### Anything else we should know?

- Macbook Pro M1 arm chip
- I had it working in a previous version (don't recollect which, but it was installed in April)
- I removed the working OBS to try an unofficial M1 compiled Obs.app but had problems with virtual camera (different problem)
- removed version (as explained in steps to reproduce) and tried installing the official version, but still have problems with virtual camera

**Comment by Michael-Brooks** [comment]
Has there been an update on this issue? I'm also having problems with Virtual Camera on the latest Macbook with M1 Max. I'm trying to use it with Discord, and get a black screen.

**Comment by fredguth** [comment]
I eventually had to format my M1 (that is right, format!) to make it work.  I tried everything.  I uninstalled, I deleted folders, I have no idea why the problem occurred and how it was not fixed by uninstalling OBS.  Formatted mac and it started working. :-/

**Comment by RytoEX** [comment]
> no UI difference noted, how do I checked it started?

What do you mean by this? The "Start Virtual Camera" button in the UI should take on a "pressed" appearance and the text should change to "Stop Virtual Camera" to indicate that it has been started.

That said, the Virtual Camera in OBS Studio 28.0.2 works fine in Chrome and Firefox. You may want to report the issue to Zoom, Discord, or whatever other apps cannot load the Virtual Camera.

**Comment by fredguth** [comment]
I will close this issue because now there is a M1 version of OBS which works fine.
