### ISSUE TITLE
Lagged audio viewer / audio mixer Windows 11

### ISSUE THREAD

**Issue by TheCiROMG** [obsproject/obs-studio#5097]
### Operating System Info

Other

### Other OS

Windows 11 x64 (Latest Dev Build)

### OBS Studio Version

27.0.1

### OBS Studio Version (Other)

-

### OBS Studio Log URL

None for now, fully working 100%

### OBS Studio Crash Log URL

None for now, fully working 100%

### Expected Behavior

The display would have to be fluid, 60fps

### Current Behavior

But when viewing the obs, the display lowers its fluidity, it looks stuck, just that

### Steps to Reproduce

None, it's just opening the OBS

### Anything else we should know?

The program works entirely with Windows 11 (taking into account that it is Windows 10, but with some things changed)

**Comment by gxalpha** [comment]
There is a known issue with the preview in Windows 11, try turning the preview off.

**Comment by TheCiROMG** [comment]
Excuse the question, but where is that ?, preview?

**Comment by IonicEcko** [comment]
I can confirm this bug across two seperate machines on the BETA branch of Win11 - the one releasing shortly. Although while gxalpha is right, turning off the preview fixes it, so does undocking the audio monitor with the preview still active. I couldn't find the preview issue gxalpha mentioned so am posting here.

**Comment by IonicEcko** [comment]
Found it... #4807
