### ISSUE TITLE
Remote media source works incorrectly for PNG-images

### ISSUE THREAD

**Issue by CSMBY** [obsproject/obs-studio#5101]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/Gx_eJ5JP86B4YATX

### Expected Behavior

Image loads immediately, refresh does not cause blinking

### Current Behavior

In version 26, a bug appeared - a remote media source that downloads an PNG image started doing it with a delay of 1-5 seconds. The image is updated in the same way, but with the blinking of the image on the screen. In addition, the image periodically reloads itself, with blinking and a delay of 1-5 seconds. This bug was not fixed in version 27. In version 25 everything works perfectly

### Steps to Reproduce

To repeat the bug is very simple - create a media source and specify as input, for example https://upload.wikimedia.org/wikipedia/commons/8/86/OBS_26.1_Screenshot_EN_2020.12.27_-_15.28.46.07.png

**Comment by notr1ch** [comment]
This is by design. A HTTP URL in a media source is treated as a stream, when the response ends, OBS thinks the stream has terminated and will try to reconnect. If you want to display a static PNG, download it and use a local file source instead of a URL.

Introduced in https://github.com/obsproject/obs-studio/pull/3864

**Comment by CSMBY** [comment]
A strange decision to break compatibility. Why not just add a checkbox with the reconnect / not reconnect option? And leave the old behavior with the new one?

**Comment by notr1ch** [comment]
A strange decision to put website URLs in the media source too! That definitely was not the intended use and probably not something we want to support. You can use the browser source if you want a supported way to load website URLs.

**Comment by CSMBY** [comment]
This website example was just an example. In the real world, there is a remote rendering server that prepares the graphics for OBS and OBS downloads those graphics. Now I have to make an agent that will download this graphics to disk for OBS. The developers changed the behavior of OBS to please some special occasion and broke many other systems. Therefore, this is a bug for many systems, and not by design.

**Comment by dodgepong** [comment]
> In the real world, there is a remote rendering server that prepares the graphics for OBS and OBS downloads those graphics.

I'm curious about this workflow because I don't know that that I've ever heard of it, or at least ever heard of it being deliverd via media source URL.

> The developers changed the behavior of OBS to please some special occasion and broke many other systems. Therefore, this is a bug for many systems, and not by design.

You're arguing that your use case is more common than people using the media source to play back remote streaming sources, and I'm sorry but I'm just not buying it. Your use case sounds much less common, and even then I'm not convinced that the correct solution to your problem is to permit loading static images via a web URL in the media source.

**Comment by CSMBY** [comment]
Maybe I'm doing something wrong, but I need to solve two problems:
1. Delivery of static images over the network to OBS. Since version 26+ this has become impossible. Or is there another way? Why do you think that the delivery of pictures over the network is bad? Good graphics require powerful rendering workstations and it is not always possible to do this on the same machine as OBS. In version 25, it was possible to display graphics by simply switching scenes, OBS downloaded automatically updated images over the network.
2. Display pictures in APNG format. Now this can only be done through media source. Or use GIF, but it looks completely unpresentable due to the color depth of 8 bits.

**Comment by dodgepong** [comment]
I'm not saying delivering static images over the network is bad, I'm saying that using the media source to do this is bad. Have you tried using the browser source, as R1CH suggested? It's designed for fetching content from a remote URL.

**Comment by CSMBY** [comment]
Browser sourсe is the first one used. Unfortunately, this option works very, very slowly and consumes a lot of resources.

**Comment by CSMBY** [comment]
And in general, as I understand it, now media source only works with live streams. If we have a regular video as a source, we will have the same bugs. The problem is not only with static images, but with any source that has an end.
It was a very strange decision to do this. Someone faced a problem with live streams, and the developers, instead of making a new option, just broke everything else.
