### ISSUE TITLE
Audio drop-outs/stutters using audio-interface, happens with OBS Studio only

### ISSUE THREAD

**Issue by drake5000** [obsproject/obs-studio#5106]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/lM41QUmjbXR5bb-n

### Expected Behavior

Audio flow should be without any stutters

### Current Behavior

Audio drop-outs/stutters using audio-interface, happens with OBS Studio only

### Steps to Reproduce

Every time I record/stream with audio-interface, both "desktop" audio and input (mic) audio track constantly and randomly (every 3-5 minutes) drops out for a short period of time, which sounds like stutter or click.

### Anything else we should know?

While using audio-interface Behringer UMC204HD with OBS Studio, audio (both microphone and windows audio tracks) constantly and randomly (every 3-5 minutes) drops out for a short period of time, which sounds like stutter or click. On the spectrogram it looks like this:

[https://i.imgur.com/oLhlLQd.png](https://i.imgur.com/oLhlLQd.png)

Most of the time the length of these drop-outs is 20 ms.

These steps were taken in order to localize the issue:

- trying different USB-cables
- trying different USB-ports, as well as self-powered USB-hubs
- running OBS with Admin privileges
- trying different OS, PC, notebook
- setting different sample rates (44100/48000)
- trying different windows audio optimizing guides (High Performance mode, disabling USB power management etc.)
- routing everything through Voicemeeter Banana in every kind of way (I promise I tried everything in there)
- routing mic signal via VB-cable through Reaper

In OBS:

- trying different codec (x264, NVENC), FPS, way of audio capture (settings vs source)
- trying ASIO capture plugin
- trying ffmpeg with WAV (PCM) as audio codec

...and many many other things that I already forgot. But I promise, I tried A LOT.

Now let's look at situations when this DOESN'T happen:

- while recording in a DAW (Reaper, Adobe Audition, Audacity / ASIO, WASAPI, MME)
- while recording in XSPLIT (!!!)
...and the most interesting:
- while recording in OBS Classic !!!!!!
huh???
I guess this might be some algorithm/codec/core process of OBS studio (which apparently absent in Classic version). What could that be?

After all these tests I plugged in my Blue Yeti USB microphone - same issue. Audio drop-outs while using OBS Studio. Then I managed to find another interface (borrowed an ancient M-Audio Fast Track from a friend). Same again. 
Another thing. One time I was able to reproduce and intensify these particular 20ms drop-outs by messing up sample rates (48000 in one setting and 44100 in another). Maybe this suggests something in OBS recording/encoding/syncing algorithms makes audio-device to re-switch its sample rate?

What's going on here?

I was on the brink of buying another interface, but now I understand there's zero point doing that.

There were quite a few topics about same issue, with this one most similar to mine:
[https://obsproject.com/forum/threads/audio-dropouts-when-recording.123058/](https://obsproject.com/forum/threads/audio-dropouts-when-recording.123058/)

My system is Windows 10 21H1 and CPU - i7 7700K.

Thank you

**Comment by Fenrirthviti** [comment]
Please use the Discord or Forums for support, thanks!
