### ISSUE TITLE
OBS using UDP for RTSP (VLC) and cause a lot of glitches

### ISSUE THREAD

**Issue by GiovanniG11** [obsproject/obs-studio#5108]
### Operating System Info

Windows 10

### Other OS

Win7 64

### OBS Studio Version

27.0.1

### OBS Studio Version (Other)

also 26.1

### OBS Studio Log URL

https://pastebin.com/jPs1tzFr

### Expected Behavior

Open an RTSP stream with TCP protocol, as it possible in VLC when selected "rtp over rtsp"

### Current Behavior

OBS opens always on UDP, generating lot of glitches, the same cameras (different models) opened on VLC in UDP produces same results (even disconnections), but on TCP they work fine. I've sniffed packets in all circumstances, I verified it.
There is a way to overcome this and force OBS use TCP?

### Steps to Reproduce

1. Open an RTSP stream with OBS from a camera
2. Check with sniffer the UDP packets

**Comment by stopforumspam** [comment]
obs is unstable with UDP stream for rtsp, hence my PR at 

https://github.com/obsproject/obs-studio/pull/4967

until someone decides to merge the PR, your options are limited

In the past I've used `rtsp_simple_server` to be the server, and ffmpeg to connect to the camera using the `--rtsp_transport tcp` to connect to the camera and then stream to `rtsp_simple_server` although you could probably do that with the `--listen` ffmpeg directive but I've not tried that myself.

**Comment by GiovanniG11** [comment]
thank you, it works for me and it can be enough for now :)
Unfortunately I've to map again (from VLC source) to ffmpeg 86 sources (( 
There is another important interesting issue to beeing solved on OBS, the chance to change volume of RTSP sources in every single scene, now when you change somewhere it reflects in all other scenes. Do you know maybe how to?
Thanks

**Comment by stopforumspam** [comment]
profiles are stored in `%appdata%\Roaming\obs-studio\basic\profiles\<profilename>\service.json` so its a case of edit and search/replace

I'm not sure there is any automated replace ability/code
