### ISSUE TITLE
Recording unnecessary audio tracks

### ISSUE THREAD

**Issue by chticer** [obsproject/obs-studio#5109]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/vo432G0r51U3U8Qt

### Expected Behavior

After recording, unused audio tracks should not be included in the file. This was the expected behavior up to 26.0.2.

### Current Behavior

After recording, all audio tracks selected to record are included in the file, even if the track has nothing in it. This has been the case since 26.1.0.

### Steps to Reproduce

1. Select the audio tracks to record in settings.
2. Make a recording that does not include at least one audio track selected in settings.
3. View the recording in a video editor or ffmpeg, which should show all audio track names that were selected to record.

### Anything else we should know?

This is the log from the last expected behavior that I have knowledge of: https://obsproject.com/logs/aHVLsYlkCF4ZZb19

This is the log from the first current behavior that I have knowledge of: https://obsproject.com/logs/huoBYNVKkYjHSneT

I looked at the change log from 26.1.0 and did not see anywhere if this change was intentional. If this is by design, feel free to close this issue.

**Comment by derrod** [comment]
The behaviour regarding audio tracks has not changed and there was no change between 26 and 26.1 (I also tested 25 and 26 just to be sure).

It wouldn't make sense to not record empty tracks either as users can enable sources on those tracks after starting the recording. If they were automatically discarded the data would be lost.
