### ISSUE TITLE
Everything is upside down and I have no idea why.

### ISSUE THREAD

**Issue by vizthex123** [obsproject/obs-studio#5111]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/W6LXyxCh_PfBLwZz

### Expected Behavior

I expected it to be rightside-up.

### Current Behavior

It's upside-down.

### Steps to Reproduce

1. Open OBS
2. Start recording anything (it happened with Minecraft for me)

### Anything else we should know?

Here's a screenshot of it recording the game properly (after I flipped it horizontally), but the mouse is captured upside-down:
![image](https://user-images.githubusercontent.com/31721920/128963479-0d5a3b70-c9d7-4d12-acc8-d86e0f20b6ee.png)

It's supposed to be even with the "Basic Cooking" research I'm highlighting.

**Comment by Fenrirthviti** [comment]
Please use the forums or Discord for support.
