### ISSUE TITLE
Audio/Video filters can't be added to Window Capture

### ISSUE THREAD

**Issue by VazMike** [obsproject/obs-studio#5136]
### Operating System Info

macOS 11.4

### OBS Studio Version

27.0.1

### OBS Studio Log URL

not necessary.

### Expected Behavior

Either remove the UI component for adding the filters or make the work.

### Current Behavior

There is an option to add Audio/Video filters to Window Capture.
But when you click OK nothing is added.

### Steps to Reproduce

1. Add Window Capture source
2. Try adding any audio/video filter

**Comment by jp9000** [comment]
Window capture has no audio, so audio filters aren't going to do anything. And the video filters probably aren't something you'd want to use with window capture. I think what you're looking for are the effect filters.

**Comment by WizardCM** [comment]
"Video Delay (Async)" works correctly, so filters themselves work on this source just fine. I do agree audio filters (such as Compressor) shouldn't appear in the dropdown if the source doesn't support audio.

**Comment by WizardCM** [comment]
After further testing, I can confirm that Audio filters are not correctly filtered out of the dropdown if a source supports `OBS_SOURCE_ASYNC_VIDEO` but not audio. They're clickable, but once you've set a name and click OK the filter is immediately deleted from the source as it's not compatible.
