### ISSUE TITLE
OBS_PROPERTIES_DEFER_UPDATE does not properly work for scripts

### ISSUE THREAD

**Issue by serializingme** [obsproject/obs-studio#5139]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/FjsVbgdGv7X53Zwa

### Expected Behavior

If the `OBS_PROPERTIES_DEFER_UPDATE` flag was set on the properties created in the `script_properties` function, the `script_update` should be called once when the "Scripts" window is closed.

As per OBS API [documentation](https://obsproject.com/docs/reference-properties.html): "OBS_PROPERTIES_DEFER_UPDATE - A hint that tells the front-end to defers updating the settings until the user has finished editing all properties rather than immediately updating any settings."

### Current Behavior

With the `OBS_PROPERTIES_DEFER_UPDATE` flag set, the `script_update` function is only called when the script is loaded, afterwards it is **never** called even if the settings are changed when the "Scripts" window is closed.

Looking at the [source code](https://github.com/alibaba/tblive/blob/master/libobs/obs-properties.h#L43), it states: "Only update when the user presses OK or Apply". However, the "Scripts" window only has a "Close" button. I think this is the root cause.
To be noted that changes in the settings are still persisted as they would if the `OBS_PROPERTIES_DEFER_UPDATE` wasn't set.

### Steps to Reproduce

1. Add the script below to OBS.
2. Change the setting defined.
3. Notice how the `script_update` is not called.

### Anything else we should know?

Script to replicate the issue.
```
import obspython as obs

def script_description():
	return "Test script."

def script_update(settings):
	print("Called script_update")

def script_defaults(settings):
	obs.obs_data_set_default_string(settings, "message", "Hello!")

def script_properties():
	props = obs.obs_properties_create()
	obs.obs_properties_set_flags(props, obs.obs_properties_get_flags(props) | obs.OBS_PROPERTIES_DEFER_UPDATE)
	obs.obs_properties_add_text(props, "message", "Message", obs.OBS_TEXT_DEFAULT)
	return props
```

**Comment by serializingme** [comment]
Small update, this for sure affects LUA scripts as well. Possible solution could be to check on the `ScriptsTool::on_close_clicked()` function if the current `ScriptsTool::propertiesView` is of type `OBSPropertiesView` and call the `OBSPropertiesView::cb` callback. Not sure how to check if the settings were changed though.

Any ideas/opinions?

**Comment by fzwoch** [comment]
I think this is similar to regular filter properties too. They just have a `Close` button and `OBS_PROPERTIES_DEFER_UPDATE` here will cause the properties of the filters to never update. That is unless one creates some kind of `Apply` button in the properties that calls `obs_properties_apply_settings()` manually.
