### ISSUE TITLE
LIBOBS Loading minimum OpenGL 3.3.0

### ISSUE THREAD

**Issue by PeterAkakpo** [obsproject/obs-studio#5142]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

not applicable

### Expected Behavior

Libobs should load the maximum supported OpenGL version of the graphics card instead of loading version 3.3.0 always

I understand opengl is not advisable on window, but still the maximum supported opengl version must be loaded.

### Current Behavior

lLibobs is always loading opengl version 3.3.0 even though the card supports version 4.6 with latest drivers installed.

06:17:03.467: Initializing OpenGL...
06:17:03.568: Loading up OpenGL on adapter NVIDIA Corporation NVIDIA GeForce GT 710/PCIe/SSE2
06:17:03.568: OpenGL loaded successfully, version 3.3.0 NVIDIA 471.68, shading language 3.30 NVIDIA via Cg compiler
06:17:03.568: Warning: The OpenGL renderer is currently in use.  On windows, the OpenGL renderer can decrease capture performance due to the lack of specific features used to maximize capture performance.  The Direct3D 11 renderer is recommended instead.

### Steps to Reproduce

1.  setup "obs_video_info" with renderer set to "libobs-opengl"
2. 
3.
...

**Comment by derrod** [comment]
> I understand opengl is not advisable on window, but still the maximum supported opengl version must be loaded.

There's one thing you haven't answered in this issue and that is: Why?

OBS doesn't need anything higher than 3.3 so what are the benefits of using something higher?

**Comment by Fenrirthviti** [comment]
Closing per above comment, OBS doesn't require anything more than 3.3 so loading higher versions has no benefit. This appears to be a mistaken assumption that loading an older version is somehow less performant or worse, which it is not, it's effectively setting the feature set available to the application.
