### ISSUE TITLE
OBS does not fully shut down, cannot perform two recordings in a session

### ISSUE THREAD

**Issue by pratyakshm** [obsproject/obs-studio#5146]
### Operating System Info

Other

### Other OS

Windows 11

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/lTYkez5s5CJ80MSN

### Expected Behavior

1. Multiple screen recordings work in one session.
2. OBS Studio shuts down all processes once I tap "Exit" from the OBS Studio app icon in tray.

### 1. OBS Studio can only perform one screen recording per session. 
After I start and stop recording, I cannot repeat the same (Start and stop another recording) throughout current session. I MUST have to shut down OBS and relaunch it again.
### 2. OBS Studio does not exit
When I right click on OBS Studio app icon in systray, and then click on "Exit", it closes down the app GUI, but the systray icon is still there, and even Task Manager shows an OBS Studio process running, which is consuming about 120MB memory.

### Steps to Reproduce

1. Start OBS Studio.
2. Start screen recording 
3. Stop screen recording 
4. Right click on systray icon > Exit.
- Cannot record again on the current session unless app is restarted.
- App does not shut down when using systray > Exit option

**Comment by notr1ch** [comment]
Downgrade your AMD drivers or switch encoder, this is a known issue in their current AMF encoder. In future, please use the forums or Discord for support issues.

**Comment by pratyakshm** [comment]
I got it. Thank you so much, and apologies for posting this to the incorrect place. Good day.
