### ISSUE TITLE
Settings Window height is more than my screen height

### ISSUE THREAD

**Issue by chrisinhim** [obsproject/obs-studio#5168]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/MlsqgVTdI6HoGoT9

### Expected Behavior

When I click on Settings button on the Controls panel, settings window should open with its height <= screen/display height. So that "OK", "Cancel" and & "Apply" buttons are visible on the screen/display.

### Current Behavior

When I click on Settings button on the Controls panel, settings window is opening with its height > screen/display height. Due to this, "OK", "Cancel" and & "Apply" buttons are going outside of screen/display area.

https://user-images.githubusercontent.com/43258549/130329102-f83f54b2-7ce3-44c1-90cd-fd84ab894aa3.mp4

### Steps to Reproduce

1. Open OBS
2. Click on Settings button on Controls panel
...

### Anything else we should know?

Please find the video attached in the Current Behavior section.

**Comment by RytoEX** [comment]
Please re-test in OBS Studio 28.1.2 (or newer). I cannot reproduce this on OBS Studio 29.0.0 Beta 1 (or OBS Studio 28.1.2).

What is your display scaling set to?
