### ISSUE TITLE
outdated chrome version?

### ISSUE THREAD

**Issue by Aworldc** [obsproject/obs-studio#5173]
### Operating System Info

Other

### Other OS

Windows 7

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/1Mb_KAIXhN8DfiwK

### Expected Behavior

Was using obs. Added a browser source to google.com. Expected google to display normally.

### Current Behavior

In my browser source, google said I should upgrade to the latest version of chrome.
![Cappture](https://user-images.githubusercontent.com/83331712/130373170-a908c244-6f93-45c5-8d17-75ba0c24c00b.PNG)

### Steps to Reproduce

1. add a browser source
2. set it to google.com

### Anything else we should know?

not really

**Comment by RytoEX** [comment]
See https://github.com/obsproject/obs-studio/discussions/3853.

**Comment by Aworldc** [comment]
oh thx
