### ISSUE TITLE
Scrollbar on audio mixer when there's no overflow

### ISSUE THREAD

**Issue by josh-65** [obsproject/obs-studio#5176]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

Not Relevant

### Expected Behavior

There should be no scrollbar

### Current Behavior

There's a scrollbar
![image](https://user-images.githubusercontent.com/26977075/130454681-63a15700-4621-45d4-afda-59a077665425.png)

### Steps to Reproduce

Not Relevant

**Comment by WizardCM** [comment]
This is not a bug, as the code is intentional.

**Comment by josh-65** [comment]
Why is that international? It's just randomly put there when other part don't do that.
