### ISSUE TITLE
VLC 4.0 beta doesn't allow VLC sources in OBS

### ISSUE THREAD

**Issue by Josh-65** [obsproject/obs-studio#5178]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/k-YG5q_6uVyF8O1J

### Expected Behavior

VLC source should show up for adding

### Current Behavior

Doesn't show in Add source

### Steps to Reproduce

1) Download vlc 4.0 (https://artifacts.videolan.org/vlc/nightly-win64/)
2) Try adding source in OBS
3) See that VLC source doesn't show

**Comment by jp9000** [comment]
We'll add VLC 4 support eventually. ...And a API version check.

**Comment by RytoEX** [comment]
This is a feature request rather than a bug. The VLC source in OBS is designed to work with VLC 3. VLC 4 support will be added when VLC 4 is ready. Feel free to test the linked PR, but we will revisit the topic when VLC 4 is finalized and released.
