### ISSUE TITLE
Crash at first start after system restart

### ISSUE THREAD

**Issue by mcDandy** [obsproject/obs-studio#5179]
### Operating System Info

Other

### Other OS

Windows 11 (22000.160)

### OBS Studio Version

27.0.1

### OBS Studio Log URL

Got empty error box with error text in header

### OBS Studio Crash Log URL

https://obsproject.com/logs/e16VFstpXxpc3_hM

### Expected Behavior

To start normally

### Current Behavior

After shutting down computer with OBS probably still running I updated windows (22000.132 -> 22000.160) After hibernation mode period or two I started OBS which showed crash dialog.

### Steps to Reproduce

1. restart PC with OBS running
2. Use hibernation mode?
3. start OBS (crash)
4. attempt to upload log with result of error dialog
...

### Anything else we should know?

The file OBS cannot upload: [2021-08-23 21-21-12.txt](https://github.com/obsproject/obs-studio/files/7034470/2021-08-23.21-21-12.txt)

**Comment by Fenrirthviti** [comment]
This looks to be crashing in LUA, likely a custom script you have loaded?

**Comment by gxalpha** [comment]
Closing as there has been no answer to the question above.
