### ISSUE TITLE
Black rectangle around cursor in PipeWire screen capture

### ISSUE THREAD

**Issue by YaLTeR** [obsproject/obs-studio#5189]
### Operating System Info

Other

### Other OS

Fedora 34

### OBS Studio Version

27.0.1

### OBS Studio Version (Other)

(OBS from Flathub)

### OBS Studio Log URL

https://obsproject.com/logs/ImD5KzQYxQzeDh23

### Expected Behavior

No black rectangle around cursor.

### Current Behavior

When using PipeWire screen capture there's a black rectangle around most cursors:

![image](https://user-images.githubusercontent.com/1794388/130820384-49a5886b-76e3-40c0-a023-1a04f1fc9c58.png)

Cursor in a Windows VM in Boxes:

![image](https://user-images.githubusercontent.com/1794388/130820458-c8aae56f-3dcb-4c5d-ac24-7facef7922dc.png)

This particular cursor in the Windows VM in Boxes has no black rectangle:

![image](https://user-images.githubusercontent.com/1794388/130820570-400182d3-86bc-43e5-8c37-94d25103c4f9.png)

### Steps to Reproduce

1. Add PipeWire screen capture with cursor.

### Anything else we should know?

GNOME 40.4 Wayland; happens both with and without `dma-buf-screen-sharing` experimental feature; has been a thing for a very long while (I don't remember if this bug was ever not present).

cc @GeorgesStavracas

**Comment by kkartaltepe** [comment]
Does this still occur on the latest versions of obs and gnome?

**Comment by YaLTeR** [comment]
Yeah

**Comment by RytoEX** [comment]
Please re-test in OBS Studio 28.1.2 (or newer) with GNOME 43 Wayland.

**Comment by YaLTeR** [comment]
Seems to work fine at the moment on my current laptop, although I don't have access to the machine where I had the bug currently, so I cannot test there. One notable difference is that the machine in question had an RX 580 (which lacks modifier support currently) whereas my current laptop has an AMD APU which does have modifier support.

**Comment by gxalpha** [comment]
We believe that this got fixed at some point. If you (or somebody else) still run into the problem on modern versions of OBS + Gnome, please leave a comment.

**Comment by whao** [comment]
I have been having this issue from the beginning.

![Image](https://github.com/user-attachments/assets/39ecf3be-96f1-4fc1-a4c5-7c2f7a1a24ab)
![Image](https://github.com/user-attachments/assets/4ead7252-599a-41f3-91f7-f1d22852d185)
![Image](https://github.com/user-attachments/assets/cf67b37e-3468-4626-b9aa-715a256db07e)
