### ISSUE TITLE
Can't start a scheduled YouTube event with a stream delay over 14 seconds

### ISSUE THREAD

**Issue by Warchamp7** [obsproject/obs-studio#5199]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.0-rc1

### OBS Studio Log URL

https://obsproject.com/logs/rT_EMqrKkw9S9Oq9

### Expected Behavior

I am able to stream to a scheduled event with a stream delay configured in advanced settings

### Current Behavior

It is currently impossible to ever click the Go Live button with a stream delay >= 15 seconds as the stream is forcefully closed after 14 seconds.

I think this is due to the timeout check in OBSBasic::YoutubeStreamCheck which does not account for a stream delay

### Steps to Reproduce

1. Schedule a YouTube event with YouTube integration
2. Set a stream delay in Advanced settings of 15 seconds or more
3. Click Start Streaming and select the scheduled event
4. Attempt to go live with the selected event

**Comment by derrod** [comment]
Hm adding a `QThread::sleep()` to the thread is fairly straightforward, what I haven't figured out yet is how to deal with the thread if you stop streaming before the delay has been reached because I don't know exactly how OBS handles that.
