### ISSUE TITLE
Weird horizontal line

### ISSUE THREAD

**Issue by LeGmask** [obsproject/obs-studio#5215]
### Operating System Info

Other

### Other OS

ArchLinux

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/E4LvRBGd0C5KyJMP

### Expected Behavior

Not a clean record

### Current Behavior

weird horizontal layout during record
https://youtu.be/jRDXyT00fdM

### Steps to Reproduce

1. Just record
...

### Anything else we should know?

Using x11 and gnome

**Comment by LeGmask** [comment]
Never mind, it's an issue with vlc ....

**Comment by kkartaltepe** [comment]
I dont see anything wrong in the video, perhaps you can provide a better example of what you mean. Otherwise it seems you are probably suffering from bad vsync in linux.
