### ISSUE TITLE
Youtube Stream Category missing Non-Profits and Activism

### ISSUE THREAD

**Issue by Jaiko657** [obsproject/obs-studio#5226]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.0-rc1

### OBS Studio Log URL

https://obsproject.com/logs/uHizETJ1Oz3RI1Zn

### Expected Behavior

Category list when Start Streaming is pressed gives all options that Standard Youtube provides.

### Current Behavior

The Category Option is missing Non-Profits and Activism

### Steps to Reproduce

1. Start Streaming
2. Go to category list
3. Non-Profits and Activism is missing

**Comment by derrod** [comment]
The category list is fetched from YouTube's API. For some reason this does not seem to include that category. But that's not something we can fix.

**Comment by derrod** [comment]
After some investigation: the API for `VideoCategories` does take the `maxResults` parameter, and setting it above 10 now gives us 14 categories, including the previously missing "News and politics", "How-to and style", "Education", "Science and Technology" but "Non-profits and activism" is still absent.
