### ISSUE TITLE
Missing Virtual Cam

### ISSUE THREAD

**Issue by ItsRogueRen** [obsproject/obs-studio#5232]
### Operating System Info

Other

### Other OS

Pop!_OS 21.04 (Ubuntu based)

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/xl71yTDcktgzNfyU

### Expected Behavior

There should be a virtual cam button in the controls menu, which was there in v26

### Current Behavior

No virtual cam button after updating to 27.0.1

### Steps to Reproduce

1. Update to v27.0.1
2. Open OBS
3.
...

### Anything else we should know?

Virtual cam was there on the previous version on both Flatpak and Ubuntu repo, missing when updated from PPA

**Comment by Fenrirthviti** [comment]
01:05:54 PM.595: v4l2loopback not installed, virtual camera disabled

Please use the support channels in the future.
