### ISSUE TITLE
Switching from a streaming service with linked Account to service with stream key leaves account linked

### ISSUE THREAD

**Issue by Gol-D-Ace** [obsproject/obs-studio#5236]
### Operating System Info

Windows 10 (and probably all other)

### OBS Studio Version

27.1.0-rc1

### OBS Studio Log URL

-

### Expected Behavior

The linked account gets unlinked and you can start a stream to the newly selected service with the streamkey.

### Current Behavior

Account stays linked and stream happens to the linked account.

### Steps to Reproduce

1. Connect an account for example YouTube
2. Switch to another service like Twitch for example
3. Click the use stream key option and enter a valid stream key
4. Apply settings and try to start a stream
5. YouTube event creation dialog will open instead of the stream starting on twitch

### Anything else we should know?

Probably happens with all services that have account linking when you switch to another service when using a stream key.

Switch to another service and linking the account will correctly unlink the old account.

**Comment by Gol-D-Ace** [comment]
This is fine in 27.0.1 btw.

**Comment by MattyFresh68** [comment]
I feel like this behavior has happened before on a non RC. Usually suggested in discord support to create a new profile. Seems easy enough but I can also see how that shouldn't be "desired" behavior.

**Comment by Gol-D-Ace** [comment]
Rodney noticed this.
https://github.com/obsproject/obs-studio/commit/e6f1daab8c64aa4cd57c7615647ad80362d72d72#diff-621df1a2159e2ad8daa9ac6e7e08281a19b0578394397d79eabbac55dcd9ea9bL433

If I readd the auth reset in this place additionally the behavior stops.
