### ISSUE TITLE
Failed to open video codec: Unknown error occurred

### ISSUE THREAD

**Issue by rajinder-yadav** [obsproject/obs-studio#5244]
### Operating System Info

Other

### Other OS

openSUSE Tumbleweed

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/FJ3mWZlMGSErVjnd

### Expected Behavior

Start recording like before!

### Current Behavior

See this unanswered thread for the error I was reporting. 

https://obsproject.com/forum/threads/failed-to-open-video-codec-unknown-error-occurred.147288/

### Steps to Reproduce

1. With OBS already open from previous session.
2. Click, "Start recording"

### Anything else we should know?

This problem just show up randomly! Closing and re-opening OBS down doesn't help, I had to reboot which is problematic as I am forced to closed everything in my work flow.

I have installed NVidia propriety Linux driver, version:  "NVIDIA-Linux-x86_64-470.63.01"

Here is my Sysinfo

Operating System: openSUSE Tumbleweed 20210902
KDE Plasma Version: 5.22.4
KDE Frameworks Version: 5.85.0
Qt Version: 5.15.2
Kernel Version: 5.13.13-1-default (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 2700X Eight-Core Processor
Memory: 62.7 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3080/PCIe/SSE2

See logs in the OBS forum thread.

https://obsproject.com/forum/threads/failed-to-open-video-codec-unknown-error-occurred.147288/

**Comment by notr1ch** [comment]
openSUSE Tumbleweed is not an officially supported platform. Please use the forums or Discord for support.
