### ISSUE TITLE
fails to stop recording

### ISSUE THREAD

**Issue by rajinder-yadav** [obsproject/obs-studio#5246]
### Operating System Info

Other

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/FzY78MbrFBusUAoJ

### Expected Behavior

Recording stops when I click on "Stop recording".

### Current Behavior

OBS has been recording my desktop for over 2 hours, when I click on, "Stop Recording", OBS kept recording.

At this point I tried to close the window, it would not close. After a while the system message dialog popped up asking if I wanted to terminate the (hung) application. I said yes, OBS would still not end.

I brought up the process monitor and tried several time to kill OBS from here as well as the command line, the application would not terminate! See screen shot.

### Steps to Reproduce

1. start recording
2. let run for 2 hours
3. click stop recording

![Screenshot_20210905_214742](https://user-images.githubusercontent.com/439226/132150240-c7d43971-cefa-44d7-85b3-fe9cb5a82f98.png)

### Anything else we should know?

Operating System: openSUSE Tumbleweed 20210902
KDE Plasma Version: 5.22.4
KDE Frameworks Version: 5.85.0
Qt Version: 5.15.2
Kernel Version: 5.13.13-1-default (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 2700X Eight-Core Processor
Memory: 62.7 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3080/PCIe/SSE2

**Comment by Fenrirthviti** [comment]
openSUSE is not a currently supported platform. Please use the forums or Discord for support.

**Comment by rajinder-yadav** [comment]
Considering it is still Linux, you don't think this bug warrants any investigation?

**Comment by rajinder-yadav** [comment]
I don't see a list of official supported Linux, where can I find this list?

Under System requirements, which I've met, I see

```
Linux/Unix

OpenGL 3.3 compatible GPU
X window system
```

https://obsproject.com/wiki/System-Requirements

**Comment by Fenrirthviti** [comment]
We only maintain and support packages for Ubuntu. All other distributions of the program are third-party repos, and unsupported by us directly. This issue has unclear replication steps, and seeing as we have a significant portion of Linux users who are not reporting this kind of bug (and it's almost always an environment issue in my experience), we would prefer it go through the normal support channels first as it's not a verified bug. Thanks for understanding!

**Comment by rajinder-yadav** [comment]
Thanks @Fenrirthviti totally understand, I did post on the forum first with zero replies, but will try bumping it again.
