### ISSUE TITLE
sometimes usb mic fails to work

### ISSUE THREAD

**Issue by rajinder-yadav** [obsproject/obs-studio#5247]
### Operating System Info

Other

### Other OS

openSUSE Tumbleweed

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/FmuP7vmS-HmuilVv

### Expected Behavior

detect usb mic (blue yeti) and have it work

### Current Behavior

sometime the mic input doesn't work, i need to close obs and re-open for the mic to work.

this has happened many time, but not always.

```sh
$ lsusb

Bus 004 Device 002: ID 152d:1562 JMicron Technology Corp. / JMicron USA Technology Corp. USB3.0 Device
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 002: ID b58e:9e84 Blue Microphones Yeti Stereo Microphone
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 006: ID 046d:0825 Logitech, Inc. Webcam C270
Bus 001 Device 007: ID 1a40:0101 Terminus Technology Inc. Hub
Bus 001 Device 005: ID 1a40:0101 Terminus Technology Inc. Hub
Bus 001 Device 004: ID 0a12:0001 Cambridge Silicon Radio, Ltd Bluetooth Dongle (HCI mode)
Bus 001 Device 010: ID 04d9:0295 Holtek Semiconductor, Inc. USB-HID Keyboard
Bus 001 Device 009: ID 1d57:ad17 Xenta ZELOTES GAME MOUSE
Bus 001 Device 008: ID 1a40:0101 Terminus Technology Inc. Hub
Bus 001 Device 003: ID 2972:0047 FiiO Electronics Technology FiiO BTR5
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

### Steps to Reproduce

1. open obs
2. talk into mic
3. check sound levels
...

### Anything else we should know?

Operating System: openSUSE Tumbleweed 20210902
KDE Plasma Version: 5.22.4
KDE Frameworks Version: 5.85.0
Qt Version: 5.15.2
Kernel Version: 5.13.13-1-default (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 7 2700X Eight-Core Processor
Memory: 62.7 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3080/PCIe/SSE2

Using Pulse Audio which is set correctly for my mic to be input.

**Comment by Fenrirthviti** [comment]
openSUSE is not a currently supported platform. Please use the forums or Discord for support.
