### ISSUE TITLE
VLC Video Source renders portrait video with incorrect aspect ratio 

### ISSUE THREAD

**Issue by pmcgaley** [obsproject/obs-studio#5250]
### Operating System Info

Windows 10

### Other OS

Also macOS 11.5.2 on M1

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/iMtIcCPaUcbCFDtI

### Expected Behavior

Portrait video from phone (mov/mp4 containing h.264/AVC and h.265/HEVC) should be rendered correctly in VLC Video Source.

### Current Behavior

Video is rotated to the correct orientation, but height and width are taken from the unrotated source, so the image is stretched horizontally.

![image](https://user-images.githubusercontent.com/18594548/132258767-5c5e10f5-7ff5-4f8f-a284-b2341cb59948.png)

### Steps to Reproduce

1. VLC Video Source to a scene.
2. Select the attached video as source.
3. Observe incorrect aspect ratio.

https://user-images.githubusercontent.com/18594548/132258725-4ef35599-fab2-44c3-8262-60d5914ea876.MOV

### Anything else we should know?

Metadata in the affected videos specifies `rotation` of `90` or `270`.

Using VLC source to stream user-uploaded content (which is often but not always taken in portrait on a phone) and "fit to screen" transform, so I can't work around by applying fixed transforms as the media dimensions and orientation change constantly.

VLC itself plays the videos correctly.

Reproduced on Windows 10 and MacOS 15.2.1 on M1.

**Comment by pmcgaley** [comment]
I did some digging and the problem seems to be caused by this code  - VLC video source overrides the preferred height and width coming back from libvlc - if I comment it out the videos render correctly...

```
	/* This is used because VLC will by default try to use a different
	 * scaling than what the file uses (probably for optimization reasons).
	 * For example, if the file is 1920x1080, it will try to render it by
	 * 1920x1088, which isn't what we want.  Calling libvlc_video_get_size
	 * gets the actual video file's size, and thus fixes the problem.
	 * However this doesn't work with URLs, so if it returns a 0 value, it
	 * shouldn't be used. */
	libvlc_video_get_size_(c->media_player, 0, &new_width, &new_height);

	if (new_width && new_height) {
		*width = new_width;
		*height = new_height;
	}
```

https://github.com/obsproject/obs-studio/blob/master/plugins/vlc-video/vlc-video-source.c#L399

**Comment by mycroftcanner** [comment]
This is still happening on a Mac running [OBS Studio 27.2 Release Candidate 1](https://github.com/obsproject/obs-studio/releases/tag/27.2.0-rc1)

all the videos that have a 90 or 270 rotation are stretched. This happens whenever a video was rotated inside the iOS Photos app.

**Comment by pmcgaley** [comment]
@mycroftcanner I have a fix for this on a fork - I mainly got stalled because one of the issues it fixes (aspect ratio of network streams) is no longer reproducible on the test given and I haven't had time to set up another one. The fix is here if you want to take a look/build locally. Otherwise I'll do my best to get back to this but can't make any promises https://github.com/pmcgaley/obs-studio/commit/70f943abc1acb1fc3b6a6ef6edd11a3bd381f07e

**Comment by pmcgaley** [comment]
(also badly needs a rebase)
