### ISSUE TITLE
unmet dependencies

### ISSUE THREAD

**Issue by IronFractal** [obsproject/obs-studio#5259]
### Operating System Info

Other

### Other OS

Pop!_OS 21.04 x86_64

### OBS Studio Version

27.0.1

### OBS Studio Log URL

N/A

### Expected Behavior

OBS to install

### Current Behavior

OBS fails to install with the following unmet dependencies.

`The following packages have unmet dependencies:
 obs-studio : Depends: libfdk-aac1 (>= 0.1.4) but it is not installable
              Depends: libx264-155 but it is not installable
`
Can OBS be updated to depend on libfdk-aac2 & libx264-160 ?? 

### Steps to Reproduce

1. sudo apt install obs-studio
2.
3.
...

**Comment by Fenrirthviti** [comment]
Pop! OS is not a supported platform. Please report to the repository maintainer for your distro to provide the dependencies.
