### ISSUE TITLE
OBS Crash on open when installed web-socket

### ISSUE THREAD

**Issue by djpegg25** [obsproject/obs-studio#5264]
### Operating System Info

macOS 10.13

### OBS Studio Version

27.1.0-rc2

### OBS Studio Log URL

https://obsproject.com/logs/QUHwSAMwIQyTl5or

### Expected Behavior

How can i fix this issues and use web-socket as normal
I try different OBS Version and also web-socket version
But it's not work

Please help

Thanks

### Current Behavior

OBS Keep crashing when open after installed plugin
but when remove from plugins folder
OBS can be open as usual

### Steps to Reproduce

1.
2.
3.
...

**Comment by notr1ch** [comment]
The websocket plugin is not part of OBS Studio's core plugins. Issues with 3rd party plugins should be reported to the plugin author.
