### ISSUE TITLE
Constantly required to "Connect" to Restream.io.  Won't "Keep" Restream.io connection

### ISSUE THREAD

**Issue by iSarge4** [obsproject/obs-studio#5290]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.0-rc2

### OBS Studio Log URL

https://obsproject.com/logs/vSMtl383oC4vEiDb

### OBS Studio Crash Log URL

Not Applicable

### Expected Behavior

After I have properly "Settings -> Stream" "Connect Account (recommended)" to Restream.io, then if I go to "Stream -> Settings" page, it should then show that I am "Connected" to Restream.io.  Should not matter whether I use "Server -> Autodetect" or "Server -> Dallas, TX", it should show that I am still connected to Restream.io.

### Current Behavior

[OBS Latest Log](https://obsproject.com/logs/vSMtl383oC4vEiDb)
[[PrintScrn of Settings -> Stream](https://www.flickr.com/photos/garyberth/51484415818/in/datetaken-public/)]

OBS Studio constantly requires "reconnection".  Worth noting: Even though it displays the "Connect Account" selection available, it appears that it is actually connected to Restream.io regardless.

### Steps to Reproduce

1. Settings -> Stream
2. Select "Restream.io" from the "Service" drop down pick item list
3. Select "Autodetect" or "Dallas, Texas" from the "Server" drop down pick list
4. Click on "Connect Account (recommended)"
5. Provide a valid Restream.io account email.
6. Provide a valid password for the Restream.io account email.
7. Click "OK"
8. Click "Settings -> Stream"
9. Now with "Restream.io" selected as "Service", the "Connect Account (recommended)" reappears.

### Anything else we should know?

Usually, after Step No. 9 above, the "Settings -> Stream" page will show that there is already a "Connected" to the "Service" Restream.io.  That's how it always worked in previous versions of OBS Studio.  Might be worth noting that, although the "Connect Account (recommended)" appears on Step 9 above, the connection to Restream.io has been saved and it works fine with streaming through Restream.io.  It just appears confusing as the "Connect Account (recommended)" appears to make a person think Restream.io isn't connected.

**Comment by Gol-D-Ace** [comment]
Can confirm this. Doesn't appear to happen on Twitch for example.

**Comment by Gol-D-Ace** [comment]
Looks like this got introduced with the YT integration aka commit e6f1daab8c64aa4cd57c7615647ad80362d72d72
