### ISSUE TITLE
OBS cannot capture any video.

### ISSUE THREAD

**Issue by mzso** [obsproject/obs-studio#5298]
### Operating System Info

Windows 10

### OBS Studio Version

26.1.1

### OBS Studio Log URL

https://obsproject.com/logs/rHb040l31yCG1IYj

### Expected Behavior

Video being recorded.

### Current Behavior

No video is recorded. I don't get it. It never worked. Codecs, settings don't matter. No video is ever recorded, meanwhile audio works just fine

Neither does MSI afterburner work when I try record with a VFW codec. Nonetheless, I would at least expect some sort of error message (preferably a useful one) for why video recording fails. But it just happens silently. I get files with video streams devoid of data.

### Steps to Reproduce

I don't really have steps since it appears to have been broken from the get go ever since I first tried OBS on 10.

(On win8.1 I could use MSI afterburner)

**Comment by derrod** [comment]
Github issues are not for support, use our Discord or Forums instead: https://obsproject.com/help

**Comment by LavaDrinker** [comment]
Looks like you only have your Audio Setup. Try adding a source to the scene so that it has something to capture.
- Display capture for your whole monitor. 
- Game Capture for Just the specific game
- Window capture for just the window (like Chrome)
- Video Capture Device for most Cameras/Webcams
![Screenshot_1](https://user-images.githubusercontent.com/32332593/133905118-cca434cd-43bd-4f48-9732-45df39c8250e.png)

**Comment by mzso** [comment]
[**@LavaDrinker**](https://github.com/LavaDrinker) commented on [2021. szept. 18. 20:36 CEST](https://github.com/obsproject/obs-studio/issues/5298#issuecomment-922353180 "2021-09-18T18:36:12Z - Replied by Github Reply Comments"):
> Looks like you only have your Audio Setup. Try adding a source to the scene so that it has something to capture.
> 
> *   Display capture for your whole monitor.
> *   Game Capture for Just the specific game
> *   Window capture for just the window (like Chrome)
> *   Video Capture Device for most Cameras/Webcams  

Wow. Facepalm. That turned out to be trivial.
Thanks!
