### ISSUE TITLE
Obs studio crash at startup after crash while running

### ISSUE THREAD

**Issue by atticus-lv** [obsproject/obs-studio#5300]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/forum/threads/obs-studio-crash-at-startup-after-crash-while-running.148345/

### OBS Studio Crash Log URL

https://obsproject.com/forum/threads/obs-studio-crash-at-startup-after-crash-while-running.148345/

### Expected Behavior

not crash at startup and work as before

### Current Behavior

crash at startup with no error report

### Steps to Reproduce

1.
2.
3.
...
Not sure what cause the problem. May be the cinema 4d r25? But uninstall it didn't solve the problem

**Comment by WizardCM** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
