### ISSUE TITLE
Failed to initialize video:  eglCreateImage not found on nvidia-340xx driver

### ISSUE THREAD

**Issue by alou-S** [obsproject/obs-studio#5302]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://gist.github.com/alou-S/383f457e1539c24453dd6110baa6bb58

### Expected Behavior

Should start without any errors.
Used to start perfectly on version `26.1.2`. Error started from `27.0.0` and still persists on `27.0.1`.

### Current Behavior

Crashes on start with "Failed to initialize video:  Graphics module not found" error and the following error in log
```
error: os_dlopen(libobs-opengl.so.0->libobs-opengl.so.0): /usr/lib/libobs-opengl.so.0: undefined symbol: eglCreateImage

error: Failed to initialize video:  Graphics module not found
```

### Steps to Reproduce

No real steps since the programs crashes right on startup.

### Anything else we should know?

Error seem to be related to the GPU Driver I use since other users with the similar driver have the same issue.

GPU : Nvidia 210
Driver : `nvidia-340xx-dkms`

The error only occurs from version `27.0.1` and doesn't occur in `26.1.2` and previous versions.

**Comment by dromer** [comment]
Heh, I just built the `27.0.1` tag on Debian 11 and I get the same thing.

**Comment by dromer** [comment]
So, for me obs fails to start because the installed libs are named differently from what is expected:

```
-rw-r--r-- 1 root root 1.2M Sep 19 14:15 /usr/lib/libobsglad.so.0
-rw-r--r-- 1 root root 5.9M Sep 19 14:37 /usr/lib/libobs.so.0
-rw-r--r-- 1 root root 272K Sep 19 14:37 /usr/lib/libobs-frontend-api.so.0.0
-rw-r--r-- 1 root root 895K Sep 19 14:37 /usr/lib/libobs-opengl.so.0.0
-rw-r--r-- 1 root root 879K Sep 19 14:37 /usr/lib/libobs-scripting.so
```

Both `libobs-frontend-api` and `libobs-opengl` have an extra `.0` appended. Symlinked to these makes the program start, at least.

**Comment by alou-S** [comment]
@dromer Doesn't seem to be the problem for me since they are already symlinked by default.
```
lrwxrwxrwx 1 root root   24 Jul 10 00:21 /usr/lib/libobs-frontend-api.so -> libobs-frontend-api.so.0
lrwxrwxrwx 1 root root   26 Jul 10 00:21 /usr/lib/libobs-frontend-api.so.0 -> libobs-frontend-api.so.0.0
-rwxr-xr-x 1 root root  30K Jul 10 00:21 /usr/lib/libobs-frontend-api.so.0.0
lrwxrwxrwx 1 root root   18 Jul 10 00:21 /usr/lib/libobs-opengl.so -> libobs-opengl.so.0
lrwxrwxrwx 1 root root   20 Jul 10 00:21 /usr/lib/libobs-opengl.so.0 -> libobs-opengl.so.0.0
-rwxr-xr-x 1 root root 150K Jul 10 00:21 /usr/lib/libobs-opengl.so.0.0
-rwxr-xr-x 1 root root 128K Jul 10 00:21 /usr/lib/libobs-scripting.so
```
Like stated, its more related to the nvidia driver.

**Comment by dromer** [comment]
I just did a fresh install and now I do have the symlinks. For me OBS starts fine when these are in place.

What do you get when you `ldd $(which obs)` ?

**Comment by derrod** [comment]
It would appear that the driver is just too old and doesn't support the EGL features that OBS now requires. Perhaps @GeorgesStavracas knows more.

**Comment by kkartaltepe** [comment]
Provide the list of all extensions from `eglinfo` in the x11 section. But as mentioned its likely that using an outdated driver and nvidias hostile nature to egl means you probably wont have the appropriate egl functions.

Right now you would have to compile obs without any egl support to avoid depending on this functionality.

**Comment by alou-S** [comment]
Here is the EGL info
```X11 platform:
EGL API version: 1.4
EGL vendor string: NVIDIA
EGL version string: 1.4
EGL client APIs: OpenGL_ES
EGL extensions string:
    EGL_NV_system_time EGL_KHR_surfaceless_context EGL_KHR_image
    EGL_KHR_image_base EGL_KHR_gl_texture_2D_image
    EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image
    EGL_KHR_config_attribs EGL_KHR_fence_sync EGL_NV_sync
    EGL_KHR_reusable_sync EGL_KHR_create_context
    EGL_EXT_create_context_robustness EGL_KHR_stream EGL_KHR_stream_fifo
    EGL_KHR_stream_producer_eglsurface EGL_KHR_stream_consumer_gltexture
    EGL_NV_stream_sync EGL_KHR_get_all_proc_addresses
    EGL_IMG_context_priority EGL_NV_post_sub_buffer EGL_KHR_image_pixmap
    EGL_EXT_buffer_age
    ```

**Comment by derrod** [comment]
Seems like `eglCreateImage` was added in EGL 1.5, so you'll need a newer driver (or whatever component provides EGL).

As @kkartaltepe mentioned you could compile OBS yourself without EGL enabled if you want to keep using such an old driver, otherwise you'll have to update to something more recent.

**Comment by alou-S** [comment]
@derrod What would be the current EGL API Version, GLX version and GL version required for running OBS?

Since I don't think EGL is the only thing that is outdated in my GPU driver.

**Comment by Gol-D-Ace** [comment]
OpenGL 3.3 and EGL appears to be 1.5

**Comment by alou-S** [comment]
Nvm I verified and confirmed that GLX has to only be 1.4. But I don't think OpenGL is 3.3 since if it were OBS should work after I removed EGL from the build.

**Comment by Gol-D-Ace** [comment]
1.4 is the newest GLX version available so there is literally nothing newer available that OBS could use.

Same with EGL.

For OpenGL OBS requires 3.3 nowadays (was 3.2 in the past).

**Comment by alou-S** [comment]
Also yeah how do I disable EGL when compiling obs?

**Comment by alou-S** [comment]
Anyway it seems that using the Mesa EGL Library fixes the issue.
```
LD_PRELOAD=/usr/lib/libEGL.so obs
```

But would still like to know how to compile obs with EGL disabled.
