### ISSUE TITLE
 Obs stops broadcasting if a transition occurs with a black screen in the game.

### ISSUE THREAD

**Issue by Adega-Studio** [obsproject/obs-studio#5309]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/bxROXZagxLGJwLY8

### Expected Behavior

I expect not to stop the broadcast if the game changes location through a black screen.

### Current Behavior

 Obs stops broadcasting if a transition occurs with a black screen in the game.

### Steps to Reproduce

1. Capturing a window
2. Start broadcast
3. An empty black transition frame appears in the game and the obs stops broadcasting (
...

### Anything else we should know?

How to fix it?

**Comment by RytoEX** [comment]
There is no stream attempt in this log and the reproduction steps aren't specific enough to be actionable (what streaming service, what capture source type, what encoder, what protocol, etc.).  Without that information, I'm inclined to close this as a support issue and have the issue be investigated via regular support channels first.

**Comment by Adega-Studio** [comment]
> There is no stream attempt in this log and the reproduction steps aren't specific enough to be actionable (what streaming service, what capture source type, what encoder, what protocol, etc.). Without that information, I'm inclined to close this as a support issue and have the issue be investigated via regular support channels first.

Here is the log where the connection is dropped without data from the game https://obsproject.com/logs/lUZuXwiXpEmwglfA

**Comment by Fenrirthviti** [comment]
https://github.com/obsproject/obs-studio/issues/5230 probably related to this, youtube is forcing the connection closed on their end for unknown reasons.

**Comment by flaeri** [comment]
So I spent some time getting pointers from @Adega-Studio in the discord, and have the following information:
* confirmed on both x264 and nvenc
* Its the combination of the large bitrate + black screen
* If you lower the "buffer size" (1/4th for instance) while maintaining the larget bitrate, it does not happen (on x264)

kbps
28 000 breaks (and above I assume)
26 000 and below works (tested 5 different lower ones, no issues)

**Comment by flaeri** [comment]
Here is a log with RTMP and the new Network code. Could maybe be of use.
https://obsproject.com/logs/yfriikmrTI-sS8lh

**Comment by Adega-Studio** [comment]
Reducing the bitrate to 12000 keeps the connection, but the quality is disgusting at 2k. Any ideas what you can do?

**Comment by flaeri** [comment]
@Adega-Studio Please retry now. Its now fixed for me after Youtube has made some changes on their end.

**Comment by Adega-Studio** [comment]
> @Adega-Studio Please retry now. Its now fixed for me after Youtube has made some changes on their end.

26000 2k everything is good). So the topic can be closed.

**Comment by RytoEX** [comment]
Closing per above comments.
