### ISSUE TITLE
Missing hardware encoder support using AMD GPUs

### ISSUE THREAD

**Issue by danger89** [obsproject/obs-studio#5310]
### Operating System Info

Other

### Other OS

Linux Mint 20.2 (Ubuntu 20.04 based)

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/cKnUoKt6ZSoq2-1K

### Expected Behavior

I recently bought a high-end AMD video card (Sapphire Nitro+ Radeon RX 580). 

However, in the settings -> Output, I can not select any **Hardware** as encoder. While Firefox for example does support hardware acceleration with my GPU. 

![image](https://user-images.githubusercontent.com/628926/134047521-110fa82e-c515-4af4-bfdd-d21674b4e988.png)

### Current Behavior

I'm only allowed to use the software encoder: x264. Which cause dropped frames, and eventually give bad performance with YouTube live streaming for example:

![bad_youtube_performance_live_streaming](https://user-images.githubusercontent.com/628926/134047618-289a21ab-8e96-4672-b302-7d6e2cce2bbf.png)

(Translated to English: "YouTube is not receiving enough video..")

### Steps to Reproduce

1. Just use OBS with a GPU video card

### Anything else we should know?

Device: AMD Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] 
Vendor: Sapphire Limited Nitro+
Driver: amdgpu
Kernel:  5.11.0-34-generic #36~20.04.1-Ubuntu x86_64

**Comment by kkartaltepe** [comment]
Please use our discord or forums for support.

No hardware encoders are available in simple mode on linux at this time.

**Comment by danger89** [comment]
Also advanced is causing the issues described above.. Please consider reopening -,-

![image](https://user-images.githubusercontent.com/628926/134049513-212e0ca2-779d-423f-b9fc-f996213f8e6b.png)

**Comment by danger89** [comment]
Nevermind, I'm going to use SimpleScreenRecorder

**Comment by Fenrirthviti** [comment]
We do not handle support requests, as explained in the template, over GitHub Issues. If you have a support question, use the appropriate forum or Discord channel, which is where support is provided. If you want to use another software, by all means.

**Comment by roadapathy** [comment]
I can confirm the same in 30.2.2-77
AMD RX 6700 TX
Nothing but H.264 (Software) available. That doesn't make sense.
