### ISSUE TITLE
obs_frontend_get_transition_duration function has nil value

### ISSUE THREAD

**Issue by cowboy** [obsproject/obs-studio#5313]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/2qxBCG7iDe7xppJ4

### Expected Behavior

In my lua script, I expect `obs.obs_frontend_get_transition_duration()` to return the transition duration.

(Note:  `obs.obs_frontend_get_current_transition()` works just fine)

### Current Behavior

When I call `obs.obs_frontend_get_transition_duration()` in my lua script, I get the following error:

```
 Failed to call frontend_event_callback for frontend API: .../path/to/file.lua:251: attempt to call field 'obs_frontend_get_transition_duration' (a nil value)
```

### Steps to Reproduce

1. Call `obslua.obs_frontend_get_transition_duration()` in a lua script

**Comment by WizardCM** [comment]
What happens if you use `obslua.get_transition_duration()` instead?

**Comment by RytoEX** [comment]
Please provide a sample Lua script that has the described issue. Please also retest in OBS Studio 28.1.2 (or newer) and confirm this is still occurring.

**Comment by cowboy** [comment]
Ok, I haven't upgraded to 28 yet, but once I do, I'll re-test. But FWIW, it was really easy to test, literally just do what's in the steps to reproduce section.

**Comment by RytoEX** [comment]
After adding `obs.obs_frontend_get_current_transition()` into an existing Lua test script of mine, I cannot reproduce this in OBS Studio 29.0.0 Beta 1. 

```
transition_duration: 200
```

**Comment by cowboy** [comment]
Ok, I'm going to close the issue then. Thanks!
