### ISSUE TITLE
'make install' as root with umask 077 break the system

### ISSUE THREAD

**Issue by pedrxd** [obsproject/obs-studio#5315]
### Operating System Info

Other

### Other OS

Debian 11

### OBS Studio Version

Git

### OBS Studio Log URL

-

### Expected Behavior

When 'make install' is executed obs-studio should be installed without change any folder permission that already exist on the system.

### Current Behavior

Actually, if you execute 'make install' with umask 077 the folder /usr/ change permission to 700 and most of the system break.

### Steps to Reproduce

1. Change system umask to 077
2. Follow the instructions for build on debian-based without browser source on the [docs](https://obsproject.com/wiki/install-instructions#debian-based-build-directions).

**Comment by kkartaltepe** [comment]
Can you provide some background as to why your environment was configured in such a way, it seems more than just obs would be broken by such a change.

**Comment by pedrxd** [comment]
It is for security reason. When you install obs-studio it can be normal for new folders and binaries to be created with umask 077, but it should not modify the permissions of folders that already exist. Like /usr/, /usr/bin or /usr/share. 
A program install must not modify the permissions of system files.

**Comment by kkartaltepe** [comment]
I mean more of what inspired you to take such an action.

Anyway obs doesnt set any directory permissions that I could find, everything is handled by cmake's install rules so there is probably nothing we can change. I have added a warning to the build rules.
