### ISSUE TITLE
OBS startup crash without crash log

### ISSUE THREAD

**Issue by atticus-lv** [obsproject/obs-studio#5316]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.0-rc3

### OBS Studio Log URL

https://obsproject.com/forum/threads/obs-studio-crash-at-startup-after-crash-while-running.148345/

### OBS Studio Crash Log URL

no crash log generate

### Expected Behavior

start as usual

### Current Behavior

log (no crash log here)
I try capture, it crash when recording too.

its log
`
System.InvalidOperationException: Error loading Ninject component ICache
No such component has been registered in the kernel's component container.

Suggestions:
  1) If you have created a custom subclass for KernelBase, ensure that you have properly
     implemented the AddComponents() method.
  2) Ensure that you have not removed the component from the container via a call to RemoveAll().
  3) Ensure you have not accidentally created more than one kernel.
`

### Steps to Reproduce

just run the obs studio. it loading for a while then crash sliently

**Comment by notr1ch** [comment]
Ninject seems to be some 3rd party software injecting into OBS. See https://obsproject.com/wiki/Known-Conflicts

**Comment by atticus-lv** [comment]
is there any way to delete it? I try reinstall obs but it did not work.
