### ISSUE TITLE
Virtual Camera not Working in Ubuntu 20.04

### ISSUE THREAD

**Issue by sagalpreet** [obsproject/obs-studio#5318]
### Operating System Info

Ubuntu 20.04

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/aRq8O7VSpwOoNXGQ

### Expected Behavior

The "Start Virtual Camera" button should change to "Stop Virtual Camera" and virtual camera should start.

### Current Behavior

There is no effect on pressing the "Start Virtual Camera" button.

### Steps to Reproduce

1. Install OBS 27.0.1 from Ubuntu Software.
2. Install v4l2loopback using command ```sudo apt-get install v4l2loopback-dkms```

### Anything else we should know?

The description on Ubuntu Software application has following command for v4l2loopback installation:
```
sudo snap connect obs-studio:kernel-module-observe sudo apt -y install v4l2loopback-dkms v4l2loopback-utils echo "options v4l2loopback devices=1 video_nr=13 card_label='OBS Virtual Camera' exclusive_caps=1" | sudo tee /etc/modprobe.d/v4l2loopback.conf echo "v4l2loopback" | sudo tee /etc/modules-load.d/v4l2loopback.conf sudo modprobe -r v4l2loopback sudo modprobe v4l2loopback devices=1 video_nr=13 card_label='OBS Virtual Camera' exclusive_caps=1
```
but this gives an error on my machine: 
```
tee: invalid option -- 'r'
Try 'tee --help' for more information.
error: unknown flag `y'
```
This [issue](https://askubuntu.com/questions/1332772/obs-studio-virtual-camera-wont-work) is quite similar to mine but the solution here didn't work for me.

**Comment by RytoEX** [comment]
The OBS Studio package in the Ubuntu Software store is not maintained by us, as explained on the Ubuntu Software page for it.
![image](https://user-images.githubusercontent.com/624931/134186091-c55c94b5-ac02-4f9f-8e77-7058132876d6.png)
> OBS Studio is software designed for capturing, compositing, encoding, recording, and streaming video content, efficiently. **This is a community-supported modified build of OBS Studio; please file issues on the Snapcrafters GitHub:** https://github.com/snapcrafters/obs-studio/issues

**Comment by ErickTucto** [comment]
I did the same steps to install obs on ubuntu 20.04. But my virtual camera does not start me

![imagen](https://user-images.githubusercontent.com/22831024/136704676-64f02e1e-c527-4ab8-af5f-1c9e405ef2c6.png)
