### ISSUE TITLE
Obs studio hangs frequently after launching from UI 

### ISSUE THREAD

**Issue by eccentrichead** [obsproject/obs-studio#5321]
### Operating System Info

Other

### Other OS

Linux Mint 20.2 x86_64

### OBS Studio Version

Other

### OBS Studio Version (Other)

OBS Studio - 25.0.3+dfsg1-2 (linux)

### OBS Studio Log URL

https://obsproject.com/logs/ghJgmKInQhOXYQ61

### Expected Behavior

The application should exit smoothly after closing the window or exiting from the app.

### Current Behavior

After installing the current stable version of OBS in a fully updated Linuxmint 20.2 environment, it is observed that the application exits uncleanly with orphaned processes left behind.  In the initial observation, it appears that this happens soon after a video is recorded. At this point, the video itself seems to be getting saved without any corruption. If the video is read from the VLC player at this point, the player misbehaves similarly where the process gets orphaned once the main window gets closed.  

Some details about the setup for reference:
Hardware: Lenovo ThinkPad T580
Kernel: 5.4.0-84-generic
CPU: Intel i7-8650U (8) @ 4.200GHz 
GPU: Intel UHD Graphics 620
Memory: 11922MiB / 31959MiB

Package details:
OBS Studio - 25.0.3+dfsg1-2 
VLC media player 3.0.9.2 Vetinari
 
Additional note:
* The log link provided in the form is not at the time of issue as I had tried opening obs app couple of times. Please refer to the below logs that have the errors. 
[2021-09-22 09-27-40.txt](https://github.com/obsproject/obs-studio/files/7208080/2021-09-22.09-27-40.txt)
* The gcore files for obs process that appears to be orphaned are as below:
https://drive.google.com/drive/folders/18YhYbrb44fy2uOxJ_ck5b527fwHFz68i?usp=sharing

### Steps to Reproduce

1. On a linuxmint 20.2 host install the stable obs release
2. launch the obs recorder from the UI 
3. Record a video from laptop screen (no live streaming)
4. Once the file is saved after the recording is done, try closing the application
5. Try to open the saved file with vlc (the video will play) but it will now misbehave like obs when trying to exit the app.
6. Trying to open obs recorder again will spawn one more instance which likely will get closed properly from the UI but there will be an orphaned process in the background for it.

**Comment by mihawk90** [comment]
This is [a one and a half year old version](https://github.com/obsproject/obs-studio/releases/tag/25.0.3), and not even the most recent 25.x version at that.

This sounds more like a packaging issue and not an OBS issue, and distro packages are not maintained by the OBS team.

On Mint you can use the PPA provided on the downloads page, which is the recommended install method anyway.

**Comment by kkartaltepe** [comment]
Probably fixed on master. Feel free to ask us to reopen if you find you can replicate it on the current release.

**Comment by eccentrichead** [comment]
Thanks for the help guys! It appears that for some reason even using the official PPA, the system was installed with an older version of obs. I re-ran the install command again and this time I noted I have the latest 27.0 stable release. I confirm the issue with the orphaned process no longer occurs with it

Thanks once again for a very quick reply.
