### ISSUE TITLE
[Bug] If a scene collection exported from Windows is imported into OBS on Linux, OBS crashes with a SIGSEGV in obs_module_get_locale_string if the Game Capture source is clicked at all.

### ISSUE THREAD

**Issue by FuzzyQuils** [obsproject/obs-studio#5323]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.0.1-3

### OBS Studio Log URL

https://obsproject.com/logs/52aCr5ZFXILrTbER

### Expected Behavior

I expected to be able to open the Game Capture source and have it show "No Properties available," giving me the ability to then remove it and replace it with the Linux equivalent.

### Current Behavior

Left-clicking, right-clicking, doesn't matter, any click on a Game Capture source imported from Windows force-closes the window with a Segmentation Fault logged if run from the terminal. No crash log appears. (or if there is one, I'm not sure where or how I'm supposed to upload it)

### Steps to Reproduce

1. Make a new Scene on the Windows version of OBS, add a Game Capture source.
2. Export the scene collection.
3. Import that same collection on a Linux machine.
4. Attempt to interact with the Game Capture source.

### Anything else we should know?

The version of OBS I am using is from the Arch Linux repos, so chances are this bug may have been found and patched already in Master.

**Comment by kkartaltepe** [comment]
Can you provide a backtrace (or rytoex who confirmed?)

**Comment by RytoEX** [comment]
> Can you provide a backtrace (or rytoex who confirmed?)

My apologies.  The issue is that a game_capture source from a Windows-based scene collection is not translated to any source type that exists on a Linux installation, so on a Linux system it tries to load a game_capture source.  It crashes when trying to run `obs_module_get_locale_string` called from `obs_module_get_locale_text`.  You can probably reproduce this by changing any source type to an unknown source type on Linux and then selecting the source in the source list.

I had thought that this could be avoided if we just translate the game_capture source to either xcomposite_input or pipewire-window-capture-source, but I wasn't sure how best to approach that, so I hadn't gotten further than some initial research.  That said, perhaps that would just mask a different issue.

Here's a gdb backtrace.
```
Thread 1 "obs" received signal SIGSEGV, Segmentation fault.
0x00007ffff54c3c3d in obs_module_get_locale_string (mod=0x0, lookup_string=0x5555557cc0d0 "Mode", 
    translated_string=0x7fffffffcf40)
    at /home/ryto/Documents/code/obsproject/obs-studio/libobs/obs-module.c:66
66		if (mod->get_string) {
(gdb) bt full
#0  0x00007ffff54c3c3d in obs_module_get_locale_string
    (mod=0x0, lookup_string=0x5555557cc0d0 "Mode", translated_string=0x7fffffffcf40)
    at /home/ryto/Documents/code/obsproject/obs-studio/libobs/obs-module.c:66
#1  0x00007ffff54c3c84 in obs_module_get_locale_text (mod=<optimized out>, text=<optimized out>)
    at /home/ryto/Documents/code/obsproject/obs-studio/libobs/obs-module.c:77
        str = 0x5555557cc0d0 "Mode"
#2  0x0000555555774fa0 in  ()
#3  0x0000555555639992 in  ()
#4  0x00007ffff4ac010c in QObject::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007ffff5677783 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007ffff4a927ba in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
    at /lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007ffff4a957e1 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
    at /lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007ffff4aecba7 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007ffff329d8eb in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007ffff32f0d28 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007ffff329b023 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007ffff4aec204 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)
    () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007ffff4a9111b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007ffff4a99604 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00005555555d8184 in main ()
```

**Comment by BinaryVigilante** [comment]
> > Can you provide a backtrace (or rytoex who confirmed?)
> 
> My apologies. The issue is that a game_capture source from a Windows-based scene collection is not translated to any source type that exists on a Linux installation, so on a Linux system it tries to load a game_capture source. It crashes when trying to run `obs_module_get_locale_string` called from `obs_module_get_locale_text`. You can probably reproduce this by changing any source type to an unknown source type on Linux and then selecting the source in the source list.
> 
> I had thought that this could be avoided if we just translate the game_capture source to either xcomposite_input or pipewire-window-capture-source, but I wasn't sure how best to approach that, so I hadn't gotten further than some initial research. That said, perhaps that would just mask a different issue.
> 
> Here's a gdb backtrace.
> 
> ```
> Thread 1 "obs" received signal SIGSEGV, Segmentation fault.
> 0x00007ffff54c3c3d in obs_module_get_locale_string (mod=0x0, lookup_string=0x5555557cc0d0 "Mode", 
>     translated_string=0x7fffffffcf40)
>     at /home/ryto/Documents/code/obsproject/obs-studio/libobs/obs-module.c:66
> 66		if (mod->get_string) {
> (gdb) bt full
> #0  0x00007ffff54c3c3d in obs_module_get_locale_string
>     (mod=0x0, lookup_string=0x5555557cc0d0 "Mode", translated_string=0x7fffffffcf40)
>     at /home/ryto/Documents/code/obsproject/obs-studio/libobs/obs-module.c:66
> #1  0x00007ffff54c3c84 in obs_module_get_locale_text (mod=<optimized out>, text=<optimized out>)
>     at /home/ryto/Documents/code/obsproject/obs-studio/libobs/obs-module.c:77
>         str = 0x5555557cc0d0 "Mode"
> #2  0x0000555555774fa0 in  ()
> #3  0x0000555555639992 in  ()
> #4  0x00007ffff4ac010c in QObject::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
> #5  0x00007ffff5677783 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
>     at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
> #6  0x00007ffff4a927ba in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
>     at /lib/x86_64-linux-gnu/libQt5Core.so.5
> #7  0x00007ffff4a957e1 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
>     at /lib/x86_64-linux-gnu/libQt5Core.so.5
> #8  0x00007ffff4aecba7 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
> #9  0x00007ffff329d8eb in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
> #10 0x00007ffff32f0d28 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
> #11 0x00007ffff329b023 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
> #12 0x00007ffff4aec204 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)
>     () at /lib/x86_64-linux-gnu/libQt5Core.so.5
> #13 0x00007ffff4a9111b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
>     at /lib/x86_64-linux-gnu/libQt5Core.so.5
> #14 0x00007ffff4a99604 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
> #15 0x00005555555d8184 in main ()
> ```

I had this same issue and it seems your theory of being able to search and replace "game_capture" with "xcomposite_input" did the trick. Thank you :)

**Comment by Silveere** [comment]
I seem to have a similar issue, except it doesn't even get past the import process without crashing. The `window_capture` id also seems to cause it. Here's my full backtrace: 
[obs-bt-full.txt](https://github.com/obsproject/obs-studio/files/13359353/obs-bt-full.txt)

(OBS Studio 30.0.0, Flatpak)
