### ISSUE TITLE
OBS Crashes every time I close

### ISSUE THREAD

**Issue by isaacrlevin** [obsproject/obs-studio#5324]
### Operating System Info

Other

### Other OS

Windows 11

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/1iB5df0Pjm3Uc73-

### OBS Studio Crash Log URL

https://obsproject.com/logs/73LSCreSaeYS8hZv

### Expected Behavior

OBS to graciously close

### Current Behavior

OBS Crashes every close

### Steps to Reproduce

1. Open OBS
2. Do stuff
3. Close OBS

**Comment by Fenrirthviti** [comment]
Crash is happening in the third party plugin: https://github.com/exeldro/obs-virtual-cam-filter

Please report this issue there.

**Comment by notr1ch** [comment]
Looks like a crash in the 3rd party virtualcam plugin.
