### ISSUE TITLE
Display Numbers are switched

### ISSUE THREAD

**Issue by SolitaryBlue** [obsproject/obs-studio#5329]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/08bjnfXS2lChVxQU

### Expected Behavior

My primary monitor should be listed as Display 1. 

### Current Behavior

My primary monitor is listed as Display 2, and my second monitor is listed as Display 1.
![OBS](https://user-images.githubusercontent.com/46092780/134776278-8f92960b-bf43-477f-a1f5-234a4b291217.PNG)

Display 1 should be 0,0 (Primary Monitor).

OBS is NOT changing my Windows 10 display settings; it's only showing the monitors in the wrong order in the dropdown. 

### Steps to Reproduce

1. I created a new profile and a new Scene Collection. 
2. Added my primary monitor as a Display Capture. 
...

### Anything else we should know?

I'm not experiencing this issue with version 26.1.1. The problem started when I upgraded to 27.0.1. I've rolled back to 26.1.1 and haven't had any issues with it.

**Comment by jpark37** [comment]
Previously, OBS would ask DXGI for the monitor info, but that only enumerates monitors attached to a specific adapter. OBS 27 added support for cross-adapter display capture, and monitor enumeration was switched to EnumDisplayMonitors to facilitate that change. OBS doesn't attempt to sort the output of that function.

**Comment by SuslikV** [comment]
The forum's origin: https://obsproject.com/forum/threads/display-numbers-are-switched-after-update-to-27-0-0.144509/page-2#post-543047

**Comment by dijikul** [comment]
Found this issue via Google and the previous forum post.  This issue persists and I have to swap display sources between Display 2 and 3 every time I open OBS.

**Comment by dijikul** [comment]
Here are OBS logs demonstrating the numbering varying between different launches of OBS in between reboots.  It's somewhat random when it occurs, not happening on every reboot.

```
12:31:05.288: 	display: 1 (1920x1080)
12:31:05.288: 	cursor: true
12:31:05.288: 	method: DXGI
12:31:05.288: signal_handler_connect: signal 'streamelements_update_settings' not found
12:31:05.304: [duplicator-monitor-capture: 'Monitor: Middle'] update settings:
12:31:05.304: 	display: 2 (3840x1600)
12:31:05.304: 	cursor: true
12:31:05.304: 	method: DXGI
12:31:05.306: [duplicator-monitor-capture: 'Monitor Right'] update settings:
12:31:05.306: 	display: 3 (1080x1920)
12:31:05.306: 	cursor: true
12:31:05.306: 	method: DXGI
------------------------
09:28:50.330: 	display: 2 (1080x1920)
09:28:50.330: 	cursor: false
09:28:50.330: 	method: DXGI
09:28:50.330: signal_handler_connect: signal 'streamelements_update_settings' not found
09:28:50.330: [duplicator-monitor-capture: 'Right  '] update settings:
09:28:50.330: 	display: 3 (3840x1600)
09:28:50.330: 	cursor: true
09:28:50.330: 	method: DXGI
09:28:50.330: signal_handler_connect: signal 'streamelements_update_settings' not found
09:28:50.331: [duplicator-monitor-capture: 'LCD Left'] update settings:
09:28:50.331: 	display: 1 (1920x1080)
09:28:50.331: 	cursor: true
09:28:50.331: 	method: DXGI
------------------------
10:01:02.118: 	display: 2 (1080x1920)
10:01:02.118: 	cursor: true
10:01:02.118: 	method: DXGI
10:01:02.122: [duplicator-monitor-capture: 'Monitor: Middle'] update settings:
10:01:02.122: 	display: 3 (3840x1600)
10:01:02.122: 	cursor: true
10:01:02.122: 	method: DXGI
10:01:02.122: signal_handler_connect: signal 'streamelements_update_settings' not found
10:01:02.123: [duplicator-monitor-capture: 'HUD: Monitor Left'] update settings:
10:01:02.123: 	display: 1 (1920x1080)
10:01:02.123: 	cursor: true
10:01:02.123: 	method: DXGI
-------------------------
13:11:01.542: 	display: 1 (1920x1080)
13:11:01.542: 	cursor: true
13:11:01.542: 	method: DXGI
13:11:01.542: signal_handler_connect: signal 'streamelements_update_settings' not found
13:11:01.548: [duplicator-monitor-capture: 'Monitor: Middle'] update settings:
13:11:01.548: 	display: 3 (1080x1920)
13:11:01.548: 	cursor: true
13:11:01.548: 	method: DXGI
13:11:01.551: [duplicator-monitor-capture: 'Monitor Right'] update settings:
13:11:01.551: 	display: 2 (3840x1600)
13:11:01.551: 	cursor: true
13:11:01.551: 	method: DXGI
-------------------------
10:36:46.391: 	display: 3 (3840x1600)
10:36:46.391: 	cursor: true
10:36:46.391: 	method: DXGI
10:36:46.394: [duplicator-monitor-capture: 'Monitor: Middle'] update settings:
10:36:46.394: 	display: 2 (1080x1920)
10:36:46.394: 	cursor: true
10:36:46.394: 	method: DXGI
10:36:46.394: signal_handler_connect: signal 'streamelements_update_settings' not found
10:36:46.394: [duplicator-monitor-capture: 'HUD: Monitor Left'] update settings:
10:36:46.394: 	display: 1 (1920x1080)
10:36:46.394: 	cursor: true
10:36:46.394: 	method: DXGI
```

**Comment by builder-main** [comment]
As explained in #7049 should probably be reopen with and this toggle added. I'll try a version prior to the PR  and let you know if it really fixes my usecase.

![image](https://github.com/obsproject/obs-studio/assets/32265170/1a40d25a-777a-4d3c-a157-4fa8f6a977b3)

**Comment by dalmackay** [comment]
This is still an issue in 2025. it has never not been an issue. I have never once been able to stream monitor 1 in over 4 years.

**Comment by Romany-hash** [comment]
still ongoing and annoying issue, if have many scenes that contains window capture source, you need to set it up every time you open OBS

**Comment by Fenrirthviti** [comment]
This specific issue was marked as resolved. If you are having issues in the current version of OBS, please open a new issue with the full details and steps to reproduce.
