### ISSUE TITLE
Browser source cannot play MPEG files

### ISSUE THREAD

**Issue by Deuchnord** [obsproject/obs-studio#5334]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/nM79NQnwRag2lFv2

### Expected Behavior

When I ask to display an MPEG file in a browser source, then it shows up.

### Current Behavior

The video cannot be read.

I got typically this error with the following file: https://user-images.githubusercontent.com/7600265/134803419-d0474539-ca97-4fe3-a030-e530d84f6277.mp4

Once converted in a WebM video, it seems to work perfectly.

### Steps to Reproduce

1. Get the [reproducer files](https://github.com/obsproject/obs-studio/files/7231194/test-videos.zip)
2. Add a browser source on OBS, set its source to the `test-video.mp4.html` file and its dimensions to 1920x1080px. Then press OK.
3. The video is not displayed.

If you replace the file loaded of the browser source with the WebM version, the video is displayed and can be played though the Interact feature of the browser source.

### Anything else we should know?

OBS is installed via FlatHub.

**Comment by mihawk90** [comment]
See here:

obsproject/obs-browser#316

**Comment by Deuchnord** [comment]
Thanks for pinging this issue, didn't find it during my search.
