### ISSUE TITLE
OBS crash when stop streaming with Bilibili SRT while not on air

### ISSUE THREAD

**Issue by wfjsw** [obsproject/obs-studio#5337]
### Operating System Info

Windows 10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/uTkfwO-74UXJka0k

### OBS Studio Crash Log URL

https://obsproject.com/logs/4oFaAqVNLoJVOZ7s

### Expected Behavior

The same behavior as in RTMP protocol, that is, no freeze when the URL is inaccessible.

### Current Behavior

When I push `Stop Streaming` **after** stopping the live on website, the app either freezes as a whole or unable to force stop streaming.

### Steps to Reproduce

1. With a stream URL that is not enabled, start streaming
2. Stop streaming
3. Freeze

**Comment by RytoEX** [comment]
Closing this as a duplicate in favor of #5791 as that has more info on it.
