### ISSUE TITLE
“Check for Updates” should appear in the “OBS” menu in the main menu—not “Help”

### ISSUE THREAD

**Issue by mdznr** [obsproject/obs-studio#5338]
### Operating System Info

macOS 11.3

### OBS Studio Version

27.0.1

### OBS Studio Log URL

N/A

### Expected Behavior

“Check for Updates” to appear in the “OBS” menu instead of the “Help” menu

### Current Behavior

“Check for Updates” appears in the “Help” menu

### Steps to Reproduce

N/A

### Anything else we should know?

For the vast majority of Mac apps using [Sparkle](https://sparkle-project.org), the “Check for Updates” menu item is in the main menu submenu with the title of the name of the app. In OBS, however, it is in the “Help” menu. This made it difficult to find.

**Comment by RytoEX** [comment]
I'd much prefer to see some sort of design document or guide of recommended/best practices rather than an anecdotal claim.  I'd like to avoid a scenario where we pursue moving this menu item only for someone else to claim that every app _they've_ ever used had it in the Help menu, or even somewhere else.  That said, I'll defer to @PatTheMav on this specific subject.

This feels more like a change request or feature request than an actual bug to me.  That being the case, it should probably be opened on https://ideas.obsproject.com/ instead.  I'll defer to @Fenrirthviti on if this should be submitted there instead.

**Comment by Fenrirthviti** [comment]
Should probably be on the ideas page.

**Comment by mdznr** [comment]
> I'd much prefer to see some sort of design document or guide of recommended/best practices rather than an anecdotal claim. I'd like to avoid a scenario where we pursue moving this menu item only for someone else to claim that every app _they've_ ever used had it in the Help menu, or even somewhere else. That said, I'll defer to @PatTheMav on this specific subject.

Agreed. There isn‘t any formal documentation for this in the Sparkle project as far as I can tell, but the sample app in that repository uses the application’s menu and not the Help menu. This is as close to documentation/guidance as there will be. https://github.com/sparkle-project/Sparkle/blob/2.x/TestApplication/Base.lproj/MainMenu.xib#L26

Just running through a few apps I have installed that use Sparkle, they all use the same pattern:
- [GitUp](https://gitup.co)
- [Kaleidoscope](https://kaleidoscope.app)
- [MacVim](https://macvim-dev.github.io/macvim/)
- [Adium](https://adium.im)

Checking for other open source projects on GitHub, as far as I went through the results page, all of them were in the first menu, not the Help menu. https://github.com/search?l=&q=%22%3Caction+selector%3D%22checkForUpdates%3A%22%22+language%3AXML&type=code

> This feels more like a change request or feature request than an actual bug to me. That being the case, it should probably be opened on https://ideas.obsproject.com/ instead. I'll defer to @Fenrirthviti on if this should be submitted there instead.

**Comment by PatTheMav** [comment]
FWIW I agree - I don't know of any proper Mac app that doesn't have the "update" menu item right below the preferences menu item. In a way it's the "law" as accepted by the macOS developer community and not doing so sticks out like a sore thumb.

I'd rather have a "macOS adjustments" discussion or issue tracking these things though, as there are many other issues that break macOS UI guidelines or best practices, some of which might be easy to tackle.

My hope would be that some community members might try to tackle them as PRs based on this curated list.

**Comment by PatTheMav** [comment]
As the idea is submitted, I'll close this for now. Functionality is not impacted and while I'd love to see more "native" UI traits, it's better suited for a future PR if someone wants to make it happen.
