### ISSUE TITLE
Dark theme displays incorrectly if non-default QT_QPA_PLATFORMTHEME is set

### ISSUE THREAD

**Issue by canalocaradoti** [obsproject/obs-studio#5339]
### Operating System Info

Other

### Other OS

ZorinOS 16 Core

### OBS Studio Version

27.1.0

### OBS Studio Log URL

https://obsproject.com/logs/qN-iazg8c0LxF20u

### Expected Behavior

**I was hoping that the dark theme would be kept in version 27.1.0, since the previous Linux version was running fine.**

### Current Behavior

**But what ended up happening is that the inside and the buttons when used in dark mode, they turn white or "grayed out", which did not happen before.**

### Steps to Reproduce

My step by step was very simple:

1. I already had the Obs Studio ppa added
2. Then I did the commands sudo apt update && sudo apt upgrade -y
3. Afterwards I restarted my notebook

### Anything else we should know?

I am using ZorinOS 16 Core, which is the same base as Ubuntu 20.04.3 LTS, even the QT5 libs are the same.

**Comment by Fenrirthviti** [comment]
Please provide screenshots as examples, the dark theme was changed in 27.1 to change how checked QPushButtons are styled, so this might be intentional.

**Comment by canalocaradoti** [comment]
No problem, here are the screenshots ✌️
![Captura de tela de 2021-09-28 17-59-42](https://user-images.githubusercontent.com/41804119/135165006-aa25297f-b846-4b46-83d2-068705ed8e86.png)
![Captura de tela de 2021-09-28 17-59-51](https://user-images.githubusercontent.com/41804119/135165009-6c18cead-08c5-41bc-bb7d-dc2f5208c636.png)

**Comment by canalocaradoti** [comment]
> Please provide screenshots as examples, the dark theme was changed in 27.1 to change how checked QPushButtons are styled, so this might be intentional.

No problem man !!
![Captura de tela de 2021-09-28 17-59-42](https://user-images.githubusercontent.com/41804119/135334628-9d8077ae-130c-4830-bdca-1d81f8fd79db.png)
![Captura de tela de 2021-09-28 17-59-51](https://user-images.githubusercontent.com/41804119/135334632-eef84193-278c-40b5-9700-f23a737aae99.png)
!

**Comment by Fenrirthviti** [comment]
Thanks, this doesn't seem to be related to the theme changes we made, but is something else entirely. Likely the version of Qt on your distro is different in some way, but I am not sure what it would be.

**Comment by canalocaradoti** [comment]
> Thanks, this doesn't seem to be related to the theme changes we made, but is something else entirely. Likely the version of Qt on your distro is different in some way, but I am not sure what it would be.

You are welcome, man. Well I am available to help with ZorinOS 16 and version 27.1.0 of OBS Studio, I just found it strange that the previous version was normal, but it happens  😅.

**Comment by andreymal** [comment]
Same on Arch Linux (with latest updates)

**Comment by andreymal** [comment]
I use qt5ct with gtk2 theme, so this may be the cause.

But note that it worked well in previous versions of OBS

**Comment by zjeffer** [comment]
I have the same problem on Arch Linux, also with `$QT_QPA_PLATFORMTHEME` set to `qt5ct`. In qt5ct, my theme is set to use the one defined in `kvantum`. In kvantum manager, my theme is set to a light theme.

@CobaltSpace's solution works for me. I can also fix it by making obs use a dark theme in Kvantum manager.

Either way, the problem is that choosing the `dark` theme in obs settings is still dependant on system settings. Choosing the 'dark' theme should be independant of whatever system settings you chose, in my opinion.

**Comment by tytan652** [comment]
With #6664 enforcing the Fusion Qt Style, setting `QT_QPA_PLATFORMTHEME` should have less impact on OBS theme.

**Comment by tytan652** [comment]
We now enforce `QT_STYLE_OVERRIDE` which prevent QPA Platform Theme to apply their style over our theme, so this should not happen without setting `QT_STYLE_OVERRIDE`.

**Comment by Fxzzi** [comment]
still seems to be happening for me. It seems to be using my QT Theme as set with qt6ct, and not the Fusion QT Theme. 
![image](https://github.com/obsproject/obs-studio/assets/18248986/f047732b-f4f7-420b-943b-f27573086aa6)

**Comment by nnra6864** [comment]
> If you have `$QT_QPA_PLATFORMTHEME` set (check with `echo $QT_QPA_PLATFORMTHEME`), try launching with it unset with this command `env -u QT_QPA_PLATFORMTHEME obs`.

This fixed it for me.
I am on arch, wayland, QT_QPA_PLATFORMTHEME = qt6ct.
I provided a picture of what it looks like with and without the command.
![image](https://github.com/obsproject/obs-studio/assets/104775644/d5576796-e47a-4366-9f11-5bad6dc7ae68)
