### ISSUE TITLE
Unable to resize some docks

### ISSUE THREAD

**Issue by chticer** [obsproject/obs-studio#5341]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.1

### OBS Studio Log URL

https://obsproject.com/logs/myqjrvgCAJrbOYax

### Expected Behavior

Be able to freely resize the width of docks.

### Current Behavior

Docks cannot be freely resized smaller.

### Steps to Reproduce

1. Open OBS.
2. Try to resize docks that are in the same row as the preview. (see attachment in "Anything else we should know?")
3. Docks can only be resized bigger (and inadvertently the program size can only be resized bigger as well).

### Anything else we should know?

![2021-09-28_20-57-48](https://user-images.githubusercontent.com/8918347/135191110-485ac724-4040-4cd7-a3a3-58c6572350f9.png)
This issue did not happen in OBS 27.0.1. As soon as I updated to OBS 27.1.1, the program size got bigger automatically. I normally have the scenes and sources dock lined up with the controls dock but I cannot make the scenes and sources dock bigger without resizing the entire program bigger (same is true for the stream information and chat dock). This is because I cannot make the preview size smaller (only for adjusting the width, it still works fine for adjusting the height).

**Comment by Warchamp7** [comment]
This is due to a fix to the source toolbar to enforce the space it needs to function. We're looking into ways to reduce the space that it needs.

For the time being, you can get back to smaller window sizes by disabling the Source Toolbar in the View menu
