### ISSUE TITLE
Can't resize to width smaller than 800px

### ISSUE THREAD

**Issue by rafalfaro18** [obsproject/obs-studio#5343]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.1

### OBS Studio Log URL

https://example.com

### Expected Behavior

Obs should be able to resize to a width of 636px like it did in the previous version.

### Current Behavior

Doesn't let me resize to smaller than 800px of width.

### Steps to Reproduce

1. Put  Scenes, Controls, Sources, Audio Mixer and Scene transitions in 2 columns under the scene preview.
2. Deselect any source that makes anything appear after Filters under the scene preview.
3. Resize the window hotizontally until you can't anymore.
...

### Anything else we should know?

This was working before I upgraded to 27.1.1. I use a monitor of 2560x1080 resolution.

**Comment by rafalfaro18** [comment]
![obs-5343](https://user-images.githubusercontent.com/16846380/135211840-8b8d2f31-5f88-49b8-a629-bccd84c29cd4.PNG)

**Comment by gxalpha** [comment]
This is caused by the source Toolbar, disabling it should let OBS get smaller again for now

**Comment by rafalfaro18** [comment]
> This is caused by the source Toolbar, disabling it should let OBS get smaller again for now

Yes this temporary fix allowed me to resize again. Thank you very much.
