### ISSUE TITLE
PipeWire Window Capture Missing On KDE with xdg-desktop-portal-kde

### ISSUE THREAD

**Issue by HurricanePootis** [obsproject/obs-studio#5348]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

27.1.1

### OBS Studio Log URL

https://obsproject.com/logs/kJey0c2Td02yyfsB

### Expected Behavior

I expected there to be an option to capture windows using PipeWire, however, there was no such option

### Current Behavior

Currently, only PipeWire screen capture exists

### Steps to Reproduce

1. Use KDE Wayland (Currently on 5.22)
2. Install OBS 27.1.1
3. Try to add a source
4. Notice PipeWire window capture is gone

### Anything else we should know?

The author of the commits relating to this behavior said to report it, [comment for reference](https://github.com/obsproject/obs-studio/commit/c18f1ea7ed117e67ed523e11ccf7a8df469cad86#commitcomment-53801192)

**Comment by Gol-D-Ace** [comment]
KDE plasma does have an incorrect dbus property and therefore OBS thinks window capture isn't available.

This should get fixed with Plasma 5.23

**Comment by HurricanePootis** [comment]
Cool

**Comment by HurricanePootis** [comment]
@Gol-D-Ace Sorry for bringing up a dead thread, but could you point towards were you got the information that this issue will be fixed in Plasma 5.23?

**Comment by Gol-D-Ace** [comment]
Conversation in our Discord

https://discord.com/channels/348973006581923840/636682839382949888/892581789216964630

https://discord.com/channels/348973006581923840/636682839382949888/892611521979486228

**Comment by Gol-D-Ace** [comment]
Specific commit https://invent.kde.org/plasma/xdg-desktop-portal-kde/-/commit/f337a34cadd17aff15b9e21594ed1f2877935a13

**Comment by HurricanePootis** [comment]
Thanks

**Comment by AaronD-GH** [comment]
Ubuntu Studio 22.04.1 LTS
KDE Plasma 5.24.6
OBS Studio 28.1.2

Still no Window Capture.

**Comment by HurricanePootis** [comment]
This problem was fixed in a newer version of KDE.

**Comment by HurricanePootis** [comment]
> > This problem was fixed in a newer version of KDE.
> 
> Great! Which version is that, and how easily can I get it?

I'm not sure, but I use Arch Linux, so I always have the latest
