### ISSUE TITLE
OBS crashed on "start streaming"/"start recording" with latest AMD Driver 21.9.2

### ISSUE THREAD

**Issue by marcobuettner** [obsproject/obs-studio#5350]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.1

### OBS Studio Log URL

https://obsproject.com/logs/SYmaevXyOGJzpA5y

### Expected Behavior

When pressing "start recording" or "start streaming" it should start the record/stream like on previous version.

### Current Behavior

Since update to AMD 21.9.2. OBS crashed with "21:51:44.459: [AMF] <Id: 3> Unable to set converter transfer characteristic, error AMF_NOT_FOUND (code 11)" error in the log. 

But in OBS it shows "H264/AVC Encoder (AMD Advanced Media Framework)"

### Steps to Reproduce

1. Install Radeon Software 21.9.2 from amd.com
2. Install OBS Studio 27.1.1
3. Setup "H264/AVC Encoder (AMD Advanced Media Framework)" on Output
4. Press "Start Streaming" or "Start Recording"
...

**Comment by Fenrirthviti** [comment]
Please replicate without the StreamFX plugin installed, as that makes changes to OBS' encoders and is not supported by us.

**Comment by marcobuettner** [comment]
Can be closed, I completly remove the Radeon Software 21.9.2 and install completly new, after that OBS works again proberly.

**Comment by RytoEX** [comment]
Closing per the above comment.
