### ISSUE TITLE
Unable to init coreaudio without a device

### ISSUE THREAD

**Issue by abeatte** [obsproject/obs-studio#5351]
### Operating System Info

macOS 11.5

### OBS Studio Version

27.1.0

### OBS Studio Log URL

.

### Expected Behavior

Unable to start virtual camera without a physical coreaudio device present on the machine. I am trying to run this as a camera emulator for a machine without a mic or camera. I want to use the feed generated from this app as a virtual camera. https://github.com/obsproject/obs-studio/blob/dde4d57d726ed6d9e244ffbac093d8ef54e29f44/plugins/mac-capture/mac-audio.c#L651 `blog(LOG_INFO, "coreaudio: no device found");` states that if there is no coreaudio device then it will print this and continue scanning. This appears to block the ability of the init script from going any further. Is there a way we can get past this without having a coreaudio present? 

### Current Behavior

The virtual camera never gets started. 

### Steps to Reproduce

1. get on a machine with no camera and no microphone
2. try to run the app from the terminal with the following params
          '--startvirtualcam',
          '-p',
          '-m',
          '--disable-updater',
          '--disable-missing-files-check',
          '--minimize-to-tray',
3. notice how the "Starting Camera" line never gets hit and the app doesn't seem to get past this and start.

**Comment by gxalpha** [comment]
Could you please give us a log instead of just putting a `.` in the field?

**Comment by RytoEX** [comment]
No log was ever provided. Closing.
