### ISSUE TITLE
Hotkeys stop working after certain UI interactions

### ISSUE THREAD

**Issue by notr1ch** [obsproject/obs-studio#5352]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.1

### OBS Studio Log URL

N/A

### Expected Behavior

Hotkeys always work.

### Current Behavior

Hotkeys stop working after certain UI interactions.

### Steps to Reproduce

1. Create a hotkey, eg toggle source visibility so you can easily spam it for testing.
2. Press hotkey when OBS is focused and unfocused. Observe hotkey works.
3. Press Profile / New. Cancel the dialog.
4. Press hotkey when OBS is focused and unfocused. Observe hotkey no longer works.

### Anything else we should know?

Likely introduced by https://github.com/obsproject/obs-studio/commit/f832d14220b572165bf69ad73f30a5b961d02258

**Comment by RytoEX** [comment]
Commit f832d14220b572165bf69ad73f30a5b961d02258 was reverted in da04907927bab03c158176717dfef6f3fed5cbdd, so this was fixed in 27.1.2.
