### ISSUE TITLE
dont worked re-hook game-captrure

### ISSUE THREAD

**Issue by badmonster** [obsproject/obs-studio#5353]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.1

### OBS Studio Log URL

https://obsproject.com/logs/NTwqpsf0uoig77xp

### Expected Behavior

dont worked re-hook game-captrure. Me capture csgo.exe on faceit anti-cheat not rehooking / not show on screen

### Current Behavior

Dont capture more after 
The patch notes for 27.1.1 also mention:
"Improved internal behaviour in the game capture source to avoid unnecessary re-hooking [rcdrone]
part log
`"[game-capture: 'CS'] hook not loaded yet, retrying..
[game-capture: 'CS'] attempting to hook process: csgo.exe
[game-capture: 'CS'] using helper (compatibility hook)`

### Steps to Reproduce

1. I'm capture my cs;go as window. worked
2. me close game
3.start faceit anticheat
4. I'm capture as game-capture

**Comment by Fenrirthviti** [comment]
Please use the forums or Discord for support.

https://obsproject.com/help

**Comment by badmonster** [comment]
> 
> 
> Please use the forums or Discord for support.
> 
> https://obsproject.com/help

https://obsproject.com/forum/threads/after-27-1-1-i-cant-game-capture-celeste.148716/#post-543830

**Comment by badmonster** [comment]
WizardCM from OBS forum:
We believe this is caused by an updated certificate/signature on the game capture DLL, and it's up to FaceIt to whitelist us.
