### ISSUE TITLE
OBS Maximized Window Bug

### ISSUE THREAD

**Issue by nico-apps** [obsproject/obs-studio#5355]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.1

### OBS Studio Log URL

https://obsproject.com/logs/gxXQMEeomTC7fZ-K

### Expected Behavior

OBS starts up at maximized size.

### Current Behavior

OBS starts up at a normal window size, and the resize button in the top right has to be pushed twice to fix this.

### Steps to Reproduce

1. Open OBS and make it maximized.
2. Close OBS.
3. Reopen OBS, it should now appear as a normal window.

### Anything else we should know?

This is only happening on Version 27.1.1, not with 27.0.1. I didn't test Version 27.1.0 though.

Here's a screenshot on how it looks on my end:
![grafik](https://user-images.githubusercontent.com/35093969/135474941-cd26c87a-51f3-4c00-96ad-08eed6a899b5.png)

**Comment by mihawk90** [comment]
Are we talking about Maximised or Fullscreen here? Because those are 2 different things.

You say Fullscreen, but the description you're giving seems to relate to Maximising instead.

**Comment by nico-apps** [comment]
@mihawk90 Well, I don't quite know the differences, but it would be maximizing, yeah. Let me edit my post real quick

**Comment by flaeri** [comment]
hmm, assuming im understanding this correctly. It seems to work fine on my machine.
I open OBS, make sure its maximized, I close it (with the x, top right), and open it again, and its still maximized.
It remembers my position and size regardless of if I have it set to maximize or not.

**Comment by nico-apps** [comment]
Aaand it's working again... I have no idea what happened, all I did was to close OBS in windowed mode, move it around, then close it in maximised mode. Now it's working as intended.

I'll close this issue then, but if this happens again, I'll post it here.

**Comment by jdeng89** [comment]
Did some additional testing. It seems that this occurs when you upgrade OBS while it's in full screen mode, and will persist so long as you continue to close it in full screen mode.

To Fix, I performed the following:

1. Close OBS in windowed mode
2. Re-Open OBS, and Full Screen
3. Close OBS
