### ISSUE TITLE
Twitch Bandwidth Test Enabled/Disabled

### ISSUE THREAD

**Issue by MattyFresh68** [obsproject/obs-studio#5361]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.1

### OBS Studio Log URL

N/A

### Expected Behavior

Connect twitch account. Enable bandwidth test in settings > stream. Apply. Close settings. If you go back into settings > stream, the box "should" still be checked. 

### Current Behavior

Currently following steps above, after applying enabling the test, going back in shows an unchecked box. This gives a user a sense that the bandwidth test is not enabled. If they attempt to re-enable, and then go to press "start stream", without a guaranteed visibility that it is enabled, they could potentially risk actually going live. 

### Steps to Reproduce

1.connect twitch acct in settings > stream.
2.enable bandwidth test, press apply. Close settings 
3.reopen settings > stream. Bandwidth test box will be unchecked
...

**Comment by Gol-D-Ace** [comment]
Can confirm this behavior on Windows.
