### ISSUE TITLE
Setting full range video results in files that claim limited range video

### ISSUE THREAD

**Issue by mzso** [obsproject/obs-studio#5363]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

26.1.1

### OBS Studio Log URL

https://obsproject.com/logs/9Ieoxas0WCh9m4lL

### Expected Behavior

Recorded video being full range, and also the playback software being signalled as such.

### Current Behavior

The video is in fact full range, but the decoder receives the information that it's limited range.
I have LAV decoder and madVR. The latter shows "limited range (says upstream)".
This in past experience meant that some data is set wrongfully which misleads the decoder.

I can verify that the video is actually proper full range, by setting madVR to override to PC range, in which case the video displays properly.

### Steps to Reproduce

1. Set lossless quality in output, simple mode.
2. Set I444, 709 color space and Full range in advanced > video.
3. record a large size video.
3. observe the the recorded video, being borked, they way I described.
...

### Anything else we should know?

Also weird, and potentially a bug, is that if I record a smaller video size (don't know exact dimensions) the recorded video will be RGB as indicated by madVR's OSD, not sure if it's right. In which case madVR also shows "full range (best guess)", so I guess range data is not set. But the video definitely appears normally.

I don't know if the problem is container related, because I see no option to change container in simple mode. And archaic .avi is used.
I made a very short sample: https://drive.google.com/file/d/1RjlVCOMPsIi6ycOSWLp-P8F0pLT5Bm1h/view?usp=sharing

**Comment by SuslikV** [comment]
The forum's origin:
https://obsproject.com/forum/threads/i-want-to-record-actully-lossless-video-full-range-rgb-no-subsampling-how-do-i-do-it.148637/

**Comment by lextra2** [comment]
NV12 with bt709 & Full range works just fine for Nvidia,
[as you can see](https://i.imgur.com/fB4Iqfh.jpeg)

Now the question is, how to tag the stream correctly to make this work for other encoders?

**Comment by flaeri** [comment]
@lextra2 This issue is in relation to the AVI container and UTVideo. Unrelated to nvidia/amd, what have you.

**Comment by lextra2** [comment]
So turns out, the actual issue is that twitch does not accept Full for AMD, while it works for Nvidia.

I never actually tested local recordings (until now) which does work just fine.

**Comment by ValZapod** [comment]
>also shows "full range (best guess)", so I guess range data is not set

It does not matter, ffmpeg does not support limited rgb, so pretty much nothing does. Therevwas a bug that sometimes output was tagged limited rgb, but that is fixed.

**Comment by flaeri** [comment]
Just going to comment here so I don't forget. It seems to be that utvideo does not work in many containers, but there are two candidates; MOV and Matroska (both should support full range tagging).

There are references to mov in the source code: https://github.com/umezawatakeshi/utvideo/blob/b963a2b76cc21f6c1951dada1913373d8ce90fb9/utv_qt/QTDecoder.cpp#L167

We could either bring back the container/format selector to simple -> lossless mode, or one could force one of those containers. Each has their merits.

**Comment by mzso** [comment]
[**@flaeri**](https://github.com/flaeri) commented on [Nov 30, 2022, 10:54 PM GMT+1](https://github.com/obsproject/obs-studio/issues/5363#issuecomment-1332780843 "2022-11-30T21:54:41Z - Replied by Github Reply Comments"):
> Just going to comment here so I don't forget. It seems to be that utvideo does not work in many containers, but there are two candidates; MOV and Matroska (both should support full range tagging).
> 
> There are references to mov in the source code: [https://github.com/umezawatakeshi/utvideo/blob/b963a2b76cc21f6c1951dada1913373d8ce90fb9/utv\_qt/QTDecoder.cpp#L167](https://github.com/umezawatakeshi/utvideo/blob/b963a2b76cc21f6c1951dada1913373d8ce90fb9/utv_qt/QTDecoder.cpp#L167)
> 
> We could either bring back the container/format selector to simple -> lossless mode, or one could force one of those containers. Each has their merits.

That would help. Matroska is the most versatile common format anyway.
