### ISSUE TITLE
27.1.1 causes game capture to be washed out/frozen

### ISSUE THREAD

**Issue by andytham** [obsproject/obs-studio#5372]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.1

### OBS Studio Log URL

https://obsproject.com/logs/q5M4f1TwCEdPiqHw

### Expected Behavior

Smooth normal capture

### Current Behavior

Washed out image, and is pretty much frozen until it changes to a more recent frame every several minutes.
![image](https://user-images.githubusercontent.com/33642114/135764645-75867848-23b1-4315-9620-199682ee59b4.png)

### Steps to Reproduce

1. Launch Valorant (game) in fullscreen
2. Game capture (fullscreen app or target window)
3. OBS preview and recording is frozen/washed out capture

### Anything else we should know?

Running OBS in admin doesn't help.
Reverting back to 27.0, doesn't have this issue.
Haven't tested in other games other than Valorant.

**Comment by MattyFresh68** [comment]
The log you posted says version 27.0.0 You should try updating, and if it still occurs, post a new log?

**Comment by RytoEX** [comment]
Valorant captures fine here on OBS Studio 27.1.1.  A test recording with fullscreen Valorant looks fine in VLC.

I'm closing this for now.  This seems like a configuration or installation issue that can be diagnosed in the support channels.  If there is a bug that we can verify, then we can reopen this.

Please use the forums or Discord for support, thanks!

https://obsproject.com/help

**Comment by andytham** [comment]
> 
> 
> The log you posted says version 27.0.0 You should try updating, and if it still occurs, post a new log? Also looks like you are using an hdr monitor. Sure hdr is off in game and in windows?

I think that's reading the version of OBS during when I uploaded using the >Upload last log file, but the version says 27.1.1 further down by the hardware settings in the log.

And thank you I will probably update and try again later.
