### ISSUE TITLE
Fullscreen Menu-Item missing

### ISSUE THREAD

**Issue by LeaHummer** [obsproject/obs-studio#5373]
### Operating System Info

macOS 10.13

### OBS Studio Version

27.1.0

### OBS Studio Log URL

https://obsproject.com/logs/uaZm5fdxyE0-lNbo

### Expected Behavior

Selecting »Fullscreen«

### Current Behavior

Menu-Item »Fullscreen« not there.

### Steps to Reproduce

1. Update from 27.0.1 to 27.1.0
2. Start OBS
3. Open menu »View« 
... be surprised about menu-item »Fullscreen« not existing anymore.

**Comment by mihawk90** [comment]
It's been removed because Mac has a native Fullscreen button.

**Comment by RytoEX** [comment]
As @mihawk90 mentioned, the item was moved to better comply with macOS app design norms.  See also #5145.

Closing this as this change is intentional.
