### ISSUE TITLE
Audio issues after update 27.1.1

### ISSUE THREAD

**Issue by DJodyHendrix** [obsproject/obs-studio#5374]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.1

### OBS Studio Log URL

https://obsproject.com/logs/q2cdi2bPzbXx_-rl

### Expected Behavior

audio to run smooth from game PC with NDI

### Current Behavior

Audio is very glitchy from game PC to Stream PC

### Steps to Reproduce

1.have a game PC use NDI
2. Capture that NDI gameplay and audio on stream PC
3.audio doesnt work properly
...

**Comment by WizardCM** [comment]
If you are having issues with the obs-ndi plugin specifically, you'll want to reach out to the developers of the plugin.

Additionally, we do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

**Comment by DJodyHendrix** [comment]
Thats not the problem, we just reverted back to previous update and it
works fine now
