### ISSUE TITLE
Virtual Camera portrait resolutions do not work in windows

### ISSUE THREAD

**Issue by abanchev** [obsproject/obs-studio#5378]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.1

### OBS Studio Log URL

none

### Expected Behavior

When we set a 9/16 resolution of the canvas the virtual camera resolution should match. In OSX this works (in zoom, google meet etc.). On Windows the image is stretched.

### Current Behavior

The video is stretched to landscape resolution.

### Steps to Reproduce

1. Change canvas and output size to 720x1280 (9:16 aspect ratio)
2. Start Virtual camera
3. Try to stream in portrait mode in any application

### Anything else we should know?

Mainly tested in browser meetings, Chrome, Firefox and Edge all have the same issue.

**Comment by flaeri** [comment]
I believe the output is actually correct, and when I test it, I get confirmation.
```
Input #0, dshow, from 'video=OBS Virtual Camera': sq=    0B f=0/0
  Duration: N/A, start: 510767.712000, bitrate: N/A
  Stream #0:0: Video: rawvideo (NV12 / 0x3231564E), nv12, 720x1280, 30 fps
```
I think the issue lies with the apps on windows, and they may have a tendency to not respect the resolution/aspect ratio, because it may be quite unexpected coming from a windows desktop.

**Comment by Fenrirthviti** [comment]
I can confirm this does indeed stretch. I'm also pretty sure this is an intentional action to preserve 16:9 aspect ratio and avoid unnecessary scaling/distortion for the majority of applications, but I could be mistaken.

**Comment by Furdox** [comment]
I really want this to be fixed...

**Comment by gxalpha** [comment]
The virtual camera itself does work with 9/16 resolutions. You can check yourself by pulling it into OBS, and it looks like Google Chrome works as well (that may have changed since the original report).
Other software (like Discord) re-stretch it into 16/9.
