### ISSUE TITLE
VSeeface and other Vtubing software will freeze instantly upon being game captured or just not get captured at all

### ISSUE THREAD

**Issue by PapaOrion** [obsproject/obs-studio#5379]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.1

### OBS Studio Log URL

https://obsproject.com/logs/UCV13aOf1hnZf7yP

### Expected Behavior

I expected it to capture the model from vseeface and actually run it not freeze immediately, vseeface i have seen isn't the problem and not everyone is having this issue, just seems to be me and a select few 

### Current Behavior

I tried to game capture the software into obs and it would just freeze up like it crashed or sometimes not display at all (and just give me no game capture of the software), vseeface will be working absolutely fine in the background

### Steps to Reproduce

1.open the software (Vseeface) set it up like usual
2.i open OBS and try to game capture, i enable transparency as to have no white background
3.once i press ok it's really a raffle on whether it'll freeze immediately or just won't capture at all and give me nothing
...

### Anything else we should know?

I have tried several older versions of OBS and it just seems that they no longer work anymore, i've even reinstalled windows and it changed nothing

**Comment by notr1ch** [comment]
Please use the forums or Discord for support requests.
