### ISSUE TITLE
jitsi meet window not loading in meeting

### ISSUE THREAD

**Issue by kvzonbr** [obsproject/obs-studio#5381]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.1

### OBS Studio Log URL

https://github.com/kvzonbr/reports/blob/main/2021-10-05%2012-08-07.txt

### Expected Behavior

after loading a navigator window with a meet.jit.si/custommmeeting *any meeting, don't load the meeting, (on osx load it ok and we can view the participants cameras), up until a month it loaded/joined the meeting without problem, now it loads the meeting and shows as joined but, didn't load any participant and didn't show on the actual meeting.

### Current Behavior

navigator, join meeting and shows it on the current shared scene. currently working properly on OSX.

### Steps to Reproduce

1. add navigator window
2.on url add the meeting URL, meet.jit.si/custom_meeting
3. resize and use
4. clic interact->settings->more-> unselect "enable pre meeting screen" 
5. (optional) add custom css to create transparency and hide the participant obs
body { background-color: rgba(0, 0, 0, 0) !important; margin: 0px auto; overflow: hidden; }

#localVideoContainer {
height: 0px;
width: 0px;
visibility: hidden;
opacity: 0;
}

#localVideoTileViewContainer {
height: 0px;
min-height:0px;
min-width: 0px;
width: 0px;
visibility: hidden;
opacity:0;
}

#notifications-container{
visibility: hidden;
}

.leftwatermark {
     opacity:0;
	visibility: hidden;
height: 0px;
}
.watermark {
	opacity:0;
	visibility: hidden;
height: 0px;
}

#filmstripLocalVideo {
opacity: 0;
visibility: hidden;
}

#largeVideoContainer{
	background-color: rgba(0, 0, 0,0.0) !important;
}
.cLnhlo{
	background-color: rgba(0, 0, 0,0.0) !important;
}
...

**Comment by Fenrirthviti** [comment]
I'm very confused by this report. Are you trying to join a webconference from inside a browser source? I don't think that is going to be possible at all in CEF, there's no support for the functions those meetings require as CEF is not designed to be used as a normal web browser. I'd recommend opening the meeting in a normal browser and just window capturing it instead. If I've misunderstood this report, please let me know and we can consider reopening.

**Comment by kvzonbr** [comment]
yes we're joining it to use as an team show, it actually works on OBS over OSX, and the windows version stoped working about a month or less ago, but is a feature we've been using for some time, that's why i added the custom css as it's been working with transparency for some time

here is a capture of it working on OSX
https://github.com/kvzonbr/reports/blob/main/Captura%20de%20Pantalla%202021-10-05%20a%20la(s)%2015.12.39.png


regards

**Comment by gxalpha** [comment]
@kvzonbr Fyi, [according to Jitsi](https://jitsi.github.io/handbook/docs/user-guide/supported-browsers) they support the current Chrome version and 10 versions older. On Windows, for reasons I won't get into here (you can read them in #3853), OBS on Windows is on an older version of CEF (and Chromium) then this and might be unsupported by Jitsi.
