### ISSUE TITLE
Sending jpeg to vlc source followed by changing to a scene can cause audio studdering

### ISSUE THREAD

**Issue by mindenguy** [obsproject/obs-studio#5389]
### Operating System Info

Other

### Other OS

windows 7

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/p6c5f8ldcHxCOHWO

### Expected Behavior

1. NO problem with 27.0.1
2. Background; Talking to obs over a web socket at speed
3. Sent a source request to a vlc source which was a jpeg (wrong thing to do, should have been image)
4. Then switch back to a scene that was in the pause/unpause mode part way thru the video
5. SHOULD have unpaused correctly and video / audio ok
6.  

### Current Behavior

if I send a jpeg to a vlc source in a lets say scene 1 ( scene 1 playing)
then quickly switch to scene 2 which was in the pause mode.
when it unpauses, the audio  and video studder for about 3 seconds.

I'm assuming that obs is dealing with the jpeg problem.
The log shows 
15:22:25.432: warning: deprecated pixel format used, make sure you did set range correctly which is obs saying it didn't like the jpeg request

### Steps to Reproduce

1. have scene 2 (vlc) play a video with the setting set to pause/unpause.
2. Play for a while
3. Keep vis set on
3. goto scene 1 (which has a vlc source)
4. vis is on
5. send request over websocket to load a jpeg
6. you get a warning message on the obs log saying 15:22:25.858: warning: deprecated pixel format used, make sure you did set range correctly
7. Switch back to scene 2 (quickly)
7. Scene 2 should unpause, but video - audio shutter for about 3 seconds.
8. You can't do this manually, has to be over a websocket and computer speeds.
2.
3.
...

### Anything else we should know?

In the current log, I stopped sending jpegs, so doesn't reflect the problem, but you do see where I sent the wrong things because of the warning messages

A old log segment that had the problem looks like this

19:22:54.189: warning: deprecated pixel format used, make sure you did set range correctly
19:23:01.852: User switched to scene 'VIEW_VIDEO_2'
19:23:01.867: warning: deprecated pixel format used, make sure you did set range correctly
19:23:11.833: User switched to scene 'VIEW_SD_SHOWS_1'
19:23:11.873: warning: deprecated pixel format used, make sure you did set range correctly
19:23:21.845: warning: deprecated pixel format used, make sure you did set range correctly
19:23:21.885: User switched to scene 'VIEW_VIDEO_2'

I know , most users are not going to work this way, but for some reason, it doesn't bother 27.0.1 which I went back to to trouble shout the problem.

I think for some reason, now, the jpeg to a vlc source request gets stuck somehow and gets busy doing things which is sort of stealing cpu cycles. Just a guess.

I'm only mentioning all this, because it worked ok on earlier revs (27.0.1), but not on current. Don't know about 27.1.1 and 2. Never tried them. Something changed!

Does any of this make sense???

Thanks for you good work

**Comment by nico-apps** [comment]
Windows 7 isn't supported anymore, so it could be the cause. Would you mind testing this on a newer version?
