### ISSUE TITLE
OBS and Snap Camera integration issue

### ISSUE THREAD

**Issue by mishmanners** [obsproject/obs-studio#5413]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/QJSE3s_vMQMtOgqY

### Expected Behavior

Seamless video experience.

### Current Behavior

I've been using Snap Camera with OBS and after the latest update, it is constantly flicking on and off.

### Steps to Reproduce

1. Start Snap Camera
2. Open Streamelements OBS
3. Start virtual camera

**Comment by Fenrirthviti** [comment]
Does this occur without Streamelement's plugin installed? We don't directly support their plugin as it replaces for components of OBS.

**Comment by WizardCM** [comment]
I cannot see any flickering with OBS 27.1.3 and Snap Camera 1.15.0 running on Windows 10 21H1. I'd recommend asking on our Discord server for direct help.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

**Comment by mishmanners** [comment]
Okay sure thing. When I mean flickering, I mean OBS loses the Snap Chat input and just shows the Logo instead. I'll ask on the Discord server for help.

**Comment by mishmanners** [comment]
And yes still occurs. Just loses the input.
