### ISSUE TITLE
Shared Library Location

### ISSUE THREAD

**Issue by swinginman** [obsproject/obs-studio#5425]
### Operating System Info

Other

### Other OS

OpenSUSE Tumbleweed

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/odu2YbujrAVMYpYs

### Expected Behavior

Shared library plugins should be loaded when placed in /usr//lib64/obs-plugins/

### Current Behavior

For some reason, OBS is adding the prefix "/usr/" to the directory it looks for shared libraries. I have been unable to find where this is being configured, I'm not even sure it is. As you can see from my log, simply having the share library in /usr/lib64/obs-plugins/ causes this error. I think it is tying to use the symlink directory of /lib64 but appending /usr/ to the front which results in a non-existent directory. If I could just remove the second / the directory would be valid, however /usr//lib64/obs-plugins/ does not exist because of the double /

### Steps to Reproduce

1. Add this plugin to your shared library folder: https://github.com/CryZe/obs-livesplit-one
2. Launch OBS
3. Read logs

**Comment by Fenrirthviti** [comment]
Please use the Forums or Discord for support requests, the official packages seem to work fine on Ubuntu, so this is either a package or environment issue, and not a bug with OBS.

https://obsproject.com/help

**Comment by swinginman** [comment]
> That aside, is there a reason you're installing in the shared lib directory instead of `~/.config/obs-studio/plugins` as the readme of the plugin suggests?

https://obsproject.com/logs/Ly1riwGPHEHBu2YS

Same behavior when they are put in that directory too.

**Comment by mihawk90** [comment]
> https://bugzilla.rpmfusion.org/show_bug.cgi?id=5999

For future reference: This is just the bug report for Fedora and RHEL-based distros.
SUSE would need a separate bug-report with their distro maintainers for them to fix it.

The mentioned command works, but it doesn't fix the underlying problem (and also doesn't link *all* the missing .so-files).

The issue is that the package is not containing the symlinks for the non-versioned .so files.
