### ISSUE TITLE
Limited Decklink Output Formats after Update

### ISSUE THREAD

**Issue by Sorqan** [obsproject/obs-studio#5427]
### Operating System Info

Other

### Other OS

Windows Server 2008 R2

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.1.3

### OBS Studio Log URL

NA

### Expected Behavior

In version 27.0.1 there were many resolutions and framerates available for the Decklink output, same as always with all recent OBS versions when using a Decklink Studio 4K and Decklink software v12.1.

![v2 7 0 1](https://user-images.githubusercontent.com/51136654/137817465-4be34504-e976-4d1a-a7eb-267ed6dfa43e.JPG)

### Current Behavior

There are now only 4 options for output and preview output decklink formats, and none of them are 720p oddly enough.

![v27 1 3](https://user-images.githubusercontent.com/51136654/137817503-52b456d1-ef0c-4b74-a9b6-8baf3b05b415.JPG)
 

### Steps to Reproduce

1. Install Decklink Studio 4K and version 12.1 firmware.
2. Update OBS to version 27.1.3.
3. Go to the Decklink Output configuration and select an output format.

### Anything else we should know?

Not sure if this behavior is the same with version 27.1 as well.

**Comment by tt2468** [comment]
OBS 27.0.0 now validates the output resolution against the supported resolutions of your decklink card, and only shows ones which are compatible.

Since OBS cannot do framerate conversions, using an unsupported output framerate would cause large amounts of lag on the output feed.

**Comment by tt2468** [comment]
Closing as this appears to be resolved.
