### ISSUE TITLE
27.1.3版本突然喊一声，麦克风音频的输入信号会变成红色！旧版本21.1.2就没有这个问题。

### ISSUE THREAD

**Issue by Aric-L** [obsproject/obs-studio#5429]
### Operating System Info

Other

### Other OS

Win7

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.1.3

### OBS Studio Log URL

None

### Expected Behavior

麦克风音频输入信号变成红色截图！
[
![QQ截图20211019115542](https://user-images.githubusercontent.com/91420458/137842060-e32b526d-07bf-49de-8c07-717aac4097d5.png)
](url)

### Current Behavior

可能会失真。

### Steps to Reproduce

1.可能会失真。
2.可能会失真。
3.可能会失真。
...

### Anything else we should know?

第一次启动时，软件出现假死现象。请把OBS软件第一次打开，推流设置的功能去掉。

**Comment by Aric-L** [comment]
请把软件第一次启动时,推流自动检测网速设置的功能去掉！

**Comment by WizardCM** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
