### ISSUE TITLE
No mouse cursor in Wayland window capture on KDE

### ISSUE THREAD

**Issue by thecookie94** [obsproject/obs-studio#5446]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/Fldnw8K5q3Jb7DnG

### Expected Behavior

When I set up a window capture with the mouse cursor enabled it captures the mouse cursor as well

### Current Behavior

When I set up a window capture with the mouse cursor enabled the mouse cursor doesn't get captured.
Mouse cursor capture in a screen capture session works just fine

### Steps to Reproduce

1. start obs (doesn't matter if it's the flatpak version or tytan's from the AUR) in a plasma wayland session
2. add a window capture with the mouse cursor capture checkbox checked
3. no mouse cursor on the canvas nor in the stream/recording output
...

### Anything else we should know?

Archlinux Wayland Plasma 5.23.1, xdg desktop portal installed&updated, as is xdg desktop portal kde&pipewire

@GeorgesStavracas asked me to tag them

**Comment by glaubersm** [comment]
Can confirm with OBS 27.1.3 from flathub on neon unstable distribution.

**Comment by mashuptwice** [comment]
Same behavior here on Arch with Plasma 5.23.5 and OBS 27.1.3

**Comment by kkartaltepe** [comment]
This does not look like our bug, the same code is used for monitor and window capture and it works for monitor capture. Adding some debug information on fedora 35 and it seems that kde simply never passes valid cursor information to window captures.

I recommend you file a bug upstream to kde.

**Comment by mashuptwice** [comment]
Created KDE bug report: https://bugs.kde.org/show_bug.cgi?id=452960

**Comment by mashuptwice** [comment]
@kkartaltepe Could you point me to some resources that contain an example of valid cursor data?

**Comment by X-m7** [comment]
KDE appears to have fixed the bug on their end for Plasma 5.26 with this [MR](https://invent.kde.org/plasma/kwin/-/merge_requests/2803).

**Comment by GeorgesStavracas** [comment]
Correct, let's close this

**Comment by DefomCode** [comment]
this is doesn't resolf
