### ISSUE TITLE
Audio mixer slider behaves in reverse in RTL mode

### ISSUE THREAD

**Issue by mskf1383** [obsproject/obs-studio#5447]
### Operating System Info

Ubuntu 21.04

### OBS Studio Version

27.1.3

### Current Behavior

In RTL devices the AudioMixer range is shown revert:
![نماگرفت از 2021-10-23 12-08-35](https://user-images.githubusercontent.com/50908329/138549536-5bb86328-45a5-46d3-8a1e-4fe8a05e8d47.png)
In that picture the top item (Desktop Audio) is hight and the bottom item (Mic/Aux) is low. but it shown revert!
Please check it...
Thanks!

**Comment by kkartaltepe** [comment]
@WizardCM were you going to submit a PR for this?

**Comment by WizardCM** [comment]
I can do so, this issue fell off my radar among other topics. I'll add it to my list.
