### ISSUE TITLE
win-capture: dx12 capture wrong frame

### ISSUE THREAD

**Issue by JacobHeAMD** [obsproject/obs-studio#5462]
### Operating System Info

Windows 10

### OBS Studio Version

Git

### OBS Studio Log URL

No log

### Expected Behavior

dx12 game should capture the backbuffer correctly, for example the first frame rendered 1, the second frame rendered 2, the third frame rendered 3, then the captured frame content should be 1, 2, 3.

### Current Behavior

dx12 game should capture the backbuffer correctly, for example the first frame rendered 1, the second frame rendered 2, the third frame rendered 3, then the captured frame content should be 1, 2, 3. However, sometimes, it is 1,2,1.
This is a regression of https://github.com/obsproject/obs-studio/pull/4939 .
It's possibly AcquireWrappedResources doesn't handle the memory barrier correctly, as a consequence, the old content of backbuffer was copied sometime since the latest content is not indeed written into the backbuffer (still resident in cache).

### Steps to Reproduce

1. startup any DX12 game
2. dump the captured images by adding some code
3. 
...

**Comment by jpark37** [comment]
Could you tell us why you closed this? Were you mistaken? I was going to ask someone to try to reproduce.
