### ISSUE TITLE
OBS encoder lags only when moving OBS window with display capture.

### ISSUE THREAD

**Issue by brifly34** [obsproject/obs-studio#5465]
### Operating System Info

Windows 11

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/Ufa8GcwkKSceXs_b

### Expected Behavior

For it to not lag

### Current Behavior

When I move the OBS window with display capture enabled, the whole encoder lags!

### Steps to Reproduce

1. Open OBS Studio
2. Switch to scene with display capture
3. Move the window

**Comment by Fenrirthviti** [comment]
Unable to replicate this, please use the Forums or Discord for support. Thanks!

https://obsproject.com/help
