### ISSUE TITLE
Transparency/Blend filter issues. 

### ISSUE THREAD

**Issue by fatihG** [obsproject/obs-studio#5466]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/XfGm6agt1hao500Y

### Expected Behavior

Applying an additive image mask on a black source, I expect the colours to be the same as the image used in the image mask filter.
It was like this in 27.0.0

Clip from 27.0.0
https://clips.twitch.tv/CooperativePoliteSwordWow-3LoqxeyAivy44lJl
notice the 'aurora' effect at the bottom

### Current Behavior

When an additive image mask is applied on top of a black source, the colours appear to be darker than the image that is used. 
Have not tested with versions between 27.0.0 and 27.1.2
Currently on 27.1.3

Clip from 27.1.3
https://clips.twitch.tv/ReliableBumblingInternPunchTrees-LzNLHxru27gwHSYZ
notice the 'aurora' effect at the bottom

### Steps to Reproduce

1. Add semi transparent black image source.
2. Add a scroll filter and notice how the transparency gets rendered differently.
3. Apply an image mask filter and set it to additive.
4. Notice how the image looks darker than the image used in the Image Mask filter.
...

### Anything else we should know?

This started to happen since I updated from 27.0.0 to 27.1.3. 
Had other issues with OBS where it would randomly freeze for a few seconds. 
I updated OBS mid stream and immediately noticed that the graphics I had set up for my visualizer looked different. 
Even mentioned it at the start of the stream:
https://clips.twitch.tv/BumblingSnappyCardCharlieBitMe-Mb7lP20IbCOlG7cV 

Read that a few post 27.0.0 releases 'fixed' things in relation to colour/transparency... My observation indicate that it is now less consistent. For example, enabling scroll filter on a semi transparent image alters the way the transparency is rendered. 

It feels like a Gamma issue. 
The smooth gradient I have in my mask image render a lot sharper now. 
The colours in my additive gradient image seems to have more contrast now.

**Comment by Fenrirthviti** [comment]
Many filters got updated to handle color more correctly, but we did not automatically upgrade the old behavior to the new behavior so we did not break existing setups, as the same settings would not work between the two filter versions. You can see in your logs that you have for example:

```
07:33:53.453:     - source: '-->Chat' (scene)
07:33:53.453:         - filter: 'Crop/Pad' (crop_filter)
07:33:53.453:         - filter: 'Image Mask/Blend' (mask_filter_v2)
```

Which is the new mask filter, so this should be working properly.

For this source:

```
07:33:53.453:         - source: 'Tracker' (window_capture)
07:33:53.453:             - filter: 'Color Key' (color_key_filter)
07:33:53.453:             - filter: 'Image Mask/Blend' (mask_filter)
07:33:53.453:             - filter: 'Crop/Pad' (crop_filter)
07:33:53.453:             - filter: 'Signed Distance Field Effects' (obs-stream-effects-filter-sdf-effects)
```

It's using v1 of the mask filter, so does not have the correct color/gamma/etc. handling. We know it's a pain, but you'll need to remove/readd all the affected filters to get the desired behavior. You can find more technical details here: https://github.com/obsproject/obs-studio/wiki/Linear-Color-Blending
