### ISSUE TITLE
Media source flashes image when image updating

### ISSUE THREAD

**Issue by CSMBY** [obsproject/obs-studio#5470]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

-

### Expected Behavior

Image does not flash

### Current Behavior

Image is flashing

### Steps to Reproduce

1. Create media source
2. Add a PNG file (or any other, APNG for example)
3. Press OK
4. The image is displayed in the live streaming
5. Open this media source again
6. Select another PNG (or APNG) file
7. Press OK
8. The image is flashed in the live streaming and then updates

This bug appeared in OBS 26+

### Anything else we should know?

Please do not advise using an simple image instead of media source:
1. Simple image does not support APNG
2. https://github.com/obsproject/obs-studio/issues/5444

**Comment by gxalpha** [comment]
The media source is not made for displaying images.

If the problem is that you need APNG support, please [open a feature request](https://ideas.obsproject.com) for image sources to support APNGs, and use a browser source in the meantime.
