### ISSUE TITLE
96c1a765 makes Media Source streams drop frames forever after network glitches

### ISSUE THREAD

**Issue by rationalsa** [obsproject/obs-studio#5474]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

Git

### OBS Studio Log URL

-

### Expected Behavior

The Media Source should play back at the stream's framerate after recovering and re-syncing after a glitch.

### Current Behavior

See Steps to reproduce. That sort of scenario is pretty common when streaming to OBS over a mobile network.

I've done a git bisect and I've traced the issue down to commit 96c1a765. I don't have a good understanding of how async frames work in OBS, but to me it looks like the author forgot to copy `free_async_cache(source);` from the deleted `if (source->async_frames.num >= MAX_ASYNC_FRAMES) {}` to the new `if (!available) {}`. Adding it in fixes the problem in the current git HEAD.

I've also added a `printf()` in `if (source->async_frames.num >= MAX_ASYNC_FRAMES) {}` and saw that when OBS is dropping source frames, this condition is always true, while after adding `free_async_cache(source)` it's only true a few times after the Media Source recovers.

### Steps to Reproduce

1. Set up a media source with an SRT stream.
2. Make the stream glitch by throttling or disconnecting the network for a few seconds, but not for long enough that the connection will timeout
3. After recovering, the media source will drop about half the frames until it's reloaded.
...

**Comment by jpark37** [comment]
Leaving out free_async_cache was intentional. The goal was to avoid reallocating memory.  It's annoying that network streams don't seem to recover in the way that local files did.

I don't have a ton of time at the moment to look, so I'm fine with just reverting the commit for now.

**Comment by alinsavix** [comment]
Hmmm. Could this also be the source of the problem in #5469 ?

**Comment by rationalsa** [comment]
@jpark37 I'm happy to open a pull request either to revert the patch entirely or just to add in `free_async_cache(source)`. What would be preferred? The original patch also removed `clean_cache()`

**Comment by jpark37** [comment]
I'd prefer a revert over a new pattern that doesn't help with the original concern, and may cause new bugs.

Jim can handle the revert whenever he gets around to looking at this issue.

**Comment by djr0x** [comment]
Same problem with 27.1.x , with 27.0 no problem

**Comment by AlfaTelevision** [comment]
This problem also the versions27.1, 27.1.1, 27.1.2, 27.1.3 for windows 10.
This is a biggest problem for the streamer. I ask one solution. Obs is the best app for the twitch live
