### ISSUE TITLE
Game Source shows and hides itself when the game window is resized

### ISSUE THREAD

**Issue by IamMusavaRibica** [obsproject/obs-studio#5477]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/f9teg7W8uzsxEq2R

### Expected Behavior

The game source should remain visible at all times

### Current Behavior

The game source hid and showed after every resizing

### Steps to Reproduce

I think it should be straightforward but add a Game Capture, don't make it fullscreen nor maximize it, and look at it in OBS studio

### Anything else we should know?

I tested this in 27.0.1 and 27.1.3

**Comment by IamMusavaRibica** [comment]
Here is a video recorded with camera to show that behaviour https://streamable.com/x5u8o2

**Comment by Nofew** [comment]
I don't think this is a bug; when you resize a window and you're on Game Capture, OBS has to re-hook it. Windows stops rendering once a resize operation begins; if you click and drag a border and move it slightly, but don't release your mouse, the game appears frozen until you let go.

**Comment by IamMusavaRibica** [comment]
How should I be able to make it reappear in OBS studio then?


uto, 2. stu 2021. u 15:41 Nofew ***@***.***> napisao je:

**Comment by Fenrirthviti** [comment]
This is expected behavior, as the game does not render until the resize operation has completed. This is a limitation we have no control over.

**Comment by Nofew** [comment]
It reappears automatically when you let go with your mouse, as you've demonstrated in your video.
