### ISSUE TITLE
warning: Failed to create xdg-screensaver: 2

### ISSUE THREAD

**Issue by ethaniel** [obsproject/obs-studio#5479]
### Operating System Info

Ubuntu 20.10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/7gNUKi_POicfu3Dy

### Expected Behavior

No error.

### Current Behavior

I am noticing the following errors in the logs: 
```
error: XDG_RUNTIME_DIR not set in the environment.
warning: Failed to create xdg-screensaver: 2
warning: Failed to create xdg-screensaver: 2
```
Everything else works normally, however I'm noticing rendering stuttering every now and then, I'm still trying to figure out if it's XDG related or not.

### Steps to Reproduce

I am running OBS inside a docker container. The host is Ubuntu 20.04 LTS, the container is Ubuntu 20.04 as well.
The container is started with the following command:

```
sudo docker run --name=obs_world -it -d --gpus all \
    --restart=unless-stopped \
    --add-host=host.docker.internal:host-gateway \
    --privileged \
    -e DISPLAY=:0 \
    -e QT_X11_NO_MITSHM=1 \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -v ~/.Xauthority:/root/.Xauthority \
    -v /root/obs-config/world:/root/.config/obs-studio \
    PRIVATEREPO/obs
```

I can provide a Dockerfile if needed for building the OBS, but it's heavily tuned for my environment (gpu passthrough,  for instance). 

I am using Docker, because I run multiple instances of OBS on my machine and it's easier to control them this way.

**Comment by ethaniel** [comment]
If anyone else stumbles upon this thread looking for a solution to run OBS inside a Docker container, then I'll save you many hours - just don't. Not only it loses in processing speed, there are a lot of dirty hacks involved.

If you want to run multiple OBS instances with separate configurations, then just start them under separate users:

```
sudo useradd -m obs-1
sudo -u obs-1 /usr/bin/obs -m -p
# configs will go into /home/obs-1/.config/obs-studio

sudo useradd -m obs-2
sudo -u obs-2 /usr/bin/obs -m -p
# configs will go into /home/obs-2/.config/obs-studio
```

**Comment by WizardCM** [comment]
Running OBS in a Docker container is not an officially supported use case. You may have more luck asking in the Linux Support channel on Discord.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
