### ISSUE TITLE
Virtual camera menu bar text is incorrect when OBS launched with `--startvirtualcam`

### ISSUE THREAD

**Issue by jfarmer** [obsproject/obs-studio#5484]
### Operating System Info

macOS 11.6

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/mWoRxaTAaqhlmUak

### Expected Behavior

On MacOS, when OBS is launched with `--startvirtualcam` both the button in the main window and the menu item should read "Stop Virtual Camera"

(Internally, OBS refers to this as the "system tray" on the Mac.)

### Current Behavior

When OBS is launched with `--startvirtualcam`, the menu item reads "Start Virtual Camera" instead of "Stop Virtual Camera". Clicking the button still _stops_ the virtual camera without updating the text, so everything is correct after the first click.

See screenshots below, taken just after startup.

<img width="264" alt="CleanShot 2021-11-03 at 10 42 55@2x" src="https://user-images.githubusercontent.com/37304/140163499-347a22fb-061a-4234-8d3b-753b05e2c086.png">
<img width="255" alt="CleanShot 2021-11-03 at 10 42 29@2x" src="https://user-images.githubusercontent.com/37304/140163456-4877d429-332f-4be6-92a3-d6f6a8556ccc.png">

### Steps to Reproduce

1. Launch OBS with `--startvirtualcam`
2. Look at main virtual camera button and see "Stop Virtual Camera"
3. Look at menu bar item (system tray) and see "Start Virtual Camera"

### Anything else we should know?

I'm not familiar with the OBS code base but tried to investigate myself. It _looks_ like this should be set in `OBSBasic::OnVirtualCamStart` See: https://github.com/obsproject/obs-studio/blob/a2c3896e1a5e4efb3bf42724bffb14c1d4222519/UI/window-basic-main.cpp#L7267-L7268

This is the only place where the main button is explicitly marked as checked. I assume it's how the main button starts in the "checked" state when OBS is launched with `--startvirtualcam`, and it's meant to do the equivalent thing for the system tray menu, too.

Maybe there's a race condition/timing issue where `OnVirtualCamStart` is called the first time before the system tray is initialized/loaded? I'm not sure how menu bar initialization works on macOS.

**Comment by gxalpha** [comment]
Can confirm, same with `--startrecording` and `--startstreaming`.
Also icon doesn't update properly.
