### ISSUE TITLE
Twitch VOD Track: Audio Track Still Recorded & Sent To Twitch VOD

### ISSUE THREAD

**Issue by LegnaGH** [obsproject/obs-studio#5492]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/RhgVCwYhAQ1NU17e

### Expected Behavior

Hi,

I have Voicemeeter Banana to route Desktop Audio to VAIO input for live streams and VOD.
I also have it to route Firefox and Spotify to AUX input for live streams and exclude from VOD.
Firefox and Spotify are set to AUX input in Advanced Sound Options in Windows sound settings.

I enabled Twitch VOD Track. Desktop Audio is set to Track 1. Twitch VOD Track is set to Track 6.
I added an Audio Output Capture source and set device to AUX input in order to exclude audio.
Track 6 is not checked, is unchecked in Advanced Audio Properties.

The above should exclude Track 6 audio from live streams and recordings.
Below are attachments of screenshots of my OBS settings.

![streaming](https://user-images.githubusercontent.com/93764589/140486588-a81a5b4c-12a9-4455-969e-3f7822cb3f8b.png)
![recording](https://user-images.githubusercontent.com/93764589/140486616-2528a45b-c6e6-488e-bfd9-1f9d85b1d423.png)
![advanced-audio-properties](https://user-images.githubusercontent.com/93764589/140486677-eddc7f4b-c0c8-4db4-9e0a-09d2b9eb0e59.png)

### Current Behavior

Twitch VOD Track does not appear to be working.

Track 6 is still recorded and is still sent to Twitch VOD.

### Steps to Reproduce

1.
2.
3.
...

### Anything else we should know?

I asked for help on Discord. A community member tried to help, asked for screenshots of my settings.
Said community says my settings appear to be correctly set. Directed me to open a ticket here.

**Comment by mihawk90** [comment]
This sounds like you're monitoring the VoiceMeter Output to the Desktop audio, which would then include it in the Desktop Audio recording.

Mute the FF/Spotify device in OBS and try another stream-test. If you're still getting both of them in the recording, something is routing the virtual audio to your Desktop Audio.

PS: I'm not sure why you were immediately redirected here, reading the Discord convo, not a lot of troubleshooting was even attempted... not exactly your fault tho.

**Comment by LegnaGH** [comment]
I did a test and muted the FF/Spotify device in OBS, the audio is muted and is not sent.

If it helps with troubleshooting, while the FF/Spotify device plays audio, the OBS audio mixer shows audio playing for the device.
The OBS audio mixer also shows no audio plays for the Desktop Audio as shown in the attachment below.

![screenshot](https://user-images.githubusercontent.com/93764589/140505216-f856de8c-6e4c-4dfd-8bce-fcb7ca662d0c.png)

**Comment by Fenrirthviti** [comment]
I've done some quick testing on my end, and in a reduced test scenario with only two audio devices and no complicated monitoring/external routing setups, everything is working fine so this is likely not an issue with OBS, but something being overlooked in the setup.

Going to close this as a support issue, please use our Discord or Forums for further assistance. If we can identify the exact conditions that cause a real bug, this can be reopened.
