### ISSUE TITLE
Discord window not updating correctly when being captured

### ISSUE THREAD

**Issue by curya** [obsproject/obs-studio#5496]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

.

### Expected Behavior

Discord should not stutter when being captured.

### Current Behavior

When Discord is being captured and a Discord video call is active, the window will only behave correctly as long as either your mouse keeps moving or the call overlay is active. Not sure which one. Could be both. But once you stop moving your mouse, the Discord window will immediately get stuttery and the videos on the call will flash previous frames.

The OBS window sees no issues and the recording always turns out just fine.

### Steps to Reproduce

1. Capture Discord.
2. Receive video call.
3. When video call is active, stop moving mouse.
4. The video in the Discord window will begin to stutter.

### Anything else we should know?

May or may not require to go fullscreen during video call. Not in a position to test at this very moment.

Also this is using the Windows 10 capture method.

Also also "capture cursor" is turned off.

**Comment by nico-apps** [comment]
A log file would be quite interesting to see. Please do the following:

1) Start Recording/Streaming.
2) Try to replicate the issue as best as you can.
3) Stop Recording/Streaming.
4) Go to Help > Log Files > Upload Current Log File, then paste the link here.

**Comment by Fenrirthviti** [comment]
Please use the Discord or Forums for support.

https://obsproject.com/help
