### ISSUE TITLE
Black Game Capture using Windows 11

### ISSUE THREAD

**Issue by ElFatFat** [obsproject/obs-studio#5499]
### Operating System Info

Windows 11

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/-kHzsTr9Ka5jMb9N

### Expected Behavior

When using Game Capture, the current Fullscreen software (or the one we select) should apper in the preview (and the record).

### Current Behavior

Everything works fine, but Game Capture doesn't show anything. I tried to capture using "Capture any fullscreen application". Doesnt work, the source stays black.
"Capture specific Window" doesn't work either.

### Steps to Reproduce

1. Launch OBS
2. Create a "Game Capture" source.
3. Select "Capture any fullscreen application"
4. Right click on your preview and click "Windowed projector (source)" to be sure that we're only watching this source.
5. Launch a game (It's Overwatch for me)
6. Game capture stays black.

### Anything else we should know?

I'm not sure if this is related to the Windows 11 update, but before, when using windows 10, everything worked perfectly fine.
Btw, sometimes the cursor of the game is still showing up, but not the game itself.

**Comment by Mister36MN** [comment]
The issues section of github is for reproducible and trackable bugs in the program, not basic support. Please use the forums or discord in the future. 

https://obsproject.com/knowledge-base/game-capture-guide-and-troubleshooting

**Comment by ElFatFat** [comment]
Hmm... Why should i go to the support? Every solutions online that exists, I already tried them. Nothing have changed since Windows 10. So it's obviously a bug, maybe it's very rare and very specific, but for me, it's not just "badly configured".

**Comment by dodgepong** [comment]
Because it's not obviously a bug. Just because you haven't been able to solve your problem on your own does not mean no solution exists. The proper support channels will help you with your issue. If they determine that you have indeed encountered a real bug, then we will re-open the issue with more detail as to the bug's nature.
