### ISSUE TITLE
Unable to properly end a scheduled YT broadcast

### ISSUE THREAD

**Issue by Vainock** [obsproject/obs-studio#5500]
### Operating System Info

Windows 11

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/rgsXX0yxUYSr8qKM

### Expected Behavior

Clicking 'End Broadcast' should actually stop the broadcast.

### Current Behavior

Reproducing to steps 4 makes OBS act weird:
- After clicking on 'Start Streaming' you will be prompted if you really want to stop the stream. Clicking 'Yes' does nothing.
- Closing OBS keeps it running in the background and unresponsive in the system tray.

### Steps to Reproduce

1. Create a YT broadcast, schedule it for later and select it.
2. Click 'Start Streaming'.
3. Click 'Go Live'.
4. Click 'End Broadcast'.
5. (Click 'Start Streaming'.)

### Anything else we should know?

Clicking 'Go Live' freezes the UI for about 4 seconds. To improve the UX that should be made async.

**Comment by energizerfellow** [comment]
Known issue with older AMD GPU drivers and AMF encoder-related bugs. You need to update to at least Adrenalin 21.10.2 or higher and restart your PC after the driver update.

**Comment by Vainock** [comment]
This seems to have fixed my issue. Thank you for helping!
