### ISSUE TITLE
FTL huge audio delay

### ISSUE THREAD

**Issue by Anulo2** [obsproject/obs-studio#5519]
### Operating System Info

Other

### Other OS

Garuda Linux

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/BKZ_VEdW-nBtzC--

### Expected Behavior

Video stream and audio stream to be in sync 

### Current Behavior

Video stream arrives immediately while the audio arrives after 1 minutes and 10 seconds.

### Steps to Reproduce

1. Open OBS
2. Set Glimesh Stream Key
3. Start Streaming
4. Check on Glimesh if there's a delay  or not between audio and video

### Anything else we should know?

The Glimesh team could not help me solve this issue. they pointed me to this Windows custom build that appear to solve the issue: https://onedrive.live.com/?authkey=%21ACxwpoEllEmYg3g&id=D94D958570E61553%21185646&cid=D94D958570E61553
I'm on linux though. So I had to compile it from source: https://github.com/Glimesh/obs-studio same issue. Before trying this I was using obs-studio from the community repo and then obs-studio-browser (installed following this guide: https://www.jeremymorgan.com/tutorials/linux/how-to-install-obs-arch-linux/). I've also tried obs-studio-tytan652 (https://aur.archlinux.org/packages/obs-studio-tytan652/). Same issue. 
The log is from obs-studio-browser.

**Comment by notr1ch** [comment]
Per [this discussion](https://github.com/obsproject/obs-studio/discussions/4021), FTL support in OBS is deprecated and slated for removal, so FTL related issues are not in-scope. Please use a different protocol.
