### ISSUE TITLE
Move transition utilizes wrong transition types on mirror sources on complex scenes

### ISSUE THREAD

**Issue by NOVAinc** [obsproject/obs-studio#5520]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/i3Sn1VrVfSQm8xB0

### Expected Behavior

Sources use existing values from the "move transition override" filters to transition to other scenes as described within the filter values.

### Current Behavior

Sources behave as if different options were selected instead of the correct ones. For example a source is told to use "fade" transition, at "none" direction when disappearing, and instead it "slides" as opposed to fading.

### Steps to Reproduce

1.1 Select move as transition type between scenes. 
1.2 Use "away from center" as default direction for appearing/disappearing settings. Everything else as default.
1.3 Create a different type of transition for scene transitions, such as slide BUT just create it, don't actually use. Keep move transition as default scene transition. I think it's just important to have _created_ a different transition type for the bug.
2. Add multiple sources to one scene.
3.1 Add mirror sources or references to the original sources on the same scene.
3.2 Add groups and move some sources inside the group
4. Add "move transition override" filters to both original and source mirror if using source mirrors otherwise references should take the same value from original. When items are inside groups you should add filter to the group itself, not the items inside it
5. Set up the filter for every source so they have no zoom, no position, and use fade transition when appearing and disappearing.
6. Create a different scene with only group sources, some at the same locations they were in the previous scene some at different.
7. Move between both scenes. Some sources will ignore your settings and use slide or a different transition type other than "fade". You might also see that the group sources start to slowly drift away from their position as you transition between scenes multiple times, even if you lock transformations.

### Anything else we should know?

I am using StreamFX to access source mirrors, but I don't think this would be the cause of the bug since it seems to be misbehavior on the transitions, no the objects.

**Comment by RytoEX** [comment]
Have you reached out to the respective plugin authors about this?  This seems like it could possibly be an issue with either source mirror (StreamFX) or with Move Transition, or possibly a bad interaction between the two.

**Comment by Fenrirthviti** [comment]
We do not directly support those third party plugins, please report the issue to the move transition repo. If Exeldro determines it's an issue with OBS itself, he's usually pretty good at submitting fixes for them.

**Comment by NOVAinc** [comment]
Thanks to both of you for your replies. I thought for whatever reason move was built into OBS since a recent release. I might have recalled this incorrectly. Sorry. I will report the issue to the author of the move plug-in!
