### ISSUE TITLE
Custom Output (FFmpeg) rawvideo 1080p cuts off recording

### ISSUE THREAD

**Issue by FireCulex** [obsproject/obs-studio#5526]
### Operating System Info

Windows 11

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/tools/analyzer?log_url=https%3A%2F%2Fobsproject.com%2Flogs%2FvhmgUctcBcyfyUdr

### Expected Behavior

Record for 90 seconds. 

### Current Behavior

Cuts off 60% of the recording. There's nothing obvious to indicate why. 

### Steps to Reproduce

1. Scene Collection -> New
2. Game Capture
3. Disable Preview
4. Record 
5. 90 seconds stop Recording
...

### Anything else we should know?

- There is no issue when scaled to 720p. 
- If I record for 2 minutes at 1080p, 1 minute of 1080p will be saved. At 30 seconds only 17 seconds will be saved.
- The moment I hit the record hotkey to stop, disk activity immediately ceases.
- Confirmed same behavior on W10 laptop

**Comment by notr1ch** [comment]
Custom output is not supported - there are many combinations of settings that may or may not work, you're on your own when you use custom output. Most likely your system does not meet the requirements for rawvideo at 1080p.
