### ISSUE TITLE
Video cannot be recorded the second time

### ISSUE THREAD

**Issue by dunkirk-4** [obsproject/obs-studio#5529]
### Operating System Info

Windows 11

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/3vUTqs2fGpF_eHpM

### Expected Behavior

When i open obs and press "Start Recording" it can recoding the video，and when i press "Stop Recording" and press "Start Recording" again it can  recoding the video also.

### Current Behavior

When i open obs and press "Start Recording" it can recoding the video，and when i press "Stop Recording" and press "Start Recording" again ,the text on the button is still  "Start Recording" 

### Steps to Reproduce

1.open the obs
2.press "Start Recording"
3. press "Stop Recording"
4. press "Start Recording" again
...

### Anything else we should know?

Cpu intel(R) i5-10600KF
Gpu AMD Radeon RX6800
I recording a video to show you  what happened ,maybe it will help solve the problem.
here is the address of the video:
https://www.bilibili.com/video/BV12h411x7Yj

**Comment by flaeri** [comment]
Please come join us in the support channels on discord (<https://obsproject.com/discord>) for issues like this. 
Looks to be a driver issue.

**Comment by WizardCM** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
