### ISSUE TITLE
window capture doesnt work on a window manager in X11 (nvidia/linux)

### ISSUE THREAD

**Issue by ana-rchy** [obsproject/obs-studio#5531]
### Operating System Info

Other

### Other OS

Arch linux with linux-zen 5.15.2 kernel

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/_SRn2C8a8Znl-vjh

### Expected Behavior

window capture should display/output whatever is on a certain window

### Current Behavior

window capture just shows black screen

### Steps to Reproduce

1. download obs-studio from arch package repos
2. run it in X11 bspwm, with nvidia card and drivers
3. open it normally through any means
4. try use window capture

### Anything else we should know?

im using X11 bspwm, nvidia card/official drivers (differing driver versions have the same result), and have nvidia-dkms drivers installed for linux-zen too
display capture works perfectly fine, window capture doesnt

**Comment by kkartaltepe** [comment]
Please use the Discord https://obsproject.com/discord or the forums https://obsproject.com/forum for technical support.
