### ISSUE TITLE
OBS Audio input/output does not work as expected

### ISSUE THREAD

**Issue by CrossHusky** [obsproject/obs-studio#5532]
### Operating System Info

Other

### Other OS

Fedora Linux 35

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/aaYWc_ekDpMYVTEb

### Expected Behavior

Input and output should be independent

### Current Behavior

Input and output are the same

### Steps to Reproduce

1. Open OBS
2. Add source/change device settings.

### Anything else we should know?

Used under pipewire 0.3.40, tried both rpm and flatpak versions.
Happens with multiple devices ex. alc887, alc4042
Using EasyEffects 6.1.2

**Comment by Fenrirthviti** [comment]
Please use the forums or Discord for support. There is unfortunately not enough information to action this, and I've tested and it works fine on my Ubuntu test system. Additionally, Fedora is not an officially supported platform, so any packaging issues may need to be reported to the respective maintainer.

This sounds like a configuration issue with your environment, the folks in #linux-support in the Discord should be able to help point you in the right location.
