### ISSUE TITLE
Selecting an output device results in the app choosing an input instead.

### ISSUE THREAD

**Issue by Zaicyn** [obsproject/obs-studio#5533]
### Operating System Info

Other

### Other OS

Garuda

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/x8lOktxz0iCWnsVB

### Expected Behavior

I expect an output device to be selected.

### Current Behavior

The app selects the default input device and plays that as an output. This results in no output devices being available.

### Steps to Reproduce

1. Install Garuda (or Fedora, it seems they are having this issue as well.)6
2.Select an output device.
3.Hear your mic coming through the output monitor.

### Anything else we should know?

I discovered this bug through an app called Helvum, which is also what I used to temporarily fix it. Also if I look under audio>applications in settings on my computer, it shows OBS with two inputs, rather than an output and an input.

This is on pipewire 0.3.40-1, which is the most up to date as I write this.

**Comment by kkartaltepe** [comment]
Not a bug. You can only record from pulseaudio inputs (sources). Recording from a pulseaudio output (sink) involves creating a pulseaudio input (source). This is what the obs source "pulseaudio output" does.

If you are having trouble configuring your audio you should use our discord https://obsproject.com/discord/ or our forums https://obsproject.com/forum/ for support configuring your system.

**Comment by Zaicyn** [comment]
That still doesn't address the issue of it not using the device I selected. And changing the selection to the default input instead.

**Comment by Zaicyn** [comment]
Found the fix for this. It was not a bug in OBS, but rather in pipewire.
https://gitlab.freedesktop.org/pipewire/wireplumber/-/merge_requests/264

**Comment by zany130** [comment]
> Found the fix for this. It was not a bug in OBS, but rather in pipewire. https://gitlab.freedesktop.org/pipewire/wireplumber/-/merge_requests/264

fix was reverted in wireplumber they say the fix needs to be done in obs https://gitlab.freedesktop.org/pipewire/wireplumber/-/issues/122

**Comment by kkartaltepe** [comment]
We dont implement pipewire audio capture, so i'm not sure how their suggestion is relevant. If pipewire breaks pulseaudio backwards compatibility that is not a fault of OBS and likely will not be fixed for a long time.

**Comment by artur-borys** [comment]
I've managed to get it working with pavucontrol and manually changing the input for OBS there, to "Monitor of {your headphones/speakers name}"

**Comment by Beraxes** [comment]
> I've managed to get it working with pavucontrol and manually changing the input for OBS there, to "Monitor of {your headphones/speakers name}"

thanks man, this solution work for me.
