### ISSUE TITLE
Obs pulling audio stream from my mic when I select my output device.

### ISSUE THREAD

**Issue by Zaicyn** [obsproject/obs-studio#5534]
### Operating System Info

Other

### Other OS

Garuda

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/Mxp3kXgGN7_soLfC

### Expected Behavior

I expect OBS to record my output device.

### Current Behavior

OBS records my mic, even when I select something else.

### Steps to Reproduce

1.Install Garuda (Or Fedora, as the same issue seems to happen there)
2.Select an output device.

### Anything else we should know?

I am using pipewire version 0.3.40-1, which is the most up to date on my distro as I write this.

**Comment by kkartaltepe** [comment]
Please do not open a new issue because you did not like the first response to your original issue.

**Comment by Zaicyn** [comment]
You are dismissing an actual bug here. I have been using OBS in windows and linux for 7 years. I know how it SHOULD work. I'm telling you its broken.
