### ISSUE TITLE
image-source: Huge images may hang or crash OBS when loaded

### ISSUE THREAD

**Issue by flaeri** [obsproject/obs-studio#5541]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://gist.github.com/flaeri/511fc9b4c105267a6b34a9b16b44d6ad

### OBS Studio Crash Log URL

https://gist.githubusercontent.com/flaeri/a0dd53850e050a184e09c3d00049ff3c/raw/a6ff918bf2c272183732f2a0862604e8b91d3a04/gistfile1.txt

### Expected Behavior

For OBS to reject loading images that are huge, pop up a warning, or somehow prevent loading the image, and possibly informing users that the image is too large.

### Current Behavior

Attempt to load the image, seemingly hanging the image-source indefinitely. OBS will hang on exit, and on the next launch it will most likely crash.

### Steps to Reproduce

1. Make a blank/new scene collection (this one you may have to delete)
2. Create a 12 500 x 12 500 pixel image (or use mine attached)
<https://otterbro.com/huge-explody-pic-grad.jpg>
3. Attempt to load it into OBS. It will hang, give it a moment.
4. Attempt to exit obs (it will hang), force close it in the task manager
5. Attempt to start OBS. You should now crash.
6. Fix it by removing the scene collection attempting to load said image.

### Anything else we should know?

I've tried with both PNG and JPG, and JPG seems more crash prone (all else equal).
Format                                   : JPEG
Width                                    : 12 500 pixels
Height                                   : 12 500 pixels
Color space                              : YUV
Chroma subsampling                       : 4:4:4
Bit depth                                : 8 bits

**Comment by flaeri** [comment]
Seems I kind of uploaded the wrong log (has a bunch of plugins). It happens without plugins as well, so im adding "clean" crash and normal log here:
https://gist.github.com/flaeri/9ae3bf637da73db34b22c47f7f9db32d
Has both

**Comment by peerau** [comment]
It's probably the same as this: #3427 and #3571

**Comment by kkartaltepe** [comment]
Closing in favor of #3427
