### ISSUE TITLE
Crash OnExit

### ISSUE THREAD

**Issue by kirillkrylov** [obsproject/obs-studio#5547]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Version (Other)

27.1.3 (64 bit)

### OBS Studio Log URL

https://obsproject.com/logs/TeBmmfaw-Fwzgr1T

### OBS Studio Crash Log URL

https://obsproject.com/logs/SWq6gDrtQS3qja9p

### Expected Behavior

Actual: OBS crashes every time I exit the application
Expected: Not crashing
Not crasshing OnExit

### Current Behavior

Everytime onExit
![image](https://user-images.githubusercontent.com/7285114/142579989-5a90bdab-a393-42ec-9624-39e8b539ca11.png)

### Steps to Reproduce

1. Exit the application viz WinFrame(X) or File->Exit

**Comment by RytoEX** [comment]
This appears to be a bug with the obs-ndi plugin.  The plugin maintainers are aware of it and will be looking into this.

**Comment by kirillkrylov** [comment]
Issue can be partially mitigated when "Preview Output" is unchecked

![image](https://user-images.githubusercontent.com/7285114/142586590-60846f04-4117-4633-92d8-db8af9f45668.png)
