### ISSUE TITLE
Game capture on ver 27.1.3 doesn't work

### ISSUE THREAD

**Issue by M0nsh3r1** [obsproject/obs-studio#5561]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/eVhqWtJnW6lwQ3O5

### Expected Behavior

Game will be captured correctly 

### Current Behavior

Game capture can't show record game window

### Steps to Reproduce

1. Updating to 27.1.3
2. Start the obs and game(Genshin Impact or World of Warcraft) from administrator
3. Open scene with this game and choose correct window same as at previous ver 27.0.1
4. First frame of the game will be shown in OBS preview window and freeze until restart OBS or Game

### Anything else we should know?

After an update from ver 27.0.1 to 27.1.3 game capture doesn't work anymore. The picture freeze on the first frame and nothing happened. All other settings like window capture and desktop capture work fine in both versions. 
Rollback to 27.0.1 and game capture works fine again.

**Comment by nico-apps** [comment]
Please use our Forums or Discord for Support.
https://obsproject.com/help

**Comment by Fenrirthviti** [comment]
We are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
