### ISSUE TITLE
When recording in m3u8 format using AMF encoder, the second and subsequent TS files are broken.

### ISSUE THREAD

**Issue by shinji3** [obsproject/obs-studio#5564]
### Operating System Info

Windows 11

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/_bwCHtoFaZcP8A9j

### Expected Behavior

Recorded with m3u8

### Current Behavior

the second and subsequent TS files are broken.

### Steps to Reproduce

1.Encoder uses H264 / AVC encoder (AMD Advanced Media Framework)
2.Format uses m3u8
3.Start Recording
4.the second and subsequent TS files are broken.
...

### Anything else we should know?

Bug Fix Pull request
https://github.com/obsproject/obs-amd-encoder/pull/412

**Comment by shinji3** [comment]
I uploaded a bug test video
https://github.com/shinji3/BugTestVideo

**Comment by RytoEX** [comment]
This Issue is against the legacy AMD encoder, which is no longer maintained.
