### ISSUE TITLE
OBS cannot access input devices (webcam, microphone,...) macOS Monterey

### ISSUE THREAD

**Issue by MartinKrimm** [obsproject/obs-studio#5577]
### Operating System Info

macOS 12.0

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/9vVHOMQqu2F6zzuw

### Expected Behavior

I start to setup a fresh and clean installation of OBS on my Mac Book Pro.
I added the internal webcam of the Mac Book as an Video Capture Device.
After I select the webcam device I expect to saw a preview picture and I can adjust the settings of the webcam.

If there is a problem with the webcam stream I would expect to give OBS the access to the webcam in the privacy settings.

### Current Behavior

After I add the Video Capture Device and select the webcam as device the preview did not start.
It is not possible for me to receive a image from a video capturing card. Also it is not possible to route an audio input to OBS. Screen recording is possible.
If I have a look to the privacy settings of macOS OBS is not shown up, e.g. in the tab camera. It is only possible to add OBS to the screen recording. 

The webcam is functional. Other apps can use the webcam as input.

### Steps to Reproduce

1. Add a new Video Capture Device
2. Select the internal webcam "FaceTime HD Camera"
3. Have a look to the preview window

**Comment by asher-the-thrasher** [comment]
would you be able to run this `csrutil status` in the terminal and send the output?

**Comment by MartinKrimm** [comment]
The status output is:

System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: disabled
	Filesystem Protections: disabled
	Debugging Restrictions: disabled
	DTrace Restrictions: disabled
	NVRAM Protections: disabled
	BaseSystem Verification: enabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.

**Comment by asher-the-thrasher** [comment]
So it looks like you need to re enable your SIP (system integrity protection). you can see how to do that at the bottom of the page [here](https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection). Then see if you can enable obs in the camera and mic settings in the security and privacy system preferences.

**Comment by MartinKrimm** [comment]
Thank you very much! Enabling the SIP fixed the problem.

**Comment by MartinKrimm** [comment]
Thank you very much! Enabling the SIP fixed the problem.
