### ISSUE TITLE
500 MB logs folder

### ISSUE THREAD

**Issue by KulaGGin** [obsproject/obs-studio#5584]
### Operating System Info

Windows 10

### OBS Studio Version

25.0.4

### OBS Studio Log URL

Not needed

### Expected Behavior

Limited size for logs. Who needs logs from 1.5 years ago?

### Current Behavior

Logs folder grows indefinitely.

### Steps to Reproduce

Use OBS.

### Anything else we should know?

Logs folder grows indefinitely: 
![image](https://user-images.githubusercontent.com/16989713/143680953-c5217b2d-d356-42ab-8f05-3f58884d0ebd.png)

I was cleaning my drive and noticed this. I don't need 500 MB of logs from OBS, I doubt anyone needs it. It would make sense to limit logs size to just few megabytes. And yes, 500 matters, I already cleaned 50 GB of this kind of bloat from the drive just now.

**Comment by flaeri** [comment]
OBS, by default only keeps the last 10 logs. Either your logs are 50mb each, which would be huge. Or there is some other stuff in there that was been kept, or this is default is somehow overridden by a custom built or something to that effect.

**Comment by KulaGGin** [comment]
Yes, was only around 10 .log files. I immediately deleted them and decided to report only after I deleted them.

**Comment by nico-apps** [comment]
Please update to 27.1.3, version 25.0.4 is very old.

**Comment by flaeri** [comment]
> Yes, was only around 10 .log files. I immediately deleted them and decided to report only after I deleted them.

Ok, then something is hardcore spamming the logs if you manage to get them up to 50mb.  Would need to see one of those logs to be able to tell you what is spamming them.

This isnt really a matter for github tho, and I suggest you come join the discord, and we can work it out there in the support channels.
<https://obsproject.com/discord>
