### ISSUE TITLE
Browser docks feature missing (Linux, 27.1.3)

### ISSUE THREAD

**Issue by rixx** [obsproject/obs-studio#5596]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/69FC_8CVip1RM_xe

### Expected Behavior

As of the OBS 27 release, browser docks are [supposed to be available](https://obsproject.com/blog/obs-studio-27-released) on Linux in the View -> Docks menu.

### Current Behavior

The View -> Docks menu only shows the options to reset/lock UI and to show/hide the predefined docks.

### Steps to Reproduce

I'm running the standard Archlinux package with no modifications. Tried uninstalling and reinstalling aswell, and removing all configuration files, to no effect.

**Comment by tytan652** [comment]
The `obs-studio` package in the Arch Community repo does not provide all the features.
Ask the OBS discord for more help about OBS on ArchLinux.

https://obsproject.com/wiki/Install-Instructions#about-unofficial-builds

**Comment by ElectronicWar** [comment]
No official AUR package is currently provided by the OBS team. Switch to the upcoming Flatpak distribution or ask your maintainer to include the desired feature.

**Comment by thebiblelover7** [comment]
> No official AUR package is currently provided by the OBS team. Switch to the upcoming Flatpak distribution or ask your maintainer to include the desired feature.

I'm here with the same problem. @ElectronicWar I tried the flatpak but don't see any browser dock. Is it still not there? If not, how else can I get the browser dock on linux?

**Comment by WizardCM** [comment]
If you're not seeing browser docks on Windows, you're likely on Wayland - browser docks are currently not supported on Wayland.

**Comment by thebiblelover7** [comment]
> If you're not seeing browser docks on Windows, you're likely on Wayland - browser docks are currently not supported on Wayland.

ah, makes sense. Yes, I am on Wayland. Any idea when  support for wayland will be added?

**Comment by WizardCM** [comment]
I believe it's a limitation of Wayland itself? Feature parity is important to us, so once it's something we can realistically achieve we'll definitely announce it.

**Comment by thebiblelover7** [comment]
> I believe it's a limitation of Wayland itself? Feature parity is important to us, so once it's something we can realistically achieve we'll definitely announce it.

great, thanks for the quick reply!

**Comment by rixx** [comment]
Yup, I can confirm that custom browser docks work on Linux with flatpak. Thank you so much for providing access to this feature!

**Comment by steven3363** [comment]
I have this issue on X11. Running F35 (Nvidia) with X11 as the display server

**Comment by Froidoh** [comment]
Can browser docks on wayland now be supported with the upgrade to CEF 95 that landed in obs-studio 27.2?

They are the one missing thing for a full-blown streaming env on wayland for me :/

**Comment by tytan652** [comment]
> Can browser docks on wayland now be supported with the upgrade to CEF 95 that landed in obs-studio 27.2?

No.

CEF still does not have a full-blown support of Wayland, no browser docks for now under Wayland.
