### ISSUE TITLE
MacOS export profile opens import window

### ISSUE THREAD

**Issue by asher-the-thrasher** [obsproject/obs-studio#5599]
### Operating System Info

macOS 12.0

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/WubKEqlS2sLIQSxX

### Expected Behavior

After clicking profiles > export, a finder window should show up to export a file that looks like this ![image](https://user-images.githubusercontent.com/76796294/144277951-0bdb9b17-8717-4421-a204-6428e5a25b52.png) but for the profile instead of scene collections.

### Current Behavior

a finder window opens to select a file to open that is the same as the import button 
![image](https://user-images.githubusercontent.com/76796294/144278684-8aa04b21-550d-4ae6-afdf-c868971c3c44.png)

### Steps to Reproduce

1. Click profile on menu bar
2. Click export
3. Finder window will open to open a file, not save a file

**Comment by WizardCM** [comment]
This is by design, operating system limitation. The `NSSavePanel` doesn't support selecting directories, and OBS Profile Export exports your profile to a directory. It should still behave as expected.
