### ISSUE TITLE
No audio output

### ISSUE THREAD

**Issue by visualJames** [obsproject/obs-studio#5601]
### Operating System Info

Other

### Other OS

Manjaro

### OBS Studio Version

27.1.3

### OBS Studio Log URL

None

### Expected Behavior

I expected that if I accidently deplug my headphones and plug then right after into my laptop again that the output audio would still be recorded.

### Current Behavior

No audio output after plugging the headphone into the computer.

### Steps to Reproduce

1. Plug your headphones into your computer
2. start recording
3. deplug your headphones
4. plug your headphones into your computer again
5. no audio anymore in audio output capture

**Comment by Fenrirthviti** [comment]
We are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
