### ISSUE TITLE
A crash caused by refs of obs_source without thread-safe

### ISSUE THREAD

**Issue by walker-WSH** [obsproject/obs-studio#5603]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

no

### Expected Behavior

refs is threasafe

### Current Behavior

when source is storaged from _obs_enum_sources_，we can't make sure if its refs has been released to -1.
If refs is -1, that means _obs_source_destory(source)_ is being invoked by another thread.
If run ++1 for source in callback，crash happen when --1 later...  

the  value of refs is changed as this order:
-1 （by another thread，destroy doing）
0（by enum thread）
-1（destroy again！）

### Steps to Reproduce

as above

### Anything else we should know?

while enumerating sources，refs should be checked

**Comment by RytoEX** [comment]
Since we implemented the destruction defer system, we consider this Issue resolved, per discussion on the linked PR (#5605).
