### ISSUE TITLE
Chroma key uses wrong blue key color

### ISSUE THREAD

**Issue by ArmorDarks** [obsproject/obs-studio#5610]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

1

### OBS Studio Crash Log URL

1

### Expected Behavior

Blue Screen key color should be `#0047bb`

### Current Behavior

It's actually orange `#ff9900 `

https://github.com/obsproject/obs-studio/blob/master/plugins/obs-filters/chroma-key-filter.c#L116

### Steps to Reproduce

1. Check the source code

**Comment by dodgepong** [comment]
That hex code is not RGB, it's BGR. In RGB form it is #0099FF.

If you'd like to suggest the hex code ought to be #0047BB (#BB4700 in BGR form) then that's another discussion to be had (and perhaps Green ought to be #00B140 while we're at it, but again that is another discussion). Probably best suited for the ideas page: https://ideas.obsproject.com/
