### ISSUE TITLE
pyenv is not honoured / python 3.6 EOL

### ISSUE THREAD

**Issue by Da-Boom** [obsproject/obs-studio#5628]
### Operating System Info

Other

### Other OS

Manjaro

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.1.3-tytan652-6

### OBS Studio Log URL

https://obsproject.com/logs/3_YF5Sal2ax5oWLE

### Expected Behavior

I expected pyenv to allow me to force OBS to use a different version of python

### Current Behavior

The pyenv vars are ignored and the system python binaries and libraries are used instead - this causes the python scripting engine to be unusable, as it ends up giving me tonnes of undefined for libraries that should just work

### Steps to Reproduce

1. update system - if your default python binary is 3.9.x, then it
3. install pyenv and setup python 3.6 
2. Install software via AUR package (`obs-studio-tytan652` or even just one of the other versions - this isnt the only AUR package where ive had this issue) 
3. set your pyenv to either local or global to use python 3.6
4. launch OBS with `pyenv exec obs`
5.run a python script that uses a standard C python library (such as datetime, urllib, math) - you will find undefined references and that it has ignored the pyenv setup, trying to load its libraries 

### Anything else we should know?

We need to allow environment variables to be honored so we can specify a python version upon launch

I also checked to see if this variable would be honored at compile time by running (though this could be a yay or a fakeroot issue)
`pyenv exec yay -S obs-studio-tytan652` 

Really, its high and time we update the python bindings to the latest python version anyway - **given that python 3.6 hits EOL in 2 weeks.**

I cannot use python scripting until this is fixed - i cannot uninstall python 3.9 as the package is in dependency hell (most of my packaged require python, and i cannot switch it out with 3.6 from the AUR - i actually already had that installed, but OBS wont use that by default anyway)

TBH the best stopgap solution right now would be to set up python so it **only** compiles with python if its a **known** working version of python. (AKA 3.6.x)

**Comment by WizardCM** [comment]
On Linux, OBS will use whatever version it's built with - you can change the CMake variables to reflect the version you want it to support. The codebase itself supports 3.8 afaik, but I think 3.9 is untested? I'm unsure if SWIG supports `pyenv` to allow for more.. dynamic mapping.

**Comment by tytan652** [comment]
`makepkg` used by `yay` will never respect/honour pyenv, because it builds the package inside a clean variable environement.

**Comment by Da-Boom** [comment]
> `makepkg` used by `yay` will never respect/honour pyenv, because it builds the package inside a clean variable environement.

That sucks, but also a clean variable environment means we should be able to set different variables in said environment and at least force python versions via the `PKGBUILD` - might look in to seeing if I can do this

> If you really want build OBS with a custom python. Try with the portable compilation. https://obsproject.com/wiki/Install-Instructions#linux-portable-mode-all-distros

How can i use this but enable all (except maybe python versions) the features/patches that you have in your build... but with a different python - also will this remove any features that are found in a non-portable compilation - if so, which ones?

> My AUR recipe have some backported fixes in them there is one to enable build with python 3.9.
> Here the one #5507 that is backported.

Weird I'm using your build via yay and, while it builds fine with python 3.9 enabled, anytime i try to run a python script inside OBS, it errors out with something along the lines of `[url-text.py] ImportError: /usr/lib/python3.9/lib-dynload/_struct.cpython-39-x86_64-linux-gnu.so: undefined symbol:  _PyFloat_Pack4`  (this is from the example `url-text.py` i found) - This looks like I'm having the very issue #2222 that the hack/fix #5507 should fix

**Comment by tytan652** [comment]
I updated my package with a missing fix, please next time use AUR comment or ask me at #linux-support in OBS discord server.
Since it's related to my package and not to the OBS project  itself.
