### ISSUE TITLE
"Woops, OBS has crashed!" problem keeps coming up under the latest OBS version 27.1.3

### ISSUE THREAD

**Issue by AlpAcA0072** [obsproject/obs-studio#5629]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://raw.githubusercontent.com/AlpAcA0072/obs-studio/master/2021-12-07%2022-23-53.txt

### OBS Studio Crash Log URL

https://raw.githubusercontent.com/AlpAcA0072/obs-studio/master/Crash%202021-12-07%2022-23-57.txt

### Expected Behavior

OBS is expected to be opened normally.

### Current Behavior

"Woops, OBS has crashed!" problem keeps coming up immediately after clicking the icon.

### Steps to Reproduce

1. Open the latest version OBS 27.1.3
2.
3.
...

### Anything else we should know?

I've tried several solutions including:

- Upgrade to the latest core graphics driver (Intel(R) UHD Graphics 630)
- Upgrade to the latest graphics driver (NVIDIA GeForce GTX 1050Ti)
- Run in compatible mode
# 
There are no problems with older versions of OBS such as 25.0.8.

**Comment by notr1ch** [comment]
You have an outdated Intel driver. See https://obsproject.com/forum/threads/obs-crashes-on-startup.148997/

**Comment by Mister36MN** [comment]
https://www.intel.com/content/www/us/en/products/sku/134906/intel-core-i78750h-processor-9m-cache-up-to-4-10-ghz/downloads.html
