### ISSUE TITLE
Ingame Overlays always recorded

### ISSUE THREAD

**Issue by uberhalit** [obsproject/obs-studio#5630]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

-

### Expected Behavior

Disabling `Capture third-party overlays` should stop OBS from recording ingame Overlays like Discord, Origin, Steam etc.

### Current Behavior

All overlays I tested are being recorded in OBS, regardless of the state of the checkbox.

Here is a screenshot of the Discord Overlay beeing shown in a recording: https://i.imgur.com/xBd59CR.jpg
Origin Overlay: https://i.imgur.com/T9E72pc.jpg

### Steps to Reproduce

1. Start OBS
2. Untick `Sources > Capture third-party overlays`
3. Setup Discord Overlay
4. Start a DX12 game like Battlefield 2042
5. Open the overlay ingame
6. Overlay is visible in OBS

### Anything else we should know?

I tested Discord, Origin, Steam and the RTSS Overlay, all 4 of the show up in OBS. 
XSplit manages to hide them just fine. 

This issue has been discussed here already: https://github.com/obsproject/obs-studio/issues/3946
The latest fix regarding this matter seems to be ineffective: https://github.com/obsproject/obs-studio/pull/4939

**Comment by WizardCM** [comment]
Are you seeing this issue only on DX12?

**Comment by uberhalit** [comment]
> Are you seeing this issue only on DX12?

I tested a DX9 game and the Origin Overlay was not visible so by looking at the previous issue I am assuming this is specific to DX12.

**Comment by micsthepick** [comment]
happened to me on Portal 2, which is DX9... right?

**Comment by Juliacare** [comment]
Ditto for FFXIV with its addon overlays. DX11, windows 10

**Comment by 44lr** [comment]
same happened to me on d3d11, and on most unity games, but sometimes it works just fine?

**Comment by Fenrirthviti** [comment]
We have made some significant changes to the way hooking works since this was reported, and we are no longer able to reproduce this against various test applications.

If this issue is still occurring on the latest OBS (28.1.2 at the time of writing), please reply here or open a new issue.
