### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by reynum2** [obsproject/obs-studio#5631]
### Operating System Info

Other

### Other OS

Debian

### OBS Studio Version

27.1.3

### OBS Studio Log URL

none

### Expected Behavior

Obs start correctly

### Current Behavior

```
obs
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/locale.ini
Attempted path: /usr/share/obs/obs-studio/locale.ini
Attempted path: share/obs/obs-studio/locale/fr-FR.ini
Attempted path: /usr/share/obs/obs-studio/locale/fr-FR.ini
info: Using preferred locale 'fr-FR'
Attempted path: share/obs/obs-studio/themes/Dark.qss
Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
info: CPU Name: AMD Ryzen 7 1700X Eight-Core Processor
info: CPU Speed: 2200.000MHz
info: Physical Cores: 8, Logical Cores: 16
info: Physical Memory: 15984MB Total, 12000MB Free
info: Kernel Version: Linux 5.15.0-2-amd64
info: Distribution: "Debian GNU/Linux" Unknown
info: Session Type: x11
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.13
info: Portable mode: false
Attempted path: share/obs/obs-studio/themes/Dark/no_sources.svg
Attempted path: /usr/share/obs/obs-studio/themes/Dark/no_sources.svg
QMetaObject::connectSlotsByName: No matching signal for on_tbar_position_valueChanged(int)
QMetaObject::connectSlotsByName: No matching signal for on_actionShowTransitionProperties_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_actionHideTransitionProperties_triggered()
info: OBS 27.1.3+dfsg1-2 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 48000
	speakers:        2
info: ---------------------------------
info: Initializing OpenGL...
Erreur de segmentation
```

### Steps to Reproduce

1. launch OBS from terminal

**Comment by Fenrirthviti** [comment]
We are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by glaubersm** [comment]
Why was this bug report closed as 'support request'?

**Comment by dodgepong** [comment]
Because this is very likely a misconfiguration issue rather than an actual bug with the program. If you're running into the same issue, please go through the support channels to ensure things are configured correctly. If it's determined that that point that there's actually a bug going on here, we will re-open the issue with additional context and more detailed reproduction steps.

**Comment by reynum2** [comment]
> Because this is very likely a misconfiguration
Ideed not I use the OBS from Debian repositories (the same worked perfectly before) 
I did not touch any configuration.

**Comment by dodgepong** [comment]
"Misconfiguration" also includes environment issues, or other issues related to your specific computer setup.

As I said, please go through support channels to resolve your issue, and if it's determined that there is a bug at that point, we will revisit this.

**Comment by Gol-D-Ace** [comment]
Leaving this here for the posterity.
Issue got solved by using the Flatpak instead of the Debian build.
