### ISSUE TITLE
OBS has trouble capturing Java Applications on proprietary NVIDIA Drivers

### ISSUE THREAD

**Issue by 0lhi** [obsproject/obs-studio#5635]
### Operating System Info

Ubuntu 20.04

### Other OS

Linux Mint 20 + Cinnamon DE

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/QAgYEbOcnWZ12ZMo

### Expected Behavior

OBS should be able to capture Java Applications without Desktop Decorations such as [Llanfair](https://github.com/gered/Llanfair) and [Chatty](https://chatty.github.io/) at every Window size, whether it is set to "resizable" or not.

### Current Behavior

These windows can be captured, but not consistently. The Window has to be randomly resized until it has a size that OBS likes. This step must be repeated on every start-up.

https://clips.twitch.tv/ColdbloodedSmokyMangetoutDatSheffy-M1kHGQSX-YfAYfXA

![BuggyOBS](https://user-images.githubusercontent.com/74732674/145292111-cd7ecd86-84be-405f-8917-ec0503e1a3bd.png)

### Steps to Reproduce

1. Download Llanfair (or Chatty with Settings -> Look -> _Use native window_ disabled) 
2. Capture the Window
3. Try to resize the Window and see how OBS reacts
4. Restart OBS and check whether previously working Settings still work

### Anything else we should know?

Tried to capture the "Stream Chat" of Chatty, which can be enabled at:

Extra -> Stream Chat -> Open Dialog

**Comment by kkartaltepe** [comment]
Consider trying #5503 to see if this helps you.

**Comment by 0lhi** [comment]
> Consider trying #5503 to see if this helps you.

Does this work on NVIDIA Drivers? It seems that #5685 disables the Change on NVIDIA Drivers :/

**Comment by 0lhi** [comment]
The issue does not occur when using the free nouveau driver. I guess, this only occurs with the proprietary driver now.

**Comment by kkartaltepe** [comment]
Provide an updated log from the latest version.

**Comment by 0lhi** [comment]
Log: https://obsproject.com/logs/lDjNjIx0UY3h3_LM

Test-Stream: https://video.ploud.fr/w/iiE6TEpKDrQTcRAa9fCFVW

**Comment by kkartaltepe** [comment]
Closing this out, this has been identified as a deficiency in nvidia drivers combined aggravated by gnome's composition implementation.
