### ISSUE TITLE
Browse button to add image or media source does not work on Ubuntu 20.x

### ISSUE THREAD

**Issue by helenvarley** [obsproject/obs-studio#5637]
### Operating System Info

Ubuntu 20.04

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/UT9_ZvONmOS3K8YU

### Expected Behavior

Setting up an image or media source, i expected the Browse button to allow me to navigate to the file on my local computer.

### Current Behavior

Nothing happens when I click on the Browse button

### Steps to Reproduce

1. right-click on an image or media source to access properties
2. click Browse to navigate to the file
3. nothing happens
...

https://user-images.githubusercontent.com/3437324/145390829-400cc03e-c91e-4806-aaa8-0883e28cde70.mp4

### Anything else we should know?

a friend suggested it could be an issue with pulse audio, but we could not work anything out. 
i tried uninstalling and re-installing OBS but this has not fixed the problem.
someone else has posted about this bug in july this year, https://obsproject.com/forum/threads/browse-button-no-longer-works-image-media-etc.146210/

**Comment by Gol-D-Ace** [comment]
Hi.
You are using the Snap package.

We have nothing to do with the Snap package (we don't make it) and therefore unfortunately can't help with it.

If you see this issue with the PPA though please reply and I will reopen the issue.

I tried with both the Snap and the PPA here and both show no issues. So I have some doubt that the PPA would help you there. I also don't think this is an issue with the package but rather your personal Ubuntu Installation.

**Comment by helenvarley** [comment]
thanks very much for the fast reply. i will try to install the PPA & see if that solves it :)
