### ISSUE TITLE
Freetype text source doesn't toggle text/path fields when toggling "Read from file"

### ISSUE THREAD

**Issue by dxf** [obsproject/obs-studio#5638]
### Operating System Info

macOS 11.6

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/BvqNhdneGR7qcacg

### Expected Behavior

Ticking the 'Read from file' box should disable the 'Text' box, and replace it with a path to file box.

### Current Behavior

The 'Text' box never disappears, and when a file location is entered into it, nothing happens

### Steps to Reproduce

1. Open OBS (Using an M1 Mac Mini)
2. Add Text (FreeType 2)
3. Click 'Read from file'
![Screenshot 2021-12-09 at 13 25 39](https://user-images.githubusercontent.com/38754061/145404672-3b3a632e-06e6-4597-891d-82150e29f726.png)
![Screenshot 2021-12-09 at 13 26 10](https://user-images.githubusercontent.com/38754061/145404768-1e89735d-ada5-4359-9f0a-d49eb31ef1bc.png)
![Screenshot 2021-12-09 at 13 26 20](https://user-images.githubusercontent.com/38754061/145404799-ed01368d-8857-486b-81d8-885f3d53a0ef.png)
![Screenshot 2021-12-09 at 13 26 36](https://user-images.githubusercontent.com/38754061/145404853-365da89a-54ed-41e2-ba0c-7b6d4e1a802b.png)

### Anything else we should know?

Reading the log, I can see that it fails to open file '' - presumably this is because I can't populate the field that it would normally source the path from.

**Comment by asher-the-thrasher** [comment]
If you scroll down a little in the properties window, you will see a text area for the file name. That’s where you should put the file name instead of the normal text box

**Comment by dxf** [comment]
> If you scroll down a little in the properties window, you will see a text area for the file name. That’s where you should put the file name instead of the normal text box

Found it - thanks!

I'd suggest that this should be changed, however, to mimic the behaviour of the Windows build, where the 'Text' field is replaced with the Path field - it caught me out, for sure.

**Comment by himanshu007-creator** [comment]
Hi ! I would like to work on this issue , please guide me on what needs to be done

**Comment by serakeri** [comment]
It looks like this should be closed by #5705

**Comment by jatinsahijwani** [comment]
i would like to work on this issue, can i?

**Comment by gxalpha** [comment]
As written, this is a feature request, for which we don't use GitHub Issues for tracking. As such, I will now close this issue.

Normally I would now advise you to open a formal feature request, however there is already an open Pull Request to address this (#7835), so that probably won't be needed.
