### ISSUE TITLE
ChromeOS blacklisted despite perfect GPU acceleration and IP Cam support

### ISSUE THREAD

**Issue by rayfoss** [obsproject/obs-studio#5642]
### Operating System Info

Ubuntu 20.10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/B5ntIeJmJTtYoQ_V 

### Expected Behavior

Can we roll this back? ChromeOS has added GPU support, stable Vulkan support, Official 11th gen Zen laptops and Neverware gaming rigs are running it too. They are also handy as portable monitors.

It's a bit strange to see this message from the OBS flatpak/Debian bullseye OBS release when the Blender flatpak runs perfectly.

### Current Behavior

The runtime environment is blacklisted not because of it's capabilities, but because of it's name.

### Steps to Reproduce

1. Get some OBS plugins that work on a Raspberry Pi, like Droidcam
2. Try to run them on your most powerful laptop
3. Be very confused as OBS clearly "runs", but only runs for the purpose of letting you know it's refusing to run.

### Anything else we should know?

Relevant discussions:
- Discriminating code: https://github.com/obsproject/obs-studio/pull/3239
    - The PR was made when Neverware shipped ChromeOS with Flatpak support... so people could easily get the latest OBS that would suddenly stop working immediately, not 4 years later as the PR OP opined
    - ChromeOS has added GPU acceleration, Vulkan stable support and many other improvements. If you have a Spectre patched BIOS give CloudReady a go, it comes with paravirtualized Linux support.
- https://www.reddit.com/r/obs/comments/r9aji9/obs_on_my_chromebook/
- https://github.com/flathub/com.obsproject.Studio/issues/99

**Comment by WizardCM** [comment]
As someone who does not own any machines running ChromeOS:

1. Does Window/Display capture work?
2. Does the user have access to hardware encoders such as VAAPI?

The most common support requests we'd receive (and the reason we added this block in the first place) is that people were unable to capture + encode due to the sandbox provided.

**Comment by rayfoss** [comment]
1. Technically yes... but by default only the mouse shows. As of ChromeOS 90 there is a built in screen recorder that records to webm... I can load that as a MediaSource, WHILE IT'S STILL RECORDING lmao. That works surprisingly well.
2. `05:07:28 AM.190: FFMPEG VAAPI supported`... yes
3. Not sure how to switch to software decoding... but I can composite a 12Mbps 1080p camera and play a media source with less than 18% CPU usage on a mid range last gen Intel 06-8e-0C Chromebook.

![Screenshot 2021-12-10 05 36 45](https://user-images.githubusercontent.com/876076/145569882-5b9ff559-ffc1-4ca5-a0bf-3a1e669c3796.png)

**Comment by WizardCM** [comment]
1. So that's a no - and it's our number one support request with Chrome OS.
2. Huh, interesting - and good to know.
3. **Encoding**, such as x264 in Settings -> Output. Video decoding in media sources is software by default.

I wouldn't be against providing some kind of workaround to allow for non-capture workloads, but the biggest concern is that first point - when users can download, install & launch OBS, they expect to be able to use all of its features but _especially_ display/window capture, and then to record/stream it.

**Comment by Gol-D-Ace** [comment]
There is already enough buzz on YouTube which makes it look like OBS works fully on ChromeOS. We don't need more of that IMHO.

**Comment by rayfoss** [comment]
We could switch the box to **warn** users... as opposed to risking bricking their container just to run some binary plugins for streaming... which it can do very well. Personally, the lack of Screen capture doesn't bother me... If I wanted something more professional I'd involve a capture device `My raspberry pi looks at me as if in danger`.

**Comment by Fenrirthviti** [comment]
Until such time as ChromeOS supports the basic functions required for OBS to work properly, we will not be providing support for it. Anyone who is savvy enough to know how to get around the lack of proper capture methods and the other issues will be able to easily compile OBS. Perhaps a cmake flag for the check would be prudent here, enabled by default as a compromise?

**Comment by kkartaltepe** [comment]
Its trivial to recompile obs without this check (`git revert  6058b6a87f2e0a29e77ff42b7616690589a0ae9c`) or to run the existing obs in yet another container/chroot which hides the trigger folder. The 7 people who want to use obs for 3rd part plugins while every core plugin doesnt work on chromeos do not outweigh the hundreds of people asking volunteers why obs starts but every built in capture plugin is broken. At least in my opinion and that of the volunteers i've spoken to.

**Comment by kkartaltepe** [comment]
I'm going to close this out as it sounds like nothing has changed since we commited  6058b6a87f2e0a29e77ff42b7616690589a0ae9c
