### ISSUE TITLE
Browser Sources Use Daylight Time on Brazil

### ISSUE THREAD

**Issue by Sxigames** [obsproject/obs-studio#5645]
### Operating System Info

Windows 11

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/LwKzSbt0TT_EmSSG

### Expected Behavior

When websites get the user time from a browser source, they should receive it without daylight time

### Current Behavior

They recieve 1 hour more than the pc time(18:00 turns into 19:00)receive

### Steps to Reproduce

1. Create a Browser Source from a website that uses user time

### Anything else we should know?

[Brazil stopped using daylight time on 2019](https://www1.folha.uol.com.br/cotidiano/2019/04/bolsonaro-confirma-que-nao-havera-horario-de-verao-em-2019.shtml)

**Comment by notr1ch** [comment]
This will likely be resolved with a CEF update, see https://github.com/obsproject/obs-studio/discussions/3853

**Comment by Sxigames** [comment]
Fixed on Latest Beta
