### ISSUE TITLE
Game capture mostly not captures any fullscreen game, or only the first frame that appears, than freezes

### ISSUE THREAD

**Issue by azure-hu** [obsproject/obs-studio#5646]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

26.1.1

### OBS Studio Log URL

https://obsproject.com/logs/Q3EqI-GBywlN9ghr

### Expected Behavior

The game set to full screen should appear in OBS, and able to capture with game capture.

### Current Behavior

Games randomly shows only the first frame, or not even visible in OBS. Sometimes only restarting OBS multiple times can help, sometimes even a complete system reboot cannot fix this. Removing and re-adding Game Capture to a scene not even fixes this.

### Steps to Reproduce

1. Start a game in full screen mode.
2. Switch to OBS, move it to a secondary display to monitor, what happens, and set game capture to that game.
3. Switch back to the game, and watch if game appears on OBS. If game appears, try to do something. Mostly in OBS, nothing changes, the first captured frame stay on. If game not appears, and nothing changes even if you do something in the game, then nothing else to do.

### Anything else we should know?

I've tried this even with a newer version, v27.0.1 on the same Windows 10 version (20H2 build: 19042.1288).
(logs uploaded to: https://obsproject.com/logs/0YlcZoCjKJMya1dE)

The games set to full screen not appears in Window Capture (maybe it's not a problem), but when the game is set to windowed borderless, a huge lag can be seen in OBS, or in the onlline stream (not counted to dropped frames), just, that cannot be seen in game.

It happens with Radeon Driver v21.10.2, but tried different drivers too, without upgrading or downgrading OBS.

I share my computer specs copied right from Steam system info.

Computer Information:
    Manufacturer:  Micro-Star International Co., Ltd.
    Model:  MS-7C84
    Form Factor: Desktop
    Touch Input Detected

Processor Information:
    CPU Vendor:  AuthenticAMD
    CPU Brand:  AMD Ryzen 5 5600X 6-Core Processor             
    CPU Family:  0x19
    CPU Model:  0x21
    CPU Stepping:  0x0
    CPU Type:  0x0
    Speed:  3700 Mhz
    12 logical processors
    6 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    AVX2:  Supported
    AVX512F:  Unsupported
    AVX512PF:  Unsupported
    AVX512ER:  Unsupported
    AVX512CD:  Unsupported
    AVX512VNNI:  Unsupported
    SHA:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Video Card:
    Driver:  AMD Radeon RX 5700
    DirectX Driver Name:  aticfx32.dll
    Driver Version:  30.0.13025.5005
    DirectX Driver Version:  30.0.13025.5005
    Driver Date: 10 5 2021
    OpenGL Version: 4.6
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 60 Hz
    DirectX Card: AMD Radeon RX 5700
    VendorID:  0x1002
    DeviceID:  0x731f
    Revision:  0xc4
    Number of Monitors:  2
    Number of Logical Video Cards:  2
    No SLI or Crossfire Detected
    Primary Display Resolution:  2560 x 1440
    Desktop Resolution: 4480 x 1440
    Primary Display Size: 23.62" x 13.39" (27.13" diag)
                                            60.0cm x 34.0cm (68.9cm diag)
    Primary Bus Type Not Detected
    Primary VRAM Not Detected
    Supported MSAA Modes:  2x 4x 8x 

Memory:
    RAM:  32693 MB

**Comment by notr1ch** [comment]
We use Github issues for verified and reproducible bugs. Please use the forums or Discord for support questions.
