### ISSUE TITLE
Profiles created/duplicated in 27.x (macOS) do not send traffic

### ISSUE THREAD

**Issue by hermiteer** [obsproject/obs-studio#5651]
### Operating System Info

macOS 12.0

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/w3hoBZXQR4blCtC-

### Expected Behavior

Duplicating and changing the stream key should stream as usual (assuming the key is valid).

### Current Behavior

When streaming was attempt with the new profile, OBS should show connected but the Twitch channel would remain offline. This also happened with the original profile, even though it had been used without issue before the dup (with 27.1.3).

Dropping back to a 26.1.2 did not work because it could not read the duped profile (many of the settings were missing).

Streaming was only possible by creating new profile, then pasting in the keys.

### Steps to Reproduce

1. Launch 27.1.3 with existing profiles (configured for Twitch) from 26.1.2
2. Profile > Duplicate
3. Open Settings and enter new stream key
4. Attempt to stream with new profile
5. Note that OBS will show connected in the bottom right status bar, but Twitch is not receiving
6. Switch profiles to the previous profile (that was duped)
7. Attempt to stream
8. Note that OBS will show connected, but Twitch is not receiving
...

### Anything else we should know?

It was double and triple checked that the pasted in key did have spaces at the end. The profile that was duped had been streamed to a couple days earlier, without any other app changes.

The profiles with other keys I have not been able to steam to (because they're busy or offline). I'll try another profile and see if the issue repros.

I stupidly deleted the original and duped profiles after creating new ones (which allowed me to stream). I'm trying to restore them with Time Machine and will attach to the issue.

**Comment by hermiteer** [comment]
This continues to be a problem with 27.1.3. For a different account, where I've refreshed the stream key on Twitch, OBS says it's streaming but Twitch never shows the channel as online. The log output from each attempt shows:

10:27:11.686: [rtmp stream: 'adv_stream'] Connecting to RTMP URL rtmp://sjc05.contribute.live-video.net/app...
10:27:12.301: [rtmp stream: 'adv_stream'] Connection to rtmp://sjc05.contribute.live-video.net/app successful
10:27:12.311: ==== Streaming Start ===============================================

**Comment by hermiteer** [comment]
I just created another profile in 26.1.2 with the same Twitch stream key, and was able to immediately stream. 27.1.3 streaming appears to be non functional.

**Comment by hermiteer** [comment]
27.1.0 also does not work. There must have been a breaking change in 27.

**Comment by hermiteer** [comment]
OK, I think I'm getting a handle on this.

Installed
- 26.1.2
- 27.0.0
- 27.1.0
- 27.1.3

Profiles created in 26.1.2 connect with 26.1.2.
Profiles created in 26.1.2 connect with 27.x
Profiles created in 27.x DO NOT CONNECT with 27.x

**Comment by hermiteer** [comment]
27.x failed to work with a resteam.io key last night too. I dropped back to 26.1.2 and the connection was stable.
At this point I don't believe 27.x is a usable version.

**Comment by Fenrirthviti** [comment]
Logs from sessions that worked and did not work would be helpful here. I have not been able to replicate this issue on my end by switching between versions, however I am testing on Windows.

**Comment by hermiteer** [comment]
Here are all the logs from that day. For any session that was no 26.1.2, OBS showed it was connected but the Twitch channel never went live. I wasn't able to determine how that is shown in the logs, but expect that y'all can read them better than I.

[logs.zip](https://github.com/obsproject/obs-studio/files/7781601/logs.zip)

**Comment by hermiteer** [comment]
Looks like this is not an issue in 27.2.4 or 28.1.2.
