### ISSUE TITLE
Update new version bug

### ISSUE THREAD

**Issue by MuXia-0326** [obsproject/obs-studio#5652]
### Operating System Info

Windows 11

### Other OS

21H2 22000.348

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/MWZvYJrdrAFuwTf9

### OBS Studio Crash Log URL

https://obsproject.com/logs/l7co0Ocpxo5ds4OE

### Expected Behavior

27.1.3 Installation open error,but Installation 26.1.0 can be used normally

### Current Behavior

27.1.3 Installation open error,but Installation 26.1.0 can be used normally

### Steps to Reproduce

1.Installation 27.1.3
2.open
3.Error message
...

**Comment by WizardCM** [comment]
You need to update your Intel video driver. You have 2 ways you can do this:

1. Update using the Intel Driver & Support Assistant, available at this link: https://www.intel.com/content/www/us/en/support/detect.html
2. Update by selecting the appropriate driver for your OS and GPU, at this link: https://downloadcenter.intel.com/product/80939/Graphics-Drivers

Always reboot your PC once your drivers are updated, even if you are not prompted to.

**Comment by MuXia-0326** [comment]
> You need to update your Intel video driver. You have 2 ways you can do this:
> 
> 1. Update using the Intel Driver & Support Assistant, available at this link: https://www.intel.com/content/www/us/en/support/detect.html
> 2. Update by selecting the appropriate driver for your OS and GPU, at this link: https://downloadcenter.intel.com/product/80939/Graphics-Drivers
> 
> Always reboot your PC once your drivers are updated, even if you are not prompted to.

I tried your suggestion, but after the test, it still doesn’t work. I don’t think it is caused by this problem. Another point I am using is a laptop. I don’t know if this will have any effect.
