### ISSUE TITLE
Browser plugin not working as intended with StreamKit

### ISSUE THREAD

**Issue by sfjuocekr** [obsproject/obs-studio#5656]
### Operating System Info

Ubuntu 21.04

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/MuMPRBbjyT6RXpqr

### Expected Behavior

OBS Browser to follow the "settings" I use for the voice widget.

### Current Behavior

Completely ignores any settings.

### Steps to Reproduce

1. Goto https://streamkit.discord.com/overlay
2. Configure a voice widget.
3. Select "Show Speaking Users Only"
4. Use the URL in the Browser plugin.

### Anything else we should know?

https://streamkit.discord.com/overlay/voice/554726596221861890/578226742205087754?icon=true&online=true&logo=white&text_color=%23ffffff&text_size=14&text_outline_color=%23000000&text_outline_size=0&text_shadow_color=%23000000&text_shadow_size=0&bg_color=%231e2124&bg_opacity=0.95&bg_shadow_color=%23000000&bg_shadow_size=0&invite_code=goonsquad&limit_speaking=true&small_avatars=true&hide_names=false&fade_chat=0

Is the URL I use, but 

https://streamkit.discord.com/overlay/voice/554726596221861890/578226742205087754

Should work as well by default, this works in a normal browser just not in OBS.

**Comment by notr1ch** [comment]
OBS doesn't care about any query parameters in the URL you entered, the behavior of those is entirely up to the implementation of the server or scripts running on the page.

**Comment by sfjuocekr** [comment]
Well, I know this is not working in a normal browser as intended either and you could have tested this for yourself as well.

Either way, the OBS Browser plugin has different behavior compared to the browser. As in, both URL do not work while the second one does work in the browser.

I would assume the second URL to work as well then, but that is not the case as the behavior is the same as the first URL.

This has always worked fine and I already complained about it to Discord as well, I get the same behavior in different browsers and the OBS bundled one is the one that shows different behavior.

**Comment by notr1ch** [comment]
We do currently ship a rather dated CEF so pages relying on the latest JS or Chrome features may behave differently to a desktop browser. We are tracking that at https://github.com/obsproject/obs-studio/discussions/3853 but I don't believe it's related to your issue. If you continue to have problems I would suggest contacting Discord for support with their overlay.

**Comment by sfjuocekr** [comment]
I have contacted Discord support about it, their answer was quite literally ridiculous at best! They told me to logout and log back into Discord, I don't even think their support employee understood the problem.

The problem is still there, the old linux-browser has the same issue so it has to be something Discord changed on their end with nobody at their support department able to comprehend the issue.

I get it, if you play games with five people there is not a big issue of having five names on the screen... we raid with a lot more than that and it just becomes a huge mess on screen.

**Comment by sfjuocekr** [comment]
I mean, these responses are truly on another level:

```
Hey there,

Thank you so much for reaching out! I'm sorry to hear that you're having issues with the Streamkit overlay. If you're currently using OBS, can you try logging out of all locations on Discord, then login into the web browser and desktop client at the same time?

If the stable desktop client isn’t working, could you try using the Public Test Build, and see if that works instead of the regular desktop app?: https://discordapp.com/api/download/ptb?platform=win

Since it's not officially released yet and is a pre-release build, it may break occasionally. So if you find yourself having trouble with it, you should switch back to our stable client!

If that doesn’t do the trick either, can you try setting your DNS to Google Public DNS? For instructions on how to set that up, please check out this support page: https://developers.google.com/speed/public-dns/docs/using

Hopefully, that works for you! If you have any other questions or are still running into issues, please let me know.

Best,
Alfred
```

**Comment by sfjuocekr** [comment]
And this:

```
Hello there,

Thanks for following up. Can you make sure that your device's drivers and operating system are on the latest software? You can use Windows Update to update your operating system. To update your drivers, use the software for your graphics card to check for video updates, then check Windows Device Manager for additional drivers.

Finally, if PTB has this issue as well, can you try our alpha client, Discord Canary? The latest version of Canary is available here: https://discordapp.com/api/download/canary?platform=win

Give all this a shot and let me know how it goes!

Best,
Alfred​
```

**Comment by Fenrirthviti** [comment]
These are all basic troubleshooting steps, and we often ask our users the same questions and to try similar things, I am not sure why you're posting them here. If you're attempting to "shame" them, you're only making yourself look bad by making fun of someone who is trying to help you. As the overlay isn't something we can directly support, please keep with with Discord's support. Thanks!

**Comment by sfjuocekr** [comment]
These are basic troubleshooting steps that are completely irrelevant to the issue, is your name Alfred and are you completely incompetent?

There has been no help at all, nobody even tried to follow the "Steps to Reproduce". I know this, because I have tested this on multiple machines. So much for support, just post "basic troubleshooting steps"... do you really think everybody is an idiot?

Why would I run Windows updates on a Linux machine, why would I need to change my Discord client. The issue is with a web URL. These are not basic troubleshooting steps, this is complete ignorance.

I'm sorry for my rant, I'm a software developer myself and seriously have never been treated this way before. It is ridiculous.

**Comment by dodgepong** [comment]
Sure, but understand that you're ranting about Discord support in a place intended for OBS bug reports. If it suddenly stopped working while OBS didn't change, then Discord had to have changed something.

That said, you may want to test out the [27.2 beta](https://github.com/obsproject/obs-studio/releases/tag/27.2.0-beta2) and see if the issue is still there, as the beta ships an updated version of CEF which might work better. If it works, then it's likely that Discord updated their overlay to require Chrome features that OBS did not support (which, IMO, is irresponsible on Discord's part).

**Comment by sfjuocekr** [comment]
I know, maybe someone else had the same problem and could chime in :)

Either way the problem is "solved" now, the doofus who updated StreamKit is using string comparison on booleans... so instead of =true you have to do =True.

Have also reported this to Discord, but they wanted me to do something unrelated so I have not responded to them again.

**Comment by pwaser** [comment]
Thank you sfjuocekr!! I was using it today for the first time and I was having the same problem! Great job on finding the silly bug! Now I can enjoy this cool widget :)

**Comment by CalamityJames** [comment]
This also fixed the problem for me, unreal that this is still not fixed at their end.

Thanks so much sfjuocekr!
