### ISSUE TITLE
Crash after being opened for long time in background

### ISSUE THREAD

**Issue by mcDandy** [obsproject/obs-studio#5660]
### Operating System Info

Windows 11

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/a8OO8mD2jbGNxZ2m

### OBS Studio Crash Log URL

https://obsproject.com/logs/XPSbXId3o70_4kVE

### Expected Behavior

It not crashing

### Current Behavior

I had OBS opened in background for a long time and now I discovered it crashed.

### Steps to Reproduce

I am not sure. 
1. I stopped recording
2.  switched PC to hibernation mode
3. turned on PC
4. Crash unknown time after

### Anything else we should know?

n/a

**Comment by Fenrirthviti** [comment]
We do not really support recovery from hibernation states, due to how OBS operates in realtime. There's likely nothing we can do. I'd recommend closing OBS before hibernating. If you can replicate this without hibernating, we can reopen and take a closer look.
