### ISSUE TITLE
there is a problem in the video timestamp if the video encoder use QuckSync H.264

### ISSUE THREAD

**Issue by wanstonq** [obsproject/obs-studio#5662]
### Operating System Info

Windows 8.1

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/16MgzdAOQsNZ1ncQ

### Expected Behavior

Incorrect timestamps need to be discarded

### Current Behavior

wrong timestamp 

### Steps to Reproduce

1.
2.
3.
...

**Comment by Fenrirthviti** [comment]
We are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
