### ISSUE TITLE
Incorrect colors when images and videos (media sources) have transparency.

### ISSUE THREAD

**Issue by qo4on** [obsproject/obs-studio#5664]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/7gMOL3cPNgM8Sr6G

### Expected Behavior

A yellow RGB image (255, 255, 0) with an opacity of 50% should have color (255, 255, 127) when placed on a white background (255, 255, 255).
https://stackoverflow.com/questions/10768836/how-does-alpha-blending-work-mathematically-pixel-by-pixel

### Current Behavior

It is (220, 220, 187) when Apply alpha in linear space **IS UNCHECKED**:
![image](https://user-images.githubusercontent.com/35609308/146593071-fa103653-95a1-4788-9e83-e5a225c53664.png)

It is (255, 255, 187) when Apply alpha in linear space **IS CHECKED**:
![image](https://user-images.githubusercontent.com/35609308/146596298-9d30a8e4-bd37-4fd6-955d-417789f24050.png)

### Steps to Reproduce

Create a clear yellow rgb (255, 255, 0) circle in any program, for example Photoshop. Then set its opacity to 50%. Then put it on a transparent background, save and use in OBS on a white rgb (255, 255, 255) background.

**Comment by qo4on** [comment]
I used **Straight or Non-premultiplied Alpha** images in the post above. Images with **Premultiplied Alpha** look even worse.

**Comment by Fenrirthviti** [comment]
Have you reviewed the page here?

https://github.com/obsproject/obs-studio/wiki/Linear-Color-Blending

I suspect MS Paint is not creating properly formatted images.

**Comment by qo4on** [comment]
If you check the colors that MS Paint creates, you will see that they are correct: (255, 255, 127) when you open an image (255, 255, 0) with an opacity of 50%. The problem is with OBS.

**Comment by jpark37** [comment]
If you want to know why 187 is halfway between 0 and 255, please read the Wiki page. I've looked at your examples, and the results are intentional.

**Comment by qo4on** [comment]
`(255, 255, 187)` is intentional for `(255, 255, 255)` color with 50% opacity in linear space. For sRGB space it should be `(255, 255, 127)`. What was the intention for `(220, 220, 187)`? What was the intention for the pre-multiplied alpha images?
