### ISSUE TITLE
NVENC HEVC creates variable framerate and artifacts

### ISSUE THREAD

**Issue by qo4on** [obsproject/obs-studio#5667]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/7gMOL3cPNgM8Sr6G

### Expected Behavior

Getting 60 fps when I set it to 60 fps, no video artifacts.

### Current Behavior

![image](https://user-images.githubusercontent.com/35609308/146627287-779783b0-c18e-43de-9ba7-25556fc81735.png)
![image](https://user-images.githubusercontent.com/35609308/146627203-193a48c1-f283-484f-b88c-a4a877d34293.png)
These settings work as expected:
Video: h264 (High 4:4:4 Predictive) (avc1 / 0x31637661), yuv444p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 15505 kb/s, 60 fps, 60 tbr, 15360 tbn, 120 tbc (default)

But nvenc hevc returns variable framerate and some artifacts:
![image](https://user-images.githubusercontent.com/35609308/146627608-51210ea6-6385-4953-983b-1c231a52de86.png)
![image](https://user-images.githubusercontent.com/35609308/146627753-cb72538b-6464-470e-8242-191060c24e7d.png)
Video: hevc (Rext) (hev1 / 0x31766568), yuv444p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 1199 kb/s, 60.17 fps, 60 tbr, 15360 tbn, 60 tbc (default)

### Steps to Reproduce

Set these settings on GTX1060.

**Comment by Fenrirthviti** [comment]
Custom ffmpeg output mode is effective unsupported, you are on your own. There is a chance that this will be resolved when we update the shipped ffmpeg versions in an upcoming release, but the ffmpeg-based hevc encoder is not something we directly support.

**Comment by Fenrirthviti** [comment]
Additionally, lossless preset is expected to be variable bitrate in nearly all cases.

**Comment by qo4on** [comment]
So OBS has no plans to support NVENC HEVC, right?

**Comment by Fenrirthviti** [comment]
We do not have any plans to support it at this time. HEVC is a licensing landmine, and we'd prefer to just not get involved.

**Comment by qo4on** [comment]
Are you going to support ffmpeg? It has a lot of useful stuff besides NVENC HEVC, which by the way works from there without any problems with fps even in lossless mode.

**Comment by Fenrirthviti** [comment]
We "support" the custom ffmpeg output mode in that we provide it as an option for users, but we do not really support the ffmpeg stuff itself. If you need assistance with settings or configuration, I'd recommend using the support channels.

https://obsproject.com/help

There's plenty of people familiar with ffmpeg who would be able to help you with settings there, we don't consider issues or bugs with ffmpeg output itself supported, as we just invoke the ffmpeg apis. It's provided without warranty or sanity checks.

**Comment by qo4on** [comment]
You might be interested to know that the variable fps problem exists for files captured with OBS in ffprobe only. And not only for hevc, but also for the qtrle codec. This test shows constant fps for both:
```
ffmpeg -i out.mov -vf vfrdet -an -f null -
```
Video files captured with StreamFX OBS plugin show the correct fps in ffprobe.
