### ISSUE TITLE
Linux: Window capture causes performance issues with proprietary nvidia drivers

### ISSUE THREAD

**Issue by univrsal** [obsproject/obs-studio#5685]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

Git

### OBS Studio Log URL

https://obsproject.com/logs/AqYbf16E3VT5g6cw

### Expected Behavior

Window capture should work as it did in https://github.com/obsproject/obs-studio/commit/4623a6b4bc4c89ceb5db684e2e7fbd57d01129aa. It seems that the issue originates from https://github.com/obsproject/obs-studio/commit/316f858c68d3ef3a73166191b6f89b7bc3f3387c which is linked to #5503.

### Current Behavior

Having a window capture visible will reduce the frame rate from 60 fps to 30. Moving any window around will reduce the frame rate even further.

### Steps to Reproduce

1. Have an nvidia card with proprietary drivers and obs built from master
2. Add a window capture

**Comment by WizardCM** [comment]
I can confirm the experience is not good on the proprietary Nvidia drivers.

![image](https://user-images.githubusercontent.com/941350/147089607-477b8870-30f4-4004-957a-1b2406680a84.png)

**Comment by ishitatsuyuki** [comment]
Looking at the logs, there is one suspicious line:

```
xcompcap: glXReleaseTexImageEXT failed: GLXBadPixmap
```

But a [search](https://github.com/search?q=glXReleaseTexImageEXT+obs&type=code) reveals that this thing has happened on Nvidia long before, so the error might or might not be related to actual issue.

As I don't own a Nvidia card, would you mind capturing a profile using the following instructions?

1. Install and set up `perf`. The exact method depends on what distro you are running.
2. Install [flamegraph (Rust version)](https://github.com/flamegraph-rs/flamegraph). If you have cargo installed and PATH properly set to include `~/.cargo/bin`, then it can be installed with `cargo install flamegraph`.
3. Launch OBS (the master version) and add the problematic capture source.
4. Obtain OBS' PID. You can use `pgrep -a obs` for example.
5. Run `flamegraph -p <PID>`. Switch back to OBS and briefly do anything that lags. Then interrupt the `flamegraph` command.
6. A flamegraph should be written to `flamegraph.svg`. Please upload it.

**Comment by univrsal** [comment]
I tried this a couple of times, but the graph doesn't really look all that useful. For this one I had the window capture showing before I started flamegraph, which meant that the framerate was reduced to 30, then started flamegraph and interrupted it quickly. For the other one I ran it a little longer and moved some windows to further reduce the framerate.
[flamegraph.svg.zip](https://github.com/obsproject/obs-studio/files/7774454/flamegraph.svg.zip)
[flamegraph_longer.svg.zip](https://github.com/obsproject/obs-studio/files/7774459/flamegraph_longer.svg.zip)

**Comment by ishitatsuyuki** [comment]
See if https://github.com/ishitatsuyuki/obs-studio/commit/a38b88e2c fixes the issue for you.

**Comment by univrsal** [comment]
Yeah that seems to have fixed it, thanks. Should I close this or wait for you to make a PR?
Also, I like the branch name but the way things are currently going my next gpu won't be from any vendor as I can't afford it :P

**Comment by ishitatsuyuki** [comment]
I will file a PR. Thanks for testing!
