### ISSUE TITLE
GPU Drivers installed although OBS does not detect them

### ISSUE THREAD

**Issue by FlufferyGR** [obsproject/obs-studio#5690]
### Operating System Info

Other

### Other OS

Fedora 35 - Linux 

### OBS Studio Version

27.1.3

### OBS Studio Version (Other)

OBS 27.1.3 (linux)

### OBS Studio Log URL

https://obsproject.com/logs/P39WJCKdn9TILlMk

### OBS Studio Crash Log URL

n/a

### Expected Behavior

opening normally

### Current Behavior

does not properly open and has an error window showing this
`[fluffery@bmw]$ obs
QSocketNotifier: Can only be used with threads started with QThread
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/locale.ini
Attempted path: /usr/share/obs/obs-studio/locale.ini
Attempted path: share/obs/obs-studio/themes/Dark.qss
Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
info: Platform: Wayland
info: CPU Name: AMD Ryzen 7 2700X Eight-Core Processor
info: CPU Speed: 3699.498MHz
info: Physical Cores: 8, Logical Cores: 16
info: Physical Memory: 16002MB Total, 6924MB Free
info: Kernel Version: Linux 5.15.10-200.fc35.x86_64
info: Distribution: "Fedora Linux" 35
info: Session Type: wayland
info: Portable mode: false
Attempted path: share/obs/obs-studio/themes/Dark/no_sources.svg
Attempted path: /usr/share/obs/obs-studio/themes/Dark/no_sources.svg
QMetaObject::connectSlotsByName: No matching signal for on_tbar_position_valueChanged(int)
QMetaObject::connectSlotsByName: No matching signal for on_actionShowTransitionProperties_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_actionHideTransitionProperties_triggered()
info: OBS 27.1.3 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 48000
	speakers:        2
info: ---------------------------------
info: Initializing OpenGL...
info: Using EGL/Wayland
info: Initialized EGL 1.5
error: eglChooseConfig failed
error: device_create (GL) failed
error: Failed to initialize video.  Your GPU may not be supported, or your graphics drivers may need to be updated.
info: Freeing OBS context data
info: == Profiler Results =============================
info: run_program_init: 2932.8 ms
info:  ┣OBSApp::AppInit: 1.642 ms
info:  ┃ ┗OBSApp::InitLocale: 0.651 ms
info:  ┗OBSApp::OBSInit: 66.85 ms
info:    ┣obs_startup: 12.372 ms
info:    ┗OBSBasic::OBSInit: 21.845 ms
info:      ┣OBSBasic::InitBasicConfig: 0.098 ms
info:      ┣OBSBasic::ResetAudio: 0.182 ms
info:      ┗OBSBasic::ResetVideo: 21.52 ms
info: obs_hotkey_thread(25 ms): min=0 ms, median=0 ms, max=0.001 ms, 99th percentile=0.001 ms, 100% below 25 ms
info: audio_thread(Audio): min=0 ms, median=0.012 ms, max=0.036 ms, 99th percentile=0.036 ms
info: =================================================
info: == Profiler Time Between Calls ==================
info: obs_hotkey_thread(25 ms): min=25.058 ms, median=25.079 ms, max=26.156 ms, 95.4955% within ±2% of 25 ms (0% lower, 4.5045% higher)
info: =================================================
info: Number of memory leaks: 182
`

### Steps to Reproduce

1. run ` sudo dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm`
2. then run `sudo dnf install xorg-x11-drv-nvidia-cuda obs-studio`
3. launching it doesnt open
...

**Comment by Fenrirthviti** [comment]
We are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by Fenrirthviti** [comment]
Additionally, the rpmfusion package is not maintained by us, you may need to reach out to them for further assistance with their packaging.

**Comment by FlufferyGR** [comment]
i see, thanks, will there be an offical version in the future 
from what i saw it only works on x11 and not wayland

**Comment by Fenrirthviti** [comment]
You should be able to use the flatpak package as an official package with support for Wayland.
