### ISSUE TITLE
chroma_key_filter v1 renders improperly since #5258

### ISSUE THREAD

**Issue by NarryG** [obsproject/obs-studio#5696]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

OBS-27.1.3-g41e465492

### OBS Studio Log URL

N/A

### Expected Behavior

Chroma Key v1 filters behave as it behaved before the refactor.

### Current Behavior

Chroma Keys versioned as `chroma_key_filter` and not `chroma_key_filter_v2` render improperly after [#5258](https://github.com/obsproject/obs-studio/pull/5460).

I've attached an image showing the same source in the CI build the day before that was merged, and after the merge.

![image](https://user-images.githubusercontent.com/3047793/147395703-d5f3df08-e298-4763-87c9-0aa9563ced13.png)  

This only affects chroma key sources that are versioned `chroma_key_filter`. As such, it only applies to sources with a chroma key filter created before https://github.com/obsproject/obs-studio/commit/47da18e26c91e116361281ae4a9269b90155775b

### Steps to Reproduce

1. Create a video source using Chroma Key in copy of OBS Studio before chroma_key_filter_v2 was introduced https://github.com/obsproject/obs-studio/commit/47da18e26c91e116361281ae4a9269b90155775b
2. Open any OBS version after [#5258](https://github.com/obsproject/obs-studio/pull/5460)
3. The Chroma Key renders incorrectly

**Comment by jp9000** [comment]
Thanks for pointing it out. I just reverted it.
