### ISSUE TITLE
OBS slows down entire computer and crashes OBS when adding an Elgado capture card

### ISSUE THREAD

**Issue by brak265** [obsproject/obs-studio#5699]
### Operating System Info

Other

### Other OS

macOS 12.1

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/G_0IwEAqQ0K227U8

### Expected Behavior

Use an Elgato HD60S+ to capture a Nintendo Switch

### Current Behavior

Webcam and Switch video feeds flash green and CPU usage skyrockets after adding elgato as a video source.  MacBook becomes laggy/unresponsive and OBS crashes. 

### Steps to Reproduce

1. Add Elgato as a video capture device.  That is all that is required to cause the crash. Crash happens a minute later, lag begins immediately

### Anything else we should know?

I am using a 8GB RAM M1 2020 MacBook Air. The application is definitely crashing, but I'm not sure where I can find a "crash log" unless you are talking about the macOS crash report which comes up.   There is nothing that says "crash log" in the menu bar where the other logs are stored, and OBS does not prompt me that there are any crash logs generated or where I can find them or upload them.

**Comment by WizardCM** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
