### ISSUE TITLE
Virtual Camera does not start (authentication error)

### ISSUE THREAD

**Issue by jivvy** [obsproject/obs-studio#5703]
### Operating System Info

Other

### Other OS

Arch

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/H5rg8GxEA6Ag-8E5

### Expected Behavior

Virtual camera would be started

### Current Behavior

Virtual camera does not start.
There seems to be a problem acquiring permission to run `modprobe`.

### Steps to Reproduce

1. `pacman -S obs-studio v4l2loopback-dkms`
2. Open terminal, `obs`
3. Click 'Start Virtual Camera'
4. Type password into prompt in terminal

### Anything else we should know?

Log uploaded does not contain full text. Here is the rest:

```
...
info: [pipewire] asking for desktop…
info: [pipewire] desktop selected, setting up screencast
info: [pipewire] created stream 0x563a30d07080
info: [pipewire] playing stream…
==== AUTHENTICATING FOR org.freedesktop.policykit.exec ====
Authentication is needed to run `/usr/bin/modprobe' as the super user
Authenticating as: jivvy
Password:
polkit-agent-helper-1: error response to PolicyKit daemon: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: No session for cookie
==== AUTHENTICATION FAILED ====
Error executing command as another user: Not authorized

This incident has been reported.
```

Of course, the password is being typed in correctly. Whether or not the keypresses are doing anything, I'm not sure.

Terminal used is Alacritty
Running Wayland with PipeWire

**Comment by notr1ch** [comment]
This looks like an upstream bug, https://gitlab.freedesktop.org/polkit/polkit/-/issues/17

In the meantime you can manually run `modprobe v4l2loopback` as root and it should work around the issue.

**Comment by jivvy** [comment]
Thank you, this work around works for me.
