### ISSUE TITLE
The Preview/Program text and scene names are not centered in the 18 scenes multiview

### ISSUE THREAD

**Issue by COOLIGUAY** [obsproject/obs-studio#5718]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.0 Beta 2

### OBS Studio Log URL

https://obsproject.com/logs/h9e4hfn6qh3o-Un7

### Expected Behavior

Text centered in the 18 scenes multiview layout.

### Current Behavior

The Preview/Program text and scene names are not centered in the 18 scenes multiview.

8 and 24 scenes layout are correctly centered.

### Steps to Reproduce

1. Create some scenes with long names
2. Set the multiview layout to 18 scenes
3. Show the multiview

### Anything else we should know?

The text is also not centered on version 27.1

18 scenes, preview/program and scene names not centered

![obs64_0yfT7rIoZX](https://user-images.githubusercontent.com/55640387/147839593-f110c236-54d7-47e1-9df6-cbbab68019a2.png)

8 scenes OK

![obs64_xRRkzgTQCA](https://user-images.githubusercontent.com/55640387/147839595-7dd7994b-da62-44e1-bcc0-7f12f06bab8e.png)

24 scenes OK

![obs64_CDmrIasZNh](https://user-images.githubusercontent.com/55640387/147839594-8e6d3049-ac81-405f-a16d-999c4a720786.png)

**Comment by WizardCM** [comment]
Note - looking at the PR and testing in 27.1.3, this bug was not introduced in 27.2 Beta.
