### ISSUE TITLE
Getting "Failed to open NVENC codec: Generic error in an external library" in Ubuntu 20.04 with NVIDIA NVENC H.264 Encoder

### ISSUE THREAD

**Issue by rohan-paul** [obsproject/obs-studio#5723]
### Operating System Info

Ubuntu 20.04

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/nydQNqLD78Dlx5MR

### Expected Behavior

After I hit 'Start Recording' > It does not create any new file in the output folder and then if I clik on "Stop Recording", OBS Hangs.

### My Log Report says (Help > Log Files > Show Log Files ) - Have Uploaded

```

[NVENC encoder: 'recording_h264'] Failed to open NVENC codec: Generic error in an external library
[NVENC encoder] nvenc_create_internal failed, trying again without Psycho Visual Tuning

```

As per the [official page](https://github.com/flathub/com.obsproject.Studio) - I have already done below

"Please see the wiki for extra configuration such as BlackMagic or [NVENC](https://github.com/flathub/com.obsproject.Studio/wiki/NVENC-Support) support."

Hardware accelerated video encoding with NVENC

NVENC requires the nvidia_uvm module and the creation of related device nodes under /dev. Manually loading the nvidia_uvm module will not create the device nodes, but invoking the nvidia-modprobe utility will.

#### Created file /etc/udev/rules.d/70-nvidia.rules: and included below line.

```
ACTION=="add", DEVPATH=="/bus/pci/drivers/nvidia", RUN+="/usr/bin/nvidia-modprobe -c0 -u"

```
But that did not help.

### Current Behavior

After I hit 'Start Recording' > It should start the recording.

### Steps to Reproduce

1.  Select NVIDIA NVENC H.264 as the Encoder
2. Hit Start Recording.
3. In Ubuntu 20.04
...

**Comment by Fenrirthviti** [comment]
We are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by tt2468** [comment]
The GT 730 does not support NVENC, hence the error.

**Comment by rohan-paul** [comment]
Thanks @tt2468 . Then guess upgrading my GPU is the only option.
