### ISSUE TITLE
Locking a scene source doesn't prevent dragging to resize

### ISSUE THREAD

**Issue by ntoff** [obsproject/obs-studio#5724]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.0 Beta 2

### OBS Studio Version (Other)

27.1.3 also affected

### OBS Studio Log URL

https://obsproject.com/logs/e1L3O7O9QPrvUzVe

### Expected Behavior

Locking a scene source should prevent resizing or moving that source around.

### Current Behavior

Locking a scene source merely hides the resize box (the red box that appears around a source in the preview window), but leaves it able to be resized if you guess where the resize handles are.

### Steps to Reproduce

1. Add a source, in my case it's a game capture set to capture specific window (heaven.exe from the unigine heaven benchmark)
2. Make sure the source fills the entire scene, or take note of where the resize handles are (the little squares on the corners / sides of the bounding box)
3. Click the padlock icon to lock the source
4. Select the source in the "sources" list (as it's locked, you can't select it from the preview window, you *must* click on it in the sources list)
5. Position the mouse cursor over where the resize handles are, note the cursor will change to the resize cursor, click and you can resize a "locked" source.

### Anything else we should know?

Also happens in previous versions of obs (tested on 27.1.3) but I only just noticed it now while testing 27.2-beta2

**Comment by WizardCM** [comment]
I can confirm this issue exists as far back as OBS 20.0.0 (August 2017) when locking sources was introduced.

Any source that's locked just hides its anchors - the click targets for them still exist & the user can resize a locked source via drag.
