### ISSUE TITLE
~45% higher GPU load with nvenc when OBS' window is minimized

### ISSUE THREAD

**Issue by stolendata** [obsproject/obs-studio#5725]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/wc64D_Ug2L7Xcbzf

### Expected Behavior

No discernable change in GPU video encode resource use.

### Current Behavior

GPU video encode resource use jumps from roughly 35% to 50%, which is a 45% increase (or 15 percentiles).

### Steps to Reproduce

1. Set up recording with nvenc h.264 (new), keep OBS window on-screen
2. Minimize OBS window to taskbar

### Anything else we should know?

NVENC H.264 (new), VBR 2500-7000 Kbps, 1 sec keyframe interval, Max Quality preset, High profile, Look-ahead + Psycho Visual Tuning enabled, 4 Max B-Frames.

**Comment by Fenrirthviti** [comment]
We are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by stolendata** [comment]
> We are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.
> 
> Thank you!

This is a bug report.

**Comment by notr1ch** [comment]
This is probably due to your GPU downclocking as there isn't enough load to require it to run at full power. This causes a corresponding higher percentage of the reduced clocks to be used which looks misleading on tools like Task Manager which do not show clock speed. Use a tool like GPU-z for proper monitoring of your GPU load.
