### ISSUE TITLE
Using "Sidechain/Ducking Source" in the Compressor filter causes crash when closing OBS

### ISSUE THREAD

**Issue by itroy187** [obsproject/obs-studio#5731]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.0 Beta 2

### OBS Studio Log URL

https://obsproject.com/logs/90WSE-D0VBPvhDsx

### OBS Studio Crash Log URL

https://obsproject.com/logs/c-vDs-mUC910Kozq

### Expected Behavior

The sidechain/ducking feature to work without crashes

### Current Behavior

Using "Sidechain/Ducking Source" in the Compressor filter causes crash when closing OBS

### Steps to Reproduce

1. Create Audio Input Capture
2. Create Audio Output Capture
3. Add a Compressor filter to the output capture and set the a "Sidechain/Ducking Source" to the audio input capture
4. Close OBS
5. OBS crashes

**Comment by jp9000** [comment]
Fixed with https://github.com/obsproject/obs-studio/commit/47d8f2e497705d38a22c9b9de26d7ccff5bba842
