### ISSUE TITLE
Recording video missing Audio track?

### ISSUE THREAD

**Issue by dragon2snow** [obsproject/obs-studio#5742]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/_gNGA7li_sLW8aJn

### Expected Behavior

recording

### Current Behavior

Push the video streaming,AV video capture device Audio track + Voice Audio track+  PC Audio track.
But when recording, AV video capture device Audio track is missing. only Voice Audio track+  PC Audio track.

### Steps to Reproduce

1.recording

**Comment by WizardCM** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

**Comment by dragon2snow** [comment]
I'm sure it's a bug
