### ISSUE TITLE
Logitech Rally Pan / Tilt is grayed out

### ISSUE THREAD

**Issue by goback136** [obsproject/obs-studio#5743]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/wKvWg-bLJLpPp5HV

### Expected Behavior

Pan and tilt the Logitech Rally camera

### Current Behavior

The sliders are grayed out

### Steps to Reproduce

1. Add the a Logitech Rally Camera (USB) as video device
2. open the Configure video screen 
3. Open the camera control tab
4. The Pan/Tilt options are grayed out 

### Anything else we should know?

I've installed the "Logitech Camera Settings"  software which can pan and tilt the camera so the drivers should be working.

**Comment by Fenrirthviti** [comment]
We are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance. However, the "Configure Video" dialog is provided by the webcam driver, so you will likely need to contact Logitech for assistance.

Thank you!
