### ISSUE TITLE
Recording video missing Audio track！is BUG!

### ISSUE THREAD

**Issue by dragon2snow** [obsproject/obs-studio#5744]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/_gNGA7li_sLW8aJn

### Expected Behavior

Push the video streaming,AV video capture device Audio track + Voice Audio track+ PC Audio track.
But when recording, AV video capture device Audio track is missing. only Voice Audio track+ PC Audio track.

### Current Behavior

Push the video streaming,AV video capture device Audio track + Voice Audio track+ PC Audio track.
But when recording, AV video capture device Audio track is missing. only Voice Audio track+ PC Audio track.

### Steps to Reproduce

Push the video streaming,AV video capture device Audio track + Voice Audio track+ PC Audio track.
But when recording, AV video capture device Audio track is missing. only Voice Audio track+ PC Audio track.

### Anything else we should know?

100% bug

**Comment by dragon2snow** [comment]
120% is bug.

Don't be so confident in your program. I'm not here to beg e

**Comment by kkartaltepe** [comment]
Please dont create new issues because you dont like the response to your previous issue.
