### ISSUE TITLE
The OS hangs because it eats up Windows 11 resources.

### ISSUE THREAD

**Issue by ogaaaan** [obsproject/obs-studio#5749]
### Operating System Info

Windows 11

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/Z3IMFRwP8_-ByO-G

### Expected Behavior

finish correctly.

### Current Behavior

not finish and OS is hang up.

### Steps to Reproduce

1. Launch OBS
2. Launch Game
3. Begin Streaming
4. Stop Streaming
5. Finish Game
6. Finish OBS but not finished
7. I have to restart my windows every time

### Anything else we should know?

it will happen so many times when after playing "Dark Souls REMASTERED".

**Comment by Fenrirthviti** [comment]
I am not able to replicate this issue on Windows 11 with any games I have, though I do not own Dark Souls Remastered to test against.

I've removed the link to the crash log to avoid confusion, as it doesn't appear related and is from October of last year.

**Comment by ogaaaan** [comment]
## Clash Report

https://obsproject.com/logs/k9RghGv2eHhRNLOn

## What is this?

![SS_004](https://user-images.githubusercontent.com/622793/160191685-75b6f5f9-649b-498f-8f1b-142acbb60cc9.JPG)

**Comment by Fenrirthviti** [comment]
That crash is happening in one of your VST plugins "Spline EQ"

The error message is coming from the obs-websocket plugin.

This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by ogaaaan** [comment]
Currently my OBS is still unstable. Once it becomes unstable, it runs very slowly until I restart Windows, even after I exit OBS. Task manager shows that OBS is not terminating properly. And I cannot terminate the task.
I think it is obviously a problem with OBS. I asked the question because I do not understand the above dialog, but it is not the main topic of this topic.
OBS is unstable. Please fix it. Even if it is unstable, a crash report is not generated, so I cannot give you a specific explanation.

**Comment by ogaaaan** [comment]
where is log file?

**Comment by ogaaaan** [comment]
where is support channel?

**Comment by Fenrirthviti** [comment]
I would recommend reaching out to the reWASD developer for further assistance if their tool is causing system instability issues.
