### ISSUE TITLE
DXGI display duplication fails to capture displays that were connected while obs-studio was already running

### ISSUE THREAD

**Issue by matoi974** [obsproject/obs-studio#5751]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/Kzb1bXllcBTHXbli

### Expected Behavior

The display that had just been added to the multi-monitor configuration should capture.

### Current Behavior

The display that had just been added to the multi-monitor configuration does not capture via DXGI display duplication, only via "Windows 10" method.

### Steps to Reproduce

1. Configure two Display capture sources to capture two different displays.
2. Quit OBS Studio
3. Change multi-monitor configuration to only use one display
4. Start OBS Studio
5. Change multi-monitor configuration to use both displays ("Extend")
6. Try capturing the second display again

**Comment by Fenrirthviti** [comment]
I'm not going to close this as I'll leave it for others to comment if they disagree, but I don't think this is a bug or anything we can do something about. Removing the display from your system is a destructive act, and when it's reconnect it's effectively a new device that doesn't have any memory of its previous existence, so you would need to reconfigure the display capture to point to the new device instead.

**Comment by matoi974** [comment]
No, that's not the issue here. The issue here is that you cannot capture this display anymore even if you create a new display capture source or edit the properties of an existing display capture source. The "Windows 10" capture method does not have this issue, but manually switching to DXGI causes nothing to be captured.

**Comment by walker-WSH** [comment]
I can reproduce it.  I think this is a bug.

Reason of this bug:
Result of `EnumDisplayMonitors` and `device->adapter->EnumOutputs` is different after reconnect monitor device. 

D3D11Device is created before reconnecting device. At that time, duplicator based on this D3D11Device can only enum one monitor.
After reconnecting, even there are two devices connected, the monitor list gotten by EnumOutputs still does not include new monitor.

**Comment by gxalpha** [comment]
As mentioned by Fenrir, plugging/unplugging devices is a hardware change that OBS isn't necessarily prepared to deal with.
Additionally, if it works fine with the WGC capture method ("Windows 10"), please use that instead.

If someone thinks they can fix this, please open a Pull Request, but as-is we don't consider this to be a bug.
