### ISSUE TITLE
Build failure with latest ffmpeg

### ISSUE THREAD

**Issue by adsr** [obsproject/obs-studio#5756]
### Operating System Info

Other

### Other OS

Debian testing

### OBS Studio Version

Other

### OBS Studio Version (Other)

fab293a6862dbe6aca9eb1bde0b00fad2d2cd785

### OBS Studio Log URL

N/A

### OBS Studio Crash Log URL

N/A

### Expected Behavior

Build succeeds

### Current Behavior

Build fails with some missing symbols:

```
/home/adam/obs-studio/plugins/obs-ffmpeg/obs-ffmpeg-output.c:346:3: error: implicit declaration of function ‘av_get_default_channel_layout’; did you mean ‘av_opt_get_channel_layout’? [-Werror=implicit-function-declaration]
  346 |   av_get_default_channel_layout(context->channels);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |   av_opt_get_channel_layout
```

etc

### Steps to Reproduce

1. Build and install ffmpeg at commit `b24f0c82b3c05f1f9ed072a343b744635c828298`. I'll paste my config below but it's probably irrelevant:
```--enable-libass --enable-libcaca --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-libopus --enable-libpulse --enable-libspeex --enable-libv4l2 --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-gpl --enable-libaom --enable-gnutls --enable-pic --enable-shared```
2. Build obs-studio at commit `fab293a6862dbe6aca9eb1bde0b00fad2d2cd785` with:
```cmake -DUNIX_STRUCTURE=1 -DENABLE_PIPEWIRE=OFF  -DBUILD_BROWSER=ON -DCEF_ROOT_DIR="../cef_binary_4280_linux64" .. && make```

### Anything else we should know?

This patch appears to fix the build: https://gist.github.com/adsr/16b359065c382082dc3450adbd9a343c

**Comment by WizardCM** [comment]
See #5665

**Comment by pkviet** [comment]
The pr indeed fixes these includes errors.

**Comment by adsr** [comment]
Thanks!
