### ISSUE TITLE
Multiple audio tracks fail at high frame rates.

### ISSUE THREAD

**Issue by lizardpeter** [obsproject/obs-studio#5763]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/i8yceKg6G7evLVtG

### Expected Behavior

The recording should work perfectly.

### Current Behavior

The recording never starts, and when trying to stop it, it reports "Stopping recording..."

### Steps to Reproduce

1. Set FPS to 120 or another high value.
2. Use multiple audio tracks.

**Comment by WizardCM** [comment]
Duplicate of #2855
