### ISSUE TITLE
Recording Capture device on Linux lags out when screens are off

### ISSUE THREAD

**Issue by nmousouros** [obsproject/obs-studio#5767]
### Operating System Info

Other

### Other OS

Fedora 35 (Gnome)

### OBS Studio Version

27.1.3

### OBS Studio Version (Other)

OBS Studio - 27.1.3 (linux)

### OBS Studio Log URL

https://obsproject.com/logs/v1uM0wiqm1v_izOB

### Expected Behavior

When I use my usb capture device with my nintendo switch to output to another program, I should be able to lock my computer, or tun off my monitors

### Current Behavior

When my computer locks or just my screens turn off to save power ( not sleep or stand by just screens off) I get almost 0FPS.

### Steps to Reproduce

1. Connect Something to the USB to HDMI
2. Start video capture and record the video 
3. Lock computer
4. Unlock and check the video
It should be fine until the computer locks, then it should lag a lot

[obs-latency.zip](https://github.com/obsproject/obs-studio/files/7835030/obs-latency.zip)

### Anything else we should know?

Uploaded a short video of this happening, I am riding my bike, I lock the computer latency start happening, I unlock my computer and I am in a completely different place when latency catches up.

Also uploaded a screenshot of my settings

**Comment by Fenrirthviti** [comment]
It looks like this is more of a support/environment issue rather than a bug with OBS itself. We are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
