### ISSUE TITLE
The Monitoring Device Reinitialization Problem

### ISSUE THREAD

**Issue by DarkR** [obsproject/obs-studio#5770]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

-

### Expected Behavior

The monitoring device should be reinitialized as Mic/Auxiliary Device do that:
`18:51:32.880: Device 'Mix 01 (ASIOVADPRO Driver)' invalidated. Retrying
18:51:35.894: WASAPI: Device 'Mix 01 (ASIOVADPRO Driver)' [44100 Hz] initialized`

### Current Behavior

The monitoring device stays inactive after device restart and I need to rechoose it again in the dropdown list.

### Steps to Reproduce

I've made a video:
https://paper.dropbox.com/doc/OBS-Monitoring-Device-Issue--BYp~mpeF~10~iO17xp8ChSn~AQ-vr255LRagOJcVwnpEhQUr

**Comment by walker-WSH** [comment]
Oh~~ can't open your video

if your issue is same with https://github.com/obsproject/obs-studio/issues/4463, it can be fixed in https://github.com/obsproject/obs-studio/pull/5398

![1643182956](https://user-images.githubusercontent.com/18413354/151122626-182de853-3dd3-41fd-8a7b-a2a78aa5a32e.png)

**Comment by DarkR** [comment]
The issue is resolved in beta. Also we start to use this plugin with separate Track 3 for monitoring and it works perfectly in any case.
https://github.com/exeldro/obs-audio-monitor
