### ISSUE TITLE
Fedora Linux OBS No Sound 

### ISSUE THREAD

**Issue by FlufferyGR** [obsproject/obs-studio#5771]
### Operating System Info

Other

### Other OS

Fedora Linux Workstation KDE

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/yRqOdXjpVFKai3Nt

### Expected Behavior

Audio Input and output should recieve but do not work

### Current Behavior

no audio 

### Steps to Reproduce

1. install obs using rpm fusion on website
2. open obs

**Comment by Fenrirthviti** [comment]
We are not currently accepting support requests on GitHub Issues, and this report does not have enough information to be actionable as a valid bug report. Additionally, we do not directly support the RPM Fusion package, so any issues will need to be reported to the maintainer if it is a package issue. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for further assistance.

Thank you!
