### ISSUE TITLE
GPU_PRIORITY_VAL are not defined in CI

### ISSUE THREAD

**Issue by NarryG** [obsproject/obs-studio#5775]
### Operating System Info

Other

### OBS Studio Version

Other

### OBS Studio Log URL

N/A

### Expected Behavior

CI builds of OBS should reflect the behavior of release builds for consistency purposes in testing 

In release builds, GPU_PRIORITY_VAL and USE_GPU_PRIORITY are defined. In CI, these are not defined.

Additionally, the intended value for GPU_PRIORITY_VAL doesn't appear to be documented or exist inside of the makefiles, leaving it a mystery as to what the defined value is in release builds, or potentially, that it's left at a default of 0 in release builds, resulting in no change to GPU Priority. 

### Current Behavior

CI Builds are created without the USE_GPU_PRIORITY flag, resulting in the GPU priority system not being available in the Windows CI builds. 

### Steps to Reproduce

N/A

**Comment by Fenrirthviti** [comment]
This is currently intentional.

**Comment by NarryG** [comment]
What is the logic behind this being disabled in CI builds if I might ask @Fenrirthviti?
I'm using it in my fork so if there's a reason it's disabled (e.g. an issue with the feature) I'd be interested in knowing

**Comment by mingjinglu** [comment]
@NarryG 
see also [https://bot-man-jl.github.io/articles/?post=2025/Reverse-Story-OBS](https://bot-man-jl.github.io/articles/?post=2025/Reverse-Story-OBS) #
