### ISSUE TITLE
Webcam video settings revert when unplugged

### ISSUE THREAD

**Issue by desmondw** [obsproject/obs-studio#5779]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/5X5aQ_HTE09wWovN

### Expected Behavior

Webcam setting maintain when the webcam is unplugged and plugged back in.

### Current Behavior

The webcam's video settings reset to default when the webcam is unplugged and plugged back in.

### Steps to Reproduce

1. Connect to webcam in sources
2. Modify video settings (zoom, tilt)
3. Exit OBS
4. Unplug webcam
5. Plug webcam back in
6. Open OBS
7. Note the webcam settings are reverted to default

### Anything else we should know?

I use a Logitech C920 for both my personal and work computers, which is connected via a USB/KVM switch. This disconnects the hardware from the computer when I toggle the switch. With this bug I have to reset the video settings for the webcam every workday at minimum, so essentially every time I stream.

There are workarounds with other webcam software (e.g. Logitech Capture) but they have their own deficits and I'd like to keep everything centralized in OBS.

**Comment by Pablomx2** [comment]
I've always had this issue and I believe it's because of the camera drivers themselves. I could be wrong tho.

**Comment by WizardCM** [comment]
This will likely be fixed in OBS 28.0. 

* #5480

**Comment by gxalpha** [comment]
As you may have noticed, the change got reverted in 28.0.1 as it cause issues with some capture cards. We're looking to reintroduce the functionality as soon as those issues are resolved.

However, we still consider this issue to be a feature request, for which we don't use GitHub Issue for tracking, so I'm going to close this issue. Please vote on https://ideas.obsproject.com/posts/345/save-metadata-for-video-capture-devices instead.
