### ISSUE TITLE
In the Docks of OBS 27.2, PNG images with transparency do not display correctly.

### ISSUE THREAD

**Issue by iesvme** [obsproject/obs-studio#5781]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.0 Beta 3

### OBS Studio Log URL

NIL

### Expected Behavior

Hopping OBS 27.2 can support the transparency of png in Docks.

### Current Behavior

In the Docks of OBS 27.2, PNG images with transparency do not display correctly.

### Steps to Reproduce

1. Custon Brower Docks
2. add PNG images with transparency in it
3. it doesn't support transparency 

### Anything else we should know?

but the OBS 27.1.3 support the transparency of png.

**Comment by WizardCM** [comment]
Are you adding an image file as a browser dock, or a webpage containing an image?

**Comment by WizardCM** [comment]
If this is what you're seeing, it is transparent - this is how Chrome renders images added directly to, so it's by design.

![image](https://user-images.githubusercontent.com/941350/149052306-2ff623ff-feb0-4f8a-b05d-be041eed9754.png)

**Comment by iesvme** [comment]
Yes, that's it. Thank you!
