### ISSUE TITLE
The Docks's background color doesn't match chrome's.

### ISSUE THREAD

**Issue by iesvme** [obsproject/obs-studio#5782]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.0 Beta 3

### OBS Studio Log URL

NIL

### Expected Behavior

Hopping Docks's background color is as the same as chrome's.

### Current Behavior

The Docks's background color doesn't match chrome's. The white color around doesn't look beautiful in OBS Docks.
![image](https://user-images.githubusercontent.com/16969250/149055314-5e58bdac-61d0-4aef-98cc-20c18c79e7af.png)
![image](https://user-images.githubusercontent.com/16969250/149055510-126da89d-9bc2-4957-acbf-016fbfb53583.png)

### Steps to Reproduce

1. Custom Brower Docks
2. add https://obs.ninja/?director=loveobs
3. the background-color is white in OBS, but the chrome background-color is black.

### Anything else we should know?

Chrome V97.0

**Comment by WizardCM** [comment]
This is not a bug or configuration issue on our side, but a purposeful piece of code in vdo.ninja. Source below.

https://github.com/steveseguin/vdo.ninja/blob/903e0910cdc5e83b913280e55293659d462844ce/main.js#L1438-L1440

aka "If we're running on OBS (even if it's a panel), remove the background"

**Comment by iesvme** [comment]
Thanks for your reply!
