### ISSUE TITLE
Random crashes while streaming/recording with Intel Iris Xe Graphics

### ISSUE THREAD

**Issue by b1scoito** [obsproject/obs-studio#5790]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/t6jiJ3LfEgtx_ltz

### OBS Studio Crash Log URL

https://obsproject.com/logs/uwY6O8jWx7gwdYEs

### Expected Behavior

Non-interrupted streaming/recording with no random crashes.

### Current Behavior

I get random crashes usually after 10-20 minutes of streaming/recording. Depending on the situation I crash minutes after starting streaming/recording.

### Steps to Reproduce

1. Start streaming/recording
2. Wait a bit
3. This is it.

### Anything else we should know?

I use a plugin called `win-capture-obs` but I'm almost certain that this isn't the cause of the crashes because it still used to happen before even I installed this plugin.

Happens with `CBR` too. Not only `CQP` or the other Intel's options.

**Comment by TomMettam** [comment]
Is this with the QuickSync h264 encoder?

**Comment by b1scoito** [comment]
Yes.

**Comment by TomMettam** [comment]
Tested for 2 hours, didn't run into any crashes, Intel Iris Xe i7-1165G7, Windows 11,  Driver version 30.0.101.1003

Could you screenshot your encoder settings? Also what resolution, framerate are you using?

**Comment by TomMettam** [comment]
(Also please try updating your display drivers, mine are newer)

**Comment by b1scoito** [comment]
![image](https://user-images.githubusercontent.com/17802984/149380381-fb51200f-d9b0-48f6-9f3f-027804421ab7.png)
![image](https://user-images.githubusercontent.com/17802984/149380412-9622ddd0-382f-4f3c-8d67-32512ce30f77.png)
![image](https://user-images.githubusercontent.com/17802984/149380435-cd5dfaf3-7127-4c80-97f6-3d158c8dbdb9.png)

My drivers are updated. Installed Windows less than a month ago.
Resolution `1600x900` and 60fps

**Comment by b1scoito** [comment]
I'm installing newer drivers from the website. Will test later

**Comment by TomMettam** [comment]
Yep, your log shows v28 but v30 is available :)

**Comment by Fenrirthviti** [comment]
Known crash that should be solved by updating drivers, closing this. If that does not fix the issue, stop by our support channels (forums or Discord) so we can take a closer look, we try to avoid support requests over GitHub, thanks!

https://obsproject.com
