### ISSUE TITLE
obs wayland screeb capture not working warning: [pipewire] Failed to start screencast, denied or cancelled by user

### ISSUE THREAD

**Issue by Bednar87** [obsproject/obs-studio#5794]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/kOlejKNWLiHMrIOz

### Expected Behavior

Screen capture on wayland should work with pipewire

### Current Behavior

I only get a black screen + the below in the log: warning: [pipewire] Failed to start screencast, denied or cancelled by user

I am not prompted by obs so select windows or screens to share; I certainly am not denying or cancelling anything

### Steps to Reproduce

1. Launch obs-studio
2. Add Screen Capture (pipewire) source
3. Black screen, no prompts, nothing
...

### Anything else we should know?

pipewire
Compiled with libpipewire 0.3.43
Linked with libpipewire 0.3.43

I have xdg-desktop-portal as well as the KDE implementations installed.

Operating System: Arch Linux
KDE Plasma Version: 5.23.90
KDE Frameworks Version: 5.90.0
Qt Version: 5.15.2
Kernel Version: 5.13.0-1-amd-staging-drm-next-git-01870-g8e74e0923ed4 (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 3700X 8-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 5700 XT

**Comment by Fenrirthviti** [comment]
The log provided shows `source: 'Screen Capture (XSHM)' (xshm_input)`

Can you provide a log file that shows you adding the source you are having issues with?

**Comment by Bednar87** [comment]
apologies, this log should be correct now https://obsproject.com/logs/LCc2DxGjq3Tf-SJh

**Comment by Bednar87** [comment]
I also see this in the journal:

`1/14/22 10:07 PM	xdg-desktop-portal-kde	QQmlApplicationEngine failed to load component
1/14/22 10:07 PM	xdg-desktop-portal-kde	qrc:/ScreenChooserDialog.qml:13:1: Type PWD.SystemDialog unavailable
1/14/22 10:07 PM	xdg-desktop-portal-kde	file:///usr/lib/qt/qml/org/kde/plasma/workspace/dialogs/SystemDialog.qml:132:9: MobileSystemDialog is not a type
1/14/22 10:07 PM	xdg-desktop-portal-kde	QObject::connect: Cannot connect (nullptr)::accept() to ScreenChooserDialog::accept()
1/14/22 10:07 PM	xdg-desktop-portal-kde	QObject::connect: Cannot connect (nullptr)::reject() to ScreenChooserDialog::reject()
1/14/22 10:07 PM	xdg-desktop-portal-kde	QObject::connect: Cannot connect (nullptr)::clearSelection() to ScreenChooserDialog::clearSelection()
1/14/22 10:07 PM	xdg-desktop-portal-kde	Failed to load dialog, cannot exec
`

and this:

`1/14/22 10:07 PM	pipewire	pw.node: (OBS-123) -> change driver (OBS-123 -> alsa_input.usb-Microsoft_Microsoft___LifeCam_Studio_TM_-02.mono-fallback-53)
1/14/22 10:07 PM	pipewire	pw.context: 0x55d3fa1e96c0: driver 0x55d3fa38e9d0: follower 0x55d3fb39ee20 OBS: active:1
1/14/22 10:07 PM	pipewire	pw.context: 0x55d3fa1e96c0: follower 0x55d3fb39ee20: active:1 'OBS'
1/14/22 10:07 PM	pipewire	pw.context: 0x55d3fa1e96c0: follower 0x55d3fa2e8b60: active:1 'OBS'
1/14/22 10:07 PM	pipewire	pw.node: (OBS-123) latency:0/0 -> 1200/48000
1/14/22 10:07 PM	pipewire	pw.context: 0x55d3fa1e96c0: driver 0x55d3fa38e9d0: follower 0x55d3fb39ee20 OBS: active:1
1/14/22 10:07 PM	pipewire	pw.context: 0x55d3fa1e96c0: follower 0x55d3fb39ee20: active:1 'OBS'
1/14/22 10:07 PM	pipewire	pw.context: 0x55d3fa1e96c0: follower 0x55d3fa2e8b60: active:1 'OBS'
1/14/22 10:07 PM	pipewire	pw.node: 0x55d3fb39ee20: (OBS) suspended -> running ((null))
1/14/22 10:07 PM	pipewire	pw.node: (OBS-123) suspended -> running
`

no idea if this is useful though

**Comment by kkartaltepe** [comment]
Your desktop-portal implementation is busted or incorrectly configured. Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum) for technical support.

**Comment by mthw0** [comment]
@Bednar87 Have you reported this to KDE? (https://bugs.kde.org/) I think I have this issue too, and I would report it if you didn't.

**Comment by Bednar87** [comment]
@mthw0  no, but I found an existing bug report: https://bugs.kde.org/show_bug.cgi?id=448423

I am rebuilding plasma-workspace with the proposed patch to see if it works

**Comment by mthw0** [comment]
I've found it too, downgrading xdg-desktop-portal-kde also fixes the issue.

**Comment by Bednar87** [comment]
this mr fixes the issue for me on arch linux 5.34 beta 

https://invent.kde.org/plasma/plasma-workspace/-/merge_requests/1368

**Comment by KronosTheLate** [comment]
I am also encountering this issue on a fresh debian install. It was working a few days ago without issues on linux mint cinnamon, same computer.

Is the reccomended workaround to downgrade `xdg-desktop-portal-kde`? If yes, downgrade to what version?

Also, given that [this linked MR](https://invent.kde.org/plasma/plasma-workspace/-/merge_requests/1368) is now merged, should this issue not be fixed?

**Comment by kkartaltepe** [comment]
As originally mentioned this is not the appropriate place to figure out how to configure xdg-desktop-portals you can use our support channels if you want help like that. And please do not necro old issues.
