### ISSUE TITLE
obs print a bogus timeout value: v4l2-input: /dev/video0: select timeout set to -9223372036854775808u

### ISSUE THREAD

**Issue by yurivict** [obsproject/obs-studio#5797]
### Operating System Info

Other

### Other OS

FreeBSD

### OBS Studio Version

27.1.3

### OBS Studio Log URL

x

### Expected Behavior

webcam works

### Current Behavior

prints bogus log line and fails to work with webcam

### Steps to Reproduce

The user reported the log [here](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=258694#c32) with the obviously bogus line from subject.

Webcam also doesn't work.

Camera: ```vendor-0x045e-USB-camera```

Please see details in the linked downstream bug report.

**Comment by RytoEX** [comment]
If the affected user is capable of compiling OBS, could they change `%ld` to `%llu` here?

https://github.com/obsproject/obs-studio/blob/27.1.3/plugins/linux-v4l2/v4l2-input.c#L180

That said, this should only fix the logged value.  The actual value should still be an unsigned long long.

**Comment by RytoEX** [comment]
Of more interest is this line in their log file:
> info: v4l2-input: Framerate: nan fps

If there's any information about what the camera settings were attempted to be set to, that may be helpful.

**Comment by yurivict** [comment]
How to get this information?

**Comment by RytoEX** [comment]
> How to get this information?

My system run Windows, so I don't know.  You could try asking the user?

Having said that, I've been keeping track of the downstream bug, and it looks like the user got the camera to be recognized.  Without more information, I'm guessing that invalid settings were previously applied to the camera.  Their remaining issue with the distorted OBS UI doesn't seem like an OBS bug to me.  However, I'll have to leave any further investigation and commentary to those more familiar with FreeBSD and v4l2.

**Comment by yurivict** [comment]
You should commit the above patch in the format statement.
The offending value came from some settings object. Not sure how could it be so off there.

About distortions: the user appears to use KDE. You need to see if any other KDE users ever reported the same issue.

**Comment by kkartaltepe** [comment]
> About distortions: the user appears to use KDE. You need to see if any other KDE users ever reported the same issue.

I have not seen any KDE reports of this or seen it myself in very limited testing on KDE. Unless someone reports it on linux my guess is its some subtle bug with the freebsd port or issue due to the versions of KDE and Qt on the users system. At least right now OBS's canvas render isnt perfectly synced with window resize so some minor size differences for 1-2 frames do occur, but not something totally broken like the user's experience.

**Comment by Marietto2008** [comment]
my webcam works great with your patch,but the distortions became worse.

you can give a look here : https://ibb.co/GF5vPXt

(im using xfce4).

anyway,the errors are still there :

ugen0.12: <Generic USB2.0 PC CAMERA> at usbus0, cfg=0 md=HOST spd=HIGH (480Mbps) pwr=ON (256mA)
root@marietto:/usr/ports/multimedia/obs-v4l2sink # service webcamd start
Starting webcamd.
webcamd 9271 - - Webcamd is already running for ugen0.12.0
root@marietto:/usr/ports/multimedia/obs-v4l2sink # obs
error: Could not create dbus connection: The connection is closed
error: Could not create dbus connection: The connection is closed
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/local/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/locale.ini
Attempted path: /usr/local/share/obs/obs-studio/locale.ini
Attempted path: share/obs/obs-studio/themes/Dark.qss
Attempted path: /usr/local/share/obs/obs-studio/themes/Dark.qss
info: CPU Name: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
info: CPU Speed: 3600.34MHz
info: Physical Cores: 8, Logical Cores: 16
info: Physical Memory: 31665MB Total, 27568MB Free
info: Kernel Version: FreeBSD 13.0-RELEASE
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.13
info: Portable mode: false
Attempted path: share/obs/obs-studio/themes/Dark/no_sources.svg
Attempted path: /usr/local/share/obs/obs-studio/themes/Dark/no_sources.svg
QMetaObject::connectSlotsByName: No matching signal for on_tbar_position_valueChanged(int)
QMetaObject::connectSlotsByName: No matching signal for on_actionShowTransitionProperties_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_actionHideTransitionProperties_triggered()
info: OBS 27.1.3 (freebsd)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
        samples per sec: 48000
        speakers:        2
info: ---------------------------------
info: Initializing OpenGL...
info: Loading up OpenGL on adapter Intel Mesa Intel(R) UHD Graphics 630 (CFL GT2)
info: OpenGL loaded successfully, version 4.6 (Core Profile) Mesa 21.3.4, shading language 4.60
info: ---------------------------------
info: video settings reset:
        base resolution:   1920x1080
        output resolution: 1280x720
        downscale filter:  Bicubic
        fps:               30/1
        format:            NV12
        YUV mode:          709/Partial
info: NV12 texture support not available
info: Audio monitoring device:
        name: Default
        id: default
info: ---------------------------------
warning: Failed to load 'en-US' text for module: 'decklink-captions.so'
warning: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
warning: v4l2loopback not installed, virtual camera disabled
info: FFMPEG VAAPI supported
info: [obs-ndi] hello ! (version 4.9.1)
info: [obs-ndi] Trying ''
info: [obs-ndi] Trying '/usr/lib'
info: [obs-ndi] Trying '/usr/local/lib'
error: [obs-ndi] Can't find the NDI library
warning: Failed to initialize module 'obs-ndi.so'
info: [obs-websocket] you can haz websockets (version 4.8.0)
info: [obs-websocket] qt version (compile-time): 5.15.2 ; qt version (run-time): 5.15.2
info: [obs-websocket] module loaded!
warning: Failed to load 'en-US' text for module: 'qtwebkit-browser.so'
info: VLC found, VLC video source enabled
info: ---------------------------------
info:   Loaded Modules:
info:     vlc-video.so
info:     v4l2sink.so
info:     text-freetype2.so
info:     sndio.so
info:     scrab.so
info:     rtmp-services.so
info:     qtwebkit-browser.so
info:     oss-audio.so
info:     obs-x264.so
info:     obs-websocket.so
info:     obs-vst.so
info:     obs-transitions.so
info:     obs-outputs.so
info:     obs-ndi.so
info:     obs-libfdk.so
info:     obs-filters.so
info:     obs-ffmpeg.so
info:     linux-v4l2.so
info:     linux-pulseaudio.so
info:     linux-jack.so
info:     linux-capture.so
info:     image-source.so
info:     frontend-tools.so
info:     decklink-ouput-ui.so
info:     decklink-captions.so
info: ---------------------------------
info: ==== Startup complete ===============================================
info: All scene data cleared
info: ------------------------------------------------
info: v4l2-input: Start capture from /dev/video0
info: v4l2-input: Input: 0
info: v4l2-input: Resolution: 640x480
info: v4l2-input: Pixelformat: YUYV
info: v4l2-input: Linesize: 1280 Bytes
info: v4l2-input: Framerate: 30.00 fps
info: v4l2-input: /dev/video0: select timeout set to 166666us (5x frame periods)
info: Switched to scene 'Scene'
info: ------------------------------------------------
info: Loaded scenes:
info: - scene 'Scene':
info:     - source: 'Video Capture Device (V4L2)' (v4l2_input)
info: ------------------------------------------------
error: v4l2-input: /dev/video0: select timed out
error: v4l2-input: /dev/video0: failed to log status
info: [obs-websocket] server started successfully on port 4444
info: [obs-websocket] io thread started
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 1074, resource id: 14881480, major code: 40 (TranslateCoords), minor code: 0
error: v4l2-input: /dev/video0: select timed out
error: v4l2-input: /dev/video0: failed to log status
Attempted path: share/obs/obs-studio/images/overflow.png
Attempted path: /usr/local/share/obs/obs-studio/images/overflow.png
error: v4l2-input: /dev/video0: select timed out
error: v4l2-input: /dev/video0: failed to log status
error: v4l2-input: /dev/video0: select timed out
error: v4l2-input: /dev/video0: failed to log status
error: v4l2-input: /dev/video0: select timed out
error: v4l2-input: /dev/video0: failed to log status
error: v4l2-input: /dev/video0: select timed out
error: v4l2-input: /dev/video0: failed to log status
error: v4l2-input: /dev/video0: select timed out
error: v4l2-input: /dev/video0: failed to log status
