### ISSUE TITLE
OBS won't use camera unless another program uses it first

### ISSUE THREAD

**Issue by d4hines** [obsproject/obs-studio#5805]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://gist.github.com/d4hines/88f78ae74b21674f5bb869a4c80a7b80

### Expected Behavior

OBS should use my webcam successfully on the first try

### Current Behavior

OBS shows a black box for the output of my webcam until I close OBS, Google Meet or another program that uses the camera, close that program and reopen OBS. Then the output of the camera is correct

### Steps to Reproduce

1. Reboot
2. Open OBS -> camera just shows a black box
3. Close OBS
4. Open Google Chrome, go to https://meet.google.com and start a new meeting to activate the camera -> camera works.
5. Close Chrome
6. Open OBS -> Camera works

### Anything else we should know?

In the attached logs, there are two files. The first is the log from the first load (unsuccessful). The second is the log from after running Chrome (successful).

I have the virtual camera provided by obs-v4l2sink set to autostart; however, I tried disabling this and got the same results from the reproduce steps.

**Comment by kkartaltepe** [comment]
We do not use GitHub Issues for support questions. Logs show things working as expected.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
