### ISSUE TITLE
OBS makes noise in a nonrecording mode under the certain circumstances

### ISSUE THREAD

**Issue by YuriiBatkovych** [obsproject/obs-studio#5806]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/fs6fgqa838xVe2cp

### Expected Behavior

The program will not make any sounds in a nonrecording mode

### Current Behavior

The program makes noise

### Steps to Reproduce

1. In the section Audio click on settings button
2. In the settings window choose an option "Advanced audio properties"
3. In the section Audio Monitoring choose an option "Monitor only (mute output)" for each device and click "Close"
4. Return to the main window
5. Try to say somrthing and notice the sound from OBS

**Comment by Fenrirthviti** [comment]
I'm not entirely sure what this report is saying. Are you just saying that the mixers are still moving? The mixers do not stop moving because you enable monitoring. Can you please clarify what the actual issue here is?

**Comment by flaeri** [comment]
they expect monitoring to not be active unless they have an output active.
Thats not the intended behavior of the monitoring in OBS.

At least thats how I interpret it based on their words and their logs.

**Comment by WizardCM** [comment]
This is intentional. An active output is not necessary for monitoring to function.
