### ISSUE TITLE
Any form of compression creates severe artifacts in local recording

### ISSUE THREAD

**Issue by runfalk** [obsproject/obs-studio#5811]
### Operating System Info

Other

### Other OS

Fedora 35

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/rD-ID5U8xRFVLl13

### Expected Behavior

I want to record my desktop and have a clean recording come out the other end. This is what text looks like when doing a lossless recording:

![lossless](https://user-images.githubusercontent.com/864128/149658651-f2d6191b-46cc-49e6-a52d-19bdc40dbb62.png)

### Current Behavior

I get weird artifacts that makes everything fuzzy.

![lossy](https://user-images.githubusercontent.com/864128/149658673-efbb17c0-2479-4e65-a023-7d4a6e9db097.png)

![lossy2](https://user-images.githubusercontent.com/864128/149658765-b29c5f29-6fbc-4249-9f3c-5ff2fd0a202e.png)

I've tried all kinds of bitrates and quality settings. They all look the same.

### Steps to Reproduce

1. Use any compresion settings when doing a local recording

### Anything else we should know?

* I record at my native resoluion (4K) so there should be no scaling.
* I am using the Flatpak version.

**Comment by fzwoch** [comment]
Please check with a different player. There is a bug out there where some hardware accelerated VLC playback will result in erroneous interlace artifacts.

See https://obsproject.com/forum/threads/horizontal-lines-glitch-when-recording-video-with-any-program.149458/

**Comment by runfalk** [comment]
Wow, you're right. I confirmed it by disabling hardware acceleration. Thanks a lot!
