### ISSUE TITLE
Beta 27.2 Show recordings opens VS Code

### ISSUE THREAD

**Issue by MIchael-Kelly7** [obsproject/obs-studio#5812]
### Operating System Info

Other

### Other OS

Manjaro Linux

### OBS Studio Version

27.2.0 Beta 3

### OBS Studio Log URL

https://obsproject.com/logs/i2125pOGNNCvwH2x

### Expected Behavior

Clicking File > Show recordings would open my file manager to appropriate directory.

### Current Behavior

Clicking File > Show Recordings launches VS Code (VS Codium in my case)

### Steps to Reproduce

1.Open OBS
2. Click File
3. Click Show Recordings
...

### Anything else we should know?

Not really sure how much of this is just something specific to my system. I have been using the current AUR package and it opened my recordings fine. This has only started happening in the flatpak.

**Comment by tytan652** [comment]
Not an issue with OBS, but with your system that chose VSCode as his default file explorer. Check your system settings (File association) to change it back to Dolphin.

**Comment by WizardCM** [comment]
Can't reproduce this on Ubuntu using the Flatpak. Sounds like a system misconfiguration.

**Comment by MIchael-Kelly7** [comment]
I have confirmed that my system default for file manager is Dolphin.

![image](https://user-images.githubusercontent.com/44328815/149668846-2ce4a298-9aed-4318-a565-10cefc0ccd30.png)

The other file menu options like show settings folder and show profile folder do the same thing.

If this is a system setting, why is 27.1.3 installed from pacman (standard arch repos) working as expected? This is only happening on the flatpak and I did confirm that nothing has changed for 27.1.3.

**Comment by tytan652** [comment]
Then maybe check `~/.config/mimeapps.list` in a text editor and remove VSCode where it should not be.
Note: `~` = `/home/"your username"`

**Comment by accuwau** [comment]
ive had this issue aswell, everything looked good in `~/.config/mimeapps.list` BUT if i look in `/usr/share/applications/mimeinfo.cache` vscode prepends itself to `inode/directory` moving `code.desktop;` to the very end of that line should fix it instantly
for example mine looks like this
`inode/directory=org.kde.dolphin.desktop;org.kde.kate.desktop;org.kde.kid3.desktop;rawtherapee.desktop;code.desktop;`
