### ISSUE TITLE
YouTube Chat Error

### ISSUE THREAD

**Issue by LOTIStream** [obsproject/obs-studio#5814]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/SunIK2ajMTszpURl

### Expected Behavior

I expected YouTube chat to continue loading in the chat window.

### Current Behavior

YouTube chat showed "Chat is currently unavailable"

### Steps to Reproduce

I have been unable to reproduce the issue, but I solved it by signing out of YouTube in OBS, and signing back in.  It created a new dockable window, which I just replaced the old one with.

**Comment by flaeri** [comment]
The YouTube chat window will say "unavailable" until you actually go live. This is expected.
I believe this is because the chat "instance" does not actually exist until you are live. Nothing we can do, as that's just how YouTube works.

**Comment by LOTIStream** [comment]
It actually did this across multiple streams.

**Comment by WizardCM** [comment]
That exact message usually means the chat itself failed to load from YouTube. Try right click -> Refresh. If that doesn't work, it's either a bug on YouTube's end, or for some reason OBS loaded the wrong chat URL.

**Comment by LOTIStream** [comment]
I tried right clicking and refreshing.  Somehow OBS seemed to loose contact
with that particular dockable container, as it created a new one, that’s
been working great since.

**Comment by Fenrirthviti** [comment]
This is not a bug, but just a misunderstanding on how YouTube chat works. If you had added a specific chat window manually, it would only work for that stream. Chat URLs are *stream* specific, not *channel* specific. So the chat changes every time you start a new stream. There is unfortunately not much we can do about it on our end.
