### ISSUE TITLE
OBS crashes when pasting enormously long text inside "Filename Formatting" box

### ISSUE THREAD

**Issue by verduttio** [obsproject/obs-studio#5815]
### Operating System Info

Windows 8.1

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/BHW-9GHVIfCxoQul

### OBS Studio Crash Log URL

https://obsproject.com/logs/77pE2QzcXEg6lQIJ

### Expected Behavior

Filename Formatting box cut the input if it is too long, and pastes only this cut part.

### Current Behavior

Filename Formatting box seems to accept all-length texts. So after pasting enormously long text in the box, OBS crashes.  

### Steps to Reproduce

1. Open OBS.
2. Click on Settings.
3. Click on Advanced.
4. Open any browser.
5. Go to a website https://wolnelektury.pl/media/book/txt/pan-tadeusz.txt 
6. Copy the whole text from the website by pressing Ctrl+a for instance and then Ctrl+c.
7. Go back to OBS.
8. Paste copied text inside "Filename Formatting" box by pressing Ctr+v for instance.
(9. OBS will crash after a few seconds.)

**Comment by kkartaltepe** [comment]
Please provide the crashlog for any crashes.

**Comment by verduttio** [comment]
> Please provide the crashlog for any crashes.

Just edited and added

**Comment by Vainock** [comment]
This has nothing to do with the length, rather the text itself:

```
    «Brawo! — rzekł Hrabia — plan twój, gotycko-sarmacki
Podoba się mi lepiej niż spór adwokacki.
Wiesz co? na całej Litwie narobim hałasu
Wyprawą niesłychaną od dawnego czasu.
I sami się zabawim. Dwa lata tu siedzę,
Jakąż bitwę widziałem? z chłopami o miedzę!
Nasza wyprawa przecież krwi rozlanie wróży.
Odbyłem taką jedną w czasie mych podróży.
Gdym w Sycylii bawił u pewnego księcia,
Rozbójnicy porwali w górach jego zięcia,
I okupu od krewnych żądali zuchwale;
My, zebrawszy naprędce sługi i wasale,
Wpadliśmy; ja dwóch zbójców ręką mą zabiłem,
Pierwszy wleciałem w tabor, więźnia uwolniłem.
Ach, mój Gerwazy! jaki to był tryumfalny,
Jaki piękny nasz powrót, rycersko-feudalny!
Lud z kwiatami spotykał nas; córka książęcia,
Wdzięczna zbawcy, ze łzami padła w me objęcia.
Gdym przybył do Palermo, wiedziano z gazety,
Palcami wskazywały mię wszystkie kobiety;
Nawet wydrukowano o całym zdarzeniu
Romans, gdzie wymieniony jestem po imieniu.
```
causes the same crash. Currently figuiring out what the 'bad characters' are.

**Comment by verduttio** [comment]
> I just took
> 
> ```
>     «Brawo! — rzekł Hrabia — plan twój, gotycko-sarmacki
> Podoba się mi lepiej niż spór adwokacki.
> Wiesz co? na całej Litwie narobim hałasu
> Wyprawą niesłychaną od dawnego czasu.
> I sami się zabawim. Dwa lata tu siedzę,
> Jakąż bitwę widziałem? z chłopami o miedzę!
> Nasza wyprawa przecież krwi rozlanie wróży.
> Odbyłem taką jedną w czasie mych podróży.
> Gdym w Sycylii bawił u pewnego księcia,
> Rozbójnicy porwali w górach jego zięcia,
> I okupu od krewnych żądali zuchwale;
> My, zebrawszy naprędce sługi i wasale,
> Wpadliśmy; ja dwóch zbójców ręką mą zabiłem,
> Pierwszy wleciałem w tabor, więźnia uwolniłem.
> Ach, mój Gerwazy! jaki to był tryumfalny,
> Jaki piękny nasz powrót, rycersko-feudalny!
> Lud z kwiatami spotykał nas; córka książęcia,
> Wdzięczna zbawcy, ze łzami padła w me objęcia.
> Gdym przybył do Palermo, wiedziano z gazety,
> Palcami wskazywały mię wszystkie kobiety;
> Nawet wydrukowano o całym zdarzeniu
> Romans, gdzie wymieniony jestem po imieniu.
> ```
> 
> from your example and it causes the same crash.

Agree, so copying the whole text was a quite too powerful example, just one paragraph can be sufficient to crash OBS
