### ISSUE TITLE
4:2:0 camera is being treated as 4:2:2 (No auto  detection) in Motion JPEG

### ISSUE THREAD

**Issue by fbievan** [obsproject/obs-studio#5821]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

Git

### OBS Studio Log URL

https://obsproject.com/logs/tU1WEc26GRSSFL4l

### Expected Behavior

Clean video, v4l2 
https://www.youtube.com/watch?v=VlyNBIg4goQ&feature=youtu.be
qv4l2 works fine

### Current Behavior

https://www.youtube.com/watch?v=VqWTLZN6VgI
Glitching

### Steps to Reproduce

1. Load up  camera
2. Pick mjpeg
3. Select any resolution
...

### Anything else we should know?

To me it seems to be with avcodec or the implementation of avcodec for decoding mjpeg. Testing qv4l2 to display an image, it works fine this program atleast from what I can tell it's own decoder to decode mjpeg.

Edit:
Camera model: avermedia pw513

This is the only camera that acts up that I have.
Does not work properly in guvcview
Works in qv4l2 though.

**Comment by RytoEX** [comment]
What is the camera manufacturer and model?

**Comment by fbievan** [comment]
Avermedia camera manfacutor
Avermedia pw513

**Comment by fbievan** [comment]
_can_ record it in   4k30 mjpeg in ffmpeg, i should be able to in obs too. Not sure whats going on here

**Comment by fbievan** [comment]
Specifically on this camera, but still doesn't explain why/how other applications pull it fine.

**Comment by fbievan** [comment]
> What is the camera manufacturer and model?

I edited it with more information, figured the only way I'll get any help or anything is if I don't add something everyday. From now on, I'll add anything requested and anything I think anyone helping me will need. I sincerely apologize, for kind of being a bit spammy

**Comment by fbievan** [comment]
Every Avenue I've gone down to try and fix this. All dead ends, not sure what to do now.

**Comment by fbievan** [comment]
I've basically worked around this by using a plugin,  named [obs-gstreamer](https://github.com/fzwoch/obs-gstreamer), but this is not optimal, for anyone interested  here is the config 
![image](https://user-images.githubusercontent.com/17110707/151251336-a2d2318d-d741-4bc4-a8aa-2864938490d7.png)

Not closing, as the orginal issue persists

**Comment by marvin0815** [comment]
I've seen this before, It might be an avcodec (ffmpeg) issue where linux-v4l2.so is linked against. You could do the countercheck and change your GST pipeline to `v4lsrc ... ! queue ! avdec_mjpeg ! video.`. If libgstjpeg.so is linked against the same avcodec library, you should see the same issue. If so, it's not an OBS issue then.

**Comment by fbievan** [comment]
> I've seen this before, It might be an avcodec (ffmpeg) issue where linux-v4l2.so is linked against. You could do the countercheck and change your GST pipeline to `v4lsrc ... ! queue ! avdec_mjpeg ! video.`. If libgstjpeg.so is linked against the same avcodec library, you should see the same issue. If so, it's not an OBS issue then.

I will definitely try later today. I'll get back with the results

**Comment by fbievan** [comment]
> I've seen this before, It might be an avcodec (ffmpeg) issue where linux-v4l2.so is linked against. You could do the countercheck and change your GST pipeline to `v4lsrc ... ! queue ! avdec_mjpeg ! video.`. If libgstjpeg.so is linked against the same avcodec library, you should see the same issue. If so, it's not an OBS issue then.
![image](https://user-images.githubusercontent.com/17110707/153292276-2dcc5f08-a1e1-4e36-af9e-d50aeaa171b6.png)
I checked and well, using avdec_mjpeg produces this

**Comment by fbievan** [comment]
> I've seen this before, It might be an avcodec (ffmpeg) issue where linux-v4l2.so is linked against. You could do the countercheck and change your GST pipeline to `v4lsrc ... ! queue ! avdec_mjpeg ! video.`. If libgstjpeg.so is linked against the same avcodec library, you should see the same issue. If so, it's not an OBS issue then.

![image](https://user-images.githubusercontent.com/17110707/153292276-2dcc5f08-a1e1-4e36-af9e-d50aeaa171b6.png)

avdec_mjpeg produces that so

**Comment by fbievan** [comment]
Heres a cool note, 
![image](https://user-images.githubusercontent.com/17110707/153679545-af755fc6-d789-409b-8136-e34081934ba0.png)
ffmpeg pulls up this for recording that camera
however other cameras which arent afected by this pull up 
![image](https://user-images.githubusercontent.com/17110707/153679619-4ea52091-f26e-4506-b79a-7c4ef2fec071.png)

**Comment by fzwoch** [comment]
```c
	case V4L2_PIX_FMT_MJPEG:
		return VIDEO_FORMAT_I422;
```
Looks like the plugin expects a hard coded 4:2:2 format as output format after MJPEG decoding, but this particular camera returns 4:2:0.

**Comment by fbievan** [comment]
> ```c
> 
> 	case V4L2_PIX_FMT_MJPEG:
> 
> 		return VIDEO_FORMAT_I422;
> 
> ```
> 
> Looks like the plugin expects a hard coded 4:2:2 format as output format after MJPEG decoding, but this particular camera returns 4:2:0.
> 
> 

That makes sense looking at the logs I posted.

**Comment by fzwoch** [comment]
Maybe something like this will help. I have no idea if that's the correct idea though.

```diff
diff --git a/plugins/linux-v4l2/v4l2-mjpeg.c b/plugins/linux-v4l2/v4l2-mjpeg.c
index 45b2b9193..7b92d1053 100644
--- a/plugins/linux-v4l2/v4l2-mjpeg.c
+++ b/plugins/linux-v4l2/v4l2-mjpeg.c
@@ -45,7 +45,7 @@ int v4l2_init_mjpeg(struct v4l2_mjpeg_decoder *decoder)
        }
 
        decoder->context->flags2 |= AV_CODEC_FLAG2_FAST;
-       decoder->context->pix_fmt = AV_PIX_FMT_YUVJ422P;
+       decoder->context->pix_fmt = AV_PIX_FMT_NONE;
 
        if (avcodec_open2(decoder->context, decoder->codec, NULL) < 0) {
                blog(LOG_ERROR, "failed to open codec");
@@ -94,5 +94,20 @@ int v4l2_decode_mjpeg(struct obs_source_frame *out, uint8_t *data,
                out->linesize[i] = decoder->frame->linesize[i];
        }
 
+       switch (decoder->context->pix_fmt) {
+               case AV_PIX_FMT_YUVJ422P:
+               case AV_PIX_FMT_YUV422P:
+                       out->format = VIDEO_FORMAT_I422;
+                       break;
+               case AV_PIX_FMT_YUVJ420P:
+               case AV_PIX_FMT_YUV420P:
+                       out->format =  VIDEO_FORMAT_I420;
+                       break;
+               case AV_PIX_FMT_YUVJ444P:
+               case AV_PIX_FMT_YUV444P:
+                       out->format =  VIDEO_FORMAT_I444;
+                       break;
+       }
+
        return 0;
 }
```

**Comment by fbievan** [comment]
> Maybe something like this will help. I have no idea if that's the correct idea though.
> 
> 
> 
> ```diff
> 
> diff --git a/plugins/linux-v4l2/v4l2-mjpeg.c b/plugins/linux-v4l2/v4l2-mjpeg.c
> 
> index 45b2b9193..7b92d1053 100644
> 
> --- a/plugins/linux-v4l2/v4l2-mjpeg.c
> 
> +++ b/plugins/linux-v4l2/v4l2-mjpeg.c
> 
> @@ -45,7 +45,7 @@ int v4l2_init_mjpeg(struct v4l2_mjpeg_decoder *decoder)
> 
>         }
> 
>  
> 
>         decoder->context->flags2 |= AV_CODEC_FLAG2_FAST;
> 
> -       decoder->context->pix_fmt = AV_PIX_FMT_YUVJ422P;
> 
> +       decoder->context->pix_fmt = AV_PIX_FMT_NONE;
> 
>  
> 
>         if (avcodec_open2(decoder->context, decoder->codec, NULL) < 0) {
> 
>                 blog(LOG_ERROR, "failed to open codec");
> 
> @@ -94,5 +94,20 @@ int v4l2_decode_mjpeg(struct obs_source_frame *out, uint8_t *data,
> 
>                 out->linesize[i] = decoder->frame->linesize[i];
> 
>         }
> 
>  
> 
> +       switch (decoder->context->pix_fmt) {
> 
> +               case AV_PIX_FMT_YUVJ422P:
> 
> +               case AV_PIX_FMT_YUV422P:
> 
> +                       out->format = VIDEO_FORMAT_I422;
> 
> +                       break;
> 
> +               case AV_PIX_FMT_YUVJ420P:
> 
> +               case AV_PIX_FMT_YUV420P:
> 
> +                       out->format =  VIDEO_FORMAT_I420;
> 
> +                       break;
> 
> +               case AV_PIX_FMT_YUVJ444P:
> 
> +               case AV_PIX_FMT_YUV444P:
> 
> +                       out->format =  VIDEO_FORMAT_I444;
> 
> +                       break;
> 
> +       }
> 
> +
> 
>         return 0;
> 
>  }
> 
> ```

I'm just test to see if this is indeed the issue, hard coding it to use i420, and the respective yuvj counterpart. And see what happens. ( I have little knowledge of c, but I know how to read so )

**Comment by fbievan** [comment]
it is offical, that is the issue. hard coding it to I420 WORKS. HOLY LORD, WE HAVE AN ACTUAL ISSUE THAT WE CAN FIX. 2 lines changed boom ( this is changing I422, to I420 in both the  v4l2-helpers.h and v4l2-jpeg.c

**Comment by kkartaltepe** [comment]
> Maybe something like this will help. I have no idea if that's the correct idea though.
> 
> ```diff
> diff --git a/plugins/linux-v4l2/v4l2-mjpeg.c b/plugins/linux-v4l2/v4l2-mjpeg.c
> index 45b2b9193..7b92d1053 100644
> --- a/plugins/linux-v4l2/v4l2-mjpeg.c
> +++ b/plugins/linux-v4l2/v4l2-mjpeg.c
> @@ -45,7 +45,7 @@ int v4l2_init_mjpeg(struct v4l2_mjpeg_decoder *decoder)
>         }
>  
>         decoder->context->flags2 |= AV_CODEC_FLAG2_FAST;
> -       decoder->context->pix_fmt = AV_PIX_FMT_YUVJ422P;
> +       decoder->context->pix_fmt = AV_PIX_FMT_NONE;
>  
>         if (avcodec_open2(decoder->context, decoder->codec, NULL) < 0) {
>                 blog(LOG_ERROR, "failed to open codec");
> @@ -94,5 +94,20 @@ int v4l2_decode_mjpeg(struct obs_source_frame *out, uint8_t *data,
>                 out->linesize[i] = decoder->frame->linesize[i];
>         }
>  
> +       switch (decoder->context->pix_fmt) {
> +               case AV_PIX_FMT_YUVJ422P:
> +               case AV_PIX_FMT_YUV422P:
> +                       out->format = VIDEO_FORMAT_I422;
> +                       break;
> +               case AV_PIX_FMT_YUVJ420P:
> +               case AV_PIX_FMT_YUV420P:
> +                       out->format =  VIDEO_FORMAT_I420;
> +                       break;
> +               case AV_PIX_FMT_YUVJ444P:
> +               case AV_PIX_FMT_YUV444P:
> +                       out->format =  VIDEO_FORMAT_I444;
> +                       break;
> +       }
> +
>         return 0;
>  }
> ```

Thanks for the patch I have put up a PR that cleans this up a bit to avoid the mistaken format conversion everywhere.
