### ISSUE TITLE
[Crash] Closing OBS while having an active Decklink Output

### ISSUE THREAD

**Issue by lindenkron** [obsproject/obs-studio#5832]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/EyGorWuXlARMNGUm

### OBS Studio Crash Log URL

https://obsproject.com/logs/Ar7YSJa5sPwyIDfE

### Expected Behavior

Not to crash.

### Current Behavior

Crashes.

### Steps to Reproduce

1. Tools > Decklink Output
2. Select Device (DeckLink SDI 4k)
3. Press 'Start' under the 'Output' setting
4. Close OBS.

### Anything else we should know?

Also got this crash on encoder PC when simply pressing the "Start" button on Decklink output. May be unrelated.
https://obsproject.com/logs/oFw3TDouwRZKGC1Q

**Comment by lindenkron** [comment]
https://github.com/obsproject/obs-studio/issues/5831

**Comment by RytoEX** [comment]
Could you please explain why you reopened this?

**Comment by lindenkron** [comment]
https://github.com/obsproject/obs-studio/issues/5831#issuecomment-1018114413

**Comment by RytoEX** [comment]
In the future, please provide context for closing/reopening Issues within the Issue itself, even if you have to duplicate some text from another related Issue.

**Comment by lindenkron** [comment]
Apologies, I just forgot to open it with the other post.

**Comment by paulh-aja** [comment]
I think this might be the same as https://github.com/obsproject/obs-studio/pull/5891
