### ISSUE TITLE
OBS Studio record black screen only

### ISSUE THREAD

**Issue by Andrej123456789** [obsproject/obs-studio#5836]
### Operating System Info

Other

### Other OS

Ubuntu 21.10

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/7zV4yUHYtBz-wDiD

### Expected Behavior

I want to record by entire screen.

### Current Behavior

Video is just black screen with mouse

### Steps to Reproduce

1. Installed OBS Studio
2. Shutdown computer after day
3. Open computer, enter Ubuntu and OBS don't want to record my screen properly. I tried to reinstall it but nothing.
...

### Anything else we should know?

![image](https://user-images.githubusercontent.com/83548580/150485347-fa4a9eb4-2957-4ae6-8ff0-877c3ffcb62d.png)

**Comment by WizardCM** [comment]
This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels below, and if it's determined that this is indeed a bug, then we will re-open this issue.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
