### ISSUE TITLE
Display capture is lagging while window capture works smooth

### ISSUE THREAD

**Issue by m0ney-dev** [obsproject/obs-studio#5837]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/iq8oyKb36NJEKn9r

### Expected Behavior

Smooth video

### Current Behavior

Display capture is lagging behind by a lot, i think at 1-5fps - check video https://vimeo.com/668571844

### Steps to Reproduce

1. Turn on display capture
2.
3.
...

### Anything else we should know?

Video of issue: https://vimeo.com/668571844

**Comment by WizardCM** [comment]
This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels below, and if it's determined that this is indeed a bug, then we will re-open this issue.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
