### ISSUE TITLE
obs virtual camera not showing on browser

### ISSUE THREAD

**Issue by ArchitJain007** [obsproject/obs-studio#5839]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

not understand.

### Expected Behavior

After installing obs studio and obs virtual camera, I open obs studio app and enable virtual camera from tools menu then I start virtual camera from control section. Then I open my browser (chrome) and try to change the web cam in settings area but obs virtual camera is not showing their...
Then I open 2 other browsers {firefox and brave} but their also the same problem that virtual web cam isn't showing...

### Current Behavior

same

### Steps to Reproduce

 This is from starting....

### Anything else we should know?

How can I treat this problem?

**Comment by Fenrirthviti** [comment]
We are not currently accepting support requests on GitHub Issues, and this sounds more like a support request than an actual bug report. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for further assistance.

Thank you!
