### ISSUE TITLE
Centering several sources produces a desync with undo/redo

### ISSUE THREAD

**Issue by VodBox** [obsproject/obs-studio#5844]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.0 Beta 3

### OBS Studio Log URL

https://obsproject.com/logs/eQP8qotbbklz60Aj

### Expected Behavior

After centering a lot of sources, hitting undo should return all those sources to the positions they had before centering.

### Current Behavior

The bottom most selected source has all the transforms of the sources before the centering applied to it sequentially, while the other sources remain centered.

### Steps to Reproduce

1. Create a scene with multiple sources which are not centered.
2. Use Ctrl/Cmd + D to center, or Right Click > Transform > Center to Screen.
3. Use Ctrl/Cmd + Z or Edit > Undo.

**Comment by CodyJung** [comment]
I was looking at another source transform undo issue recently, so I thought I'd take a stab at this one. I've tried selecting all in the source list for a scene and hitting Ctrl-D, and that seems to undo fine. Any suggestions on specific things that might be different about your setup?

**Comment by VodBox** [comment]
It appears this bug is only happening in a specific collection I have, and not generally. Will reopen once I determine what happened with this collection to produce the bug that doesn't happen in normal operation.
