### ISSUE TITLE
OSB Studio & VLC Plugin - MediaPlayerEncounteredError

### ISSUE THREAD

**Issue by sweetngx** [obsproject/obs-studio#5847]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.0 Beta 3

### OBS Studio Log URL

None

### Expected Behavior

None

### Current Behavior

I'm using the VLC Player plugin for OBS Studio, But I noticed that if you have a playlist and it only consists of video files, the loop feature works, because when a video is finished the `libvlc_MediaPlayerStopped `event forces it to switch to the next video. But this is not possible in live streams, because in any interruption or resource error in live streams, the `libvlc_MediaPlayerEncounteredError `event is triggered, not the stop event.

So I did some work on the VLC Plugin and added the `libvlc_MediaPlayerEncounteredError `event and realized that it was triggered by a potential problem in live streams, as I guessed.

But the problem starts after that... `libvlc_media_list_player_next_(c->media_list_player);` I added and recompiled the codes. OBS freezes and hangs when switching to the next video when there is a problem with the stream... I can't find the cause and I need help

```
libvlc_event_attach_(event_manager, libvlc_MediaPlayerEncounteredError, vlcs_error, c);

static void vlcs_error(const struct libvlc_event_t *event, void *data)
{
    MessageBox(NULL, L"Stream Down!", L"Title", MB_ICONINFORMATION);

    struct vlc_source *c = data;

    libvlc_media_list_player_next_(c->media_list_player);
    

    UNUSED_PARAMETER(event);
}
```

### Steps to Reproduce

1.
2.
3.
...

**Comment by WizardCM** [comment]
Could you provide a proper diff for your changes?

**Comment by gxalpha** [comment]
No reply in over 10 months.

**Comment by saning18888-hue** [comment]
> ### Operating System Info
> Windows 10
> 
> ### Other OS
> _No response_
> 
> ### OBS Studio Version
> 27.2.0 Beta 3
> 
> ### OBS Studio Version (Other)
> _No response_
> 
> ### OBS Studio Log URL
> None
> 
> ### OBS Studio Crash Log URL
> _No response_
> 
> ### Expected Behavior
> None
> 
> ### Current Behavior
> I'm using the VLC Player plugin for OBS Studio, But I noticed that if you have a playlist and it only consists of video files, the loop feature works, because when a video is finished the `libvlc_MediaPlayerStopped `event forces it to switch to the next video. But this is not possible in live streams, because in any interruption or resource error in live streams, the `libvlc_MediaPlayerEncounteredError `event is triggered, not the stop event.
> 
> So I did some work on the VLC Plugin and added the `libvlc_MediaPlayerEncounteredError `event and realized that it was triggered by a potential problem in live streams, as I guessed.
> 
> But the problem starts after that... `libvlc_media_list_player_next_(c->media_list_player);` I added and recompiled the codes. OBS freezes and hangs when switching to the next video when there is a problem with the stream... I can't find the cause and I need help
> 
> ```
> libvlc_event_attach_(event_manager, libvlc_MediaPlayerEncounteredError, vlcs_error, c);
> 
> static void vlcs_error(const struct libvlc_event_t *event, void *data)
> {
>     MessageBox(NULL, L"Stream Down!", L"Title", MB_ICONINFORMATION);
> 
>     struct vlc_source *c = data;
> 
>     libvlc_media_list_player_next_(c->media_list_player);
>     
> 
>     UNUSED_PARAMETER(event);
> }
> ```
> 
> ### Steps to Reproduce
> 
> ...
> 
> ### Anything else we should know?
> _No response_
