### ISSUE TITLE
Blank Screen with a cursor in Pipewire Screen/Window Capture [Plasma Wayland + NVIDIA].

### ISSUE THREAD

**Issue by SamPingu** [obsproject/obs-studio#5850]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.2.0.beta3.r49.gb2360b433

### OBS Studio Log URL

https://obsproject.com/logs/WNEvqoGWBwRCeSVf

### Expected Behavior

OBS Pipewire Screen/Window Capture must capture the allowed screen/window instead of just showing a black screen with a cursor.

### Current Behavior

When I have Pipewire Screen/Window Capture as Source, the xdg-portal asks for permission but the permitted screen/window doesnt show up but only a black screen with a moving cursor.

### Steps to Reproduce

1. Log-in to Plasma Wayland session with NVIDIA Proprietary Drivers (495) + latest qt5-wayland having NVIDIA GBM patch.
2. Open OBS Studio.
3. Add Pipewire Screen/Window Capture as Source and select the screen/window to be recorded.
4. See a blank screen with just mouse cursor.

### Anything else we should know?

I am using latest NVIDIA stable proprietary driver 495.46 in Plasma 5.23.90 (downgraded xdg-desktop-portal-kde to 5.23.5 because the 5.23.90 one is broken. Downgrading Plasma entirely to 5.23.5 also results in the same issue) with the latest qt5-wayland from repo which has qt fix for NVIDIA.

Log File attached.
[2022-01-23 13-02-27.txt](https://github.com/obsproject/obs-studio/files/7920013/2022-01-23.13-02-27.txt)

**Comment by kkartaltepe** [comment]
There are just too many possible issues here, unless  you can report something else successfully using the xdg-desktop-portal working im going to close this as a likely kde bug. If you can provide an example of something else working we can reopen this.

**Comment by Bleuzen** [comment]
Also happens with other apps, this is a bug of xdg-desktop-portal-kde, see:
https://bugs.kde.org/show_bug.cgi?id=448944

**Comment by SamPingu** [comment]
> Also happens with other apps, this is a bug of xdg-desktop-portal-kde/kwin, see: https://bugs.kde.org/show_bug.cgi?id=448944

Thanks for letting me know. Following the bug report there.
