### ISSUE TITLE
27.2 beta4 crash when applying settings

### ISSUE THREAD

**Issue by iesvme** [obsproject/obs-studio#5854]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.0 Beta 4

### OBS Studio Log URL

https://obsproject.com/logs/U69kfu9kmcTHFrgA

### Expected Behavior

Do not crash.

### Current Behavior

27.2 beta4 crash when applying settings

### Steps to Reproduce

1. open settings
2. click "keep recording when stream stops"
3. apply
4. crash

**Comment by WizardCM** [comment]
I cannot reproduce this crash on a clean Beta 4 installation. Please include the crash log.

**Comment by iesvme** [comment]
https://obsproject.com/logs/btvXpmfA9g3oF1YI

**Comment by WizardCM** [comment]
Hmm. Did you change any other settings when you changed that one?

Also, it seems OBS was blocked from properly fetching the list of antivirus applications you have running. Try temporarily disabling your antivirus to see if the crash goes away.

**Comment by iesvme** [comment]
Now I quit all background programs, including antivirus software. But the problem is still there. I just open settings, check a random option, press apply, and the program crashes.

**Comment by WizardCM** [comment]
Ah, I bet I know why. Because you're running an old version of Windows 10 (1809, you should really update), `hideOBSFromCapture` is deleted but it tries to save it anyway.

**Comment by iesvme** [comment]
Oh, that's it. Thank you!

**Comment by WizardCM** [comment]
Definitely reproduced it on Windows 10 1607. Thanks for the report!

**Comment by iesvme** [comment]
My pleasure!
