### ISSUE TITLE
NVIDIA Noise Removal used to work on unsupported GPU until explicit GPU check was added

### ISSUE THREAD

**Issue by Peksa** [obsproject/obs-studio#5858]
### Operating System Info

Windows 11

### OBS Studio Version (Other)

27.0.0

### OBS Studio Log URL

https://obsproject.com/logs/gnka9blB2MjnnR23

### Expected Behavior

Using OBS 27.0.0.RC6 and the latest NVIDIA Audio Effects SDK 1.0.5.11 (for Turing) I can successfully use the NVIDIA Noise Removal Filter in OBS using an unsupported GTX 1080 card, **even** though the log file shows:
`[noise suppress: 'Noise Suppression (NVIDIA)'] NvAFX_CreateEffect() failed, error 11`

![image](https://user-images.githubusercontent.com/903976/150855251-d70009cd-196c-4f23-bc65-d6f904c0ae40.png)

I verified that the filter actually has effect AND is different from both the other two Noise removal methods; Speex and RNNoise

Log file for `27.0.0.RC6`:
https://obsproject.com/logs/5MQmxXz50hZPNtkz

### Current Behavior

In OBS 27.0.0 the filter is greyed out, and the log file shows:
`[noise suppress: Nvidia RTX denoiser disabled: unsupported GPU]`

![image](https://user-images.githubusercontent.com/903976/150855361-4cda5302-ad38-4969-a39a-d26e13fc473b.png)

Log file for `27.0.0`:
https://obsproject.com/logs/gnka9blB2MjnnR23

### Steps to Reproduce

1. Use an unsupported NVIDIA GPU (tested with a GTX 1080)
2. Download the latest NVIDIA Audio Effects SDK **for Turing** from https://www.nvidia.com/sv-se/geforce/broadcasting/broadcast-sdk/resources/ (tested with 1.0.5.11)
2. Run OBS version 27.0.0 or greater
3. Add a Noise Suppression filter to an Audio source
4. Confirm that the Method `NVIDIA Noise Removal` is greyed out and unselectable.
5. Repeat with OBS 27.0.0.RC6 and confirm that the filter is selectable and functional.

### Anything else we should know?

After confirming the solution from the forum post [here](https://obsproject.com/forum/resources/use-nvidia-rtx-voice-noise-removal-with-geforce-gtx-1000-1600-series-cards-on-windows-7-8-8-1-10.1233/) actually worked, I was curious why this had stopped working with newer versions of OBS, which caused me to investigate this.

Somehow some/enough parts of the NVIDIA SDK still work for a GTX 1080 card, even if the SDK reports that the GPU is unsupported during `NvAFX_CreateEffect(NVAFX_EFFECT_DENOISER)`. I suspect this commit https://github.com/obsproject/obs-studio/commit/c5bb1278f4dee866a2aed12d82f2a8e5cec0c639 then caused a regression for my (admittedly unsupported) use-case.

**Comment by Fenrirthviti** [comment]
Are you able to test on latest release with that specific commit reverted? I also don't really know if this is something we should be supporting, as we're trusting the SDK for the capabilities test. I'm also a little surprised that guide was approved on our forums encouraging using old and outdated drivers/OBS versions.

**Comment by Peksa** [comment]
I am not (easily) able to build from source, but I'd happily test a build if that could help. I have no strong opinions on how/if this could/should be supported, but it seems the SDK (at least the current version) works on at least my GPU, and that the current capability test is not truthful.

**Comment by pkviet** [comment]
Our nvidia contacts told us non RTX GPUs would be supported eventually in an official manner in the future (no idea about the timetable though). RTX are needed for improving the AI models (so they told me).

**Comment by notr1ch** [comment]
`[noise suppress: 'Noise Suppression (NVIDIA)'] NvAFX_CreateEffect() failed, error 11` means unsupported GPU. If you got this error on an old version of OBS, NVAFX would not be initialized further,  and the filter falls back to using Speex. So if you want to reproduce this in the newest version of OBS, simply select Speex from the filter methods directly.

**Comment by Peksa** [comment]
> `[noise suppress: 'Noise Suppression (NVIDIA)'] NvAFX_CreateEffect() failed, error 11` means unsupported GPU. If you got this error on an old version of OBS, NVAFX would not be initialized further, and the filter falls back to using Speex. So if you want to reproduce this in the newest version of OBS, simply select Speex from the filter methods directly.

I was concerned something like this was happening, during my subjective recording they sounded different.

However, I just re-did my tests comparing just Speex and NVIDIA Noise Removal I'm ashamed to confirm that they do in fact sound the same - my fault!

Sorry, but thank you all for the quick responses!

**Comment by Peksa** [comment]
(I can also confirm that using the specific versions from the forum post - an older nightly OBS 26.1.2 and NVIDIA Audio Effects SDK 0.5.4 leads to exactly the same thing on my machine - `[noise suppress: 'Noise Suppression (NVIDIA)'] NvAFX_CreateEffect() failed, error 11` in the logfile, and it sounds the same as Speex.)
