### ISSUE TITLE
OBS Studio Crashes When Opening After Mac Install

### ISSUE THREAD

**Issue by Bobdibildur123** [obsproject/obs-studio#5859]
### Operating System Info

macOS 11.5

### OBS Studio Version

27.1.3

### OBS Studio Log URL

It didn't open so I don't have a log

### Expected Behavior

I expected OBS to install normally to my Mac without issues

### Current Behavior

When I open the app after installation it opens but comes up with the error message "“OBS” is damaged and can’t be opened. You should move it to the Bin." When I click move to bin it says it couldn't move to bin but when I go back to applications the app has uninstalled itself.

### Steps to Reproduce

1. Download the mac installer from https://obsproject.com/download.
2. Open the installer and drag the file inside the installer to applications.
3. From applications open the obs studio applications and the error message should appear.
...

### Anything else we should know?

I tried this on multiple versions from your GitHub but they all failed to work

**Comment by FTL1** [comment]
I have the same problem. This occurs with the prior version (already installed).. so I installed the latest version and it does the same thing:  crash  on (attempted) opening. 

I have attached the dump.  Let me know if I should drop this into separate issue :-)
[OBS_crash_report.txt](https://github.com/obsproject/obs-studio/files/7999385/OBS_crash_report.txt)

**Comment by RytoEX** [comment]
This Issue isn't actionable. Our best guess on this is something related to code signing, but all of our macOS binaries should be properly signed. Please try reinstalling OBS Studio 29.0 (or newer).
