### ISSUE TITLE
OBSPropertiesView crashed while deleting audio filter

### ISSUE THREAD

**Issue by walker-WSH** [obsproject/obs-studio#5862]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.0 Beta 4

### OBS Studio Version (Other)

I am using latest code at master ( b77ccceae76106bde6a476557f2c7e91383613a2)

### OBS Studio Log URL

reproduced 100%

### Expected Behavior

no crash

### Current Behavior

crashed while deleting filter.

The reason is that OBSPropertiesView is using filter source which has been released.
The released filter object is storaged in OBSPropertiesView ::obj.

Unfortunately I am not familiar with code related with filter view.

### Steps to Reproduce

1. add source;
2. open filter window;
3. add three audio filters;
4. delete any filter will cause crash.

**Comment by Fenrirthviti** [comment]
Can you provide the crash log please? I believe this was already discovered by @WizardCM, but either way he was just looking at that code.

**Comment by WizardCM** [comment]
This sounds like it's related to
* #5846

**Comment by walker-WSH** [comment]
> Can you provide the crash log please? I believe this was already discovered by @WizardCM, but either way he was just looking at that code.

@WizardCM 

Here is the log and callstack

[2022-01-25 09-04-00.txt](https://github.com/obsproject/obs-studio/files/7929870/2022-01-25.09-04-00.txt)

![1643072680](https://user-images.githubusercontent.com/18413354/150891223-0f5140a0-7739-460f-89a4-5ebf83c50d2a.png)

**Comment by walker-WSH** [comment]
On my PC, crash can happen while doing below operations：
delete topmost filter
delete middle filter
delete bottommost filter

**Comment by walker-WSH** [comment]
@WizardCM 

It seems that PR does not fix it.
I think the reason of this crash is that we are saving/accessing pointer object, but no logic to ensure it's valid while accessing. 

Do you have any solution ? Otherwise I will try to modify logic for OBSPropertiesView::obj

**Comment by exeldro** [comment]
that crash can also be fixed by adding `if (obs_source_removed(source)) return NULL;` into `obs_source_properties`

**Comment by walker-WSH** [comment]
> that crash can also be fixed by adding `if (obs_source_removed(source)) return NULL;` into `obs_source_properties`

When crash happen, `obs_source_t *source` has been released. 
So I think it is not good to access `source->removed` at that time.

**Comment by ogmkp** [comment]
@jp9000 released 27.2.0-rc1, what about this issue and PR https://github.com/obsproject/obs-studio/pull/5846 and PR https://github.com/obsproject/obs-studio/pull/5863 ?
