### ISSUE TITLE
.mxf files not usable on Mac for Stinger transitions

### ISSUE THREAD

**Issue by snip** [obsproject/obs-studio#5870]
### Operating System Info

macOS 11.6

### OBS Studio Version

27.1.3

### OBS Studio Log URL

na

### Expected Behavior

Have .mxf selectable on Mac and Windows for Stinger transition properties and in normal 'Media source' properties.
Have * selectable on Mac for Stinger transition (as a workaround in case of similar issue with other file extension).

### Current Behavior

Today only the following list is selectable:
![image](https://user-images.githubusercontent.com/466133/151176927-d779fcb1-ede8-407d-b45d-fe34770d4cbf.png)

So .mxf files are not usable on Mac for transitions.
.mxf is usable as a 'Media source' to display it normaly (but here also by selecting 'All files' as .mxf is not listed as Video extension supported).

### Steps to Reproduce

1. Add a new trasition type Stinger
2. In Properties try to add a video file with extension .mxf

### Anything else we should know?

On Windows i'm able to slect (*) in the drop down liste of acceptable file extension in Stinger properties. (So which is not the case on Mac)
So on Windows .mxf is usable in Stinger properties. But can be enven better to have mxf in the supported extension file list.

Thanks

**Comment by skeletonbow** [comment]
.mfx or .mxf?

**Comment by snip** [comment]
> .mfx or .mxf?

.mxf thanks.
Edited to correct it.

**Comment by WizardCM** [comment]
Confirmed that for some reason the Stinger file selector has a blank entry + a video files option. And that additionally, our Video Files selection is very limited. I think the best fix here is actually to fix the blank entry so that it's marked as All Files, and that we default to Video Files.
