### ISSUE TITLE
audio via browser source not working in 27.2 beta 4

### ISSUE THREAD

**Issue by micudaj** [obsproject/obs-studio#5878]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.0 Beta 4

### OBS Studio Log URL

https://obsproject.com/logs/ZGwaquA9ANMEnGmD

### Expected Behavior

In OBS 27.1 and earlier I was able to grab audio and control the audio monitor from browser when "control audio via obs" was activated.

### Current Behavior

 In Beta 27.2 no audio is recorded or displayed in monitor. It is not picking up anything.

### Steps to Reproduce

1. Create a webcam share via [vdo.ninja](https://vdo.ninja/)
2.share the view url in a browser source
3. tick "control audio via obs"
...

### Anything else we should know?

In 27.1 I can her audio but the video is stuttering. just fyi. maybe you know why this is the case, because then I could use 27.1

**Comment by WizardCM** [comment]
There are no known issues with the "Control audio via OBS" setting in 27.4. What do you mean by "grab audio"? If you're not hearing the browser source's audio in monitoring, try manually setting your monitoring device in Settings -> Audio.

**Comment by micudaj** [comment]
sorry for nit stating it clearly. I just meant that the audio monitor is not showing any audio activity from the browser source. changing audio devices did not help.But I am using remote audio there as it is a vm. It worked in 27.1 though.

**Comment by WizardCM** [comment]
I cannot reproduce with either a locally created webcam share or a Remote Audio RDP device. Sounds like this isn't an issue in OBS to me.
