### ISSUE TITLE
OBS 27.2 Beta 4 - Browser Source crashes OBS in Virtual Machine with GPU-P

### ISSUE THREAD

**Issue by polskafan** [obsproject/obs-studio#5885]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.0 Beta 4

### OBS Studio Log URL

https://obsproject.com/logs/KEfSXQ8P8C38Mza6

### OBS Studio Crash Log URL

https://obsproject.com/logs/t3cQBg-Hzyh9aol6

### Expected Behavior

Adding a browser source should not crash OBS in a Hyper-V GPU-P environment with Hardware Acceleration enabled.

### Current Behavior

OBS crashes right away, when adding a browser source in a GPU-P virtual environment. It only works when accelerated rendering is disabled.

### Steps to Reproduce

1. Run OBS 27.2.0 Beta 4
2. Add a Browser Source to any scene.

**Comment by RytoEX** [comment]
We do not support running OBS on virtual machines.
