### ISSUE TITLE
OBS 27.2 Beta4 crashes after enabling WebSocket Server

### ISSUE THREAD

**Issue by X21de** [obsproject/obs-studio#5889]
### Operating System Info

macOS 12.0

### Other OS

MacOS 12.2 

### OBS Studio Version

27.2.0 Beta 4

### OBS Studio Version (Other)

Also with 27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/cx-gQKN3sPiWiCC-

### Expected Behavior

 I'd like to use OBS with my StreamDeck 

### Current Behavior

If I start the WebSockets-Server with eg. Port 4444 or 5555 OBS crashes immediately. 

### Steps to Reproduce

1. Just tick the WebSocket-Server checkbox and click Okay

### Anything else we should know?

I tried this on different Macs, all with the same behavior.

**Comment by tt2468** [comment]
Looks like a known issue with conflicting ASIO versions used by obs-webocket and other potential plugins. I recommend uninstalling the loupdeck-obs plugin and alerting the developers that they need to strictly use ASIO version 1.12.1.

I also cannot find the source code for loupdeck-obs, which would put them in violation of our code license.

**Comment by X21de** [comment]
Thanks for pointing me the right direction.
I deleted the Loupdeck Folder in:
/Library/Application Support/obs-studio/plugins/

**Comment by X21de** [comment]
Talked to the Loubdeck Support,

they have addressed the issue and will fix it in the version.
