### ISSUE TITLE
Obs Frequently crashes

### ISSUE THREAD

**Issue by Derpspace1** [obsproject/obs-studio#5890]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/A2NCB9roUB557S7L

### OBS Studio Crash Log URL

https://obsproject.com/logs/UARpmH-cjf3k7xAh

### Expected Behavior

I expect obs to open/close without crashing.

### Current Behavior

When I open obs, about 50% of the time it shows the obs has cashed message. When I close obs, most of the time it crashes aswell.

### Steps to Reproduce

1. Open obs
or
2. Close obs

**Comment by RytoEX** [comment]
This crash appears to be caused by the win-capture-audio plugin.  Please update both OBS and win-capture-audio plugin and check again.  However, if it is still crashing, I recommend consulting the plugin author, as this crash is caused by the plugin and not OBS itself.
