### ISSUE TITLE
Quest for Glory 5 Capture Issues

### ISSUE THREAD

**Issue by CMSCalvert** [obsproject/obs-studio#5894]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/pqPM5BHgF5jVZkXs

### Expected Behavior

When using window capture or game capture, OBS Should acknowledge the EXE of the game being used to capture, and display it properly in the scene/monitor.

### Current Behavior

I'm having issues capturing an old game from GOG: Quest for Glory 5. 
This game was working fine for weeks, until a recent windows update.
Based on the help from the volunteers in discord, as well as their support site links, I was able to confirm that NONE of the listed "conflicting" software is running on my tower, and conflicting with OBS or the game I'm capturing. For WEEKS, it worked fine with Window Capture, and eventually Game Capture, but as of today neither works. Window Capture refuses to acknowledge the EXE exists when running. Game Capture sees the EXE but won't output the display of the game to the scene/window in OBS. 
Per suggestions from discord volunteers I've even updated my GeForce Drivers, but to no avail. The ONLY way that works is doing a display capture, which is not ideal.
Based on all of this, I believe windows updates are causing the compatibility and capture/display issues. I see this as a bug between OBS and those windows updates, specific to full screen games, or older games.

### Steps to Reproduce

1. Launch QFG5.exe (quest for glory 5, either from desktop shortcut, back end EXE, or from the GOG Galaxy Console.
2. Alt+TAB out of the game, since it launches into full screen mode by default and cannot be windowed.
3. Open OBS, run as-administrator.
4. Go to the scene where Window Capture or Game Capture is set to capture your game.
5. Use the properties for WINDOW CAPTURE, and try to set it to capture that window where the game's EXE is listed.
6. The game's EXE will not show up;
7. Attempt to configure a GAME CAPTURE, with the same EXE, which should be selectable in the properties of the game capture. 
8. ALT+TAB back to the game, 
9. Your game will not display in the scene, but you may be able to hear the game audio if it's outputting as "desktop audio".
...

### Anything else we should know?

The ONLY thing that really changed with my PC in the last week, is that there were 2 windows updates:
Windows update KB5008876
Security Update KB5007186
Both installed within the last week, since the last time I streamed this particular game, exactly 1 saturday ago.

**Comment by WizardCM** [comment]
This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels below, and if it's determined that this is indeed a bug, then we will re-open this issue.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
