### ISSUE TITLE
No way to access legacy color correction and no way to copy it out of source in another scene collection

### ISSUE THREAD

**Issue by PQCraft** [obsproject/obs-studio#5897]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

27.1.3

### OBS Studio Log URL

N/A

### OBS Studio Crash Log URL

N/A

### Expected Behavior

A menu option saying 'Color correction (legacy)' or any way to use the old color correction

### Current Behavior

Cannot copy it out of the filters from another scene collection but can copy to anything in that collection

### Steps to Reproduce

1. Look for a way to use the old color correction

### Anything else we should know?

I see this as a regression therefore I reported it as a bug instead of a feature request. The old color correction has the ability to invert the colors and brightness by inverting the contrast which is very useful for what I'm trying to do.

**Comment by Fenrirthviti** [comment]
It sounds like the old behavior was a bug, and not an intended result. I'd read this as a feature request for a proper "Invert Colors" filter, as I don't think we should be supporting bugs as viable workflow options. Hue Shift in the new filter seems to do most of the job, but it doesn't invert blacks, so probably not the effect you're looking for.

I'm not going to close this as I'd like other contributor's opinions, but it's unlikely that we will expose the legacy filter.

**Comment by mufunyo** [comment]
You can invert colours using the LUT filter.

**Comment by PQCraft** [comment]
@mufunyo Thanks! I took the `original.png` LUT template and inverted the colors in GIMP then put it into OBS and it works 👍
