### ISSUE TITLE
 Encoder x264 recording blurred

### ISSUE THREAD

**Issue by Pantyhose-X** [obsproject/obs-studio#5901]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.0 Beta 4

### OBS Studio Log URL

https://obsproject.com/logs/jrE_nP3hKjcRUUCD

### Expected Behavior

Use this default value to solve the Game Recording BlurRed
> * [ ] `Output Mode` `Advancced` Default `Bitrate 5000kbps` Default 
> * [ ] `Video` Downscale Filter `Lanczos (Sparpened Scaling, 36 Samples)`

### Current Behavior

`Output Mode` `Advancced` Default `Bitrate 2500kbps` Default 
`Video` Downscale Filter `Bicubic (Sparpened Scaling, 16 Samples)`

### Steps to Reproduce

1.Settings `Output Mode` `Advancced` Encoder Software (x264)
2.Settings Video Downscale Filter
3.
...

**Comment by kkartaltepe** [comment]
Please do not repeatedly open issues after your original has been closed.

**Comment by norihiro** [comment]
I think the suggestion page is more adequate.
https://ideas.obsproject.com/
