### ISSUE TITLE
Mouse is being incorrectly rendered in obs studio

### ISSUE THREAD

**Issue by K4LCIFER** [obsproject/obs-studio#5902]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

27.1.3

### OBS Studio Version (Other)

27.1.3-3

### OBS Studio Log URL

https://obsproject.com/logs/wWRXwNA5azdeZKvd

### Expected Behavior

I expect obs studio to just use my system mouse.

### Current Behavior

OBS seems to replace my system mouse when I hover over the window for some reason. 
- The mouse is scaled in size by what seems to be about 3 times
- My mouse cursor theme is removed and reverted back to the stock gnome theme

https://user-images.githubusercontent.com/7829231/152094411-3f886c7c-707e-4e79-b1ff-d4c808c633e8.mp4

### Steps to Reproduce

1. Open OBS studio
2. hover the mouse over OBS and observe that it is different than what it should be

### Anything else we should know?

AMD RX 6600
Gnome Wayland on Arch Linux
Pipewire

**Comment by kkartaltepe** [comment]
We dont generally maintain the cursor state, so you should probably instead file a bug to Qt that they dont choose what you expect given your gnome theme settings. I doubt there is anything for us to do but ill leave this bug open for now.

**Comment by All3xJ** [comment]
Same bug here #6400

**Comment by gxalpha** [comment]
This is likely https://bugreports.qt.io/browse/QTBUG-67579 which would be fixed in Qt 6.4.2 or 6.5.0.
This should be fixed once we update to either of those versions (OBS 29 will only be 6.4.1 though).

**Comment by RytoEX** [comment]
> This is likely https://bugreports.qt.io/browse/QTBUG-67579 which would be fixed in Qt 6.4.2 or 6.5.0. This should be fixed once we update to either of those versions (OBS 29 will only be 6.4.1 though).

As an aside, we don't maintain the package this was reported against. It looks like Arch Linux is now using Qt 6.4.3, so this might be fixed in new installs of the package. If this happens in our Flatpak builds, then we can control when Qt is updated for those. This should be fixed in OBS Studio 29.1 (currently in beta) Flatpak builds, which use Qt 6.4.3.
