### ISSUE TITLE
Unable to start virtual cam on macOS

### ISSUE THREAD

**Issue by jnnkB** [obsproject/obs-studio#5904]
### Operating System Info

macOS 12.0

### OBS Studio Version

27.1.3

### OBS Studio Log URL

see below

### Expected Behavior

When clicking on Start Virtual Camera the virtual camera is startet.

### Current Behavior

Nothing happens. The log shows the following line:

```
[mac-virtualcam] [macOS] VirtualCam DAL Plugin Installation status: (null)
```

### Steps to Reproduce

1. Open OBS
2. Click Start Virtual Camera

### Anything else we should know?

Here are the startup logs:

<details><summary>Startup Logs</summary>
<pre>
10:47:08.866: CPU Name: Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
10:47:08.866: CPU Speed: 3400MHz
10:47:08.866: Physical Cores: 4, Logical Cores: 4
10:47:08.866: Physical Memory: 8192MB Total
10:47:08.866: OS Name: Mac OS X
10:47:08.866: OS Version: Version 12.1 (Build 21C52)
10:47:08.866: Kernel Version: 21.2.0
10:47:08.908: hotkeys-cocoa: Getting keyboard keys failed
10:47:08.908: hotkeys-cocoa: Getting keyboard keys failed
10:47:08.908: hotkeys-cocoa: Using layout 'com.apple.keylayout.German'
10:47:08.911: Current Date/Time: 2022-02-02, 10:47:08
10:47:08.912: Browser Hardware Acceleration: true
10:47:08.912: Portable mode: false
10:47:19.035: OBS 27.1.3 (mac)
10:47:19.035: ---------------------------------
10:47:19.368: ---------------------------------
10:47:19.368: audio settings reset:
10:47:19.368: 	samples per sec: 48000
10:47:19.368: 	speakers:        2
10:47:20.009: ---------------------------------
10:47:20.009: Initializing OpenGL...
10:47:20.396: Loading up OpenGL on adapter ATI Technologies Inc. AMD Radeon Pro 560 OpenGL Engine
10:47:20.396: OpenGL loaded successfully, version 4.1 ATI-4.7.101, shading language 4.10
10:47:21.209: ---------------------------------
10:47:21.209: video settings reset:
10:47:21.209: 	base resolution:   1280x720
10:47:21.209: 	output resolution: 1280x720
10:47:21.209: 	downscale filter:  Bicubic
10:47:21.209: 	fps:               30/1
10:47:21.209: 	format:            NV12
10:47:21.209: 	YUV mode:          709/Partial
10:47:21.209: NV12 texture support not available
10:47:21.270: Audio monitoring device:
10:47:21.270: 	name: Default
10:47:21.270: 	id: default
10:47:21.324: ---------------------------------
10:47:21.530: Failed to load 'en-GB' text for module: 'coreaudio-encoder.so'
10:47:21.572: Failed to load 'en-US' text for module: 'decklink-captions.so'
10:47:21.717: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
10:47:22.964: os_dlopen(libpython3.9.dylib->libpython3.9.dylib): dlopen(libpython3.9.dylib, 0x0101): tried: '/Applications/OBS.app/Contents/MacOS/../Frameworks/libpython3.9.dylib' (no such file), '/Applications/OBS.app/Contents/MacOS/../Frameworks/libpython3.9.dylib' (no such file), '/Applications/OBS.app/Contents/MacOS/../Frameworks/libpython3.9.dylib' (no such file), '/Applications/OBS.app/Contents/MacOS/../Frameworks/libpython3.9.dylib' (no such file), 'libpython3.9.dylib' (no such file), '/usr/lib/libpython3.9.dylib' (no such file), '//libpython3.9.dylib' (no such file), '/usr/lib/libpython3.9.dylib' (no such file)
10:47:22.964: 
10:47:22.964: [Python] Could not load library: libpython3.9.dylib
10:47:23.539: Failed to load 'en-GB' text for module: 'mac-capture.so'
10:47:23.656: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
10:47:23.676: No blackmagic support
10:47:23.912: [mac-virtualcam] version=1.3.0
10:47:24.130: Failed to load 'en-GB' text for module: 'mac-vth264.so'
10:47:24.571: obs_register_encoder: Encoder id 'com.apple.videotoolbox.videoencoder.h264.gva' already exists!  Duplicate library?
10:47:24.571: [VideoToolbox encoder]: Adding VideoToolbox H264 encoders
10:47:24.727: Failed to load 'en-GB' text for module: 'obs-browser.so'
10:47:24.727: [obs-browser]: Version 2.16.3
10:47:24.727: [obs-browser]: CEF Version 85.0.0-HEAD.2273+g93b66a0+chromium-85.0.4183.121
10:47:28.905: Failed to load 'en-GB' text for module: 'obs-vst.so'
10:47:29.046: Failed to load 'en-GB' text for module: 'obs-x264.so'
10:47:29.221: Failed to load 'en-GB' text for module: 'rtmp-services.so'
10:47:30.086: VLC found, VLC video source enabled
10:47:30.087: ---------------------------------
10:47:30.088:   Loaded Modules:
10:47:30.088:     vlc-video.so
10:47:30.088:     text-freetype2.so
10:47:30.088:     rtmp-services.so
10:47:30.088:     obs-x264.so
10:47:30.088:     obs-vst.so
10:47:30.088:     obs-transitions.so
10:47:30.088:     obs-outputs.so
10:47:30.088:     obs-filters.so
10:47:30.088:     obs-ffmpeg.so
10:47:30.088:     obs-browser.so
10:47:30.088:     mac-vth264.so
10:47:30.088:     mac-virtualcam.so
10:47:30.088:     mac-syphon.so
10:47:30.088:     mac-decklink.so
10:47:30.088:     mac-capture.so
10:47:30.088:     mac-avcapture.so
10:47:30.088:     image-source.so
10:47:30.088:     frontend-tools.so
10:47:30.088:     decklink-ouput-ui.so
10:47:30.088:     decklink-captions.so
10:47:30.088:     coreaudio-encoder.so
10:47:30.088: -------------------------------
</pre>
</details>

**Comment by gxalpha** [comment]
Did you get a prompt to enter your admin password? If so, did you dismiss it?

**Comment by jnnkB** [comment]
No I didn't

**Comment by gxalpha** [comment]
In Finder, could you click Go To -> Go to folder (or press Cmd+Shift+G), enter `/Library/CoreMediaIO/Plug-Ins/DAL` in the field that pops up and check wether there is a file called `obs-mac-virtualcam.plugin` in there?

**Comment by jnnkB** [comment]
No it seems to be missing

**Comment by jnnkB** [comment]
Ok so I just downloaded the DMG again and copied the file `/Volumes/OBS-Studio 27.1.3/OBS.app/Contents/Resources/data/obs-plugins/mac-virtualcam` into `/Library/CoreMediaIO/Plug-Ins/DAL`. Now its working :)
