### ISSUE TITLE
UI : Audio Mixer show the scrollbar even when not necessary

### ISSUE THREAD

**Issue by Trouffman** [obsproject/obs-studio#5905]
### Operating System Info

Windows 11

### OBS Studio Version

27.1.3

### OBS Studio Version (Other)

portable

### OBS Studio Log URL

https://obsproject.com/logs/uhXtMHTXT7nqiE2b

### Expected Behavior

The Audio Mixer Dock show not show the scrollbar when not required.

For example : when only 2 audio input are displayed, the scroll bar is usually not needed (unless you reduce the size of the dock.

![image](https://user-images.githubusercontent.com/2151317/152230974-ea817dcb-ed5d-4ec0-8339-359dbde976aa.png)

### Current Behavior

The scrollbar on the right side of the Audio Mixer dock is visible at all time even whne not required.

![image](https://user-images.githubusercontent.com/2151317/152230850-5c788ac3-7a57-4ab0-9b7a-195dcf280510.png)

Btw this is the same on OBS 27.2 RC1
![image](https://user-images.githubusercontent.com/2151317/152231314-82fc4cac-35dc-4890-a9cc-0524a782acc3.png)

### Steps to Reproduce

1. Open OBS
2. Look at the Audio Mixer

### Anything else we should know?

This is purely cosmetic.

**Comment by Warchamp7** [comment]
This is intentional but I forget if it's to prevent controls jumping around, or if it was a performance thing because of the mixers render update shenanigans. Will chat with some folks on this

**Comment by WizardCM** [comment]
For reference this was last reported in #5176.

The code for this is:

https://github.com/obsproject/obs-studio/blob/f52f34b614804b43486117aa2b06da0fdf3c6260/UI/forms/OBSBasic.ui#L1018-L1019

https://github.com/obsproject/obs-studio/blob/f52f34b614804b43486117aa2b06da0fdf3c6260/UI/forms/OBSBasic.ui#L1074-L1075

**Comment by Trouffman** [comment]
Thanks @WizardCM 

Do you remember the reason behind it? (So this can be referenced if this comment pops-up again)

As far a I could go back I could not find more details.

I went all the way back to this back in the days:
https://github.com/obsproject/obs-studio/commit/52746c25230d4cd724246ea8a56800de675fc341?diff=split

**Comment by Ricky-Tigg** [comment]
Far from cosmetic. In the depicted context its very presence does imply that there is more to be seen. This behaviour is eligible to be interpreted as an issue rather than a intentional.

**Comment by Ricky-Tigg** [comment]
Far from cosmetic. In the depicted context its very presence does imply that **there is more to be seen**. This behaviour is eligible to be interpreted as an issue rather than intentional.

**Comment by Fenrirthviti** [comment]
I don't think anyone disagrees that this isn't ideal, this is the lesser of two evils until a better solution can be found. However, it *is* a cosmetic issue, not really a bug. It does not impact or impede any functionality of the program, and the scrollbar being there is an intentional choice made to avoid other issues (related to snapping and resizing, which if I remember right, would actually break the scrollbar from working at all).

**Comment by cg2121** [comment]
With #6352, I found it causes no problems whatsoever when having the scrollbars only show up when needed.
