### ISSUE TITLE
Stuttering in output video in games and desktop capture

### ISSUE THREAD

**Issue by CobaltRogue1998** [obsproject/obs-studio#5912]
### Operating System Info

Windows 11

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/Jq_fDN3C75D4aKFn

### Expected Behavior

Recordings to not have glitches and stutters or dropped frames

### Current Behavior

I have 2 computers with completely different hardware both running Windows 11 and recordings come out with dropped frames even though my GPU, RAM and CPU aren't being fully utilized. No matter if I used x264 or NVENC on my desktop or x264 or AMD on my laptop it has this issue. MSI afterburner has the issue too. It may be something up with Windows 11. Tried different bitrates, resolutions, high process priority, game mode on and off, administrator mode and still ends up stuttery. The log probably shows dropped frames.

If you watch this video and you pause at anytime it reveals there is a ghost cursor and is not as smooth as it could be for 60fps. In games this looks like dropped frames. This was just the easiest way to reveal the issue. 
https://www.youtube.com/watch?v=U5tMLF4jr9g

This image is a screenshot of the cursor.
https://ibb.co/BPrNYJT

### Steps to Reproduce

1. while using windows 11 record the desktop or a game
2. the output should have stutters
...

**Comment by Fenrirthviti** [comment]
This appears to be a support request, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by CobaltRogue1998** [comment]
Sorry, I later figured out this is a duplicate of issue #4191
