### ISSUE TITLE
Videos recorded directly at OBS glitches

### ISSUE THREAD

**Issue by ApplicationCoding** [obsproject/obs-studio#5915]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/kdJ8PG5x6KXm5hxC

### Expected Behavior

I was expecting OBS to record video just fine.

### Current Behavior

I was recording a video on OBS. Everything seems to work just fine as the viewer doesn't show any kind of bug. But when I was to play the video recording itself, the video was glitching. If my term is wrong, please correct it. But I have a screenshot of the clip I have recorded as an example of this bug.
![OBS Glitch Screenshot](https://user-images.githubusercontent.com/76902392/152452307-33d5e63e-9024-4a24-bfa4-cd64a484df5e.png)

### Steps to Reproduce

1. Record a video (screen recording, video recording, etc.)
2. Start recording
3. Stop recording
...

### Anything else we should know?

This bug started to happen last month. This same thing happens at any software I put it into. I don't think it's the graphics driver itself that makes the problem because most of the video clips I play are just fine. But, I think OBS has another way of recording that my graphic does not support or, it's just an OBS bug.

**Comment by WizardCM** [comment]
This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels below, and if it's determined that this is indeed a bug, then we will re-open this issue.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
