### ISSUE TITLE
Performance issues using PipeWire sources on GBM/Wayland NVidia

### ISSUE THREAD

**Issue by VortexAcherontic** [obsproject/obs-studio#5916]
### Operating System Info

Other

### Other OS

openSUSE Tumbleweed

### OBS Studio Version

Git

### OBS Studio Log URL

https://obsproject.com/logs/yGKrGXVZQDFk1miI

### Expected Behavior

Smooth game play and smooth video footage

### Current Behavior

Choppy game play and choppy video footage

### Steps to Reproduce

1. Run Wayland on NVidia with driver 510.47.03
2. Add a PipeWire Dekstop or Window capture source
3. Select either an XWayland windows or native Wayland Window
4. Notice performance drops both in game and frame drops in OBS Studio

### Anything else we should know?

The more taxing a game is for the system the worse the gameplay and video footage gets.
Using PipeWire Desktop Capture is less choppy than Window capture but still not a pleasant experience.  
Running entirely on X11 on the same recording and game settings does not produce any lags or frame drops neither in the footage nor in-game.

Here are some test screencasts under different circumstances:

- [DOOM Eternal Wayland PipeWire Desktop](https://youtu.be/PQJK4M4t6Bo)
- [DOOM Eternal Wayland PipeWire Window](https://youtu.be/g0h3pNO473k)
- [DOOM Eternal X11 XComposite](https://youtu.be/GSMItv3BQBs)
- [DOOM Eternal X11 XSHM](https://youtu.be/9bMXtza4VN0)

You can see that running on X11 and both XSHM and XComposite produce butter smooth video footage also the gameplay is just fine.

To add a less taxing game and one where I was able to force the use of XWayland or native Wayland here are some Xonotic Screen captures.  
Using XWayland or native Wayland seems not to make any differences.  
Still the issue with the PipeWire sources is also there but less noticeable. 
While also both X11 screencasts are butter smooth as well:

- [Xonotic Wayland PipeWire Window](https://youtu.be/yoiNbDVyvIY)
- [Xonotic XWayland PipeWire Window](https://youtu.be/FQCuUPaOcPM)
- [Xonotic X11 XComposite](https://youtu.be/irHU0zG5AZc)
- [Xonotic X11 XSHM](https://youtu.be/XphFWI-QV8Y)

Not sure if this is a driver thing and up to nvidia to fix or an actual issue with the PipeWire sources.

Also I used the latest Git build (3rd Feb. 2022) because of egl errors with 27.1.3

NVidia Driver Version: 510.47.03
Mesa: 21.3.4
libwayland-egl1: 1.20.0
libnvidia-egl-wayland1: 1.1.9
Kernel: 5.16.2
xwayland: 21.1.4
PipeWire: 0.3.45

Kind regards,
V.

**Comment by kkartaltepe** [comment]
The log shows there is no issue with pipewire sources on your system. Instead your compositor and Qt are failing to display the preview in a timeline manner, you should file a bug against one or the other (but since you dont provide information about either who knows). Also nvidia egl drivers are qt are not compatible so until that is resolved nvidia on wayland is basically unsupported.

**Comment by VortexAcherontic** [comment]
Thank you for your quick answers.
Guess I'll check out the qt thingy.

Many thanks :)

Compositor is Mutter of Gnome 41.3 and qt5 is 5.12.2 in case this would change anything 😄

**Comment by kaimast** [comment]
I see weird delays on Gnome/Mutter too. Did you ever file a bug on GNOME's gitlab for this?

**Comment by VortexAcherontic** [comment]
Actually no. But I have a feeling they close it with "3. Not Gnome". Hadthis with other OBS related issues on NNvidia already :/

**Comment by kaimast** [comment]
This one might be relevant? https://gitlab.gnome.org/GNOME/mutter/-/issues/2249

**Comment by kkartaltepe** [comment]
Please dont use our bug tracker as a forum. We have a forum and a discord for you to discuss on, use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum) links to get there.
