### ISSUE TITLE
OBS randomly hard-crashes Windows

### ISSUE THREAD

**Issue by BACONGUDEN** [obsproject/obs-studio#5918]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.2.0-beta4

### OBS Studio Log URL

https://obsproject.com/logs/MDXQeyMPUF91RYaT

### OBS Studio Crash Log URL

https://obsproject.com/logs/D-J-JDU1Y_TWXA3_

### Expected Behavior

Obs to not crash, this happens randomly without any warning

### Current Behavior

Random crashes with no indication, no BSOD. This freezes my computer entirely requiring a "choke restart" (holding power button down).

### Steps to Reproduce

1. Start OBS
2. Sit and wait

### Anything else we should know?

I have tried the following:
Updated all drivers
Unplugged all USB devices
Run a blank profile
Uninstalling all plugins
Reinstalling OBS Beta 4
Removing all VST's from Audio sources

More troubleshooting:
This has never happened before updating to Beta 3 and Beta 4.
Times between booting OBS and for it to hard crash differs every time, no specific action is needed other than opening OBS.
Last logs in event viewer is a DCOM issue before crash
Nothing in kernel live reports

Any troubleshooting help is very much appreciated!

I have a video on how this is happening on my Twitter: 
https://twitter.com/BACONGUDEN/status/1490072707677007874

**Comment by BACONGUDEN** [comment]
> This sounds like a hardware issue, user mode programmes like OBS cannot freeze your PC in this way.

There is no other program on my computer that causes this type of crash, this has never happened before upgrading to Beta 3 and then Beta 4 and I have been using OBS before the Studio version was out. 
I really need help in troubleshooting this since OBS is the only program that can reproduce this issue.

**Comment by BACONGUDEN** [comment]
I tried tinkering some more by running OBS just for a few seconds each then closing it, and I got two log files where I managed to close OBS without it freezing my computer. 

I'm not familiar with the logs, but at the bottom of each log file it says:
"Number of memory leaks: 31171"
"Number of memory leaks: 18950"

[2022-02-06 00-21-07.txt](https://github.com/obsproject/obs-studio/files/8009110/2022-02-06.00-21-07.txt)

Does anyone know if this is what's causing the crash?
I'm really in need of help here, I really wanna fix this so I can get back to streaming.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

You're also using a decent number of third party plugins, which are almost certainly the cause for the high number of memory leaks being reported.

Thank you!
