### ISSUE TITLE
[27.2.0-rc1] SVT-AV1 encoder not respecting bitrate setting

### ISSUE THREAD

**Issue by McMasterGold** [obsproject/obs-studio#5920]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.0 RC 1

### OBS Studio Log URL

https://obsproject.com/logs/5BbyLGWyd4Df0N7S

### Expected Behavior

In the Output -> Recording settings menu, the bitrate (and probably rate control) settings are not respected when using the SVT-AV1 encoder.

### Current Behavior

Instead, the video file seems to be capped to a bitrate of about 2Mbps, or even less when there is not much motion in the recording. The situation is the same with either the default bitrate controls (CBR 2500Kbps) or any custom ones (including CBR, VBR and CQP).

### Steps to Reproduce

1. Go to Output -> Recording settings.
2. Make sure Output Mode is set to Advanced.
3. Select SVT-AV1 as the encoder.
4. Adjust the bitrate and/or rate control.
5. Observe the bitrate of the output video file.

### Anything else we should know?

I have tested all three rate control settings (CBR, VBR and CQP), presets 10/11/12, as well as MP4 and MKV containers. No difference.

The issue does not occur with AOM AV1 (as well as x264).

**Comment by jp9000** [comment]
Good catch, seems it has an explicit rate control setting in ffmpeg rather than it intelligently deducing which rate control method based upon the ffmpeg parameters. I'll try to fix this for RC2.

**Comment by jp9000** [comment]
Should be mostly fixed via 109b54fd66d3ae24b3f4477b07928f7df441710f

**Comment by McMasterGold** [comment]
With the release 27.2.0 build I can confirm that CBR and VBR modes in SVT-AV1 now seem to be working correctly, however CQP is still bugged. The bitrate stays the same (2-3Mbps) no matter the CQ Level (even at 1 it's the same with 50). Is a fix planned for the future or should I open a new issue report?
