### ISSUE TITLE
Custom browser docks not remembering logins after closing OBS

### ISSUE THREAD

**Issue by mopheadniall** [obsproject/obs-studio#5923]
### Operating System Info

Windows 11

### OBS Studio Version

27.2.0 RC 1

### OBS Studio Log URL

https://obsproject.com/logs/PTnpB_qiIepgkCtq

### Expected Behavior

Custom browser docks were previously saving twitch logins between closing and opening OBS

### Current Behavior

Custom browser docks aren't keeping any logins saved anymore and require a new login and auth code each session

### Steps to Reproduce

1. create custom browser dock for a twitch dashboard popout
2. log in to twitch (ticking "remember this login for 30 days")
3. restart obs studio
4. see the prompt to require login again (also to accept cookies again)

### Anything else we should know?

repeatable with fresh obs studio install and with other website logins

**Comment by WizardCM** [comment]
I definitely have not run into this issue. Try clearing your cookies:

1. Exit OBS (make sure OBS is not running)
2. Delete the folder `%appdata%\obs-studio\plugin_config\obs-browser\obs_profile_cookies`
3. Start OBS
4. Settings -> Stream -> disconnect -> connect

**Comment by mopheadniall** [comment]
really thought this wasn't just a me issue, sorry that this became a support thread :/

> I definitely have not run into this issue. Try clearing your cookies:
> 
> 1. Exit OBS (make sure OBS is not running)
> 2. Delete the folder `%appdata%\obs-studio\plugin_config\obs-browser\obs_profile_cookies`
> 3. Start OBS
> 4. Settings -> Stream -> disconnect -> connect

tried clearing the cookies as you said and still had the same issue 

**solved it nonetheless! so many thanks**

i believe i solved it by deleting the "cookies" and "cookies-journal" files inside '%appdata%\obs-studio\plugin_config\obs-browser'
since the "obs_profile_cookies" don't apply to custom docks

but i also deleted the "cef.74.0.chrome.0.1946.74.0" folder as it contained files including the word "cookie"

**i guess a sure fix for anyone else would be: 

1) navigate to '%appdata%\obs-studio\plugin_config\obs-browser'
2) search for "cookie" 
3) recycle everything that it finds**

**Comment by WizardCM** [comment]
Thank you for providing the solution that worked for you. We'll keep an eye out for similar reports for people migrating from OBS 27.1.3 to OBS 27.2

**Comment by DeDumChee** [comment]
Just commenting so you know you're not alone, your fix solved it for me!
