### ISSUE TITLE
OBS will grind Windows to a halt

### ISSUE THREAD

**Issue by Caladius** [obsproject/obs-studio#5924]
### Operating System Info

Windows 11

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/PlkSbpILFMZ4JJwG

### Expected Behavior

I expected OBS to be able to be left open while I work on Scenes and other stream related things while not streaming. I also expected to be able to Start and Stop streaming or change games while streaming without the issue occurring every time.

### Current Behavior

I have been trying my hardest to collect a usable log file for my odd behavior. Whether i actually go live or not the problem still occurs, frequently too. I used the batch file to set OBS to Verbose logging but I don't see anything out of the ordinary that I am smart enough to discern.

The issue is I launch OBS (this occurred day one on a fresh install even without any scenes, sources, or plug ins added) and after some time, 5 mins or sometimes 30 minutes, OBS will begin locking up my computer. Task Manger does not show resource hogging of any kind (everything is well under 20% utilization), however OBS will not respond to anything, the preview window is frozen, and anything i have open in windows begins to chug/stutter/framedrop to a halt.

This is immediately resolved once i can force OBS to close (everything will begin operating at full speed again). Attached is my latest log if someone is able to assist. I have a pretty modern PC running Windows 11, for some reason the log shows Windows 10.

I reinstalled OBS twice today (2-6-2022) and was unable to resolve the issue. As a test I installed StreamLabs (I greatly prefer OBS due to the high quality of work put in and the support for plugins that I currently use) to ensure it was not my PC, StreamLabs did not present this issue after multiple test streams using the same scenes and sources.

### Steps to Reproduce

There are 2 scenarios which end with the same result.

Steam Method
1. Launch OBS Studio
2. Create a scene with Game Capture
3. Run the Game and start streaming
4. Close out of the game and attempt to switch games

Non Stream Method
1. Open OBS
2. Create some scenes with Game Captures or other typical sources for basic stream setups
3. Leave open for a period of time (the last issue occurred on its own when OBS was left open undisturbed for a couple of hours

### Anything else we should know?

Can provide screenshots or other Scene details as requested. I have tried to remove all scenes and sources and create new profiles but all resulted with the issue occurring.

Willing to work with someone to resolve this as the plugins available on OBS make this software my preferred choice and improve the quality of my stream and ability to entertain.

Thank you for the hard work put in thus far, I love the software otherwise
![Scenes](https://user-images.githubusercontent.com/8377717/152715302-e9a594fb-5233-451e-a763-1f920dfa0502.png)
![Source Sample](https://user-images.githubusercontent.com/8377717/152715303-133626b7-eba1-42ee-a66d-9432a59a052a.png)
.

**Comment by WizardCM** [comment]
Try it without the SE.Live plugin, as that replaces a core component of OBS.

**Comment by Caladius** [comment]
Thank you! I will give it a try and let you know ASAP.

Appreciate it greatly

**Comment by Caladius** [comment]
Hi Matt,
 Thank you for the tip, I installed OBS without the Stream elements
components and it worked perfectly.

Thank you for the quick response!
