### ISSUE TITLE
OBS FPS drops the moment a browser sources content becomes active

### ISSUE THREAD

**Issue by TheRealDadbeard** [obsproject/obs-studio#5933]
### Operating System Info

Windows 11

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.2.0 RC 2

### OBS Studio Log URL

https://obsproject.com/logs/dqwNGFl-OZaB_yZa

### Expected Behavior

No stuttering when browser sources are enabled

### Current Behavior

Having browser sources on the scene make OBS drop it's FPS

### Steps to Reproduce

1. Have a scene with Kappagen (because it can be triggered)
2. Start a Game, for me I tested with Hitman 3, Highest Settings
3. Trigger Kappagen while OBS is open and watch the FPS counter

### Anything else we should know?

I have HAGS on so I don't start OBS as admin and with the exact same setup, scene etc. on the release version I have no fps drops.

**Comment by TheRealDadbeard** [comment]
Just tested with a low gpu usage game and it does not happen there.

**Comment by TheRealDadbeard** [comment]
This is still an issue with the new release. Just tried with Cyberpunk and my FPS instantly drop in OBS.

**Comment by TheRealDadbeard** [comment]
I can't seem to repro it now constistenly.

I think It had something to do with nested scenes as this is where I had my alerts in and then nested that in my gaming scene.

I now tried multiple combinations but can't seem to make it drop fps. I have no idea how this fixed itself.

**Comment by TheRealDadbeard** [comment]
OK I can now repro it way better. Hitman 3 is still a good game to test this as it hammers the GPU.

I found out that this only happens when I have my Alert browser source activated too. So what I did is to trigger follower alerts in Streamelements with my alert and kappagen source on. Then move around in Hitman 3 and watch the FPS counter in obs.

It would occasionally drop. Sometimes only one time so I had to try multiple times. When I disable my alert source those drops did not occur. I can have up to 5 browser sources active at any time. They are

Subgoal
Followergoal
Kappagen
Alert Source
Alert Source only for Text and TTS

Disabling any of the others other than my Alert source seem to not make a difference. I use Boosted Alerts from Nerd Or Die. They have a free version so you can try it out. This does not happen on the previous OBS release. 

My issue goes away though when I disable Hardware acceleration. I tried this with HAGS on and off and it did not make a difference.

If you have more questions ask me.

**Comment by TheRealDadbeard** [comment]
Any fix for that in sight? I'm pretty much stuck on 27.1.3 because of this

**Comment by RytoEX** [comment]
We _may_ have a fix for this available as part of our investigation into #5974.  That aside, we'll update this Issue if we have any new information to share.

**Comment by TheRealDadbeard** [comment]
Okay thank you, I'll just watch this space and then test updates when they come if it fixes my issue.

**Comment by TheRealDadbeard** [comment]
27.2.1 has fixed my issue.
