### ISSUE TITLE
OBS is crashing a lot in the new rc-3 update

### ISSUE THREAD

**Issue by MarcBeast** [obsproject/obs-studio#5934]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.2.0-rc3

### OBS Studio Log URL

https://obsproject.com/logs/4ts36UwrFRuXEq95

### OBS Studio Crash Log URL

https://obsproject.com/logs/5_1Nl7k-5QfkdiP4

### Expected Behavior

Changing the Stream encoder to H264

### Current Behavior

OBS is crashing after changing too many options or too fast. Or sometimes even when Opening the settings menu.
 

### Steps to Reproduce

1. Opening OBS
2. Going to the settings menu (if it's not crashed already>)
3. Change some Settings
...

### Anything else we should know?

Sry if i have some bad english miss spells, english is not my Mainlanguage. And i know this update is just one hour old, but i think you quys should know this. I will try reinstalling OBS completily.
Latest Windows update (today realeased, 08.02.2022) and current VC Redist are installed.

**Comment by MarcBeast** [comment]
So... I reinstalled OBS with the current rc-3 update, and it is still crashing and some setting's are gone i quess...
I dont know if this is new that you can't change Recording Proberties anymore, or if this is a bug > Screenshots
![Screenshot 2022-02-08 213714](https://user-images.githubusercontent.com/77436704/153071725-2af5ba7c-e7a1-4854-85a3-7388ea59cdef.png)

**Comment by notr1ch** [comment]
Looks like a regression introduced by https://github.com/obsproject/obs-studio/commit/b0528e0cf7c67d4ae17967bd50fbebb919006f4f, `rawObj` is not always initialized.

**Comment by jp9000** [comment]
My fault. Sorry about that.
