### ISSUE TITLE
OBS sets Mac OS 12.2 on M1 to 60fps globally 

### ISSUE THREAD

**Issue by koshimazaki** [obsproject/obs-studio#5937]
### Operating System Info

Other

### Other OS

Mac OS 12.2

### OBS Studio Version

27.2.0-rc4

### OBS Studio Log URL

n/a 

### Expected Behavior

OBS shouldn't change setting in OS or in other software after closing. 

### Current Behavior

OBS is limiting other software and especially running on second monitor in my case Cycling 7 Max8 / Jitter to 60fps even after closing OBS. 
I have tried multiple settings it seemed to set it globally in my mac.
Once i have OBS in focus fps jumps back to 120 fps once in Max / Jitter its 60fps this happens after installing OBS on my system. I cant find a way to undo it. Removed OBS from my sytem issue is still there. 

### Steps to Reproduce

1.  Install Max 8 run any patch at 120 fps  https://cycling74.com/downloads
2. Install Syphon http://syphon.v002.info/recorder/
3. Run the same patch and see what fps it produces now, should be 120 fps.
4. Install OBS on your system 
5. Run the same patch and see fps. Its 60 fps here.  
6. Click on OBS or Syphon window. Should be 120 fps click on Max window its 60 fps. 
This happens only after installation of OBS. And once quitting Syphon and OBS Max is capped at 60 fps now.
7. Quit OBS and run the same patch should be 120 and its 60 fps still.
8.  Uninstall OBS run the same patch and see what fps you are getting. Im still getting 60 fps.

### Anything else we should know?

Would appreciate any help or commands I can try to undo what OBS have set somewhere in the OS?

**Comment by WizardCM** [comment]
Check the Advanced tab of the Settings window, it contains an option for "Disable macOS V-Sync".

**Comment by koshimazaki** [comment]
@WizardCM thanks so much! that worked. Also, using external monitor limits to 60fps due to refresh rate. Cheers!

**Comment by PatTheMav** [comment]
Interesting that it works for this user, while it doesn't seem to have any effect on my machine.

**Comment by kkartaltepe** [comment]
Should this be closed? It seems like the fix already exists and works(?)

**Comment by Fenrirthviti** [comment]
Going to close, if there is new information, feel free to post and we can consider reopening.
