### ISSUE TITLE
OBS 27.1.3  sound issues with Yamaha MG10XU 

### ISSUE THREAD

**Issue by Clelest** [obsproject/obs-studio#5939]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/47RUmkCOumIT40Sd

### Expected Behavior

My OBS (and also Discord) have some problem when I use my Yamaha MG10XU as audio source. When I have my new PC, all my windows sound (like spotify) is stuttering and my mic (as input with my soundboard MG10XU) too. This not happen when I use my Realtek output.

### Current Behavior

All my Windows sound stuttering with my Yamaha MG10XU as audio output/input. I observe that the frequency my sound stutter is according to which scene is currently use. As you see in this vidéo [https://youtu.be/nRXNjXlkINo](url), my first scene use many media source, and my last have only 1 screen capture, and my sound stutter less when I use my last scene.

### Steps to Reproduce

1. I just launch OBS : there is no filter on the sound, just some video source, many or just one.

### Anything else we should know?

I tried everything I have search on the internet : change my MG10XU drivers, change OBS version, uninstall and install drivers, uninstall windows to restart OBs from scratch. It don't work when I use Discord too, but it perfectly work when I use Audacity for recording with my mic, and when those both soft aren't open (OBS and Discord), my Windows sound don't stuttering at all. There is no difference between my audio sample size.
I really don't understand, hope you can find something, and thank you by advance.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
