### ISSUE TITLE
Apple VT Encoders not following the set bitrate on fractional FPS on Apple Silicon computers 

### ISSUE THREAD

**Issue by hardy-yan** [obsproject/obs-studio#5948]
### Operating System Info

Other

### Other OS

macOS 12.1

### OBS Studio Version

27.2.0-rc4

### OBS Studio Log URL

https://obsproject.com/logs/zo_fuxSWjuI73YHL

### Expected Behavior

The streaming/recording output should follow the set bitrate.

### Current Behavior

The output bitrate seems to be not limited, as shown in the OBS Stats window.

<img width="1092" alt="Screenshot 2022-02-12 at 2 50 51 PM" src="https://user-images.githubusercontent.com/83881426/153704368-3f3639bb-5cf6-41db-b964-c63c99a4c632.png">

Also, the output shows the same issue, 115MB in 10 seconds, averaged around 90Mbps.

### Steps to Reproduce

1. Use a fractional FPS In OBS, I tested with 29.97 or 59.94.
2. Set streaming/recording encoder to VT Software/Hardware (the issue affects both to a different extent)
3. Set bitrate to a normal bitrate, e.g. 1000-5000 kbps
4. Add a source with a good amount of motion, panning shots will exaggerate the issue.
5. Start streaming or recording.
6. Look at the bitrate on the bottom right corner for streaming, or in the Stats window for recording.

### Anything else we should know?

The issue was reproduced on two setups, a fresh setup of macOS and OBS on MacBook Pro (16-inch, 2021) equipped with M1 Max.
MacBook Pro (13-inch, 2020) equipped with M1 was tested on my friend's installation w/o clean install.

VT Software has less of an issue but still seems uncapped.

I have previously tested with plugins installed, GStreamer plugin, which allows encoders to be used with single-digit bitrate. I tried with 4. It seems the encoder has interpreted the value as 4Mbps, and it outputted a 4Mbps stream.

**Comment by hardy-yan** [comment]
I didn't mean it should output as CBR, with fractional framerate the encoder seems to misinterpret the settings as I mentioned.
With the bitrate set to 4000 Kbps, VBR encoder that works properly should not output data as high as 100 Mbps.

And also, integer FPS works perfectly fine on my machine.

**Comment by dodgepong** [comment]
Regardless, this strikes me as a bug with VT itself, not OBS.

**Comment by RytoEX** [comment]
Fractional FPS in VT in OBS has some quirks that we've been trying to investigate, and we're not yet sure what the root of the issue is.  See also #2760.

**Comment by RytoEX** [comment]
According to your log file, you haven't enabled the "Limit bitrate" setting, which means that VT has no hard bitrate limit to obey. If you want to cap the bitrate, you must enable this setting. The VT encoder can still peak higher than the cap that you set, but only momentarily for periods shorter than the window duration.

**Comment by hardy-yan** [comment]
It's not behaving properly even with the Limit Bitrate settings being set.

The 1st screenshot here shows that I've set 2500 kbps as the bitrate and 3000 kbps as the limit, and the encoder renders out a 50 Mbps stream under 29.97 FPS.

<img width="617" alt="Screenshot 2022-02-13 at 10 45 41 AM" src="https://user-images.githubusercontent.com/83881426/153736082-5d203f75-f24b-47f2-b75d-a7c66fced123.png">

Meanwhile, with all other settings kept intact, changing the FPS to 30.00 fixed the issue I have mentioned.

<img width="658" alt="Screenshot 2022-02-13 at 10 46 06 AM" src="https://user-images.githubusercontent.com/83881426/153736122-06c71148-9991-400f-b3db-2060c8f9fbd5.png">

**Comment by RytoEX** [comment]
Have you verified the output files' size in Finder?  This may be the same core/underlying issue as #2760, so I'm hesitant to reopen this just yet, as we've discovered some weirdness with fractional FPS with VT in general.

**Comment by hardy-yan** [comment]
Yes, I have verified the output of those two recordings, hugely different file sizes.

And I would like to mention that this issue is only occurring on M1 Macs, I have tried the same setup on my old Intel Mac (albeit with an older version of macOS) the bitrate was fine. #2760 is affected on both architectures AFAIK.

<img width="570" alt="Screenshot 2022-02-13 at 1 55 57 PM" src="https://user-images.githubusercontent.com/83881426/153741228-a937a983-a1a6-4d51-90dd-5ccb30ae5415.png">

**Comment by RytoEX** [comment]
I will tentatively reopen this for now, but I still suspect that both #2760 and this have the same core/underlying issue. Could you please provide some small sample files that we can analyze?

**Comment by hardy-yan** [comment]
Here is the log of the testing session.
https://obsproject.com/logs/GitLx7_jMC4gZZyW

And recorded files here.
https://drive.google.com/drive/folders/1BPm58s3vqITXnGQHp5HOGHFc5oZqbcE9?usp=sharing

2022-02-14 22-00-39.mov - 29.97fps
2022-02-14 22-01-00.mov - 30fps

I have only changed the FPS for the 30fps recording.
