### ISSUE TITLE
Filter resize grip breaks the view if dragged all the way to the top

### ISSUE THREAD

**Issue by iesvme** [obsproject/obs-studio#5959]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.0

### OBS Studio Log URL

https://obsproject.com/logs/fJvtzkwY56p4gdTt

### Expected Behavior

The split window ratio of the Property should be the same as the Filters, both 1:1 size.

### Current Behavior

The filters' window is frozen and cannot be resized.

### Steps to Reproduce

1. Add a source of Text (GDI+)
2. Click Filters of it
3. Add a Color correction
4. Adjust its window size upwards
5. Frozen
![动画](https://user-images.githubusercontent.com/16969250/153995099-e29c4943-4ee0-4948-8d67-55559fd9133b.gif)

**Comment by tt2468** [comment]
Can reproduce on Windows 10
