### ISSUE TITLE
27.2 Recording via NDI works fine when using SVT-1, but is unusable using x264 Slow preset from 27.1.3 2 PC setup

### ISSUE THREAD

**Issue by zombiefaace** [obsproject/obs-studio#5960]
### Operating System Info

Other

### Other OS

Windows 10 streaming PC/Windows 11 Gaming PC

### OBS Studio Version

27.2.0

### OBS Studio Log URL

https://obsproject.com/logs/m_zIhlFx7j8ui3KB

### OBS Studio Crash Log URL

https://obsproject.com/logs/X-ZI6b7Ed1ysGxfC

### Expected Behavior

x264 recording to function as it did in version 27.1.3 over NDI using the Slow Preset at 8000 bitrate.

### Current Behavior

When attempting to record with x264 on the Slow preset at 8000 bitrate from the streaming PC over NDI the playback of the recording acted as if there were severe dropped frames and the playback wasn't smooth. The gaming PC specs are a Ryzen 7 3700x 32GB of RAM, and an Nvidia RTX 2080TI. I was also using the Nvidia Broadcast software version 1.3.0.45 for the AI green screen effect on the gaming PC. The streaming PC specs are Ryzen 9 3950x, 32GB RAM, and a Nvidia GTX 1050TI. 

When using the SVT-1 preset with it set on level 7 I was able to record just fine with no issues other than small text looking distorted on version 27.2 (I figured it was needing optimization/maturity since the encoder itself is brand new) and I didn't seem to have any dropped frames or issues with the playback quality. After about an hour of troubleshooting on the OBS Discord it was decided to try downgrading back to version 27.1.3. After doing so x264 recording went back to normal operation.

### Steps to Reproduce

1. Install OBS 27.2 on 2 PC's
2. Use NDI for OBS to record via x264 Slow
3. Watch playback
...

### Anything else we should know?

Streaming PC is running Windows 10 Pro
Gaming PC is running Windows 11 Pro

The crash log link is actually the log from the streaming PC.
The Studio Log link is the log from the gaming PC.
All WASAPI errors were cleared before the downgrade and problem still persisted.
Did attempt disabling the RTX AI Greenscreen effect and the issue persisted.
Tried disabling the camera in OBS and the issue persisted.

https://send.tresorit.com/a#uGL1jNeMiXjSeY0A9m_mhQ
SVT-1 and x264 recording can be found here.
SVT-1 recording is the 240MB file.
x264 recording is the 59MB file.

Both PC's had Game Mode enabled, both PC's had OBS set to Run As Admin. Both PC's were also freshly rebooted to troubleshoot the issue.

**Comment by RytoEX** [comment]
Please attempt to reproduce this with the following changes separately:
1. Do not use any custom x264 options.
2. Use something simple like a Media Source in the OBS instance used for encoding.

Please provide log files for both attempts.

**Comment by zombiefaace** [comment]
I removed NDI by making the streaming PC a single PC setup.

With and without custom x264 options on the slow preset the issue did not occur.
I would say this issue is tied to NDI and not x264. Thanks for all the help.
