### ISSUE TITLE
OBS Do not capture LOST ARK after update to 27.2

### ISSUE THREAD

**Issue by panoc** [obsproject/obs-studio#5961]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.0

### OBS Studio Log URL

https://obsproject.com/logs/F9dK0FNyol_1A_Ve

### Expected Behavior

Should be able to capture game Lost Ark in Capture Game mod

### Current Behavior

Does not capture it, it captures the first frame and then black screen.
Other games i tested worked just fine.

### Steps to Reproduce

1.Open OBS and set game capture source to Lost Ark game
2.Open Lost Ark Game
3.No capture
...

**Comment by derrod** [comment]
You added multiple game capture sources for the same game, that won't work.

Also GitHub isn't for support, use our forums or Discord.

**Comment by panoc** [comment]
Thank you for your reply ! Really appreciate it !
