### ISSUE TITLE
OBS freezes for a short time under Windows if using a dropdown in interact mode (might be site specific)

### ISSUE THREAD

**Issue by FaeyUmbrea** [obsproject/obs-studio#5966]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.0

### OBS Studio Log URL

https://obsproject.com/logs/RrT4VtvNGeUKigLh

### Expected Behavior

Choosing an option on the Dropdown should not halt the OBS Process at all

### Current Behavior

OBS freezes for about a Minute after modifying the Dropdown menu

### Steps to Reproduce

1. Launch OBS 
2. Add a browser source pointing to the relevant site
3. Open Interact mode
4. Modify the Dropdown

### Anything else we should know?

This behaviour might be specific to either the particular Software I am using which is FoundryVTT, or it might be specific to WebGL Processes. 
You can try this by using https://demo.foundryvtt.com/join as the URL for your browser source.

The Site works perfectly fine in Custom Dock Mode aswell, my guess would be that it has something to do with rendering the Dropdown itself.

**Comment by Fenrirthviti** [comment]
I can confirm this, but I'm not sure if this is a supported use case for browser sources. Interact is typically a last resort option when there is no other solution, and I do recall dropdown menus not working properly more or less by design as they're not intended to be used in the context of the browser source. I would expect capturing a browser window for this page would be a better solution. however this is at least confirmed.

**Comment by FaeyUmbrea** [comment]
Thank you for confirming my issue. The Dropdown itself is not required to operate this site, only the selection box it is attached to. And the operation of this menu part is only necessary once every few days or so to log into the relevant account for streaming. The entire remaining Setup is automated through the website. 

I have done some further analysis and it seems that WebGL crashes in this usage scenario. If the WebGL crash can be prevented, that would solve the issue for me.

**Comment by rbl047** [comment]
This new OBS Studio version freezes my whole computer after some seconds. I had to go back to the old version.

**Comment by Fenrirthviti** [comment]
> This new OBS Studio version freezes my whole computer after some seconds. I had to go back to the old version.

This has nothing to do with the issue being discussed here. We're aware of this freeze, it appears to be a display driver bug and are actively working with the appropriate vendors to identify root cause. Please use our Discord for more status updates.

**Comment by rbl047** [comment]
> an't confirm OBS itself freezing (at least for me), but I do see all browser instances freeze for a time (at least a minute, for some reason). Running CEF in verbose provides no additional information, but disabling hardware acceleration seems to mitigate the freeze. UFO Test seems



> > This new OBS Studio version freezes my whole computer after some seconds. I had to go back to the old version.
> 
> This has nothing to do with the issue being discussed here. We're aware of this freeze, it appears to be a display driver bug and are actively working with the appropriate vendors to identify root cause. Please use our Discord for more status updates.

Sorry.

**Comment by WizardCM** [comment]
@FaeyUmbrea are you still seeing this in 27.2.1?

**Comment by FaeyUmbrea** [comment]
Bug has been resolved for me! @WizardCM 
Thanks for the headsup, I missed the 27.2.1 release. Closing!
