### ISSUE TITLE
Audio Output not working on Windows 8.1/OBS 27.2

### ISSUE THREAD

**Issue by prgmitchell** [obsproject/obs-studio#5967]
### Operating System Info

Windows 8.1

### OBS Studio Version

27.2.0

### OBS Studio Log URL

https://obsproject.com/logs/zH_BrN7WdA5QS8RQ

### Expected Behavior

OBS should detect an audio output source and show the green bar moving in the audio mixer.

### Current Behavior

OBS is not detecting audio coming from an audio output source

### Steps to Reproduce

1. Add audio output source in a blank scene collection
2.
3.
...

### Anything else we should know?

The audio source works without issue on 27.1.3. I am submitting this report on behalf of the multiple people in the audio support channel experiencing this issue, all on Windows 8.1.

**Comment by WizardCM** [comment]
Apparently this also happens with the global Desktop Audio source, either on the default setting or with a specific device selected. OBS *reports* that it initialised the device currently, but doesn't display/capture any audio. Input devices works fine.

`22:16:20.229: WASAPI: Device 'Headphones (Arctis 7 Game)' [48000 Hz] initialized`

**Comment by WizardCM** [comment]
Current running theory is that this bug was introduced in the below PR, which contains 16 commits. I am personally unsure which could have introduced it.

* #5269
