### ISSUE TITLE
27.2.0 RC4 Crash on OBS Close

### ISSUE THREAD

**Issue by thelegendtubaguy** [obsproject/obs-studio#5968]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.2.0 RC4

### OBS Studio Log URL

https://obsproject.com/logs/vl2VsqBvO7i2ATHu

### OBS Studio Crash Log URL

https://obsproject.com/logs/3ri-64IaPJIFHp4c#logFile

### Expected Behavior

I had stopped stream and tried to exit OBS.

### Current Behavior

Upon trying to close OBS, a dialog came up saying it had crashed.  I realize this is for RC4 and not the release version.  I'm going to update to 27.2 release version, so if you just want to close this, that's fine by me.  Just wanted to make sure I filed this since I got an actual OBS crash.

### Steps to Reproduce

I just tried to close OBS.

### Anything else we should know?

My computer is running at very high CPU usage even though I'm using nvenc.  I have a suspicion it's an issue with running two CamLink Pros.  I point this out just to say that I'm aware of the high usage and OBS's complaints about it.

**Comment by Fenrirthviti** [comment]
You have a significant number of third party plugins, any of which could be responsible for this kind of crash. I'd recommend making sure they are all updated.

If you need further assistance, I'd recommend the support channels on our Forums or Discord. https://obsproject.com/help
