### ISSUE TITLE
My recordings for DHEWM 3 (A source port for Doom 3) are frozen the whole recording

### ISSUE THREAD

**Issue by Sixteen60** [obsproject/obs-studio#5970]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.0

### OBS Studio Log URL

https://obsproject.com/logs/n7csXundrK4PdQFy

### Expected Behavior

I thought I would be able to get gameplay like this. (Played on Original Doom 3 for show)

https://user-images.githubusercontent.com/99849136/154382662-7f5269a0-c41e-4b5e-8a64-b1812bcd16da.mp4

### Current Behavior

Instead, I get this when I record DHEWM 3.

https://user-images.githubusercontent.com/99849136/154382276-b0d30766-3977-4fe6-a817-2c90f200c26f.mp4

### Steps to Reproduce

1. I started OBS Studios
2. I started up DHEWM 3
3. Hit record
4. Save record
5 View record and then it appears as a solid picture every time
...

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
