### ISSUE TITLE
For 27.2.0, Right click menu still captured when set Hide OBS  windows

### ISSUE THREAD

**Issue by kirahan** [obsproject/obs-studio#5971]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.0

### OBS Studio Log URL

https://obsproject.com/logs/7XlUNWHQoa0fCmUM

### Expected Behavior

When active "Hide OBS windows from screen capture",  the main window of  OBS will not be captured, but right-click popup menu also captured, the top menu bar also captured
![image](https://user-images.githubusercontent.com/7088329/154397227-c3b59d08-4de5-4259-a342-15f4c75d67ce.png)
![image](https://user-images.githubusercontent.com/7088329/154397438-eebde530-e734-4e6d-bb8b-b25ac3cb0f84.png)

### Current Behavior

all right-click menu and menu bar should not be captured when setting "Hide OBS windows from screen capture"

### Steps to Reproduce

reboot obs and reinstall obs

**Comment by WizardCM** [comment]
This is expected behaviour. The alternative is unpredictable black rectangles. We believe it's a bug on the Windows API side, or a side effect of how Qt renders context menus.
