### ISSUE TITLE
Recording with stream encoder has wrong bit rate

### ISSUE THREAD

**Issue by akiirui** [obsproject/obs-studio#5975]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/nfDyUzhFpddz-ZLV

### Expected Behavior

Start recording a few minutes and stop it. Run `mediainfo` to check video bit rate:
> It shows high bitrate value > 100Kbps

### Current Behavior

Start recording a few minutes and stop it. Run `mediainfo` to check video bit rate:
> It shows fixed bitrate value = 100Kbps (the CBR bitrate value)

### Steps to Reproduce

Output - Streaming:
- Encoder: x264
- Rate Control: CRF (and set CBR with bitrate 100Kbps)
- CRF: 0

Output - Recording:
- Encoder: (Use stream encoder)

1. Start recording a few minutes
2. Stop
3. Check video bitrate

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by akiirui** [comment]
> This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.
> 
> Thank you!

This is a bug report not a support request (

**Comment by akiirui** [comment]
streamEncoder.json

```json
{"bitrate":100,"crf":0,"rate_control":"CRF"}
```

Recording encoder is "(Use streaming encoder)"

mediainfo output:

```
Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4.2
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 10 s 0 ms
Nominal bit rate                         : 100.0 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 60.000 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.001
Writing library                          : x264 core 164 r3081 19856cc
Encoding settings                        : cabac=1 / ref=1 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=2 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=0 / me_range=16 / chroma_me=1 / trellis=0 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=0 / threads=24 / lookahead_threads=8 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=1 / keyint=120 / keyint_min=12 / scenecut=40 / intra_refresh=0 / rc_lookahead=10 / rc=cbr / mbtree=1 / bitrate=100 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / vbv_maxrate=100 / vbv_bufsize=100 / nal_hrd=none / filler=1 / ip_ratio=1.40 / aq=1:1.00
Default                                  : Yes
Forced                                   : No
Color range                              : Full
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
```
