### ISSUE TITLE
27.2 Browser Source No Audio in Windows 10 VM's

### ISSUE THREAD

**Issue by Wolbaz** [obsproject/obs-studio#5978]
### Operating System Info

Windows 10

### Other OS

Unraid KVM

### OBS Studio Version

27.2.0

### OBS Studio Log URL

https://obsproject.com/logs/q-q6PUt037hRaEOY

### Expected Behavior

Browser sources play audio through stream and recording with monitoring and output selected.

### Current Behavior

No audio is played or monitored when audio alerts sent to browser sources. No Indication of audio other than the audio bar in the mixer switching to stereo. Same issue on 2 currently running VM's and only fixed by downgrading to 27.1.3. Spun up another VM to verify VM exclusive.

### Steps to Reproduce

1. Spin up fresh Windows 10 VM in Unraid
2. Install 27.2 OBS in normal or portable mode
3. Add browser source and check control audio via OBS
4. Send test alert, no audio is given but the mixer turns from mono to stereo and the two squares appear but do not light up.
...
![unknown](https://user-images.githubusercontent.com/69988407/154764181-e70b5cd1-9780-433b-bdfb-ea6061816654.png)

**Comment by Fenrirthviti** [comment]
OBS is not supported running in a VM environment, as OBS expects direct hardware access. You can try asking in our Discord, but as this is not an officially supported environment, we do not consider this a bug.
