### ISSUE TITLE
Video audio on OBS does not come out to zoom

### ISSUE THREAD

**Issue by Carlos-Kronem** [obsproject/obs-studio#5984]
### Operating System Info

macOS 12.0

### OBS Studio Version

27.2.0

### OBS Studio Log URL

https://obsproject.com/logs/e20-XcTXqvRb31re

### Expected Behavior

VIDEO AUDIO ON OBS (27.2.0) DOES NOT COME OUT TO ZOOM (5.9.3) ON MAC OS MONTEREY M1

### Current Behavior

VIDEO AUDIO ON OBS (27.2.0) DOES NOT COME OUT TO ZOOM (5.9.3) ON MAC OS MONTEREY M1 AFTER OBS UPDATE TO VERSION 27.2.0

### Steps to Reproduce

1.OPEN ZOOM
2.OPEN OBS
3.PLAY VIDEO WITH AUDIO
4 SOUND NOT COME OUT ON ZOOM

### Anything else we should know?

<img width="904" alt="Captura de Tela 2022-02-19 às 09 42 00" src="https://user-images.githubusercontent.com/52799598/154801248-bb1c26b8-9da9-413a-926d-066686a19bc0.png">

**Comment by tehbasshunter** [comment]
Assuming you're Torvizz00 on discord I answered you there.

**Comment by tehbasshunter** [comment]
Apple does not have a method that allows desktop audio capture. Use one of these options to do that.

https://obsproject.com/forum/resources/505/
https://obsproject.com/forum/resources/1191/

**Comment by dodgepong** [comment]
OBS does not support a virtual audio output at this point. Given that this is a feature request, you can show your support for this feature here: https://ideas.obsproject.com/posts/965/additional-aux-send-monitor-channel-or-virtual-audio-output
