### ISSUE TITLE
Memory-Leak with FPS drops in OBS and following PC Crash while recording a game

### ISSUE THREAD

**Issue by ERZMAGIERSKYRIM** [obsproject/obs-studio#5987]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.0

### OBS Studio Log URL

https://obsproject.com/logs/OvC0oPXY3ndwqSIT

### Expected Behavior

A not crashing System and a stable FPS in OBS.

### Current Behavior

After 10-20 min recording and streaming the OBS-Window with NDI to another system it crashed. I reproduced it many times with Dying Light 2 and Cyberpunk 2077. I looked it up in the log files and it says something about a 'memory leak'.

### Steps to Reproduce

1.
2.
3.
...
Just start recording a game (in my way DL2 and Cyberpunk2077) and let it 10-20 min running. Than the PC will crash.

### Anything else we should know?

I hope I described it in a understandable way, my english is really bad (sry).

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
