### ISSUE TITLE
OBS Crash on scene change ( 27.1 +)

### ISSUE THREAD

**Issue by theweirdlobster** [obsproject/obs-studio#5988]
### Operating System Info

Windows 10

### OBS Studio Version

27.1.3

### OBS Studio Version (Other)

27.1.3 & 27.2.0

### OBS Studio Log URL

https://obsproject.com/logs/mjytt4NSTWknUEx7

### OBS Studio Crash Log URL

https://obsproject.com/logs/MtGvaZ-fwlKKtAs4

### Expected Behavior

Trying to switch into any other Scene collection 

### Current Behavior

OBS stops responding as soon as i click the other scene collection i want to use. I miraculously managed to change into my main scene collection a couple of days ago, but i cant change into any of my scene collections. I usually have to Force Quit obs, than relaunch, and it brings me back into the scene i am originally in

### Steps to Reproduce

1. Launch OBS
2. Scene Collection > Click on any of my scene collections
3. OBS Stops responding & i get the Windows pop-up of 'OBS has stopped responding. Force quit or Wait for the program to respond"
...

### Anything else we should know?

Here is a screenshot of the crash https://imgur.com/s6DrD9h

**Comment by WizardCM** [comment]
This crash is caused by an outdated [win-capture-audio](https://obsproject.com/forum/resources/win-capture-audio.1338/) plugin. Update to 2.2.2.
