### ISSUE TITLE
After 27.2 upgrade window capture doesn't appear

### ISSUE THREAD

**Issue by liloumuloup** [obsproject/obs-studio#5989]
### Operating System Info

Ubuntu 20.04

### OBS Studio Version

27.2.0

### OBS Studio Log URL

https://obsproject.com/logs/KnBU_H5UT_AOD7wC

### Expected Behavior

Access to Window Capture without being `sudo`. I had no problem to do it in 25 version.

### Current Behavior

When i try to add a new Window Capture, the button doens't appear. I had a window capture before and tried to delete it, to recreate it because it didn't showed my game anymore.

![image](https://user-images.githubusercontent.com/4968531/154862126-ba24ebcf-53fe-4fc3-96d8-fab959074c3e.png)

I found out that, when i try to launch OBS Studio with sudo, this button appears but it's a different user so i don't have access to my settings and overlay parameters.

![image](https://user-images.githubusercontent.com/4968531/154862229-e691231b-a799-4d4e-b27b-4cd86938c893.png)

### Steps to Reproduce

1. Install 25 version
2. Add a scene with windows capture in it
3. Upgrade to 27.2 from 25 version (couldn't remember the exact version, sorry)
4. Check your window capture

**Comment by kkartaltepe** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

**Comment by liloumuloup** [comment]
This is not a support question. This is a bug. OBS worked perfectly before the upgrade.
