### ISSUE TITLE
Steps to actually compile on Linux?

### ISSUE THREAD

**Issue by LiamDawe** [obsproject/obs-studio#60]
Hi guys, Liam from GamingOnLinux here, I see there instructions haven't yet been made.

What steps do I need to do to compile it on Linux?

**Comment by Xaymar** [comment]
For debian based systems, one could use [deb-multimedia](http://deb-multimedia.org), which provides the required packages from ffmpeg. However, i haven't managed to compile on debian so far, so i don't know if they work.
