### ISSUE TITLE
Pipewire window capture doesn't use transparency

### ISSUE THREAD

**Issue by micahscopes** [obsproject/obs-studio#6000]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

27.2.0

### OBS Studio Log URL

---

### OBS Studio Crash Log URL

---

### Expected Behavior

I'm using a window with a transparent background and expected the pipewire window capture source to include the alpha channel

### Current Behavior

The pipewire window source is composited with a black background.

### Steps to Reproduce

1. open a window with an alpha channel
2. add the window as a pipewire capture source
3. add another layer below
4. notice that a black background is added to the window with the alpha channel

### Anything else we should know?

I used shadertoy-rs with the command:
```shadertoy --texture0 texture-with-alpha.png get ltjGDK -r```

where `texture-with-alpha.png` is a texture with an alpha channel

**Comment by kkartaltepe** [comment]
please see #5796
