### ISSUE TITLE
Mac Build still not including symlinks to linked librarires

### ISSUE THREAD

**Issue by QuinnyPig** [obsproject/obs-studio#6002]
### Operating System Info

macOS 12.0

### OBS Studio Version

27.2.1

### OBS Studio Log URL

https://shitposting.pictures/tv25LVvfEZLte

### Expected Behavior

The various plugins (in this case, obs-ssp to work when  `/Applications/OBS.app/Contents/Frameworks/libavcodec.58.dylib` is found.

### Current Behavior

instead `/Applications/OBS.app/Contents/Frameworks/libavcodec.58.134.100.dylib` is hanging out there instead without a symlink as attempted to get fixed in the commit found as https://github.com/obsproject/obs-studio/commit/7a5bffc0a66980113c32dbed123b3928d38abe8b.

https://shitposting.pictures/seQHnX8YpVI1T shows the current contents of the 21.2.1 hotfix release Framework page.

### Steps to Reproduce

1. Install the latest OBS on a mac
2. Attempt to use any plugin that requires the short name of the linked library; obs-ssp is just one example.
3. Loss, the exact opposite of "profit!"

**Comment by QuinnyPig** [comment]
While certainly not advised, this workaround *does* fix it temporarily:
```
sudo ln -s /Applications/OBS.app/Contents/Frameworks/libavcodec.58.134.100.dylib /Applications/OBS.app/Contents/Frameworks/libavcodec.58.dylib
sudo ln -s /Applications/OBS.app/Contents/Frameworks/libavdevice.58.13.100.dylib /Applications/OBS.app/Contents/Frameworks/libavdevice.58.dylib
sudo ln -s /Applications/OBS.app/Contents/Frameworks/libavfilter.7.110.100.dylib /Applications/OBS.app/Contents/Frameworks/libavfilter.7.dylib
sudo ln -s /Applications/OBS.app/Contents/Frameworks/libavformat.58.76.100.dylib /Applications/OBS.app/Contents/Frameworks/libavformat.58.dylib
sudo ln -s /Applications/OBS.app/Contents/Frameworks/libavutil.56.70.100.dylib /Applications/OBS.app/Contents/Frameworks/libavutil.56.dylib
```

**Comment by RytoEX** [comment]
> Can confirm. Caching issue on the build system ?

Caching is not the issue.  The build script that was changed in #5986 is not currently used on CI.  It can be used for local builds.  Please check if the build artifacts from #6006 resolve your issue.

**Comment by QuinnyPig** [comment]
Can confirm that the artifact from that build solves the problem: 
<img width="823" alt="image" src="https://user-images.githubusercontent.com/489170/155213701-ebed92ae-44dd-4c2a-8ce4-56a15c8d1346.png">
