### ISSUE TITLE
Special Unicode characters in Browser source not displaying correctly (Worked in 27.1)

### ISSUE THREAD

**Issue by noggynoggy** [obsproject/obs-studio#6007]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.1

### OBS Studio Log URL

https://obsproject.com/logs/u13rbaazDW7w7P-5

### Expected Behavior

Special characters like , , or  being displayed correctly (characters from [nerdfonts.com](https://www.nerdfonts.com/)) like in Chrome
![image](https://user-images.githubusercontent.com/50501527/155194495-1d18623d-f998-4c13-b09f-874452578458.png)

Firefox, 
![image](https://user-images.githubusercontent.com/50501527/155194583-64387875-8b27-48db-8a84-a3003307a792.png)

or OBS 27.1.3 
![image](https://user-images.githubusercontent.com/50501527/155194806-fa4c83d6-c64d-47cf-97b1-6e585905a371.png)

### Current Behavior

Special characters like , , or  being displayed incorrectly (characters from [nerdfonts.com](https://www.nerdfonts.com/)) like in Internet explorer
![image](https://user-images.githubusercontent.com/50501527/155195120-7737c73f-33f3-4429-87e7-3d7fb5a57f71.png)

and since the new update OBS 27.2.1
![image](https://user-images.githubusercontent.com/50501527/155194394-66e96ad5-541f-400f-b5c2-f31802896cd9.png)

### Steps to Reproduce

1. Add browser source (local file) with special characters
2. no custom css (idk if thats important)

### Anything else we should know?

the html code of the `stringmetest.htm` is 

```html
<!DOCTYPE html>
<html>
</meta>
<style>
    @font-face {
        font-family: 'casnf';
        src: url(fonts/casnf.woff2);
    }

    .n {
        font-family: 'casnf';
        font-size: xx-large;
        color: #ffffff;
    }
</style>

<body>
    <p class="n"><span style="color:#21a1e4">this is an icon from nerdfonts:  </span> <span style="color:#21a1e4"></span></p>
</body>

</html>
```

the `casnf.woff2` is CascaydiaCove from nerdfonts.com

**Comment by notr1ch** [comment]
Your HTML file is missing a `<meta charset>` tag, you'll need to specify UTF-8 if you want to use UTF-8 codepoints.
