### ISSUE TITLE
v27.2.1 breaks Windows 10 Enterprise N LTSC - MFPlat.DLL not found

### ISSUE THREAD

**Issue by Zamiell** [obsproject/obs-studio#6008]
### Operating System Info

Windows 10 Enterprise N LTSC

### OBS Studio Version

27.2.1

### OBS Studio Log URL

n/a (can't open program at all)

### Expected Behavior

I expect the program to open.

### Current Behavior

The program refuses to open.

### Steps to Reproduce

Install the latest version of OBS on a fresh copy of Windows 10 Enterprise N LTSC.
Observe that the program refuses to open and displays the following error:
```
MFPlat.DLL not found
```

### Anything else we should know?

[As per Microsoft](https://support.microsoft.com/en-us/topic/media-feature-pack-for-n-editions-of-windows-10-version-1607-b657cb70-33e7-1f11-7119-3b4b50be4e89), the N editions do not include Windows Media Player, Skype, or certain preinstalled media apps (Music, Video, Voice Recorder). Thus, I believe this error has something to do with that.

Note that previous versions of OBS Studio worked just fine on this operating system, so this might have been caused by a recent library update or something along those lines.

**Comment by Zamiell** [comment]
Why is this a requirement of OBS in the latest version? Note that the entire point of installing Windows N in the first place is that you don't have to install Windows Media Player, so this is not a viable solution.

**Comment by RytoEX** [comment]
> Why is this a requirement of OBS in the latest version? Note that the entire point of installing Windows N in the first place is that you don't have to install Windows Media Player, so forcing Windows N users to install Windows Media Player is not a viable solution.

To be clear, this isn't a requirement of OBS itself.  This is a requirement from FFmpeg as a result of our upgrade from FFmpeg 4.2 to 4.4.1 between OBS Studio 27.1.3 and 27.2.0.  FFmpeg 4.3 added a MediaFoundation encoder wrapper which causes it to require that DLL.

**Comment by derrod** [comment]
> Why is this a requirement of OBS in the latest version? Note that the entire point of installing Windows N in the first place is that you don't have to install Windows Media Player, so forcing Windows N users to install Windows Media Player is not a viable solution.

The media feature pack itself does not include media player etc. It just provides the mediafoundation features that some media applications can use to handle various tasks.

**Comment by derrod** [comment]
(clicked the wrong button don't mind me)

**Comment by rstrickstrock** [comment]
I installed the Media Feature Pack (and also reinstalled OBS) and still get this error message

**Comment by Zamiell** [comment]
Ok, thank you derrod for responding. I will close this issue now, since it sounds like reverting FFmpeg is not desirable.
