### ISSUE TITLE
UI: Source name is sometimes not editable when renaming

### ISSUE THREAD

**Issue by norihiro** [obsproject/obs-studio#6015]
### Operating System Info

Ubuntu 20.04

### OBS Studio Version

27.2.1

### OBS Studio Log URL

https://obsproject.com/logs/K3Tdn4yKT3ylXtFs

### Expected Behavior

The name of the selected source becomes editable.

### Current Behavior

Sometimes the name of the selected source does not become editable.

### Steps to Reproduce

1. Click an item in the list of `Sources`.
2. Right click.
3. Click `Rename`
...

**Comment by norihiro** [comment]
I've recorded my screen.
At around 4 second, the name became editable.
At around 8 second, the name didn't become editable.

https://user-images.githubusercontent.com/780600/155322466-a0d479ef-fcc2-417f-a493-e46e32e047c9.mp4

This issue also happens with older versions such as 27.1.3.

**Comment by kkartaltepe** [comment]
Somehow i replicated this exactly once. I think there are more problems here though. After attempting to rename a source I can no longer drag and drop it...

**Comment by cg2121** [comment]
@norihiro could you confirm if this is still the case? I can't reproduce it on 22.04, so it might be a Qt5 problem.

**Comment by norihiro** [comment]
> it might be a Qt5 problem

I compared obs-studio a5468cfe with Qt6 and Qt5 on Fedora 36. The issue is observed with Qt5 only so far. So, I suspect it's a Qt5's problem.
