### ISSUE TITLE
UI - Improve visibility/contrast in Advanced Audio Properties > Tracks

### ISSUE THREAD

**Issue by fefo-dev** [obsproject/obs-studio#6016]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.1

### OBS Studio Log URL

https://obsproject.com/logs/g9lB3fmp2a4NB4q2

### Expected Behavior

Making out how your track setup is from a quick glance

### Current Behavior

As the ammount of sources add up it can become hard to understand which is enabled in which track due to how poorly the checkmarks contrast whitin the info density

### Steps to Reproduce

1. Add several sources with audio properties (Audio Input Capure, etc)
2. Setup those tracks at will in Advanced Audio Properties > Tracks
3. Close Advanced Audio Properties
3. Change each added source name to change its position on the list
4. Reopen Advanced Audio Properties and check try to identify what sources are in a track

### Anything else we should know?

I did a quick mockup by changing the tick-style checkbox to a fillbox, notice how easier is to quickly identify enabled sources in a track:

Present
![](https://i.imgur.com/6ksa2S5.png)

Mockup
![](https://i.imgur.com/8utYOaX.png)

This can be improved in many ways, but it shows how significative it is in that regard

**Comment by RytoEX** [comment]
Our GitHub Issues is for verified bug reports.  Please use [our Ideas and Suggestion site](https://ideas.obsproject.com/), [Discord](https://obsproject.com/discord), or [forums](https://obsproject.com/forum/) for feature requests.

**Comment by gxalpha** [comment]
For your info, this currently also depends on the OS.
This is how it looks on Windows 11:
![image](https://user-images.githubusercontent.com/59806498/155375561-8b267f24-a4d0-4981-ab8d-2e7c9337f598.png)

**Comment by fefo-dev** [comment]
Wow, that's vastly better. Had a suspicion that each OS would have it's implementation.
