### ISSUE TITLE
having more than one Jack Input Client causes a hang

### ISSUE THREAD

**Issue by ShadowFungi** [obsproject/obs-studio#6017]
### Operating System Info

Other

### Other OS

Ubuntu 21.10

### OBS Studio Version

27.2.1

### OBS Studio Log URL

https://obsproject.com/logs/9E3Dyc6ZkCZlN4VM

### Expected Behavior

A second "Jack Input Client" source would be added to the scene.

### Current Behavior

Hangs when adding a second "Jack Input Client".

### Steps to Reproduce

1. Download OBS 27.2.1 flatpak via flathub
2. Make a new scene
3. add "Jack Input Client" with a unique name
4. add another "Jack Input Client" with standard name

**Comment by kkartaltepe** [comment]
I cannot replicate this, can you provide a backtrace from gdb?

**Comment by ShadowFungi** [comment]
I'd be glad to, if you could point me in a direction on how to do so

**Comment by kkartaltepe** [comment]
https://docs.flatpak.org/en/latest/debugging.html something like this I hope would get you into gdb in the terminal. From the gdb prompt you can start the program by typing `r` and then wait until it crashes. Once it crashes you can go back to the gdb prompt and use `bt` to create a backtrace you can post.

**Comment by ShadowFungi** [comment]
okay here you go

bt returns:
```
 #0  0x00007ffff47a4b5d in poll () at /usr/lib/x86_64-linux-gnu/libc.so.6
 #1  0x00007fffefdb64dd in g_main_context_iterate.constprop () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
 #2  0x00007fffefdb6614 in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
 #3  0x00007ffff4f33834 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
 #4  0x00007ffff4edabcb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
 #5  0x00007ffff4ee2ea0 in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
 #6  0x00005555555f1874 in run_program (argv=0x7fffffffd9c8, argc=<optimized out>, logFile=...) at /run/build/obs/UI/obs-app.cpp:2208
 #7  main(int, char**) (argc=<optimized out>, argv=0x7fffffffd9c8) at /run/build/obs/UI/obs-app.cpp:2904
```

here's the error obs drops in the terminal when it crashes:
```
error: jack-input: jack_client_open Error:Could not create JACK client! JACK Input Client
error: Failed to create source 'JACK Input Client'!
info: User added source 'JACK Input Client' (jack_output_capture) to scene '[NS] Desktop Audio'
```

**Comment by kkartaltepe** [comment]
This does not appear to be a crash.

**Comment by ShadowFungi** [comment]
no it doesn't (now that I look at it a bit more intently), which is all the more confusing as when I add the "Jack Input Client" with the flatpak debugging enable it freezes and doesn't load, I'm suspecting that OBS doesn't know a Jack instance is already running. Which I probably should of mentioned earlier as well

**Comment by ShadowFungi** [comment]
okay I figured out what the issue was, turns out I was using an outdated version of flatpak.

**Comment by ShadowFungi** [comment]
> okay I figured out what the issue was, turns out I was using an outdated version of flatpak.

Wanted to provide a bit information on this.

The version of Flatpak which I had was a development version (1.11.2), which at the time was held back by the Pop!_OS kernel, this may have changed since the original date of this thread, but I have since stopped using Pop!_OS due to the custom kernel they've used
