### ISSUE TITLE
Stream stops capturing game after 27.2.1 update

### ISSUE THREAD

**Issue by jwoertink** [obsproject/obs-studio#6019]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.1

### OBS Studio Log URL

https://obsproject.com/logs/7hYbmvbK9g1Bc5Fo

### Expected Behavior

When using a game capture window (game capture, specific window, xbox console companion) it is expected to stream and continue streaming (staying visible) along with the live stream.  The game capture is also expected to remain the same size.

### Current Behavior

Game capture will stream for approximately one minute after going live or recording.  It then goes blank, not capturing or streaming the game. If it does come back the game capture window is no longer the same size and has moved positions in the scene. 

### Steps to Reproduce

1)    Start streaming
2)    Make xbox console companion full screen
3)    Live stream continues normally
4)    After approximately 1-3 minutes the game capture box goes blank
5)    Upon returning to OBS the box remains blank and sometimes changes position and size in the scene 

### Anything else we should know?

1. This did not happen on v27.2.0
2. Y'all are amazing, and this product is great! :heart:

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by jwoertink** [comment]
Oh. I do feel like this is a bug since an update caused OBS to stop working as intended, but I'll move over to discord and/or the forum to see if we can find more info on this. Thanks!
