### ISSUE TITLE
Hardware acceleration is not used for VP9 with Alpha channel

### ISSUE THREAD

**Issue by megapro17** [obsproject/obs-studio#6020]
### Operating System Info

Windows 11

### OBS Studio Version

27.2.1

### OBS Studio Log URL

https://obsproject.com/logs/Y3OyStov4XKb6Zn7

### Expected Behavior

Decode video using GPU

### Current Behavior

I have a VP9 video with alpha channel, created by ffmpeg with `-pix_fmt yuva420p` option. It's working fine, and has transparency as I needed. But OBS refuses to use GTX 1060 GPU to decode it. I can see Video decode graph in task manager is always zero when video is playing in OBS, and high CPU usage. 
I tried different videos and they are accelerated in OBS just fine: H264, VP9 3840x2160 without transparency.

GPU can decode this video, because when I'm opening in video player, I can see Video decode is about 10-20%. Also, tried ffmpeg `-hwaccel dxva2` and `-hwaccel d3d11va`, both are working fine, with gpu decode usage.

### Steps to Reproduce

1. Add Media source, enable alpha channel and hardware acceleration, select file that I attached
2. Check task manager and see high cpu usage and missing gpu decode.

### Anything else we should know?

```
ffmpeg -y -i "1.mov" -c:v libvpx-vp9 -profile:v 0 -quality good -cpu-used 4 -crf 16 -b:v 0 -pix_fmt yuva420p -write_tmcd 0 -lag-in-frames 25 -tile-columns 4 -tile-rows 0 -threads 8 -row-mt 1 -auto-alt-ref 1 -enable-tpl 1 -pass 1 -an -f null -
ffmpeg -y -i "1.mov" -c:v libvpx-vp9 -profile:v 0 -quality good -cpu-used 4 -crf 16 -b:v 0 -pix_fmt yuva420p -write_tmcd 0 -lag-in-frames 25 -tile-columns 4 -tile-rows 0 -threads 8 -row-mt 1 -auto-alt-ref 1 -enable-tpl 1 -pass 2 -an "1.mkv"
```

**Comment by Fenrirthviti** [comment]
This is not possible, as there is no hardware decoder that supports VP9 with Alpha. Are you absolutely certain that the video is being decoded *with* alpha? On VP9, the alpha channel is basically a hack, where it's a completely separate video track effectively, and no hardware decoders know how to handle it. I suspect the tests are not actually decoding the alpha channel, but just the normal video, discarding alpha information.

**Comment by Fenrirthviti** [comment]
Also, VP9 as a codec doesn't even support alpha. See:

https://groups.google.com/a/webmproject.org/g/codec-devel/c/BUJ2jEFPrBk

Since this is not a bug, I'd recommend joining our Discord and hopping in either the tech-talk or encoding-talk channels for further information.

**Comment by megapro17** [comment]
@Fenrirthviti Okay, but maybe it's possible to decode non transparent part with gpu? There is no any other lossy video codec with transparency that obs or ffmpeg can open, except prores that is taking a lot of resources. 
I heard HEVC can support transparency, but not with x265 encoder. Maybe it'll work with gpu?
