### ISSUE TITLE
OBS 27.2.1 constant crash and cannot transform source size

### ISSUE THREAD

**Issue by pwaser** [obsproject/obs-studio#6023]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.1

### OBS Studio Log URL

https://obsproject.com/logs/H3jxhhgCaK5kggcW

### OBS Studio Crash Log URL

https://obsproject.com/logs/w7xLtf3AFyFWERcH

### Expected Behavior

No misbehaviour.

### Current Behavior

OBS crashes when hitting the close button. Unhandled exception: c0000005

Also, I cannot resize window captures: reset transform, fit to screen... Sometimes it works, most of the time it's greyed out.
I will be restoring back to the previous version, which only had the problem of a full computer freeze when capturing games, but I worked around it by capturing everything as "window".

### Steps to Reproduce

1.Open OBS
2.Close OBS
3.OBS has crashed
...

**Comment by notr1ch** [comment]
Looks like the `advanced-scene-switcher.dll` plugin is responsible for the crash, try updating or removing it.

**Comment by Fenrirthviti** [comment]
This crash is being caused by the Advanced Scene Switcher plugin, you will need to report it to them.

https://github.com/WarmUpTill/SceneSwitcher
