### ISSUE TITLE
error: use of undeclared identifier 'GS_DMABUF_FLAG_IMPLICIT_MODIFIERS_SUPPORTED'

### ISSUE THREAD

**Issue by yurivict** [obsproject/obs-studio#6027]
### Operating System Info

Other

### Other OS

FreeBSD

### OBS Studio Version

27.2.1

### OBS Studio Log URL

n/a

### OBS Studio Crash Log URL

n/a

### Expected Behavior

Build succeeds.

### Current Behavior

Build fails:
```
/disk-samsung/freebsd-ports/multimedia/obs-studio/work/obs-studio-27.2.1/libobs-opengl/gl-egl-common.c:262:19: error: use of undeclared identifier 'GS_DMABUF_FLAG_IMPLICIT_MODIFIERS_SUPPORTED'
                *dmabuf_flags = GS_DMABUF_FLAG_IMPLICIT_MODIFIERS_SUPPORTED;
                                ^
```

### Steps to Reproduce

Build.

**Comment by WizardCM** [comment]
Is this fixed by #6026?

**Comment by yurivict** [comment]
Yes it is.

**Comment by Fenrirthviti** [comment]
Just for future reference, for our project if you are submitting a PR, you don't need to open a matching issue. We're ok with just the PR :)

**Comment by yurivict** [comment]
Sorry, I didn't know about the PR.

**Comment by Fenrirthviti** [comment]
Ah, my mistake I thought you were the one who had opened the PR as well. Getting emails jumbled. Apologies!

**Comment by yurivict** [comment]
No problem!
