### ISSUE TITLE
OBS Studio Deadlock on windows 11

### ISSUE THREAD

**Issue by mingoal** [obsproject/obs-studio#6040]
### Operating System Info

Windows 11

### OBS Studio Version

27.2.1

### OBS Studio Log URL

https://obsproject.com/logs/w0DftHYdyFxjYhp_

### Expected Behavior

OBS could stop streaming successfully

### Current Behavior

OBS fail to stop streaming

### Steps to Reproduce

1. OBS with websocket/move/stream fx plugins installed
2. Add "Display Capture" and Text Source
3. connect obs with websocket on the same machine
4. Start streaming
5. Stop streaming

### Anything else we should know?

I connected obs with websocket service. I clicked the "Stop Streaming" button, but it seems OBS can't stop successfully. Click "Start Streaming" again not make it work. The CPU usage of OBS is low, but windows says OBS is under deadlock status. Close OBS window doesn't make OBS exit, must be killed from windows task manager.

This happens on recording too.

![obs-deadlock](https://user-images.githubusercontent.com/15058046/155844073-18ad3e70-aea9-4a28-ba4b-1da179547bba.png)

**Comment by mingoal** [comment]
another log. This time I started/stopped recording several times. And click "Start Recording" didn't bring it to "Stop Recording".

from "Help => Logs => View Current Log", The last line is NOT "Recording start".

https://obsproject.com/logs/z2wFGtWwMnhy9Jk1

![freeze-on-click](https://user-images.githubusercontent.com/15058046/155845292-0ee449ad-605a-4281-86d4-9f2799ae54e0.png)

![deadlock-after-start-stop-recording-several-times](https://user-images.githubusercontent.com/15058046/155845349-cfdcec42-de3e-4d3b-ba18-9ae0f2331b50.png)

**Comment by mingoal** [comment]
The GPU usage.
![gpu-usage](https://user-images.githubusercontent.com/15058046/155845550-a3c8535a-56fb-41d1-afa1-115c0dbec47a.png)

**Comment by energizerfellow** [comment]
Update your AMD GPU drivers.

**Comment by mingoal** [comment]
> Update your AMD GPU drivers.

Thanks.
I just updated GPU driver. Will back and update whenever it happens again or not in 1 or 2 days.

**Comment by mingoal** [comment]
After upgraded GPU driver, the deadlock doesn't happen again.
