### ISSUE TITLE
Restream Browser Login (or any browser passwords)

### ISSUE THREAD

**Issue by ashmanmedia** [obsproject/obs-studio#6046]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.1

### OBS Studio Log URL

https://obsproject.com/logs/90cyTljFxAKyGq1h

### OBS Studio Crash Log URL

https://obsproject.com/logs/2F4MBWP17zf6GHNX

### Expected Behavior

Restream uses docks to LOGIN and since latest 2 versions maybe the Browser wont keep the saved passwords on the accounts.
This is also happening with Browser Added pages I use for OCULUS CASTING.
![obs64_2022-02-27_16-38-53](https://user-images.githubusercontent.com/3086735/155901390-b9605240-3789-4076-91f8-f6c317156ac8.jpg)

### Current Behavior

The Password Login constantly comes up with every boot in of OBS now.
Used to keep the login password on any browser activity.

### Steps to Reproduce

1.Just using Restreams Integration with OBS and there floating docks dont log in after each session.
2.Or try adding a browser tab with a email client like gmail maybe wont keep passwords logged in?

### Anything else we should know?

Love your program TY first time adding a bug

**Comment by WizardCM** [comment]
Your issue is caused by the SE Live plugin. We do not provide support for it - contact StreamElements.
