### ISSUE TITLE
version 27.2.1 crashes on startup

### ISSUE THREAD

**Issue by Sanluli36li** [obsproject/obs-studio#6050]
### Operating System Info

Windows 11

### OBS Studio Version

27.2.1

### OBS Studio Log URL

https://obsproject.com/logs/BdGPNqMwfV7hjICl

### OBS Studio Crash Log URL

https://obsproject.com/logs/BdGPNqMwfV7hjICl

### Expected Behavior

it should start normally

### Current Behavior

I just start it up and I just see the crash window

### Steps to Reproduce

In fact I just installed the latest version of OBS and that's it
When I rollback OBS to 27.1.3 everything works fine

### Anything else we should know?

Tried removing all plugins, still the same

**Comment by Sanluli36li** [comment]
[Crash 2022-02-23 23-53-25.txt](https://github.com/obsproject/obs-studio/files/8154780/Crash.2022-02-23.23-53-25.txt)
[Crash 2022-02-23 23-55-13.txt](https://github.com/obsproject/obs-studio/files/8154782/Crash.2022-02-23.23-55-13.txt)
[Crash 2022-02-23 23-57-56.txt](https://github.com/obsproject/obs-studio/files/8154784/Crash.2022-02-23.23-57-56.txt)
[Crash 2022-02-23 23-58-30.txt](https://github.com/obsproject/obs-studio/files/8154785/Crash.2022-02-23.23-58-30.txt)
[Crash 2022-02-23 23-52-56.txt](https://github.com/obsproject/obs-studio/files/8154786/Crash.2022-02-23.23-52-56.txt)

earlier crash log

**Comment by Fenrirthviti** [comment]
It also appears that you're using the win-audio-capture plugin, can you remove that and see if that fixes the crash? I believe the crash in that plugin was fixed in an updated version if you are still using the functionality.

**Comment by RytoEX** [comment]
This appears to be a crash that we've recently fixed in #6028.  This should be fixed in our next release.
