### ISSUE TITLE
Won't capture desktop sound 27.2.1

### ISSUE THREAD

**Issue by pzyber** [obsproject/obs-studio#6052]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.1

### OBS Studio Log URL

http://upload.pzyber.net/nolist/obslogs/2022-02-25%2021-04-07.txt

### Expected Behavior

Sounds should be captured and audio level should be shown for the Desktop Audio channel whenever sounds are being played on the computer.

### Current Behavior

No sounds for the Desktop Audio channel are being captured at all.
Mic still works.

### Steps to Reproduce

1. Update from version 27.1.3 to 27.2.1.
2. Desktop Audio stops working.

Doesn't matter what audio device that is selected in the settings.
I usually have it set to default and never switches it in windows either, has been working withouit any adjustments or problems for years until this update.

### Anything else we should know?

Version 27.1.3 works without problem, I downgraded to this version until this issue has been resolved.
I also attached the log file from before the upgrade where it was working here.
[2022-02-18 18-34-11.txt](https://github.com/obsproject/obs-studio/files/8156860/2022-02-18.18-34-11.txt)
.

**Comment by Fenrirthviti** [comment]
Hi, you appear to be using OBS with the StreamElements.live plugin, which we are no longer supporting when installed.

If you are able to, please remove their plugin and reproduce the issue in a clean install of OBS for us to take a closer look, otherwise you will need to report the issue to them.

**Comment by Xorshasia** [comment]
This sounds like a support issue, rather than a bug. Have you tried asking for assistance in the official OBS Discord server?

**Comment by Fenrirthviti** [comment]
As an additional note, your version of Windows is significantly out of date, and probably contributing to the problem. I would recommend updating your Windows version as well.
