### ISSUE TITLE
[Crash] OBS closes on crash

### ISSUE THREAD

**Issue by LoneMarauder** [obsproject/obs-studio#6054]
### Operating System Info

Windows 11

### OBS Studio Version

27.2.1

### OBS Studio Log URL

https://obsproject.com/logs/hiP8Tlq_VM6pUHhT

### OBS Studio Crash Log URL

https://obsproject.com/logs/eEq36a8t4oy5MRfh

### Expected Behavior

When I click the X in the top-right, I expect to go back to the desktop without a crash

### Current Behavior

When I click the X in the top-right, the application exits and generates a crash.

### Steps to Reproduce

1. Open OBS Studio
2. Close OBS Studio
3. ???
4. Profit!

**Comment by WizardCM** [comment]
This crash is caused by an outdated Advanced Scene Switcher plugin. You will need to update it.
