### ISSUE TITLE
Custom Output (FFmpeg) failed to set qscale  and q parameter

### ISSUE THREAD

**Issue by DanielLausch** [obsproject/obs-studio#6059]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.1

### OBS Studio Log URL

https://obsproject.com/logs/gM8MLFNzFJDfMR1k

### Expected Behavior

Adding qscale=1 or q=1 to "Video Encoder Settings (if any)" should work.

### Current Behavior

qscale=1 or q=1 "Failed to set" (log)

### Steps to Reproduce

1. Set "Output Mode" to Advanced in OBS Output settings.
2. Switch to "Recording" tab and set Type to "Custom Output (FFmpeg)"
3. Set "Container Format" to "mpegts (Video)"
4. Click the checkbox "Show all codecs (even if potentially incompatible)"
5. Set "Video Encoder" to "mpeg1video"
6. Set "Video Encoder Settings (if any)" to "q=1 qscale=1"
7. Apply Settings and start recording.
8. Check log and you should find the text "Failed to set q=1" and "Failed to set Failed to set qscale=1"

### Anything else we should know?

The parameter works fine on FFmpeg standalone. I tried FFmpeg version 4 and 5 (latest as of reporting time)

**Comment by pkviet** [comment]
those are options for ffmpeg (the binary) not options for the encoder ... That's why. obs is NOT a front-end to ffmpeg; it uses its libraries avcodec, etc ... 
The options from avcodec encoders that obs can accept are listed here: 
https://www.ffmpeg.org/ffmpeg-codecs.html
