### ISSUE TITLE
Wayland | 'qt.qpa.wayland: Wayland does not support QWindow::requestActivate()'

### ISSUE THREAD

**Issue by Ricky-Tigg** [obsproject/obs-studio#6065]
### Operating System Info

Other

### Other OS

Fedora (Linux) on Wayland platforms Gnome and KDE

### OBS Studio Version

27.2.1

### OBS Studio Log URL

https://obsproject.com/logs/g2ZcbaWu6D2YGSPn

### Expected Behavior

- Behavior in Gnome
The dock's window to not missi the title bar,

- Dock's window  located outside the application window's frame to behave the same in Wayland and X11 sessions. The highest probability to behave as intended is certainly observable in X11 session. If so, be that behaviour the one in Wayland too.

### Current Behavior

- Common output in Gnome and KDE sessions
```shell
$ obs
QSocketNotifier: Can only be used with threads started with QThread
(...)
info: Qt Version: 5.15.2 (runtime), 5.15.2 (compiled)
info: Portable mode: false
(...)
info: Using EGL/Wayland
info: Initialized EGL 1.5
info: Loading up OpenGL on adapter Intel Mesa Intel(R) HD Graphics 620 (KBL GT2)
info: OpenGL loaded successfully, version 4.6 (Core Profile) Mesa 21.3.7, shading language 4.60
(...)
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
```
Output produced as consequence of grabbing a dock then moving it outside the application window's frame. 
```shell
This plugin supports grabbing the mouse only for popup windows
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
```
- Behaviours in Gnome
The dock's window **is missing** the title bar, as a consequence it cannot be moved neither be closed.

**Note**: Exiting the application while the dock's window is in that state, then reopening the application, will add the missing title bar to that dock's window.

- Behavior in KDE
The dock's window **is not missing** the title bar, as a consequence it can be moved or closed

- **Common** behavior in Gnome and KDE
Unlike under sessions on X11, clicking the title bar of a dock being outside of its original location won't  bring it it back into its original location in the UI but will enlarge the window.

- Illustration of a dock's title bar in Gnome session

![OBS_Studio_dock_title_bar](https://user-images.githubusercontent.com/26058215/156343990-3f4d131d-b6e2-42c2-b07c-cb82b4db0c31.png)

### Steps to Reproduce

Ensure a Wayland session is opened:
```shell
$ echo $XDG_SESSION_TYPE
wayland
```
Then either execute `obs` or `QT_QPA_PLATFORM=wayland obs`

**Note**: Execution of that last command in X11 session causes a **crash** of this application.

```shell
$ QT_QPA_PLATFORM=wayland obs
Failed to create wl_display (No such file or directory)
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.
Aborted (core dumped)
```

**Comment by tytan652** [comment]
```
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
```
Not an issue, Qt has just no implementation of this function for Wayland platform.

---

Every other weird behavior about docks does not comes from OBS but Qt itself.

**Comment by WizardCM** [comment]
How did you install OBS? Via our Flatpak, or somewhere else?

**Comment by Ricky-Tigg** [comment]
Hello. That very mention i intended not to omit in report -- via rpmfusion-free repository.

**Comment by tytan652** [comment]
I finally found the titlebar "issue", it's a QGnome that apply a WaylandDecoration to all floating docks.
And it affects Flatpak and Fedora distros (and maybe more) that both provide QGnome by default.

Qt just apply the same titlebar to the Main Window and docks.

**Comment by kkartaltepe** [comment]
It looks like everything has been identified as working as intended or not our bug?

> qt.qpa.wayland: Wayland does not support QWindow::requestActivate()

Working as intended

> I finally found the titlebar "issue", it's a QGnome that apply a WaylandDecoration to all floating docks.

Sounds like a bug in Qt?

> Note: Execution of that last command in X11 session causes a crash of this application.

If you cannot establish a connection to the compositor, things are not going to work. If anyone wants to figure out where the crash originates and fixes it thats great but its not going to improve the fact that nothing will work.

**Comment by Ricky-Tigg** [comment]
Attempts to send related crash report fails invariably.. **Crash function:** _qt_message_output(QtMsgType, QMessageLogContext const&, QString const&) [clone .cold]_.  I shall next let _Qt project_ know about this issue despite it may not be the one at the source of the issue, but _Gnome project_.

**Comment by tytan652** [comment]
What crash did I misread your issue ?
---

```
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
```
This is normal, Qt has not finished their Wayland implementation.

---

The titlebar is because of QGnome WaylandDecorations not GNOME's fault.

Qt 5 as also known weird behavior under some Wayland compositor like Mutter (GNOME).

--- 

Running `QT_QPA_PLATFORM=wayland obs` under X11/Xorg will make the app crash because Wayland apps are not meant to run under X11/Xorg. This crash is expected.

If your are talking about this crash, you are just misusing Qt arguments.

**Comment by Ricky-Tigg** [comment]
You did not misread; you too had pertinent answers. Since Wayland implementation at Qt's is a work in progress, that crash was due to misuse of Qt arguments, i wonder if there is something _Qt project_ might need to be aware of which would require to send it a report, so that it knows that qt.qpa.wayland: support of _QWindow::requestActivate()_ is needed or that an application may behave differently in Wayland when that one is served by **Mutter** and **KWin**. Or is there nothing to do but wait since all good shall come on time?
