### ISSUE TITLE
CEF Browser with Shaka Player DRM

### ISSUE THREAD

**Issue by sweetngx** [obsproject/obs-studio#6067]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.1

### OBS Studio Version (Other)

ALL Version

### OBS Studio Log URL

None

### OBS Studio Crash Log URL

None

### Expected Behavior

Playing protected content

### Current Behavior

OBS Browser CEF version 95.0.4638.69 works great, but unfortunately Shaka Player cannot play DRM content and I get an error. I ran tests on the Chromium browser to find the cause of the error and found that the issue is a general one and some browsers have this issue.
Is it possible for OBS developers to fix it by modifying the CEF?

https://www.radiantmediaplayer.com/docs/latest/gist/drm/all.html

"message": "Shaka Error DRM.REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE()", 

### Steps to Reproduce

1.
2.
3.
...

**Comment by Fenrirthviti** [comment]
We have no interest in supporting DRM content through browser source in OBS.
