### ISSUE TITLE
obs dont want to stop recording ruining my content

### ISSUE THREAD

**Issue by SyncMaster93** [obsproject/obs-studio#6073]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.1

### OBS Studio Log URL

https://obsproject.com/logs/qyFPf54xoASnK4Jo

### Expected Behavior

To work fine LMAO

### Current Behavior

Recording button is stucked!

### Steps to Reproduce

1. Trying to record my gameplay
2.
3.
...

**Comment by gxalpha** [comment]
This issue appears to be a support request, which we don't use GitHub Issues for.
Please make sure to visit the support sections on our [Discord server](https://discord.gg/obsproject) or [Forums](https://obsproject.com/forum).

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
