### ISSUE TITLE
Output freezes when the OBS window is covered in Wayland session

### ISSUE THREAD

**Issue by myownfriend** [obsproject/obs-studio#6076]
### Operating System Info

Other

### Other OS

Fedora 35

### OBS Studio Version

27.2.1

### OBS Studio Log URL

https://obsproject.com/logs/4Vto6Yd7zZck7Yit

### Expected Behavior

When recording, streaming, or using virtual camera, OBS should always update it's output whether the OBS window is covered or not.

### Current Behavior

When recording to disk or using the Virtual Camera, covering the OBS window with another window causes the output to continue sending the last frame.  I haven't tried streaming but it probably happens when streaming, too. Minimizing doesn't seem to trigger the same behavior but that just might be a difference in how Mutter handles things.

### Steps to Reproduce

1. Capture something with constant movement
2. Record or stream it
3. Cover the OBS window entirely with another window
...

### Anything else we should know?

Using Nvidia 510.47.03

**Comment by kkartaltepe** [comment]
nvidia on wayland is not supported. Please let me know if you can replicate with mesa drivers and we can reopen.

**Comment by myownfriend** [comment]
> nvidia on wayland is not supported. Please let me know if you can replicate with mesa drivers and we can reopen.

I wasn't aware that as the case. Is that stated anywhere? I know that previously when I mentioned issues with Nvidia on Wayland, you told me that I need to wait until Nvidia supports DMA-buf and GBM which it now does. Then there was an additional MR that added support for rendering on Nvidia GPUs so I figured it was at the point where it was fine to post Nvidia issues.

**Comment by kkartaltepe** [comment]
You can read more about known issues with nvidias drivers in the commit that enabled them to sort of work https://github.com/obsproject/obs-studio/pull/5620#issuecomment-989005035 I havnt really written a list as most of them seem unlikely to be fixed soon, and at least for now I am unfortunate enough to have a system to test with.

**Comment by AlynxZhou** [comment]
I can reproduce this with a RTX2070Super/GNOME/Wayland, streaming gets disconnected soon if obs is covered by other window, which is strange. If I leave obs foreground, or just minimize it, all things works fine.

I am not sure whether this is a NVIDIA Wayland driver issue, and maybe @erik-kz from NVIDIA who always handle NVIDIA/Wayland problems can offer some help, this is really annoying because obs is widely used for streaming.
