### ISSUE TITLE
gl_copy_backbuffer: failed to blit: 1286

### ISSUE THREAD

**Issue by zhaokaixs** [obsproject/obs-studio#6078]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.3

### OBS Studio Log URL

https://obsproject.com/logs/69mhs-6GjbRmryau

### Expected Behavior

capture success

### Current Behavior

OpenGL 4.5 ,gl_copy_backbuffer: failed to blit: 1286

### Steps to Reproduce

 OpenGL 4.5 ,gl_copy_backbuffer: failed to blit: 1286

**Comment by tt2468** [comment]
Please provide a proper log along with reproduction steps otherwise we cannot help you.

**Comment by zhaokaixs** [comment]
> 请提供正确的日志以及复制步骤，否则我们无法为您提供帮助。
[log:](https://obsproject.com/logs/69mhs-6GjbRmryau)
test app url, use game capture
[https://dasdsad2.oss-cn-beijing.aliyuncs.com/test_app.zip?Expires=1646399256&OSSAccessKeyId=TMP.3Khnb4rJeepM854fzbwgoJ2Pze1TSqhgAH2xiTnnpuVwkGFXWWVRBiGBazyGqmFiJ3G515KS836vMH4D4LrVUpV4tTiToR&Signature=PNXumxe3yfFQkX0Az3V%2F0cLLio8%3D](url)

**Comment by zhaokaixs** [comment]
> Please provide a proper log along with reproduction steps otherwise we cannot help you.

Thank you

**Comment by zhaokaixs** [comment]
gl_copy_backbuffer:	glBindFramebuffer(GL_READ_FRAMEBUFFER, 0); reset back buffer
