### ISSUE TITLE
Browser Source are not showing anymore

### ISSUE THREAD

**Issue by sgaechter** [obsproject/obs-studio#6085]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.3

### OBS Studio Log URL

https://obsproject.com/logs/3zc7Zia8mUV8hlx6

### Expected Behavior

If a Browser Source is created, the content should be displayed. 

### Current Behavior

No Browser content shown

### Steps to Reproduce

1. create Browser Source
2. Display Browser Source
3. wonder..
...

### Anything else we should know?

I Updated from 27.1.3 to 27.2.3. The Browser source will be shown if I reinstall 27.1.3

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by Fenrirthviti** [comment]
That said, you probably just need to disable hardware acceleration from browser source in Settings -> Advanced, as your hardware is extremely old and most likely doesn't support the newer version of CEF we ship with.

**Comment by sgaechter** [comment]
Sorry, I didn't think about the hardware acceleration. This was it. Thanks for your quick help, even if it was Support. Regards Sven
