### ISSUE TITLE
Stream Deck/Macro Deck not sending Hotkeys to OBS

### ISSUE THREAD

**Issue by TomKaland** [obsproject/obs-studio#6090]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.3

### OBS Studio Log URL

https://obsproject.com/logs/BaW8y2U51BQoLuiX

### Expected Behavior

Setting up a Stream Deck/Macro Deck the units should be able to send Hotkeys to OBS when the mouse is active on OBS software

### Current Behavior

Last couple of weeks/monts neither the MAcro Deck or Stream Deck seems to send hotkeys to OBS, when OBS is the active program on computer. I always need to click on another screen or program to get the hotkeys to execute.

The websocket command in both (Setting scene choise) Macro Deck and Stream Deck works fine.

I run Synergy mouse software on the computer to have the same keyboard/mouse on 4 computers. Have uninstalled this without any change in behavour.

### Steps to Reproduce

When it does NOT work:
1. Click on OBS 
2. Push hotkey button on Stream Deck
3. No Hotkey excecuted

When it DOES work:
1. Click on another screen/program on the computer 
2. Push hotkey button on Stream Deck
3. Hotkey excecuted and working fine

### Anything else we should know?

If it is the OBS or the Websocket Plugin or the OBS software I dont know. Both are up to date, as is Windows.
(I did not have this problem using the older version Macro Deck)

**Comment by Fenrirthviti** [comment]
We are unable to support third party hardware and tools, please reach out to their respective support channels.

**Comment by TomKaland** [comment]
Hi,

So yo`re saying it is not OBS, but Websocket plugin? As both Macro Deck and Stream Deck both behave the same, you might exclude these.
