### ISSUE TITLE
Crash when exiting while an output is active

### ISSUE THREAD

**Issue by Susko3** [obsproject/obs-studio#6093]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.3

### OBS Studio Log URL

https://obsproject.com/logs/efk3G1YSqoiajtD0

### OBS Studio Crash Log URL

https://github.com/obsproject/obs-studio/files/8191322/Crash.2022-03-05.20-19-10.txt

### Expected Behavior

OBS should close without showing an error box when a video output (recording/stream) is running.

### Current Behavior

An error box will appear after OBS closes.

### Steps to Reproduce

1. Open OBS
2. Start recording and/or start streaming
3. Press Exit or the windows X button
4. Click 'Yes' on the 'Are you sure you want to exit?' box
5. OBS will close as expected
    - the video appears to be saved just fine (tested with a .mp4 recording), recording looks fine, just has a split-second of black (no video and audio) on the end
7. A second or two later, an 'OBS has crashed' error box will appear

### Anything else we should know?

Doesn't crash if only Virtual Camera output is running. (So crashes with Recording and Streaming only.)

[Crash 2022-03-05 20-19-10.txt](https://github.com/obsproject/obs-studio/files/8191322/Crash.2022-03-05.20-19-10.txt)
```
Thread 1BAC: libobs: graphics thread (Crashed)
Stack            EIP              Arg0             Arg1             Arg2             Arg3             Address
0000007BC50FFAD0 00007FFADC743B57 0000018537065E01 0000000000000001 0000018537065E40 000001853EC37FE0 w32-pthreads.dll!pthread_mutex_unlock+0x27
0000007BC50FFB30 00007FFAB586E3A6 0000000000000010 0000000000000010 0000007BC50FFC60 0000018534698088 obs.dll!video_output_lock_frame+0x106
0000007BC50FFB60 00007FFAB58D0B79 0000000000000000 0000000000000000 0000000000000000 00000185346984A8 obs.dll!output_frame+0x229
0000007BC50FFCA0 00007FFAB58D06CE 01D830C5D50E2508 0000000000FE5001 00009C245768E198 FFFFFFFFFFFFFFFF obs.dll!obs_graphics_thread_loop+0x31e
0000007BC50FFD60 00007FFAB58D036C FFFFFFFFFFFFFFFF 00007FFADC4F6C30 0000000000000000 0000007BC50FFE59 obs.dll!obs_graphics_thread+0x2ec
0000007BC50FFE10 00007FFADC747A06 0000018536EC4500 0000000000000000 0000000000000000 0000000000000000 w32-pthreads.dll!ptw32_threadStart+0x126
0000007BC50FFEC0 00007FFAF3541BB2 0000000000000000 0000000000000000 0000000000000000 0000000000000000 ucrtbase.dll!0x7ffaf3541bb2
0000007BC50FFEF0 00007FFAF55C7034 0000000000000000 0000000000000000 0000000000000000 0000000000000000 kernel32.dll!0x7ffaf55c7034
0000007BC50FFF20 00007FFAF5E62651 0000000000000000 0000000000000000 0000000000000000 0000000000000000 ntdll.dll!0x7ffaf5e62651
```

A quick check with WinDbg shows the following:

```
FAILURE_BUCKET_ID:  NULL_CLASS_PTR_READ_c0000005_w32-pthreads.dll!pthread_mutex_unlock
```

So it's probably crashing here with a nullptr:

https://github.com/obsproject/obs-studio/blob/9b6cc99828848ffcbb9217b03a6823710ae29999/libobs/media-io/video-io.c#L476

**Comment by notr1ch** [comment]
Please also test without 3rd party plugins.

**Comment by Susko3** [comment]
Uninstalled [DroidCam OBS](https://www.dev47apps.com/obs/) and no crash. Installed again, and no crash. I was probably on an older version.

Is there some safe mode that will not load 3rd party plugins without uninstalling them?

**Comment by Fenrirthviti** [comment]
> Is there some safe mode that will not load 3rd party plugins without uninstalling them?

Unfortunately, not currently, but it's something on our radar as this kind of thing happens fairly regularly.
