### ISSUE TITLE
obs在直播csgo时提醒编码过载，然后obs会直接黑屏停止响应，并且无法正常关闭，稍等一会电脑就直接蓝屏了

### ISSUE THREAD

**Issue by grayVI** [obsproject/obs-studio#6096]
### Operating System Info

Windows 11

### OBS Studio Version

27.2.3

### OBS Studio Log URL

https://obsproject.com/logs/h2iHJIRRq6jMIOjd

### Expected Behavior

希望obs不要停止响应，不要导致电脑蓝屏

### Current Behavior

obs导致的系统蓝屏，微软工程师分析为obs的问题
我升级显卡驱动到最新后依然有这个问题
https://answers.microsoft.com/zh-hans/windows/forum/all/win11%E8%93%9D%E5%B1%8F%E8%AF%B7%E5%B8%AE%E5%BF%99/9ee81f88-a039-49ca-9e3a-3804e266f2a0

### Steps to Reproduce

1.r9000p 打开obs，设置已附在下面
2.进入csgo游戏，obs左下角提示编码过载，之后obs直接黑屏，并且只能从任务管理器中结束该obs进程
3.如果不结束该进程，之后电脑会直接蓝屏，电脑系统为win11最新
...

### Anything else we should know?

电脑配置  r9000p   cpu  r75800  gpu  3060
obs设置如下
试过obs的26版本和最新版本，都能百分百复现这个问题
![image](https://user-images.githubusercontent.com/48689007/156912682-2f0ef19c-9cde-4f14-8f2d-3266c9503bb4.png)
![image](https://user-images.githubusercontent.com/48689007/156912697-1da51443-06c7-4f8d-9185-8db92d9e13b8.png)

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by Ra2-IFV** [comment]
> This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.
> 
> Thank you!

Bro, this is not a feature request, it's a bug report.
I also have this problem on Windows 10 :(

**Comment by RytoEX** [comment]
> > This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.
> > Thank you!
> 
> Bro, this is not a feature request, it's a bug report. I also have this problem on Windows 10 :(

Blue screens are not something that OBS can cause directly. Blue screens are caused by issues with hardware, drivers, or low-level kernel applications. OBS is none of these things. Please try updating your drivers, or seek assistance in a general computer help forum to diagnose blue screen issues.

For support with OBS itself, please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.
