### ISSUE TITLE
No Browser source update, Browser source imgae laoding issue and freezes.

### ISSUE THREAD

**Issue by KBNOtaku** [obsproject/obs-studio#6097]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.3

### OBS Studio Log URL

https://obsproject.com/forum/attachments/2022-03-06-12-48-54-txt.81352/?hash=0f3a9272ccdf12ea9ea4b2ee4ce320f7

### Expected Behavior

Browser source update when changing scenes.
Browser source HTML files Picture file loading to be possible again.
No freezes

### Current Behavior

Hello I need your help pleas.
I just updated to the newest version 27.2.3 (64 bit) and have now several issue.

1. The Browser sources do not get updated after changing scenes even thought they are set to do so?
2. In Overlays that uses HTML with pictures OBS can´t load these pictures anymore?
12:49:06.904: obs-browser: Not allowed to load local resource: file:///J:/Streaming/FlightSIM/html/images/event-background.png (source: http://absolute/J:/Streaming/FlightSIm/html/landing.html:0)
3. OBS freezes for a few second every time I change from OBS back to the game (like clicking in OBS and when clicking outside OBS again, OBS freezes). And it freezes a lot when using Scenery changes?

LOG:
https://obsproject.com/forum/attachments/2022-03-06-12-48-54-txt.81352/?hash=0f3a9272ccdf12ea9ea4b2ee4ce320f7

I am having those issues since updating to  version 27.2.1?

### Steps to Reproduce

1. Starting a live stream with OBS
2. Changing scenes
3. Changing from OBS back to the game which is recorded via Game recording.
...

**Comment by DaemonShake** [comment]
Having the same issue with the browser source. I also cannot add custom css to remove transparency. Shame.

**Comment by aMytho** [comment]
I am also having the same issue. I am unable to load local files.
![OBS error message](https://obsproject.com/forum/attachments/1646536853805-png.81334/)

**Comment by Fenrirthviti** [comment]
file:/// working differently is a side effect of increased security updates on the version of CEF we upgraded to, and is expected. You can migrate existing pages to use http://absolute/ instead.

Everything else sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
