### ISSUE TITLE
AV1 recording error when resuming from pause

### ISSUE THREAD

**Issue by Tombodett0** [obsproject/obs-studio#6099]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.3

### OBS Studio Log URL

https://obsproject.com/logs/WT4X5hjHHnB7in98

### OBS Studio Crash Log URL

https://obsproject.com/logs/WT4X5hjHHnB7in98

### Expected Behavior

continue recording to the same output file which works fine for x264 and others.

### Current Behavior

![OBSerror](https://user-images.githubusercontent.com/100237148/157091076-c8bd75f2-1418-42a3-9e31-1bf78801437b.png)

Stops recording to file.

### Steps to Reproduce

1. Set AV1 encoder in Settings -> Output -> Recording (either can produce it, but I used SVT-AV1)
2. Start Recording
3. Pause
4. Unpause
...

### Anything else we should know?

I have replicated this on 3 separate computers on Windows 10 and 11. Maybe 10%of the time this error does not come up, but it happens almost every time.

**Comment by Toniob** [comment]
Same issue here with the latest obs version. If I use SVT-AV1 for local recording, I can pause the recording, but when I unpause it, I’ve got the same error and the recording stops.

**Comment by Tombodett0** [comment]
This appears fixed in the most recent patch, 28.0.3
