### ISSUE TITLE
Can't create scenes with individual Blackmagic devices.

### ISSUE THREAD

**Issue by MarcMouries** [obsproject/obs-studio#6100]
### Operating System Info

macOS 11.6

### OBS Studio Version

27.2.2

### OBS Studio Log URL

https://obsproject.com/logs/pUWxfd2TvafvevCt

### Expected Behavior

The goal is to create 2 scenes with two separate instances of the same Blackmagic Device (Ultra Studio Recorder 3G) 
Example:
- Scene 1: Discussion mode: sharing only the webcam (Blackmagic device occupying the full screen)
- Scene 2: Presentation mode: sharing the desktop with the webcam in a circle (Blackmagic device )

### Current Behavior

I can create the first scene without any issue. I then create the second scene and OBS does not show a second instance of the camera connected by the Blackmagic device.

### Steps to Reproduce

Steps: 
1. I create a second scene
2. Add source Blackmagic device
3. Select "Create New"
4. Keep the automatically created name "Blackmagic Device 2"
5. Select Device: Ultra Studio Recorder 3G
6. Select Video connect: HDMI
=> No preview shows up unlike when I created the first scene

Additionally, when I remove the second device, this makes the device no longer working in the first scene

**Comment by notr1ch** [comment]
Few devices permit multiple instances. Generally you should use "Add Existing" rather than "Create New" to use the same source on multiple scenes.

**Comment by Fenrirthviti** [comment]
This is definitely sounding like a support request at this point, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for further assistance.

Thank you!
