### ISSUE TITLE
obs cant get desktop sound or from any app! Steinberg 22mk II

### ISSUE THREAD

**Issue by gitalexhubuser** [obsproject/obs-studio#6102]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.3

### OBS Studio Log URL

https://obsproject.com/logs/OJJpevW-OKIfgn5Y

### Expected Behavior

Record background sound as usual. 

### Current Behavior

after update - no sound.

mic - works
but else - not

### Steps to Reproduce

1. update obs

### Anything else we should know?

Just update obs to fresh.
Not changed anything in my settings (scenes, etc)

When shoot my video - saw that there are NO BACKGROUND sound. From anythwere (game, vlc, desktop, chrome).

Change all the settings and reboot obs - nothing helped.

I dont try to reinstall or uninstall.

I`, using steinberg ur 22 mkII sound-card (not cheap) but [this guy](https://www.youtube.com/watch?v=BCr0oSQi_PM) with 11 views got the same effect.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
