### ISSUE TITLE
Length of volume bar intensity not proportional to value

### ISSUE THREAD

**Issue by Ricky-Tigg** [obsproject/obs-studio#6108]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.3

### OBS Studio Log URL

https://obsproject.com/logs/o0iwr6-Hlnj4RUWg

### Expected Behavior

2. Length of volume bar intensity to bet according to value in percent - here then a length half of the maximal length.

### Current Behavior

2.  Length of volume bar intensity **not proportional** to value  in percent.

### Steps to Reproduce

1. Set volume to maximal (100 %)

![OBS_Studio_v 27 2 3_audio_mixer_volume_100](https://user-images.githubusercontent.com/26058215/157251437-eee0089c-a68a-460e-afd8-c30252941b87.png)

2. Settings icon | _Advanced audio properties_; set volume value to 50 %.

![OBS_Studio_v 27 2 3_audio_mixer_volume_50](https://user-images.githubusercontent.com/26058215/157251523-e50b1bc1-7b15-420c-8379-7f4d8db1cf81.png)

**Comment by Fenrirthviti** [comment]
This all seems correct to me, the volume meter is not linear, so 50% would not be 50% of the slider.

https://obsproject.com/wiki/Understanding-the-Mixer
