### ISSUE TITLE
Crashed by hide Chatbox

### ISSUE THREAD

**Issue by SehkiTV** [obsproject/obs-studio#6110]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.3

### OBS Studio Log URL

https://obsproject.com/logs/BiHtboPOpPqiBGvw

### OBS Studio Crash Log URL

https://obsproject.com/logs/wQ83uKrn1Ni2me7N

### Expected Behavior

In my chat scnene is a chatbox from Streamlabs and if I hide this than my OBS is crashed.

### Current Behavior

In my chat scnene is a chatbox from Streamlabs and if I hide this than my OBS is crashed.

### Steps to Reproduce

1. Set a Webbroswer
2. Binding a Streamlabs Chatbox
3. Hide them

**Comment by notr1ch** [comment]
This is likely caused by a 3rd party plugin, please test without plugins or make sure all plugins are up to date.

**Comment by MattyFresh68** [comment]
My money is on move plugin.

**Comment by RytoEX** [comment]
Per comments above, this was likely an issue with a plugin. Please try again without any third party plugins, or try again with an updated version of the problematic plugin.
