### ISSUE TITLE
OBS freezing when using Fullscreen APP/GAME etc...

### ISSUE THREAD

**Issue by KBNOtaku** [obsproject/obs-studio#6116]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.3

### OBS Studio Log URL

https://obsproject.com/logs/mvCE7EHMKoBJTRHP

### Expected Behavior

No freezing of OBS when changing into an Fullscreen app/game etc...

### Current Behavior

Fore some time now every time when I have running a Fullscreen Application OBS will freeze for a few second every time I click inside the Fullscreen APP?
This only happens when running a app in full screen, if I run them in windowed mode the freezing do not happen?
OBS doesn't even have to be set to record that app via game capture etc.. even when OBS is just running, as soon as going into any Fullscreen app OBS is freezing for a few seconds?
For example it also happen in an scene where no Display, Window or game Capturing is set. I Also created for testing a scene with only Webcam and nothing else, issue still happens.

1st LOG:
https://obsproject.com/logs/mvCE7EHMKoBJTRHP

2nd LOG:
https://obsproject.com/logs/9rVKYa6WjMnBUqaz

### Steps to Reproduce

1. Run OBS
2. Run an app or game in Fullscreen
3. changing, clicking in or opening a Fullscreen app or game

### Anything else we should know?

System:
Windows 10 up to date
i9-11900k
RTX 3080ti driver up to date
32GB RAM

**Comment by Fenrirthviti** [comment]
We will need a dump file from OBS to investigate this further. Please create a dump file following the process outlined here: https://obsproject.com/forum/resources/598/

Once obtained, please join our Discord and ping me (Fenrir) so you can send me the link privately. Do not share publicly, as it can contain sensitive information from within OBS.

**Comment by KBNOtaku** [comment]
Thank you will do asap!

**Comment by Fenrirthviti** [comment]
Spoke with user and investigated minidump, this is just an expected side effect of switching modes to fullscreen with certain games. Not a bug with OBS.
