### ISSUE TITLE
OBS crashes SteamVR

### ISSUE THREAD

**Issue by schreibmachine** [obsproject/obs-studio#6118]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.2.3

### OBS Studio Log URL

https://obsproject.com/logs/c0EosWbc-snzA9oo

### Expected Behavior

I have used OBS succesfully for recording my whole screen when I'm testing my VR Project in Unity (in editor play mode).

### Current Behavior

Since I made an update to the specified version, it crashes SteamVR and I am unable to restart SteamVR, rendering it completely useless :(

### Steps to Reproduce

1. Open a Unity VR Project, with SteamVR running
2. Start OBS to record the whole screen (the Desktop, not the goggles) + audio output
3. Press "Play" in Editor in unity
4. Watch SteamVR crash :(

### Anything else we should know?

This might be a rather specific problem, but it has never happened before the update to this OBS version & SteamVR only ever crashes when I start OBS. I will try updating OBS.

Thank you btw for making this amazing software :) This is the first time I've ever encountered an issue and I'm very thankful for your work! <3

**Comment by Fenrirthviti** [comment]
This likely needs to be reported to SteamVR support, but I will leave this open for now in case anyone else on the team has any insight.

**Comment by vrbugstream** [comment]
I also have this issue, I launch SteamVR v1..24.7 and test and VR is working fine.
I open OBS and SteamVR starts to lag and eventually crashes.

**Comment by Fenrirthviti** [comment]
As there isn't much we can do on our end, this will need to be reported back to SteamVR, if it's still happening. Closing.
