### ISSUE TITLE
OBS keeps crashing

### ISSUE THREAD

**Issue by Surrenic** [obsproject/obs-studio#6119]
### Operating System Info

Windows 11

### OBS Studio Version

27.2.3

### OBS Studio Log URL

https://obsproject.com/logs/Umn6Id1iefHSb6rD

### Expected Behavior

Don't know why but randomly during streams my OBS just crashes. 

### Current Behavior

OBS freezes and becomes white and then the Windows crash reporter pops up

### Steps to Reproduce

1. Going live
2. Playing a game using game capture
3. Crashes after certain time
...

**Comment by WizardCM** [comment]
This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels below, and if it's determined that this is indeed a bug, then we will re-open this issue.

You have a number of outdated plugins which are likely causing issues.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
