### ISSUE TITLE
Profile export on Linux produces no output

### ISSUE THREAD

**Issue by davidstaudt** [obsproject/obs-studio#6121]
### Operating System Info

Ubuntu 21.04

### OBS Studio Version

27.2.2

### OBS Studio Log URL

https://obsproject.com/logs/m6etzhoNvjavTSHi

### Expected Behavior

Selecting Profile/Export and choosing a writeable destination should produce a profile export file.

### Current Behavior

No output or error.

### Steps to Reproduce

1. Open OBS Studio
2. Select Profile->Export
3. Choose a destination and click 'Open' (I think this is where things go awry - this should be Save rather than Open?)
...

**Comment by WizardCM** [comment]
Cannot reproduce on Ubuntu 20.04.

![image](https://user-images.githubusercontent.com/941350/157592486-400b9c42-439c-4480-9e89-2b4c3bac042d.png)

The 'Open' button is outside of our control and a limitation of the file manager. It should work regardless of what the button says.


How did you install OBS?

**Comment by davidstaudt** [comment]
User error :)

**Comment by RytoEX** [comment]
Duplicate of #4548. The profile export requires you to select a folder, and it exports an entire folder which may contain 1 file or many files.
