### ISSUE TITLE
Craahing when opening camera

### ISSUE THREAD

**Issue by pranshuthegamer** [obsproject/obs-studio#6125]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.3

### OBS Studio Log URL

https://obsproject.com/logs/2CESpgV_rI18oN80

### OBS Studio Crash Log URL

https://pastebin.com/PEjYrJge

### Expected Behavior

The camera should work

### Current Behavior

It crashes when i turn on my camera

### Steps to Reproduce

1. get an hp laptop 
2. open camera in obs

### Anything else we should know?

its an hp laptop with intel 10th gen

**Comment by WizardCM** [comment]
The provided crash log comes from the obs-virtualbg plugin.

**Comment by pranshuthegamer** [comment]
so i gotta update the plugin?

**Comment by WizardCM** [comment]
As the plugin doesn't specify what version you're running, that's worth trying first. If that doesn't work out, raise an issue on their GitHub Issues page.
