### ISSUE TITLE
Horizontal scrollbar in Scenes pane blocks the last entry

### ISSUE THREAD

**Issue by CodeYan01** [obsproject/obs-studio#6130]
### Operating System Info

macOS 12.0

### OBS Studio Version

27.2.2

### OBS Studio Log URL

https://obsproject.com/logs/OOQcX-vlFH7zO1zF

### Expected Behavior

Horizontal scrollbar should not block the last entry or the vertical scrollbar should let us scroll to the last.

### Current Behavior

The last entry is only partially visible.

### Steps to Reproduce

1. Have many scenes enough to make the vertical scrollbar appear
2. Resize the window enough to make the horizontal scrollbar appear (I have the statistics pane docked too.
3. Try to scroll to the last item. Notice that the last scene is only partially visible.
<img width="1429" alt="Screen Shot 2022-03-11 at 8 17 32 PM" src="https://user-images.githubusercontent.com/65320293/157866354-3134321b-0b8b-402a-bb0d-34593eaf2398.png">

**Comment by RytoEX** [comment]
I'm not seeing this on OBS Studio 28.1.2 on macOS 12.6 on my MacBook Pro. Could you re-test in OBS Studio 28.1.2 (or newer)?

**Comment by CodeYan01** [comment]
Will do soon, thanks

**Comment by CodeYan01** [comment]
Retested in 28.1.2 with both Dark and Yami themes, looks like it is fixed. Thanks
