### ISSUE TITLE
OBS does not put itself in the background

### ISSUE THREAD

**Issue by thebigwolfy** [obsproject/obs-studio#6131]
### Operating System Info

Windows 8.1

### OBS Studio Version

27.2.3

### OBS Studio Log URL

https://obsproject.com/logs/1XAIP7_tiVkkXDs8

### Expected Behavior

I expect OBS to get into the background 

### Current Behavior

When obs is in the foreground and for example I open discord, I have to manually (via the - top right) in the background.

### Steps to Reproduce

When obs is in the foreground and for example I open discord, I have to manually (via the - top right) in the background.

### Anything else we should know?

Sorry for bad english, i am translate in google ^^'

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
