### ISSUE TITLE
cannot find Audio desktop in Audio Mixer on MacOS (obs 27.2.2)

### ISSUE THREAD

**Issue by jason11501** [obsproject/obs-studio#6144]
### Operating System Info

macOS 12.0

### OBS Studio Version

27.2.2

### OBS Studio Log URL

https://obsproject.com/logs/OZxXBJ69qb161eDR

### Expected Behavior

bring back Audio Desktop in Audio Mixer.

### Current Behavior

unsee Audio Desktop in Audio Mixer

### Steps to Reproduce

1.Open OBS
2.in Audio Mixer, only see Mic/Aux, cant see Audio Desktop

### Anything else we should know?

![image](https://user-images.githubusercontent.com/55671823/158286072-dc29b6aa-1705-4508-bcec-749b591b522a.jpg)

image attachment

**Comment by WizardCM** [comment]
This is a support issue rather than a bug. Please submit this through one of our support channels below.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
