### ISSUE TITLE
Delete the scene, the video source is not completely deleted

### ISSUE THREAD

**Issue by zengsansui** [obsproject/obs-studio#6145]
### Operating System Info

Windows 11

### OBS Studio Version

27.2.3

### OBS Studio Log URL

https://obsproject.com/logs/Mhe9F38qMmxQDGHm

### Expected Behavior

When deleting a scene, the sources in the scene should all be deleted.

### Current Behavior

1. Set show stinger transition for video/music in scene1.
2.  Click show/hide video/music
3.  Delete scene1
4.  Add video/music in scene2，video/music stay in existing. Add it.
5.  Delete video/music， but video/music stay in audio mixer, and the sound keeps coming out.

### Steps to Reproduce

1.
2.
3.
...

**Comment by WizardCM** [comment]
You have the following third party plugins loaded. Please remove them first and test again:
* StreamFX
* obs-virtualbg

**Comment by zengsansui** [comment]
The issue still exists after removing the third-party plugin.
LOG URL : https://obsproject.com/logs/LY9n4EqkUmeBtfDu

**Comment by sora-blue** [comment]
I reproduced the problem on the lastest version 27.2.4 and the version built from pulled repo on Windows 10. And if you add the source back, you will find its transtition settings gone. So i suppose when the scene is deleted, the transition video source is deleted but the original source is falsely ignored.

**Comment by jpc0** [comment]
I am finding it quite difficult to reproduce this on the current release/27.2 branch. Can you try without any sources loaded or alternatively give more clear instructions to reproduce?

**Comment by sora-blue** [comment]
@jpc0 i reprpduced it on the version built from main branch & 27.4 release by following these steps:
 1. create a media source at current scene
 2. add a stinger transition for it 
 3. double click hide button at sceneitem list to make transition start to play 
 4. create a new scene and delete previous scene 
 Then you should be able to see media source left at Mixer dock.

**Comment by jpc0** [comment]
@sora-blue Just to confirm, should step 4 occur while the stinger transition is still running? The more specific the steps the more likely to get exactly what causes the issue.

**Comment by jpc0** [comment]
Can confirm, I recreates this with any source show transition, if the scene is deleted while a source transition is still running the source is not correctly cleaned up. 

Some more observed behaviour, if the source is readded from the add existing menu the trabsition will no longer fire and the source will not autoplay but will play when using the media controls, it will also lose any information relating to the transition.


Steps:

- Create a source that has an audio element
- Add a show transition with a long duration, I used 10 seconds
- Delete the scene while the transition is running, media element is not cleanly removed

This does not occur on video only sources and does not occur on hide transitions

**Comment by sora-blue** [comment]
@jpc0 Just as you have observed, the key point is to leave the transition playing. The process that sceneitem goes through when scene is removed differs from it when it is removed one by one. Transition sources are removed as expected, but the media source itself is left with one more `active_ref` and `show_ref` as it is **being played in the background**. 

I've tried to fix it at [PR #6337](https://github.com/obsproject/obs-studio/pull/6337) and tested its effect. It seemed to work fine with other parts while solving the problem, but i was not sure if further test is needed. You can refer to [my blog](https://sora-blue.github.io/blog/2022/04/16/Debug-process-on-obs-studio-pr-6337/) for more details.

**Comment by jpc0** [comment]
The reason I was looking into it is because I don't feel like the issue is in obs-scene but somewhere else in the code base, I looked at your PR and although as you said it does solve the problem, I'm not sure on what is expected behavior here, should ref have been incremented twice? Should another function be decrementing the refs and not the source itself? Also where is scene_enum_sources in the callstack when a scene is being destroyed.

**Comment by jpc0** [comment]
Something we may need to look into, in the [obs_sceneitem_destroy](https://github.com/obsproject/obs-studi/blob/d9865bdffb5b8cb6ce616b20087b75d4611d13c6/libobs/obs-scene.c#L2077) method the transitions are released but in the [obs_sceneitem_remove](https://github.com/obsproject/obs-studio/blob/d9865bdffb5b8cb6ce616b20087b75d4611d13c6/libobs/obs-scene.c#L2103) method they are set to NULL before release is called, this does not happen however if the scene is destroyed. I was looking into why if the media item is removed while the transition is running everything works as expected however if the scene is running we have a lingering ref.

**Comment by jpc0** [comment]
So I can confirm even if I replace [remove_all_items](https://github.com/obsproject/obs-studio/blob/d9865bdffb5b8cb6ce616b20087b75d4611d13c6/libobs/obs-scene.c#L214) with a loop that just iterates over all the items and calls [obs_sceneitem_remove](https://github.com/obsproject/obs-studio/blob/d9865bdffb5b8cb6ce616b20087b75d4611d13c6/libobs/obs-scene.c#L2103) I observe the same behavior which makes me think that the issue is in the calling code and not in libobs itself. 

If I have some time in the next few days I will write a simple libobs backed program that just calls the libobs functions to create a scene, set a show transition with a long duration, call the transition and then remove the scene and see if the same behavior is observer without the UI code.

**Comment by PatTheMav** [comment]
Is this still an issue with v30? I just tried to reproduce the issue given the steps outlined in https://github.com/obsproject/obs-studio/issues/6145#issuecomment-1121203122 but I do not get a media source lingering in the mixer when deleting the source during the transition.

**Comment by PatTheMav** [comment]
I also get this in the log, suggesting that both the media source as well as the associated transition were destroyed:

```
debug: private source 'Media Source Show Transition' destroyed
debug: source 'Media Source' destroyed
```
