### ISSUE TITLE
Python API -> Enum

### ISSUE THREAD

**Issue by sweetngx** [obsproject/obs-studio#6150]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.3

### OBS Studio Log URL

None

### Expected Behavior

I discovered that while Lua can simply list source-dependent filters, this support is not available for python. Maybe there is a method but I don't know, but it seems it is not possible to access it with obs.obs_source_enum_filters

### Current Behavior

I discovered that while Lua can simply list source-dependent filters, this support is not available for python. Maybe there is a method but I don't know, but it seems it is not possible to access it with obs.obs_source_enum_filters

### Steps to Reproduce

1.
2.
3.
...

**Comment by skeletonbow** [comment]
The OBS Discord server has a #scripting channel for discussion of script related development issues.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by sweetngx** [comment]
src = obs.obs_get_source_by_name("mysource")
    sources = obs.obs_source_backup_filters(src)
    print(obs.obs_data_get_string(obs.obs_data_array_item(sources, 1), "name"));

After working for a few hours I found an alternative way to access the filters
