### ISSUE TITLE
[lua script]calling `obs_frontend_set_current_scene()` in a timer when a frontend event callback has been registered crashes OBS

### ISSUE THREAD

**Issue by rhetr** [obsproject/obs-studio#6151]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.3

### OBS Studio Log URL

https://obsproject.com/logs/umUbGPG7-5p7PZqa

### Expected Behavior

given this lua script:
```lua
local obs = obslua

local current_cycle = "cycle_a"
local next_cycle = "cycle_b"
local cycling = false
local freq = 1

local function sceneCyclerCallback(e)
  print('dj khaled')
end

local function cycleScenes()
  local next_scene = obs.obs_get_source_by_name(next_cycle)
  obs.obs_frontend_set_current_scene(next_scene)
  obs.obs_source_release(next_scene)

  local last = current_cycle
  current_cycle = next_cycle
  next_cycle = last
end

function script_update(settings)
  freq = obs.obs_data_get_int(settings, "freq")
  if freq == 0 then
    freq = 1
  end

  if cycling then
    obs.timer_remove(cycleScenes)
  else
    cycling = true
  end
  obs.timer_add(cycleScenes, freq * 1000)
end

function script_description()
    return [[
        Cycle between scenes
    ]]
end

function script_properties()
    local props = obs.obs_properties_create()
    obs.obs_properties_add_int(props, "freq", "Frequency (seconds)", 1, 10, 1)
    obs.obs_frontend_add_event_callback(sceneCyclerCallback)

    return props
end
```
I expected the script to:
- switch between scenes `cycle_a` and `cycle_b` via `obs_frontend_set_current_scene()`
- whenever the scene is switched, `sceneCyclerCallback` should be called and "dj khaled" should be printed in the script log

### Current Behavior

OBS crashes

### Steps to Reproduce

1. create two scenes `cycle_a` and `cycle_b`
2. load the given lua script into obs

### Anything else we should know?
if either `obs.obs_frontend_add_event_callback(sceneCyclerCallback)` or `obs.obs_frontend_set_current_scene(next_scene)` is commented out, then OBS does not crash.

**Comment by rhetr** [comment]
i think i misunderstood the api and have to use `obs.signal_handler_connect` instead.

**Comment by rhetr** [comment]
found a different way to script what i needed so doesn't matter

**Comment by HeedfulCrayon** [comment]
> found a different way to script what i needed so doesn't matter

Do you mind sharing how you got around this issue?

**Comment by rhetr** [comment]
I used [`script_tick`](https://obsproject.com/docs/scripting.html?highlight=enum_sources#script_tick) instead of using a timer, which worked for my purpose.
