### ISSUE TITLE
Automatic reconnection of audio sources when disconnected?

### ISSUE THREAD

**Issue by GanerCodes** [obsproject/obs-studio#6153]
### Operating System Info

Other

### Other OS

Gentoo

### OBS Studio Version

27.2.3

### OBS Studio Log URL

Nothing relevent is displayed in logs.

### Expected Behavior

When Pipewire restarts (or the OBS capture nodes somehow get unlinked) OBS should, ideally, try and reconnect to the devices.

### Current Behavior

The OBS GUI shows that the audio devices are active, but receives no input. This can be verified by the lack of OBS nodes in Helvum

### Steps to Reproduce

Rearrange some links/restart pipewire and OBS won't adapt to it correctly

**Comment by kkartaltepe** [comment]
I'm just going to close this as more of a feature request than anything else. Other than not supporting pipewire, we only support pulseaudio/alsa/jack as interfaces so any behavior difference between pulse and pipewire is a pipewire bug. But also I don't even have any programs that can keep playing audio if the pulse server dies.
