### ISSUE TITLE
Include representative screenshots with Linux package

### ISSUE THREAD

**Issue by Eonfge** [obsproject/obs-studio#6159]
### Operating System Info

Other

### Other OS

Fedora Linux 35

### OBS Studio Version

27.2.3

### OBS Studio Version (Other)

Flathub

### OBS Studio Log URL

Not applicable 

### OBS Studio Crash Log URL

Not applicable 

### Expected Behavior

The current GNOME Software and Flathub listing only has a single image to display. Moreover, that image is taken on Windows. This is no deal-breaker for me, but the FreeDesktop AppStream standard does have certain recommendations for screenshots:

https://freedesktop.org/software/appstream/docs/chap-Quickstart.html#qsr-app-screenshots-info

If you approve, I would ask some active Linux streamers to provide a screenshot of their setup, so that OBS can use those images as promotional material on Linux.

Example of image I would wish to include;
https://www.gamingonlinux.com/2022/02/obs-studio-272-is-out-bringing-flatpak-support-and-much-more/

### Current Behavior

Easy example;
https://flathub.org/apps/details/com.obsproject.Studio

### Steps to Reproduce

Not applicable

**Comment by feetstv** [comment]
It would be better for such screenshots to be internally made, rather than outsourced. There’s no reason we can’t make conformant screenshots ourselves. I would personally consider this a documentation issue, so I would be happy to do it.

**Comment by Eonfge** [comment]
For me, the biggest issue is lacking any 'representive' images. I'm no streamer so I don't have any setup to speak of. If a frew streamers could help us, that would be great. 

If you can make some representitive screenshots, meeting most of the screenshot-requirements, then that would be great. I'll then gladly help you with the .metainfo.xml file.

**Comment by WizardCM** [comment]
Here's where the Flatpak screenshots are defined:
https://github.com/obsproject/obs-studio/blob/02e54103813f90eac34530de95c868251df01b9b/UI/xdg-data/com.obsproject.Studio.appdata.xml.in#L34-L36

**Comment by mihawk90** [comment]
> Fedora Linux 35

> GNOME Software

I'm not sure if you're referring only to the Flatpak listing in GNOME software or to the native version too, but keep in mind that the native version is not under OBS' control. They are packaged by RPM Fusion so the right place to raise that is probably the RPM Fusion bugzilla.

**Comment by Eonfge** [comment]
> Since the appdata is part of the repo it would be packaged along with it

Correct. The images will have to be put somewhere inside this repository or on your website, and then they'll have to be references in the .metainfo.xml file. 

I wasn't actually aware of a Fedora Linux native version. I would recommend everybody to use the Flathub version since that's the official version with all codecs and such bundled.

**Comment by LiamDawe** [comment]
Hi, got an email from someone today asking about this, I attached a shot to them but here it is too, feel free to use it
![Screenshot_20220317_132102](https://user-images.githubusercontent.com/83223/158817622-e68a18b5-7f4a-46c9-be25-5d6a50874708.png)
.

**Comment by dodgepong** [comment]
We're actually already in the process of updating our library of screenshots for use in promotional contexts such as store pages -- we'll be sure to include Linux in this list of things to update.

We use Github issues strictly for bug reports, so given that this isn't a bug, I'm going to close this. But we've taken note of the request and will take appropriate steps to update the screenshots in due time.
