### ISSUE TITLE
OBS allows to add v4l2 device multiple times without any alert

### ISSUE THREAD

**Issue by ggodlewski** [obsproject/obs-studio#6170]
### Operating System Info

Ubuntu 20.04

### OBS Studio Version

Git

### OBS Studio Log URL

https://obsproject.com/logs/gFGVr2wQRdfH0VqL

### Expected Behavior

I added webcam as V4L2_Device_1 to Scene1 and then added the same camera as V4L2_Device_2 to Scene2
The second source didn't work. I didn't get any alert.

There is only "v4l2-input: Initialization failed" in the log which is hard to find.

Similar behavior happens when I have 2nd camera connected as V4L2_Device_2 and then change it to 1st camera (which is already connected as V4L2_Device_1 in another scene). It just freezes with last frame of 2nd camera.

### Current Behavior

User should be notified that the webcam is already connected as source.
Or it should prevent user from selecting camera which already connected.

### Steps to Reproduce

I added webcam as V4L2_Device_1 to Scene1 and then added the same camera as V4L2_Device_2 to Scene2
The second source didn't work. I didn't get any alert. There is only "v4l2-input: Initialization failed" in the log which is hard to find.

Similar behavior happens when I have 2nd camera connected as V4L2_Device_2 and then change it to 1st camera (which is already connected as V4L2_Device_1 in another scene). It just freezes with last frame of 2nd camera.

**Comment by kkartaltepe** [comment]
This is working as intended, and consistent across platforms.

While I agree its unintuitive this is more of a feature request then a bug.

**Comment by Jookia** [comment]
It's 2024 and I just spent an hour troubleshooting only to find this was my issue. Is there no better way to fix this, at least by adding a hint in the log? I understand this is difficult to fix: I have two cameras that are identical USB-wise so it can't remember which is picked in the scene. I'm happy to have a go at trying to implement a solution here.
