### ISSUE TITLE
PROBLEM WHEN RECORD 1 WINDOW CHROME WITH GOOGLE MEET TAB

### ISSUE THREAD

**Issue by huuson889** [obsproject/obs-studio#6181]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.3

### OBS Studio Log URL

https://snipboard.io/tXGQUk.jpg

### OBS Studio Crash Log URL

https://snipboard.io/tXGQUk.jpg

### Expected Behavior

When other present there screen in google meet, I can see it in chrome browser but sometime when a change windows by Alt + Tab or open other windows , the present on gg meet became dark in OBS

### Current Behavior

OBS must record all gg meet same I see on chrome browser when I open other app windows or I change windows

### Steps to Reproduce

1. Change between windows app
2. Use Alt + Tab or click on other app on taskbar

**Comment by huuson889** [comment]
https://snipboard.io/tXGQUk.jpg
Screen Capture is here

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
