### ISSUE TITLE
Unable to edit and do anything besides add scenes

### ISSUE THREAD

**Issue by czadikem** [obsproject/obs-studio#6183]
### Operating System Info

Other

### Other OS

AlmaLinux

### OBS Studio Version

27.2.3

### OBS Studio Log URL

Unable to do this because of the issue

### Expected Behavior

I should be able to add a source edit the settings etc.

### Current Behavior

I can only interact with obs-studio when I add scenes and also when I click the studio mode button.

### Steps to Reproduce

1. Install Almalinux or RockyLinux
2. Install Flathub repo file or the rpmfusion repo
3. Install OBS-Studio
4. Launch it and try to interact with OBS
...

**Comment by kkartaltepe** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
