### ISSUE TITLE
ffmpeg output nvenc Recording error randomly occurs

### ISSUE THREAD

**Issue by krakow10** [obsproject/obs-studio#6184]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

27.2.3

### OBS Studio Log URL

https://obsproject.com/logs/KhjIwsTvNlywQUsS

### Expected Behavior

Streaming continues without issues

### Current Behavior

Popup window "An unspecified error occurred while recording." ends stream prematurely

### Steps to Reproduce

1. Record hevc_nvenc or h264_nvenc with ffmpeg custom output using obnoxiously high bitrate (50mbps-200mbps).  I usually encode 1440p at 120fps but it still happens at 1440p 60fps.  Happens **silently** with Output to file (continues writing audio but video is frozen in the file) and with error dialogue on Output to URL.
2. Stream for seconds, minutes, or hours waiting for error.  I have had 14 hour streams where the error does not occur and times where it happened within seconds of pressing Record.
3. Recording error
![unspecified error](https://user-images.githubusercontent.com/3529698/159406025-e930a515-9ac6-48a0-9f6b-2261e3e1aef9.png)

### Anything else we should know?

The log entries printed when the error occurs are these:
```
20:07:51.556: receive_video: Error encoding video: Invalid argument
20:07:51.629: process_packet: Error writing packet: Invalid argument
```

I am using custom output to stream SRT with multiple audio tracks.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
