### ISSUE TITLE
Crash when using with Video Delay (Async)

### ISSUE THREAD

**Issue by sweetngx** [obsproject/obs-studio#6188]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.3

### OBS Studio Log URL

https://obsproject.com/logs/s0_fUTqQxiW9Q9EA

### Expected Behavior

-

### Current Behavior

When I change track from VLC playlist (prev, next) after adding Video Delay (Async) to VLC source, I get a Crash error. 

### Steps to Reproduce

1. Add a VLC source
2. Add more than one file to the playlist
3. Add a Video Delay filter to the VLC source
4. Switch tracks until a crash occurs (usually only a few times necessary)
...

**Comment by Fenrirthviti** [comment]
Updated the reproduction steps for you, in the future please make sure you fill out the entire template. Reproduction steps will help us understand if you're doing something different than us, but luckily I was able to reproduce this.

Marking confirmed as well.

**Comment by gxalpha** [comment]
Is this the same crash as https://github.com/obsproject/obs-studio/issues/5831?

**Comment by sweetngx** [comment]
> Could this be the same crash as #5831? Crash logs look suspiciously similar

Yes, I think it's due to the same issue. But I found a solution. Now I'm using Render Delay. You know there is a 500ms limit on Render Delay but I was able to increase it. I had to recompile the OBS Source codes. Works great and stable now

**Comment by tuduweb** [comment]
does this PR #7077 work?
@Fenrirthviti @gxalpha

**Comment by jp9000** [comment]
Merged the proposed fix a bit prematurely. I think it's okay if this issue lingers for 28 for now -- it's a very niche scenario with a very rarely-used filter.
