### ISSUE TITLE
Local storage is not shared across Browser Source and Custom Dock

### ISSUE THREAD

**Issue by ivanosh** [obsproject/obs-studio#6202]
### Operating System Info

Windows 10

### Other OS

macOS

### OBS Studio Version

27.2.3

### OBS Studio Log URL

https://obsproject.com/logs/MBTz0KLKbOqL8e3S

### Expected Behavior

I have my own fully local widget. It have2 html files: `widget.html` & `config.html`.
`widget.html` is used as Browser Source
`config.html` -- Custom Dock to configure widget.
Settings are saved to local storage.
I want to have ability to write smth to local storage from `config.html` and read it in `widget.html`

### Current Behavior

With latest release Browser Source and Custom Dock have its own local storages

### Steps to Reproduce

1. Write smth to local storage from Custom Dock
2. Try to read it from Browser Source
Result: There is no saved data

### Anything else we should know?

This functionality was working in previous release: 27.1.3

**Comment by WizardCM** [comment]
If this is for local files, this is probably expected - in local file mode the sources now use http://absolute/C:/ whereas docks tend to use file:///

**Comment by PaulSTL** [comment]
This used to work until a few months ago. I also had this set up, dock for config, save to localstorage, read by browser source. if browser source page is put in a dock they interact, same if both in browser source.

**Comment by gxalpha** [comment]
Closing per the comment above, use `http://absolute/C:/` in your Docks.

**Comment by ivanosh** [comment]
> This used to work until a few months ago. I also had this set up, dock for config, save to localstorage, read by browser source. if browser source page is put in a dock they interact, same if both in browser source.
> 
> using the http://absolute/C:/ path in the Dock url gets it working again

Just found this comment :) It works, thank you!

**Comment by hongson4477** [comment]
> This used to work until a few months ago. I also had this set up, dock for config, save to localstorage, read by browser source. if browser source page is put in a dock they interact, same if both in browser source.
> 
> using the http://absolute/C:/ path in the Dock url gets it working again

you save my life
