### ISSUE TITLE
RTSP Fails in 27.2.x works in 27.1.x

### ISSUE THREAD

**Issue by cswroe** [obsproject/obs-studio#6204]
### Operating System Info

Windows 11

### OBS Studio Version

27.2.3

### OBS Studio Log URL

https://obsproject.com/logs/MweBQVAj_OD2U7aL

### Expected Behavior

Media Source using RTSP to show in scene.

### Current Behavior

A small red square in the upper left then disappears when resizing the red square disappears. Everything works correctly in 27.1.3.  I have tried this with an upgrade and with a fresh install, same behavior.
Link to log from the upgrade from .1 to .2 : https://obsproject.com/logs/YtSK5HTMJ4ZmSW4w

### Steps to Reproduce

1. Create Media Source
2. Add URL for RTSP
3. See small red square in the upper left which is not resizable then disappears. 
4. There is no audio from rtsp when the red square show.
...

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by cswroe** [comment]
I have already talked with support in Discord. This is a regression between versions.

**Comment by derrod** [comment]
Do you have a 27.1.3 log as well?

**Comment by tt2468** [comment]
Does your URL use special unicode characters? It doesn't appear to render correctly in the log files.

**Comment by cswroe** [comment]
There are no special characters. The password contains standard symbols (!@#$%)
rtsp://username:password@192.168.50.182:554/Streaming/Channels/1

**Comment by Fenrirthviti** [comment]
Does your password contain an @ symbol in it? Can you try a password that does not contain special characters, just to be sure?

**Comment by RytoEX** [comment]
What device are you getting the RTSP stream from? Have you tried opening it via ffmpeg/ffplay CLI tools?

**Comment by RytoEX** [comment]
> I can open the stream with the same URL in VLC without issue.

While interesting, I'm more interested in whether or not you can open it in ffplay/ffmpeg, since our Media Source uses FFmpeg libraries.

**Comment by cswroe** [comment]
> > I can open the stream with the same URL in VLC without issue.
> 
> While interesting, I'm more interested in whether or not you can open it in ffplay/ffmpeg, since our Media Source uses FFmpeg libraries.

Seems to work fine with ffplay

`C:\Users\cwroe\Downloads\ffmpeg-2023-01-04-git-4a80db5fc2-full_build\ffmpeg-2023-01-04-git-4a80db5fc2-full_build\bin>ffplay.exe rtsp://admin:RedGreen123@192.168.50.181:554/Streaming/Channels/1
ffplay version 2023-01-04-git-4a80db5fc2-full_build-www.gyan.dev Copyright (c) 2003-2023 the FFmpeg developers
  built with gcc 12.1.0 (Rev2, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      57. 43.100 / 57. 43.100
  libavcodec     59. 56.100 / 59. 56.100
  libavformat    59. 34.102 / 59. 34.102
  libavdevice    59.  8.101 / 59.  8.101
  libavfilter     8. 53.100 /  8. 53.100
  libswscale      6.  8.112 /  6.  8.112
  libswresample   4.  9.100 /  4.  9.100
  libpostproc    56.  7.100 / 56.  7.100
Input #0, rtsp, from 'rtsp://admin:RedGreen123@192.168.50.181:554/Streaming/Channels/1':
  Metadata:
    title           : Media Presentation
  Duration: N/A, start: 0.000000, bitrate: N/A
  Stream #0:0: Video: h264 (Main), yuvj420p(pc, bt709, progressive), 2688x1520 [SAR 190:189 DAR 16:9], 20 fps, 30 tbr, 90k tbn
  Stream #0:1: Audio: pcm_mulaw, 8000 Hz, mono, s16, 64 kb/s
[swscaler @ 0000021db5733340] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0000021db5832340] deprecated pixel format used, make sure you did set range correctly
[swscaler @ 0000021db59538c0] deprecated pixel format used, make sure you did set range correctly
    Last message repeated 1 times
Switch subtitle stream from #-1 to #-1 vq=  385KB sq=    0B f=0/0
  14.31 A-V: -0.002 fd=   1 aq=    8KB vq= 1015KB sq=    0B f=0/0`

**Comment by RytoEX** [comment]
> This is a basic IP camera, nothing special.

Unfortunately, I don't think any of the cameras I have access to do RTSP. Would be great to know what the actual model is to see if it's something a project member has.

**Comment by cswroe** [comment]
> > This is a basic IP camera, nothing special.
> 
> Unfortunately, I don't think any of the cameras I have access to do RTSP. Would be great to know what the actual model is to see if it's something a project member has.

The specific ones I use for RTSP in OBS are from Alibi Security, Model ALI-NS1124VR and ALI-NS1025VR.  I have also tried it on their previous models, which are rebranded Hikvision, Model ALI-NS3014R, ALI-NS4014R, and ALI-NS3024R.

I am looking to upgrade the cameras I use for OBS in the near future. So if there is a camera that does RTSP that is working, I am game.

**Comment by cswroe** [comment]
Just to update, it looks like we are somewhat back in business with 29.0.0  I was able to get the cameras connected but had to remove any special characters in the password.
