### ISSUE TITLE
Desktop capture on Wayland / Nvidia results in black/grey screen

### ISSUE THREAD

**Issue by Pshemas** [obsproject/obs-studio#6208]
### Operating System Info

Other

### Other OS

Linux

### OBS Studio Version

27.2.3

### OBS Studio Log URL

https://obsproject.com/logs/JbEvFrPVBgzC9HYt

### Expected Behavior

Screen capture on Wayland Nvidia should work :) .

### Current Behavior

When I try to enable screen capture via Pipewire under Wayland Nvidia session I get nothing (grey screen). But the note on the Gnome's top bar that screen sharing is on displays correctly.

### Steps to Reproduce

1. Open OBS under Wayland with Nvidia GPU
2. Click + button and choose Pipewire screen capture
3. Choose screen

**Comment by Fenrirthviti** [comment]
https://bugs.kde.org/show_bug.cgi?id=448944

Pretty sure this is a bug with Wayland and NVIDIA drivers, not anything on our side.

**Comment by kkartaltepe** [comment]
Nvidia Proprietary drivers are known to be incompatible with the wayland graphics environment, and as such are unsupportable by us.

**Comment by licamla** [comment]
i am gnome user,
screen capture on Wayland Nvidia should is working with firefox, but obs can not.i do not known what am I doing wrong.
log output:
```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/locale.ini
Attempted path: /usr/share/obs/obs-studio/locale.ini
Attempted path: share/obs/obs-studio/locale/zh-CN.ini
Attempted path: /usr/share/obs/obs-studio/locale/zh-CN.ini
info: Using preferred locale 'zh-CN'
Attempted path: share/obs/obs-studio/themes/Dark.qss
Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
info: Command Line Arguments: --verbose
info: Platform: Wayland
info: CPU Name: AMD Ryzen 9 5900X 12-Core Processor
info: CPU Speed: 3318.753MHz
info: Physical Cores: 12, Logical Cores: 24
info: Physical Memory: 64261MB Total, 55591MB Free
info: Kernel Version: Linux 5.15.26-gentoo-x86_64
info: Distribution: Gentoo Unknown
info: Session Type: wayland
info: Qt Version: 5.15.2 (runtime), 5.15.2 (compiled)
info: Portable mode: false
Attempted path: share/obs/obs-studio/themes/Dark/no_sources.svg
Attempted path: /usr/share/obs/obs-studio/themes/Dark/no_sources.svg
QMetaObject::connectSlotsByName: No matching signal for on_tbar_position_valueChanged(int)
QMetaObject::connectSlotsByName: No matching signal for on_actionShowTransitionProperties_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_actionHideTransitionProperties_triggered()
info: OBS 27.2.3 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 48000
	speakers:        2
info: ---------------------------------
info: Initializing OpenGL...
info: Using EGL/Wayland
info: Initialized EGL 1.5
info: Loading up OpenGL on adapter NVIDIA Corporation NVIDIA GeForce GTX 1070/PCIe/SSE2
info: OpenGL loaded successfully, version 3.3.0 NVIDIA 470.103.01, shading language 3.30 NVIDIA via Cg compiler
info: ---------------------------------
info: video settings reset:
	base resolution:   1920x1080
	output resolution: 1920x1080
	downscale filter:  Bicubic
	fps:               60/1
	format:            NV12
	YUV mode:          sRGB/Full
info: NV12 texture support not available
info: Audio monitoring device:
	name: 默认
	id: default
info: ---------------------------------
warning: Failed to load 'en-US' text for module: 'decklink-captions.so'
warning: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
info: [pipewire] Available captures:
info: [pipewire]     - Desktop capture
info: [pipewire]     - Window capture
libDeckLinkAPI.so: 无法打开共享对象文件: 没有那个文件或目录
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
info: No blackmagic support
warning: v4l2loopback not installed, virtual camera disabled
info: [obs-browser]: Version 2.17.13
info: [obs-browser]: CEF Version 95.0.0-MediaHandler.2463+g3b3ac84+chromium-95.0.4638.69
info: NVENC supported
info: FFMPEG VAAPI supported
info: [vlc-video]: VLC 3.0.16 Vetinari found, VLC video source enabled
info: ---------------------------------
info:   Loaded Modules:
info:     vlc-video.so
info:     text-freetype2.so
info:     rtmp-services.so
info:     obs-x264.so
info:     obs-transitions.so
info:     obs-outputs.so
info:     obs-filters.so
info:     obs-ffmpeg.so
info:     obs-browser.so
info:     linux-v4l2.so
info:     linux-pulseaudio.so
info:     linux-decklink.so
info:     linux-capture.so
info:     linux-alsa.so
info:     image-source.so
info:     frontend-tools.so
info:     decklink-ouput-ui.so
info:     decklink-captions.so
info: ---------------------------------
info: ==== Startup complete ===============================================
info: All scene data cleared
info: ------------------------------------------------
info: pulse-input: Server name: 'PulseAudio (on PipeWire 0.3.36) 15.0.0'
info: pulse-input: Audio format: s32le, 48000 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_output.pci-0000_0a_00.4.analog-stereo.monitor'
...

info: [pipewire] desktop selected, setting up screencast
info: [pipewire] server version: 0.3.36
info: [pipewire] library version: 0.3.36
info: [pipewire] header version: 0.3.36
info: [pipewire] created stream 0x556e733dbe00
info: [pipewire] playing stream…
info: [pipewire] window selected, setting up screencast
info: [pipewire] server version: 0.3.36
info: [pipewire] library version: 0.3.36
info: [pipewire] header version: 0.3.36
info: [pipewire] created stream 0x556e733de400
info: [pipewire] playing stream…
```

**Comment by spagoc** [comment]
The Nvidia proprietary driver v. 510.60.02 is compatible with Wayland on Fedora 36 prerelease.
I may confirm this obs bug in that environment but it's the same in Firefox. 
Chromium has also the bug for the entire screen (but Chromium can capture a browser tab).

**Comment by kkartaltepe** [comment]
Nvidia is still not supported due to known incompatibilities throughout the pipewire capture and wayland stack. If your configuration happens to work congratulations and enjoy, if not dont file bugs as its an unsupported platform until the bugs in drivers and the wayland stack get resolved.

**Comment by lucario** [comment]
@kkartaltepe Could you link to an issue tracking nvidia support? F36 went ahead with defaulting to wayland on nvidia proprietary so it's only a matter of time where this will have to be a supported configuration.

**Comment by kkartaltepe** [comment]
Only an nvidia engineer could give you tracking information for issues with their driver, so no i cannot link anything. As for bugs related to other open source code im not tracking those but anything that matters would probably be resolved by the next release.

**Comment by babafc** [comment]
It used to work couple months ago (before 510, i think 495 was it and Gnome defaulted to EGL over GBM at that time). I used it on Gnome Wayland,  Arch, Pipewire, Nvidia.

Somewhere around driver 510 release it stopped working

**Comment by licamla** [comment]
> It used to work couple months ago (before 510, i think 495 was it and Gnome defaulted to EGL over GBM at that time). I used it on Gnome Wayland, Arch, Pipewire, Nvidia.
> 
> Somewhere around driver 510 release it stopped working

obs is work with driver 510.73.05.Only the window capture has black edges.
https://www.bilibili.com/video/BV19F411F7Vt/?vd_source=c06e9b4de900138205ade500d5352ca6

**Comment by kkartaltepe** [comment]
Nvidia is still unsupported, please do not use bug reports as a forum to discuss your success or failure with nvidia drivers, we have a [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum) for you to discuss obs.

**Comment by andrewfader** [comment]
I understand it's not implemented yet @kkartaltepe, with the latest driver releases, everything pretty much does work for wayland screen sharing and pipewire. There was a bug in egl-wayland https://github.com/NVIDIA/egl-wayland/commit/fee26e9cbd0890bab890f4534d7e92e78d8d0d37#commitcomment-75786195 which is resolved in 5.57.

**Comment by kkartaltepe** [comment]
Again, this bug report is not the place to track random issues with nvidia or its supportability. Wait until you see us report that nvidia is supported before filing bugs. Otherwise you can discuss in the forums and discord, since our bug reports are not for off-topic discussion about unrelated issues to the original report.

**Comment by wade-welles** [comment]
Is there anyway to resolve the black edges around the pipewire window sharing, or do I have to rebuild obs so it uses X?
