### ISSUE TITLE
Browser: When video is in full screen, video controls should disappear after a few seconds and remain invisible

### ISSUE THREAD

**Issue by jeffbfx** [obsproject/obs-studio#6210]
### Operating System Info

macOS 10.15

### OBS Studio Version

27.2.2

### OBS Studio Log URL

https://obsproject.com/logs/s2_m_mm6fN86qvm8

### Expected Behavior

When using the OBS browser to record a video, and the video is put in full-screen mode, the on-video controls (play/pause/etc.) should consistently disappear with the same behavior exhibit in the default non-full-screen mode.

### Current Behavior

When using the OBS browser to record, I wanted to put the video I was recording in full screen mode in the OBS browser.

The problem is that in full-screen mode in the OBS browser, the on-screen video controls often don't fade/disappear like they're supposed to do.

The workaround was to set OBS to capture the small screen image of the video.  (Quality is good in the final recording—video is not hi-res). When playing in the small screen, the on-screen video controls  work as expected.

### Steps to Reproduce

1. Find a website that has a video occupying a small portion of the web page.
2. Start playing the video and move the mouse of the video image area (click on this area if you want to)
3. Observe that the on-video-image Play/Pause, etc. controls disappear within a few seconds.
4. Set the video in the OBS browser to full-screen.
5. Move the mouse off-screen and/or outside the OBS browser window
6. Observe that the video controls either 1) don't disappear and/or 2) reappear before the video is through playing. (The behavior is not consistent in how it misbehaves.). The point is that the video controls should behave identically with both the small and full-screen modes inside the OBS browser.
...

**Comment by Fenrirthviti** [comment]
This is not really a supported use for browser source, as it's not a true browser and isn't really expected to be interacted with. If you want to record a video from a website, you should just capture a proper browser like Chrome or Firefox.
