### ISSUE TITLE
Can't resize window

### ISSUE THREAD

**Issue by Timtaran** [obsproject/obs-studio#6212]
### Operating System Info

Other

### Other OS

Fedora Linux Workstation 35

### OBS Studio Version

27.2.3

### OBS Studio Log URL

um....

### Expected Behavior

I'm want to resize window

### Current Behavior
![image](https://i.imgur.com/vTtQ7Qq.png)

### Steps to Reproduce

1. Use 768 height monitor

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
