### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by for-the-zero** [obsproject/obs-studio#6213]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Log URL

(sorry,i am uninstalled now)

### Expected Behavior

when I use obs,it only had black screen and my mouse
i can see my mouse but I can't see other

my computer:cpu(amd a4-9125 Radeon r3),gpu(cpu igd,other one didn't work)

### Current Behavior

black screen but can see my mouse

### Steps to Reproduce

1.add my computer screen

**Comment by derrod** [comment]
GitHub issues are not for support, please use our Discord or forums instead.
