### ISSUE TITLE
scroll bar blocks lock in sources box

### ISSUE THREAD

**Issue by G2G2G2G** [obsproject/obs-studio#6215]
### Operating System Info

Other

### Other OS

Arch / Manjaro

### OBS Studio Version

27.2.1

### OBS Studio Log URL

no

### Expected Behavior

![1](https://user-images.githubusercontent.com/50514477/160247160-39b1875f-e1f4-4e93-bf8d-284937d4db2d.jpg)

### Current Behavior

![1](https://user-images.githubusercontent.com/50514477/160247170-fa0178d7-9ade-4b4f-bbe1-9e9e348d3aba.jpg)

### Steps to Reproduce

1. make several "sources"
2. drag the height bar down so it adds a scroll bar to the sources...
3. gg
...

### Anything else we should know?

This doesn't seem to do this on windows, it moves the locks over to the left as you would expect. been doing it for past year or so

I assume it does this in the scenes & audio mixer too..

**Comment by RytoEX** [comment]
Please include an OBS log as this helps us verify components of the local environment.

**Comment by kkartaltepe** [comment]
I cannot replicate this.

**Comment by G2G2G2G** [comment]
I tried on my laptop and I can't either, my desktop computer is cursed. Time to sodoku

https://user-images.githubusercontent.com/50514477/161324981-17fd4ee1-fa04-4087-9ef4-b666434b3bea.mp4

**Comment by kkartaltepe** [comment]
I believe there is an issue with switching themes without restarting obs. Since you appear to use a theme that sets the scrollbar to lay on top of content that property may be preserved when you switch themes without restarting.

I believe you were on another issue where non-standard base themes were affecting obs, so you may not be able to start obs on the dark theme without a conflicted theme loading first. But you could try it and see if that resolves the issue.

**Comment by G2G2G2G** [comment]
All themes do this as shown, and my obs is just the default from pacman...
It does it on startup, with any theme. Video just demonstrates 2 themes doing it in different ways.
Why are my themes non-standard?

**Comment by kkartaltepe** [comment]
Thanks for confirming, again in the other issue if you figure out what sets this `QT_QPA_PLATFORMTHEME` on your system that would be interesting to know.

**Comment by G2G2G2G** [comment]
https://wiki.archlinux.org/title/qt this mentions qt5ct
pacman says qt5ct is required by xfce-settings... so I'm guessing something xfce related on my install at least uses it, I don't use xfce, I use i3wm, but I do use thunar.. and that is probably why? According to the docs the env variable makes it so settings are picked up by Qt applications, which OBS obviously doesn't like, but it is required for all the other programs.
