### ISSUE TITLE
Unexpected Crashing on Win 11

### ISSUE THREAD

**Issue by JoshuaPoddoku** [obsproject/obs-studio#6223]
### Operating System Info

Windows 11

### OBS Studio Version

27.2.3

### OBS Studio Log URL

https://drive.google.com/file/d/1JuHsryUZEQRTu3KFWF-hJwPyce0hht69/view?usp=sharing

### OBS Studio Crash Log URL

https://drive.google.com/file/d/1PshpNZ2px5kM8tJTum6W3As2YRkFdKu1/view?usp=sharing

### Expected Behavior

OBS was running smoothly when connected to multiple media with one audio source being monitored. 

### Current Behavior

![image](https://user-images.githubusercontent.com/31725457/160299578-7ae3d616-2963-4565-9b11-676df8571bbd.png)
Tried changing and removing audio and video sources. 

### Steps to Reproduce

1. Add Media (Audio in the background)
2. Connect a Virtual Wifi Cam (EpocCam in my case)
3. Start recording
...

**Comment by Fenrirthviti** [comment]
This crash is occurring in the 3rd party virtualcam plugin, which is effectively no longer supported.

I would recommend uninstalling it.

**Comment by JoshuaPoddoku** [comment]
Thanks for the help. Could you please mention the name of the plugin, please..

**Comment by Fenrirthviti** [comment]
https://obsproject.com/forum/resources/obs-virtualcam.949/

This plugin. There should be an uninstaller for it that will unregister all the virtual devices when uninstalled so they aren't left hanging around.

**Comment by JoshuaPoddoku** [comment]
Really appreciate your help, Joel.

Adding the solution here as a future reference

- Uninstall [OBS Virtual Cam ](https://obsproject.com/forum/resources/obs-virtualcam.539/)in Windows `Search>Apps & Features>OBS Virtual Cam`
![image](https://user-images.githubusercontent.com/31725457/160700671-c46a6fb2-7960-4947-8fa5-5926ffd1baad.png)
Source: [OBS Forum](https://obsproject.com/forum/threads/how-to-uninstall-obs-virtual-camera-this-is-messing-with-other-apps.131701/post-520857)
