### ISSUE TITLE
Build Issues Interfering with RTMP Streaming

### ISSUE THREAD

**Issue by ewhac** [obsproject/obs-studio#6226]
### Operating System Info

Other

### Other OS

Debian "Sid" (Unstable)

### OBS Studio Version

Git

### OBS Studio Log URL

https://obsproject.com/logs/NCBsaJp3j5vJGQOs

### Expected Behavior

OBS should be able to connect to streaming services without crashing.

### Current Behavior

There are at least two issues here:

  1. A modification to `plugins/obs-outputs/CMakeLists.txt` in commit 49e9d49 caused symbols defined in obs-outputs to be made public.  This causes a recurrence of bug #98 where the plugin dynamically links to librtmp (if installed) instead of resolving the symbols internally.  The result is OBS crashes the instant you attempt streaming.
  2. Once the above link issue is resolved by setting default symbol visibility as hidden, OBS then claims to not be able to find the symbol `obs_load_module` in the obs-outputs plugin.  This is because the `EXPORT` macro in `libobs/util/c99defs.h` doesn't actually do anything on non-MSVC builds.

Additionally, if `ENABLE_RTMPS` is configured to `AUTO`, then cmake doesn't appear to correctly detect if the system package `libmbedtls-dev` is installed, and RTMP support won't be enabled.

### Steps to Reproduce

1. Install your system's `librtmp1` and `libmbedtls-dev` packages.
2. `git clone` obs-studio from top-of-tree
3. Create `build` directory; `ccmake ..` from it to configure and generate Makefiles.  (You may need to ensure `ENABLE_RTMPS` is set to `AUTO`.)
4. Build and install OBS.
5. Run OBS.  Click on Start Streaming.  The program will crash.  GDB backtrace will show the obs-outputs plugin is calling in to librtmp1.so, not its own RTMP functions.

### Anything else we should know?

The following patches seem to help get OBS working properly.  The first fixes the broken `EXPORT` macro.  The second ensures all symbols not explicitly exported are marked as hidden.

```diff
diff --git a/libobs/util/c99defs.h b/libobs/util/c99defs.h
index 995e179d3..1d0bb3dc6 100644
--- a/libobs/util/c99defs.h
+++ b/libobs/util/c99defs.h
@@ -50,7 +50,8 @@
 #ifdef _MSC_VER
 #define EXPORT __declspec(dllexport)
 #else
-#define EXPORT
+/*  This is a GNU C-ism; might not work in clang.  */
+#define EXPORT __attribute__((visibility("default")))
 #endif
 
 #include <stddef.h>
diff --git a/plugins/obs-outputs/CMakeLists.txt b/plugins/obs-outputs/CMakeLists.txt
index 124df673f..cde40922f 100644
--- a/plugins/obs-outputs/CMakeLists.txt
+++ b/plugins/obs-outputs/CMakeLists.txt
@@ -96,9 +96,11 @@ if(ENABLE_RTMPS STREQUAL "AUTO" OR ENABLE_RTMPS STREQUAL "ON")
       target_link_libraries(obs-outputs PRIVATE ${FOUNDATION_FRAMEWORK}
                                                 ${SECURITY_FRAMEWORK})
       set_target_properties(obs-outputs PROPERTIES CXX_VISIBILITY_PRESET hidden)
+      set_target_properties(obs-outputs PROPERTIES C_VISIBILITY_PRESET hidden)
 
     elseif(OS_POSIX)
       set_target_properties(obs-outputs PROPERTIES CXX_VISIBILITY_PRESET hidden)
+      set_target_properties(obs-outputs PROPERTIES C_VISIBILITY_PRESET hidden)
     endif()
   endif()
 else()
```

**Comment by PatTheMav** [comment]
Thanks for the report, that is indeed an oversight that the visibility is set for C++, but not C.

However to me it seems we have an architectural issue here and are just fixing symptoms around the periphery - correct me if I'm wrong, but the issue seems to boil down to:

* OBS links against libavcodec on Linux
* libavcodec is commonly dynamically linked against librtmp 
* OBS uses its own librtmp implementation and introduces symbol collisions

So the proper fix (IMO) is to use the system-provided librtmp on Linux (which also taps into the second issue raised about OBS not using libmbedtls-dev) and not use its own "local" sources.

**Comment by PatTheMav** [comment]
Had some chats on this internally - we don't know if a system-provided librtmp will work with our current implementation (and err on the side of caution, so the answer is probably "we are not"), so OBS defaults to using the variant shipped in-source. Allowing this would in essence be a new feature, so feel free to make the necessary adjustments and open a PR for it.

As for the visibility fixes, the proposed changes look good to me, the visibility attribute should be supported by clang as-is, feel free to open a PR with those changes.

**Comment by derrod** [comment]
We've had another user on Discord confirm that this fixes the issue they've had. If you do not wish to PR this yourself someone from the team can do it.
