### ISSUE TITLE
Youtube manage broadcast dialog crashes in wayland on gnome 41

### ISSUE THREAD

**Issue by kkartaltepe** [obsproject/obs-studio#6227]
### Operating System Info

Other

### Other OS

Fedora 35

### OBS Studio Version

27.2.3

### OBS Studio Log URL

https://obsproject.com/logs/yXBM6JlqutxUfGQM

### Expected Behavior

Obs doesnt close.

### Current Behavior

The dialog causes gnome to issue a fatal wayland protocol exception and closes the connection. This doesnt appear to cause a fatal error on other compositors (sway) but the window behaves weirdly suggesting something is definitely incorrect.

Replicated from a report in discord.

### Steps to Reproduce

1. Launch obs
2. Link with youtube
3. Select "Manage Broadcast"
4. Select "Select Existing Broadcasts"
5. obs closes immediately.

### Anything else we should know?

I doubt this is useful for us but the wayland debug log right before the crash.

```
[ 718440.740]  -> xdg_toplevel@48.set_app_id("com.obsproject.Studio")
[ 718441.113]  -> wl_surface@42.set_buffer_scale(1)
[ 718441.484]  -> wl_surface@42.set_buffer_transform(0)
[ 718441.804]  -> wl_surface@42.commit()
[ 718442.070]  -> wl_compositor@4.create_region(new id wl_region@49)
[ 718442.487]  -> wl_region@49.add(3, 30, 616, 712)
[ 718443.011]  -> wl_surface@42.set_opaque_region(wl_region@49)
[ 718443.388]  -> wl_region@49.destroy()
[ 718444.213] wl_buffer@32.release()
[ 718445.252]  -> xdg_toplevel@48.set_min_size(562, 738)
[ 718445.781]  -> xdg_toplevel@48.set_max_size(720, 880)
[ 718446.180]  -> wl_surface@42.commit()
[ 718446.497]  -> wl_compositor@4.create_region(new id wl_region@50)
[ 718446.906]  -> wl_region@50.add(3, 30, 616, 738)
[ 718447.396]  -> wl_surface@42.set_opaque_region(wl_region@50)
[ 718447.752]  -> wl_region@50.destroy()
...
[ 719721.243] wl_pointer@3.frame()
[ 719722.174]  -> xdg_toplevel@48.set_min_size(746, 738)
[ 719722.386]  -> xdg_toplevel@48.set_max_size(720, 880)
[ 719722.567]  -> wl_surface@42.commit()
[ 719722.716]  -> xdg_surface@47.set_window_geometry(0, 0, 752, 771)
[ 719722.962]  -> wl_compositor@4.create_region(new id wl_region@54)
[ 719723.156]  -> wl_region@54.add(3, 30, 746, 738)
[ 719723.414]  -> wl_surface@42.set_opaque_region(wl_region@54)
[ 719723.594]  -> wl_region@54.destroy()
[ 719723.753] wl_buffer@34.release()
[ 719723.980] wl_callback@49.done(3395)
[ 719724.247]  -> wl_shm_pool@52.destroy()
[ 719724.455]  -> wl_buffer@53.destroy()
[ 719724.678]  -> wl_surface@25.attach(wl_buffer@34, 0, 0)
[ 719724.975]  -> wl_surface@25.damage(0, 0, 2147483647, 2147483647)
[ 719725.222]  -> wl_shm_pool@46.destroy()
[ 719725.449]  -> wl_buffer@51.destroy()
[ 719725.690]  -> wl_surface@25.commit()
[ 719725.932]  -> wl_display@1.sync(new id wl_callback@49)
[ 719726.198]  -> wl_shm@5.create_pool(new id wl_shm_pool@50, fd 45, 2319168)
[ 719726.818]  -> wl_shm_pool@50.create_buffer(new id wl_buffer@55, 0, 752, 771, 3008, 0)
[ 719728.263] wl_display@1.error(wl_surface@42, 4, "Invalid min/max size")
```

Invalid surface size seems about right as we see the window size changing unexpectedly on other compositors which maybe is them accommodating this incorrect behavior. Likely the qt ui for this needs to be modified.

**Comment by imprevo** [comment]
I have the same issue with OBS Studio 27.2.4 on Fedora 35.
OBS Studio logs: `The Wayland connection experienced a fatal error: Protocol error`.
The only workaround I've found is switching to X11 from Wayland.

**Comment by RytoEX** [comment]
I don't seem to encounter this crash on Ubuntu 22.04 running GNOME 42.0.
