### ISSUE TITLE
CI Script <build-windows.ps1> would't work in some non-English OS

### ISSUE THREAD

**Issue by kirahan** [obsproject/obs-studio#6229]
### Operating System Info

Windows 11

### OBS Studio Version

27.2.3

### OBS Studio Log URL

https://obsproject.com/logs/7XlUNWHQoa0fCmUM

### Expected Behavior

@PatTheMav 
The new CI script is very very good for build OBS, but I found it has a bug of get the OSArchitecture in non-English OS for example in Chinese, hope to fix this bug
![QQ截图20220328133124](https://user-images.githubusercontent.com/7088329/160332414-39a300f9-aa25-4797-a2c0-6e3a07c902b5.png)

### Current Behavior

The value of 
```
(Get-WmiObject Win32_OperatingSystem).OSArchitecture
````
is "64 位" not 64-bit
![QQ截图20220328133307](https://user-images.githubusercontent.com/7088329/160332656-8b5dd2c2-74ef-468f-8217-d47759bad5bd.png)
@PatTheMav 

### Steps to Reproduce

1. run CI\build-windows.ps1 not work
2. run CI\build-windows.ps1 -Help not work
3. run CI\build-windows.ps1 -BuildArch '64-bit' work well
4. run (Get-CimInstance Win32_OperatingSystem).OSArchitecture get "64 位" not “64-bit”
...

**Comment by PatTheMav** [comment]
On obs-deps we migrated to using `[System.Environment]::Is64BitOperatingSystem` for detection of the host architecture and `x86` and `x64` as the architecture bits.

Feel free to open a PR to fix this, if you already found the source of the issue.

**Comment by tommyvct** [comment]
这确实有点脑瘫😂经典Windows

还是整个英文系统吧
还有依赖是在obs-deps库，你要是开issue也是在那边开

**Comment by kirahan** [comment]
> 这确实有点脑瘫😂经典Windows
> 
> 还是整个英文系统吧 还有依赖是在obs-deps库，你要是开issue也是在那边开

不好意思，没有看到还有个专门的obs-deps仓库
sorry, I didn't notice that there is a repository
