### ISSUE TITLE
OBS starts but GUI only appears after killing enc_amf_test64

### ISSUE THREAD

**Issue by HeavelyZ** [obsproject/obs-studio#6230]
### Operating System Info

Windows 11

### OBS Studio Version

27.2.3

### OBS Studio Log URL

https://obsproject.com/logs/nrsJcKgPslg7IQG7

### Expected Behavior

OBS GUI would be presented when OBS exe was called

### Current Behavior

OBS exe is called, but no GUI presented
If I kill enc_amf_test64 via task manager, OBS GUI is presented

### Steps to Reproduce

1. Start OBS
2. <<<Wait [forever]>>>
3. OR <<<Kill enc_amf_test64 via Task Manager>>>
4. OBS GUI appears
...

### Anything else we should know?

See https://obsproject.com/forum/threads/obs-wont-start.154739/#post-566607 for previous discussion/ fixes tried

**Comment by goasChris** [comment]
Most likely due to previously having an AMD gpu installed, and leftover drivers are causing issues.
Please properly uninstall the old AMD GPU drivers, and the problem should go away.

Further support should happen in the discord, if you run into issues.
https://obsproject.com/discord

**Comment by flaeri** [comment]
Most likely due to a previous AMD card being installed in the machine, and the old drivers are still hanging around.
Please try properly uninstalling them.

Further support should happen in the discord.
https://obsproject.com/discord

**Comment by notr1ch** [comment]
Interesting find, I suppose we should add a timeout for that (not that it's ever expected to freeze, that's probably a driver thing).

**Comment by Fenrirthviti** [comment]
Going to leave this open for tracking, as notr1ch is correct that we should have some kind of timeout in place for this. It's a rare edge case, but this is also not the first time we've seen it.

**Comment by gxalpha** [comment]
Fixed by https://github.com/obsproject/obs-amd-encoder/pull/427
