### ISSUE TITLE
Soundcard broke in latest OBS and Monterey

### ISSUE THREAD

**Issue by FreQRiDeR** [obsproject/obs-studio#6240]
### Operating System Info

macOS 12.0

### OBS Studio Version

27.2.3

### OBS Studio Log URL

Na

### Expected Behavior

Audio input

### Current Behavior

No audio input from soundcard.

### Steps to Reproduce

1. Select audio input
2.no audio input
3.
...

### Anything else we should know?

Soundcard works in all other apps in Monterey 12.3. Logic, Live, Quicktime, etc...

Soundcard shows up and is selected in Properties and Monitor In/Out under advanced.

OBS is present in Privacy/Microphone and checked.

Worked fine in 12.1, only fails in 12.3. 

Works fine in Mojave.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
