### ISSUE TITLE
Virtual camera size incorrect

### ISSUE THREAD

**Issue by Coloryr** [obsproject/obs-studio#6250]
### Operating System Info

Windows 11

### OBS Studio Version

27.2.3

### OBS Studio Log URL

https://obsproject.com/logs/t_7JauS1SJi1VwUq

### Expected Behavior
the `Virtual camera`size is correct.

### Current Behavior

the `Virtual camera` size incorrect in `SetMediaType`.
![V7XB(D0~W1E%763M) @XA_L](https://user-images.githubusercontent.com/26276037/160832334-ec5293a0-1b7b-42dd-9b86-1bed8ddfc128.png)
![RS_GPVFSR_ZO{DPJ}AY}A97](https://user-images.githubusercontent.com/26276037/160832220-019610d6-f297-4f02-b3ea-179b0b95fa95.png)
![EE12E 91~TM05OU%B7($2PJ](https://user-images.githubusercontent.com/26276037/160832666-1e350079-12fd-4800-8928-dd7b1b6438ec.png)

I'm use my `Virtual camera`,it work in `AMCAM`,but at `obs` the size is incorrect.
It's [my code](https://github.com/Coloryr/Live2D_FaceTrack/blob/5020440e9569793ee3e6ba58c868cb76572019c4/L2d_Desktop/VCam/VCamFilter.cs#L216) error?

### Steps to Reproduce

1. Add camera
2. select my `Virtual camera`

**Comment by WizardCM** [comment]
This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels below, and if it's determined that this is indeed a bug, then we will re-open this issue.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
