### ISSUE TITLE
27.2.3 crash 3 days in a row when stopping stream then closing OBS a few minutes later.

### ISSUE THREAD

**Issue by johnebgood** [obsproject/obs-studio#6252]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.3

### OBS Studio Log URL

https://obsproject.com/logs/he-lH4wMrEhKhRP-

### OBS Studio Crash Log URL

https://obsproject.com/logs/YUuth4g0UUCOvRqu

### Expected Behavior

I would expect when closing OBS it would not crash.

### Current Behavior

OBS crashes after streaming for a long period, 6+ hours, stopping stream and then closing OBS.

### Steps to Reproduce

1. Stream for a long time.
2. Stop Stream. 
3. Close OBS.
4. OBS will crash.

### Anything else we should know?

Started happening a few days ago after quite a while on 27.2.3 and have been streaming every day, not sure if it was something I added.  My computer blue screened yesterday after ending stream but not closing OBS, not sure if it's related at this point, will attempt that tomorrow.

**Comment by kkartaltepe** [comment]
This looks like a bug in obs-ndi freeing its resources too early, i'd recommend you open a bug against them.

**Comment by johnebgood** [comment]
I updated to 27.2.4 and had 3 crashes during stream today. Is there something I can look for to see if these crashes were related to NDI?
[Crash 2022-04-01 10-55-15.txt](https://github.com/obsproject/obs-studio/files/8399371/Crash.2022-04-01.10-55-15.txt)
[Crash 2022-04-01 07-41-06.txt](https://github.com/obsproject/obs-studio/files/8399372/Crash.2022-04-01.07-41-06.txt)
[Crash 2022-04-01 03-37-47.txt](https://github.com/obsproject/obs-studio/files/8399373/Crash.2022-04-01.03-37-47.txt)

**Comment by Fenrirthviti** [comment]
Two of those crashes are caused by `win-spout.dll` which is another third party plugin..

You can typically tell what is causing the crash by looking at the modules in the crashed thread, but sometimes (in the case of the NDI free crash) it is not so obvious. Unfortunately it just comes with experience and familiarity in same cases.

**Comment by gxalpha** [comment]
This looks like an issue with third-party plugins.
Please file issues against them if you're still having problems.
