### ISSUE TITLE
Images source visibility under "group" source get applied directly to the "program" view (studio mode)

### ISSUE THREAD

**Issue by Rodyll** [obsproject/obs-studio#6262]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/j4PkSiontIOgLOej

### Expected Behavior

Previously, when a source group visibility was on, image sources visibility were applied only to the "preview" of the studio mode (like any other visibility change afaik).

### Current Behavior

The image source visibility directly impacts the "program" view of the studio mode, whatever the visibility of the group source it is in.

### Steps to Reproduce

1. Create a group source
2. Put an image source inside it
3. Play with group and source visibility in studio mode
4. See that the image source visibility is directly applied to the "program" view of studio mode

### Anything else we should know?

Some additional notes :
- If you move the image source outside of the group source, the visibility is again applied properly only to the "preview" window of the studio mode
- I tried creating new image sources to put them inside a new group, but the issue is still here

**Comment by WizardCM** [comment]
This is expected behaviour. You can change this by clicking the gear in the middle between the two views and select "Duplicate Sources"

![image](https://user-images.githubusercontent.com/941350/161240320-b2f5efa3-da02-47cf-b402-b94d6974a6b0.png)
