### ISSUE TITLE
Mac - OBS Crashes with 27.2.x every time, every version

### ISSUE THREAD

**Issue by sjallyn** [obsproject/obs-studio#6265]
### Operating System Info

macOS 12.0

### Other OS

Also ON Mac OS 11.x

### OBS Studio Version

27.2.4

### OBS Studio Version (Other)

Any 27.2 version crashes

### OBS Studio Log URL

I can't run the App so how can I do this?

### OBS Studio Crash Log URL

I don't undestand how to do this

### Expected Behavior

I expect OBS to Run

### Current Behavior

It crashes on launch

### Steps to Reproduce

1.Launch OBS
2. It crashes unexpectedly
3.
...

### Anything else we should know?

[2022-04-02 17-41-42.txt](https://github.com/obsproject/obs-studio/files/8403424/2022-04-02.17-41-42.txt)

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by sjallyn** [comment]
How is it not a bug, that it crashes on launch on 4 different Mac computers, with 3 different OS's, and version 27.1 runs fine on all 4?

Stuart Allyn

**Comment by Fenrirthviti** [comment]
That would be a great discussion to have in our support channels so someone can take a closer look. Without more information to go off, this is impossible for us to take action on.
