### ISSUE TITLE
OBS fails to compile with latest FFMPEG

### ISSUE THREAD

**Issue by ConHuevosGuey** [obsproject/obs-studio#6266]
### Operating System Info

Other

### Other OS

Linux

### OBS Studio Version

Git

### OBS Studio Log URL

https://pastebin.com/jaEEgnPS

### Expected Behavior

Attempting to compile the current git pull on OBS against FFMPEG version N-106468-g54a4c58dd6 , it fails to build at media-remux.c citing:

` error: ‘AVStream’ has no member named ‘codec’
   91 |                         job->ofmt_ctx, in_stream->codec->codec)`

Build log here:

https://pastebin.com/jaEEgnPS

### Current Behavior

Fails to compile.

### Steps to Reproduce

git clone --recursive https://github.com/obsproject/obs-studio.git
cd obs-studio
mkdir build && cd build
cmake -DLINUX_PORTABLE=ON -DCMAKE_INSTALL_PREFIX="${HOME}/obs-studio-portable" -DENABLE_BROWSER=OFF -DENABLE_AJA=OFF ..
make

**Comment by kkartaltepe** [comment]
It appears you are either using an old version of ffmpeg or you have a broken system such that your ffmpeg is reporting itself as an old version. As the line in error is only compiled when libavcodec reports itself as older than 57.48.101

**Comment by CartoonFan** [comment]
Would you consider reopening this, @kkartaltepe? I'm also getting this build error, but my libavcodec is greater than 57.48.101.

OBS build log: [obs_ffmpeg5_build.log](https://github.com/obsproject/obs-studio/files/8568859/obs_ffmpeg5_build.log)

ffmpeg-git version:
```console
$ ffmpeg -version 
ffmpeg version N-106684-g1da3394adb Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 11.2.0 (GCC)
configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-amf --enable-avisynth --enable-cuda-llvm --enable-lto --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libdav1d --enable-libdrm --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librav1e --enable-librsvg --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libsvtav1 --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxcb --enable-libxml2 --enable-libxvid --enable-libzimg --enable-nvdec --enable-nvenc --enable-shared --enable-version3
libavutil      57. 24.101 / 57. 24.101
libavcodec     59. 27.100 / 59. 27.100
libavformat    59. 23.100 / 59. 23.100
libavdevice    59.  6.100 / 59.  6.100
libavfilter     8. 37.100 /  8. 37.100
libswscale      6.  6.100 /  6.  6.100
libswresample   4.  6.100 /  4.  6.100
libpostproc    56.  5.100 / 56.  5.100
```
Thanks in advance!

**Comment by kkartaltepe** [comment]
Thanks for attaching your build log, but it seems to show that something is extremely wrong with your ffmpeg headers as its printing garbage, so it looks even less like an obs bug.

**Comment by CartoonFan** [comment]
Thanks for the advice. Can you point out which line looks like garbage, so I can test the build myself? Thanks again!

**Comment by CartoonFan** [comment]
Never mind; I **think** I might have found the issue: ffmpeg-git has the major version in a separate header called "version_major.h".
