### ISSUE TITLE
Preview window gets unmaximized when main window minimizes (Wayland, Gnome)

### ISSUE THREAD

**Issue by Pshemas** [obsproject/obs-studio#6284]
### Operating System Info

Other

### Other OS

Linux

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/xV__iKzOBdld9tor

### Expected Behavior

I should be able to minimize main OBS window with preview staying intact.

### Current Behavior

When displaying the preview window (projector) on the other screen minimizing OBS window unmaximizes projector window.

### Steps to Reproduce

1. Set up screen / window capture.
2. Open preview / projector window and move it to other monitor
3. Maximize it
4. Minimize main OBS screen

### Anything else we should know?

I'm using flatpak version, OpenSUSE Tumbleweed, Intel gpu

**Comment by kkartaltepe** [comment]
Cannot replicate on gnome 41
