### ISSUE TITLE
Decklink Output Audio Delay

### ISSUE THREAD

**Issue by MNSenate** [obsproject/obs-studio#6293]
### Operating System Info

Windows 11

### OBS Studio Version

27.1.3

### OBS Studio Log URL

https://obsproject.com/logs/PO-KFyQk1bsuiiAq

### Expected Behavior

Audio and Video from the Decklink card output to be in sync.

### Current Behavior

We have one room which we made the four cameras in output NDI. So we can pull in those to OBS as NDI sources.  

We are using a black magic decklink 4k SDI card in the computer which has OBS running on it. We use the decklink card to send out to a HELO for webstreaming and then also a router so we can watch the output on a monitor. 

Looking at the OBS program monitor and listening to it, everything looks in sync. But then looking at the output from the decklink card I often get audio drifting typically about a 300ms delay. Oddly, the audio arriving late. You would expect NDI video to be the delay. It is Dante audio. Pulled in as an audio input capture in OBS.

If we add a -300ms audio delay in, the audio and video look good on the decklink output, but then my local recording on OBS is off by that delay.  Sometimes it needs more than -300ms. It appears to be random.

When not using hose NDI cameras, we just capture a zoom meeting in OBS using desktop audio and it syncs up perfectly on the OBS program monitor and the decklink output. Adding in these NDI sources somehow the Decklink card and OBS will not play well together. 

Restarting OBS does seem to fix it temporarily when things get way out of sync. 

It's not anything with skipped or dropped frames as those have been good looking at the OBS stats window. The computer has plenty of RAM, CPU processing power and GPU resource still available while OBS is running those NDI cameras.

### Steps to Reproduce

1. Add 4 NDI cameras. Each in it's own scene
2. Audio Input capture a Dante Audio source
3. View the Decklink output for sync issues
...

### Anything else we should know?

The program monitor and recording local in OBS everything is in sync. Yet when viewing the decklink output the audio is ahead of the video.

**Comment by Fenrirthviti** [comment]
This issue is a bit too reliant on 3rd party plugins and a very complex setup that it makes it hard for us to action. As written, this reads more like a support request, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for further assistance. If this is confirmed to be a bug, we can re-open.

Thank you!
