### ISSUE TITLE
Exporting Profile no longer working

### ISSUE THREAD

**Issue by sporetec** [obsproject/obs-studio#6298]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

na

### Expected Behavior

When I open the Profile menu and click on export, there should be a file dialogue allowing me to select the folder and file name.

### Current Behavior

Currently the steps open a file open dialogue and do not save anything

### Steps to Reproduce

1. Open OBS
2. Click the Profile menu
3. Select the profile you want to export
4. Open the Profile menu again
5. Click export

**Comment by WizardCM** [comment]
I cannot reproduce this. Sounds like a system issue. Please submit this through one of our support channels below, and if it's determined that this is indeed a bug, then we will re-open this issue.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
