### ISSUE TITLE
macOS: Window Capture while in macOS Full Screen

### ISSUE THREAD

**Issue by HiroiSekai** [obsproject/obs-studio#6299]
### Operating System Info

Other

### Other OS

macOS 12.3.1

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/Wg53D5wzRovqKqzs

### Expected Behavior

When using OBS Studio in macOS' native full screen mode (green dot), window capture should see other open applications around it.

### Current Behavior

When OBS Studio OR the wanted application to window capture is using macOS' native full screen mode, Window Capture properties will not display the app. If OBS Studio is the app in full screen, all it will display is certain UI elements from macOS to capture, like the Mac's battery indicator, Wi-Fi symbol, desktop wallpaper, etc.

### Steps to Reproduce

1. Use the green dot in the top left corner of OBS Studio on the Mac to expand to macOS' native full screen mode.
2. Add a new source for Window Capture
3. Issue will appear here: there is no way to capture any other window.
...

### Anything else we should know?

I am not sure if this is a macOS limitation, but I'm wondering/really hoping that there is a workaround that can be implemented. I have a very strictly set workflow and taking OBS as well as all of my other apps I want to Window Capture out of full screen mode is pretty much a no-go. I would just like the ability to capture an app's window if it's open, no matter its status (windowed or full screen), just like on the Windows version of OBS Studio.

**Comment by feetstv** [comment]
This is partly a macOS limitation and partly an OBS one. The way that OBS currently gets the window image is dependent on the window being on screen.

A newer method of window capture has been proposed (and a PR made), but if and when that code will be integrated has no ETA.

**Comment by HiroiSekai** [comment]
Thanks for the explanation. I personally know a lot of people are switching to Mac streaming with the newest line of Mac computers greatly improving the capabilities of running OBS and streams, so this would be a much appreciated change.

**Comment by HiroiSekai** [comment]
Oh sorry, I forgot to mention this earlier.

I have also tried the alternative programs during my full transition to Mac, which included Streamlabs OBS and Twitch Studio Beta. Neither of those also can capture specific windows unless setup exactly as mentioned, with both OBS and capture window be in windowed mode on the same desktop.

If OBS ends up implementing the proposed fix for this, it would become the sole obvious option for all Mac users to use, as this would be a hugely important feature for ease-of-use.

**Comment by msikma** [comment]
> A newer method of window capture has been proposed (and a PR made), but if and when that code will be integrated has no ETA.

Would you happen to know which PR this is? I would be interested in building and giving it a try.

**Comment by gxalpha** [comment]
> Would you happen to know which PR this is? I would be interested in building and giving it a try.

#5875
There should already be CI test builds on the PR.

**Comment by gxalpha** [comment]
As mentioned earlier, all the capture methods require the window to actually get rendered. This only happens if the window is actually on screen, or at least on a visible Desktop (one of the ways how macOS is great at saving power).

I consider this to not be a bug, or at least not one we can do anything about.
