### ISSUE TITLE
macOS: Resizing docks does not respond accurately

### ISSUE THREAD

**Issue by HiroiSekai** [obsproject/obs-studio#6300]
### Operating System Info

Other

### Other OS

macOS 12.3.1

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/Wg53D5wzRovqKqzs

### Expected Behavior

When you click and drag a handle on either side of a dock to resize it, it should respond 100% of the time as long as your cursor was in the correct spot.

### Current Behavior

I would say something like 70% of the time, even if the cursor has changed from the pointer to the handle for resizing, if you click and drag, nothing happens. You have to do a multitude of trial and error clicks to find that one magic area that lets you drag to resize the dock.

### Steps to Reproduce

1. Ensure a couple docks are open on OBS Studio for Mac.
2. Place cursor on either end of a dock, click and drag to attempt making it wider/smaller.
3. Issue occurs here: most of the time, the resizing will not happen. If you keep persisting and fidgeting through trial and error, you will eventually find a magic spot to be able to resize.
4. Similarly, if you also try to click and drag the dock itself to a new location, most of the time it won't snap into place, but instead float about awkwardly. You need to do the same trial and error fidgeting with the dock or restarting OBS entirely to fix this.
...

### Anything else we should know?

This issue is not new, it has persisted on the macOS version for quite a while. It's a bizarre issue, but it does make restructuring my OBS workspace very annoying.

**Comment by feetstv** [comment]
This issue comes from the version of Qt that is used to make the interface. When OBS Studio moves to a later version of Qt, this issue will be resolved — however, I don't believe there's an ETA for when that'll happen.

Currently, one can build OBS with a later version of Qt. However, this may preclude compatibility with existing OBS plugins.

**Comment by HiroiSekai** [comment]
Thank you for the explanation. Plugins overall will be much more important to me at the moment since I need the LiveSplit-One plugin working for stream. I may give it a test whirl to see if it can handle it, but it's good to know.

I'm assuming the macOS version holds less users and generally less priority overall for these fixes/additions? I'm aware of the delta but just absolutely do not ever want to return to using Windows. 😅

**Comment by Fenrirthviti** [comment]
macOS having less users doesn't factor in to issue priority, however, the smaller userbase usually means less developers who are familiar enough with issues to work around them (if workarounds are possible). This is an upstream bug with Qt though, and we do have plans to migrate to Qt6 on all platforms at some point which should hopefully fix it. As feetstv mentioned, there is no current ETA for that, but it is something we're working towards.

**Comment by HiroiSekai** [comment]
Great to know, thank you for sharing. This is definitely a much smaller problem than the one around Window Capture on Mac that I posted, so I am more than content knowing it is internally a known issue and plans to be worked on at some point.

Thanks again, I'll close this one.

**Comment by WizardCM** [comment]
Reopening this ticket as it has been determined that this issue is separate from the known docking issue, as this one is specific to the grip between docked dock widgets. We may close it again if we find a way to fix it via alternative means, or once we've ensured a valid report is submitted with Qt itself.

**Comment by HiroiSekai** [comment]
Ah okay, thank you for the update. Will keep a look out for more input.
