### ISSUE TITLE
OBS won't open

### ISSUE THREAD

**Issue by poetrynmotion7** [obsproject/obs-studio#6301]
### Operating System Info

Other

### Other OS

Mac Monterey 12.3.1

### OBS Studio Version

27.2.4

### OBS Studio Log URL

obs-2022-04-09-083030.ips

### Expected Behavior

I expected it to open

### Current Behavior

When I open OBS there's a small box and then it doesn't open.

### Steps to Reproduce

1.Opening OBS

### Anything else we should know?

It's been buggy for the past few days.

**Comment by notr1ch** [comment]
Please use the forums or Discord for support.
