### ISSUE TITLE
Gamecapture doesnt capture the game Armored Warfare

### ISSUE THREAD

**Issue by DisturbedNoob** [obsproject/obs-studio#6304]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/adP4BRkoUSMaZ3q2

### Expected Behavior

Gamecapture should capture the Game

### Current Behavior

Gamecapture does not capture the Game

### Steps to Reproduce

1.Open OBS
2. Try to capture the Game "Armored Warfare" with Gamecapture

**Comment by WizardCM** [comment]
This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels below, and if it's determined that this is indeed a bug, then we will re-open this issue.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
