### ISSUE TITLE
'Hide OBS windows from screen capture' doesn't work after re-opening OBS

### ISSUE THREAD

**Issue by Vainock** [obsproject/obs-studio#6309]
### Operating System Info

Windows 11

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/E3hvP77vwK4_0PGN

### Expected Behavior

The 'Hide OBS windows from screen capture' setting should always hide OBS window.

### Current Behavior

The 'Hide OBS windows from screen capture' setting only works every second time I open OBS. The other time the OBS is visible and being captured.

https://user-images.githubusercontent.com/39059951/162628184-571f33f1-e03d-4f34-bcd0-ae90410de054.mp4

### Steps to Reproduce

1. Enable 'Hide OBS windows from screen capture'.
2. Add a Display Capture source.
3. Minimize the OBS window and re-open it like shown in my video.

### Anything else we should know?

In my video I only observe the preview, but the issue still persists in the recorded file.

**Comment by notr1ch** [comment]
Fixed in https://github.com/obsproject/obs-studio/commit/a8ecf3c8f2c2c28624a01249d3ec8b6435198009
