### ISSUE TITLE
OBS recording fails with "av_interleaved_write_frame failed: Error 13 access denied"

### ISSUE THREAD

**Issue by Adr1one** [obsproject/obs-studio#6310]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/iLyobOpST4v0pIpG

### OBS Studio Crash Log URL

https://obsproject.com/logs/AObwHm8m25Kz3-AF

### Expected Behavior

I expected to record a video

### Current Behavior

OBS either failed to record at all, started recording but would not stop recording, or became unresponsive to the extent that exiting did not work, nor End Process in Task Manager (I had to force power down). I uninstalled the previous version and downloaded and updated the latest version. I tried different encoder settings and checked CPU and GPU performance- neither of which was taxed. Plenty of disc space (external drive). The disk also became unresponsive when trying to access recordings.

I have two RAM sticks- the old 4Gb and a new 16Gb. Tried different configurations, but not the 4Gb on its own.

### Steps to Reproduce

1. Press record :)
2. Error appears during recording
3.Stop record
...

### Anything else we should know?

I saw this: https://github.com/obsproject/obs-studio/issues/3738

**Comment by RytoEX** [comment]
Does this still occur in OBS Studio 28.0.2 or newer? We implemented some fixes targeted at recording to external drives.

**Comment by gxalpha** [comment]
Closing as there hasn't been a reply and we believe the issue has been fixed. If you can confirm that it still happens on 28.0 (or newer), please respond here or open a new issue.

**Comment by ChiuChillgaming** [comment]
I still have this issue and I have no idea why it happens. 

I'm using version **28.0.3** and every time I record for about 20 minutes or so, I'll get notified **"No space left on device av_interleaved_write_frame failed: -1: Operation not permitted"** even though I still have **700GB** in my drive. And yes I've set the recording directory to a folder in my hard drive **(D:\)**. I've also already tried most of the methods I found online such as pasting in the file directory, changing the recording type to FFmpeg or updating my computer's path variable to OBS DLLs. Still, none of them seem to work.

Here is the log: _https://obsproject.com/logs/4TvQr9zGhaKGx5t4_

**Comment by notr1ch** [comment]
What filesystem is being used on D? How big is the output file at the time of the failure?

**Comment by ChiuChillgaming** [comment]
Nevermind, just found out that my drive was using FAT32 and that most of my files average 4GBs which was causing OBS unable to keep on recording since it was about to exceed the 4GB limit. Sorry for the inconvenience caused.

**Comment by kellervater** [comment]
I get a similar one...

The OBS window seems to be stuck... but after a while it comes back with 2 modal dialogs. 
One ⚠️:
`Error writing to 'D:/Recordings/blabla.mkv', Invalid argument av_interleaved_write_frame failed: -1 Operation not permitted`
And the other ❌ with something like "not enough disk space..." but there are 5TB left on my external Synology drive.

It occurs very randomnly througout my recording. Once when hitting 15GB, once on 2GB.

My setup:
* Windows 11
* OBS 30.0.0
* Recording to Synology network drive via 10Gb network.
* Recording in WQHD and HDR (NVIDIA NVENC HEVC, main10, slowest, QCP 16, .mkv, P010, Rec. 2100 (PQ))

I guess it has something to do with the Synology network drive, but I can't pinpoint the problem exactly.
