### ISSUE TITLE
Unable to start OBS

### ISSUE THREAD

**Issue by lynnguo666-personal** [obsproject/obs-studio#6317]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

Can Not Upload the Log, plz look the commit.

### Expected Behavior

Display the OBS software page

### Current Behavior

No prompts and windows are opened

### Steps to Reproduce

1.Open OBS
2.
3.
...

**Comment by lynnguo666-personal** [comment]
20:02:34.763: CPU Name: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
20:02:34.763: CPU Speed: 2208MHz
20:02:34.763: Physical Cores: 6, Logical Cores: 12
20:02:34.763: Physical Memory: 16252MB Total, 6023MB Free
20:02:34.763: Windows Version: 10.0 Build 19044 (release: 2009; revision: 1620; 64-bit)
20:02:34.763: Running as administrator: false
20:02:34.763: Aero is Enabled (Aero is always on for windows 8 and above)
20:02:34.764: Windows 10 Gaming Features:
20:02:34.764: 	Game DVR: On
20:02:34.765: Sec. Software Status:
20:02:34.766: 
20:02:34.766: 
20:02:34.767: 
20:02:34.767: Current Date/Time: 2022-04-11, 20:02:34
20:02:34.768: Browser Hardware Acceleration: true
20:02:34.768: Hide OBS windows from screen capture: false
20:02:34.768: Qt Version: 5.15.2 (runtime), 5.15.2 (compiled)
20:02:34.768: Portable mode: false
20:02:34.988: OBS 27.2.4 (64-bit, windows)
20:02:34.988: ---------------------------------
20:02:34.989: ---------------------------------
20:02:34.989: audio settings reset:
20:02:34.989: 	samples per sec: 48000
20:02:34.989: 	speakers:        2
20:02:34.992: ---------------------------------
20:02:34.992: Initializing D3D11...
20:02:34.992: Available Video Adapters: 
20:02:35.002: 	Adapter 0: NVIDIA GeForce GTX 1050 Ti
20:02:35.002: 	  Dedicated VRAM: 4206886912
20:02:35.002: 	  Shared VRAM:    4225853440
20:02:35.002: 	  PCI ID:         10de:1c21
20:02:35.002: 	  Driver Version: 26.21.14.3187
20:02:35.002: 	  output 0:
20:02:35.002: 	    name=LM156LF9L01
20:02:35.002: 	    pos={0, 0}
20:02:35.002: 	    size={1920, 1080}
20:02:35.002: 	    attached=true
20:02:35.002: 	    refresh=60
20:02:35.002: 	    space=RGB_FULL_G22_NONE_P709
20:02:35.002: 	    sdr_white_nits=80
20:02:35.002: 	    nit_range=[min=0.500000, max=270.000000, max_full_frame=270.000000]
20:02:35.002: 	Adapter 1: Intel(R) UHD Graphics 630
20:02:35.002: 	  Dedicated VRAM: 134217728
20:02:35.002: 	  Shared VRAM:    4225853440
20:02:35.002: 	  PCI ID:         8086:3e9b
20:02:35.003: 	  Driver Version: 23.20.16.5037
20:02:35.010: Loading up D3D11 on adapter NVIDIA GeForce GTX 1050 Ti (0)
20:02:35.095: D3D11 loaded successfully, feature level used: b000
20:02:35.095: DXGI increase maximum frame latency success
20:02:35.095: D3D11 GPU priority setup failed (not admin?)
20:02:35.546: ---------------------------------
20:02:35.546: video settings reset:
20:02:35.546: 	base resolution:   1920x1080
20:02:35.546: 	output resolution: 1280x720
20:02:35.546: 	downscale filter:  Bicubic
20:02:35.546: 	fps:               30/1
20:02:35.546: 	format:            NV12
20:02:35.546: 	YUV mode:          709/Partial
20:02:35.547: NV12 texture support enabled
20:02:35.548: Audio monitoring device:
20:02:35.548: 	name: 默认
20:02:35.548: 	id: default
20:02:35.548: ---------------------------------
20:02:35.558: No AJA devices found, skipping loading AJA UI plugin
20:02:35.558: Failed to initialize module 'aja-output-ui.dll'
20:02:35.569: No AJA devices found, skipping loading AJA plugin
20:02:35.569: Failed to initialize module 'aja.dll'
20:02:35.570: Skipping module '../../obs-plugins/64bit/chrome_elf.dll', not an OBS plugin
20:02:35.574: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
20:02:35.576: Failed to load 'en-US' text for module: 'decklink-captions.dll'
20:02:35.580: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
20:02:35.621: [AMF] Unable to load 'amfrt64.dll', error code 126.
20:02:35.623: [AMF] AMF Test failed due to one or more errors.
20:02:35.623: Failed to initialize module 'enc-amf.dll'
20:02:35.640: Skipping module '../../obs-plugins/64bit/libcef.dll', not an OBS plugin
20:02:35.640: Skipping module '../../obs-plugins/64bit/libEGL.dll', not an OBS plugin
20:02:35.641: Skipping module '../../obs-plugins/64bit/libGLESv2.dll', not an OBS plugin
20:02:35.709: [obs-browser]: Version 2.17.13
20:02:35.709: [obs-browser]: CEF Version 95.0.0-MediaHandler.2467+g8092a57+chromium-95.0.4638.69
20:02:35.731: NVENC supported
20:02:35.736: [noise suppress]: NVIDIA RTX denoiser disabled, redistributable not found

**Comment by WizardCM** [comment]
This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels below, and if it's determined that this is indeed a bug, then we will re-open this issue.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

**Comment by lynnguo666-personal** [comment]
> 这听起来更像是一个支持问题而不是一个错误。请通过以下我们的支持渠道之一提交此问题，如果确定这确实是一个错误，那么我们将重新打开此问题。
> 
> 请使用[Discord 服务器](https://obsproject.com/discord)或[论坛](https://obsproject.com/forum)。有关更多信息，请查看我们的[帮助页面](https://obsproject.com/help)。

I'm pretty sure this is a bug and not an issue due to support.
Because OBS provides a crash report

**Comment by RytoEX** [comment]
This is likely caused by outdated Intel GPU drivers, which is a support issue. Update your Intel GPU drivers.

**Comment by lynnguo666-personal** [comment]
Thanks, this issue is resolved.
