### ISSUE TITLE
Menus are scaled incorrectly and clipped on dual monitor system

### ISSUE THREAD

**Issue by boramis** [obsproject/obs-studio#6319]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/WkUPuVNMcrORvli2

### Expected Behavior

Menus should be scaled correctly for the monitor that they're on

### Current Behavior

When right clicking on the main preview area to show the context menu, the "Preview Scaling" submenu initially shows correctly, but if you move the mouse away so it closes and then hover over it again, the text and images are scaled up 200%, while the menu size itself isn't, so the menu is clipped:
![OBS Scaling Bug](https://user-images.githubusercontent.com/6313052/162819772-2d53d98a-cd45-4d03-a8e7-d552bf746529.png)

The "Fullscreen Projector (Preview)" and "Add" submenus are not affected.  Opening the top-level "Edit" menu in the menu bar corrects the issue for "Preview Scaling" and it continues working correctly until the program is restarted.  The other top-level menus (File/View/Docks/Profile/Scene Collection/Tools/Help) do **not** do that, and it will keep showing incorrectly.

### Steps to Reproduce

1. Have two monitors set up, the primary one on the left is a 4K monitor, set to 3840x2160 with scaling set to 200%.  The secondary one on the right is set to 1920x1080 with scaling set to 100%.
2. Launch OBS on the secondary monitor.
3. Right click on the preview image to show the context menu.
4. Move the mouse down to "Preview scaling".  The submenu will open, looking correct.
5. Move the mouse away so "Preview scaling" closes.  Clicking away to close the menu entirely will also work.
6. Re-open the "Preview scaling" submenu.  The text/images are now scaled up by 200%, but the menu size isn't, so everything is clipped.
7. Click the top-level "Edit" menu.
8. Right click on the Preview again.  "Preview scaling" will now look correct.
...

### Anything else we should know?

Windows 10 21H1 19043.1586, NVIDIA GeForce 980ti with up to date drivers (512.15, released 3/22/2022).

**Comment by boramis** [comment]
Possible related issue: https://github.com/obsproject/obs-studio/issues/6113

**Comment by cnschu** [comment]
this seems to be the same problem as #6113

**Comment by Trouffman** [comment]
(sorry for bump, but I exeperienced this again today)

This happen when you have 2 different scaling on mutli-monitor setup.

Overall : the sub-menu (never the first one) will use the font scaling of the primary monitor rather than the monitor OBS is on.

Workaround : If you go into settings and change the font scaling of Primary monitor to the same as secondary monitor = no problem. you can set it back to the previous scaling. Do the same on the secondary monitor : Set the scaling on 2nd monitor as same as the primary then back to what it was. > this fixed it for me ( but need to be done everytime you launch OBS :D!)

OS Name	Microsoft Windows 11 Home
Version	10.0.22000 Build 22000
RTX 2060 Max-Q - Driver GRD 516.59

**Comment by RytoEX** [comment]
Please confirm if this is still occurring in OBS Studio 28.0.3 (or newer).

**Comment by boramis** [comment]
No longer reproducible in 28.0.3.  Thanks!

**Comment by jerry-sileon** [comment]
This is still happening on Windows 11, OBS 29.0.2 (64 bit). Super annoying.

(Please know that OBS is definitely not the only program having problems like this!)

**Comment by Fenrirthviti** [comment]
If it is still happening for you, please open a new issue with your environment details, and steps to reproduce. It may be a similar, related, but still separate issue.
