### ISSUE TITLE
zoom  not showing up

### ISSUE THREAD

**Issue by solomoncyj** [obsproject/obs-studio#6349]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/YgalvX5H0B_mQfu-

### Expected Behavior

I am able to see the zoom meeting in the window

### Current Behavior

![image](https://user-images.githubusercontent.com/74647769/163800810-b271fb4a-e543-48de-b0bd-e560d4a4f104.png)

### Steps to Reproduce

1. put a window capture to the zoom meeting
2.
3.
...

### Anything else we should know?

no

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
