### ISSUE TITLE
Recording video as m3u8, the recorded video is shorter than the actual

### ISSUE THREAD

**Issue by Adonis-Song** [obsproject/obs-studio#6355]
### Operating System Info

macOS 11.5

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/0AWxBdYwUTMRrju2

### Expected Behavior

The recorded video is shorter than the actual

### Current Behavior

The m3u8 file contains up to 5 ts files just as shown below.  If the num of ts files is more than 5, the first ts file will be deleted frome m3u8 file.  And I think the reason of this is the default value of "**hls_list_size**" in ffmpeg is 5.  

#EXTM3U
#EXT-X-VERSION:3
**#EXT-X-TARGETDURATION:8**
#EXT-X-MEDIA-SEQUENCE:2
#EXTINF:8.333333,
**2022-04-19 18-04-152.ts**
#EXTINF:8.333333,
2022-04-19 18-04-153.ts
#EXTINF:8.333333,
2022-04-19 18-04-154.ts
#EXTINF:8.333333,
2022-04-19 18-04-155.ts
#EXTINF:0.433333,
2022-04-19 18-04-156.ts
#EXT-X-ENDLIST

### Steps to Reproduce

Set output mode to **Advanced**
Set Recording Format to **m3u8**
Set Encoder to **x264**

And start recording. you will find this bug.
![截屏2022-04-19 下午6 16 24](https://user-images.githubusercontent.com/34226411/163982722-9ab490f2-38c9-432d-bf98-ba46bc140af1.png)

### Anything else we should know?

I know I can set the value of "hls_list_size" in ffmpeg command, but I donnot konw how to set it using code.

**Comment by derrod** [comment]
Set it via the "Custom Mixer Settings" box in a `key=value` format.

**Comment by Adonis-Song** [comment]
Thanks

**Comment by cqtian** [comment]
I also met this problem, but I still couldn't solve it through this method, so I want to ask for help
[2023-03-10 12-11-28.txt](https://github.com/obsproject/obs-studio/files/10938962/2023-03-10.12-11-28.txt)
