### ISSUE TITLE
Obs recorded the ivcam virtual camera and found the recorded video stuck.

### ISSUE THREAD

**Issue by star2k** [obsproject/obs-studio#6373]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

no

### Expected Behavior

I hope to record the video with background smoothly.

### Current Behavior

When obs records the "ivcam" virtual camera and turns on the background recording of ivcam, the generated video is stuck, while the software that comes with ivcam records a smooth video.

ivcam Download address ：https://www.e2esoft.com/ivcam/

### Steps to Reproduce

1.Run ivcam
2.Turn on Background Removal in the menu.
3.Use obs.
4.After watching the recorded video, I found Caton playing.
...
![2](https://user-images.githubusercontent.com/9582078/164950309-ff1473f1-4d6d-4502-8c28-452d3c1f3f14.png)

### Anything else we should know?

ivcam Download address ：https://www.e2esoft.com/ivcam/

**Comment by Fenrirthviti** [comment]
Please report issues with third party tools to their support.
