### ISSUE TITLE
OneNote doesn't work with OBS

### ISSUE THREAD

**Issue by DeaderSurvival** [obsproject/obs-studio#6375]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/I5k3SkPXAldx8jag

### Expected Behavior

Onenote for Windows 10 to show up on a window or game capture

### Current Behavior

Literally nothing. No matter what I do, OneNote refuses to show up, and it's size is always 0 or 90001, regardless of what size I actually try to set it to.

### Steps to Reproduce

1.Have OneNote Open
2.Open OBS
3.Try to make OBS capture OneNote
...

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
