### ISSUE TITLE
Overlapping popup on Wayland/Gnome on startup

### ISSUE THREAD

**Issue by gabrieleturchi** [obsproject/obs-studio#6380]
### Operating System Info

Other

### Other OS

Fedora Linux 35

### OBS Studio Version

27.2.4

### OBS Studio Log URL

-

### Expected Behavior

Opening OBS with multiple PipeWire Window capture, the window selection popups shows up to select the involved windows.

### Current Behavior

The window selection popups shows up perfectly overlapping, and is impossible to close them, given that usually the active one is also the lower one.
Ok, you can say: it is a Wayland problem. But I think that, having multiple requesters to be opened, they should be opened in sequence, each one after the user closed the previous one, maybe also indicating the involved source name.

### Steps to Reproduce

1. Configure multiple PipeWire window capture
2. Close OBS
3. Open OBS
...

**Comment by kkartaltepe** [comment]
Complain to your xdg-desktop-portal provider

**Comment by gabrieleturchi** [comment]
Sorry, but... 
            "... they should be opened in sequence, each one after the user closed the previous one, ..."

How the xdg-desktop-portal provider may understand that the requesters should be shown in sequence?

**Comment by kkartaltepe** [comment]
Its the only software on your system that knows how many requests are active. So its the only software that could show all requests one at a time.

**Comment by udoprog** [comment]
Coming from #6465

@kkartaltepe you mention that this was dismissed upstream, can you post a link to that conversation? Do you know which GNOME project this goes under (e.g. mutter)?

Thanks!

**Comment by udoprog** [comment]
Opened upstream issue: https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/issues/40
