### ISSUE TITLE
System Crash 27.2.4

### ISSUE THREAD

**Issue by IcyChills** [obsproject/obs-studio#6389]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/dsh_SvUGTX4oLWYJ

### Expected Behavior

Expected OBS to record game window.

### Current Behavior

Entire screen throws random color, game audio glitches (Matrix like sound), system locks up and crashes.

### Steps to Reproduce

1. Start Recording

### Anything else we should know?

Using latest Nvidia driver version 512.59.
Tested with CPU x264 and Nvidia x264 Encoders.
Recording format mkv, Rate Control CRF 18.
Tested with DX9, DX11, OpenGL 3.3, OpenGL 4.5, Vulkan applications.
Did not have this issue with older OBS version used 25.0.8.

**Comment by IcyChills** [comment]
Tested recording with Windows Game Bar, crash happens there as well. Could be an issue with newer Nvidia drivers or Windows 10 updates (Fresh install of Windows). Going to fall back to old drivers to test again.

**Comment by notr1ch** [comment]
Please use the forums or Discord for support requests.

**Comment by IcyChills** [comment]
> OBS doesn't cause system crashes, so whatever issue is likely with drivers/hardware.

I agree, as I have tested recording with XBox Game Bar as well, which caused the same crash as well. It may be a hardware/driver or Windows update fault. Closing as I believe this issue is not with OBS.
