### ISSUE TITLE
Wrong cursor size

### ISSUE THREAD

**Issue by All3xJ** [obsproject/obs-studio#6400]
### Operating System Info

Other

### Other OS

ArchLinux

### OBS Studio Version

27.2.3

### OBS Studio Log URL

https://obsproject.com/logs/9ZTSCeI11MokFzN1

### Expected Behavior

The size should be the same of the system icon cursor 

### Current Behavior

The size is bigger

### Steps to Reproduce

1. Open OBS
2. See the cursor size

### Anything else we should know?

I reported it here: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/4783
Also, if I start OBS with: `XCURSOR_SIZE=24 obs` it fixes. Why?

**Comment by RytoEX** [comment]
This seems like a duplicate of #5902.

**Comment by All3xJ** [comment]
> This seems like a duplicate of #5902.

yeah
