### ISSUE TITLE
Screen flickers

### ISSUE THREAD

**Issue by KrzzLpzz** [obsproject/obs-studio#6403]
### Operating System Info

Windows 11

### OBS Studio Version

Other

### OBS Studio Version (Other)

the last two (27.2.3 and 27.2.4)

### OBS Studio Log URL

Logs: https://obsproject.com/logs/cOCN14J6TXtnbdPA

### OBS Studio Crash Log URL

No crash.

### Expected Behavior

That my laptop screen didn't start flickering, because the truth makes me nervous. I use other programs and in the others nothing happens, I try to demand a little from the laptop and nothing happens, only with OBS has it given me that problem.

### Current Behavior

Hello, first, I'm sorry because English is not my main language.

I have recently noticed problems with OBS. What happens is that when I open the camera properties or filters in obs, my screen starts to flicker when there are apps in the background that use video (eg YouTube, Microsoft Teams, Zoom, etc) but only when obs and the properties or filter screen is on top (but not in full screen) of the program that has the video (it also happened to me to have obs in full screen with the properties of the camera open but with the zoom program in front). But when I capture the screen or close the properties or filters windows or go to the desktop, the problem disappears (the problem does not occur when the desktop is in the background of the program).

I have turned off the laptop's hardware acceleration and programs, checked the drivers, changed the graphics that OBS is using on the laptop and the problem persists.

Someone can help me?

*It only happens with OBS.
**i connected a second screen to my laptop and in the second screen doesnt happend
***i made a thread in the official website also, is in spanish too: https://obsproject.com/forum/threads/eng-es-what-cause-this-%C2%BFqu%C3%A9-causa-esto.155974/

https://user-images.githubusercontent.com/66136708/166118664-7c193d7f-1e58-40c6-9d5c-bb05726162e2.mp4

Sometimes the screen keeps black after the problem but i move the mouse and comes to the normality.
![3](https://user-images.githubusercontent.com/66136708/166118672-f9019eaf-380d-4055-bd02-091d3812d72b.jpeg)

https://user-images.githubusercontent.com/66136708/166118673-8ff99b07-04d1-424c-b0e3-0cf43897eeac.mp4

https://user-images.githubusercontent.com/66136708/166118678-27229de8-5e86-4f8e-8506-4a70ef4e84f0.mp4

### Steps to Reproduce

1. Start OBS
2. In a clear scene (preferably no other scenes)
3. Add a camera capture source
4. Open the zoom and activate your camera.
5. In obs open camera properties and move that window somewhere (mirroring my video)

**Comment by energizerfellow** [comment]
Update your Intel iGPU drivers to the [latest version](https://www.intel.com/content/www/us/en/support/products/197533/graphics/graphics-for-10th-generation-intel-processors/intel-uhd-graphics-for-10th-gen-intel-processors.html#drivers-software). Follow the [directions from Intel](https://www.intel.com/content/www/us/en/support/articles/000056629/graphics.html) if you get an error about OEM drivers and/or not applying to your hardware.

**Comment by KrzzLpzz** [comment]
> Update your Intel iGPU drivers to the [latest version](https://www.intel.com/content/www/us/en/support/products/197533/graphics/graphics-for-10th-generation-intel-processors/intel-uhd-graphics-for-10th-gen-intel-processors.html#drivers-software). Follow the [directions from Intel](https://www.intel.com/content/www/us/en/support/articles/000056629/graphics.html) if you get an error about OEM drivers and/or not applying to your hardware.

Thanks for your answer brother, but I have a question. Is it safe to uninstall my manufacturer's OEM driver?

An Intel driver is listed on the laptop support page, but it is the same as the one installed on my laptop and there is no new update from the manufacturer, but a new version is listed on the Intel page you mentioned. I downloaded that update, installed it (install was successful) an i restart the PC but when I go to see if the update was applied, it didn't and I'm still the same version as before the update.

**Comment by KrzzLpzz** [comment]
Update:

Well, after a successful installation of the latest Intel driver, the problem persists and I don't know what to do anymore because I already tried everything.

**Comment by gxalpha** [comment]
As frustrating as it is (it's frustrating for us as well), flickering like this is a driver or Windows issue.

While OBS' existence may catalyze this, OBS itself doesn't cause it (these flickers can also happen with other applications), and there's nothing we can do about it. Some drivers play more nicely than others, your best bet is usually to experiment with both the newest and older drivers to see which are more and which are less bad.

**Comment by RytoEX** [comment]
As mentioned above, this is likely to be a driver issue. If you are able to reliably reproduce this, an interesting piece of information would be whether or not you can reproduce this while running a build of OBS from our GitHub CI, as that might lead to a hint that we can pass along to driver vendors and Microsoft.
