### ISSUE TITLE
OBS soft-freezes the entire system if HAGS is active

### ISSUE THREAD

**Issue by TigerHix** [obsproject/obs-studio#6405]
### Operating System Info

Windows 11

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/NouqTin6nV7eK4Q4

### Expected Behavior

My PC does not soft-freeze.

### Current Behavior

OBS soft-freezes the entire computer (seemingly only the UI thread, as my streamers were able to hear me well when it happened). By "soft-freeze," I mean I can still move my mouse at maybe 3 FPS, and everything becomes slow and unresponsive (including my keyboard strokes). If I am lucky and have task explorer open, I can forcefully kill OBS and then everything immediately becomes smooth again. Otherwise I need to press the power button to forcefully shut down my computer.

### Steps to Reproduce

1. Create a Game Capture but with no game selected (or the game has just quitted).
2. My computer soft-freezes!
3. It seems like the more inactive Game Capture I have in scene, the laggier my computer becomes...

### Anything else we should know?

Turning off HAGS (Windows Hardware GPU Scheduler) as advised on the forums completely solved my issue. Here are the logs after I turned off HAGS: https://obsproject.com/logs/NouqTin6nV7eK4Q4

I figured I should still let you guys know that HAGS is causing more problems than you may expect and really should be something warned to the user if detected. This freezing issue has bothered me for months, and I am very happy that I have finally found the culprit...

**Comment by Fenrirthviti** [comment]
While I understand the frustration here, it's very unlikely that it's anything on our end causing this. We might be triggering some kind of system or driver issue, but just to set expectations I don't think there's anything we can do about this. It's an issue with MS and HAGS.

**Comment by Fenrirthviti** [comment]
As an additional note, this is likely to be an issue with your specific system more than widespread. HAGS has been known to cause issues, but I have not heard of it causing the entire PC to freeze up like that. I'd quicker blame faulty hardware or drivers. You're on quite an outdated NVIDIA driver as is, and I'm pretty sure that many issues with HAGS were resolved in newer driver versions. I'd recommend updating that first. I'm going to go ahead and close this as there's not really much for us to do, and this is more of a support issue.

**Comment by TigerHix** [comment]
> While I understand the frustration here, it's very unlikely that it's anything on our end causing this. We might be triggering some kind of system or driver issue, but just to set expectations I don't think there's anything we can do about this. It's an issue with MS and HAGS.

You are absolutely right! I fully believe it is a HAGS issue. But I do think it might be worthy for OBS to add a warning on startup to notify the user that HAGS can create stability issues, including soft-freezing your computer - even if you are not streaming or recording.

> As an additional note, this is likely to be an issue with your specific system more than widespread. HAGS has been known to cause issues, but I have not heard of it causing the entire PC to freeze up like that. I'd quicker blame faulty hardware or drivers. You're on quite an outdated NVIDIA driver as is, and I'm pretty sure that many issues with HAGS were resolved in newer driver versions. I'd recommend updating that first. I'm going to go ahead and close this as there's not really much for us to do, and this is more of a support issue.

Sure, I will try updating the NVIDIA driver. Alas, I hope it indeed only happened on me ¯\_(ツ)_/¯

**Comment by ninox14** [comment]
same issue here, the whole system lags every 5 seconds with strange side effects, and it feels like the video driver crashing 

strangely it stops lagging when I start streaming 

win 11 with the latest Nvidia driver
