### ISSUE TITLE
Windows 11 rounded corners are opaque

### ISSUE THREAD

**Issue by Sukadia** [obsproject/obs-studio#6413]
### Operating System Info

Windows 11

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/gs5tN_JZ27I8-oCg

### Expected Behavior

This all occurs with Window Capture on Windows 11, Windows 10 doesn't have this issue:

For windows applications, preferably the rounded corners would be transparent, since the window doesn't visibly occupy that space.

For maximized applications, the entire window should be captured.

### Current Behavior

For windowed applications, the rounded corners are displayed as sharp black corners.

For maximized applications, the entire window's capture is inset by 8 or so pixels on all sides.

This video shows both occurences; you can see the topbar very tight to the window buttons, and my mouse outlines where my screen (where the maximized application) actually ends. The maximized window is stretched to the 1920x1080 bounds (it'd be black space otherwise, its actual size is 1912x1024).

https://user-images.githubusercontent.com/37813632/166402766-a6886027-0429-47e2-a8c8-85ca7fb26e16.mp4

### Steps to Reproduce

1. Be on Windows 11, create a Window Capture
2. Maximize and/or window the captured window to see the issue

**Comment by Sukadia** [comment]
The windowed corners issue would likely be solved with #4964. Cropping I'm unsure about.

**Comment by jpark37** [comment]
VS Code is doing something custom with the title bar and client area. Try unchecking "Client Area" in the window capture properties.

**Comment by Sukadia** [comment]
> VS Code is doing something custom with the title bar and client area. Try unchecking "Client Area" in the window capture properties.

Thanks! That fixes that main issue. The rounded corner issue still stands though, hopefully this issue can put a bit of priority on the pull request mentioned above.

**Comment by jpark37** [comment]
Rounded corners are addressed by #6414.

Not that I speak for OBS as a whole, but I'm not a fan of that other PR for the reasons I mentioned inside.

**Comment by RytoEX** [comment]
Fixed by #6414.
