### ISSUE TITLE
async-delay-filter

### ISSUE THREAD

**Issue by summershrimp** [obsproject/obs-studio#6417]
### Operating System Info

Windows 11

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/FJo2L8ruWMhC1oEB

### Expected Behavior

Add async-delay-filter to a media source, audio should delayed as same time as video.

### Current Behavior

Add async-delay-filter to a media source, video delayed but audio not. Tested on vlc source and ndi sourcee.

### Steps to Reproduce

1. add a vlc source
2. add a video file to playlist
3. add async video filter to vlc source created on step 1
4. change delay time to 2000ms
5. you should see and here audio is not in sync with video.
...

**Comment by WizardCM** [comment]
Video filters do not affect audio. This is expected. If you need to delay audio, use Sync Offset in Edit -> Advanced Audio Properties.

**Comment by summershrimp** [comment]
> Video filters do not affect audio. This is expected. If you need to delay audio, use Sync Offset in Edit -> Advanced Audio Properties.

I checked the code of async-delay-filter.c
  https://github.com/obsproject/obs-studio/blob/952988d9ec1ac0f455c98fa65f8afd1be4cf36f8/plugins/obs-filters/async-delay-filter.c#L179

it says audio would automatic sync with video, but it not happend
