### ISSUE TITLE
OBS does not warn the user that AMF is not found when recording with AMF HEVC encoder

### ISSUE THREAD

**Issue by entriphy** [obsproject/obs-studio#6418]
### Operating System Info

Windows 11

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/BvG_qXIophD6Sh-a

### Expected Behavior

An error should appear to prevent the user from recording.

### Current Behavior

The user is able to "record" using the AMF HEVC encoder despite AMD software/drivers not being installed. When the user tries to stop the recording, it gets stuck at "Stopping recording..." and the video never gets written to a file. The logs display `AMF_NOT_FOUND`, but this error does not get properly relayed to the user and makes it look like the recording started successfully.

### Steps to Reproduce

1. Uninstall AMD Software/Drivers
2. Start a recording in OBS using H265/HEVC Encoder (AMD Advanced Media Framework)
3. Attempt to stop the recording

### Anything else we should know?

I noticed this issue after upgrading from Windows 10 to 11. I'm assuming that in the process of updating, it either removed the AMD driver or I had an older version of the driver. Installing the latest AMD driver fixes the issue, but OBS should still warn the user since the user won't know about it until they try to stop the recording, at which point all data is lost since the video never actually gets written to a file.
The AMF H.264 encoder seems to work fine with the drivers uninstalled, so it only seems to be an issue with the H.265 encoder.

(Yes, it seems dumb to not have graphics drivers installed, but I unfortunately fell victim to this issue after unknowingly having my drivers uninstalled, so it would probably be best to warn the user in this case)

**Comment by Pablomx2** [comment]
AMF_NOT_FOUND has shown since a long time ago, OBS devs haven't touched their implementation of the codec.
