### ISSUE TITLE
Missing tray icon on Wayland

### ISSUE THREAD

**Issue by PAI5REECHO** [obsproject/obs-studio#6422]
### Operating System Info

Other

### Other OS

NixOS

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://gist.github.com/PAI5REECHO/6826dd6d3cbe6be23b03ecd2cc0c7f96

### Expected Behavior

A tray icon to appear

### Current Behavior

![image](https://user-images.githubusercontent.com/96688573/166884346-78bc89ac-439a-414c-97f9-144f5abddeb5.png)

### Steps to Reproduce

1. Open OBS

**Comment by GeorgesStavracas** [comment]
This is very unlikely to be an OBS problem. It can be anything between Qt, and the receiving end.

What desktop environment are you using? Have you tried the Flatpak package?

**Comment by RytoEX** [comment]
Closing per above comment by @GeorgesStavracas .
