### ISSUE TITLE
Can't run OBS flatpak within VNC -- qt.qpa.xcb: could not connect to display 

### ISSUE THREAD

**Issue by OrvilleQ** [obsproject/obs-studio#6432]
### Operating System Info

Other

### Other OS

OpenSUSE 15.3

### OBS Studio Version

27.2.4

### OBS Studio Log URL

No log here.

### Expected Behavior

The program should works as binary.

### Current Behavior

OBS crashed with
```
orville@athlon:~> flatpak run com.obsproject.Studio 
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

### Steps to Reproduce

1. install obs studio with flatpak
2. connect to your server with VNC (`echo $DISPLAY 192.168.1.142:1`)
3. run `flatpak run com.obsprojects.Studio`
4. OBS crash with `qt.qpa.xcb: could not connect to display`
...

### Anything else we should know?

If I run OBS installed from RPM package, it actually works.

So I believe this is some issue with Flatpak side.

**Comment by norihiro** [comment]
I think `DISPLAY` environment should be `:1` without host IP address.

```
$ DISPLAY=:2 flatpak run com.obsproject.Studio
```
This starts OBS Studio.

If set `DISPLAY` like below, it fails as same as the issue report.
```
$ DISPLAY=127.0.0.1:2.0 flatpak run com.obsproject.Studio
F: Can't get document portal: GDBus.Error:org.freedesktop.portal.Error.Failed: Can't mount fuse fs on /run/user/1000/doc: File exists
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.
```

I tested above on Fedora 34, VNC server running as display number `:2`, and xfce4.

**Comment by GeorgesStavracas** [comment]
Thanks @norihiro for digging into that - closing this issue under the premise that this was not an OBS bug, but a misconfigured system. If necessary, we can reopen it.
