### ISSUE TITLE
youtube videos on any browser window in the background not shown after choosing another window (window capture mode)

### ISSUE THREAD

**Issue by satomy24** [obsproject/obs-studio#6433]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/WChHVceAMHtS3aZE

### Expected Behavior

the youtube video that is in the browser window (window capture mode) in the background is not shown in the recording.
![image](https://user-images.githubusercontent.com/94205012/167273809-6355f2c4-4004-4d94-ba24-0996198ec2e6.png)

### Current Behavior

the youtube video that is in the browser window (window capture mode) in the background should be shown in the recording.
![08 05 2022_00 10 52_REC](https://user-images.githubusercontent.com/94205012/167273485-f5d0e0c9-56a3-43c7-8796-f9b2f5e7648e.png)

### Steps to Reproduce

1.open obs
2.create window capture
3.choose a window with a youtube video (on any browser)
4. start recording
5. go back to the window that window capture mode is on it
6. choose another window or open anything else
7. youtube video turns to white (video not shown)
...

### Anything else we should know?

i turned the hard acceleration disabled in the browser, but still have the same issue.

**Comment by Fenrirthviti** [comment]
I'm pretty sure this is just normal Chrome DRM, there likely won't be anything we can do.
