### ISSUE TITLE
Artificial build limit ?

### ISSUE THREAD

**Issue by SkybuckFlying** [obsproject/obs-studio#6450]
### Operating System Info

Other

### Other OS

Windows 7

### OBS Studio Version

27.2.4

### OBS Studio Log URL

none for now.

### Expected Behavior

Build should be possible if using recent build tools. Visual Studio 2019.

### Current Behavior

It seems an artificial build rule may have prevented building OBS Studio for example:

"If windows 7 operating system detected abort build".

### Steps to Reproduce

1. Run windows 7 in virtual machine or real hardware.
2. Install Visual Studio 2019
3. Try and build OBS Studio or try build OBS Studio project file with CMAKE.

CMAKE will complain that Windows 10 SDK is required.

However as far as I can tell Visual Studio 2019 does already use Windows 10 SDK.

So this could mean that there are some strange rules inside the CMAKE file which probably detects the OS and therefore aborts the build.

### Anything else we should know?

Windows 7 without windows updates is a feature not a limitation. It causes 100% uptime.

While windows 10 and windows 11 are plagued with downtime because of windows update rollbacks.

**Comment by SkybuckFlying** [comment]
Which Windows SDK version does OBS studio require ?

According to visual studio 2019 information:

"
When the May 2019 Update is fully released: Run the Visual Studio installer or go to https://www.visualstudio.com/downloads/ and download it. Select “Universal Windows Platform development” under Workloads, Windows 10 SDK (10.0. 18362) will be included by default.
"

**Comment by derrod** [comment]
Read the build documentation: https://github.com/obsproject/obs-studio/wiki/Build-Instructions-For-Windows
