### ISSUE TITLE
obs is unsupported

### ISSUE THREAD

**Issue by 5390845** [obsproject/obs-studio#6455]
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

27.2.4

### OBS Studio Log URL

i can't get in to OBS

### Expected Behavior

obs to open 

### Current Behavior

it say "OBS appears to be running inside a chromeOS container. This platform is unsupported"
![Screenshot 2022-05-11 10 29 22 AM](https://user-images.githubusercontent.com/105376563/167890055-f4517b18-16d5-402c-a99f-72eb080f7849.png)

### Steps to Reproduce

1.try to run obs
2.
3.
...

**Comment by RytoEX** [comment]
As the error message says, we do not support running OBS inside a ChromeOS container.
