### ISSUE TITLE
Doubling of parts of the image only seen in OBS

### ISSUE THREAD

**Issue by myownfriend** [obsproject/obs-studio#6459]
### Operating System Info

Windows 11

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/qjvcgNj1nHpEDMnF

### Expected Behavior

Capturing the screen should just capture things as they're seen.

### Current Behavior

Sometimes parts of the image (a plane) can be doubled in a game. The best way to understand what I'm talking about is to watch this clip

https://clips.twitch.tv/WildCrunchyEggGOWSkull-xeMXvyoeXqomqXUm

The character gets overlayed on top of a video file but only the character gets doubled.

### Steps to Reproduce

I'm writing this on behalf of a friend but as far as I can tell, all she's doing is a screen capture while playing Final Fantasy IX.

I've seen it in the cutscene shown above but I've also seen it any time she opened the options to skip a cutscene. In that case, just the text in the window would double.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
