### ISSUE TITLE
Can't select screen share source when multiple pipewire sources are initializing on GNOME / Wayland

### ISSUE THREAD

**Issue by udoprog** [obsproject/obs-studio#6465]
### Operating System Info

Other

### Other OS

Fedora 36/37 GNOME 42 on Wayland

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/lMv8pfDN-syoL0KI

### Expected Behavior

You should be able to select screen / window to share when using more than one PipeWire source on Gnome.

### Current Behavior

You can't select screen / windows to share.

### Steps to Reproduce

1. Use Gnome Wayland with Mutter 42.1 (fixes black screen issue #6208)
2. Add a `Screen Capture (PipeWire)` or `Window Capture (PipeWire)` source but **do not** select which screen / window to share in the `Screen Share` dialog that pops up (see screenshot below).
3. Add another `Screen Capture (PipeWire)` or `Window Capture (PipeWire)` source. You can no longer interact with the first `Screen Share` dialog.
4. Close OBS (and have it save the scene).
5. Open up OBS and you can no longer interact with any of the `Screen Share` dialogs that pop up.

This is an issue since these dialogs pop up when OBS starts up a scene, so if you have more than one PipeWire source you can't configure them. The only remedy I've found is to remove and re-add the sources.

### Anything else we should know?

Screenshot of the `Screen Share` dialog that gets stuck:

![image](https://user-images.githubusercontent.com/111092/168338966-15bb1e07-e411-4c54-95a3-4f8578e44b6d.png)

**Comment by kkartaltepe** [comment]
As mentioned in #6380 this is a problem that your xdg-desktop-portal implementation will have to solve. You should file a bug against them as recommended in the earlier issue. I will leave this ope as georges hasnt closed this.

**Comment by GeorgesStavracas** [comment]
This is a problem in how xdg-desktop-portal-gnome handles its dialog windows, and is being tracked at https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/issues/40. There's nothing to do on OBS side.

**Comment by rloutrel** [comment]
I discovered this ticket and the one from xdg-destop-portal-gnome today. I am not sure to understand properly the limits between the client (obs) and the screen/window sharing service, so please forgive the bellow question if it is not appropriate or if it is something that xdg-destop-portal-gnome would not allow to implement.

### Context / Use case:
I am probably using the things badly, but I have one OBS profile with different scenes (each based on the program I am streaming) and I am too lazy to start all programs every times before launching OBS.

### Possible Feature:
Given that all windows are not always started, when OBS is launched, may I open a Feature-request ticket on the side of OBS, to postpone the access requests (not at the launch time but on a Need-Basis) and/or change the font colour in the list of sources (like in red with a mouse-over-hint, or whatever the Ux seems appropriate) for each sources without accesses allowed? So the user would notice it in the normal and studio modes and would not be annoyed if the shared element is not used.
