### ISSUE TITLE
Hang after closing properties or filters windows on Wayland with the NVIDIA driver

### ISSUE THREAD

**Issue by erik-kz** [obsproject/obs-studio#6466]
### Operating System Info

Other

### Other OS

Arhc Linux

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/THEcoe9zOlxpeXsK

### Expected Behavior

OBS studio should not hang after closing the properties or filters windows.

### Current Behavior

OBS studio hangs after closing the properties or filters windows.

### Steps to Reproduce

1. Launch obs on a Wayland desktop with an NVIDIA GPU using the proprietary driver.
2. Open either the "Properties" or "Filters" windows from the gear icon in the "Audio Mixer" panel.
3. Close the window .
4. Behold, obs is no longer responsive.

### Anything else we should know?

The hang is occurring in obs_display_destroy acquiring the displays_mutex, which is being called from the OBSQTDisplay destructor after closing the pop-up window.

Meanwhile, the graphics thread is stuck in eglSwapBuffers while holding said muted.

eglSwapBuffers is stuck because it is waiting for a wl_surface::frame callback from the previous swap.

This callback will never arrive because Qt has already destroyed the wl_surface by this point, which discards any frame callbacks registered for the surface.

In general, it is illegal to call eglSwapBuffers on an EGLSurface if the backing platform surface (in this case, the wl_surface) has been destroyed.

**Comment by GeorgesStavracas** [comment]
We call `eglSwapInterval(plat->display, 0)`, I assumed that would prevent waiting for frame callbacks. Is that not the case for NVidia?

**Comment by erik-kz** [comment]
Hmm, yes setting the swap interval to 0 should prevent waiting for frame callbacks. Unfortunately, it would seem that our eglSwapInterval implementation on Wayland has been completely broken since we added support for GBM-based compositors. I'm surprised nobody has noticed until now, honestly.

Fortunately it's a pretty trivial to fix, and doing so does resolve the hang. Thanks for helping to catch that.

__However__ I still think you guys might want to fix the underlying problem of calling eglSwapBuffers after the wl_surface has been destroyed. Even if this specific issue can be avoided with a driver fix, I'm fairly certain you're still invoking undefined behavior and it might come back to haunt you in the future.

**Comment by kkartaltepe** [comment]
> I'm surprised nobody has noticed until now, honestly.

Ill be honest I assumed this was a bug related to your earlier Qt patch not being applied, and have not bothered trying to diagnose why the nvidia drivers hang. It is quite impossible to figure out where to report such bugs such that anyone will care. Thanks for taking a look.

**Comment by GeorgesStavracas** [comment]
> However I still think you guys might want to fix the underlying problem of calling eglSwapBuffers after the wl_surface has been destroyed. Even if this specific issue can be avoided with a driver fix, I'm fairly certain you're still invoking undefined behavior and it might come back to haunt you in the future.

Yes, this is a problem with the current codebase, and I've been trying to redesign this part of libobs to not do that. It may take some time but it's being worked on.

**Comment by erik-kz** [comment]
> Ill be honest I assumed this was a bug related to your earlier Qt patch not being applied

FYI, that patch was made unnecessary by https://codereview.qt-project.org/c/qt/qtwayland/+/301712 which should also solve that socket polling problem. I probably ought to close my old MR, I'm just lazy.

**Comment by GeorgesStavracas** [comment]
@erik-kz does https://github.com/NVIDIA/egl-wayland/commit/ddaa27209a8149c1960c70799c87151206401bbc fix this problem on NVIDIA's side?

**Comment by erik-kz** [comment]
> does [NVIDIA/egl-wayland@ddaa272](https://github.com/NVIDIA/egl-wayland/commit/ddaa27209a8149c1960c70799c87151206401bbc) fix this problem on NVIDIA's side?

No, that addresses a different issue. I've checked in the fix for this bug internally, I just need to push it to the public GitHub repo.

**Comment by GeorgesStavracas** [comment]
Wonderful! Do you think you can tag a release for this fix after publishing the patches? This was a topic of concern recently
