### ISSUE TITLE
Failed to initialize video.

### ISSUE THREAD

**Issue by TherioJunior** [obsproject/obs-studio#6469]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

27.2.4

### OBS Studio Log URL

My OBS does not open.

### Expected Behavior

I expected OBS to just open normally.

### Current Behavior

OBS did not start and is instead giving me an error.
"Failed to initialize video.  Your GPU may not be supported, or your graphics drivers may need to be updated."
This happened after I made a system upgrade using pacman -Syyu. Pacman asked me to remove nvidia for nvidia-dkms, I said yes, then this error happened. Though even after switching back to nvidia, the error still persists.
![obs](https://user-images.githubusercontent.com/74859408/168412785-efec3e4a-d37d-447d-9c47-f9a21d8ed9e8.png)
Everything was still working fine yesterday.

### Steps to Reproduce

1. OS: Arch Linux
2. Use package "nvidia 515.43.04-2" as graphics driver for you GPU: "NVIDIA GeForce GTX 980 Ti", alternatively use "nvidia-dkms-515.43.04-1", it produces the same error.
3. Open OBS
...

### Anything else we should know?

Like I already mentioned in current behavior, everything was still working perfectly fine yesterday. Is it just that OBS doesn't recognize this version of the graphics driver? Also sorry for the bad grammar in case there is some, I'll be here to answer questions if you have some.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
