### ISSUE TITLE
obs recording blank videos

### ISSUE THREAD

**Issue by jakbin** [obsproject/obs-studio#6482]
### Operating System Info

Other

### Other OS

kali linux

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/GDZi7nG2iQCmkp9H

### Expected Behavior

it should record screen video, but it recorded only blank videos. obs works fine with version 27.2.0  .

### Current Behavior

it recorded only blank videos

### Steps to Reproduce

1. i just upgrade my obs studio.
2. its recording only blank videos.
3.
...

**Comment by notr1ch** [comment]
Please use the forums or Discord for support.
