### ISSUE TITLE
svt-av1 not avivable on linux

### ISSUE THREAD

**Issue by jokbon** [obsproject/obs-studio#6489]
### Operating System Info

Other

### Other OS

Kubuntu based on Ubuntu 20.04

### OBS Studio Version

27.2.4

### OBS Studio Log URL

none

### Expected Behavior

svt-av1 shud be posible to select with recording format mkv

### Current Behavior

svt-av1 not posible to select with recording format mkv

### Steps to Reproduce

1.start obs
2.settings
3.output
4.recording
5.recording format mkv
6.Encoder SVT-AV1 is missing

### Anything else we should know?

Just writing up in case obs completed codec on windows and forgot to add on linux.

**Comment by jokbon** [comment]
I can't use alternative AOM-AV1 as it crashes on both windows and linux on my system.

**Comment by tytan652** [comment]
It only means that Ubuntu don't build their FFmpeg with SVT-AV1.

You can try the OBS Flatpak since it provides it's own FFmpeg build.

**Comment by mihawk90** [comment]
Definitely available on Linux:

![image](https://user-images.githubusercontent.com/556162/168544561-4991a7c9-b994-4164-9868-d1dc1f6fe9be.png)

But FFmpeg needs to support it as tytan mentioned.

You can check easily:
```
z% ffmpeg -codecs | grep AV1
ffmpeg version 5.0.1 Copyright (c) 2000-2022 the FFmpeg developers
...
 DEV.L. av1                  Alliance for Open Media AV1 (decoders: libdav1d libaom-av1 av1 av1_cuvid av1_qsv ) (encoders: libaom-av1 librav1e libsvtav1 )
```

Important is the E.
