### ISSUE TITLE
Automatic Reconnect does not work reliably with Dynamic Bitrate

### ISSUE THREAD

**Issue by jgaull** [obsproject/obs-studio#6497]
### Operating System Info

macOS 12

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/sTvi20FCfQnEdY5p

### Expected Behavior

The automatic reconnect feature would allow OBS to reconnect, even while using Dyanmic Bitrate (Dynamically change bitrate to manage congestion (Beta)).

### Current Behavior

OBS will not automatically reconnect. Clicking Stop Stream does not stop the stream. OBS must be "force quit" and relaunched. I will refer to this as "the broken state".

### Steps to Reproduce

1. Connect your computer to the internet via wifi
2. Launch OBS
3. Enable "Dynamically change bitrate to manage congestion (Beta)" under Advanced
4. Enable Automatically Reconnect, set the retry delay to `5 s` and the Maximum Retries to `9999`
5. Apply the settings and click ok
6. Start Streaming
7. Wait until the stream has been live for 30 seconds
8. Disable the wifi adapter on your computer
9. Wait for at least 15 seconds
10. Re-enable your wifi adapter

### Anything else we should know?

- The purpose of my test case is to replicate a symptom that I frequently see while streaming on bonded LTE connections. The steps I've included in this bug consistently reproduce the symptom which I have observed in more than half of my recent streams.
- I am hoping that a fix to the issue described here would apply to my real-world use case of streaming in unstable network conditions, not just when somebody disables their wifi.
- This method will not reproduce the issue 100% of the time. I estimate it at ~60% success.
- I have never seen the issue when Dynamic Bitrate (beta) is disabled.
- I am unable to reproduce this behavior using an ethernet connection
- I am using an M1 Macbook Pro 14"
- While in the broken state I disabled and re-enabled Automatically Reconnect, waiting 30 seconds between each settings change, but this did not consistently work around the issue. I'm assuming the times it appeared to resolve the issue were a coincidence.
- I read through [this issue](https://github.com/obsproject/obs-studio/issues/2496), but I feel it does not apply to the issue I'm describing because:
  1. Nobody on the thread has reported that the issue still exists
  2. [The fix](https://github.com/obsproject/obs-studio/pull/5169) appears to have to do with `nvenc`, which is not supported on my computer
- While I have only reproduced this issue while in a controlled environment using a Mac computer, I believe I have observed the same behavior on a Windows 10 computer in unstable network conditions
- The times when I _do not_ observe this issue I see `Freeing 1352 remaining packets` in the logs

I hope this information is helpful. Please let me know if I can provide further information.

Thank you!

**Comment by pkviet** [comment]
Wasn't able to repro with these exact repro steps.
My test machine was win 10 pro though.
So there's probably something else at play on your network.

**Comment by jgaull** [comment]
I spent about an hour yesterday trying to find a way to reproduce this issue on Windows 10, but I was unsuccessful. I experimented with all different ways of creating network instability:

- toggling wifi on/of
- disconnecting and reconnecting from wifi
- disabling the wifi device in the device manager
- removing the wifi antenna from my computer
- connecting to a mobile hotspot and then moving the mobile hotspot out of range
- [Clumsy](https://github.com/jagt/clumsy)

But none of them worked.

Given this I feel that the issue is much easier to reproduce on Mac OS. However, I have observed the issue on both Windows and Mac out in the field on my livestream so I feel confident there is _some_ way to reproduce it on a test bench. Maybe I need to build a Faraday cage 🤔

**Comment by jgaull** [comment]
I went back and tested this on my mac and was only able to reproduce the issue ~25% of the time. I think I need to get more precise with my testing steps.

**Comment by gxalpha** [comment]
Hey there, I've tried reproducing this on my Mac with no success, it seems like it always recovers correctly.
Did you happen to be able to get more precise steps to reproduce?

**Comment by pkviet** [comment]
closing for now; if @jgaull you have further comments, feel free to reopen.
