### ISSUE TITLE
VLC Video Source only playing one .xspf file instead of multiple from a directory?

### ISSUE THREAD

**Issue by Allanbuzzy** [obsproject/obs-studio#6513]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/8FhbDrqFjUBqx3Wu

### Expected Behavior

When adding a directory full of VLC .xspf files (i.e: /stream/StreamPlaylists), the VLC Source should, in theory, play the xspf files in order and/or in shuffle if selected.

### Current Behavior

VLC Video Source just replays one .xspf file over and over, and won't skip unless the user constantly presses the next button constantly.

### Steps to Reproduce

1. Open up OBS
2. Create multiple .xspf files, all in different orders to each other, on VLC. (place multiple video files all in different orders, Media > Save Playlist to File)
3. Save them to a directory.
4. Add a new VLC Video Source by clicking on the + 
5. Right click on VLC Video Source, click properties.
6. Click the +, Add Directory, then add the directory you have made.
7. Click the >I button multiple times and see if the pattern is the same upon multiple presses.

**Comment by Fenrirthviti** [comment]
Playlist functionality is not currently supported by the VLC source. We suspect that these files are handled by the VLC UI, and not libvlc itself, so this is probably not something we can fix. We welcome PRs for it, but this is currently not a bug, but simply a missing feature.
