### ISSUE TITLE
Missing OBS_FRONTEND_EVENT_SCENE_COLLECTION_RENAMED from obs version 27.2.4

### ISSUE THREAD

**Issue by DigitOtter** [obsproject/obs-studio#6517]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://github.com/obsproject/obs-studio/blob/27.2.4/UI/obs-frontend-api/obs-frontend-api.h

### Expected Behavior

The documentation for libobs v27.2.4, lists an `obs_frontend_event` called `OBS_FRONTEND_EVENT_SCENE_COLLECTION_RENAMED`, see [here](https://obsproject.com/docs/reference-frontend-api.html?highlight=OBS_FRONTEND_EVENT_SCENE_COLLECTION_RENAMED#c.obs_frontend_event).

I would like to listen for the event to detect when a scene collection is renamed.

### Current Behavior

When looking at the source code for version 27.2.4, `OBS_FRONTEND_EVENT_SCENE_COLLECTION_RENAMED` is missing from `enum obs_frontend_event` (see [here](https://github.com/obsproject/obs-studio/blob/27.2.4/UI/obs-frontend-api/obs-frontend-api.h), line 60).

The enum is added a commit after the one tagged with `27.4.2`, see [here](https://github.com/obsproject/obs-studio/blob/c7bf56401506137cfdc9cafbbd28e9dcc7bb48b6/UI/obs-frontend-api/obs-frontend-api.h), line 62

### Steps to Reproduce

1. Compare file `UI/obs-frontend-api/obs-frontend-api.h` in the commit tagged `27.2.4` and `c7bf56401506137cfdc9cafbbd28e9dcc7bb48b6`
2. Note the missing `OBS_FRONTEND_EVENT_SCENE_COLLECTION_RENAMED` at line 62

**Comment by RytoEX** [comment]
This is not a bug, per se. As you've noted, the OBS_FRONTEND_EVENT_SCENE_COLLECTION_RENAMED event was added _after_ 27.2.4 was released, so it is not a part of that release. The documentation site, however, lists the most recent version number and does not indicate if any items are for an upcoming release rather than the current stable release.

I'm looking into if this can be clarified, or if the hosted docs can be reverted to a more 27.2.4 accurate versions.

**Comment by DigitOtter** [comment]
Thanks, I wasn't sure what to list it under. If it's not a bug, you can close the issue, I just wanted to make sure I wasn't missing something.

**Comment by PatTheMav** [comment]
@RytoEX can this be closed?

**Comment by RytoEX** [comment]
Yes. The docs have been updated, both for 28.x and 27.2.x.
https://obsproject.com/docs/
https://obsproject.com/docs/27.2/
