### ISSUE TITLE
Ubuntu 22.04 with wayland QT crash

### ISSUE THREAD

**Issue by wiltonlazary** [obsproject/obs-studio#6524]
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

27.2.4

### OBS Studio Log URL

.

### OBS Studio Crash Log URL

.

### Expected Behavior

Open normaly

### Current Behavior

qt.qpa.wayland: Wayland does not support QWindow::requestActivate()

### Steps to Reproduce

1. open obs
2.
3.
...

### Anything else we should know?

 export QT_QPA_PLATFORM=wayland

**Comment by gxalpha** [comment]
Please include an OBS log file.

**Comment by kkartaltepe** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
