### ISSUE TITLE
linux-capture: Xcomposite - darray_erase: Assertion `idx < dst->num' failed

### ISSUE THREAD

**Issue by Chiitoo** [obsproject/obs-studio#6532]
### Operating System Info

Other

### Other OS

Gentoo Linux

### OBS Studio Version

Git

### OBS Studio Log URL

https://obsproject.com/logs/vnjcnBE1fibN3ZxK

### Expected Behavior

No crashy crashy.

### Current Behavior

obs: /[build-path]/libobs/util/darray.h:312: darray_erase: Assertion `idx < dst->num' failed.

Thread 34 "libobs: graphic" received signal SIGABRT, Aborted.

### Steps to Reproduce

1. Starting with a clean profile (after deleting '$HOME/.config/obs-studio', although it seems to be enough if the 'Untitled.json' is deleted from under 'scenes'), run OBS Studio.
2. Add a Window Capture (Xcomposite) source.
3. Select a window to capture, and close said window.

- It may be enough to simply close OBS Studio instead of closing the source window.
- I can also trigger the failure by mousing over the LXQt panel to make it come out of hiding (it is set to automatically hide).

### Anything else we should know?

This starts with commit 1604400e488 [1], although I did not have it happening when initially testing the PR for it.

Not that I'm familiar with the code, but it doesn't look too normal that 'idx' is suddenly such a big number (18446744073709551615), when it seems to normally be 0 to 3.  Or maybe 4 was the highest I saw while testing with added logging.

Log with backtrace: https://gist.github.com/Chiitoo/3ac706dc0d134a85d467970489ee9018

1. https://github.com/obsproject/obs-studio/commit/1604400e488f66c885dc43e9ad8fb2a56beaa0bb

**Comment by kkartaltepe** [comment]
Thanks I cannot replicate this on my side but the fix should be in the referenced PR, if this happens consistently for you can you try testing it out?

**Comment by adsr** [comment]
Fix confirmed but see my comment on the PR. I think there's also a logic bug.
