### ISSUE TITLE
Replay Buffer "Save Replay" shortcut stops working after ~30 minutes

### ISSUE THREAD

**Issue by xxDementia** [obsproject/obs-studio#6544]
### Operating System Info

macOS 12

### OBS Studio Version

Git

### OBS Studio Log URL

https://obsproject.com/logs/b1yahc4t9P7JEAhQ

### Expected Behavior

Save a replay upon using shortcut

### Current Behavior

Does not save replay using shortcut

### Steps to Reproduce

1. Enable Replay Buffer, Start Replay Buffer
2. Use a shortcut to save replay
3. Play a game, clip over a period of time until saving message stops popping up

### Anything else we should know?

Manually pressing save button works, shortcut saving stops working after a while

**Comment by PatTheMav** [comment]
Is there no video file saved at all or is the file just not usable (cannot be played back)?

**Comment by RytoEX** [comment]
Please retest in OBS Studio 29.0.0 or newer. We've rewritten the hotkeys implementation on macOS for OBS Studio 28.

**Comment by xxDementia** [comment]
Will do, will return if I have any issues.

**Comment by xxDementia** [comment]
**Two new entirely different issues**:
- Replay buffer keeps recording past the limit I set (Set to 30s, records for 14 minutes and counting)
- When OBS is left on long enough, it eventually will display a still image in the preview (and record that still image). I assume this has something to do with me setting my Mac to sleep WHILE replay buffer is on
![image](https://user-images.githubusercontent.com/69117597/213578807-e6eaa200-dc9d-4449-9784-0766d4e424f9.png)
https://user-images.githubusercontent.com/69117597/213579051-433541c3-e25f-4c40-8d70-cc5150571d1c.mp4

**Comment by Fenrirthviti** [comment]
If those issues are different to this, please report them as separate issue reports to avoid over scoping this issue report in to multiple unrelated issues. Make sure to include proper reliable reproduction steps.

**Comment by xxDementia** [comment]
Got it 👍

**Comment by RytoEX** [comment]
Most importantly: is the original issue still reproducible in OBS Studio 29.0.0 or not? If not, then we will close this GitHub Issue as resolved.

**Comment by xxDementia** [comment]
Don't think so, you can go ahead and close it
