### ISSUE TITLE
Failed build

### ISSUE THREAD

**Issue by TomaszWaszczyk** [obsproject/obs-studio#6548]
### Operating System Info

Other

### Other OS

Debian 11

### OBS Studio Version

27.2.4

### OBS Studio Log URL

not able to install

### Expected Behavior

Able to install

### Current Behavior

FAILED: plugins/linux-pipewire/CMakeFiles/linux-pipewire.dir/pipewire.c.o 
/usr/bin/ccache /usr/bin/cc -DHAVE_OBSCONFIG_H -Dlinux_pipewire_EXPORTS -I../libobs -Iconfig -I../deps/glad/include -isystem /usr/include/pipewire-0.3 -isystem /usr/include/spa-0.2 -isystem /usr/include/gio-unix-2.0 -isystem /usr/include/libmount -isystem /usr/include/blkid -isystem /usr/include/glib-2.0 -isystem /usr/lib/x86_64-linux-gnu/glib-2.0/include -O2 -g -DNDEBUG -fPIC -Wextra -Wvla -Wno-unused-function -Wno-missing-field-initializers -fno-strict-aliasing -Werror-implicit-function-declaration -Wno-missing-braces -mmmx -msse -msse2 -D_REENTRANT -I/usr/include/pipewire-0.3 -I/usr/include/spa-0.2 -pthread -I/usr/include/gio-unix-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -MD -MT plugins/linux-pipewire/CMakeFiles/linux-pipewire.dir/pipewire.c.o -MF plugins/linux-pipewire/CMakeFiles/linux-pipewire.dir/pipewire.c.o.d -o plugins/linux-pipewire/CMakeFiles/linux-pipewire.dir/pipewire.c.o -c ../plugins/linux-pipewire/pipewire.c
../plugins/linux-pipewire/pipewire.c: In function ‘build_format’:
../plugins/linux-pipewire/pipewire.c:415:10: error: ‘SPA_POD_PROP_FLAG_MANDATORY’ undeclared (first use in this function); did you mean ‘SPA_POD_PROP_FLAG_HARDWARE’?
  415 |          SPA_POD_PROP_FLAG_MANDATORY |
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |          SPA_POD_PROP_FLAG_HARDWARE
../plugins/linux-pipewire/pipewire.c:415:10: note: each undeclared identifier is reported only once for each function it appears in
[76/351] Building CXX object plugins/decklink/CMakeFiles/decklink.dir/decklink-device-instance.cpp.o
ninja: build stopped: subcommand failed.
  + ERROR during build step: configure build

### Steps to Reproduce

1.
2.
3.
...

**Comment by WizardCM** [comment]
Please provide full steps that you followed when building.

**Comment by kkartaltepe** [comment]
You require a newer version of pipewire.
