### ISSUE TITLE
OBS on MacOS requires permission to read keystrokes at any time.

### ISSUE THREAD

**Issue by borseno** [obsproject/obs-studio#6551]
### Operating System Info

macOS 12

### Other OS

macOS

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com

### Expected Behavior

OBS should not want to read all my keystrokes at any time.

### Current Behavior

It allows to read keystrokes. Probably there's some backdoor.

### Steps to Reproduce

1. Download OBS for MacOS
2. Launch it
3.
...

### Anything else we should know?

I think that it could be some backdoor. Could you please check.

**Comment by derrod** [comment]
Access to keystrokes is needed for hotkeys. This isn't an issue, although we're working on improvements to the permissions setup.
