### ISSUE TITLE
Xcomposite does not list borderless windows

### ISSUE THREAD

**Issue by ysalmon** [obsproject/obs-studio#6559]
### Operating System Info

Ubuntu 20.04

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/FAba4fReNarYRRZM

### Expected Behavior

All toplevel windows to be listed in the Xcomposite source dropdown.

### Current Behavior

An existing, bordeless, toplevel window is not listed.

### Steps to Reproduce

1. Have an application create a borderless window
2. Add a XComposite source to OBS scene and try to select that window

### Anything else we should know?

The borderless window is from https://github.com/ysalmon/draw-on-stream-telestrator.
The current idea is to have this (translucent) window on top of an OBS projector, and a XComposite capture of that window in the scene, to enable live annotation of the scene with either the mouse or a wacom tablet.

This might evolve into an OBS plugin, but I am very far from being able to do that right now.

**Comment by mihawk90** [comment]
Unless "borderless window" is handled differently then e.g. Borderless Fullscreen games, I can't confirm this. They capture just fine and I have done this with a multitude of games.

I also forced one of my Konsole windows to remove the Titlebar and Frame (which should be the same as "borderless" then?), and I had no issue capturing that either.

Cannot test your sample application as I'm getting:
```
z% ./painter.py
Traceback (most recent call last):
  File "/home/tarulia/Development/draw-on-stream-telestrator/./painter.py", line 945, in <module>
    Painter(root)
  File "/home/tarulia/Development/draw-on-stream-telestrator/./painter.py", line 285, in __init__
    self.load_config()
  File "/home/tarulia/Development/draw-on-stream-telestrator/./painter.py", line 406, in load_config
    if self.configfollowing.startswith("*") :
AttributeError: 'NoneType' object has no attribute 'startswith'
```

And the window from the original un-forked repo doesn't seem to be borderless either.

**Comment by ysalmon** [comment]
Thank you for helping here. You spotted a bug in way changes (which I now corrected). The borderless mode is only activated when the ``config.json`` file states a window to follow (the idea is to put there the title name of a window, and the app will adjust its own window on top of that one). Here to follow an OBS projector :
```
{
  "width": 5,
  "color": "#000000",
  "background": "#ffffff",
  "mode": "pen",
  "alpha": 94,
  "fill": null,
  "geometry": "1098x617+2191+1046",
  "separate": true,
  "following": "Projecteur fen\u00eatr\u00e9 (aper\u00e7u)",
  "ratio": [
    1280,
    720
  ]
}
```

How did you force a Konsole window to be borderless ? I cannot find such an option in its settings.

Currently, I am using tkinter's ``overrideredirect``.

**Comment by kkartaltepe** [comment]
You must correctly work with your compositor to negotiate windowless. Unredirected windows have never been supported.
