### ISSUE TITLE
AOM AV1 encoder CBR setting is actually ABR

### ISSUE THREAD

**Issue by SuslikV** [obsproject/obs-studio#6560]
### Operating System Info

Other

### Other OS

Any OS

### OBS Studio Version

Git

### OBS Studio Version (Other)

de11632

### OBS Studio Log URL

about:blank

### Expected Behavior

For AV1 encoder (AOM AV1 in _Settings>Output>Output Mode: Advanced>Recordings tab_) the _Rate Control_  CBR entry setting should be replaced by the ABR (average bitrate).

When the AV1 encoder _Rate Control_ set to CBR, the recorded file should has predictable size.

### Current Behavior

When for AV1 encoder the _Rate Control_ set to CBR, the recorded file may has significantly lower size than predicted by the bitrate (especially for static pictures).

### Steps to Reproduce

1. Add Color source to OBS (static picture)
2. Set OBS to 30 fps, 1280x720 (base canvas and output), Output Mode: Advanced, Encoder AOM AV1, Control Rate CBR, Bitrate 2500 Kbps, mute all sound sources (if any).
3. Make recording for about 30 sec long.
4. Notice that the recorded file is much smaller in size than the 2500 Kbps * 30 sec + Audio data (~80KB or x100 less than expected ~9MB media file).

### Anything else we should know?

For example, the CBR setting for the x264 encoder in OBS makes padding. Not padded _Rate Control_ in OBS named ABR (average bitrate).

I assume that the CBR can be read as Constant Bit Rate or Constrained Bit Rate in OBS. Thus, some minor clarification needed.

It would be nice to keep same logic in parameters naming across the encoders.

**Comment by Fenrirthviti** [comment]
Closing per above.
