### ISSUE TITLE
Disabling `auto`  for focus in camera properties don't set manual focus

### ISSUE THREAD

**Issue by asm128** [obsproject/obs-studio#6580]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/WQr0Okw3YERVDul1

### Expected Behavior

I expect autofocus to disable autofocus and set focus to the value shown in the dialog:

![image](https://user-images.githubusercontent.com/26621255/171561500-96610e65-6aae-404a-8238-a10cdf613cdb.png)

### Current Behavior

Disabling `auto` for `focus` just leaves a zombie value focus set, which is worsened by the lack of UX in the UI of the Camera Control dialog, which don't allow to set a value by typing numbers and it prevents to enable/disable autofocus during recording unless you're some kind of combination of Superman + Flash + Microman.

### Steps to Reproduce

1. Set focus to a custom value, such as 63
2. Tick "auto" checkbox
3. Disable "auto" checkbox
4. The value will be other than 63

### Anything else we should know?

This bug is actually a combination of half-done tasks which result in a completely unusable feature that for some recordings is mandatory.

**Comment by MatuaDoc** [comment]
That particular properties window technically doesn't have anything to do with OBS, that's provided by Windows. If it's not doing what you want, that's down to (A) Windows, and (B) the device driver provided by the manufacturer (if you have installed one).

**Comment by feetstv** [comment]
That particular interface isn't actually OBS', it's provided automatically by Windows. If it isn't doing what you want, that's either (A) Windows' fault, or (B) your device driver's fault (if you installed any).

**Comment by feetstv** [comment]
A "resolution" would be to use the software that comes with the device drivers for your camera, if any. For example, Logitech's streaming cameras are configurable with G-Hub.

**Comment by asm128** [comment]
Thank you. I downloaded LogiTune and it seems to be even more disfunctional as it doesn't even show numbers nor allow to change other settings. I'll file a bunch of tickets to both Logitech and Microsoft until they decide to invest some time learning to code functional UIs.
