### ISSUE TITLE
OBS stopped working after upgrading to Ubuntu 22.04

### ISSUE THREAD

**Issue by Dagur** [obsproject/obs-studio#6582]
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.2.3+dfsg1

### OBS Studio Log URL

Cannot start OBS Studio

### Expected Behavior

Can't run OBS anymore

### Current Behavior

I get an error and OBS exits

```
$ obs
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Aborted (core dumped)
```

### Steps to Reproduce

1. Run OBS

### Anything else we should know?

Worked fine in 21.10

**Comment by gxalpha** [comment]
This OBS version does not sound like our official build.
Please follow the Ubuntu Instructions on https://obsproject.com/download#linux to get our official build and try again.

**Comment by Gol-D-Ace** [comment]
Hi
Please remove the Debian OBS Studio version and check if the PPA is having the same issue.

sudo apt remove obs-studio
sudo apt remove obs-plugins
sudo apt remove libobs0

sudo add-apt-repository ppa:obsproject/obs-studio
sudo apt install obs-studio

**Comment by Dagur** [comment]
Thank you both. I followed Gol-D-Ace's instructions and that worked :)
