### ISSUE TITLE
Mac M1 recordings still a bit choppy and laggy

### ISSUE THREAD

**Issue by Gabby16Bitbox** [obsproject/obs-studio#6592]
### Operating System Info

macOS 12

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/AA8AzzNA0530-LBt

### Expected Behavior

No lag and choppy recording

### Current Behavior

When i use OBS on my Mac mini m1 16gb ram the recording is a bit sloppy and choppy, is decent but not perfect as with the same equipment on my windows pc.

I just use obs and start record my PC Screen with an elgato HD 60+

i need that because i want to record my gameplay in obs so i can edit my gameplay directly in final cut without swapping disk and loose time. And maybe use it as streaming pc in the future.

### Steps to Reproduce

I use an Elgato HD 60+ to record my windows PC i have tried all the codecs, but all are a bit laggy. The best one seem the Hardware Apple.

### Anything else we should know?

A lot of people are moving to use mac as a streaming recording pc, it would be nice to have a reliable software here to finally record with no hassle or performance drop of the gaming pc.

**Comment by gxalpha** [comment]
This issue appears to be a support request, for which we don't use GitHub Issues.
Please make sure to visit the support sections on our [Discord server](https://discord.gg/obsproject) or [Forums](https://obsproject.com/forum).

Thank you!

**Comment by Gabby16Bitbox** [comment]
i see, but it's a bug on obs side or mac in general because it has the same behavior on all my macs
