### ISSUE TITLE
WriteN, RTMP send error 32 / 9

### ISSUE THREAD

**Issue by VortexAcherontic** [obsproject/obs-studio#6594]
### Operating System Info

Other

### Other OS

openSUSE Tumbleweed

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/cT1epQKpDHvyEAtn

### Expected Behavior

Stream to not disconnect

### Current Behavior

Stream randomly disconnected from Twitch two times.  
At the first DC it reconnected but at the 2nd one OBS did not recover and I had to force quit it via KDE System monitor

### Steps to Reproduce

It's hard to repoduce as this happens randomly.

1. Stream
2. Wait for the stream to randomly disconnect

### Anything else we should know?

I'm using the flatpak version with no additional addons.  

This issue happened in near each stream in the past two weeks or so to me now.  
Sometimes it did not happened in over 8h sometimes it happens after like 30 minutes which makes it hard to reproduce tho :/  

At this point I am not even sure if this is an issue with Twitch instead of OBS but some needs to start somewhere ^^"

**Comment by derrod** [comment]
The disconnect seems like a network issue, rather than an OBS issue. The freezing issue can happen if the connection dies in a way that blocks OBS due to a missing timeout, which #6431 aims to fix.
