### ISSUE TITLE
Recording just one minute and shows up a black screen

### ISSUE THREAD

**Issue by RenanZX** [obsproject/obs-studio#6595]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/3ZLciUWlOc_QZ1eV

### OBS Studio Crash Log URL

https://obsproject.com/logs/h7EbK8jvRABcFu0c

### Expected Behavior

Record screen image all time

### Current Behavior

Recorded 1 minute or 30 seconds and displays a black screen after this time

### Steps to Reproduce

1. Open OBS Studio and Xbox App
2. Broadcast your xbox screen to Xbox app in PC
3. Setup Gaming tab in OBS studio and select Xbox App
4. Start Record
5.  After 2 or 5 minutes stop record, it will show a black screen after 1 minute of record.

### Anything else we should know?

No

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
