### ISSUE TITLE
Window Capture: Client Area on/off makes no difference

### ISSUE THREAD

**Issue by DarkiStar** [obsproject/obs-studio#6596]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

???

### Expected Behavior

The expected result would be that with the setting "Client Area on" only the client area of the window is included. 

### Current Behavior

The "Windows header" etc. will also be included. 
With Chrome Browser as target window also the browser tabs are included etc.
It doesn't matter if "Client Area" is on or off. The result is identical.

### Steps to Reproduce

1. Open Chrome Browser and surf to any site
2. Capture that Chrome Browser Windows in OBS with Windows Capture
3. Switch between Client Area on / off and see there is no difference
...

### Anything else we should know?

All OBS developers are doing a great job. Thank you.

**Comment by MatuaDoc** [comment]
This is because Chrome doesn't have a proper Windows title bar. It draws its own title bar in the client area.

**Comment by WizardCM** [comment]
For Chrome, this is expected behaviour.
