### ISSUE TITLE
Plasma Wayland with PipeWire won't record screen.

### ISSUE THREAD

**Issue by raphipod** [obsproject/obs-studio#6601]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.2.4-1 (Arch Linux package)

### OBS Studio Log URL

https://obsproject.com/logs/U7_7GsPgdnr-g2y5

### Expected Behavior

OBS should record the screen, but it doesn't. Mouse is captured, though.

### Current Behavior

OBS should record the whole screen, but it's just blackscreen. Error message spam in console:

**glDisable failed, glGetError returned GL_INVALID_OPERATION(0x502)
glDeleteBuffers failed, glGetError returned GL_INVALID_OPERATION(0x502)**

### Steps to Reproduce

1. Install obs-studio with pacman
2. Add "Screen Capture (PipeWire)" to Sources
3. Choose screen to be captured (Preview is already just blackscreen, mouse is captured though...)
4. Record a bit, video is completely black.

### Anything else we should know?

Arch Linux
Kernel: 5.18.1-zen1-1-zen
Display server: Wayland
WM: Plasma 5.24.5
GPU: NVIDIA GTX 1660 Super with Driver 515.48.07

**Comment by kkartaltepe** [comment]
Nvidia on wayland is not supported.
