### ISSUE TITLE
linux-capture: Cannot select window to capture with pipewire window caputre source when using xorg

### ISSUE THREAD

**Issue by SwooshyCueb** [obsproject/obs-studio#6605]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/6aZ8WUxv9Zc0MDZt

### Expected Behavior

"Select Window" button allows me to select a window to capture.

### Current Behavior

"Select Window" button prints `warning: [pipewire] Failed to create session, denied or cancelled by user` to the log. Nothing else happens.

### Steps to Reproduce

1. Add a "Window Capture (Pipewire)" source
2. Click "Select Window"

### Anything else we should know?

Googling the error printed in the log only returns results dealing with Wayland. I am not using Wayland.
"Window Capture (Xcomposite)" does not show up in the list of available sources. (maybe I shouldn't be using Pipewire for window capture and this is the real issue?)
I have `OBS_USE_EGL` set to `1` so that I can use vkcapture.

**Comment by kkartaltepe** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

**Comment by kkartaltepe** [comment]
> So this behavior is by design?

Probably, Also egl on X11 is unsupported until the next release.

**Comment by tytan652** [comment]
Not all XDG portal implementation are able to capture under X11. Most of them are focused on Wayland.
