### ISSUE TITLE
Audio Output capture Echos with recording audio

### ISSUE THREAD

**Issue by benji88i** [obsproject/obs-studio#6607]
### Operating System Info

Other

### Other OS

Fedora 36 (Gnome version)

### OBS Studio Version

27.2.4

### OBS Studio Version (Other)

27.2.4 (64 Bit)

### OBS Studio Log URL

https://obsproject.com/logs/WrRKZFZQKSDQO2_g

### OBS Studio Crash Log URL

no crash

### Expected Behavior

I hope I am describing this correct. 

My expected behavior is that the inputs from my speakers will be transmitted through and recorded by OBS. But I get echos

### Current Behavior

Everything works perfect except the students voice is echoey and the voice of my student (talking through google meets) sounds quite odd. His voice is droning and echoes and soft.

### Steps to Reproduce

1. Audio starts coming out of my speakers
2. I open OBS and start recording
3. I hit stop and playback the video to find that the audio in (which is the output audio from the speakers) is having some echo and droning.

...

### Anything else we should know?

Perhaps i can send a video to make it clearer. If you listen to the audio of this you will hear the echo

https://user-images.githubusercontent.com/68906758/172749425-461a48d8-9889-4dad-bedd-99cf2adfa8d1.mp4

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
