### ISSUE TITLE
Bug: Obs not loading some plugins if not installed in windows drive (C:\)

### ISSUE THREAD

**Issue by WinGamingPT** [obsproject/obs-studio#6608]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/L5bUjqgbHUE0SE-e

### Expected Behavior

Plugins to all be loaded

### Current Behavior

One plugin that is working and loads in other obs' is not loading properly

### Steps to Reproduce

1.Install OBS outside C Drive
2. Install websocket plugin
3. Voillá, that plugin wont load and some others (after some searching of the forums of other plugins having the same issue)
...

**Comment by notr1ch** [comment]
If you install OBS in a non-standard location, you will need to make sure your plugins are also installed to the same non-standard location.
