### ISSUE TITLE
Pipewire capture uses incorrect stride for some resolutions

### ISSUE THREAD

**Issue by eaglesemanation** [obsproject/obs-studio#6609]
### Operating System Info

Other

### Other OS

Fedora 36

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/u6jDTFcrq14KQp5p

### Expected Behavior

Normal recording of a screen, like with my secondary 1080x1920 display:

https://user-images.githubusercontent.com/52473614/173119097-008779aa-91fe-4e44-a38b-e4ed1a66e559.mp4

### Current Behavior

Really strange artifacts appear when I try to record my 3440x1440 display:

https://user-images.githubusercontent.com/52473614/173119348-089e5e12-9398-4bc0-abe0-36b15df9037d.mp4

### Steps to Reproduce

1. Use PipeWire Screen capture in OBS
2. Select 3440x1440 display

This problem seems to be unique to OBS, because Kooha works fine while still using a portal for recording.

It also seems to be unique to Screen capture, because Window capture works fine:
![Screenshot from 2022-06-10 13-29-10](https://user-images.githubusercontent.com/52473614/173119942-99f79652-452d-4edb-9792-3517483883a6.png)

**Comment by kkartaltepe** [comment]
I guess this is another flavor of #4961 I think there is another issue open somewhere but I cannot find it now, so this seems fine.

**Comment by kkartaltepe** [comment]
I think someone mentioned this was replicable on mesa drivers with 720p capture as well.

**Comment by eaglesemanation** [comment]
Remembered additional info: I'm pretty sure that started to happen after I updated from Fedora 35 to Fedora 36. Previously it worked fine.

**Comment by kkartaltepe** [comment]
https://gitlab.gnome.org/GNOME/mutter/-/issues/1913 this was the bug i was thinking of.

Can you please try building against master and letting me know if you have the same experience? `Cannot create EGLImage` is reported and the capture fails?

If you do then this is technically fixed and we are waiting for compositors to fixup their format negotiation. Right now I think the only successfully tested xdg-desktop-portal implementation is the one for wlroots on master that negotiates back to shared memory when the dmabuf cannot be imported due to issues like this.

**Comment by eaglesemanation** [comment]
Building obs-studio from master results in the same bug, but I don't see `Cannot create EGLImage` in both new and old logs.
Here is the new log: https://obsproject.com/logs/BeVv8Q-jAXLC9GpT
And here is new recording just to be sure I'm not doing something dumb:

https://user-images.githubusercontent.com/52473614/173710793-bfff95ba-f7af-4654-8b43-a4d4309b0b2b.mp4

**Comment by kkartaltepe** [comment]
Thanks for taking the time to build it. Looks like we need to find a dev to replicate and peek at the strides to make sure we are passing the right data around. At least a cursory look it seems fine to me and we correctly passing in the data from the compositor to the driver.

**Comment by GeorgesStavracas** [comment]
I think I can see what's the problem on Mutter / GNOME Shell side, I'll try and come up with a solution throughout this week

**Comment by GeorgesStavracas** [comment]
This has been fixed by https://gitlab.gnome.org/GNOME/mutter/-/commit/ab3931f which is queued for backporting to GNOME 42.
