### ISSUE TITLE
OBS doesn't work with Webex on Macbook Pro M1

### ISSUE THREAD

**Issue by HerrAlbers** [obsproject/obs-studio#6611]
### Operating System Info

macOS 12

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/E-4LyF3ev5qNrkdH

### Expected Behavior

Webex would accept OBS virtual Cam as a cam!

### Current Behavior

When selecting OBS as a camera, the Preview Window remains gray,
![Ohne Titel](https://user-images.githubusercontent.com/52204452/173198082-01eeedfa-6fd7-40a9-b371-8ba3e64cb95c.png)
![macobswebex](https://user-images.githubusercontent.com/52204452/173198100-60dbcfff-8de6-43a2-80d6-eec9b4654e84.jpg)
 

### Steps to Reproduce

1. start OBS
2.start virtual Camera
3. start Webex and select Jobs as camera
...

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
