### ISSUE TITLE
My OBS(M1,macOS12) was unstable after "e8b2b20"

### ISSUE THREAD

**Issue by hakihaki95** [obsproject/obs-studio#6615]
### Operating System Info

macOS 12

### OBS Studio Version

Git

### OBS Studio Log URL

https://obsproject.com/logs/Jrfi090zGQ1T27gz

### OBS Studio Crash Log URL

https://github.com/obsproject/obs-studio/tree/e8b2b2092bd3eaee85f7c919af7e52f317356dfc

### Expected Behavior

Push "Start Streaming" then, Start with Youtube RTMPS Setting

### Current Behavior

OBS Studio is gone.
But, Youtube RTMP, HLS was working, but, unstable.

### Steps to Reproduce

1. Recording worked very well.
2. But, I pushed "Start Streaming" it is gone.
3. I checked various git version.
4. And I found this e8b2b20 conflicted with my M1, and next to last version also not working.
5. But, 5e696cd is working very well

**Comment by tt2468** [comment]
This is a known issue which should be fixed soon. Pinging @jp9000 since I'm not able to fix it any time soon via my PR due to personal events.

**Comment by gxalpha** [comment]
Fixed by 7ba9db37446b3c0acf2449dd26e210235f7666af
