### ISSUE TITLE
Activating Hotkeys Becomes Unpredictable Using Simulated Keypresses While OBS Doesn't Have Focus

### ISSUE THREAD

**Issue by Yowlen** [obsproject/obs-studio#6624]
### Operating System Info

Other

### Other OS

Xubuntu 20.04

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/_YxdUp_76eUN44-q

### Expected Behavior

Hotkeys work with software-based keypress tools like `xdotool` without any issues.

### Current Behavior

Hotkeys work as expected when OBS has focus, but for the two options that allow hotkeys to work out of focus, detection is sporadic.

### Steps to Reproduce

1. Set a hotkey in Settings -> Hotkeys. (I personally tested this with making a toggle to mute the Mic/Aux audio source.)
2. Verify that Settings -> Advanced -> "Hotkey Focus Behavior" is set to "Never disable hotkeys"
3. Apply changes if needed, then exit out of Settings.
4. Try various methods of activating the hotkey with `xdotool key <hotkey>` with OBS both in and out of focus.

Three methods I've tried are:
- Running `xdotool key <hotkey>` in the terminal (only testable for out of focus)
- Running `sleep 1 && xdotool key <hotkey>` in the terminal (lets me test with OBS both in and out of focus)
- Adding a custom launcher to a panel with the command `xdotool key <hotkey>` (also lets me test with OBS both in and out of focus)

### Anything else we should know?

Discord is able to detect the keys just fine every time. For uncommon keys such as F13, Discord displays the keymap ID instead of a proper label. So, because I use `xmodmap -e 'keycode 197=F13'` to assign F13 to the keymap, Discord shows `UNK197` as the key binding, probably for "Unknown Key 197". I mention this only as an example of an app working with `xdotool` in all cases to indicate it's possible and potentially give any extra info that might be relevant.

I've noticed that it actually changes its effectiveness when granting and re-losing focus, as well as changing between the various hotkey options and even restarting OBS itself. Beyond that, each of the three methods to activate the hotkey can work or not work independently of the others for any given attempt.

Lastly, all methods work fine when OBS has focus. It's just when OBS doesn't have focus that things become unpredictable.

Edit: I had errored in my testing, and after further testing, I found the real issue, so I've updated this to reflect that.

**Comment by kkartaltepe** [comment]
Please test and provide a log without any third party addons

**Comment by Yowlen** [comment]
I'm having trouble reproducing it. I'm guessing an update somewhere ended up reducing its occurrence. I don't know what update could've done it, however. Seems it might've been a system update that "fixed" it because I don't recall updating anything OBS-related, including addons, within the relevant timeframe. Given that's what I can gather, I'm left to conclude that the rare remaining issues are likely to be related to system bugs, as well. Sorry for the erroneous bug report.
