### ISSUE TITLE
Wiki build directions missing dependencies for Red Hat system builds

### ISSUE THREAD

**Issue by kharyam** [obsproject/obs-studio#6625]
### Operating System Info

Other

### Other OS

Fedora 36

### OBS Studio Version

27.2.4

### OBS Studio Log URL

N/A

### OBS Studio Crash Log URL

N/A

### Expected Behavior

The build directions in the wiki (https://github.com/obsproject/obs-studio/wiki/build-instructions-for-linux#red-hat-based)  lists dependencies that are pre-requisites for the build on Red Hat based systems. Expect these to be sufficient to build. 

### Current Behavior

Build fails due to missing development packages. The following packages are missing:

- alsa-lib-devel
- libdrm-devel
- vlc-devel
- pciutils-devel
- qt5-qtbase-private-devel

### Steps to Reproduce

Follow the build directions as is for Red Hat-based systems on the wiki (https://github.com/obsproject/obs-studio/wiki/build-instructions-for-linux#red-hat-based) and it will fail (at least for Fedora 36 where I tested). Install the additional packages and the build succeeds:

`yum install -y alsa-lib-devel libdrm-devel vlc-devel pciutils-devel qt5-qtbase-private-devel`

**Comment by tt2468** [comment]
If there are dependencies missing from the wiki then you can edit the wiki page to add them to the dependencies list.

**Comment by kharyam** [comment]
Thank you, updated.

**Comment by norihiro** [comment]
Please note that there is another section for Fedora.

- Red Hat: https://github.com/obsproject/obs-studio/wiki/build-instructions-for-linux#red-hat-based
- Fedora: https://github.com/obsproject/obs-studio/wiki/build-instructions-for-linux#fedora

**Comment by kharyam** [comment]
Thank you! I will update
