### ISSUE TITLE
No red dot on Win 10 taskbar icon when recording if taskbar uses small buttons

### ISSUE THREAD

**Issue by yhdanid** [obsproject/obs-studio#6626]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

NA

### Expected Behavior

On Win 10, when using small buttons on taskbar, OBS should show the red dot recording indicator as it does when the Windows taskbar is not using small buttons.

### Current Behavior

No red dot is shown on the taskbar icon to show a recording is in progress. This of course leaves one to doubt/not know if the recording is currently actually happening or not.

### Steps to Reproduce

1. Right click on Win's 10 taskbar
2. Click "Taskbar settings"
3. Toggle "Use small task bar buttons" to On
4. Start recording in OBS

Result:
No indication/red dot is shown in the taskbar while recording is in progress.

**Comment by WizardCM** [comment]
This is expected behaviour on the Windows side. It's tied to the "Show badges on taskbar buttons" setting, which requires "Show small taskbar buttons" to be disabled.
