### ISSUE TITLE
Icon mismatch between linux mint and obs

### ISSUE THREAD

**Issue by fuadnse03** [obsproject/obs-studio#6637]
### Operating System Info

Other

### Other OS

Linux Mint 20.3

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/T2wNS0M1ZxcfvXGz

### Expected Behavior

![malfunction](https://user-images.githubusercontent.com/62174144/174891426-69ae8481-3848-4003-a56a-523bb5848a1e.png)
I am using the Mint-Y-Dark-Blue icon on linux mint but obs is showing the Mint-Y icon(default).I expected obs to show me the icons I am using on my OS which is Mint-Y-Dark-Blue.

### Current Behavior

I am using the Mint-Y-Dark-Blue icon on linux mint but obs is showing the Mint-Y icon(default)
![Screenshot from 2022-06-22 03-08-27](https://user-images.githubusercontent.com/62174144/174897786-cf9fa573-127c-4511-bcd4-9084017f0bc9.png)

### Steps to Reproduce

1.Open Obs and go to Files>Settings>Output>Recording path>Browse
2.You will see Mint Y icons
3.
...

**Comment by RytoEX** [comment]
We invoke Qt's QFileDialog via `getExistingDirectory`:
https://github.com/obsproject/obs-studio/blob/0d0b65e8c82d29e4b7068153c86b1745ac7adcfb/UI/qt-wrappers.cpp#L348-L350

This sounds like a Qt bug to me.

**Comment by GeorgesStavracas** [comment]
Not even Qt, but xdg-desktop-portal-gtk or GTK3 itself
