### ISSUE TITLE
Text that is within the “About” window does not adhere to the size that KDE Plasma mandates.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [obsproject/obs-studio#6641]
### Operating System Info

Other

### Other OS

http://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Server/x86_64/iso/Fedora-Server-netinst-x86_64-Rawhide-20220618.n.0.iso 1653307616.0001 5.19.0-0.rc2.20220616git30306f6194ca.23.fc37 #1 SMP PREEMPT_DYNAMIC 2022-06-16T14:03:31+0000

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/jvX9j1yp6voShrYk

### Expected Behavior

I have configured KDE Plasma to mandate identical size of text for every type. Consequently, the large text that ![this](https://user-images.githubusercontent.com/42837531/175048259-ee940ae3-d9ae-484e-8ad4-aedff956796c.png) depicts demonstrates that Open Broadcaster Software Studio does not utilize the presets that are possible to configure.

### Current Behavior

![This](https://user-images.githubusercontent.com/42837531/175048259-ee940ae3-d9ae-484e-8ad4-aedff956796c.png) demonstrates that the size of some of the text that is presented is not adherent to what KDE Plasma mandates.

### Steps to Reproduce

1. Invoke "`kcmshell5 kcm_fonts`" to invoke what ![this](https://user-images.githubusercontent.com/42837531/175045632-8be4eb04-8224-4921-95a2-845fe3551232.png) depicts.
2. Configure the consequently apparent window to anything, because Open Broadcaster Software Studio does not adhere to any configuration of this.

**Comment by mihawk90** [comment]
I assume you are referring to the "OBS Studio" title? That is a heading and as you can see that is not configurable in KDE (or anywhere else for that matter).

It's not a matter of a predefined font-size.
