### ISSUE TITLE
Iconography is presented within the configurative window, although I have configured KDE Plasma to mandate disallowment of presentation of iconography.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [obsproject/obs-studio#6642]
### Operating System Info

Other

### Other OS

http://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Server/x86_64/iso/Fedora-Server-netinst-x86_64-Rawhide-20220618.n.0.iso 1653307616.0001 5.19.0-0.rc2.20220616git30306f6194ca.23.fc37 #1 SMP PREEMPT_DYNAMIC 2022-06-16T14:03:31+0000

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/jvX9j1yp6voShrYk

### Expected Behavior

No iconography should be presented.

### Current Behavior

![This](https://user-images.githubusercontent.com/42837531/174446495-ad56272d-cebf-4bcf-95f7-f4cb355be2c5.png) demonstrates that iconography is presented despite my disallowment of it via what "`kcmshell5 kcm_style`" invokes:

### Steps to Reproduce

1. Invoke "`kcmshell5 kcm_style`" configure the consequently apparent window to what ![this](https://user-images.githubusercontent.com/42837531/174447430-71c06416-2c05-4eb5-b696-d518660eb13b.png) depicts.

**Comment by kkartaltepe** [comment]
Please file a bug against Qt if you think this should work.
