### ISSUE TITLE
Iconography that is presented does not adhere to the size that KDE Plasma mandates.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [obsproject/obs-studio#6643]
### Operating System Info

Other

### Other OS

http://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Server/x86_64/iso/Fedora-Server-netinst-x86_64-Rawhide-20220618.n.0.iso 1653307616.0001 5.19.0-0.rc2.20220616git30306f6194ca.23.fc37 #1 SMP PREEMPT_DYNAMIC 2022-06-16T14:03:31+0000

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/jvX9j1yp6voShrYk

### Expected Behavior

The iconography should be presented at the size that I have configured. I have configured that size to be 16-by-16 pixels.

### Current Behavior

![This](https://user-images.githubusercontent.com/42837531/175047684-5b82c3e3-f62c-46e8-b7dc-65f95231a882.png) demonstrates that the size of the iconography is too large to be adherent to what KDE Plasma mandates.

### Steps to Reproduce

1. Invoke "`kcmshell5 kcm_style`" to invoke what ![this](https://user-images.githubusercontent.com/42837531/175047476-7819637e-280d-45a3-b125-bca3056737ff.png) depicts.
2. Configure the consequently apparent window to anything, because Open Broadcaster Software Studio does not adhere to any configuration of this.

**Comment by kkartaltepe** [comment]
Please file a bug against Qt if you think this should work.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@kkartaltepe, it does in literally all other Qt software that I have utilised. Are you certain that your implementation is not the fault?

**Comment by kkartaltepe** [comment]
Provide response from Qt developers that this is intended to work for all Qt applications. Another contributor has suggested that KDE platform integration is separate from Qt, in which case this is working as intended as we dont intend to integrate into various theming platform extensions.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@kkartaltepe, do you know where is best to contact them?
