### ISSUE TITLE
Application was unable to start correctly 0xc000007b

### ISSUE THREAD

**Issue by h4mmad** [obsproject/obs-studio#6648]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

-

### Expected Behavior

I expected OBS to work properly

### Current Behavior

Shows an error: application not able to start correctly 0xc000007b, 
I also installed Microsoft Visual C++

### Steps to Reproduce

Just open OBS

**Comment by notr1ch** [comment]
Please use the forums or Discord for support.
