### ISSUE TITLE
Audio mixer : Hide Media source entry when audio still play

### ISSUE THREAD

**Issue by mvji** [obsproject/obs-studio#6670]
### Operating System Info

macOS 11

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/1foqr438zlNQkZ6r

### Expected Behavior

Audio mixer entry for hidden "media source" with audio playing stay visible.

### Current Behavior

When hiding a media source with audio (and when "restart playback when source become active" unchecked), audio continue to play, but audio mixer entry disappear.

### Steps to Reproduce

1. Import files with Audio using Media source
2. Uncheck "Restart playback when sources become visble"
3. Hide the layer
4. Audio mixer entry disappear, but audio still play

**Comment by tuduweb** [comment]
When Uncheck "Restart playback when sources become visible", the media will not stop playing(load and sent to output buf) in backend:
https://github.com/obsproject/obs-studio/blob/f6f6690ccfeb4b78eec82d4ff853cb6db7138860/plugins/obs-ffmpeg/obs-ffmpeg-source.c#L672-L684

and sent to audio-monitoring system in `coreaudio-output.c`, `on_audio_playback`:
but in this function, not like in other backends(windows/linux), there are missing some judgement about source activate:

https://github.com/obsproject/obs-studio/blob/f6f6690ccfeb4b78eec82d4ff853cb6db7138860/libobs/audio-monitoring/pulse/pulseaudio-output.c#L230-L231

https://github.com/obsproject/obs-studio/blob/f6f6690ccfeb4b78eec82d4ff853cb6db7138860/libobs/audio-monitoring/win32/wasapi-output.c#L316-L318

So, I think we need to add this judgement in `coreaudio-output` like other backends.

**Comment by WizardCM** [comment]
Duplicate of #4181
