### ISSUE TITLE
Radeon Super Resolution causes issues with OBS's ability to properly hook/causes choppy recording

### ISSUE THREAD

**Issue by Slashvenom1** [obsproject/obs-studio#6697]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/UiMCnz463rS_J8LL

### Expected Behavior

OBS should be able to game capture a game enhanced by Radeon Super Resolution without issues.

### Current Behavior

OBS seems to be having an issue hooking or something when RSR is enabled, the recording seems to de-sync and become choppy after high amounts of movement. This happens in all games as far as I can tell. Though, it's less noticeable in non-FPS titles.

### Steps to Reproduce

1. Enable 'Radeon Super Resolution' in AMD Adrenaline software
2. Enter a FPS title and begin recording using the AMD Advanced Media Framework encoder 
3. Either by Alt-tabbing or high amounts of movement in game you should be able to cause the recording to go slightly 'out of sync' with the game, causing a choppy recording
4. OBS will not report a frame loss or increased encoding time
5. OBS will produce a choppy/not smooth recording
...

### Anything else we should know?

**_Here's where the bulk of the information will be posted, the Studio Log submitted with the report is not correct. 2 correct Logs attached in this section._**

Operating System
	Windows 10 Pro 64-bit
CPU
	Intel Core i7 9700K @ 3.60GHz	42 °C
	Coffee Lake 14nm Technology
RAM
	64.0GB Dual-Channel DDR4 (16-18-18-38)
Motherboard
	Micro-Star International Co. Ltd. MPG Z390M GAMING EDGE AC (MS-7B50) (U3E1)	36 °C
Graphics
	BenQ EX2780Q (2560x1440@144Hz)
	XF251Q (1920x1080@59Hz)
	Intel UHD Graphics 630 (MSI)
	8176MB ATI AMD Radeon RX 5700 XT (MSI)
	CrossFire Disabled
Storage
	931GB Western Digital WDC WDS100T2B0C-00PXH0 (Unknown (SSD))
	465GB Seagate BarraCuda 120 SSD ZA500CM10003 (SATA (SSD))	24 °C
	931GB Intel Raid 1 Volume (SATA )
Optical Drives
	No optical disk drives detected
Audio
	Realtek High Definition Audio
	
	
OBS Version: 27.2.4
AMD driver version: 22.5.2

I've been having this issue where OBS will produce choppy/not smooth recordings if Radeon Super Resolution is enabled. It seems that OBS is competing to hook or something with the software. After an unspecified amount of time (in most cases immediately upon starting recording/replay buffer) the recording will become choppy to the point where it looks as if it's only capturing 2/3 frames while reporting no frame loss or encoder overload.

I actually have many. many clips of this behavior however I did record a fresh example for the reporting process.

Video 1, RSR enabled: https://youtu.be/Yfz6IvKLTr8
Log for Video 1: [Video 1 with RSR enabled.txt](https://github.com/obsproject/obs-studio/files/9069158/Video.1.with.RSR.enabled.txt)

Video 2, RSR disabled: https://youtu.be/vlMzUC3_SR0
Log for Video 2: [Video 2 with RSR disabled.txt](https://github.com/obsproject/obs-studio/files/9069179/Video.2.with.RSR.disabled.txt)

(**EDIT:** In this entire report I use the word 'choppy' a lot, realistically I feel like I should make a distinction here where it's not like other 'choppy' reports, it's more like 'not smooth'. As in where other people complain of 'choppy' behavior it's encoder overload or dropped frames etc, but in my case the recording does look like it's genuinely capturing 60 frames, just the 'frametime' for lack of a better term is not even. Causing a 'not-smooth' recording. It's not that it's 'choppy' per se, but that the frames are not being displayed in a smooth manner. You might get a better idea of what I'm saying when watching the videos, thought I'd clear that up here though as re-reading it is kind of hard to tell what I'm talking about when I say 'choppy'.)

In Video 1 you can see when I'm flicking around with high amounts of movement the targets in the range become choppy. The whole thing is choppy but it's easiest to tell looking at the targets. The Grid on the floor is also a good marker and you can see when it becomes choppy. Note that the entire video isn't choppy the whole time, nor is it unwatchable, but you can definitely see it if you're looking for it. More importantly (to myself at least), when these videos are posted on sites such as Reddit or others and they're displayed next to clips that are not "moderately choppy", it becomes an issue of presentation on my end and anyone else that uses RSR + OBS.

In Video 2 (though short + excuse my language) you can see that the choppiness is gone. If you look at the targets and compare them to Video 1, you can see that the targets are actually 'trackable' with your eyes. If you still can't see it, slow down both videos to 0.25 and either put them side by side or just watch one after the other. Watch 0:07-0:10s on Video 1 and compare to 0:24-0:27 on Video 2. It almost looks like the frames in Video 1 are kind of 'clumping' together while the frames in Video 2 are much more evenly spaced.

If you still can't see it then you'll just have to trust that I have over 70 2-3 minute clips with RSR on that display this "choppy" behavior and another 50 2-3 minute clips that do not display this behavior. The only difference is whether RSR is On or Off.

Turning RSR off resolves the issue, however it's an incredibly nice feature for getting high FPS while running low resolution with minimal quality loss on high-pixel count displays. It would be nice to either have a work-around or a setting for compatibility. 

Though with all that said I'm not sure whether it's going to be better for OBS or AMD/Radeon to handle it, the only real reason I'm reporting this to OBS is because it feels like there's a greater potential to be helped or at least heard on here compared to just submitting a bug report to AMD considering they don't exactly give you much ability to actually show what your issue is.

Thanks to anyone who took the time to read this, I'll be keeping this page open on my PC for any questions until resolution or until it is clear that nothing can/will happen for this issue. Until then I'll run with RSR off if I am planning on capturing gameplay as a workaround. 

_Let me know as well if this isn't the correct spot for this report and I'll take my issue wherever it needs to go, genuinely don't know my best course of action with this issue._

**Comment by Fenrirthviti** [comment]
This appears to be a bug on AMD's side, and would be best reported to them.
