### ISSUE TITLE
Virtual webcam broken on Wayland

### ISSUE THREAD

**Issue by ObsidianChickenz** [obsproject/obs-studio#6701]
### Operating System Info

Other

### Other OS

NixOS Unstable

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/Pm4UG1Lq3CyYRYz5

### Expected Behavior

The virtual webcam turns on.

### Current Behavior

OBS becomes unresponsive. The preview screen still updates, but I cannot click on any menus whatsoever.

### Steps to Reproduce

1. Install and launch the Hyprland compositor and OBS Studio.
2. Attempt to turn on virtual webcam.

### Anything else we should know?

I am using the wlrobs plugin, but I have tested this without the plugin installed, and the problem still exists. I do not have xdg-desktop-portal-wlr installed and working, as Hyprland conflicts with it.

**Comment by kkartaltepe** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

Though obs should never deadlock your system appears to be fairly broken so please try to use support for debugging your system.
