### ISSUE TITLE
Control audio via OBS don't work

### ISSUE THREAD

**Issue by Timtaran** [obsproject/obs-studio#6708]
### Operating System Info

Other

### Other OS

Windows 7 x64

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/QUmT_kfyamOGOjwI

### Expected Behavior

Control audio will work lol

### Current Behavior

Control audio don't work

### Steps to Reproduce

1. Enable `Control Audio via OBS` at `Browser` settings

**Comment by WizardCM** [comment]
This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels below, and if it's determined that this is indeed a bug, then we will re-open this issue.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

**Comment by Timtaran** [comment]
I send video of this bug at discord server and got ban WTF

**Comment by Fenrirthviti** [comment]
Apologies for the accidental ban on Discord, we have a blacklist on dropmefiles as it's riddled with malware. I've revoked the ban, but avoid using/linking that file sharing site or you may get hit by our moderation bots again.

**Comment by Timtaran** [comment]
> Apologies for the accidental ban on Discord, we have a blacklist on dropmefiles as it's riddled with malware. I've revoked the ban, but avoid using/linking that file sharing site or you may get hit by our moderation bots again.

thanks
