### ISSUE TITLE
Window capture switches windows for a microsecond when switching workspaces [Tiling Window Manager]

### ISSUE THREAD

**Issue by Ahptt** [obsproject/obs-studio#6710]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/ltJoDU6LdyO_ExaD

### Expected Behavior

I was expecting OBS to simply preview my Game and never switch what it was capturing, even when switching workspaces. In this case, the game I'm playing is Minecraft.

### Current Behavior

When I select the source in OBS through window capture and switch to the game, for a very brief moment, obs captures another window. This also occurs after switching to the game, while moving to other workspaces and back. I have included a small clip showing the issue.

This issue occurs both when my windows are full screen, and when the windows are tiled (not fullscreen).

### Steps to Reproduce

1. Select the window capture and select the game/window
2. Switch workspaces while capturing (occurs when streaming and recording)
...

### Anything else we should know?

I am running Arch Linux with a dynamic tiling window mananger, Xmonad with Xmobar to be more specific. I believe this bug also is present in a floating window manager like KDE Plasma, but it's been a while since I've used one and I can't confirm.

Normally, something like this wouldn't bug me. However, I recently streamed and this occurred, showing private chats I was having with someone, which is why I am reporting it. Many thanks for the diligent efforts in making OBS pure gold!

https://user-images.githubusercontent.com/107279537/178152229-286318e3-b5f6-49fc-9264-b3da41011708.mov

**Comment by kkartaltepe** [comment]
Please try to replicate on current git master, I also cannot replicate this on i3 on 27.2.4.

**Comment by Ahptt** [comment]
@kkartaltepe I'm very new to GitHub. Would you mind educating me on how to do that? Thanks!

**Comment by RytoEX** [comment]
Please retest in OBS Studio 29.0.0 or newer.

**Comment by Ahptt** [comment]
I hope someone else can test this. I've moved on from Arch to Void Linux with the dwm window manager, and I no longer have this problem.

**Comment by kkartaltepe** [comment]
Ill close this then, we have rewritten a fair portion of this code since 27. If anyone can replicate this im happy to reopen it.
