### ISSUE TITLE
OBS Crashes when captured window size is set to 0x0

### ISSUE THREAD

**Issue by Alphatism** [obsproject/obs-studio#6711]
### Operating System Info

Windows 11

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/kQoPjwbFpFX8RQss

### Expected Behavior

The intended behavior is to show nothing and not crash. 

### Current Behavior

OBS crashes with no resulting Crash File when you are capturing a window that then is set to the size of 0 width and/or 0 height. 

### Steps to Reproduce

1. Capture a window via Window Capture
2. Use capture method "Windows 10 (1903 and up)"
3. Set the window size to 0 width and/or height programmatically. 

Sample code to do this in Java

```JFrame frame = new JFrame
frame.setTitle("test");
frame.setSize(100,100);
new Thread(() -> {
    Thread.sleep(15000); //Wait 15 seconds
    frame.setSize(0,0);
}).start();
```

**Comment by RytoEX** [comment]
Please retest in OBS Studio 29.0.0 or newer.

**Comment by RytoEX** [comment]
Just as an aside, the code snippet does not compile. Even after getting this code into a compilable Java application, I cannot reproduce this crash in OBS Studio 29.0.0 on Windows 10.
