### ISSUE TITLE
OBS Causing System Freeze And Or Crashing

### ISSUE THREAD

**Issue by Duckos-Mods** [obsproject/obs-studio#6728]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/nruWV4DlTlcvkKL3

### Expected Behavior

OBS To Open And Record / Stream Norrmaly

### Current Behavior

If I Open OBS My System Freezes Some Times It Comes Back And OBS Is Just A Black Screen So I Restart OBS And It Works Other Times It Causes A Black Screen Then My Monitor Stops Getting A Display Out Put Then All Peripherals Turn Off And I Have To Hold My Power Button Down To Fix It Or It Black Screens But Everything Is Still Getting Power 

### Steps to Reproduce

1.Open OBS

### Anything else we should know?

I Have An AMD CPU / GPU I think this could be my  GPU Clashing With OBS But I Dont Know

**Comment by RytoEX** [comment]
This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels ([Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum)), and if it's determined that this is indeed a bug, then we will re-open this issue.
