### ISSUE TITLE
Misleading Replay Buffer error message for nonexistent path

### ISSUE THREAD

**Issue by treylav** [obsproject/obs-studio#6731]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://gist.github.com/treylav/04412ccf2f2c73ba6e29b3cfeda50df6

### Expected Behavior

When you specify an incorrect path in Settings → Output → Recording path (for example, to a nonexistent folder), attempts to start recording and start the replay buffer **same message** must appear: _"The configured Recording Path could not opened. Please, check your Recording Path under Setting → Output → Recording."_

### Current Behavior

When you specify an incorrect path in Settings → Output → Recording path (for example, to a nonexistent folder), attempts to start recording and start the replay buffer cause different error messages.

When Start Recording is activated, an error message appears with a direct indication of the problem: _"The configured Recording Path could not opened. Please, check your Recording Path under Setting → Output → Recording."_

When the Replay Buffer is activated, a misleading message appears: "_There is not sufficient disk space to continue recording."_

### Steps to Reproduce

1. Specify an incorrect path (for example, to a non-existent folder) in Settings → Output → Recording path.
2. Try to start recording.
3. Note the error message: it correctly indicates the problem.
4. Try to start replay buffer.
5. Note that the error message is different and indicates that there is not enough free disk space.

### Anything else we should know?

I'm not sure if the problem has not been reported before, but, unfortunately, the issue tracker of the project is quite large and I didn't find a similar report.

**Comment by derrod** [comment]
Should be fixed with #6744 being merged.
