### ISSUE TITLE
Segmentation fault after new pipewire 0.3.55 version

### ISSUE THREAD

**Issue by hoergen** [obsproject/obs-studio#6738]
### Operating System Info

Ubuntu 21.10

### Other OS

Kubuntu  21.10 impish

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/can't provide uase isnt starting

### Expected Behavior

obs-studio starting

### Current Behavior

It's crashing with segmentation fault

### Steps to Reproduce

1. start
2. start
3. start
...

### Anything else we should know?

The log  messages with obs >obs.log   (contains german error messages like Speicherzugriffsfehler = segmentation fault)

[obs.log](https://github.com/obsproject/obs-studio/files/9120925/obs.log)

**Comment by hoergen** [comment]
I should mention that every other software I use with pipewire works fine.

**Comment by tytan652** [comment]
Ubuntu 21.10 officially provide PipeWire 0.3.32, so the PPA is build against this version of PipeWire.

This scenario where PipeWire is upgraded may require you to build OBS from source or to use the Flatpak.

**Comment by hoergen** [comment]
Oh ok that's good info. I tried the flatpak. All  my settings are "gone", but obs is starting and think working. With flatpak a lot additinal KDE software was installed, so maybe it's not pipewire maybe as well something with kde. But can't figure out exactly what.

But thank you very much :sunflower:    I close this issue.

**Comment by tytan652** [comment]
Flatpak use another location for storing application settings.
