### ISSUE TITLE
Build no longer working on Arch Linux (Manjaro)

### ISSUE THREAD

**Issue by julian-bieringer** [obsproject/obs-studio#6754]
### Operating System Info

Other

### Other OS

Manjaro

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.2.0.521 was the last working build

### OBS Studio Log URL

Not the application but the build crashed

### Expected Behavior

Build should work as before

### Current Behavior

Build crashes

```bash
[ 38%] Built target decklink
make: *** [Makefile:156: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

### Steps to Reproduce

```
pamac build obs-studio-git
```

**Comment by RytoEX** [comment]
We don't maintain the AUR package. You'll have to report this to the package maintainer.
