### ISSUE TITLE
In-game FPS drops when OBS is open, even when not recording

### ISSUE THREAD

**Issue by marsh1832** [obsproject/obs-studio#6763]
### Operating System Info

Windows 11

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/2EuDng97rbjIgtH1

### Expected Behavior

Since there are no missed or dropped frames, and neither the CPU or GPU are anywhere maxed out, having OBS open should not have any impact on FPS, especially if it's not even recording.

### Current Behavior

FPS tanks at random times, but seems to take about 30 minutes of recording to start, although it can be more or less. Even after stopping recording, FPS is still tanked, until you close OBS which fixes the FPS. Sometimes it will go away if you just wait a few minutes. FPS goes from perfect 60 to 40-60 fps.

According to Factorio's OSD, UPS (cpu) is fine at 60, and FPS (gpu) is what is lagging. Looking at the frame time display, the lagging element is Flip (on), which is vsync. For some reason vsync seems to break after a while of having OBS open/recording. This can be "fixed" by disabling vsync, but it makes Factorio look like garbage, either terrible tearing, or stutter that's even worse than the FPS drops.

### Steps to Reproduce

1. Run Factorio at 4k
2. Begin recording at 4k
3. After some time (30-90 minutes) FPS will start to fall to around 40 with no additional load or clock speed changes on GPU or CPU
4. Stop recording, FPS remains bad
5. Close OBS, FPS goes back to 60
...

### Anything else we should know?

I've tried every combination of every random setting i've read about, including GPU scheduler, game mode, DVR, browser acceleration, 59.94 vs 60.00 vs 120, nvenc vs cpu, run as admin, gsync, limit capture rate, mp4/mkv, source capture type, ect. 

I've also closely monitored the heat and clock speeds of both the CPU and GPU to make sure neither are clocking down. They don't seem to be, and I've even forced them to run at full speed with no power savings to make sure that's not what's happening (since it takes a period of time for the slowdown to begin.) Neither device is particularly hot as this is a water cooled computer, both are running stock speeds, and Factorio is not a resource intensive game. GPU is about 40c and CPU is about 50c during recordings. 10900k and a 3080ti at 4K so power is not a problem.

I get the feeling this is some kind of vsync conflict with win 11. Games run great if OBS is closed OR vsync is disabled, but Factorio in particular looks really bad without vsync, lots of tearing and stutters.

I also have a random stuttering issue that I have been unable to solve, it may be related, but it has persisted since the computer that this one replaced, a win 7 computer, 7700k, 1080. The random stuttering is unexplained single frame drops with OBS reporting no missed or dropped frames. It never actually harms the FPS, as the game seems fine, I only find out about the stutters when I review the recordings. Some of the settings you may raise an eyebrow to (such as 59.94 fps recording) is to combat these random stutters the best I can. I've kind of learned to live with it since it seems unfixable.

But what's happening above is severe FPS drops to 40 fps and below that I have never experienced in Factorio with the exception of running OBS on win 11.

**Comment by msmafra** [comment]
I am having this problem on Linux for a while. With OBS just opened, not recording nor streaming, FPS in games drop.
Fedora Workstation 36
Intel Core i7-10750H
16GB DDR4/2x8 GiB 2667 MT/s
GeForce RTX 2060 Mobile 6GB currently with  NVIDIA 515.57 drivers, but previous versions also same behavior.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
