### ISSUE TITLE
Failed to find locale/*.ini

### ISSUE THREAD

**Issue by justanameok** [obsproject/obs-studio#6780]
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

Git

### OBS Studio Log URL

sorry 

### Expected Behavior

start obs

### Current Behavior

Failed to find locale/*.ini

### Steps to Reproduce

1.start
2.
3.
...

**Comment by notr1ch** [comment]
Sounds like you are launching OBS from a different working directory or didn't follow the build instructions.

https://github.com/obsproject/obs-studio/wiki/build-instructions-for-linux

> NOTE: When building OBS with LINUX_PORTABLE disabled, OBS expects GNU-based install paths (e.g. /usr/local/[bin,lib,share]) and is built for a single architecture only. To create separate builds for 32-bit and 64-bit architectures, always enable portable builds.

Closing this as it isn't an issue with OBS, but with your environment.
