### ISSUE TITLE
OBS Crash

### ISSUE THREAD

**Issue by NyaniQwerty** [obsproject/obs-studio#6790]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/AJrM4WeZfvcz3yB_

### OBS Studio Crash Log URL

https://obsproject.com/logs/xdQhYzJPJ9NjLyjk

### Expected Behavior

Working normally

### Current Behavior

It crash and it won't let me to use the software

### Steps to Reproduce

1. Open OBS
2. Crash (with crash log)
3. Click OK, then exit

**Comment by RytoEX** [comment]
This appears to be related to the win-capture-audio plugin. Please reach out to the plugin author for support.

**Comment by nyanonimus** [comment]
After the newest update, it seems that OBS has finally decided to maintain this plugin and improve it on their own even though it's still in beta, but that's a great news!

**Comment by RytoEX** [comment]
> After the newest update, it seems that OBS has finally decided to maintain this plugin and improve it on their own even though it's still in beta, but that's a great news!

We have our own implementation that is not related to the third-party plugin.
