### ISSUE TITLE
amf-texture: Inconsistent preset autodetect

### ISSUE THREAD

**Issue by flaeri** [obsproject/obs-studio#6793]
### Operating System Info

Windows 11

### OBS Studio Version

Git

### OBS Studio Version (Other)

git e3f416f3f

### OBS Studio Log URL

https://obsproject.com/logs/w3WGvRvbFfoRVuSA

### Expected Behavior

I would expect simple and advanced mode to behave the same way in terms of automatically determining preset for the new texture based amd hw encoder.

### Current Behavior

With simple/default settings (even with a new profile), the behavior is very different.

Simple mode:
HQ (quality) is automatically chosen (you dont get to choose). Logs confirm HQ (quality).

Advanced mode:
By default the preset is set to "quality" (HQ). When recording, the log output confirms "speed" preset is chosen on my GPU.

I suspect on my low power GPU, speed is the correct preset. I suspect that simple mode does not correctly (or at all) use the code path that will adjust the preset

### Steps to Reproduce

1. Have hardware low end enough that your preset gets set to lower than Quality (HQ). In my case that is a 4500U APU
2. Make a clean/new profile. Skip auto config wizard
3. Ensure video is set to 1080p60
4. Set simple mode to AMD HW h264, indistinguishable. Start recording.
5. Confirm log output (should be "hq")
6. Switch to advanced, pick amd hw h264, select cqp, leave the rest (cqp20, preset "quality"), start recording
7. Verify log output, encoder is set to non-hq (given weak enough GPU)

### Anything else we should know?

I think it would be good to ensure that simple mode also uses the new codepath that will modify the preset if needed. Simple mode is arguably more important for this feature than advanced, in my opinion.

**Comment by flaeri** [comment]
I tried to grab a quick peek at what is going on, and I am currently of the opinion that `enc->max_throughput` never gets set to a value other than the 0 it is initialized with.

At least as far as I can tell in the debugger, on my GPU, no value is returned, or the returned value is "0".

https://github.com/obsproject/obs-studio/blob/4e1ba087017bfc17333d2eeb25674596adac9306/plugins/obs-ffmpeg/texture-amf.cpp#L1172

**Comment by flaeri** [comment]
I've had help from a user with a 6900 XT, and they verify that the query returns an actual value. Its possible that this cap query only works on RDNA1 and later.

This is a bit unfortunate, as I would say the main use for this cap query is to get that kind of information from lower end GPUs.

As seen above, I've made a submission to the AMF repo to get some clarification and perhaps they'll have some input going forward on how to handler older devices. 

If nothing else, I think it might be a good idea to have a way to handle GPUs that do not support it, or at least unify the behavior between simple and advanced.

**Comment by jp9000** [comment]
"hq" is actually an invalid preset. The AMD encoder only supports the preset names of "quality", "balanced", and "speed". Simple output mode was unintentionally using "hq" for recording, so I'll fix that. Should be "quality". Streaming should be using whatever the encoder defaults to, which should also be quality, but if it can't query that API, it'll use balanced instead. It won't use speed unless the API is available and the API confirms that it's not supported. So you definitely shouldn't be going all the way down to speed unless the API is available.

**Comment by jp9000** [comment]
I think my fallback has a slight bug, and is falling back to "speed" if the API isn't available. I'll fix that.

I was specifically recommended not to use quality if the API isn't available from the driver. So if you updated your driver and the API is still not available, then I don't think there's anything I can do to avoid you from using balanced without potentially risking other people from having broken setups.

**Comment by jp9000** [comment]
I've pushed two fixes: https://github.com/obsproject/obs-studio/commit/d68539e26788250ee10298575b309d446d636948 and https://github.com/obsproject/obs-studio/commit/f6f6690ccfeb4b78eec82d4ff853cb6db7138860.

**Comment by flaeri** [comment]
@jp9000 Yep, tested both simple and advanced, and both now work as one would expect, and I end up with "balanced" on both.

I did indeed try the latest drivers, and still no dice for getting a value returned on max_throughput on my GPU model.

All good on my end, so I'll close this issue. Thank you very much!
