### ISSUE TITLE
RME Babyface Pro's Mic sound not working

### ISSUE THREAD

**Issue by kilinbox** [obsproject/obs-studio#6795]
### Operating System Info

macOS 12

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/LN3zfdHP52cXcOCi

### Expected Behavior

Microphone connected to RME Babyface Pro can be used.

### Current Behavior

Microphone sound not working when to RME Babyface Pro.
Errors appear in the log.

> [input_callback]:[device 'Babyface Pro (73017498)'] audio retrieval failed: -50

### Steps to Reproduce

1. Select "Babyface Pro" for Mic Audio in the Audio Setting. Or, set "Babyface Pro" to Audio Input Capture of the source.
2. But there is no response on the Audio Mixer volume meter.

### Anything else we should know?

I have a Macbook built-In mic and a MOTU M2 on my Mac, both of which are fine.
I wondered what the difference was compared to a correctly working device, so I added the following code to the coreaudio_init_format function in mac-audio.c.

```
	if ((desc.mFormatFlags & kAudioFormatFlagIsNonInterleaved) == kAudioFormatFlagIsNonInterleaved) {
		blog(LOG_INFO, "NonInterleaved");
	} else {
		blog(LOG_INFO, "Interleaved");
	}
```

Then the following log was shown as NonInterleaved for Babyface.
https://obsproject.com/logs/EXXXsRmYh7jzqgHp

> 22:14:42.500: Interleaved
> 22:14:42.533: coreaudio: device 'MacBook Airのマイク' initialized
> 22:14:43.914: Interleaved
> 22:14:44.284: coreaudio: device 'M2' initialized
> 22:14:45.933: NonInterleaved
> 22:14:46.150: coreaudio: device 'Babyface Pro (73017498)' initialized

Is mac-audio.c the code for what non-interleaved can handle?

**Comment by pkviet** [comment]
The code assumes interleaved. Don't change that.
As to your interface not working, there's not enough info as to why.
Without the device we'll have a hard time debugging.
How many channels does it support ? Could be it has more than 8 which is the max supported.

**Comment by pkviet** [comment]
24 channels. That's why. One solution would  be to use a virtual driver like loopback.

**Comment by kilinbox** [comment]
> The code assumes interleaved. Don't change that. As to your interface not working, there's not enough info as to why. Without the device we'll have a hard time debugging. How many channels does it support ? Could be it has more than 8 which is the max supported.

babyface is 14 channels.

> Could be it has more than 8 which is the max supported.

okay, Unfortunately, I understand.
thanks.

**Comment by pkviet** [comment]
there's a solution here; try to compile this Pull Request:
https://github.com/obsproject/obs-studio/pull/2889
You'll have to rebase it though.
Marking as closed.

**Comment by kilinbox** [comment]
thanks.
I know it's closed now, but...

I already tried #2889 but it did not resolve the issue.
I also feel that this may be another problem since the microphones connected to 1ch and 2ch are not recognized in the first place.
Other applications, such as "Audacity", can use the microphone without problems.
