### ISSUE TITLE
OBS recording freezes to one frame after switching to full-screen game with Fedora 36, Nvidia, and Wayland

### ISSUE THREAD

**Issue by SaltySpectrum** [obsproject/obs-studio#6803]
### Operating System Info

Other

### Other OS

Fedora Linux 36 (Workstation Edition) Gnome version 42.3

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/UWucxV4-MnJIV5L5

### Expected Behavior

After clicking the record button and switching to my full-screen game. The recording should display what is happening in the full-screen game.

### Current Behavior

The recording freezes to one frame after switching to the full-screen game. Audio works just fine.

### Steps to Reproduce

1. Use Fedora 36 with Nvidia graphics card and Wayland
2. Try to use display capture or windows capture (pipewire) and select game you want to record.
3. Record with OBS and switch to full-screen game.
4. Review footage to see that the video image freezes to one frame and see the audio working.

**Comment by tytan652** [comment]
NVIDIA on Wayland is not supported.

**Comment by gxalpha** [comment]
Closing per above.

**Comment by HurricanePootis** [comment]
I've had this problem on Mesa using an RX 580 as well https://github.com/obsproject/obs-studio/issues/6353

**Comment by SpookySkeletons** [comment]
Got this issue with AMD RX 6800M on KDE wayland
