### ISSUE TITLE
Switching scenes too fast messes up fading

### ISSUE THREAD

**Issue by fulldecent** [obsproject/obs-studio#6823]
### Operating System Info

macOS 12

### OBS Studio Version

27.2.4

### OBS Studio Log URL

n/a

### Expected Behavior

Only blue and green scenes are visible on the screen.

### Current Behavior

The screen shows all three: red, green, and blue scenes.

### Steps to Reproduce

1. Increase your transition time, or be able to click/move very fast
2. Create three scenes: all red, all blue, all green
3. Click red scene
4. Quickly click between the blue and green scenes over and over... blue... green... blue... green... blue... green... blue... green... blue... green... blue... green... 

### Anything else we should know?

I am using the iPad and Apple Pencil as a second display for the scenes. So this makes it easy to switch between the blue and green scenes.

And quickly clicking back and forth is no big deal, this is a normal thing that would happen during a broadcast. In fact I use this to switch between two scenes where one of them has a badge on top. Going back and forth would have the intended effect of blinking the badge.

**Comment by tuduweb** [comment]
You mean the red scence didn't disppear after transition time?

**Comment by fulldecent** [comment]
As you are clicking you will see these transitions:

Red -> green
Red -> blue
Red -> green
Red -> blue

where I was expecting

Red -> green
green -> blue
blue -> green
green -> blue

**Comment by RavenX8** [comment]
Can confirm that this issue also occurs on Windows 10 and Windows 11 (both x64)

**Comment by PatTheMav** [comment]
Sounds to me like the "active" scene is changed in UI, but not necessarily inside the compositor, because the observed behaviour matches what would happen if the reference to the currently active scene is only set by the callback of a finished transition.

As you don't allow the transition to finish however, the internal "source" for the transition isn't changed, to switching to yet another scene creates a new transition between the (still unchanged) internal source scene to the new destination scene.

**Comment by PatTheMav** [comment]
After having looked into a similar issues with stinger transitions, this is indeed "as implemented" - only after a transition has finished will the active scene be switched. 

When you click on yet another scene while the transition is ongoing, the old transition will be aborted and a new transition will be triggered. A transition will always use the current active scene as the "source" and the clicked scene as the "destination". As the prior transition did not finish, the source scene will stay the same.

Alas as implemented, the transition system creates a confusion between "visual" state of a transition and the actual state as understood by the compositor. For now, this works as intended.
