### ISSUE TITLE
The game "Call of Duty" does not work on monitor capture with "Win10 (1903 at least)" mode

### ISSUE THREAD

**Issue by yanrk** [obsproject/obs-studio#6831]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/48CLf7-enxvbFqqi

### Expected Behavior

I expected the game can be captured on mode "Win10 (1903 at least)", just like mode "DXGI capture" does

### Current Behavior

The game "Call of Duty" does not work on monitor capture with "Win10 (1903 at least)" mode, but work on "DXGI capture" mode; the problem also happend on other games sometimes.

### Steps to Reproduce

1. prepare 2 monitors;
2. open obs-studio to capture monitor 1 with mode "Win10 (1903 at least)", obs works;
3. move obs-studio to monitor 2, obs still works;
4. open the game "Call of Duty", play it, obs doest not work now.
5. close the game, obs works again.
...

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
