### ISSUE TITLE
[Mac] - Docks windows can't be add to OBS layout 

### ISSUE THREAD

**Issue by vclerissj** [obsproject/obs-studio#6885]
### Operating System Info

macOS 12

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/SJT0z98eMZ_viZ84

### Expected Behavior

Can change the docks windows and integrate them to OBS layout.

### Current Behavior

https://user-images.githubusercontent.com/18285026/182040785-d7aa8083-e6be-4908-a662-fd44c207f09a.mov

### Steps to Reproduce

1. Open OBS
2. Click on docks menu
3. Add windows docks like Twitch Activity Feed
4. Try to integrate previous window to layout on moving on the OBS border
5. Nothings happen

### Anything else we should know?

My lockUI in docks menu is deactivate.

**Comment by gxalpha** [comment]
There are many issues with docks on macOS due to Qt 5. While I can't tell 100%, this looks like one of them.
We're switching to Qt 6 in OBS 28 which will fix this issue. Keep an eye out for the beta, or try a nightly build of OBS. If it happens there as well, feel free to reopen this issue.

**Comment by vclerissj** [comment]
Thx ! I will try the nightly build !
