### ISSUE TITLE
SRT/RIST: Hardware Decoding an HEVC video feed causes the Media Source to freeze & crash OBS on exit

### ISSUE THREAD

**Issue by Miltos95** [obsproject/obs-studio#6889]
### Operating System Info

Windows 10

### OBS Studio Version

Git

### OBS Studio Log URL

https://obsproject.com/logs/8Zh9iHH71I3Y63du

### Expected Behavior

Play the video feed without freezing or causing a crash on exit.

### Current Behavior

Plays the feed for a couple of seconds and freeze-frames.
Also causes a crash on exit.

### Sender OBS
1. Setup an SRT/RIST stream
2. Use the NVIDIA NVENC HEVC (new) encoder (the encoder settings doesn't seem to matter)
3. Start the stream

### Receiver OBS
1. Use a Media Source to play the SRT/RIST feed
2. Check the box "Use hardware decoding when available"
3. Press OK and observe the video feed freeze after a couple of seconds
4. Press Exit to terminate the Receiver OBS and observe it crashing.

### Anything else we should know?

H264 hardware decoding works fine.
Also happens on 27.2.0 if paired with the "Custom Output (FFmpeg)" on the Sender OBS.

Tested using a GeForce GTX 970 (Maxwell 2nd Gen).

**Comment by marazmarci** [comment]
@pkviet, is it possible that this issue will also be solved by #7306 ?

**Comment by pkviet** [comment]
> @pkviet, is it possible that this issue will also be solved by #7306 ?

Unrelated. The leak is with the srt output. The issue here is with the Media Source.

**Comment by RytoEX** [comment]
I've tested this with two OBS Studio 29.0.2 instances on the same system with a GTX 1060. I was not able to reproduce this. The Media Source in the Receiver OBS plays the SRT stream from the Sender OBS just fine in my test case.

**Comment by gxalpha** [comment]
As stated above, we were unable to reproduce this issue in any way. As such, unfortunately we don't think there's anything we can fix here.

**Comment by Miltos95** [comment]
I cannot reproduce it either with a GTX 1050 and an RTX 3060 Ti, only with a GTX 970.
Perhaps Maxwell related or my 970's hardware decoder is giving up?
I don't have another Maxwell-based card handy to test right now.
