### ISSUE TITLE
NEW macOS Screen Capture (one using ScreenCaptureKit) doesn't capture Powerpoint presentation correctly.

### ISSUE THREAD

**Issue by phu54321** [obsproject/obs-studio#6893]
### Operating System Info

macOS 12

### OBS Studio Version

Git

### OBS Studio Version (Other)

27.2.0-862-g7ec6f0a66

### OBS Studio Log URL

https://obsproject.com/logs/b-dQqxqq2UbLS0eD

### Expected Behavior

Fullscreen Powerpoint presentation should be recorded like this. (This works on deprecated "Display Capture" mode)

<img width="1191" alt="Greenshot 2022-08-01 19 00 15" src="https://user-images.githubusercontent.com/775265/182124919-9112c14f-98a4-4869-800f-aa9a433f81e8.png">

> note: this "expected behavior" is captured using deprecated "Display Capture" source.

### Current Behavior

https://youtu.be/dZ_rbE3XtGM

Only desktop image is recorded.

<img width="1191" alt="Greenshot 2022-08-01 19 00 21" src="https://user-images.githubusercontent.com/775265/182124935-07c62e65-fd0a-4e3c-9278-02d82a7135f3.png">

### Steps to Reproduce

1. Attach Second Display. (I'm using [BetterDummy](https://github.com/waydabber/BetterDisplay) for that purpose)
2. Run any powerpoint presentation
3. Control surface should appear on the first display, and **the presentation itself should appear on the second display**.
4. Record the second display via macOS Screen Capture - Display Capture.

<img width="832" alt="image" src="https://user-images.githubusercontent.com/775265/182124605-d1dbb5fd-30fd-4261-a5cb-1f4184db8ce0.png">

### Anything else we should know?

- macOS 12.5
- Powerpoint version 16.63.1 (22071401, Microsoft Office 365 subscription)

**Comment by gxalpha** [comment]
This issue might be because of a workaround we have to use for Display Capture on macOS 12 due to a bug in SCK.
I'll try to investigate.
