### ISSUE TITLE
Python: On Windows, Python 3.6 crashes on launch

### ISSUE THREAD

**Issue by flaeri** [obsproject/obs-studio#6897]
### Operating System Info

Windows 11

### OBS Studio Version

Git

### OBS Studio Version (Other)

27.2.0-813-g7bfc7e65f

### OBS Studio Log URL

https://gist.github.com/flaeri/bf75a3804ccef2fbe9142497b70bab8d

### OBS Studio Crash Log URL

https://gist.github.com/flaeri/b5a0d6bf5cdfc163952940fe5fb4440e

### Expected Behavior

I expect on OBS Windows will not crash on startup with Python 3.6 path set.

### Current Behavior

It crashes on `7bfc7e65f` and later commits, if python 3.6 is set in the global.ini file.

### Steps to Reproduce

1. Download Python 3.6
<https://www.python.org/ftp/python/3.6.8/python-3.6.8-embed-amd64.zip>
2. Unzip to C:\python36
3. Add it to your path via tools > scripts > python path
4. Observe silent crash

### Anything else we should know?

If you upgrade from a version prior, IE the py36 path is already set, you will crash on launch (see attached crashlog).

This happens on python 3.6.0 and 3.6.8. I've tried the installer as well as the zip, no change.

Happens with and without any python scripts loaded.

Earliest commit that causes this: 7bfc7e65f4
You can download it here: <https://github.com/obsproject/obs-studio/actions/runs/2763999685>

Also happens on latest master/nightly for the past few days.

Building these older commits is now quite tricky due to recent changes (C2220, linker errors to py), so I've attached the stack trace in VS via a more recent commit c2122b0

![image](https://user-images.githubusercontent.com/50419942/182203424-02a1157d-1a0a-44b9-89c5-420ec17f9b95.png)

**Comment by RytoEX** [comment]
Bisected CI builds to this being the first bad commit, unfortunately:
https://github.com/obsproject/obs-studio/commit/7bfc7e65f4ab7d4ec7796257695cfb8beb209b15

@PatTheMav ?

**Comment by PatTheMav** [comment]
Threads are initialised only up to Py 3.6, but are released without any guard:

https://github.com/obsproject/obs-studio/blob/67f7a84076be2c73d172eb14265c60d6209598db/deps/obs-scripting/obs-scripting-python.c#L1665

Maybe worth removing the ifdef?

**Comment by Scrxtchy** [comment]
I could only replicate this from a build produced by CI, not one from my development environment

**Comment by RytoEX** [comment]
> I could only replicate this from a build produced by CI, not one from my development environment

Are you using the latest Windows dependencies (2022-07-29)?

**Comment by Scrxtchy** [comment]
> > I could only replicate this from a build produced by CI, not one from my development environment
> 
> Are you using the latest Windows dependencies (2022-07-29)?

Yes, I have upgraded my deps today, I had to clear my cmake cache for this to compile [[discord log]](https://discord.com/channels/348973006581923840/374636084883095554/1003617472575967374)

**Comment by RytoEX** [comment]
> > > I could only replicate this from a build produced by CI, not one from my development environment
> > 
> > 
> > Are you using the latest Windows dependencies (2022-07-29)?
> 
> Yes, I have upgraded my deps today, I had to clear my cmake cache for this to compile [[discord log]](https://discord.com/channels/348973006581923840/374636084883095554/1003617472575967374)

On Windows, this requires more than just clearing your CMake cache, in my experience. You also have to clear out your `additional_install_files` folder to prevent any older deps residing there from being used.

**Comment by Scrxtchy** [comment]
> On Windows, this requires more than just clearing your CMake cache, in my experience. You also have to clear out your `additional_install_files` folder to prevent any older deps residing there from being used.

I had all libs that dated back to 2017 and cleared it all out, reconfiguring and regenerating these did not reproduce the error in the OP

The error appears to be related to the obspython.pyd file, as copying it from my working build into the failing CI build would resolve the crash, I have a70dd4d925f67488b57016811778303a5e998d8a merged, I am yet to understand anything about the file

but I suspect it is more to do with this
![image](https://user-images.githubusercontent.com/12771982/182251052-7596a439-b895-436d-a53a-842d97ce41ed.png)

**Comment by RytoEX** [comment]
> > On Windows, this requires more than just clearing your CMake cache, in my experience. You also have to clear out your `additional_install_files` folder to prevent any older deps residing there from being used.
> 
> I had all libs that dated back to 2017 and cleared it all out, reconfiguring and regenerating these did not reproduce the error in the OP
> 
> The error appears to be related to the obspython.pyd file, as copying it from my working build into the failing CI build would resolve the crash, I have [a70dd4d](https://github.com/obsproject/obs-studio/commit/a70dd4d925f67488b57016811778303a5e998d8a) merged, I am yet to understand anything about the file
> 
> but I suspect it is more to do with this \<snip>🎉
> 
> ```
> 'obs64.exe' (Win32): Loaded 'D:\Scratch\Documents\Git\obs-studio\build\rundir\Debug\data\obs-scripting\64bit\_obspython.pyd'. Symbols loaded.
> Exception thrown at 0x00007FFCE3493416 (ntdll.dll) in obs64.exe: 0xC0000005: Access violation writing location 0x0000000000000024.
> ```

Those files should all have the same date/timestamp if you do a fresh build with an empty build folder.
![image](https://user-images.githubusercontent.com/624931/182252373-a07de0cb-f101-49a8-93d0-e3235862a537.png)

As far as I understand, SWIG _requires_ one "_obspython.pyd" and one "obspython.py". The "obspython.pyd" file without an underscore was an accident, which was resolved in #6882.

**Comment by Scrxtchy** [comment]
Ya, the commit from my post was in reference to the PR, but as it stated depending on the filename it took preference over the newer file which is built on a newer version of python 
-- 
Sent from mobile

**Comment by flaeri** [comment]
Unsure if this is of use, but with procmon this is the stack of the last OBS operation prior to exploding.

![image](https://user-images.githubusercontent.com/50419942/182324278-83ffa342-8d48-4752-b6b4-3236f50af804.png)


Frame | Module | Location | Address | Path
-- | -- | -- | -- | --
0 | FLTMGR.SYS | FltGetFileNameInformation   + 0x1e53 | 0xfffff80508266f73 | C:\WINDOWS\System32\drivers\FLTMGR.SYS
1 | FLTMGR.SYS | FltGetFileNameInformation + 0x1906 | 0xfffff80508266a26 | C:\WINDOWS\System32\drivers\FLTMGR.SYS
2 | FLTMGR.SYS | FltGetFileNameInformation   + 0x992 | 0xfffff80508265ab2 | C:\WINDOWS\System32\drivers\FLTMGR.SYS
3 | FLTMGR.SYS | FltGetFileNameInformation + 0x71b | 0xfffff8050826583b | C:\WINDOWS\System32\drivers\FLTMGR.SYS
4 | ntoskrnl.exe | IofCallDriver +   0x55 | 0xfffff8050ac504a5 | C:\WINDOWS\system32\ntoskrnl.exe
5 | ntoskrnl.exe | IoBuildDeviceIoControlRequest + 0x67e | 0xfffff8050aca12fe | C:\WINDOWS\system32\ntoskrnl.exe
6 | ntoskrnl.exe | KeAcquireQueuedSpinLock   + 0x1180 | 0xfffff8050acc4f10 | C:\WINDOWS\system32\ntoskrnl.exe
7 | ntoskrnl.exe | KeAcquireQueuedSpinLock + 0x1be4 | 0xfffff8050acc5974 | C:\WINDOWS\system32\ntoskrnl.exe
8 | ntoskrnl.exe | MmProbeAndLockPages   + 0x314b | 0xfffff8050ac75dab | C:\WINDOWS\system32\ntoskrnl.exe
9 | ntoskrnl.exe | setjmpex + 0x4545 | 0xfffff8050ae268f5 | C:\WINDOWS\system32\ntoskrnl.exe
10 | python36.dll | PyArg_ParseTuple_SizeT   + 0xbc | 0x6b969560 | C:\secret\python36.dll
11 | python36.dll | PyArg_ParseTuple_SizeT + 0x2a | 0x6b9694ce | C:\secret\python36.dll
12 | python36.dll | Py_hashtable_size   + 0x10e5d | 0x6ba27e29 | C:\secret\python36.dll
13 | python36.dll | PyCFunction_FastCallDict + 0x195 | 0x6b977a45 | C:\secret\python36.dll
14 | python36.dll | PyObject_GetAttr   + 0x399 | 0x6b978119 | C:\secret\python36.dll
15 | python36.dll | PyEval_EvalFrameDefault + 0x2ae | 0x6b978b4e | C:\secret\python36.dll
16 | python36.dll | PyFunction_FastCallDict   + 0xd3 | 0x6b973b53 | C:\secret\python36.dll
17 | python36.dll | PyObject_ClearWeakRefs + 0x7da | 0x6b973a06 | C:\secret\python36.dll
18 | python36.dll | PyCFunction_Call   + 0xd86 | 0x6b97079e | C:\secret\python36.dll
19 | python36.dll | PyCFunction_Call + 0x7e4 | 0x6b9701fc | C:\secret\python36.dll
20 | python36.dll | PyObject_SetItem   + 0x49 | 0x6b96643d | C:\secret\python36.dll
21 | python36.dll | PyEval_EvalFrameDefault + 0xc27 | 0x6b9794c7 | C:\secret\python36.dll
22 | python36.dll | PyObject_Free +   0x3e8 | 0x6b975728 | C:\secret\python36.dll
23 | python36.dll | PyEval_EvalCodeEx + 0x9b | 0x6b94b45f | C:\secret\python36.dll
24 | python36.dll | PyEval_EvalCode   + 0x2d | 0x6b94b3bd | C:\secret\python36.dll
25 | python36.dll | PyArena_Free + 0xa7 | 0x6b94b367 | C:\secret\python36.dll
26 | python36.dll | PyRun_StringFlags   + 0x89 | 0x6b94b291 | C:\secret\python36.dll
27 | python36.dll | PyRun_SimpleStringFlags + 0x45 | 0x6b98344d | C:\secret\python36.dll
28 | <unknown> | 0x7ffbf4bd0d05 | 0x7ffbf4bd0d05 |  
29 | <unknown> | 0x7ffbefd2fffa | 0x7ffbefd2fffa |  
30 | <unknown> | 0x7ffbefd3a4be | 0x7ffbefd3a4be |
