### ISSUE TITLE
New AMD AVC HW encoder overloading(h264)

### ISSUE THREAD

**Issue by Johl7** [obsproject/obs-studio#6899]
### Operating System Info

Windows 10

### OBS Studio Version

Git

### OBS Studio Log URL

https://obsproject.com/tools/analyzer?log_url=https%3A%2F%2Fobsproject.com%2Flogs%2FUqfPewGbbWqfM_tC#logURL

### Expected Behavior

Changing scenes goes smoothly and no overload happens

### Current Behavior

Changing scenes into a game capture causes encoder to overload and OBS to hang, requiring the use of task manager.

### Steps to Reproduce

1.Have a scene set with game capture and anti compatibility hook checkmarked.
2.Start the game while having a different scene selected, like a media playing or somethin.
3.After the game has started change into the scene with it as game capture
...

### Anything else we should know?

Tested with only a few games, MHW(dx12,dx11) and MHR(dx12).

**Comment by flaeri** [comment]
Could you please redo the log with the following changes:
1. Make sure you hit stop streaming/recording before you upload the log.
2. Remove all of the custom encoder options
3. Remove  'Media Source 5':  D:/Videos/test/2022-06-08 10-30-05.mp4. Use a different video, or preferably some other simple test, like an image/color source or similar.

**Comment by Jocker73** [comment]
[2022-08-02 10-41-53.txt](https://github.com/obsproject/obs-studio/files/9242695/2022-08-02.10-41-53.txt)

**Comment by flaeri** [comment]
Were you the one who mentioned downgrading drivers solved this issue?

Or is it still happening? If yes, I assume its the same as this one https://github.com/obsproject/obs-studio/issues/7047?

**Comment by Jocker73** [comment]
I havent tried downgrading drive yet.. but in the past i was with the current stable driver and i had multiple instances of the encoder overloading... so, similar behavior. Overloads used to happen way b4... as mentioned in this post, seems like anything that pushes the encoder a bit can make it overload and high change of it stalling.

**Comment by flaeri** [comment]
> Tried with driver 22.5.1(thou not clean install) and the encoder behaved the same.

Sure, but would you say this is a seperate issue from https://github.com/obsproject/obs-studio/issues/7047?
If it feels like its the same, we should probably keep gathering all the info in that one.

**Comment by Johl7** [comment]
Ohh, sure.. mb, thou this info is already inclued in there.

**Comment by RytoEX** [comment]
Duplicate of #7047

**Comment by BrianChenkus** [comment]
Same issues here. Had to revert to using software encoding
[2022-09-11 10-08-49.txt](https://github.com/obsproject/obs-studio/files/9542818/2022-09-11.10-08-49.txt)
[2022-09-11 10-30-11.txt](https://github.com/obsproject/obs-studio/files/9542819/2022-09-11.10-30-11.txt)
[2022-09-11 10-34-05.txt](https://github.com/obsproject/obs-studio/files/9542820/2022-09-11.10-34-05.txt)
[2022-09-11 10-48-14.txt](https://github.com/obsproject/obs-studio/files/9542821/2022-09-11.10-48-14.txt)

**Comment by Johl7** [comment]
> Same issues here. Had to revert to using software encoding [2022-09-11 10-08-49.txt](https://github.com/obsproject/obs-studio/files/9542818/2022-09-11.10-08-49.txt) [2022-09-11 10-30-11.txt](https://github.com/obsproject/obs-studio/files/9542819/2022-09-11.10-30-11.txt) [2022-09-11 10-34-05.txt](https://github.com/obsproject/obs-studio/files/9542820/2022-09-11.10-34-05.txt) [2022-09-11 10-48-14.txt](https://github.com/obsproject/obs-studio/files/9542821/2022-09-11.10-48-14.txt)

The issue has been fixed in between rc2 and 28 stable release, if ur using 28 then its prob some other issue
