### ISSUE TITLE
Automatic Remux doesn't appear to be working

### ISSUE THREAD

**Issue by GentlePuppet** [obsproject/obs-studio#6903]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/udI00yLFZYDMNWYa

### Expected Behavior

With `Automatically remux to mp4` enabled and ending a recording it should automatically remux the mkv to an mp4 file. 
I recently updated and automatic remux was working just fine in the previous version I was using (I don't remember what version it was, unfortunately).

Manually remuxing recordings does work just fine, but that defeats the purpose of "Automatic remux" mode.

![image](https://user-images.githubusercontent.com/43224790/182274578-ffbc8b59-03f8-4596-90bd-c074ee2b13f6.png)
![image](https://user-images.githubusercontent.com/43224790/182298879-b90954ed-fae6-45e3-aa75-22b77843fc84.png)

### Current Behavior

It doesn't automatically remux the mkv to mp4.

### Steps to Reproduce

1. Enable automatic remux
> Set the _Settings>Output>Output Mode: Advanced>Recording tab>Type>**Custom Output (FFmpeg)**_
> Switch back to the _Output Mode: Simple_
Credit to [SuslikV](https://github.com/SuslikV) for figuring out how to reproduce the issue.

### Anything else we should know?
[Roaming\obs-studio\basic\profiles\basic.ini.txt](https://github.com/obsproject/obs-studio/files/9239327/basic.ini.txt)
[Roaming\obs-studio\basic\scenes\Game_Capture.json.txt](https://github.com/obsproject/obs-studio/files/9239328/Game_Capture.json.txt)

**Comment by RytoEX** [comment]
I cannot reproduce this. Automatic Remux works fine for me in all cases I tested, including trying to replicate the settings in your log and screenshots. I also do not believe that this log file matches these settings screenshots, as the settings between them do not match.

**Comment by GentlePuppet** [comment]
Ah, yes screenshot the wrong profile. But that is redundant, unfortunately, causes it happens in both. The only difference between the 2 is the video and audio bitrate.

**Comment by GentlePuppet** [comment]
Updated with my config files, I pruned my twitch data (also just reset my key anyways so eh) maybe these can help.

I have no idea what is causing this issue but it's rather annoying. Seems like I just have issues with obs.

**Comment by SuslikV** [comment]
To reproduce the issue you need to:
1) set the _Settings>Output>Output Mode: Advanced>Recording tab>Type>**Custom Output (FFmpeg)**_
2) back to the _Output Mode: Simple_


@GentlePuppet
as workaround, try to set  _Settings>Output>Output Mode: Advanced>Recording tab>Type>**Standard**_
and only then back to the _Output Mode: Simple_

**Comment by PatTheMav** [comment]
Changing the UI doesn't necessarily change the settings, so when Custom FFmpeg output is enabled, the auto-remux setting is ignored.

Just changing the output mode to "simple" doesn't change the state of the advanced output config (but that's where we look for the setting), so the entire feature stays disabled.

I guess guarding the check for FFmpeg output only if advanced output is enabled as well should fix this issue, feel free to open a PR for this.
