### ISSUE TITLE
VLC Plugin limits subtitle track selection to 10 tracks.

### ISSUE THREAD

**Issue by TinFoilFox** [obsproject/obs-studio#6906]
### Operating System Info

Windows 10

### Other OS

N/A

### OBS Studio Version

27.2.4

### OBS Studio Version (Other)

N/A

### OBS Studio Log URL

https://obsproject.com/logs/4Elre3etiSW7Jn9i

### OBS Studio Crash Log URL

N/A

### Expected Behavior

The OBS VLC plugin should allow the user to select any of the available subtitles in a media file.

### Current Behavior

The OBS VLC plugin limits the subtitle selection to only 10 subtitle tracks, even if the media file has more.

### Steps to Reproduce

1. Add a media file with many subtitles with the VLC media source. 
2. Double-click on the media source or right-click on it and click on properties.
3. At the bottom of the properties form, try to select a subtitle track higher than 10.

### Anything else we should know?

I tested this with many different mkv media files that had multilingual subtitles, some of which had over 25 subtitle tracks.
Example:
![Screenshot 2022-08-01 233222](https://user-images.githubusercontent.com/15332259/182299577-a0849fc9-519d-4d36-a549-bc3121e41282.png)

The VLC plugin limits the selection to the first 10.
Example:
![image](https://user-images.githubusercontent.com/15332259/182300735-25bda96c-cfeb-42f0-a91e-92f35aac7185.png)

I have included a test media file with 30 subtitle tracks and an external subtitle track so you can test this separately.

The easy solution would probably be to just increase the arbitrary limit to something like 100 tracks (or higher). Since I've never seen more than about 25-30 myself, that would probably solve most cases users would run across.

[Subtitle-Test.zip](https://github.com/obsproject/obs-studio/files/9239246/Subtitle-Test.zip)

**Comment by gxalpha** [comment]
As a workaround for now, if you want to you could try to manually edit the scene collection and set an arbitrary number.

For others reading this, this would be fixed by #6680.

**Comment by TinFoilFox** [comment]
Ah perfect, I searched for existing issues but forgot to take a look at PR's.
Thank you @jjm2473 for your pull request. I hope to see it merged :)
