### ISSUE TITLE
UI: Useless setting in Advanced recording tab

### ISSUE THREAD

**Issue by SuslikV** [obsproject/obs-studio#6909]
### Operating System Info

Other

### Other OS

any OS

### OBS Studio Version

Git

### OBS Studio Version (Other)

d12836a

### OBS Studio Log URL

about:blank

### Expected Behavior

Option exposed to user through UI should do something.

### Current Behavior

The item:

https://github.com/obsproject/obs-studio/blob/d12836af51e07e69348d83a316b6c853ad0c1639/UI/forms/OBSBasicSettings.ui#L2933-L2937

do nothing (do not saves/restores its value, do not changes OBS behavior) but it visible to the user.

### Steps to Reproduce

1. Set the _Settings>Output>Output Mode: Advanced>Recording tab>Automatic File Splitting: **Only split manually**_
2. Close the Settings with OK button
3. Open _Settings>Output>Output Mode: Advanced>Recording tab_
4. Notice that the _Automatic File Splitting_ value resets by itself back to _**Split by Time**_

### Anything else we should know?

Feature shouldn't be enabled in the code until fully implemented (it is normal practice).

https://github.com/obsproject/obs-studio/pull/6816/files

I have no access to the PR to comment, so here it is.

**Comment by gxalpha** [comment]
You’re wrong.
You can split manually with a hotkey.

**Comment by SuslikV** [comment]
UI entry doesn't changes mentioned behavior.

**Comment by gxalpha** [comment]
I see what you mean now. However the feature itself is implemented, what you found is a bug with the feature. Saying "Feature shouldn't be enabled in the code until fully implemented (it is normal practice)" makes it sound nothing was added, and the UI option doesn't have any functionality.

**Comment by SuslikV** [comment]
The UI setting changed its save/load behavior in:
https://github.com/obsproject/obs-studio/pull/6910

(it just info to link the issues and solutions, so be kind and respect information linking)
