### ISSUE TITLE
OBS crashes when selecting lossless in "NVENC (new)"

### ISSUE THREAD

**Issue by style1925** [obsproject/obs-studio#6911]
### Operating System Info

Windows 10

### OBS Studio Version

Git

### OBS Studio Log URL

https://obsproject.com/logs/Jr3Taws1zttuaUZf

### OBS Studio Crash Log URL

https://obsproject.com/logs/Kf3GKDsiktJ53zP0

### Expected Behavior

OBS starts output without crashing

### Current Behavior

OBS crashes.

### Steps to Reproduce

1. download Nightly Build
2. Open Settings -> Output
3. Set output mode to "Advanced
4. Open the Recording tab
5. Set to "NVIDIA NVENC H.264 (new)
or "NVIDIA NVENC HEVC (new)".
6. Change "Rate Control" to "Lossless".
7. Start Recording (or Start Replay Buffer)
8. OBS crashes.

### Anything else we should know?

This does not occur in 27.2.4.

If "Psycho Visual Tuning" is disabled, the crash will not occur. (Why?)

I'm using translation. Sorry if the English is not correct.

**Comment by flaeri** [comment]
Can confirm I've seen another user in the discord report the exact same thing. Happened on both HEVC and h264. Rtx 2070super, driver: 472.84

https://obsproject.com/logs/qnMqy6aNjgZ-duiI
https://obsproject.com/logs/WgERhrw5521FKDOB
