### ISSUE TITLE
[28.0.0-beta1] EOS Webcam utility not visible as video capture device (apple silicon)

### ISSUE THREAD

**Issue by dotLou** [obsproject/obs-studio#6931]
### Operating System Info

macOS 12.5

### OBS Studio Version

Other

### OBS Studio Version (Other)

28.0.0-beta1 - installed with arm64 dmg

### OBS Studio Log URL

https://obsproject.com/logs/X97BWFqDCDBIO59b

### Expected Behavior

On previous versions (including 27.2.4) EOS Webcam utility is available as a video capture device and thus can be used as output (for virtual camera or otherwise).

### Current Behavior

In this version an existing capture device shows it as disabled.

![image](https://user-images.githubusercontent.com/2522036/182644167-869456be-5ae4-4695-8ade-d85a4530f70e.png)

Selecting another device works, but then the EOS Webcam utility disappears from the dropdown entirely.
![image](https://user-images.githubusercontent.com/2522036/182644212-57755cd7-3dcd-4453-a34e-58c538760ee8.png)

This remains true if a new video capture device is added

### Steps to Reproduce

1. Install 27.2.4 on an apple silicon macbook pro - e.g. MacBook Pro (14-inch, 2021)
2. Attempt to use a video capture device with `EOS Webcam utility`

### Anything else we should know?

Other virtual cameras are available and appear properly, such as krisp camera

**Comment by gxalpha** [comment]
From what I can tell, this is expected as you're running the native version of OBS. For the EOS Webcam utility to get picked up, it also needs to be native (or better even universal), as OBS itself loads the camera plugin and Rosetta doesn't allow mixing native and translated code.
You can work around this by running the Rosetta version of OBS 28. If that does not fix this issue, feel free to reopen it.
