### ISSUE TITLE
VLC Video Source breaks with VLC 3.0.17.4

### ISSUE THREAD

**Issue by tehbasshunter** [obsproject/obs-studio#6932]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/tools/analyzer?log_url=https%3A%2F%2Fpastebin.com%2FwanSZU4z

### Expected Behavior

Should have option to add VLC Video Source.

### Current Behavior

Source option is not available and logs error to log file.

```
07:15:59.294: LoadLibrary failed for 'C:\Users\tehbasshunter\Desktop\Stream App & Folders\VLC_Player\libvlc.dll': %1 is not a valid Win32 application.
07:15:59.294:  (193)
07:15:59.294: [vlc-video]: Couldn't find VLC installation, VLC video source disabled
```

### Steps to Reproduce

1. Have OBS 27.2.4 installed.
2. Have VLC Player 3.0.17.4 installed
3. Have `HKEY_LOCAL_MACHINE\SOFTWARE\VideoLAN\VLC` set to the following/similar
![95DTEAh](https://user-images.githubusercontent.com/6345556/182652348-29f65643-b5fd-462d-ad68-9ac7f63aee71.jpg)

**Comment by notr1ch** [comment]
A 64-bit version of OBS requires a 64-bit version of VLC.
