### ISSUE TITLE
Windows 11: Fullscreen projector has constant tearing for Dual PC streaming/recording but not the windowed projector 

### ISSUE THREAD

**Issue by arckiCriss** [obsproject/obs-studio#6936]
### Operating System Info

Windows 11

### OBS Studio Version

27.2.4

### OBS Studio Version (Other)

all versions after 27.1-rc3

### OBS Studio Log URL

https://obsproject.com/logs/7V0vLxx3JsUKH6tN

### Expected Behavior

Fullscreen projector should has not tearing and behave as the same as windowed projector in updated Windows 11.

### Current Behavior

My setup:
      Gaming PC: i7-9700k, RTX 3080, OBS 27.2.4, Windows 11 22622.450
      Streaming PC: i7-6820HK, GTX1070, OBS 27.2.4, Windows 10 19044.1806
      Capture card: Avermedia GC553 @ 1440p60hz

I mostly do streaming/recording with FPS games, e.g., Apex, COD, CSGO etc. And the mentioned setup works flawlessly when my gaming pc was Windows 10.

After my gaming rig was updated to Windows 11, I suddenly found constant screen tearing in my streaming/recording. And after some research, I found that the Fullscreen Projector is to blame. With windowed Projector, there is no tearing at all. 

Fullscreen projector:
![full](https://user-images.githubusercontent.com/9159368/182678607-807b7d2b-92da-4b29-8907-5768c5727d97.gif)

Windowed screen projector:
![windowed](https://user-images.githubusercontent.com/9159368/182678649-ac7af6c9-78c0-41d3-b833-b8d563e45a6f.gif)

### Steps to Reproduce

1.Setup Dual PC streaming with a capture card and download OBS after 27.1 rc2 with Windows 11.
2.Set capture card as extended monitor and use Fullscreen projector.
3.Play some FPS game and move the angle quickly.
4.Same 1-3 steps with windowed projector.
...

### Anything else we should know?

I find five temporary solutions but they all has some drawbacks:
1. Not using projector and clone my monitor to capture card, but some games' UI are broken;
2. Revert the OBS back to 27.1-rc2 (which has no implementation of D3D swap enhancements) to minimize the screen tearing; This one lead to stutter for my streaming/recording and not as smooth as the 27.2.4;
3. Use windowed projector, but I cannot get rid of the caption bar;
4. Use VSync on OBS with Nvidia control panel, but this one leads to severe rendering latency;
5. Use legacy OpenGL rendering, but again it's not smooth as D3D11.

Things I tried:
Tested lots of OBS version, with no 3rd plugins;
HAGS on/off;  Admin or not;  VRR on/off; "Optimization for windowed game" on/off; "Disable Fullscreen Optimizations" on/off
Switch between WGC/DXGI capture method
Change projector origin(source/scene/preview)
Upgrade gaming rig to Windows 11 Insider build; 
Upgrade firmware of capture card;
Change different Hz of capture card and fps settings of OBS;
Set OBS for a single CPU core;
Messing with FILP_DISCARD and ALLOW_TEARING in libobs-d3d11/d3d11-subsystem.cpp and compiled modified versions, turns out without ALLOW_TEARING has rendering latency problem;

My current two cents:
1. D3D swap chain enhancements are introduced by Microsoft to boost performance for rendering.
2. OBS Devs added these swap chain enhancements, but test cases didn't cover all situations.
3. These enhancements are not working exactly the same for Fullscreen borderless window in Windows 11 and Windows 10, or Microsoft broke somethings in Windows 11 (The FILP_DISCARD and ALLOW_TEARING combo works under Windows 10 in my case).
4. Maybe it's related to how the projector's window created/rendered since Fullscreen borderless has tearing while windowed not.
5. In rare cases, the Fullscreen projector can work flawless without tearing, but it's not stable and the tearing may occur during the streaming/recording. Maybe something happened and cause the rendering of Fullscreen borderless window out-of-sync?

Possible related pulls:
[D3D swap chain enhancements #2064](https://github.com/obsproject/obs-studio/pull/2064)
[Fix Windows 11 responsiveness using FLIP_DISCARD #5265](https://github.com/obsproject/obs-studio/pull/5265)
[libobs-d3d11: Use ALLOW_TEARING if supported #5266](https://github.com/obsproject/obs-studio/pull/5266)

Possible related posts: (There are lots of them I just list some)
[Preview screen tearing](https://obsproject.com/forum/threads/preview-screen-tearing-issue-from-obs-studio-27-1-rc3-and-onward-not-present-in-rc2-and-earlier.153499/)
[Constant screen tearing](https://www.reddit.com/r/elgato/comments/u6s55z/any_luck_with_dual_pc_streaming_without_screen/)
[Dual pc screen tearing](https://www.reddit.com/r/Twitch/comments/s32fxi/dual_pc_screen_tearing_issue/)

**Comment by jpark37** [comment]
Are you streaming a capture of a projector? The projectors aren't meant to be relied upon for streaming/recording. They're just for sanity checking.

I'm not familiar with 2-PC setups, but this doesn't sound typical. Shouldn't you capture the original game feed?

**Comment by arckiCriss** [comment]
Thanks for your rapid response. If my understanding is correct, yes I am streaming/recording a projector.

In order to save CPU/GPU resource for gaming PC, streamers use display capture and projector to send images to the capture card, which works as a virtual monitor for gaming PC. The capture card then sends images to another PC for streaming/recording. The key idea is to separate the workload of gaming and streaming with the help of projector.

I also tried game capture with the projector, but the results are same(Fullscreen tearing while windowed not). Since windowed projector works just fine, I think the problem may not related to the capture side (WGC/DXGI), but some sort of out-of-sync issues for rendering frames in Fullscreen projector window under Windows 11.

**Comment by jpark37** [comment]
I'm getting a lot of internal feedback that this is common. (I wish they had told me sooner...)

I think I have a potential solution that won't tear, or stall the graphics thread. I'll see what I can do.

**Comment by arckiCriss** [comment]
Really appreciate your efforts on this amazing project!

**Comment by faureq** [comment]
I'm experiencing this issue with OBS v29.1.0. Windowed preview works flawlessly but fullscreen preview has tearing. I tried windowed preview with autohotkey to remove the window's title and borders. If I hide the title (-WS_CAPTION) it doesn't tear. If I hide the title and borders (-WS_THICKFRAME) it tears. Seems like some FSO bug. I'm on W11.
