### ISSUE TITLE
Can't build on Fedora 36 cmake error

### ISSUE THREAD

**Issue by RyzenDew** [obsproject/obs-studio#6947]
### Operating System Info

Other

### Other OS

Fedora 36

### OBS Studio Version

28.0.0-beta1

### OBS Studio Log URL

none

### OBS Studio Crash Log URL

none

### Expected Behavior

For it to not have a cmake error 

### Current Behavior

```
-- Found FFmpeg: /usr/lib64/libavcodec.so (found version "59.18.100") found components: avcodec avutil avformat 
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Librist (missing: LIBRIST_LIB LIBRIST_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindLibrist.cmake:49 (find_package_handle_standard_args)
  plugins/obs-ffmpeg/CMakeLists.txt:21 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/matt/Downloads/obs-studio/build/CMakeFiles/CMakeOutput.log".
See also "/home/matt/Downloads/obs-studio/build/CMakeFiles/CMakeError.log".
```

### Steps to Reproduce

install all recommended deps 
also install `sudo dnf in libxkbcommon-devel ` cause it's needed
then run `cmake -DENABLE_BROWSER=OFF -DENABLE_AJA=OFF ..`

### Anything else we should know?

yes please add .deb and rpm for beta's please makes testing alot easier linux users should never be third class

**Comment by RyzenDew** [comment]
also tried sudo dnf in `librist` and `librist-devel `both failed

**Comment by tytan652** [comment]
Add `-DENABLE_NEW_MPEGTS_OUTPUT=OFF` to disable native librist and srt output.

> yes please add .deb and rpm for beta's please makes testing alot easier linux users should never be third class

We only support Flatpak and Ubuntu 20.04 and 22.04 officially. The 28 beta will come soon on those.

**Comment by RyzenDew** [comment]
> 

ya i won't touch those dated OS sorry ubuntu is horrible for any type of use

**Comment by RyzenDew** [comment]
that worked

**Comment by msmafra** [comment]
> Add `-DENABLE_NEW_MPEGTS_OUTPUT=OFF` to disable native librist and srt output.
> 
> > yes please add .deb and rpm for beta's please makes testing alot easier linux users should never be third class
> 
> We only support Flatpak and Ubuntu 20.04 and 22.04 officially. The 28 beta will come soon on those.

Thanks! That worked.
