### ISSUE TITLE
There is no Game and win and desktop capture on version 28.0 of obs

### ISSUE THREAD

**Issue by FearowGaming** [obsproject/obs-studio#6949]
### Operating System Info

Windows 10

### Other OS

NA

### OBS Studio Version

28.0.0-beta1

### OBS Studio Version (Other)

NA i switched back to 27.2.4 

### OBS Studio Log URL

NA 

### OBS Studio Crash Log URL

NA

### Expected Behavior

when i started my stream today there was no game capture to capture my game screen

### Current Behavior

No Game Capture or win capture on obs v. 28.0.0

### Steps to Reproduce

1.
2.
3.
...

### Anything else we should know?

NA

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
