### ISSUE TITLE
SRV DNS Records do not work.

### ISSUE THREAD

**Issue by Sokoloft** [obsproject/obs-studio#6950]
### Operating System Info

Other

### Other OS

Debian 11 Bullseye/ Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/lH15et8x-P2pdFuohttps://obsproject.com/logs/lH15et8x-P2pdFuo

### Expected Behavior

Encoder output to nginx rtmp ingest.

### Current Behavior

Works, but only with a cname dns record. SRV records do not work.

### Steps to Reproduce

1. Install [this](https://github.com/JamiePhonic/rtmps-hls-server) docker image.

2. Use the [minimal settings](https://github.com/JamiePhonic/rtmps-hls-server/blob/master/conf/nginx_rtmp_minimal_no-stats.conf) nginx config. Commenting out everything pertaining to allow/denying IPs.

3. Have a server setup with a DNS SRV record pointing to port 1935 _http._tcp.rtmp.domain.name

4. Under obs settings < stream. Set service to custom and use a URL pertaining to your domain name. 
    Example= rtmp://rtmp.domain.name/live (live is the default application name in the nginx config)

5. Apply and try to go live. You will error out with the following:
![obs64_5cqtLCOy8x](https://user-images.githubusercontent.com/49052130/182942634-3f4e1043-2f19-4f9a-b9a7-939897d5780a.png)

### Anything else we should know?

Hello! 😄 

I troubleshooted this issue with a few people on discord that are way smarter than me. For a few hours. We've come to the conclusion that OBS does not support SRV DNS records. I have also found an old post of [someone on the OBS forums](https://obsproject.com/forum/threads/does-obs-recognize-srv-records-for-a-domain.108533/) having the same exact issue as me. It seems dead so I figured I'd bring the issue up here. For now I have it setup with a cname record which seems to work however it isn't quite what I wanted but oh well. 

Thank you very much to the OBS team that has developed this amazing software for the past years. I've used this off and on since 2016 and its always been rock solid! 💪 

I hope a solution can come for this issue, or at the very least bring it to the teams attention. 
Have a wonderful day! 😃

**Comment by notr1ch** [comment]
Is this expected to work? I didn't find any mention of SRV records in the RTMP specification.

**Comment by Sokoloft** [comment]
> Is this expected to work? I didn't find any mention of SRV records in the RTMP specification. Does other client software support them?

I'm honestly unsure. I will re-enable my SVR record and try with to use Larix Broadcaster as the encoder and see if that pushes to my test channel. I was unable to find the source documentation. Can you please link me what you're looking at? If that is the case then I'll make a post to nginx/the rtmp module. However I think the rtmp module isn't supported anymore? I'll have to look more into that and see if there is a maintainer if so.

**Comment by derrod** [comment]
This is a feature request, not a bug or issue, please post it on https://ideas.obsproject.com/ instead, thanks.
