### ISSUE TITLE
OBS cannot display the EVGA XR1's capture upon launch.

### ISSUE THREAD

**Issue by DaveKap** [obsproject/obs-studio#6953]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/EA0BxFCrhhMdyN09

### Expected Behavior

I expect OBS to properly display my EVGA XR1's output upon launch.

### Current Behavior

Upon launch, OBS displays a black screen for my EVGA XR1 device. I have to power cycle the device and then open up the device's source in order to properly obtain the device's display.

### Steps to Reproduce

1. Have an EVGA XR1 plugged in.
2. Start up OBS and switch to a scene where the EVGA XR1's source is displaying.
3. Notice the black screen.

### Anything else we should know?

This seems to have started happening after I updated the EVGA XR1's firmware.

**Comment by derrod** [comment]
You have multiple sources trying to use the same device, that won't work. If you need further assitance, please use our [support channels](https://obsproject.com/help) before opening any issues.

**Comment by DaveKap** [comment]
Thanks! I didn't realize how much cruft I was allowing to build in my scenes. I've now solved the problem!
