### ISSUE TITLE
OBS 27.2.4 green screen on capture card in preview window

### ISSUE THREAD

**Issue by PaddyMac** [obsproject/obs-studio#6954]
### Operating System Info

Other

### Other OS

FreeBSD

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/ZPfFlPWHUsKcQKIH

### Expected Behavior

When I start OBS, the preview window should correctly display the video from my capture card.

### Current Behavior

This is an intermittent error. Sometimes when I start OBS, everything works fine. Other times, when I start OBS, the preview window shows only green. This is fixed by going to the options for my source, which is an EVGA XR1 Lite, and switching it momentarily to my laptop's built-in webcam and then back to the XR1 Lite or by exiting OBS and restarting it. I have not encountered this issue on Windows or Linux.

### Steps to Reproduce

1. Start OBS on FreeBSD
2. Sometimes it works as expected. Sometimes it doesn't.

**Comment by kkartaltepe** [comment]
FreeBSD is not supported, consider filing a bug against your package manager for freebsd help or replicating this on linux.
