### ISSUE TITLE
Valorant hook not able to load

### ISSUE THREAD

**Issue by yongyouth7** [obsproject/obs-studio#6959]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.0-beta1

### OBS Studio Log URL

https://obsproject.com/logs/n3bWXMTv1zEE2xbv

### Expected Behavior

Capture Valorant game normally while using the Application Audio Capture (BETA) for audio

### Current Behavior

valorant unable to boot, even when I am in the game. As soon as i launch OBS Valorant hangs and shows black screen.

### Steps to Reproduce

1. Launch OBS BETA 28
2. Launch Valorant (interchangeable)

### Anything else we should know?

Genshin works fine, same with Desktop capture

**Comment by RytoEX** [comment]
I can confirm this on Windows 10 with OBS Studio 28.0.0-beta1.

**Comment by derrod** [comment]
The hook was updated in 28, perhaps this is an anti-cheat issue and Riot will need to whitelist the new version.

**Comment by RytoEX** [comment]
We can confirm that this has been fixed in OBS Studio 28.0.0 Beta 2 by https://github.com/obsproject/obs-studio/commit/86963f65d2b83de0616e16b87332dd1f1672387d. The issue seems to have been related to https://github.com/obsproject/obs-studio/commit/69ff026647b8f3e9a3183eec760e9047ba667520 (#5218).
