### ISSUE TITLE
[28.0.0-beta1] ScreenCaptureKit: status bar missing in display capture

### ISSUE THREAD

**Issue by dnaka91** [obsproject/obs-studio#6968]
### Operating System Info

macOS 12

### OBS Studio Version

28.0.0-beta1

### OBS Studio Log URL

https://obsproject.com/logs/YfeId7hiaktREmT0

### Expected Behavior

With display capture, OBS should capture the whole screen, including any system elements.

### Current Behavior

The applications on screen are all recorded, but the status bar is missing. Sometimes it comes up for a second, but disappears again. Also, at some point it was visible, but all dropdown menu from the menu items were not visible.

### Steps to Reproduce

1. Create a scene.
2. Add a "macOS Screen Capture" source with "Display Capture" setting.
3. (Eventually restart once).

### Anything else we should know?

The log probably says "modified" for the OBS version, but this is a local build from the current beta release, only removed ccache from the Brewfile, as it makes compilation faster for me, that's all.

**Comment by tehbasshunter** [comment]
From their discord:

`known issue due to a workaround to try and avoid certain bugs in 12.5. i believe we have a fix in the works, should hopefully be fixed in beta 2`

**Comment by dnaka91** [comment]
Thanks. Didn't find any issue related to it on GitHub, so I wasn't sure whether this is already known.

Will check for any upcoming commits and re-compile and test once some kind of fix lands.

**Comment by dnaka91** [comment]
Thanks, works like a charm 🚀
