### ISSUE TITLE
Obs makes computer lock up randomly

### ISSUE THREAD

**Issue by JOEYOCHO** [obsproject/obs-studio#6975]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.0-beta1

### OBS Studio Version (Other)

28.beta1

### OBS Studio Log URL

https://obsproject.com/logs/lKRZ7XHAXWT2UZhN

### Expected Behavior

to record fine

### Current Behavior

did not crash but when using hvec encoder makes computer lock up randomly and cause visual glitches also i think it might happen with the nvenc to

### Steps to Reproduce

1. change encoder to hvec after brand new install of new version 
2.
3.
...

### Anything else we should know?

i have a gtx 1060

**Comment by energizerfellow** [comment]
You're on both an Insider Preview build of Windows 11, plus a dev build of a Nvidia GPU driver. Running into periodic problems with these is a known issue and should be expected with such builds.

Please roll back to a standard release build of both Windows 11 and Nvidia GPU drivers, ideally Nvidia's Studio Driver, which is Nvidia-speak for public stable release.

**Comment by Fenrirthviti** [comment]
Preview builds and dev drivers are not officially supported. If this can be reproduced on release builds, please let us know on the Discord or Forums and we can take a closer look.
