### ISSUE TITLE
Bug: Content changes to text source are propagated from preview to program in studio mode

### ISSUE THREAD

**Issue by corche** [obsproject/obs-studio#6977]
### Operating System Info

Windows 11

### OBS Studio Version

27.2.4

### OBS Studio Log URL

Bugs found in OBS Grouping feature

### Expected Behavior

When you make TEXT into other sources and Gruop in Studio mode and activate duplicate sources, TEXT in the group should not be changed in the program even if it is changed in Preview.

### Current Behavior

In Studio mode, TEXT is changed to other sources and Gruop, and when duplicate sources are activated, TEXT in the group is changed from Preview to Program.

### Steps to Reproduce

1.Enable Studio Mode.
2.Create TEXT and group with other sources.
3.Enable the Duplicate Sources option.
4.When you change the TEXT in the Gruop in the Preview, the TEXT changes the same in the Program.

### Anything else we should know?

I used a translator to write down this issue. Therefore, please understand even if grammar or words feel strange.

**Comment by tuduweb** [comment]
Could you please record and upload a reproduce video.
Thanks.

**Comment by corche** [comment]
It's a video that shows how to make a bug
https://youtu.be/IbcUeTSoDKE

**Comment by tuduweb** [comment]
I can reproduce it in obs27/28.

**Comment by PatTheMav** [comment]
Issue is independent of the grouping feature, when the contents of a text source are changed in the preview, the change is also propagated to the program, which is not expected behaviour.

**Comment by gxalpha** [comment]
This is currently as designed.
Enable "Duplicate Sources" in Studio Mode to have settings not propagate immediately.
<img width="553" alt="image" src="https://user-images.githubusercontent.com/59806498/214682071-98512bf7-b770-4950-92eb-2a1981e64bf0.png">
