### ISSUE TITLE
Screen sharing of OBS Application in Studio Mode shares the preview instead of program.

### ISSUE THREAD

**Issue by SuperZooper3** [obsproject/obs-studio#6979]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/7F8qWcRjI5pXj36d

### Expected Behavior

Expected a screen share (Discord) of the OBS application to grab the program feed in studio mode and pass that as the screen share. It would be nice if this was changed, or added as a setting.

### Current Behavior

OBS only screen shares the preview window.

### Steps to Reproduce

1. Open any obs scenes and turn on studio mode
2. Have a different scene active in the preview and program windows
3. Screen share the obs window and not which scene is being shared.

**Comment by kkartaltepe** [comment]
We do not maintain discord, please file bugs with their screen capture to discord.
