### ISSUE TITLE
FFmpeg output path "browse" button broken

### ISSUE THREAD

**Issue by Holy13Gaming** [obsproject/obs-studio#6986]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.0-beta1

### OBS Studio Log URL

https://obsproject.com/logs/FJY_dX1vcE9NFk13

### Expected Behavior

Browse button in FFmpeg video encoder settings should be there.

### Current Behavior

If you use the FFmpeg encoder and set it up for the first time, you can't set the output path via the "browse" button, because it's just not there. (see screenshot)
![image](https://user-images.githubusercontent.com/110762451/183281850-386ffc90-31a7-4118-ab26-16598689204c.png)

copy and pasting the path (like I did) doesn't work either. It just keeps recording to: "C:\Users\USER\Videos\OBS"
You'd have to change the output to URL first and then back to Path for the browse button to show up again

### Steps to Reproduce

1.
2.
3.
...
just open obs and check. confirmed in official obs discord

**Comment by WizardCM** [comment]
After some basic testing confirming the issue, the entire field/button area is using the "Output to URL" widget. This is why populating the box doesn't work, as it's mapped to the wrong field.

Switching to Output to File & back restores the correct behaviour.
