### ISSUE TITLE
No pop-up when hovering over or clicking in '?' buttons

### ISSUE THREAD

**Issue by smitdylan2001** [obsproject/obs-studio#6989]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.0-beta1

### OBS Studio Log URL

https://obsproject.com/logs/sA2DEfn1zphmJCxf

### Expected Behavior

Get more info on Look-ahead or Phycho Visual Tuning when hovering over or clicking on the ? button next to them

### Current Behavior

Nothing happens

### Steps to Reproduce

1. Start OBS 28 beta1
2. Go to Output settings
3. Hover over ? buttons

### Anything else we should know?

Happens in both streaming and recording tabs

**Comment by WizardCM** [comment]
I can't confirm this. It can take up to 2 seconds for the tooltip to appear.

![image](https://user-images.githubusercontent.com/941350/183288525-6334cffd-0333-4b84-8417-25a1ca82fb8a.png)

**Comment by MattyFresh68** [comment]
![image](https://user-images.githubusercontent.com/66339760/183288930-ef041eb4-e38a-4e4a-8b7f-27aa7a2c14b5.png)

I am getting the tooltips as well

**Comment by smitdylan2001** [comment]
It had to do with impatience, if I click the button before the tooltip appears the tooltip never comes.  (or if you spam click it)
When I do not click on it it does work properly
Just found this out. I personally would prefer having the tooltip always appear when clicked on the button, but that's personal preference

**Comment by RytoEX** [comment]
Once a control has been clicked on, the tooltip will only activate if the cursor has been moved. I don't think this is behavior that we control. My initial thought is that this is just Qt behavior, though I would have to investigate further to be more certain.

At the very least, this is not new/unique to OBS Studio 28.0.0-beta1. This also occurs in 27.2.4, and we have not, to my knowledge, done anything to change the behavior.

**Comment by smitdylan2001** [comment]
Understandable, I am also guessing this is a Qt behaviour. Just noticed and thought to open an issue so people can decide if it's worth looking into

**Comment by tuduweb** [comment]
I reproduce this and I find that sometimes happen.

**Comment by tuduweb** [comment]
I reproduce this and I find that sometimes happen.

**Comment by RytoEX** [comment]
I've checked in several other applications and found that most of them do not show a tooltip after a mouse click event has occurred and the cursor position has not changed. The only exceptions were where the element itself changed after being clicked. I do not think this is a bug that we can address. I think it is simply working as designed by Qt. Someone else can reopen this if they think I'm mistaken.
