### ISSUE TITLE
Typo in the remux completed alert 

### ISSUE THREAD

**Issue by CodeCraftPlugin** [obsproject/obs-studio#6993]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.0-beta1

### OBS Studio Log URL

https://obsproject.com/logs/t6eVC-WEJ9vRvzlo

### Expected Behavior

there is a typo in the remux tab once the remux is finished 
it should show this
![image](https://user-images.githubusercontent.com/86466022/183302787-0adf8fbd-6635-4027-8a39-f9b0a3ea04a3.png)

### Current Behavior

this is what is shown 
![image](https://user-images.githubusercontent.com/86466022/183302745-7a461fa8-5f69-43af-a508-101fc661117c.png)t

### Steps to Reproduce

click on the remux tab and select the remux 
then select a file and click remux after 
that the remux complete should appear 
it does appear but 
![image](https://user-images.githubusercontent.com/86466022/183302745-7a461fa8-5f69-43af-a508-101fc661117c.png)

**Comment by RytoEX** [comment]
These strings look identical to me. What is the typo?

**Comment by CodeCraftPlugin** [comment]
the ed

**Comment by CodeCraftPlugin** [comment]
it has a space

**Comment by pkupper** [comment]
I don't think there is a space. But the kerning is really bad. Either caused by the font or the text renderer.

**Comment by RytoEX** [comment]
> I don't think there is a space. But the kerning is really bad. Either caused by the font or the text renderer.

Indeed. The string from the locale file is "Recording remuxed". There is no space in the string itself. This is just a kerning/rendering issue. I'm not sure there's anything we can do about that, currently.
