### ISSUE TITLE
The color format displays errors in Chinese language

### ISSUE THREAD

**Issue by Danjuanlab** [obsproject/obs-studio#6999]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.0-beta1

### OBS Studio Log URL

https://obsproject.com/logs/SgcaXj3DD3OWmopU

### Expected Behavior

The color mode label is as in the English language

### Current Behavior

![AA](https://user-images.githubusercontent.com/42509669/183556583-da8b9ac0-b88f-40e7-8a3a-19a17c89d24c.jpg)
![BB](https://user-images.githubusercontent.com/42509669/183556591-0c62e54a-3f49-40f9-a5e9-42c5df4371ae.jpg)

### Steps to Reproduce

1.select Chinese language
2.check color mode
3.
...

**Comment by RytoEX** [comment]
The error here is that the Chinese translation relied on Crowdin's Translation Memory feature and it incorrectly used "NV12" as the translation for "P010". I've changed this on Crowdin, where we handle our localization.
