### ISSUE TITLE
Unable build obs-studio without obs-browser

### ISSUE THREAD

**Issue by NTMan** [obsproject/obs-studio#7025]
### Operating System Info

Other

### Other OS

Fedora Linux

### OBS Studio Version

28.0.0-beta1

### Expected Behavior

Build obs-studio without errors.

### Current Behavior

When I build obs-studio without submodule obs-browser, compilation ended with error message:
```
-- OBS:    -        obs-vst uses bundled VST headers
-- OBS:  ENABLED    obs-vst
CMake Error at cmake/Modules/ObsHelpers.cmake:452 (message):
  OBS: obs-browser submodule not available.
Call Stack (most recent call first):
  plugins/CMakeLists.txt:11 (obs_status)
  plugins/CMakeLists.txt:64 (check_obs_browser)
```
[build-wo-submodule-obs-browser.log](https://github.com/obsproject/obs-studio/files/9300993/build-wo-submodule-obs-browser.log)

When I add  submodule obs-browser and build again, compilation ended with error message:
```
-- OBS:    -        obs-vst uses bundled VST headers
-- OBS:  ENABLED    obs-vst
-- OBS:  DISABLED   obs-browser
CMake Warning at plugins/obs-browser/CMakeLists.txt:10 (message):
  Browser source support is not enabled by default - please switch
  ENABLE_BROWSER to ON and specify CEF_ROOT_DIR to enable this functionality.


CMake Error at cmake/Modules/ObsHelpers.cmake:452 (message):
  OBS: obs-websocket submodule not available.
Call Stack (most recent call first):
  plugins/CMakeLists.txt:88 (obs_status)
```
[build-with-submodule-obs-browser.log](https://github.com/obsproject/obs-studio/files/9300992/build-with-submodule-obs-browser.log)

but I don't wanna ENABLE_BROWSER to ON because I use wayland and obs-browser support only X11 environment.

**Comment by tytan652** [comment]
Initialising the submodules is a requirement, you can use `−DENABLE_BROWSER=OFF` afterward.

**Comment by NTMan** [comment]
> Initialising/cloning the submodules is a requirement, you can use `−DENABLE_BROWSER=OFF` afterward.

with submodule obs-browser compilation ended with error:
```
CMake Warning at plugins/obs-browser/CMakeLists.txt:10 (message):
  Browser source support is not enabled by default - please switch
  ENABLE_BROWSER to ON and specify CEF_ROOT_DIR to enable this functionality.
```

**Comment by tytan652** [comment]
Could you avoid mixing up warnings and errors.

```
CMake Error at cmake/Modules/ObsHelpers.cmake:452 (message):
  OBS: obs-websocket submodule not available.
```
Is the error.
