### ISSUE TITLE
Unable to build DEBian package using provided instructions

### ISSUE THREAD

**Issue by iam-TJ** [obsproject/obs-studio#7027]
### Operating System Info

Other

### Other OS

Debian Bullseye

### OBS Studio Version

Git

### OBS Studio Log URL

None

### OBS Studio Crash Log URL

None

### Expected Behavior

Be able to successfully build a debian package by following the instructions.

### Current Behavior

Attempting to do a custom Debian build following instructions at https://obsproject.com/wiki/build-instructions-for-linux results in a series of increasingly opaque failures.

First:  "Option B: Custom Debian builds" > "7. Create Debian package" results in:
```
$ cmake --package "${build_dir}"
CMake Error: Unknown argument --package
```
Secondly, after discovering `CI/linux/03_package_obs.sh` tried using that:
```
$ CI/linux/03_package_obs.sh --verbose --build-dir "${build_dir}" |& tee /tmp/obs-debian.package.log                                                      
  + Fetch OBS tags...
[OBS-Studio] Create Linux debian package                                                                         
  + Package OBS...
...
  + ERROR No suitable OBS debian package generated
```
This due to `${build_dir}/CPackConfig.cmake` having:
```
set(CPACK_BINARY_DEB "OFF")
```
So, change that to`"ON"` and retry - same result. Spotted another key:
```
set(CPACK_GENERATOR "STGZ;TGZ;TZ")
```
aha - let's add `DEB` to that!
```
set(CPACK_GENERATOR "DEB;STGZ;TGZ;TZ")
```
Progress... but!
```
$ CI/linux/03_package_obs.sh --verbose --build-dir "${build_dir}" |& tee /tmp/obs-debian.package.log
  + Fetch OBS tags...
[OBS-Studio] Create Linux debian package
  + Package OBS...
[0/1] cd /srv/NAS/Sunny/SourceCode/builds/obs-studio-debian && /usr/local/bin/cpack --config ./CPackConfig.cmake
CPack: Create package using DEB
CPack: Install projects
CPack: - Install project: obs-studio []
CPack: Create package
-- CPACK_DEBIAN_PACKAGE_DEPENDS not set, the package will have no dependencies.
CPack: - package: /srv/NAS/Sunny/SourceCode/builds/obs-studio-debian/obs-studio-28.0.0-9-Linux.deb generated.
...
```
So, how is `CPACK_DEBIAN_PACKAGE_DEPENDS` supposed to be set?

There is only one occurrence of it and that doesn't appear to be processed:
```
$ grep -rn CPACK_DEBIAN_PACKAGE_DEPENDS
cmake/external/ObsPluginHelpers.cmake:546:      set(CPACK_DEBIAN_PACKAGE_DEPENDS
```

### Steps to Reproduce

Follow the instructions as described above.

### Anything else we should know?

Yes; links to access the Discord server result in "Invite Invalid" and Discord goes around in circles driving up the frustration level.

On trying to register Discord independently I then hit a verification loop that seems insurmountable for years by many many Discord users; see https://support.discord.com/hc/en-us/community/posts/360057959511-Fix-Phone-Verification

All-in-all a very developer/user-hostile service creating barriers to developers like me that have the experience to contribute but are not prepared to waste time on artificial proprietary obstacles!

**Comment by PatTheMav** [comment]
The documentation is unfortunately not correct - packaging can be invoked either via

* `cmake --build <YOUR_BUILD_DIR> --target package`, or
* `cpack` in the build directory

By default this will generate a DEB package if obs-studio is not configured to be compiled as a portable app (`LINUX_PORTABLE` is set to `OFF`), otherwise just `.sh`, `.Z`, and `.tgz` will be generated:

```
CPack: Create package using DEB
CPack: Install projects
CPack: - Install project: obs-studio []
CPack: Create package
CPackDeb: - Generating dependency list
CPack: - package: /home/ptm/GitHub/obs-studio/build_arm64/obs-studio-28.0.0-17-Linux.deb generated.
```

@tytan652 could you update the wiki accordingly?

**Comment by PatTheMav** [comment]
Documentation has been updated to use the correct command for packaging.
