### ISSUE TITLE
Failed to load channel information for Twitch

### ISSUE THREAD

**Issue by itsonlyMiRE** [obsproject/obs-studio#7044]
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/Gu5ClX8r3kotUh3B

### Expected Behavior

Sign-in to Twitch successful, modules like chat and stream info loaded successfully.

### Current Behavior

dialog window: "Loading channel information for Twitch, please wait....", followed by an error dialog window stating "Failed to load channel information for Twitch [newline] Failed to get text from remote: Resolving timed out after 5000 milliseconds"

### Steps to Reproduce

1. Connect Account (recommended)
2. Sign in with Twitch creds and enter MFA code
3. Wait for error dialog

### Anything else we should know?

I see a lot of info stating that this is supposed to be fixed by 27.2 but I am on version 27.2.4 and have been for a while and this issue still occurs very often (around 90% of the time of launching OBS). I have also tried removing the OBS Studio connection from my Twitch connections and re-authorizing, does not work.

**Comment by tt2468** [comment]
Looks like you have a bad or unreliable DNS server configured on your system. Please use our support channels like [the Discord server](https://discord.gg/obsproject) before submitting bug reports.
