### ISSUE TITLE
texture-amf: RX 4/500 series encoder stall on fullscreen game capture

### ISSUE THREAD

**Issue by flaeri** [obsproject/obs-studio#7047]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.0-beta2

### OBS Studio Log URL

https://obsproject.com/logs/unRaFk9WYpVEzmyt

### Expected Behavior

When recording with the new AMD implementation you should be able to alt+tab without the encoder stalling/crashing.

### Current Behavior

When recording with the new AMD implementation the encoder will silently stall/crash when you alt+tab on exclusive fullscreen games.

### Steps to Reproduce

Seems to be a little bit inconsistent, so it might require a few tries.

1. Use an RX 4/500 series GPU
2. Setup a 1080p60 canvas and output
3. Start streaming/recording using simple mode, with the AMF HW h264 encoder
4. Have game capture set to seemingly any exclusive fullscreen game
5. Alt+tab a few times
6. Try to stop the record/stream
7. Observe hang, may need to kill OBS in task manager

### Anything else we should know?

* Multiple (3-4) reports on RX 4/500 series
* Multiple drivers tested, including 22.7.1, 22.5.1
* Users tried the "speed" preset, nothing in the custom input
* Users tried disabling encoder extras, like VBAQ, RateControlPreAnalysis
* User report it does not happen when context switching without game capture running
* Users reports stall on OpenGL, dx11 and dx12
* Users have tried with/without anti cheat compat (one user initially assessed it might help), but still hangs for others
* Users report issue on both beta 1 and 2.

More logs from more users:
https://obsproject.com/logs/bfiEZDnJBL-lO6N4
https://obsproject.com/logs/i7N_GmzU-uTywF2I

**Comment by flaeri** [comment]
Two users report the following:

Neither can cause the issue to happen if they force `fallback-amf-h264` via using "rescale output" with a different resolution.
We tested with the same resolution set in video > output (texture sharing), where as rescale output does not (not texture sharing, amf-fallback).

This is hopefully a big point towards what could be the issue. Seeing as the some users have claimed the old implementation did not have this issue, and that didnt have texture sharing, it would seem to follow that it would be related, as we now have several points in that direction.

**Comment by cs9kc** [comment]
Repro using an RX 580 on a fresh Windows 10 install, encoding a (cpu-decoded) video file being played back from a media source.  No other 3D/graphics programs were running at the time.

https://obsproject.com/logs/tEAQZWUIUU_5maj9
![task manager](https://user-images.githubusercontent.com/64284066/184511909-8bec9eb4-ec30-416d-8c15-4eb83d9a9752.png)

**Comment by gutko** [comment]
hang when pressing stop recording
https://obsproject.com/logs/dDV5Qjd42hi4LZbx

**Comment by flaeri** [comment]
@gutko This is a separate issue actually, hehe.
Seems that when you tried to record with a wonky resolution `1904x1071` the encoder fails. Please use a more standard resolution like 1270x720, and try again :)

It's a bit unfortunate that it hangs, it might be worth to submit a separate issue.

**Comment by Johl7** [comment]
Me and another user tried extensively the other day... we couldnt make the encoder stall while using rescale, i also retried it yesterday... no stalls.

**Comment by Johl7** [comment]
The issue can also be repro when setting in a new source into a scene, ex(inserting a window cap with a browser page). Thou after done once it can be inconsistent to repro..

**Comment by kjzl** [comment]
Can reproduce this too - RX 580, 22.7.1 Drivers, Win11 https://obsproject.com/logs/gHUKwLPk0KNWWgKj

**Comment by flaeri** [comment]
Resolved by 6dc8897e7959d3f6149c0d6ac00ad42d02243edc.
