### ISSUE TITLE
[macOS] Dark theme breaks dock resizing

### ISSUE THREAD

**Issue by HiroiSekai** [obsproject/obs-studio#7050]
### Operating System Info

macOS 12

### OBS Studio Version

28.0.0-beta2

### OBS Studio Log URL

https://obsproject.com/logs/x0p7v-zh3tdQxouN

### Expected Behavior

**Dock Placement/Resizing**
Understandably in progress, the expected behaviour is to have the pull handles respond every time to resizing and relocating requests. Unsure if this is still not implemented in all themes, but the Yami theme does this more accurately, while the other themes do not. From my [previously opened ticket](https://github.com/obsproject/obs-studio/issues/6300), it appears the switch to Qt6 will remedy this, just pointing out the issue is currently still here.

### Current Behavior

**Dock Placement/Resizing**
In the current beta, I use the Dark theme as the Stream controls dock is smaller and allows me to shrink the footer area down for more space above. However, at least on the Dark theme, it is currently still very spotty with moving and resizing the docks. I assume this is currently not adapted to the new upcoming Qt6, and that's the issue. 

Regardless, the handles to resize the docks don't react over 50% of the time, and sometimes, if you accidentally undock something large, it fills up the screen with the tiny minimize/close buttons obscured off screen. Only way to fix this is to either close OBS entirely, or to reset the UI and redo all of the specific placement/resizing of docks.

### Steps to Reproduce

- Set the theme to Dark.
- Set some docks and try to pull the handles to resize them. (Resizing issue)
- After setting some docks, pull one out to undock it. Specifically in this case, the Stream Information dock. (Obstruction issue)

**Comment by feetstv** [comment]
This would be better as individual bugs so they can be closed one-by-one.

**Comment by HiroiSekai** [comment]
For a beta, would you prefer it that way? I posted it this way in expectation that there will be bugs, but also newly established bugs and other unexpected usability issues as it progresses. I kind of thought that just having a list of what I find as a bug can just be replied to here in one thread if it's being worked on, is not feasible, or is user error, and any actually fixed bugs show up in a future beta's changelog. I myself can know to not repeat the same bug in a different list for the next beta release if a dev says that it won't be fixed for 28.0 yet.

If you prefer, I can do it separately, but I can preemptively say that I'll be opening a lot more tickets and repeating the same base information for each, and for every single beta release with new bugs I'll have to open a separate ticket for each different issue instead. If that is preferred for the devs though, I can do it that way as well. Just hoping to keep it easier for both sides during the beta process.

**Comment by feetstv** [comment]
Having one bug per issue is how the GitHub Issues feature is intended to be used, beta or not.

I think it would be useful if you discuss these in the #beta-testing channel on the Discord support server before posting them here.

**Comment by HiroiSekai** [comment]
Noted, I'll split these up going forward, no problem.

Regarding the Discord, I've sadly filled Discord's annoying limitation of how many servers you can join at once. The joys of being in multiple Twitch speedrunning communities.

**Comment by gxalpha** [comment]
To clarify, this is not something that needs to be "adapted" for Qt 6, it's just broken. The update to Qt 6 fixed other issues with docks, but this one wasn't one of them.
We know that something is up with what we're doing in Dark but not Yami (or the other way around), but that is it. As we're now using Yami as the standard theme and consider Dark deprecated, this is unlikely to get fixed (considering that it wasn't fixed in the last 5 years). I'll leave this issue open for now, but the fix for this issue is "Don't use Dark".
