### ISSUE TITLE
[28.0 Beta 2, macOS] Show Cursor

### ISSUE THREAD

**Issue by HiroiSekai** [obsproject/obs-studio#7053]
### Operating System Info

macOS 12

### OBS Studio Version

28.0.0-beta2

### OBS Studio Log URL

https://obsproject.com/logs/PMQu3gQVXt7dkohQ

### Expected Behavior

Currently, the Show Cursor toggle only appears to mirror your cursor on top of OBS Studio. It should only limit the cursor's appearance to the specific window or application you have selected.

### Current Behavior

Currently, whenever you toggle Show Cursor, it will just mirror your cursor from within the OBS window, instead of limiting it to what your cursor does on a specific window or application.

### Steps to Reproduce

- Add a macOS Screen Capture source.
- Select either Application or Window capture.
- Toggle on Show Cursor.

**Comment by gxalpha** [comment]
Do I understand correctly that "The cursor is on another window that is in front of the one currently being captured, so it should not be shown in OBS"?

**Comment by HiroiSekai** [comment]
Sorry, it's really difficult to explain it with text. I recorded a short screen capture to visualize what is happening. (sorry about the quality, there's a 10MB limit)

https://user-images.githubusercontent.com/44986450/184557543-b0d22d83-c3fe-4417-8141-b5e3d908ccd5.mp4

In the first half, you can see that with Application Capture, you can see that no matter what application I select, if it's not OBS Studio, it just shows a blank screen with the OBS Studio menu bar mirrored. In the second half I moved the cursor around to show that the capture just shows the cursor as it appears on OBS Studio.

Window Capture to an extent does display individual tabs correctly, but the "Show Cursor" option does the same thing. It previews capturing the selected window, but the cursor just overlays on top as you move around OBS Studio. The cursor should only appear when I am interacting with the selected window/application.

**Comment by gxalpha** [comment]
This is expected. Also it's something we can't do anything about, as we just tell macOS to give us a picture with (or without) cursor and show the result.
If you think that this is wrong behaviour, please send your feedback to Apple (for example at https://feedbackassistant.apple.com)
