### ISSUE TITLE
[28.0 Beta 2, macOS] Elgato Stream Deck

### ISSUE THREAD

**Issue by HiroiSekai** [obsproject/obs-studio#7054]
### Operating System Info

macOS 12

### OBS Studio Version

28.0.0-beta2

### OBS Studio Log URL

https://obsproject.com/logs/NZVNFqwLv300Pf34

### Expected Behavior

This is a simple one, and I believe it's just because Stream Deck's OBS plugin it is supposed to install during setup of its proprietary app is not installing because this is an OBS beta. Currently however, the expected behaviour is that when I add a macro that connects to OBS from Elgato's Stream Deck app, it should just automatically see my setup so I can choose what to affect.

### Current Behavior

Currently, when you add something like the Scene macro for OBS from the Stream Deck app, it just pops up a "Waiting For OBS" spinning wheel and stays there forever.

### Steps to Reproduce

- If possible, plug in an Elgato Stream Deck into a Mac. 
- Launch Elgato's proprietary Stream Deck software, which is required to activate and utilize the Stream Deck itself. 
- In the Stream Deck software, add an OBS "Scene" macro to get the infinitely loading "Waiting For OBS" error.

**Comment by gxalpha** [comment]
The stream deck plugin isn’t compatible with M1 native OBS yet. This needs to be fixed by Elgato, please contact them instead.

**Comment by CarrotCodes** [comment]
If anyone else is looking for builds while Elgato are working on support, I've ported their plugin to use `obs-plugintemplate`, for OBS 28 support, and have builds available in the releases on this repo: https://github.com/CarrotCodes/streamdeck-obs

**Comment by RytoEX** [comment]
> If anyone else is looking for builds while Elgato are working on support, I've ported their plugin to use `obs-plugintemplate`, for OBS 28 support, and have builds available in the releases on this repo: https://github.com/CarrotCodes/streamdeck-obs

For the record, we are in touch with Elgato, and they are working on updating the Stream Deck plugin.

**Comment by HiroiSekai** [comment]
Thank you everyone for the info and link!
