### ISSUE TITLE
OBS Crashes on pausing recording

### ISSUE THREAD

**Issue by ItzMeRainbow** [obsproject/obs-studio#7059]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.0-beta2

### OBS Studio Log URL

https://obsproject.com/logs/HX_yLbUOTzR3f8J-

### OBS Studio Crash Log URL

https://obsproject.com/logs/dCRqiZ2DQ2g1xtSD

### Expected Behavior

The video to pause

### Current Behavior

obs crashes

### Steps to Reproduce

1.Start a recording
2.Pause the recording
3.obs crashes
...

### Anything else we should know?

Specs:
Processor	AMD FX(tm)-8320 Eight-Core Processor              3.50 GHz
GPU: AMD Radeon RX 570
Installed RAM	16.0 GB
System type	64-bit operating system, x64-based processor

**Comment by ItzMeRainbow** [comment]
video: https://drive.google.com/file/d/1P1GPzohwTAE-t1lwIvvkrmeuSdIIVe6U/view?usp=sharing

**Comment by tytan652** [comment]
Already fixed by #7040 for the next beta/RC.
