### ISSUE TITLE
[28.0 Beta 2] Screen captures include the macOS notification center and OBS window.

### ISSUE THREAD

**Issue by BlueSkyAnimal** [obsproject/obs-studio#7060]
### Operating System Info

macOS 12

### OBS Studio Version

28.0.0-beta2

### OBS Studio Log URL

https://obsproject.com/logs/-YgiYbd8BdLiUPv6

### Expected Behavior

OBS window should not be recorded with the benefit of macOS' ScreenCaptureKit.
And the notification center should not be recorded in a screen capture as well.

### Current Behavior

The preview screen on the OBS window shows that both the Notification Center and the OBS window itself are recorded.

### Steps to Reproduce

1. Run OBS and add "macOS Screen Capture" to the source
2. Click the clock on the right edge of the macOS menu bar to display the Notification Center
3. The preview screen on the OBS window shows that both the Notification Center and the OBS window itself are recorded.

**Comment by gxalpha** [comment]
This is not a bug, it’s called Display Capture after all.
If you think what you mentioned should be added to OBS, please write a feature requests on https://ideas.obsproject.com
