### ISSUE TITLE
[28.0 Beta 2] Some menu bar items are not displayed in macOS screen capture

### ISSUE THREAD

**Issue by BlueSkyAnimal** [obsproject/obs-studio#7061]
### Operating System Info

macOS 12

### OBS Studio Version

28.0.0-beta2

### OBS Studio Log URL

https://obsproject.com/logs/-YgiYbd8BdLiUPv6

### Expected Behavior

All items displayed in the macOS menu bar should be reflected correctly in the screen capture.

### Current Behavior

Shortcuts.app, battery indicator, control center icon and clock in macOS menu bar are not recorded in screen capture.

### Steps to Reproduce

1. Launch OBS and add macOS Screen Capture to the source
2. Some menu bar items are not displayed correctly on the OBS preview screen

**Comment by gxalpha** [comment]
This is an expected result of a workaround we have to do because of a bug in macOS 12.5. There is nothing we can do against it (or else it wouldn’t capture at all).
It should be fine on macOS 13. If Apple fixes the bug in 12.6 we will of course also disable the workaround there.
