### ISSUE TITLE
28 Beta Flatpak doesn't launch correctly via .desktop file

### ISSUE THREAD

**Issue by MIchael-Kelly7** [obsproject/obs-studio#7070]
### Operating System Info

Other

### Other OS

Fedora 36

### OBS Studio Version

28.0.0-beta2

### OBS Studio Log URL

https://obsproject.com/logs/4PNy6Qu0TuGPMTaO

### Expected Behavior

OBS to open successfully when launching via the .desktop file either via the app menu or pinned icon on the taskbar.

Running flatpak run com.obsproject.Studio will actually make this successful

### Current Behavior

OBS icon appears in the taskbar at the bottom then disappears. Trying to launch obs again will note that obs is already running and asks if you want to launch again. If you do, OBS comes up (two instances running at this point, one in the background)

### Steps to Reproduce

1. Launch OBS using the .desktop file via app menu or pinned to taskbar
2. OBS will try to launch, but then appear to fail
3. Trying to launch OBS again will note it's already running, clicking launch anyway will cause it to launch.
...

### Anything else we should know?

Running flatpak run com.obsproject.Studio will actually make this successful.

I checked the .desktop file, I do not see anything out the ordinary there. I have rebooted a few times.

**Comment by kkartaltepe** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

**Comment by MIchael-Kelly7** [comment]
> We do not use GitHub Issues for support questions.
> 
> Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

I believe this to be a bug. The flatpak version of 27 did not do this. Only 28 beta. This is not expected behavior.

**Comment by tytan652** [comment]
> I believe this to be a bug. The flatpak version of 27 did not do this. Only 28 beta. This is not expected behavior.

Yes since beta 2 there is a bug (#7095) not related at all to the desktop file which is fixed by #7129.
