### ISSUE TITLE
NVENC error

### ISSUE THREAD

**Issue by xCoBeTHuKx** [obsproject/obs-studio#7100]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.0-beta2

### OBS Studio Log URL

https://obsproject.com/logs/sjkvodFKlAyL9IGn

### Expected Behavior

I can not stream with that settings

![2022-08-16 193647](https://user-images.githubusercontent.com/65200284/184943466-e5f3d505-a1d1-4423-acbd-2b895920fe3a.jpg)

![2022-08-16 193511](https://user-images.githubusercontent.com/65200284/184943242-6a51f1cc-58c1-4727-9ddd-be43e372d4a3.jpg)

### Current Behavior

Impossible to stream with HDR settings

### Steps to Reproduce

1.
2.
3.
...

**Comment by xCoBeTHuKx** [comment]
Use RTX 2070 Super as GPU

**Comment by derrod** [comment]
You will need to use the NVENC HEVC encoder for HDR, this is not a bug.
