### ISSUE TITLE
PipeWire share individual display keeps blank except mouse pointer

### ISSUE THREAD

**Issue by VortexAcherontic** [obsproject/obs-studio#7108]
### Operating System Info

Other

### Other OS

openSUSE Tumbleweed

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/BiISQd9LNZcQKoz7

### Expected Behavior

I expected the PipeWire capture source to preview and actually capture the selected screen and not just the mouse pointer.

### Current Behavior

You can select if you want to share an individual screen or the entire desktop but there are no previews shown.  

After the unsuccessful selection of an individual screen you can also not switch the screen to be shown as Pipe Wire stops with `warning: [pipewire] Failed to start screencast, denied or cancelled by user`

No matter if it is an single screen or the entire desktop.

If you restart OBS Studio you have one chance to at least share the entire desktop.  
This one works (Excpet of massive performance issues) but you will not be able to switch to an individual screen afterwards or back to the full desktop capture due to the same warning: "warning: [pipewire] Failed to start screencast, denied or cancelled by user"

However if you're still in the not "warning: [pipewire] Failed to start screencast, denied or cancelled by user" state the mouse pointer is at least captured on the correct display.

### Steps to Reproduce

1. Run OBS Studio on Wayland (maybe nVidia is required too here)
2. Try to share an individual screen
3. No sharing

or:

1. Run OBS Studio on Wayland (maybe nVidia is required too here)
2. Try share the entire desktop
4. Switch the to be shared screen to an individual screen
5. No sharing afterwards and no switching back

### Anything else we should know?

As mentioned in the steps to reproduce I feel to mention I run on:

Operating System: openSUSE Tumbleweed 20220814
KDE Plasma Version: 5.25.4
KDE Frameworks Version: 5.96.0
Qt Version: 5.15.5
Kernel Version: 5.19.1-1-default (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 1800X Eight-Core Processor
Memory: 15.5 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3080/PCIe/SSE2
Graphics Driver Version: 515.65.01
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7A33
System Version: 2.0

![Screen share selection screen](https://user-images.githubusercontent.com/11244092/184993065-8c51687b-9d5b-4e52-9d3a-451a807149d5.png)

![Screen preview screen after selecting a display, notice the mouse pointer](https://user-images.githubusercontent.com/11244092/184993146-00c6bc07-de95-4d0c-8e30-7ca4ba847f8f.png)

![Scene preview, also notice the mouse pointer](https://user-images.githubusercontent.com/11244092/184993215-2b4c9923-bf08-48ab-8971-9eec5ba17dda.png)

**Comment by kkartaltepe** [comment]
nvidia on wayland is not supported.
