### ISSUE TITLE
"Cross-Record" ? Not sure.

### ISSUE THREAD

**Issue by HideakiAtsuyo** [obsproject/obs-studio#7120]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/5wzsd4hfbbJnyRQR

### Expected Behavior

Game Capture to capture the game

### Current Behavior

Black screen, every single window that I select in "game capture" mode are black (even with both on GPU1, but for example a Windows capture let me capture something on GPU0 (example: Discord))

### Steps to Reproduce

1. Create a Game Capture Source
2. Settings for it: https://i.imgur.com/hoDiN8T.png & https://i.imgur.com/FNteXYd.png
3. Enjoy the black screen

### Anything else we should know?

GPU0 = Chipset graphic from my CPU
GPU1 = GTX 1650

I can record something on GPU0 while having OBS on GPU1 if it's not a Game Capture and even with both on GPU1 Game Capture doesn't work for me 😔

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request, and we are not currently accepting support requests on GitHub Discussions. Make sure you read any [pinned posts](https://github.com/obsproject/obs-studio/discussions/5206) on discussion boards before opening a new discussion. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for further assistance.

Thank you!
