### ISSUE TITLE
x264 Crash occurring even after many troubleshooting steps taken

### ISSUE THREAD

**Issue by Marstead** [obsproject/obs-studio#7138]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/N8Hc2MOgUbrYVo7W

### OBS Studio Crash Log URL

https://obsproject.com/logs/KAwU6Zgzi4aYWIVq

### Expected Behavior

I've been streaming with OBS for 7+ years without any issues or crashes. My stream schedule is 4 hours per weekday. Up until recently I have been able to stream and record with no crashes.

### Current Behavior

Since the most recent OBS Updates, OBS has been crashing only while livestreaming. It tends to only crash once per 4-hour period and at a random interval.

### Steps to Reproduce

I am unable to reliably reproduce this crash; it occurs about once a week or month. It does only occur during livestreaming (not simply recording) and does not seem to connect to any events in the stream.

### Anything else we should know?

I sought extensive help on the OBS Discord for this before raising a ticket. Here are the steps they helped me with, and I still crashed afterward:

1) Updating all Chipset drivers
2) Updating the BIOS
3) Uninstalling applications that share data across other PCs on my network
4) Running SFC /SCANNOW and DISM /Online /Cleanup-Image /CheckHealth
5) I wasn't running any overclocking but I disabled the CPU Boost in my BIOS. RAM is running at default speeds.
6) It was recommended I keep an eye on CPU Thermals, I've been running CPUTemp with logging and during my crash Wednesday I was at 76F, still haven't exceed 81F since I started testing
7) Made all fixes in a [linked comment from @energizerfellow](https://discord.com/channels/348973006581923840/374636015396192257/1008895416181457016)-- Partial color fix, local recording to CQP, stopped running OBS as admin, removed all unnecessary sources including all display & game captures, updated Windows 10, fixed high profile in the x264 encoder that was missing
8) Ran an overnight Memtest for ~9 hours, no errors returned.

I've also attached my .zip of all my crash files, and my Mem test results. I can attach or provide more information upon request
[marstead obs crashes.zip](https://github.com/obsproject/obs-studio/files/9382807/marstead.obs.crashes.zip)
[MemTest86-Report-20220818-201010.txt](https://github.com/obsproject/obs-studio/files/9382812/MemTest86-Report-20220818-201010.txt)
.

**Comment by notr1ch** [comment]
Unfortunately x264 crashes are almost guaranteed to be hardware-related issues outside of the scope of OBS, most likely a BIOS (microcode), CPU, motherboard or memory error. Try additional stress test diagnostics such as Prime95 and OCCT to determine system stability. Sometimes it can take days of testing for intermittent hardware failures to manifest.

**Comment by alinsavix** [comment]
There's also a known issue w/ some Ryzen CPUs/motherboards w/ libx264, yes?

Though, really, @Marstead, your easiest solution will just be to use NVENC. From what I see of your config, there's no real benefit to doing software encoding here anyhow.
