### ISSUE TITLE
When saving the replay buffer, the video disappears and becomes a video file with audio only.

### ISSUE THREAD

**Issue by gamimin** [obsproject/obs-studio#7144]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.0-rc1

### OBS Studio Log URL

https://obsproject.com/logs/vUsuJ-dsuZXAnR8b

### Expected Behavior

I used the official version before the beta version, and the replay buffer was saved normally at that time

### Current Behavior

The screen is dark! ! I can't see the game screen! ! yes! ? ! ?
Beta1 and Beta2 had the same phenomenon, rc1 had the same phenomenon, sad if it's a bug that hasn't been discovered yet.

### Steps to Reproduce

1.start replay buffer
2.Save videos up to the number of seconds set in the replay buffer
3.Something... the screen is dark and only the audio is playing...
...

### Anything else we should know?

First (already the last column) I'm a Japanese OBS fan, and I'm writing using Google Interpreter. thank you!

First, the number of seconds I set for the replay buffer is 480s.
And if you save the replay at 480s or less, the video file will be saved normally with both video and audio.

I don't know if it's necessary, but the video file when saving a replay is not a thumbnail notation of the video, but a video icon when loading... (sorry if it's hard to understand)
It usually shows a thumbnail of the video

Pretend to be loading no matter how many minutes or hours you wait (see image
![スクリーンショット 2022-08-20 175932](https://user-images.githubusercontent.com/111633716/185737539-c2bc6d58-a9eb-48d1-b075-0f72b49de336.png)
)

**Comment by PatTheMav** [comment]
Confirmed this with about 8 minutes of replay buffer running, `ffprobe` tells me the video stream's headers are broken:

```
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x140604f50] stream 0, missing mandatory atoms, broken header
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x140604f50] Could not find codec parameters for stream 0 (Video: h264 (avc1 / 0x31637661), none(bt709), 1280x720): unspecified pixel format
Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Replay 2022-08-23 14-25-39.mov':
  Metadata:
    major_brand     : qt  
    minor_version   : 512
    compatible_brands: qt  
    encoder         : Lavf59.16.100
  Duration: 00:07:58.90, start: 0.000000, bitrate: 15283 kb/s
  Stream #0:0[0x1]: Video: h264 (avc1 / 0x31637661), none(bt709), 1280x720, 60 fps, 90k tbr, 90k tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : FFMP
  Stream #0:1[0x2]: Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 256 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
```

**Comment by Foo-x** [comment]
Confirmed with 400s on 28.0.0 (not rc).
