### ISSUE TITLE
UI: fields no longer expand horizontally in Custom Output (FFmpeg)

### ISSUE THREAD

**Issue by afriza** [obsproject/obs-studio#7147]
### Operating System Info

macOS 12

### OBS Studio Version

28.0.0-rc1

### OBS Studio Log URL

none

### Expected Behavior

Settings > Output > Output Mode = Advanced > Recording > Type = Custom Output (FFmpeg)

The width of fields expands/stretches after window resize..

### Current Behavior

Settings > Output > Output Mode = Advanced > Recording > Type = Custom Output (FFmpeg)

The width of fields is too narrow and doesn't expand/stretch after window resize.. This is a regression in v28.0.0-rc1 compared to v27.2.4 where the width will adjust accordingly when I stretch the window..

### Steps to Reproduce

1. Settings
2. Output
3. Output Mode = Advanced
4. Recording
5. Type = Custom Output (FFmpeg)
...

**Comment by WizardCM** [comment]
Confirmed on macOS in beta 1 and rc 1. Does not happen on Windows.

![image](https://user-images.githubusercontent.com/941350/185772414-0f14808b-c2b4-4c0b-8315-ca583726dace.png)
