### ISSUE TITLE
NVIDIA NVENC HEVC does not use padding in CBR mode (no "strict CBR")

### ISSUE THREAD

**Issue by Logan589XP** [obsproject/obs-studio#7154]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.0-rc1

### OBS Studio Log URL

https://obsproject.com/logs/LxttwzhJG6l37l1Y

### Expected Behavior

The bitrate to remain mostly stable as it does when set to other encoders like NVIDIA NVENC H.264 or x264 when set to CBR.

### Current Behavior

When you record or stream using NVIDIA NVENC HEVC it does so in VBR even though it's set to CBR. This does not occur on H.264, only HEVC. This has been an issue since v28 Beta 1.

### Steps to Reproduce

Simply set your encoder to NVIDIA NVENC HEVC, select your bitrate, and make sure it's set to CBR and start the recording.

Then bring up the Stats windows and if you look at the output bitrate you'll see it jump dramatically up and down depending on how much movement there is on screen, indicating (as far as I can tell) that VBR is being used and not CBR.

**Comment by notr1ch** [comment]
Note that is not truly VBR - it's CBR without padding, i.e. the encoder didn't need to use all the bitrate, so it didn't. For whatever reason, H264 seems to include padding by default to match the desired bitrate and HEVC does not.

**Comment by TheRealCeylan** [comment]
Yes, I'm running into this issue too.
When using Nvenc HEVC (Streaming to YouTube using HLS in my case), your bitrate is not constant even when using CBR. Whether or not it is because of  _padding_, I don't know.
If it is because of the lack of _padding_, I wonder if that's optimal for live streaming, I've always heard that you should keep a strict constant bitrate when you stream to avoid complications with the streaming site, but I don't know to what extent is that true.
Would appreciate if someone could clarify this for me.
But still, having the cbr behaviour be different when changing codecs is still a bit confusing on the user's end, I haven't seen anyone else talk about this issue in other places. There's also no option to enable _paddding_ if someone wants to use strict cbr.

**Comment by Logan589XP** [comment]
Just posting an quick update that this issue is still present as of OBS 28.1.2.

**Comment by pkviet** [comment]
@Logan589XP You're recording in an mp4 container which doesn't allow for filler nalus per spec:
`No filler data. Video data is naturally represented as variable bit rate in the file format and should be filled for transmission if needed. Filler Data NAL units and Filler Data SEI messages shall not be present in the file format stored stream.
(ISO/IEC 14496-15 - Carriage of network abstraction layer (NAL) unit structured video in the ISO base media file format)`
So it's normal it doesn't work. 
Not sure why it seems to work for you with nvenc h264 or hevc in previous versions of obs.
@TheRealCeylan your case is different. Our HLS muxer uses mpeg-ts which allows for filler nalus. This would require some changes for nvenc hevc, namely setting  enableFillerDataInsertion to 1 which we don't atm. I'll look into it to fix it.
Could you open a separate issue ?

**Comment by notr1ch** [comment]
I don't really see the point of filler data for HLS since the segments are no longer a "stream" but discrete files, filling them with padding seems like a waste of resources.

**Comment by pkviet** [comment]
> I don't really see the point of filler data for HLS since the segments are no longer a "stream" but discrete files, filling them with padding seems like a waste of resources.

yeah agreed and YouTube accepts VBR just fine anyway ...
@TheRealCeylan on second thoughts, don't open another issue. @notr1ch is right, we shouldn't waste time implementing it.

**Comment by Fenrirthviti** [comment]
If this is still required, it should be reported to nvidia for them to support properly.

**Comment by ValeZAA** [comment]
https://github.com/FFmpeg/FFmpeg/commit/839b41991d5ee6b9179fede9a402f7e15f859f0a

**Comment by derrod** [comment]
Please do not bump old issues with irrelevant comments.
