### ISSUE TITLE
libobs: threading.h includes w32-pthreads as a relative path

### ISSUE THREAD

**Issue by univrsal** [obsproject/obs-studio#7155]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.0-rc1

### OBS Studio Log URL

n/a

### Expected Behavior

Including the obs header <util/threading.h> breaks the build for plugins using the plugin template on windows as [the header](https://github.com/obsproject/obs-studio/blob/master/libobs/util/threading.h#L30) includes "../../deps/w32-pthreads/pthread.h". That file isn't present in the plugin dependencies and so the build fails. Here's a test project I made based on the template:
https://github.com/univrsal/test123
And here's the CI log:
https://github.com/univrsal/test123/runs/7821655312?check_suite_focus=true

I use that header in a plugin to set the name of a separate thread via os_thread_set_name (https://github.com/obsproject/obs-studio/blob/master/libobs/util/threading.h#L95) which used to work fine with the old CI I used, but I'm trying to switch to the actions from this template because I have to redo the CI for the move to Qt6.

### Current Behavior

The build fails.

### Steps to Reproduce

1. Create repository from the plugin template
2. Include util/threading.h
3. CI fails

### Anything else we should know?

I was told to report this here instead of in the plugin template. The original issue is here https://github.com/obsproject/obs-plugintemplate/issues/36

**Comment by paulpv** [comment]
When I hard reset `obs-studio` to `28.0.0-rc2`, I look at the files `libobs/CMakeLists.txt` and `libobs/utils/threading.h`, they look updated with this fix.

When I build a plugin (`obs-ndi`) in a folder beside `obs-studio` I get the following error:
```
C:\...\obs-build-dependencies\plugin-deps-2022-08-02-qt6-x64\include\util/threading.h(30,10): fatal error C1083: Cannot open include file: '../../deps/w32-pthreads/pthread
.h': No such file or directory [C:\...\obs-ndi\build_x64\obs-ndi.vcxproj]
```

Does the plugin-deps-2022-08-02-qt6-x64 need to be updated, or something else?

**Comment by paulpv** [comment]
Nevermind, I see that obs-ndi buildspec.json is:
```
{
    "dependencies": {
        "obs-studio": {
            "version": "28.0.0-beta1",
            "repository": "https://github.com/obsproject/obs-studio.git",
            "branch": "master",
            "hash": "43a49dca47344a5170159ef99b86b97f90d4e4ad"
        },
        ...
```

I can fix that...

**Comment by glikely** [comment]
I'm also having this problem, and changing the build spec as @paulpv suggests above has not fixed my Windows build in GitHub actions. I get the exact same cannot find pthreads.h error.

This is on the obs-ptz plugin. You can see the result here:
https://github.com/glikely/obs-ptz/actions/runs/3061262667

**Comment by paulpv** [comment]
@glikely 🤷‍♂️ Those deps look to be up to date.
Your [excellent looking] project looks to be based off of https://github.com/obsproject/obs-plugintemplate, so this is even more mysterious. :/

**Comment by PatTheMav** [comment]
This obviously cannot work if `w32-pthreads` doesn't export its `pthreads.h` as a public header (it isn't marked as such in its CMakeLists file).
