### ISSUE TITLE
What's New on macOS/Linux not working correctly for pre-relase due to RELEASE_CANDIDATE / BETA not being set on CI

### ISSUE THREAD

**Issue by derrod** [obsproject/obs-studio#7158]
Not sure what the best way to tackle this is, perhaps we can try parsing the tag and `-rc<#>` and `-beta<#>` and set the CMake variables (`RELEASE_CANDIATE` / `BETA`) accordingly? This would need to be included both in Flatpak (no idea) and macOS build scripts (again, no idea). Perhaps a question for @patthemav and @tytan652

**Comment by PatTheMav** [comment]
Probably easiest to move the parsing of the git tag higher up in `VersionConfig.cmake`, run a check for `-rc` or `-beta` suffixes in the version string yielded from that and then set `RELEASE_CANDIDATE`/`BETA` accordingly (so that part of the code can stay as-is).

**Comment by tytan652** [comment]
Improving `VersionConfig.cmake` seems to be the best solution.
