### ISSUE TITLE
Gysnc bug

### ISSUE THREAD

**Issue by Spartanz1080** [obsproject/obs-studio#7160]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.0-rc1

### OBS Studio Log URL

Don’t have one 

### Expected Behavior

Gysnc to work properly 

### Current Behavior

I literally have a video of the issue

https://youtu.be/2ev1wk7vUsY

If I just open OBS the issue happens in every game I have tried changing various settings nothing works. This issue just happened with this beta. I love the HDR features but I can’t even play with the micro stutter it’s a huge deal for me. As soon as I close obs the issue stops. 

### Steps to Reproduce

1. Just open OBS and play a game 
2.
3.
...

**Comment by WizardCM** [comment]
This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels below, and if it's determined that this is indeed a bug, then we will re-open this issue.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
