### ISSUE TITLE
Fixed gsync issue possible Nvidia broadcast SDK bug

### ISSUE THREAD

**Issue by Spartanz1080** [obsproject/obs-studio#7168]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.0-rc1

### OBS Studio Log URL

https://obsproject.com/logs/WbxHjAnGDE-84Two

### Expected Behavior

For NVIDIA broadcast noise removal and noise plus echo removal to work or just noise removal to work only room echo removal works. 

### Current Behavior

I did more investigation and fixed my gsync issue it was the Nvidia broadcast SDK only echo removal causes correct gpu usage resulting in correct Gsync behavior.

I made a new video watch the whole video and you will see. 

https://youtu.be/urjQYstJcJs

### Steps to Reproduce

1. Select noise or noise plus room echo removal in Nvidia broadcast SDK mic filters 
...

### Anything else we should know?

I am also using camera effects but turning them on or off does nothing.

**Comment by WizardCM** [comment]
This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels below, and if it's determined that this is indeed a bug, then we will re-open this issue.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
