### ISSUE TITLE
Streamkit dont show persons that are talking in Browser Source (Wroks perfect on Chrome / Mozilla)

### ISSUE THREAD

**Issue by Agustinzero1** [obsproject/obs-studio#7172]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

i not have an error log

### OBS Studio Crash Log URL

i not have an error log

### Expected Behavior

load a discord icons, and produce a highlight effect on users we tey have a mic activity using the discord Streamkit integration, https://streamkit.discord.com/overlay/voice/ (I'm not giving the complete link because have some ID that i don't know if they are Private or so, but is really replicable easily)

### Current Behavior

Load the list of Online users on the voice channel in the captured browser image, but with no voice activity effect. (and update in real-time if the user enters or exit the voice channel)

### Steps to Reproduce

1. Link discord with the StreamKit here https://streamkit.discord.com/overlay
2. go to Voice Widget Options, then select a discord and a voice channel for test
3. next copy the resulting web plugin link
4. go to obs and add browser source and paste the web plugin link that copy before
5. and paste in chrome or another browser too for testing propose.
...
discord

### Anything else we should know?

in the browser works perfectly, but in the browser source in obs doesn't work the highlight function on voice activity not working. but shows in real-time if some enter or exit from the voice channel, I don't know what happens

the browser source is not reproducing the web plugin correctly, and I think that is an obs error and not a discord Streamkit error.

I test on Chrome Versión 104.0.5112.81 (Build Oficial) (64 bits) and in this version works perfectly, when I talk in discord show highlight color on my icon, but not in obs browser source

**Comment by WizardCM** [comment]
I cannot reproduce this. Works fine for me.

![image](https://user-images.githubusercontent.com/941350/186178208-52497969-5966-4826-862c-32a6fc4e3b49.png)

**Comment by Agustinzero1** [comment]
![image](https://user-images.githubusercontent.com/12629927/186180200-f20a099d-6ba9-4578-ab84-1641c3202c41.png)

**Comment by Agustinzero1** [comment]
![image](https://user-images.githubusercontent.com/12629927/186181184-5736209b-1ac9-4a51-8c7f-19abdc0f8293.png)

**Comment by WizardCM** [comment]
OBS with the StreamElements plugin is not supported.

This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels below, and if it's determined that this is indeed a bug, then we will re-open this issue.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

**Comment by Agustinzero1** [comment]
and I'm having the same problem on Streamlabs, that is suspicious considering that obs and streamlabs have the same core... i don't think that this is a compatibility issue...

**Comment by Agustinzero1** [comment]
![image](https://user-images.githubusercontent.com/12629927/186183836-26f33b3e-1eb4-41bc-8b6c-758e223e63ac.png)

i unstall the Stream elements and the OBS core version is having the same problem...
