### ISSUE TITLE
Streaming RIST does not send data

### ISSUE THREAD

**Issue by LainLayer** [obsproject/obs-studio#7176]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/Ixz7_Lrkhvv18Gd6

### Expected Behavior

data is sent, like with ristsender from librist:

![image](https://user-images.githubusercontent.com/10339438/186462639-7fef43ee-ca23-45fe-a9ee-e1c0edd79f19.png)

### Current Behavior

nothing is sent
![image](https://user-images.githubusercontent.com/10339438/186462996-cb23c788-eb0a-48e8-9d4c-f6423ca5cedf.png)

### Steps to Reproduce

1. set up a rist receiving program (in my case MistServer)
2. set stream output to a rist url, i.e `rist://localhost:5002`
3. click start streaming
...

**Comment by tytan652** [comment]
It seems you are using ArchLinux repo package, this is more of support question (try the discord for more help).

Long story short, FFmpeg is not build with RIST support.

**Comment by LainLayer** [comment]
I see, makes sense, thanks. Should probably show some error anyway, instead of showing like its streaming just fine

**Comment by tytan652** [comment]
But you can check the Flatpak OR `ffmpeg-obs` or even `obs-studio-browser` on the AUR.

**Comment by RytoEX** [comment]
Closing this as this seems to be something that needs to be addressed in Arch packages.
