### ISSUE TITLE
[28.0.0-rc1] some build options appear to have no effect and don't fail when they should

### ISSUE THREAD

**Issue by tgurr** [obsproject/obs-studio#7180]
### Operating System Info

Other

### Other OS

Exherbo Linux

### OBS Studio Version

28.0.0-rc1

### OBS Studio Log URL

-

### Expected Behavior

* fail when option is requested but dependencies are not fulfilled
* allow to succesfully enable/disable options
* things getting built properly

### Current Behavior

Trying to figure out a build issue locally our CI runs into: https://gitlab.exherbo.org/tgurr/media/-/jobs/48624 I first discovered that the CMake `obs_status` summary always reads 

```
-- OBS:  ENABLED    obs-outputs
-- OBS:  ENABLED    rtmp-services
```
no matter if `-DENABLE_RTMPS:BOOL=FALSE` and `-DENABLE_SERVICE_UPDATES:BOOL=FALSE` was passed. Put up a pull request for that here: https://github.com/obsproject/obs-studio/pull/7179

However I'm also able to build rc1 even when not having mbedtls installed at all and passing `-DENABLE_RTMPS:BOOL=TRUE` resulting in not linking mbedtls, while building 27.2.4 just works fine.

#### 28.0.0-rc1

There is no CMake configure output at all in regards to MbedTLS being searched for and/or found, but only for the plugin printing:

`-- OBS:  ENABLED    obs-outputs`

```
[ 51%] Linking C shared module obs-outputs.so
cd /var/tmp/paludis/build/media-video-obs-studio-28.0.0-rc1/work/build/plugins/obs-outputs && /usr/x86_64-pc-linux-gnu/bin/cmake -E cmake_link_script CMakeFiles/obs-outputs.dir/link.txt --verbose=1
/usr/bin/x86_64-pc-linux-gnu-cc -fPIC -march=native -O2 -pipe -Wl,-O1 -Wl,--as-needed -shared  -o obs-outputs.so "CMakeFiles/obs-outputs.dir/obs-outputs.c.o" "CMakeFiles/obs-outputs.dir/flv-mux.c.o" "CMakeFiles/obs-outputs.dir/flv-output.c.o" "CMakeFiles/obs-outputs.dir/net-if.c.o" "CMakeFiles/obs-outputs.dir/null-output.c.o" "CMakeFiles/obs-outputs.dir/rtmp-stream.c.o" "CMakeFiles/obs-outputs.dir/rtmp-windows.c.o"  -Wl,-rpath,/var/tmp/paludis/build/media-video-obs-studio-28.0.0-rc1/work/build/libobs: ../../libobs/libobs.so.28
```

and empty ldd output on the resulting library:

`$ ldd /usr/x86_64-pc-linux-gnu/lib/obs-plugins/obs-outputs.so | grep libmbed`

#### 27.2.4

There is CMake configure output in regards to MbedTLS:

`-- Found MbedTLS: /usr/x86_64-pc-linux-gnu/bin/../lib64/libmbedtls.so;/usr/x86_64-pc-linux-gnu/bin/../lib64/libmbedcrypto.so;/usr/x86_64-pc-linux-gnu/bin/../lib64/libmbedx509.so`

as well as it is linked during build:

```
[ 49%] Linking C shared module obs-outputs.so
cd /var/tmp/paludis/build/media-video-obs-studio-27.2.4/work/build/plugins/obs-outputs && /usr/x86_64-pc-linux-gnu/bin/cmake -E cmake_link_script CMakeFiles/obs-outputs.dir/link.txt --verbose=1
/usr/bin/x86_64-pc-linux-gnu-cc -fPIC -Wall -Wextra -Wvla -Wno-unused-function -Werror-implicit-function-declaration -Wno-missing-braces -Wno-missing-field-initializers -march=native -O2 -pipe -std=gnu99 -fno-strict-aliasing -Wl,-O1 -Wl,--as-needed -shared  -o obs-outputs.so "CMakeFiles/obs-outputs.dir/obs-outputs.c.o" "CMakeFiles/obs-outputs.dir/null-output.c.o" "CMakeFiles/obs-outputs.dir/rtmp-stream.c.o" "CMakeFiles/obs-outputs.dir/rtmp-windows.c.o" "CMakeFiles/obs-outputs.dir/flv-output.c.o" "CMakeFiles/obs-outputs.dir/flv-mux.c.o" "CMakeFiles/obs-outputs.dir/net-if.c.o" "CMakeFiles/obs-outputs.dir/librtmp/amf.c.o" "CMakeFiles/obs-outputs.dir/librtmp/cencode.c.o" "CMakeFiles/obs-outputs.dir/librtmp/hashswf.c.o" "CMakeFiles/obs-outputs.dir/librtmp/log.c.o" "CMakeFiles/obs-outputs.dir/librtmp/md5.c.o" "CMakeFiles/obs-outputs.dir/librtmp/parseurl.c.o" "CMakeFiles/obs-outputs.dir/librtmp/rtmp.c.o"  -Wl,-rpath,/var/tmp/paludis/build/media-video-obs-studio-27.2.4/work/build/libobs: ../../libobs/libobs.so.0 /usr/x86_64-pc-linux-gnu/bin/../lib64/libmbedtls.so /usr/x86_64-pc-linux-gnu/bin/../lib64/libmbedcrypto.so /usr/x86_64-pc-linux-gnu/bin/../lib64/libmbedx509.so /usr/x86_64-pc-linux-gnu/lib/../lib64/libz.so
```

and correctly present in the resulting library:

```
$ ldd /usr/x86_64-pc-linux-gnu/lib/obs-plugins/obs-outputs.so | grep libmbed
        libmbedtls.so.14 => /usr/x86_64-pc-linux-gnu/lib/libmbedtls.so.14 (0x00007f0a0e5d9000)
        libmbedcrypto.so.7 => /usr/x86_64-pc-linux-gnu/lib/libmbedcrypto.so.7 (0x00007f0a0e562000)
        libmbedx509.so.1 => /usr/x86_64-pc-linux-gnu/lib/libmbedx509.so.1 (0x00007f0a0e540000)
```

### Steps to Reproduce

1. uninstall mbedtls or have it installed
2. build 28.0.0-rc1 passing `-DENABLE_RTMPS:BOOL=TRUE`
3. see it neither complaining with any error during configure/build nor correctly finding, picking up and linking mbedtls at all
...

**Comment by derrod** [comment]
`obs-outputs` and `rtmp-services` are larger modules, with RTMPS support and service updates just being part of it. The log output is therefore correct.

`ENABLE_RTMPS` is a STRING, not BOOL. It has to be set to `ON` (by default it is `AUTO`).

**Comment by tgurr** [comment]
I probably got confused when messing around trying to solve the initial issue that the `obs_status` cmake configure output for this plugin always showed enabled no matter what was passed since I did test the following at first, because in the process I also tried the following as the solution here is to pass `-DENABLE_RTMPS:STRING=OFF/ON` instead of `-DENABLE_RTMPS:BOOL=TRUE/FALSE` as `obs-outputs` stricly requires `STRING` while other plugins like `linux-pipewire`, `linux-pulseaudio` do not and work with both. Would be nice if this could be streamlined, preferably all options also working with BOOL as well.

**Comment by RytoEX** [comment]
`ENABLE_RTMPS` is a string because it required a tri-state flag, with the options being AUTO/ON/OFF. From my recollection, we considered a boolean, and disregarded it as unworkable with the requirements of various Linux distros and package management systems.
