### ISSUE TITLE
When group is added to Scene it is not positioned as group is set but in top left corner

### ISSUE THREAD

**Issue by pedjas** [obsproject/obs-studio#7183]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

no need for log

### Expected Behavior

When user adds Group as source, Group should be positioned as position is set for that group.
User must reposition group where it should be.

### Current Behavior

That does no happen. Group position is ignored and group is positioned to 0.0.

### Steps to Reproduce

1. Create group
2. Edit transform for the group and set x and y position
3. Add that group to some other Scene. Group will not be positioned as set in a group but at top left corner.

**Comment by WizardCM** [comment]
A group is a scene item, like all other scene items. Its position can be different for each instance in any scene. This is intentional.

**Comment by pedjas** [comment]
Yes it can be different but id does not have to. Actually, most of the groups I create should be positioned at the same place like Logos, titles, subtitles, signatures.... And later, if I want to reposition group, i need it to be done on the group and then repeated everywhere where that group is used.

It should follow position set for the group. If one wants to move it he freely can. Resetting group position to zero helps nothing. One that wants to move it do not care where it is positioned at the insert as he will move it anyways. 

It just makes problem if group has to be repeated in several scenes at the same place. It is especially bothers when Scene Collection is in process of creating when building elements a moved and sized a lot until all Scenes are created and set. It is also issue if something needs to be changed afterwards. User must go through all scenes and repeat the same change everywhere.

This behavior of OBS that some items are copied and some referenced without any consistency is really annoying.

**Comment by WizardCM** [comment]
For your use case, you can either
1. Use Copy/Paste Transform to copy the position from one group to another OR
2. Use nested scenes instead, which are the size of a scene and therefore anything within it will have the same position in all scenes

**Comment by pedjas** [comment]
Copy/Paste Transform does not work.

I switched from using nested scenes because I need these elements other in few various groups of scenes where they are positioned differently. I gave up from scenes as they had their own quirks for that purpose.

Basically, I ended up almost giving up using reusable element but creating each scene independently. Very annoying.
