### ISSUE TITLE
The video input device (webcam) does not capture properly in the virtual machine when using remote connections

### ISSUE THREAD

**Issue by tp4azo1** [obsproject/obs-studio#7184]
### Operating System Info

Windows 10

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/IFd64bObNHsxwV40

### Expected Behavior

Sharing camera data to the virtual machine via remote desktop (mstsc.exe) and broadcasting via OBS.

### Current Behavior

The video input device does not capture properly when using Remote Desktop (mstsc.exe) to establish a connection with the local Hyper-V virtual machine and connect the local camera to the virtual machine. However, the "Camera" application that comes with Windows on the virtual machine can capture the webcam content normally.
This issue can be reproducible after the virtual machine completed OOBE and only installed OBS.

### Steps to Reproduce

1. Virtual machine install system via official iso.
2. The virtual machine allow remote connections and installs OBS.
3. The host selects the camera in local devices and connections when opening remote desktop and connects to the virtual machine.
4. In the virtual machine, adding "video capture device" in the OBS , I can see and select the host camera but there is no image.
![屏幕截图 2022-08-26 002717](https://user-images.githubusercontent.com/17009637/186722257-ffbe65d1-fcd2-4223-ba9e-715b26d58a9c.png)
6. Opening the "Camera" application in the virtual machine can see the content of the host camera normally.
![屏幕截图 2022-08-26 002652](https://user-images.githubusercontent.com/17009637/186723023-29381c32-1ac2-4252-b750-f0e0126359cd.png)

### Anything else we should know?

Host: Windows 10 (19044.1889)
Virtual machine: Windows 10 (19044.1288)
Tested on both generation 1 and 2 virtual machine in Hyper-V.

**Comment by derrod** [comment]
The webcam may not work properly with DirectShow in the VM, the Windows "Camera" application is using Media Foundation instead and works differently. Additionally running OBS in a VM, especially one without proper GPU, is entirely unsupported.  You are on your own.

**Comment by tp4azo1** [comment]
The problem was solved after using CamSplitter, a commercial software (US$9.99 For 1 PC) made by e2esoft (known for its VCam SDK), to capture the host camera and re-export it as a virtual camera inside the virtual machine. However, the company's live streaming software, WeCam, also has the same problem.
