### ISSUE TITLE
Windows 10 Capture Method causes laggy mouse and system lags

### ISSUE THREAD

**Issue by KinComet** [obsproject/obs-studio#7190]
### Operating System Info

Windows 11

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/QeHvOg-rAGvJ5TKc

### Expected Behavior

Normally capture the sources and don't cause the lags.

### Current Behavior

Capturing the sources, but few frames may lost in output in a second.
The mouse easily seen laggy. The system may be laggy and the mouse is even more laggy when you doing something that requires GPU.

### Steps to Reproduce

1. Add display or window source with Windows 10 (1903 and up) Capture Method
2. Don't need to start recording or streaming, just enable the source, make it viewable
3. see the problem. If not happen, maybe you need to cause some GPU usages first.

### Anything else we should know?

If Wallpaper Engine (or other things that causes GPU usages) is enabled, this is more frequent.
My PC is using Optimus tech, if Intel GPU 40%+ it'll happen to me. (But if not using Windows 10 Capture Method, this doesn't happen even if it's 70%+)
![image](https://user-images.githubusercontent.com/111748332/186906556-cd83d17d-a395-43b2-9f5c-a11eb90e13c8.png)

I came to Discord server to get support, but no one could help me solve the problem

**Comment by Fenrirthviti** [comment]
Can you confirm if the issue described is affecting the output only, or is the mouse on your actual system showing this lag?

**Comment by KinComet** [comment]
> on your actual system showing this lag

Yes, it's on my actual system.

**Comment by gxalpha** [comment]
When using the WGC capture method (called "Windows 10 (1903 and up)" in OBS), Windows currently forces a software cursor. This can make the mouse feel laggy. Unfortunately, there is nothing that we can change about that situation, as it purely depends on Windows.
You can read https://github.com/microsoft/Windows.UI.Composition-Win32-Samples/issues/51 for further insights on this.
