### ISSUE TITLE
OBS will sometimes get stuck on "Stopping Recording..." or "Stopping Replay Buffer..."

### ISSUE THREAD

**Issue by haayfe** [obsproject/obs-studio#7191]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.0-rc2

### OBS Studio Log URL

https://obsproject.com/logs/VLCpIxTwzhorq6IW

### Expected Behavior

The recording and/or replay buffer to end.

### Current Behavior

They remain stuck until I reset OBS using task manager.

### Steps to Reproduce

1. Make a recording
2. Wait around 10 seconds
3. Attempt to stop the recording

**Comment by Mister36MN** [comment]
This is most likely a support issue, please use the discord or forums as support issues are not for GitHub.

**Comment by PatTheMav** [comment]
Cannot be reproduced dependably, also no further updates in 2 weeks. Closing as stale.
