### ISSUE TITLE
log file stops after obs-websocket disconnected

### ISSUE THREAD

**Issue by afriza** [obsproject/obs-studio#7194]
### Operating System Info

macOS 12

### OBS Studio Version

28.0.0-rc2

### OBS Studio Log URL

https://obsproject.com/logs/WqaE0o11v0W23Flw

https://obsproject.com/logs/REiWYw7pBgjqyRkJ

### Expected Behavior

log file keeps logging and shows ffmpeg_source/vlc_source being updated

### Current Behavior

log file stops after showing connected/disconnected

### Steps to Reproduce

1. use [goobs](https://github.com/andreykaipov/goobs) to connect
2. get & set ffmpeg_source/vlc_source settings to play video

Sample [test go app](https://github.com/afriza/goobs/blob/obs-log/test/test.go)
```console
# download & install latest go from https://go.dev/doc/install
git clone https://github.com/afriza/goobs.git --branch obs-log
cd goobs/test
# edit websocket password & video file location in test.go
./run.sh
```

**Comment by afriza** [comment]
sorry.. after recheck with OBS v28.. and cross-check with OBS v27.0.1 ..

ffmpeg_source does have messages written to the log..

vlc_source does **NOT** have messages written to the log..

this behavior is the same when I cross-checked with v27.0.1 and is not related with obs-websocket status..

should I create a feature request to have vlc_source related messages written to the log?

**Comment by PatTheMav** [comment]
Creating a feature request via the appropriate channels would be the correct approach, or - better yet -  a pull request adding that feature to the VLC plugin.
