### ISSUE TITLE
Cannot tell active scene you are in by looking at the Scene switcher if you click elsewhere on the scene switcher or other control

### ISSUE THREAD

**Issue by BarryCarlyon** [obsproject/obs-studio#7196]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.0-rc2

### OBS Studio Log URL

https://obsproject.com/logs/xmuPv06G-Qtx3wYv

### Expected Behavior

The [blue highlight] on Yami Theme (issue present on all themes) stays blue to indicate current scene regardless of where you click on the scene switcher

![image](https://user-images.githubusercontent.com/20999/187032433-dd3a5aa1-cc27-433e-8b8b-9692712e2beb.png)

This issue exists both in grid view and list view of the Scenes Control

### Current Behavior

You can cause the button highlight that indicates the active scene to disappear from the scene switcher leaving you with no idea which scene you are currently in

### Steps to Reproduce

1. Be in a scene - 
![image](https://user-images.githubusercontent.com/20999/187032483-a5d1ebd1-9153-4ee5-a156-8e12805d76f3.png)
2. Change Scenes - 
![image](https://user-images.githubusercontent.com/20999/187032494-06fee0b0-555a-4fae-937f-8cf9d059d89b.png)
3. Click here - 
![image](https://user-images.githubusercontent.com/20999/187032496-c72da85f-6923-4ba5-ba40-6432d648e7a1.png)
4. Become confused - 
![image](https://user-images.githubusercontent.com/20999/187032506-f5bbdb6b-d6ed-437b-9e85-d35ac4a739a4.png)
5. Bonus points - click elsewhere in the UI (any other dock/control or the canvas itself) such as here and lose the dotted border - 
![image](https://user-images.githubusercontent.com/20999/187032521-e2e71982-ebb8-414b-9a92-73fd8c1e6ee0.png)

**Comment by gxalpha** [comment]
We confirmed this already and determined it to be a dependency issue with Qt, which we reported upstream (see [QTBUG-105870](https://bugreports.qt.io/browse/QTBUG-105870)). We intend to find *some* fix for the full release.
I'll leave this open as we have it on the bug tracker, but only as a card, not an issue.

**Comment by BarryCarlyon** [comment]
Yeah I expected it would of been a QTBUG (should of noted that in the anything else) but good to know it's a problem _elsewhere_ and filed!
