### ISSUE TITLE
When virtual camera is on, monitors do not go to sleep on PC idle

### ISSUE THREAD

**Issue by alejandro5042** [obsproject/obs-studio#7205]
### Operating System Info

Windows 11

### OBS Studio Version

27.2.4

### OBS Studio Log URL

N/A

### Expected Behavior

Virtual camera state should not prevent monitors from going to sleep when the PC is idle (a Windows feature).

### Current Behavior

When the virtual camera is enabled, the monitors never fall asleep.

### Steps to Reproduce

1. Make sure your PC sets your monitors to fall asleep after a certain time.
2. Start virtual camera.
3. Wait until the PC should turn off your monitors.
4. See that it doesn't.
5. Stop the virtual camera and see that the monitors do in fact go to sleep on idle.

**Comment by WizardCM** [comment]
Technically this is intentional. OBS disables sleep when an output is active.

**Comment by CodeYan01** [comment]
I do not see any reason why virtual camera should not prevent sleep. With my setup, I actually do need my pc to stay awake if my virtual camera is on, since I use obs for the camera, not recording/streaming.

**Comment by Fenrirthviti** [comment]
Confirming this is intentional, and not something we are likely to change.
