### ISSUE TITLE
OBS horrible internal audio on linux, microphone works just fine

### ISSUE THREAD

**Issue by gabriele2000** [obsproject/obs-studio#7209]
### Operating System Info

Other

### Other OS

Pop!_Os 22.04

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.2.3

### OBS Studio Log URL

https://obsproject.com/logs/CfdrErPCik6_D08l

### Expected Behavior

Following that issue https://github.com/wwmm/easyeffects/issues/1780 the expected behavious would be: perfect sound, without perceived quality loss, like low-bitrate encodings, since it never happened until... half a month ago?

The expected behavious is: internal audio like "simplescreenrecorder" (posted on my last reply, github broke the video and it's audio-only)

### Current Behavior

Internal audio sounds like I'm compressing the audio too much, like old-school mp3 encodings at 64kbps, this one sounds more like 192kbps

### Steps to Reproduce

At this point I don't even know what caused it.

### Anything else we should know?

I tried to reinstall everything, both OBS and Pipewire, tried to reset the samplerate, tried to reset OBS, I tried everything in my power.

**Comment by kkartaltepe** [comment]
reading the linked bug, you would like us to record in the same audio level as some other screen recorder. This does not sound like a bug, also if you are using pipewire for audio you should consider all audio related bugs a pipewire bug first and determine if the issue happens with a pure pulseaudio stack.

**Comment by gabriele2000** [comment]
> reading the linked bug, you would like us to record in the same audio level as some other screen recorder. This does not sound like a bug, also if you are using pipewire for audio you should consider all audio related bugs a pipewire bug first and determine if the issue happens with a pure pulseaudio stack. Since obs does not support audio recording from pipewire so most bugs are in the pipewire-pulse or pipewire routing layer.

[Fixed (last comment)](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2668)
