### ISSUE TITLE
OBS crashes when trying to add multiple pipewire source types

### ISSUE THREAD

**Issue by GloriousEggroll** [obsproject/obs-studio#7210]
### Operating System Info

Other

### Other OS

Fedora 36 Linux

### OBS Studio Version

Git

### OBS Studio Log URL

https://obsproject.com/logs/VeEo8e6wgsZYQqhK

### Expected Behavior

Should be able to add multiple pipewire sources

### Current Behavior

> Add pipewire screen capture = OK
> Add pipewire window capture after adding previous screen capture = crash

also happens if I try adding pipewire audio capture after adding a screen or window capture. seems to just dislike capturing multiple pipewire sources no matter the source type

### Steps to Reproduce

> Add pipewire screen capture = OK
> Add pipewire window capture after adding previous screen capture = crash

also happens if I try adding pipewire audio capture after adding a screen or window capture. seems to just dislike capturing multiple pipewire sources no matter the source type

**Comment by GloriousEggroll** [comment]
probably the same issue:

also crashes if you add a second browser source

**Comment by kkartaltepe** [comment]
please provide a stack trace from a crash.

**Comment by GloriousEggroll** [comment]
> please provide a stack trace from a crash.

theres not one created, the entire application just completely closes, nothing in the logs.

I'll see if I can bisect later.

**Comment by derrod** [comment]
Could you check if d69c749aafa052331d3678d9b60eecbddd2dba2d (#7201 now merged) has fixed this?

**Comment by kkartaltepe** [comment]
Please add a breakpoint to `exit`, `_exit`, `abort` and set `catch syscall 60` and provide the backtrace from that.

**Comment by GloriousEggroll** [comment]
closing -- resolved as of testing today's upstream git commits
