### ISSUE TITLE
[macOS] Menu bar only captured partially

### ISSUE THREAD

**Issue by dnaka91** [obsproject/obs-studio#7212]
### Operating System Info

macOS 12

### OBS Studio Version

28.0.0-rc2

### OBS Studio Log URL

https://obsproject.com/logs/12VYg4mYAO6DKK7o

### Expected Behavior

Expected the whole screen to be captured, including all items on the menu bar.

### Current Behavior

Most of the menu bar is captured, except a few system elements. Namely, volume control, battery status, network status, system settings and date/time.

This is my current menu bar:
![SCR-20220829-dh6](https://user-images.githubusercontent.com/36804488/187135940-6272a7aa-75a2-4cc2-af32-90dcb256f8e7.png)

And this is what OBS captures:
![SCR-20220829-dgv](https://user-images.githubusercontent.com/36804488/187135992-4137ab89-2f1e-4d21-8637-d60bd1b618ca.png)

### Steps to Reproduce

1. Add a macOS Screen Capture source.
2. Set the mode to "Display Capture".
3. (Eventually) restart OBS once.

**Comment by PatTheMav** [comment]
Closed because known issue with macOS 12.5 and not possible fix (except for updating to macOS 13 or a possible 12.6 release).
