### ISSUE TITLE
Audio bitrate always set to default 128 kbit/s if Twitch VOD track is enabled

### ISSUE THREAD

**Issue by marvin0815** [obsproject/obs-studio#7218]
### Operating System Info

Windows 11

### OBS Studio Version

Other

### OBS Studio Version (Other)

Tested 27.2.4 and 28 RC's

### OBS Studio Log URL

https://obsproject.com/logs/oIOWywcrC-LeBdqn

### Expected Behavior

Bitrate should be the defined value in the Output->Audio tab

### Current Behavior

Audio bitrate is 128 kbit/s for both stream and vod track. It seems to be encoder agnostic, tested with coreaudio, fdk-aac and ffmpeg-aac.

### Steps to Reproduce

1. Set bitrate to a >128 value
2. enable Twitch VOD Track
3. Start stream

### Anything else we should know?

I haven't checked the behaviour of record only footage and bitrates lower than 128 kbit/s.

**Comment by RytoEX** [comment]
The logs say the audio bitrates are 160. How are you verifying the bitrate?

**Comment by marvin0815** [comment]
Use streamlink to get the HLS link of a livestream and open it with ffplay or something that can display the track bitrates

**Comment by flaeri** [comment]
I tested this, and I get 160kbps (what I asked for) in output, with the twitch track enabled. They way I measured was streaming to twitch, and enabling a copy of the stream to be dumped to disk, and measured the audio bitrate with ffmpeg.

The issue with downloading VODs and similar from twitch is that they might mess with the metadata, or do other unexpected stuff. Pretty sure its not the first time I'm hearing of people downloading vods and complaining that there were indications of the audio stream being lower than expected.

Another thing to keep in mind is that a lot of the time, the audio bitrate will not hit bitrate that you set, as the encoder does not require that much bitrate, and it does not add filler/padding to reach it. You can test this by muting all audio output, and see the audio bitrate drop to almost zero.

**Comment by flaeri** [comment]
I ran a few more tests, and tested a few other channels, including my own.

I think you are right. When the twitch VOD track is enabled, it seems the audio bitrate is not the same. I suspect when Twitch detects multiple audio tracks, it triggers a path that will re-encode the audio. Thats the only way I can see this happening. The dump of the stream to disk is 160kbps, but HLS dumping its 128kbps. I believe OBS is sending with the correct birate, and the only way for it to change is if Twitch is re-encoding it on their end.

**Comment by marvin0815** [comment]
I think you've right, now I remember I read something about that Twitch limits dual audio to 2x 128kbits. I can't find any sources about it and maybe thought I was misremembering.

**Comment by flaeri** [comment]
Interesting. I haven't read about it anywhere, but for me, it seems the only plausible explanation. Feel free to close this issue if you feel satisfied. People can still find it and reference it if they should be wondering about this behavior.
