### ISSUE TITLE
Scene change (plugin) event is "late" when using a Stinger

### ISSUE THREAD

**Issue by BarryCarlyon** [obsproject/obs-studio#7219]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.0-rc2

### OBS Studio Log URL

https://obsproject.com/logs/H8Yl7hx4gRDWQwEt

### Expected Behavior

`OBS_FRONTEND_EVENT_SCENE_CHANGED` to trigger when the scene changes not after the Stinger completes

### Current Behavior

Both the WebSocket Event `CurrentProgramSceneChanged` and CEF event `obsSceneChanged` trigger when a Stinger completes and _not_ when the scene actually changes. part way thru a stinger.

Which means browser overlays that use scenes to detemine placment animated _after_ a Stinger completes not "under the cover" of the stinger.

### Steps to Reproduce

1. Have Scene Transition set to stinger
2. Set Stinger to Transition point to something like the 10th frame or 1ms (anything way less than the length of the Stinger file)
3. TriggerTransition
4. Observe that the events trigger when the Stinger completes, not the set transition point of the stinger.

### Anything else we should know?

Apologies if this is in the wrong place, but I believe it is an "upstream" issue inside OBS rather than obs-browser/Websockets/other plugins themself, as the issue is present in both obs-browser and WebSockets. (I have a feeling it's in pre 28 OBS which I just worked around another way, but intending to use Stingers properly now as I'm working on my OBS 27 to 28 migration paths)

I am testing obs-browser and built in websockets, not other plugins that may use this event (as don't know of any off hand).

This is a simple browser source to highligh the issue

```html

<html>
<head>
<title>OBS test</title>

<style type="text/css">
#output {
background: red;
color: white;
position: absolute;
top: 0px;
left: 0px;
width: calc(1920px / 2);
height: 300px;
overflow: hidden;
}
</style>

</head>
<body>
https://github.com/obsproject/obs-browser
<div id="output"></div>

<script type="text/javascript">
function write(line) {
    let l = document.createElement('div');
    l.textContent = line;
    document.getElementById('output').prepend(l);
}
write('Born ' + new Date().getTime()); 

window.obsstudio.getControlLevel((level) => {
    write(`getControlLevel: ${level}`);
});
window.addEventListener('obsSceneChanged', (event) => {
    write(`obsSceneChanged ${JSON.stringify(event.detail)}`);
});

write('Ready ' + new Date().getTime());
</script>

</body>
</html>
```

And you'll see that when using it with a Stinger. The log line "pops" into view after the Stinger finishes rather than appearing behind the Stinger at the Stinger Transition point.

Video for issue to illistrate the "pop"

https://user-images.githubusercontent.com/20999/187291304-0c6ed06b-d76b-4cb3-babe-5618955a53b8.mov

Edit: So I went to test this in OBS 27 release. It's present there too. It broadcasts the event _after_ the Stinger Transition completes rather than at the transition point.

Edit b: if I subscribe to the relevant events via WebSockets this is the timeline for a given Stinger run with the Stinger transition point set to the 10th frame (with the video being 60fps and 3 seconds in length) so it should `CurrentProgramSceneChanged` very quickly after `SceneTransitionStarted`

```
2022-08-29T20:36:14.670Z CurrentSceneTransitionChanged { transitionName: 'Stinger' }
2022-08-29T20:36:14.672Z SceneTransitionStarted { transitionName: 'Stinger' }
2022-08-29T20:36:17.929Z SceneTransitionVideoEnded { transitionName: 'Stinger' }
2022-08-29T20:36:17.948Z CurrentProgramSceneChanged { sceneName: 'Main Scene' }
2022-08-29T20:36:17.995Z SceneTransitionEnded { transitionName: 'Stinger' }
```

Edit c: if you run code in your browser source similar to

```js
    setInterval(function() {
        window.obsstudio.getCurrentScene(function(data) {
            var name = data.name;
            if (last_name != name) {
                console.log('broadcast', 'window getCurrentScene tick: ' + name);
                last_name = name;
            }
        });
    }, 1000);
```

The scene is correctly fetched via _spamming_ OBS browser source to get the scene.
So just the event is broadcast late it would seem

And I can get closer to the transition point if I spam OBS with `GetCurrentProgramScene` Websocket requests. This in itself reports the "new" scene before the stingers transition point anyway. (say if you set the transition point to 2000ms using a setInterval (in JS) fo 10 ms you pick up the new scene 20ms after you recv `SceneTransitionStarted`)

**Comment by PatTheMav** [comment]
The observed behaviour is correct insofar as that's how it's implemented:

The `OBS_FRONTEND_EVENT_SCENE_CHANGED` event is triggered together with `OBS_FRONTEND_EVENT_TRANSITION_STOPPED` in the `OBSBasic::TransitionStopped` function.

The tricky part about the stinger is that what you see visually (a switch to the new scene at the transition point configured on the transition) does not represent the internal state of the scene management:

From the POV of OBS, a stinger is a video that uses the source texture and a video to composit a transition that just happens to use a different source texture (the scene you're transitioning to) after the transition point, but internally no transition has taken place until that composited video has finished (the same is true for all transitions afaik).

The desired use case is understood, but without changing how/when OBS considers a scene transitioned or adding a new frontend event I don't see how the expected outcome is possible with OBS right now.
