### ISSUE TITLE
Application audio capture causes ingame fps drop

### ISSUE THREAD

**Issue by z0fa** [obsproject/obs-studio#7230]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.0-rc2

### OBS Studio Log URL

https://obsproject.com/logs/xfGeiqaadj1GaH7W

### Expected Behavior

Application audio capture sources of inactive scenes should not impact game performance

### Current Behavior

Having 10 or more scenes with one application audio capture source in each of them causes ingame fps drop and random input lag

### Steps to Reproduce

1. Create 10+ scenes with one application audio capture source in each of them
2. Open any game (I have tested with Overwatch)
3. Notice fps drop each 5 seconds and random input lag
...

### Anything else we should know?

Video example: https://youtu.be/kfzF5jk9Dng
I can provide my scene collection if needed

Related issues from the win-capture-audio plugin:
https://github.com/bozbez/win-capture-audio/issues/62#issuecomment-1037238279
https://github.com/bozbez/win-capture-audio/issues/179

**Comment by z0fa** [comment]
I have tried the latest release of OBS + win-capture-audio plugin and the performance issue seem to be solved, maybe you can just check the plugin code for a possibile fix

**Comment by SaraJLeen** [comment]
Experiencing something quite like this in OBS 28.0.2 -- I had created a scene collection with many scenes for specific games, and matching application audio captures. It seems that the more application audio captures you have, the worse the effect is. Mouse movements will lag every few seconds (in the OS itself) and the applications will experience FPS drops as well...
It's interesting (and problematic!) that the number of Application Audio Captures has an effect here even when they are in inactive scenes.

**Comment by jamespark-unreal** [comment]
28.0.3 has logic to avoid reconnect attempts if the captures are in inactive scenes. Can you see if that helps?

**Comment by SaraJLeen** [comment]
For me, the performance issues seem entirely gone in 28.0.3

**Comment by z0fa** [comment]
yep I can confirm
