### ISSUE TITLE
New UVC camera behaviour causing unintended setting behaviour in non webcams.

### ISSUE THREAD

**Issue by jdudetv** [obsproject/obs-studio#7239]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.0

### OBS Studio Log URL

https://obsproject.com/logs/_QHRw2tThR1h2QQI

### Expected Behavior

Changing settings in the properties menu should only change those settings and nothing else.

### Current Behavior

Changing settings in the properties menu FPS, Resolution, Video format, colour space, colour range etc is pushing default / random settings through to camera setting brightness, contrast etc to 0 or in other cases setting the shutter speed on my camera to 1/8000. been reported to happen with Camlinks but is happening to me on the ZCAM E2 plugged in over USB as a UVC camera. 

Causes the camera to just go black or become unresponsive currently. Also will lock up OBS when pushing the settings through.

### Steps to Reproduce

1. have non webcam UVC camera installed.
2.Change from device default to custom in properties menu
3. change any of the settings
4. the configure video settings will now be changed.

**Comment by prgmitchell** [comment]
I've stated so elsewhere but I want to confirm that have experienced this on multiple devices, both UVC and non-UVC. The repro steps here do not work for me but I am unable to find the exact trigger to reproduce myself.

**Comment by RytoEX** [comment]
Presumably caused by #5480. We'll probably revert that temporarily while we investigate how to reimplement the feature without causing issues.

**Comment by RytoEX** [comment]
We've reverted #5480 for now. We'll revisit it at a later date.
