### ISSUE TITLE
The dialog after pressing the close button can't be tabbed so that you can close the window using only the keyboard.

### ISSUE THREAD

**Issue by CodeYan01** [obsproject/obs-studio#7241]
### Operating System Info

macOS 12

### OBS Studio Version

28.0.0

### OBS Studio Log URL

https://obsproject.com/logs/iXcX77yywgOpK-_t

### Expected Behavior

I should be able to press Cmd+q, then Tab, then press spacebar or Enter to confirm closing the app.

### Current Behavior

It seems to only stay at "No", as pressing Enter would cancel closing the app. There's no highlighted button.

### Steps to Reproduce

1. Start virtual camera or other outputs.
2. Press cmd+q or click the close button.
3. Press Tab. 
4. Press Enter. You will see that it cancels closing the app.
5. Step 2-4 again, but skip step 3. Notice that it still cancels closing the app.
...

### Anything else we should know?

I'm pretty sure that on windows, the correct behavior is observable.

**Comment by PatTheMav** [comment]
Navigation between dialog items with the tab key requires a setting in the "shortcuts" tab of the keyboards settings to be enabled on macOS. This functionality is not enabled by default.

However even with this setting enabled, the dialogbox cannot be navigated using the tab key, which seems like an additional issue with Qt.

**Comment by PatTheMav** [comment]
We've checked this internally and the described functionality is enabled on macOS by enabling keyboard navigation in your accessibility options. That allows you to switch between buttons not only on the prompt but also the entire main applications.

The desired functionality of having a switch between buttons be always available via tab is commonly provided by the operating system and - as explained above - not a default functionality on macOS.
