### ISSUE TITLE
What is this upgrade... 

### ISSUE THREAD

**Issue by SAMYEL06** [obsproject/obs-studio#7243]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.0

### OBS Studio Log URL

None

### Expected Behavior

Nice UI, compatible plugins.

### Current Behavior

Horrible UI, incompatible plugins.

### Steps to Reproduce

1. Update to 28
2. Open
3. Tadaaaa, it's worse than 27.2.
...

### Anything else we should know?

Stick to the old UI, and most of all, work on the compatibility with old plugins.

I'mma revert back to 27.2

**Comment by WizardCM** [comment]
This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels below, and if it's determined that this is indeed a bug, then we will re-open this issue.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
