### ISSUE TITLE
Cursor for Scene item resize handles don't respect rotation

### ISSUE THREAD

**Issue by Richard-Quinlivan** [obsproject/obs-studio#7247]
### Operating System Info

Windows 11

### OBS Studio Version

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/DzZ4Yps15coeWonj

### Expected Behavior

The resize handles for the webcam source should face outwards from the corner

### Current Behavior

The resize handles for the webcam source are flipped from what they should be 

### Steps to Reproduce

1. add webcam source
2. resize webcam source
3.
...

**Comment by WizardCM** [comment]
Could you post a screenshot example?

**Comment by Richard-Quinlivan** [comment]
Sure, here you go

**Comment by WizardCM** [comment]
Confirmed, resize handles don't respect rotation.

![image](https://user-images.githubusercontent.com/941350/189506014-ec5b3010-7a5c-471d-9bed-1de3e048dbd1.png)
