### ISSUE TITLE
Colors and transparency are incorrect when playing some special videos using media sources

### ISSUE THREAD

**Issue by Danjuanlab** [obsproject/obs-studio#7251]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.0

### OBS Studio Log URL

https://obsproject.com/logs/QEV8df8b7NJYKV_N

### Expected Behavior

The video is displayed correctly

### Current Behavior

![OBS vlc](https://user-images.githubusercontent.com/42509669/187951459-8b0573d8-3420-49c3-a00d-866762bef244.png)
![OBS meiti](https://user-images.githubusercontent.com/42509669/187951471-c4446c1e-c9bd-43ad-93e3-1abe473734bc.png)
The video footage is an 8bit 4k 30 60M video shot with the Sony A7M3. Features HRG3 gamma and 709 color spaces. When I load the video using the v28 media source, the colors are displayed incorrectly and come with strange and strange transparency. I also tested in OBS V27 and the display was normal.
I uploaded the original video material to this Google Cloud Drive, maybe you can test it. https://drive.google.com/file/d/16ISIO9knhkVaouYCTgaC-3ERceq8vUKi/view?usp=sharing

### Steps to Reproduce

1.add media source
2.add video file
3.
...

**Comment by jpark37** [comment]
I'll take a look later today. Thanks for providing solid repro info.

**Comment by PatTheMav** [comment]
@jpark37 did you have a chance to take a look at this yet?

**Comment by jpark37** [comment]
Link needs access that he hasn't provided.

**Comment by Danjuanlab** [comment]
> Link needs access that he hasn't provided.

I have allowed to share

**Comment by jpark37** [comment]
This is an 8-bit HDR video with HLG gamma. Are you trying to capture an HDR video? If not, you should use an SDR transfer function like Rec. 709 instead of HLG. If you are trying to take an HDR video, then you should use 10-bit color minimum.

I can add a workaround to OBS, but this combination of video properties is not ideal.

**Comment by Danjuanlab** [comment]
> This is an 8-bit HDR video with HLG gamma. Are you trying to capture an HDR video? If not, you should use an SDR transfer function like Rec. 709 instead of HLG. If you are trying to take an HDR video, then you should use 10-bit color minimum.
> 
> I can add a workaround to OBS, but this combination of video properties is not ideal.

Thanks for the reply, I'm not trying to capture HDR footage, I just found this problem in a test playback video.
The same video can be parsed correctly in V27 version of OBS, but not in V28. Also as I described earlier, when playing it on my computer using obs's media source, it's not just a color issue, it's adding a strange transparency. I don't know if you have compared the effect of V28 and V27 playback.I just tested version 28.0.1, and playing this video on my computer using the media source will have a strange transparency
![无标A题](https://user-images.githubusercontent.com/42509669/190552051-a5096e1a-08c0-4e8a-b6fb-da443818384b.jpg)

**Comment by jpark37** [comment]
I'm looking at the manual for your camera, and you probably want to set your Gamma setting to ITU709 instead of HLG3. I'm pretty confident that will fix your issue, and give you more accurate SDR colors.

I understand why the transparency weirdness is happening, and it's a bit difficult to explain. The short answer is that OBS 28 doesn't expect 8-bit video to use HDR. This didn't happen in OBS 27 because we added HDR support to OBS 28.

**Comment by jpark37** [comment]
Movie and Cine# may also be reasonable Gamma choices (subjective). Just don't use any of the HLG options if you want SDR.

**Comment by Danjuanlab** [comment]
> I'm looking at the manual for your camera, and you probably want to set your Gamma setting to ITU709 instead of HLG3. I'm pretty confident that will fix your issue, and give you more accurate SDR colors.
> 
> I understand why the transparency weirdness is happening, and it's a bit difficult to explain. The short answer is that OBS 28 doesn't expect 8-bit video to use HDR. This didn't happen in OBS 27 because we added HDR support to OBS 28.

I can understand what you mean. In the afternoon, I used SONY A7M4 (422 10bit gamma-HLG3 /color space-BT2020) mode and captured camera images through Elgato camlink 4k capture card. When I select the color space as Rec.2100 PG or Rec.2100 HLG in the OBS video capture device, the preview screen is also translucent as before. And changing the color space to 709 shows normal. PS: I know that camlink 4k does not support 2020 color gamut, I don't know if this is the problem. Because I don't seem to have a capture card that supports the HDR standard at the moment.

But from this, it can be guessed that when the video gamma added to OBS V28 is HLG, the backend code will automatically set the color space to 2100PQ or 2100HLG in order to match HDR, but in fact the color space of the video is 709.

In addition, I don't know if SONY A7M4 (422 10bit gamma-HLG3 /color space-BT2020) mode + a capture card that supports 2020 color gamut and supports HDR capture is the correct HDR input for OBS.
Because some Canon machines have a clear 2100PQ setting, but Sony does not have such a setting.
![屏幕截图 2022-09-16 163440](https://user-images.githubusercontent.com/42509669/190596759-81ff5e9b-e510-4703-9b20-c74e29551605.jpg)
![2无标题](https://user-images.githubusercontent.com/42509669/190596813-f1a8f64f-e26e-4ad6-ac33-9ca52bdc2203.jpg)
![a无标题](https://user-images.githubusercontent.com/42509669/190597614-6fa2c048-9935-4986-bd82-16ef0d2cf9dc.jpg)

**Comment by jpark37** [comment]
> When I select the color space as Rec.2100 PG or Rec.2100 HLG in the OBS video capture device, the preview screen is also translucent as before.

This is a variation of the same problem. YUY2 is an 8-bit pixel format, and OBS does not anticipate HDR being used with 8-bit formats. On a capture device that does support HDR, e.g. HD60 S+, you will be able to select P010 and Rec. 2100 without alpha issues.

> But from this, it can be guessed that when the video gamma added to OBS V28 is HLG, the backend code will automatically set the color space to 2100PQ or 2100HLG in order to match HDR, but in fact the color space of the video is 709.

We don't change the mixing color space based on source color spaces. Users have the flexibility to stream/record SDR/HDR on SDR, or SDR/HDR on HDR.
