### ISSUE TITLE
macOS arm64 DMG download not available on OBS website

### ISSUE THREAD

**Issue by alexsch01** [obsproject/obs-studio#7252]
### Operating System Info

macOS

### OBS Studio Version

28.0.0

### Expected Behavior

The macOS download for ARM64 - apple silicon machines should be available on the OBS website - https://obsproject.com/

### Current Behavior

The macOS download for ARM64 - apple silicon machines is not available on the OBS website - https://obsproject.com/

### Steps to Reproduce

1. Go to https://obsproject.com/
2. Notice that the macOS download is x86-64 and there isn't a button for the arm64 build

**Comment by RytoEX** [comment]
The website has been updated to provide distinct links for Intel (x86_64) and Apple Silicon (arm64) downloads.
