### ISSUE TITLE
Menu tabs are showing on preview even 'Hide OBS windows from screen capture' is enabled

### ISSUE THREAD

**Issue by saukko28** [obsproject/obs-studio#7253]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.0

### OBS Studio Log URL

https://obsproject.com/logs/PsJco7ovEN1pBEf2

### Expected Behavior

I expected the menu tabs not to appear on the preview.

### Current Behavior

For example opening Help menu tab shows the tab window on preview despite having 'Hide OBS windows from screen capture' enabled.
![bugi](https://user-images.githubusercontent.com/8791488/187961443-82c9d112-384b-45e2-be7a-a0f6d2267964.jpg)

(Sorry, I had to take a photo on my camera, because otherwise I couldn't showcase the problem.)

### Steps to Reproduce

1. Enable 'Hide OBS windows from screen capture' in Settings menu
2. Apply the setting by pressing 'OK'
3. Open any menu (File, Edit, View, etc.) or open any other menu like pressing three dots icon on 'Audio Mixer'
4. A window will pop up on the preview window

**Comment by notr1ch** [comment]
This is a known limitation with the feature, unfortunately certain temporary windows like context menus and toolbar tips will not be hidden. Attempting to hide them with the Windows API results in random black squares in the capture.

**Comment by saukko28** [comment]
I was also about to post another issue which is actually a health risk and could cause seizures for an epileptic. It is also related to the same setting.
