### ISSUE TITLE
Unable to stream Windowed Projector into Discord

### ISSUE THREAD

**Issue by supersonicsjm** [obsproject/obs-studio#7254]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.0

### OBS Studio Log URL

https://obsproject.com/logs/iAALd1O8sa8DlFaU

### Expected Behavior

When I create a Windowed Projector and stream into Discord, the feed should match what the Windowed Projector is doing, not display a static image.

### Current Behavior

When I create a Windowed Projector for the scene I am on in OBS, whilst the Windowed Projector itself is fine, when I ask OBS to stream the window to people in a call, it simply projects a static image of the first frame from when I open the stream or Windowed Projector. There have also been a couple of other instances where the window displays in Discord in the middle of a white space or Discord's feed is just completely white, but most instances are just of the static image of my scene.

### Steps to Reproduce

1. Open OBS
2. Right click the current scene in the list of scenes and click "Windowed Projector (Scene)"
3. Maximize the Windowed Projector
4. In Discord, ensure you're logged in and either start a call with someone or join a voice channel
5. Click the "Screen" button at the bottom left
6. Select the Windowed Projector
7. Observe as the feed is static and not showing what the Windowed Projector is currently displaying
...

### Anything else we should know?

The previous version of OBS I was on (27.2) did not have this issue. This is only occurring for me on OBS 28.

**Comment by hazrpg** [comment]
Issue happens with me as well when sharing the projection window to discord.

**Comment by RytoEX** [comment]
Currently cannot reproduce this on OBS Studio 28 on Windows 10.

**Comment by MattyFresh68** [comment]
Mine still runs in discord with both windowed projector in focus and minimized. Cannot replicate.

**Comment by supersonicsjm** [comment]
Just tried again now after my machine has been rebooted and I'm still getting the same issue. If a dev is unable to replicate, happy to jump in a Discord call to demonstrate and diagnose if required.

**Comment by RytoEX** [comment]
I can confirm that this _only_ happens if you are running OBS as an administrator. Discord can capture OBS 28 projectors fine if OBS is not being run as an administrator.

**Comment by Fenrirthviti** [comment]
Discord support has recommended not running OBS as admin, as it's not guaranteed to be able to capture an escalated context from a non-escalated context in Windows. I'm honestly surprised this ever worked at all.

**Comment by jsonvillanueva** [comment]
> I can confirm that this _only_ happens if you are running OBS as an administrator. Discord can capture OBS 28 projectors fine if OBS is not being run as an administrator.
> 
> For tracking purposes, bisected to [ed70de5](https://github.com/obsproject/obs-studio/commit/ed70de55cf70cd6b2a586b6b013d285b0c09f04d) (#6105).
@RytoEX 

Might there be any other reasons for this issue besides the OBS process having administrator privileges? I seem to be running into the same issues as described in #8941 despite running OBS as a non-admin and launching Discord with, and without, admin privileges:

- OBS 29.1.1:

https://github.com/obsproject/obs-studio/assets/29168469/ef621c93-a4f6-46be-9bef-10fee894878b

- OBS 28.0.0 (thought it might just be a regression, but it's here as well for me):

https://github.com/obsproject/obs-studio/assets/29168469/a33ed894-322e-4cec-88ad-6611b02ab91f

**Comment by RytoEX** [comment]
> I fixed this issue on my end after changing a myriad of settings, but the one setting directly responsible for this behavior is Discord's setting Use our advanced technology to capture your screen

Are you saying that enabling this feature in Discord fixed it for you? Or does disabling this feature in Discord fix it for you?

**Comment by jsonvillanueva** [comment]
@RytoEX Enabling this feature fixed it.

**Comment by ibigfire** [comment]
Enabling this feature did not fix it for me, it was already enabled.  It was updating OBS to version 28+ that made it no longer work for me, but it did work previously.  I see the issue was closed, but I don't believe that actually is the full picture.

**Comment by megatrook** [comment]
I was also having this issue, but I think I've found a fix! I launched Discord in administrator mode, and the screenshared Windowed Preview is not having issues anymore when under other aplications. (I'm using OBS 30.0.2, also in admin mode)
