### ISSUE TITLE
OBS fails to launch on Linux Mint 21

### ISSUE THREAD

**Issue by teklynk** [obsproject/obs-studio#7255]
### Operating System Info

Ubuntu 22.04

### Other OS

Linux Mint

### OBS Studio Version

28.0.0

### OBS Studio Log URL

https://pastebin.com/ZNWGEXvC

### OBS Studio Crash Log URL

https://pastebin.com/ZNWGEXvC

### Expected Behavior

Click OBS in the Linux Mint menu to open.
Launch OBS from a terminal.

### Current Behavior

OBS does not launch at all from desktop or from a terminal

### Steps to Reproduce

1. type obs in termnal
2. click the obs icon from the system menu
3.
...

### Anything else we should know?

I included a pastebin of the output from the terminal. This shows the failed messages which all seem to be QT related: 
qt.svg: Cannot open file '/usr/share/obs/obs-studio/themes/Dark/Close.svg', because: No such file or directory
QObject::connect: Cannot connect (nullptr)::valueChanged(int) to WSEvents::TransitionDurationChanged(int)
QObject::startTimer: Timers can only be used with threads started with QThread
QWidget: Must construct a QApplication before a QWidget

**Comment by derrod** [comment]
Your OBS is using Qt6, but you nave an old version of the websockets plugin trying to use Qt5 installed, which causes a conflict. Try removing it.

**Comment by teklynk** [comment]
That worked! Thank you!
For reference:
sudo apt remove obs-websocket-compat
