### ISSUE TITLE
Hotkeys possiblities using onscreen keyboard (accessibility keyboard) downgraded from OBS27 to OBS28

### ISSUE THREAD

**Issue by pkej** [obsproject/obs-studio#7259]
### Operating System Info

macOS 12

### OBS Studio Version

28.0.0

### OBS Studio Log URL

https://obsproject.com/logs/P1xh0KkQqIKjy-9J

### Expected Behavior

In OBS27 it is possible to use any combination of the four modifier keys alt, shift, meta and ctrl and selecting any key from the onscreen accessibility keyboard in macOS.

In OBS28 it is only possible to select a single modifier and any other key, as well as the combination alt+shift and any other key. 

Trying to use any other combination of modifier keys and pressing a key onscreen with the mouse will not register. 

### Current Behavior

It is not possible to assign more than two specific modifier keys to a  hotkey when using the onscreen accessibility keyboard on macOS. Only alt+shift will register any accompanying keypress from non-modifier keys. The modifier keys can be used by themselves with any other key.

### Steps to Reproduce

1. Open "System Preferences" -> "Accessibility" -> select tab "Viewer" 
2. Open "Panel Editing" from the above dialog
3. Press "Add Panel" and select "Keyboard - ISO (Large)
4. Go to the "File"-menu and select "Save"
5. Quit the "Panel Editor"
6. Return to the "Accessibility" preferences panel
7. Hook off "Enable Accessibility Keyboard
8. In the "Accessibility Keyboard" shown on screen press the custom button on the first row to the far right
9. In the "Custom" window select "Keyboard - ISO (Large)"
10. Go into OBS 28
11. Open "Preferences"
12. Go to Hotkeys
13. Choose any empty hotkey
14. Press down different modifier keys on your physical keyboard 
15. Try to combine with any key on the onscreen keyboard
16. Only shift+alt + any other non-modifier key will be registered in the hotkey field in OBS
17. Try different combinations to verify that alt+command, alt+meta, shift+meta, shift+command, command+meta, command+alt + any other onscreen keyboard key isn't registered in OBS
18. Try any three modifier combination and note that it can't work with any non-modifier keys on the onscreen keyboard
19. Also note that any of the above will work with physical keys
20. Note that a four modifier key chord (alt+shift+meta+command) will not combine neither with physical keys, nor onscreen keyboard keys.
21. All of the above is working in OBS27
...

**Comment by pkej** [comment]
Notice that repeating the steps on OBS27 will show everything working.  And loading the OBS27 settings with OBS28 will keep the keyboard assignments, and OBS will react to the multikey combinations.

**Comment by PatTheMav** [comment]
This doesn't seem limited to the accessibility keyboard but is also an issue with a physical keyboard:

* The only other second modifier accepted by the settings screen is the shift key
* No other combination (CMD+Alt, CMD+Ctrl, Alt+Ctrl, etc.) is accepted

We introduced a few changes to the hotkey system to get them working as expected on macOS in 28, including accepting hotkeys when OBS is not in focus and after a secure input field was shown to the user, so it's very much possible that the issue was introduced by that.

**Comment by PatTheMav** [comment]
We've been able to identify the exact changes to Qt6 that lead to this issue, we opened an upstream issue report for this:

https://bugreports.qt.io/browse/QTBUG-106516

There is no obvious or simple solution for us to fix this right now, so until Qt fixes this (or we come up with a workaround that doesn't break the screen for other OSes) this means the following for macOS users:

* You can use combinations of a single modifier + shift + your desired key
* Any combinations of `CMD`, `CTRL`, or `ALT` won't work

We understand this is an inconvenience and possible regression, but it's an issue with our core dependency Qt, limiting our current options.
