### ISSUE TITLE
Large GUI text in V28

### ISSUE THREAD

**Issue by fxscreamer** [obsproject/obs-studio#7260]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.0

### OBS Studio Log URL

https://obsproject.com/logs/JfReb3Y8AEH2bIdl

### Expected Behavior

Text was much smaller on V27.2.4. Normal sized. Screen is 4K with 175% scaling.  Going to V28 made the font at least twice as large, bulky, bloated, ugly.
![Capture2](https://user-images.githubusercontent.com/112675426/188050708-81289827-599e-4119-a6d4-2bf929a6b879.JPG)

### Current Behavior

Font at least twice as large, bulky, bloated GUI, ugly. Buttons are large and obtrusive. Can't scale OBS UI.
![Capture](https://user-images.githubusercontent.com/112675426/188050724-72c40972-a2c4-44cd-9483-2c518decbfef.JPG)

### Steps to Reproduce

1. Run V27.2.4
2. Upgrade to V28 through OBS
3.
...

### Anything else we should know?

Never happened on any other version of OBS ever.

**Comment by feetstv** [comment]
You can switch back to the Dark theme in OBS Settings -> General.

**Comment by iesvme** [comment]
I also feel the padding of Yami is too large. It would be better to customize the resizing.

**Comment by Myrthian** [comment]
Even the dark theme doesn't fully alleviate the issue: 
![00](https://user-images.githubusercontent.com/30933093/188065167-2ab8aab4-6042-4e87-93fc-150b7f96a4e5.jpg)

**Comment by demonkingzaine** [comment]
I'll chime in and say that I have similar issues, with the additional annoyance that context menus and the like are all cut off. 

Switching to the dark theme alleviates some of this but doesn't fix the issue.

**Comment by akiirui** [comment]
We need a option to set scale percentage. 100% / 125% / 150% / 200% and etc...

Just like telegram-desktop.

**Comment by Fenrirthviti** [comment]
So, there's a few issues being conflated here. First, if you don't like the Yami theme, then you are welcome not to use it. "I don't like it" isn't a valid bug report, and isn't actionable on our end. The original report here falls in this category, so I'm going to go ahead and close this issue.

However, if there are issues with the Dark theme, those are considered valid issues and for the short term, I would like to get them corrected. There were some very minor inconsistencies between Qt5 and Qt6 with Dark theme, even though we didn't really make any changes to Dark. If you have a specific problem with the Dark theme in OBS 28, please open a new issue with that specific problem, so that we can take a look and address it appropriately. Please try and keep those reports to specific components of the UI, and not general reports of "it looks weird".

**Comment by fxscreamer** [comment]
Updating to V28 did an automatic override of my visual settings, so it certainly looked like a bug. I have never ran Yami theme ever for OBS. I didn't even know it was a theme. After countless upgrades, this was never an issue... so technically you could still say it's a bug because it wasn't honoring my initial settings and it simply appeared visually broken on upgrade. This happened everytime I went from v27 to v28.... no other version ever did this.

My complaints are legitimate. No need for hostile responses saying "the user is the problem."

**Comment by Fenrirthviti** [comment]
Apologies if the response comes off hostile, but nowhere did I state that the user is the problem. I'm just trying to avoid this thread turning in to non-actionable complaints about not liking the new theme when it's easy to just switch back to Dark. We already knew going in that a small number of users would be unhappy with the new theme, and that is why Dark was left in as an option (which can be selected in Settings -> General, if anyone is unaware where the theme setting is).

As mentioned, if there are actual issues or bugs with the Dark theme itself, they should be reported as separate issues so we can look at those individually and correct them where we can. We knew about a few small quirks with the Qt6 upgrade, and tried our best to fix as many as we could, but we might have missed some edge cases there, so those reports would be very helpful to us.

The theme was set to Yami for all users of 28 on purpose. This isn't a bug, and is not something we are going to change. We have gone through this in the past when we switched the default from System to Dark, and received a number of similar complaints. People don't like change, but in our experience so far, the majority response has always been a positive one.

I understand the perception of forcing a settings change can be read as a loss of trust with the application, but the decision was not made lightly. As it's an entirely visual change only (we would never change any functional settings, without good reason or plenty of notice), we felt that just telling users to switch back to Dark if they didn't like it was sufficient enough to go forward.

Thank you for understanding, and sorry for the trouble.

**Comment by fxscreamer** [comment]
That makes sense. It really boiled down to confusion on the upgrade since I've never witnessed that before. Once I realized it was a simple theme change, all was well.

Have you considered a welcome message for V28 showing the new Yami theme and reminding people how to switch it? Would probably clear all that up.

**Comment by akiirui** [comment]
I think the main problem is the change in QT6 for HiDPI.
For users using fractional scaling like 150%, OBS v28 will only shows the user interface with an integer multiplier.
But it is different with the previous interface scaling in QT5 (some UIs shows 200% and other shows 100%), that's why these users think there is something wrong with OBS28's interface.

**Comment by akiirui** [comment]
Here are some snapshots of different HighDpiScaleFactorRoundingPolicy on 150% 4K monitor.
1. `Round`
![1-Round](https://user-images.githubusercontent.com/3736910/189727557-95442f1b-020f-4179-9837-8cce850dc179.jpg)

2. `Ceil`
![2-Ceil](https://user-images.githubusercontent.com/3736910/189727568-e12ca7b3-5a69-4e48-8cf9-978f98b098a2.jpg)

3. `Floor`
![3-Floor](https://user-images.githubusercontent.com/3736910/189727569-0c42fdd2-95dd-4012-85f4-bf9b421dcf53.jpg)

4. `RoundPreferFloor`
![4-RoundPreferFloor](https://user-images.githubusercontent.com/3736910/189727575-f64b06e7-be5b-4df4-a313-14f15580a771.jpg)

5. `PassThrough (obs's default)`
![5-PassThrough](https://user-images.githubusercontent.com/3736910/189727578-45af5366-e406-4a53-86a6-7c13a5436493.jpg)

@fxscreamer maybe you can add a environment `QT_SCALE_FACTOR_ROUNDING_POLICY`, value is `Floor` or `RoundPreferFloor`. It's may let obs looks like v27

**Comment by thomaswnr** [comment]
It would be helpful if you could set the ui font size yourself in the settings.

**Comment by thomaswnr** [comment]
It would be helpful if you could adjust the ui font size yourself in the settings.

**Comment by Luckz** [comment]
Looks like 2005-esque _ugly Linux software_ with that theme.

**Comment by RichyT** [comment]
"we felt that just telling users to switch back to Dark if they didn't like it was sufficient enough to go forward."

I didn't even know this was an option, just that things suddenly looked ugly (like happened with Thunderbird). If you're going to tell users this, it might be better to tell them in the app when they upgrade than having them have to seek it out in bug reporting forums.

That's just a quality of life/first world problems thing though. Thanks for all the good work.

**Comment by Fenrirthviti** [comment]
We did communicate it in the app, when we did the update, through the patch notes that popped up.
