### ISSUE TITLE
Check for missing files falsely reports files are missing for images with sources from a URL

### ISSUE THREAD

**Issue by DaBenjamins** [obsproject/obs-studio#7264]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.0

### OBS Studio Log URL

https://obsproject.com/logs/mscwKMHX9VNpjLOb

### Expected Behavior

No Missing Files Dialog box should open when opening a Scene Collection with images using URLs as there source.

### Current Behavior

Missing Files Dialog box opens, and lists all images that have sources pointing to a URL

### Steps to Reproduce

1. Create a Image source
2. add URL to the filename box on the open file dialog box
3. switch scene collection from and back to
4. see missing files dialog box
...
![obs64_UHvFqu9Hiv](https://user-images.githubusercontent.com/26729589/188060807-0d1dddaa-3e8e-41b4-b21a-5d02780ee45c.png)

**Comment by WizardCM** [comment]
Technically, this is correct. The file that File Explorer points to internally is temporary and doesn't exist once nothing is using it. When you switch back, it downloads it again and stores it in the temp folder with a different name.
