### ISSUE TITLE
Windows 8.1: Updater provides OBS 28 with no compatibility warning, unable to start program

### ISSUE THREAD

**Issue by ray890** [obsproject/obs-studio#7268]
### Operating System Info

Other

### Other OS

Windows 8.1 Pro x64

### OBS Studio Version

28.0.0

### OBS Studio Log URL

Unable to upload. Program does not start.

### Expected Behavior

The updater should have only offered 27.2.4, if that is the last version to work on Windows 8.1

### Current Behavior

The updater updated the program to 28.0 without warning the user that the program may not work, and has rendered the program unable to start.
![image](https://user-images.githubusercontent.com/11812575/188179460-b8601c61-9b2d-433b-bae9-87763be2cce1.png)

### Steps to Reproduce

1. Be on an unsupported operating system
2. Open the program, it will present you with a pop-up asking user to update
3. Update now
4. After updating, open the program, and it will not start
...

**Comment by RytoEX** [comment]
Will be fixed by #7261 , which will prevent the updater from running on Windows versions below Windows 10 and issue a warning.
