### ISSUE TITLE
Recording for too long causes files to be turned into audio files

### ISSUE THREAD

**Issue by Sigel2134** [obsproject/obs-studio#7269]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.0

### OBS Studio Log URL

https://obsproject.com/logs/yW1pLcN83khyD2Q3

### Expected Behavior

I expected the recording function to properly record my videos with audio and video intact.

### Current Behavior

However ever recording I have that went past about the 10 minute mark doesn't function. Playing them in VLC doesn't work, Windows media player only plays the audio, and premiere pro crashes if importing those corrupted files.

![image](https://user-images.githubusercontent.com/112714689/188186406-09ab3e8e-b848-461e-a45c-12911a450e0c.png)

### Steps to Reproduce

1.Record for more than 10 minutes.
2.Check your videos to see if any appear to still be loading.

### Anything else we should know?

The files that do have a thumbnail on them are both about a minute long

**Comment by Mister36MN** [comment]
Thanks for the report, we will look into it. 

In the meantime, it's highly recommended to record using MKV then remux to mp4 afterwards, specifically to prevent corrupted files. It's also most not recommended to use CBR when recording, use the quality presets in simple mode or the CQP preset.

**Comment by derBrodi** [comment]
I have the same problem .... i tryed 3 time to record a video of 20 minutes each .... same thing here. it results always as an audio-file .... then i tryed to change the safe-destination from a USB-HardDrive to an internal SSD-FlashDrive .... i recorded a 4th 20-minute-Video .... that was succesful saved as an mp4-videofile ... maybe it was luck .... maybe it solved the problem .... i will check it in the future ...
