### ISSUE TITLE
PlayStation Remote Play seems to undergo HDR > SDR conversion while the input is already SDR

### ISSUE THREAD

**Issue by RaienryuuNoNatsu** [obsproject/obs-studio#7271]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.0

### OBS Studio Log URL

https://obsproject.com/logs/HennRlQgfRnLDXbu

### Expected Behavior

I will go in more details in the last part of this form, but what I was expecting to happen was proper tonemapping. Or, to be precise, that nothing was done to the input, as it's already SDR by default. This behaviour also happens with local programs. I didn't have any game to test, so I tried with Nox Player, as I did stream it before.

### Current Behavior

The input seems to be treated as HDR even if the built-in HDR setting in PlayStation Remote Player is off. About Nox Player, not much to say there for the time being.

### Steps to Reproduce

1. Either on PS4 Pro/5, change the HDR setting to be on only for games that actually use it.
2. Launch a non-HDR ready game.
3. Game Capture doesn't seem to work for Remote Play, I'm not sure if it's a me thing, or it's normal. So, I use Windows Capture Mode.

### Anything else we should know?

Okay, now for the details. First, my TV is an **LG UN73006LC** which, unfortunately, doesn't really give me much infos about the current output, but should help nonetheless. So, both on my PC and on PS5 with HDR ON, the output is: 2160p, HDR, BT.2020.

To be more specific, I'm running **Windows 10 Pro 21H2 (build 19044.1889)**. As GPU, I have an **NVidia GTX 1060 6GB** set to output 8bit RGB in full range (driver version 512.15).

By default, I set my PS5 to disable HDR when a game doesn't support it internally (note that either fully ON or selectively ON made no difference in OBS). All other colour related settings are set to automatic. So, when I launch a non-HDR game, the output does change. However, unfortunately, my TV doesn't tell me if it's using Rec.709. The output is simply: 2160p, telling me HDR and BT.2020 aren't used/assumed anymore.

Long story short:
1) PS5 with HDR ON: 2160p, HDR, BT.2020 (this is true for my PC output as well).
2) PS5 with HDR OFF: 2160p.

So, on the PS5 side of things, the output seems to be correctly assumed as SDR.

![image](https://user-images.githubusercontent.com/31509027/188217650-ee8b135d-adb7-4988-bbde-ef3580045c5b.png)
About PlayStation Remote Play: to enable HDR, the **Microsoft HEVC Video Extension** is needed, and the local PC on which it's running needs to have HDR ON. At the moment of writing this and taking screenshots, Windows HDR option is ON, while on Remote Play it's OFF. I also wanna add that I read the work in progress Wiki about this version, and I left the brightness set to 40, and kept the default SDR White level value to 300 nits and the HDR peak to 1'000 nits in OBS.

![image](https://user-images.githubusercontent.com/31509027/188219876-bd9d84d2-e0cb-44a7-955f-0291c3708718.png)
This is what the output looks like in Remote Play, aside from losing some sharpness (that's fine, I'd rather not filter it).

![1](https://user-images.githubusercontent.com/31509027/188221053-8166169e-bdd3-4a91-92e4-769c98d3ed23.png)
This one is weird. Capturing this screenshot with the Snipping tool, it's overly bright. What I actually see in OBS is muuuuch darker. This could be what the Wiki meant by "OBS Reinhard SDR conversion displays different results from what Windows does". Nonetheless, being brighter or extremely dark, it's not what Remote Play outputs.

![image](https://user-images.githubusercontent.com/31509027/188221629-99990d1e-d327-4a30-a42f-777fa1d195f7.png)
Before I keep going, these are the settings I use in terms of colours. While the Rec.2100 (HLG) colorspace displays brighter results (yet not the correct ones), it shouldn't be the correct output. Remote Play is limited to 1080p anyway, and the output is SDR by default, which led me to keep those settings.

![image](https://user-images.githubusercontent.com/31509027/188222689-d8fbedab-8db9-490b-b40f-00065ecbb26c.png)
To demonstrate the problem, this is the correct behaviour in OBS 27.2.4. Aside from the SDR White level and the HDR peak (which aren't a thing here), all other colour settings are exactly the same. Windows runs with HDR ON, and Remote Play has it OFF.

**NOTE**: As I mentioned Nox Player earlier, both versions of OBS behave the same way. The output is correct in version 27.2.4, while in version 28, it does the same thing as Remote Play. In this case, it's a bit easier, as I can just turn Windows' HDR OFF, and that actually fixes Nox Player. I find, however, that this is a workaround, and not the proper behaviour which the previous version actually displayed.

![image](https://user-images.githubusercontent.com/31509027/188224309-2aa6398d-e11c-431a-9c66-fb907709445a.png)
So, with all the details down, here's what I found strange. If I apply color correction, which only works with SDR inputs, nothing happens. Parameters are obviously more than exaggerated there, to show they're doing nothing.

![image](https://user-images.githubusercontent.com/31509027/188224531-8a7501ca-9bea-4f30-80bf-7f27cb21eff2.png)
So now, what I do is apply tonemapping and make it SDR. And there we go, color correction now works.

At this point my question is: why is my canvas assumed to be HDR, when every single input is SDR? What this looks like to me is, OBS implies everything is HDR by default > Auto-conversion to SDR (which I guess doesn't happen IF I change color settings to HDR parameters and use HEVC instead?) > Output is wrong because the source isn't actually HDR > But still assumed HDR when using filters???

I'm not sure if it's a bug or if I'm doing something wrong. I'll be waiting for any input on what else to try to hopefully fix it. Thanks in advance for the hard work and awesome update, and for the eventual help.

**Comment by jpark37** [comment]
The Remote Play window is assumed to be HDR because it is running on an HDR screen (your LG is reporting `RGB_FULL_G2084_NONE_P2020` in the log). We don't know of a way to get Windows to tell us if a window is actually SDR on HDR, so we assume all windows an an HDR screen are HDR. You can work around this by disabling HDR in Windows display settings.

In the future, maybe we could add a checkbox to window capture properties to force SDR interpretation of a window an on HDR monitor although we already have a billion settings no one understands as it is.

**Comment by RaienryuuNoNatsu** [comment]
> The Remote Play window is assumed to be HDR because it is running on an HDR screen (your LG is reporting `RGB_FULL_G2084_NONE_P2020` in the log). We don't know of a way to get Windows to tell us if a window is actually SDR on HDR, so we assume all windows an an HDR screen are HDR. You can work around this by disabling HDR in Windows display settings.
> 
> In the future, maybe we could add a checkbox to window capture properties to force SDR interpretation of a window an on HDR monitor although we already have a billion settings no one understands as it is.

Thanks for the reply. So for the time being, that's the only real solution to it. Thanks for taking the time to look into it and give an explanation. Be looking forward to an eventual implementation, should you decide to do so.
