### ISSUE TITLE
Scene transitions are grayed out when scene collection is changed

### ISSUE THREAD

**Issue by style1925** [obsproject/obs-studio#7280]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.0

### OBS Studio Version (Other)

28.0.1

### OBS Studio Log URL

https://obsproject.com/logs/jf8KR4FuHCoRqgss

### Expected Behavior

Scene transitions can be changed even after changing the scene collection.

### Current Behavior

Scene transitions are grayed out.

### Steps to Reproduce

1. change the scene collection
2. Scene transitions are grayed out

28.0-rc2

https://user-images.githubusercontent.com/1337354/188270494-c5e9a288-cf17-4477-9433-92f0c6cf3a54.mp4

28.0.1

https://user-images.githubusercontent.com/1337354/188270496-55ec9e91-32fa-4531-86ee-e62e8ae044e9.mp4

### Anything else we should know?

It does not occur until 28.0 rc2.
Changing the scene cures the gray out. (It will be grayed out only when changing scene collections.)

**Comment by kkartaltepe** [comment]
Replicated on linux.

**Comment by yoshinorisano** [comment]
I also reproduced the bug and investigated it using Visual Studio's debugger.
I found that the following pull request produces this bug.
https://github.com/obsproject/obs-studio/pull/7200/

**Comment by PatTheMav** [comment]
The observation is correct - the change introduced by that commit forces a scene item to be selected even though we purposefully clear the selection before importing the new scene selection.

This leads to a forced scene transition twice, which starts a transition (disabling the transition dock), but as no actual transition takes place, the dock is not activated again until users interact with the scene setup.
