### ISSUE TITLE
NDI does not work

### ISSUE THREAD

**Issue by CBAshley13** [obsproject/obs-studio#7281]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.0

### OBS Studio Log URL

https://obsproject.com/logs/uu_piR_O_UIdo_qD

### Expected Behavior

NDi should work.

### Current Behavior

Receive message upon opening that the NDI plugin did not load.

### Steps to Reproduce

1.  Open OBS
2.
3.
...

**Comment by tytan652** [comment]
NDI plugin is not available for OBS 28 for now.
https://obsproject.com/kb/obs-studio-28-plugin-compatibility
