### ISSUE TITLE
New Mac Display Capture causes Unity projects to freeze

### ISSUE THREAD

**Issue by pilky** [obsproject/obs-studio#7283]
### Operating System Info

macOS 12

### OBS Studio Version

28.0.0

### OBS Studio Log URL

https://obsproject.com/logs/fZ6wZ4dM07Btm7pR

### Expected Behavior

The new Display capture would work without causing issues elsewhere

### Current Behavior

If I add the new macOS Display Capture as a source (specifically the whole display capture) I find that apps built using Unity will start to freeze up when in the background. I've uploaded a video showing the problem (http://pilky.me/images/displaycapturebug.mp4) but I'll explain it below as well

### Steps to Reproduce

1. Launch something built in Unity (either needs to have movement or to be controlled while in the background)
2. Add a macOS display capture source and point it to a display
3. Observe the Unity app 

### Anything else we should know?

First up, in case it matters, my display setup is a 4K main monitor running scaled to effectively 1440p, plus two 1440p monitors (one rotated to portrait). I'm running on an M1 Ultra with macOS 12.5

My stream setup involves a 3D overlay built in Unity (essentially a game world) with parts of it I can chroma key out to show a display capture of my screen, so people can see what I'm working on. In terms of OBS 28 I tried capturing with the new capture tools, with a window capture for the overlay (running on a second display) and a screen capture for my main monitor. 

Unfortunately while streaming I noticed the overlay would just drop frames or pause when not the frontmost app (note, the entire window could be visible on the second display). Sometimes this wouldn't happen for a few minutes, sometimes it would happen immediately after switching away. After some messing around I discovered that it was the screen capture that was causing it. I had the overlay frozen and the second I removed the display capture source in OBS it started again. 

Some important notes:
- This seems to affect stuff built with Unity in general. I tried with the URP sample project Unity provides and got similar results
- It isn't OBS dropping frames during the capture, it is the Unity-built app/game itself which is freezing up (though not beachballing)
- You don't need to be capturing the Unity-built app/game itself. It can be on a separate display to the display capture with no other capture source on it and it will display this behaviour
- Using the new Window capture with the legacy screen capture seems to let me work around the issue, but using deprecated tech isn't ideal

**Comment by PatTheMav** [comment]
Please define "background" - do you mean you launch the Unity app, but then switch to OBS? Also does the Unity app run in fullscreen?

**Comment by pilky** [comment]
> Pardon me, didn't watch the video. So I just tested this with a Unity-based game running in background and its idle animations are captured just fine via window capture (also without any framerate issues). I guess you got something like input monitoring activated on that Unity demo project to receive controller input while in the background?

Yeah, I tweaked it in Unity so it will register background control inputs (it's just a setting). It was quicker than me making something animate and I wanted to show it happening with the demo project to show it's not just my own project

> Note that this only works if the game is not in fullscreen, as SCK will not capture frames from an app not visible to the user (and apparently having a game/app in fullscreen effectively puts it on a different space and "deactivates" it when you are not active on that space). Putting the app into full screen on a different _physical_ display (and in the foreground) should _not_ be affected however (and your example runs on the same active screen).

So in my case the app is in windowed mode and on a different physical display to the display being capture by OBS. It's also worth noting that you do not need to capture the Unity app in OBS with a window capture for the Unity app to start stuttering, you just need a display capture and the app to be on a different display. Window capture of the Unity app actually works flawlessly if you don't use the new display capture on another display too.

This feels like it's either going to be a flaw in how DisplayCaptureKit is used in OBS or a bug in DisplayCaptureKit itself. Either way, given I believe Apple helped implement this in OBS, I figured it was best to file a report here as hopefully the can check both possibilities (or at least it can hopefully be ruled out in OBS so I can file a bug with Apple directly)

**Comment by PatTheMav** [comment]
So I just had the same Unity game I used for testing moved on a second screen, added that screen via display capture, and I have the idle animations captured just fine. With another game I had it pause any animation/rendering when the app was not in foreground, so it seems to also require the game/app to continue rendering when not in focus.

TBF I used my second Mac as a "virtual" second display, so maybe that changes the baseline setup so much that it's not comparable.

It also seems as if SCK works best if the app/game in question generates frames continuously - I've had desktop, app, and window capture work without issue on that second screen and with the game that continued to run in the background. With the other game, I ended up with black frames or had to cycle the "show cursor" checkbox once or twice before it captured a frame.

> Either way, given I believe Apple helped implement this in OBS I figured it was best to file a report here as hopefully they can check both possibilities (or at least it can hopefully be ruled out in OBS so I can file a bug with Apple directly)

If it's fine by you, could you post the FB id here, so I can refer our Apple contacts to your report?

**Comment by pilky** [comment]
Sorry for the delay in getting back to you. I've just managed to get a feedback filed with Apple. It's FB11461625 (I've linked to this issue in the feedback)

**Comment by pilky** [comment]
@PatTheMav It seems this was fixed in macOS 13.1. Just upgraded and tested it and it seems to work fine now

**Comment by PatTheMav** [comment]
That's great news - let's hope we got most kinks hammered out of SCK by now.
