### ISSUE TITLE
Unhandled exception in w32-pthreads.dll

### ISSUE THREAD

**Issue by PythooonUser** [obsproject/obs-studio#7286]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

28.0.1

### OBS Studio Log URL

https://obsproject.com/logs/HenfRC6nmIk5Yifs

### OBS Studio Crash Log URL

https://obsproject.com/logs/ERGCy13uTz0pX9yf

### Expected Behavior

OBS should start normally.

### Current Behavior

OBS crashes (maybe 9 out of 10 times).

### Steps to Reproduce

1. I installed OBS 28.0.1
2. I installed Stream Deck Plugin for Qt6
3. I try to start OBS

**Comment by notr1ch** [comment]
It looks like you have multiple copies of OBS plugins. Could you show the contents of `C:\ProgramData\obs-studio\plugins` if it exists? Also is there a `OBS_PLUGINS_PATH` environment variable set? (Open a command prompt, and type `set` to see)

**Comment by PythooonUser** [comment]
Ha, maybe that is why I see this in the "Tools" menu. I'll check that.

![image](https://user-images.githubusercontent.com/13063023/188323087-448297ff-697a-4e6e-b8ad-01b4c0bdd418.png)

**Comment by PythooonUser** [comment]
Such a folder does not exist, but I have these environmental variables set.

```
OBS_PLUGINS_DATA_PATH=E:\Program Files\obs-studio\data\obs-plugins
OBS_PLUGINS_PATH=E:\Program Files\obs-studio\obs-plugins\64bit
```

**Comment by notr1ch** [comment]
That would do it. Any idea what you installed that might have set these?

You can remove them from the system control panel (search start menu for "environment variables") and it should fix your issue.

**Comment by notr1ch** [comment]
We think this is being caused by the StreamDeck plugin. Did you change the installation directory when installing it?

**Comment by PythooonUser** [comment]
Yes, I installed both applications in a different directory.

For Stream Deck I followed [the OBS 28 upgrade guide](https://help.elgato.com/hc/en-us/articles/8815141056013-Elgato-Stream-Deck-Plugin-Update-for-OBS-Studio-28). Maybe that did something weird. It's hard to tell.

**Comment by PythooonUser** [comment]
But thanks @notr1ch , that fixed it :)
