### ISSUE TITLE
Mac OS 13 audio cannot be captured

### ISSUE THREAD

**Issue by allinu** [obsproject/obs-studio#7293]
### Operating System Info

Other

### Other OS

Mac OS 13

### OBS Studio Version

Other

### OBS Studio Version (Other)

28.0.1

### OBS Studio Log URL

https://obsproject.com/logs/7bkQOAJXucyFHmZV

### Expected Behavior

- Ability to successfully record computer audio

### Current Behavior

- Audio cannot be recorded successfully

### Steps to Reproduce

mac 13 and normal install

### Anything else we should know?

- I have install OBS before 28.0.0 and uninstall with cleanmymac app.
- I have install blackhole before but now uninstall and reboot

**Comment by allinu** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/32992109/188341035-1b9ce2ab-4611-4529-8281-338c8dc6bdc8.png">

**Comment by RytoEX** [comment]
I'm fairly certain that this is expected. Desktop audio devices are not exposed by macOS to OBS in this way. You _can_ select the Desktop audio by using a "macOS Screen Capture" source on macOS 13+.
