### ISSUE TITLE
Error when running cmake command on MAC OS 10.9.2

### ISSUE THREAD

**Issue by fredotech** [obsproject/obs-studio#73]
CMake Error at obs/CMakeLists.txt:20 (find_package):
  By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Widgets", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Widgets" with
  any of the following names:
-    Qt5WidgetsConfig.cmake
-    qt5widgets-config.cmake
  
  Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set
  "Qt5Widgets_DIR" to a directory containing one of the above files.  If
  "Qt5Widgets" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!
See also "/Applications/obs-studio-master/cmbuild/CMakeFiles/CMakeOutput.log".
See also "/Applications/obs-studio-master/cmbuild/CMakeFiles/CMakeError.log".

**Comment by bojanstef** [comment]
Initially I was not able to run `cmake`. Then after setting up the `QTDIR` in my zshrc I was able to run `cmake`. For example...

1. Open your `~/.zshrc` (or `~/.bashrc`) in some text editor (`vim ~/.zshrc`).
2. Paste the following export:
```
# Set QT5 directory for OBS development
export QTDIR=/usr/local/opt/qt # or wherever you qt is located
```
3. Source your `~/.zshrc` (or `~/.bashrc`) (`source ~/.zshrc`).
