### ISSUE TITLE
The same PulseAudio (on pw-pulse) input captured twice has large random delay in second copy of source.

### ISSUE THREAD

**Issue by xorgy** [obsproject/obs-studio#7302]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

28.0.0

### OBS Studio Log URL

https://obsproject.com/logs/W4qivhtq1dC-dqxT

### Expected Behavior

Two sources of the same input should be synchronized, and have a predictable latency between loads.

### Current Behavior

Two sources from the same input are desynchronized by a random amount. Often the desynchronization is on the order of several seconds if starting a project with two such sources open at the beginning; usually less when the second source is added at runtime; but in both cases, the delay is random and very noticeable.

I also experienced this behaviour on OBS 27.

### Steps to Reproduce

1. Add two PulseAudio sources for the same input.

### Anything else we should know?

A general improvement that would also moot this issue, would be to support multiple filter paths in a filter chain, rather than just one (possibly through nodes, or railroad diagrams, or busing).
My current issue is that I want to use RNNoise to detect voice activity, and make my voice louder than the ambient sound I'm also capturing with my stereo microphones. If I could support this use case with a single source of this input, it wouldn't matter that two such sources were desynchronized, though probably the infrastructure for this feature could also solve the issue directly.

**Comment by kkartaltepe** [comment]
> Two sources of the same input should be synchronized, and have a predictable latency between loads.

This is not how obs works. Audio sources will add buffering if your system cannot keep up with real time. You can try the new advanced audio low latency mode if you want relatively fixed latency with lots of audio artifacts when your system cannot keep up with real time.

**Comment by kkartaltepe** [comment]
It should be noted that if you are trying to do advanced audio filtering and sidechaining there is some minor support for this in obs but you are generally better off processing in an audio workstation and then using the input from that for obs. This is trivial to integrate with the jack source.

**Comment by xorgy** [comment]
> > Two sources of the same input should be synchronized, and have a predictable latency between loads.
> 
> This is not how obs works. Audio sources will add buffering if your system cannot keep up with real time. You can try the new advanced audio low latency mode if you want relatively fixed latency with lots of audio artifacts when your system cannot keep up with real time.

... what? I think you didn't understand the issue. This is literally the same audio input, the same device. And no, I'm nowhere near running out of resources to keep up with realtime, and the input buffers are never five seconds long.
