### ISSUE TITLE
Unsupported OS dialog uses bad characters

### ISSUE THREAD

**Issue by JThundley** [obsproject/obs-studio#7304]
### Operating System Info

Other

### Other OS

Windows 7

### OBS Studio Version

28.0.0

### OBS Studio Log URL

https://obsproject.com/logs/l-j3KWFNpuJj02Gq

### Expected Behavior

I expected some kind of symbol to show up between the different menu locations it explains in the end.

### Current Behavior

It shows a lowercase "a" with a caret above it jjoined with cross and apostrophe.

### Steps to Reproduce

1. Start OBS 27 on Windows 7
2. Try to update it
3. Receive the dialog with the bad characters.
...

### Anything else we should know?

See a screenshot here: https://i.postimg.cc/SsRHTC3Y/image.png

**Comment by JThundley** [comment]
Forgot to mention that I am using American English and no other languages. My locale is US.

**Comment by kkartaltepe** [comment]
Win7 is unsupported, if the unsupported dialog doesnt render correctly there I don't think anyone is going to try and fix it. Thanks for reporting though.

**Comment by notr1ch** [comment]
Given the message is explicitly targeting those unsupported OSes it seems like we should make an effort to to fix it. It looks like UTF-8 sequences require compilation with `/utf-8` in order to work correctly.
