### ISSUE TITLE
[Regression] Dragging sources between other sources functionality change from v27

### ISSUE THREAD

**Issue by lindenkron** [obsproject/obs-studio#7321]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.1

### OBS Studio Log URL

Unnecessary 

### Expected Behavior

Dragging a source in between two sources should act as previous.

Dragging a source between two sources should keep that source dropable between the two sources:
Example:
https://streamable.com/t1yu1q

### Current Behavior

Dragging a source in between the two sources, now has a weird space (probably due to new margin space) where dropping a source will instead place it at the very bottom of the list, which can be a nuisance.

Example:
https://streamable.com/autrdp

### Steps to Reproduce

1. Create three sources
2. Drag and drop.

**Comment by RytoEX** [comment]
> OBS Studio Log URL
> Unnecessary

Please let us decide if the log is necessary or not.

**Comment by lindenkron** [comment]
> > OBS Studio Log URL
> > Unnecessary
> 
> Please let us decide if the log is necessary or not.

As you wish:
https://streamable.com/tf8bxt[
](https://obsproject.com/logs/nwcUOxVc8pcdG2sJ)

**Comment by gxalpha** [comment]
I reported this upstream as [QTBUG-106395](https://bugreports.qt.io/browse/QTBUG-106395).

For reference, the spacing causing this was added intentionally in #6896 (although the bug wasn't added on purpose obviously). Due to the items being larger in Yami-based themes, the issue is a bit less noticeable there as you're more likely to hover above another item rather than exactly above the spacing.

**Comment by dkonopka** [comment]
Confirming it, this feature here https://obsproject.com/tools/browser-drag-and-drop is not working properly in v28

**Comment by WizardCM** [comment]
> Confirming it, this feature here [obsproject.com/tools/browser-drag-and-drop](https://obsproject.com/tools/browser-drag-and-drop) is not working properly in v28

Such an issue would be unrelated to this one. I am not reproducing your described issue.

**Comment by dkonopka** [comment]
@WizardCM did you checked on Windows? because on MacOS it is working properly

**Comment by WizardCM** [comment]
> @WizardCM did you check it on Windows? because on MacOS it is working properly

Yes, I primarily test on Windows.

**Comment by RytoEX** [comment]
> Confirming it, this feature here https://obsproject.com/tools/browser-drag-and-drop is not working properly in v28

The feature you're describing and the bug described in this Issue are separate. The demo you link to works fine for me on Windows. It will not work if OBS is run as admin, as noted on the page itself. Let's keep this Issue focused on the internal drag-and-drop action of the Sources dock.
