### ISSUE TITLE
[macOS VT HEVC Encoders] Remuxed recordings use hev1 instead of hvc1, can't be used by system software without retagging

### ISSUE THREAD

**Issue by jcm93** [obsproject/obs-studio#7322]
### Operating System Info

Other

### Other OS

macOS 13

### OBS Studio Version

Other

### OBS Studio Version (Other)

https://github.com/obsproject/obs-studio/pull/7010

### OBS Studio Log URL

https://obsproject.com/logs/A8qbyrYnsrNcdHuk

### Expected Behavior

If possible, remuxed HEVC recordings in OBS made with the hardware encoder should use hvc1 so as to be usable by system software directly after remuxing.

### Current Behavior

Currently, remuxed HEVC recordings in OBS must be retagged with e.g. ffmpeg as hvc1 before built-in software (QuickTime, Final Cut, etc.) can open them.

### Steps to Reproduce

Any remuxed recording made with the VT HEVC Hardware Encoder in OBS has this issue.

### Anything else we should know?

Filed at Pat's request over at https://github.com/obsproject/obs-studio/pull/7010 .

**Comment by derrod** [comment]
Making remuxing use `hvc1` by default should work (since at this time you're not supposed to record to MP4 directly anyway).

Right now the tag is just set to `0`: https://github.com/obsproject/obs-studio/blob/12d1f1c3358f7231244db0b971a333445e346f80/libobs/media-io/media-remux.c#L152

**Comment by gxalpha** [comment]
Fixed by bbb3dc00590a572cf49f97db3397221f0828f9ad
