### ISSUE TITLE
Update Fedora Linux build intructions for +28. 

### ISSUE THREAD

**Issue by 3laws** [obsproject/obs-studio#7324]
### Operating System Info

Other

### Other OS

Fedora 36

### OBS Studio Version

Git

### OBS Studio Log URL

None

### Expected Behavior

Qt6 dependencies, x86_64 specific commands for some packages that only install i686 unless otherwise indicated.

Also, is there a reason why we can't built non-portable with `make -j4` instead of `make -j$(nproc)` ? Both work just fine and show no difference in logs.

### Current Behavior

Build fails.

### Steps to Reproduce

1. Follow instructions on Fedora 36.

**Comment by kkartaltepe** [comment]
Feel free to update the wiki if it is out of date for your distro.
