### ISSUE TITLE
Bug Report: "PALookAheadBufferDepth" stalls/breaks the AMF encoder when used with PAHighMotionQualityBoostMode or PATemporalAQMode

### ISSUE THREAD

**Issue by cs9kc** [obsproject/obs-studio#7326]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.1

### OBS Studio Log URL

Logs are in the body of the ticket.

### Expected Behavior

I am submitting this ticket after experimenting with the AMD AMF encoder option "PALookAheadBufferDepth", which is part of the PreAnalysis Component.

Expected behaviour would be for the encoder to lose the first 50-100 frames (which is normal when the PreAnalysis Component is used), and for the encoder to produce a proper output, which it does with the following settings:

CBR, 7Mbit, 2s, Quality, High, 3 B-frames
> HighMotionQualityBoostEnable=false EnableVBAQ=false RateControlPreanalysisEnable=0 BReferenceEnable=true AdaptiveMiniGOP=false RateControlSkipFrameEnable=false EnablePreAnalysis=true PASceneChangeDetectionEnable=false PAHighMotionQualityBoostMode=0 PATemporalAQMode=0 PAFrameSadEnable=false PALookAheadBufferDepth=2

I tested "PALookAheadBufferDepth" up to a value of 20 and the encoder and output file operated/looked as expected.

### Current Behavior

If "PAHighMotionQualityBoostMode" is set to "1", the encoder chugs/partially stalls, and "stopping recording" shows up and takes about a minute to go away.  The output video is missing most of its content.

[PAHighMotionQualityBoostMode Log.txt](https://github.com/obsproject/obs-studio/files/9531593/PAHighMotionQualityBoostMode.Log.txt)

If "PATemporalAQMode" is set to "1", The encoder goes for about 10 seconds, and a prompt pops up with "An encoder error occurred while recording".  There is no encoder activity in task manager, and the output file has only the first I-frame, and nothing else.

[PATemporalAQMode log.txt](https://github.com/obsproject/obs-studio/files/9531594/PATemporalAQMode.log.txt)

### Steps to Reproduce

1. Use OBS Studio 28.0.1
2. Use AMD Driver 22.8.1
3. Set the following options in OBS Studio encoder settings: AMD HW H.264, CBR, 7Mbit, 2s, Quality, High, 3 B-frames
> HighMotionQualityBoostEnable=false EnableVBAQ=false RateControlPreanalysisEnable=0 BReferenceEnable=true AdaptiveMiniGOP=false RateControlSkipFrameEnable=false EnablePreAnalysis=true PASceneChangeDetectionEnable=false PAHighMotionQualityBoostMode=0 PATemporalAQMode=0 PAFrameSadEnable=false PALookAheadBufferDepth=2
4. Change either "PAHighMotionQualityBoostMode" or "PATemporalAQMode" to "1"
5. Start the encode
...

### Anything else we should know?

I'm reporting this after hearing back from RhutsAMD over on the AMD AMF github, regarding more information on the PreAnalysis Component feature "PALookAheadBufferDepth".  Ticket https://github.com/GPUOpen-LibrariesAndSDKs/AMF/issues/349  

The feature works when PA is enabled and only PALookAheadBufferDepth is set, but according to AMD, PALookAheadBufferDepth should work alongside and help improve the function of PAHighMotionQualityBoostMode and PATemporalAQMode.

This is not the case in the current version of OBS Studio.  If it is determined that the OBS Studio developers can't remedy the error, I will be happy to pass this ticket on to the AMD AMF github; just say the word.

Thanks!

**Comment by notr1ch** [comment]
OBS doesn't validate any advanced settings you enter to ensure they're functional or compatible. Not sure there's anything to do on our end. Custom encoder settings are strictly "you break it, you fix it" territory.

**Comment by cs9kc** [comment]
Please don't take this as me being rude, but I would at least appreciate it if Jim or another dev that has recently been involved in the new AMD AMF encoder implementation, would take a look at it first before I'm effectively told to "go to AMD, not our issue".

After spending the last 2.5 months passing data to Jim and testing out fixes for AMD's AMF encoder during the v28 Beta implementation, it is a bit jarring, and slightly insulting, to suddenly be told "not our problem anymore" , especially if you haven't even reviewed the issue at hand.

The way the AMD AMF encoder is implemented in OBS Studio v28, it gives access to _all_ of the encoder options.  I found an option combination that breaks.  All I'm asking for is an opinion on whether the appropriate devs think that this is an OBS Studio problem, or an AMF problem.  If the latter, I will whisk it away to the AMD AMF github so that they can look at it.

**Comment by cs9kc** [comment]
I was able to repro in VCEEnc, and this repros on both programs using RX 5700 XT and RX 6900 XT.

Closing here, and passing this issue on to the AMD AMF gitub.

**Comment by sandr1x** [comment]
Hi! I don't have a chance to test the parameters as I have an RX 570. I'm wondering if PALookAheadBufferDepth is now working or not. This setting is required for AQs such as PAPerceptualAQMode and PATemporalAQMode to work. This may indicate that AQ other than VBAQ does not work for AMF. Whether this is actually the case is not clear.
