### ISSUE TITLE
Nvidia Nvenc (New) does not show up for me with obs 28.0.1

### ISSUE THREAD

**Issue by athulfalkon** [obsproject/obs-studio#7328]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.1

### OBS Studio Log URL

https://obsproject.com/logs/losnU2fhpLphqLQF

### Expected Behavior

Nvidia Nvenc (New) does not show up for me with obs 28.0.1. However, it is present on 27.2.4 with no issues. 

### Current Behavior

Streamlabs OBS is able to show Nvidia Nvenc (New) but this option is not there on 28.0.1 even after a fresh instal of windows 10 with no other programs installed except the current Nvidia driver (516.94).

These are the options I see currently on 28.0.1 (screenshot) [https://imgur.com/a/CTfejhT](url)

### Steps to Reproduce

1. I installed each version (27.2.4, 28.0.0 and 28.0.1) individually and the Nvidia Nvenc (New) was not present in both of the 28 versions
2. I also tried saving my settings in 27.2.4 and then updated the program drictly though obs to 28.0. 1 and again the Nvidia Nvenc (New) encoder option has disappeared 
3. This option is not there on 28.0.1 even after a fresh instal of windows 10 with no other programs installed except the current Nvidia driver (516.94).
...

### Anything else we should know?

System Specs

R7 2700x
ROG Strix GTX1080Ti
16 Gb Ram @3200Mhz

**Comment by WizardCM** [comment]
It was renamed to "NVIDIA NVENC H.264"

**Comment by athulfalkon** [comment]
@WizardCM Thank you for the quick responce! :)
