### ISSUE TITLE
Changing python install path does not update the python version used

### ISSUE THREAD

**Issue by CodeYan01** [obsproject/obs-studio#7329]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.1

### OBS Studio Log URL

https://obsproject.com/logs/iAuo--Hhf93cbk6d

### Expected Behavior

Switching the python install path will change the python installation that obs uses.

### Current Behavior

If the path is empty, then you choose a path of the python install path, it does update, and added python scripts will then work. However, now that it has loaded a python interpreter, further changes to the python install path won't update it.

### Steps to Reproduce

1. Have a new portable obs installation, or change the python install path to a random non-Python folder then restart obs.
2. Download this simple python script.
[python_version.txt](https://github.com/obsproject/obs-studio/files/9535299/python_version.txt)
3. Change the file extension to .py
4. Add it to obs.
5. Check script log and see that it does not print anything, since there is no valid Python path yet.
6. Change the python install path to a valid one. (I used 3.8.5)
7. Reload the script. The script log should log the python version that obs uses.
8. Change the path to a different one. (I used 3.9.13)
9. Reload the script. The script log will say the same python version that you used first.
10. Restart obs. The script log will now say the correct python version.
...

**Comment by WizardCM** [comment]
Correct. An OBS restart is required, as Python is not designed to be dynamically unloaded. See #6970
