### ISSUE TITLE
Launching OBS crashes AMD GPU driver

### ISSUE THREAD

**Issue by HarGabt** [obsproject/obs-studio#7332]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.1

### OBS Studio Log URL

https://obsproject.com/logs/x2rrwzA8aJ2S7Cip

### Expected Behavior

No GPU driver crash

### Current Behavior

GPU driver crash

### Steps to Reproduce

1. Launch OBS
2. Select or switch to a scene with a display capture source(s)
3. Next thing you see is mouse lagging followed by screen freezing and going black

### Anything else we should know?

Using AMD RX 580 8GB, driver version 22.8.2
Also I had colour format set to `RGB`, colour space to `sRGB` and full colour range, does it have to do with driver crash? OBS itself did not crash

I can provide a bug report generated by AMD Adrenalin, maybe this can help.
[AMD Bug Reporting Form Submitted Data 20220909T215200.zip](https://github.com/obsproject/obs-studio/files/9537795/AMD.Bug.Reporting.Form.Submitted.Data.20220909T215200.zip)

**Comment by RytoEX** [comment]
You're running an AMD beta/optional driver. Please report this to AMD. Please rollback to a stable driver and retest this. If you can reproduce this in a stable driver, we can reopen this.

**Comment by HarGabt** [comment]
This issue was fixed with 22.10.2 driver update, which mentions `Driver timeout may occur using HEVC hardware encoding on Radeon™ RX 6000 series GPUs` as a fixed issue. Despite RX 6000 series alone being mentioned here, the fix also works for RX 500 series GPUs.

**Comment by jrigle** [comment]
I on  driver version 24.1.1 still have this issue with the RX 580

**Comment by OreCraftNetwork** [comment]
> En la versión 24.1.1 del controlador todavía tengo este problema con el RX 580

Tengo el mismo problema con la RX 580 8GB, hay veces (no siempre) que abre OBS Studio y el mouse se friza, seguido de una pantalla negra y luego vuelve. ¿No han encontrado solución @jrigle o @HarGabt?
![image](https://github.com/obsproject/obs-studio/assets/93739264/091c720d-c625-4fe4-8848-237ddcb675ac)

**Comment by HarGabt** [comment]
@OreCraftNetwork
I don't have the aforementioned GPU anymore, and therefore can't come up with a definite solution that might solve your problem.
I'd suggest you to resort to RdN.ID Community Driver (formerly Amernime Zone) and switch to a specific AMF version that doesn't have those issues.
Or open a new issue with referencing to this one, considering you're not using beta/optional version of the driver like I did back in the day of writing this issue.
