### ISSUE TITLE
Recordings/Streams stutter more

### ISSUE THREAD

**Issue by TheRealDadbeard** [obsproject/obs-studio#7334]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.1

### OBS Studio Log URL

will provide files below

### Expected Behavior

No stuttering

### Current Behavior

So I tested this with a completely clean OBS for both versions. I had some weird issues with stuttering coming up in 28 but could not really replicate it perfectly still can't but when you watch footage from both versions back to back you see that the output 28 provides stutters more.

Sometimes it will even hitch very bad.I never had this happen on 27. I really see it and have no idea why this is happening. Maybe some Windows 11 quirk but it's really happening. I watched the recordings at 60hz to be sure.

I will attach all the files that I have made.

Recordings:
https://filen.io/f/f7d8c68c-9b31-4932-9310-dec688cc002c#!rwRt1rJHWsbH7TNyc64pPFjUMzEMo2Ht

Logs:
[27.2.4.txt](https://github.com/obsproject/obs-studio/files/9539696/27.2.4.txt)
[28.0.1.txt](https://github.com/obsproject/obs-studio/files/9539697/28.0.1.txt)

### Steps to Reproduce

1.Record in OBS 28
2. Watch Recording
3. See it has some stutter
4. Do the same with OBS 27
5. See it doesn't stutter so much

### Anything else we should know?

This looks like it's only in my eyes but I can really see the small weird stutters in the recordings that only started to happen on 28.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by TheRealDadbeard** [comment]
You always say it's a support request for my reports and in the end there is a weird bug. How is it a support request when recordings are smoother on 27?
