### ISSUE TITLE
Windows - Middle Mouse Button doesn't scroll advanced audio sources

### ISSUE THREAD

**Issue by jasongoldsmith1** [obsproject/obs-studio#7337]
### Operating System Info

Windows 10

### Other OS

Build 19044

### OBS Studio Version

28.0.1

### OBS Studio Log URL

https://obsproject.com/logs/ExisxnOiImck9Imb

### Expected Behavior

Under advanced audio properties, when an 'Audio Monitoring' option is selected, in version 27.x and prior, you could use the middle mouse wheel of the mouse to scroll between 'Monitor Off', Monitor Only (mute output) and 'Monitor and Output'.

Now it needs to be clicked each time. In context for my stream I need to swap between monitor > monitor and output for every single source so I have to do that every time a new source is added. 

If there is a way to always default to monitor and output then that would work around this issue but there may still be others who would like the middle scroll functionality back

### Current Behavior

Advanced Audio Properties is selected. Middle mouse is hovering over a source and doesn't move the option from 'Monitor off' to any other setting (or if other settings are selected, doesn't swap back to Monitor Off)

### Steps to Reproduce

1. Click advanced audio properties
2. Highlight a source 'Audio Monitoring' selection
3. Attempt to use middle scroll wheel to scroll up/down between 'Monitor Off' and 'Monitor and Output'
...

**Comment by notr1ch** [comment]
This is an intentional behavior change - see https://github.com/obsproject/obs-studio/issues/7011 for further discussion.
