### ISSUE TITLE
AMD HW HEVC recording 30FPS even when set to 60

### ISSUE THREAD

**Issue by WubTheGame** [obsproject/obs-studio#7339]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.1

### OBS Studio Log URL

https://obsproject.com/tools/analyzer?log_url=https%3A%2F%2Fobsproject.com%2Flogs%2F9SNKZFLLRZhe2zve

### Expected Behavior

Recordings to output 60FPS regardless of encoder.

### Current Behavior

Recordings output 60FPS if AVC via AMD's encoder, 30FPS if HEVC via AMD's encoder. Haven't bothered to try CPU encoding. Even the stats at the bottom say 60FPS with either encoder.

### Steps to Reproduce

1. Literally just set recording encoder to AMD HW H.265. I've tried with several other settings alongside (Bitrate control options, file split on/off, different recording resolutions, different sources active and inactive) and none of that makes a difference.
2. Record a video.
3. Check video file framerate?
...

### Anything else we should know?

My friend does not have this issue: https://obsproject.com/logs/_iiiXxTdTuWzPizc
Edit with better log: https://obsproject.com/logs/l2jq4Fpcy_Q6E9Eq

I use some plugins, but I'm not really expecting any of them to be the cause. I haven't made any recent changes to my PC or OBS that I know should have any relation, but this started at least afternoon yesterday. Thanks in advance and sorry if this turns out not OBS' fault. Edit: Also, I get encode overload plenty while recording at 60FPS, I don't think that's much to worry about in my case. And it's not like my encode usage in task manager is 100% while that's happening (I've checked).

**Comment by gxalpha** [comment]
This issue appears to be a support request, for which we don't use GitHub Issues.
Please make sure to visit the support sections on our [Discord server](https://discord.gg/obsproject) or [Forums](https://obsproject.com/forum).

Thank you!
