### ISSUE TITLE
OBS crashing since updating to 28.0.1

### ISSUE THREAD

**Issue by RoryLetteney** [obsproject/obs-studio#7344]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.1

### OBS Studio Log URL

https://obsproject.com/logs/KRuni9eb8w-fZeDi

### OBS Studio Crash Log URL

https://obsproject.com/logs/Od0UbqC8ZYxTsq-v

### Expected Behavior

1. Open OBS
2. "Start Recording"
3. Record

### Current Behavior

1. Open OBS
2. "Start Recording"
3. Short program freeze followed by crash

### Steps to Reproduce

1. Open OBS
2. Click "Start Recording"
3. Watch it crash

### Anything else we should know?

This was working prior to updating to 28.0.1. I don't have any plugins.

**Comment by WizardCM** [comment]
So this crash in particular is happening specifically in the AMD encoder, specifically in HEVC mode.. within the AMD encoder itself? That's very strange.

First, try updating your graphics drivers.

**Comment by derrod** [comment]
I can't find the specific version of that driver, but based on this table it seems to be from 2019: https://gpuopen.com/version-table/ So updating would be the first step.

**Comment by RoryLetteney** [comment]
Updating the graphics card driver did the trick. Thank you WizardCM.
