### ISSUE TITLE
YouTube chat input box covers chat

### ISSUE THREAD

**Issue by icvidanova** [obsproject/obs-studio#7353]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.1

### OBS Studio Log URL

https://obsproject.com/logs/NUtDZZRXabkNJFT7

### Expected Behavior

The chat would display entirely, regardless of size

### Current Behavior

The message box covers chat if the chat height is small/minimum height
![image](https://user-images.githubusercontent.com/105178667/189552751-80e2fb8e-dab9-4349-96ba-6818d3875602.png)

### Steps to Reproduce

1. Connect to YouTube
2. Start a livestream
3. Send a message in chat
4. Make the chat dock small

### Anything else we should know?

A chat pop-out from the YouTube studio website fits in an even smaller window so I would assume my intended size should be achievable
![image](https://user-images.githubusercontent.com/105178667/189552899-b3cafbdc-f81a-4906-b72a-57731b3ab689.png)

**Comment by gxalpha** [comment]
Vertically, these are the smallest dock sizes I could create without something getting cut off (making it smaller than this would cut have something cut off as you described):

<p>
<img align="top" width="170" alt="Bildschirm­foto 2022-09-12 um 01 46 59" src="https://user-images.githubusercontent.com/59806498/189554566-35943d33-7a6d-411d-a3be-4d8b9b879a2c.png">
<img align="top" width="170" alt="Bildschirm­foto 2022-09-12 um 01 45 46" src="https://user-images.githubusercontent.com/59806498/189554562-a99bf3a5-0f3a-4ed7-aa4d-6d57afa710b8.png">
<img align="top" width="170" alt="Bildschirm­foto 2022-09-12 um 01 48 54" src="https://user-images.githubusercontent.com/59806498/189554738-854f1175-d119-4330-9c37-763b8e114f78.png">
<img align="top" width="170" alt="Bildschirm­foto 2022-09-12 um 01 50 11" src="https://user-images.githubusercontent.com/59806498/189554737-fb57cfda-0f3f-43c8-b087-cc22a69e231b.png">
</p>

This is both with and without the chat box, and with and without our custom CSS. It suggests that the browser itself still has the same minimum height, but our custom chat box makes the dock larger so a dock with the same size will get cut off. Perhaps we could make the minimum size smaller as part of the script that hides the original chat.
