### ISSUE TITLE
OBS not capturing Voice Chat in several games

### ISSUE THREAD

**Issue by lesjj** [obsproject/obs-studio#7357]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.1

### OBS Studio Log URL

https://obsproject.com/logs/_RfuoV3nlDD-JbN5

### Expected Behavior

I've seperated my audio through the built-in plugin Application Audio Capture. It captures the audio of games and other programs perfectly, but with games like Warzone, Valorant, CS:GO, Rainbow Six Siege it won't capture the voice chat. 

I've search for a solution, but didn't find any. Even tried this plugin: https://obsproject.com/forum/resources/win-capture-audio.1338/. But no succes either, same problem. 

### Current Behavior

Not capturing voice chat, only audio from the game itself. 

### Steps to Reproduce

1. Add Application Audio Capture with the game Warzone
2. Record/Stream gameplay and talk with friends in-game voice chat.
3. No voice chat has been streamed/recorded. 
...

**Comment by RytoEX** [comment]
This is because Warzone uses a separate process for its voice chat audio, so it is not captured by targeting the main Warzone process. This is by design, and not a bug.

**Comment by lesjj** [comment]
Hi Ryan,

I know that Warzone and other games are doing this. But why would you design this plugin to not capture it? It doesn’t make any sense.
And what otherwise is the solution to get it working?

Van: Ryan ***@***.***>
Verzonden: maandag 12 september 2022 13:31
Aan: ***@***.***>
CC: ***@***.***>; ***@***.***>
Onderwerp: Re: [obsproject/obs-studio] OBS not capturing Voice Chat in several games (Issue #7357)


This is because Warzone uses a separate process for its voice chat audio, so it is not captured by targeting the main Warzone process. This is by design, and not a bug.
