### ISSUE TITLE
Website states macos minimum requirement as 10.13 whereas it is now 10.15

### ISSUE THREAD

**Issue by michaelrommel** [obsproject/obs-studio#7361]
### Operating System Info

macOS 10.15

### OBS Studio Version

28.0.1

### OBS Studio Log URL

-

### OBS Studio Crash Log URL

-

### Expected Behavior

The website should be updated to state 10.15 as minimum version

### Current Behavior

![Screenshot 2022-09-12 at 19 30 16](https://user-images.githubusercontent.com/919935/189720495-e2cc5e69-a5bb-4f6a-a645-f601cb2cf3d5.png)

### Steps to Reproduce

Download the current version for macos and try to install on Mojave.

**Comment by Fenrirthviti** [comment]
Thanks for pointing this out, I've corrected the translation to show the proper version.
