### ISSUE TITLE
Won't Start Stream

### ISSUE THREAD

**Issue by OldKills** [obsproject/obs-studio#7366]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.1

### OBS Studio Log URL

https://obsproject.com/logs/FXOjRPhhU4GAyfVT

### Expected Behavior

I expected to be able to go live to Facebook

### Current Behavior

When I click "Start Streaming" and enter in the information then hit "Go Live" it takes me to a screen that says:

"Oops! Something went wrong...
We could not create a Live Video on the page."

All stream settings are correct
![Desktop Screenshot 2022 09 12 - 18 46 17 58](https://user-images.githubusercontent.com/113394845/189771661-a104df29-8ed9-4f7a-a16c-1c85a8884667.png)

### Steps to Reproduce

1.start streaming
2.go live
3.error
...

**Comment by notr1ch** [comment]
Please contact StreamElements for support with their plugin, this is not part of OBS Studio.
