### ISSUE TITLE
Filename conflicts with scripts

### ISSUE THREAD

**Issue by Penwy** [obsproject/obs-studio#7370]
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

28.0.1

### OBS Studio Log URL

https://obsproject.com/logs/OYnQS2zEoF6tEFUf

### Expected Behavior

- Scripts named `test.py` should work the same way as with any other name
- Two different scripts with the same filename (from different folders) should each use their own code and not conflict

### Current Behavior

- Any script named `test.py` doesn't do anything at all when added.
- Adding more than one different script with similar names makes any subsequent script execute the code of the first script, not their own.

### Steps to Reproduce

- "test" name issue :
1. Download [this](https://cdn.discordapp.com/attachments/767069216011452450/1019286110200934420/test.py) testing script.
2. Add it to OBS.
3. Verify that nothing gets printed to log.
4. Change the filename to something else and re-add it to OBS.
5. Verify that `Loaded` has been printed to the log

- same name issue :
6. Create a copy of that same script in another folder with the same name but different code (f.e. prints a different message)
7. load that script in OBS
8. Verify that it prints the message of the first loaded script, not the one it should itself.

### Anything else we should know?

Reproduced on Windows 10 & 11

**Comment by gxalpha** [comment]
Closing per above.
