### ISSUE TITLE
GPU CPU/Memory Leak w/ Nested Scene Source use

### ISSUE THREAD

**Issue by GrandAdmiralQuack** [obsproject/obs-studio#7377]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/JQUzNDPZCUPfjQsL

### Expected Behavior

I expected GPU Usage to be less then 4% when sitting idle.

### Current Behavior

Depending on how deep you go w/ nested scenes, the deeper you go w/ more nested scenes, the media file ends up taking up to 99% of GPU utilization depending on how many nested scenes are in the overall scene collection.

This is my current scene nesting:
*Contains Nested Scenes

/ ------ STREAM STARTING ------ \*
All - Screen Alerts*
	- This scene has 6 nested SFX/VFX Scenes*
                - This has 5 nested scenes*
                   - Each nested scene may have a VFX/SFX !command w/ SFX/VFX

I've noticed that when I have a generic scene, w/ multiple scenes w/ multiple nested scenes, as soon as I turn on a media source, the GPU will spike from 4% to over 35% at a very easy level, w/ more nested scenes it can go all the way up to 99% causing video files to studder.

### Steps to Reproduce

1. Create 20 Scenes A-(1-6) B-(1-6) C-(1-6) D-(1-6)
2. Create 20 nested scenes within these base scenes A(1-6)-(U-Z)  
3. Nest Scenes D into C into B into A
4. Nest Sub Scenes Z into D, Y into C, X into B, W into A
5. Nest these into some of the (Letter) 1-6 scenes so that you have multiple levels

What I do is do this:

*Each has nested scenes
/ ------ STREAM STARTING ------ \*
  - All - Screen Alerts*
    - All - Screen Alerts (SFX) Commands*
       - Individual SFX Scene
	- Media Sources
    - All - Screen Alerts (VFX) Commands*
	- Individual SFX Scene
	   - Media Sources
    - All - Screen Alerts (SFX) Events*
	- Individual SFX Scene
           - Media Sources
    - All - Screen Alerts (SFX) Shoutouts*
	- Individual SFX Scene

This is very basic but to get even more, just nest a couple levels more deep, and then in the deepest scene have a media file.

### Anything else we should know?

Please explain to me how this should work. I feel that the media file should only be loaded once, but with the way its acting, its as if the media file is loaded once PER nested scene. So as you nest and chain more scenes together it exponentially gets worst. 

I do have the checkbox checked to unload file when not in use, and I can do this with a single media file. I do notice this happens w/ other sources, i've witnessed some of this same behavior with audio MIC sources, but I also know it pretty bad with camera sources. 

In my head (not a programmer) the nested scenes should act as a visual reference of placement. My reason for doing this is because groups are broken and everyone talks about nesting scenes within scenes within scenes, but I think due to my video card I see this most prominently. You won't probably notice this behavior in RTX cards, but I just can't afford a higher end card so hoping this is not a "feature" and an actual bug. Thanks!

**Comment by kkartaltepe** [comment]
We discussed this in discord, but the reporter has a fairly low power card and is attempting to render something like 10k+ nested scenes. This is expected to perform poorly though for reference a typical "gaming" setup of a 1070gtx can maintain 60fps at 16k nested draws and still have 70% capacity left over as the gpu drivers (cpu work) become a bottleneck at this point.
