### ISSUE TITLE
Crash when clicking titlebar/video capture properties camera input

### ISSUE THREAD

**Issue by frankhuurman** [obsproject/obs-studio#7380]
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

28.0.1

### OBS Studio Log URL

https://obsproject.com/logs/xT7X8QudIALyQwdK

### Expected Behavior

That I can use the OBS Studio flatpack without crashing.
When I clicked the title bar of the OBS Studio window, it crashed my desktop environment(back to Ubuntu login screen). 
When I tried to open up the properties of the video capture input and clicked on the 2nd dropdown, it crashed my desktop environment.

It's persistent and can be reproduced.

### Current Behavior

After clicking on the titlebar, it crashed the desktop environment to the Ubuntu login screen.
After clicking on some of the different dropdowns of the video capture properties, it did the same.

### Steps to Reproduce

1. Open OBS Studio Flatpack
2. Click on the titlebar of the window a couple of times
3. Or: add a video capture, go to properties and try to switch around some settings
...

### Anything else we should know?

I'm on a 2 year old Lenovo laptop with 16GB RAM and an i5-1135G7.
OBS Studio worked fine without crashes before this new version.

**Comment by VladimirMrzv** [comment]
My system crashes too, but after start streaming.

https://obsproject.com/logs/z5sKa9lIBgLOTywU

**Comment by VladimirMrzv** [comment]
before works fine.

I got updates for 
cmake (3.22.1-1ubuntu1) to 3.22.1-1ubuntu1.22.04.1
cmake-data (3.22.1-1ubuntu1) to 3.22.1-1ubuntu1.22.04.1
gnome-control-center (1:41.7-0ubuntu0.22.04.4) to 1:41.7-0ubuntu0.22.04.5
gnome-control-center-data (1:41.7-0ubuntu0.22.04.4) to 1:41.7-0ubuntu0.22.04.5
gnome-control-center-faces (1:41.7-0ubuntu0.22.04.4) to 1:41.7-0ubuntu0.22.04.5
libpoppler-cpp0v5 (22.02.0-2) to 22.02.0-2ubuntu0.1
libpoppler-glib8 (22.02.0-2) to 22.02.0-2ubuntu0.1
libpoppler-glib8:i386 (22.02.0-2) to 22.02.0-2ubuntu0.1
libpoppler118 (22.02.0-2) to 22.02.0-2ubuntu0.1
libpoppler118:i386 (22.02.0-2) to 22.02.0-2ubuntu0.1
libqt5core5a (5.15.3+dfsg-2ubuntu0.1) to 5.15.3+dfsg-2ubuntu0.2
libqt5dbus5 (5.15.3+dfsg-2ubuntu0.1) to 5.15.3+dfsg-2ubuntu0.2
libqt5gui5 (5.15.3+dfsg-2ubuntu0.1) to 5.15.3+dfsg-2ubuntu0.2
libqt5network5 (5.15.3+dfsg-2ubuntu0.1) to 5.15.3+dfsg-2ubuntu0.2
libqt5opengl5 (5.15.3+dfsg-2ubuntu0.1) to 5.15.3+dfsg-2ubuntu0.2
libqt5printsupport5 (5.15.3+dfsg-2ubuntu0.1) to 5.15.3+dfsg-2ubuntu0.2
libqt5sql5 (5.15.3+dfsg-2ubuntu0.1) to 5.15.3+dfsg-2ubuntu0.2
libqt5sql5-sqlite (5.15.3+dfsg-2ubuntu0.1) to 5.15.3+dfsg-2ubuntu0.2
libqt5test5 (5.15.3+dfsg-2ubuntu0.1) to 5.15.3+dfsg-2ubuntu0.2
libqt5widgets5 (5.15.3+dfsg-2ubuntu0.1) to 5.15.3+dfsg-2ubuntu0.2
libqt5xml5 (5.15.3+dfsg-2ubuntu0.1) to 5.15.3+dfsg-2ubuntu0.2
poppler-utils (22.02.0-2) to 22.02.0-2ubuntu0.1
python3-distupgrade (1:22.04.13) to 1:22.04.14
gir1.2-gdkpixbuf-2.0 (2.42.8+dfsg-1) to 2.42.8+dfsg-1ubuntu0.1
gir1.2-javascriptcoregtk-4.0 (2.36.6-0ubuntu0.22.04.1) to 2.36.7-0ubuntu0.22.04.1
gir1.2-webkit2-4.0 (2.36.6-0ubuntu0.22.04.1) to 2.36.7-0ubuntu0.22.04.1
libgdk-pixbuf-2.0-0 (2.42.8+dfsg-1) to 2.42.8+dfsg-1ubuntu0.1
libgdk-pixbuf-2.0-0:i386 (2.42.8+dfsg-1) to 2.42.8+dfsg-1ubuntu0.1
libgdk-pixbuf2.0-bin (2.42.8+dfsg-1) to 2.42.8+dfsg-1ubuntu0.1
libgdk-pixbuf2.0-common (2.42.8+dfsg-1) to 2.42.8+dfsg-1ubuntu0.1
libwebkit2gtk-4.0-37 (2.36.6-0ubuntu0.22.04.1) to 2.36.7-0ubuntu0.22.04.1
libxatracker2 (22.3~git2209130600.e612f3~oibaf~j) to 22.3~git2209140600.eec1e7~oibaf~jqt5-gtk-platformtheme (5.15.3+dfsg-2ubuntu0.1) to 5.15.3+dfsg-2ubuntu0.2
qt5-xdgdesktopportal-platformtheme (5.15.3+dfsg-2ubuntu0.1) to 5.15.3+dfsg-2ubuntu0.2
torbrowser-launcher (0.3.3-6ubuntu1) to 0.3.3-6ubuntu1.22.04.1
ubuntu-release-upgrader-core (1:22.04.13) to 1:22.04.14
ubuntu-release-upgrader-gtk (1:22.04.13) to 1:22.04.14
xserver-xorg-video-amdgpu (22.0.0-1build1) to 22.0.0-1ubuntu0.1
zlib1g (1:1.2.11.dfsg-2ubuntu9) to 1:1.2.11.dfsg-2ubuntu9.1
zlib1g-dev (1:1.2.11.dfsg-2ubuntu9) to 1:1.2.11.dfsg-2ubuntu9.1
zlib1g:i386 (1:1.2.11.dfsg-2ubuntu9) to 1:1.2.11.dfsg-2ubuntu9.1

after update the packages my system get crashing to login screen or reboot when start streaming in obs

**Comment by VladimirMrzv** [comment]
also update mesa
today test old build and no crashes.
problem begin from update with commit
https://gitlab.freedesktop.org/mesa/mesa/-/commit/eec1e728c5cde99e8cd61a49791dfd96e383a902

and works fine with 
https://gitlab.freedesktop.org/mesa/mesa/-/commit/e612f32e1ad20789441057b0de131fa04466e55e

**Comment by mijorus** [comment]
same issue here

**Comment by kkartaltepe** [comment]
Closing as users report it is a mesa bug. The original post also refers to clicking properties which was also reported to be a gnome bug.
