### ISSUE TITLE
Immediate disconnect from Twitch without reconnect period

### ISSUE THREAD

**Issue by Meirania** [obsproject/obs-studio#7381]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.1

### OBS Studio Log URL

https://obsproject.com/logs/oz2dZ0qNxGM4TFQs

### Expected Behavior

Getting a 2 minute reconnect period to Twitch when there are network errors.

### Current Behavior

Ever since I updated to version 28, I keep getting immediate disconnects from twitch instead of the 2 minute wait they usually give you. My log shows errors RTMP 10060 and 10038 twice yesterday at 22:46 and then again two minutes after.
This has happened at least once per stream ever since the update. I've tried changing the output server to other locations, same results. 
I tried downgrading back to version 27.2.4 and had no issues whatsoever.
This does not seem to be exclusively internet related: I've attempted disconnecting my cable during a stream and got the 2 minute wait as intended. 

### Steps to Reproduce

I can't seem to reproduce it, as whenever I disconnect from the internet manually the reconnect period works as intended.
However, this has consistently happened at least once per stream since I updated to version 28. The order of events is:
1. Stream working as intended
2. Got a disconnect event
3. Stream closes immediately
4. OBS reconnects automatically, but now in a new stream

**Comment by Meirania** [comment]
Seems to have been caused by SE.live, I have uninstalled it and will close the issue if I have no more problems till the end of the week

**Comment by Fenrirthviti** [comment]
Closing per above.
