### ISSUE TITLE
OBS not sending out mic audio despite mic working fine in other programs and audio mixer picks up mic

### ISSUE THREAD

**Issue by crazyidoit** [obsproject/obs-studio#7387]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.1

### OBS Studio Log URL

n/a

### Expected Behavior

I expect audio from mic to be sent out on stream or recording when using obs and I can see the audio mixer working as normal

### Current Behavior

OBS is not sending out the Mic Audio from my microphone even though audio mixer shows life and microphone works fine on other programs, discord calls, teams etc.

### Steps to Reproduce

1. turn on obs
2.
3.
...

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by crazyidoit** [comment]
Good morning,

Are you kidding me ive been successfully using your software for 4 years.

This fault only gets fixed after reinstalling obs completely and then it works fine till pc gets turned off thats not support that is a bug with your new software!

Kind regards

Daniel Fell

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
