### ISSUE TITLE
BUG MANAGE BROADCAST

### ISSUE THREAD

**Issue by flamesidgs** [obsproject/obs-studio#7394]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.1

### OBS Studio Log URL

https://obsproject.com/logs/g_K1iiCQmW4L7g6j

### Expected Behavior

Can apply when finished

### Current Behavior

I Can't apply because the apply button is closed by the task bar, if i change the width of the broadcast menu, i have a bug that the broadcast menu will disappear under the taskbar

![image](https://user-images.githubusercontent.com/87573334/190887996-a578fcf7-0138-4dab-a331-fd4c10ae033d.png)

### Steps to Reproduce

1. just press the Manage Broadcast button
![image](https://user-images.githubusercontent.com/87573334/190888104-0b969c62-e91d-4ddb-838d-5b9e57ac293f.png)

### Anything else we should know?

I don't know this is a bug or not, for sure this can trouble us

**Comment by kkartaltepe** [comment]
Already fixed in #7267
