### ISSUE TITLE
UI inconsistencies on v28

### ISSUE THREAD

**Issue by alexitx** [obsproject/obs-studio#7400]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.1

### OBS Studio Log URL

https://obsproject.com/logs/N9uBpKQlgm6DTtKh

### Expected Behavior

The font size should stay consistent across rows and columns in the same dock and wide or overflowing text inside buttons shouldn't get cut off early leaving a lot of empty space around.

### Current Behavior

The Status field in the Stats dock has significantly larger font size than the rest of the columns and UI.
Yami (default):
![Stats Yami](https://user-images.githubusercontent.com/26458119/190918588-2950a250-59ef-45c5-bb5e-235372d2844d.png)
Dark:
![Stats Dark](https://user-images.githubusercontent.com/26458119/190918593-7e00af71-0d51-432e-9125-ae1ad3841ac8.png)
v27 also appears to have slightly larger font on the status field, but on v28 this seems to be amplified probably due to the new themes having larger font size and a new font.

Buttons containing a lot of text or wide characters have the contents cut off early at the sides.
Yami (default):
![Controls Yami](https://user-images.githubusercontent.com/26458119/190918630-42bc4f4e-3903-4af5-b05f-e72f82e7bf8a.png)
Dark:
![Controls Dark](https://user-images.githubusercontent.com/26458119/190918634-a48eee4f-752a-4020-970a-751a6b92e178.png)

The system scaling is at the default 100%.

### Steps to Reproduce

N/A

**Comment by charbelnicolas** [comment]
I updated from 27 to 28 on arch linux today. It seems developers these days just "fix" what is not broken. V28 is glitchy as hell. Time to move on.

**Comment by alexitx** [comment]
> I updated from 27 to 28 on arch linux today. It seems developers these days just "fix" what is not broken. V28 is glitchy as hell. Time to move on.

v28 has been running fine for me on Windows 10 and Manjaro, but the new themes and the old updated ones are getting increasingly more cluttered while wasting space on my 1080p monitor. Friends of mine who run both smaller and larger monitors also have hard time navigating and positioning many widgets which wasn't an issue before.

The Dark theme works okayish for me for now, but I'll probably end up spending some time to make a clean and improved theme from scratch.

Regardless, it would be nice if the inconsistencies are fixed and the default themes don't force minimum size or large whitespace on many of the widgets, because if the UI creates issues on a 1080p display, it might be unusable on old smaller monitors.

**Comment by Fenrirthviti** [comment]
Please keep comments on-topic and constructive.

We are aware there are a few instances with the new theme that need addressing, but they are overall very minor and, in our opinion, don't really impact the actual usability of the application. If there are other specific cases that need to be addressed where there is a clear bug or theme issue (such as those reported in the original post here, one of which there is an open PR to fix!), please do continue to report those so we can fix them.

As with any change, there will always be those who don't like it. In our experience so far, there has been an overwhelmingly positive response to the new theme in OBS, so it's unlikely it will be reverted or going away. If someone doesn't like it, the old default Dark theme is still available.

**Comment by Fenrirthviti** [comment]
Fixed by https://github.com/obsproject/obs-studio/pull/7613
