### ISSUE TITLE
Window Capture(Xcomposite) resets its target every time OBS launches

### ISSUE THREAD

**Issue by Ryu945** [obsproject/obs-studio#7404]
### Operating System Info

Other

### Other OS

Fedora 36 XFCE

### OBS Studio Version

28.0.1

### OBS Studio Version (Other)

28.0.1 64bit

### OBS Studio Log URL

https://obsproject.com/logs/bVsiDlwzGq8M0Eoh

### Expected Behavior

When I use Window Capture.   If I do not have the application open then it should be black.   If I do have the application open then it should show the application.   This is how it worked in the previous flatpak version of OBS.

### Current Behavior

Every time I launch OBS, it changes the window capture target in my scene to whatever options is at the to for new window captures.   It remembers the cropping but not the target application.  It did not use to do this.   I have to set the correct target every time I launch the application.

### Steps to Reproduce

1.  Launch OBS
2.  See that  a scene with Window capture is on the wrong target
3.  Launch the application
4.   See that  a scene with window capture is still on the wrong target.

### Anything else we should know?

Most of the time it defaults to my desktop.   Sometimes it defaults to Discord if I have Discord open.

**Comment by kkartaltepe** [comment]
I cannot replicate this. Please provide more information on what you are capturing. For example chrome/mpv/urxvt all behave as you expect for me.

Because you say your desktop is captured it sounds like your compositor might not label windows with classes correctly and we may behave differently but please try another compositor like gnome/kde.

**Comment by Ryu945** [comment]
> I cannot replicate this. Please provide more information on what you are capturing. For example chrome/mpv/urxvt all behave as you expect for me.
> 
> Because you say your desktop is captured it sounds like your compositor might not label windows with classes correctly and we may behave differently but please try another compositor like gnome/kde.

I am using Virt Manager with QEMU.   I am having it capture the window you open to display a virtual OS.

On the list of options for Window Capture (Xcomposite), I see every program window as an option, the desktop as an option and I even see my XFCE bars as an option.   I never had any problems previously because once I would set it, then it would remember it.  It doesn't remember it anymore.

**Comment by LGCW** [comment]
I can replicate this with XFCE 4.16 / Nvidia on Debian testing and stable. This started happening with #6474. 

My workaround has been to have everything open before launching OBS.

**Comment by regulargvy13** [comment]
I have the same problem on Arch linux with KDE

**Comment by arrowgent** [comment]
obs 29.1.3
ubuntu 18.04
NVIDIA-SMI 525.125.06   Driver Version: 525.125.06

this issue still occurs.

1: set Window Capture (xcomposite) for a game
2: close obs
3: close game
4: open obs
5: open game
6: window capture is not capturing the window set before.


if you are somehow telling me from obs 26.0.3 i was using before, this worked flawlessly
and a "work around" is to have the game open before starting OBS
this is a regression, issue....

**Comment by kkartaltepe** [comment]
If you think there was a regression please file a new bug with logs from both versions. It is typically unhelpful to comment on closed bugs.
