### ISSUE TITLE
OBS crashed the entire GNOME shell when clicking outside a dropdown menu

### ISSUE THREAD

**Issue by QuanMCPC** [obsproject/obs-studio#7414]
### Operating System Info

Other

### Other OS

Fedora 36

### OBS Studio Version

28.0.1

### OBS Studio Log URL

https://obsproject.com/logs/t8t4U0ag4-nk2dfb

### OBS Studio Crash Log URL

https://obsproject.com/logs/57APuf6j1xz5E9EY

### Expected Behavior

When the user clicked outside a dropdown menu, it should just close the dropdown.

### Current Behavior

The entire GNOME shell crashed

### Steps to Reproduce

1. Create a new source (any source) and click on "Properties"
![Screenshot from 2022-09-20 12-31-32](https://user-images.githubusercontent.com/60545346/191175112-5cad3cd5-d450-49a0-9093-62cda9d775aa.png)
2. Find a dropdown menu an click on it to make the dropdown show
![Screenshot from 2022-09-20 12-31-38](https://user-images.githubusercontent.com/60545346/191175122-2a0108f8-548b-4c1f-8123-1798651d3d5b.png)
3. Click outside the dropdown

**Comment by tytan652** [comment]
Reproduce-able with the Flatpak on ArchLinux.

**Comment by kkartaltepe** [comment]
Please report this to gnome shell.

**Comment by btaroli** [comment]
Trying OBS and instantly ran into this bug. Very reproducible.

**Comment by tytan652** [comment]
GNOME OS Nightly (GNOME 43) does not have this issue. I'm waiting for Arch Linux package to re-check.

**Comment by tytan652** [comment]
Mutter bug report: https://gitlab.gnome.org/GNOME/mutter/-/issues/2439

**Comment by tytan652** [comment]
The merge request for GNOME 42 is merged, so the issue will also be fixed in the upcoming GNOME 42 fix update.
