### ISSUE TITLE
OBS Studio 28+: NVENC is not detected and not working as intended.

### ISSUE THREAD

**Issue by dreaddr** [obsproject/obs-studio#7425]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.1

### OBS Studio Log URL

https://obsproject.com/logs/s2BCRp7Nv06yKtcl

### Expected Behavior

For NVENC to continue working like in OBS version 27.2.4

### Current Behavior

Crashes and reports that NVIDIA driver is not available, even though the latest version that is only a year old is already installed and functional. https://file.io/ohr7k31A5dVd (NVIDIA control panel log file)

### Steps to Reproduce

Start recording/streaming and it will pop up.

### Anything else we should know?

Downgraded to OBS 27.2.4, and it works as expected on that version of OBS. This could be affecting more users who just updated due to the "New update available" notice.

**Comment by derrod** [comment]
The minimum driver version for NVENC in OBS 28.0 is 471.41. Kepler mobile has not received feature driver updates for three years now, and is no longer supported.
