### ISSUE TITLE
Windows8.1 w64 crash QT "no Qt platform plugin could be initialized"

### ISSUE THREAD

**Issue by zaher** [obsproject/obs-studio#7426]
### Operating System Info

Other

### Other OS

Windows 8.1

### OBS Studio Version

28.0.1

### OBS Studio Log URL

NA

### Expected Behavior

Run application

### Current Behavior

When trying run (nothing show yet) crash with this error

This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: windows.

### Steps to Reproduce

1.
2.
3.
...

**Comment by gxalpha** [comment]
OBS 28 does not support Windows 8.1.
Please use OBS 27.2.4 or update to Windows 10.
