### ISSUE TITLE
Can't able to resize Broadcast setup window 

### ISSUE THREAD

**Issue by xeron56** [obsproject/obs-studio#7429]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.1

### OBS Studio Log URL

https://obsproject.com/logs/-1P3BCOPOTseZNL3

### Expected Behavior

Broadcast setup window should be resized 

### Current Behavior

![sd](https://user-images.githubusercontent.com/11449967/191665785-b0f9a595-09fd-4d35-9d7a-46459673cc8c.gif)

### Steps to Reproduce

1.open obs
2. click Manage broadcast button
3. then try to resize. mine current screen size is 1366x768
...

**Comment by tytan652** [comment]
Fixed by #7267
