### ISSUE TITLE
Interact tab minimises while obs is minimised

### ISSUE THREAD

**Issue by HunarPG** [obsproject/obs-studio#7435]
### Operating System Info

Other

### Other OS

Kde Neon 5.25

### OBS Studio Version

28.0.1

### OBS Studio Log URL

https://obsproject.com/logs/G-JakmDXxcH8Fifb

### Expected Behavior

I was expecting minimising obs would not have minimised any other windows opened in it 

### Current Behavior

Usually a windows of obs like setting does not minimise if you minimise main obs windows but it's not the case with the windows which opens after opening interact tab

### Steps to Reproduce

1.Open OBS
2.Click interact on an interactable windows(mainly a plugin or a browser source)
3.minimise main obs windows without closing interact tab
...

### Anything else we should know?

I should also provide more info about it
I am using an OBS Plugin for Live Split which is not available for Linux and a creator has made a plugin for linux users
I don't have a dual monitor setup so I can't open obs while speedrunning and I just minimise it
Now there is no possible way to see this window on my screen while speedrunning other than opening an interact windows and looking at it
Here is the link for the plugin 
https://github.com/CryZe/obs-livesplit-one

**Comment by WizardCM** [comment]
I believe currently this is by design. Theoretically it shouldn't be too complex to change this, but may have unintende side effects.

**Comment by HunarPG** [comment]
So if get's easily implemented without side effect it would be available in the next release right??

**Comment by HunarPG** [comment]
I will be closing this issue for now
As I will Dual-Boot with Windows for now
If it ever get in a release feel free to open it
