### ISSUE TITLE
Red Streaming Icon still shows, after streaming is stopped

### ISSUE THREAD

**Issue by JacobWKlein** [obsproject/obs-studio#7439]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.1

### OBS Studio Version (Other)

Actually using 28.0.2, but issue persists

### OBS Studio Log URL

https://obsproject.com/logs/2bFmhxiUxKO-L9P1

### Expected Behavior

Right-click the System Tray icon, and choosing "Stop Streaming", and both the System Tray icon and Taskbar icon should no-longer show the red streaming dot on the icon.

### Current Behavior

Sometimes, both the System Tray icon and Taskbar icon will show the red streaming dot on the icon, even though streaming has been stopped.

### Steps to Reproduce

1. Start Streaming
2. Right-click the System Tray icon
3. Choose "Stop Streaming"
4. BUG: Sometimes the icons in System Tray and Taskbar will both still show the red streaming icon, even though streaming has stopped.

**Comment by PatTheMav** [comment]
Does the icon return to its normal state when you move the mouse over it?

**Comment by JacobWKlein** [comment]
It happened once, and I don't remember with certainty, if hovering it changed anything. I think the answer is no that it didn't. I'm hopeful that somebody can inspect the code to figure out what happened.

**Comment by Fenrirthviti** [comment]
Keep in mind that the red dot shows for any outputs, not just streaming. You had the virtual camera output active:

```07:49:58.279: ==== Virtual Camera Start ==========================================```

Which would leave the red dot when you stop streaming. Looks like nothing to inspect or fix here, just a misunderstanding on how the dot shows.

**Comment by JacobWKlein** [comment]
Thank you. I guess I didn't realize that was on. I must have accidentally clicked it, I suspect. I truly appreciate you helping me. Thanks again.
