### ISSUE TITLE
RPM update error

### ISSUE THREAD

**Issue by tjapro** [obsproject/obs-studio#7440]
### Operating System Info

Other

### Other OS

Fedora 36

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.2.4

### OBS Studio Log URL

N/A

### OBS Studio Crash Log URL

N/A

### Expected Behavior

Update resumes correctly.

### Current Behavior

No update done.

### Steps to Reproduce

1. Run `sudo dnf update -y`
2. See the errors.

### Anything else we should know?

I have this setting activated in my system: `update-crypto-policies --set TEST-FEDORA39`.  
See https://fedoraproject.org/wiki/Changes/StrongCryptoSettings3Forewarning2

This is the errors:
```
A executar verificação de transação
erro: rpmdbNextIterator: skipping h#    2483 
Header V3 RSA/SHA1 Signature, key ID d651ff2e: BAD
Header SHA256 digest: OK
Header SHA1 digest: OK
erro: rpmdbNextIterator: skipping h#     816 
Header V3 RSA/SHA1 Signature, key ID d651ff2e: BAD
Header SHA256 digest: OK
Header SHA1 digest: OK
erro: rpmdbNextIterator: skipping h#     437 
Header V3 RSA/SHA1 Signature, key ID d651ff2e: BAD
Header SHA256 digest: OK
Header SHA1 digest: OK
Erro: verificação da transação vs depsolve:
x264 is needed by obs-studio-28.0.1-4.fc36.x86_64
libftl.so.0()(64bit) is needed by obs-studio-libs-28.0.1-4.fc36.x86_64
libx264.so.163()(64bit) is needed by obs-studio-libs-28.0.1-4.fc36.x86_64
Para diagnosticar o problema, tente executar: 'rpm -Va --nofiles --nodigest'.
Provavelmente corrompeu a BD RPM, executar 'rpm --rebuilddb' poderá resolver o problema.
Os pacotes descarregados foram guardados em cache até à próxima transação com sucesso.
Pode remover os pacotes em cache executando 'dnf clean packages'.
```

doing `sudo rpm -rebuilddb` do not resolve this issue.

**Comment by tytan652** [comment]
OBS Project only provides officially Ubuntu PPA and Flatpak packages.

If you have an issue with an unofficial package, report the issue to the package maintainer(s).
