### ISSUE TITLE
Use hardware decoding when available on M1 Max results to black screen

### ISSUE THREAD

**Issue by Teressss** [obsproject/obs-studio#7449]
### Operating System Info

macOS 12

### OBS Studio Version

28.0.2

### OBS Studio Log URL

https://obsproject.com/logs/0Kh8NpvPItN18uVJ

### Expected Behavior

Apple Silicon M1 Max has built-in encoders/decoders on chip, so obviously the would be if OBS would use it to accelerate sources. 

### Current Behavior

But when I enable "Use hardware decoding when available" on Apple Silicon M1 Max 16" MacBook Pro it shows only black screen. To be able to see my media sources I have to disable hardware decoding so it's running only on CPU the hard way.

### Steps to Reproduce

1. add to scene media source
2. choose .mov H264 file
3. enable "Use hardware decoding when available"
4. result is black screen
...

**Comment by PatTheMav** [comment]
What is the width and height of the video you are trying to add as a media source?

**Comment by Teressss** [comment]
> What is the width and height of the video you are trying to add as a media source?

exact 4K = 3840x2160/60fps

**Comment by PatTheMav** [comment]
Got it, just tried a 4k test video and got this in the log:

`[h264 @ 0x157a39930] hardware accelerator failed to decode picture`

So something's definitely broken there, especially as I distinctly remember using 4k hardware accelerated videos on my M1 Max before..

**Comment by PatTheMav** [comment]
After some more testing it seems that hardware acceleration via VideoToolbox works in FFmpeg 5.1.1, but _not_ in the 5.0.1 version we ship with OBS.

It seems the issue was fixed upstream by commit https://github.com/FFmpeg/FFmpeg/commit/c534d9f72a89542ed639071b1ae15893aadf1f18.

This means that H.264 hardware-accelerated decoding is broken for now (HEVC, VP9 and ProRes should be unaffected) and will require an FFmpeg-update on our end to fix this.

**Comment by jeremy-murphy** [comment]
I'm seeing this problem right now with 30.0.2 and an Apple ProRes HQ clip on a MacBook Pro 2021, which has an M1 Pro. :\

**Comment by RytoEX** [comment]
> I'm seeing this problem right now with 30.0.2 and an Apple ProRes HQ clip on a MacBook Pro 2021, which has an M1 Pro. :\

I don't think the M1 chips have ProRes hardware decoding. That was a feature new to the M2 generation. That sounds like a different problem from the original issue here, which was about hardware acceleration being broken in FFmpeg.

**Comment by PatTheMav** [comment]
> > I'm seeing this problem right now with 30.0.2 and an Apple ProRes HQ clip on a MacBook Pro 2021, which has an M1 Pro. :\
> 
> I don't think the M1 chips have ProRes hardware decoding. That was a feature new to the M2 generation. That sounds like a different problem from the original issue here, which was about hardware acceleration being broken in FFmpeg.

To be more precise, it was not available in the non-Pro/Max/Ultra variant of M1.

**Comment by RytoEX** [comment]
> > > I'm seeing this problem right now with 30.0.2 and an Apple ProRes HQ clip on a MacBook Pro 2021, which has an M1 Pro. :\
> > 
> > 
> > I don't think the M1 chips have ProRes hardware decoding. That was a feature new to the M2 generation. That sounds like a different problem from the original issue here, which was about hardware acceleration being broken in FFmpeg.
> 
> To be more precise, it was not available in the non-Pro/Max/Ultra variant of M1.

Ah, I see there is a distinction there. Yes, the M1 Pro should have ProRes hardware decode. I don't have any appropriate M1 hardware to double check this.

**Comment by jeremy-murphy** [comment]
I know you merged something to fit it but do you want to confirm with @Teressss that it worked? If it did, then makes sense for me to open a new ticket for the M1 Pro, but if the problem remains then maybe it's the same one.
