### ISSUE TITLE
encoding error amd

### ISSUE THREAD

**Issue by flover2102** [obsproject/obs-studio#7457]
### Operating System Info

Windows 10

### Other OS

windows

### OBS Studio Version

28.0.2

### OBS Studio Log URL

https://obsproject.com/logs/6KH1HiwkZFTLtfyd

### Expected Behavior

i have try a stream

### Current Behavior

i got error aboute encoder

### Steps to Reproduce

1.start obs
2.click on "start streaming"
3.
...

### Anything else we should know?

i have the last driver update on adrenaline  , i use "AMD HW H.264" and my obsis preset on "power  saving"

i got this porbleme after updating obs to V28  befor that i was in V26 i think and it works fine

**Comment by energizerfellow** [comment]
Manually assigning a GPU will typically break OBS. You need to remove any custom GPU assignments you may have made for `obs64.exe`, then restart Windows. You will then want to run OBS's autoconfig wizard from the Tools menu and apply the recommended settings at the end.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
