### ISSUE TITLE
Output video quality broken when using VAAPI encoding

### ISSUE THREAD

**Issue by pierreavizou** [obsproject/obs-studio#7463]
### Operating System Info

Other

### Other OS

Manjaro

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.2.4

### OBS Studio Log URL

https://obsproject.com/logs/wwHdcFIZDcf3dBDZ

### Expected Behavior

Streaming et recording video quality should be acceptable when using VAAPI encoding

### Current Behavior

When choosing FFMPEG VAAPI to encode video (streaming and recording), the resulting video has very degraded quality: extremely pixelated, also sometimes with RGB screen flashes. Below is an example video output. The result is the same when broadcasting to a livestream platform. 

https://user-images.githubusercontent.com/7101583/192145069-1a7c9227-5b30-4223-869e-a0d9bbc11129.mp4

Here are my current settings for video recording: 
![image](https://user-images.githubusercontent.com/7101583/192145172-5c494dd5-f892-4a6b-8e52-a64bd5cf367f.png)

I've tried multiple combinations and nothing seems to work. Only increasing bitrate to ridiculous values like 20000kbps improve the output quality. 

### Steps to Reproduce

1.Install OBS on Linux
2. Open output settings
3. Choose Advanced output mode
4. Choose FFMPEG VAAPI as a video encoder
5. Start recording something for a few seconds
6. Open video output file, you should see degraded quality
...

### Anything else we should know?

I have the same issue on both AMD and Nvidia GPUs, and regardless of OBS installation method (native package, flatpak). I have the latest drivers for both GPUs. 

At some point in the logs, a possibly relevant message shows up: `[h264_vaapi @ 0x55bf8def1740] Driver does not support some wanted packed headers (wanted 0xd, found 0).`

I also tried OBS 28 and the same thing happened.

**Comment by kkartaltepe** [comment]
this is about what i would expect for these settings.

RGB flashing is a bug in mesa, i think it will be fixed in the latest 22.2 release or something. try reporting that issue to them.

**Comment by pierreavizou** [comment]
Ok I will. 
Appart from flashing, is there a way to have good video quality when using hardware encoding? Because the video is still very pixelated anyway.
