### ISSUE TITLE
It is impossible to capture sound from the OBS

### ISSUE THREAD

**Issue by BazZziliuS** [obsproject/obs-studio#7468]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.2

### OBS Studio Log URL

https://obsproject.com/logs/gk0TbI9RHHyLN2i2

### Expected Behavior

You can capture the sound from the OBS and alerts from the "Browser" will be heard

### Current Behavior

Due to the fact that it is impossible to select a sound from the OBS, the sound alerts of donations or subscriptions are not heard on the stream

### Steps to Reproduce

1. Select the audio capture of the application
2. Will be upset that there is no OBS
![image](https://user-images.githubusercontent.com/18011884/192256035-22775b91-acc0-46f3-930f-db723f25f335.png)

### Anything else we should know?

I love you and look forward to a speedy update

**Comment by WizardCM** [comment]
This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels below, and if it's determined that this is indeed a bug, then we will re-open this issue.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

**Comment by RealIndrit** [comment]
I usually have alerts as a browser source, with "control audio through obs" checked in the source properties, then you go to advanced settings and set the audio output to "Monitor And Output" then both you and the stream can hear the alert
