### ISSUE TITLE
OBS crashing on startup - possible issue with Multipass and Qt5?

### ISSUE THREAD

**Issue by debemdeboas** [obsproject/obs-studio#7469]
### Operating System Info

Windows 11

### OBS Studio Version

Other

### OBS Studio Version (Other)

28.0.1

### OBS Studio Log URL

I can't open OBS to upload a log file

### OBS Studio Crash Log URL

I can't open OBS to upload a crash log file

### Expected Behavior

I'd expect OBS to open.

### Current Behavior

It doesn't open, it crashes on startup and flashes an error message.

### Steps to Reproduce

1. Try to open
2. Fail

### Anything else we should know?

When I took a look at the crash log files, I noticed something interesting: OBS was trying to load Multipass's Qt5Core DLL, which I found extremely odd.
I only recently installed Multipass on this computer, but I didn't think much of it.
Is it possible that OBS is looking on the $PATH for Qt DLLs? Not sure.

GitHub didn't let me paste my log file here so I pasted it on [PasteBin](https://pastebin.com/V6zBCRpH).

**Comment by tehbasshunter** [comment]
This is an issue with an "older" version SE.Live and OBS. Rerun the SE.Live installer from the website as is without any changes.

**Comment by debemdeboas** [comment]
@tehbasshunter it worked! Thank you - and sorry for wasting your time.
