### ISSUE TITLE
Crashing after ~30 minutes of recording.

### ISSUE THREAD

**Issue by wikwity** [obsproject/obs-studio#7471]
### Operating System Info

Other

### Other OS

MacOS 13 beta 8

### OBS Studio Version

28.0.2

### OBS Studio Log URL

https://obsproject.com/logs/-sMhcc9E-HLCoLWZ

### Expected Behavior

Recording without interruptions.

### Current Behavior

Every 30 minutes my OBS crashes (I have encountered this behavior four times in a row). I click reopen and start record again. Files are OK, but still on 28.0.1 I've recorded over 10 hours without any problems, 28.0.2 doesn't allow me this.

### Steps to Reproduce

 just use obs for recording as you always did. I was using VT H264 Hardware Encoder with M1 Pro. CBR, 1000 KB/s, 3024x1964 and 16 FPS. Enhanced audio latency is off. Not sure what may cause this behavior other than software regression.

**Comment by gxalpha** [comment]
Please provide a crash log. Instructions can be found here:
> 1. In Finder, click the Go menu
> 2. Select Go To Folder, and type in `~/Library/Logs/DiagnosticReports/`
> 3. Upload the file prefixed `OBS_` with the most recent date (format is year-month-day)

Please also reconfirm that it still works fine on 28.0.1 on macOS Beta 8 specifically, but not 28.0.2. There are known regressions on the macOS side, so it'd be important to have those ruled out.

**Comment by wikwity** [comment]
MacOS Ventura Beta 8 bug. Hasn't spotted any weird behaviour on beta 9. Thanks for this beautiful software! :)
