### ISSUE TITLE
OBS 28.0.2 Crashes when using "Custom Output (FFMPEG)" with "libaom-av1" video encoder

### ISSUE THREAD

**Issue by JCBuck** [obsproject/obs-studio#7472]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.2

### OBS Studio Log URL

When OBS Crashes it doesn't produce a log file
Edit: Most recent log with encoder parameters listed below
https://obsproject.com/logs/63gdP33KEVaZGjtk

### OBS Studio Crash Log URL
Edit: Most recent crash log, then older log running on 5850u
https://obsproject.com/logs/ihyRKqChk1G9spn1#logURL
https://obsproject.com/logs/tZ40BOwfJQvchJJ_#logURL

_No response_

### Expected Behavior

Not crash after starting recording, and actual video being recorded into file rather than 262 bytes

### Current Behavior

No matter what is in the "Video Encoder Settings" field , including nothing, it will crash after starting and stopping the recording after a few seconds (and will record only a 262 byte mp4 file (using this container)

### Steps to Reproduce

Settings > output > output mode `Advanced`
Type `Custom Output (FFMPEG)`
Video Encoder `libaom-av1`
Recording format `mp4`
Start recording
wait a few seconds
stop recording
crash

### Anything else we should know?

Doesn't crash if using Type `standard`
Custom Output works with `libsvtav1 (libaom-av1)`

**Comment by RytoEX** [comment]
OBS always starts producing a log file as soon as you open it. Regular log files and crash log files are different. If OBS does not produce a popup warning that "Woops, OBS has crashed!" then there is no crash log, but there is still a regular log.

Please provide the regular log file from a session where this occurred.

**Comment by flaeri** [comment]
There is no timeout protections in custom ffmpeg output, and libaom-av1 is incredibly slow (hard to run) by default. If a large amount of lag happens, it does indeed crash.

You need to take extreme caution to monitor the lag. It works fine for me as long as I speed it up substantially using certain parameters, so that no lag happens.

**Comment by JCBuck** [comment]
> 

Ah okay I do see the regular log files, and after running enough times it seems to have produced a crash log as well. I'll edit the original post with them

I've set the fps to 10, 5, and 1. Though the reported encoding time in stats is usually around 1-2ms anyway.
Per @flaeri's suggestion I tried using faster encoding parameters, `-cpu-used 6 -crf 30 -b:v 0 -usage good -row-mt 1 -tiles 4x2` and `-cpu-used 6 -crf 30 -b:v 0 -usage realtime -row-mt 1 -tiles 4x2`
I've tried both I420 and I444. I want to use the libaom-av1 for the lossless I444 support, which the libsvtav1 doesn't support, but I haven't gotten any encoder argument to work in Custom Output

> There is no timeout protections in custom ffmpeg output, and libaom-av1 is incredibly slow (hard to run) by default. If a large amount of lag happens, it does indeed crash.
> 
> You need to take extreme caution to monitor the lag. It works fine for me as long as I speed it up substantially using certain parameters, so that no lag happens.

Are you using Custom Output? would you be able to share your arguments?
I've tried the above arguments with 1, and 5 fps, where it crashes less often but even still it produces only a shell of a file of 262 bytes (depending on how long i let it run for, maybe it's crashing at a certain number of frames?)

It's just weird that the libsvtav1 one works without any parameters, and up to 30 fps as well

I've tested on two separate laptops: one with a ryzen 5850u 8 core processor, and another with an intel xeon 2176m 6 core processor.

**Comment by flaeri** [comment]
I'm happy to go thru it if you want in the Discord server if you want (https://obsproject.com/discord). Feel free to ping me in the "encoding" channel.

Personally I feel like that's the better option, as its turning more away from a bug report / issue submission, and I believe we can probably get it to work.

**Comment by PatTheMav** [comment]
Closing as per prior comment: Custom FFmpeg output is an unsupported export mode with the expectation that errors found are fixed by reporters themselves.

If there is indeed a bug in FFmpeg, please report it upstream.
