### ISSUE TITLE
Python scripts -- "No properties available"

### ISSUE THREAD

**Issue by super-ibby** [obsproject/obs-studio#7473]
### Operating System Info

macOS 12

### OBS Studio Version

28.0.2

### OBS Studio Log URL

https://obsproject.com/logs/5rqErfctap_wfino

### Expected Behavior

Upon loading of Python script, properties should be available.

### Current Behavior

A message saying "No properties available" appears when trying to run the obs-zoom-and-follow script from this repo:
https://github.com/tryptech/obs-zoom-and-follow

Upon inspecting the log, it appears OBS fails to "load" or recognise Python.

### Steps to Reproduce

1. In **Terminal**, enter `which python`. Note the **directory** in which the python interpreter is located. 
2. In **OBS**, go to `Tools` -> `Scripts`.
3. Under the `Python Settings` tab, enter the path to the **directory** in which the python interpreter is located (i.e. from step 1, above).
4. Under the `Scripts` tab, click the `+` icon to add the `zoom_and_follow_mouse.py` script downloaded from [this repo](https://github.com/tryptech/obs-zoom-and-follow).
5. Observe that the `Description` box on the right displays "No properties available".

See additional screenshots, [here](https://github.com/tryptech/obs-zoom-and-follow/issues/70).

### Anything else we should know?

- Python version is `3.8.5` in a **Miniconda** installation.
- I'm not aware of any additional non-standard Python libraries that may be required in my environment in order to leverage the scripts. Please document this somewhere if there are such dependencies.
- Also, the log is not very helpful in deducing why Python cannot be "loaded" as it simply states: `[Python] Could not load library: /Users/ibby/miniconda3/bin/`.
- I've also tried pointing OBS to the global installation of Python built into MacOS (under `/usr/bin`), however that did not work either (even after removing the Miniconda installation from my `~/.zshrc` file).

**Comment by PatTheMav** [comment]
Starting with OBS 28 we require a Python Framework installation as is standard on macOS (as shipped by Apple or installed by Homebrew).

Linux-style Python installations are not supported.

**Comment by super-ibby** [comment]
Hi, thanks for the response.

I've removed references to `miniconda3`, and pointed OBS to the system installation on macOS Monterey 12.6 (that is, `python 3.7`). I'm not exactly sure which path OBS expects. I've tried many, all to no avail:

```
12:24:37.183: [Python] Could not load library: /usr/local/bin/
12:25:12.460: [Python] Could not load library: /usr/local/lib/python3.10/
12:25:26.840: [Python] Could not load library: /usr/local/lib/python3.7/
12:25:32.804: [Python] Could not load library: /usr/local/lib/python3.7/site-packages/
12:25:55.123: [Python] Could not load library: /usr/local/bin/
12:26:12.795: [Python] Could not load library: /usr/local/opt/python@3.10/
12:26:28.056: [Python] Could not load library: /usr/local/Cellar/python@3.10/3.10.7/bin/
12:26:42.014: [Python] Could not load library: /usr/local/Cellar/python@3.10/3.10.7/libexec/bin/
12:27:17.493: [Python] Could not load library: /usr/local/Cellar/python@3.10/3.10.7/libexec/
12:29:07.001: [Python] Could not load library: /usr/bin/
```

Note that I've also installed `python 3.10` via Homebrew. Again, no luck.

Are you sure it supports the out-of-the-box installation of Python on MacOS? If so:
- Please can you point to where it might be expecting this?
- Shouldn't OBS find it automatically (unless I override it)?

Thanks again!

**Comment by PatTheMav** [comment]
There is no "system installation" of Python 3 on macOS - Apple removed it from the base system and it's only available via Xcode or the Developer Utilities - in that case the framework is located at `/Applications/Xcode.app/Contents/Developer/Library/Frameworks`.

If installed via Homebrew, Frameworks are installed to `/usr/local/Frameworks` or `/opt/homebrew/Frameworks` respectively. This is also where the "default" Python3 (as considered by Homebrew) is installed and that's the directory you need to configure.

**Comment by super-ibby** [comment]
Hi, apologies -- haven't had a chance to give that a go until now.

I have the Developer Utilities installed, but again, no luck pointing to those directories:

```
14:15:53.937: [Python] Could not load library: /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/
14:16:07.005: [Python] Could not load library: /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/
14:16:14.421: [Python] Could not load library: /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/
14:16:47.505: [Python] Could not load library: /usr/local/Frameworks/Python.framework/
```

Any thoughts?

**Comment by super-ibby** [comment]
Having stepped through [the source code](https://github.com/obsproject/obs-studio/blob/24a123119ace78b58bbc3e852aa69977faf46d90/deps/obs-scripting/obs-scripting-python-import.c#L82), I finally got it working by pointing to **the folder containing the `Python.framework` folder**, i.e. the following for my Homebrew installation:

```
/usr/local/Cellar/python@3.10/3.10.7/Frameworks
```

It **does not** work using the Xcode Developer Tools installation of Python:

```
/Applications/Xcode.app/Contents/Developer/Library/Frameworks/
```

That's because this location contains a `Python3.framework` folder, but the source code explicitly expects a `Python.framework` folder -- [see line 39](https://github.com/obsproject/obs-studio/blob/24a123119ace78b58bbc3e852aa69977faf46d90/deps/obs-scripting/obs-scripting-python-import.c#L39).

**Comment by sheatsley** [comment]
> Having stepped through [the source code](https://github.com/obsproject/obs-studio/blob/24a123119ace78b58bbc3e852aa69977faf46d90/deps/obs-scripting/obs-scripting-python-import.c#L82), I finally got it working by pointing to **the folder containing the `Python.framework` folder**, i.e. the following for my Homebrew installation:
> 
> ```
> /usr/local/Cellar/python@3.10/3.10.7/Frameworks
> ```
> 
> It **does not** work using the Xcode Developer Tools installation of Python:
> 
> ```
> /Applications/Xcode.app/Contents/Developer/Library/Frameworks/
> ```
> 
> That's because this location contains a `Python3.framework` folder, but the source code explicitly expects a `Python.framework` folder -- [see line 39](https://github.com/obsproject/obs-studio/blob/24a123119ace78b58bbc3e852aa69977faf46d90/deps/obs-scripting/obs-scripting-python-import.c#L39).

Just wanted to say thanks for looking into this. I was having trouble getting OBS to recognize my Python installation via homebrew on my M1. I was able to adapt your steps to my environment. For those in the same boat, this path worked for me (macOS 12.6 on M1, OBS 28.0.3, Python 3.10.8 via homebrew):
`/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks`

**Comment by PatTheMav** [comment]
> Having stepped through [the source code](https://github.com/obsproject/obs-studio/blob/24a123119ace78b58bbc3e852aa69977faf46d90/deps/obs-scripting/obs-scripting-python-import.c#L82), I finally got it working by pointing to **the folder containing the `Python.framework` folder**, i.e. the following for my Homebrew installation:
> 
> ```
> /usr/local/Cellar/python@3.10/3.10.7/Frameworks
> ```
> 
> It **does not** work using the Xcode Developer Tools installation of Python:
> 
> ```
> /Applications/Xcode.app/Contents/Developer/Library/Frameworks/
> ```
> 
> That's because this location contains a `Python3.framework` folder, but the source code explicitly expects a `Python.framework` folder -- [see line 39](https://github.com/obsproject/obs-studio/blob/24a123119ace78b58bbc3e852aa69977faf46d90/deps/obs-scripting/obs-scripting-python-import.c#L39).

Good catch, would you be willing to open a PR to support both? Because I think at the very least we should support the Python framework shipped by Apple (even via the Developer Tools) as well as "custom" installations via Homebrew.
