### ISSUE TITLE
Checkout Page In Games Easily Visible When Game Capture is set to Capture any fullscreen application.

### ISSUE THREAD

**Issue by MrTeeXD** [obsproject/obs-studio#7485]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.2

### OBS Studio Log URL

https://obsproject.com/logs/11Xq9H0a6sGorLkM

### Expected Behavior

When the Game Capture source is set to "Capture any fullscreen application" Checkout pages in games should be blocked with a black screen instead of the full thing being shown

### Current Behavior

![obs64_6JCVzbnFkV](https://user-images.githubusercontent.com/37266538/192843212-05fac507-5657-4b14-b9d9-34b705389e52.png)

### Steps to Reproduce

1. Add a Game Capture source
2. Set the Capture Method to Capture any fullscreen application
3. Open any game that is in Windowed Mode or Fullscreen
4. Go to the game's checkout page where you navigate to entering a Credit Card Information

### Anything else we should know?

When the Game Capture is set to "Capture Specific Window" the checkout page gets blocked from View.

**Comment by gxalpha** [comment]
> When the Game Capture source is set to "Capture any fullscreen application" Checkout pages in games should be blocked with a black screen instead of the full thing being shown

Is that something we're claiming somewhere, or do you just think that it should be the expectation?

**Comment by Fenrirthviti** [comment]
This sounds like a feature request, not a bug report. Please use the [ideas page](https://ideas.obsproject.com/) for new feature requests.

**Comment by jp9000** [comment]
We unfortunately are not able to simply automatically determine whether something that's being captured happens to be sensitive or private information. It's up to the user to disable their capture before getting to that point.
