### ISSUE TITLE
Memory corruption in other programs due to OBS / Application Audio Capture

### ISSUE THREAD

**Issue by 9001** [obsproject/obs-studio#7487]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.2

### OBS Studio Log URL

https://ocv.me/stuff/bugs/obs/appaucap-memsmash/2022-09-26_16-32-01.txt

### OBS Studio Crash Log URL

https://ocv.me/stuff/bugs/obs/appaucap-memsmash/Crash_2022-09-17_14-25-11.txt

### Expected Behavior

not corrupting the memory of other applications while streaming

### Current Behavior

okay, so this is kinda bonkers but grab some popcorn and read on (y)

been helping a friend debug some crazy issues with his OBS; every time he streamed:
* firefox and chrome would start reading corrupted data from disk during file uploads
  * the corruption happened somewhere between the filesystem and javascipt, not between the browser and the server
  * unfortunately don't have any samples (not sure if it was bitflips or nulls or whatever) since the ranges got server-rejected due to bad checksums
* firefox and chrome would suddenly "white out", entire window just turning white, followed by [various crashes](https://ocv.me/stuff/bugs/obs/appaucap-memsmash/firefoxreport.txt)
  * happened exactly in time with [these spikes](https://ocv.me/stuff/bugs/obs/appaucap-memsmash/obs-spikes.png) (and [another](https://ocv.me/stuff/bugs/obs/appaucap-memsmash/gpu-spikes-2.png) example)
  * didn't get a crashdurmp from chrome but once it said RESULT_CODE_KILLED_BAD_MESSAGE
  * crashes would usually happen in quick succession, in one case it was obs first, then firefox, then chrome, all throwing fastfails -- [some eventviewer entries](https://ocv.me/stuff/bugs/obs/appaucap-memsmash/eventviewer.txt)
* a completely unrelated program (written in go) would have a single goroutine deadlock, and it also [crashed once](https://ocv.me/stuff/bugs/obs/appaucap-memsmash/reportyta.txt)
  * it has two goroutines running in parallel doing essentially the same thing, which is downloading different chunks of data from the same server over https and writing to files on disk, and only one of those two got stuck
  * citing some devs, *"null pointer in the runtime... ye his RAM is fubar mate"* -- and -- *"there's no way for a goroutine to be killed on its own, so it's been deadlocked somehow"*

of course this **Absolutely Smells Like Hardware** and that's what we assumed at first but:
* the ram survived several batches of the default 4 passes of memtest86 (OG passmark) without issue
  * and also some windows ramtester he found for 6 hours, came out clean
* furmark ran at a persistent 100% gpu load for ages without issue
* the HDD [looks fine](https://ocv.me/stuff/bugs/obs/appaucap-memsmash/chikensmart.png)

we tried a whole bunch of stuff,
* `dism /online /cleanup-image /restorehealth & sfc /scannow` was all good
* clean gpu driver reinstall with DDU, no dice
* suspecting power issues, switched from nvenc to x264, and at first it seemed like switching to the ultrafast profile made it *slightly better*, probably just chance tho
* suspecting qt6 issues, downgraded to OBS 25.0.8, **problem gone!**
* upgraded back to 28.0.2, **problem still gone!** wait what?
* reenabled Application Audio Capture, whoops there we go, it's back

and that's how we've landed at our current suspicion

### Steps to Reproduce

honestly don't know sorry (´<_`　)  
but we're happy to take questions!

**Comment by notr1ch** [comment]
Could you try without any 3rd party APOs such as A-Volute?

**Comment by 9001** [comment]
Good catch! You're right, looks like this is all due to Asus Sonic Studio and/or Sonic Radar, which means both OBS and voicemeeter are okay: https://ocv.me/stuff/bugs/obs/appaucap-memsmash/2022-09-29_10-23-42.txt

Not sure if you wanna keep this issue open to add a warning about Asus jank or whatnot :>

**Comment by Fenrirthviti** [comment]
I'll go ahead and close this, and add a note to our https://obsproject.com/wiki/Known-Conflicts page.
