### ISSUE TITLE
Crash on start almost every time

### ISSUE THREAD

**Issue by FelicitusNeko** [obsproject/obs-studio#7490]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.2

### OBS Studio Log URL

https://obsproject.com/logs/arnmlszoINFdYoS8

### OBS Studio Crash Log URL

https://obsproject.com/logs/o0rm6OA6MysY3Yx_

### Expected Behavior

OBS launches without issue every time, or at least almost.

### Current Behavior

OBS crashes on start almost every time.

### Steps to Reproduce

1. Start OBS

### Anything else we should know?

This log was taken after attempting to uninstall and reinstall OBS to fix the problem. Also, for some reason, the Tools menu lists off all plugins twice.

**Comment by notr1ch** [comment]
See https://obsproject.com/forum/threads/obs-crashing-on-startup-since-new-updated.159402/#post-584122
