### ISSUE TITLE
Cannot add JACK Input Client and the ones I already set up disappear

### ISSUE THREAD

**Issue by Willgheminass** [obsproject/obs-studio#7495]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

28.0.2

### OBS Studio Log URL

https://obsproject.com/logs/MBnmj-Xqd67Yhx6t

### Expected Behavior

To have all my JACK Input clients already set up to record my Music and Game audios separately onto different tracks. I have a qpwgraph window beside my OBS window to check and see if everything works just fine.

### Current Behavior

All my JACK Input client sources disappeared after I updated to this version and now I cannot add one, it does not even show up in the plus sign menu under "Sources" or in the right-click context menu under "Sources".

### Steps to Reproduce

1. Update OBS to ver. 28.0.2
2. Open OBS
3. Click the plus sign under "Sources" or the right-click context menu while hovering over "Sources"
4. Expect to see a "JACK Input Client" option
...

### Anything else we should know?

Everything was working just fine before I updated.

**Comment by kkartaltepe** [comment]
Please file this bug against your package manager.

**Comment by kik4444** [comment]
Same problem here. As a temporary workaround, you could try installing the flatpak version of OBS 28 and either use that, or copy its `$HOME/.local/share/flatpak/app/com.obsproject.Studio/current/active/files/lib/obs-plugins/linux-jack.so` file to your `/lib/obs-plugins` directory. Then your Arch OBS's Jack should start working.

**Comment by Willgheminass** [comment]
> Same problem here. As a temporary workaround, you could try installing the flatpak version of OBS 28 and either use that, or copy its `$HOME/.local/share/flatpak/app/com.obsproject.Studio/current/active/files/lib/obs-plugins/linux-jack.so` file to your `/lib/obs-plugins` directory. Then your Arch OBS's Jack should start working.

This worked, thank you. I cannot get input-overlay to work now even after dropping the files into the correct places like I did with the obs I installed through pacman, but separating audio was the most important thing for me.
