### ISSUE TITLE
Bluetooth audio across entire PC borderline doesn't work when audio interface is connected and OBS is open

### ISSUE THREAD

**Issue by UsernameBillion** [obsproject/obs-studio#7498]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.2

### OBS Studio Log URL

none needed

### Expected Behavior

Audio to just work

### Current Behavior

Whenever OBS is open and my scarlett 2i2 is connected, audio across my entire computer becomes basically non-functional. I'll hear maybe a half second of audio every dozen seconds. It resolves as soon as I unplug the audio interface or close OBS.

As I type this I've realised that this seemingly only affects bluetooth audio devices - audio works if I output through my PC speakers, but not through my bluetooth headphones.

No OBS settings seem to fix the issue.

### Steps to Reproduce

1. have obs running, with an audio interface connected, and audio output as bluetooth
2.
3.
...

### Anything else we should know?

I dont even have the scarlett 2i2 enabled or used as an audio source in OBS, I don't understand why this happens.

My guess is that OBS is somehow hogging audio bandwidth or something.

**Comment by notr1ch** [comment]
This sounds more like a support issue than a bug in OBS, likely USB bandwidth overload or similar. Please use the forums or Discord for support issues (https://obsproject.com/help).
