### ISSUE TITLE
Advanced FFmpeg custom output on Full colour range produces green video.

### ISSUE THREAD

**Issue by tearfur** [obsproject/obs-studio#7500]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.2

### OBS Studio Log URL

https://obsproject.com/logs/nZYpEE9LQRFbZQrp

### Expected Behavior

A video with full range colour is produced.

### Current Behavior

A video with a heavy green tint is produced.

### Steps to Reproduce

1. Create a new profile.
2. Select "Advanced" output mode and "Custom Output (FFmpeg)", any video format will do.
3. Select NV12, Rec. 709 and Full range.
4. Record a video with this profile.

**Comment by kkartaltepe** [comment]
Fixed in next release.
