### ISSUE TITLE
EOS Web Utility doesn't show up in list of inputs for video source

### ISSUE THREAD

**Issue by Blue-EyesWhiteDragon** [obsproject/obs-studio#7501]
### Operating System Info

macOS 12

### OBS Studio Version

28.0.2

### OBS Studio Log URL

https://obsproject.com/logs/Ef8w-PQlOZsND7oj

### Expected Behavior

EOS Web Utility or camera showing up as an option for Video Capture Device

### Current Behavior

EOS Web Utility or camera doesn't show up as an option in OBS Studio but will show up in Streamlabs OBS.

### Steps to Reproduce

1. Turn on Camera
2. Plug in USB
3. Make sure EOS Utility isn't running as this clashes with EOS Web Utility4. 
4. Boot up OBS
5. Create new Video Capture
6. Only option there is webcam or existing peripherals

### Anything else we should know?

Works in Streamlabs 1.11.0 for Mac OS

I am on M1 Max running OBS in Metal / Apple Silicon

**Comment by gxalpha** [comment]
You're running the native version of OBS. For the EOS Webcam utility to get picked up, it also needs to be native (or better even universal), as OBS itself loads the camera plugin and Rosetta doesn't allow mixing native and translated code.
You can work around this by running the Rosetta version of OBS 28.

**Comment by Blue-EyesWhiteDragon** [comment]
Ah I see, I thought the Steamlabs was an Universal binary, however it is intel. My apologies.

**Comment by Blue-EyesWhiteDragon** [comment]
Y'all ever making a Universal Binary?

**Comment by gxalpha** [comment]
Never say never, but it doesn't look likely.
It wouldn't change this situation though. The programs runs *either* natively, or as Rosetta. There is no mixing during runtime, universal binaries just make distributing simpler. You still run only one architecture.

**Comment by Blue-EyesWhiteDragon** [comment]
@gxalpha Just don't want to download two versions of OBS for one to become redundant when and if Canon ever update their software.
