### ISSUE TITLE
No Sign of obs-websocket on version OBS 28.0.2-2 (linux)

### ISSUE THREAD

**Issue by ArtiomSu** [obsproject/obs-studio#7508]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

28.0.2

### OBS Studio Log URL

https://obsproject.com/logs/nSC0vlgklHozPaWI

### Expected Behavior

web-sockets plugin should show up in Tools. Client should be able to connect to it.

### Current Behavior

No sign of web-sockets anywhere.

### Steps to Reproduce

1. run obs --verbose
2. press tools
3. nothing shows up
...

**Comment by kkartaltepe** [comment]
We do not maintain the arch linux packages, if you find components missing please file a bug with your package manager.

**Comment by ArtiomSu** [comment]
> We do not maintain the arch linux packages, if you find components missing please file a bug with your package manager.

Thanks I thought they just pulled and repackaged ubuntu one.

I tried the flathub version and its working there just fine. My apologies keep up the good work
