### ISSUE TITLE
Characters do not appear on the screen when using fonts from cloud font services

### ISSUE THREAD

**Issue by hoehoetvhss** [obsproject/obs-studio#7509]
### Operating System Info

Windows 10

### OBS Studio Version

Git

### OBS Studio Version (Other)

28.0.3

### OBS Studio Log URL

https://obsproject.com/logs/OXhAj8BNKT25_S6O

### Expected Behavior

The text should appear on the screen.

### Current Behavior

Text does not appear on the screen.

### Steps to Reproduce

1. Create text.
2. Select the font provided by the cloud font service for the font of the text.

### Anything else we should know?

In the 27.X version of OBS Studio it worked fine.

**Comment by RytoEX** [comment]
Please re-test in OBS Studio 29.0.2 (or newer). Please also test this in the FreeType2 text source.

What is a "cloud font service"? What font is being loaded?

**Comment by hoehoetvhss** [comment]
I'll close this issue as I'll have to try again on the new version.
