### ISSUE TITLE
macOS Screen Capture (BETA) doesn’t Allow You to Zoom & Hides Menubar Icons

### ISSUE THREAD

**Issue by leafac** [obsproject/obs-studio#7511]
### Operating System Info

macOS 12

### OBS Studio Version

28.0.2

### OBS Studio Log URL

Doesn’t Apply

### Expected Behavior

macOS has this feature in which you can zoom into the whole display. This can be enabled under **System Preferences > Accessibility > Zoom**. It’s useful on tutorials, video-chats, and so forth.

The **Display Capture** source in OBS shows the zooming as you’d expect, but the **macOS Screen Capture (BETA)** doesn’t. You zoom, you see the zoom in your display, but OBS doesn’t capture that.

Also, the **macOS Screen Capture (BETA)** hides a couple menubar icons (those icons on the top right showing the volume, wifi status, and so forth). Again, **Display Capture** gets this right.

### Current Behavior

(Explained in **Expected Behavior**)

### Steps to Reproduce

(Explained in **Expected Behavior**)

### Anything else we should know?

Thank you very much for OBS. I love it and use it every day 😁

**Comment by gxalpha** [comment]
> macOS has this feature in which you can zoom into the whole display. This can be enabled under System Preferences > Accessibility > Zoom. It’s useful on tutorials, video-chats, and so forth.
> 
> The Display Capture source in OBS shows the zooming as you’d expect, but the macOS Screen Capture (BETA) doesn’t. You zoom, you see the zoom in your display, but OBS doesn’t capture that.

I cannot reproduce this on macOS 13, when zooming in only the visible part of the Display is captured. The API we're using has quite a few bugs on macOS 12, this might be one of them. 

> Also, the macOS Screen Capture (BETA) hides a couple menubar icons (those icons on the top right showing the volume, wifi status, and so forth). Again, Display Capture gets this right.

This part is expected due to a workaround we have to do because of a bug on macOS 12. It will work correctly on macOS 13.

**Comment by leafac** [comment]
@gxalpha Thanks for the information 😁
