### ISSUE TITLE
OBS freezes under specific circumstances when switching a scene with a python script

### ISSUE THREAD

**Issue by MadnessOverflow** [obsproject/obs-studio#7516]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

28.0.3

### OBS Studio Log URL

https://obsproject.com/logs/agQfH2AoIh91lF3r

### Expected Behavior

I wrote a python script adding a frontend event callback with
`obs.obs_frontend_add_event_callback(test)`

In this callback I am printing out "hello" whenever it the callback is invoked (for test purposes)
```
def test(event):
    print("lol")
```
Now I am switching the current obs scene with my script via:
```
def obs_set_current_scene(scene):
    scene_t = obs.obs_get_scene_by_name(scene)
    source_t = obs.obs_scene_get_source(scene_t)
    obs.obs_frontend_set_current_scene(source_t)
    obs.obs_scene_release(scene_t)
```
(the parameter scene represents the scene name i get from my scripts properties)

Now I am expecting OBS to switch the scene and to print out "hello" 3 times.

3 times because of the following 3 events:
```
OBS_FRONTEND_EVENT_PREVIEW_SCENE_CHANGED
OBS_FRONTEND_EVENT_TRANSITION_STOPPED
OBS_FRONTEND_EVENT_SCENE_CHANGED
``` 

### Current Behavior

OBS freezes on Scene switch. 
As you can see, the last message in the log is my script telling me that it is going to switch the scene.

Then OBS just freezes and I need to close it manually. Sadly no crash report is created by doing this.
I tracked the bug/crash down to this specific scenario.

If you switch the scene manually it is just working fine: 
OBS is printing "hello" 3 times (also can be seen in the log)

And if you don't add an event callback it is also working fine:
My script just switches the scene without crashing.

Only if both things are done in the same script it crashes on Scene Switch

### Steps to Reproduce

1. add an event callback with `obs.obs_frontend_add_event_callback(test)` (f.ex. in script_load())
2. try to switch the scene with your python script using ` obs.obs_frontend_set_current_scene(source_t)`
3. OBS freezes

### Anything else we should know?

I tried this on all OBS 28 versions and the behaviour is always the same. 
I really need this functionality because originally I am switching the scene with one python script and reacting to it with another python script. But this error seems to occur even if you are doing it in the same script.

**Comment by PatTheMav** [comment]
How do you trigger the scene change? I'm not able to reproduce the issue with this test script:

```
import obspython as obs

def _callback(event):
    print(f"_callback: {event}")

def _change_callback(props, prop):
    obs_set_current_scene("Scene 2")
    
def obs_set_current_scene(scene):
    scene_t = obs.obs_get_scene_by_name(scene)
    source_t = obs.obs_scene_get_source(scene_t)
    obs.obs_frontend_set_current_scene(source_t)
    obs.obs_scene_release(scene_t)

def script_load(settings):
    print("Script loaded...")
    obs.obs_frontend_add_event_callback(_callback)

def script_description():
    return "Test script for events"

def script_update(settings):
    pass

def script_unload():
    pass

def script_properties():
    props = obs.obs_properties_create()
    obs.obs_properties_add_button(props, "button", "Change Scene", _change_callback)
    return props

def script_save(settings):
    pass
```

Generated the following output:

```
info: [Python: event_test.py] _callback: 24
info: User switched to scene 'Scene 2'
info: [Python: event_test.py] _callback: 11
info: [Python: event_test.py] _callback: 8
```

**Comment by MadnessOverflow** [comment]
You are right. With your script it is actually working.
My Code is pretty specific so I looked further into it and found that when invoking the scene switch from a Thread using asyncio.

Using the following code I got OBS to crash:

```
import obspython as obs
import threading

scene_name = None

def _callback(event):
    print(f"_callback: {event}")


def _change_callback(props, prop):
    thread = threading.Thread(target=obs_set_current_scene, args=(scene_name,), daemon=True)
    thread.start()


def obs_set_current_scene(scene):
    scene_t = obs.obs_get_scene_by_name(scene)
    source_t = obs.obs_scene_get_source(scene_t)
    obs.obs_frontend_set_current_scene(source_t)
    obs.obs_scene_release(scene_t)


def script_defaults(settings):
    pass


def script_load(settings):
    print("Thread Script loaded...")
    obs.obs_frontend_add_event_callback(_callback)


def script_unload():
    obs.obs_frontend_remove_event_callback(_callback)
    pass


def script_description():
    return "Test Script."


def script_update(settings):
    global scene_name
    scene_name = obs.obs_data_get_string(settings, "scene")


def script_properties():
    props = obs.obs_properties_create()

    p1 = obs.obs_properties_add_list(props, "scene", "Scene", obs.OBS_COMBO_TYPE_EDITABLE,
                                     obs.OBS_COMBO_FORMAT_STRING)
    scenes = obs.obs_frontend_get_scenes()
    if scenes is not None:
        for scene in scenes:
            name = obs.obs_source_get_name(scene)
            obs.obs_property_list_add_string(p1, name, name)

        obs.source_list_release(scenes)
    obs.obs_properties_add_button(props, "button", "Change Scene", _change_callback)
    return props
```

**Comment by PatTheMav** [comment]
OBS freezes because Python uses a global interpreter lock (GIL) which means that only one Python thread can be active at a time. In your case you start the thread, which waits for the lock to be released, which never happens because OBS holds the lock for executing your script.

In essence: Don't use threads in Python scripts. Our scripting functionality is not meant for complex, multithreaded, workflows, but instead for automating things you'd normally do manually.

**Comment by MadnessOverflow** [comment]
And this is the reasion for OBS freezing in my case? 
I'm understanding why my test script is causing a freeze now but in my case I am able to switch the scene using another Thread and it isn't a problem until i add a callback for the scene switch.

Is this the same Problem with Python's GIL?
