### ISSUE TITLE
HDR AMD HEVC Gets Tagged With YCoCg When Full Color Range Is Selected

### ISSUE THREAD

**Issue by jansol** [obsproject/obs-studio#7518]
### Operating System Info

Windows 11

### OBS Studio Version

Other

### OBS Studio Version (Other)

28.0.3

### OBS Studio Log URL

https://obsproject.com/logs/RIc2GTfkdX5ap_00

### Expected Behavior

OBS either records a valid video or tells me the configuration is not supported.

### Current Behavior

OBS records a video with wrong colors.

### Steps to Reproduce

1. Record a game running with Windows 11 AutoHDR and color range set to full (10bit HEVC bt2100, mkv container)
2. Open recorded video in MPV or Chrome
3. Colors are all green-pink
4. Use ffprobe or mkvinfo to confirm that the video bitstream is tagged as YCoCg.

Opening the video in VLC does not work. Apparently VLC ignores the ycocg tag.

### Anything else we should know?

Prior problem exploration: mpv-player/mpv#10696

**Comment by flaeri** [comment]
Cannot reproduce on windows with MPV, looks fairly normal.

When I record using your settings, I dont get `YCoCg` as my matrix coefficient, I get `BT.2020 nc`

```
Color range                              : Full
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : Display P3
Mastering display luminance              : min: 0.0000 cd/m2, max: 1000 cd/m2
Maximum Content Light Level              : 1000
MaxCLL_Original                          : 1000 cd/m2
Maximum Frame-Average Light Level        : 1000
MaxFALL_Original                         : 1000 cd/m2
```

**Comment by jansol** [comment]
That is the driver that Windows installed automagically. Tried again after manually installing 22.9.2 drivers and the problem indeed seems to be gone.

**Comment by ZaquL** [comment]
> Tried again after manually installing 22.9.2 drivers and the problem indeed seems to be gone.

WOW!
