### ISSUE TITLE
Loading any SRT stream via Media Source causes rendering freeze

### ISSUE THREAD

**Issue by fGeorjje** [obsproject/obs-studio#7521]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

28.0.3

### OBS Studio Log URL

https://obsproject.com/logs/fT1FBuieL943kCZW

### Expected Behavior

SRT streams via Media Source should be loaded asynchronously in the background.

### Current Behavior

Loading any SRT stream via Media Source causes temporary freeze. UI thread is not affected.

### Steps to Reproduce

1. Create a Media Source
2. Input any srt:// URL (valid or invalid)
3. Observe the preview (and recording) freezing for a temporary amount of time

### Anything else we should know?

live video demonstration: https://www.youtube.com/watch?v=wnEnUQtoG-Y

my best guess is that SRT initialization logic is accidentally running on the main graphics thread

**Comment by PatTheMav** [comment]
Cannot reproduce on macOS, neither UI nor recording/preview output is affected by loading an SRT stream into a media source - will require separate reproduction on Windows.
