### ISSUE TITLE
OBS craches on Windows 10 and not re-installing Nvidia drivers didn't resoved the crach issue

### ISSUE THREAD

**Issue by AKhateeb** [obsproject/obs-studio#7524]
### Operating System Info

Windows 10

### Other OS

OBS v28.0.3 Craches on Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

v28.0.3

### OBS Studio Log URL

https://obsproject.com/logs/DB-E5-fEVLDOEtZR

### OBS Studio Crash Log URL

https://obsproject.com/logs/DB-E5-fEVLDOEtZR

### Expected Behavior

I want to record my screen

I reinstalled NVidia driver GeForce 740 M but didn't solve the crash

### Current Behavior

keeps crashing after a few seconds of running

### Steps to Reproduce

1. Run the OBS
2. Crached
3. killed after closing the catch dialog
...
![image](https://user-images.githubusercontent.com/19706280/193800339-57688fa6-0c93-4f38-a9e6-64678daadc98.png)

**Comment by WizardCM** [comment]
Please post the crash log link from Help -> Crash Reports -> Upload Last Crash Report.

**Comment by RytoEX** [comment]
Closing this. Without a crash log, this is not actionable.
