### ISSUE TITLE
Crashes in Firefox, caused by an Apple bug, but possibly triggered by OBS

### ISSUE THREAD

**Issue by steven-michaud** [obsproject/obs-studio#7528]
### Operating System Info

Other

### Other OS

macOS 10.15, 11, 12 and 13

### OBS Studio Version

Other

### OBS Studio Version (Other)

28.0 and up

### OBS Studio Log URL

na

### OBS Studio Crash Log URL

na

### Expected Behavior

na

### Current Behavior

na

### Steps to Reproduce

na

### Anything else we should know?

I'm investigating reports of crashes in Firefox, in a BMO (bugzilla.mozilla.org) [bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1793538). There's evidence that OBS is involved. It's all circumstantial -- I don't yet have STR. But the circumstantial evidence is quite compelling, I think.

The crashes are [almost certainly an Apple bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1793538#c9). But I'm pretty sure OBS is somehow triggering them. [Judging by when the crash reports started appearing, they started happening with OBS 28.0](https://bugzilla.mozilla.org/show_bug.cgi?id=1793538#c13). The `obs-mac-virtualcam` module appears in the list of modules of all the crash reports I've looked at. The "debug id" (aka the UUID) of that module in the most recent crash reports matches that of the same module in the most recent (version 28.0.3) OBS installer (58738D38-F229-33D0-9D13-82A340332318 on Intel). So even the most recent version of OBS is still effected.

All the most interesting and useful information is at https://bugzilla.mozilla.org/show_bug.cgi?id=1793538. It will be updated as we (at Mozilla) find out more. But I'll try to give a brief (and hopefully clear) summary here:

Here's a ersatz crash stack. It was made in `lldb`, but (unfortunately) it's more accurate than the crash stacks in Mozilla's crash reports:

```
* thread #110, queue = 'org.webrtc.videocapture', stop reason = breakpoint 2.1
  * frame #0: 0x00007ff81205c110 CoreFoundation`CFRunLoopAddSource
    frame #1: 0x00000001a6bf5b4c CMIOBaseUnits`___lldb_unnamed_symbol389$$CMIOBaseUnits + 226
    frame #2: 0x00000001a6c6c5cf CMIOBaseUnits`___lldb_unnamed_symbol1346$$CMIOBaseUnits + 29
    frame #3: 0x00000001a6c23120 CMIOBaseUnits`___lldb_unnamed_symbol762$$CMIOBaseUnits + 58
    frame #4: 0x00000001a6befd1a CMIOBaseUnits`___lldb_unnamed_symbol330$$CMIOBaseUnits + 102
    frame #5: 0x00000001a6bf7ef1 CMIOBaseUnits`___lldb_unnamed_symbol421$$CMIOBaseUnits + 23
    frame #6: 0x00000001a6c04a16 CMIOBaseUnits`___lldb_unnamed_symbol551$$CMIOBaseUnits + 43
    frame #7: 0x00007ff81fd12505 CoreMediaIO`CMIOUnitNodeInfo::Initialize(CMIOGraph*) + 57
    frame #8: 0x00007ff81fd04e00 CoreMediaIO`CMIOGraph::Initialize() + 3072
    frame #9: 0x00007ff82be5d356 AVFCapture`-[AVCaptureSession_Tundra _buildAndRunGraph] + 2029
    frame #10: 0x00007ff82be5e913 AVFCapture`-[AVCaptureSession_Tundra _setRunning:] + 456
    frame #11: 0x00007ff82be5e460 AVFCapture`-[AVCaptureSession_Tundra startRunning] + 180
    frame #12: 0x0000000112ba7827 XUL`-[RTCVideoCaptureIosObjC startCaptureInBackgroundWithOutput:](self=0x0000000132708ac0, _cmd=<unavailable>, currentOutput=<unavailable>) at rtc_video_capture_objc.mm:200:3 [opt]
    frame #13: 0x00007ff811e030cc libdispatch.dylib`_dispatch_call_block_and_release + 12
    frame #14: 0x00007ff811e04317 libdispatch.dylib`_dispatch_client_callout + 8
    frame #15: 0x00007ff811e0a317 libdispatch.dylib`_dispatch_lane_serial_drain + 672
    frame #16: 0x00007ff811e0adfd libdispatch.dylib`_dispatch_lane_invoke + 366
    frame #17: 0x00007ff811e14eee libdispatch.dylib`_dispatch_workloop_worker_thread + 753
    frame #18: 0x00007ff811fb7fd0 libsystem_pthread.dylib`_pthread_wqthread + 326
    frame #19: 0x00007ff811fb6f57 libsystem_pthread.dylib`start_wqthread + 15
```

There's a single line of Mozilla code here (`XUL:-[RTCVideoCaptureIosObjC startCaptureInBackgroundWithOutput:]`). But all the rest is system (Apple) code.

My current speculation is that these crashes have something to do with sleeping and waking. Their proximate cause is misbehavior by the [`IORegisterForSystemPower()` system call](https://developer.apple.com/documentation/iokit/1557114-ioregisterforsystempower), which has to do with registering for sleep and wake notifications.

I'll learn more over time, and hopefully I'll be able to come up with STR. But I know almost nothing about OBS. So people here, who know more about it, may be able to help at https://bugzilla.mozilla.org/show_bug.cgi?id=1793538.

**Comment by PatTheMav** [comment]
See my comment here - we’ve reported this to Apple already: https://github.com/obsproject/obs-studio/issues/7287#issuecomment-1268187358

**Comment by PatTheMav** [comment]
While this is valid, it's a duplicate of #7287 - feel free to reference that bug in the bugzilla issue as well and mention our agreement that this looks like some internal issue of IOKit:

https://github.com/opensource-apple/IOKitUser/blob/b80a5cbc0ebfb5c4954ef6d757918db0e4dc4b7f/IOKitLib.c#L674

IOKit tries to open a mach port with a port number and receives a "cached" port (but it needs a fresh one). We have no insight into which port that is and I currently do not think it is related to the mach ports we use for the virtual camera.

Closed as duplicate.

**Comment by steven-michaud** [comment]
Thanks, @PatTheMav, for this information. Given that these crashes have nothing to do with sleeping and waking, I think your theory (that this has to do with "cached" ports) is more likely to be true than mine (that this is caused by `IONotificationPortGetRunLoopSource()` failing to do an error return when it should).

I assume you're aware that, even if Apple fixes this bug, it will only be in macOS 13. Unless it somehow turns out to be a security bug, or bigger fish are involved than OBS Project or Mozilla.

**Comment by PatTheMav** [comment]
Yeah that thought occurred to me this morning as well, we've been looking into Apple's Camera Extensions which have been introduced in 12.3 and allow for "native" virtual camera support.

Any system that supports 12.6 and beyond should be able to use that "new" virtual camera (which would implicitly avoid this issue) and older systems - namely those that did not support macOS 12 - might not even be affected by this issue, but we haven't had the resources to track down how "old" this issue might be.
