### ISSUE TITLE
OBS DRIVER TIMEOUT ISSUE

### ISSUE THREAD

**Issue by DarkestFantasies** [obsproject/obs-studio#7532]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.3

### OBS Studio Version (Other)

27.2.4

### OBS Studio Log URL

https://drive.google.com/drive/folders/1RMwN31MiyqIfHUoXwjYlkRIin3MF7dpa?usp=sharing

### OBS Studio Crash Log URL

https://drive.google.com/drive/folders/1RMwN31MiyqIfHUoXwjYlkRIin3MF7dpa?usp=sharing

### Expected Behavior

I want the program to run stably.

### Current Behavior

when i try to open it, my screen go black without a reason and then a window pop up with message "driver timeout" and windows says "application has been blocked from accessing graphics hardware"

### Steps to Reproduce

1.Start PC
2.wait 15-20 seconds
3.open obs

### Anything else we should know?

i thought and i think that it is gpu-related problem, but when i place my gpu on another pc obs starts without errors. the only version of amd drivers that doesn't make obs crash on startup (on my pc) is 20.12.1, but there are a lot of bugs and i cant use it. the only version of the amd drivers that doesn't cause obs to crash on startup (on my computer) is 20.12.1 but it has a lot of bugs and I can't use it.

I even reinstalled windows, installed only chipset drivers and then amd drivers and i had no luck, the same problem happened again on pure system.

**Comment by gxalpha** [comment]
This issue appears to be a support request, for which we don't use GitHub Issues.
Please make sure to visit the support sections on our [Discord server](https://discord.gg/obsproject) or [Forums](https://obsproject.com/forum).

Thank you!
