### ISSUE TITLE
OBS (Flatpak, Wayland) Replay Buffer runs into an error saying "An unspecified error occurred while recording." after a certain amount of time.

### ISSUE THREAD

**Issue by IAmV0id** [obsproject/obs-studio#7534]
### Operating System Info

Other

### Other OS

Fedora 37

### OBS Studio Version

28.0.3

### OBS Studio Log URL

https://obsproject.com/logs/zWrJjVBaafqxWQUQ

### Expected Behavior

Replay buffer functions as normal, without running into an error.

### Current Behavior

Replay buffer works for a small amount of time, before ultimately stopping with a error message popping up saying "An unspecified error occurred while recording."

Afterwards, the "Record" button says "Stopping recording" indefinitely, despite replay buffer being used.

### Steps to Reproduce

1. Launch OBS Flatpak
2. Enable replay buffer (I set it to 60 seconds, 1024MB)
3. Start replay buffer
4. Wait a bit, it could be a minute before an error shows up
5. Window pops up saying "An unspecified error occurred while recording."
...

### Anything else we should know?

**This problem only occurs on Wayland, X11 had no issues.**
**This problem does not happen on the native RPM OBS, this only seems to effect the flatpak version on Wayland.**

My system uses a NVIDIA GTX 1080.

**Comment by IAmV0id** [comment]
Interesting, I have seem to fixed this issue by completely wiping the OBS Flatpak folder in .var

Not sure what caused this, but out of sight, out of mind. Since the problem has been solved, I'll close the issue.

**Comment by IAmV0id** [comment]
Nevermind, this seem to only temporarily fix the problem. Issue has been reopened, ignore my other comment.

**Comment by tytan652** [comment]
Side note: We actually don't support Wayland on NVIDIA.

Could you try to use encoder other than NVENC for replay buffer (recording) if the same issue happen ?

**Comment by IAmV0id** [comment]
Using the software encoder (specifically the low CPU usage preset), I don't receive the error, and I can use replay buffer just fine.

However the logs still show "Failed to create xdg-screensaver: 2", this doesn't seem to cause any issues however.

Here's the logs for the session with software encoder. https://obsproject.com/logs/HU5tqASoUrK_5cqr

**Comment by tytan652** [comment]
Seems to be connected to FFmpeg NVENC. Potentially a dependency issue.

The screensaver thing, is surely OBS preventing the screensaver to be enabled.

**Comment by IAmV0id** [comment]
That would explain why the issue only persists on the flatpak package, not the native RPM package.

**Comment by RytoEX** [comment]
```
08:32:29.403: [NVIDIA NVENC H.264 (FFmpeg) encoder: 'simple_video_recording'] Encoding queue duration surpassed 5 seconds, terminating encoder
[...]
08:32:29.426: Output 'Replay Buffer': Number of lagged frames due to rendering lag/stalls: 679 (24.3%)
```
Something is causing the encoder to get backed up and then terminate. I don't know what that something is.

> This problem only occurs on Wayland, X11 had no issues.
This problem does not happen on the native RPM OBS, this only seems to effect the flatpak version on Wayland.

Does it happen with the RPM version in Wayland instead of X11? Does this still occur in OBS Studio 29.0.2 (or newer)?

**Comment by gxalpha** [comment]
There has been no response to the comment above. As such, this issue unfortunately is not actionable for us.
