### ISSUE TITLE
OBS Studio crashed when playing mkv videos

### ISSUE THREAD

**Issue by tomato013** [obsproject/obs-studio#7535]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.3

### OBS Studio Log URL

https://obsproject.com/logs/S5WKOzdzLkI9Wa2i

### Expected Behavior

No crashes.

### Current Behavior

OBS Studio crashed after clicking any video playing control buttons.

### Steps to Reproduce

1. Add multiple mkv video files to the VLC video source.
2. Stop playing / Switching or any other operations that refer to playing control.
3. OBS crashes.
...

**Comment by RytoEX** [comment]
Please provide the OBS crash log. If OBS showed a dialog saying, "Woops, OBS has crashed!", then there will be a crash log in `%APPDATA%\obs-studio\crashes`.

**Comment by tomato013** [comment]
I have already put it in OBS Studio Log URL, I'm sorry that I put it in the wrong place.

> Please provide the OBS crash log. If OBS showed a dialog saying, "Woops, OBS has crashed!", then there will be a crash log in `%APPDATA%\obs-studio\crashes`.

I have already put it in OBS Studio Log URL, I'm sorry that I put it in the wrong place.

**Comment by RytoEX** [comment]
Please also provide the regular OBS log for the session where this crash occurs. When reporting a crash, both logs are required.

In any case, this is crashing inside libvlc, so I'm not sure if this is something we can address.
