### ISSUE TITLE
AMF_FAIL when attempting to record in HDR

### ISSUE THREAD

**Issue by FireCulex** [obsproject/obs-studio#7539]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.3

### OBS Studio Log URL

https://obsproject.com/logs/q5dnolTDUB5BrwrH

### Expected Behavior

Record in HDR

### Current Behavior

Starting the output failed. Please check log files for details.

amf_hevc_create_fallback: AMFComponent::Init failed:

### Steps to Reproduce

1. Output -> Recording ->AMD HW H.265 (HEVC)
2. Settings
3. Color Format -> P010
4. Color Space -> Rec. 2100 (PQ)
5. Record
...

### Anything else we should know?

AMD Radeon Pro 22.Q3

**Comment by energizerfellow** [comment]
While HEVC was a new-for-Polaris encoder feature (your Radeon RX 580 is Polaris), it only supported 8-bit color depth in hardware. AMD's HEVC encoder gained 10-bit deep color for VCN2 which first appeared on 4000-series Ryzen APUs and RX 5000-series discrete GPUs.

**Comment by RytoEX** [comment]
Closing per above comment. The RX 580 does not support this configuration

**Comment by FireCulex** [comment]
Thanks. I suspected it might not be supported, difficult to find info.  "does not support 10bit depth H.265/HEVC encoding" error msg would be more intuitive.
