### ISSUE TITLE
VLC Media Source Lag

### ISSUE THREAD

**Issue by Chromagram** [obsproject/obs-studio#7552]
### Operating System Info

macOS 12

### OBS Studio Version

28.0.3

### OBS Studio Log URL

https://obsproject.com/logs/Ol1XxkvDPm8Qo3eE

### Expected Behavior

When VLC plays through a set list of files, the on screen controls should respond instantly, like a normal file playback should.

### Current Behavior

Currently, pressing any of the buttons like skip, pause, play, stop, etc. completes the action, but not before a minimum of at least 3 seconds of delay, usually longer. This causes plugins like Tuna that display song metadata to change its displayed data instantly as expected, but the music doesn’t actually catch up until many seconds later.

### Steps to Reproduce

1. Add a new VLC media source.
2. Add either a group of songs or a directory into the playlist.
3. Start the playback, and turn on Audio Monitoring to hear the upcoming issue.
4. Maybe wait about 15 seconds, then start trying to control the playback in any way. It will delay.

Opt. If you can, try running this with the Tuna extension as well to see the visual results too. If not, the delay can still be heard without installing Tuna.

### Anything else we should know?

I have been trying to fix this for multiple years, updating OBS and VLC as I go, but the issue persists for some reason. It makes a stream playlist practically useless.

I was hoping with the new macOS Capture, I could just load up a separate player like VLC or IINA and let that play the audio, while I captured the metadata from the player’s window. However, with the restriction of macOS capture still being unable to see anything that isn’t directly under it in windowed mode, it’s also not really an option for me.

I’d love to know if a fix for the VLC source is considerable, or if not, what alternative I can use to have a simple running playlist of music for my stream with some actively running metadata to display. This is dead simple on Windows but an absolute nightmare on Mac.

**Comment by PatTheMav** [comment]
Issue is confirmed, though it only seems to affect the audio monitoring - I did a recording of my VLC source and skipped around the file and every skip was correctly recorded without any delays.

The audio monitoring however buffered over 10 seconds of audio, leading to delayed reaction to skips, stopping playback, and other interactions.

I have no idea how to fix this right now, but it would probably require clearing the circle buffer when such actions are taken by users.

**Comment by usuallyno** [comment]
same problem here with mac

**Comment by PatTheMav** [comment]
Thank you for your comment, but at this point we are not in need of further confirmations but bug fixes. 😅

**Comment by Martiszz** [comment]
Same problem here with the mac

**Comment by PigDan20** [comment]
Has this been fixed yet? Audio is very unreliable.

**Comment by usakhelo** [comment]
PR is ready, just needs to be merged at some point.

**Comment by PigDan20** [comment]
> PR is ready, just needs to be merged at some point.

I hope to see an update soon! Thanks

**Comment by derrod** [comment]
Shoudl be fixed by #8147
