### ISSUE TITLE
Crash when attempting to stream

### ISSUE THREAD

**Issue by H46K3RL0L** [obsproject/obs-studio#7559]
### Operating System Info

Other

### Other OS

Raspbian (Debian modification for raspberry pi)

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.2.0

### OBS Studio Log URL

https://obsproject.com/logs/eWc3fh_fCZ5IBEeY

### Expected Behavior

I was expecting my stream to just start.

### Current Behavior

It immediately crashed.

### Steps to Reproduce

1. Install obs on Raspbian through pi-apps
2. Run it
3. Do the walkthrough while changing nothing
4. Start bitrate test stream
5. Bitrate test stream crashes obs as it is a stream
6. Try to start stream
7. Stream crashes
...

### Anything else we should know?

I don’t know how to access the log files except for the same ones that link goes to.

**Comment by kkartaltepe** [comment]
We dont support arm platforms for linux, feel free to send a PR if you find out something is broken.
