### ISSUE TITLE
Double click on `Start recording` starts and stops recording.

### ISSUE THREAD

**Issue by jtagcat** [obsproject/obs-studio#7564]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.3

### OBS Studio Log URL

-

### Expected Behavior

Recording is started. There is a period (500ms—1s), where any clicks are discarded, or until recording is actually started.

### Current Behavior

Recording is started, and stopped right away.	

### Steps to Reproduce

1a. Have a trackpad, that sometimes bounces on too little or too much force when clicking.
1b. Double click (everything) because user is used to it.

**Comment by notr1ch** [comment]
This is by design. You can turn on a confirmation dialog in settings if you accidentally click stop stream.
