### ISSUE TITLE
YouTube access error 'The request cannot be completed because you have exceeded your quote'

### ISSUE THREAD

**Issue by pixelwatt** [obsproject/obs-studio#7567]
### Operating System Info

macOS 12

### OBS Studio Version

28.0.3

### OBS Studio Log URL

https://obsproject.com/logs/t7OqqSkON_349Ugw

### Expected Behavior

I expected to hit "Manage Broadcast", select my precreated YouTube broadcast, and go live.

### Current Behavior

When I select "Manage Broadcast", I receive the following error: YouTube access error 'The request cannot be completed because you have exceeded your [quota](https://github.com/youtube/v3/getting-started#quota).'.

### Steps to Reproduce

1. Open OBS
2. Press "Manage Broadcast"

**Comment by RytoEX** [comment]
We are looking into this. Unfortunately, there is nothing we can do to address this at the moment. In the mean time, you should still be able to stream without YouTube integration by disconnecting your account and using a stream key.

**Comment by yanickrochon** [comment]
I prepared a stream for tomorrow and I got the same problem. Tried reconnecting, but no change. I've tried searching for this issue but only found [this](https://www.googlecloudcommunity.com/gc/Developer-Tools/Youtube-Quota-Exceed-Error/m-p/396907) describing some admin page. 

I do not recall having set this page; is this how OBS access our content, through a global Google API library?

**Comment by yanickrochon** [comment]
Maybe this can help?
https://youtu.be/0tLi7k9feZc

**Comment by RytoEX** [comment]
We are already aware of the issue and are working to resolve it. Please be patient while we work on resolving this issue. Thank you for your understanding.

**Comment by yanickrochon** [comment]
> We are already aware of the issue and are working to resolve it. Please be patient while we work on resolving this issue. Thank you for your understanding.

Just trying to help while understanding the issue myself :)

**Comment by pixelwatt** [comment]
Thanks guys! Just got caught off guard by the issue and wanted to make sure if was reported. I'll just fall back to stream keys for time being as needed.

**Comment by derrod** [comment]
The quota usage should have reset after midnight PST and everything should work again now. We will hopefully get a quota increase soon so this issue won't happen again.
