### ISSUE TITLE
OBS Mac Memory Leak - with BlackMagic Decklink Video capture device

### ISSUE THREAD

**Issue by thomaslfessler** [obsproject/obs-studio#7568]
### Operating System Info

macOS 12

### OBS Studio Version

Other

### OBS Studio Version (Other)

28.0.1

### OBS Studio Log URL

https://obsproject.com/logs/j3Qtl2Ge2HdYAo_M

### Expected Behavior

Memory usage should stay consistent and not increase over time.

### Current Behavior

Memory usage slowly climbs when displaying the BlackMagic video capture device.   

### Steps to Reproduce

Startup obs
in a scene, add a blackmagic video capture device that's displaying content at 1080p/60 with 5.1 audio.
Watch the stats window.  Over time memory usage increases.

**Comment by PatTheMav** [comment]
The provided log suggests a massive scene setup with lots of filters and plugins loaded - could you please try updating to OBS 28.0.3 and also switch to an empty scene collection and just add the capture device to observe memory usage.

Most appreciated would be if you could check out the repository yourself, compile and run OBS with Xcode and attach Instruments to have it actually detect the memory leaks and tell you which calls are responsible for them (if there are any).

**Comment by gxalpha** [comment]
Closing as there has not been a response in over 3 months.
