### ISSUE TITLE
OBS Has white decorators by defoult

### ISSUE THREAD

**Issue by adambelis** [obsproject/obs-studio#7571]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.3

### OBS Studio Log URL

https://obsproject.com/logs/MPxkSbgk2lfHnArE

### Expected Behavior
This is a screenshot from https://obsproject.com/ .  So I expect that is developers intended to look for the app

to have black decorators (black bg, white text, withe icons) to match look of app
![image](https://user-images.githubusercontent.com/50795097/194753806-13939848-d2e0-4711-ae43-1c3962cd8a32.png)

### Current Behavior

white decorators with black text and black icons   that do not match look of app
![image](https://user-images.githubusercontent.com/50795097/194753824-c5120df4-54ae-4c70-b93a-c8adb15963fd.png)

### Steps to Reproduce

Instal obs on windows
run  OBS
observe withe decotrators (top bar)

### Anything else we should know?
This is not a regression.This was problem for years.
not sure if I should categorize this as a UI bug or a feature request . It is just not aesthetically pleasing look 
maybe an answer how to do it would be here ?
https://www.qt.io/blog/custom-window-decorations

**Comment by PatTheMav** [comment]
Please complete the issue template with written text instead of just dumping nondescript screenshots into it, also don't just type "a" instead of providing a OBS Studio Log URL.

**Comment by adambelis** [comment]
Templet is confusing because it does not allow uploading files so I was not sure how to deal with that so I ignored it.
i upaded log file here I hope that is what  does that expect.
also added  more text  to the issue let me know if this is more clear now

**Comment by PatTheMav** [comment]
The template _explicitly_ tells you how to generate the log URL:

> Please provide the obsproject.com URL (from Help menu > Log Files > Upload Current/Previous Log File) to the OBS log file where this issue occurred.

Your post also does not clarify if this is a regression: Did OBS use black decorators before and it stopped doing so now? Is the first screenshot an edit? That's the kind of information we'd need in writing.

**Comment by adambelis** [comment]
i saw and read that instructions and find files but I am still not sure what to do with them. It talk albou log URL and I still don't know what that is I see just  txt file are you expecting me to  upload it gitlab ? if so  add a file picker.  or am I spos tu uplodn time to random place ? am I missing something is there real URL somewhere ?

**Comment by adambelis** [comment]
I added more info in to original issue let me know if there is more  to add

**Comment by PatTheMav** [comment]
When you do what it tells you (select Log Files > Upload Current Log File from the Help Menu), you'll be presented with this dialog, which shows you a URL - that's the one to copy and paste:

![2022_10_09-Upload-Log](https://user-images.githubusercontent.com/9436503/194756376-e71df60e-38f9-4923-9958-00ff6bb54a4a.jpg)

**Comment by adambelis** [comment]
hmm, kind a miss that, thanks fixed that . i guess you can take it as user feedback that this is not idiot proof. maybe it could be reordered to be as a first  item in menu ?

 or you can just write it off as me being dumb :D and my  dyslexia  acting up again

**Comment by PatTheMav** [comment]
No bother, I can confirm that even with Windows 11 set to dark mode the main OBS window still has a light-themed title bar. As the first picture is taken from the screenshot on our website I have to investigate how that screenshot came to be.

**Comment by adambelis** [comment]
its not realy about a screensho imho it whouls follow the look of app and  be dark

**Comment by tytan652** [comment]
The one who made the screenshots used Windows 11 personalisation features to make the title bar colour match Yami.

**Comment by adambelis** [comment]
is that good reason not tom implement this?

**Comment by PatTheMav** [comment]
> is that good reason not tom implement this?

GitHub issues are meant for issue reports but not feature requests - if you wish for OBS to support "dark mode" (and ignore the Windows personalisation settings) you can request that feature at https://ideas.obsproject.com/.

**Comment by adambelis** [comment]
ah i see thanks

**Comment by adambelis** [comment]
this has been fixed in 29.1.1
