### ISSUE TITLE
VST 2 unsupported in native Apple Silicon, but still listed as a filter option in Apple Silicon builds

### ISSUE THREAD

**Issue by eadnams22** [obsproject/obs-studio#7575]
### Operating System Info

macOS 12

### OBS Studio Version

28.0.3

### OBS Studio Log URL

https://obsproject.com/logs/SNV8XV-7qy_e-E_7

### Expected Behavior

VST2 plugins should function
OR 
VST 2 should not be listed as an option.

### Current Behavior

A user can ad all the VST 2.x plugins they want under filters, but none of them do anything.

### Steps to Reproduce

1. Add Audio Source
2. Add Filter
3.  Select a VST2.x plugin
4. Apply
5. There is no effect
6.
...

### Anything else we should know?

I know VST2 is EoL, just having it listed when it wont work on apple silicon is deceptive.

**Comment by PatTheMav** [comment]
I would ask you kindly to reconsider your choice of words. You probably did not mean it that way, but "deceptive" usually implies malicious intent and the people working on and maintaining OBS in their spare time do not deserve such insinuations.

There is no architectural reason for VST2 plugins not to support arm64, in fact Blue Cat's VSTs run natively on Apple M1 machines (and within OBS) without issue - thus there was no reason for us to remove the VST filter for them.

While it might be true that some VST authors might not bother updating their VSTs to include an arm64 slice (opting to upgrade to VST3), it is possible and some actually did.

**Comment by eadnams22** [comment]
> I would ask you kindly to reconsider your choice of words. You probably did not mean it that way, but "deceptive" usually implies malicious intent and the people working on and maintaining OBS in their spare time do not deserve such insinuations.
> 
> There is no architectural reason for VST2 plugins not to support arm64, in fact Blue Cat's VSTs run natively on Apple M1 machines (and within OBS) without issue - thus there was no reason for us to remove the VST filter for them.
> 
> While it might be true that some VST authors might not bother updating their VSTs to include an arm64 slice (opting to upgrade to VST3), it is possible and some actually did.

Fair, didn't mean it as any jab, edited.

This is the opposite of what I was told by several VST developers, who claimed it was impossible to create VST2 plugins for native apple silicon, further they cited Steinberg having no interest in updating the standard to make them work, and to move on to VST3 (Which is currently unsupported in OBS, unfortunately).

**Comment by PatTheMav** [comment]
The comments regarding Steinberg's attitude are correct - they want people to move to VST3, but from what I heard developers are anything but happy about VST3.

I dunno _how_ the Blue Cat folks made it work, but they did. Alas I haven't worked with the VST2-SDK to know what specifically might be the issue, but we opted to at least allow loading the ones that do exist.

**Comment by eadnams22** [comment]
> The comments regarding Steinberg's attitude are correct - they want people to move to VST3, but from what I heard developers are anything but happy about VST3.
> 
> I dunno _how_ the Blue Cat folks made it work, but they did. Alas I haven't worked with the VST2-SDK to know what specifically might be the issue, but we opted to at least allow loading the ones that do exist.

Makes sense! Thanks!

Heck, I'd be thrilled with AU support! Either way, I've been using Hosting AU to do my processing outside OBS, and then feeding it into OBS from there, which is an okay hack for now. :)

**Comment by eadnams22** [comment]
Also, I submitted cash towards the VST3 bounty! Hoping it helps!

**Comment by attaboyBrad** [comment]
> Also, I submitted cash towards the VST3 bounty! Hoping it helps!

How/where does one do this? I'd like to chip in.
