### ISSUE TITLE
OBS crushed everytime I exit

### ISSUE THREAD

**Issue by nmMmnmMmn** [obsproject/obs-studio#7590]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.3

### OBS Studio Log URL

https://obsproject.com/logs/OP4oWY1ZM2fwdE3M

### OBS Studio Crash Log URL

https://obsproject.com/logs/IRlDMfIcLr_wGLdn

### Expected Behavior

no crush, just exit.

### Current Behavior

crush shows up everytime after i click "exit" or close the window (after the window disappeared).

### Steps to Reproduce

1. run obs
2. click exit or just close the window
3. 
![image](https://user-images.githubusercontent.com/21982381/195138037-d1cb272f-f03c-4d07-bdd3-56f48b477cec.png)

### Anything else we should know?

this happened after i upgraded from 27.2.4 to 28.0.3. i've upgraded all plugins to latest version, no plugin compatibility warning shows up.

**Comment by Fenrirthviti** [comment]
Please test without any third party plugins installed to see if this still occurs. This is almost certainly an issue with one of the many plugins you are using, but will be hard to identify what. You will need to just test one-by-one until the triggering cause is uncovered. If this occurs without any plugins installed at all, please grab a new crash log and normal log, and we can take a closer look.

**Comment by nmMmnmMmn** [comment]
After some test... This is caused by [source dock plugin](https://github.com/exeldro/obs-source-dock). Not OBS's problem.
