### ISSUE TITLE
Enhancement: option to Hide Transition widgets in Studio Mode

### ISSUE THREAD

**Issue by kamalmostafa** [obsproject/obs-studio#7592]
### Operating System Info

Other

### Other OS

all

### OBS Studio Version

28.0.3

### OBS Studio Log URL

n/a

### Expected Behavior

New Settings option: General -> Studio Mode -> **Hide Transition widgets**

When checked, the Transition button and associated widgets are hidden, allowing the side-by-side Preview and Program video windows to display as large as possible.

Note: When the Transition widgets are hidden, transitions can still be invoked by the "Transition to scene when double-clicked" method, websocket, or scripting methods.

![obs-HideTransitionWidgets](https://user-images.githubusercontent.com/1181534/195223128-56f96dd8-12b7-4a96-beaa-4807dbf18a36.png)

### Current Behavior

By default, the placement of the Transition widgets consumes quite a bit of screen real estate.  For some workflows, the Transition widgets might be unnecessary, and the screen space better used for bigger video windows.

The default layout (without enabling the new feature) looks like this for comparison:

![obs-default](https://user-images.githubusercontent.com/1181534/195223667-be1b3ebf-4f4c-4910-830e-248b7b203911.png)

### Steps to Reproduce

1.
2.
3.
...

**Comment by RytoEX** [comment]
We do not track feature requests on GitHub Issues. Please submit feature requests on [our Ideas site](https://ideas.obsproject.com/) after confirming that it has not already been submitted there. Thank you for your understanding.
