### ISSUE TITLE
MacOS Hardware (Apple, H.264) encoding doesn't work

### ISSUE THREAD

**Issue by jadenquinn** [obsproject/obs-studio#7596]
### Operating System Info

macOS 12

### OBS Studio Version

28.0.3

### OBS Studio Log URL

https://obsproject.com/logs/yODaWeQfo_3mX81v

### Expected Behavior

I expected recording to start.

### Current Behavior

I press record, and I get an error pop-up.

### Steps to Reproduce

1. Switch to Hardware encoding on M1, M1 Pro, M1 WHATEVER, or M2 machine.
2. Press record.
3. Fix the damn program idk

### Anything else we should know?

I strongly detest Windows, so I'm hoping this gets solved quickly.

**Comment by gxalpha** [comment]
Could you try a more reasonable, common resolution like 1920*1080?

**Comment by frankbasti** [comment]
I too have noticed huge performance losses when using obs 28 on intel mac mini.  When streaming the dropped frames are 3-5% .  Worse when media sources include video or window capute (google chrome playing a video)   And far worse (10%+) drop frame when using the apple hardware encoder. 

It seems like the performance of using a hardware encoder no longer applies in obs 28 for both intel / arm macs

**Comment by gxalpha** [comment]
Closing as there hasn't been an answer from OP in a week. We believe that the resolution you're using isn't compatible with the Apple VT encoder.
Additionally, please be a bit more mindful with your wording. Telling the maintainers to "Fix the damn program idk" doesn't make a good impression.

@frankbasti
Dropped frames as reported by OBS (as "Dropped Frames") are generally unrelated to the encoder, and only depend on your internet connection. Additionally, the VT encoder isn't (and has never been) suitable for streaming (unless you're on an Apple Silicon Mac with macOS 13 and are using the "CBR" rate control method) as the bitrate can fluctuate wildly.
If there are other performance regressions with the VT encoder while recording (like "Encoder Overload"), please open a new issue with reproduction steps on both 27.2 and 28.0.
