### ISSUE TITLE
Not getting cc stream in custom rtmp stream

### ISSUE THREAD

**Issue by NimitzDEV** [obsproject/obs-studio#7597]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.3

### OBS Studio Log URL

https://obsproject.com/logs/d7fcyV7L1xAowNp5

### Expected Behavior

FFmpeg should report cc stream in terminal

How can I get cc push into the video stream? Is it an RTMP protocol issue?

### Current Behavior

FFmpeg only reports video and audio streamsFFmpegreports

### Steps to Reproduce

1. Enable WebSocket Server
2. Connect to WebSocket Server
3. Start a FFmpeg RTMP server using the command `ffmpeg -listen 1 -timeout 10000 -f flv -i rtmp://127.0.0.1:5000/mystream -c copy record.mkv`
4. Inside OBS settings -> Stream -> Custom, setServer as `rtmp://127.0.0.1:5000/mystream` and Stream Key as `mystream`
5. Click Start Streaming
6. Send the following message to OBS WebSocket, and responded with code 100 which means operation succeded
```
{
    "op": 6,
    "d": {
      "requestId": "stream",
      "requestType": "SendStreamCaption",
      "requestData": {
        "captionText": "123"
      }
    }
  }
```
7. See FFmpeg's output, only showing audio and video streams
![image](https://user-images.githubusercontent.com/7098462/195388604-884930f8-abce-4287-8e53-47671371f2e0.png)

**Comment by ratwithacompiler** [comment]
The captions should be there but I don't think ffmpeg shows CEA captions OBS uses in the output separately there unlike other subtitle formats. You can check with something like `ccextractor` (if you save as `.ts` or `.mp4` at least) but worked for me with your command and record.ts just now when testing. But very few tools support CEA embedded captions well unfortunately.

**Comment by derrod** [comment]
As @ratwithacompiler said, CEA embedded captions aren't well supported, and ffmpeg won't show them by default, but it can extract them in theory: https://trac.ffmpeg.org/wiki/HowToExtractAndRemoveClosedCaptions
