### ISSUE TITLE
OBS fails to launch due to missing library libQt6Core.so.6

### ISSUE THREAD

**Issue by trevormac789** [obsproject/obs-studio#7618]
### Operating System Info

Other

### Other OS

Centos 7

### OBS Studio Version

28.0.3

### OBS Studio Log URL

https://obsproject.com/logs/IgMitv8abCOYm70k

### Expected Behavior

I expected OBS to launch the GUI and start

### Current Behavior

It doesn't launch and then I get an error in /var/log/messages obs: error while loading shared libraries: libQt6Core.so.6: cannot open shared object file: No such file or directory

If I do a locate of that file it's only under KDE which I assume is KDE desktop.

I find them here.
/var/lib/flatpak/runtime/org.kde.Platform/x86_64/6.3/da5db79df3afb70fe080b06f44b84ef1db3400ea8eb8cba77c22ab07c9065f64/files/lib/x86_64-linux-gnu/libQt6Core.so.6
/var/lib/flatpak/runtime/org.kde.Platform/x86_64/6.3/da5db79df3afb70fe080b06f44b84ef1db3400ea8eb8cba77c22ab07c9065f64/files/lib/x86_64-linux-gnu/libQt6Core.so.6.3.2

We use Gnome 3.28 desktop environment and I assume that that library should exists in org.gnome.Platform? 

In any case I am able to get it working by rolling back to the March commit version. 

### Steps to Reproduce

1.Updated to latest version of OBS via puppet a week or two ago
2.Attempt to launch OBS
3.OBS shows spinning icon and then fails to launch. 
...

### Anything else we should know?

Hopefully that's enough info. For now we're going to use an older version from flathub and hopefully this'll be addressed soon.

Thank you.

**Comment by Fenrirthviti** [comment]
We do not maintain the Centos package, please report it to the package maintainer.

**Comment by slycordinator** [comment]
If you're in Docker or WSL, you might need to run:
sudo strip --remove-section='.note.ABI-tag' /path/to/libQt6Core.so.6
