### ISSUE TITLE
Many Plugins don't show up for Steam-based installs of OBS

### ISSUE THREAD

**Issue by attaboyBrad** [obsproject/obs-studio#7619]
### Operating System Info

macOS 12

### OBS Studio Version

28.0.3

### OBS Studio Version (Other)

Also occurs on 28.1 Beta (from Steam)

### OBS Studio Log URL

https://obsproject.com/logs/EpxFWO15P4naqu3O

### Expected Behavior

I expected to be able to use the 'Audio Monitor' and 'Move Transition' plugins from Exeldro, among several others.

### Current Behavior

The Plugins don't appear as options under "Scene Transitions" or "Audio Filters" or "Docks" where they usually do (and do when OBS is installed normally via dmg in '/Applications'.

### Steps to Reproduce

1. Install OBS via  Steam
2. Run installers for 'Audio Monitor' or 'Move Transition' plugin by Exeldro (several others fail in similar fashion)
3. Attempt to add a 'Move Transition' to Scene Transitions or to add 'Audio Monitor' filter to an audio source.
...

### Anything else we should know?

Aside from a regular install, I also tried copy/pasting the plugin files from '~/Library/Application Support/obs-studio/plugins' to '/Library/Application Support/Steam/steamapps/common/OBS Studio/arm64/OBS.app/Contents/PlugIns'.  That seemed to work for StreamFX and Color Monitor, but not for several other plugins beyond the ones referenced above: media-controls, source-copy, source-dock, etc.

**Comment by Fenrirthviti** [comment]
You cannot load x86 plugins on an m1 build, or m1 plugins on an x86 build.

From your logs:
(mach-o file, but is an incompatible architecture (have (arm64), need (x86_64)))

**Comment by attaboyBrad** [comment]
Thanks--I saw both x86 and Arm64 versions in the folder but had assumed Steam was running the M1 build since I have a Mac Studio. 

That difference could explain the VST issue I'm having as well...
