### ISSUE TITLE
OBS doesn't read en-US locale, and keys in the locale file are not correct.

### ISSUE THREAD

**Issue by pkej** [obsproject/obs-studio#7630]
### Operating System Info

macOS 12

### OBS Studio Version

28.0.3

### OBS Studio Log URL

https://gist.github.com/pkej/5d4e96bd92ad272d55ab879771ef9fc1

### Expected Behavior

When using English American I expect OBS to read the en-US.ini file in OBS.app/Resources/locale.

### Current Behavior

I wanted to change the names of audio devices as [per this information](https://obsproject.com/forum/threads/rename-audio-sources-hide-mixer-sources.56178/).

In the file the relevant section was originally like this:

...# audio device names
Basic.DesktopDevice1="Desktop Audio"
Basic.DesktopDevice2="Desktop Audio 2"
Basic.AuxDevice1="Mic/Aux"
Basic.AuxDevice2="Mic/Aux 2"
Basic.AuxDevice3="Mic/Aux 3"
Basic.AuxDevice4="Mic/Aux 4"

Changing them to:

...# audio device names
Basic.DesktopDevice1="Full mix"
Basic.DesktopDevice2="Music (Clean)"
Basic.AuxDevice1="Game (Clean)"
Basic.AuxDevice2="Guests (mixdown)"
Basic.AuxDevice3="Host (Clean)"
Basic.AuxDevice4="Notes (Clean)"

Yielded nothing either.

I tried to append the relevant strings to "en-GB.ini" with no result either.

I almost gave up, but I took a look into the Norwegian locale, and discovered that the correct syntax for the keys in this section is:

Basic.Settings.Audio.Devices="Globale lyd enheter"
Basic.Settings.Audio.DesktopDevice="Skrivebordslyd"
Basic.Settings.Audio.DesktopDevice2="Skrivebordslyd 2"
Basic.Settings.Audio.AuxDevice="Mikrofon/Aux"
Basic.Settings.Audio.AuxDevice2="Mikrofon/Aux"
Basic.Settings.Audio.AuxDevice3="Mikrofon/Aux"
Basic.Settings.Audio.AuxDevice4="Mikrofon/Aux"

After adding the following to the "en-GB.ini" I finally got OBS to change the UI in Settings:

Basic.Settings.Audio.DesktopDevice="Full mix"
Basic.Settings.Audio.DesktopDevice2="Music (Clean)"
Basic.Settings.Audio.AuxDevice="Game (Clean)"
Basic.Settings.Audio.AuxDevice2="Guests (mixdown)"
Basic.Settings.Audio.AuxDevice3="Host (Clean)"
Basic.Settings.Audio.AuxDevice4="Notes (Clean)"

Therefore there are two errors when it comes to the ini-file and one when switching locales:

1. the keys in the "en-US.ini" are probably all suspect.
2. the "en-US.ini" isn't read upon startup, so changing the device names for the settings panel doesn't work anyway.
3. Changing locales and answering "Yes" to the "OBS Studio needs to be restarted. Do you want to restart now?" prompt that appears will restart OBS faster than the shutdown of the previous instance and yielding a prompt with with: "OBS is already running! Unless you meant to do this, please shut down any existing instances of OBS before trying to run a new instance. If you have OBS set to minimise to the system tray, please check to see if it's still running there."

### Steps to Reproduce

1. Open the "OBS.app/Resources/locale/en-US.ini" file in a text editor
2. From here on, any locale file name, like "en-US.ini" will be from the directory "OBS.app/Resources/locale"
3. Note how the keys and values of the audio device names are like this:

...# audio device names
Basic.DesktopDevice1="Desktop Audio"
Basic.DesktopDevice2="Desktop Audio 2"
Basic.AuxDevice1="Mic/Aux"
Basic.AuxDevice2="Mic/Aux 2"
Basic.AuxDevice3="Mic/Aux 3"
Basic.AuxDevice4="Mic/Aux 4"

4. Change the relevant locale in "en-US.ini" to the following:

...# audio device names
Basic.Settings.Audio.DesktopDevice="Full mix"
Basic.Settings.Audio.DesktopDevice2="Music (Clean)"
Basic.Settings.Audio.AuxDevice="Game (Clean)"
Basic.Settings.Audio.AuxDevice2="Guests (mixdown)"
Basic.Settings.Audio.AuxDevice3="Host (Clean)"
Basic.Settings.Audio.AuxDevice4="Notes (Clean)"

5. Change locale inside Settings->General to "English"
6. Save changes to Settings
7. Accept restart prompt
8. NOTE that on and Apple Silicon M1 Pro the new instance will start fast enough to trigger the "OBS already running, warning" while closing down
9. Go into Settings->Audio and under the group "Global Audio Devices" note the names are not changed to the names in the ini file.
10. Append the following to the "en-GB.ini":

...# audio device names
Basic.Settings.Audio.DesktopDevice="Full mix"
Basic.Settings.Audio.DesktopDevice2="Music (Clean)"
Basic.Settings.Audio.AuxDevice="Game (Clean)"
Basic.Settings.Audio.AuxDevice2="Guests (mixdown)"
Basic.Settings.Audio.AuxDevice3="Host (Clean)"
Basic.Settings.Audio.AuxDevice4="Notes (Clean)"

11. Change locale inside Settings->General to "English (UK)"
12. Save changes to Settings
13. Accept restart prompt
14. Go into Settings->Audio and under the group "Global Audio Devices" note the names are changed to the names in the ini file.

...

### Anything else we should know?

Nope

**Comment by WizardCM** [comment]
As a side note, you can just right click audio sources in the Audio Mixer and select "Rename" if you want to change source names at runtime.

**Comment by derrod** [comment]
Both of those keys exist in the `en-US` file, one is used for the name of the actual source that is created, the other for the label of the dropdown in settings.

**Comment by pkej** [comment]
My mistake, thank you for such a quick reply.
