### ISSUE TITLE
NVIDIA Broadcast SDK with HAGS GPU Usage Bug

### ISSUE THREAD

**Issue by Spartanz1080** [obsproject/obs-studio#7639]
### Operating System Info

Windows 11

### OBS Studio Version

28.1.0-rc1

### OBS Studio Log URL

https://obsproject.com/logs/fYO6trHRXIL0qD3Q

### Expected Behavior

GPU usage with NVidia broadcast effects enabled to be low

### Current Behavior

With HAGS enabled GPU usage and an NVIDIA broadcast SDK effect enabled GPU usage jumps all over the place with just OBS open launching a game causing FPS to become unstable making it unplayable. Turning off HAGS makes GPU usage 5 to 10% with NVIDIA SDK effect and it is fine again.

### Steps to Reproduce

1. HAGS on
2. NVIDIA Broadcast SDK Effect Enabled
3. Open OBS
4. Launch Game
5. Look at GPU Usage

### Anything else we should know?

4090
Windows 11
12700K

Regarding VRR instability it’s just with the gpu usage fluctuating fps changes causing VRR refresh to fluctuate which leads to perceived microstutter

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by pkviet** [comment]
as i said in discord, i don't repro your issue with my rtx 4090. The GPU usage reported is not a consistent metrics because the gpu clock varies, so you have to check at constant clock. In my pc, i see obs + nvidia filter at 30 % gpu usage (hags on or off) but gpu clock is at 800 MHz

**Comment by pkviet** [comment]
more precisely, with hags off i have 10% gpu load but the frequency is tripled. So the real gpu load is about the same hags on or off

**Comment by Spartanz1080** [comment]
I’m not sure what’s wrong with my system then had the same issue with my 3090 just gonna stream with HAGS off

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Spartanz1080** [comment]
Regarding VRR instability it’s just with the gpu usage fluctuating fps changes causing VRR refresh to fluctuate which leads to perceived microtutter

**Comment by Spartanz1080** [comment]
So I have found a to deal with my issue. I downloaded the NVIDIA broadcast application and tried using that with OBS like it was in previous versions. The gpu usage is fine now and there is no issue with VRR in games anymore. The only way I can use the SDK is turn HAGS off but then I lose DLSS3. Is there some place I can go to submit feedback to NVIDIA on the SDK so maybe they can update it?

**Comment by pkviet** [comment]
Ok i wonder if it might be fixed by my pr #7466 ;
Retrieve the artefact here:
https://github.com/obsproject/obs-studio/actions/runs/3316594645
Set the mask refresh slider to 2 instead of 1. 
The nvidia broadcast app refreshes at 30 fps while in obs the default is 60 fps.
This can cause stuttering under high gpu load.
The new slider will decrease for you the mask refresh frequency to 30 fps when set to 2.

**Comment by Spartanz1080** [comment]
This is great sorry though I am bit on how to install it and use it and find the setting.

**Comment by pkviet** [comment]
Download the zip in any folder. It won't delete your current obs install.
Just run it from the unzipped folder in bin/64bit . You'll find obs.exe there.
If you create a shortcut for the exe with --portable it won't use your obs current settings but will start from clean slate.
It might be better in order start from a clean position.

**Comment by Spartanz1080** [comment]
So if i download that the flatpak and install it the mask setting will be 2 and I can uninstall as needed if I want use 2 also I thought there was a slider setting I had to find

**Comment by pkviet** [comment]
No! Don't download the flatpak , it's a linux binary. Download the windows x64 zip.
When you add the nvidia background removal, you 'll see 1 new setting.
Set the mask refresh to 2.

**Comment by Spartanz1080** [comment]
Ok will it also be In microphone noise removal settings I’ll try it after work and report back. Thank you.

**Comment by pkviet** [comment]
No, only for background removal which is the more demanding

**Comment by Spartanz1080** [comment]
I haven’t tested I’m at work I’m just wondering assuming it works will this feature make it into a release of OBS

**Comment by Spartanz1080** [comment]
I made this same comment in discord but I’m just posting it here too. 

pkv you are god it works. For some reason even mask frequency 1 works. It goes all the way up to 4 so I’d like to know what that does. When I go back to normal OBS it does not work though. Also I’m not sure if something changed with microphone noise removal but it didn’t seem to be working as well as in normal OBS. Maybe it was my mic settings but it’s not a big deal it was just picking up some more noise. Anyway I’m extremely excited to get this into a future release. Thank you.

**Comment by pkviet** [comment]
> I made this same comment in discord but I’m just posting it here too. 
> 
> pkv you are god it works. For some reason even mask frequency 1 works. It goes all the way up to 4 so I’d like to know what that does. When I go back to normal OBS it does not work though. Also I’m not sure if something changed with microphone noise removal but it didn’t seem to be working as well as in normal OBS. Maybe it was my mic settings but it’s not a big deal it was just picking up some more noise. Anyway I’m extremely excited to get this into a future release. Thank you.

Mmh. If it works with mask refresh = 1 , it's not my code which fixes your build. If you ran with --portable , i suspect it's the clean setup.

**Comment by Spartanz1080** [comment]
I replied on discord and did what you asked

**Comment by Spartanz1080** [comment]
I have a question on if changing mask settings affects the effectiveness of the SDK effects.

**Comment by Spartanz1080** [comment]
I have one last question if I update my normal OBS this will not update my zip version with the latest fixes and I have to wait until this feature is included in a beta before I can get updated fixes past 28.1 RC1 in the zip correct?

**Comment by pkviet** [comment]
> I have one last question if I update my normal OBS this will not update my zip version with the latest fixes and I have to wait until this feature is included in a beta before I can get updated fixes past 28.1 RC1 in the zip correct? 

No.
The zip is separate. If you get update messages when running the zip, don't update or it'll remove the binaries.
You'll have to wait until end of November for 29 beta where it'll be in.

**Comment by pkviet** [comment]
Fixed by https://github.com/obsproject/obs-studio/pull/7466
