### ISSUE TITLE
Virtual Camera does not work with Zoom on Mac for v28.0.3

### ISSUE THREAD

**Issue by grahamegrieve** [obsproject/obs-studio#7641]
### Operating System Info

macOS 12

### OBS Studio Version

28.0.3

### OBS Studio Log URL

https://obsproject.com/logs/o6-409madPhZYxoH

### Expected Behavior

The virtual Camera should work with zoom, and does with OBS 27.2.4 (and world again after I downgraded)

### Current Behavior

Zoom is set to use the virtual camera, but it just saw that 'virtual camera not started' image even after I started the virtual camera. I tried all the different settings on the new settings button next to the camera, but none of them made any difference - I just saw that 'not started' image. 

downgrading to 27.2.4 fixed the problem.

### Steps to Reproduce

1. upgraded to 28.03
2. started OBS
3. Started the virtual camera
4. 
...

### Anything else we should know?

![image](https://user-images.githubusercontent.com/5858581/197365909-0f5c79bb-f999-4b93-a01c-3657c099c6d0.png)

**Comment by attaboyBrad** [comment]
I had the same issue.  This is fixed in v28.1.

Here's the thread I opened for the same thing: https://github.com/obsproject/obs-studio/issues/7287
