### ISSUE TITLE
AMD AMF HEVC heavy regular artifacts

### ISSUE THREAD

**Issue by pannal** [obsproject/obs-studio#7642]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.3

### OBS Studio Log URL

https://obsproject.com/logs/EHU02ZG5KnuZ8Dcb

### Expected Behavior

Video would stream normally

### Current Behavior

Massive artifacts using AMF HEVC (settings don't matter), especially with frames that are partially still. Fully moving frames don't show this behaviour.

### Steps to Reproduce

1. Stream using AMD HW H.265 HEVC

### Anything else we should know?

GPU: 6800 XT, latest Preview driver (22.10.2)
Transport: SRT
![image](https://user-images.githubusercontent.com/1359593/197367847-be993ecb-f934-4936-b7e6-a0dcc2ad9dda.png)
![image](https://user-images.githubusercontent.com/1359593/197367850-eee1f86f-8f14-4606-bd26-3de563ae3a8e.png)

**Comment by lextra2** [comment]
Works fine for me, RX 5700 with driver 22.9.1

**Comment by gxalpha** [comment]
Preview drivers are not supported.
Please use release drivers.

**Comment by RytoEX** [comment]
> This issue needs to be reopened cause the 22.10.2 drivers are pretty much WQHL and are being pushed to the stable channel, they are not preview as stated by @gxalpha
> 
> There a reason AMD focused most of their fixes on 22.10.2, plus the drivers page confirms this as well, https://www.amd.com/en/support/kb/release-notes/rn-rad-win-22-10-2
> 
> Not to mention if you all working on keeping stability with AMD, you should be testing with preview drivers to be aware of incoming issues.

As noted above, 22.10.2 is marked an Optional, and therefore beta/preview, driver. Please report issues on beta drivers to AMD. We pass frames to AMD to encode, and it sends encoded frames back to OBS. OBS does not, itself, encode the frames.

That aside, as the OP mentions using SRT, this is unlikely to be anything with the encoder choice. Make sure you have set appropriate parameters for latency. In my experience, SRT is particularly sensitive to this kind of artifacting if the latency parameter is not set correctly. You should be set latency to 2.5x-4x your RTT/ping to the ingest. For example, 100 ms RTT/ping would need a latency of 250-400 ms. When specifying this value in OBS, multiply by 1000 (i.e., `latency=250000` or `latency=400000`).

**Comment by pannal** [comment]
Hmm I doubt the artifacting is due to using SRT. I use SRT with the same settings with x264 with huge bitrates and no adjustments to SRT, just fine.

This seems to be HEVC specific. I can test whether this happens with AMD HW HEVC and RTMP, though, to make sure.

**Comment by pannal** [comment]
> AMD always does that to make sure no major issues are being passed to the stable channel, but you can expect 22.10.2 to be pushed to the stable channel in a few days.

That'd be a shame as 22.10.2 still causes driver timeouts in light loads (Chrome).

**Comment by RytoEX** [comment]
> AMD always does that to make sure no major issues are being passed to the stable channel, but you can expect 22.10.2 to be pushed to the stable channel in a few days.
> 
> **AMD doesn't bother with WHQL tags on optional drivers ever.**

I beg to differ.
![image](https://user-images.githubusercontent.com/624931/198293849-0f6d8995-446a-4743-a2da-7d3d22a408be.png)

The drivers will be Recommended when they are _actually_ Recommended. Until then, please stop arguing about this here, as all it does is spam anyone subscribed with an argument about AMD driver status and not about the core parts of the described Issue itself.

@pannal 
Please test in 22.5.1 and/or a recording to rule out various factors (drivers, SRT issues). Having previously done testing with SRT, I still think this is latency related until shown otherwise. For example, see these old SRT tests of mine with x264:
![image](https://user-images.githubusercontent.com/624931/198294959-f5166ea0-194d-42dd-890e-5d1e9b524af2.png)
![image](https://user-images.githubusercontent.com/624931/198294817-962f74c9-c9d9-4a2c-9229-d7465d39eeb8.png)
![image](https://user-images.githubusercontent.com/624931/198295044-0daea58c-919a-41ec-a7bd-2ae4aa4bc3a4.png)

**Comment by pannal** [comment]
> @pannal
> Please test in 22.5.1 and/or a recording to rule out various factors (drivers, SRT issues). Having previously done testing with SRT, I still think this is latency related until shown otherwise. For example, see these old SRT tests of mine with x264:

I'll try a recording for sure. Again, with x264 (bitrate over 20000 for 1440p/120 for hours) I had no visible artifacts using the default SRT settings (no explicit latencies set).

**Comment by gxalpha** [comment]
Thanks for confirming in the edits that this is not an AMF issue.

There are many people subscribed to this thread and/or the entire repo, some of which I really don't want to get flooded with emails. As such, I'm going to lock this thread.
Please try the steps described at https://github.com/obsproject/obs-studio/issues/7642#issuecomment-1292225688, and visit the support sections on our [Discord server](https://discord.gg/obsproject) or [Forums](https://obsproject.com/forum) if you continue to have issues, as they are support issues and not bugs.

Thank you!
