### ISSUE TITLE
obs libcef.dll  qt

### ISSUE THREAD

**Issue by carlsummer** [obsproject/obs-studio#7646]
### Operating System Info

Windows 10

### OBS Studio Version

28.1.0-rc1

### OBS Studio Log URL

https://github.com/obsproject/obs-studio/releases/download/28.1.0-rc1/OBS-Studio-28.1-rc1-Full-x64.zip

### OBS Studio Crash Log URL

https://github.com/obsproject/obs-studio/releases/download/28.1.0-rc1/OBS-Studio-28.1-rc1-Full-x64.zip

### Expected Behavior

![image](https://user-images.githubusercontent.com/16281965/197402586-12400d48-7dab-4ea0-b25d-858448d6a5b3.png)

### Current Behavior

![image](https://user-images.githubusercontent.com/16281965/197402596-fd5adcff-16c0-42c1-84f1-2c0278cbe345.png)

### Steps to Reproduce

1. download https://github.com/obsproject/obs-studio/releases/download/28.1.0-rc1/OBS-Studio-28.1-rc1-Full-x64.zip
2. unzip OBS-Studio-28.1-rc1-Full-x64.zip
3. ./bin/64bit/obs64.exe

**Comment by Fenrirthviti** [comment]
I cannot replicate this issue, the 28.1 RC1 following the steps provided. The zip works just fine. More information is required to reproduce.

**Comment by RytoEX** [comment]
This is most likely caused by the Windows version being too old.

**Comment by carlsummer** [comment]
@Fenrirthviti All right, try  [OBS-Studio-28.1-rc1-Full-Installer-x64.exe](https://github.com/obsproject/obs-studio/releases/download/28.1.0-rc1/OBS-Studio-28.1-rc1-Full-Installer-x64.exe)  ；but OBS-Studio-28.1-rc1-Full-Installer-x64.exe Error libcef.dll；

**Comment by carlsummer** [comment]
@RytoEX My system is window10 professional 64 bit

**Comment by Fenrirthviti** [comment]
Both the installer and .zip are working fine for me on my Windows 10 test machine.

What exact build number are you running? You might be significantly out of date with Windows Updates.

You can check by pressing win+r -> type `winver` in the run dialog, and looking at the exact full version number.

**Comment by carlsummer** [comment]
Solved   https://github.com/obsproject/obs-studio/releases?page=3   
![image](https://user-images.githubusercontent.com/16281965/197527601-59fb477d-07bf-46f0-8bb8-5ab03694ad3c.png)

**Comment by carlsummer** [comment]
![image](https://user-images.githubusercontent.com/16281965/197527640-ae94b40b-5adb-491e-9719-569104dfdbcd.png)

**Comment by dodgepong** [comment]
Installing an old version isn't really a solution if there's actually a problem. Did you follow the instructions of running `winver` to get the specific version of Windows 10 Professional that you are running?
