### ISSUE TITLE
Application Audio Capture unable to capture audio from [WindowTerminal.exe]

### ISSUE THREAD

**Issue by sheuronazxe** [obsproject/obs-studio#7648]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.3

### OBS Studio Log URL

no error in log

### Expected Behavior

heard sound from any script opened in windows terminal.

### Current Behavior

none sound is recorded from windows terminal

### Steps to Reproduce

1. Add Application Audio Capture (BETA) and select WindowsTerminal.exe

2. Open WindowsTerminal.exe, to test audio type in powershell:
[console]::beep(500,3000)

**Comment by WizardCM** [comment]
Sounds from Windows Terminal are not played via the Terminal exe, but rather the System Sounds category. This is outside of our control.

![image](https://user-images.githubusercontent.com/941350/197425974-04117f3a-7d36-41c9-933e-4ee170294ab9.png)
