### ISSUE TITLE
OBS doesnt let you use certain keys as hotkeys

### ISSUE THREAD

**Issue by DianaNites** [obsproject/obs-studio#7649]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

28.0.3

### OBS Studio Log URL

https://obsproject.com/logs/X1oXHyj43UroUddv

### Expected Behavior

The keys I push should show up as part of the hotkey

### Current Behavior

Pushing certain keys, such as print screen, or any of the "media control" keys like SKIP TRACK, does nothing.

### Steps to Reproduce

1. Open OBS
2. Open settings
3. Open hotkeys
4. Try to use print screen or a "media control" key as a hotkey

### Anything else we should know?

Other applications, such as Discord, properly recognize the keys you push. For example, I have Discord's push-to-talk set to SKIP TRACK, since I have that globally unbound on my desktop, and its in a convenient location on my keyboard. It's a convenient single key that nothing else uses, which will never conflict with anything else, to which theres no replacement on my keyboard, and OBS for some reason doesn't recognize.

This issue means that I cannot have both Discord and OBS set to the same push-to-talk hotkey, and have to come up with a difficult to use contrived hotkey thats acceptable to OBS and doesnt conflict with anything else.

**Comment by WizardCM** [comment]
On GNOME on Ubuntu 22.04, I can confirm that the system's shortcuts take priority - Print Screen and media keys are stolen by the DE.

If I disable the default Screenshot hotkey mapped to Print Screen, then OBS correctly detects the keypress.

![image](https://user-images.githubusercontent.com/941350/197438578-60a9ac43-2583-4634-ad61-6b6af388b226.png)

For media keys, a quick Google tells me there isn't a simple way to disable these system-wide.

**Comment by DianaNites** [comment]
But other applications, like Discord, correctly detect both print screen and media control keys, even the ones that *are* bound.

I'm on KDE, and have the media keys unset.

![2022-10-23-195142](https://user-images.githubusercontent.com/5275194/197439368-ba122d4c-a76b-4772-b901-d9a70338f56f.png)
![2022-10-23-195204](https://user-images.githubusercontent.com/5275194/197439374-7627e152-9c58-4f84-a746-8d4cebfaef4d.png)

**Comment by kkartaltepe** [comment]
We never implemented the media keys since no one had asked until now.

**Comment by kkartaltepe** [comment]
But also i cannot replicate your issue with print screen, this key works for me already.

**Comment by DianaNites** [comment]
That one appears to be because I do have print screen bound in my DE, if I unbind it then OBS seems to see it. Discord sees it either way.
