### ISSUE TITLE
Mouse/Display lag after making a captured Mac app fullscreen can be fixed by changing the display's Color Profile.

### ISSUE THREAD

**Issue by attaboyBrad** [obsproject/obs-studio#7651]
### Operating System Info

Other

### Other OS

MacOS 13 [Ventura]

### OBS Studio Version

28.1.0-rc1

### OBS Studio Log URL

https://obsproject.com/logs/qLu3FoRf7IuStVTy

### Expected Behavior

Consistent performance in OBS

### Current Behavior

After making an app fullscreen and returning to windowed mode, the mouse and every app on that display lags horribly and OBS drops to single digit FPS.

### Steps to Reproduce

The issue:

1. Launch OBS with a ScreenCaptureKit source.
2. Make the SCK captured app (or any app on the same display) full screen and then return it to windowed mode.
3. Observe the terrible screen lag, mouse lag, and OBS performance that will remain as long as OBS is running even if you quit and restart OBS.  I'm not even certain rebooting the Mac fixes it, but I didn't check.

The Remedy:

5. Under 'Display Settings', change the Color Profile on the affected display to anything else (and probably change it back, but that's not part of remedying the above issue).
6. Observe that optimal screen/pointer/OBS performance has resumed.

### Anything else we should know?

I think it might have something to do with the way Spaces work with the ScreenCaptureKit API.  Don't take my smooth-brained word for it though.

Here's a quick video where I reproduce the issue and the fix: https://youtu.be/J0stHr4EfR0

**Comment by attaboyBrad** [comment]
The captured app may need to be on a secondary display as mine is.  I didn't try to reproduce it otherwise.

I'm running the latest Ventura beta, build 22A380.

**Comment by attaboyBrad** [comment]
It may matter whether or not the app is a Catalyst app--I noticed it in GoodNotes and previously observed similar behavior when I used Notability.  At the time I thought it was an issue with the Notability app rather than MacOS or OBS.

**Comment by attaboyBrad** [comment]
- I have reproduced the issue on my primary monitor.
- The performance degradation seems to be made somewhat worse if any sort of Display Scaling is used (including Pixel-Halving a native 2160p display to 1080p), but it’s present even at native resolutions.
- It appears that changing the Display Scaling on the affected display in any way (even to a non-integer scale) remedies the issue similarly to changing the Color Profile for the affected display.
- I have reproduced the issue with Adobe Acrobat Pro in place of GoodNotes, so it’s not limited to Catalyst apps.

**Comment by gxalpha** [comment]
Please confirm that this is still an issue on the current version of macOS (13.2.1 at the time of writing).
13.0 has been known to have quite a few issues regarding ScreenCaptureKit.

**Comment by attaboyBrad** [comment]
I'm afraid I've moved and my setup has changed substantially since I initially filed the report (mostly by consolidating to a single monitor for my Mac setup) so I can't reproduce the conditions exactly, but I don't seem to be able to reproduce the issue now so I'll close the report.
