### ISSUE TITLE
can't add any resource

### ISSUE THREAD

**Issue by truitot** [obsproject/obs-studio#7654]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.3

### OBS Studio Version (Other)

https://obsproject.com/logs/zOkxEljeIeoC6nI9

### OBS Studio Log URL

https://obsproject.com/logs/t7zMXR7kn6mNqWgz

### Expected Behavior

can not add any resource . the add resource is empty when i click on it
and only the white screen i see where the video should be

![obs](https://user-images.githubusercontent.com/116569339/197540128-31d490c2-f00e-4d10-92fe-5dab38c4795b.jpg)

### Current Behavior

i see nothing only white screen and when i click to add resource nothing happens . doesnt opens anything from where to add any files or resource

### Steps to Reproduce

1.
![obs](https://user-images.githubusercontent.com/116569339/197540630-5a65ae3f-b946-47b7-90b4-8dee5709017b.jpg)

2.
![obs](https://user-images.githubusercontent.com/116569339/197540606-1b0f0590-dc5f-4767-85a2-0e486417d158.jpg)

3.
![obs](https://user-images.githubusercontent.com/116569339/197540641-b3a15cd6-fbf4-40dd-be8d-bfe6632d5644.jpg)

...

**Comment by RytoEX** [comment]
This is usually caused by outdated graphics drivers. Please update your graphics drivers. For further support, please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for further assistance. Thank you for your understanding.

**Comment by truitot** [comment]
drivers are up to date, there is no new updates available. but i still can not add any source through the add source button

**Comment by RytoEX** [comment]
You currently have 369.09 installed for the NVIDIA GeForce GT 555M and 21.21.13.6909 installed for the Intel HD Graphics 3000. The latest versions available are 391.35 for the GT 555M

The Intel is a bit trickier as that hardware doesn't appear to have an official Windows 10 driver. Regardless, this is a support issue and not a bug in OBS itself. Please refer to the resources that I previously linked.

**Comment by truitot** [comment]
driver version 381.65 after updates
and when i click to add source there no action !
on other computer with the older version of obs - the same thing
this is bug
the window where to add any source does not work
![oob](https://user-images.githubusercontent.com/116569339/197556793-9ec2f97f-18f0-44d4-b7a7-59f515a79f9c.jpg)

**Comment by RytoEX** [comment]
The window looks normal to me. Click the "OK" button to add a Media Source named "Media Source". In any case, at this point, this is a support request and not a bug report. Please refer to the resources that I previously linked.

**Comment by truitot** [comment]
when i click OK button - nothing happens
there should be the list of all available sources to add - but there is not

**Comment by RytoEX** [comment]
You removed the name under the "Create new" label, so there is no name, so you cannot add a source because a source must have a name. "Add Existing" is only filled with items after you have already added sources. It is for "adding copies of existing sources", which is why it says "Add Existing".

Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for further assistance. Thank you for your understanding.
