### ISSUE TITLE
Missing sources in the "Add source" menu

### ISSUE THREAD

**Issue by truitot** [obsproject/obs-studio#7655]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.3

### OBS Studio Log URL

https://obsproject.com/logs/ywktK4ZXT9OElpE1

### Expected Behavior

when i click to add source there is no list of sources to add

### Current Behavior

The sources that would be displayed on a  column on the small screen, are just not there.
When OBS is displayed on the  monitor, the "add source" menu should be filled with all the available sources.

### Steps to Reproduce

1.Start OBS 28.0.3
2.Open the "Add source" menu, and see that  sources are missing
3. Clicking on the line where should be added source but nothing happens
4. 
![uft](https://user-images.githubusercontent.com/116569339/197565439-14ab478a-bec6-4aad-8e90-d4475b021056.jpg)

...

**Comment by gxalpha** [comment]
See https://github.com/obsproject/obs-studio/issues/7654#issuecomment-1289204287 where you got an answer.

**Comment by truitot** [comment]
empty place in the place where the list of sources should be
when i click on it - nothing opens
![ryr](https://user-images.githubusercontent.com/116569339/197568501-57ee3995-7c83-4a03-8b1f-6ff9093a68c8.jpg)

**Comment by truitot** [comment]
why you close it when it not resolved

**Comment by dodgepong** [comment]
Two reasons:

1) This is a duplicate issue (multiple issues should not be submitted for the same problem)
2) This is a support issue, which should be handled through the regular [support channels](https://obsproject.com/help) rather than through GitHub issues.
