### ISSUE TITLE
[28.1.0-rc1] Projector window "always on top" translation string missing

### ISSUE THREAD

**Issue by ntoff** [obsproject/obs-studio#7657]
### Operating System Info

Windows 10

### OBS Studio Version

28.1.0-rc1

### OBS Studio Log URL

https://obsproject.com/logs/yaD8UVEq96TE8DSp

### Expected Behavior

That the translated "Always on top" string would be displayed

### Current Behavior

Translation id "Basic.MainMenu.AlwaysOnTop" is displayed

![image](https://user-images.githubusercontent.com/9030085/197597535-4b0a75c4-3562-4098-b2e0-4dc363cb90e0.png)

### Steps to Reproduce

1. Open OBS 28.1.0-RC1
2. Right click the preview window -> windowed projector (preview)

### Anything else we should know?

Same issue with the "full screen projector" window as well.

**Comment by derrod** [comment]
Looks like #7525 renamed the translation key without checking other uses. Should be reasonably easy to fix.

**Comment by tytan652** [comment]
Fixed with 6f50aac941bf289fb72766a0f60313e26cf012a1
