### ISSUE TITLE
audio track name missing when recording ffmpeg

### ISSUE THREAD

**Issue by on1razor** [obsproject/obs-studio#7658]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.3

### OBS Studio Log URL

https://link.storjshare.io/jw75lt32aa7axz6kafkdtxahhmdq/obslog%2F2022-10-25%2004-50-01.txt

### Expected Behavior

The name of the audio tracks when recording ffmpeg must correspond to the names specified in the audio section

### Current Behavior

The name of the audio tracks when recording ffmpeg does not correspond to the name specified in the audio section

### Steps to Reproduce

-

**Comment by kyzima-spb** [comment]
I have exactly the same problem when running ffmpeg from console, ffmpeg version 4.4.3

**Comment by tuduweb** [comment]
Because obs-ffmpeg don't set the specified name to ffmpeg command line.

**Comment by Fenrirthviti** [comment]
We don't use ffmpeg cli, we interface with the library.

**Comment by tuduweb** [comment]
> We don't use ffmpeg cli, we interface with the library.

Maybe I am wrong. But this caused by obs-ffmpeg not set the audio name in stream metadata, and I have debugged this last time. It's not easy to fix.
