### ISSUE TITLE
OBS making screen black and unusable while streaming

### ISSUE THREAD

**Issue by JinglBells** [obsproject/obs-studio#7659]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.3

### OBS Studio Log URL

https://obsproject.com/logs/fKmTOt2wFqUnQKeQ

### Expected Behavior

The stream to function smoothly and not crash,

### Current Behavior

While streaming OBS makes my screen go black and eventually becomes unusable requiring a force restart of my system.

### Steps to Reproduce

1.open OBS
2.open Chatterino
3.stream
...

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
