### ISSUE TITLE
Yellow frame around entire screen rather than shared "Display Capture > Filters > Crop/Pad"

### ISSUE THREAD

**Issue by T-E-N** [obsproject/obs-studio#7660]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.3

### OBS Studio Log URL

n/a

### Expected Behavior

When using "Display Capture > Filters > Crop/Pad", the yellow frame should show around the shared area

### Current Behavior

When using "Display Capture > Filters > Crop/Pad", the yellow frame is drawn around the edges of the entire monitor, of which only a fraction may be practicable to broadcast (e.g. due to resolution), but unnecessarily difficult to use without borders indicating its actual crop area.
![OBS Display Capture Filter Crop-Pad 1280x720](https://user-images.githubusercontent.com/33468474/197759465-3f946d9b-4846-472d-b07a-c7af7cd5e0b5.png)

### Steps to Reproduce

1. Configure "Display Capture > Filters > Crop/Pad" to part of a monitor (e.g. 1280x720 out of 3840x2160).
2. Observe the yellow frame which should show around the actual capture, but is currently drawn at all 4 edges of the screen instead (hence only part of 1 top line visible in the attached screen shot).

**Comment by gxalpha** [comment]
The yellow border is drawn by Windows, we cannot control where it is.
As a side note, it doesn’t exist at all on Windows 11.
