### ISSUE TITLE
Starting Stream via YouTube  Connected Account disregards Studio Defaults

### ISSUE THREAD

**Issue by domenicdistefano** [obsproject/obs-studio#7661]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.3

### OBS Studio Log URL

NA

### Expected Behavior

Full writeup [here](https://obsproject.com/forum/threads/how-to-disable-youtube-live-chat-with-connected-account-spam-sex-bots-issue.160895/).

When OBS starts a YouTube Stream via a Connected Account connection (NOT stream key) the Studio Defaults are NOT used - specifically chat is ENABLED even if the default is disabled within Studio. 

The OBS interface for starting a stream via the API does not have checkboxes for controlling chat (yes / no checkbox would be desired)

### Current Behavior

Result is live streams are plagued with spam / sex bots 

### Steps to Reproduce

1.
2.
3.
...

**Comment by derrod** [comment]
The YouTube Studio defaults are not accessible via the YouTube API, furthermore YouTube does not allow us to disable the chat via the API.

Also GitHub issues are not for feature requests, use the ideas page for those: https://ideas.obsproject.com/
