### ISSUE TITLE
Overflow of `display_width` in vlc-video plugin

### ISSUE THREAD

**Issue by CoalZombik** [obsproject/obs-studio#7666]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

Git

### OBS Studio Log URL

https://obsproject.com/logs/-9kLz92IqEfzryb8

### Expected Behavior

Valid width and height of VLC video source.

### Current Behavior

Playing a video with very high resolution (tested with 3860x2160) multiplexed via MKVToolNix causes overflow of `display_width` variable in `calculate_display_size` function (`plugins/vlc-video/vlc-video-source.c`), because `track->video->i_sar_num` and `track->video->i_sar_den` contain a large number (in my scenario total number of pixels): 3840*8294400 > 2^31-1.

### Steps to Reproduce

1. Make example videos
    - `ffmpeg -f lavfi -i testsrc=duration=15:size=3840x2160:rate=30 -c:v libx264 -preset fast -crf 22 4k_test_ffmpeg.mkv`
    - `mkvmerge -o 4k_test_toolnix.mkv 4k_test_ffmpeg.mkv`
2. In OBS, create new VLC source and select:
    - `4k_test_ffmpeg.mkv`, the video plays correctly
    - `4k_test_toolnix.mkv`, the video is horizontally squished due overflow

**Comment by RytoEX** [comment]
I've confirmed that the Steps To Reproduce above result in the Current Behavior described and that the linked PR resolves the issue.
