### ISSUE TITLE
Hotkey edit boxes for keyboard shortcuts in Settings Need Accessible Names

### ISSUE THREAD

**Issue by kellylford** [obsproject/obs-studio#7668]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.3

### OBS Studio Log URL

https://obsproject.com/logs/b1mX12Botw9iAMqV

### Expected Behavior

To hear proper names of each hotkey whn moving to the edit area for configuring the hotkey. This is the name of the function, not the actual hotkey.

### Current Behavior

All you hear is "edit" with a screen reader.

### Steps to Reproduce

1. Load a screen reader such as JAWS, NVDA or Windows Narrator. Alternatively use an accessibility verification tool such as Accessibility Insights from http://accessibilityinsights.io. For this issue besure and get the Windows version, not the web extension.
2. Open Settings:Hotkeys.
3. Tab through this area and note how for all the places where you are to enter a hotkey, all you hear with a screen reader is edit. The name of the hotkey, such as stop recording, would ideally be the name of the edit box.

**Comment by buddywhitman** [comment]
I did some digging and figured out these files need to be edited:
[Language-specific UI](https://github.com/obsproject/obs-studio/blob/c289efd84a42887feba89c3579d39a9c264b749e/UI/data/locale/en-US.ini#L1166)
[Backend](https://github.com/obsproject/obs-studio/blob/c289efd84a42887feba89c3579d39a9c264b749e/UI/window-basic-main.cpp#L2524)

Need some help on relevant tags or syntax to specify metadata for these respective buttons, basically, what do I use as the equivalent of html tags in cpp to provide screen readers with the right metadata?

**Comment by shashtag** [comment]
Hey, Please can you assign this issue to me.

**Comment by RytoEX** [comment]
Fixed by #10144. Will be part of OBS Studio 30.1 (currently in beta).
