### ISSUE TITLE
28.0.3 is running using Rosetta on M1 MBP

### ISSUE THREAD

**Issue by proactivematter** [obsproject/obs-studio#7674]
### Operating System Info

macOS 12

### OBS Studio Version

28.0.3

### OBS Studio Log URL

https://obsproject.com/logs/JWV8AcVsMi9Uurtd

### Expected Behavior

OBS 28+ to run natively on M1.

### Current Behavior

OBS in running on Rosetta.

Can be seen in the log "Rosetta translation used: true" and also in Acitivity Monitor > CPU, where OBS is listed as "Intel"

### Steps to Reproduce

.

**Comment by RytoEX** [comment]
Is this the Steam copy?

**Comment by proactivematter** [comment]
OBS is available on Steam? Didn't know that - so no, it's not. I had OBS 27 previously installed and merely read the release notes when it prompted me to update to 28 and though that was it. So everyone who's on M1 needs to redownload it?

I wonder if this is the case for all apps - I've had a bunch of apps that announced native M1 support on their release notes but I didn't redownload / reinstall unless instructed.

**Comment by proactivematter** [comment]
OK. Downloaded, unninstaled what I had and installed the ARM64 version. Problem solved.

This is still a bug, in the sense that users should be instructed to perform this procedure, but I'll close it for now.

Also, it needs to be said - holy fuck what a difference. I'm running a multi-instance 2X4K feeds recording setup and I can push way more quality now - more than what I need honestly, don't even know where the ceiling is - and at less CPU cost. Apple silicon is amazing.
