### ISSUE TITLE
P010 Video Format Incompatible with Scale Filtering/Luma Wipe Transition

### ISSUE THREAD

**Issue by Lycanthrope-R** [obsproject/obs-studio#7675]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.3

### OBS Studio Log URL

https://obsproject.com/logs/QMIRIIDq_CxYeJB5

### Expected Behavior

When using capture card HDR video input set to P010, the video should be automatically tone-mapped into SDR when placed into an SDR canvas.

### Current Behavior

If the HDR video source has a downscaling filter applied to it, e.g. bilinear, bicubic, etc., it darkens the video. This is negated if you set the canvas to either P010 or Rec.2100 in the advanced settings, but that prevents streaming in SDR.

Previewing the video source in the properties or filter menu reveals the actual color, and it can be compared to the darkened version in the actual scene.

![Screenshot (23)](https://user-images.githubusercontent.com/116864540/198512638-b84e69f8-c03c-44e6-9561-7d17b89b866a.png)

### Steps to Reproduce

1. In the Advanced Settings, set OBS to NV12 format, and the color space to Rec.709.
2. Create a scene and add a Video Capture source 📷 with HDR input.
3. In the properties, set the capture to P010 format and Rec.2100 (PQ) color space.
4. Right click on the source and apply any type of scale filtering.
5. ***NEW (10/31/2022)*** Set the transition to Luma Wipe or Cut
6. ***NEW (10/31/2022)*** Disable scale filtering or switch to Fade transition to compare.

### Anything else we should know?

The capture card used was AVerMedia GC553 Live Gamer Ultra.
The HDR tone mapping (override) filter doesn't appear to have any general effects.
***NEW (10/31/2022)*** Engaging Deinterlacing at the same time also seems to negate the problem.

**Comment by jpark37** [comment]
I am using a Video Capture Device source that is capturing Rec. 2100 P010, I cannot repro a difference between any of the scale filtering options in the scene preview, even shrinking the source a little bit.

I do reproduce a difference between source preview and scene preview, but this is expected if HDR is enabled on the display in Windows settings. We don't care about how the source will eventually be displayed for source preview; we give you the full HDR color if the source and display both support it. The scene preview version of the source will be darker because we have tonemapped that down to SDR since the video color space is set to Rec. 709.

**Comment by Lycanthrope-R** [comment]
My computer display does not have HDR capabilities. Maybe that has something to do with it. But I would think that the preview in the Properties/Filter screen is already tonemapped. Whatever is showing in my scene with scale filtering applied just isn't correct. And it can't be streamed as-is. The difference can be pretty substantial depending on what's being shown and trying to add color correction filters seemingly disables the HDR.

No color correction. You can see the difference in brightness. The Filter side is what it's supposed to look like.
![Screenshot (26)](https://user-images.githubusercontent.com/116864540/198815549-4b40ef5f-1564-4138-991f-636daff8896c.png)

Color correction. The color correction applied just makes both previews look bad, though the same.
![Screenshot (25)](https://user-images.githubusercontent.com/116864540/198815565-49b7a6a1-bf1f-437c-9bbc-d0008f0ac1c7.png)

Something is going wrong.

**Comment by jpark37** [comment]
With HDR flipped off in Windows display settings, I still can't repro, only now the brightness between previews are the same. I'm still toggling through the scale filter options on a slightly shrunken source, and it's not making a difference.
![image](https://user-images.githubusercontent.com/10396506/198837578-ba0dae2e-2487-471b-916f-05987275bf86.png)

Have you tried testing this in a fresh portable install without plugins? I have no idea how invasive StreamFX and StreamElements are, and they might be messing with the color handling.

**Comment by Lycanthrope-R** [comment]
A clean install almost solved it. But I don't think it's the plugins. Transferring my scenes back seems to have triggered it again. I'll have to run some more tests to pinpoint the problem.

**Comment by Lycanthrope-R** [comment]
I think I've figured out the trigger. Do everything I've listed above, AND add a Luma Wipe scene transition.

P010 HDR Video Format + Scale Filtering + Luma Wipe seems to be conflicting somewhere.

**Comment by jpark37** [comment]
Thanks, I was able to repro. Fix coming.

**Comment by Lycanthrope-R** [comment]
I appreciate it.
