### ISSUE TITLE
MS Store version is out of date

### ISSUE THREAD

**Issue by ppvnf** [obsproject/obs-studio#7681]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.3

### OBS Studio Log URL

N/A

### Expected Behavior

OBS Studio 28.0.3

### Current Behavior

OBS Studio 28.0.1

### Steps to Reproduce

1. Download OBS Studio from MS Store

### Anything else we should know?

I believe MS Store version should be correctly updated or removed. An outdated version does more harm than good

**Comment by Jeroenvh99** [comment]
The version on MS store is still 28.0.1, while the latest release on the OBS website is 28.1.2

**Comment by Fenrirthviti** [comment]
The version update has been submitted, but it can take a few days for MS to approve.
