### ISSUE TITLE
Please use WinGet Releaser (or similar solution to auto update Winget package)

### ISSUE THREAD

**Issue by ppvnf** [obsproject/obs-studio#7683]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.3

### OBS Studio Log URL

N/A

### Expected Behavior

I believe obs-studio is already on Winget and it seems up to date, but would it be possible to use https://github.com/marketplace/actions/winget-releaser (or a similar solution) to make it up to date automatically?

### Current Behavior

Thanks to [vedantmgoyal2009](https://github.com/vedantmgoyal2009) efforts, obs-studio is automatically updated on Winget, but this isn't ideal because:

- Sometimes automation may go offline for maintenance, hence it is better to use GitHub Action. It is also easier to maintain and implement new features in the action. All apps use the latest manifest schema and fields.

- Automation is generally preferred for non-GitHub packages (meaning: software which are hosted on GitHub) that cannot take advantage of the GitHub Action.

- Since all GitHub API requests are authenticated with my account, using action distrubutes the amount of traffic on GitHub. The action is triggered automatically on releases, so we don't need to fetch APIs or scrape webpages to check for updates periodically, and PRs are created with the software's developer account.

- Microsoft prefers publishers managing releases for their apps themselves instead of a third party. It isn't a hard-and-fast rule, note the word "prefers" here.

### Steps to Reproduce

N/A

**Comment by Fenrirthviti** [comment]
Since we do not currently manage or have anything to do with the winget packages, this is effectively a request for an official winget package. If so, this should be submitted to our [ideas page](https://ideas.obsproject.com) as we do not use GitHub issues for feature requests.

**Comment by ppvnf** [comment]
> Since we do not currently manage or have anything to do with the winget packages, this is effectively a request for an official winget package. If so, this should be submitted to our [ideas page](https://ideas.obsproject.com) as we do not use GitHub issues for feature requests.

I am unable to log in there

![Captura de tela 2022-10-29 160844](https://user-images.githubusercontent.com/73800734/198848768-8c42b63a-fcc6-4ba4-ab1c-0f6966a3b021.png)

**Comment by ppvnf** [comment]
https://ideas.obsproject.com/posts/2008/please-use-winget-releaser
