### ISSUE TITLE
Selection in comboboxes can't be changed with mouse wheel

### ISSUE THREAD

**Issue by owlnull** [obsproject/obs-studio#7688]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.3

### OBS Studio Log URL

https://obsproject.com/logs/b7ewdR_LWPHSQwBf

### Expected Behavior

Selection in comboboxes can be changed with mouse wheel without opening the dropdown

### Current Behavior

Mouse wheel over comboboxes does just nothing

### Steps to Reproduce

1. Find any combobox
2. Try to change the selection with mouse wheel

**Comment by nullium21** [comment]
Also reproducible with 28.0.3 @ Arch Linux.

**Comment by gxalpha** [comment]
This is intended behavior to avoid accidental changes that could pose privacy risks, for example when changing a captured window in the source toolbar.

**Comment by derrod** [comment]
It's an intentional change as many people ran into issues of accidentally changing their settings when trying to scroll a container that contains properties with dropdowns.

**Comment by nullium21** [comment]
Would still be nice if it was doable by, e.g. holding some modifier key (Shift/Alt/Ctrl) while scrolling.

**Comment by owlnull** [comment]
Oh, I see. But why it can't be re-enabled in the settings? It's a common behavior and I'm frequently using it, for example to quickly tweak some settings. In case this ux change was made because of privacy issues, why can't it be disabled just in some specific places such as window selector, not everywhere?
