### ISSUE TITLE
NVENC encoder error v28.1

### ISSUE THREAD

**Issue by Lakida0** [obsproject/obs-studio#7698]
### Operating System Info

Windows 11

### OBS Studio Version

28.1.0

### OBS Studio Log URL

https://obsproject.com/logs/6U366dxiJuEc4mi9

### Expected Behavior

I want to be able to start recording video or streaming normally in simple output mode using NVENC encoder

### Current Behavior

An error occurred in the NVENC encoder, I cannot use NVENC to record video or stream

### Steps to Reproduce

1.I use Nvidia GTX 1050 mobile graphics card
2.I use simple video settings like below
<img width="713" alt="屏幕截图 2022-11-01 141422" src="https://user-images.githubusercontent.com/94156927/199173506-489b40ac-4f48-4f38-9303-56272bab8cb6.png">
3.Then this error occurred while recording video
<img width="372" alt="屏幕截图 2022-11-01 141459" src="https://user-images.githubusercontent.com/94156927/199174365-67d0c3f0-c1c0-4c2b-824b-cdc21dc6eb1c.png">
4.Stuck in connecting when clicking Start Streaming
<img width="180" alt="屏幕截图 2022-11-01 142511" src="https://user-images.githubusercontent.com/94156927/199174429-477dbb41-8459-4daa-881a-3514053db1de.png">

...

### Anything else we should know?

The problem does not exist in version 28.0.3 or use NVIDIA H.264 encoder and I use the latest version of nvidia driver

**Comment by energizerfellow** [comment]
Nvidia GPUs have no support for B-frames in HEVC at the hardware level until 7th-gen NVENC on Turing (GTX 1650 Super / RTX 2000-series and up).

More information:
https://docs.nvidia.com/video-technologies/video-codec-sdk/nvenc-application-note/index.html
https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new

**Comment by Lakida0** [comment]
> Nvidia GPUs have no support for B-frames in HEVC at the hardware level until 7th-gen NVENC on Turing (GTX 1650 Super / RTX 2000-series and up).
> 
> More information: https://docs.nvidia.com/video-technologies/video-codec-sdk/nvenc-application-note/index.html https://developer.nvidia.com/video-encode-and-decode-gpu-support-matrix-new

Thanks, but this issue doesn't happen in 28.0.3, and the release log doesn't say it will change the B-frame settings in simple output mode, if possible I'd like a future version to automatically recognize the graphics card to use a different output preset

**Comment by RytoEX** [comment]
@Lakida0 Please test the build from #7700.
