### ISSUE TITLE
Browser plugin missing in rpmfusion.org build

### ISSUE THREAD

**Issue by hs65** [obsproject/obs-studio#7701]
### Operating System Info

Other

### Other OS

fedora 36

### OBS Studio Version

28.0.3

### OBS Studio Log URL

http://notneeded.com

### Expected Behavior

I miss the Browser plugin in the build of rpmfusion-free-36.rpm on rpmfusion.org

### Current Behavior

Plugin does not exists

### Steps to Reproduce

1. Open OBS Studio
2. Add new Source
3.
...

### Anything else we should know?

I do not know who created the build and is responsible for.

**Comment by Fenrirthviti** [comment]
We do not maintain the rpmfusion build, please report it to the package maintainer.

**Comment by 3laws** [comment]
[This is what you're looking for.](https://github.com/mihawk90/obs-studio.spec/releases)
