### ISSUE TITLE
Docks shuffle around randomly when on laptop screen

### ISSUE THREAD

**Issue by LudoNarraBrit64** [obsproject/obs-studio#7702]
### Operating System Info

Windows 10

### OBS Studio Version

28.0.3

### OBS Studio Log URL

https://obsproject.com/logs/iIjk7kLxIOTP-AJ-

### Expected Behavior

I expected the docks to all be in the same place on my smaller laptop monitor when I move the window from my big monitor.

### Current Behavior

![Screenshot 2022-11-01 184234](https://user-images.githubusercontent.com/108527789/199312774-1c56e2ee-3c43-4f06-9ba7-032961d3a4bd.png)
The docks all overlap each other, but this is purely visual. If I click on the right of the screen, where Stream Chat should be, it still highlights the buttons in that dock, but this isn't ideal. I want to use the big monitor to display the game I'm streaming.

### Steps to Reproduce

Extend displays, then move the OBS window from one window to another.

**Comment by RytoEX** [comment]
Your graphics drivers (particularly for the Intel iGPU) are out of date, which is usually the cause for such visual glitches.

**Comment by LudoNarraBrit64** [comment]
I've updated both the integrated graphics and the NVIDIA GPU drivers to the latest version and I still get the same visual glitches.

**Comment by RytoEX** [comment]
Please provide a new log file. Please attempt to reproduce this in OBS Studio 28.1.0. Please also attempt to reproduce this with the following conditions, independently and in combination:
1. No third-party plugins.
2. Fresh scene collection.
3. No browser docks.

**Comment by LudoNarraBrit64** [comment]
I've done the things you suggested but it still looks like this:
![image](https://user-images.githubusercontent.com/108527789/199481042-a687979f-295c-4bd9-987f-8795828d6f04.png)


New log https://obsproject.com/logs/jSwLhDCWgf_HuRxm

**Comment by Fenrirthviti** [comment]
Are you using any kind of screen mirroring or VR display utilities? Those are the most common causes of rendering issues in OBS, which are outside of our control. Since this is more of a support issue than a bug report, please use our Forums or Discord for further assistance.

https://obsproject.com/kb/known-conflicts
