### ISSUE TITLE
With dark mode enabled, scroll bar in Release Notes is white in macOS

### ISSUE THREAD

**Issue by rakleed** [obsproject/obs-studio#7703]
### Operating System Info

macOS 13

### OBS Studio Version

28.0.3

### OBS Studio Log URL

https://obsproject.com/logs/Ox5toZNwi5HUoxfp

### Expected Behavior

The scroll bar is dark in Release Notes when using the dark theme.

### Current Behavior

The scroll bar is light in Release Notes when using the dark theme.

### Steps to Reproduce

1. Make sure dark theme is selected in macOS Appearance settings
2. Install OBS 28.0.3
3. Open OBS
4. Click on OBS Studio app menu
5. Choose Check for Updates

### Anything else we should know?

<details><summary>Screenshot</summary>

<img width="732" alt="Screenshot 2022-11-01 at 03 55 46@2x" src="https://user-images.githubusercontent.com/19418601/199320109-a66d0daf-75e9-4beb-9d5d-7e22794e87b0.png">

</details>

You most likely need to update [Sparkle](https://github.com/sparkle-project/Sparkle) dependence to the latest version. Specifically, in version [2.2.1](https://github.com/sparkle-project/Sparkle/releases/tag/2.2.1) this problem was fixed.

**Comment by gxalpha** [comment]
Fixed by a combination of https://github.com/obsproject/obs-studio/pull/7723 and https://github.com/obsproject/obs-studio/pull/8161
