### ISSUE TITLE
Please add back the ability to dock "stats" window on to bottom panel.

### ISSUE THREAD

**Issue by CortexReaver** [obsproject/obs-studio#7706]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

28.1.1

### OBS Studio Log URL

no

### Expected Behavior

Like it was before, back to old versions.

### Current Behavior

This was such a useful feature, why do you have disabled it? Also you need to reactivate it after each start, it does not stay on the same place even as a window.
![Скриншот 02-11-2022 141908](https://user-images.githubusercontent.com/34350690/199480324-5c46c11f-2131-4a21-991f-c997c60dfe39.jpg)

### Steps to Reproduce

1. Open OBS
2. View
3. Stats

**Comment by WizardCM** [comment]
Use Docks -> Stats for the Stats dock. The option under view is a separate Window that cannot be docked.
