### ISSUE TITLE
Three crashes in one day

### ISSUE THREAD

**Issue by wells1013** [obsproject/obs-studio#7712]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

26.1.1

### OBS Studio Log URL

https://obsproject.com/logs/h_foXPknNgdVBGXz

### OBS Studio Crash Log URL

https://obsproject.com/forum/attachments/crash-2022-10-31-19-02-05-txt.88206/

### Expected Behavior

other logs files:
https://obsproject.com/forum/attachments/crash-2022-10-31-20-46-10-txt.88207/
https://obsproject.com/forum/attachments/crash-2022-10-31-20-46-57-txt.88208/

There's something wrong with this "OBSBasicSettings::SimpleRecordingEncoderChanged“  method

### Current Behavior

obs crashed

### Steps to Reproduce

1.
2.
3.
...

### Anything else we should know?

One of them crashed after changing the rate

**Comment by WizardCM** [comment]
OBS 26.1.1 was released January 2021 and is no longer supported. Please update to 28.1.1 and attempt to recreate the crash.
