### ISSUE TITLE
MacOS: Fullscreen recording indicator visible in Display Capture & MacOS Screen Capture Beta

### ISSUE THREAD

**Issue by TheCymaera** [obsproject/obs-studio#7713]
### Operating System Info

macOS 12

### OBS Studio Version

28.1.1

### OBS Studio Log URL

NA

### Expected Behavior

The indicator window should be filtered out.
See Chromium and Electron for a possible solution: 
- https://source.chromium.org/chromium/_/webrtc/src.git/+/a18fddcb53e64448afee62aaf84489c8bb89cb6a
- https://github.com/electron/electron/issues/33661

### Current Behavior

MacOS Monterey displays a recording indicator when an application is screencasting and/or using the microphone.
In OBS, the indicator is visible in Display Capture & MacOS Screen Capture Beta.

See orange dot in top right corner:
![Screen Shot 2022-11-03 at 11 20 17 PM](https://user-images.githubusercontent.com/69355340/199762989-309eaf72-fa9d-4cbb-87ec-d1df360411cb.png)

### Steps to Reproduce

1. Open screen capture in OBS.
2. Open a window in fullscreen.
3. Observe top right corner.

**Comment by gxalpha** [comment]
We only use GitHub issues for tracking bugs, and as the yellow dot really does show up on the display, this is a feature request. Please post feature requests on https://ideas.obsproject.com.
Thank you!
