### ISSUE TITLE
HDR to SDR tonemapping (override) does not show or do anything in the preview window

### ISSUE THREAD

**Issue by deesto1** [obsproject/obs-studio#7717]
### Operating System Info

Windows 11

### Other OS

Mac Os 12.6.1

### OBS Studio Version

28.1.1

### OBS Studio Log URL

N/A

### Expected Behavior

Using an HD60X to caputre HDR content and using an HDR to SDR filter (override) within OBS does not seem to do anything. Expected colours to change accordingly as if I were to apply a LUT color correction filter.

### Current Behavior

Using an HD60X to caputre HDR content and using an HDR to SDR filter (override) within OBS does not seem to do anything. Expected colours to change accrodingly as if I were to apply a LUT color correction filter.

### Steps to Reproduce

1. Use HD60X elgato to capture HDR content with internal tonemapping switched off using elgato's utility.
2. obs
3. apply HDR tonemapping (override) filter setting onto the capture device, as you would for a LUT (which does work)
...

**Comment by gxalpha** [comment]
Please provide an OBS log file.

**Comment by gxalpha** [comment]
Closing as there was no response in two weeks.
