### ISSUE TITLE
NVENC Error: init_encoder_h264:

### ISSUE THREAD

**Issue by oklokl** [obsproject/obs-studio#7724]
### Operating System Info

Windows 10
insider Version 10.0.19045.2130 stable version

### OBS Studio Version

28.1.1

### OBS Studio Version (Other)

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/lBpyFvHVoWNXQo9G

### Expected Behavior

An error occurs when the start recording button is pressed.

### Current Behavior

![d8c3ca25370df1472489122d9f290b67664008a9](https://user-images.githubusercontent.com/1571600/200147202-cb40f927-f240-48ca-9306-b396d2bbe67d.png)

NVENC Error: init_encoder_h264: nv.nvEncinitialize Encodersen >session, &enc->params) failed: 8 (NV_ENC_ERR_INVALID PARAM),
'ffmpeg' installation was successful, but the bug persisted.
This is from the last month or so. This is the symptom after the obs version upgrade.
I recently formatted windows. The computer is in its initial state. All programs have been installed.
If you use software encoding, you can record without problems.
I've used Nvidia well in the past.

`AppData\Roaming\obs-studio\crashes` The file does not exist.

### Steps to Reproduce

1.record button.
2.error message
3.
...

**Comment by Penwy** [comment]
this is usually caused by trying to use quarter res multipass (default in simple mode) on a GPU that doesn't support it.
Set multipass to full or single pass.

**Comment by derrod** [comment]
Yeah Kepler (GTX 660 in this case) doesn't support multipass. Not sure if we have an issue for tracking that, or if we even really care since Kepler is only a tiny percentage of our users and no longer supported by Nvidia.

**Comment by oklokl** [comment]
![2022-11-06 (1)](https://user-images.githubusercontent.com/1571600/200147954-588b7a2d-904a-4fc9-87f9-1f0c4d0d4483.png)
I am not secure. where are you?

**Comment by oklokl** [comment]
Thank you it was successful.
It would be nice if you could automatically make it compatible with older computers like mine.
:)
