### ISSUE TITLE
OBS Scene changes not working with Zoom

### ISSUE THREAD

**Issue by ddflink** [obsproject/obs-studio#7725]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/1q-Cq6VDrtxo9k8h

### Expected Behavior

when changings scenes in OBS the scene should also change in Zoom. 

### Current Behavior

when changing scenes in OBS the Zoom screen goes blank. I need to stop virtual camera and restart the virtual camera for that scene to appear in Zoom.

### Steps to Reproduce

1. when changing scenes in OBS the Zoom screen goes blank. 
2. I need to stop virtual camera and restart the virtual camera for that scene to appear in Zoom.

### Anything else we should know?

This was working fine before version 28.0. (In version 27.2.4)
Is this a bug in the update? Any workaround? Or can this be corrected in the next update?

**Comment by RytoEX** [comment]
Please re-test OBS Studio 29.0.2 (or newer) and please attach a log file for an OBS session where this problem occurs. The log file that you previously provided shows no scene changes, so it does not appear to match your Steps To Reproduce.

**Comment by RytoEX** [comment]
I cannot reproduce this on OBS Studio 29.0.2.
