### ISSUE TITLE
Latest update (28.1.2) broke existing profiles that use NVENC encoder.

### ISSUE THREAD

**Issue by Ramaloke** [obsproject/obs-studio#7727]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/WaJohfOFE2fMh3T4

### Expected Behavior

Stream starts after "Start Streaming" button is pressed using the selected profile.

### Current Behavior

Stream doesn't start and the following error window appears: https://i.imgur.com/MZ3kwQ0.png

When I go to the profile settings, it has the following appearence: https://i.imgur.com/h0ClPvw.png and my previous configuration disappeared.

### Steps to Reproduce

1. Updated OBS to 28.1.2
2. Pressed "Start Streaming" button
3. Error message "NVENC Error" appeared

**Comment by Ramaloke** [comment]
Additional info: OBS was updated from 28.0.3 to 28.1.2

**Comment by energizerfellow** [comment]
Nvidia Kepler GPUs like your GTX 780 Ti lack support for quarter-resolution multi-pass at the hardware level. Change multi-pass setting to either single-pass or full-resolution.
