### ISSUE TITLE
sparkle feed not valid XML ( https://obsproject.com/osx_update/stable/updates_arm64.xml )

### ISSUE THREAD

**Issue by core-code** [obsproject/obs-studio#7729]
### Operating System Info

macOS 12

### Other OS

macOS

### OBS Studio Version

Other

### OBS Studio Log URL

none

### Expected Behavior

sparkle feeds should be valid XML, and your X86 sparkle feed is working fine. however the ARM64 feed is broken:

`			<title>OBS Studio 28.1.2/title>`

you should change `/title>` to `</title>`

### Current Behavior

update check broken

### Steps to Reproduce

check for updates in ARM version

### Anything else we should know?

nothing

**Comment by jp9000** [comment]
Fixed, thanks.
