### ISSUE TITLE
Recording with NVIDIA NVENC HEVC encoder is not working

### ISSUE THREAD

**Issue by nilsoncore** [obsproject/obs-studio#7735]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

28.1.2, 28.1.1, 28.1

### OBS Studio Log URL

https://obsproject.com/logs/ceVBAM_NdTFQbi0T

### Expected Behavior

NVIDIA NVENC HEVC for some reason is not working.

My graphics card is NVIDIA GeForce GTX 1080 Ti and It should support this encoder. Card's code name is GP102 according to https://en.wikipedia.org/wiki/List_of_Nvidia_graphics_processing_units#GeForce_10_series. Looking at a compatibility table from https://en.wikipedia.org/wiki/Nvidia_NVENC - It says that this card supports this encoder.

### Current Behavior

When I try to record with this encoder selected an error window occurs that says: "An encoder error occurred while recording: Error opening '<filename>': Function not implemented".

It is not informative at all - what kind of function is not implemented or how to possibly avoid this problem?

### Steps to Reproduce

1. Go to "Settings" -> "Output" -> "Recording".
2. Change "Encoder" type in "Recording Settings" to "NVIDIA NVENC HEVC".
3. Press "Start Recording".

### Anything else we should know?

Here are some screenshots:
![obs_hevc1](https://user-images.githubusercontent.com/65307695/200572826-dedfa96b-dc57-4d6b-af8f-bd48c8c8e387.png)
![obs_hevc2](https://user-images.githubusercontent.com/65307695/200572844-283d0a3f-10cc-485f-b3d9-4b991ae1165e.png)

It seems that this problem may be related to a recent fix in 28.1.1 - "Fixed the inability to start the encoder when NVENC is set to a bframe coun higher than is supported by the device [RytoEX]" - because this graphics card doesn't support B-frames in HEVC encoder. Although, this problem occured in 28.1.2, as well as in 28.1.1 and 28.1 (I reinstalled from 28.1.2 to 28.1 and then to 28.1.1 - all the same).

**Comment by nilsoncore** [comment]
The previous log file is a little too bloated since I tried to launch multiple recordings with different settings.

Now I started OBS freshly and then tried only HEVC encoder recording - log file: https://obsproject.com/logs/IBtvf3Vvn8qdyeGV.

**Comment by pkviet** [comment]
hevc is NOT supported by the flv container. Try mkv or mp4 but not flv.
