### ISSUE TITLE
Choppy audio when recording desktop via PipeWire and Mic/Aux is enabled

### ISSUE THREAD

**Issue by haasn** [obsproject/obs-studio#7739]
### Operating System Info

Other

### Other OS

openSuSE Tumbleweed

### OBS Studio Version

28.1.1

### OBS Studio Log URL

https://obsproject.com/logs/arkgDbKjziEuVOtn

### Expected Behavior

Audio is recorded smoothly, the way it is with e.g. `parecord capture.wav`.

### Current Behavior

Audio is very choppy and stuttery.

### Steps to Reproduce

1. Run a video game, in this case "Sunless Skies".
2. Start a recording with the desktop audio capture enabled.

### Anything else we should know?

I've attached a [sample of the recorded audio to demonstrate the issue](https://user-images.githubusercontent.com/1149047/200705631-bc5294dc-5eab-40b0-b6c8-a21778d9efef.mp4). The bug happens even when not grabbing the window, i.e. recording a blank canvas.

It also does not happen when merely recording the desktop under regular usage (e.g. playing music), it seems to only happen intermittently when running something "strenuous enough" to trigger it (e.g. a video game).

I've also attached [the output of `pw-dump`](https://github.com/obsproject/obs-studio/files/9966232/pipewire-dump.txt) with both OBS and Sunless Skies running.

**Comment by haasn** [comment]
An update: It seems that disabling the 'mic/aux capture' (enabled by default) solved the issue. I no longer hear any stuttering whatsoever when recording *just* the default audio monitor.

**Comment by mijorus** [comment]
For those who have the same issue: what @haasn was saying is basically that as a workaround you can set your mic as `mix/aux ` instead of creating multiple sources.

I don't know why

**Comment by tytan652** [comment]
Did this still happen on latest version of PipeWire and OBS Studio since you are on OpenSUSE Tumbleweed ?

**Comment by mijorus** [comment]
> Did this still happen on the latest version of PipeWire and OBS Studio since you are on OpenSUSE Tumbleweed ?

I'm on Pipewire 0.3.66 and OBS 29.0.2, seems to be fixed for me

**Comment by tytan652** [comment]
Closing as fixed as stated above and the author did not gave any update since the my message (3 weeks).
