### ISSUE TITLE
Python 3.11 doesn't work

### ISSUE THREAD

**Issue by fedorareis** [obsproject/obs-studio#7740]
### Operating System Info

Windows 11

### OBS Studio Version

Other

### OBS Studio Version (Other)

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/SrncO9Ez14p6HG5h

### Expected Behavior

Python 3.11 should have loaded

### Current Behavior

OBS comes back with "Could not load Library: <path_to_python311>"

### Steps to Reproduce

1. Open the scripts window
2. Select the "Python Settings" tab
3. Browse to the folder for Python 3.11

**Comment by WizardCM** [comment]
At this time Python 3.11 is untested and unsupported. 3.6-3.10 should all work. To properly support 3.11 we'd likely have to drop 3.6 support, which most users are currently configured for.

**Comment by WizardCM** [comment]
Note: I can reproduce this on Windows.

```
[Python] Could not load library: B:/Software/Python/Python311/
```

**Comment by WizardCM** [comment]
Note: this is currently intentional.

https://github.com/obsproject/obs-studio/blob/dc024a86435ad962e2f06d7d6cbc8457bb288041/deps/obs-scripting/obs-scripting-python-import.c#L42-L43

**Comment by WizardCM** [comment]
I can confirm bumping the maximum supported version does allow 3.11 to load, and basic Python scripts work without issue. Further testing recommended with more complicated scripts.

**Comment by terax111** [comment]
so maybe the patchnotes for obs28 should be updated to reflect this? took me some time to realize what was the problem... (either this or the docs should have a clear list for supported python versions)

**Comment by Jimmy-Z** [comment]
I see this is still the case with OBS 29 and Python 3.11 and found this issue here. I'm guessing this affects a lot of people since if someone goes to python.org, they'll get Python 3.11, which was released several days before this issue was posted.

OBS just says "Python not currently loaded", I'd suggest maybe say something about unsupported python version, and what version is supported, that would be nicer.

**Comment by rogueyoshi** [comment]
Yeah, silent fails should be a no-go generally. Many people might not have a clue where to start. I just had to do a quick google to remember this myself on a fresh OBS install.

**Comment by RytoEX** [comment]
Please test #8520 with Python 3.11.
