### ISSUE TITLE
Silent installing is not working

### ISSUE THREAD

**Issue by sebionofrei** [obsproject/obs-studio#7741]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

28.1.2

### OBS Studio Log URL

n/a

### OBS Studio Crash Log URL

n/a

### Expected Behavior

Running full installer with /S (for silent install) and /D parameter (for specifying where to install it), would expect it to install the product.

D:\>OBS-Studio-28.1.2-Full-Installer-x64.exe /S /D="D:\OBS"

### Current Behavior

However, installer quits in about 5 seconds after starting it with /S /D params.

### Steps to Reproduce

1. download installer from https://cdn-fastly.obsproject.com/downloads/OBS-Studio-28.1.2-Full-Installer-x64.exe
2. open CMD prompt, and navigate to where you downloaded the installer
3. D:\>OBS-Studio-28.1.2-Full-Installer-x64.exe /S /D="D:\OBS"
4. verify if OBS has installed to D:\OBS
...

**Comment by WizardCM** [comment]
What status code does it return? That'll tell you why the installer closed early.

**Comment by sebionofrei** [comment]
D:\>echo Exit Code is %errorlevel%
Exit Code is 0

**Comment by WizardCM** [comment]
I have tested this on Windows 10 22H2 and cannot reproduce. It installs and loads without error. This might be an environment issue - what happens if you load the installer non-silently?

**Comment by WizardCM** [comment]
NSIS might temporarily write an install log to `%temp%`? I forget. That may be worth checking, at least.

**Comment by sebionofrei** [comment]
just checked %temp% path. Creates a temp directory where it extracts ObsInstallUtils.dll and some other file... but 2-3 seconds later this directory gets deleted.

**Comment by sebionofrei** [comment]
Just tried the silent installer on a VM and it didn't upgrade the existing OBS files that exists there.
See attached image

![Capture](https://user-images.githubusercontent.com/5826625/200852639-89d44b63-a240-4c07-8849-f53b500a3417.JPG)

**Comment by sebionofrei** [comment]
Hello,

It seems that OBS installer sometimes ignores /D parameter
I just tested it 3 times in a row, and here is how it behaves:
![image](https://user-images.githubusercontent.com/5826625/201295696-0d9d77fb-8c91-43a1-90b8-66ad9fb5d298.png)

To be sure parameter gets sent, i also checked task manager:
![image](https://user-images.githubusercontent.com/5826625/201295999-ece4628c-2fe7-4077-995a-6265b81ad0c8.png)

**Comment by Fenrirthviti** [comment]
From NSIS documentation:

```
/D sets the default installation directory ([$INSTDIR](https://nsis.sourceforge.io/Docs/Chapter4.html#varother)), overriding [InstallDir](https://nsis.sourceforge.io/Docs/Chapter4.html#ainstalldir) and [InstallDirRegKey](https://nsis.sourceforge.io/Docs/Chapter4.html#ainstalldirregkey). It must be the last parameter used in the command line and must not contain any quotes, even if the path contains spaces. Only absolute paths are supported.
```

**Comment by sebionofrei** [comment]
Thanks for the /D no-quotes explanation, this should have been the issue.
