### ISSUE TITLE
Rotate handle is not working when source is flipped

### ISSUE THREAD

**Issue by exeldro** [obsproject/obs-studio#7744]
### Operating System Info

Windows 10

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/O2uWwY5197No4QDa

### Expected Behavior

drag rotation handle to rotate the source
![image](https://user-images.githubusercontent.com/5457024/200875930-3a5467b6-bd8c-43c2-9c19-4ebbd02214b3.png)

### Current Behavior

rotation handle is not in the position it is drawn
![image](https://user-images.githubusercontent.com/5457024/200875811-e147fff4-76a5-4853-8d1d-3a7fbe7f483a.png)

### Steps to Reproduce

1. Add a source
2. use context menu Transform -> Flip Horizontal
3. try rotating the source by dragging the rotate handle

### Anything else we should know?

the handle seems to be drawn in offset the other direction than its responding for mouse position

**Comment by ioerjfoige0439i** [comment]
lol you would think they would know how to make sure the simplest issues are fixed ... anyways thanks for your plugins exeldro.

**Comment by jp9000** [comment]
> lol you would think they would know how to make sure the simplest issues are fixed ... anyways thanks for your plugins exeldro.

Exeldro is an acknowledged contributor of OBS itself, not just a plugin developer. He has submitted many features, bug fixes, and changes to OBS itself. If this were merely a simple issue, do you not think he would have just submitted the code changes himself?

It's perfectly acceptable to be annoyed with an issue that may seem at first glance to be simple. However, unless you are a developer submitting code to the project, it's kind of presumptuous of you to assume that something may or not be a simple issue. It's a bit more rude when you are not a developer, then mock the project for not having fixed some issue that you as a typical user think is just a "simple" issue. You are not just being disrespectful to all the people who work on the project, but you're being disrespectful to Exeldro as well when you say things like this.

In the future, please be kind and patient with the project and people involved with it. It's a project made up of like-minded contributors who all want to make the tool better. People who have lives. Imperfect, fallible, normal people.
