### ISSUE TITLE
Cannot stop recording

### ISSUE THREAD

**Issue by mcDandy** [obsproject/obs-studio#7745]
### Operating System Info

Windows 11

### OBS Studio Version

28.0.3

### OBS Studio Log URL

https://obsproject.com/logs/MGQRl8Ut6GK8fB3l

### Expected Behavior

Recording will stop

### Current Behavior

Recording did not stop after jitting stop recording button

### Steps to Reproduce

1. start recording with obs droidcam installed and connected to phone via usb
2. after recording some (over 2h in my case) unplug phone
3. try stopping recording
...

### Anything else we should know?

I am low on main ssd space (MBs left becouse of pagefile) which negativly impacts ram usage and in turn behaviour of some programs. I am recording to secondary hdd. File is still salvageable using ffmpeg.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by Fenrirthviti** [comment]
As a note, if this issue is triggered by a third party plugin, please report to the plugin repo.

https://github.com/dev47apps/droidcam
