### ISSUE TITLE
OBS Virtual Camera causes Snap Camera to freeze

### ISSUE THREAD

**Issue by djojoz** [obsproject/obs-studio#7748]
### Operating System Info

macOS 12

### OBS Studio Version

28.1.2

### OBS Studio Log URL

N/A

### Expected Behavior

When using the OBS virtual camera as a source in the Snap Camera application (https://snapcamera.snapchat.com/), the video output should show properly and not freeze.

### Current Behavior

When using the OBS Virtual Camera as a source in the Snap Camera application, the video output freezes. Switching back to another camera source won't work anymore. Only solution is to kill and restart Snap Camera.

The OBS application does not crash. The reason I'm posting the bug report here is because the freeze only happens with OBS Virtual Camera. If I use any other camera sources (FaceTime Camera, Cam Link 4k), and switch back and forth between them, Snap Camera works just fine.

I see this PR #7581 got merged a few days ago, fixing a similar issue. It got released in 28.1.0. I use 28.1.2, so I assume my version contains this fix. The problem must be elsewhere.

### Steps to Reproduce

1. Open OBS.
2. Start the virtual camera.
3. Open Snap Camera.
4. Go to "Settings" and select "OBS Virtual Camera" as source.
5. Click "Back" to return to the main screen.
--> The video output is frozen

### Anything else we should know?

Maybe this could be relevant: my laptop has a M1 Pro chip.

**Comment by MacarioPatrick** [comment]
> ⚠️ Important: On January 25, 2023, Snap Camera will no longer be available to use or download. You can continue using Lenses on your computer with [Snapchat for Web](http://web.snapchat.com/?ref=snap_camera_support) 👻 💻

**Comment by nileshtrivedi** [comment]
There's a project trying to preserve Snap Camera and lenses for desktop: https://github.com/jaku/SnapCameraPreservation

I actually think it would be fantastic to have similar effects as plugins in OBS Studio. But it's non-trivial amount of work, perhaps a startup idea: https://github.com/jaku/SnapCameraPreservation/issues/11

**Comment by RytoEX** [comment]
As Snap Camera no longer distributes or supports their desktop app, we will be closing this as not planned.
