### ISSUE TITLE
MacOS 11 - Problem with Audio Mixer the "Desktop Audio" item

### ISSUE THREAD

**Issue by Rudolfet** [obsproject/obs-studio#7753]
### Operating System Info

macOS 11

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/KKFR619NbNCTElB5

### Expected Behavior

To see on the Audio Mixer the "Desktop Audio" item. 

1. Open Settings
2. Go to Audio
3. Dektop Audio menu 
3.1 Find the list of Global audio devices
3.1.1 Deactivated

### Current Behavior

Does not show desktop audio

### Steps to Reproduce

1. Open Settings
2. Go to Audio
3. Dektop Audio menu 
3.1 Find the list of Global audio devices
3.1.1 Deactivated

### Anything else we should know?

First download of the version 26.x.x and after download the last deplyed 28.1.2

**Comment by Penwy** [comment]
Current versions of OBS Studio running on macOS 13 (Ventura) or later can capture desktop and app audio using the [macOS Screen Capture source](https://obsproject.com/kb/macos-desktop-audio-capture-guide#capture-audio-on-macos-13-ventura).

On older versions of macOS and/or OBS Studio, you must use an [external audio app](https://obsproject.com/kb/macos-desktop-audio-capture-guide#capture-audio-on-previous-versions-of-macos) to capture desktop and app audio.

For more information, see the [macOS Desktop Audio Capture Guide](https://obsproject.com/kb/macos-desktop-audio-capture-guide).

**Comment by gxalpha** [comment]
Closing per the above comment.
Please see our [Discord server](https://discord.gg/obsproject) or [Forums](https://obsproject.com/forum) if you have further questions.
