### ISSUE TITLE
Using an Image Source with a file from a network drive results in missing frames

### ISSUE THREAD

**Issue by SonicMastr** [obsproject/obs-studio#7756]
### Operating System Info

Windows 11

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/V0L_i58hBJAt9dm-

### Expected Behavior

Normal behavior without a performance degradation

### Current Behavior

If the image file is not local, after a short period of time while the source is active(a few seconds), frames will begin to frequently drop until changed to a locally accessable file or disabled

### Steps to Reproduce

1. Create an Image Source
2. Set the image file to a file on a network drive
3. Wait a few seconds

### Anything else we should know?

I haven't ran into this until updating to v28 a short while ago, so this seems like a recent issue. I thought it was something else running in the background, but after disabling sources one by one I found this weird quirk

**Comment by RytoEX** [comment]
This is currently a known design flaw with the Image Source. Images are loaded and polled for changes on the video thread, which can block rendering and cause rendering to stall. This will remain the case until we rewrite the Image Source to load images on a separate thread. In the meantime, it would be best to avoid loading images from network sources.
