### ISSUE TITLE
Dialog box text overwrites the Info badge

### ISSUE THREAD

**Issue by Xylopyrographer** [obsproject/obs-studio#7758]
### Operating System Info

macOS 12

### OBS Studio Version

28.1.2

### Expected Behavior

Dialog box text should not overwrite the info badge

### Current Behavior

Dialog box text item  "Close file when inactive" overwrites the info badge
![SourcePropsGUI](https://user-images.githubusercontent.com/81269441/201293861-4cacc027-75bd-43da-8ab3-55c5d9ff918d.jpg)

### Steps to Reproduce

1. Create a scene
2. IN that scene, add a local media file as a source
3. Right click on that source
4. Select "Properties"
5. Observe the "Close file when inactive" item
...
You'll note the "circle with a question mark" badge is partially overwritten by the text.

**Comment by nikola3211** [comment]
Hi, I think I can solve this. Should I make a PR?

**Comment by Fenrirthviti** [comment]
We always welcome PRs to fix open issues.
