### ISSUE TITLE
After OBS 28 Update VLC Video Sources Via URL Will No Longer Show In Highest Resolution Available But In Lowest Resolution

### ISSUE THREAD

**Issue by WattMilkins** [obsproject/obs-studio#7763]
### Operating System Info

Windows 11

### OBS Studio Version

28.1.1

### OBS Studio Log URL

https://obsproject.com/logs/mCkH_SkPUgY2uJge

### Expected Behavior

Prior to OBS 28, using a VLC Video Source linked to a YouTube URL would show the YouTube video in the highest resolution available. If the highest available quality for that YouTube video is 4K then the VLC Video Source in OBS will show the source in 4K. 

I am currently using version 27.2.4 because of this issue with 28+

### Current Behavior

After the OBS 28 update using a VLC Video Source linked to a YouTube URL will show the YouTube video in a low resolution. If the highest available quality for that YouTube video is 4K then the VLC Video Source in OBS will show the source in a very low resolution such as 144p or 240p or 360p or 480p. I believe instead of showing the highest possible resolution, it is now showing the lowest possible resolution.

### Steps to Reproduce

1. Create a VLC Video Source in Version 27.2.4
2. Link to a 4K live stream by going to the newly created VLC Video Source's properties
3. Then Click the Plus Sign (+) and Add Path/URL
4. Insert a link to a 4K YouTube video or Livestream (Working Link Example: https://www.youtube.com/watch?v=1-iS7LArMPA&ab_channel=EarthCam)
5. Watch the VLC Video Source show a 4K version of the linked video within OBS
... (Now to Compare in Any Version after OBS 28)
6. Follow the steps 1-4 in OBS 28.1.2 (or any version of OBS 28+)
7. Watch the VLC Video Source show a lower resolution version, possibly the lowest resolution available, of the linked video within OBS. (Significant quality drop off)

### Anything else we should know?

If possible I would create a parameter within the VLC Video Source Properties to toggle between available video qualities.

**Comment by RytoEX** [comment]
On my system, in OBS Studio 27.2.4, the video loads in the VLC Source at 256x144.

**Comment by WattMilkins** [comment]
> On my system, in OBS Studio 27.2.4, the video loads in the VLC Source at 256x144.

On both my systems, running OBS 27.2.4 will display the VLC Video Source at max available resolution and running OBS 28+ will display the VLC Video Source at a much lower resolution. 

For Example: https://www.youtube.com/watch?v=R_3-0WkNyr8   
All of the VLC Video Sources at the bottom of this video are being displayed in their highest available setting. However, when they first load into the scene they are momentarily in a much lower resolution.

Additionally, this setting in VLC itself might affect ones results.
VLC > Tools > Preferences (Ctrl+P) > Show Settings = All > Input / Codecs > Preferred video resolution > Best Available

**Comment by RytoEX** [comment]
> > On my system, in OBS Studio 27.2.4, the video loads in the VLC Source at 256x144.
> 
> On both my systems, running OBS 27.2.4 will display the VLC Video Source at max available resolution and running OBS 28+ will display the VLC Video Source at a much lower resolution.

As stated above, that was not my experience.

> For Example: https://www.youtube.com/watch?v=R_3-0WkNyr8 All of the VLC Video Sources at the bottom of this video are being displayed in their highest available setting. However, when they first load into the scene they are momentarily in a much lower resolution.

This video loads in with the scene item at 1280x720 for me.

> Additionally, this setting in VLC itself might affect ones results. VLC > Tools > Preferences (Ctrl+P) > Show Settings = All > Input / Codecs > Preferred video resolution > Best Available

This was already set for me with the previous test.

**Comment by Souljah87** [comment]
I just had a related issue, where 16:9 twitch streams weren't shown in 16:9 but showing it a little less wider (squeezed) using VLC Video Sources. With Browser Sources there seem to be no issue. Also tested with VLC itself where it was shown correctly.

I will create an own issue for this...

**Comment by Souljah87** [comment]
Regarding THIS issue here, i just opened this video directly in VLC and it also uses 720p Resolution for some reason (i selected "best available" in Settings).
So this one could be in issue with VLC itself, not with the VLC Video Source in OBS:
https://www.youtube.com/watch?v=L_KbEsT80KY

**Comment by TerminatorSAW2k** [comment]
Hello, I have the same problem with the current OBS, is there already a solution to this problem?

**Comment by WattMilkins** [comment]
> Hello, I have the same problem with the current OBS, is there already a solution to this problem?

[RytoEX](https://github.com/RytoEX) was not able to replicate the problem so I'm not sure. I still have the issue. After updating to OBS Studio 28+ all of the VLC sources in my scene will play in a significantly lower quality. Reverting back to 27.2.4 leads to the same VLC sources playing at higher quality. This is happening on both of my computers. 

Hopefully this problem can be solved because I would like to update to the newest version of OBS! :)

**Comment by RytoEX** [comment]
It appears that libvlc is no longer able to load URLs in this way, as I can no longer even load any YouTube URLs in this way as a VLC source in OBS, so this Issue seems to be moot unless it can be demonstrated that other video sources are affected.

See also:
* https://code.videolan.org/videolan/vlc/-/issues/10237

**Comment by WattMilkins** [comment]
@RytoEX @TerminatorSAW2k @Souljah87 
👇🏻
Issue with Versions of OBS After OBS 27.2.4 🌎 4/4/2024 📅
https://www.youtube.com/watch?v=FZaczvljMl0&ab_channel=MattWilkins

**Comment by WattMilkins** [comment]
> @RytoEX @TerminatorSAW2k @Souljah87 👇🏻 Issue with Versions of OBS After OBS 27.2.4 🌎 4/4/2024 📅 https://www.youtube.com/watch?v=FZaczvljMl0&ab_channel=MattWilkins

@RytoEX @TerminatorSAW2k @Souljah87  

Ryan,
I made a video showing this issue is still present in the latest versions of OBS but my comment tagging the people involved in this conversation was marked as spam. 
Would you please look into this? 
I would really appreciate if this can be fixed or if you could work with the VLC team to improve both VLC & OBS simultaneously.

Thanks,
Matt Wilkins

**Comment by RytoEX** [comment]
I went and rechecked this in OBS Studio 27.2.4. I still cannot reliably load any YouTube URL in a VLC source with VLC 3.0.20 installed. I also cannot get VLC 3.0.20 itself to load or playback YouTube URLs reliably. When they do load, they are not their highest available resolution. I have still not had it demonstrated to me that it "works perfectly fine in an older version" independent of what VLC version is installed, so I am still not convinced that OBS is the place where something needs to be fixed. It's _possible_ that something went wrong between commit 59bdac1569304cd2112154b51fa5d25df61569cf and some VLC update, but as I am yet unable to reliably load YouTube URLs in VLC sources in either OBS Studio 27.2.4 or 30.1.2, I can't really say for sure and I can't debug this.

I appreciate that this issue is critical to you, but until someone can isolate exactly which versions of VLC and OBS Studio are required to reliably load YouTube URLs or provide a URL video that works reliably that demonstrates this issue, it's unlikely anyone is going to spend time on this in the face of 450+ other Issues and 200+ PRs.

Furthermore, this may yet be an issue in VLC:
* https://code.videolan.org/videolan/vlc/-/issues/10237
* https://code.videolan.org/videolan/vlc/-/issues/28286

**Comment by WattMilkins** [comment]
@RytoEX 

Ryan,
I appreciate the quick response!
I have to use VLC 3.0.17.4 in order to get it to provide a higher resolution in both VLC & OBS. If you use VLC 3.0.17.4 you will see this works properly in OBS 27.2.4, and earlier versions of OBS.

In the 2nd link you shared (https://code.videolan.org/videolan/vlc/-/issues/28286) this person is complaining about this issue arising in the next version of VLC after 3.0.17.4 which is VLC 3.0.18.

I believe both VLC 3.0.18. & OBS 28+ contained changes which led to this issue with OBS and that they are separate issues.
I haven't been able to update my OBS since this started, even if I keep VLC at version 3.0.17.4, after OBS 28+ the resolution does not scale properly.

I will do more research into this and reach out to the VLC devs on their forum too, but a fix might require some collaboration on the part of both development teams.

Thanks,
Matt Wilkins
