### ISSUE TITLE
Unusable for 1 month.

### ISSUE THREAD

**Issue by JanisPlayer** [obsproject/obs-studio#7764]
### Operating System Info

Windows 11

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://pastebin.com/we9A998C

### Expected Behavior

obs-streamelements-core.qt6.dymod was responsible for many crashes a few days ago and was looking for files that couldn't exist, now I have a new problem again.
I reinstalled everything and only the most necessary plugins.
But OBS keeps choosing to freeze.
Sometimes it happens right away or after a few minutes.
Simply unusable, I've lost the stream so often now.

### Current Behavior

The OBS just works and doesn't say, um, I'm not doing anything anymore, and strangely enough, whenever the logs say this:
07:06:15.293: [game-capture: 'Spielaufnahme'] d3d11 shared texture capture successful
And frozen, this time it's not the fault of streamelements but directly of OBS and I don't know why.

### Steps to Reproduce

1. Just use it.
...

### Anything else we should know?

obs-streamelements-core.qt6.dymod ist trash

**Comment by mihawk90** [comment]
If streamelements is being an issue then you should address that issue to streamelements, which is a third party entirely unrelated to OBS.

**Comment by JanisPlayer** [comment]
I've already done that, but as it turns out. Is OBS also partly to blame for the crashes. I no longer have this plugin in it and yet my OBS keeps freezing.

**Comment by JanisPlayer** [comment]
![image](https://user-images.githubusercontent.com/54918417/201462087-3e2eadcd-235f-4dd0-a7d5-d2de14239843.png)
https://pastebin.com/DL64QA93

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by Fenrirthviti** [comment]
As an additional note:

https://twitter.com/OBSProject/status/1587642599271288832

**Comment by JanisPlayer** [comment]
HAGS was the problem, turn it off and everything works fine, now I can use Nvidia noise reductionwithout crashing.
https://obsproject.com/wiki/How-to-disable-Windows-10-Hardware-GPU-Scheduler
That only causes problems, Valorant and OBS are now running great.
