### ISSUE TITLE
Xcomposite preview bug obs 28.0.1.11-3 (64 bit) debian 12

### ISSUE THREAD

**Issue by koreanfan** [obsproject/obs-studio#7768]
### Operating System Info

Other

### Other OS

Debian 12

### OBS Studio Version

Other

### OBS Studio Version (Other)

28.0.1.11-3 (64 bit)

### OBS Studio Log URL

https://obsproject.com/logs/nRbQSfbJACe_5HRt

### Expected Behavior

1.Start obs
2.Add xcomposite and select application window
3.Watch preview
4.Disable preview
5.Enable preview

### Current Behavior

1.Start obs
2.Add xcomposite and select application window
3.Watch preview
4.Disable preview
5.Failed to re-enable preview, no errors shows up
6.Close obs-studio
7.Launch obs-studio, preview shows up
8.Disable preview
9.Failed to re-enable preview, no errors shows up
10.etc

### Steps to Reproduce

1.Start obs
2.Add xcomposite and select application window
3.Watch preview
4.Disable preview
5.Failed to re-enable preview, no errors shows up
6.Close obs-studio
7.Launch obs-studio, preview shows up
8.Disable preview
9.Failed to re-enable preview, no errors shows up
10.etc

**Comment by kkartaltepe** [comment]
I cannot replicate this, the preview can be enabled and disabled with hotkeys or the context menu. With or without xcomposite sources capturing obs or other windows.

**Comment by koreanfan** [comment]
Can't enable preview with hotkeys or context menu

**Comment by koreanfan** [comment]
> I cannot replicate this, the preview can be enabled and disabled with hotkeys or the context menu. With or without xcomposite sources capturing obs or other windows.

Today i test other plugins and confirm that problems only with enabling preview
