### ISSUE TITLE
Segmentation fault on startup, fresh Pop!OS 

### ISSUE THREAD

**Issue by ThatOhio** [obsproject/obs-studio#7772]
### Operating System Info

Ubuntu 22.04

### Other OS

Pop!OS

### OBS Studio Version

28.1.2

### OBS Studio Log URL

N/A (Unable to open OBS)

### Expected Behavior

OBS Studio to launch

### Current Behavior

Crashes without loading

### Steps to Reproduce

1. Install obs-studio via apt with `sudo apt install obs-studio`
2. Open OBS, complete the initial wizard. I've done this with and without actually modifying the scene, and with any of the wizard options.
3. Close OBS
4. Attempt to re-open OBS 
...

### Anything else we should know?

This is the content of my log (the segmentation fault is not listed in the log, but it is the last thing that happens if running from a terminal) 
[2022-11-13 16-04-29.txt](https://github.com/obsproject/obs-studio/files/9998225/2022-11-13.16-04-29.txt)

I am able to open OBS if I first remove the obs folder in .config with `sudo rm -r ~/.config/obs-studio` however this of course removes any settings and forces me to re-do the wizard at the start, and then it will segfault if I run again without removing this folder.

I have done a full apt purge of obs-studio with a autoremove and re-install with no luck.

**Comment by kkartaltepe** [comment]
Please provide a backtrace of the segfault.

**Comment by ThatOhio** [comment]
I hate to be this person but running the app with gdb to try to capture had the app open without problem? And now it's opening fine? I will come back here if the issue comes back up I guess

**Comment by kkartaltepe** [comment]
Then ill close this out, if you do find it reoccurs and get a stacktrace we can open this back up.
