### ISSUE TITLE
preview bug obs 28.0.1.11-3 (64 bit) debian 12 bookworm/sid

### ISSUE THREAD

**Issue by koreanfan** [obsproject/obs-studio#7773]
### Operating System Info

Other

### Other OS

debian 12 bookworm/sid 6.0.0-3-amd64

### OBS Studio Version

Other

### OBS Studio Version (Other)

obs 28.0.1.11-3 (64 bit)

### OBS Studio Log URL

https://obsproject.com/logs/XLRF-q0C_1JdAJF_

### Expected Behavior

1.Start obs
2.Disable preview
3.Enable preview

### Current Behavior

1.Start obs, watch enabled_preview.png
2.Disable preview working, watch disabled_preview.png
3.Click on enable preview button and nothing happend, enable preview button became unpressable after you press this one time.
4.If you try to use context menu command for enable preview then nothing happend, only enable preview button became clickable. Watch button.png
5.If you try to use context menu command for enable preview second time then nothing happend, only enable preview button became unpressable
![enabled_preview](https://user-images.githubusercontent.com/60460757/201596916-67a631c9-822f-4822-aecf-cd122cdbf9d8.png)
![disabled_preview](https://user-images.githubusercontent.com/60460757/201596943-c61e3673-d256-4888-8c47-bc5ceae29ecf.png)
![button](https://user-images.githubusercontent.com/60460757/201597321-d08a9957-d8b2-4b55-a6b2-fd7e13b1abc3.png)

### Steps to Reproduce

1.Start obs
2.Disable preview
3.Enable preview

**Comment by kkartaltepe** [comment]
Do not open duplicate reports, please reopen your original report if you still care about this issue.

**Comment by koreanfan** [comment]
> Do not open duplicate reports, please reopen your original report if you still care about this issue.

i close previous thread and create new thread with new tag name. Read carefully and reopen this thread.
