### ISSUE TITLE
obs crashed on start-up

### ISSUE THREAD

**Issue by test-black** [obsproject/obs-studio#7774]
### Operating System Info

Windows 10

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://gist.github.com/test-black/9e0069d93d5d50def8c47982c4ff14dc

### OBS Studio Crash Log URL

https://gist.github.com/test-black/fdadceab546d08233f6b95c9e937c859

### Expected Behavior

Not crash

### Current Behavior

crash

### Steps to Reproduce

1.
2.
3.
...

**Comment by flaeri** [comment]
Most likely an issue in the LUA script (advanced-timer.lua). Please use the support channels if you would like more assistance.

Discord:
https://obsproject.com/discord

Forums:
https://obsproject.com/forum/

**Comment by gxalpha** [comment]
Closing per above.
