### ISSUE TITLE
High GPU usage with HAGS on and driver >=522.25

### ISSUE THREAD

**Issue by xcasxcursex** [obsproject/obs-studio#7776]
### Operating System Info

Windows 10

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/5D3rTprg5hdpkmci

### Expected Behavior

Same between driver versions

### Current Behavior

Different between driver versions

### Steps to Reproduce

1. Install driver 512.59
2. Enable HAGS
3. Enjoy performance
4. Upgrade to driver 526.86
5. Note high GPU usage when OBS is on screen and encoding

Notes from my testing:

```

Utilisation of the GPU (no encoder etc) of a stock RTX3090
While encoding and visible/minimised to tray
HAGS on vs off
Driver pre-522.25 vs post-522.25

also compared Gsync windowed vs fullscreen only, admin vs unprivileged user, and game mode - 
no change except minor improvement with windowed gsync (interesting but unrelated)
'Prefer maximum performance' in NVCPL makes this MUCH WORSE
tested each scenario three times (hags on test hags off test, hags on test hags off test, hags on test hags off test)



Driver version 526.86

HAGS off
visible			y
buffering			y			n
				%	hz		%	hz
				8	1965		25	210
				
visible			n
buffering			y			n
				%	hz		%	hz
				3	1950		5	210
				


HAGS on
visible			y
buffering			y			n
				%	hz		%	hz
				35	1950		12	210
				
visible			n
buffering			y			n
				%	hz		%	hz
				5	1965		4	210
				



Driver version 512.59

HAGS off
visible			y
buffering			y			n
				%	hz		%	hz
				7	1965		20	210
				
visible			n
buffering			y			n
				%	hz		%	hz
				4	1965		4	210
				


HAGS on
visible			y
buffering			y			n
				%	hz		%	hz
				5	1950		7	210
				
visible			n
buffering			y			n
				%	hz		%	hz
				2	1965		1	210
				

```

### Anything else we should know?

There's currently a known bug in the nvidia drivers causing high GPU util by DWM. I tested 512.59, 517.48 (same results for these two), 522.25, 526.86 (and same for these two (broken)). I do not experience that bug, but these seem likely related. It's the same symptom with the same driver versions on two different apps when they are doing similar compositing tasks.

I don't usually have any problem with HAGS on, in fact my performance was always worse without it, excluding these seemingly broken drivers.

Probably nothing for the OBS team to do here aside from maybe escalate to nvidia, but I thought I should report it so hopefully other users can avoid the days of troubleshooting.

**Comment by notr1ch** [comment]
There isn't really much we can do here as you guessed. HAGS in general can cause all kinds of weird issues as it involves highly GPU / driver dependent behavior, we recommend disabling it if you experience issues. Hopefully newer drivers will resolve the problem.

**Comment by xcasxcursex** [comment]
> Hopefully newer drivers will resolve the problem.

As predicted, the DWM bug was fixed and this one went away, too. Performance in these new drivers with HAGS on is massively improved even over the old versions.

Test results as per the above:


```

Driver version 526.98

HAGS off
visible			y
buffering			y			n
				%	hz		%	hz
				7	1965		22	210
				
visible			n
buffering			y			n
				%	hz		%	hz
				3	1950		4	210
				


HAGS on
visible			y
buffering			y			n
				%	hz		%	hz
				2	1950		5	210
				
visible			n
buffering			y			n
				%	hz		%	hz
				2	1950		0	210
				


```
