### ISSUE TITLE
NVENC settings migration/adjustment causes significant performance loss

### ISSUE THREAD

**Issue by kg** [obsproject/obs-studio#7779]
### Operating System Info

Windows 10

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/lGBSl5CWYsyMI33q

### Expected Behavior

OBS studio update should not regress game performance meaningfully

### Current Behavior

When I updated OBS Studio it appears to have migrated to significantly slower NVENC settings. From checking the update notes this seems somewhat expected, but I was *very* surprised and spent some time messing with downgrading emulators and updating video drivers before realizing that the problem was OBS. Previously when streaming android emulators with OBS doing both x264 CPU encode + NVENC hardware encode simultaneously I could maintain framerates in the 100-120 range in the emulator (vs a near-solid 120 with OBS closed) but suddenly the game was dropping below 60fps while streaming.

My guess is that the issue is the migration produced much higher settings than it would have used previously - I forgot to take a screenshot before troubleshooting, but I believe it had selected CQP, Preset P5 (Slow) or P4 (Medium), and Two Passes (Quarter Resolution). It also had lookahead, 3 bframes, and high profile set along with the high quality tuning. Some of these no doubt map directly to the old settings I had but it seems to have gotten much, much slower. I'm doing high quality offline recording to a big SSD and not trying to maximize quality when streaming via NVENC, so it was quite a shock to have this change.

### Steps to Reproduce

Update to the latest version with NVENC configured for recording

### Anything else we should know?

I think it's fine that things changed this way, but maybe you should detect in the future that the user has NVENC configured and show them a warning that the new settings may cause their games to lag.

I have a few older log files from long streaming sessions that may be more helpful if this seems like it's actually a bug, i made a copy of them.

**Comment by Fenrirthviti** [comment]
This was specifically called out in the patch notes, and there's unfortunately not much we can do, as the old presets don't really have a 1:1 conversion to the new ones. The patch notes have more information:

https://github.com/obsproject/obs-studio/releases/tag/28.1.2
