### ISSUE TITLE
Error linking libobs on arm64 macOS

### ISSUE THREAD

**Issue by realaboo** [obsproject/obs-studio#7783]
### Operating System Info

macOS 12

### OBS Studio Version

Git

### OBS Studio Log URL

N/A

### Expected Behavior

OBS Studio could be built using CI/build-macos.sh as described in https://github.com/obsproject/obs-studio/wiki/build-instructions-for-mac.

### Current Behavior

The script fails on linking libobs as some symbols from FFmpeg could not be found.
FFmpeg included in obs-deps is 5.0.1 which doesn't have these symbols, while latest FFmpeg (5.1.2) does have.

```
FAILED: libobs/libobs.framework/Versions/A/libobs

Undefined symbols for architecture arm64:
  "_av_channel_layout_compare", referenced from:
      _audio_resampler_create in audio-resampler-ffmpeg.c.o
  "_av_channel_layout_default", referenced from:
      _audio_resampler_create in audio-resampler-ffmpeg.c.o
  "_swr_alloc_set_opts2", referenced from:
      _audio_resampler_create in audio-resampler-ffmpeg.c.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Steps to Reproduce

1. `git clone --recursive https://github.com/obsproject/obs-studio.git`
2. `cd obs-studio`
3.  `./CI/build-macos.sh`

**Comment by RytoEX** [comment]
I cannot reproduce this on my M2 MacBook Pro on macOS 12.

**Comment by pkviet** [comment]
@RytoEX tells me CI builds on mac. So imo it seems a local issue.

**Comment by PatTheMav** [comment]
The issue is indeed related to the compiler picking up headers from the wrong location, but this shouldn't happen by default (I do have Homebrew and FFmpeg installed and CMake never picks up anything from there if it isn't already provided by the prebuilt dependencies).

One way this _could_ happen is if the Homebrew include directory is somehow added as a default search path in the shell environment.

**Comment by realaboo** [comment]
> The issue is indeed related to the compiler picking up headers from the wrong location, but this shouldn't happen by default (I do have Homebrew and FFmpeg installed and CMake never picks up anything from there if it isn't already provided by the prebuilt dependencies).
> 
> One way this _could_ happen is if the Homebrew include directory is somehow added as a default search path in the shell environment.

Thanks! I had CFLAGS env var set in my .zshrc which adds "-I/Homebrew/Dir". Removing this before building resolves my issue.
