### ISSUE TITLE
Windowed/fullscreen projector too bright on HDR displays with video capture device

### ISSUE THREAD

**Issue by niekvb** [obsproject/obs-studio#7790]
### Operating System Info

Windows 10

### OBS Studio Version

28.1.2

### OBS Studio Log File

[https://obsproject.com/logs/bLL7UKS5-k1_PpEU](https://obsproject.com/logs/bLL7UKS5-k1_PpEU)

### Expected Behavior

Expected the output to look exactly the same as in the OBS main window.

### Current Behavior

The output image of the (small) windowed projector (and fullscreen projector) is way brighter than it should be on displays with HDR enabled. This happens when using a video capture device, in my case the Elgato Cam Link 4K.

When the projector is moved to/displayed on a display without HDR enabled/available the image looks identical to the one in OBS's main window.

**NOTE**: The screenshot below looks even brighter than IRL, but you can see the difference in brightness

![Untitled2](https://user-images.githubusercontent.com/37668320/202266464-7e8da3eb-d717-4a45-893d-84bf407c3803.png)

### Steps to Reproduce

1. Enable HDR for a capable display in Windows 10:
    - Open *Settings* app.
    - Go to *System* > *Display* > *Windows HD Color settings*.
    - Select the display under *Choose display*.
    - Enable *Use HDR*.
3. Open OBS.
4. Right-click the video capture device.
5. Select either *Windowed Projector (Source)* or *Fullscreen Projector (Source)*
6. Notice the image being way too bright.

### Anything else we should know?

- **No filters are applied** to any source or output.
- ***Configure Video*** settings of the capture device **are set to default**, at:
    - Richt-click video capture device.
    - Below *Device* click on *Configure video*.
    - Click *Default*.
    - Save by pressing *OK*.

**Comment by Fenrirthviti** [comment]
Please provide a log file instead of removing that part of the template.

**Comment by niekvb** [comment]
Log file has been added
