### ISSUE TITLE
preview center

### ISSUE THREAD

**Issue by bandaid** [obsproject/obs-studio#7792]
### Operating System Info

Windows 10

### OBS Studio Version

28.1.2

### OBS Studio Log URL

na

### Expected Behavior

preview ought to lock to center and scale by the size of OBS studio.

### Current Behavior

Justified to the right and top. When resizing the OBS studio the preview window is cut off on the right and bottom.

### Steps to Reproduce

Right-click on the preview pane

Enable  Preview 

Preview Scaling > Scale to window

**Comment by skeletonbow** [comment]
The preview window is intentionally movable and scalable by using the appropriate controls.  This is a support issue best handled on OBS Discord.

**Comment by bandaid** [comment]
![20221117_000911_obs64](https://user-images.githubusercontent.com/8212255/202371628-c5057043-e95d-4ad5-87a3-6e8ae868cd9f.png)
![20221117_001129_obs64](https://user-images.githubusercontent.com/8212255/202371639-f568ba88-b576-43c4-8a69-d0f2fca0e556.png)

**Comment by bandaid** [comment]
> The preview window is intentionally movable and scalable by using the appropriate controls. This is a support issue best handled on OBS Discord.

unrelated. this is not user error. check the bug before spewing junk.

**Comment by bandaid** [comment]
![20221117_002849_firefox](https://user-images.githubusercontent.com/8212255/202374950-6a1eecfa-e4aa-407a-b27d-e88aa03b3013.png)
![20221117_004029_firefox](https://user-images.githubusercontent.com/8212255/202374954-ce0a143e-d7b1-4482-b00f-a69922783f56.png)

**Comment by bandaid** [comment]
So, it is a user error. Changed the "Base (Canvas) Resolution" under the Video category in File > Settings. The borders are no longer cropped. I was under the impression this was automatically detected, even when the user changes resolutions.

**Comment by Fenrirthviti** [comment]
Changing the canvas resolution is a potentially destructive act that can impact all scenes and sources. This is not something we would want to automate.

**Comment by bandaid** [comment]
#Changing the canvas resolution is a potentially destructive act that can impact all scenes and sources. This is not something we would want to automate.

How is detecting the correct input destructive when the application is not recording/streaming? How about adding a dialog box to notify the user that the canvas resolution is different than the current input resolution upon startup? It seems like a legitimate request and functional characteristic to me, just as functional as adding split-time recording which you previously scoffed at as useless.
