### ISSUE TITLE
No open plugin-in interface button (macos)

### ISSUE THREAD

**Issue by hamidreza4dev** [obsproject/obs-studio#7793]
### Operating System Info

macOS 12

### OBS Studio Version

Other

### OBS Studio Version (Other)

28.1.1

### OBS Studio Log URL

https://obsproject.com/logs/qWO4Om2wtLf6skbG

### Expected Behavior

seeing "open plug-in interface" button while I'm adding VST plugin

### Current Behavior

I can't see a button to open the plug-in interface.
image : 
![image](https://user-images.githubusercontent.com/69403093/202374816-ddf5192f-4c2a-4c7c-bc1e-969fe11b6088.png)

NOTE: I got this on every plugin

**Comment by gxalpha** [comment]
The VST plugins don't load as you're using the Apple Silicon version of OBS. The plugins themselves would need to be compiled for Apple Silicon to make this work.

If you want to use x86_64 VST plugins, please run the Intel version of OBS.
