### ISSUE TITLE
SDR-only filters do not throw error messages with HDR sources

### ISSUE THREAD

**Issue by matoi974** [obsproject/obs-studio#7796]
### Operating System Info

Windows 10

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/tmcWOliEOqhyNWH9

### Expected Behavior

SDR filters (such as Image Mask/Blend) should throw an error in the log file when they're being applied to a HDR source (and thus won't do anything).

### Current Behavior

They fail silently.

### Steps to Reproduce

1. Add an Image Mask/Blend filter to any HDR source, like a Video Capture Device source
2. Read the log file

**Comment by gxalpha** [comment]
This works as designed.
When adding a filter, there is an info text informing the user that "Settings only apply to SDR video".

You (or anyone for that matter) are free to submit a PR adding such info to the log (though beware that sources can change color space from frame to frame so this could get very messy), but as written this is a feature request and not a bug.
