### ISSUE TITLE
FFmpeg recording error (NVENC)

### ISSUE THREAD

**Issue by EvilPlayer1** [obsproject/obs-studio#7803]
### Operating System Info

Windows 11

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/_tgpedFggusF5rwo

### Expected Behavior

Recording starts just as before.

### Current Behavior

Unknown error.

### Steps to Reproduce

1. Try to start recording with FFmpeg with any NVENC encoder.

### Anything else we should know?

I think it's caused by new NVIDIA drivers 526.98. I could record videos until I updated them.

**Comment by EvilPlayer1** [comment]
https://obsproject.com/logs/ktBvLz7VSswu_OgR
What is "the gop"? Keyframe interval (frames)?

**Comment by pkviet** [comment]
Yes it is key frame interval.
Try what's suggested.
If it doesn't work, post a log after starting obs with --verbose option (create a shortcut with the option)

**Comment by EvilPlayer1** [comment]
I set it to 4 and recording started. Will it affect video quality on YouTube? They recommend to record with 2 B-frames.

**Comment by pkviet** [comment]
Depends on the content. Shouldn't matter overmuch.
Closing this.

**Comment by EvilPlayer1** [comment]
Thanks for help
