### ISSUE TITLE
After recent update i can no longer use nvenc

### ISSUE THREAD

**Issue by MparkG** [obsproject/obs-studio#7815]
### Operating System Info

Other

### Other OS

5.15.78-1-MANJARO

### OBS Studio Version

28.1.2

### OBS Studio Version (Other)

tried the one supplied with pacman (28.1.2-1) then compiled my own, both execute with the same result.

### OBS Studio Log URL

https://obsproject.com/logs/XKpBUIcjBA0C4kLJ

### Expected Behavior

- my settings would be kept present / intact.
- nvenc would be chosen
- screen recording would work.

### Current Behavior

- my settings are lost, possibly because of redesigned settings menu... and a default choice of twitch as stream sink.

in settings:
- nvenc not popping up as an option. Why not?! id be using that.
- however vaapi pops up:
which doesnt work with the nvidia card:
```
info: [FFmpeg VAAPI encoder: 'advanced_video_recording'] settings:
        device:       /dev/dri/by-path/pci-0000:09:00.0-render <- this is the right device, le nvidia gpu.
        rate_control: CBR
        profile:      578
        level:        40
        qp:           0
        bitrate:      2500
        maxrate:      2500
        keyint:       120
        width:        960
        height:       540
        b-frames:     0

[h264_vaapi @ 0x55b09a3f0880] No usable encoding entrypoint found for profile VAProfileH264ConstrainedBaseline (13).
warning: [FFmpeg VAAPI encoder: 'advanced_video_recording'] Failed to open VAAPI codec: function not implemented

```

### Steps to Reproduce

1. open obs
2. cant configure nvenc
3. try vaapi
4. error
...

### Anything else we should know?

its a laptop with intel on chip grafics, and an nvidia dedicated gpu model GK208M.
while this version of obs has problems, ffmpeg does not hesitate to transcode with h264_nvenc.

i compiled my version just now, with the guide provided here https://github.com/obsproject/obs-studio/wiki/build-instructions-for-linux
>No idea why it says "(28.1.0-beta1-194-gcfcad30e3)"

tell me if you want more info.

**Comment by kkartaltepe** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help). though in this case you should probably ask archlinux users how to correctly configure your environment and not the obs community.

**Comment by MparkG** [comment]
it worked fine before the update.

**Comment by Fenrirthviti** [comment]
I would recommend reporting to the package maintainer, as we don't maintain any of those packages ourselves.
