### ISSUE TITLE
"Sec. Software Status" is not logged by Windows language setting

### ISSUE THREAD

**Issue by style1925** [obsproject/obs-studio#7816]
### Operating System Info

Windows 11

### OBS Studio Version

28.1.2 / 29.0.2

### OBS Studio Log URL

There are two log files, listed under "Current Behavior".

### Expected Behavior

Security Software name is logged in the log file.

### Current Behavior

If the Windows language setting is not English (e.g., Japanese), the security software name is not logged in the log file.

log file (If the Windows language setting is "English")
[2022-11-21 08-57-30.txt](https://github.com/obsproject/obs-studio/files/10051088/2022-11-21.08-57-30.txt)
![English](https://user-images.githubusercontent.com/1337354/202934146-87d5e6a6-42da-4f4c-91ab-5988a221d2d0.png)

log file (If the Windows language setting is "Japanese")
[2022-11-21 09-00-16.txt](https://github.com/obsproject/obs-studio/files/10051095/2022-11-21.09-00-16.txt)
![Japanese](https://user-images.githubusercontent.com/1337354/202934205-70b9c169-5b4f-4602-a3e0-c5c2df0dab25.png)

### Steps to Reproduce

1. Set the Windows display language to "English"
2. Start OBS.
3. Open the log file.
4. The name of the security software is logged in the log file.
5. Quit OBS.
6. Set the Windows display language to "Japanese"
7. Log out of Windows and log in again to apply the settings.
8. Start OBS.
9. Open the log file
10. Security software name is not logged in log file.

### Anything else we should know?

I'm using translation. Sorry if the English is not correct.

Results of checking past versions
21.1.2 and later : No logging. (Same behavior as now)

21.0.1 : Security software names are only partially logged.
```
09:31:56.479: Sec. Software Status:
09:31:56.480: 	Microsoft Defender 
09:31:56.480: 	Windows 
```

**Comment by RytoEX** [comment]
See #7749 and #7766.

**Comment by style1925** [comment]
Thanks for the link to the pull request.
