### ISSUE TITLE
Ram Usage Keeps going up every second. Mac M1

### ISSUE THREAD

**Issue by sutharsha** [obsproject/obs-studio#7820]
### Operating System Info

macOS 13

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/K-vbvvFdpJ9m0cmq

### Expected Behavior

Ram usage needs to be stable after the initial load. 

### Current Behavior

Ram usage keeps going up. 

### Steps to Reproduce

1.Use any camera source
2.Start virtual camera 
3.
...

### Anything else we should know?

Only happens in the m1 versions. On older x86 versions this does not happen.

**Comment by gxalpha** [comment]
Please try again without the droidcamobs plugin.

**Comment by gxalpha** [comment]
Closing as there has been no response in 2 months.
