### ISSUE TITLE
System theme fails to completely automatically transition between light & dark

### ISSUE THREAD

**Issue by sambostock** [obsproject/obs-studio#7821]
### Operating System Info

macOS 13

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/r9YnLUAhwYY7gedD

### Expected Behavior

When the OBS UI theme is set to `System`, it should reliably alternate with the system's appearance changes (`Light`, `Dark`, `Auto`).

Light|Dark
-|-
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/8219340/203143100-b9d75e7e-6b52-4e5a-ba0f-deb45f7609c2.png">|<img width="1191" alt="image" src="https://user-images.githubusercontent.com/8219340/203143017-4d7d3d94-f9cc-4498-89ed-b875415b0ed5.png">

### Current Behavior

When the OBS UI theme is set to `System`, portions of the UI do not update correctly.

Dark to Light Transition|Light to Dark Transition
-|-
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/8219340/203143056-528c8587-4f52-4176-9d40-4c239a762edc.png">|<img width="1191" alt="image" src="https://user-images.githubusercontent.com/8219340/203142932-24af5ff2-94e8-4356-a3f6-128d455d6198.png">

### Steps to Reproduce

1. Open the OBS settings window
2. Under `General` > `General` > `Theme`, select `System`
    <img width="343" alt="image" src="https://user-images.githubusercontent.com/8219340/203142330-3d0b7978-19e7-465c-8c9f-2b4b0361d9b6.png">
3. Open macOS System Settings (formerly "System Preferences")
4. From `Appearance` > `Appearance`, toggle between `Light`, `Dark`, and `Auto`
    <img width="475" alt="image" src="https://user-images.githubusercontent.com/8219340/203142445-28c89556-36ad-437f-93b9-e06e2bb799eb.png">
5. Notice the incomplete changes to the OBS UI

**Comment by RytoEX** [comment]
This is technically working as designed, as the System Theme was not, and is not currently, designed to reflect changes in the Operating System's theme preferences. "System" Theme was originally just "not Dark Theme".

I believe Qt is still implementing some features to assist with detecting OS theme preference changes. So we may revisit this in the future.
