### ISSUE TITLE
Stream Information Dock Errors

### ISSUE THREAD

**Issue by HiroiSekai** [obsproject/obs-studio#7831]
### Operating System Info

macOS 13

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/ST3QCothZQLVmSFK

### Expected Behavior

When you add some information to change your stream information and click "Done", it should update successfully.

### Current Behavior

<img width="299" alt="Screenshot 2022-11-22 at 4 44 29 AM" src="https://user-images.githubusercontent.com/44986450/203317557-6bb6a1f7-09be-4d1b-be17-fb0c0888f485.png">

Almost always, it just returns a pair of "Failed to update" prompts with no particular reason or explanation as to why. Only think to do is to close the Stream Information dock entirely, reopen it, and input the information again.

### Steps to Reproduce

1. Open the Stream Information dock. Make sure you're logged into Twitter account on OBS.
2. Try to add anything in the two fields and click done.
3. To temporarily patch the error for that one instance, close that dock, reopen it and file the information again. This will work as expected until the next time you stream, where the errors will reoccur and you have to restart the process.
...

**Comment by RytoEX** [comment]
This dock is just a Twitch web page that we load directly. Neither the fields nor the submission action are directly implemented by us. If it's not working, the only thing I can suggest is disconnecting your account, closing OBS, purging your obs-browser plugin cookies, reopening OBS, and reconnecting your Twitch account.

**Comment by HiroiSekai** [comment]
I figured that's what it was, thanks for confirming. It also explains why I can never copy/paste my randomly generated Twitch password from my clipboard.

I followed the steps and it's working for the time being, I'll close this and keep an eye on it for the longer term. Thanks again :)
