### ISSUE TITLE
QSV AV1 - Encoding fails when QSV capable iGPU and Arc GPU are present in the same system

### ISSUE THREAD

**Issue by shenef** [obsproject/obs-studio#7837]
### Operating System Info

Windows 11

### OBS Studio Version

Other

### OBS Studio Version (Other)

commit fceee90 automated build artifact

### OBS Studio Log URL

https://obsproject.com/logs/8A71kjTgtUvMSDd4

### Expected Behavior

Encode an AV1 video stream into a mkv container.

### Current Behavior

Recording failed.

### Steps to Reproduce

1. Open Settings > Output Mode Simple
2. For Recording select High Quality, format MKV and QSV AV1 as the encoder
3. Try to record

### Anything else we should know?

Looking at the log, it seems to have tried encoding with the iGPU of my CPU which does not support AV1 encoding.
However the Arc A770 16GB that is GPU 0 does support AV1 encoding.

**Comment by shenef** [comment]
I have confirmed the encoding works fine if the iGPU is disabled in BIOS.

**Comment by jp9000** [comment]
Annoyingly, I have a system with both Arc dGPU and iGPU, I'm not getting that.

**Comment by shenef** [comment]
I've now upgraded to 29.0 Beta 1 and i was able to replicate the problem multiple times. Encoding never starts when the iGPU is enabled and it can start when the iGPU is disabled.

Now on Beta 1 the recording often does not start on the first try. Log: https://obsproject.com/logs/6gO8nf-lXa-_lymt
Going back to the fceee90 artifact, encoding still starts reliably (if no iGPU is present).

**Comment by jlambert360** [comment]
The problem might be you can't use AV1 when running OBS on your non arc gpu. When running on my 3060ti it gives an error. 
![image](https://user-images.githubusercontent.com/39280243/203607110-dfe1e762-79d9-4d71-9dd2-1d651282465c.png)
If I run OBS on my A380 it works fine though. Guessing this is a bug since you can still use NVENC while OBS is running on a non-nvidia gpu?

**Comment by NyaakoYT** [comment]
Also having a similar issue where QSV AV1 doesn't show up as an option regardless if I set OBS to run on the A380.

Some days ago back in [the obs-qsv11 add AV1](https://github.com/obsproject/obs-studio/pull/7704) some artifact builds were made that allowed QSV AV1 encode to work even with OBS running on a non-ARC GPU. But very recent changes made them completely not work anymore as it used to.

**Comment by RytoEX** [comment]
Thank you for the feedback. For now, we do not need more confirmation that this is occurring.

**Comment by RytoEX** [comment]
Please retest in OBS Studio 29 Beta 3 or newer.

**Comment by NyaakoYT** [comment]
> Please retest in OBS Studio 29 Beta 3 or newer.

Working well.

**Comment by jlambert360** [comment]
Working great for me.

**Comment by shenef** [comment]
29 Beta 3
![image](https://user-images.githubusercontent.com/20268890/208993164-48bf2ef3-dd0a-47c5-8a08-239f3a4bf365.png)
https://obsproject.com/logs/_zrEEb6rC7Lq79QG

After that i went through the Laptop troubleshooting guide (I'm not using a laptop but the log analyzer says it's using the iGPU) and switching OBS from "Let windows decide" to the Arc A770, the error persists.
https://obsproject.com/logs/6Q11x5f65HRWXK8i

Just to confirm, QSV HEVC and H.264 work fine and the iGPU shows additional load. So the problem still seems to be that OBS starts on the iGPU instead of dedicated

**Comment by RytoEX** [comment]
OBS being forced onto the iGPU is a different issue, at the moment. That will be resolved in a later update.

**Comment by shenef** [comment]
I see, then the root cause seems to be what was described in #7917 and this can be closed as a duplicate of that.
