### ISSUE TITLE
obs-websocket submodule deps not available

### ISSUE THREAD

**Issue by justanameok** [obsproject/obs-studio#7853]
### Operating System Info

Windows 10

### OBS Studio Version

28.1.2

### OBS Studio Log URL

no

### OBS Studio Crash Log URL

no

### Expected Behavior

build OBS successfully

### Current Behavior

when i build OBS with 'git clone --recursive https://github.com/obsproject/obs-studio.git'  'CI/build-windows.ps1', i got this:
CMake Error at cmake/Modules/ObsHelpers.cmake:446 (message):
  OBS: obs-websocket submodule deps not available.
Call Stack (most recent call first):
  plugins/obs-websocket/CMakeLists.txt:17 (obs_status)

### Steps to Reproduce

1.git clone --recursive https://github.com/obsproject/obs-studio.git
2.CI/build-windows.ps1
3.
...

### Anything else we should know?

thank you!

**Comment by RytoEX** [comment]
I cannot reproduce this on Windows 10 with Git for Windows 2.38.1.
```
git clone --recursive https://github.com/obsproject/obs-studio.git
[...]
Submodule 'deps/asio' (https://github.com/chriskohlhoff/asio.git) registered for path 'plugins/obs-websocket/deps/asio'
Submodule 'deps/json' (https://github.com/nlohmann/json.git) registered for path 'plugins/obs-websocket/deps/json'
Submodule 'deps/qr' (https://github.com/nayuki/QR-Code-generator.git) registered for path 'plugins/obs-websocket/deps/qr'
Submodule 'deps/websocketpp' (https://github.com/zaphoyd/websocketpp.git) registered for path 'plugins/obs-websocket/deps/websocketpp'
[...]
Submodule path 'plugins/obs-websocket/deps/asio': checked out 'b73dc1d2c0ecb9452a87c26544d7f71e24342df6'
Submodule path 'plugins/obs-websocket/deps/json': checked out 'a34e011e24beece3b69397a03fdc650546f052c3'
Submodule path 'plugins/obs-websocket/deps/qr': checked out '8518684c0f33d004fa93971be2c6a8eca3167d1e'
Submodule path 'plugins/obs-websocket/deps/websocketpp': checked out '56123c87598f8b1dd471be83ca841ceae07f95ba'
```
```
.\CI\build-windows.ps1
```

**Comment by justanameok** [comment]
thank you! i see what the problem is. thank you again!

**Comment by staring** [comment]
Big brother, How can we fix this problem
