### ISSUE TITLE
OBS Studio 29.0 Beta 1 Quicksync AV1 does not show up

### ISSUE THREAD

**Issue by mavericknoob** [obsproject/obs-studio#7856]
### Operating System Info

Windows 11

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.0 Beta 1 

### OBS Studio Log URL

https://obsproject.com/logs/O52W4S2_F4NOm4yi

### Expected Behavior

I expected AV1 hardware encoder to be visible and select-able in setting>output>recording. 

### Current Behavior

Only quicksync options are H.264, AV1 encoder not visible.

### Steps to Reproduce

1.Have Intel Arc A380 (connected to a monitor or not)
2.Launch OBS Studio 29.0 Beta 1
3.Go to settings
4. go to output
5. go to recording
6. Attempt to set Encoder to Quicksync AV1
...

### Anything else we should know?

The Intel Arc GPU in question, is the ASRock Challenger ITX (Intel Arc A380), Driver version 312.0.101.3802 
Have not tried to reproduce in Linux
System Specs:
CPU: AMD Ryzen 9 7950x
MotherBoard: ASUS ROG Crosshair X670E Hero
RAM: G.Skill 32GB Flare X5 6000Mhz
Primary GPU: MSI GeForce RTX 3090 Ti GAMING X TRIO
Secondary GPU: ASRock Challenger ITX (Intel Arc A380)

**Comment by gxalpha** [comment]
There were several fixes after Beta 1, could you confirm whether this is still an issue in OBS 29.0.2?

**Comment by mavericknoob** [comment]
I no longer have the Intel Card, however it was working before I got rid of the card
