### ISSUE TITLE
OBS 29.0.0 beta1 QSV H.264 and H.265 broken

### ISSUE THREAD

**Issue by MCShotty** [obsproject/obs-studio#7858]
### Operating System Info

Windows 11

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.0.0-beta1

### OBS Studio Log URL

https://obsproject.com/logs/AAkDepixCJGLtlZN

### Expected Behavior

Recording starts, no issues.

### Current Behavior

I get 

Starting the output failed. Please check the log for details. 

### Steps to Reproduce

1. Start recording.
2. Get the error.

### Anything else we should know?

System Specifications

i7 12700K 
32GB RAM 
UHD770 driver version 31.0.101.3790
RTX 3090 driver version 526.98

**Comment by MCShotty** [comment]
> There were several fixes after Beta 1, could you confirm whether this is still an issue in OBS 29.0.2?

Really sorry for my extremely late reply but as of 29.0 and 29.1 Beta1 I still get the exact same error. 

https://obsproject.com/logs/bUi0AiF8slNNkL6D

**Comment by RytoEX** [comment]
Are you trying to record in HEVC with LA_ICQ for this latest log? Could you please provide a log file with H.264 as well?

**Comment by MCShotty** [comment]
> Are you trying to record in HEVC with LA_ICQ for this latest log? Could you please provide a log file with H.264 as well?

Yes, every LA_ mode fails on H.265. But LA_ modes in H.264 work flawlessly. 

https://obsproject.com/logs/X5topeBlvBWQbJBN

**Comment by RytoEX** [comment]
I'm fairly certain that this is expected. I don't think QSV HEVC supports lookahead.

**Comment by MCShotty** [comment]
Damn. Okay thanks for the help.

**Comment by RytoEX** [comment]
Closing this per prior comments. The logs and Step To Reproduce don't demonstrate any broken H.264 sessions, and the issue with HEVC was incompatible settings.
