### ISSUE TITLE
Consider supporting Windows Auto Color Management (ACM)

### ISSUE THREAD

**Issue by jiabaoyu** [obsproject/obs-studio#7863]
### Operating System Info

Windows 11

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/iveU88xghDlV4H3j

### Expected Behavior

When [Windows Auto Color Management (ACM)](https://devblogs.microsoft.com/directx/auto-color-management/) enabled, the recorded video should be widegamut with gamma 2.2.

### Current Behavior

The current recording looks dark and dull.

### Steps to Reproduce

1. ensure the OS has been upgraded to windows11 22H2
2. ensure the monitor isn't in HDR mode
3. make a **enableACM.reg** file with content of 
     ```
    Windows Registry Editor Version 5.00
    
    [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers]
    "EnableAcmSupportDeveloperPreview"=dword:00000001
    ```
     And run the reg file.
4. If your monitor is an external one, disconnect and reconnect it to the PC
5. open system setting > Display > Advanced Display, select correct display and turn on Automatically manage color for apps
6. use OBS to recording a video clip.

### Anything else we should know?

Reference and Doc:
https://devblogs.microsoft.com/directx/auto-color-management/
https://learn.microsoft.com/en-us/windows/win32/direct3darticles/high-dynamic-range

Here's two sample recordings:
ACM disabled:https://user-images.githubusercontent.com/12813865/204071643-d6b9041b-e2e6-4cbd-b421-2f288caff3d7.mp4

ACM enabled:https://user-images.githubusercontent.com/12813865/204071647-8efd0e2c-7b6b-4b13-9976-faaca9c1f681.mp4

**Comment by WizardCM** [comment]
Please use the [Ideas site](https://ideas.obsproject.com/) for suggestions. We only use GitHub Issues for bug reports.
