### ISSUE TITLE
SRT Stream does not report any dropped frames in the OBS Stats

### ISSUE THREAD

**Issue by saltarob** [obsproject/obs-studio#7865]
### Operating System Info

macOS 12

### OBS Studio Version

29.0.0-beta1

### OBS Studio Log URL

https://obsproject.com/logs/TCc7NGQmtQfB0jHO

### Expected Behavior

Expecting any dropped frames or bandwidth issues with the SRT stream to be reported in the OBS Stats.

### Current Behavior

Stats doesn't show any dropped frame and reports the full encoded stream bandwidth which is handed over to the SRT Link regardless the actual upload bandwidth. 

### Steps to Reproduce

1. Set up an SRT Stream with 4 Mbps
2. Connect OBS with an internet connection which has only 2 Mbps 
3. Start the stream and see if OBS Stats is reporting the missing 2 Mbps of bandwidth
...

**Comment by pkviet** [comment]
The frame drops are not implemented in srt.
I'm not sure it would work well with srt because srt has its own mechanisms to deal with network issues, namely ARQ.
Srt resends packets.

**Comment by pkviet** [comment]
So closing. I might implement dynamic bitrate instead.

**Comment by saltarob** [comment]
Thank you. Is there any way or any plugin to monitor the srt stream?

**Comment by pkviet** [comment]
Start obs with --verbose argument. You'll get stats for rtt and link bandwidth every minute.
Plus detailled stats at the end of your stream.

**Comment by saltarob** [comment]
> So closing. I might implement dynamic bitrate instead.

What does that mean in regards to srt?

**Comment by saltarob** [comment]
> Start obs with --verbose argument. You'll get stats for rtt and link bandwidth every minute. Plus detailled stats at the end of your stream.

Great, thank you. Sorry, how do I start obs with --verbose argument on a mac?

**Comment by saltarob** [comment]
I think I started it with --verbose argument from terminal. Do you mean that log entries?
`21:52:53.086: [obs-ffmpeg mpegts muxer / libsrt]: RTT [118.96 ms], Link Bandwidth [76.7 Mbps]
21:53:53.098: [obs-ffmpeg mpegts muxer / libsrt]: RTT [112.13 ms], Link Bandwidth [61.8 Mbps]`

But they are not very useful and maybe even wrong. I only have a link bandwidth of 10 Mbps. From where are the 76.7 Mbps coming?

**Comment by pkviet** [comment]
Yes
