### ISSUE TITLE
NVIDIA on Wayland is not supported

### ISSUE THREAD

**Issue by Peque** [obsproject/obs-studio#7866]
### Operating System Info

Other

### Other OS

Linux (any)

### OBS Studio Version

Other

### OBS Studio Version (Other)

Any

### OBS Studio Log URL

N/A

### Expected Behavior

NVIDIA on Wayland is not supported, and any new issues related to NVIDIA+Wayland will be closed (i.e.: https://github.com/obsproject/obs-studio/issues/6803, https://github.com/obsproject/obs-studio/issues/6740, https://github.com/obsproject/obs-studio/issues/6572, ...).

However, there is one open issue to track any possible future updates on this matter. When a NVIDIA+Wayland issue is closed, a link to this general issue is shared so the user can subscribe and be notified if/when this changes.

### Current Behavior

NVIDIA on Wayland is not supported, but there is no open issue to track progress on this. Even if it is not planned in the short term, it would be great to have one single issue open so that anybody interested in this can subscribe and be notified if/when this changes.

The fact that there is no open issue related to Wayland+NVIDIA may result in more users creating new unnecessary issues without noticing this (i.e.: https://github.com/obsproject/obs-studio/issues/6803, https://github.com/obsproject/obs-studio/issues/6740, https://github.com/obsproject/obs-studio/issues/6572, ...).

### Steps to Reproduce

1. Search for open issues related to NVIDIA+Wayland
2. None is open clearly stating that NVIDIA+Wayland is not supported
3. You need to look for closed issues to understand this is actually not supported at this point

**Comment by kkartaltepe** [comment]
> it would be great to have one single issue open so that anybody interested in this can subscribe and be notified if/when this changes.

The changes to support nvidia are already in place with v28. But to our knowledge no xdg-desktop-portal implementation actually supports proper buffer negotiation. So there is nothing we can track here. If you feel things should work please file a bug against your compositor's implementation of the portal.

Since we are not aware of anyone supporting the required infrastructure (xdg-desktop-portal implementations), we cannot make any claims to support nvidia.

If anyone wants to open a bug relating to nvidia on wayland please provide a link to a bug opened against your compositor or xdg-desktop-portal implementation where they claim the issue is in OBS first.

**Comment by Peque** [comment]
@kkartaltepe Thanks for your reply.

I thought it could be of good help to have an issue where that information could be shared by OBS users/developers so that others coming in here (and not knowing about the state of support when it comes to xdg-desktop-portal, xdg-desktop-portal-gnome and mutter) could easily understand why this was blocked and perhaps find useful links to the projects blocking this so that they could go there and subscribe/comment/help.

Otherwise for me as a user it feels hard to understand what is the current state, which are the current blockers and who is working on this.

Open issues have higher visibility than closed ones and perhaps that helped you avoiding unnecessary new issues reported by users not knowing that Wayland+NVIDIA is not supported (and that this support is currently not blocked by OBS in any means).

**Comment by kkartaltepe** [comment]
> I thought it could be of good help to have an issue where that information could be shared by OBS users/developers so that others coming in here (and not knowing about the state of support when it comes to xdg-desktop-portal, xdg-desktop-portal-gnome and mutter) could easily understand why this was blocked and perhaps find useful links to the projects blocking this so that they could go there and subscribe/comment/help.

This is what our forums and discord are for, feel free to start a thread on the forums tracking the progress of all the compositors and their implementations and directing people there. But this is not the purpose of our issue tracker. There is nothing to be done in obs right now for nvidia so there is no need to track anything in our issues. If compositors find we need to change something then we can open a bug for that change with a reference to the compositors discussion.

> Otherwise for me as a user it feels hard to understand what is the current state, which are the current blockers and who is working on this.

Thats why nvidia is unsupported.

**Comment by Peque** [comment]
In case anybody wants to share more information/details or simply track this issue: https://gitlab.gnome.org/GNOME/mutter/-/issues/2532

**Comment by uncomfyhalomacro** [comment]
Hello. This issue may be closed but you just need to enable NVENC with a udev rule so it won't matter if you are on Wayland. The Arch Wiki tells you how to do it :) https://wiki.archlinux.org/title/NVIDIA#Hardware_accelerated_video_encoding_with_NVENC

![image](https://user-images.githubusercontent.com/66054069/218781093-70434c09-8364-4b2c-b6ef-4663fd7c5390.png)
