### ISSUE TITLE
OBS studio

### ISSUE THREAD

**Issue by Jason-Guo2008** [obsproject/obs-studio#7868]
### Operating System Info

Windows 11

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/RYFDjj7tFre3H8pZ

### Expected Behavior

I turned on the virtual camera and set up two scenes
![image](https://user-images.githubusercontent.com/76830748/204182665-e26e7b32-0d35-4225-b4f5-012ee925300d.png)
My software connected to the virtual camera, and I decided to change the scene
![image](https://user-images.githubusercontent.com/76830748/204183157-c09d6ea3-685e-455c-b733-6917fe688678.png)
It should look like this
![image](https://user-images.githubusercontent.com/76830748/204183237-15972446-bea0-417b-818f-afffb5a8d34c.png)

### Current Behavior

However, the software does not switch scenarios
![image](https://user-images.githubusercontent.com/76830748/204183362-8b3581ab-3e3d-4958-a640-99802266aaef.png)
But I've switched over
![image](https://user-images.githubusercontent.com/76830748/204183486-6fb89fe4-a404-4033-a3e5-17e4890af220.png)

### Steps to Reproduce

1.Open OBS studio
2.Set up two scenarios
3.Turn on the virtual camera
4.Open an application that requires a camera (such as a conference application) and connect the virtual camera
5.Try toggle the scene in OBS studio and you'll see that the camera in the software doesn't change

### Anything else we should know?

I am a Chinese,so I'm not good at English.Please understand!
My e-mail:562732650@qq.com or jason.Guohaiyue@outlook.com

**Comment by Jason-Guo2008** [comment]
QwQ

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by Jason-Guo2008** [comment]
emm……But this is a bug

**Comment by RytoEX** [comment]
When Studio Mode is enabled (as indicate in several places in the log), the scene output by the Virtual Camera by default does not change unless you actually transition the scene. While OBS will log "User switched to scene" each time you select a new scene to preview (the left side of the OBS window), that does not indicate that it has transitioned in the program view (the right side of the OBS window). I would suspect the scene has not actually changed. As @Fenrirthviti indicated, this can be more easily determined in our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/).

**Comment by Jason-Guo2008** [comment]
Thanks for help!!!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "obsproject/obs-studio"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月28日(星期一) 下午2:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [obsproject/obs-studio] OBS studio (Issue #7868)





 
When Studio Mode is enabled (as indicate in several places in the log), the scene output by the Virtual Camera by default does not change unless you actually transition the scene. While OBS will log "User switched to scene" each time you select a new scene to preview (the left side of the OBS window), that does not indicate that it has transitioned in the program view (the right side of the OBS window). I would suspect the scene has not actually changed. As @Fenrirthviti indicated, this can be more easily determined in our forums or Discord.
