### ISSUE TITLE
Bug in debian's preview is no active and themes don't refresh

### ISSUE THREAD

**Issue by Hanter492** [obsproject/obs-studio#7872]
### Operating System Info

Other

### Other OS

Kali 2022.03 -> debian testing

### OBS Studio Version

Other

### OBS Studio Version (Other)

http://ftp.debian.org/debian/pool/main/o/obs-studio/obs-studio_28.0.1+dfsg1-3_amd64.deb

### OBS Studio Log URL

https://obsproject.com/logs/XOof6cRW9UTss5UN

### Expected Behavior

I wish the creators knew the problem. And information on how to fix it. (you'd also need to see if the latest version works well on debian). Loading the view after opening the view. Fix in refreshing themes on app startup (I think the styles are destroyed by customizing the colors and icons of the kali system.).

### Current Behavior

Themes do not set up properly and after restarting they need to be refreshed. But a real error appears after minimizing the application. The preview disappears and it cannot be recovered. I use OBS and checked the latest versions on Ubuntu and Debian11 (in this in official repository is a v26.1.2 I can't install v28). This problem I see only in Kali.
I would be grateful for the information.

### Steps to Reproduce

1. Install the latest version of kali linux on VirtualBox.
2. `sudo apt update -y`
3. `sudo apt install obs-studio`
4. View errors when minimized. See bad appearance after application restart.

### Anything else we should know?

I know you don't support kali linux but I think these bugs can help to improve the program. (OBS is great)

**Comment by kkartaltepe** [comment]
We dont support debian packages, please replicate with the latest release. I've tested this and cannot replicate with the latest release.

**Comment by gxalpha** [comment]
Closing as there has been no response to the comment above since November.
