### ISSUE TITLE
Browser source audio stays active when hidden

### ISSUE THREAD

**Issue by Phwanky** [obsproject/obs-studio#7878]
### Operating System Info

macOS 13

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/DlkFOx-71f8xuWXi

### Expected Behavior

When the scene containing the browser source is hidden, the browser source and its audio should be inactive.

### Current Behavior

Sometimes, the audio from the browser source stays active when hidding its scene.

### Steps to Reproduce

1. Import the scene collection into OBS
2. Configure a Stream Deck or Touch Portal software to switch the scenes as shown in the "Toggle A" and "Toggle B"
3. Switch several times between "Toggle A" and "Toggle B"
4. You can check the video provided where you can see the behaviour
[Bug Browser Source.zip](https://github.com/obsproject/obs-studio/files/10126320/Bug.Browser.Source.zip)

### Anything else we should know?

It seems not to happen when we put a delay of 500 ms between the showing/hidding of scenes.

**Comment by Go1den** [comment]
I am experiencing this problem as well on Windows 10. obs-browser-page.exe stays open even if I am on a scene that has no browser sources, and even if I do not have that browser element added in my audio mixer on ANY scene.

**Comment by Warchamp7** [comment]
This is the case when the browser is outputting to the audio device directly, as the page has no understanding of OBS' visibility state.

If you want the browser source's audio to be routed through OBS and follow it's visibility state, please enable **Control audio via OBS** in the browser source settings.

This will require you to also set up audio monitoring for the source to be able to hear it, much like media sources.
