### ISSUE TITLE
Video preview not visible in obs.

### ISSUE THREAD

**Issue by zookeeper76** [obsproject/obs-studio#7882]
### Operating System Info

Other

### Other OS

Linux Fedora Silverblue 37

### OBS Studio Version

28.1.2

### OBS Studio Log URL

Can't get to it, OBS is now crashing

### Expected Behavior

When a video source is selected, I expect to have the live video feed previewed in OBS. This use to work until a few days ago when it stopped working for some reason.

### Current Behavior

When a source is selected, let's say you open a live video stream in Firefox, you open OBS, select a scene and capture that browser window using Pipewire. Right now, the video preview is not working. If the video is playing in the browser you would expect to see the exact same video in the OBS preview area. This is not the case. What you see right now is a picture of the video being played but it is paused. The only way to get to see the video preview in OBS is to hit the Super Key "Windows Key" which has for effect to show the apps switcher in Gnome. At this point the OBS video preview does work while minimized but only then.

### Steps to Reproduce

1. Open Firefox, play any random YouTube video in full screen, I'm in 1080P right now.
2. Open OBS "Flatpak" version and capture the browser window using Pipewire.
3. The OBS preview window is frozen. To view the video preview playing normally in OBS, hit the Windows Key on your keyboard to view the app switcher which has for effect to now enable the video preview as it should be displayed.
...

### Anything else we should know?

And by the way, OBS now crashed on Fedora Silverblue 37 from time to time...

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
