### ISSUE TITLE
No sound is recorded while recording ANYTHING.

### ISSUE THREAD

**Issue by randomsomeone69** [obsproject/obs-studio#7883]
### Operating System Info

Windows 10

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/WOdBHCbjkpmKa5fr

### Expected Behavior

When I'm recording anything (ex. Mario Party 8 title screen), there should be sound. 

### Current Behavior

No sound are recorded.

### Steps to Reproduce

1. Start OBS
2. Start a Recording.

### Anything else we should know?

Sometimes, Windows will report that an audio is unplugged while it's still plugged.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
