### ISSUE TITLE
Linux obs segfault on launch

### ISSUE THREAD

**Issue by VictorKruger** [obsproject/obs-studio#7889]
### Operating System Info

Other

### Other OS

Linux Mint 21

### OBS Studio Version

28.1.2

### OBS Studio Log URL

N/A

### OBS Studio Crash Log URL

N/A

### Expected Behavior

I would expect the program to launch without error

### Current Behavior

A fresh install of obs 28.1.2 will let you run obs one time, giving you setup wizard.  after completing the setup wizard and closing obs, all further attempted launches will end in a segfault.

### Steps to Reproduce

1. run obs via gui or terminal

### Anything else we should know?

[obs 28.1.2 segfault.txt](https://github.com/obsproject/obs-studio/files/10145581/obs.28.1.2.segfault.txt)

**Comment by WizardCM** [comment]
Please provide a gdb backtrace.

**Comment by VictorKruger** [comment]
Attach is the gdb log.
[BackTrace.txt](https://github.com/obsproject/obs-studio/files/10146807/BackTrace.txt)

**Comment by kkartaltepe** [comment]
It looks like your system is mixing qt5 and qt6 components, qt6 does not check layouts versions and will crash in that case. File a bug to qt I guess but its probably better to figure out what qt extension you have that is saving garbage or what is using qt5. qt5ct is a common cause.

**Comment by VictorKruger** [comment]
Thank you for the quick solution. I was able to remove qt5ct without issue and OBS works again.
