### ISSUE TITLE
Compilation error obs-browser submodule not avaliable

### ISSUE THREAD

**Issue by VictorKruger** [obsproject/obs-studio#7890]
### Operating System Info

Other

### Other OS

Linux Mint 21

### OBS Studio Version

28.1.2

### OBS Studio Log URL

N/A

### OBS Studio Crash Log URL

N/A

### Expected Behavior

Compile clean 

### Current Behavior

CMake Error at cmake/Modules/ObsHelpers.cmake:446 (message):
  OBS: obs-browser submodule not available.
Call Stack (most recent call first):
  plugins/CMakeLists.txt:11 (obs_status)
  plugins/CMakeLists.txt:64 (check_obs_browser)

### Steps to Reproduce

1. git clone --branch 28.1.2 https://github.com/obsproject/obs-studio.git
2. CI/build-linux.sh --build-dir ./build ---DCMAKE_BUILD_TYPE=debug

### Anything else we should know?

[CMakeOutput.log](https://github.com/obsproject/obs-studio/files/10145889/CMakeOutput.log)
[OBS compile error.txt](https://github.com/obsproject/obs-studio/files/10145901/OBS.compile.error.txt)

Trying to compile to further investigate obsproject/obs-studio#7889

**Comment by WizardCM** [comment]
Clone recursively, per our [build instructions](https://github.com/obsproject/obs-studio/wiki/build-instructions-for-linux#build-procedure).
