### ISSUE TITLE
OBS Crashes immediately after opening

### ISSUE THREAD

**Issue by CBlasek** [obsproject/obs-studio#7896]
### Operating System Info

Windows 11

### OBS Studio Version

29.0.0-beta1

### OBS Studio Version (Other)

28.1

### OBS Studio Log URL

https://pastebin.com/ubuXBvve

### Expected Behavior

Bein able to open OBS

### Current Behavior

When opening OBS, I receive an error and OBS closes with error message on Pastebin

### Steps to Reproduce

1. Open OBS
2.
3.
...

**Comment by gxalpha** [comment]
This is a crash within the StreamFX plugin. Please report it to StreamFX instead.
