### ISSUE TITLE
[OBS 29-beta2] VST plugin window contents don't update unless window is dragged

### ISSUE THREAD

**Issue by ntoff** [obsproject/obs-studio#7898]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

OBS 29.0.0-beta2 (64-bit, windows)

### OBS Studio Log URL

https://obsproject.com/logs/orH2WobLULqK1obo

### Expected Behavior

That the contents of the VST plugin window would update.

### Current Behavior

Plugin window contents don't update unless you click on the window and drag it around.

### Steps to Reproduce

1. Install the OTT plugin from xfer https://xferrecords.com/freeware
2. Add the OTT_64 plugin to the desktop audio device
3. Play some audio
4. Open the plugin's panel and observe none of the meters in the plugin window move, and adjusting the dials also appears to do nothing until you drag the window.

### Anything else we should know?

I suspect maybe this is an issue with the plugin itself, as the other VST plugins I've tried **do** update their windows correctly. Though I don't know why it would be the case that it doesn't work in just obs (the plugin works in vsthost). So I figured I'd report anyway.

The plugin works otherwise, it's just that the UI doesn't update.

**Comment by Fenrirthviti** [comment]
Does this happen in previous versions of OBS, or is this new to 29 beta? Want to be sure we're looking at the correct scope here.

**Comment by ntoff** [comment]
I don't generally use many VST filters inside obs so only just discovered the issue today in the beta.

Just tested and:
v28.1.2 = same behaviour as v29b2, only updates when window is dragged around
v27.2.4 = OTT window doesn't update at all even when dragged

Also may or may not be worth noting in windows I have "show window contents while dragging" turned on
![image](https://user-images.githubusercontent.com/9030085/205915921-d4c82c1e-cc7f-4e39-b4c6-16389cf8b8b8.png)

**Comment by Fenrirthviti** [comment]
Thanks! I suspected this was not a new issue, and might be something with the plugin itself. We'll take a look as time allows.

**Comment by Fenrirthviti** [comment]
We're fairly sure this is an issue with the VST itself, as we don't manage the VST window contents.

Closing as there hasn't been any updates or new information on our end, and it seems specific to this VST only as far as we can tell.
