### ISSUE TITLE
Importer does not clear new_socket_loop_enabled on non-windows platforms

### ISSUE THREAD

**Issue by kkartaltepe** [obsproject/obs-studio#7900]
### Operating System Info

Ubuntu 22.10

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/CiOvHUK7vychoYWH

### Expected Behavior

We should clear this flag if its set when importing windows setups, if not users will be unable to stream because the output does not fallback it simply errors out on non-windows platforms. See `plugins/obs-outputs/rtmp-stream.c:938`

### Current Behavior

The flag remains set, users cannot stream nor can they turn the flag off in the UI as this flag is hidden on non-windows platforms.

### Steps to Reproduce

1. Set the flag for new networking path in windows
2. Export profile
3. Import profile into linux
4. Attempt a stream

### Anything else we should know?

User reported, I assume this was through the importer and not manually copied. If this is actually handled via the importer I just missed it and we can close this.

**Comment by RytoEX** [comment]
I don't think the importer does anything with profiles. It just works on scene collections.

**Comment by kkartaltepe** [comment]
> I don't think the importer does anything with profiles. It just works on scene collections.

Ah, well maybe in that case we should just add a fallback in the output/ui code if thats easier then extending importers. Either way seems reasonable.

**Comment by RytoEX** [comment]
> > I don't think the importer does anything with profiles. It just works on scene collections.
> 
> Ah, well maybe in that case we should just add a fallback in the output/ui code if thats easier then extending importers. Either way seems reasonable.

To be clear, the "Scene Collection Importer" (the "importer" that we often refer to) only applies to Scene Collection data when importing a Scene Collection JSON file. The "Profile Importer" isn't really an importer at all. It just invokes a folder open dialog, and the selected Profile folder (with INI file) is copied to the obs-studio AppData directory. "Importing" a profile is equivalent to manually copying the folder between systems. One menu item is not related to the other. They share no code, and the data files for each are separate formats (Scene Collections are JSON, Profiles are INI). I wouldn't call that extending so much as "writing a whole new feature to convert Profiles between platforms".

In any case, glancing at the code, it does seem that we delete the UI elements for this on non-Windows platforms, which puts non-Windows users copying profiles from Windows systems in a bind. We do, apparently, override this if RTMPS is being used. We could probably override it to disabled on non-Windows platforms.
