### ISSUE TITLE
Cannot enable preview in studio mode after minimizing and restoring the window

### ISSUE THREAD

**Issue by rolandixor** [obsproject/obs-studio#7901]
### Operating System Info

Ubuntu 22.10

### OBS Studio Version

Other

### OBS Studio Version (Other)

28.1.11-3 (64 bit)

### OBS Studio Log URL

https://obsproject.com/logs/ahtIfsjsYJc4M4iD

### Expected Behavior

The preview should be shown at all times, and re-enabled if you click "enable preview". Even right-clicking and clicking "Enable Preview" in the menu does nothing.

### Current Behavior

The preview is disabled if you minimize the window and restore it, or switch to another application and back to OBS Studio.

### Steps to Reproduce

1. Minimize the window or switch to another application.
2. Restore OBS Studio or switch back to OBS Studio.
3.
...

### Anything else we should know?

Nothing that I can think of.

**Comment by kkartaltepe** [comment]
We are still looking for better reproduction steps, no one has been able to reproduce this consistently on a developer machine.

**Comment by rolandixor** [comment]
I can't think of any particulars that trigger it, but I'll see if I can track it down further.

**Comment by fzwoch** [comment]
Another user on the Forums:

https://obsproject.com/forum/threads/cant-enable-preview.162840/

They attached a video.

**Comment by Fenrirthviti** [comment]
This appears to have been solved in newer versions of OBS, according to the thread posted there. If this is still an issue, please provide further details on how to reliably reproduce, and we can reopen. As it stands, we cannot, and this might be an environment issue or other dep issue we don't have control over.
