### ISSUE TITLE
Simple recording mode replay buffer "Cannot estimate memory usage. Please set maximum memory limit"

### ISSUE THREAD

**Issue by ntoff** [obsproject/obs-studio#7903]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

OBS 29.0.0-beta2 (64-bit, windows)

### OBS Studio Log URL

https://obsproject.com/logs/K6XMtX3HxcUdYc-v

### Expected Behavior

Replay buffer estimated memory usage would either tell me one of two things:

* the amount of memory it thinks it'll use, or
*  the recording mode is CQP/CRF and that memory usage will vary based on scene contents and can't be calculated accurately.

### Current Behavior

Replay buffer memory usage calculation warns me to set a maximum memory limit, despite having set one.

![image](https://user-images.githubusercontent.com/9030085/206432661-08134c90-0b63-45da-955c-731a9fe8b6d1.png)

### Steps to Reproduce

1. Download obs
2. Run in portable mode, auto config wizard selected recording only mode
3. Change replay buffer memory limit / time in the simple output mode
4. Observe the notification that I must set a memory limit, despite having one set.

### Anything else we should know?

More a UI string / description error I think. I suspect this is because it's using CQP mode and not a fixed bitrate mode for recording, and *that* is the reason why memory usage can't be calculated? And not the lack of a maximum memory limit?

Changing to advanced output + CBR allows the memory usage to be calculated, but going advanced + CRF also gives the warning about setting a maximum memory limit, despite there being one set.

Behaviour is also present in obs v28 as well.

**Comment by WizardCM** [comment]
It is not a warning, it is a descriptive text based on the output mode. This is intentional.

**Comment by Fenrirthviti** [comment]
The warning could be changed to read something like "Maximum memory limit will be used." instead of asking the user to take action on a message that will not update even if they take said action. This is a fair complaint, albeit minor.
