### ISSUE TITLE
Pipewire screencast only receives black image

### ISSUE THREAD

**Issue by valeth** [obsproject/obs-studio#7904]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/rKQKE5-Jv3ju_55a

### Expected Behavior

Screen capture and window capture show the captured screen/window.

### Current Behavior

Output of capture stays black

### Steps to Reproduce

1. Create a new Pipewire capture
2. Select any screen/window from the dialog
3. Get black capture area and errors in log

### Anything else we should know?

Capture seems to work just fine on my laptop with runs an old Intel iGPU (i7-2670QM).
Also worked fine on my old desktop system which ran an AMD Radeon RX 480.
The problem only started with the Ryzen 7600X iGPU.

I tested all of them with the official Flatpak, only change I made with Flatseal are some paths to resource files which didn't affect the other two GPUs mentioned.

So far I'm not sure if that's a OBS, Pipewire, or KDE issue.

**Comment by fzwoch** [comment]
> 13:59:58.866: Loading up OpenGL on adapter Mesa/X.org llvmpipe (LLVM 12.0.1, 256 bits)

OBS runs in software emulation. It may very well be that the GPU is not supported by the current kernel and installed Mesa version.

**Comment by valeth** [comment]
This seems to be completely fixed in the `29.0.0-beta1` Flatpak release

**Comment by tytan652** [comment]
So fixed by the runtime bump between 6.3 (21.08) and 6.4 (28.08).
