### ISSUE TITLE
OBS does not capture screen in gnome (wayland and pipewire)

### ISSUE THREAD

**Issue by rV4nxZ** [obsproject/obs-studio#7905]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/AuM0LK7f8tgM4Kdc

### Expected Behavior

Screen sharing preview correctly in OBS

### Current Behavior

OBS preview is black and only audio is captured (pulseaudio)

### Steps to Reproduce

1. Add screen capture (pipewire)
2. Select default display (integrated screen)
3. In the preview screen adding the screen capture does not show the screen
4. Adding it and it does not show in preview panel
...

**Comment by kkartaltepe** [comment]
Screencapture is successfully established but the compositor is sending OBS a pause signal. File a bug against your compositor if you think this is incorrect and it should be sending OBS frames.
