### ISSUE TITLE
OBS Virtual Camera does not work with Zoom

### ISSUE THREAD

**Issue by leoplaw** [obsproject/obs-studio#7907]
### Operating System Info

Other

### Other OS

Linux OpenSuse Tumbleweed

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/fd8amazw8nJn8KCl

### Expected Behavior

Start OBS
Start OBS Virtual Camera
Start Zoom
Start Zoom Meeting with OBS Virtual Camera
Expect to see OBS Virtual Camera output in Zoom

### Current Behavior

Blank Zoom window when using OBS Virtual Camera

### Steps to Reproduce

Start OBS
Start OBS Virtual Camera
Start Zoom
Start Zoom Meeting with OBS Virtual Camera
Expect to see OBS Virtual Camera output in Zoom, but see blank Zoom Window

### Anything else we should know?

OBS Virtual Camera works with Skype.

Zoom Version: 5.12.9 (367)
OBS: 28.1.2 (64 bit)

Operating System: openSUSE Tumbleweed 20221122
KDE Plasma Version: 5.26.3
KDE Frameworks Version: 5.100.0
Qt Version: 5.15.7
Kernel Version: 6.0.9-3.g059900f-default (64-bit)
Graphics Platform: X11
Processors: 32 × Intel® Xeon® CPU E5-2690 0 @ 2.90GHz
Memory: 62.7 GiB of RAM
Graphics Processor: AMD CEDAR
Manufacturer: Intel
Product Name: X79

**Comment by kkartaltepe** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
