### ISSUE TITLE
Lossless libx264rgb outputs green video with video artifacts

### ISSUE THREAD

**Issue by spacebanana420** [obsproject/obs-studio#7923]
### Operating System Info

Other

### Other OS

Debian Linux (bookworm)

### OBS Studio Version

Other

### OBS Studio Version (Other)

28.0.1

### OBS Studio Log URL

https://obsproject.com/logs/s1XM_VrKxXLsfeOv

### Expected Behavior

Using x264 and FFmpeg, the video output is supposed to be a lossless RGB H.264 encode without any visual errors, as it has been on previous versions

### Current Behavior

The video output is mostly green and has visual artifacts, besides poor performance on playback despite the encoding settings being tuned for playback and editing performance
Media players might also not be able to playback the video, despite supporting RGB and lossless H.264 decoding

### Steps to Reproduce

- Change recording output mode to FFmpeg
- Change video encoder to libx264rgb
- Set the following video encoding parameters: `preset=veryfast crf=0 tune=fastdecode bf=0`
- Set the keyframe interval to 1 frame
- Change pixel format to RGB (using limited gamma and sRGB color space)
- Record your entire screen

### Anything else we should know?

OBS version used is 28.0.1 from Debian's testing/bookworm repository (package version 28.0.1+dfsg1-3)
I'm using OBS under x11
Audio encoding settings, x264 preset and video container don't matter to reproduce the bug

**Comment by pkviet** [comment]
we don't support the use of the ffmpeg custom recording output. I'm not surprised that x264rgb doesn't work. Closing.

**Comment by PatTheMav** [comment]
For clarification: The app supports custom outputs on a technical level, but we do not give support for any issues that might arise out of that - if you use custom outputs you are considered an ‘expert’ that knows that they are doing.
