### ISSUE TITLE
Crash when using x264 streaming. Error code c0000005

### ISSUE THREAD

**Issue by shoucandanghehe** [obsproject/obs-studio#7928]
### Operating System Info

Windows 11

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/_Zo7PT_0dqxuZHwX

### OBS Studio Crash Log URL

https://obsproject.com/logs/Lbo37EplQSJWebLj

### Expected Behavior

Can be used normally with x264 for live streaming. It won't cause obs to crash.

### Current Behavior

When I use x264 for live streaming, obs crashes randomly.

### Steps to Reproduce

1.open obs
2.Start Streaming
3.wait
4.crash

### Anything else we should know?

I started obs with the integrated graphics because I wanted to use intel's quicksync, my discrete graphics card is too weak, but when I use quicksync it throws an error: Encoder error when streaming.
I don't know if the two are related, but they both prevent me from streaming properly :XD

**Comment by Fenrirthviti** [comment]
Crashes that deep in to x264 are usually an indicator of an unstable overclock, failing ram, or other hardware instability.
