### ISSUE TITLE
Failed to start screencasting. Failed to connect to PiperWire context. OBS does not record screen on wayland kde.

### ISSUE THREAD

**Issue by Giger22** [obsproject/obs-studio#7937]
### Operating System Info

Other

### Other OS

Artix Linux OpenRC

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/VvZo7EpMRqMK97BD

### Expected Behavior

Screen recording without issues.

### Current Behavior

Audio works, also on xorg screen capture works but not on wayland. Only black screen.

### Steps to Reproduce

1. Add Source
2. Screen capture or windows capture (pipewire)
3. Select monitor or other and click share.
...

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
