### ISSUE TITLE
HDR content recorded improperly under macOS

### ISSUE THREAD

**Issue by TensorP7** [obsproject/obs-studio#7944]
### Operating System Info

macOS 13

### OBS Studio Version

29.0.0-beta2

### OBS Studio Log URL

https://obsproject.com/logs/V6v4_BBn7oo5x_uU

### Expected Behavior

I am using a M1 MacBook Pro with XDR display. The screen is set to HDR Video mode. I tried both the Rec.2100 PQ and Rec.2100 HLG with Apple VT HEVC encoder and I hoped to capture the HDR content on the monitor. 

### Current Behavior

In the recored video, the system UIs are in HDR but all the HDR content played through the display is not correctly tone mapped, so that HDR content in DaVinci resolve, YouTube or just a local quicktime player are all blown out.

### Steps to Reproduce

1. Play any HDR content using a MacBook
2. Try to capture the screen using Rec.2100(PQ or HLG) P101 4:2:0 10bit with Apple VT HEVC encoder

**Comment by gxalpha** [comment]
This is expected. The capture API does not let us capture HDR content properly.

**Comment by PatTheMav** [comment]
Please open a Feedback with Apple to request this feature - we already informed Apple about this being requested by users informally, but it is helpful if people would also report this as Feedback to Apple directly:

https://feedbackassistant.apple.com/

**Comment by TensorP7** [comment]
> Please open a Feedback with Apple to request this feature - we already informed Apple about this being requested by users informally, but it is helpful if people would also report this as Feedback to Apple directly:
> 
> https://feedbackassistant.apple.com/

Thank you for replying me and all the efforts you have made. I will try to feed back the problem to Apple.
