### ISSUE TITLE
Installation fatal error message at end of installation.

### ISSUE THREAD

**Issue by ninoupte7** [obsproject/obs-studio#7945]
### Operating System Info

Other

### Other OS

windows 7.1

### OBS Studio Version

28.1.2

### OBS Studio Log URL

I have no idea how to find this log.

### OBS Studio Crash Log URL

I have no idea how to find this log.

### Expected Behavior

I expected the installer to successfully install OBS Studio.

### Current Behavior

I just downloaded and ran OBS installer without any changes to defaults. OBS added a short cut to my desktop. Chose open OBS at end of installation. Recieved crash error message from OBS installer. I've attached the MS Snipper jpg screen image.

![OBS Instal ErrMsg (fatal)](https://user-images.githubusercontent.com/121059835/208512899-c4a88a8a-81c1-464c-b064-05b09b2d6a15.JPG)

If the current OBS does not run with my dell computer with OS Win7.1 Pro x64, where can I get the version which will run on my system?
Thanks. 
![OBS Instal ErrMsg (fatal)](https://user-images.githubusercontent.com/121059835/208513858-841ba7a6-f6b5-459f-a897-03ff3ebe17c3.JPG)

### Steps to Reproduce

1.Steps are provided above.
2.
3.
...

**Comment by kkartaltepe** [comment]
https://obsproject.com/wiki/System-Requirements Update to windows 10 if you want to continue to use obs.
