### ISSUE TITLE
It does not work with NVENC in OBS version 28.1.2

### ISSUE THREAD

**Issue by LJLonGithub** [obsproject/obs-studio#7957]
### Operating System Info

Windows 10

### OBS Studio Version

28.1.2

### OBS Studio Log URL

http://ljldownload.cn/bugreport/log.txt

### Expected Behavior

using OBS  to record video normally.

### Current Behavior

Give me a text 
![text picture](http://ljldownload.cn/bugreport/bug.png "text")
![text picture in EN](http://ljldownload.cn/bugreport/bugEN.png "text in EN")

### Steps to Reproduce

1.Click"Files"-"Settings"
2.Click"Out Put"
3.Choose"Harware'NVENC''" in EnCoder
4.Click"OK"
5.cCick"Start Recording"

### Anything else we should know?

My GPU is Nvidia Geforce RT 730
I think I made bug because my GPU is so old. But to day I try to use OBS 29.0 Beta 3.The OBS work very prefect.Please tell me what happen.

**Comment by LJLonGithub** [comment]
I am a Chinese user.So the log have some Chinese.
I often use OBS to recordiing Desktop.

**Comment by Penwy** [comment]
what happens is that your GPU is too old to work with the multipass mode that's set as default in obs 28.1.
As you noticed, in obs 29, obs automatically detect if it's the case and makes it work.
If you need further support, you should use the discord : http://discord.gg/obsproject

**Comment by LJLonGithub** [comment]
> what happens is that your GPU is too old to work with the multipass mode that's set as default in obs 28.1. As you noticed, in obs 29, obs automatically detect if it's the case and makes it work. If you need further support, you should use the discord : http://discord.gg/obsproject

Thank you for your helping! I got it!

**Comment by tt2468** [comment]
The GT 730 GPU does not support NVENC.
