### ISSUE TITLE
Abnormally high systemd GPU usage when recording is started in Fedora 37

### ISSUE THREAD

**Issue by JolanAklin** [obsproject/obs-studio#7960]
### Operating System Info

Other

### Other OS

Fedora 37

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/iYXE4RQ8HuDHH9LL

### Expected Behavior

Start the recording using intel igpu (i7-1165G7) encoding using FFMPEG VAAPI H.264 and the record doesn't buffer.

### Current Behavior

When the recording is started, systemd uses 40% and more of the gpu and make the recording buffer after a minute or so. This behaviour is the same in Wayland and Xorg

### Steps to Reproduce

1. Set the ouput mode to advanced
2. Set the Encode to FFMPEG VAAPi H.264
3. Set the VAAPI device to UHD Graphics
4. Start recording

**Comment by tytan652** [comment]
This behavior seems normal for iGPU hardware encoder.
