### ISSUE TITLE
Linux build of OBS 29 fails with too-old CEF, no configure warning

### ISSUE THREAD

**Issue by Rosuav** [obsproject/obs-studio#7963]
### Operating System Info

Other

### Other OS

Debian Bullseye

### OBS Studio Version

29.0.0-beta2

### OBS Studio Log URL

n/a

### Expected Behavior

If OBS cannot compile against a particular CEF version, it should be caught by the configure phase.

### Current Behavior

Build fails with `error: ‘class CefWindowInfo’ has no member named ‘bounds’`

### Steps to Reproduce

1. Use an old CEF eg build 4280
2. Build OBS 29 from trunk
3. Observe errors

### Anything else we should know?

Would be helpful to know the actual minimum CEF version required.

Incompatibility came in with [obs-browser#7142b21](https://github.com/obsproject/obs-browser/commit/7142b2109e7be991c5b82d194e32d918b0eb6c29)

**Comment by gxalpha** [comment]
> Would be helpful to know the actual minimum CEF version required.

We generally keep compatibility with the version we had prior to the one we currently use.
We updated to 5060 / 103 in 28.0, so that would be 4638 / 95 from OBS 27.2.

That being said, since this is a feature that was introduced very recently there's a chance that it may not work with 4638 either as it likely wasn't tested with it, so your milage may very (though if it doesn't work it wouldn't be my call to make as to whether that should be fixed).

**Comment by Rosuav** [comment]
Yep fair enough! I'm about to update my CEF but in the light of this, I'll try testing on 4638 before going to 5060.

**Comment by Rosuav** [comment]
Can confirm: works on both 4638 and 5060. So the actual functionality is (probably) fine, it would just be nice to demonstrate a minimum CEF version.

**Comment by WizardCM** [comment]
Yeah could be worth documenting as part of CMake what the minimum is.

**Comment by rafalszm** [comment]
> > Would be helpful to know the actual minimum CEF version required.
> 
> We generally keep compatibility with the version we had prior to the one we currently use. We updated to 5060 / 103 in 28.0, so that would be 4638 / 95 from OBS 27.2.
> 
> That being said, since this is a feature that was introduced very recently there's a chance that it may not work with 4638 either as it likely wasn't tested with it, so your milage may very (though if it doesn't work it wouldn't be my call to make as to whether that should be fixed).

Hi, when is the CEF planned to be updated to one that supports the following CSS features?
offset-distance:
offset-path:

![image](https://github.com/obsproject/obs-studio/assets/22595566/0cdcea04-9f96-48b0-b176-cbf79c96592a)

**Comment by RytoEX** [comment]
> > > Would be helpful to know the actual minimum CEF version required.
> > 
> > 
> > We generally keep compatibility with the version we had prior to the one we currently use. We updated to 5060 / 103 in 28.0, so that would be 4638 / 95 from OBS 27.2.
> > That being said, since this is a feature that was introduced very recently there's a chance that it may not work with 4638 either as it likely wasn't tested with it, so your milage may very (though if it doesn't work it wouldn't be my call to make as to whether that should be fixed).
> 
> Hi, when is the CEF planned to be updated to one that supports the following CSS features? offset-distance: offset-path:

All CEF progress and plans are tracked here:
https://github.com/obsproject/obs-studio/discussions/3853

**Comment by RytoEX** [comment]
Technically requires an obs-studio update to actually resolve this here.

**Comment by RytoEX** [comment]
The obs-browser update landed some time ago, so this is actually resolved now.
