### ISSUE TITLE
System theme causes menu entries to ellipsize

### ISSUE THREAD

**Issue by Rosuav** [obsproject/obs-studio#7964]
### Operating System Info

Other

### Other OS

Debian Bullseye

### OBS Studio Version

29.0.0-beta2

### OBS Studio Log URL

n/a

### Expected Behavior

Menus should be fully readable regardless of theme selected

### Current Behavior

As per screenshot, a number of menu entries are ellipsized, obscuring their meanings.

![Screenshot_2022-12-26_11-52-20](https://user-images.githubusercontent.com/640535/209486827-f608fbc8-8f30-46c8-a0e1-636c480f3ae5.png)

### Steps to Reproduce

1. Select "System" theme
2. Open menu eg Docks

### Anything else we should know?

This may possibly depend on specific theme settings. I'm using the Adwaita theme from Debian/XFCE.

**Comment by kkartaltepe** [comment]
It doesnt look like our style or ui configuration has any specific limitations regarding the width of these elements, so if you think this looks bad file a bug against your style provider.

**Comment by Rosuav** [comment]
On what systems have you tested this? I need something to compare against. Far as I can tell, my style (which has shipped with Xfce for quite a few versions now) doesn't have any width limitations either, so it has to be somewhere.
