### ISSUE TITLE
Can't change the OSS input chanel in the 'Audio Input Capture (OSS)' screen

### ISSUE THREAD

**Issue by yurivict** [obsproject/obs-studio#7979]
### Operating System Info

Other

### Other OS

FreeBSD

### OBS Studio Version

28.1.2

### OBS Studio Log URL

n/a

### Expected Behavior

n/a

### Current Behavior

It defaults to channel 2 and arrows up/down don't work.
There are channels 0..7 and only 2 can be used in OBS.

https://user-images.githubusercontent.com/271906/209934666-9abba0c3-31f0-40ea-b389-e8b73a2d8ba7.mp4

### Steps to Reproduce

n/a

**Comment by gxalpha** [comment]
Closing as this problem is exclusive to *nix systems which are not officially supported by us.
However, we're of course always happy to receive patches fixing problems on these platforms if people wish to contribute.
