### ISSUE TITLE
recording+NVENC error

### ISSUE THREAD

**Issue by qiuming696** [obsproject/obs-studio#7980]
### Operating System Info

Windows 10

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/LPDo8V-WAKHCXO3o

### Expected Behavior

解决问题

### Current Behavior

![FB18B17F-1330-4b0d-A953-CC47284A64E3](https://user-images.githubusercontent.com/121618210/209956075-58e57b7a-0393-4d60-aec0-718b0bb71c5e.png)

### Steps to Reproduce

正常开始录制但是无法开始

### Anything else we should know?

请帮助解决

**Comment by theHamsta** [comment]
I saw this in your log: 
```
21:00:23.653: [jim-nvenc] init_encoder_h264: nv.nvEncInitializeEncoder(enc->session, &enc->params) failed: 8 (NV_ENC_ERR_INVALID_PARAM): ::NV_ENC_TWO_PASS_FULL_RESOLUTION is only supported multipass encoding on this architecture.
```
Maybe you can check your encoding parameters

**Comment by prgmitchell** [comment]
Your recording settings are trying to utilize multi-pass but your card does not support it. There was a check added for this in the v29 release of OBS. Either installing the beta or configuring settings in advanced mode to disable multi pass should resolve this for you.

**Comment by notr1ch** [comment]
I've opened PR #7994 to better expose this error, but this is indeed a config issue as your GPU doesn't support the settings you have selected.
