### ISSUE TITLE
Failed to start SRT stream

### ISSUE THREAD

**Issue by jlongo-encora** [obsproject/obs-studio#7984]
### Operating System Info

Ubuntu 20.04

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/uWJ89VIu7rIEekYJ

### Expected Behavior

Stream SRT should work

### Current Behavior

SRT streaming is not working

### Steps to Reproduce

I'm trying to send an SRT video stream from OBS studio to Oven Media Engine - https://airensoft.gitbook.io/ovenmediaengine/live-source/srt-beta#obs-studio.

Every time I try I can see the following error:
```
14:19:55.597: ==== Streaming Start ===============================================
14:19:55.597: [ffmpeg muxer: 'adv_stream'] Writing file 'srt://127.0.0.1:9999?mode=caller&timeout=5000000&transtype=live&pkt_size=1316&streamid=srt%3A%2F%2F127.0.0.1%3A9999%2Fapp%2Ftest'...
14:20:03.126: [ffmpeg muxer: 'adv_stream'] os_process_pipe_write for info structure failed
14:20:03.127: [ffmpeg muxer: 'adv_stream'] Output of file 'srt://127.0.0.1:9999?mode=caller&timeout=5000000&transtype=live&pkt_size=1316&streamid=srt%3A%2F%2F127.0.0.1%3A9999%2Fapp%2Ftest' stopped
14:20:03.127: Output 'adv_stream': stopping
14:20:03.127: Output 'adv_stream': Total frames output: 224
14:20:03.127: Output 'adv_stream': Total drawn frames: 226
14:20:03.127: Output 'adv_stream':  Reconnecting in 2.00 seconds..
14:20:03.128: libfdk_aac encoder destroyed
```

and the logs from Oven Media Engine doesn't change, which seems like the streaming is not reaching Oven Media Engine.

I've already tried without options `mode=caller&timeout=5000000&transtype=live` with the same results.

### Anything else we should know?

If I run "srt-live-transmit" tool in a separate terminal:
```
./srt-live-transmit "udp://127.0.0.1:1234?pkt_size=1316" "srt://localhost:9999?streamid=srt%3A%2F%2Flocalhost%3A9999%2Fapp%2Ftest"
```
and try to send the video stream from OBS to `udp://localhost:1234?pkt_size=1316`, everything works. However, this is a hack, I'd like to send an SRT video stream from OBS

**Comment by tytan652** [comment]
Ubuntu 20.04 FFmpeg package has no SRT support.

Try with the Flatpak if you want SRT support on 20.04.
