### ISSUE TITLE
Jack client's name doesn't contain "OBS Studio" in it

### ISSUE THREAD

**Issue by yurivict** [obsproject/obs-studio#7988]
### Operating System Info

Other

### Other OS

FreeBSD

### OBS Studio Version

28.1.2

### OBS Studio Log URL

n/a

### Expected Behavior

n/a

### Current Behavior

it just says "JACK Input Client".
![image](https://user-images.githubusercontent.com/271906/210110348-53818209-4567-4cc8-b894-63862f567747.png)
it should be "OBS Studio: JACK Input Client" instead.

### Steps to Reproduce

n/a

**Comment by WizardCM** [comment]
This is the only place where we set the text "Jack Input Client"

https://github.com/obsproject/obs-studio/blob/1b8a6955711333ad203645a2c7959dca6b9607a6/plugins/linux-jack/jack-input.c#L28

As far as I can tell, this function is only used to get the name of the source/plugin within OBS. I don't know if changing this return value will affect the JACK client.

**Comment by yurivict** [comment]
When the user adds the JACK source with some name - Jack source name should be formatted as ```"OBS Studio: {user-provided-source-name}"```.

**Comment by univrsal** [comment]
https://github.com/obsproject/obs-studio/blob/1b8a6955711333ad203645a2c7959dca6b9607a6/plugins/linux-jack/jack-input.c#L75-L81

This seems to be where the source name is used for the jack input name. Prepending something there shouldn't be too difficult.

**Comment by gxalpha** [comment]
>  There's probably a better way to prepend strings though.

@univrsal You probably want `dstr`ings from `<util/dstr.h>`

**Comment by vapour101** [comment]
This fix has broken my setup. Prepending a string with a colon to a jack source creates a new group. My source list in QJackCtl is now this: 
![image](https://github.com/obsproject/obs-studio/assets/2683046/54cca860-a524-48ba-95c3-785ea56f49c3)

The correct solution for this "bug" should be for OP to name their sources properly in OBS.
