### ISSUE TITLE
OBS doesnt launch , even after reinstalling 

### ISSUE THREAD

**Issue by kinnytamilvaloYT** [obsproject/obs-studio#7996]
### Operating System Info

Windows 10

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://github.com/obsproject/obs-studio/files/10329363/2023-01-02.01-02-40.txt

### Expected Behavior

When i try to open OBS64.exe, nothing happens, below information from the respective log

-- Crash log folder is empty 

[2023-01-02 01-02-40.txt](https://github.com/obsproject/obs-studio/files/10329363/2023-01-02.01-02-40.txt)

- did a reinstall of obs with antivirus disabled
- removed the settings folder and did a reinstall
- tried a portable install
and that all of those resulted in the exact same behavior with the exact same log.

### Current Behavior

it doesn't open any OBS window and log generated as attached above

### Steps to Reproduce

1. Launch OBS
2.
3.
...

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by kinnytamilvaloYT** [comment]
@Fenrirthviti  i spend good amount of time in Discord forum and we tried several things, i was routed here from discord to raise this as Bug

**Comment by Fenrirthviti** [comment]
Unfortunately, github issues are reserved for bug reports that have reproduction steps. It is unlikely that this is a bug with OBS, and more likely that your antivirus is preventing OBS from launching. I'd recommend fully uninstalling (disabling it doesn't actually disable it, as reflected in the log that it's still active. They need to be fully uninstalled.
