### ISSUE TITLE
OBS crash on startup with twich chat dock pinned

### ISSUE THREAD

**Issue by PhilG112** [obsproject/obs-studio#8004]
### Operating System Info

Other

### Other OS

Ubuntu 22.04.1 LTS

### OBS Studio Version

28.1.2

### OBS Studio Log URL

Cannot access the help menu due to crashing on startup, see crash log below.

### OBS Studio Crash Log URL

https://pastebin.com/js50EPdR

### Expected Behavior

Expected OBS to start up as normal.

### Current Behavior

Obs starts up and automatically opens the twitch chat dock on the right hand side (see image). OBS then instantly crashes with a segmentation fault.

![Screenshot from 2023-01-04 15-02-54](https://user-images.githubusercontent.com/10988092/210482650-c4420c7c-a1d3-47f3-8ab3-d4969c578c4d.png)

### Steps to Reproduce

1. Open OBS with the twitch chat dock automatically pinned.
2. Set your `DockState` in your `basic.ini` to the one below to reproduce.

### Anything else we should know?

I tried uninstally and reinstalling OBS with no luck. Seems like something is wrong with my dockstate, see below.

This is my dock state from my basic.ini file

```
DockState=AAAA/wAAAAD9AAAAAgAAAAEAAADIAAACXPwCAAAAA/wAAAAXAAACXAAAASwA////+gAAAAEBAAAAAvsAAAAUAHQAdwBpAHQAYwBoAEkAbgBmAG8D////ev///+sAAADIAAACNvsAAAAUAHQAdwBpAHQAYwBoAEMAaABhAHQBAAADbwAAAMgAAADIAP////sAAAAWAHQAdwBpAHQAYwBoAFMAdABhAHQAcwIAAAIzAAABTwAAAMgAAAD6+wAAABQAdAB3AGkAdABjAGgARgBlAGUAZAIAAADgAAAAsQAAASwAAAKKAAAAAwAABDcAAAEB/AEAAAAG+wAAABQAcwBjAGUAbgBlAHMARABvAGMAawEAAAAAAAAA1QAAAKAA////+wAAABYAcwBvAHUAcgBjAGUAcwBEAG8AYwBrAQAAANkAAADVAAAAoAD////7AAAAEgBtAGkAeABlAHIARABvAGMAawEAAAGyAAABFgAAAN4A////+wAAAB4AdAByAGEAbgBzAGkAdABpAG8AbgBzAEQAbwBjAGsBAAACzAAAAKAAAACgAP////sAAAAYAGMAbwBuAHQAcgBvAGwAcwBEAG8AYwBrAQAAA3AAAADHAAAAngD////7AAAAEgBzAHQAYQB0AHMARABvAGMAawIAAAOiAAACbAAAArwAAADIAAADawAAAlwAAAAEAAAABAAAAAgAAAAI/AAAAAA=
```

Note: I deleted the above dockstate which reset all my docks and the issue was fixed. However, adding that dock state back into my basic.ini file caused the issue to reproduce.

**Comment by kkartaltepe** [comment]
This is not our bug as Qt crashes when restoring dockstate from qt5 on qt6. File a bug against Qt if you find this crash annoying, as only they can fix it.
