### ISSUE TITLE
Newest Intel A380 Drivers Lose AV1/H265 Encoding Features

### ISSUE THREAD

**Issue by Kelkador** [obsproject/obs-studio#8010]
### Operating System Info

Windows 11

### OBS Studio Version

29.0.0-beta3

### OBS Studio Log URL

https://obsproject.com/logs/5hVJkt9u82xYqjv9

### Expected Behavior

QSV AV1 encoding would be available as a recording codec just like on driver version 31.0.101.3959

### Current Behavior

Only H264 encoding was available as a QSV option from the codec drop down (and not functional, it would cause an error) and my display capture source that was connected to a display on my Nvidia 3080 Ti also broke. 

### Steps to Reproduce

1. Upgrade drivers to latest version (31.0.101.4032)
2. That's it.

### Anything else we should know?

Rolling back drivers fixed issue completely (including display adapter issue).

**Comment by Fenrirthviti** [comment]
Please remove all third party plugins, and test again. Some of your plugins are known to cause issues with encoders.

**Comment by Kelkador** [comment]
Tested again. Same result. Display capture inoperable and I only have the option of H264 on QSV (which worked with the prior drivers but do not anymore).

https://obsproject.com/logs/C7m7cPB9xsgDB8LG

**Comment by Fenrirthviti** [comment]
Thanks, we've had another report of this driver causing issues, we're checking in to it. Might be something on Intel's side.

**Comment by Kelkador** [comment]
Thanks for the confirmation. Something weird by the way when the driver updated it removed itself from the "High performance" setting in Windows graphics settings:

Older Driver: 
![image](https://user-images.githubusercontent.com/82776543/210925230-f7b0848f-07e7-4e2d-b5c2-f13293b0a68c.png)


Newer Driver:
![image](https://user-images.githubusercontent.com/82776543/210924305-f53b2b61-defc-451b-a8bb-1387e5fea9fe.png)

Unsure if that does anything for you.

PS: Display capture was working this time with the new driver, after I reinstalled StreamFX. Might've just been an outdated version of the Plugin interfering? No clue what's happening there but with old driver and new plugin everything's working.

**Comment by Fenrirthviti** [comment]
Yeah, that's another known issue that could potentially cause issues, but my understanding is that *shouldn't* affect the encoder init check we do.

**Comment by RytoEX** [comment]
Please specify exact driver versions rather than "older" and "newer".

**Comment by Kelkador** [comment]
Updated my comparison post.

**Comment by RytoEX** [comment]
Please retest in OBS Studio 29.0.2 (or newer) and please provide a new OBS log file.

**Comment by Kelkador** [comment]
Tested on version 29.0.2 with Intel A380 driver version 31.0.101.4091

QuickSync Video AV1 is still not selectable.

https://obsproject.com/logs/Tfd8omBtonOOMMTJ

**Comment by RytoEX** [comment]
> Tested on version 29.0.2 with Intel A380 driver version 31.0.101.4091
> 
> QuickSync Video AV1 is still not selectable.
> 
> https://obsproject.com/logs/Tfd8omBtonOOMMTJ

Can you confirm that a real display is physically connected to the A380? Can you confirm the type of connection (DisplayPort, HDMI)?

**Comment by sandr1x** [comment]
31.0.101.4146 driver released, сheck it

**Comment by NyaakoYT** [comment]
> 31.0.101.4146 driver released, сheck it

It doesn't work.
There is a "fix" from here: https://github.com/ma3uk/obs-qsv-onevpl/tree/main/builds

**Comment by RytoEX** [comment]
Intel has confirmed that this is a driver issue and that they are working on it. We will provide an update when we are able to do so.

**Comment by Nemezor** [comment]
I also have this issue. Using an Intel Arc A380 for recording and an AMD Radeon RX 6600 as the main GPU driving the displays.

I did some testing and simply attaching monitors to the Arc A380 does not make it appear in OBS, I have to launch OBS specifically on the Arc A380 for the encoders to show up - basically, it works if the A380 is driving the primary display (since Windows will launch apps on the GPU that the primary display is attached to), any other configuration did not show QSV AV1.

This leads me to believe this actually is an OBS bug, not an Intel driver bug. Afaik there was a driver bug that showed Arc dGPUs as iGPUs to Windows, so there is a chance the reason this worked in the past was because Windows was putting OBS onto the "iGPU" which happened to be an Arc card.

**Comment by RytoEX** [comment]
> I also have this issue. Using an Intel Arc A380 for recording and an AMD Radeon RX 6600 as the main GPU driving the displays.
> 
> I did some testing and simply attaching monitors to the Arc A380 does not make it appear in OBS, I have to launch OBS specifically on the Arc A380 for the encoders to show up - basically, it works if the A380 is driving the primary display (since Windows will launch apps on the GPU that the primary display is attached to), any other configuration did not show QSV AV1.
> 
> This leads me to believe this actually is an OBS bug, not an Intel driver bug. Afaik there was a driver bug that showed Arc dGPUs as iGPUs to Windows, so there is a chance the reason this worked in the past was because Windows was putting OBS onto the "iGPU" which happened to be an Arc card.

As previously stated, Intel has already tested and confirmed that this is an Intel driver bug. Our code simply starts an encode session on each adapter with each codec and returns a boolean result based on if the encoder returned an error or not.

**Comment by nilankadesilva** [comment]
I found a workaround.

As @Nemezor mentioned the latest driver requires OBS to be launched on the monitor connected to the ARC GPU. But if you rollback to 31.0.101.3959 and disable automatic updates. It will fix this requirement. You can open OBS on any monitor. But you need something plugged to the Arc GPU for it to be detected. I use an HDMI dummy plug. Rolling back the driver doesn’t seem to impact anything so until Intel fixes it, I’m keeping 31.0.101.3959

**Comment by nilankadesilva** [comment]
Latest 31.0.101.4369 doesn't fix this either. I had to rollback to 31.0.101.3959

**Comment by sternskr** [comment]
The newest released beta arc driver 31.0.101.4382 appears to have the same issue still

**Comment by nilankadesilva** [comment]
Latest 31.0.101.4502 doesn't fix the issue either.

**Comment by nilankadesilva** [comment]
Anyone tried 101.4575?

**Comment by NyaakoYT** [comment]
> Anyone tried 101.4575?

It doesn't work, still.

Still using this temporary fix (https://github.com/ma3uk/obs-qsv-onevpl) in order to display the native AV1 and HEVC encoder for OBS. You can take the file "obs-qsv-test.exe" from there and replace the default one in the root folder where you have obs.exe installed.

**Comment by fumoadol** [comment]
I must connect a real display to use AV1 encoder.Is it a bug?

**Comment by RytoEX** [comment]
I've received a report that this no longer occurs in OBS Studio 30.0.0-beta2. Could people affected please retest to confirm?

**Comment by nilankadesilva** [comment]
> I must connect a real display to use AV1 encoder.Is it a bug?

You can even connect a dummy plug and it would be fine.

**Comment by Tylerjet** [comment]
> I've received a report that this no longer occurs in OBS Studio 30.0.0-beta2. Could people affected please retest to confirm?

@RytoEX Confirmed for me on Intel Driver 31.0.101.4644 Quicksync options are showing with no dummy plug or workaround enabled! Nice!

**Comment by SKECHER9** [comment]
> > I've received a report that this no longer occurs in OBS Studio 30.0.0-beta2. Could people affected please retest to confirm?
> 
> @RytoEX Confirmed for me on Intel Driver 31.0.101.4644 Quicksync options are showing with no dummy plug or workaround enabled! Nice!

I checked OBS 30.0.0-beta2 on a system running win10, 5900X cpu, 7900XTX gpu0 (driver 23.8.1(3 display out)) and A380 gpu1 (driver 31.101.4644 (no display (currently adding display to A380 causes memory leak driver bug, unrelated to obs))) 
![Screenshot 2023-08-26 154525](https://github.com/obsproject/obs-studio/assets/108960412/d1575db9-b821-47ca-a18f-a741d2102186)
QSV AV1 shows up now, but not QSV H.265/HEVC.

**Comment by RytoEX** [comment]
> > > I've received a report that this no longer occurs in OBS Studio 30.0.0-beta2. Could people affected please retest to confirm?
> > 
> > 
> > @RytoEX Confirmed for me on Intel Driver 31.0.101.4644 Quicksync options are showing with no dummy plug or workaround enabled! Nice!
> 
> I checked OBS 30.0.0-beta2 on a system running win10, 5900X cpu, 7900XTX gpu0 (driver 23.8.1(3 display out)) and A380 gpu1 (driver 31.101.4644 (no display (currently adding display to A380 causes memory leak driver bug, unrelated to obs))) ![Screenshot 2023-08-26 154525](https://user-images.githubusercontent.com/108960412/263494672-d1575db9-b821-47ca-a18f-a741d2102186.png) QSV AV1 shows up now, but not QSV H.265/HEVC.

I'm pretty sure that QSV HEVC does not show up in Simple Output Mode regardless at the moment. It's a separate issue.

**Comment by fumoadol** [comment]
> I've received a report that this no longer occurs in OBS Studio 30.0.0-beta2. Could people affected please retest to confirm?

It's Okay now.

**Comment by nilankadesilva** [comment]
> I've received a report that this no longer occurs in OBS Studio 30.0.0-beta2. Could people affected please retest to confirm?

Works for me to. Does this mean that the fix was needed on OBS's end and not Intel?

**Comment by RytoEX** [comment]
> > I've received a report that this no longer occurs in OBS Studio 30.0.0-beta2. Could people affected please retest to confirm?
> 
> Works for me to. Does this mean that the fix was needed on OBS's end and not Intel?

As I previously stated, Intel themselves confirmed to us that this was a driver bug.

> Intel has confirmed that this is a driver issue and that they are working on it. We will provide an update when we are able to do so.

Given that it used to work on an older driver, but stopped working after a certain driver, we are inclined to agree with them on this point.

Either something changed between driver versions 4575 and 4644, or VPL's API returns different results from the driver than MSDK's API. If the latter, then it could have been a "driver bug that only surfaces when using MSDK". If someone with an affected setup wants to test the matrix of drivers between 4575 and 4644 and OBS Studio 29.1.3 and OBS Studio 30.0.0-beta1/2 to narrow down what change may have caused this behavior difference, by all means, feel free to do so, but I do not have an affected setup to test.

Regardless, I'm going to consider this Issue resolved.
