### ISSUE TITLE
QSV settings changes can't be applied.

### ISSUE THREAD

**Issue by Mishasama** [obsproject/obs-studio#8011]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.0-beta3

### OBS Studio Log URL

https://obsproject.com/logs/3pgFI6zo1bRlOzzB

### Expected Behavior

[qsv encoder: 'advanced_video_stream'] settings:
rate_control:   VBR
target_bitrate: 3500

### Current Behavior

[qsv encoder: 'advanced_video_stream'] settings:
rate_control:   CBR
target_bitrate: 2500

### Steps to Reproduce

1. Setting Output Mode as Advanced
2. Encoder QS
3. RC=VBR
4. Bitrate=3500
5. Click OK
6. Start Streaming
7. Check the Log
...

### Anything else we should know?

Any changes about QSV settings were in no effect. Only default settings were applied.

**Comment by gxalpha** [comment]
This is expected, although not communicated well.
At the moment, CBR is always used for the stream encoder (regardless of which encoder you’re using). When recording, selecting another rate control method should work fine.

**Comment by Mishasama** [comment]
> This is expected, although not communicated well. At the moment, CBR is always used for the stream encoder (regardless of which encoder you’re using). When recording, selecting another rate control method should work fine.

Got it, thx.
