### ISSUE TITLE
OBS 29 Stable release still locked in CBR

### ISSUE THREAD

**Issue by Mishasama** [obsproject/obs-studio#8016]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.0.0

### OBS Studio Log URL

https://obsproject.com/logs/3pgFI6zo1bRlOzzB

### Expected Behavior

All RC modes should work like the old versions.

### Current Behavior

#8011

### Steps to Reproduce

1. Just try streaming with any RC mode except CBR
2. See logs
...

### Anything else we should know?

It shouldn't have this problem on the stable release.

**Comment by derrod** [comment]
OBS has always enforcd CBR for streaming.

**Comment by Mishasama** [comment]
> OBS has always enforcd CBR for streaming.

What? When? I never heard before. And I never had this problem when using 27.
