### ISSUE TITLE
GPU memory leaking?

### ISSUE THREAD

**Issue by Mishasama** [obsproject/obs-studio#8019]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.0-beta3

### OBS Studio Version (Other)

29.0.0 Stable Release

### OBS Studio Log URL

https://obsproject.com/logs/WfkQmZ5PPXWLDsOC

### Expected Behavior

![image](https://user-images.githubusercontent.com/54498172/211193060-9d5f1140-4d36-4191-a0b2-5a395b7204d8.png)

This is the shared GPU memory display at the task manager.

### Current Behavior

It looks terrible.

### Steps to Reproduce

1. idk
2. just start streaming
3. wait after 1 hour
4. check taskman
...

### Anything else we should know?

![image](https://user-images.githubusercontent.com/54498172/211193204-c7954aa6-3456-459f-b49a-7b77ecade219.png)

![image](https://user-images.githubusercontent.com/54498172/211193194-9f0ca465-2645-4499-9fb4-4dd3586ed3e7.png)

But actually there is no big problem? I haven't encountered this kind of thing in previous versions.

**Comment by kkartaltepe** [comment]
Provide usage of the previous versions after 1 hour for comparison. This does not seem particularly out of line with prior releases to me.

**Comment by Mishasama** [comment]
> Provide usage of the previous versions after 1 hour for comparison. This does not seem particularly out of line with prior releases to me.

![image](https://user-images.githubusercontent.com/54498172/211278105-aa87a497-55cf-40ca-b259-ad7cd15e68bc.png)
27.2.4 over hours.

But it may just be the something Windows bug. I can't feel it has impacted performance.
