### ISSUE TITLE
the procedure entry point IsWow64Process2 could not be located in the dynamic link library OBS.DLL

### ISSUE THREAD

**Issue by ZhanhaoLiu1** [obsproject/obs-studio#8021]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.0-beta3

### OBS Studio Log URL

OBS hangs; log file doesn't show this

### Expected Behavior

OBS launches like normal without crashes

### Current Behavior

The window shows "the procedure entry point IsWow64Process2 could not be located in the dynamic link library OBS.DLL" every time open the obs studio

### Steps to Reproduce

1. run the obs-studio.exe
2.
3.
...

**Comment by notr1ch** [comment]
Your Windows 10 install may be out of date if it's missing this API, try running the Update Assistant.

https://support.microsoft.com/en-us/topic/windows-10-update-assistant-3550dfb2-a015-7765-12ea-fba2ac36fb3f

**Comment by R-Adrian** [comment]
note: also try running `winget upgrade` in an elevated command prompt and then upgrade any Visual C++ redistributables that winget detects as being outdated. (TL;DR hint: `winget upgrade --all` )

if your command prompts shows an error that it cannot find a `winget` command then your Windows 10 installation is really WAY out of date.

**Comment by derrod** [comment]
Closing as this appears to be an issue related to using Windows 7/8 or a very old Windows 10 install. All of which are unsupported.

**Comment by FishamanP** [comment]
What exactly are the supported versions of Windows? I can't find this info in the Readme, the GitHub wiki, or the project website. This error started occuring on Windows 10 LTSB as of 29.0. 28.0 worked well.

**Comment by derrod** [comment]
According to https://learn.microsoft.com/en-us/windows/win32/api/wow64apiset/nf-wow64apiset-iswow64process2 Windows 10 1511 or Windows Server 2016 and up should be supported. The oldest LTSC version is still 1507 however so that won't work.

**Comment by FishamanP** [comment]
My LTSB is definitely based on a later version. I want to say 1803, but I can check precisely which version later this week.

**Comment by derrod** [comment]
Please report back, it would be annoying if the Microsoft docs are wrong there. Also please check this is the actual error and you're not getting one about a different function.

**Comment by FishamanP** [comment]
Checked, it must be 1809. And this is the exact error shown.

**Comment by RytoEX** [comment]
It appears the current documentation is incorrect:
https://github.com/MicrosoftDocs/sdk-api/pull/995

**Comment by FishamanP** [comment]
Apologies, I was mistaken. The OS is LTSB 2016, based on 16.07. So this falls in the affected range from the wrong documentation.
