### ISSUE TITLE
Virtual Camera image stutters in Mac

### ISSUE THREAD

**Issue by mattharrison** [obsproject/obs-studio#8023]
### Operating System Info

macOS 12

### Other OS

12.5.1 Monterey

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/pTShDcjHxn7MGs8i

### Expected Behavior

When I click "Start Virtual Camera" with Canon EOS Webcam, and start using the virtual camera in Zoom, the video stutters.

I would expect it to work without stuttering like it works in Windows.

### Current Behavior

Virtual camera stuttering when using it in Zoom.

(Note that the built-in webcam appears to work without stuttering.)

### Steps to Reproduce

1. Start virtual camera with EOS Webcam Video Capture device
2. Start Zoom
3. Use virtual camera in Zoom
...

**Comment by gxalpha** [comment]
Please test if any of the following scenarios also shows the stuttering:
- Using another source (like a media source or display capture) with the virtual camera
- Recording the EOS Webcam in OBS (and checking whether it shows the stutter in the final recording).

As an aside, the EOS Webcam will stop working with macOS 14 as it needs updating from Canon's side anyways.

**Comment by gxalpha** [comment]
Closing s there has been no response.
