### ISSUE TITLE
Windows Title Bar colour does not match theme

### ISSUE THREAD

**Issue by LooneyH** [obsproject/obs-studio#8024]
### Operating System Info

Windows 10

### OBS Studio Version

29,0,0

### OBS Studio Log URL

https://obsproject.com/logs/MkZBWnIZ0CQ6riXI

### Expected Behavior

I have found that whilst using the OBS Studio 29 beta, the title bar would match the theme. In a dark theme, it would be black, and in light themes, I tested it and it changes to a grey bar.

### Current Behavior

In the final release of OBS Studio 29, I have found that the title bar doesn't match this behaviour. I imagine this may have been done to distinguish between beta and stable releases, but I have been personally frustrated for so long that I had no means to change this and after it seemed to finally be adaptive, I now am back to frustrated. I see no reason for this to be enforced without at least a toggle in the menu somewhere (even just below the theme option) to change this, or just linking it to the theme option if a toggle would feel like an unnecessary addition.

### Steps to Reproduce

1. Open OBS Studio 29.0.0-beta3
2. Set theme to a dark theme if not already and the title bar will be dark/black as well.
3. Close OBS Studio 29.0.0-beta3.
4. Open OBS Studio 29.0.0 (stable).
5. Set theme to a dark theme if not already and the title bar will remain white.

### Anything else we should know?

As stated already, I believe that whether this is to distinguish between beta and stable versions or was an unintended side-effect of some kind (be it that made it dark in the first place or that made it light now), I do not see any reason to not have this more easily customisable, be it by allowing themes to customise it, or by allowing it to adaptively change, or even by just having a toggle for a white or black title bar. More options are never a bad thing, and OBS has a wealth of options that are for very specific use-cases, so I do not see why this simple aesthetic change cannot be added as an option.

I have another log to provide here as well of the beta version to compare to the full release (a separate install I have had for testing [linked here](https://obsproject.com/logs/YMX98uEHBYZyEad4), although I did also install the beta over my main install and had the same behaviour showcased there so it was not due to any plugin differences at all)

**Comment by WizardCM** [comment]
This is due to a to downgrade of Qt version for the final release due to a regression in the Settings window.

**Comment by LooneyH** [comment]
Ahhh okay, so I assume that means this will return once the issues with the QT version are resolved? Mind if I ask what the issues are, out of curiosity?

**Comment by WizardCM** [comment]
Correct, as soon as it's safe to upgrade, we will do so.

The bug in question is https://bugreports.qt.io/browse/QTBUG-109237

It results in the Settings window taking unrealistic time to load, and may cause other issues.
