### ISSUE TITLE
Saved recording does not get remuxed successfully

### ISSUE THREAD

**Issue by physanus** [obsproject/obs-studio#8029]
### Operating System Info

Windows 11

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.0.0

### OBS Studio Log URL

https://obsproject.com/logs/iBjekFuN2emZQtXo

### Expected Behavior

I have enabled the setting `Advanced > Recording > Automatically remux to mp4`.
I do record in the `.ts` file format.

After saving a recording or the replay buffer, I expect OBS to create two files: A `Replay 2023-01-09 15-37-58.ts` and a short time after that a `Replay 2023-01-09 15-37-58.mp4`. 

### Current Behavior

The `.mp4` file is empty (`0 KB`). 
This bug has not been present in my previous version of OBS (latest release of `28.Y.Z` I believe), only since yesterday, since I upgraded to `29.0.0`.

### Steps to Reproduce

I am unsure since I do not know which settings need to be active (maybe it has to do something with the ts file format? Maybe with my encoder? I really don't know).

At least, this is what is needed:
1. Activate `Advanced > Recording > Automatically remux to mp4`
2. Save a recording or the replay buffer to disk
3. Empty `.mp4` file gets created

**Comment by icedterminal** [comment]
Chiming in. I have this exact same issue too. https://obsproject.com/logs/IYFp5pctVmCBFGsN
