### ISSUE TITLE
Expander produce "clicks" after attack event happens, after update from OBS v28 to v29

### ISSUE THREAD

**Issue by FelikZ** [obsproject/obs-studio#8030]
### Operating System Info

macOS 13.1

### Other OS

M1 Pro

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.0.0

### OBS Studio Log URL

https://obsproject.com/logs/Dei5QTHkC3co7Vhi

### Expected Behavior

Expander does not produce extra "clicks" in sound

### Current Behavior

Produces a "click" sound right after "Attack" happens

### Steps to Reproduce

1. Create similar expander config as attached, but configure threshold to "background noise level you have in the room"
2. Monitor your voice input (in sound settings you can choose device to monitor OBS output)
3. It should produce clicks

Sample config json and as screenshot:

```
            {
                "balance": 0.5,
                "deinterlace_field_order": 0,
                "deinterlace_mode": 0,
                "enabled": true,
                "flags": 0,
                "hotkeys": {},
                "id": "expander_filter",
                "mixers": 255,
                "monitoring_type": 0,
                "muted": false,
                "name": "Expander",
                "prev_ver": 469827585,
                "private_settings": {},
                "push-to-mute": false,
                "push-to-mute-delay": 0,
                "push-to-talk": false,
                "push-to-talk-delay": 0,
                "settings": {
                    "attack_time": 1,
                    "output_gain": 0.0,
                    "presets": "expander",
                    "ratio": 8.0,
                    "release_time": 400,
                    "threshold": -60.0
                },
                "sync": 0,
                "versioned_id": "expander_filter",
                "volume": 1.0
            },
```

<img width="854" alt="image" src="https://user-images.githubusercontent.com/1080269/211358960-dd299d21-8426-4370-b98d-d7f03c541ab4.png">

### Anything else we should know?

Used to work normally, until I have upgraded to v29 from v28.

If I disable expander, the issue disappears but I need expander for a reason :)

Also a sample audio file, where you can clearly hear "clicks".

v29
https://user-images.githubusercontent.com/1080269/211359822-479a6ce9-29a9-474a-a0e6-0098c8b5281f.mp4
v28.1.2
https://user-images.githubusercontent.com/1080269/211363567-eb5f860c-47af-4c7f-a730-49c416a713fa.mp4

**Comment by pkviet** [comment]
Fixed here: https://github.com/obsproject/obs-studio/pull/8031

**Comment by FelikZ** [comment]
@pkviet wow, thanks for such quick response! I will test it as soon as available.

**Comment by pkviet** [comment]
FYI i have a new PR which includes the fix. See #8121 for test builds
