### ISSUE TITLE
Virtual Cam on macOS shows a red screen instead of video (again, 29.0.0 regression)

### ISSUE THREAD

**Issue by infinitewarp** [obsproject/obs-studio#8039]
### Operating System Info

macOS 12

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.0.0

### OBS Studio Log URL

https://obsproject.com/logs/LJahkNJAeWt66n0S

### Expected Behavior

Virtual camera should show the currently selected output scene.

### Current Behavior

Any other app using the virtual camera shows a bright red screen when the virtual cam is enabled. When virtual cam is disabled, it shows the normal placeholder graphic.

![Screen Shot 2023-01-10 at 10 25 59 AM](https://user-images.githubusercontent.com/1472326/211595043-b16cb1fd-af03-4a58-83bb-f250ceaa298a.png)

### Steps to Reproduce

1. Use old OBS (28.1.2) with normal working virtual camera
2. Either upgrade from 28.1.2 to 29.0.0 via the in-app upgrade prompt, or manually download the new version directly from https://obsproject.com/download (I tried both with the same result)
3. Restart OBS (29.0.0).
4. Start the virtual camera.
5. Enter system credentials to allow the system to install the new version of the mac-virtualcam plugin.
6. Note that the video looks fine in OBS itself.
7. Note that the video is solid red when viewed in other apps like Google Chrome.

### Anything else we should know?

This appears to be a **regression** of https://github.com/obsproject/obs-studio/issues/7333. My system also suffered red screen video output in a previous 28.x version, but presumably https://github.com/obsproject/obs-studio/pull/7403 fixed it in a later 28.x version, and it's been working fine in the latest 28.1.2. Did that code get lost or changed in the 29.x development branch?

Restarting other apps, OBS itself, or the whole system seems to have no effect on the red screen issue. Swapping the video input selection in apps like Google Chrome to something else and then back to OBS also doesn't help.

Closing OBS 29.0.0, replacing it with *28.1.2*, and following the usual steps (including authorizing it to reinstall its version of mac-virtualcam plugin) successfully restores normal video output while using OBS 28.1.2. Upgrading to 29.0.0 breaks it again.

I'm running this on a MacBook Pro (16-inch, 2019) with the following specs:

    macOS version: 12.6.2 (21G320)
    Processor: 2.6 GHz 6-Core Intel Core i7
    Memory: 32 GB 2667 MHz DDR4
    Graphics: AMD Radeon Pro 5300M 4 GB, Intel UHD Graphics 630 1536 MB

**Comment by sissiwup** [comment]
Back to 28.1.2 did not fix the problem. The cam stays red.

**Comment by gxalpha** [comment]
After going back, try rebooting your computer.

**Comment by infinitewarp** [comment]
OBS 28.1.2 _should_ detect and reinstall its older plugin automatically, but to be extra thorough, you could close OBS and any video streaming apps (Firefox, Chrome, Zoom, etc.), and manually delete `/Library/CoreMediaIO/Plug-Ins/DAL/obs-mac-virtualcam.plugin`. Then the next time you start OBS and enable the virtual camera, it should prompt for your password to install its version of the plugin.

Restarting your whole computer would certainly ensure nothing is still trying to use the newer version of the plugin, but in my case, simply closing and reopening the apps themselves was good enough.

**Comment by echohack** [comment]
+1. I'm also receiving this issue (although I get a Green screen, or sometimes a screen with different levels of static and other colors) only after upgrading to 29.0.0 on MacOS Ventura 13.1.

**Comment by RytoEX** [comment]
If you are affected by this, please specify if your system has an Intel CPU or Apple Silicon CPU (even better, provide an OBS log file). Please also test the test build at #8044.

**Comment by davidolrik** [comment]
I'm on Intel and I've just tested with obs-studio-macos-x86_64-1de63184d from #8044 and I still get a completely green screen when sharing my virtual camera in Teams.

macOS 13.1 (22C65)
OBS Studio 29.0.0 (3895376203)

I tried uploading a OBS log file, but was told there was nothing in it to see because I wasn't recording or streaming.
Here is a OBS log file where I'm recording: https://obsproject.com/logs/V4PyeB7Z7qIRJhG7

When recording I still got the green screen, and some single frames with picture.

**Comment by gxalpha** [comment]
@davidolrik did you restart your Computer after using the virtual camera from the PR build for the first time?

**Comment by davidolrik** [comment]
@gxalpha No, I did not. - But I've just rebooted and now it works! 👍🏽

**Comment by PatTheMav** [comment]
@infinitewarp Would you be able to confirm the nightly created by #8044 fixes the issue as well?

**Comment by superpowered1** [comment]
I'm having the same problem streaming on Whatnot with the red screen.  Is this fixed yet?  On MAC ventura 13.1 which doesn't let me reinstall the older OBS now.  is there a fix yet?

**Comment by herr-lehmann** [comment]
> @infinitewarp Would you be able to confirm the nightly created by #8044 fixes the issue as well?

This worked for me like a charm after restarting! Thanks!

**Comment by superpowered1** [comment]
@infinitewarp how do I implement this? thanks!

**Comment by infinitewarp** [comment]
> @infinitewarp Would you be able to confirm the nightly created by #8044 fixes the issue as well?

Sorry it took a while before I could try this out. Yes, the `obs-studio-macos-arm64-1de63184d` artifact from your PR ([from here](https://github.com/obsproject/obs-studio/actions/runs/3895376203)) appears to have resolved the red screen problem on my system. 👍 

Thank you very much for the quick fix, @PatTheMav! 👏

**Comment by garrettreid** [comment]
+1, fixed an issue with solid green screen in Workplace Chat for me.
For anyone looking for a temporary workaround, I also found that opening another app to poll the camera (e.g. Zoom's video preferences) caused virtual camera to behave correctly.
