### ISSUE TITLE
Display capture cannot select primary display with a disconnected display

### ISSUE THREAD

**Issue by chticer** [obsproject/obs-studio#8040]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.0

### OBS Studio Log URL

https://obsproject.com/logs/q6ZPLlBOnHq4V9Yi

### Expected Behavior

Display capture should show the primary display whenever a display device is disconnected.

### Current Behavior

Display capture does not show the primary display whenever a display device is disconnected.

### Steps to Reproduce

1. Add at least 2 different display capture sources, including the primary display, then close OBS.
2. In Windows, go to Settings -> System -> Display, select a display that isn't the primary display then select "Disconnect this display" under Multiple displays and apply changes.
3. Open OBS. The primary display should now be black.
4. Open the display capture properties. Even though the display list contains the primary display, selecting it chooses another display.

### Anything else we should know?

I have always had 3 displays plugged in into my GPU with 1 of the displays disconnected most of the time. This was never an issue prior to OBS 29.0.0.

This is the log link of all 3 connected displays with 3 different display capture sources: [https://obsproject.com/logs/shhHTjCBdopCC3EO](https://obsproject.com/logs/shhHTjCBdopCC3EO)

**Comment by prgmitchell** [comment]
Repro steps left me with my primary monitor being displayed properly but the UI showing my secondary (portrait) monitor as the selected one.

![image](https://user-images.githubusercontent.com/86465454/211685522-5b74a84f-9e90-404b-866c-d45cf31bd9fc.png)

**Comment by jpark37** [comment]
I tried reproducing with two displays. Conveniently #1 is primary, and #2 is secondary in Windows settings on my PC.

- Set up scene with primary and secondary monitors display captured. Close OBS.
- Disconnect display 2 (in Windows 11, the option is "Show only on 1")
- Run OBS.
- Primary capture is still capturing primary. Secondary capture is blank. Both are as expected.
- Open display capture properties for secondary, and it selects primary, which is expected since it's the only display in the list. Clicking Cancel makes the display capture blank again.

I don't know if reproducing your issue requires three monitors, or Windows 10, but I'm not in a position to check either easily.

**Comment by chticer** [comment]
> I tried reproducing with two displays. Conveniently 1 is primary, and 2 is secondary in Windows settings on my PC.
> 
> * Set up scene with primary and secondary monitors display captured. Close OBS.
> * Disconnect display 2 (in Windows 11, the option is "Show only on 1")
> * Run OBS.
> * Primary capture is still capturing primary. Secondary capture is blank. Both are as expected.
> * Open display capture properties for secondary, and it selects primary, which is expected since it's the only display in the list. Clicking Cancel makes the display capture blank again.
> 
> I don't know if reproducing your issue requires three monitors, or Windows 10, but I'm not in a position to check either easily.

Hmm, could be possible that order matters. I did not map the OBS source names to the Windows display order correctly. Here is the mapping:

- OBS source "Monitor 3" is display 1 in Windows. This is the disconnected display.
- OBS source "Monitor 2" is display 2 in Windows. This is the secondary display.
- OBS source "Monitor 1" is display 3 in Windows. This is the primary display.

Also looking through the logs, when all three monitors are connected, it shows this from log shhHTjCBdopCC3EO:

> 17:12:48.303: [duplicator-monitor-capture: 'Monitor 3'] update settings:
> 17:12:48.303: 	display: LG TV (1920x1080)
> 17:12:48.303: 	cursor: true
> 17:12:48.303: 	method: DXGI
> 17:12:48.309: [duplicator-monitor-capture: 'Monitor 2'] update settings:
> 17:12:48.309: 	display: ASUS VS228 (1920x1080)
> 17:12:48.309: 	cursor: true
> 17:12:48.309: 	method: DXGI
> 17:12:48.316: [duplicator-monitor-capture: 'Monitor 1'] update settings:
> 17:12:48.316: 	display: ASUS VS228 (1920x1080)
> 17:12:48.316: 	cursor: true
> 17:12:48.316: 	method: DXGI

After disconnecting OBS source "Monitor 3", it shows this from log q6ZPLlBOnHq4V9Yi:

> 17:13:16.443: [duplicator-monitor-capture: 'Monitor 1'] update settings:
> 17:13:16.443: 	display:  (0x0)
> 17:13:16.443: 	cursor: true
> 17:13:16.443: 	method: WGC
> 17:13:16.447: [duplicator-monitor-capture: 'Monitor 2'] update settings:
> 17:13:16.447: 	display:  (0x0)
> 17:13:16.447: 	cursor: true
> 17:13:16.447: 	method: WGC
> 17:13:16.451: [duplicator-monitor-capture: 'Monitor 3'] update settings:
> 17:13:16.451: 	display: ASUS VS228 (1920x1080)
> 17:13:16.451: 	cursor: true
> 17:13:16.451: 	method: DXGI

It seems that OBS updated the source "Monitor 3" to be my secondary display and thinks that the primary display source has been disconnected.

**Comment by FloydNex** [comment]
Hi
I have the same issue since the last update (windows 10). With 2 monitor, I can select anything I want under screen capture properties, the only screen captured is the secondary screen. If I disable the secondary display, the primary is capture as it should but of course it's not usable for my way to work.

**Comment by chticer** [comment]
#8069 seems to be having some similar symptoms as well.

**Comment by jpark37** [comment]
This potential fix is really for the other issue, but maybe it'll help you. You can try the OBS build here:
https://github.com/obsproject/obs-studio/actions/runs/3955522487

Scroll to the bottom, and download obs-studio-windows-x64-e26d3b67f

**Comment by chticer** [comment]
Before I checked out this build, I went back to reproducing this bug in OBS 29.0.0 and now it is unreproducible. I tested the build for any regression and there is none. Not entirely sure how it fixed itself but doesn't seem there is anything to fix here.

**Comment by SquiIIiam** [comment]
Still having this problem 3+ years later
