### ISSUE TITLE
FFMPEG "Output to URL" does not use the selected codec

### ISSUE THREAD

**Issue by ma3uk** [obsproject/obs-studio#8043]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.0

### OBS Studio Log URL

https://obsproject.com/logs/ynqBly2EFUoLWObR

### Expected Behavior

Using the selected codec when output to the URL

### Current Behavior

libx264 is always used

### Steps to Reproduce

1. Select Advanced Output Mode
2. Select Custom Output (FFMPEG)
3. Select FFMPEG Output Type - Output to URL
4. Set any RTPM:// url (Twitch?)
5. Select FLV container format
6. Select h264_nvenc codec
7. Start record
![recording settings](https://user-images.githubusercontent.com/2519070/211793925-49af1da4-e46a-46bc-8b04-2a05d53388fc.png)
![cpu usage](https://user-images.githubusercontent.com/2519070/211793227-aecf073f-9ad9-4366-8bed-fa9281c80471.png)
![gpu usage](https://user-images.githubusercontent.com/2519070/211793244-916885ac-64ce-475c-be4f-5a45049b9c52.png)

### Anything else we should know?

After doing a little analysis, I found that this behavior occurs due to a condition in the obs-ffmpeg-output.c file on line 633, the condition is never met, so the libx264 codec is always installed
![code](https://user-images.githubusercontent.com/2519070/211792642-ab0d926d-8057-4d18-bafd-1eb7f574c363.png)

**Comment by Eageashik** [comment]
Borman
