### ISSUE TITLE
OBS 29.0 Crashes on Record

### ISSUE THREAD

**Issue by Jerry-Morgan** [obsproject/obs-studio#8045]
### Operating System Info

Ubuntu 20.04

### OBS Studio Version

29.0.0

### OBS Studio Log URL

https://obsproject.com/logs/iJLRbuErOYR2BWq2

### OBS Studio Crash Log URL

None Generated (I Think)

### Expected Behavior

With a scene in both studio windows I click on Start Recording. I expected OBS to start a xxx.mp4 file on my desktop.  At least it is set to Recording path-Home/Jerry/Desktop, Recording Format- mp4, Recording Quality- High Quality..., Encoder- Software (x264... This all worked in the previous version (unknown) which updated some where between uses.

### Current Behavior

With in a second OBS has closed.  I say closed because nothing happens as if I had clicked on the X in the Upper Right.

### Steps to Reproduce

1.  Open OBS
2. Pick a scene that I've  used before.
3. Transition that scene to the output window
4. click on Start Recording.
5. OBS closes (maybe crashes)
6. Open Desktop and discover that no file was created 
7. Re-Start OBS and fine everything just as it was before I clicked on Start recording
8.
9.
...

### Anything else we should know?

I only use this to make recordings so I can't tell you what it does in Start Streaming because I can't go beyond the Enter Key window. I have a meeting to record next week!  I'm glade I tried to set up my camera here at home.

**Comment by Fenrirthviti** [comment]
Please provide a gdb trace of the crash.

**Comment by Jerry-Morgan** [comment]
The previous version that worked was 28.1.2

**Comment by Jerry-Morgan** [comment]
I'm not a Command terminal guy.  I can cut and past if I have the commands but entering them without a step by step and exact commands just never works.  Is there something I can do from the GUI?

**Comment by Yamakuzure** [comment]
1. Open a console
2. Issue `ulimit -c unlimited`
3. Remove a previously placed core file with `rm -f core`
4. According to [this answer on askubuntu.com](https://askubuntu.com/questions/1349047/where-do-i-find-core-dump-files-and-how-do-i-view-and-analyze-the-backtrace-st/1442665#1442665) you need to fight against apport to get your core file by issuing: `echo 'core' | sudo tee /proc/sys/kernel/core_pattern`
5. Start obs from console (Probably `/usr/bin/obs-studio`? I am not on Linux right now)
6. Reproduce the crash.
7. Back in the console you should be seeing a statement, that a core dump has been written. You can check that is there with `ls -lh core`
( On Ubuntu 22.04 after `echo 'core' | sudo tee /proc/sys/kernel/core_pattern` the file is named as: `core.<pid>` )
8. You can now load the core file into gdb by issuing: `gdb /usr/bin/obs-studio core.12345` (example PID),
9. and then get the Backtrace in gdb using the command `bt`

However, there is another method you could use if the crash is quickly reproducable: Run OBS through gdb:
1. `gdb -ex run /usr/bin/obs-studio`
2. When the crash occurred you see a prompt in your gdb session where you can issue the `bt` command to get the backtrace.

The first method is good if you have to do quite some steps to get to the crashing, as running gdb would slow the program down. The second method is good if you can easily get to the crash or if there is some reason why you can not produce a core dump.

**Comment by Jerry-Morgan** [comment]
I removed version 29 and installed version 27.1.3 which works for me.  Obviously I can no longer produce the problem so I will close this ticket (unresolved)
