### ISSUE TITLE
Intel QSV H.264 encoder fails with 0 b-frames

### ISSUE THREAD

**Issue by JarodGu** [obsproject/obs-studio#8047]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.0

### OBS Studio Version (Other)

29.0 beta 3

### OBS Studio Log URL

https://obsproject.com/logs/z85LB9LL2naS27T7

### Expected Behavior

OBS should begin streaming or recording with the following settings:

Rate Control: CBR
Bitrate: 6000 Kbps
Target Usage: slower
Profile: high
Keyframe Interval: 4s
Latency: Normal
B frames: 0
Subjective Video Enhancements: Disabled

### Current Behavior

An error message says
`Starting the output failed. Please check the log for details. Note: If you are using the NVENC or AMD encoders, make sure your video drivers are up to date.`
I'm on the latest drivers for Intel UHD 630

Changing the b-frame parameter from 0 to 1 starts the stream/recording as expected
Modifying latency from normal to ultra-low also works with 0 b-frames

### Steps to Reproduce

1. Use Intel QSV H.264 for recording or streaming
2. Specify 0 b-frames and normal latency
3. Start stream or start recording

**Comment by RytoEX** [comment]
I cannot reproduce this while recording in OBS Studio 29.0.2 on Windows 10 21H2 system with an NVIDIA GTX 1060 (driver version 31.0.15.2802) and an Intel HD Graphics 630 (driver version 31.0.101.2115), even at 1080p120 with your exact settings. Consider updating your drivers, Windows, and/or OBS, and re-test.

**Comment by JarodGu** [comment]
Thanks for testing. I updated Intel UHD driver and Windows but get the same error on two separate PCs. Tested with a fresh OBS zip install running in portable and only parameter changed is Output->Advanced->QuickSync H.264->B frames 0

PC1 is Windows 10 22H2 on Intel driver 31.0.101.2121
https://obsproject.com/logs/iI3P2W9DPO4znpMu

PC2 is Windows 10 LTSC 1809 on Intel driver 31.0.101.2121
https://obsproject.com/logs/OeQ3cAO3PbTKarjg
