### ISSUE TITLE
Plugin does not appear in Sources

### ISSUE THREAD

**Issue by Chromagram** [obsproject/obs-studio#8060]
### Operating System Info

macOS 13

### OBS Studio Version

29.0.0

### OBS Studio Log URL

https://obsproject.com/logs/dAU15yx1LCGfj6q1

### Expected Behavior

https://github.com/CryZe/obs-livesplit-one

This plugin, once added, should appear as an addable source called LiveSplit One.

### Current Behavior

Currently, even once the plugin file is added, OBS does not pick it up and does not display the correct source option in the dropdown.

### Steps to Reproduce

1. From https://github.com/CryZe/obs-livesplit-one, download the plugin file. (Tried both x86_64 and aarc-darwin)
2. Try adding .so plugin file by going to Applications > OBS > Contents > Plugins. (Tried also separately adding file to ~/Library/Application Support/obs-studio/Plugins)
3. Close OBS Studio for Mac.
4. Reopen OBS Studio.
...

### Anything else we should know?

This plugin used to work before one of the OBS updates. I have reached out to the plugin dev since the original issue occurred, but they could not find anything specifically wrong with the plugin itself. This is why I am also asking on here to see if the OBS team can recognize why it isn't appearing.

**Comment by Fenrirthviti** [comment]
We do not maintain or develop this plugin, please report to the plugin developer.

**Comment by Fenrirthviti** [comment]
If the author is looking for guidance, they can use our forums or Discord to reach out, but I would prefer to keep bugs on our repo to the program we maintain, not third party plugins.
