### ISSUE TITLE
OBS 29.0 Auto Configuration Wizard does not use Apple Hardware Encoder

### ISSUE THREAD

**Issue by Piipperi** [obsproject/obs-studio#8061]
### Operating System Info

macOS 13

### OBS Studio Version

29.0.0

### OBS Studio Log URL

https://obsproject.com/logs/Ah0cmsp3e809ZyZl

### Expected Behavior

Changelogs for OBS 29.0 indicate Auto-Config Wizard says it would support Apple Hardware Encoder now

### Current Behavior

Auto-Config Wizard still just defaults to CPU encoding, when very clearly the CPU is a huge bottleneck.

### Steps to Reproduce

1. Updated to 29.0
2. Created new profile
3. Ran the Auto-Config Wizard at 2560x1440 @ 60 FPS
4. Doesn't even give me an option to use hardware encoding, resulting settings are for software encoding with low resolution

**Comment by gxalpha** [comment]
The wording on the release notes is a bit imprecise here, the hardware encoders will only be recommended on Apple Silicon machines with macOS 13 or newer. This is because those hardware encoders support the required rate control methods, which the Intel encoders don’t (on macOS at least).
