### ISSUE TITLE
Broken work in full screen mode at scale resolution

### ISSUE THREAD

**Issue by vaut** [obsproject/obs-studio#8063]
### Operating System Info

Ubuntu 20.04

### OBS Studio Version

29.0.0

### OBS Studio Log URL

https://obsproject.com/logs/yHHdOCQikd2n9jBf

### Expected Behavior

no graphic artifacts

### Current Behavior

When opening in full screen, part of the interface breaks
![output2](https://user-images.githubusercontent.com/697742/212477835-c499e49a-3293-45d2-ad03-01faba02f0dc.gif)
```
OpenGL version string: 4.6.0 NVIDIA 525.60.11
$ xrandr --current'
HDMI-0 connected 2560x2048+3840+0 (normal left inverted right x axis y axis) 380mm x 300mm
   1280x1024     60.02 +  75.02* 
DP-0 connected primary 3840x2160+0+0 (normal left inverted right x axis y axis) 700mm x 390mm
   3840x2160     60.00 + 143.98*  119.99    97.98    59.94    50.00    29.97    25.00    23.98 
```

### Steps to Reproduce

1. configure any monitor with scale other than 1
For example `xrandr --output HDMI-0 --scale 2x2`
2. expand the application to full screen
3. observe artifacts
4. bring the application back to the screen with scale 1x1
5. artifacts disappear

**Comment by kkartaltepe** [comment]
Is the gif supposed to be the recording from obs?

**Comment by vaut** [comment]
https://user-images.githubusercontent.com/697742/212492165-d9207259-40de-402b-ade5-fc99463c2afe.mp4

**Comment by vaut** [comment]
@kkartaltepe
Re-recorded the video. Github doesn't allow attaching mkv :(

https://user-images.githubusercontent.com/697742/212492904-052d68be-928c-4516-b66a-d1ac443b675a.mp4

**Comment by kkartaltepe** [comment]
Thanks , thats good.

**Comment by vaut** [comment]
ubuntu 22.04, OBS Studio - 29.0.2
The problem no longer reproduces
