### ISSUE TITLE
logitech HD Pro webcam C920 after WIN 11 update shows black screen

### ISSUE THREAD

**Issue by UweGSchulte** [obsproject/obs-studio#8067]
### Operating System Info

Windows 11

### OBS Studio Version

29.0.0

### OBS Studio Log URL

https://obsproject.com/logs/FhLenBO7tU8GIEZR

### Expected Behavior

Up to now the preview for the logitech webcam worked fine

### Current Behavior

No other usage of the camera is active; windows privacy settings are ok for OBS camera access; when trying the camera with other application it works fine. Driver for graphics card and camera are uptodate according to Win admin update screen.
In OBS the blue light for the camera comes on, one can change the settings and they change e.g. the zoom ( checked with logitech camera settings) just the preview screen stays black. I have reinstalled the camera, that did not change anything, restarted OBS and also Windows. It made no change

### Steps to Reproduce

1. Just start OBS with the USB Webcam plugged in and make the Videoinput visible
2.
3.
...

**Comment by Mister36MN** [comment]
I have the exact same webcam with Windows 11 and do not have this problem. Make sure your drivers are update to date and no other applications are using the webcam.

For further support issues please use the discord or forums.

**Comment by UweGSchulte** [comment]
Thank you for your quick reply. I am sorry for my misunderstanding. I clicked on forum/discord in OBS and ended up here. My mistake. Just to close the subject: as I pointed out before all drivers are up to date (double checked) and it had worked before.
I have now uninstalled OBS and re-installed without changing anything else and the camera is working again as it should be.
