### ISSUE TITLE
Second Display not shown in device list for Display Capture

### ISSUE THREAD

**Issue by philipp-fischer** [obsproject/obs-studio#8069]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.0

### OBS Studio Log URL

https://obsproject.com/logs/dqKWqWOW6WBcV8pE

### Expected Behavior

Dropdown list for display capture should show two monitors.

### Current Behavior

Dropdown list only shows primary monitor.

### Steps to Reproduce

1. Create a new scene
2. Add Display Capture source
3. Try to select second monitor from list of available displays.

The log clearly shows two 4K monitors `DELL U2720Q` and `Sound System`, but the second monitor dows not appear in the list.

### Anything else we should know?

**Everything worked fine before I updated OBS to 29.0.0**

**Comment by Fenrirthviti** [comment]
What exactly is your second display? Does it show up if you change the capture method manually to WGC?

**Comment by philipp-fischer** [comment]
The second display is connected to an HDMI output of the same NVIDIA GPU as the primary monitor.
The HDMI cable goes to an `Onkyo TX-L50` HDMI input which then connects to a `Samsung 55UJ6309` 4K TV.

**Comment by jpark37** [comment]
Your receiver doesn't seem to be sold in the USA... I'd buy one off of eBay to reproduce, but I don't want to find out on arrival that it's incompatible with my equipment. Anyone seeing this behavior with an American A/V receiver?

**Comment by jpark37** [comment]
If you want to test a potential fix, you can try the OBS build here:
https://github.com/obsproject/obs-studio/actions/runs/3955522487

Scroll to the bottom, and download obs-studio-windows-x64-e26d3b67f

**Comment by philipp-fischer** [comment]
Awesome. This fixes it.
