### ISSUE TITLE
x264: artifacts when encoding unsual frame sizes

### ISSUE THREAD

**Issue by lnicola** [obsproject/obs-studio#8072]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

29.0.0

### OBS Studio Log URL

https://obsproject.com/logs/hAX1BQ5RyjuVm2x8

### Expected Behavior

Output looks more or less good.

### Current Behavior

https://user-images.githubusercontent.com/308347/212696529-03c71577-2cdd-4449-9afc-c3528dad4a69.mp4

### Steps to Reproduce

1. choose Window Capture (PipeWire)
2. record a window
3. check the output

(does not always happen)

### Anything else we should know?

![image](https://user-images.githubusercontent.com/308347/212696666-eeb13b02-c46d-4bdf-9360-ac1e0afee1dc.png)

![image](https://user-images.githubusercontent.com/308347/212696678-a2ca792f-0240-45bf-9459-bd48d8639a11.png)

This is intermittent, but it's possible that it might be caused by odd (not divisible by 4) scene sizes. I can't precisely control the size of a window in GNOME, so it would be nice if OBS could handle this.

This one is:

```
   Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc, bt709/bt709/iec61966-2-1, progressive), 884x654 [SAR 1:1 DAR 442:327], 85 kb/s, 30 fps, 30 tbr, 15360 tbn (default)
```

**Comment by kkartaltepe** [comment]
Does the preview show this artifact?

**Comment by lnicola** [comment]
No.

**Comment by kkartaltepe** [comment]
Sounds like the issue is instead with the encoder, i have updated the issue title to reflect it.

**Comment by gxalpha** [comment]
Could you re-test this with the latest version of OBS and x264? If it still happens then, could you test using any other encoder? We think this is an issue with the encoder that we are unlikely to have control over.

(That said, it's probably not a good idea to have the size of a window you're capturing determine the size of your output in general)
