### ISSUE TITLE
Starting Stream or Recording crashes OBS (no dialog box pop-up)

### ISSUE THREAD

**Issue by BearsMan** [obsproject/obs-studio#8073]
### Operating System Info

Windows 11

### OBS Studio Version

29.0.0

### OBS Studio Log URL

https://obsproject.com/logs/sdmGxeO1IBPXkF6k

### OBS Studio Crash Log URL

https://obsproject.com/logs/sdmGxeO1IBPXkF6k

### Expected Behavior

I expected to record and/or stream and it stops right away at startup.

### Current Behavior

After hitting record and/or streaming, it stops and I will manually close OBS

### Steps to Reproduce

1. Opened OBS and had to switch to Streamlabs OBS for it to work
2. None (Tried Streaming and it stopped)
3. None (Tried Recording and it stopped)
...

### Anything else we should know?

[2023-01-16 10-21-41.txt](https://github.com/obsproject/obs-studio/files/10427111/2023-01-16.10-21-41.txt)

**Comment by gxalpha** [comment]
Could you please check if there are crash logs in the folder?

To find the OBS Studio crash logs, follow these steps:
1. Press WinKey+R to open the Run dialog
2. Type in: `%APPDATA%\obs-studio\crashes` and press Enter
3. Upload the desired crash log here

**Comment by BearsMan** [comment]
[Crash 2023-01-13 08-35-32.txt](https://github.com/obsproject/obs-studio/files/10446374/Crash.2023-01-13.08-35-32.txt)

This is the latest crash that I could find at the moment.

**Comment by BearsMan** [comment]
We can ignore this it's fixed
