### ISSUE TITLE
Pipewire screen recording not working

### ISSUE THREAD

**Issue by Timmmm** [obsproject/obs-studio#8103]
### Operating System Info

Other

### Other OS

RHEL 8

### OBS Studio Version

29.0.0

### OBS Studio Log URL

https://obsproject.com/logs/37pU4UVpCynvBoPW

### Expected Behavior

Add the `Screen Capture (Pipewire)` source, and it should show the screen.

### Current Behavior

It does let me add the source and even shows the "Select Monitor" dialog:

![image](https://user-images.githubusercontent.com/376842/213677368-8eec6667-57d3-4673-a761-d4fdf431c6cd.png)

![image](https://user-images.githubusercontent.com/376842/213677441-1f89edd5-f986-4225-ac1e-14dae131d05a.png)

However you only ever get a black screen and a 0x0px input.

![image](https://user-images.githubusercontent.com/376842/213677574-c3af57e7-2c1c-4b29-b868-f9d61bda1b3f.png)

### Steps to Reproduce

1. Install OBS
2. Try to add the Screen Capture Pipewire input.

### Anything else we should know?

Screen capture with Firefox *does* work.

Also the "Copy to Clipboard" button in the log upload dialog does not work, not can you even select the URL and press Ctrl-C! I had to click Analyze Logs and copy the URL from the web page.

**Comment by Timmmm** [comment]
Here is the relevant bit of the log for the benefit of Google:

```
10:41:31.423: [pipewire] Stream 0x55bcea33ae70 state: "connecting" (error: none)
10:41:31.423: [pipewire] Playing stream 0x55bcea33ae70
10:41:31.424: [pipewire] Stream 0x55bcea33ae70 state: "error" (error: wrong resource type/version)
10:41:31.424: [pipewire] Error id:2 seq:3 res:-71 (Unknown error -71): wrong resource type/version
10:41:31.424: [pipewire] Stream 0x55bcea33ae70 state: "unconnected" (error: none)
10:41:31.424: [pipewire] Error id:0 seq:4 res:-22 (Unknown error -22): unknown resource 2 op:2
10:41:31.424: [pipewire] Error id:0 seq:5 res:-22 (Unknown error -22): unknown resource 2 op:3
```

**Comment by Timmmm** [comment]
Seems like it might be a FlatPak-related issue based on [this thread](https://bugs.launchpad.net/ubuntu/+source/xdg-desktop-portal/+bug/1950040). I think 2023 might not be the Year of Linux on the Desktop.

**Comment by kkartaltepe** [comment]
basically, i dont think is ever going to work but you can probably file a bug to pipewire to see if they care to try and maintain compatibility back 50 versions. For the record they already broke compatibility 10 versions back to a much more popular user desktop.

**Comment by kkartaltepe** [comment]
We also have a hard requirement on something like pipewire 3.30 which I believe extends to the server but someone else would have give a more precise answer.

**Comment by Timmmm** [comment]
So is the issue that OBS depends on a newer version of Pipewire than the one I have?

Perhaps it could at least give a reasonable error in the UI.

**Comment by kkartaltepe** [comment]
Well i reviewed it and we have the assorted checks that suggest it should run on years old pipewire versions like 3.24. Since your pipewire is older than our plugin and no distributions use the version you are using, it was untested whether or not such a version would work. We dont put any checks to prevent it as pipewire's policy is that it "wont" break compatibility on the major version so it possible it could have worked I guess. Thanks for confirming it doesnt but im not sure we will implement any such check in the code still.

**Comment by Timmmm** [comment]
> no distributions use the version you are using

What do you mean? As far as I can tell I'm using the version that RHEL 8 provides (and Centos/Rocky) - 0.3.6. It's only 2 years old.

I did find that screen capture with OBS in X11 works flawlessly though, so that is good. I guess Wayland still isn't quite ready. Maybe in another decade or two :-P
