### ISSUE TITLE
Audio spilling over between scenes such that it overlaps

### ISSUE THREAD

**Issue by ElMagnificoGames** [obsproject/obs-studio#8118]
### Operating System Info

Other

### Other OS

Garuda Linux

### OBS Studio Version

29.0.0

### OBS Studio Log URL

https://obsproject.com/logs/6jA6mdAiB1ttXNnw

### Expected Behavior

Audio from the previous scene should stop playing by the end of a scene transition.

### Current Behavior

Audio from the previous scene overlaps with the current scene for a short period.

### Steps to Reproduce

Perform a scene transition whilst one or more "Media Source" sources are playing in the scene being transitioned from.

### Anything else we should know?

Please see this video of the issue:  https://youtu.be/Jg1vX6YuhCE

This is an intermittent issue.  Whilst investigating this, I discovered that the issue can be exacerbated by heavy disk load, although it persists after disk load has returned to normal (until OBS Studio is restarted).  Interestingly, this issue does not affect how quickly media in the destination scene starts to play, only how slowly it takes the source scene to cease playback.

I'm not particularly familiar with your code, but looking at the log file, I'm guessing that during times of heavier disk usage the part of OBS responsible for audio playback may be adding additional audio buffering as it cannot read the file quickly enough, which is never reverted (at least until OBS is restarted).  The problem then is that the "Media Source" refuses to stop playing audio during a scene transition until it has exhausted the contents of any existing buffer.  Obviously, my guess could be wildly wrong.  One problem with this theory is that the identified source in the log file, "OBS Mic Input", is not involved in the problem case at all (it is not present in any of the scenes I transitioned to or from).

I first encountered this problem in the version of OBS Studio that comes with the system package manager.  Since then, I have recompiled OBS from source, but sadly the issue still persists.

**Comment by gxalpha** [comment]
Looking at the video and the log, you are using audio monitoring to observe the problem.

Audio monitoring and the audio output to recordings/streams work very differently, with audio monitoring you're monitoring the input, not the output. The input (in this case from the media sources) will stay active until the transition is fully over, so it will keep playing in audio monitoring. It will however not appear on the output (the recording or stream made by OBS).

Closing this issue per the explanation above. In case the problem can also be observed in the recording produced by OBS, feel free to reopen the issue (and make sure to attach said recording).
