### ISSUE TITLE
我的显卡驱动是最新的，为啥报错说n卡audio and video sdk过期

### ISSUE THREAD

**Issue by carryyourself** [obsproject/obs-studio#8119]
### Operating System Info

Windows 11

### OBS Studio Version

29.0.0

### OBS Studio Log URL

23:10:59.598: CPU Name: 13th Gen Intel(R) Core(TM) i5-13600KF 23:10:59.598: CPU Speed: 3494MHz 23:10:59.598: Physical Cores: 14, Logical Cores: 20 23:10:59.598: Physical Memory: 16193MB Total, 10624MB Free 23:10:59.598: Windows Version: 10.0 Build 22621 (release: 22H2; revision: 1105; 64-bit) 23:10:59.598: Running as administrator: false 23:10:59.598: Windows 10/11 Gaming Features: 23:10:59.598: 	Game Bar: Off 23:10:59.598: 	Game DVR: Off 23:10:59.598: 	Game DVR Background Recording: Off 23:10:59.598: 	Game Mode: On 23:10:59.598: 	Hardware GPU Scheduler: On 23:10:59.599: Sec. Software Status: 23:10:59.600:  23:10:59.600:  23:10:59.600:  23:10:59.600:  23:10:59.600: Current Date/Time: 2023-01-22, 23:10:59 23:10:59.600: Browser Hardware Acceleration: true 23:10:59.600: Hide OBS windows from screen capture: false 23:10:59.600: Qt Version: 6.3.1 (runtime), 6.3.1 (compiled) 23:10:59.600: Portable mode: false 23:10:59.789: OBS 29.0.0 (64-bit, windows) 23:10:59.789: --------------------------------- 23:10:59.789: --------------------------------- 23:10:59.789: audio settings reset: 23:10:59.789: 	samples per sec: 44100 23:10:59.789: 	speakers:        2 23:10:59.789: 	max buffering:   1044 milliseconds 23:10:59.789: 	buffering type:  dynamically increasing 23:10:59.790: --------------------------------- 23:10:59.790: Initializing D3D11... 23:10:59.790: Available Video Adapters:  23:10:59.791: 	Adapter 0: NVIDIA GeForce RTX 3060 Ti 23:10:59.791: 	  Dedicated VRAM: 4133486592 23:10:59.791: 	  Shared VRAM:    4195211264 23:10:59.791: 	  PCI ID:         10de:2486 23:10:59.791: 	  Driver Version: 31.0.15.2802 23:10:59.792: 	  output 0: 23:10:59.792: 	    name=25G3Z 23:10:59.792: 	    pos={0, 0} 23:10:59.792: 	    size={1920, 1080} 23:10:59.792: 	    attached=true 23:10:59.792: 	    refresh=240 23:10:59.792: 	    space=RGB_FULL_G22_NONE_P709 23:10:59.792: 	    sdr_white_nits=80 23:10:59.792: 	    nit_range=[min=0.000000, max=426.859802, max_full_frame=426.859802] 23:10:59.792: Loading up D3D11 on adapter NVIDIA GeForce RTX 3060 Ti (0) 23:10:59.854: D3D11 loaded successfully, feature level used: b000 23:10:59.854: DXGI increase maximum frame latency success 23:10:59.854: D3D11 GPU priority setup failed (not admin?) 23:11:00.667: --------------------------------- 23:11:00.667: video settings reset: 23:11:00.667: 	base resolution:   1920x1080 23:11:00.667: 	output resolution: 1920x1080 23:11:00.667: 	downscale filter:  Bicubic 23:11:00.667: 	fps:               60/1 23:11:00.667: 	format:            NV12 23:11:00.667: 	YUV mode:          Rec. 709/Partial 23:11:00.667: NV12 texture support enabled 23:11:00.667: P010 texture support not available 23:11:00.668: Audio monitoring device: 23:11:00.668: 	name: 默认 23:11:00.668: 	id: default 23:11:00.669: --------------------------------- 23:11:00.670: No AJA devices found, skipping loading AJA UI plugin 23:11:00.670: Failed to initialize module 'aja-output-ui.dll' 23:11:00.671: No AJA devices found, skipping loading AJA plugin 23:11:00.671: Failed to initialize module 'aja.dll' 23:11:00.671: Skipping module '../../obs-plugins/64bit/chrome_elf.dll', not an OBS plugin 23:11:00.671: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded 23:11:00.672: Failed to load 'en-US' text for module: 'decklink-captions.dll' 23:11:00.672: Failed to load 'en-US' text for module: 'decklink-output-ui.dll' 23:11:00.674: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed 23:11:00.674: Failed to initialize module 'decklink.dll' 23:11:00.690: [AMF] Unable to load 'amfrt64.dll', error code 126. 23:11:00.691: [AMF] AMF Test failed due to one or more errors. 23:11:00.691: Failed to initialize module 'enc-amf.dll' 23:11:00.695: Skipping module '../../obs-plugins/64bit/libcef.dll', not an OBS plugin 23:11:00.695: Skipping module '../../obs-plugins/64bit/libEGL.dll', not an OBS plugin 23:11:00.695: Skipping module '../../obs-plugins/64bit/libGLESv2.dll', not an OBS plugin 23:11:00.701: [obs-browser]: Version 2.19.0 23:11:00.701: [obs-browser]: CEF Version 103.0.5060.134 (runtime), 103.0.0-5060-shared-textures.2591+g4204d54+chromium-103.0.5060.134 (compiled) 23:11:00.702: NVENC supported 23:11:00.791: [NVENC] AV1 is not supported 23:11:00.792: [noise suppress]: NVIDIA denoiser disabled, redistributable not found or could not be loaded. 23:11:00.792: Failed to get NVVideoEffects.dll version info size 23:11:00.792: [NVIDIA VIDEO FX]: FX disabled, redistributable not found or could not be loaded. 23:11:00.816: [obs-websocket] [obs_module_load] you can haz websockets (Version: 5.1.0 | RPC Version: 1) 23:11:00.816: [obs-websocket] [obs_module_load] Qt version (compile-time): 6.3.1 | Qt version (run-time): 6.3.1 23:11:00.816: [obs-websocket] [obs_module_load] Linked ASIO Version: 101201 23:11:00.821: [obs-websocket] [obs_module_load] Module loaded. 23:11:00.822: [vlc-video]: Couldn't find VLC installation, VLC video source disabled 23:11:00.825: --------------------------------- 23:11:00.825:   Loaded Modules: 23:11:00.825:     win-wasapi.dll 23:11:00.825:     win-mf.dll 23:11:00.825:     win-dshow.dll 23:11:00.825:     win-capture.dll 23:11:00.825:     vlc-video.dll 23:11:00.825:     text-freetype2.dll 23:11:00.825:     rtmp-services.dll 23:11:00.825:     obs-x264.dll 23:11:00.825:     obs-websocket.dll 23:11:00.825:     obs-vst.dll 23:11:00.825:     obs-transitions.dll 23:11:00.825:     obs-text.dll 23:11:00.825:     obs-qsv11.dll 23:11:00.825:     obs-outputs.dll 23:11:00.825:     obs-filters.dll 23:11:00.825:     obs-ffmpeg.dll 23:11:00.825:     obs-browser.dll 23:11:00.825:     image-source.dll 23:11:00.825:     frontend-tools.dll 23:11:00.825:     decklink-output-ui.dll 23:11:00.825:     decklink-captions.dll 23:11:00.825:     coreaudio-encoder.dll 23:11:00.825: --------------------------------- 23:11:00.826: ==== Startup complete =============================================== 23:11:00.860: All scene data cleared 23:11:00.860: ------------------------------------------------ 23:11:00.874: [win-wasapi: '桌面音频'] update settings: 23:11:00.874: 	device id: default 23:11:00.874: 	use device timing: 1 23:11:00.875: [Loaded global audio device]: '桌面音频' 23:11:00.875: [win-wasapi: '麦克风/Aux'] update settings: 23:11:00.875: 	device id: default 23:11:00.875: 	use device timing: 0 23:11:00.876: [noise suppress: '噪声抑制'] NVAFX redist is not installed. 23:11:00.876: [WASAPISource::TryInitialize]:[default] Failed GetDefaultAudioEndpoint: 80070490 23:11:00.876: WASAPI: Device 'default' failed to start (source: 麦克风/Aux) 23:11:00.877: [Loaded global audio device]: '麦克风/Aux' 23:11:00.877:     - filter: '噪声抑制' (noise_suppress_filter_v2) 23:11:00.890: WASAPI: Device '扬声器 (Realtek High Definition Audio)' [48000 Hz] initialized 23:11:01.231: Switched to scene '场景' 23:11:01.231: ------------------------------------------------ 23:11:01.231: Loaded scenes: 23:11:01.231: - scene '场景': 23:11:01.231:     - source: '游戏源' (game_capture) 23:11:01.231: ------------------------------------------------ 23:11:13.262: Failed to read log file C:\Users\25527\AppData\Roaming\obs-studio/crashes/ 23:11:28.155: Failed to read log file C:\Users\25527\AppData\Roaming\obs-studio/crashes/

### Expected Behavior

噪音抑制滤镜的时候不会提示我sdk过期

### Current Behavior

噪音抑制滤镜的时候提示我sdk过期

### Steps to Reproduce

1.
2.
3.
...
xxx

**Comment by kkartaltepe** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
