### ISSUE TITLE
OBS incompatible with Bandicam

### ISSUE THREAD

**Issue by TheArtOfGriefing** [obsproject/obs-studio#8131]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.0

### OBS Studio Log URL

https://obsproject.com/logs/Pm1yK997vlmcA2QV

### Expected Behavior

OBS should capture specific windows while Bandicam is running.

### Current Behavior

OBS doesn't capture certain games (black screen), or the capture is frozen on a single frame while Bandicam is running.

### Steps to Reproduce

1. Launch Bandicam and OBS in any order
2. Create a game capture source
3. Launch the game

### Anything else we should know?

Downgrading OBS to version 27 fixes the issue entirely. Recording the entire screen also works fine, it's just that the window capture feature is broken. Killing all of Bandicam's processes also removes the issue.
Unfortunately, it's not an option for me to replace either OBS or Bandicam, and I would like to keep OBS updated, so I'm posting this here in case someone comes up with a solution or confirms this is a bug.

The specific game I need this for is Castle Crashers and the specific function I need from Bandicam is a hotkey to lower the game's framerate, none of the video recording features are used.

**Comment by Fenrirthviti** [comment]
```
21:20:09.824: [game-capture: 'Castle Crashers'] d3d9 shared texture capture successful
21:20:09.835: [game-capture: 'Castle Crashers'] shared texture capture successful
```

Seems like OBS is able to hook properly, but Bandicam is doing something that is either conflicting with, or breaking our capture. This will almost definitely need to be reported to them.

**Comment by TheArtOfGriefing** [comment]
But then I don't understand how come installing an earlier version of OBS could resolve the issue. Clearly it's something in OBS that changed, which is preventing it from working in the newer versions. Or maybe I just didn't configure something correctly.
I could try contacting Bandicam, but in all honesty, it seems like a totally futile effort. I highly doubt they will bother fixing their software to accommodate a couple of people who are experiencing this rare issue. They don't even have a dedicated support email address.

**Comment by RytoEX** [comment]
> But then I don't understand how come installing an earlier version of OBS could resolve the issue. Clearly it's something in OBS that changed, which is preventing it from working in the newer versions. Or maybe I just didn't configure something correctly. I could try contacting Bandicam, but in all honesty, it seems like a totally futile effort. I highly doubt they will bother fixing their software to accommodate a couple of people who are experiencing this rare issue. They don't even have a dedicated support email address.

We changed our hooking mechanism in 27.1 to use Detours instead of our own custom hooking functions. See #4720. When we did this, we also saw an uptick in failure reports for users using RTSS. Subsequently, RTSS added an option to also use Detours. That is what we would recommend Bandicam does, as we are unlikely to revert our hook changes.

**Comment by TheArtOfGriefing** [comment]
Got it, thank you!
