### ISSUE TITLE
OBS Studio stopped working, uninstalled, now cant reinstall from Microsoft Store

### ISSUE THREAD

**Issue by lockerus** [obsproject/obs-studio#8132]
### Operating System Info

Windows 11

### OBS Studio Version

29.0.0

### OBS Studio Log URL

n/a

### Expected Behavior

1. Log in to PC
2. Open OBS Studio
3. Use the app

### Current Behavior

OBS Studio missing as an app on my PC, tried to uninstall, now cant reinstall because it gives me an error which directs me to here.

### Steps to Reproduce

1. Log in to PC
2. Try to find OBS Studio
3. App is missing
...

### Anything else we should know?

OBS Studio is installed on my work PC and I work at Microsoft. My other colleagues havent had issues with their OBS Studio though.

**Comment by gxalpha** [comment]
No error message has been provided.
