### ISSUE TITLE
Alpha channel recording not working since OBS 28.0.3

### ISSUE THREAD

**Issue by JustDalek** [obsproject/obs-studio#8133]
### Operating System Info

Windows 11

### Other OS

windows 10 and 11

### OBS Studio Version

28.1.2

### OBS Studio Log URL

https://obsproject.com/logs/WXO1NIh3xBJPOsAJ

### Expected Behavior

Record video with alpha channel transparency

### Current Behavior

Footage does not have alpha channel, and renders alpha as black

### Steps to Reproduce

WORKING V28.0.3:
1. Install OBS
2. Navigate to settings>Output
3. Set output mode to advanced
4. Go to recording tab
5. Set the following settings:
![image](https://user-images.githubusercontent.com/78516780/214217686-535f5b3b-c93a-4ffc-b6db-9ec068e500d3.png)
6. Go to advanced settings
7. Set Color format to RGB
8. Record
9. Product:

https://user-images.githubusercontent.com/78516780/214217788-e7cc05a2-6913-4a04-99f7-de29f022e0e7.mov

NOT WORKING V29
1. Install OBS
2. Navigate to settings>Output
3. Set output mode to advanced
4. Go to recording tab
5. Set the following settings:
![image](https://user-images.githubusercontent.com/78516780/214217686-535f5b3b-c93a-4ffc-b6db-9ec068e500d3.png)
6. Go to advanced settings
7. Set Color format to RGBA
8. Record
9. Product:

https://user-images.githubusercontent.com/78516780/214217902-31842642-534d-462d-b7a6-aa176e1a9622.mov

These videos can be opened in davinci resolve or any other video editor that supports alpha channel to check the transparency, but for context I went ahead and obtained the following screenshots of what happens

OBS 28.0.3
![image](https://user-images.githubusercontent.com/78516780/214218193-dcee1320-817c-4e0c-b777-53bd07fa8569.png)

OBS 29
![image](https://user-images.githubusercontent.com/78516780/214218233-72a9b0d7-93d2-4a93-ac8d-8bb2deca676b.png)

### Anything else we should know?

We discovered this issue through updating, and slowly downgraded release by release, it appears this was last working on obs 28.0.3. Anything after does not work.

**Comment by Fenrirthviti** [comment]
Just as a note to anyone looking at this, I'm reasonably sure that we don't consider this a supported use case, at least currently. It was a surprise to most of us on the project that this ever worked in the first place.

Which is to say, I don't think there is a bug that needs to be fixed or a regression that needs to be investigate, but more of a core change in philosophy of how we handle alpha on output. If we want to support alpha output, we should do so properly, not with a set of undocumented magic settings that happened to work incidentally.

I'll leave this open for visibility for now, but at this point, my opinion is that this is a feature request.

**Comment by JustDalek** [comment]
Thank you for your consideration!. I hope we gather enough interest for it to become a supported feature. The demographic for this (at least in my case) is virtual creators/vtubers. We can make great use of an alpha channel 💜

**Comment by flaeri** [comment]
I figured I'd do a little write up to tidy you over for the moment. Completely unsupported, but it works for the time being. Here is what I do when I want/need alpha chanel output:

You can use `pixel_format=xxxx` in the "Video Encoder" field.

You can find the supported pixel format in ffmpeg by querying the encoder for its supported pixel formats via: `ffmpeg -h encoder=xxxx` (seperate from OBS).

The alpha supported formats usually have an "a" (alpha) in their name. For example, PNG that would be "rgba", cineform is "grabp12le" and qtrle would be "argb". There are more, but you get the gist.

As the devs have said, this is in *no* way supported. It can and will (as we've seen) break at any point. Just a happy accident ;)

**Comment by Knipnogg** [comment]
Also very interested in this! I know it's all unofficial, but I am also having an issue where it appears that RGB is not an option for Color Format for me. I am using OBS 29.0.0. Do I need a plugin?

Thanks!

**Comment by JustDalek** [comment]
> I figured I'd do a little write up to tidy you over for the moment. Completely unsupported, but it works for the time being. Here is what I do when I want/need alpha chanel output:
> 
> You can use `pixel_format=xxxx` in the "Video Encoder" field.
> 
> You can find the supported pixel format in ffmpeg by querying the encoder for its supported pixel formats via: `ffmpeg -h encoder=xxxx` (seperate from OBS).
> 
> The alpha supported formats usually have an "a" (alpha) in their name. For example, PNG that would be "rgba", cineform is "grabp12le" and qtrle would be "argb". There are more, but you get the gist.
> 
> As the devs have said, this is in _no_ way supported. It can and will (as we've seen) break at any point. Just a happy accident ;)

Thank you for this!. Me and a friend are on 28.0.3 for the time being, but since upgrading and downgrading is so easy I will happily give this a try. Thank you! 😁😁🙌

**Comment by Knipnogg** [comment]
> > I figured I'd do a little write up to tidy you over for the moment. Completely unsupported, but it works for the time being. Here is what I do when I want/need alpha chanel output:
> > You can use `pixel_format=xxxx` in the "Video Encoder" field.
> > You can find the supported pixel format in ffmpeg by querying the encoder for its supported pixel formats via: `ffmpeg -h encoder=xxxx` (seperate from OBS).
> > The alpha supported formats usually have an "a" (alpha) in their name. For example, PNG that would be "rgba", cineform is "grabp12le" and qtrle would be "argb". There are more, but you get the gist.
> > As the devs have said, this is in _no_ way supported. It can and will (as we've seen) break at any point. Just a happy accident ;)
> 
> Thank you for this!. Me and a friend are on 28.0.3 for the time being, but since upgrading and downgrading is so easy I will happily give this a try. Thank you! 😁😁🙌

If you come up with something, please let me know! :)

**Comment by JustDalek** [comment]
> > > I figured I'd do a little write up to tidy you over for the moment. Completely unsupported, but it works for the time being. Here is what I do when I want/need alpha chanel output:
> > > You can use `pixel_format=xxxx` in the "Video Encoder" field.
> > > You can find the supported pixel format in ffmpeg by querying the encoder for its supported pixel formats via: `ffmpeg -h encoder=xxxx` (seperate from OBS).
> > > The alpha supported formats usually have an "a" (alpha) in their name. For example, PNG that would be "rgba", cineform is "grabp12le" and qtrle would be "argb". There are more, but you get the gist.
> > > As the devs have said, this is in _no_ way supported. It can and will (as we've seen) break at any point. Just a happy accident ;)
> > 
> > 
> > Thank you for this!. Me and a friend are on 28.0.3 for the time being, but since upgrading and downgrading is so easy I will happily give this a try. Thank you! 😁😁🙌
> 
> If you come up with something, please let me know! :)

Sure thing, but do be advised, it does work on 28.0.3

Best of all, it even works through NDI! (Sending to another computer)

**Comment by JustDalek** [comment]
> 

I'm not familiar with

> > > > > I figured I'd do a little write up to tidy you over for the moment. Completely unsupported, but it works for the time being. Here is what I do when I want/need alpha chanel output:
> > > > > You can use `pixel_format=xxxx` in the "Video Encoder" field.
> > > > > You can find the supported pixel format in ffmpeg by querying the encoder for its supported pixel formats via: `ffmpeg -h encoder=xxxx` (seperate from OBS).
> > > > > The alpha supported formats usually have an "a" (alpha) in their name. For example, PNG that would be "rgba", cineform is "grabp12le" and qtrle would be "argb". There are more, but you get the gist.
> > > > > As the devs have said, this is in _no_ way supported. It can and will (as we've seen) break at any point. Just a happy accident ;)
> > > > 
> > > > 
> > > > Thank you for this!. Me and a friend are on 28.0.3 for the time being, but since upgrading and downgrading is so easy I will happily give this a try. Thank you! 😁😁🙌
> > > 
> > > 
> > > If you come up with something, please let me know! :)
> > 
> > 
> > Sure thing, but do be advised, it does work on 28.0.3
> > Best of all, it even works through NDI! (Sending to another computer)
> 
> Great to know! I can certainly downgrade (I think), but I still don't know how to find RGB as a color format or how to "query the encoder" to find the pixel formats. Would someone mind explaining that process to me?

Im not familiar with that either to be honest, it's something I will be checking on that this afternoon if I have time. My method (in my reproduction steps) does not require any of that. Tested on 3 different computers myself and with a friend.

But the encoder part, it sounds like I need to install FFMPEG and run that command. I haven't used FFMPEG in CLI before, but have used many applications that implement it. Shouldn't be that bad I dont think
