### ISSUE TITLE
Custom browser docks not consistently docking to UI.

### ISSUE THREAD

**Issue by lindenkron** [obsproject/obs-studio#8140]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.0

### OBS Studio Log URL

https://obsproject.com/logs/VLaBiA5Ppqra8G2d

### Expected Behavior

Upon dragging a custom browser dock to a dockable position, it should dock on first drag.
**Example:**
https://streamable.com/aaq442

### Current Behavior

The custom browser dock does not properly dock consistently, and may take multiple attempts before it works.

### Steps to Reproduce

1. Install clean OBS v29
2. Add a custom browser dock (https://google.com)
3. Drag it to where it should dock.

### Anything else we should know?

- If you drag a dock that's _**already**_ docked, it **will** dock properly.
- If you double click a dock it **will** dock properly.
- This faulty behaviour is present in v29 & v28.1.2.
- This faulty behaviour is **not** present in v27.2.4

**Comment by RytoEX** [comment]
I'm going to hazard a guess that this is a Qt bug. Probably this one: https://bugreports.qt.io/browse/QTBUG-106530

**Comment by lindenkron** [comment]
> I'm going to hazard a guess that this is a Qt bug. Probably this:
> 
>     * https://bugreports.qt.io/browse/QTBUG-106530
> 
> 
> A good way to confirm might be to test the OBS Studio 29 beta releases, which were built against Qt 6.4.1. There are some other related issues with docks that are not fixed until Qt 6.4.3+.

Rob tested it in 29b3, and said there were no docking issues like this in there, so this does seems like an explanation to that.

**Comment by WizardCM** [comment]
I have also seen such weird docking behaviour lately (across all platforms). I've been using the "double click" method as a temporary workaround. I second that it's a Qt bug, and will continue testing Qt versions to see how things improve.
