### ISSUE TITLE
After the OBS was restarted, Steam displays the status is not running.

### ISSUE THREAD

**Issue by TianQiBuTian** [obsproject/obs-studio#8154]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

Steam version

### OBS Studio Log URL

I don't think need this log file

### Expected Behavior

After the OBS was restarted, Steam displays the status is running.

### Current Behavior

Steam displays the status is not running.

### Steps to Reproduce

https://user-images.githubusercontent.com/26628474/214877390-1af065ad-7a67-4811-adeb-7305a9b30a7d.mp4

1. Change the configuration that requires restarting the OBS.
2. That's it.

**Comment by derrod** [comment]
When OBS is restarted this way we use `QProcess::startDetached` which is probably why Steam loses track of the obs process. I don't think we can really fix it, nor would it be worth the effort imo.
