### ISSUE TITLE
Segmentation fault (core dumped) at start

### ISSUE THREAD

**Issue by c3kkos** [obsproject/obs-studio#8158]
### Operating System Info

Other

### Other OS

Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy

### OBS Studio Version

29.0.0

### OBS Studio Version (Other)

OBS 27.2.3+dfsg1-1 (linux)

### OBS Studio Log URL

got none!

### OBS Studio Crash Log URL

got none!

### Expected Behavior

the program to start

### Current Behavior

the program crashes almost immediatly with this output:

~$ obs
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/locale.ini
Attempted path: /usr/share/obs/obs-studio/locale.ini
Attempted path: share/obs/obs-studio/themes/Dark.qss
Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
info: CPU Name: Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz
info: CPU Speed: 2394.157MHz
info: Physical Cores: 2, Logical Cores: 2
info: Physical Memory: 3894MB Total, 355MB Free
info: Kernel Version: Linux 6.1.0-7.2-liquorix-amd64
info: Distribution: "Linux Mint" "21.1"
info: Session Type: x11
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.21.1
info: Qt Version: 5.15.3 (runtime), 5.15.2 (compiled)
info: Portable mode: false
Attempted path: share/obs/obs-studio/themes/Dark/no_sources.svg
Attempted path: /usr/share/obs/obs-studio/themes/Dark/no_sources.svg
QMetaObject::connectSlotsByName: No matching signal for on_tbar_position_valueChanged(int)
QMetaObject::connectSlotsByName: No matching signal for on_actionShowTransitionProperties_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_actionHideTransitionProperties_triggered()
info: OBS 27.2.3+dfsg1-1 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 48000
	speakers:        2
info: ---------------------------------
info: Initializing OpenGL...
info: Loading up OpenGL on adapter X.Org AMD RV710 (DRM 2.50.0 / 6.1.0-7.2-liquorix-amd64, LLVM 13.0.1)
info: OpenGL loaded successfully, version 3.3 (Core Profile) Mesa 22.0.5, shading language 3.30
info: ---------------------------------
info: video settings reset:
	base resolution:   1366x768
	output resolution: 1092x614
	downscale filter:  Bicubic
	fps:               30/1
	format:            NV12
	YUV mode:          709/Partial
info: NV12 texture support not available
info: Audio monitoring device:
	name: Default
	id: default
info: ---------------------------------
Segmentation fault (core dumped)

### Steps to Reproduce

1. launch obs in terminal
2. watch it
3.
...

### Anything else we should know?

this is inxi -Fxxrzc0 output:

~$ inxi -Fxxrzc0
System:
  Kernel: 6.1.0-7.2-liquorix-amd64 x86_64 bits: 64 compiler: gcc v: 11.3.0
    Desktop: Xfce 4.16.0 tk: Gtk 3.24.23 wm: xfwm dm: LightDM
    Distro: Linux Mint 21.1 Vera base: Ubuntu 22.04 jammy
Machine:
  Type: Portable System: Dell product: Studio 1555 v: A13
    serial: <superuser required>
  Mobo: Dell model: 0C234M v: A13 serial: <superuser required> BIOS: Dell
    v: A13 date: 04/02/2011
Battery:
  ID-1: BAT0 charge: 4.7 Wh (100.0%) condition: 4.7/4.4 Wh (106.0%)
    volts: 7.7 min: 11.1 model: SIMPLO Dell serial: <filter> status: Full
CPU:
  Info: dual core model: Intel Core2 Duo P8600 bits: 64 type: MCP
    arch: Core Yorkfield rev: A cache: L1: 128 KiB L2: 3 MiB
  Speed (MHz): avg: 2045 high: 2401 min/max: 800/2401 boost: enabled cores:
    1: 1690 2: 2401 bogomips: 9575
  Flags: ht lm nx pae sse sse2 sse3 sse4_1 ssse3 vmx
Graphics:
  Device-1: AMD RV710/M92 [Mobility Radeon HD 4530/4570/545v] vendor: Dell
    driver: radeon v: kernel pcie: speed: 2.5 GT/s lanes: 16 ports:
    active: LVDS-1 empty: HDMI-A-1,VGA-1 bus-ID: 01:00.0 chip-ID: 1002:9553
  Device-2: Microdia Laptop_Integrated_Webcam_2M type: USB driver: uvcvideo
    bus-ID: 1-6:2 chip-ID: 0c45:63ea
  Display: x11 server: X.Org v: 1.21.1.3 compositor: xfwm v: 4.16.1 driver:
    X: loaded: ati,radeon unloaded: fbdev,modesetting,vesa gpu: radeon
    display-ID: :0.0 screens: 1
  Screen-1: 0 s-res: 1366x768 s-dpi: 96
  Monitor-1: LVDS res: 1366x768 dpi: 101 diag: 394mm (15.5")
  OpenGL:
    renderer: AMD RV710 (DRM 2.50.0 / 6.1.0-7.2-liquorix-amd64 LLVM 13.0.1)
    v: 3.3 Mesa 22.0.5 compat-v: 3.0 direct render: Yes
Audio:
  Device-1: Intel 82801I HD Audio vendor: Dell driver: snd_hda_intel
    v: kernel bus-ID: 00:1b.0 chip-ID: 8086:293e
  Device-2: AMD RV710/730 HDMI Audio [Radeon HD 4000 series] vendor: Dell
    driver: snd_hda_intel v: kernel pcie: speed: 2.5 GT/s lanes: 16
    bus-ID: 01:00.1 chip-ID: 1002:aa38
  Sound Server-1: ALSA v: k6.1.0-7.2-liquorix-amd64 running: yes
  Sound Server-2: JACK v: 1.9.20 running: no
  Sound Server-3: PulseAudio v: 15.99.1 running: no
  Sound Server-4: PipeWire v: 0.3.63 running: yes
Network:
  Device-1: Intel WiFi Link 5100 driver: iwlwifi v: kernel pcie:
    speed: 2.5 GT/s lanes: 1 bus-ID: 04:00.0 chip-ID: 8086:4232
  IF: wlp4s0 state: up mac: <filter>
  Device-2: Broadcom NetLink BCM5784M Gigabit Ethernet PCIe vendor: Dell
    driver: tg3 v: kernel pcie: speed: 2.5 GT/s lanes: 1 port: N/A
    bus-ID: 08:00.0 chip-ID: 14e4:1698
  IF: enp8s0 state: down mac: <filter>
Drives:
  Local Storage: total: 111.79 GiB used: 30.53 GiB (27.3%)
  ID-1: /dev/sda vendor: Samsung model: SSD 840 Series size: 111.79 GiB
    speed: 3.0 Gb/s serial: <filter>
Partition:
  ID-1: / size: 108.98 GiB used: 30.52 GiB (28.0%) fs: ext4 dev: /dev/sda3
  ID-2: /boot/efi size: 512 MiB used: 5.2 MiB (1.0%) fs: vfat
    dev: /dev/sda2
Swap:
  ID-1: swap-1 type: file size: 2 GiB used: 297.2 MiB (14.5%) priority: -2
    file: /swapfile
Sensors:
  System Temperatures: cpu: 58.0 C mobo: 49.0 C gpu: radeon temp: 57.5 C
  Fan Speeds (RPM): cpu: 0 fan-2: 0 fan-3: 0

i feel the two things that my system have that might cause this issue are:

pipewire with wireplumber?
liquorix kernel?

**Comment by WizardCM** [comment]
Please provide a gdb backtrace.

**Comment by derrod** [comment]
Additionally, you're using an old and third-party build of OBS. Since you are on a Ubuntu derivate you should be able to use our official PPA for the latest version: https://launchpad.net/~obsproject/+archive/ubuntu/obs-studio

Please confirm that whatever issue you're having also occurs with that version and provide a backtrace.

**Comment by c3kkos** [comment]
Switching to the PPA updated version fixed it.

info: OBS 29.0.0 (linux)

now up & running flawlessy.

This means that the official jammy repo obs .deb is somehow broken, and should be noticed.

Thank you.

**Comment by RytoEX** [comment]
We don't maintain that repository. Someone is welcome to report this to them.
