### ISSUE TITLE
Hide yellow border when using Windows 10 capture method for window capture

### ISSUE THREAD

**Issue by Alveel** [obsproject/obs-studio#8159]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.0

### OBS Studio Log URL

https://obsproject.com/logs/dhbzS7f4jQB5faH5

### Expected Behavior

When using the Windows 10 capture method for window capture, a yellow border appears around the captured window. Users should be able to hide this border.

### Current Behavior

The border always shows up. This is a feature of Windows 10, and not caused by OBS. You cannot currently disable the border.

### Steps to Reproduce

1. In a scene, add a window capture source
2. In the window capture source properties, select the window you want to capture, and set the capture method to "Windows 10 (1903 and up)"
3. Notice the yellow border around the selected window

### Anything else we should know?

Since Windows 10 build 2104 it is possible to request disabling this border when capturing.

[Relevant Windows API documentation](https://learn.microsoft.com/en-us/uwp/api/windows.graphics.capture.graphicscapturesession.isborderrequired)

I'm not familiar with the code (_at all_), but relevant code already seems to be present [here](https://github.com/obsproject/obs-studio/blob/22ea8f4/libobs-winrt/winrt-capture.cpp#L301-L315).

Related to #7660.

**Comment by tytan652** [comment]
Duplicate of #7660 

Note that OBS Github issue are not for feature request.

**Comment by gxalpha** [comment]
As an additional note, the version of Windows referenced in the API docs is a server version. So far, it looks like on consumer versions of Windows this is only in Windows 11 (and may always stay that way).

As you pointed out, we check in code whether the function is available, and disable the border if it is.
Please update your Windows to a version where the function exists, probably only Windows 11.

**Comment by Alveel** [comment]
@tytan652 apologies, I updated the issue with more info. Can you look over it again?

**Comment by Alveel** [comment]
@gxalpha I didn't realise that was for Windows server documentation. It's a shame if this feature won't be in desktop Windows 10. But if that's the case, the issue can stay closed.

**Comment by Sotasho** [comment]
bruh W10 and W11 literally the same OS.

Anyway

**Comment by atesin** [comment]
> Duplicate of [#7660](https://github.com/obsproject/obs-studio/issues/7660)
> 
> Note that OBS Github issue are not for feature request.
> 
> > The yellow border is drawn by Windows, we cannot control where it is.
> > As a side note, it doesn’t exist at all on Windows 11.

i don't see the OP is requesting a new feature, but reporting a bug/misbehavior for an existent functionality, that is for issues are

i am the author of issue @baffler mentioned above, the problem is still present in current OBS version

**Comment by Fenrirthviti** [comment]
This cannot be fixed on Windows 10, please update to Windows 11. If the issue persists there, then it is not the same as this, and should be reported a new issue.

Microsoft does not allow hiding the border on Windows 10, so this is not something we can fix.

**Comment by atesin** [comment]
> This cannot be fixed on Windows 10, please update to Windows 11. If the issue persists there, then it is not the same as this, and should be reported a new issue.
> 
> Microsoft does not allow hiding the border on Windows 10, so this is not something we can fix.


i see you didn't even read the external link to issue so i will put a screenshot:

<img width="960" height="396" alt="Image" src="https://github.com/user-attachments/assets/28e87ba5-c97a-431e-9b92-0a567e63ca7d" />

and this is the tooltip when you hover the mouse in link mentioned above:

<img width="938" height="468" alt="Image" src="https://github.com/user-attachments/assets/13b4904f-bc01-4308-b378-0ca45c52c2c6" />

please anybody knows some fix/workaround that doesn't involve to spend the money i don't have?... thanks

**Comment by Fenrirthviti** [comment]
I'm not sure your point. Your rejection to the solution doesn't make the solution any more valid. This cannot be fixed on our end, because there is nothing to fix. This information is not only in this thread multiple times, but you've been informed on your linked issue (which I did not read before, because it's not relevant to the issue here).

You have been given multiple workarounds and options, and have rejected all of them. That's your choice, and there isn't anything we can do about it.

EDIT: Additionally, upgrading to Windows 11 does not cost money. You can just upgrade.

**Comment by atesin** [comment]
> EDIT: Additionally, upgrading to Windows 11 does not cost money. You can just upgrade.

yes it does because my pc doesn't meet the requirements and i don't have money to buy another pc just to supress a yellow border ... not everybody have a nasa developer/broadcaster pc

so, if there is nothing to fix, what a shame on me, and for many others that don't have win11 compatible pc either ... sorry for bothering for nothing
