### ISSUE TITLE
Chroma Key green line

### ISSUE THREAD

**Issue by nospam2k** [obsproject/obs-studio#8162]
### Operating System Info

Windows 11

### OBS Studio Version

29.0.0

### OBS Studio Log URL

n/a

### OBS Studio Crash Log URL

n/a

### Expected Behavior

No outline around image

### Current Behavior

outline around image

### Steps to Reproduce

1. add camera source to scene
2. add Chroma key filter to source
3. Tweak key color type, similarity, smoothness, key color spill reduction, etc.
![Screen Shot 2023-01-27 at 10 28 17 AM](https://user-images.githubusercontent.com/1284287/215165844-33500c8b-6804-414e-9ca8-74c7fd408e12.png)

### Anything else we should know?

I have tried all kinds of changes to lighting, distance from green screen, etc. Nothing I do allows me to remove the outline. It would be nice if there was an option in chroma key to remove a few pixels around the key color to reduce the outline.

**Comment by Fenrirthviti** [comment]
This is not a bug, but simply how chroma key works in an improper setup. Most commonly, this is caused by insufficient or uneven lighting. See here for more details: https://www.youtube.com/watch?v=OH8TWTt51W8

Also, in the future, please include a log file as issues are almost always inactionable without them.

**Comment by nospam2k** [comment]
I understand and have watched tons of videos on configuring for green screen. They all say "sort of" for keying, even with the right equipment. My suggestion was just to add a bit of cropping (as in a slider that "punches out" a few pixels of the remaining content where the green still exists) to the key color to allow a slight compensation to accommodate users that don't have a budget of $20k for the proper green screen room. Thanks for you fast response though! I really like OBS and appreciate it very much!

**Comment by Fenrirthviti** [comment]
You are describing the spill reduction feature that is already implemented.

**Comment by nospam2k** [comment]
That is along the lines of what I'm referring to but not quite. The spill reduction only removes the key color from the whole image. So the outline remains, it just becomes a less the key color. What I'm referring to is addressing the line itself. The control would detect the "edge" of the key color and continue to remove pixels surrounding the key color which would eat up the line. The smoothing control could follow after to clean up the edges. This is a technique used when trying to remove a subject from its background in an image. Get an outline based on color around the subject and then subtract a few pixels. Thanks for continuing to listen to my explanations, I appreciate it. I realize that this can be handled by the right (aka expensive) equipment, but part of the attraction of OBS is it caters to a lower budget audience. A feature as I'm desicribing I think would be very helpful. There are so many tutorials on YouTube that all end with a sort of "this is the best you can do with low end equipment" I'm not even sure this will help in a motion blur setting but it would be helpful. Thanks again ;)
