### ISSUE TITLE
Failed to set pix_fmt=rgb24

### ISSUE THREAD

**Issue by PotionClair** [obsproject/obs-studio#8163]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.0

### OBS Studio Log URL

https://obsproject.com/logs/GLLxnjDAZHtiCSdE

### Expected Behavior

The output video should have been RGB (8-bit).

### Current Behavior

The output video was YUV 4:2:0 instead.

### Steps to Reproduce

1. Set video capture device format to XRGB
2. In Settings - Advanced, set OBS 29.0.0 Video Color Format to BGRA (8-bit)
3. In Settings - Output, set Output Mode: Advanced, Recording, Type: Custom Output (FFmpeg)
4. In FFmpeg Settings, set Video Encoder: hevc_nvenc ; Video Encoder Settings: "preset=lossless pix_fmt=rgb24"
...

### Anything else we should know?

I used to record videos in RGB format with OBS without issues.

Since I updated to OBS 29.0.0, videos end up being in YUV 4:2:0 while I have not changed any setting.

The video capture card's format is still XRGB, and OBS video color format is still BGRA (8-bit).

I notice the name of the color format in Advanced settings has changed, I believe it was just "_RGB_" before and now appears as "_BGRA (8-bit)_". Maybe something related to the RGB output format has been modified in OBS 29? Or maybe it is just a clarification on which RGB format OBS uses exactly?

I went through the log and, in particular, upon starting the recording, it says "**Failed to set pix_fmt=rgb24**". Why is that so?

In the attached example I used Nvenc but the same issue appears when using libx264rgb as well. Thus I suspect it is either a problem with OBS 29.0.0 or the FFmpeg version it uses.

I also attached what MediaInfo says about a video recorded with OBS 29.0.0 (on the left: YUV 4:2:0) vs. a video recorded with OBS 28 (on the right: RGB 8 bits). The OBS 29 video is much smaller and I can see the reds bleeding so it's definitely not RGB.

![obs_29_rgb_settings_capture](https://user-images.githubusercontent.com/12266606/215182503-8695b30d-83d8-41ff-83ec-80cf33c8c3e4.png)
![obs_29_rgb_settings_output](https://user-images.githubusercontent.com/12266606/215182506-4733d940-96f8-4461-8906-0d3452d1ef10.png)
![obs_mediainfo_comparison](https://user-images.githubusercontent.com/12266606/215182507-76c3a344-4fbf-49c8-b961-f283ea754aae.PNG)

**Comment by derrod** [comment]
`rgb24` is not a valid pixel format for ffmpeg. Use `ffmpeg -h encoder=<encoder name>` to see a list of supported formats.

**Comment by PotionClair** [comment]
@derrod I tried rgb0 & bgr0, which are listed in FFmpeg's hevc_nvenc Supported pixel formats, and get the same error.


![hevc_nvenc_pixfmt](https://user-images.githubusercontent.com/12266606/215189864-e32cf7e1-7eeb-4063-b647-df79d5f45b11.png)


https://obsproject.com/logs/i8B69g91ZlOgA3vZ

**Comment by derrod** [comment]
`pix_fmt` might not actually work there since it's not actually an encoder option, but I'm not sure what the correct way to set that is. Either way, this is more of a support issue or perhaps feature request, not a bug. Try asking on our forums or Discord (although be aware that custom FFmpeg output is generally not well supported).
