### ISSUE TITLE
Browser source disappeared as an input source. Existing browser sources longer working.

### ISSUE THREAD

**Issue by ovidiu-ionescu** [obsproject/obs-studio#8176]
### Operating System Info

Other

### Other OS

Debian Bookworm

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.0.0.11.2

### OBS Studio Log URL

https://obsproject.com/logs/VD2DkRAN7ERfiBzI

### Expected Behavior

Video from my ip cam should be shown. This worked fine only days ago,

### Current Behavior

Browser source is no longer available as an option. Current browser sources are no longer working.

### Steps to Reproduce

Just by staring OBS

**Comment by WizardCM** [comment]
This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels below, and if it's determined that this is indeed a bug, then we will re-open this issue.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

I'm unsure where you installed OBS from, but the version you have doesn't seem to have obs-browser installed, therefore the browser components don't exist.

**Comment by derrod** [comment]
It looks like you're running a third-party build that does not include the browser source plugin.
