### ISSUE TITLE
OBS fails to hook to vulkan RetroArch

### ISSUE THREAD

**Issue by DfactorLongplays** [obsproject/obs-studio#8183]
### Operating System Info

Windows 11

### OBS Studio Version

29.0.0

### OBS Studio Log URL

https://obsproject.com/logs/2nLByokpHwNkqclB

### Expected Behavior

OBS "Capture any fullscreen application" or "Capture specific window" hook to retroarch.exe (vulkan renderer).

### Current Behavior

OBS fails to hook to retroarch.exe (vulkan renderer).

### Steps to Reproduce

1. Download RetroArch from Steam or latest stable standalone 64-bit Windows version (1.14.0).
2. Launch RetroArch, go to Settings > Drivers > Video and set to "vulkan".
3. Go back to Main Menu > Restart RetroArch.
4. Re-launch RetroArch.
5. Attempt hooking with OBS via "Capture any fullscreen application".

### Anything else we should know?

OBS hooks successfully if other APIs are selected, tested with DX12 and GL.

I've discovered this issue on Jan 15th, shortly after applying Cumulative Windows Update KB5022303. I have a suspicion that the update is a potential cause for this issue.

Display Capture is the only way it's possible to capture Vulkan RetroArch.

**Comment by DmitriyFrogo** [comment]
Seems like #7738 

Temporary fix is to install Vulkan Runtimes 1.3.236.0+ version, until Nvidia provide it in new drivers

You can find latest VulkanRT here
https://vulkan.lunarg.com/sdk/home

Or direct link to latest version: https://sdk.lunarg.com/sdk/download/latest/windows/vulkan-runtime.exe
