### ISSUE TITLE
[Flatpak] Tuna plugin doesn't work in Flatpak.

### ISSUE THREAD

**Issue by IgLocoXD** [obsproject/obs-studio#8186]
### Operating System Info

Other

### Other OS

ArcoLinux

### OBS Studio Version

29.0.0

### OBS Studio Log URL

https://obsproject.com/logs/xlsos94roYpxPOtV

### Expected Behavior

Be able to use Tuna Plugin in the Flatpak version of OBS.

### Current Behavior

OBS Simply doesn't want to load it because it needs "libtag.so.1" Even if it its installed in the System (as taglib)

### Steps to Reproduce

1. Extract/Install the Tuna Plugin in Flatpak trough folder method.
2. Open OBS
3. Tuna isn't in the Tools tab

### Anything else we should know?

I tested the plugin with OBS Arch/Native repositories and works well, also other plugins that i installed trough Folder method worked for me (DVD Screensaver plugin and Livesplit OBS)

**Comment by tytan652** [comment]
We only support plugins being installed through Flatpak extensions.

The Flatpak have it's own runtime separated from the actual system.
Installing a library in the system will not affect the runtime.
