### ISSUE TITLE
Floting windows in obs 

### ISSUE THREAD

**Issue by djtobbelito** [obsproject/obs-studio#8189]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.0

### OBS Studio Log URL

djtobbelito

### Expected Behavior

was going to apply floating window called "Twitch statistics" but after we updated obs to version 29 then we had the floating window in the control panel on obs so yes could see how many people were online and show followers the page about my sound mixer in obs.

### Current Behavior

my floating window in obs with my twitch stats has disappeared i tried to restore and recreate but it is not listed on obs anymore in the "floating window" menu how do i do this?  have tried reset docks 5 times now. but all other windows exist without twitch statistics. as mine is in Swedish.I absolutely can't get it to work I can't find my dashboard url to my obs on twitch may have to reinstall obs just because the floating window has run away for me.Could you please help me find the url to find the floating window on obs called twitch stats doesn't want to show up in my list even though I have restarted obs and reset all my floating windows in that menu on obs. I need a url to get back exactly the windows I'm looking for called (twitch statistics) in Swedish

### Steps to Reproduce

1.
2.
3.
...

### Anything else we should know?

Could you please help me find the url to find the floating window on obs called twitch stats doesn't want to show up in my list even though I have restarted obs and reset all my floating windows in that menu on obs. I need a url to get back exactly the windows I'm looking for called (twitch statistics) in Swedish

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by djtobbelito** [comment]
we solved it now. i had to delete my stremkey and recreate it and all the floating windows came up. now I was happy.
