### ISSUE TITLE
Incomplete/incorrect video capture during cutscenes in Hyperdimension Neptunia Re;Birth1

### ISSUE THREAD

**Issue by PaddyMac** [obsproject/obs-studio#8193]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.0

### OBS Studio Log URL

https://obsproject.com/logs/BT8gO4e272oKLIOR

### Expected Behavior

I expect the captured and streamed/recorded video to appear the same as it appears on my monitor.

### Current Behavior

I have not tested previous versions of OBS with this game, but OBS forum posts as early as 2015 reported completely black screens in video capture during the game's cutscenes. The error I am seeing is much less severe. The characters' faces have lines around their mouths and shadows around their eyes which make them look extremely odd in the recording/stream. Forum posts suggest this error occurs with Hyperdimension Neptunia Re;Birth1, Re;Birth2, and Re;Birth3. I have only tested Re;Birth1 so far.

### Steps to Reproduce

1. Start Hyperdimension Neptunia Re;Birth1
2. Start OBS and capture the game's screen
3. View the recorded video and see that it contains visual errors
...

### Anything else we should know?

If it is helpful, I am also attaching a screen shot which shows an example of the distorted image.

![Hyperdimension Nuptunia ReBirth1 OBS capture problem Screenshot 2023-01-22 205122](https://user-images.githubusercontent.com/1041361/216231931-e046f39f-4f83-4d01-9dad-f2d7fd33bf7e.png)

**Comment by Fenrirthviti** [comment]
This is a known issue on old AMD GPUs with games that run on OpenGL. Not much we can do, other than suggest checking to see if newer drivers are available for that GPU.
