### ISSUE TITLE
can't display any windows in Mac 12.6.3 with M1 pro

### ISSUE THREAD

**Issue by Aragamiz** [obsproject/obs-studio#8198]
### Operating System Info

macOS 12

### OBS Studio Version

29.0.0

### OBS Studio Log URL

https://1drv.ms/u/s!AjCv9QAqSyrvhYYYhrlYSuOazxj4hA?e=bNU89F

### Expected Behavior

I want to open obs , but can't display any windows
system mention me obs is working , and useing microphone
and i can't find obs in my desktop or dock.
In 2023 jan is working fine.

### Current Behavior

nothing happen , only mention me obs is working but no windows

### Steps to Reproduce

1.uninstall obs to install new
2.reboot system
but not working

**Comment by gxalpha** [comment]
This issue appears to be a support request, for which we don't use GitHub Issues.
Please make sure to visit the support sections on our [Discord server](https://discord.gg/obsproject) or [Forums](https://obsproject.com/forum).

Thank you!
