### ISSUE TITLE
Unable to update portable OBS, while other portable OBS open.

### ISSUE THREAD

**Issue by lindenkron** [obsproject/obs-studio#8200]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.0

### OBS Studio Version (Other)

29.0.1

### OBS Studio Log URL

https://obsproject.com/logs/PaorPO5TBCV317TG

### Expected Behavior

- Open 2nd OBS.
- Press Update.
- Update without issues.

### Current Behavior

- Open 2nd OBS
- Press Update.
- Update hangs on "Waiting to close OBS.."

### Steps to Reproduce

1. Download Portable OBS 29.0.0
2. Download Portable OBS 29.0.1
3. Open portable OBS 29.0.1
4. Open portable OBS 29.0.0
5. Press 'Update OBS' on 29.0.0.

**Comment by derrod** [comment]
This will be fixed by #8142
