### ISSUE TITLE
nvenc error when screen set 150% scale with  Fractional scaling with ubuntu 22.04 lts

### ISSUE THREAD

**Issue by hawk0w1** [obsproject/obs-studio#8207]
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

29.0.1

### OBS Studio Log URL

https://obsproject.com/logs/EhaDGHBHwNXoDf67

### Expected Behavior

can use nvenc recording video 

### Current Behavior

 eneric error in an external library

### Steps to Reproduce

1. ubuntu 22.04 with nvidia 3090 and driver installed 
2. 4k screen and set scale to 150%  with Fractional scaling
3. record video with nvenc 
...

### Anything else we should know?

when set to 200%  without Fractional scaling , it run well

**Comment by kkartaltepe** [comment]
You are using an invalid video size for your encoder. This is working as intended.
