### ISSUE TITLE
Output in RGB color format is broken

### ISSUE THREAD

**Issue by mia-is-baka** [obsproject/obs-studio#8209]
### Operating System Info

Windows 11

### OBS Studio Version

29.0.1

### OBS Studio Log URL

https://obsproject.com/logs/q4qSKazjOlC0zJjm

#### Case 1

Video should be encoded as RGB

#### Case2

Video should be properly encoded as RGB with encoder such as libx264rgb and have RGB color space in metadata without messed colors 

### Current Behavior

If you select BGRA (8-bit) color format in advanced settings and try to record video with standard output, it actually record video with NV12 or I420 color format

With custom FFmpeg output things are more interesting:
- With some encoders such as libx264rgb file is marked as YUV with chroma-subsampling 4:4:4 instead of RGB
- With some encoders such as utvideo output looks as it should

#### Case 1 (standard output)

1. Launch OBS
2. Select RGB color format in advanced settings
3. Setup standard output with libx264 as encoder
4. Record short video
5. Video should look normal at first sight, but if you look at file metadata or playback info in mpc-hc, it turns that video is YUV with chroma-subsampling 4:2:0 (NV12 or I420)

#### Case 2 (custom FFmpeg output)

1. Launch OBS
6. Select RGB color format in advanced settings
7. Setup custom FFmpeg output with libx264rgb as encoder
8. Record short video
9. Look at messed wrong colors and YUV with chroma-subsampling 4:4:4 in file metadata or playback info

### Anything else we should know?

It's not broken in versions before 28.x.x

**Comment by flaeri** [comment]
In custom ffmpeg output in RGB works fine for several different codecs, but libx264rgb has quirks. When you're titling and writing up issues, its best to be specific, so instead of writing "output in rgb broken" (insinuating that its a root problem with rgb, impacting all codecs), instead do rgb broken for libx264rgb. Or better, "Incorrect matrix/color space tagging for libx264rgb in custom ffmpeg output"

There was an issue open for this already, and you can fix the issue by specifying the colorspace via `colorspace=0`
https://github.com/obsproject/obs-studio/issues/7345

**Comment by mia-is-baka** [comment]
> In custom ffmpeg output in RGB works fine for several different codecs, but libx264rgb has quirks. When you're titling and writing up issues, its best to be specific, so instead of writing "output in rgb broken" (insinuating that its a root problem with rgb, impacting all codecs), instead do rgb broken for libx264rgb. Or better, "Incorrect matrix/color space tagging for libx264rgb in custom ffmpeg output"

But it also is not working with standard output

**Comment by flaeri** [comment]
You can't output RGB with x264. Thats why libx264rgb exists, which is a weird special thing. Personally, I feel like rgb in h264 is weird, and you might as well use a different codec where rgb makes more sense, like huffyuv, cineform or others.

If you really like it, then you can specify the correct matrix/color space, and it will work :)

**Comment by mia-is-baka** [comment]
> You can't output RGB with x264

Yeah, but in pre-28 OBS it actually worked. I think OBS by default could use libx264rgb if RGB is used, but this behavior has been removed or broken

> Personally, I feel like rgb in h264 is weird, and you might as well use a different codec where rgb makes more sense, like huffyuv, cineform, utVideo or others

Oh, yes there is :p

**Comment by mia-is-baka** [comment]
> > You can't output RGB with x264
> 
> Yeah, but in pre-28 OBS it actually worked. I think OBS by default could use libx264rgb if RGB is used, but this behavior has been removed or broken

Oh, my apologies, even older versions has behavior like 28+

I'm closing my issue as wrong and duplicate of #3745
