### ISSUE TITLE
LIBOBS - BROWSER PLUGIN DOES NOT LOAD IN A NON QT APPLICATION

### ISSUE THREAD

**Issue by PeterAkakpo** [obsproject/obs-studio#8211]
### Operating System Info

Windows 11

### OBS Studio Version

29.0.1

### OBS Studio Log URL

N/A

### Expected Behavior

browser plugin should load irrespective of the development environment

### Current Behavior

using libobs to develop application in environment other than QT does not load the browser plugin.  

### Steps to Reproduce

1.  create an application with the obs library without QT libraries.
2.
3.
...

**Comment by PeterAkakpo** [comment]
on further investigation i notice this behavoir is due to the fact that the plugin has not seperated the UI part of the plugin from the core.  taking the decklink plugin as an example , the ui is in a different DLL (decklink.ui.dll) and the core in  decklink.dll. so the decklink.dll is able to load, while the decklink.ui.dll does not. so i think the browser plugin should also foloow the same format (obs_browser.dll and obs_browser.ui.dll)  so that those interested only in the core functionality and not interested in the ui functionality can use the obs_browser.dll

**Comment by tytan652** [comment]
Some plugin are made in a way that they only works OBS Studio (libobs + Qt), this is the case for obs-browser and obs-websocket and other frontend plugins.

**Comment by PeterAkakpo** [comment]
will disabling ENABLE_BROWSER disable only the UI functionalities or the whole browser plugin. if it will disable building the who plugin,  then there is no point in doing that , because i want to use the plugin to load html contents

**Comment by gxalpha** [comment]
> will disabling ENABLE_BROWSER disable only the UI functionalities or the whole browser plugin

It will disable the entire plugin. obs-browser is not currently designed to be built without Qt.
You are of course always welcome to submit a Pull Request changing that.

**Comment by PeterAkakpo** [comment]
thanks for the feedback

**Comment by michael-dm** [comment]
@PeterAkakpo is it still the case today ? did you find a workaround ?
Thanks
