### ISSUE TITLE
problem with NVENC or AMD drivers

### ISSUE THREAD

**Issue by chocolhache** [obsproject/obs-studio#8219]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.1

### OBS Studio Log URL

https://obsproject.com/logs/hoZxxivaKGoGR9IL

### Expected Behavior

I was hoping the problem was that the drivers needed to be updated.

### Current Behavior

It's not a crash or bug, at least that's what I think. But recently when starting transmission obs throws the following message **"Could not start output. Please check logs for more details.
Note: If you are using NVENC or AMD encoders, make sure your video drivers are up to date."**

The problem is that it is not that the drivers are outdated, since I have verified this several times even reinstalling the latest drivers or changing the obs version to version 28.1.2

But the error message still appears.

### Steps to Reproduce

1.In the general settings, in the output section, have the option "Automatically record when streaming" checked
2.Press the "Start recording" button or in case of streaming "Start transmission"

**Comment by gxalpha** [comment]
This issue appears to be a support request, for which we don't use GitHub Issues.
Please make sure to visit the support sections on our [Discord server](https://discord.gg/obsproject) or [Forums](https://obsproject.com/forum).

Thank you!
