### ISSUE TITLE
Expander Presets can't display new values ​​in real time

### ISSUE THREAD

**Issue by Mishasama** [obsproject/obs-studio#8224]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.1

### OBS Studio Log URL

No log for this.

### Expected Behavior

When changing the presets, the values should change in real time. As the old versions did.

### Current Behavior

It must select another filter and then reselect it, or reopen the filter properties window to display the new values.

### Steps to Reproduce

1. Add an Expander filter for an audio source.
2. Change the presets from Expander to Gate.
3. See the bug.
...

**Comment by Fenrirthviti** [comment]
Please provide a log, as it can provide important environment and configuration clues.

**Comment by tuduweb** [comment]
can reproduce.
