### ISSUE TITLE
PTT not working properly on Wayland (KDE)

### ISSUE THREAD

**Issue by Tesla-Tank** [obsproject/obs-studio#8235]
### Operating System Info

Other

### Other OS

Nobara37

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/c9TBLOM5OfemD7T8

### Expected Behavior

Setting up PTT for the microphone would work (with or without focusing on OBS)

### Current Behavior

PTT works for one second and stops recording anything from the microphone, even when the PTT hotkey is active.

### Steps to Reproduce

1. Start PC with Wayland
2. Create a microphone source (Pipewire or Pulseaudio)
3. Setup PTT for the microphone
4. Test the PTT 

### Anything else we should know?

The OS (Nobara37) is a modified version of Fedora. I tried this on Fedora37 as well with the same issue (on Wayland and KDE).
I also updated to KDE 5.27 which has a legacy x11 global shortcuts and tried Discord PTT on Wayland, which worked. OBS PTT does not work even when it is focused.
I haven't tried this with any other distro or desktop environment at the moment.

**Comment by tytan652** [comment]
As it is OBS support hotkeys only when focused under Wayland.

There is plans to use the Global Shortcut Portal in the future.

**Comment by Tesla-Tank** [comment]
> As it is, OBS Studio support hotkeys only works when focused under Wayland.
It doesn't, that is the issue and why I am writing this. 

My temporary solution is to start obs as a xwayland client and configuring gamecapture to work with xwayland. Thanks for the comment though.
