### ISSUE TITLE
AMF QVBR configure error

### ISSUE THREAD

**Issue by miaowsyf** [obsproject/obs-studio#8237]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.0.2

### OBS Studio Log URL

(https://obsproject.com/logs/04q9bmxmJJio50Ac)

### Expected Behavior

When encoder=AMD HW H.264/H.265 and RateControl=QVBR
User should setting "QVBR_QUALITY_LEVEL=1-51" instead of "TargetBitrate"
according to AMF QVBR wiki “User does not need to provide any target bitrate information as no rate control is employed”

### Current Behavior

encoder=AMD HW H.264/H.265
bitrate conrol=QVBR
_Bitrate setting has no effect_

### Steps to Reproduce

1.
2.
3.
...

**Comment by Fenrirthviti** [comment]
Please provide a log file.

**Comment by miaowsyf** [comment]
> Please provide a log file.

uploaded

**Comment by flaeri** [comment]
I think this is what they mean:
![image](https://user-images.githubusercontent.com/50419942/217798879-c647f373-cfb7-43ff-a78a-a58a8821beaa.png)
There is no QP/Q/crf selector visible, its just bitrate, which does not make a lot of sense for a rate control that is akin to CQP/CRF.
