### ISSUE TITLE
TikTok Live Studio installation messed up OBS game capture, or is it a problem with the latest version?

### ISSUE THREAD

**Issue by tazttv** [obsproject/obs-studio#8240]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/uaxoVW5IjY39K7PU

### Expected Behavior

I was expecting as usual once I start OBS my game to appear in the preview window and start streaming as usual.

### Current Behavior

Yesterday I installed tiktok live studio as I don't have a server and key yet, to stream on tiktok (I use OBS to stream on twitch). Today and without changing anything in OBS the preview is black, although when I click on the game capture I can see the game (see screenshot). I think there is a conflict maybe between the two installations and OBS cannot preview anymore? 
![2023-02-09 12_27_05-Window](https://user-images.githubusercontent.com/124879697/217787581-bc28c5c4-9071-4fb4-8d41-bbe6ea33ecad.png)
![2023-02-09 12_27_24-Window](https://user-images.githubusercontent.com/124879697/217787590-cc656b3d-6fbd-48fc-b6cf-0b607c4207e1.png)

### Steps to Reproduce

1. Tried to create a new game capture either by capturing a specific window or any fullscreen application, it does not work.
2. Tried to do a display capture, this works. 

### Anything else we should know?

In tiktok live studio I am also using game capture. I should also point out that I am not running both OBS and tiktok live studio simultaneously.

**Comment by Penwy** [comment]
This sounds more like a support issue than a bug, do you mind swinging by the official support discord so we can try some troubleshooting?

**Comment by tazttv** [comment]
Resolved with help from Penwy.

**Comment by disquemarito** [comment]
> This sounds more like a support issue than a bug, do you mind swinging by the official support discord so we can try some troubleshooting?

Could I know how  you fixed this? I am having the same Issue.
