### ISSUE TITLE
29.0.2 Encoder SVT-AV1 is taking too long to encode (timeout: 5 seconds)

### ISSUE THREAD

**Issue by tormyvancool** [obsproject/obs-studio#8241]
### Operating System Info

Windows 11

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/SpQ2CZHHvXIfWtuY

### Expected Behavior

no warnings and no errors should appear.

### Current Behavior

When click on stop recording, this pops up

The same is for the AOM-AV1 encoder
![image](https://user-images.githubusercontent.com/32305535/217849565-e1927848-1e80-4904-a794-36fc31ef92b5.png)

### Steps to Reproduce

1. Start recording
2. Do what you want
3. Stop recording
4. the popup appears
...

### Anything else we should know?

Windows 11 Pro 64 bit
AMD Ryzen 7
48GB RAM

Output format MKV

**Comment by notr1ch** [comment]
This is not a bug, your CPU simply isn't fast enough to encode AV1 at 4k.

**Comment by mmehnert** [comment]
Actually, I had the same problem on a much faster system, but in a situation where the general load of the system was at about 70-80% CPU usage due to other processes (although at lower priority). I increased the timeout arbitrarily to 20s and recompiled. Did not have a problem after that and the created videos were fine. Perhaps it would be nice to have an option to adjust the ffmpeg timeout via the user interface. Or have a little bit higher value than just 5s.

**Comment by tormyvancool** [comment]
> This is not a bug, your CPU simply isn't fast enough to encode AV1 at 4k.

To export just a short screen recording, and having this issue on a Ryzen 7 3.2GHz 48GB RAM I think something is wrong in terms of embedded settings.
If you think a user should own a CRAY in order to use this feature: then this setting is pointless.

**Comment by Fenrirthviti** [comment]
OBS isn't "exporting" anything, it's encoding in real-time, which is very different than running an encode/export in something like a video editor, where it can take as much time as it wants per-frame.

AV1 software encoders are well known to require extremely high-end hardware to run in real-time, even at 1080p. Trying to push 4k through it is even more of a pipe dream right now, until such time as they are optimized further.

**Comment by MochyPei** [comment]
I have same issue on 29.1.3, when trying to record speedpaint in 1080p 1 frame per second, on NVENC HEVC/H264, with RTX 3060M, but when i record 3 frames per second, it's no problems, even when 120 frames, absolutely normal work.
