### ISSUE TITLE
failed to open nvenc codec

### ISSUE THREAD

**Issue by kimikazZZ** [obsproject/obs-studio#8249]
### Operating System Info

Other

### Other OS

debian 11

### OBS Studio Version

29.0.1

### OBS Studio Log URL

no crash

### Expected Behavior

I could use nvenc codec for record and my processor feels good while recording 120fps(epic)

### Current Behavior

At this point i can't use hardware codec to record. Already spent hours to fix this issue and tried this patch https://github.com/keylase/nvidia-patch , have FFmpeg installed.

obs installed from flatpack otherwise nvenc doesn't even showing in encoders(common) 

NVIDIA driver version : 470.161.03

![image](https://user-images.githubusercontent.com/107315478/218251948-36b08aa3-b59c-4450-a949-0f62e2a0c262.png)

### Steps to Reproduce

1. select ![image](https://user-images.githubusercontent.com/107315478/218252332-dd81cab6-75c1-47aa-a119-f415ebee7a0c.png)
2. obs record won't work and my brain gets damage bc i looked for this issue for the whole day

**Comment by tytan652** [comment]
Debian provide Data Center versions of NVIDIA driver, so the Flatpak can't support it because there is no NVIDIA runtime with those versions.

Debian's OBS package rely on a FFmpeg build that does not provide NVENC.
