### ISSUE TITLE
10-bit color spaces cause massive frame loss

### ISSUE THREAD

**Issue by BoxcartCoronet** [obsproject/obs-studio#8250]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/duMxok8xyEnuQet9

### Expected Behavior

Smooth recording

### Current Behavior

Massive frame loss in output recording file/encoder reaching capacity when color spaces are set to 10-bit (Rec. 2020 PQ or HLG)

I am recording a 4K HDR input  in OBS. With the output recording type set to standard in Output > Type, it works as expected. However I want to take advantage of advanced audio encoders which are only available with the "Custom Output (FFmpeg)" recording type. However when I do this, I get massive/unwatchable stuttering in the output recording when the "Color Space" in Advanced > Video is set to a 10-bit option (Rec. 2100 (PQ) or Rec. 2100 (HLG)). If I set it to Rec. 709 the output recording does not have frame loss, although HDR is not enabled.

### Steps to Reproduce

Described above. When Color Space is Rec. 2020 PQ or HLG I experience massive frame loss in the output file. When it is alternatively set to a non 10-bit option it works as expected.

Here is my configuration:

https://obsproject.com/forum/attachments/1-png.91562/

https://obsproject.com/forum/attachments/2-png.91563/

https://obsproject.com/forum/attachments/3-png.91564/

**Comment by Fenrirthviti** [comment]
Advanced ffmpeg output mode is provided "as-is" and it looks like you're simply overloading what the encoder is capable of. I'd recommend stopping by the encoding-talk channel in our Discord for more assistance.
