### ISSUE TITLE
Drag and Drop not working in remux window

### ISSUE THREAD

**Issue by Zaptyp** [obsproject/obs-studio#8252]
### Operating System Info

Windows 11

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/BPpyNFY3WGOISE3B

### Expected Behavior

The remux window should allow you to drop files via Drag and Drop

### Current Behavior

Remux window locks and does not allow to move files using drag and drop.

### Steps to Reproduce

1. Start OBS 
2. Go to File > remux
3. Try to do Drag and Drop to remux window.
...

**Comment by tuduweb** [comment]
cant reproduce.
could you please provide the screen recording?

**Comment by WizardCM** [comment]
Drag and Drop is not supported when OBS is running as Administrator. This is an operating system limitation.
