### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by LAISOVECHAT** [obsproject/obs-studio#8255]
### Operating System Info

Other

### Other OS

Windows7

### OBS Studio Version

Other

### OBS Studio Version (Other)

Windows

### OBS Studio Log URL

Windows

### OBS Studio Crash Log URL

Windows

### Expected Behavior

Windows

### Current Behavior

Windows

### Steps to Reproduce

1.
2.
3.
...
Windows

### Anything else we should know?

Windows

**Comment by tytan652** [comment]
Closing as the issue is empty.

**Comment by gxalpha** [comment]
Windows 10 or Windows 11

**Comment by derrod** [comment]
Windows

**Comment by Penwy** [comment]
Windows?
