### ISSUE TITLE
OBS Crashing at random

### ISSUE THREAD

**Issue by kc8iqw** [obsproject/obs-studio#8262]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.0.2

### OBS Studio Log URL

https://gist.github.com/kc8iqw/27826e7ac165a28def6858aeb18e7514

### OBS Studio Crash Log URL

https://gist.github.com/kc8iqw/69c380ac5be6112b357ecba0ec9510b8

### Expected Behavior

OBS Studio to remain open and continue streaming.

### Current Behavior

OBS Studio will randomly crash.  The majority there is no crashdump, logs look identical to this (abrupt stop), and will sometimes remain running in the background but not actually working (as evidenced by no stream data).

### Steps to Reproduce

I was streaming only to Facebook Live.  I was not interacting with the system at the times it crashed.

### Anything else we should know?

This is the first crash that generated a crashdump so I am not sure if this crash is related to the other crashes it had.  I recently upgraded to 29.0.2 due to an audio issue with NDI but 28.1.2 was otherwise working.  I have seen other forum posts mentioning 29.0.1 and 29.0.2 randomly crashing without dumps as well.

**Comment by Fenrirthviti** [comment]
This crash appears to be caused by the third party NDI plugin, so this should be reported to them.
