### ISSUE TITLE
SE Live/OBS crashing upon scene switch

### ISSUE THREAD

**Issue by b1gdogttv** [obsproject/obs-studio#8263]
### Operating System Info

Windows 11

### OBS Studio Version

29.0.1

### OBS Studio Log URL

https://obsproject.com/logs/ICImS95k6OZSkyhf

### OBS Studio Crash Log URL

https://obsproject.com/logs/U12KcBEzDVRBnW0O

### Expected Behavior

Expected to switch scenes within obs, then edit a source within the scene.

### Current Behavior

After switching scenes, obs froze and crashed. 

### Steps to Reproduce

1.Open obs
2. click whatever scene is available
3. attempt to click a source within a scene if not frozen at this point, 
4. by this time obs will not allow you to click anything further and should force quit/crash. 
...

**Comment by Fenrirthviti** [comment]
If you need help with StreamElements products or services, please join their [Discord server](https://discordapp.com/invite/se) or [submit a support ticket](https://streamelements.com/contact).

They are tracking this crash from their plugin and have a proposed fix for it, pending final review.
