### ISSUE TITLE
Full screen projector crashes when display is disconnected

### ISSUE THREAD

**Issue by jrk** [obsproject/obs-studio#8264]
### Operating System Info

macOS 13

### OBS Studio Version

29.0.1

### OBS Studio Log URL

https://obsproject.com/logs/f8szQmCEd4yzEkpH

### Expected Behavior

The projection would stop when a fullscreen projector display was disconnected.

### Current Behavior

OBS Studio crashes.

### Steps to Reproduce

1. Plug in external display
2. Right click on main preview > Fullscreen Projector > [external display]
3. Un-plug external display

**Comment by gxalpha** [comment]
Fixed by #8271. Thanks for the report.
