### ISSUE TITLE
Changing bitrate mid-stream doesn't actually change the bitrate

### ISSUE THREAD

**Issue by instazedd** [obsproject/obs-studio#8268]
### Operating System Info

Windows 11

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/L7iT9xqfrWf3L5II

### Expected Behavior

Ideally, when I"m in the middle of a stream, and I change the bitrate in the output tab, it should change as soon as I hit apply.

### Current Behavior

The actual streaming bitrate (Lower right corner) stays the same, until I actually stop the stream, and start it back again.

### Steps to Reproduce

1.Start streaming
2.Change the bitrate in the output settings, hit apply
3.Nothing changes (The actual streaming bitrate stays the same)
4.Stop Streaming
5.Strat streaming again
6.The bitrate (Lower right corner) is now matching the actual value applied in settings.
...

### Anything else we should know?

It worked for me once before, couple of weeks ago (Can't remember if it was v28 or v29).

On discord, they asked me to try with v27.2.4 , I did, and it worked.

**Comment by pkviet** [comment]
I can't confirm your report.
I tried with nvenc and the bitrate was changed.
I also stepped into the code and the nvenc_update function was called and the encoder was reconfigured.
I'm not sure what causes the issue on your side.
Could you try to disable dynamic bitrate and test on a vanilla install without any third party plugin.

**Comment by pkviet** [comment]
Tested with and without dynamic bitrate, but in both cases, the bitrate is updated manually.

**Comment by Fenrirthviti** [comment]
Please test again without any third party plugins installed. I have tested on my end as well and cannot replicate. Everything updates as it should within a few seconds to the new bitrate.

**Comment by MattyFresh68** [comment]
I've tested with both amf and x264 on 29.0.2 and with DBR enabled/disabled. Adjusting bitrate during active output works just fine here.

**Comment by instazedd** [comment]
First of all, thank you for your replies.
So I actually installed a fresh portable version of OBS 29.0.2 (StreamFX was detected for some reason), and did some further testing, and I found a very interesting bahaviour !!! And it was the same behaviour on my main version.

When using the NVIDIA NVENC H.264 Ecnoder, I have to start the stream uning the preset from P1 to P5, then, I can change the bitrate mid-stream. But if I start the stream using the P6 or P7 preset, changing the bitrate doesn't change anything untill I stop the stream and start it back again.

And BTW, changing the present during the stream doesn't change this behaviour, it only matters which preset I use when starting the stream.

Is this actually the expected behaviour? OR is this a bug?


I should also mention that I tried with multiple combinations of turning on/off IP Binding, network optimization, dynamic bitrate... and it change a thing. It's all about the preset when starting the stream.

I made a screen recording that shows this issue:
https://youtu.be/SpzkFJ9JD7c

**Comment by Fenrirthviti** [comment]
Please provide a log file from that session as well.

**Comment by instazedd** [comment]
Didn't save the log file of that particular session, but here's a new one with the exact same steps shown in the video : 
https://obsproject.com/logs/Zt6Dm6LhROOASIBk

**Comment by pkviet** [comment]
NVIDIA enables lookahead for P6 & P7, which disables the capability to change bitrate on the fly. We've had issues in the past with lookahead and dynamic change of bitrate.
So this can't be fixed on our side; if you want to change bitrate on the fly, only use P1 to P5.

**Comment by pkviet** [comment]
correction: after checking more thoroughly the code, lookahead is not auto enabled by nvenc, but P6 & P7 request it so we comply. NVIDI told us that lookahead was at the core of the improvements brought by P6 & P7 so it wouldn't make sense to override and disable it for P6 & P7.

**Comment by pkviet** [comment]
after extensive testing, it seems that the 'lookahead' option is not interfering any more with bitrate live update. So we'll enable it, see the PR referenced above. You'll be able to test it when CI completes.

**Comment by pkviet** [comment]
test builds available here: https://github.com/obsproject/obs-studio/actions/runs/4186857952

**Comment by sandr1x** [comment]
> исправление: после более проверки проверки кода nvenc не активирует функцию просмотра вперед автоматически, но P6 и P7 запрашивают ее, поэтому мы ее выполняем. NVIDIA сообщила нам, что просмотр вперед лежит в основе улучшений, внесенных в P6 и P7, поэтому не имеет смысла переопределять и отключать его для P6 и P7.



> correction: after checking more thoroughly the code, lookahead is not auto enabled by nvenc, but P6 & P7 request it so we comply. NVIDIA told us that lookahead was at the core of the improvements brought by P6 & P7 so it wouldn't make sense to override and disable it for P6 & P7.


A month ago, I devoted a whole topic to this. Can you quote or send a response from NVIDIA? I understand that this will not be fixed and the topic can be closed.
https://obsproject.com/forum/threads/disabling-look-ahead-does-not-disable-adaptive-b-frames-on-presets-p6-p7-tune-hq-nvenc-h-264.163506/

**Comment by sandr1x** [comment]
> correction: after checking more thoroughly the code, lookahead is not auto enabled by nvenc, but P6 & P7 request it so we comply. NVIDIA told us that lookahead was at the core of the improvements brought by P6 & P7 so it wouldn't make sense to override and disable it for P6 & P7.

A month ago, I devoted a whole topic to this. Can you quote or send a response from NVIDIA? I understand that this will not be fixed and the topic can be closed.
https://obsproject.com/forum/threads/disabling-look-ahead-does-not-disable-adaptive-b-frames-on-presets-p6-p7-tune-hq-nvenc-h-264.163506/

**Comment by pkviet** [comment]
@sandr1x there's a fix. Try the test builds linked above.

**Comment by sandr1x** [comment]
> @sandr1x there's a fix. Try the test builds linked above.

I tested your test assembly and reported in your topic. Thanks, the fix is ​​working. Disabling look-ahead on the P6-P7 Tune HQ presets will still enable adaptive b-frames. This is exactly what interests me. For now, I'm using streamFX to manage this.
![image](https://user-images.githubusercontent.com/113405680/219668262-35be6926-c4d5-4eb5-901c-861e5551a878.png)

**Comment by RytoEX** [comment]
Let us please not pollute the core issue described here with other concerns.
