### ISSUE TITLE
Picture and sound has offset after 1 hour used

### ISSUE THREAD

**Issue by JKYLien** [obsproject/obs-studio#8282]
### Operating System Info

Windows 11

### OBS Studio Version

29.0.1

### OBS Studio Version (Other)

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/94zbCcCb4R8k9lVv

### Expected Behavior

I would like to ask is there any setting that is not done well or is this a problem?

### Current Behavior

I connected the GC553 to the computer and captured the screen
no problem at first
But after about an hour of use, the sound will be cut off for a short time
From then on the video and sound will have a fixed offset
I need to restart OBS to get back to normal

But look at the sound effects section
GC553 output sound effect is normal without fixed deviation
is a fixed offset of the video from the streaming and monitor output

### Steps to Reproduce

1. Use GC553
2. After streaming or recording for 1~2 hours
3. there is a short sound disappearing
4. If it is not reopened, it will be held continuously, even if the recording is stopped.

### Anything else we should know?

CPU : i7 - 13700
GPU : RTX3060
RAM: DDR5 32G
Board : ROG STRIX B660-I GAMING WIFI

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
