### ISSUE TITLE
huge fonts

### ISSUE THREAD

**Issue by f1-outsourcing** [obsproject/obs-studio#8284]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Log URL

https://obsproject.com

### Expected Behavior

normal

### Current Behavior

I am not really using obs that often so I hardly update it. But I am wondering if it is even useful to update for the current issue I have. This is probably related to the morons at microsoft not doing their job correctly? Although things like libre office seem to be fine. However when I drag a file on the desktop, I also have huge fonts.

![huge-fonts](https://user-images.githubusercontent.com/13450219/219609084-387450b1-d6c3-4515-aa0c-309d5aa115b7.png)

![text-to-big](https://user-images.githubusercontent.com/13450219/219609426-98d3d77c-72e3-4f1f-81e2-a261d0f489d9.jpg)

### Steps to Reproduce

?

**Comment by WizardCM** [comment]
This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels below, and if it's determined that this is indeed a bug, then we will re-open this issue.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

**Comment by f1-outsourcing** [comment]
So move it then ... Do you think I am going to type everything again?
