### ISSUE TITLE
Audio Output Capture: Device not connected or not available 

### ISSUE THREAD

**Issue by jasonm** [obsproject/obs-studio#8288]
### Operating System Info

macOS 13

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/nqjwBjV7d574057D

### Expected Behavior

I expected an "Audio Output Capture" source to enumerate audio output devices.

### Current Behavior

The "Audio Output Capture" source only shows the following in the device picker: "[Device not connected or not available]"

### Steps to Reproduce

1. Start OBS on macOS 13.2.1
2. Add a source "Audio Output Capture"
3. See that the device picker only says "[Device not connected or not available]"

### Anything else we should know?

The "macOS Screen Capture" source correctly captures audio, so this "Audio Output Capture" source issue isn't too big of a problem. It was kinda confusing at first, though.

I previously had some audio routing software (Soundflower) installed prior to macOS 13, but do not have it installed now.

I also tried this on OBS 28.1.2 (clearing `~/Library/Application Support/obs-studio` before changing versions) and saw the same behavior. The report in this issue is from OBS 29.0.2.

Here's a screenshot of my Audio MIDI Setup in case that's helpful:

![image](https://user-images.githubusercontent.com/1031/219826371-4813b0d8-c8a8-4fd0-bb24-e769f525de1f.png)

**Comment by derrod** [comment]
Audio output capture on Mac onky works with a loopback driver (soundflower, blackhole, etc.) installed.

**Comment by Fenrirthviti** [comment]
As an additional note, using either screen or window capture should capture the system or application audio, respectively.

**Comment by jasonm** [comment]
Thanks for the speedy clarifications!

I see this is correctly documented in https://obsproject.com/kb/macos-desktop-audio-capture-guide

I somehow came across https://cdm.link/2023/01/obs-studio-captures-audio-directly-more/ instead and read that, which incorrectly states:

> You just Add Source and choose Audio Output Capture. That’s it. “All audio from all applications will be captured regardless of which display you select.

I commented on that article accordingly.
