### ISSUE TITLE
Ubuntu Arm64 Browser Building error

### ISSUE THREAD

**Issue by Antoni950425** [obsproject/obs-studio#8292]
### Operating System Info

Ubuntu 22.04

### Other OS

Ubuntu

### OBS Studio Version

29.0.1

### OBS Studio Log URL

NA

### Expected Behavior

Trying to follow the automatic build process by simply running CI/build-linux.sh. Should be easily finish building process.

### Current Behavior

Currently the building process always failed. Stuck in Obs-browser part. 
After checking the log seems cef_binary_5060_linux64 only have x86 version.
`/usr/bin/ld: /home/ubuntu/develop/obs-build-dependencies/cef_binary_5060_linux64/Release/libcef.so: error adding symbols: file in wrong format`

### Steps to Reproduce

Simply running `CI/build-linux.sh` in ubuntu or debian arm version.

### Anything else we should know?

To successful build in arm ubuntu.
- I manually download cef from https://cef-builds.spotifycdn.com/index.html#linuxarm64 (the 103.0.5060.134 version)
- Unpack and cd to folder 'cef_binary_5060_arm64' and run `cmake ./ && make libcef_dll_wrapper` 
- Noticed the building will also failed because of architecture.
- Then I manually edit `cmake/cef_variables.cmake` changed x86 to arm64, the build again succeed.
- Remove everything inside folder `cef_binary_5060_linux64`
- copy everything inside `cef_binary_5060_arm64` to cef_binary_5060_linux64
- The back to obs-studio building folder and run `CI/build-linux.sh --skip-dependency-checks`
- The build should be successful

It seems like a problem from cef side, but hope OBS-Studio can help provide linux arm version cef pack when running automatic build.

**Comment by tytan652** [comment]
cef_binary_5060_linux64 is a x86_64 build of CEF.
