### ISSUE TITLE
Editable list property type has incorrect background color when placed inside property group

### ISSUE THREAD

**Issue by tt2468** [obsproject/obs-studio#8302]
### Operating System Info

Ubuntu 20.04

### OBS Studio Version

29.0.1

### OBS Studio Log URL

n/a

### Expected Behavior

I would expect that the value container has a background color matching that of the other value containers (see screenshot)

### Current Behavior

The value container inherits the background color of the group it's in:

![image](https://user-images.githubusercontent.com/28720189/219980159-67a62662-ced8-4bf5-8bba-e8240610aaf5.png)

### Steps to Reproduce

1. Create a source that displays an editable text property inside of a property group
2. Open the properties dialog for that source

**Comment by tytan652** [comment]
Does it affect also Yami variants (Light, Acri, Rachni…) ?

**Comment by tuduweb** [comment]
> Does it affect also Yami variants (Light, Acri, Rachni…) ?

Light, yes.
Rachni, no.
Acri, yes.
Dark, no.
Grey, yes.
System, no.

**Comment by tuduweb** [comment]
I found the key to the issue.
the background-color of `QListWidget`(`QAbstractItemView`) same to `QGroupBox` and `PropertiesContainer`
