### ISSUE TITLE
obs not recording window of same name in browsers

### ISSUE THREAD

**Issue by solomoncyj** [obsproject/obs-studio#8307]
### Operating System Info

Windows 11

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.0.0

### OBS Studio Log URL

https://obsproject.com/logs/98yIpbavVoQR8P96

### Expected Behavior

the window capture goes blank (re-scanning the open windows) before capturing back the detached tab of the same name

### Current Behavior

window capture the tab moved even though it has a different name and "window title must match" is enabled

### Steps to Reproduce

1. open chrome with multiple tabs
2. set obs to current video tab with "window title must match" enabled
3. drag the current tab away from the other tab to detach the recorded tab and reveal a tab with a different name, thus changing the window title of the original window
4. obs will record the original window instead that has a different name of the detected window of the same name until reset
...
reveal

**Comment by WizardCM** [comment]
Once OBS has found a match, it will "stick" to the window that matched the original rules. It will only try to find a new matching window if it loses the previously matched window (such as if it's closed).

**Comment by gxalpha** [comment]
Closing per the above comment. This is working as implemented, OBS "automagically" switching windows would pose several risks which is why it sticks to the window it's currently capturing.
