### ISSUE TITLE
using jetson nano NVENC natively

### ISSUE THREAD

**Issue by lblabr** [obsproject/obs-studio#8313]
### Operating System Info

Ubuntu 20.04

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/dbDjc9AClKYUxoTc

### Expected Behavior

would be great if you could support jetson nano and the nvenc by default with the great software! 
unfortunaly with cpu encoding the cpu load is to high to use ....

### Current Behavior

i would like to use the nvida tegra nvenc in OBS. at the moment i use the hardware encoding with a self compiled ffmpeg.
when is use custom ffmpeg the replay buffer is not vailable.

is there a way to use the nvidia tegra nvenc directly in obs? i do not no something about obs internals...

### Steps to Reproduce

1) Settings
2) set custom ffmpeg
3) as known replay buffer is not available

**Comment by derrod** [comment]
Jetson Nano does not have NVENC.

**Comment by Fenrirthviti** [comment]
Additionally, feature requests should be posted to our [Ideas page](https://ideas.obsproject.com/), not to GitHub Issues.
