### ISSUE TITLE
Video recording does not stop and the recorded file is cut

### ISSUE THREAD

**Issue by wirowka** [obsproject/obs-studio#8315]
### Operating System Info

Windows 11

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/SKEHzrBRmShvdW8d and https://obsproject.com/logs/g8tBBDudDD7Ce12L

### Expected Behavior

The recording starts and stops, a video/recording file is complete.

### Current Behavior

When recording a video (I am just using OBS to record my pulpit) everything is fine, but when I click a button to stop recording, the button turns into "stopping recording" and hungs forever. When I click it again after some time, the button changes into "start recording" but the recorded video file is cut - no idea why.
I does not happen every time, but quite often.
I did not do any deep dive tests, but seems that the longer the video, the bigger chance that the issue pops up. My recordings are usually shorter than 10mins.

### Steps to Reproduce

1. Configure display capture (Capthure Method: Automatic), Display: Dell U2722D: 2560x1440@-298,-1440 and Capture Cursor selected
2. Settings Output: Recording: Quality: High Quality, format: mkv, Encoder: Hardware (QSV)
3. Settings: Video: Base (2560x1440, ration 16:9), Output: 1920:1080 (16:9), Downscale Filter (Bicubic), Common FPS:60
4. Start recording
5. Stop recording

**Comment by tuduweb** [comment]
Sometimes I can reproduce this in early version. (win10)

**Comment by Mister36MN** [comment]
Please use the discord or forums for support - this is a standard case of encoder overload/failure that can be assisted there.

**Comment by RytoEX** [comment]
This sounds more likely to be a support request, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for further assistance.

Thank you for your understanding.
