### ISSUE TITLE
Immediate Crash with Pipewire

### ISSUE THREAD

**Issue by Seneral** [obsproject/obs-studio#8328]
### Operating System Info

Ubuntu 22.04

### Other OS

more precisely, KDE neon 5.27

### OBS Studio Version

29.0.2

### OBS Studio Version (Other)

more precisely, the Flatpak version 29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/VkQI3kpd3nwymrnx

### OBS Studio Crash Log URL

https://obsproject.com/logs/OPBhzoXldUBZX4kb

### Expected Behavior

Setting up a PipeWire screenshare works.

### Current Behavior

Setting up a PipeWire screenshare in the flatpak version under wayland crashes the program after selecting a screen to share with the system interface (Pipewire).

### Steps to Reproduce

1. Install flatpak obs studio and debug utilities (kde SDK 6.4 was necessary for me to debug)
```
flatpak install com.obsproject.Studio
flatpak install com.obsproject.Studio.Debug
flatpak install org.kde.Sdk
```
2. Debug obs in flatpak (behaves the same as running normally)
```
flatpak run --command=sh --devel com.obsproject.Studio
  gdb obs
    run
```
3. Go through setup wizard
4. Add a PipeWire Screen Capture
5. Select a screen to share in the popup
6. Crash after the GUI (still the screen capture wizard) attempts to display the stream.
Bonus:
8. Restart, observe that screen capture doesn't work, but it also doesn't crash
9. Edit the screen capture. It detects screen isn't shared properly, it will ask for another share, resulting in a crash in the same circumstances.
10. From then on, any restart will immediately ask for a new screen to share. Cancelling does work however.

### Anything else we should know?

Continuation of normal logs (which show no abnormality) with gdb backtrace - I hope this can be reproduced, but just in case:
```
info: [pipewire] Screencast session created
info: [pipewire] Screencast session created
info: [pipewire] Asking for window
info: [pipewire] Asking for desktop
[Thread 0x7fff951ad640 (LWP 75) exited]
info: [pipewire] desktop selected, setting up screencast
[New Thread 0x7fff60ce6640 (LWP 90)]
[New Thread 0x7fff3bfff640 (LWP 91)]
info: [pipewire] Server version: 0.3.48
info: [pipewire] Library version: 0.3.59
info: [pipewire] Header version: 0.3.59
info: [pipewire] Created stream 0x5555573a2440
info: [pipewire] Stream 0x5555573a2440 state: "connecting" (error: none)
info: [pipewire] Playing stream 0x5555573a2440
info: [pipewire] Stream 0x5555573a2440 state: "paused" (error: none)

Thread 36 "PipeWire thread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff3bfff640 (LWP 91)]
0x00007fff95bae21e in impl_send_command () from /usr/lib/x86_64-linux-gnu/libpipewire-0.3.so.0
(gdb) backtrace
#0  0x00007fff95bae21e in impl_send_command () at /usr/lib/x86_64-linux-gnu/libpipewire-0.3.so.0
#1  0x00007fff95b929bb in pw_impl_node_set_state () at /usr/lib/x86_64-linux-gnu/libpipewire-0.3.so.0
#2  0x00007fff94014a3d in client_node_command () at /usr/lib/x86_64-linux-gnu/pipewire-0.3/libpipewire-module-client-node.so
#3  0x00007fff94023474 in client_node_demarshal_command.lto_priv () at /usr/lib/x86_64-linux-gnu/pipewire-0.3/libpipewire-module-client-node.so
#4  0x00007fff9405c738 in process_remote () at /usr/lib/x86_64-linux-gnu/pipewire-0.3/libpipewire-module-protocol-native.so
#5  0x00007fff9405cdc0 in on_remote_data () at /usr/lib/x86_64-linux-gnu/pipewire-0.3/libpipewire-module-protocol-native.so
#6  0x00007fff9622c3c0 in loop_iterate () at /usr/lib/x86_64-linux-gnu/spa-0.2/support/libspa-support.so
#7  0x00007fff95bb52bc in do_loop () at /usr/lib/x86_64-linux-gnu/libpipewire-0.3.so.0
#8  0x00007ffff3c8f1da in start_thread () at /usr/lib/x86_64-linux-gnu/libc.so.6
#9  0x00007ffff3d17d84 in clone () at /usr/lib/x86_64-linux-gnu/libc.so.6
```

I have used OBS with both X11 and Wayland before on this same system interchangeably without problems.
After switching to wayland again it crashed upon startup (my Scene had Screen Shares, but afaik the only active ones were X11 streams). I cleared my config and encountered the same error as described above after the auto configuration wizard.

The two logs I attached are both equal crashes, the "crash"-labeled one is initial setup after clearing config with multiple auto configuration wizards, the other one is a much cleaner one of the restart right after, crashing while editing the screen share.

**Comment by kkartaltepe** [comment]
You must update your flatpak, you are on a bugged version of pipewire we have released a new version with pipewire 0.65 that resolves the bug.

**Comment by kkartaltepe** [comment]
Sorry i was mistaken, we didn't yet push a release with this fix.

**Comment by Seneral** [comment]
Yep can't find an update yet, but thanks to the version number I found the main issue #7849 so you may close this. Sorry for not seeing that before. Thanks!
