### ISSUE TITLE
OBS SRT Stream Outputs Bad Quality Stream – Lots of lost frames and packets 

### ISSUE THREAD

**Issue by saltarob** [obsproject/obs-studio#8329]
### Operating System Info

macOS 13

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/FZYTptlzoncZmItR

### Expected Behavior

I expect that the SRT Stream from OBS is published in a decent quality. Without dropped frames and distorted pixel artefacts which is indicating the packet loss. 

### Current Behavior

Dropped frames and distorted pixel artefacts, which indicates the packet loss, in the SRT Stream. 

### Steps to Reproduce

1. Send an SRT stream to Wowza with the from OBS recommend output settings: srt://YouWowzaServer:10000
2. Watch the dropped frames and pixel artefacts on the SRT receiving server.
3. Try the same with an RTMP stream.
4. Setup a local NGINX server to where you send your OBS RMTP Stream. 
5. Push the received OBS RMTP stream in NGINX to FFMPEG and Wowza: exec_push ffmpeg -i rtmp://localhost/live/$name -c copy -f mpegts srt://YourWowzaServer:10000?
6. So as far as I understand ffmpeg does then the same job with NGINX as it does with OBS. 
7. But if I send it via NGINX and FFMPEG I receive a proper stream on my Wowza server. Without dropped frames and ugly pixel artefacts every few frames. 
8. Therefore I believe there is a bug in your OBS - FFMPEG configuration. 

...

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by saltarob** [comment]
Support Request? I think you need support to fix your SRT setup. But if you don’t want...

**Comment by tt2468** [comment]
Our SRT implementation works just fine, but it's easily misconfigured. Try adding `?latency=1000000` to set the connection retransmit latency to 1000ms. In your current configuration, if Wowza doesn't have a latency applied on its side, you may be in a situation where the final negotiated SRT latency is too low for the protocol to transmit reliably over your network path.

**Comment by saltarob** [comment]
Thank you. Wowza has latency applied and SRT does choose the bigger value, so no need to apply it on both sides. And as you can see on the ffmpeg setup with Nginx, I am using the same setup there as in OBS. No further settings applied to the ffmpeg output. 
So can you explain why it is working fine with ffmpeg through Nginx and not working with ffmpeg through OBS?

**Comment by saltarob** [comment]
And your OSB SRT streaming output doesn’t allow any configuration. Only the server address and the port number. I don’t want to sacrifice the recording output. By the way my Wowza SRT configuration works fine since years with several different SRT devices (Kiloview, Wirecast, vMix, ffmpeg) and in all circumstances. Only OBS SRT delivers bad quality.

**Comment by pkviet** [comment]
Hi @saltarob you don't seem to have read the wiki for setting up srt.
Right now the latency must be set through the url. There's no ui, though i plan to add one. I'm waiting for a rework of outputs which is being done before adding changes to srt to make i easier to use. I use wowza all the time with obs, without issues. It's actually the first server i test against when coding srt stuff. Obviously I have a very low latency to my wowza server, which you don't seem to have. So just tune latency per the guidance provided in the wiki and ot should work.

**Comment by saltarob** [comment]
Hi thank you. Yes I know, sorry. I think it was maybe in a previous version of OBS where the url setup was not supported that way in the streaming output.
But that’s not the problem. As I mentioned before if the latency is defined on the wowza server there is no need to set it up on the encoder side. Or am I wrong? It is handled like this with all the other SRT encoders I am using. An I made thousands of SRT live streams in the same network, same encoding settings etc. So the settings are approved as working. Only with OBS they are not working?

**Comment by pkviet** [comment]
Hi @saltarob 
The way latency is dealt with in obs is done by libsrt itself. We don't do anything.
So if latency is set on server and not on obs, libsrt will handle the negociations between the server latency and the 120 ms used by obs since it's the default set by libsrt.
Anyway rather than us discussing in theory, just set the latency as 2 to 4 times the rtt which you get from the ping to your server and report if it works.

**Comment by saltarob** [comment]
Hi,

thank you.  
> The way latency is dealt with in obs is done by libsrt itself. We don't do anything.
> 
I think that’s exactly the same way as in my Nginx + ffmpeg setup. That’s why I used it as a reference and for comparison.

exec_push ffmpeg -i rtmp://localhost/live/$name -c copy -f mpegts srt://WowzaIP:10000?passphrase=XXXXXXX 

> Anyway rather than us discussing in theory, just set the latency as 2 to 4 times the rtt which you get from the ping to your server and report if it works.

My RTT is up to 100 ms. The latency set in Wowza is 400 ms, the default value. So 4 times the RTT. Recommend is 2.5 times RTT as you surely know.

That would mean the libsrt in OBS is for some reason not negotiating the latency with the Wowza Server and taking instead the 120 ms default latency.

Is it somewhere logged which latency is used or was negotiated?

Thank you so much.
