### ISSUE TITLE
OBS reconnect ignores availability of internet

### ISSUE THREAD

**Issue by Devocub** [obsproject/obs-studio#8335]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.2.3

### OBS Studio Log URL

-

### OBS Studio Crash Log URL

-

### Expected Behavior

Add ability to click on "Attemting to reconnect" or "Waiting 40 sec..." to force reconnect right now!

### Current Behavior

I have internet connection lost for 10-30 sec and I have retry delay 5s but OBS waits for 5, then on second reconnect 10, third 20 (i don't remember exact number but they grow), 40 etc. Even if i set it to 1 sec it still does it. 

### Steps to Reproduce

1. Stream with obs
2. Get internet connection lost for a minute (for example)
3. See reconnect delay grows

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
