### ISSUE TITLE
OBS quit when disconnect external fullscreen monitor

### ISSUE THREAD

**Issue by Darkwood3r** [obsproject/obs-studio#8336]
### Operating System Info

macOS 13

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/WNBfcCK7P0euENOs

### Expected Behavior

I expected to work normally without the external projector. 

### Current Behavior

OBS crashed.

### Steps to Reproduce

1.
2.
3.
...

### Anything else we should know?

I am using Macbook M1 Pro 16". And I am using fullscreen projector (program).

**Comment by tytan652** [comment]
Duplicate of #8264
