### ISSUE TITLE
Virtual camera vertical/portrait layout

### ISSUE THREAD

**Issue by DaveScream** [obsproject/obs-studio#8342]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/Hc1soxSOa32bZnFV

### Expected Behavior

I expect portrait layout in Skype, Telegram, Discord and other apps.

### Current Behavior

Only horizontal layout, cant rotate

### Steps to Reproduce

1. In settings set resolution to 1080x1920 - portrait aspect ratio 9:16
![изображение](https://user-images.githubusercontent.com/3002276/221275475-91130dbf-efd3-4b26-81fa-9e97be1f1159.png)
![изображение](https://user-images.githubusercontent.com/3002276/221276737-51e0e85d-ec80-4407-b0f4-75f3adc11167.png)
2. Start virtual camera
3. Run telegram, skype, discord
4. Its stretched
![изображение](https://user-images.githubusercontent.com/3002276/221277088-cdd3e285-95e4-4416-ae73-e611bdc8b905.png)

...

### Anything else we should know?

Release Windows 10 Pro
Version 22H2
installed 20.‎10.‎2022
build 19045.2486
Windows Feature Experience Pack 120.2212.4190.0

**Comment by Fenrirthviti** [comment]
We do not restrict the output resolution, this is up to the applications to support. We output vertical video if that's what it selected, it is Skype/Discord/etc. that force it to 16:9, not us.

**Comment by Fenrirthviti** [comment]
As an additional note, situations where the resolution was not properly being read should be fixed by #7934, which will be in the next release of OBS.
