### ISSUE TITLE
Unable to record a video at 2160*1215 at I444

### ISSUE THREAD

**Issue by Peter-JY** [obsproject/obs-studio#8350]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/COhkd6ly8ZAwOCZs

### Expected Behavior

Because in I420 color format, it need to combine a 2\*2 pixels to get the color, so the resolution must be able to devided by 2. But in I444, it doesn't need to do the combination, so odd recolution is posible. ffmpeg can do this. As a result, when I use obs with output with ffmpeg mode, it should provide me an output video of 2160\*1215 not 2160*1214.

### Current Behavior

I've set the color format to I444, then have set `Output Resolution` to `2160x1215`, but it output a video at 2160*1214.

### Steps to Reproduce

1. Overwrite the dlls in obs root-directory from the latest ffmpeg build. (or there won't be a libx265 encoder)
2. Choose `Color Format` to `I444`. (IMPROTANT)
3. Set `Base Resolution` to `2160x1215`.
4. Set `Output Resolution` to `2160x1215`, instead of `2160x1214` as default.
5. Choose `Custom Output(FFmpeg)`, then choose `libx265` encoder or `libx264` encoder, and set the Video Encoder Settings to `preset=ultrafast r=30 crf=24 filter:v="scale=2160:1215,setsar=sar=16/9,setdar=dar=16/9"`. (Just want to enforce the encoder output a video at 2160*1215, but it doesn't work :-( )
6. Just record things.
7. Then use ffmpeg to show the resolution. It showed `hevc (Rext), yuv444p(pc, bt709), 2160x1214, 30.30 fps, 30 tbr, 1k tbn`.

### Anything else we should know?

`-preset ultrafast -r 30 -crf 24 -filter:v scale=2160:1215,setsar=sar=16/9,setdar=dar=16/9` can be used in cmd to let ffmpeg re-encode an video at 2160*1215 at square pixels at 30fps with an crf of 24 using the ultrafast preset, so I tried to let obs do this.

**Comment by Fenrirthviti** [comment]
```
01:01:47.504: Failed to set r=30
01:01:47.504: Failed to set filter:v="scale=2160:1215,setsar=sar=16/9,setdar=dar=16/9"`
```

These are not valid parameters for the encoder. We do not use ffmpeg CLI, but the API.

This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
