### ISSUE TITLE
No video output, though the preview looked fine while recording

### ISSUE THREAD

**Issue by MorganMoss** [obsproject/obs-studio#8354]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://raveressmoss-my.sharepoint.com/:t:/g/personal/morgan_raveressmoss_onmicrosoft_com/EdpVHw9O7yJIpOEe5J6928MB4bS_r8utL6TTY8z2Zr6nuw?e=JaRv0c

### Expected Behavior

I expected the recording output to also have video, but it seems to have no data

### Current Behavior

There was seemingly no video output. The file was really small and reported a 0 bitrate video

### Steps to Reproduce

1. I opened the game Tunic in fullscreen.
2. I opened obs
3. Used a hotkey (ctrl + space)  to record and stop recording, while in the game

### Anything else we should know?

![image](https://user-images.githubusercontent.com/36437754/221432771-3cf73c60-3d1c-4164-bd89-be23d0d47a71.png)
![image](https://user-images.githubusercontent.com/36437754/221432773-9c36c521-d638-4982-8314-99042ed9d449.png)
![image](https://user-images.githubusercontent.com/36437754/221432787-ddc95ff3-a7ac-4569-bb08-01a892f86102.png)

The video that was blank in the log was after the two test runs, first was missing my mic and the second was working fine.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
