### ISSUE TITLE
ui: projectors are not restored to the last known desktop they were on 

### ISSUE THREAD

**Issue by moosdev** [obsproject/obs-studio#8355]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/6gDFlyaGafLwmFgQ

### Expected Behavior

(This requires that "Save projectors on exit" is enabled via the obs settings, and one or multiple projectors were opened and moved   to different desktops.)  
After exiting and restarting obs, all previously saved projectors are restored to the last known desktop they were on, i.e. other desktops created using the multiple desktops functionality of windows 10. 

### Current Behavior

(Again, this requires that "Save projectors on exit" is enabled via the obs settings, and one or multiple projectors were opened and moved to different desktops.)  
After exiting and restarting obs, all previously saved projectors are restored to the desktop obs was started on.
(Window and monitor position are considered and restored correctly, as expected.)

### Steps to Reproduce

1. in windows os, create a new desktop via the windows 10 multiple desktop functionality
2. in obs, in settings, enable "General -> Projectors -> Save projectors on exit"
3. in obs, create one or multiple projectors
4. move projector(s) to other previously created desktop(s)
5. close and restart obs (on any desktop)
6. projectors are restored, but all on the same desktop that obs was started on in step 5. 

### Anything else we should know?

Since previously saved projectors consider window and monitor position when restoring, I think their last known desktop should be considered too.
I've also not really _tested_ if other applications generally behave the same, but I know that firefox does restore previously saved windows to their last known desktop, which led me to believe that this may be an obs issue.

**Comment by Fenrirthviti** [comment]
Currently, virtual desktops are not a supported environment for us, so it's unlikely we'll be looking in to this ourselves.

However, at first glance, this would be something that Qt would need to explicitly support, which it looks like they do not.
