### ISSUE TITLE
Misplaced text in the "COPYING" GPL license file

### ISSUE THREAD

**Issue by leogcurvelo** [obsproject/obs-studio#8356]
### Operating System Info

Windows 11

### OBS Studio Version

29.0.2

### OBS Studio Log URL

Not applicable

### Expected Behavior

The `COPYING` file should only have the GPL terms and conditions.. Is what I would expect.

### Current Behavior

At the bottom of the file there are instructions on how to apply the license as well as additional advice and examples.

### Steps to Reproduce

1. Navigate to the [COPYING](https://github.com/obsproject/obs-studio/blob/master/COPYING) file
2. Search for "How to Apply These Terms to Your New Programs"
3. Read the file from there on forward

### Anything else we should know?

It's not a problem; it was just slightly disorienting to me when I was reading the file and found `Gnomovision version 69` and `Yoyodyne, Inc.` at the bottom..

I'm also not sure if this is actually intended, but I didn't find anything regarding this. 
I'm aware this is not an issue with the software code, but I feel like it's also not a feature request nor a topic for discussion, so I'm posting this here..

**Comment by Fenrirthviti** [comment]
This text is part of the GPL license.

https://www.gnu.org/software/toutdoux/doc/user/en/x652.html
