### ISSUE TITLE
OBS studio does not export application menu under Wayland

### ISSUE THREAD

**Issue by evertvorster** [obsproject/obs-studio#8361]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

Git

### OBS Studio Log URL

https://obsproject.com/logs/7JGJIOJmw9orqPEu

### Expected Behavior

Almost all applications export their menu to the window manager. OBS studio does this as well under X11, but not under Wayland.

### Current Behavior

When you run OBS studio under Wayland, the Application Menu is not exported to Plasma.

### Steps to Reproduce

1. Start a Wayland Plasma session
2. Open OBS Studio
3. Look at the icon next to the OBS icon in the titlebar

### Anything else we should know?

This is what an exported Application menu looks like under X11:
![image](https://user-images.githubusercontent.com/12045269/221626816-639714cc-712a-4fc6-87ea-b4a26f76a0d1.png)

The three horizontal lines are missing from the title bar under Wayland. All the other applications I use export their application menu under Wayland. 

When you work on small screens, every bit of screen space is important, and the amount of empty space in the title bars is wasted space. On KDE, you can populate that space with the Application Menu and hide the normal menu bar, giving you that extra little bit of screen area.

**Comment by tytan652** [comment]
Like I said [here](https://github.com/obsproject/obs-studio/issues/8359#issuecomment-1446566525). This is a Plasma issue with Qt6.

**Comment by tytan652** [comment]
Duplicate of 4895

**Comment by tytan652** [comment]
Duplicate of #4895

**Comment by tytan652** [comment]
Off-thread someone confirmed to me that it is an OBS issue already reported.

Sorry for the inconvenience.

**Comment by evertvorster** [comment]
With all due respect, this seems like a different issue than the cursor capture to me. 
This is purely the application interacting with the window manager. 

Here is my reasoning:
1. OBS Studio does export it's applicaiton menu under X11. 
2. Other applications export their application menu under Wayland as well as X11.

This raises questions
1. What is different between Wayland and X11 in regards with Appliction menu exporting
2. Why are other applications able to solve this "dependency issue" on Wayland right now?
3. What are they doing differently?

Sorry to be a pain about it, but at some point the world will move on from X11, and then the Wayland issues become more pressing. Are we sure this issue will be solved when KDE finally switches over to Qt6?

FYI, I am on QT5, not QT6, that's a little too experimental, even for me.

**Comment by tytan652** [comment]
The duplicate that I undo is because I mix up my tabs with the other issue, sorry.

This issue is really only on Plasma side, they enforce their Wayland decoration on any Qt application.

**Comment by evertvorster** [comment]
I did a little digging, and you might appreciate this information. 
In KDE, there is a background service called "Applications menu daemon"

This daemon takes the menu of an application and exports it to something called a global menu, which is a widget that you can place anywhere. 

This widget ends up on a panel at the top of my screen with application launchers and some icons, making KDE look a lot like GNOME and the Apple interfaces. It works really well, and is a godsend on low resolution monitors.

There are very few exceptions where this background service gets confused and is not able to produce the application's menu. OBS studio under Wayland is one, and I have seen reports of Davince Resolve also not working properly with this service. There is information on making a Kwin rule to disable the service just for Davinci here: https://wiki.archlinux.org/title/DaVinci_Resolve#Troubleshooting

I might adapt this rule for OBS, but so far I am running X11 and both this issue and the cursor issue are Wayland specific, so this is something that I will look into later when/if I decide to switch to Wayland full time, if it is still necessary at that time.

**Comment by tytan652** [comment]
Let me be clear about how Wayland works the title/header bar is normally drawn/created by the application. This is usually named CSD (Client Side Decoration, IIRC) which is normally the default and SSD (Server Side Decoration) is a fallback.

Plasma do the oposite they use SSD by default, but they seem to enforce their decoration on every Qt application rather than only their own. This is a bad behavior, they should not override our decoration and "menubar".

**Comment by evertvorster** [comment]
Thank you for the insight. 
Debating the finer points of application/window manager interaction is certainly fascinating. Whether the way that the QT devs do it is good or bad is a matter of opinion though. You dislike it, and that is your right. I, on the other hand, think that it is a good thing as I can use my very limited screen space more effectively. 

The Qt devs certainly could have provided a better way of allowing exceptions for applications that do not play nicely with the Applications menu daemon. Bugs reported to them do have a way of being forgotten about, and I have some very old and unrelated bug reports languishing in their bug reporting system. 

Anyways, on to the issue at hand. Because this menu export does actually work under X11, and not Wayland, leads me to suspect that its some permissions thing, as Wayland is supposedly more secure than X11. Of course, I am not an expert in the field, and can only report on what I see. 

As the menubar disappears when this daemon is active under Wayland, it would appear that OBS is giving it some control, but then not exporting the menu. The whole matter is moot in any case, as this bug report is closed with WONTFIX, and I will find a workaround when I need to. It may miraculously work on its own sometime in the future, who knows? It's no biggie.

Thanks again for actually responding to this bug report in an expedient way.

**Comment by tytan652** [comment]
Please don't mix up Qt devs and Plasma devs (KDE), here we are talking mostly about Plasma behavior.

> Debating the finer points of application/window manager interaction is certainly fascinating. Whether the way that the QT devs do it is good or bad is a matter of opinion though. You dislike it, and that is your right. I, on the other hand, think that it is a good thing as I can use my very limited screen space more effectively.

It is not a matter of opinion, the Wayland protocol clearly stands for CSD first and so the application must draw it.
SSD is really mostly for edge cases and IIRC the compositor has no obligation to implement one.

**Comment by jandie1505** [comment]
It seems that displaying the OBS menu in the KDE Global Menu is currently not possible. However, there is a workaround to at least show the menu within the application itself which makes it possible to use functions that are only accessible through the menu. This workaround only applies to the Flatpak version of OBS.

To get the menu back, the following command can be used:
`sudo flatpak override com.obsproject.Studio --no-talk-name=com.canonical.AppMenu.Registrar`
(This command prevents OBS from accessing the dbus interface for the global menu. This causes the menu to be displayed in OBS itself).

**Comment by leafpool243** [comment]
Does anyone know of a way to disable Application Menu Daemon for just OBS Studio (Ubuntu PPA version)? I rather like having my global menu. 😅

For now I’m just going to manually disable it before I open OBS, haha.
