### ISSUE TITLE
CSS Individual Transfrom Not Working

### ISSUE THREAD

**Issue by itzanka** [obsproject/obs-studio#8369]
### Operating System Info

Windows 11

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/LWZl5F5WIOxb62a4

### Expected Behavior

I should be able to use the translate, scale, skew and other properties which are independent from the css transform.

in browser (chrome Version 110.0.5481.105 (Official Build) (64-bit)) it runs fine.

I think this is because the embedded browser that obs uses hasn't been updated for a long time.

This css property has actually been introduced since 2019

### Current Behavior

individual properties of css transform cannot be used as they should

### Steps to Reproduce

1. create a new source browser
2. can use urls or local files
3. in css (either in source or custom css field) use individual properties of transform
4. no change in obs

css samples
```css
body {
background: red;
rotate: 45deg;
}
```

### Anything else we should know?

The independent transform css property is a new css property that makes it possible to define a translation transformation individually and independently of the transform property. This property was introduced in 2019 as part of the CSS Transforms Module specification

**Comment by WizardCM** [comment]
The requested capabilities were introduced in Chrome 104. OBS supports Chrome 103's core due to Google removing the capabilities we need for off-screen rendering in newer versions. We are unable to update for the forseeable future.
