### ISSUE TITLE
Websocket crash when using Touch Portal

### ISSUE THREAD

**Issue by prgmitchell** [obsproject/obs-studio#8370]
### Operating System Info

Windows 11

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.0.0

### OBS Studio Log URL

https://obsproject.com/logs/OaGo2P6PBwcKuYKL

### OBS Studio Crash Log URL

https://obsproject.com/logs/EfU7jNAvUBIjHvpV

### Expected Behavior

OBS should not crash.

### Current Behavior

OBS experiences a websocket related crash. I am posting this on behalf of a user in the community discord and although I don't have clear repro steps, I still think it would be best to track this.

### Steps to Reproduce

Sorry for the lack of repro steps, the only common thread amongst these crashes that I've seen have been that Touch Portal was involved in the setup. I don't use it personally and have not gotten a response from the user who originally posted about the crash when I inquired for more information.

**Comment by DSulhour** [comment]
[Crash 2023-03-03 00-20-45.txt](https://github.com/obsproject/obs-studio/files/10878508/Crash.2023-03-03.00-20-45.txt)
[Crash 2023-03-03 00-03-04.txt](https://github.com/obsproject/obs-studio/files/10878509/Crash.2023-03-03.00-03-04.txt)
[2023-03-03 00-07-18.txt](https://github.com/obsproject/obs-studio/files/10878510/2
[2023-03-02 23-04-04.txt](https://github.com/obsproject/obs-studio/files/10878512/2023-03-02.23-04-04.txt)
023-03-03.00-07-18.txt)
OBS gives a crash error after closing it. I use websocket 5 and 4.9x. Thanks!
