### ISSUE TITLE
Framerate drops and crashes livestream

### ISSUE THREAD

**Issue by OfficiallySp** [obsproject/obs-studio#8378]
### Operating System Info

Windows 11

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/UOLYboObYCXQD5DJ

### Expected Behavior

The current stream should not crash

### Current Behavior

the stream unexpectedly crashes after a couple of hours

### Steps to Reproduce

1. Start live streaming to any platform
2. After a couple of hours in the stats panel the fps drops until the stream crashes

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
