### ISSUE TITLE
Right click at group name, Add any element - it added at root but must be added inside a group

### ISSUE THREAD

**Issue by desirepl** [obsproject/obs-studio#8398]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.2

### OBS Studio Log URL

-

### Expected Behavior

Elements must be added inside an active group

### Current Behavior

Elements added outside of active group

### Steps to Reproduce

1. Add a group to scene
2. Select with LMB that group OR skip this step and move to step 3
3. RMB at this group > Add > Choose any element > Ok

This new element is created outside of selected group, it is created at root and as a topmost element.
But must be added inside selected group as a topmost group element.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a feature request rather than a bug report, and we are not currently accepting feature requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
