### ISSUE TITLE
Windows positions/sizes not remembered

### ISSUE THREAD

**Issue by desirepl** [obsproject/obs-studio#8399]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.2

### OBS Studio Log URL

-

### Expected Behavior

Windows positions/sizes must be (?) remembered

### Current Behavior

Each time windows opened at default positions and interfere with workspace closing view and lead to move/resize windows each time they've opened.

### Steps to Reproduce

1. Start new project
2. Scene list > Press "+" or RMB "Add" > Window "Add scene" with the name of the scene opens with *default* position/size. Moving/resizing it didn't remembered and adding a new scene will open that window again with default position/size. Press OK.
3. Sources list > Press "+" or RMB "Add" > Select any element (for example, "Background color") > Window "Create/select source" with the name of the selected element opens with *default* position/size. Moving/resizing it didn't remembered and adding a new scene will open that window again with default position/size (for example to other monitor). Press OK.
4. Options window of created element is opened with *default* position/size (at the main monitor, occupies the entire desktop space on the main monitor).
5. Move options window to other monitor (and/or) resize, Press OK.
6. RMB at this element, choose Options. Options window is opened with *default* position/size again...

This happens with any element and takes almost 2/3 of time when a lot of changes of options applied/tried.

**Comment by Fenrirthviti** [comment]
Properties windows are currently set to open roughly at the center of the OBS main window. This is intentional, and not a bug.

**Comment by desirepl** [comment]
Is it so hard to save 4 numbers at closing window and load 4 numbers if exist at opening?
Too sad.

**Comment by dodgepong** [comment]
We only use GitHub for bugs. Given that the current behavior is intentional, this would be a feature request, not a bug. Thus, you should post this on ideas.obsproject.com.
