### ISSUE TITLE
game capture is not working

### ISSUE THREAD

**Issue by Soham456** [obsproject/obs-studio#8409]
### Operating System Info

Windows 11

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/TaghUBGePtq0aEw9

### Expected Behavior

it should capture specific window.

### Current Behavior

it is not capturing the specified window

### Steps to Reproduce

1.added game caputre to the scene
2.specify the window to the game capture
3.it does not show the specified window.
...

### Anything else we should know?

i am new to open source and would like to contribute. sorry if this is wrong place to say this lol.

**Comment by kkartaltepe** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
