### ISSUE TITLE
Nvidia nvenc h.264(ffmpeg) take too long time

### ISSUE THREAD

**Issue by hawk0w1** [obsproject/obs-studio#8417]
### Operating System Info

Other

### Other OS

Fedora 37

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/UsWXGs5661xGzO2t

### Expected Behavior

work well

### Current Behavior

error with windows : Nvidia nvenc h.264(ffmpeg) take too long time
then the recording is stop

### Steps to Reproduce

set video record cofig to high quality
set video config to 3840x2160 and 60fps
recording

### Anything else we should know?

CPU: AMD Ryzen 9 5950X 16-Core @ 32x 3.4GHz
GPU: NVIDIA GeForce RTX 3090/PCIe/SSE2

NVIDIA driver version : 525.89.02
OBS version : 28.1.2

OS : fedora 37 with wayland

other: when set to 30fps , it works well

**Comment by hawk0w1** [comment]
OBS version : 29.02

**Comment by kkartaltepe** [comment]
Please dont open new bugs just because your earlier bug was closed.

**Comment by hawk0w1** [comment]
@kkartaltepe it's new version
