### ISSUE TITLE
Recording/Streaming Dropping Frames With AMD RX 480

### ISSUE THREAD

**Issue by bassguy95** [obsproject/obs-studio#8419]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/X70JtkAdPCB1qKuO

### Expected Behavior

Expected the RX 480 card to be able to handle encoding a 1080p 60fps 10000kbps stream/recording. This is well within the capabilities of the card.

### Current Behavior

It cannot handle the stream/recording encoding, and gets overloaded for some reason while using it with OBS. If I stream and record with the AMD software this problem does not occur. 

The card shows four encoders in windows task manager. If using OBS, windows task manager shows it at 100% utilization where if I use AMD Adrenaline it shows it at closer to 50% both encoding the same 1080p 60fps stream at 10000kbps
![OBS Util](https://user-images.githubusercontent.com/67638713/223448320-b795125e-a7bd-4b97-9db5-e58854fdcbbc.PNG)

### Steps to Reproduce

1. Open OBS while having AMD RX 480 (or equivalent) card and drivers installed
2. Begin recording/streaming a 1080p frame at 60fps 10000kbps
3. Open task manager and note the GPU utilization being reported. It should be extremely high.
4. Wait between 1 - 10 minutes and it should begin dropping every single frame.

### Anything else we should know?

Incredibly frustrating that a computer and card that SHOULD be able to handle this stream seemingly can't. I had specifically purchased this card because it was supposed to be a huge upgrade in performance from the previous 7700 AMD card that I was running. Ironically the 7700 performs BETTER than the RX 480 does in this particular instance.

**Comment by gxalpha** [comment]
Closing per Flaeri's comment. Please visit the support channels linked above.

**Comment by bassguy95** [comment]
This is unfair. It's not the drive. It's not the network. 

You're kidding if you're going to insist my SSD can't handle a 10Mbps write speed.. 

When I asked about it on the forums the response I got was "hur AMD bad"
