### ISSUE TITLE
AMD Card High Use (Forums were NOT helpful)

### ISSUE THREAD

**Issue by bassguy95** [obsproject/obs-studio#8421]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/X70JtkAdPCB1qKuO

### Expected Behavior

Expected the RX 480 card to be able to handle encoding a 1080p 60fps 10000kbps stream/recording. This is well within the capabilities of the card.

### Current Behavior

It cannot handle the stream/recording encoding, and gets overloaded for some reason while using it with OBS. If I stream and record with the AMD software this problem does not occur.

The card shows four encoders in windows task manager. If using OBS, windows task manager shows it at 100% utilization where if I use AMD Adrenaline it shows it at closer to 50% both encoding the same 1080p 60fps stream at 10000kbps

### Steps to Reproduce

1. Open OBS while having AMD RX 480 (or equivalent) card and drivers installed
2. Begin recording/streaming a 1080p frame at 60fps 10000kbps standard settings, AMD H.264
3. Open task manager and note the GPU utilization being reported. It should be extremely high.
4. Wait between 1 - 10 minutes and it should begin dropping every single frame.

### Anything else we should know?

I posted this previously and it was closed, and I was directed to the forums. The forums have ALREADY been tried, and I was given a very unfriendly response that insisted AMD cards "suck" and that I "should have bought a real video card". I was never given any real answers to my problems as none of the suggested fixes actually fixed the problem.

I'm not really happy with that response as there is no good reason that the AMD RX 480 can't handle this. The bottleneck is the card for some unknown to me reason. It has nothing to do with my network (enterprise gigabit) or my SSD which can most assuredly handle a 10Mbps write speed. Literally as evidenced by the Adrenaline software being able to accomplish the EXACT task with HALF the GPU usage.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

It looks like you're simply overloading the GPU. Try the #encoding-talk channel for assistance tuning the AMD encoder options.

Thank you!

**Comment by bassguy95** [comment]
> This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.
> 
> It looks like you're simply overloading the GPU. Try the #encoding-talk channel for assistance tuning the AMD encoder options.
> 
> Thank you!

Seriously? I just told you that I TRIED support.

**Comment by bassguy95** [comment]
> This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.
> 
> It looks like you're simply overloading the GPU. Try the #encoding-talk channel for assistance tuning the AMD encoder options.
> 
> Thank you!

Super unprofessional. Not helpful at all. 

WILL NOT RECOMMEND THIS SOFTWARE.

**Comment by bassguy95** [comment]
> This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.
> 
> It looks like you're simply overloading the GPU. Try the #encoding-talk channel for assistance tuning the AMD encoder options.
> 
> Thank you!

WHY can you not just look into it. IT IS A BUG
