### ISSUE TITLE
OBS keep resetting back to NTSC-M while recording VHS tapes

### ISSUE THREAD

**Issue by VinnyCordeiro** [obsproject/obs-studio#8431]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/IIJMAdCLdD9bkhdd

### Expected Behavior

When setting up a capture device for recording old VHS tapes (_Configure Video_ button)
![Screenshot 2023-03-08 21 47 36](https://user-images.githubusercontent.com/15346104/223886860-02837353-cc99-44d8-9532-c35a05b239dc.png)
you are presented with a screen to choose the desired video standard. By default the selected choice is NTSC_M, which is the American video standard.
![Screenshot 2023-03-08 21 47 15](https://user-images.githubusercontent.com/15346104/223887014-60742b9b-67df-48d8-9d00-dd661e7430d1.png)
The expected behavior is to choose the video standard you want (in my case PAL_M)
![Screenshot 2023-03-08 21 47 06](https://user-images.githubusercontent.com/15346104/223887111-330c6448-88a2-4581-ad14-44cf72eafef0.png)
and the option would be set for recording the tapes, whatever happens with the video source.

### Current Behavior

Every time there's an artifact on the tape's image (typically when transitioning from a recording session to another) it reverts back to NTSC-M video standard.

### Steps to Reproduce

1. Set video standard to PAL_M (or whatever video standard that isn't NTSC_M);
2. Start playing/recording video;
3. Wait until there's an artifact on the video that disrupts the image;
4. OBS will have reset the video standard back to NTSC_M. In my case, you see when that happen when the image goes from colored to black and white.

### Anything else we should know?

Changing back the video standard while playing/recording is still possible. However, because OBS keep resetting back to NTSC_M you have to baby sit the recording process, which shouldn't be needed.

**Comment by Fenrirthviti** [comment]
Can you confirm if this happens in other applications?

As a note, the "configure video" button opens the capture device's driver config. That is not an OBS window, and we don't exert any control over it. These cheap ezcap devices are notorious for being poorly made and being unreliable, so I would not be surprised if this is an issue with the card itself.

**Comment by energizerfellow** [comment]
As alluded to above, this appears to be the Ezcap capture device resetting to its default settings when the analog front-end experiences a signal dropout. The DirectShow settings panel you see are provided by the device's drivers and appears to be Windows' default UVC device support.

Fix here is to use a device that either doesn't reset on input signal loss and/or being power cycled. The Ezcap analog SD capture dongles specifically are known to be issue-prone and deep into the clone-of-a-clone territory for many, many years. Something like the I-O Data GV-USB2 or one of the [Conexant CX2310x varients](https://www.linuxtv.org/wiki/index.php/Conexant_CX2310x) would be typical alternatives, though you can certainly go higher-end than these, along with using a S-video deck to preserve the on-tape separate Y/C signals for capture without downmixing. There are also specialist SD analog capture applications specifically designed to handle unstable tapes.

**Comment by VinnyCordeiro** [comment]
> Can you confirm if this happens in other applications?
> 
> As a note, the "configure video" button opens the capture device's driver config. That is not an OBS window, and we don't exert any control over it. These cheap ezcap devices are notorious for being poorly made and being unreliable, so I would not be surprised if this is an issue with the card itself.

I'm afraid the problem really is the capture device. Long story short, I made a Win10 reinstall due to issues on my computer. On the old install only OBS was able to access the capture device, but on the new one I could also test on VLC Player, and the behavior repeated there.

I'm closing the issue, since it isn't OBS fault. Thank you for your explanation, I wasn't aware of that.
