### ISSUE TITLE
Elgato Video Capture [Audio Failure]

### ISSUE THREAD

**Issue by Kneesnap** [obsproject/obs-studio#8439]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

21.1.0

### OBS Studio Log URL

https://pastebin.com/VnWwCzrG

### Expected Behavior

I expected to be able to record audio from my Elgato Video Capture USB device, however, audio capturing fails. Only video capturing works. I will test on a new version of OBS shortly.

### Current Behavior

The video feed appears as expected in the scene, however, no audio is recorded. No audio playback occurs in my recordings, nor does the "green audio bar" which shows in the audio mixer indicate any audio is actually playing.

However, when I use the official Elgato software, I get audio playback just fine. Judging by the amount of threads on the OBS forums I've found which have the exact issue, I believe this problem is not me using the software incorrectly, but instead a problem with OBS.

I believe the relevant line from my log is:
```
14:59:07.499: [WASAPISource::TryInitialize]:[Analog Audio In (Elgato Video Capture)] Failed to get mix format: 88890008
```

### Steps to Reproduce

1. Attempt to capture audio with a composite Elgato video capture card.

**Comment by RytoEX** [comment]
OBS Studio 21.1.0 on Windows has a broken updater. The current version of OBS Studio is 29.0.2. Please update to OBS Studio 29.0.2 and try again.

**Comment by Kneesnap** [comment]
Will do. I believe it happens on newer versions because my laptop (which is running a newer version of OBS) also experiences the issue. I did just manage to find a weird workaround, detailed here: https://obsproject.com/forum/threads/transferring-vhs-to-elgato-video-capture-with-obs-but-audio-not-working.165016/#post-605412

**Comment by Kneesnap** [comment]
The audio goes away as soon as I edit that configuration window though, so this is 100% not a long-term solution I should clarify.

**Comment by RytoEX** [comment]
We will still need to see a log of this happening in OBS Studio 29.0.2 or newer. I would also recommend making sure the Elgato software and drivers are up to date.

**Comment by Kneesnap** [comment]
Updating right now! I'll check the driver version too

**Comment by Fenrirthviti** [comment]
Does the same issue occur in Elgato's software?

**Comment by Kneesnap** [comment]
No, the Elgato software plays audio just fine.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report at this point, Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for further assistance.

Thank you!
