### ISSUE TITLE
Screen Capture source stops updating after some time

### ISSUE THREAD

**Issue by sreuter** [obsproject/obs-studio#8440]
### Operating System Info

macOS 13

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/wX_Cghv6fWz-e_ny

### Expected Behavior

Screen Capture source should keep on updating with what is on the screen.

### Current Behavior

Screen Capture suddenly stops working/updating during a recording and keeps showing an outdated image.

### Steps to Reproduce

1. Configure a scene with a couple of sources (camera, etc.) including Screen Capture
2. Start recording
3. Notice how after a few minutes the image of the screen capture is not updating anymore
...

### Anything else we should know?

This also has been reported here: https://obsproject.com/forum/threads/obs-stop-record-the-image-after-sometime.160200/ .. so I linked their existing logs above.

**Comment by Fenrirthviti** [comment]
Please include a log from a current version of OBS, and not someone else's.

**Comment by jcm93** [comment]
Guessing this is the memory pressure issue that was fixed in 13.1, also.

**Comment by gxalpha** [comment]
Closing as there has been no response regarding logs from the author and current OBS, and all evidence (mostly the linked log being macOS 12.6) suggests that this is indeed the problem fixed in macOS 13.1 and newer.
