### ISSUE TITLE
OBS not launching

### ISSUE THREAD

**Issue by anfokaboom** [obsproject/obs-studio#8450]
### Operating System Info

Ubuntu 20.04

### OBS Studio Version

29.0.2

### OBS Studio Log URL

Not able

### Expected Behavior

OBS to launch

### Current Behavior

~$ obs
debug: Found portal inhibitor
debug: Attempted path: share/obs/obs-studio/locale/en-US.ini
debug: Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
debug: Attempted path: share/obs/obs-studio/locale.ini
debug: Attempted path: /usr/share/obs/obs-studio/locale.ini
debug: Attempted path: share/obs/obs-studio/locale/en-GB.ini
debug: Attempted path: /usr/share/obs/obs-studio/locale/en-GB.ini
info: Using preferred locale 'en-GB'
debug: Attempted path: share/obs/obs-studio/themes/Yami.qss
debug: Attempted path: /usr/share/obs/obs-studio/themes/Yami.qss
info: Using EGL/X11
info: CPU Name: AMD Ryzen 9 7950X 16-Core Processor
info: CPU Speed: 3000.000MHz
info: Physical Cores: 16, Logical Cores: 32
info: Physical Memory: 31229MB Total, 11470MB Free
info: Kernel Version: Linux 5.15.0-67-generic
info: Distribution: "Zorin OS" "16"
info: Session Type: x11
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.13
info: Qt Version: 5.12.8 (runtime), 5.12.8 (compiled)
info: Portable mode: false
QMetaObject::connectSlotsByName: No matching signal for on_tbar_position_valueChanged(int)
info: OBS 29.0.2 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 48000
	speakers:        2
	max buffering:   960 milliseconds
	buffering type:  dynamically increasing
info: ---------------------------------
info: Initializing OpenGL...
libEGL warning: DRI2: failed to create any config
libEGL warning: DRI2: failed to create any config
libEGL warning: MESA-LOADER: failed to open zink: /opt/amdgpu/lib/x86_64-linux-gnu/dri/zink_dri.so: cannot open shared object file: No such file or directory (search paths /opt/amdgpu/lib/x86_64-linux-gnu/dri, suffix _dri)

Segmentation fault

### Steps to Reproduce

1. Ensure prerequisitives are satisfied: https://github.com/obsproject/obs-studio/wiki/install-instructions#linux
2. Install OBS via various modes
3. Attempt to run in GUI and CLI
...

### Anything else we should know?

Prerequisites satisfied:
OpenGL version 4.6.0 Compatibility Profile Context 19.30.230130
xserver-xorg version (1:7.7+19ubuntu14)

Using Ubuntu fork Zorin OS Core 16.2

**Comment by kkartaltepe** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
