### ISSUE TITLE
SRT Stream Suffers under High Packet Loss

### ISSUE THREAD

**Issue by saltarob** [obsproject/obs-studio#8464]
### Operating System Info

macOS 13

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/FZYTptlzoncZmItR

### Expected Behavior

Sorry to open another bug report but it seems to be the only way to reach out to you. I posted my SRT stream questions and findings several times on the Discord server but I never got any respond.  

Unfortunately neither OBS nor Wowza provide any reports about the SRT stream. The Session summary of OBS seems to be not correct either. Your answers for my last findings and bug report were not satisfying, sorry. 

I reached out with my questions to the SRT Alliance Slack Server. I was advised to use Wireshark and lib-tcpdump-processing to analyse the SRT stream. They gave me following instructions: https://srtlab.github.io/srt-cookbook/how-to-articles/using-tshark-wireshark-to-analyse-srt-traffic.html. They said these tools are reliable and the results are accurate.

With these tools I captured and analysed the SRT stream on both sides. OBS and Wowza or Sender and Receiver. I made many tests over several days. I used different network connections, different computers (two MacBook Pro) and different OBS versions. I compared OBS with Wirecast and FFmpeg. The results were always the same. The SRT stream of OBS suffered from a packet loss of 20-30 % whereas Wirecast delivered the SRT stream under the exact same condition with less than one percent packet loss. If I speak about packet loss I mean the packet loss of the original transmission. Of course if the latency is big enough libsrt will retransmit the packets, several times, and the stream recovers, all packets may be recovered. But to retransmit 30 % needs a big overhead and lots of latency. 

In this report I will focus on the comparison of OBS with Wirecast. I will attach example analysis for each application's stream.

Of course you are free to close that report down again and declare it as misconfiguration. But then please try to explain what kind of misconfiguration you believe it is. Thank you.

### Current Behavior

High packet loss

### Steps to Reproduce

1. SRT stream from OBS to Wowza. Target video bitrate 5000 Mbps. Audio 192 Kbps.
2. Capture the SRT stream with Wireshark and TShark on Sender and Receiver side. 
3. Analyse the captured packages with lib-tcpdump-processing. 
4. SRT stream from Wirecast to Wowza. Target video bitrate 5000 Mbps. Audio 192 Kbps. Same video as with OBS, same computer same network.
5. Capture the SRT stream with Wireshark and TShark on Sender and Receiver side. 
6. Analyse the captured packages with lib-tcpdump-processing. 
7. Compare the lib-tcpdump-processing analysis of the OBS SRT stream with the lib-tcpdump-processing analysis of the Wirecast SRT stream.
...

**Comment by saltarob** [comment]
**OBS Sender ib-tcpdump-processing analysis:** 

<img width="775" alt="OBSSender" src="https://user-images.githubusercontent.com/7444144/224697172-08d81f10-f7c4-4d1c-9394-f0658d01503d.png">

**Wowza Receiver ib-tcpdump-processing analysis of the same OBS SRT stream:**

<img width="775" alt="WowzaReceiverOBS" src="https://user-images.githubusercontent.com/7444144/224697411-d9883646-7308-419e-8a84-51e9bebbf5a2.png">

**Wirecast Sender ib-tcpdump-processing analysis on the same MacBook Pro under the same conditions:** 

<img width="779" alt="WirecastSender" src="https://user-images.githubusercontent.com/7444144/224697628-4c5eaf44-4d4a-4152-9cd0-3baf1737a5b2.png">

**Wowza Receiver ib-tcpdump-processing analysis of the same Wirecast SRT stream:**

<img width="780" alt="WowzaReceiverWirecast" src="https://user-images.githubusercontent.com/7444144/224697780-b002b5ce-33c5-4437-9f58-a43ba2a5b18f.png">

**Comment by pkviet** [comment]
unless someone is able to repro your issue, which I'm not, I can't conclude as to whether there's a bug.
The stats summary is delivered directly by libsrt, so I think it's fairly reliable.
It does show resent packets and dropped ones in all my tests with unreliable networks.
If you don't upgrade wowza, then consider testing against another one, like nimble or airensoft Oven Media Engine. This will show if the issue is really with obs or with wowza.
You could also test against  wowza in a linux server with or without upgrade to libsrt 1.5.1. I'm not suggesting to upgrade your prod server but just a test one.
I don't have time to work as a consultant, so no i didn't make any suggestion to hire me.
I'm going to close since I can't repro the issue against my own wowza server (on linux).
If you get reliable repro steps, feel free to post and re-open.

**Comment by saltarob** [comment]
Okay thank you. Your feedback is very valuable for me.

**Comment by pkviet** [comment]
Could you test from another machine ? 
Windows and Mac preferably.
For me from windows 0% loss and perfect picture to both wowza and nimble, ome, elemental live, haivision makito ...

**Comment by saltarob** [comment]
I reported the tests of three different machines with Windows and macOS... 
But I didn't tell you yet about my tests with my Mac Pro 5,1 from 2010. On the old Mac Pro the packet loss is only 5 %.
I made many modifications on that Mac Pro, it's more a Hackintosh than a Mac. Maybe the technology of the network card in the computer has an influence. In my tests it seems as older the computer as better are the results.

**Comment by pkviet** [comment]
Sorry didn't see the test from bootcamp. The hw would be the same though. Do you have another windows pc ?
There's something which seems local to your network.
How are you connected ? 
Ethernet ? Mobile lte ? Wifi ?
Test on ethernet if the previous tests were on wifi.

**Comment by saltarob** [comment]
May I ask if you take the 0% from the session summary in the OBS log or from a lib-tcpdump-processing analysis?

All machines and tests are with Ethernet cables. But I also made some tests with Wifi which didn't make a difference in the results with a good Wifi and of course worse results with a bad Wifi.

If it would be a network issue then Wirecast and FFmpeg should also be affected from it, I think. And I made almost 100 tests now with consistent results which should exclude any fluctuations in the network.

I can do another test from my home which is 2 km from here but uses the same ISP.

**Comment by pkviet** [comment]
As I said above, the stats are straight from libsrt.
You must realize that there would be a ton of complaints if the srt output had some fatal flaw.
It doesn't work in your case for some unknown reason.
I'm out of ideas. I wrote the code, it works for me and most people.
So at this stage the only piece of advice i can give is to use wirecast. I'm unable to devote time to what seems to me a support issue since i'm unable to repro, very sorry.

**Comment by saltarob** [comment]
I understand. It may be a constellation which rarely happens or just a minor flaw in the latest libsrt stats which is just unnoticed. The libsrt 1.4.1 stats of Wirecast correspond exactly to the lib-tcpdump-processing analysis.

As a last favour, would it be maybe possible to tell me the OBS version which has libsrt 1.4.1? I would like to do some tests with this version.

Thank you so much.

**Comment by pkviet** [comment]
I don't really remember. Try 28 and 27. Sorry I can't be of much help.
