### ISSUE TITLE
[macOS] Output with H265 hardware encoder with 'auto' keyframe interval lags QuickTime, FCP, etc.

### ISSUE THREAD

**Issue by jcm93** [obsproject/obs-studio#8466]
### Operating System Info

macOS 13

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/tJC1sq4dO1Ooualk

### Expected Behavior

H265 output with the 0=auto keyframe interval should behave normally and have comparable performance with seeks, trims, etc. as prescribed keyframe intervals do (i.e. 2).

### Current Behavior

Output generated with 0=auto keyframes results in poor performance in Final Cut, QuickTime, VLC, etc. Recordings longer than approximately ~1 minute are unreasonably poorly performing when attempting seeks, trim operations, etc. Setting the keyframe interval to e.g. 2 resolves the issue.

### Steps to Reproduce

1. Set encoder to Apple VT HEVC Hardware Encoder.
2. Ensure keyframe interval is 0=auto. ~~Container and bitrate control method does not seem to matter~~ Seems to occur in ABR or CRF mode, with any container on my system. Occurs with remuxed mkvs, or when recording directly to mp4/mov.
3. Record for at least one minute.
4. Open the resulting file and try to manipulate it in editor of choice (FCP, QuickTime, and VLC tested).

### Anything else we should know?

Successfully trimming a small section at the end of these videos with QuickTime seems to result in an abnormally large file near in size to the original. This seems odd but I do not know enough to speculate about possible causes from that info.

Not sure if this is could be an encoder issue, or maybe some issue with ffmpeg or another part of OBS's H265 path.

Tested to occur with or without b-frames enabled in OBS, and with other reasonable keyframe intervals like 4 and 5 (which perform as expected)

Example video uploaded to Discord: https://cdn.discordapp.com/attachments/1016400504814837811/1084899034621280366/2023-03-13_12-57-04.mov

**Comment by gxalpha** [comment]
I was able reproduce this.
It specifically only happened with the HEVC Hardware encoder, and only in CRF (Constant Quality) mode. MP4/MKV showed the described behavior, MOV didn't even bother starting to write (nothing happens, when you click "Stop Recording" it hangs infinitely and when I force-quit it, I got "Couldn't initialize muxer" in stdout).

*However* after trying again when writing this report, it magically started working again. And then it not working again. So doesn't seem to have a 100% reproduction rate.

**Comment by norihiro** [comment]
> Example video uploaded to Discord: https://cdn.discordapp.com/attachments/1016400504814837811/1084899034621280366/2023-03-13_12-57-04.mov

It's a 60 fps video with 4133 frames. Interestingly, there is only one keyframe.

**Comment by jcm93** [comment]
Interesting followups. I've just now confirmed on my end that the issue occurs with CRF as well as ABR, but *not* CBR mode as I initially thought. Writing directly to .mov, however, works fine and reproduces the issue reliably on my system. With respect to Sebastian's .mov output failure, there could be separate issues at play here. On my end, CRF or ABR together with auto keyframe seems to be the common denominator, regardless of container.
