### ISSUE TITLE
"QLabel" text is not vertical aligned with the text on the right.

### ISSUE THREAD

**Issue by TianQiBuTian** [obsproject/obs-studio#8468]
### Operating System Info

Windows 10

### OBS Studio Version

Git

### OBS Studio Version (Other)

b31344d82ec60608e03b9648f5ff96fa486d5c9a

### OBS Studio Log URL

UI bug

### Expected Behavior

Vertical aligned with the text on the right.

### Current Behavior

![label](https://user-images.githubusercontent.com/26628474/225126676-87203839-0c99-42e1-8b0e-d60f1bb1dc3c.png)
1. Fill in the blank box
2. Hotkeys box
3. Select list box

### Steps to Reproduce

UI bug

**Comment by SuslikV** [comment]
Note. I didn't find the shift in v23.1.0 (but all later versions are affected).

**Comment by TianQiBuTian** [comment]
#8747 only fixed hotkey pages in the Yami theme and did not fix other "QLabel".
And on the hotkey page in the Dark/System theme:
![hotkey](https://user-images.githubusercontent.com/26628474/233633999-fc147d81-752f-4a2b-9cb6-3916991cc2cf.png)
So I request to reopen this issue.
