### ISSUE TITLE
unable to capture primary display via display capture

### ISSUE THREAD

**Issue by gatherium** [obsproject/obs-studio#8472]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/hw09qi9eWm32YVYG

### Expected Behavior

having my primary monitor being the one that was captured by display capture

### Current Behavior

only secondary monitor can be captured

### Steps to Reproduce

1. make a new scene
2. create a new display capture source
3. select primary monitor
4. doesnt capture primary monitor only captures secondary monitor

### Anything else we should know?

havent used obs in a while, but i updated everything today, everything works (so far as i can tell) besides the display capture. when i go to settings on display capture to set a different display, both of my monitors show up in the drop down. i select my primary display (lg ultra gear) and click ok and in the preview window it shows my secondary monitor(benq). when i have the display capture selected just below the preview it shows that the LG monitor is being displayed, but actually its the benq monitor being displayed. i have windows up to date. my graphics drivers are up to date as of writing this 2:40pm march 15th 2023.  obs is updated to the latest stable build. i updated the stream elements live plugin. ive restarted my pc and restarted obs.

the only way i can get obs to display capture my primary monitor(LG) is if i disconnect my benq display in windows. but as soon as i reconnect it, it changes the display capture to benq.

windows does show both monitors, obs shows both monitors.

everything else seems to work. even if i have something on my LG monitor and do window or game capture, it works fine.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by gatherium** [comment]
I had a conversation with someone on discord troubleshooting this issue and
they directed me to submit this bug report since we couldn't resolve the
issue.

**Comment by Fenrirthviti** [comment]
Assuming this was unresolved in support, there is already an issue for tracking here: https://github.com/obsproject/obs-studio/issues/8181

**Comment by Fenrirthviti** [comment]
Duplicate of #8181
