### ISSUE TITLE
[29.0.2] Simple recording settings with [high qualtiy, medium filesize] uses quality preset on AMF causing overload on RX580 which can handle 1080p60 only with balanced preset

### ISSUE THREAD

**Issue by gutko** [obsproject/obs-studio#8502]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://pastebin.com/WTLcxjcX

### Expected Behavior

when using simple settings and wizard with [high quality medium file size] obs uses balanced profile on RX580 for 1080p60

### Current Behavior

when using simple settings and wizard with [high quality medium file size] obs uses quality profile which causes RX580 (probably whole polaris line) to overload in 1080p60 because it can handle 1080p60 only in balanced preset

### Steps to Reproduce

1. have rx580 - probably any card from polaris lineup which cant handle 1080p60 on amf quality preset
2. use wizard or use simple settings with {high quality, med file size}
3. get encoder overload in 1080p60

### Anything else we should know?

not sure how it should be handled because its hardware limitation of polaris lineup. ideal solution would be detection if gpu is polaris and default use of balanced preset in such case for 1080p
using latest 23.3.1 driver at the time of this report

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
