### ISSUE TITLE
I think its a system memory/GPU issue but OBS keeps crashing/droping the stream 

### ISSUE THREAD

**Issue by michaelpaulsen** [obsproject/obs-studio#8514]
### Operating System Info

Windows 11

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/6DdXnLjbJcLKZmAO

### OBS Studio Crash Log URL

https://obsproject.com/logs/155Duv5YM6B2fsIq

### Expected Behavior

for obs to not crash [though I am nearly positive it is an issue with my GPU or a lack of Vram I am more posting this just in case it is not] 

### Current Behavior

Obs froze then recovered but my frame rate was super low.  When I tried to close OBS, to reset it, Windows poped up a segfault message [I hope a crash report was created]. I think that this is more to do with my GPU overheating and crashing, because I have issues running UE5 too [and I am running on a laptop]. 

### Steps to Reproduce

it seems to be, in large part a random event, however I was streaming a minecraft mod pack so that could be part of it. 

### Anything else we should know?

I am using the multiple output plug-in to stream to both twitch and youtube [hence why I think it is a [V]RAM/GPU issue]

**Comment by notr1ch** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
