### ISSUE TITLE
Audio Output Capture becomes inactive in studio mode

### ISSUE THREAD

**Issue by Vlad-Zumer** [obsproject/obs-studio#8518]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/y7x1iBNJuQjOmEtY

### Expected Behavior

Audio Output Capture should still be present in studio mode.

### Current Behavior

Audio Output Capture should still gets set to inactive.

### Steps to Reproduce

1. Open OBS and switch out of "Studio Mode".
1. Make new scene.
1. Add a Audio Output Capture to the scene
1. Notice that it appears in the Audio Mixer
1. Switch to "Studio Mode"
1. Notice that the Audio Output Capture is no longer in the Audio Mixer
1. Result persists even after "transitioning to live scene".

See: https://www.youtube.com/watch?v=-J9lGssORjM

**Comment by derrod** [comment]
The source in question is from the third-party [win-capture-audio](https://github.com/bozbez/win-capture-audio) plugin, the OBS native version works just fine.

**Comment by notr1ch** [comment]
You are using the 3rd party plugin "win-audio-capture", not the audio output capture built into OBS Studio. You should report your issues to the plugin developer.

**Comment by Vlad-Zumer** [comment]
Thank you!
