### ISSUE TITLE
Linux: NVENC Issue when streaming but not when recording

### ISSUE THREAD

**Issue by ShadiestGoat** [obsproject/obs-studio#8521]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

Git

### OBS Studio Log URL

https://obsproject.com/logs/RlQMMKnYQoQWB1Df

### Expected Behavior

I expect for OBS to be able to either stream, or be consistently not working between streaming and recording, when using the same encoder for recording and streaming.

### Current Behavior

When streaming, OBS refuses:

> Starting the output failed. Please check the log details.
> 
> Note: if you are using the NVENC or AMD encoders, make usre your video drivers are up to date.

When recording, it seems to record fine.

### Steps to Reproduce

Unsure. My GPU is the following:

> NVIDIA GeForce GTX 1650 Ti Mobile

I use the proprietary Nvidia drivers. 

### Anything else we should know?

My Nvidia driver version is `525.89.02-13`, which is not the latest, `530.41.03-1`, since the latest causes issues with my second monitor. I have not tested for this bug on that version.

This bug feels odd to me - recording and streaming should have the same set of checks, so how come it works on one but not the other? This is why to me, it seems more like an OBS issue than a driver issue.

Using the chaotic-aur version

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

As a note, looks like you have an issue with your streaming service settings: ```19:40:37.681: The protocol '' is not registered```

Thank you!

**Comment by RytoEX** [comment]
This might have been fixed by #8508 .

**Comment by ShadiestGoat** [comment]
> This might have been fixed by #8508 .

This was fixed by this pr, thank you!
