### ISSUE TITLE
New AMF doesn't support reconfiguration properly

### ISSUE THREAD

**Issue by MattyFresh68** [obsproject/obs-studio#8548]
### Operating System Info

Windows 11

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/O4PGzxUYDutvJB6C

### Expected Behavior

I expect to be able to adjust bitrate during an active stream output and the bitrate change to either apply, or at the very least, silently remain the same. 

### Current Behavior

With the change to the new version of amf, updating bitrate during an active output will hard lock at 0kbps. OBS will then also hang requiring killing it with task manager. 

### Steps to Reproduce

1. start stream at 3500kbps(I used twitch but other user in discord repro to YT)
2. adjust bitrate of stream output to 4500kbps
3.watch bitrate lock at 0kbps with green indicator
4.press stop stream
5.close obs(will then still be active in task manager until killed)

**Comment by MattyFresh68** [comment]
As I can't personally test, but based on a report in discord, it seems this behavior also occurs using av1 on amd hardware.

**Comment by RytoEX** [comment]
Can confirm on an RX 6600M.

**Comment by Johl7** [comment]
Late to the party, tested here briefly with the mentioned OBS vers.. Couldnt repro on my Polaris gpu, using the latest drivers.

**Comment by flaeri** [comment]
I'll add my confirmation as well. Pretty much instant encoder death on bitrate change reconfig.

https://obsproject.com/logs/Ik2S2z7XsnUiOXde

23.4.2 drivers, 29.0.2 OBS. Please always include a log if confirming/disproving :)
