### ISSUE TITLE
Application that freezes OBS

### ISSUE THREAD

**Issue by style1925** [obsproject/obs-studio#8552]
### Operating System Info

Windows 11

### OBS Studio Version

29.0.2

### OBS Studio Log URL

n/a

### Expected Behavior

OBS does not freeze.

### Current Behavior

OBS freezes.

### Steps to Reproduce

1, OBS "Preview" freeze
Application Information
Application name : Bandicam
DLL name : bdcam64.dll
DLL File Location : C:\Program Files\Bandicam\bdcam64.dll
log file : https://obsproject.com/logs/EOF6PGfffo3LyED2

Steps to Reproduce
bug video : https://youtu.be/-QXlTdpUzao

1. Download and install Bandicam ( https://www.bandicam.com/ )
2. Start Bandicam and use 'Game Recording' mode.
3. Click on OBS. (Make sure Bandicam shows obs64.exe)
4. Exit Bandicam.
5. Only the OBS preview will freeze.

***
2, OBS "Video Capture Device Properties" freeze (UnityCapture)

Application Information
Application name : VirtualMotionCapture
Application Version : v0.51f2
Device name : VMC_Camera
DLL name : VMC_CameraFilter64bit.dll (Timestamp November 2018)
DLL File Location : C:\VMC_Camera\VMC_CameraFilter64bit.dll (If step 4 is done)
DLL File Location : VirtualMotionCapture0.51f2\ControlPanel\VMC_Camera\VMC_CameraFilter64bit.dll
Note : The VMC_CameraFilter64bit.dll (Timestamp December 2022) in the latest version v0.54f1 seems to be fixed.
https://github.com/sh-akira/VirtualMotionCapture/releases/tag/v0.54f1

Steps to Reproduce
bug video : https://youtu.be/FwpKSxSDVW8
(OBS Classic was used to verify the device listings).

1. Download version v0.51f2
https://github.com/sh-akira/VirtualMotionCapture/releases/tag/v0.51f2
2. Launch VirtualMotionCapture.exe 
3. Press "Setting" when the "Control panel" window appears.
4. Press "Install" in "Virtual WebCam Setting"
5. Add a video capture device with OBS.
6. Properties freeze!

***

Application Information
Application name : HolisticMotionCapture
Application Version : v1.1.0
Device name : HolisticMotionCapture
DLL name : HolisticMotionCaptureFilter64bit.dll
DLL File Location : C:\Program Files (x86)\HolisticMotionCapture\VirtualCamera\HolisticMotionCaptureFilter64bit.dll

Steps to Reproduce
bug video : https://youtu.be/4AjQdzBSLLc
(OBS Classic was used to verify the device listings).

1. Download version 1.1.0 (HolisticMotionCapture-1.1.0setup.exe)
https://github.com/creativeIKEP/HolisticMotionCapture/releases
2. Launch HolisticMotionCapture-1.1.0setup.exe
3. install.
4. Add a video capture device with OBS.
5. Properties freeze!

### Anything else we should know?

@notr1ch 
I was told on the Discord development channel that it is preferable to post information on github.
https://discord.com/channels/348973006581923840/374636084883095554/1090030538439532714

Sorry if my english is wrong as I am using a translation.

**Comment by notr1ch** [comment]
Thanks for the detailed report and reproduction videos! I've opened a PR to block these in a future release.

**Comment by style1925** [comment]
Thank you for opened a PR to block!
