### ISSUE TITLE
[Nightly Build] Property Window Issues

### ISSUE THREAD

**Issue by style1925** [obsproject/obs-studio#8553]
### Operating System Info

Windows 11

### OBS Studio Version

Git

### OBS Studio Version (Other)

master 712a6c3

### OBS Studio Log URL

n/a

### Expected Behavior

Same behavior as 29.0.2

### Current Behavior

It moves strangely.

Nightly Build (bug video)

https://user-images.githubusercontent.com/1337354/228135765-eadbbf0e-6f8c-445d-af72-af1264020b1c.mp4

***

29.0.2

https://user-images.githubusercontent.com/1337354/228135793-ea56faa4-8049-4c82-8e13-107f480a1eba.mp4

### Steps to Reproduce

1. Launch Nightly Build.
2. Open the properties of "Text (GDI+)"
3. Scroll to the end of the properties.
4. Check the checkbox.
5. The property scrolls by itself.

### Anything else we should know?

The problem occurs after a0b5c1b3f5027600f097ad180ff2efa5baf73df4
( It does not occur with b2375a0660b9174a42e05ce1b32ae63e2457e5b1 )

**Comment by WizardCM** [comment]
This bug only seems to occur in Yami-based themes. It does not occur in Dark or System. This likely means it's tied to padding somewhere.

**Comment by style1925** [comment]
@WizardCM 
Dark or  system also occur.
I downloaded several Nightly Builds and looked for the date the problem occurred.
The problem occurs after a0b5c1b  (It does not occur with b2375a0660b9174a42e05ce1b32ae63e2457e5b1 )

![log](https://user-images.githubusercontent.com/1337354/228145528-10725aa9-9f1e-4748-aa37-226220e40782.png)

Nightly Build (bug video)

https://user-images.githubusercontent.com/1337354/228141223-0cdfdfc6-c2e5-4c60-89ae-c6bb98e642e9.mp4

***

29.0.2

https://user-images.githubusercontent.com/1337354/228141270-47c423f7-ad6f-48b7-8be5-1a94c762600b.mp4
