### ISSUE TITLE
Turning on the OBS Replay Buffer with the NVENC encoder prevents 2080Ti from reaching its maximum performance level, getting stuck at 4/5 instead of being able to reach 5/5 (Maximum performance)

### ISSUE THREAD

**Issue by ipaqmaster** [obsproject/obs-studio#8574]
### Operating System Info

Other

### Other OS

Arch Linux, Kernel 6.2.7-arch1-1

### OBS Studio Version

29.0.2

### OBS Studio Version (Other)

OBS Studio - 29.0.2-2 (linux)

### OBS Studio Log URL

https://pastebin.com/Mp5pEG5q

### OBS Studio Crash Log URL

NA

### Expected Behavior

2080Ti graphics card is expected to be able to access its maximum performance setting as is immediately possible while the OBS Replay Buffer isn't running.

### Current Behavior

2080Ti graphics card gets stuck at performance level 4/5, slightly below its maximum potential while the OBS Replay Buffer is running with NVENC.

### Steps to Reproduce

1. Set recordings to use NVENC
2. open `nvidia-settings` and go to the "PowerMizer" tab
3. Toggle the replay buffer on and off with graphically demanding software running. It will flip between maximum performance and one level before that as you toggle the OBS Replay Buffer on and off.

No amount of tweaking in this "PowerMizer" menu can get the GPU to maximum performance while the OBS Replay Buffer is active.

### Anything else we should know?

Is this just NVIDIA's intentional design I'm seeing when using NVENC?

**Comment by kkartaltepe** [comment]
The power level is controlled by your drivers. I dont see any performance issues in your log so this doesnt seem like an issue.
