### ISSUE TITLE
Image Slideshow remains on screen after scene change

### ISSUE THREAD

**Issue by Balzac40** [obsproject/obs-studio#8575]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.1 Beta

### OBS Studio Log URL

None

### OBS Studio Crash Log URL

(https://obsproject.com/logs/31z7mWqtM0W0hOqv)

### Expected Behavior

When switching from Scene 1 (including an Image Slideshow running) to another Scene, Slideshow must disappear.

### Current Behavior

Slideshow remains on output screen, on every other scene(s).

### Steps to Reproduce

1. Include a Slideshow on a Scene
2. Switch to another Scene
3. The Slideshow remains on screen
...

**Comment by Fenrirthviti** [comment]
Please include a log file, or this is unactionable.

**Comment by Balzac40** [comment]
It seems a problem with my scenes collection... Sorry
