### ISSUE TITLE
OBS Crashes with AMD RX6600 + Ryzen 5 7600X setup

### ISSUE THREAD

**Issue by maksic87** [obsproject/obs-studio#8576]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/0zXiKjdrPkDszmq0

### OBS Studio Crash Log URL

https://obsproject.com/logs/COjhoAvwCOQ4818g

### Expected Behavior

OBS to not crash after switching scenes or while using it

### Current Behavior

Sometimes it crashes when switching scenes, or during a stream decoder just halts and stops decoding.

### Steps to Reproduce

1.Open OBS
2.Start streaming
3.It randomly crashes, not 100% of the time
...

### Anything else we should know?

My hardware is as follows:

- MB MSI PRO B650-P WIFI
- VGA AsRock 6600 Challenger 8GB
- CPU AMD Ryzen 5 7600X AM5
- Cooler CPU Noctua NH-D15 chromax.black
- RAM 32GB DDR 5 Kingston FURY 6000 MHz
- PSU FSP Hydro PRO 800W
- Storage NVMe Samsung SSD 980 PRO 250GB

**Comment by maksic87** [comment]
Did and it seems to be patched in the newest AMD driver. Did not have any further crashes once the latest driver was installed.

**Comment by gxalpha** [comment]
Thank you for your response.
As this is resolved, I will close this issue.
