### ISSUE TITLE
AV1 for AMD 7000 Series Not Showing In Simple Mode Encoder Options List

### ISSUE THREAD

**Issue by KevinEightSeven** [obsproject/obs-studio#8584]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.0-beta1

### OBS Studio Log URL

https://obsproject.com/logs/aPCLGspVLOfqOIjU

### Expected Behavior

I expected to be able to select AV1 encoder for my 7900 XTX under the simple menu for the streaming section however it only shows up in the recording section. I'm only limited to H264 and HEVC options.

### Current Behavior

I'm only able to select AV1 under the advanced output mode for streaming.

### Steps to Reproduce

Nothing other than having the latest AMD graphics card I assume. Bug is there if it is indeed a bug the application is opened.

### Anything else we should know?

You guys rock!? XD

**Comment by pannal** [comment]
This might be slightly off-topic (I'll create a separate ticket if necessary), but: When an SRT streaming target is set, AMD AV1 isn't selectable. Only with RTMP (which doesn't work with Nimble Streamer, even not when using HEVC).

**Comment by Jhinta** [comment]
When i select the av1 for streaming its showing me a resolution of 1918x1080 witch youtube doesnt like.
Compiled from source and added av1 support and default build.
output res is 1920x1080

**Comment by RytoEX** [comment]
> When i select the av1 for streaming its showing me a resolution of 1920x1048 witch youtube doesnt like. Compiled from source and added av1 support and default build. output res is 1920x1080 7900xtx

"Viewport" size is the size of the player inside your browser. It is not related to the size of the video sent to YouTube.
