### ISSUE TITLE
AMD HW AV1 not selectable with SRT target

### ISSUE THREAD

**Issue by pannal** [obsproject/obs-studio#8590]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.0-beta1

### OBS Studio Log URL

https://obsproject.com/logs/QWRwAv3anTAPV3D4

### Expected Behavior

I should be able to stream AV1 to an SRT endpoint as SRT is codec-agnostic.

### Current Behavior

When an SRT endpoint is set as streaming target, the AMD HW AV1 encoder isn't selectable. With an RTMP target it is.

![image](https://user-images.githubusercontent.com/1359593/228826518-2a4a6290-5d6e-482c-a4e3-bfd631af97c5.png)

### Steps to Reproduce

1. Set up an SRT streaming endpoint in OBS
2. Try to select AMD HW AV1

**Comment by derrod** [comment]
SRT is using MPEG-TS to encapsulate the video data, which doesn't support AV1 yet.

**Comment by derrod** [comment]
Pretty much. And ffmpeg might only start implementing it once it has become actually part of the mpeg-ts standard.

**Comment by pkviet** [comment]
Closing since it's not implementable yet
