### ISSUE TITLE
OBS failed to start encoding when using QSV HEVC in LA_ICQ mode

### ISSUE THREAD

**Issue by Ptilopsis01** [obsproject/obs-studio#8591]
### Operating System Info

Windows 11

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/hJFuWZpO8gbifB1Z

### Expected Behavior

LA_ICQ mode can be functioning properly.

### Current Behavior

When using IA_ICQ mode in QSV HEVC encoding, an error was reported like:
![屏幕截图 2023-03-30 200958](https://user-images.githubusercontent.com/93318731/228831558-8e920e40-26d9-410e-8e72-9450a65cdeae.png)

### Steps to Reproduce

1.Choose QSV HEVC as encoder
2.Use LA_ICQ mode
3.Begin encoding
...

**Comment by WizardCM** [comment]
```
20:05:08.654: >>> app not on intel GPU, fall back to old qsv encoder
20:05:08.654: [qsv encoder: 'advanced_video_recording'] settings:
20:05:08.654: 	rate_control:   LA_ICQ
20:05:08.654: 	ICQ Quality:    18
20:05:08.654: 	Lookahead Depth:30
20:05:08.654: 	fps_num:        30
20:05:08.654: 	fps_den:        1
20:05:08.654: 	width:          2560
20:05:08.654: 	height:         1440
20:05:08.654: [qsv encoder: 'advanced_video_recording'] debug info:
20:05:08.668: 	impl:           D3D11
20:05:08.668: 	surf:           D3D11
20:05:08.737: [qsv encoder: 'msdk_impl'] Unsupported configurations, parameters, or features (MFX_ERR_UNSUPPORTED)
20:05:08.744: [qsv encoder: 'advanced_video_recording'] qsv failed to load
20:05:08.744: 	major:          1
20:05:08.744: 	minor:          255
```

**Comment by RytoEX** [comment]
My guess would be that QSV HEVC does not support Lookahead - the "LA" part of LA_ICQ/LA_CBR/LA_VBR.

**Comment by Ptilopsis01** [comment]
> My guess would be that QSV HEVC does not support Lookahead - the "LA" part of LA_ICQ/LA_CBR/LA_VBR.

I agree, they all failed in my test; However, it would be strange to show such an option here if it is not usable.

**Comment by RytoEX** [comment]
> > My guess would be that QSV HEVC does not support Lookahead - the "LA" part of LA_ICQ/LA_CBR/LA_VBR.
> 
> I agree, they all failed in my test; However, it would be strange to show such an option here if it is not usable.

We currently don't do any capabilities testing to filter the list of rate control methods here. While we could do that, it could result in the user's rate control method choice being reset to something they did not mean to choose. For example, if the user chose LA_ICQ for H.264, but then chose a codec that does not support LA_ICQ, and we reset the rate control method to default (CBR), and they do not notice. To handle this gracefully, we would probably need to fallback to the non-LA variants of each rate control method, but that is probably more work.

**Comment by Ptilopsis01** [comment]
> > > My guess would be that QSV HEVC does not support Lookahead - the "LA" part of LA_ICQ/LA_CBR/LA_VBR.
> > 
> > 
> > I agree, they all failed in my test; However, it would be strange to show such an option here if it is not usable.
> 
> We currently don't do any capabilities testing to filter the list of rate control methods here. While we could do that, it could result in the user's rate control method choice being reset to something they did not mean to choose. For example, if the user chose LA_ICQ for H.264, but then chose a codec that does not support LA_ICQ, and we reset the rate control method to default (CBR), and they do not notice. To handle this gracefully, we would probably need to fallback to the non-LA variants of each rate control method, but that is probably more work.

I understand...thanks a lot

**Comment by Fenrirthviti** [comment]
Closing as this is currently expected, and a change to current behavior would be a feature request.
