### ISSUE TITLE
Build fails with CMake < 3.19

### ISSUE THREAD

**Issue by c4ashley** [obsproject/obs-studio#8595]
### Operating System Info

Other

### Other OS

Debian Bullseye

### OBS Studio Version

Git

### OBS Studio Log URL

n/a

### Expected Behavior

Using CI/build-linux.sh I expected all prerequisites to be installed as required, or a friendly error message where prerequisites couldn't be satisfied trivially.

### Current Behavior

CMake Error at deps/media-playback/CMakeLists.txt:5 (add_library):
  add_library INTERFACE library may not be used with EXCLUDE_FROM_ALL.

### Steps to Reproduce

1. $ sudo apt update && sudo apt full-upgrade
2. $ git clone --recursive https://github.com/obsproject/obs-studio.git && cd obs-studio
3. $ CI/build-linux.sh

### Anything else we should know?

deps/media-playback/CMakeLists.txt should be updated to hint a minimum CMake version of 3.19, since that was when "EXCLUDE_FROM_ALL" became allowable with interface libraries.

At the time of writing, Debian Bullseye (stable) only packages CMake 3.18 so manual installation of a later CMake is required. Seems to work OK with a freshly built CMake 3.26.2.

**Comment by gxalpha** [comment]
Fixed by #8579

**Comment by gxalpha** [comment]
Oh wait, no.
Apologies.
