### ISSUE TITLE
OBS Crashes when saving a replay with Fragmented MP4 or Fragmented MOV

### ISSUE THREAD

**Issue by Breadsniffer** [obsproject/obs-studio#8603]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.0-beta1

### OBS Studio Log URL

https://obsproject.com/logs/ptfygNUUrb5vdQsN

### OBS Studio Crash Log URL

https://obsproject.com/logs/HujtCQVkB5XnLEUx

### Expected Behavior

OBS to not crash when saving a replay with Fragmented MP4 or Fragmented MOV selected

### Current Behavior

OBS Crashes when saving a replay with Fragmented MP4 or Fragmented MOV selected

### Steps to Reproduce

1. Select Fragmented MP4 or Fragmented MOV as recording format
2. Start replay buffer
3. Save a replay
4. It crashes
...

**Comment by RytoEX** [comment]
Could you confirm what encoder settings you had selected? The normal OBS log is cut off before that information is logged.

**Comment by Breadsniffer** [comment]
nvidia nvenc h264

**Comment by Breadsniffer** [comment]
oh I didn't catch what you meant

Rate control = CBR
Bitrate = 35000 Kbps
Keyframe Interval = 0 s
Preset = P7: Slowest
Tuning = High Quality
Multipass mode = Two Passes Quarter Resolution
Profile = high
Look-ahead = off
Psycho Visual Tuning = on
GPU = 0
Max B-frames = 2
