### ISSUE TITLE
Build errors on Fedora with 29.1.0-beta1

### ISSUE THREAD

**Issue by GloriousEggroll** [obsproject/obs-studio#8609]
### Operating System Info

Windows 11

### Other OS

Fedora/Nobara

### OBS Studio Version

29.1.0-beta1

### OBS Studio Log URL

N/A, build/compile issue

### Expected Behavior

Build without errors

### Current Behavior

(1)
```
/builddir/build/BUILD/obs-studio-ac87106f032b9ac850d97b18a1354cdcc7f0cdc4/plugins/linux-pipewire/pipewire.c: In function 'obs_pipewire_get_width':
/builddir/build/BUILD/obs-studio-ac87106f032b9ac850d97b18a1354cdcc7f0cdc4/plugins/linux-pipewire/pipewire.c:1050:1: error: control reaches end of non-void function [-Werror=return-type]
 1050 | }
```
(2)
```
In function 'memset',
    inlined from 'darray_push_back_new' at /builddir/build/BUILD/obs-studio-ac87106f032b9ac850d97b18a1354cdcc7f0cdc4/libobs/util/darray.h:213:2,
    inlined from 'init_format_info' at /builddir/build/BUILD/obs-studio-ac87106f032b9ac850d97b18a1354cdcc7f0cdc4/plugins/linux-pipewire/pipewire.c:454:10,
    inlined from 'obs_pipewire_create' at /builddir/build/BUILD/obs-studio-ac87106f032b9ac850d97b18a1354cdcc7f0cdc4/plugins/linux-pipewire/pipewire.c:919:2:
/usr/include/bits/string_fortified.h:59:10: error: 'memset' offset [0, 23] is out of the bounds [0, 0] [-Werror=array-bounds]
   59 |   return __builtin___memset_chk (__dest, __ch, __len,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   60 |                                  __glibc_objsize0 (__dest));
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

### Steps to Reproduce

1. Grab copy of current rpmfusion build files:
https://github.com/rpmfusion/obs-studio

2. in spec sheet change version, add the following new build dependencies:
BuildRequires:	libuuid-devel
BuildRequires:	json-devel
BuildRequires:	asio-devel
BuildRequires:	AMF-devel

3. Try to build (I use a custom mock config that has the rpmfusion repos added):
mock -r nobara-37-x86_64.cfg --rebuild --enable-network *.src.rpm
[nobara-37-x86_64.zip](https://github.com/obsproject/obs-studio/files/11126998/nobara-37-x86_64.zip)

**Comment by mihawk90** [comment]
Ran into the same thing and it seems the RPM builder is using a stricter GCC flag configuration then usual which results in this warning which turns into an error due to `-Werror`.

Unless you know a better solution to change the RPM builder flags, this helps:

https://github.com/mihawk90/obs-studio.spec/blob/389c0c25fe6d033416b2fde1f78c7065c7e0a6ef/obs-studio.spec#L123

**Comment by GloriousEggroll** [comment]
Thanks for the workaround. Looks like it's caused by this commit:

https://github.com/obsproject/obs-studio/commit/189c6939d11ad16a92cbb76c9132c0de3e0eb140

**Comment by kkartaltepe** [comment]
PRs welcome, but closing as it doesnt fail with our flag configuration. You can read the comments in the darray code and maybe suggest an alternate pragma if desired. The switch arms are fully covered so that one just seems pedantic as well.

**Comment by kkartaltepe** [comment]
Also im not opposed to just giving packagers an option to opt out of all our common flags if people prefer that, though I think there are also other cmake changes pending. So that might have to wait for a bit.
