### ISSUE TITLE
Turning on 'Decklink Output > Start' turns random settings text black.

### ISSUE THREAD

**Issue by lindenkron** [obsproject/obs-studio#8620]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/uM03ivUVIJJP42rr

### Expected Behavior

Dont turn text black.

### Current Behavior

Text turning.. black.

### Steps to Reproduce

1. Decklink Output
2. 'Start'
3. Go to Settings menu, random text is black.

### Anything else we should know?

Recording on clean 29.0.2:
https://streamable.com/yvjhci

**Comment by derrod** [comment]
This should be fixed by #8321, please check the 29.1 beta.

**Comment by lindenkron** [comment]
Appears to be fixed in beta. Thanks.
