### ISSUE TITLE
Core dump when begin record

### ISSUE THREAD

**Issue by zhen-NA** [obsproject/obs-studio#8639]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/fEtLt6mY7NhgkNdD

### OBS Studio Crash Log URL

https://obsproject.com/logs/fEtLt6mY7NhgkNdD

### Expected Behavior

I wanted to record the screen, but after clicking the start button, OBS crashed

### Current Behavior

click "开始录制“，then，core dump

### Steps to Reproduce

1. Open  OBS
2. click "开始录制"

### Anything else we should know?

environment: Arch Linux + KDE + X11
error: [h264_nvenc @ 0x563db80f0800] dl_fn->cuda_dl->cuInit(0) failed -> CUDA_ERROR_UNKNOWN: unknown error
段错误 (核心已转储)
[terminal_output.txt](https://github.com/obsproject/obs-studio/files/11139425/terminal_output.txt)

**Comment by kkartaltepe** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
