### ISSUE TITLE
Browser hardware acceleration doesnt work after building from source.

### ISSUE THREAD

**Issue by draccurate** [obsproject/obs-studio#8657]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.0-beta1

### OBS Studio Log URL

theres no log fils

### Expected Behavior

I should work fine but it just get black screen

### Current Behavior

black screen unresponsive

### Steps to Reproduce

1. Get updated CEF binary and build it.
2.Compile ths obs source code
3.it works fine without hardware accleration but i need updated browser with hardware accerlation
thanks in advance
...

**Comment by Fenrirthviti** [comment]
A few things:

No logs provided, which basically make this unactionable by itself. No information on what "get updated CEF binary" means here. No other information on how this was built. I'd recommend starting with our documentation, and use the #development channel on our Discord for more assistance before filing an unactionable issue report.

**Comment by draccurate** [comment]
> A few things:
> 
> No logs provided, which basically make this unactionable by itself. No information on what "get updated CEF binary" means here. No other information on how this was built. I'd recommend starting with our documentation, and use the #development channel on our Discord for more assistance before filing an unactionable issue report.

I followed the build instruction but changed the CEF binary with an updated version using chromium 111 instead of 103 that is currently used 
if you could guide my on how to get the log file I will be thankful
and also the discord server link

**Comment by WizardCM** [comment]
@draccurate Builds not built by us don't contain shared textures support that OBS requires, as it is a third party patch applied on top of functionality that was officially stripped out of CEF 103 and above. We were able to revert some changes in 103 so that we could update our shipping CEF, but it's currently impossible to do what you're attempting (hardware acceleration in CEF 104+)

**Comment by draccurate** [comment]
@WizardCM 

thanks for replying.
what if i needed an updated version of the browser even without hw acceleration as obs integrated builds are much smoother.
