### ISSUE TITLE
P416 color format is not compatible with HDR

### ISSUE THREAD

**Issue by arm64-v9a** [obsproject/obs-studio#8665]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.0-beta1

### OBS Studio Log URL

https://obsproject.com/logs/Fu8UvOyHJM0v9Gvf

### Expected Behavior

Normal output 4:4:4 16bit/10bit video

### Current Behavior

"OBS does not support 8bit output of Rec.2100"

### Steps to Reproduce

1. Settings > Adanced > Color Format > P416 (I would prefer to use P410, but OBS does not have this. As far as I know, NVENC will automatically convert P416 to P410)
2. Settings > Adanced > Color Space > Rec.2100
3. Add Display Capture Source
4. Start Recoding

**Comment by gxalpha** [comment]
P416 is only compatible with macOS ProRes encoders at this time. NVENC is probably silently falling back to NV12, causing this message. I do see room for improvement, but the expectation here should be a better error message and not NVENC working.

**Comment by derrod** [comment]
That's FFmpeg, not OBS. The encoder itself does not support P416 and the obs-ffmpeg encoder plugin does not use the conversion that the FFmpeg CLI would do, instead it just falls back to NV12.

**Comment by gxalpha** [comment]
Maybe in the future. However, that is not relevant to this issue as-is and would be a feature request.

For this issue to be considered fixed, PRs #8811, #8812, and similar not-yet-existing PRs for NVENC, AMF, and other encoders need to be merged to provider better error message and to avoid opaque conversions.
