### ISSUE TITLE
Linux Startup Crash  `Buffer size is not divisible by scale (2)`

### ISSUE THREAD

**Issue by TwoClocks** [obsproject/obs-studio#8674]
### Operating System Info

Other

### Other OS

Arch

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/lACfMBFLmosWat90

### Expected Behavior

OBS Should start

### Current Behavior

OBS Crashes on startup with the follow msg (from cmd line start):

```
wl_surface@29: error 2: Buffer size (3027x1404) is not divisible by scale (2)
The Wayland connection experienced a fatal error: Protocol error
The Wayland connection experienced a fatal error: Protocol error
``

### Steps to Reproduce

1. Run a tiliing window manager in linux on a high-res screen
2. Open OPS on a blank desktop, so that it will open full-screen
3. Watch the fireworks.
...


### Anything else we should know?

I run sway (i3-like)  on linux, which is a tiling window manager. If I try to open OBS on an empty desktop, so that as the first app it will take up the entire screen, I get the error logs msg.

If I open up a few other apps first, that take up space, obs launches fine. If I try to make OBS full screen, it crashes.

**Comment by kkartaltepe** [comment]
This doesnt look like our bug, if you can backtrace where the error is emitted and confirm that the code at fault here is not ours.

Basically all windowing is performed by Qt, so you would probably want to report errors with surface handling there.

**Comment by xux1217** [comment]
hi, I meet the same issue.

maybe we can refer this issue to resolve it:
- https://github.com/swaywm/sway/issues/7398#issuecomment-1403388390

looks like it must fix by every applications.

**Comment by kkartaltepe** [comment]
Closing as this is Qt's bug to fix.
