### ISSUE TITLE
Do not disturb mode enabled while OBS running but not recording

### ISSUE THREAD

**Issue by dshatz** [obsproject/obs-studio#8679]
### Operating System Info

Other

### Other OS

Opensuse Tumbleweed KDE Plasma 5.27.3

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/jxBGswa76BdxQVkA

### Expected Behavior

  1. Start OBS Studio
  2. No DND yet
  3. Add a pipewire screen capture source
  4. No DND yet
  5. Press start recording
  6. System DND enabled 

### Current Behavior

  1. Start OBS Studio
  2. No DND
  3. Add a pipewire screen capture source
  4. System DND enabled.

Can we wait with enabling DND until the recording has been started?

### Steps to Reproduce

See current&expected behavior

**Comment by gxalpha** [comment]
This sounds like a feature request, which we don't track using GitHub Issues (we use GitHub exclusively for bug reports).
Please put ideas and feature requests on [our ideas page](https://ideas.obsproject.com).

Thank you!

**Comment by tytan652** [comment]
If I understand this right.
The enablement of this DND feature is not related to OBS Studio itself, but on how Plasma manage screen-sharing.
So DND gets enables the moment that a screen-sharing is activated on Plasma.

**Comment by dshatz** [comment]
Thanks for sending me in the correct direction.
