### ISSUE TITLE
RIST streaming doesn't work in 29.0.2 installed from Ubuntu PPA

### ISSUE THREAD

**Issue by grimshins** [obsproject/obs-studio#8690]
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/pvIXbtn0IBriOaWo

### Expected Behavior

RIST streaming should work regardless of whether OBS is installed from the Ubuntu PPA or from Flathub

### Current Behavior

Attempts to stream RIST using OBS installed from Ubuntu PPA fail. Console message: `Couldn't open [server address], Protocol not found
Couldn't initialize muxer`
RIST streaming works fine with OBS Flatpak installed from Flathub

### Steps to Reproduce

1. Install OBS 29.0.2 from Ubuntu PPA
2. Attempt to start a RIST stream

**Comment by Fenrirthviti** [comment]
Please provide a full log instead of ignoring the field.

**Comment by Gol-D-Ace** [comment]
Hi
Ubuntu 22.04 Jammy.is not providing the necessary libraries for support in their package repo.

You will require at least Ubuntu 22.10 Kinetic for rist support.

**Comment by grimshins** [comment]
Thank you for the quick response. I figured it was an Ubuntu issue but did not see any guidance regarding minimum OS requirements for RIST support on the OBS website.
