### ISSUE TITLE
Obs Crash when adding / modify video capture devices

### ISSUE THREAD

**Issue by Felzow47** [obsproject/obs-studio#8691]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/O9c17u1jb7KhPdN5

### Expected Behavior

Adding / modify a video capture devices

### Current Behavior

Obs Freeze and get forced to close with taskmgr 

### Steps to Reproduce

1. Start OBS
2. Add or Modify a Video capture devices
3. Crash !
...

**Comment by Fenrirthviti** [comment]
Duplicate of https://github.com/obsproject/obs-studio/issues/7812

**Comment by Fenrirthviti** [comment]
This should be fixed in 29.1, which is currently in [beta](https://obsproject.com/forum/threads/obs-studio-29-1-beta-3.165547).
