### ISSUE TITLE
OBS stops streaming/recording silently

### ISSUE THREAD

**Issue by alxhu-dev** [obsproject/obs-studio#8693]
### Operating System Info

Windows 11

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://pastebin.com/HCGDUUL6

### Expected Behavior

- No freeze while recording/streaming - or - an notification that there was an error.
- A way to force stop recording (and not kill OBS via task manager).

### Current Behavior

While streaming and recording, it randomly stops. The timers in the bottom status bar continue, but the video preview freezes and the upload bitrate shows "0 kb/s". The UI is still responsive except exiting the application.

Clicking on "stop stream" or "stop recording" doesn't work. Exiting the application doesn't work. I need to close OBS via task manager.

This is the fifth time I've experienced the error.

### Steps to Reproduce

Honestly I don't know the circumstances how to reproduce this bug. It happens randomly.

1. Start streaming
2. Start recording
3. After a while, the preview freezes and the upload bitrate drops to 0 kb/s (although the indicator is still green).

It happened a month ago while playing "Sonic Frontiers" after streaming/recording for ~30 minutes.

It happened once a week ago and three times today while playing "NaissanceE". First today after streaming/recording for ~12 minutes, second after streaming/recording for 9 seconds, third after streaming/recording for 12 minutes.

In the past, there were no issues streaming/recording those games.

### Anything else we should know?

I was not able to upload the log file to obsproject.com because I restarted OBS several times and I'm unable to find the menu entry to upload an log file prior to the last two. The log file I've provided is from the first time this happened today while recording/streaming "NaissanceE".

I can provide additional log files from the other two times this happened today if they could be useful.

**Comment by prgmitchell** [comment]
@alxhu-dev this is probably Hardware-Accelerated GPU Scheduling causing your issue.

`To disable HAGS, go to:
Windows 11: ⚙️ Settings → System → Display → Graphics → Change default graphics settings

From there, set "Hardware-accelerated GPU scheduling" to OFF, then reboot your computer.`

**Comment by gxalpha** [comment]
Closing per the comment above. If you need further help, please make sure to visit the support sections on our [Discord server](https://discord.gg/obsproject) or [Forums](https://obsproject.com/forum) as mentioned.

Thank you!
