### ISSUE TITLE
(Intel) Media Source does not use hardware decoding AV1/VP9/H265/H264

### ISSUE THREAD

**Issue by phaitonican** [obsproject/obs-studio#8694]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.0-beta3

### OBS Studio Log URL

https://obsproject.com/logs/oCWl8vA5cV6AB4Jy

### Expected Behavior

Using a video with AV1/VP9/H265/H264 codec (and different types of file extensions tried too)
Media Source should use AV1/VP9/H265/H264 hardware decoding with my Intel A750 graphics card and have no CPU usage. Taskmanager should show some percentage on "Video Decode".

### Current Behavior

Media Source doesn't use hardware video decoding. CPU usage rises, neither AV1/VP9/H265/H264 hardware video decoding is used (tried all codecs respectively and some file Formats like .mp4 or .mkv)

### Steps to Reproduce

1. Add Media Source with AV1/VP9/H265/H264 codec
2. Check "Use video decode when..."
3. Play media and see CPU usage rise/no usage of video decoder in taskmanager

### Anything else we should know?

I am using the Intel Arc A750 graphics card.

**Comment by phaitonican** [comment]
BUMP

**Comment by RytoEX** [comment]
This _may_ be because we don't build FFmpeg with `--enable-libmfx` or `--enable-libvpl`, which means the only hwaccels that our FFmpeg build on Windows supports are: cuda, dxva2, d3d11va. I'm not sure if this is an oversight or intentional. We can attempt to adjust this for the next major/minor release after 29.1.

**Comment by phaitonican** [comment]
I don't see where FFMPEG is build in the build instructions in https://github.com/obsproject/obs-studio/wiki/build-instructions-for-windows (Option B: Custom Windows builds)
It just says I need a development package of FFMPEG.
I will have to build and install a custom version of FFMPEG on my Windows system? Or is it somewhere build while OBS is getting build basically?

**Comment by phaitonican** [comment]
Thanks a lot I will try to recompile the obs-deps with either `--enable-libmfx` or `--enable-libvpl`, and try to build OBS with those obs-deps instead once I have time and figure it out (since I am used to building the Linux version) and try to open a PR if it works. Thanks a lot.

**Comment by gxalpha** [comment]
As-is this is a feature request, which we don't track using GitHub Issues (we use GitHub exclusively for bug reports), so I will close this Issue.
Feel free to open a Pull Request if you figured out the changes needed to make this work.
