### ISSUE TITLE
hide obs from screen capture option not available in linux

### ISSUE THREAD

**Issue by coderam9898** [obsproject/obs-studio#8705]
### Operating System Info

Ubuntu 20.04

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/4zss8H5tio2RSS8d/https://obsproject.com/logs/aUipAQE6ZkckoDvh

### Expected Behavior

I wanted the hide obs window from screen capture fature in linux os. thats currently available in windows and mac only and not the linux version of obs.

### Current Behavior

The hide obs from screeb capture feature is not available

### Steps to Reproduce

1. went to settings and in general tab looked for hide obs from screen capture but currently there is no option like that.

### Anything else we should know?

plase bring all the features of obs to all the operating systems including linux.
![Screenshot from 2023-04-10 11-45-54](https://user-images.githubusercontent.com/71559062/230837038-80986b72-385a-4db2-90d0-494d5ce5a141.png)

**Comment by tytan652** [comment]
This a Windows-only feature, and there is no equivalent on Linux.

Note that it sounds like a feature request, which we don't track using GitHub Issues (we use GitHub exclusively for bug reports).
Please put ideas and feature requests on our [ideas page](https://ideas.obsproject.com/).
