### ISSUE TITLE
AV1 streaming to Youtube Crash instantly but AV1 recording works on M1 mac.

### ISSUE THREAD

**Issue by johannesschander** [obsproject/obs-studio#8711]
### Operating System Info

macOS 13

### OBS Studio Version

29.1.0-beta3

### OBS Studio Log URL

https://obsproject.com/logs/62w2H7tpDOzwkipv

### Expected Behavior

Stream output to YouTube over RTMPS with AV1 codec. 

### Current Behavior

OBS 29.0.3 crashes instantly when I press "start streaming". 

### Steps to Reproduce

1. Set stream service to Youtube RTMPS
2. Set output codec to AOM AV1
3. Click start streaming
...

### Anything else we should know?

I tried both connecting my account and using stream key
Doing local recording with AOM AV1 works on M1 Mini

**Comment by derrod** [comment]
Known issue, fixed by 3de564258d6b9b6ba2e90c6fe7ffb78aa51c169d
Next beta will have the fix.
