### ISSUE TITLE
[BUG] - Chroma sub-sampling happens regardless of colour format when recording with H.265.

### ISSUE THREAD

**Issue by Knewest** [obsproject/obs-studio#8719]
### Operating System Info:

Windows 10

### OBS Studio Version:

29.1.0-beta3

### OBS Studio Log URL:

https://obsproject.com/logs/btVD3OvPCQTey1jf

### Expected Behavior:

When selecting the colour format 'I444' using 'NVENC NVIDIA HEVC' codec, it should provide accurate colours with zero chroma sub-sampling.

### Current Behavior:

For whatever reason, _all_ colour formats selected will chroma sub-sample if you use the aforementioned H.265 codec.<br>This does not happen when using the H.264 codecs.
<br>
### Steps to Reproduce:
<br>
<b><ul>1. Copy these for reference (VBR):</b></ul><a href="https://cdn.discordapp.com/attachments/374636015396192257/1095649027372101642/bYTIu8MbM4.webp"><img src="https://cdn.discordapp.com/attachments/374636015396192257/1095649027372101642/bYTIu8MbM4.webp" style="width:928px;height:1040px;"></a><br><br><a href="https://cdn.discordapp.com/attachments/374636015396192257/1095649064135184474/XxgKXPxuly.webp"><img src="https://cdn.discordapp.com/attachments/374636015396192257/1095649064135184474/XxgKXPxuly.webp" style="width:935px;height:1036px;"></a><br><br><br>
<b><ul>2. Use this reference image (or one you prefer):</b></ul><a href="https://cdn.discordapp.com/attachments/374636015396192257/1095648561011626005/0OVqe2ejIQ.webp"><img src="https://cdn.discordapp.com/attachments/374636015396192257/1095648561011626005/0OVqe2ejIQ.webp" style="width:2560px;height:1080px;"></a><br><br><br>
<b><ul>3. Look at the green online status and Roblox logo on the bottom left for comparisons:</b></ul>
<a href="https://cdn.discordapp.com/attachments/374636015396192257/1095644703527014481/ydQr3iabvO.webp"><img src="https://cdn.discordapp.com/attachments/374636015396192257/1095644703527014481/ydQr3iabvO.webp" style="width:964px;height:477px;"></a><br>
 <a href="https://cdn.discordapp.com/attachments/374636015396192257/1095644469640036352/CniwcbR1nz.webp"><img src="https://cdn.discordapp.com/attachments/374636015396192257/1095644469640036352/CniwcbR1nz.webp" style="width:964px;height:477px;"></a>
 <sub>^^Left is the recorded image and right is the original image.^^</sub><br><br><br>

### Anything else we should know?:

Discussion of my findings can be found in the #windows-support channel in the OBS Community Discord server here: https://canary.discord.com/channels/348973006581923840/374636015396192257/1095639852931878932

It was verified to be an issue by two other individuals and I discovered this problem around October of 2022 (from recollection).<br>I just switched to H.264 out of frustration at the time and brushed it off as something that would be addressed (which obviously it didn't since I am here).

**Comment by derrod** [comment]
OBS is set to an 8-bit format but you've set nvenc to main10, I'm not sure if nvenc supports 10-bit 444 so try main first.

**Comment by flaeri** [comment]
We have continued to look at the issue in the support channels, as I could not reproduce the issue. In the end it seems to be something with OPs decoder or screenshot tool. I have tested their video plays back correctly in MPV and VLC. See attached filed (must be unscaled (or fullscreen 1080p)

Attached, users encoded video:
[2023-04-12_19-25-26.zip](https://github.com/obsproject/obs-studio/files/11210966/2023-04-12_19-25-26.zip)

**Comment by Knewest** [comment]
It seems that at some point, my Pot Player settings were reset, giving me a false impression that the encoder was faulty, this was more reaffirmed when I accidently recorded the recording and not the original screenshot and extracted the screenshot using Adobe Premiere. 
I apologise for possibly wasting everyone's time.
