### ISSUE TITLE
Ubuntu 23.04 Not able to run OBS or compile from source

### ISSUE THREAD

**Issue by BriegerCA** [obsproject/obs-studio#8720]
### Operating System Info

Other

### Other OS

Ubuntu 23.04

### OBS Studio Version

Git

### OBS Studio Log URL

Can't do

### Expected Behavior

I expect it to either run or compile

### Current Behavior

**Standard OBS error after Ubuntu upgrade**
info: [Downstream Keyer] loaded version 0.2.5
Widget: Must construct a QApplication before a QWidget
Aborted (core dumped)

**When compiling from Source**
The following packages have unmet dependencies:
libqt6svg6-dev : Depends: libqt6svg6 (= 6.2.4-1ubuntu1) but 6.4.2-1ubuntu1 is to be installed
Depends: libqt6svgwidgets6 (= 6.2.4-1ubuntu1) but 6.4.2-1ubuntu1 is to be installed
E: Unable to correct problems, you have held broken packages.
+ ERROR during build step: install_qt6-deps

### Steps to Reproduce

The Steps should be clear. Just run Ubuntu 23.04 and OBS 29.02 crashes as per above.

Source compile not possible, there is no 6.4.2 Version of libqt6svg6-dev to be found.
No idea if that is still needed or nor or what I need to change where

**Comment by kkartaltepe** [comment]
Provide a backtrace, this looks like you have installed a broken plugin that is crashing.

**Comment by BriegerCA** [comment]
I removed any number of Plug-Ins. They all fail with the same error message.
That's why I consider a compile from Source as it could be related to QT.

**Comment by BriegerCA** [comment]
Update,
I removed all the Plugins and then OBS works. Moved them back one at a time to find out which failed. I provided MY list on the OBS web site. The compile works fine, if the libqt6svg6-dev  is removed from 01_install_dependencies.sh

**Comment by kkartaltepe** [comment]
Closing as it was a bug in third party plugins. There was some discussion of package names changing in ubuntu 23.04 as its not officially released. Once it does release the tooling will be updated with name it sounded like.
