### ISSUE TITLE
OBS Failed to open NVENC Codec: Function not implemented

### ISSUE THREAD

**Issue by aaaaadrien** [obsproject/obs-studio#8723]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/uhU3LpBJ7fPhO0uB

### Expected Behavior

NVENC Working

### Current Behavior

Since upgraded from OBS 27.x to 29.x NVENC not available.

22:45:40.550: error:   The minimum required Nvidia driver for nvenc is 471.41 or newer

### Steps to Reproduce

1.
2.
3.
...

### Anything else we should know?

Why ???
Please add a compatibility option for old graphics !
It worked a charm before with multiples overlays.

**Comment by Mister36MN** [comment]
The minimum required nvidia driver message is self-explanatory. It will not be changed as dependencies and software are updated.
