### ISSUE TITLE
New OBS versions is just... broken. Audio and push to talk problems, sound and picture synchronization and even design.

### ISSUE THREAD

**Issue by BK-2-0-1** [obsproject/obs-studio#8727]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.2

### OBS Studio Version (Other)

27 and 28

### OBS Studio Log URL

don't have it cos i uninstall it :( and i'm not sure if logs show smthng

### Expected Behavior

Normal work, no problems with synchronization and sound as it was before new (27-29) versions (everything was perfect).

### Current Behavior

Lets start with audio. First thing i noticed strange delays (or i will even call it pre-delays). What do I mean - i was using push to talk since early obs versions cos for me it's easiest way to speak clear and cut off any noises (breath/clicks/etc), but in new versions i face huge problem. I take a breath, press button, speak, done. later during editing I notice that my audio is activated a second early, i hear my breath and after i even hear how i press my PTT button. this does not always happen, but often, and instead of calm editing, I have to check each of my phrases, and there can be 100 of them in one video. it's just a real nightmare.

Second thing - when you press buttons like alt, shift, ctrl - your audio(voice) just cuts. In older versions everything worked perfect and never bothered me at all. Now i should rebind my keys (because they are used in almost all games and applications) or don't press it at all, which is absolutely terrible. i had to stop using ptt and switch to voice on/off activation, and it's terribly inconvenient.

Third thing - audio quality, when i record smthng in obs, no matter what, voice from microphone, just music playing in browser - final quality is worse than the original, it's not very noticeable, but it's a fact. my audio bitrate is the maximum. in other similar programs there are no such problems, the sound after recording is the same as it was.

Next thing i faced recently - sound and picture out of sync, I just record the game as always and everything was fine before, but now I see that the picture and sound that comes from the game do not match. Rarely happens, but still unpleasant. Never had this problem in older versions.

And last thing - design. I know there is themes but... huge buttons, font, nothing fits and nothing can be configured (only change the theme to another one, but it also doesn’t look good). I don't know who came up with this design and who it was made for (perhaps if your monitor is 4k resolution and 48 inches it will look fine) but on regular monitor with full hd resolution it looks awful. it's scary to imagine how it looks on a laptop.

I understand that the OBS is free, it's amazing(best) app for recording/streaming, I am very grateful to the developers, and I'm all so terrible how I even dare to complain - but after all, all this did not exist before, and appeared only in the new versions. I did not change anything, the settings are the same, everything I did was - update. But why do we need new versions if they are much worse and more unstable than the old ones? Now, unfortunately, I have to use the old version, because in the new one, apart from bugs and terrible design, nothing new has appeared. I really hope that at least in version 30 or later all problems will disappear, it will be possible to customize the design and you can just enjoy stable work.

p.s. I didn’t mean to offend anyone, if I did - I apologize in advance, I just want to help my favorite application.

### Steps to Reproduce

1. I just recorded the video as before and then found problems at the editing stage.

**Comment by Fenrirthviti** [comment]
This, unfortunately, is several completely unrelated things being reported. Without log files, none of this is going to be actionable, and most of it sounds like things that could be fixed through our support channels. We are currently reserving GitHub issues for verified and reproducible bug reports, and in general all issue reports should be scoped to a single issue.

I recommend stopping by our support channels on our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/), for further assistance. None of these sound like global issues with OBS itself, but more likely something with your specific environment/setup, a misconfiguration, or at worst, some kind of hardware issue at play. Our support community should be able to help work through things, though I do recommend focusing on one issue at a time, rather than trying to fix everything at once.

Thanks for your understanding.
