### ISSUE TITLE
What to do with the gray HDR

### ISSUE THREAD

**Issue by KangChengli** [obsproject/obs-studio#8728]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.0-beta3

### OBS Studio Log URL

https://obsproject.com/logs/1XCGz33NJFB7jMzB

### Expected Behavior

I am an HDR 4k monitor, and the images I have been recording with OBS are always gray. I don't know how to handle it

### Current Behavior

I am an HDR 4k monitor, and the images I have been recording with OBS are always gray. I don't know how to handle it

### Steps to Reproduce

1.It's a display acquisition
2.
3.
...

### Anything else we should know?

I am Chinese and my English is not very good. I don't know how to describe it.If possible, reply in Chinese next time

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by KangChengli** [comment]
我尝试了，很多的方法，它一直是灰蒙蒙的，无法兼容HDR 我看了很多中国的论坛，都没有解决方法



发自我的iPhone


------------------ Original ------------------
From: Joel Bethke ***@***.***&gt;
Date: Thu,Apr 13,2023 9:24 AM
To: obsproject/obs-studio ***@***.***&gt;
Cc: KangChengli ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [obsproject/obs-studio] What to do with the gray HDR (Issue#8728)





 
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our forums or Discord for assistance.
 
Thank you!

**Comment by xiaomaofeng** [comment]
can you retry with the lastest version of obs?, and please confirm the display and windows are already opened the hdr
