### ISSUE TITLE
obs-script: TypeError: in method 'signal_handler_connect_ref', argument 3 of type 'signal_callback_t'

### ISSUE THREAD

**Issue by 1170300710** [obsproject/obs-studio#8732]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.0-beta3

### OBS Studio Log URL

None

### Expected Behavior

bind a callback successful

### Current Behavior

raise an error: `TypeError: in method 'signal_handler_connect_ref', argument 3 of type 'signal_callback_t'`

### Steps to Reproduce

I am try to use obspython.py in my python project.
I am confused that how to use the function in obspython.py like:
```
def signal_handler_connect_ref(handler: "signal_handler_t *", signal: "char const *", callback: "signal_callback_t", data: "void *"):
    do_something....
```
I use these code:
```
signals = obs_output_get_signal_handler(self.m_output_repley)
signal_handler_connect_ref(
    signals,
    "saved",
    lambda a,b:print(123),
    None
)
```
it raise an error: "TypeError: in method 'signal_handler_connect_ref', argument 3 of type 'signal_callback_t'"

and I try these code too, but get same error:
```
def replay_saved_callback(param, data):
    print("asd")
signals = obs_output_get_signal_handler(self.m_output_repley)
signal_handler_connect_ref(
    signals,
    "saved",
    replay_saved_callback,
    None
)
```

### Anything else we should know?

the python version is 3.10

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
