### ISSUE TITLE
OBS 27.2.0 crashes when testing stream

### ISSUE THREAD

**Issue by rblst** [obsproject/obs-studio#8733]
### Operating System Info

Other

### Other OS

Raspberry Pi OS 64-bit (Debian Linux 11) 

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.2.0

### OBS Studio Log URL

https://obsproject.com/logs/57ptvBKfzqTOaHSO

### Expected Behavior

Auto-Configuration Wizard completes successfully.

### Current Behavior

OBS crashes when testing RTMP stream in Auto-Configuration Wizard.

### Steps to Reproduce

1. Go to _Tools_ -> _Auto-Configuration Wizard_ in the menu.
2. Click _Next_.
3. Click _Next_.
4.  In the _Service_ field, select: _YouTube - RTMPS_
5. In the _Stream Key_ field, enter your streaming key.
6. Click _Next_.
7. In the _Stream warning_ pop-up window, click _Yes_.

### Anything else we should know?

Here is the end of the output:

```
info: [rtmp stream: 'test_stream'] Connecting to RTMP URL rtmps://a.rtmps.youtube.com:443/live2...
/usr/bin/obs: line 2: 4339 Segmentation fault LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libGL.so MESA_GL_VERSION_OVERRIDE=3.3 /usr/bin/obs-exec "$@"
```

**Comment by gxalpha** [comment]
OBS 27.2 is unsupported. Additionally, the Raspberry Pi is not known to be suitable to run OBS.
