### ISSUE TITLE
Encoder list empty in Custom output

### ISSUE THREAD

**Issue by lemon-sh** [obsproject/obs-studio#8734]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/yohEMqBfsHRQGlcz

### Expected Behavior

I expected to see all the available encoders upon selecting the `matroska` container format.

### Current Behavior

The "Video encoder" and "Audio encoder" dropdowns are empty, I can't select any encoder.

![image](https://user-images.githubusercontent.com/26277478/231817186-8a3188bb-b414-4e48-aea4-0b2cb794dee3.png)

### Steps to Reproduce

1. Install `obs-studio` on Arch Linux
2. Go to output settings
3. Select output mode to "Advanced"
4. In Recording, set Type to "Custom Output (FFmpeg)"
5. Set the "Container Format" to `matroska`
6. Try to select a video or an audio encoder

### Anything else we should know?

1. When I set the "Container format" to `matroska` and then click "OK" and then reopen settings again, it will reset back to "Default Format".

2. When I start OBS in a terminal, upon opening the settings, the following line is spammed in the terminal:
   ```
   QVariant: Provided metatype for '{anonymous}::FormatDesc' does not support destruction and copy construction
   ```
   It sounds like it might be related to the problem.

3. I've actually first discovered this issue in [obs-studio-git](https://aur.archlinux.org/packages/obs-studio-git), but then installed the regular package ([obs-studio](https://archlinux.org/packages/community/x86_64/obs-studio/)) and it was present there as well. This seems to have happened after a system update.

**Comment by PolarianDev** [comment]
@lemon-sh This might also be a packaging issue, you will also want to submit this as an issue on the arch bug tracker :)

**Comment by RytoEX** [comment]
We don't maintain any packages on Arch ourselves. If this occurs in our Flatpak builds, then feel free to report as such and we can reopen this.
