### ISSUE TITLE
AV1 + Dynamic bitrate not working

### ISSUE THREAD

**Issue by johannesschander** [obsproject/obs-studio#8740]
### Operating System Info

macOS 13

### OBS Studio Version

29.1.0-beta4

### OBS Studio Log URL

https://obsproject.com/logs/8LwW8sTkU5zj7gjB

### Expected Behavior

When my target bitrate is 8000Kbps and I alter my network bandwith to 2000Kbps, dymanic bitrate on should make the encoder lower the bitrate to avoid frame drops.

### Current Behavior

When I artificially limit the bandwith of my connection the encoder drops right down to ≈ 168Kbps and gives me 99% frames droped. 
When I bring the bandwith back to 100/100Mbit the encoder stays at ≈ 168Kbps and wont go back up. 

### Steps to Reproduce

1. Select AOM AV1 as encoder Preset 8 8000Kbps
2. Destination Youtube RTMPS
3. Lower the bandwith of internet connection to 2000Kbps
...

### Anything else we should know?

System: M1 Mac mini

**Comment by johannesschander** [comment]
> afaict aom doesn't support bitrate live reconfiguration, nor does svt-av1, neither amf av1. Dynamic bitrate should be disabled for these codecs. We'll fix that in next beta.

Okey, so AV1 won't support any form of rate control based on internet connection? Now that AV1 works on the M1 mac at 9W total power draw it would be a dream come true for IRL streamers on Twitch. Quality is AMAZING and totally watchable at 1000Kbps but without rate control it's not as great as it could be.

**Comment by pkviet** [comment]
see Pull Request: https://github.com/obsproject/obs-studio/pull/8741
