### ISSUE TITLE
Stream abruptly stops (bitrate is 0 kb/s) and OBS crashes (Hardware-Accelerated GPU Scheduling is enabled)

### ISSUE THREAD

**Issue by riazXrazor** [obsproject/obs-studio#8746]
### Operating System Info

Windows 11

### OBS Studio Version

29.0.2

### OBS Studio Log URL

n/a

### OBS Studio Crash Log URL

https://obsproject.com/logs/eIIKdcUDLpEjZkjx

### Expected Behavior

Streaming show work without any issue and as long as  don't stop the stream.

### Current Behavior

After sometime stream abruptly stops (bitrate is 0 kb/s) and when i press stop stream button OBS crashes

### Steps to Reproduce

1. Enable Hardware-Accelerated GPU Scheduling
2. Start streaming 
3. After sometime stream abruptly stops (bitrate is 0 kb/s) and when i press stop stream button OBS crashes

### Anything else we should know?

disabling HAGS (Hardware-Accelerated GPU Scheduling) fixes the issue , but i'm using RTX 4070 now and DLSS 3 Frame Generation doesn't with HAGS  disabled.

**Comment by riazXrazor** [comment]
Log file:
[2023-04-14 21-55-17.txt](https://github.com/obsproject/obs-studio/files/11236771/2023-04-14.21-55-17.txt)

**Comment by Fenrirthviti** [comment]
Please also provide the crash log.

**Comment by notr1ch** [comment]
HAGS is known to break many things. There's nothing we can do on our end, fixes to HAGS related issues need to come from your GPU vendor and Microsoft.

**Comment by riazXrazor** [comment]
is there no workaround for this ? 
DLSS 3 Frame Generation is an important feature for 40xx cards :'(

**Comment by Fenrirthviti** [comment]
There might be, but to be more clear, the issue is entirely within the operating system and driver. As far as we know, there isn't anything we can do. At best, we may be able to recover a bit more gracefully where the encoder just dies and doesn't take down OBS as well, but it's unclear if even that is possible at the moment.

**Comment by 777Awesomesun** [comment]
OBS is crashing after 1-2 minutes for me. Where do i turn this graphic setting off? I have GTX 3060 Ti. I'm thinking it's the gfx card

**Comment by cheatpeda** [comment]
Hi, I would like to comment regarding a recent problem I am experiencing with OBS Studio in 2025.

Currently, during streaming or preview sessions, OBS suddenly freezes and the bitrate drops to 0 kbps. This happens after some time (for example, after 1.5 to 2.5 hours). The application itself becomes unresponsive during these events. I have not found any clear information or discussion about this specific behavior, even though some streamers and content creators seem to be facing similar issues.

I would appreciate if this could be investigated or if anyone could provide guidance on this matter. Thank you for your work on OBS!

**Comment by Fenrirthviti** [comment]
> I would appreciate if this could be investigated or if anyone could provide guidance on this matter. Thank you for your work on OBS!

We don't provide support over GitHub Issues, and this issue has been closed for nearly 2 years. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
