### ISSUE TITLE
Replay Buffer rarely working properly

### ISSUE THREAD

**Issue by Johnlongears** [obsproject/obs-studio#8753]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/5DEMMpW2xm6DlxYV

### Expected Behavior

I expected my Replay Buffer to work, for it to save the last 60 seconds whenever I click on my Save Replay button on my keyboard, as it has worked for months.

### Current Behavior

Whenever I click on the Save Replay button, 4/5 times it just does absolutely nothing, then whenever I click on Stop Replay Buffer in the application to try to fix it, it says "Stopping Replay Buffer..." 
![image](https://user-images.githubusercontent.com/77125467/232247968-5a07b15d-7914-42ca-8d41-fe4fcddfec4e.png) indefinitely until I force quit the program using task manager. There are cases where my replay buffer works perfectly fine, but it is not very common.

### Steps to Reproduce

1. Start Replay Buffer
2. Disable Preview
3. Hide OBS using system tray
4. Click Save Replay
...

### Anything else we should know?

I record in 180 fps, and my Replay Buffer is set to save the last 60 seconds.

**Comment by gxalpha** [comment]
Please check if this happens when recording in 60 FPS as well.

**Comment by Johnlongears** [comment]
> Please check if this happens when recording in 60 FPS as well.

This still happens when I doing 60 FPS. The only way for me to prevent this issue is to repeatedly restart OBS and test it to see if it works, then after a few restarts it usually works, then from then until I close the program again it works perfectly.

**Comment by gxalpha** [comment]
Please provide a log file of that (on OBS 29.1.2).
Once it's stuck on stopping, please also create a memory dump of OBS, as described here: https://obsproject.com/forum/resources/how-to-create-a-dmp-file-for-debugging.598
Make sure not to put that here, instead please send it to the community manager Fenrir (`len`) on our [Discord server](https://obsproject.com/discord) with a link to this issue.
