### ISSUE TITLE
How to report a security vulnerability?

### ISSUE THREAD

**Issue by security-companion** [obsproject/obs-studio#8756]
### Operating System Info

Windows 10

### OBS Studio Version

29.0.2

### OBS Studio Log URL

Does not Appliy

### Expected Behavior

Hi,
I found a possible security vulnerability in OBS Studio and would like to know how I can report it privatly.
My suggestion is to create a SECURITY.md so that people know how to report vulnerabilities.
Github now also supports private vulnerability reporting, perhaps that's also something you want to activate.
Looking forward to your answer.
Greetings
security-companion

### Current Behavior

Could not find instructions about how to report a security-vulnerability.

### Steps to Reproduce

1.
2.
3.
...

**Comment by tytan652** [comment]
Duplicate of #6681

**Comment by derrod** [comment]
See https://github.com/obsproject/obs-studio/issues/6681#issuecomment-1172949864

We have not enabled that github feature since it's pretty new and we just haven't looked into it. We might consider using it going forward.

**Comment by Fenrirthviti** [comment]
Just to note here as well, please email us at security@obsproject.com and we will review.
