### ISSUE TITLE
Video Capture Device Issues after v28.0 (Elgato HD60 S+)

### ISSUE THREAD

**Issue by trus0und** [obsproject/obs-studio#8771]
### Operating System Info

macOS 13

### OBS Studio Version

Other

### OBS Studio Version (Other)

28.1.0

### OBS Studio Log URL

https://obsproject.com/logs/O8a0O1LAT1tKu3OG

### Expected Behavior

When using a capture card such as the Elgato HD60S+ on macOS with OBS versions beyond 28.0, the capture should look normal.

### Current Behavior

Certain parts of the image look to be garbled. This is not present in other applications on the same system. Here is a comparison between OBS 29.0.2 and Streamlabs Desktop 1.12.3:

OBS 29.0.2: https://pasteboard.co/VyAhBvQxMVq5.png
SL Desktop 1.12.3: https://pasteboard.co/nC1ezVB13SiX.png

Best places to look in the image are the ZR button or how Pouch or Items seems garbled. This persists across multiple devices such as Nintendo Switch or PS5, but is not apparent in SL Desktop, Quicktime, or Elgato Game Capture.

### Steps to Reproduce

1. Connect an Elgato HD60S+ to a Mac (Only tested on Intel so far).
2. Add the HD60S+ as a Video Capture Device on OBS v28.1 or above.
3. See oddities in image.

### Anything else we should know?

I have not yet testing on M1. Will add my results as I have them.

**Comment by trus0und** [comment]
Does not occur on Apple Silicon in 29.0.2.

**Comment by Fenrirthviti** [comment]
Probably a dupe of https://github.com/obsproject/obs-studio/issues/7742

**Comment by trus0und** [comment]
Yes, sorry I missed that. It's exactly the issue I am having in #7742

**Comment by trus0und** [comment]
Closed as duplicate.

**Comment by Fenrirthviti** [comment]
Duplicate of https://github.com/obsproject/obs-studio/issues/7742
