### ISSUE TITLE
Virtual camera on Linux with a gphoto2 USB camera

### ISSUE THREAD

**Issue by bdelphin** [obsproject/obs-studio#8779]
### Operating System Info

Other

### Other OS

Arch Linux - kernel 6.2.11-arch1-1

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/jfxjOfrYRyU51Xeo

### Expected Behavior

OBS Virtual camera shouldn't start on the same V4L2 video device (e.g. `/dev/video8`) as my Canon USB camera.

A solution could be to allow users to select the V4L2 video device used by OBS virtual camera, as this was the case with [this obsolete plugin](https://github.com/CatxFish/obs-v4l2sink). Maybe I can edit some config file to force the V4L2 device used by OBS ?

### Current Behavior

When I try to start the OBS Virtual Camera, my Canon USB Camera source starts to flicker :

Virtual camera OFF :
![capture_20-04-2023_15:01:16](https://user-images.githubusercontent.com/24278157/233375376-b4db8f0d-413b-4349-ba79-7f9ee9aff5d2.png)

Virtual camera ON : 
![capture_20-04-2023_15:01:11](https://user-images.githubusercontent.com/24278157/233375473-1ab4d7e7-2517-4f0d-aaee-c2d5b236d48e.png)

I'm using a Canon EOS 500D connected to my computer via a USB cable, with gphoto2 to create a V4L2 device (command used to start the video from my camera : `gphoto2 --stdout --capture-movie | ffmpeg -i - -vcodec rawvideo -pix_fmt yuv420p -hide_banner -loglevel error -nostats -threads 0 -f v4l2 /dev/video8`).

I have tried to change the V4L2 device used by my camera (e.g. from `/dev/video7` to `/dev/video8`), but OBS seems to select the same video device as my camera, no matter what I try ...

Since OBS 29.x, the [obs-v4l2sink plugin](https://github.com/CatxFish/obs-v4l2sink) isn't working anymore, so I've to use the OBS virtual camera. 

### Steps to Reproduce

1. Start a V4L2 gphoto2 stream, from a USB camera (with the command above) 
2. Add a new V4L2 source in OBS, and select the camera stream
3. Start the OBS virtual camera

**Comment by fzwoch** [comment]
OBS uses the first loopback device it finds. (if it finds one it will not create a device on its own)
Create two of them manually. E.g. video6 and video8.
OBS will use video6. You can then use video8 for your gphoto cli.

**Comment by bdelphin** [comment]
Thanks @fzwoch :pray: 
Yesterday, no matter what I tried OBS didn't want to use another V4L2 device (even after changing gphoto2 to `/dev/video8` and leaving `/dev/video7` unused, for OBS).

Today, everything's working properly : `/dev/video8` is used by gphoto, and OBS select the first loopback device available : `/dev/video7`. As usual, I should have tried turning it off and on again.
