### ISSUE TITLE
An encoder error while recording

### ISSUE THREAD

**Issue by hakihaki95** [obsproject/obs-studio#8780]
### Operating System Info

macOS 13

### OBS Studio Version

29.1.0-beta4

### OBS Studio Log URL

https://obsproject.com/logs/NxbxXtuYtyvBstvg

### Expected Behavior

If I click "Start Recording", it will work

### Current Behavior

If I click "Start Recording", as soon as "An encoder error occurred while recording." message comes.
But, I can "Start Streaming"

### Steps to Reproduce

1. Click "Start Recording" with "simple mode" and "Advanced standard mode"
2. The error message comes with "An encoder error occurred while recording."
3. Click "Start Recording" with "Advanced Custom Output(FFmpeg)"
4. It is working.

**Comment by gxalpha** [comment]
Please try this with a downloaded (official) build of OBS, ideally [OBS 29.1.0-rc1](https://github.com/obsproject/obs-studio/releases/tag/29.1.0-rc1).
