### ISSUE TITLE
Random black screening when using game capture of xbox pc app

### ISSUE THREAD

**Issue by Tbris22** [obsproject/obs-studio#8784]
### Operating System Info

Windows 11

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/tStfFSO6vzWTw8q8 

### Expected Behavior

I just want to game capture so I can stream from my xbox to twitch with obs overlay.

### Current Behavior

It worked perfectly once last week. Now, it takes forever to actually show game capture. When it does finally appear, it will work for various amounts of time before black screening. I've tried changing graphic preferences, checking to make sure I have the correct version, trying all game capture settings, deleting and reinstalling, running as administrator, and tried to troubleshoot/run compatibility and it pops up with (Failed to find locale/en-US.ini) and (Failed to load locale) right after. I just started using it last week and don't know why it stopped working.

### Steps to Reproduce

1. Open Xbox PC App and OBS Studio
2. Start Remote Play from xbox to laptop
3.  Issue occurs (immediate black screen that I have to refresh and open/close apps to finally show up and when it does work, black screens at random time after starting stream. usually about 5-10 minutes in)

### Anything else we should know?

Laptop specs
Processor	11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz   2.42 GHz
Installed RAM	16.0 GB (15.7 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	Touch support with 10 touch points
Graphics    iRISxe Intel
 
The only thing I've added/changed from when it worked to now is a snowball ice mic. Everything else is the same.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
