### ISSUE TITLE
Flag OBS_PROPERTIES_DEFER_UPDATE does not affect sources defined by Lua scripts

### ISSUE THREAD

**Issue by PhantomShift** [obsproject/obs-studio#8813]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

Other

### OBS Studio Version (Other)

OBS 29.0.2-tytan652-2

### OBS Studio Log URL

https://obsproject.com/logs/e9hNtYigS3baaadV

### Expected Behavior

With `OBS_PROPERTIES_DEFER_UPDATE` flag set, modification callbacks should be called after the user has clicked save.

### Current Behavior

Despite `OBS_PROPERTIES_DEFER_UPDATE` flag being set, modification callbacks are called every single time a property updates.

### Steps to Reproduce

1. Add the following script to OBS
```lua
local obs = obslua

local testSrcDef = {
    id = "testDeferUpdateSource",
    type = obs.OBS_SOURCE_TYPE_OUTPUT,
    output_flags = obs.OBS_SOURCE_DO_NOT_DUPLICATE,
}

function testSrcDef.create(settings, source)
    return {}
end
function testSrcDef.destroy(data)
    return
end

function testSrcDef.get_name()
    return "Defer Update Test"
end

local function textUpdateCallback(props, prop, settings)
    local newText = obs.obs_data_get_string(settings, "text")
    print(newText)
end

function testSrcDef.get_properties(data)
    local props = obs.obs_properties_create()

    local textProp = obs.obs_properties_add_text(props, "text", "Text", obs.OBS_TEXT_DEFAULT)
    obs.obs_property_set_modified_callback(textProp, textUpdateCallback)

    obs.obs_properties_set_flags(props, obs.OBS_PROPERTIES_DEFER_UPDATE)

    return props
end

obs.obs_register_source(testSrcDef)

```
2. Create a new source defined by the script above (Defer Update Test)
3. Monitor script logs
4. Edit the text field of the source
5. Observe the changes being applied immediately instead of on save

### Anything else we should know?

I have not confirmed it myself, but this issue may be related to [this](https://github.com/obsproject/obs-studio/issues/5139) one since they seem a bit similar, though they differ in nature since the issue here is the flag having no effect whereas the issue there was the flag breaking expected functionality.

I have tried using luajit's ffi to set the flag instead of using the obslua object provided, however this just seems to result in a segfault when executing the command. This however could very easily be me not handling it properly.

Although this issue isn't a big deal when it comes to binary choices (bools) or lists, it is rather annoying when working with sliders or editable text fields since the modification callbacks will often be given lots of incomplete data, or simply data that won't end up being used.

**Comment by gxalpha** [comment]
> With OBS_PROPERTIES_DEFER_UPDATE flag set, modification callbacks should be called after the user has clicked save.

Modified callbacks are unaffected by the `OBS_PROPERTIES_DEFER_UPDATE` flag, which is intentional. Only the `.update` callback of the source itself gets deferred by the flag.

**Comment by PhantomShift** [comment]
I see, really appreciate the clarification.
