### ISSUE TITLE
Interface Editing Stopped Working on Linux

### ISSUE THREAD

**Issue by Ryu945** [obsproject/obs-studio#8816]
### Operating System Info

Other

### Other OS

Nobara 37 (A modified Gnome Fedora 37)

### OBS Studio Version

Other

### OBS Studio Version (Other)

OBS 29.1.0

### OBS Studio Log URL

None

### Expected Behavior

1)  When I log into Youtube or Twitch, I expect for the chat widget to appear

2)  To be able to add browser sources as a widget.

3)  To be able to snap the different boxes likes Scences and Controls to different locations in OBS.

### Current Behavior

1)  Twitch and Youtube Chat no longer get added when you long into your account.

2)  It is not possible to add a browser source as a widget anymore.

3)  It is not possible to snap a widget to a different location on the OBS interface anymore.  If you Snap it out of its existing location, it is impossible to place it back in unless you reset the entire interface.

### Steps to Reproduce

1.  Install OBS via RPM using the package manager  ( Flatpak version also showed it has this same chat bug problem)
2.  Log into Youtube/Twitch ( See no chat box pops up in interface)
3.  Drag boxes in the interface around.  ( See you can't move them around)
4.  See there is no option to add a broswer source as an interface widget.
...

### Anything else we should know?

Nobara Is a copy of Gnome Fedora except the following changes were made.  https://nobaraproject.org/

**Comment by derrod** [comment]
You didn't provide a log but this sounds like the known limitation of browser docks not being supported on Wayland.

**Comment by tytan652** [comment]
I also add that everything related to Nobara OBS package since it's a really modified version of OBS, you must report to Nobara first.

**Comment by Ryu945** [comment]
> You didn't provide a log but this sounds like the known limitation of browser docks not being supported on Wayland.

Is that also why the inteface itself can't be customized for the menus that are there?

**Comment by Ryu945** [comment]
> I also add that everything related to Nobara OBS package since it's a really modified version of OBS, you must report to Nobara first.

Isn't the OBS package on Nobara just the standard Fedora RPM package.  Remember that this problem exist on Flatpak as well.

**Comment by tytan652** [comment]
> Isn't the OBS package on Nobara just the standard Fedora RPM package.

No, it's a package made for Nobara with a modifed version of OBS code.

**Comment by mihawk90** [comment]
> Is there any plans in the near future for Wayland support?

It is always "planned", but not currently possible. You can track the issue here:
obsproject/obs-browser#279
