### ISSUE TITLE
ppa installation for Ubuntu 23.04 (lunar) - missing release file

### ISSUE THREAD

**Issue by encore64** [obsproject/obs-studio#8817]
### Operating System Info

Other

### Other OS

Ubuntu 23.04

### OBS Studio Version

29.0.2

### OBS Studio Log URL

...

### Expected Behavior

Using the official instructions to install via PPA from https://obsproject.com/download#linux
```
sudo add-apt-repository ppa:obsproject/obs-studio
sudo apt update
sudo apt install ffmpeg obs-studio

```
should run fine.

### Current Behavior

```
$ sudo add-apt-repository ppa:obsproject/obs-studio
Repository: 'deb https://ppa.launchpadcontent.net/obsproject/obs-studio/ubuntu/ lunar main'
Description:
Latest stable release of OBS Studio
More info: https://launchpad.net/~obsproject/+archive/ubuntu/obs-studio
Adding repository.
Press [ENTER] to continue or Ctrl-c to cancel.
Found existing deb entry in /etc/apt/sources.list.d/obsproject-ubuntu-obs-studio-lunar.list
Adding deb entry to /etc/apt/sources.list.d/obsproject-ubuntu-obs-studio-lunar.list
Found existing deb-src entry in /etc/apt/sources.list.d/obsproject-ubuntu-obs-studio-lunar.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/obsproject-ubuntu-obs-studio-lunar.list
Adding key to /etc/apt/trusted.gpg.d/obsproject-ubuntu-obs-studio.gpg with fingerprint BC7345F522079769F5BBE987EFC71127F425E228
Hit:1 http://se.archive.ubuntu.com/ubuntu lunar InRelease
...
Ign:9 https://ppa.launchpadcontent.net/obsproject/obs-studio/ubuntu lunar InRelease
Err:10 https://ppa.launchpadcontent.net/obsproject/obs-studio/ubuntu lunar Release
  404  Not Found [IP: 185.125.190.52 443]
Reading package lists... Done                             
E: The repository 'https://ppa.launchpadcontent.net/obsproject/obs-studio/ubuntu lunar Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

### Steps to Reproduce

1. Update system to Ubuntu 23.04
2. Use the official instructions to install via PPA from https://obsproject.com/download#linux

### Anything else we should know?

Similar to https://github.com/obsproject/obs-studio/issues/7631

**Comment by Gol-D-Ace** [comment]
Hi
PPA for Lunar will be added with OBS Studio 29.1

Debian/Ubuntu provides a package for 29.0.2 which overtakes priority.

If you need a package and know how to prevent Ubuntu from overriding the package you can get the Deb from here:

https://launchpad.net/~gol-d-ace/+archive/ubuntu/test/+files/obs-studio_29.0.2-0obsproject1~lunar_amd64.deb

**Comment by encore64** [comment]
Ah, good to know! Thank you.

**Comment by Gol-D-Ace** [comment]
The main PPA should have the package in an hour or two as well but like I said the Ubuntu repo package will take priority by default.
