### ISSUE TITLE
[linux] obs 29.0.2 able to crash ALSA

### ISSUE THREAD

**Issue by arrowgent** [obsproject/obs-studio#8821]
### Operating System Info

Other

### Other OS

Ubuntu 18.04

### OBS Studio Version

29.0.2

### OBS Studio Log URL

nope.

### Expected Behavior

audacious mp3 plays without crashing system sound & obs sound

### Current Behavior

audacity mp3 (only certain ones) will crash the obs sound input

```
info: audio settings reset:
	samples per sec: 48000
	speakers:        2
	max buffering:   960 milliseconds
	buffering type:  dynamically increasing
```

```
info: pulse-input: Server name: 'pulseaudio 12.2-2'
info: pulse-input: Audio format: s16le, 192000 Hz, 2 channels
info: pulse-input: Started recording from 'alsa_output.pci-0000_00_1b.0.analog-stereo.monitor'
info: pulse-am: Prevented feedback-loop in 'alsa_output.pci-0000_00_1b.0.analog-stereo.monitor'
```

this is when it crashes.
```
ALSA lib pcm_dsnoop.c:641:(snd_pcm_dsnoop_open) unable to open slave
error: alsa-input: Failed to open 'default': Device or resource busy
info: alsa-input: PCM 'default' rate set to 48000
info: alsa-input: PCM 'default' channels set to 2
```

### Steps to Reproduce

1. open obs
2. start certain mp3 files while obs is open
3. audio will crash, obs audio stops
4. system audio stops
5. shutting off obs resets the system audio
...

### Anything else we should know?

ideally if the audio crashes then obs should attempt to reset it, recover from the failure?
this would be better than exiting and restarting obs

**Comment by kkartaltepe** [comment]
You are using an unsupported outdated os, and you have not provided a log, and this looks like a system configuration issue. After you have updated to a supported os, please use our support channels in discord or the forums if you still have issues.
