### ISSUE TITLE
Cannot change output size

### ISSUE THREAD

**Issue by o-alquimista** [obsproject/obs-studio#8822]
### Operating System Info

Ubuntu 22.10

### OBS Studio Version

Other

### OBS Studio Version (Other)

OBS Studio - 28.0.1.11-3 (linux)

### OBS Studio Log URL

https://obsproject.com/logs/IjB3AmRyNXM0D5KT

### Expected Behavior

I'm trying to record a **small** part of my screen.
Here's an example video I made using GNOME's built-in screen recorder:

[Screencast from 2023-04-29 18-42-19.webm](https://user-images.githubusercontent.com/25424263/235325386-e46a05b2-7258-479f-86b4-17940663c217.webm)

### Current Behavior

The resulting video has an undesired black area, making it much larger than desired:
![Screenshot from 2023-04-29 18-49-47](https://user-images.githubusercontent.com/25424263/235325557-04708305-72e9-4db3-bf9c-a910b90f8b28.png)

Here I reproduce the problem:

https://user-images.githubusercontent.com/25424263/235325280-a8163c63-1a20-4e31-aa8b-521cfc5a996d.mp4

### Steps to Reproduce

1. Transform the output, making a crop to record a small part of your desktop.
2. With the source selected, open a context menu and use the option "Resize output (source size)". I expected this to adjust the output size to the cropped area. If I'm not mistaken, older versions did exactly that.
3. Record and then watch the resulting video file.

### Anything else we should know?

I'm on Ubuntu, GNOME Wayland session. It was installed with `sudo apt install obs-studio`.

**Comment by tytan652** [comment]
In OBS, the video resolution is always the output canvas resolution set in the settings.

**Comment by GeorgesStavracas** [comment]
OBS doesn't need to expose the area capture, because it supports cropping the captured monitor within the canvas itself. Press `Alt` and drag the source edges, and it'll crop.

**Comment by nyanpasu64** [comment]
> In OBS, the video resolution is always the output canvas resolution set in the settings.

The problem is that not only cropping the *source* by alt-dragging doesn't auto-crop the *output* video file to the same area, but you cannot *manually* crop the output to the same size, because "Resize output (source size)" resizes the output to the *uncropped* source dimensions and blows the cropped source up to fill the canvas (with letterboxing/pillarboxing). To be useful as a screen-region recorder, OBS would need an easy way to resize the output to the *visible* portion of the current source (with 1:1 pixel mapping).

This was actually explained and requested in the original post (not by me), but the issue was closed without understanding the problem or providing a solution.

**Comment by Fenrirthviti** [comment]
This would effectively be a feature request at this point, not a bug report. We currently are only accepting bug reports for GitHub issues, and all feature requests should be submitted to our [ideas page](https://ideas.obsproject.com/).

That said, to explain further, while we understand that this might help some very, very specific and niche workflows, the reality is that most users do not change their resolution very often, if at all. Even less to something that isn't a ratio of their display. Our stance has typically been that if someone has an advanced enough workflow to know that they need a specific, esoteric output size, that they understand how to set that size manually.

One might think that this would be a "simple" or "easy" change for us to make, but understand it adds another code path that we need to test, account for, update, and maintain as necessary. However, if there is enough demand shown on the ideas page, we will certainly consider it!

**Comment by aimountain** [comment]
unsubscribe.
















At 2023-06-11 13:52:37, "Joel Bethke" ***@***.***> wrote:

This would effectively be a feature request at this point, not a bug report. We currently are only accepting bug reports for GitHub issues, and all feature requests should be submitted to our ideas page.

That said, to explain further, while we understand that this might help some very, very specific and niche workflows, the reality is that most users do not change their resolution very often, if at all. Even less to something that isn't a ratio of their display. Our stance has typically been that if someone has an advanced enough workflow to know that they need a specific, esoteric output size, that they understand how to set that size manually.

One might think that this would be a "simple" or "easy" change for us to make, but understand it adds another code path that we need to test, account for, update, and maintain as necessary. However, if there is enough demand shown on the ideas page, we will certainly consider it!

**Comment by hopeseekr** [comment]
So it was never implemented due to bureaucracy? Did I read this thread right?
