### ISSUE TITLE
"Check for Updates" pop up refuses to go away and keeps showing up even after restarting the application

### ISSUE THREAD

**Issue by albas99** [obsproject/obs-studio#8827]
### Operating System Info

macOS 13

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/xwPxXi4Oe9Hzw80x

### Expected Behavior

When I click on "Check Automatically" or "Don't Check", it should close the pop up or at least stop showing up when I restart the application.

### Current Behavior

Even when I click either of the buttons, it just doesn't go away and restarting the application doesn't help the issue also. It just keeps popping up the moment I open the application.

### Steps to Reproduce

1. Fresh install OBS
2. Finish setting everything up for streaming
3. Restart the application in order for screen sharing permissions to kick in.
...

### Anything else we should know?

I don't know if this is part of the issue, but I didn't restart it immediately after I set the screen sharing permissions, I restarted after I finish setting it up and added the macOS Screen Capture source. That was when this issue started.

Also, here's a screencast: https://www.loom.com/share/8af5997c2f8f4296a339b5a2e97e1ffe

**Comment by gxalpha** [comment]
This should be fixed in OBS Studio 29.1.
