### ISSUE TITLE
Crash when authenticating with streaming services

### ISSUE THREAD

**Issue by Inifio** [obsproject/obs-studio#8836]
### Operating System Info

macOS 12

### Other OS

12.5.1 (21G83)

### OBS Studio Version

29.1.0

### OBS Studio Log URL

https://obsproject.com/logs/prJvCulYnkQtb6b4

### OBS Studio Crash Log URL

https://pastebin.com/5EyzzmZ6

### Expected Behavior

- Successful authentication OAuth authentication with services like Twitch or Restream

### Current Behavior

- Upon allowing access in the OAuth popup window, the application crashes. 

### Steps to Reproduce

1. Open Settings in OBS Studio
2. Go to "Services"
3. Select service which has authentication as an option (Twitch, or Restream)
4. Follow authentication prompts
5. Once finished with prompts the application will crash. 

### Anything else we should know?

I have consulted other team member about the issue, at least 3 others experience the same issue with Restream. Completely uninstalling the application (removing all OBS files from Library) and reinstalling, the issue still exists. 

The issue does not appear to be limited to Apple Silicon machines. 1 person from the sample had an Intel Mac and had the same experience. 

Some reported that this issue is intermittent.

**Comment by RytoEX** [comment]
I was not able to reproduce this on an Apple M2 MacBook Pro on macOS 13.3.1 when authenticating with Twitch. I was able to reproduce this when authenticating with Restream.

**Comment by micsthepick** [comment]
Can reliably reproduce on my new M1 MacBook Air.
