### ISSUE TITLE
Nvidia AV1 not working

### ISSUE THREAD

**Issue by bmcginnis827** [obsproject/obs-studio#8837]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.0

### OBS Studio Log URL

https://obsproject.com/logs/OmJfotklXYn4uCAB

### Expected Behavior

Streaming to Youtube using AV1 encoding with 4090 GPU. Using latest Nvidia drivers. 531.79

### Current Behavior

I get error: Failed to start streaming. Starting the output failed. please check log for details.

### Steps to Reproduce

1. Just try to stream to Youtube using AV1 NVidia encoder.
...

### Anything else we should know?

I switched back to Nvidia HEVC encoder and streaming to youtube RTMPS works fine. Not using HDR.

**Comment by derrod** [comment]
Disable output rescaling, this is not currently supported with the AV1 encoder since it doesn't have an FFmpeg fallback.

**Comment by bmcginnis827** [comment]
> Disable output rescaling, this is not currently supported with the AV1 encoder since it doesn't have an FFmpeg fallback.

Thank you derrod, that worked.

**Comment by RytoEX** [comment]
Is there a particular reason that you're setting OBS to downscale to 1080p and then setting the encoder to upscale to 4K? This should just work if you set OBS output resolution to 4K.

**Comment by bmcginnis827** [comment]
> Is there a particular reason that you're setting OBS to downscale to 1080p and then setting the encoder to upscale to 4K? This should just work if you set OBS output resolution to 4K.

Left over settings. Resolved. Thank you 👍

**Comment by RytoEX** [comment]
Ah, sorry, seems there was cross-posting while I had the window open. My apologies.
