### ISSUE TITLE
DRI_PRIME=1 stop working

### ISSUE THREAD

**Issue by gabrielcapilla** [obsproject/obs-studio#8839]
### Operating System Info

Other

### Other OS

Linux 6.1.25-1-MANJARO

### OBS Studio Version

Other

### OBS Studio Version (Other)

obs-studio-amf 29.1.0-1

### OBS Studio Log URL

https://obsproject.com/logs/rwnriHoBOVxFE6vG

### Expected Behavior

With a dual AMD GPU setup (_GPU:0 and GPU:1_) select via `DRI_PRIME=1` the **GPU:1** for recording content.

> GPU:0 is RX 5700 XT and GPU:1 is RX 5700

### Current Behavior

It seems that it is now not possible to select the GPU using `DRI_PRIME=1`. It uses GPU:0 even though it was instructed to use GPU:1 using `DRI_PRIME=1`.

### Steps to Reproduce

1. Update OBS
2. OBS is updated to version` obs-studio-amf 29.1.0-1`

### Anything else we should know?

Before the update, it worked correctly with `DRI_PRIME=1` (_I don't know the specific version before 29.1.0-1_). To simplify the process, just add **DRI_PRIME=1** to `Exec=` in `/usr/share/applications/com.obsproject.Studio.desktop`.

The result looks like this: `Exec=DRI_PRIME=1 env XCURSOR_SIZE=24 VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/amd_pro_icd64.json obs`

**Comment by kkartaltepe** [comment]
Please provide a log of the older version of obs with your current drivers where the DRI_PRIME selector is working.

**Comment by gabrielcapilla** [comment]
> Please provide a log of the older version of obs with your current drivers where the DRI_PRIME selector is working.

How can I do it? Running `sudo downgrade obs-studio-amf `tells me the following:

```
Downgrading from A.L.A. is disabled on the stable branch. To override this behavior, set DOWNGRADE_FROM_ALA to 1.
See https://wiki.manjaro.org/index.php/Downgrading_packages for more details.
```

I don't know how to install an older version of obs-studio-amf, can you give me some suggestions on how exactly to install the version before 29.1.0-1? It is literally the version before 29.1.0-1.

**Comment by tytan652** [comment]
Closed because:
- You stated that it now works
- You use a package of OBS that have unsupported patches applied
