### ISSUE TITLE
Switching collections causes sources to change order and change names. Very weird behaviour

### ISSUE THREAD

**Issue by nacalai** [obsproject/obs-studio#8843]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.0

### OBS Studio Log URL

https://obsproject.com/logs/LMo6rn3pE80jleEt

### Expected Behavior

Switching scene collections should have no effect on the order and names of sources in the collection.

### Current Behavior

I have a scene collection with a lot of "Kamera 1", "Kamera 2", and so on, as seen here:

![image](https://user-images.githubusercontent.com/4357694/235877902-e6f16ce6-3fa1-4180-b282-c0f914b6bc78.png)

If I switch to for example an empty scene collection, and then back again, suddenly things are not the way they were. "Kamera 1" is now at the  bottom of the list, and is named "Kamera 1 2", as if it's been duplicated, but in reality it is not. Some sources are moved around and have a "2" added to them, some are not.

![image (1)](https://user-images.githubusercontent.com/4357694/235877946-7545e40d-9bed-4f62-94c5-584099178fe6.png)

Incredibly weird behaviour.

In the logs I can see stuff like this

`
11:22:12.908: Attempted to insert context with duplicate name "NDI Kam 4"! Name has been changed to "NDI Kam 4 2"

11:22:12.908: Attempted to insert context with duplicate UUID "2213c270-102a-4f0e-a26f-4df8e660fe9d"!
11:22:12.908: Attempted to insert context with duplicate UUID "72a0de21-1e01-4309-94df-512a56a97a00"!
11:22:12.908: A/V thread for 'NDI Kam 4 2' started
11:22:12.909: Attempted to insert context with duplicate UUID "6c0c3437-be0f-4c6f-a489-8f7358d8b756"!
11:22:12.909: Attempted to insert context with duplicate UUID "5f06c5d2-8304-4fb1-9c45-4280dec7fc6f"!
11:22:12.909: started A/V threads for source 'CAM-2 (Channel 1)'
11:22:12.909: Attempted to insert context with duplicate name "NDI Kam 3"! Name has been changed to "NDI Kam 3 2"
11:22:12.909: Attempted to insert context with duplicate UUID "945391de-36c4-4365-bb7b-768cafcb0a98"!
11:22:12.909: Attempted to insert context with duplicate UUID "4643243d-61fc-40a8-ab3f-3974a346476b"!
11:22:12.910: A/V thread for 'NDI Kam 3 2' started
11:22:12.910: Attempted to insert context with duplicate UUID "75a1a4c5-b054-4e07-bab6-3d15a003ad38"!
11:22:12.910: Attempted to insert context with duplicate UUID "5b713fda-9ee9-43be-b0cf-20cfe7bc9f92"!
`

### Steps to Reproduce

1. Switch to any other scene collection
2. Switch back to the scene collection
3. Sources get's messed up in the order and naming
...

**Comment by derrod** [comment]
If you have backups of the collection, try them again but without any third party plugins (you have several, you can use [portable mode](https://github.com/obsproject/obs-studio/wiki/Install-Instructions#portable-version) to run it separately from your main install). It seems like some plugin may be holding onto some sources when switching, causing issues with unloading the scene collection.

**Comment by nacalai** [comment]
I'll try that. This does not happen on v27, with the exact same setup and
plugins (different version though).

ons. 3. mai 2023, 11:43 skrev Rodney ***@***.***>:

**Comment by derrod** [comment]
We changed some internals to improve performance and better support certain use cases, so now a source never being released can probably result in this issue. Previously this would've just kept sources loaded and negatively impacted your performance and possibly have broken some functionality that relies on finding sources by name. So either way it's an issue that needs to be fixed in the plugin responsible for this.

**Comment by nacalai** [comment]
Aha, makes sense. I found which plugin caused the problem. It was Source Dock. It wasn't using the latest version. I updated it, and it works without problems.

The PR you linked seems like a nice thing btw.
