### ISSUE TITLE
macOS 10.15 Catalina support dropped in OBS 29.1? Please build for Catalina or update documentation/changelog to say minimum supported macOS is macOS 11

### ISSUE THREAD

**Issue by DeeDeeG** [obsproject/obs-studio#8849]
### Operating System Info

macOS 10.15

### OBS Studio Version

29.1.0

### OBS Studio Log URL

N/A (OBS does not launch, so no log file is generated)

### Expected Behavior

Expected OBS Studio 29.1 to launch on macOS 10.15, since it didn't say anywhere I looked before downloading that macOS 11 or newer was required. In fact, it said macOS 10.15 or newer.

### Current Behavior

OBS 29.1 says it requires macOS 11 or later, and refuses to fully launch.

![You can't use this version of the application "OBS" with this version of macOS. You have macOS 10.15.7. The application requires macOS 11.0 or later.](https://user-images.githubusercontent.com/20157115/236084637-cef96d06-655d-4ae1-ba4b-88f80fa43c1e.png)

### Steps to Reproduce

1. Download OBS 29.1 on macOS 10.15. (OBS 29.1 Beta 1 through to the Relese Candidate and 29.1.0 final release, all are equally affected)
2. Try to launch it

### Anything else we should know?

This macOS 11 minimum version requirement seems to have been introduced as of the big CMake 3 PR merged in March: https://github.com/obsproject/obs-studio/pull/8247

> [Minimum macOS deployment target is macOS 11.0](https://github.com/obsproject/obs-studio/pull/8247#issuecomment-1426415629)

Note: If a person only has a Mac capable of running macOS 10.15.7, they apparently cannot build from source, since [docs say building OBS from source on macOS requires macOS 12 or newer.](https://github.com/obsproject/obs-studio/wiki/Build-Instructions-For-Mac)

**_So I would humbly request either a build be made that can run on macOS 10.15.7, e.g. if CMake 2 can be used to produce such a build of OBS, or else the Changelog and all the documentation please be updated to say macOS 11.0 is the new minimum for OBS 29.1._**

**Documentation pages that should be updated if macOS 10.15 support is truly gone:**
- https://github.com/obsproject/obs-studio/wiki/System-Requirements
- https://obsproject.com/kb/system-requirements
- https://obsproject.com/download --> click the Apple logo to see "The macOS release of OBS Studio supports macOS **_10.15_** and newer."
- Changelog: https://github.com/obsproject/obs-studio/releases/tag/29.1.0
- Release notes: https://obsproject.com/blog/obs-studio-29-release-notes
- _(Maybe others, but these are the pages/docs I found mentioning macOS 10.15 support.)_

Note, for any macOS 10.15.7 users who may be curious which versions they can use... **_OBS 29.0.2 and older are usable on macOS 10.15.7_** (or at least I can confirm it launches on my macOS 10.15 machine).

---

P.S. obviously I understand you can't support older macOS forever.

Thank you for all you do, and thanks for considering this request.

Best Regards.

**Comment by gxalpha** [comment]
I have updated the wiki and knowledge base. Download page still needs updating.
OBS 29.0.2 is the last version to support macOS 10.15, we’re currently not looking to release OBS 29.1 for macOS 10.15.

**Comment by RytoEX** [comment]
This was an oversight. My own notes on "announcements for OBS 29.1" had an item to include an item for "dropping macOS 10.15" and I forgot to make sure it was included. For that, I apologize.

As you mentioned, this was changed as part of #8247. It has become increasingly difficult to support macOS 10.15 as a platform, for both end-user support and code maintainability, so we made the decision to drop support for it. It is unlikely that will we provide new builds of OBS for macOS 10.15 or older. As you have noted, OBS Studio 29.0.2 will continue to work on macOS 10.15.

We have amended the documentation items that you listed.

* [x] https://github.com/obsproject/obs-studio/wiki/System-Requirements
* [x] https://obsproject.com/kb/system-requirements
* [x] https://obsproject.com/download
* [x] Changelog: https://github.com/obsproject/obs-studio/releases/tag/29.1.0
* [x] Release notes: https://obsproject.com/blog/obs-studio-29-release-notes

**Comment by DeeDeeG** [comment]
### Note to users on any intel-based (mostly older) Macs: Consider installing Windows?

Dropping by to note: If using the same machine is important, but being on macOS is not important, affected users may wish to install Windows (https://support.apple.com/en-us/HT201468).

You get access to the intel QuickSync Video (QSV) hardware encoder that can be really useful for livestreams, since it supports CBR quality controls that streaming services expect, unlike the Apple-provided hardware encoders exposed through macOS (Apple Video Toolbox (VT) H264 Hardware Encoder). (https://obsproject.com/kb/hardware-encoding) Assuming you have anything to stream that can run on the older Mac in the first place.... But in general, streaming from these older machines gets a lot more capable under Windows than macOS, IMO, just based off which encoders you can and can't use on each respective OS.

### Note to users on newer Macs (model year 2013+): Consider installing newer macOS if you can?

The most affected machines would be model year 2012 or older. If you have a model year 2013 or newer Mac, you should be able to get newer macOS. Although I hear OBS supports more and more features / supports them better the newer macOS you can be on...

#### Which versions of macOS can my Mac run?

- [macOS Catalina (macOS 10.15) is compatible with these computers](https://support.apple.com/HT210222)
- [macOS Big Sur (macOS 11) is compatible with these computers](https://support.apple.com/HT211238)
- [macOS Monterey (macOS 12) is compatible with these computers](https://support.apple.com/HT212551)
- [macOS Ventura (macOS 13) is compatible with these computers](https://support.apple.com/HT213264)

#### How to update to newer macOS?

- [Update macOS on Mac](https://support.apple.com/HT201541)
- [How to download macOS](https://support.apple.com/HT211683)

### Caveat: I'm not part of OBS team

I am not a part of the OBS team, I don't represent them, I'm just a random person trying to drop whatever helpful resources I can on this thread that I think people will find if they search for why macOS 10.15 support was dropped and what they can do about it.

**Comment by victornpb** [comment]
> I have updated the wiki and knowledge base. Download page still needs updating. OBS 29.0.2 is the last version to support macOS 10.15, we’re currently not looking to release OBS 29.1 for macOS 10.15.

## OBS 29.0.2

For future reference:

OBS 29.0.2 being the latest version supporting macOS 10.15 (Catalina) can still be downloaded here:

- Intel: https://github.com/obsproject/obs-studio/releases/download/29.0.2/obs-studio-29.0.2-macos-x86_64.dmg
- Arm64: https://github.com/obsproject/obs-studio/releases/download/29.0.2/obs-studio-29.0.2-macos-arm64.dmg

Release: https://github.com/obsproject/obs-studio/releases/tag/29.0.2
