### ISSUE TITLE
Can't uninstall when installing over Intune (Microsoft Store App)

### ISSUE THREAD

**Issue by Hustenstopper** [obsproject/obs-studio#8856]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.2.4 (from Microsoft Store)

### OBS Studio Log URL

N/A

### OBS Studio Crash Log URL

N/A

### Expected Behavior

I expect to be able to uninstall an application again, after it has been installed.

### Current Behavior

![image](https://user-images.githubusercontent.com/121304549/236464364-bbcf9f40-6b9a-40c0-9fd4-a0e5b0b78efd.png)
(It won't be uninstalled at all).

### Steps to Reproduce

1. Add OBS to Intune as "Windows Store App (new)" App-Type
![image](https://user-images.githubusercontent.com/121304549/236464903-5957e58e-11fb-4e26-92ce-b2691b1ce070.png)

2. Create assignment
![image](https://user-images.githubusercontent.com/121304549/236465291-01086e0a-35ed-4453-95a7-ba1a5018be34.png)

3. Install it on any client via company portal (works)
![image](https://user-images.githubusercontent.com/121304549/236466086-4bf2f06b-0392-47ea-99be-b2e12a7538c7.png)

4. Change assignment to "uninstall"
![image](https://user-images.githubusercontent.com/121304549/236466866-17fc17ae-6454-4896-a798-50cf39e41004.png)

5. Watch the uninstallation fail (permanently)
![image](https://user-images.githubusercontent.com/121304549/236467198-8e5c7eed-6738-4717-ac66-dc7f4e1e54a9.png)

### Anything else we should know?

Tested with User-Group assignment and Machine-Group assignment. Both fail.

Assumption: 

The user dialog, which asks during uninstallation if the configuration should be preserved, prevents a successful uninstallation over Intune since the users can't see those dialogs and Intune can't catch / suppress it either.

**Comment by notr1ch** [comment]
You may need to configure it to run the uninstaller with the `/s` argument for a silent uninstall.

**Comment by Hustenstopper** [comment]
@notr1ch That's something you can't in Intune since it utilizes Microsoft Store & WinGet (backend). I guess the only ones who can adjust the parameters on the Microsoft Store version are the developers resp. those who have published the app in the Microsoft Store.

**Comment by Fenrirthviti** [comment]
From my experience, Intune expects you to package and deploy your own custom packages for cases like this. I don't see much crossover from the MS Store and a managed environment with custom package requirements.

Since we have a valid solution, and it is a limitation of Intune that is incompatible with this solution, there isn't likely much we can do anyway on this. I'd recommend providing the feedback to allow Intune to pass what are effectively Windows-defined flags to applications.

**Comment by Hustenstopper** [comment]
Hi Joel

It's a pity to hear this, since everything is going more and more towards UWP / WinGet and also the "Self-Service" approach in client-management.

Packaging OBS as a Win32 app is not something I will do to myself. We can't afford the time to create a new package every time OBS publish an Update.
We will therefore abandon OBS in our company and look for other alternatives.

Kind regards

S. Alder

**Comment by Fenrirthviti** [comment]
Having spent 15+ years working as desktop support, and security, for a managed enterprise environment, creating a package is a normal and expected part of any standard sysadmin job. You're going to run in to a lot of packages that don't work otherwise.

OBS is also shipped as a .zip installation as well with every release, and the only "install" that needs to be done is copying the files where you want them. This should take any competent sysadmin 5 minutes to write a script to create an Intune install package. Our installer is more or less handling some basic conflict checking and user settings, and isn't required for the application to work just fine. Just dump the files where you want them, and you're done.

**Comment by Fenrirthviti** [comment]
In any event, someone else on the team decided to look in to it and this might be a solution, though it's not tested. Since this is your request, testing this PR would be welcome to hear if it solves your issue or not:

https://github.com/obsproject/bouf/pull/34

**Comment by Hustenstopper** [comment]
Hi Joel

Technologies change, so does client management and modern Client Management differs significantly from the classic approach.

"If you do something the way you've been doing it for 10 years, chances are high, that you're doing it wrong."
- Charles Kettering

As I see it, just because something's always been done that way, doesn't mean it should continue to be done that way.
For me, the advantage of UWP apps / WinGet is precisely that the administration effort is kept within limits / practically is non-existent.

It's not that I as an admin want to use certain Windows Store apps, but that my users approach us with corresponding requests.
But since we don't have an explicit "software packager" and also won't hire one, UWP would allow us to provide such apps to our users without shooting ourselves in the foot in terms of administration effort.

I have already started some time ago to convert everything that is at all possible to UWP.
And I have had good experiences with it. Also with the self-service approach via the company portal.

A fact is that it was never really contemporary to give the user local admin rights. This has actually always been a bad habit.
And without such local admin rights, the user cannot uninstall the (supposedly) UWP app - which he could install without admin rights - without writing a ticket.
This is exactly what I want to avoid and therefore I will only make such (non-business critical) tools available to my employees if the administration effort is kept within limits.

Therefore, I will leave OBS-Studio out for the time being.

Kind regards

**Comment by Hustenstopper** [comment]
Hi Joel

I will of course be very happy to test and provide feedback. 😊

Kind regards

S. Alder
