### ISSUE TITLE
Missing dll files albeit being present in the path

### ISSUE THREAD

**Issue by qomhmd** [obsproject/obs-studio#8857]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.0

### OBS Studio Version (Other)

29.0 and 29.0.1 and 29.0.2

### OBS Studio Log URL

N/A

### Expected Behavior

The program must run after I install it.

### Current Behavior

Two error dialogs are shown sequentially after trying to open OBS program:

![qt](https://user-images.githubusercontent.com/9105400/236576651-f493ad12-457e-474f-aaa4-77f8d47b88cf.png)

![obs](https://user-images.githubusercontent.com/9105400/236576648-4c6a5c5c-8463-40af-acea-81f47f63ff3c.png)

Both `.dll` files are there in the represented path.

I tried installing it in a path without space characters in it but it didn't differ.

Also, I tried the three previous versions but the `obs.dll` was not again found by the software.

### Steps to Reproduce

1. Install it.
2. Open it.

### Anything else we should know?

PS. Windows version edited.

**Comment by Penwy** [comment]
Can you do the following :
1. Press WinKey+R to open the Run dialog
2. Paste the following into the box and hit OK: %APPDATA%\obs-studio\logs
3. grab any file from there and upload it here

**Comment by qomhmd** [comment]
> 2. Paste the following into the box and hit OK: %APPDATA%\obs-studio\logs
No `obs-studio` folder in the AppData, @Penwy.

**Comment by RytoEX** [comment]
Please do the following:
1. Press WinKey+R to open the Run dialog
2. Paste the following into the box and hit OK: winver
3. Share a screenshot of the "About Windows" window

**Comment by qomhmd** [comment]
I mistakenly set the OS option as Windows 11 in the first post. Edited.

![20230506_015839](https://user-images.githubusercontent.com/9105400/236579021-2a1666de-c48e-42fc-b429-94dfef4b3edb.jpg)

**Comment by derrod** [comment]
OBS does not support Windows 10 versions prior to 1803, and Qt 6 (the UI framework) only supports 1809 or later. OBS 27.2 might work, but any newer version won't.
