### ISSUE TITLE
No *_qsv encoder in the list of video encoders for custom output

### ISSUE THREAD

**Issue by arm64-v9a** [obsproject/obs-studio#8859]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.0

### OBS Studio Log URL

N/A

### Expected Behavior

The *_qsv encoder should exist

### Current Behavior

Can't find

### Steps to Reproduce

1. Settings -> Output -> Recording -> Custom Output (FFmpeg) -> Video Encoder

**Comment by tytan652** [comment]
The FFmpeg build included is not built with QSV features.
