### ISSUE TITLE
OBS no real 60 fps on wayland

### ISSUE THREAD

**Issue by IgnIVertiKalCaD** [obsproject/obs-studio#8860]
### Operating System Info

Other

### Other OS

Arch linux

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/trBY3zd6WvLfjDBc

### Expected Behavior

60 real shots on wayland

### Current Behavior

On x11, there are no problems with the smoothness of the final video sequence. On Wayland it feels like 30, although in the settings it is 60. In real life, there are no friezes, starters and other things. The picture is smooth, but in the final video you can see starters, dips, and so on.

### Steps to Reproduce

1. Set wayland session

### Anything else we should know?

https://youtu.be/o66OlbItlto

**Comment by GeorgesStavracas** [comment]
This was a bug in Mutter that was fixed in https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2804. Arch didn't update Mutter to a version that contains that fix yet. Please ask Arch packagers to update GNOME.

**Comment by IgnIVertiKalCaD** [comment]
Can you suggest. On which version of mutter was my bug fixed?

my version mutter: 43.4

**Comment by GeorgesStavracas** [comment]
44.1

**Comment by IgnIVertiKalCaD** [comment]
Working without freezing and more, if:
![image](https://user-images.githubusercontent.com/54883747/236661363-2b542e03-ab8d-4411-ad9f-73082f45c783.png)

thanks all much
