### ISSUE TITLE
v29.1.0 Media Source cannot be heard

### ISSUE THREAD

**Issue by wkitty42** [obsproject/obs-studio#8863]
### Operating System Info

Ubuntu 20.04

### OBS Studio Version

29.1.0

### OBS Studio Log URL

https://obsproject.com/logs/N9t765VBB4SG67ze

### Expected Behavior

i expect to hear the media source when it is playing... in this case, the media source is a local mp3 file... the source is not muted in the mixer...

### Current Behavior

cannot hear the media source while it is playing but the level bars in the mixer are showing that the source is playing... the media source is properly heard in recordings and i assume it is also heard in the (twitch) stream when broadcasting live...

### Steps to Reproduce

1. in a Scene, Add a Media Source
2. in the Media Source properties, be sure "Local File" is selected
3. set the Media Source to play a mp3 file
4. all of the options below the file path are selected except the last one, "Close when inactive"
5. everything else is default

### Anything else we should know?

it used to work just fine... when i load the scene, the mp3 would be playing and i could hear it... i don't know when the problem actually appeared as i've not loaded OBS in a while but there have been several updates pulled in and applied...

in this specific case, i have a slideshow of solar system planets being shown while the mp3 is playing on loop... this sideshow is a group scene (?) that is included in a couple of other scenes... this group is used in my starting, intermission, and stopping scenes...

i don't know what else to add as it has been a year or two since i created the group and everything worked nicely at that point...

**Comment by tytan652** [comment]
The sound of a media source is only sent to OBS outputs (recording, streaming).

You can use audio monitoring if you want to hear the source audio.

**Comment by wkitty42** [comment]
> The sound of a media source is only sent to OBS outputs (recording, streaming).
> 
> You can use audio monitoring if you want to hear the source audio.

i've tried using the mixer monitor options but still don't hear the media being played...
i mean it used to work by default but something changed between versions and monitoring was not needed... i'm confused...

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by wkitty42** [comment]
On 5/7/23 1:24 PM, Joel Bethke wrote:
> This sounds more likely to be a support request rather than a bug report, and we 
> are not currently accepting support requests on GitHub Issues. Please use our 
> forums <https://obsproject.com/forum/> or Discord 
> <https://obsproject.com/discord/> for assistance.

oooookay... i figured it was a bug because it worked just fine from 2019 when i 
installed OBS for the first time until it stopped working with one of the last 
updates... it was working just fine a few weeks ago and now not... anyway, 
yeah... i'll traipse over to the discord and/or forums, i guess...

> Thank you!

thank you! :)

**Comment by kaanelloed** [comment]
I'm running Linux Mint 21.1 and the audio monitoring doesn't seem to work in OBS Studio 29.1.0. No problem with version 29.0.2. It seems to be a bug.

**Comment by wkitty42** [comment]
#8877 may be the same
