### ISSUE TITLE
29.1.0 Update Breaks Context Menu on High DPI Display (Menu Out of Screen)

### ISSUE THREAD

**Issue by peidaqi** [obsproject/obs-studio#8865]
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

29.1.0

### OBS Studio Log URL

n/a

### Expected Behavior

Context menu correctly displays within the screen boundary (see screenshot from 29.0.0)

![obs-29 0 0](https://user-images.githubusercontent.com/18495787/236706976-2e7d9a9c-f6fa-4828-96fc-965c3bdf32ed.png)

### Current Behavior

Context menu out of screen boundary (see screenshot below from 29.1.0)
This bug was fixed in 29.0.0 but re-surfaced after 29.1.0 update.

I'm using Dell XPS 13 3840x2400 resolution with 300% Zoom on Ubuntu 22.04.
The issue is fixed by reverting back to 29.0.0

![obs-29 1 0](https://user-images.githubusercontent.com/18495787/236706999-67355abc-a7a6-4d3d-b197-17b408c03ec2.png)

### Steps to Reproduce

Start OBS and open any Context Menu in bottom docked window.

**Comment by kkartaltepe** [comment]
These menus are laid out by Qt and your compositor. We do not control where they are rendered. Since you provide no logs from the two instances thats about all I can say for this.
