### ISSUE TITLE
(Reoccurrence of #6936) Windows 11: Fullscreen projector has constant tearing for Dual PC streaming/recording but not the windowed projector

### ISSUE THREAD

**Issue by faureq** [obsproject/obs-studio#8866]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.0

### OBS Studio Log URL

https://obsproject.com/logs/7V0vLxx3JsUKH6tN

### Expected Behavior

Fullscreen projector should has not tearing and behave as the same as windowed projector in updated Windows 11.

### Current Behavior

My setup:
Gaming PC: i7-9700k, RTX 3080, OBS 27.2.4, Windows 11 22622.450
Streaming PC: i7-6820HK, GTX1070, OBS 27.2.4, Windows 10 19044.1806
Capture card: Avermedia GC553 @ 1440p60hz

I mostly do streaming/recording with FPS games, e.g., Apex, COD, CSGO etc. And the mentioned setup works flawlessly when my gaming pc was Windows 10.

After my gaming rig was updated to Windows 11, I suddenly found constant screen tearing in my streaming/recording. And after some research, I found that the Fullscreen Projector is to blame. With windowed Projector, there is no tearing at all.

Fullscreen projector: ![full](https://user-images.githubusercontent.com/9159368/182678607-807b7d2b-92da-4b29-8907-5768c5727d97.gif) [ ](https://user-images.githubusercontent.com/9159368/182678607-807b7d2b-92da-4b29-8907-5768c5727d97.gif)

Windowed screen projector: ![windowed](https://user-images.githubusercontent.com/9159368/182678649-ac7af6c9-78c0-41d3-b833-b8d563e45a6f.gif) [ ](https://user-images.githubusercontent.com/9159368/182678649-ac7af6c9-78c0-41d3-b833-b8d563e45a6f.gif)

### Steps to Reproduce

1.Setup Dual PC streaming with a capture card and download OBS after 27.1 rc2 with Windows 11.
2.Set capture card as extended monitor and use Fullscreen projector.
3.Play some FPS game and move the angle quickly.
4.Same 1-3 steps with windowed projector.
...

### Anything else we should know?

Reoccurrence of [#6936](https://github.com/obsproject/obs-studio/pull/6942)

I'm experiencing this issue with OBS v29.1.0. Windowed preview works flawlessly but fullscreen preview has tearing. I tried windowed preview with autohotkey to remove the window's title and borders. If I hide the title (-WS_CAPTION) it doesn't tear. If I hide the title and borders (-WS_THICKFRAME) it tears...

**Comment by RytoEX** [comment]
Please do not copy the old text of the previous Issue. Please provide your own logs and fill out the Issue Template with your own information.

**Comment by faureq** [comment]
[data.zip](https://github.com/obsproject/obs-studio/files/11639967/data.zip)

Here I attached a video showing the behavior of the full screen preview VS the windowed preview. I also attached the logs from the OBS instance on my streaming PC as well as the logs from the OBS instance on my gaming PC.

I used https://www.testufo.com/stutter to show the problem with display capture but I can assure you the result is the same in games with game capture. Exactly as shown in the first post.

I use the same setup as explained in the first post : two PCs, one for gaming and one for streaming (with a capture card). The gaming PC does not clone/duplicate the display to the capture card, instead I configured the capture card as a second monitor (extended mode) and I use OBS preview to "copy" my main screen on the capture card.

Why would we do that? Here are a few reasons:
 - no need to have a capture card with the same capabilities as the gaming monitor
 - no screen tearing because of mismatched refresh rates
 - better control of what is on stream via OBS scenes and sources
 - no black screen when starting/closing full screen exclusive games
 - no black screen when alt-tabbing in and out of full screen exclusive games
 - color settings in NVCPL can be different
 - no input lag related to unstable clone/duplicate mode
 - DSR/DLDSR does not work in clone mode
 - clone/duplicate implementation seem bad overall https://forums.blurbusters.com/viewtopic.php?f=10&t=6965

**Comment by faureq** [comment]
Should I open a new issue or is this enough?
