### ISSUE TITLE
OBS don't show Window Capture filter

### ISSUE THREAD

**Issue by smogbh** [obsproject/obs-studio#8879]
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

29.1.1

### OBS Studio Log URL

no url

### Expected Behavior

See in the filters window 

### Current Behavior

OBS don't show Window Capture filter

### Steps to Reproduce

1. Start OBS
2. See in the filter window

**Comment by Penwy** [comment]
Window Capture is a source, not a filter

**Comment by smogbh** [comment]
Yeah, I'm sorry. Muy fault. But the problem persist in Ubuntu 22.04 with Wayland.

**Comment by Fenrirthviti** [comment]
Please provide a log file, as per the requirements of the template.

**Comment by kkartaltepe** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
