### ISSUE TITLE
ERR_CERT_AUTHORITY_INVALID - OBS 27.2.4 (64 bits), Win 7 x64 SP1

### ISSUE THREAD

**Issue by hellishvictor** [obsproject/obs-studio#8880]
### Operating System Info

Windows 11

### Other OS

Windows 7 x64 SP1

### OBS Studio Version

29.1.1

### OBS Studio Version (Other)

27.2.4

### OBS Studio Log URL

https://obsproject.com/tools/analyzer?log_url=https%3A%2F%2Fobsproject.com%2Flogs%2Fvb6k7knTHM174iRi#logURL

### Expected Behavior

It should load the chat dock.

### Current Behavior

It doesn't show the chat dock.
I tried "Stream" -> "Connect Account", and then it shows that "Couldn't load that page!". 

### Steps to Reproduce

![sshot-1](https://github.com/obsproject/obs-studio/assets/34694956/59d8a1eb-453a-471d-b029-a5f2fd64e78c)

**Comment by derrod** [comment]
You're running an unsupported version on an unsupported operating system, chances are you system root certificate store is out of date.

**Comment by mahdiyari** [comment]
I'm having the same error on Ubuntu 22. Version 30.0.2

**Comment by Sturmlocke86** [comment]
I just had the same issue on my openSUSE Leap 15.6 + Gnome machine.

The solution can be found in the comments here: https://www.reddit.com/r/openSUSE/comments/1d56u29/obs_issue_ssl_cert_error/

And in the comments here: https://github.com/obsproject/obs-studio/issues/10385

**Comment by hellishvictor** [comment]
> I just had the same issue on my openSUSE Leap 15.6 + Gnome machine.
> 
> The solution can be found in the comments here: https://www.reddit.com/r/openSUSE/comments/1d56u29/obs_issue_ssl_cert_error/
> 
> And in the comments here: #10385

Thank you for share that, but I'm on Win 7 x64 SP1.
