### ISSUE TITLE
OBS 29.1.1 has issues with plugins and addons.....

### ISSUE THREAD

**Issue by kuroganashi** [obsproject/obs-studio#8882]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.1

### OBS Studio Log URL

https://github.com/kuroganashi/OBS/blob/main/2023-05-10%2002-38-28.txt

### Expected Behavior

OBS is supposed to be able to swap Scene collections 

### Current Behavior

![crash](https://github.com/obsproject/obs-studio/assets/4380256/8af72c5d-a9f1-478a-b082-9bb6fe9e67e9)

### Steps to Reproduce

1. go to Scene collection tab
2. select any Scene collection
3. Error pops
...

### Anything else we should know?

was working fine before I updated to 29.1.1

**Comment by derrod** [comment]
Please read the error and follow its instructions. If updating plugins does not help you'll have to figure out which plugin is causing this issue and remove it.

**Comment by WizardCM** [comment]
You have the following third party plugins installed. You will need to update them all, or remove them one by one to track down the cause.

- obs-3DStingerTransition
- source-clone
- spectralizer
- obs-backgroundremoval
- gradient-source
- 3d-effect
- streamup
- source-copy
- win-capture-audio
- browser-transition
- time-warp-scan
- obs-face-tracker
- obs_scene_tree_view
- obs-streamelements-core
- scale-to-sound
- obs-streamelements
- obs-soundboard
- waveform
- obs-image-reaction-ashmanix
- source-switcher
- obs-shaderfilter
- scene-collection-manager
- obs-vintage-filter
- source-dock
- obs-multi-rtmp
- motion-transition
- source-record
- motion-filter
- media-controls
- move-transition
- recursion-effect
- transition-table
- vertical-canvas
- freeze-filter
- dynamic-delay
- scene-notes-dock
- downstream-keyer
- audio-monitor
- advanced-scene-switcher
- scene-as-transition

**Comment by kuroganashi** [comment]
> You have the following third party plugins installed. You will need to update them all, or remove them one by one to track down the cause.
> 
> * obs-3DStingerTransition
> * source-clone
> * spectralizer
> * obs-backgroundremoval
> * gradient-source
> * 3d-effect
> * streamup
> * source-copy
> * win-capture-audio
> * browser-transition
> * time-warp-scan
> * obs-face-tracker
> * obs_scene_tree_view
> * obs-streamelements-core
> * scale-to-sound
> * obs-streamelements
> * obs-soundboard
> * waveform
> * obs-image-reaction-ashmanix
> * source-switcher
> * obs-shaderfilter
> * scene-collection-manager
> * obs-vintage-filter
> * source-dock
> * obs-multi-rtmp
> * motion-transition
> * source-record
> * motion-filter
> * media-controls
> * move-transition
> * recursion-effect
> * transition-table
> * vertical-canvas
> * freeze-filter
> * dynamic-delay
> * scene-notes-dock
> * downstream-keyer
> * audio-monitor
> * advanced-scene-switcher
> * scene-as-transition

how do I remove 1 by 1 ? confused do I just delete the folders ?

**Comment by Fenrirthviti** [comment]
You would delete them the same way you installed them. Either using the provided uninstaller, or deleting the files manually where you installed them to. With that many plugins, many of which are abandoned or deprecated, it's almost a guarantee that one of them is causing your issues. If you need further assistance, please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/).

Thank you!

**Comment by Ofloo** [comment]
Source-record crashes when switching scenes. It is basically the only plugin I use and it crashes.
