### ISSUE TITLE
viewer freezing

### ISSUE THREAD

**Issue by mcDandy** [obsproject/obs-studio#8884]
### Operating System Info

Windows 11

### OBS Studio Version

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/AvxOyHLim1n1vxpU

### Expected Behavior

scene being shown and reacting to what I do

### Current Behavior

Scene viewer is frozen, recording stopped the moment I opened obs back up.

### Steps to Reproduce

1. Start recording
2. hide OBS using the tray icon 
3. record for copule of hours
4. viewer frozen

**Comment by notr1ch** [comment]
This is likely caused by HAGS, try turning it off.

https://obsproject.com/wiki/How-to-disable-Windows-10-Hardware-GPU-Scheduler

**Comment by mcDandy** [comment]
Ok, thank you.
