### ISSUE TITLE
Update 29.1.0 removed the ability to restart currently selected media source by press ing "R"

### ISSUE THREAD

**Issue by Penwy** [obsproject/obs-studio#8886]
### Operating System Info

Ubuntu 22.04

### Other OS

Also confirmed on windows

### OBS Studio Version

29.1.1

### OBS Studio Log URL

29.0.2 : https://obsproject.com/logs/0t5fYBXztKy45Dxe || 29.1.0 : https://obsproject.com/logs/r8TCBtxmlVRytA0c

### Expected Behavior

On obs 29.0.2, selecting a media source in the sources list and pressing the R key will restart its playback from the beginning.

### Current Behavior

On OBS 29.1.0, doing the same things does nothing.

### Steps to Reproduce

1. Add a media source
2. Select it in the source list
3. Press R
...

### Anything else we should know?

Logs come from linux flatpak, but also happens on PPA and has also been confirmed to be the same on windows.
From checking, the change happens specifically between 29.0.2 and 29.1.0.

**Comment by WizardCM** [comment]
I don't believe this has ever been intentional/expected behaviour.

**Comment by WizardCM** [comment]
This functionality was disabled as part of https://github.com/obsproject/obs-studio/pull/8411. The new behaviour is intentional.

**Comment by lin362** [comment]
I have the same issue on windows! https://obsproject.com/logs/Esbo2JVwZst0nzG6
