### ISSUE TITLE
Not selecting an audio track causes output to error

### ISSUE THREAD

**Issue by prgmitchell** [obsproject/obs-studio#8887]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.1

### OBS Studio Log URL

https://obsproject.com/logs/b5fdYPrxHOng1ZhQ

### Expected Behavior

I don't think it should be possible to select no audio tracks if it will always error. Also, this error is not logged. Advanced output shows a "You must select at least one track" error in the UI while simple mode does not.

### Current Behavior
![image](https://github.com/obsproject/obs-studio/assets/86465454/a54a502e-36c9-4a33-9fcb-d451b5324727)

![image](https://github.com/obsproject/obs-studio/assets/86465454/28476a2b-1f7a-4cc2-a449-346a7393c45c)

### Steps to Reproduce

1. Select simple output mode
2. Set recording quality to anything besides Same as Stream
3. Try to start your recording
...

**Comment by SuslikV** [comment]
> I don't think it should be possible to select no audio tracks if it will always error...

Not quite right. The virtual webcam outputs of OBS may has no sound.

**Comment by RytoEX** [comment]
> > I don't think it should be possible to select no audio tracks if it will always error...
> 
> Not quite right. The virtual webcam outputs of OBS may has no sound.

The Virtual Camera does not have selectable audio tracks, so it is not relevant to this Issue.

**Comment by SuslikV** [comment]
@RytoEX :) it was my small attempt to steel attention (I was unable to post in the related PR thread so...). It is related to the proposed message: 

> OutputWarnings.NoTracksSelectedOnExit.Text="**All outputs** must have at least one audio track selected."

 is right, in general, but you already know...

I apologizes for this small trick.

**Comment by RytoEX** [comment]
Following up. This output failure appears to only occur in Simple Output Mode. In Advanced Output Mode, there is a warning displayed in the UI, but the output _will_ start, and the recording silently falls back to using the Audio Track that was selected for Streaming. There is an open PR (#8897) to prevent exiting Settings without selecting audio tracks.
