### ISSUE TITLE
Error message confusion with Nvenc and Dual GPU

### ISSUE THREAD

**Issue by JamesMahy** [obsproject/obs-studio#8890]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.1

### OBS Studio Log URL

https://obsproject.com/logs/fVSzbQNoyW3yo7EU

### Expected Behavior

When running dual GPU's and Nvidia Driver 516.94 / Nvenc 11.1
I expect to be able to select the GPU to encode with.

### Current Behavior

I currently get the error message
```
Failed to open NVENC code: Function not implemented

You have selected GPU 1 in your output encoder settings. Set this back to 0 and try again
```
![image](https://github.com/obsproject/obs-studio/assets/864011/19a278b3-ebc0-422d-a9af-80c10e1cd0c0)

After reviewing the logs I see the actual issue is that I have Nvenc version 11.1 and OBS 29.1.1 now only works with 12.0

### Steps to Reproduce

1. Use a system with 2 gpus
2. Click Settings
3. Click Output
4. Change Encoder to NVENC
5. Set GPU to 1
6. Attempt to Record
...

### Anything else we should know?

This feature works in OBS 29.0.2 with Nvenc 11.1 and upgrade beyond Nvidia 516.94 is not currently an option because it causes artificating issues for many users

[https://www.nvidia.com/en-us/geforce/forums/geforce-graphics-cards/5/513459/new-nvidia-drivers-causing-artifacting-for-number-/](https://www.nvidia.com/en-us/geforce/forums/geforce-graphics-cards/5/513459/new-nvidia-drivers-causing-artifacting-for-number-/)

[https://www.techpowerup.com/forums/threads/rtx-3000-series-artifacts-black-squares-that-flicker-in-desktop-and-2d-mode.297640/](https://www.techpowerup.com/forums/threads/rtx-3000-series-artifacts-black-squares-that-flicker-in-desktop-and-2d-mode.297640/)

[https://www.nvidia.com/en-us/geforce/forums/geforce-graphics-cards/5/518886/nvidia-drivers-53179-cause-random-artifacting-duri/](https://www.nvidia.com/en-us/geforce/forums/geforce-graphics-cards/5/518886/nvidia-drivers-53179-cause-random-artifacting-duri/)

**Comment by derrod** [comment]
Using a secondary GPU falls back to the ffmpeg encoder which requires a more recent driver version, this isn't a bug, nor can we fix it. Use an older OBS version or update your drivers.

**Comment by notr1ch** [comment]
Regarding the error message, FFmpeg gives a very generic error code back when it fails, so we have to guess what the most likely cause is. For the vast majority of users, they are on a single GPU setup so trying to use a 2nd GPU is almost certainly the reason for failure.

**Comment by JamesMahy** [comment]
> Regarding the error message, FFmpeg gives a very generic error code back when it fails, so we have to guess what the most likely cause is. For the vast majority of users, they are on a single GPU setup so trying to use a 2nd GPU is almost certainly the reason for failure.

Understood, why would the log for Stream Record give me the correct error message?

**Comment by notr1ch** [comment]
The log is arbitrary text from FFmpeg that can come at any time. While we could store all the log contents and show them to the user when an FFmpeg error occurs, this also isn't an ideal solution as the log messages can come from anywhere at any time - e.g. a media source thread might be in the middle of decoding a bad packet and generate a lot of bad packet log entries. So the text that's output into the FFmpeg log may not line up with the action that the user was taking at the time.

**Comment by energizerfellow** [comment]
> I don't get this issue through FFMpeg in command line

Update to FFmpeg 6.0+

**Comment by JamesMahy** [comment]
> The log is arbitrary text from FFmpeg that can come at any time. While we could store all the log contents and show them to the user when an FFmpeg error occurs, this also isn't an ideal solution as the log messages can come from anywhere at any time - e.g. a media source thread might be in the middle of decoding a bad packet and generate a lot of bad packet log entries. So the text that's output into the FFmpeg log may not line up with the action that the user was taking at the time.

Ah that makes sense, thanks for taking the time to explain
