### ISSUE TITLE
OBS crash when trying to open settings

### ISSUE THREAD

**Issue by xdettlaff** [obsproject/obs-studio#8902]
### Operating System Info

Other

### Other OS

Fedora 38

### OBS Studio Version

29.1.1

### OBS Studio Log URL

https://obsproject.com/logs/srrWenc5XHjEVNLC

### Expected Behavior

open settings

### Current Behavior

click "settings" and obs crash 

```
debug: Attempted path: share/obs/obs-studio/locale.ini
debug: Attempted path: /usr/share/obs/obs-studio/locale.ini
debug: Attempted path: share/obs/obs-studio/themes/
debug: Attempted path: /usr/share/obs/obs-studio/themes/
debug: service 'temp_service' (rtmp_common) created
debug: service 'temp_service' destroyed
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
[1]    7446 IOT instruction (core dumped)  obs --verbose
```

### Steps to Reproduce

1. click settings

**Comment by kkartaltepe** [comment]
Please report this to your package manager, or use our official builds.

**Comment by xdettlaff** [comment]
> Please report this to your package manager, or use our official builds.
@kkartaltepe 


https://obsproject.com/download#linux
but u have only ubuntu and flatpack, but in flatpack shortcuts doesnt work

**Comment by tytan652** [comment]
Fedora applies big patches to OBS Studio for their package, report the issue to them firstly.

Or use our official packages.

**Comment by Conan-Kudo** [comment]
I didn't even make an OBS 29.1.1 package yet.

**Comment by tytan652** [comment]
> I didn't even make an OBS 29.1.1 package yet.

Author's mistake while creating the issue, the log is from 29.1.0

**Comment by Mattchine** [comment]
```bash
# WARNING!: This is system upgrade command.
# Make sure you understand what it does before running the command.
sudo dnf upgrade --refresh
```

This solve the issue for me.
