### ISSUE TITLE
SLI/CF/SMC mode in game capture does not support vulkan.

### ISSUE THREAD

**Issue by eebssk1** [obsproject/obs-studio#8909]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.1

### OBS Studio Log URL

https://obsproject.com/logs/OHOCoMK2r7miJIS4

### Expected Behavior

Should able to capture games.

### Current Behavior

Blank capture output

### Steps to Reproduce

1. Force OBS to run on iGPU.
2. enable game capture source and enable sli/cross fire mode.
3.Start a vulkan based game(default on dGPU).

### Anything else we should know?

The game is tricked to use vulkan by using dxvk.
The whole purpose for this is to use the new QSV encoder.
It's fine if this issue can not be solved, but i think it's better to make everyone benifites from the new QSV encoder.

**Comment by eebssk1** [comment]
Also found it's impossible to use h264_qsv in custom output even if obs support it in normal mode(running under dGPU),is this intented?

**Comment by derrod** [comment]
Capturing gwmes running via DXVK is not supported.

FFmpeg is not compiled with QSV support, so they won't be available.

**Comment by eebssk1** [comment]
> Capturing games running via DXVK is not supported.
> 
> FFmpeg is not compiled with QSV support, so they won't be available.

Does this also mean there  will be no support currently for using new qsv encoder running under dGPU?

**Comment by pannal** [comment]
> Capturing games running via DXVK is not supported.
> 
> FFmpeg is not compiled with QSV support, so they won't be available.

DXVK and OBS work fine over here. "Not supported" as in "doesn't work", or "we don't support it"?

**Comment by eebssk1** [comment]
> > Capturing games running via DXVK is not supported.
> > FFmpeg is not compiled with QSV support, so they won't be available.
> 
> DXVK and OBS work fine over here. "Not supported" as in "doesn't work", or "we don't support it"?

It seems Obs with Dxvk doe not work on this setup only.Other combination/setup works normally for me too.
