### ISSUE TITLE
NVENC error: unsupported device 

### ISSUE THREAD

**Issue by NattyMcK** [obsproject/obs-studio#8911]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.1

### OBS Studio Log URL

https://obsproject.com/logs/vpykDMMIPBsLKFHB

### Expected Behavior

recording properly from microphone and logi cam 

### Current Behavior

Hello,
I was notified of a NVENC error. I updated my drives as requested. when running on the integrated card this error appears, when using dedicated card the video input fails. 

### Steps to Reproduce

1. clicked record on integrated card for NVENC error
2. swapped to dedicated card for video input failure 
3.
...

**Comment by prgmitchell** [comment]
This would be a support issue. Please head to the [https://discord.com/invite/obsproject](community discord) or [https://obsproject.com/forum/](forums) for help.
