### ISSUE TITLE
Auto-Config Wizard not working when using SRT link without Stream Key

### ISSUE THREAD

**Issue by kingprawn22** [obsproject/obs-studio#8912]
### Operating System Info

Windows 11

### Other OS

All of them

### OBS Studio Version

29.1.1

### OBS Studio Log URL

No log needed

### Expected Behavior

I expect to be able to use the 'auto-config wizard' when using an SRT link, so that the connection can be tested and the ideal settings selected.

### Current Behavior

Without a stream key, I'm unable to click 'Next' when at the 'Stream Information' section of the wizard. If I remove a part of the URL entered into the 'Server' field and paste it into the 'Stream Key' field then click 'Next', I get the error "Failed to connect to any servers...", despite the link working fine when clicking 'Start Streaming' in the main interface.

### Steps to Reproduce

1. Open 'auto-config wizard'
2. When at the 'Stream Information' section of the wizard, enter the SRT URL, leave the 'Stream Key' field blank since SRT doesn't use stream keys.
3. Unable to click 'Next'.

### Anything else we should know?

I've moved my streaming project from using RTMP to SRT. The project requires multiple external streamers to connect to a server, which generates SRT links that are input to a central OBS server. Previously when using RTMP, I could have the individual streamers use the 'auto-config wizard' to automatically detect the best settings for their connection and system. After moving to SRT, this is no longer possible.

The reason this is no longer possible is that SRT doesn't use stream keys, and when following the wizard, you can't get past the 'Server Information' section without entering a stream key since the 'Next' button isn't able to be clicked. The official 'SRT Protocol Streaming Guide' also shows that there is no stream key, but doesn't provide guidance on if, or how one can use the wizard (https://obsproject.com/kb/srt-protocol-streaming-guide)

I've tried putting random characters in the 'Stream Key' field of the wizard, which is technically a valid SRT link (when entering the same random string into the 'Stream Key' field in the 'Stream' section of the Settings the connection works), but entering the same string or anything else in the 'Stream Key' field of the wizard specifically results in "Failed to connect to any servers...".

The 'auto-config wizard' is a great tool that my project made good use of until now. With it no longer working for us, we have to spend much more time with individual streamers to determine the best settings for them, instead of just running a tool that loads ideal settings in a matter of a few click.

Could this tool be updated to run with an SRT link that doesn't have a stream key, please?

**Comment by pkviet** [comment]
The wizard was written for rtmp.
There's no plan to update it to support SRT. We assume the user to have enough technical knowledge to not need a wizard for this protocol which is used mostly in broadcast.
The stream key field is used to store the streamid for SRT. There's a tooltip which explains it.
The passphrase can be entered in the password field when enabling authentication.
Anyway, with SRT all options can be passed through URL.
