### ISSUE TITLE
All scenes and sources disappeared after creating and saving a new profile

### ISSUE THREAD

**Issue by NoticeCorp** [obsproject/obs-studio#8915]
### Operating System Info

macOS 13

### OBS Studio Version

29.1.1

### OBS Studio Log URL

https://obsproject.com/logs/hdOlKkjNiHSXx7cl

### Expected Behavior

Not to lose all our scenes and sources

### Current Behavior

They disappeared

### Steps to Reproduce

1.
2.
3.
...

**Comment by NoticeCorp** [comment]
Note that all scenes and sources disappeared for all profiles - I am not talking about the docks - they are all in same place, just empty.

**Comment by WizardCM** [comment]
Without full reproduction steps, this is not actionable. Additionally, scenes and sources are tied to Scene Collections, not Profiles. These two menues are next to each other.

This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels below, and if it's determined that this is indeed a bug, then we will re-open this issue.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

**Comment by NoticeCorp** [comment]
To reproduce, create a new profile, add some scenes/sources, quit, then relaunch.
