### ISSUE TITLE
Size of Screen Capture

### ISSUE THREAD

**Issue by krklek** [obsproject/obs-studio#8916]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.1

### OBS Studio Version (Other)

64bit

### OBS Studio Log URL

https://obsproject.com/logs/MmFSduao2f3tGoP3

### Expected Behavior

When I unlock the projector?? (I don't use the "studio setting") and the capture area turns RED, if I place my cursor over the small box on the side of the area, the cursor shows a LEFT AND RIGHT ARROW, yet when I move the mouse left or right, the whole area gets smaller rather than just the left or right, as one would EXPECT.  I feel this should be changed so if you only want to see a SQUARE AREA, one should be able to accomplish this. 

This screenshot LINK indicates what I'm talking about...
https://drive.google.com/file/d/1x2-1WcRjNhBzjTl_f8i8ew3iE6BfLtOo/view?usp=share_link

### Current Behavior

  The entire screen retains the 3/4 or 9/16 resolution size.  I want to size the capture area to WHATEVER size I need at MY discretion.

### Steps to Reproduce

1.  n/a
2.
3.
...

### Anything else we should know?

n/a

**Comment by derrod** [comment]
Sounds like what you're looking for is cropping, which can be done while holding Alt when dragging the handles.

Either way, this is not a bug.

**Comment by krklek** [comment]
Oh My, THANK YOU for the information, I'll try that straight away.

Kerry
