### ISSUE TITLE
How I can import old json profile to new obs?

### ISSUE THREAD

**Issue by ProgMan01** [obsproject/obs-studio#8921]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.1

### OBS Studio Log URL

https://obsproject.com/logs/qItSCtokn5U9WRAd

### Expected Behavior

How or can I import old json profile to new obs?

### Current Behavior

I just reinstalled windows and I don't know how to import my old profile (.json)

### Steps to Reproduce

1.install obs
2.import profile 
3.don't working

**Comment by tytan652** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
