### ISSUE TITLE
HD60 X Capture shows up Blurry in preview window

### ISSUE THREAD

**Issue by neosylis** [obsproject/obs-studio#8924]
### Operating System Info

Other

### Other OS

MacOS 14.1

### OBS Studio Version

29.1.1

### OBS Studio Log URL

https://obsproject.com/logs/CWXK9sXewg9BJHua

### Expected Behavior

Capture to show clear within the preview window

### Current Behavior

Capture in preview shows up blurry.

<img width="1542" alt="Screenshot 2023-05-18 at 8 05 01 AM" src="https://github.com/obsproject/obs-studio/assets/67390998/118a80fb-995d-44ae-915a-fc9be91f7361">

### Steps to Reproduce

1. Add source and choose video capture
2. Select device as HD60 X
3.
...

**Comment by derrod** [comment]
Looks like macOS's background blur feature is enabled on the cspture card for some reason, try disabling that.

**Comment by neosylis** [comment]
It worked thank you.
I had enabled it for the webcam and it transferred to OBS.
