### ISSUE TITLE
Lots of issues with RTMP sources on Windows 11

### ISSUE THREAD

**Issue by marktheminer** [obsproject/obs-studio#8931]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.1

### OBS Studio Log URL

n/a

### Expected Behavior

I expect OBS on Windows 11 to render rtmp video sources as well as it does on Windows 10 and Linux.

### Current Behavior

https://obsproject.com/forum/threads/lots-of-issues-with-rtmp-sources-on-windows-11.166588/

### Steps to Reproduce

[1.
2.
3.
...
](https://obsproject.com/forum/threads/lots-of-issues-with-rtmp-sources-on-windows-11.166588/)

**Comment by gxalpha** [comment]
Please include all information in the issue post itself instead of linking to a forum post.

**Comment by gxalpha** [comment]
No reaction to the comment above.
