### ISSUE TITLE
Recording fails/hangs with older intel QSV H.264 using CQP or AVBR at <= 17x17 output resolution

### ISSUE THREAD

**Issue by DeeDeeG** [obsproject/obs-studio#8934]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.1

### OBS Studio Log URL

https://obsproject.com/logs/5IBTa02tvaLSCkJG

### Expected Behavior

Either the recording works fully, or else OBS shows sort of warning or error message, and/or doesn't partly hang

### Current Behavior

I get `[qsv encoder: 'simple_video_recording'] Failed to reconfigure` in the logs right when I press "Start Recording".

Also: The recording never saves (no file is written out to disk for the recording session), and if you try to stop the recording, the button just says "Stopping Recording..." forever, the Recording ("REC") icon stays red and the recording length keeps incrementing in the bottom bar, and if you try to "Exit", regardless of trying to stop the recording or not, the visible window does close, but the OBS process keeps running in the background instead of fully exiting.

### Steps to Reproduce

1. Under "Video", set the output resolution to 17x17 or smaller (regardless of whether scaled or matching canvas)
2. Under "Output", set the recording encoder to QuickSync H.264
3. Set the "Quality" or "Rate Control" to something that uses CQP or AVBR
4. Press the "Start Recording" button

### Anything else we should know?

_This seems like a separate issue,_ but whenever I try to output to exactly 18x18 or 19x19 with QSV, regardless of CBR or CQP whatever (unlike the main issue I am reporting), I get a popup:

Window title: "Recording error" Message: "An encoder error occurred while recording." Button: "[OK]" (popup dialog)

**Comment by RytoEX** [comment]
If I:
1. In Video Settings, set Output Resolution to 17x17.
2. In Output Settings, leave OBS at Simple Output Mode.
3. Select:
  1. Recording Quality: Indistinguishable Quality, Large File Size
  2. Video Encoder: Hardware (QSV, H.264)

I get an error message stating that the recording failed to start. The recording will not start at all. The same thing occurs at 16x16, 18x18, or 19x19. I can get the recording to start just fine at 20x20.

In Simple Output Mode, there is no way to directly select CQP or AVBR, it should be automatically set to CQP. The rate control method can be directly selected in Advanced Output Mode, but your log does not reflect that this was what you used. In any case, if I select Advanced Output Mode and CQP, I once again get a "Failed to start recording" error message, and no recording is started.

I am unable to get the output to start in the scenario you describe. Perhaps this is a quirk of older hardware on older drivers? I believe there should be a driver update available for that GPU. I would start by trying to update that.

As an aside, this appears to be Mac hardware running Windows. I'm not sure if QSV is expected to work in that scenario.

**Comment by energizerfellow** [comment]
Not sure why you're trying to hide the CPU model and audio hardware on what would appear to be an Intel Ivy Bridge varient they made millions of, but OK.

Given the use case as laid out in the log, OBS isn't a DAW and not designed to be a standalone audio recorder. OBS will always try to encode *some* form of video.

As mentioned above, your GPU driver version is from 2015 according to the Microsoft Update Catalog and Intel's web site has drivers from 2020 for this hardware, which will likely be better behaved. That said, Intel QSV of this era is known to have various quirks, so bumping to a more standard video resolution like 480p or 720p may be required.

**Comment by DeeDeeG** [comment]
> In Simple Output Mode, there is no way to directly select CQP or AVBR, it should be automatically set to CQP.

Yes, I relied on Simple Output Mode implicitly using **_CQP_** for the session you see in the log. _(Explicitly setting CQP or AVBR in Advanced Output Mode behaves the exact same as the Simple Mode scenario, exactly as reported above, on my machine.)_ I also tried setting recording to use the stream encoder vs setting recording to use a separate encoder, same results.

> Perhaps this is a quirk of older hardware on older drivers? I believe there should be a driver update available for that GPU. I would start by trying to update that.

> As mentioned above, your GPU driver version is from 2015 according to the Microsoft Update Catalog and Intel's web site has drivers from 2020 for this hardware, which will likely be better behaved.

I found the drivers on intel's website, installed them and restarted. (Version 10.18.10.5161 from 2020, marked as "latest" for my hardware on intel's website.) Results are once again exactly the same with the newer driver.

> As an aside, this appears to be Mac hardware running Windows. I'm not sure if QSV is expected to work in that scenario.

Yes, it is an intel Mac running Windows 10. I installed Windows 10 via Bootcamp, as is officially supported by Apple. (Docs: https://support.apple.com/HT201468) I can (anecdotally) say it's working really well for me. **_QSV works flawlessly for me at resolutions 20x20 and above, I've both streamed and recorded with it without any problems at all._** So, yeah, extrapolating from this, I'd say intel Macs that can install Windows 10 via Bootcamp should work quite well, at least based on my own experience with this machine.

It behaves just like any other decent intel-based Windows laptop of its year. In terms of the encoder situation, it's like any other Windows computer with an intel HD 4000 iGPU.

> That said, Intel QSV of this era is known to have various quirks, so bumping to a more standard video resolution like 480p or 720p may be required.

Wouldn't surprise me if there were quirks. So if this hardware is not top-of-the-top on the priority list, that does make sense to me, it is rather old at this point...

Yeah, outputting to a more normal resolutions is a perfectly fine workaround in my situation, where I'm just wanting to record my OBS audio setup to make sure it sounds good.

_**My ideal outcome for this issue, if possible, would be for OBS to recover gracefully from this situation, rather than how it hangs the recording currently,**_ which makes it unusable and un-exit-able until you realize you need to force quit it. Exiting the process via Task Manager is easy enough for me to do, since I know how to do it, but an error or warning would be helpful, and not hanging would especially help to not confuse the less tech-savvy folks out there.

I'm not great with C / C++ but if I somehow figured out how to fix this myself in a good way I'd happily post a PR... Best I can do for now is narrow down the Steps to Reproduce as much as possible and report it, as I've done above. Although maybe the title needs to be amended to say it's probably specific to older generations of intel QSV.
