### ISSUE TITLE
plugin linux : v4l2-controls not applied at OBS start, need open source properties manually

### ISSUE THREAD

**Issue by ludolpif** [obsproject/obs-studio#8946]
### Operating System Info

Other

### Other OS

Linux Debian testing (for bookworm release)

### OBS Studio Version

29.1.1

### OBS Studio Version (Other)

29.1.1 hand-compiled with CI/Build-linux.sh

### OBS Studio Log URL

https://obsproject.com/logs/IW5TksHYvxclOJhi

### Expected Behavior

At OBS start on a freshly booted system, a previously configured video source capture from a v4l2 device should apply to the camera the saved source properties.

### Current Behavior

It does not happens for me for most of them. The saved resolution is correctly used, but I think anything else is not set.
Example parameters that aren't set on camera as saved in OBS previously : power line at 50hz, white balance, zoom factor at 150%. 

Those parameters will be applied by OBS if I open the source properties of my webcam. I have nothing else to do except closing it. While doing that : source video stream is cut, logs show up for the first time with v4l2-controls INFO lines, the  source video stream start again, with right settings.

### Steps to Reproduce

1. Open OBS with a blank profile / settings and so 
2. Add a webcam source in a scene, set some source parameter like zoom (easy to spot if not set)
3. Close OBS
4. Open OBS
5. See in with main preview that the camera is not set to the previously configured zoom factor
6. Open camera's source properties
7. It's fixed without doing other actions
8. It will run fine by closing the properties

### Anything else we should know?

In attached log :
- At 18:31:52.544, the OBS is finishing it's start, capture begins without any v4l2-controls INFO lines. The captured image is "bad", no saved zoom, no saved white-balance, no power line freq at 50hz (and so on).
- At 18:31:55.428, I clicked on the source properties of my webcam, so it going to show up v4l2-controls INFO lines then the image capture is visually correct in the preview.

I am trying OBS 29.1 for incoming Debian 12. I compiled, made .deb, installed then started with those commands : 
```
(chroot)ludolpif@lud-5490:~$ git clone https://github.com/obsproject/obs-studio.git
(chroot)ludolpif@lud-5490:~$ cd obs-studio/
(chroot)ludolpif@lud-5490:~$ git checkout 29.1.1
(chroot)ludolpif@lud-5490:~$ CI/build-linux.sh
(chroot)ludolpif@lud-5490:~$ cmake --build build --target package
root@lud-5490:~# dpkg -i /home/chroot/home/ludolpif/obs-studio/build/obs-studio-29.1.1-13-Linux.deb
(Lecture de la base de données... 290639 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de .../obs-studio-29.1.1-13-Linux.deb ...
Dépaquetage de obs-studio (29.1.1-13) sur (29.1.0-12) ...
Paramétrage de obs-studio (29.1.1-13) ...
root@lud-5490:~# 
ludolpif@lud-5490:~$ obs --verbose
```

**Comment by kkartaltepe** [comment]
For now this is how it is intended to work, for people who depended on configuring these settings outside of obs.
