### ISSUE TITLE
VAAPI H.264 on CBR drops bitrate and framerate without overloading

### ISSUE THREAD

**Issue by physixcat** [obsproject/obs-studio#8956]
### Operating System Info

Other

### Other OS

Debian Sid

### OBS Studio Version

29.1.1

### OBS Studio Log URL

https://obsproject.com/logs/Ex1GULRcG3Fj2Tep

### Expected Behavior

Recording CBR @ 6000Kbps @ 60fps in a difficult-to-encode scene should drop its quality, but maintain the 60fps. Quality should return after a few moments of stillness. 

### Current Behavior

Recording CBR @ 6000Kbps @ 60fps in a difficult-to-encode scene results in quality plummeting and framerate slowing down to less than 1 FPS. Quality and FPS seemingly only return after 30 seconds of stillness or so.

### Steps to Reproduce

1. Record or stream using VAAPI H.264, CBR, 6000Kbps, 60fps, 1920x1080
2. Footage being captured should be difficult to encode, such as grass/vegetation in a videogame while moving fast, or the fireblu texture in Doom, for at least 10 seconds
3. Note usage of CPU/GPU during the process, finish recording, play back footage 

### Anything else we should know?

Flatpak OBS 28.1.2 (dated Nov 5th 2022) seems to be the last commit that still has the expected behavior. I tried Native 28.0.1, and had the same problem I'm describing in this issue. I can only suspect that this means the bug is being caused by a dependency, but I don't know which one.

**Comment by kkartaltepe** [comment]
You didnt provide a sample but probably you are affected but known issues in AMD's vaapi implementation. This has been fixed in the latest and as of yet unreleased mesa update. Wait until the next mesa update or roll back mesa until you find a working version, or use software encoding for the time being.

**Comment by physixcat** [comment]
Thank you, Debian Sid is currently on Mesa 22.3.6 so I'll have to stick it out until 23.x reaches us. For the time being I'll be using Flatpak OBS 28.1.2 as this is working well for now

Unsure if it's worth mentioning but CQP had no issues, apparently only CBR and VBR
