### ISSUE TITLE
Audio monitoring a source while outputting to Teams results in no audio.

### ISSUE THREAD

**Issue by nacalai** [obsproject/obs-studio#8957]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.1

### OBS Studio Log URL

Not relevant I believe

### Expected Behavior

It's a bit of a weird issue. I am also not entirely sure if posting as a bug on here is suitable, or even relevant to OBS, but perhaps it will shed some light on the weird problem.

Workflow: Send OBS audio -> Teams, by using for example virtual audio cable.

### Current Behavior

The problem is that if you monitor the same source via advanced audio settings, the sound to Teams is cut entirely. Turn off monitoring, and it plays just fine again. How come?

The audio that is sent out works just fine everywhere else; volume mixer, Zoom, other recording softwares. They all pick up the signal. It seem to only be isolated to Teams. As soon as monitoring is turned on, the sound is cut. It's just really strange.

A guy on reddit has the same issue. My colleague also has the same issue. He had used Zoom L8 digital mixer, while I am using the Audio Monitor plugin for OBS. So it seems not isolated to my hardware and workflow.

### Steps to Reproduce

1. Put "Audio Monitor" plugin on a media source. Select VBCable e as device.
2. Play the media source
3. Select the VBCable as mic in Teams
4. The audio will play just fine through
5. Enable monitoring on the source via advanced audio monitoring
6. The audio is now cut from Teams.

### Anything else we should know?

Again, no idea if this is directly related to OBS at all, but was hoping at least for a direction of what could be the cause.

**Comment by prgmitchell** [comment]
This sounds like a support issue, please head to the [OBS community discord](https://discord.com/invite/obsproject) or the [OBS Forums](https://obsproject.com/forum/) for support.
