### ISSUE TITLE
Low quality for Browser source

### ISSUE THREAD

**Issue by kevinpl07** [obsproject/obs-studio#8961]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.1

### OBS Studio Log URL

https://obsproject.com/logs/c5owiz7nDJndAOzO

### Expected Behavior

I added a Browser source where I'm watching a local WebRTC stream being drawn on a canvas.

### Current Behavior

When watching the WebRTC stream in my Chrome browser the quality and FPS are really good. In OBS Browser source its very bad. What's the reason for that and is there a way to improve that?

### Steps to Reproduce

1.add Browser source
2.set youtube video with high resolution as URL
3.
...

**Comment by gxalpha** [comment]
This issue appears to be a support request, for which we don't use GitHub Issues.
Please make sure to visit the support sections on our [Discord server](https://discord.gg/obsproject) or [Forums](https://obsproject.com/forum).

Thank you!
