### ISSUE TITLE
OBS sometimes crashes when switching scenes

### ISSUE THREAD

**Issue by iarspider** [obsproject/obs-studio#8962]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.1

### OBS Studio Log URL

https://obsproject.com/logs/jwEnra00prO3XET7

### OBS Studio Crash Log URL

https://obsproject.com/logs/UhgOy4TOau5Yd217

### Expected Behavior

Not crash

### Current Behavior

Sometimes OBS crashes when switching scenes with Transition set to Stinger

### Steps to Reproduce

1.
2.
3.
...

**Comment by notr1ch** [comment]
Should be fixed in https://github.com/obsproject/obs-studio/commit/a12d5812af59197ed36dd068abadf9b50d0295d5.

**Comment by iarspider** [comment]
Thanks!
