### ISSUE TITLE
Pipewire window capture not working with Radeon RX 7900 XTX

### ISSUE THREAD

**Issue by Tony-Klink** [obsproject/obs-studio#8965]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.1.1-tytan652-1

### OBS Studio Log URL

https://obsproject.com/logs/hYX4rziZgeVQ4Rnw

### Expected Behavior

The Pipewire screen capture (capture window or capture region) should be working.

### Current Behavior

With Radeon 7900 XTX screen capture (pipewire) is working when capturing entire screen, but when trying to capture specific window or region it shows up as a zero size object

### Steps to Reproduce

1.  Add new 'Screen Capture (PipeWire)' source
2. Select window from the list of available windows
3. Click OK

### Anything else we should know?

I use Hyprland with following packages:
xdg-desktop-portal 1.16.0-3
xdg-desktop-portal-hyprland-git 1:r283.4f0c575-1
qt5-wayland 5.15.9+kde+r55-1
qt6-wayland 6.5.0-2
pipewire 1:0.3.71-1
wireplumber 0.4.14-1
slurp 1.4.0-1

**Comment by kkartaltepe** [comment]
This is probably an issue with your xdg-desktop-portal implementation you should file against them. You can try checking against gnome/kde/wlr implementations and it should work.

**Comment by Tony-Klink** [comment]
I tried with wlr implementation - it only allows me to capture the screen. Option to capture window is missing from the picker menu. I'll try with gnome next

**Comment by RytoEX** [comment]
Related to #8170?

**Comment by kkartaltepe** [comment]
> Related to #8170?

Basically,  yea.

**Comment by Tony-Klink** [comment]
@RytoEX could be
In logs for `/usr/lib/xdg-desktop-portal-hyprland -l DEBUG` I see negative window handle. May be this causes the issue
```
2023/05/25 00:06:35 [INFO] - xdpw: screencast instance 0x558ece1718f0 has 1 references
2023/05/25 00:06:35 [INFO] - xdpw: 1 active screencast instances
2023/05/25 00:06:35 [INFO] - hyprland: window handle -838824752
2023/05/25 00:06:35 [DEBUG] - hyprland: toplevel handle created 558ece16ffb0
2023/05/25 00:06:35 [DEBUG] - hyprland: toplevel app_id com.obsproject.Studio
2023/05/25 00:06:35 [DEBUG] - hyprland: toplevel handle created 558ece170020
2023/05/25 00:06:35 [DEBUG] - hyprland: toplevel app_id hyprland-share-picker
2023/05/25 00:06:35 [DEBUG] - hyprland: toplevel closed hyprland-share-picker
2023/05/25 00:06:35 [INFO] - dbus: start method invoked
2023/05/25 00:06:35 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_126/obs3
2023/05/25 00:06:35 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_126/obs1
2023/05/25 00:06:35 [INFO] - dbus: app_id: 
2023/05/25 00:06:35 [INFO] - dbus: parent_window: 
2023/05/25 00:06:35 [DEBUG] - dbus: start: found matching session /org/freedesktop/portal/desktop/session/1_126/obs1
2023/05/25 00:06:35 [INFO] - wlroots: no modifiers available for format 0
2023/05/25 00:06:35 [INFO] - pipewire: stream state changed to "connecting"
2023/05/25 00:06:35 [INFO] - pipewire: node id is -1
2023/05/25 00:06:35 [INFO] - pipewire: stream state changed to "paused"
2023/05/25 00:06:35 [INFO] - pipewire: node id is 65
2023/05/25 00:06:35 [INFO] - xdph: registered restoreToken with token 7CA383DE-4654-482E-83AE-B4D6C22B2D8F
2023/05/25 00:06:35 [DEBUG] - dbus: start: returning node 65
2023/05/25 00:06:35 [INFO] - pipewire: stream state changed to "error"
2023/05/25 00:06:35 [INFO] - pipewire: node id is 65
```

**Comment by Tony-Klink** [comment]
Switched to GNOME, the problem has gone. The issue is not on the OBS Studio side. Thank you

**Comment by linuxmobile** [comment]
The issue is related to OBS version.. Check this comment. I change that lines and work fine again. Fix obs please: 
https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/58#issuecomment-1583110406

**Comment by kkartaltepe** [comment]
Duplicate of #9084, and as explained there it looks like an issue in your compositor.
