### ISSUE TITLE
OBS crashes every time they record video for more than 2 hours

### ISSUE THREAD

**Issue by Saber-CC** [obsproject/obs-studio#8967]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.1

### OBS Studio Log URL

https://obsproject.com/logs/Y6Ptc9M4ZHtskkQc

### OBS Studio Crash Log URL

https://obsproject.com/logs/e0ZFZ0bqWGsrXzpe

### Expected Behavior

OBS does not crash every time the video is recorded

### Current Behavior

When OBS records video for about 2 hours each time, the video stream will stop. If you click to close recording at this time, you will be stuck in the closing recording all the time. If you click to exit OBS, you cannot exit without any response. The strange thing is that this BUG happened only a few days ago, I have been using OBS without any problems before this problem occurred, during which time I did not change the OBS configuration or update the driver condition, so this problem is very strange

### Steps to Reproduce

1.Whenever I record a video, it crashes around 2 hours
2.
3.
...

**Comment by gxalpha** [comment]
Uninstall logi_obs_plugin. Also make sure to disable OBS integration in the Logitech app (not 100% sure about the name), otherwise it will reinstall the plugin.
