### ISSUE TITLE
My computer crashed and Blue screen of dealth

### ISSUE THREAD

**Issue by OldJERN8322** [obsproject/obs-studio#8968]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.1

### OBS Studio Log URL

https://obsproject.com/logs/pctdx3rqdWv2iSNZ

### OBS Studio Crash Log URL

Nothing for crashed. sorry

### Expected Behavior

Hey! this open OBS Studio but. who's did my computer BSoD many. (a lot.)
Also. im used this CPU: AMD Ryzen 5 4500 6-Core Processor 3.60 ~ 4.30 GHz
and GPU: Radeon RX550/550 Series
How can do this fixing that?

### Current Behavior

i don't know.

### Steps to Reproduce

1. Open this OBS studio
2. After this crashed my computer. **(on BSoD)**

**Comment by notr1ch** [comment]
This is more likely to be a support issue than a bug in OBS. Please use the forums or Discord for support.
