### ISSUE TITLE
Deinterlacing/Recording/playback issue on UTV007

### ISSUE THREAD

**Issue by Gomam0n-afk** [obsproject/obs-studio#8971]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.1

### OBS Studio Log URL

https://obsproject.com/logs/VeqSGatbdIuO0JOf

### Expected Behavior

Smooth motion during recording, playback and viewing an EasyCAP UTV007 capture card with deinterlacing on.

### Current Behavior

I've started at some point to get a "skipped frame" / jump every second while recording anything using my Easycap utv007 with all deinterlacing methods, even though it used to work fine a while ago. Pictured in the attached files is Linear 2x mode.
https://github.com/obsproject/obs-studio/assets/59240947/870da524-c3b4-44c1-96b5-63cd96037211
I'm also reporting a huge issue with Yadif 2x, which has never worked for me for as long as i remember, it jitters every frame like you would expect from the first field being the wrong one, even though i am 100% certain i am on the right setting (same as Linear 2x, Bottom field first.)
https://github.com/obsproject/obs-studio/assets/59240947/97a4e9e8-ae3e-46cd-b199-c30ef0896f98

Both of these issues are constant, happen in both the preview and final recording, and also do no happen using other recording/video processing software.  could use those, but as of now, OBS is the best all around for my usecase.

### Steps to Reproduce

1.Set your UTV007 as video capture device.
2.Set deinterlacing to any mode that does not discard half of the fields.

### Anything else we should know?

PC Config : i7-7700, GTX 1060 6gb, Win10 IoT Enterprise 22h2.
Codec used : NVENC H.264, VBR mode.
The correct (only ?) drivers are installed, i've tried reinstalling windows entirely already.
Video source is an original Xbox plugged into a VCR, used as a passthrough to the S-Video and audio input of my capture card, video format in example videos is PAL-60, but this issue also happens in NTSC and PAL-50 (didn't try SECAM)

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
