### ISSUE TITLE
OBS crash every time the video is recorded and living

### ISSUE THREAD

**Issue by Saber-CC** [obsproject/obs-studio#8974]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.0

### OBS Studio Log URL

https://obsproject.com/logs/tNb4e9BkOaUWuvF1

### Expected Behavior

OBS does not crash every time the video is recorded and living

### Current Behavior

Every time the OBS played and recorded, the video stream would suddenly stop after a while. If you click to close recording at this time, you will be stuck in the closing recording all the time. If you click to exit OBS, you cannot exit without any response. The strange thing is that this BUG happened only a few days ago, I have been using OBS without any problems before this problem occurred, during which time I did not change the OBS configuration or update the driver condition, so this problem is very strange, yesterday I also raised the issue ,but not uploading the correct log file, today the correct log file

### Steps to Reproduce

1.Whenever I recorded and living video

**Comment by RytoEX** [comment]
Please provide the OBS crash log.

**Comment by Saber-CC** [comment]
> Please provide the OBS crash log. Please also test in 29.1.1. We do not support versions older than the latest stable release.

no new crash log in the local obs-studio\crashe,The last crash log was two weeks ago. Sorry, maybe there is something wrong with my description. The crash may be caused by my forced exit, because my video stream stopped for unknown reasons and recording could not be restarted, so I had to forcibly exit OBS, leading to the crash

**Comment by Saber-CC** [comment]
> Please provide the OBS crash log. Please also test in 29.1.1. We do not support versions older than the latest stable release.

https://obsproject.com/logs/Jg27Vw7l4E6llXOs
This is the log I just tested for version 29.1.1
