### ISSUE TITLE
Stinger transitions linger on last frame.

### ISSUE THREAD

**Issue by Penwy** [obsproject/obs-studio#8981]
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

29.1.1

### OBS Studio Log URL

https://obsproject.com/logs/j8sG5Fkg7phh0vIP

### Expected Behavior

The last frame of a stinger transition should be shown for exactly as long as it's supposed to last.

### Current Behavior

The last frame instead lingers for much longer than it should. 
Recording at 60 fps a stinger at 60fps itself lasting for 1 second results in the last frame of the stinger lasting for 15 frames of the resulting video.
For an example :
[stinger used](https://cdn.discordapp.com/attachments/767069216011452450/1112158503130386592/stinger_test.mp4)
[resulting video](https://cdn.discordapp.com/attachments/767069216011452450/1112158502723526656/2023-05-28_01-07-49.mkv)

### Steps to Reproduce

1. Add a stinger transition whose last frame isn't fully transparent
2. Record a scene transition with it
3. Check the recording for lingering frames

### Anything else we should know?

Testing was done on linux here but also has been reproduced [on windows.](https://discord.com/channels/348973006581923840/374636015396192257/1112111833772466247)
As can be expected, this does not reproduce on 29.0.2.

**Comment by gxalpha** [comment]
Tested with multiple videos including the attached sample, can reproduce with all of them.

**Comment by Wiethoofd** [comment]
Same issue on Windows 10 and has been happening in all 29.1.x versions.

You can also see it in the preview of a stinger that it freezes on the last frame, loading to ram or not makes no difference.
![image](https://github.com/obsproject/obs-studio/assets/9917564/9cfd510d-7502-4f67-8d16-815be104b7e9)

**Comment by Penwy** [comment]
Just to have it here for anyone who finds this issue :
Until the issue is identified and resolved, the workaround is to add a fully transparent frame at the end of the stinger's video. It'll still freeze, but freeze on an invisible frame.

**Comment by ogmkp** [comment]
Any progress on this issue?

**Comment by SuslikV** [comment]
related thread on the forum (if someone still interested):
https://obsproject.com/forum/threads/stingers-pause-on-last-frame-before-switching-scenes-29-1-1-and-29-1.166575/

**Comment by Lain-B** [comment]
Should be fixed now. Thank you for reporting! And sorry it took an entire minor version for this to get fixed.

**Comment by Dydaser** [comment]
got this issue with version 29.1.3

**Comment by Lain-B** [comment]
It'll be fixed in 30

**Comment by gxalpha** [comment]
@Dydaser that's expected, it should be fixed in 30.0 though. Feel free to test the Beta.
