### ISSUE TITLE
capture card not showing up in obs just black screen

### ISSUE THREAD

**Issue by kamikazilucas** [obsproject/obs-studio#8999]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.2

### OBS Studio Log URL

https://obsproject.com/logs/6jxU89lO6BvBhwBp

### Expected Behavior

the capture card to show up 

### Current Behavior

couple days ago i was able to use capture card fine but now whenever i turn on obs its just a black screen

### Steps to Reproduce

1.turn on capture card
2. turn on obs
3.
... dosent work

**Comment by notr1ch** [comment]
This is more likely to be a support issue than a bug in OBS. Please use the forums or Discord for support.
