### ISSUE TITLE
Select service that needs to be "Show All", and it will not be displayed after saving.

### ISSUE THREAD

**Issue by TianQiBuTian** [obsproject/obs-studio#9000]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.2

### OBS Studio Log URL

https://obsproject.com/logs/xlA13mlN0xOwI6kO

### Expected Behavior

Display the selected service and server.

### Current Behavior

The service displays "custom" and the server displays blank.

### Steps to Reproduce

1. Select the services that require clicking on "Show All".
2. Save and close the settings window.
3. Reopen the stream settings page.

### Anything else we should know?

It will not happen to services that do not require clicking on "Show All" or "Custom".

https://github.com/obsproject/obs-studio/assets/26628474/64346ae8-b529-4ff8-914a-89b6f55ecdb7

**Comment by gxalpha** [comment]
Fixed by https://github.com/obsproject/obs-studio/pull/9068
