### ISSUE TITLE
unrecognized selector when adding a new video caputre device

### ISSUE THREAD

**Issue by Th3R3p0** [obsproject/obs-studio#9002]
### Operating System Info

macOS 13

### OBS Studio Version

29.1.2

### OBS Studio Log URL

https://gist.github.com/Th3R3p0/014fab25fd2baa1faa880a079e84439e

### Expected Behavior

When I attempt to add a new capture device, I expect OBS to not crash. 

### Current Behavior

OBS Crashes

### Steps to Reproduce

1. Open OBS
2. Click "+" in Sources
3. Click "Video Capture Device"

### Anything else we should know?

This is my first time using OBS. I was running a previous version of OSX when I saw the error. I upgraded OSX to the latest version and I still saw the error. 

I have not installed any 3rd party plugins.

I have 3 cameras attached (built-in webcam, external webcam, and a Sony camera). I have disconnected all USB devices to eliminate any issues that may cause.

I have tried downgrading to version 29.0.2 and the same error occurs.

The stacktrace is not displayed 100% of the time. I would say 1 in 4 times. However, the app crashes 100% of the time when I follow my reproduction steps. 

The log file attached is from iterm because when when I upload the log through the app, the stack trace isn't showing. This may be due to the reproduction of the stack trace I mentioned above.

**Comment by Th3R3p0** [comment]
@gxalpha I had one generated today in `~/Library/Logs/DiagnosticReports/`. [Here is the log file](https://gist.github.com/Th3R3p0/802a7c255193e73f09c1a2dbf0106cb0)

**Comment by Th3R3p0** [comment]
There was one directory named `RelayCam.plugin` in that directory. Once I removed the directory, it started working. Interestingly, it seems that it is [related](https://bugs.chromium.org/p/chromium/issues/detail?id=1379392) to Chrome not being able to load the webcams.

**Comment by gxalpha** [comment]
Seems like this is fixed, I'll close the issue then. There is nothing we can do about DAL plugins crashing us.
Although they will stop working entirely in macOS 14, so if others still run into this problem it will solve itself.
