### ISSUE TITLE
Blank output for screen and selected Windows

### ISSUE THREAD

**Issue by coreybruce** [obsproject/obs-studio#9005]
### Operating System Info

Other

### Other OS

Manjaro

### OBS Studio Version

29.1.2

### OBS Studio Log URL

https://obsproject.com/logs/ea9wFTgkxEw8ED0O

### Expected Behavior

Select your screen and window should show a output  

### Current Behavior

Shows a blank screen when you select either windows or screen instead of showing an output

![image](https://github.com/obsproject/obs-studio/assets/8393780/85e0e31d-68b4-4c26-9bfb-513cd617b1f2)

### Steps to Reproduce

1. Select a screen or Window.
...

### Anything else we should know?

- Manjaro Gnome 43.5
- Ryzen 5700G
- RX 6700XT
- Mesa 23.03-1
- Wayland
- OBS flatpak

**Comment by gmankab** [comment]
install `pipewire` package

**Comment by coreybruce** [comment]
> install `pipewire` package

pipewire is already installed, any other suggestions?
![image](https://github.com/obsproject/obs-studio/assets/8393780/c0eadea4-4b39-4629-b037-61017bde1554)

**Comment by gmankab** [comment]
if pipewire installed, and pc restarted, then no other suggestions :)

**Comment by coreybruce** [comment]
Damn that's a shame, I really this to be fixed so I can us use OBS :(

**Comment by RytoEX** [comment]
Related to #8170 ?

**Comment by coreybruce** [comment]
Hmm might be but I'm not 100% sure

**Comment by coreybruce** [comment]
I figured out what the issue is, OBS requires pipewire audio to work, not just pipewire but also manjaro-pipewire

**Comment by gxalpha** [comment]
Closing per the above comment
