### ISSUE TITLE
OBS ( 28.1.2 - 29.1.2 ] with Intel QSV Stopping Recording...

### ISSUE THREAD

**Issue by 20ND** [obsproject/obs-studio#9010]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

28.1.2 - 29.1.2

### OBS Studio Log URL

https://youtu.be/qsi0CxZ8QkI 28.1.2 to 29.1.1https://youtu.be/Lc97IuOL2Sw 29.2.2

### Expected Behavior

https://youtu.be/Lc97IuOL2Sw 29.2.2

### Current Behavior

Stopping Recording...
and
Crash ( only 29.0.2 )

### Steps to Reproduce

1. OBS ( 28.1.2 - 29.1.2 ]
2. ~Intel Gen 12.2 Alder
3. Change encoder settings while recording

### Anything else we should know?

CBR, VCM - Ok
VBR, ICQ - Not Ok

**Comment by RytoEX** [comment]
Please provide OBS Studio logs for when it worked and when it did not work.

**Comment by gxalpha** [comment]
No log has been provided.
