### ISSUE TITLE
Version Consistency?

### ISSUE THREAD

**Issue by jiapei100** [obsproject/obs-studio#9012]
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

29.1.2

### OBS Studio Log URL

26.0.0-4136-g7cd7ca80f

### Expected Behavior

What's displayed on top of the GUI should be 29.1.2, rather than 26.0.0 ??

### Current Behavior

For me, the version consistency has some problem. They are of different version numbers.

### Steps to Reproduce

1. Just have it installed.
2. And run it 
3.
...

**Comment by norihiro** [comment]
Have you installed the official obs-studio via the PPA? You need to configure APT and install from obsproject's obs-studio to get the latest version.

```sh
sudo add-apt-repository ppa:obsproject/obs-studio
sudo apt update
sudo apt install ffmpeg obs-studio
```

**Comment by derrod** [comment]
The version is based on `git describe`'s output, if you haven't fet hed tags in a while it will be outdated.
