### ISSUE TITLE
About getting source width and height

### ISSUE THREAD

**Issue by lijialin9** [obsproject/obs-studio#9033]
### Operating System Info

Windows 11

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.1.1

### OBS Studio Log URL

No

### Expected Behavior

In window-capture,I want to get width and height.
I use the following API:
```
source_width = obs_source_get_width(my_source);
source_height = obs_source_get_height(my_source); 
```
But return 0!
I created the source using the default Settings.
And just specify the window.
I looked at the code and found : 
**The width and height are set only in the function "video_tick" , this seems unreasonable.**
**I can't find any way to call it in the public API**
monitor-capture working properly！

### Current Behavior

No

### Steps to Reproduce

1.
2.
3.
...

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
