### ISSUE TITLE
Please revert commit 27dc30b67220317ea6d419c2e361f26a93cf577e.

### ISSUE THREAD

**Issue by cmdremily** [obsproject/obs-studio#9035]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.2

### OBS Studio Log URL

N/A

### Expected Behavior

I expect the stream to be output as I have configured it to be, so that it can be tonemapped to SDR by by proxy before being pushed to twitch.  I want to do this as a work around until https://ideas.obsproject.com/posts/2105/ability-to-stream-in-sdr-but-record-in-hdr is implemented so that I can upload the local recordings in 10bit HDR to YouTube later.

### Current Behavior

"HDR output is currently disabled for this output".

### Steps to Reproduce

1. Setup NGINX RTMP proxy to tonemap and re-stream incomming RTMP stream from OBS.
2. Start streaming in OBS with NVENC_HEVC as stream encoder with HDR output configured.

Note that NVENC_H264 also only supports 8 bit, so there's no way of recording/streaming 10 bit HDR at this point as far as I can tell.

### Anything else we should know?

This issue is caused by the arbitratry limitations put in place by commit 27dc30b67220317ea6d419c2e361f26a93cf577e, and would be fixed by rolling it back.

**Comment by Penwy** [comment]
Out of curiosity, why aren't you using HLS rather than RTMP?

**Comment by tt2468** [comment]
NGINX RTMP doesn't support HEVC (no ERTMP support). I don't believe reverting that commit would help at all, you'd just be left with a broken RTMP stream anyway.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support or feature request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by cmdremily** [comment]
> Out of curiosity, why aren't you using HLS rather than RTMP?

@Penwy I went with the thing I knew for a start to see if I could get something working at all. Probably switch once I can get OBS to output a 10bit HDR stream. Right now you can only use Rec 2100 with a 10 bit colour format. But x264 and nvenc_h264 can only output 8 bit colour in OBS, and the above commit prevents streaming Rec 2100 in any format but h264. 

So it seems like HDR streaming is effectively broken. 🤷🏻

**Comment by cmdremily** [comment]
@Fenrirthviti please consider re-opening this bug as it's not a feature request (I want to use existing features that were disabled for some reason), and it's not a support request (I'm not asking for help, I know how to do the things, I'm asking that the existing functionality be re-enabled).

**Comment by Fenrirthviti** [comment]
We are not currently prepared to support this workflow. This is intentional and we will not be reverting it for now. You may build locally to remove this restriction if you want, but this is effectively a feature request as there was never a build that actually supported it. AV1/HEVC streaming and this restriction were added at the same time.
