### ISSUE TITLE
“ui_output.h”: No such file or directory

### ISSUE THREAD

**Issue by chentiannan** [obsproject/obs-studio#9038]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.2

### OBS Studio Log URL

“ui_output.h”: No such file or directory

### Expected Behavior

Compilation successful

### Current Behavior

Using the dependencies of cmake and qt6, vs2022 will not compile the. ui file during compilation, resulting in the generated ui_ Xxx header file not found

### Steps to Reproduce

1.
2.
3.
...

**Comment by Fenrirthviti** [comment]
Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance building OBS.

Make sure you've read our [build directions](https://obsproject.com/wiki/build-instructions-for-windows) first.

Thank you!
