### ISSUE TITLE
Program and Preview are incorrectly sized and obstruct other interface elements

### ISSUE THREAD

**Issue by trader-crows** [obsproject/obs-studio#9050]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.2

### OBS Studio Log URL

https://obsproject.com/logs/EOnIcTy0cOOx0hRt

### Expected Behavior

I expected to see a preview and program view that shows the full view of each scene.

### Current Behavior

The "Program" and "Preview" viewport are cropped and also show duplicates of other interface elements where I would expect there to be video feeds. The "Program" and "Preview" also obstruct other interface elements as seen in the attached screenshot

![Screenshot 2023-06-09 123559](https://github.com/obsproject/obs-studio/assets/1766619/0685a31b-b258-4ab9-9ab4-be541da3257f)

### Steps to Reproduce

1. Open OBS Studio after a fresh install, either in studio mode or not.
2. ???
3. Issue observed.

**Comment by trader-crows** [comment]
On further inspection of the log file, OBS Studio appears to be detecting the wrong resolution for my monitor. Its native resolution is 2560x1440, as set in Windows and indicated by the manufacturer. OBS Studio seems to think it's a 2048x1152 display. Not sure if relevant, but something I noticed.

**Comment by RytoEX** [comment]
2048x1152 is exactly 0.8 * 2560x1440. I'd guess that there's some kind of display scaling going on, despite Windows telling us otherwise. That OBS/Qt thinks there is no display scaling occurring is probably causing the mismatch.

**Comment by trader-crows** [comment]
> 2048x1152 is exactly 0.8 * 2560x1440. I'd guess that there's some kind of display scaling going on, despite Windows telling us otherwise. That OBS/Qt thinks there is no display scaling occurring is probably causing the mismatch.

Ah ha! It was the text scaling in windows that made it go wonky. Bit of a shame, as it didn't used to cause me any problems. 😢
