### ISSUE TITLE
"Blocked Files Downloaded from Internet" Causes OBS Scenes Referencing Blocked File to Hang and Interrupts Stream

### ISSUE THREAD

**Issue by kyledmoore** [obsproject/obs-studio#9051]
### Operating System Info

Windows 11

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/gcCVDswSy0Ke1Bs7

### Expected Behavior

If access to a file referenced in a source is blocked by the OS, that element should not show up rather than the entire scene transition hanging and crashing the stream.

I'm not sure if the "previous log" I shared reflects the situation as I restarted OBS a couple of times since.  I had downloaded an image of another streamer from a website and didn't realize Windows had introduced this new feature and while it added the file to the source fine, when I then later went to access the scene it appears the OS did something to block it.  I only noticed later that the checkbox on the file properties had the "This file came from another computer and might be blocked to help protect this computer" setting checked.  

Initially I thought it was an issue w/ the network share to my NAS disconnecting, but I have a ton of other resources on there referenced in various scenes and I could recreate it w/ this particular scene very easily.  When I opened the file in a Windows Explorer window outside of OBS, file explorer also would hang for a second (maybe it is virus scanning the file, not sure), but then it eventually opened and whatever file lock or what have you seemed to get released and OBS then opened the scene.

In any event, I suspect there is some error handling surrounding image sources or sources in general that could possibly be improved generally to prevent this type of file access problem from interrupting scene changes and the stream.

### Current Behavior

Upon changing to a scene with an image source referencing a jpg file w/ the "this file came from another computer and might be blocked to help protect this computer" setting present, the transition hangs, the current scene remains on screen, OBS becomes unresponsive and the stream output is interrupted.

### Steps to Reproduce

1. Download an image file from a webpage on a Windows 11 machine where the group policy for this has not been disabled (see  [this article](https://www.elevenforum.com/t/enable-or-disable-block-files-downloaded-from-internet-in-windows-11.1128/)).
2. Reference this file on an image source within a scene.
3. Close all other applications referencing this file, which may have resulted in a prompt to allow viewing of the file and some kind of temporary white listing by the OS
4. Attempt to change to that scene, observe if OS blocks it that OBS hangs and stream interrupts

### Anything else we should know?

I have not attempted to recreate on current release.

**Comment by notr1ch** [comment]
The zone identifier is ignored by OBS, this is only used by Windows Explorer and a few other apps. The real problem seems to be a bunch of image files you're using that are corrupt, perhaps in a slideshow source.

```
19:31:30.799: error:   Invalid PNG signature 0x5160700020000.
19:31:30.801: warning: Could not find codec parameters for stream 0 (Video: png, none(pc)): unspecified size
19:31:30.801: Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
19:31:30.801: error:   Invalid PNG signature 0x5160700020000.
19:31:30.801: Failed to decode frame for 'Z:/projects/kull/gsg-art/._753260872209530961.png': Invalid data found when processing input
19:31:30.809: WIC: Failed to create IWICBitmapDecoder from file: Z:/projects/kull/gsg-art/._753260872209530961.png
19:31:30.809: gs_image_file_init_internal: Failed to load file 'Z:/projects/kull/gsg-art/._753260872209530961.png'
19:31:30.809: [image_source: '(null)'] failed to load texture 'Z:/projects/kull/gsg-art/._753260872209530961.png'
19:31:30.823: error:   Invalid PNG signature 0x5160700020000.
19:31:30.825: warning: Could not find codec parameters for stream 0 (Video: png, none(pc)): unspecified size
19:31:30.825: Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
19:31:30.825: error:   Invalid PNG signature 0x5160700020000.
19:31:30.825: Failed to decode frame for 'Z:/projects/kull/gsg-art/._753261006205223052.png': Invalid data found when processing input
19:31:30.828: WIC: Failed to create IWICBitmapDecoder from file: Z:/projects/kull/gsg-art/._753261006205223052.png
19:31:30.828: gs_image_file_init_internal: Failed to load file 'Z:/projects/kull/gsg-art/._753261006205223052.png'
19:31:30.828: [image_source: '(null)'] failed to load texture 'Z:/projects/kull/gsg-art/._753261006205223052.png'
19:31:30.839: error:   Invalid PNG signature 0x5160700020000.
19:31:30.841: warning: Could not find codec parameters for stream 0 (Video: png, none(pc)): unspecified size
19:31:30.841: Consider increasing the value for the 'analyzeduration' (0) and 'probesize' (5000000) options
19:31:30.841: error:   Invalid PNG signature 0x5160700020000.
19:31:30.841: Failed to decode frame for 'Z:/projects/kull/gsg-art/._753261668997267487.png': Invalid data found when processing input
19:31:30.844: WIC: Failed to create IWICBitmapDecoder from file: Z:/projects/kull/gsg-art/._753261668997267487.png
19:31:30.844: gs_image_file_init_internal: Failed to load file 'Z:/projects/kull/gsg-art/._753261668997267487.png'
19:31:30.844: [image_source: '(null)'] failed to load texture 'Z:/projects/kull/gsg-art/._753261668997267487.png'
19:31:30.850: error:   Invalid PNG signature 0x5160700020000.
```
Try deleting these .files which look like temporary / trash files.

**Comment by kyledmoore** [comment]
That's not the scene in question, sorry.  The scene I'm referring to doesn't have a slideshow source.

**Comment by notr1ch** [comment]
I'd suggest using a local copy of the file as the network drive likely isn't helping things. In any case this doesn't sound like a bug in OBS as we don't process zone identifiers or really do anything other than ask the OS to open the file, if that process is hanging then it's outside of OBS' control. I'd suggest posting on the forums or Discord if you need further support.

**Comment by kyledmoore** [comment]
I just have a much higher standard of quality around file handling I suppose.  Having the file load in its own thread or something and letting the scene load after a short timeout w/ a "file not found" would be much better for user than the thing becoming unresponsive and stream output ending when there is an issue w/ a single file, regardless of where it is located.
