### ISSUE TITLE
NVIDIA Noise suppression corrupts audio channel and crashes OBS

### ISSUE THREAD

**Issue by Jookia** [obsproject/obs-studio#9064]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.1.1

### OBS Studio Log URL

https://obsproject.com/logs/ys8v94H819LocnPC

### OBS Studio Crash Log URL

https://obsproject.com/forum/attachments/crash_2023-05-26_17-31-19-txt.94741/

### Expected Behavior

Streaming with NVIDIA Noise suppression should suppress noise.

### Current Behavior

During a stream my friend found one of his audio channels was completely gone, but it would only happen sometimes. After a while troubleshooting we found that disabling NVIDIA Noise suppression this fixes the issue instantly. Re-enabling it once or twice manages to crash OBS. Crash and OBS log attached.

### Steps to Reproduce

1. Enable NVIDIA Noise suppression
2. Restart OBS or steam long enough
3. Find an audio channel is missing
4. Add or remove the NVIDIA Noise suppression until it crashes

**Comment by energizerfellow** [comment]
Update your Nvidia GPU drivers to the latest Studio Driver release and see if the behavior changes or goes away.

**Comment by theHamsta** [comment]
Check whether you have hardware scheduling enabled (also possible to enable on Windows 10, it's just not the default). 29.1.2 has a work-around for a hardware-scheduling related issue.

**Comment by gxalpha** [comment]
@Jookia please see the above comments regarding out-of-date drivers and OBS as well as HAGS.

**Comment by gxalpha** [comment]
Given that there has been no response on this, as-is this issue unfortunately is not actionable for us.
