### ISSUE TITLE
Window Capture experiences periodic stuttering when a Window Portal has been shared

### ISSUE THREAD

**Issue by deadmeu** [obsproject/obs-studio#9070]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

29.1.2

### OBS Studio Version (Other)

Flatpak

### OBS Studio Log URL

https://obsproject.com/logs/ImHm40OqaOaFNWBM

### Expected Behavior

Window Capture should not have periodic stuttering when a Window is being captured.

### Current Behavior

Using a Window Capture source, when a portal is shared with OBS I begin to experience stuttering every second. If I open OBS and no portal is shared (and the sharing popup opens) I do not experience any stuttering.

### Steps to Reproduce

1. Create a Window Capture source
2. Select a window to share from the Screen Sharing Portal and share it
3. Observe a periodic lag spike occurring every second

### Anything else we should know?

This seems to be a Flatpak/Wayland issue and could potentially be an issue with the portal provider (although I don't know much about that) rather than with OBS.

Additionally, it seems like if I have OBS running for a while without sharing a window, or by changing the shared window, it sometimes seems to fix the issue and the stuttering stops even while the window is being shared (though I cannot reliably reproduce this). Restarting OBS causes the stutter to begin once again.

**Comment by GeorgesStavracas** [comment]
It's not entirely clear from this issue *what* is stuttering. Is it OBS Studio that sttutters? Is it your stream? Or is it your entire desktop?

**Comment by GeorgesStavracas** [comment]
Thanks. It's clear from the recordings that your entire desktop is lagging, that's very likely to be a problem in your compositor (seems like it's KDE's kwin? ). OBS Studio does not influence the performance of the compositor, it merely requests a screencast and receives the frames. There is nothing we can do about it on OBS Studio side. Please report this to your desktop environment.

**Comment by tobyg0** [comment]
@deadmeu Did you create a bug in the KDE bug tracker as I'm running into this issue myself.
