### ISSUE TITLE
Font Outline Bug

### ISSUE THREAD

**Issue by totoygamingyt** [obsproject/obs-studio#9073]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.2

### OBS Studio Log URL

https://obsproject.com/logs/zY5nwM2xIjYvXod9

### Expected Behavior

The text should show a Normal Outline.

### Current Behavior

![obs64_IHpkpw9LXz](https://github.com/obsproject/obs-studio/assets/72244878/b52dc3cd-94a2-4672-a47e-e3e1fac95899)

The outline looks awful.

### Steps to Reproduce

1. Open OBS Studio
2. Create a Text (GDI+) Source
3. Add a Word or Text
4. Scroll down, and Add an outline
5. Set the outline size to 20
6. Change the outline color to Black

**Comment by totoygamingyt** [comment]
Note: I tried to switch fonts, Bring the outline to 1 or random outline size, Tried restarting.

**Comment by Fenrirthviti** [comment]
Likely a duplicate of https://github.com/obsproject/obs-studio/issues/2415

**Comment by totoygamingyt** [comment]
> Likely a duplicate of #2415

I can't find any solution on #2415 :(

**Comment by kkartaltepe** [comment]
To me this looks like it may just be a poorly designed font. There are several rules font authors must follow to ensure that things like outlining work well in addition to just pure letter forms, this font is probably only authored to support pure letter forms.

It could still definitely be related to 2415, but someone with fonts would need to test the various rendering settings and make a PR.

**Comment by totoygamingyt** [comment]
I found the fix for the issue, Previously I am using a font from Google Fonts, I tried downloading the same font in other website, and it works. Idk if I did something wrong with the google fonts, but i can say this is Fixed now. Thanks for help!
