### ISSUE TITLE
can it support live for several scenes at the same time

### ISSUE THREAD

**Issue by lubibama** [obsproject/obs-studio#9082]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.2

### OBS Studio Log URL

feature suggest

### Expected Behavior

I have this use case，I build several scenes ，when i press the start live button，I want to live these scenes at the same time，not the selected one only. I can achieve this goal by start several obs.exe to live  separately，but this is not a good way I think

### Current Behavior

the obs can live for only one scene,when i switch the scene,the live data switched

### Steps to Reproduce

not bug

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
