### ISSUE TITLE
error: cast to 'OS_THREAD_ROUTINE' (aka 'void *') from smaller integer type 'int' 

### ISSUE THREAD

**Issue by yurivict** [obsproject/obs-studio#9105]
### Operating System Info

Other

### Other OS

FreeBSD

### OBS Studio Version

29.1.2

### OBS Studio Log URL

n/a

### Expected Behavior

successful build

### Current Behavior

```
/usr/ports/multimedia/obs-studio/work/obs-studio-29.1.2/plugins/obs-outputs/ftl-sdk/libftl/ingest.c:338:10: error: cast to 'OS_THREAD_ROUTINE' (aka 'void *') from smaller integer type 'int' [-Werror,-Wint-to-void-pointer-cast]
  return (OS_THREAD_ROUTINE)total_ingest_cnt;
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

### Steps to Reproduce

Regular build

### Anything else we should know?

clang-15

**Comment by PatTheMav** [comment]
Can confirm, it's an issue specifically with Clang 15.0.0 which elevated some warnings to errors:

https://releases.llvm.org/15.0.0/tools/clang/docs/ReleaseNotes.html#improvements-to-clang-s-diagnostics

Alas the FTL SDK is quite dead and we pull it in via git submodule, so disabling FTL when Clang is used is the only "clean" way to fix this.

**Comment by aet** [comment]
Standard OBS/libftl doesn't do any casting with total_ingest_cnt, is FreeBSD ports system applying some patches already to this part of the source tree and build system?

I don't think OBS is using the libftl project settings from ftl-sdk's CMake at all, but instead uses the rules from plugins/obs-outputs/cmake/{ftl.cmake,legacy.cmake}, including some -Wno-errors for clang.

I'd prefer OBS to be willing to consider changing the ftl-sdk repo used to someone who's willing to maintain it for a bit (I can volunteer, though personally I would suggest @haydenmc with some existing visible history), but adding an extra -Wno-int-to-void-pointer-cast to existing list of workarounds shouldn't be a big deal

**Comment by yurivict** [comment]
This is indeed caused by the FreeBSD port's patch.

Sorry for the disturbance.

**Comment by PatTheMav** [comment]
> I'd prefer OBS to be willing to consider changing the ftl-sdk repo used to someone who's willing to maintain it for a bit (I can volunteer, though personally I would suggest @haydenmc with some existing visible history), but adding an extra -Wno-int-to-void-pointer-cast to existing list of workarounds shouldn't be a big deal

That will not work, as I explained. It’s not a warning anymore in Clang 15.0.0, it’s an actual error.

**Comment by aet** [comment]
Ah, overlooked at the message, sorry about that. I suppose -Wno-error=int-to-void-pointer-cast exists to turn it into warning.

**Comment by PatTheMav** [comment]
> Ah, overlooked at the message, sorry about that. I suppose -Wno-error=int-to-void-pointer-cast exists to turn it into warning, or use of an equivalent flag.

That is incorrect: `-Wno-error` just reverts a specific elevation of all warnings to errors via `-Werror`, you cannot turn errors into warnings. Such a feature would be entirely antithetical to the idea of compiler errors, which tell you explicitly "this is wrong code, it will not work, change your code".

(There are very specific warnings that do differentiate between a warning case and an actual error case, where the `-Wno-error` switch allows one to disable the error case, but I'm only aware of `-Wno-changes-meaning` in GCC behaving that way).

**Comment by haydenmc** [comment]
> I'd prefer OBS to be willing to consider changing the ftl-sdk repo used to someone who's willing to maintain it for a bit (I can volunteer, though personally I would suggest @haydenmc with some existing visible history), but adding an extra -Wno-int-to-void-pointer-cast to existing list of workarounds shouldn't be a big deal

Happy to help consult/review PRs - we do have a _slightly_ more active ftl-sdk fork here: https://github.com/Glimesh/ftl-sdk, but I can't commit very much time beyond that. FWIW, Glimesh is shutting down in just over a week, but it sounds like this is a "life support" situation that only needs to last another 9 months or so, and I don't think the repos are going anywhere (@clone1018 fyi).

**Comment by aet** [comment]
@PatTheMav I checked the Clang release notes at https://releases.llvm.org/15.0.0/tools/clang/docs/ReleaseNotes.html#improvements-to-clang-s-diagnostics and found this bit explicitly mentioned:
```
The -Wint-conversion warning diagnostic for implicit int <-> pointer conversions now defaults to an error in all C language modes. It may be downgraded to a warning with -Wno-error=int-conversion, or disabled entirely with -Wno-int-conversion.
```

I think my usual compilers between various OS's are still 14 or older but was curious to check it in practise.

OBS seems to build with -Werror -Wextra by default but seems the int-to-void-pointer-cast behavior didn't change by default when moving on from 14.x to 15.x and both -Wno-error=int-to-void-pointer-cast and -Wno-int-to-void-pointer-cast would get the issue worked around.

```
% cat test.c 
// Stripped down testcase from clang
#include <stdint.h>

int main(int argc, char **argv)
{
  int foo = 0;
  void *bar = foo;
  (void) (void *) foo;
  return 0;
}
% clang-14 --version | grep version
clang version 14.0.6
% clang-14 test.c -o test
test.c:7:8: warning: incompatible integer to pointer conversion initializing 'void *' with an expression of type 'int' [-Wint-conversion]
        void *bar = foo;
              ^     ~~~
test.c:8:9: warning: cast to 'void *' from smaller integer type 'int' [-Wint-to-void-pointer-cast]
        (void) (void *) foo;
               ^~~~~~~~~~~~
2 warnings generated.
% clang-15 --version | grep version
clang version 15.0.7
% clang-15 test.c -o test         
test.c:7:8: error: incompatible integer to pointer conversion initializing 'void *' with an expression of type 'int' [-Wint-conversion]
        void *bar = foo;
              ^     ~~~
test.c:8:9: warning: cast to 'void *' from smaller integer type 'int' [-Wint-to-void-pointer-cast]
        (void) (void *) foo;
               ^~~~~~~~~~~~
1 warning and 1 error generated.
% clang-15 test.c -o test -Wno-error=int-conversion
test.c:7:8: warning: incompatible integer to pointer conversion initializing 'void *' with an expression of type 'int' [-Wint-conversion]
        void *bar = foo;
              ^     ~~~
test.c:8:9: warning: cast to 'void *' from smaller integer type 'int' [-Wint-to-void-pointer-cast]
        (void) (void *) foo;
               ^~~~~~~~~~~~
2 warnings generated.
% clang-15 test.c -o test  -Wno-int-conversion     
test.c:8:9: warning: cast to 'void *' from smaller integer type 'int' [-Wint-to-void-pointer-cast]
        (void) (void *) foo;
               ^~~~~~~~~~~~
1 warning generated.
% clang-15 test.c -o test  -Wno-int-conversion -Werror
test.c:8:9: error: cast to 'void *' from smaller integer type 'int' [-Werror,-Wint-to-void-pointer-cast]
        (void) (void *) foo;
               ^~~~~~~~~~~~
1 error generated.
% clang-15 test.c -o test  -Wno-int-conversion -Werror -Wno-error=int-to-void-pointer-cast
test.c:8:9: warning: cast to 'void *' from smaller integer type 'int' [-Wint-to-void-pointer-cast]
        (void) (void *) foo;
               ^~~~~~~~~~~~
1 warning generated.
% clang-15 test.c -o test  -Wno-int-conversion -Werror -Wno-int-to-void-pointer-cast 
```

**Comment by PatTheMav** [comment]
Interesting, so they chose to enable this behaviour for that specific error as well - the more you know.
