### ISSUE TITLE
Running OBS while Windows Subsystem for Android is running / active BSODs system

### ISSUE THREAD

**Issue by Blue018Phoenix** [obsproject/obs-studio#9109]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.2

### OBS Studio Log URL

N/A

### Expected Behavior

OBS should run fine, which it does for like a second before the device its running on locks up before showing a BSOD

### Current Behavior

PC Locks up as soon as OBS is run (While WSA is running, be it in the background or as a service), and crashes completely to a BSOD

### Steps to Reproduce

1. Install WSA, launch WSA and do whatever with it
2. Launch OBS
3. PC performance drops drastically, with web apps freezing up first
4. PC crashes to a BSOD

### Anything else we should know?

_This could either be an issue with OBS or WSA, but its hard to tell from just event logs_

**Comment by WizardCM** [comment]
This is most likely a GPU driver issue, but without additional information (such as an OBS log file and the BSOD error code) this ticket is not actionable.

I personally don't run into any issues with OBS + WSA running, on either Windows 10 or 11.

**Comment by Blue018Phoenix** [comment]
Prolly an issue on my end then, or with WSA

**Comment by Blue018Phoenix** [comment]
The odd thing about this is that the crash is so bad that windows cant even create a crash log, although checking the reliability log shows that it was a LiveKernelEvent Code 141, Its prolly an issue on my end though
