### ISSUE TITLE
Set the preview resolution to the size of the capture window, and the picture quality is much worse than that of the capture window

### ISSUE THREAD

**Issue by qq88797833** [obsproject/obs-studio#9111]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.2

### OBS Studio Log URL

https://obsproject.com/help

### Expected Behavior

![image](https://github.com/obsproject/obs-studio/assets/28855943/bf3bea2e-429b-41de-94bc-c682a485cf42)

### Current Behavior

Set the preview resolution to the size of the capture window, and the picture quality is much worse than that of the capture window

### Steps to Reproduce

1. capture window
2. Preview resolution Settings window size
![image](https://github.com/obsproject/obs-studio/assets/28855943/f64cbd55-56d7-4186-9a9e-e210a3dea831)
4.The obs preview is not as good as the source window

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
