### ISSUE TITLE
Replay buffer and sleep / hibernate mode

### ISSUE THREAD

**Issue by Senliast** [obsproject/obs-studio#9117]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.2

### OBS Studio Log URL

https://obsproject.com/logs/jg7DTr5TOEBfsFyC

### Expected Behavior

OBS should stop replay buffer / on hibernate / sleep mode enter and relauch it after the PC exit the hibernate / sleep mode, if it was running.

### Current Behavior

OBS prevents the PC from entering sleep mode when replay buffer is on. If the PC enter hibernate mode and then exits it - replay buffer hangs and doesnt record anything and cannot be stopped normaly anymore. OBS needs to be killed via Task Manager.

### Steps to Reproduce

1. Start replay buffer
2. Try to put the PC into sleep mode - it will not work, the PC will continue running
3. Try to put the PC into hibernate mode and the turn it on again - the replay buffer will hang and not record anything

### Anything else we should know?

I would like to use OBS as Instant Replay alternative - because nVidia Instant Replay is unreliable and disables by itself often, when i need it and it doesnt recognize all games as games and therefore doesnt record them. To start and stop Replay Buffer or Instant Replay manually every time i am playing a game is not as comfortable and you could forget to do it the moment you need it. Therefore it would be great if you would optimize it for the sleep / hibernate mode so that it disables the replay buffer and then re-enables, once the PC is awake again. Thank you in advance!

**Comment by Fenrirthviti** [comment]
Putting the PC to sleep or hibernating while OBS is running is not supported.
