### ISSUE TITLE
OBS Virtual Camera crashes Discord when resizing in OBS

### ISSUE THREAD

**Issue by xudonax** [obsproject/obs-studio#9119]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/mvixiwB36PFOOHmv

### Expected Behavior

Discord (Stable 206653 (baa744e), Host 1.0.9013 (33666)) is able to use the camera when OBS is resizing from 1920x1080 (canvas) to 1280x720 (output, scaled).

### Current Behavior

Discord is able to show the camera in the Settings => Voice & Video preview screen, but restarts when actually trying to use it in a voice call on a server.

### Steps to Reproduce

1. Set-up OBS with a Base (Canvas) Resolution of 1920x1080, an Output (Scaled) Resolution of 1280x720, and set the Downscale Filter to Bilinear. Finally, set the resolution to 59.94.
2. Start the Virtual Camera using the button in the Controls panel
3. Join a Discord voice call, and enable the camera
4. Watch Discord dim the screen a bit, trying to open the camera overlay, and crashing

### Anything else we should know?

This only happens when running the Windows app. When running Discord in the browser this works without a problem. This seemed similar to #7529, but that was an older version. Also, this is happening when OBS is resizing the camera. That was the bug that I found when searching for others with the same issue.

**Comment by superconvert** [comment]
obs version: 29.02 (64bit)
had patched : notr1ch-vcam-resize-721e4fbe.zip
video size: 1092x614
os : win10
![Uploading obs_virtual_camera_crash.png…]()

**Comment by notr1ch** [comment]
> notr1ch-vcam-resize-721e4fbe.zip

Please do not use artifacts from old issues, the latest version of OBS includes this fix and others.

**Comment by superconvert** [comment]
I tried the latest version and this issue still persists.
OBS Version: 30.0.2(64 bit)
As long as there is a dynamic switch in the video size, it will crash
The scenario is as follows: The webrtc camera module calls the virtual camera of OBS

**Comment by RytoEX** [comment]
Please re-test this in OBS Studio 30.1.2 (or newer). This should be (hopefully) fixed.

**Comment by xudonax** [comment]
Retested, no crash anymore. Thanks!

**Comment by RytoEX** [comment]
Thanks for confirming!

**Comment by superconvert** [comment]
Retested, no crash anymore. 3Q
