### ISSUE TITLE
It is not possible to specify the number of channels for different sound sources

### ISSUE THREAD

**Issue by Tamago4a** [obsproject/obs-studio#9133]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/IhqmvIsdcTIw5c9T

### Expected Behavior

I expected that this program will be able to record the sound in the game in 5.1 format, and the sound from the microphone in stereo.

### Current Behavior

In the end, I found out that the best thing I can do is to record audio from both devices in 5.1 format.
![1](https://github.com/obsproject/obs-studio/assets/47304666/6039673a-c3f9-46b5-b737-cc4a749ad81a)
![2](https://github.com/obsproject/obs-studio/assets/47304666/60e890ab-f2dd-4607-a671-8f3320b469c9)

### Steps to Reproduce

1. Set the audio recording format to 5.1
2. Specify Windows sounds with the second audio track.
3. Specify the microphone as the first audio track.
4. Launch any audio source that can produce 5.1 audio
5. Record.
6. As a result, the video file will have 2 audio tracks. One kept the sounds of windows, and the other sound from the microphone. But both will be in 5.1 format, while a mono sound would be enough for a microphone.

Why such redundancy?

### Anything else we should know?

```MediaInfo
Audio #1
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 2 min 28 s
Bit rate mode                            : Variable
Bit rate                                 : 803 kb/s
Maximum bit rate                         : 1 024 kb/s
Channel(s)                               : 6 channels
Channel layout                           : C L R Ls Rs LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 14.2 MiB (6%)
Title                                    : Windows Sound
Default                                  : Yes
Alternate group                          : 1

Audio #2
ID                                       : 3
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 2 min 28 s
Bit rate mode                            : Variable
Bit rate                                 : 491 kb/s
Maximum bit rate                         : 1 024 kb/s
Channel(s)                               : 6 channels
Channel layout                           : C L R Ls Rs LFE
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 8.67 MiB (4%)
Title                                    : Microphone
Default                                  : No
Alternate group                          : 1
```

**Comment by gxalpha** [comment]
The "Set the audio recording format to 5.1" is universal across all audio tracks in OBS. The program doesn't care about which sources are on that track.

Wanting to specify different channels per audio track is a feature request, which we don't track using GitHub Issues (we use GitHub exclusively for bug reports).
Please put ideas and feature requests on [our ideas page](https://ideas.obsproject.com).

Thank you!

**Comment by Tamago4a** [comment]
https://ideas.obsproject.com/posts/2320/for-different-sound-sources-a-different-number-of-channels

**Comment by Tamago4a** [comment]
![Снимок](https://github.com/obsproject/obs-studio/assets/47304666/3ab2628d-9259-4535-ba3a-aa0c5616ae8e)
