### ISSUE TITLE
Unable to Game Capture when starting OBS

### ISSUE THREAD

**Issue by blodiak** [obsproject/obs-studio#9134]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/Sw2vZDlcFeivTdza

### Expected Behavior

Game Capture should work.

### Current Behavior

Capture is not working with Roblox Player at all (other games are fine) Log shows: `attempting to hook process: RobloxPlayerBeta.exe` then `capture stopped`

### Steps to Reproduce

1. Start game to capture
2. Start OBS
3. Attempt to capture
...

**Comment by Fenrirthviti** [comment]
Roblox broke game capture in their update, this is something they need to fix.
