### ISSUE TITLE
UI: Lossless mode uses muxer settings from Fragmented MP4 format

### ISSUE THREAD

**Issue by SuslikV** [obsproject/obs-studio#9135]
### Operating System Info

Other

### Other OS

Any

### OBS Studio Version

29.1.3

### OBS Studio Log URL

about:blank

### Expected Behavior

When user selects Lossless recording mode in OBS, only compatible and user defined muxer settings should apply.

### Current Behavior

OBS attempts to apply muxer settings from _Recording Format: Fragmented MP4 (.mp4)_ if it was selected earlier (before the user switched to the _Recording Quality: Lossless Quality, Tremendously Large File Size_).

This also leaves traces in the log:
```
11:01:14.764: Using muxer settings: 
11:01:14.764: 	movflags=frag_keyframe+empty_moov+delay_moov
11:01:14.769: Invalid muxer settings: 
11:01:14.769: 	movflags=frag_keyframe+empty_moov+delay_moov
```

### Steps to Reproduce

1. Make new profile & switch to this profile of OBS.
2. In OBS _Settings_,  set the _Output > Output Mode: Simple > Recording Format: Fragmented MP4 (.mp4)_ and click Apply settings.
3. Set the _Output > Recording Quality: Lossless Quality, Tremendously Large File Size_ and click OK to close settings.
4. Make recording (file will be saved in .avi format).
5. Open OBS log file and notice next message:
```
Invalid muxer settings: 
	movflags=frag_keyframe+empty_moov+delay_moov
```

### Anything else we should know?

_Recording Format: Fragmented MP4 (.mp4)_ muxer settings applies even if this field is not visible to the user.

**Workaround**
1. Set _Recording Quality_ **to other** than _Lossless Quality, Tremendously Large File Size_
2. Then set _Recording Format_ **to other** than _Fragmented MP4 (.mp4)_ or _Fragmented MOV (.mov)_
3. Now you can set _Recording Quality_ to _Lossless Quality, Tremendously Large File Size_ again and start recording without triggering warning in the log.

**Comment by gxalpha** [comment]
Please provide a full log.

**Comment by SuslikV** [comment]
@gxalpha cannot give you a heart, man. Sorry. Maybe restrictions in the messages you make on the github.

[2023-06-23 10-59-54.txt](https://github.com/obsproject/obs-studio/files/11847868/2023-06-23.10-59-54.txt) - from VirtualBox machine.
