### ISSUE TITLE
I'm trying to build a continuous build of OBS Studio in AppImage format, by myself, just need some pointers, for those interested

### ISSUE THREAD

**Issue by ivan-hc** [obsproject/obs-studio#9136]
### Operating System Info

Other

### Other OS

GNU/Linux

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://github.com/ivan-hc/OBS-Studio-appimage/issues/1

### Expected Behavior

Start services

### Current Behavior

debug: Found dbus service: org.freedesktop.ScreenSaver
debug: Attempted path: /tmp/.mount_OBS-StG35Oki/usr/share/obs/:locale/en-US.ini
debug: Attempted path: share/obs/obs-studio/locale/en-US.ini
debug: Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
debug: Attempted path: /tmp/.mount_OBS-StG35Oki/usr/share/obs/:locale.ini
debug: Attempted path: share/obs/obs-studio/locale.ini
debug: Attempted path: /usr/share/obs/obs-studio/locale.ini
debug: Attempted path: /tmp/.mount_OBS-StG35Oki/usr/share/obs/:locale/it-IT.ini
debug: Attempted path: share/obs/obs-studio/locale/it-IT.ini
debug: Attempted path: /usr/share/obs/obs-studio/locale/it-IT.ini
info: Using preferred locale 'it-IT'
debug: Attempted path: /tmp/.mount_OBS-StG35Oki/usr/share/obs/:themes/Yami.qss
debug: Attempted path: share/obs/obs-studio/themes/Yami.qss
debug: Attempted path: /usr/share/obs/obs-studio/themes/Yami.qss
info: Using EGL/X11
info: CPU Name: AMD Ryzen 5 3600 6-Core Processor
info: CPU Speed: 2802.819MHz
info: Physical Cores: 6, Logical Cores: 12
info: Physical Memory: 15922MB Total, 7191MB Free
info: Kernel Version: Linux 6.1.0-9-amd64
info: Distribution: "Debian GNU/Linux" "12"
info: Desktop Environment: XFCE (lightdm-xsession)
info: Session Type: x11
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.21.1
info: Qt Version: 5.15.8 (runtime), 5.12.8 (compiled)
info: Portable mode: false
QMetaObject::connectSlotsByName: Connecting slot on_transitionDuration_valueChanged() with the first of the following compatible signals: ("valueChanged(int)", "valueChanged(QString)")
info: OBS 29.1.2 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 48000
	speakers:        2
	max buffering:   960 milliseconds
	buffering type:  dynamically increasing
info: ---------------------------------
info: Initializing OpenGL...
libEGL warning: DRI2: failed to authenticate
info: Loading up OpenGL on adapter Mesa/X.org llvmpipe (LLVM 15.0.6, 256 bits)
info: OpenGL loaded successfully, version 4.5 (Core Profile) Mesa 22.3.6, shading language 4.50
info: ---------------------------------
info: video settings reset:
	base resolution:   1280x1024
	output resolution: 1024x818
	downscale filter:  Bicubic
	fps:               30/1
	format:            NV12
	YUV mode:          Rec. 709/Partial
info: NV12 texture support not available
info: P010 texture support not available
info: Audio monitoring device:
	name: Predefinito
	id: default
info: ---------------------------------
info: ---------------------------------
info:   Loaded Modules:
info: ---------------------------------
info: ==== Startup complete ===============================================
error: Service 'rtmp_common' not found
error: Failed to initialize service
info: Freeing OBS context data
info: == Profiler Results =============================
info: run_program_init: 4854.67 ms
info:  ┣OBSApp::AppInit: 7.339 ms
info:  ┃ ┗OBSApp::InitLocale: 3.799 ms
info:  ┗OBSApp::OBSInit: 128.614 ms
info:    ┣obs_startup: 3.013 ms
info:    ┗OBSBasic::OBSInit: 93.844 ms
info:      ┣OBSBasic::InitBasicConfig: 0.518 ms
info:      ┣OBSBasic::ResetAudio: 0.179 ms
info:      ┣OBSBasic::ResetVideo: 89.965 ms
info:      ┣OBSBasic::InitOBSCallbacks: 0.003 ms
info:      ┣OBSBasic::InitHotkeys: 0.02 ms
info:      ┣obs_load_all_modules2: 0.016 ms
info:      ┗OBSBasic::InitService: 0.055 ms
info: obs_hotkey_thread(25 ms): min=0.046 ms, median=0.175 ms, max=0.653 ms, 99th percentile=0.351 ms, 100% below 25 ms
info: audio_thread(Audio): min=0.005 ms, median=0.019 ms, max=0.044 ms, 99th percentile=0.039 ms
info: obs_graphics_thread(33.3333 ms): min=0.044 ms, median=0.118 ms, max=0.262 ms, 99th percentile=0.258 ms, 100% below 33.333 ms
info:  ┣tick_sources: min=0 ms, median=0 ms, max=0.001 ms, 99th percentile=0.001 ms
info:  ┣output_frame: min=0.035 ms, median=0.083 ms, max=0.22 ms, 99th percentile=0.218 ms
info:  ┃ ┗gs_context(video->graphics): min=0.035 ms, median=0.083 ms, max=0.22 ms, 99th percentile=0.218 ms
info:  ┃   ┣render_video: min=0.006 ms, median=0.029 ms, max=0.038 ms, 99th percentile=0.036 ms
info:  ┃   ┃ ┗render_main_texture: min=0.005 ms, median=0.025 ms, max=0.031 ms, 99th percentile=0.031 ms
info:  ┃   ┗gs_flush: min=0.025 ms, median=0.049 ms, max=0.181 ms, 99th percentile=0.179 ms
info:  ┗render_displays: min=0.002 ms, median=0.003 ms, max=0.004 ms, 99th percentile=0.004 ms
info: =================================================
info: == Profiler Time Between Calls ==================
info: obs_hotkey_thread(25 ms): min=25.105 ms, median=25.646 ms, max=26.133 ms, 43.0108% within ±2% of 25 ms (0% lower, 56.9892% higher)
info: obs_graphics_thread(33.3333 ms): min=32.762 ms, median=33.332 ms, max=33.961 ms, 100% within ±2% of 33.333 ms (0% lower, 0% higher)
info: =================================================
info: Number of memory leaks: 680

### Steps to Reproduce

    wget https://raw.githubusercontent.com/ivan-hc/OBS-Studio-appimage/main/obs-studio
    chmod a+x ./obs-studio
    ./obs-studio
    ./*.AppImage

### Anything else we should know?

Hi, in reference of https://github.com/obsproject/obs-studio/pull/2868#issuecomment-1135258064

I know the difference between a developer and a packager, I'm the second one. I build AppImages regardless the rules of the main community, for example, due to Github Actions and the lack of virtual environments available, I can build AppImages from the previous (not the oldest) Ubuntu LTS still supported (now it is Ubuntu 20.04 "Focal").

I understand that to packaging the same software in different formats is a waste of time for the developers that, instead, should be focused in improving their software. So to package the software is a work of the packagers, and in GNU/Linux (and the open source in general) "Unofficial is normal".

I don't ask you to add my builds to your releases because I wont to give you responsabilities that you wont if my builds does not work as expected... I can mark it as "Unofficial" if you want. I'll take alle responsibility tho what I'm trying to build.

All I ask you is to point me in the right way, by let me understanding why my build is not working:
- My repository is this https://github.com/ivan-hc/OBS-Studio-appimage
- My issue is this https://github.com/ivan-hc/OBS-Studio-appimage/issues/1
- A list of AppImages I already mantain is here instead https://github.com/ivan-hc#my-appimage-packages

For those that are interested I've just provided my links, we can talke here or on my repository, this is not important for me, I only want to build an AppImage because for me, in my use case, it is more convenient. And if I'll have success this will be available for everybody want to use AppImages over any other distribution method.

Thank you for your attention, cheers. 

Ivan

**Comment by gxalpha** [comment]
libobs isn’t loading any plugins, including those considered core functionality by OBS Studio. This is why it can’t find any services.

I can’t tell you *why* it doesn’t find these (you may need to specify the module environment variable), but that sounds like a support issue to me, not a bug report.

**Comment by ivan-hc** [comment]
@gxalpha I'd like to keep you updated about my project. 

I'm distributing the unofficial client containing a containerized version of Arch Linux known as [JuNest](https://github.com/fsquillace/junest), that is the based of a project I started with the name [ArchImage](https://github.com/ivan-hc/ArchImage)

The source code of my Appimage is https://github.com/ivan-hc/OBS-Studio-appimage

You can download the daily builds from https://github.com/ivan-hc/OBS-Studio-appimage/releases

The package is about 200 MB, but it can be smaller with a deep search, ArchImages have the advantage of work in the 90% of cases because they contain a whole Arch Linux container made portable thanks to the inbuilt "proot". Once the app is ready, all we have to do is to remove all unneeded stuff. Originally the package was 690 MB, I reached the size of 200 MB by listing what the script must remove from the package.

Also, the oly host's requirements is at least the Linux kernel 2.6. Thanks to JuNest, the app is widely compatible with all GNU/Linux distros, old and new (but I have not tested yet if the app works on FreeBSD too).

I hope you like my work. Cheers.
