### ISSUE TITLE
NVENC doesnt start

### ISSUE THREAD

**Issue by StreamVersus** [obsproject/obs-studio#9138]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/BFfCnF6mNfe71Cpf

### Expected Behavior

Recording should start and work as should

### Current Behavior

Failed to open NVENC codec: Function not implemented

### Steps to Reproduce

1. Start OBS
2. Check, that encoding method is Nvenc H264
3. Start Recording
4. Get error

### Anything else we should know?

GPU: GTX 880m
All works fine in version 27.0.1

**Comment by gxalpha** [comment]
This issue appears to be a support request, for which we don't use GitHub Issues.
Please make sure to visit the support sections on our [Discord server](https://discord.gg/obsproject) or [Forums](https://obsproject.com/forum).

Thank you!
