### ISSUE TITLE
Cursor visible in Application Capture when application is closed on MacOS

### ISSUE THREAD

**Issue by mxrlkn** [obsproject/obs-studio#9145]
### Operating System Info

macOS 13

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/wRvHr3e6lPL9fJyn

### Expected Behavior

I expect cursor only to be visible when the application in Application Capture mode is open. With "show cursor" enabled.

### Current Behavior

The cursor in Application Capture mode, when the application is closed, is still visible.

### Steps to Reproduce

1. Set Application in Application Capture
2. Close Application
3. See cursor is still visible

### Anything else we should know?

I don't know if this is necessarily a bug, but it feels like one to me. If it's not, I'd like it to be a feature request.

**Comment by gxalpha** [comment]
This works as expect and intended. Application capture captures your entire screen, but only shows the windows of the app you're capturing. The "Show cursor" selection is completely independent of whether the app is open, has any windows, or is closed.

**Comment by mxrlkn** [comment]
Alright. Can I make it a feature request, or is this completely up for Apple to implement?

**Comment by gxalpha** [comment]
You can create a feature request on our [ideas](https://ideas.obsproject.com) website, sure. However I wouldn't expect it to be implemented to be honest, the current behavior is what most people would expect.
Besides, it would indeed likely depend on Apple to add an option to the capture API.
