### ISSUE TITLE
OBS crashes when using VST plugins in a Wayland session on Fedora Linux

### ISSUE THREAD

**Issue by dcmen007** [obsproject/obs-studio#9147]
### Operating System Info

Other

### Other OS

Fedora 38

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.1.2

### OBS Studio Log URL

https://pastebin.com/fs4NERQL

### Expected Behavior

I expected that when using OBS in a Wayland session, the VST plugin would show its interface.

### Current Behavior

When using OBS in a Wayland session, the VST plugin, when opened, provokes the departure of OBS.
[Screencast from 2023-06-25 09-56-08.webm](https://github.com/obsproject/obs-studio/assets/137626367/156ef4bc-2812-4086-814c-59894aa7ad76)

### Steps to Reproduce

1. Added the "VST-Plugin 2.x" filter.
2. ticked the box next to the item "Open interface when active".
3. I selected the "GGate" VST plugin from the list.
The app crashed!

### Anything else we should know?

I inserted the text from the terminal instead of the log file, because there was no error in the logs
```[tasklist]
### Tasks
```

**Comment by Fenrirthviti** [comment]
Please also provide a gdb backtrace.

**Comment by dcmen007** [comment]
> Please also provide a gdb backtrace.

I am not a developer and therefore do not know how to do it. 
Can you tell me how to do gdb tracing?

**Comment by dcmen007** [comment]
> Please also provide a gdb backtrace.
Well, it seems like I was able to do a backtrace
I hope this is what you need

[backtrace.log](https://github.com/obsproject/obs-studio/files/11859205/backtrace.log)

**Comment by kkartaltepe** [comment]
The provided backtrace was canceled before it got to the thread that crashed. Just run `backtrace` in gdb after the crash instead of whichever command you ran.

**Comment by dcmen007** [comment]
> The provided backtrace was canceled before it got to the thread that crashed. Just run `backtrace` in gdb after the crash instead of whichever command you ran.

I've tried it before, but it didn't work out.
For I have little experience in such things.
Anyway, it's your job to do backtracking and look for the cause of the error.

**Comment by kkartaltepe** [comment]
Closing this as its probably just the vst being incompatible with wayland.

**Comment by dcmen007** [comment]
> Closing this as its probably just the vst being incompatible with wayland.

Actually, I tried different VST plugins and none of them worked.
That GGate, that Loudmax, even plugins from Linux Studio Plugins Project cause the same error.
So, only Wayland is to blame here.
