### ISSUE TITLE
obs game capture fails on windows with width > 16384 pixels on windows 11

### ISSUE THREAD

**Issue by tildejustin** [obsproject/obs-studio#9149]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/POQ15AE8NbrEBABH

### Expected Behavior

with stretch to bounds turned on, i would expect the window to be captured as it is when the width is 16384 pixels or less.

### Current Behavior

The capture goes black after setting the window to 1920 * 16385 or greater
additionally, after bringing the window back to 1920 * 1027 i then have to unmaximize it to get it to be captured again...

### Steps to Reproduce

1. set up a game capture with a window (i have been using Minecraft: Java Edition), with transform bounding box type "set to stretch to bounds".
2. change the window's size to 1920 x <number in-between 16385 and 32768, inclusive> (I have been using an AutoHotKey script for this, if i can link it here i will)
3. observe that, if on windows 11 (windows 10 this will crash minecraft, i'm not sure about linux in regards to obs behavior but i know window size can be made larger than 32768 based on testing from other people)

### Anything else we should know?

At some point around the release of windows 11 (not sure exactly when, this also could be a gpu thing), making windows up to 32768 pixels in width instead of up to 16384 was made possible without crashing (specifically, this would crash Minecraft: Java Edition, i haven't tested with any other programs, and can't anymore) on windows, and I assume this is due to not following that change or something like that?

**Comment by tildejustin** [comment]
ahk script
```
#SingleInstance force


; Increasing height will zoom in more.
; Change these values to whatever you're comfortable with, the default should be fine for most users however.
; Most values should be okay as long as you ensure you're getting 0.004 stdev when calibrating Ninjabrain Bot.
; ping or dm priffin#5472 if any questions/issues

zoomHeight := 16385
zoomWidth := 1920

zoomXPos := Floor( -((zoomWidth-A_ScreenWidth) / 2) )
zoomYPos := Floor( -((zoomHeight-A_ScreenHeight) / 2) )

#If WinActive("Minecraft") && (WinActive("ahk_exe javaw.exe") || WinActive("ahk_exe java.exe"))
    *E:: ; hotkey
        WinGetPos,,,,h,A
        if (h < zoomHeight){
            WinGet, initialStyle, Style, A
            WinGet, initialExStyle, ExStyle, A
            WinSet, Style, -0xC40000, A
            DllCall("SetWindowPos", "Ptr", WinExist("A"), "UInt", 0, "Int", zoomXPos, "Int", zoomYPos, "Int", zoomWidth, "Int", zoomHeight, "UInt", 0x0400)	
        }
        else {
            WinSet, Style, %initialStyle%, A
            WinSet, ExStyle, %initialExStyle%, A
            DllCall("SetWindowPos", "Ptr", WinExist("A"), "UInt", 0, "Int", 0, "Int", 0, "Int", A_ScreenWidth, "Int", A_ScreenHeight, "UInt", 0x0400)
        }
    return
```

**Comment by RytoEX** [comment]
D3D11 textures max out at 16384 pixels/texels in any dimension. I do not believe it is possible to capture/draw anything larger.

**Comment by alinsavix** [comment]
The title should actually say it fails on windows with a *height* of more than 16384 pixels (not width)

...I admit, I'm pretty curious about why OP actually wants this/what it would be used for/etc.

**Comment by tildejustin** [comment]
It most likely happens with width as well, I just haven't tested. This is used in top-level Minecraft: Java Edition speedruns (commonly called eyezoom) for increased precision (ex. https://www.youtube.com/watch?v=T2Wmhf4tNj4&t=12s). It's certainly niche, but a fix that would be appreciated regardless (if it can be fixed).

**Comment by RytoEX** [comment]
> The title should actually say it fails on windows with a _height_ of more than 16384 pixels (not width)

> It most likely happens with width as well, I just haven't tested. This is used in top-level Minecraft: Java Edition speedruns (commonly called eyezoom) for increased precision (ex. https://www.youtube.com/watch?v=T2Wmhf4tNj4&t=12s). It's certainly niche, but a fix that would be appreciated regardless (if it can be fixed).

It would fail in either case:
> D3D11 textures max out at 16384 pixels/texels in any dimension. I do not believe it is possible to capture/draw anything larger as a single texture.

**Comment by Fenrirthviti** [comment]
Since this is not expected to, and hasn't ever worked, I'm going to go ahead and close this.

For clarity, d3d does not support texture sizes above 16384 (width or height), even if we were to switch to d3d12.

**Comment by tildejustin** [comment]
oh, I think i figured why it worked. it has to do with GL_MAX_TEXTURE_SIZE being larger (32768) on nvidia cards.

**Comment by tildejustin** [comment]
Thanks for entertaining the suggestion anyway, even if it is impossible...
