### ISSUE TITLE
Window on inactive i3 workspace isn't captured

### ISSUE THREAD

**Issue by fmahnke** [obsproject/obs-studio#9150]
### Operating System Info

Other

### Other OS

NixOS 22.11

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.0.2

### OBS Studio Log URL

https://obsproject.com/logs/IimU7Vjcu4Mb1F9Z

### Expected Behavior

I expect the Xcomposite source to capture from windows that are on all my i3 workspaces (virtual desktops). Expect capture whether or not the workspace containing the window is currently activated on either of my monitors.

A previous major version of OBS captured windows on inactive workspaces, as expected.

### Current Behavior

Windows are captured only when they are on a workspace that's currently active on either of my monitors.

### Steps to Reproduce

1. Launch OBS.
2. Add a Window Capture (Xcomposite) source with a window on a currently active i3 workspace.
3. Verify the window is being captured in the OBS preview.
4. Switch to a different workspace on the monitor with the window being captured.
5. Verify the capture is no longer happening in the OBS preview.
6. Switch back to the workspace with the window.
7. Verify the capture is once again happening in the OBS preview.
...

### Anything else we should know?

xorg server 1.20.14
i3 version 4.21.1
OBS 29.0.2

A previous major version of OBS captured windows on inactive workspaces, as expected.

The problem began last year with (I think) the upgrade from OBS 28 to 29. A system upgrade could have included changes to X11 or i3 around the same time, so I've not ruled out the possibility of the change being caused by one of those components.

**Comment by mihawk90** [comment]
Generally speaking inactive workspaces are not rendered by the Desktop Environment and either way this would be an issue for the DE not for OBS.
OBS just receives what the DE and/or X11 is giving it.

**Comment by fmahnke** [comment]
Thanks for your reply. That sounds fair enough. I was getting lucky with the previous environment.

For anyone else looking for this functionality, it looks like this has come up in [i3's issue tracker](https://github.com/i3/i3/issues/1925) and there's no solution there.

There are a couple promising starting points for doing this in nested X sessions using [Xnest](https://www.reddit.com/r/i3wm/comments/kryciv/record_window_from_nonfocused_workspace_with_obs/) or [Xephyr](https://www.reddit.com/r/i3wm/comments/kiljuo/obs_capture_window_that_is_not_if_the_foreground/).
