### ISSUE TITLE
"Remove settings and sources" in portable mode uninstall caused main install to lose all scenes and sources also

### ISSUE THREAD

**Issue by PowerfulDot** [obsproject/obs-studio#9151]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/MjHYITBP6tv93Cpb

### Expected Behavior

I used a portable mode install to test a new plugin that had been crashing. Install location was in C:/obs-studio portable/ It had a very minimal scene collection so for safe testing, I uninstalled OBS studio. I navigated to the uninstall exe in the "obs-studio portable" folder, and chose "remove settings and sources". 

I expected this would only remove settings and sources in the portable instance. 

### Current Behavior

The portable uninstall worked as intended. 

When I opened my main OBS Studio install, I found all my profiles and scene collections were gone. I had not backed them up manually. In case this is of interest to anyone, trying to restore files from windows did not work. Both System Restore and the Win 7  Backup and Restore did not bring them back. 

Log file above is from the portable instance after reinstall, the ones below from my main install after uninstall removed everything. https://obsproject.com/logs/E4jB77IqtzkgM0DW

### Steps to Reproduce

1. Have a portable mode install of OBS Studio and a main install
2. Navigate to the portable mode uninstall exe and use it
3. Tick the checkbox for "remove settings, scenes..."

**Comment by derrod** [comment]
There is no such thing as a "portable install" (bit of an oxymoron, isn't it?). What you did is just a regular OBS install into a different folder, and then uinstalled it. 

If you want to run OBS in portable mode just unpack the ZIP file and either run the .exe with `--portable` or create a file called `portable_mode.txt` in the root folder. Then all your data will be saved in a `config` folder rather than in AppData. See the instructions on the wiki: https://github.com/obsproject/obs-studio/wiki/install-instructions#portable-version

**Comment by PowerfulDot** [comment]
Apologies if the terminology I used was not quite perfect. 

I did have installed OBS twice, and one was using portable mode correctly as it shows in the log. I navigated specifically to c:/obs-studio portable/ to run the uninstall.exe. I expected this would not affect the install that was not using portable mode. 

11:48:45.472: Current Date/Time: 2023-06-24, 11:48:45
11:48:45.472: Browser Hardware Acceleration: true
11:48:45.472: Hide OBS windows from screen capture: false
11:48:45.472: Qt Version: 6.4.3 (runtime), 6.4.3 (compiled)
11:48:45.472: Portable mode: true

**Comment by derrod** [comment]
If you install OBS and then run it in portable mode it is still installed regularly, the uninstaller does not check the portable mode file.

**Comment by PowerfulDot** [comment]
I can see now how this results in the issue, thanks for taking the time to explain. To a cautious user, it appears to be the "right way" to uninstall safely however. The program appears to be installed twice and seems to be a very separate thing. I will make a suggestion. Thanks.
