### ISSUE TITLE
raw_active is not reset after stopping output

### ISSUE THREAD

**Issue by notr1ch** [obsproject/obs-studio#9153]
### Operating System Info

Windows 10

### OBS Studio Version

Git

### OBS Studio Version (Other)

ba92140f

### OBS Studio Log URL

N/A

### Expected Behavior

After stopping all outputs, `obs_video_active` should return `false`.

### Current Behavior

`obs_video_active` always returns true after toggling vcam on and off. Inspecting `video->raw_active` on the main mix shows it incrementing every time vcam is toggled.

### Steps to Reproduce

1. Toggle vcam
2. Open settings
3. Notice the settings are restricted due to an active output

### Anything else we should know?

Likely introduced by the multi track video changes.

**Comment by Lain-B** [comment]
Bisected to 7cd7ca80f8b3dde1e4a1b4cdf256ade2a9af65f4
