### ISSUE TITLE
7.1 Audio recording and output bugs

### ISSUE THREAD

**Issue by Billycar11** [obsproject/obs-studio#9156]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/forum/threads/7-1-audio-wont-import-to-almost-anything.166001/#post-616231

### Expected Behavior

7.1 audio should playback in most players

### Current Behavior

when set to 7.1 almost no players can play the 7.1 or video editors import it
and if you do get it to play it seems to be boosted way more than it should be. unless you use float 32 but then channel mapping is wrong

### Steps to Reproduce

1.set obs to 7.1 recording
2. try to play it in most players it wont see the audio

**Comment by pkviet** [comment]
more info is needed:
- a log file which will allow us to check the encoder selected,
- the platform
- the apps with which you tested

**Comment by pkviet** [comment]
found logs in the forum post, but still it'd be better to post here

**Comment by pkviet** [comment]
can't confirm the issue.

- I used a wav 7.1 source (https://www2.iis.fraunhofer.de/AAC/multichannel.html), played in obs Media Source.
- Recorded with ffmpeg aac with audio settings in 7.1.
- Converted the recorded aac to wav and checked on Reaper (top is obs, bottom is original wav from Fraunhoffer):
![reaper_2023-06-26_13-46-57](https://github.com/obsproject/obs-studio/assets/9283407/6ec98368-da3b-469c-bd8f-c7a85c578e4d)
- then played the audio on VLC; i hear all the channels ...
Post more info regarding the apps you tested the file with.
If it doesn't work well for you with FFmpeg native aac, I'd suggest to switch to coreaudio aac encoder; quality will be better.
It will require that you install iTunes.

**Comment by Billycar11** [comment]
not sure if the email went through but here it is.
Check out my video in the obs post. https://obsproject.com/forum/threads/7-1-audio-wont-import-to-almost-anything.166001/#post-616226
Pretty much any player but vlc is broken windows native ect.
Also 7.1 can't be imported to DaVinci resolve but 5.1 can without issue.
It does not just break the 7.1 track it breaks all tracks after the change to 7.1 that they cant import to the editor.

Thanks,
Billy

**Comment by energizerfellow** [comment]
Define "Pretty much any player but vlc". Exact software names and version numbers matter here, including any editing software or hardware playback devices you may be using.

I would also document any behavior using non-remuxed, non-fragmented MP4 and MOV containers instead of MKV. Make sure to try *both* MP4 *and* MOV as well. Please document findings with both these containers for any behavior changes.

**Comment by RytoEX** [comment]
I've looked into this. Media Player doesn't seem to handle 7.1 audio.

I recorded a test file with 7.1 audio from FFmpeg, and it would not play that file at all. Running that file through HandBrake and downmixing audio to Stereo makes Media Player play it fine. Running the same file through HandBrake with the downmix setting set to 7.1 results in Media Player not playing the audio, as described here. Downmixing to 6.1 also does not play in Media Player, whereas 5.1 audio works fine.

Media Player warns that it cannot play the audio and offers the option to submit feedback.
![image](https://github.com/obsproject/obs-studio/assets/624931/fa4ae1fc-5129-4dc0-adf7-c30b91b48044)

I do not think this is our bug. Please submit a report via Feedback Hub to Microsoft for their Media Player(s). Please submit reports for the other affected software to the appropriate places.
