### ISSUE TITLE
Accessing settings is no longer possible

### ISSUE THREAD

**Issue by ToRRent1812** [obsproject/obs-studio#9158]
### Operating System Info

Other

### Other OS

Nobara KDE (Based of Fedora 38)

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/g2x9uY00kMN9aZMY

### Expected Behavior

Being able to reach obs settings.

### Current Behavior

Clicking on settings button closes obs. Console log shows
`terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string: construction from null is not valid
[1]    3632850 IOT instruction (core dumped)  obs`

### Steps to Reproduce

1. Install obs studio RPM
2. Try to open settings

**Comment by Fenrirthviti** [comment]
Please also provide a gdb backtrace.

As a note, this probably will need to be reported to the rpm maintainer, as that is not an official package. This smells like a build issue, but backtrace will help identify what might be going on.

**Comment by tytan652** [comment]
This package is built without x264 support, the issue is on the packager/distro side.

**Comment by tytan652** [comment]
It was confirmed that it's an issue with the distribution that didn't correctly introduced dependency on x264.
