### ISSUE TITLE
Thông báo lỗi

### ISSUE THREAD

**Issue by TXAVL** [obsproject/obs-studio#9163]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/Bhp7lTUHoxny0thm

### Expected Behavior

**I want it to record the browser screen on OBS Studio version 29.1.3**

### Current Behavior

When I click Start Recording it shows the error message:

---------------------------
Can't start video recording
---------------------------
Unable to write output. Please check the log files for more details.

Note: if you are using the NVENC or AMD encoder, you must update the GPU to the latest version.
---------------------------
Agree
---------------------------
![image](https://github.com/obsproject/obs-studio/assets/102934765/1d018631-6f5f-407d-a699-50e5c9d2b3f8)

### Steps to Reproduce

**1. Click Icon obs studion on my desktop
2. Configure software to record
3. Click Start Record
...**

**Comment by kkartaltepe** [comment]
We do not use GitHub Issues for support questions.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

**Comment by TXAVL** [comment]
> Chúng tôi không sử dụng Sự cố GitHub cho các câu hỏi hỗ trợ.
> 
> Vui lòng sử dụng [máy chủ Discord](https://obsproject.com/discord) hoặc [diễn đàn](https://obsproject.com/forum) . Để biết thêm thông tin, hãy xem [trang Trợ giúp](https://obsproject.com/help) của chúng tôi .

UK, I know
