### ISSUE TITLE
MultiTrack Audio for Custom not Working as Expected

### ISSUE THREAD

**Issue by fairbairn** [obsproject/obs-studio#9167]
### Operating System Info

macOS 12

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.1.0-191

### OBS Studio Log URL

https://obsproject.com/logs/A0RXip0qMFBEgwqV

### Expected Behavior

We're attempting to use the Twitch VOD multi-track audio functionality using a Custom Stream destination.

We've modified the global.ini to include these additional flags:

```
[General]
EnableCustomServerVodTrack=true

[AdvOut]
TrackIndex=1
VodTrackEnabled=true
VodTrackIndex=2
```

The option does appear in OBS, and we have it checked.  We selected the primary Audio to use "Track 1" and Twitch VOD to use "Track 2".

We're streaming to a local RTMP ingest server so that we can probe the RTMP output directly.

We never see a second audio stream in the RTMP, which we assume would be mapped in the RTMP multiplexed output, so the Custom service could select which streams are combined for live vs vod (which is the intent) in the cloud upon ingest.

Instead, we only see these two streams with ffprobe...

```
  Duration: 00:00:00.00, start: 8.448000, bitrate: N/A
  Stream #0:0: Audio: aac (LC), 48000 Hz, stereo, fltp, 163 kb/s
  Stream #0:1: Video: h264 (Baseline), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 8192 kb/s, 60 fps, 60 tbr, 1k tbn
  ```
  

### Current Behavior

We get one audio stream on the output.

### Steps to Reproduce

1.
2.
3.
...

### Anything else we should know?

We asked for help on the Discord, which helped us identify the flags to configure.

We've looked through the source code and not found exactly where the problem may have occurred.

Our assumption is that enabling this capability would likely do two things, provide two audio streams in the RTMP output along with one video stream and a metadata stream that would help identify the intent of each audio stream.

This is a total guess.

**Comment by derrod** [comment]
The audio data for the second stream is sent as metadata as RTMP does not support multiple audio tracks. Ffprobe/Ffmpeg doesn't support this.
