### ISSUE TITLE
GPU driver update changes streaming profile settings

### ISSUE THREAD

**Issue by chticer** [obsproject/obs-studio#9185]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/RKX6aV625zDWq7kP

### Expected Behavior

Streaming settings in Settings > Output should not be changed after updating GPU drivers.

### Current Behavior

Streaming settings in Settings > Output are changed to the NVIDIA NVENC H.264 encoder at 50 Kbps bitrate.

### Steps to Reproduce

1. Update GPU drivers (mine was done through GeForce Experience)
2. Open Settings > Output in OBS for current profile.
3. Video Encoder under Streaming Settings and Bitrate under Encoder Settings are changed.

If different profiles are available, switch to another profile and step 3 should be replicable as well.

### Anything else we should know?

The screenshot below shows that GPU drivers were updated on Thursday, June 29 (this was during the morning hours).

![2023-06-30_16-59-05](https://github.com/obsproject/obs-studio/assets/8918347/01a7c6f4-e89a-49c1-80b9-5e79475c3bdf)

I remember this issue happening before and I believe it was because of a GPU driver update. It's not something that happens very often but probably because I do not update GPU drivers very often either.

## Wednesday, June 28, 2023 1:44:56 PM
This was a day before the GPU drivers update. As shown in the log, the "Twitch (NVENC Stream)" profile was used:

```
13:44:56.042: Command Line Arguments: --startstreaming --profile Twitch (NVENC Stream) --scene Music Streaming Player - Starting Soon
```

The log indicates that the NVIDIA NVENC H.264 encoder with 6000 bitrate was used, which is the correct streaming settings:

```
13:45:03.555: [FFmpeg NVENC encoder: 'advanced_video_stream'] settings:
13:45:03.555: 	encoder:      NVIDIA NVENC H.264 (FFmpeg)
13:45:03.555: 	rate_control: CBR
13:45:03.555: 	bitrate:      6000
```

Full log: https://obsproject.com/logs/zMm8VDxYhvSkU6eP

## Thursday, June 29, 2023 13:44:56 PM

This was the same day that GPU drivers were updated. As shown in the log, the "Twitch (x264 Stream, 720p60fps)" profile was used:

```
13:44:56.490: Command Line Arguments: --startstreaming --profile Twitch (x264 Stream, 720p60fps) --scene Music Streaming Player - Starting Soon
```

The log indicates that the NVIDIA NVENC H.264 encoder with 50 bitrate was used, which is the incorrect streaming settings (should be the x264 encoder with 6000 bitrate):

```
13:45:06.585: [FFmpeg NVENC encoder: 'advanced_video_stream'] settings:
13:45:06.585: 	encoder:      NVIDIA NVENC H.264 (FFmpeg)
13:45:06.585: 	rate_control: CBR
13:45:06.585: 	bitrate:      50
```

Full log: https://obsproject.com/logs/qLyEiGzyxenNOem4

## Friday, June 30, 2023 13:44:55 PM

This was the day after that GPU drivers were updated and the same profile used from Wednesday, June 28:

```
13:44:55.830: Command Line Arguments: --startstreaming --profile Twitch (NVENC Stream) --scene Music Streaming Player - Starting Soon
```

The log indicates that the NVIDIA NVENC H.264 encoder with 50 bitrate was used, which is the incorrect streaming settings (should be with 6000 bitrate):

```
13:45:04.585: [FFmpeg NVENC encoder: 'advanced_video_stream'] settings:
13:45:04.585: 	encoder:      NVIDIA NVENC H.264 (FFmpeg)
13:45:04.585: 	rate_control: CBR
13:45:04.585: 	bitrate:      50
```

Full log: https://obsproject.com/logs/RKX6aV625zDWq7kP

**Comment by derrod** [comment]
GeForce Experience can change OBS settings, this is unfortunately not something we can prevent since it just updates the config files. But you can disable the automatic optimisation in GFE.

**Comment by chticer** [comment]
It didn't show that optimization was turned on. Still find it weird that it can modify the config file for all the profiles in %APPDATA%. Regardless though, I have just decided to uninstall the program.
