### ISSUE TITLE
obs-scripting + api doc: obs_properties_add_button2()

### ISSUE THREAD

**Issue by ludolpif** [obsproject/obs-studio#9198]
### Operating System Info

Other

### Other OS

Debian 12

### OBS Studio Version

29.1.3

### OBS Studio Log URL

N/A

### Expected Behavior

I am  using lua scripting for shader filters. This BR is more a custom binding missing and doc missing hint than a "expected/current behavior" deviation.

### Current Behavior

I try to add a button in a source of type filter configuration from lua to trigger a shader recompilation.
I want to change a run-time variable or call code that need my filter implementation data instead of alter a setting (I don't want to persist it).
I've read https://docs.obsproject.com/reference-properties#c.obs_properties_add_button
I see for the callback a signature with (props, prop, settings) args. And there is no "data" (void * like, for filter implementation data).
I've seeked for already shipped C++ example in OBS source, I've read ./plugins/linux-pipewire/screencast-portal.c. It uses the C obs_properties_add_button2() function from ./libobs/obs-properties.h
First : obs_properties_add_button2() is not documented in https://docs.obsproject.com/reference-properties. Is that a publicly available function / parts of the supported API ? May I PR a .rst addendum for that ?

Callback of this one have a 4th argument for user data. It seems interesting for my need.
In obs-scripting/obslua, obs_properties_add_button2() in not usable from lua script because it is undeclared in ./deps/obs-scripting/obs-scripting-lua.c:add_hook_functions().
The C function obs_properties_add_button2() is used to implement the obs_properties_add_button() lua function in properties_add_button(lua_State *script). It's unclear for me if the callback 4th argument could be some lua user data or not.

Second : I wish pass a lua table as user data from my lua user script. Is that possible currently ? Is it taking a addition for a  lua obs_properties_add_button2() wrapper ? Is it possible at all ?

### Steps to Reproduce

N/A since it's doc/API hole

**Comment by Penwy** [comment]
Due to the way callbacks are implemented in the scripting API, they indeed do not accept private data.
This is documented in https://docs.obsproject.com/scripting#obs_properties_add_button
If you need the callback to have access and modify a run-time variable of your script, make it a global variable.

I am not involved in OBS development but I'd say this is unlikely to ever change without a complete overhaul of the scripting API.

**Comment by ludolpif** [comment]
Hi,
> If you need the callback to have access and modify a run-time variable of your script, make it a global variable.

It seems not easy to me : it's a variable tied to one of multiple instances of the same filter defined by the script. I may don't understand your suggestion, could you add precision or do you know a working example of that somewhere ?

Thanks,

**Comment by ludolpif** [comment]
Hi,
I eventually found a working lua way to set a variable in my filter implementation data without using callback userdata, inspired https://obsproject.com/wiki/Scripting-Tutorial-Halftone-Filter, it takes a closure and optionally a anonymous function, and knowing the fact that semi-colon exists in lua, and allow multiple statements on the same line : 

```lua
obs = obslua
function script_description()
  return [[Test button filter.
  Demo of obs.obs_properties_add_button() to modify filter implementation data
  allowing doing action in render thread at next frame.
  It takes a closure to circumvent the lack of userdata in callback arguments.]]
end
function script_load(settings)
  obs.obs_register_source(source_info)
end
source_info = {}
source_info.id = 'filter-test-button'
source_info.type = obs.OBS_SOURCE_TYPE_FILTER
source_info.output_flags = obs.OBS_SOURCE_VIDEO
source_info.get_name = function() return "Test button filter"; end
source_info.create = function(settings, source)
  local filter_impl_data = {}
  filter_impl_data.test_value = false
  -- [...]
  return filter_impl_data
end
source_info.get_properties = function(filter_impl_data)
  local props = obs.obs_properties_create()
  obs.obs_properties_add_button(props, "btn_test", "Test button",
    function(properties, property) filter_impl_data.test_value = true; end)
  return props
end
source_info.video_render = function(filter_impl_data)
  if ( filter_impl_data.test_value ) then
    obs.script_log(obs.LOG_INFO, "video_render: test_value true -> false")
    filter_impl_data.test_value = false
  end
end
```
if the closure set some settings, and the content of other parameters fields in the UI should be refreshed, the closure must return true (no return is the same as return nil).

**Comment by ludolpif** [comment]
API doc of [obs_properties_add_button](https://docs.obsproject.com/scripting#obs_properties_add_button) isn't targeting subtleties about lua or python bindings. If my snippet is correct, where or how I should post a message to help getting this findable by newcomers that go straightforward in binding pitfalls as I just done ?

And for C++ user : should obs_properties_add_button2() API documented ?
Thanks,

**Comment by CodeYan01** [comment]
it doesn't necessarily have to be an anonymous function. you could also define the function within the function normally.

obs_properties_add_button2 should be documented for C/C++ users, feel free to write a PR to add docs for it. Some people eventually add docs, but there are a lot of OBS undocumented functions at the moment.

> API doc of [obs_properties_add_button](https://docs.obsproject.com/scripting#obs_properties_add_button) isn't targeting subtleties about lua or python bindings. If my snippet is correct, where or how I should post a message to help getting this findable by newcomers that go straightforward in binding pitfalls as I just done ?

I'm not sure what kind of description would be necessary to be added to the docs, but feel free to write a suggestion here, or better, a PR for the docs, so it will be reviewed.
