### ISSUE TITLE
Unable to capture screen

### ISSUE THREAD

**Issue by for-the-zero** [obsproject/obs-studio#9213]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.3

### OBS Studio Log URL

---

### Expected Behavior

capture screen

### Current Behavior

black screen
<img width="960" alt="uTools_1688742262786" src="https://github.com/obsproject/obs-studio/assets/101497510/2a4a2fba-086d-477e-94d9-6794e9e20d5d">
<img width="960" alt="uTools_1688742290974" src="https://github.com/obsproject/obs-studio/assets/101497510/b6ca2cda-e176-4abb-a547-5fee318f3644">

### Steps to Reproduce

The usual.

### Anything else we should know?

<img width="960" alt="uTools_1688742375515" src="https://github.com/obsproject/obs-studio/assets/101497510/3b30fb0f-065c-4e72-9342-f8a24401fa3a">

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
