### ISSUE TITLE
Auto-configuration wizard shows your current frame rate in scientific notation if FPS is >= 100

### ISSUE THREAD

**Issue by matoi974** [obsproject/obs-studio#9216]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.3

### OBS Studio Log URL

n/a

### Expected Behavior

Fractional frame rates should be displayed as-is (i.e. 120/1, 60000/1001).

### Current Behavior

Fractional frame rates are displayed in scientific notation (1.2e+02).
![image](https://github.com/obsproject/obs-studio/assets/63289008/05d9b9f9-28b8-4cb5-b74b-21a875914c77)

### Steps to Reproduce

1. In Settings>Video, set FPS type to fractional, numerator to 120, denominator to 1.
2. Run the auto-configuration wizard, choose "Optimize for recording".
3. Open the frame rate selection drop-down.

### Anything else we should know?

Reproduced on MacOS 13 and Windows 10, so presumably affects all platforms.

**Comment by Xorshasia** [comment]
This happens anytime the framerate selected in Settings > Video has more than two digits in the integral portion. The actual framerate can be either using integer or fractional.
