### ISSUE TITLE
windows build error ,  about CEF

### ISSUE THREAD

**Issue by yiyezhangmu** [obsproject/obs-studio#9219]
### Operating System Info

Windows 11

### OBS Studio Version

Git

### OBS Studio Log URL

https://github.com/obsproject/obs-studio/wiki/build-instructions-for-windows

### Expected Behavior

build success

### Current Behavior

I hava  set    env  "CEF_ROOT_DIR=D:\dev\program\studio\cef_binary_5060_windows_x64".
but  i run  command  ".\.github\scripts\Build-Windows.ps1",  it occur error 👍 

…………
CMake Warning (dev) at cmake/finders/FindLibAJANTV2.cmake:83 (message):
  Failed to find LibAJANTV2 version.
Call Stack (most recent call first):
  plugins/aja/CMakeLists.txt:12 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at C:/Program Files/CMake/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find CEF (missing: CEF_LIBRARY_RELEASE
  CEF_LIBRARY_WRAPPER_RELEASE) (found version "103.0.0")

      Reason given by package: Ensure that location of pre-compiled Chromium Embedded Framework is set as CEF_ROOT_DIR.

Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  cmake/finders/FindCEF.cmake:163 (find_package_handle_standard_args)
  plugins/obs-browser/CMakeLists.txt:14 (find_package)

-- Configuring incomplete, errors occurred!
Exception: D:\dev\program\studio\obs-studio\.github\scripts\Build-Windows.ps1:107
Line |
 107 |  Build
     |  ~~~~~
     | cmake --preset windows-x64 exited with non-zero code 1.

### Steps to Reproduce

nothing

### Anything else we should know?

[p](https://github.com/obsproject/obs-studio/wiki/build-instructions-for-windows)

**Comment by RytoEX** [comment]
We've recently updated our build system and [build instructions for Windows](https://github.com/obsproject/obs-studio/wiki/Build-Instructions-For-Windows). Please use CMake Presets instead of the CI scripts. CMake will automatically download the necessary dependencies. Please note that you appear to be using a pre-release version of CMake 3.27 and we have only tested up to CMake 3.26.

**Comment by xipengfei** [comment]
how can I do

CMake Error at C:/Program Files/CMake/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find CEF (missing: CEF_LIBRARY_RELEASE
  CEF_LIBRARY_WRAPPER_RELEASE CEF_INCLUDE_DIR) (found version "0.0.0")

      Reason given by package: Ensure that location of pre-compiled Chromium Embedded Framework is set as CEF_ROOT_DIR.

Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  cmake/finders/FindCEF.cmake:165 (find_package_handle_standard_args)
  plugins/obs-browser/CMakeLists.txt:14 (find_package)
