### ISSUE TITLE
[Report]: Heavy network fluctuation

### ISSUE THREAD

**Issue by joe733** [obsproject/obs-studio#9222]
### Operating System Info

Other

### Other OS

ArchLinux

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/0r7IWWWrpXFrnm5b

### Expected Behavior

Network is stable.

### Current Behavior

Network keeps flickering like a lamp.

### Steps to Reproduce

1. Insert stream key
2. Start stream

### Anything else we should know?

[Screencast from 2023-07-09 10-09-51.webm](https://github.com/obsproject/obs-studio/assets/38415384/45d3e53c-9d52-4872-80c9-813fe907e820)

[Screencast from 2023-07-09 10-11-10.webm](https://github.com/obsproject/obs-studio/assets/38415384/da19f70e-4f59-4dc1-aeca-6cabdb1ed54c)

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
