### ISSUE TITLE
OBS windowed preview + browser sources completely freeze out and are unusable 

### ISSUE THREAD

**Issue by alexandremix** [obsproject/obs-studio#9223]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/sRYfW4NyKw6pLLD0

### Expected Behavior

Expected behaviour is being able to flawlessly use any browser source and not having the preview screen frozen randomly. 

### Current Behavior

Preview window is frozen randomly, need to restart obs to fix, browser docks also freeze sometimes restarting dock works, other times it just loads a white page unresponsive

### Steps to Reproduce

1. Use obs
2. Wait
3. Bugged
...

### Anything else we should know?

Tried asking for help in obs a lot of times, youtube videos google, nothing fixes. Did DDU my system, also unsinstalled obs and installed again. no fixes at all.

**Comment by notr1ch** [comment]
The steps to reproduce should be 100% reproducible, or it's most likely an issue with your system or configuration. Please use the forums or Discord for support issues.

**Comment by alexandremix** [comment]
I asked for help there 5 times , noone replies me

**Comment by yongsongTang** [comment]
@alexandremix 
I have a problem similar to yours，I control the obs source through websocket. After a while, the preview shows a white screen. I don’t find any rules 
can you give me some tips?
