### ISSUE TITLE
endavor os arch screen sharing after installing requirements

### ISSUE THREAD

**Issue by coolst3r** [obsproject/obs-studio#9224]
### Operating System Info

Other

### Other OS

arch linux

### OBS Studio Version

29.1.3

### OBS Studio Log URL

none

### OBS Studio Crash Log URL

none

### Expected Behavior

screen share

### Current Behavior

error

### Steps to Reproduce

1.
2.
3.
...
launch on wayland

### Anything else we should know?

qt.qpa.wayland: Wayland does not support QWindow::requestActivate() error

warning: Failed to load 'en-US' text for module: 'obs-vnc.so'

error: Unable to load NvFBC library
warning: Failed to initialize module 'nvfbc.so'

**Comment by tytan652** [comment]
This looks like a support request, please go to the [forum](https://obsproject.com/forum/) or the [discord](https://obsproject.com/discord).

And on top of that there is no log provided.

PS: NvFBC plugin no longer works since OBS 28 because we dropped GLX support.
