### ISSUE TITLE
Windows audio enhancements

### ISSUE THREAD

**Issue by Slxdy** [obsproject/obs-studio#9225]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.3

### OBS Studio Log URL

n/a

### Expected Behavior

OBS should ignore audio enhancements specified for an audio device (in the "More sound settings" settings) on Windows when capturing desktop audio.

### Current Behavior

When capturing desktop audio, OBS seems to also capture Windows audio enhancements, which are meant to only enhance the output of a certain audio device.

### Steps to Reproduce

Capture desktop audio with extra audio enhancements on your current audio device.

### Anything else we should know?

This issue form is annoying for reporting issues like these.

**Comment by derrod** [comment]
OBS captures the device output, including all filtering applied to it. There's no way around that as far as I'm aware. You can use the application audio capture instead if you wish to capture the raw audio emitted by an application minus any filtering applied within Windows.

Either way this is not a bug, and should be posted on the [ideas page](https://ideas.obsproject.com/) instead.
