### ISSUE TITLE
Flatpak crashes after a few seconds

### ISSUE THREAD

**Issue by RickAndTired** [obsproject/obs-studio#9245]
### Operating System Info

Other

### Other OS

Ubuntu 23.04

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/fCxOVmbM2KqcQwJd

### OBS Studio Crash Log URL

https://obsproject.com/logs/fCxOVmbM2KqcQwJd

### Expected Behavior

Flatpak OBS to open and stay open

### Current Behavior

OBS crashes after a few seconds

### Steps to Reproduce

1. Open OBS from menu
2. Do nothing
3. Crash
...

### Anything else we should know?

It only crashes when launching from the menu.
If I run OBS from the terminal `flatpak run com.obsproject.Studio` it does not crash.

**Comment by kkartaltepe** [comment]
Please provide a backtrace from gdb and remove all third party plugins.

**Comment by tytan652** [comment]
For using gdb in the Flatpak ([src](https://docs.flatpak.org/en/latest/debugging.html)):
``` sh
$ flatpak install org.freedesktop.Sdk.Debug com.obsproject.Studio.Debug # Optional: Install OBS Studio debug symbols
$ flatpak run --command=sh --devel com.obsproject.Studio
$ gdb /app/bin/obs
```

Once `gdb` ready, run by entering the command `r` and reproduce the crash.
Once done, you should be able to enter the command `bt`. Message the output of this command.
You can quit by entering the command `q`.

**Comment by kkartaltepe** [comment]
This user came to support chat, and found that all methods of running obs worked except by launching from their launcher. This included using the cli gnome launcher. Seems an issue with their launcher tool instead of obs.
