### ISSUE TITLE
With "Lock Docks" enabled, double click on a dock titlebar locks that dock in the UI

### ISSUE THREAD

**Issue by LukasThyWalls** [obsproject/obs-studio#9255]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/hKp701YJDiVRHsuh

### Expected Behavior

With "Lock Docks" enabled, any floating dock should not be locked in the UI with any movement or interaction, it should be kept floating.

### Current Behavior

With "Lock Docks" enabled, a floating dock can be locked in the UI with double clicking in the title bar, and as it is "Lock Docks" enabled, it can't be released until you disable "Lock Docks".

### Steps to Reproduce

1. Have enable "Lock Docks" in "Docks" menu.
2. Open any floating dock (example, Stats)
3. Make a double click in the title bar. The Stats dock become locked in the UI.
4. Only can be released if "Lock Docks" is disabled.

Video example:
https://github.com/obsproject/obs-studio/assets/1467366/37f83736-d85c-4f4b-991e-5d464b22d565

### Anything else we should know?

Maybe it's something about Qt docking system and is hard to fix if they don't do it, although i think it's something to look a little bit because i found constantly with issues about this because dragging the docks to clear the view when streaming sometimes suddenly it locks the dock and i think it's because i double click in the title bar by mistake.

Thanks!

**Comment by RytoEX** [comment]
When "Lock Docks" is enabled, all docks are set to `QDockWidget::NoDockWidgetFeatures`, meaning they cannot be closed, moved, or made floatable (undocked). While it's probably possible that one could conditionally exclude previously floating docks from this, that would be a feature request. As it is now, we unconditionally lock all docks, so this is by design.

**Comment by LukasThyWalls** [comment]
> When "Lock Docks" is enabled, all docks are set to `QDockWidget::NoDockWidgetFeatures`, meaning they cannot be closed, moved, or made floatable (undocked). While it's probably possible that one could conditionally exclude previously floating docks from this, that would be a feature request. **As it is now, we unconditionally lock all docks, so this is by design**.

Maybe i explained it bad because my language, but the response doesn't seems to fit what i'm talking about.

Of course i understand that you want to lock all docks when "Lock Docks" is enabled, what i'm talking about it is a floating dock can be docked when double clicking in its titlebar, no matter what "Lock Docks" is enabled or not. If "Lock Docks" is disabled, you can do it dragging it to where you want it, but with "Lock Docks" enabled, you can't, but you can still do it double clicking the titlebar.

As i understand, "Lock Docks" means to lock the UI, but double clicking in the floating docks titlebar breaks that.

PD.: If it's still considered a Feature Request, i will put there in ideas.obsproject.com but i don't see it really is...

**Comment by RytoEX** [comment]
Lock Docks does not prevent docks from being redocked. There is no `QDockWidget::DockWidgetFeature` in Qt to prevent this.

**Comment by LukasThyWalls** [comment]
I think i get it, with the actual implementation can't be done so you should be change it partially or entirely to do it, and that's not a fix and more a change of direction.

So, I posted in the ideas site the feature request here https://ideas.obsproject.com/posts/2317/with-lock-docks-enabled-lock-all-ui-in-every-way-disable-titlebar-double-click-dock

If it's like that, i see it very limited. I was expecting that at least the dock titlebar double click can be disabled, so it doesn't do anything when you double click and that will fix my recurring issue, but looking that maybe can't be done too...

Anyway, Thanks!
