### ISSUE TITLE
Build failure with qt5

### ISSUE THREAD

**Issue by jmarca** [obsproject/obs-studio#9262]
### Operating System Info

Other

### Other OS

Slackware Current

### OBS Studio Version

Git

### OBS Studio Log URL

NA

### Expected Behavior

I expected the program to compile cleanly when I chose -DQT_VERSION=5 in the cmake options, as per the build instructions.

### Current Behavior

Build fails:

```
AILED: UI/frontend-plugins/decklink-output-ui/CMakeFiles/decklink-output-ui.dir/__/__/slider-ignorewheel.cpp.o
/usr/bin/ccache /usr/bin/c++ -DENABLE_HEVC -DHAVE_OBSCONFIG_H -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -Ddecklink_output_ui_EXPORTS -I/home/james/repos/obs-related/obs-studio/build/UI/frontend-plugins/decklink-output-ui/decklink-output-ui_autogen/include -I/home/james/repos/obs-related/obs-studio/libobs -I/home/james/repos/obs-related/obs-studio/build/config -I/home/james/repos/obs-related/obs-studio/UI/obs-frontend-api -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/qt5/QtGui/5.15.10 -isystem /usr/include/qt5/QtGui/5.15.10/QtGui -isystem /usr/include/qt5/QtCore/5.15.10 -isystem /usr/include/qt5/QtCore/5.15.10/QtCore -O2 -g -DNDEBUG -std=c++17 -fPIC -Werror -Wextra -Wvla -Wswitch -Wno-error=switch -Wformat -Wformat-security -Wunused-parameter -Wno-unused-function -Wno-missing-field-initializers -fno-strict-aliasing -Wconversion-null -Wno-error=maybe-uninitialized -mmmx -msse -msse2 -fPIC -MD -MT UI/frontend-plugins/decklink-output-ui/CMakeFiles/decklink-output-ui.dir/__/__/slider-ignorewheel.cpp.o -MF UI/frontend-plugins/decklink-output-ui/CMakeFiles/decklink-output-ui.dir/__/__/slider-ignorewheel.cpp.o.d -o UI/frontend-plugins/decklink-output-ui/CMakeFiles/decklink-output-ui.dir/__/__/slider-ignorewheel.cpp.o -c /home/james/repos/obs-related/obs-studio/UI/slider-ignorewheel.cpp
/home/james/repos/obs-related/obs-studio/UI/slider-ignorewheel.cpp: In member function ‘virtual void SliderIgnoreClick::mousePressEvent(QMouseEvent*)’:
/home/james/repos/obs-related/obs-studio/UI/slider-ignorewheel.cpp:104:36: error: ‘class QMouseEvent’ has no member named ‘position’
  104 |         if (handle.contains(event->position().toPoint())) {
      |                                    ^~~~~~~~
```

### Steps to Reproduce

1.  Clean git pull into new directory on a QT5 only machine
2.  ccache --clear
3.   cmake -S .  -B build -G Ninja         -DCEF_ROOT_DIR="../obs-build-dependencies/cef_binary_5060_linux64"      -DENABLE_PIPEWIRE=ON    -DENABLE_AJA=0         -DENABLE_WEBRTC=1        -DQT_VERSION=5
4.  cmake --build build
...

### Anything else we should know?

It seems like all the QT5/6 ifdef guards were dropped a few days ago with commit a4834efde9d08110b1ab345adb8bed5dc9f7d038

```
commit a4834efde9d08110b1ab345adb8bed5dc9f7d038
Author: Sebastian Beckmann <beckmann.sebastian@outlook.de>
Date:   Sat Jun 10 17:36:11 2023 +0200

    UI: Remove Qt 5 ifdef guards and code
```

I didn't see anything in that commit that touched the cmake stuff, so I am not sure how to correctly indicate that I am compiling for qt5, not qt6.

Is qt5 support going to be dropped?  

(QT6 is not yet included in slackware-current, and my first attempt to build it failed.)

**Comment by tytan652** [comment]
https://github.com/obsproject/obs-studio/discussions/9055

We are actually removing Qt5 support.

**Comment by jmarca** [comment]
Sorry I searched but did not find that. Ah. I was looking for qt5 (no space). (GitHub search is pretty bad)JamesOn Jul 16, 2023, at 09:07, tytan652 ***@***.***> wrote:﻿
Closed #9262 as not planned.

**Comment by jmarca** [comment]
Yep, even searching for qt 5 (with space) does not show that issue. Can you perhaps rename the issue to make it findable for users like me who only recompile this project periodically? Regards,JamesOn Jul 16, 2023, at 09:32, Activimetrics ***@***.***> wrote:﻿Sorry I searched but did not find that. Ah. I was looking for qt5 (no space). (GitHub search is pretty bad)JamesOn Jul 16, 2023, at 09:07, tytan652 ***@***.***> wrote:﻿
Closed #9262 as not planned.

**Comment by RytoEX** [comment]
> Yep, even searching for qt 5 (with space) does not show that issue. Can you perhaps rename the issue to make it findable for users like me who only recompile this project periodically? Regards,James

Searching for qt 5 (without quotes) or "qt 5" brings it up as the top item in Discussions. It doesn't show up in Issues because it is not a GitHub Issue, it is a GitHub Discussion.

**Comment by jmarca** [comment]
Heh. My bad. GitHub search sucks rocks. JamesOn Jul 16, 2023, at 09:38, Ryan Foster ***@***.***> wrote:﻿

Yep, even searching for qt 5 (with space) does not show that issue. Can you perhaps rename the issue to make it findable for users like me who only recompile this project periodically? Regards,James

Searching for qt 5 (without quotes) or "qt 5" brings it up as the top item in Discussions. It doesn't show up in Issues because it is not a GitHub Issue, it is a GitHub Discussion.
