### ISSUE TITLE
Blackmagic Decklink multiple audio output

### ISSUE THREAD

**Issue by Spo-oky** [obsproject/obs-studio#9268]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.3

### OBS Studio Log URL

NA

### Expected Behavior

If OBS audio settings is configured to 7.1 audio, when it start Decklink Output, should appear the 8ch audio with sound.

### Current Behavior

when it starts decklink output it only appears 2 audio channels.

### Steps to Reproduce

1. Change OBS audio settings to 7.1
2. Go to Tools -> Decklink Output -> choose the card and press start
...

### Anything else we should know?

In outputs like Aja and NDI work's well with 8 audio channels.

Tks

**Comment by pkviet** [comment]
we hardcode the decklink output to stereo.
Here:
https://github.com/obsproject/obs-studio/blob/master/plugins/decklink/decklink-output.cpp#L72
I might fix that eventually; pinging the author of decklink ouput though: @DDRBoxman should he want to fix it.

**Comment by Spo-oky** [comment]
Thanks. It would be great to have this.

**Comment by gxalpha** [comment]
This sounds like a feature request, which we don't track using GitHub Issues (we use GitHub exclusively for bug reports).
Please put ideas and feature requests on [our ideas page](https://ideas.obsproject.com).

Thank you!
