### ISSUE TITLE
UI: MP4 warning cut off in advanced mode

### ISSUE THREAD

**Issue by CyBeRoni** [obsproject/obs-studio#9276]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.3

### OBS Studio Log URL

none

### Expected Behavior

MP4 warning to be fully visible

### Current Behavior

When "(Use stream encoder)" is selected, the warning about MP4 is cut-off due to lack of space.

### Steps to Reproduce

1. Open Output settings in Advanced mode
2. Select "(use stream encoder)" and MP4 or MOV (non-fragmented) output
3. Warning doesn't fit on screen

![image](https://github.com/obsproject/obs-studio/assets/5394358/ed231e6e-9370-4686-98c0-3df77057230d)

Looks correct in simple mode as the whole container scrolls.

**Comment by GPattenden** [comment]
Hi, I would like to take a look into this

**Comment by RytoEX** [comment]
This should have been fixed by #10337.
