### ISSUE TITLE
Unable to Start OBS in a different way

### ISSUE THREAD

**Issue by AG-YT** [obsproject/obs-studio#9280]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.3

### OBS Studio Log URL

Nothing

### Expected Behavior

I would except that the executable (obs64.exe) would open as (obs32.exe) would.

### Current Behavior

It shown me the error because it did not find "VCRUNTIME140_1.dll", "VCRUNTIME140.dll", "MSCVP140.dll", and "VCRUNTIME140.dll (again)".

### Steps to Reproduce

1. I'd open the OBS Studio folder (uncompressed with the help of Unrar)
2. I'd then open the Bin(64) and find for the executable.
3. The executable (obs64.exe) shows a warning.

### Anything else we should know?

I am a content creator that is only intended for recording as if the streaming takes a lot of hard resources in the CPU.

**Comment by notr1ch** [comment]
Please use the forums or Discord for support issues.

**Comment by AG-YT** [comment]
Alright.
