### ISSUE TITLE
Window Capture (Pipewire) menu resets when window titles change.

### ISSUE THREAD

**Issue by Envian** [obsproject/obs-studio#9281]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/pVBOCFZ77bOOY8Ld

### Expected Behavior

When selecting a screen source for a Window Capture (Pipewire) component, my selected option should remain selected until I change it, or close the menu.

### Current Behavior

When the title of any window changes, your selection will reset, regardless of whether the afflicted window is your selected option or not. This behavior has been confirmed with both the Arch Linux repo version of OBS, as well as the flatpak version, both running on Arch Linux with Gnome on Wayland.

### Steps to Reproduce

1. While running a wayland based DE, run OBS side by side with an application which has a dynamic title (I.E.  Firefox, Gnome Files), as well as a few other windows to populate the Select Window menu.
2. Add a Window Capture (Pipewire) component, and open the Select Window menu.
3. Select an option.
4. Change the title of a window  through any means (Open a folder in Gnome Files, browse to another page in Firefox)
5. Observe that your selected window has been reset.
...

### Anything else we should know?

While the steps provided are an edge case, I frequently run an application which includes a timestamp w/ seconds in the title, making this menu nearly impossible to use.

**Comment by kkartaltepe** [comment]
Unfortunately we have no control over the video streams or the selection menus on wayland, if you find those dont behave the way you expect you should file a bug against your compositor.

**Comment by Envian** [comment]
Thank you for the followup! I've opened a ticket with the Gnome team to address this. Adding a link here for visibility to anyone else who may be bothered by this issue: https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/issues/93
