### ISSUE TITLE
AVG Antivirus Identifies This as Virus-Infected

### ISSUE THREAD

**Issue by LW10111** [obsproject/obs-studio#9282]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://cdn-fastly.obsproject.com/downloads/OBS-Studio-29.1.3-Full-Installer-x64.exe

### Expected Behavior

Want to download the app without issues

### Current Behavior

Gets blocked by AVG antivirus : We've safely aborted connection on "https://cdn-fastly.obsproject.com/downloads/OBS-Studio-29.1.3-Full-Installer-x64.exe", because it was infected with URL: Blacklist.

### Steps to Reproduce

1. Simply go to OBS official website (obsproject.com) and click on download link for windows: https://cdn-fastly.obsproject.com/downloads/OBS-Studio-29.1.3-Full-Installer-x64.exe
2.
3.
...

**Comment by Fenrirthviti** [comment]
Report to AVG, we have no control over their blocklists.
