### ISSUE TITLE
CUSTOM FFMPEG OUTPUT DOES NOT USE FILTER GRAPH

### ISSUE THREAD

**Issue by PeterAkakpo** [obsproject/obs-studio#9283]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.3

### OBS Studio Log URL

N/A

### Expected Behavior

custom ffmpeg output should accept -filter:v option 

### Current Behavior

the filter:v or vf options are not used 

### Steps to Reproduce

1.  there is no settings to set filter options
2.
3.
...

**Comment by pkviet** [comment]
The custom ffmpeg is not a frontend to ffmpeg.exe It just implements avformat/avcodec to mux and encode.
Filters are therefore NOT supported.
