### ISSUE TITLE
KDE Plasma: Window Capture: error: xcb_composite_name_window_pixmap failed

### ISSUE THREAD

**Issue by iam-TJ** [obsproject/obs-studio#9284]
### Operating System Info

Other

### Other OS

Debian 12 Bookworm

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.0.2.1-1+b1

### OBS Studio Log URL

https://obsproject.com/logs/XFdfWbWY9Sz9QFDU

### Expected Behavior

Some way to capture windows still!

### Current Behavior

Unable to capture windows as previously

### Steps to Reproduce

1. Start OBS
2. Add  Window Capture (Xcomposite)
3. Select source
...

### Anything else we should know?

I've just encountered this with Debian 12 (Bookworm) amd64 and KDE Plasma desktop. It's a UX regression since Debian 11 (but I'm not attributing the cause to OBS; just making it known) - I hadn't used OBS since upgrading to Debian 12 and was confused when the several Xcomposite based window captures all failed, so went digging deeper.

As well as Pipewire window captures failing as described in Issue #7931, in my case the existing (or indeed a new) Xcomposite window capture also fails with:
```
error: xcb_composite_name_window_pixmap failed
```
as others have detailed in

https://obsproject.com/forum/threads/error-xcb_composite_name_window_pixmap-failed-and-window-capture-xcomposite-doesnt-work.164861/

Unfortunately I do not have Xorg logs from Debian 11 to see if this is some way related to the Xorg Xcomposite extension not being loaded. It isn't reported in /var/log/Xorg.0.log but I don't know if it was in Debian 11.

Plasma is set to do compositing as it was for Debian 11 so I'm currently stumped!

Screen Capture (XSHM) does work but is no good since it is capturing the entire screen not the application window.

**Comment by kkartaltepe** [comment]
You do not have a graphics card, or you do not have drivers for it. This is an unsupported configuration and you should expect many things to fail.

**Comment by iam-TJ** [comment]
What - where do you get that idea!? Of course there's a graphics card AND it has all the correct drivers, AND Plasma is happily compositing!

**Comment by iam-TJ** [comment]
Eventually tracked the cause down. After a `kexec` reboot on July 14th the kernel `radeon` driver had a problem and resulted in:
```
Jul 14 14:52:59 sunny kernel: [drm:r600_ring_test [radeon]] *ERROR* 
radeon: ring 0 test failed (scratch(0x850C)=0xCAFEDEAD)
Jul 14 14:52:59 sunny kernel: radeon 0000:0a:00.0: disabling GPU 
acceleration
```
and `/var/log/Xorg.0.log`:
```
$ grep -E 'DRI|rendering' /var/log/Xorg.0.log
[    60.448] (==) RADEON(0): DRI3 disabled
[    60.448] (WW) RADEON(0): Direct rendering disabled
[    60.510] (II) Initializing extension DRI3
[    60.510] (II) AIGLX: Screen 0 is not DRI2 capable
[    60.852] (II) GLX: Initialized DRISWRAST GL provider for screen 0
[    60.852] (II) Initializing extension XFree86-DRI
[    60.852] (II) Initializing extension DRI2
```
A power-off restart fixed it. Hope this helps someone else!
```
$ grep -E 'DRI|rendering' /var/log/Xorg.0.log
[    47.776] (II) RADEON(0): [DRI2] Setup complete
[    47.776] (II) RADEON(0): [DRI2]   DRI driver: radeonsi
[    47.776] (II) RADEON(0): [DRI2]   VDPAU driver: radeonsi
[    47.776] (==) RADEON(0): DRI3 enabled
[    47.776] (II) RADEON(0): Direct rendering enabled
[    48.026] (II) Initializing extension DRI3
[    48.034] (II) GLX: Initialized DRI2 GL provider for screen 0
[    48.034] (II) Initializing extension XFree86-DRI
[    48.034] (II) Initializing extension DRI2
```

**Comment by neruthes** [comment]
I am seeing a similar problem and `dmesg` suggests...

![image](https://github.com/user-attachments/assets/22c12948-3a5a-49a1-a427-e1f4c4afb14e)

To assist anyone that may find this issue from search engines, I will update this comment if kernel driver version matching fixes the problem.
