### ISSUE TITLE
AMF encoder not listed in standard but works under custom output.

### ISSUE THREAD

**Issue by Skyrion9** [obsproject/obs-studio#9293]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/vtCvUS6eBrospvh3

### Expected Behavior

To be able to select AMF hardware encoders (H264/H265) from video encoders.
![obsenc](https://github.com/obsproject/obs-studio/assets/74653117/e5cdb6bb-3a7a-44f4-8792-ddb772e16faf)

### Current Behavior

Only software encoders are available for Standard type recordings, however by using Custom Output (FFmpeg), I am able to use AMF. By extension, I am unable to use AMF for replay buffer.

### Steps to Reproduce

1. Open OBS 29.1.3
2. Settings > Output > Output Mode : Advanced
3. Recording > Type : Standard
4. Video Encoder : --Can't choose AMF--
![image](https://github.com/obsproject/obs-studio/assets/74653117/61c79705-7dda-4405-88b1-d9f252ec9f44)

### Anything else we should know?

I am on Adrenalin 23.7.1 (Latest driver as of this issue)
Relive works, and I can utilize AMF encoders by using Custom Output, however it is not listed in Standard mode.
It's NOT a dual GPU system, I've a CPU not an APU. (R5 1600 + RX 6700)

This is a recurring issue from previous versions, however mine is a single GPU system.

https://github.com/obsproject/obs-studio/issues/7546

Some users fixed the issue by replacing AMF libraries from 28 beta version, citing a size difference in enc-amf.pdb file.
https://obsproject.com/forum/threads/obs-28-0-0-28-0-1-amd-amf-problem-amd-ryzen-7-5700g-igpu.159318/post-587665

EDIT : Easiest workaround for this issue right now:
1- Export your profile, 
2- Open basic.ini in the exported folder and under [AdvOut] find and edit RecEncoder to this:
RecEncoder=amd_amf_h265
 
 264_texture_amf and h265_texture_amf can also be used, they are the newer implementation and work just fine for me.
 
 h264 version is amd_amf_h264, you can also edit Encoder=amd_amf_265 for streams. Finally import the edited pofile back again and restart OBS.

**Comment by Fenrirthviti** [comment]
The error as listed is a driver error, going all the way back to https://github.com/obsproject/obs-studio/issues/4689 (probably earlier even). If the driver itself is reporting that AMF isn't supported, I'm unsure if there's anything we can do. Are you able to try rolling back to an older AMD driver to see if it works properly there? This wouldn't be the first, and probably won't be the last, time that we've seen AMF break in driver updates.

**Comment by Skyrion9** [comment]
I'm unaware which drivers are confirmed to work with OBS, do you have a specific version?

**Comment by Fenrirthviti** [comment]
I don't have a specific driver version in mind, unfortunately, but someone else on the team might watch AMD a bit closer. Typically, troubleshooting you can just do n-1, and then n-2, etc. I understand it's a pain to roll back drivers, however. I've tested on my laptop (my only available AMD system) and all encoders show up just fine for me on driver version 31.0.12042.2002 as reported by OBS logs.

The error is the same:

`03:31:27.936: [AMF] <Id: 1> Unable to set converter transfer characteristic, error AMF_NOT_FOUND (code 11)`

Just occurs at different times due to different versions of OBS and the AMF plugin.

As an additional point, when using custom FFmpeg output, does AMF actually start properly or does it just show up in the list?

**Comment by Skyrion9** [comment]
> As an additional point, when using custom FFmpeg output, does AMF actually start properly or does it just show up in the list?

To clarify, I am able to use and record successfully with when choosing custom output. It works and records just fine. Going back to OBS 28 beta 1 the AMF also works fully even in standard mode, allowing for replay buffer among other things. However the implementation there is different.

I'm unsure which adrenalin version that driver version corresponds to. And this has something to do with driver changes ofcourse, but with custom output working I'm left wondering why standard won't list, or let me attempt to use it.

**Comment by Fenrirthviti** [comment]
Because custom ffmpeg output uses ffmpeg, our native implementation does not.

I can't say why the driver check is failing to report AMF support for our implementation, but FFmpeg doesn't have such checks in place.

I have no insight in to why the driver check is failing for ours, I'll have to leave that to others more familiar. Thank you for the patience and clarification/testing, it's greatly appreciated!

**Comment by flaeri** [comment]
I updated my AMD GPU to 23.7.1.
OBS reports: 31.0.21001.45002, same as your log. The AMD encoders are available to me in old profiles, and new.

Just as a precaution, could you try a new profile, and confirm its not available there (top bar -> profile -> new).

I don't see any errors relating to AMD/AMF in your log. The only quirk is failing QSV test:
`Failed to launch the QSV test process I guess`

Seeing as your don't have an Intel CPU, I can't see how it should fail. Could you try going to the top bar -> help -> check file integrity? Just want to rule that out as well.

If all else fails, I think I would personally consider doing a clean re-install of the AMD drivers. When you install it, there should be a "clean option", by clicking the little arrow pointing right.

If all else fails, and you still want to spend some time troubleshooting the issue, please ping me on discord (https://obsproject.com/discord)  `@flaeri`

**Comment by Skyrion9** [comment]
File check downloaded nothing (no corruption) and new profile changed nothing the AMF encoders are still not listed properly.

This was already a cleanly installed driver through AMD's installer. Furthermore, when I faced this issue I've done an uninstall+DDU+reinstall of my driver.

However, I've found a workaround that bypasses the UI. Afte rediting the parameters under [AdvOut] in basic.ini of the profile I've exported. Recording with AMF HEVC under Advanced output mode with Standard as the type works. Replay buffer and every setting related to AMF encoder works, the only caveat is if I switch to any other encoder and close the settings UI, the AMF encoder disappears again until I edit the .ini file. There are no parameters for B-frames, not sure if that's normal for RDNA2 cards.

![image](https://github.com/obsproject/obs-studio/assets/74653117/14d828ba-16d3-4068-87c7-794bc9f91377)


[AdvOut]
Encoder=h265_texture_amf
RecEncoder=amd_amf_h265

I found the names for the encoders by looking at OBS 28 beta 1 that was working for me, just copied over these two parameters from basic.ini profile I use with OBS 28. With everything but the UI functioning correctly, I believe this is simply an UI issue.

And to confirm again, AMF is fully functional. I've successfully recorded replays, normal recordings and fiddled with encoder settings to various different results and task manager shows activity under "Video codec 0" the HW acceleration is working.

**Comment by Fenrirthviti** [comment]
Current leading theory is that your Kaspersky AV is blocking the subprocess for encoder checks from running. In your log, it shows:

`03:31:28.100: Failed to launch the QSV test process I guess`

Which is very atypical, and can really only happen if something blocks the process, or the test executable was deleted entirely. AMF has a very similar subprocess check that runs to test capabilities.

We'd recommend uninstalling, or disabling, Kaspersky (and any other non-Defender AV) to test. This wouldn't be the first time they falsely flagged newer versions of OBS and caused issues.

**Comment by Skyrion9** [comment]
I've tried with Kaspersky completely disabled without success. And there are no files being blocked/quarantined and obs-studio\bin\64bit has both obs-qsv-test.exe and it's .pdb file. AMF test is also there.

I'm out of ideas with this and as a last resort I've replaced the existing enc-amf.dll and enc-amf..pdb with ones from OBS 28 Beta 1 (As linked in the main post, it fixed the problem for some others.) which made all AMF options available to me without issues, I can use them for streaming and recording in standard mode now.

This could be a compatibility issue between RX 6700 with current drivers and the latest AMF encoder OBS is using. I'm still puzzled by the fact that fiddling with configuration settings I can still utilize the existing AMF encoders, simply because they're now listed.

For now I'll stick to edited basic.ini with OBS 29.1.3 enc-amf.dll, as a workaround to not being able to pick them from list of encoders. I only tested 28 beta 1 DLL to confirm the others experience in how they fixed it. So the problem is narrowed down to enc-amf.dll

Here's the log of working OBS 29.1.3 with amf-encoder.dll from OBS 28 beta 1 for good measure, same lines about QSV etc. exist but the AMF encoders display and work properly (Skip the error about h265 texture, that's just improper config parameter)  : https://obsproject.com/logs/WlKyt54SUXxD8u9X


For anyone who might face the same issue, export your profile, open basic.ini and under [AdvOut] find and edit RecEncoder to this:
RecEncoder=amd_amf_h265
 
 h264 version is amd_amf_h264, you can also edit Encoder=amd_amf_265 for streams. Finally import the edited pofile back again and restart OBS.

**Comment by RytoEX** [comment]
The error message:
```
03:31:28.100: Failed to launch the QSV test process I guess
```
indicates that OBS cannot launch `obs-qsv-test.exe` at all for some reason (perhaps it is missing, or its file permissions are incorrect, or some other reason), which makes me think that OBS is similarly unable to launch `obs-amf-test.exe`.

From the obs-studio install directory, go to the sub-directory `bin\64bit`, open a terminal (Terminal, cmd, PowerShell) and run:
```
.\obs-amf-test.exe
```
Please post the results here.

As an aside, `amd_amf_h264` and `amd_amf_h265` are for the legacy obs-amd-encoder/enc-amf. This error message comes from that implementation:
```
03:31:27.936: [AMF] <Id: 1> Unable to set converter transfer characteristic, error AMF_NOT_FOUND (code 11)
```
It is odd that the test app for the legacy implementation runs, but the QSV and newer AMF test apps do not run.

The newer implementation IDs are `h264_texture_amf` and `h265_texture_amf` respectively.

The AMD encoder shows in my UI with:
* Windows 11 22H2
* CPU: AMD Ryzen 7 5800H with Radeon Graphics
* GPU0: AMD Radeon RX 6600M
* GPU1: AMD Radeon Graphics
* OBS Studio 29.1.3
* AMD driver 23.5.2 (31.0.14057.5006) or 23.7.2 (31.0.21023.2010)

**Comment by Skyrion9** [comment]
I've tried with h265_texture_amf through the same ini editing trick and it works just the same as amd_amf_h265. Here's the log of successfully recording with it, and the UI behaves the same.

https://obsproject.com/logs/yWCeBquiOk0ksXxM

Here's the console output you requested @RytoEX 
`[0]
is_amd=true
supports_avc=true
supports_hevc=true
supports_av1=false
[1]
is_amd=false
supports_avc=false
supports_hevc=false
supports_av1=false`

I doubt it has anything to do with permissions, as I ran this through a non-elevated powershell as well as elevated, the results are the same.
I'm not sure what the [0] or [1] are, I but I only have 1 GPU in my system. I've a dual monitor setup.

**Comment by RytoEX** [comment]
> I've tried with h265_texture_amf through the same ini editing trick and it works just the same as amd_amf_h265. Here's the log of successfully recording with it, and the UI behaves the same.
> 
> https://obsproject.com/logs/yWCeBquiOk0ksXxM
> 
> Here's the console output you requested @RytoEX
> 
> > [0]
> > is_amd=true
> > supports_avc=true
> > supports_hevc=true
> > supports_av1=false
> > [1]
> > is_amd=false
> > supports_avc=false
> > supports_hevc=false
> > supports_av1=false
> 
> I doubt it has anything to do with permissions, as I ran this through a non-elevated powershell as well as elevated, the results are the same. I'm not sure what the [0] or [1] are, I but I only have 1 GPU in my system. I've a dual monitor setup.

I'm not surprised that editing the encoder ID in manually works. The GPU is capable, it's just that it's hidden from the UI because the test executable (obs-amf-test.exe) is (presumably) unable to be run from OBS itself and return capabilities results, so OBS doesn't show them to you. The capabilities tests aren't re-run on encoder start.

[0] is `Adapter 0: AMD Radeon RX 6700`. [1] is Microsoft Basic Renderer (something like that), which is always enumerated and is the last entry.

On my AMD+AMD system, I do not get this log line:
```
21:04:25.010: Failed to launch the QSV test process I guess
```
Which goes back to my original concern that _something_ is preventing OBS from opening the test executables. Running them yourself from terminal just verifies that the test executables exist and work, but there are still other possible issues at play. Is OBS installed in the default location (`C:\Program Files\obs-studio`)? If not, where is it installed and what is the full path?

**Comment by RytoEX** [comment]
Please also try to launch OBS with `--verbose` and attach a log from that.

**Comment by Skyrion9** [comment]
https://obsproject.com/logs/Rb2KTTaT5ohsA8Yh

> Failed to launch the QSV test process I guess

obs-studio\obs-plugins\64bit\obs-qsv11.dll

It's related to Quicksync video, no idea why it fails but I shouldn't be surprised since I've no iGPU (not even one to check if it's intel or AMD). Maybe it doesn't fail on yours because of that.

**Comment by notr1ch** [comment]
It should still run correctly even without QSV hardware, the idea is that the test programs do the hardware checks since if the drivers crash it only takes down the test program and not all of OBS. It seems both QSV and AMF test programs are failing on your system for some reason. Perhaps antivirus or something is preventing OBS from running programs?

Running ProcMon and tracing an OBS launch might provide more insight.

**Comment by RytoEX** [comment]
> https://obsproject.com/logs/Rb2KTTaT5ohsA8Yh
> 
> > Failed to launch the QSV test process I guess
> 
> obs-studio\obs-plugins\64bit\obs-qsv11.dll
> 
> It's related to Quicksync video, no idea why it fails but I shouldn't be surprised since I've no iGPU (not even one to check if it's intel or AMD). Maybe it doesn't fail on yours because of that.

That's not the test app. The test app is at `obs-studio\bin\64bit\obs-qsv-test.exe` and is invoked from OBS itself on startup. It runs just fine on systems that don't have Intel GPUs, as I mentioned earlier:

> On my AMD+AMD system, I do not get this log line:
> 
> ```
> 21:04:25.010: Failed to launch the QSV test process I guess
> ```

**Comment by RytoEX** [comment]
Please test this artifact and let us know if the AMD encoder shows up in the OBS UI.
https://github.com/obsproject/obs-studio/suites/15499767870/artifacts/885164333

**Comment by Skyrion9** [comment]
C:\Program Files\obs-studio\bin\64bit is where obs64.exe is located, it is default path. I reinstalled OBS when I first faced this issue, with configuration reset.

What filters should I use for ProcMon? Here's trace of just opening OBS (no recording)
![image](https://github.com/obsproject/obs-studio/assets/74653117/7eb66357-d58c-4891-b2b0-34d0d46811af)

[Logfile3.zip](https://github.com/obsproject/obs-studio/files/12444223/Logfile3.zip)

**Comment by Skyrion9** [comment]
![image](https://github.com/obsproject/obs-studio/assets/74653117/35710e5e-7309-4d27-b706-20c2932e4044)
![image](https://github.com/obsproject/obs-studio/assets/74653117/c49db9fa-0b4a-4598-9b47-c176648deab4)


It works, gj!

**Comment by notr1ch** [comment]
The issue occurred because you have a file in the root of your C drive called `Program` or `Program.exe`, `Program.vbs`, etc. OBS did not quote the path properly which caused it to find that file instead of the one it expected. You may wish to delete that file as this may affect other programs too.

Regarding the encoder start error, it looks like your .ini editing is still in effect. Try swapping between the available encoders in settings so that it updates the setting properly, or make a new profile.

**Comment by RytoEX** [comment]
> EDIT : It seems to be missing a lot of encoder options, is that supposed to happen?

Yes. "AMD HW H.264 (AVC)" (texture-amf/h264_texture_amf/texture-amf-h264) is a different encoder from the older AMD encoder, which we no longer ship or support.

> EDIT2 : Celebrated too soon. ![image](https://user-images.githubusercontent.com/74653117/263422420-570ca881-d3ff-4e2a-970c-9cf4480b1180.png)
> 
> https://obsproject.com/logs/YQIODnn5AliSOww7

This is a separate issue from the encoder not being listed, and may just be due to ini editing as @notr1ch mentioned above.

**Comment by Skyrion9** [comment]
I did have a 0 byte file "Program" at C:\  . Here's what I did in OBS 29.1.3 :
1_) Deleted the file.
2_) Created new profile, restarted OBS
3_) Went to settings, the encoders are visible and recording works.

It fixed the whole thing.

![image](https://github.com/obsproject/obs-studio/assets/74653117/29bcb6e9-9512-40ca-9c1c-499c81978ffa)

![image](https://github.com/obsproject/obs-studio/assets/74653117/b1f476a4-babc-4084-8f7f-0807a3ef7468)


Can't believe not using quotes is the source of weeks of headache.

https://obsproject.com/logs/ie0RBe1NLtqXu87B verbose log of 29.1.3

Here's the artifact with verbose log as a bonus, it records just fine with new profile from 29.1.3 : https://obsproject.com/logs/8GmXNaCPo3dxXSPT

**Comment by RytoEX** [comment]
Glad to hear it. This will be closed whenever we merge the linked PR.

**Comment by Skyrion9** [comment]
Thanks for the help! Btw there's no AMD HW H.265 under streaming, so I don't think this is a complete fix. I don't stream but it's something to note.

**Comment by RytoEX** [comment]
> Thanks for the help! Btw there's no AMD HW H.265 under streaming, so I don't think this is a complete fix. I don't stream but it's something to note.

Unless you're streaming to a service that supports H.265 with a protocol that supports it, it won't show up.

**Comment by Skyrion9** [comment]
Yeah, after picking youtube RTMPS it shows up now.
