### ISSUE TITLE
OBS doesn't display some Sinhala words correctly

### ISSUE THREAD

**Issue by hanariyada** [obsproject/obs-studio#9299]
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

29.1.3

### Expected Behavior

![image](https://github.com/obsproject/obs-studio/assets/115437950/81e0ddc0-1139-4590-8699-2def7b58a265)

### Current Behavior

![image](https://github.com/obsproject/obs-studio/assets/115437950/b8d96a9c-bcad-45c0-a27d-4fc4dd7aa0f7)

### Anything else we should know?

Language: Sinhala
Script: Sinhala
System Font: Noto Sans/Serif Sinhala

**Comment by kkartaltepe** [comment]
Happens on my machine with the chosen language. We shouldnt see combining characters displayed in the (stippled circles) in the menu bar.

Are there any other places where this occurs?

**Comment by kkartaltepe** [comment]
In the translation files I see `File` menu as `&ගොනුව` Which appears to match the recommended value. So the translations seem probably correct in the repository at least.

**Comment by kkartaltepe** [comment]
Looks like a bug in QT's underlining code where they split the text run which prevents proper combining. Removing the `&` fixes rendering.

**Comment by kkartaltepe** [comment]
The same line in an arabic font appears to use a separate bit of text for hotkeys

`Basic.MainMenu.File="ﻢﻠﻓ (&F)"`

Likely you (or someone else) will need to update the translations to move the `&` to separate text like arabic languages have. At least for when the hotkey'ed character is part of a composed/cursive symbol.

**Comment by hanariyada** [comment]
>Likely you (or someone else) will need to update the translations on CrowdIn to move the & to separate text like arabic languages have. At least for when the hotkey'ed character is part of a composed/cursive symbol.

I discussed that problem with helabasa team. Please check OBS with the latest changes.

![image](https://github.com/obsproject/obs-studio/assets/115437950/f1f5e452-2dd2-4015-abae-b18c6f3ccc4d)

**Comment by kkartaltepe** [comment]
Updated translations are always pulled before the next release, so you should see your changes in the repository eventually.

Thanks for updating the translations.
