### ISSUE TITLE
inaccurate capture with utvideo on windows

### ISSUE THREAD

**Issue by tari3x** [obsproject/obs-studio#9312]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/vG0oUpz9fFQiocZ6

### Expected Behavior

When recording my screen with utvideo (tremendously large file size) I expect the captured video to be pixel-by-pixel identical to the screen. 

### Current Behavior

This works as expected on linux but not on windows: the captured image has slightly different colours and more importantly, it looks as if it is trying to scale the image by something like 1.001 - so the screen is a teeny-tiny stretched in the video, which of course results in blur cause pixels don't map to pixels any more. 

Here's the actual screen:
<img width="1920" alt="screen" src="https://github.com/obsproject/obs-studio/assets/374071/e0d7571a-b116-430c-9718-6d13c8c4f8ce">

Here's a video frame:
![frame](https://github.com/obsproject/obs-studio/assets/374071/2bf255f6-711c-4327-8239-2876926d7217)

Some things I tried: setting windows scaling to 100% (didn't help), trying other colour formats and colour spaces.

I have nvidia A6000 with latest nvidia drivers. I run windows in a virtual machine (QEMU), with graphics card pass-through, so I very much doubt that virtualization is an issue.  

### Steps to Reproduce

See above, I think the description containsall the relevant info.

**Comment by tari3x** [comment]
Followup: I was able to figure out the stretch. If you select the source and the go into edit -> transform, the numbers for the scaling were a very tiny bit off, and one number was even fractional. I don't remember changing those settings, let alone putting a fractional number in - is there anything automated that ever computes this? I once tried to capture 800x600 into 4k, perhaps that tripped it?

A bit of a grumble regarding UI design: there's the "settings" button at the bottom and everything about it makes you feel like these are "all the settings" but they are not.

The colour problem still remains - NV12 records smoothly, but gives me incorrect colours, RGBA records corrects colours, but gives me "Encoder overloaded" for no apparent reason. I'll start a separate thread on that.

**Comment by Fenrirthviti** [comment]
Going to close give then above, and that this sounds more like a support issue than a bug report. If you need assistance on performance issues or on expected results when converting color formats/spaces, please use the normal support channels in our Discord or forums.

**Comment by tari3x** [comment]
I think the unresolved part here are the strange fractional numbers that I found in the transform. If there is any piece of code that fills those in automatically, I think this points to a bug in that code.
