### ISSUE TITLE
Docks don't snap into main window

### ISSUE THREAD

**Issue by Milliw** [obsproject/obs-studio#9318]
### Operating System Info

Other

### Other OS

Nobara 38 Linux

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/HXn6nhCWOoYvyTaq

### Expected Behavior

Grab a floating dock and drag it to main window where it snaps in place then

### Current Behavior

Docks do not snap into main window. No matter which one.

### Steps to Reproduce

1.
2.
3.
...

### Anything else we should know?

Gnome 44, Wayland

**Comment by kkartaltepe** [comment]
Qt's dock implementation is generally fairly broken in wayland, and we cant do much other than ask you file bugs upstream.

**Comment by tytan652** [comment]
It's an Qt issue, there is no reason to keep it open on our issue tracker.

The required Wayland protocol is not even merged upstream https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/204 so once merged it will be up to compositors to implement it.

**Comment by Milliw** [comment]
@tytan652 Thanks for your information.

I worked around by launching a X session and setting it up there and then go back to Wayland. Just can't rearrange there because that gets the docks floating immediately. But I can live with that. =)
