### ISSUE TITLE
Browser sources failing to clear when clearing scene data on collection switch, forcing OBS exit

### ISSUE THREAD

**Issue by SuperZooper3** [obsproject/obs-studio#9319]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/jxRUsRklbovV4EfY

### Expected Behavior

I should be able to switch scene collections, and OBS should be able to deal with any kinds of even buggy browser sources when closing them, like most standard web browsers should.

### Current Behavior

Instead, this popup apears and forces me to close OBS.

![image](https://github.com/obsproject/obs-studio/assets/54122151/4343d564-66ee-4876-9008-1ce22b87ee44)

It traps me inside this scene collection.

### Steps to Reproduce

1. Add https://ctt-board.herokuapp.com/obs/players/tiyo/total (an internal webiste we use) to a browser source
2. Save the browser source and scene collection
3. Switch scene collection
4. Observe hard-lock / forceed exit

**Comment by derrod** [comment]
It's not the browser source, it's your python script.

**Comment by SuperZooper3** [comment]
Interesting. Thanks for trying to reproduce it. Is there something in specific that tells you that it would be the Python script?

In trying to look through the logs, the only things I see comming up from the Python script that might be indicative of a problem are these lines:
```23:31:00.393: obs_source_update: Null 'source' parameter```

Here is the python script in question:
```# A proxy file to update OBS browser sources
import obspython as obs
import json

datafile_directory = ""
last_data = {}
 
def update(mode = "normal"):
    try:
        global last_data
        with open(datafile_directory, "r") as f:
            data = json.load(f)
            if data != last_data or mode == "force":
                last_data = data
                
                # Update all the data
                for key in data:
                    try:
                        source = obs.obs_get_source_by_name(key)

                        settings = obs.obs_data_create()
                        obs.obs_data_set_string(settings, "url", data[key])
                        obs.obs_source_update(source, settings)
                        obs.obs_data_release(settings) # #NoMemLeaks
                        print("Set " + key + " to " + data[key])

                    except:
                        print("Source not found: " + key)
    except:
        print(f"Error loading datafile: {datafile_directory}")
        return

def refresh_pressed(props, prop):
    update(mode = "force") 

# OBS SETTINGS STUFF------------------------------------------------------------

def script_description():
    return "Set OBS properties bassed off JSON\n\nBy SuperZooper3"

def script_update(settings): # Sets the python variables to what is in OBS
    global datafile_directory

    datafile_directory = obs.obs_data_get_string(settings, "datadirectory")

    # Lil timer to make it automaticaly refresh every 5 minutes
    obs.timer_remove(update)

    if datafile_directory != "":
        obs.timer_add(update, 1000) # refresh every second :)

def script_defaults(settings): # Sets the defaults for the values in the obs editor
    obs.obs_data_set_default_string(settings, "datadirectory", "")

def script_properties(): # Get the property boxes so we can type them in in the scripts pannel
    props = obs.obs_properties_create()

    obs.obs_properties_add_path(props, "datadirectory", "Source data directory", obs.OBS_PATH_FILE, "", "")

    # Button to refresh the PAGE
    obs.obs_properties_add_button(props, "button", "Refresh", refresh_pressed)
    return props
```

On line 25 I do try and release the browser sources, could this be poorly done?

`obs.obs_data_release(settings)`

**Comment by derrod** [comment]
You're only releasing the data, not the source.

**Comment by SuperZooper3** [comment]
Oh! I hadn't noticed that I had to do but, but given the OBS pattern, it makes sense.

For anyone else who stumbles into this issue later, just make sure to add `obs.obs_source_release(source)` once you're done dealing with it. Thanks for the help @derrod <3
