### ISSUE TITLE
OBS does not remember window sources

### ISSUE THREAD

**Issue by Milliw** [obsproject/obs-studio#9327]
### Operating System Info

Other

### Other OS

Nobara 38 (Fedora 38 based)

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/0n2JA3SBCjP3B3t5

### Expected Behavior

Created sources should remember their sources

### Current Behavior

Created sources do not remember their sources on every restart

### Steps to Reproduce

1. Create new source (e.g. window pipewire)
2. Select window source in OS popup
3. Save source
4. Restart OBS
5. OS popup will occur again asking for window selection

### Anything else we should know?

Sometimes there are even OS window selection popups that don't react to user input meaning they can't even be clicked away.

Tried on system provided rpm version and official flatpak version as well as under X and Wayland.

**Comment by kkartaltepe** [comment]
This is by design in the xdg portal, if you dislike it please report issues there.

**Comment by Milliw** [comment]
> This is by design in the xdg portal, if you dislike it please report issues there.

Isn't xdg-desktop-portal only used by/for flatpack software?
Oh and also I get `xdg-desktop-portal-gnome killed by SIGSEGV` sometimes when starting OBS. It then immediately closes but then starts as usual. Or is this also not "OBS fault"?
