### ISSUE TITLE
Source Visibility Toggle only works in preview when in studio mode

### ISSUE THREAD

**Issue by rafpd2215** [obsproject/obs-studio#9329]
### Operating System Info

Windows 11

### Other OS

Windows 10

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/ofG2K2evRDtphBuH

### Expected Behavior

If the scene is live in Program and I toggle on/of a source within that scene I expected it to do it in both preview and program when in studio mode. 

### Current Behavior

It currently only does it in Preview even if the same scene is live in Program. 

Point is, I had a source visible toggle on/off button on my stream deck and now it doesn't work. But neither does manually toggling in OBS either

### Steps to Reproduce

1.Toggle Source on/off while scene is in both preview and program
2.
3.
...

**Comment by derrod** [comment]
This is not a bug, but intentional behaviour. After all, the point of studio mode is to be able to modify a scene *before* it goes live.

To have changes in the preview be reflected immediately uncheck "Duplicate Scene" after clicking on the button with the vertical three dots.
