### ISSUE TITLE
Windows11 versionconfig.cmake:65 list index: 1 out of range (-1, 0)

### ISSUE THREAD

**Issue by haydenzhourepo** [obsproject/obs-studio#9333]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/help

### Expected Behavior

run `cmake --preset windows-x64` successfully

### Current Behavior

run `cmake --preset windows-x64` throw error:
CMake Error at cmake/common/versionconfig.cmake:65 (list):
  list index: 1 out of range (-1, 0)
Call Stack (most recent call first):
  cmake/common/bootstrap.cmake:56 (include)
  CMakeLists.txt:4 (include)

I have investigated this because the var `_obs_version_canonical`  extracted from the command  only have one element, so the list index out of range.

![image](https://github.com/obsproject/obs-studio/assets/21101605/87df1ed7-452d-49f2-a118-7df48888ee62)

### Steps to Reproduce

1. git clone repository
2. execute command `cmake --preset windows-x64`

### Anything else we should know?

I can not find the log Files menu on this website https://obsproject.com/help

**Comment by PatTheMav** [comment]
How did you clone the repo? The reproduction steps are precisely what we do on CI and there are no issues with that.

One scenario I could imagine would be a shallow clone without full history and all tags which would lead to `git describe` not yielding a semantic version string.

We don’t support building with a shallow clone however - in that case you’d have to specify a version override to ensure a semantic version string.

**Comment by PatTheMav** [comment]
Closing this as there was no response in 2 weeks. Currently indicates that the repository wasn't fully checked out (including full commit history).

> [!NOTE]
> Building obs-studio with a sparse checkout will require providing an `OBS_VERSION_OVERRIDE` as we rely on `git describe` to get a version number from a commit tag. That requires that at least the entire commit history until the tagged release is fetched, which a sparse checkout cannot provide. Thus this works as intended.

**Comment by danieloneill** [comment]
I think you're bang on here. I tried a shallow clone and it was entirely unbuildable. I know, reviving an old report, but it's worth discussion, I think.

Requiring a feature of the CVS to cleanly build might be overkill? How about something simpler like $(git rev-parse HEAD) instead? 

Even then, assuming that the source came from git (and requiring it to be to build cleanly) kinda smells bad...

**Comment by PatTheMav** [comment]
> I think you're bang on here. I tried a shallow clone and it was entirely unbuildable. I know, reviving an old report, but it's worth discussion, I think.
> 
> Requiring a feature of the CVS to cleanly build might be overkill? How about something simpler like $(git rev-parse HEAD) instead?
> 
> Even then, assuming that the source came from git (and requiring it to be to build cleanly) kinda smells bad...

IMO it should not be necessary to use `git` at all - we already have a build specification file, the program version as well as the `libobs` API version should be maintained there as a baseline and CVS information is then used to extend that if available (both versions are coupled right now which is also not semantically "correct").

Alas that's not how the project was set up, so it would be a somewhat disruptive change to the current build system that would need to be developed in such a way to not disrupt current maintainers' setups and also needs to work with all current CI workflows, some of which might have the opposite opinion of mine (namely that version managed should only ever be done via `git`)
