### ISSUE TITLE
Image Slide Show 'Randomise Playback' option loops the slideshow

### ISSUE THREAD

**Issue by biosmatrix123** [obsproject/obs-studio#9342]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/96avj0qWMfySH82T

### Expected Behavior

I expected the slide show to show the images in the playlist in a random order, then stop.

It seems the randomise option literally chooses an item from the playlist at random and continues indefinitely.

### Current Behavior

Using the 'randomise playback' option has the same effect as the 'Loop' option (though images from the playlist are shown randomly).

### Steps to Reproduce

1. Add the image slide show source and configure it to look at a folder of images
2. Enable the 'Randomise Playback' option and ensure 'Loop' is not enabled
3. After the slide show starts, it will never stop / finish

### Anything else we should know?

Could this be improved so that a playlist is built in a random order and 'Randomise Playback' option becomes 'Play the images in a random order'. There is no repeat protection currently, so random really is random and could in theory end up showing the same images repeatedly.

**Comment by derrod** [comment]
Works as intended. Frature requests go on https://ideas.obsproject.com/

**Comment by biosmatrix123** [comment]
This is working as intended? What does the loop function do if 'Randomise Playback' is in use? Seems a strange way of labeling things to me. I won't submit a feature request as I doubt it will get any traction but thanks anyway.
