### ISSUE TITLE
Using pipewire to capture the screen and turn on the virtual camera causes the Linux desktop to crash.

### ISSUE THREAD

**Issue by ashixu** [obsproject/obs-studio#9346]
### Operating System Info

Other

### Other OS

Arch linux

### OBS Studio Version

29.1.3

### OBS Studio Log URL

01:02:18.157: Platform: Wayland 01:02:18.157: CPU Name: AMD Ryzen 7 6800H with Radeon Graphics 01:02:18.157: CPU Speed: 1972.818MHz 01:02:18.158: Physical Cores: 8, Logical Cores: 16 01:02:18.158: Physical Memory: 14744MB Total, 11886MB Free 01:02:18.158: Kernel Version: Linux 6.4.6-arch1-1 01:02:18.158: Distribution: "Arch Linux" Unknown 01:02:18.158: Desktop Environment: Hyprland 01:02:18.158: Session Type: wayland 01:02:18.159: Qt Version: 6.5.2 (runtime), 6.5.1 (compiled) 01:02:18.159: Portable mode: false 01:02:18.187: OBS 29.1.3-1 (linux) 01:02:18.187: --------------------------------- 01:02:18.187: --------------------------------- 01:02:18.187: audio settings reset: 01:02:18.187: 	samples per sec: 48000 01:02:18.187: 	speakers:        2 01:02:18.187: 	max buffering:   960 milliseconds 01:02:18.187: 	buffering type:  dynamically increasing 01:02:18.188: --------------------------------- 01:02:18.188: Initializing OpenGL... 01:02:18.188: Using EGL/Wayland 01:02:18.220: Initialized EGL 1.5 01:02:18.230: Loading up OpenGL on adapter AMD AMD Radeon Graphics (rembrandt, LLVM 15.0.7, DRM 3.52, 6.4.6-arch1-1) 01:02:18.230: OpenGL loaded successfully, version 4.6 (Core Profile) Mesa 23.1.4, shading language 4.60 01:02:18.250: --------------------------------- 01:02:18.250: video settings reset: 01:02:18.250: 	base resolution:   2240x1400 01:02:18.250: 	output resolution: 2240x1400 01:02:18.250: 	downscale filter:  Bicubic 01:02:18.250: 	fps:               30/1 01:02:18.250: 	format:            NV12 01:02:18.250: 	YUV mode:          Rec. 709/Partial 01:02:18.250: NV12 texture support not available 01:02:18.250: P010 texture support not available 01:02:18.253: Audio monitoring device: 01:02:18.253: 	name: Default 01:02:18.253: 	id: default 01:02:18.253: --------------------------------- 01:02:18.261: Failed to load 'en-US' text for module: 'decklink-captions.so' 01:02:18.267: Failed to load 'en-US' text for module: 'decklink-output-ui.so' 01:02:18.272: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed 01:02:18.272: Failed to initialize module 'decklink.so' 01:02:18.354: [pipewire] Available captures: 01:02:18.354: [pipewire]     - Desktop capture 01:02:18.380: VAAPI: API version 1.19 01:02:18.382: FFmpeg VAAPI H264 encoding supported 01:02:18.389: FFmpeg VAAPI HEVC encoding supported 01:02:18.433: --------------------------------- 01:02:18.433:   Loaded Modules: 01:02:18.433:     text-freetype2.so 01:02:18.433:     rtmp-services.so 01:02:18.433:     obs-x264.so 01:02:18.433:     obs-vst.so 01:02:18.433:     obs-transitions.so 01:02:18.433:     obs-outputs.so 01:02:18.433:     obs-libfdk.so 01:02:18.433:     obs-filters.so 01:02:18.433:     obs-ffmpeg.so 01:02:18.433:     linux-v4l2.so 01:02:18.433:     linux-pulseaudio.so 01:02:18.433:     linux-pipewire.so 01:02:18.433:     linux-jack.so 01:02:18.433:     linux-capture.so 01:02:18.433:     linux-alsa.so 01:02:18.433:     image-source.so 01:02:18.433:     frontend-tools.so 01:02:18.433:     decklink-output-ui.so 01:02:18.433:     decklink-captions.so 01:02:18.433: --------------------------------- 01:02:18.433: ==== Startup complete =============================================== 01:02:18.468: All scene data cleared 01:02:18.468: ------------------------------------------------ 01:02:18.472: pulse-input: Server name: 'PulseAudio (on PipeWire 0.3.76) 15.0.0' 01:02:18.472: pulse-input: Audio format: s32le, 48000 Hz, 2 channels 01:02:18.472: pulse-input: Started recording from 'alsa_output.pci-0000_33_00.6.HiFi__hw_Generic_1__sink.monitor' (default) 01:02:18.472: [Loaded global audio device]: 'Desktop Audio' 01:02:18.472: pulse-input: Server name: 'PulseAudio (on PipeWire 0.3.76) 15.0.0' 01:02:18.473: pulse-input: Audio format: s32le, 48000 Hz, 2 channels 01:02:18.473: pulse-input: Started recording from 'alsa_input.pci-0000_33_00.6.HiFi__hw_acp6x__source' (default) 01:02:18.473: PipeWire initialized 01:02:18.474: Switched to scene 'Scene' 01:02:18.474: ------------------------------------------------ 01:02:18.474: Loaded scenes: 01:02:18.474: - scene 'Scene': 01:02:18.474:     - source: '音频输入采集(PulseAudio)' (pulse_input_capture) 01:02:18.474:     - source: '屏幕采集(PipeWire)' (pipewire-desktop-capture-source) 01:02:18.474: ------------------------------------------------ 01:02:18.502: [pipewire] Screencast session created 01:02:18.514: [pipewire] Asking for desktop 01:02:18.525: [pipewire] desktop selected, setting up screencast 01:02:18.529: [pipewire] Server version: 0.3.76 01:02:18.529: [pipewire] Library version: 0.3.76 01:02:18.529: [pipewire] Header version: 0.3.72 01:02:18.529: [pipewire] Created stream 0x5651fb432db0 01:02:18.529: [pipewire] Stream 0x5651fb432db0 state: "connecting" (error: none) 01:02:18.529: [pipewire] Playing stream 0x5651fb432db0 01:02:18.529: [pipewire] Stream 0x5651fb432db0 state: "paused" (error: none) 01:02:18.531: [pipewire] Negotiated format: 01:02:18.531: [pipewire]     Format: 8 (Spa:Enum:VideoFormat:BGRx) 01:02:18.531: [pipewire]     Modifier: 0x0 01:02:18.531: [pipewire]     Size: 2240x1400 01:02:18.531: [pipewire]     Framerate: 0/1 01:02:18.531: [pipewire] Negotiated format: 01:02:18.531: [pipewire]     Format: 8 (Spa:Enum:VideoFormat:BGRx) 01:02:18.531: [pipewire]     Modifier: 0x20000001056bb03 01:02:18.531: [pipewire]     Size: 2240x1400 01:02:18.531: [pipewire]     Framerate: 0/1 01:02:18.532: [pipewire] Stream 0x5651fb432db0 state: "streaming" (error: none) 01:02:19.041: adding 42 milliseconds of audio buffering, total audio buffering is now 42 milliseconds (source: Desktop Audio) 01:02:19.041:  01:02:42.918: [pipewire] buffer is corrupt 01:02:42.934: [pipewire] buffer is corrupt 01:02:42.951: [pipewire] buffer is corrupt 01:02:42.967: [pipewire] buffer is corrupt 01:02:42.984: [pipewire] buffer is corrupt 01:02:43.001: [pipewire] buffer is corrupt 01:02:43.018: [pipewire] buffer is corrupt 01:02:43.035: [pipewire] buffer is corrupt 01:02:43.052: [pipewire] buffer is corrupt 01:02:43.069: [pipewire] buffer is corrupt 01:02:43.085: [pipewire] buffer is corrupt 01:02:43.101: [pipewire] buffer is corrupt 01:02:43.118: [pipewire] buffer is corrupt 01:02:43.135: [pipewire] buffer is corrupt 01:02:43.151: [pipewire] buffer is corrupt 01:02:43.168: [pipewire] buffer is corrupt 01:02:43.185: [pipewire] buffer is corrupt 01:02:43.202: [pipewire] buffer is corrupt 01:02:43.218: [pipewire] buffer is corrupt 01:02:43.235: [pipewire] buffer is corrupt 01:02:43.252: [pipewire] buffer is corrupt 01:02:43.268: [pipewire] buffer is corrupt 01:02:43.285: [pipewire] buffer is corrupt 01:02:43.302: [pipewire] buffer is corrupt 01:02:43.319: [pipewire] buffer is corrupt 01:02:43.335: [pipewire] buffer is corrupt 01:02:43.352: [pipewire] buffer is corrupt 01:02:43.369: [pipewire] buffer is corrupt 01:02:43.386: [pipewire] buffer is corrupt 01:02:43.402: [pipewire] buffer is corrupt 01:02:43.419: [pipewire] buffer is corrupt

### Expected Behavior

01:02:18.157: Platform: Wayland
01:02:18.157: CPU Name: AMD Ryzen 7 6800H with Radeon Graphics
01:02:18.157: CPU Speed: 1972.818MHz
01:02:18.158: Physical Cores: 8, Logical Cores: 16
01:02:18.158: Physical Memory: 14744MB Total, 11886MB Free
01:02:18.158: Kernel Version: Linux 6.4.6-arch1-1
01:02:18.158: Distribution: "Arch Linux" Unknown
01:02:18.158: Desktop Environment: Hyprland
01:02:18.158: Session Type: wayland
01:02:18.159: Qt Version: 6.5.2 (runtime), 6.5.1 (compiled)
01:02:18.159: Portable mode: false
01:02:18.187: OBS 29.1.3-1 (linux)
01:02:18.187: ---------------------------------
01:02:18.187: ---------------------------------
01:02:18.187: audio settings reset:
01:02:18.187: 	samples per sec: 48000
01:02:18.187: 	speakers:        2
01:02:18.187: 	max buffering:   960 milliseconds
01:02:18.187: 	buffering type:  dynamically increasing
01:02:18.188: ---------------------------------
01:02:18.188: Initializing OpenGL...
01:02:18.188: Using EGL/Wayland
01:02:18.220: Initialized EGL 1.5
01:02:18.230: Loading up OpenGL on adapter AMD AMD Radeon Graphics (rembrandt, LLVM 15.0.7, DRM 3.52, 6.4.6-arch1-1)
01:02:18.230: OpenGL loaded successfully, version 4.6 (Core Profile) Mesa 23.1.4, shading language 4.60
01:02:18.250: ---------------------------------
01:02:18.250: video settings reset:
01:02:18.250: 	base resolution:   2240x1400
01:02:18.250: 	output resolution: 2240x1400
01:02:18.250: 	downscale filter:  Bicubic
01:02:18.250: 	fps:               30/1
01:02:18.250: 	format:            NV12
01:02:18.250: 	YUV mode:          Rec. 709/Partial
01:02:18.250: NV12 texture support not available
01:02:18.250: P010 texture support not available
01:02:18.253: Audio monitoring device:
01:02:18.253: 	name: Default
01:02:18.253: 	id: default
01:02:18.253: ---------------------------------
01:02:18.261: Failed to load 'en-US' text for module: 'decklink-captions.so'
01:02:18.267: Failed to load 'en-US' text for module: 'decklink-output-ui.so'
01:02:18.272: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
01:02:18.272: Failed to initialize module 'decklink.so'
01:02:18.354: [pipewire] Available captures:
01:02:18.354: [pipewire]     - Desktop capture
01:02:18.380: VAAPI: API version 1.19
01:02:18.382: FFmpeg VAAPI H264 encoding supported
01:02:18.389: FFmpeg VAAPI HEVC encoding supported
01:02:18.433: ---------------------------------
01:02:18.433:   Loaded Modules:
01:02:18.433:     text-freetype2.so
01:02:18.433:     rtmp-services.so
01:02:18.433:     obs-x264.so
01:02:18.433:     obs-vst.so
01:02:18.433:     obs-transitions.so
01:02:18.433:     obs-outputs.so
01:02:18.433:     obs-libfdk.so
01:02:18.433:     obs-filters.so
01:02:18.433:     obs-ffmpeg.so
01:02:18.433:     linux-v4l2.so
01:02:18.433:     linux-pulseaudio.so
01:02:18.433:     linux-pipewire.so
01:02:18.433:     linux-jack.so
01:02:18.433:     linux-capture.so
01:02:18.433:     linux-alsa.so
01:02:18.433:     image-source.so
01:02:18.433:     frontend-tools.so
01:02:18.433:     decklink-output-ui.so
01:02:18.433:     decklink-captions.so
01:02:18.433: ---------------------------------
01:02:18.433: ==== Startup complete ===============================================
01:02:18.468: All scene data cleared
01:02:18.468: ------------------------------------------------
01:02:18.472: pulse-input: Server name: 'PulseAudio (on PipeWire 0.3.76) 15.0.0'
01:02:18.472: pulse-input: Audio format: s32le, 48000 Hz, 2 channels
01:02:18.472: pulse-input: Started recording from 'alsa_output.pci-0000_33_00.6.HiFi__hw_Generic_1__sink.monitor' (default)
01:02:18.472: [Loaded global audio device]: 'Desktop Audio'
01:02:18.472: pulse-input: Server name: 'PulseAudio (on PipeWire 0.3.76) 15.0.0'
01:02:18.473: pulse-input: Audio format: s32le, 48000 Hz, 2 channels
01:02:18.473: pulse-input: Started recording from 'alsa_input.pci-0000_33_00.6.HiFi__hw_acp6x__source' (default)
01:02:18.473: PipeWire initialized
01:02:18.474: Switched to scene 'Scene'
01:02:18.474: ------------------------------------------------
01:02:18.474: Loaded scenes:
01:02:18.474: - scene 'Scene':
01:02:18.474:     - source: '音频输入采集(PulseAudio)' (pulse_input_capture)
01:02:18.474:     - source: '屏幕采集(PipeWire)' (pipewire-desktop-capture-source)
01:02:18.474: ------------------------------------------------
01:02:18.502: [pipewire] Screencast session created
01:02:18.514: [pipewire] Asking for desktop
01:02:18.525: [pipewire] desktop selected, setting up screencast
01:02:18.529: [pipewire] Server version: 0.3.76
01:02:18.529: [pipewire] Library version: 0.3.76
01:02:18.529: [pipewire] Header version: 0.3.72
01:02:18.529: [pipewire] Created stream 0x5651fb432db0
01:02:18.529: [pipewire] Stream 0x5651fb432db0 state: "connecting" (error: none)
01:02:18.529: [pipewire] Playing stream 0x5651fb432db0
01:02:18.529: [pipewire] Stream 0x5651fb432db0 state: "paused" (error: none)
01:02:18.531: [pipewire] Negotiated format:
01:02:18.531: [pipewire]     Format: 8 (Spa:Enum:VideoFormat:BGRx)
01:02:18.531: [pipewire]     Modifier: 0x0
01:02:18.531: [pipewire]     Size: 2240x1400
01:02:18.531: [pipewire]     Framerate: 0/1
01:02:18.531: [pipewire] Negotiated format:
01:02:18.531: [pipewire]     Format: 8 (Spa:Enum:VideoFormat:BGRx)
01:02:18.531: [pipewire]     Modifier: 0x20000001056bb03
01:02:18.531: [pipewire]     Size: 2240x1400
01:02:18.531: [pipewire]     Framerate: 0/1
01:02:18.532: [pipewire] Stream 0x5651fb432db0 state: "streaming" (error: none)
01:02:19.041: adding 42 milliseconds of audio buffering, total audio buffering is now 42 milliseconds (source: Desktop Audio)
01:02:19.041: 
01:02:42.918: [pipewire] buffer is corrupt
01:02:42.934: [pipewire] buffer is corrupt
01:02:42.951: [pipewire] buffer is corrupt
01:02:42.967: [pipewire] buffer is corrupt
01:02:42.984: [pipewire] buffer is corrupt
01:02:43.001: [pipewire] buffer is corrupt
01:02:43.018: [pipewire] buffer is corrupt
01:02:43.035: [pipewire] buffer is corrupt
01:02:43.052: [pipewire] buffer is corrupt
01:02:43.069: [pipewire] buffer is corrupt
01:02:43.085: [pipewire] buffer is corrupt
01:02:43.101: [pipewire] buffer is corrupt
01:02:43.118: [pipewire] buffer is corrupt
01:02:43.135: [pipewire] buffer is corrupt
01:02:43.151: [pipewire] buffer is corrupt
01:02:43.168: [pipewire] buffer is corrupt
01:02:43.185: [pipewire] buffer is corrupt
01:02:43.202: [pipewire] buffer is corrupt
01:02:43.218: [pipewire] buffer is corrupt
01:02:43.235: [pipewire] buffer is corrupt
01:02:43.252: [pipewire] buffer is corrupt
01:02:43.268: [pipewire] buffer is corrupt
01:02:43.285: [pipewire] buffer is corrupt
01:02:43.302: [pipewire] buffer is corrupt
01:02:43.319: [pipewire] buffer is corrupt
01:02:43.335: [pipewire] buffer is corrupt
01:02:43.352: [pipewire] buffer is corrupt
01:02:43.369: [pipewire] buffer is corrupt
01:02:43.386: [pipewire] buffer is corrupt
01:02:43.402: [pipewire] buffer is corrupt
01:02:43.419: [pipewire] buffer is corrupt

### Current Behavior

Using pipewire to capture the screen and turn on the virtual camera causes the Linux desktop to crash. 

### Steps to Reproduce

1. lanch obs
2. Using pipewire to capture the screen and turn on the virtual camera
3. wait about 30 minuts
...

### Anything else we should know?

And my vm is hyprland, it report bug as following:
```
--------------------------------------------
   Hyprland Crash Report
--------------------------------------------
"stable"

Hyprland received signal 11 (Segmentation fault)

Version: b08b72358ad549fd066e5be0fc3aa4c9df367607
Tag: v0.27.2

System info:
	System name: Linux
	Node name: Arch
	Release: 6.4.6-arch1-1
	Version: #1 SMP PREEMPT_DYNAMIC Mon, 24 Jul 2023 20:19:38 +0000

GPU:
	33:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Rembrandt [Radeon 680M] [1002:1681] (rev 02) (prog-if 00 [VGA controller])


os-release:
	NAME="Arch Linux"
	PRETTY_NAME="Arch Linux"
	ID=arch
	BUILD_ID=rolling
	ANSI_COLOR="38;2;23;147;209"
	HOME_URL="https://archlinux.org/"
	DOCUMENTATION_URL="https://wiki.archlinux.org/"
	SUPPORT_URL="https://bbs.archlinux.org/"
	BUG_REPORT_URL="https://bugs.archlinux.org/"
	PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
	LOGO=archlinux-logo
	


Backtrace:
	#0 | Hyprland(_ZN13CrashReporter18createAndSaveCrashEi+0x458) [0x564f3858fe88]
		??
		??:0
	#1 | Hyprland(_Z25handleUnrecoverableSignali+0x47) [0x564f38528a37]
		??
		??:0
	#2 | /usr/lib/libc.so.6(+0x39ab0) [0x7fdf22362ab0]
		??
		??:0
	#3 | Hyprland(_ZN15CHyprOpenGLImpl31renderTextureInternalWithDamageERK8CTextureP7wlr_boxfP15pixman_region32ibbbb+0xf0) [0x564f386101d0]
		??
		??:0
	#4 | Hyprland(_ZN15CHyprOpenGLImpl13renderTextureERK8CTextureP7wlr_boxfibb+0x46) [0x564f38610d66]
		??
		??:0
	#5 | Hyprland(_ZN15CHyprOpenGLImpl13renderTextureEP11wlr_textureP7wlr_boxfib+0x65) [0x564f38613995]
		??
		??:0
	#6 | Hyprland(_Z13renderSurfaceP11wlr_surfaceiiPv+0x435) [0x564f38613ec5]
		??
		??:0
	#7 | /usr/lib/libwlroots.so.12032(+0x7b10e) [0x7fdf22d9a10e]
		??
		??:0
	#8 | Hyprland(_ZN13CHyprRenderer12renderWindowEP7CWindowP8CMonitorP8timespecb15eRenderPassModebb+0x7df) [0x564f3861660f]
		??
		??:0
	#9 | Hyprland(_ZN13CHyprRenderer28renderAllClientsForWorkspaceEP8CMonitorP10CWorkspaceP8timespecRK8Vector2DRKf+0x2a0) [0x564f3861ca10]
		??
		??:0
	#10 | Hyprland(_ZN13CHyprRenderer15renderWorkspaceEP8CMonitorP10CWorkspaceP8timespecRK7wlr_box+0xde) [0x564f3861d3be]
		??
		??:0
	#11 | Hyprland(_ZN13CHyprRenderer13renderMonitorEP8CMonitor+0x564) [0x564f3861d954]
		??
		??:0
	#12 | Hyprland(_Z13handleWrappedP11wl_listenerPv+0x40) [0x564f385b3cb0]
		??
		??:0
	#13 | /usr/lib/libwayland-server.so.0(wl_signal_emit_mutable+0x7e) [0x7fdf22cd601e]
		??
		??:0
	#14 | /usr/lib/libwlroots.so.12032(+0x53f19) [0x7fdf22d72f19]
		??
		??:0
	#15 | /usr/lib/libdrm.so.2(drmHandleEvent+0xff) [0x7fdf228b79af]
		??
		??:0
	#16 | /usr/lib/libwlroots.so.12032(+0x4e8de) [0x7fdf22d6d8de]
		??
		??:0
	#17 | /usr/lib/libwayland-server.so.0(wl_event_loop_dispatch+0xa2) [0x7fdf22cd7ae2]
		??
		??:0
	#18 | /usr/lib/libwayland-server.so.0(wl_display_run+0x27) [0x7fdf22cd82d7]
		??
		??:0
	#19 | Hyprland(main+0x9b0) [0x564f38516f70]
		??
		??:0
	#20 | /usr/lib/libc.so.6(+0x23850) [0x7fdf2234c850]
		??
		??:0
	#21 | /usr/lib/libc.so.6(__libc_start_main+0x8a) [0x7fdf2234c90a]
		??
		??:0
	#22 | Hyprland(_start+0x25) [0x564f38525875]
		??
		??:0


Log tail:
[LOG] Disable TextInput
[WARN] Disabled TextInput commit?
[WARN] Disabled TextInput commit?
[LOG] Enable TextInput
[LOG] IME TextInput Keyboard Grab new
[LOG] Registered signal for owner 564f3d4eb730: 564f3c535010 -> 564f3d4eb740 (owner: IME Keyboard Grab)
[LOG] Set keyboard focus to surface 564f3d3cf5c0, with window name: ~
[LOG] Callback 564f3d4eb768 -> 564f3d4eb760, IME Keyboard Grab removed.
[LOG] IME TextInput Keyboard Grab destroy
[LOG] Disable TextInput
[WARN] Disabled TextInput commit?
[WARN] Disabled TextInput commit?
[LOG] Enable TextInput
[LOG] IME TextInput Keyboard Grab new
[LOG] Registered signal for owner 564f3d4eb730: 564f3c53fe20 -> 564f3d4eb740 (owner: IME Keyboard Grab)
[LOG] Set keyboard focus to surface 564f3bb96700, with window name: 未保存文檔 - Xournal++
[LOG] Callback 564f3d4eb768 -> 564f3d4eb760, IME Keyboard Grab removed.
[LOG] IME TextInput Keyboard Grab destroy
[LOG] Disable TextInput
[WARN] Disabled TextInput commit?
[WARN] Disabled TextInput commit?
[LOG] Set keyboard focus to surface 564f3bfe69a0, with window name: 高等代数（第四版） (北京大学数学系前代数小组；王萼芳；石生明；) (Z-Library).pdf
[LOG] Keybind triggered, calling dispatcher (64, , 50)
[LOG] Set keyboard focus to surface 564f3bd3b1b0, with window name: 腾讯会议
[LOG] Registered signal for owner 564f3bd39d50: 564f3dbc6370 -> 564f3bd39db8 (owner: XWayland Window)
[LOG] Registered signal for owner 564f3bd39d50: 564f3bca2470 -> 564f3bd3a368 (owner: Toplevel)
[LOG] Registered signal for owner 564f3bd39d50: 564f3bca2480 -> 564f3bd3a3d0 (owner: Toplevel)
[LOG] Registered signal for owner 564f3bd39d50: 564f3bca2490 -> 564f3bd3a300 (owner: Toplevel)
[LOG] Registered signal for owner 564f3bd3a570: 564f3dbc63a0 -> 564f3bd3a578 (owner: CWLSurface)
[LOG] CWLSurface 564f3bd3a570 called init()
[LOG] Registered signal for owner 564f3bd39d50: 564f3dbc6380 -> 564f3bd39e20 (owner: CWindow)
[LOG] Searching for matching rules for wemeetapp (title: EmojiFloatWnd)
[LOG] Window got assigned a surfaceTreeNode 0
[LOG] Registered signal for owner 564f3bd39d50: 564f3bd39c30 -> 564f3bd39fc0 (owner: XWayland Window Late)
[LOG] Registered signal for owner 564f3bd39d50: 564f3bd39c40 -> 564f3bd3a230 (owner: XWayland Window Late)
[LOG] Registered signal for owner 564f3bd39d50: 564f3bd39c70 -> 564f3bd39ef0 (owner: XWayland Window Late)
[LOG] Registered signal for owner 564f3bd39d50: 564f3bd39c10 -> 564f3bd3a0f8 (owner: Xwayland Window Late)
[LOG] Registered signal for owner 564f3bd39d50: 564f3bd39c20 -> 564f3bd3a160 (owner: Xwayland Window Late)
[LOG] Registered signal for owner 564f3e28dd90: 564f3dbc6390 -> 564f3e28de08 (owner: SurfaceTreeNode)
[LOG] Registered signal for owner 564f3e28dd90: 564f3dbc6360 -> 564f3e28de70 (owner: SurfaceTreeNode)
[LOG] Registered signal for owner 564f3e28dd90: 564f3dbc63a0 -> 564f3e28ded8 (owner: SurfaceTreeNode)
[LOG] Creating a surfaceTree Root! (pWindow: 564f3bd39d50)
[LOG] Map request dispatched, monitor eDP-1, xywh: 4.000000 1238.000000 150.000000 46.000000
[CRITICAL] 
==========================================================================================
ASSERTION FAILED! 

Attempted to draw NULL texture!

at: line 527 in OpenGL.cpp
```

**Comment by tytan652** [comment]
Did you check with Hyprland devs if it is really an issue from OBS Studio ?

**Comment by kkartaltepe** [comment]
This doesnt look like our bug, report crashes in your compositor with your compositor to the compositor instead.

**Comment by ashixu** [comment]
Thinks，But it's very strange that I only encounter this issue when using OBS, and other software is normal. Anyway, thank you for your reply.
