### ISSUE TITLE
Vulkan Validation Error caused by the OBS Hook when Using View With Narrowed Usage

### ISSUE THREAD

**Issue by cwfitzgerald** [obsproject/obs-studio#9353]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.3

### Related Issues

~~Introduced by: https://github.com/obsproject/obs-studio/pull/8504~~
Upstream: https://github.com/gfx-rs/wgpu/issues/3855

### Expected Behavior

No vulkan validation errors when using narrowed image usages.

### Steps to Reproduce

The flow is as follows.
- Swapchain is made with `VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT`
  - OBS inserts `VK_IMAGE_USAGE_TRANSFER_SRC_BIT`
- Image View is made using `VkImageViewUsageCreateInfo` in the pnext chain, with the usage set to `VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT`
  - OBS **does not** insert `VK_IMAGE_USAGE_TRANSFER_SRC_BIT`
- Framebuffer is made using usages `VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT`
  - OBS's internal framebuffer is made with `VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT|VK_IMAGE_USAGE_TRANSFER_SRC_BIT` despite the image view now having that usage.

Run the following on machine with OBS and Validation Layers:
```rust
git clone https://github.com/gfx-rs/wgpu/
cd wgpu
git checkout d11d2f96dc86657d11ae3549507df5fb0bd9fdb2

cargo run --bin cube
```

and you'll see a slew of validation errors coming from OBS's internal framebuffer.

```
VALIDATION [VUID-VkRenderPassBeginInfo-framebuffer-04627 (0x45125641)]
        Validation Error: [ VUID-VkRenderPassBeginInfo-framebuffer-04627 ] Object 0: handle = 0x59f7450000000038, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0x45125641 | vkCmdBeginRenderPass: Image view #0 created from an image with usage set as (VK_IMAGE_USAGE_TRANSFER_SRC_BIT|VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT) but using VkImageViewUsageCreateInfo the inherited usage is the subset (VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT) and the image info #0 used to create the framebuffer had usage set as (VK_IMAGE_USAGE_TRANSFER_SRC_BIT|VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT). The Vulkan spec states: If framebuffer was created with a VkFramebufferCreateInfo::flags value that included VK_FRAMEBUFFER_CREATE_IMAGELESS_BIT, each element of the pAttachments member of a VkRenderPassAttachmentBeginInfo structure included in the pNext chain must be a VkImageView with an inherited usage equal to the usage member of the corresponding element of VkFramebufferAttachmentsCreateInfo::pAttachmentImageInfos used to create framebuffer (https://vulkan.lunarg.com/doc/view/1.3.250.0/windows/1.3-extensions/vkspec.html#VUID-VkRenderPassBeginInfo-framebuffer-04627)
[2023-08-03T05:04:29Z ERROR wgpu_hal::vulkan::instance]         objects: (type: RENDER_PASS, hndl: 0x59f7450000000038, name: ?)
```

A three frame dump of vulkan commands. Note that we only ever make one Framebuffer: [dump.txt](https://github.com/obsproject/obs-studio/files/12247062/dump.txt)

**Comment by jpark37** [comment]
Seems unrelated to #8504. Regardless, I think this is something we can address.

**Comment by jpark37** [comment]
I dug into this some more, and it is only in concert with #8504 that this new validation error appears although I think you would just slam into the other validation error that the PR fixed without it.

I'm working on slapping TRANSFER_SRC usage onto all image view narrowing structs that we detect as building on top of swap chain images. Let me know if you think that's a bad idea.

Also, I get that as a Vulkan developer that you'd be annoyed to debug something that ultimately wasn't your fault, but can you cut us some slack? (I scrolled through the links.) I can assure you we give a good-faith effort to run clean, but it's very difficult from the layer side to anticipate all the ways an application can use the API.

**Comment by cwfitzgerald** [comment]
Yeah I think that should work fine.

Definitely didn't mean to offend or put pressure in any way, my apologies if it came off that way. Really appreciate the quick response to the issue.
