### ISSUE TITLE
Browser docks now works under wayland when I revert the disable

### ISSUE THREAD

**Issue by neolectron** [obsproject/obs-studio#9369]
### Operating System Info

Ubuntu 22.10

### OBS Studio Version

Git

### OBS Studio Log URL

https://obsproject.com/logs/4WXvjRYBshjkFrRA

### Expected Behavior

Expected behavior would be to NOT work without the temporary commit that disable custom browser docks on wayland.

### Current Behavior

It DOES work, therefore the disabling of custom browser docks is useless.

### Steps to Reproduce

1. clone OBS-studio
2. revert commit `7402271392a6a74fb49f16d84fb3c04c1b603d9a` in obs-browser
3. build from source
4. start OBS with qt (for X): `GDK_BACKEND=x11 QT_QPA_PLATFORM=xcb obs`
5. The stuff works

![image](https://github.com/obsproject/obs-studio/assets/5268400/ead7a3f9-c767-4c6c-915b-359037bc8098)

### Anything else we should know?

(I tested it on Arch and the last ubuntu, they both worked)

**Comment by tytan652** [comment]
```
GDK_BACKEND=x11 QT_QPA_PLATFORM=xcb obs
```

```
Session Type: wayland
Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.23.1
```

You are under XWayland so an X11 implementation, not Wayland.

**Comment by neolectron** [comment]
@tytan652 yes but that's still the only way to make the browser-docks appear when your host session is wayland.

It works with pipewire AND xwayland.

**Comment by tytan652** [comment]
This is not Wayland (Wayland backend no XWayland).

Also we do not support running under XWayland.

**Comment by neolectron** [comment]
Let's not focus on the semantics, but rather on the results.

Is there any other way to have both screen-capture AND browser-docks working on wayland at the current time, that I might not be aware of ?

If no, I don't really get why we would like to prevent users to run their OBS like so.
Thanks.

**Comment by tiberium-v** [comment]
Browser Docks are disable on wayland because of a CEF bug/limitation. That's why obs prevent the creation it on wayland.

**Comment by notAutomne** [comment]
Hello,

I fully agree with @neolectron. It's rather :
- Losing a feature
- Having a feature with a minor workaround 

Having to recompile OBS just to get a feature that can work only with an argument in startup seems a biggest issue for the user. 

The safest option is just to add a messagebox if the user tries to launch browser-docks without delegating to XWayland.

**Comment by tytan652** [comment]
> Let's not focus on the semantics, but rather on the results.

The result is: it works under X11 (XWayland is one of its implementation), not Wayland.

I repeat:
- We do not support running under XWayland.

**Comment by neolectron** [comment]
You do not support it, but it's only based on personnal belief, because it just works.

**Comment by notAutomne** [comment]
> 



> > Let's not focus on the semantics, but rather on the results.
> 
> The result is: it works under X11 (XWayland is one of its implementation), not Wayland.
> 
> I repeat:
> 
>     * We do not support running under XWayland.

Not supporting is a thing. Preventing to use OBS in a unsupported way with the user consent is another.

It should be denied but not at compile time but rather with a simple check at runtime.

**Comment by notAutomne** [comment]
Any statement on this conflict @jp9000 @jpark37 ?

**Comment by neolectron** [comment]
I was under the impression that the commit I reverted was initially temporary, as it was stated in the commit description made by jp in 2021.

Since this particular commit doesn't really fix or prevent any crash anymore, I don't see why you would like to keep it.

![image](https://github.com/obsproject/obs-studio/assets/5268400/f7df4166-34c0-4f44-afb4-86a8262bcdc0)

**Comment by BenStigsen** [comment]
Are there any updates on this?
I have been able to find several CEF Wayland specific issues on the Chromium tracker, but I'm not sure which one is relevant to this case.

**Comment by WizardCM** [comment]
> Are there any updates on this? I have been able to find several CEF Wayland specific issues on the Chromium tracker, but I'm not sure which one is relevant to this case.

You can track https://github.com/chromiumembedded/cef/issues/2804

**Comment by tiritto** [comment]
> > Are there any updates on this? I have been able to find several CEF Wayland specific issues on the Chromium tracker, but I'm not sure which one is relevant to this case.
> 
> You can track [chromiumembedded/cef#2804](https://github.com/chromiumembedded/cef/issues/2804)

Looking at this linked issue, it appears that the issue will soon be resolved.

**Comment by madmalkav** [comment]
https://chromium-review.googlesource.com/c/angle/angle/+/7844989

🎉🎉🎉

**Comment by UserwithAccount** [comment]
so can this issue be reopened? docks would be a great added feature

**Comment by tiberium-v** [comment]
@UserwithAccount There is still work to do for CEF. That reported merge is for chromium and will for CEF not be enough. It is a starting point for them and others. 

The next chromium release after that reported merge, will not give CEF or obs any fix about the situation.
