### ISSUE TITLE
Browser dockwidget whic is floating will be hided when click the third window on Mac platform.

### ISSUE THREAD

**Issue by 63663455** [obsproject/obs-studio#9381]
### Operating System Info

macOS 12

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/JQtOw3BqwlU2Rn6G

### Expected Behavior

1、create a browser dockwiget, and make it floating.
2、click the third window, make the window before the obs mainwindow.
3、 the dockwidget which is floating will not be hided.

### Current Behavior

1、create a browser dockwiget, and make it floating.
2、click the third window, make the window before the obs mainwindow.
3、 the dockwidget which is floating will be hide.
4、click the obs mainwindow, make it before all other window. The dockwidget which is floating will be show.

### Steps to Reproduce

1、create a browser dockwiget, and make it floating.
2、click the third window, make the window before the obs mainwindow.
3、 the dockwidget which is floating will be hide.
4、click the obs mainwindow, make it before all other window. The dockwidget which is floating will be show.

**Comment by gxalpha** [comment]
This unfortunately is how all Qt applications, including the standalone Qt Designer, work. I’m not sure whether the limitation is Qt or macOS, but I don’t think we can do a lot about this.

**Comment by gxalpha** [comment]
As mentioned above, this is how floating windows behave on macOS. We don't think there's anything we can do about that.
