### ISSUE TITLE
vlc rtsp stream no video

### ISSUE THREAD

**Issue by vital121** [obsproject/obs-studio#9385]
### Operating System Info

Windows 11

### Other OS

Windows 11

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/tAvd6oeXldg9ebJb

### Expected Behavior

play rtsp stream

### Current Behavior

blank picture

### Steps to Reproduce

1.add source
2.choose VLC VIDEO Source
3.check loop
4.add source  rtsp://admin:123@192.168.1.1:8554/stream1 to playlist
5.visibility behaviour always play even when not visible

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
