### ISSUE TITLE
SRT can only handle mpegts

### ISSUE THREAD

**Issue by Quackdoc** [obsproject/obs-studio#9388]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/mWRRIynk3pm88ZHN

### Expected Behavior

when adding an SRT:// stream via media source, you are forced to use mpegts for the input format

### Current Behavior

Allow selecting other formats. 

### Steps to Reproduce

1. add media source
2. add srt uri `srt://127.0.0.1:9990?mode=listener&transtype=live&latency=0&recv_buffer_size=0`
3. set input format to `matroska`
4. re-open media source settings and see its forced mpegts
...

### Anything else we should know?

SRT (and rist) are a container agnostic protocols, this means ogg/ogv and matroska should work with it. 

this can easily be verified by opening mpv using `mpv.com srt://127.0.0.1:9990?mode=listener&transtype=live&latency=0&recv_buffer_size=0 --no-cache --untimed --no-demuxer-thread --video-sync=audio --vd-lavc-threads=1` or using `ffplay srt://127.0.0.1:9990?mode=listener&transtype=live&latency=0&recv_buffer_size=0 ` and sending a compatible stream to it such as 

`ffmpeg -re -stream_loop -1 -i .\input.video -c copy -f matroska "srt://127.0.0.1:9990?mode=caller&transtype=live&latency=0&recv_buffer_size=0"`

**Comment by tt2468** [comment]
Valid bug, need to remove hardcoded mpegts override for SRT. Libavformat detects mpegts just fine in SRT sockets.

**Comment by pkviet** [comment]
Fair enough. Ok to remove the hardcoding to mpegts
