### ISSUE TITLE
Custom Dock Fails to load URLs - Unable to Identify Cause

### ISSUE THREAD

**Issue by propertunist** [obsproject/obs-studio#9393]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/EiU5jq1lAzmOE5o8

### Expected Behavior

The custom dock is intended to correctly render the dashboard pages, such as: https://splinterlands.tv/dashboard/apeofwallst

### Current Behavior

Sometimes, with some users' dashboards, the custom dock loads a 404 page from our server instead of the correct dashboard page.

### Steps to Reproduce

1. Create a custom dock in OBS and assign as a target URL: https://splinterlands.tv/dashboard/apeofwallst
2. load and reload the dock/OBS.
3. The page may or may not load as a 404 not found error page instead of the correct page.

### Anything else we should know?

We have created a dashboard page for streamers at SPLTV that displays some basic info for them about the schedule/show. After a recent upgrade to our system, some users are unable to load their dashboard URL in the OBS custom dock that they usually use. The page loads correctly in browsers 100% of the time, but fails to load in the dock sometimes.

We have explored the developer tools in the custom dock, disabled caching, reset the caches in the dock and checked a variety of things, but have not yet found the cause. Since this only occurs in OBS and I think that the version of Google Chrome being used in OBS is pretty old, I am enquiring here to see if there is anything you guys can do.

Points of note:

- It's not all of the streamer pages that have a problem. This one is known to: https://splinterlands.tv/dashboard/apeofwallst
- Some of the pages loaded when https:// was removed from their URL but not all of them!
- The problem doesn't occur on all computers.
- If the page fails to load, we see a 404 error. This suggests to me that there may be some kind of transport error or something may need to change in Nginx on our server, but I have no idea what.

**Comment by notr1ch** [comment]
If you see a 404 error on your server logs and you're sure the URL is correct, then your server is somehow responsible for the issue. I did a few tests on the URL you provided and noticed the etag changes every second. If the content is reading from a static file then you need to make sure it is updated atomically - if the old file is deleted / renamed and then a new file put in place, there is a window where a request could not find the file. Any new file must be moved on top of the old file, and you must not be using options like [open_file_cache](https://nginx.org/en/docs/http/ngx_http_core_module.html#open_file_cache).

In any case I doubt this is an issue on the OBS side, regardless of how old our CEF version is.

**Comment by gxalpha** [comment]
Closing per the comment above.
If you have more evidence to suggest that OBS is indeed at fault here, please follow up and we can reopen if needed.

**Comment by propertunist** [comment]
> If you see a 404 error on your server logs and you're sure the URL is correct, then your server is somehow responsible for the issue. I did a few tests on the URL you provided and noticed the etag changes every second. If the content is reading from a static file then you need to make sure it is updated atomically - if the old file is deleted / renamed and then a new file put in place, there is a window where a request could not find the file. Any new file must be moved on top of the old file, and you must not be using options like [open_file_cache](https://nginx.org/en/docs/http/ngx_http_core_module.html#open_file_cache).
> 
> In any case I doubt this is an issue on the OBS side, regardless of how old our CEF version is.

thanks for looking. the page is served dynamically via node express, so there's no file being overwritten and there is no period where data is not served. this is part of why the page never fails in a normal browser.

i'll dig around more and try to find the source of the problem at the network level.
