### ISSUE TITLE
performance impact of RGBA colour space for recording 

### ISSUE THREAD

**Issue by tari3x** [obsproject/obs-studio#9394]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/kaPFh32OBBeBtN1d

### Expected Behavior

When choosing RGBA vs I444 for recording I expect the performance to be roughly similar.

### Current Behavior

I444 recording works without a glitch, RGBA hits "Encoding overloaded" after a couple of seconds, and the resulting video is garbage (about one frame per several seconds). 

For comparison, dxtory is able to record RGB without problems.

Reading [I want to record actully lossless video (full range RGB, no subsampling)](https://obsproject.com/forum/threads/i-want-to-record-actully-lossless-video-full-range-rgb-no-subsampling-how-do-i-do-it.148637/#post-543855) it seams like RGB performance loss is a well-known issue but I don't think that thread explains where it comes from. 

Is this entirely due to the fact that RGBA is 4 bytes and I444 only 3? If so, would it be possible to add a pure RGB option? 

### Steps to Reproduce

Start recording with the settings as per log - I get "Encoding overloaded" after a couple of seconds.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by tari3x** [comment]
I weep. 

My issue report includes the link to the forum thread where I spent considerable time trying to get help. Sadly, OBS developers don't seem to go there, so it was fruitless.

Helpfully someone pointed out that when I choose RGBA, I see this in my log:
GPU conversion not available for format: 7

I will open a new issue with this new information, hope you forgive me.

**Comment by tari3x** [comment]
Apologies, the link to my thread is actually this one, and I didn't include it: [performance impact and precision of colour formats](https://obsproject.com/forum/threads/performance-impact-and-precision-of-colour-formats.168651/)

My new issue: https://github.com/obsproject/obs-studio/issues/9396

Sorry for the double attempt, I know it's a bit rude - but I've noticed that people generally don't read responses to closed issues, sadly.

**Comment by tari3x** [comment]
This looks like it may resolve the problem: 
https://github.com/obsproject/obs-studio/pull/5706

**Comment by tari3x** [comment]
I don't think https://github.com/obsproject/obs-studio/pull/5706 is relevant actually - it talks specifically about nvenc, but I see the difference when encoding to utvideo. 

Looking at the code, there is no handling of BGRA data on the GPU - we don't set it up in calc_gpu_conversion_sizes and we don't have a provision for it in format_conversion.effect. So then it goes via the "slow" path even though I still don't understand what's slow in it - we should just copy the frame and hand it to the encoder. 

I'll try to hack BGRA or BGR3  to follow the same path as I444 (which I know to be fast) and see what happens.

**Comment by tari3x** [comment]
Played around, no effect. 

In https://github.com/obsproject/obs-studio/issues/9395 it was suggested that the problem is "GPU conversion not available for format: 7". Having tinkered with the code I now don't think that's the case. This error message is misleading: 
```
	if (!video->conversion_needed) {
		blog(LOG_INFO, "GPU conversion not available for format: %u",
```
The message probably should say "GPU pixel format conversion is not necessary". 

So I'm back to the drawing board. With BGRA and utvideo I get 
Video stopped, number of skipped frames due to encoding lag: 448/468 (95.7%)

With I444 I only get 
Video stopped, number of skipped frames due to encoding lag: 11/425 (2.6%)

I don't see anything within obs itself that could cause such a huge difference, so maybe there's something about the ffmpeg encoder. However this happens both with utvideo and x264 which seem to be rather different paths. 

I'll see if I can force obs to never skip frames since I don't care how long it takes to encode.

**Comment by tari3x** [comment]
One possibility is that BGRA is 30% more bandwidth than I444 so maybe that's enough to push it over? Would be a lot of coincidence.
