### ISSUE TITLE
GPU conversion not available for RGBA

### ISSUE THREAD

**Issue by tari3x** [obsproject/obs-studio#9396]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/GqGn1j8orOzcboZM

### Expected Behavior

RGBA conversion should be as smooth as I444.

### Current Behavior

Please oh mighty, I beg you: do not send me back to the forums! I've been there: [performance impact and precision of colour formats](https://obsproject.com/forum/threads/performance-impact-and-precision-of-colour-formats.168651/). 

When I choose RGBA I see in the log:
GPU conversion not available for format: 7

Correspondingly the performance is very bad. Could something be improved in OBS to make it available? 

### Steps to Reproduce

Record in RGBA.

**Comment by Fenrirthviti** [comment]
Please stop opening new issues for support.

**Comment by tari3x** [comment]
1 star.
