### ISSUE TITLE
Error "failed to find locale/en-US.ini" and subsequent "Failed to load locale" error after task scheduler autostart

### ISSUE THREAD

**Issue by D4n2021** [obsproject/obs-studio#9413]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/Hw9OxKpmUYB72d2Y

### Expected Behavior

OBS to autostart in background, or at all

### Current Behavior

first error window "failed to find locale/en-US.ini" appears, then when clicking "OK", next error window "Failed to load locale" appears, then clicking "OK", OBS is entirely closed.

### Steps to Reproduce

1. create a task scheduler task with the settings compiled in the .xml file inside this .zip (or import that .xml file, it should work afaik? I exported it from task scheduler)
[OBS buffer.zip](https://github.com/obsproject/obs-studio/files/12322656/OBS.buffer.zip)
2. reboot PC
3. error should appear after Windows login

**Comment by notr1ch** [comment]
OBS expects to be started from its own working directory, this is not a bug.

**Comment by Arkenervs** [comment]
> @notr1ch thanks for the super quick reply! Fixed it with shell:startup, that _does_ work for some strange reason.

sorry to reopen this, but how did you fix it with shell:startup for the task scheduler?
