### ISSUE TITLE
active OBS replay buffer blocking PC from switching into standby-mode/energy-saving mode

### ISSUE THREAD

**Issue by D4n2021** [obsproject/obs-studio#9415]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/1rQmkAFgrJ5WfXJA

### Expected Behavior

PC should go into energy saving mode no problem (power-LED should be blinking)

### Current Behavior

monitors loose signal, but power-LED remains on, not reaching energy-saving mode

### Steps to Reproduce

1. start replay buffer (at 20 min, so 1200s)
2. minimize OBS to system tray
3. try to force PC into standby/power saving mode
...

**Comment by RytoEX** [comment]
This is by design. OBS intentionally inhibits sleep while outputs are active to prevent several bad scenarios from occurring.
