### ISSUE TITLE
Arch Linux: OBS crashing on record start. 

### ISSUE THREAD

**Issue by tetoNidan** [obsproject/obs-studio#9417]
### Operating System Info

Other

### Other OS

Arch

### OBS Studio Version

29.1.3

### OBS Studio Version (Other)

extra/obs-studio 29.1.3-1 [installed]

### OBS Studio Log URL

https://obsproject.com/logs/3SciaF379vWpI0bH

### OBS Studio Crash Log URL

https://obsproject.com/logs/3SciaF379vWpI0bH

### Expected Behavior

To not crash when pressing record

### Current Behavior

Crashing when starting screen capture.

### Steps to Reproduce

1.open OBS
2.press record with keyboard shortcut or through GUI buttons [streaming, recording]
3.crash
...

### Anything else we should know?

Under help I could not find a crash report option. Is there a way I can provide you with that? I went in to show logs and I'm not sure that there was a crash log generated. Or maybe any fog that is generated during a crashed OBS session is a crash log and I'm just confused?

Any way if there is anything I can do to give you more information or something you want me to try that would give you more information let me know.

Thanks OBS.

**Comment by kkartaltepe** [comment]
Please provide a stacktrace from gdb.

**Comment by sikhadev** [comment]
On Arch, you should already have coredumps automatically saved, so I assume you should be able to find dumps from OBS crashes via `coredumpctl list`, drop into gdb with `coredumpctl debug $PID` (where $PID is the process ID of the OBS instance that crashed), and run `backtrace`.

**Comment by tetoNidan** [comment]
So to get this right, I should run OBS, get the pid of the OBS process `ps aux | grep obs`,  then initiate the crash, run the `coredumpctl debug $PID`, then run `backtrace`? Is that how to do it? Sory I havent done this before.

**Comment by tetoNidan** [comment]
Here is the coredump https://pastebin.com/ytPwP9jN

backtrace is not installed, would that be `libbacktrace-git`?

**Comment by kkartaltepe** [comment]
You have broken your system by not updating properly.

**Comment by tetoNidan** [comment]
Thanks, Sorry for the waste of time!

**Comment by sikha-root** [comment]
> backtrace is not installed, would that be `libbacktrace-git`?

for future reference, backtrace is a command in `gdb` to print out the stack trace.
