### ISSUE TITLE
Display capture causes 3D core overload on Intel GPU

### ISSUE THREAD

**Issue by ma3uk** [obsproject/obs-studio#9423]
### Operating System Info

Windows 11

### OBS Studio Version

Git

### OBS Studio Log URL

https://obsproject.com/logs/0nkgU4OhQ3aai3PT

### Expected Behavior

Processing on specialized video decoding units

### Current Behavior

Processing on a 3D core, which leads to an overload of the graphics card.
When recording or broadcasting using the same video card on which OBS is running, it can cause frame drops

### Steps to Reproduce

1. Install the intel video card as the main device/select the intel video card to run OBS-studio.
2. Add a "Display capture" source with the Windows 10 capture method (1903 and up)
3. Launch any game or video with active movement on the captured display

### Anything else we should know?

The problem with 3D core overload is more clearly visible on discrete Intel Arc graphics cards, I took screenshots of the load level when running OBS-Studio on different video cards with screen capture - Nvidia 3080 uses specialized blocks for video decoding, the load on which is about 12-13%; Intel UHD 770 integrated graphics uses 3D cores and the load is about 26-30%; Intel Arc A380 discrete graphics uses 3D cores and the load is 65-75%.
![GPU 3D core overload](https://github.com/obsproject/obs-studio/assets/2519070/2b6c3a65-d2e1-4a7d-8a91-591880721e40)

All measurements were performed without recording or broadcasting, i.e. the presented load was only from screen capture, the "Display capture" source was used on all video cards with the following settings
![Display capture settings](https://github.com/obsproject/obs-studio/assets/2519070/e68d86d7-59c9-4fda-8c81-47f0d5b5aaea)

**Comment by derrod** [comment]
None of your media sources have hardware decoding enabled. Also you're running some messed up build with outdated plugins. This is more of a support issue which GitHub issues aren't meant for.

**Comment by ma3uk** [comment]
> 
This is the latest OBS-Studio build from the master branch
I repeated the process with a clean install, the result is similar

**Comment by ma3uk** [comment]
@derrod This is the latest OBS-Studio build from the master branch
I repeated the process with a clean install, the result is similar
And what does this have to do with media files added to other scenes that are not displayed?
In addition, at the moment OBS-Studio does not support hardware decode for media files on Intel video cards

**Comment by derrod** [comment]
If hardware decoding isn't enabled it won't be used. We use FFmpeg an dgeneric vendor agnostic APIs like DXVA, if those don't work on Intel that's not our problem.

This build clearly isn't just from master as it contains massively outdated plugins (we.g. RTMP services).

**Comment by ma3uk** [comment]
> If hardware decoding isn't enabled it won't be used. We use FFmpeg and generic vendor agnostic APIs like DXVA, if those don't work on Intel that's not our problem.
> 
> This build clearly isn't just from master as it contains massively outdated plugins (we.g. RTMP services).

https://obsproject.com/logs/Qn2m2jE7aaKzlAJY 
I performed a clean install so as not to pull outdated plugins. You can familiarize yourself with the log file.
I opened this Issue not because of the lack of hardware decode support. and because the screen capture loads the 3D core of the video card heavily. The load on the core of the discrete video adapter is similar to abnormal compared to the load on the integrated

**Comment by derrod** [comment]
Your issue conplains that the video decode cores aren't used, those aren't used because you're not hardware decoding any video. The high load is both because they're low end GPUs, the 3080 is several times more powerful so of course it's fairly low. If you want more efficient capture use game capture or old display/window capture methods.

**Comment by ma3uk** [comment]
> Your issue conplains that the video decode cores aren't used, those aren't used because you're not hardware decoding any video. The high load is both because they're low end GPUs, the 3080 is several times more powerful so of course it's fairly low. If you want more efficient capture use game capture or old display/window capture methods.

But there is no setting in the screen capture settings for using hardware decode, how do I enable it for this source?

I will clarify once again that the source of the screen capture is on a separate scene from the media files. Media files are not played at the time of screen capture

**Comment by derrod** [comment]
Window/display capture aren't encoded so hardware decode isn't used. So the complaint that they aren't in the issue is invalid.
