### ISSUE TITLE
OBS virtual camera and macos 14

### ISSUE THREAD

**Issue by clementHA1** [obsproject/obs-studio#9424]
### Operating System Info

Other

### Other OS

macOS 14

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://no_log.com

### Expected Behavior

When the virtual camera is enable and Zoom open, the virtual camera work as expected. 

### Current Behavior

 When I activate this feature, Zoom closes abruptly and I can no longer participate in meetings. By visiting your Discord, I learned that the OBS virtual camera uses a DAL plugin that is no longer compatible with macOS 14, according to an announcement made at the WWDC. I also saw that an update for the virtual camera was under development by your teams. I would like to thank you for your work and your responsiveness.

### Steps to Reproduce

1.Use macOS 14
2.enable the virtual camera
3.open Zoom and choose "OBS virtual camera" as camera

**Comment by tytan652** [comment]
A CMIO based implementation to replace the DAL is already merged for the next release (#7777).
