### ISSUE TITLE
Screenrecording freezes after a few minutes

### ISSUE THREAD

**Issue by binnichtaktiv** [obsproject/obs-studio#9433]
### Operating System Info

macOS 13

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/gqtbNIfq2jBTrodN

### Expected Behavior

OBS just records everything until I stop the recording...

### Current Behavior

After a random? time the recording freezes. When I record everything looks good, no problems obs is reacting etc but when I stop recording and then when I watch the video it freezes after a time. I just see a freeze frame then. And even if i start a new recording the same image is still there. I did it the first time the error occurred and at the end I had a video with just a still image that had started in the recording before.... The funny thing is that I didn't do anything, no update, no settings changed. There is enough storage space

### Steps to Reproduce

Uhh I dont know record a game with macOS 13 and a M1 mac?

**Comment by binnichtaktiv** [comment]
> This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.
> 
> Thank you!

No I saw other people that had this problem on macs too. Its not just my problem

**Comment by Fenrirthviti** [comment]
Duplicate of https://github.com/obsproject/obs-studio/issues/9056
