### ISSUE TITLE
[CRITICAL] Reload frozen webcams

### ISSUE THREAD

**Issue by es20490446e** [obsproject/obs-studio#9434]
### Operating System Info

Other

### OBS Studio Version

Git

### OBS Studio Log URL

https://pastebin.com/raw/fPWv7yzd

### Expected Behavior

Any webcam that freezes shall reconnect.

### Current Behavior

Many people in the last years are reporting that their cams freeze with OBS, and they don't know what to do about it. No matter the operating system or the webcam model.

Sometimes you are in the middle of a live stream, and the cam freezes without you noticing. Other times people are forced to move to a distant place to reload OBS.

https://www.google.com/search?q=obs+cam+freeze

It doesn't matter how good the software is if it can't do its basic function. This shall be priority number one.

### Steps to Reproduce

Own a cam.

### Anything else we should know?

- It doesn't happen with any other webcam or streaming software, hence the problem lies in OBS.
- Changing ports, updating firmware, drivers, UEFI, or tweaking config doesn't work.
- Potential root cause: USB 3.0 transfer mode wrongly selected: https://help.elgato.com/hc/en-us/articles/4681224843917-Elgato-Facecam-How-To-Change-USB-Transfer-Mode

**Comment by notr1ch** [comment]
OBS already provides a way to deactivate and reactivate a capture device, though if the driver itself has frozen there isn't much it can do. Often this issue is triggered by [USB bandwidth overload](https://r1ch.net/blog/managing-usb-bandwidth-with-usbview) in combination with other systems being stressed, and lowering the input resolution or FPS is the best solution.

**Comment by es20490446e** [comment]
@notr1ch Sorry, but I have already tested that's not the issue.

I have tested setting the cam with minimum resolution, framerate and format. And it still freezes. Same with changing USB port.

But even if that's the cause, it shall be dealt with. Because all kinds of people are experiencing it, and they don't really know what to do it.

A solution shall be put in place, or this software is effectively useless.

**Comment by NikolaiSchreier** [comment]
After thinking about this for a day, this might be a specific deficiency of v4l2-input. 
1. The "Deactivate/Reactivate" functionality @notr1ch mentioned does not exist for those sources.
2. Camera freezes might well occur on other platforms, but might have completely different symptoms that are not detectable by OBS. The issue we are having is clearly recognized by the v4l2-input code.
3. As far as I know, on other platforms resetting/reconnecting the camera results in the video stream resuming. For v4l2-input, as soon as the stream is broken, the source is dead and I have to recreate it. I made a script that automates this, but that only works if the source is in one scene and is a top level source. So it is only a very terrible crutch.
4. Other software that uses v4l2 devices is generally more robust in this regard. Even browser-based programs like Discord are handling disconnects/reconnects more gracefully.

**Comment by NikolaiSchreier** [comment]
Just as an example, I ran OBS with the camera source working fine and unplugged the camera. OBS logged this:
```
11:59:43.000: v4l2-input: decoder: failed to send frame to codec
11:59:43.000: v4l2-input: failed to unpack jpeg or h264
11:59:43.000: v4l2-input: /dev/video0: Stopped capture after 3019 frames
11:59:43.216: v4l2-input: Device /dev/video0 disconnected
```
Then I reconnected the camera:
```
11:59:48.645: v4l2-input: Device /dev/video0 reconnected
11:59:48.645: v4l2-input: Start capture from /dev/video0
11:59:48.646: v4l2-input: Input: 0
11:59:48.651: v4l2-input: Resolution: 1920x1080
11:59:48.651: v4l2-input: Pixelformat: MJPG
11:59:48.651: v4l2-input: Linesize: 0 Bytes
11:59:48.654: v4l2-input: Framerate: 30.00 fps
11:59:48.655: v4l2-input: /dev/video0: select timeout set to 166666 (5x frame periods)
11:59:48.806: v4l2-input: /dev/video0: failed to enqueue buffer
11:59:48.806: v4l2-input: /dev/video0: Stopped capture after 1 frames
```

At this point the _only_ things that can recover this are an OBS restart or a "remove source", "unplug camera", "reconnect camera", "recreate source" procedure.
