### ISSUE TITLE
Cant't stream with output mode "advanced"  selected

### ISSUE THREAD

**Issue by PANyZHAL** [obsproject/obs-studio#9444]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.3

### OBS Studio Version (Other)

29.1.1

### OBS Studio Log URL

https://obsproject.com/logs/leeMisg5e7SNIjpO

### Expected Behavior

change my VOD track, and tweak encoder settings for stream

### Current Behavior

When I choose the advanced option, no matter what configuration I use, it doesn't work. Usually, I can record, but if I change the advanced mode/recording tab/audio to "stream encoder," I also can't record.
it says
"Starting the output failed.Please check the log for details.
Note: if you are using the NVENC or AMD encoder, make sure your video drivers are up to date."

### Steps to Reproduce

1.settings
2.Output
3.Output mode from simple to advanced
4.Select x264 or NVENC
5,Start streaming

### Anything else we should know?

I have my NVIDIA (rtx 3060) drivers up to date.

**Comment by WizardCM** [comment]
The relevant snippet causing your issues:
```
23:28:52.196: [FFmpeg NVENC encoder: 'vertical_canvas_record_video_encoder'] settings:

23:28:52.196: 	width:        8
23:28:52.196: 	height:       -1225800656

23:28:52.196: error:   Picture size 8x3069166640 is invalid
23:28:52.196: [NVENC encoder] nvenc_create_internal failed
```

The vertical canvas is created by a third party plugin. Please reach out to them for support.

**Comment by WizardCM** [comment]
Secondarily, it's also failing to start the main stream output as it's attempting to CoreAudio AAC after you (recently?) uninstalled iTunes.

**Comment by PANyZHAL** [comment]
> Secondarily, it's also failing to start the main stream output as it's attempting to CoreAudio AAC after you (recently?) uninstalled iTunes.

i uninstall vertical canvas and there still the issue, and yes i uninstall itunes recently but i already reinstalled it and persists :C
