### ISSUE TITLE
The window of vst do not reopen when close itself

### ISSUE THREAD

**Issue by iesv** [obsproject/obs-studio#9455]
### Operating System Info

Windows 10

### OBS Studio Version

30.0.0-beta1

### OBS Studio Log URL

NONE

### Expected Behavior

Fix

### Current Behavior

The window of vst do not reopen when close itself.

### Steps to Reproduce

1. open vst plug
2. close window by itself
3. can not reopen
...

**Comment by RytoEX** [comment]
Please provide an OBS log for the session where this occurred and please provide the name of the VST that has this issue.

**Comment by gxalpha** [comment]
No log has been provided.
