### ISSUE TITLE
[obs-webrtc] [whip_output: 'adv_stream'] WHIP server did not provide a resource URL via the Location header

### ISSUE THREAD

**Issue by moo-the-cow** [obsproject/obs-studio#9459]
### Operating System Info

Windows 11

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.0.0-beta1

### OBS Studio Log URL

https://obsproject.com/logs/4dRtsoRCRDnCb6s1

### Expected Behavior

expecting to connect to the twitch endpoint 
https://g.webrtc.live-video.net:4443/v2/offer

### Current Behavior

Returing "Failed to connect to Server" when trying to start the stream

13:25:30.255: [obs-webrtc] [whip_output: 'adv_stream'] PeerConnection state is now: Connecting
13:25:30.922: [obs-webrtc] [whip_output: 'adv_stream'] WHIP server did not provide a resource URL via the Location header
13:25:30.923: [obs-webrtc] [whip_output: 'adv_stream'] PeerConnection state is now: Closed

### Steps to Reproduce

1. select WHIP in menu -> stream
2. enter credentials (streamkey)
3. switch to OPUS audio
4. adding Media Source (4k test video)
5. starting stream

**Comment by moo-the-cow** [comment]
I suspect it might be something related to this? it's just speculation though, because it's the last commit for WHIP on this tag
https://github.com/obsproject/obs-studio/commit/c81f531edbc2cdf45487bae5fc209e468db2301a

**Comment by RytoEX** [comment]
I can confirm this in OBS Studio 30.0.0-beta2. I had previously tested WHIP with Twitch on July 20, and it worked fine in OBS then, so the linked commit and its pair https://github.com/obsproject/obs-studio/commit/34e57a04968e969fd0a871acfc7665ff597ed1ff are under suspicion. @Sean-Der ?

**Comment by StrikerMan780** [comment]
Getting the same issue.

**Comment by Sean-Der** [comment]
A fix has been deployed. OBS WHIP output now works against Twitch. Sorry for the delay!

Would you mind testing again @StrikerMan780 and @moo-the-cow ?

**Comment by moo-the-cow** [comment]
sure! I know how it is, I was lurking 👍 thank you so much for the hard work

**Comment by moo-the-cow** [comment]
![image](https://github.com/obsproject/obs-studio/assets/34907770/d6f2d2d4-1ce0-429a-a34b-67e7cb40e953)
worked fine. I used the windows build release

**Comment by StrikerMan780** [comment]
> A fix has been deployed. OBS WHIP output now works against Twitch. Sorry for the delay!
> 
> Would you mind testing again @StrikerMan780 and @moo-the-cow ?

Worked the first time, but now it says I'm connected, but there's no output on Twitch, and Twitch says I'm "offline".

**Comment by moo-the-cow** [comment]
@StrikerMan780 per default it is using a very high bitrate. twitch still allows only 7500k (at best). set it to 7000 to be sure. any success?

**Comment by StrikerMan780** [comment]
I was set to much less than that. 6000k.

**Comment by moo-the-cow** [comment]
ok maybe unlucky twitch glitch, I mean. it is also a new thing on twitch, so.

**Comment by sandr1x** [comment]
Does not work. Tested on OBS 30.0 Beta 2 and 3
![image](https://github.com/obsproject/obs-studio/assets/113405680/2c62a14c-5da8-4931-88ed-4a31dc334b13)

https://obsproject.com/logs/wvlknmERKTqJsRqi

23:35:38.241: ==== Streaming Start ===============================================
23:36:10.282: [obs-webrtc] [whip_output: 'adv_stream'] PeerConnection state is now: Failed
23:36:10.282: [obs-webrtc] [whip_output: 'adv_stream'] PeerConnection state is now: Closed
23:36:10.285: ==== Streaming Stop ================================================
23:36:10.410: [obs-webrtc] [whip_output: 'adv_stream'] DELETE request for resource URL failed. HTTP Code: 405

**Comment by RytoEX** [comment]
> Does not work. Tested on OBS 30.0 Beta 2 and 3

Works fine here on Beta 3.

**Comment by sandr1x** [comment]
> > Does not work. Tested on OBS 30.0 Beta 2 and 3
> 
> Works fine here on Beta 3.

Yes you are right. Works great, but for me, only via VPN. Hmm, that's weird
