### ISSUE TITLE
QSV CBR AVC Bug unusable for streaming

### ISSUE THREAD

**Issue by maginhart** [obsproject/obs-studio#9460]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.0-beta1

### OBS Studio Version (Other)

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/0gd5UhqSh9CyR6J3

### Expected Behavior

CBR Spikes should still respect the set keyframe interval and should fall back to CBR target bitrate (in this example 6000+audio bitrate) over the course of 2 seconds.

### Current Behavior

With CBR set to 6000 Kbps bitrate spikes up pretty high on complex scenes 10500 kbps and **stays in the range of 8700-8900 kbps far longer than the set keyframe interval**. Also during those moments you can clearly see that the whole picture starts pulsating and creates additional picture blockiness.
If a person will try to stream to twitch the result of this kind of behaviour will lead to disabled video player on twitch if no transcodes were available. If transcodes were available people will only see those.

### Steps to Reproduce

1. Start recording
2. Switch to a scene with visually complex gameplay
3.
...

### Anything else we should know?

Video example of the issue with stats window
https://drive.google.com/file/d/19OqxZ5X6V3JruBDPVdJEUC_6uBybr7Go/view?usp=sharing

Settings used 
![image](https://github.com/obsproject/obs-studio/assets/60628882/ec97edf8-2456-4fb7-93e7-d184d2df3c66)

This issue was already reported in #9258 and RytoEX sent the reported issue to Intel.

**Comment by RytoEX** [comment]
Just to clarify, QSV having CBR variance or exhibiting this problem is not new to OBS Studio 30.0.0-beta1. It can occur in OBS Studio 29.1.3, as noted in my comments on the PR.

https://github.com/obsproject/obs-studio/pull/9258#issuecomment-1670097677:
> For what it's worth, I just spent the past hour testing this with OBS Studio 29.1.3 with your settings, and I managed to lose Source quality with QSV H.264 with OBS Studio 29.1.3, so I do not think this PR is to blame. QSV CBR has high variance before and after this PR. Additionally, Source quality eventually returned after the bitrate stabilized enough, both with and without this PR.

https://github.com/obsproject/obs-studio/pull/9258#issuecomment-1670366573:
> In any case, in my test streams, I did not notice that the CBR variance was notably worse after this PR. In fact, with this PR, the average bitrate for the session was closer to the target bitrate. I did notice one higher peak than without this PR, but one observance is hardly sufficient testing to draw a solid conclusion. As mentioned, I've escalated the issue of CBR variance in general to Intel.

As such, I'm going to adjust the Issue report accordingly.

**Comment by maginhart** [comment]
Possible fix for the issue was commited to VPL on august 18th
https://github.com/oneapi-src/oneVPL-intel-gpu/commit/249c854056273b88dd0417f97fff12a548c59c63

**Comment by maginhart** [comment]
https://drive.google.com/file/d/1zL7RJzmo9DwbhKN3Ftz8MJozZxGxyz8_/view?usp=sharing
Another example.
Bitrate was set to 6000
Different game (WoW) starting recording on empty scene switch to gameplay and the bitrate doesn't drop back to target not even once during those 54 seconds.

This was tested with OBS 30.0.0-beta2-15-gb78c03985 which contains pull request 9503 (obs-qsv11: Improve QSV CBR variance)
