### ISSUE TITLE
Unable to use the .deb on Ubuntu for 30.0 Beta

### ISSUE THREAD

**Issue by LiamDawe** [obsproject/obs-studio#9465]
### Operating System Info

Other

### Other OS

Ubuntu 23.04

### OBS Studio Version

30.0.0-beta1

### OBS Studio Log URL

can't provide one

### Expected Behavior

Trying the .deb for Ubuntu 23.04 from the 30.0 Beta 1 release and it can't find dependencies. I assume your build system needs adjusting for Ubuntu 23.04?

> liam@liam-kub:~$ sudo dpkg -i /home/liam/Downloads/OBS-Studio-30.0.0-beta1-Ubuntu-x86_64.deb 
> [sudo] password for liam: 
> Selecting previously unselected package obs-studio.
> (Reading database ... 227729 files and directories currently installed.)
> Preparing to unpack .../OBS-Studio-30.0.0-beta1-Ubuntu-x86_64.deb ...
> Unpacking obs-studio (30.0.0-1) ...
> dpkg: dependency problems prevent configuration of obs-studio:
>  obs-studio depends on libavcodec58 (>= 7:4.4); however:
>   Package libavcodec58 is not installed.
>  obs-studio depends on libavdevice58 (>= 7:4.4); however:
>   Package libavdevice58 is not installed.
>  obs-studio depends on libavformat58 (>= 7:4.4); however:
>   Package libavformat58 is not installed.
>  obs-studio depends on libavutil56 (>= 7:4.4); however:
>   Package libavutil56 is not installed.
>  obs-studio depends on libluajit-5.1-2 (>= 2.0.4+dfsg); however:
>   Package libluajit-5.1-2 is not installed.
>  obs-studio depends on libmbedtls14 (>= 2.28.0); however:
>   Package libmbedtls14 is not installed.
>  obs-studio depends on libmbedx509-1 (>= 2.28.0); however:
>   Package libmbedx509-1 is not installed.
>  obs-studio depends on libpython3.10 (>= 3.10.0); however:
>   Package libpython3.10 is not installed.
>  obs-studio depends on libqt6core6 (>= 6.2.0); however:
>   Package libqt6core6 is not installed.
>  obs-studio depends on libqt6gui6 (>= 6.1.2); however:
>   Package libqt6gui6 is not installed.
>  obs-studio depends on libqt6network6 (>= 6.1.2); however:
>   Package libqt6network6 is not installed.
>  obs-studio depends on libqt6svg6 (>= 6.2.0); however:
>   Package libqt6svg6 is not installed.
>  obs-studio depends on libqt6widgets6 (>= 6.1.2); however:
>   Package libqt6widgets6 is not installed.
>  obs-studio depends on libqt6xml6 (>= 6.1.2); however:
>   Package libqt6xml6 is not installed.
>  obs-studio depends on libswresample3 (>= 7:4.4); however:
>   Package libswresample3 is not installed.
>  obs-studio depends on libswscale5 (>= 7:4.4); however:
>   Package libswscale5 is not installed.
>  obs-studio depends on libx264-163 (>= 2:0.163.3060+git5db6aa6); however:
>   Package libx264-163 is not installed.
> 
> dpkg: error processing package obs-studio (--install):
>  dependency problems - leaving unconfigured
> Errors were encountered while processing:
>  obs-studio

### Current Behavior

It won't install

### Steps to Reproduce

1. Try to run the deb on ubuntu 23.04
2.
3.
...

**Comment by tytan652** [comment]
This package is meant for Ubuntu 22.04.

**Comment by Gol-D-Ace** [comment]
PPA will likely follow with Beta2 which includes a deb for 23.04
