### ISSUE TITLE
OBS 30 Beta 1 affecting Stable Build

### ISSUE THREAD

**Issue by KensonPlayz** [obsproject/obs-studio#9469]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.0-beta1

### OBS Studio Log URL

https://obsproject.com/logs/0UPElOU3ecSSfObB

### Expected Behavior

When going from Beta (beta installed via Steam) to Stable (29.1.3) installed on its own separately, I expect the docks to revert to bottom bar going all the way across the screen.

When I ran OBS 30 Beta 1, then closed and opened 29.1.3, the full-height docks were like copied to 29.1.3. I'm not sure if that will affect my 29.1.3's performance (I'm leaving to visit someone in the hospital for a few hours), but I expect it to go back to the normal stable build with the scenes/mixer/etc expanding all the way across, which it is not doing.

### Current Behavior

1) Open 30 Beta, love the full-height chat dock.
2) Close 30 Beta  (via Steam). Open 29.1.3 via a regular install (not Steam, not MS Store, manual install)
3) 29.1.3 has full-height docks. Doesn't seem to be buggy otherwise.

### Steps to Reproduce

1) Open 30 Beta, love the full-height chat dock.
2) Close 30 Beta  (via Steam). Open 29.1.3 via a regular install (not Steam, not MS Store, manual install)
3) 29.1.3 has full-height docks. Doesn't seem to be buggy otherwise.

**Comment by prgmitchell** [comment]
If you would like to run multiple versions of OBS, you would normally want to run one in portable mode otherwise the scenes/settings are shared.

```
Portable Mode allows the program to save and access configuration data from the program's base folder. To enable portable mode:

1.) Install/unzip to a custom directory outside of "C:\Program Files (x86)" or "C:\Program Files"
2.) Then either modify its shortcut with the --portable or -p command line parameter, or create a blank text file named "portable_mode.txt" in the base installation/unzip folder.
```

**Comment by KensonPlayz** [comment]
I do like having scenes shared, just in case I do want to test things a bit more than just exploring the settings. Its rare, but on occasion I do like doing a short test stream with my bot account with betas.

**Comment by derrod** [comment]
Configuration data will be shared between any OBS installs unless you run them in portable mode. You can export/import your scene collections if you want to have them in both, though that won't be synced of course.
