### ISSUE TITLE
USB Cameras not working with OBS

### ISSUE THREAD

**Issue by javmast3r** [obsproject/obs-studio#9472]
### Operating System Info

macOS 13

### OBS Studio Version

30.0.0-beta1

### OBS Studio Version (Other)

Have tried 28 & 29 

### OBS Studio Log URL

https://obsproject.com/logs/0EPkal2gGV6CISYg

### Expected Behavior

all USB video input devices should display a preview and image when selected.

### Current Behavior

Have installed latest OBS with latest OSX on a M2 Mini. Connected two USB Webcams and a composite to USB converter as video input through an external powered USB Hub.
Other video apps recognize all USB devices and show video, like photo booth.
When launching OBS only one USB camera is displayed, the others are shown on the device list are always black. Already checked for permissions on the app and system. 
Changed USB Hub, same problem. Connected two cameras directly to Mac Mini USB port, same issue. 
It used to work on previous versions, reinstalled and deleted the obs-studio folder under /Application Support, still have the same problem. 
As mentioned, other applications (Photo Booth, Streamyard) can display the cameras with no problem, just OBS fails. 

### Steps to Reproduce

1. Start OBS
2. Select Video Capture device 
3. From the list, select the USB Camera
4. only the first selected displays, the others are listed, but when selected the preview is black
...

### Anything else we should know?

Mac Mini just running a browser (Brave), The Mac Mini M2 was purchased specifically for OBS. No other software or hardware installed, using bluetooth wireless keyboard and mouse.

**Comment by javmast3r** [comment]
Hello, any updates? Here is the lates log, note that the "Nisheng M3" is the camera that doesn't display.


21:44:29.711: [macOS] Permission for audio device access granted.
21:44:29.714: [macOS] Permission for video device access granted.
21:44:29.716: [macOS] Permission for accessibility granted.
21:44:29.720: [macOS] Permission for screen capture granted.
21:44:29.720: CPU Name: Apple M2
21:44:29.720: Physical Cores: 8, Logical Cores: 8
21:44:29.720: Physical Memory: 8192MB Total
21:44:29.720: OS Name: macOS
21:44:29.721: OS Version: Version 13.5 (Build 22G74)
21:44:29.721: Rosetta translation used: false
21:44:29.721: Kernel Version: 22.6.0
21:44:29.721: hotkeys-cocoa: Using layout 'com.apple.keylayout.US'
21:44:29.721: Current Date/Time: 2023-08-22, 21:44:29
21:44:29.721: Browser Hardware Acceleration: true
21:44:29.721: Qt Version: 6.5.2 (runtime), 6.5.2 (compiled)
21:44:29.721: Portable mode: false
21:44:29.795: OBS 30.0.0-beta1 (mac)
21:44:29.795: ---------------------------------
21:44:29.796: ---------------------------------
21:44:29.796: audio settings reset:
21:44:29.796: 	samples per sec: 48000
21:44:29.796: 	speakers:        2
21:44:29.796: 	max buffering:   960 milliseconds
21:44:29.796: 	buffering type:  dynamically increasing
21:44:29.796: ---------------------------------
21:44:29.796: Initializing OpenGL...
21:44:29.827: Loading up OpenGL on adapter Apple Apple M2
21:44:29.827: OpenGL loaded successfully, version 4.1 Metal - 83.1, shading language 4.10
21:44:29.990: ---------------------------------
21:44:29.990: video settings reset:
21:44:29.990: 	base resolution:   1920x1080
21:44:29.990: 	output resolution: 1920x1080
21:44:29.990: 	downscale filter:  Bicubic
21:44:29.990: 	fps:               60/1
21:44:29.990: 	format:            NV12
21:44:29.990: 	YUV mode:          Rec. 709/Partial
21:44:29.990: NV12 texture support not available
21:44:29.990: P010 texture support not available
21:44:29.990: Audio monitoring device:
21:44:29.990: 	name: Default
21:44:29.990: 	id: default
21:44:29.990: ---------------------------------
21:44:29.993: No AJA devices found, skipping loading AJA UI plugin
21:44:29.993: Failed to initialize module 'aja-output-ui'
21:44:29.995: No AJA devices found, skipping loading AJA plugin
21:44:29.995: Failed to initialize module 'aja'
21:44:29.995: Failed to load 'en-US' text for module: 'decklink-captions'
21:44:29.996: Failed to load 'en-US' text for module: 'decklink-output-ui'
21:44:29.997: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
21:44:29.997: Failed to initialize module 'decklink'
21:44:30.090: [obs-browser]: Version 2.22.0
21:44:30.090: [obs-browser]: CEF Version 103.0.5060.134 (runtime), 103.61.23+g2fe5a76+chromium-103.0.5060.134 (compiled)
21:44:30.099: [obs-websocket] [obs_module_load] you can haz websockets (Version: 5.2.3 | RPC Version: 1)
21:44:30.099: [obs-websocket] [obs_module_load] Qt version (compile-time): 6.5.2 | Qt version (run-time): 6.5.2
21:44:30.099: [obs-websocket] [obs_module_load] Linked ASIO Version: 102800
21:44:30.101: [obs-websocket] [obs_module_load] Module loaded.
21:44:30.105: [vlc-video]: VLC 3.0.18 Vetinari found, VLC video source enabled
21:44:30.105: ---------------------------------
21:44:30.105:   Loaded Modules:
21:44:30.105:     vlc-video
21:44:30.105:     text-freetype2
21:44:30.105:     rtmp-services
21:44:30.105:     obs-x264
21:44:30.105:     obs-websocket
21:44:30.105:     obs-webrtc
21:44:30.105:     obs-vst
21:44:30.105:     obs-transitions
21:44:30.105:     obs-outputs
21:44:30.105:     obs-filters
21:44:30.105:     obs-ffmpeg
21:44:30.105:     obs-browser
21:44:30.105:     mac-virtualcam
21:44:30.105:     mac-videotoolbox
21:44:30.105:     mac-syphon
21:44:30.105:     mac-capture
21:44:30.105:     mac-avcapture
21:44:30.105:     image-source
21:44:30.105:     frontend-tools
21:44:30.105:     decklink-output-ui
21:44:30.105:     decklink-captions
21:44:30.105:     coreaudio-encoder
21:44:30.105: ---------------------------------
21:44:30.105: [obs-websocket] [obs_module_post_load] Post load started.
21:44:30.105: [obs-websocket] [obs_module_post_load] obs-websocket plugin API version: 2
21:44:30.105: [obs-websocket] [obs_module_post_load] Called GetVersion. Status Code: 100 | Comment: (null) | Response Data: {"availableRequests":["GetMonitorList","OpenInputInteractDialog","SetMediaInputCursor","ToggleRecordPause","StopRecord","ToggleRecord","GetRecordStatus","SendStreamCaption","TriggerMediaInputAction","StopStream","StartStream","SetOutputSettings","GetOutputSettings","StartOutput","ToggleOutput","SaveReplayBuffer","StopReplayBuffer","StartReplayBuffer","StopVirtualCam","StartVirtualCam","SetSceneItemPrivateSettings","GetStudioModeEnabled","GetSceneItemPrivateSettings","SetSceneItemBlendMode","GetSourceFilterDefaultSettings","SetSceneItemLocked","GetLastReplayBufferReplay","GetSceneItemBlendMode","GetSceneItemTransform","GetGroupSceneItemList","GetSceneItemId","ToggleVirtualCam","GetSceneItemList","GetInputList","GetVideoSettings","DuplicateSceneItem","GetSourcePrivateSettings","GetSourceScreenshot","SetSourceFilterIndex","RemoveScene","GetSceneItemIndex","SetTBarPosition","GetSourceFilter","OpenInputFiltersDialog","SetSourceFilterName","RemoveSourceFilter","GetSourceFilterList","GetMediaInputStatus","TriggerStudioModeTransition","GetCurrentSceneTransitionCursor","SetCurrentSceneTransitionDuration","OffsetMediaInputCursor","GetVirtualCamStatus","CreateSourceFilter","SetCurrentSceneTransition","GetTransitionKindList","SetSceneItemEnabled","SetSceneItemIndex","SetInputAudioTracks","GetInputVolume","GetInputAudioTracks","SetCurrentProgramScene","SetInputAudioMonitorType","SetInputAudioSyncOffset","SetInputAudioBalance","GetCurrentSceneTransition","SetInputSettings","SetSourceFilterEnabled","GetInputSettings","OpenSourceProjector","SetSceneItemTransform","GetInputAudioBalance","BroadcastCustomEvent","GetPersistentData","SetInputName","GetInputKindList","CreateSceneCollection","GetOutputStatus","GetSceneSceneTransitionOverride","SetInputMute","SetCurrentSceneTransitionSettings","GetSceneTransitionList","PauseRecord","SetSceneSceneTransitionOverride","OpenVideoMixProjector","SetCurrentPreviewScene","SetSceneName","CreateScene","GetInputAudioSyncOffset","GetStreamStatus","GetGroupList","GetOutputList","GetSceneList","CreateSceneItem","GetInputMute","GetCurrentProgramScene","SetSourceFilterSettings","CallVendorRequest","SetStreamServiceSettings","SaveSourceScreenshot","GetRecordDirectory","GetInputDefaultSettings","GetStreamServiceSettings","CreateProfile","RemoveProfile","ResumeRecord","GetInputAudioMonitorType","RemoveInput","OpenInputPropertiesDialog","ToggleReplayBuffer","GetHotkeyList","SetCurrentSceneCollection","GetSceneItemLocked","GetSceneCollectionList","GetProfileList","ToggleInputMute","TriggerHotkeyByKeySequence","CreateInput","GetCurrentPreviewScene","TriggerHotkeyByName","SetStudioModeEnabled","GetSourceActive","SetVideoSettings","PressInputPropertiesButton","SetProfileParameter","SetInputVolume","ToggleStream","SetSourcePrivateSettings","Sleep","StartRecord","GetReplayBufferStatus","SetPersistentData","GetProfileParameter","GetInputPropertiesListPropertyItems","GetSpecialInputs","GetStats","RemoveSceneItem","StopOutput","SetCurrentProfile","GetVersion","GetSceneItemEnabled"],"obsVersion":"29.1.3","obsWebSocketVersion":"5.2.3","platform":"macos","platformDescription":"macOS Ventura (13.5)","rpcVersion":1,"supportedImageFormats":["bmp","cur","heic","heif","icns","ico","jp2","jpeg","jpg","pbm","pgm","png","ppm","tif","tiff","wbmp","webp","xbm","xpm"]}
21:44:30.105: [obs-websocket] [obs_module_post_load] Post load completed.
21:44:30.109: [VideoToolbox encoder]: Added VideoToolbox encoders
21:44:30.109: QWidget::setTabOrder: 'first' and 'second' must be in the same window
21:44:30.109: ==== Startup complete ===============================================
21:44:30.117: Switched to Preview/Program mode
21:44:30.117: ------------------------------------------------
21:44:30.141: All scene data cleared
21:44:30.141: ------------------------------------------------
21:44:31.314: coreaudio: Device 'Nisheng M3' [48000 Hz] initialized
21:44:31.314: [Loaded global audio device]: 'Mic/Aux'
21:44:31.333: Main Cam: Selected device 'NexiGo N930E FHD Webcam'
21:44:31.336: Main Cam: Using preset High
21:44:31.406: top Cam: Could not initialize device with unique ID '0x23000001bcf28c4'
21:44:31.406: Switched to scene 'Scene'
21:44:31.406: User switched Program to scene 'Scene'
21:44:31.407: ------------------------------------------------
21:44:31.407: Loaded scenes:
21:44:31.407: - scene 'Scene':
21:44:31.407:     - source: 'Main Cam' (av_capture_input_v2)
21:44:31.407:     - source: 'top Cam' (av_capture_input_v2)
21:44:31.407: ------------------------------------------------
21:44:31.546: YT: InitYTUserUrl() User is not signed
21:44:31.547: YT: InitYTUserUrl() User is not signed
21:44:31.779: [mac-virtualcam] macOS Camera Extension user approval required.
21:44:34.771: adding 106 milliseconds of audio buffering, total audio buffering is now 106 milliseconds (source: Mic/Aux)
21:44:34.771: 
21:44:34.854: adding 85 milliseconds of audio buffering, total audio buffering is now 192 milliseconds (source: Mic/Aux)
21:44:34.854: 
21:44:34.963: adding 106 milliseconds of audio buffering, total audio buffering is now 298 milliseconds (source: Mic/Aux)
21:44:34.963: 
21:44:35.027: adding 64 milliseconds of audio buffering, total audio buffering is now 362 milliseconds (source: Mic/Aux)
21:44:35.027: 
21:44:35.108: adding 85 milliseconds of audio buffering, total audio buffering is now 448 milliseconds (source: Mic/Aux)
21:44:35.108: 
21:44:44.908: top Cam: Selected device 'USB Video'
21:44:44.908: top Cam: Using preset High
21:44:47.129: top Cam: Selected device 'Nisheng M3'
21:44:47.129: top Cam: Using preset High
21:44:49.351: top Cam: Capturing 'Nisheng M3' (0x23112001bcf28c4):
21:44:49.351: 	Resolution: 2592x1944
21:44:49.351: 	FPS: 30 (30000030/1000000)
21:44:49.351: 	Frame interval: 0.0333333 s
21:44:49.351: 	Input format: Auto (actual: NV12 - 420YpCbCr8BiPlanar (420v))
21:44:49.351: 	Requested color space: Auto (-1)
21:44:49.351: 	Requested video range: Auto (-1)
21:44:49.351: 	Using format: <AVCaptureDeviceFormat: 0x6000027a2bb0> 'vide'/'420v' 2592x1944, { 30.00 fps }
21:44:50.442: top Cam: Selected preset AVCaptureSessionPresetHigh
21:44:58.897: Main Cam: Device with unique ID '0x24000001bcf2284' disconnected
21:45:02.278: Main Cam: Device with unique ID '0x24000001bcf2284' connected, resuming capture
21:45:02.278: Main Cam: Selected device 'NexiGo N930E FHD Webcam'
21:45:02.278: Main Cam: Using preset High
21:45:03.624: coreaudio: device 'Nisheng M3' disconnected or changed.  attempting to reconnect
21:45:04.109: coreaudio: Device 'NexiGo N930E FHD Webcam Audio' [48000 Hz] initialized
21:45:29.768: ==== Shutting down ==================================================
21:45:29.875: All scene data cleared
21:45:29.875: ------------------------------------------------
21:45:29.918: [obs-websocket] [obs_module_unload] Shutting down...
21:45:29.919: Tried to call obs_frontend_remove_event_callback with no callbacks!
21:45:29.919: Tried to call obs_frontend_get_global_config with no callbacks!
21:45:29.919: [obs-websocket] [Config::Save] Unable to fetch OBS config!
21:45:29.919: [obs-websocket] [obs_module_unload] Finished shutting down.
21:45:29.932: [Scripting] Total detached callbacks: 0
21:45:29.932: Freeing OBS context data
21:45:29.938: == Profiler Results =============================
21:45:29.939: run_program_init: 2128.03 ms
21:45:29.939:  ┣OBSApp::AppInit: 3.061 ms
21:45:29.939:  ┃ ┗OBSApp::InitLocale: 0.984 ms
21:45:29.939:  ┗OBSApp::OBSInit: 2029.76 ms
21:45:29.939:    ┣obs_startup: 1.095 ms
21:45:29.939:    ┗OBSBasic::OBSInit: 1954.47 ms
21:45:29.939:      ┣OBSBasic::InitBasicConfig: 0.11 ms
21:45:29.939:      ┣OBSBasic::ResetAudio: 0.065 ms
21:45:29.939:      ┣OBSBasic::ResetVideo: 194.197 ms
21:45:29.939:      ┃ ┗obs_init_graphics: 194.067 ms
21:45:29.939:      ┃   ┗shader compilation: 163.159 ms
21:45:29.939:      ┣OBSBasic::InitOBSCallbacks: 0.002 ms
21:45:29.939:      ┣OBSBasic::InitHotkeys: 0.011 ms
21:45:29.939:      ┣obs_load_all_modules2: 115.201 ms
21:45:29.939:      ┃ ┣obs_init_module(aja-output-ui): 0.05 ms
21:45:29.939:      ┃ ┣obs_init_module(aja): 0.033 ms
21:45:29.939:      ┃ ┣obs_init_module(coreaudio-encoder): 0.002 ms
21:45:29.939:      ┃ ┣obs_init_module(decklink-captions): 0 ms
21:45:29.939:      ┃ ┣obs_init_module(decklink-output-ui): 0 ms
21:45:29.939:      ┃ ┣obs_init_module(decklink): 0.018 ms
21:45:29.939:      ┃ ┣obs_init_module(frontend-tools): 1.219 ms
21:45:29.939:      ┃ ┣obs_init_module(image-source): 0.003 ms
21:45:29.939:      ┃ ┣obs_init_module(mac-avcapture): 68.559 ms
21:45:29.939:      ┃ ┣obs_init_module(mac-capture): 0.037 ms
21:45:29.939:      ┃ ┣obs_init_module(mac-syphon): 0.004 ms
21:45:29.939:      ┃ ┣obs_init_module(mac-videotoolbox): 0.004 ms
21:45:29.939:      ┃ ┣obs_init_module(mac-virtualcam): 0.003 ms
21:45:29.939:      ┃ ┣obs_init_module(obs-browser): 15.757 ms
21:45:29.939:      ┃ ┣obs_init_module(obs-ffmpeg): 0.039 ms
21:45:29.939:      ┃ ┣obs_init_module(obs-filters): 0.011 ms
21:45:29.939:      ┃ ┣obs_init_module(obs-outputs): 0.002 ms
21:45:29.939:      ┃ ┣obs_init_module(obs-transitions): 0.002 ms
21:45:29.939:      ┃ ┣obs_init_module(obs-vst): 0 ms
21:45:29.939:      ┃ ┣obs_init_module(obs-webrtc): 0.003 ms
21:45:29.939:      ┃ ┣obs_init_module(obs-websocket): 2.173 ms
21:45:29.939:      ┃ ┣obs_init_module(obs-x264): 0 ms
21:45:29.939:      ┃ ┣obs_init_module(rtmp-services): 0.515 ms
21:45:29.939:      ┃ ┣obs_init_module(text-freetype2): 0.011 ms
21:45:29.939:      ┃ ┗obs_init_module(vlc-video): 1.207 ms
21:45:29.939:      ┣obs_websocket_request_processing: 0.061 ms
21:45:29.939:      ┣OBSBasic::InitService: 1.383 ms
21:45:29.939:      ┣OBSBasic::ResetOutputs: 5.857 ms
21:45:29.939:      ┣OBSBasic::CreateHotkeys: 0.016 ms
21:45:29.939:      ┣OBSBasic::InitPrimitives: 0.031 ms
21:45:29.939:      ┗OBSBasic::Load: 1290.82 ms
21:45:29.939: obs_hotkey_thread(25 ms): min=0 ms, median=0 ms, max=0.037 ms, 99th percentile=0.001 ms, 100% below 25 ms
21:45:29.939: audio_thread(Audio): min=0.003 ms, median=0.043 ms, max=1.135 ms, 99th percentile=0.698 ms
21:45:29.939: obs_graphics_thread(16.6667 ms): min=0.051 ms, median=3.625 ms, max=81.656 ms, 99th percentile=4.934 ms, 99.8326% below 16.667 ms
21:45:29.939:  ┣tick_sources: min=0 ms, median=0.019 ms, max=81.488 ms, 99th percentile=0.055 ms
21:45:29.939:  ┣output_frame: min=0.043 ms, median=0.659 ms, max=7.71 ms, 99th percentile=1.731 ms
21:45:29.939:  ┃ ┗gs_context(video->graphics): min=0.042 ms, median=0.658 ms, max=7.709 ms, 99th percentile=1.73 ms
21:45:29.939:  ┃   ┣render_video: min=0.009 ms, median=0.439 ms, max=6.122 ms, 99th percentile=1.348 ms
21:45:29.939:  ┃   ┃ ┗render_main_texture: min=0.008 ms, median=0.429 ms, max=6.12 ms, 99th percentile=1.34 ms
21:45:29.939:  ┃   ┗gs_flush: min=0.026 ms, median=0.231 ms, max=1.584 ms, 99th percentile=0.404 ms
21:45:29.939:  ┗render_displays: min=0 ms, median=2.751 ms, max=20.434 ms, 99th percentile=3.688 ms
21:45:29.939: =================================================
21:45:29.939: == Profiler Time Between Calls ==================
21:45:29.939: obs_hotkey_thread(25 ms): min=25.02 ms, median=28.668 ms, max=31.407 ms, 4.57979% within ±2% of 25 ms (0% lower, 95.4202% higher)
21:45:29.939: obs_graphics_thread(16.6667 ms): min=0.698 ms, median=16.667 ms, max=81.658 ms, 77.6228% within ±2% of 16.667 ms (11.3281% lower, 11.0491% higher)
21:45:29.939: =================================================
21:45:29.949: Number of memory leaks: 0

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by javmast3r** [comment]
They sent me to GitHub from the forums and Discord. Only happens with OBS, other programs can open the cameras normally. Regards, Javier RiveraOn Aug 22, 2023, at 11:00 PM, Joel Bethke ***@***.***> wrote:﻿
Closed #9472 as not planned.
