### ISSUE TITLE
The text display color of the tooltip is incorrect

### ISSUE THREAD

**Issue by TianQiBuTian** [obsproject/obs-studio#9473]
### Operating System Info

Windows 10

### OBS Studio Version

30.0.0-beta1

### OBS Studio Version (Other)

Exactly after 807c8a9106d0ea62a6f53f406eaceffa52137632

### OBS Studio Log URL

UI bug

### Expected Behavior

![before](https://github.com/obsproject/obs-studio/assets/26628474/16571a87-8c72-4d66-b98d-3d5784b8596f)

### Current Behavior

![after](https://github.com/obsproject/obs-studio/assets/26628474/79e4c4cf-4c7b-4990-8f45-176bbbecfe34)

### Steps to Reproduce

↑

### Anything else we should know?

Currently, I see a special and correct text color.
![sp](https://github.com/obsproject/obs-studio/assets/26628474/d4df6178-ce90-456a-811b-c2f9bd9a0c7f)

**Comment by NextThread** [comment]
hi, can I work on this?

**Comment by TianQiBuTian** [comment]
> hi, can I work on this?

Yea, sure.

**Comment by WizardCM** [comment]
I did some heavy testing, and here's what I found:

* It's not the palette (currently using `palette(text)`)
* It's not the positioning of QToolTip within the Stylesheet (tried moving it to the end)
* `color` just does not seem to work 
* Seems to be Windows-only?

Example
```css
QToolTip {
    background-color: blue;
    color: pink;
    border: none;
}
```
`background-color` correctly changes, `color` does not.
