### ISSUE TITLE
WHIP/WebRTC support missing on linux release

### ISSUE THREAD

**Issue by pdiasgon** [obsproject/obs-studio#9484]
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

30.0.0-beta1

### OBS Studio Log URL

NA

### Expected Behavior

As per release notes, WHIP / WebRTC support should be avialable as an option for stream output.

### Current Behavior

No WHIP option avialable for stream output

### Steps to Reproduce

1. Download and install OBS 30.0.0 beta 
2. Launch OBS
3. Goto settings -> stream -> services 
4. No WHIP option avialable.

### Anything else we should know?

It seams to me that OBS for linux is compiled without WEBRTC option enabled as /usr/local/lib/plugins does not contain webrtc output libs.

Apologise for bad english.

**Comment by tytan652** [comment]
The dependency (which is in alpha) required to enable WHIP is not available on Ubuntu 22.04.

**Comment by Gol-D-Ace** [comment]
Hi
Ubuntu / Debian currently doesn't offer a package for libdatachannel.

Therefore it isn't possible to build OBS Studio on the PPA with WHIP support for now.

If you need WHIP support I may suggest our Flatpak for now.

**Comment by theofficialgman** [comment]
@tytan652 @Gol-D-Ace your answers are, simply put, bad.

@pdiasgon the problem is not really that the library [libdatachannel](https://github.com/paullouisageneau/libdatachannel) isn't available in 22.04's apt repositories but more so that the library is MPL2. If the library was also GPLv2 like OBS Studio then OBS Studio could statically build it into the project without an issue. But since it is MPL2, they cannot legally do that and can only dynamically link to that library. 

Now why don't they package libdatachannel into the deb as a separate library and dynamically link it I do not know. That is what is done for the flatpak and can be done for the deb as well.

**Comment by Gol-D-Ace** [comment]
If you find the truth bad then I'm sorry.

The library not being available in the Ubuntu repos is the reason for the delay.

You mentioned the exact reasons why it isn't available (yet).

**Comment by theofficialgman** [comment]
> If you find the truth bad then I'm sorry.
> 
> The library not being available in the Ubuntu repos is the reason for the delay.
> 
> You mentioned the exact reasons why it isn't available (yet).

actually you just proved your own answers inadequate with your response. thanks. in the future instead of saying "sorry use the flatpak", say why it isn't available like my response.
It took no extra time and actually explains the reason.

**Comment by Fenrirthviti** [comment]
> > If you find the truth bad then I'm sorry.
> > The library not being available in the Ubuntu repos is the reason for the delay.
> > You mentioned the exact reasons why it isn't available (yet).
> 
> actually you just proved your own answers inadequate with your response. thanks.
> 
> in the future instead of saying "sorry, use the flatpak", say why it isn't available like my response. It would have taken no extra time for you to do and actually explains the reason to the user and anyone (like myself) looking up why it is missing.

I'm going to take this opportunity to issue an official warning for your conduct on our repository. You need to tone the attitude down, as well as the condescending and rude comments. Your comments across multiple issue posts, and in our discord, have been needlessly confrontational. Nobody has acted this way towards you and you are continuing to, frankly, be an ass for no reason at all.

Failure to comply with our [code of conduct](https://github.com/obsproject/obs-studio/blob/master/COC.rst) may result in action being taken, including a permanent ban from our communities.

Thank you for understanding.
