### ISSUE TITLE
Virtual camera does not pass through RDP

### ISSUE THREAD

**Issue by MattCarothers** [obsproject/obs-studio#9493]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.3

### OBS Studio Log URL

None

### Expected Behavior

My camera is plugged into my local machine, and I run OBS there.  When I log into a remote machine, I should see the virtual camera under Local Resources that I can share with the remote machine.

### Current Behavior

The physical camera is present, but the virtual camera does not show up.

![image](https://github.com/obsproject/obs-studio/assets/4381389/2f7148bd-cbe3-478c-b67c-58323c6d0e85)

### Steps to Reproduce

1. Open Remote Desktop
2. Click Show Options
3. Click the Local Resources tab
4. Click "More ..." under "Local devices and resources"
5. Expand the "Video capture devices" section
6. Observe that the OBS virtual camera is not listed

**Comment by Fenrirthviti** [comment]
What exactly leads you to believe this should be supported? We register the device as a virtual directshow device. If RDP doesn't see it, it likely doesn't support it. Can you show where this works with other virtual devices?

**Comment by MattCarothers** [comment]
Hi, Joel.  My use case relates to remote work.  I can only access work resources from my corporate PC, so I RDP from my personal PC to my work PC.  My camera is plugged into my personal PC, so I need to get the video over to my work PC via RDP in order to use it for Zoom, etc.

According to a post at https://superuser.com/questions/1768223/passthrough-of-virtual-devices-through-remote-desktop, there are three products today that create virtual webcams that show up as USB devices for RDP:

* e2eSoft VCam
* ManyCam
* AlterCam

**Comment by RytoEX** [comment]
> there are three products today that create virtual webcams that show up as USB devices for RDP:
> * e2eSoft VCam
> * ManyCam
> * AlterCam

These products install a driver to act as the virtual camera. OBS' Virtual Camera does not, which is why it will not show up as a device, USB or otherwise, in Device Manager or anything else that is looking for a device in such a manner. As such, this use-case sounds unsupported.
