### ISSUE TITLE
obs 30 beta 2 crashing on x11, not wayland tho

### ISSUE THREAD

**Issue by pollux56** [obsproject/obs-studio#9494]
### Operating System Info

Other

### Other OS

Fedora

### OBS Studio Version

30.0.0-beta2

### OBS Studio Log URL

https://obsproject.com/logs/opTR5iVR390fYC3e

### OBS Studio Crash Log URL

https://obsproject.com/logs/AMturHJLBkYVw3Xq

### Expected Behavior

it opens and doesnt crash on x11 after a couple of seconds

### Current Behavior

it opens, seems to load everything fine then after a couple of seconds it crashes only in x11 on either kde plasma or gnome

i opened it through the terminal and it also didnt seem to have any issues 

i have had a couple of tries where it will open fine but most of the time it will crash

it only works fine in wayland which is ok but i want screen tearing when playing games on stream  

### Steps to Reproduce

1.be in a x11 environment on either gnome or kde plasma
2.install obs beta flatpak
3.open it 
...

**Comment by pollux56** [comment]
interesting, installing it on my intel, nvidia system it doesnt crash hmmm might be something wrong with my flatpak idk

**Comment by GeorgesStavracas** [comment]
Thanks. There's nothing in the logs that could indicate what's the root cause of this crash. Could you please provide us a coredump?

**Comment by pollux56** [comment]
https://drive.google.com/file/d/1bzUco_tzkvJCtzB4auq_4Gba0r2x9Q29/view?usp=sharing

is this what your looking for?
sorry iv never done a coredump before lol

**Comment by pollux56** [comment]
> Thanks. There's nothing in the logs that could indicate what's the root cause of this crash. Could you please provide us a coredump?

https://drive.google.com/file/d/1bzUco_tzkvJCtzB4auq_4Gba0r2x9Q29/view?usp=sharing

is this what your looking for?
sorry, iv never done a coredump before lol

**Comment by pollux56** [comment]
edit seems to have fixed itself after reinstalling fedora, i shall close this, thanks for the reply george :)
