### ISSUE TITLE
OBS failing to load plugins

### ISSUE THREAD

**Issue by phill-85** [obsproject/obs-studio#9495]
### Operating System Info

Other

### Other OS

Ubuntu 23.04

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/vvsTxMBhwUoinu1P

### Expected Behavior

Plugins do not load

### Current Behavior

Installed using the ubuntu instructions at https://obsproject.com/download#linux

### Steps to Reproduce

1. install obs
2. install ptz plugin
3. ptz plugin does not load
...

### Anything else we should know?

the double forward slash in "/usr//lib/" look suspicious

**Comment by mihawk90** [comment]
This is not an issue with OBS. If you have an issue with a plugin, ask the plugin author for support.

And also you're missing a dependency. Clearly.

**Comment by tytan652** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by phill-85** [comment]
> And also you're missing a dependency. Clearly.

I mean, yeah something isn't right but its not clear what's missing. Perhaps as your so cleaver you'd like to enlighten me?
 
> I find it somewhat ironic that you notice the double-slash (which by the way is irrelevant), but not the actual error in the same line.

Yeah I saw it said it couldn't open the shared object, I'm sorry if my dumb ass was trying to help by pointing out what I thought the cause of this error may be.

**Comment by mihawk90** [comment]
The log is telling you it can't find `libQt6SerialPort.so.6`. You need whatever package provides this. But again, this is a packaging issue of the plugin.

The plugin package should specify the dependencies it needs so the package manager can resolve the dependencies and install them with the plugin. Obviously that is not happening and therefore this is an issue that should be reported to the plugin author.

Perhaps here:
glikely/obs-ptz#156
