### ISSUE TITLE
Simple mode encoder not being saved for AMD h264

### ISSUE THREAD

**Issue by flaeri** [obsproject/obs-studio#9497]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.0-beta2

### OBS Studio Log URL

https://obsproject.com/logs/EPfMa3HW5f63voNF

### Expected Behavior

When I go into the settings (both on an existing profile and new/fresh), and try to change the simple mode encoder to AMD, it will now be saved/stored in the basic.ini. I expect that when I close and re-open OBS, it will remember my encoder selection in simple mode

### Current Behavior

When you go into the settings, and try to change the simple mode encoder from x264 to AMD h264, it will bot be stored. It is not written to the profile basic.ini, and upon the next launch, you will find that the UI is back to showing and using x264.

### Steps to Reproduce

0. Have AMD h264 capable hardware
1. Create a new profile
2. Go into the settings, and change the streaming encoder to "Hardware (AMD, H.264)
3. Hit ok
4. Close OBS, and re-open it
5. Observe UI showing x264 again
6. Start recording, and observe the log using x264

### Anything else we should know?

[AMD30beta2.zip](https://github.com/obsproject/obs-studio/files/12406023/AMD30beta2.zip)
Example of file where I have just changed to the AMD h264 encoder in simple mode, and quit obs.

You can use the encoder (and it is correctly set and working) after you set it, but upon closing OBS, and opening it again, you'll find that the UI and the actual encoder that gets used is x264.

It happens not only for the stream encoder, but also the recording encoder.

It works fine in advanced mode.

If I manually type in `h264_texture_amf` into the basic.ini, it neither uses nor shows (in the UI) the correct encoder.

Other encoders seem fine, like `nvenc` is stored and works correctly in the .ini file and in the UI if I change to that one

**Comment by flaeri** [comment]
I left out a piece of information, because I was lookign at the wrong profile.

Upon changing the simple mode encoders. the basic.ini gets updated with this value:
```
StreamEncoder=amd
RecEncoder=amd
```
As soon as you restart OBS, this value gets changed to x264

**Comment by flaeri** [comment]
In simple mode, if you change the video encoder on the recording encoder to AMF HEVC `amd_hevc`, then this is stored and remembered.

It seems that its just the name for the simple mode amf h264 encoder (which now seems to be `amd`) that is either incorrectly named, or incorrectly parsed.

**Comment by tytan652** [comment]
Just for clarification:
If you set the encoder to AMF and save, and start a stream does it use AMF ?
And if you quit and re-open OBS without checking settings and start a stream does it use AMF ?

**Comment by flaeri** [comment]
Yes, I can select the AMF h264, and stream/record. It works fine. As soon as your close start OBS, thats when it gets overwritten.

**Comment by flaeri** [comment]
Finally managed to bisect:
```
edf2c8210ca45d4d25c96ac1b9afc122caadb529 is the first bad commit
commit edf2c8210ca45d4d25c96ac1b9afc122caadb529
Author: derrod <dennis@obsproject.com>
Date:   Wed Jan 25 21:59:28 2023 +0100

    cmake,plugins,build-aux: Remove enc-amf

 .gitmodules                 | 3 ---
 build-aux/.run-format.zsh   | 4 ++--
 cmake/windows/helpers.cmake | 2 --
 plugins/CMakeLists.txt      | 9 ---------
 plugins/enc-amf             | 1 -
 5 files changed, 2 insertions(+), 17 deletions(-)
 delete mode 160000 plugins/enc-amf
```

Seems that when we removed the legacy enc-amf plugin/submodule, something was not accounted for.
This does not really point us in any specifics to the code, but at least its good to know the cause.
