### ISSUE TITLE
@ not working in youtube dock

### ISSUE THREAD

**Issue by bzzzbrasil** [obsproject/obs-studio#9506]
### Operating System Info

Windows 10

### OBS Studio Version

30.0.0-beta2

### OBS Studio Log URL

https://obsproject.com/logs/52rMjBHupywQfn4m

### Expected Behavior

when entering the email address of the google account we should be able to enter the @

### Current Behavior

the @ key (french keyboard) does not work in the youtube dock

### Steps to Reproduce

1.just try to enter an @
2.
3.
...

### Anything else we should know?

Have a good day

**Comment by Fenrirthviti** [comment]
Which dock exactly shows this issue? Can you provide a screenshot or more clear steps to reproduce? There are several places that a login prompt might be provided, we need to know which one you are trying to use.
