### ISSUE TITLE
use AMD HW AV1 record video a causes code overload

### ISSUE THREAD

**Issue by txs1234** [obsproject/obs-studio#9512]
### Operating System Info

Windows 10

### OBS Studio Version

30.0.0-beta2

### OBS Studio Log URL

https://obsproject.com/logs/T9iBiS47Zr5CS3N2

### Expected Behavior

Record video with amd hw av1

### Current Behavior

When AMD HW AV1 encoder is used, encoding overload can result, which in turn reduces the number of video frames, a problem that does not occur with other hardware encoders

### Steps to Reproduce

1.Record using the AMD HW AV1 encoder

### Anything else we should know?

This is the only type of encoder that causes recording problems, so I don't think it's a graphics card performance issue

**Comment by tytan652** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
