### ISSUE TITLE
OBS Studio 29.1.3 cannot Startup Fully

### ISSUE THREAD

**Issue by Ryu945** [obsproject/obs-studio#9521]
### Operating System Info

Other

### Other OS

Fedora Gnome 37

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/jqJldIKlVXUyHcyJ

### Expected Behavior

For the application to start up.  Twitch information panel and chat panel to load.

### Current Behavior

It complains that obs-ndi plugin is not loading.   It says to remove it to try to fix the problem.  I never installed any plugin like that.  I even tried removing all plugins.   This bug is causing the Twitch Stream information and chat pages to not load.

### Steps to Reproduce

1.Update OBS Studio to 29.1.3 on Fedora Gnome 37 ( using X11)
2.Start OBS Studio

### Anything else we should know?

Just running OBS Studio a single time in default configurations could have shown this bug.  What type of testing does the Linux versions of OBS Studio receive?  Are there not accounts with the different streaming services setup used in start up testing?

**Comment by WizardCM** [comment]
This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels below, and if it's determined that this is indeed a bug, then we will re-open this issue.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

**Comment by mihawk90** [comment]
To add on to this:

When you report a supposed issue, stop stating incorrect information.

You are *not* on Fedora. You are on Nobara. It is *based* on Fedora but it has changed enough that it *is not* Fedora.

Besides: the Linux version is tested and works perfectly fine (on Fedora too I might add), but third-party packages are not our responsibility, nor is installing plugins by default.
All of which is done *by Nobara*.
They explicitemy state this on their project page.

**Comment by Ryu945** [comment]
> To add on to this:
> 
> When you report a supposed issue, stop stating incorrect information.
> 
> You are _not_ on Fedora. You are on Nobara. It is _based_ on Fedora but it has changed enough that it _is not_ Fedora.
> 
> Besides: the Linux version is tested and works perfectly fine (on Fedora too I might add), but third-party packages are not our responsibility, nor is installing plugins by default. All of which is done _by Nobara_. They explicitemy state this on their project page.


Thankyou.  I was not aware of Nobara installing custom plugins on the X11 version which I thought was the default version.

**Comment by mihawk90** [comment]
It's not an "X11 version". It's Nobara's package.

**Comment by Ryu945** [comment]
I discovered the solution was to update Nobara 37 to Nobara 38.  Then it offered the correct packages to run OBS Studio.  Remaining on Nobara 37 past when I should have upgraded started installing the wrong packages.
