### ISSUE TITLE
Hide OBS is not  available on ScreenCaptureKit capable macs - why?

### ISSUE THREAD

**Issue by gchilds** [obsproject/obs-studio#9522]
### Operating System Info

macOS 13

### OBS Studio Version

30.0.0-beta2

### OBS Studio Log URL

no important logs

### OBS Studio Crash Log URL

no crash

### Expected Behavior

Hide obs is present / not disabled in the code

### Current Behavior

Hide OBS is not present / is disabled in the code

### Steps to Reproduce

1.run obs
2.go to general settings
3. look for hide obs
4. it's not there
5. enable hide_obs in the code
6. run
7. see that obs hiding works
8. wonder why it's disabled
...

**Comment by gxalpha** [comment]
Hide OBS is available. It’s not in general settings, but in the settings of the individual SCK capture sources.

**Comment by gchilds** [comment]
Thank you, sorry - my bad, I couldn't find it in the stable 29.1.3 then made the mistake of assuming it was not in the beta.
