### ISSUE TITLE
Flatpak org.kde.Platform 6.4 dependency reached EOL

### ISSUE THREAD

**Issue by lasombra** [obsproject/obs-studio#9542]
### Operating System Info

Other

### Other OS

Fedora 38

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/0bR3c622UyGQ6yNc

### Expected Behavior

```
> flatpak --user --system update
Looking for updates…

Nothing to do.
```

### Current Behavior

```
> flatpak --user --system update
Looking for updates…

Info: runtime org.kde.Platform branch 6.4 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Plaform and SDK
Info: applications using this runtime:
   com.obsproject.Studio
```

### Steps to Reproduce

1. ```flatkpak install com.obsproject.Studio```
2. ```flatpak uninstall org.kde.Platform//6.4```

**Comment by tytan652** [comment]
We are aware that the version 6.5 of the runtime is out but there is some pieces of software that needs to be updated before upgrading.
We also had an issue with with 6.5, which now we did made a workaround (#9373).
6.4 reaching end of life is not an issue, updating is planned.

Those warnings are not meant for end-users but mostly for packagers.

**Comment by cassiofb-dev** [comment]
I also just got this message:

```txt
localhost:~$ flatpak upgrade
Looking for updates…

Info: runtime org.kde.Platform branch 6.4 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Plaform and SDK
Info: applications using this runtime:
   com.obsproject.Studio
```

**Comment by credativ-dar** [comment]
> Those warnings are not meant for end-users but mostly for packagers, so the former should ignore them.

Still they are shown to the end-users at each update, at least when using the cli, which is quite annoying. (And one can't tell whether this is being worked on or not without further research.)

**Comment by Fenrirthviti** [comment]
This is resolved by https://github.com/obsproject/obs-studio/pull/9545 and is already on master branch. We normally close issues when the fixes have been merged, but I'm going to reopen this because too many people keep reporting it and not reading/searching existing issues or even the pinned issue at the top of the repo.

Hopefully this being open will help discovery that this is already known/fixed for next release.

**Comment by tytan652** [comment]
Re-closing as OBS Studio 30 is out on Flathub.
