### ISSUE TITLE
AMF encoder not work with RX6600XT in windows11

### ISSUE THREAD

**Issue by sjz123321** [obsproject/obs-studio#9547]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/pYgOKheNzc9pnOLo

### Expected Behavior

open the obs-studio software

### Current Behavior

can not use AMF encoder

### Steps to Reproduce

1.use AMD RX 6600XT
2.windows 11
3.open the software
...

### Anything else we should know?

RX590GME seems work well

**Comment by RytoEX** [comment]
Please explain "can not use AMF encoder". Does it not show up in the UI at all? Does it show up in the UI, but you get an error when you try to record/stream? I have an RX 6600M and it works fine.

Please check [this comment](https://github.com/obsproject/obs-studio/issues/9293#issuecomment-1694081024) for a possible cause:
> The issue occurred because you have a file in the root of your C drive called `Program` or `Program.exe`, `Program.vbs`, etc. OBS did not quote the path properly which caused it to find that file instead of the one it expected. You may wish to delete that file as this may affect other programs too.

**Comment by sjz123321** [comment]
> Please explain "can not use AMF encoder". Does it not show up in the UI at all? Does it show up in the UI, but you get an error when you try to record/stream? I have an RX 6600M and it works fine.
> 
> Please check [this comment](https://github.com/obsproject/obs-studio/issues/9293#issuecomment-1694081024) for a possible cause:
> 
> > The issue occurred because you have a file in the root of your C drive called `Program` or `Program.exe`, `Program.vbs`, etc. OBS did not quote the path properly which caused it to find that file instead of the one it expected. You may wish to delete that file as this may affect other programs too.

Only x264 encoder shows in UI . No AMF option
