### ISSUE TITLE
QSV fails on Intel A380 DG2 on Ubuntu 23.04

### ISSUE THREAD

**Issue by reedmcintosh** [obsproject/obs-studio#9548]
### Operating System Info

Other

### Other OS

Ubuntu 23.04

### OBS Studio Version

30.0.0-beta2

### OBS Studio Log URL

https://obsproject.com/logs/ik39mcxm06ZLQAGk

### Expected Behavior

QSV to encode AV1/HEVC/H264

### Current Behavior

QSV encode fails on AV1/HEVC/H264 with MFX_ERR_DEVICE_FAILED

### Steps to Reproduce

1. Install A380 as primary or secondary GPU
2. Install OBS 30 Beta2 from unstable PPA on Ubuntu 23.04
3. Select any QSV encoder with default settings

### Anything else we should know?

I intend to use the A380 as a secondary encoding GPU, but I tested with the A380 as the only GPU in the system to isolate the issue

Ubuntu 23.04 is used because the graphics stack should support DG2 out of the box per https://dgpu-docs.intel.com/driver/client/overview.html and onevpl drivers are installed correctly as far as I can tell

FFMPEG VAAPI encoding to HEVC/H264 works normally

**Comment by reedmcintosh** [comment]
Issue actually seems to be intermittent, could get encode to work if settings are not changed https://obsproject.com/logs/OO6TVv0lBhc9rDAs 

Might be related to #9324

**Comment by kkartaltepe** [comment]
Please test upcoming beta3 or build from master to see if this still occurs.
