### ISSUE TITLE
obs-websocket: GetStreamStatus and GetRecordStatus return outputDuration 0

### ISSUE THREAD

**Issue by norihiro** [obsproject/obs-studio#9550]
### Operating System Info

Other

### Other OS

Fedora 37

### OBS Studio Version

Git

### OBS Studio Version (Other)

112adb0a73c968658336a23d8dac1d02c82f6892

### OBS Studio Log URL

https://obsproject.com/logs/WWo5Y21MrsR5D79j

### Expected Behavior

`outputDuration` and `outputTimecode` returned by `GetStreamStatus` and `GetRecordStatus` should be non-zero.

### Current Behavior

`outputDuration` and `outputTimecode` returned by `GetStreamStatus` and `GetRecordStatus` are zero.

The returned status of `GetStreamStatus` is as below.
```json
{
	"outputActive": true,
	"outputBytes": 2296197,
	"outputCongestion": 0.0,
	"outputDuration": 0,
	"outputReconnecting": false,
	"outputSkippedFrames": 0,
	"outputTimecode": "00:00:00.000",
	"outputTotalFrames": 210
}
```

The returned status of `GetRecordStatus` is as below.
```json
{
	"outputActive": true,
	"outputBytes": 1029385,
	"outputDuration": 0,
	"outputPaused": false,
	"outputTimecode": "00:00:00.000"
}
```

### Steps to Reproduce

1. Configure streaming (in above log, I set SRT but the issue should happen if using encoded output types) and enable obs-websocket.
2. Restart OBS
3. Start streaming and recording
4. Wait some seconds
5. Call `GetStreamStatus` and `GetRecordStatus`. (I use this script. [request-websocket.py](https://github.com/norihiro/obs-command-source/blob/5f70af131869ca69dab6626fa36a27bcc83ab111/tools/request-websocket.py))

The issue was introduced 

### Anything else we should know?

Bisect reached my commit fb57eff212fbe5e777cf559288bc70bf67d9c428 (I locally fixed `libobs/data/default.effect` because the shader has syntax errors at that commit).

**Comment by tt2468** [comment]
I would prefer to implement an `obs_output_get_duration()` function to track true output duration. As one encoder can be assigned to multiple outputs, fetching duration from the video_t is not accurate anyway.

**Comment by norihiro** [comment]
The commit 2036de8ec3e in the master branch fixed this issue.
