### ISSUE TITLE
obs-websocket: Dangling pointer access in GetStreamStatus and GetRecordStatus

### ISSUE THREAD

**Issue by norihiro** [obsproject/obs-studio#9551]
### Operating System Info

Other

### Other OS

Fedora 37

### OBS Studio Version

29.1.3

### OBS Studio Version (Other)

c58e511813c33e93da7637d50aa431ae0cddda0c with modification

### OBS Studio Log URL

https://obsproject.com/logs/bHaewDVhx6RE3Vo9

### Expected Behavior

`GetRecordStatus` and `GetStreamStatus` return correct `outputDuration` and `outputTimecode`.

### Current Behavior

`GetRecordStatus` and `GetStreamStatus` have dangling pointer access so that  `outputDuration` and `outputTimecode` are invalid.

### Steps to Reproduce

1. Add these changes to `video_output_close`.
```patch
diff --git a/libobs/media-io/video-io.c b/libobs/media-io/video-io.c
index afa0fe5c4..b8bfac8b6 100644
--- a/libobs/media-io/video-io.c
+++ b/libobs/media-io/video-io.c
@@ -231,6 +231,8 @@ int video_output_open(video_t **video, struct video_output_info *info)
        if (!out)
                goto fail0;
 
+       blog(LOG_INFO, "video_output_open video=%p", out);
+
        memcpy(&out->info, info, sizeof(struct video_output_info));
        out->frame_time =
                util_mul_div64(1000000000ULL, info->fps_den, info->fps_num);
@@ -281,7 +283,8 @@ void video_output_close(video_t *video)
        pthread_mutex_destroy(&video->data_mutex);
        pthread_mutex_destroy(&video->input_mutex);
 
-       bfree(video);
+       blog(LOG_INFO, "video_output_close video=%p", video);
+       memset(video, 0x12, sizeof(*video));
 }
 
 static size_t video_get_input_idx(const video_t *video,
```
2. Build and start OBS
3. Change video settings (changed frame rate for example)
4. Start recording
5. Wait several seconds
6. Call `GetRecordStatus`. It returns as below.
```json
{
	"outputActive": true,
	"outputBytes": 2495594,
	"outputDuration": 1736164148113,
	"outputPaused": false,
	"outputTimecode": "482267:49:08.113"
}
```

### Anything else we should know?

On Linux, usually `bzalloc` followed by `bfree` returns the same address and `video_output_open` is called just after `video_output_close` during restarting video. Hence, the issue rarely happens.

If the revert PR #9536 is merged, this issue will raise again.

**Comment by tt2468** [comment]
Great find! Always wondered where this came from...

**Comment by notr1ch** [comment]
I think the safest thing to do is reset outputs when we change video, so there are no dangling video mixes accessible to OBS itself or through plugins. Try this commit: https://github.com/obsproject/obs-studio/commit/6fb63c52972b41caefdd939b3c252fbcb44ddf9a

**Comment by norihiro** [comment]
This is not an issue for now because #9536 was closed without merging.

Probably, the UI code to use `obs_x264` encoder has similar dangling pointer access but it should be a different issue.

**Comment by norihiro** [comment]
> I think the safest thing to do is reset outputs when we change video, so there are no dangling video mixes accessible to OBS itself or through plugins. Try this commit: [6fb63c5](https://github.com/obsproject/obs-studio/commit/6fb63c52972b41caefdd939b3c252fbcb44ddf9a)

I tested the commit 6fb63c5 and confirmed it fixes the crash on x264 encoder. (I'm afraid the x264 crash issue is not reported on GitHub issues yet but just discussed on Discord.)

**Comment by notr1ch** [comment]
The root cause of this and the x264 issue are the same though, changing the video settings resets video which leaves all outputs with dangling `video_t` pointers.

**Comment by RytoEX** [comment]
> > I think the safest thing to do is reset outputs when we change video, so there are no dangling video mixes accessible to OBS itself or through plugins. Try this commit: [6fb63c5](https://github.com/obsproject/obs-studio/commit/6fb63c52972b41caefdd939b3c252fbcb44ddf9a)
> 
> I tested the commit [6fb63c5](https://github.com/obsproject/obs-studio/commit/6fb63c52972b41caefdd939b3c252fbcb44ddf9a) and confirmed it fixes the crash on x264 encoder. (I'm afraid the x264 crash issue is not reported on GitHub issues yet but just discussed on Discord.)

Did this commit ever actually get merged to the master branch? It currently says, "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository."

**Comment by notr1ch** [comment]
No, it's still only on my branch as there are of course multiple ways to fix this (for example, libobs not allowing outputs to have dangling mixes to begin with).
