### ISSUE TITLE
OBS flatpak depends on end-of-life org.kde.Platform

### ISSUE THREAD

**Issue by sankasan** [obsproject/obs-studio#9560]
### Operating System Info

Other

### Other OS

Flatpak (Linux)

### OBS Studio Version

29.1.3

### OBS Studio Log URL

N/A, see "Current Behavior".

### Expected Behavior

OBS to use runtimes that are not end-of-life to have a secure sandbox environment.

### Current Behavior

```
flatpak update
Looking for updates…

Info: runtime org.kde.Platform branch 6.4 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Plaform and SDK
Info: applications using this runtime:
   com.obsproject.Studio

Nothing to do.
```

### Steps to Reproduce

1. Install OBS via flathub 
2. Update `flatpak update`
3. See the result as described in "Current Behavior".

**Comment by tytan652** [comment]
Duplicate of #9542
