### ISSUE TITLE
OBS 29.1.3 not loading video from AtomX Cast on 2 different PCs

### ISSUE THREAD

**Issue by dansperfect** [obsproject/obs-studio#9564]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://drive.google.com/file/d/1Igm7XobmBabGKxXbtVJtCsvZgmD2YfNo/view?usp=drive_link

### Expected Behavior

I expected the Atomx Cast Video to be displayed.

### Current Behavior

Shows a black Screen for the Atomx Cast even when the live is active on the Atomx Cast.

### Steps to Reproduce

1. Use a Clean installation where OBS has not been installed.
2. Install OBS Version 29.1.3
3. At the AtomX Cast as a Video Capture Device
4. Hit live on the AtomX Cast 

### Anything else we should know?

I installed OBS 29.1.1 and the video feed worked fine. I still have OBS 29.1.3 installed so I opened OBS 29.1.3 and the video began working now that 29.1.1 has been installed. But when I change the name of the OBS Studio 29.1.1 folder then launch 29.1.3 I get these errors. Failed to find local/en-US.ini and failed to load locale. So I'm unsure what 29.1.1 has installed the 29.1.3 doesn't have or what's not working correctly is beyond me and I'm hoping you can help me out here.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by dansperfect** [comment]
I dont need support. I explained i fixed the problem for myself but others
wont be so lucky. But hey if you dont care I sure as hell dont.

**Comment by Fenrirthviti** [comment]
The issue report doesn't say anything about you actually having it fixed, and the final comment says "I'm hoping you can help me out here." which is asking for support, and we don't provide support over github.

The errors you're getting indicate that your copy of OBS is not installed properly (i.e. the `Failed to find locale` message), or is not being launched from the correct working directory, all of which are support issues.

This report is, at best, confusingly presented and misleading. If you choose not to follow our process, there isn't much more for us to do. I'm glad you were able to figure things out, however.

**Comment by dansperfect** [comment]
You are no understanding anything I wrote. It does indicate I fixed the
ptoblem when I installed 29.1.1 like I stated and stated that once
installed 29.1.3 began working. I explained how those errors occured as
well.  Im sure glad I do not have to depend on you for help as I would just
quit with such horrible advice. What good would a log file showing
everything working do when Im trying to point out a problem in your
software? The statements you make, make it seem like your reading
comprehension is poor. You can close this. I dont need your help, and like
I stated before I do not care if anyonr else has the problem especially
when you all dont and just make retarded assumptions lile its not a bug its
support. No its a bug in 29.1.3 like the log file shows. Have a good day
though. Good luck.
