### ISSUE TITLE
Cannot select Channel in "YouTube Live Control Panel" Dock

### ISSUE THREAD

**Issue by rasamassen** [obsproject/obs-studio#9565]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.0-beta2

### OBS Studio Log URL

NA

### Expected Behavior

Option 1) Like the YouTube Chat dock, you're automatically logged in on the Live Control Panel dock after connected to the stream service in Settings.

Option 2) If that is not possible, when logging into the Live Control Panel dock, it would ask you which channel you want to use.

### Current Behavior

When logging into YouTube from Live Control Panel dock, it automatically selects the primary channel for the account and there is no option anywhere to select a secondary channel.

### Steps to Reproduce

1. Login to YouTube from Live Control Panel dock.
2. In the top right corner where the circle/icon appears, try to select a different channel.

### Anything else we should know?

My account has two channels. One is personal and one is professional. I primarily stream from the professional channel, but the personal channel is listed first. The Live Control Panel dock automatically selects the personal channel and has no option to select the professional channel, making it useless for me.

**Comment by RytoEX** [comment]
This is a known issue, but it is something that must be addressed on YouTube's end.

**Comment by joelgerard** [comment]
This is now fixed.
