### ISSUE TITLE
GPU and Async Delay Filters do not delay audio

### ISSUE THREAD

**Issue by PeterAkakpo** [obsproject/obs-studio#9566]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.3

### OBS Studio Log URL

N/A

### Expected Behavior

When delay is applied on a video , it should affect the audio too

### Current Behavior

When delay is applied on a video , only the image is affected

### Steps to Reproduce

1. Add a media source
2. add Render Delay or Video Delay(Async) filter
3. 
...

**Comment by WizardCM** [comment]
This is expected behaviour. These are video filters, not audio filters. This is indicated by their names. If you need to delay the audio to match, you can do so in the Advanced Audio Properties dialog under the "Sync Offset" field.
