### ISSUE TITLE
OBS crash report after stopping recording

### ISSUE THREAD

**Issue by Swarkin** [obsproject/obs-studio#9569]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.3

### OBS Studio Log URL

-

### OBS Studio Crash Log URL

[Crash 2023-09-07 12-43-38.txt](https://github.com/obsproject/obs-studio/files/12547791/Crash.2023-09-07.12-43-38.txt)

### Expected Behavior

The software not crashing.

### Current Behavior

The software crashed, but the video was saved properly.

### Steps to Reproduce

Not sure as I'm unable to reproduce it, but wanted to share the crash report in case it helps.

### Anything else we should know?

The only apps that were open while this happened was Discord and Godot Engine.

**Comment by WizardCM** [comment]
The crash occurred in the AMD graphics driver.

This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels below, and if it's determined that this is indeed a bug, then we will re-open this issue.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).
