### ISSUE TITLE
REGRESSION: VPL only available for AMD64

### ISSUE THREAD

**Issue by theofficialgman** [obsproject/obs-studio#9578]
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

30.0.0-beta2

### OBS Studio Log URL

NA

### Expected Behavior

Unable to build latest OBS Beta versions as is requires intels AMD64 only VPL developement headers.

### Current Behavior

Unable to successfully complete cmake

### Steps to Reproduce

1. attempt to run cmake on Linux on any non-AMD64 architecture

### Anything else we should know?

Intel OneAPI is AMD64 only as it is right now (for current distros at least) so this enabling support for this in OBS needs to be made optional so that distro maintainers can continue to build OBS Studio for other architectures.

**Comment by kkartaltepe** [comment]
We dont support non-AMD64 architectures on linux, disable features that dont work.

**Comment by tytan652** [comment]
Use `ENABLE_VPL` CMake option to disable it.

This sounds more likely to be a support request rather than a bug report, and we are not currently accepting feature requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://discord.gg/obsproject) for such request.

Thank you.

**Comment by theofficialgman** [comment]
> We dont support non-AMD64 architectures on linux, disable features that dont work.

@kkartaltepe please re-open. thats exactly the problem. the feature CANT be disabled currently. `ENABLE_VPL` DOES NOT EXIST

**Comment by theofficialgman** [comment]
@ty2570 too you. re-open

**Comment by derrod** [comment]
The option is called `ENABLE_QSV11`, but does exist.

**Comment by moo-the-cow** [comment]
ENABLE_QSV11=OFF worked for me on ARM64, do you guys test that architecture? it is valuable to me, because I can make use of the MALI gpu

**Comment by derrod** [comment]
> ENABLE_QSV11=OFF worked for me on ARM64, do you guys test that architecture? it is valuable to me, because I can make use of the MALI gpu

We don't. We currently do not support arm64 on Linux.
