### ISSUE TITLE
Upgrade from 29.0.2 > 29.1.3 Source Record Issue "ffmpeg-mux: Couldn't find an appropriate muxer"

### ISSUE THREAD

**Issue by ccollabgist** [obsproject/obs-studio#9593]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/Pb5MOGcEMZ1r6DB9

### Expected Behavior

All recordings, including Source Record recordings will be saved, as was the case in OBS v. 29.0.2. It'd be nice to be able to update OBS.

### Current Behavior

When updating OBS from 29.0.2 > 29.1.3, while using the Source Record plugin, the sources assigned the Source Record filter stop recording. There are no issues with the primary OBS recording; only Source Record recordings.

Upon checking the log data it appears that the os_process_pipe_write is failing and the ffmpeg-mux couldn't find an appropriate muxer.

Reverting to OBS 29.0.2 fixes the issue and all recording sources save accordingly. Would like to be able to update OBS to latest versions.

### Steps to Reproduce

1. Upgrade from 29.0.2 > 29.1.3 (with Source Record installed and assigned to some sources)
2. Start Recording
3. Source Records are not recording. Only the main OBS recording works.
4. Check logs > showing a Muxer issuer
4. Downgrade to 29.0.2 - Source Recordings working again.
...

**Comment by gxalpha** [comment]
Please report this to the plugin author first to make sure it’s not a plugin issue. If they determine it to be an OBS problem, we can reopen this issue.
