### ISSUE TITLE
Flatpak version: runtime org.kde.Platform branch 6.4 is end-of-life

### ISSUE THREAD

**Issue by MikeNavy** [obsproject/obs-studio#9598]
### Operating System Info

Ubuntu 20.04

### OBS Studio Version

29.1.3

### OBS Studio Log URL

Not logged in OBS Studio

### Expected Behavior

OBS Studio to use a supported runtime.

### Current Behavior

Flatpak message:
Info: runtime org.kde.Platform branch 6.4 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Playform and SDK
Info: applications using this runtime:
   com.obsproject.Studio

### Steps to Reproduce

just type "flatpak update" in a terminal

**Comment by GeorgesStavracas** [comment]
The next OBS Studio release already updated to the KDE platform v6.5 :+1: 

We can't update the current stable release due to API / ABI breakage.
