### ISSUE TITLE
Seemingly random crashes on qt6core.dll (30.0.0 beta versions)

### ISSUE THREAD

**Issue by Mr-Z-2697** [obsproject/obs-studio#9602]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.0.0-beta3

### OBS Studio Log URL

No log entries at the time of crash

### OBS Studio Crash Log URL

https://obsproject.com/logs/O7hEGlRVFaGMLXFq

### Expected Behavior

Don't crash, I guess?

### Current Behavior

Crashes.

### Steps to Reproduce

I haven't found any.
Mostly happens when starting recording, iirc.

### Anything else we should know?

I came from 29.1.3 -> 30.0.0-beta2 -> 30.0.0-beta3
30.0.0-beta2 gave me a lot crashes, then I used 30.0.0-beta3 for 5 days now and it haven't crashed until now.

**Comment by gxalpha** [comment]
> Steps to Reproduce
I haven't found any.

Did you start a recording when it crashed, or had something (plugin, script, websocket) start a recording?

**Comment by Mr-Z-2697** [comment]
> > Steps to Reproduce
> > I haven't found any.
> 
> Did you start a recording when it crashed, or had something (plugin, script, websocket) start a recording?

I did, this time, 
but I can't be sure about previous ones, they are more than 5 days ago and I thought the problem was fixed in beta3.

**Comment by gxalpha** [comment]
Could you also share those previous crash logs? Also, could you please attach a current normal OBS log?

**Comment by Mr-Z-2697** [comment]
[qt6core-dll-crash-reports.zip.txt](https://github.com/obsproject/obs-studio/files/12641432/qt6core-dll-crash-reports.zip.txt) (this is a zip file actually, sorry looks like github don't like zip files despite it says it supports)
Looks like they are all happen when start or stop a recording

**Comment by Mr-Z-2697** [comment]
> Could you also share those previous crash logs? Also, could you please attach a current normal OBS log?

this is current log, crash reports in comment above https://obsproject.com/logs/czysTQ8YBFfD9noj

**Comment by gxalpha** [comment]
@Mr-Z-2697 
> I used 30.0.0-beta3 for 5 days now and it haven't crashed until now.

Is this still the case? Did you observe any beta 3 crashes since?

**Comment by Mr-Z-2697** [comment]
> @Mr-Z-2697
> 
> > I used 30.0.0-beta3 for 5 days now and it haven't crashed until now.
> 
> Is this still the case? Did you observe any beta 3 crashes since?

Yes, it crashed several times, quite a few actually.

**Comment by notr1ch** [comment]
This was fixed in #9586.
