### ISSUE TITLE
AMF encoder on linux fails to correctly record during streaming

### ISSUE THREAD

**Issue by ToRRent1812** [obsproject/obs-studio#9604]
### Operating System Info

Other

### Other OS

Nobara KDE (Based of Fedora 38)

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/N1I2FOfQSZ4bgiw8

### Expected Behavior

Having functional recordings

### Current Behavior

Whenever I use AMF encoder for recording, and I stream and record at the same time. Recordings are looking washed out, like some frames are stuck inside video. 
It doesn't matter is it H264 or H265, is obs running in x11, wayland or xwayland
Example: https://www.youtube.com/watch?v=J6813Bv_fto

### Steps to Reproduce

1. Launch obs
2. Set Recording encoder to AMF
3. Stream and record at the same time
4. Check recordings

**Comment by tytan652** [comment]
This feature is not provide by OBS Studio but by Nobara through a patch.

Pleas request support to Nobara.
