### ISSUE TITLE
30.0.0 beta 3 SEGV on start with MacOS 12.6.6 & old profile from 29.x

### ISSUE THREAD

**Issue by risacher** [obsproject/obs-studio#9606]
### Operating System Info

macOS 12

### OBS Studio Version

Other

### OBS Studio Version (Other)

3.0.0-beta3

### OBS Studio Log URL

https://obsproject.com/logs/AnbXRkDC55v0Ztib

### Expected Behavior

OBS should run - or at least not segfault.

### Current Behavior

Segfault on program start. 

### Steps to Reproduce

1. Run obs studio 30.0.0 beta 3 (with my profile from 29.1.2 still around)
2. Wait for it to crash.
3.
...

### Anything else we should know?

It's a beta, I get that.  Just thought y'all should know 30.0.0 beta 3 is SEGV on start for MacOS.  If I delete ${HOME}/Library/Application Support/obs-studio/, then it starts okay, but all my previously configured scenes are obviously gone.  Possibly OBS should nuke the old profile, or offer to do so?

Feel free to close this issue if you don't feel it's worth addressing.

**Comment by gxalpha** [comment]
Please attach a crash log. Also, do you still have the old scenes/profiles?

**Comment by benstegink** [comment]
I have a similar issue in that two of my 29.x.x scenes crash when switching to them in OBS 3 beta 3. my other 2 scenes work just fine. 

[2023-09-20 20-52-42.txt](https://github.com/obsproject/obs-studio/files/12678863/2023-09-20.20-52-42.txt)

**Comment by gxalpha** [comment]
@benstegink that looks useful, please also attach a crash log.
My first hunch in this situation would be third-party plugins, in particular the Stream Deck plugin. Try if removing those fixes the crash.

If it does not, it would be useful to also attach the scene collection json files of both a working and a broken collection, however keep in mind this would include full paths of any files you set in your scene collection. If you’re uncomfortable sharing that publicly but would be okay doing so privately, feel free to ping me on our [Discord server](http://obsproject.com/discord) (Sebastian | gxalpha).

**Comment by benstegink** [comment]
@gxalpha here is the additional information. The crash log is the one that goes along with the log file I uploaded above. I also tried removing all the plugins (as well as running in safe mode) and it still crashes. I also experienced the same behavior on two different machines (both macOS) but one running the Sonora beta and one running Ventura.

- Training: One of my Working Scene
[Training.txt](https://github.com/obsproject/obs-studio/files/12683802/Training.txt)
- MS Cloud IT Pro Podcast: Working Scene
[MS_Cloud_IT_Pro_Podcast.txt](https://github.com/obsproject/obs-studio/files/12683805/MS_Cloud_IT_Pro_Podcast.txt)
- Intelligink: Scene that crashes
[Intelligink.txt](https://github.com/obsproject/obs-studio/files/12683815/Intelligink.txt)

[OBS-2023-09-20-205248.txt](https://github.com/obsproject/obs-studio/files/12683756/OBS-2023-09-20-205248.txt)

Thanks and let me know if anything else would be helpful!

**Comment by gxalpha** [comment]
Thank you! I will investigate.

**Comment by risacher** [comment]
[Untitled.json.txt](https://github.com/obsproject/obs-studio/files/12689227/Untitled.json.txt)

Attached is the scene definition that caused my crash. "~/Library/Application Support/obs-studio/basic/scenes/Untitled.json". 

Forgive my ignorance, where would I find the crashlog?  I don't see anything in obs-studio/logs/ other than the regular log that I already uploaded and linked above.

**Comment by risacher** [comment]
[log-that-breaks.txt](https://github.com/obsproject/obs-studio/files/12689493/log-that-breaks.txt)
[log-okay.txt](https://github.com/obsproject/obs-studio/files/12689500/log-okay.txt)
There don't seem to be any 3rd party plugins that loaded in the old profile which breaks that aren't in the recreated one that works (I did add a 3rd party plugin "freeze-filter" to the new scenes that are okay.)
