### ISSUE TITLE
Crash when stopping WebM recording

### ISSUE THREAD

**Issue by szmarczak** [obsproject/obs-studio#9610]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/64p94XkCRRjhJYzU

### OBS Studio Crash Log URL

https://obsproject.com/logs/0oM93uBUUp4rXUrx

### Expected Behavior

No crash to happen.

### Current Behavior

Crash.

### Steps to Reproduce

Record WebM with default settings, make sure the video is at least 20 seconds long.

**Comment by szmarczak** [comment]
Same thing happens with 30.0 Beta 3: https://obsproject.com/logs/zYgOav3NKJdHzNlo

**Comment by gxalpha** [comment]
> Record WebM with default settings

To clarify, are you using "Custom Output (FFmpeg)" to do this?

**Comment by szmarczak** [comment]
Correct.

**Comment by gxalpha** [comment]
Custom Output (FFmpeg) is very much not default settings and we generally consider it to be unsupported.
