### ISSUE TITLE
(OBS 30.0.0-beta3) QSV crashes OBS

### ISSUE THREAD

**Issue by maginhart** [obsproject/obs-studio#9611]
### Operating System Info

Windows 11

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.0.0-beta3

### OBS Studio Log URL

https://obsproject.com/logs/J7tEszLSxTkcgswc

### OBS Studio Crash Log URL

https://obsproject.com/logs/xjjyUQiHEcOLD5b0

### Expected Behavior

Encoder shouldn't crash obs.

### Current Behavior

OBS crashes when you stop recording while running stream.

### Steps to Reproduce

1.Select qsv as encoder both on streaming and recording tab
2. Start streaming
3. Start recording
4. Stop recording
5. Crash!
...

### Anything else we should know?

This issue started with OBS 30.0 beta-3
**OBS 30.0 beta-2** works without issues no crashes.

**Comment by flaeri** [comment]
I don't know what the correct fix is, but I can confirm that gating the close/release behind the g_numEncodersOpen solves it.

Introduced in: 75e9eb48c657fc386ab4b2ccd37672a16b74691a0923799778b4673021ec752b

```cpp
if ((m_bUseTexAlloc) && (g_numEncodersOpen <= 0)) {
	g_DX_Handle = NULL;
	Release();
}
MFXVideoENCODE_Close(m_session);
return sts;
```
Works for me. Tested with and without gpu tex.

**Comment by Lordmau5** [comment]
> I don't know what the correct fix is, but I can confirm that gating the close/release behind the g_numEncodersOpen solves it.
> 
> Introduced in: #9510
> 
> ```c++
> if ((m_bUseTexAlloc) && (g_numEncodersOpen <= 0)) {
> 	g_DX_Handle = NULL;
> 	Release();
> }
> MFXVideoENCODE_Close(m_session);
> return sts;
> ```
> 
> Works for me. Tested with and without gpu tex.

Perhaps the fix would be to do something like this?
```cpp
if (m_bUseTexAlloc) {
	g_DX_Handle = NULL;
}

if (g_numEncodersOpen <= 0) {
	Release();
}
MFXVideoENCODE_Close(m_session);
return sts;
```

Though I am not sure what the `DX_Handle` is used for
