### ISSUE TITLE
Python script crashes when closing OBS

### ISSUE THREAD

**Issue by ysnist** [obsproject/obs-studio#9613]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.0-beta2

### OBS Studio Log URL

https://obsproject.com/logs/OF7lVSsShFG3GvO7

### Expected Behavior

Any api access needs to be left correct

### Current Behavior

It's just really sad that such a simple script can cause a crash when **closing** obs. I also could not find any way to prevent this.

```
import obspython as obs

def script_description():
    return "My Script"

def test():
    print(obs.obs_frontend_get_current_scene())

def script_update(settings):
    obs.timer_add(test, 1000)
```

### Steps to Reproduce

Add this script to any python version and then close obs

**Comment by Penwy** [comment]
As per the documentation of `obs_frontend_get_current_scene`
"A new reference to the currently active scene. **Release with obs_source_release().**"

It is quite expected behaviour that issues will happen if you do not properly release what needs to be released.

**Comment by WizardCM** [comment]
Please use the API as documented. Currently the scripting API is not built to auto-release references.
