### ISSUE TITLE
(30.0.0 beta3) May be a lack of the first 50 video/audio RTP packets when conducting WHIP streaming

### ISSUE THREAD

**Issue by MarcoMayCry** [obsproject/obs-studio#9614]
### Operating System Info

macOS 13

### Other OS

Windows11

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.0.0 beta3

### OBS Studio Log URL

https://obsproject.com/logs/6tFFezGfhxSWSq1b

### Expected Behavior

In OBS versions 30.0.0 beta2 and earlier, the sequence numbers of audio/video RTP packets for WHIP streaming start from 0, and the first video frame is an I-frame with SPS and PPS to initialize the decoder. After clicking the start streaming button, the server can immediately receive a decodable video stream.

The following image shows a Wireshark capture, where PT 96 represents video. It can be observed that the RTP packets start from sequence number 0.
<img width="725" alt="image" src="https://github.com/obsproject/obs-studio/assets/79976248/df0f4def-9735-4440-83ec-3f6447db4668">

### Current Behavior

However, after updating to version 30.0.0 beta3 on macOS 13/Windows 11, when I click the start streaming button, OBS occasionally fails to send the first 40-50 RTP packets, mostly video packets but also some audio packets. This results in the first GOP data being unable to be decoded, and we have to wait for the next I-frame.

The following image shows a Wireshark capture, where PT 96 represents video and PT 111 represents audio. It can be observed that the video is missing sequence numbers 0-52, while the audio is missing sequence number 0-1.
<img width="739" alt="image" src="https://github.com/obsproject/obs-studio/assets/79976248/177521b2-29aa-4be3-9440-2eb8100d8ac8">

This issue is not consistent, but it has been observed that there is a high probability of it occurring during multiple streaming attempts on macOS 13 and Windows 11.

### Steps to Reproduce

1. Use OBS 30.0.0 beta3
2. Streaming using WHIP.
3. Capturing packets using Wireshark.

**Comment by gxalpha** [comment]
CC @Sean-Der, is this a valid issue and/or what are the necessary steps here?

**Comment by MarcoMayCry** [comment]
Currently, I haven't found any other necessary steps. I accidentally discovered it during multiple identical streaming steps, and I'm not sure if it was triggered by some operation.

**Comment by MarcoMayCry** [comment]
Currently, I haven't found any other necessary steps. I accidentally discovered it during multiple identical streaming steps, and I'm not sure if it was triggered by some operation.

**Comment by Sean-Der** [comment]
@MarcoMayCry Does this happen if you lower the bitrate/resolution?

You are experiencing some sort of congestion collapse. libdatachannel doesn't have any built in packet pacing, I would like to go fix that soon.

**Comment by MarcoMayCry** [comment]
@Sean-Der 
So far, I haven't found a definite connection between this issue and the bitrate/resolution. It has occurred in both 2Mbps and 4Mbps live streams.
Recently, in addition to my own computer, I have observed this issue among some of our online users that we serve.

**Comment by MarcoMayCry** [comment]
@Sean-Der 
In addition, may I ask if the WHIP push stream will not actively perform frame dropping when there is weak network (packet loss)? This usually happens in RTMP push streaming. Please refer to the following picture, which shows the frame dropped of RTMP pushing and WHIP pushing when 10% packet loss is set.

RTMP：
<img width="353" alt="image" src="https://github.com/obsproject/obs-studio/assets/79976248/17d51e1d-89bf-44d4-8797-166016709086">

WHIP:
<img width="330" alt="image" src="https://github.com/obsproject/obs-studio/assets/79976248/c477bb54-c3ee-4e8a-a073-8f3650b95a77">

**Comment by Sean-Der** [comment]
I think we can resolve this one! I have tried a few different times/ways to reproduce this and haven't seen it myself. Have you seen this recently @MarcoMayCry ?

![2024-04-27-204630_611x980_scrot](https://github.com/obsproject/obs-studio/assets/1302304/b6bef27a-509a-4b8a-941b-ae1662dfddd5)

**Comment by Fenrirthviti** [comment]
Closing as reproduction steps are not specific enough. If we can get more information on how this is encountered, we can reopen later.

**Comment by MarcoMayCry** [comment]
> I think we can resolve this one! I have tried a few different times/ways to reproduce this and haven't seen it myself. Have you seen this recently @MarcoMayCry ?
> 
> ![2024-04-27-204630_611x980_scrot](https://private-user-images.githubusercontent.com/1302304/326221235-b6bef27a-509a-4b8a-941b-ae1662dfddd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzOTY1NzQsIm5iZiI6MTcxNDM5NjI3NCwicGF0aCI6Ii8xMzAyMzA0LzMyNjIyMTIzNS1iNmJlZjI3YS01MDlhLTRiOGEtOTQxYi1hZTE2NjJkZmRkZDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjlUMTMxMTE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmJhZDgzYzdlOWZlNmZjMTQ3MzBlMmUxOGE5MTg4NTk1MzM4ZmQzNTAxMTNiOTEyMjQyNWFiZGFhMTAxNGFjMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mAL1HkHP8LM_a9XB7EL_9hghJ2SuUz7btf9EkJURZbU)

I haven't encountered this situation recently. According to last year's records, this problem couldn't be reproduced through fixed steps, it seemed to occur probabilistically. Thanks for all your replies. If I can reproduce this issue in the future, I will provide more information.

**Comment by MarcoMayCry** [comment]
> Closing as reproduction steps are not specific enough. If we can get more information on how this is encountered, we can reopen later.

Okay, thanks
