### ISSUE TITLE
OBS Studio Crashes on Arch Linux after selecting screen (pipewire)

### ISSUE THREAD

**Issue by mylinux4work** [obsproject/obs-studio#9617]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/WKUljs7PfSQdNJ9W

### Expected Behavior

Full screen recording on selected monitor.

### Current Behavior

Crashes immediately after selecting a screen with pipewire on Hyprland/Wayland.

### Steps to Reproduce

1. Open OBS Studio
2. Add pipewire as a source
3. Select a screen
4. Crash
...

### Anything else we should know?

Worked everything before the current full Arch Linux update. Maybe something in combination of OBS Studio and pipewire?
Using Hyprland on Wayland with pipewire 0.3.80

**Comment by kkartaltepe** [comment]
Please provide a backtrace from gdb

**Comment by mylinux4work** [comment]
Sorry, but how to get this backtrace?

**Comment by kkartaltepe** [comment]
To make a backtrace with gdb. Open a terminal and run `gdb obs`, if it asks `Enable debuginfod for this session?` you can enter `y` if you have good internet and want to provide more info. Then you will be at a prompt where you can start obs by  entering `run`.

Trigger the crash in obs and then then go back to the terminal and you should have the prompt again. You can now get the backtrace by entering `bt` at the prompt. Copy the entire output here.

**Comment by NudeRat** [comment]
Here's mine:

```
#0  0x0000000000000000 in  ()
#1  0x00007fffa9b2e30c in swap_texture_red_blue (texture=<optimized out>) at /usr/src/debug/obs-studio/obs-studio-29.1.3/plugins/linux-pipewire/pipewire.c:322
#2  0x00007fffa9b2ebe3 in on_process_cb (user_data=0x5555580150a0) at /usr/src/debug/obs-studio/obs-studio-29.1.3/plugins/linux-pipewire/pipewire.c:688
#3  0x00007fffa9c13a28 in do_call_process (loop=<optimized out>, async=<optimized out>, seq=<optimized out>, data=<optimized out>, size=<optimized out>, user_data=0x555557f98350)
    at ../pipewire/src/pipewire/stream.c:452
#4  do_call_process (loop=<optimized out>, async=<optimized out>, seq=<optimized out>, data=<optimized out>, size=<optimized out>, user_data=0x555557f98350)
    at ../pipewire/src/pipewire/stream.c:445
#5  0x00007fffa9b788e1 in flush_items (impl=0x555557f7c4a8) at ../pipewire/spa/plugins/support/loop.c:171
#6  0x00007fffa9b77a09 in source_event_func (source=0x555557f68fc0) at ../pipewire/spa/plugins/support/loop.c:650
#7  0x00007fffa9b795b6 in loop_iterate (object=0x555557f7c4a8, timeout=<optimized out>) at ../pipewire/spa/plugins/support/loop.c:483
#8  0x00007fffa9c1e00d in do_loop (user_data=0x555556307e40) at ../pipewire/src/pipewire/thread-loop.c:295
#9  0x00007ffff3c8c9eb in start_thread (arg=<optimized out>) at pthread_create.c:444
#10 0x00007ffff3d10dfc in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```

**Comment by kkartaltepe** [comment]
This one should be fixed in #8993 try using the beta via the ppa or flatpak.

**Comment by jonhoo** [comment]
I'm using a build of Git HEAD (also on Arch), and am seeing what appears to be nearly the same crash:
```
(lldb) bt
* thread #28, name = 'PipeWire thread', stop reason = signal SIGSEGV: invalid address (fault address: 0x30)
  * frame #0: 0x00007fffc7e3e8ec linux-pipewire.so`renegotiate_format(data=0x0000555557a102e0, expirations=<unavailable>) at pipewire.c:631:2
    frame #1: 0x00007fffbffe4cc9 libspa-support.so`source_event_func(source=0x00005555574dcc60) at loop.c:663:2
    frame #2: 0x00007fffbffe6666 libspa-support.so`loop_iterate(object=0x00005555574af308, timeout=<unavailable>) at loop.c:496:4
    frame #3: 0x00007fff88cda14d libpipewire-0.3.so.0`do_loop(user_data=0x0000555557315260) at thread-loop.c:295:14
    frame #4: 0x00007ffff3eaa9eb libc.so.6`start_thread(arg=<unavailable>) at pthread_create.c:444:8
    frame #5: 0x00007ffff3f2e7cc libc.so.6`__clone3 at clone3.S:78
```
The crash happens after the second time I select the screen (I'm not sure why, but OBS always asks me twice for which screen to use on start-up).

I'm running:
- obs-studio @ b29a44a67db76c6f665bcc0887730d689e6b908d
- pipewire: 0.3.82
- hyprland: 0.30.0
- xdg-desktop-portal-hyprland: 1.2.2

on Arch Linux

**Comment by kkartaltepe** [comment]
This looks like a different crash, please open a new issue with this content.

**Comment by jonhoo** [comment]
Filed https://github.com/obsproject/obs-studio/issues/9733
