### ISSUE TITLE
[Bug] OBS doesn't always recognize it is Streaming to Twitch

### ISSUE THREAD

**Issue by Ryu945** [obsproject/obs-studio#9619]
### Operating System Info

Other

### Other OS

Nobara 38

### OBS Studio Version

29.1.3

### OBS Studio Version (Other)

RPM version

### OBS Studio Log URL

It seems my OBS logs from yesturday are deleted so I will have to generate some new ones today.

### Expected Behavior

When You click to stream a video, it starts and the client recognizes it.

### Current Behavior

Some percentage of the time, OBS does not recognize that it has started a successful stream to Twitch.  It throw an error [forgot the exact message] that basically says failed to connect/stream to Twitch.  This is a mistake on OBS' part.  If you actually look on Twitch, your see that it has successfully streamed to Twitch.  OBS will actually continue to stream to Twitch even though it is giving no indication that it is streaming.  This continues until you close the application.  I usually get around this bug by stopping OBS, restarting OBS and restarting the stream over and over again until it doesn't fail.  Sometimes it streams right away with no issues. Sometimes I have tried five times and I am stilling failing to get OBS to recognize it successfully started a stream.

### Steps to Reproduce

1. Open OBS
2. Stream to Twitch
3. Some percentage of the time, it will say it failed.
4.
5.
...

### Anything else we should know?

RPM version of OBS

**Comment by Fenrirthviti** [comment]
I am not currently seeing how this could be a bug in OBS, as no log file, description of the error, screenshot of the error, etc. is provided here. This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by Ryu945** [comment]
The end of the log should show you the error OBS threw

**Comment by Ryu945** [comment]
> I am not currently seeing how this could be a bug in OBS, as no log file, description of the error, screenshot of the error, etc. is provided here. This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.
> 
> Thank you!

Since OBS only keeps logs for a day, I had to get it to regenerate a new log.   You can look at the logs attached.

**Comment by Fenrirthviti** [comment]
OBS stores the last 20 logs indefinitely by default. Any rotation is your own system configuration.

**Comment by Fenrirthviti** [comment]
Additionally, there is no attempt to stream in the log file, which still puts this back towards support. I'd recommend the forums or Discord for someone to be able to take a closer look.

**Comment by Ryu945** [comment]
> Additionally, there is no attempt to stream in the log file, which still puts this back towards support. I'd recommend the forums or Discord for someone to be able to take a closer look.

I attached some more logs of this same bug hoping it will help.   It is not possible to get support from the Discord so I will try the forums.
