### ISSUE TITLE
webm - libvpx-vp9 crash when stop recording

### ISSUE THREAD

**Issue by nurdism** [obsproject/obs-studio#9625]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.0-beta2

### OBS Studio Log URL

https://obsproject.com/logs/COFXYwawZQRBPhhH

### OBS Studio Crash Log URL

https://obsproject.com/logs/vCNMVlkkIqKvCZ17

### Expected Behavior

OBS to not crash to desktop

### Current Behavior

The video does seem to save correctly but OBS will crash to desktop

### Steps to Reproduce

1. set these settings: 
  - ![image](https://github.com/obsproject/obs-studio/assets/420102/44a96e80-bdec-4bd4-bc85-d820734751d9)
  - ![image](https://github.com/obsproject/obs-studio/assets/420102/2268522b-ee4a-4547-8954-1ab10bbf2c5c)
  - Under "Advanced" > Video ![image](https://github.com/obsproject/obs-studio/assets/420102/20988055-83b1-4c14-99a8-e73513880f49)

2. record video > 5 seconds
3. stop recording 
...

**Comment by nurdism** [comment]
note: messing with video encoder settings, I was using the wrong format `deadline=realtime cpu-used=8 crf=30` seems to do ok and doesn't crash sometimes.

**Comment by RytoEX** [comment]
I can record to webm with default settings without crashing just fine.

"Video Encoder Settings" must be provided as a space-delimited list of options:
```
opt1-name=opt1-value opt2-name=opt2-value opt3-name=opt3-value
```

All of that said, Custom Output (FFmpeg) is essentially provided as-is with no guarantees. We pass the configured values to FFmpeg libraries and if it works, it works.
