### ISSUE TITLE
Window capture has limited functionality on Wayland (Pipewire)

### ISSUE THREAD

**Issue by TriVoxel** [obsproject/obs-studio#9630]
### Operating System Info

Other

### Other OS

Fedora 38

### OBS Studio Version

29.1.3

### OBS Studio Log URL

N/A

### Expected Behavior

This is not *necessarily* a bug, but represents a massive loss of core functionality which can be felt by streamers trying to use Pipewire window (or screen) capture on the Wayland window manager for advanced gaming setups.

My friend is a streamer trying to use Linux for game streaming. His usual setup on Windows and older versions of Linux running X11 would be to create a `capture` scene. In this scene, he would launch a Steam game, add a window capture source, and then rinse and repeat for each game he planned on streaming. This way, OBS would automatically display a game feed, which is less problematic than a screen capture, and the game would automatically be picked up based on some attribute, maybe executable path or Window title. This allowed him to leave a scene with pre-cropped clips for each of the many games he regularly streamed, and allowed him to quickly switch games with ease.

### Current Behavior

On Wayland, the only option is Pipewire window and screen capture. This method is severely limited. Each time the window or OBS is closed, the source requires a new permission from Pipewire to capture the source, and on top of that, it doesn't even remember the source window or screen. This means that OBS on Wayland has no way of automatically loading game windows. A streamer that wants to switch games, using Pipewire, would need to manually select a window or desktop every time they want to change sources.

### Steps to Reproduce

1. Add window capture for a window
2. Close the Window
3. Re-open the window, no source

### Anything else we should know?

Wayland really needs a game capture at the very least that can identify games, or a way to recognize windows by binary or at the very least a name match, so that they can automatically be picked up. I'm not too technical with how Pipewire works, this could be impossible currently, but Pipewire is very bad for streaming.

**Comment by tytan652** [comment]
This sounds more likely to be a feature request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [Fider](https://ideas.obsproject.com/) or [Discord](https://obsproject.com/discord/).

Thank you!

**Comment by Fenrirthviti** [comment]
> This is a bad idea for performance and reliability reasons, as each source is constantly checking for whether the window exists yet. A scene should contain **one** Game Capture source. There is a hotkey mode that can be used with any game to explicitly capture the open game in this scenario.

Just as a note here, I assume WizardCM missed that this is a Linux host, where there is (currently) no Game Capture source available.

**Comment by TriVoxel** [comment]
> > In this scene, he would launch a Steam game, add a window capture source, and then rinse and repeat for each game he planned on streaming.
> 
> This is a bad idea for performance and reliability reasons, as each source is constantly checking for whether the window exists yet. A scene should contain **one** Game Capture source. There is a hotkey mode that can be used with any game to explicitly capture the open game in this scenario.

To be completely honest, I think this is a totally ridiculous setup as well, and I tried to explain an alternative setup to my friend. However, I want to point out that there is no "Game capture" on Wayland, and maybe not on Linux in general? I really hope this is a planned feature. At any rate, this change does bring about legitimate workflow degredations imo, but I digress.
