### ISSUE TITLE
Video files are not playing in studio mode if switch scene

### ISSUE THREAD

**Issue by avoitenko-logitech** [obsproject/obs-studio#9633]
### Operating System Info

Windows 10

### Other OS

Linux, MacOS

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/CmBKjZ1yoIQ7Ssdk

### Expected Behavior

Video files are playing when selecting scene with video file source in studio mode.

### Current Behavior

Video files are not playing when selecting scene with video file source in studio mode.

### Steps to Reproduce

1. Create 2 scenes. One with camera and one with media file source
2. Select scene with camera
3. Enter studio mode
4. Select scene with media file source
5. Observe `Preview` part of studio mode window

Here is the link with video of reproduction: https://www.youtube.com/watch?v=-vPmgmpbK2A

### Anything else we should know?

Note: this issue is not happening when option `Restart playback when source becomes active` is unchecked.

I investigated this a bit and the issue is related to video file source activation state when we observe other scenes in studio mode.
Video is not playing because source is not active. Currently the only legal way to activate items is to switch current scene via `obs_set_output_source`, but this call will have side effects and is not meant to be done in studio mode.

Other option which is worked for me was exposing internal `obs_source_activate` and `obs_source_activate` to public API and calling them from UI. But this approach seems to be a little hackish and requires extra care.

**Comment by Fenrirthviti** [comment]
This is not a bug, and expected behavior for studio mode. Sources are only considered active in the output/program.

Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for further assistance.

Thank you!
