### ISSUE TITLE
Show/hide hotkeys for separate sceneitems of the same source on the same scene get merged after restart

### ISSUE THREAD

**Issue by Penwy** [obsproject/obs-studio#9639]
### Operating System Info

Ubuntu 22.04

### Other OS

Also windows 10

### OBS Studio Version

30.0.0-beta2

### OBS Studio Version (Other)

Also confirmed on 29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/uV7ol09LN88KVeEj

### Expected Behavior

Hotkeys for separate sceneitems should be saved and loaded separately.

### Current Behavior

Upon restart all sceneitems of the same source on the same scene get the same show/hide hotkeys regardless of what was assigned to them.

### Steps to Reproduce

1. Create a scene with two or more sceneitems of the same source.
2. In Settings > Hotkeys, assign different show/hide hotkeys to each.
3. Restart OBS.
4. Notice the hotkeys are now the same for each.
...

### Anything else we should know?

Log is from a 30.0 beta session because it was easier for me to provide, but behaviour is similar on 29.1.3.

**Comment by derrod** [comment]
I get the feeling this may have been my fault... Will have to investigate later.

**Comment by derrod** [comment]
Confirmed this bug also exists in 27.1.3, so unrelated to the hash table refactorings.
