### ISSUE TITLE
Staters in recording and preview or broadcast.

### ISSUE THREAD

**Issue by Adega-Studio** [obsproject/obs-studio#9645]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/27NloqOqbVIbuBOm

### Expected Behavior

I expect the same smooth recording as I see on the motor.

### Current Behavior

Staters in recording and preview or broadcast with any settings and using any capture method.
Clean Windows 10, new Nvidia driver, set to 60Hz everywhere. I recorded a video demonstrating the problem in which there is an OBS with a jerky preview.
Here is a video where you can clearly see the problem at 6:40 timing and the OBS itself with a preview at 7:20 https://youtu.be/YOYhmuY543Y https://drive.google.com/file/d/1dsiBD4zhfmZDzq_-NktE_MnvnhJ3CcCj/view?usp =drive_link
Over the years, everything has been tried, but the problem remains in any version of the program.
Below I will attach a link to one working version of OBC which was specially made by jpark37 https://github.com/jpark37 and in it screen capture in DXGI mode works perfectly. I’ll attach a link to the OBS from jpark37 (although there are plugins I installed for it to work). https://drive.google.com/file/d/1_7JQ4g5ytLg6uu6RQKpb0jucIiroLM8M/view?usp=drive_link
I hope this problem will be resolved once and for all and the topic will not be closed for various reasons!

### Steps to Reproduce

1.Record at 60fps on a 60fps monitor Website for smoothness test https://www.testufo.com/stutter#demo=smooth&foreground=ffffff&background=000000&pps=720
2.Recording time from 10 min to 40 min
3.Any version of obs
...

**Comment by WizardCM** [comment]
This sounds more likely to be a support issue than a bug. Please submit this through one of our support channels below, and if it's determined that this is indeed a bug, then we will re-open this issue.

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum). For more info, check our [Help page](https://obsproject.com/help).

**Comment by Adega-Studio** [comment]
> Это скорее проблема поддержки, чем ошибка. Пожалуйста, отправьте это через один из наших каналов поддержки, указанных ниже, и если будет установлено, что это действительно ошибка, мы повторно откроем эту проблему.
> 
> Пожалуйста, используйте [сервер Discord](https://obsproject.com/discord) или [форумы](https://obsproject.com/forum) . Для получения дополнительной информации посетите нашу [страницу справки](https://obsproject.com/help) .

I also wrote on the forum. The problem is in the OBS, verified. Some people are tired of writing about it, while others are resigned to it(

**Comment by Fenrirthviti** [comment]
Duplicate of https://github.com/obsproject/obs-studio/issues/4191
