### ISSUE TITLE
Valorant + OBS when HAGS and reflex on + boost

### ISSUE THREAD

**Issue by physbyte** [obsproject/obs-studio#9651]
### Operating System Info

Windows 11

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.0.0 beta3 and others

### OBS Studio Log URL

https://obsproject.com/logs/hEhVmuPsWO3xYvVk

### Expected Behavior

I expected to see a video encoder loading, not a 3D loading.

### Current Behavior

The load on the “3D” video card increases greatly when reflex+acceleration is enabled, if hacks are enabled in Windows and Valorant is running.
It was also noticed that under the same conditions, the “copy” graph jumps to 100% with a certain periodicity.

### Steps to Reproduce

1. Launch Valorant and turn on reflex + boost then minimize Valorant.
2. Launch OBS and enable video recording.
3. Minimize OBS to the taskbar or notification area (minimizing gives even more load.)
4. Launch the task manager and look in the GPU tab in the 3D chart.

### Anything else we should know?

Disabling HAGS in windows or disabling reflex on + boost solves the problem.

Yes, I saw messages about hags in the log analyzer, but perhaps my research will somehow help you.

https://imgur.com/a/4EHBMIq

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
