### ISSUE TITLE
screen color not correct

### ISSUE THREAD

**Issue by glepnir** [obsproject/obs-studio#9659]
### Operating System Info

Other

### Other OS

Arch linux with hyprland

### OBS Studio Version

Git

### OBS Studio Version (Other)

30.0-beta3

### OBS Studio Log URL

https://obsproject.com/logs/ABxKyodx5FatkuM1

### Expected Behavior

color same as screen render

### Current Behavior

![image](https://github.com/obsproject/obs-studio/assets/41671631/25829164-76f1-4194-b3de-411aac6e7486)

### Steps to Reproduce

1. yay -S obs-studio-git
2. yay -S mbedtls2 --if don't install this obs crash
3. select monitor

**Comment by tytan652** [comment]
Duplicates of #9627

**Comment by tytan652** [comment]
> yay -S mbedtls2 --if don't install this obs crash

Rebuild (clean rebuild) against MbedTLS 3

**Comment by glepnir** [comment]
> Rebuild the OBS package (clean rebuild) against MbedTLS 3

`yay -S mbedtls` install three version and obs will popup `create audio stream encoder failed` only `mbedtls2` works

**Comment by glepnir** [comment]
@tytan652  any suggestion on `mbedtls` version ..
