### ISSUE TITLE
Dynamic bitrate not working with AMF

### ISSUE THREAD

**Issue by Johl7** [obsproject/obs-studio#9667]
### Operating System Info

Windows 10

### OBS Studio Version

30.0.0-beta3

### OBS Studio Log URL

https://obsproject.com/logs/qDQmIo76kxo1BvyH

### Expected Behavior

Dynamic bitrate to be functioning as expected

### Current Behavior

The feature fails to activate(ive heard its due to the flag not bein readded properly after the fix)

### Steps to Reproduce

1.Enable dynamic bitrate
2.Click start streaming
3.
...

**Comment by mihawk90** [comment]
Dynamic Bitrate support depends on the card. Yours doesn't support it so it is disabled automatically:

> 11:50:24.570: [rtmp stream: 'adv_stream'] Dynamic bitrate disabled. The encoder does not support on-the-fly bitrate reconfiguration.

**Comment by Johl7** [comment]
Yeah, it was intentionally disabled in for a period o time due to it causing crashes on the encoder, but on the latest releases its suposed to be back on, what happened is that they added the fix but forgot to add back the flag for it(somethin like that), so it isnt working.
