### ISSUE TITLE
Application Audio Capture: Allow for toggling of capturing process tree audio (currently always on)

### ISSUE THREAD

**Issue by Zarithya** [obsproject/obs-studio#9669]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/owBtQIXkg4ulBYCh

### Expected Behavior

When choosing to capture audio from Streamer.bot, I expect to only capture Streamer.bot's audio, not also OBS's audio.

### Current Behavior

I have OBS set to launch from within Streamer.bot when that tool opens. I also want to capture audio from within Streamer.bot using Application Audio Capture. However, this causes any audio that is output by OBS (such as browser sources whose "Control audio via OBS" boxes are ticked) to also come through the Streamer.bot audio source.

### Steps to Reproduce

1. Launch OBS from within Streamer.bot (or similar tool)
2. Use Application Audio Capture to capture Streamer.bot audio
3. Observe OBS monitored audio coming through both expected source and Streamer.bot audio source

### Anything else we should know?

Seemingly this is caused here: https://github.com/obsproject/obs-studio/blob/e11e2133e29dd16d2217c17f9f56ca3824a36f76/plugins/win-wasapi/win-wasapi.cpp#L790C1-L792C54
By using `PROCESS_LOOPBACK_MODE_INCLUDE_TARGET_PROCESS_TREE`, all processes in the target tree (which in my case includes OBS, as it was launched from Streamer.bot) are included in the loopback capture. Either this should be exposed to the user ("Include child processes" tickbox?) or set to exclude by default (though there are probably situations where children would be expected to be captured).

**Comment by gxalpha** [comment]
This sounds like a feature request, which we don't track using GitHub Issues (we use GitHub exclusively for bug reports).
Please put ideas and feature requests on [our ideas page](https://ideas.obsproject.com).

Thank you!
