### ISSUE TITLE
Virtual Camera not Installable on macOS Sonoma 14.0 (30.0.0-rc1)

### ISSUE THREAD

**Issue by vogtadi** [obsproject/obs-studio#9692]
### Operating System Info

macOS 14

### OBS Studio Version

Other

### OBS Studio Version (Other)

OBS Studio 30.0.0-rc1

### OBS Studio Log URL

https://obsproject.com/logs/qt9lUEh7emlsC3MD

### Expected Behavior

Once OBS Starts, clicking the "Start Virtual Camera" button requests admin permissions to install the driver, then the virtual camera is active.

### Current Behavior

the request for admin permissions pops up (correct), then the message "Could not find virtual camera. Please try again." appears.

### Steps to Reproduce

1. Start OBS
2. Click "Start Virtual Camera"
3. Enter Admin Credentials
4. -> Error "Could not find virtual camera. Please try again."

**Comment by gxalpha** [comment]
> Once OBS Starts, clicking the "Start Virtual Camera" button requests admin permissions to install the driver, then the virtual camera is active.

Where does it request this? From the system settings, or within OBS?

**Comment by ikzelf** [comment]
I guess the requests comes from OBS. Any way, the requested privileges are granted as can be seen in the overview:
![image](https://github.com/obsproject/obs-studio/assets/496774/72de9342-3842-4ee9-850e-6069adf6bf25)

**Comment by vogtadi** [comment]
> > Once OBS Starts, clicking the "Start Virtual Camera" button requests admin permissions to install the driver, then the virtual camera is active.
> 
> Where does it request this? From the system settings, or within OBS?

It's the OS Authorization screen (Pops Up in the Center of the main screen) and asks for username and password. It is triggered by OBS (as it needs the rights for the installation), but presented by macOS afak.

System Settings does not show an entry (i.e. also no missing driver rights).

**Comment by vogtadi** [comment]
> I guess the requests comes from OBS. Any way, the requested privileges are granted as can be seen in the overview: ![image](https://user-images.githubusercontent.com/496774/274606665-72de9342-3842-4ee9-850e-6069adf6bf25.png)

It shows all permissions granted (same as yours).

**Comment by vogtadi** [comment]
For whatever reason, I cannot reproduce the problem today. i.e. it DOES run the virtual camera driver of 30.0.0-rc1 after installation.

Not sure, what resolved it. I did NOT reboot the mac since reporting the issue (uptime is 5 days). But I logged of the account I performed the installation.

**Comment by vogtadi** [comment]
For whatever reason, I cannot reproduce the problem today. i.e. it DOES run the virtual camera driver of 30.0.0-rc1 after installation.

Not sure, what resolved it. I did NOT reboot the mac since reporting the issue (uptime is 5 days). But I logged of the account I performed the installation.

**Comment by RytoEX** [comment]
Just to clarify, the Virtual Camera has nothing to do with the Permissions dialog shown above. The Permissions dialog is about OBS having access to those things. The Virtual Camera System Extension needs permission from the user to be installed, for which you get separate prompts.

**Comment by hroland** [comment]
+1 here. I'm on the stable 30.0.0 release.

When opening `/Library/CoreMediaIO/Plug-Ins/DAL`, the plugin file is missing. I get no admin prompts what so ever when attempting to start virtual cam. Permissions all granted too. This last attempt was running OBS in `sudo`.

I tried manually copying `OBS.app/Contents/Resources/obs-mac-virtualcam.plugin` to the `/Plug-Ins/DAL` folder, but when I launched the cam, I got the auth popup, but then the file got deleted, and i got the same _Could not find virtual camera._ popup 😪

![Screenshot 2023-11-13 at 15 41 53](https://github.com/obsproject/obs-studio/assets/12371411/8696d9f6-f61e-485a-81ea-e67a73787862)

**Comment by gxalpha** [comment]
`obs-mac-virtualcam.plugin` is no longer used on macOS 13+, as we're now using CMIO System Extensions there.
If you have the problem on your screenshot, firstly try restarting your Mac after installing the virtual camera.

**Comment by vogtadi** [comment]
Just confirming my earlier observation, that the error "disappears" once, you logout and log back in. 

On all Installations of RC-x and production, I had the issue, that directly after the upgrade inside the current session, the error pops up. Once logged out and back in, the virtual camera works as expected. Restarting the mac was not required.

Kind Regards
Adrian

**Comment by kir3d** [comment]
> `obs-mac-virtualcam.plugin` is no longer used on macOS 13+, as we're now using CMIO System Extensions there. If you have the problem on your screenshot, firstly try restarting your Mac after installing the virtual camera.

Macbook M2 Pro / Macos 13.6.5
OBS 30.1.2 for Apple Silicon
All permissions for OBS granted

from Python/Virtualcam/OpenCV can't send to virtualcam:
`RuntimeError: 'obs' backend: OBS Virtual Camera is not installed in your system. Use the Virtual Camera function in OBS to trigger installation.`

on Windows 11 some code works.

**Comment by gxalpha** [comment]
This is not an OBS issue. See https://github.com/letmaik/pyvirtualcam/issues/111.

**Comment by kir3d** [comment]
> This is not an OBS issue. See [letmaik/pyvirtualcam#111](https://github.com/letmaik/pyvirtualcam/issues/111).
tried upgrade to Macos 14.4.1 and execute system-override in repair mode - doesn't help :(

**Comment by gxalpha** [comment]
Again, none of that has anything to do with OBS. Please take that support question to pyvirtualcam.
