### ISSUE TITLE
webcam resolution remains at 1920*1081 ignoring settings

### ISSUE THREAD

**Issue by ikzelf** [obsproject/obs-studio#9700]
### Operating System Info

macOS 14

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.0.0-beta3

### OBS Studio Log URL

https://obsproject.com/logs/QEuzQ5bggJKBPkQ4

### Expected Behavior

I expected to be able to see a resolution conform the settings in OBS.
[https://webcamtests.com](https://webcamtests.com) keeps telling me the resolution is 1920*1081.
Since 30.0.0-beta3 was for me the first try of obs studio I can not tell how this was in earlier versions

### Current Behavior

[https://webcamtests.com](https://webcamtests.com) keeps telling me the resolution is 1920*1081.
![image](https://github.com/obsproject/obs-studio/assets/496774/5d6abe72-16b1-4a3b-898a-6a7b2b71c088)

### Steps to Reproduce

1) on macOS Sonoma on Apple silicon (M2) run OBS-30.0.0-beta3 (but not RC1 since there the virtual cam will not start at all)
2) start the virtual camera and change the resolution
3) test on [https://webcamtests.com](https://webcamtests.com)

### Anything else we should know?

from comments in the discord beta channel I understood it does work on intel macs.

**Comment by ikzelf** [comment]
just tested with obs-30.0.0-rc1:
![image](https://github.com/obsproject/obs-studio/assets/496774/a48fd991-9b46-437a-a180-b05798962a60)
The resolution changed a bit from 1920x1081 to 1920x1080 but still not the resolution I choose.

**Comment by gxalpha** [comment]
Webcamtest is wrong. I can reproduce it with Webcamtest as well, but other sites (e.g. https://www.onlinemictest.com/de/webcam-testen), as well as OBS, show the correct resolution.

**Comment by ikzelf** [comment]
![image](https://github.com/obsproject/obs-studio/assets/496774/c5dff2b2-1dbe-44ed-8eee-5ea0f42eee82)
I have no idea which site is right or wrong but both show an other resolution as OBS studio shows.
In this case https://www.onlinemictest.com/de/webcam-testen/ shows 
`Webcamnaam: OBS Virtual Camera
Frame rate: 60 FPS
Webcamresolutie: 556x401`
it also shows 60FPS where obs shows 30.
obs shows as resolution: 768x432

**Comment by Fenrirthviti** [comment]
Is there a practical issue here, or is this just a number on a website? If the website is displaying something incorrect, but it's not actually affecting anything, this isn't really worth the time to investigate further.

If someone can provide an actual, practical use case in their workflow that this is affecting, I'd be happy to reopen and investigate.

**Comment by ikzelf** [comment]
If recording the webcam in obs, saving the result and inspecting it with QuickTime Player shows the correct resolution, that an app like jitsi receives, it is ok. In that case obs is correct.
