### ISSUE TITLE
OBS Studio freezes after 20-30 seconds

### ISSUE THREAD

**Issue by jrossstocholm** [obsproject/obs-studio#9701]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/WVNh8CrCBvMufhBn

### Expected Behavior

I have just installed OBS Studio on Windows 11 (I am on the Windows Insider Canary track). I have installed the "background removal plugin). I am using OBS for recording only.

I would expect to be able to record for more than 20-30 seconds before it OBS freezes.

### Current Behavior

When I start recording, after 20-30 seconds OBS freezes and I have no other option than to force stop the program.

### Steps to Reproduce

1. Start recording
2. After 20-30 seconds OBS freezes.
3.
...

### Anything else we should know?

At no point in time does my PC seem to be overloaded. CPU load is below 30% and memory consumption is below 50%. I am using two 24 screens. I could not upload a crash file since the folder is empty. Settings are all more or less default. I am using 2800 kbs output settings, medium file size and MKV as output format

Update: I looked at the log file and could see that it showed me as running OBS not as admin (which was true). I have run OBS again as admin and uploaded the log file here: https://obsproject.com/logs/NI5nP7b0EP61NPMq .

**Comment by jrossstocholm** [comment]
@RytoEX I have uninstalled the plugin and done another couple of tests. It still freezes - but now it shows and error message first.

Log file is here:

https://obsproject.com/logs/BtAxIxuDbnlqFqlq

Error message is here:

![image](https://github.com/obsproject/obs-studio/assets/683942/f26ee96f-230c-46bc-8c43-7ed8d56267bb)

**Comment by RytoEX** [comment]
The encoder error is likely the encoder failing. Since you are using a hardware encoder, you should ensure that your GPU drivers are up to date.

This almost sounds like the GPU is locking up and then killing the encoder session.

That said, we do not provide support for Windows Insider Preview Builds due to their unpredictable nature, and we have heavily rewritten the QSV plugin for OBS Studio 30. I would be interested in seeing if this is resolved in one of these scenarios:
* Windows 11 stable, OBS 29.1.3, updated GPU drivers
* Windows 11 stable, OBS 30.0.0-rc1 (or newer), updated GPU drivers

**Comment by jrossstocholm** [comment]
> The encoder error is likely the encoder failing. Since you are using a hardware encoder, you should ensure that your GPU drivers are up to date.
> 
> This almost sounds like the GPU is locking up and then killing the encoder session.
> 
> That said, we do not provide support for Windows Insider Preview Builds due to their unpredictable nature, and we have heavily rewritten the QSV plugin for OBS Studio 30. I would be interested in seeing if this is resolved in one of these scenarios:
> 
>     * Windows 11 stable, OBS 29.1.3, updated GPU drivers
> 
>     * Windows 11 stable, OBS 30.0.0-rc1 (or newer), updated GPU drivers

I know that you don't support Windows 11 Insider (Canary) - it is perfectly understandable 😊.

I updated OBS to 30.0.0.rc1 - it had no effect and OBS still crashed.

I have for some time wanted to move to a "not-so-unstable" version of Windows, and this was the nudge I needed. So I have done a clean install of Windows 11 and updated to latest, official version - 10.0.22621 Build 22621. I have reinstalled OBS and the background removal plugin, and so far everything seems to work just fine.

I appreciate your time on this 👍😊

/Jesper

**Comment by jrossstocholm** [comment]
Since it seems like my problems were due to me using Windows 11 Insider Canary/Dev channel, I close this issue again.
