### ISSUE TITLE
Black box around cursor when using 10 bit color profile (KDE Plasma Wayland and X11)

### ISSUE THREAD

**Issue by Guitarmadillo** [obsproject/obs-studio#9702]
### Operating System Info

Other

### Other OS

Debian 12 (bookworm)

### OBS Studio Version

Other

### OBS Studio Version (Other)

29.0.2.1-1+b1

### OBS Studio Log URL

https://obsproject.com/logs/8ngt0f7NOuGLqisz

### Expected Behavior

This is an issue exclusive to Linux as I tried it on Windows 11. On Windows latest version the 10 bit color profiles record the display without a black box around the cursor.

### Current Behavior

When enabling a 10 bit color profile in Settings > Advanced:
Color Format: l010 (10-bit, 4:2:0, 3 planes)
Color Space Rec. 2100 (HLG)

There is a visible black box that follows the cursor around the screen. It appears when recording the screen on Wayland using Pipewire and also on X11 with XHSM.  
 

### Steps to Reproduce

1. Enable a 10 bit color profile in Settings > Advanced:
Color Format: l010 (10-bit, 4:2:0, 3 planes)
Color Space Rec. 2100 (HLG)
2. Set up a display capture using PipeWire or XHSM and make sure "Show Cursor" is enabled in the properties for the display capture.
3. Look at the OBS monitor to see a black box following around the cursor
...

**Comment by RytoEX** [comment]
Is this not a duplicate of #5189 ?

**Comment by Fenrirthviti** [comment]
Also, just to confirm, when OBS is set to default color format/space, this issues does not occur?

**Comment by Guitarmadillo** [comment]
The issue does not occur when set to default color format/space. It occurs when I set the color space to one of the Rec. 2100 options.

**Comment by kkartaltepe** [comment]
Test with the current version of obs, i cannot replicate this.

**Comment by gxalpha** [comment]
No reply has been given to the question/request above.
We can reopen this if it also occurs on current OBS.

**Comment by shawarden** [comment]
I am currently using OBS 31.0.3 and this issue is present on Wayland on KDE Plasma 6.3.4

![Image](https://github.com/user-attachments/assets/2932e331-4cb6-4d9e-b689-cb22eafe0430)

![Image](https://github.com/user-attachments/assets/11af54ea-07b6-4b2e-8ba6-9a8f05ee81d8)

![Image](https://github.com/user-attachments/assets/40ff0815-04a4-4003-9abf-416c0dc9ce81)

It appears in the preview window in OBS and in the resulting video recording.

**Comment by contrapoetra** [comment]
Additional info: on Arch Linux, the git version of the package seems to have this problem with any colorspace, including the defaults. The release package's (which at the time of writing, `obs-studio 31.0.3-2`) problem is the same as reported (black box on PQ and HLG colorspaces only)

**Comment by Meolsei** [comment]
I was searching around for this issue and only just now realized how recent of an issue this was. I have this same issue currently, and I believe I use the AUR package as well. Furthermore, I previously was using the flatpak release of OBS, which hadn't had this issue in particular, but had many different issues with the loop back camera package and the text on boxes.

**Comment by Syndace** [comment]
Hey, could we have some acknowledgement that the new comments are being read? Otherwise I'll open a new issue soon.

**Comment by Meolsei** [comment]
I'm so far the only one who's been keeping tabs on this.
