### ISSUE TITLE
30.0 beta does not log frame info on output end.

### ISSUE THREAD

**Issue by Penwy** [obsproject/obs-studio#9704]
### Operating System Info

Ubuntu 22.04

### Other OS

Also confirmed on windows

### OBS Studio Version

30.0.0-rc1

### OBS Studio Log URL

https://obsproject.com/logs/Pv9gJJAZcyyoKqBY

### Expected Behavior

On output stop OBS usually logs the amount of frames drawn, outputted, lagged, skipped and dropped.

### Current Behavior

No logging happens

### Steps to Reproduce

1. Start output
2. Stop output
3. Look at log
...

### Anything else we should know?

This seems to be caused by `output->video` evaluating to false in [`obs_output_end_data_capture_internal`](https://github.com/obsproject/obs-studio/blob/c58e511813c33e93da7637d50aa431ae0cddda0c/libobs/obs-output.c#L2359)

A bisect placed the culprit between f049d04af459a8e1d09aa39292b0a18c69bb61d4 and 2edb9f3151b2369cfb324d4c4281914c9c940aef. 
I cannot go any further because any commit between those refuses to run on my machine but that likely means the culprit is fb57eff212fbe5e777cf559288bc70bf67d9c428

**Comment by derrod** [comment]
Is this also the case in beta1?

**Comment by Penwy** [comment]
yes it is the commits I'm mentionning are pre beta1

**Comment by derrod** [comment]
Changing https://github.com/obsproject/obs-studio/blob/c58e511813c33e93da7637d50aa431ae0cddda0c/libobs/obs-output.c#L2359 to check for the video flag on the output instead should work

**Comment by Penwy** [comment]
Can confirm it fixes it.

**Comment by Jeroenvh99** [comment]
Where can I find this log on linux?
