### ISSUE TITLE
OBS on Mac Intel has no Hardware accelerated option but ffmpeg can use videotoolbox encoders

### ISSUE THREAD

**Issue by stephane-archer** [obsproject/obs-studio#9707]
### Operating System Info

macOS 13

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/GsHAXkplbVzLbT1l

### Expected Behavior

I should see videotoolbox encoders in OBS

### Current Behavior

videotoolbox encoders doesn't show up

### Steps to Reproduce

1. open OBS on an intel mac
2. see your CPU melting when encoding using xh264
3.
...

**Comment by gxalpha** [comment]
Please go through the support channels first.

This issue appears to be a support request, for which we don't use GitHub Issues.
Please make sure to visit the support sections on our [Discord server](https://discord.gg/obsproject) or [Forums](https://obsproject.com/forum).

Thank you!

**Comment by stephane-archer** [comment]
Do you support videotoolbox encoders in OBS for Mac Intel? I don't see why this is supposed to be a support question.

**Comment by gxalpha** [comment]
We do support them. If you can’t see or find them, I’m 95% sure that this is a support issue that can be dealt with on the Discord server. (And furthermore, the steps to reproduce in the description aren’t very descriptive. What are your settings?, Where are you looking for the encoder?, etc. But again, this sounds like a support problem).
