### ISSUE TITLE
Screen capture (Pipewire) broken for latest update to Snap Store

### ISSUE THREAD

**Issue by argosopentech** [obsproject/obs-studio#9715]
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/ZJoFGr2d316Nk3im

### Expected Behavior

OBS studio screen sharing used to consistently work until the latest Snap Store update a few days ago.

### Current Behavior

OBS studio crashes when I select a screen to share with this error:

```
warning: [pipewire] Failed to start screencast, denied or cancelled by user
info: PipeWire initialized
info: [pipewire] Screencast session created
info: [pipewire] Asking for desktop
info: [pipewire] desktop selected, setting up screencast
[E] pw.loop [loop.c:86 pw_loop_new()] 0x55a22d23b040: can't make support.system handle: No such file or directory
Segmentation fault (core dumped)

```

Here's another example of someone with the same error:
https://askubuntu.com/questions/1488828/obs-crashes-immediately-after-selecting-the-screen-it-was-working-fine-before-t

### Steps to Reproduce

1. Install obs-studio from the Snap Store on Ubuntu Linux
2. Attempt to record your screen
3. OBS studio crashes

**Comment by gxalpha** [comment]
This seems like a problem with the snap, report it to them.

**Comment by argosopentech** [comment]
> This seems like a problem with the snap, please report it to the snap maintainers instead.

Thanks for the reply. I made an issue on the Snapcraft forum:
https://forum.snapcraft.io/t/pipewire-screensharing-broken-in-latest-obs-studio-update/37309

**Comment by mihawk90** [comment]
A more appropriate place would probably be the issue section of their github repo:

https://github.com/snapcrafters/obs-studio/issues
