### ISSUE TITLE
No package for Ubuntu Mantic Minotaur in the PPA repository

### ISSUE THREAD

**Issue by 240-185** [obsproject/obs-studio#9720]
### Operating System Info

Other

### Other OS

Ubuntu 23.10

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/VnuuxJKPibiJnz31

### Expected Behavior

Réception de :7 https://ppa.launchpadcontent.net/obsproject/obs-studio/ubuntu mantic/main amd64 Packages [1 132 B]
Réception de :8 https://ppa.launchpadcontent.net/obsproject/obs-studio/ubuntu mantic/main Translation-en [160 B]

### Current Behavior

Err :7 https://ppa.launchpadcontent.net/obsproject/obs-studio/ubuntu mantic Release
  404  Not Found [IP : 185.125.190.52 443]

### Steps to Reproduce

1. Open some terminal thing
2. sudo add-apt-repository ppa:obsproject/obs-studio
3. Press ENTER

### Anything else we should know?

I should not have to modify by hand the file "obsproject-ubuntu-obs-studio-mantic.sources" and point to the Lunar packages.

The attached log is just there to show I'm using Ubuntu 23.10.

**Comment by tytan652** [comment]
The PPA will likely support 23.10 when OBS Studio 30 is released as stable.

I let @Gol-D-Ace have the final word.

**Comment by Gol-D-Ace** [comment]
Hi

Considering that Mantic does have 29.1.3 in the  official Ubuntu package repo the PPA would only reach people that actively try to install from the PPA.

Also without special precautions the PPA package would be overridden again.

I would prefer to just wait for the 30.0.0 release.

I can try to build a package for mantic though if you would prefer that.

**Comment by 240-185** [comment]
…I have no words.

**Comment by Gol-D-Ace** [comment]
While I don't quite get your reply I tried to do a mantic build for 29.1.3

There are issues with external dependencies (aja) which currently prevents building.

This got fixed with 30.0.0

Therefore there will be indeed no PPA build for 29.1.3
