### ISSUE TITLE
betterTTV crash chat twitch

### ISSUE THREAD

**Issue by TOWUK** [obsproject/obs-studio#9731]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.0-rc1

### OBS Studio Log URL

https://obsproject.com/logs/2L3Fo2sHkDrHXBjb

### Expected Behavior

just open emoji betterttv in chat obs

### Current Behavior

clear window chat

### Steps to Reproduce

login with twitch and use betterttv and ffz option
open chat window and emoji menu

**Comment by TOWUK** [comment]
![image](https://github.com/obsproject/obs-studio/assets/28830162/ee58c370-148a-422b-95f2-e4a35dc9d6b3)
29 version worked normally!!!

**Comment by Fenrirthviti** [comment]
This is a known issue already fixed in master, and will be fixed for the next RC and release.

**Comment by TOWUK** [comment]
> This is a known issue already fixed in master, and will be fixed for the next RC and release.

thanks <3
