### ISSUE TITLE
Using any BTTV emote crashes Twitch chat on OBS beta (and only on beta)

### ISSUE THREAD

**Issue by Akumanjo** [obsproject/obs-studio#9737]
### Operating System Info

Windows 10

### OBS Studio Version

30.0.0-rc1

### OBS Studio Log URL

http://obsproject.com

### Expected Behavior

I expect the embedded chat (the one included in OBS) to display my viewer's messages when they send me some, and to get BTTV emotes visible by toggling on the option in OBS's parameters

I also expect the same behaviour from third party overlays that I include on my stream (mostly streamelements' chat overlay)

### Current Behavior

Using a BTTV emote (not an official Twitch emote) crashes the chat on the dock. The chat becomes a blank page, which can only disappear by  restarting the app. Closing the chat while not restarting brings back the blank page on the dock.

Moreover, third party chats also crash, but differently. Using a BTTV emote with streamelement's chat overlay makes the feed stop. When going to the overlay's web page, the chat keeps running, so the problem is OBS dependant

I precise that switching back to 29 made everything work back. So the problem seems to be only in the beta build.

### Steps to Reproduce

1. Open OBS
2. Connect it to your Twitch account (did not try on YouTube). This will dock your chat on the screen (if not, dock it)
3. Check in your parameters the option that allows the BTTV integration on chat
4. (For this step, I will assume you have BTTV emotes linked to your account) type in your chat one of your BTTV emotes (I do not use FrankenFaceZ, but it might trigger the same bug)
5. The docked chat will instantly go blank, while any third-party chat (I used streamelements') will simply freeze, and not display any new message.
...

### Anything else we should know?

I created this account just now, to tell you about this issue that bothered me a bit

Please be kind, as it is my first (but not last) contribution to the open source community

I will be providing screenshots later, but as for now I will stream in 10 minutes. So before I forget, I wanted to post this issue here

Lastly, English is not my first language. So excuse me for any syntax error.

Thanks for your attention, take care

**Comment by Penwy** [comment]
that's a known issue, already fixed in master and will be fixed in the next releases.

**Comment by tytan652** [comment]
Fixed by #9695
