### ISSUE TITLE
Unable to enter text in the Interact window of a browser Source

### ISSUE THREAD

**Issue by Brier1104** [obsproject/obs-studio#9740]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/WDkpawRh8I8hRpJo

### Expected Behavior

When clicking the Interact button for a browser Source, it should be possible to enter text in a web page text box.

### Current Behavior

Web pages do not accept text input.

### Steps to Reproduce

1. Select or create a browser Source with a web page that has a text box.
2. Click the Interact button.
3. Try entering some text.
...

### Anything else we should know?

This small bug occurs intermittently on 3 different PCs (about 30% of the time).  I have not found any pattern in this behaviour.  I guess this makes it difficult to debug.  I'll make a log file next time it happens.

**Comment by PatTheMav** [comment]
To be able to properly debug this it would be helpful to provide a set of URLs where this behaviour consistently occurs. Without such a stable reproducer it's very unlikely the issue could be identified, let alone be fixed.

**Comment by Brier1104** [comment]
I'll make a note of the URLs whenever it happens.

Thanks.

**Comment by RytoEX** [comment]
Closing this as not actionable. If someone can provide reliable steps to reproduce (including a sample URL or HTML file) that does this, then we can consider reopening this.
