### ISSUE TITLE
black screen capture on wayland (swaywm, nvidia, gentoo)

### ISSUE THREAD

**Issue by Xephobia** [obsproject/obs-studio#9741]
### Operating System Info

Other

### Other OS

Gentoo

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/lObQWdzHmyH6Back

### Expected Behavior

When using a pipewire screen capture, it should be able to record videos.

### Current Behavior

The output is black, with an `error: [pipewire] Error id:2 seq:10 res:-32 (Unknown error -32): no more input formats` error
This occurs when using the nvidia gpu (with `prime-run`) but i haven't been able to test on the integrated amd gpu because of #9733

### Steps to Reproduce

1. launch obs with `prime-run obs`
2. create a `Screen Capture (PipeWire)` input
3. black screen, even after selecting the monitor to record
...

### Anything else we should know?

I did setup everything right for screen capture on my side, as can be proven both by
1. trying screen capture on firefox (works)
2. trying the [xdp-screen-cast.py](https://gitlab.gnome.org/-/snippets/19) script (also works)

**Comment by kkartaltepe** [comment]
please test the current master commit, and include the compositor and xdg implementation you are using, along with a stacktrace from gdb if the issue persists on master.

**Comment by Xephobia** [comment]
Hi, the error is gone on the last commit, as well as https://github.com/obsproject/obs-studio/issues/9733. Now another interesting issue is that red and blue seems to be inverted (as can be seen on the screenshot)
![image](https://github.com/obsproject/obs-studio/assets/28755060/74ae3475-b6cd-493d-8dac-2121b5c7664e)

a relevant bit in the log seems to be :
```
info: [pipewire] Negotiated format:
info: [pipewire]     Format: 7 (Spa:Enum:VideoFormat:RGBx)
info: [pipewire]     Size: 1920x1080
info: [pipewire]     Framerate: 0/1
```

as for the compositor, I am using sway (wlroots) and the xdg implementation I'm using is `xdg-desktop-portal-wlr`

**Comment by kkartaltepe** [comment]
Closing since this is not occuring on main. the other bug is already noted elsewhere and has a fix pending.
