### ISSUE TITLE
Processes without windows do not show up in Application Audio Capture

### ISSUE THREAD

**Issue by JakeIsMeh** [obsproject/obs-studio#9750]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.3

### OBS Studio Log URL

N/A

### Expected Behavior

I should be able to capture audio from window-less processes emitting audio

### Current Behavior

I am unable to capture audio from window-less processes emitting audio

### Steps to Reproduce

1. Use something like plain mpv to emit audio from a window-less process: `mpv --no-video [audio file/video with audio]`
2. Attempt to capture it's audio stream with application audio capture
3. It does not show up in the list of available processes to capture.

### Anything else we should know?

Another use case affected by this is capturing audio from a VMware virtual machine, as the display window does not emit the audio, instead the hypervisor process `vmware-vmx.exe` does.

I understand that there is no way of determining whether a process emits audio or not, and thus the window list solution is a best effort implementation right now, but I'd love to be able to select any arbitrary process to capture from somehow.

**Comment by Mr-Z-2697** [comment]
I remember I had this issue once with vmware you mentioned, I tried edit the scene config file and it actually works, you can try this kinda workaround if urgent.

**Comment by gxalpha** [comment]
Only processes with windows showing up is working as designed (even though the design might not be optimal).

We don't track track feature request using GitHub Issues (we use GitHub exclusively for bug reports).
Please put feature requests on [our ideas page](https://ideas.obsproject.com).

Thank you!
