### ISSUE TITLE
When selecting different source in Video Capture device, OBS crashes

### ISSUE THREAD

**Issue by Darkwood3r** [obsproject/obs-studio#9757]
### Operating System Info

macOS 13

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/FtptpG6mUPQFvUyn

### Expected Behavior

Loading the selected source video capture device.

### Current Behavior

OBS crash whenever I choose different source in my VIDEO CAPTURE device. 

### Steps to Reproduce

1. Open OBS
2. Click on Video Capture Device
3. Selecting different source
4. Crash
...

### Anything else we should know?

The only workaround is selecting different source like FaceTime camera, then exit the OBS. 
And then it is usually possible to choose the needed source like BlackMagic webcam or AverMedia capture card.

I am using Macbook pro M1, OS 13.5.1

**Comment by Darkwood3r** [comment]
log here [OBS-2023-10-25-183854.ips.zip](https://github.com/obsproject/obs-studio/files/13168715/OBS-2023-10-25-183854.ips.zip)

**Comment by gxalpha** [comment]
@Darkwood3r could you retest this with the latest Release Candidate version of OBS 30.0? If it still crashes there, could you provide another crash log from that version?

**Comment by Darkwood3r** [comment]
Just tried the 30.0 RC and it seems to be fixed.

I also tried it on the stable version 29.1.3 and could not reproduce the
problem :/ So, I am a bit confused :)

cheers


čt 26. 10. 2023 v 22:16 odesílatel Sebastian Beckmann <
***@***.***> napsal:

**Comment by PatTheMav** [comment]
This crash is due to a known Qt bug that we reported: https://bugreports.qt.io/browse/QTBUG-116155

Should be fixed with OBS 30 and above because we updated the Qt version for it.
