### ISSUE TITLE
Browser source not showing anything (v30.0.0-rc1)

### ISSUE THREAD

**Issue by Geczy** [obsproject/obs-studio#9761]
### Operating System Info

Windows 11

### Other OS

MacOS, Windows

### OBS Studio Version

30.0.0-rc1

### OBS Studio Log URL

https://obsproject.com/logs/BBo2Hsi2qL0KyXuO

### Expected Behavior

Show browser source

### Current Behavior

Shows nothing

### Steps to Reproduce

Add [this url](https://dotabod.com/overlay/clmtwxp5t0004lc08lyssqdee) as a browser source

You should see this.

![CleanShot 2023-10-26 at 07 21 40@2x](https://github.com/obsproject/obs-studio/assets/1036968/4f988283-43bd-4a5e-81f6-1b0a3eb3d896)

 But instead it shows nothing

![CleanShot 2023-10-26 at 07 23 14@2x](https://github.com/obsproject/obs-studio/assets/1036968/1207a966-8250-4e9f-b267-9b8ef024a9fc)

### Anything else we should know?

Works in OBS v29, v28
Does not work in v27

**Comment by gxalpha** [comment]
Could you test with the latest nightly build ([Windows link](https://obsbot.rodney.io/artifacts/1006048557))?
Browser is known to be broken in RC1.

**Comment by Geczy** [comment]
Sorry, I only have a Mac to test with @gxalpha

**Comment by gxalpha** [comment]
Here is [Apple Silicon](https://github.com/obsproject/obs-studio/suites/17603837245/artifacts/1006048551) or [Intel](https://github.com/obsproject/obs-studio/suites/17603837245/artifacts/1006048553)

**Comment by Geczy** [comment]
I couldn't open it, even trying to use Open Anyway. Can you test it?

![CleanShot 2023-10-26 at 07 39 10@2x](https://github.com/obsproject/obs-studio/assets/1036968/e2e0efd3-26d3-41fb-937e-f4ed04526e90)

![CleanShot 2023-10-26 at 07 39 35@2x](https://github.com/obsproject/obs-studio/assets/1036968/71b2472d-9cda-4aec-82e1-77d4076376ca)

**Comment by gxalpha** [comment]
Instead of double-clicking, do Right Click -> Open. That should give you the option to open in the first popup.

**Comment by poecco** [comment]
> Could you test with the latest nightly build ([Windows link](https://obsbot.rodney.io/artifacts/1006048557))? Browser is known to be broken in RC1.

Tested this (win11) - looks good.
![image](https://github.com/obsproject/obs-studio/assets/71287790/f299ef92-4115-42fd-afa3-fdbe5e57c002)

**Comment by Fenrirthviti** [comment]
This is known and will be fixed in RC2/Release.
