### ISSUE TITLE
OBS no longer 

### ISSUE THREAD

**Issue by blovelego** [obsproject/obs-studio#9778]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/J3n229Y2OAVsG2oM

### Expected Behavior

when I added a display capture it picks up any monitor i select

### Current Behavior

when I added a display capture it no longer picked up any screens except my main monitor

### Steps to Reproduce

1. not sure it's just installed and updated and suddenly my other screens arnt picking up
2.
3.
...

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
