### ISSUE TITLE
Custom placeholder of virtual cam on macOS does not show up 

### ISSUE THREAD

**Issue by Backpackstudio** [obsproject/obs-studio#9783]
### Operating System Info

macOS 14

### OBS Studio Version

30.0.0-rc2

### OBS Studio Log URL

https://obsproject.com/logs/q2SkeO61puuPMFIW

### Expected Behavior

When not streaming, Virtual Cam shows custom placeholder.

### Current Behavior

When not streaming, Virtualcam does not show custom placeholder. Virtual Cam itself is working.

### Steps to Reproduce

1. Open FaceTime
2. Select OBS Virtual Camera as camera
3. Start stream in OBS
4. Stop steam in OBS
...

### Anything else we should know?

I did check the code and according to the code, there can be several locations for custom placeholder. 

I have placed in several locations my custom image, but Virtual Cam does not use any of them.

```
/Applications/OBS.app/Contents/Resources/obs-mac-virtualcam.plugin/Contents/Resources/placeholder.png
```

```
~/Library/Application Support/obs-studio/plugin_config/mac-virtualcam/placeholder.png
```

```
/Library/Application Support/obs-studio/plugin_config/mac-virtualcam/placeholder.png
```

https://github.com/obsproject/obs-studio/blob/df990192b2582f9b254837adb3c4aed4d61b479d/plugins/mac-virtualcam/src/dal-plugin/OBSDALStream.mm#L155

https://github.com/obsproject/obs-studio/blob/df990192b2582f9b254837adb3c4aed4d61b479d/plugins/mac-virtualcam/src/dal-plugin/OBSDALStream.mm#L160C85-L160C95

**Comment by tehbasshunter** [comment]
This is no longer possible as of v30.

**Comment by gxalpha** [comment]
OBS 30 uses a CMIO Camera Extension on macOS 13 upwards. Due to the design of system extensions, custom placeholders are longer be supported.

**Comment by felippenardi** [comment]
@gxalpha how is the placeholder setup now? It is totally impossible to change it? 🥺

**Comment by gxalpha** [comment]
The placeholder is now part of the system extension bundle. Messing with it will probably invalidate the code signatures.
The only way to change it would be to compile OBS yourself instead of using the official build, which is not recommended.

**Comment by pinetreemoonlight** [comment]
Please add this feature back :(

**Comment by Fenrirthviti** [comment]
Just to expand on the comment above, we cannot add this back, as the new camera extension system in macOS doesn't allow for hot-swapping the image. You'd need to rebuild the module yourself if you want to change it.

**Comment by JayHoltslander** [comment]
There needs to be some kind of change made to OBS to support changing this placeholder image by some other means then. 

To the uninitiated, in a business Zoom meeting setting, the OBS logo looks kind of weird creepy and confusing. 
>"Is that some kind of swastik?"

I'd **much** rather see a more universally recognized choice used like [SMPTE Color Bars](https://en.wikipedia.org/wiki/SMPTE_color_bars) instead of the current placeholder if there's going to forever be no way of changing this image.

**Comment by CriticalTinkerer** [comment]
Hey, guys, if OBS can output to the virtual camera, then OBS can supply the placeholder image.  Just requires rethinking the current implementation. The placeholder could even be an MPEG.

**Comment by CGDogan** [comment]
It seems entirely possible to make it configurable - there just isn't demand for it judging by the fact that no one has started a GitPay.
