### ISSUE TITLE
OBS crashes when closing

### ISSUE THREAD

**Issue by GrilleFFM** [obsproject/obs-studio#9784]
### Operating System Info

Windows 10

### OBS Studio Version

30.0.0-rc2

### OBS Studio Version (Other)

30.0.0-rc1 and Beta

### OBS Studio Log URL

https://obsproject.com/logs/30A4i0eKNgFsibLV

### OBS Studio Crash Log URL

https://obsproject.com/logs/BODH4uwY3HQQebxv

### Expected Behavior

That OBS would close normally and restart normally.

### Current Behavior

I have been testing since the beta for 30.0.0 and have the problem that OBS seems to crash every time I close it. It takes a very long time to close and when I restart it, the choice between normal and safe start is displayed every time. 

Normally no crash log is created. Yesterday, however, one was created because the message that there was a crash also appeared. This message does not usually appear and I only notice that there was a crash when I restart.

### Steps to Reproduce

1. I close OBS normally
2. I open OBS normally
3.
...

### Anything else we should know?

My collection of scenes is very extensive. But with the last official release, everything ran without problems. There, the closing process also took a little longer, but afterwards OBS started up normally again.

I have not noticed any problems during running sessions.

**Comment by Fenrirthviti** [comment]
Can you please test without any third party plugins to see if this crash still occurs?

**Comment by GrilleFFM** [comment]
without third-party plugins, everything runs normally. OBS closes very quickly and starts normally. I'll probably have to look for the bad plugin in.

**Comment by GrilleFFM** [comment]
Ok thanks, i will do. I found the bad plugin it is obs-shaderfilter-2.1.1-windows.
