### ISSUE TITLE
OBS won't let me Stream to youtube

### ISSUE THREAD

**Issue by RyzenDew** [obsproject/obs-studio#9786]
### Operating System Info

Windows 11

### Other OS

Arch Linux And Nobara and Fedora

### OBS Studio Version

30.0.0-rc2

### OBS Studio Log URL

https://obsproject.com/logs/LnVrljrNPgtKGMDU

### Expected Behavior

![image](https://github.com/obsproject/obs-studio/assets/84041391/aba22424-fa09-4e47-ac1a-53ee10f8bf25)
as you can see i am allowed to stream been that way since 2014 or so 

### Current Behavior

![image](https://github.com/obsproject/obs-studio/assets/84041391/c54c787f-564c-4d81-835d-a9a28ac9ccfb)

![image](https://github.com/obsproject/obs-studio/assets/84041391/23e3ec5b-182e-4513-8393-336d73668654)

### Steps to Reproduce

1.connect obs to youtube 
2.Try to manage broadcast
3.and it tells you some bs about how you can't
...

**Comment by Gol-D-Ace** [comment]
Hi.

As a first step please try logging out / disconnecting the YouTube account in OBS Studio.

Make sure you select the right account/ brand when connecting.

If this doesn't bring any change let us know.

**Comment by RyzenDew** [comment]
> Hi.
> 
> As a first step please try logging out / disconnecting the YouTube account in OBS Studio.
> 
> Make sure you select the right account/ brand when connecting.
> 
> If this doesn't bring any change let us know.

Already did all that even reinstalled windows and it's the correct account as you can see above. nothing is working

**Comment by derrod** [comment]
There's nothing we can do here, OBS just gets this error from the YouTube API:
> 11:10:37.536: YouTube API error:
11:10:37.536: 	HTTP status: 403
11:10:37.536: 	URL: https://www.googleapis.com/youtube/v3/liveBroadcasts?part=snippet,contentDetails,status&broadcastType=all&maxResults=50&broadcastStatus=active
11:10:37.536: 	JSON: {"error": {"code": 403, "errors": [{"domain": "youtube.liveBroadcast", "extendedHelp": "https://www.youtube.com/features", "message": "The user is not enabled for live streaming.", "reason": "liveStreamingNotEnabled"}], "message": "The user is not enabled for live streaming."}}

This is ultimately an issue on YouTube's end or with your account.

**Comment by RyzenDew** [comment]
> There's nothing we can do here, OBS just gets this error from the YouTube API:
> 
> > 11:10:37.536: YouTube API error:
> > 11:10:37.536: 	HTTP status: 403
> > 11:10:37.536: 	URL: https://www.googleapis.com/youtube/v3/liveBroadcasts?part=snippet,contentDetails,status&broadcastType=all&maxResults=50&broadcastStatus=active
> > 11:10:37.536: 	JSON: {"error": {"code": 403, "errors": [{"domain": "youtube.liveBroadcast", "extendedHelp": "https://www.youtube.com/features", "message": "The user is not enabled for live streaming.", "reason": "liveStreamingNotEnabled"}], "message": "The user is not enabled for live streaming."}}
> 
> This is ultimately an issue on YouTube's end or with your account.

yet it only happens on obs and not xsplit ... so kinda your issue cause things on youtube didn't change i was already asking youtube support

**Comment by tytan652** [comment]
This sounds more likely to be a support request rather than a bug 
report, and we are not currently accepting support requests on GitHub 
Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for further assistance.

Thank you!

**Comment by RyzenDew** [comment]
even stream labs works ...

**Comment by paulpv** [comment]
What are the http requests on Steam Labs and XSplit?
