### ISSUE TITLE
Ubuntu 22.04 no WHIP

### ISSUE THREAD

**Issue by Neon-Ice** [obsproject/obs-studio#9789]
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

30.0.0-rc2

### OBS Studio Version (Other)

30 rc2

### OBS Studio Log URL

?

### Expected Behavior

Show WHIP in Settings -> Stream -> Service  selection list

### Current Behavior

No WHIP

### Steps to Reproduce

1. installed OBS-Studio-30.0.0-rc2-Ubuntu-x86_64.deb
2. go to Settings -> Stream -> Service 
3. no WHIP
...

**Comment by derrod** [comment]
WHIP is not supported as Ubutnu 22.04 does not provide any or only outdated packages for libdatachannel (iirc), use the Flatpak instead.

**Comment by Neon-Ice** [comment]
Oke, thank you.
