### ISSUE TITLE
DOOM ETERNAL WONT LAUNCH WHEN THIS IS INSTALLED. 

### ISSUE THREAD

**Issue by dwarfthelegend** [obsproject/obs-studio#9792]
### Operating System Info

Windows 11

### Other OS

windows 11

### OBS Studio Version

29.1.3

### OBS Studio Log URL
https://obsproject.com/logs/XVOnsMTOxDzezSk6
https://obsproject.com/logs/t3WZoXWS3WOXmBql

### Expected Behavior

Usually, I'm able to launch doom eternal and play this game fine while recording it with OBS. but this seems to be an issue related to #970 and #9168

### Current Behavior

Basically, when OBS is installed on my system, it conflicts with my all-time favorite game, Doom Eternal, the hook file to be specific apparently. please fix this, because i make doom eternal videos with OBS, I used to be able to do this and now I sadly cannot. I love OBS and doom eternal and i just want them to get along, now my game won't even make it to the first screen before crashing while this is installed. if you fix this, ill personally donate 100$ to the GitHub page. I don't have much to offer, I don't have much in general, but I don't want the only game i like to not work anymore.]
https://steamcommunity.com/app/782330/discussions/0/6812310007744914356/?ctp=2

thats the discussion

### Steps to Reproduce

1.i installed OBS
2.Tried to launch doom eternal 
3. and it did not launch
...

### Anything else we should know?

nope

**Comment by YorVeX** [comment]
Have you also tried the latest stable version of OBS (29.1.3)? Especially game hooking/capturing is something where it's important to use the stable.

**Comment by kkartaltepe** [comment]
Please follow the instructions when creating an issue to attach a log from obs. I will repeat them for you since you appear not to have read them the first time "Please provide the obsproject.com URL (from Help menu > Log Files > Upload Current/Previous Log File) to the OBS log file where this issue occurred."

The linked issues seem unlikely to be related as they are about opengl and directx applications while according to the discussion you linked the game is a vulkan game. If you can follow the instructions from that discussion https://steamcommunity.com/app/782330/discussions/0/6812310007744914356/#c6812310007745053272 the crash dump may be helpful.

**Comment by dwarfthelegend** [comment]
> Please follow the instructions when creating an issue to attach a log from obs. I will repeat them for you since you appear not to have read them the first time "Please provide the obsproject.com URL (from Help menu > Log Files > Upload Current/Previous Log File) to the OBS log file where this issue occurred."
> 
> The linked issues seem unlikely to be related as they are about opengl and directx applications while according to the discussion you linked the game is a vulkan game. If you can follow the instructions from that discussion https://steamcommunity.com/app/782330/discussions/0/6812310007744914356/#c6812310007745053272 the crash dump may be helpful.

[Crash_m202310310516.zip](https://github.com/obsproject/obs-studio/files/13246419/Crash_m202310310516.zip)
[Crash_m202310310520.zip](https://github.com/obsproject/obs-studio/files/13246420/Crash_m202310310520.zip)
[Crash_m202311011231.zip](https://github.com/obsproject/obs-studio/files/13246421/Crash_m202311011231.zip)
[Crash_m202311030224.zip](https://github.com/obsproject/obs-studio/files/13246422/Crash_m202311030224.zip)
[Crash_m202311030233.zip](https://github.com/obsproject/obs-studio/files/13246423/Crash_m202311030233.zip)

**Comment by Fenrirthviti** [comment]
Please also provide an OBS log file. This was a known issue, but only occurs on very old NVIDIA drivers, and was a bug that NVIDIA shipped, and has since fixed.

The OBS RC2 is also not available directly on the Windows store, and would require manual opt-in to the beta channel to be updated to.

**Comment by dwarfthelegend** [comment]
> Have you also tried the latest stable version of OBS (29.1.3)? Especially game hooking/capturing is something where it's important to use the stable.

yes, indeed i did. that's the version that makes doom eternal stop working i appreciate this reply by the way

**Comment by dwarfthelegend** [comment]
> Please also provide an OBS log file. This was a known issue, but only occurs on very old NVIDIA drivers, and was a bug that NVIDIA shipped, and has since fixed.
> 
> The OBS RC2 is also not available directly on the Windows store, and would require manual opt-in to the beta channel to be updated to.

how do i do that

**Comment by Fenrirthviti** [comment]
Launch OBS > Help menu > Log Files > Upload Current/Previous Log File, as stated in the issue template and replies here.

Please be mindful in the future to read and follow the template, as this is all explained already. When you ignore the template, it makes things more of a burden on both parties.

**Comment by dwarfthelegend** [comment]
> Launch OBS > Help menu > Log Files > Upload Current/Previous Log File, as stated in the issue template and replies here.
> 
> Please be mindful in the future to read and follow the template, as this is all explained already. When you ignore the template, it makes things more of a burden on both parties.

i did it

**Comment by kkartaltepe** [comment]
> > Launch OBS > Help menu > Log Files > Upload Current/Previous Log File, as stated in the issue template and replies here.
> > Please be mindful in the future to read and follow the template, as this is all explained already. When you ignore the template, it makes things more of a burden on both parties.
> 
> i did it

And please remember the most important part "Please provide the obsproject.com URL"

**Comment by kkartaltepe** [comment]
I see you edited the original issue now. Thanks.

**Comment by dwarfthelegend** [comment]
> I see you edited the original issue now. Thanks.ofc i just want the issue fixed

**Comment by dwarfthelegend** [comment]
> I see you edited the original issue now. Thanks.
any ideas on this issue at all?

**Comment by dwarfthelegend** [comment]
> Our GitHub is for reporting confirmed bugs with reliable replication steps, and this is a borderline support request. If you're looking for something more immediate, please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance. Otherwise this may be a while before we have time to devote resources to investigating as this is the only report we've heard and I am not able to replicate.
> 
> Thank you!

i understand sorry for being impatient thank you for being polite abt saying this

**Comment by Fenrirthviti** [comment]
If Bethesda support can provide specifics on why they believe this is our issue, that would helpful in the meantime. We are typically not able to investigate crashes in applications that are not OBS, as they are closed source.

Any technical specifics they can provide would help push this forward.

**Comment by MattyFresh68** [comment]
Works fine here on win11 22h2 and obs v30 rc1
![image](https://github.com/obsproject/obs-studio/assets/66339760/3587dc96-55e0-4731-ac16-5f030c82738b)

**Comment by Mister36MN** [comment]
Also have no issues here, using 30-rc2 and Windows 11 22635. It's highly unlikely this is an OBS or DOOM issue

**Comment by dwarfthelegend** [comment]
> Also have no issues here, using 30-rc2 and Windows 11 22635. It's highly unlikely this is an OBS or DOOM issue

that would make no sense as doom works fine while obs is uninstalled. and has no issue launching when the program isnt installed

**Comment by dwarfthelegend** [comment]
> If Bethesda support can provide specifics on why they believe this is our issue, that would helpful in the meantime. We are typically not able to investigate crashes in applications that are not OBS, as they are closed source.
> 
> Any technical specifics they can provide would help push this forward.

this is what they told me 
![Screenshot 2023-11-03 223642](https://github.com/obsproject/obs-studio/assets/149748277/7c0c8334-d53a-40b6-a1cc-146ae68963cf)

**Comment by dwarfthelegend** [comment]
> If Bethesda support can provide specifics on why they believe this is our issue, that would helpful in the meantime. We are typically not able to investigate crashes in applications that are not OBS, as they are closed source.
> 
> Any technical specifics they can provide would help push this forward.

a lot of people ARE having this issue

**Comment by Fenrirthviti** [comment]
There might be others having the issue, however we haven't heard any reports of it, and are not able to replicate on our end, so there is some information that is missing. A game crashing on our hook also doesn't exactly mean it's us doing something wrong, there is a very real chance the game is not handling the vulkan capture layer (which is part of vulkan spec) properly. We've seen a similar issue with Doom in the past, and it was fixed with a driver update on NVIDIA GPUs, so I'm very reluctant to assume this is our fault without further information.

All that said, we see this issue, and will look at it as time allows. More detailed replication steps (i.e. any other third party programs being used, overlays, etc.) would be useful, as we have tried what is listed here and aren't able to cause the issue.

**Comment by dwarfthelegend** [comment]
> There might be others having the issue, however we haven't heard any reports of it, and are not able to replicate on our end, so there is some information that is missing. A game crashing on our hook also doesn't exactly mean it's us doing something wrong, there is a very real chance the game is not handling the vulkan capture layer (which is part of vulkan spec) properly. We've seen a similar issue with Doom in the past, and it was fixed with a driver update on NVIDIA GPUs, so I'm very reluctant to assume this is our fault without further information.
> 
> All that said, we see this issue, and will look at it as time allows. More detailed replication steps (i.e. any other third party programs being used, overlays, etc.) would be useful, as we have tried what is listed here and aren't able to cause the issue.

never said it was your fault im just being redirected to different forums every week and this is where i ended up. sorry if it seems that way

**Comment by dwarfthelegend** [comment]
> There might be others having the issue, however we haven't heard any reports of it, and are not able to replicate on our end, so there is some information that is missing. A game crashing on our hook also doesn't exactly mean it's us doing something wrong, there is a very real chance the game is not handling the vulkan capture layer (which is part of vulkan spec) properly. We've seen a similar issue with Doom in the past, and it was fixed with a driver update on NVIDIA GPUs, so I'm very reluctant to assume this is our fault without further information.
> 
> All that said, we see this issue, and will look at it as time allows. More detailed replication steps (i.e. any other third party programs being used, overlays, etc.) would be useful, as we have tried what is listed here and aren't able to cause the issue.

i had sonic radar 3 installed, that was causing the graphics hook error with doom eternal and OBS because sonic radar was conflicting with obs causing conflictions between OBS and doom eternal

**Comment by Shirk** [comment]
Might as well be a problem with how DOOM Eternal tries to setup Vulkan (going by the fact that there's people here than run the game fine with the same setup you describe) - have you tried to select OpenGL instead of Vulkan as the graphics output for the game?

E.g. the opposite of [this](https://help.bethesda.net/#en/answer/34863) - if OBS is closed the graphics-hook is only loaded by Vulkan apps.

**Comment by RytoEX** [comment]
> i had sonic radar 3 installed, that was causing the graphics hook error with doom eternal and OBS because sonic radar was conflicting with obs causing conflictions between OBS and doom eternal

Sonic Radar is listed in our [Known Application Conflicts list](https://obsproject.com/kb/known-conflicts). Closing per above.

**Comment by Squall-Leonhart** [comment]
This issue is all due to OBS's detours hooking not playing nice with the hooking behaviours of other apps, 

OBS was informed of such issues by the RTSS developer 2 years ago, its no surprise that Asus and the nahimic overlay introduce the same issue, and its highly doubtful either of these will be updated because as far as things go, they are in the right - OBS is in the wrong.
