### ISSUE TITLE
OBS 30.0.0 RC2 does not create a virtual camera which other applications can see

### ISSUE THREAD

**Issue by Iritscen** [obsproject/obs-studio#9797]
### Operating System Info

macOS 14

### OBS Studio Version

30.0.0-rc2

### OBS Studio Log URL

https://obsproject.com/logs/ouw4QNlX2WgU6TiB

### Expected Behavior

A virtual camera showing the same contents as OBS's preview window.

### Current Behavior

OBS Virtual Camera shows as an available device to choose in various applications (Discord, Skype, QuickTime Player) but the stream itself is always black.  Audio doesn't seem to be present in the virtual camera stream either.

### Steps to Reproduce

1. Choose a window or screen to capture with OBS's "Window Capture" or "macOS Screen Capture" source.  Set up some audio source(s) too.
2. Click "Start Virtual Camera".
3. Open an application that takes camera input and select OBS Virtual Camera as the device.  The stream will be a pure black screen with silence.

### Anything else we should know?

OBS has been granted Screen Recording permission in the macOS Security preferences.

**Comment by Penwy** [comment]
the virtual camera does not carry any sound, that much is normal.
For the video that likely a support issue than a bug, you should use the [forums](https://obsproject.com/forum/) or [discord](https://obsproject.com/discord/) for assistance on this.

**Comment by RytoEX** [comment]
Works fine here on macOS 13.6.1 with OBS Studio 30.0.0-rc2 in FaceTime, QuickTime Player, and Discord. If you updated from a pre-30 version of OBS, perhaps those applications are trying to load the old Virtual Camera? @gxalpha @PatTheMav ?

**Comment by Iritscen** [comment]
I solved the problem by selecting "Program (Default)" as the output type.  I previously had selected Source > Video Capture Device.  Thanks to Penwy for the help on Discord.
