### ISSUE TITLE
OBS is fucking my CPU

### ISSUE THREAD

**Issue by NotJuba** [obsproject/obs-studio#9799]
### Operating System Info

Ubuntu 22.10

### OBS Studio Version

30.0.0-rc2

### OBS Studio Version (Other)

29.1.3

### OBS Studio Log URL

.

### OBS Studio Crash Log URL

NO crush 

### Expected Behavior

To avoid excessive CPU consumption

### Current Behavior

Excessive CPU consumption

### Steps to Reproduce

1 I tried to open OBS on my Ubuntu machine
2 I used the 'top' command and discovered OBS is hogging my machine
3 I'm really clueless about what's causing this because I know I have a good CPU and all
4 I recorded a [video here](https://www.youtube.com/watch?v=CMqZrBn9IrQ) Please tell me if you have any tips or suggestions. I would really appreciate it because I love OBS especially the fact that it's written in C and has a good GUI

### Anything else we should know?

.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by NotJuba** [comment]
Fair enough
