### ISSUE TITLE
OBS will crash when you're to change fonts with code c0000005

### ISSUE THREAD

**Issue by HotoRas** [obsproject/obs-studio#9802]
### Operating System Info

Other

### Other OS

Windows 11 22H2 x64, build 22621.2428 (10.0.22621.2428)

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/rdhPtdwM2pZcuQQc

### OBS Studio Crash Log URL

https://obsproject.com/logs/ybFqYr6nTMprrniu

### Expected Behavior

The font changing management screen should open.

### Current Behavior

Font management screen doesn't open but crashes.

### Steps to Reproduce

1. Create new `Text (GDI)` source.
2. Open `Change fonts` or whatsover have the same effect.
3. OBS will crash.

**Comment by Fenrirthviti** [comment]
I am unable to reproduce this on 30 RC2, can you test there as well?

Also, do you have any custom fonts installed?

**Comment by HotoRas** [comment]
> I am unable to reproduce this on 30 RC2, can you test there as well?

It shows as expected- closing issue. Thanks!
