### ISSUE TITLE
DXGI gives a black screen

### ISSUE THREAD

**Issue by timelessnesses** [obsproject/obs-studio#9804]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/aOitGwYTMOQei0vD

### Expected Behavior

DXGI Desktop Duplication in Display Capture should show the current display that is recording

### Current Behavior

DXGI Desktop Duplication gives black screen as an output

### Steps to Reproduce

1. Add "Display Capture" to the scene
2. Change "Capture Method" from Automatic to DXGI Desktop Duplication

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by timelessnesses** [comment]
> This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.
> 
> Thank you!

ah thanks!
