### ISSUE TITLE
Stats dock may report wrong amount of free space

### ISSUE THREAD

**Issue by JacksonChen666** [obsproject/obs-studio#9810]
### Operating System Info

macOS 14

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/fnzG1p9vOyUiW2cH

### Expected Behavior

I expected OBS to use the free space reported by Finder/Disk utility (the actual free space), which would say that there is actually 44GB left.

### Current Behavior

OBS reports the free space without accounting for purgeable space, so values can be very low and give a false visual warning.

### Steps to Reproduce

1. Write some big useless file (`dd if=/dev/urandom bs=1M of=~/asdf`, interrupt before running out of free space (watch it by running `watch -n0 df -h /` in another terminal))
2. Make a time machine snapshot by running `tmutil localsnapshot /`
3. Delete that big useless file (`rm ~/asdf`)
4. Check OBS's counter
5. Compare that to the number by finder

### Anything else we should know?

The file and snapshot creation might not be 100% reliable for creating purgeable space, so if it doesn't work, try waiting for a bit after the second step.

Images:
![Finger Quick look on the macOS disk says 44,67 GB is available (35,45 GB purgeable).](https://github.com/obsproject/obs-studio/assets/50755746/b45fab5f-6aee-44b8-ae40-f7c0a7199e03)
![OBS reports 8.6 GB of free space](https://github.com/obsproject/obs-studio/assets/50755746/3448247e-9774-45d7-8a8f-14f8ca4b2d1e)

**Comment by tt2468** [comment]
OBS just uses the unix `statvfs()` function to calculate available disk space. Arguably, this is working as intended. In theory, a dedicated platform function could be added to the Cocoa implementation to account for this "purgeable" disk space: https://developer.apple.com/documentation/foundation/nsfilemanager/1411896-attributesoffilesystemforpath
