### ISSUE TITLE
OBS freezes after nearly 50 days of uptime

### ISSUE THREAD

**Issue by michaeltoohig** [obsproject/obs-studio#9823]
### Operating System Info

Windows 10

### OBS Studio Version

Other

### OBS Studio Version (Other)

28.1.1

### OBS Studio Log URL

https://obsproject.com/logs/w6VjkTI4CKhakVBX
https://obsproject.com/logs/5fvhrP8NzJrjm7Xb

### Expected Behavior

OBS to continue operating normally without freezing.

### Current Behavior

After just short of 50 days (roughly 1192 hours) of uptime OBS freezes and must be restarted.

### Steps to Reproduce

1. Start OBS
2. Play videos
3. Wait...
...

### Anything else we should know?

I had two separate instances of OBS on two different machines this morning frozen with the same uptime of 50 days on each machine. My monitoring shows both froze at roughly the same time.

**Comment by Fenrirthviti** [comment]
OBS 28.1.1 and the version in the log file (29.0.2) are both outdated, and no longer supported.

If this can be reproduce on a current build, we likely need a memory dump while the process is frozen to determine what might be causing this.

**Comment by michaeltoohig** [comment]
I have a 3rd dedicated machine running videos this time only via VLC. I just checked and it was frozen too about the same time as the others. All three machines have 50 days of uptime so the problem must have been VLC not OBS.

**Comment by Fenrirthviti** [comment]
Closing per above.
