### ISSUE TITLE
Graphical Artifacts In Audio Mixer on Wayland

### ISSUE THREAD

**Issue by 5p4r74cu5** [obsproject/obs-studio#9824]
### Operating System Info

Other

### Other OS

Debian 12

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/7S6BFdLcL6LyNhn7

### Expected Behavior

No visual artifacts.

### Current Behavior

There are minor visual artifacts in the levels of the audio mixer, in this screenshot they are visible as red, and change colours, white, blue, etc. Some time the artifacting is worse, but generally the meters are clear enough to be usable.

![Screenshot_20231108_154256](https://github.com/obsproject/obs-studio/assets/26020949/be85f19b-15b1-4e12-99d5-eff447658752)

### Steps to Reproduce

Install the OBS flatpak.

### Anything else we should know?

KDE Plasma v5.27.5 in Wayland session.

**Comment by kkartaltepe** [comment]
There is a minor rendering issue with the space between the meters where nothing is rendered. This means its usually transparent in modern renders and displays whatever is behind your obs.

**Comment by v4u6h4n** [comment]
Ah I see, makes sense.

**Comment by RytoEX** [comment]
Fixed by #10223

**Comment by 5p4r74cu5** [comment]
Thanks :-)
