### ISSUE TITLE
Artefacts everywhere on screen recording macOS Sonoma

### ISSUE THREAD

**Issue by benfrain** [obsproject/obs-studio#9829]
### Operating System Info

macOS 14

### OBS Studio Version

30.0.0-rc2

### OBS Studio Log URL

https://obsproject.com/logs/rDFk5aWBRmG3ujZF

### Expected Behavior

No visual artefacts on the recordings. 

### Current Behavior

Since installing macOS Sonoma, every recording gets lots of artefacts at random points. 

Was fine on 13.6, with 29.1.3.
Artefacts on 14.1, 14.1.1 with 29.1.3 and 30 rc2

<img width="1402" alt="image" src="https://github.com/obsproject/obs-studio/assets/1318466/09a66274-7f32-44ab-9ae5-830bcf80b6d5">

### Steps to Reproduce

1. make a screen recording for about a minute, maybe pause it a few times (unsure if pausing is relevant)
2. stop recording and play it back 

### Anything else we should know?

Here are the settings I have, they have been unchanged for months:

<img width="734" alt="image" src="https://github.com/obsproject/obs-studio/assets/1318466/e7625acd-99de-4b31-932d-e07d15747a69">

**Comment by PatTheMav** [comment]
The log shows encoder errors happening:

```
23:09:40.787: [VideoToolbox encoder]: Error in encoder callback: The operation couldn’t be completed. (OSStatus error -12912.)
```

The error code is a generic encoder error, which suggests encoder overload or running into memory limits, but it's entirely internal to VideoToolbox and there's really nothing we can do about it.

Apple is known to update the encoders via firmware updates shipped with macOS so I would expect any issue to be related to that.

Please report it to Apple via https://developer.apple.com/bug-reporting/, though you might need to provide a more consistent reproducer for that issue (I replicated your settings and was able to record fine on 14.1 without any encoder issues.

**Comment by benfrain** [comment]
Thanks @PatTheMav I’ll roll back to 13.6 and ensure it works as expected there. If it does I’ll message here to confirm and then close

**Comment by benfrain** [comment]
Having downgraded back to 13.6.1 I can confirm that everything is working as expected with no visual anomalies and exactly the same settings. Closing this as @PatTheMav has advised there is nothing that can be done here.

**Comment by Developer-Ecosystem-Engineering** [comment]
@benfrain Were you able to log a Feedback as @PatTheMav suggested? We'd love to reproduce this issue and understand whats at play! With the information that's been provided here in this issue, we aren't able to at the moment.

**Comment by benfrain** [comment]
@Developer-Ecosystem-Engineering  unfortunately not, I was up against it timewise and having clicked that link there was just too much friction to log anything with expedience (wall of text, log-in with Apple id etc). Sorry!

**Comment by rickykresslein** [comment]
I'm still having this issue on Sonoma 14.4. Anytime I close a window it stays on the screen, with boxes of the background showing over it when the mouse moves over it, just like in @benfrain's screenshot.Is this something that can't be fixed by OBS and has to be fixed on Apple's side?

**Comment by PatTheMav** [comment]
> I'm still having this issue on Sonoma 14.4. Anytime I close a window it stays on the screen, with boxes of the background showing over it when the mouse moves over it, just like in @benfrain's screenshot.Is this something that can't be fixed by OBS and has to be fixed on Apple's side?

Provide a feedback to Apple per the request in https://github.com/obsproject/obs-studio/issues/9829#issuecomment-1808701039.

**Comment by benfrain** [comment]
Well, I’ve found that by changing some settings in OBS the problem can be fixed. I’ll list the settings I am now using in Sonoma that work later even at desktop
