### ISSUE TITLE
Fullscreen Applications freezes Elgato Camlink 4K video source

### ISSUE THREAD

**Issue by JayDee2202** [obsproject/obs-studio#9830]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/pCzr39qQaTDlDLtn

### Expected Behavior

No camera freezes while entering a fullscreen or a borderless windowed application

### Current Behavior

For a few weeks now, I have had the problem with my Camlink 4K and a connected Sony Alpha 5100 that the picture freezes when starting full-screen applications. The only thing that helps is restarting the source, i.e. switching it off completely (with the option Deactivate if the source is not displayed checked) and then on again. The problem also exists in frameless window mode, but not in pure window mode.

I currently have an ATEM Mini Pro here and have connected the camera to it as a test. The problem does not exist with this. Until a few weeks ago, the Camlink also always worked without any problems.
I have also tried all the different USB ports on the computer, but the problem persists there too and cannot be solved. There are no pending driver updates.
I only have the problem with freezes in OBS. If I open the camera app in Windows or use the camera in any other way, these problems do not occur. It doesn't matter whether I use hardware acceleration for the source or not.

I am currently also in contact with Elgato support, they don't know what to do at the moment either. However, as the problem only affects OBS, I wanted to open an issue about this as well.

### Steps to Reproduce

1. open OBS
2. use a scene which uses the Camlink 4K
3. open a game in fullscreen or borderless window
4. Camera freezes instantly. Only deactivating and reactivating the source via streamdeck/shortcut fixes this issue on the short term
5. After tabbing out of the game and tabbing back in the freeze occurs again.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
