### ISSUE TITLE
Output Encoder NVENC Fails to Use Nvidia API Default Settings, Risking Performance Failures for Users

### ISSUE THREAD

**Issue by LuminairPrime** [obsproject/obs-studio#9835]
### Expected Behavior

Settings -> Output:
Preset P4
Tuning Low Latency
Psycho Visual Tuning Off
Max B-frames Off

### Current Behavior

Settings -> Output:
Preset P5
Tuning High Quality
Psycho Visual Tuning On
Max B-frames 2

### Steps to Reproduce

1. Fresh install, or run Tools -> Auto-Configuration Wizard.

### Anything else we should know?

The goal of the video encoder is to reproduce the original video stream at as high a quality as possible. Frame rate is always prioritized over frame quality, so blocking is allowed to occur, but lost frames are not. Yet there are thousands of cases of people having performance failures with NVENC in OBS. [1]

A common misconception about the NVENC API is that it only uses the NVENC hardware encoding block on the GPU. Instead, many features use the same GPU cores (CUDA) as games use, thus reducing game performance or causing encoding failures. Nvidia recommends disabling certain NVENC settings to gain back GPU performance for games. [2] In the future these CUDA features could be exposed and named in the OBS GUI so users know what to disable to preserve encoder performance when the GPU cores are used for other applications.

To prevent these video encoder problems, Nvidia's NVENC API recommend modest visual quality settings for streamers. [3] As the developer of NVENC, Nvidia's recommendations should be heeded to reduce the number of users facing performance problems. Unfortunately the Preset feature doesn't change all features necessary to ensure a successful encode, so users of OBS must learn about several other features, further increasing the importance of OBS having safe defaults. OBS could also implement a new "all-in-one" quality/performance option which changes all of the relevant features.

Examples of Nvidia's default NVENC settings for streamers which OBS deviates from such that users could have performance problems include:
- Preset P4
- Ultra-low latency or low latency Tuning Info
- No B Frames

Nvidia also notes that single pass rate control reduces video memory used.

Encoder operation and settings are complicated. Most users don't know how to manually configure an encoder, so it is very important that the default OBS settings are as safe as possible to prevent users from facing problems that they cannot solve.

Please see OBS Studio Ideas and Suggestions for a related feature request:
https://ideas.obsproject.com/posts/2432/nvidia-nvenc-all-in-one-quality-performance-option-which-combines-all-nvidia-recommendations

References:
1: https://www.nvidia.com/en-us/geforce/guides/broadcasting-guide/
2: https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fobsproject.com%2Fforum%2F+nvenc+frames
3: https://docs.nvidia.com/video-technologies/video-codec-sdk/12.1/nvenc-video-encoder-api-prog-guide/index.html#recommended-nvenc-settings

**Comment by Penwy** [comment]
Your first link recommends using simple mode, and if using advanced mode, to use P6, High quality, and 4 or 2 B-frames
Your second link recommends, for broadcasting, recommends High quality and B-frames.

Broadcasting is not a low latency use case.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by LuminairPrime** [comment]
> Your first link recommends using simple mode, and if using advanced mode, to use P6, High quality, and 4 or 2 B-frames

1) It's important for you to understand the difference between "default" and "recommended". The Nvidia API and OBS defaults must adhere to a stricter standard than what you'd recommend to a friend who already has the defaults working. The defaults are chosen for high compatibility with untrained users, maximizing total utility for all. Whereas Gerardo recommends lower-compatibility settings in the official guide for users who want to RISK causing a performance failure with the encoder to increase their frame quality. 

2) It's also very important for you to understand the difference between frame visual quality and VIDEO visual quality. The framerate is an attribute of the VIDEO and cannot be allowed to fail, which is why video encoders sacrifice FRAME quality to maintain the FRAMERATE. But other software on the system shares hardware resources, so unfortunately we can't just ship OBS with all encoder settings maxed. OBS defaults ARE set below maximum for increased compatibility, they're just set higher than recommended in the NVENC API, thus the preventable complaints by users on the forum, and thusly this bug report. 

> Your third link recommends, for broadcasting, High quality and B-frames.

Nvidia's NVENC API refers to streaming as "streaming", not broadcasting. Broadcasting is non-interactive and implies less system hardware performance on the machine, thus the higher frame quality settings. That's totally different than the streaming most people do with OBS, and totally different than the single PC use of OBS that most people use. Just to reiterate: the NVENC API will use system resources BEYOND the NVENC encoder block if allowed, causing performance problems in some configurations, thus the high-compatibility settings recommended for streaming in the NVENC API documentation.

**Comment by LuminairPrime** [comment]
> This sounds more likely to be a support request rather than a bug report

I'm sorry if I confused you. My OBS works. The bug is that OBS is using Nvidia's API in a manner not recommended in the API documentation. Would it help you if I took screenshots of the API documentation so you don't have to read the whole thing?
