### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by BinKot** [obsproject/obs-studio#9836]
### Operating System Info

macOS 12

### OBS Studio Version

29.1.3

### OBS Studio Log URL

?

### Expected Behavior

I use it on zoom i was ok

### Current Behavior

Afterr 10 minutes it crash and now i can't chose obs in web cams

### Steps to Reproduce

1.zoom meetting

### Anything else we should know?

I can't pdate i have intel mac.

**Comment by BinKot** [comment]
in chrome it is working, but in another apps no(my browser is arc) In Arc too(

**Comment by BinKot** [comment]
I can send sreenshots

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
