### ISSUE TITLE
obs recording only audio on fedora kde

### ISSUE THREAD

**Issue by A53o** [obsproject/obs-studio#9837]
### Operating System Info

Other

### Other OS

fedora Linux KDE desktop

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/qXdDOTxhzAYmaVMN

### Expected Behavior

Export MKV video with video and audio tracks

### Current Behavior

When I record minecraft or any other game, obs only records audio. The game on the preview shows but the video only comes out as an audio track when I put the video into an editing software, and if I open the video with a media player it says "cannot play video.mkv"

### Steps to Reproduce

1. Start recording 
2. Stop recording 
3. Put Video file in editing software 

### Anything else we should know?

This hasn't happened before to me I am on the same operating system that I was on before but recently I had to reset my computer and so I had to reinstall everything and now obs is like this I think it might be a problem with ffmpeg but idk

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
