### ISSUE TITLE
Switching between scene collections causes OBS to crash.

### ISSUE THREAD

**Issue by GregSaintJean** [obsproject/obs-studio#9839]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/xXn5bojdh5S6fBwu

### Expected Behavior

When I go to "scene collection" menu and change the scene set I want to use, it should change the scene set in OBS without crashing.

### Current Behavior

When I go to "scene collection" menu and change the scene set I want to use, it crashes

### Steps to Reproduce

1. Make sure more than one scene collection is in OBS.
2. Go to the "scene collection" menu.
3. Try to select another scene collection other than the one you are using.

**Comment by Fenrirthviti** [comment]
Please provide the crash log.

**Comment by GregSaintJean** [comment]
> Please provide the crash log.

No crash log comes up. OBS just exits.

**Comment by Fenrirthviti** [comment]
Do you have a dock/browser source from Kick added to OBS anywhere?

**Comment by GregSaintJean** [comment]
Not from Kick specifically. I don't stream from Kick. I have a variety of browser sources. One from Twitch, one from socialstream.ninja, and one from streamlabs.

**Comment by Fenrirthviti** [comment]
Thanks, we're aware of a specific issue with Kick where their browser pages call an exit on OBS when closed, which they haven't seemed interested in fixing. I haven't heard of any other issues with Twitch or Streamlabs pages. I'm not familiar if Socialstream might have the same thing, but given how popular things like vdo.ninja are I'm sure we'd have heard more reports.

Can you trigger the issue, reopen OBS, and then upload LAST log and link it here?

**Comment by GregSaintJean** [comment]
https://obsproject.com/logs/ug1itQSwextndYSH

**Comment by Fenrirthviti** [comment]
Thanks. Can you test on the recently released OBS 30 as well? I don't expect this to be fixed, but there's always a small chance other dependency updates might have improved things.

The log seems to just completely cut off, which indicates something external to OBS is causing the process to forcibly quit. I see you have some third-party AV software installed, which might be killing the process as it writes out data on a collection switch as a wild guess.

Past that, I am not sure where to proceed as OBS itself isn't logging anything useful. I'll have to defer to other members of the team if they have any ideas on what we can do here.

It may help if you can zip up your scene collections and send them to us (privately, Discord is typically best for that) so we can see if we can replicate with your scene collection and identify the cause.

**Comment by GregSaintJean** [comment]
I can do that. I can also provide a list of all the plugins installed on OBS. Please let me know and I will provide that too.

**Comment by GregSaintJean** [comment]
Which channel in discord should I re-engage this conversation? Or is there someone I should mention or DM in discord to re-engage the conversation?

**Comment by Fenrirthviti** [comment]
You can ping me (Fenrir) in the OBS discord, and can go from there. The log file shows plugins, and there's definitely the possibility this is being caused by a third-party plugin and not OBS itself as well.

**Comment by GregSaintJean** [comment]
Finally, should I close this issue or leave it open?

**Comment by Fenrirthviti** [comment]
Since we don't know what is causing this yet, it can remain open.

**Comment by GregSaintJean** [comment]
> You can ping me (Fenrir) in the OBS discord, and can go from there. The log file shows plugins, and there's definitely the possibility this is being caused by a third-party plugin and not OBS itself as well.

I confirmed that the crash/exit is caused by a third party plug-in I installed. Thank you @Fenrirthviti
