### ISSUE TITLE
Linux/Flatpak: NVENC is unusable in old NVIDIA GPUs

### ISSUE THREAD

**Issue by guihkx** [obsproject/obs-studio#9847]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

30.0.0

### OBS Studio Log URL

https://obsproject.com/logs/P8LktBKTCOrlZ1xR

### Expected Behavior

I wish that NVENC was usable on my old (yet still supported, I think) NVIDIA GPU - a GTX 660 (Kepler).

### Current Behavior

NVENC H264 only fails here because OBS ships version 12.x of [ffmpeg's NVIDIA codec headers](https://github.com/FFmpeg/nv-codec-headers).

Here's what I get in the terminal output after I try to record locally:

```
[h264_nvenc @ 0x559c0662ffc0] Driver does not support the required nvenc API version. Required: 12.0 Found: 11.1
[h264_nvenc @ 0x559c0662ffc0] The minimum required Nvidia driver for nvenc is 520.56.06 or newer
```

And this is what shows up on OBS:

![image](https://github.com/obsproject/obs-studio/assets/626206/bd0c88cf-1c43-479f-98a4-5398a6c05c54)

### Steps to Reproduce

Make sure that you have an old NVIDIA GPU (e.g. Kepler) *and* that you're using the Flatpak package.

1. Enable NVENC encoding
2. Try to start recording

### Anything else we should know?

I made a local Flatpak build of OBS with nv-codec-headers downgraded to version 11.x, and now recording obviously works:

![image](https://github.com/obsproject/obs-studio/assets/626206/5272f92c-a06c-4a27-aa17-07088ccfa6f3)

However, I'm not sure about the full implications of doing that. For example, will owners of newer NVIDIA GPUs get an inferior recording quality after that? But if maintainers think there are no downsides to this, I can gladly send a pull request.

Thanks!

**Comment by tytan652** [comment]
Nvidia has dropped support for 470 series drivers in their latest codec headers.
And to be able to use Nvidia newest/recent NVENC features, using their latest headers is a requirement.
