### ISSUE TITLE
Browser Docks Missing in Linux

### ISSUE THREAD

**Issue by Manokii** [obsproject/obs-studio#9848]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

30.0.0

### OBS Studio Log URL

https://obsproject.com/logs/BVcOGen9IDQlGlaO

### Expected Behavior

Browser Docks should be visible in Docks Menu

### Current Behavior

It doesn't show Browser Docks

### Steps to Reproduce

1. Open the obs-studio
2. Open Docks in menu

### Anything else we should know?

Browser docks were gone after upgrading from `29.1.3` -> `30.0.0`

![image](https://github.com/obsproject/obs-studio/assets/49423729/134dbd42-a41c-444f-9846-1432fb0ab9f3)

**Comment by derrod** [comment]
Browser docks are unsupported on Wayland, additionally, you're running a third-party build that does not seem to include `obs-browser` in the first place.
