### ISSUE TITLE
Monitoring audio do not respect audio delay

### ISSUE THREAD

**Issue by gavalierm** [obsproject/obs-studio#9849]
### Operating System Info

Windows 11

### OBS Studio Version

29.1.3

### OBS Studio Log URL

-

### Expected Behavior

Audio A delay 1000ms via advanced mixer settings (audio has 0ms input latecny)
Audio B delay 500ms via advanced mixer settings (audio has 500ms input latency)
Video A delay 1000ms via video dealay async plugin (video has 0ms input latency, same as audio A)

Output is OK - synced.
Monitoring is BAD - not synced - audio A is 1000ms before video, audio B is 500ms before video.

I try to sync audio(variable from 0-1000ms) and video(1000ms) to match high latency audio sources. 

### Current Behavior

Audio at delay 1000ms
Video via async plugin at 1000ms

Output is OK - synced.
Monitoring is BAD - not synced - audio is before video.

### Steps to Reproduce

1. input source: BM card with video and audio which is synced at the source as source A
2. second audio source: Something which is way way more behind the source A... as source B
3. add video async delay to the source A 1000ms
4. add audio delay 1000ms to audio from source A
5. add audio delay XYms (to match audio A) to audio source B

Recording/stream is synced.
Monitoring/listening with phones direct from OBS is not synced.

### Anything else we should know?

I think this is feature, to monitor "audio sources" as soon as possible - like "cue/aux/hearing my self" but for monitoring "final output" as last check point is not useable when is not synced.

For me i will find to great to have "output monitoring" option without any futher settings or parameters...

**Comment by Fenrirthviti** [comment]
This is not a bug, as this is currently by design that monitoring is pre-filter/fader. We are aware of the use cases a master mix would allow. You can show your support for the feature further by upvoting here:

<https://ideas.obsproject.com/posts/170/output-volume-visualization-master-mix>
