### ISSUE TITLE
why installer fail for discord and microsoft teams ??

### ISSUE THREAD

**Issue by markonop93** [obsproject/obs-studio#9851]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.0

### OBS Studio Log URL

http://nolog.com

### Expected Behavior

obs studio install shall not fail if discord and microsoft teams are open

### Current Behavior

it fail and wait to close

### Steps to Reproduce

1. install with discord or microsoft team open
2. see error message

**Comment by ArgoKhoth** [comment]
When you install OBS Studio, and you have those open it should tell you it cannot install and all you have to do is close the programs, and also close them from the system tray. If for some reason you do this, and it is still there just open task manager and close Discord and Teams from there. With those programs closed, it should install fine and then you can reopen them.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by Fenrirthviti** [comment]
For further clarification, we only request applications to be closed if they are using files from OBS which means we cannot update them. For your case, something in those applications was accessing files OBS needed to update, and they had to be closed before it could continue. We don't have a list of applications that must be closed, it is based on what applications are accessing OBS at the time.

For further assistance, please use our Discord or forums, as mentioned above.
