### ISSUE TITLE
OBS Maximizing to wrong monitor

### ISSUE THREAD

**Issue by ErueWoad** [obsproject/obs-studio#9852]
### Operating System Info

Windows 10

### OBS Studio Version

30.0.0

### OBS Studio Log URL

https://obsproject.com/logs/UcOgaMZGRqRnZaNb

### Expected Behavior

OBS Studio when clicked on from the task bar will be opened on the same monitor it was on before being minimized or alt tabbed.

### Current Behavior

OBS Studio is defaulting to same monitor when clicked on from the task bar, despite being repeatedly dragged and maximized to another monitor 

### Steps to Reproduce

1.Open OBS
2.Move to another monitor and maximize
3.Minimize OBS
4.Click OBS on task bar
...

**Comment by WizardCM** [comment]
I am also on Windows 10 and not experiencing this. Please try in safe mode (Help -> Safe Mode)

**Comment by ErueWoad** [comment]
So I restarted my computer and it seems to have fixed itself.
