### ISSUE TITLE
CTRL+V and SCROLL is not working in browser

### ISSUE THREAD

**Issue by hamidhtc** [obsproject/obs-studio#9862]
### Operating System Info

Windows 10

### OBS Studio Version

30.0.0

### OBS Studio Log URL

https://obsproject.com/logs/Gb7QjlLtQbF2HIBp

### Expected Behavior

i want login in a website and recording it. but for login CTRL+V is not working in password section and my password is made with bitwarden and its too long for typing.

also scroll is not working for some sites

### Current Behavior

in some websites CTRL+V and scroll is not working in obs browser.
like this site: 
https ://ddn.csdiran.ir/auth/login

### Steps to Reproduce

1. add browser in obs
2. set this url for browser: https :// ddn.csdiran.ir/auth/login
3. then click interact and try scroll page or ctrl+v in password section.

**Comment by gxalpha** [comment]
Could you confirm whether this is new to OBS 30.0.0 or if this also happened in 29.1.3?

**Comment by RytoEX** [comment]
I cannot reproduce this on Windows trying to log into a Google Account. I can paste characters into the password field just fine. Perhaps Bitwarden is preventing you from pasting the password.

**Comment by hamidhtc** [comment]
> Could you confirm whether this is new to OBS 30.0.0 or if this also happened in 29.1.3?

yes. this also happened in previous versions

> I cannot reproduce this on Windows trying to log into a Google Account. I can paste characters into the password field just fine. Perhaps Bitwarden is preventing you from pasting the password.

try to login and scrolling in this site: https://ddn.csdiran.ir/auth/login
in google site there is not problem.

**Comment by Fenrirthviti** [comment]
This sounds like an issue with that specific website, I suggest reaching out to them for more assistance, as we don't have control over the content. All other websites I've tested are working fine.
