### ISSUE TITLE
Virtual Camera on OBS 30 on MacOS consuming 40% CPU

### ISSUE THREAD

**Issue by ben-gineer** [obsproject/obs-studio#9864]
### Operating System Info

macOS 13

### OBS Studio Version

30.0.0

### OBS Studio Log URL

https://obsproject.com/logs/JNiFtFBeGtaAzKqu

### Expected Behavior

I don't expect the CPU to run at 40%, which causes the fan to run continuously

### Current Behavior

The CPU runs at 40%, and the fan continuously runs. This didn't happen with OBS 29.

Including spindump too.

[Spindump.txt](https://github.com/obsproject/obs-studio/files/13362374/Spindump.txt)

### Steps to Reproduce

1. Start OBS
2. Start Virtual Camera
3.
...

**Comment by PatTheMav** [comment]
Is this 40% in OBS or 40% in activity display? Also for which process?

**Comment by ben-gineer** [comment]
This is 40% for OBS Studio within Activity display:
<img width="764" alt="Screenshot 2023-11-15 at 13 32 44" src="https://github.com/obsproject/obs-studio/assets/4173590/e087710c-95bd-4463-a85f-4501464f8a34">

**Comment by RytoEX** [comment]
Was fixed by #10049.
