### ISSUE TITLE
Virtual Camera adds visible latency

### ISSUE THREAD

**Issue by hofst** [obsproject/obs-studio#9865]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.0

### OBS Studio Log URL

https://obsproject.com/logs/0Z03M7OCEOlbyvtK

### Expected Behavior

When using the virtual camera, there is a visible delay in the picture (~300ms).
I tested in on multiple very beefy workstations but the problem persists.
I also tried an alternative solution via NDI webcam which shows no visible latency. So this performance problem is really inherent to the OBS virtual camera and can be fixed.

### Current Behavior

See expected behavior.

### Steps to Reproduce

Use OBS Virtual Camera with a full hd output in any software. Observe significant visible delay between the preview and the receiving software.

### Anything else we should know?

This is a performance problem. Likely, the implementation can be significantly optimized. Likely, the optimization would also reduce cpu consumption which others users reported as a problem.
This is not a problem with my hardware. I tested it on multiple very beefy workstations (20core CPUs, 128GB RAM, Nvidia RTX 3070) and the problem persists. Also, I verified that the problem does not occur when I grab the OBS output via NDI Webcam, so it really is a performance problem in OBS Virtual Camera.

**Comment by Fenrirthviti** [comment]
I have tested and I am not able to reproduce. There is no visible latency when using the virtualcam in Discord, Google Meet, or Zoom. This will need more complete replication steps.

**Comment by hofst** [comment]
@Fenrirthviti Intersting, thank you for jumping in.
To double-check:
- Did you use a full-hd 1920x1080 video output?
- Did you open the OBS preview window and gmeet simultaneously and moved your hand to check the delay? 

If the answer to both answers is yes I can upload a screen capture to show the situation on my machines so we can compare it. It the situation is indeed better on your system, I will be very interested to find out why.

**Comment by Fenrirthviti** [comment]
Yes to both. A video doesn't help much, I don't doubt that this is happening on your system, just reporting that I am not able to replicate. We will need more information before being able to properly investigate, assuming this is even something we can fix on our end. Do you have another PC you can test on to see if the same issue occurs?

**Comment by hofst** [comment]
Hmm, I just tried reproducing the problem again but failed to do so (on both of my workstations). I will close the issue for now. Still, thank you for your time!
