### ISSUE TITLE
Quicksync does not work in flatpak

### ISSUE THREAD

**Issue by 46620** [obsproject/obs-studio#9867]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

30.0.0

### OBS Studio Version (Other)

flatpak

### OBS Studio Log URL

https://obsproject.com/logs/CLynycsEwa0q92E9

### Expected Behavior

Record/stream using quicksync

### Current Behavior

Starting the output failed. Please check the log for details

Note: If you are using the NVENC or AMD encoders, make sure your video driers are up to date.

### Steps to Reproduce

1. Install OBS via flatpak
2. Select any quicksync option
3. Press record or Start Streaming

### Anything else we should know?

I am able to record with quicksync when using obs-studio from the arch repos, but it seems to throw errors in flatpak. This is a very fresh install of Arch with the following being installed for intel drivers. `intel-gmmlib intel-media-driver onevpl-intel-gpu`

If you need any other logs lmk and I will try to get them as soon as I can.

**Comment by tytan652** [comment]
The Flatpak relies on Freedesktop 22.08 runtime which does not provide support for Arc GPUs encoding, this will hopefully be fixed in the future by switching to a Freedesktop 23.08 runtime.
