### ISSUE TITLE
OBS Studio cannot start on version 30.0

### ISSUE THREAD

**Issue by Pure-Fox** [obsproject/obs-studio#9869]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.0

### OBS Studio Log URL

https://obsproject.com/logs/c7j4ZKk3IqHHviLA

### Expected Behavior

OBS Studio 30.0 to start normally.

### Current Behavior

Shows Error "Failed to Initialize video. Your GPU May not be supported, or your graphics drivers may need to be updated".

### Steps to Reproduce

1. Updated to Version 30.0
2. Start OBS studio

### Anything else we should know?

- DDU and reverting the driver version back (Nvidia driver 537.58) or installing the latest driver (Nvidia driver 546.01) does not solve the issue.
- Reverting the OBS Studio version back to 29.1.3 fixes the problem, the log is as follows: https://obsproject.com/logs/OgnSR8t4AzpmlmFb or https://obsproject.com/logs/h40KBrQfYMIeoyK3

**Comment by notr1ch** [comment]
Can you check `C:\Windows\System32` and show which `D3DCompiler_XX.dll` files you have?

**Comment by Pure-Fox** [comment]
Looks like I have a bunch of them, D3DCompiler_33 to 43 and D3DCompiler_47.

**Comment by notr1ch** [comment]
Could you share the `D3DCompiler_47.dll`?

**Comment by Pure-Fox** [comment]
[D3DCompiler_47.zip](https://github.com/obsproject/obs-studio/files/13368565/D3DCompiler_47.zip)

**Comment by notr1ch** [comment]
Thanks, could you also share the contents of `C:\ProgramData\obs-studio\shader-cache`? Deleting this after sharing may resolve the problem.

**Comment by Pure-Fox** [comment]
[shader-cache.zip](https://github.com/obsproject/obs-studio/files/13368625/shader-cache.zip)
It does look like the old shader cache was causing the issue, and deleting those makes 30.0.0 operational again.

**Comment by notr1ch** [comment]
It looks like the cache files are the correct size of a compiled HLSL program but the contents are gone, very weird. Did you experience any PC crashes / hard resets recently that might have caused filesystem corruption?

**Comment by Pure-Fox** [comment]
I think so, had some hard reset recently. It is kinda weird how the shader file corruption only affect 30.0.0 though

**Comment by notr1ch** [comment]
The shader cache is a new feature in v30. Looks like we will have to add some additional checks to make sure the files aren't corrupt.
