### ISSUE TITLE
bug that has been occuring on all public versions of macos 14 (sonoma)~ 14.0, 14.1 & 14.1.1, where the menu bar title glitches from "OBS" -> "OBS Studio" as soon as you do something else in another app and click back on obs.

### ISSUE THREAD

**Issue by AIDaN80112** [obsproject/obs-studio#9871]
### Operating System Info

macOS 14

### OBS Studio Version

30.0.0

### OBS Studio Log URL

https://obsproject.com/logs/XlwIpw2lVqjOoZc4

### Expected Behavior

App name to remain "OBS" at all times

### Current Behavior

App name in menu bar title glitches from "OBS" -> "OBS Studio" as soon as you do something else in another app and click back on obs. 

### Steps to Reproduce

1. launch obs
2. do something in another app (not just clicking a button, changing the actual app to display something else like searching something in a browser)
3. go back to obs

### Anything else we should know?

[VIDEO OF ISSUE OCCURING](https://youtu.be/zDU3HlJUTpw) (was too big to upload here so thats why its a yt link)

**Comment by PatTheMav** [comment]
While I was able to observe this behaviour on macOS 14.1, I haven't seen it in macOS 13.5.

What is being displayed is influenced by the `CFBundleName` and `CFBundleDisplayName` in the `Info.plist` of the bundle - in version 29 those were identical, in version 30 we treated them differently, but that seems to lead to the observed behaviour.

I guess it should be fine to align both values again.

**Comment by bdash** [comment]
We saw this same issue in Google Chrome and believe it has been fixed in the most recent macOS 14.2 beta.

**Comment by PatTheMav** [comment]
> We saw this same issue in Google Chrome and believe it has been fixed in the most recent macOS 14.2 beta.

Good to know - "OBS Studio" is our `CFBundleDisplayName`, but iirc only `CFBundleName` is used for menu bar, dock icon, task switcher, etc.
