### ISSUE TITLE
Crash: OBS won't close if YouTube stream still running

### ISSUE THREAD

**Issue by rasamassen** [obsproject/obs-studio#9872]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.0

### OBS Studio Log URL

https://obsproject.com/logs/Om1C1a0vpYrRqetX

### OBS Studio Crash Log URL

https://obsproject.com/logs/n2NE1NYTjWz9yo7F

### Expected Behavior

OBS to close down properly.

### Current Behavior

OBS did not close down properly. The window closed, but the icon remained in the toolbar dock and the task remained active in task manager. When trying to reopen OBS, it complained because an instance was already running, and upon ignoring the complaint is when the crash officially happened. The crash file may only reflect the double-instance issue, but I loaded in in case it shows the issue with OBS not shutting down properly in the first place.

### Steps to Reproduce

1. Using YouTube to stream, Controls Panel => Manage Broadcast => Create Broadcast and Start Streaming
2. Close OBS. Click "Yes" when it complains that you're still streaming.
3. OBS window closes. Icon remains in taskbar with red streaming dot and exe file still running in task manager, no matter how long you wait.

### Anything else we should know?

Sometimes we have to close OBS when a source wasn't started properly before OBS was turned on, or became disconnected for random reasons (especially webcams - they love to disconnect). Usually this is only when we're testing, and not in a live setup, but our site is a church and the people running the AV setup are not necessarily experts, so often the easiest instruction we can give them is "restart OBS" and see if that fixes it.

Yes, I just updated to the latest release, 30.0.0 official, just to make sure this was showing up post-beta.

**Comment by rasamassen** [comment]
It turns out Killer Control Center was the problem. When that was uninstalled from the computer, OBS operated smoothly and shutdown correctly. As OBS already recommends uninstalling this program, I'm assuming this issue falls into the "Won't Fix" category.

**Comment by Fenrirthviti** [comment]
Unfortunately, this is correct. Killer Network injects itself in to places it shouldn't be. There isn't anything we can do about it, as they mess with system drivers and other places OBS has no place being. We strongly recommend avoiding anything from Killer.
