### ISSUE TITLE
I can no longer record with QuickSync H.264

### ISSUE THREAD

**Issue by swordcube** [obsproject/obs-studio#9873]
### Operating System Info

Windows 10

### OBS Studio Version

30.0.0

### OBS Studio Log URL

https://obsproject.com/logs/sNgKA3IFjSfhqM9W

### Expected Behavior

The recording starts with no errors.

### Current Behavior

The following error pops up instead of the recording starting.

![image](https://github.com/obsproject/obs-studio/assets/49110074/0195ef0f-068e-401a-a897-739e794ffe6a)

Only this encoder seems to be completely broken, as x264 is completely normal, and the other remaining encoders refuse to continue encoding randomly while recording.

This issue has only started occuring on 30.0.0, the previous version before this worked fine.

### Steps to Reproduce

1. Switch video encoder to Hardware (QSV, H.264) (on Basic Mode) or QuickSync H.264 (on Advanced Mode)
2. Start recording a video, error occurs then.

### Anything else we should know?

CPU: Intel Core i5-3230M @ 2.60GHz, 2601 Mhz, 2 cores, 4 Logical Processors
GPU: Intel HD Graphics (Integrated)

**Comment by Fenrirthviti** [comment]
Unfortunately, CPUs older than Broadwell are no longer supported by Intel or in versions of OBS 30+

**Comment by wilsontulus** [comment]
> Unfortunately, CPUs older than Broadwell are no longer supported by Intel or in versions of OBS 30+

The problem is: I don't see anything related to "OBS 30 removed pre-Skylake QSV support" in the changelogs. The only 
closest thing i saw is "Removed D3D9 QSV plugin" which AFAIK only applies to Sandy Bridge that lacks Direct3D11 support.

This is basically like treating pre-Skylake Intel GPUs like if it's Windows 7 and 8. Intel HD 4600 is still able to record 1080p30, or even 1080p60 if there's not a lot of motion.

**Comment by Fenrirthviti** [comment]
We didn't remove it, Intel did.

**Comment by wsy** [comment]
Indeed, IvyBridge platforms are too old to be supported. But it would be nice to include a "minimal hardware spec" in the release note.
If there were something like "IntelQSV requires Nth gen Intel Core processor" in the release note when I upgrade my OBS to 30.x, I would not have spend half an hour trying to restart my computer, uninstall and reinstall softwares, reinstall Intel graphic driver, analyze the log, etc.

**Comment by wilsontulus** [comment]
![image](https://github.com/obsproject/obs-studio/assets/54766538/4aaa9bd8-baeb-4cba-a111-c766c4879177)

The clarification is actually there in the OBS's own check for updates popup, just you need to scroll it down a bit. Still, the clarification isn't there in Github Release's release notes, neither the "News" page of the obsproject site.
The Gen7.x intel graphics at this point is very close to the true end already, and like any other sane developers including OBS - they have to focus more on latest hardware demands than the older ones.

Even in the future when OBS 29 shows it's age, at least OBS 29 can still be used for recording. At least if Microsoft will definitely not going to think about blocking older OBS versions like what they did with older version of VMware and Legacy Broadcom Drivers.
