### ISSUE TITLE
Cannot remux more files after finishing a remux task until restarting OBS

### ISSUE THREAD

**Issue by Ulexos** [obsproject/obs-studio#9878]
### Operating System Info

Windows 10

### OBS Studio Version

30.0.0

### OBS Studio Log URL

not required

### Expected Behavior

After finishing a remux task one can add more files via the empty cell with the [...] option

![image](https://github.com/obsproject/obs-studio/assets/16191795/e5e39ef3-86e7-48db-9472-5fe4f6e5670a)

### Current Behavior

Finishing one remux task removes the empty cell with the [...] option to add more files to remux them.
Reopening the remux window does not re-add the empty cell with the [...] option.

![MissingCell](https://github.com/obsproject/obs-studio/assets/16191795/818ab87e-c2d1-4145-a373-3f0ed87f7d3e)

### Steps to Reproduce

1. Open remux window
2. Add file via "[...]"
3. Click remux (the empty cell with the [...] option disappears)
4. There no longer is an empty cell with the [...] option to add further remux tasks

**Comment by RytoEX** [comment]
Looks like this specifically regressed in OBS Studio 30.0.0-rc1 where we updated from Qt 6.5.2 to 6.5.3, so I'd think a change in Qt is the cause of this. It works fine in OBS Studio 30.0.0-beta3.

**Comment by LastofAvari** [comment]
Still an issue in OBS 30.0.2 (Windows 10 PRO 22H2). After initial remuxing of the recordings it is impossible to add any more. Clearing the queue doesn't help either. It just leaves a completely empty table with nothing at all.
![OBS Studio 30 0 2 - Remux List Glitch](https://github.com/obsproject/obs-studio/assets/88505203/ba8ccbe1-2921-4a94-9cc1-a72012b5ba9e)

**Comment by wardhale** [comment]
Still an issue... extremely frustrating. I have been remuxing outside of obs because of this.

![obswtf](https://github.com/obsproject/obs-studio/assets/33298961/026b669a-2465-4816-a6e4-3c7fd163de0a)
OBS 30.0.2
Windows 10 Version	10.0.19045 Build 19045
