### ISSUE TITLE
Start Recording fails with error message stating permission of out of disk space

### ISSUE THREAD

**Issue by pfranzek** [obsproject/obs-studio#9891]
### Operating System Info

Ubuntu 20.04

### OBS Studio Version

30.0.0

### OBS Studio Version (Other)

snap

### OBS Studio Log URL

https://obsproject.com/logs/tryZHtONZGaktLTi

### Expected Behavior

Recording started.

### Current Behavior

On first attempt, an error message popup indicating a permission problem or lack of disk space.
Second attempt results in a crash.
This occurred after the latest snap update. This error also occurred on the previous snap update in October.

Upon investigation it was found that the obs studio configuration was still pointing to the old snap location. The files containing erroneous configuration were as follows:
1. /snap/obs-studio/1292/.config/obs-studio/plugin_config/vertical-canvas/config.json
2. ./snap/obs-studio/1292/.config/obs-studio/global.ini
3. ./snap/obs-studio/1292/.config/obs-studio/basic/profiles/Service/basic.ini
4. ./snap/obs-studio/1292/.config/QtProject.conf

These files were corrected to point to the correct path and recording started as expected.

### Steps to Reproduce

1. After latest snap update - start obs studio
2. Select Start Recording
3.
...

### Anything else we should know?

Log files upload does not help since both the current and previous no longer contain any error trace.

**Comment by tytan652** [comment]
OBS Project is not the author of the Snap, please direct this issue to the Snap packagers.
