### ISSUE TITLE
VLC option default or OFF  / Qt5 or 6 option 

### ISSUE THREAD

**Issue by fungilife** [obsproject/obs-studio#9899]
### Operating System Info

Other

### Other OS

linux glibc

### OBS Studio Version

30.0.0

### OBS Studio Version (Other)

30.0.0rc1+58+g1a86ff551

### OBS Studio Log URL

https://termbin.com/mdfn

### Expected Behavior

Building behavior:
I am trying to build 30.0 stable release and noted 2 things after building 30.0.0rc1+58+g1a86ff551 last week or so

When I add VLC enable option it responds as it is off by default, when I take this option out building asks for libvlc

Up till 10 days ago when I last built the rc version I can turn Qt5 or 6 on/off, why is qt6 enforced now on the 30.0 release?

### Current Behavior

it doesn't build without Qt6 anymore

### Steps to Reproduce

    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DENABLE_BROWSER=OFF \
    -DCEF_ROOT_DIR="/opt/cef-obs" \
    -DENABLE_VST=ON \
    -DENABLE_VLC=OFF \
    -DENABLE_NEW_MPEGTS_OUTPUT=OFF \
    -DENABLE_AJA=OFF \
    -DENABLE_JACK=ON \
    -DENABLE_ALSA=ON \
   -DENABLE_NEW_MPEGTS_OUTPUT=OFF \
    -DENABLE_LIBFDK=ON \
    -DENABLE_PIPEWIRE=FALSE \
    -DENABLE_PULSEAUDIO=FALSE \
    -DENABLE_WEBRTC=OFF \
    -DOBS_VERSION_OVERRIDE="$pkgver" \
    -Wno-dev

### Anything else we should know?

I really wish for Qt5 on Qt6 off

**Comment by fungilife** [comment]
small correction, as in the "reproduce steps" with VLC=off it says it is off by default, when the term is removed it looks for libvlc, with vlc=off ok, hence it is not default

**Comment by tytan652** [comment]
> why is qt6 enforced now on the 30.0 release?

We dropped Qt5 support as of 30
https://github.com/obsproject/obs-studio/releases/tag/30.0.0

The VLC plugin is enabled by default.
