### ISSUE TITLE
NVENC Not Present in Flatpak

### ISSUE THREAD

**Issue by M15071060** [obsproject/obs-studio#9902]
### Operating System Info

Other

### Other OS

Debian 12

### OBS Studio Version

30.0.0

### OBS Studio Log URL

https://obsproject.com/logs/R2OdFcIBXpJrLFvQ

### Expected Behavior

In the Encoder Selection, I am looking to select `NVIDIA NVENC H.265 (FFmpeg)`, as I am able to do in the Debian repository OBS (29.0.1.1-1+b1). 

### Current Behavior

In the Flatpak version, however, there is no option so it falls back to CPU only encoding.

I will also note that the reason for using the Flatpak version is that the Debian repository OBS does not have a `Browser Source` so I am unable to use it.

### Steps to Reproduce

Install OBS from Flathub
Settings > Output > Output Mode: Advanced > Encoder, try to select NVIDIA NVENC H.264

### Anything else we should know?

I apologize if it's something obvious I've missed, but I'm unable to rectify this after a few days of looking.

**Comment by tytan652** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for further assistance.  

Thank you!
