### ISSUE TITLE
"Incompatible Encoder" error on Linux with QuickSync HEVC and SRT

### ISSUE THREAD

**Issue by mikeful** [obsproject/obs-studio#9904]
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

30.0.0

### OBS Studio Log URL

https://obsproject.com/logs/CgOkwwDDrVM1Ezku

### Expected Behavior

Allow input of `srt://` address to custom stream destination "Server" address field with Intel QuickSync selected.

### Current Behavior

I currently get 'Incompatible Encoder: The streaming service "Custom..." does not support the encoder "QuickSync HEVC". The encoder will be changed to "x264". Do your want to continue?' error dialog when I input last slash charater of `srt://` into the address field.

If select any H264 encoder from output tab, I'm able to input SRT address to the custom destination field. Going back to output tab displays only "QuickSync H.264", "FFmpeg VAAPI H.264" and "x264" as available video encoders.

Recording QuickSync H264 and QuickSync HEVC to local file works as expected. I'm able input SRT address and stream QuickSync H264 as expected.

### Steps to Reproduce

1. Install Ubuntu 22.04
2. Add OBS PPA and install OBS
3. Install Intel graphics drivers with instructions from https://dgpu-docs.intel.com/driver/client/overview.html#client-intel-package-repository-configuration
4. Open OBS and go through setup steps
5. Skip streaming service selection
6. Go to settings
7. Select "QuickSync H.264" as video encoder and ensure local recording works
8. Select "QuickSync HEVC" as video encoder and ensure local recording works
9. Keep "QuickSync HEVC" as encoder and select "Custom..." streaming service in Stream tab
10. Start writing "srt://host.domain" to Server field
11. Error dialog should pop out

### Anything else we should know?

Attached log file contains short QuickSync HEVC recording session and attempt to input SRT address.

OBS 30.0 was installed via PPA and QuickSync drivers were with Intel [wiki instructions](https://dgpu-docs.intel.com/driver/client/overview.html#client-intel-package-repository-configuration).

This is on computer with Intel N100 chipset. I'm not using the PC for anything else and was it fresh install. I can test anything that might help on this.

I tried to read through the service encoder compatibility validation code here on Github but I can't see way it should cause this. Tried asking on Discord but I didn't see anyone else with this issue.

**Comment by tytan652** [comment]
Ubuntu 22.04 builds are made with the old SRT output implementation, this implementation is not marked to support HEVC.

**Comment by mikeful** [comment]
Which would be recommended way to get version with SRT support installed?

**Comment by tytan652** [comment]
You can try the Flatpak.
