### ISSUE TITLE
FaceTime/Sharing Icon in Mac Menu Bar Stuck

### ISSUE THREAD

**Issue by realtofuine** [obsproject/obs-studio#9906]
### Operating System Info

macOS 14

### OBS Studio Version

30.0.0

### OBS Studio Log URL

https://obsproject.com/logs/D8OI6RC4XjKXavoL

### Expected Behavior

When OBS is closed (completely quitted with Cmd+Q), the purple icon in the menu bar should disappear. However, the icon persists unless the system is rebooted.

The purple icon is show in the current behavior section.

### Current Behavior

![Screenshot 2023-11-22 at 3 26 52 PM](https://github.com/obsproject/obs-studio/assets/73127480/70d5e2d4-dfed-4810-a426-a632e457bc16)
This icon remains in the menu bar even when OBS is completely quit. When clicked, the following is shown:
![Screenshot 2023-11-22 at 3 27 32 PM](https://github.com/obsproject/obs-studio/assets/73127480/02574fb7-da44-4a67-b550-7c97a8015916)
Clicking on the left and right arrows also do not show anything.

### Steps to Reproduce

1. Open OBS
2. Observe that the purple sharing icon is in the menu bar.
3. Quit OBS with Cmd+Q.
4. Look in the menu bar and see that the icon is still there and will continue to stay there no matter what unless you completely restart the computer.

### Anything else we should know?

It's a real pesky purple icon.

**Comment by realtofuine** [comment]
A potential workaround is quitting the system process "Control Center," but the glyph will reappear every time OBS is relaunched.

This workaround was described in this thread:
[https://obsproject.com/forum/threads/obs-on-macos-14-%E2%80%9Csonoma%E2%80%9D.167331/post-630353](https://obsproject.com/forum/threads/obs-on-macos-14-%E2%80%9Csonoma%E2%80%9D.167331/post-630353)

**Comment by PatTheMav** [comment]
Issue is fixed on macOS 14.2. Nothing to be fixed on OBS’ side.

**Comment by Erik262** [comment]
Same here on latest macOS 14.1.2 and obs 30.0.2 very annoying...

**Comment by anitaposch** [comment]
> Issue is fixed on macOS 14.2. Nothing to be fixed on OBS’ side.

I'm on macOS 14.3 and the icon is still stuck after quitting OBS.

**Comment by jus-jus** [comment]
> Issue is fixed on macOS 14.2. Nothing to be fixed on OBS’ side.

I'm on macOS 14.4.1 and the issue persists
