### ISSUE TITLE
Trouble converting db from obs websocket to match obs slider

### ISSUE THREAD

**Issue by nospam2k** [obsproject/obs-studio#9908]
### Operating System Info

macOS 14

### OBS Studio Version

30.0.0

### OBS Studio Log URL

no log needed

### OBS Studio Crash Log URL

no crash needed

### Expected Behavior

I'm trying to figure out how to convert the db number into a linear number to pass to input range slider. If I set the slider range to -100 min and max 0 and step 1, the -100, 0 are fine but I cannot figure out how to convert the rest in between. I've read about 20 log(db) but that doesn't seem to work either. I know this isn't specifically a problem with OBS but I would really appreciate the help. I've been working on this for several days now and it doesn't seem it should be this hard. I have the sliders working and can get scenes, check for valid sources, etc. All that took about an hour. What am I missing?

### Current Behavior

Slider is linear and out of sync with OBS slider

### Steps to Reproduce

1.
2.
3.
...

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
