### ISSUE TITLE
OBS always activates Safe Mode after restarting Windows

### ISSUE THREAD

**Issue by DrGugl** [obsproject/obs-studio#9913]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.0

### OBS Studio Log URL

https://obsproject.com/logs/ksaj9GxjzFmBKbWu

### Expected Behavior

OBS starting normally after booting up Windows and starting the replay buffer.

### Current Behavior

Whenever Windows boots up I get a message from OBS telling me that the programme did not close correctly the last time. I have the option to start normally or start in safe mode. 

### Steps to Reproduce

1. Create a app shortcut to start OBS with replay buffer enabled automatically
2. Put shortcut into Windows auto start folder
3. Restart Windows
...

### Anything else we should know?

As mentioned above, I use a custom App shortcut for starting OBS so that it not only starts automatically with Windows but also automatically starts the replay Buffer. I want to minimize this process so that I can record Highlights with OBS without having to start anything manually. But know I always have to select the way OBS starts after each Boot. This problem also only occured after updating to 30.0.0

**Comment by tytan652** [comment]
Duplicates of #9877
