### ISSUE TITLE
Screen Capturing Behaves Unreliably with Magnification

### ISSUE THREAD

**Issue by ahmutkadim** [obsproject/obs-studio#9919]
### Operating System Info

macOS 13

### Other OS

null

### OBS Studio Version

30.0.0

### OBS Studio Version (Other)

null

### OBS Studio Log URL

null

### OBS Studio Crash Log URL

null

### Expected Behavior

I expect it to capture screen normally, as it is never magnified.

### Current Behavior

It captures the screen as zoomed, ignoring any other setting for screen capture.

### Steps to Reproduce

Firstly, I want to give some sub context to describe my issue. Due to eye problems, I use native macOS magnification to see the contents of the screen and would not like the video to be recorded as how I see my screen. 

1. Enable macOS magnification from system preferences -> accessibility
2. Set activation method to what you see fit, set magnification mode to "full screen" and set the magnification to follow cursor from advanced settings.
3. add screen capture to resources and enable preview in OBS
4. Enable magnification and look at the preview
...

### Anything else we should know?

I really need this to be fixed to use this software. I do not know whether it is an bug or intended but I do not believe it should react this way.

**Comment by jcm93** [comment]
If you're using the Display Capture mode of macOS Screen Capture, I don't think there's any way around this behavior. That mode is designed explicitly to capture whatever is on your display, after all compositing, etc., including Accessibility features. 

You may be able to work around this behavior by using macOS Screen Capture's Window Capture or Application Capture modes, which capture program windows before they are fully composited; their captures should not change when using Accessibility features like magnification.

**Comment by ahmutkadim** [comment]
Most of the programs I tested behaved the same but a little few of them did not so I thought it was about preference or rendering technique of the software. Thanks for your feedback. But I believe rendering each application separately is too much work. I just wish to ask whether this can be fixed with a modification to OBS.

**Comment by gxalpha** [comment]
There is nothing that we are able to modify here in OBS. We use the image that macOS gives us, and that includes the zoom.

Feel free to write a Feedback to Apple via [Feedback Assistant](https://feedbackassistant.apple.com) and suggest them giving developers the option to toggle this.

**Comment by IJEMIN** [comment]
Using different app(Screenflick) but suffering from same issue here. Downgrade macOS to 12 because of this.

**Comment by zxzzz8** [comment]
> There is nothing that we are able to modify here in OBS. We use the image that macOS gives us, and that includes the zoom.
> 
> Feel free to write a Feedback to Apple via [Feedback Assistant](https://feedbackassistant.apple.com) and suggest them giving developers the option to toggle this.

well, i just tried and Feedback Assistant seems to be for Developers or Beta testers only? 
so asking the end-users to ask there is a bit...? XD

so id really appreciate if the OBS Developers make such a request themselves to represent their users requests,
at least it seems thats how apple prefer it given they are blocking regular users from this feedback system?

--

and btw my case is of similar concept but different, for me the recording showing the magnifier effects that follow the mouse around it is extremely important, and until now it also worked fine, but i just updated from Sonoma to Sequoia and it stopped working, the OS screenshots already couldn't grab it for me, and its even more so really tilting now that OBS can't either.

i generally think its something pretty critical or at least natural to be controlled by the user based on the use case, at least the magnifier was extremely useful so far until now when i could still record it, and i think being able to control in the app [or at least somewhere, like in the OS settings] whats being filtered and what not is very vital.

[ _i've also seen the magnifier have other effect like inverted colors etc', not to mention the similarly system overall screen effects like tinting, and to me it would really be nice personally and i'd really appreciated it if the user could set to record "as we see it" or as close as possible to that, but maybe thats too much to ask i guess? = P_ ]

either way, at least the magnifier was extremely useful so far until now when i could still record it in my case, and i really hope i can get that fixed back.

**Comment by stereo3d** [comment]
hello, any news on this issue?

**Comment by sebastian-s-beckmann** [comment]
As far as I'm aware, there is nothing OBS can change to fix this behavior. Please [file a Feedback with Apple](https://feedbackassistant.apple.com/).
