### ISSUE TITLE
Update failed to latest version

### ISSUE THREAD

**Issue by CoderLittleChen** [obsproject/obs-studio#9920]
### Operating System Info

Windows 10

### OBS Studio Version

29.1.3

### OBS Studio Log URL

https://obsproject.com/logs/OZpSVbRsZTtKzmUt

### Expected Behavior

update success

### Current Behavior

![image](https://github.com/obsproject/obs-studio/assets/32502670/555052ce-b56f-4eef-88d4-eca9a69f2dfc)

### Steps to Reproduce

1.start the software
2.current update
3.
...

**Comment by derrod** [comment]
Do these links work for you?

- https://cdn-fastly.obsproject.com/update_studio/stable/core/bin/64bit/obs64.exe.zst
- https://cdn-fastly.obsproject.com/patches_studio/stable/core/bin/64bit/obs64.exe/8f7700e0ae737be2e68b07204f3b13c0553148ed

**Comment by CoderLittleChen** [comment]
Update Successed
