### ISSUE TITLE
QSV encoders not available on Arc A750

### ISSUE THREAD

**Issue by INS4NIt** [obsproject/obs-studio#9921]
### Operating System Info

Ubuntu 22.04

### OBS Studio Version

30.0.0

### OBS Studio Log URL

https://obsproject.com/logs/iyRwcecjD41UwjEM

### Expected Behavior

Settings>Output (Advanced)>Streaming/Recording>Video Encoder should contain an entry for QSV with all relevant codecs

### Current Behavior

Currently only x264, FFmpeg VAAPI (with relevant codecs), and AOM AV1 are available as encoder options

### Steps to Reproduce

Consistent on every OBS launch

### Anything else we should know?

Kernel has been updated to Mainline 6.5.11, although "stock" kernel 6.2.0-37.38 behaved the same way
Mesa has been updated to latest available Kisak release (23.2.1), although "stock" Ubuntu Mesa version behaved the same way

**Comment by kkartaltepe** [comment]
We do not use GitHub Issues for support questions, for help configuring your system:

Please use the [Discord server](https://obsproject.com/discord) or the [forums](https://obsproject.com/forum).
