### ISSUE TITLE
OBS compiled for Portable opening and config problems

### ISSUE THREAD

**Issue by msmafra** [obsproject/obs-studio#9922]
### Operating System Info

Other

### Other OS

Fedora 39

### OBS Studio Version

30.0.0

### OBS Studio Log URL

no url - is not opening

### Expected Behavior

After successfully compiling, for ti to open and store its configurations inside the same folder.

### Current Behavior

It opens once. If it is in $HOME it tries to create a config folder in ../../. If I move it to something like $HOME/Downloads/apps it opens only once. After closing it won't finish opening:

```
❯ ~/Downloads/Apps-etc/obs-studio-portable-qt6/bin/64bit/obs
debug: Found portal inhibitor
debug: Attempted path: ../../data/obs-studio/locale/en-US.ini
debug: Attempted path: ../../data/obs-studio/locale/en-US.ini
error: Failed to load locale
info: == Profiler Results =============================
info: run_program_init: 1740.34 ms
info:  ┗OBSApp::AppInit: 1098.87 ms
info:    ┗OBSApp::InitLocale: 1098.63 ms
info: =================================================
info: == Profiler Time Between Calls ==================
info: =================================================
info: Number of memory leaks: 1

~
❯ ~/Downloads/Apps-etc/obs-studio-portable-qt6/bin/64bit/obs --portable
debug: Found portal inhibitor
error: Failed to create required user directories
info: == Profiler Results =============================
info: run_program_init: 15583.4 ms
info:  ┗OBSApp::AppInit: 10620.1 ms
info: =================================================
info: == Profiler Time Between Calls ==================
info: =================================================
info: Number of memory leaks: 1
```

### Steps to Reproduce

1. Compile it, successfully, on Fedora workstation
2. Open it from $HOME/obs-portable
3. Open it from $HOME/some-folder/some-other-folder/obs-portable
4. I won't open on the first path, and will open only once on the second.
[2023-11-26 16-30-06.txt](https://github.com/obsproject/obs-studio/files/13467900/2023-11-26.16-30-06.txt)

...

### Anything else we should know?

Build parameters

  project_folder="${HOME}/Projects/obs-studio"
  build_folder="${project_folder}/build"
  qtver="${1}"
  install_prefix="${HOME}/Downloads/App-etc/obs-studio-portable-qt${qtver}"
  cef_location="${HOME}/Projects/cef_binary_5060_linux64"
  npu="$(nproc)"
  ld_so_conf="/etc/ld.so.conf.d/local.conf"
  local_lib="/usr/local/lib"

  cmake -DLINUX_PORTABLE=ON -DCMAKE_INSTALL_PREFIX="${install_prefix}" \
    -DENABLE_BROWSER=ON -DCEF_ROOT_DIR="${cef_location}" -DENABLE_AJA=OFF \
    -DENABLE_NEW_MPEGTS_OUTPUT=OFF -DQT_VERSION="${qtver}" \
    -DENABLE_PIPEWIRE=ON -DBROWSER_PANEL_SUPPORT_ENABLED=TRUE ..

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by Fenrirthviti** [comment]
Looks like you did not have permissions to write to the portable directory.

`error: Failed to create required user directories`

**Comment by msmafra** [comment]
> Looks like you did not have permissions to write to the portable directory.
> 
> `error: Failed to create required user directories`

It my user folder and I'm the only user. And its looking for configurations outside its folder. Which I think is a mistake since is portable.

**Comment by Fenrirthviti** [comment]
Make sure you compiled with `LINUX_PORTABLE` enabled.

But either way, this is a support question and not a bug report, please use the forums or Discord for further assistance.

**Comment by msmafra** [comment]
> Make sure you compiled with `LINUX_PORTABLE` enabled.
> 
> But either way, this is a support question and not a bug report, please use the forums or Discord for further assistance.

I used it. The parameters I used are in the "Anything else we should know?" section
