### ISSUE TITLE
Browser Source Keeps Crashing on OBS 30

### ISSUE THREAD

**Issue by ENTPRESTIGIOUS** [obsproject/obs-studio#9924]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.0

### OBS Studio Log URL

https://obsproject.com/tools/analyzer?log_url=https%3A%2F%2Fobsproject.com%2Flogs%2FIIarBjUuOJ7sBXnS

### Expected Behavior

The browser source to keep running.

### Current Behavior

The browser source completely disappeared for no reason.

### Steps to Reproduce

1. Create browser source
2. Stream
3. Browser Source magically disappears

### Anything else we should know?

Do you think it can be caused by a plugin?

**Comment by ENTPRESTIGIOUS** [comment]
Just attempted refresh cache

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
