### ISSUE TITLE
Display Capture Main Monitor

### ISSUE THREAD

**Issue by Jason22Douce** [obsproject/obs-studio#9932]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.0

### OBS Studio Log URL

https://obsproject.com/logs/0NOUoNT0LBwWxOx7

### Expected Behavior

when changing the display in display capture to main monitor, the main monitor should be captured. 

### Current Behavior

only secondary monitor is displayed in display capture regardless of changes made. cannot use main monitor for display capture.

### Steps to Reproduce

1.have 2 monitors
2.create display capture
3.try switching from 1 to another in properties, secondary to main monitor
...

### Anything else we should know?

this seems to be an issue for many that I havent seen a fix for yet.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
