### ISSUE TITLE
obs causes computer monitor to freeze

### ISSUE THREAD

**Issue by HoneyAlloy** [obsproject/obs-studio#9940]
### Operating System Info

Windows 11

### OBS Studio Version

30.0.0

### OBS Studio Log URL

https://obsproject.com/logs/2i0IvW8yfIkzKsuO

### Expected Behavior

OBS doesn't have any problems when it's not working

### Current Behavior

When OBS is not working, and without turning it off, after using or leaving the computer for a certain period of time, the computer monitor will suddenly experience severe freezes, with a frame rate of 5 seconds/frame, and will cause problems with the keyboard and mouse. Wait for the device's response delay to reach about 1 to 2 minutes.
As for why I know that it is not the computer hardware that is lagging but the impact of OBS on the monitor, that is because when I try to use the shortcut keys to play music, the computer can respond to my shortcut keys and play songs as quickly as usual. This operation makes me I believe it's not a problem with my computer, but something caused by some software.
Because OBS was always on when recording videos many times before or paused during screen recording, I thought it was OBS that caused my computer monitor to freeze.
Sure enough, it took me about 10 minutes to move my mouse pointer very slowly to the OBS window and close OBS. Finally, the computer monitor returned to normal and the computer no longer lags.
I decided to report on this issue.

### Steps to Reproduce

I'm not sure if other people will encounter the same problem I had when using it.
1.Open OBS
2.Leave OBS alone for a period of time, without recording the screen, or pause while recording the screen and then leave it alone (not sure how long, because the time between opening OBS and freezing is different each time.
3.Then the computer monitor will become very laggy
...

**Comment by HoneyAlloy** [comment]
thanks, let me try.

**Comment by gxalpha** [comment]
@HoneyAlloy have you had a chance to update and re-test?

**Comment by HoneyAlloy** [comment]
I'm very sorry for the late reply. I have updated the driver and this problem has been solved. Thank you very much!

**Comment by gxalpha** [comment]
Alright, I'll go ahead and close the issue then.
