### ISSUE TITLE
OBS crashes when not started in safe mode

### ISSUE THREAD

**Issue by phako** [obsproject/obs-studio#9951]
### Operating System Info

Other

### Other OS

Fedora 39

### OBS Studio Version

30.0.0

### OBS Studio Version (Other)

Installed from Flathub

### OBS Studio Log URL

https://obsproject.com/logs/6lWGwwa3iMwBDona

### Expected Behavior

Should start without problems

### Current Behavior

Crashes right away before starting

Backtrace:
```
(gdb) bt
#0  QtWaylandClient::QWaylandAbstractDecoration::update() (this=0x0) at /run/build-runtime/qt6-wayland/src/client/qwaylandabstractdecoration.cpp:110
#1  0x00007fff9c057a4a in QAdwaitaDecorations::forceRepaint() (this=0x55555812ff80) at /run/build/qadwaitadecorations/src/qadwaitadecorations.cpp:698
#2  0x00007fff9c05ac12 in QAdwaitaDecorations::initConfiguration() (this=0x55555812ff80) at /run/build/qadwaitadecorations/src/qadwaitadecorations.cpp:157
#3  0x00007ffff47a4553 in QObject::event(QEvent*) (this=0x55555812ff80, e=0x5555564b73d0) at /run/build-runtime/qt6-qtbase/src/corelib/kernel/qobject.cpp:1438
#4  0x00007ffff5799a78 in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=<optimized out>, receiver=0x55555812ff80, e=0x5555564b73d0) at /run/build-runtime/qt6-qtbase/src/widgets/kernel/qapplication.cpp:3290
#5  0x00007ffff4751ce8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x55555812ff80, event=0x5555564b73d0) at /run/build-runtime/qt6-qtbase/src/corelib/kernel/qcoreapplication.cpp:1118
#6  0x00007ffff4755397 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) (receiver=0x0, event_type=0, data=0x555555ae8720) at /run/build-runtime/qt6-qtbase/src/corelib/kernel/qcoreapplication.cpp:1898
#7  0x000055555570de61 in OBSBasic::ClearSceneData() (this=0x555555f6a510) at /run/build/obs/UI/window-basic-main.cpp:4972
#8  0x000055555570e699 in OBSBasic::LoadData(obs_data*, char const*) (this=0x555555f6a510, data=0x555557c9f340, file=0x7fffffffcb20 "/home/jgeorg/.var/app/com.obsproject.Studio/config/obs-studio/basic/scenes/Code_Streaming.json")
    at /run/build/obs/UI/window-basic-main.cpp:1104
#9  0x000055555572a683 in OBSBasic::OBSInit() (this=<optimized out>) at /run/build/obs/UI/window-basic-main.cpp:2100
#10 0x000055555563d15b in OBSApp::OBSInit() (this=0x7fffffffd8b0) at /run/build/obs/UI/obs-app.cpp:1740
#11 0x000055555560fa3e in run_program (argv=0x7fffffffe0d8, argc=<optimized out>, logFile=...) at /run/build/obs/UI/obs-app.cpp:2578
#12 main(int, char**) (argc=<optimized out>, argv=0x7fffffffe0d8) at /run/build/obs/UI/obs-app.cpp:3450
```

### Steps to Reproduce

1. Install OBS from flathub
2. Run

### Anything else we should know?

I can work around this by either starting in safe mode or removing org.kde.WaylandDecoration.QAdwaitaDecorations extension

**Comment by tytan652** [comment]
We only support bradient decorations (defaults of Qt), forced-provided decorations (e.g. Fedora-Qt's QAdwaita/QGnome) are not supported.

**Comment by tytan652** [comment]
I forgot to mention, report this issue to the decoration developer.

**Comment by phako** [comment]
Thanks. This is somehow dragged in by the flatpak (at least it complains if I remove it that OBS recommends it)? Can you point me to what safe mode disables for further debugging?

**Comment by tytan652** [comment]
> This is somehow dragged in by the flatpak (at least it complains if I remove it that OBS recommends it)?

FedoraQt somehow made KDE "force" its installation on GNOME for any Flatpak apps relying on the KDE Plarform (which provides Qt).
Which is pretty bad, Adwaita-like decoration for Qt apps are literally waste of space.
It just encumber the "Qt apps on GNOME" experience, and you reported that it can make those apps crash.

> Can you point me to what safe mode disables for further debugging?

https://github.com/obsproject/obs-studio/releases/tag/30.0.0
> - Added a "Safe Mode" that runs OBS without third-party plugins, scripting, and websockets [derrod]
>   - When OBS detects that it was not shut down properly it will offer the user the option to launch in Safe Mode for troubleshooting purposes. It can also be manually activated via the "Help" menu.

**Comment by phako** [comment]
Thanks again.
