### ISSUE TITLE
Url source stopped working

### ISSUE THREAD

**Issue by cphgamer** [obsproject/obs-studio#9952]
### Operating System Info

Windows 10

### OBS Studio Version

30.0.0

### OBS Studio Log URL

https://obsproject.com/logs/OkM1i9ghLPOmVBpB

### Expected Behavior

Expected it would still show my URL's from Streamelements. 

### Current Behavior

It worked this morning and **now none of the URL's are showing up**. I can see them in a normal Chrome session. 

** EDIT** Twitch URL source (Goal widget) are working / showing up, but Streamelements not (remember, it works in any normal browser)

### Steps to Reproduce

1. I didn't do anything in OBS.
2. Windows 10 updated this morning, but it worked a while after that.

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!
