### ISSUE TITLE
Stutter in OBS (on macOS)

### ISSUE THREAD

**Issue by fallenlonelie** [obsproject/obs-studio#9966]
### Operating System Info

macOS 14

### OBS Studio Version

30.0.0

### OBS Studio Log URL

https://drive.google.com/file/d/13NSWImVmlQdDdvsu8ePHnQlJhoziNDi2/view?usp=sharing

### Expected Behavior

Recordings should be made without stuttering regardless of conditions.

### Current Behavior

OBS has an unknown stuttering on macOS.

The screen of the game console was recorded at 1080p@60hz using the capture card,
If shown main window, stuttering occurs in the chart scroll in rhythm game.
As look this: https://youtu.be/q9jeRiP5H_Q

If I open the "window projector (preview)", the above problem will not stutter even the same settings.
As look this: https://youtu.be/vxj9OzDRvxQ

System specifications were tested in the following specifications and symptoms were the same.
1. Intel Xeon 2690v4 / Asus X99-A / 64GB 2400Mhz ECC / RX 6600 / MOTU M2 / ATURIA MINIFUSE2 / macOS 14.1.2
2. i5 10400F / MSI B460M-A Pro / 32GB 3200Mhz / RX 6600 / macOS 14.1.2

### Steps to Reproduce

1. It stuttered when record a fast-changing game (ex: rhythm game) with a capture card.
2. It does not occur when you open the window projector (preview).

### Anything else we should know?

It doesn't seem to be a problem with system specifications or settings.
Results vary depending on whether the window projector (preview) is opened in the same environment and settings.

----

A few additional confirmations.
1. Stuttering was resolved when the window projector (preview) was made full screen through Space manager.
2.  Make to OBS window to a minimum has resolved stuttering.
3. Turning off a preview on OBS (main window) did not resolve stuttering.

**Comment by PatTheMav** [comment]
The second capture definitely also has some stuttering, albeit not as severe as the first example.

Please add a proper OBS Studio log from a recording session to the opening post (you can use the built-in log uploader which generates a URL for you that you can paste here). You need to also fully close OBS before uploading the log so we can look at some important metrics that are not written to the log otherwise.

Please also reduce the scene collection to an absolute minimum (e.g. just the capture card, nothing else) for this.

**Comment by fallenlonelie** [comment]
The first and second stutters are a huge difference.
Is it the only solution to erase all other sources and scenes, leaving only a certain source?
Doesn't that sound ridiculous?

**Comment by PatTheMav** [comment]
> The first and second stutters are a huge difference. Is it the only solution to erase all other sources and scenes, leaving only a certain source? Doesn't that sound ridiculous?

On the contrary - it is well-established good practice to eliminate as many factors as possible to isolate a problem and in the case of OBS any filter, transition, plugin, or other sources, can influence an issue.

You are of course very welcome to debug this issue locally on your machine as you see fit and open a PR with an appropriate bug fix.

**Comment by gxalpha** [comment]
These systems are running hardware which macOS is not made or tested for. We cannot debug or provide fixes for those.
> Intel Xeon 2690v4 / Asus X99-A / 64GB 2400Mhz ECC / RX 6600 / MOTU M2 / ATURIA MINIFUSE2 / macOS 14.1.2
i5 10400F / MSI B460M-A Pro / 32GB 3200Mhz / RX 6600 / macOS 14.1.2
