### ISSUE TITLE
Window capture priority title then class not working

### ISSUE THREAD

**Issue by CodeYan01** [obsproject/obs-studio#9976]
### Operating System Info

Windows 10

### OBS Studio Version

30.0.0

### OBS Studio Log URL

https://obsproject.com/logs/GPAeGpOZpJGN4jeu

### Expected Behavior

When I restart obs, it should select the same window because it has the same class name.

### Current Behavior

When I restart obs, it does not select a window and is just a black screen. 

### Steps to Reproduce

1. New scene collection
2. Open Brave browser.
3. Add window capture, set to Windows 10 capture (just so we can isolate this). Select the browser.
4. Go to a different tab so window title changes.
5. Verify that the source still captures.
6. Restart OBS. Window capture doesn't capture.
7. Switch window capture priority to title then exe. It will capture.
8. You can do the same test with the title then exe priority and it will work as expected. 
...

### Anything else we should know?

I checked the scene collection json when i selected both tabs. They had the same window class name `Chrome_WidgetWin_1`. Oddly i've tried PotPlayer (video player, class name `PotPlayer64`) and Notepad (class name `Notepad`), they worked as expected. But vs code exhibits the issue as well, with the same class name of Brave.

**Comment by CodeYan01** [comment]
i'm debugging through the code and it seems to me that WINDOW_PRIORITY_CLASS and WINDOW_PRIORITY_TITLE are defined in reverse.

**Comment by CodeYan01** [comment]
ah, it's because a class name of Chrome is considered a generic class. instead of falling back to WINDOW_PRIORITY_TITLE, wouldn't it be better to fall back to WINDOW_PRIORITY_EXE? i've seen a few cases in #windows-support having issues with chrome.

**Comment by gxalpha** [comment]
We've looked at this and think this is working as designed, not a bug. The design probably isn't *great*, but the concept of an implicit fallback is somewhat problematic anyways.
We'll probably revisit the entire design in the future.
