### ISSUE TITLE
OBS v30.0.1 for Mac Silicon crashes after fresh install.

### ISSUE THREAD

**Issue by jeffschwartz** [obsproject/obs-studio#9985]
### Operating System Info

Windows 11

### Other OS

n/a

### OBS Studio Version

30.0.0

### OBS Studio Version (Other)

v30.0.1

### OBS Studio Log URL

n/a

### Expected Behavior

Expected OBS not to crash immediate after launching fresh install.

### Current Behavior

OBS crashed upon launching fresh install.

### Steps to Reproduce

1. Install OBS v30.0.1
2. Launch OBS.

### Anything else we should know?

[OBS Studio-2023-12-10-112907.ips.zip](https://github.com/obsproject/obs-studio/files/13628539/OBS.Studio-2023-12-10-112907.ips.zip)

**Comment by tytan652** [comment]
Fixed by #9983
