### ISSUE TITLE
hopefully the media source's playback speed supports higher values

### ISSUE THREAD

**Issue by xiaoli-style** [obsproject/obs-studio#9987]
### Operating System Info

Windows 10

### OBS Studio Version

30.0.0

### OBS Studio Log URL

none

### Expected Behavior

In the properties of the media source, the speed option can be set up to 200%. I hope to support a higher value, such as 1000%.

### Current Behavior

none

### Steps to Reproduce

none

**Comment by xiaoli-style** [comment]
![1](https://github.com/obsproject/obs-studio/assets/35419620/2520f460-7864-44ed-ac2c-f6691f621c43)

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by tt2468** [comment]
Playing back a video file at 10x speed is likely to cause significant system resource usage. As such, the maximum value of this setting will not be changed. If you need a higher speed, you can compile OBS yourself.
