### ISSUE TITLE
CMake configuration

### ISSUE THREAD

**Issue by Samlu718** [obsproject/obs-studio#9988]
### Operating System Info

Windows 10

### OBS Studio Version

30.0.0

### OBS Studio Log URL

-na-

### Expected Behavior

Generate an obs-studio.sln file

### Current Behavior

CMD 
  ******************************************************************************
C:\Users\Samlu\Desktop\obs-studio>cmake --preset windows-x64
Preset CMake variables:

  ENABLE_BROWSER:BOOL="TRUE"
  ENABLE_CCACHE:BOOL="FALSE"
  GPU_PRIORITY_VAL:STRING=""
  OBS_CMAKE_VERSION:STRING="3.0.0"
  RESTREAM_CLIENTID:STRING=""
  RESTREAM_HASH:STRING=""
  TWITCH_CLIENTID:STRING=""
  TWITCH_HASH:STRING=""
  VIRTUALCAM_GUID:STRING="A3FCE0F5-3493-419F-958A-ABA1250EC20B"
  YOUTUBE_CLIENTID:STRING=""
  YOUTUBE_CLIENTID_HASH:STRING=""
  YOUTUBE_SECRET:STRING=""
  YOUTUBE_SECRET_HASH:STRING=""

CMake Warning (dev) at cmake/common/versionconfig.cmake:52 (message):

  ******************************************************************************

    + OBS-Studio - Release candidate detected, OBS_VERSION is now: 30.0.0-rc1-121-gf674d1716

  ******************************************************************************
Call Stack (most recent call first):
  cmake/common/bootstrap.cmake:60 (include)
  CMakeLists.txt:4 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19044.
-- The C compiler identification is MSVC 19.38.33133.0
-- The CXX compiler identification is MSVC 19.38.33133.0
  ******************************************************************************

### Steps to Reproduce

1.Clone the repository including submodules:
   git clone --recursive https://github.com/obsproject/obs-studio.git

2.Set current directory to obs-studio

3.Check available CMake presets: cmake --list-presets

4.Select the windows-x64 preset: cmake --preset windows-x64

**Comment by WizardCM** [comment]
There are no errors in that cmake log. Please instead use our [Discord server](https://obsproject.com/discord)'s #development channel to troubleshoot your issue..

**Comment by Samlu718** [comment]
I've been inquiring on the #development channel of the Discord server for two days, but no one has responded to my messages. I would like to know why I'm getting the same result when using both the new build system and Legacy Build Instructions For Windows. I am unable to generate the obs-studio.sln file. What could be the reason for this situation?

**Comment by Fenrirthviti** [comment]
I have checked the chat history in #development on our discord, and see no messages from you asking for help. Are you sure you joined the correct server?

https://obsproject.com/discord

**Comment by Samlu718** [comment]
![image](https://github.com/obsproject/obs-studio/assets/112963090/3f23e254-f40d-43a2-8a56-7c407c02e6f8)


It's right here, right?

**Comment by RytoEX** [comment]
```
CMake Warning (dev) at cmake/common/versionconfig.cmake:52 (message):

+ OBS-Studio - Release candidate detected, OBS_VERSION is now: 30.0.0-rc1-121-gf674d1716
```

This is a non-fatal warning. It is not an error and does not prevent building. There are no CMake errors (specifically _errors_, not warnings), in the excerpt that you posted, so we cannot provide additional insight.

**Comment by Samlu718** [comment]
[cmake_log.txt](https://github.com/obsproject/obs-studio/files/13852753/cmake_log.txt)
[CMakeLists.txt](https://github.com/obsproject/obs-studio/files/13852754/CMakeLists.txt)

**Comment by RytoEX** [comment]
> [cmake_log.txt](https://github.com/obsproject/obs-studio/files/13852753/cmake_log.txt) [CMakeLists.txt](https://github.com/obsproject/obs-studio/files/13852754/CMakeLists.txt)
> 
> Is this cmake log what you need?

Something in your CMake invocation is causing it to look at the parent directory, which correctly has no CMakeLists.txt file. It seems like you are trying to pass `..` somewhere in your CMake invocation, and CMake tries to ignore it, but ends up checking it anyway.

The steps to reproduce you listed should not by themselves result in this error. Please note that you would invoke CMake commands from within Windows PowerShell 7 or Windows Terminal, not Git Bash. It may also help to place the obs-studio repo in a path with only ANSI/non-Unicode characters.

For further assistance, please use our [Discord server](https://obsproject.com/discord)'s #development channel to troubleshoot your issue.
