### ISSUE TITLE
OBS crashes on startup if websocket request comes too fast after connection

### ISSUE THREAD

**Issue by frogeater** [obsproject/obs-studio#9991]
### Operating System Info

Windows 10

### OBS Studio Version

30.0.0

### OBS Studio Log URL

https://obsproject.com/logs/suq6O9XSUNIyGMAe

### OBS Studio Crash Log URL

https://obsproject.com/logs/ObUgYLE89zVXKpfS

### Expected Behavior

no crash

### Current Behavior

crash

### Steps to Reproduce

1.External program tries connection to websocket priodically
2.OBS is started
3.External program websocket connection succeeds
4.External program sends immediatly GetCurrentSceneCollection request
5.OBS crashes ; UI is not opened

**Comment by SuslikV** [comment]
On the forum there are threads that has similar crash logs including crashes on both startup and close of OBS (OBS v30.0.2 and Win11).
https://obsproject.com/forum/threads/obs-crash-on-start-up-randomly.171721/
https://obsproject.com/forum/threads/obs-crashing.171772/

**Comment by notr1ch** [comment]
It looks like obs-websocket assumes the system tray will always exist, which isn't the case on startup (it's created after scene data is loaded). I guess we could move the systray init code earlier, but obs-websocket should also be checking the API response.

**Comment by SuslikV** [comment]
@notr1ch just to clarify app behavior, in my tests it crashes on close when tray is disabled in OBS settings.

**Comment by frogeater** [comment]
Just to clarify.
If OBS is started first there is no crash never.
Crash happens only if application is started first.
The application uses BarRaider module obs-websocket-dotnet [https://github.com/BarRaider/obs-websocket-dotnet]
Most probably OBS is not ready when obs-websocket starts accepting requests.

**Comment by frogeater** [comment]
The issue is not fixed on version 5.4.2.
