### ISSUE TITLE
Crashes Immediately upon opening. Cannot run Safe Mode

### ISSUE THREAD

**Issue by MoRpH3uSYT** [obsproject/obs-studio#9992]
### Operating System Info

macOS 14

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.0.2

### OBS Studio Log URL

Can't, won't open

### Expected Behavior

OBS Opens

### Current Behavior

OBS doesn't open

### Steps to Reproduce

1. Open OBS
2. OBS Doesn't open

**Comment by MoRpH3uSYT** [comment]
Diagnostics reports are not selectable when I attempt to use the "Paste, drop or click to add files" 

Get an error:
We don’t support that file type.
Try again with GIF, JPEG, JPG, MOV, MP4, PNG, SVG, WEBM, CPUPROFILE, CSV, DMP, DOCX, FODG, FODP, FODS, FODT, GZ, JSON, JSONC, LOG, MD, ODF, ODG, ODP, ODS, ODT, PATCH, PDF, PPTX, TGZ, TXT, XLS, XLSX or ZIP.

How should I go about uploading?

**Comment by gxalpha** [comment]
Either compress as a ZIP file (Right click -> Compress) or add ".txt" to the file name (make sure you have file extensions turned on in Finder).

**Comment by MoRpH3uSYT** [comment]
[OBS Studio-2023-12-11-092511.txt](https://github.com/obsproject/obs-studio/files/13639747/OBS.Studio-2023-12-11-092511.txt)

Also started immediately after I updated OBS this morning to 30.0.2

**Comment by gxalpha** [comment]
This crash report is from 30.0.1. Please go to https://obsproject.com/download to download 30.0.2 and install that instead of 30.0.1.

**Comment by MoRpH3uSYT** [comment]
That's very strange as I did update this morning and it went sideways. But thank you!
