### ISSUE TITLE
recording did not stop in a timely manner

### ISSUE THREAD

**Issue by whirlicote** [obsproject/obs-studio#9995]
### Operating System Info

Windows 10

### OBS Studio Version

30.0.0

### OBS Studio Log URL

https://obsproject.com/logs/ruxOyfX4JMnij31a

### OBS Studio Crash Log URL

https://obsproject.com/logs/VvvEhfOAFEs7P5Z7

### Expected Behavior

program isolates faulty components and aborts action in case of error

### Current Behavior

the freeze affected the whole program to crash

### Steps to Reproduce

1. heavy load I assume
2. stop button wont stop. even waiting several minutes does not help
3. application warns/refuses to properly close when X in window bar is pressed
4. closing laptop lid might have interfered
5. removing external hard drive by accident at some later point in time might have interfered

### Anything else we should know?

some older crash report

https://obsproject.com/logs/2f5DrIrpMZzAs4VJ

**Comment by RytoEX** [comment]
The older crash report is for a different crash and is not relevant to the Issue described above.

> closing laptop lid might have interfered
> removing external hard drive by accident at some later point in time might have interfered

Did you close the laptop lid while the recording was paused? Did you remove the external hard drive while the recording was paused?

**Comment by whirlicote** [comment]
I closed the lid after i already closed the window. I believe i removed the external hard drive after i closed the lid.

I am not sure if the recording was paused when I tried to stop the recording.
It might be possible that i tried to stop the recording while it was still paused. But i think its unlikely.

When I tried/closed the window it complained that some recording was still ongoing.

Now that i think about it I am not so sure anymore if I confirmed the closing of the window. It might be possible that i tried to give it some more time with the lid closed.

**Comment by Fenrirthviti** [comment]
It sounds like that this happened just once during a set of actions that are not expected to work or supported, and is not actually reproducible. If you can come up with a set of reliable reproduction steps that we can proper test/investigate instead of "I think" or "not sure" we can reopen. It's important to keep in mind that we can't investigate or test without due diligence on reporting an issue. Thanks for understanding!

**Comment by whirlicote** [comment]
> It sounds like that this happened just once during a set of actions that are not expected to work or supported

I have two use cases in mind:

Use case I: Starting a screen recording. Stopping a screen recording. Starting a second screen recording without killing the application in the Task Manager.
Use case II: Starting a screen recording. Pausing a screen recording. Resuming a screen recording: The output file gets written to again.

> and is not actually reproducible.

I did several recordings, that triggered the behavior. About 3 out of 5 recordings trigger the behavior.


One recording was rather short. In this particular recording no undesired behavior was triggered.

When the recording gets longer than 2 to 3 minutes the probability increases that the recording does not stop anymore. The window stays unresponsive even after several minutes. The GPU usage is constantly around 38.1%.

When I press the pause button the output file is never written to again even after resuming and pausing several times.


> If you can come up with a set of reliable reproduction steps that we can proper test/investigate instead of "I think" or "not sure" we can reopen. It's important to keep in mind that we can't investigate or test without due diligence on reporting an issue.

I try my best to provide you with all the necessary information. Unfortunately I currently do not have the time to come up with lots of due diligence that may not be relevant. The concrete steps I am doing are starting recording and stopping recording. The condition is triggered more often when i do use the pause and resume button over longer periods of time.

What can I do to give you more reliable reproduction steps?
