### ISSUE TITLE
Encoding Issue Since Update

### ISSUE THREAD

**Issue by MoRpH3uSYT** [obsproject/obs-studio#9997]
### Operating System Info

macOS 14

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.0.2

### OBS Studio Log URL

https://obsproject.com/logs/XO2fY6ykksQSbUb8

### Expected Behavior

OBA to function as intended

### Current Behavior

Encoding issues the entire time. Stream and recording are a choppy mess.

### Steps to Reproduce

1. Start Stream
2. Start Recording

### Anything else we should know?

Started after 30.0.2 update

**Comment by Fenrirthviti** [comment]
This sounds more likely to be a support request rather than a bug report, and we are not currently accepting support requests on GitHub Issues. Please use our [forums](https://obsproject.com/forum/) or [Discord](https://obsproject.com/discord/) for assistance.

Thank you!

**Comment by MoRpH3uSYT** [comment]
I can't. It says I don't have privileges to contribute to the forum
